### ISSUE TITLE
kupfer does not build

### ISSUE THREAD

**Issue by luxferresum** [NixOS/nixpkgs#100036]
**Describe the bug**
When building kupfer it errors with

```
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "/nix/store/l0pzd5jxgg6hj23si7kf3cp9cpkj3r96-python3-3.6.12/lib/python3.6/tokenize.py", line 452, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
builder for '/nix/store/dvn4b4lybpjy69izbf66f8yv4ada3vn4-kupfer-319.drv' failed with exit code 1
error: build of '/nix/store/dvn4b4lybpjy69izbf66f8yv4ada3vn4-kupfer-319.drv' failed
```

**To Reproduce**
run `nix-build -A kupfer` on the `nixpkgs` repo

**Expected behavior**
It should build kupfer

**Notify maintainers**
@cobbal

**Metadata**
```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/rlknkw60sngvky1rkrdws0qik3scjcln-bash-interactive-4.4-p23-dev
copying path '/nix/store/rlknkw60sngvky1rkrdws0qik3scjcln-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.69, NixOS, 20.09.git.7badbf18c45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/var/src/nixpkgs`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by avdv** [comment]
This was likely already fixed by https://github.com/NixOS/nixpkgs/commit/dfb9e8689dfbe633f6f7ac579f89593ab0a0368b (can't find a PR for this though)
