### ISSUE TITLE
ihaskell fails at startup

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#10074]
This is my log:

```
Sep 26 14:38:54 katara bash[23809]: ihaskell:
Sep 26 14:38:54 katara bash[23809]: Ran commands:
Sep 26 14:38:54 katara bash[23809]: which jupyter
Sep 26 14:38:54 katara bash[23809]: which ipython
Sep 26 14:38:54 katara bash[23809]: /nix/store/z49mh0ivxwlwnn4hqhd21xizpg1la7nv-python2.7-ipython-4.0.0/bin/ipython --version
Sep 26 14:38:54 katara bash[23809]: which /nix/store/z49mh0ivxwlwnn4hqhd21xizpg1la7nv-python2.7-ipython-4.0.0/bin/ipython
Sep 26 14:38:54 katara bash[23809]: withTmpDir
Sep 26 14:38:54 katara bash[23809]: rm -f /tmp/tmpThreadId41804289383846930886
Sep 26 14:38:54 katara bash[23809]: mkdir /tmp/tmpThreadId41804289383846930886
Sep 26 14:38:54 katara bash[23809]: mkdir -p /tmp/tmpThreadId41804289383846930886/haskell
Sep 26 14:38:54 katara bash[23809]: writefile /tmp/tmpThreadId41804289383846930886/haskell/kernel.json
Sep 26 14:38:54 katara bash[23809]: cp /nix/store/sjay5j8f3iiblkwlszknzr3y7iidh69r-ihaskell-0.8.0.0/share/x86_64-linux-ghc-7.10.2/ihaskell-0.8.0.0/html/kernel.js /tmp/tmpThreadId41804289383846930886/haskell/kernel.js
Sep 26 14:38:54 katara bash[23809]: cp /nix/store/sjay5j8f3iiblkwlszknzr3y7iidh69r-ihaskell-0.8.0.0/share/x86_64-linux-ghc-7.10.2/ihaskell-0.8.0.0/html/logo-64x64.png /tmp/tmpThreadId41804289383846930886/haskell/logo-64x64.png
Sep 26 14:38:54 katara bash[23809]: which ipython
Sep 26 14:38:54 katara bash[23809]: /nix/store/z49mh0ivxwlwnn4hqhd21xizpg1la7nv-python2.7-ipython-4.0.0/bin/ipython kernelspec install --user /tmp/tmpThreadId41804289383846930886/haskell --replace
Sep 26 14:38:54 katara bash[23809]: which /nix/store/z49mh0ivxwlwnn4hqhd21xizpg1la7nv-python2.7-ipython-4.0.0/bin/ipython
Sep 26 14:38:54 katara bash[23809]: rm -rf /tmp/tmpThreadId41804289383846930886
Sep 26 14:38:54 katara bash[23809]: Exception: error running: /nix/store/z49mh0ivxwlwnn4hqhd21xizpg1la7nv-python2.7-ipython-4.0.0/bin/ipython kernelspec install --user /tmp/tmpThreadId41804289383846930886/haskell --replace
Sep 26 14:38:54 katara bash[23809]: exit status: 1
Sep 26 14:38:54 katara bash[23809]: stderr: Traceback (most recent call last):
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/z49mh0ivxwlwnn4hqhd21xizpg1la7nv-python2.7-ipython-4.0.0/bin/.ipython-wrapped", line 10, in <module>
Sep 26 14:38:54 katara bash[23809]: load_entry_point('ipython==4.0.0', 'console_scripts', 'ipython')()
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/z49mh0ivxwlwnn4hqhd21xizpg1la7nv-python2.7-ipython-4.0.0/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
Sep 26 14:38:54 katara bash[23809]: return launch_new_instance(argv=argv, **kwargs)
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/fbd4wcwhyl8iq6p853zj75yq4av3bhmq-python2.7-traitlets-4.0.0/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
Sep 26 14:38:54 katara bash[23809]: app.initialize(argv)
Sep 26 14:38:54 katara bash[23809]: File "<string>", line 2, in initialize
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/fbd4wcwhyl8iq6p853zj75yq4av3bhmq-python2.7-traitlets-4.0.0/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
Sep 26 14:38:54 katara bash[23809]: return method(app, *args, **kwargs)
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/z49mh0ivxwlwnn4hqhd21xizpg1la7nv-python2.7-ipython-4.0.0/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
Sep 26 14:38:54 katara bash[23809]: super(TerminalIPythonApp, self).initialize(argv)
Sep 26 14:38:54 katara bash[23809]: File "<string>", line 2, in initialize
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/fbd4wcwhyl8iq6p853zj75yq4av3bhmq-python2.7-traitlets-4.0.0/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
Sep 26 14:38:54 katara bash[23809]: return method(app, *args, **kwargs)
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/z49mh0ivxwlwnn4hqhd21xizpg1la7nv-python2.7-ipython-4.0.0/lib/python2.7/site-packages/IPython/core/application.py", line 386, in initialize
Sep 26 14:38:54 katara bash[23809]: self.parse_command_line(argv)
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/z49mh0ivxwlwnn4hqhd21xizpg1la7nv-python2.7-ipython-4.0.0/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
Sep 26 14:38:54 katara bash[23809]: return super(TerminalIPythonApp, self).parse_command_line(argv)
Sep 26 14:38:54 katara bash[23809]: File "<string>", line 2, in parse_command_line
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/fbd4wcwhyl8iq6p853zj75yq4av3bhmq-python2.7-traitlets-4.0.0/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
Sep 26 14:38:54 katara bash[23809]: return method(app, *args, **kwargs)
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/fbd4wcwhyl8iq6p853zj75yq4av3bhmq-python2.7-traitlets-4.0.0/lib/python2.7/site-packages/traitlets/config/application.py", line 487, in parse_command_line
Sep 26 14:38:54 katara bash[23809]: return self.initialize_subcommand(subc, subargv)
Sep 26 14:38:54 katara bash[23809]: File "<string>", line 2, in initialize_subcommand
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/fbd4wcwhyl8iq6p853zj75yq4av3bhmq-python2.7-traitlets-4.0.0/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
Sep 26 14:38:54 katara bash[23809]: return method(app, *args, **kwargs)
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/fbd4wcwhyl8iq6p853zj75yq4av3bhmq-python2.7-traitlets-4.0.0/lib/python2.7/site-packages/traitlets/config/application.py", line 418, in initialize_subcommand
Sep 26 14:38:54 katara bash[23809]: subapp = import_item(subapp)
Sep 26 14:38:54 katara bash[23809]: File "/nix/store/q55vjaam9cv78xf10mlj2smwai7psx14-python2.7-ipython_genutils-0.1.0/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
Sep 26 14:38:54 katara bash[23809]: module = __import__(package, fromlist=[obj])
Sep 26 14:38:54 katara bash[23809]: ImportError: No module named jupyter_client.kernelspecapp
Sep 26 14:38:54 katara systemd[1]: ihaskell.service: main process exited, code=exited, status=1/FAILURE
Sep 26 14:38:54 katara systemd[1]: Unit ihaskell.service entered failed state.
Sep 26 14:38:54 katara systemd[1]: ihaskell.service failed.
```

cc @edwtjo

**Comment by edwtjo** [comment]
Thanks for the report, lookin into it

**Comment by FRidh** [comment]
This is because in #9254 I updated IPython/Jupyter to 4.0. From that point on ihaskell should depend on jupyter or the notebook package (not entirely sure which, I'm sure the docs of ihaskell would say) instead of the ipython package.

**Comment by edwtjo** [comment]
@FRidh I know, I'm considering whether to keep an older ipython version for ihaskell since its support for 4.0.0 seems unstable.

**Comment by edwtjo** [comment]
Nope, I missread a couple of error messages.. Fixed in 7cef1a4150a799d5a4ca3f1c42d0ac8d55fed1f9

**Comment by Profpatsch** [comment]
I’m sorry, but no.

```
Sep 28 11:46:17 katara systemd[1]: Starting IHaskell notebook instance...
Sep 28 11:46:17 katara systemd[1]: Started IHaskell notebook instance.
Sep 28 11:46:18 katara bash[26423]: No Jupyter / IPython detected -- install Jupyter 3.0+ before using IHaskell.
Sep 28 11:46:18 katara bash[26423]: ihaskell:
Sep 28 11:46:18 katara bash[26423]: Ran commands:
Sep 28 11:46:18 katara bash[26423]: which jupyter
Sep 28 11:46:18 katara bash[26423]: which ipython
Sep 28 11:46:18 katara bash[26423]: Exception: ExitFailure 1
Sep 28 11:46:18 katara systemd[1]: ihaskell.service: main process exited, code=exited, status=1/FAILURE
Sep 28 11:46:18 katara systemd[1]: Unit ihaskell.service entered failed state.
Sep 28 11:46:18 katara systemd[1]: ihaskell.service failed.
```

**Comment by Profpatsch** [comment]
Added `jupyter_core` to the propagatedBuildInputs:

```
Sep 28 11:52:30 katara bash[28716]: ihaskell:
Sep 28 11:52:30 katara bash[28716]: Ran commands:
Sep 28 11:52:30 katara bash[28716]: which jupyter
Sep 28 11:52:30 katara bash[28716]: which jupyter
Sep 28 11:52:30 katara bash[28716]: /nix/store/9g90rw5kmnmjq1lglpb1ix60njm22hba-ipython-faux-environment/bin/jupyter --version
Sep 28 11:52:30 katara bash[28716]: which /nix/store/9g90rw5kmnmjq1lglpb1ix60njm22hba-ipython-faux-environment/bin/jupyter
Sep 28 11:52:30 katara bash[28716]: withTmpDir
Sep 28 11:52:30 katara bash[28716]: rm -f /tmp/tmpThreadId41804289383846930886
Sep 28 11:52:30 katara bash[28716]: mkdir /tmp/tmpThreadId41804289383846930886
Sep 28 11:52:30 katara bash[28716]: mkdir -p /tmp/tmpThreadId41804289383846930886/haskell
Sep 28 11:52:30 katara bash[28716]: writefile /tmp/tmpThreadId41804289383846930886/haskell/kernel.json
Sep 28 11:52:30 katara bash[28716]: cp /nix/store/sjay5j8f3iiblkwlszknzr3y7iidh69r-ihaskell-0.8.0.0/share/x86_64-linux-ghc-7.10.2/ihaskell-0.8.0.0/html/kernel.js /tmp/tmpThreadId41804289383846930886/haskell/kernel.js
Sep 28 11:52:30 katara bash[28716]: cp /nix/store/sjay5j8f3iiblkwlszknzr3y7iidh69r-ihaskell-0.8.0.0/share/x86_64-linux-ghc-7.10.2/ihaskell-0.8.0.0/html/logo-64x64.png /tmp/tmpThreadId41804289383846930886/haskell/logo-64x64.png
Sep 28 11:52:30 katara bash[28716]: which ipython
Sep 28 11:52:30 katara bash[28716]: rm -rf /tmp/tmpThreadId41804289383846930886
Sep 28 11:52:30 katara bash[28716]: Exception: user error (Pattern match failure in do expression at src/IHaskell/IPython.hs:204:5-16)
Sep 28 11:52:30 katara systemd[1]: ihaskell.service: main process exited, code=exited, status=1/FAILURE
Sep 28 11:52:30 katara systemd[1]: Unit ihaskell.service entered failed state.
Sep 28 11:52:30 katara systemd[1]: ihaskell.service failed.
```

It’s also pretty verbose, can we stop it from dumping everything it does into the journal?

**Comment by edwtjo** [comment]
Yes, I tested it, but with a pinned version of haskellPackages..

**Comment by Profpatsch** [comment]
No, these are from

    services.ihaskell.enable

and a consecutive nixos-rebuild.

**Comment by edwtjo** [comment]
@Profpatsch thank you for the input, can you please try again, it should be working now.

**Comment by Profpatsch** [comment]
It does!

**Comment by edwtjo** [comment]
Great, thanks!
