### ISSUE TITLE
TeXstudio segfaults at startup

### ISSUE THREAD

**Issue by mohe2015** [NixOS/nixpkgs#102166]
**Describe the bug**
TeXstudio segfaults at startup

**To Reproduce**
1. Install TeXstudio and pkgs.texlive.combined.scheme-full (probably not fully needed)
2. Run it
 
**Expected behavior**
It works

**Additional context**
```
Thread 1 ".texstudio-wrap" received signal SIGSEGV, Segmentation fault.
bt
#0  0x000000000072f597 in ManhattanStyle::event(QEvent*) ()
#1  0x00007ffff77d6cef in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/7vk814x0mgw3v17hx5yxzpzypx32vxzw-q
#2  0x00007ffff77dfb50 in QApplication::notify(QObject*, QEvent*) () from /nix/store/7vk814x0mgw3v17hx5yxzpzypx32vxzw-qtbase-5.15.0/l
#3  0x00007ffff68617fa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/7vk814x0mgw3v17hx5yxzpzypx32vxzw-qt
#4  0x00007ffff68963c7 in QObject::setProperty(char const*, QVariant const&) () from /nix/store/7vk814x0mgw3v17hx5yxzpzypx32vxzw-qtba
#5  0x000000000072f854 in ManhattanStyle::ManhattanStyle(QString const&) ()
#6  0x000000000062064a in ConfigManager::setInterfaceStyle() ()
#7  0x00000000006430cf in ConfigManager::readSettings(bool) ()
#8  0x0000000000821efe in Texstudio::readSettings(bool) ()
#9  0x00000000008275b6 in Texstudio::Texstudio(QWidget*, QFlags<Qt::WindowType>, QSplashScreen*) ()
#10 0x000000000072a6db in TexstudioApp::init(QStringList&) ()
#11 0x000000000059d29f in main ()
```

**Notify maintainers**
@ajs124
@Chaddai

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
Can't run, I'm using master with flakes.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
> Can't run, I'm using master with flakes.

$ nix flake info nixpkgs

from the folder containing your flake.

**Comment by FRidh** [comment]
Cannot reproduce this issue with nixpkgs master at 8c7ef10f716ca5983fd4bb69112aea0ae84e2d09
```
$ nix run nixpkgs/8c7ef10f716ca5983fd4bb69112aea0ae84e2d09#texstudio
```

**Comment by mohe2015** [comment]
Got fixed for me too. Don't know which commit though. Thanks for checking.
