### ISSUE TITLE
Failure of LLVM build from source (missing zlib module)

### ISSUE THREAD

**Issue by Obikawa** [NixOS/nixpkgs#102195]
Greetings.

I have only recently discoverd NixOS and I already like it a lot. 

I am now trying to rebuild my installation of Nightingale with hardware specific optimizations (march=znver1, etc.). I have encountered a wall which I am not able to clear: LLVM build fails some tests due to a missing "module". Here's a sample error message:

```
: 'RUN: at line 8';   /build/llvm/build/bin/llvm-readobj --sections /build/llvm/build/test/tools/llvm-objcopy/ELF/Output/strict-no-add.test.tmp2 | /build/llvm/build/bin/FileCheck --check-prefix=SECS /build/llvm/test/tools/llvm-objcopy/ELF/strict-no-add.test
--
Exit Code: 1

Command Output (stderr):
--
Traceback (most recent call last):
  File "/build/llvm/test/tools/llvm-objcopy/ELF/../Inputs/ungzip.py", line 1, in <module>
    import gzip
  File "/nix/store/abllfxv9k8wxl223q03mfzmkj0z9frj3-python3-3.8.5/lib/python3.8/gzip.py", line 9, in <module>
    import zlib
ModuleNotFoundError: No module named 'zlib'

```

I had tried to declare in a number of ways to install packages with zlib in their name, but nothing worked. Also, I strictly use the declarative paradigm - I really want to have my system defined only through the .nix files.

I suspect that LLVM build actually depends on zlib, but it is not specified in the dependencies, which leads to the failure. I have observed this failure in both version 7 and 10.

By the way: It is still impossible to browse through the closed issues in this Github repository. If this kind of problem had been reported, then I can not know it.

**Comment by Obikawa** [comment]
Of course, only after writing the report and right before going to sleep, I had the "brilliant idea" of garbage collecting everything and starting from scratch.

I did see zlib be built as the third or fourth derivation. After a night of compilation, it is still going. LLVM work seems not to be started yet, because I can see it only in the "These derivations will be built" section of the output.

I will keep observing the compilation process and share more of my thoughts when LLVM gets actually built without errors. I may be still waiting for the same failure to occur.

**Comment by Obikawa** [comment]
This is frustrating, but nothing changed - I got exactly the same failure in tests, due to missing zlib module.

**Comment by xaverdh** [comment]
I don't claim to be an expert on this stuff, but I think `python` during the `llvm` build refers to a bootstrap version, so maybe that doesn't have `zlib` support? But its strange that you get this error, while hydras `llvm` builds just fine..
can you share exact build instructions / config?

**Comment by Obikawa** [comment]
[configuration.txt](https://github.com/NixOS/nixpkgs/files/5469296/configuration.txt)
[fonts.txt](https://github.com/NixOS/nixpkgs/files/5469297/fonts.txt)
[hardware-configuration.txt](https://github.com/NixOS/nixpkgs/files/5469298/hardware-configuration.txt)
[optimization.txt](https://github.com/NixOS/nixpkgs/files/5469299/optimization.txt)

I was not able to paste the .nix files directly, so I simply swapped their endings into txt.

**Comment by Obikawa** [comment]
I had thought of one possible cause of this.

I can see in my build output, that there is a bunch of Python38 packages queued up for compilation. However, LLVM always gets built ahead of it. In case of the hydra system, if it had Python get built first, it would allow LLVM to continue successfuly. This way the issue went undetected until now.

I have an idea for a solution: edit the LLVM packages to explicitly ask for the appropriate Python module. Unfortunately, I only know just enough Nix to declare a configuration. I have no idea how to write a package modification.

**Comment by xaverdh** [comment]
cc @matthewbauer (he probably knows more about the bootstrap process)

**Comment by Obikawa** [comment]
How do I use an overlay to change the cmakeFlag from "-DLLVM_BUILD_TESTS=ON" to OFF? I am pretty sure this is a valid workaround, but I have not been able to figure out the declarative magic for this modification.

**Comment by xaverdh** [comment]
Does it fails in the check phase? In that case adding something like
```nix
llvm = prev.llvm.overrideAttrs (oldAttrs: { doCheck = false; })
```
to your overlay (optimization.nix) should work.

**Comment by Obikawa** [comment]
No, it fails at the end of the compilation, during tests. This is why I want to disable the tests.

**Comment by Obikawa** [comment]
On a separate note, I have asked some of the companies listed in the "Commercial Support" for a quote to solve this issue. Since Friday I have received none. I want to pay to get this sorted out. What is the community's quote?

**Comment by Obikawa** [comment]
I have modified your suggestion to more of what I want, but the flag still is not changed. However, I did notice this error in the build log:
```
: CommandLine Error: Option 'polly-delicm-max-ops' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

```
final: prev:

{
  llvm = prev.llvm.overrideAttrs (oldAttrs: {
    cmakeFlags = with prev.stdenv; [         <--- Blindly changed stdenv to prev.stdenv, because Nix complained about undefined variable.
      "-DCMAKE_BUILD_TYPE=${if debugVersion then "Debug" else "Release"}"
      "-DLLVM_INSTALL_UTILS=ON" # Needed by rustc 
      "-DLLVM_BUILD_TESTS=OFF"        <--- This is what I want
      "-DLLVM_ENABLE_FFI=ON"
      "-DLLVM_ENABLE_RTTI=ON" 
      "-DLLVM_HOST_TRIPLE=${stdenv.hostPlatform.config}" 
      "-DLLVM_DEFAULT_TARGET_TRIPLE=${stdenv.hostPlatform.config}" 
      "-DLLVM_ENABLE_DUMP=ON"
    ] ++ optionals enableSharedLibraries [
      "-DLLVM_LINK_LLVM_DYLIB=ON"
    ] ++ optionals enableManpages [
      "-DLLVM_BUILD_DOCS=ON"
      "-DLLVM_ENABLE_SPHINX=ON"
      "-DSPHINX_OUTPUT_MAN=ON" 
      "-DSPHINX_OUTPUT_HTML=OFF"
      "-DSPHINX_WARNINGS_AS_ERRORS=OFF"
    ] ++ optionals (!isDarwin) [
      "-DLLVM_BINUTILS_INCDIR=${libbfd.dev}/include" 
    ] ++ optionals isDarwin [
      "-DLLVM_ENABLE_LIBCXX=ON"
      "-DCAN_TARGET_i386=false"
    ] ++ optionals (stdenv.hostPlatform != stdenv.buildPlatform) [
      "-DCMAKE_CROSSCOMPILING=True" 
      "-DLLVM_TABLEGEN=${buildPackages.llvm_10}/bin/llvm-tblgen"
    ];
  });
}
```

**Comment by Obikawa** [comment]
One more observation: Package search in NixOs reveals over 3000 results. Are those modules? The Python website does list zlib as a separate module. It could be in one of the 3000 packages, but there is no obvious match for zlib.

https://docs.python.org/3.8/library/zlib.html
https://search.nixos.org/packages?channel=20.09&from=0&size=30&sort=alpha_asc&query=python38
https://search.nixos.org/packages?channel=20.09&from=0&size=30&sort=alpha_asc&query=zlib

**Comment by xaverdh** [comment]
These are packages, which may or may not correspond to python modules. One package can provide more then one module, in principle, and some modules may be "built in".  I think `zlib` is such a "built in" module in python, but requires the `zlib` library as a dynamically loaded dependency.

**Comment by Obikawa** [comment]
There is one more clue that I picked up today. During the configuration phase there is this line:

```
-- Could NOT find Z3: Found unsuitable version "0.0.0", but required is at least "4.7.1" (found Z3_LIBRARIES-NOTFOUND)
```

**Comment by Obikawa** [comment]
After spending hours on experimentation and research, I have concluded that this issue is caused by a deeper bug.

When I start the python shell, I am able to import zlib. Zlib is not packaged by itself. From this I deduct that zlib is built as part of python package. However, it is not propagated. Because of that. packages which depend on the python environment receive just the interpreter, without its built in modules.
