### ISSUE TITLE
dockerTools: image builds (post #91084) fail when multiple are run at once

### ISSUE THREAD

**Issue by glittershark** [NixOS/nixpkgs#102494]
**Describe the bug**

After #91084, if I try to build multiple layered images at once all but one fails with:

```
Traceback (most recent call last):                                                                                                          
  File "/nix/store/5jd17m4yj0hqrl0ws0snjng8dy18jxhn-stream", line 304, in <module>                                                          
    main()                                                                                                                                  
  File "/nix/store/5jd17m4yj0hqrl0ws0snjng8dy18jxhn-stream", line 253, in main                                                              
    info = add_layer_dir(tar, store_layer, mtime=mtime)                                                                                     
  File "/nix/store/5jd17m4yj0hqrl0ws0snjng8dy18jxhn-stream", line 179, in add_layer_dir                                                     
    tar.addfile(layer_tarinfo, read)                                                                                                        
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/tarfile.py", line 1997, in addfile                          
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)                                                                       
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/tarfile.py", line 249, in copyfileobj                       
    raise exception("unexpected end of data")                                                                                               
OSError: unexpected end of data  
```

Note that this is *different* than #75888, which was reported before #91084 and which I was never able to reproduce.

**To Reproduce**

Build multiple images with `buildLayeredImage` simultaneously on the same machine

**Notify maintainers**

@flokli @purcell @grahamc 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.15-ck1, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(grfn): `"home-manager, nixpkgs-unstable-20.09pre229671.9d0c3ffe678"`
 - channels(root): `"nixos-20.03.2425.9a3e34ae601, nixos-hardware, nixpkgs-20.09pre232709.d13d819b894"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- dockerTools
# a list of nixos modules affected by the problem
module:
```

**Comment by utdemir** [comment]
Thank you for reporting the issue.

However, I can not reproduce it on my system. I prepared this file which builds five images at the same time:

```nix
{ arg }:

let
nixpkgs = ../github.com/nixos/nixpkgs;
pkgs = import nixpkgs {};
in
builtins.map
  (i: pkgs.dockerTools.buildLayeredImage {
    name = "testfoo-${i}";
    maxLayers = 4;
    tag = "latest";
    contents = [
      (pkgs.writeScriptBin "test" "echo ${arg}")
      pkgs.qt4
    ];
  })
  (builtins.map
    (i: "${arg}-${toString i}")
    (pkgs.lib.range 0 5))
```

And called it with `nix-build repro.nix --argstr arg $RANDOM  --builders "" -j 5`, but the build finished successfully.

Since Nix runs the builds inside a sandbox, it should be unlikely for different builds to affect each other. However, I suspect that a system resource issue might cause this:

* Maybe your system is going out-of-memory, and it causes something to fail.
* Or, running multiple builds at the same time slows down some process which surfaces a concurrency issue.

But unfortunately, it is hard for me to figure out the reason without a reproducer, or more details.

Could also post:

* If your system is approaching its memory limits
* If you can reliably reproduce it with using smaller docker images (eg. the example I posted above)
* The full log of the build, in case there is a clue hidden there. If this is not possible, could you double check if there is anything pointing out to a failing thread or another Python exception.

**Comment by glittershark** [comment]
so maybe it's worth noting that I'm building multiple images in separate docker images with `/nix` mounted as shared, which I originally assumed wouldn't really impact this but might. 

Also, another symptom I'm getting is when I try to do the whole `$(nix-build -A streamDocker) | gzip --fast | skopeo copy docker-archive:/dev/stdin ...` thing I get the following error message:

```
FATA[0140] Error writing blob: Patch "https://gcr.io/v2/my-project/my-image/blobs/uploads/AJAD5v1X8PMsNg9Nq6jMWTPEKE1noB_o5FW5yu54vxAJF8qYo8HxnuUuzLDLHVX2MVmEMF
GDLrOleiRoL7ACws4": Digest did not match, expected sha256:d35ba6044a3cffbea7e46ec2bb1de2804badeda502c89ad57cb50bb95854cbcf, got sha256:d16690d9a3f21ef7433d7bfe8325bea55d7e4ce18ca13e928447746df14c3e0c
```

which I assume is the same symptom

---


> - If your system is approaching its memory limits
 
doesn't look like it, no 

> - If you can reliably reproduce it with using smaller docker images (eg. the example I posted above)

I'll give it a shot

> - The full log of the build, in case there is a clue hidden there. If this is not possible, could you double check if there is anything pointing out to a failing thread or another Python exception.

No, it just prints the stacktrace in the OP right after the list of layers and their nix store path contents.

**Comment by jskrzypek** [comment]
It's possible that this was resolved by #101403. I can't be 100% certain as we've been unable to reliably reproduce [the originally reported error](https://github.com/NixOS/nixpkgs/issues/102494#issue-734644365) outside of our CI system.

OTOH, we suspect that [the second error @glittershark mentioned](https://github.com/NixOS/nixpkgs/issues/102494#issuecomment-722469355) comes from the current lack of support for non-seekable files in `skopeo copy` (cf.: https://github.com/containers/skopeo/issues/590#issuecomment-670787272).

I'll see if I can find a way to reproduce the first error locally on a version prior to #101403 and report back.

**Comment by jskrzypek** [comment]
Nope, the skopeo issue crops up even after we write the docker archives to the disk

**Comment by jskrzypek** [comment]
Does anyone have any suggestions for how we can get around these issues?

**Comment by utdemir** [comment]
> Does anyone have any suggestions for how we can get around these issues?

I haven't looked into this issue properly yet, but below is my hunch:

---


The executable created by `streamLayeredImage` reads the store paths twice when creating the docker archive because of how `tar` formats requires the file metadata before the file contents. So, on the first read it computes **the size and the digest**, and it reads it again to actually add the contents to the tar archive. We expect the store paths contents to not change between those reads, otherwise I think we'd get the exact same kinds of errors you mentioned:

Size mismatch:

>    raise exception("unexpected end of data")                                                                                               
> OSError: unexpected end of data  

Digest mismatch:

> Digest did not match, expected sha256:d35ba6044a3cffbea7e46ec2bb1de2804badeda502c89ad57cb50bb95854cbcf, got sha256:d16690d9a3f21ef7433d7bfe8325bea55d7e4ce18ca13e928447746df14c3e0c

So, I don't know how that happens, but this suggests me that the store path contents are changing while the executable created by `streamLayeredImage` is running. This is causing the metadata calculated by the initial read to be different than the actual files in the store path, and things go bad after that.

> so maybe it's worth noting that I'm building multiple images in separate docker images with /nix mounted as shared, which I originally assumed wouldn't really impact this but might.

I am wondering if this is indeed the issue. I do not know how your setup works, but if one of those images are overwriting a store path while `streamLayeredImage` result is running, I'd expect the above issues to happen.

I hope this helps.
