### ISSUE TITLE
Cannot nixos-rebuild switch due to cpio segfault

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#102624]
**Describe the bug**

I upgraded my server to nixos 20.09, but the `nixos-rebuild switch` command fails:

```
Traceback (most recent call last):
  File "/nix/store/pgp9z69lscx5vamw0hgn59hb20imsd3s-systemd-boot-builder.py", line 258, in <module>
    main()
  File "/nix/store/pgp9z69lscx5vamw0hgn59hb20imsd3s-systemd-boot-builder.py", line 227, in main
    write_entry(*gen, machine_id)
  File "/nix/store/pgp9z69lscx5vamw0hgn59hb20imsd3s-systemd-boot-builder.py", line 95, in write_entry
    subprocess.check_call([append_initrd_secrets, "/boot%s" % (initrd)])
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/sssbfdn7m1r5kmnbimiigkj3x222sd3l-append-initrd-secrets/bin/append-initrd-secrets', '/boot/efi/nixos/256xb92fcn9nbmg7w7hliiwjqm
4irmbh-initrd-linux-5.4.68-initrd.efi']' died with <Signals.SIGSEGV: 11>.
warning: error(s) occurred while switching to the new configuration
```

The segfault comes from the cpio command: just executing `cpio` or `cpio --help` is enough to produce a segmentation fault. The weird thing is that the cpio that is installed system-wide is different from the cpio used in the `append-initrd-secrets` script, and my guess is that it segfaults due to a glibc mismatch:

- The runpath from the cpio inside the `append-initrd-secrets` script: `Library runpath:[/nix/store/xg6ilb9g9zhi2zg1dpi4zcp288rhnvns-glibc-2.30/lib]`
- The runpath from the systemd-wide cpio: `Library runpath:[/nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib]`

**To Reproduce**

I'm not sure how to reproduce it :-/

**Expected behavior**

No segfault from the cpio used in the `append-initrd-secrets` script

**Additional context**

**Notify maintainers**

@shlevy by `git blame`? Although I'm not sure this is an append-initrd-secrets issue, but more of an unfortunate consequence of something far more sinister.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72-hardened, NixOS, 20.09.1500.edb26126d98 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager-20.09, nixos-20.09.1500.edb26126d98, nixpkgs-unstable-21.03pre250049.4b30d5601da"`
 - channels(minijackson): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by minijackson** [comment]
Soo, I managed to get out of this situation by executing a `nix-collect-garbage -d` and then a `nixos-rebuild switch`, but this was a very stressful experience, because nixos had deleted every boot entry, and failed midway, so for a while, I did not have any boot entry :fearful: 

From what I have gathered, every program using the old version of glibc just segfaulted, so when trying to add boot entries of my old generations, it tried to append the initrd secrets, failed, and no boot entry was written.

I'm not sure why the programs using the old glibc segfaulted, but I think that at least we should ensure that we have some boot entries ^^ (either by continuing after an error, or restoring the previous entries)

**Comment by itc-ger** [comment]
Sounds to me as if this issue is related to #100799

**Comment by minijackson** [comment]
Thanks for the PR. Unfortunately, my CPU supports both FMA and FMA4. But I am using the hardened profile, so it is true that I am using the scudo allocator. It does sound quite related.

**Comment by alunduil** [comment]
> Soo, I managed to get out of this situation by executing a `nix-collect-garbage -d` and then a `nixos-rebuild switch`, but this was a very stressful experience, because nixos had deleted every boot entry, and failed midway, so for a while, I did not have any boot entry :fearful: 
> 
> From what I have gathered, every program using the old version of glibc just segfaulted, so when trying to add boot entries of my old generations, it tried to append the initrd secrets, failed, and no boot entry was written.
> 
> I'm not sure why the programs using the old glibc segfaulted, but I think that at least we should ensure that we have some boot entries ^^ (either by continuing after an error, or restoring the previous entries)

So I ran into this and before I realised what had happened rebooted to find no boot entries.  I'm now trying to overcome this from an install media.  Any guidance that you can provide to roughly do the equivalent? Do I need to do a nixos-enter and drop the old generations? 

I'll also try dropping the hardened profile and see if that is the cause.

**Comment by alunduil** [comment]
Please disregard my note as more than a me too.  I resolved my situation by doing the following:

1. Boot recent installation media
2. Mount existing system
3. Drop inclusion of the hardened profile
4. nixos-install

Hopefully if someone else ends up where I was this saves them some time.
