### ISSUE TITLE
wicd-curses not working

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#10281]
```
$ wicd-curses
Traceback (most recent call last):
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 1063, in <module>
    main()
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 995, in main
    ui.run_wrapper(run)
  File "/nix/store/v8mzs7wfw9rnlhsayhkvkq0cq3ycj0sp-python2.7-urwid-1.3.0/lib/python2.7/site-packages/urwid/display_common.py", line 757, in run_wrapper
    return fn()
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 88, in wrapper
    return func(*args, **kargs)
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 1003, in run
    app = appGUI()
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 591, in __init__
    self.update_status()
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 88, in wrapper
    return func(*args, **kargs)
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 734, in update_status
    self.set_status):
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 88, in wrapper
    return func(*args, **kargs)
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 161, in check_for_wireless
    ('$C', ip))
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 781, in set_status
    self.update_ui()
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 88, in wrapper
    return func(*args, **kargs)
  File "/nix/store/aqcd9nzlpdkprbrv08wvjlbl6irr1xm8-wicd-1.7.2.4/share/curses/wicd-curses.py", line 930, in update_ui
    input_data = ui.get_input_nonblocking()
AttributeError: 'Screen' object has no attribute 'get_input_nonblocking'
```
wicd-gtk work. Issue with pythod [already](https://bbs.archlinux.org/viewtopic.php?id=190578) has been [solved](https://technik.blogbasis.net/wicd-curses-fix-fuer-attributeerror-screen-object-no-attribute-get_input_nonblocking-04-12-2014) in [upsteream](http://wicd.sourceforge.net/development.php).

**Comment by matthiasbeyer** [comment]
Yep, I can confirm this, though I'm not using wicd anymore.

Can someone maybe label this "bug" and change the title to something like "wicd-curses not working"?

**Comment by matthiasbeyer** [comment]
Yep, I can confirm this, though I'm not using wicd anymore.

Can someone maybe label this "bug" and change the title to something like "wicd-curses not working"?

**Comment by matthiasbeyer** [comment]
Maybe #9014 is related to this?

**Comment by Pitometsu** [comment]
Still not working.

**Comment by kYroL01** [comment]
I can confirm that `wicd-curses` still not working. Same error on 'Screen' object.

**Comment by DarkStarSword** [comment]
I just hit this in Debian testing, and admittedly while I have not checked if the issue is still present upstream, this patch from Arch does the trick:
https://git.archlinux.org/svntogit/packages.git/tree/trunk/wicd-1.7.3-urwid-1.3.0.patch?h=packages/wicd

**Comment by x1n4u** [comment]
@DarkStarSword Bug is still presen in upstream

**Comment by garbas** [comment]
@Pitometsu @x1n4u @DarkStarSword i've applied the patch from arch. can you confirm that it works for you? if not please reopen this ticket.

**Comment by Pitometsu** [comment]
@garbas confirm: it work for me now, thanks for all!
