### ISSUE TITLE
Linker error running CrashPlanDesktop from crashplan

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#10365]
I encountered this while using nix on Ubuntu.
Adding `x11` to the build inputs doesn't help.

```
$ nix-env -i crashplan
installing ‘crashplan-3.6.4’

$ CrashPlanDesktop

$ Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/jayatana/libjayatanaag.so: libX11.so.6: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.jarego.jayatana.Agent.premain(Agent.java:85)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
```

**Comment by expipiplus1** [comment]
Aha, this seems to be a duplicate of #7082

**Comment by domenkozar** [comment]
crashplan doesn't work currently since it out of date and support is not helping me solve upgrade problems.

**Comment by expipiplus1** [comment]
Should the package be marked as broken then?

**Comment by domenkozar** [comment]
Sadly, yes

**Comment by domenkozar** [comment]
Marked as broken in 1c174d107c3988fd9a83173685636f1f9b756ca4, sorry
