### ISSUE TITLE
'sup' does not pull 'which'

### ISSUE THREAD

**Issue by Phlogistique** [NixOS/nixpkgs#10415]
The binary installed by package 'sup' in nixpkgs does not run correctly:

```
no@nrubinstein-de ~ % sup
[2015-10-16 11:37:21 +0200] ERROR: oh crap, an exception
----------------------------------------------------------------
We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/no/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
The Sup Developers
----------------------------------------------------------------
--- Errno::ENOENT from thread: main
No such file or directory - /nix/store/rpicl75di45vix7mgxxyrwnscqc9h068-which-2.21/bin/which gpg2
/nix/store/hdx5116gy6cvz7zrdindw7k94nyxsr9w-sup-0.20.0/lib/ruby/gems/1.9.3/gems/sup-0.20.0/lib/sup/crypto.rb:88:in ``'
/nix/store/hdx5116gy6cvz7zrdindw7k94nyxsr9w-sup-0.20.0/lib/ruby/gems/1.9.3/gems/sup-0.20.0/lib/sup/crypto.rb:88:in `initialize'
/nix/store/hdx5116gy6cvz7zrdindw7k94nyxsr9w-sup-0.20.0/lib/ruby/gems/1.9.3/gems/sup-0.20.0/lib/sup/util.rb:662:in `new'
/nix/store/hdx5116gy6cvz7zrdindw7k94nyxsr9w-sup-0.20.0/lib/ruby/gems/1.9.3/gems/sup-0.20.0/lib/sup/util.rb:662:in `init'
/nix/store/hdx5116gy6cvz7zrdindw7k94nyxsr9w-sup-0.20.0/lib/ruby/gems/1.9.3/gems/sup-0.20.0/lib/sup.rb:178:in `block in start'
/nix/store/hdx5116gy6cvz7zrdindw7k94nyxsr9w-sup-0.20.0/lib/ruby/gems/1.9.3/gems/sup-0.20.0/lib/sup.rb:178:in `each'
/nix/store/hdx5116gy6cvz7zrdindw7k94nyxsr9w-sup-0.20.0/lib/ruby/gems/1.9.3/gems/sup-0.20.0/lib/sup.rb:178:in `start'
/nix/store/hdx5116gy6cvz7zrdindw7k94nyxsr9w-sup-0.20.0/lib/ruby/gems/1.9.3/gems/sup-0.20.0/bin/sup:158:in `<module:Redwood>'
/nix/store/hdx5116gy6cvz7zrdindw7k94nyxsr9w-sup-0.20.0/lib/ruby/gems/1.9.3/gems/sup-0.20.0/bin/sup:74:in `<top (required)>'
/home/no/.nix-profile/bin/sup:21:in `load'
/home/no/.nix-profile/bin/sup:21:in `<main>'
```

and indeed,  /nix/store/rpicl75di45vix7mgxxyrwnscqc9h068-which-2.21 does not exist on my system.

```
no@nrubinstein-de ~ % nix-store --query --references $(which sup)
/nix/store/28pd462hnvj199c8kjzmry2abnqjxnmr-sup-0.20.0-bundle
/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21
/nix/store/31w31mc8immhpnmxvcl4l0fvc3i5iwh0-zlib-1.2.8
/nix/store/xag5ayq906w9zhlxs8wayv4kvpiyqphq-bash-4.3-p42
/nix/store/4i01mpa2s194m44xrz41wmf4yr49jysq-ncurses-5.9
/nix/store/8xfxnm4a7jvyh0i1sd967z6rws8lh21a-coreutils-8.24
/nix/store/viaj0jy9xvn7jjr6m6b24r7mvg4irmzf-gnugrep-2.21
/nix/store/2k425jcvvcy0vx9rgvqda0m7cp9lngyi-ruby-1.9.3-p551
/nix/store/i9nn1fkcy95dzf0hb9wi8gbkid3iw1sa-gcc-4.9.3
/nix/store/kxf1p7l7lgm6j5mjzkiwcwzc98s9f1az-binutils-2.23.1
/nix/store/4n9yj90rdggqcx34ylbshryg3rf9cqpj-gcc-wrapper-4.9.3
/nix/store/9zp90x611wgkw3zq920yj3vgvfgl1dqn-gnused-4.2.2
/nix/store/fnaz4d1h0gqd8fpyglxiwznha253pcqj-git-2.5.3
/nix/store/fsk51ll2zykrwwh5jliqrgfzh59h0i0r-ruby-1.9.3-p551-bundler-2015-01-11
/nix/store/vh8554xqwr9aip4l0r2q9q0712mip237-util-linux-2.26.2
/nix/store/mw50g7is94zggic0ynxi5kdj3pwh80rb-xapian-1.2.21
/nix/store/hdx5116gy6cvz7zrdindw7k94nyxsr9w-sup-0.20.0
```

**Comment by Phlogistique** [comment]
Seems to have been fixed in as of nixpkgs-16.03pre71923.3087ef3
