### ISSUE TITLE
Problem running Publii AppImage using appimage-run

### ISSUE THREAD

**Issue by ptman** [NixOS/nixpkgs#104376]
**Describe the bug**
Problem running Publii AppImage using appimage-run

**To Reproduce**

1. wget https://cdn.getpublii.com/Publii-0.37.3.AppImage
2. appimage-run Publii-0.37.3.AppImage
3. Error:
```
Publii-0.37.3.AppImage installed in /home/ptman/.cache/appimage-run/895e7901ce59ba1227fed2ca34e127da994e2973b24018876431efc08b971101
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ptman/.cache/appimage-run/895e7901ce59ba1227fed2ca34e127da994e2973b24018876431efc08b971101/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Expected behavior**
That publii would launch.

**Additional context**
Seems publii is implemented using electron.

**Notify maintainers**
@tilpner ?

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.75, NixOS, 20.09.1889.58f9c4c7d3a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1889.58f9c4c7d3a, nixos-unstable-21.03pre252388.069f183f16c"`
 - channels(ptman): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by tilpner** [comment]
appimage-run doesn't come with libsecret, see if adding it helps:

```
appimage-run.override { extraPkgs = p: [ p.gnome3.libsecret ]; }
```

**Comment by ptman** [comment]
Much better, thank you. I'm quite new to nixos. I added the following to `~/.config/nixpkgs/config.nix`:

```nix
  packageOverrides = pkgs: with pkgs; rec {
    appimage-run = pkgs.appimage-run.override {
      extraPkgs = p: [ p.gnome3.libsecret ];
    };
  };
```

And now publii starts, but crashes on opening a save dialog. Also the preview feature doesn't seem to do anything. The crash output is:

```
Publii-0.37.3.AppImage installed in /home/ptman/.cache/appimage-run/895e7901ce59ba1227fed2ca34e127da994e2973b24018876431efc08b971101
The window-config.json file will be created
The app-config.json file will be created
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(!) Unable to set spellchecker to use selected language - null
(!) Unable to set spellchecker to use selected language - null

(Publii:20368): GLib-GIO-ERROR **: 10:31:42.539: No GSettings schemas are installed on the system
zsh: trace trap (core dumped)  appimage-run Publii-0.37.3.AppImage
```

**Comment by Artturin** [comment]
file dialog issue fixed in https://github.com/NixOS/nixpkgs/pull/161739
