### ISSUE TITLE
Xonsh: Xonfig configuration commands error

### ISSUE THREAD

**Issue by crinklywrappr** [NixOS/nixpkgs#104745]
**Describe the bug**

```
 $ xonfig wizard
Traceback (most recent call last):
  File "/nix/store/4k342j1vwfx34pvd00smmam59gkm1c9g-xonsh-0.9.21/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 14992, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
  File "/nix/store/4k342j1vwfx34pvd00smmam59gkm1c9g-xonsh-0.9.21/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 14785, in proxy_two
    return f(args, stdin)
  File "/nix/store/4k342j1vwfx34pvd00smmam59gkm1c9g-xonsh-0.9.21/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 21069, in xonfig
    return xonfig_main(args)
  File "/nix/store/4k342j1vwfx34pvd00smmam59gkm1c9g-xonsh-0.9.21/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 17309, in xonfig_main
    return _XONFIG_MAIN_ACTIONS[ns.action](ns)
  File "/nix/store/4k342j1vwfx34pvd00smmam59gkm1c9g-xonsh-0.9.21/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 17070, in _wizard
    w = make_xonfig_wizard(
  File "/nix/store/4k342j1vwfx34pvd00smmam59gkm1c9g-xonsh-0.9.21/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 17030, in make_xonfig_wizard
    wiz.YesNo(question=WIZARD_ENV_QUESTION, yes=make_env_wiz(), no=wiz.Pass()),
  File "/nix/store/4k342j1vwfx34pvd00smmam59gkm1c9g-xonsh-0.9.21/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 16963, in make_env_wiz
    w = _make_flat_wiz(make_envvar, sorted(builtins.__xonsh__.env._docs.keys()))
AttributeError: 'Env' object has no attribute '_docs'


 $ xonfig web
/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/bin/python3.8: Error while finding module specification for 'xonsh.webconfig' (ModuleNotFoundError: No module named 'xonsh')
```

**Additional context**
I added `xonsh` to `environment.systemPackages` because I wanted to play around with it before setting it as login shell.  Not off to a good start.

**Notify maintainers**
Notifying these 3 because they all touched the pkg recently.
@garbas 
@r-ryantm 
@marsam 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.1500.edb26126d98 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by crinklywrappr** [comment]
I ran this in a `nix-shell`, using `nixpkgs-unstable`, and the issue appears to be fixed.

However, on `nixos-unstable` I continue to see the same problem with `xonfig web`, but `xonfig wizard` seems to work.
