### ISSUE TITLE
ndg-httpsclient: attribute ‘bsd’ missing

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#10530]
```
$ nox-review pr 10522
=== Reviewing PR 10522 : gplaycli: init at 0.1.2
==> Fetching base (master)
==> Fetching PR
==> Fetching extra history for merging
==> Merging PR into base
error: while evaluating ‘makeOverridable’ at /home/davidak/.nox/nixpkgs/lib/customisation.nix:54:24, called from /home/davidak/.nox/nixpkgs/pkgs/top-level/python-packages.nix:4369:21:
while evaluating anonymous function at /home/davidak/.nox/nixpkgs/pkgs/development/python-modules/generic/default.nix:8:1, called from /home/davidak/.nox/nixpkgs/lib/customisation.nix:56:12:
while evaluating ‘mkDerivation’ at /home/davidak/.nox/nixpkgs/pkgs/stdenv/generic/default.nix:91:5, called from /home/davidak/.nox/nixpkgs/pkgs/development/python-modules/generic/default.nix:62:1:
while evaluating ‘licenseAllowed’ at /home/davidak/.nox/nixpkgs/pkgs/stdenv/generic/default.nix:128:24, called from /home/davidak/.nox/nixpkgs/pkgs/stdenv/generic/default.nix:147:14:
while evaluating ‘hasDeniedUnfreeLicense’ at /home/davidak/.nox/nixpkgs/pkgs/stdenv/generic/default.nix:70:28, called from /home/davidak/.nox/nixpkgs/pkgs/stdenv/generic/default.nix:129:12:
while evaluating ‘isUnfree’ at /home/davidak/.nox/nixpkgs/pkgs/stdenv/generic/default.nix:55:14, called from /home/davidak/.nox/nixpkgs/pkgs/stdenv/generic/default.nix:73:5:
while evaluating ‘toList’ at /home/davidak/.nox/nixpkgs/lib/lists.nix:123:12, called from /home/davidak/.nox/nixpkgs/pkgs/stdenv/generic/default.nix:73:15:
while evaluating the attribute ‘meta.license’ at /home/davidak/.nox/nixpkgs/pkgs/top-level/python-packages.nix:4385:7:
attribute ‘bsd’ missing, at /home/davidak/.nox/nixpkgs/pkgs/top-level/python-packages.nix:4385:17
Traceback (most recent call last):
  File "/nix/store/jdhb4a1gvqc9nv6dl45z75lis03ghxqj-nox-0.0.2/bin/.nox-review-wrapped", line 11, in <module>
    sys.exit(cli())
  File "/nix/store/hq0qk6dlyj100c72n3iffi8yl3k4pvf9-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/hq0qk6dlyj100c72n3iffi8yl3k4pvf9-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/nix/store/hq0qk6dlyj100c72n3iffi8yl3k4pvf9-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/hq0qk6dlyj100c72n3iffi8yl3k4pvf9-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/hq0qk6dlyj100c72n3iffi8yl3k4pvf9-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/hq0qk6dlyj100c72n3iffi8yl3k4pvf9-python3.4-click-5.1/lib/python3.4/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/jdhb4a1gvqc9nv6dl45z75lis03ghxqj-nox-0.0.2/lib/python3.4/site-packages/nox/review.py", line 127, in review_pr
    attrs = differences(packages_for_sha(base),
  File "/nix/store/ivi1vv3jsc5m0p89jnx0mxi5gkc0416r-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 1013, in decorate
    should_cache_fn)
  File "/nix/store/ivi1vv3jsc5m0p89jnx0mxi5gkc0416r-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 640, in get_or_create
    async_creator) as value:
  File "/nix/store/9bji2g5ndk3xyhvrv5x7dq9zsdxd2vi9-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/nix/store/9bji2g5ndk3xyhvrv5x7dq9zsdxd2vi9-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/nix/store/9bji2g5ndk3xyhvrv5x7dq9zsdxd2vi9-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/nix/store/ivi1vv3jsc5m0p89jnx0mxi5gkc0416r-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 612, in gen_value
    created_value = creator()
  File "/nix/store/ivi1vv3jsc5m0p89jnx0mxi5gkc0416r-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 1009, in creator
    return fn(*arg, **kw)
  File "/nix/store/jdhb4a1gvqc9nv6dl45z75lis03ghxqj-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 90, in packages_for_sha
    return packages(repo.path)
  File "/nix/store/jdhb4a1gvqc9nv6dl45z75lis03ghxqj-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 81, in packages
    universal_newlines=True)
  File "/nix/store/lwz7kmb4jzgh3da04p1pa723i6084xk0-python3-3.4.3/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['nix-env', '-f', '/home/davidak/.nox/nixpkgs', '-qaP', '--drv-path', '--show-trace']' returned non-zero exit status 1
```

added in https://github.com/NixOS/nixpkgs/pull/10522

@DamienCassou have you tested it? i get this problem on OS X (darwin) and NixOS (x86_64).

**Comment by domenkozar** [comment]
Should be fixed now, thanks!

**Comment by DamienCassou** [comment]
I successfully built it as it was a dependency of a project I installed. But building with `nix-build` and even installing a dependent package does not reveal issues in meta data. Thanks for noticing it. Can you please tell me how you found it?

**Comment by domenkozar** [comment]
tarball job checks `meta` information:

`nix-build pkgs/top-level/release.nix -A tarball`

**Comment by davidak** [comment]
@DamienCassou i tried to test another PR (https://github.com/NixOS/nixpkgs/pull/10499) and got the error above. i don't see how `ndg-httpsclient` is a dependency of `lmdb` or does that informations get evaluated for all packages?

you can use **nox** to easily test PRs like you can see above.
before creating a PR you can test with `nix-env -i python2.7-gplaycli-0.1.2 -f ~/nixpkgs/`

the problem is solved, thank you! :+1:
