### ISSUE TITLE
Editable install with poetry

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#105593]
**Describe the bug**
It's something that is driving me a bit crazy is that pip can't do editable install from a poetry project (with a pyproject.toml) as shown in https://github.com/python-poetry/poetry/issues/34 (and concerns me at https://github.com/nix-community/poetry2nix/issues/159).

In the first link it is explained how to generate a setup.py from a pyproject.toml (good, I dont need to duplicate the project description) via `poetry build --format sdist && tar --wildcards -xvf dist/*.tar.gz -O '*/setup.py' > setup.py `.

What I've tried to do is a shell.nix with:
```
  myApp = poetry.mkPoetryApplication {
      ...
  };

  myAppHacked = myApp.overrideAttrs {
    buildInputs = [
      pkgs.python3Packages.pipInstallHook
    ];
```

but then I get
```
Traceback (most recent call last):
  File "/run/user/1000/tmp.IYeEKG54cK/bin/mptcpanalyzer", line 33, in <module>
    sys.exit(load_entry_point('mptcpanalyzer', 'console_scripts', 'mptcpanalyzer')())
  File "/run/user/1000/tmp.IYeEKG54cK/bin/mptcpanalyzer", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: mptcpanalyzer
```

There are various things that could be improved but I wonder if that's an ok direction or if some else (  @FRidh  ?) had something working.

(I just saw there was a `format = "pyproject";` but Ideally I would like to be able to reuse myApp and not have to rewrite another derivation with buildPythonPackage. ?)

**Comment by FRidh** [comment]
> It's something that is driving me a bit crazy is that pip can't do editable install from a poetry project (with a pyproject.toml) as shown in python-poetry/poetry#34 (and concerns me at nix-community/poetry2nix#159).

PEP 517/518 do not consider editable installs. 

To be honest, I really see no value in editable installs. It is often trivial to be able to work with your source tree without an editable installation. I often symlink the trees I need into a folder and put that folder on PYTHONPATH. Another option, especially useful when you need extension modules, is to put the result/out link on your PYTHONPATH. Then you just need to do a nix-build, but won't need to reload your environment. Heck, using inotify you could automate that even (could actually be an interesting hook).

Anyway, I can't help you with poetry2nix, you better ask @adisbladis about that.

**Comment by teto** [comment]
PYTHONPATH=. seems to do the trick. I was worried that my entrypoints wouldn't be found etc but so far it looks ok. mkPoetryApplication builds my app in /nix/store and put it in PATH but with `export PYTHONPATH=. `it seems like my local changes are taken into account.
Looking at the wrapper I am not sure how it picks up my PYTHONPATH ?
```
#!/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/bin/python3.8
# -*- coding: utf-8 -*-
import sys;import site;import functools;sys.argv[0] = '/nix/store/gb8l4rf4v4l89h8ablirzr0w9pzj5akr-python3.8-mptcpanalyzer-0.3.4/bin/mptcpanalyzer';functools.reduce(lambda k, p: site.addsitedir(p, k), ['/nix/store/gb8l4rf4v4l89h8ablirzr0w9pzj5akr-python3.8-mptcpanalyzer-0.3.4/lib/python3.8/site-packages','/nix/store/nz5ks879aihnx4qmvh5c384c39524y3g-python3.8-pyqt5-5.15.2/lib/python3.8/site-packages','/nix/store/6i1hk29y3gqwwskpxaxcwxk26kq408ma-python3.8-pyqt5-sip-12.8.1/lib/python3.8/site-packages','/nix/store/3xx8qpr3nz9wp2d2n9krwgrnl74m5zmw-python3.8-bitmath-1.3.3.1/lib/python3.8/site-packages','/nix/store/iqz00df20f9br5vp7vl3fcwvclg3l7f7-python3.8-cairocffi-1.2.0/lib/python3.8/site-packages','/nix/store/mdwr7f4zfaqxkc3r9lvkd4wngq86r0l3-python3.8-cffi-1.14.4/lib/python3.8/site-packages','/nix/store/48cp48xdjznh524ykqyqkk42x4xgwwbx-python3.8-pycparser-2.20/lib/python3.8/site-packages','/nix/store/8riz51rw697r8shh5zg3dyhqjpm1sf8h-python3.8-cmd2-1.4.0/lib/python3.8/site-packages','/nix/store/7qq30vf13rb9mfdlzidg0lsfaswph3fi-python3.8-attrs-20.3.0/lib/python3.8/site-packages','/nix/store/x7lqyimwp6914pr72cp9pbpwhc0vqd2q-python3.8-colorama-0.4.4/lib/python3.8/site-packages','/nix/store/zzlrpr86xgah0f13d52nn1nsfh5h2rpm-python3.8-pyperclip-1.8.1/lib/python3.8/site-packages','/nix/store/4czpz1cg3dbmq18bqlp9x7ad7nqcc5ij-python3.8-wcwidth-0.2.5/lib/python3.8/site-packages','/nix/store/47a43sy56mylnpycj84k5z73b8bfs232-python3.8-importlib-metadata-3.1.0/lib/python3.8/site-packages','/nix/store/a866pdbwl7i1vzfjgpawgz434vcp1y0v-python3.8-zipp-3.4.0/lib/python3.8/site-packages','/nix/store/zq7rn880gfingy0zi1xkblxr7zj7azry-python3.8-toml-0.10.2/lib/python3.8/site-packages','/nix/store/qjw1lc02czyx1b26gh4xmyw0mffm43qg-python3.8-matplotlib-3.3.2/lib/python3.8/site-packages','/nix/store/k82jicvaafc5qzc2yii99df3wv4dyp1m-python3.8-certifi-2020.11.8/lib/python3.8/site-packages','/nix/store/50w17bpki0c412wg3zi196dgj8fj1i47-python3.8-cycler-0.10.0/lib/python3.8/site-packages','/nix/store/1na5piykw15553kw3dc6ixmw41plnz6w-python3.8-six-1.15.0/lib/python3.8/site-packages','/nix/store/f5fa05spd3z2mm1jx773gczmpi60vg9b-python3.8-kiwisolver-1.3.1/lib/python3.8/site-packages','/nix/store/512vd7a6z4wbg7nlvzrg3k16qr2v8ndg-python3.8-numpy-1.19.4/lib/python3.8/site-packages','/nix/store/8rjbknswqzg68kbr2xp89iyyf9y0diym-python3.8-pillow-8.0.1/lib/python3.8/site-packages','/nix/store/m95wbq876in9v7qbfjnqb19ijlzwbawq-python3.8-pyparsing-2.4.7/lib/python3.8/site-packages','/nix/store/np1s7l09fi7mzyp07r9rk49ka6piqjqa-python3.8-python-dateutil-2.8.1/lib/python3.8/site-packages','/nix/store/lr5fvlzd4arzva83f38nl3v7xmqphi8m-python3.8-pandas-1.1.4/lib/python3.8/site-packages','/nix/store/x7jqipqvbcafc6z6q8mcvk4zmbz16bz6-python3.8-pytz-2020.4/lib/python3.8/site-packages','/nix/store/xjzl7wcxs18fx3jr105jxagqgvpq9r6z-python3.8-pixcat-0.1.4/lib/python3.8/site-packages','/nix/store/807lv7l60xgcsn9inlwcdkvh5dkdq41x-python3.8-blessed-1.17.12/lib/python3.8/site-packages','/nix/store/n2ld08a3sanmhqsi4vr7cn8hkc5zj2az-python3.8-docopt-0.6.2/lib/python3.8/site-packages','/nix/store/px1k8i4c2wayv1rqsspa4nrzkvazav5s-python3.8-requests-2.25.0/lib/python3.8/site-packages','/nix/store/p0rgvqnrp0by34rc96vm7pd9hdiw0zl8-python3.8-chardet-3.0.4/lib/python3.8/site-packages','/nix/store/ifyd6mza5h8vv5nc53ydfq80k5azi4jx-python3.8-idna-2.10/lib/python3.8/site-packages','/nix/store/2gdyfrwl2gyvcqf5iiifqici2njn6bbn-python3.8-urllib3-1.26.2/lib/python3.8/site-packages','/nix/store/l1rc6nqkrrjmf35cjdyz6wz3ssg5cxi2-python3.8-pycairo-1.18.2/lib/python3.8/site-packages','/nix/store/qin4x6f6d0v79mln2bq2qd7mmjbrvd53-python3.8-pygobject-3.36.1/lib/python3.8/site-packages','/nix/store/kz791k8wd2wlldj0jr18w107gf4x5laz-python3.8-stevedore-3.3.0/lib/python3.8/site-packages','/nix/store/jci582dm7lrhlpwykwkwvnq97jjbhzmf-python3.8-pbr-5.5.1/lib/python3.8/site-packages','/nix/store/29721233vmklbhkcps3ddfd99m6a4f2f-python3.8-setuptools-47.3.1/lib/python3.8/site-packages'], site._init_pathinfo());
import re
import sys
from mptcpanalyzer.cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by FRidh** [comment]
> PYTHONPATH=. seems to do the trick. I was worried that my entrypoints wouldn't be found etc but so far it looks ok. 

Yes, those won't get picked up. You really need to do a build then, and then put the `bin/` on PATH.

> Looking at the wrapper I wonder how it picks up my PYTHONPATH though ? (I know it's a silly question)

The Python interpreter always listens to `PYTHONPATH`, unless instructed not to.

**Comment by teto** [comment]
ok thanks a lot you saved me a ton of time. All good then.
