### ISSUE TITLE
vm-test-run-misc fails, blocking nixos-unstable(-small)

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#105581]
**Describe the bug**
https://hydra.nixos.org/build/131866531

```
nixos/tests/misc.nix
```

```
$ nix-build -A nixos.tests.misc.x86_64-linux nixos/release-small.nix
...
(0.03 seconds)
(0.08 seconds)
whether kernel.poweroff_cmd is set
machine: must succeed: [ -x "$(cat /proc/sys/kernel/poweroff_cmd)" ]
(0.01 seconds)
(0.01 seconds)
whether the blkio controller is properly enabled
machine: must succeed: [ -e /sys/fs/cgroup/blkio/blkio.reset_stats ]
machine: output: 
Test "whether the blkio controller is properly enabled" failed with error: "command `[ -e /sys/fs/cgroup/blkio/blkio.reset_stats ]` failed (exit code 1)"
error: 
Traceback (most recent call last):
  File "/nix/store/pjh4wascfzzsdsihbv819qkpk4fh5nrv-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 897, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 44, in <module>
  File "/nix/store/pjh4wascfzzsdsihbv819qkpk4fh5nrv-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 422, in succeed
    raise Exception(
Exception: command `[ -e /sys/fs/cgroup/blkio/blkio.reset_stats ]` failed (exit code 1)
cleaning up
killing machine (pid 6)
(0.00 seconds)
builder for '/nix/store/q0vgahcsaya1yjhn1khqj41difgfia9l-vm-test-run-misc.drv' failed with exit code 1
```

**To Reproduce**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: `nixos.tests.misc.x86_64-linux`
# a list of nixos modules affected by the problem
module:
```

**Comment by dasJ** [comment]
cc @flokli is this related to the cgroupsv2 PR?

**Comment by lukegb** [comment]
Looks like it.

Before:
```
whether the blkio controller is properly enabled
machine: must succeed: [ -e /sys/fs/cgroup/blkio/blkio.reset_stats ]
machine: output:
Test "whether the blkio controller is properly enabled" failed with error: "command `[ -e /sys/fs/cgroup/blkio/blkio.reset_stats ]` failed (exit code 1)"
error:
Traceback (most recent call last):
  File "/nix/store/pjh4wascfzzsdsihbv819qkpk4fh5nrv-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 897, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 44, in <module>
  File "/nix/store/pjh4wascfzzsdsihbv819qkpk4fh5nrv-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 422, in succeed
    raise Exception(
Exception: command `[ -e /sys/fs/cgroup/blkio/blkio.reset_stats ]` failed (exit code 1)
cleaning up
killing machine (pid 9)
(0.00 seconds)
```

After changing default for `systemd.unifiedCgroupHierarchy` to false, the test succeeds.

Which, well, totally makes sense :P

**Comment by lukegb** [comment]
Proposed patch, but I'd like someone closer to the space to make a judgement:

```diff
diff --git a/nixos/tests/misc.nix b/nixos/tests/misc.nix
index ae150553273..40661cdca0a 100644
--- a/nixos/tests/misc.nix
+++ b/nixos/tests/misc.nix
@@ -88,8 +88,8 @@ import ./make-test-python.nix ({ pkgs, ...} : rec {
       with subtest("whether kernel.poweroff_cmd is set"):
           machine.succeed('[ -x "$(cat /proc/sys/kernel/poweroff_cmd)" ]')
 
-      with subtest("whether the blkio controller is properly enabled"):
-          machine.succeed("[ -e /sys/fs/cgroup/blkio/blkio.reset_stats ]")
+      with subtest("whether the io cgroupv2 controller is properly enabled"):
+          machine.succeed("grep -q '\\bio\\b' /sys/fs/cgroup/cgroup.controllers")
 
       with subtest("whether we have a reboot record in wtmp"):
           machine.shutdown
```

**Comment by flokli** [comment]
yeah, that location looks different with unified cgroups, looking in `/sys/fs/cgroup/cgroup.controllers` looks probably right.

I didn't check `nixos/tests/misc.nix` apparently checks for the presences of the blkio controller :shrug:

Thanks for catching that! Could you file a PR?
