### ISSUE TITLE
darwin: mosh: v1.2.5 fails to build

### ISSUE THREAD

**Issue by benmont** [NixOS/nixpkgs#10611]
Machine info:

$ uname -a
Darwin tattoo 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64 i386 Macmini7,1 Darwin

End of build log:

```
make  all-recursive
make[1]: Entering directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5'
Making all in src
make[2]: Entering directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src'
Making all in protobufs
make[3]: Entering directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/protobufs'
  GEN      userinput.pb.cc
  GEN      hostinput.pb.cc
  GEN      transportinstruction.pb.cc
make  all-am
make[4]: Entering directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/protobufs'
  CXX      userinput.pb.o
  CXX      hostinput.pb.o
  CXX      transportinstruction.pb.o
  AR       libmoshprotos.a
make[4]: Leaving directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/protobufs'
make[3]: Leaving directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/protobufs'
Making all in util
make[3]: Entering directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/util'
  CXX      locale_utils.o
  CXX      swrite.o
  CXX      select.o
  CXX      timestamp.o
  CXX      pty_compat.o
pty_compat.cc:42:10: fatal error: 'sys/stropts.h' file not found
#include <sys/stropts.h>
         ^
1 error generated.
Makefile:352: recipe for target 'pty_compat.o' failed
make[3]: *** [pty_compat.o] Error 1
make[3]: Leaving directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/util'
Makefile:331: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src'
Makefile:378: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5'
Makefile:318: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/348zch7hhrr4abb6zslyc3lhqjjrj3pa-mosh-1.2.5.drv’ failed with exit code 2
error: build of ‘/nix/store/348zch7hhrr4abb6zslyc3lhqjjrj3pa-mosh-1.2.5.drv’ failed
Traceback (most recent call last):
  File "/nix/store/08cv7hl3mhxvr7f5ywphfg0jxyd5xk42-nox-0.0.2/bin/.nox-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/3bf8bn66ryfd9aad0pa0d47fifc9v524-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/3bf8bn66ryfd9aad0pa0d47fifc9v524-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/nix/store/3bf8bn66ryfd9aad0pa0d47fifc9v524-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/3bf8bn66ryfd9aad0pa0d47fifc9v524-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/08cv7hl3mhxvr7f5ywphfg0jxyd5xk42-nox-0.0.2/lib/python3.4/site-packages/nox/search.py", line 83, in main
    subprocess.check_call(['nix-env', '-iA', '--show-trace'] + attributes)
  File "/nix/store/j9x359la91dfif21hc4niyxgpyvx3fwz-python3-3.4.3/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nix-env', '-iA', '--show-trace', 'nixpkgs.mosh']' returned non-zero exit status 100
```

**Comment by jcf** [comment]
Mosh fails to build with the new pure Darwin setup too.

```
check flags: SHELL=/nix/store/jxbyzscwyrrhcd2nn7hw71inbrz1zvng-bash-4.3-p42/bin/bash
Running Mkbootstrap for IO::Tty ()
chmod 644 Tty.bs
PERL_DL_NONLAZY=1 /nix/store/53nx9qw9xd7896vnzshxln0f40pgrcf4-perl-5.20.2/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
# Configuration: -DHAVE_GRANTPT -DHAVE_POSIX_OPENPT -DHAVE_PTSNAME -DHAVE_SIGACTION -DHAVE_STRLCPY -DHAVE_TERMIOS_H -DHAVE_TTYNAME -DHAVE_UNLOCKPT -DHAVE_UTIL_H
# Checking for appropriate ioctls:
# TIOCNOTTY
# TIOCSCTTY
trying posix_openpt()...
pty_allocate(nonfatal): posix_openpt(): Operation not permitted at /private/var/folders/0_/ldrvd84j5b712wbnfrg7z_700000gn/T/nix-build-perl-IO-Tty-1.12.drv-1/IO-Tty-1.12/blib/lib/IO/Pty.pm line 24.
trying BSD /dev/pty??...
Cannot open a pty at t/test.t line 32.

#   Failed test '0 exit code from forked child - Checking that returned fd's don't clash with stdin/out/err'
#   at t/test.t line 46.
#          got: '512'
#     expected: '0'
#  === Checking if child gets pty as controlling terminal
trying posix_openpt()...
pty_allocate(nonfatal): posix_openpt(): Operation not permitted at /private/var/folders/0_/ldrvd84j5b712wbnfrg7z_700000gn/T/nix-build-perl-IO-Tty-1.12.drv-1/IO-Tty-1.12/blib/lib/IO/Pty.pm line 24.
trying BSD /dev/pty??...
Cannot open a pty at t/test.t line 52.
# Looks like you planned 5 tests but ran 2.
# Looks like you failed 1 test of 2 run.
# Looks like your test exited with 2 just after 2.
t/test.t ..
Dubious, test returned 2 (wstat 512, 0x200)
Failed 4/5 subtests

Test Summary Report
-------------------
t/test.t (Wstat: 512 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 5 tests but ran 2.
Files=1, Tests=2,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.04 cusr  0.05 csys =  0.11 CPU)
Result: FAIL
Failed 1/1 test programs. 1/2 subtests failed.
Makefile:1025: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 2
builder for ‘/nix/store/gicx191yvz3njic09873y70g98f2x954-perl-IO-Tty-1.12.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/6lzj0fv1qi9j5cn9r7fjwppv1adbdwjm-mosh-1.2.5.drv’: 1 dependencies couldn't be built
```

I tried to build without chroot using the command below, which resulted in the error reported here.

```
nix-store --realise /nix/store/6lzj0fv1qi9j5cn9r7fjwppv1adbdwjm-mosh-1.2.5.drv --option build-use-chroot false
```

**Comment by davidak** [comment]
https://github.com/NixOS/nix/pull/672 got merged, perl-IO-Tty-1.12 seams to build succesfully now but mosh still fails.

cc @henrytill

```
post-installation fixup
gzipping man pages in /nix/store/hdmqyh3bhf0iiz26rzah0z6z6n55svna-perl-IO-Tty-1.12
stripping (with flags -S) in /nix/store/hdmqyh3bhf0iiz26rzah0z6z6n55svna-perl-IO-Tty-1.12/lib
strip: can't process non-object and non-archive file: /nix/store/hdmqyh3bhf0iiz26rzah0z6z6n55svna-perl-IO-Tty-1.12/lib/perl5/site_perl/5.20.2/darwin-2level/auto/IO/Tty/.packlist
strip: can't process non-object and non-archive file: /nix/store/hdmqyh3bhf0iiz26rzah0z6z6n55svna-perl-IO-Tty-1.12/lib/perl5/site_perl/5.20.2/darwin-2level/IO/Pty.pm
strip: can't process non-object and non-archive file: /nix/store/hdmqyh3bhf0iiz26rzah0z6z6n55svna-perl-IO-Tty-1.12/lib/perl5/site_perl/5.20.2/darwin-2level/IO/Tty/Constant.pm
strip: can't process non-object and non-archive file: /nix/store/hdmqyh3bhf0iiz26rzah0z6z6n55svna-perl-IO-Tty-1.12/lib/perl5/site_perl/5.20.2/darwin-2level/IO/Tty.pm
patching script interpreter paths in /nix/store/hdmqyh3bhf0iiz26rzah0z6z6n55svna-perl-IO-Tty-1.12
building path(s) ‘/nix/store/8nrqs944jhv3h0x200rdhm0brf1vxd8x-mosh-1.2.5’
unpacking sources
unpacking source archive /nix/store/b7zc807dj04n3yyvp9bpc4q87q43alzy-mosh-1.2.5.tar.gz
source root is mosh-1.2.5
patching sources
configuring
configure flags: --disable-dependency-tracking --prefix=/nix/store/8nrqs944jhv3h0x200rdhm0brf1vxd8x-mosh-1.2.5
checking for a BSD-compatible install... /nix/store/7wp5lq3v2njqqvd9wx1028z80q83bn34-coreutils-8.24/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /nix/store/7wp5lq3v2njqqvd9wx1028z80q83bn34-coreutils-8.24/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether clang understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of clang... none
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking dependency style of clang++... none
checking for ranlib... ranlib
checking for protoc... /nix/store/9j0gcxg81c66fsg74s4ilcmai1qv6lp9-protobuf-2.6.1/bin/protoc
checking for ar... ar
checking the archiver (ar) interface... ar
checking whether C compiler accepts -fno-strict-overflow... yes
checking whether C++ compiler accepts -fno-strict-overflow... yes
checking whether C compiler accepts -D_FORTIFY_SOURCE=2... yes
checking whether C++ compiler accepts -D_FORTIFY_SOURCE=2... yes
checking whether C compiler accepts -fstack-protector-all... yes
checking whether C++ compiler accepts -fstack-protector-all... yes
checking whether C compiler accepts -Wstack-protector... yes
checking whether C++ compiler accepts -Wstack-protector... yes
checking whether C compiler accepts --param ssp-buffer-size=1... yes
checking whether C++ compiler accepts --param ssp-buffer-size=1... yes
checking whether C compiler accepts -fPIE... yes
checking whether C++ compiler accepts -fPIE... yes
checking whether the linker accepts -fPIE -pie... no
checking whether the linker accepts -fPIE -Wl,-pie... yes
checking whether the linker accepts -Wl,-z,relro... no
checking whether C++ compiler accepts -fno-default-inline... no
checking whether C++ compiler accepts -pipe... yes
checking for library containing utempter_remove_record... no
configure: WARNING: Unable to find libutempter; utmp entries will not be made.
checking for library containing compress... -lz
checking for library containing socket... none required
checking for library containing inet_addr... none required
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /nix/store/xdg4rn8dprpkkzany58z61s0n8mvjszr-gnugrep-2.21/bin/grep
checking for egrep... /nix/store/xdg4rn8dprpkkzany58z61s0n8mvjszr-gnugrep-2.21/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for sys/stat.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking pty.h usability... no
checking pty.h presence... no
checking for pty.h... no
checking util.h usability... yes
checking util.h presence... yes
checking for util.h... yes
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking endian.h usability... no
checking endian.h presence... no
checking for endian.h... no
checking sys/endian.h usability... no
checking sys/endian.h presence... no
checking for sys/endian.h... no
checking utmpx.h usability... yes
checking utmpx.h presence... yes
checking for utmpx.h... yes
checking termio.h usability... no
checking termio.h presence... no
checking for termio.h... no
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int64_t... yes
checking for pid_t... yes
checking for C/C++ restrict keyword... __restrict
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for uintptr_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether mbrtowc and mbstate_t are properly declared... yes
checking for gettimeofday... yes
checking for setrlimit... yes
checking for iswprint... yes
checking for memchr... yes
checking for memset... yes
checking for nl_langinfo... yes
checking for posix_memalign... yes
checking for setenv... yes
checking for setlocale... yes
checking for sigaction... yes
checking for socket... yes
checking for strchr... yes
checking for strdup... yes
checking for strncasecmp... yes
checking for strtok... yes
checking for strerror... yes
checking for strtol... yes
checking for wcwidth... yes
checking for cfmakeraw... yes
checking for pselect... yes
checking for getaddrinfo... yes
checking for getnameinfo... yes
checking for library containing clock_gettime... no
checking for pkg-config... /nix/store/hwi5wsri3ji74378irrig7s5m6paxp7q-pkg-config-0.28/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for OPENSSL... yes
checking for TINFO... no
checking for TINFO... yes
checking whether forkpty is declared... no
checking for forkpty in -lutil... no
checking whether pipe2(..., O_CLOEXEC) is supported... no
checking whether FD_ISSET() argument is const... yes
checking whether __builtin_bswap64 is declared... no
checking whether __builtin_ctz is declared... no
checking whether mach_absolute_time is declared... yes
checking whether be64toh is declared... no
checking whether betoh64 is declared... no
checking whether OSSwapHostToBigInt64 is declared... yes
checking whether IP_MTU_DISCOVER is declared... no
checking whether IP_RECVTOS is declared... no
checking whether __STDC_ISO_10646__ is declared... no
configure: WARNING: C library doesn't advertise wchar_t is Unicode (OS X works anyway with workaround).
checking whether IUTF8 is declared... yes
checking for protobuf... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/crypto/Makefile
config.status: creating src/frontend/Makefile
config.status: creating src/network/Makefile
config.status: creating src/protobufs/Makefile
config.status: creating src/statesync/Makefile
config.status: creating src/terminal/Makefile
config.status: creating src/util/Makefile
config.status: creating scripts/Makefile
config.status: creating src/examples/Makefile
config.status: creating src/tests/Makefile
config.status: creating man/Makefile
config.status: creating conf/Makefile
config.status: creating config.h
config.status: executing depfiles commands
configure:  === Configuration results ===
configure: Version:             1.2.5
configure: c++ compiler:        clang++
configure: Warning CXXFLAGS:    -Wall
configure: Picky CXXFLAGS:
configure: Harden CFLAGS:        -fno-strict-overflow -D_FORTIFY_SOURCE=2 -fstack-protector-all -Wstack-protector --param ssp-buffer-size=1 -fPIE
configure:  =============================
building
make flags: SHELL=/nix/store/lqk1zn0p3b58x5fib175zi9nmz18r5g3-bash-4.3-p42/bin/bash
make  all-recursive
make[1]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5'
Making all in src
make[2]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src'
Making all in protobufs
make[3]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/protobufs'
  GEN      userinput.pb.cc
  GEN      hostinput.pb.cc
  GEN      transportinstruction.pb.cc
make  all-am
make[4]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/protobufs'
  CXX      userinput.pb.o
  CXX      hostinput.pb.o
  CXX      transportinstruction.pb.o
  AR       libmoshprotos.a
make[4]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/protobufs'
make[3]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/protobufs'
Making all in util
make[3]: Entering directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/util'
  CXX      locale_utils.o
  CXX      swrite.o
  CXX      select.o
  CXX      timestamp.o
  CXX      pty_compat.o
pty_compat.cc:42:10: fatal error: 'sys/stropts.h' file not found
#include <sys/stropts.h>
         ^
1 error generated.
Makefile:352: recipe for target 'pty_compat.o' failed
make[3]: *** [pty_compat.o] Error 1
make[3]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src/util'
Makefile:331: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5/src'
Makefile:378: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/private/var/folders/g0/80z2tlp95k3gdmx68vhslfl80000gn/T/nix-build-mosh-1.2.5.drv-0/mosh-1.2.5'
Makefile:318: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/348zch7hhrr4abb6zslyc3lhqjjrj3pa-mosh-1.2.5.drv’ failed with exit code 2
error: build of ‘/nix/store/348zch7hhrr4abb6zslyc3lhqjjrj3pa-mosh-1.2.5.drv’ failed
```

**Comment by henrytill** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/commit/772960bcb7c7b49661f355e36c83962444c2d0c8

**Comment by pipping** [comment]
Indeed, this works for me

```
% uname -v   
Darwin Kernel Version 15.6.0: Tue May 17 20:05:28 PDT 2016; root:xnu-3248.60.3~4/RELEASE_X86_64
% which mosh
.../.nix-profile/bin/mosh
% mosh --version
mosh 1.2.5 [build mosh 1.2.5]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
% 
```

I believe this issue can be closed.

**Comment by benmont** [comment]
Confirmed, no longer reproduces against HEAD.
