### ISSUE TITLE
asciidoctor: add bibtex support

### ISSUE THREAD

**Issue by tg-x** [NixOS/nixpkgs#106364]
**Describe the bug**
include [asciidoctor-bibtex](https://github.com/asciidoctor/asciidoctor-bibtex) in the asciidoctor package

**Notify maintainers**
@gpyh @nicknovitski

**Comment by doronbehar** [comment]
I would like this too. I tried this diff:

```difff
diff --git i/pkgs/tools/typesetting/asciidoctor/Gemfile w/pkgs/tools/typesetting/asciidoctor/Gemfile
index 702dabee2e0..b007b1d3168 100644
--- i/pkgs/tools/typesetting/asciidoctor/Gemfile
+++ w/pkgs/tools/typesetting/asciidoctor/Gemfile
@@ -5,6 +5,7 @@ gem 'asciidoctor-pdf'
 gem 'asciidoctor-epub3'
 gem 'asciidoctor-mathematical'
 gem 'asciidoctor-revealjs'
+gem 'asciidoctor-bibtex'
 gem 'coderay'
 gem 'pygments.rb'
 gem 'rouge'
diff --git i/pkgs/tools/typesetting/asciidoctor/default.nix w/pkgs/tools/typesetting/asciidoctor/default.nix
index 29b2b567be2..55db3614358 100644
--- i/pkgs/tools/typesetting/asciidoctor/default.nix
+++ w/pkgs/tools/typesetting/asciidoctor/default.nix
@@ -11,6 +11,7 @@ let
 
     exes = [
       "asciidoctor"
+      "asciidoctor-bibtex"
       "asciidoctor-pdf"
       "asciidoctor-epub3"
       "asciidoctor-revealjs"
```

And then I ran:

```
./maintainers/scripts/update-ruby-packages
```

According to the manual:

https://nixos.org/manual/nixpkgs/unstable/#sec-language-ruby

But it failed:

```
make: Entering directory '/build/git-2.29.2/contrib/subtree'
make -C ../../ GIT-VERSION-FILE
make[1]: Entering directory '/build/git-2.29.2'
make[1]: 'GIT-VERSION-FILE' is up to date.
make[1]: Leaving directory '/build/git-2.29.2'
install -d -m 755 /nix/store/8as13bxzifw7fgdzcwvk20qqbln3qd0b-git-2.29.2/libexec/git-core
install -m 755 git-subtree /nix/store/8as13bxzifw7fgdzcwvk20qqbln3qd0b-git-2.29.2/libexec/git-core
asciidoctor -b docbook -d manpage  \
        -agit_version=2.29.2 -I../../Documentation -rasciidoctor-extensions -alitdd='&#x2d;&#x2d;' git-subtree.txt
`/homeless-shelter` is not a directory.
Bundler will use `/build/bundler20201215-11155-br5j8s11155' as your home directory temporarily.
Traceback (most recent call last):
        3: from /nix/store/7jckg3adcrvzp8ansbq4y360bajhvafw-asciidoctor-2.0.10/bin/asciidoctor:18:in `<main>'
        2: from /nix/store/y31qcq2h21vv5x65q036w3b2r9q425q5-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
        1: from /nix/store/y31qcq2h21vv5x65q036w3b2r9q425q5-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:13:in `setup'
/nix/store/y31qcq2h21vv5x65q036w3b2r9q425q5-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:466:in `ensure_equivalent_gemfile_and_lockfile': You are trying to install in deployment mode after changing (Bundler::ProductionError)
your Gemfile. Run `bundle install` elsewhere and add the
updated ../../../../nix/store/gcb57k1kvn9hvb1nb3x2gws8mv1gs6ha-gemfile-and-lockfile/Gemfile.lock to version control.

If this is a development machine, remove the /nix/store/gcb57k1kvn9hvb1nb3x2gws8mv1gs6ha-gemfile-and-lockfile/Gemfile freeze
by running `bundle install --no-deployment`.

The dependencies in your gemfile changed

You have added to the Gemfile:
* asciidoctor-bibtex
make: *** [Makefile:86: git-subtree.xml] Error 1
make: Leaving directory '/build/git-2.29.2/contrib/subtree'
```

Not experienced enough with the ruby ecosystem to know what to do.

**Comment by doronbehar** [comment]
So I learn from https://github.com/NixOS/nixpkgs/pull/106971 that this issue is not so hard to tackle - just add:

```diff
diff --git i/pkgs/tools/typesetting/asciidoctor/Gemfile w/pkgs/tools/typesetting/asciidoctor/Gemfile
index 702dabee2e0..3aaea5bdf5a 100644
--- i/pkgs/tools/typesetting/asciidoctor/Gemfile
+++ w/pkgs/tools/typesetting/asciidoctor/Gemfile
@@ -1,5 +1,8 @@
 source 'https://rubygems.org'
 gem 'asciidoctor'
+gem 'asciidoctor-bibtex'
 gem 'asciidoctor-diagram'
 gem 'asciidoctor-pdf'
 gem 'asciidoctor-epub3'
```

And run:

```
nix-shell maintainers/scripts/update.nix --argstr package asciidoctor
```

And seeing that this is so easy, I wonder why not add more extensions to asciidoctor's runtime, but this is of course at the price of closure size. @nicknovitski and @yacinehmito what do you think? We could also have a separate `asciidoctor-with-extensions` attribute with more gems at the runtime of it...

**Comment by InLaw** [comment]
@doronbehar 
is there progress to adjust the package to a "asciidoctor-with-extensions"-format?

**Comment by doronbehar** [comment]
Yes: #149935.
