### ISSUE TITLE
Tkinter problem on darwin

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#10667]
i get this problem on OS X 10.9.5 but not on NixOS.

code of guitest.py

```
#! /usr/bin/env nix-shell
#! nix-shell -i python -p python python27Packages.tkinter

import Tkinter

class simpleapp_tk(Tkinter.Tk):
    def __init__(self,parent):
        Tkinter.Tk.__init__(self,parent)
        self.parent = parent
        self.initialize()

    def initialize(self):
        pass

if __name__ == "__main__":
    app = simpleapp_tk(None)
    app.title('my application')
    app.mainloop()
```

```
Traceback (most recent call last):
  File "./guitest.py", line 16, in <module>
    app = simpleapp_tk(None)
  File "./guitest.py", line 8, in __init__
    Tkinter.Tk.__init__(self,parent)
  File "/nix/store/qp0d2fi7bqsb3vl1qpknc294klq4g9zp-python-2.7.10/lib/python2.7/lib-tk/Tkinter.py", line 1816, in __init__
    self._loadtk()
  File "/nix/store/qp0d2fi7bqsb3vl1qpknc294klq4g9zp-python-2.7.10/lib/python2.7/lib-tk/Tkinter.py", line 1832, in _loadtk
    % (_tkinter.TK_VERSION, tk_version)
RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
```

same error with `#! nix-shell -i python3 -p python3`

**Comment by domenkozar** [comment]
@datakurre ideas? it works on NixOS.

**Comment by datakurre** [comment]
I can reproduce this with the latest master and new pure darwin stdenv with the changes below. I'll flag this for ##nix-darwin for an issue to be resolved. /cc @pikajude 

```
diff --git a/pkgs/development/interpreters/python/2.7/default.nix b/pkgs/development/interpreters/python/2.7/default.nix
index 6f951bc..79cea58 100644
--- a/pkgs/development/interpreters/python/2.7/default.nix
+++ b/pkgs/development/interpreters/python/2.7/default.nix
@@ -1,5 +1,5 @@
 { stdenv, fetchurl, self, callPackage
-, bzip2, openssl, gettext
+, bzip2, openssl, gettext, darwin
 
 , includeModules ? false
 
@@ -249,7 +249,10 @@ let
 
     tkinter = if stdenv.isCygwin then null else (buildInternalPythonModule {
       moduleName = "tkinter";
-      deps = [ tcl tk xlibsWrapper libX11 ];
+      deps = [ tcl tk xlibsWrapper libX11 
+               darwin.apple_sdk.frameworks.Cocoa
+               darwin.apple_sdk.frameworks.Tcl
+               darwin.apple_sdk.frameworks.Tk];
     });
 
   } // {
diff --git a/pkgs/os-specific/darwin/apple-sdk/frameworks.nix b/pkgs/os-specific/darwin/apple-sdk/frameworks.nix
index 750adfe..b828e55 100644
--- a/pkgs/os-specific/darwin/apple-sdk/frameworks.nix
+++ b/pkgs/os-specific/darwin/apple-sdk/frameworks.nix
@@ -100,7 +100,7 @@ with frameworks; with libs; {
   SystemConfiguration     = [ CF Security ];
   TWAIN                   = [ Carbon ];
   Tcl                     = [];
-  Tk                      = [ ApplicationServices Carbon X11 ];
+  Tk                      = [ ApplicationServices Carbon ];
   VideoDecodeAcceleration = [ CF CoreVideo ];
   VideoToolbox            = [ CF CoreMedia CoreVideo ];
   WebKit                  = [ ApplicationServices Carbon JavaScriptCore OpenGL ];
diff --git a/pkgs/os-specific/darwin/apple-sdk/impure-deps.nix b/pkgs/os-specific/darwin/apple-sdk/impure-deps.nix
index 94152d1..d2d1c93 100644
--- a/pkgs/os-specific/darwin/apple-sdk/impure-deps.nix
+++ b/pkgs/os-specific/darwin/apple-sdk/impure-deps.nix
@@ -252,6 +252,12 @@ rec {
   SecurityFoundation = [
     "/System/Library/Frameworks/SecurityFoundation.framework"
   ];
+  Tcl = [
+    "/System/Library/Frameworks/Tcl.framework"
+  ];
+  Tk = [
+    "/System/Library/Frameworks/Tk.framework"
+  ];
   Kernel = [
     "/System/Library/Frameworks/Kernel.framework"
   ];
```

**Comment by datakurre** [comment]
Was already flagged and known issue.

**Comment by FRidh** [comment]
Has this been fixed? Is this issue still relevant?

**Comment by davidak** [comment]
build of python27Packages.tkinter fails on nixpkgs master.

http://ipfsbin.xyz/#QmePDtMzqb6iGS6PQZsrqLwhXfU8rzTYXts2gNEeEMjcq3

with python3 i just get:

```
[nix-shell:~]$ python3 guitest.py
Traceback (most recent call last):
  File "guitest.py", line 1, in <module>
    import Tkinter
ImportError: No module named 'Tkinter'
```

there is no `python35Packages.tkinter`.

**Comment by FRidh** [comment]
The Python 3.x module is named `tkinter`, instead of `Tkinter`, and is on Nix not in any separate derivation contrary to 2.x.

**Comment by davidak** [comment]
@FRidh thanks.

simple example with python3 also fails:
```
#! /usr/bin/env nix-shell
#! nix-shell -i python3 -p python3

import tkinter
top = tkinter.Tk()
top.mainloop()
```

```
imac:Python davidak$ ./guitest.py
Traceback (most recent call last):
  File "./guitest.py", line 6, in <module>
    import tkinter
  File "/nix/store/gzsbc240vkz13z5wypmlkm2kh1gmw1f6-python3-3.5.2/lib/python3.5/tkinter/__init__.py", line 35, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named '_tkinter'
```

build of python-tkinter-2.7.12 still fails:

```
creating Modules/Setup
creating Modules/Setup.local
creating Makefile
building
running build_ext
sh: file: command not found
building '_tkinter' extension
creating build/temp.macosx-10.7-x86_64-2.7/private
creating build/temp.macosx-10.7-x86_64-2.7/private/var
creating build/temp.macosx-10.7-x86_64-2.7/private/var/folders
creating build/temp.macosx-10.7-x86_64-2.7/private/var/folders/fb
creating build/temp.macosx-10.7-x86_64-2.7/private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn
creating build/temp.macosx-10.7-x86_64-2.7/private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T
creating build/temp.macosx-10.7-x86_64-2.7/private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T/nix-build-python-tkinter-2.7.12.drv-0
creating build/temp.macosx-10.7-x86_64-2.7/private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T/nix-build-python-tkinter-2.7.12.drv-0/Python-2.7.12
creating build/temp.macosx-10.7-x86_64-2.7/private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T/nix-build-python-tkinter-2.7.12.drv-0/Python-2.7.12/Modules
clang -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DWITH_APPINIT=1 -I/Library/Frameworks/Tcl.framework/Headers -I/Library/Frameworks/Tcl.framework/Versions/Current/PrivateHeaders -I/Library/Frameworks/Tk.framework/Headers -I/Library/Frameworks/Tk.framework/Versions/Current/PrivateHeaders -I/no-such-path/X11R6/include -I/nix/store/n3bdl0kg02d11qpww05bmhx68xq191ld-python-2.7.12/include -I. -IInclude -I./Include -I/nix/store/n3bdl0kg02d11qpww05bmhx68xq191ld-python-2.7.12/include/python2.7 -c /private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T/nix-build-python-tkinter-2.7.12.drv-0/Python-2.7.12/Modules/_tkinter.c -o build/temp.macosx-10.7-x86_64-2.7/private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T/nix-build-python-tkinter-2.7.12.drv-0/Python-2.7.12/Modules/_tkinter.o -framework Tk
clang-3.7: warning: -framework Tk: 'linker' input unused
clang-3.7: warning: argument unused during compilation: '-fno-strict-overflow'
/private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T/nix-build-python-tkinter-2.7.12.drv-0/Python-2.7.12/Modules/_tkinter.c:1178:38: warning: incompatible pointer types passing 'Py_UNICODE *' (aka 'unsigned int *') to parameter of type 'const Tcl_UniChar *' (aka 'const unsigned short *') [-Wincompatible-pointer-types]
            return Tcl_NewUnicodeObj(inbuf, size);
                                     ^~~~~
/nix/store/xqqg00f9z3p3f1iyasg8qfzr81vjnz1a-tcl-8.6.6/include/tclDecls.h:1103:55: note: passing argument to parameter 'unicode' here
EXTERN Tcl_Obj *        Tcl_NewUnicodeObj(const Tcl_UniChar *unicode,
                                                             ^
1 warning generated.
clang -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DWITH_APPINIT=1 -I/Library/Frameworks/Tcl.framework/Headers -I/Library/Frameworks/Tcl.framework/Versions/Current/PrivateHeaders -I/Library/Frameworks/Tk.framework/Headers -I/Library/Frameworks/Tk.framework/Versions/Current/PrivateHeaders -I/no-such-path/X11R6/include -I/nix/store/n3bdl0kg02d11qpww05bmhx68xq191ld-python-2.7.12/include -I. -IInclude -I./Include -I/nix/store/n3bdl0kg02d11qpww05bmhx68xq191ld-python-2.7.12/include/python2.7 -c /private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T/nix-build-python-tkinter-2.7.12.drv-0/Python-2.7.12/Modules/tkappinit.c -o build/temp.macosx-10.7-x86_64-2.7/private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T/nix-build-python-tkinter-2.7.12.drv-0/Python-2.7.12/Modules/tkappinit.o -framework Tk
clang-3.7: warning: -framework Tk: 'linker' input unused
clang-3.7: warning: argument unused during compilation: '-fno-strict-overflow'
creating build/lib.macosx-10.7-x86_64-2.7
clang -bundle -undefined dynamic_lookup build/temp.macosx-10.7-x86_64-2.7/private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T/nix-build-python-tkinter-2.7.12.drv-0/Python-2.7.12/Modules/_tkinter.o build/temp.macosx-10.7-x86_64-2.7/private/var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T/nix-build-python-tkinter-2.7.12.drv-0/Python-2.7.12/Modules/tkappinit.o -L/nix/store/n3bdl0kg02d11qpww05bmhx68xq191ld-python-2.7.12/lib -o build/lib.macosx-10.7-x86_64-2.7/_tkinter.so -framework Tcl -framework Tk
ld: warning: directory not found for option '-L/nix/store/a8gicd4d85bc5j73s6rs601v5fga6yja-xlibs-wrapper/lib'
ld: framework not found Tcl
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)

Python build finished, but the necessary bits to build these modules were not found:
_bsddb     _curses    _curses_panel
_sqlite3   _ssl       bsddb185
bz2        dbm        dl
gdbm       imageop    linuxaudiodev
nis        ossaudiodev   readline
spwd       sunaudiodev   zlib
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


Failed to build these modules:
_tkinter

installing
cp: missing destination file operand after '/nix/store/m10dzar03bpksqm6w1wmj7bl6s520r25-python-tkinter-2.7.12/lib/python2.7/site-packages/'
Try 'cp --help' for more information.
builder for ‘/nix/store/jcp1r9xvz8bj2hvwk4qvklzi5szq2pr4-python-tkinter-2.7.12.drv’ failed with exit code 1
error: build of ‘/nix/store/jcp1r9xvz8bj2hvwk4qvklzi5szq2pr4-python-tkinter-2.7.12.drv’ failed
```

on master (nixpkgs-17.03pre93141.e3deccc)

**Comment by FRidh** [comment]
The following works:
```
#! /usr/bin/env nix-shell
#! nix-shell -i python3 -p 'python3.withPackages(ps:[ps.tkinter])'

import tkinter
top = tkinter.Tk()
top.mainloop()
```
