### ISSUE TITLE
Exiting tui in gdb causes a segfault

### ISSUE THREAD

**Issue by jamii** [NixOS/nixpkgs#106868]
**Describe the bug**
Exiting tui mode in gdb causes a segfault. This is not the case on other platforms.

**To Reproduce**
Run `gdb -tui`. Type `tui disable` and hit return.

```
jamie@machine:~$ gdb -tui focus/test
Aborted (core dumped)

[nix-shell:~]$ lz4cat /var/lib/systemd/coredump/core.gdb.1000.a7b8b2b782434a4d8fe6be07cb8cb0d9.4596.1607891435000000.lz4 > gdb.dump

[nix-shell:~]$ gdb gdb ./gdb.dump
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gdb...
(No debugging symbols found in gdb)
[New LWP 4596]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libthread_db.so.1".
Core was generated by `gdb -tui focus/test'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007feff0fc808a in raise ()
   from /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libc.so.6
(gdb) bt
#0  0x00007feff0fc808a in raise ()
   from /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libc.so.6
#1  0x00007feff0fb2528 in abort ()
   from /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libc.so.6
#2  0x000000000041b64c in handle_sigsegv(int) [clone .cold] ()
#3  <signal handler called>
#4  0x00007feff1000c61 in fwrite ()
   from /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libc.so.6
#5  0x00007feff1ce6734 in _rl_output_some_chars ()
   from /nix/store/bcjk6hwdn1aq7m45a042a9k1lqih74ja-readline-8.0p4/lib/libreadline.so.8
#6  0x00007feff1cdf6d9 in update_line ()
   from /nix/store/bcjk6hwdn1aq7m45a042a9k1lqih74ja-readline-8.0p4/lib/libreadline.so.8
#7  0x00007feff1ce177f in rl_redisplay ()
   from /nix/store/bcjk6hwdn1aq7m45a042a9k1lqih74ja-readline-8.0p4/lib/libreadline.so.8
#8  0x00007feff1ccbc33 in readline_internal_setup ()
   from /nix/store/bcjk6hwdn1aq7m45a042a9k1lqih74ja-readline-8.0p4/lib/libreadline.so.8
#9  0x00007feff1ce5479 in _rl_callback_newline ()
   from /nix/store/bcjk6hwdn1aq7m45a042a9k1lqih74ja-readline-8.0p4/lib/libreadline.so.8
#10 0x00007feff1ce54c8 in rl_callback_handler_install ()
   from /nix/store/bcjk6hwdn1aq7m45a042a9k1lqih74ja-readline-8.0p4/lib/libreadline.so.8
#11 0x000000000059efd0 in gdb_rl_callback_handler_install(char const*) ()
#12 0x000000000059fbff in display_gdb_prompt(char const*) ()
#13 0x000000000059f9ec in gdb_rl_callback_handler(char*) ()
#14 0x00007feff1ce5a20 in rl_callback_read_char ()
   from /nix/store/bcjk6hwdn1aq7m45a042a9k1lqih74ja-readline-8.0p4/lib/libreadline.so.8
#15 0x000000000059ecfe in gdb_rl_callback_read_char_wrapper_noexcept() ()
#16 0x000000000059f8b1 in gdb_rl_callback_read_char_wrapper(void*) ()
#17 0x000000000059ec1c in stdin_event_handler(int, void*) ()
#18 0x000000000059d906 in gdb_wait_for_event(int) ()
#19 0x000000000059de6c in gdb_do_one_event() ()
#20 0x000000000059df25 in start_event_loop() ()
#21 0x000000000066eeae in captured_command_loop() ()
#22 0x0000000000670dd5 in gdb_main(captured_main_args*) ()
#23 0x000000000042e7ac in main ()
```

I also have an rr recording if needed.

**Notify maintainers**
@globin @lsix

**Metadata**
```
jamie@machine:~/nixpkgs$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.80, NixOS, 20.09.2076.ffb3aab257e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(jamie): `""`
 - channels(root): `"nixos-20.09.2076.ffb3aab257e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lsix** [comment]
Yep, I can reproduce it, I’ll to look into that asap

**Comment by lsix** [comment]
I have opened a PR that fixes this by back-porting the fix that was already available upstream (https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=a350efd4fb368a35ada608f6bc26ccd3bed0ae6b).

**Comment by jamii** [comment]
Wow, that was fast. Thanks so much :)

**Comment by jamii** [comment]
I'm afraid I don't have access to a computer at the moment due to some border-related excitement. Should be able to confirm by the end of the week.

**Comment by lsix** [comment]
No problem. Just let me know when you see fIt so I close the issue.

**Comment by jamii** [comment]
Yep, this works for me on the latest unstable. Thanks @lsix
