### ISSUE TITLE
pythonPackages.python-prctl fails to build

### ISSUE THREAD

**Issue by MetaDark** [NixOS/nixpkgs#106871]
**Describe the bug**
Recently, `python-prctl` started failing to build due to a test failure in `test_speculation_ctrl`.

**To Reproduce**
1. `nix-build '<nixpkgs>' -A python38Packages.python-prctl`

```
======================================================================
ERROR: test_speculation_ctrl (test_prctl.PrctlTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-prctl-1.8.1/test_prctl.py", line 335, in test_speculation_ctrl
    prctl.set_speculation_ctrl(prctl.SPEC_STORE_BYPASS, prctl.SPEC_ENABLE)
  File "/build/python-prctl-1.8.1/build/lib.linux-x86_64-3.8/prctl.py", line 19, in call_prctl
    return _prctl.prctl(option, arg, arg2)
PermissionError: [Errno 1] Operation not permitted

----------------------------------------------------------------------
```

**Expected behavior**
Should build succesfully

**Notify maintainers**
@catern 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 21.03pre257780.e9158eca70a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-21.03pre257780.e9158eca70a, nur"`
 - channels(kira): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python27Packages.python-prctl, python37Packages.python-prctl, python38Packages.python-prctl
# a list of nixos modules affected by the problem
module:
```

**Comment by MetaDark** [comment]
@FRidh The failure seems to be caused by the recent upgrade: dbe5c3d3582e1bf4a4ba3600948d3d3383cf8531
