### ISSUE TITLE
package request: rkvm: Virtual KVM switch for Linux machines 

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#108276]
**Project description**
It's like synergy or barrier, but supports wayland and windows as well.

I started packaging it [here](https://github.com/colemickens/nixcfg/tree/main/pkgs/rkvm), but it doesn't build yet (`build.rs` fails to find the evdev files it wants).

**Metadata**

* homepage URL: https://github.com/htrefil/rkvm
* source URL: https://github.com/htrefil/rkvm
* license: mit
* platforms: linux

**Comment by colemickens** [comment]
here's the build log so far: https://gist.githubusercontent.com/colemickens/82187cfd7fdb250bfe76ce3112b4e906/raw/c244abd314ccd69cd5500e01ebac77ea27bd0711/gistfile0.txt

**Comment by colemickens** [comment]
`glue/glue.h:1:10: fatal error: 'libevdev/libevdev.h' file not found`

**Comment by colemickens** [comment]
well, this is probably the issue: https://github.com/htrefil/rkvm/blob/ec404c69b38f7feff5103f898612734ee8d7ee95/input/build.rs#L18

I'll file an issue.

**Comment by thiagokokada** [comment]
@colemickens If this is the only issue you can probably patch it like this:

```
diff --git a/input/build.rs b/input/build.rs
index a267b65..c5a35df 100644
--- a/input/build.rs
+++ b/input/build.rs
@@ -15,7 +15,7 @@ fn main() {
     // TODO: pkg-config
     let bindings = Builder::default()
         .header("glue/glue.h")
-        .clang_arg("-I/usr/include/libevdev-1.0/")
+        .clang_arg("-I@LIBEVDEV@")
         .parse_callbacks(Box::new(CargoCallbacks))
         .generate()
         .unwrap();
```

And during `preInstall` phrase you can use `substituteInPlace` or `sed` to substitute `@LIBDEV@` with `$libevdev`. Should work.

**Comment by colemickens** [comment]
Good idea. Another weird one popped out though:

```
...
   Compiling bincode v1.3.1
   Compiling toml v0.5.8
error: failed to run custom build command for `input v0.2.0 (/build/source/input)`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/input-8e4ca7164380d3b7/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=glue/glue.h
  cargo:rustc-link-lib=evdev

  --- stderr
  /nix/store/2sykgd31iyfq537bhqd9y5irxksgyjhm-libevdev-1.10.0/include/libevdev-1.0/libevdev/libevdev.h:30:10: fatal error: 'linux/input.h' file not found
  /nix/store/2sykgd31iyfq537bhqd9y5irxksgyjhm-libevdev-1.10.0/include/libevdev-1.0/libevdev/libevdev.h:30:10: fatal error: 'linux/input.h' file not found, er>
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', input/build.rs:21:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Not sure what's up, since libevdev does not seem to actually come with that header file included... and from what I can tell ubuntu's libevdev-dev packages don't either??

**Comment by colemickens** [comment]
Weird, debian's libevdev-dev pkg:

```
❯ tar xvf data.tar.xz 
./
./usr/
./usr/include/
./usr/include/libevdev-1.0/
./usr/include/libevdev-1.0/libevdev/
./usr/include/libevdev-1.0/libevdev/libevdev-uinput.h
./usr/include/libevdev-1.0/libevdev/libevdev.h
./usr/lib/
./usr/lib/x86_64-linux-gnu/
./usr/lib/x86_64-linux-gnu/libevdev.a
./usr/lib/x86_64-linux-gnu/pkgconfig/
./usr/lib/x86_64-linux-gnu/pkgconfig/libevdev.pc
./usr/share/
./usr/share/doc/
./usr/share/doc/libevdev-dev/
./usr/share/doc/libevdev-dev/changelog.Debian.gz
./usr/share/doc/libevdev-dev/copyright
./usr/share/man/
./usr/share/man/man3/
./usr/share/man/man3/libevdev.3.gz
./usr/lib/x86_64-linux-gnu/libevdev.so
```

**Comment by colemickens** [comment]
Looks like I misunderstood. I think they bundle their input.h for building their lib, but expect `linuxHeaders` to be providing `linux/input.h`, so I'm adding that to the clang_args too...

**Comment by colemickens** [comment]
Okay, update:

```nix
{ stdenv, rustPlatform, fetchFromGitHub
, pkg-config, libevdev, openssl, llvmPackages_latest, linuxHeaders }:

let
  metadata = import ./metadata.nix;
in
rustPlatform.buildRustPackage rec {
  pname = "rkvm";
  version = metadata.rev;

  src = fetchFromGitHub {
    owner = "htrefil";
    repo = pname;
    rev = metadata.rev;
    sha256 = metadata.sha256;
  };

  cargoSha256 = metadata.cargoSha256;

  postPatch = ''
    # patch in libevdev/include + linuxHeaders/include
    sed -i 's|.clang_arg("-I/usr/include/libevdev-1.0/")|.clang_arg("-I${libevdev}/include/libevdev-1.0").clang_arg("-I${linuxHeaders}/include")|g' ./input/build.rs
  '';

  nativeBuildInputs = [ pkg-config openssl llvmPackages_latest.libclang ];
  LIBCLANG_PATH = "${llvmPackages_latest.libclang}/lib";
  buildInputs = [ libevdev openssl linuxHeaders ];

  meta = with stdenv.lib; {
    description = "Virtual KVM switch for Linux machines";
    homepage = "https://github.com/htrefil/rkvm";
    license = licenses.mit;
    maintainers = [ maintainers.colemickens ];
  };
}
```

error:
```
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95> error: failed to run custom build command for `input v0.2.0 (/build/source/input)`
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95> Caused by:
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95>   process didn't exit successfully: `/build/source/target/release/build/input-8e4ca7164380d3b7/build-script-build` (exit code: 101)
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95>   --- stdout
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95>   cargo:rerun-if-changed=glue/glue.h
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95>   cargo:rustc-link-lib=evdev
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95>   --- stderr
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95>   /nix/store/0avnch9kw2il7xqssha6ahxx03i38xi9-linux-headers-5.9.8/include/linux/input.h:13:10: fatal error: 'sys/time.h' file not found
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95>   /nix/store/0avnch9kw2il7xqssha6ahxx03i38xi9-linux-headers-5.9.8/include/linux/input.h:13:10: fatal error: 'sys/time.h' file not found, err: true
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95>   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', input/build.rs:21:10
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95> warning: build failed, waiting for other jobs to finish...
rkvm-ec404c69b38f7feff5103f898612734ee8d7ee95> error: build failed
```

**Comment by I-Want-ToBelieve** [comment]
default.nix

```nix
{
  lib,
  rustPlatform,
  fetchFromGitHub,
  pkg-config,
  libevdev,
  openssl,
  llvmPackages,
  linuxHeaders,
}:
rustPlatform.buildRustPackage rec {
  pname = "rkvm";
  version = "0.3.3";

  # src = fetchFromGitHub {
  #   owner = "htrefil";
  #   repo = "rkvm";
  #   rev = "master";
  #   hash = "";
  # };

  src = ./.;

  cargoLock = {
    lockFile = ./Cargo.lock;
    outputHashes = {
    };
  };

  nativeBuildInputs = [llvmPackages.clang pkg-config];

  buildInputs = [libevdev openssl linuxHeaders];

  LIBCLANG_PATH = lib.makeLibraryPath [llvmPackages.libclang];

  # The libevdev bindings preserve comments from libev, some of which
  # contain indentation which Cargo tries to interpret as doc tests.
  doCheck = false;

  meta = with lib; {
    description = "Virtual KVM switch for Linux machines";
    homepage = "https://github.com/htrefil/rkvm";
    license = licenses.mit;
    maintainers = with maintainers; [colemickens];
    platforms = platforms.linux;
  };
}
```

**Comment by byrongibson** [comment]
What's the status on this, doesn't look like it's made it into the binary cache yet.  Is it a 23.11 addition?

**Comment by colemickens** [comment]
@byrongibson the PR is still being reviewed: https://github.com/NixOS/nixpkgs/pull/250792
