### ISSUE TITLE
darwin: ffmpeg build failure

### ISSUE THREAD

**Issue by benmont** [NixOS/nixpkgs#10827]
```
Making all in examples
make[2]: Entering directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-audiofile-0.3.6.drv-0/audiofile-0.3.6/examples'
clang -DHAVE_CONFIG_H -I. -I.. -I../libaudiofile    -g -O2 -c adddcoffset.c
/nix/store/ifmxr73y49plvswmbl97ml105kfg738x-bash-4.3-p42/bin/bash ../libtool --tag=CC   --mode=link clang  -g -O2   -o adddcoffset adddcoffset.o ../libaudiofile/libaudiofile.la
libtool: link: clang -g -O2 -o .libs/adddcoffset adddcoffset.o  ../libaudiofile/.libs/libaudiofile.dylib -lm
clang -DHAVE_CONFIG_H -I. -I.. -I../libaudiofile    -g -O2 -c power.c
/nix/store/ifmxr73y49plvswmbl97ml105kfg738x-bash-4.3-p42/bin/bash ../libtool --tag=CC   --mode=link clang  -g -O2   -o power power.o ../libaudiofile/libaudiofile.la -lm
libtool: link: clang -g -O2 -o .libs/power power.o  ../libaudiofile/.libs/libaudiofile.dylib -lm
clang -DHAVE_CONFIG_H -I. -I.. -I../libaudiofile    -g -O2 -c osxplay.c
osxplay.c:47:10: fatal error: 'CoreServices/CoreServices.h' file not found
#include <CoreServices/CoreServices.h>
         ^
1 error generated.
Makefile:365: recipe for target 'osxplay.o' failed
make[2]: *** [osxplay.o] Error 1
make[2]: Leaving directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-audiofile-0.3.6.drv-0/audiofile-0.3.6/examples'
Makefile:408: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/private/var/folders/q7/3bmqjbs50cz9jzz0k69n820m0000gp/T/nix-build-audiofile-0.3.6.drv-0/audiofile-0.3.6'
Makefile:312: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/cin1964m684xi0j7vpdxmrf33g798sb0-audiofile-0.3.6.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/2jqq0bdjavab7dphn84ri02bppyw6kz0-SDL-1.2.15.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/bha1icsdh1kkifh5d9hql1rlb6ky4ca5-boehm-gc-7.2f’
killing process 98786
cannot build derivation ‘/nix/store/nvbgz2abzj2wl9pbd9rww73g5ii4ving-ffmpeg-2.7.2.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/nvbgz2abzj2wl9pbd9rww73g5ii4ving-ffmpeg-2.7.2.drv’ failed
Traceback (most recent call last):
  File "/nix/store/08cv7hl3mhxvr7f5ywphfg0jxyd5xk42-nox-0.0.2/bin/.nox-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/3bf8bn66ryfd9aad0pa0d47fifc9v524-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/3bf8bn66ryfd9aad0pa0d47fifc9v524-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/nix/store/3bf8bn66ryfd9aad0pa0d47fifc9v524-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/3bf8bn66ryfd9aad0pa0d47fifc9v524-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/08cv7hl3mhxvr7f5ywphfg0jxyd5xk42-nox-0.0.2/lib/python3.4/site-packages/nox/search.py", line 83, in main
    subprocess.check_call(['nix-env', '-iA', '--show-trace'] + attributes)
  File "/nix/store/j9x359la91dfif21hc4niyxgpyvx3fwz-python3-3.4.3/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nix-env', '-iA', '--show-trace', 'nixpkgs.ffmpeg']' returned non-zero exit status 100
```

**Comment by sjourdois** [comment]
works here in darwin pure

**Comment by zimbatm** [comment]
Having a similar issue on darwin pure.
```
$ uname -a
Darwin Voodoo-Lady.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
$ cat ~/.nixpkgs/config.nix
{
  allowUnfree = true;
  allowBroken = true;
  replaceStdenv = { pkgs }: pkgs.allStdenvs.stdenvDarwinPure;
}
$ nix-env -i ffmpeg
<snip>
clang -DHAVE_CONFIG_H -I. -I.. -I../libaudiofile    -g -O2 -c adddcoffset.c
/nix/store/jxbyzscwyrrhcd2nn7hw71inbrz1zvng-bash-4.3-p42/bin/bash ../libtool --tag=CC   --mode=link clang  -g -O2   -o adddcoffset adddcoffset.o ../libaudiofile/libaudiofile.la
libtool: link: clang -g -O2 -o .libs/adddcoffset adddcoffset.o  ../libaudiofile/.libs/libaudiofile.dylib -lm
clang -DHAVE_CONFIG_H -I. -I.. -I../libaudiofile    -g -O2 -c power.c
/nix/store/jxbyzscwyrrhcd2nn7hw71inbrz1zvng-bash-4.3-p42/bin/bash ../libtool --tag=CC   --mode=link clang  -g -O2   -o power p


ower.o ../libaudiofile/libaudiofile.la -lm


libtool: link: clang -g -O2 -o .libs/power power.o  ../libaudiofile/.libs/libaudiofile.dylib -lm
clang -DHAVE_CONFIG_H -I. -I.. -I../libaudiofile    -g -O2 -c osxplay.c
osxplay.c:47:10: fatal error: 'CoreServices/CoreServices.h' file not found
#include <CoreServices/CoreServices.h>
         ^
1 error generated.
Makefile:365: recipe for target 'osxplay.o' failed
make[2]: *** [osxplay.o] Error 1
make[2]: Leaving directory '/private/var/folders/5c/vpb0xhs56bb2rq2dgmw0pc540000gn/T/nix-build-audiofile-0.3.6.drv-0/audiofile-0.3.6/examples'
Makefile:408: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/private/var/folders/5c/vpb0xhs56bb2rq2dgmw0pc540000gn/T/nix-build-audiofile-0.3.6.drv-0/audiofile-0.3.6'
Makefile:312: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/adx5ww2zyjg0qxm79y78aww91isjsdgg-audiofile-0.3.6.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/xf5n41xyak19qahyzqcbnxxz2s1j2vf6-SDL-1.2.15.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/6r64ca65c7123xcjx4ga26xfcmr2y4d6-soxr-0.1.2-Source.tar.xz’
killing process 26222
cannot build derivation ‘/nix/store/6nxkdbx628j4llvr1kk7xkgwsdqcqmsh-ffmpeg-2.7.2.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/6nxkdbx628j4llvr1kk7xkgwsdqcqmsh-ffmpeg-2.7.2.drv’ failed
```

**Comment by davidak** [comment]
i have the unstable channel on OS X 10.9.5 (64-bit) and get the same error as @zimbatm and @benmont.

```
osxplay.c:47:10: fatal error: 'CoreServices/CoreServices.h' file not found
#include <CoreServices/CoreServices.h>
         ^
1 error generated.
Makefile:365: recipe for target 'osxplay.o' failed
```

**Comment by zimbatm** [comment]
I had the CoreServices.h issue with another package (don't remember which-one) and it was fixed on master. Hopefully staging will be merged soon.

**Comment by sjourdois** [comment]
AKAICT this was fixed in commit aa12640cb913051f646d2422cfdad97616fdb4a0 by Asko Soukka and I'm using master. This probably explains why it worked for me.

**Comment by davidak** [comment]
isn't master the https://nixos.org/channels/nixpkgs-unstable channel?

**Comment by sjourdois** [comment]
nah : https://github.com/NixOS/nixpkgs <https://github.com/NixOS/nixpkgs> is :)

**Comment by ntuckerxx** [comment]
I share @davidak's confusion about where my nixpkgs should be coming from.  A fresh install following the "Get Nix" instructions from the wiki set me up to install things from nixpkgs-unstable, which still has this issue.  If I switch to master I'm able to build ffmpeg.  Does it make sense that the default channel is not master?

**Comment by joachifm** [comment]
Looks like ffmpeg builds on darwin these days
