### ISSUE TITLE
k3s: failed to get rootfs info: failed to get device for dir "/var/lib/kubelet": could not find device with major: 0, minor: 28 in cached partitions map

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#109471]
**Describe the bug**

k3s seems to crash.

```
jan 15 14:48:17 desktop k3s[12426]: W0115 14:48:17.526380   12426 server.go:226] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.541619   12426 server.go:407] Version: v1.19.4+k3s-8f9e5628-dirty
jan 15 14:48:17 desktop k3s[12426]: time="2021-01-15T14:48:17.546898079-05:00" level=info msg="Waiting for node desktop: nodes \"desktop\" not found"
jan 15 14:48:17 desktop k3s[12426]: E0115 14:48:17.556621   12426 node.go:125] Failed to retrieve node info: nodes "desktop" is forbidden: User "system:kube-proxy" cannot get resource "nodes" in API group "" a>
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.586470   12426 dynamic_cafile_content.go:167] Starting client-ca-bundle::/var/lib/rancher/k3s/agent/client-ca.crt
jan 15 14:48:17 desktop k3s[12426]: W0115 14:48:17.683050   12426 nvidia.go:61] NVIDIA GPU metrics will not be available: Could not initialize NVML: could not load NVML library
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.718376   12426 server.go:640] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.719081   12426 container_manager_linux.go:289] container manager verified user specified cgroup-root exists: []
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.719126   12426 container_manager_linux.go:294] Creating Container Manager object based on Node Config: {RuntimeCgroupsName:/systemd/system.slice SystemCgroups>
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.719271   12426 topology_manager.go:126] [topologymanager] Creating topology manager with none policy
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.719298   12426 container_manager_linux.go:324] [topologymanager] Initializing Topology Manager with none policy
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.719310   12426 container_manager_linux.go:329] Creating device plugin manager: true
jan 15 14:48:17 desktop k3s[12426]: W0115 14:48:17.719420   12426 util_unix.go:103] Using "/run/k3s/containerd/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///run/k3s>
jan 15 14:48:17 desktop k3s[12426]: W0115 14:48:17.719533   12426 util_unix.go:103] Using "/run/k3s/containerd/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///run/k3s>
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.719610   12426 kubelet.go:261] Adding pod path: /var/lib/rancher/k3s/agent/pod-manifests
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.719638   12426 kubelet.go:273] Watching apiserver
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.724671   12426 kuberuntime_manager.go:214] Container runtime containerd initialized, version: v1.4.3-k3s1, apiVersion: v1alpha2
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.725121   12426 server.go:1148] Started kubelet
jan 15 14:48:17 desktop k3s[12426]: E0115 14:48:17.736050   12426 cri_stats_provider.go:376] Failed to get the info of the filesystem with mountpoint "/var/lib/rancher/k3s/agent/containerd/io.containerd.snapsh>
jan 15 14:48:17 desktop k3s[12426]: E0115 14:48:17.736088   12426 kubelet.go:1218] Image garbage collection failed once. Stats initialization may not have completed yet: invalid capacity 0 on image filesystem
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.736514   12426 server.go:152] Starting to listen on 0.0.0.0:10250
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.737938   12426 server.go:424] Adding debug handlers to kubelet server.
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.739103   12426 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.742149   12426 volume_manager.go:265] Starting Kubelet Volume Manager
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.742662   12426 desired_state_of_world_populator.go:139] Desired state populator starts to run
jan 15 14:48:17 desktop k3s[12426]: E0115 14:48:17.765999   12426 controller.go:228] failed to get node "desktop" when trying to set owner ref to the node lease: nodes "desktop" not found
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.804864   12426 status_manager.go:158] Starting to sync pod status with apiserver
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.805189   12426 kubelet.go:1741] Starting kubelet main sync loop.
jan 15 14:48:17 desktop k3s[12426]: E0115 14:48:17.805448   12426 kubelet.go:1765] skipping pod synchronization - [container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet t>
jan 15 14:48:17 desktop k3s[12426]: E0115 14:48:17.845179   12426 kubelet.go:2183] node "desktop" not found
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.875811   12426 cpu_manager.go:184] [cpumanager] starting with none policy
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.875838   12426 cpu_manager.go:185] [cpumanager] reconciling every 10s
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.875865   12426 state_mem.go:36] [cpumanager] initializing new in-memory state store
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.876107   12426 state_mem.go:88] [cpumanager] updated default cpuset: ""
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.876124   12426 state_mem.go:96] [cpumanager] updated cpuset assignments: "map[]"
jan 15 14:48:17 desktop k3s[12426]: I0115 14:48:17.876141   12426 policy_none.go:43] [cpumanager] none policy: Start
jan 15 14:48:17 desktop k3s[12426]: F0115 14:48:17.876173   12426 kubelet.go:1296] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/lib/kubelet": could not find de>
jan 15 14:48:18 desktop k3s[12426]: goroutine 4567 [running]:
jan 15 14:48:18 desktop k3s[12426]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc00a559600, 0xe4, 0xfd)
jan 15 14:48:18 desktop k3s[12426]:         github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
jan 15 14:48:18 desktop k3s[12426]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x8ad78e0, 0xc000000003, 0x0, 0x0, 0xc003c742a0, 0x87b2f81, 0xa, 0x510, 0x0)
jan 15 14:48:18 desktop k3s[12426]:         github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:945 +0x191
jan 15 14:48:18 desktop k3s[12426]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x8ad78e0, 0xc000000003, 0x0, 0x0, 0x615f4f4, 0x23, 0xc00aa21cb0, 0x1, 0x1)
jan 15 14:48:18 desktop k3s[12426]:         github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
jan 15 14:48:18 desktop k3s[12426]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
jan 15 14:48:18 desktop k3s[12426]:         github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1456
jan 15 14:48:18 desktop k3s[12426]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules(0xc00b419500)
jan 15 14:48:18 desktop k3s[12426]:         github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1296 +0x385
jan 15 14:48:18 desktop k3s[12426]: sync.(*Once).doSlow(0xc00b419d38, 0xc004df1dd0)
jan 15 14:48:18 desktop k3s[12426]:         sync/once.go:66 +0xec
jan 15 14:48:18 desktop k3s[12426]: sync.(*Once).Do(...)
```

**To Reproduce**

1. `services.k3s.enable = true`

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

@euank

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.1-zen1, NixOS, 21.03.20210109.257cbbc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-21.03pre260232.733e537a8ad"`
 - channels(bbigras): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by bachp** [comment]
@bbigras Are you using btrfs as the backing filesystem? If yes I think https://github.com/kubernetes/kubernetes/issues/94335 could be the reason.

**Comment by bbigras** [comment]
@bachp Yes I'm using btrfs. Thanks.

**Comment by bbigras** [comment]
> I don't seem to have this problem anymore. I'm still using btrfs and I enabled k3s with the confg from https://nixos.wiki/wiki/K3s.
