### ISSUE TITLE
libvirtd failed to start on nixos-unstable-small

### ISSUE THREAD

**Issue by Ninlives** [NixOS/nixpkgs#109537]
**Describe the bug**
libvirtd on `b3616bd96400ce0252c241d76fcafb64389defc6` failed with:
```
Unable to connect to libvirt qemu:///system.

Verify that the 'libvirtd' daemon is running.

Libvirt URI is: qemu:///system

Traceback (most recent call last):
  File "/nix/store/y1vviyf32xwdzwy9abpvcl6vm326ldib-virt-manager-3.1.0/share/virt-manager/virtManager/connection.py", line 922, in _do_open
    self._backend.open(cb, data)
  File "/nix/store/y1vviyf32xwdzwy9abpvcl6vm326ldib-virt-manager-3.1.0/share/virt-manager/virtinst/connection.py", line 153, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/nix/store/j1gjgsnvnnwxc4fsfpgq1vi20fc349l8-python3.8-libvirt-6.8.0/lib/python3.8/site-packages/libvirt.py", line 148, in openAuth
    raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: Failed to connect socket to '/var/lib/run/libvirt/libvirt-sock': No such file or directory
```
Works fine on current nixos-unstable channel `b3616bd96400ce0252c241d76fcafb64389defc6`

**Comment by alesguzik** [comment]
@Ninlives is it solved? I'm on nixos-unstable and it's broken. The libvirtd daemon is running, but the socket path it creates is `/run/libvirt/libvirt-sock`, not `/var/lib/run/libvirt/libvirt-sock` that virsh and virt-manager try to use.

**Comment by alesguzik** [comment]
Ok, if anyone else had the same problem - seems like a restart or two solved it.
