### ISSUE TITLE
bundlerEnv/bundlerApp binstubs fail when invoked from a binstub with a different Gemfile

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#110974]
**Describe the bug**
`bundlerEnv` and `bundlerApp` write out binstubs for each binary they install. The binstubs set up various environment vars for Bundler, such as `BUNDLE_GEMFILE`.

Bundler has a lot more env vars than are touched in the binstub, but experimentally it seems that Bundler ignores those extra vars just fine.

Unfortunately, it also sets one var that isn't ignored, which is `RUBYOPT`. This is interpreted by Ruby directly, so Bundler doesn't even have a chance to touch it. And it also seems that Bundler sets this variable to the absolute path of the `bundler/setup` script, I'm really not sure why. I suppose it means nested ruby interpreters automatically get the same Gemfile. But in our case, it just confuses Bundler as it does initial setup with the wrong env vars.

One possible solution is to just change the binstub to include the `--disable-rubyopt` flag in the shebang. This will make it ignore `RUBYOPT`, though I don't know if the presence of the var will also cause Bundler to behave differently. I have not actually tested this solution. And of course it will prevent users from being able to pass options to Ruby, but maybe that's a good thing for these binstubs.

The other option is to replace the current binstub with a bash script instead of a ruby script, and have the bash script then clean up the environment before calling into Ruby. The bits that need to run inside Ruby could be passed as a `-e` flag. Our bash script can then do something like

```bash
if ${RUBYOPT+}; then
  read -r -d '' -a opts <<<"$RUBYOPT"
  for idx in "${!opts[@]}"; do
    [[ "${opts[$idx]}" = -r*bundler/setup ]] && unset opts[$idx]
  done
  RUBYOPT=${opts[*]}
fi
```

(I don't recommend searching for `-r${bundler}/${ruby.gemPath}/gems/bundler-${bundler.version}/lib/bundler/setup` specifically as if I install ruby bins from different generations of the nixpkgs channel they may have different bundler paths)

**To Reproduce**

1. Create a file called `Podfile` with the following contents:

   ```ruby
   system(*%w{nix run nixpkgs.fastlane -c fastlane lanes})
   exit!
   ```

2. Run `nix run nixpkgs.cocoapods -c pod install`

There's probably other gems I could use that have fewer dependencies, but this is what I know offhand.

**Expected behavior**
`fastlane` should execute properly (and in this case it should complain that it can't find a fastlane configuration).

**Actual behavior**
It prints the following:

```
Traceback (most recent call last):
	2: from /nix/store/hm6gdln16lz0sqmbpk1114v0b8chxrqx-fastlane-2.171.0-gems/bin/fastlane:20:in `<main>'
	1: from /nix/store/1cjlqqnv1h67lr7qy23b6i3x6bbxd7y9-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:413:in `block in replace_bin_path'
/nix/store/1cjlqqnv1h67lr7qy23b6i3x6bbxd7y9-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in replace_bin_path': can't find executable fastlane for gem fastlane. fastlane is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
```

**Notify maintainers**
I'm not sure who's a maintainer for this infrastructure right now, but based on git file history:
@manveru @alyssais @nyarly 

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.3.8`
 - channels(lilyball): `""`
 - channels(root): `"nixpkgs-21.03pre263062.980c4c3c2f6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- bundlerApp
- bundlerEnv
# a list of nixos modules affected by the problem
module:
```

**Comment by lilyball** [comment]
Bundler also sets `RUBYLIB`, and we should probably clean that too in case the binary I'm executing has a different version of bundler than the one that previously executed.

**Comment by lilyball** [comment]
Looks like this doesn't just require nested binstubs; a coworker just failed on invoking a single `bundlerApp` binary and right now it's looking like it's because he has `GEM_ROOT` / `GEM_HOME` / `GEM_PATH` set in his environment (I'm assuming this comes from `rvm`). Like with `RUBYOPT` I don't know if this is something we can clean from within a ruby script.

**Comment by lilyball** [comment]
My coworker says clearing `GEM_ROOT` bypasses the error, and clearing both `GEM_HOME` and `GEM_PATH` but leaving `GEM_ROOT` does not. So it sounds like we technically only need to clear `GEM_ROOT`, but should probably clear all 3 to be sure.
