### ISSUE TITLE
agda, nixos/tests/agda: LLVM error on aarch64-linux

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#111738]
**Describe the bug**

The test `nixos/tests/agda.nix` fails on `aarch64-linux` because it doesn't find LLVM:

```
Calling: /nix/store/jg9bfvlpmgwrmnzw2ny78lcz6gigqqqh-ghc-8.10.3-with-packages/bin/ghc -O -o /tmp/HelloWorld -Werror -i/tmp -main-is MAlonzo.Code.HelloWorld /tmp/MAlonzo/Code/HelloWorld.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
[  1 of 130] Compiling MAlonzo.RTE      ( MAlonzo/RTE.hs, MAlonzo/RTE.o )
Compilation error:

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM 9

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM 9
ghc: could not execute: opt
```

Note that Agda itself works fine, but the subsequent call to ghc doesn't succeed.

The correct resolution is probably to make sure that on `aarch64-linux`, the GHC called by Agda has an additional dependency on LLVM. (We could also make LLVM available on the test machine, but I think it's likely that Agda is actually broken on `aarch64-linux` in general, not just in the test.)

**Notify maintainers**

@alexarice @neosimsim

**Comment by turion** [comment]
Example failed run: https://hydra.nixos.org/build/136240205

**Comment by turion** [comment]
Side note: It would be nice to have a `6.topic: agda` label, but I don't know who can create one.

**Comment by turion** [comment]
I don't know how I reproduce this locally. I can do `nix-build nixos/tests/agda.nix --option system aarch64-linux --sandbox`, but then I get:

```
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
warning: ignoring the user-specified setting 'system', because it is a restricted setting and you are not a trusted user
[...]
error: a 'aarch64-linux' with features {} is required to build '/nix/store/w6wf7h1cqam1vy3jma072iz6lic072m0-hello-world.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
```

**Comment by turion** [comment]
When I add myself to trusted users and execute the same command (with or without `--sandbox`), I get:

```
building '/nix/store/qn5r3sdski7j47hzwa64bl2l8iqijns4-append-initrd-secrets.drv'...
while setting up the build environment: executing '/nix/store/83zszzf9h5zrgaasga0wwm4jnpby4i1z-bash-4.4-p23/bin/bash': Exec format error
while setting up the build environment: executing '/nix/store/83zszzf9h5zrgaasga0wwm4jnpby4i1z-bash-4.4-p23/bin/bash': Exec format error
builder for '/nix/store/qn5r3sdski7j47hzwa64bl2l8iqijns4-append-initrd-secrets.drv' failed with exit code 1
builder for '/nix/store/w6wf7h1cqam1vy3jma072iz6lic072m0-hello-world.drv' failed with exit code 1
cannot build derivation '/nix/store/nmf13vw5l5k62k9h6cfqmh7bmfhs0lfj-nixos-test-driver-agda.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/kr605yh3vrhjlzvz2bs6qm3fjqr4227b-vm-test-run-agda.drv': 1 dependencies couldn't be built
error: build of '/nix/store/kr605yh3vrhjlzvz2bs6qm3fjqr4227b-vm-test-run-agda.drv' failed
```

I think the misunderstanding here is that I don't need the build architecture to be `aarch64-linux`, only the VM architecture.

**Comment by alexarice** [comment]
I unfortunately have no idea about cross compiling

**Comment by turion** [comment]
With adisbladis' help I did the following:

* Add `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` to my host system
* `nix-build nixos/tests/agda.nix --option system aarch64-linux`

I then get:

```
$ nix-build nixos/tests/agda.nix --option system aarch64-linux --sandbox
these derivations will be built:
  /nix/store/2bfx002wcaizj49pc70nb63qr13klpwi-vm-test-run-agda.drv
building '/nix/store/2bfx002wcaizj49pc70nb63qr13klpwi-vm-test-run-agda.drv'...
starting VDE switch for network 1
running the VM test script
machine: must succeed: touch TestEmpty.agda
machine: waiting for the VM to finish booting
machine: starting vm
machine # Formatting '/build/vm-state-machine/machine.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=536870912 lazy_refcounts=off refcount_bits=16
machine # kvm version too old
machine # qemu-system-aarch64: failed to initialize kvm: Function not implemented
machine: QEMU running (pid 28)
machine: connected to guest root shell
machine: (connecting took 0.00 seconds)
(0.65 seconds)
error:
Traceback (most recent call last):
  File "/nix/store/avlkddzkp0q51w6rys4wkwcw5cc80b30-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 897, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 2, in <module>
  File "/nix/store/avlkddzkp0q51w6rys4wkwcw5cc80b30-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 419, in succeed
    (status, out) = self.execute(command)
  File "/nix/store/avlkddzkp0q51w6rys4wkwcw5cc80b30-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 400, in execute
    self.shell.send(out_command.encode())
BrokenPipeError: [Errno 32] Broken pipe
cleaning up
killing machine (pid 28)
(0.00 seconds)
builder for '/nix/store/2bfx002wcaizj49pc70nb63qr13klpwi-vm-test-run-agda.drv' failed with exit code 1
error: build of '/nix/store/2bfx002wcaizj49pc70nb63qr13klpwi-vm-test-run-agda.drv' failed
```

**Comment by turion** [comment]
I can't make any progress here if noone can teach us how to do cross-testing locally.

**Comment by neosimsim** [comment]
I have no idea either.

**Comment by sternenseemann** [comment]
Should be fixed on the `haskell-updates` branch.

**Comment by turion** [comment]
Ok, I'll assume this is fixed. Reopen if the problem occurs again.

**Comment by sternenseemann** [comment]
It's gonna be a bit until it hits `master` though, but yeah, I think this should be resolved for now.
