### ISSUE TITLE
package key-mon is broken

### ISSUE THREAD

**Issue by krgn** [NixOS/nixpkgs#11183]
How to reproduce:

Install `key-mon`:

```
nix-env -i key-mon
```

Start it:
```
➜  ~ key-mon

** (process:9370): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:9370): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:9370): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
Xlib.protocol.request.QueryExtension
Xlib.protocol.request.QueryExtension
/nix/store/vhsckmhsn4dipflb21jdy0yvv7sspwck-key-mon-1.17/lib/python2.7/site-packages/keymon/lazy_pixbuf_creator.py:109: GtkWarning: Cannot open pixbuf loader module file '/nix/store/9rhmfgpy8d0dj3hjgyj3j4sda18p5nz0-librsvg-2.40.9/lib/gdk-pixbuf/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /nix/store/9rhmfgpy8d0dj3hjgyj3j4sda18p5nz0-librsvg-2.40.9/lib/gdk-pixbuf/loaders.cache
to make things work again for the time being.
  return gtk.gdk.pixbuf_new_from_file(fname)
Traceback (most recent call last):
  File "/nix/store/vhsckmhsn4dipflb21jdy0yvv7sspwck-key-mon-1.17/bin/..key-mon-wrapped-wrapped", line 4, in <module>
    km.main()
  File "/nix/store/vhsckmhsn4dipflb21jdy0yvv7sspwck-key-mon-1.17/lib/python2.7/site-packages/keymon/key_mon.py", line 1032, in main
    keymon = KeyMon(opts)
  File "/nix/store/vhsckmhsn4dipflb21jdy0yvv7sspwck-key-mon-1.17/lib/python2.7/site-packages/keymon/key_mon.py", line 135, in __init__
    self.create_window()
  File "/nix/store/vhsckmhsn4dipflb21jdy0yvv7sspwck-key-mon-1.17/lib/python2.7/site-packages/keymon/key_mon.py", line 286, in create_window
    timeout=self.options.visible_click_timeout)
  File "/nix/store/vhsckmhsn4dipflb21jdy0yvv7sspwck-key-mon-1.17/lib/python2.7/site-packages/keymon/shaped_window.py", line 43, in __init__
    self.pixbuf = self.pixbufs.get('mouse')
  File "/nix/store/vhsckmhsn4dipflb21jdy0yvv7sspwck-key-mon-1.17/lib/python2.7/site-packages/keymon/lazy_pixbuf_creator.py", line 63, in get
    name = self.create_pixbuf(name)
  File "/nix/store/vhsckmhsn4dipflb21jdy0yvv7sspwck-key-mon-1.17/lib/python2.7/site-packages/keymon/lazy_pixbuf_creator.py", line 80, in create_pixbuf
    img = self._composite(img, self._read_from_file(operation))
  File "/nix/store/vhsckmhsn4dipflb21jdy0yvv7sspwck-key-mon-1.17/lib/python2.7/site-packages/keymon/lazy_pixbuf_creator.py", line 109, in _read_from_file
    return gtk.gdk.pixbuf_new_from_file(fname)
glib.GError: Couldn't recognize the image file format for file '/nix/store/vhsckmhsn4dipflb21jdy0yvv7sspwck-key-mon-1.17/lib/python2.7/site-packages/keymon/themes/classic/mouse-indicator.svg'
```

**Comment by nbp** [comment]
cc @domenkozar

**Comment by cillianderoiste** [comment]
Thanks @krgn, it should be fixed now.

**Comment by domenkozar** [comment]
@cillianderoiste would be nice to use 'makeWrapperArgs` instead

**Comment by cillianderoiste** [comment]
Ah thanks, I'll give that a shot.

**Comment by cillianderoiste** [comment]
@domenkozar like that?

**Comment by domenkozar** [comment]
Yeah if you define it in bash you could reference bash variavles as before. Grep around for export makeWrapperArgs

**Comment by cillianderoiste** [comment]
Hrm, I can't seem to find any examples of that. Things like `--set GDK_PIXBUF_MODULE_FILE "$GDK_PIXBUF_MODULE_FILE"` don't seem to work either.

**Comment by domenkozar** [comment]
Right, there is one example in my wheels branch. I'll fix it later when I'm
home

**Comment by cillianderoiste** [comment]
That's perfect, thanks. I can test it out, I'll test it with the wheels branch too.

**Comment by cillianderoiste** [comment]
Just to confirm, this works fine on the wheels branch too.
