### ISSUE TITLE
RFP: Video DownloadHelper Companion App (vdhcoapp)

### ISSUE THREAD

**Issue by milahu** [NixOS/nixpkgs#112046]
**Project description**

Video DownloadHelper is a "Browser extension to download videos from the Web"

> Some operations required by Video DownloadHelper cannot be performed from within the browser. In order to be able to still do the job, the add-on relies on an external application that is called transparently. We call it the Companion Application.

**Metadata**

* homepage URL: https://www.downloadhelper.net/install-coapp
* source URL: https://github.com/mi-g/vdhcoapp
* license: gpl2
* platforms: linux, darwin, (windows)

**other build scripts**

* [arch linux](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vdhcoapp)

**Comment by WolfangAukang** [comment]
FYI, I have been trying to figure this one out from source, but as `node2nix` isolates the build (which means it does not allow contacting any URL to download something), and one of the dependencies totally requires going to GitHub. I am still on it, and if it doesn't work, I hope the tar option works as a solution (really want to avoid the deb option).

**Comment by milahu** [comment]
i would recommend [npmlock2nix](https://github.com/nix-community/npmlock2nix) or [nix-npm-buildpackage](https://github.com/serokell/nix-npm-buildpackage) to build the node_modules from the package-lock.json lockfile.
in this case, package-lock.json is missing, and must be generated with `npm install`
(the lockfile should be added to the vdhcoapp repo ...)

> one of the dependencies totally requires going to GitHub

at least npmlock2nix allows to symlink extra files into node_modules

**Comment by WolfangAukang** [comment]
I have been also trying to do it with the tar and the deb files. The tar requires an extra install step (be it for system or user), and I get the following error:
```
pkg/prelude/bootstrap.js:1
leEnd(buf) {
           ^

SyntaxError: Unexpected token '{'
    at new Script (vm.js:89:7)
    at readPrelude (internal/bootstrap/pkg.js:29:13)
    at internal/bootstrap/pkg.js:36:18
    at internal/bootstrap/pkg.js:43:4
    at internal/bootstrap/pkg.js:44:2
```

For the deb, that does not require the extra steps, I can install it fine, but Firefox is not recognizing it.
![image](https://user-images.githubusercontent.com/8378365/136597461-6867f84b-5126-4b8a-bbe6-22f56c68feec.png)

**Comment by WolfangAukang** [comment]
Just in case, I've found this one [here](https://github.com/sigprof/nur-packages/blob/1df14af8abfe29a983e6832651547cc4112b4e39/pkgs/vdhcoapp/default.nix) which is way more advanced in building it. It even uses a patch to avoid using pkg (which was the issue I was having). Plus, it is kind of similar to the way it is built on the AUR.

I'd rather use this as a guide. I had already overwritten the `default.nix` I was using from source with the deb one.

**Comment by milahu** [comment]
> I've found this one [here](https://github.com/sigprof/nur-packages/blob/1df14af8abfe29a983e6832651547cc4112b4e39/pkgs/vdhcoapp/default.nix)

nice!

thing is, that one was made with npm2nix which generates [these huuuuge lockfiles](https://github.com/sigprof/nur-packages/blob/1df14af8abfe29a983e6832651547cc4112b4e39/pkgs/vdhcoapp/node-packages.nix),
which should be replaced with package-lock.json, stored in the upstream repo (vdhcoapp), to keep nixpkgs small

the 5KB patch can be compressed to
`sed -i -E s|(require)|if (process.execPath.endsWith("/node") process.execPath = process.argv[1];\n\1|' index.js`
not tested, but im feeling lucky ; )

**Comment by milahu** [comment]
[global install](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#linux) should work with
`/nix/store/*-vdhcoapp-*/lib/mozilla/native-messaging-hosts/net.downloadhelper.coapp.json`
and
`LD_LIBRARY_PATH+=:${vdhcoapp}/lib`
or
`MOZ_SYSTEM_DIR+=:${vdhcoapp}/lib`

but i always get

```
Companion App not installed
Checking companion app returned: No such native application net.downloadhelper.coapp
```

which is a known WONTFIX https://github.com/NixOS/nixpkgs/issues/47340#issuecomment-434052314

**Comment by haizaar** [comment]
Thank you @WolfangAukang for packaging this into NUR.

After installing from there I _still_ had to do 
```
path/to/net.downloadhelper.coapp install --user
```
Otherwise neither chromium nor FF couldn't find it even after reboot.

**Comment by WolfangAukang** [comment]
Sure thing @haizaar. I wish I could find a way to indicate that when installing, but for now that's the only way it works.

Now with 21.11, it should even work with Chrome (that specific browser was looking for a specific GLibC version packaged on 21.11).

**Comment by meditans** [comment]
@haizaar @WolfangAukang can the NUR package be used on pure nixos given that the manifest should live under `/lib`?
After installation and
```
path/to/net.downloadhelper.coapp install --user
```
I still can't trick firefox into recognizing the plugin

**Comment by WolfangAukang** [comment]
Yes, if Chromium is detecting the manifests after applying the user setup, then this might be something related to your Firefox setup.

I will still try your recommendation.

**Comment by haizaar** [comment]
I couldn't make it work on Firefox unfortunately (NixOS unstable with NUR package and post-install cmd)

**Comment by WolfangAukang** [comment]
Let's move the discussion to https://github.com/WolfangAukang/nur-packages/issues/9, as this is more related to the packaging issue. I will throw more details there.

**Comment by haizaar** [comment]
To wrap it up - silly me forgot that I need to rerun the post install command every time (browsers?) update. Now works both on Chromium and Firefox.

**Comment by WolfangAukang** [comment]
> To wrap it up - silly me forgot that I need to rerun the post install command every time (browsers?) update. Now works both on Chromium and Firefox.

@Shawn8901 posted a way for Firefox through Home-Manager to set the VDHCoApp manifests through the system installation. [Check here ](https://github.com/WolfangAukang/nur-packages/issues/9#issuecomment-1089072988).

With that, I'm seriously considering sending a PR to Nixpkgs, just need to check and format the code properly.

**Comment by WolfangAukang** [comment]
@Shawn8901 I have indeed, although it was more on re-running the process of creating the whole nix setup from scratch and use NodeJS 16. Now, my only concern (besides the code and many of my PR's not being reviewed) is that I don't want to keep maintaining more stuff on nixpkgs. If anyone wants to throw it, just go for it and I can help you, but personally I don't want to keep maintaining more packages because of lack of time.

**Comment by WolfangAukang** [comment]
FYI, a new major version will be released (2.0) and it is a refactor on the building process, which might make it easier to install compared to the way it currently works.

**Comment by haizaar** [comment]
I curious how's the work on packaging version 2.x is going? Is there still intention to merge it into nixpkgs?

**Comment by WolfangAukang** [comment]
@haizaar I have been trying it sporadically. The wall I'm facing is regarding the [bundling process](https://github.com/aclap-dev/vdhcoapp/blob/085338f4da9f93f332472b4dda84a35b7f6cc508/build.sh#L309). If I skip it, I don't see anything useful to add to the output, but if I try to bundle it, I get a `missing /lib` issue. I was able to figure out the rest though:

```
{ lib
, stdenvNoCC
, fetchFromGitHub
, buildNpmPackage
, fetchurl
, yq-go
, nodejs #Using nodejs-slim_18
, esbuild
, ejs
, vercel-pkg
}:

let
  pname = "vdhcoapp";
  version = "2.0.14";
  ffmpeg-version = "2.0.3";

  platforms = {
    x86_64-linux = "linux-x86_64";
  };
  platform = platforms.${stdenvNoCC.system};

  src = fetchFromGitHub {
    owner = "aclap-dev";
    repo = "vdhcoapp";
    rev = "v${version}";
    hash = "sha256-//GO7zGWJ3Epo4rGYc/+WJvUi9pd2tpCBQEkfvDYC00=";
  };

  app = buildNpmPackage {
    pname = "vdhcoapp-app";
    inherit version src;
    sourceRoot = "${src.name}/app";
    npmDepsHash = "sha256-E032U2XZdyTER6ROkBosOTn7bweDXHl8voC3BQEz8Wg=";
    dontNpmBuild = true;
    installPhase = ''
      cp -r . "$out"
    '';
  };

  ffmpeg-static-builder = fetchurl {
    url = "https://github.com/aclap-dev/ffmpeg-static-builder/releases/download/v${ffmpeg-version}/ffmpeg-${ffmpeg-version}-${platform}.tar.bz2";
    hash = "sha256-Gxr8oJKNfYH9jDinWidjjVOys4bxFJkXLXAGV6/i8XM=";
  };

in stdenvNoCC.mkDerivation (finalAttrs: {
  inherit pname version src;

  nativeBuildInputs = [
    yq-go
    nodejs
    esbuild
    ejs
    vercel-pkg
  ];

  patches = [
    ./debug.patch
  ];

  postPatch = ''
    rm -r app
    cp -r ${app} app
    chmod +w app

    patchShebangs ./build.sh

    mkdir dist
    tar xf ${ffmpeg-static-builder} -C dist
    mv dist/ffmpeg{,-${ffmpeg-version}}-${platform}
  '';

  buildPhase = ''
    ./build.sh --skip-bundling --skip-packaging --target ${platform}
  '';

  installPhase = ''
    ls dist/linux/x86_64 # Will only show ffmpeg stuff
    # ...
    exit 1
  '';
  
})
```

**Comment by HannesGitH** [comment]
Hi, i'm kind of a nixos rookie so sorry for asking, but:

i tried installing the coapp first via `nix-alien` but firefox did not recognize it (loads forever), so installed it via @WolfangAukang's NUR, but now the browser wants me to update the coapp (which is pinned to 1.6.3 here it seems)

so: how can i update this? 

( i tried cloning it but running `update.sh` fails as node2nix runs into `TypeError: Cannot read properties of undefined (reading 'dependencies')`)

**Comment by WolfangAukang** [comment]
@HannesGitH currently there is no way unless you can get 2.X packaged. As mentioned on the comment above, I'm struggling with the bundling process that uses `pkg` to get the new `vdhcoapp` binary.

**Comment by WolfangAukang** [comment]
> Edit: but in case i find time, will your current efforts be publicly available somewhere? (not just the default.nix, but a more complete repo e.g. also containing debug.patch)

Sure, you can find it [here](https://codeberg.org/wolfangaukang/nix-agordoj/src/branch/vdhcoapp-2.0.0/pkgs/vdhcoapp).

**Comment by WolfangAukang** [comment]
@liberodark [please watch the discussion](https://github.com/NixOS/nixpkgs/issues/112046#issuecomment-1913731808), there is a reason version 2.X still hasn't been added yet.

**Comment by WolfangAukang** [comment]
Good news everyone, someone figured a way to package it and it's working, so I just adapted it to work the nixpkgs way.

If you are interested in pushing it to nixpkgs (I really don't want to maintain it), you will need to pack [filepicker](https://codeberg.org/wolfangaukang/nix-agordoj/src/branch/main/pkgs/filepicker/default.nix) (could be internal to the same vdhcoapp package) and [this one](https://codeberg.org/wolfangaukang/nix-agordoj/src/branch/main/pkgs/vdhcoapp/default.nix).

**Comment by ToasterUwU** [comment]
Im not experienced enough and/or attached enough to NixOS yet to take that on, but i would really appreciate if someone makes it happen. If i get into NixOS more in the future, i would also be willing to take it over at some point if needed

**Comment by HannesGitH** [comment]
> Good news everyone, someone figured a way to package it and it's working, so I just adapted it to work the nixpkgs way.

well done! 

> Im not experienced enough and/or attached enough to NixOS yet to take that on, but i would really appreciate if someone makes it happen. If i get into NixOS more in the future, i would also be willing to take it over at some point if needed

Im not very experienced either, but i use nixos as my main system so at least im attached enough ;) i will try pushing it to nixpgs (as my first contribution) today

**Comment by JJJHolscher** [comment]
Thank you for your work.
I noticed I had to do a `vdhcoapp install` after a `nixos-rebuild switch` in order for the extension to detect the package.
It seems there might be [a way](https://github.com/NixOS/nixpkgs/pull/300051#issuecomment-2060047867) to have this be done automatically if you do it well in my NixOS config, which now looks like
```nix
programs.firefox.enable = true;
programs.firefox.policies.ExtensionSettings = { <stuff> };
environment.systemPackages = [ pkgs.vdhcoapp ];
```

But it was not clear to me what exactly needed to be done. Does anyone want to spell it out for me?
I'll add your answer to the [video-downloadhelper github disscussions](https://github.com/aclap-dev/video-downloadhelper/discussions) so others can more easily find it.

**Comment by Shawn8901** [comment]
I havent had yet any problems with having FF installed via home manager.

Here the according snippet is:

```nix
    programs. firefox.nativeMessagingHosts = [ pkgs.vdhcoapp ];
```
That will lead to having the required symlinks in `~/.mozilla` (where the manual install also places the files).
So in case you are using Home Manger, and there is no other option missing, could also consider switching your FF install to Home Manager.

**Comment by haizaar** [comment]
N. M

**Comment by JJJHolscher** [comment]
Thanks Toaster, it did not work for me. I'll keep doing it manually since it's really only required _once_.

**Comment by tempergate** [comment]
> Does it work only with Firefox or can it work with forks like Librewolf and Floorp?

it works, 
copy '~/.mozilla/native-messaging-hosts' to '~/.librewolf/native-messaging-hosts'
and  '~/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts' to '~/.var/app/.librewolf/native-messaging-hosts'
