### ISSUE TITLE
nixpkgs.emacs24Macport_24_3 build fails

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#11378]
Self-explanatory:

```
checking for gnutls >= 2.6.6... yes CFLAGS='-I/nix/store/0r9ryjv78ksdvlnq3b5psv7vij121ac0-gnutls-3.4.6/include ' LIBS='-L/nix/store/0r9ryjv78ksdvlnq3b5psv7vij121ac0-gnutls-3.4.6/lib -lgnutls '
checking for gnutls_certificate_set_verify_function... no
checking for xaw3d... no
checking for libXaw... configure: error: No X toolkit could be found.
If you are sure you want Emacs compiled without an X toolkit, pass
  --with-x-toolkit=no
to configure.  Otherwise, install the development libraries for the toolkit
that you want to use (e.g. Gtk+) and re-run configure.
builder for ‘/nix/store/p4n0fdxf8nk4yjnyq4adm1ad2n8fhbd8-emacs-24.3-mac-4.8.drv’ failed with exit code 1
error: build of ‘/nix/store/p4n0fdxf8nk4yjnyq4adm1ad2n8fhbd8-emacs-24.3-mac-4.8.drv’ failed
Traceback (most recent call last):
  File "/nix/store/6qfj65ymwsqhnm8qvarrs2zzdh0g4nhq-nox-0.0.2/bin/.nox-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/a91labs9457vv63fb30mbvq8nxbx4na2-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/a91labs9457vv63fb30mbvq8nxbx4na2-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/nix/store/a91labs9457vv63fb30mbvq8nxbx4na2-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/a91labs9457vv63fb30mbvq8nxbx4na2-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/6qfj65ymwsqhnm8qvarrs2zzdh0g4nhq-nox-0.0.2/lib/python3.4/site-packages/nox/search.py", line 83, in main
    subprocess.check_call(['nix-env', '-iA', '--show-trace'] + attributes)
  File "/nix/store/xzz8w7li1zw21glb7acifashvpyz7z8r-python3-3.4.3/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nix-env', '-iA', '--show-trace', 'nixpkgs.emacs24Macport_24_3']' returned non-zero exit status 100
```

**Comment by markWot** [comment]
So you use python... in your emacs on mac and it can not find X. Do you even have an X or some port on Mac?

**Comment by aragnon** [comment]
@markWot No, I am just running an installation in a shell, so the fact that it is Emacs is not really relevant.

**Comment by markWot** [comment]
Well I just enumerated the information I could extract from your log. You said it is self explanatory. I do not think so. What are you doing and why are you doing it?

**Comment by Profpatsch** [comment]
(triage) is this still a problem?

**Comment by matthewbauer** [comment]
We've fixed this since then.

**Comment by Profpatsch** [comment]
Nice, closing.
