### ISSUE TITLE
raspberrypi-eeprom requires vcgencmd in PATH

### ISSUE THREAD

**Issue by jonas-schievink** [NixOS/nixpkgs#113851]
**Describe the bug**
`rpi-eeprom-config` expects `vcgencmd` in `PATH`, but the containing package `raspberrypi-eeprom`, doesn't ensure this

**To Reproduce**
1. Install `raspberrypi-eeprom`
2. Run `rpi-eeprom-config`

**Expected behavior**
It should work.

**Screenshots**
```
Traceback (most recent call last):
  File "/run/current-system/sw/bin/rpi-eeprom-config", line 347, in <module>
    main()
  File "/run/current-system/sw/bin/rpi-eeprom-config", line 339, in main
    current_config = read_current_config()
  File "/run/current-system/sw/bin/rpi-eeprom-config", line 163, in read_current_config
    return shell_cmd(['vcgencmd', 'bootloader_config'])
  File "/run/current-system/sw/bin/rpi-eeprom-config", line 69, in shell_cmd
    result = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/nix/store/akrgx3370c6bl8akpd3j75hzqclicdl4-python3-3.8.7/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/akrgx3370c6bl8akpd3j75hzqclicdl4-python3-3.8.7/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vcgencmd'
```

**Notify maintainers**

cc @dasJ

**Metadata**

```
 - system: `"aarch64-linux"`
 - host os: `Linux 5.4.79, NixOS, 21.05pre270709.6b1057b452c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre270709.6b1057b452c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- raspberrypi-eeprom
# a list of nixos modules affected by the problem
module:
```

**Comment by jonas-schievink** [comment]
For now, a simple workaround is to also install `libraspberrypi`, which contains the `vcgencmd` program

**Comment by IvanMalison** [comment]
Not stale. This is still an issue.

**Comment by Artturin** [comment]
#135104
