### ISSUE TITLE
freecad doesn't build: FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#114029]
**Describe the bug**

```
-- Build files have been written to: /build/source/build
cmake: enabled parallel building
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "/nix/store/qyv5ffskmq8fv9yf5mb6fr5yracavid4-python3-3.8.7/lib/python3.8/tokenize.py", line 392, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
error: --- Error --- nix-daemon
builder for '/nix/store/chqprbhksn9fj60g8kpgbpvyi59sz7j0-python3.8-pivy-0.6.5.drv' failed with exit code 1; last 10 log lines:
  -- Build files have been written to: /build/source/build
  cmake: enabled parallel building
  building
  Executing setuptoolsBuildPhase
  Traceback (most recent call last):
    File "nix_run_setup", line 8, in <module>
      exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
    File "/nix/store/qyv5ffskmq8fv9yf5mb6fr5yracavid4-python3-3.8.7/lib/python3.8/tokenize.py", line 392, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix-build
1 dependencies of derivation '/nix/store/dh92r05bpsj49fk2kwrwq49kiy5ry1d2-freecad-unstable-2020-12-08.drv' failed to build
```

**To Reproduce**
1. cd ~/nixpkgs
2. nix-build -A freecad

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

@viric @gebner

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.10-zen1, NixOS, 21.05.20210219.9816b99 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-21.03pre267696.fab6fcdceb2"`
 - channels(bbigras): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by bbigras** [comment]
Thanks!

**Comment by ziguana** [comment]
This is still happening for me on unstable, same error.
