### ISSUE TITLE
Mastodon: tootctl domains purge - needed environment

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#114252]
**Describe the bug**
Error running command `tootctl domains purge DOMAIN`:
```
sudo su - mastodon -s /bin/sh -c "tootctl domains purge DOMAIN"
ERROR: Missing RAILS_ENV environment variable, please set it to "production", "development", or "test".
```

With `RAILS_ENV=production tootctl domains purge DOMAIN`:
```
sudo su - mastodon -s /bin/sh -c "RAILS_ENV=production tootctl domains purge DOMAIN --verbose --dry-run"
Traceback (most recent call last):
        66: from /etc/profiles/per-user/mastodon/bin/tootctl:5:in `<main>'
        65: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
        64: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
        63: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
        62: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
        61: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        60: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        59: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        58: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        57: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        56: from /nix/store/j050qzpmhhgc7m48izsq3wsxd0vsclzl-mastodon-3.3.0/lib/cli.rb:4:in `<top (required)>'
        55: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
        54: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
        53: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
        52: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
        51: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        50: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        49: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        48: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        47: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        46: from /nix/store/j050qzpmhhgc7m48izsq3wsxd0vsclzl-mastodon-3.3.0/lib/mastodon/media_cli.rb:4:in `<top (required)>'
        45: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
        44: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
        43: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
        42: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
        41: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        40: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        39: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        38: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        37: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        36: from /nix/store/j050qzpmhhgc7m48izsq3wsxd0vsclzl-mastodon-3.3.0/config/environment.rb:5:in `<top (required)>'
        35: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
        34: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
        33: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        32: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        31: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        30: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
        29: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
        28: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        27: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
        26: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `call'
        25: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `tsort_each_child'
        24: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `each'
        23: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        22: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        21: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        20: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        19: from /nix/store/kpiyw5hydcllwlaj61nn25p0g90l9b66-ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        18: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
        17: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
        16: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
        15: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:607:in `block in <class:Engine>'
        14: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:607:in `each'
        13: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:608:in `block (2 levels) in <class:Engine>'
        12: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
        11: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
        10: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
         9: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
         8: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
         7: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         6: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
         5: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
         4: from /nix/store/j050qzpmhhgc7m48izsq3wsxd0vsclzl-mastodon-3.3.0/config/environments/production.rb:1:in `<top (required)>'
         3: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:216:in `configure'
         2: from /nix/store/474r73da0zyva3l14n7dx6cpw887nkp5-mastodon-gems-3.3.0/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:216:in `instance_eval'
         1: from /nix/store/j050qzpmhhgc7m48izsq3wsxd0vsclzl-mastodon-3.3.0/config/environments/production.rb:114:in `block in <top (required)>'
/nix/store/j050qzpmhhgc7m48izsq3wsxd0vsclzl-mastodon-3.3.0/config/environments/production.rb:114:in `fetch': key not found: "OTP_SECRET" (KeyError)
```

cc @erictapen

**Comment by Izorkin** [comment]
Sorry, required running with `mastodon-env` - `mastodon-env tootctl domains purge DOMAIN`.
