### ISSUE TITLE
python3Packages.pytorch-metric-learning: tests fail on master

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#114740]
```

tests/utils/test_distributed.py FFF                                      [ 92%]
tests/utils/test_logit_getter.py .                                       [ 93%]
tests/utils/test_loss_and_miner_utils.py .....                           [ 98%]
tests/utils/test_loss_tracker.py .                                       [ 99%]
tests/utils/test_module_with_records_and_reducer.py .                    [100%]

=================================== FAILURES ===================================
____ TestDistributedLossWrapper.test_distributed_classifier_loss_and_miner _____

self = <tests.utils.test_distributed.TestDistributedLossWrapper testMethod=test_distributed_classifier_loss_and_miner>

    def test_distributed_classifier_loss_and_miner(self):
>       self.loss_and_miner_tester(
            losses.ArcFaceLoss, miners.MultiSimilarityMiner, False
        )

tests/utils/test_distributed.py:281:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils/test_distributed.py:252: in loss_and_miner_tester
    mp.spawn(
/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py:199: in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py:157: in start_processes
    while not context.join():
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <torch.multiprocessing.spawn.ProcessContext object at 0x7fffa05bf490>
timeout = None

    def join(self, timeout=None):
        r"""
        Tries to join one or more processes in this spawn context.
        If one of them exited with a non-zero exit status, this function
        kills the remaining processes and raises an exception with the cause
        of the first process exiting.

        Returns ``True`` if all processes have been joined successfully,
        ``False`` if there are more processes that need to be joined.

        Arguments:
            timeout (float): Wait this long before giving up on waiting.
        """
        # Ensure this function can be called even when we're done.
        if len(self.sentinels) == 0:
            return True

        # Wait for any process to fail or all of them to succeed.
        ready = multiprocessing.connection.wait(
            self.sentinels.keys(),
            timeout=timeout,
        )

        error_index = None
        for sentinel in ready:
            index = self.sentinels.pop(sentinel)
            process = self.processes[index]
            process.join()
            if process.exitcode != 0:
                error_index = index
                break

        # Return if there was no error.
        if error_index is None:
            # Return whether or not all processes have been joined.
            return len(self.sentinels) == 0

        # Assume failure. Terminate processes that are still alive.
        for process in self.processes:
            if process.is_alive():
                process.terminate()
            process.join()

        # There won't be an error on the queue if the process crashed.
        if self.error_queues[error_index].empty():
            exitcode = self.processes[error_index].exitcode
            if exitcode < 0:
                name = signal.Signals(-exitcode).name
                raise Exception(
                    "process %d terminated with signal %s" %
                    (error_index, name)
                )
            else:
                raise Exception(
                    "process %d terminated with exit code %d" %
                    (error_index, exitcode)
                )

        original_trace = self.error_queues[error_index].get()
        msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
        msg += original_trace
>       raise Exception(msg)
E       Exception: 
E       
E       -- Process 0 terminated with the following error:
E       Traceback (most recent call last):
E         File "/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
E           fn(i, *args)
E         File "/build/source/tests/utils/test_distributed.py", line 145, in single_process_function
E           assert parameters_are_equal(original_model, ddp_mp_model.module)
E       AssertionError

/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py:118: Exception
----------------------------- Captured stdout call -----------------------------
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
_______ TestDistributedLossWrapper.test_distributed_tuple_loss_and_miner _______

self = <tests.utils.test_distributed.TestDistributedLossWrapper testMethod=test_distributed_tuple_loss_and_miner>

    def test_distributed_tuple_loss_and_miner(self):
>       self.loss_and_miner_tester(
            losses.ContrastiveLoss, miners.MultiSimilarityMiner, True
        )

tests/utils/test_distributed.py:276:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils/test_distributed.py:252: in loss_and_miner_tester
    mp.spawn(
/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py:199: in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py:157: in start_processes
    while not context.join():
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <torch.multiprocessing.spawn.ProcessContext object at 0x7fffa0621fa0>
timeout = None

    def join(self, timeout=None):
        r"""
        Tries to join one or more processes in this spawn context.
        If one of them exited with a non-zero exit status, this function
        kills the remaining processes and raises an exception with the cause
        of the first process exiting.

        Returns ``True`` if all processes have been joined successfully,
        ``False`` if there are more processes that need to be joined.

        Arguments:
            timeout (float): Wait this long before giving up on waiting.
        """
        # Ensure this function can be called even when we're done.
        if len(self.sentinels) == 0:
            return True

        # Wait for any process to fail or all of them to succeed.
        ready = multiprocessing.connection.wait(
            self.sentinels.keys(),
            timeout=timeout,
        )

        error_index = None
        for sentinel in ready:
            index = self.sentinels.pop(sentinel)
            process = self.processes[index]
            process.join()
            if process.exitcode != 0:
                error_index = index
                break

        # Return if there was no error.
        if error_index is None:
            # Return whether or not all processes have been joined.
            return len(self.sentinels) == 0

        # Assume failure. Terminate processes that are still alive.
        for process in self.processes:
            if process.is_alive():
                process.terminate()
            process.join()

        # There won't be an error on the queue if the process crashed.
        if self.error_queues[error_index].empty():
            exitcode = self.processes[error_index].exitcode
            if exitcode < 0:
                name = signal.Signals(-exitcode).name
                raise Exception(
                    "process %d terminated with signal %s" %
                    (error_index, name)
                )
            else:
                raise Exception(
                    "process %d terminated with exit code %d" %
                    (error_index, exitcode)
                )

        original_trace = self.error_queues[error_index].get()
        msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
        msg += original_trace
>       raise Exception(msg)
E       Exception: 
E       
E       -- Process 0 terminated with the following error:
E       Traceback (most recent call last):
E         File "/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
E           fn(i, *args)
E         File "/build/source/tests/utils/test_distributed.py", line 145, in single_process_function
E           assert parameters_are_equal(original_model, ddp_mp_model.module)
E       AssertionError

/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py:118: Exception
----------------------------- Captured stdout call -----------------------------
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
_____ TestDistributedLossWrapper.test_distributed_tuple_miner_with_ref_emb _____

self = <tests.utils.test_distributed.TestDistributedLossWrapper testMethod=test_distributed_tuple_miner_with_ref_emb>

    def test_distributed_tuple_miner_with_ref_emb(self):
>       self.loss_and_miner_tester(
            losses.ContrastiveLoss, miners.MultiSimilarityMiner, True, test_ref_emb=True
        )

tests/utils/test_distributed.py:286:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils/test_distributed.py:252: in loss_and_miner_tester
    mp.spawn(
/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py:199: in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py:157: in start_processes
    while not context.join():
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <torch.multiprocessing.spawn.ProcessContext object at 0x7fffa05f4eb0>
timeout = None

    def join(self, timeout=None):
        r"""
        Tries to join one or more processes in this spawn context.
        If one of them exited with a non-zero exit status, this function
        kills the remaining processes and raises an exception with the cause
        of the first process exiting.

        Returns ``True`` if all processes have been joined successfully,
        ``False`` if there are more processes that need to be joined.

        Arguments:
            timeout (float): Wait this long before giving up on waiting.
        """
        # Ensure this function can be called even when we're done.
        if len(self.sentinels) == 0:
            return True

        # Wait for any process to fail or all of them to succeed.
        ready = multiprocessing.connection.wait(
            self.sentinels.keys(),
            timeout=timeout,
        )

        error_index = None
        for sentinel in ready:
            index = self.sentinels.pop(sentinel)
            process = self.processes[index]
            process.join()
            if process.exitcode != 0:
                error_index = index
                break

        # Return if there was no error.
        if error_index is None:
            # Return whether or not all processes have been joined.
            return len(self.sentinels) == 0

        # Assume failure. Terminate processes that are still alive.
        for process in self.processes:
            if process.is_alive():
                process.terminate()
            process.join()

        # There won't be an error on the queue if the process crashed.
        if self.error_queues[error_index].empty():
            exitcode = self.processes[error_index].exitcode
            if exitcode < 0:
                name = signal.Signals(-exitcode).name
                raise Exception(
                    "process %d terminated with signal %s" %
                    (error_index, name)
                )
            else:
                raise Exception(
                    "process %d terminated with exit code %d" %
                    (error_index, exitcode)
                )

        original_trace = self.error_queues[error_index].get()
        msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
        msg += original_trace
>       raise Exception(msg)
E       Exception: 
E       
E       -- Process 0 terminated with the following error:
E       Traceback (most recent call last):
E         File "/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
E           fn(i, *args)
E         File "/build/source/tests/utils/test_distributed.py", line 145, in single_process_function
E           assert parameters_are_equal(original_model, ddp_mp_model.module)
E       AssertionError

/nix/store/svzyz956fl1yxcy5piw07m890ginflvx-python3.8-pytorch-1.7.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py:118: Exception
----------------------------- Captured stdout call -----------------------------
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
testing pytorch_metric_learning version 0.9.95 with pytorch version 1.7.1
=========================== short test summary info ============================
FAILED tests/utils/test_distributed.py::TestDistributedLossWrapper::test_distributed_classifier_loss_and_miner
FAILED tests/utils/test_distributed.py::TestDistributedLossWrapper::test_distributed_tuple_loss_and_miner
FAILED tests/utils/test_distributed.py::TestDistributedLossWrapper::test_distributed_tuple_miner_with_ref_emb
=========== 3 failed, 100 passed, 5 deselected in 200.90s (0:03:20) ============
builder for '/nix/store/pdj2gs0qj9xsra0cgas64kn4xm1gnzvz-python3.8-pytorch-metric-learning-0.9.95.drv' failed with exit code 1
error: build of '/nix/store/pdj2gs0qj9xsra0cgas64kn4xm1gnzvz-python3.8-pytorch-metric-learning-0.9.95.drv' failed
```

**Notify maintainers**

@bcdarwin

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.pytorch-metric-learning python37Packages.pytorch-metric-learning
# a list of nixos modules affected by the problem
module:
```

**Comment by sternenseemann** [comment]
New failure:

```
============================= test session starts ==============================
platform linux -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /build/source
collected 123 items / 1 error / 8 deselected / 114 selected                    

==================================== ERRORS ====================================
________________ ERROR collecting tests/utils/test_inference.py ________________
ImportError while importing test module '/build/source/tests/utils/test_inference.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/utils/test_inference.py:4: in <module>
    import faiss
E   ModuleNotFoundError: No module named 'faiss'
=============================== warnings summary ===============================
src/pytorch_metric_learning/utils/common_functions.py:394
src/pytorch_metric_learning/utils/common_functions.py:394
  /build/source/src/pytorch_metric_learning/utils/common_functions.py:394: DeprecationWarning: invalid escape sequence \.
    regex_wrapper("best[0-9]+\.pth$") if best else regex_wrapper("[0-9]+\.pth$")

src/pytorch_metric_learning/utils/common_functions.py:396
  /build/source/src/pytorch_metric_learning/utils/common_functions.py:396: DeprecationWarning: invalid escape sequence \.
    epoch_regex = regex_wrapper("[0-9]+\.pth$")

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
ERROR tests/utils/test_inference.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
================== 8 deselected, 3 warnings, 1 error in 2.14s ==================
```

**Comment by mweinelt** [comment]
Fixed in 99c0fb9059be2986eb443ae8700f5d4b9d23f53f and cfb653e47f57a0b64674258ceca93c19dd6153c1
