### ISSUE TITLE
$shell conflicts with $SHELL under certain conditions: rename $shell in stdenv

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#114873]
**Describe the bug**

There are situations where $shell (from stdenv) conflicts with $SHELL (from a regular environment). I bumped into this in an environment created with nix-shell: https://github.com/armijnhemel/binaryanalysis-ng/issues/68
where python's configparser module lowercases all environment variables and then barfs. It might be better to rename $shell to something else like $nixshell

**To Reproduce**

1. start a nix-shell
2. create a python script (python3):
```
import os
import configparser
blah = configparser.ConfigParser(os.environ)
```
3. run the script, for example as follows:
```
$ python3 /tmp/test.py 
Traceback (most recent call last):
  File "/tmp/test.py", line 3, in <module>
    blah = configparser.ConfigParser(os.environ)
  File "/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/lib/python3.8/configparser.py", line 639, in __init__
    self._read_defaults(defaults)
  File "/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/lib/python3.8/configparser.py", line 1219, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/lib/python3.8/configparser.py", line 752, in read_dict
    raise DuplicateOptionError(section, key, source)
configparser.DuplicateOptionError: While reading from '<dict>': option 'shell' in section 'DEFAULT' already exists
```

**Expected behavior**

No crash should have happened.

**Additional context**

This is a bug that caught me by surprise. I would have expected that it would "just work'. Of course there is something to say for that Python's configparser module is wrong here, but there also doesn't seem to be a really good reason to have both $shell and $SHELL.

**Comment by armijnhemel** [comment]
@edolstra my guess is that this could potentially be an intrusive change

**Comment by armijnhemel** [comment]
Leaving a workaround for people bumping into the same issue: clean up the environment first before feeding it to ConfigParser avoids the issue.

**Comment by armijnhemel** [comment]
As far as I know this is still an issue.
