### ISSUE TITLE
beets-check plugin's tests are broken

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#114994]
**Describe the bug**

```

running install tests
/nix/store/4kpxs30zfpq2650jnlgcyb5i98nmmh33-beets-unstable-2021-01-29/lib/python3.8/site-packages/beets/mediafile.py:21: UserWarning: beets.mediafile is deprecated; use mediafile instead
  warnings.warn("beets.mediafile is deprecated; use mediafile instead")
............................EE............
======================================================================
ERROR: test_convert_command (test.integration_test.ConvertTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test/integration_test.py", line 185, in test_convert_command
    beets.ui._raw_main(['convert', 'ok.ogg'])
  File "/nix/store/4kpxs30zfpq2650jnlgcyb5i98nmmh33-beets-unstable-2021-01-29/lib/python3.8/site-packages/beets/ui/__init__.py", line 1264, in _raw_main
    subcommand, suboptions, subargs = parser.parse_subcommand(subargs)
  File "/nix/store/4kpxs30zfpq2650jnlgcyb5i98nmmh33-beets-unstable-2021-01-29/lib/python3.8/site-packages/beets/ui/__init__.py", line 1094, in parse_subcommand
    raise UserError(u"unknown command '{0}'".format(cmdname))
beets.ui.UserError: unknown command 'convert'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: no user configuration found at /build/tmpvcmt5spe/config.yaml
beets: DEBUG: data directory: /build/tmpvcmt5spe
beets: DEBUG: plugin paths:
beets: DEBUG: Sending event: pluginload
beets: DEBUG: library database: /build/tmpvcmt5spe/library.db
library directory: /build/tmpvcmt5spe/libdir
beets: DEBUG: Sending event: library_opened
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_update_after_keep_new_convert (test.integration_test.ConvertTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test/integration_test.py", line 192, in test_update_after_keep_new_convert
    beets.ui._raw_main(['convert', '--keep-new', 'ok.ogg'])
  File "/nix/store/4kpxs30zfpq2650jnlgcyb5i98nmmh33-beets-unstable-2021-01-29/lib/python3.8/site-packages/beets/ui/__init__.py", line 1264, in _raw_main
    subcommand, suboptions, subargs = parser.parse_subcommand(subargs)
  File "/nix/store/4kpxs30zfpq2650jnlgcyb5i98nmmh33-beets-unstable-2021-01-29/lib/python3.8/site-packages/beets/ui/__init__.py", line 1094, in parse_subcommand
    raise UserError(u"unknown command '{0}'".format(cmdname))
beets.ui.UserError: unknown command 'convert'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: no user configuration found at /build/tmp8xd7b829/config.yaml
beets: DEBUG: data directory: /build/tmp8xd7b829
beets: DEBUG: plugin paths:
beets: DEBUG: Sending event: pluginload
beets: DEBUG: library database: /build/tmp8xd7b829/library.db
library directory: /build/tmp8xd7b829/libdir
beets: DEBUG: Sending event: library_opened
--------------------- >> end captured logging << ---------------------

Name                 Stmts   Miss  Cover
----------------------------------------
beetsplug/check.py     316     19    94%
----------------------------------------------------------------------
Ran 42 tests in 8.415s

FAILED (errors=2)
builder for '/nix/store/1wjywzypgl7y0fg7b1aq0z93j028rym6-beets-check.drv' failed with exit code 1
error: build of '/nix/store/1wjywzypgl7y0fg7b1aq0z93j028rym6-beets-check.drv' failed
```

**Notify maintainers**

@lovesegfault

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: beets
# a list of nixos modules affected by the problem
module:
```

**Comment by sternenseemann** [comment]
Removed in a2492b0831915aa9a24cdc4ff96b1288241898c7.
