### ISSUE TITLE
nix traefik test is flaky

### ISSUE THREAD

**Issue by maxeaubrey** [NixOS/nixpkgs#115418]
**Describe the bug**
The traefik nix test is flaky, as pointed out in https://github.com/NixOS/nixpkgs/pull/113878#issuecomment-782817274. 

**To Reproduce**
Run `nix-build nixpkgs/nixos/tests/traefik.nix` several times. In personal experience about 1 in 3 test runs fail.

**Expected behavior**
The test always succeeds.

**Screenshots**
Relevant excerpts from the referenced PR:
Failing test:
```
[nix-shell:~/.cache/nixpkgs-review/pr-113878-1]$ nix-build nixpkgs/nixos/tests/traefik.nix
...
traefik # [   16.605144] dhcpcd[726]: veth3aa29b9: soliciting a DHCP lease
Check that a container can be reached via Traefik
client: must succeed: curl -sSf -H Host:nginx.traefik.test http://traefik/
client # curl: (22) The requested URL returned error: 404 Not Found
client: output:
Test "Check that a container can be reached via Traefik" failed with error: "command `curl -sSf -H Host:nginx.traefik.test http://traefik/` failed (exit code 22)"
error:
Traceback (most recent call last):
  File "/nix/store/c0zxi1j4ch5c0v446k4m31crx4npkb82-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 897, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 13, in <module>
  File "/nix/store/c0zxi1j4ch5c0v446k4m31crx4npkb82-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 422, in succeed
    raise Exception(
Exception: command `curl -sSf -H Host:nginx.traefik.test http://traefik/` failed (exit code 22)
```

Succeeding test:
```
Check that a container can be reached via Traefik
client: must succeed: curl -sSf -H Host:nginx.traefik.test http://traefik/
traefik # [   16.630064] 9d3fb07985a7[529]: 172.17.0.1 - - [21/Feb/2021:07:53:40 +0000] "GET / HTTP/1.1" 200 52 "-" "curl/7.74.0
```

Test succeeding by waiting for the success:
```
client: waiting for success: curl -sSf -H Host:nginx.traefik.test http://traefik
client # curl: (22) The requested URL returned error: 404 Not Found
traefik # [   26.299894] c564e47bdead[619]: 172.17.0.1 - - [07/Mar/2021:15:25:13 +0000] "GET / HTTP/1.1" 200 52 "-" "curl/7.74.0"
(1.54 seconds)
Check that a container can be reached via Traefik
client: must succeed: curl -sSf -H Host:nginx.traefik.test http://traefik/
traefik # [   26.342905] c564e47bdead[619]: 172.17.0.1 - - [07/Mar/2021:15:25:13 +0000] "GET / HTTP/1.1" 200 52 "-" "curl/7.74.0"
```

**Additional context**
It seems to be purely a timing issue, see further notes https://github.com/NixOS/nixpkgs/pull/113878#issuecomment-792690659.

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.1, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixpkgs-maxine, home-manager"`
 - channels(maxine): `"home-manager"`
 - nixpkgs: `/var/run/current-system/systems/nixpkgs`
 ```

Maintainer information:
```yaml
attribute: traefik
# a list of nixos modules affected by the problem
module:
```

**Comment by Mindavi** [comment]
I've seen this on traefik too -- it takes some time from serving 404s to being fully operational. Maybe there's some service endpoints that could be used instead? (Just spewing some ideas)
