### ISSUE TITLE
pympress|python-gi missing GLIBC

### ISSUE THREAD

**Issue by kennyballou** [NixOS/nixpkgs#115576]
**Describe the bug**

After installing `pympress` though `nix-env` and attempting to execute `pympress slides.pdf`, the following stack trace is returned:

```
Traceback (most recent call last):
  File "/nix/store/b9624h1jpr90k40cv3mw9b89i35jnaj2-pympress-1.5.1/bin/..pympress-wrapped-wrapped", line 6, in <module>
    from pympress.__main__ import main
  File "/nix/store/b9624h1jpr90k40cv3mw9b89i35jnaj2-pympress-1.5.1/lib/python3.8/site-packages/pympress/__main__.py", line 66, in <module>
    import gi
  File "/nix/store/463l6zzw36is0jdpasyb5m570c2iyg3z-python-environment/lib/python3.8/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib/libc.so.6: version `GLIBC_2.32' not found (required by /nix/store/5i172qh374nls3canh28ydniqkgliv11-glib-2.66.4/lib/libglib-2.0.so.0)
```

This likely indicates a missing dependency or package build issue?

**To Reproduce**
1. `nix-env -i pympress`
2. `pympress`

**Expected behavior**
No stack trace, trying out the application for a presentation, not sure what to expect otherwise.

**Additional context**

Using latest nixpkgs unstable, NixOS/nixpkgs@a2b0ea6865b2346ceb015259c76e111dcca039c5.

Uninstalling and then building and installing shows a different error that appears more of an upstream issue(?):

```bash
nix-env --uninstall pympress
nix build nixpkgs.pympress
nix-env -iA nixpkgs.pympress
pympress
```

```
<... lots of GTK warnings ... >
ged' is invalid for instance '0xde85f0' of type 'GInotifyFileMonitor'
  self.add_from_file(util.get_ui_resource_file(resource_name))
Traceback (most recent call last):
  File "/nix/store/4j5j6m9i8g1j02ijxmdn69lmw7r3gvwi-pympress-1.5.1/bin/..pympress-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/4j5j6m9i8g1j02ijxmdn69lmw7r3gvwi-pympress-1.5.1/lib/python3.8/site-packages/pympress/__main__.py", line 167, in main
    gui = ui.UI()
  File "/nix/store/4j5j6m9i8g1j02ijxmdn69lmw7r3gvwi-pympress-1.5.1/lib/python3.8/site-packages/pympress/ui.py", line 209, in __init__
    self.make_cwin()
  File "/nix/store/4j5j6m9i8g1j02ijxmdn69lmw7r3gvwi-pympress-1.5.1/lib/python3.8/site-packages/pympress/ui.py", line 252, in make_cwin
    self.c_frame.set_property("yalign", self.config.getfloat('content', 'yalign'))
TypeError: object of type `GtkAspectFrame' does not have property `yalign'
```

**Notify maintainers**

CC: @tbenst 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.18, NixOS, 20.09.3341.df8e3bd1109 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3398.f26c6ddc472"`
 - channels(kb): `"nixpkgs-21.05pre273941.a2b0ea6865b"`
 - nixpkgs: `/home/kb/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by tbenst** [comment]
Hm, this looks like a problem with libglib requiring a glibc version that isn't available..?

**Comment by kennyballou** [comment]
I have upgraded to NixOS/nixpkgs@b49e47309d0df845ce3eb6c01ffe720952ed3695, no dice.  I'm not sure how else to address the underlying libglib issue.

Full disclosure, I discovered `pdfpc` which serves the purpose `pympress` would serve.  I may have less vested interested, but making things work is important, so I can still help fix this if there is something I can do to help resolve it.

**Comment by tbenst** [comment]
Glad you found an alternative! pdfpc looks neat. I’m happy to offer pointers if anyone wants to investigate, but don’t have bandwidth to fix

**Comment by smancill** [comment]
I upgraded pympress to latest release with #132248, and I saw no issue opening a pdf.

**Comment by kennyballou** [comment]
I'm receiving a different error with version `1.6.3`:

```

ERROR: Gobject Introspections and/or pycairo module is missing, make sure Gtk, pygobject and pycairo are installed on your system.

Try your operating system’s package manager, or try running: pip install pygobject pycairo
pip will then download and compile pygobject and pycairo, for which you need the Gtk and cairo headers (or development packages).

For instructions, refer to https://github.com/Cimbali/pympress/blob/master/README.md#dependencies
If using a virtualenv or anaconda, you can also try allowing system site packages.

```

The same result was given after installing the updating `pympress` (`nix-channel --update && nix-env --upgrade`) and after trying `nix-shell -p pympress` (`nix-shell --pure -p pympress` caused even more issues, but that's likely inability to connect to X).

I'm fine closing this out if it's working for others; I'm no stranger to my setup being the cause of issues than the package itself.

**Comment by smancill** [comment]
Cannot reproduce, and this is the nixpkgs-unstable cached build:

```
$ nix-env -iA unstable.pympress
installing 'pympress-1.6.3'
...
copying path '/nix/store/xb12807ap8h0510lkp67szz2alk9bshh-pympress-1.6.3' from 'https://cache.nixos.org'...
...

$ pympress --version
Pympress: 1.6.3 ; Python: 3.9.6 ; OS: Linux 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 ; Gtk 3.24.30 ; GLib 2.68.3 ; Poppler 21.06.1 cairo ; Cairo 1.16.0 , pycairo 1.20.1
```

<img width="989" alt="Captura de Pantalla 2021-08-23 a la(s) 00 17 06" src="https://user-images.githubusercontent.com/238528/130389531-d282d79b-4080-49ff-8047-dc261f9f6235.png">


But this is nixpkgs running on lnl7/nix Docker image, not NixOS.

**Comment by kennyballou** [comment]
@smancill: seeing as I can't even run `--version` without getting the above error and you're not running NixOS, do you happen to have `pyobject` or `(py)?cairo` installed through pip or brew?

**Comment by smancill** [comment]
> @smancill: seeing as I can't even run `--version` without getting the above error and you're not running NixOS, do you happen to have `pyobject` or `(py)?cairo` installed through pip or brew?

No, I tried in an empty container with nothing else installed.

Maybe you can try a different package that uses pycairo. I see pick-colour-picker or hamster.

**Comment by kennyballou** [comment]
> Maybe you can try a different package that uses pycairo. I see pick-colour-picker or hamster.

Both of those confirm it's not local to `pympress`.

```
% nix-shell -p pick-colour-picker
{{nix output elided}}

[nix-shell:~]$ pick-colour-picker
Traceback (most recent call last):
  File "/nix/store/qn1qvcybm33yk3prd55dbvw4qxciga2z-python3.9-pick-colour-picker-unstable-2021-01-19/bin/..pick-colour-picker-wrapped-wrapped", line 6, in <module>
    from pick.__main__ import main
  File "/nix/store/qn1qvcybm33yk3prd55dbvw4qxciga2z-python3.9-pick-colour-picker-unstable-2021-01-19/lib/python3.9/site-packages/pick/__main__.py", line 9, in <module>
    import cairo, math, json, os, codecs, time, subprocess, sys, base64, colorsys
  File "/nix/store/sm286smqrx81yg3plhr2ajgdd05pjhi2-python-environment/lib/python3.8/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ModuleNotFoundError: No module named 'cairo._cairo'

[nix-shell:~]$ exit
% nix-shell -p hamster
{{nix output elided}}

[nix-shell:~]$ hamster
Traceback (most recent call last):
  File "/nix/store/1k42nmpbv4d9cysjhy6q6fjpzciwq7c0-hamster-3.0.2/bin/.hamster-wrapped", line 44, in <module>
    from hamster.edit_activity import CustomFactController
  File "/nix/store/1k42nmpbv4d9cysjhy6q6fjpzciwq7c0-hamster-3.0.2/lib/python3.9/site-packages/hamster/edit_activity.py", line 29, in <module>
    from hamster import widgets
  File "/nix/store/1k42nmpbv4d9cysjhy6q6fjpzciwq7c0-hamster-3.0.2/lib/python3.9/site-packages/hamster/widgets/__init__.py", line 26, in <module>
    from hamster.widgets.activityentry import (
  File "/nix/store/1k42nmpbv4d9cysjhy6q6fjpzciwq7c0-hamster-3.0.2/lib/python3.9/site-packages/hamster/widgets/activityentry.py", line 24, in <module>
    import cairo
  File "/nix/store/sm286smqrx81yg3plhr2ajgdd05pjhi2-python-environment/lib/python3.8/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ModuleNotFoundError: No module named 'cairo._cairo'
```

Interesting.  Neither elided output contains a derivation for `pycairo` or `cairo`.

I may need to study this some more.  Seeing the `python-environment` line tells me this has something to do with my, likely crazy, overlay setup.

**Comment by tbenst** [comment]
@kennyballou recommend you use / think of pympress as a standalone application. Best to use vanilla pythonPackages w/o overlays as input
