### ISSUE TITLE
jekyll doesn't seem to work

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#11564]
My channel is pointing at `nixos-16.03pre73106.b1dca6c`.

```
$ nix-shell -p jekyll

[nix-shell:~]$ jekyll
/nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/execjs-2.5.2/lib/execjs/runtimes.rb:48:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/execjs-2.5.2/lib/execjs.rb:5:in `<module:ExecJS>'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/execjs-2.5.2/lib/execjs.rb:4:in `<top (required)>'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `require'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `require'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `<top (required)>'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `require'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `<top (required)>'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:46:in `require'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:46:in `block in gracefully_require'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in `each'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in `gracefully_require'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/jekyll-2.5.3/lib/jekyll.rb:166:in `<top (required)>'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/jekyll-2.5.3/bin/jekyll:6:in `require'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/lib/ruby/gems/2.1.6/gems/jekyll-2.5.3/bin/jekyll:6:in `<top (required)>'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/bin/jekyll:21:in `load'
	from /nix/store/ymbp77pi88prxd1q43i9r3cmd3fcf0xi-jekyll-2.5.3/bin/jekyll:21:in `<main>'
```

cc @pesterhazy

**Comment by jgillich** [comment]
Works for me, but I also have `nodejs` installed.

**Comment by copumpkin** [comment]
Ah, so that implicit dependency should probably be added to the package, right?

**Comment by jgillich** [comment]
I'd guess so, but `v8` is probably the better choice here because it is a lot lighter.

**Comment by zimbatm** [comment]
execjs is just a dispatcher to one of the compatible JavaScript engines but you need at least one. The nodejs-one is really the most stable in my experience.

**Comment by copumpkin** [comment]
Makes sense, but it still seems like the dispatcher chosen should be represented in the expression and not via environment at runtime, right? I can make the change if interested parties agree on that.

**Comment by jgillich** [comment]
v8 is what node uses anyhow, but node also comes with npm and a lot of other stuff. And yes, we all want packages to work after installing them, therefore the expression should depend on a javascript engine.

**Comment by zimbatm** [comment]
@copumpkin agreed, it shouldn't depend on the user's environment

@jgillich do you mean v8 as a standalone executable or the ruby bindings (aka therubyracer) ? I didn't know the former was an option. The latter is not really good in my experience, having two GC in the same process and referencing each-other's objects tend to not go very well.

**Comment by jgillich** [comment]
[v8 standalone is also listed](https://github.com/rails/execjs), so I guess it supports both?

**Comment by jgillich** [comment]
This is also fixed by #12226, since Jekyll v3 no longer depends on ExecJS.

**Comment by copumpkin** [comment]
:beers:

**Comment by jgillich** [comment]
This can be closed I think.

**Comment by copumpkin** [comment]
yup, thanks!
