### ISSUE TITLE
pyopencl is not working. undefined symbol: clSetProgramSpecializationConstant

### ISSUE THREAD

**Issue by rowanG077** [NixOS/nixpkgs#116266]
**Describe the bug**
When trying to use `pyopencl` the import within python fails with an undefined symbol error. 

**To Reproduce**
1. import `pyopencl`: `nix-shell -p python38 python38Packages.pyopencl --run 'python -c "import pyopencl"'`
2. See error:
```
λ nix-shell -p python38 python38Packages.pyopencl --run 'python -c "import pyopencl"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/smwbd0v5m2nj4dfq24hv7117a4hh5al7-python3.8-pyopencl-2020.3.1/lib/python3.8/site-packages/pyopencl/__init__.py", line 29, in <module>
    import pyopencl.cltypes  # noqa: F401
  File "/nix/store/smwbd0v5m2nj4dfq24hv7117a4hh5al7-python3.8-pyopencl-2020.3.1/lib/python3.8/site-packages/pyopencl/cltypes.py", line 22, in <module>
    from pyopencl.tools import get_or_register_dtype
  File "/nix/store/smwbd0v5m2nj4dfq24hv7117a4hh5al7-python3.8-pyopencl-2020.3.1/lib/python3.8/site-packages/pyopencl/tools.py", line 37, in <module>
    from pyopencl._cl import bitlog2  # noqa: F401
ImportError: /nix/store/smwbd0v5m2nj4dfq24hv7117a4hh5al7-python3.8-pyopencl-2020.3.1/lib/python3.8/site-packages/pyopencl/_cl.cpython-38-x86_64-linux-gnu.so: undefined symbol: clSetProgramSpecializationConstant
```

**Expected behavior**
I expect `pyopencl` to work.

**Notify maintainers**
@FRidh 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
λ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.8, NixOS, 21.03pre263901.68398d2dd50 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(rowan.goemans): `""`
 - channels(root): `"nixos-21.05pre271938.c7d0dbe094c, nixos-hardware, stable-20.09.3246.d4189f68fdb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by b12f** [comment]
Have you managed to find a workaround for this?

**Comment by rowanG077** [comment]
@b12f No, unfortunately not. The use case for me what to use Futhark. But that has the option to use C ffi bindings so I did that.

**Comment by athas** [comment]
This is sort of fixed now, as it fails at load-time with a complaint that Python 3.8 is not supported.
