### ISSUE TITLE
OctoPrint: Restoring from backup not working

### ISSUE THREAD

**Issue by Stunkymonkey** [NixOS/nixpkgs#116473]
**Describe the bug**
when uploading an old backup to restore it, the permissions prevent from restoring the backup

```
Uploading backup, this can take a while. Please wait...
Found config folder backup from prior restore, deleting it...
Restoring from backup... 
Unpacking backup to /tmp/tmpz4y797i0...
UnpackedRenaming /var/lib/octoprint to /var/lib/octoprint.bck...
Removing temporary unpacked folder
Error while running restoreTraceback (most recent call last):  File "/nix/store/00gw6mj6585zmki0a0mnx08yvldq5kmg-python3-3.8.8/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)PermissionError: [Errno 13] Permission denied: '/var/lib/octoprint' -> '/var/lib/octoprint.bck/octoprint'
During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/nix/store/rrvbjrqcbm9yxsy72wmfkf4f9i31pvlb-python3.8-OctoPrint-1.4.2/lib/python3.8/site-packages/octoprint/plugins/backup/__init__.py", line 907, in _restore_backup
    shutil.move(basedir, basedir_backup)  File "/nix/store/00gw6mj6585zmki0a0mnx08yvldq5kmg-python3-3.8.8/lib/python3.8/shutil.py", line 803, in move
    rmtree(src)  File "/nix/store/00gw6mj6585zmki0a0mnx08yvldq5kmg-python3-3.8.8/lib/python3.8/shutil.py", line 722, in rmtree
    onerror(os.rmdir, path, sys.exc_info())  File "/nix/store/00gw6mj6585zmki0a0mnx08yvldq5kmg-python3-3.8.8/lib/python3.8/shutil.py", line 720, in rmtree
    os.rmdir(path)
PermissionError: [Errno 13] Permission denied: '/var/lib/octoprint' 
Restore failed! Check the above output and octoprint.log for reasons as to why.
Removing temporary zip
```

**To Reproduce**
1. upload backup-file via webinterface
2. wait for error

**Expected behavior**
No Error and everything is restored.

**Additional context**
i know how to restore this by hand, so this is not a major problem for me.

**Notify maintainers**

@abbradar @gebner @WhittlesJr 

**Metadata**
 - system: `"aarch64-linux"`
 - host os: `Linux 4.19.118, NixOS, 20.09.git.2821518e360M (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3456.bba2f2bdc4d, nixos-unstable-21.05pre275232.29b0d4d0b60"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: octoprint
```

**Comment by gador** [comment]
I got the same error. The user `octoprint` isn't allowed to create a new folder under `/var/lib`.

I don't have a nix way arround this error, but resolved to manually restore the octoprint backup to `/var/lib/octoprint` and fixed the hardcoded paths in config.yaml.

**Comment by 7FM** [comment]
I guess the nix way might be something like this: https://github.com/7FM/nixpkgs/commit/8b1473feee463caacb0f61cc12f02afdd169cb89
However, now the restore procedure fails one step later when it tries to restart the octoprint service via `sudo service octoprint restart`. Octoprint itself also has an option `serverRestartCommand` to change this restart command. Yet, I do not know if there exists a nice way to restart octoprint in an unprivileged manner. Maybe someone with more knowledge about systemd stuff can help here.

**Comment by gador** [comment]
@7FM why do you create a `state` dir inside the `base` dir?
This way, it will create the `state` dir in `/var/lib/octoprint/octoprint` 

If at all, this is an octoprint issue, since it tries to move the octoprint folder to a new temporary directory, where it doesn't (and IMO shouldn't) have access.

**Comment by 7FM** [comment]
> why do you create a `state` dir inside the `base` dir?

Primarily to ensure that octoprint has the required permissions in the parent folder of its `state` dir. Hence, during recovery octprint can move its `state` folder `/var/lib/octoprint/octoprint` to `/var/lib/octoprint/octoprint.bck` and create a new empty `state` folder.

> This way, it will create the `state` dir in `/var/lib/octoprint/octoprint`

Exactly. I have to admit that this is more a hack than a solution.

> If at all, this is an octoprint issue, since it tries to move the octoprint folder to a new temporary directory, where it doesn't (and IMO shouldn't) have access.

I guess octoprint somewhat assumes that it is installed & run by a normal user (with sudo access) and residing in `~/.octoprint`. Therefore, it also has access to the whole `~` directory and not just its `state` directory.

**Comment by 7FM** [comment]
regarding the restarting issue: one might be able to employ something like this https://superuser.com/questions/1171751/restart-systemd-service-automatically-whenever-a-directory-changes-any-file-ins by setting `serverRestartCommand` to something like `touch /var/lib/octoprint/restart`. I will give it a try and report back :)

**Comment by 7FM** [comment]
> regarding the restarting issue: one might be able to employ something like this https://superuser.com/questions/1171751/restart-systemd-service-automatically-whenever-a-directory-changes-any-file-ins by setting `serverRestartCommand` to something like `touch /var/lib/octoprint/restart`. I will give it a try and report back :)

It works! :D (c.f. https://github.com/7FM/nixpkgs/commit/6f6346ee8506055cc12288680365d1fb21b70b0f)

**Comment by Stunkymonkey** [comment]
I think this can be fixed with:
```
      systemd.tmpfiles.rules = [
        "d '${cfg.stateDir}' - ${cfg.user} ${cfg.group} - -"
      ];
```
Since I am no longer using octoprint i did not test it.

**Comment by marmolak** [comment]
Hi. I fixed this issue with workarond:
```
  services.octoprint = {
    ...
    # FIX: allow restore from backup.
    # Octoprint want's to rename octoprint directory to octoprint.bck in /var/lib but without luck.
    stateDir = "/var/lib/octoprint-root/octoprint";
  };

  # Part of FIX for octoprint (more in services.octoprint.
  systemd.tmpfiles.rules = [
    "d /var/lib/octoprint-root/ 0770 octoprint octoprint -"
    "d /var/lib/octoprint-root/octoprint 0770 octoprint octoprint -"
  ];
```

I'm not sure if this is right way how to do it, but it works for me.

**Comment by Stunkymonkey** [comment]
> ```
>   services.octoprint = {
>     ...
>     # FIX: allow restore from backup.
>     # Octoprint want's to rename octoprint directory to octoprint.bck in /var/lib but without luck.
>     stateDir = "/var/lib/octoprint-root/octoprint";
>   };
> 
>   # Part of FIX for octoprint (more in services.octoprint.
>   systemd.tmpfiles.rules = [
>     "d /var/lib/octoprint-root/ 0770 octoprint octoprint -"
>     "d /var/lib/octoprint-root/octoprint 0770 octoprint octoprint -"
>   ];
> ```

the directions seems right, but I am not sure about the `stateDir` value. Are you sure this is needed?

**Comment by Stunkymonkey** [comment]
just out of my head (untested): https://github.com/Stunkymonkey/nixpkgs/commit/f5a4eda7844a713ac787e1a90ac1a0d3665f9b82
