### ISSUE TITLE
virt-manager display not working

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#11643]
Tried virt-manager with a local libvirt daemon and one on the network, couldn't get VNC/SPICE working on both.

![screenshot from 2015-12-12 07-55-07](https://cloud.githubusercontent.com/assets/347965/11760723/315a92f4-a0a6-11e5-840d-835223fe26e7.png)
I don't have a `~/.virt-manager/virt-manager.log`, no idea if there is any other way to get logs.

**Comment by jgillich** [comment]
@devhell Since you've touched virt-manager recently, I guess you don't get this? :)

**Comment by devhell** [comment]
Hmmm, just tried it as you mentioned it, and I can't get a new virtual machine set up. The error is as follows: 
```
Unable to complete install: 'internal error: process exited while connecting to monitor: ((null):22923): Spice-Warning **: reds.c:2454:reds_init_socket: reds_init_socket: binding socket to 127.0.0.1:5900 failed
2015-12-12T17:23:34.094143Z qemu-system-x86_64: failed to initialize spice server
'

Traceback (most recent call last):
  File "/nix/store/qfy2b7sr89z3bic9bnjna6wk9g19sqmd-virt-manager-1.2.1/share/virt-manager/virtManager/asyncjob.py", line 89, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/nix/store/qfy2b7sr89z3bic9bnjna6wk9g19sqmd-virt-manager-1.2.1/share/virt-manager/virtManager/create.py", line 1873, in do_install
    guest.start_install(meter=meter)
  File "/nix/store/qfy2b7sr89z3bic9bnjna6wk9g19sqmd-virt-manager-1.2.1/share/virt-manager/virtinst/guest.py", line 414, in start_install
    noboot)
  File "/nix/store/qfy2b7sr89z3bic9bnjna6wk9g19sqmd-virt-manager-1.2.1/share/virt-manager/virtinst/guest.py", line 478, in _create_guest
    dom = self.conn.createLinux(start_xml or final_xml, 0)
  File "/nix/store/2b8p1br4iz7l2g3cys4iv1dbxakvvxl4-libvirt-python-1.2.19/lib/python2.7/site-packages/libvirt.py", line 3598, in createLinux
    if ret is None:raise libvirtError('virDomainCreateLinux() failed', conn=self)
libvirtError: internal error: process exited while connecting to monitor: ((null):22923): Spice-Warning **: reds.c:2454:reds_init_socket: reds_init_socket: binding socket to 127.0.0.1:5900 failed
2015-12-12T17:23:34.094143Z qemu-system-x86_64: failed to initialize spice server
```

**Comment by devhell** [comment]
I should also mention that `mpd` and `syncthing` are currently unable to bind to ipv4.

**Comment by jgillich** [comment]
Wow whats happening there..do you even have a loopback interface?

Running virt-manager with --debug gives me this:

```
  File "/nix/store/lb5k52aq5yqa1157idrdag8kvzfg2mps-virt-manager-1.2.1/share/virt-manager/virtManager/autodrawer.py", line 286, in do_size_allocate
    self.set_allocation(tmpalloc)
TypeError: argument allocation: Expected Gdk.Rectangle, but got gi.repository.cairo.RectangleInt
```
Trying to upgrade it to the latest version, maybe that helps.

**Comment by devhell** [comment]
Hmm, not getting that.

**Comment by jgillich** [comment]
This is [a bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800798) in pygobject and the version we have is really old. It got updated a few days ago, but it apparently hasn't arrived in unstable yet.

**Comment by jgillich** [comment]
![screenshot from 2015-12-12 20-33-07](https://cloud.githubusercontent.com/assets/347965/11763541/9914b1a4-a10f-11e5-9a54-34abe215c6ee.png)
