### ISSUE TITLE
Can't run gradle in Darwin derivations: Failed to load native library 'libnative-platform.dylib' for Mac OS X x86_64.

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#116529]
**Describe the bug**

When you try to execute gradle in a derivation this happens:

```
FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Could not initialize native services.
   > Failed to load native library 'libnative-platform.dylib' for Mac OS X x86_64.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

<details>
<summary>Useless stacktrace</summary>

```
* Exception is:
org.gradle.initialization.exception.InitializationException: Gradle could not start your build.
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:49)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
        at org.gradle.launcher.Main.doAction(Main.java:35)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
Caused by: org.gradle.internal.service.ServiceCreationException: Could not initialize native services.
        at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:133)
        at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:84)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:42)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
        ... 11 more
Caused by: net.rubygrapefruit.platform.NativeException: Failed to load native library 'libnative-platform.dylib' for Mac OS X x86_64.
        at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:67)
        at net.rubygrapefruit.platform.Native.init(Native.java:56)
        at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:99)
        ... 15 more
Caused by: java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at net.rubygrapefruit.platform.internal.NativeLibraryLocator.find(NativeLibraryLocator.java:45)
        at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:45)
        ... 17 more
```

</details>

**To Reproduce**

Minimal reproducer by @roberth, formatted and adjusted by yours truly:

```Nix
with import <nixpkgs> {};

stdenv.mkDerivation {
  src = /var/empty;

  name = "foo";

  buildInputs = [ gradle ];

  buildPhase = "gradle --stacktrace";
}
```

**Expected behavior**

**Screenshots**

**Additional context**

https://stackoverflow.com/questions/48652914/nix-gradle-dist-failed-to-load-native-library-libnative-platform-so-for-linu  
(It works on Linux now for some reason)

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Atemu** [comment]
Setting `GRADLE_USER_HOME=".gradle"` makes it work; seems like gradle just tries to access some location it shouldn't.
