### ISSUE TITLE
After an upgrade from nixos-20.09 to nixos-unstable, `nixos-rebuild` segfaults

### ISSUE THREAD

**Issue by anna328p** [NixOS/nixpkgs#117835]
**Describe the bug**
After an upgrade from nixos-20.09 to nixos-unstable, `nixos-rebuild` segfaults.

**To Reproduce**
1. Set up a system using the nixos-20.09 channel
2. Update the channel to nixos-unstable
3. Attempt to `nixos-rebuild switch`

**Expected behavior**
Rebuild succeeds

**Screenshots**

**Additional context**

Here's my configuration: https://paste.rs/CeE.nix

Using gdb on the generated coredump, I narrowed down the problem to `bash`:

```
Core was generated by `/nix/store/w65ydq10abi813fi7d5j7afdcrxj3aqq-bash-4.4-p23/bin/bash /nix/store/03'.                                      
Program terminated with signal SIGSEGV, Segmentation fault.            
#0  0x00006ea235c1a9ec in call_init () from /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/ld-linux-x86-64.so.2                
warning: File "/nix/store/c10296m7xgm3ksibcklb2xf48jr635x3-gcc-9.3.0-lib/lib/libstdc++.so.6.0.28-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/nix/store/fmxgxr7kx29aqbzjp662v5mhkrbjvl91-gcc-10.2.0-lib".
(gdb) bt                                                               
#0  0x00006ea235c1a9ec in call_init () from /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/ld-linux-x86-64.so.2                
#1  0x00006ea235c1ab3d in _dl_init () from /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/ld-linux-x86-64.so.2                 
#2  0x00006ea235c0c08a in _dl_start_user () from /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/ld-linux-x86-64.so.2           
#3  0x0000000000000003 in ?? ()                                        
#4  0x0000716f6a0193c9 in ?? ()                                        
#5  0x0000716f6a01940b in ?? ()                                        
#6  0x0000716f6a019457 in ?? ()                                        
#7  0x0000000000000000 in ?? ()                                        
```

I ran `ldd` on that bash:

```
[anna@talos:~/qbot]$ ldd /nix/store/w65ydq10abi813fi7d5j7afdcrxj3aqq-bash-4.4-p23/bin/bash                                                    
        linux-vdso.so.1 (0x000064cb1dd0d000)                           
        /nix/store/plbfwlai3l6jy94gm0bf89c7ir8ca7nv-malloc-provider-scudo/lib/libclang_rt.scudo-x86_64.so (0x000064cb1d433000)                
        libdl.so.2 => /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libdl.so.2 (0x000064cb1d42e000)                           
        libc.so.6 => /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libc.so.6 (0x000064cb1d26d000)                             
        libgcc_s.so.1 => /nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib/libgcc_s.so.1 (0x000064cb1d253000)                     
        /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/ld-linux-x86-64.so.2 => /nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib64/ld-linux-x86-64.so.2 (0x000064cb1dd0e000)                                                                                     
        librt.so.1 => /nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib/librt.so.1 (0x000064cb1d249000)                           
        libpthread.so.0 => /nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib/libpthread.so.0 (0x000064cb1d226000)                 
        libstdc++.so.6 => /nix/store/c10296m7xgm3ksibcklb2xf48jr635x3-gcc-9.3.0-lib/lib/libstdc++.so.6 (0x000064cb1d045000)                   
        libm.so.6 => /nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib/libm.so.6 (0x000064cb1cf04000)                             
```

The important line here is:
```
        /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/ld-linux-x86-64.so.2 => /nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib64/ld-linux-x86-64.so.2 (0x000064cb1dd0e000)                                                                                     
```

Seems like it's being loaded with an older glibc than what it's linked with.

I tried overriding it:

```
[anna@talos:~/qbot]$ sudo env LD_LIBRARY_PATH=/nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib nixos-rebuild switch
/nix/store/9ywr69qi622lrmx5nn88gk8jpmihy0dz-bash-4.4-p23/bin/bash: symbol lookup error: /nix/store/90illc73xfs933d06daq6d41njs8yh66-glibc-2.32-37/lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE
```

Here's a verbose rebuild log: http://ix.io/2Uio

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Segmentation fault (core dumped)

running just `nix-info -m` gives this:
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.100-hardened1, NixOS, 20.09.3613.34f85de51bb (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre278406.d3f7e969b98"`
 - channels(anna): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by anna328p** [comment]
Managed to get some basic system functionality to work by committing some terrible store manipulation...

![Screenshot of my terminal](https://i.imgur.com/b8kCkZ2.png)

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/issues/100799#issuecomment-728935064
Also you should consider changing your password since you publicly shared the hash.

**Comment by anna328p** [comment]
@TredwellGit I don't know why I even have a password here...

I'll try disabling the hardened profile and rebuilding.

**Comment by anna328p** [comment]
Seems like it was caused by the hardened profile. After removing, rebuld seems to work.
