### ISSUE TITLE
ihaskell install doesn't work 

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#11810]
```
# ihaskell install
ihaskell:
Ran commands:
which jupyter
which jupyter
/usr/local/bin/jupyter --version
which /usr/local/bin/jupyter
withTmpDir
rm -f /tmp/tmpThreadId41804289383846930886
mkdir /tmp/tmpThreadId41804289383846930886
mkdir -p /tmp/tmpThreadId41804289383846930886/haskell
writefile /tmp/tmpThreadId41804289383846930886/haskell/kernel.json
cp /nix/store/hylyyj5jgcpgsbqgy05m1xlpalgm3jfz-ihaskell-0.8.2.0/share/x86_64-linux-ghc-7.10.2/ihaskell-0.8.2.0/html/kernel.js /tmp/tmpThreadId41804289383846930886/haskell/kernel.js
cp /nix/store/hylyyj5jgcpgsbqgy05m1xlpalgm3jfz-ihaskell-0.8.2.0/share/x86_64-linux-ghc-7.10.2/ihaskell-0.8.2.0/html/logo-64x64.png /tmp/tmpThreadId41804289383846930886/haskell/logo-64x64.png
which ipython
/usr/local/bin/ipython kernelspec install --user /tmp/tmpThreadId41804289383846930886/haskell --replace
which /usr/local/bin/ipython
rm -rf /tmp/tmpThreadId41804289383846930886

Exception: error running: /usr/local/bin/ipython kernelspec install --user /tmp/tmpThreadId41804289383846930886/haskell --replace
exit status: 1
stderr: Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/zmq/__init__.py", line 49, in <module>
    from zmq import backend
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/nix/store/kswx3i4af2sf96n0565rx3wkhjb9fziy-python-2.7.10-env/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/lib/librt.so.1: symbol __shm_directory, version GLIBC_PRIVATE not defined in file libpthread.so.0 with link time reference
```

**Comment by peti** [comment]
The very first lines refer to `/usr/local/bin/jupyter`, which is hardly a package installed by Nix. Apparently, you're trying to mix Nix packages with ones from the host system, and that cannot be expected to work.

**Comment by aragnon** [comment]
ihaskell install only needs to store a file in some directory. 

I would expect to be able to just use the nix haskell kernel with a non-Nix Jupyter.

**Comment by FRidh** [comment]
It might be a non-Nix jupyter installation, but it is using a Nix-version of Python.
What is exactly what you are trying to achieve, since in #11261 you were also trying something with Jupyter and other kernels.

**Comment by aragnon** [comment]
A multi-language Jupyterhub, which I already achieved, but I wanted to add Haskell too and I prefer to have as many dependencies managed by Nix.

**Comment by FRidh** [comment]
@peti pointed out the issue so I'm closing this now. If you have a specific question, feel free to open an issue.
