### ISSUE TITLE
solaar: TypeError: Argument 1 does not allow None as a value

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#118622]
**Describe the bug**

Solaar crashes with the following error:

```
Traceback (most recent call last):
  File "/nix/store/48hgb7x5q46xi0vgyach2p8cqirr7c3n-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/__init__.py", line 143, in <lambda>
    application.connect('startup', lambda app, startup_hook:_startup(app,startup_hook,use_tray,show_window), startup_hook)
  File "/nix/store/48hgb7x5q46xi0vgyach2p8cqirr7c3n-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/__init__.py", line 101, in _startup
    window.init(show_window, use_tray)
  File "/nix/store/48hgb7x5q46xi0vgyach2p8cqirr7c3n-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/window.py", line 744, in init
    Gtk.Window.set_default_icon_from_file(_icons.icon_file(NAME.lower()))
TypeError: Argument 0 does not allow None as a value
Traceback (most recent call last):
  File "/nix/store/48hgb7x5q46xi0vgyach2p8cqirr7c3n-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/__init__.py", line 112, in _activate
    app.add_window(window._window)
TypeError: Argument 1 does not allow None as a value
```

**Notify maintainers**

@spinus @ysndr

**Comment by spinus** [comment]
@suhr thanks for report, I can reproduce it. I'll try to find some time to investigate, it looks like it cannot find an icon?

**Comment by spinus** [comment]
@suhr can you elaborate how you run this?
I was able to reproduce the issue with `nix-shell --pure`, but when I install in the system with `nix-env -iA` it works. It's something with xdg and icons discovery and I wasn't able to fix this, probably some specific XDG variable or desktop environment variable must be set to properly discover icons.

**Comment by suhr** [comment]
Yes, it seems like it was indeed the problem with icons. Installing KDE fixes the issue even without using it.

**Comment by legendofmiracles** [comment]
The wiki has a small section on this: https://nixos.wiki/wiki/Development_environment_with_nix-shell#Icons_not_working


But on a side note @spinus. The package is out of date 😄

**Comment by spinus** [comment]
@legendofmiracles thanks. Locally I updated to latest version and it didn't change much. 
If I have a sec I'll try debug little more.

**Comment by aszenz** [comment]
Same error, here's the output i get when running `solaar --window=show`

```
(.solaar-wrapped:56467): Gtk-WARNING **: 12:56:34.032: Could not find the icon 'solaar-init-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

(.solaar-wrapped:56467): Gtk-WARNING **: 12:56:34.041: Found an icon but could not load it. Most likely gdk-pixbuf does not provide SVG support.
Traceback (most recent call last):
  File "/nix/store/mwjwlr3bdqcbggxmqqgnp7x25sqqznjm-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/__init__.py", line 143, in <lambda>
    application.connect('startup', lambda app, startup_hook:_startup(app,startup_hook,use_tray,show_window), startup_hook)
  File "/nix/store/mwjwlr3bdqcbggxmqqgnp7x25sqqznjm-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/__init__.py", line 101, in _startup
    window.init(show_window, use_tray)
  File "/nix/store/mwjwlr3bdqcbggxmqqgnp7x25sqqznjm-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/window.py", line 744, in init
    Gtk.Window.set_default_icon_from_file(_icons.icon_file(NAME.lower()))
TypeError: Argument 0 does not allow None as a value
Traceback (most recent call last):
  File "/nix/store/mwjwlr3bdqcbggxmqqgnp7x25sqqznjm-solaar-1.0.2/lib/python3.8/site-packages/solaar/ui/__init__.py", line 112, in _activate
    app.add_window(window._window)
TypeError: Argument 1 does not allow None as a value
```
I'm running i3 as my desktop environment

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.32, NixOS, 21.05pre287001.39e6bf76474 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre287001.39e6bf76474"`
 - channels(aszen): `"nixos-21.05pre283256.b2f2d04f01b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by JulesdeCube** [comment]
same problem with `solaar` + `i3`.

@spinus how you investigation progress?


```
solaar:116186): Gtk-WARNING **: 20:12:05.764: Found an icon but could not load it. Most likely gdk-pixbuf does not provide SVG support.
Traceback (most recent call last):
  File "/nix/store/r9brgyp5q586i9wb4hn9a9ryk9yza53h-solaar-1.0.6/lib/python3.9/site-packages/solaar/ui/__init__.py", line 159, in <lambda>
    application.connect('startup', lambda app, startup_hook: _startup(app, startup_hook, use_tray, show_window), startup_hook)
  File "/nix/store/r9brgyp5q586i9wb4hn9a9ryk9yza53h-solaar-1.0.6/lib/python3.9/site-packages/solaar/ui/__init__.py", line 117, in _startup
    window.init(show_window, use_tray)
  File "/nix/store/r9brgyp5q586i9wb4hn9a9ryk9yza53h-solaar-1.0.6/lib/python3.9/site-packages/solaar/ui/window.py", line 832, in init
    Gtk.Window.set_default_icon_from_file(_icons.icon_file(NAME.lower()))
TypeError: Argument 0 does not allow None as a value
Traceback (most recent call last):
  File "/nix/store/r9brgyp5q586i9wb4hn9a9ryk9yza53h-solaar-1.0.6/lib/python3.9/site-packages/solaar/ui/__init__.py", line 128, in _activate
    app.add_window(window._window)
TypeError: Argument 1 does not allow None as a value
```

```
- system: "x86_64-linux"
- multi-user?: yes
- version: nix-env (Nix) 2.3.15
- channels(root): "nixos-21.11pre309670.253aecf69ed"
- channels(jules): ""
- nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```
