### ISSUE TITLE
qutebrowser crashes on unstable

### ISSUE THREAD

**Issue by wedens** [NixOS/nixpkgs#118784]
I've updated nixpkgs to a recent nixos-unstable (`3d1a7716d7f1fccbd7d30ab3b2ed3db831f43bde`) which contains #116724, #118084, #118263. 

After the update, as soon as I invoke `:version` command in qutebrowser or try to open a downloaded file from qutebrowser or just start it as `qutebrowser -V`, it crashes with an error (`QVersionNumber` part is always the same):

```
Traceback (most recent call last):
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/bin/.qutebrowser-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/qutebrowser.py", line 218, in main
    return app.run(args)
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/app.py", line 105, in run
    print(version.version_info())
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/utils/version.py", line 850, in version_info
    dist = distribution()
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/utils/version.py", line 165, in distribution
    dist_version = utils.VersionNumber.parse(info[version_key])
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/utils/utils.py", line 129, in parse
    return cls(*ver.normalized().segments())
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/utils/utils.py", line 92, in __init__
    self._ver = QVersionNumber(*args)
TypeError: arguments did not match any overloaded call:
  QVersionNumber(): too many arguments
  QVersionNumber(Iterable[int]): argument 1 has unexpected type 'int'
  QVersionNumber(int): too many arguments
  QVersionNumber(int, int): too many arguments
  QVersionNumber(int, int, int): too many arguments
  QVersionNumber(QVersionNumber): argument 1 has unexpected type 'int'

```

/cc @dotlambda  @rnhmjoj

**Comment by wedens** [comment]
Looks like it's an issue upstream: https://github.com/qutebrowser/qutebrowser/issues/6354.

Maybe we should add the patch?

**Comment by dotlambda** [comment]
I can't reproduce the issue on 3d1a7716d7f1fccbd7d30ab3b2ed3db831f43bde.

**Comment by wedens** [comment]
@dotlambda 
Here is what I have in `/etc/os-release` (that's what caused qutebrowser to crash, according to the fix in the linked issue):
```
NAME=NixOS
ID=nixos
VERSION="20.09.20210402.46ba1c3 (Nightingale)"
VERSION_CODENAME=nightingale
VERSION_ID="20.09.20210402.46ba1c3"
PRETTY_NAME="NixOS 20.09 (Nightingale)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```
Specifically, `VERSION_ID` and `VERSION` fields.

**Comment by rnhmjoj** [comment]
If I had to guess, @dotlambda is running a system built from a git checkout, so the version is something like `VERSION="21.05.git.3d1a771"` which doesn't trigger the crash.

**Comment by dotlambda** [comment]
> If I had to guess, @dotlambda is running a system built from a git checkout, so the version is something like `VERSION="21.05.git.3d1a771"` which doesn't trigger the crash.

Indeed.
