### ISSUE TITLE
update.py script for vim plugins hits github rate limit

### ISSUE THREAD

**Issue by legendofmiracles** [NixOS/nixpkgs#119534]
**Describe the bug**
The `update.py` script for vim plugins doesn't work, instead of generating a list it only prints `429 Too many Requests errors`
```
> ./update.py --add "sophacles/vim-processing"
warning: unknown setting 'experimental-features'
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
```
After a few minutes it crashes with the following text printed really often: 

```
indentLine: HTTP Error 429: too many requests
Traceback (most recent call last):
  File "/home/nix/nixpkgs/maintainers/scripts/pluginupdate.py", line 385, in prefetch
    plugin, redirect = prefetch_plugin(owner, repo, branch, alias, cache)
  File "/home/nix/nixpkgs/maintainers/scripts/pluginupdate.py", line 239, in prefetch_plugin
    commit, date = repo.latest_commit()
  File "/home/nix/nixpkgs/maintainers/scripts/pluginupdate.py", line 62, in f_retry
    return f(*args, **kwargs)
  File "/home/nix/nixpkgs/maintainers/scripts/pluginupdate.py", line 109, in latest_commit
    with urllib.request.urlopen(commit_req, timeout=10) as req:
  File "/nix/store/5470xw15wnn972ap0c4f7q642z4nvh6f-python3-3.8.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/5470xw15wnn972ap0c4f7q642z4nvh6f-python3-3.8.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/nix/store/5470xw15wnn972ap0c4f7q642z4nvh6f-python3-3.8.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/nix/store/5470xw15wnn972ap0c4f7q642z4nvh6f-python3-3.8.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/nix/store/5470xw15wnn972ap0c4f7q642z4nvh6f-python3-3.8.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/nix/store/5470xw15wnn972ap0c4f7q642z4nvh6f-python3-3.8.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: too many requests
```
**To Reproduce**
Run the `pkgs/misc/vim-plugins/update.py` script without any arguments

**Expected behavior**
It running normally and finishing with a status code of `0`

**Additional context**
Someone on IRC said that it has something to do with the PyPI XMLRPC Search being disabled.

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.27, NixOS, 21.05pre281538.9e377a6ce42 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(root): `"nixos-21.05pre281538.9e377a6ce42"`
 - channels(nix): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment]
you can go through the related issues to get to work around. Basically you need to authenticate with a github token to increase the rate limit or you can decrease the update.py's speed by using --proc=1

**Comment by legendofmiracles** [comment]
The flag fixed it.
