### ISSUE TITLE
IntelliJ IDEA Ultimate 2021.1 crashes on startup

### ISSUE THREAD

**Issue by chrispickard** [NixOS/nixpkgs#119618]
**Describe the bug**
IntelliJ IDEA Ultimate 2021.1 crashes on startup because it is unable to load 'e2p'. 

**To Reproduce**
1. upgrade to 2021.1
2. start idea-ultimate

**Expected behavior**
idea ultimate starts successfully

<details>
<summary>Relevant logs on startup</summary>

```
java.lang.UnsatisfiedLinkError: Unable to load library 'e2p':
libe2p.so: cannot open shared object file: No such file or directory
libe2p.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libe2p.so) not found in resource path (/nix/store/b9cgm0kb3vabpzfds7ay0hry0law7kh2-idea-ultimate-2021.1/idea-ultimate-2021.1/lib/bootstrap.jar:/nix/store/b9cgm0kb3vabpzfds7ay0hry0law7kh2-idea-ultimate-2021.1/idea-ultimate-2021.1/lib/util.jar:/n
ix/store/b9cgm0kb3vabpzfds7ay0hry0law7kh2-idea-ultimate-2021.1/idea-ultimate-2021.1/lib/jdom.jar:/nix/store/b9cgm0kb3vabpzfds7ay0hry0law7kh2-idea-ultimate-2021.1/idea-ultimate-2021.1/lib/log4j.jar:/nix/store/b9cgm0kb3vabpzfds7ay0hry0law7kh2-idea-ultimate-2021.1/idea-ultima
te-2021.1/lib/jna.jar:/lib/tools.jar)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Library$Handler.<init>(Library.java:192)
        at com.sun.jna.Native.load(Native.java:596)
        at com.sun.jna.Native.load(Native.java:570)
        at com.intellij.openapi.util.io.FileSystemUtil$E2P.<clinit>(FileSystemUtil.java:745)
        at com.intellij.openapi.util.io.FileSystemUtil.getLinuxCaseSensitivity(FileSystemUtil.java:714)
        at com.intellij.openapi.util.io.FileSystemUtil.readCaseSensitivityByNativeAPI(FileSystemUtil.java:545)
        at com.intellij.openapi.util.io.FileSystemUtil.readParentCaseSensitivity(FileSystemUtil.java:477)
        at com.intellij.openapi.vfs.newvfs.VfsImplUtil.generateCaseSensitivityChangedEventForUnknownCase(VfsImplUtil.java:306)
        at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.updateCaseSensitivityIfUnknown(VirtualDirectoryImpl.java:314)
        at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:77)
        at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:513)
        at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:45)
        at com.intellij.openapi.vfs.impl.FilePartNode.findChildThroughJar(FilePartNode.java:476)
        at com.intellij.openapi.vfs.impl.FilePartNodeRoot.findOrCreateByPath(FilePartNodeRoot.java:181)
        at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.getOrCreate(VirtualFilePointerManagerImpl.java:348)
        at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.create(VirtualFilePointerManagerImpl.java:248)
        at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.create(VirtualFilePointerManagerImpl.java:159)
        at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.create(VirtualFilePointerContainerImpl.java:343)
        at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.lambda$addAll$1(VirtualFilePointerContainerImpl.java:180)
        at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1894)
        at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.addAll(VirtualFilePointerContainerImpl.java:180)
        at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.readExternal(VirtualFilePointerContainerImpl.java:62)
        at com.intellij.openapi.projectRoots.impl.RootsAsVirtualFilePointers.read(RootsAsVirtualFilePointers.java:146)
        at com.intellij.openapi.projectRoots.impl.RootsAsVirtualFilePointers.readExternal(RootsAsVirtualFilePointers.java:84)
        at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.readExternal(ProjectJdkImpl.java:181)
        at com.intellij.openapi.projectRoots.impl.ProjectJdkTableImpl.loadState(ProjectJdkTableImpl.java:313)
        at com.intellij.openapi.projectRoots.impl.JavaAwareProjectJdkTableImpl.loadState(JavaAwareProjectJdkTableImpl.java:93)
        at com.intellij.openapi.projectRoots.impl.JavaAwareProjectJdkTableImpl.loadState(JavaAwareProjectJdkTableImpl.java:20)
        at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:440)
        at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:372)
        at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:123)
        at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:49)
        at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:433)
        at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:53)
        at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:13)
        at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.run(ServiceComponentAdapter.kt:43)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
        at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:42)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:64)
        at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:488)
        at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
        at com.intellij.openapi.projectRoots.ProjectJdkTable.getInstance(ProjectJdkTable.java:22)
        at com.android.tools.idea.sdk.AndroidSdks.lambda$getAllAndroidSdks$0(AndroidSdks.java:215)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:844)
        at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
        at com.android.tools.idea.sdk.AndroidSdks.getAllAndroidSdks(AndroidSdks.java:215)
        at com.android.tools.idea.sdk.AndroidSdks.getAndroidSdkPathsFromExistingPlatforms(AndroidSdks.java:194)
        at com.android.tools.idea.sdk.AndroidSdks.tryToChooseAndroidSdk(AndroidSdks.java:181)
        at org.jetbrains.android.sdk.AndroidSdkUtils.isAndroidSdkAvailable(AndroidSdkUtils.java:437)
        at org.jetbrains.android.actions.RunAndroidAvdManagerAction.update(RunAndroidAvdManagerAction.java:59)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$1(ActionUtil.java:170)
        at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
        at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
        at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:510)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$1(ActionUpdater.java:104)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:147)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$2(ActionUpdater.java:105)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:492)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:333)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:308)
        at com.intellij.util.TimeoutUtil.compute(TimeoutUtil.java:134)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$22(ActionUpdater.java:307)
        at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1511)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:307)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:389)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:308)
        at com.intellij.util.TimeoutUtil.compute(TimeoutUtil.java:134)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$22(ActionUpdater.java:307)
        at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1511)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:307)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:199)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:173)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupWithTimeout$11(ActionUpdater.java:215)
        at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
        at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.withTimeout(ProgressIndicatorUtils.java:310)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroupWithTimeout(ActionUpdater.java:215)
        at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroupWithTimeout(ActionUpdater.java:207)
        at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1118)
        at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.updateActionsImpl(ActionToolbarImpl.java:175)
        at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:151)
        at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:70)
        at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1097)
        at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1092)
        at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:213)
        at java.desktop/java.awt.Container.addImpl(Container.java:1146)
        at java.desktop/java.awt.Container.add(Container.java:489)
        at com.intellij.openapi.wm.impl.IdeRootPane.updateToolbar(IdeRootPane.java:224)
        at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$beforeProjectOpenedTask$1.run(ToolWindowManagerImpl.kt:405)
        at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
        at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
        at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
        Suppressed: java.lang.UnsatisfiedLinkError: libe2p.so: cannot open shared object file: No such file or directory
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
                ... 130 more
        Suppressed: java.lang.UnsatisfiedLinkError: libe2p.so: cannot open shared object file: No such file or directory
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
                ... 130 more
        Suppressed: java.io.IOException: Native library (linux-x86-64/libe2p.so) not found in resource path (/nix/store/b9cgm0kb3vabpzfds7ay0hry0law7kh2-idea-ultimate-2021.1/idea-ultimate-2021.1/lib/bootstrap.jar:/nix/store/b9cgm0kb3vabpzfds7ay0hry0law7kh2-idea-ultimate-20
21.1/idea-ultimate-2021.1/lib/util.jar:/nix/store/b9cgm0kb3vabpzfds7ay0hry0law7kh2-idea-ultimate-2021.1/idea-ultimate-2021.1/lib/jdom.jar:/nix/store/b9cgm0kb3vabpzfds7ay0hry0law7kh2-idea-ultimate-2021.1/idea-ultimate-2021.1/lib/log4j.jar:/nix/store/b9cgm0kb3vabpzfds7ay0hry
0law7kh2-idea-ultimate-2021.1/idea-ultimate-2021.1/lib/jna.jar:/lib/tools.jar)
                at com.sun.jna.Native.extractFromResourcePath(Native.java:1096)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
                ... 130 more


```
</details>

**Notify maintainers**
@edwtjo @mic92

**Metadata**
```
» nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.27, NixOS, 21.05pre282669.e019872af81 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(chris.pickard): `"home-manager"`
 - channels(root): `"nixos-21.05pre282669.e019872af81"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
Thanks!

**Comment by Mic92** [comment]
If e2p is in the package itself maybe we need to add its directory back to the rpath? It seems to load it in a `dlopen` like manner.
`LD_DEBUG=libs ls -la` might help.

**Comment by SakulK** [comment]
FYI I had the same issue with idea-community but today I did `sudo nixos-rebuild switch --upgrade` once again and it works fine now

**Comment by Mic92** [comment]
I cannot reproduce the problem as well with current master.
You can test like this:

```console
$ nix-store -r /nix/store/fdm073xb89p4l0536q0xng80i0d7pvy8-idea-ultimate-2021.1/bin/idea-ultimate
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/fdm073xb89p4l0536q0xng80i0d7pvy8-idea-ultimate-2021.1
$ /nix/store/fdm073xb89p4l0536q0xng80i0d7pvy8-idea-ultimate-2021.1/bin/idea-ultimate
```

**Comment by Tchekda** [comment]
I'm currently having the same problem on all of my Jetbrains products (PHPStorm, Rider, Webstorm).
`nixos-rebuild switch --upgrade` and `nix-store -r` didn't help....
Is there any other solutions  ?

**Comment by Mic92** [comment]
@Tchekda

Try if it crashes in a pure environment:

```console
$ nix-shell --pure -p jetbrains.rider
```

**Comment by Tchekda** [comment]
> @Tchekda
> 
> Try if it crashes in a pure environment:
> 
> ```
> $ nix-shell --pure -p jetbrains.rider
> ```
@Mic92 
Hi, thank you for your proposition but sadly it doesn't work.... Here are the rider logs [Pastebin](https://pastebin.com/0HSLwpe0)
And here is the command I used `nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/9abe4174c776625539ffa4c21477e7cf090bb587.tar.gz --pure -p jetbrains.rider`

**Comment by chrispickard** [comment]
hey everyone,
sorry I was out essentially all last week, however whatever work you all did took care of it. I'm on

```
» nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.29, NixOS, 21.05pre284548.1fe6ed37fd9 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(chris.pickard): `"home-manager"`
 - channels(root): `"nixos-21.05pre284548.1fe6ed37fd9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

and it is working again.

@Tchekda: Are you still having the same issue? if it's fixed feel free to close this issue

**Comment by Tchekda** [comment]
> hey everyone,
> sorry I was out essentially all last week, however whatever work you all did took care of it. I'm on
> 
> ```
> » nix-shell -p nix-info --run "nix-info -m"
>  - system: `"x86_64-linux"`
>  - host os: `Linux 5.10.29, NixOS, 21.05pre284548.1fe6ed37fd9 (Okapi)`
>  - multi-user?: `yes`
>  - sandbox: `yes`
>  - version: `nix-env (Nix) 2.3.10`
>  - channels(chris.pickard): `"home-manager"`
>  - channels(root): `"nixos-21.05pre284548.1fe6ed37fd9"`
>  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
> ```
> 
> and it is working again.
> 
> @Tchekda: Are you still having the same issue? if it's fixed feel free to close this issue

Hi @chrispickard, i'm still having this issue sadly....
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.11, NixOS, 20.09.3857.b2a189a8618 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(tchekda): `"home-manager-20.09, unstable-21.05pre282015.a73020b2a15"`
 - channels(root): `"nixos-20.09.3857.b2a189a8618, home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

But i found something interesting in the `backend.log` : 
```
It was not possible to find any compatible framework version                                                                                                               │
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.                                                                                                      │
  - The following frameworks were found:                                                                                                                                   │
      3.1.8 at [/nix/store/rynf6g7xhx9i0v9i3jiakx7s33gnzbz4-dotnet-sdk-3.1.402/shared/Microsoft.NETCore.App]                                                               │
                                                                                                                                                                           │
You can resolve the problem by installing the specified framework and/or SDK.                                                                                              │
                                                                                                                                                                           │
The specified framework can be found at:                                                                                                                                   │
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=nixos.20.09.3857.b2a189a8618-x64
 ```
I tried installing `dotnetCorePackages.net_5_0` but still the same error

**Comment by jwygoda** [comment]
I'm experiencing the same issue with pycharm-professional.

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.7, NixOS, 21.11.20210601.1c2986b (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.03pre265961.891f607d530"`
 - channels(xddd): `"home-manager, nixos-21.03pre253635.2247d824fe0"`
 - nixpkgs: `/nix/store/ypgnj9x286v31wf3061j60vqmyq7pc45-source`
```

**Comment by cideM** [comment]
Still happening

```
2021-07-26 23:09:21,999 [   4332]   WARN - openapi.util.io.FileSystemUtil - Unable to load library 'e2p':
libe2p.so: cannot open shared object file: No such file or directory
libe2p.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libe2p.so) not found in resource path (/nix/store/jss9iyl6591rqjh13w178cp9bvhfk1f5-goland-2021.1.3/goland-2021.1.3/lib/bootstrap.jar:/nix/store/jss9iyl6591rqjh13w178cp9bvhfk1f5-goland-2021.1.3/goland-2021.1.3/lib/util.jar:/nix/store/jss9iyl6591rqjh13w178cp9bvhfk1f5-goland-2021.1.3/goland-2021.1.3/lib/jdom.jar:/nix/store/jss9iyl6591rqjh13w178cp9bvhfk1f5-goland-2021.1.3/goland-2021.1.3/lib/log4j.jar:/nix/store/jss9iyl6591rqjh13w178cp9bvhfk1f5-goland-2021.1.3/goland-2021.1.3/lib/jna.jar)
java.lang.UnsatisfiedLinkError: Unable to load library 'e2p':
libe2p.so: cannot open shared object file: No such file or directory
libe2p.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libe2p.so) not found in resource path (/nix/store/jss9iyl6591rqjh13w178cp9bvhfk1f5-goland-2021.1.3/goland-2021.1.3/lib/bootstrap.jar:/nix/store/jss9iyl6591rqjh13w178cp9bvhfk1f5-goland-2021.1.3/goland-2021.1.3/lib/util.jar:/nix/store/jss9iyl6591rqjh13w178cp9bvhfk1f5-goland-2021.1.3/goland-2021.1.3/lib/jdom.jar:/nix/store/jss9iyl6591rqjh13w178cp9bvhfk1f5-goland-2021.1.3/goland-2021.1.3/lib/log4j.jar:/nix/store/jss9iyl6591rqjh13w178cp9bvhfk1f5-goland-2021.1.3/goland-2021.1.3/lib/jna.jar)
```

**Comment by cideM** [comment]
This should now be fixed
