### ISSUE TITLE
python2Packages.virtualenv: can't be built because importlib-resources dropped support for python2

### ISSUE THREAD

**Issue by kalekseev** [NixOS/nixpkgs#121011]
**Describe the bug**

importlib-resources was bumped to v5 that dropped support for python2 as a result virtualenv can't be built on python2

**To Reproduce**

```
❯ nix-build  --no-out-link -E 'with (import ./. { }); python2Packages.virtualenv'
these 2 derivations will be built:
  /nix/store/xsd3gx6zraxcpjdgi5xjyzqa1gcrfpmz-python2.7-importlib_resources-5.1.2.drv
  /nix/store/p4rrqccwnlgvacj0zv0ylcmscdq06m2d-python2.7-virtualenv-20.4.3.drv
building '/nix/store/xsd3gx6zraxcpjdgi5xjyzqa1gcrfpmz-python2.7-importlib_resources-5.1.2.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing setuptools-check-hook
unpacking sources
unpacking source archive /nix/store/wjc23gch97rynppgiywll43qxj628hq4-importlib_resources-5.1.2.tar.gz
source root is importlib_resources-5.1.2
setting SOURCE_DATE_EPOCH to timestamp 1614883644 of file importlib_resources-5.1.2/setup.cfg
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 6, in <module>
    setuptools.setup()
  File "/nix/store/lh376a85ihdvav132xniagq12335nnb3-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/25lzm81cpg9jqasc9pccl9dzx9gh7rdl-python-2.7.18/lib/python2.7/distutils/core.py", line 124, in setup
    dist.parse_config_files()
  File "/nix/store/lh376a85ihdvav132xniagq12335nnb3-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/nix/store/lh376a85ihdvav132xniagq12335nnb3-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/config.py", line 116, in parse_configuration
    options.parse()
  File "/nix/store/lh376a85ihdvav132xniagq12335nnb3-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/nix/store/lh376a85ihdvav132xniagq12335nnb3-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/nix/store/lh376a85ihdvav132xniagq12335nnb3-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/nix/store/lh376a85ihdvav132xniagq12335nnb3-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/config.py", line 577, in _parse_packages
    'find_namespace: directive is unsupported on Python < 3.3')
distutils.errors.DistutilsOptionError: find_namespace: directive is unsupported on Python < 3.3
error: builder for '/nix/store/xsd3gx6zraxcpjdgi5xjyzqa1gcrfpmz-python2.7-importlib_resources-5.1.2.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/p4rrqccwnlgvacj0zv0ylcmscdq06m2d-python2.7-virtualenv-20.4.3.drv' failed to build
```

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**
cc @FRidh 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(wtf): `"nixos-20.09-20.09.3975.17b101e29df, nixpkgs-21.05pre285827.267761cf444"`
 - nixpkgs: `/Users/wtf/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
I think the standard answer here is that we can add an older version of the package to enable the python2 support. Patches are welcome.

**Comment by teto** [comment]
havent we given up on python2 already ?

**Comment by veprbl** [comment]
> havent we given up on python2 already ?

Not to an extreme, and I'm personally pleased to see that.
