### ISSUE TITLE
jekyll: could not find a JavaScript runtime

### ISSUE THREAD

**Issue by kragniz** [NixOS/nixpkgs#12166]
Tested on unstable and current master:

Running jekyll causes the following error:

```
$ jekyll 
/nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/execjs-2.5.2/lib/execjs/runtimes.rb:48:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/execjs-2.5.2/lib/execjs.rb:5:in `<module:ExecJS>'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/execjs-2.5.2/lib/execjs.rb:4:in `<top (required)>'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `require'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `require'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `<top (required)>'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `require'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `<top (required)>'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:46:in `require'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:46:in `block in gracefully_require'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in `each'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in `gracefully_require'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/jekyll-2.5.3/lib/jekyll.rb:166:in `<top (required)>'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/jekyll-2.5.3/bin/jekyll:6:in `require'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/lib/ruby/gems/2.1.7/gems/jekyll-2.5.3/bin/jekyll:6:in `<top (required)>'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/bin/jekyll:21:in `load'
	from /nix/store/h16j5hnp2wgwzmw2q2w270ayggj7nx05-jekyll-2.5.3/bin/jekyll:21:in `<main>'
```

**Comment by jgillich** [comment]
Duplicate of #11564, TLDR: install `nodejs`. I'll look into fixing it.

**Comment by kragniz** [comment]
Thanks, sorry for the duplicate.
