### ISSUE TITLE
idea-ultimate: idea fails to start when hidpi mode is enabled

### ISSUE THREAD

**Issue by datakurre** [NixOS/nixpkgs#12228]
NixOS unstable has now Intellij Idea 15.0.1 and 15.0.2 is already in master. Idea >= 15 is supposed to support hidpi resolutions, but I cannot get it to work. It didn't auto-detect itself and copying and editing .vmoptions-files from /nix/store into ~/.IntellijIdea-folder didn't have effect. Any other NixOS users with hidpi screens around? Any tips would be appreciated (I'm new to hidpi on Linux).

Gnome 3 did auto-configure itself properly to run in its hidpi-mode (scaling-factor 2).

http://blog.jetbrains.com/idea/2015/07/intellij-idea-15-eap-comes-with-true-hidpi-support-for-windows-and-linux/

**Comment by datakurre** [comment]
@jgillich Does Idea work for you with 

```
xrandr --dpi 192 && idea-ultimate
```

My crashes in init with stack trace.

**Comment by datakurre** [comment]
```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[    632]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.ExceptionInInitializerError
	at com.intellij.util.ImageLoader.scaleImage(ImageLoader.java:108)
	at com.intellij.util.ImageLoader.loadFromUrl(ImageLoader.java:88)
	at com.intellij.util.ImageLoader.loadFromUrl(ImageLoader.java:66)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:371)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconWidth(IconLoader.java:394)
	at com.intellij.ui.Splash$SplashImage.getIconWidth(Splash.java:225)
	at javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(BasicLabelUI.java:223)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at javax.swing.JRootPane$RootLayout.preferredLayoutSize(JRootPane.java:920)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at com.intellij.ui.Splash.<init>(Splash.java:85)
	at com.intellij.ui.Splash.<init>(Splash.java:100)
	at com.intellij.idea.IdeaApplication$IdeStarter.a(IdeaApplication.java:245)
	at com.intellij.idea.IdeaApplication$IdeStarter.access$000(IdeaApplication.java:221)
	at com.intellij.idea.IdeaApplication.<init>(IdeaApplication.java:109)
	at com.intellij.idea.IdeaUltimateApplication.<init>(IdeaUltimateApplication.java:12)
	at com.intellij.idea.MainImpl$1$1.proceed(MainImpl.java:57)
	at com.intellij.ide.a.g.cb$2.run(cb$2.java:354)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: Can't load standard profile: GRAY.pf
	at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:935)
	at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:929)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.color.ICC_Profile.getStandardProfile(ICC_Profile.java:928)
	at java.awt.color.ICC_Profile.getDeferredInstance(ICC_Profile.java:1075)
	at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:895)
	at java.awt.color.ColorSpace.getInstance(ColorSpace.java:333)
	at org.imgscalr.Scalr.<clinit>(Scalr.java:344)
	... 41 more
[    635]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 15.0.1  Build #IU-143.382.35 
[    635]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_76 
[    635]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
[    635]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
[    636]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 

Start Failed: Internal error. Please report to http://jb.gg/ide/critical-startup-errors

java.lang.ExceptionInInitializerError
	at com.intellij.util.ImageLoader.scaleImage(ImageLoader.java:108)
	at com.intellij.util.ImageLoader.loadFromUrl(ImageLoader.java:88)
	at com.intellij.util.ImageLoader.loadFromUrl(ImageLoader.java:66)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:371)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconWidth(IconLoader.java:394)
	at com.intellij.ui.Splash$SplashImage.getIconWidth(Splash.java:225)
	at javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(BasicLabelUI.java:223)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at javax.swing.JRootPane$RootLayout.preferredLayoutSize(JRootPane.java:920)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1796)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at com.intellij.ui.Splash.<init>(Splash.java:85)
	at com.intellij.ui.Splash.<init>(Splash.java:100)
	at com.intellij.idea.IdeaApplication$IdeStarter.a(IdeaApplication.java:245)
	at com.intellij.idea.IdeaApplication$IdeStarter.access$000(IdeaApplication.java:221)
	at com.intellij.idea.IdeaApplication.<init>(IdeaApplication.java:109)
	at com.intellij.idea.IdeaUltimateApplication.<init>(IdeaUltimateApplication.java:12)
	at com.intellij.idea.MainImpl$1$1.proceed(MainImpl.java:57)
	at com.intellij.ide.a.g.cb$2.run(cb$2.java:354)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: Can't load standard profile: GRAY.pf
	at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:935)
	at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:929)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.color.ICC_Profile.getStandardProfile(ICC_Profile.java:928)
	at java.awt.color.ICC_Profile.getDeferredInstance(ICC_Profile.java:1075)
	at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:895)
	at java.awt.color.ColorSpace.getInstance(ColorSpace.java:333)
	at org.imgscalr.Scalr.<clinit>(Scalr.java:344)
	... 41 more
```

**Comment by edwtjo** [comment]
The ICC error has already been addressed upstream by not supporting openjdk with idea.

**Comment by datakurre** [comment]
@edwtjo Is there a workaround? Like optionally building Idea with nonfree Java?

**Comment by edwtjo** [comment]
Yes of course; Since jetbrains wontfix you have to override jdk with oraclejdk in your packageOverrides. I should add an assert for that.

**Comment by datakurre** [comment]
@edwtjo Thanks. Switching to oraclejdk8 fixed that error message. Hidpi support is still mostly broken, but because some dialogs (like splash) do scale correctly, it's probably more an issue of idea than nixos.

**Comment by datakurre** [comment]
Idea works properly after setting larger font manually and restarting it once. Thanks.

**Comment by danielgafni** [comment]
Hey @datakurre ! 

Sorry for necro posting, but it seems like the issue is still present, or at least hidpi doesn't work well out of the box. 

Is there any specific NixOS configuration code required to make it work in e.g. PyCharm? 

To be clear, the IDE does not crash, but has blurry text.
