### ISSUE TITLE
Markdown 3.2.2 fails tests with Python 3.6

### ISSUE THREAD

**Issue by cgevans** [NixOS/nixpkgs#123412]
**Describe the bug**
Markdown 3.2.2 fails tests when built with Python 3.6, in 20.09 and unstable.  3.1.1 (in 20.03) works.  3.2.2 with Python 3.7 (in 20.09) works.

I'm not sure whether this is a test-only problem that could be resolved with doCheck = false, or if Markdown 3.2.2 should be disabled for Python 3.6.

**To Reproduce**

In 20.09 and unstable, the following should cause the failure. 

```nix-env -iA {channel}.python36Packages.markdown```

**Screenshots**
```
Executing pipInstallPhase
/build/Markdown-3.2.2/dist /build/Markdown-3.2.2
Processing ./Markdown-3.2.2-py3-none-any.whl
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /nix/store/92vlxl0qmc2r4pidldbjb138375klihc-python3.6-importlib-metadata-1.7.0/lib/python3.6/site-packages (from Markdown==3.2.2) (1.7.0)
Requirement already satisfied: zipp>=0.5 in /nix/store/87s7qy8ss30525f6ndnvjv347qqaxg4z-python3.6-zipp-3.1.0/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->Markdown==3.2.2) (3.1.0)
Installing collected packages: Markdown
  WARNING: The script markdown_py is installed in '/nix/store/jkla535z76z93w0knkgvxn1f1lsza74s-python3.6-Markdown-3.2.2/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Markdown-3.2.2
/build/Markdown-3.2.2
Finished executing pipInstallPhase
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/jkla535z76z93w0knkgvxn1f1lsza74s-python3.6-Markdown-3.2.2
strip is /nix/store/vfqlryhvm8063hs7ax9k2vb8wmch5v0v-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/jkla535z76z93w0knkgvxn1f1lsza74s-python3.6-Markdown-3.2.2/lib  /nix/store/jkla535z76z93w0knkgvxn1f1lsza74s-python3.6-Markdown-3.2.2/bin
patching script interpreter paths in /nix/store/jkla535z76z93w0knkgvxn1f1lsza74s-python3.6-Markdown-3.2.2
checking for references to /build/ in /nix/store/jkla535z76z93w0knkgvxn1f1lsza74s-python3.6-Markdown-3.2.2...
Rewriting #!/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13/bin/python3.6 to #!/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13
wrapping `/nix/store/jkla535z76z93w0knkgvxn1f1lsza74s-python3.6-Markdown-3.2.2/bin/markdown_py'...
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
running install tests
no Makefile or custom buildPhase, doing nothing
pythonCatchConflictsPhase
pythonRemoveBinBytecodePhase
pythonImportsCheckPhase
Executing pythonImportsCheckPhase
setuptoolsCheckPhase
Executing setuptoolsCheckPhase
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing Markdown.egg-info/PKG-INFO
writing dependency_links to Markdown.egg-info/dependency_links.txt
writing entry points to Markdown.egg-info/entry_points.txt
writing requirements to Markdown.egg-info/requires.txt
writing top-level names to Markdown.egg-info/top_level.txt
reading manifest file 'Markdown.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'MANIFEST'
writing manifest file 'Markdown.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 143, in <module>
    'Topic :: Text Processing :: Markup :: HTML'
  File "/nix/store/kxmwmridqf2pkh431jfabpf30m547rsi-python3.6-setuptools-47.3.1/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/kxmwmridqf2pkh431jfabpf30m547rsi-python3.6-setuptools-47.3.1/lib/python3.6/site-packages/setuptools/command/test.py", line 238, in run
    self.run_tests()
  File "/nix/store/kxmwmridqf2pkh431jfabpf30m547rsi-python3.6-setuptools-47.3.1/lib/python3.6/site-packages/setuptools/command/test.py", line 260, in run_tests
    exit=False,
  File "/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13/lib/python3.6/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13/lib/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13/lib/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13/lib/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13/lib/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/nix/store/kxmwmridqf2pkh431jfabpf30m547rsi-python3.6-setuptools-47.3.1/lib/python3.6/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/q7icaxmiv3a5qma2gbzr6l9wzm18smr9-python3-3.6.13/lib/python3.6/unittest/loader.py", line 213, in loadTestsFromName
    raise TypeError("don't know how to make test from: %s" % obj)
TypeError: don't know how to make test from: <markdown.pep562.Pep562 object at 0x7ffff64b3ac8>
builder for '/nix/store/9hp9llc5fx1bdh4pfjxy8j33bi511vph-python3.6-Markdown-3.2.2.drv' failed with exit code 1
error: build of '/nix/store/9hp9llc5fx1bdh4pfjxy8j33bi511vph-python3.6-Markdown-3.2.2.drv' failed
```

**Additional context**

**Notify maintainers**
@FRidh 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- python36Packages.markdown
# a list of nixos modules affected by the problem
module:
```

**Comment by cgevans** [comment]
This appears to be Nix-specific: building and running tests with `python setup.py test` in a virtualenv with `nix-shell -p python36` works.

**Comment by smancill** [comment]
@cgevans I think this was resolved by the linked PR.
