### ISSUE TITLE
lens becomes unresponsive when trying to download logs.

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#123688]
**Describe the bug**

I have had a few issues with lens recently, first I couldn't see the logs but removing ~/.config/Lens/extensions fixed it.
On every reboot, I seem to run into though.
```
[Error: EACCES: permission denied, rmdir '/home/teto/.config/Lens/extensions/example-extension/dist'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'rmdir',
  path: '/home/teto/.config/Lens/extensions/example-extension/dist'
}
Trace
    at App.<anonymous> (/nix/store/awpa9hrf7m50zznjhdjg86r93kyh1px2-lens-4.2.4-extracted/resources/app.asar/static/build/main.js:1:189261)
```

Once I was able to see the logs of a pod (can be tricky, you have to go to the pods list and click one button at the top right), I tried to download the logs but then lens becomes unresponsive with the following log.
`
(kontena-lens:2): GLib-GIO-ERROR **: 15:47:30.768: No GSettings schemas are installed on the system
`
Nothing happens and I have to kill lens.

(I've installed lens via nix-env with a rcent nixpkgs 35220510333528e005606552a63a83fcf500db47)

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
cc @dbirks

**Comment by dbirks** [comment]
Yeah I've been hitting the same issue on reboot. It (though I don't know exactly what) creates the extensions folder as root, and then lens can't remove it on startup -- or at least that's as far as I've been able to troubleshoot. I'm still pretty new to nixos.

**Comment by teto** [comment]
I dont think it can create them as root (apart if it's setuid but I dont see why it would be and I dont think it is the case). Also all the files belong to me. I haven't looked into but it calls rmdir while there are still files there so that could be it.

I am curious, coudl you reproduce the issue about downloading the logs ?

NB: thanks for packaging it, this software is really awesome.

**Comment by teto** [comment]
looking at 
```
Trace
    at App.<anonymous> (/nix/store/88qdw694lfw6r1cck4gp4irr0310awwz-lens-4.2.4-extracted/resources/app.asar/static/build/main.js:1:189261)
```
I tried to open the main.js file but I only have `/nix/store/88qdw694lfw6r1cck4gp4irr0310awwz-lens-4.2.4-extracted/resources/app.asar`
```
$ file /nix/store/88qdw694lfw6r1cck4gp4irr0310awwz-lens-4.2.4-extracted/resources/app.asar                                                                                                    
/nix/store/88qdw694lfw6r1cck4gp4irr0310awwz-lens-4.2.4-extracted/resources/app.asar: data
```
Is that some appimage trickery ?

**Comment by teto** [comment]
@dbirks would you consider packaging straight from source (e.g., without the appimage). I just remembered about https://github.com/NixOS/nixpkgs/pull/123358 and tested but it exhibits the same issues :(

**Comment by jan-kouba** [comment]
I'm still hitting this issue.
I'm still seeing exactly the same error message as described in the issue #135852, just with newer version.
It seems that Lens try to re-create extension directories on every start, but they create the extension directories without write permission. Then, on next start, when they try to delete files from the directories, it fails.

```
[node1:~/.config/Lens/extensions]$ ls -la
total 0
drwxr-xr-x 1 honza honza 240 23. pro 17.17 .
drwx------ 1 honza honza 992 23. pro 17.20 ..
dr-xr-xr-x 1 honza honza 128 23. pro 17.17 kube-object-event-status
dr-xr-xr-x 1 honza honza  50 23. pro 17.17 lenscloud-lens-extension
dr-xr-xr-x 1 honza honza 104 23. pro 17.17 license-menu-item
dr-xr-xr-x 1 honza honza 136 23. pro 17.17 metrics-cluster-feature
dr-xr-xr-x 1 honza honza 108 23. pro 17.17 node-menu
dr-xr-xr-x 1 honza honza 106 23. pro 17.17 pod-menu
dr-xr-xr-x 1 honza honza 102 23. pro 17.17 survey
dr-xr-xr-x 1 honza honza 108 23. pro 17.17 telemetry
```

**Comment by otavio** [comment]
I am facing it too. This is very annoying.

**Comment by Tchekda** [comment]
Same here, I tried giving write permission to the whole folder but it didn't help....

**Comment by nazarewk** [comment]
same here, I found related upstream issue https://github.com/lensapp/lens/issues/5261

**Comment by teto** [comment]
between the openlens -> lens -> mandatory login, I 've become quite proficient with k9s which is a lovely software. closing this
