### ISSUE TITLE
Runelite cannot enable GPU plugin (AMD hardware?)

### ISSUE THREAD

**Issue by Ashe** [NixOS/nixpkgs#123827]
**Describe the bug**
The runelite package doesn't install necessary packages for using the GPU plugin and I don't really know how to get it working.

I have AMD hardware if that matters. It seems like it's looking for `/home/ashe/natives/linux-amd64/libgluegen_rt.so` which doesn't exist and isn't symlinked to anywhere. I've tried installing packages `jdk`, `javaPackages.jogl_2_3_2` and neither of these fixed it. I'm not a very advanced user of nix and wasn't really sure how to proceed.

```
2021-05-20 20:23:15 [main] INFO  net.runelite.client.RuneLite - RuneLite 1.7.8.1 (launcher version 2.0.0) starting up, args: none
2021-05-20 20:23:17 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2021-05-20 20:23:17 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2021-05-20 20:23:17 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1277117578.139
2021-05-20 20:23:18 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
<... I deleted all the posts about other plugins ..>
2021-05-20 20:23:22 [Client] INFO  c.f.controller.DataHandler - initiating load
2021-05-20 20:23:22 [Client] INFO  c.f.db.TradePersister - flipping directory already exists so it's not being created
2021-05-20 20:23:22 [Client] INFO  c.f.controller.DataHandler - loading account wide data
2021-05-20 20:23:22 [Client] INFO  c.f.controller.DataHandler - successfully loaded account wide data
2021-05-20 20:23:22 [Client] INFO  c.f.controller.DataHandler - successfully loaded trades
2021-05-20 20:23:22 [Client] INFO  c.f.controller.FlippingPlugin - changing view to Accountwide
2021-05-20 20:23:22 [Client] INFO  c.f.jobs.WikiDataFetcherJob - started wiki fetching job
2021-05-20 20:23:23 [main] INFO  net.runelite.client.RuneLite - Client initialization took 7464ms. Uptime: 8484ms
2021-05-20 20:23:23 [pool-6-thread-1] INFO  c.f.jobs.CacheUpdaterJob - starting cache updator job!
2021-05-20 20:23:23 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1305,60,1409x453,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,2249x1366,invalid,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@18833be6,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-05-20 20:23:29 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.UnsatisfiedLinkError: Can't load library: /home/ashe/natives/linux-amd64/libgluegen_rt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2387)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:154)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:329)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:195)
	at eg.ct(eg.java:35168)
	at client.ak(client.java)
	at aq.xz(aq.java:357)
	at aq.run(aq.java:311)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-20 20:23:29 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$4(GpuPlugin.java:495)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:61)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:46)
	at net.runelite.client.plugins.gpu.GpuPlugin.shutDown(GpuPlugin.java:448)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:439)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:195)
	at eg.ct(eg.java:35168)
	at client.ak(client.java)
	at aq.xz(aq.java:357)
	at aq.run(aq.java:311)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-20 20:23:29 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$4(GpuPlugin.java:495)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:195)
	at eg.ct(eg.java:35168)
	at client.ak(client.java)
	at aq.xz(aq.java:357)
	at aq.run(aq.java:311)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-20 20:23:40 [Client] INFO  c.f.controller.FlippingPlugin - Crystal xo has just logged in!
2021-05-20 20:23:40 [Client] INFO  c.f.controller.FlippingPlugin - data handler does not contain data for Crystal xo
2021-05-20 20:23:40 [Client] INFO  c.f.controller.DataHandler - adding Crystal xo to data handler
2021-05-20 20:23:40 [Client] INFO  c.f.controller.FlippingPlugin - changing view to Crystal xo
2021-05-20 20:23:40 [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login
2021-05-20 20:23:45 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:329)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:195)
	at eg.ct(eg.java:35168)
	at client.ak(client.java)
	at aq.xz(aq.java:357)
	at aq.run(aq.java:311)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-20 20:23:45 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$4(GpuPlugin.java:495)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:61)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:46)
	at net.runelite.client.plugins.gpu.GpuPlugin.shutDown(GpuPlugin.java:448)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:439)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:195)
	at eg.ct(eg.java:35168)
	at client.ak(client.java)
	at aq.xz(aq.java:357)
	at aq.run(aq.java:311)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-20 20:23:45 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$4(GpuPlugin.java:495)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:195)
	at eg.ct(eg.java:35168)
	at client.ak(client.java)
	at aq.xz(aq.java:357)
	at aq.run(aq.java:311)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-20 20:23:50 [Client] INFO  c.f.controller.FlippingPlugin - Crystal xo is logging out
2021-05-20 20:23:50 [Client] INFO  c.f.controller.DataHandler - storing data
2021-05-20 20:23:50 [Client] INFO  c.f.controller.DataHandler - accounts with unsaved changes are [Crystal xo]. Saving them.
2021-05-20 20:23:50 [Client] INFO  c.f.db.TradePersister - storing trades for Crystal xo
```

**To Reproduce**
1. Install runelite package
2. Log in and try to activate runelite plugin 
3. It fails - check logs. Could be hardware dependent

**Expected behavior**
The GPU plugin enables without issue.

Instead, it disables instantaneously and outputs this to logs:

**Notify maintainers**
@Kmeakin 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05pre289339.83d907fd760 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05pre289339.83d907fd760"`
 - channels(ashe): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ashe** [comment]
More information (not sure if its a hardware thing or a general thing): It seems that the launcher for runelite downloads these 'missing' libraries into `.runelite` as shown below. I wonder if this issue with the GPU is because of some NixOS-specific issues with runelite being installed and not having access. 

I believe setting the following fixed the missing `libgluegen` error, but there's still the error with regards to `GLProfile` in the original post.
```
LD_LIBRARY_PATH=~/.runelite/repository2:$LD_LIBRARY_PATH
```

These are the libraries inside `.runelite/repository2`
```
~/.runelite/repository2
❯ tree
.
├── aopalliance-1.0.jar
├── archive-patcher-1.0.jar
├── client-1.7.8.1.jar
├── client-patch-1.7.8.1.jar
├── commons-csv-1.4.jar
├── commons-lang3-3.7.jar
├── commons-text-1.2.jar
├── discord-1.4.jar
├── gluegen-rt-2.4.0-rc-20200429.jar
├── gluegen-rt-2.4.0-rc-20200429-natives-linux-amd64.jar
├── gluegen-rt-2.4.0-rc-20200429-natives-windows-amd64.jar
├── gluegen-rt-2.4.0-rc-20200429-natives-windows-i586.jar
├── gluegen-rt-natives-macosx-2.4.0-rc-20210117.jar
├── gson-2.8.5.jar
├── guava-23.2-jre.jar
├── guice-4.1.0-no_aop.jar
├── http-api-1.7.8.1.jar
├── javax.inject-1.jar
├── jna-4.5.1.jar
├── jna-platform-4.5.1.jar
├── jocl-1.0.jar
├── jocl-1.0-macos-arm64.jar
├── jocl-1.0-macos-x64.jar
├── jogl-all-2.4.0-rc-20200429.jar
├── jogl-all-2.4.0-rc-20200429-natives-linux-amd64.jar
├── jogl-all-2.4.0-rc-20200429-natives-windows-amd64.jar
├── jogl-all-2.4.0-rc-20200429-natives-windows-i586.jar
├── jogl-all-natives-macosx-2.4.0-rc-20210117.jar
├── jopt-simple-5.0.1.jar
├── jsr305-3.0.2.jar
├── logback-classic-1.2.3.jar
├── logback-core-1.2.3.jar
├── okhttp-3.7.0.jar
├── okio-1.12.0.jar
├── runelite-api-1.7.8.1.jar
├── slf4j-api-1.7.25.jar
├── substance-8.0.02.jar
└── trident-1.5.00.jar
```

**Comment by Kmeakin** [comment]
I will look into this - the GPU plugin is broken on my machine as well. In the meantime you can try downloading the AppImage client from https://runelite.net/ and running it with `appimage-run RuneLite.AppImage` which is what I'm doing.

**Comment by Kmeakin** [comment]
@Ashe try this

```nix
{ stdenv, lib, pkgs, ... }:

stdenv.mkDerivation rec {
  pname = "runelite";
  version = "2.1.5";

  jar = pkgs.fetchurl {
    url = "https://github.com/runelite/launcher/releases/download/${version}/RuneLite.jar";
    sha256 = "4BX188QIjIFTxng2ktqlKn7AqQ9tdBcKWmgOj/5yd10=";
  };

  icon = pkgs.fetchurl {
    url = "https://github.com/runelite/launcher/raw/${version}/appimage/runelite.png";
    sha256 = "04fcjm7p546gr82g0jbh497j7rnh70lrvas0k171bff4v3knrjw1";
  };

  # The `.so` files provided by these two jars aren't detected by RuneLite for some reason, so we have to provide them manually
  jogl = pkgs.fetchurl {
    url = "https://repo.runelite.net/net/runelite/jogl/jogl-all/2.4.0-rc-20200429/jogl-all-2.4.0-rc-20200429-natives-linux-amd64.jar";
    sha256 = "S60qxyWY9RfyhLFygn/OxZFWnc8qVRtTFdWMbdu+2U0=";
  };
  gluegen = pkgs.fetchurl {
    url = "https://repo.runelite.net/net/runelite/gluegen/gluegen-rt/2.4.0-rc-20200429/gluegen-rt-2.4.0-rc-20200429-natives-linux-amd64.jar";
    sha256 = "eF8S5sQkJFDtW8rcVBKIyeyKm5Ze5rXK5r/yosZcHjU=";
  };
  dontUnpack = true;

  nativeBuildInputs = with pkgs; [ makeWrapper unzip ];
  installPhase = ''
    mkdir -p $out/share/runelite
    mkdir -p $out/share/applications
    mkdir -p $out/natives

    ${pkgs.unzip}/bin/unzip ${jogl}    'natives/*' -d $out
    ${pkgs.unzip}/bin/unzip ${gluegen} 'natives/*' -d $out

    ln -s ${jar} $out/share/runelite/RuneLite.jar

    # Cant use `makeDesktopItem` because we want to refer to `$out/bin/runelite`
    # Also heredocs dont seem to be working
    echo "[Desktop Entry]" > $out/share/applications/RuneLite.desktop
    echo "Type=Application" >> $out/share/applications/RuneLite.desktop
    echo "Exec=$out/bin/runelite" >> $out/share/applications/RuneLite.desktop
    echo "Terminal=false" >> $out/share/applications/RuneLite.desktop
    echo "Name=RuneLite" >> $out/share/applications/RuneLite.desktop
    echo "Icon=${icon}" >> $out/share/applications/RuneLite.desktop
    echo "Comment=Open source Old School RuneScape client" >> $out/share/applications/RuneLite.desktop
    echo "GenericName=Oldschool Runescape" >> $out/share/applications/RuneLite.desktop
    echo "Categories=Game" >> $out/share/applications/RuneLite.desktop
 
    makeWrapper ${pkgs.jre}/bin/java $out/bin/runelite \
      # RuneLite looks for `.so` files in $PWD/natives, so ensure that we set the PWD to the right place
      --run "cd $out" \
      --prefix LD_LIBRARY_PATH : "${pkgs.xorg.libXxf86vm}/lib" \
      --add-flags "-jar $out/share/runelite/RuneLite.jar"
  '';

  meta = with lib; {
    description = "Open source Old School RuneScape client";
    homepage = "https://runelite.net/";
    license = licenses.bsd2;
    maintainers = with maintainers; [ kmeakin ];
    platforms = [ "x86_64-linux" ];
  };
}
```

**Comment by Ashe** [comment]
> @Ashe try this

I added it to my home manager file like so (I apologise if this displays my lack of experience but it seems to be built): 
```nix
  home.packages = with pkgs; [
    (callPackage ./packages/runelite/runelite.nix {})
# ...
```
After rebuilding, I get this:
```nix
~/.config/nixpkgs master* 11s
❯ home-manager switch
these derivations will be built:
  /nix/store/kwj43xrqsfb8hps6gvqyg57lafwjwqpn-runelite-2.1.5.drv
  /nix/store/rv91brdbwzwvip8c1vg53d4pqi0k7mfr-home-manager-path.drv
  /nix/store/bfhzai5zsiyink0b7wg3vbb403jfngak-activation-script.drv
  /nix/store/67bh615fsiilwj7cgd8pjbgcajzci1zq-runelite-2.1.5-fish-completions.drv
  /nix/store/b5xj9qn6iw3mrbizsnzqzgbiy7vby8pb-ashe-fish-completions.drv
  /nix/store/fkax0wi00x8yjpg9ac92cwg4id6gnm88-hm_fontconfigconf.d10hmfonts.conf.drv
  /nix/store/c2zz9kj1qj5lgvfyix3pb2i8s3rjq8wm-home-manager-files.drv
  /nix/store/4synrn0gqc3xb97h6ads8rb610q6l9sa-home-manager-generation.drv
building '/nix/store/kwj43xrqsfb8hps6gvqyg57lafwjwqpn-runelite-2.1.5.drv'...
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
Archive:  /nix/store/mxmsspzc02w70c2xqfg0cx21il9pgbdf-jogl-all-2.4.0-rc-20200429-natives-linux-amd64.jar
  inflating: /nix/store/qa9s9lv6a8pcavhhlr8dzgwa6d57cml2-runelite-2.1.5/natives/linux-amd64/libjogl_desktop.so
  inflating: /nix/store/qa9s9lv6a8pcavhhlr8dzgwa6d57cml2-runelite-2.1.5/natives/linux-amd64/libjogl_mobile.so
  inflating: /nix/store/qa9s9lv6a8pcavhhlr8dzgwa6d57cml2-runelite-2.1.5/natives/linux-amd64/libnativewindow_awt.so
  inflating: /nix/store/qa9s9lv6a8pcavhhlr8dzgwa6d57cml2-runelite-2.1.5/natives/linux-amd64/libnativewindow_drm.so
  inflating: /nix/store/qa9s9lv6a8pcavhhlr8dzgwa6d57cml2-runelite-2.1.5/natives/linux-amd64/libnativewindow_x11.so
  inflating: /nix/store/qa9s9lv6a8pcavhhlr8dzgwa6d57cml2-runelite-2.1.5/natives/linux-amd64/libnewt_drm.so
  inflating: /nix/store/qa9s9lv6a8pcavhhlr8dzgwa6d57cml2-runelite-2.1.5/natives/linux-amd64/libnewt_head.so
Archive:  /nix/store/x9xdh820lqj4bv1hblraanll1h9zp8fm-gluegen-rt-2.4.0-rc-20200429-natives-linux-amd64.jar
  inflating: /nix/store/qa9s9lv6a8pcavhhlr8dzgwa6d57cml2-runelite-2.1.5/natives/linux-amd64/libgluegen_rt.so
/nix/store/qg8qhrxiab3r87xmaxbq565g1g8bnl57-stdenv-linux/setup: line 1332: --run: command not found
builder for '/nix/store/kwj43xrqsfb8hps6gvqyg57lafwjwqpn-runelite-2.1.5.drv' failed with exit code 127
cannot build derivation '/nix/store/rv91brdbwzwvip8c1vg53d4pqi0k7mfr-home-manager-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/67bh615fsiilwj7cgd8pjbgcajzci1zq-runelite-2.1.5-fish-completions.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4synrn0gqc3xb97h6ads8rb610q6l9sa-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/4synrn0gqc3xb97h6ads8rb610q6l9sa-home-manager-generation.drv' failed
```
Seems like something went wrong with `stdenv-linux/setup`? Did I do something wrong?

**Comment by Kmeakin** [comment]
My bad, there was a syntax error

```nix
{ stdenv, lib, pkgs, ... }:

stdenv.mkDerivation rec {
  pname = "runelite";
  version = "2.1.5";

  jar = pkgs.fetchurl {
    url = "https://github.com/runelite/launcher/releases/download/${version}/RuneLite.jar";
    sha256 = "4BX188QIjIFTxng2ktqlKn7AqQ9tdBcKWmgOj/5yd10=";
  };

  icon = pkgs.fetchurl {
    url = "https://github.com/runelite/launcher/raw/${version}/appimage/runelite.png";
    sha256 = "04fcjm7p546gr82g0jbh497j7rnh70lrvas0k171bff4v3knrjw1";
  };

  # The `.so` files provided by these two jars aren't detected by RuneLite for some reason, so we have to provide them manually
  jogl = pkgs.fetchurl {
    url = "https://repo.runelite.net/net/runelite/jogl/jogl-all/2.4.0-rc-20200429/jogl-all-2.4.0-rc-20200429-natives-linux-amd64.jar";
    sha256 = "S60qxyWY9RfyhLFygn/OxZFWnc8qVRtTFdWMbdu+2U0=";
  };
  gluegen = pkgs.fetchurl {
    url = "https://repo.runelite.net/net/runelite/gluegen/gluegen-rt/2.4.0-rc-20200429/gluegen-rt-2.4.0-rc-20200429-natives-linux-amd64.jar";
    sha256 = "eF8S5sQkJFDtW8rcVBKIyeyKm5Ze5rXK5r/yosZcHjU=";
  };
  dontUnpack = true;

  nativeBuildInputs = with pkgs; [ makeWrapper unzip ];
  installPhase = ''
    mkdir -p $out/share/runelite
    mkdir -p $out/share/applications
    mkdir -p $out/natives

    ${pkgs.unzip}/bin/unzip ${jogl}    'natives/*' -d $out
    ${pkgs.unzip}/bin/unzip ${gluegen} 'natives/*' -d $out

    ln -s ${jar} $out/share/runelite/RuneLite.jar

    # Cant use `makeDesktopItem` because we want to refer to `$out/bin/runelite`
    # Also heredocs dont seem to be working
    echo "[Desktop Entry]" > $out/share/applications/RuneLite.desktop
    echo "Type=Application" >> $out/share/applications/RuneLite.desktop
    echo "Exec=$out/bin/runelite" >> $out/share/applications/RuneLite.desktop
    echo "Terminal=false" >> $out/share/applications/RuneLite.desktop
    echo "Name=RuneLite" >> $out/share/applications/RuneLite.desktop
    echo "Icon=${icon}" >> $out/share/applications/RuneLite.desktop
    echo "Comment=Open source Old School RuneScape client" >> $out/share/applications/RuneLite.desktop
    echo "GenericName=Oldschool Runescape" >> $out/share/applications/RuneLite.desktop
    echo "Categories=Game" >> $out/share/applications/RuneLite.desktop
 
    # RuneLite looks for `.so` files in $PWD/natives, so ensure that we set the PWD to the right place
    makeWrapper ${pkgs.jre}/bin/java $out/bin/runelite \
      --run "cd $out" \
      --prefix LD_LIBRARY_PATH : "${pkgs.xorg.libXxf86vm}/lib" \
      --add-flags "-jar $out/share/runelite/RuneLite.jar"
  '';

  meta = with lib; {
    description = "Open source Old School RuneScape client";
    homepage = "https://runelite.net/";
    license = licenses.bsd2;
    maintainers = with maintainers; [ kmeakin ];
    platforms = [ "x86_64-linux" ];
  };
}
```

**Comment by Ashe** [comment]
@Kmeakin great job, that works perfectly!! 

Are you going to update the package in nixpkgs?

**Comment by Kmeakin** [comment]
I will do, but I should probably get someone to review it first
