### ISSUE TITLE
python33Packages.acd_cli: wrapper not expanding PYTHONPATH

### ISSUE THREAD

**Issue by womfoo** [NixOS/nixpkgs#12386]
``` bash
[kranium@silverspark:~]$ acd_cli
Traceback (most recent call last):
  File "/nix/store/imfbgzba79c1dciidvii2wd4mj0vm064-python3.3-acd_cli-0.3.1/bin/.acd_cli-wrapped", line 8, in <module>
    from acd_cli import main
  File "/nix/store/imfbgzba79c1dciidvii2wd4mj0vm064-python3.3-acd_cli-0.3.1/bin/acd_cli.py", line 2
    export PYTHONPATH=/nix/store/imfbgzba79c1dciidvii2wd4mj0vm064-python3.3-acd_cli-0.3.1/lib/python3.3/site-packages:/nix/store/vs9d5klxm0l7h15hr6imhgrxz8abljk4-python3.3-appdirs-1.4.0/lib/python3.3/site-packages:/nix/store/g8ays0y66j168rbm09j4q9l2qmlq91sm-python3-3.3.6/lib/python3.3/site-packages:/nix/store/yw34zp3adz4c97y41ajbjjrizm2jw80q-python3.3m-setuptools-18.2/lib/python3.3/site-packages:/nix/store/pfmc67ass8r15i3n39fvdlf16hc171ba-python3.3-colorama-0.3.3/lib/python3.3/site-packages:/nix/store/52apj2gmcnpi1f00hvj6sqkx8ky2n3i0-python3.3-dateutil-2.4.2/lib/python3.3/site-packages:/nix/store/xxkzk6a3s4bs4chrpylw1ik59qzsp6pf-python3.3-six-1.10.0/lib/python3.3/site-packages:/nix/store/4ncrdpkvl0hgrs0dyskc8pirnim8i8zv-python3.3-requests-2.8.1/lib/python3.3/site-packages:/nix/store/xi2gf8z71lvmajwfcq6qk2xkh8sj51i5-python3.3-requests-toolbelt-0.4.0/lib/python3.3/site-packages:/nix/store/lwaz7w0qcvydjv7fi66vwg5p6dybd4v9-python3.3-SQLAlchemy-0.7.10/lib/python3.3/site-packages${PYTHONPATH:+':'}$PYTHONPATH
                    ^
SyntaxError: invalid syntax
```

**Comment by womfoo** [comment]
closing case. issue no longer exists in top-level `acd-cli`
