### ISSUE TITLE
pypyPackages.mezzanine fails to build

### ISSUE THREAD

**Issue by kragniz** [NixOS/nixpkgs#12405]
Trying to build `pypyPackages.mezzanine` currently fails. Should this be disabled? It builds fine on other python versions.

#11589 triggers a rebuild of this, causing it to fail.

```
~/g/nixpkgs (master) $ nix-env -f ~/git/nixpkgs -iA pypyPackages.mezzanine
installing ‘pypy4.0-mezzanine-3.1.10’
these derivations will be built:
  /nix/store/45yrgm328fvc4k3cls540jamygqh1cp1-pypy4.0-mezzanine-3.1.10.drv
building path(s) ‘/nix/store/39kq3g4xybi23w02l7avb84y5wxy7qw9-pypy4.0-mezzanine-3.1.10’
unpacking sources
unpacking source archive /nix/store/qrjsfg8v8ifv5mymv72h3rbhcj43wqzr-3.1.10.tar.gz
source root is mezzanine-3.1.10
patching sources
configuring
/nix/store/9ndszsw5gziw31xx9d9bc3bfxk1x5bmm-stdenv/setup: line 69: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
building
/nix/store/fx1kaw6faw8vmpwbhmlhl4agxgb110yw-bash-4.3-p42/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/mezzanine
copying mezzanine/__init__.py -> build/lib/mezzanine
copying mezzanine/urls.py -> build/lib/mezzanine
creating build/lib/mezzanine/template
copying mezzanine/template/__init__.py -> build/lib/mezzanine/template
copying mezzanine/template/loader_tags.py -> build/lib/mezzanine/template
creating build/lib/mezzanine/generic
copying mezzanine/generic/managers.py -> build/lib/mezzanine/generic
copying mezzanine/generic/views.py -> build/lib/mezzanine/generic
copying mezzanine/generic/models.py -> build/lib/mezzanine/generic
copying mezzanine/generic/tests.py -> build/lib/mezzanine/generic
copying mezzanine/generic/__init__.py -> build/lib/mezzanine/generic
copying mezzanine/generic/fields.py -> build/lib/mezzanine/generic
copying mezzanine/generic/defaults.py -> build/lib/mezzanine/generic
copying mezzanine/generic/forms.py -> build/lib/mezzanine/generic
copying mezzanine/generic/admin.py -> build/lib/mezzanine/generic
copying mezzanine/generic/urls.py -> build/lib/mezzanine/generic
creating build/lib/mezzanine/galleries
copying mezzanine/galleries/models.py -> build/lib/mezzanine/galleries
copying mezzanine/galleries/tests.py -> build/lib/mezzanine/galleries
copying mezzanine/galleries/__init__.py -> build/lib/mezzanine/galleries
copying mezzanine/galleries/admin.py -> build/lib/mezzanine/galleries
creating build/lib/mezzanine/forms
copying mezzanine/forms/models.py -> build/lib/mezzanine/forms
copying mezzanine/forms/tests.py -> build/lib/mezzanine/forms
copying mezzanine/forms/signals.py -> build/lib/mezzanine/forms
copying mezzanine/forms/__init__.py -> build/lib/mezzanine/forms
copying mezzanine/forms/page_processors.py -> build/lib/mezzanine/forms
copying mezzanine/forms/fields.py -> build/lib/mezzanine/forms
copying mezzanine/forms/defaults.py -> build/lib/mezzanine/forms
copying mezzanine/forms/forms.py -> build/lib/mezzanine/forms
copying mezzanine/forms/admin.py -> build/lib/mezzanine/forms
creating build/lib/mezzanine/bin
copying mezzanine/bin/mezzanine_project.py -> build/lib/mezzanine/bin
copying mezzanine/bin/__init__.py -> build/lib/mezzanine/bin
copying mezzanine/bin/runtests.py -> build/lib/mezzanine/bin
creating build/lib/mezzanine/blog
copying mezzanine/blog/views.py -> build/lib/mezzanine/blog
copying mezzanine/blog/models.py -> build/lib/mezzanine/blog
copying mezzanine/blog/tests.py -> build/lib/mezzanine/blog
copying mezzanine/blog/__init__.py -> build/lib/mezzanine/blog
copying mezzanine/blog/feeds.py -> build/lib/mezzanine/blog
copying mezzanine/blog/defaults.py -> build/lib/mezzanine/blog
copying mezzanine/blog/forms.py -> build/lib/mezzanine/blog
copying mezzanine/blog/admin.py -> build/lib/mezzanine/blog
copying mezzanine/blog/urls.py -> build/lib/mezzanine/blog
creating build/lib/mezzanine/accounts
copying mezzanine/accounts/views.py -> build/lib/mezzanine/accounts
copying mezzanine/accounts/models.py -> build/lib/mezzanine/accounts
copying mezzanine/accounts/tests.py -> build/lib/mezzanine/accounts
copying mezzanine/accounts/__init__.py -> build/lib/mezzanine/accounts
copying mezzanine/accounts/defaults.py -> build/lib/mezzanine/accounts
copying mezzanine/accounts/forms.py -> build/lib/mezzanine/accounts
copying mezzanine/accounts/admin.py -> build/lib/mezzanine/accounts
copying mezzanine/accounts/urls.py -> build/lib/mezzanine/accounts
creating build/lib/mezzanine/project_template
copying mezzanine/project_template/fabfile.py -> build/lib/mezzanine/project_template
copying mezzanine/project_template/settings.py -> build/lib/mezzanine/project_template
copying mezzanine/project_template/__init__.py -> build/lib/mezzanine/project_template
copying mezzanine/project_template/wsgi.py -> build/lib/mezzanine/project_template
copying mezzanine/project_template/manage.py -> build/lib/mezzanine/project_template
copying mezzanine/project_template/urls.py -> build/lib/mezzanine/project_template
creating build/lib/mezzanine/twitter
copying mezzanine/twitter/managers.py -> build/lib/mezzanine/twitter
copying mezzanine/twitter/models.py -> build/lib/mezzanine/twitter
copying mezzanine/twitter/__init__.py -> build/lib/mezzanine/twitter
copying mezzanine/twitter/defaults.py -> build/lib/mezzanine/twitter
copying mezzanine/twitter/admin.py -> build/lib/mezzanine/twitter
creating build/lib/mezzanine/conf
copying mezzanine/conf/models.py -> build/lib/mezzanine/conf
copying mezzanine/conf/tests.py -> build/lib/mezzanine/conf
copying mezzanine/conf/__init__.py -> build/lib/mezzanine/conf
copying mezzanine/conf/context_processors.py -> build/lib/mezzanine/conf
copying mezzanine/conf/forms.py -> build/lib/mezzanine/conf
copying mezzanine/conf/admin.py -> build/lib/mezzanine/conf
creating build/lib/mezzanine/core
copying mezzanine/core/managers.py -> build/lib/mezzanine/core
copying mezzanine/core/middleware.py -> build/lib/mezzanine/core
copying mezzanine/core/request.py -> build/lib/mezzanine/core
copying mezzanine/core/views.py -> build/lib/mezzanine/core
copying mezzanine/core/models.py -> build/lib/mezzanine/core
copying mezzanine/core/tests.py -> build/lib/mezzanine/core
copying mezzanine/core/__init__.py -> build/lib/mezzanine/core
copying mezzanine/core/fields.py -> build/lib/mezzanine/core
copying mezzanine/core/defaults.py -> build/lib/mezzanine/core
copying mezzanine/core/auth_backends.py -> build/lib/mezzanine/core
copying mezzanine/core/sitemaps.py -> build/lib/mezzanine/core
copying mezzanine/core/forms.py -> build/lib/mezzanine/core
copying mezzanine/core/admin.py -> build/lib/mezzanine/core
copying mezzanine/core/exceptions.py -> build/lib/mezzanine/core
copying mezzanine/core/urls.py -> build/lib/mezzanine/core
creating build/lib/mezzanine/mobile
copying mezzanine/mobile/models.py -> build/lib/mezzanine/mobile
copying mezzanine/mobile/__init__.py -> build/lib/mezzanine/mobile
creating build/lib/mezzanine/utils
copying mezzanine/utils/cache.py -> build/lib/mezzanine/utils
copying mezzanine/utils/device.py -> build/lib/mezzanine/utils
copying mezzanine/utils/views.py -> build/lib/mezzanine/utils
copying mezzanine/utils/models.py -> build/lib/mezzanine/utils
copying mezzanine/utils/docs.py -> build/lib/mezzanine/utils
copying mezzanine/utils/tests.py -> build/lib/mezzanine/utils
copying mezzanine/utils/email.py -> build/lib/mezzanine/utils
copying mezzanine/utils/importing.py -> build/lib/mezzanine/utils
copying mezzanine/utils/__init__.py -> build/lib/mezzanine/utils
copying mezzanine/utils/sites.py -> build/lib/mezzanine/utils
copying mezzanine/utils/html.py -> build/lib/mezzanine/utils
copying mezzanine/utils/timezone.py -> build/lib/mezzanine/utils
copying mezzanine/utils/conf.py -> build/lib/mezzanine/utils
copying mezzanine/utils/urls.py -> build/lib/mezzanine/utils
creating build/lib/mezzanine/pages
copying mezzanine/pages/managers.py -> build/lib/mezzanine/pages
copying mezzanine/pages/middleware.py -> build/lib/mezzanine/pages
copying mezzanine/pages/views.py -> build/lib/mezzanine/pages
copying mezzanine/pages/models.py -> build/lib/mezzanine/pages
copying mezzanine/pages/tests.py -> build/lib/mezzanine/pages
copying mezzanine/pages/__init__.py -> build/lib/mezzanine/pages
copying mezzanine/pages/page_processors.py -> build/lib/mezzanine/pages
copying mezzanine/pages/fields.py -> build/lib/mezzanine/pages
copying mezzanine/pages/defaults.py -> build/lib/mezzanine/pages
copying mezzanine/pages/context_processors.py -> build/lib/mezzanine/pages
copying mezzanine/pages/admin.py -> build/lib/mezzanine/pages
copying mezzanine/pages/urls.py -> build/lib/mezzanine/pages
creating build/lib/mezzanine/boot
copying mezzanine/boot/models.py -> build/lib/mezzanine/boot
copying mezzanine/boot/lazy_admin.py -> build/lib/mezzanine/boot
copying mezzanine/boot/__init__.py -> build/lib/mezzanine/boot
creating build/lib/mezzanine/generic/templatetags
copying mezzanine/generic/templatetags/comment_tags.py -> build/lib/mezzanine/generic/templatetags
copying mezzanine/generic/templatetags/keyword_tags.py -> build/lib/mezzanine/generic/templatetags
copying mezzanine/generic/templatetags/rating_tags.py -> build/lib/mezzanine/generic/templatetags
copying mezzanine/generic/templatetags/__init__.py -> build/lib/mezzanine/generic/templatetags
copying mezzanine/generic/templatetags/disqus_tags.py -> build/lib/mezzanine/generic/templatetags
creating build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0009_auto__del_field_threadedcomment_email_hash.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0014_auto__add_field_rating_user.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0012_auto__add_field_rating_rating_date.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0011_auto__add_field_threadedcomment_rating_count__add_field_threadedcommen.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0010_auto__chg_field_keyword_slug__chg_field_keyword_title.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0007_auto__add_field_assignedkeyword__order.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0006_move_keywords.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0001_initial.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0005_keyword_site.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/__init__.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0004_auto__chg_field_rating_object_pk__chg_field_assignedkeyword_object_pk.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0013_auto__add_field_threadedcomment_rating_sum.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0009_auto__chg_field_keyword_title__chg_field_keyword_slug.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0002_auto__add_keyword__add_assignedkeyword.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0008_set_keyword_order.py -> build/lib/mezzanine/generic/migrations
copying mezzanine/generic/migrations/0003_auto__add_rating.py -> build/lib/mezzanine/generic/migrations
creating build/lib/mezzanine/galleries/migrations
copying mezzanine/galleries/migrations/0001_initial.py -> build/lib/mezzanine/galleries/migrations
copying mezzanine/galleries/migrations/__init__.py -> build/lib/mezzanine/galleries/migrations
creating build/lib/mezzanine/forms/migrations
copying mezzanine/forms/migrations/0005_auto__chg_field_fieldentry_value.py -> build/lib/mezzanine/forms/migrations
copying mezzanine/forms/migrations/0002_auto__add_field_field_placeholder_text.py -> build/lib/mezzanine/forms/migrations
copying mezzanine/forms/migrations/0001_initial.py -> build/lib/mezzanine/forms/migrations
copying mezzanine/forms/migrations/__init__.py -> build/lib/mezzanine/forms/migrations
copying mezzanine/forms/migrations/0003_auto__chg_field_field_field_type.py -> build/lib/mezzanine/forms/migrations
copying mezzanine/forms/migrations/0004_auto__chg_field_form_response__chg_field_form_content.py -> build/lib/mezzanine/forms/migrations
creating build/lib/mezzanine/blog/templatetags
copying mezzanine/blog/templatetags/__init__.py -> build/lib/mezzanine/blog/templatetags
copying mezzanine/blog/templatetags/blog_tags.py -> build/lib/mezzanine/blog/templatetags
creating build/lib/mezzanine/blog/management
copying mezzanine/blog/management/base.py -> build/lib/mezzanine/blog/management
copying mezzanine/blog/management/__init__.py -> build/lib/mezzanine/blog/management
creating build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0003_categories.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0010_category_site_allow_comments.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0013_auto__chg_field_blogpost_featured_image.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0016_add_field_blogpost__meta_title.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0004_auto__del_field_blogpost_category.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0014_auto__add_field_blogpost_gen_description.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0001_initial.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0015_auto__chg_field_blogcategory_title__chg_field_blogcategory_slug__chg_f.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/__init__.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0005_auto__del_comment__add_field_blogpost_comments_count__chg_field_blogpo.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0002_auto.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0011_comment_site_data.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0009_auto__chg_field_blogpost_content.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0020_auto__add_field_blogpost_created__add_field_blogpost_updated.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0012_auto__add_field_blogpost_featured_image.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0017_add_field_blogpost__related_posts.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0007_auto__add_field_blogpost_site.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0008_auto__add_field_blogpost_rating_average__add_field_blogpost_rating_cou.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0019_auto__add_field_blogpost_rating_sum.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0018_auto__add_field_blogpost_in_sitemap.py -> build/lib/mezzanine/blog/migrations
copying mezzanine/blog/migrations/0006_auto__del_field_blogpost__keywords__add_field_blogpost_keywords_string.py -> build/lib/mezzanine/blog/migrations
creating build/lib/mezzanine/blog/management/commands
copying mezzanine/blog/management/commands/import_tumblr.py -> build/lib/mezzanine/blog/management/commands
copying mezzanine/blog/management/commands/import_posterous.py -> build/lib/mezzanine/blog/management/commands
copying mezzanine/blog/management/commands/__init__.py -> build/lib/mezzanine/blog/management/commands
copying mezzanine/blog/management/commands/import_wordpress.py -> build/lib/mezzanine/blog/management/commands
copying mezzanine/blog/management/commands/import_rss.py -> build/lib/mezzanine/blog/management/commands
copying mezzanine/blog/management/commands/import_blogger.py -> build/lib/mezzanine/blog/management/commands
creating build/lib/mezzanine/accounts/templatetags
copying mezzanine/accounts/templatetags/__init__.py -> build/lib/mezzanine/accounts/templatetags
copying mezzanine/accounts/templatetags/accounts_tags.py -> build/lib/mezzanine/accounts/templatetags
creating build/lib/mezzanine/twitter/templatetags
copying mezzanine/twitter/templatetags/__init__.py -> build/lib/mezzanine/twitter/templatetags
copying mezzanine/twitter/templatetags/twitter_tags.py -> build/lib/mezzanine/twitter/templatetags
creating build/lib/mezzanine/twitter/management
copying mezzanine/twitter/management/__init__.py -> build/lib/mezzanine/twitter/management
creating build/lib/mezzanine/twitter/migrations
copying mezzanine/twitter/migrations/0002_auto__chg_field_query_value.py -> build/lib/mezzanine/twitter/migrations
copying mezzanine/twitter/migrations/0001_initial.py -> build/lib/mezzanine/twitter/migrations
copying mezzanine/twitter/migrations/__init__.py -> build/lib/mezzanine/twitter/migrations
creating build/lib/mezzanine/twitter/management/commands
copying mezzanine/twitter/management/commands/poll_twitter.py -> build/lib/mezzanine/twitter/management/commands
copying mezzanine/twitter/management/commands/__init__.py -> build/lib/mezzanine/twitter/management/commands
creating build/lib/mezzanine/conf/migrations
copying mezzanine/conf/migrations/0002_auto__add_field_setting_site.py -> build/lib/mezzanine/conf/migrations
copying mezzanine/conf/migrations/0004_ssl_account_settings_rename.py -> build/lib/mezzanine/conf/migrations
copying mezzanine/conf/migrations/0001_initial.py -> build/lib/mezzanine/conf/migrations
copying mezzanine/conf/migrations/__init__.py -> build/lib/mezzanine/conf/migrations
copying mezzanine/conf/migrations/0003_update_site_setting.py -> build/lib/mezzanine/conf/migrations
creating build/lib/mezzanine/core/templatetags
copying mezzanine/core/templatetags/__init__.py -> build/lib/mezzanine/core/templatetags
copying mezzanine/core/templatetags/mezzanine_tags.py -> build/lib/mezzanine/core/templatetags
creating build/lib/mezzanine/core/management
copying mezzanine/core/management/__init__.py -> build/lib/mezzanine/core/management
creating build/lib/mezzanine/core/migrations
copying mezzanine/core/migrations/0003_auto__add_sitepermission.py -> build/lib/mezzanine/core/migrations
copying mezzanine/core/migrations/0006_auto__add_unique_sitepermission_user.py -> build/lib/mezzanine/core/migrations
copying mezzanine/core/migrations/0001_initial.py -> build/lib/mezzanine/core/migrations
copying mezzanine/core/migrations/0002_auto__del_keyword.py -> build/lib/mezzanine/core/migrations
copying mezzanine/core/migrations/__init__.py -> build/lib/mezzanine/core/migrations
copying mezzanine/core/migrations/0004_set_site_permissions.py -> build/lib/mezzanine/core/migrations
copying mezzanine/core/migrations/0005_auto__chg_field_sitepermission_user__del_unique_sitepermission_user.py -> build/lib/mezzanine/core/migrations
creating build/lib/mezzanine/core/management/commands
copying mezzanine/core/management/commands/collecttemplates.py -> build/lib/mezzanine/core/management/commands
copying mezzanine/core/management/commands/runserver.py -> build/lib/mezzanine/core/management/commands
copying mezzanine/core/management/commands/createdb.py -> build/lib/mezzanine/core/management/commands
copying mezzanine/core/management/commands/__init__.py -> build/lib/mezzanine/core/management/commands
creating build/lib/mezzanine/pages/templatetags
copying mezzanine/pages/templatetags/pages_tags.py -> build/lib/mezzanine/pages/templatetags
copying mezzanine/pages/templatetags/__init__.py -> build/lib/mezzanine/pages/templatetags
creating build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0007_auto__chg_field_page_slug__chg_field_page_title.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0003_auto__add_field_page_site.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0002_auto__del_field_page__keywords__add_field_page_keywords_string__chg_fi.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0005_rename_contentpage.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0006_auto__add_field_page_gen_description.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0008_auto__add_link.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0001_initial.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/__init__.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0010_set_menus.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0004_auto__del_contentpage__add_richtextpage.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0013_auto__add_field_page_in_sitemap.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0009_add_field_page_in_menus.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0012_add_field_page__meta_title.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0014_auto__add_field_page_created__add_field_page_updated.py -> build/lib/mezzanine/pages/migrations
copying mezzanine/pages/migrations/0011_delete_nav_flags.py -> build/lib/mezzanine/pages/migrations
running egg_info
creating Mezzanine.egg-info
writing Mezzanine.egg-info/PKG-INFO
writing dependency_links to Mezzanine.egg-info/dependency_links.txt
writing entry points to Mezzanine.egg-info/entry_points.txt
writing requirements to Mezzanine.egg-info/requires.txt
writing top-level names to Mezzanine.egg-info/top_level.txt
writing manifest file 'Mezzanine.egg-info/SOURCES.txt'
Traceback (most recent call last):
  File "nix_run_setup.py", line 6, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 87, in <module>
    "Topic :: Software Development :: Libraries :: Python Modules",
  File "/nix/store/hh69yrk1rdjby3nk49zvvylsqbn2zhg7-pypy-4.0.1/pypy-c/lib-python/2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/nix/store/hh69yrk1rdjby3nk49zvvylsqbn2zhg7-pypy-4.0.1/pypy-c/lib-python/2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/nix/store/hh69yrk1rdjby3nk49zvvylsqbn2zhg7-pypy-4.0.1/pypy-c/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/nix/store/96qwrag1c4d13nlc30yj1n6c9w6zpxip-python-4.0.1-bootstrapped-pip-7.1.2/site-packages/wheel/bdist_wheel.py", line 176, in run
    self.run_command('build')
  File "/nix/store/hh69yrk1rdjby3nk49zvvylsqbn2zhg7-pypy-4.0.1/pypy-c/lib-python/2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/nix/store/hh69yrk1rdjby3nk49zvvylsqbn2zhg7-pypy-4.0.1/pypy-c/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/nix/store/hh69yrk1rdjby3nk49zvvylsqbn2zhg7-pypy-4.0.1/pypy-c/lib-python/2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/nix/store/hh69yrk1rdjby3nk49zvvylsqbn2zhg7-pypy-4.0.1/pypy-c/lib-python/2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/nix/store/hh69yrk1rdjby3nk49zvvylsqbn2zhg7-pypy-4.0.1/pypy-c/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 47, in run
    self.build_package_data()
  File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 103, in build_package_data
    for package, src_dir, build_dir, filenames in self.data_files:
  File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 59, in __getattr__
    self.data_files = files = self._get_data_files()
  File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 72, in _get_data_files
    self.analyze_manifest()
  File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 123, in analyze_manifest
    self.run_command('egg_info')
  File "/nix/store/hh69yrk1rdjby3nk49zvvylsqbn2zhg7-pypy-4.0.1/pypy-c/lib-python/2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/nix/store/hh69yrk1rdjby3nk49zvvylsqbn2zhg7-pypy-4.0.1/pypy-c/lib-python/2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 180, in run
    self.find_sources()
  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 207, in find_sources
    mm.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 291, in run
    self.add_defaults()
  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 320, in add_defaults
    sdist.add_defaults(self)
  File "build/bdist.linux-x86_64/egg/setuptools/command/sdist.py", line 98, in add_defaults
    self.filelist.append(fn)
  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 234, in append
    if self._safe_path(path):
  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 254, in _safe_path
    u_path = unicode_utils.filesys_decode(path)
  File "build/bdist.linux-x86_64/egg/setuptools/unicode_utils.py", line 31, in filesys_decode
    return path.decode(enc)
TypeError: expected string, got NoneType object
builder for ‘/nix/store/45yrgm328fvc4k3cls540jamygqh1cp1-pypy4.0-mezzanine-3.1.10.drv’ failed with exit code 1
error: build of ‘/nix/store/45yrgm328fvc4k3cls540jamygqh1cp1-pypy4.0-mezzanine-3.1.10.drv’ failed
```

**Comment by FRidh** [comment]
cc maintainer @prikhi
Tests are already disabled so who knows whether this package actually works. Furthermore, [version 4.0.1](https://pypi.python.org/pypi/Mezzanine/4.0.1) is already available.
