### ISSUE TITLE
urlwatch: matrix_client not working

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#124309]
**Describe the bug**
Trying to use the matrix notification fails.

**To Reproduce**
1. Setup a config with matrix enabled
2. Let urlwatch check a URL.
3. Observe the error

**Expected behavior**
Working matrix integration

**Screenshots**
```
urlwatch 2.19, Copyright 2008-2020 Thomas Perl
Website: https://thp.io/2008/urlwatch/
watched 2 URLs in 0 seconds
Traceback (most recent call last):
  File "/nix/store/f5g1kd2ncrffrq95fn3b87dn0i13k1sv-urlwatch-2.19/bin/.urlwatch-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/f5g1kd2ncrffrq95fn3b87dn0i13k1sv-urlwatch-2.19/lib/python3.8/site-packages/urlwatch/cli.py", line 112, in main
    urlwatch_command.run()
  File "/nix/store/f5g1kd2ncrffrq95fn3b87dn0i13k1sv-urlwatch-2.19/lib/python3.8/site-packages/urlwatch/command.py", line 298, in run
    self.urlwatcher.close()
  File "/nix/store/f5g1kd2ncrffrq95fn3b87dn0i13k1sv-urlwatch-2.19/lib/python3.8/site-packages/urlwatch/main.py", line 99, in close
    self.report.finish()
  File "/nix/store/f5g1kd2ncrffrq95fn3b87dn0i13k1sv-urlwatch-2.19/lib/python3.8/site-packages/urlwatch/handler.py", line 181, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/nix/store/f5g1kd2ncrffrq95fn3b87dn0i13k1sv-urlwatch-2.19/lib/python3.8/site-packages/urlwatch/reporters.py", line 109, in submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "/nix/store/f5g1kd2ncrffrq95fn3b87dn0i13k1sv-urlwatch-2.19/lib/python3.8/site-packages/urlwatch/reporters.py", line 705, in submit
    raise ImportError('Python module "matrix_client" not installed')
ImportError: Python module "matrix_client" not installed
```

**Notify maintainers**
@kmein

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.119, NixOS, 20.09.4165.1f7155200fa (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-20.09.4165.1f7155200fa, nixos-unstable-21.05pre280949.fae6b041601"`
 - channels(dfrank): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: urlwatch
# a list of nixos modules affected by the problem
module:
```

**Comment by fabaff** [comment]
@tokudan, could you please test #124419?

**Comment by tokudan** [comment]
@fabaff I get an error about an invalid token, but I assume that's wrong configuration on my end. Thanks for being so fast!
