### ISSUE TITLE
mastodon-init-db.service fails to execute

### ISSUE THREAD

**Issue by Obikawa** [NixOS/nixpkgs#124541]
Greetings.

First, I want to thank everyone for the hard work to bring Mastodon to NixOs.

I am trying to deploy the server on the unstable channel. Here is the log of the failing service:
```
● mastodon-init-db.service
     Loaded: loaded (/nix/store/8cgnyi8rxxk4zm3afxv9c95wrczw3b68-unit-mastodon-init-db.service/mastodon-init-db.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-05-26 22:04:08 CEST; 28ms ago
    Process: 71780 ExecStart=/nix/store/q3i044xxj9295rpb0vriqhwx87h9adr3-unit-script-mastodon-init-db-start/bin/mastodon-init-db-start (code=exited, status=1/FAILURE)
   Main PID: 71780 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 3.799s

maj 26 22:04:08 obikawa14 mastodon-init-db-start[71786]: rails aborted!
maj 26 22:04:08 obikawa14 mastodon-init-db-start[71786]: Psych::SyntaxError: (<unknown>): did not find expected whitespace or line break while scanning a tag at line 22 column 20
maj 26 22:04:08 obikawa14 mastodon-init-db-start[71786]: /nix/store/ar3xygprf0kk78xzpggh3fkcks15q97m-mastodon-3.4.0/config/environment.rb:5:in `<top (required)>'
maj 26 22:04:08 obikawa14 mastodon-init-db-start[71786]: /nix/store/ar3xygprf0kk78xzpggh3fkcks15q97m-mastodon-3.4.0/bin/rails:4:in `<main>'
maj 26 22:04:08 obikawa14 mastodon-init-db-start[71786]: Tasks: TOP => db:schema:load => db:load_config => environment
maj 26 22:04:08 obikawa14 mastodon-init-db-start[71786]: (See full trace by running task with --trace)
maj 26 22:04:08 obikawa14 systemd[1]: mastodon-init-db.service: Main process exited, code=exited, status=1/FAILURE
maj 26 22:04:08 obikawa14 systemd[1]: mastodon-init-db.service: Failed with result 'exit-code'.
maj 26 22:04:08 obikawa14 systemd[1]: Failed to start mastodon-init-db.service.
maj 26 22:04:08 obikawa14 systemd[1]: mastodon-init-db.service: Consumed 3.799s CPU time, no IP traffic.
```

And here is my .nix file with the mastodon declaration, mostly a copy of the defaults:
```
{
  pkgs ,
  ...
}: {
  services.mastodon = {
    enable = true;

    automaticMigrations = true;
    configureNginx = true;
    enableUnixSocket = true;
    group = "mastodon";
    localDomain = "mastodon.palin.pl";
    otpSecretFile = "/var/keys/mastodon/otp-secret";
    package = pkgs.mastodon;
    secretKeyBaseFile = "/var/keys/mastodon/secret-key-base";
    sidekiqPort = 55002;
    streamingPort = 55000;
    trustedProxy = "127.0.0.1";
    user = "mastodon";
    vapidPrivateKeyFile = "/var/keys/mastodon/vapid-private-key";
    vapidPublicKeyFile = "/var/keys/mastodon/vapid-public-key";
    webPort = 55001;

    database = {
      createLocally = true;

      host = "/run/postgresql";
      name = "mastodon";
      passwordFile = "/var/keys/mastodon/db-password";
      port = 5432;
      user = "mastodon";
    };

    elasticsearch = {
      host = null;
#      port = 9200;
    };

    extraConfig = {
    };

    redis = {
      createLocally = true;
      host = "127.0.0.1";
      port = 6379;
    };

    smtp = {
      authenticate = true;
      createLocally = false;
      fromAddress = "[---]";
      host = "[---]";
      passwordFile = "/var/keys/mastodon/smtp-password";
      port = 587;
      user = "[---]";
    };
  };
}
```

**Comment by Obikawa** [comment]
I have tried disabling the automaticMigrations. The installation went through, but now I get the same error on runtime. Here is the situation  log when I refresh my Mastodon page:

```
maj 28 21:07:18 obikawa14 nginx[496000]: 2021/05/28 21:07:18 [crit] 496000#496000: *79 connect() to unix:/run/mastodon-web/web.socket failed (2: No such file or directory) while connecting to upstream, client: 89.228.60.53, server: mastodon.palin.pl, request: "GET / HTTP/2.0", upstream: "http://unix:/run/mastodon-web/web.socket:/", host: "mastodon.palin.pl"
maj 28 21:07:31 obikawa14 systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 40.
maj 28 21:07:31 obikawa14 systemd[1]: Stopped Mastodon sidekiq.
maj 28 21:07:31 obikawa14 systemd[1]: mastodon-sidekiq.service: Consumed 4.255s CPU time, no IP traffic.
maj 28 21:07:31 obikawa14 systemd[1]: Started Mastodon sidekiq.
maj 28 21:07:31 obikawa14 sidekiq[498320]: `/nix/store/ar3xygprf0kk78xzpggh3fkcks15q97m-mastodon-3.4.0` is not writable.
maj 28 21:07:31 obikawa14 sidekiq[498320]: Bundler will use `/tmp/bundler20210528-498320-f8svqp498320' as your home directory temporarily.
maj 28 21:07:33 obikawa14 systemd[1]: mastodon-web.service: Scheduled restart job, restart counter is at 41.
maj 28 21:07:33 obikawa14 systemd[1]: Stopped Mastodon web.
maj 28 21:07:33 obikawa14 systemd[1]: mastodon-web.service: Consumed 3.725s CPU time, no IP traffic.
maj 28 21:07:33 obikawa14 systemd[1]: Started Mastodon web.
maj 28 21:07:33 obikawa14 puma[498329]: `/nix/store/ar3xygprf0kk78xzpggh3fkcks15q97m-mastodon-3.4.0` is not writable.
maj 28 21:07:33 obikawa14 puma[498329]: Bundler will use `/tmp/bundler20210528-498329-1249i6498329' as your home directory temporarily.
maj 28 21:07:34 obikawa14 puma[498329]: [498329] Puma starting in cluster mode...
maj 28 21:07:34 obikawa14 puma[498329]: [498329] * Puma version: 5.3.0 (ruby 3.0.1-p64) ("Sweetnighter")
maj 28 21:07:34 obikawa14 puma[498329]: [498329] *  Min threads: 5
maj 28 21:07:34 obikawa14 puma[498329]: [498329] *  Max threads: 5
maj 28 21:07:34 obikawa14 puma[498329]: [498329] *  Environment: production
maj 28 21:07:34 obikawa14 puma[498329]: [498329] *   Master PID: 498329
maj 28 21:07:34 obikawa14 puma[498329]: [498329] *      Workers: 2
maj 28 21:07:34 obikawa14 puma[498329]: [498329] *     Restarts: (✔) hot (✖) phased
maj 28 21:07:34 obikawa14 puma[498329]: [498329] * Preloading application
maj 28 21:07:35 obikawa14 sidekiq[498320]: 2021-05-28T19:07:35.691Z pid=498320 tid=arck INFO: Booting Sidekiq 6.2.1 with redis options {:driver=>:hiredis, :url=>"redis://127.0.0.1:6379/0", :namespace=>nil}
maj 28 21:07:35 obikawa14 sidekiq[498320]: 2021-05-28T19:07:35.753Z pid=498320 tid=arck WARN: Psych::SyntaxError: (<unknown>): did not find expected whitespace or line break while scanning a tag at line 22 column 20
maj 28 21:07:35 obikawa14 sidekiq[498320]: 2021-05-28T19:07:35.754Z pid=498320 tid=arck WARN: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/psych.rb:456:in `parse'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/psych.rb:456:in `parse_stream'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/psych.rb:390:in `parse'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/psych.rb:280:in `load'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/secrets.rb:28:in `block in parse'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/secrets.rb:25:in `each'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/secrets.rb:25:in `each_with_object'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/secrets.rb:25:in `parse'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/application.rb:406:in `secrets'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/devise-4.8.0/lib/devise/secret_key_finder.rb:12:in `find'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/devise-4.8.0/lib/devise/rails.rb:37:in `block in <class:Engine>'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `run'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `each'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `call'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/x56a57yznh736c6g52n8qizzakrzmp67-ruby-3.0.1/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:60:in `run_initializers'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/application.rb:384:in `initialize!'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/ar3xygprf0kk78xzpggh3fkcks15q97m-mastodon-3.4.0/config/environment.rb:5:in `<top (required)>'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:265:in `boot_application'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:37:in `run'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/dyvjdfaf20ys0z05qmp239wyfx0pw4qp-mastodon-gems-3.4.0/lib/ruby/gems/3.0.0/gems/sidekiq-6.2.1/bin/sidekiq:31:in `<top (required)>'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/ar3xygprf0kk78xzpggh3fkcks15q97m-mastodon-3.4.0/bin/sidekiq:20:in `load'
maj 28 21:07:35 obikawa14 sidekiq[498320]: /nix/store/ar3xygprf0kk78xzpggh3fkcks15q97m-mastodon-3.4.0/bin/sidekiq:20:in `<main>'
maj 28 21:07:35 obikawa14 systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by erictapen** [comment]
Hey @Obikawa, sorry for not reaching back for almost a year...
In the meantime a lot has changed in the NixOS Mastodon module. Are you still using it and if yes could you try to check wether the issue still persists?

Btw, you don't need to explicitly set options to their default values. It can even lead to unexpected results, as we might change the default values in the future.
