### ISSUE TITLE
Gramps broken image

### ISSUE THREAD

**Issue by yourfavouriteuncle** [NixOS/nixpkgs#124700]
**Describe the bug**
```
2021-05-27 23:24:09.697: ERROR: grampsapp.py: line 156: Unhandled exception
Traceback (most recent call last):
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/grampsgui.py", line 794, in do_activate
    Gramps(self.argparser, self)
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/grampsgui.py", line 613, in __init__
    self._vm = ViewManager(app, dbstate,
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/viewmanager.py", line 189, in __init__
    self.__build_main_window() # sets self.uistate
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/viewmanager.py", line 261, in __build_main_window
    self.window.set_icon_from_file(ICON)
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/share/gramps/images/gramps.png” (3)

Error in sys.excepthook:
Traceback (most recent call last):
  File "/nix/store/qyv5ffskmq8fv9yf5mb6fr5yracavid4-python3-3.8.7/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/logger/_gtkhandler.py", line 44, in emit
    ErrorView(error_detail=self, rotate_handler=self._rotate_handler)
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/logger/_errorview.py", line 67, in __init__
    self.set_window(self.top, None, None)
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/managedwindow.py", line 499, in set_window
    set_titles(window, title, text, msg)
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/managedwindow.py", line 734, in set_titles
    window.set_icon_from_file(ICON)
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/share/gramps/images/gramps.png” (3)

Original exception was:
Traceback (most recent call last):
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/grampsgui.py", line 794, in do_activate
    Gramps(self.argparser, self)
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/grampsgui.py", line 613, in __init__
    self._vm = ViewManager(app, dbstate,
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/viewmanager.py", line 189, in __init__
    self.__build_main_window() # sets self.uistate
  File "/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/lib/python3.8/site-packages/gramps/gui/viewmanager.py", line 261, in __build_main_window
    self.window.set_icon_from_file(ICON)
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/nix/store/kb5kd1h4xhwcbihabi95ql680lbj1hdc-gramps-5.1.3/share/gramps/images/gramps.png” (3)
^C2021-05-27 23:24:12.965: ERROR: grampsgui.py: line 701:
Gramps failed to start. Please report a bug about this.
This could be because of an error in a (third party) View on startup.
To use another view, don't load a Family Tree, change view, and then load your Family Tree.
You can also change manually the startup view in the gramps.ini file
by changing the last-view parameter.
```

**To Reproduce**
1. start `gramps` on latest nightly

**Notify maintainers**

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.11pre291991.ea7d4aa9b82 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.11pre291991.ea7d4aa9b82, home-manager"`
 - channels(asdf): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by SCOTT-HAMILTON** [comment]
I tried reproducing with this but gramps works : 
Test driver code : 

<details>

```nix
let
  nixpkgs = builtins.fetchTarball {
    url = "http://github.com/NixOS/nixpkgs/archive/ea7d4aa9b8225abd6147339f0d56675d6f1f0fd1.tar.gz";
    sha256 = "11bwgyglag40w2y50nq2gg4697ymdjprkgip75kb3hjrvvwpma53";
  };
in
  import "${nixpkgs}/nixos/tests/make-test-python.nix" ({ pkgs, ...}: {
    system = "x86_64-linux";
    nodes.machine = { nodes, config, pkgs, ... }:
    {
      imports = [
        "${nixpkgs}/nixos/tests/common/user-account.nix"
        "${nixpkgs}/nixos/tests/common/x11.nix"
      ];
      environment.systemPackages = with pkgs; [
        gramps
      ];
    };
    enableOCR = true;
    testScript = ''
      start_all()
      machine.wait_for_x()
      machine.succeed("gramps & 1>&2")
      machine.wait_for_text("Gramps")
      machine.screenshot("screen1")
    '';
})
```

</details>

**Comment by vcunat** [comment]
I think the pixbuf loaders are plugins, so perhaps it's something around (not) using them from some impure path.
