### ISSUE TITLE
21.05 changes python 3 `pip install --editable .` to not produce the `site.py` inside the `PIP_PREFIX` which results in package not being found

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#125167]
**Describe the bug**

I'm not sure if this is due to Nixpkgs or something changed in upstream python.

I'm using `console_scripts` to produce a CLI command for python packages.

Here's an example project: https://github.com/MatrixAI/Python-Demo

Entering nix-shell, the command `python-demo` should just work.

The `shell.nix` will run:

```
pip install --editable .
```

Which produces the `pip_packages` with the installed executable.

On nixpkgs revision https://github.com/NixOS/nixpkgs/commit/d892551a834f826875d892519375c480b7fa7de3 this worked fine.

But with the latest 21.05: https://github.com/NixOS/nixpkgs/commit/7e9b0dff974c89e070da1ad85713ff3c20b0ca97

Running `python-demo` results in:

```
Traceback (most recent call last):
  File "/home/cmcdragonkai/Projects/Python-Demo/pip_packages/bin/python-demo", line 33, in <module>
    sys.exit(load_entry_point('python-demo', 'console_scripts', 'python-demo')())
  File "/home/cmcdragonkai/Projects/Python-Demo/pip_packages/bin/python-demo", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/nix/store/fn2kv4wn3n4kpv6sb96cp9hi65ra9zb1-python3-3.9.4/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/nix/store/fn2kv4wn3n4kpv6sb96cp9hi65ra9zb1-python3-3.9.4/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: python-demo
```

I've traced this problem to the `pip_packages/lib/python3.7/site-packages/site.py` file.

Originally this file would exist, and the links would work.

Now that file no longer gets generated after pip installation.

I tried copying `site.py` that was generated from the previous `pip install` under the old revision into the same location for the new `pip install`, and the `python-demo` command just works normally.

This is pretty strange, not sure why `site.py` is not being generated anymore.

**To Reproduce**

1. Clone https://github.com/MatrixAI/Python-Demo
2. Change `pkgs.nix` to `7e9b0dff974c89e070da1ad85713ff3c20b0ca97` as the new revision
3. Try `nix-shell` then `python-demo`

**Expected behavior**

I expect `python-demo` command to execute properly and end up executing the command that I'm editing inside `python_demo/__main__.py`.

**Comment by dgw** [comment]
Sounds like #108525
