### ISSUE TITLE
python3Packages.libusb1 broken on aarch64-darwin

### ISSUE THREAD

**Issue by prusnak** [NixOS/nixpkgs#125400]
build fails with:

```
______________________ ERROR collecting usb1/testUSB1.py _______________________
/nix/store/iklkh4c168gr82m9shqzbjcgcacd4zpn-python3-3.8.9/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:783: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
usb1/__init__.py:806: in <module>
    USBTransfer._USBTransfer__ctypesCallbackWrapper = libusb1.libusb_transfer_cb_fn_p(
E   MemoryError
```

same with importing the module with the check disabled:

```
$ python3
Python 3.8.9 (default, May 19 2021, 05:04:28) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libusb1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/sdg1gp8vrgzv9cc34mm88jrshn3vgv9k-python3.8-libusb1-1.9.2/lib/python3.8/site-packages/libusb1.py", line 8, in <module>
    from usb1.libusb1 import *
  File "/nix/store/sdg1gp8vrgzv9cc34mm88jrshn3vgv9k-python3.8-libusb1-1.9.2/lib/python3.8/site-packages/usb1/__init__.py", line 806, in <module>
    USBTransfer._USBTransfer__ctypesCallbackWrapper = libusb1.libusb_transfer_cb_fn_p(
MemoryError
```

x86_64-darwin works fine

**Comment by prusnak** [comment]
It seems the issue has resolved itself 🤷
