### ISSUE TITLE
Python: packages require newer setuptools because of environment markers

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#12565]
It is inevitable. We currently use setuptools 18.2 but it seems we need to upgrade to at least 18.5 since [`ipython` uses ` platform_python_implementation`](https://github.com/ipython/ipython/issues/9159) which was added in 18.5. The [latest version](https://pypi.python.org/pypi/setuptools) of setuptools is 19.4.

The last time we tried a newer setuptools, version 18.4, was during the [wheels changes](https://github.com/NixOS/nixpkgs/pull/11086), but that broke many packages.

At this point we can 
- try again a setuptools upgrade
- maintain patches for `ipython` and any other packages that start using such environment markers.

**Comment by FRidh** [comment]
setuptools 18.5 and 19.4 consistently break:
```
Traceback (most recent call last):
  File "nix_run_setup.py", line 6, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 38, in <module>
    main()
  File "setup.py", line 34, in main
    zip_safe=False,
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/s219nx333ahz7b1zyh2g7fc7ib7ahjr2-python3.5m-setuptools-19.4/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/setuptools/command/test.py", line 159, in run
  File "/nix/store/s219nx333ahz7b1zyh2g7fc7ib7ahjr2-python3.5m-setuptools-19.4/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/setuptools/command/test.py", line 140, in with_project_on_sys_path
  File "/nix/store/s219nx333ahz7b1zyh2g7fc7ib7ahjr2-python3.5m-setuptools-19.4/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/setuptools/command/test.py", line 180, in run_tests
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/nix/store/s219nx333ahz7b1zyh2g7fc7ib7ahjr2-python3.5m-setuptools-19.4/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/setuptools/command/test.py", line 38, in loadTestsFromModule
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/nix/store/s219nx333ahz7b1zyh2g7fc7ib7ahjr2-python3.5m-setuptools-19.4/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/setuptools/command/test.py", line 24, in loadTestsFromModule
  File "/nix/store/xm2yjz479faibz2pmhl46asn46kwx9fb-python3-3.5.1/lib/python3.5/unittest/loader.py", line 120, in loadTestsFromModule
    for name in dir(module):
TypeError: py.test.__dict__ is not a dictionary
```

**Comment by FRidh** [comment]
As mentioned in `setuptools/default.nix` the problem is introduced in setuptools 18.4.

**Comment by FRidh** [comment]
Problem seems to be solved by undoing two upstream commits.
https://bitbucket.org/pypa/setuptools/commits/2a74388a933c629ef747941a83596213d8dd0827?at=18.3
https://bitbucket.org/pypa/setuptools/commits/53d34a922b37c58f2fd8a5e375d6227bdeac7d25?at=18.3

The upstream commits will execute tests, even if no test suite is provided.

**Comment by copumpkin** [comment]
cc @domenkozar

**Comment by domenkozar** [comment]
@FRidh so the fix is really to disable tests for packages that don't contain tests?

**Comment by FRidh** [comment]
@domenkozar It would seem like it. We have a lot of packages that actually do have tests, but we simply do not invoke the test runner correctly. Many of those packages fail with really vague errors.

**Comment by domenkozar** [comment]
That's good then, we should fix those false positives.

**Comment by globin** [comment]
I guess #12552 fixed this?

**Comment by FRidh** [comment]
Yes indeed, thanks for reminder!
