### ISSUE TITLE
builds.sr.ht doesn't work

### ISSUE THREAD

**Issue by misuzu** [NixOS/nixpkgs#126111]
**Describe the bug**
builds.sr.ht doesn't work, https://github.com/NixOS/nixpkgs/pull/113244#issuecomment-855303926

**To Reproduce**

```nix
{ config, pkgs, ... }:

{
  networking.hosts = {
    "127.0.0.1" = [
      "builds.sr.ht.local"
      "dispatch.sr.ht.local"
      "git.sr.ht.local"
      "hub.sr.ht.local"
      "logs.sr.ht.local"
      "man.sr.ht.local"
      "meta.sr.ht.local"
      "paste.sr.ht.local"
      "todo.sr.ht.local"
      "sr.ht.local"
    ];
  };
  services.sourcehut = {
    enable = true;
    originBase = "sr.ht.local";
    services = [
      "builds"
      "dispatch"
      "git"
      "hub"
      "man"
      "meta"
      "paste"
      "todo"
    ];
    builds = {
      enableWorker = true;
    };
    settings = {
      "sr.ht" = {
        environment = "production";
        global-domain = "sr.ht.local";
        origin = "http://sr.ht.local";
        # nix shell nixpkgs#sourcehut.coresrht -c srht-keygen network
        network-key = "OeXzQ6A8Vcgt5QJkXScuxeXCtfdKzKev99BRNb3_CWQ=";
        # nix shell nixpkgs#sourcehut.coresrht -c srht-keygen service
        service-key = "62427596fed00fa48c19f95bc85c14d0c618a5f8c130b53ba9a6a6b403bf1507";
      };
      # nix shell nixpkgs#sourcehut.metasrht -c metasrht-manageuser -t admin -e mymail@gmail.com misuzu
      "meta.sr.ht" = {
        origin = "http://meta.sr.ht.local";
      };
      "meta.sr.ht::settings" = {
        onboarding-redirect = "http://meta.sr.ht.local";
        registration = "yes";
      };
      # nix shell nixpkgs#sourcehut.coresrht -c srht-keygen webhook
      webhooks.private-key= "U7yd/8mGs/v0O3kId4jpeSghUCa9tqP1fYQwSV8UOqo=";
    };
  };

  services.nginx = {
    enable = true;
    # only recommendedProxySettings are strictly required, but the rest make sense as well.
    recommendedTlsSettings = true;
    recommendedOptimisation = true;
    recommendedGzipSettings = true;
    recommendedProxySettings = true;

    virtualHosts = with pkgs.lib; {
      "builds.sr.ht.local".forceSSL = mkForce false;
      "dispatch.sr.ht.local".forceSSL = mkForce false;
      "git.sr.ht.local".forceSSL = mkForce false;
      "hub.sr.ht.local".forceSSL = mkForce false;
      "logs.sr.ht.local".forceSSL = mkForce false;
      "man.sr.ht.local".forceSSL = mkForce false;
      "meta.sr.ht.local".forceSSL = mkForce false;
      "paste.sr.ht.local".forceSSL = mkForce false;
      "todo.sr.ht.local".forceSSL = mkForce false;
      "sr.ht.local".forceSSL = mkForce false;
    };
  };
}
```
1. Create admin user (`nix shell nixpkgs#sourcehut.metasrht -c metasrht-manageuser -t admin -e mymail@gmail.com <your username>`).
2. Login on http://meta.sr.ht.local
3. Go to http://builds.sr.ht.local
4. Observe 500 error code.

**Expected behavior**
It works

**Additional context**
```
Jun 06 01:17:00 localhost postgres[902711]: [902711] ERROR:  relation "user" does not exist at character 543
Jun 06 01:17:00 localhost postgres[902711]: [902711] STATEMENT:  SELECT "user".id AS user_id, "user".created AS user_created, "user".updated AS user_updated, "user".username AS user_username, "user".email AS user_email, "user".user_type AS user_user_type, "user".url AS user_url, "user".location AS user_location, "user".bio AS user_bio, "user".suspension_notice AS user_suspension_notice, "user".oauth_token AS user_oauth_token, "user".oauth_token_expires AS user_oauth_token_expires, "user".oauth_token_scopes AS user_oauth_token_scopes, "user".oauth_revocation_token AS user_oauth_revocation_token
Jun 06 01:17:00 localhost postgres[902711]:         FROM "user"
Jun 06 01:17:00 localhost postgres[902711]:         WHERE "user".username = 'misuzu'
Jun 06 01:17:00 localhost gunicorn[902499]: [2021-06-06 01:17:00,641] ERROR in app: Exception on / [GET]
Jun 06 01:17:00 localhost gunicorn[902499]: Traceback (most recent call last):
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
Jun 06 01:17:00 localhost gunicorn[902499]:     self.dialect.do_execute(
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Jun 06 01:17:00 localhost gunicorn[902499]:     cursor.execute(statement, parameters)
Jun 06 01:17:00 localhost gunicorn[902499]: psycopg2.errors.UndefinedTable: relation "user" does not exist
Jun 06 01:17:00 localhost gunicorn[902499]: LINE 2: FROM "user"
Jun 06 01:17:00 localhost gunicorn[902499]:              ^
Jun 06 01:17:00 localhost gunicorn[902499]: The above exception was the direct cause of the following exception:
Jun 06 01:17:00 localhost gunicorn[902499]: Traceback (most recent call last):
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
Jun 06 01:17:00 localhost gunicorn[902499]:     response = self.full_dispatch_request()
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
Jun 06 01:17:00 localhost gunicorn[902499]:     rv = self.handle_user_exception(e)
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
Jun 06 01:17:00 localhost gunicorn[902499]:     reraise(exc_type, exc_value, tb)
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Jun 06 01:17:00 localhost gunicorn[902499]:     raise value
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/flask/app.py", line 1948, in full_dispatch_request
Jun 06 01:17:00 localhost gunicorn[902499]:     rv = self.preprocess_request()
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/flask/app.py", line 2242, in preprocess_request
Jun 06 01:17:00 localhost gunicorn[902499]:     rv = func()
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/srht/flask.py", line 388, in get_session_cookie
Jun 06 01:17:00 localhost gunicorn[902499]:     g.current_user = self.oauth_service.lookup_user(user_info["name"])
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/srht/oauth/interface.py", line 194, in lookup_user
Jun 06 01:17:00 localhost gunicorn[902499]:     user = User.query.filter(User.username == username).one_or_none()
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
Jun 06 01:17:00 localhost gunicorn[902499]:     ret = list(self)
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
Jun 06 01:17:00 localhost gunicorn[902499]:     return self._execute_and_instances(context)
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
Jun 06 01:17:00 localhost gunicorn[902499]:     result = conn.execute(querycontext.statement, self._params)
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
Jun 06 01:17:00 localhost gunicorn[902499]:     return meth(self, multiparams, params)
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
Jun 06 01:17:00 localhost gunicorn[902499]:     return connection._execute_clauseelement(self, multiparams, params)
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
Jun 06 01:17:00 localhost gunicorn[902499]:     ret = self._execute_context(
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
Jun 06 01:17:00 localhost gunicorn[902499]:     self._handle_dbapi_exception(
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
Jun 06 01:17:00 localhost gunicorn[902499]:     util.raise_(
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
Jun 06 01:17:00 localhost gunicorn[902499]:     raise exception
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
Jun 06 01:17:00 localhost gunicorn[902499]:     self.dialect.do_execute(
Jun 06 01:17:00 localhost gunicorn[902499]:   File "/nix/store/a8xq7rnhv9k4rj8s5wd94nmpx46im39d-python3-3.8.9-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Jun 06 01:17:00 localhost gunicorn[902499]:     cursor.execute(statement, parameters)
Jun 06 01:17:00 localhost gunicorn[902499]: sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "user" does not exist
Jun 06 01:17:00 localhost gunicorn[902499]: LINE 2: FROM "user"
Jun 06 01:17:00 localhost gunicorn[902499]:              ^
Jun 06 01:17:00 localhost gunicorn[902499]: [SQL: SELECT "user".id AS user_id, "user".created AS user_created, "user".updated AS user_updated, "user".username AS user_username, "user".email AS user_email, "user".user_type AS user_user_type, "user".url AS user_url, "user".location AS user_location, "user".bio AS user_bio, "user".suspension_notice AS user_suspension_notice, "user".oauth_token AS user_oauth_token, "user".oauth_token_expires AS user_oauth_token_expires, "user".oauth_token_scopes AS user_oauth_token_scopes, "user".oauth_revocation_token AS user_oauth_revocation_token
Jun 06 01:17:00 localhost gunicorn[902499]: FROM "user"
Jun 06 01:17:00 localhost gunicorn[902499]: WHERE "user".username = %(username_1)s]
Jun 06 01:17:00 localhost gunicorn[902499]: [parameters: {'username_1': 'misuzu'}]
Jun 06 01:17:00 localhost gunicorn[902499]: (Background on this error at: http://sqlalche.me/e/13/f405)
```

**Notify maintainers**

@tomberek 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.sourcehut
```

**Comment by tomberek** [comment]
I’ve noticed this too. Running buildsrht-initdb fixes it, not sure why sometimes it doesn’t run or if it’s due to a change, or some race condition.

**Comment by tomberek** [comment]
Looks like the original issue was because of the buildsrht/buildssrht confusion in `srht-update-profiles`, but [Drew is saying](https://lists.sr.ht/~sircmpwn/sr.ht-discuss/%3C20210609155741.pajmqdu5qcezbsmt%40tsurf%3E) it's a one-off problem that may not be needed anymore. This patch allows the preStart to proceed even if that script fails. If this works and we see that the whole thing is not needed we can remove that part of the script.

https://github.com/tomberek/nixpkgs/commit/20cab8aad8871b8cf1e1a9e46110a569925b6e35

@misuzu: does this work for you?

**Comment by misuzu** [comment]
> Looks like the original issue was because of the buildsrht/buildssrht confusion in `srht-update-profiles`, but [Drew is saying](https://lists.sr.ht/~sircmpwn/sr.ht-discuss/%3C20210609155741.pajmqdu5qcezbsmt%40tsurf%3E) it's a one-off problem that may not be needed anymore. This patch allows the preStart to proceed even if that script fails. If this works and we see that the whole thing is not needed we can remove that part of the script.
> 
> [tomberek@20cab8a](https://github.com/tomberek/nixpkgs/commit/20cab8aad8871b8cf1e1a9e46110a569925b6e35)
> 
> @misuzu: does this work for you?

I've removed the state before trying your changes.

It seems to load without 500s now, but I see the following error in logs:
```
Jun 10 15:20:46 localhost buildsrht-pre-start[2043385]: INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
Jun 10 15:20:46 localhost buildsrht-pre-start[2043385]: INFO  [alembic.runtime.migration] Will assume transactional DDL.
Jun 10 15:20:46 localhost buildsrht-pre-start[2043385]: INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
Jun 10 15:20:46 localhost buildsrht-pre-start[2043385]: INFO  [alembic.runtime.migration] Will assume transactional DDL.
Jun 10 15:20:46 localhost buildsrht-pre-start[2043464]: Traceback (most recent call last):
Jun 10 15:20:46 localhost buildsrht-pre-start[2043464]:   File "/nix/store/8yiy7xj35nyqdb341qb1p0ppc8yrv8yf-python3.8-srht-0.67.4/bin/.srht-update-profiles-wrapped", line 7, in <module>
Jun 10 15:20:46 localhost buildsrht-pre-start[2043464]:     app = __import__(site.replace(".", "") + ".app").app.app # disgusting hack
Jun 10 15:20:46 localhost buildsrht-pre-start[2043464]: ModuleNotFoundError: No module named 'buildssrht'
Jun 10 15:20:46 localhost systemd[1]: Started builds.sr.ht website service.
```

I've also tried submitting the following task:
```yaml
image: archlinux
packages:
  - meson
  - scdoc
  - wayland-protocols
  - wlroots-git
  - wayland
  - libxkbcommon
  - cairo
  - pango
  - gdk-pixbuf2
  - pixman
  - libinput
  - xorg-server-xwayland
sources:
  - https://github.com/swaywm/sway
tasks:
  - setup: |
      cd sway
      meson build
  - build: |
      cd sway
      ninja -C build
```

But it fails with a weird error:
```
[#2] 2021/06/10 15:26:33 Booting image archlinux (default) on port 22101
Unknown image archlinux
[#2] 2021/06/10 15:26:33 Error: boot: exit status 1
```

And it's not exactly clear from the documentation where it is searching for images.

**Comment by tomberek** [comment]
We could bring the image.nix into Nixpkgs which should make it possible to build the config.

For the qemu image, that looks great, make a PR? I wanted to start working on supporting the full set of images (i've focused only on the NixOS one till now).

**Comment by tomberek** [comment]
@misuzu i got something building/working in a flake context...... it's ugly at the moment, but something does work under pure flake evaluation.
https://github.com/tomberek/nixpkgs/tree/sourcehut-builds-qemu-image

This is based off your qemu image branch.
