### ISSUE TITLE
OBS v27 segfaults on start

### ISSUE THREAD

**Issue by djahandarie** [NixOS/nixpkgs#126410]
(Upstream bug, autoclosed due to NixOS not being supported: https://github.com/obsproject/obs-studio/issues/4852)

I get the following segv on start: 
```
#0  0x00007fff9f9fe510 in base::internal::SequenceLocalStorageMap::Get(int) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#1  0x00007fff9fa54795 in mojo::internal::MessageDispatchContext::MessageDispatchContext(mojo::Message*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#2  0x00007fffa065ffe4 in service_manager::mojom::ServiceManagerListenerStubDispatch::Accept(service_manager::mojom::ServiceManagerListener*, mojo::Message*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#3  0x00007fff9fa4ceb8 in mojo::internal::MultiplexRouter::ProcessIncomingMessage(mojo::internal::MultiplexRouter::MessageWrapper*, mojo::internal::MultiplexRouter::ClientCallBehavior, base::SequencedTaskRunner*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#4  0x00007fff9fa4c8e7 in mojo::internal::MultiplexRouter::Accept(mojo::Message*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#5  0x00007fff9fa46921 in mojo::Connector::DispatchMessage(mojo::Message) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#6  0x00007fff9fa4703b in mojo::Connector::ReadAllAvailableMessages() ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#7  0x00007fff9fa5a425 in mojo::SimpleWatcher::OnHandleReady(int, unsigned int, mojo::HandleSignalsState const&) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#8  0x00007fff9f9d80bd in base::TaskAnnotator::RunTask(char const*, base::PendingTask*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#9  0x00007fff9f9e744c in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#10 0x00007fff9f9e7899 in non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() () from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#11 0x00007fff9f9a85ff in base::(anonymous namespace)::WorkSourceDispatch(_GSource*, int (*)(void*), void*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#12 0x00007fffefe415ab in g_main_context_dispatch ()
   from /nix/store/dcb3cyba5wl6qimv6vwdpbi0kg0g1nlb-glib-2.68.2/lib/libglib-2.0.so.0
#13 0x00007fffefe41858 in g_main_context_iterate.constprop ()
   from /nix/store/dcb3cyba5wl6qimv6vwdpbi0kg0g1nlb-glib-2.68.2/lib/libglib-2.0.so.0
#14 0x00007fffefe4190f in g_main_context_iteration ()
   from /nix/store/dcb3cyba5wl6qimv6vwdpbi0kg0g1nlb-glib-2.68.2/lib/libglib-2.0.so.0
#15 0x00007ffff555f520 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /nix/store/z8s9ggc72xkhv9xfxk88q08rrylcxqjf-qtbase-5.15.2/lib/libQt5Core.so.5
#16 0x00007ffff5505d7b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /nix/store/z8s9ggc72xkhv9xfxk88q08rrylcxqjf-qtbase-5.15.2/lib/libQt5Core.so.5
#17 0x00007ffff550e360 in QCoreApplication::exec() ()
   from /nix/store/z8s9ggc72xkhv9xfxk88q08rrylcxqjf-qtbase-5.15.2/lib/libQt5Core.so.5
#18 0x0000000000482306 in main ()
```

This behavior was not present pre-v27.

@deviant @jb55 @MP2E

**Comment by djahandarie** [comment]
Not sure what the issue is but removing a scene that had a browser embed in it stopped the crash. (I tried it because libcef is chrome).

**Comment by deviant** [comment]
Okay, I can confirm that adding a Browser scene (then quitting OBS, then opening it again) will cause a segfault. Actually adding the scene does not cause any problems, although I was unable to get it to render anything.

**Comment by deviant** [comment]
This is probably due to our CEF version being out of date. Currently building with a newer copy…

**Comment by deviant** [comment]
It was indeed our CEF version being out of date. It's practically ancient, from 2019-07-27. Building against latest gives me an OBS that doesn't crash on startup & shows stuff in the Browser source. See #126505 for the fix.
