### ISSUE TITLE
create-elm-app doesn't work out of the box (fails to copy read-only directory)

### ISSUE THREAD

**Issue by kephas** [NixOS/nixpkgs#126916]
**Describe the bug**
`create-elm-app` fails to create files when copying its template from Nix store

**To Reproduce**
1. Install `create-elm-app`
2. Run `create-elm-app`

**Expected behavior**
A new Elm project is created

**Screenshots**
```
pierre@viper ~> nix-shell '<nixpkgs>' -p elmPackages.create-elm-app

[nix-shell:~]$ create-elm-app foo

Creating foo project...

Error: EACCES: permission denied, copyfile '/nix/store/12x5whhsfi40rn4ksjkab0jhy7fqq9yp-node_create-elm-app-5.22.0/lib/node_modules/create-elm-app/template/README.md' -> '/home/pierre/foo/README.md'
    at Object.copyFileSync (fs.js:1907:3)
    at copyFile (/nix/store/12x5whhsfi40rn4ksjkab0jhy7fqq9yp-node_create-elm-app-5.22.0/lib/node_modules/create-elm-app/node_modules/fs-extra/lib/copy-sync/copy-sync.js:68:8)
    at onFile (/nix/store/12x5whhsfi40rn4ksjkab0jhy7fqq9yp-node_create-elm-app-5.22.0/lib/node_modules/create-elm-app/node_modules/fs-extra/lib/copy-sync/copy-sync.js:52:41)
    at getStats (/nix/store/12x5whhsfi40rn4ksjkab0jhy7fqq9yp-node_create-elm-app-5.22.0/lib/node_modules/create-elm-app/node_modules/fs-extra/lib/copy-sync/copy-sync.js:47:39)
    at startCopy (/nix/store/12x5whhsfi40rn4ksjkab0jhy7fqq9yp-node_create-elm-app-5.22.0/lib/node_modules/create-elm-app/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:10)
    at copyDirItem (/nix/store/12x5whhsfi40rn4ksjkab0jhy7fqq9yp-node_create-elm-app-5.22.0/lib/node_modules/create-elm-app/node_modules/fs-extra/lib/copy-sync/copy-sync.js:134:10)
    at /nix/store/12x5whhsfi40rn4ksjkab0jhy7fqq9yp-node_create-elm-app-5.22.0/lib/node_modules/create-elm-app/node_modules/fs-extra/lib/copy-sync/copy-sync.js:127:39
    at Array.forEach (<anonymous>)
    at copyDir (/nix/store/12x5whhsfi40rn4ksjkab0jhy7fqq9yp-node_create-elm-app-5.22.0/lib/node_modules/create-elm-app/node_modules/fs-extra/lib/copy-sync/copy-sync.js:127:23)
    at mkDirAndCopy (/nix/store/12x5whhsfi40rn4ksjkab0jhy7fqq9yp-node_create-elm-app-5.22.0/lib/node_modules/create-elm-app/node_modules/fs-extra/lib/copy-sync/copy-sync.js:123:10) {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: '/nix/store/12x5whhsfi40rn4ksjkab0jhy7fqq9yp-node_create-elm-app-5.22.0/lib/node_modules/create-elm-app/template/README.md',
  dest: '/home/pierre/foo/README.md'
}
```

**Additional context**

**Notify maintainers**
@turboMaCk 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.0-7-amd64, Debian GNU/Linux, 11 (bullseye)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(pierre): `"nixpkgs-21.11pre293448.2a1c29ef4ba"`
 - nixpkgs: `/home/pierre/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: elmPackages.create-elm-app
# a list of nixos modules affected by the problem
module:
```

**Comment by turboMaCk** [comment]
Thanks I'll look in a more detail into this later.

**Comment by kephas** [comment]
The culprit seems to be `mkDirAndCopy` who chmods the destination to match the source, but when the source is in the Nix store, it is not writable. It seems a bug of `fs-extra` to chmod in such a way that you could not write…

**Comment by turboMaCk** [comment]
there are more packages that exhibit the same problem. for instance files generated by `elm-test init` also has these permissions. Current workaround is to fix this manually.
