### ISSUE TITLE
Protonvpn-GUI fails to connect

### ISSUE THREAD

**Issue by Anderssorby** [NixOS/nixpkgs#128114]
**Describe the bug**
When trying to connect to the server it fails to launch and produces the error message "shell not found in /etc/shells". I'm using zsh which for some reason is not listed in  /etc/shells 

**To Reproduce**
1. Install protonvpn-gui and login with your credentials
2. Try to connect to any server
3. Possibly use a different shell than bash as standard

**Expected behavior**
A successfull connection to a free protonvpn server

**Screenshots**
![Screenshot from 2021-06-25 13-15-27](https://user-images.githubusercontent.com/6331075/123417148-b35ed480-d5b7-11eb-841b-4891b1c90134.png)

**Additional context**

**Notify maintainers**

@jtcoolen @jefflabonte @SCOTT-HAMILTON @caugner @offlinehacker

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.44, NixOS, 21.05.1153.0ccd0d91361 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(anderscs): `"home-manager, unstable-21.11pre297740.c223fd60072"`
 - channels(root): `"nixos-21.05.1153.0ccd0d91361"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.protonvpn-gui
# a list of nixos modules affected by the problem
module: nixos.protonvpn-gui
```

**Comment by WolfangAukang** [comment]
FYI, I also use ZSH but I'm not able to reproduce this issue.

Also, there is a new version packaged. Can you please check if the same issue persists?

**Comment by nrdxp** [comment]
Having a similar issue, except that the gui tries to connect to a given server, but just stays stuck in the "connecting" screen forever, never actually making the connection. :shrug:

**Comment by WolfangAukang** [comment]
This is strange. Although I don't use ProtonVPN Plus anymore, I'm still able to use the default servers and connect to them:

![image](https://user-images.githubusercontent.com/8378365/163574548-cf1cd353-22c2-4338-b512-e0e2f49a7773.png)

**Comment by mainrs** [comment]
I have trouble using the Proton VPN GUI client. @WolfangAukang do you happen to have NetworkManager configured on your system? For some reason Proton VPN fails on my machine to connect. 

I get this error in the log files:

```console
Support for given configuration is not implemented
Traceback (most recent call last):
  File "/nix/store/7wjnygr4ym3k4285gi1q295acm2p4agp-protonvpn-gui-1.9.0/lib/python3.9/site-packages/protonvpn_gui/view_model/dashboard.py", line 352, in connect
    server = protonvpn.setup_connection(
  File "/nix/store/bsysrcgk5qa1w84pypazbrc97jlc0idn-python3.9-protonvpn-nm-lib-3.10.0/lib/python3.9/site-packages/protonvpn_nm_lib/api.py", line 158, in setup_connection
    self._env.connection_backend.setup(**data)
  File "/nix/store/bsysrcgk5qa1w84pypazbrc97jlc0idn-python3.9-protonvpn-nm-lib-3.10.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client.py", line 51, in setup
    connection, protocol_implementation = NMPlugin.import_vpn_config(
  File "/nix/store/bsysrcgk5qa1w84pypazbrc97jlc0idn-python3.9-protonvpn-nm-lib-3.10.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/plugin/nm_plugin.py", line 31, in import_vpn_config
    raise NotImplementedError(
NotImplementedError: Support for given configuration is not implemented
```

Sounds more like some misconfiguration on my machine than anything else. I installed from `github:NixOS/nixpkgs/nixpkgs-unstable`. 

I configured my system's networking like this:

```nix
networking.hostId = "<id>";
networking.interfaces.enp3s0.useDHCP = true;
networking.useDHCP = mkForce true;
```

**Comment by WolfangAukang** [comment]
> I get this error in the log files:

This is similar to https://github.com/NixOS/nixpkgs/issues/172831#issuecomment-1140287872. Unfortunately, the best recommendation would be checking if `protonvpn-cli_2` works (this one does not rely on NetworkManager).

I really don't know what can be done on this case because I'm really not sure of what causes this issue, rather open an issue on the `protonvpn-nm-lib` repo and hope for the best.

**Comment by mainrs** [comment]
I've actually went ahead and contacted Proton VPN support with my log files. I'll keep the issue updated if new information emerges.

**Comment by Nyabinary** [comment]
![image](https://github.com/NixOS/nixpkgs/assets/97130632/c951b2b5-e2dc-43f4-9fe2-48a82894ba9c)
Getting something different entirely

**Comment by raspher** [comment]
Same here, in addition their public repo is now archived https://github.com/ProtonVPN/linux-app

**Comment by nyabinary** [comment]
> Same here, in addition their public repo is now archived https://github.com/ProtonVPN/linux-app
> 
> edit: but i've found this https://github.com/ProtonVPN/proton-vpn-gtk-app

the new protonvpn is already packaged in nixpkgs-unstable

**Comment by raspher** [comment]
@nyabinary i see package is outdated as latest version is [4.1.10](https://github.com/ProtonVPN/proton-vpn-gtk-app/tags) when in repo it's:
- unstable -> `4.1.0-unstable-2023-10-25`
- 23.11 -> `1.12.0` does not work at all as API probably changed

I wanted to update it but it's complicated a little, say not my level of understanding nix :)

**Comment by raspher** [comment]
When using unstable channel i can connect. However i'll fill an update request
![image](https://github.com/NixOS/nixpkgs/assets/23345803/183ddc88-f786-4517-af32-a670d2e47c0c)

**Comment by Kaukov** [comment]
When I used `nixos-23.11` as my base and only included `unstable` for `protonvpn-gui`, `networkmanager` (and its other packages), I couldn't connect to any server and I got unknown errors. My guess is I had missed another dependency I needed to pull from `unstable`.

When I set the URL to my `nixos` channel to `nixos-unstable`, I no longer face any issues with ProtonVPN and can successfully connect to the servers.

This issue is resolved for `nixos-unstable` 100%.

**Comment by MrFlacko** [comment]
I'm having some problems with base installat ion of protonvpn-gui as well.
Seems I cannot get wireguard protocol to work, have to change the protocol in the app settings to OpenVPN UDP

Once I do this it works but I'm unable to use the features of wireguard

```nix
{ config, pkgs, ... }:
{
  nixpkgs.config.allowUnfree = true;

  # Proton GUI talks to NetworkManager + systemd-resolved
  networking.networkmanager = {
    enable = true;
    dns = "systemd-resolved";
    plugins = [ 
      pkgs.networkmanager-openvpn 
    ];
  };
  services.resolved.enable = true;
  services.dbus.enable = true;

  # Disable reverse-path filtering – without this the tunnel
  # comes up, packets get dropped, the client reconnects forever.
  networking.firewall.checkReversePath = false;

  boot.kernel.sysctl = {
    "net.ipv4.conf.all.rp_filter" = 2;
    "net.ipv4.conf.default.rp_filter" = 2;
  };

  environment.systemPackages = with pkgs; [
    protonvpn-gui
    wireguard-tools
    iptables
    networkmanager-openvpn
  ];

  boot.kernelModules = [ "wireguard" ];

  programs.wireshark.enable = true;
  programs.wireshark.dumpcap.enable = true; 
  programs.wireshark.usbmon.enable  = false; 
}

**Comment by Naharie** [comment]
@MrFlacko's comment was very helpful. I had the same problem as it turns out. Forcing the use of systemd-resolved along side openvpn fixed it. I was already using network manager, so I made the following changes:
```nix
networking =
  networkmanager =
    dns = "systemd-resolved";
    plugins = [ 
      pkgs.networkmanager-openvpn 
    ];
  };
  firewall =
    checkReversePath = false;
  };
};

services.resolved.enable = true;

environment.systemPackages = with pkgs; [
  networkmanager-openvpn
];
```

Notably I never explicitly enabled either wireguard or openvpn before. It worked before 25.05, though, so something must have changed about what exactly the options I have set pull in.
