### ISSUE TITLE
keybase login fails: TypeError: pathcheck is not a function

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#12827]
`keybase login`

```
/nix/store/f1qzi3173l1dj6hdv7wnv082ix04w0jq-nodejs-keybase-0.8.22/lib/node_modules/keybase/lib/merkle_client.js:539
              pathcheck({
              ^

TypeError: pathcheck is not a function
    at iced.Deferrals.parent (/nix/store/f1qzi3173l1dj6hdv7wnv082ix04w0jq-nodejs-keybase-0.8.22/lib/node_modules/keybase/lib/merkle_client.js:539:15)
    at /nix/store/f1qzi3173l1dj6hdv7wnv082ix04w0jq-nodejs-keybase-0.8.22/lib/node_modules/keybase/lib/merkle_client.js:551:15
    at Deferrals.exports.Deferrals.Deferrals._call (/nix/store/hi5kb8c4i4j14fdb3awx8pfckddhk0cr-nodejs-iced-runtime-1.0.2/lib/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /nix/store/hi5kb8c4i4j14fdb3awx8pfckddhk0cr-nodejs-iced-runtime-1.0.2/lib/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/nix/store/hi5kb8c4i4j14fdb3awx8pfckddhk0cr-nodejs-iced-runtime-1.0.2/lib/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/nix/store/hi5kb8c4i4j14fdb3awx8pfckddhk0cr-nodejs-iced-runtime-1.0.2/lib/node_modules/iced-runtime/lib/runtime.js:96:16)
    at ret (/nix/store/hi5kb8c4i4j14fdb3awx8pfckddhk0cr-nodejs-iced-runtime-1.0.2/lib/node_modules/iced-runtime/lib/runtime.js:29:18)
    at /nix/store/853y5i9vdybw4dllm9lhzl912x1r2s7s-nodejs-iced-error-0.0.9/lib/node_modules/iced-error/index.js:92:22
    at /nix/store/f1qzi3173l1dj6hdv7wnv082ix04w0jq-nodejs-keybase-0.8.22/lib/node_modules/keybase/lib/merkle_client.js:440:26
    at Deferrals.exports.Deferrals.Deferrals._call (/nix/store/hi5kb8c4i4j14fdb3awx8pfckddhk0cr-nodejs-iced-runtime-1.0.2/lib/node_modules/iced-runtime/lib/runtime.js:86:16)
```

**Comment by tvon** [comment]
Same problem for me.  This was also reported upstream (from a NixOS user) here: https://github.com/keybase/node-client/issues/219
