### ISSUE TITLE
Home Assistant NixOS test fails

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#128327]
Why do we suddenly require `setuptools` at runtime? What introduced this issue?

## Issue description

```
hass # [  891.618448] hass[5753]: Traceback (most recent call last):
hass # [  891.619485] hass[5753]:   File "/nix/store/ds18n82xzh284rzgxqqi9l1m0vwwl9vv-homeassistant-2021.6.6/bin/.hass-wrapped", line 9, in <module>
hass # [  891.621981] hass[5753]:     sys.exit(main())
hass # [  891.623791] hass[5753]:   File "/nix/store/ds18n82xzh284rzgxqqi9l1m0vwwl9vv-homeassistant-2021.6.6/lib/python3.8/site-packages/homeassistant/__main__.py", line 280, in main
hass # [  891.630941] hass[5753]:     args = get_arguments()
hass # [  891.631851] hass[5753]:   File "/nix/store/ds18n82xzh284rzgxqqi9l1m0vwwl9vv-homeassistant-2021.6.6/lib/python3.8/site-packages/homeassistant/__main__.py", line 61, in get_arguments
hass # [  891.634996] hass[5753]:     import homeassistant.config as config_util
hass # [  891.636956] hass[5753]:   File "/nix/store/ds18n82xzh284rzgxqqi9l1m0vwwl9vv-homeassistant-2021.6.6/lib/python3.8/site-packages/homeassistant/config.py", line 18, in <module>
hass # [  891.643893] hass[5753]:     from homeassistant import auth
hass # [  891.644890] hass[5753]:   File "/nix/store/ds18n82xzh284rzgxqqi9l1m0vwwl9vv-homeassistant-2021.6.6/lib/python3.8/site-packages/homeassistant/auth/__init__.py", line 18, in <module>
hass # [  891.647130] hass[5753]:     from .mfa_modules import MultiFactorAuthModule, auth_mfa_module_from_config
hass # [  891.650974] hass[5753]:   File "/nix/store/ds18n82xzh284rzgxqqi9l1m0vwwl9vv-homeassistant-2021.6.6/lib/python3.8/site-packages/homeassistant/auth/mfa_modules/__init__.py", line 12, in <module>
hass # [  891.657887] hass[5753]:     from homeassistant import data_entry_flow, requirements
hass # [  891.659130] hass[5753]:   File "/nix/store/ds18n82xzh284rzgxqqi9l1m0vwwl9vv-homeassistant-2021.6.6/lib/python3.8/site-packages/homeassistant/requirements.py", line 13, in <module>
hass # [  891.661934] hass[5753]:     import homeassistant.util.package as pkg_util
hass # [  891.663902] hass[5753]:   File "/nix/store/ds18n82xzh284rzgxqqi9l1m0vwwl9vv-homeassistant-2021.6.6/lib/python3.8/site-packages/homeassistant/util/package.py", line 13, in <module>
hass # [  891.670966] hass[5753]:     import pkg_resources
hass # [  891.671849] hass[5753]: ModuleNotFoundError: No module named 'pkg_resources'
```

### Steps to reproduce

```
nix-build -A nixosTests.home-assistant
```

Assigning fabaff and dotlambda, because they are the most active contributors to home-assistant currently.

**Comment by dotlambda** [comment]
My guess is we always did but it was recently removed from some dependency's `propagatedBuildInputs`.

**Comment by mweinelt** [comment]
They don't mention it in their core requirements.txt though, annoying.

**Comment by dotlambda** [comment]
In 19581cb9619d58f76e10293b7a57aaf477db28d9, `setuptools` was removed from `python3Packages.jinja2`'s `propagatedBuildInputs`. So the solution is to add it to `home-assistant`'s because it is used in https://github.com/home-assistant/core/blob/2021.6.6/homeassistant/util/package.py#L13.
