### ISSUE TITLE
darcs-to-git fails to build

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#12870]
Context:  fresh `closure-size`.

```
these derivations will be built:
  /nix/store/ixcj2d2a4sx33v0v91hpdyiy0fzg106n-darcs-to-git-0.2git.drv
building path(s) ‘/nix/store/vy4g67wz6x65r8b94kg9ykiqb3g7p82r-darcs-to-git-0.2git’
unpacking sources
unpacking source archive /nix/store/0adwqf27pq9zq1mfk3hmc2ikacahbdc1-darcs-to-git-58a5593
source root is darcs-to-git-58a5593
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
running tests
Repository initialized.
Adding 'new_file1'
Finished recording patch 'c1'
Adding 'new_file2'
Finished recording patch 'c2'
Moved: new_file2 to: only_one_file
Finished recording patch 'c3'
/nix/store/86wnj7rhvyrnd993zc8kjz523hjwiipw-ruby-2.2.3-p0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- iconv (LoadError)
        from /nix/store/86wnj7rhvyrnd993zc8kjz523hjwiipw-ruby-2.2.3-p0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /tmp/nix-build-darcs-to-git-0.2git.drv-0/darcs-to-git-58a5593/darcs-to-git:32:in `<main>'
builder for ‘/nix/store/ixcj2d2a4sx33v0v91hpdyiy0fzg106n-darcs-to-git-0.2git.drv’ failed with exit code 1
```

**Comment by vcunat** [comment]
It seems like a problem in ruby, probably not locating the `iconv` program. It's now located on `${glibc.bin}/bin/iconv`.

**Comment by vcunat** [comment]
Reported against 16.03 as well.

**Comment by rasendubi** [comment]
Builds fine on nixpkgs-unstable (26a2392594ad432883f9af06951e7b4c5e108eac)

**Comment by deepfire** [comment]
@vcunat, has the fix been propagated to 16.03 -- can we close this?

**Comment by vcunat** [comment]
The error seems still the same on today's 16.03.

**Comment by rasendubi** [comment]
(triage) still an issue on 16.03.

If someone would point me to the actual fix, I could backport it.

**Comment by rasendubi** [comment]
With the release of 16.09, 16.03 is currently unmaintained. Given this fact and the fact we don't know which commit fixes the issue, I'm closing this.
