### ISSUE TITLE
home-assistant won't start

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#129425]
**Describe the bug**
On master, home-assistant can't start on a fresh install

**To Reproduce**

config is
```nix
{
  services.home-assistant.enable = true;
}
```

journal is
```
Jul 06 12:49:58 home-nixos systemd[1]: Started Home Assistant.
Jul 06 12:50:02 home-nixos hass[26317]: 2021-07-06 12:50:02 WARNING (MainThread) [homeassistant.bootstrap] Skipping pip installation of required modules. This may cause issues
Jul 06 12:50:03 home-nixos hass[26317]: 2021-07-06 12:50:03 ERROR (MainThread) [homeassistant.setup] Setup failed for recorder: Unable to import component: No module named 'sqlalchemy'
Jul 06 12:50:03 home-nixos hass[26317]: 2021-07-06 12:50:03 ERROR (MainThread) [homeassistant.setup] Error during setup of component http
Jul 06 12:50:03 home-nixos hass[26317]: Traceback (most recent call last):
Jul 06 12:50:03 home-nixos hass[26317]:   File "/nix/store/7adqcf54llbbv2ic04b7ylfncmbrvlgj-homeassistant-2021.6.6/lib/python3.8/site-packages/homeassistant/setup.py", line 248, in _async_setup_component
Jul 06 12:50:03 home-nixos hass[26317]:     result = await task
Jul 06 12:50:03 home-nixos hass[26317]:   File "/nix/store/7adqcf54llbbv2ic04b7ylfncmbrvlgj-homeassistant-2021.6.6/lib/python3.8/site-packages/homeassistant/components/http/__init__.py", line 162, in async_setup
Jul 06 12:50:03 home-nixos hass[26317]:     server = HomeAssistantHTTP(
Jul 06 12:50:03 home-nixos hass[26317]:   File "/nix/store/7adqcf54llbbv2ic04b7ylfncmbrvlgj-homeassistant-2021.6.6/lib/python3.8/site-packages/homeassistant/components/http/__init__.py", line 244, in __init__
Jul 06 12:50:03 home-nixos hass[26317]:     setup_cors(app, cors_origins)
Jul 06 12:50:03 home-nixos hass[26317]:   File "/nix/store/7adqcf54llbbv2ic04b7ylfncmbrvlgj-homeassistant-2021.6.6/lib/python3.8/site-packages/homeassistant/components/http/cors.py", line 35, in setup_cors
Jul 06 12:50:03 home-nixos hass[26317]:     import aiohttp_cors
Jul 06 12:50:03 home-nixos hass[26317]: ModuleNotFoundError: No module named 'aiohttp_cors'
Jul 06 12:50:03 home-nixos hass[26317]: 2021-07-06 12:50:03 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of system_log. Setup failed for dependencies: http
Jul 06 12:50:03 home-nixos hass[26317]: 2021-07-06 12:50:03 ERROR (MainThread) [homeassistant.setup] Setup failed for system_log: Could not set up all dependencies.
[... etc]
```

**Additional context**
I cleared /var/lib/hass to be sure

**Notify maintainers**

@fabaff 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.5, NixOS, 21.11pre300283.f930ea227ce (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(wmertens): `"home-manager, nixpkgs-20.09pre235456.127634e4af8"`
 - channels(root): `"nixos-21.11pre300226.20887e4bbfd, nixos-hardware, nixpkgs-21.11pre300283.f930ea227ce"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: home-assistant
# a list of nixos modules affected by the problem
module: home-assistant
```

**Comment by wmertens** [comment]
I downgraded to stable and I have the same problem

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.5, NixOS, 21.05.1268.21b696caf39 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(wmertens): `"home-manager, nixpkgs-21.11pre300283.f930ea227ce"`
 - channels(root): `"nixos-21.05.1268.21b696caf39, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by fabaff** [comment]
As far as I remember could this issue be caused by the absent of `default_config:`.

**Comment by mweinelt** [comment]
Indeed our onboarding situation is not ideal right now and configuring

```
{
  services.home-assistant.config = {
    default_config = {}
    met = {};
  };
}
```

is indeed the way to get started. Met is the default weather provider that is loaded unconditionally, but now defined as part of their manifests here:

https://github.com/home-assistant/core/blob/933e0161501ffc160fb9009baf0112eabbae17f7/homeassistant/components/onboarding/views.py#L163-L165

**Comment by bjornfor** [comment]
I'm hitting this on release-21.11. I don't want to opt-in to declarative config yet (ref. https://github.com/NixOS/nixpkgs/issues/129425#issuecomment-876447265), but it's good to know there's a workaround.

I tried fixing the out-of-the-box experience by adding missing deps. I got this far:

```patch
diff --git a/pkgs/servers/home-assistant/default.nix b/pkgs/servers/home-assistant/default.nix
index 695febd118c..a37aceb6d7a 100644
--- a/pkgs/servers/home-assistant/default.nix
+++ b/pkgs/servers/home-assistant/default.nix
@@ -233,6 +233,15 @@ in with py.pkgs; buildPythonApplication rec {
     yarl
     # Not in setup.py, but used in homeassistant/util/package.py
     setuptools
+    # Not in setup.py, but used by NixOS services.home-assistant.enable = true.
+    aiodiscover
+    aiohttp-cors
+    gtts
+    hass-nabucasa
+    ifaddr
+    mutagen
+    pillow
+    sqlalchemy
   ] ++ lib.optionals (pythonOlder "3.9") [
     backports-zoneinfo
   ] ++ componentBuildInputs ++ extraBuildInputs;
~
```

...but there's still something missing:

```
systemd[1]: Started Home Assistant.
hass[2292300]: 2021-12-22 16:08:59 WARNING (MainThread) [homeassistant.bootstrap] Skipping pip installation of required modules. This may cause issues
hass[2292300]: 2021-12-22 16:09:00 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //var/lib/hass/home-assistant_v2.db>
hass[2292300]: 2021-12-22 16:09:00 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=1 from 2021-12-22 14:30:16.118830)
hass[2292300]: 2021-12-22 16:09:01 ERROR (MainThread) [homeassistant.setup] Error during setup of component frontend
hass[2292300]: Traceback (most recent call last):
hass[2292300]:   File "/nix/store/znmpmnfvs3g0slmk4d5a62qrqzz1cjs4-homeassistant-2021.11.5/lib/python3.9/site-packages/homeassistant/setup.py", line 254, in _async_setup_component
hass[2292300]:     result = await task
hass[2292300]:   File "/nix/store/znmpmnfvs3g0slmk4d5a62qrqzz1cjs4-homeassistant-2021.11.5/lib/python3.9/site-packages/homeassistant/components/frontend/__init__.py", line 346, in async_set>
hass[2292300]:     root_path = _frontend_root(repo_path)
hass[2292300]:   File "/nix/store/znmpmnfvs3g0slmk4d5a62qrqzz1cjs4-homeassistant-2021.11.5/lib/python3.9/site-packages/homeassistant/components/frontend/__init__.py", line 321, in _frontend>
hass[2292300]:     import hass_frontend
hass[2292300]: ModuleNotFoundError: No module named 'hass_frontend'
```

A bit of context around that traceback:

```
315 def _frontend_root(dev_repo_path: str | None) -> pathlib.Path:
316     """Return root path to the frontend files."""
317     if dev_repo_path is not None:
318         return pathlib.Path(dev_repo_path) / "hass_frontend"
319     # Keep import here so that we can import frontend without installing reqs
320     # pylint: disable=import-outside-toplevel
321     import hass_frontend
322 
323     return cast(pathlib.Path, hass_frontend.where())
```

I'm guessing it shouldn't have tried to `import hass_frontend` but instead `return pathlib.Path(dev_repo_path) / "hass_frontend"` on line 318.

**Comment by bjornfor** [comment]
>You are missing the default_config component.

Yes, I saw the [workaround](https://github.com/NixOS/nixpkgs/issues/129425#issuecomment-876447265) you posted (thanks!). And https://nixos.wiki/wiki/Home_Assistant has roughly the same. But as I said, I wanted to try the default imperative config and started out with a minimal `services.home-assistant.enable = true` -- which is broken.

I think for this issue to be closed, we should either fix the default imperative configuration or inject a minimal working declarative config and forbid imperative config.

**Comment by Thesola10** [comment]
I think there should be an option to allow home-assistant's pip resolver to work -- on the podman install at least, it installs in HASS' data directory, so while stateful, it should work on NixOS.
Something like `services.home-assistant.resolveDependencies`

**Comment by dotlambda** [comment]
> I think there should be an option to allow home-assistant's pip resolver to work -- on the podman install at least, it installs in HASS' data directory, so while stateful, it should work on NixOS.

That's as easy as
```
services.home-assistant.package = pkgs.home-assistant.override {
  skipPip = false;
}
```

**Comment by Thesola10** [comment]
@dotlambda 
uh... it doesn't. It complains that `/bin/python3.10: No module named pip` even though I checked it's in the wrapper scripts

My test config:
```nix
{ pkgs, config, ... }:

{
  services.home-assistant =
    { enable = true;

      package = pkgs.home-assistant.override {
        skipPip = false;
        extraComponents =
          [ "default_config"
            "mqtt"
            "ipp"
          ];
        extraPackages = python3Packages: with python3Packages;
          [ pip ];
      };
      config.default_config = {};
      config.group = "!include groups.yaml";
      config.automation = "!include automations.yaml";
      config.script = "!include scripts.yaml";
      config.scene = "!include scenes.yaml";
    };
}
```

**Comment by mweinelt** [comment]
Can you post the complete traceback?

**Comment by mogorman** [comment]
```Apr 17 14:49:13 random hass[656596]: 2023-04-17 14:49:13.862 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package pyotp==2.8.0: /nix/store/fdqpyj613dr0v1l1lrzqhzay7sk4xg87-python3-3.10.10/bin/python3.10: No module named pip
Apr 17 14:49:13 random hass[656596]: 2023-04-17 14:49:13.916 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package pyotp==2.8.0: /nix/store/fdqpyj613dr0v1l1lrzqhzay7sk4xg87-python3-3.10.10/bin/python3.10: No module named pip
Apr 17 14:49:13 random hass[656596]: 2023-04-17 14:49:13.968 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package pyotp==2.8.0: /nix/store/fdqpyj613dr0v1l1lrzqhzay7sk4xg87-python3-3.10.10/bin/python3.10: No module named pip
Apr 17 14:49:14 random hass[656596]: 2023-04-17 14:49:14.069 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package PyQRCode==1.2.1: /nix/store/fdqpyj613dr0v1l1lrzqhzay7sk4xg87-python3-3.10.10/bin/python3.10: No module named pip
Apr 17 14:49:14 random hass[656596]: 2023-04-17 14:49:14.124 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package PyQRCode==1.2.1: /nix/store/fdqpyj613dr0v1l1lrzqhzay7sk4xg87-python3-3.10.10/bin/python3.10: No module named pip
Apr 17 14:49:14 random hass[656596]: 2023-04-17 14:49:14.180 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package PyQRCode==1.2.1: /nix/store/fdqpyj613dr0v1l1lrzqhzay7sk4xg87-python3-3.10.10/bin/python3.10: No module named pip
Apr 17 14:49:14 random hass[656596]: 2023-04-17 14:49:14.181 ERROR (MainThread) [homeassistant.bootstrap] Home Assistant core failed to initialize. Further initialization aborted
Apr 17 14:49:14 random hass[656596]: 2023-04-17 14:49:14.181 WARNING (MainThread) [homeassistant.bootstrap] Unable to set up core integrations. Activating safe mode
Apr 17 14:49:14 random hass[656596]: 2023-04-17 14:49:14.185 ERROR (MainThread) [homeassistant.bootstrap] Home Assistant core failed to initialize. Further initialization aborted



``` is the error I get with similar code

**Comment by mweinelt** [comment]
We do provide pip right here:

https://github.com/NixOS/nixpkgs/blob/6eceb07c28016ec50dd683fda94995702b67e855/pkgs/servers/home-assistant/default.nix#L405

Home Assistant uses `Popen` to call `python -m pip install --quiet $package` in `homeassistant/utli/package.py` in function `install_package`.

Would need investigation. But with all that said:

Not sure how this could work, given that the PYTHONPATH isn't writable, and even if it were, python packages with native code can never work unpatched on NixOS.

This affects packages like numpy or zeroconf.

**Comment by mogorman** [comment]
the hass systemd script never sets up a pythonpath
```
systemctl show --property=PYTHONPATH home-assistant.service 
```
it looks like it wraps everything instead. I take it that because of that the popen call will fail
