### ISSUE TITLE
sway: segfault when clicking link in Chromium

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nixpkgs#129636]
**Describe the bug**
There's a particular link that, when clicked in Chromium, crashes my sway session.

The same link opened in Firefox doesn't Crash sway.

I'm hesitant about sharing the specific link because it reveals some private details. Let me know if you need it, and I'll share it privately.

**To Reproduce**
1. Open Chromium
2. Click on `$LINK`
3. Watch sway crash

**Expected behavior**
No crash.

**Additional context**
- sway 1.6.1
- nixos-unstable
- no custom kernel config
- chromium: Version 91.0.4472.114 (Official Build) (64-bit)
- Thinkpad T450s with Intel GPU

This is the output of the core dump:

```
(gdb) bt
#0  0x00007fa4922b933a in raise () from /nix/store/wvgyhnd3rn6dhxzbr5r71gx2q9mhgshj-glibc-2.32-48/lib/libc.so.6
#1  0x00007fa4922a3523 in abort () from /nix/store/wvgyhnd3rn6dhxzbr5r71gx2q9mhgshj-glibc-2.32-48/lib/libc.so.6
#2  0x00007fa4922a341f in __assert_fail_base.cold.0 () from /nix/store/wvgyhnd3rn6dhxzbr5r71gx2q9mhgshj-glibc-2.32-48/lib/libc.so.6
#3  0x00007fa4922b1d92 in __assert_fail () from /nix/store/wvgyhnd3rn6dhxzbr5r71gx2q9mhgshj-glibc-2.32-48/lib/libc.so.6
#4  0x00007fa4924f0f21 in wlr_texture_from_pixels () from /nix/store/8fiwg9ylxgh9wxxrq7qvm94pljnjsxg6-wlroots-0.14.0/lib/libwlroots.so.9
#5  0x000000000044e385 in update_title_texture ()
#6  0x000000000044e7f6 in container_update_title_textures ()
#7  0x0000000000454c1c in view_update_title ()
#8  0x0000000000459622 in handle_set_title ()
#9  0x00007fa49253b43c in wlr_signal_emit_safe () from /nix/store/8fiwg9ylxgh9wxxrq7qvm94pljnjsxg6-wlroots-0.14.0/lib/libwlroots.so.9
#10 0x00007fa4925420e3 in read_surface_property () from /nix/store/8fiwg9ylxgh9wxxrq7qvm94pljnjsxg6-wlroots-0.14.0/lib/libwlroots.so.9
#11 0x00007fa492543390 in x11_event_handler () from /nix/store/8fiwg9ylxgh9wxxrq7qvm94pljnjsxg6-wlroots-0.14.0/lib/libwlroots.so.9
#12 0x00007fa49258e4a2 in wl_event_loop_dispatch () from /nix/store/s7g2zwjb44yi2vdykgplz2paqw6nfr4a-wayland-1.19.0/lib/libwayland-server.so.0
#13 0x00007fa49258c135 in wl_display_run () from /nix/store/s7g2zwjb44yi2vdykgplz2paqw6nfr4a-wayland-1.19.0/lib/libwayland-server.so.0
#14 0x000000000040fabd in main ()
```

**Notify maintainers**

**Metadata**

```
❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.47, NixOS, 21.11.20210706.00c86ad (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.05.650.eaba7870ffc"`
 - channels(asymmetric): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
  ```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by asymmetric** [comment]
Linking [this issue](https://github.com/NixOS/nixpkgs/issues/127413), although the coredump looks different.

**Comment by asymmetric** [comment]
Seems solved!
