### ISSUE TITLE
archivy fails to run

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#130460]
```
[milan@nixos-t14s:~]$ nix-shell -p archivy

[nix-shell:~]$ archivy init
Traceback (most recent call last):
  File "/nix/store/h12d4jkr5igry869a1pn0awck2wxcji3-archivy-1.4.0/bin/.archivy-wrapped", line 6, in <module>
    from archivy.cli import cli
  File "/nix/store/h12d4jkr5igry869a1pn0awck2wxcji3-archivy-1.4.0/lib/python3.8/site-packages/archivy/__init__.py", line 11, in <module>
    from archivy.api import api_bp
  File "/nix/store/h12d4jkr5igry869a1pn0awck2wxcji3-archivy-1.4.0/lib/python3.8/site-packages/archivy/api.py", line 8, in <module>
    from archivy.models import DataObj, User
  File "/nix/store/h12d4jkr5igry869a1pn0awck2wxcji3-archivy-1.4.0/lib/python3.8/site-packages/archivy/models.py", line 2, in <module>
    from pkg_resources import require
ModuleNotFoundError: No module named 'pkg_resources'
```

Looks like it is missing python3Packages.setuptools...

**Comment by prusnak** [comment]
works for me - please provide output from `nix-info`

**Comment by tex** [comment]
```
[milan@nixos-t14s:~]$ nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3.12, channels(root): "nixos-21.11pre302265.c6c4a3d45ab, nixos-hardware", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos

[milan@nixos-t14s:~]$ archivy
Traceback (most recent call last):
  File "/nix/store/h12d4jkr5igry869a1pn0awck2wxcji3-archivy-1.4.0/bin/.archivy-wrapped", line 6, in <module>
    from archivy.cli import cli
  File "/nix/store/h12d4jkr5igry869a1pn0awck2wxcji3-archivy-1.4.0/lib/python3.8/site-packages/archivy/__init__.py", line 11, in <module>
    from archivy.api import api_bp
  File "/nix/store/h12d4jkr5igry869a1pn0awck2wxcji3-archivy-1.4.0/lib/python3.8/site-packages/archivy/api.py", line 8, in <module>
    from archivy.models import DataObj, User
  File "/nix/store/h12d4jkr5igry869a1pn0awck2wxcji3-archivy-1.4.0/lib/python3.8/site-packages/archivy/models.py", line 2, in <module>
    from pkg_resources import require
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by mweinelt** [comment]
```diff
diff --git a/pkgs/applications/misc/archivy/default.nix b/pkgs/applications/misc/archivy/default.nix
index 0a89e4f4765..728081dd573 100644
--- a/pkgs/applications/misc/archivy/default.nix
+++ b/pkgs/applications/misc/archivy/default.nix
@@ -13,6 +13,7 @@
 , python-dotenv
 , python-frontmatter
 , requests
+, setuptools
 , tinydb
 , validators
 , werkzeug
@@ -57,6 +58,7 @@ buildPythonApplication rec {
     python-dotenv
     python-frontmatter
     requests
+    setuptools
     tinydb
     validators
     werkzeug
```

fixes that, but then you will be running into

```pytb
❯ ./result/bin/archivy
Traceback (most recent call last):
  File "/nix/store/x7xqy37dg1pagmflsn2hgaz054z89s7a-archivy-1.4.0/bin/.archivy-wrapped", line 6, in <module>
    from archivy.cli import cli
  File "/nix/store/x7xqy37dg1pagmflsn2hgaz054z89s7a-archivy-1.4.0/lib/python3.8/site-packages/archivy/__init__.py", line 89, in <module>
    app.jinja_options["extensions"].append("jinja2.ext.do")
KeyError: 'extensions'
```
@siraben

**Comment by siraben** [comment]
I have informed the author of archivy, @Uzay-G, and he's looking into it.

**Comment by Uzay-G** [comment]
This is because in https://github.com/NixOS/nixpkgs/blob/dadf56e3a6835f2cc8047e4ae8569b0343d53892/pkgs/applications/misc/archivy/default.nix#L44 the version requirements are loosened and an incompatible new version of flask is used to run archivy. Removing this change to the version constraints for flask would fix the problem.
