### ISSUE TITLE
zeronet does not start

### ISSUE THREAD

**Issue by N0lim** [NixOS/nixpkgs#130466]
### I added the package to /etc/nixos/configuration.nix

...
environment.systemPackages = with pkgs; [
                gutenprint hplip splix
                zeronet
                wget
                firefox chromium
                emacs leiningen git
                gimp
                libreoffice
                tdesktop
                gnunet
                obs-studio kdenlive ffmpeg mpv
                earlyoom
                clamav
        ];
...

### start zeronet

[n0lim@nixos-PC:~]$ zeronet

 `-` Starting ZeroNet...
ERROR:root:Unhandled exception: [Errno 30] Read-only file system: './data'
Traceback (most recent call last):
  File "/nix/store/zv13i0sj2g8slw7jwpdmsr4ksajv526x-zeronet-0.7.1/share/zeronet.py", line 16, in main
    import main
  File "/nix/store/zv13i0sj2g8slw7jwpdmsr4ksajv526x-zeronet-0.7.1/share/src/main.py", line 24, in <module>
    os.mkdir(config.data_dir)
OSError: [Errno 30] Read-only file system: './data'
Traceback (most recent call last):
  File "/nix/store/zv13i0sj2g8slw7jwpdmsr4ksajv526x-zeronet-0.7.1/share/zeronet.py", line 16, in main
    import main
  File "/nix/store/zv13i0sj2g8slw7jwpdmsr4ksajv526x-zeronet-0.7.1/share/src/main.py", line 24, in <module>
    os.mkdir(config.data_dir)
OSError: [Errno 30] Read-only file system: './data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/zv13i0sj2g8slw7jwpdmsr4ksajv526x-zeronet-0.7.1/share/zeronet.py", line 137, in <module>
    start()
  File "/nix/store/zv13i0sj2g8slw7jwpdmsr4ksajv526x-zeronet-0.7.1/share/zeronet.py", line 133, in start
    main()
  File "/nix/store/zv13i0sj2g8slw7jwpdmsr4ksajv526x-zeronet-0.7.1/share/zeronet.py", line 28, in main
    traceback.print_exc(file=open(error_log_path, "w"))
FileNotFoundError: [Errno 2] No such file or directory: './log/error.log'

Starting with sudo nothing changes (issuing the same error)

Starting with Application launcher, there is no reaction (absolutely, the system does not issue errors and does not launch the application)

**Notify maintainers**

@fgaz

**Comment by fgaz** [comment]
That is "normal": the default data directory is in the installation directory, which is of course read only. You can set it explicitly, or you could just enable the zeronet service, which takes care of everything, in your configuration.nix

**Comment by fgaz** [comment]
It's weird that there is a broken application launder though. I think we should just remove it. Patching the default directory is also an option, but I'm a bit against it especially since we have a working NixOS module. What do you think, @N0lim ?

**Comment by fgaz** [comment]
@veprbl eeh not really, the module itself works fine, it's the package that doesn't work on its own without a configuration. Neither does nginx though, so I'll probably just close this in a week or so unless @N0lim or someone else disagrees
