### ISSUE TITLE
Ferdi silently fails to connect to internal server

### ISSUE THREAD

**Issue by unode** [NixOS/nixpkgs#130509]
**Describe the bug**
Ferdi can run without a Login by connecting to a server running on the local machine.
This server is started when `ferdi` is launched.
The internal server listen address is displayed in the terminal.

```
Starting local server on port 45569
info: serving app on http://pluto:45569
```
On Ferdi startup, there are `Login` and `Use Ferdi without an Account` buttons.
**The bug:** Clicking the latter produces no result.
In fact, if we launch Ferdi, open the developer console by pressing `Alt+Ctrl+I` and press the `Use Ferdi without an Account` button, the console will display the following error:
```
instrument.ts:158 POST http://127.0.0.1:45569/v1/auth/login net::ERR_CONNECTION_REFUSED
```
which is puzzling, since we saw above that the internal server is listening on `http://pluto:45569`.

Pointing a browser to this address shows a message `Internal Ferdi Server`, pointing to `http://127.0.0.1:45569` results in `Unable to connect`.

Turns out that in NixOS `/etc/hosts` contains:
```
127.0.0.1 localhost
::1 localhost
127.0.0.2 pluto
```
and somehow the internal server ends up listening on 127.0.0.**2** while the Ferdi frontend tries to connect to 127.0.0.**1**. 

This issue is therefore both a question to other NixOS Ferdi users and a possible bug report.

I found this to be an issue both in NixOS 20.09 and 21.05.
Ferdi: `/nix/store/pvyzr7zjvd17xrjw089bqpp22xhnyg79-ferdi-5.6.0-beta.6`

Issue also reported to Ferdi at: https://github.com/getferdi/ferdi/issues/1253

**To Reproduce**
1. nix-env -iA ferdi
2. ferdi
3. *click `Use Ferdi without an Account`*

**Expected behavior**
After clicking `Use Ferdi without an Account` Ferdi should be able to successfully contact the internal server.

**Notify maintainers**
@davidtwco @Ma27

**Metadata**
```
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.196, NixOS, 21.05.git.913c5044147 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-20.09pre217261.a2e06fc3423"`
 - nixpkgs: `/var/nixpkgs-channels/nixos`
```

**Comment by Ma27** [comment]
Hmm, the fact that ferdi starts a "server" on one IP and tries to listen to it on another one sounds like an upstream bug to me tbh.

**Comment by unode** [comment]
> Hmm, the fact that ferdi starts a "server" on one IP and tries to listen to it on another one sounds like an upstream bug to me tbh.

I tend to agree but at the same time wonder if and how are people working around this in NixOS?

**Comment by unode** [comment]
The issue has now been addressed in https://github.com/getferdi/ferdi/issues/1253

However I'm currently getting a segfault when running ferdi, both the version in nixos-21.05 and the latest ferdi nightly (`5.6.1-nightly.16`).
Can someone reproduce the segfault? I haven't been able to diagnose what is causing it and how to workaround.

**Comment by Ma27** [comment]
Can you please give me a backtrace for it? (`sudo coredumpctl gdb`, then `bt`).

**Comment by unode** [comment]
There are no debug symbols so this is all I got.
```
           PID: 16998 (.ferdi-wrapped)
           UID: 1000 (unode)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Fri 2021-08-06 11:48:05 CEST (25s ago)
  Command Line: /nix/store/mdh3g7cncxlfvy1r12skq0wlv6w60rmq-ferdi-5.6.1-nightly.16/opt/Ferdi/.ferdi-wrapped
    Executable: /nix/store/mdh3g7cncxlfvy1r12skq0wlv6w60rmq-ferdi-5.6.1-nightly.16/opt/Ferdi/.ferdi-wrapped
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (unode)
       Boot ID: fff615de44644791b5f774f7c783c6ce
    Machine ID: 2239f2e799114f7fb0d295befa3b0102
      Hostname: pluto
       Storage: /var/lib/systemd/coredump/core.\x2eferdi-wrapped.1000.fff615de44644791b5f774f7c783c6ce.16998.1628243285000000.lz4
       Message: Process 16998 (.ferdi-wrapped) of user 1000 dumped core.

GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /nix/store/mdh3g7cncxlfvy1r12skq0wlv6w60rmq-ferdi-5.6.1-nightly.16/opt/Ferdi/.ferdi-wrapped...
(No debugging symbols found in /nix/store/mdh3g7cncxlfvy1r12skq0wlv6w60rmq-ferdi-5.6.1-nightly.16/opt/Ferdi/.ferdi-wrapped)

warning: Can't open file /dev/shm/.org.chromium.Chromium.zrWKWx (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.yuuJgw (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.x5LO5w (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.Vle6Aw (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.uZRtxt (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.CKGzNw (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.xJ2NIt (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.YTFGEw (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.Smlrix (deleted) during file-backed mapping note processing
[New LWP 16998]
[New LWP 17007]
[New LWP 17010]
[New LWP 17005]
[New LWP 17008]
[New LWP 17011]
[New LWP 17015]
[New LWP 17014]
[New LWP 17137]
[New LWP 17009]
[New LWP 17006]
[New LWP 17016]
[New LWP 17012]
[New LWP 17018]
[New LWP 17020]
[New LWP 17017]
[New LWP 17026]
[New LWP 17021]
[New LWP 17013]
[New LWP 17023]
[New LWP 17025]
[New LWP 17138]
[New LWP 17022]
[New LWP 17027]
[New LWP 16999]
[New LWP 17024]
[New LWP 17150]
[New LWP 17028]
[New LWP 17029]
[New LWP 17140]
[New LWP 17149]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libthread_db.so.1".
Core was generated by `/nix/store/mdh3g7cncxlfvy1r12skq0wlv'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc46432ac73 in gtk_tray_icon_manager_filter () from /nix/store/r21sjymv9yljmnbnjgqw5fackqhafbh2-gtk+3-3.24.27/lib/libgtk-3.so.0
[Current thread is 1 (Thread 0x7fc45fbccdc0 (LWP 16998))]
(gdb) bt
#0  0x00007fc46432ac73 in gtk_tray_icon_manager_filter () from /nix/store/r21sjymv9yljmnbnjgqw5fackqhafbh2-gtk+3-3.24.27/lib/libgtk-3.so.0
#1  0x00007fc463eaeacf in gdk_event_apply_filters () from /nix/store/r21sjymv9yljmnbnjgqw5fackqhafbh2-gtk+3-3.24.27/lib/libgdk-3.so.0
#2  0x00007fc463eaee02 in _gdk_x11_display_queue_events () from /nix/store/r21sjymv9yljmnbnjgqw5fackqhafbh2-gtk+3-3.24.27/lib/libgdk-3.so.0
#3  0x00007fc463e54660 in gdk_display_get_event () from /nix/store/r21sjymv9yljmnbnjgqw5fackqhafbh2-gtk+3-3.24.27/lib/libgdk-3.so.0
#4  0x00007fc463eaeb62 in gdk_event_source_dispatch () from /nix/store/r21sjymv9yljmnbnjgqw5fackqhafbh2-gtk+3-3.24.27/lib/libgdk-3.so.0
#5  0x00007fc464bf05ab in g_main_context_dispatch () from /nix/store/bdcrmljjppwlpqkllr4i86dpbclpz876-glib-2.68.2/lib/libglib-2.0.so.0
#6  0x00007fc464bf0858 in g_main_context_iterate.constprop () from /nix/store/bdcrmljjppwlpqkllr4i86dpbclpz876-glib-2.68.2/lib/libglib-2.0.so.0
#7  0x00007fc464bf090f in g_main_context_iteration () from /nix/store/bdcrmljjppwlpqkllr4i86dpbclpz876-glib-2.68.2/lib/libglib-2.0.so.0
#8  0x0000555c9fd8b041 in ?? ()
#9  0x0000000000000000 in ?? ()
```

**Comment by unode** [comment]
The nightly above was built with these changes:
```
  # version = "5.6.0-beta.6";
  version = "5.6.1-nightly.16";
  src = fetchurl {
    # url = "https://github.com/getferdi/ferdi/releases/download/v${version}/ferdi_${version}_amd64.deb";
    url = "https://github.com/getferdi/nightlies/releases/download/v${version}/ferdi_${version}_amd64.deb";
    # sha256 = "sha256-Q1HSAEVcaxFyOq7oWqa6AJJpsBKRxbsKb9ydyK/gH/A=";
    sha256 = "1sm4pal7yimgw37ycv33z6gyx8yrxj2fbgnx6vvwwpgig09rj7vp";
  }
```

**Comment by unode** [comment]
One of the backtraces had something a little more informative that gave some hints:
```
Using host libthread_db library "/nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libthread_db.so.1".
Core was generated by `/nix/store/mdh3g7cncxlfvy1r12skq0wlv'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  gtk_tray_icon_manager_filter (xevent=0x7ffed2b20990, event=0x186b7a3fc5d0, user_data=0x186b7ac00450) at ../gtk/deprecated/gtktrayicon-x11.c:725
725	../gtk/deprecated/gtktrayicon-x11.c: No such file or directory.
[Current thread is 1 (Thread 0x7efed3f61dc0 (LWP 7466))]
(gdb) bt
#0  gtk_tray_icon_manager_filter (xevent=0x7ffed2b20990, event=0x186b7a3fc5d0, user_data=0x186b7ac00450) at ../gtk/deprecated/gtktrayicon-x11.c:725
#1  0x00007efed8243acf in gdk_event_apply_filters (xevent=xevent@entry=0x7ffed2b20990, event=event@entry=0x186b7a3fc5d0, window=window@entry=0x0) at ../gdk/x11/gdkeventsource.c:79
#2  0x00007efed8243e02 in gdk_event_source_translate_event (xevent=0x7ffed2b20990, event_source=0x186b7a120300) at ../gdk/x11/gdkeventsource.c:198
#3  _gdk_x11_display_queue_events (display=0x186b7aa440e0) at ../gdk/x11/gdkeventsource.c:341
#4  0x00007efed81e9660 in gdk_display_get_event (display=display@entry=0x186b7aa440e0) at ../gdk/gdkdisplay.c:442
#5  0x00007efed8243b62 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ../gdk/x11/gdkeventsource.c:363
#6  0x00007efed8f855ab in g_main_context_dispatch () from /nix/store/bdcrmljjppwlpqkllr4i86dpbclpz876-glib-2.68.2/lib/libglib-2.0.so.0
#7  0x00007efed8f85858 in g_main_context_iterate.constprop () from /nix/store/bdcrmljjppwlpqkllr4i86dpbclpz876-glib-2.68.2/lib/libglib-2.0.so.0
#8  0x00007efed8f8590f in g_main_context_iteration () from /nix/store/bdcrmljjppwlpqkllr4i86dpbclpz876-glib-2.68.2/lib/libglib-2.0.so.0
#9  0x000055982a7d7041 in ?? ()
#10 0x0000000000000000 in ?? ()
```

I'm using i3 and polybar for icon taskbar. I killed polybar and was able to launch ferdi without a segfault.
I then restarted polybar and I can still launch ferdi.

However this is a bit strange since I rebooted the machine earlier this morning.
I'll keep running with it to see if I notice any change after which ferdi starts segfaulting again.

**Comment by unode** [comment]
Since the initial issue is now fixed and to avoid going off-topic I'll close this.
If the segfault reappears I'll open another issue so we can dig further into it.

Thanks for the help @Ma27
