### ISSUE TITLE
GNOME apps freezing and crashing

### ISSUE THREAD

**Issue by ratsclub** [NixOS/nixpkgs#130574]
**Describe the bug**
Every time I open a GNOME application such as `nautilus` or `gnome.pomodoro` it freezes and then crashes after a few seconds.

**To Reproduce**
1. Open `nautilus`/`gnome-pomodoro`
2. See it freezing
3. See it crashing a few seconds later

**Expected behavior**
The app should not freeze and crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/25647735/126078548-b446e5d0-f17f-4fb2-ba3f-e321f3355bff.png)

**Additional context**
Opening them with `sudo` works as expected.

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.12.15, NixOS, 21.05.20210717.b2f87e0 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.11pre295280.fa0326ce523"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
I have not encountered that. Could you get the stack trace by running `systemctl gdb` and `bt full` in there? (`environment.enableDebugInfo = true;` option or better https://github.com/edolstra/dwarffs to get debugging symbols would be useful too.)

**Comment by ratsclub** [comment]
I'm not sure how I should go about doing this. I opened nautilus and typed ``gdb nautilus `pidof nautilus` `` then I typed `bt full` inside `gdb`. Is this what I was supposed to do? This is the output:

```gdb
(gdb) bt full
#0  0x00007fd37b6b0329 in __GI___poll (fds=0x19c3d10, nfds=3, timeout=8108) at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = -516
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd37c8817ee in g_main_context_poll (priority=<optimized out>, n_fds=3, fds=0x19c3d10, timeout=<optimized out>, context=0x178eba0) at ../glib/gmain.c:4434
        ret = <optimized out>
        errsv = <optimized out>
        poll_func = 0x7fd37c890c80 <g_poll>
        poll_func = <optimized out>
        ret = <optimized out>
        errsv = <optimized out>
#2  g_main_context_iterate (context=context@entry=0x178eba0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4126
        max_priority = 2147483647
        timeout = 8108
        some_ready = <optimized out>
        nfds = 3
        allocated_nfds = <optimized out>
        fds = 0x19c3d10
        begin_time_nsec = 0
#3  0x00007fd37c88190f in g_main_context_iteration (context=context@entry=0x178eba0, may_block=may_block@entry=1) at ../glib/gmain.c:4196
        retval = <optimized out>
#4  0x00007fd37bc5fb95 in g_application_run (application=0x174f210, argc=1390422452, argv=<optimized out>) at ../gio/gapplication.c:2560
        arguments = 0x174deb0
        status = 0
        context = 0x178eba0
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#5  0x00000000004487a7 in main ()
No symbol table info available.
```

**Comment by ratsclub** [comment]
Well I erased my system and it started working. Might be something on my side...
