### ISSUE TITLE
LightTable console error

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#13067]
When I open the console in LightTable, this error is printed:

```
Error: ENOENT: no such file or directory, open '/nix/store/2fl3mgdh8k5pj2qgjjbc20z7bpqakg00-lighttable-0.8.1/share/LightTable/resources/app/user_compiled.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at c (file:///nix/store/2fl3mgdh8k5pj2qgjjbc20z7bpqakg00-lighttable-0.8.1/share/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:19310:91)
    at a (file:///nix/store/2fl3mgdh8k5pj2qgjjbc20z7bpqakg00-lighttable-0.8.1/share/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:19318:18)
    at Function.lt.objs.plugins.__BEH__load_js (file:///nix/store/2fl3mgdh8k5pj2qgjjbc20z7bpqakg00-lighttable-0.8.1/share/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:29948:33)
    at c (file:///nix/store/2fl3mgdh8k5pj2qgjjbc20z7bpqakg00-lighttable-0.8.1/share/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///nix/store/2fl3mgdh8k5pj2qgjjbc20z7bpqakg00-lighttable-0.8.1/share/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
```

It goes away after the first start and everything appears to be working nonetheless.

**Comment by zimbatm** [comment]
This needs some research to find out what `user_compiled.js` is used for in LightTable

**Comment by jgillich** [comment]
Another thing I noticed is that cutting (`Ctrl-X`) doesn't work.

**Comment by Profpatsch** [comment]
triage: still an issue?

**Comment by jgillich** [comment]
Closing because LightTable hasn't seen a release since 2016 and I can't imagine anyone's using it anymore. I'd suggest dropping the package.
