### ISSUE TITLE
Rendering issues with anki/anki-bin

### ISSUE THREAD

**Issue by vale981** [NixOS/nixpkgs#131063]
**Describe the bug**
In anki, most labels in the main window aren't rendered.
In anki-bin the label heights are wrong, and the card browser has black fringes / the click area of the buttons does not coincide with their labels.

**Screenshots**
![image](https://user-images.githubusercontent.com/4025991/126633846-b38d7b84-779f-4e02-ae3d-9dfc656c6f43.png)
![image](https://user-images.githubusercontent.com/4025991/126633884-6bffed73-9ae8-4c46-a6b8-1d05812a8e5f.png)

**Notify maintainers**

@atemu 
@oxij 
@Profpatsch 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.14-zen1, NixOS, 21.11pre303315.16105403bdd (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(root): `"nixos-21.11pre303315.16105403bdd, nixos-stable-20.03.3328.6d1a044fc9f, nixos-unstable-21.11pre301044.87807e64a5e"`
 - channels(hiro): `"nixos-21.11pre301044.87807e64a5e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by primeos** [comment]
This seems to be related to #131074. I see that `anki` has a dependency on `pyqtwebengine` so maybe this is already fixed by #131121 (not sure if there's a Hydra build to test yet)?

**Comment by vale981** [comment]
i've just tried it with the latest  master in a pure shell.

``` 
[hiro@Lobsang:~/src/nixpkgs]$ nix-shell --pure -p anki-bin -I nixpkgs=/home/hiro/src/nixpkgs/

[nix-shell:~/src/nixpkgs]$ anki
Traceback (most recent call last):
  File "anki/__init__.py", line 14, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runanki.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/dae/venv/lib/python3.8/site-packages/PyInstaller-4.0.dev0+g2886519-py3.8.egg/PyInstaller/loader/pyimod03_importers.py", line 625, in exec_module
  File "aqt/__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/dae/venv/lib/python3.8/site-packages/PyInstaller-4.0.dev0+g2886519-py3.8.egg/PyInstaller/loader/pyimod03_importers.py", line 625, in exec_module
  File "anki/__init__.py", line 16, in <module>
Exception: Anki requires a UTF-8 locale.
[5] Failed to execute script runanki
 ```

**Comment by vale981** [comment]
the issues persist

**Comment by vale981** [comment]
interestingly the issue disappeared yesterday and reappeared today. 
i'm still trying to find out what the problem is. 
is suspect bspwm...

**Comment by Atemu** [comment]
I'm running i3, so that should be a fairly similar environment. I don't often run anki any more sadly.

**Comment by vale981** [comment]
It seems to be resolved now :).
At least for me it works.
