### ISSUE TITLE
mill does not work without `--no-server`

### ISSUE THREAD

**Issue by lucc** [NixOS/nixpkgs#131790]
### Describe the bug
Running mill without the `--no-server` option results in an exception

### Steps To Reproduce
Steps to reproduce the behavior:  `nix-shell --pure -p mill --run "mill --version"`

On the other hand `nix-shell --pure -p mill --run "mill --no-server --version"` works fine.

The same is the case for other mill subcomands, without the no-server option I get a stack trace (see below) with the option I can compile and run my project with mill.

#### Question
Can I somehow start a minimal NixOS VM with mill installed to isolate it even more (than just `nix-shell --pure`)? 

### Expected behavior
I expect no exception but instead output similar to (obtained with --no-server):
```
Mill Build Tool version 0.9.9
Java version: 1.8.0_272, vendor: Oracle Corporation, runtime: /nix/store/6iybqxhfnyp8y76qxhy1kc1zx6r1in61-openjdk-8u272-b10-jre/lib/openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "Linux", version: 5.10.52, arch: amd64
```

### Additional context
This seems to be the case for some mill versions on my system. If I looked through my nix store and tested old version:
```
$ for mill in /nix/store/*mill*/bin/mill ; do echo $mill; $mill --version; done
/nix/store/1xgcd1lab8vdlzgxrl701pdllkas5dgf-mill-0.9.6/bin/mill
Exception in thread "main" java.lang.Exception: Reached max server processes limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:164)
	at mill.main.client.MillClientMain.main(MillClientMain.java:102)
/nix/store/2n95dcy7kpslbv33vrhhg1n9y6kfdlrc-mill-0.9.5/bin/mill
Exception in thread "main" java.lang.Exception: Reached max process limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:173)
	at mill.main.client.MillClientMain.main(MillClientMain.java:99)
/nix/store/2w14ffrk48qsw9rh1p863wjn1f4x83ca-mill-0.9.9/bin/mill
Exception in thread "main" java.lang.Exception: Reached max server processes limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:176)
	at mill.main.client.MillClientMain.main(MillClientMain.java:114)
/nix/store/36hzdbwiy2ymsz0hyvv4va8wzgwl7zy3-mill-0.9.6/bin/mill
Exception in thread "main" java.lang.Exception: Reached max server processes limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:164)
	at mill.main.client.MillClientMain.main(MillClientMain.java:102)
/nix/store/46gh3znkpqfl5wcy6wj7sszwhg2xqqgz-mill-0.9.8/bin/mill
Exception in thread "main" java.lang.Exception: Reached max server processes limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:176)
	at mill.main.client.MillClientMain.main(MillClientMain.java:114)
/nix/store/4p4yrqnz147hkxfk82wwwxx33c5rbk2d-mill-0.9.5/bin/mill
Exception in thread "main" java.lang.Exception: Reached max process limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:173)
	at mill.main.client.MillClientMain.main(MillClientMain.java:99)
/nix/store/6sx407i6fa43wi6ym58gciyy654lsn5d-mill-0.9.3/bin/mill
Exception in thread "main" java.lang.Exception: Reached max process limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:173)
	at mill.main.client.MillClientMain.main(MillClientMain.java:99)
/nix/store/8h4qhvm6j9hwgyzamzqjqljjgmvw5jq7-mill-0.9.6/bin/mill
Exception in thread "main" java.lang.Exception: Reached max server processes limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:164)
	at mill.main.client.MillClientMain.main(MillClientMain.java:102)
/nix/store/8y9xx95wdssvnisciqsrvv8rs9h3s324-mill-0.9.6/bin/mill
Mill Build Tool version 0.9.6
Java version: 1.8.0_272, vendor: Oracle Corporation, runtime: /nix/store/c0rqbvzy1jyi87g3gd33yvi1n47y557n-openjdk-8u272-b10-jre/lib/openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "Linux", version: 5.10.52, arch: amd64
/nix/store/9b8vvn63hc9cvfwnv746f75yz1y8y9b2-mill-0.9.9/bin/mill
Exception in thread "main" java.lang.Exception: Reached max server processes limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:176)
	at mill.main.client.MillClientMain.main(MillClientMain.java:114)
/nix/store/bw8whbj76b6pds269jvkxbh0rdhywwid-mill-0.9.3/bin/mill
Exception in thread "main" java.lang.Exception: Reached max process limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:173)
	at mill.main.client.MillClientMain.main(MillClientMain.java:99)
/nix/store/mj94dxmqyg1kddps5dfn1bg1zb0si447-mill-0.9.5/bin/mill
Exception in thread "main" java.lang.Exception: Reached max process limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:173)
	at mill.main.client.MillClientMain.main(MillClientMain.java:99)
/nix/store/pca4b05skfr63kqfcs3qvrkpjcqkbwyd-mill-0.9.3/bin/mill
Exception in thread "main" java.lang.Exception: Reached max process limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:173)
	at mill.main.client.MillClientMain.main(MillClientMain.java:99)
/nix/store/s4nxpzxp2jhxm50z2j6h7bc9lnr18hn1-mill-0.9.6/bin/mill
Exception in thread "main" java.lang.Exception: Reached max server processes limit: 0
	at mill.main.client.MillClientMain.main0(MillClientMain.java:164)
	at mill.main.client.MillClientMain.main(MillClientMain.java:102)
/nix/store/z58bvbrs46p93vyx6dhzsb6yah4bk8br-mill-0.9.6/bin/mill
Mill Build Tool version 0.9.6
Java version: 1.8.0_272, vendor: Oracle Corporation, runtime: /nix/store/yygyaglwk8grf8n1gz9cqxq1hxvamcky-openjdk-8u272-b10-jre/lib/openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "Linux", version: 5.10.52, arch: amd64
```

### Notify maintainers
@scalavision 

### Metadata
I am using NixOS unstable with flakes.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.11.20210727.8ecc61c (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(root): `"nixos-21.11pre296557.33d42ad7cf2"`
 - channels(luc): `""`
 - nixpkgs: `/nix/store/svybjwf9ab3iqiz8zwwqwbqzksl3gx8v-source`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by lucc** [comment]
Never mind, it was a problem with a stale `out/` folder in my project. I deleted that and now (current) mill works fine without the `--no-server` option.

Sorry for the noise.
