### ISSUE TITLE
cocoa pods not working

### ISSUE THREAD

**Issue by Kloenk** [NixOS/nixpkgs#132049]
### Describe the bug
Cocoapods is unable to load the Packaged Gemfile.lock

### Steps To Reproduce
1. install current cocoapods or cocoapods-beta
2. run pod
3. se it fail

### Expected behavior
`pod` should work

### Traceback
~~~
Traceback (most recent call last):
	3: from /nix/store/5mwa347n7p5kpxzlq6i25yzy3kr0qj4a-cocoapods-1.10.1/bin/pod:18:in `<main>'
	2: from /nix/store/4hklfzkfa9hcd7dbwc5wrfvll8dn9kkw-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler.rb:149:in `setup'
	1: from /nix/store/4hklfzkfa9hcd7dbwc5wrfvll8dn9kkw-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/runtime.rb:13:in `setup'
/nix/store/4hklfzkfa9hcd7dbwc5wrfvll8dn9kkw-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:439:in `ensure_equivalent_gemfile_and_lockfile': You are trying to install in deployment mode after changing (Bundler::ProductionError)
your Gemfile. Run `bundle install` elsewhere and add the
updated ../../nix/store/53ipw64azfnag9qc9s8xq7dil7064f4w-gemfile-and-lockfile/Gemfile.lock to version control.

If this is a development machine, remove the /nix/store/53ipw64azfnag9qc9s8xq7dil7064f4w-gemfile-and-lockfile/Gemfile freeze
by running `bundle config unset frozen`.

The list of sources changed

You have added to the Gemfile:
* source: locally installed gems
~~~
### Additional context
I'm using an m1 Mac. I also build `legacyPackages.x86_64-darwin.cocoapods` same error there.

Via git bisect I managed to find it the bad commit is somewhere between `8f71a7f33524bf3cdb2bd4df0ab0cf7a29a3115e` and `9655bb9a69954515bdc5e18dee4a04a713c6da86`. I could not test any further, as this contains a staging merge, and wanted do build +140 packages.

### Notify maintainers
@peterromfeldhk, @lilyball

### Metadata
```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
 - system: `0`
 - host os: `Darwin 20.6.0, macOS 11.5`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210525_dirty`
 - channels(kloenk): `""`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
    - cocoapods
    - cocoapods-beta
# a list of nixos modules affected by the problem
module:
```

**Comment by Kloenk** [comment]
@winterqt Thanks, it's fixed. But it seems incredible slow on my m1 Mac.
