### ISSUE TITLE
NixOS 21.05: buildPythonApplication import conflict when two applications are built using different interpreter versions and same named dependencies

### ISSUE THREAD

**Issue by rzetterberg** [NixOS/nixpkgs#132761]
### Describe the bug

I have created an [MWE](https://github.com/NixOS/nixpkgs/files/6937558/buildPythonApplication.zip) with two dummy applications (they only import `numpy` and print a message when run) that I build with the following inputs:

```nix
  new_app = pkgs.callPackage ./new_app/default.nix {
    inherit (pkgs);
    inherit (pkgs.python3Packages) buildPythonApplication numpy;
  };

  old_app = pkgs.callPackage ./old_app/default.nix {
    inherit (pkgs);
    inherit (pkgs.python2Packages) buildPythonApplication numpy setuptools;
  };
```

`new_app/default.nix`:
```nix
{ buildPythonApplication, numpy }:

buildPythonApplication {
  pname   = "new_app";
  version = "1.0.0";
  src     = ./.;

  doCheck = false;

  propagatedBuildInputs = [numpy];
}
```

`old_app/default.nix`:
```nix
{ buildPythonApplication, numpy, setuptools }:

buildPythonApplication {
  pname   = "old_app";
  version = "1.0.0";
  src     = ./.;

  nativeBuildInputs = [setuptools];

  doCheck = false;

  propagatedBuildInputs = [numpy];
}
```

When I supply these two applications as `buildInputs` to a package that I create a `nix-shell` from and run them, I get the following error due to `new_app` trying to use `numpy` from `python2.7`:

```bash
$ old_app.py
>> Old app main

$ new_app.py
Traceback (most recent call last):
  File "/nix/store/ab2w199fgr4zaa668knd81zwl6bm2yjd-python2.7-numpy-1.16.6/lib/python2.7/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/nix/store/ab2w199fgr4zaa668knd81zwl6bm2yjd-python2.7-numpy-1.16.6/lib/python2.7/site-packages/numpy/core/multiarray.py", line 13, in <module>
    from . import overrides
  File "/nix/store/ab2w199fgr4zaa668knd81zwl6bm2yjd-python2.7-numpy-1.16.6/lib/python2.7/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dynamic module does not define module export function (PyInit__multiarray_umath)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/sg9hssj0mqb9q7fssfdjj4sp9b4v35kf-new_app-1.0.0/bin/.new_app.py-wrapped", line 4, in <module>
    import numpy
  File "/nix/store/ab2w199fgr4zaa668knd81zwl6bm2yjd-python2.7-numpy-1.16.6/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/nix/store/ab2w199fgr4zaa668knd81zwl6bm2yjd-python2.7-numpy-1.16.6/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
```

- I get the same error with and without the `--pure` for `nix-shell`
- I get the same error when using the applications in a phase of my downstream package that is built using `nix-build`

### Steps To Reproduce

1. Download [the zip-file containing the MWE](https://github.com/NixOS/nixpkgs/files/6937558/buildPythonApplication.zip)
2. Extract the zip-file
3. Run `nix-build default.nix`
4. See the error unfold

### Expected behavior

When I run these apps I should get the following output:

```bash
$ old_app.py
>> Old app main

$ new_app.py
>> New app main
```

### Additional context

`old_app.py` contents:
```bash
$ cat $(which old_app.py)
#! /nix/store/xvvgw9sb8wk6d2c0j3ybn7sll67s3s4z-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/4prbf2c5ya287bp8gyi1n7bi4r413bzs-python-2.7.18/bin:/nix/store/i3yi7b9xmc7jp06afcc5fdq8hxf9b02c-old_app-1.0.0/bin:/nix/store/ab2w199fgr4zaa668knd81zwl6bm2yjd-python2.7-numpy-1.16.6/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/i3yi7b9xmc7jp06afcc5fdq8hxf9b02c-old_app-1.0.0/bin/.old_app.py-wrapped"  "$@"
```

`.old_app.py-wrapped` contents:
```bash
$ cat $(dirname $(which old_app.py))/.old_app.py-wrapped
#!/nix/store/4prbf2c5ya287bp8gyi1n7bi4r413bzs-python-2.7.18/bin/python2.7

import sys;import site;import functools;sys.argv[0] = '/nix/store/i3yi7b9xmc7jp06afcc5fdq8hxf9b02c-old_app-1.0.0/bin/old_app.py';functools.reduce(lambda k, p: site.addsitedir(p, k), ['/nix/store/i3yi7b9xmc7jp06afcc5fdq8hxf9b02c-old_app-1.0.0/lib/python2.7/site-packages','/nix/store/ab2w199fgr4zaa668knd81zwl6bm2yjd-python2.7-numpy-1.16.6/lib/python2.7/site-packages'], site._init_pathinfo());
import numpy

#-------------------------------------------------------------------------------

if __name__ == '__main__':
    print('>> Old app main')
```

`new_app.py` contents:
```bash
$ cat $(which new_app.py)
#! /nix/store/xvvgw9sb8wk6d2c0j3ybn7sll67s3s4z-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/zv167zw7gwr9h0gpkfcikdfqnscrd0q6-python3-3.8.9/bin:/nix/store/sg9hssj0mqb9q7fssfdjj4sp9b4v35kf-new_app-1.0.0/bin:/nix/store/ys7ffnghl2iaza8ly4mjpycfyargxv4z-python3.8-numpy-1.20.2/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/sg9hssj0mqb9q7fssfdjj4sp9b4v35kf-new_app-1.0.0/bin/.new_app.py-wrapped"  "$@"
```

`.new_app.py-wrapped` contents:
```bash
$ cat $(dirname $(which new_app.py))/.new_app.py-wrapped
#!/nix/store/zv167zw7gwr9h0gpkfcikdfqnscrd0q6-python3-3.8.9/bin/python3.8

import sys;import site;import functools;sys.argv[0] = '/nix/store/sg9hssj0mqb9q7fssfdjj4sp9b4v35kf-new_app-1.0.0/bin/new_app.py';functools.reduce(lambda k, p: site.addsitedir(p, k), ['/nix/store/sg9hssj0mqb9q7fssfdjj4sp9b4v35kf-new_app-1.0.0/lib/python3.8/site-packages','/nix/store/ys7ffnghl2iaza8ly4mjpycfyargxv4z-python3.8-numpy-1.20.2/lib/python3.8/site-packages'], site._init_pathinfo());
import numpy

#-------------------------------------------------------------------------------

if __name__ == '__main__':
    print('>> New app main')
```

`PYTHONPATH` contents:
```bash
$ echo $PYTHONPATH | tr ':' '\n'
/nix/store/i3yi7b9xmc7jp06afcc5fdq8hxf9b02c-old_app-1.0.0/lib/python2.7/site-packages
/nix/store/ab2w199fgr4zaa668knd81zwl6bm2yjd-python2.7-numpy-1.16.6/lib/python2.7/site-packages
/nix/store/4prbf2c5ya287bp8gyi1n7bi4r413bzs-python-2.7.18/lib/python2.7/site-packages
``` 

It seems that the outputs are wrapped correctly and that the problem comes from `PYTHONPATH` containing paths to the `python2.7` packages that are used in `old_app`. 

### Notify maintainers

@FRidh 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.1987.16bf3980bfa (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(root): `"nixos-21.05.1987.16bf3980bfa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FRidh** [comment]
There is no separate `PYTHONPATH` for the different interpreters and `buildPythonPackage` propagates inputs. Propagation of inputs is what we need to get rid off. https://github.com/NixOS/nixpkgs/pull/102613

**Comment by rzetterberg** [comment]
Thanks for the quick response! :+1: 

What is your advice for me to solve the problem I'm having? Wait for that PR to land or can I employ some workaround in the meantime? 

The only solution/workaround I can come up on spontaneously is to overwrite `PYTHONPATH` in the executable wrapper to only include paths to the packages that were given inside `propagatedBuildInputs`.

**Comment by FRidh** [comment]
In the derivation where you use these two *applications* as `buildInputs` and which you `nix-shell` on, you can unset `PYTHONPATH` in e.g. the `preBuild`.

**Comment by rzetterberg** [comment]
Works like a charm! Thanks a bunch for the help :1st_place_medal:
