### ISSUE TITLE
vscode-extensions.matklad.rust-analyzer: Extension fails to activate

### ISSUE THREAD

**Issue by winterqt** [NixOS/nixpkgs#132938]
### Describe the bug

The extension fails to activate.

### Steps To Reproduce
1. Install the extension via home-manager
2. Attempt to activate it by opening VS Code to a Rust project

### Expected behavior
For the extension to activate successfully.

### Additional context
Logs:
```
[2021-08-06 16:59:01.070] [exthost] [error] Activating extension matklad.rust-analyzer failed due to an error:
[2021-08-06 16:59:01.070] [exthost] [error] TypeError: Cannot destructure property 'ANY' of 'require$$26' as it is undefined.
	at Object.<anonymous> (/nix/store/59nk7z6h9gfcqqjv0kiajns9j4pwn173-vscode-extension-rust-analyzer-2021-08-02/share/vscode/extensions/matklad.rust-analyzer/out/src/main.js:2378:13)
	at Module.u._compile (/nix/store/d81pjajpc0xcplx7ch921lrw4s8v37g1-vscode-1.58.2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.i._load (/nix/store/d81pjajpc0xcplx7ch921lrw4s8v37g1-vscode-1.58.2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27843)
	at Function.b._load (/nix/store/d81pjajpc0xcplx7ch921lrw4s8v37g1-vscode-1.58.2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24471)
	at Function.l._load (/nix/store/d81pjajpc0xcplx7ch921lrw4s8v37g1-vscode-1.58.2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59004)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/nix/store/d81pjajpc0xcplx7ch921lrw4s8v37g1-vscode-1.58.2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
	at u._loadCommonJSModule (/nix/store/d81pjajpc0xcplx7ch921lrw4s8v37g1-vscode-1.58.2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:25877)
	at u._doActivateExtension (/nix/store/d81pjajpc0xcplx7ch921lrw4s8v37g1-vscode-1.58.2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12556)
	at u._activateExtension (/nix/store/d81pjajpc0xcplx7ch921lrw4s8v37g1-vscode-1.58.2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11657)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
```

### Notify maintainers

@oxalica

### Metadata

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 20.6.0, macOS 11.5.1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(winter): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/a0wni8bqlfwqr67qjwg0yhlfwg2nlq4r-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: vscode-extensions.matklad.rust-analyzer
# a list of nixos modules affected by the problem
module:
```

**Comment by winterqt** [comment]
Note: rolling back to https://github.com/NixOS/nixpkgs/commit/1454412796de471d1826154344c18178a44288bb#diff-95ca71480a98f51984b63d5ea3b588211290c1b3d96af0fbda2a7363c1aff0a7 fixes the issue.

**Comment by yaymukund** [comment]
Hello, I've been looking at this since yesterday. I *think* we need to pin rollup to 2.51 to avoid https://github.com/rollup/rollup/issues/4195 / https://github.com/npm/node-semver/issues/318 - I am presently regenerating node-packages.nix to test this fix.

I think you are right that my 08-02 update introduced the regression. I apologize, can cut a revert PR later today if my fix doesn't work and if that would be desirable.
