### ISSUE TITLE
pythonImportsCheck fails to detect missing runtime setuptools dependency

### ISSUE THREAD

**Issue by bcdarwin** [NixOS/nixpkgs#133032]
### Describe the bug

If a package import setuptools at runtime and setuptools is not provided in `propagatedBuildInputs`, the package will of course fail at runtime unless `setuptools` is otherwise propagated.  We expect `pythonImportsCheck` to detect this, but it does not, presumably because setuptools is available as part of the build environment in which the imports check is run.

For instance, see [this thread](https://github.com/NixOS/nixpkgs/pull/132919#discussion_r684530109) as part of #132919.

### Steps To Reproduce

On a branch on which #132919 has not been applied, observe the following behaviour regardless of whether `pythonImportsCheck = [ "envisage.api" ];` is added to the `python3Packages.envisage` expression (in particular note that building the package succeeds in both cases):

```
$ nix-shell -p 'python3.withPackages (ps: with ps; [ envisage ])' --command 'python3 -c "import envisage.api"'
 ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/vn0jw817b278ycjq8vy53bnvcv7cqhq5-python3-3.9.6-env/lib/python3.9/site-packages/envisage/api.py", line 71, in <module>
    from .egg_plugin_manager import EggPluginManager
  File "/nix/store/vn0jw817b278ycjq8vy53bnvcv7cqhq5-python3-3.9.6-env/lib/python3.9/site-packages/envisage/egg_plugin_manager.py", line 18, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by SuperSandro2000** [comment]
I think it gets impurely added by https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/mk-python-derivation.nix#L124. Either we remove it from https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/catch_conflicts/catch_conflicts.py#L9 or we find a way to remove it from the imports hook

**Comment by kevincox** [comment]
This also affects `google-cloud-kms`.

**Comment by SFrijters** [comment]
This is extra confusing because https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#using-pythonimportscheck-using-pythonimportscheck= explicitly states 

"This can also be useful in verifying that the package doesn't assume commonly present packages (e.g. `setuptools`)"

**Comment by SuperSandro2000** [comment]
I think we could work around this by moving the setuptools package to the one hook that needs it.
