### ISSUE TITLE
Unable to use platformio for zephyr framework builds

### ISSUE THREAD

**Issue by j-hui** [NixOS/nixpkgs#133185]
### Describe the bug
I'm unable to build Zephyr-based projects with platformio, because it sets up its own virtual environment and installs packages using `pip`. This doesn't work on NixOS.

### Steps To Reproduce
1. Install `platformio`
2. Setup Zephyr project with `pio project init --board nrf52840_dk --project-option "framework=zephyr"`
3. `pio run`

I encounter this error:

```console
$ pio run
Processing nrf52840_dk (platform: nordicnrf52; board: nrf52840_dk; framework: zephyr)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/nordicnrf52/nrf52840_dk.html
PLATFORM: Nordic nRF52 (8.1.0) > Nordic nRF52840-DK
HARDWARE: NRF52840 64MHz, 256KB RAM, 1MB Flash
DEBUG: Current (jlink) On-board (cmsis-dap, jlink) External (blackmagic, stlink)
PACKAGES:
 - framework-zephyr 2.20500.210226 (2.5.0)
 - framework-zephyr-canopennode 0.0.0-alpha+sha.468d350028
 - framework-zephyr-civetweb 0.0.0-alpha+sha.e6903b80c0
 - framework-zephyr-cmsis 0.0.0-alpha+sha.c3bd2094f9
 - framework-zephyr-fatfs 0.0.0-alpha+sha.1d1fcc725a
 - framework-zephyr-hal-nordic 0.0.0-alpha+sha.f0d54d8449
 - framework-zephyr-hal-st 0.0.0-alpha+sha.b52fdbf4b6
 - framework-zephyr-libmetal 0.0.0-alpha+sha.9d4ee2c3cf
 - framework-zephyr-littlefs 0.0.0-alpha+sha.9e4498d1c7
 - framework-zephyr-loramac-node 0.0.0-alpha+sha.3f545d76a2
 - framework-zephyr-lvgl 0.0.0-alpha+sha.31acbaa36e
 - framework-zephyr-mbedtls 0.0.0-alpha+sha.24d84ecff1
 - framework-zephyr-mcuboot 0.0.0-alpha+sha.3fc59410b6
 - framework-zephyr-mcumgr 0.0.0-alpha+sha.43845e883f
 - framework-zephyr-mipi-sys-t 0.0.0-alpha+sha.75e671550a
 - framework-zephyr-open-amp 0.0.0-alpha+sha.de1b85a130
 - framework-zephyr-openthread 0.0.0-alpha+sha.1d668284a0
 - framework-zephyr-segger 0.0.0-alpha+sha.38c79a447e
 - framework-zephyr-sof 0.0.0-alpha+sha.b5b772dd61
 - framework-zephyr-tfm-mcuboot 1.7.0-rc1
 - framework-zephyr-tinycbor 0.0.0-alpha+sha.40daca97b4
 - framework-zephyr-tinycrypt 0.0.0-alpha+sha.3e9a49d267
 - framework-zephyr-trusted-firmware-m 0.0.0-alpha+sha.96340fb6c0
 - tool-cmake 3.16.4
 - tool-dtc 1.4.7
 - tool-gperf 3.0.4
 - tool-ninja 1.7.1
 - tool-sreccat 1.164.0 (1.64)
 - toolchain-gccarmnoneeabi 1.80201.181220 (8.2.1)
Installing Zephyr's Python dependencies
/nix/store/yqjhkdarf7p74wcha7aypzsb751n7wl2-python3-3.9.5/bin/python3.9: No module named pip
*** Error 1
Reading CMake configuration...
-- Application: /home/j-hui/scratch/pio-proj/zephyr
-- Zephyr version: 2.5.0 (/home/j-hui/.platformio/packages/framework-zephyr)
-- Found Python3: /nix/store/yqjhkdarf7p74wcha7aypzsb751n7wl2-python3-3.9.5/bin/python3.9 (found suitable exact version "3.9.5") found components: Interpreter
-- Configuring incomplete, errors occurred!

CMake Error at /home/j-hui/.platformio/packages/framework-zephyr/cmake/zephyr_module.cmake:61 (message):
  Traceback (most recent call last):

    File "/home/j-hui/.platformio/packages/framework-zephyr/scripts/zephyr_module.py", line 25, in <module>
      import pykwalify.core

  ModuleNotFoundError: No module named 'pykwalify'

Call Stack (most recent call first):
  /home/j-hui/.platformio/packages/framework-zephyr/cmake/app/boilerplate.cmake:183 (include)
  CMakeLists.txt:2 (include)
```

### Expected behavior
It should install the `framework-zephyr` package, before proceeding to build the package and the project.

### Notify maintainers
@mogorman 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.1669.973910f5c31 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(root): `"nixos-21.05.1669.973910f5c31, nixpkgs-unstable-21.11pre304227.ecaf3da9340"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by acowley** [comment]
I think I am seeing the same error trying to use an `esp32-c3-devkitm-1` board.

```
Processing esp32-c3-devkitm-1 (platform: espressif32; board: esp32-c3-devkitm-1; framework: espidf)
--------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option                                                        
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-c3-devkitm-1.html                    
PLATFORM: Espressif 32 (3.3.2) > Espressif ESP32-C3-DevKitM-1                                                 
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash                                                                
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)                                                    
PACKAGES:                                                                                                     
 - framework-espidf 3.40300.0 (4.3.0)                                                                         
 - tool-cmake 3.16.4                                                                                          
 - tool-esptoolpy 1.30100.210531 (3.1.0)                                                                      
 - tool-ninja 1.7.1                                                                                           
 - toolchain-riscv-esp 1.80400.0 (8.4.0)                                                                      
/nix/store/1g54cwl6m78rgrqsnn1pp29dbvldpvsd-python3-3.9.6/bin/python3.9: No module named pip                  
CalledProcessError: Command '['/nix/store/1g54cwl6m78rgrqsnn1pp29dbvldpvsd-python3-3.9.6/bin/python3.9', '-m', 'pip', 'list', '--format=json']' returned non-zero exit status 1.:                                           
  File "/nix/store/60wpsxpdbj5i2cpqn2wdppia0r6azw2i-platformio-5.1.1/lib/python3.9/site-packages/platformio/builder/main.py", line 177:                                                                                     
    env.SConscript("$BUILD_SCRIPT")                                                                           
  File "/home/acowley/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Script/SConscript.py", line 591:
    return _SConscript(self.fs, *files, **subst_kw)                                                           
  File "/home/acowley/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Script/SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)                                     
  File "/home/acowley/.platformio/platforms/espressif32/builder/main.py", line 218:                           
    target_elf = env.BuildProgram()                                                                           
  File "/home/acowley/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Util.py", line 658:             
    return self.method(*nargs, **kwargs)                                                                      
  File "/nix/store/60wpsxpdbj5i2cpqn2wdppia0r6azw2i-platformio-5.1.1/lib/python3.9/site-packages/platformio/builder/tools/platformio.py", line 61:                                                                          
    env.ProcessProgramDeps()                                                                                  
  File "/home/acowley/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Util.py", line 658:             
    return self.method(*nargs, **kwargs)                                                                      
  File "/nix/store/60wpsxpdbj5i2cpqn2wdppia0r6azw2i-platformio-5.1.1/lib/python3.9/site-packages/platformio/builder/tools/platformio.py", line 127:                                                                         
    env.BuildFrameworks(env.get("PIOFRAMEWORK"))                                                              
  File "/home/acowley/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Util.py", line 658:             
    return self.method(*nargs, **kwargs)                                                                      
  File "/nix/store/60wpsxpdbj5i2cpqn2wdppia0r6azw2i-platformio-5.1.1/lib/python3.9/site-packages/platformio/builder/tools/platformio.py", line 342:
    SConscript(env.GetFrameworkScript(f), exports="env")
  File "/home/acowley/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Script/SConscript.py", line 654:
    return method(*args, **kw)
  File "/home/acowley/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Script/SConscript.py", line 591:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/acowley/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Script/SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/acowley/.platformio/platforms/espressif32/builder/frameworks/espidf.py", line 1045:
    install_python_deps()
  File "/home/acowley/.platformio/platforms/espressif32/builder/frameworks/espidf.py", line 1006:
    installed_packages = _get_installed_pip_packages()
  File "/home/acowley/.platformio/platforms/espressif32/builder/frameworks/espidf.py", line 986:
    pip_output = subprocess.check_output(
  File "/nix/store/1g54cwl6m78rgrqsnn1pp29dbvldpvsd-python3-3.9.6/lib/python3.9/subprocess.py", line 424:
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/1g54cwl6m78rgrqsnn1pp29dbvldpvsd-python3-3.9.6/lib/python3.9/subprocess.py", line 528:
    raise CalledProcessError(retcode, process.args,
========================================= [FAILED] Took 1.08 seconds =========================================
```

**Comment by mweinelt** [comment]
@Mindavi Try adding pykwalify to dependencies after https://github.com/NixOS/nixpkgs/pull/422153.
