### ISSUE TITLE
Calibre does not find jeepney Python module

### ISSUE THREAD

**Issue by dschrempf** [NixOS/nixpkgs#133595]
### Describe the bug
Start calibre, try to send a file to a device. A popup shows up stating that the module `jeepney` cannot be found.

I read something about `jeepney` replacing `python-dbus` on https://calibre-ebook.com/whats-new.

### Detailed error message
```
calibre, version 5.24.0
ERROR: Unhandled exception: <b>ModuleNotFoundError</b>:No module named 'jeepney'

calibre 5.24  embedded-python: False is64bit: True
Linux-5.10.57-x86_64-with-glibc2.33 Linux ('64bit', 'ELF')
('Linux', '5.10.57', '#1-NixOS SMP Sun Aug 8 07:05:24 UTC 2021')
Python 3.9.6
Interface language: None
Traceback (most recent call last):
  File "/nix/store/z0s651a0i5p3h5mld8yyxqyfknhy9jjf-calibre-5.24.0/lib/calibre/calibre/gui2/device.py", line 1291, in dispatch_sync_event
    self.sync_to_device(on_card, delete, fmt)
  File "/nix/store/z0s651a0i5p3h5mld8yyxqyfknhy9jjf-calibre-5.24.0/lib/calibre/calibre/gui2/device.py", line 1527, in sync_to_device
    self.status_bar.show_message(_('Sending books to device.'), 5000)
  File "/nix/store/z0s651a0i5p3h5mld8yyxqyfknhy9jjf-calibre-5.24.0/lib/calibre/calibre/gui2/init.py", line 325, in show_message
    self.notifier(msg)
  File "/nix/store/z0s651a0i5p3h5mld8yyxqyfknhy9jjf-calibre-5.24.0/lib/calibre/calibre/gui2/notify.py", line 146, in __call__
    self.initialize()
  File "/nix/store/z0s651a0i5p3h5mld8yyxqyfknhy9jjf-calibre-5.24.0/lib/calibre/calibre/gui2/notify.py", line 44, in initialize
    from jeepney.io.blocking import open_dbus_connection
ModuleNotFoundError: No module named 'jeepney'
```

### Notify maintainers
@pSub @AndersonTorres

### Metadata
I cannot run `nix-info` because I don't use channels but Nix Flakes. This is the relevant part of the lock file:
```console
"nixpkgs": {
      "locked": {
        "lastModified": 1628693817,
        "narHash": "sha256-WtlM8ptjcUUWRvbpkToKJHzLlGCEXZKGh+SfwUYHobA=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "9df2cb074d72ea80ac9fd225b29060c8cf13dd39",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
```

EDIT: I just realized that the book is correctly added to the device, but the error still shows up. Also, the books on the device are not reported in calibre.

**Comment by samdoshi** [comment]
I've submitted a PR for this, but if you need a temporary fix replace `calibre` in your `systemPackages` with:

```
(calibre.overrideAttrs (o: { nativeBuildInputs = o.nativeBuildInputs ++ [ python3Packages.jeepney ];}))
```

or if you also wish to get the DeDRM plugin working too:

```
(calibre.overrideAttrs (o: { nativeBuildInputs = o.nativeBuildInputs ++ [ python3Packages.pycryptodome python3Packages.jeepney ];}))
```

**Comment by dschrempf** [comment]
Thank you very much!
