### ISSUE TITLE
Eclipse is missing libsecret (keyring support)

### ISSUE THREAD

**Issue by Nervengift** [NixOS/nixpkgs#133628]
### Describe the bug
Eclipse's keyring integration does not work. In my specific case, the sonar lint plugin would crash when trying to safe a connection:

<details>
  <summary>stacktrace</summary>
<pre>
java.lang.UnsatisfiedLinkError: Unable to load library 'secret-1': Native library (linux-x86-64/libsecret-1.so) not found in resource path (/nix/store/5n7i02hgvxryl5d3lg9964a9676fa1mi-eclipse-java-4.19/eclipse//plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.loadLibrary(Native.java:569)
	at com.sun.jna.Native.loadLibrary(Native.java:544)
	at org.eclipse.equinox.internal.security.linux.LinuxPasswordProvider.unlockSecretService(LinuxPasswordProvider.java:99)
	at org.eclipse.equinox.internal.security.linux.LinuxPasswordProvider.canUnlock(LinuxPasswordProvider.java:140)
	at org.eclipse.equinox.internal.security.linux.LinuxPasswordProvider.isValid(LinuxPasswordProvider.java:220)
	at org.eclipse.equinox.internal.security.storage.PasswordProviderSelector.findAvailableModules(PasswordProviderSelector.java:138)
	at org.eclipse.equinox.internal.security.storage.PasswordProviderSelector.findStorageModule(PasswordProviderSelector.java:163)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.getModulePassword(SecurePreferencesRoot.java:237)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.getPassword(SecurePreferencesRoot.java:230)
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.put(SecurePreferences.java:229)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesWrapper.put(SecurePreferencesWrapper.java:128)
	at org.sonarlint.eclipse.core.internal.engine.connected.ConnectedEngineFacadeManager.storeCredentials(ConnectedEngineFacadeManager.java:271)
	at org.sonarlint.eclipse.core.internal.engine.connected.ConnectedEngineFacadeManager.addServer(ConnectedEngineFacadeManager.java:260)
	at org.sonarlint.eclipse.ui.internal.binding.wizard.connection.ServerConnectionWizard.finalizeConnectionCreation(ServerConnectionWizard.java:255)
	at org.sonarlint.eclipse.ui.internal.binding.wizard.connection.ServerConnectionWizard.performFinish(ServerConnectionWizard.java:238)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
</pre>
</details>

### Steps To Reproduce

I found the issue while setting up the sonar lint plugin (from marketplace) and connecting it to sonarqube but it may be possible to also produce it by e.g. saving secrets for egit. It seems to be an issue in eclipse, not sonar lint.

### Expected behavior
No crash in plugins, keyring integration works.

### Additional context
I could fix the issue locally by adding libsecret here:

https://github.com/NixOS/nixpkgs/blob/927f070592c7cfbd9c0507e90fb9049f039b454a/pkgs/applications/editors/eclipse/build-eclipse.nix#L44

I could provide an MR if anyone can tell me if this is an ok fix or if we need a feature toggle for this.

### Notify maintainers

@jerith666 (last commits, no maintainer?)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"                                                                ⏎
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.05.1542.268dee84298 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.1542.268dee84298"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jerith666** [comment]
> I could fix the issue locally by adding libsecret here:

I don't have a problem with that fix -- please open a PR so we can get some more opinions.  Thanks!
