### ISSUE TITLE
ledger-autosync-0.2.3 missing ofxclient.config

### ISSUE THREAD

**Issue by codemac** [NixOS/nixpkgs#13411]
## Basic info

To make sure that we are on the same page:

```
codemac@neah:~/beans % nixos-version
16.03pre76756.885acea (Emu)
codemac@neah:~/beans % uname -a
Linux neah 4.1.17 #1-NixOS SMP Sun Jan 31 19:23:48 UTC 2016 x86_64 GNU/Linux
codemac@neah:~/beans % nix-instantiate --eval "<nixpkgs>" -A lib.nixpkgsVersion
"16.03pre76756.885acea"
codemac@neah:~/beans % nix-env --version
nix-env (Nix) 1.11.1
```
## Describe your issue here

When I run ledger-autosync, it complains about a missing module.

### Expected result

I expect it to run

### Actual result

It prints:

```
Traceback (most recent call last):
  File "/nix/store/z53xbxlv8ssmcxnspdxakbx43pv18wsx-python2.7-ledger-autosync-0.2.3/bin/.ledger-autosync-wrapped", line 8, in <module>
    from ledgerautosync.cli import run
  File "/nix/store/z53xbxlv8ssmcxnspdxakbx43pv18wsx-python2.7-ledger-autosync-0.2.3/lib/python2.7/site-packages/ledgerautosync/cli.py", line 22, in <module>
    from ofxclient.config import OfxConfig
ImportError: No module named ofxclient.config
```
### Steps to reproduce

```
nix-env -iA nixos.python27Packages.ledger-autosync
ledger-autosync
```

**Comment by codemac** [comment]
Let me know if there is any other information you would like me to provide.

**Comment by FRidh** [comment]
cc maintainer @nlewo  (btw, nlewo, your nick in `pythonPackages.ledger-autosync` is wrong)
