### ISSUE TITLE
Missing dependencies for qmk

### ISSUE THREAD

**Issue by moritzschaefer** [NixOS/nixpkgs#134530]
### Describe the bug
qmk requires several tools for compiling. These should be added as a dependency: 

`[I] moritz@moxps ~/P/qmk_firmware (master) [SIGINT]> qmk  setup
Ψ Found qmk_firmware at /home/moritz/Projects/qmk_firmware.
Ψ QMK Doctor is checking your environment.
Ψ Detected Linux.
⚠ Missing or outdated udev rules for 'kiibohd' boards. Run 'sudo cp /home/moritz/Projects/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'stm32' boards. Run 'sudo cp /home/moritz/Projects/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'bootloadhid' boards. Run 'sudo cp /home/moritz/Projects/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'usbasploader' boards. Run 'sudo cp /home/moritz/Projects/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'massdrop' boards. Run 'sudo cp /home/moritz/Projects/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Detected ModemManager without the necessary udev rules. Please either disable it or set the appropriate udev rules if you are using a Pro Micro.
⚠ Missing or outdated udev rules for 'caterina' boards. Run 'sudo cp /home/moritz/Projects/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
Ψ QMK home: /home/moritz/Projects/qmk_firmware
☒ Can't find arm-none-eabi-gcc in your path.
☒ Can't find avr-gcc in your path.
☒ Can't find avrdude in your path.
☒ Can't run `bin/qmk --version`
☒ Can't find dfu-programmer in your path.
☒ Can't find dfu-util in your path.
`

### Steps To Reproduce
1. Install qmk
2. Try to compile anything with qmk

### Expected behavior
The required tools are available

### Notify maintainers
bhipple is there a specific reason that you did not include the dependencies?

**Comment by RealET** [comment]
I am having a similar issue, though with some different missing dependencies.  I am not sure if I missed something in the installation process.
`[realet@RealET-laptop:~/qmk_firmware]$ qmk setup
Ψ Found qmk_firmware at /home/realet/qmk_firmware.
Ψ QMK Doctor is checking your environment.
Ψ QMK home: /home/realet/qmk_firmware
Ψ Detected Linux.
⚠ Missing or outdated udev rules for 'atmel-dfu' boards. Run 'sudo cp /home/realet/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'kiibohd' boards. Run 'sudo cp /home/realet/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'stm32' boards. Run 'sudo cp /home/realet/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'bootloadhid' boards. Run 'sudo cp /home/realet/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'usbasploader' boards. Run 'sudo cp /home/realet/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'massdrop' boards. Run 'sudo cp /home/realet/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
⚠ Missing or outdated udev rules for 'caterina' boards. Run 'sudo cp /home/realet/qmk_firmware/util/udev/50-qmk.rules /etc/udev/rules.d/'.
☒ Can't find arm-none-eabi-gcc in your path.
☒ Can't find avr-gcc in your path.
☒ Can't find avrdude in your path.
☒ Can't find dfu-programmer in your path.
☒ Can't find dfu-util in your path.
Would you like to install dependencies? [Y/n] y
<class 'FileNotFoundError'>
☒ [Errno 2] No such file or directory: 'util/qmk_install.sh'
Traceback (most recent call last):
  File "/nix/store/cha2xgvxchxjdkrwk42r01a4cz29n4im-python3.9-milc-1.4.2/lib/python3.9/site-packages/milc/milc.py", line 476, in __call__
    return self.__call__()
  File "/nix/store/cha2xgvxchxjdkrwk42r01a4cz29n4im-python3.9-milc-1.4.2/lib/python3.9/site-packages/milc/milc.py", line 479, in __call__
    return self._subcommand(self)
  File "/home/realet/qmk_firmware/lib/python/qmk/cli/doctor.py", line 96, in doctor
    cli.run(['util/qmk_install.sh', '-y'], stdin=DEVNULL, capture_output=False)
  File "/nix/store/cha2xgvxchxjdkrwk42r01a4cz29n4im-python3.9-milc-1.4.2/lib/python3.9/site-packages/milc/milc.py", line 154, in run
    return subprocess.run(command, **kwargs)
  File "/nix/store/yqjhkdarf7p74wcha7aypzsb751n7wl2-python3-3.9.5/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/yqjhkdarf7p74wcha7aypzsb751n7wl2-python3-3.9.5/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/yqjhkdarf7p74wcha7aypzsb751n7wl2-python3-3.9.5/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'util/qmk_install.sh'
`
