### ISSUE TITLE
tmuxinator package broken

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#13484]
## Basic info

To make sure that we are on the same page:

* Kernel: Linux alpha 4.4.2 #1-NixOS SMP Wed Feb 17 20:31:25 UTC 2016 x86_64 GNU/Linux
* System: 16.03pre77568.40c586b (Emu)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.03pre77568.40c586b

### Expected result

No error on running `tmuxinator` command

### Actual result

```
$ tmuxinator
/nix/store/1waqk6r3y5p7s9pznn3269pi4078yhsa-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /nix/store/1waqk6r3y5p7s9pznn3269pi4078yhsa-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /run/current-system/sw/bin/tmuxinator:16:in `<main>'
```

### Steps to reproduce

run `tmuxinator` on latest unstable

```
$ nix-shell -p tmuxinator --pure --run "tmuxinator" 
```

tmuxinator package wasn't update since may 2005 so I suspect something changed in ruby packaging.

might be related to #13158 (similar error message)

**Comment by ericsagnes** [comment]
working on master
