### ISSUE TITLE
Cide fails execute

### ISSUE THREAD

**Issue by lsix** [NixOS/nixpkgs#13553]
## Basic info

To make sure that we are on the same page:
- Kernel: `Linux 4.1.17 #1-NixOS SMP Sun Jan 31 19:23:48 UTC 2016 x86_64 GNU/Linux`
- System: `16.03pre76756.885acea (Emu)`
- Nix version: `nix-env (Nix) 1.11.1`
- Nixpkgs version: (master@eaed5598592ca8ccc05d9f09abcb4a27a06f1fb4) `16.03pre-git`
## Describe your issue here

This is a follow-up of #13485.

`pkgs.cide` builds fine, but cannot execute properly on my system (and within an isolated, created for the test virtual machine).

Here is a simple test case that fails to pass:

```
import <nixpkgs/nixos/tests/make-test.nix> ({ pkgs, ... }:
{
  name = "cide-exe-test";
  nodes = {
    thehost = { config, pkgs, ... }:
              {
                 environment.systemPackages = [ pkgs.cide ];
              };
  };
  testScript =
  ''
    startAll;
    $thehost->waitForUnit("default.target");
    $thehost->succeed("cide --version");
  '';
})
```
### Actual result

```
thehost# /nix/store/p1smzl194057x5ixk5aymkal6cwmjq3j-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
thehost#        from /nix/store/p1smzl194057x5ixk5aymkal6cwmjq3j-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
thehost#        from /nix/store/q4jlk1p6q0pmsd31w6b6wyv9mh1f23pf-cide-0.9.0-gems/bin/cide:16:in `<main>'
```
### Steps to reproduce

Given that the test describes before is in `test_cide.nix`:

```
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/eaed5598592ca8ccc05d9f09abcb4a27a06f1fb4.tar.gz nix-build test_cide.nix
```

**Comment by zimbatm** [comment]
Awesome report :)

Can you give me the output of:
```
$ env | grep GEM
```

Also try to run with `unset GEM_PATH; cide`. I think the rubygem wrappers need a bit of re-thinking.

**Comment by lancelotsix** [comment]
I do not have any `GEM_PATH` set (I do not have any ruby dev env by default):

```bash
$ env | grep GEM
$
```

If this is of any use, here is the result of the wrapper:

```bath
cat /nix/store/4aajy5f0kvv3h74xlx5lbd01vhwziyqc-cide-0.9.0/bin/cide 
#! /nix/store/idm1067y9i6m87crjqrbamdsq2ma5r7p-bash-4.3-p42/bin/bash -e
export PATH=/nix/store/npl3mjnz6v6xz3zk2lj55sn8paw8x5w0-docker-1.10.0/bin:/nix/store/h1s9586w90h80r1na0wsixy9yqyjlj0q-git-2.7.1/bin:/nix/store/ay8cpbxz6xavpapx568c3dyj8spilzfp-gnutar-1.28/bin:/nix/store/0fm4p26lvg6cv97gs3z29y9qr990677q-gzip-1.6/bin
exec /nix/store/q4jlk1p6q0pmsd31w6b6wyv9mh1f23pf-cide-0.9.0-gems/bin/cide "${extraFlagsArray[@]}" "$@"
$ cat /nix/store/q4jlk1p6q0pmsd31w6b6wyv9mh1f23pf-cide-0.9.0-gems/bin/cide 
#!/nix/store/p1smzl194057x5ixk5aymkal6cwmjq3j-ruby-2.3.0-p0/bin/ruby
#
# This file was generated by Nix.
#
# The application 'cide' is installed as part of a gem, and
# this file is here to facilitate running it.
#

ENV["BUNDLE_GEMFILE"] = "/nix/store/67dgnxamxdcsrr07yjrjz5ysxy08zr39-gemfile-and-lockfile/Gemfile"
ENV["BUNDLE_PATH"] = "/nix/store/q4jlk1p6q0pmsd31w6b6wyv9mh1f23pf-cide-0.9.0-gems/lib/ruby/gems/2.3.0"

gem_path = ENV["GEM_PATH"]
ENV["GEM_PATH"] = "#{gem_path}#{":" unless gem_path.nil? || gem_path.empty?}/nix/store/1gy2vlxga1nzaan9hrxjnppgzfj07hzd-bundler-1.10.6/lib/ruby/gems/2.3.0"

require 'rubygems'
require 'bundler/setup'

load Gem.bin_path("cide", "cide")
```

**Comment by grahamc** [comment]
I ran in to a very similar problem with `sup`, and if I run `nix-shell p bundler` and then inside that, run my package, it works. But without it, I get the same bundler error.

**Comment by zimbatm** [comment]
cide has been removed from nixpkgs since
