### ISSUE TITLE
Nextcloud fails on startup with traceback err on 21.11

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#136552]
### Describe the bug

```console
[root@finnaboo:/var/db]# systemctl restart nextcloud-setup.service 
Job for nextcloud-setup.service failed because the control process exited with error code.
See "systemctl status nextcloud-setup.service" and "journalctl -xe" for details.

[root@finnaboo:/var/db]# journalctl -xe
nextcloud-setup-start[7456]: Next Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "oc_appconfig" does not exist
Sep 03 09:21:42 finnaboo nextcloud-setup-start[7456]: LINE 1: SELECT * FROM "oc_appconfig"
Sep 03 09:21:42 finnaboo nextcloud-setup-start[7456]:                       ^ in /nix/store/v3x0psjsk8xg2fk544ppvdf34bsylnyq-nextcloud-22.0.0/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:67
Sep 03 09:21:42 finnaboo nextcloud-setup-start[7456]: Stack trace:
...
Sep 03 09:21:42 finnaboo nextcloud-setup-start[7456]: #34 /nix/store/v3x0psjsk8xg2fk544ppvdf34bsylnyq-nextcloud-22.0.0/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query('OC\\Files\\Node\\H...', false)
Sep 03 09:21:42 finnaboo nextcloud-setup-start[7456]: #35 /nix/store/v3x0psjsk8xg2fk544ppvdf34bsylnyq-nextcloud-22.0.0/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\\Files\\Node\\H...')
Sep 03 09:21:42 finnaboo nextcloud-setup-start[7456]: #36 /nix/store/v3x0psjsk8xg2fk544ppvdf34bsylnyq-nextcloud-22.0.0/lib/private/Server.php(1373): OC\AppFramework\Utility\SimpleContainer->get('OC\\Files\\Node\\H...')
Sep 03 09:21:42 finnaboo nextcloud-setup-start[7456]: #37 /nix/store/v3x0psjsk8xg2fk544ppvdf34bsylnyq-nextcloud-22.0.0/lib/base.php(594): OC\Server->boot()
Sep 03 09:21:42 finnaboo nextcloud-setup-start[7456]: #38 /nix/store/v3x0psjsk8xg2fk544ppvdf34bsylnyq-nextcloud-22.0.0/lib/base.php(1083): OC::init()
Sep 03 09:21:42 finnaboo nextcloud-setup-start[7456]: #39 /nix/store/v3x0psjsk8xg2fk544ppvdf34bsylnyq-nextcloud-22.0.0/console.php(48): require_once('/nix/store/v3x0...')
Sep 03 09:21:42 finnaboo nextcloud-setup-start[7456]: #40 /nix/store/v3x0psjsk8xg2fk544ppvdf34bsylnyq-nextcloud-22.0.0/occ(11): require_once('/nix/store/v3x0...')
Sep 03 09:21:42 finnaboo nextcloud-setup-start[7456]: #41 {main}
Sep 03 09:21:42 finnaboo systemd[1]: nextcloud-setup.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit nextcloud-setup.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Sep 03 09:21:42 finnaboo systemd[1]: nextcloud-setup.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit nextcloud-setup.service has entered the 'failed' state with result 'exit-code'.
Sep 03 09:21:42 finnaboo systemd[1]: Failed to start nextcloud-setup.service.
░░ Subject: A start job for unit nextcloud-setup.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit nextcloud-setup.service has finished with a failure.
░░ 
░░ The job identifier is 3821 and the job result is failed.
```

### Steps To Reproduce
1. Import this file:
```nix
# REF(Krey): How to set up Nextcloud on NixOS https://jacobneplokh.com/how-to-setup-nextcloud-on-nixos/
# REF(KREY): NixOS manual on nextcloud https://nixos.org/manual/nixos/stable/index.html#module-services-nextcloud
{ config, lib, ... }: lib.mkIf config.services.nextcloud.enable {
	services.nextcloud = {
		hostName = "nextcloud" + config.networking.fqdn;
		https = true;
		# FIXME-QA(Krey): implement logic that adjusts the value based on our available storage
			maxUploadSize = "8M";
		config = {
			# NOTE(Krey): Force nextcloud to use https
			overwriteProtocol = "https";

			adminuser = "admin";

			# Nextcloud PostegreSQL database configuration, recommended over using SQLite
			dbtype = "pgsql";
			dbuser = "nextcloud";
			dbhost = "/run/postgresql"; # nextcloud will add /.s.PGSQL.5432 by itself
			dbname = "nextcloud";
		};
		autoUpdateApps.startAt = "05:00:00";
	};
	# DND-SECURITY(Krey): These have to have a secret handling
	services.nextcloud.config.adminpass = "Heeyay";
	services.nextcloud.config.dbpass = "Heeyay";

	# Enable postgresql if nextcloud needs it
	# FIXME(Krey): Figure out why is this not working
	# services.postgresql.enable = if(config.service.nextcloud.config.dbtype == "pgsql")
	# 		then true
	# 		else false;
	services.postgresql.enable = true;
	services.postgresql = {
		ensureDatabases = [ "nextcloud" ];
		ensureUsers = [{
				name = "nextcloud";
				ensurePermissions."DATABASE nextcloud" = "ALL PRIVILEGES";
			}];
	};

	# ensure that postgres is running *before* running the setup
	systemd.services."nextcloud-setup" = {
		requires = ["postgresql.service"];
		after = ["postgresql.service"];
	};

	networking.firewall.allowedTCPPorts = [ 80 443 ];
}
```
2. Set `services.nextcloud.enable = true;`

### Expected behavior

Working nextcloud

### Additional context

System runs on a Hetzner cloud with a local builder

### Notify maintainers

CC @schneefux @bachp @globin @fpletz @ma27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
# Build system
[kreyren@leonid:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.11pre301985.23cd13167a1 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre301985.23cd13167a1"`
 - channels(kreyren): `"home-manager-21.05, master"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
 
# Hetzner Cloud
[root@finnaboo:/var/db]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.11pre301985.23cd13167a1 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bachp** [comment]
@Kreyren Is this on a fresh installation of nextcloud or did you upgrade from a previous version?

**Comment by Kreyren** [comment]
> @Kreyren Is this on a fresh installation of nextcloud or did you upgrade from a previous version? @bachp

Fresh installation

**Comment by Kreyren** [comment]
@bachp I assume that you closed this issue by mistake?

**Comment by Ma27** [comment]
Going to look into this later today.

**Comment by bachp** [comment]
> @bachp Did you closed this issue by mistake?

Yes sorry I was on mobile and must have accidently hit the wrong button.

**Comment by Ma27** [comment]
@Kreyren first of all, can you please check if `journalctl -u nextcloud-setup` has some more info (and post it here)?

I have a theory though:

* For some reason (I don't really understand), PHP's memory limit is set to `maxUploadSize` (8M in your case) in the module.
* My tests confirmed that this is by far not sufficient to run the setup. So perhaps, you have some inconsistent installation with no migrations applied and that's were your problem comes from.
* So if that's correct, you should be able to set `services.nextcloud.phpOptions.memory_limit = "1G"` (or whatever, but at least 512M according to Nextcloud) and re-run the installer (you may want to clear `/var/lib/nextcloud` though, but that shouldn't be a big deal in your case considering that this is a fresh install with no data that can be lost, correct?)..

**Comment by Kreyren** [comment]
> @Kreyren first of all, can you please check if journalctl -u nextcloud-setup has some more info (and post it here)? @Ma27 

```console
[nix-shell:~]# journalctl -u nextcloud-setup 2>&1 | ix
http://ix.io/3xOA
```

**Comment by Ma27** [comment]
Can you please run `mv /var/lib/nextcloud/config/config.php /var/lib/nextcloud/config/config.php.bak` and retry? It seems as if your installation config should be correct by now and you'll have to re-run the installer (which will happen if the `config.php` doesn't exist anymore).

**Comment by Kreyren** [comment]
> For some reason (I don't really understand), PHP's memory limit is set to maxUploadSize (8M in your case) in the module. @Ma27 

Same issue with the `maxUploadSize` commented out which defaults to `512M`

[nix-shell:~]# journalctl -u nextcloud-setup 2>&1 | ix
http://ix.io/3xOD

**Comment by Kreyren** [comment]
With `maxUploadSize` commented out `services.nextcloud.enable = true;` and `mv /var/lib/nextcloud/config/config.php /var/lib/nextcloud/config/config.php.bak`

```console
[root@finnaboo:~]# systemctl restart nextcloud-setup.service 
Job for nextcloud-setup.service failed because the control process exited with error code.
See "systemctl status nextcloud-setup.service" and "journalctl -xe" for details.

[root@finnaboo:~]# journalctl -u nextcloud-setup 2>&1 | ix
http://ix.io/3xOE
```

**Comment by Kreyren** [comment]
I've renamed the `/var/lib/nextcloud/config/config.php` again and run the `nextcloud-setup` service again and now it seems to work:

![image](https://user-images.githubusercontent.com/11302521/131988181-1563f03c-eb70-439e-b960-72b816d167e4.png)

**Comment by Ma27** [comment]
OK, great :) 

Anything else to handle here? Or can we close this then? :)

**Comment by Kreyren** [comment]
> Anything else to handle here? Or can we close this then? :) -- @Ma27

Seems to work so we can close, thanks for the help!

**Comment by Ma27** [comment]
> Seems to work so we can close, thanks for the help!

You're welcome! :)
