### ISSUE TITLE
Discourse fails to build with GemNotFound on 21.11

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#136547]
### Describe the bug

```console
[nix-shell:~/REDACTED/]$ HOSTNAME=finnaboo nixos-rebuild switch -I nixos-config=. --use-remote-sudo --target-host root@REDACTED
building Nix...
(root@REDACTED) Password: 
(root@REDACTED) Password: 
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
building the system configuration...
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
these derivations will be built:
  /nix/store/d643awr7ibza1ag0sr3bm8cmic0cakyg-discourse-assets-2.7.4.drv
  /nix/store/bi5a06iwfd9gdqgywmllxqmi93l5m8vn-discourse-2.7.4.drv
  /nix/store/zmcwrwshyzi5mx9h9460f3rsmcrz68cj-discourse-rake.drv
  /nix/store/5c2yga9zmjqb5zc0frr2xqb1jbmhvmcg-system-path.drv
  /nix/store/ap4ajhhapb4198lsv9801zrz14il19fq-dbus-1.drv
  /nix/store/332s42q1v5v388k8311qnw8qswxkv7yg-unit-dbus.service.drv
  /nix/store/71c0f12fcar6b5jywwpja7fh8ismiwc4-unit-systemd-fsck-.service.drv
  /nix/store/s5h7755dncmjmw3jjgnqaqgsqbp2vr90-unit-script-discourse-pre-start.drv
  /nix/store/fn47k0nky439yxvqjlswz81iggcasb2m-unit-discourse.service.drv
  /nix/store/pxl92sqa0fjzs1bwkfch8xfbai2s84nj-unit-polkit.service.drv
  /nix/store/7zdqc1d6q0amg1nxrskipjjlypbn2zmw-system-units.drv
  /nix/store/zggivr1wvx8z7j7pgzmdxkw0svn5pli0-unit-dbus.service.drv
  /nix/store/xay0dgy54535a6v0ny4rz0rc4ngpap02-user-units.drv
  /nix/store/n19ha8g67za5c83gzfkqba2is0l8s5ry-etc.drv
  /nix/store/67cvz5k8sapwizsrqsikccjn4pfablq7-nixos-system-finnaboo-21.11pre301985.23cd13167a1.drv
building '/nix/store/d643awr7ibza1ag0sr3bm8cmic0cakyg-discourse-assets-2.7.4.drv'...
unpacking sources
unpacking source archive /nix/store/hd8cbp0i09lzk1xv2fq094arclw4qccw-source
source root is source
patching sources
applying patch /nix/store/fwr2l8n5jfd9h1c7h5v30cc9plsm44ik-plugin_gem_api_version.patch
patching file lib/plugin_gem.rb
configuring
no configure script, doing nothing
building
Waiting for Redis and PostgreSQL to be ready..
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/build/.s.PGSQL.5432"?
2021-09-03 05:09:02.644 UTC [32] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-03 05:09:02.646 UTC [32] LOG:  listening on Unix socket "/build/.s.PGSQL.5432"
2021-09-03 05:09:02.659 UTC [36] LOG:  database system was shut down at 2021-09-03 05:09:02 UTC
2021-09-03 05:09:02.664 UTC [32] LOG:  database system is ready to accept connections
CREATE ROLE
CREATE DATABASE
CREATE EXTENSION
CREATE EXTENSION
bundler: failed to load command: rake (/nix/store/iai83miyc25hxwd79w6xh0ana0b9md1r-discourse-ruby-env-2.7.4/lib/ruby/gems/2.7.0/bin/rake)
Traceback (most recent call last):
        27: from /nix/store/v11va3c5l83mjkypr6wv1axazd42yjpl-ruby-2.7.4/bin/bundle:23:in `<main>'
        26: from /nix/store/v11va3c5l83mjkypr6wv1axazd42yjpl-ruby-2.7.4/bin/bundle:23:in `load'
        25: from /nix/store/iai83miyc25hxwd79w6xh0ana0b9md1r-discourse-ruby-env-2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/exe/bundle:37:in `<top (required)>'
        24: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
        23: from /nix/store/iai83miyc25hxwd79w6xh0ana0b9md1r-discourse-ruby-env-2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/exe/bundle:49:in `block in <top (required)>'
        22: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli.rb:24:in `start'
        21: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        20: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli.rb:30:in `dispatch'
        19: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        18: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        17: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        16: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli.rb:474:in `exec'
        15: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:28:in `run'
        14: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:61:in `kernel_load'
        13: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:61:in `require_relative'
        12: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/setup.rb:20:in `<top (required)>'
        11: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/ui/shell.rb:88:in `silence'
        10: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/ui/shell.rb:136:in `with_level'
         9: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/setup.rb:20:in `block in <top (required)>'
         8: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler.rb:149:in `setup'
         7: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/runtime.rb:20:in `setup'
         6: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/runtime.rb:91:in `block in definition_method'
         5: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:240:in `requested_specs'
         4: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:258:in `specs_for'
         3: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:189:in `specs'
         2: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/spec_set.rb:90:in `materialize'
         1: from /nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/spec_set.rb:90:in `map!'
/nix/store/vpsp8197vb5s9y2rlmfgkmivz5r9wlrm-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find libv8-node-15.14.0.1-x86_64-linux in any of the sources (Bundler::GemNotFound)
builder for '/nix/store/d643awr7ibza1ag0sr3bm8cmic0cakyg-discourse-assets-2.7.4.drv' failed with exit code 1
cannot build derivation '/nix/store/bi5a06iwfd9gdqgywmllxqmi93l5m8vn-discourse-2.7.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/zmcwrwshyzi5mx9h9460f3rsmcrz68cj-discourse-rake.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fn47k0nky439yxvqjlswz81iggcasb2m-unit-discourse.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/5c2yga9zmjqb5zc0frr2xqb1jbmhvmcg-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/7zdqc1d6q0amg1nxrskipjjlypbn2zmw-system-units.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/67cvz5k8sapwizsrqsikccjn4pfablq7-nixos-system-finnaboo-21.11pre301985.23cd13167a1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/67cvz5k8sapwizsrqsikccjn4pfablq7-nixos-system-finnaboo-21.11pre301985.23cd13167a1.drv' failed
```

### Steps To Reproduce

Set the following on NixOs 21.11 and expect failure:

```nix
services.discourse = {
	enable = true;
	hostname = "discourse" + config.networking.fqdn;
	admin = {
		fullName = "Jacob Hrbek";
		username = "kreyren";
		# FIXME(Krey): Decide on admin mail
		email = "kreyren@fsfe.org";
		passwordFile = "/var/db/discourse.db";
	};
};
# HOTFIX(Krey): The PostgreSQL version recommended for use with Discourse is 13.3, you're using 11.12. Either update your PostgreSQL package to the correct version or set services.discourse.database.ignorePostgresqlVersion. See https://nixos.org/manual/nixos/stable/index.html#module-postgresql for details on how to upgrade PostgreSQL.
	## Note(Krey): The assertion happens https://github.com/NixOS/nixpkgs/blob/7f857f1c32580c056d3b09758f0196a2acae962d/nixos/modules/services/web-apps/discourse.nix#L523, no idea why it's using postgresql_11 by default, needs to be investigated
services.discourse.database.ignorePostgresqlVersion = false;
services.postgresql.enable = true;
# CONTRIB(Krey): The upstream still use postgresql_11 which breaks the discourse build
services.postgresql.package = pkgs.postgresql_13;
```

### Expected behavior

Build Discourse

### Additional context

Distributed build from this system on Hetzner's Cloud
![image](https://user-images.githubusercontent.com/11302521/131953836-85932f1b-1e83-4be6-aa80-73e4e0321b5d.png)

### Notify maintainers

CC @talyz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
# Local Build system
[kreyren@leonid:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.11pre301985.23cd13167a1 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre301985.23cd13167a1"`
 - channels(kreyren): `"home-manager-21.05, master"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
# Hetzner system
[root@finnaboo:~]# nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/lp90qhw19dcp79cnlicjg09llgh7dzsz-bash-interactive-4.4-p23-dev
copying path '/nix/store/lp90qhw19dcp79cnlicjg09llgh7dzsz-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.44, NixOS, 21.11pre301985.23cd13167a1 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Kreyren** [comment]
Solved as pebcak i had issue in my handling that caused it to fail update repos.
