### ISSUE TITLE
Cocoapods broken due to wrong platform

### ISSUE THREAD

**Issue by jakubgs** [NixOS/nixpkgs#136971]
### Describe the bug

Cocoapods appears to not work at all when MacOS paltform is `x86_64-darwin-17`.

### Steps To Reproduce

1. Use `nixpkgs-unstable`
  ```
   > nix-channel --list          
  nixpkgs https://nixos.org/channels/nixpkgs-unstable
  ```
2. Start a shell with Cocoapods
  ```
   > nix-shell -p cocoapods
  [nix-shell:~]$ 
  ```
3. Try using any Cocoapods command/flag
  ```
  [nix-shell:~]$ pod --version
  Traceback (most recent call last):
  	3: from /nix/store/gpdhjclychkaa79jrxppbggklrfy4l54-cocoapods-1.10.2/bin/pod:18:in `<main>'
  	2: from /opt/nix/store/lgpws4n8vn3576wmp37j03q78z5ys6bl-bundler- 
 2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler.rb:143:in `setup'
  	1: from /opt/nix/store/lgpws4n8vn3576wmp37j03q78z5ys6bl-bundler- 
 2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/definition.rb:444:in `validate_runtime!'
  /opt/nix/store/lgpws4n8vn3576wmp37j03q78z5ys6bl-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler- 
 2.2.20/lib/bundler/definition.rb:475:in `validate_platforms!': Your bundle only supports platforms ["arm64-darwin-20"] but your local platform is x86_64-darwin-17. Add the current platform to the lockfile with `bundle lock --add-platform x86_64-darwin-17` and try again. (Bundler::ProductionError)
  ```

### Expected behavior

It works.

### Additional context

Previously Cocoapods would faild because of a different issue: https://github.com/NixOS/nixpkgs/issues/132049

But upgrade to `1.10.2` has resolved that failure: https://github.com/NixOS/nixpkgs/pull/134396

My understanding is that this happens because of platform missing in the `Gemfile.lock`:
```
 > COCOA=$(nix-build '<nixpkgs>' --no-out-link -A cocoapods)                                       
 > grep BUNDLE_GEMFILE $COCOA/bin/pod                                                              
ENV["BUNDLE_GEMFILE"] = "/nix/store/jvf9v0wxjw0y20vfkp20vjirhir835mk-gemfile-and-lockfile/Gemfile"
 > grep -A2 PLATFORMS /nix/store/jvf9v0wxjw0y20vfkp20vjirhir835mk-gemfile-and-lockfile/Gemfile.lock
PLATFORMS
  arm64-darwin-20
```

### Notify maintainers
@peterromfeldhk, @lilyball

### Metadata

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(jenkins): `"nixpkgs-21.11pre312229.08ef0f28e3a"`
 - nixpkgs: `/Users/jenkins/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
    - cocoapods
    - cocoapods-beta
# a list of nixos modules affected by the problem
module:
```

**Comment by jakubgs** [comment]
I see there is a `Gemfile.lock` directly in the repo that specifies this:
https://github.com/NixOS/nixpkgs/blob/23d5823337f4502dfa17e192d8c53a47cabcb6b4/pkgs/development/mobile/cocoapods/Gemfile.lock#L91-L92
And I see there is an update script that updates those:
https://github.com/NixOS/nixpkgs/blob/23d5823337f4502dfa17e192d8c53a47cabcb6b4/pkgs/development/mobile/cocoapods/update#L11
Not sure what's the correct way of dealing with his.

**Comment by jakubgs** [comment]
I guess on option is to modify this line:
https://github.com/NixOS/nixpkgs/blob/23d5823337f4502dfa17e192d8c53a47cabcb6b4/pkgs/development/mobile/cocoapods/update#L9
To look like this:
```sh
bundler lock --add-platform x86_64-darwin-17
```

**Comment by jakubgs** [comment]
We can see that this change happened in:
https://github.com/NixOS/nixpkgs/pull/134396/files#diff-813c447b2dae3c70a7501b406a225770f8ab51a567475683d82830db9048cfeaL86-L87
Where the allowed platform went from `ruby` to `arm64-darwin-20`, which is broken on any other platform.

**Comment by jakubgs** [comment]
Maybe if we want to retain the previous value the correct line would be:
```
bundler lock --add-platform ruby
```
But not sure if that would work.

**Comment by jakubgs** [comment]
Will be fixed by: https://github.com/NixOS/nixpkgs/pull/137240
