### ISSUE TITLE
vimPlugins.markdown-preview-nvim not working

### ISSUE THREAD

**Issue by ursi** [NixOS/nixpkgs#137239]
When running `:MarkdownPreview` I get the following error (silently, I have to run `:mes` to see it)

```
internal/modules/cjs/loader.js:892
  throw err;
  ^
Error: Cannot find module 'tslib'
Require stack:
- /nix/store/5pvg3ncxdr0iqs8qm8j2163khsrl43y5-vimplugin-markdown-preview-nvim-2021-03-10/share/vim-plugins/markdown-preview-nvim/app/lib/app/index.js
- /nix/store/5pvg3ncxdr0iqs8qm8j2163khsrl43y5-vimplugin-markdown-preview-nvim-2021-03-10/share/vim-plugins/markdown-preview-nvim/app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/nix/store/5pvg3ncxdr0iqs8qm8j2163khsrl43y5-vimplugin-markdown-preview-nvim-2021-03-10/share/vim-plugins/markdown-preview-nvim/app/lib/app/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/5pvg3ncxdr0iqs8qm8j2163khsrl43y5-vimplugin-markdown-preview-nvim-2021-03-10/share/vim-plugins/markdown-preview-nvim/app/lib/app/index.js',
    '/nix/store/5pvg3ncxdr0iqs8qm8j2163khsrl43y5-vimplugin-markdown-preview-nvim-2021-03-10/share/vim-plugins/markdown-preview-nvim/app/index.js'
  ]
}
```

building my system with 8d8a28b47b7c41aeb4ad01a2bd8b7d26986c3512

@ing @SuperSandro2000 since you're the last person to touch `generated.nix` and I don't know who specifically to @.

**Comment by teto** [comment]
there are a few plugins that regularly break (unicode.vim too). Whoever tackles this it would be nice to add a checkPhase (see https://github.com/NixOS/nixpkgs/pull/117285 for inspiration).

**Comment by SuperSandro2000** [comment]
tslib is missing. Probably the package.json for that plugin needs to be updated.

**Comment by oxalica** [comment]
According to README https://github.com/iamcco/markdown-preview.nvim/#install--usage
The extension requires a `yarn init` to populate the `node_modules` first. But we currently simply download and unpack the source code.
I'm curious about how it works at the first place.
