### ISSUE TITLE
paperless-ng webserver not working

### ISSUE THREAD

**Issue by StillerHarpo** [NixOS/nixpkgs#137558]
### Describe the bug
I can't open paperless-ng in a web browser

### Steps To Reproduce
1. Add the following to your nixos configuration
```nix
    paperless-ng = {
      enable = true;
      passwordFile = "/path/to/password/file;
      consumptionDir = "/path/to/your/consume/directory";
      consumptionDirIsPublic = true;
    };

```
2. run `nixos-rebuild switch`
3. open https://localhost:28981/ in webbrowser

### Expected behavior
I should be able to open paperless in a webrowser with `localhost:28981`

### Additional context
I have the following in the log of `paperless-ng-web.service`

```console
Sep 12 20:49:01 nixos-thinkpad systemd[1]: Started Paperless web server.
Sep 12 20:49:02 nixos-thinkpad gunicorn[5267]: [2021-09-12 18:49:02 +0000] [5267] [INFO] Starting gunicorn 20.1.0
Sep 12 20:49:02 nixos-thinkpad gunicorn[5267]: [2021-09-12 18:49:02 +0000] [5267] [INFO] Listening at: http://127.0.0.1:28981 (>
Sep 12 20:49:02 nixos-thinkpad gunicorn[5267]: [2021-09-12 18:49:02 +0000] [5267] [INFO] Using worker: paperless.workers.Config>
Sep 12 20:49:02 nixos-thinkpad gunicorn[5267]: [2021-09-12 18:49:02 +0000] [5267] [INFO] Server is ready. Spawning workers
Sep 12 20:49:03 nixos-thinkpad gunicorn[5267]: [2021-09-12 18:49:03 +0000] [5267] [WARNING] Worker with pid 5274 was terminated>
Sep 12 20:49:03 nixos-thinkpad gunicorn[5267]: [2021-09-12 18:49:03 +0000] [5267] [INFO] Shutting down: Master
Sep 12 20:49:03 nixos-thinkpad gunicorn[5267]: [2021-09-12 18:49:03 +0000] [5267] [INFO] Reason: Worker failed to boot.
Sep 12 20:49:04 nixos-thinkpad systemd[1]: paperless-ng-web.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Sep 12 20:49:04 nixos-thinkpad systemd[1]: paperless-ng-web.service: Failed with result 'exit-code'.
Sep 12 20:49:04 nixos-thinkpad systemd[1]: paperless-ng-web.service: Consumed 3.906s CPU time, no IP traffic.
Sep 12 20:49:04 nixos-thinkpad systemd[1]: paperless-ng-web.service: Scheduled restart job, restart counter is at 171.
Sep 12 20:49:04 nixos-thinkpad systemd[1]: Stopped Paperless web server.
Sep 12 20:49:04 nixos-thinkpad systemd[1]: paperless-ng-web.service: Consumed 3.906s CPU time, no IP traffic.
```

I also have this in `paperless-ng-server.service`
```console
Sep 13 18:07:04 nixos-thinkpad paperless-ng[16051]: documents.consumer.ConsumerError: input_200_29_08_2021.pdf: Cannot consume /home/florian/Dokumente/scans/input_200_29_08_2021.pdf: File not found.
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16048]: 16:07:05 [Q] INFO recycled worker Process-1:235
Sep 13 18:07:05 nixos-thinkpad paperless-ng[34467]: 16:07:05 [Q] INFO Process-1:236 ready for work at 34467
Sep 13 18:07:05 nixos-thinkpad paperless-ng[34467]: 16:07:05 [Q] INFO Process-1:236 processing [input_44_29_08_21.pdf]
Sep 13 18:07:05 nixos-thinkpad paperless-ng[34467]: [2021-09-13 16:07:05,200] [ERROR] [paperless.consumer] Cannot consume /home/florian/Dokumente/scans/input_44_29_08_21.pdf: File not found.
Sep 13 18:07:05 nixos-thinkpad paperless-ng[34467]: 16:07:05 [Q] INFO Process-1:236 stopped doing work
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]: 16:07:05 [Q] ERROR Failed [input_44_29_08_21.pdf] - input_44_29_08_21.pdf: Cannot consume /home/florian/Dokumente/scans/input_44_29_08_21.pdf: File not found. : Traceback (most recent call last):
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]:   File "/nix/store/lq7aci9bh5n8jkj8cnk818b6f1jplfa5-python3.9-django-q-1.3.4/lib/python3.9/site-packages/django_q/cluster.py", line 436, in worker
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]:     res = f(*task["args"], **task["kwargs"])
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]:   File "/nix/store/0nsyi2dzxicg487p0kk5m6gzwndyd2pc-paperless-ng-1.5.0/lib/paperless-ng/src/documents/tasks.py", line 74, in consume_file
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]:     document = Consumer().try_consume_file(
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]:   File "/nix/store/0nsyi2dzxicg487p0kk5m6gzwndyd2pc-paperless-ng-1.5.0/lib/paperless-ng/src/documents/consumer.py", line 195, in try_consume_file
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]:     self.pre_check_file_exists()
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]:   File "/nix/store/0nsyi2dzxicg487p0kk5m6gzwndyd2pc-paperless-ng-1.5.0/lib/paperless-ng/src/documents/consumer.py", line 86, in pre_check_file_exists
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]:     self._fail(
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]:   File "/nix/store/0nsyi2dzxicg487p0kk5m6gzwndyd2pc-paperless-ng-1.5.0/lib/paperless-ng/src/documents/consumer.py", line 70, in _fail
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]:     raise ConsumerError(f"{self.filename}: {log_message or message}")
Sep 13 18:07:05 nixos-thinkpad paperless-ng[16051]: documents.consumer.ConsumerError: input_44_29_08_21.pdf: Cannot consume /home/florian/Dokumente/scans/input_44_29_08_21.pdf: File not found.

```

### Notify maintainers
@Flakebi 
@erikarvstedt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.05.20210910.8b0b81d (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.05.2549.a1007637cea, nixos-unstable-21.05pre273435.0aeba64fb26, nixpkgs-20.09.3341.df8e3bd1109"`
 - channels(florian): `"home-manager, nixos-21.05.1076.bad3ccd099e, nixos-unstable-21.11pre296557.33d42ad7cf2, nixpkgs-21.05.1076.bad3ccd099e"`
 - nixpkgs: `/home/florian/.nix-defexpr/channels/nixpkgs`
```

The channels aren't relevant because I'm using flakes. [Here](https://github.com/StillerHarpo/nixosconfiguration/blob/c789f89e7aaccc727319559fb7dd7dca9417f7d8/thinkpadSpecific.nix#L83) is the relevant part in my configuration

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: paperless-ng
# a list of nixos modules affected by the problem
module: services.paperless-ng
```

**Comment by Flakebi** [comment]
The `[WARNING] Worker with pid 5274 was terminated>` seems to be cut off, is there something useful in there?

Consuming files works fine for me, but I’m setting the user instead of `consumptionDirIsPublic`:
```nix
  services.paperless-ng = {
    enable = true;
    user = "sebi";
    consumptionDir = "/home/sebi/paperless";
  };
```

Maybe that makes a difference if the parent directories are not accessible by the consume service.

**Comment by StillerHarpo** [comment]
I fixed it by using paperless from the master channel (the fixing commit https://github.com/StillerHarpo/nixosconfiguration/commit/1825773f7f0a888947fc6f8cf04217e21e2bdb82)
