### ISSUE TITLE
`pkgsCross.aarch64-multiplatform.gcc` is broken on aarch64-darwin

### ISSUE THREAD

**Issue by mstone** [NixOS/nixpkgs#137877]
### Describe the bug

`nix -L build nixpkgs#pkgsCross.aarch64-multiplatform.gcc` fails while building `aarch64-unknown-linux-gnu-stage-final-gcc-debug-11.1.0` with log messages:

```console
...
configure: error: conditional "ENABLE_DARWIN_AT_RPATH" was never defined.
Usually this means the macro was only invoked conditionally.
```

### Other notes

CC: @bobrik, based on 4aa95e33121c316c5b34031bb08106d2dc113e38 / credit for [this line](https://github.com/NixOS/nixpkgs/blame/2a58c796aae69a2d89acab70d83ec86c5c775fd2/pkgs/development/compilers/gcc/11/default.nix#L75), in case you have by chance already tangled with this...

### Metadata

```console
[user@system:~]$ $ nix run nixpkgs#nix-info -- -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 20.6.0, macOS 11.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210914_275cb44`
 - channels(root): `"nixpkgs-21.11pre302272.fd16fa6805e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gcc11
# a list of nixos modules affected by the problem
module:
```

**Comment by mstone** [comment]
Note: after doing just a touch of digging in https://github.com/iains/gcc-darwin-arm64, it looks like this may plausibly already be fixed "upstream", perhaps in https://github.com/iains/gcc-darwin-arm64/pull/46 or https://github.com/iains/gcc-darwin-arm64/commit/7bdd75771b961368d28d64b2a0c5b216ae1a3856 so as a result I think a good next step is indeed to try regenerating the patch that @bobrik's `nixpkgs` change is applying to `gcc11` to add the `aarch64-darwin` port to see if that enables us to get any further...

**Comment by bobrik** [comment]
I did look into making cross-compiling work initially, but it wasn't targeted in Homebrew (where the patch originated), and I'm not exactly an expert in this, so I ultimately gave up.

**Comment by happysalada** [comment]
I'm interested in this.
Perhaps being over optimistic, but is there a chance that this could work if gcc was updated ?

**Comment by happysalada** [comment]
it wasn't super clear from my last post, but if you have ideas of things to try to fix this, I'm game.

**Comment by ElvishJerricco** [comment]
So if I build `pkgsCross.aarch64-multiplatform.stdenv` on darwin, I get this error as expected in `aarch64-unknown-linux-gnu-stage-final-gcc-debug-11.2.0`. But interestingly enough, if I build `pkgsCross.aarch64-multiplatform.pkgsLLVM.stdenv`, I see that it *does still build* a version of `aarch64-unknown-linux-gnu-stage-final-gcc-debug-11.2.0`, but this one succeeds, and indeed so does the `stdenv` derivation. Seems you can in fact build a cross toolchain for Linux on Darwin if you use an LLVM toolchain. In fact I can even build `hello` in this package set. However when running that `hello` binary on an `aarch64-linux` machine, I get this:

```
Inconsistency detected by ld.so: get-dynamic-info.h: 126: elf_get_dynamic_info: Assertion `info[DT_RUNPATH] == NULL' failed!
```

**Comment by ElvishJerricco** [comment]
Ah no I misread my builds slightly. Whether you use `pkgsLLVM` or not, it builds `aarch64-unknown-linux-gnu-stage-static-gcc-debug-11.2.0`. What it *doesn't* build with `pkgsLLVM` is `aarch64-unknown-linux-gnu-stage-final-gcc-debug-11.2.0`, and that's the one that fails. Regardless, `pkgsCross.aarch64-multiplatform.pkgsLLVM` is at least *close* to working :P

**Comment by freezeboy** [comment]
I would also be interested in this fix. I can help investigate but I don't know precisely how the cross compilation is done in nixpkgs.

**Comment by ElvishJerricco** [comment]
I tried something kind of stupid and just added this to the GCC derivation:

```
ENABLE_DARWIN_AT_RPATH_TRUE = "#";
ENABLE_DARWIN_AT_RPATH = "no";
```

And... it built! So it seems like just a bug in the configure scripts.

Even `pkgsCross.aarch64-multiplatform.hello` built. But it had the same runtime error as with the LLVM build.

```
Inconsistency detected by ld.so: get-dynamic-info.h: 126: elf_get_dynamic_info: Assertion `info[DT_RUNPATH] == NULL' failed!
```

Absolutely no idea what that's about.

**Comment by alekseysidorov** [comment]
Hi! I also tried to override the GCC derivation:

```
  gcc = super.lowPrio (super.wrapCC (super.gcc.cc.overrideAttrs (old: {
        ENABLE_DARWIN_AT_RPATH_TRUE = "#";
        ENABLE_DARWIN_AT_RPATH = "no";
      })));
```

And GCC successfully built, but when I tried to create a docker image I'd got an error:

```
Creating layer 1 from paths: ['/nix/store/h1lbygjcrz6xyvfbd8hg8q0cpdymibml-musl-x86_64-unknown-linux-musl-1.2.3']
Traceback (most recent call last):
  File "/nix/store/f7z6gw9zd5xzrylh7z2ww97rdhf7farx-stream", line 392, in <module>
    main()
  File "/nix/store/f7z6gw9zd5xzrylh7z2ww97rdhf7farx-stream", line 340, in main
    info = add_layer_dir(tar, store_layer, store_dir, mtime=mtime)
  File "/nix/store/f7z6gw9zd5xzrylh7z2ww97rdhf7farx-stream", line 232, in add_layer_dir
    archive_paths_to(
  File "/nix/store/f7z6gw9zd5xzrylh7z2ww97rdhf7farx-stream", line 94, in archive_paths_to
    ti = append_root(tar.gettarinfo(filename))
  File "/nix/store/pxlg0drlwxb367agwf121i9rjwmahnsw-python3-3.9.13/lib/python3.9/tarfile.py", line 1879, in gettarinfo
    linkname = os.readlink(name)
PermissionError: [Errno 13] Permission denied: '/nix/store/h1lbygjcrz6xyvfbd8hg8q0cpdymibml-musl-x86_64-unknown-linux-musl-1.2.3/lib/ld-musl-x86_64.so.1'
error: builder for '/nix/store/i278zncbikcd9cqb1pj8lfhqb9rjsb67-post_meeting_api.tar.gz.drv' failed with exit code 1;
       last 10 log lines:
       >     main()
       >   File "/nix/store/f7z6gw9zd5xzrylh7z2ww97rdhf7farx-stream", line 340, in main
       >     info = add_layer_dir(tar, store_layer, store_dir, mtime=mtime)
       >   File "/nix/store/f7z6gw9zd5xzrylh7z2ww97rdhf7farx-stream", line 232, in add_layer_dir
       >     archive_paths_to(
       >   File "/nix/store/f7z6gw9zd5xzrylh7z2ww97rdhf7farx-stream", line 94, in archive_paths_to
       >     ti = append_root(tar.gettarinfo(filename))
       >   File "/nix/store/pxlg0drlwxb367agwf121i9rjwmahnsw-python3-3.9.13/lib/python3.9/tarfile.py", line 1879, in gettarinfo
       >     linkname = os.readlink(name)
       > PermissionError: [Errno 13] Permission denied: '/nix/store/h1lbygjcrz6xyvfbd8hg8q0cpdymibml-musl-x86_64-unknown-linux-musl-1.2.3/lib/ld-musl-x86_64.so.1'
       For full logs, run 'nix log /nix/store/i278zncbikcd9cqb1pj8lfhqb9rjsb67-post_meeting_api.tar.gz.drv'.
```

It seems that the GCC produces broken `/nix/store/h1lbygjcrz6xyvfbd8hg8q0cpdymibml-musl-x86_64-unknown-linux-musl-1.2.3/lib/ld-musl-x86_64.so.1` link.

```
ls -la /nix/store/h1lbygjcrz6xyvfbd8hg8q0cpdymibml-musl-x86_64-unknown-linux-musl-1.2.3/lib/                                                                                                   aleksey@hunkybook
total 7552
dr-xr-xr-x  19 root  wheel      608 Jan  1  1970 .
dr-xr-xr-x   4 root  wheel      128 Jan  1  1970 ..
-r--r--r--   1 root  wheel     4992 Jan  1  1970 Scrt1.o
-r--r--r--   1 root  wheel     4992 Jan  1  1970 crt1.o
-r--r--r--   1 root  wheel     2856 Jan  1  1970 crti.o
-r--r--r--   1 root  wheel     2800 Jan  1  1970 crtn.o

ls: /nix/store/h1lbygjcrz6xyvfbd8hg8q0cpdymibml-musl-x86_64-unknown-linux-musl-1.2.3/lib//ld-musl-x86_64.so.1: Permission denied
lrwx------   1 root  wheel        7 Jan  1  1970 ld-musl-x86_64.so.1
-r--r--r--   1 root  wheel  2992102 Jan  1  1970 libc.a
lrwxr-xr-x   1 root  wheel        7 Jan  1  1970 libc.musl-x86_64.so.1 -> libc.so
-r-xr-xr-x   1 root  wheel   799120 Jan  1  1970 libc.so
-r--r--r--   1 root  wheel        8 Jan  1  1970 libcrypt.a
-r--r--r--   1 root  wheel        8 Jan  1  1970 libdl.a
-r--r--r--   1 root  wheel        8 Jan  1  1970 libm.a
-r--r--r--   1 root  wheel        8 Jan  1  1970 libpthread.a
-r--r--r--   1 root  wheel        8 Jan  1  1970 libresolv.a
-r--r--r--   1 root  wheel        8 Jan  1  1970 librt.a
-r--r--r--   1 root  wheel        8 Jan  1  1970 libutil.a
-r--r--r--   1 root  wheel        8 Jan  1  1970 libxnet.a
-r--r--r--   1 root  wheel     9552 Jan  1  1970 rcrt1.o
```

**Comment by szlend** [comment]
@ElvishJerricco I was able to fix the issue with `ld.so`. It looks like it's compiled with `RPATH`set to `""` for some reason, which causes an assertion to fail:

```
Inconsistency detected by ld.so: get-dynamic-info.h: 126: elf_get_dynamic_info: Assertion 'info[DT_RUNPATH] == NULL' failed!
```

I'm not sure where the empty rpath is introduced, but an easy temporary workaround is to path the resulting library:
```
patchelf --remove-rpath <path_to_ld.so>
```

This can be done in the patch phase of glibc.

**Comment by tanshihaj** [comment]
Btw, I've managed to build `pkgsCross.aarch64-multiplatform.gcc` upgrading it to version 12.1.0 (already present in nixpkgs, but default `gcc` for aarch64-darwin is 11.2.0). I will try to check if binaries produced by this compiler is workable and after that I think we can try to find since which version of gcc it begin to build.

**Comment by G3zz** [comment]
@tanshihaj how did you get on?

**Comment by tanshihaj** [comment]
Well, except fact on 12 gcc it build I didn't get much further, unfortunately.

**Comment by zhaofengli** [comment]
Ok, I figured it out. The problem is three-parts:

1. `ENABLE_DARWIN_AT_RPATH` not defined
2. `libgcc` breakage with gcc 11.3 (https://github.com/NixOS/nixpkgs/pull/171792)
3. `Assertion 'info[DT_RUNPATH] == NULL' failed` in rtld

Let's discuss one by one:

## `ENABLE_DARWIN_AT_RPATH` not defined

The configure script does appears to be broken, and the problem does not occur for gcc 11.3 with [the patchset used by Homebrew](https://github.com/Homebrew/formula-patches/blob/8184603db1db7da12d0fbfa47e1329ba0e21558e/gcc/gcc-11.3.0-arm.diff).

## `libgcc` breakage with gcc 11.3

https://github.com/NixOS/nixpkgs/pull/171792 downgraded gcc11 to 11.2 because it broke the standalone `libgcc`:

```
make: *** No rule to make target 'emutls_s.o', needed by 'libemutls_w.a'.  Stop.
```

Because we build the standalone `libgcc` with `--disable-shared`, `libemutls_s.o` is [natually not built](https://github.com/gcc-mirror/gcc/blob/2d280e7eafc086e9df85f50ed1a6526d6a3a204d/libgcc/fixed-obj.mk#L29-L32). I wrote [a small patch]() to fix it. 

## `Assertion 'info[DT_RUNPATH] == NULL' failed` in rtld

The assertion occurs when loading rtld itself:

```console
[macos:nixpkgs]$ nix-build -A pkgsCross.aarch64-multiplatform.stdenv.cc.libc
/nix/store/89x0fgys5n5whsqvs72gazljzjg8xgdi-glibc-aarch64-unknown-linux-gnu-2.35-163
[linux:nixpkgs]$ /nix/store/89x0fgys5n5whsqvs72gazljzjg8xgdi-glibc-aarch64-unknown-linux-gnu-2.35-163/lib/ld-linux-aarch64.so.1 
Inconsistency detected by ld.so: ./get-dynamic-info.h: 118: elf_get_dynamic_info: Assertion `info[DT_RUNPATH] == NULL' failed!
```

[The assertion](https://github.com/bminor/glibc/blob/f94f6d8a3572840d3ba42ab9ace3ea522c99c0c2/elf/get-dynamic-info.h#L118-L119) makes sense because rtld itself is not supposed to have a RPATH or RUNPATH. But why does it have a RUNPATH? Let's see:

```
[macos:nixpkgs]$ readelf -a /nix/store/89x0fgys5n5whsqvs72gazljzjg8xgdi-glibc-aarch64-unknown-linux-gnu-2.35-163/lib/ld-linux-aarch64.so.1 | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: []
```

Wait, it's empty! This is a bit suspicious... Maybe it was shrinked during the fixup phase?

```
[macos:nixpkgs]$ nix-build -E 'with import ./. {}; pkgsCross.aarch64-multiplatform.stdenv.cc.libc.overrideAttrs (_: { dontPatchELF = 1; })'
/nix/store/rk7m7bhka5lsn9snp2zqnmpsc1bs00sy-glibc-aarch64-unknown-linux-gnu-2.35-163
[macos:nixpkgs]$ readelf -a result/lib/ld-linux-aarch64.so.1 | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/9rb5qaba71mkgfgd8wfqg03cmi46xarg-apple-framework-CoreFoundation-11.0.0/Library/Frameworks]
```

Indeed! Pretty amusing to see a Linux ELF with CoreFoundation in the RUNPATH. The culprit is [this](https://github.com/NixOS/nixpkgs/blob/d9f2904cb7a36377c75beefa04eb2fc9f43f198d/pkgs/build-support/bintools-wrapper/ld-wrapper.sh#L227-L231):

```bash
# This is outside the DONT_SET_RPATH branch because it's more targeted and we
# usually want it (on Darwin) even if DONT_SET_RPATH is set.
if [ -n "${NIX_COREFOUNDATION_RPATH:-}" ]; then
  extraAfter+=(-rpath $NIX_COREFOUNDATION_RPATH)
fi
```

`NIX_COREFOUNDATION_RPATH` is set [here](https://github.com/NixOS/nixpkgs/blob/02ad70f21fedf9695081524f3988fd362f80304a/pkgs/stdenv/darwin/default.nix#L679). Let's try clearing it:

```console
[macos:nixpkgs]$ cat glibc-hack.nix
let
  pkgs = import ./. {};
  stdenv = pkgs.pkgsCross.aarch64-multiplatform.stdenv;
  libc = stdenv.cc.libc.overrideAttrs (old: {
    dontPatchELF = 1;
    preBuild = ''
      export NIX_COREFOUNDATION_RPATH=
    '';
  });
in libc
[macos:nixpkgs]$ nix-build glibc-hack.nix
/nix/store/fqsakyml0ll8y4byc3qj6yb9k78bnm4x-glibc-aarch64-unknown-linux-gnu-2.35-163
[linux:nixpkgs]$ /nix/store/fqsakyml0ll8y4byc3qj6yb9k78bnm4x-glibc-aarch64-unknown-linux-gnu-2.35-163/lib/ld-linux-aarch64.so.1 
/nix/store/fqsakyml0ll8y4byc3qj6yb9k78bnm4x-glibc-aarch64-unknown-linux-gnu-2.35-163/lib/ld-linux-aarch64.so.1: missing program name
Try '/nix/store/fqsakyml0ll8y4byc3qj6yb9k78bnm4x-glibc-aarch64-unknown-linux-gnu-2.35-163/lib/ld-linux-aarch64.so.1 --help' for more information.
```

Things are looking good. Let's apply [the fix]() and verify our work:

```
[macos:nixpkgs]$ nix-build -A pkgsCross.aarch64-multiplatform.hello
/nix/store/npy3b4i7iily58r3xp4mh92nn8phnah6-hello-aarch64-unknown-linux-gnu-2.12.1
[linux:nixpkgs]$ /nix/store/npy3b4i7iily58r3xp4mh92nn8phnah6-hello-aarch64-unknown-linux-gnu-2.12.1/bin/hello
Hello, world!
```

Success!

## PRs

Since the freeze period for critical packages has begun for 22.11, let's apply the fix in two parts:

1. Fix `NIX_COREFOUNDATION_RPATH` for `glibc`: #196564.
2. Bump `gcc11` on Darwin to 11.3 with the new patchset and `libgcc` fix: #196565. This will probably have to wait until branch-off.

**Comment by mstone** [comment]
Wow, thanks @zhaofengli for this amazing and persistent debugging — it will be really exciting to have this fixed, pending merging and testing!

**Comment by cideM** [comment]
For what it's worth, I used the branch on my M1 MacBook Pro to build https://github.com/cideM/nix-docker which is GNU Hello World put in a Docker container using cross compilation It Just Worked™ @zhaofengli

**Comment by mstone** [comment]
@zhaofengli — congratulations, it looks like both your patches have been merged!

**Comment by mstone** [comment]
`nix build nixpkgs/e9f52e843edb26059593be60d5c8cb237dff87ba#pkgsCross.aarch64-multiplatform.gcc` now succeeds so I think this is the home stretch!
