### ISSUE TITLE
python39Packages.envisage fails build/test:AttributeError: 'NoneType' object has no attribute 'shell'

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#138393]
`python39Packages.envisage` fails to build as: https://hydra.nixos.org/build/153066757

```
============ 20 failed, 205 passed, 4 skipped, 7 warnings in 4.12s =============
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/build/envisage-6.0.1/envisage/plugins/ipython_kernel/kernelapp.py", line 188, in close
    self.close_shell()
  File "/build/envisage-6.0.1/envisage/plugins/ipython_kernel/kernelapp.py", line 205, in close_shell
    shell = self.kernel.shell
AttributeError: 'NoneType' object has no attribute 'shell'
```

### Notify maintainers

@knedlsepp 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python39Packages.envisage
```

**Comment by trofi** [comment]
Closing as INVALID
