### ISSUE TITLE
dropbox can't start due to missing libGL.so.1

### ISSUE THREAD

**Issue by timbertson** [NixOS/nixpkgs#13859]
## Basic info

To make sure that we are on the same page:

* Kernel: (run `uname -a`)

```
Linux meep 4.4.3-300.fc23.x86_64 #1 SMP Fri Feb 26 18:45:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 23 (Twenty Three)
Release:	23
Codename:	TwentyThree
```

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.10

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"16.09pre78567.370c318"

## Describe your issue here

When I run `dropbox` (at `/nix/store/c8s3jycdcgvdwcxnnc2w5fdhhrbm7304-dropbox-3.14.7/bin/dropbox`), I get:

```
Couldn't start Dropbox.
This is usually because of a permissions error. Storing your home folder on a network share can also cause an error.

Get more help at https://www.dropbox.com/c/help/permissions_error

Please contact Dropbox support with the following info for help:

/tmp/dropbox_errorSUnHYs.txt
```

Checking that log file, it ends with:

```
(...)
Traceback (most recent call last):
  File "dropbox/client/main.py", line 4698, in main_startup
  File "dropbox/client/main.py", line 2043, in run
  File "ui/common/uikit.py", line 401, in create_ui_kit
  File "dropbox/client/ui/qt/__init__.py", line 28, in <module>
  File "PyQt5/QtWidgets.py", line 14, in <module>
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

This looks exactly like #11728, even though that's been fixed for some time. Looks like @bendlas and @ttuegel fixed this last time - any ideas?

**Comment by bendlas** [comment]
I think the problem is, that dropbox ships with its own pyqt, which also depends on libGL:
```
$ ldd /nix/...../opt/dropbox/PyQT5.QtWidgets.so
...
libGL.so.1 => /run/opengl-driver/lib/libGL.so.1 (0x00007ffff642a000)
...
```
I'll try to build dropbox against our own pyqt...

**Comment by bendlas** [comment]
Ok, linking up our PyQt .so files against the python interpreter embedded with dropbox doesn't really seem to work (and it would be a pretty crazy thing to ship anyway). 
I think applying https://github.com/bendlas/nixpkgs/commit/a6a85b82b43fa0972b7b02ff07176bfb455a0f6c should fix it. @ttuegel ?

**Comment by bendlas** [comment]
@timbertson could you verify, that dropbox from the 15.09 channel already works for you?

**Comment by timbertson** [comment]
@bendlas Unfortunately it doesn't, but it's for a different reason:

```
Traceback (most recent call last):
  File "dropbox/client/main.py", line 4698, in main_startup
  File "dropbox/client/main.py", line 2043, in run
  File "ui/common/uikit.py", line 401, in create_ui_kit
  File "dropbox/client/ui/qt/__init__.py", line 13, in <module>
  File "PyQt5/QtCore.py", line 14, in <module>
ImportError: /nix/store/rb22kxyp4jj8359ia2jrka92c2qdr61q-dropbox-3.14.7-bin/opt/dropbox/PyQt5.QtCore.so: undefined symbol: _ZNK11QMetaObject10Connection18isConnected_helperEv
```

Also from that same log, it printed out:

```
LD_LIBRARY_PATH: u'/nix/store/3piabk8nz65d46w5vagfygh7fxz0mpr3-dbus-libs-1.8.20/lib:/nix/store/f1p2lhaa5aj3g4ca9clvp43wyy7ymm6m-gcc-wrapper-4.9.3/lib:/nix/store/f2v2q0v7yx8w58lrkhxavp7qxc4qagrl-glib-2.44.1/lib:/nix/store/pn4q9wrbhs3j2fi36qp4gijfq8k0l6gg-libdrm-2.4.64/lib:/nix/store/siijhvj6aky6xln7115ijhnkfab37ra6-libffi-3.2.1/lib:/nix/store/1dijwd728zjnq2n1s81230m30cbbci3r-libICE-1.0.9/lib:/nix/store/xshvi3x91jcj4qgvacq8xmvdf7fnicvf-libSM-1.2.2/lib:/nix/store/cq2igqdkzx6nadsw9zy6807l5nn9zx9w-libX11-1.6.3/lib:/nix/store/720m8xjnl49yigx6zwc5fklbbw6ydy0b-libXmu-1.1.2/lib:/nix/store/0qbm6w87r0b01bzsa592g91nykwr41ax-ncurses-5.9/lib:/nix/store/gzybk8js1zi9d21jscc96vgm9gfsximd-popt-1.16/lib:/nix/store/gai2s0fq54m2idf2f53pn1yjnj6h5bk7-qtbase-5.5.0/lib:/nix/store/v4acq7mi9wfpk67y5fr6kwq2bwhyw7vw-qtdeclarative-5.5.0/lib:/nix/store/kx36rsf2f95qimbcpvvvvyra9ljv7fm5-qtwebkit-5.5.0/lib:/nix/store/v737f8si5ch9bccd05a5rjlf0jrr1k29-zlib-1.2.8/lib:/nix/store/y524saq63640d4rhlfq2mxqgnsvqd7fc-mesa-noglu-10.6.9/lib'
```

So then:

```
$ env LD_LIBRARY_PATH='(...)' ldd /nix/store/rb22kxyp4jj8359ia2jrka92c2qdr61q-dropbox-3.14.7-bin/opt/dropbox/PyQt5.QtWidgets.so | grep libGL
	libGL.so.1 => /nix/store/y524saq63640d4rhlfq2mxqgnsvqd7fc-mesa-noglu-10.6.9/lib/libGL.so.1 (0x00007fa08c155000)

```

Adding this lib path to the nixpkgs unstable binary manually does work:

```
env LD_LIBRARY_PATH='/nix/(...)-mesa-noglu-10.6.9/lib' /nix/(...)-dropbox-3.14.7/bin/dropbox
```

..so I'm pretty confident that your patch will fix my issue.

**Comment by vcunat** [comment]
No, that patch isn't a good approach. IIRC it won't work if the machine is using some different kernel driver, e.g. a proprietary one. See #9415 for libGL on non-NixOS.

**Comment by bendlas** [comment]
@vcunat how about we leave the issue open, until we know how to fix it?

**Comment by vcunat** [comment]
That issue *is* open, and it has some "solutions", although not very user-friendly ones. Note that this has really not much to do with dropbox; various programs use libGL nowadays.
