### ISSUE TITLE
Nvidia driver 361.28 makes programs crash

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#13942]
Programs crash at startup or exit, e.g. some XFCE programs (e.g. Thunar, xfce4-terminal) crash on exit only possibly after forking off a child and trying to exit, and others (e.g. VLC) crash on startup. This must be related to Nvidia drivers, the issue does not appear when using Nouveau. It is probably a regression from 358.16 -> 361.28 (5b3c61ea5feaffb37546cf35bccf838c4534d678) but I didn't verify yet.

Backtrace for xfce4-terminal (crash on exit after fork):
```
Thread 1 "xfce4-terminal" received signal SIGSEGV, Segmentation fault.
0x00007ffff37bbec1 in __eglTeardownVendor () from /run/opengl-driver/lib/libEGL.so.1
(gdb) bt
#0  0x00007ffff37bbec1 in __eglTeardownVendor () from /run/opengl-driver/lib/libEGL.so.1
#1  0x00007ffff7de9398 in _dl_fini () from /nix/store/h1vm2sdhphj52p0bhf9si7szviw2km7z-glibc-2.23/lib/ld-linux-x86-64.so.2
#2  0x00007ffff55d1a39 in __run_exit_handlers () from /nix/store/h1vm2sdhphj52p0bhf9si7szviw2km7z-glibc-2.23/lib/libc.so.6
#3  0x00007ffff55d1a85 in exit () from /nix/store/h1vm2sdhphj52p0bhf9si7szviw2km7z-glibc-2.23/lib/libc.so.6
#4  0x00007ffff55bc86c in __libc_start_main () from /nix/store/h1vm2sdhphj52p0bhf9si7szviw2km7z-glibc-2.23/lib/libc.so.6
#5  0x000000000040fbe9 in _start ()
```

Backtrace for VLC (crash at startup, does not start):
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe76aaec1 in __eglTeardownVendor () from /run/opengl-driver/lib/libEGL.so.1
(gdb) bt
#0  0x00007fffe76aaec1 in __eglTeardownVendor () from /run/opengl-driver/lib/libEGL.so.1
#1  0x00007ffff7dedc71 in _dl_close_worker () from /nix/store/h1vm2sdhphj52p0bhf9si7szviw2km7z-glibc-2.23/lib/ld-linux-x86-64.so.2
#2  0x00007ffff7dee7ce in _dl_close () from /nix/store/h1vm2sdhphj52p0bhf9si7szviw2km7z-glibc-2.23/lib/ld-linux-x86-64.so.2
#3  0x00007ffff7de8c64 in _dl_catch_error () from /nix/store/h1vm2sdhphj52p0bhf9si7szviw2km7z-glibc-2.23/lib/ld-linux-x86-64.so.2
#4  0x00007ffff779b4ed in _dlerror_run () from /nix/store/h1vm2sdhphj52p0bhf9si7szviw2km7z-glibc-2.23/lib/libdl.so.2
#5  0x00007ffff779b01f in dlclose () from /nix/store/h1vm2sdhphj52p0bhf9si7szviw2km7z-glibc-2.23/lib/libdl.so.2
#6  0x00007ffff71875ce in AllocatePluginDir () from /nix/store/3x5bgvnk4pm31aq19m780a0pdpm6ppaw-vlc-2.2.2/lib/libvlccore.so.8
#7  0x00007ffff7187244 in AllocatePluginDir () from /nix/store/3x5bgvnk4pm31aq19m780a0pdpm6ppaw-vlc-2.2.2/lib/libvlccore.so.8
#8  0x00007ffff71877a4 in AllocatePluginPath () from /nix/store/3x5bgvnk4pm31aq19m780a0pdpm6ppaw-vlc-2.2.2/lib/libvlccore.so.8
#9  0x00007ffff7187d6a in module_LoadPlugins () from /nix/store/3x5bgvnk4pm31aq19m780a0pdpm6ppaw-vlc-2.2.2/lib/libvlccore.so.8
#10 0x00007ffff71108aa in libvlc_InternalInit () from /nix/store/3x5bgvnk4pm31aq19m780a0pdpm6ppaw-vlc-2.2.2/lib/libvlccore.so.8
#11 0x00007ffff7bc2b1b in libvlc_new () from /nix/store/3x5bgvnk4pm31aq19m780a0pdpm6ppaw-vlc-2.2.2/lib/libvlc.so.5
#12 0x0000000000401447 in main ()
```

**Comment by ambrop72** [comment]
And indeed reverting the 3 latest commits for nvidia-x11 resolved the issue for me (bringing the driver back to 358.16).

```
git revert 36bad18d574305b6a99afb5b9bf59361e4883e14 8c6cf0ca7ca86e48891076b05444846174a36d1e 5b3c61ea5feaffb37546cf35bccf838c4534d678
```

**Comment by codyopel** [comment]
> The GLVND libraries do work, but you must create version symlinks to specific libraries.  The libraries being `libGLX_nvidia.so.0`, `libEGL_nvidia.so.0`, `libGLESv1_CM_nvidia.so.1`, `libGLESv2_nvidia.so.2`, & `libGL.so.1`.
> 
> https://devtalk.nvidia.com/default/topic/915640/unix-graphics-announcements-and-news/multiple-glx-client-libraries-in-the-nvidia-linux-driver-installer-package/
> 
> Fixing this will resolve the random segfaults you are encountering when libEGL looks for the library named with a specific version that doesn't exist at runtime.
>
>https://github.com/triton/triton/blob/master/pkgs/all-pkgs/nvidia-drivers/builder-generic.sh

Part of:
https://github.com/NixOS/nixpkgs/pull/12719

**Comment by vcunat** [comment]
I believe this single revert I did is enough to "fix" the issue.
