### ISSUE TITLE
nix-build fails during setuptoolsBuildPhase, but nix-shell executes it fine

### ISSUE THREAD

**Issue by freemagma** [NixOS/nixpkgs#139648]
### Describe the bug
I am working on creating a nix expression to build [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose), and was making decent progress until today. When I run `nix-build alphapose.nix`, I get the following error during setuptoolsBuildPhase

```
these derivations will be built:
  /nix/store/pdgr35jnbrxn8pajknjwarglb59jpj4x-python3.9-alphapose.drv
building '/nix/store/pdgr35jnbrxn8pajknjwarglb59jpj4x-python3.9-alphapose.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing setuptools-check-hook
Using setuptoolsCheckPhase
unpacking sources
unpacking source archive /nix/store/z4n96d7sqrh4r3nvndv1lfhwc8gxvxkm-alphapose
source root is alphapose
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file alphapose/setup.py
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
No CUDA runtime is found, using CUDA_HOME='/nix/store/vrl4kg9vafj8s6immsg4d8znrfld0szy-cudatoolkit-11.2.1'
running bdist_wheel
running build
running build_py
copying alphapose/version.py -> build/lib.linux-x86_64-3.9/alphapose
running build_ext
building 'detector.nms.soft_nms_cpu' extension
Emitting ninja build file /build/alphapose/build/temp.linux-x86_64-3.9/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[many lines omitted here]
Traceback (most recent call last):
  File "/build/alphapose/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  [some traceback lines omitted here]
  File "/nix/store/pbglpk07na7y3gnxhl5y9014awyhxl40-python3.9-pytorch-1.9.0/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 424, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/nix/store/pbglpk07na7y3gnxhl5y9014awyhxl40-python3.9-pytorch-1.9.0/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1562, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
builder for '/nix/store/pdgr35jnbrxn8pajknjwarglb59jpj4x-python3.9-alphapose.drv' failed with exit code 1
error: build of '/nix/store/pdgr35jnbrxn8pajknjwarglb59jpj4x-python3.9-alphapose.drv' failed
```

However, when I do things more manually by first calling `nix-shell alphapose.nix` then `cd alphapose && setuptoolsBuildPhase`,
it runs fine. Notably, when using this method I do NOT get the message `No CUDA runtime is found, using CUDA_HOME='/nix/store/vrl4kg9vafj8s6immsg4d8znrfld0szy-cudatoolkit-11.2.1'` which makes sense to me since I am exporting
`CUDA_HOME` in my derivation:

```nix
with import <nixpkgs> {
  config = {
    allowUnfree = true;
    cudaSupport = true;
  };
  overlays = [
    (self: super: {
      cudatoolkit = super.cudaPackages.cudatoolkit_11;
      cudnn = super.cudnn_cudatoolkit_11;
    })
  ];
};

let
  python = python3;
  cython_bbox = python.pkgs.buildPythonPackage rec {
    pname = "cython_bbox";
    version = "0.1.3";
    src = fetchFromGitHub {
      owner = "yanfengliu";
      repo = "cython_bbox";
      rev = "e7b95b6dc0933b10bd0ec02b90755a12ca996c68";
      sha256 = "09yhgngzjpfvx6ylq68h4hmdscvalw6h50kvsniwqvmnqrs94ipz";
    };

    propagatedBuildInputs = with python.pkgs; [ numpy cython ];
  };
  alphapose = python.pkgs.buildPythonPackage rec {
    name = "alphapose";

    src = ./alphapose;

    nativeBuildInputs = [ which ninja ];
    buildInputs = [ cudatoolkit ];
    propagatedBuildInputs = with python.pkgs; [
      pytorch
      torchvision
      cython
      pytest-runner
      pybind11
      cython_bbox
    ];

    preBuild = ''
      export CUDA_HOME=${cudatoolkit}
      export CUDA_PATH=${cudatoolkit}
      export PATH=${cudatoolkit}/bin:$PATH
      export LD_LIBRARY_PATH=${cudatoolkit}/lib64:$LD_LIBRARY_PATH
    '';
  };
in alphapose
```

### Steps To Reproduce
1. copy the above derivation into `alphapose.nix`
2. `git clone https://github.com/MVIG-SJTU/AlphaPose.git alphapose && cd alphapose && git pull origin pull/592/head`
3. run `nix-build alphapose.nix`

### Expected behavior
I expect nix-shell and nix-build to act similarly. I cannot tell why one errors and the other doesn't (and one finds my exported CUDA_HOME and the other doesn't)

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.68, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre318500.51bcdc4cdaa, home-manager"`
 - channels(cgunn): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sternenseemann** [comment]
`arch_list` is populated by checking the available CUDA devices which is not possible in the nix build sandbox, so it is to be expected that it doesn't succeed when using `nix-build`. Seems like you may need to set `TORCH_CUDA_ARCH_LIST` as well: <https://github.com/pytorch/pytorch/blob/8130157504e4a8d289e8cb0ae57d81da53bb037f/torch/utils/cpp_extension.py#L1582-L1615>

**Comment by SomeoneSerge** [comment]
> Seems like you may need to set TORCH_CUDA_ARCH_LIST as well: 

That's right, e.g. https://github.com/NixOS/nixpkgs/blob/95af2245a32f8e1310ad4e3bf50b76d86ddbbc0a/pkgs/development/python-modules/torchvision/default.nix#L48
