### ISSUE TITLE
Permission denied on mastodon tootctl

### ISSUE THREAD

**Issue by LEXUGE** [NixOS/nixpkgs#139722]
### Describe the bug
Seems like mastodon v3.4.1 is trying to write path cache into store.

### Steps To Reproduce
1. setup mastodon
2. `sudo su - mastodon -s /bin/sh -c "mastodon-env tootctl accounts create newuser --email newuser@example.com"`

### Expected behavior
Tootctl working

### Additional context
Upstream related issue: https://github.com/mastodon/mastodon/issues/4625
Log:
```
warning: parser/current is loading parser/ruby30, which recognizes
warning: 3.0.1-compliant syntax, but you are running 3.0.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:83:in `binwrite': Permission denied @ rb_sysopen - /nix/store/9f65kjrwqyqmda2hcf4v1fv87k7irw02-mastodon-3.4.1/tmp/cache/bootsnap/load-path-cache.531843.17862.tmp (Errno::EACCES)
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:83:in `dump_data'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:59:in `commit_transaction'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:50:in `block in transaction'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:46:in `synchronize'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:46:in `transaction'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/cache.rb:154:in `unshift_paths_locked'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/cache.rb:107:in `block in unshift_paths'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/cache.rb:107:in `synchronize'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/cache.rb:107:in `unshift_paths'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/change_observer.rb:20:in `unshift'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/engine.rb:577:in `block (2 levels) in <class:Engine>'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/engine.rb:576:in `reverse_each'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/engine.rb:576:in `block in <class:Engine>'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `run'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:50:in `each'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:415:in `call'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:50:in `each'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:415:in `call'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /nix/store/snq91p909l4dj3b6h4px25175kn46jlk-ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/application.rb:384:in `initialize!'
	from /nix/store/9f65kjrwqyqmda2hcf4v1fv87k7irw02-mastodon-3.4.1/config/environment.rb:5:in `<top (required)>'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	from /nix/store/9f65kjrwqyqmda2hcf4v1fv87k7irw02-mastodon-3.4.1/lib/mastodon/media_cli.rb:4:in `<top (required)>'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	from /nix/store/9f65kjrwqyqmda2hcf4v1fv87k7irw02-mastodon-3.4.1/lib/cli.rb:4:in `<top (required)>'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
	from /nix/store/wyllvki4q0byi4gw45y0yc632jn5p1rm-mastodon-gems-3.4.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	from /etc/profiles/per-user/mastodon/bin/tootctl:5:in `<main>'
```

### Notify maintainers
@happy-river

**Comment by LEXUGE** [comment]
```nix
pkgs.mastodon.overrideAttrs (oldAttrs: rec {
      postPatch = ''
        substituteInPlace config/boot.rb --replace "load_path_cache:      true," "load_path_cache:      false," \
          --replace "autoload_paths_cache: true," "autoload_paths_cache: false,"
      '';
    })
```
This works around the issue.

**Comment by turion** [comment]
For me, this works. I believe I have 3.5.3.

**Comment by erictapen** [comment]
@LEXUGE  I suppose this can be closed?
