### ISSUE TITLE
Virtscreen fails to launch

### ISSUE THREAD

**Issue by TheOPtimal** [NixOS/nixpkgs#139861]
### Describe the bug
Virtscreen fails to launch because of some GLIBC version not found error

### Steps To Reproduce
1. Try to launch virtscreen

### Expected behavior
Virtscreen to launch and show me the UI.

### Additional context
Full error:

```
Traceback (most recent call last):
  File "/nix/store/y1xqipg9cn1j434197p35a2dhfhh1k85-virtscreen-0.3.1/bin/.virtscreen-wrapped", line 6, in <module>
    from virtscreen.__main__ import main
  File "/nix/store/y1xqipg9cn1j434197p35a2dhfhh1k85-virtscreen-0.3.1/lib/python3.8/site-packages/virtscreen/__main__.py", line 21, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /nix/store/wvgyhnd3rn6dhxzbr5r71gx2q9mhgshj-glibc-2.32-48/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/yijjamlqw2b7yfj5731z35yyhqdmdb4c-libX11-1.7.2/lib/libX11.so.6)
```

### Notify maintainers

@borisbabic

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52-1-MANJARO, Manjaro Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre19700101_b4736bd`
 - channels(optimal): `"home-manager, nixgl"`
 - channels(root): `"nixpkgs-21.11pre302881.314f595ab1c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- virtscreen
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
probably this issue https://github.com/NixOS/nixpkgs/issues/84043

getting your channels in sync will fix it as once you do that you'll not have 2 glibc versions

**Comment by TheOPtimal** [comment]
Thanks.
