### ISSUE TITLE
sqlite update broke pythonPackages.sqlalchemy[7-9]

### ISSUE THREAD

**Issue by lsix** [NixOS/nixpkgs#14026]
## Basic info

To make sure that we are on the same page:
- Kernel: `Linux 4.4.5 #1-NixOS SMP Wed Mar 9 23:35:58 UTC 2016 x86_64 GNU/Linux`
- System: `16.03.171.0b5026f`
- Nix version: `nix-env (Nix) 1.11.2`
- Nixpkgs version: `master`

d86633386f2f2b786628b3ca14609a710cc6b993 broke legacy `sqlalchemy` packages (only tested with the `pythonPackages`-set).

``` bash
$ git bisect start 1941c806106c64ffe3b37734d23b8e3835b86c8f 36506df7fe1e087fd0af99f8eb6ee71759fffa81
$ git bisect run nix-build -A python27Packages.sqlalchemy7
…
d86633386f2f2b786628b3ca14609a710cc6b993 is the first bad commit
```

Multiple options to solve this:
- revert the commit (an update will eventually have to be done)
- make sure no-one depends on sqlalchemy legacy versions (this would be the best choice, but can require a big amount of work)
- re-introduce an outdated `sqlite` version only used by `sqlalchemy` legacy version (I’ll prepare a PR shortly that follows this path)

cc @edolstra

**Comment by lancelotsix** [comment]
To be complete, the build problem is a test failure:

```
patching script interpreter paths in /nix/store/v8lq5q24j1isy0i5dclg2kiiwrbmv45z-python2.7-SQLAlchemy-0.7.10
running install tests
/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./lib/sqlalchemy/dialects/access/base.py:163: SAWarning: The access dialect is not yet ported to SQLAlchemy 0.6/0.7
  super(AccessDialect, self).__init__(**params)
....SSS.......S.....................SS.....................................................................................................S......SSS.SSS...............................SS.SS.....
.......SSSS.............S.......SSS.SS...............SSS..........S.......SSSSSS.SSSSS......................SSSSSSSS.SSS.SSSSS....................................................................
...........................................S.............................S..S.....................................................S..................SS...........S..S.S..S..SSS.S.S.S....SS......
.............................S...SS....SSSS..................SS......S.S....SS.SS....S.SS.........................................................................................................
..................................................................................................................................................................................................
..................................................................................................................................................................................................
..................................................................................................................................................................................................
..................................................................................................................................................................................................
...................................................................................................................................................................................................................................................................................................................................................................................................$.................................................................................................................................................................................................$...................................................................................................................................S.............................................................$....................................................................................................................................................................................S............$.................................................................................................................................................................................................$.................................................................................................................................................................................................$.................................................................................................................................................................................................$.................................S.............S..S.................S...................................................................................SSSSSSSS...SSSSSSS...S..SS...SS..........$....S.............................S...........................................................................................................S..................................................$.......................................................................................................S...SS...S.S...S....SS....................................................................$................................................................................................................................................................................................S$.....S...............FE...........................S..........S..................S..SSS...........................................................................................................$....................................................SSSSSS
======================================================================
ERROR: test.sql.test_query.QueryTest.test_column_accessor_sqlite_translated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/4rdqlx810h9484h7cricwmyinkm9x3r6-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 1, in <lambda>
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/lib/exclusions.py", line 45, in decorate
    return fn(*args, **kw)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/sql/test_query.py", line 800, in test_column_accessor_sqlite_translated
    eq_(r['query_users.user_id'], 1)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./lib/sqlalchemy/engine/base.py", line 2615, in __getitem__
    processor, obj, index = self._parent._key_fallback(key)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./lib/sqlalchemy/engine/base.py", line 2834, in _key_fallback
    expression._string_or_unprintable(key))
NoSuchColumnError: "Could not locate column in row for column 'query_users.user_id'"

======================================================================
FAIL: test.sql.test_query.QueryTest.test_column_accessor_sqlite_raw
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/4rdqlx810h9484h7cricwmyinkm9x3r6-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 1, in <lambda>
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/lib/exclusions.py", line 45, in decorate
    return fn(*args, **kw)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/sql/test_query.py", line 783, in test_column_accessor_sqlite_raw
    assert 'user_id' not in r
AssertionError

----------------------------------------------------------------------
Ran 4069 tests in 224.118s

FAILED (SKIP=145, errors=1, failures=1)
builder for ‘/nix/store/7clj3bcixsjw8pl1rq65bv75n2kn8nwh-python2.7-SQLAlchemy-0.7.10.drv’ failed with exit code 1
error: build of ‘/nix/store/7clj3bcixsjw8pl1rq65bv75n2kn8nwh-python2.7-SQLAlchemy-0.7.10.drv’ failed
```

I also checked, we cannot downgrade sqlite only for few pythonPackages, the entire python (and package set) have to be changed.

Any preferred way to go?

**Comment by globin** [comment]
(We should check if we still need this version, have it removed locally for virtmanager, virtinst as it isn't used, but haven't had the time to push that)

**Comment by lancelotsix** [comment]
Yes, this is the preferred way to go. I began that but did not finish it yet, and it impacts some important parts (it causes xen to fail) I would prefer not to break because of unsufficient testing from me. This is in progress but could require some time to complete.

**Comment by domenkozar** [comment]
FYI xen already fails on `16.03`

**Comment by pSub** [comment]
FYI: I switched away from sqlalchemy7 in `pythonPackages.radicale` yesterday.

**Comment by joachifm** [comment]
Apart from virtinst, acd_cli, beaker, coilmq, geeknote are the only revdeps of sqlalchemy7, as far as I can tell.

**Comment by lancelotsix** [comment]
I openned #14110 to do some cleanup on sqlalchemy7. There still is `buildbot` that explicitly require `sqlalchemy7`.

The same work will have to be done for `sqlalchemy8` and `sqlalchemy9`.

**Comment by FRidh** [comment]
This should have remained open.

**Comment by FRidh** [comment]
Using an older version of sqlite requires overriding the derivations of the interpreters.

**Comment by copumpkin** [comment]
See #8909
