### ISSUE TITLE
wallabag is not loading and console does not work

### ISSUE THREAD

**Issue by benneti** [NixOS/nixpkgs#140408]
### Describe the bug
Wallabag is not working (the bug could also be me...)

### Steps To Reproduce
1. setup phpfpm for wallabag
2. create a config
3. rebuild nixos

### Expected behavior
Wallabag should work and console should also work.

For the php environment I use and how I call the console see additional details.

Console output I get:
```
Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
Did you forget a "use" statement for another namespace? in /nix/store/s0f8n75h4wraami6fz6l5b1rs58a1x3m-wallabag-2.4.2/app/AppKernel.php:52
Stack trace:
#0 /nix/store/s0f8n75h4wraami6fz6l5b1rs58a1x3m-wallabag-2.4.2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(493): AppKernel->registerBundles()
#1 /nix/store/s0f8n75h4wraami6fz6l5b1rs58a1x3m-wallabag-2.4.2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /nix/store/s0f8n75h4wraami6fz6l5b1rs58a1x3m-wallabag-2.4.2/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#3 /nix/store/s0f8n75h4wraami6fz6l5b1rs58a1x3m-wallabag-2.4.2/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\Framew in /nix/store/s0f8n75h4wraami6fz6l5b1rs58a1x3m-wallabag-2.4.2/app/AppKernel.php on line 52
```

### Additional context
https://git.tissot.de/benneti/nixos/src/branch/master/profiles/server/wallabag/default.nix

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.6, NixOS, 21.05.20210923.d22c3a6 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210830_50a3586`
 - nixpkgs: `/nix/store/05w190gfgrvid91gqs68wj8arnbyxqd0-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: @mweinelt @schneefux 
# a list of nixos modules affected by the problem
module:
```

**Comment by benneti** [comment]
nevermind I forgot the --env=prod argument...
