### ISSUE TITLE
Setting environment variables during bootctl setup

### ISSUE THREAD

**Issue by michaelbarrington** [NixOS/nixpkgs#141715]
### Describe the bug
With the following in configuration.nix:

```
boot.loader.systemd-boot.enable = true;
boot.loader.efi.canTouchEfiVariables = true;
```
And attempting to install to non-GPT formatted disk, the following is observed:
```
File system "/dev/block/8:18" is not on a GPT partition table.                                                                                                                
Traceback (most recent call last):                                                                                                                                            
  File "/nix/store/hskyrbyld4l73czpfzjd1kjk03xnvn47-systemd-boot", line 274, in <module>                                                                                      
    main()                                                                                                                                                                    
  File "/nix/store/hskyrbyld4l73czpfzjd1kjk03xnvn47-systemd-boot", line 212, in main                                                                                          
    subprocess.check_call(["/nix/store/n5j5fjn60nhck658j9ab84k8n9z24n1r-systemd-247.6/bin/bootctl", "--path=/boot", "install"])                                               
  File "/nix/store/32q6ryrb860sksdi1al5djg3pgcpq92l-python3-3.8.11/lib/python3.8/subprocess.py", line 364, in check_call                                                      
    raise CalledProcessError(retcode, cmd)                                                                                                                                    
subprocess.CalledProcessError: Command '['/nix/store/n5j5fjn60nhck658j9ab84k8n9z24n1r-systemd-247.6/bin/bootctl', '--path=/boot', 'install']' returned non-zero exit status 1.
```

### Steps To Reproduce
See above. I can force this manually by setting a not-terribly-well-documented systemd environment variable:
```
[root@nixos:~]# SYSTEMD_RELAX_ESP_CHECKS=1 /nix/store/n5j5fjn60nhck658j9ab84k8n9z24n1r-systemd-247.6/bin/bootctl --path /mnt/boot install                                     
Copied "/nix/store/n5j5fjn60nhck658j9ab84k8n9z24n1r-systemd-247.6/lib/systemd/boot/efi/systemd-bootx64.efi" to "/mnt/boot/EFI/systemd/systemd-bootx64.efi".                   
Copied "/nix/store/n5j5fjn60nhck658j9ab84k8n9z24n1r-systemd-247.6/lib/systemd/boot/efi/systemd-bootx64.efi" to "/mnt/boot/EFI/BOOT/BOOTX64.EFI".                              
Random seed file /mnt/boot/loader/random-seed successfully written (512 bytes).                                                                                               
Created EFI boot entry "Linux Boot Manager".                                                                                                                                  
```
This was how I was able to do the original setup for the Arch install I'm hoping to replace with NixOS. 

### Expected behavior
Honestly this is (I hope) just a rocky start to learning Nix. After several days of research and trying to grok the nixpkgs source I had hoped the following or some variant (`wrapProgram` or similar) would  solve this:

```nix
  # does not work; I'm not even convinced it's being evaluated
  system.build.installBootLoader = let 
    old = import <nixpkgs/nixos/modules/system/boot/loader/systemd-boot/systemd-boot.nix> {}; 
    in pkgs.writeShellScriptBin "systemd-boot" ''
       SYSTEMD_RELAX_ESP_CHECKS=1 exec ${old}
    ''; 
```
But I'm at this point at a loss and almost ready to abandon the effort because I can't get the installer to proceed (though having nix alongside pacman has been great, I'm really hoping I can fully convert). Any insight into how to most correctly wrap/overlay this would be most appreciated.

**Comment by accelbread** [comment]
For anybody else who passes by, here is a fix that does not involve copying the systemd-boot module into your config.

Add this to your config:

```nix
systemd.package = pkgs.runCommand pkgs.systemd.name
  {
    inherit (pkgs.systemd) outputs passthru meta;
    nativeBuildInputs = [ pkgs.makeBinaryWrapper ];
  } ''
  cp -r ${pkgs.systemd} $out
  ln -s ${pkgs.systemd.man} $man
  ln -s ${pkgs.systemd.dev} $dev
  chmod -R u+w $out
  wrapProgram $out/bin/bootctl --set SYSTEMD_RELAX_ESP_CHECKS 1
'';
```

I ran into a similar issue where SYSTEMD_RELAX_ESP_CHECKS is needed (my /boot is mounted with FUSE), and fixed it using the above.
