### ISSUE TITLE
Graphor

### ISSUE THREAD

**Issue by Narice** [NixOS/nixpkgs#142459]
**Project description**
Gaphor is a UML and SysML modeling application written in Python. It is designed to be easy to use, while still being powerful. Gaphor implements a fully-compliant UML 2 data model, so it is much more than a picture drawing tool. You can use Gaphor to quickly visualize different aspects of a system as well as create complete, highly complex models.

**Metadata**

* homepage URL: https://gaphor.org/
* source URL: https://github.com/gaphor/gaphor
* license: apache-2.0
* platforms: unix, linux, darwin, windows

**Comment by WolfangAukang** [comment]
Having issues building one of the dependencies of this project (`generic`):

```
·> nix-build -A python38Packages.generic                                                                                                                                                                                   [73/1846]
this derivation will be built:
  /nix/store/rf811ysbscqjwp58iphjdpq163b89a5j-python3.9-generic-1.0.0.drv
building '/nix/store/rf811ysbscqjwp58iphjdpq163b89a5j-python3.9-generic-1.0.0.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/yr9cr89bxaqrkhvlfbacl387xm1njfzk-generic-1.0.0.tar.gz
source root is generic-1.0.0
setting SOURCE_DATE_EPOCH to timestamp 1574110272 of file generic-1.0.0/README.md
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip
with sudo, you should use sudo's -H flag.
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /build/pip-ephem-wheel-cache-226w2549
Created temporary directory: /build/pip-req-tracker-iqeybriv
Initialized build tracking at /build/pip-req-tracker-iqeybriv
Created build tracker: /build/pip-req-tracker-iqeybriv
Entered build tracker: /build/pip-req-tracker-iqeybriv
Created temporary directory: /build/pip-wheel-7o0v429r
Processing /build/generic-1.0.0
  Created temporary directory: /build/pip-req-build-vdl7jj3f
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior be
fore it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Added file:///build/generic-1.0.0 to build tracker '/build/pip-req-tracker-iqeybriv'
    Created temporary directory: /build/pip-modern-metadata-a6jy3ldu
    Running command /nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/bin/python3.9 /nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.p
y prepare_metadata_for_build_wheel /build/tmpnqcimwk8
    Preparing wheel metadata ... done                                                                                                                                                                                      [30/1846]
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/commands/wheel.py", line 142, in run
    requirement_set = resolver.resolve(
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 103, in resolve
    r = self.factory.make_requirement_from_install_req(
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 429, in make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
    super().__init__(
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 36, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 549, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 534, in _generate_metadata
    return generate_metadata(
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_internal/operations/build/metadata.py", line 31, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 184, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 275, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/nix/store/5w0rmiv65bg1hrsx3wv6p284bnd3z7bx-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry.masonry'

Removed file:///build/generic-1.0.0 from build tracker '/build/pip-req-tracker-iqeybriv'
Removed build tracker: '/build/pip-req-tracker-iqeybriv'
```

**Comment by WolfangAukang** [comment]
Now, my issue building this application is getting the correct GTK libraries to make it work. The issue I get is:

```
Traceback (most recent call last):
  File "/nix/store/1vx6ahfiv5l1q2p5p8nls4fgmicm9jnc-gaphor-2.6.5/bin/..gaphor-wrapped-wrapped", line 6, in <module>
    from gaphor.ui import main
  File "/nix/store/1vx6ahfiv5l1q2p5p8nls4fgmicm9jnc-gaphor-2.6.5/lib/python3.9/site-packages/gaphor/__init__.py", line 13, in <module>
    gi.require_version("GtkSource", gtk_source_version)
  File "/nix/store/x0wvq97rkzlcflzhmny0b4y762154jn7-python3.9-pygobject-3.42.0/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
```

Right now I'm using:
- NativeBuildInputs: gobject-introspection and wrapGAppsHook
- BuildInputs: gtk3
- strictDeps = false (avoids asking for PangoCairo)
