### ISSUE TITLE
Build of `rustup` fails in tests: Text file busy

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#142629]
### Describe the bug

I am unable to build rustup (in nixpkgs master) on a NixOS 21.05 machine running Linux 5.10.75-hardened1 and btrfs. I reproduced this on a second machine with the same kernel and use of btrfs.

The official Hydra does not have any problems building it: https://hydra.nixos.org/jobset/nixpkgs/trunk#tabs-jobs

When I build it, the tests fail with:

```
     Running tests/cli-self-upd.rs (target/x86_64-unknown-linux-gnu/release/deps/cli_self_upd-deeedca270fb782c)

running 45 tests
test as_rustup_setup ... FAILED
test install_but_rustup_sh_is_installed ... ok

[...]

failures:

---- as_rustup_setup stdout ----
inprocess: true
status: Some(0)
----- stdout

----- stderr

inprocess: true
status: Some(0)
----- stdout

----- stderr
info: auto-self-update mode set to 'disable'

thread 'as_rustup_setup' panicked at 'Unable to run test command: Os { code: 26, kind: ExecutableFileBusy, message: "Text file busy" }', tests/mock/clitools.rs:685:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    as_rustup_setup

test result: FAILED. 44 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 21.54s

error: test failed, to rerun pass '--test cli-self-upd'
builder for '/nix/store/0znfz3hpvmbvhal5gdvxx77phhcwmaxd-rustup-1.24.3.drv' failed with exit code 101
```

or

```

failures:

---- set_nightly_toolchain stdout ----
inprocess: true
status: Some(0)
----- stdout

----- stderr

inprocess: true
status: Some(0)
----- stdout

----- stderr
info: auto-self-update mode set to 'disable'

thread 'set_nightly_toolchain' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 26, kind: ExecutableFileBusy, message: "Text file busy" }', tests/cli-inst-interactive.rs:39:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    set_nightly_toolchain

test result: FAILED. 29 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 18.32s

error: test failed, to rerun pass '--test cli-inst-interactive'

```

Some full build logs:
- https://gist.githubusercontent.com/ivan/3578a1dcd3bc30c996158a3de8561f83/raw/0a75432513c20de748d293fac8311742462f6962/nixpkgs%2520master%2520rustup%2520build.log
- https://gist.githubusercontent.com/ivan/02494eee0e19417942edddaebebd4cf0/raw/e8790db5c0b5db2bdcefa899c051606b8ddbffae/gistfile1.txt

I believe this is a regression in master from NixOS 21.05, where I did not have problems building rustup.

### Notify maintainers

@Mic92 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.75-hardened1, NixOS, 21.05.git.4f613b46c63 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ivan** [comment]
This is still happening for me on NixOS 21.11 on Ryzen 5950X + btrfs + regular (not hardened) kernel.

```
test updater_is_deleted_after_running_rustc ... ok
test update_installs_clippy_cargo_and ... ok
test updater_is_deleted_after_running_rustup ... ok
test updater_leaves_itself_for_later_deletion ... ok

failures:

---- as_rustup_setup stdout ----
inprocess: true
status: Some(0)
----- stdout

----- stderr

inprocess: true
status: Some(0)
----- stdout

----- stderr
info: auto-self-update mode set to 'disable'

thread 'as_rustup_setup' panicked at 'Unable to run test command: Os { code: 26, kind: ExecutableFileBusy, message: "Text file busy" }', tests/mock/clitools.rs:685:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    as_rustup_setup

test result: FAILED. 44 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 26.55s

error: test failed, to rerun pass '--test cli-self-upd'
```
