### ISSUE TITLE
yarn2nix breaks with packages pinned to a commit

### ISSUE THREAD

**Issue by ckiee** [NixOS/nixpkgs#143828]
### Describe the bug
When running `yarn2nix` against a `yarn.lock` that has a package pinned to a git commit hash instead of a version, it fails to complete.

### Steps To Reproduce
1. Go to a folder you can delete afterwards
2. `nix-shell -p yarn2nix '(yarn.override { nodejs = nodejs_latest; })' --run 'yarn init -y && yarn add discordjs/discord.js#d0bc4d7ff037035d4f315a0286b06f0a1ade29c1 && yarn2nix'`
3. Watch it fail: (partial log below)
```console
<ref *1> Error: spawnSync nix-prefetch-git ENOENT
    at Object.spawnSync (internal/child_process.js:1077:20)
    at spawnSync (child_process.js:776:24)
    at execFileSync (child_process.js:822:15)
    at prefetchgit (/nix/store/fp1khj91f35w6kk8q5ya0g0g33wks22h-yarn2nix-1.0.0/libexec/yarn2nix/deps/yarn2nix/lib/generateNix.js:36:5)
    at fetchgit (/nix/store/fp1khj91f35w6kk8q5ya0g0g33wks22h-yarn2nix-1.0.0/libexec/yarn2nix/deps/yarn2nix/lib/generateNix.js:59:23)
    at /nix/store/fp1khj91f35w6kk8q5ya0g0g33wks22h-yarn2nix-1.0.0/libexec/yarn2nix/deps/yarn2nix/lib/generateNix.js:92:14
    at _map (/nix/store/fp1khj91f35w6kk8q5ya0g0g33wks22h-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/nix/store/fp1khj91f35w6kk8q5ya0g0g33wks22h-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/ramda/src/map.js:64:14)
    at /nix/store/fp1khj91f35w6kk8q5ya0g0g33wks22h-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/ramda/src/internal/_dispatchable.js:41:15
    at Object.f2 [as map] (/nix/store/fp1khj91f35w6kk8q5ya0g0g33wks22h-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/ramda/src/internal/_curry2.js:29:14) {
```

### Expected behavior
I expected it to spit a bunch of Nix code out as it does when reverting these commits:
```
4c7e1a10b4b * yarn2nix: fix "rev is not defined" (#141207)
b7e7d35ccce * yarn2nix: workaround for NixOS/nix#5128
b27d18a412b * yarn2nix: handle codeload.github.com uris in IFD mode (#136922)
```

### Additional context
I don't think the yarn Node.js version matters, that's just to satisfy `discord.js`'s engine requirements.

### Notify maintainers
@yu-re-ka

### Metadata
```console
ckie@cookiemonster /tmp/foob -> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.14-zen1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(root): `""`
 - nixpkgs: `/run/current-system/sw/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: yarn2nix-moretea
# a list of nixos modules affected by the problem
module:
```

**Comment by yu-re-ka** [comment]
Thanks for the thorough bug report. Please try it with yarn2nix from #143890 .
