### ISSUE TITLE
Building 16.03 fails because of sqlalchemy test (?)

### ISSUE THREAD

**Issue by ne0phyte** [NixOS/nixpkgs#14380]
* Kernel: Linux 4.4.6 #1-NixOS SMP Wed Mar 16 15:43:17 UTC 2016 x86_64 GNU/Linux
* System: 16.09pre79453.32b7b00 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre79453.32b7b00

Building 16.03 failed. After removing libvirtd and virtmanager from my configuration the build went through without any errors. 
I would look further into why it's failing, but I honestly don't know where to look.

```
ERROR: test.sql.test_query.QueryTest.test_column_accessor_sqlite_translated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/m9psy29hd64sls9b2b11j1v7sypvcjc1-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 1, in <lambda>
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/lib/exclusions.py", line 45, in decorate
    return fn(*args, **kw)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/sql/test_query.py", line 800, in test_column_accessor_sqlite_translated
    eq_(r['query_users.user_id'], 1)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./lib/sqlalchemy/engine/base.py", line 2615, in __getitem__
    processor, obj, index = self._parent._key_fallback(key)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./lib/sqlalchemy/engine/base.py", line 2834, in _key_fallback
    expression._string_or_unprintable(key))
NoSuchColumnError: "Could not locate column in row for column 'query_users.user_id'"

======================================================================
FAIL: test.sql.test_query.QueryTest.test_column_accessor_sqlite_raw
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/m9psy29hd64sls9b2b11j1v7sypvcjc1-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 1, in <lambda>
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/lib/exclusions.py", line 45, in decorate
    return fn(*args, **kw)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/sql/test_query.py", line 783, in test_column_accessor_sqlite_raw
    assert 'user_id' not in r
AssertionError
```

Here is the full log of `nixos-rebuild build`.
[log.txt](https://github.com/NixOS/nixpkgs/files/200458/log.txt)

**Comment by FRidh** [comment]
See #14026

**Comment by domenkozar** [comment]
Both packages now build on 16.09, please reopen if issue persist. Also SQLAlchemy 7 has been removed.
