### ISSUE TITLE
fetchYarnDeps: git fetch not working on specific lockfile

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#144200]
### Steps To Reproduce
1. Build this
```
with (import ./. {});

let 
  src = fetchFromGitHub {
    owner = "chatwoot";
    repo = "chatwoot";
    rev = "03b1a3d045bbfc221bcf07c8155eccd2d0d88905";
    sha256 = "dJ3uG8wpuDGzPOZEgRCv1FHyU3pHch+sgsFRlaWxNjY=";
    fetchSubmodules = true;
    # rev = "v${version}";
  };
in
fetchYarnDeps {
    yarnLock = src + "/yarn.lock";
    sha256 = lib.fakeSha256;
}
```

Watch it fail as follows:
```
Error: hash mismatch, expected 7e8acadd10d7b932c0dc0bd0a18f804434f83517, got 3adb1f02d5b6054de0046e367c1d687b6cdf7aff
    at IncomingMessage.<anonymous> (/nix/store/ngdkv56l59jjp660j7fqbbkff42xx984-prefetch-yarn-deps/libexec/index.js:45:42)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

### Expected behavior
Fetches dependencies and throws error about invalid output hash

### Additional context

The problem is with the git fetcher itself, which seems to ignore the revision part of the url (or does something else entirely wrong)

Changing the hash to the one the error message contains (in yarn.lock) causes the error to go away but yarn is subsequently unable to fetch from that lockfile so it must be a bug in fetchYarnDeps not yarn itself

### Notify maintainers
@yu-re-ka 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by yu-re-ka** [comment]
The problem here is the difference between `https://github.com/...` and `git+https://github.com/...`. yarn itself uses some magical logic to assign the resolved field to a fetcher (git, https, ...). fetchYarnDeps sees the `https://` prefix and tries to download it as a file via https.

You can try patching the lockfile to say `git+https`. hedgedoc does the same thing. yarn2nix also has the same problem.

**Comment by mkg20001** [comment]
The magic seems to be here https://github.com/yarnpkg/yarn/tree/master/src/resolvers/exotics

It doesn't seem like a lot so it would be worth implementing it (or possibly just using that code directly)

I'll try git+https patching for now

**Comment by mkg20001** [comment]
I've found another bug

This part of the lockfile

```
caniuse-lite@^1.0.0, caniuse-lite@^1.0.30000981, caniuse-lite@^1.0.30001109, caniuse-lite@^1.0.30001125, caniuse-lite@^1.0.30001214:
  version "1.0.30001219"
  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30001219.tgz#5bfa5d0519f41f993618bd318f606a4c4c16156b"
  integrity sha512-c0yixVG4v9KBc/tQ2rlbB3A/bgBFRvl8h8M4IeUbqCca4gsiCfvtaheUssbnux/Mb66Vjz7x8yYjDgYcNQOhyQ==
```

Results in this error

```
Error: [https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001271.tgz]: hash mismatch, expected undefined, got 0dda0c9bcae2cf5407cd34cac304186616cc83e8
    at IncomingMessage.<anonymous> (/nix/store/b4j67lppkril4pz3m42q9d34f5aajdx5-prefetch-yarn-deps/libexec/index.js:45:42)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by jtojnar** [comment]
The undefined part should be fixed by https://github.com/NixOS/nixpkgs/pull/119522 by preferring `integrity`.

**Comment by AleXoundOS** [comment]
I get such errors too:
```
Error: hash mismatch, expected 0dfc80309beec8411e65e706461c408b0bb9b431, got bbba84135de6b052c2210e74e0cc5b2a9d359ddb
    at IncomingMessage.<anonymous> (/nix/store/vxwkpcpfxsra97qwkqvax0zcm44pdcxm-prefetch-yarn-deps/libexec/index.js:46:42)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
But it seems this time the problem is more general, because I get this exact hash `bbba84135de6b052c2210e74e0cc5b2a9d359ddb` for any npm packet. And googling of this hash gives... 

```console
$ echo -n Found | sha1sum
bbba84135de6b052c2210e74e0cc5b2a9d359ddb  -
```

```console
$ curl "https://registry.npmmirror.com/7zip-bin/download/7zip-bin-5.1.1.tgz"
Found
```

But!
```console
$ wget -nv "https://registry.npmmirror.com/7zip-bin/download/7zip-bin-5.1.1.tgz"
2022-01-20 01:42:41 URL:https://oss.npmmirror.com/7zip-bin/-/7zip-bin-5.1.1.tgz [5054087/5054087] -> "7zip-bin-5.1.1.tgz" [1]
```

**Comment by AleXoundOS** [comment]
Ok, going further, we get a "document moved" (`302` HTTP code) answer from the server. So we need to follow the redirect. For example, `curl -L` does this.

**Comment by AleXoundOS** [comment]
A quick example of patching this with an overlay:
```nix
let
  fetch-patch = builtins.toFile "fetch.patch" ''
    diff --git a/pkgs/build-support/node/fetch-yarn-deps/index.js b/pkgs/build-support/node/fetch-yarn-deps/index.js
    index f3662a54361..193656ccd41 100755
    --- a/pkgs/build-support/node/fetch-yarn-deps/index.js
    +++ b/pkgs/build-support/node/fetch-yarn-deps/index.js
    @@ -36,6 +36,22 @@ const urlToName = url => {
     const downloadFileHttps = (fileName, url, expectedHash) => {
     	return new Promise((resolve, reject) => {
     		https.get(url, (res) => {
    +			if (res.statusCode === 301 || res.statusCode === 302) {
    +				return https.get(res.headers.location, (res) => {
    +					const file = fs.createWriteStream(fileName)
    +					const hash = crypto.createHash('sha1')
    +					res.pipe(file)
    +					res.pipe(hash).setEncoding('hex')
    +					res.on('end', () => {
    +						file.close()
    +						const h = hash.read()
    +						if (h != expectedHash) return reject(new Error(`hash mismatch, expected ''${expectedHash}, got ''${h}`))
    +							resolve()
    +						})
    +						res.on('error', e => reject(e))
    +					})
    +			}
    +
     			const file = fs.createWriteStream(fileName)
     			const hash = crypto.createHash('sha1')
     			res.pipe(file)
  '';
  overlay = _final: prev: {
    prefetch-yarn-deps = prev.prefetch-yarn-deps.overrideAttrs (_def: {
      postBuild = ''
        chmod +w libexec/index.js
        cp ${pkgs.path + /pkgs/build-support/node/fetch-yarn-deps/index.js} `
        `libexec/index.js
        patch -p5 libexec/index.js ${fetch-patch}
        patchShebangs libexec/index.js
      '';
    });
  };
  pin = builtins.fetchTarball {
    name = "nixpkgs";
    url = "https://github.com/NixOS/nixpkgs/archive/d5dae6569ea9952f1ae4e727946d93a71c507821.tar.gz";
    sha256 = "1w4wch077d2wgrdaya8y1pa34rzvh26xns6zgzr4kmlfd5g2rhwd";
  };
  pkgs = import pin { overlays = [ overlay ]; };
in
pkgs.fetchYarnDeps {
  yarnLock = pkgs.runCommandLocal "fix-yarn.lock" { } ''
    sed 's/\.tgz\?[^#]\+/\.tgz/g' ${./yarn.lock} > $out
  '';
  sha256 = pkgs.lib.fakeSha256;
}

```
