### ISSUE TITLE
Heroku toolbelt is broken (in an unrecoverable manner) after deleting your ~/.heroku directory

### ISSUE THREAD

**Issue by rehno-lindeque** [NixOS/nixpkgs#14496]
## Issue description

Deleting your `~/.heroku` directory appears to cause unrecoverable problems. This follows the merge of https://github.com/NixOS/nixpkgs/pull/13914.
### Steps to reproduce

```
$ mv ~/.heroku ~/.heroku-backup

$ nix-shell -p heroku

[nix-shell:~/projects/development/myproject]$ heroku
Installing Heroku Toolbelt v4... done.
For more information on Toolbelt v4: https://github.com/heroku/heroku-cli
heroku-cli: Adding dependencies... 6.68 MB/6.68 MB
heroku-cli: Adding dependencies... 6.68 MB/6.68 MB
 ▸    rename /home/myusername/.heroku/tmp/732830271/file /nix/store/rykiflhsfl9sa96mhrsiqh5dil5w9947-nodejs-5.9.0/bin/node: invalid cross-device link
heroku-cli: Adding dependencies... 6.68 MB/6.68 MB
heroku-cli: Adding dependencies... 6.68 MB/6.68 MB
 ▸    rename /home/myusername/.heroku/tmp/867538066/file /nix/store/rykiflhsfl9sa96mhrsiqh5dil5w9947-nodejs-5.9.0/bin/node: invalid cross-device link
heroku-cli: Installing core plugins...
 ▸    module.js:341
 ▸        throw err;
 ▸        ^
 ▸    
 ▸    Error: Cannot find module '/home/myusername/.heroku/npm-3.8.5/cli.js'
 ▸        at Function.Module._resolveFilename (module.js:339:15)
 ▸        at Function.Module._load (module.js:290:25)
 ▸        at Function.Module.runMain (module.js:447:10)
 ▸        at startup (node.js:142:18)
 ▸        at node.js:939:3
module.js:341
    throw err;
    ^

Error: Cannot find module '/home/myusername/.heroku/npm-3.8.5/cli.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

 ▸    exit status 1
heroku-cli: Installing core plugins (retrying)...
 ▸    Error installing package. 
 ▸    module.js:341
 ▸        throw err;
 ▸        ^
 ▸    
 ▸    Error: Cannot find module '/home/myusername/.heroku/npm-3.8.5/cli.js'
 ▸        at Function.Module._resolveFilename (module.js:339:15)
 ▸        at Function.Module._load (module.js:290:25)
 ▸        at Function.Module.runMain (module.js:447:10)
 ▸        at startup (node.js:142:18)
 ▸        at node.js:939:3
 ▸    
 ▸    Try running again with GODE_DEBUG=info to see more output.
heroku-cli: Adding dependencies... 6.68 MB/6.68 MB
heroku-cli: Adding dependencies... 6.68 MB/6.68 MB
 ▸    rename /home/myusername/.heroku/tmp/705578544/file /nix/store/rykiflhsfl9sa96mhrsiqh5dil5w9947-nodejs-5.9.0/bin/node: invalid cross-device link
heroku-cli: Installing core plugins...
 ▸    module.js:341
 ▸        throw err;
 ▸        ^
 ▸    
 ▸    Error: Cannot find module '/home/myusername/.heroku/npm-3.8.5/cli.js'
 ▸        at Function.Module._resolveFilename (module.js:339:15)
 ▸        at Function.Module._load (module.js:290:25)
 ▸        at Function.Module.runMain (module.js:447:10)
 ▸        at startup (node.js:142:18)
 ▸        at node.js:939:3
module.js:341
    throw err;
    ^

Error: Cannot find module '/home/myusername/.heroku/npm-3.8.5/cli.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

 ▸    exit status 1
heroku-cli: Installing core plugins (retrying)...
 ▸    Error installing package. 
 ▸    module.js:341
 ▸        throw err;
 ▸        ^
 ▸    
 ▸    Error: Cannot find module '/home/myusername/.heroku/npm-3.8.5/cli.js'
 ▸        at Function.Module._resolveFilename (module.js:339:15)
 ▸        at Function.Module._load (module.js:290:25)
 ▸        at Function.Module.runMain (module.js:447:10)
 ▸        at startup (node.js:142:18)
 ▸        at node.js:939:3
 ▸    
 ▸    Try running again with GODE_DEBUG=info to see more output.
 !    error getting commands pid 5442 exit 1
```

**Comment by kamilchm** [comment]
Same for me. Strange thing.
What I did for now as a workaround when digging into it:

```
export HEROKU_NODE_PATH=/nix/store/qiqms0k1mwa6zg1fc11hd4hy81bc4zc7-nodejs-5.7.1/bin/node
~/.heroku/heroku-cli
```

**Comment by kamilchm** [comment]
Someone want to preserve `HEROKU_NODE_PATH` for heroku command here https://github.com/heroku/heroku/blob/master/lib/heroku/jsplugin.rb#L171 ?

I'm not Ruby dev but it looks like possible solution http://stackoverflow.com/a/9357883

**Comment by wmertens** [comment]
[triage] is this still a problem? I see that the heroku tool gained a minor version number in the mean time?

**Comment by rasendubi** [comment]
Cannot reproduce.
