### ISSUE TITLE
21.05 & Unstable Unable to emulate TPM with libvirt

### ISSUE THREAD

**Issue by Lillecarl** [NixOS/nixpkgs#145010]
### Describe the bug
When creating a VM with virt-manager and adding a TPM2 device the following errror occurs:

```
Error starting domain: Unable to find 'swtpm' binary in $PATH: No such file or directory

Traceback (most recent call last):
  File "/nix/store/s7hs76h96ilg58b4ch401r09lv3lv2lp-virt-manager-3.2.0/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/nix/store/s7hs76h96ilg58b4ch401r09lv3lv2lp-virt-manager-3.2.0/share/virt-manager/virtManager/asyncjob.py", line 101, in tmpcb
    callback(*args, **kwargs)
  File "/nix/store/s7hs76h96ilg58b4ch401r09lv3lv2lp-virt-manager-3.2.0/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/nix/store/s7hs76h96ilg58b4ch401r09lv3lv2lp-virt-manager-3.2.0/share/virt-manager/virtManager/object/domain.py", line 1329, in startup
    self._backend.create()
  File "/nix/store/8liinkhdjmwdkiwg5d001d3avn68ibrd-python3.8-libvirt-7.0.0/lib/python3.8/site-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: Unable to find 'swtpm' binary in $PATH: No such file or directory
```

It seems like libvirt depends on calling swtpm to perform some TPM actions. This is "important" if one wishes to run Windows 11 in a virtual machine.

### Steps To Reproduce
1. Enable libvirt
2. Install virt-manager
3. Create a VM
4. Add an emulated TPM device
5. Start the VM

### Expected behavior
libvirt depends on swtpm for this functionality, we should also depend on it.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.76, NixOS, 21.05.3990.372e59d2af7 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.3990.372e59d2af7, nixos-hardware, unstable-21.11pre327669.b67e752c29f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/development/libraries/libvirt/default.nix
# a list of nixos modules affected by the problem
module:
https://github.com/NixOS/nixpkgs/blob/nixos-21.05/nixos/modules/virtualisation/libvirtd.nix
```

@fpletz 
@globin

**Comment by thiagokokada** [comment]
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/libvirtd.nix#L51

**Comment by thiagokokada** [comment]
Also: https://search.nixos.org/options?channel=unstable&show=virtualisation.libvirtd.qemu.swtpm.enable&from=0&size=50&sort=relevance&type=packages&query=swtpm

**Comment by Lillecarl** [comment]
@thiagokokada I was certain I searched unstable, must've had a brainfart. Thanks for the correction.
