### ISSUE TITLE
kwin_wayland segfaults on plasma 5.23.2+

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#145576]
### Describe the bug
kwin_wayland segfaults with plasma 5.23.2

### Steps To Reproduce
1. use unstable after b67e752c29f
2. open a KDE wayland session
3. notice that kwin_wayland keeps segfaulting and after a few seconds that you're returned to sddm

### Expected behavior
The normal plasma desktop to show.

### Additional context
With plasma 5.23.1 everything was working wonderfully.

We have a pending update for libepoxy that *might* have an impact here as the crash happens there: https://github.com/NixOS/nixpkgs/pull/145039

<details>

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/libthread_db.so.1".
Core was generated by `/run/wrappers/bin/kwin_wayland --wayland_fd 5 --socket wayland-0 --xwayland-fd'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f3efa664baa in raise () from /nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/libc.so.6
[Current thread is 1 (Thread 0x7f3ef67c0880 (LWP 2229))]
(gdb) bt
#0  0x00007f3efa664baa in raise () from /nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/libc.so.6
#1  0x00007f3efa64f5d3 in abort () from /nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/libc.so.6
#2  0x00007f3efad3c090 in gl_provider_resolver () from /nix/store/9dzpbhzf0ccsncddhsjqlz629ds28xp4-epoxy-1.5.4/lib/libepoxy.so.0
#3  0x00007f3efad3c0d3 in gl_single_resolver () from /nix/store/9dzpbhzf0ccsncddhsjqlz629ds28xp4-epoxy-1.5.4/lib/libepoxy.so.0
#4  0x00007f3efad4308f in epoxy_glDrawBuffer_global_rewrite_ptr () from /nix/store/9dzpbhzf0ccsncddhsjqlz629ds28xp4-epoxy-1.5.4/lib/libepoxy.so.0
#5  0x00007f3ee8442846 in KWin::EglGbmBackend::makeContextCurrent(KWin::EglGbmBackend::Output::RenderData const&) const ()
   from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#6  0x00007f3ee8444e67 in KWin::EglGbmBackend::prepareRenderingForOutput(KWin::EglGbmBackend::Output&) ()
   from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#7  0x00007f3ee8449bc6 in KWin::EglGbmBackend::beginFrame(KWin::AbstractOutput*) ()
   from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#8  0x00007f3ee844badc in KWin::EglGbmBackend::renderTestFrame(KWin::DrmAbstractOutput*) ()
   from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#9  0x00007f3ee8439dc3 in KWin::DrmPipeline::checkTestBuffer() () from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#10 0x00007f3ee843afb5 in KWin::DrmPipeline::commitPipelines(QVector<KWin::DrmPipeline*> const&, KWin::DrmPipeline::CommitMode) [clone .part.0] ()
   from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#11 0x00007f3ee843094a in KWin::DrmGpu::commitCombination(QVector<KWin::DrmPipeline*> const&) ()
   from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#12 0x00007f3ee8432df2 in KWin::DrmGpu::findWorkingCombination(QVector<KWin::DrmPipeline*> const&, QVector<KWin::DrmConnector*>, QVector<KWin::DrmCrtc*>, QVector<KWin::DrmPlane*> const&) ()
   from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#13 0x00007f3ee8432791 in KWin::DrmGpu::findWorkingCombination(QVector<KWin::DrmPipeline*> const&, QVector<KWin::DrmConnector*>, QVector<KWin::DrmCrtc*>, QVector<KWin::DrmPlane*> const&)::{lambda(KWin::DrmCrtc*, KWin::DrmPlane*)#2}::operator()(KWin::DrmCrtc*, KWin::DrmPlane*) const ()
   from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#14 0x00007f3ee84330e8 in KWin::DrmGpu::findWorkingCombination(QVector<KWin::DrmPipeline*> const&, QVector<KWin::DrmConnector*>, QVector<KWin::DrmCrtc*>, QVector<KWin::DrmPlane*> const&) ()
   from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#15 0x00007f3ee84348e8 in KWin::DrmGpu::updateOutputs() () from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#16 0x00007f3ee8414958 in KWin::DrmBackend::updateOutputs() () from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/qt-5.15.2/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
#17 0x00007f3efb193387 in ?? () from /nix/store/dj66jij1jaa2iywh4cgar3h4js9brr4a-qtbase-5.15.2/lib/libQt5Core.so.5
#18 0x00007f3efde38f7c in KWin::Compositor::setupStart() [clone .part.0] () from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/libkwin.so.5
#19 0x00007f3efde3abd1 in KWin::WaylandCompositor::start() () from /nix/store/b4dyi8qyz2cdz60ddy2nbplg01sb2i92-kwin-5.23.2/lib/libkwin.so.5
#20 0x00007f3efb18910c in QObject::event(QEvent*) () from /nix/store/dj66jij1jaa2iywh4cgar3h4js9brr4a-qtbase-5.15.2/lib/libQt5Core.so.5
#21 0x00007f3efbfcf74f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/dj66jij1jaa2iywh4cgar3h4js9brr4a-qtbase-5.15.2/lib/libQt5Widgets.so.5
#22 0x00007f3efb15c38a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/dj66jij1jaa2iywh4cgar3h4js9brr4a-qtbase-5.15.2/lib/libQt5Core.so.5
#23 0x00007f3efb15f3d1 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /nix/store/dj66jij1jaa2iywh4cgar3h4js9brr4a-qtbase-5.15.2/lib/libQt5Core.so.5
#24 0x00007f3efb1b19a9 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/dj66jij1jaa2iywh4cgar3h4js9brr4a-qtbase-5.15.2/lib/libQt5Core.so.5
#25 0x00000000004911ed in QUnixEventDispatcherQPA::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#26 0x00007f3efb15ad3b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/dj66jij1jaa2iywh4cgar3h4js9brr4a-qtbase-5.15.2/lib/libQt5Core.so.5
#27 0x00007f3efb163320 in QCoreApplication::exec() () from /nix/store/dj66jij1jaa2iywh4cgar3h4js9brr4a-qtbase-5.15.2/lib/libQt5Core.so.5
#28 0x000000000042b5fe in main ()
```

</details>

Cc: @NixOS/qt-kde

**Comment by peterhoeg** [comment]
This environment variable was the culprit:
```
KWIN_COMPOSE = "O2ES";
```

Removing it made things work again.
