### ISSUE TITLE
Darcs2git broken (apparently by a Ruby update)

### ISSUE THREAD

**Issue by pijul** [NixOS/nixpkgs#14619]
## Issue description

gitAndTools.darcsToGit doesn't build on NixOS 16.03.

### Steps to reproduce

Add gitAndTools.darcsToGit to /etc/nixos/configuration.nix, then nixos-rebuild switch.

~~~
these derivations will be built:
  /nix/store/hn2782pwbjvxzbyy8s57xircllw47w45-darcs-to-git-0.2git.drv
  /nix/store/wwwhmylbi2nzpanrpgc884vsq08r7352-system-path.drv
  /nix/store/syxyrpw90kf5l4xyajb14v079l9j5f9v-unit-polkit.service.drv
  /nix/store/zv58y2zhbh8xrvc75kg9qyb6flfy8dj4-dbus-conf.drv
  /nix/store/z5mayyhlz8vxpw0p3jzzhjjn38b24hg5-unit-dbus.service.drv
  /nix/store/ymdlr6xbcv247v59x65a4bviislyi7kq-system-units.drv
  /nix/store/85r5g3m4ilfbbrwk1b61jx19vqvf4ghd-etc.drv
  /nix/store/y5w2grj8i8q59zx7dz47z4mb7j30xqr0-nixos-system-marcelle-16.03.503.3f96280.drv
building path(s) ‘/nix/store/j5sk6gb9lpdbisxhff65rfs5waixx9zr-darcs-to-git-0.2git’
unpacking sources
unpacking source archive /nix/store/0adwqf27pq9zq1mfk3hmc2ikacahbdc1-darcs-to-git-58a5593
source root is darcs-to-git-58a5593
patching sources
configuring
grep: : No such file or directory
grep: : No such file or directory
no configure script, doing nothing
building
no Makefile, doing nothing
running tests
Repository initialized.
Adding 'new_file1'
Finished recording patch 'c1'
Adding 'new_file2'
Finished recording patch 'c2'
Moved: new_file2 to: only_one_file
Finished recording patch 'c3'
/nix/store/0d00q7k7y9nnjppcshq3766xi4l45h60-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- iconv (LoadError)
	from /nix/store/0d00q7k7y9nnjppcshq3766xi4l45h60-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/nix-build-darcs-to-git-0.2git.drv-0/darcs-to-git-58a5593/darcs-to-git:32:in `<main>'
builder for ‘/nix/store/hn2782pwbjvxzbyy8s57xircllw47w45-darcs-to-git-0.2git.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/wwwhmylbi2nzpanrpgc884vsq08r7352-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/y5w2grj8i8q59zx7dz47z4mb7j30xqr0-nixos-system-marcelle-16.03.503.3f96280.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/y5w2grj8i8q59zx7dz47z4mb7j30xqr0-nixos-system-marcelle-16.03.503.3f96280.drv’ failed
~~~

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.03.503.3f96280 (Emu)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.03.503.3f96280"

**Comment by copumpkin** [comment]
I love that in this ticket we have one VCS system reporting a bug in a converter between two other VCS systems 😄

**Comment by pijul** [comment]
You're actually right: this won't be a problem for us for much longer anyway ;-)

**Comment by vcunat** [comment]
Ah, this was originally reported against closure-size https://github.com/NixOS/nixpkgs/issues/12870, but if you experience it on 16.03, it must've started earlier. Let's keep the older ticket.
