### ISSUE TITLE
qtile missing some more modules

### ISSUE THREAD

**Issue by mhwombat** [NixOS/nixpkgs#146281]
### Describe the bug

The installation of qtile seems to omit some modules.
Related to #146026.

### Steps To Reproduce

Note: I built NixOS from github, version 21.11.git.2fa862644fcM (Porcupine), but I have included this patch: #146029.

1. In NixOS config, add `qtile` to `environment.systemPackages`.
2. `nixos-rebuild switch --upgrade`
3. Log into qtile.
4. Run `qtile check`.

```
$ qtile check
checking qtile config file /home/amy/.config/qtile/config.py
error: failed mypy build.
config.pyi:4: error: Cannot find implementation or library stub for module named 'libqtile.config'
config.pyi:4: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
config.pyi:5: error: Cannot find implementation or library stub for module named 'libqtile.layout.base'
```

### Expected behavior

I expected qtile to check the configuration file.

### Notify maintainers
@kamilchm 
@jonringer 

### Metadata

```console
# nix-channel --list
nixos https://nixos.org/channels/nixos-unstable

$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/94n19nsi7xdsna40zl7iy4476kwldlzg-bash-interactive-5.1-p8-dev
copying path '/nix/store/94n19nsi7xdsna40zl7iy4476kwldlzg-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.75, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(amy): `""`
 - channels(root): `"nixos-21.11pre330462.2fa862644fc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: qtile
```

**Comment by jonringer** [comment]
please review PR

**Comment by mhwombat** [comment]
I tried this, and it had no effect on the error. However, I'm new to working with branches and trying other people's commits, so **I may be doing something wrong**. Here's what I did:

```
git clone https://github.com/NixOS/nixpkgs
cd nixpkgs
git remote update origin
git checkout -b local 931ab058daa

```
Next, I copied the `pkgs/applications/window-managers/qtile/default.nix` in your PR, replacing the one in my repo. **I assume there's a smarter way to do this?**

`nixos-rebuild switch --upgrade -I nixpkgs=/home/amy/nixpkgs`

**Comment by mhwombat** [comment]
To explore this issue further, I thought I'd try to build the upstream repo according to their instructions, outside of NixOS. I ran into a problem, and I thought I'd post it here in case it's relevant. Even if it's not relevant to the issue, maybe you can tell me how to fix it and I can go on to investigate the real issue.

I created a nix shell with with what I believe are all the required dependencies. I entered that shell and ran the following commands, all of which succeeded.

```
virtualenv venv
source venv/bin/activate
pip install --no-cache-dir cairocffi
pip install qtile
```

Finally, I invoked `qtile check` and got an error about a missing library.

```
$ qtile check
Traceback (most recent call last):
  File "/home/amy/qtile/venv/bin/qtile", line 5, in <module>
    from libqtile.scripts.main import main
  File "/home/amy/qtile/venv/lib/python3.9/site-packages/libqtile/scripts/main.py", line 6, in <module>
    from libqtile.scripts import check, cmd_obj, migrate, run_cmd, shell, start, top
  File "/home/amy/qtile/venv/lib/python3.9/site-packages/libqtile/scripts/check.py", line 29, in <module>
    from libqtile import confreader
  File "/home/amy/qtile/venv/lib/python3.9/site-packages/libqtile/confreader.py", line 31, in <module>
    from libqtile.backend.x11 import core
  File "/home/amy/qtile/venv/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 38, in <module>
    import xcffib
  File "/home/amy/qtile/venv/lib/python3.9/site-packages/xcffib/__init__.py", line 38, in <module>
    lib = ffi.dlopen(soname)
OSError: cannot load library 'libxcb.so': libxcb.so: cannot open shared object file: No such file or directory
(venv)
```

Here's my `shell.nix`.

```
$ cat shell.nix
with (import <nixpkgs> {});
stdenv.mkDerivation {
  name = "pip-env";
  buildInputs = [
    # System requirements.
    readline
    mypy
    glib
    cairo
    pango
    pkg-config
    xcb-util-cursor
    xorg.libxcb

    # Python requirements (enough to get a virtualenv going).
    python39Full
    python39Packages.virtualenv
    python39Packages.pip
    python39Packages.setuptools
    python39Packages.wheel
    python39Packages.pywlroots
    python39Packages.pywayland
    python39Packages.xkbcommon
  ];
  src = null;
  shellHook = ''
    # Allow the use of wheels.
    SOURCE_DATE_EPOCH=$(date +%s)

    # Augment the dynamic linker path
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${R}/lib/R/lib:${readline}/lib
  '';
}

```

```It seems to me that, having installed `xlibs.xcb`, libxcb.so should be visible.

```
 nix-locate libxcb.so --top-level
remarkable-toolchain.out                              0 s /nix/store/qpgskxqvrvbs960kb73f31lx0gkjrc11-remarkable-toolchain-3.1.2/sysroots/x86_64-codexsdk-linux/usr/lib/libxcb.so.1
remarkable-toolchain.out                        158,600 x /nix/store/qpgskxqvrvbs960kb73f31lx0gkjrc11-remarkable-toolchain-3.1.2/sysroots/x86_64-codexsdk-linux/usr/lib/libxcb.so.1.1.0
remarkable2-toolchain.out                             0 s /nix/store/x53cix2lcr1yxblybbyr5wl8v26h499b-remarkable2-toolchain-3.1.2/sysroots/x86_64-codexsdk-linux/usr/lib/libxcb.so.1
remarkable2-toolchain.out                       158,600 x /nix/store/x53cix2lcr1yxblybbyr5wl8v26h499b-remarkable2-toolchain-3.1.2/sysroots/x86_64-codexsdk-linux/usr/lib/libxcb.so.1.1.0
xlibs.libxcb.out                                      0 s /nix/store/c2ghjp08azbccl3nj75rrm3s78vwkxvh-libxcb-1.14/lib/libxcb.so
xlibs.libxcb.out                                      0 s /nix/store/c2ghjp08azbccl3nj75rrm3s78vwkxvh-libxcb-1.14/lib/libxcb.so.1
xlibs.libxcb.out                                223,760 x /nix/store/c2ghjp08azbccl3nj75rrm3s78vwkxvh-libxcb-1.14/lib/libxcb.so.1.1.0

```
