### ISSUE TITLE
OBS sometimes segfaults when using screen capture with xdg-desktop-portal-wlr/sway

### ISSUE THREAD

**Issue by zseri** [NixOS/nixpkgs#146769]
### Describe the bug
I use Sway as Wayland compositor/server and OBS to experiment with screen / window captures.
Currently, window captures just don't work as expected, and instead result in the whole screen being captured.
Screen captures mostly work, but OBS or OBS pipewire threads might segfault when trying to remove the capture from the OBS scene.

e.g. might result in some dmesg messages like (on NixOS 21.11 17f73e226198a511a74a953758ceed6efdad9444 x86-64):
```
[ 1861.495128] PipeWire thread[6089]: segfault at 7f838c758020 ip 00007f83a295de15 sp 00007f83321ed098 error 4 in libc-2.33.so[7f83a284e000+143000]
[ 1861.495151] Code: 65 05 00 77 20 4d 63 0c 93 48 01 d6 48 01 d7 4d 01 d9 41 ff e1 0f 0b 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 40 38 fe 7e 5b <f3> 0f 6f 06 48 89 f9 48 83 e7 f0 48 83 c7 10 49 89 c8 48 29 f9 48
[ 1877.434762] PipeWire thread[6177]: segfault at 7f8ffdcac000 ip 00007f906e8bdf78 sp 00007f8ffe70d098 error 4 in libc-2.33.so[7f906e7ae000+143000]
[ 1877.434776] Code: 00 00 00 66 0f 6f 26 0f 28 4e 10 0f 28 56 20 0f 28 5e 30 66 0f 7f 27 0f 29 4f 10 0f 29 57 20 0f 29 5f 30 48 81 ea 80 00 00 00 <0f> 28 66 40 0f 28 6e 50 0f 28 76 60 0f 28 7e 70 48 8d b6 80 00 00
[ 2175.654634] .obs-wrapped[6228]: segfault at 1cf ip 00007f228ede1d55 sp 00007fff071e9d38 error 4 in libobs.so.0[7f228edad000+a2000]
[ 2175.654644] Code: fc ff 48 85 c0 74 13 48 89 c2 48 f7 d2 83 e2 1f 48 83 c2 01 48 01 d0 88 50 ff 48 83 c4 08 c3 66 0f 1f 44 00 00 48 85 ff 74 13 <48> 0f be 47 ff 48 29 c7 e9 7e c9 fc ff 66 0f 1f 44 00 00 c3 0f 1f
```

### obs segfault

gdb asm snippet
```
│    0x7f228ede1d4a                  nopw   0x0(%rax,%rax,1)
│    0x7f228ede1d50 <a_free>         test   %rdi,%rdi
│    0x7f228ede1d53 <a_free+3>       je     0x7f228ede1d68 <a_free+24>
│  > 0x7f228ede1d55 <a_free+5>       movsbq -0x1(%rdi),%rax
│    0x7f228ede1d5a <a_free+10>      sub    %rax,%rdi
│    0x7f228ede1d5d <a_free+13>      jmp    0x7f228edae6e0 <free@plt>
│    0x7f228ede1d62 <a_free+18>      nopw   0x0(%rax,%rax,1)
│    0x7f228ede1d68 <a_free+24>      ret
│    0x7f228ede1d69                  nopl   0x0(%rax)
```

gdb backtrace
```
#0  0x00007f228ede1d55 in a_free () from /nix/store/3qwn9mhnpy8q2b7nfxbp7czc6lhiywlh-obs-studio-27.0.1/lib/libobs.so.0
#1  0x00007f2237d51ae8 in update_info_destroy () from /nix/store/3qwn9mhnpy8q2b7nfxbp7czc6lhiywlh-obs-studio-27.0.1//lib/obs-plugins/rtmp-services.so
#2  0x00007f2237d50900 in obs_module_unload () from /nix/store/3qwn9mhnpy8q2b7nfxbp7czc6lhiywlh-obs-studio-27.0.1//lib/obs-plugins/rtmp-services.so
#3  0x00007f228ee392fc in free_module () from /nix/store/3qwn9mhnpy8q2b7nfxbp7czc6lhiywlh-obs-studio-27.0.1/lib/libobs.so.0
#4  0x00007f228ee13fcf in obs_shutdown () from /nix/store/3qwn9mhnpy8q2b7nfxbp7czc6lhiywlh-obs-studio-27.0.1/lib/libobs.so.0
#5  0x00000000004b11d5 in OBSApp::~OBSApp() ()
#6  0x000000000048238b in main ()
```

### Steps To Reproduce
Non-deterministic, I don't know what exactly causes the behavior, besides the stuff mentioned above.

### Expected behavior
Neither pipewire threads nor OBS should segfault when trying to remove a screen-sharing connection.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.76, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211108_7a71621`
 - nixpkgs: `/etc/nix-flake-channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - obs-studio
  - pipewire
  - xdg-desktop-portal-wlr
# a list of nixos modules affected by the problem
module:
```

**Comment by fpletz** [comment]
We've packaged new versions of OBS and a new pipewire capture plugin. Closing this for now since this is an old issue. Please reopen if this still is an issue.
