### ISSUE TITLE
wpscan 3.8.19 crashes at startup

### ISSUE THREAD

**Issue by zseri** [NixOS/nixpkgs#146826]
### Describe the bug
```
Traceback (most recent call last):
	6: from /nix/store/whasmak8l86lmfhjbrhv08rsdj6y1fjy-wpscan-3.8.19/bin/.wpscan-wrapped:19:in `<main>'
	5: from /nix/store/j68sj34yx1szr5hmblxvvyfs2vcyl3bi-bundler-2.2.24/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler.rb:149:in `setup'
	4: from /nix/store/j68sj34yx1szr5hmblxvvyfs2vcyl3bi-bundler-2.2.24/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/runtime.rb:18:in `setup'
	3: from /nix/store/j68sj34yx1szr5hmblxvvyfs2vcyl3bi-bundler-2.2.24/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/definition.rb:244:in `specs_for'
	2: from /nix/store/j68sj34yx1szr5hmblxvvyfs2vcyl3bi-bundler-2.2.24/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/spec_set.rb:85:in `materialize'
	1: from /nix/store/j68sj34yx1szr5hmblxvvyfs2vcyl3bi-bundler-2.2.24/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/spec_set.rb:85:in `map!'
/nix/store/j68sj34yx1szr5hmblxvvyfs2vcyl3bi-bundler-2.2.24/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/spec_set.rb:90:in `block in materialize': Could not find nokogiri-1.12.4-x86_64-linux in any of the sources (Bundler::GemNotFound)
```

### Steps To Reproduce
1. Install `wpscan` from nixpkgs 17f73e226198a511a74a953758ceed6efdad9444
2. Run the `result/bin/wpscan` file

### Expected behavior
`wpscan` shouldn't crash.

### Notify maintainers

@nyanloutre @manveru

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.76, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211108_7a71621`
 - nixpkgs: `/etc/nix-flake-channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - wpscan
# a list of nixos modules affected by the problem
module:
```

**Comment by fabaff** [comment]
3.8.20 works for me.

```bash
$ nix-env -iA nixos.wpscan
$ wpscan --url 192.168.1.1
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.20
       Sponsored by Automattic - https://automattic.com/
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________


Scan Aborted: The remote website is up, but does not seem to be running WordPress.
````

**Comment by fabaff** [comment]
> /nix/store/j68sj34yx1szr5hmblxvvyfs2vcyl3bi-bundler-2.2.24/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/spec_set.rb:90:in `block in materialize': Could not find nokogiri-1.12.4-x86_64-linux in any of the sources (Bundler::GemNotFound)

Not the first time, that `nokogiri` causes trouble. Adding `dependencies = ["mini_portile2" "racc"];`` for `nokogiri` in `gemset.nix` could help.

**Comment by Scriptkiddi** [comment]
3.8.20 is also broken for me, @fabaff does it work for you when you run things with `nix-shell -p wpscan`?
