### ISSUE TITLE
"How to install NixOS from Linux" instructions don't work

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#14680]
### Steps to reproduce

Follow the steps listed at https://nixos.org/wiki/How_to_install_NixOS_from_linux

## Technical details

The `chroot . /$INIT` command fails:

    chroot: failed to run command `/./nix/store/.../init': No such file or directory

**Comment by ericsagnes** [comment]
Some parts of the wiki are outdated and is in process to be moved in the manual.

You can try [nixos-in-place](https://github.com/jeaye/nixos-in-place) instead.

**Comment by chris-martin** [comment]
I'm not trying to install in-place; I'm trying to install onto a different partition.

**Comment by joachifm** [comment]
Probably something to bring up when/if this gets ported to the manual: https://github.com/NixOS/nixpkgs/issues/13305. That said, to me it looks like the wiki is all but abandoned at this point, so not sure if you can expect any errors therein to be fixed.

**Comment by chris-martin** [comment]
In the meantime, I would like to use NixOS - Is there a way to do what I'm trying to do? I can't use the boot CD due to #5829.

**Comment by joachifm** [comment]
Those instructions are ridiculously complex ... When you're installing from a live cd, all you basically do is: partition the disk, install file systems, mount the rootfs on `/mnt`, then run nixos-install targeting `/mnt` as the rootfs. I don't know why that wouldn't work from any other running Linux system.

**Comment by chris-martin** [comment]
> run nixos-install

How do I do that in Ubuntu? Install `nixos-install` using the Nix package manager?

**Comment by wkennington** [comment]
Because you have to install nix, and the nixos tools, and somehow unmount
root, then overwrite the disk and reboot.

**Comment by chris-martin** [comment]
Why do I have to unmount root or overwrite anything if I'm installing NixOS to a different partition?

**Comment by joachifm** [comment]
Anything more complex than `mount /dev/sdaX /mnt; bootstrap /mnt` just looks bad. 

Anyways ...

@chris-martin I'm assuming that you copied `nix/store` from the live-cd into `$installPrefix/nix/store` and then called `chroot $installPrefix /nix/store/*-nixos-*/init`? Looks to me like that *should* work.

**Comment by joachifm** [comment]
It does work.
```
% mkdir nixos-iso
% mount -o loop nixos.iso nixos-iso 
% targetRoot=/mnt
# mount partition on $targetRoot here
% mkdir -p $targetRoot/nix
% unsquashfs -d $targetRoot/nix nixos-iso/nix-store.squashfs '*'
% cd $targetRoot
% chroot . nix/store/*-nixos-system-*/init
```

**Comment by chris-martin** [comment]
All I've tried so far is following the wiki instructions verbatim. I'll give that a shot tomorrow.

**Comment by joachifm** [comment]
Okay. Everything you might need *should* be under `$targetRoot/nix/store`.

**Comment by nickjanus** [comment]
I just wanted to note that the above did not work for me in an arch install.  I've since found a thumb drive, so I'll copy the iso over and install that way.
```
[root@hydra mnt]# chroot . nix/store/*-nixos-system-*/init

<<< NixOS Stage 2 >>>

mount: / not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
rm: cannot remove '/var/setuid-wrappers': Device or resource busy
running activation script...
setting up /etc...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
starting systemd...
Trying to run as user instance, but the system has not been booted with systemd.
```

Looking through dmesg, it seems as if the setup of /etc is what failed
```
#### Activation script snippet etc:
# Set up the statically computed bits of /etc.
echo "setting up /etc..."
/nix/store/48zgyzbngzsl2nysql1jpfghkfbzgx4q-perl-5.22.1/bin/perl -I/nix/store/xmpplvvfj1xddsiclbbvw4aw4hxz073c-perl-File-Slurp-9999.19/lib/perl5/site_perl /nix/store/1hzvalfcpsryma
```

dmesg:
```
[ 1042.611566] booting system configuration /nix/store/sxi78zg2vb0ip6h96frcb0bbymk5mfw2-nixos-system-nixos-16.03.769.f98d57b
[ 1042.648038] stage-2-init: running activation script...
[ 1042.652991] stage-2-init: setting up /etc...
[ 1042.654452] stage-2-init: perl: warning: Setting locale failed.
[ 1042.654535] stage-2-init: perl: warning: Please check that your locale settings:
[ 1042.654582] stage-2-init: LANGUAGE = (unset),
[ 1042.654624] stage-2-init: LC_ALL = (unset),
[ 1042.654664] stage-2-init: LANG = "en_US.utf8"
[ 1042.654715] stage-2-init: are supported and installed on your system.
[ 1042.654769] stage-2-init: perl: warning: Falling back to the standard locale ("C").
[ 1042.720300] stage-2-init: perl: warning: Setting locale failed.
[ 1042.720363] stage-2-init: perl: warning: Please check that your locale settings:
[ 1042.720402] stage-2-init: LANGUAGE = (unset),
[ 1042.720438] stage-2-init: LC_ALL = (unset),
[ 1042.720472] stage-2-init: LANG = "en_US.utf8"
[ 1042.720515] stage-2-init: are supported and installed on your system.
[ 1042.720561] stage-2-init: perl: warning: Falling back to the standard locale ("C").
```

**Comment by joachifm** [comment]
@nickjanus looks to me like the only relevant info in the output is
> mount: / not mounted or bad option
       In some cases useful info is found in syslog - try
       dmesg | tail or so.
rm: cannot remove '/var/setuid-wrappers': Device or resource busy

Almost all the other output is locale warnings which doesn't help much in figuring out what the problem is here.

**Comment by chris-martin** [comment]
@joachifm I just tried your instructions on Ubuntu 16.04, and the last step fails with:

```
starting systemd...
Trying to run as user instance, but the system has not been booted with systemd.
```

**Comment by joachifm** [comment]
@chris-martin I kind of swapped this out of my memory, sorry. The sequence of commands is complete as I recall, executed on arch linux. If you want nixos-install, I'd think running init would be redundant. The point is to get into an environment where all the tools required to do the install are available (extracting from the iso has to give you everything you need, provided the ISO works at all). If Nix store paths resolve as expected (i.e., `/nix/store` is available on the host), I'd expect to be able to run the nixos-install command without chrooting first, but it's hard to tell because I don't know the state of your system.

In the steps I posted, you could instead of chrooting, copy the `nix` directory to `/nix` on the host and proceed from there, without chrooting. You'd then prepare the partition, mount it and any other filesystem on `/mnt`, then call `/nix/store/whatever/bin/nixos-install /mnt`.

**Comment by chris-martin** [comment]
`nixos-install` fails with:

```
warning: the group 'nixbld' specified in 'build-users-group' does not exist
./...nixos-install/bin/nixos-install: line 204: nix-instantiate: command not found
readline: missing operand
Try 'readlink --help' for more information.
```

**Comment by joachifm** [comment]
The `nixbld` thing just means you have to create the group on the host.

To overcome the nix-instantiate issue you'd need to add `/nix/store/*-nix-*/bin` or whatever to your `PATH`. It's unfortunate and a little surprising that it doesn't hard-code the full path or setup a suitable `PATH` itself, though, I think that goes against the idea that everything in the store be self-contained.

chroot + activate/init would get you into a consistent environment; the alternative is to read the nixos-install script to determine which of its assumptions disagrees with your current host and adjust manually as needed.

**Comment by chris-martin** [comment]
Did these additional things:

* `groupadd nixbld`
* Add `nixos-install` and `nix-instantiate` to `PATH`
* `git clone --depth 1 https://github.com/NixOS/nxpkgs-channels.git -b nixos-16.09`
* `export NIX_PATH=nixpkgs=$HOME/nixpkgs-channels`

Now nixos-install fails with:

    error: the build users group 'nixbld' has no members

**Comment by joachifm** [comment]
Typically you'd also do
```sh
for i in $(seq 1 $numberOfBuildUsers) ; do
  useradd --system -d /var/empty -s $nologin -g $nixbuildGroup nixbld$i
done
```
or something to add the build users. In this case you probably only need one.

**Comment by chris-martin** [comment]
Hm, I created a user

```
useradd --system -d /var/empty -s $(which nologin) -g nixbld nixbld1
```

and verified it does belong to the group

```
# groups nixbld1
nixbld1 : nixbld
```

But oddly still get the same

    error: the build users group 'nixbld' has no members

**Comment by chris-martin** [comment]
Ah ha, the build user must also have `nixbld` as a supplementary group:

    useradd --system -d /var/empty -s $(which nologin) -g nixbld -G nixbld nixbld0

**Comment by chris-martin** [comment]
New errors:

```
copying NixOS/Nixpkgs sources...

*** Copying ‘/nix/store/gmakdl3svnnrsp9glv525990ix1iysjc-nixos-16.09.1647.ff7777b’ from ‘/tmp/root/nix/store/gmakdl3svnnrsp9glv525990ix1iysjc-nixos-16.09.1647.ff7777b’

created 1 symlinks in user environment
finalising the installation...
Failed to check file system type of "/boot": No such file or directory
Traceback (most recent call last):
  File "/nix/store/cfl6jcwzz3gi3bfdh151hkyaj4hx1sdg-systemd-boot-builder.py", line 102, in <module>
    subprocess.check_call(["/nix/store/41psl3b534rdwl2nva0ljs7mmjly14b7-systemd-231/bin/bootctl", "--path=/boot", "install"])
  File "/nix/store/a21ahiimxzb3gc9vgdvxqlv4p4n5iph8-python-2.7.13/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/41psl3b534rdwl2nva0ljs7mmjly14b7-systemd-231/bin/bootctl', '--path=/boot', 'install']' returned non-zero exit status 1
```

This is the same error I got when trying to use nixos-in-place.

**Comment by joachifm** [comment]
What is under `/boot`?

**Comment by joachifm** [comment]
Note that `bootctl` expects the `--path` argument to point to the EFI system partition mount point.

**Comment by chris-martin** [comment]
Okay, I didn't have an EFI system partition. Trying again...

**Comment by chris-martin** [comment]
Is that `/boot` on the host, or `/mnt/boot`?

**Comment by joachifm** [comment]
That steps runs via `chroot` so `/mnt/boot` makes sense.

**Comment by chris-martin** [comment]
Okay, this is starting to make sense and I've made some comprehensive notes on what I've done so far:

https://gist.github.com/chris-martin/4ead9b0acbd2e3ce084576ee06961000

It seems to be compiling everything. Is there something special I need to do to get it to pull from Hydra?

**Comment by chris-martin** [comment]
I think we're making progress!

But `nixos-install` still fails.

```
cp /tmp/nix-build-gcc-5.4.0.drv-0/gcc-5.4.0/libstdc++-v3/config/abi/pre/gnu.ver libstdc++-symbols.ver.tmp
make[6]: *** No rule to make target '../src/c++98/libc++98convenience.la', needed by 'libstdc++.la'.  Stop.
make[6]: *** Waiting for unfinished jobs....
chmod +w libstdc++-symbols.ver.tmp
if test "x../../../../gcc-5.4.0/libstdc++-v3/config/abi/pre/float128.ver" != x; then \
  if grep '^# Appended to version file.' \
       ../../../../gcc-5.4.0/libstdc++-v3/config/abi/pre/float128.ver > /dev/null 2>&1; then \
    cat ../../../../gcc-5.4.0/libstdc++-v3/config/abi/pre/float128.ver >> libstdc++-symbols.ver.tmp; \
  else \
    sed -n '1,/DO NOT DELETE/p' libstdc++-symbols.ver.tmp > tmp.top; \
    sed -n '/DO NOT DELETE/,$p' libstdc++-symbols.ver.tmp > tmp.bottom; \
    cat tmp.top ../../../../gcc-5.4.0/libstdc++-v3/config/abi/pre/float128.ver tmp.bottom > libstdc++-symbols.ver.tmp; \
    rm tmp.top tmp.bottom; \
  fi; \
fi
```
[...]
```
make[6]: Leaving directory '/tmp/nix-build-gcc-5.4.0.drv-0/build/x86_64-unknown-linux-gnu/libstdc++-v3/src'
Makefile:637: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/tmp/nix-build-gcc-5.4.0.drv-0/build/x86_64-unknown-linux-gnu/libstdc++-v3/src'
Makefile:507: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/tmp/nix-build-gcc-5.4.0.drv-0/build/x86_64-unknown-linux-gnu/libstdc++-v3'
Makefile:414: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/tmp/nix-build-gcc-5.4.0.drv-0/build/x86_64-unknown-linux-gnu/libstdc++-v3'
Makefile:13033: recipe for target 'all-stageprofile-target-libstdc++-v3' failed
make[2]: *** [all-stageprofile-target-libstdc++-v3] Error 2
make[2]: Leaving directory '/tmp/nix-build-gcc-5.4.0.drv-0/build'
Makefile:20345: recipe for target 'stageprofile-bubble' failed
make[1]: *** [stageprofile-bubble] Error 2
make[1]: Leaving directory '/tmp/nix-build-gcc-5.4.0.drv-0/build'
Makefile:20481: recipe for target 'profiledbootstrap' failed
make: *** [profiledbootstrap] Error 2
builder for ‘/nix/store/rlxvy2fhgpa9crv87zpaj9nkazzvqh6r-gcc-5.4.0.drv’ failed with exit code 2
```
[...]
```
error: build of ‘/nix/store/cjkjg31wyzd32si4bfgpkf3ln7wr1hjc-nixos-system-nixos-16.09pre-git.drv’ failed
```

**Comment by joachifm** [comment]
It's a little surprising that it wants to rebuild this stuff. Feels like this may be a symptom of Nix not being initialized properly or something. I think there are too many unknowns for me to give more specific advice here, but consider that the install procedure (to disk, with bootloader) basically is
1. Build NixOS system on install host (strictly optional, you could use a pre-built system)
2. Prepare and mount filesystems; copy NixOS system from step 1 ontop
3. Install bootloader entry, arranging for it to run the NixOS kernel and stage2 init (which in turn runs activation)
4. Reboot

I'm sure that all the problems you're seeing stem from mismatches between the assumed and actual execution environment.
