### ISSUE TITLE
pythonPackages.numpy: f2py script missing

### ISSUE THREAD

**Issue by bzizou** [NixOS/nixpkgs#14692]
## Issue description
The f2py script is missing in the package. It should be in the bin directory.

### Steps to reproduce

Install python2.7-numpy package and try to launch the "f2py" command.
If I take a "f2py" script from an OS (for example redhat 6.3), and adapt the shebang to the nix python package, it works fine. So only the script is missing, everything else is ok (the f2py python module is ok).

## Technical details

* System: RHEL 6.3
* Nix version: 1.11.1
* Nixpkgs version: 16.03pre-git

**Comment by FRidh** [comment]
This is indeed missing. Since so far nobody seemed to need it I didn't bother fixing this.

**Comment by bzizou** [comment]
Thank you for this comment. Well, you now found someone who needs it ;-) Do you plan to fix it or do you want me to investigate into the build process? I've no idea of what caused this lack of script for now...

**Comment by FRidh** [comment]
Test error:
```
test_scripts.test_f2py ... FAIL

======================================================================
FAIL: test_scripts.test_f2py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/mcbrxgzcy12yd51gm8w9xwfy8gabqy9x-python3.5-nose-1.3.7/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/nix/store/w7d3x53i8d099idj7v603rjgs8m7psn7-python3.5-numpy-1.11.0/lib/python3.5/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/nix/store/w7d3x53i8d099idj7v603rjgs8m7psn7-python3.5-numpy-1.11.0/lib/python3.5/site-packages/numpy/tests/test_scripts.py", line 99, in test_f2py
    assert_(success, msg)
  File "/nix/store/w7d3x53i8d099idj7v603rjgs8m7psn7-python3.5-numpy-1.11.0/lib/python3.5/site-packages/numpy/testing/utils.py", line 71, in assert_
    raise AssertionError(smsg)
AssertionError: Warning: neither f2py nor f2py3 nor f2py3.5 found in path
```


Actually, `f2py3.5m` does work.
```
$ nix-shell -p pythonPackages.numpy --run f2py3.5m -v
2
```
But indeed, `f2py` is missing. I could add symbolic links.

**Comment by reckbo** [comment]
I got this error (pasted below)  just when trying to install  numpy for the first time via nox.  However it installed fine after running

    nix-env -i python2.7-numpy-1.11.0

    installing ‘python2.7-numpy-1.11.0’
    building path(s) ‘/nix/store/f610ak803yl0hr37j4qp1jih8l9svj6q-user-environment’
    created 1193 symlinks in user environment

I'd like to be able to install without test errors though, so I can distribute an app that needs numpy
to users.

Ryan

----
test_matlib.test_repmat ... ok
test_numpy_version.test_valid_numpy_version ... ok
test_scripts.test_f2py ... FAIL

======================================================================
FAIL: test_scripts.test_f2py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/frs7yp6ggv972r8784zyvxlf2nwbf9fx-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/nix/store/n0xkqwagcq3fvivsain0db15nbpya9g2-python2.7-numpy-1.11.0/lib/python2.7/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/nix/store/n0xkqwagcq3fvivsain0db15nbpya9g2-python2.7-numpy-1.11.0/lib/python2.7/site-packages/numpy/tests/test_scripts.py", line 99, in test_f2py
    assert_(success, msg)
  File "/nix/store/n0xkqwagcq3fvivsain0db15nbpya9g2-python2.7-numpy-1.11.0/lib/python2.7/site-packages/numpy/testing/utils.py", line 71, in assert_
    raise AssertionError(smsg)
AssertionError: Warning: neither f2py nor f2py2 nor f2py2.7 found in path

----------------------------------------------------------------------

**Comment by FRidh** [comment]
@reckbo 
```
nix-env -i python2.7-numpy-1.11.0
```
is unsupported. See https://github.com/NixOS/nixpkgs/issues/10597.

**Comment by FRidh** [comment]
This is an upstream issue (https://github.com/numpy/numpy/issues/7532#issuecomment-229778862), so I am closing this.

A PR adding a symbolic link as I suggested is welcome :)

**Comment by FRidh** [comment]
symlink is added in d4c7f583017c66434aba907769809bec75a562e3
