### ISSUE TITLE
rubyPackages.rmagick fails to install 

### ISSUE THREAD

**Issue by sarkologist** [NixOS/nixpkgs#146987]
### Describe the bug
installing the ruby package `rmagick` fails on darwin

### Steps To Reproduce
1. `nix-env -iA nixpkgs.rubyPackages.rmagick`

### Additional context
```
$ nix-env -iA nixpkgs.rubyPackages.rmagick
installing 'ruby2.7.4-rmagick-4.2.3'
these derivations will be built:
  /nix/store/slfvgd3yihss7jp5fj0pvjd04n1kjppj-ruby2.7.4-rmagick-4.2.3.drv
building '/nix/store/slfvgd3yihss7jp5fj0pvjd04n1kjppj-ruby2.7.4-rmagick-4.2.3.drv'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
installing
buildFlags:
WARNING:  You build with buildroot.
  Build root: /
  Bin dir: /nix/store/xdjldwmmsji1d34ygyh51zpm4sigr87d-ruby2.7.4-rmagick-4.2.3/lib/ruby/gems/2.7.0/bin
  Gem home: /nix/store/xdjldwmmsji1d34ygyh51zpm4sigr87d-ruby2.7.4-rmagick-4.2.3/lib/ruby/gems/2.7.0
  Plugins dir: /nix/store/xdjldwmmsji1d34ygyh51zpm4sigr87d-ruby2.7.4-rmagick-4.2.3/lib/ruby/gems/2.7.0/plugins
Building native extensions. This could take a while...
ERROR:  Error installing /nix/store/8jrhhh8i32wqx8a0ld7i259afhskxxpm-rmagick-4.2.3.gem:
        ERROR: Failed to build gem native extension.

    current directory: /nix/store/xdjldwmmsji1d34ygyh51zpm4sigr87d-ruby2.7.4-rmagick-4.2.3/lib/ruby/gems/2.7.0/gems/rmagick-4.2.3/ext/RMagick
/nix/store/6pmrf1633z5c9b73w6a8ah4h65gxhqvb-ruby-2.7.4/bin/ruby -I /nix/store/6pmrf1633z5c9b73w6a8ah4h65gxhqvb-ruby-2.7.4/lib/ruby/2.7.0 -r ./siteconf20211122-91605-cvrrdm.rb extconf.rb
checking for brew... no
checking for pacman... no
checking for Ruby version >= 2.3.0... yes
checking for pkg-config... yes
checking for outdated ImageMagick version (<= 6.7.7)... no
checking for clang... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/nix/store/6pmrf1633z5c9b73w6a8ah4h65gxhqvb-ruby-2.7.4/bin/$(RUBY_BASE_NAME)
extconf.rb:219:in ``': No such file or directory - file (Errno::ENOENT)
        from extconf.rb:219:in `configure_archflags_for_osx'
        from extconf.rb:77:in `configure_compile_options'
        from extconf.rb:19:in `initialize'
        from extconf.rb:398:in `new'
        from extconf.rb:398:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /nix/store/xdjldwmmsji1d34ygyh51zpm4sigr87d-ruby2.7.4-rmagick-4.2.3/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-17/2.7.0/rmagick-4.2.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /nix/store/xdjldwmmsji1d34ygyh51zpm4sigr87d-ruby2.7.4-rmagick-4.2.3/lib/ruby/gems/2.7.0/gems/rmagick-4.2.3 for inspection.
Results logged to /nix/store/xdjldwmmsji1d34ygyh51zpm4sigr87d-ruby2.7.4-rmagick-4.2.3/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-17/2.7.0/rmagick-4.2.3/gem_make.out
builder for '/nix/store/slfvgd3yihss7jp5fj0pvjd04n1kjppj-ruby2.7.4-rmagick-4.2.3.drv' failed with exit code 1
error: build of '/nix/store/slfvgd3yihss7jp5fj0pvjd04n1kjppj-ruby2.7.4-rmagick-4.2.3.drv' failed
```
### Notify maintainers

@marsam @siraben (sorry guys, if i tagged you wrong, was using git blame)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.16`
 - channels(sark): `"nixos-21.05pre295530.e74894146a4, nixpkgs-21.11pre329221.c11d08f0239"`
 - nixpkgs: `/Users/sark/.nix-defexpr/channels/nixpkgs
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.rubyPackages.rmagick
# a list of nixos modules affected by the problem
module:
```

**Comment by rickhull** [comment]
> `extconf.rb:219:in ``': No such file or directory - file (Errno::ENOENT)`

I'd guess the nixpkg `file` is missing from the the buildInputs
