### ISSUE TITLE
Vortex mod manager

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#147228]
**Project description**

From the [home page](https://www.nexusmods.com/site/mods/1):

> Vortex is the new, modern mod manager from Nexus Mods. It is designed to make modding your game as simple as possible for new users, while still providing enough control for more experienced veterans of the modding scene. Lead by Tannin, the creator of Mod Organizer, Vortex takes the lessons learnt during the development of MO and Nexus Mod Manager to provide the most powerful and intuitive modding experience available.
> 
> Our approach with Vortex aims to take complex tasks such as sorting your load order or managing your mod files and automates as much of the process as possible with the goal of having you achieve a stable modded game with minimal effort. We want to help you spend less time modding and more time playing your games.

**Metadata**

* homepage URL: https://www.nexusmods.com/site/mods/1
* source URL: https://github.com/Nexus-Mods/Vortex
* license: GPLv3
* platforms: Mainly Windows. [Builds & runs on Linux](https://github.com/Nexus-Mods/Vortex/issues/2862#issuecomment-625742078), but currently unsupported. Nix's reproducible builds makes it the perfect platform to showcase this advanced gaming software on Linux.

Update: I'm not sure HEAD builds on Linux. I used the following shell.nix:

```
{ pkgs ? import
    (
      fetchTarball
        {
          name = "21.05";
          url = "https://github.com/NixOS/nixpkgs/archive/7e9b0dff974c89e070da1ad85713ff3c20b0ca97.tar.gz";
          sha256 = "1ckzhh24mgz6jd1xhfgx0i9mijk6xjqxwsshnvq789xsavrmsc36";
        })
    { }
}:
pkgs.mkShell {
  buildInputs = [
    pkgs.mono
    pkgs.nodejs
    pkgs.python3
    pkgs.yarn
  ];
}
```

The build result:

```console
$ yarn install
yarn install v1.22.10
$ git submodule update --init --recursive
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > modmeta-db@0.7.0" has incorrect peer dependency "commander@^6.1.0".
warning " > modmeta-db@0.7.0" has unmet peer dependency "express@^4.14.0".
warning "react-sortable-tree > frontend-collective-react-dnd-scrollzone@1.0.2" has incorrect peer dependency "react-dnd@^7.3.0".
[4/4] Building fresh packages...
[7/17] ⠄ icon-extract
[14/17] ⠄ @bitdisaster/exe-icon-extractor
[3/17] ⠄ drivelist
[9/17] ⠄ libxmljs
error /home/user/Vortex/node_modules/icon-extract: Command failed.
Exit code: 1
Command: npm run autogypi && node-gyp configure build
Arguments: 
Directory: /home/user/Vortex/node_modules/icon-extract
Output:
npm WARN lifecycle The node binary used for scripts is /run/user/1000/yarn--1637737991396-0.008285407273942225/node but npm is using /nix/store/cdalbhzm3z4gz07wyg89maprdbjc4yah-nodejs-14.17.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> icon-extract@1.1.0 autogypi /home/user/Vortex/node_modules/icon-extract
> autogypi

gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.17.0 | linux | x64
gyp info find Python using Python version 3.8.9 found at "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/bin/python3"
gyp info spawn /nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/user/Vortex/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/Vortex/node_modules/icon-extract/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/Vortex/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.cache/node-gyp/13.1.6/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/13.1.6',
gyp info spawn args   '-Dnode_gyp_dir=/home/user/Vortex/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/13.1.6/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/Vortex/node_modules/icon-extract',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/user/Vortex/node_modules/icon-extract/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  AR(target) Release/obj.target/node_modules/node-addon-api/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/IconExtractor/src/IconExtractor.o
make: Leaving directory '/home/user/Vortex/node_modules/icon-extract/build'
In file included from ../src/IconExtractor.cpp:1:
../node_modules/node-addon-api/napi.h:32:6: error: #error Exception support not detected. Define either NAPI_CPP_EXCEPTIONS or NAPI_DISABLE_CPP_EXCEPTIONS.
   32 |     #error Exception support not detected. \
      |      ^~~~~
../src/IconExtractor.cpp:9:10: fatal error: IconExtractorLinux.h: No such file or directory
    9 | #include "IconExtractorLinux.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [IconExtractor.target.mk:118: Release/obj.target/IconExtractor/src/IconExtractor.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/Vortex/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.10.79
gyp ERR! command "/nix/store/cdalbhzm3z4gz07wyg89maprdbjc4yah-nodejs-14.17.0/bin/node" "/home/user/Vortex/node_modules/icon-extract/node_modules/.bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/user/Vortex/node_modules/icon-extract
```

**Comment by K1aymore** [comment]
I'd like this as well; I can't install the Stardew Valley modding API on NixOS, but this mod manager should make it work.

**Comment by natto1784** [comment]
bump

**Comment by l0b0** [comment]
I got started on [a branch](https://github.com/NixOS/nixpkgs/pull/203404), but it's currently failing to build:

> Error: Couldn't find any versions for "node-gyp" that matches "^9.0.0" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.

Not sure what to do about this. If anyone else is up for it, feel free to fork and ideally add yourself as a maintainer @K1aymore @natto1784 @meutraa.

**Comment by natto1784** [comment]
It won't build just like that, there are some of the dependencies that need to be patched and overall requires some more native deps like mono and freefont, it should be package-able after some time though. I have managed to run it on my system but it is one of the forks (by the person who was helping with the stuff related to the linux "port") and that fork has some extensions disabled due to win-only headers of those deps.

**Comment by l0b0** [comment]
Cancelling this since there's now [NexusMods.App, which already supports Linux](https://github.com/Nexus-Mods/NexusMods.App/issues/148).
