### ISSUE TITLE
todoist-electron had been broken recently on 21.11-beta

### ISSUE THREAD

**Issue by pshirshov** [NixOS/nixpkgs#147319]
```
❯ /nix/store/wdaaz48ysjdnhpibjs5gan4lf4mz6jhq-electron-16.0.1/lib/electron/.electron-wrapped --enable-crashpad /nix/store/r7h4rjzv2zjcs3lk5vb8wan5nbc2xi8c-todoist-electron-1.0.1/share/todoist-electron/resources/app.asar
App threw an error during load
Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2027)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/nix/store/r7h4rjzv2zjcs3lk5vb8wan5nbc2xi8c-todoist-electron-1.0.1/share/todoist-electron/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2027)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/nix/store/r7h4rjzv2zjcs3lk5vb8wan5nbc2xi8c-todoist-electron-1.0.1/share/todoist-electron/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
[12005:1125/004602.340700:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
^C%
```

**Comment by sersorrel** [comment]
todoist-electron works fine for me with the following override:

```nix
  (self: super: {
    todoist-electron = super.todoist-electron.override {
      electron = super.electron_15;
    };
  })
```

Electron 16 was made the default quite recently in d421ffb4832b176675aa82e83921e3a41b4f9700.

This kind of problem has happened before with todoist-electron, in #116101.

**Comment by kylesferrazza** [comment]
I have no problems using `todoist-electron` with electron 16. 

@pshirshov looks like you're skipping the line in the wrapper that sets LD_LIBRARY_PATH (hence why the app could not find `libsecret` in your library path):

```
❯ cat $(which todoist-electron)
#! /nix/store/a54wrar1jym1d8yvlijq0l2gghmy8szz-bash-5.1-p12/bin/bash -e
export LD_LIBRARY_PATH='/nix/store/2nkjrh3za68vrw6kf8lxn6nq1dval05v-gcc-10.3.0-lib/lib:/nix/store/6l20vnpppmx7q12k6s1mjxg21nc6rp8j-libsecret-0.20.4/lib'${LD_LIBRARY_PATH:+':'}$LD_LIBRARY_PATH
exec "/nix/store/ph5g8gpaaxl4v6mq1psqvzipxvi8w1pf-electron-16.0.4/bin/electron"  /nix/store/lbpipppbc9jsd25bbnrmif6gd83wzkdg-todoist-electron-1.0.1/share/todoist-electron/resources/app.asar "$@"
```

Try running the `export` line first (or just running the `todoist-electron` wrapper directly, and let me know if it still doesn't work for you?

**Comment by pshirshov** [comment]
```
~ on ☁️  (eu-west-1)
❯ cat $(which todoist-electron)
#! /nix/store/l0wlqpbsvh1pgvhcdhw7qkka3d31si7k-bash-5.1-p8/bin/bash -e
export LD_LIBRARY_PATH='/nix/store/c9f15p1kwm0mw5p13wsnvd1ixrhbhb12-gcc-10.3.0-lib/lib:/nix/store/5zfwh3wmvm0xny4pxvmy3sa1wbfxcsii-libsecret-0.20.4/lib'${LD_LIBRARY_PATH:+':'}$LD_LIBRARY_PATH
exec "/nix/store/bp7g8pf1fmaajkjpppg9facm1hdzkn4f-electron-16.0.2/bin/electron"  /nix/store/a6blg401n4h5av0g3z0w8vscs4y1ml6p-todoist-electron-1.0.1/share/todoist-electron/resources/app.asar "$@"

~ on ☁️  (eu-west-1)
❯ export LD_LIBRARY_PATH='/nix/store/c9f15p1kwm0mw5p13wsnvd1ixrhbhb12-gcc-10.3.0-lib/lib:/nix/store/5zfwh3wmvm0xny4pxvmy3sa1wbfxcsii-libsecret-0.20.4/lib'${LD_LIBRARY_PATH:+':'}$LD_LIBRARY_PATH

~ on ☁️  (eu-west-1)
❯ todoist-electron
[245101:1215/165041.935393:FATAL:double_fork_and_exec.cc(131)] execv /nix/store/bp7g8pf1fmaajkjpppg9facm1hdzkn4f-electron-16.0.2/lib/electron/chrome_crashpad_handler: No such file or directory (2)
<hangs here>
^C 

~ on ☁️  (eu-west-1) took 5s
❯

```

**Comment by pshirshov** [comment]
The 16->15 monkeypatch works fine.

**Comment by pshirshov** [comment]
Still broken

**Comment by kylesferrazza** [comment]
> Still broken

Are you seeing the same `libsecret` issue?

**Comment by sersorrel** [comment]
I see the same behaviour as @pshirshov; the `libsecret` error if I run todoist by hand with `.electron-wrapped`, and the `chrome_crashpad_handler` error if I just run `todoist-electron` directly.

**Comment by kylesferrazza** [comment]
Will be updated to Electron 24 in #237663. Please confirm whether you are still seeing this? I am unable to reproduce.

**Comment by kylesferrazza** [comment]
https://github.com/NixOS/nixpkgs/pull/237663#issuecomment-1597798813
