### ISSUE TITLE
using magic-wormhole gives "ZIP does not support timestamps before 1980"

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#147840]
### Describe the bug
When using magic-wormhole on unstable , I get 
ZIP does not support timestamps before 1980

### Steps To Reproduce
```
nix run .#magic-wormhole send ~/.ssh      
Building zipfile..
Traceback (most recent call last):
  File "/nix/store/175q50xfvc9d6h9qpq6iz2s0nsdxk94j-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/nix/store/175q50xfvc9d6h9qpq6iz2s0nsdxk94j-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/internet/defer.py", line 1751, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
  File "/nix/store/175q50xfvc9d6h9qpq6iz2s0nsdxk94j-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
    result = current_context.run(
  File "/nix/store/175q50xfvc9d6h9qpq6iz2s0nsdxk94j-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/nix/store/gic4b9nb8w7hfnfhf6ks8d6lr7q29f7q-python3.9-magic-wormhole-0.12.0/lib/python3.9/site-packages/wormhole/cli/cli.py", line 122, in _dispatch_command
    yield maybeDeferred(command)
  File "/nix/store/175q50xfvc9d6h9qpq6iz2s0nsdxk94j-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
    result = current_context.run(
  File "/nix/store/175q50xfvc9d6h9qpq6iz2s0nsdxk94j-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/nix/store/gic4b9nb8w7hfnfhf6ks8d6lr7q29f7q-python3.9-magic-wormhole-0.12.0/lib/python3.9/site-packages/wormhole/cli/cmd_send.py", line 93, in go
    yield d
  File "/nix/store/175q50xfvc9d6h9qpq6iz2s0nsdxk94j-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/nix/store/gic4b9nb8w7hfnfhf6ks8d6lr7q29f7q-python3.9-magic-wormhole-0.12.0/lib/python3.9/site-packages/wormhole/cli/cmd_send.py", line 107, in _go
    offer, self._fd_to_send = self._build_offer()
  File "/nix/store/gic4b9nb8w7hfnfhf6ks8d6lr7q29f7q-python3.9-magic-wormhole-0.12.0/lib/python3.9/site-packages/wormhole/cli/cmd_send.py", line 365, in _build_offer
    zf.write(localfilename, archivename)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/zipfile.py", line 1727, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/zipfile.py", line 517, in from_file
    zinfo = cls(arcname, date_time)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/zipfile.py", line 361, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
builtins.ValueError: ZIP does not support timestamps before 1980
ERROR: ZIP does not support timestamps before 1980




```

### Notify maintainers

@asymmetric 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.2, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - nixpkgs: `/home/teto/nixpkgs`
```

**Comment by asymmetric** [comment]
@teto which version of nixpkgs are you running the program from?

Running this from master, I can't repro:

```
❯ nix run github:nixos/nixpkgs#magic-wormhole -- send ~/foo.json 
Sending 892 Bytes file named 'foo.json'
Wormhole code is: 95-fascinate-apple
On the other computer, please run:

wormhole receive 95-fascinate-apple
```

**Comment by teto** [comment]
@asymmetric wormhole creates a zip when it needs to send several files so you wont trigger the behavior with just one: try the same command with a folder for instance (just tried it and could see my initial error)

**Comment by asymmetric** [comment]
```
❯ nix run github:nixos/nixpkgs/nixos-21.11#magic-wormhole -- send ranger.conf/
Building zipfile..
Sending directory (33.5 kB compressed) named 'ranger.conf'
Wormhole code is: 5-hurricane-spaniel
On the other computer, please run:

wormhole receive 5-hurricane-spaniel
```

Can you run the same exact command?

**Comment by tournemire** [comment]
I can reproduce using the command above.

nix-info:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(dara): `"home-manager, nixos-unstable-22.05pre333986.73369f8d086"`
 - channels(root): `"nixos-22.05pre333986.73369f8d086"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment]
I can reproduce (dont mind the aws error, it's because my clock is not synchronized and I have an s3 substituter configured).
```
➜ nix run github:nixos/nixpkgs/nixos-21.11#magic-wormhole -- send ~/.ssh
AWS error 'RequestTimeTooSkewed' (The difference between the request time and the current time is too large.), will retry in 0 ms
Building zipfile..
Traceback (most recent call last):
  File "/nix/store/w6fqk428szyzsphqrh59c0f6p085z5js-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/nix/store/w6fqk428szyzsphqrh59c0f6p085z5js-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/internet/defer.py", line 1751, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
  File "/nix/store/w6fqk428szyzsphqrh59c0f6p085z5js-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
    result = current_context.run(
  File "/nix/store/w6fqk428szyzsphqrh59c0f6p085z5js-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/nix/store/dff0vfmjy7dsa6ja8lhrsqrlm060pjs6-python3.9-magic-wormhole-0.12.0/lib/python3.9/site-packages/wormhole/cli/cli.py", line 122, in _dispatch_command
    yield maybeDeferred(command)
  File "/nix/store/w6fqk428szyzsphqrh59c0f6p085z5js-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
    result = current_context.run(
  File "/nix/store/w6fqk428szyzsphqrh59c0f6p085z5js-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/nix/store/dff0vfmjy7dsa6ja8lhrsqrlm060pjs6-python3.9-magic-wormhole-0.12.0/lib/python3.9/site-packages/wormhole/cli/cmd_send.py", line 93, in go
    yield d
  File "/nix/store/w6fqk428szyzsphqrh59c0f6p085z5js-python3.9-Twisted-21.7.0/lib/python3.9/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/nix/store/dff0vfmjy7dsa6ja8lhrsqrlm060pjs6-python3.9-magic-wormhole-0.12.0/lib/python3.9/site-packages/wormhole/cli/cmd_send.py", line 107, in _go
    offer, self._fd_to_send = self._build_offer()
  File "/nix/store/dff0vfmjy7dsa6ja8lhrsqrlm060pjs6-python3.9-magic-wormhole-0.12.0/lib/python3.9/site-packages/wormhole/cli/cmd_send.py", line 365, in _build_offer
    zf.write(localfilename, archivename)
  File "/nix/store/5bh6rpya1ar6l49vrhx1rg58dsa42906-python3-3.9.6/lib/python3.9/zipfile.py", line 1727, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/nix/store/5bh6rpya1ar6l49vrhx1rg58dsa42906-python3-3.9.6/lib/python3.9/zipfile.py", line 517, in from_file
    zinfo = cls(arcname, date_time)
  File "/nix/store/5bh6rpya1ar6l49vrhx1rg58dsa42906-python3-3.9.6/lib/python3.9/zipfile.py", line 361, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
builtins.ValueError: ZIP does not support timestamps before 1980
ERROR: ZIP does not support timestamps before 1980
```

**Comment by asymmetric** [comment]
I'm not quite know how to debug this further. Running wormhole with the latest commit on the `nixos-21.11` branch Works On My Machine(tm), which is:

```
❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.79, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.05.650.eaba7870ffc"`
 - channels(asymmetric): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
  ```

```
❯ nix run github:nixos/nixpkgs/e34c5379866833f41e2a36f309912fa675d687c7#magic-wormhole -- send ~/.ssh
Building zipfile..
Sending directory (35.3 kB compressed) named '.ssh'
Wormhole code is: 1-pacific-trouble
On the other computer, please run:

wormhole receive 1-pacific-trouble
```

**Comment by r-burns** [comment]
Try it with a nix-created directory which will typically have a unix-epoch (1970) mtime. Zip files use msdos dates which start at 1980. Here's a better reproducer:

```
$ nix-build -A magic-wormhole
$ ./result/bin/wormhole send ./result/bin/
```

This is certainly annoying but seems to be working as intended. Perhaps ask upstream for a `.tar.gz` option?

**Comment by asymmetric** [comment]
@r-burns great catch! My `~/.ssh` is not managed by NixOS/HM, which explains why I couldn't reproduce.

I would say this closes the issue on our end then. Thanks everyone!

**Comment by piegamesde** [comment]
This is a fundamental flaw in zip files and its usage in the Magic Wormhole protocol. See https://github.com/magic-wormhole/magic-wormhole/issues/401 for an upstream tracking issue.

**Comment by teto** [comment]
for people arriving here, I've just used https://github.com/magic-wormhole/magic-wormhole.rs/ that doesn't suffer from the issue
