### ISSUE TITLE
yarn2nix: support yarn 2.x

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#148042]
### Describe the bug

yarn 2 with zero-installs

```
❯ yarn2nix > yarn.nix
/nix/store/5qpfawd2jcj6lx944jiyz6ldxwdag0zr-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/@yarnpkg/lockfile/index.js:5064
    throw new SyntaxError(`${msg} ${this.token.line}:${this.token.col} in ${this.fileLoc}`);
    ^

SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile
    at Parser.unexpected (/nix/store/5qpfawd2jcj6lx944jiyz6ldxwdag0zr-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/@yarnpkg/lockfile/index.js:5064:11)
    at Parser.parse (/nix/store/5qpfawd2jcj6lx944jiyz6ldxwdag0zr-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/@yarnpkg/lockfile/index.js:5193:14)
    at parse (/nix/store/5qpfawd2jcj6lx944jiyz6ldxwdag0zr-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/@yarnpkg/lockfile/index.js:5262:17)
    at Object.module.exports.exports.default (/nix/store/5qpfawd2jcj6lx944jiyz6ldxwdag0zr-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/@yarnpkg/lockfile/index.js:4835:96)
    at Object.<anonymous> (/nix/store/5qpfawd2jcj6lx944jiyz6ldxwdag0zr-yarn2nix-1.0.0/libexec/yarn2nix/deps/yarn2nix/bin/yarn2nix.js:48:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
```

### Steps To Reproduce
1. ...
2. ...
3. ...

### Notify maintainers
@yu-re-ka

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.3-zen1, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(root): `"nixos-21.11pre299825.d8079260a30"`
 - nixpkgs: `/run/current-system/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by yu-re-ka** [comment]
yarn 2 has a completely different lockfile format and will likely never be supported by yarn2nix

**Comment by asymmetric** [comment]
Let's close this then, and reopen if/when support does come.
