### ISSUE TITLE
mkvtoolnix-62.0.0 fails a test on x86_64-darwin

### ISSUE THREAD

**Issue by tricktron** [NixOS/nixpkgs#148111]
### Describe the bug
`mkvtoolnix` 62.0.0 fails a test on x86_64-darwin:

```log
running tests
LC_ALL=C ./tests/unit/common/common
rake aborted!
TypeError: no implicit conversion from nil to integer
/private/tmp/nix-build-mkvtoolnix-63.0.0.drv-0/source/rake.d/helpers.rb:42:in `exit'
/private/tmp/nix-build-mkvtoolnix-63.0.0.drv-0/source/rake.d/helpers.rb:42:in `run'
/private/tmp/nix-build-mkvtoolnix-63.0.0.drv-0/source/rake.d/gtest.rb:12:in `block (3 levels) in <top (required)>'
/private/tmp/nix-build-mkvtoolnix-63.0.0.drv-0/source/rake.d/gtest.rb:12:in `each'
/private/tmp/nix-build-mkvtoolnix-63.0.0.drv-0/source/rake.d/gtest.rb:12:in `block (2 levels) in <top (required)>'
/nix/store/cjfxidyh7ffaj0mm617a2ggbac7k9dim-rake-12.3.2/lib/ruby/gems/2.7.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => tests:run_unit
(See full trace by running task with --trace)
builder for '/nix/store/n1l9d4ixmr76zq9hdqljm3snp83nx3pb-mkvtoolnix-63.0.0.drv' failed with exit code 1
```

Full log: https://hydra.nixos.org/build/159777645/nixlog/2/tail

### Steps To Reproduce
`nix-build -A mkvtoolnix-cli`

### Expected behavior
Build with tests succeed.

### Notify maintainers
@rnhmjoj  @codyopel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-darwin"`
- host os: `Darwin 20.6.0, macOS 10.16`
- multi-user?: `yes`
- sandbox: `no`
- version: `nix-env (Nix) 2.5pre20211007_844dd90`
- channels(tricktron): `"unstable-21.11pre329388.f096b7122ab"`
- channels(root): `"nixpkgs-21.05pre285827.267761cf444"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by tricktron** [comment]
Closing because we are already at version 67.0.0 and the build works again https://hydra.nixos.org/build/178202705.
