### ISSUE TITLE
esphome seems broken - upload fails - ERROR Running command failed: fileno

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#148332]
yay python

```
~/code/nixcfg_backup/hosts/xeep/modules/home-assistant/esphome main* ⇡ 54s
❯ esphome upload desk110.yaml
INFO Reading configuration desk110.yaml...
Found multiple options, please choose one:
  [1] /dev/ttyUSB1 (CP2102 USB to UART Bridge Controller - CP2102 USB to UART Bridge Controller)
  [2] Over The Air (192.168.69.110)
(number): 1
ERROR Running command failed: fileno
ERROR Please try running platformio run -d desk110 -t idedata locally.
Traceback (most recent call last):
  File "/nix/store/h0xkwl4n9vwdkc4yv73qrwbjx97c41fv-esphome-2021.10.1/bin/.esphome-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/h0xkwl4n9vwdkc4yv73qrwbjx97c41fv-esphome-2021.10.1/lib/python3.9/site-packages/esphome/__main__.py", line 815, in main
    return run_esphome(sys.argv)
  File "/nix/store/h0xkwl4n9vwdkc4yv73qrwbjx97c41fv-esphome-2021.10.1/lib/python3.9/site-packages/esphome/__main__.py", line 802, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/nix/store/h0xkwl4n9vwdkc4yv73qrwbjx97c41fv-esphome-2021.10.1/lib/python3.9/site-packages/esphome/__main__.py", line 343, in command_upload
    exit_code = upload_program(config, args, port)
  File "/nix/store/h0xkwl4n9vwdkc4yv73qrwbjx97c41fv-esphome-2021.10.1/lib/python3.9/site-packages/esphome/__main__.py", line 255, in upload_program
    return upload_using_esptool(config, host)
  File "/nix/store/h0xkwl4n9vwdkc4yv73qrwbjx97c41fv-esphome-2021.10.1/lib/python3.9/site-packages/esphome/__main__.py", line 241, in upload_using_esptool
    rc = run_esptool(first_baudrate)
  File "/nix/store/h0xkwl4n9vwdkc4yv73qrwbjx97c41fv-esphome-2021.10.1/lib/python3.9/site-packages/esphome/__main__.py", line 198, in run_esptool
    idedata = platformio_api.get_idedata(config)
  File "/nix/store/h0xkwl4n9vwdkc4yv73qrwbjx97c41fv-esphome-2021.10.1/lib/python3.9/site-packages/esphome/platformio_api.py", line 149, in get_idedata
    idedata = IDEData(_load_idedata(config))
  File "/nix/store/h0xkwl4n9vwdkc4yv73qrwbjx97c41fv-esphome-2021.10.1/lib/python3.9/site-packages/esphome/platformio_api.py", line 137, in _load_idedata
    data = _run_idedata(config)
  File "/nix/store/h0xkwl4n9vwdkc4yv73qrwbjx97c41fv-esphome-2021.10.1/lib/python3.9/site-packages/esphome/platformio_api.py", line 105, in _run_idedata
    match = re.search(r'{\s*".*}', stdout)
  File "/nix/store/5bh6rpya1ar6l49vrhx1rg58dsa42906-python3-3.9.6/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

current nixos-unstable

**Comment by dotlambda** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/148180
