### ISSUE TITLE
tdesktop crashes in rlottie with existing .local/share/TelegramDesktop/tdata

### ISSUE THREAD

**Issue by koiuo** [NixOS/nixpkgs#148769]
### Describe the bug

telegram-desktop from the latest unstable crashes on an attempt to open any chat
```
[Switching to Thread 0x7fffab47f640 (LWP 523877)]
0x00007ffff70ae84e in rlottie::internal::model::PathData::lerp(rlottie::internal::model::PathData const&, rlottie::internal::model::PathData const&, float, VPath&) () from /nix/store/hx7nrgspgq98hfhli3vh14bb0xzkgqm7-rlottie-0.2/lib/librlottie.so.0
(gdb) bt full
#0  0x00007ffff70ae84e in rlottie::internal::model::PathData::lerp(rlottie::internal::model::PathData const&, rlottie::internal::model::PathData const&, float, VPath&) () from /nix/store/hx7nrgspgq98hfhli3vh14bb0xzkgqm7-rlottie-0.2/lib/librlottie.so.0
No symbol table info available.
#1  0x3eaaaaab3f800000 in ?? ()
No symbol table info available.
#2  0x0000000000000000 in ?? ()
No symbol table info available.
```

Removing `.local/share/TelegramDesktop/tdata` fixes the issue
**WARNING**: this removes all the configuration including *existing sessions*

I guess the issue is the migration from rlottie-0.1 to rlottie-0.2 and backward-incompatible changes in the latter

### Steps To Reproduce
1. open telegram-desktop
2. open any chat
3. observe telegram segfaulting

### Expected behavior
telegram-desktop does not crash

### Notify maintainers
@oxalica @primeos @VergeDX @CRTified

**Comment by koiuo** [comment]
no longer relevant
