### ISSUE TITLE
[unstable regression] semiphemeral 0.6 is broken

### ISSUE THREAD

**Issue by zseri** [NixOS/nixpkgs#148966]
### Describe the bug
```console
$ semiphemeral delete
semiphemeral 0.6
Traceback (most recent call last):
  File "/nix/store/gs8wbrrr471ci3iw104qqymi7vlga19z-semiphemeral-0.6/bin/.semiphemeral-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/clp40m7w86scbhby5cq6wr9p6lxy77sl-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/clp40m7w86scbhby5cq6wr9p6lxy77sl-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/nix/store/clp40m7w86scbhby5cq6wr9p6lxy77sl-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/clp40m7w86scbhby5cq6wr9p6lxy77sl-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/clp40m7w86scbhby5cq6wr9p6lxy77sl-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/gs8wbrrr471ci3iw104qqymi7vlga19z-semiphemeral-0.6/lib/python3.9/site-packages/semiphemeral/__init__.py", line 68, in delete
    t = Twitter(common)
  File "/nix/store/gs8wbrrr471ci3iw104qqymi7vlga19z-semiphemeral-0.6/lib/python3.9/site-packages/semiphemeral/twitter.py", line 31, in __init__
    self.api = tweepy.API(
TypeError: __init__() got an unexpected keyword argument 'wait_on_rate_limit_notify'
```

failing lines:
```python
        self.api = tweepy.API(
            auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True
        )
```

### Steps To Reproduce
Install `semiphemeral` from nixpkgs b9982bcba7b0a54e004f73ece06743768c1781cd (afaik forked at fafe9a8d0414682365fac2fb123b2d3389faeab7), setup it with Twitter API keys and then invoke the above mentioned command `semiphemeral delete` (`semiphemeral stats` also works to produce the same effect, but `semiphemeral configure` doesn't directly trigger it).

### Expected behavior
semiphemeral shouldn't crash. as with nixpgks 17f73e226198a511a74a953758ceed6efdad9444

### Additional context
config repo: https://github.com/zseri/nixos-configs

```console
$ # working version:
$ j=/nix/store/sp3yiijjw98n4ixl38axk071g4mj8gbl-semiphemeral-0.6; for i in bin/semiphemeral nix-support/propagated-build-inputs; do cat "$j/$i"; echo; done
#! /nix/store/5r4i6d1jiapjvbaamqsbmdn849mh4q6q-bash-5.1-p8/bin/bash -e
export PATH='/nix/store/94whplwl4afl2jngcpm573wgfvxr7cf5-python3-3.9.6/bin:/nix/store/sp3yiijjw98n4ixl38axk071g4mj8gbl-semiphemeral-0.6/bin:/nix/store/w3c7iclvqf2zpgv24rjzk2n32272bahr-python3.9-Flask-2.0.1/bin:/nix/store/jkjjjrjp1v3w1qvf53x3wsh5xpnr5wnn-python3.9-python-dotenv-0.19.0/bin:/nix/store/1mzqm8wb6fh5awk8p2pbs4x8fmh6pk7q-python3.9-Babel-2.9.1/bin:/nix/store/advfk84y603k4yry1ndj31d2j0cyl5m1-python3.9-watchdog-2.1.5/bin:/nix/store/1d63hsawy0iw43g0lc472b0l1xrvi7q4-python3.9-charset-normalizer-2.0.1/bin:/nix/store/qywv7rci26fzq5rsfr364755zq7zgiqp-python3.9-chardet-4.0.0/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/sp3yiijjw98n4ixl38axk071g4mj8gbl-semiphemeral-0.6/bin/.semiphemeral-wrapped"  "$@"

/nix/store/dvv37jhxhra7805bv2qidypspyx73zdv-python3.9-click-8.0.1 /nix/store/q6xfr6hlvjxzlksfdfxil8wlhb5dkpv0-python3.9-SQLAlchemy-1.4.25 /nix/store/w3c7iclvqf2zpgv24rjzk2n32272bahr-python3.9-Flask-2.0.1 /nix/store/xr05wh7cblr08xcqlg7f53a621sbs9kd-python3.9-tweepy-3.10.0 /nix/store/r90s4a7mlxb51hykcv0p8kyx95c8bp6k-python3.9-colorama-0.4.4 /nix/store/94whplwl4afl2jngcpm573wgfvxr7cf5-python3-3.9.6 

$ # broken version:
$ j=/nix/store/gs8wbrrr471ci3iw104qqymi7vlga19z-semiphemeral-0.6; for i in bin/semiphemeral nix-support/propagated-build-inputs; do cat "$j/$i"; echo; done
#! /nix/store/1f7awrfnxjy40zw7vqyaib31yzpfsbqv-bash-5.1-p8/bin/bash -e
export PATH='/nix/store/yl510xpzpr17dsarb4mammnm829bw3qd-python3-3.9.6/bin:/nix/store/gs8wbrrr471ci3iw104qqymi7vlga19z-semiphemeral-0.6/bin:/nix/store/2k8zy579fps7p26rhr6w24yb2m6lp5ll-python3.9-Flask-2.0.2/bin:/nix/store/cn4b5nzl868q0vfqybv5dmywnd8a6zrp-python3.9-python-dotenv-0.19.0/bin:/nix/store/bf7yr308ps7pnnlpxb04mc567f04xsid-python3.9-Babel-2.9.1/bin:/nix/store/4li22j6wq7c6m21ljzx47vcy4frgxqmi-python3.9-watchdog-2.1.6/bin:/nix/store/q3gslkrf71w374rls7xhkmd5dp0q3qcl-python3.9-charset-normalizer-2.0.5/bin:/nix/store/a015fvjjfdabi74p22wi34ygbdpcc6d0-python3.9-cchardet-2.1.7/bin:/nix/store/96zas1g9i4r69c1xn9y4vl4a9s33k3z6-python3.9-chardet-4.0.0/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/gs8wbrrr471ci3iw104qqymi7vlga19z-semiphemeral-0.6/bin/.semiphemeral-wrapped"  "$@"

/nix/store/clp40m7w86scbhby5cq6wr9p6lxy77sl-python3.9-click-8.0.3 /nix/store/x3klm44rqw7zr17khk22yfmwkmfw5fan-python3.9-SQLAlchemy-1.4.27 /nix/store/2k8zy579fps7p26rhr6w24yb2m6lp5ll-python3.9-Flask-2.0.2 /nix/store/l4b8i35kmbxfvkbs5bmvhckdx40xr3m9-python3.9-tweepy-4.4.0 /nix/store/lqb4vcskdn4xvnf667xkcm9npwr259yw-python3.9-colorama-0.4.4 /nix/store/yl510xpzpr17dsarb4mammnm829bw3qd-python3-3.9.6 
```

### Notify maintainers
@amanjeev

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211202_3f3561f`
 - nixpkgs: `/etc/nix-flake-channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - semiphemeral
# a list of nixos modules affected by the problem
module:
```

**Comment by amanjeev** [comment]
Thank you for the detailed report.  I will take a look at this asap.
