### ISSUE TITLE
playonlinux can't find libgobject

### ISSUE THREAD

**Issue by spacehitchhiker42** [NixOS/nixpkgs#14914]
## Issue description
added playonlinux  to systempackages. running playonlinux form the terminal gives this output

```
Looking for python... 2.7.11 - wxversion(s): 2.8-gtk2-unicode
Traceback (most recent call last):
  File "/nix/store/1n29m7iq3szxhxwydvrvqmjbhg2apvji-playonlinux-4.2.9/share/playonlinux/python/check_python.py", line 7, in <module>
    import wx
  File "/nix/store/830m9na34q830g085bz7970n8fpisvvb-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/nix/store/830m9na34q830g085bz7970n8fpisvvb-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
failed tests
Looking for python2.7... 2.7.11 - wxversion(s): 2.8-gtk2-unicode
Traceback (most recent call last):
  File "/nix/store/1n29m7iq3szxhxwydvrvqmjbhg2apvji-playonlinux-4.2.9/share/playonlinux/python/check_python.py", line 7, in <module>
    import wx
  File "/nix/store/830m9na34q830g085bz7970n8fpisvvb-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/nix/store/830m9na34q830g085bz7970n8fpisvvb-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
failed tests
Looking for python2.6... which: no python2.6 in (/nix/store/fyhkq4h356cfpnaxgglphxhgrlawva7s-cabextract-1.6/bin:/nix/store/ccmyi36pqr600f2bq7nivbahnczkfqf3-python-2.7.11/bin:/nix/store/s6z1y55yaic8vyfkpa92q7ybyzrkwkdl-gettext-0.19.7/bin:/nix/store/vzz1j63w5vs4iqydbyq606jxwdgq3cpc-glxinfo-8.1.0/bin:/nix/store/1pv8z79v2cii2yqgg2jhr7m1bs7bb89j-gnupg1compat-0/bin:/nix/store/wr3vp60m2iajm1dqmfwdq6nkkajay857-icoutils-0.31.0/bin:/nix/store/9jsmiibvlxkrl7mwvp993dj2w6zsc9cw-imagemagick-6.9.2-0/bin:/nix/store/dm6x6i27p88cqdmr705gbr1cisy7j9l6-netcat-gnu-0.7.1/bin:/nix/store/8sh5vy2cav8ngdv7rdis2nl2j251l3jp-p7zip-9.38/bin:/nix/store/73n658r4lkdxn1460zgfyypxad7bnj12-unzip-6.0/bin:/nix/store/mfji387mbxrs9x6hwixfknr6qhnm768k-wget-1.17.1/bin:/nix/store/fa3h51605pqsw6yaij6k4c9g6vc7nw4d-wine-1.8.1/bin:/nix/store/9i4d67ngqsw50c68j8jymy9clz8r4r0h-xdg-user-dirs-0.15/bin:/nix/store/gmki25inmk8dn0lrf34x2pcc7inymc60-xterm-320/bin:/nix/store/pxmb3i6anrh86rwsr1f58h52imd4p2rg-which-2.21/bin:/nix/store/yd4bk6biwjiinzi96kwx4wiaxjnrz8sl-curl-7.47.1/bin:/root/bin:/var/setuid-wrappers:/root/.nix-profile/bin:/root/.nix-profile/sbin:/root/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/run/current-system/sw/bin:/run/current-system/sw/sbin:/run/current-system/sw/lib/kde4/libexec)

Looking for python2... 2.7.11 - wxversion(s): 2.8-gtk2-unicode
Traceback (most recent call last):
  File "/nix/store/1n29m7iq3szxhxwydvrvqmjbhg2apvji-playonlinux-4.2.9/share/playonlinux/python/check_python.py", line 7, in <module>
    import wx
  File "/nix/store/830m9na34q830g085bz7970n8fpisvvb-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/nix/store/830m9na34q830g085bz7970n8fpisvvb-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
failed tests
Please install python before trying to run this program
```

### Steps to reproduce
install playonlinux and try to run from terminal

## Technical details

* System: 16.03.503.3f96280 (Emu)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.03.503.3f96280

**Comment by FRidh** [comment]
Error also occurs on very recent master.

**Comment by Twey** [comment]
This is an error with wxPython in general, not just with playonlinux.  All wxPython packages are (presumably) currently broken at runtime.

**Comment by spacehitchhiker42** [comment]
why would wxpython not be able to find gobject?

**Comment by Radivarig** [comment]
@Twey based on this  #13956

**Comment by Twey** [comment]
That bug was closed a month ago, but I was still having the issue with HEAD a week and a half ago, so I don't think it's the same bug.

**Comment by anderspapitto** [comment]
a simpler repro is

```
[anders@gurney:~]$ nix-build -E 'with import <nixpkgs> { }; python.buildEnv.override { extraLibs = [ pythonPackages.wxPython28 ]; }'
/nix/store/mksl7hn3kzgjsdid9340ll8cvdwk9hd3-python-2.7.11-env

[anders@gurney:~]$ echo import wx | ./result/bin/python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/mksl7hn3kzgjsdid9340ll8cvdwk9hd3-python-2.7.11-env/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/nix/store/mksl7hn3kzgjsdid9340ll8cvdwk9hd3-python-2.7.11-env/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by anderspapitto** [comment]
another note: setting LD_LIBRARY_PATH=${pkgs.glib.out}/lib fixes this issue, however I'm not quite sure what the best way is to incorporate that into the wxPython derivation. Adding `glib.out` to `buildInputs` or `propagatedBuildInputs` doesn't fix it.

**Comment by FRidh** [comment]
`_core` is indeed not having a path to the library, just having the name of it. 
We should likely just patch the source and replace any reference to this library with the full path. This is done more often in python-packages.nix, though mostly when cffi is used.
See https://github.com/NixOS/nixpkgs/issues/7307

**Comment by spacehitchhiker42** [comment]
patchelf maybe?

**Comment by FRidh** [comment]
I think we should be able to patch `_core.so` or else wrap the playonlinux binary with a wrapper where we set  `LD_LIBRARY_PATH`.

**Comment by seschwar** [comment]
A workaround would be building playonlinux against wxPython30. This produces a working package. However wxPython28 remains broken.

**Comment by FRidh** [comment]
If POL works with wxPython30 then that's a good solution. There aren't many packages left using wxPython28 so hopefully soon we can get rid of it then.
