### ISSUE TITLE
fpm seems to be broken

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#15042]
## Issue description

Running `fpm` results in a crash as follows:

```
$ result/bin/fpm
/nix/store/0lwpkxcnnsv92i48ms94dvhhfib6bba4-fpm-1.4.0/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:263:in `attach': unhandled exception
	from /nix/store/0lwpkxcnnsv92i48ms94dvhhfib6bba4-fpm-1.4.0/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:263:in `attach_function'
	from /nix/store/0lwpkxcnnsv92i48ms94dvhhfib6bba4-fpm-1.4.0/lib/ruby/gems/2.3.0/gems/fpm-1.4.0/lib/fpm/util.rb:16:in `rescue in <module:Util>'
	from /nix/store/0lwpkxcnnsv92i48ms94dvhhfib6bba4-fpm-1.4.0/lib/ruby/gems/2.3.0/gems/fpm-1.4.0/lib/fpm/util.rb:12:in `<module:Util>'
	from /nix/store/0lwpkxcnnsv92i48ms94dvhhfib6bba4-fpm-1.4.0/lib/ruby/gems/2.3.0/gems/fpm-1.4.0/lib/fpm/util.rb:6:in `<top (required)>'
	from /nix/store/0lwpkxcnnsv92i48ms94dvhhfib6bba4-fpm-1.4.0/lib/ruby/gems/2.3.0/gems/fpm-1.4.0/lib/fpm/package.rb:2:in `require'
	from /nix/store/0lwpkxcnnsv92i48ms94dvhhfib6bba4-fpm-1.4.0/lib/ruby/gems/2.3.0/gems/fpm-1.4.0/lib/fpm/package.rb:2:in `<top (required)>'
	from /nix/store/0lwpkxcnnsv92i48ms94dvhhfib6bba4-fpm-1.4.0/lib/ruby/gems/2.3.0/gems/fpm-1.4.0/lib/fpm.rb:3:in `require'
	from /nix/store/0lwpkxcnnsv92i48ms94dvhhfib6bba4-fpm-1.4.0/lib/ruby/gems/2.3.0/gems/fpm-1.4.0/lib/fpm.rb:3:in `<top (required)>'
	from /nix/store/0lwpkxcnnsv92i48ms94dvhhfib6bba4-fpm-1.4.0/lib/ruby/gems/2.3.0/gems/fpm-1.4.0/bin/fpm:5:in `require'
	from /nix/store/0lwpkxcnnsv92i48ms94dvhhfib6bba4-fpm-1.4.0/lib/ruby/gems/2.3.0/gems/fpm-1.4.0/bin/fpm:5:in `<top (required)>'
	from result/bin/fpm:18:in `load'
	from result/bin/fpm:18:in `<main>'
```
### Steps to reproduce

1. Get nixpkgs 3a542c737414d8cc4d8759997983f596fcd6a6a
2. Run `nix-build -A fpm` from your clone
3. Run ./result/bin/fpm
4. Be sad

cc @vcunat who added the package

### Other stuff

I'm running this on NixOS, on x86_64.

**Comment by copumpkin** [comment]
Hmm, this doesn't seem to be broken on my machine anymore, even on the same commit. I guess I should be worried, but I'll just close this for now.

**Comment by vcunat** [comment]
I don't think anything similar has ever happened to me.
