### ISSUE TITLE
Waydroid does not start due to binder not being present

### ISSUE THREAD

**Issue by madonius** [NixOS/nixpkgs#150755]
### Describe the bug
When trying to execute `waydroid init` I get
```console
> # waydroid init
[21:00:45] Failed to load binder driver
[21:00:45] modprobe: FATAL: Module binder_linux not found in directory /run/current-system/kernel-modules/lib/modules/5.10.81
[21:00:45] ERROR: Binder node "binder" for waydroid not found
[21:00:45] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
`waydroid log` yields:
```console
(004488) [21:00:45] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /run/current-system/kernel-modules/lib/modules/5.10.81
(004488) [21:00:45] Failed to load binder driver
(004488) [21:00:45] modprobe: FATAL: Module binder_linux not found in directory /run/current-system/kernel-modules/lib/modules/5.10.81
(004488) [21:00:45] ERROR: Binder node "binder" for waydroid not found
(004488) [21:00:45] See also: <https://github.com/waydroid>
(004488) [21:00:45] Traceback (most recent call last):
  File "/nix/store/wzc8a0y2kznbgvr69kciymypa89iiim3-waydroid-1.2.0/lib/python3.9/site-packages/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/nix/store/wzc8a0y2kznbgvr69kciymypa89iiim3-waydroid-1.2.0/lib/python3.9/site-packages/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/nix/store/wzc8a0y2kznbgvr69kciymypa89iiim3-waydroid-1.2.0/lib/python3.9/site-packages/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/nix/store/wzc8a0y2kznbgvr69kciymypa89iiim3-waydroid-1.2.0/lib/python3.9/site-packages/tools/helpers/drivers.py", line 137, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found
```

### Steps To Reproduce
1. Install waydroid ( I added it in my configuration.nix)
2. Run `waydroid init`

### Expected behavior
I would expect waydroid to initialise its environment

### Notify maintainers

@FlorianFranzen 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(madonius): `"home-manager-21.11, nixos-21.11.334139.1bd4bbd49be, nixpkgs-21.11.334139.1bd4bbd49be, nixpkgs-unstable-22.05pre337603.47f45c8440e, sops-nix"`
 - channels(root): `"nixos-20.09.4125.7974217f94c, sops-nix, unstable-21.05pre281538.9e377a6ce42"`
 - nixpkgs: `/home/madonius/.nix-defexpr/channels/nixpkgs`
```

**Comment by Artturin** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/148442

Status can be tracked at https://nixpk.gs/pr-tracker.html?pr=148442
