### ISSUE TITLE
Gajim 1.3.3 does not build

### ISSUE THREAD

**Issue by sheepforce** [NixOS/nixpkgs#151767]
### Describe the bug
`gajim` does not build in nixpkgs-unstable, nixos-21.11 and master. The test phase fails with python import errors for emoji data.
Thus gajim seems broken in current NixOS and branches.
```
======================================================================
ERROR: gajim_mocks (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: gajim_mocks
Traceback (most recent call last):
  File "/nix/store/wl02plhc6zf84m6x9984l42wnnnbly5m-python3-3.9.6/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/build/gajim-gajim-1.3.3/test/lib/gajim_mocks.py", line 9, in <module>
    from gajim.common.connection_handlers import ConnectionHandlers
  File "/build/gajim-gajim-1.3.3/gajim/common/connection_handlers.py", line 33, in <module>
    from gajim.common.connection_handlers_events import PresenceReceivedEvent
  File "/build/gajim-gajim-1.3.3/gajim/common/connection_handlers_events.py", line 25, in <module>
    from gajim.common import helpers
  File "/build/gajim-gajim-1.3.3/gajim/common/helpers.py", line 84, in <module>
    from gajim.common.regex import INVALID_XML_CHARS_REGEX
  File "/build/gajim-gajim-1.3.3/gajim/common/regex.py", line 76, in <module>
    EMOT_AND_LINK_REGEX = re.compile(_get_emot_and_basic_pattern(False),
  File "/build/gajim-gajim-1.3.3/gajim/common/regex.py", line 58, in _get_emot_and_basic_pattern
    from gajim.gui.emoji_data import emoji_data
ModuleNotFoundError: No module named 'gajim.gui.emoji_data'


----------------------------------------------------------------------
Ran 4 tests in 0.869s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=4 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=4 errors=1 failures=0>
```

### Steps To Reproduce
1. `nix-build https://github.com/NixOS/nixpkgs/archive/9ab7d12287ced0e1b4c03b61c781901f178d9d77.tar.gz -A gajim` (current head of nixos-21.11)

### Expected behavior
Gajim builds without any errors.

### Additional context
Possibly introduced by https://github.com/NixOS/nixpkgs/commit/7545018f7ddae97eef2a6502195fb3aac409c38f#diff-6994d9de30403b7069f343ba1c9ef2f65b076de6604df84fda43aff6cd8d752aL61

### Notify maintainers
@raskin
@abbradar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.10, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(root): `"nixos-21.11.334639.9ab7d12287c"`
 - channels(phillip): `"nixpkgs-22.05pre339108.2d555e5f652"`
 - nixpkgs: `/home/phillip/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: `gajim`
```

**Comment by DeeUnderscore** [comment]
Looks like it builds now in [nixos-21.11](https://hydra.nixos.org/build/162015501) and [master](https://hydra.nixos.org/build/162156238)

**Comment by ony** [comment]
I confirm that after updating `nixpkgs`
```plain
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/1158f3463912d54cc981d61213839ec6c02570d3' (2021-12-23)
  → 'github:nixos/nixpkgs/00f84d37a2507dee0219cf894f11a7cbf0c49ccb' (2021-12-24)
```
I got Gajim back.

**Comment by sheepforce** [comment]
Yup, can confirm. Works again, now.
