### ISSUE TITLE
Atom: Module did not self-register

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#15267]
This is not an actual issue with Nix right now.
What I am trying to do is update the Atom package.
1.7 and 1.8-beta behave the same way, I chose 1.8 because I figure by the time I have this figured out, 1.8 will be out.

Here is the issue:
Before 1.7 (master currently has 1.6.2 I believe), the Atom package was perfectly fine.
Since 1.7 there some weirdness going on that I believe to be caused by a node.js package.
And I have spent considerable time trying to fix it and cannot.
I am hoping to get some help from people familiar with node.

I do not know how to link GitHub branches in tickets, but I essentially just changed the Atom expression to use 1.8.0-beta3.
A few things needed fixing, nothing major. Everything builds fine.
Upon opening ./result/bin/atom the editor opens but immediately the Chrome Dev Tools open and report the following, which I cannot seem to figure out.

Any ideas from anybody? :D

Poking @svanderburg @gilligan because they look like the resident JS experts :)

```
Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:170:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:218:4)
    at Module._compile (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:9:10)
    at Object.<anonymous> (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1482:4)
    at Module._compile (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/src/project.js:18:16)
    at Object.<anonymous> (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/src/project.js:529:4)
    at Module._compile (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/nix/store/g99swn9z76palwyfj02mmf7rrzwj0n7v-atom-1.8.0-beta3/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by mythmon** [comment]
@NeQuissimus did you find out what the problem was here? I think I'm running into a similar issue. Recording the solution here (if any) would be very helpful.

**Comment by NeQuissimus** [comment]
No, I never did find out. People are saying it works but it even happened to me on a clean installation. I started to think that it has something to do with other software I am using but I eventually switched back to Sublime Text since I did not have the time to investigate any deeper into this.
