### ISSUE TITLE
VS Code: Error about missing `jschardet` when opening menu/file

### ISSUE THREAD

**Issue by FPtje** [NixOS/nixpkgs#152939]
### Describe the bug

I just updated my personal `flake.lock` to the latest `nixos-21.11`, revision `8a053bc2255659c5ca52706b9e12e76a8f50dbdd`. VS Code has become practically unusable. When I try to open a file, an error pops up on the bottom left about missing module `jschardet`. The `Log (Window)` output shows the full error:

```
[2021-12-31 14:57:42.331] [renderer1] [error] Cannot find module 'jschardet'
Require stack:
- electron/js2c/renderer_init: Error: Cannot find module 'jschardet'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Function.t._resolveFilename (electron/js2c/renderer_init.js:45:859)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.t._load (electron/js2c/renderer_init.js:45:307)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at r (vscode-file://vscode-app/nix/store/p4w9h4r2480vmjfcfw5h8nzc61wnkg0s-vscode-1.63.2/lib/vscode/resources/app/out/vs/loader.js:5:101)
    at e.load (vscode-file://vscode-app/nix/store/p4w9h4r2480vmjfcfw5h8nzc61wnkg0s-vscode-1.63.2/lib/vscode/resources/app/out/vs/loader.js:3:11528)
    at e.load (vscode-file://vscode-app/nix/store/p4w9h4r2480vmjfcfw5h8nzc61wnkg0s-vscode-1.63.2/lib/vscode/resources/app/out/vs/loader.js:3:10695)
    at d (vscode-file://vscode-app/nix/store/p4w9h4r2480vmjfcfw5h8nzc61wnkg0s-vscode-1.63.2/lib/vscode/resources/app/out/vs/loader.js:5:10300)
    at Object.errorback (vscode-file://vscode-app/nix/store/p4w9h4r2480vmjfcfw5h8nzc61wnkg0s-vscode-1.63.2/lib/vscode/resources/app/out/vs/loader.js:5:10421)
    at e.triggerErrorback (vscode-file://vscode-app/nix/store/p4w9h4r2480vmjfcfw5h8nzc61wnkg0s-vscode-1.63.2/lib/vscode/resources/app/out/vs/loader.js:3:11059)
    at vscode-file://vscode-app/nix/store/p4w9h4r2480vmjfcfw5h8nzc61wnkg0s-vscode-1.63.2/lib/vscode/resources/app/out/vs/loader.js:3:10765
    at HTMLScriptElement.d (vscode-file://vscode-app/nix/store/p4w9h4r2480vmjfcfw5h8nzc61wnkg0s-vscode-1.63.2/lib/vscode/resources/app/out/vs/loader.js:3:11280)
```

### Steps To Reproduce
Update nixpkgs to latest nixos-21.11, commit `8a053bc2255659c5ca52706b9e12e76a8f50dbdd`. Open a VS Code project (attribute `pkgs.vscode`), try to open some file.

### Expected behavior
No error

### Screenshots
![image](https://user-images.githubusercontent.com/1202014/147827223-e889d310-a2d8-4a16-8fed-c566f7c9dc1f.png)

### Notify maintainers

@eadwu 
@Synthetica9 
@maxeaubrey 
@bobby285271 

### Metadata

Looks like my channels are a bit messed up, but I don't use those anyway. VS Code is definitely the `1.63.2` from the nixos-21.11, as I saw the update changelog. 

```
$ nix run nixpkgs#nix-info -- -m
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:9:

            1| (import <nixpkgs> {}).stdenv.hostPlatform.system
             |         ^
 - system: `0`
 - host os: `Linux 5.10.88, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(falco.peijnenburg): `"nixos-19.03-19.03.172762.89e6170b755"`
 - channels(root): `""`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:1:

            1| <nixpkgs>
             | ^
 - nixpkgs: `0`
 ```

**Comment by FPtje** [comment]
Ah, I've found out that the bug is due to the `files.autoGuessEncoding` setting being set to `true`. Setting it to `false` works around the issue. 

Still, this seems like a packaging bug that started occurring in the latest VS Code update. I've had this option on for a while, and everything worked right before my last nixpkgs pin update.

**Comment by SuperSandro2000** [comment]
I am having the same bug and zero ideas why this is happening.

**Comment by SuperSandro2000** [comment]
Found the issue in a little bit over 4 hours and fixed it in #168882.

**Comment by dandanua** [comment]
@SuperSandro2000 

I believe this bug is not fully fixed. 

When I try to "Select Encoding" by pressing encoding button at the bottom right and then choose "Reopen with Encoding", the same error pops up 
```Cannot find module 'jschardet'
Require stack:
- electron/js2c/renderer_init``` 

I tried it in both vscode and vscodium, version `1.67.2`, nixos-21.11.

**Comment by bobby285271** [comment]
Looks like the change didn't backport to 21.11
