### ISSUE TITLE
Unifi Service doesn't let devices join. 

### ISSUE THREAD

**Issue by AlessandroEmm** [NixOS/nixpkgs#153747]
### Describe the bug
The unifi controller doesn't allow unifi devices to join (adopt).  Devices go into 
![image](https://user-images.githubusercontent.com/1146302/148422769-42bb7d39-cb48-4c57-9adf-3ac90bcb3ed3.png)
eventually.

### Steps To Reproduce
- Setup a new system without backup with a local account. 
- Try to adopt a device

I tried this with a restored setup as well. Same issue.

### Expected behavior
Device joins unifi controller. The same devices join effortlessly on a classic install on an OSX Controller.

### Additional context
I have a very common error on the devices that want join:
ace_reporter.reporter_fail(): Server Reject (http://x.x.x.x:8080/inform)

Per requests from device I get this in the logs of the unifi controller.
```[2022-01-06T18:06:43,367] <inform-3> ERROR [InformServlet] - Servlet.service() for servlet [InformServlet] in context with path [] threw exception [Servlet execution threw an exception] with root cause
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Color
	at com.ubnt.service.config.O0OO.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.config.I.Object(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.config._.voidnew(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.inform.A.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.inform.A.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.OoOO.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.F.new(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.lock.F.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.H.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.inform.A.Ò00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.service.devmgr.inform.A.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.net.InformServlet.o00000(Unknown Source) ~[ace.jar:?]
	at com.ubnt.net.InformServlet.service(Unknown Source) ~[ace.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at com.ubnt.ace.view.UbiosHttpsFilter.doFilter(Unknown Source) ~[ace.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1627) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.56.jar:8.5.56]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
```
A quick google search on this very generic error revealed that its either that libraries are missing or that -Djava.awt.headless=true can (needs?) be set. I tried the latter which didnt help. For the prior i'm way to inexperienced in things NixOs. :-)

### Notify maintainers
@erictapen @globin @patryk27 @pennae 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.89, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```console
these paths will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/gd7ihraqqpginv5cmhgk347nfn2iiqkj-bash-interactive-5.1-p8-dev
copying path '/nix/store/gd7ihraqqpginv5cmhgk347nfn2iiqkj-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.89, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Patryk27** [comment]
1. Could you paste your configuration? 🙂 (not necessarily the entire contents, just the one related to your Unifi setup)
2. Are you using custom firewall rules and/or nftables?

**Comment by AlessandroEmm** [comment]
Sorry, my config is so generic that i didnt think about it:

```   nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
      "unifi-controller"
    ];

  systemd.services.unifi.serviceConfig.ExecStart = lib.mkForce  [
    ""
    "${config.services.unifi.jrePackage}/bin/java -Djava.awt.headless=true  -jar /var/lib/unifi/lib/ace.jar start"
  ];

services.unifi = {
    enable = true;
    unifiPackage = pkgs.unifiStable;
    openPorts = true;
    jrePackage = pkgs.jre8_headless;
  };

```

2. Firewalls are deactivated, and connectivity from the devices SSH Terminal seems to work. It's very apparent because for every error on the client i get the stacktrace on the server.

**Comment by Patryk27** [comment]
Hmm, is there a reason why you switched from the default `jrePackage` (of `pkgs.jre8`) to `pkgs.jre8_headless`?

**Comment by AlessandroEmm** [comment]
Good point, I copied it from https://github.com/NixOS/nixpkgs/issues/75133 and I used headless for my old instance on debian.

But hey that was it! I'm sorry I should've kept and tried with the default.

**Comment by Patryk27** [comment]
No worries 😄 So unless you've got some further questions / reports, would you mind closing this issue? 🙂
