### ISSUE TITLE
clojure-lsp fails to build on darwin

### ISSUE THREAD

**Issue by willcohen** [NixOS/nixpkgs#153765]
### Describe the bug

`/tmp` is not writable on darwin, which seems like it's preventing this from build from working since the move to `buildGraalvmNativeImage`.

### Steps To Reproduce
1. Bump the clojure-lsp version
2. nix-env -f $NIXPKGS -iA clojure-lsp

Output:
```
...
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:527)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
Caused by: java.lang.IllegalStateException: Failed to extract lmdb/libraries/liblmdb/lmdb.h in /tmp
        at datalevin.ni.Lib$Directives.extract(Lib.java:157)
        at datalevin.ni.Lib$Directives.<clinit>(Lib.java:127)
        ... 16 more
[clojure-lsp:85266]      [total]:   5,628.35 ms,  1.19 GB
```

### Additional context

If `extraNativeImageBuildArgs` is changed to `"-H:CLibraryPath=$TMPDIR"`, it still fails:

```
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
Caused by: java.lang.IllegalStateException: Failed to create directory /nix/store/isr2gbnqc5rdmvng34p8h5dv512yzk92-graalvm11-ce-lib/lib/lmdb/libraries/liblmdb
        at datalevin.ni.Lib$Directives.<clinit>(Lib.java:123)
        ... 16 more
[clojure-lsp:85488]      [total]:   4,384.00 ms,  0.95 GB
```

### Notify maintainers
@ericdallo @babariviere @thiagokokada 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.2.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(wcohen): `"darwin, home-manager"`
 - channels(root): `"nixpkgs-21.11pre333180.98747f27ecf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by thiagokokada** [comment]
Closed by: https://github.com/NixOS/nixpkgs/pull/153775
