### ISSUE TITLE
notmuch fails to build on master

### ISSUE THREAD

**Issue by otavio** [NixOS/nixpkgs#154297]
### Describe the bug
The build is failing on master; it has been reproduced at c9248a6d87ce071fc7538dc5358b60ce86092e49.

An example of the failure is below:
```console
T670-duplicate-mid: Testing duplicate message ids
 PASS   at most 1 thread-id per xapian document
 PASS   search: first indexed subject preserved
 BROKEN First subject preserved in notmuch-show (json)
        --- T670-duplicate-mid.3.expected       2022-01-10 15:49:39.334299463 +0000
        +++ T670-duplicate-mid.3.output 2022-01-10 15:49:39.334299463 +0000
        @@ -2,6 +2,7 @@
             [
                 [
                     {
        +                "crypto": {},
                         "date_relative": "2001-01-05",
                         "excluded": false,
                         "filename": [
        @@ -12,7 +13,7 @@
                         "headers": {
                             "Date": "GENERATED_DATE",
                             "From": "Notmuch Test Suite <test_suite@notmuchmail.org>",
        -                    "Subject": "message 1",
        +                    "Subject": "message 0",
                             "To": "Notmuch Test Suite <test_suite@notmuchmail.org>"
                         },
                         "id": "XXXXX",
 PASS   Search for second subject
 BROKEN Regexp search for second subject
        --- T670-duplicate-mid.5.EXPECTED       2022-01-10 15:49:39.352299871 +0000
        +++ T670-duplicate-mid.5.OUTPUT 2022-01-10 15:49:39.352299871 +0000
        @@ -1,3 +0,0 @@
        -MAIL_DIR/copy0
        -MAIL_DIR/copy1
        -MAIL_DIR/copy2
 PASS   search for body in duplicate file
 PASS   reindex drops terms in duplicate file
 PASS   reindex choses subject from first filename
 PASS   Deleted first duplicate file does not stop notmuch show from working
...

Notmuch test suite complete.
1537/1559 tests passed.
6 broken tests failed as expected.
16 tests failed.
All tests in 2 files skipped.
ERROR: some tests failed; first failed returned error code 1
make: *** [test/Makefile.local:75: test] Error 1
```

There is a new release (`0.34.3`) which also doesn't pass, so I didn't send the PR as it'd fail on CI.

### Steps To Reproduce
1. `nix-build -A notmuch`

### Notify maintainers

@flokli
@puckipedia

**Comment by tadfisher** [comment]
Those aren't the failing tests (BROKEN means they are known to fail). These are the real failures:

```
T355-smime: Testing S/MIME signature verification and decryption
 FAIL   emacs delivery of S/MIME signed message
        emacs_fcc_message \
             "test signed message 001" \
             "This is a test signed message." \
             "(mml-secure-message-sign \"smime\")"
*ERROR*: GPG error: "Sign failed", "Unusable secret key: 0DFB64A6E0972A47; Unusable public key: 0DFB64A6E0972A47"
 FAIL   emacs delivery of S/MIME encrypted + signed message
        emacs_fcc_message \
            "test encrypted message 001" \
            "<#secure method=smime mode=signencrypt>\nThis is a test encrypted message.\n"
*ERROR*: GPG error: "Sign failed", "Unusable secret key: 0DFB64A6E0972A47; Unusable public key: 0DFB64A6E0972A47"
 FAIL   Signature verification (openssl)
        --- T355-smime.3.EXPECTED       2022-01-10 20:47:04.570845875 +0000
        +++ T355-smime.3.OUTPUT 2022-01-10 20:47:04.572845879 +0000
        @@ -1 +1,2 @@
        -Verification successful
        +Error reading S/MIME message
        +140737348175680:error:0D0D40D1:asn1 encoding routines:SMIME_read_ASN1:no content type:crypto/asn1/asn_mime.c:399:
Error: Cannot open database at /build/notmuch-0.34.2/test/tmp.T355-smime/mail/.notmuch: No such file or directory.
 FAIL   signature verification (notmuch CLI)
        --- T355-smime.4.expected       2022-01-10 20:47:04.897846462 +0000
        +++ T355-smime.4.output 2022-01-10 20:47:04.897846462 +0000
        @@ -1,72 +1 @@
        -[
        -    [
        -        [
        -            {
        -                "body": [
        -                    {
        -                        "content": [
        -                            {
        -                                "content": "This is a test signed message.\n",
        -                                "content-type": "text/plain",
        -                                "id": 2
        -                            },
        -                            {
        -                                "content-disposition": "attachment",
        -                                "content-length": "NONZERO",
        -                                "content-transfer-encoding": "base64",
        -                                "content-type": "application/pkcs7-signature",
        -                                "filename": "smime.p7s",
        -                                "id": 3
        -                            }
        -                        ],
        -                        "content-type": "multipart/signed",
        -                        "id": 1,
        -                        "sigstatus": [
        -                            {
        -                                "created": 946728000,
        -                                "email": "<test_suite@notmuchmail.org>",
        -                                "expires": 424242424,
        -                                "fingerprint": "616F46CD73834C63847756AF0DFB64A6E0972A47",
        -                                "status": "good",
        -                                "userid": "CN=Notmuch Test Suite"
        -                            }
        -                        ]
        -                    }
        -                ],
        -                "crypto": {
        -                    "signed": {
        -                        "status": [
        -                            {
        -                                "created": 946728000,
        -                                "email": "<test_suite@notmuchmail.org>",
        -                                "expires": 424242424,
        -                                "fingerprint": "616F46CD73834C63847756AF0DFB64A6E0972A47",
        -                                "status": "good",
        -                                "userid": "CN=Notmuch Test Suite"
        -                            }
        -                        ]
        -                    }
        -                },
        -                "date_relative": "2000-01-01",
        -                "excluded": false,
        -                "filename": [
        -                    "YYYYY"
        -                ],
        -                "headers": {
        -                    "Date": "Sat, 01 Jan 2000 12:00:00 +0000",
        -                    "From": "Notmuch Test Suite <test_suite@notmuchmail.org>",
        -                    "Subject": "test signed message 001",
        -                    "To": "test_suite@notmuchmail.org"
        -                },
        -                "id": "XXXXX",
        -                "match": true,
        -                "tags": [
        -                    "inbox",
        -                    "signed"
        -                ],
        -                "timestamp": 946728000
        -            },
        -            []
        -        ]
        -    ]
        -]
        +
Error: Cannot open database at /build/notmuch-0.34.2/test/tmp.T355-smime/mail/.notmuch: No such file or directory.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
 FAIL   Decryption and signature verification (openssl)
        --- T355-smime.5.EXPECTED       2022-01-10 20:47:04.936846532 +0000
        +++ T355-smime.5.OUTPUT 2022-01-10 20:47:04.938846535 +0000
        @@ -1 +1,2 @@
        -Verification successful
        +Error reading S/MIME message
        +140737348175680:error:0D0D40D1:asn1 encoding routines:SMIME_read_ASN1:no content type:crypto/asn1/asn_mime.c:399:
Error: Cannot open database at /build/notmuch-0.34.2/test/tmp.T355-smime/mail/.notmuch: No such file or directory.
Error reading S/MIME message
140737348175680:error:0D0D40D1:asn1 encoding routines:SMIME_read_ASN1:no content type:crypto/asn1/asn_mime.c:399:
 FAIL   Decryption (notmuch CLI)
        --- T355-smime.6.EXPECTED       2022-01-10 20:47:04.975846602 +0000
        +++ T355-smime.6.OUTPUT 2022-01-10 20:47:04.976846604 +0000
        @@ -1 +0,0 @@
        -This is a test encrypted message.
Error: Cannot open database at /build/notmuch-0.34.2/test/tmp.T355-smime/mail/.notmuch: No such file or directory.
Traceback (most recent call last):
  File "/build/notmuch-0.34.2/test/json_check_nodes.py", line 55, in <module>
    data = json.load(sys.stdin)
  File "/nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
 FAIL   Cryptographic message status (encrypted+signed)
        
Error: Cannot open database at /build/notmuch-0.34.2/test/tmp.T355-smime/mail/.notmuch: No such file or directory.
 FAIL   encrypted+signed message is known to be encrypted, but signature is unknown
        --- T355-smime.8.expected       2022-01-10 20:47:05.123846868 +0000
        +++ T355-smime.8.output 2022-01-10 20:47:05.123846868 +0000
        @@ -1 +1 @@
        -thread:0000000000000002   2000-01-01 [1/1] Notmuch Test Suite; test encrypted message 001 (encrypted inbox)
        +
Error: Cannot open database at /build/notmuch-0.34.2/test/tmp.T355-smime/mail/.notmuch: No such file or directory.
 PASS   Encrypted body is not indexed
 FAIL   Reindex cleartext
        notmuch reindex --decrypt=true subject:'test encrypted message 001'
Error: Cannot open database at /build/notmuch-0.34.2/test/tmp.T355-smime/mail/.notmuch: No such file or directory.
 FAIL   signature is now known
        --- T355-smime.11.expected      2022-01-10 20:47:05.177846965 +0000
        +++ T355-smime.11.output        2022-01-10 20:47:05.177846965 +0000
        @@ -1 +1 @@
        -thread:0000000000000002   2000-01-01 [1/1] Notmuch Test Suite; test encrypted message 001 (encrypted inbox signed)
        +
Error: Cannot open database at /build/notmuch-0.34.2/test/tmp.T355-smime/mail/.notmuch: No such file or directory.
 FAIL   Encrypted body is indexed
        --- T355-smime.12.expected      2022-01-10 20:47:05.201847008 +0000
        +++ T355-smime.12.output        2022-01-10 20:47:05.201847008 +0000
        @@ -1 +1 @@
        -thread:0000000000000002   2000-01-01 [1/1] Notmuch Test Suite; test encrypted message 001 (encrypted inbox signed)
        +
Error: Cannot open database at /build/notmuch-0.34.2/test/tmp.T355-smime/mail/.notmuch: No such file or directory.
 FAIL   verify signed PKCS#7 subject (multipart-signed) signer User ID
        sig_uid: object not found: data[0][0][0]["crypto"]["signed"]["status"][0]["userid"]
 FAIL   verify signed PKCS#7 subject (onepart-signed) signer User ID
        sig_uid: object not found: data[0][0][0]["crypto"]["signed"]["status"][0]["userid"]
 FAIL   confirm signed and encrypted PKCS#7 subject (sign+enc) signer User ID
        sig_uid: object not found: data[0][0][0]["crypto"]["signed"]["status"][0]["userid"]
 FAIL   confirm signed and encrypted PKCS#7 subject (sign+enc+legacy-disp) signer User ID
        sig_uid: object not found: data[0][0][0]["crypto"]["signed"]["status"][0]["userid"]
```

Looks like a broken GPG setup in the build environment.

**Comment by hughobrien** [comment]
fixed in the next point release I think https://github.com/notmuch/notmuch/blob/63d3b2b5cf8702b5fecea77392ce46f8a8249175/NEWS#L7

**Comment by hughobrien** [comment]
prior work https://github.com/NixOS/nixpkgs/pull/154309/files
