### ISSUE TITLE
inkcut: crashes on startup

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#154266]
### Describe the bug

Noticed when I wanted to test #153982: on startup, inkcut crashes with:

```
Logging to /home/aengelen/.config/inkcut/logs/inkcut.txt
2022-01-10 10:08:13,426 | INFO    | inkcut | ========================================
2022-01-10 10:08:13,427 | INFO    | inkcut | Inkcut launched
2022-01-10 10:08:13,427 | INFO    | inkcut | Version: 2.1.3
2022-01-10 10:08:13,427 | INFO    | inkcut | Python: 3.9.9 (main, Nov 15 2021, 18:05:17) 
[GCC 10.3.0]
2022-01-10 10:08:13,427 | INFO    | inkcut | System: uname_result(system='Linux', node='rigter', release='5.15.12', version='#1-NixOS SMP Wed Dec 29 11:29:03 UTC 2021', machine='x86_64')
2022-01-10 10:08:13,427 | INFO    | inkcut | Executable: /nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/bin/python3.9
2022-01-10 10:08:13,427 | INFO    | inkcut | Args: ['/nix/store/zq28r7sjlbmw6rp9phkis0dz53313lwz-inkcut-2.1.3/bin/inkcut']
2022-01-10 10:08:13,444 | INFO    | inkcut | Qt: 5.15.3 Api:
2022-01-10 10:08:13,444 | INFO    | inkcut | ========================================
2022-01-10 10:08:13,474 | ERROR   | inkcut | Traceback (most recent call last):
  File "/nix/store/zq28r7sjlbmw6rp9phkis0dz53313lwz-inkcut-2.1.3/lib/python3.9/site-packages/inkcut/app.py", line 97, in main
    from inkcut.core.workbench import InkcutWorkbench
  File "/nix/store/zq28r7sjlbmw6rp9phkis0dz53313lwz-inkcut-2.1.3/lib/python3.9/site-packages/inkcut/core/workbench.py", line 22, in <module>
    from enaml.workbench.ui.api import UIWorkbench
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/workbench/ui/api.py", line 14, in <module>
    from .workspace import Workspace
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/workbench/ui/workspace.py", line 11, in <module>
    from enaml.widgets.container import Container
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/widgets/container.py", line 13, in <module>
    from enaml.layout.layout_helpers import vbox
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/layout/layout_helpers.py", line 8, in <module>
    from .constraint_helper import ConstraintHelper
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/layout/constraint_helper.py", line 13, in <module>
    class ConstraintHelper(Atom):
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/layout/constraint_helper.py", line 18, in ConstraintHelper
    strength = StrengthMember()
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/layout/strength_member.py", line 21, in __init__
    super(StrengthMember, self).__init__(default, factory)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

Traceback (most recent call last):
  File "/nix/store/zq28r7sjlbmw6rp9phkis0dz53313lwz-inkcut-2.1.3/bin/.inkcut-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/zq28r7sjlbmw6rp9phkis0dz53313lwz-inkcut-2.1.3/lib/python3.9/site-packages/inkcut/app.py", line 97, in main
    from inkcut.core.workbench import InkcutWorkbench
  File "/nix/store/zq28r7sjlbmw6rp9phkis0dz53313lwz-inkcut-2.1.3/lib/python3.9/site-packages/inkcut/core/workbench.py", line 22, in <module>
    from enaml.workbench.ui.api import UIWorkbench
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/workbench/ui/api.py", line 14, in <module>
    from .workspace import Workspace
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/workbench/ui/workspace.py", line 11, in <module>
    from enaml.widgets.container import Container
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/widgets/container.py", line 13, in <module>
    from enaml.layout.layout_helpers import vbox
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/layout/layout_helpers.py", line 8, in <module>
    from .constraint_helper import ConstraintHelper
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/layout/constraint_helper.py", line 13, in <module>
    class ConstraintHelper(Atom):
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/layout/constraint_helper.py", line 18, in ConstraintHelper
    strength = StrengthMember()
  File "/nix/store/1zcf7avsqc9j5g3jlimdraha5lvm57k6-python3.9-enaml-0.13.0/lib/python3.9/site-packages/enaml/layout/strength_member.py", line 21, in __init__
    super(StrengthMember, self).__init__(default, factory)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given
```

### Steps To Reproduce
1. start inkcut

### Additional context

I see there's also a new upstream version of enaml available, possibly related.

**Comment by raboof** [comment]
This was due to a mismatch between enaml and atom: enaml 0.13 calls the Value init method in atom 0.6.0 with 3 parameters (counting `self`). However, the parameters changed in atom 0.7.0, so this likely broke with 8f48296bd47c664a161edb3aeb56167def61342a (verified it indeed broke somewhere between 2a295f42c84df1a413295e580945d7c334c9b6b0 and 9fcf9be974fd979631f60a6d603ae77f4c220679).

In enaml 0.14 the invocation is fixed to match what atom 0.7.0 expects, so I PR'ed  #154930
