### ISSUE TITLE
python3{8,10}Packages.eventlet broken

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#154879]
See https://hydra.nixos.org/build/164042853/nixlog/1:

```
Traceback (most recent call last):
  File "/build/eventlet-0.33.0/eventlet/hubs/hub.py", line 476, in fire_timers
    timer()
  File "/build/eventlet-0.33.0/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/build/eventlet-0.33.0/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/build/eventlet-0.33.0/tests/queue_test.py", line 269, in fetch_item
    got.append(queue.get())
  File "/build/eventlet-0.33.0/eventlet/queue.py", line 322, in get
    return waiter.wait()
  File "/build/eventlet-0.33.0/eventlet/queue.py", line 141, in wait
    return get_hub().switch()
  File "/build/eventlet-0.33.0/eventlet/hubs/hub.py", line 313, in switch
    return self.greenlet.switch()
Exception: kaboom
..............................................................................................................................................................................127.0.0.1 - - [07/Jan/2022 16:59:44] code 400, message Bad request syntax ('X')
127.0.0.1 - - [07/Jan/2022 16:59:44] "X" 400 -
Traceback (most recent call last):
  File "/build/eventlet-0.33.0/tests/wsgi_test.py", line 566, in server
    serv.process_request([addr, client_socket, wsgi.STATE_IDLE])
  File "/build/eventlet-0.33.0/eventlet/wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "/build/eventlet-0.33.0/eventlet/wsgi.py", line 352, in __init__
    self.finish()
  File "/build/eventlet-0.33.0/eventlet/wsgi.py", line 751, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "/nix/store/b798fp24zf2fdafmyyc4sxfr48ly5yy9-python3-3.10.1/lib/python3.10/socketserver.py", line 811, in finish
    self.wfile.close()
  File "/nix/store/b798fp24zf2fdafmyyc4sxfr48ly5yy9-python3-3.10.1/lib/python3.10/socket.py", line 723, in write
    return self._sock.send(b)
  File "/build/eventlet-0.33.0/eventlet/green/ssl.py", line 194, in send
    return self._call_trampolining(
  File "/build/eventlet-0.33.0/eventlet/green/ssl.py", line 162, in _call_trampolining
    return func(*a, **kw)
  File "/nix/store/b798fp24zf2fdafmyyc4sxfr48ly5yy9-python3-3.10.1/lib/python3.10/ssl.py", line 1205, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2384)
F......................................S............SSSSSSSSSSSSSSSSSSSSSSSS
======================================================================
FAIL: tests.patcher_test.test_patcher_existing_locks_locked
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/nyljsjchchlgvb1vbjvb68wsk2q8mpkk-python3.10-nose-1.3.7/lib/python3.10/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/eventlet-0.33.0/tests/patcher_test.py", line 480, in test_patcher_existing_locks_locked
    tests.run_isolated('patcher_existing_locks_locked.py')
  File "/build/eventlet-0.33.0/tests/__init__.py", line 381, in run_isolated
    run_python(prefix + path, **kwargs)
  File "/build/eventlet-0.33.0/tests/__init__.py", line 374, in run_python
    assert ok, 'Expected single line "pass" in stdout'
AssertionError: Expected single line "pass" in stdout

======================================================================
FAIL: test_017_ssl_zeroreturnerror (tests.wsgi_test.TestHttpd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/eventlet-0.33.0/tests/wsgi_test.py", line 592, in test_017_ssl_zeroreturnerror
    assert success
AssertionError

----------------------------------------------------------------------
Ran 700 tests in 48.074s
```

A similar failure occurs for python38 on my machine locally (reproduce with `nix-build -A python38Packages.eventlet` in a freshly checked out `nixpkgs`).

### Notify maintainers

@SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"home-manager, musnix, nixos-22.05pre335501.c71f061c68b, nixos-hardware"`
 - channels(turion): `"home-manager, nixpkgs-21.11pre329221.c11d08f0239"`
 - nixpkgs: `/home/turion/.nix-defexpr/channels/nixpkgs`
```

**Comment by turion** [comment]
Strange, I can't reproduce the error with 3.8 anymore :thinking: it seems that although the tests failed, and this was visible during `nix-build`, the derivation did successfully build.

**Comment by turion** [comment]
So is the test simply flaky, and sometimes succeeds on Hydra? Or if not, shouldn't we exclude the test if it can't be set up properly?
