### ISSUE TITLE
pythonPackages.SPARQLWrapper is holding back tests.gnome3.x86_64-linux and unstable releases

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#15499]
`nix-build '<nixos/release.nix>' -A tests.gnome3.x86_64-linux` fails, because `nix-build '<nixpkgs>' -A pythonPackages.SPARQLWrapper` fails, because of 5d68baa8dbcf8f9970ea0174949cb1dd67c87ae4 and this is holding back `nixos-unstable` from releasing:

![image](https://cloud.githubusercontent.com/assets/3359345/15293722/402e36ea-1b81-11e6-82d7-290ab55c3057.png)

Error:
```
$ nix-build '<nixpkgs>' -A pythonPackages.SPARQLWrapper
these derivations will be built:
  /nix/store/8yf98s720cibkpsq5lvw1acq451cx6ks-python2.7-SPARQLWrapper-1.7.4.drv
building path(s) ‘/nix/store/a8w1wg406yw45n5hkk19hpycdg54jllx-python2.7-SPARQLWrapper-1.7.4’
unpacking sources
unpacking source archive /nix/store/r7addvb5a6ns2600d41jv9wq2zcs1036-SPARQLWrapper-1.7.4.tar.gz
source root is SPARQLWrapper-1.7.4
setting SOURCE_DATE_EPOCH to timestamp 1446731807 of file SPARQLWrapper-1.7.4/setup.cfg
patching sources
configuring
building
Traceback (most recent call last):
  File "nix_run_setup.py", line 6, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 46, in <module>
    _requires = [str(r.req.project_name) for r in requirements]
AttributeError: 'Requirement' object has no attribute 'project_name'
builder for ‘/nix/store/8yf98s720cibkpsq5lvw1acq451cx6ks-python2.7-SPARQLWrapper-1.7.4.drv’ failed with exit code 1
error: build of ‘/nix/store/8yf98s720cibkpsq5lvw1acq451cx6ks-python2.7-SPARQLWrapper-1.7.4.drv’ failed
```

Reverting fixes everything:

```diff
--- a/pkgs/development/python-modules/bootstrapped-pip/default.nix
+++ b/pkgs/development/python-modules/bootstrapped-pip/default.nix
@@ -15,11 +15,11 @@ let
   };
 in stdenv.mkDerivation rec {
   name = "python-${python.version}-bootstrapped-pip-${version}";
-  version = "8.1.2";
+  version = "8.1.1";
 
   src = fetchurl {
-    url = "https://pypi.python.org/packages/9c/32/004ce0852e0a127f07f358b715015763273799bd798956fa930814b60f39/pip-${version}-py2.py3-none-any.whl";
-    sha256 = "18cjrd66mn4a0gwa99zzs89lrb0xn4xmajdzya6zqd7v16cdsr34";
+    url = "https://pypi.python.org/packages/py2.py3/p/pip/pip-${version}-py2.py3-none-any.whl";
+    sha256 = "0p62v87lm595kwmxrnqxc81dr7h6maaxj1y28b00bf9ag11c7fa4";
   };
 
   unpackPhase = ''
```

cc // @FRidh @pikajude @domenkozar @lethalman

**Comment by joachifm** [comment]
What about https://github.com/NixOS/nixpkgs/commit/aed4881ca54b72d2a46017e9b96f77f4813c3c2f

**Comment by FRidh** [comment]
Indeed, that seems to be a better solution.

**Comment by obadz** [comment]
Yes, hadn't seen it.
