### ISSUE TITLE
cannot get backtrace from rustfmt (and presumably other rust programs)

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nixpkgs#15524]
## Issue description

When using rustfmt from nix, if RUST_BACKTRACE is set, rustfmt fails to give me a backtrace when it panics in library code, because it has a hard-coded reference to the build-dir:

```
$ RUST_BACKTRACE=1 rustfmt --write-mode display lib.rs
thread '<main>' panicked at 'explicit panic', /tmp/nix-build-rustfmt-0.4.drv-0/deps/registry/src/-2304f9dd481834b8/syntex_syntax-0.30.0/src/errors/mod.rs:360
stack backtrace:
   1:     0x5650c1107be0 - sys::backtrace::tracing::imp::write::h09d7a562cdce3ef9Xcv
Illegal instruction (core dumped)
```

### Steps to reproduce

```
$ nix-shell -p rustfmt
$ echo titi > toto
$ RUST_BACKTRACE=1 rustfmt --write-mode display toto
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "expected item, found `titi`"', src/libcore/result.rs:746
stack backtrace:
   1:     0x55b48abbfbe0 - sys::backtrace::tracing::imp::write::h09d7a562cdce3ef9Xcv
Illegal instruction (core dumped)
```

I expect rustfmt to output a nice error rather than panicing (that's rustfmt's bugs), but, failing that, I expect to be able to get a backtrace of that panic (it seems I'm unable to get that because of nixpkgs).

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 16.09pre79453.32b7b00 (Flounder)

* Nix version: (run `nix-env --version`) nix-env (Nix) 1.11.2
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 16.09pre-git

**Comment by the-kenny** [comment]
Are you sure this is caused by the reference to `/tmp/...` and not by the (stripped) release build?

**Comment by FlorentBecker** [comment]
The /tmp/… reference was only a guess, I'll check.

**Comment by the-kenny** [comment]
Any updates on this?

**Comment by FlorentBecker** [comment]
Sorry, haven't checked since then.
