### ISSUE TITLE
Seafile-Server / Seahub crashes after login

### ISSUE THREAD

**Issue by TuxCoder** [NixOS/nixpkgs#156202]
### Describe the bug
I tryed to install the seafile server on a nixos machine, the build / deploy process was fine and looked good.
But after login with the set credentials, it returend a 500 error.

After to long debuging I found out that seahub still uses a old version of django-webpack-loader[1].
it changes the format of the metadata file and gives now a strange exception in the processing.

the current installed version in nixospkg 21.11 is `1.4.0` required for seahub[2] is `0.7`.

Is it possible to have two version of an python pkg in nix? I saw that the old version is in nixpkgs 21.01 but there is no seafile/seahub pakge.

The parssing issue is from this file: `/nix/store/y1yln91z2gbybmg1nn0b4sz4mbana04l-python3.9-seahub-8.0.7/frontend/webpack-stats.pro.json`

[1] https://github.com/django-webpack/django-webpack-loader
[2] https://github.com/haiwen/seahub/blob/master/requirements.txt#L5

### Steps To Reproduce
1. `services.seafile-server.enable = true;`
2. go to login page

### Expected behavior
No 500 error.

### Screenshots
Stacktrace:

### Additional context

I saw that there is a refactor going on for seafile: https://github.com/NixOS/nixpkgs/pull/153388
Not quite sure if I made a misstake but I don't see it :/.

### Notify maintainers
@schmittlauch
@greizgh

Also thanks to the maintainers, I tried also to crate a package from scratch before this was released,
the seafile code is not good maintained and hard to get running.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
Build machine:
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.0-rc8, Debian GNU/Linux, 11 (bullseye)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(tuxcoder): `"nixpkgs-21.11pre335454.fd2624ba104, nixpkgs_21_05-21.05pre296205.0fd9ee1aa36"`
 - nixpkgs: `/home/tuxcoder/.nix-defexpr/channels/nixpkgs`
```
executed machine:
```
 nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.93, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`

 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```console
Jan 22 20:51:33 seafile .gunicorn-wrapp[636]: 2022-01-22 19:51:33,914 [ERROR] django.request:222 log_response Internal Server Error: /
                                              Traceback (most recent call last):
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
                                                  response = get_response(request)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
                                                  response = self.process_exception_by_middleware(e, request)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
                                                  response = wrapped_callback(request, *callback_args, **callback_kwargs)
                                                File "/nix/store/y1yln91z2gbybmg1nn0b4sz4mbana04l-python3.9-seahub-8.0.7/seahub/auth/decorators.py", line 27, in _wrapped_view
                                                  return view_func(request, *args, **kwargs)
                                                File "/nix/store/y1yln91z2gbybmg1nn0b4sz4mbana04l-python3.9-seahub-8.0.7/seahub/views/__init__.py", line 1173, in react_fake_view
                                                  return render(request, "react_app.html", {
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/shortcuts.py", line 36, in render
                                                  content = loader.render_to_string(template_name, context, request, using=using)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
                                                  return template.render(context, request)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
                                                  return self.template.render(context)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/template/base.py", line 171, in render
                                                  return self._render(context)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/template/base.py", line 163, in _render
                                                  return self.nodelist.render(context)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/template/base.py", line 937, in render
                                                  bit = node.render_annotated(context)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/template/base.py", line 904, in render_annotated
                                                  return self.render(context)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
                                                  return compiled_parent._render(context)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/template/base.py", line 163, in _render
                                                  return self.nodelist.render(context)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/template/base.py", line 937, in render
                                                  bit = node.render_annotated(context)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/template/base.py", line 904, in render_annotated
                                                  return self.render(context)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/django/template/library.py", line 192, in render
                                                  output = self.func(*resolved_args, **resolved_kwargs)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/webpack_loader/templatetags/webpack_loader.py", line 20, in render_bundle
                                                  tags = utils.get_as_tags(
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/webpack_loader/utils.py", line 61, in get_as_tags
                                                  bundle = _get_bundle(bundle_name, extension, config)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/webpack_loader/utils.py", line 39, in _get_bundle
                                                  bundle = get_loader(config).get_bundle(bundle_name)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/webpack_loader/loader.py", line 97, in get_bundle
                                                  filtered_chunks = self.filter_chunks(chunks)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/webpack_loader/loader.py", line 45, in filter_chunks
                                                  ignore = any(regex.match(chunk)
                                                File "/nix/store/mnj5gbjzd2s4kj3llb10jx0iq5hmkgyx-python3-3.9.6-env/lib/python3.9/site-packages/webpack_loader/loader.py", line 45, in <genexpr>
                                                  ignore = any(regex.match(chunk)
                                              TypeError: expected string or bytes-like object
```

Variable content in `ignore = any(regex.match(chunk)`:

.0 | <list_iterator object at 0x7f13e752e580>
-- | --
chunk | {'name': 'static/css/commons.chunk.css',  'path': '/var/lib/seafile/seahub/media/assets/frontend/static/css/commons.chunk.css'}
regex | re.compile('.+\\.hot-update.js')

Config:
```nix
{
    services.nginx = {
      enable = true;
    };
    services.nginx.upstreams."gunicorn_seafile" = {
      servers."unix:/run/seahub/gunicorn.sock" = {};
    };
    services.nginx.upstreams."seafhttp" = {
      servers."127.0.0.1:8082" = {};
    };
    services.nginx.virtualHosts."${fqdn}" = {
      addSSL = true;
      enableACME = true;
      serverName = fqdn;
     locations."/" = {
       proxyPass = "http://gunicorn_seafile"; # without a trailing /
       extraConfig = ''
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Host $server_name;
          #proxy_set_header Host $host;
          proxy_read_timeout  1200s;

          client_max_body_size 0; # disable max upload size
       '';
     };
     locations."/seafhttp" = {
       proxyPass = "http://seafhttp"; # without a trailing /
       extraConfig = ''
         rewrite ^/seafhttp(.*)$ $1 break;
         client_max_body_size 0;

         proxy_connect_timeout  36000s;
         proxy_read_timeout  36000s;
         proxy_send_timeout  36000s;

         proxy_request_buffering off;
         send_timeout  36000s;
       '';
     };
    };


    services.seafile = {
      enable = true;
      adminEmail = "root@" + domain;
      initialAdminPassword = "ThisIsNotSafeOt9eij";
      ccnetSettings = {
        General = {
          Name = domain;
          SERVICE_URL = "https://${fqdn}";
        };
#       Database = {
#         ENGINE = "postgres";
#         HOST = "db.${domain}";
#         #PORT = ;
#         USER = "seafile-ccnet";
#         #PASSWD = 
#         DB = "seafile-ccnet";
#         CONNECTION_CHARSET = "utf8";
#       };
      };
      seafileSettings = {
        history.keep_days = 365; # days of history to keep
        fileserver = {
          host = "127.0.0.1";
          port = 8082;
        };
        general.enable_syslog = true;
#       database = {
#         type = "mysql";
#         host = "127.0.0.1";
#         user = "root";
#         password = "root";
#         db_name = "seafile_db";
#         connection_charset = "utf8";
#         max_connections = 100;
#       };
      };
      seahubExtraConf = ''
        DEBUG = True
        STATIC_ROOT = '/var/lib/seafile/seahub/media/assets/'
        ALLOWED_HOSTS = [ '${fqdn}' ]
        CSRF_COOKIE_SECURE = True
        CSRF_COOKIE_SAMESITE = 'Strict'
        LOGGING = {
            'version': 1,
            'disable_existing_loggers': True,
            'formatters': {
                'verbose': {
                    'format': '%(process)-5d %(thread)d %(name)-50s %(levelname)-8s %(message)s'
                },
                'standard': {
                    'format': '%(asctime)s [%(levelname)s] %(name)s:%(lineno)s %(funcName)s %(message)s'
                },
                'simple': {
                    'format': '[%(asctime)s] %(name)s %(levelname)s %(message)s',
                    'datefmt': '%d/%b/%Y %H:%M:%S'
                },
            },
            'filters': {
                'require_debug_false': {
                    '()': 'django.utils.log.RequireDebugFalse',
                },
                'require_debug_true': {
                    '()': 'django.utils.log.RequireDebugTrue',
                },
            },
            'handlers': {
                'console': {
                    'filters': ['require_debug_true'],
                    'class': 'logging.StreamHandler',
                    'formatter': 'simple'
                },
                'syslog': {
                    'class': 'logging.handlers.SysLogHandler',
                    'address': '/dev/log',
                    'formatter': 'standard'
                },
            },
            'loggers': {
                # root logger
                # All logs printed by Seahub and any third party libraries will be handled by this logger.
                "": {
                    'handlers': ['syslog'],
                    'level': 'INFO', # Logs when log level is higher than info. Level can be any one of DEBUG, INFO, WARNING, ERROR, CRITICAL.
                    'disabled': False
                },
                # This logger recorded logs printed by Django Framework. For example, when you see 5xx page error, you should check the logs recorded by this logger.
                'django.request': {
                    'handlers': ['syslog'],
                    'level': 'INFO',
                    'propagate': False,
                },
            },
        }

        #ENABLE_OAUTH = True
        OAUTH_ENABLE_INSECURE_TRANSPORT = False
        OAUTH_CLIENT_ID = "seafile"
        AUTH_CLIENT_SECRET = "xxx"
        AUTH_REDIRECT_URL = 'https://${fqdn}/oauth/callback/'
        OAUTH_PROVIDER_DOMAIN = '${domain}'
        OAUTH_AUTHORIZATION_URL = 'https://oauth2.${domain}/oauth2/auth'
        OAUTH_TOKEN_URL = 'https://${domain}.o-g.at/oauth2/token'
        OAUTH_USER_INFO_URL = 'https://oauth2.${domain}/userinfo'
        OAUTH_SCOPE = ["openid", "profile", "email"]
        OAUTH_ATTRIBUTE_MAP = {
          "id": (False, "email"), # stupdi default overwrite 
          "preferred_username": (True, "name"),
          "email": (True, "email"),
        }
      '';
    };
}
```

**Comment by TuxCoder** [comment]
ok is duplicated, ... https://github.com/NixOS/nixpkgs/pull/148477
good that I wrote this :)

I will wait until the new version is ready
