### ISSUE TITLE
leo-editor fails to launch

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#15713]
Tested in both 16.03 and unstable.

```
> leo
setting leoID from os.getenv('USER'): 'chris'
Traceback (most recent call last):
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/bin/.leo-wrapped", line 12, in <module>
    sys.exit(run())
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/core/runLeo.py", line 78, in run
    g.app.loadManager.load(fileName,pymacs)
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/core/leoApp.py", line 2639, in load
    ok = lm.doPostPluginsInit()
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/core/leoApp.py", line 3009, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/core/leoApp.py", line 3067, in openEmptyWorkBook
    c = lm.loadLocalFile(fn,gui=g.app.gui,old_c=None)
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/core/leoApp.py", line 3263, in loadLocalFile
    c = lm.openFileByName(fn,gui,old_c,previousSettings)
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/core/leoApp.py", line 3291, in openFileByName
    previousSettings=previousSettings)
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/core/leoApp.py", line 1671, in newCommander
    return leoCommands.Commands(fileName,relativeFileName,gui,previousSettings)
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/core/leoCommands.py", line 81, in __init__
    c.finishCreate()
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/core/leoCommands.py", line 336, in finishCreate
    c.frame.finishCreate()
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/plugins/qt_frame.py", line 2067, in finishCreate
    f.top = g.app.gui.frameFactory.createFrame(f)
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/plugins/qt_frame.py", line 4684, in createFrame
    self.createMaster()
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/plugins/qt_frame.py", line 4708, in createMaster
    g.app.gui.attachLeoIcon(mf)
  File "/nix/store/2mxkwgm3n3hcnlif41q2q5vwmq1bhry8-leo-editor-5.1/lib/python2.7/site-packages/leo/plugins/qt_gui.py", line 677, in attachLeoIcon
    window.setWindowIcon(self.appIcon)    
TypeError: QWidget.setWindowIcon(QIcon): argument 1 has unexpected type 'NoneType'
```

**Comment by joachifm** [comment]
This has been fixed.
