### ISSUE TITLE
Cannot run phantomjs

### ISSUE THREAD

**Issue by NicolasPetton** [NixOS/nixpkgs#15719]
## Issue description

With phantomjs2 installed, when running `phantomjs`, I get

```
phantomjs                                                                                              ~
Error executing phantom at /nix/store/i51xm2sih7nih5y20yxka04z77jhrc2b-nodejs-phantomjs-2.1.7/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs
Error: spawn /nix/store/i51xm2sih7nih5y20yxka04z77jhrc2b-nodejs-phantomjs-2.1.7/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:134:18)
    at node.js:962:3
```

## Technical details

* System: 16.09.git.ccf29b7 (Flounder)
* Nix version: nix-env (Nix) 1.11.2

**Comment by DamienCassou** [comment]
I can't reproduce:

```shellCommands
$ nix-env -f '<nixpkgs>' -iA phantomjs2
installing ‘phantomjs-2.1.1’

$ cat /tmp/hello.js 
console.log('Hello, world!');
phantom.exit();

$ phantomjs /tmp/hello.js 
Hello, world!
```

I'm running nixos version 6d16979

**Comment by DamienCassou** [comment]
what is ccf29b7?

**Comment by NicolasPetton** [comment]
@DamienCassou I get the same result when installed using `phantomjs2`.
It turns out that phantomjs 2.1.7 is available as a npm package (`nodePackages.phantomjs`), which is the package that I was using.

I don't see why we should keep both, I think I'll send a PR to remove it from `nodePackages`.

Then I still get (with the same `hello.js`):
