### ISSUE TITLE
clojure-lsp: graalvm build error

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#157574]
### Describe the bug

Recently, clojure-lsp build started to fail on unstable and master

### Steps To Reproduce

- check out `nixos-unstable` or `master`
- `nix-build . -A clojure-lsp`

### Screenshots
```
Fatal error: com.oracle.svm.core.util.VMError$HostedError: Option name "AddAllCharsets" has multiple definitions: com.oracle.svm.hosted.jdk.localization.LocalizationFeature$Options.AddAllCharsets and com.oracle.svm.core.jdk.localization.LocalizationFeature$Options.AddAllCharsets
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at com.oracle.svm.hosted.option.HostedOptionParser.lambda$collectOptions$0(HostedOptionParser.java:74)
        at com.oracle.svm.common.option.CommonOptionParser.collectOptions(CommonOptionParser.java:172)
        at com.oracle.svm.core.option.SubstrateOptionsParser.collectOptions(SubstrateOptionsParser.java:120)
        at com.oracle.svm.hosted.option.HostedOptionParser.collectOptions(HostedOptionParser.java:63)
        at com.oracle.svm.hosted.option.HostedOptionParser.<init>(HostedOptionParser.java:58)
        at com.oracle.svm.hosted.AbstractNativeImageClassLoaderSupport.setupHostedOptionParser(AbstractNativeImageClassLoaderSupport.java:118)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:179)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:121)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:617)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1770)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1477)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1438)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1425)
error: builder for '/nix/store/hhqgbqlpiaxq4bsj6jl3lw4yp5mnpagl-clojure-lsp-2022.01.22-01.31.09.drv' failed with exit code 1;
       last 10 log lines:
       >        at com.oracle.svm.hosted.AbstractNativeImageClassLoaderSupport.setupHostedOptionParser(AbstractNativeImageClassLoaderSupport.java:118)
       >         at com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:179)
       >         at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:121)
       >  at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:617)
       > Error: Image build request failed with exit status 1
       > com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
       >        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1770)
       >  at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1477)
       >      at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1438)
       >       at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1425)

```

### Additional context

Bisecting suggests, that this is because of a recent update to graalvm -> 22.0.0.2

https://github.com/NixOS/nixpkgs/commit/a362925794d7b6f7e562b4c49136ac685d1e38cc

#### Attempted variations

- graalvm17
- changing command line parameters to match https://github.com/clojure-lsp/clojure-lsp/blob/master/cli/graalvm/native-unix-compile.sh
- updating clojure-lsp (already is at latest version)

### Notify maintainers

@ericdallo @babariviere 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.93, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `""`
 - channels(herwig): `""`
 - nixpkgs: `/etc/nixpkgs`

**Comment by ericdallo** [comment]
@bendlas this is related with graalvm bump, but I'm aware of it, next clojure-lsp version which is soon should fix the issue since we will stop using datalevin to use transit as the db
