### ISSUE TITLE
mat2: nautilus-plugin not working

### ISSUE THREAD

**Issue by Stunkymonkey** [NixOS/nixpkgs#157514]
### Describe the bug
When starting `nautilus`:
```
Using python version sys.version_info(major=3, minor=9, micro=6, releaselevel='final', serial=0)
Traceback (most recent call last):
  File "/run/current-system/sw/share/nautilus-python/extensions/mat2.py", line 27, in <module>
    from libmat2 import parser_factory
  File "/nix/store/7am33cqjj4zgmr9gbfiivqw27hldwhz6-python3.9-mat2-0.12.2/lib/python3.9/site-packages/libmat2/parser_factory.py", line 31, in <module>
    __load_all_parsers()
  File "/nix/store/7am33cqjj4zgmr9gbfiivqw27hldwhz6-python3.9-mat2-0.12.2/lib/python3.9/site-packages/libmat2/parser_factory.py", line 28, in __load_all_parsers
    importlib.import_module('.' + name, package='libmat2')
  File "/nix/store/2jk1l6lvp9hys6p7lnzhpxdx8hlrdv7q-python3-3.9.6-env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nix/store/7am33cqjj4zgmr9gbfiivqw27hldwhz6-python3.9-mat2-0.12.2/lib/python3.9/site-packages/libmat2/audio.py", line 7, in <module>
    import mutagen
ModuleNotFoundError: No module named 'mutagen'
```

### Steps To Reproduce
1. start nautilus on console

### Expected behavior
No error and the context-menu is shown

### Notify maintainers

@dotlambda 
maybe @jtojnar could help?

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
  /nix/store/q6ayjwizl0xcbvknkcksy5g4n1ipa6b1-bash-interactive-5.1-p8-dev
copying path '/nix/store/q6ayjwizl0xcbvknkcksy5g4n1ipa6b1-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.2, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(felix): `""`
 - channels(root): `"nixos-21.11.335526.6c4b9f1a2fd, nixos-unstable-22.05pre343321.78cd22c1b86"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
Look at the top of `bin/..mat2-wrapped-wrapped`. You will need something like that in `share/nautilus-python/extensions/mat2.py` to find dependencies.

**Comment by jtojnar** [comment]
Also linking https://github.com/NixOS/nixpkgs/issues/126074 for context.

**Comment by jtojnar** [comment]
Actually, looks like it is there, only incomplete. For some reason `pythonPath` does not contain the contents of `propagatedBuildInputs`.

https://github.com/NixOS/nixpkgs/blob/78e2ef7e3dab7778d823977129e8f8902020ffe6/pkgs/development/python-modules/mat2/default.nix#L79 

In the worse case, you can add it manually:

```diff
--- a/pkgs/development/python-modules/mat2/default.nix
+++ b/pkgs/development/python-modules/mat2/default.nix
@@ -76,7 +76,7 @@ buildPythonPackage rec {
     install -Dm 444 data/mat2.svg -t "$out/share/icons/hicolor/scalable/apps"
     install -Dm 444 doc/mat2.1 -t "$out/share/man/man1"
     install -Dm 444 nautilus/mat2.py -t "$out/share/nautilus-python/extensions"
-    buildPythonPath "$out $pythonPath"
+    buildPythonPath "$out $pythonPath $propagatedBuildInputs"
     patchPythonScript "$out/share/nautilus-python/extensions/mat2.py"
   '' + lib.optionalString dolphinIntegration ''
     install -Dm 444 dolphin/mat2.desktop -t "$out/share/kservices5/ServiceMenus"
```

but then it will fail differently:

```ShellSession
$ env "NAUTILUS_EXTENSION_DIR=$(nix-build -A gnome.nautilus-python --no-out-link)/lib/nautilus/extensions-3.0" "XDG_DATA_DIRS=$(nix-build -A mat2 --no-out-link)/share:$XDG_DATA_DIRS" nautilus
[…]
Traceback (most recent call last):
  File "/nix/store/sqd5ydp6j9pg99vqq2f3ab0ss3q4d7z0-python3.9-mat2-0.12.3/share/nautilus-python/extensions/mat2.py", line 28, in <module>
    from libmat2 import parser_factory
  File "/nix/store/sqd5ydp6j9pg99vqq2f3ab0ss3q4d7z0-python3.9-mat2-0.12.3/lib/python3.9/site-packages/libmat2/parser_factory.py", line 30, in <module>
    __load_all_parsers()
  File "/nix/store/sqd5ydp6j9pg99vqq2f3ab0ss3q4d7z0-python3.9-mat2-0.12.3/lib/python3.9/site-packages/libmat2/parser_factory.py", line 27, in __load_all_parsers
    importlib.import_module('.' + name, package='libmat2')
  File "/nix/store/gras7a25yy9f7djmzrgh1bsiiacg0s9c-python3-3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nix/store/sqd5ydp6j9pg99vqq2f3ab0ss3q4d7z0-python3.9-mat2-0.12.3/lib/python3.9/site-packages/libmat2/pdf.py", line 15, in <module>
    gi.require_version('Poppler', '0.18')
  File "/nix/store/xgqn1hdpc08m0rs8pwihxwq01ba25yjc-python3.9-pygobject-3.42.0/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Poppler not available
```

so you need to fix the typelib as mentioned in the manual:

https://nixos.org/manual/nixpkgs/stable/#ssec-gnome-common-issues-unwrappable-package-gnome-shell-ext

**Comment by Stunkymonkey** [comment]
I think i followed your suggestions: https://github.com/Stunkymonkey/nixpkgs/tree/mat2-nautilus-extension
but I am still getting the same error :confused:

**Comment by jtojnar** [comment]
As you can see from the error, you need Poppler, not Gmenu typelib. And possibly some other.

**Comment by Stunkymonkey** [comment]
i can confirm, that the entry is now visible, but two times. Might be, that my configuration is weird.
