### ISSUE TITLE
`odoo` package fail to run: No module named 'werkzeug.posixemulation' (nixpkgs-unstable)

### ISSUE THREAD

**Issue by timothee-haudebourg** [NixOS/nixpkgs#157702]
## Issue description

The executable provided by the `odoo` package raise an error when started because of a missing python package:
```
$ odoo
Traceback (most recent call last):
  File "/nix/store/hbqm1kr8fvs1djbh9llhf9sahnc7iqb1-odoo-15.0.20211029/bin/.odoo-wrapped", line 6, in <module>
    import odoo
  File "/nix/store/hbqm1kr8fvs1djbh9llhf9sahnc7iqb1-odoo-15.0.20211029/lib/python3.9/site-packages/odoo/__init__.py", line 134, in <module>
    from . import http
  File "/nix/store/hbqm1kr8fvs1djbh9llhf9sahnc7iqb1-odoo-15.0.20211029/lib/python3.9/site-packages/odoo/http.py", line 58, in <module>
    from .tools._vendor import sessions
  File "/nix/store/hbqm1kr8fvs1djbh9llhf9sahnc7iqb1-odoo-15.0.20211029/lib/python3.9/site-packages/odoo/tools/_vendor/sessions.py", line 29, in <module>
    from werkzeug.posixemulation import rename
ModuleNotFoundError: No module named 'werkzeug.posixemulation'
```

## Technical details

```
building shell
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.91, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels: `"nixpkgs-22.05pre349906.7f65e4abd5e"`
```

@mkg20001 I see you are declared as a maintainer, is it a known issue?

**Comment by mkg20001** [comment]
Yes

I have a fix here https://github.com/NixOS/nixpkgs/pull/157689

**Comment by timothee-haudebourg** [comment]
Thanks for the quick answer, I guess I can close this then.

**Comment by mkg20001** [comment]
It's not fixed yet so let's leave this open

**Comment by mkg20001** [comment]
Once PR is merged this can be closed
