### ISSUE TITLE
GitHub runner failing

### ISSUE THREAD

**Issue by kirinnee** [NixOS/nixpkgs#158970]
### Describe the bug
Trying to configure GitHub runner fails

### Steps To Reproduce
1. Start a shell with `github-runner`
  ```sh
  nix-shell -p github-runner
  ```
2. Configure with `github-runner`
  ```sh
  config.sh
  ```

### Expected behavior
Configure a Github runner

### Screenshots
Error:
```
touch: cannot touch '.env': Permission denied
./env.sh: line 37: .path: Permission denied
./env.sh: line 32: .env: Permission denied
./env.sh: line 32: .env: Permission denied
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/nix/store/5mfdyxrakk7vl50szz9pfly1j53vbawr-github-runner-2.287.1/_diag' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at GitHub.Runner.Common.HostTraceListener..ctor(String logFileDirectory, String logFilePrefix, Int32 pageSizeLimit, Int32 retentionDays)
   at GitHub.Runner.Common.HostContext..ctor(String hostType, String logFile)
   at GitHub.Runner.Listener.Program.Main(String[] args)
/nix/store/5mfdyxrakk7vl50szz9pfly1j53vbawr-github-runner-2.287.1/lib/config.sh: line 81: 11937 Aborted
```
### Additional context
Unsure if this is how the Runner is supposed to be used.

### Notify maintainers
@veehaitch @newAM 

### Metadata

```console
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/4cx98f94l8a27rn3fgi4c54mvvivvk0z-nix-info
copying path '/nix/store/4cx98f94l8a27rn3fgi4c54mvvivvk0z-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-97-generic, Ubuntu, 20.04.3 LTS (Focal Fossa)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by veehaitch** [comment]
Thanks for reporting!

I think, however, this isn't strictly a bug. The upstream runner assumes that its root directory is writable to store configuration data. When using Nix, the runner artifacts live in the Nix store which is read-only. Therefore, we patched the runner to have it consider the value of the environment variable `RUNNER_ROOT` as its root directory.

Also refer to the NixOS module:

https://github.com/NixOS/nixpkgs/blob/5bc03b163ad1fbd5339481e2d9827e9f8a658e60/nixos/modules/services/continuous-integration/github-runner.nix#L209-L218

**Comment by kirinnee** [comment]
@veehaitch Thank you so much for your reply!

 It is working better now. I am running my GitHub Runners with:
```sh
RUNNER_ROOT="$(pwd)" config.sh --url <url> --token <token>
```
It configures and starts the runner without much issues. However, it seems that the environment cannot be loaded:
```console
touch: cannot touch '.env': Permission denied
./env.sh: line 37: .path: Permission denied
./env.sh: line 32: .env: Permission denied
./env.sh: line 32: .env: Permission denied
```
This seems to export my current environment to the runner, I am not sure how important it is. But even with this setup, my GitHub runners run into issues trying to invoke `nix-shell` within the Action script itself:
![image](https://user-images.githubusercontent.com/15990242/153563507-d68367ff-ba57-4524-b91c-43b1d9ff0289.png)

I believe this is related to the `.env.sh` having permission denied since it cannot inject my `LD_PATH` for `nix-shell` to use, but I could be mistaken.

I have tried running the GitHub Action Runner manually (downloading from GitHub and extracting tarball etc), and it works (with `nix-shell` without problem). 

Again, I really appreciate such a fast reply and thank you for your time!

**Comment by veehaitch** [comment]
> Is the error at the frontend intended after setting RUNNER_ROOT?

You can ignore that.

I did a basic test on Ubuntu using Nix: the service configures and runs without issues. A minimal workflow also succeeded.

Here's what I did:

```ShellSession
export RUNNER_ROOT=`pwd`
./result/bin/config.sh --unattended --disableupdate --work "$(mktemp -d)" --url 'https
://github.com/user/repo' --token "ADS7XXXXXXXXXXXXXXXXXXXXXXXXX" --name "selfhosted-test" --replace
# Make sure RUNNER_ROOT is still set
./result/bin/runsvc.sh
```

**Comment by kirinnee** [comment]
I see. The problem does not lie with setting up, but after setting up. Anything running within the scope of `nix-shell` will face the `glibc` problem. 

[Here](https://github.com/kirinnee/github-runner-nix-minimal-reproduction) is a repository with minimal reproduction, you see the error within [Actions Tab](https://github.com/kirinnee/github-runner-nix-minimal-reproduction/runs/5181219473?check_suite_focus=true#step:3:1). 

If it would help, I would love to give you SSH access to the machine, I'll just need your public key.

The machine installed with `docker` using `apt` and `github-runner` via 
```sh
nix-env -i github-runner
```

This is the exact script to start the runner (with the token replaced with `x`):
```sh
#!/bin/sh

export RUNNER_ROOT=`pwd`
config.sh --name "selfhosted-test" --unattended --disableupdate --work "_work" --url https://github.com/kirinnee/github-runner-nix-minimal-reproduction --token ADZ7XXXXXXXXXXXXXXXXXXXXXXXXX --replace
echo $RUNNER_ROOT
run.sh 
```

Here is the nix status info:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-97-generic, Ubuntu, 20.04.3 LTS (Focal Fossa)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```
 
 Thank you again, for you time.

**Comment by hiroqn** [comment]
I got same error, but runner works well.

Maybe, this code cause this issue
https://github.com/actions/runner/blob/408d6c579c36f0eb318acfdafdcbafc872696501/src/Misc/layoutroot/config.sh#L65

```
# Change directory to the script root directory
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd "$DIR"
```

**Comment by cmoog** [comment]
https://github.com/NixOS/nixpkgs/commit/568b598a9a86f9107e754672b373038db53e4bdc fixes this behavior on master. This issue is probably good to close.

**Comment by veehaitch** [comment]
As mentioned by @cmoog, the issue should be resolved. Feel free to reopen, if not.
