### ISSUE TITLE
python310Packages.ipython build error

### ISSUE THREAD

**Issue by StarrFox** [NixOS/nixpkgs#159155]
### Describe the bug
Running the command `nix-shell -p python10Packages.ipython` results in an error which seems to be caused by pytest. 

traceback:
```
running install tests
Traceback (most recent call last):
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/bin/.py.test-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/nix/store/hlkcjhrgihs238iqh1z1xc9s2r1qh4mj-python3.10-pluggy-1.0.0/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/nix/store/hlkcjhrgihs238iqh1z1xc9s2r1qh4mj-python3.10-pluggy-1.0.0/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/nix/store/hlkcjhrgihs238iqh1z1xc9s2r1qh4mj-python3.10-pluggy-1.0.0/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/lib/python3.10/site-packages/_pytest/helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/nix/store/hlkcjhrgihs238iqh1z1xc9s2r1qh4mj-python3.10-pluggy-1.0.0/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/nix/store/hlkcjhrgihs238iqh1z1xc9s2r1qh4mj-python3.10-pluggy-1.0.0/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 988, in _preparse
    self.pluginmanager.consider_preparse(args, exclude_only=False)
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 547, in consider_preparse
    self.consider_pluginarg(parg)
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 572, in consider_pluginarg
    self.import_plugin(arg, consider_entry_points=True)
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 613, in import_plugin
    __import__(importspec)
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 143, in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
  File "/nix/store/5bkkaraqm1af77bmzvpxa85r3nl2rca7-python3.10-pytest-5.4.3/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 330, in _rewrite_test
    co = compile(tree, fn, "exec", dont_inherit=True)
TypeError: required field "lineno" missing from alias
builder for '/nix/store/1hcqlmjvr2jb3y20k4p0zi5my6n2v6sy-python3.10-pytest-5.4.3.drv' failed with exit code 1
```

The full output of the command can be found here: http://ix.io/3Pgq

### Steps To Reproduce
1. nix-shell -p python10Packages.ipython

### Expected behavior
I wanted a new shell environment with python3.10 ipython 

### Notify maintainers

@bjornfor @FRidh 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.96, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(starr): `""`
 - channels(root): `"nixos-21.11.335820.521e4d7d13b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by vcunat** [comment]
I don't think python 3.10 is really supported in nixpkgs 21.11 yet.  On unstable/master this builds: https://hydra.nixos.org/job/nixpkgs/trunk/python310Packages.ipython.x86_64-linux  

_Anyway, I just stumbled upon this by accident; I won't be of much help here._

**Comment by FRidh** [comment]
Correct
