### ISSUE TITLE
Can't install kitty

### ISSUE THREAD

**Issue by marcelarie** [NixOS/nixpkgs#159813]
### Describe the bug
After doing a `nix-rebuild switch --upgrade-all` nix can't install `kitty`. I'm not sure if the `upgrade-all` is the real reason because I tried to do a rollback of the channel and it still happens.
### Steps To Reproduce
1. `nix-shell -p kitty`

### Expected behavior
To install kitty in the nix-shell.

### Screenshots
![2022-02-13_12-03](https://user-images.githubusercontent.com/62728887/153750201-3cf2a03f-c820-4677-a1b8-ee3706926ebc.png)
![2022-02-13_12-04](https://user-images.githubusercontent.com/62728887/153750202-6148adff-1c13-4734-a265-653bd9f2a75f.png)

<details>
<summary>Error</summary>
this derivation will be built:
  /nix/store/dhah3nazhf161y7rb77770khvmsxs8xh-kitty-0.24.2.drv
building '/nix/store/dhah3nazhf161y7rb77770khvmsxs8xh-kitty-0.24.2.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/89jpgy2661rrlllknmlxmfc164vinaqa-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/update-on-ubuntu
patching sources
building
CC: ['gcc'] (10, 3)
[16/16] Generating wayland-text-input-unstable-v3-client-protocol.c ... done...
[102/102] Compiling kitty/gl-wrapper.c ... done....ent-protocol.c ...col.c ... ......
[7/7] Linking kittens/choose/subseq_matcher ... done.
make docs
make -C docs man
make[1]: Entering directory '/build/source/docs'
sphinx-build -M man "." "_build" -n -q -j auto -T
/build/source/docs/changelog.rst:2344: ERROR: GitHub commit id "8dea5b3" not recognized.
/build/source/docs/changelog.rst:2459: ERROR: GitHub commit id "ad1109b" not recognized.
/build/source/docs/changelog.rst:2471: ERROR: GitHub commit id "889ca77" not recognized.
make[1]: Leaving directory '/build/source/docs'
make -C docs html
make[1]: Entering directory '/build/source/docs'
sphinx-build -M html "." "_build" -n -q -j auto -T

Traceback (most recent call last):
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/__init__.py", line 158, in _html_page_context
    _add_asset_hashes(
  File "/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/__init__.py", line 138, in _add_asset_hashes
    static[index].filename = _asset_hash(asset)  # type: ignore
  File "/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/__init__.py", line 130, in _asset_hash
    digest = hashlib.sha1(full_path.read_bytes()).hexdigest()
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/pathlib.py", line 1259, in read_bytes
    with self.open(mode='rb') as f:
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/theme/furo/static/styles/furo.css'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 529, in write
    self._write_parallel(sorted(docnames),
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 556, in _write_parallel
    self.write_doc(firstname, doctree)
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 632, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1033, in handle_page
    newtmpl = self.app.emit_firstresult('html-page-context', pagename,
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/application.py", line 464, in emit_firstresult
    return self.events.emit_firstresult(event, *args,
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/events.py", line 119, in emit_firstresult
    for result in self.emit(name, *args, allowed_exceptions=allowed_exceptions):
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/events.py", line 109, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function _html_page_context at 0x7ffff3215c10> for event 'html-page-context' threw an exception (exception: [Errno 2] No such file or directory: '/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/theme/furo/static/styles/furo.css')

Extension error (furo):
Handler <function _html_page_context at 0x7ffff3215c10> for event 'html-page-context' threw an exception (exception: [Errno 2] No such file or directory: '/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/theme/furo/static/styles/furo.css')
make[1]: *** [Makefile:24: html] Error 2
make[1]: Leaving directory '/build/source/docs'
make: *** [Makefile:42: html] Error 2
error: builder for '/nix/store/dhah3nazhf161y7rb77770khvmsxs8xh-kitty-0.24.2.drv' failed with exit code 2;
       last 10 log lines:
       >     for result in self.emit(name, *args, allowed_exceptions=allowed_exceptions):
       >   File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/events.py", line 109, in emit
       >     raise ExtensionError(__("Handler %r for event %r threw an exception") %
       > sphinx.errors.ExtensionError: Handler <function _html_page_context at 0x7ffff3215c10> for event 'html-page-context' threw an exception (exception: [Errno 2] No such file or directory: '/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/theme/furo/static/styles/furo.css')
       >
       > Extension error (furo):
       > Handler <function _html_page_context at 0x7ffff3215c10> for event 'html-page-context' threw an exception (exception: [Errno 2] No such file or directory: '/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/theme/furo/static/styles/furo.css')
       > make[1]: *** [Makefile:24: html] Error 2
       > make[1]: Leaving directory '/build/source/docs'
       > make: *** [Makefile:42: html] Error 2
       For full logs, run 'nix log /nix/store/dhah3nazhf161y7rb77770khvmsxs8xh-kitty-0.24.2.drv'.
</details>

### Metadata
```console
~ on  nix [!]
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.98, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixos-22.05pre353535.48d63e924a2"`
 - channels(marcel): `"home-manager, nixgl, nixos, nixos-21.11-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sersorrel** [comment]
this was, afaict, fixed in #159255, but that has not yet made it into nixos-unstable because the channel is blocked: #159612
