### ISSUE TITLE
kitty-0.24.2 fails to build

### ISSUE THREAD

**Issue by dag-h** [NixOS/nixpkgs#160221]
### Describe the bug
Kitty fails to build. 

### Steps To Reproduce
1. Try to build kitty-0.42.2

### Expected behavior
It builds.

### Additional context

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/89jpgy2661rrlllknmlxmfc164vinaqa-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/update-on-ubuntu
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "buildPhase" }
building
CC: ['gcc'] (10, 3)

[K[1/16] Generating [32mwayland-xdg-shell-client-protocol.h[39m ...
[K[2/16] Generating [32mwayland-xdg-shell-client-protocol.c[39m ...
[K[3/16] Generating [32mwayland-viewporter-client-protocol.h[39m ...
[K[4/16] Generating [32mwayland-viewporter-client-protocol.c[39m ...
[K[5/16] Generating [32mwayland-relative-pointer-unstable-v1-client-protocol.h[39m ...
[K[6/16] Generating [32mwayland-relative-pointer-unstable-v1-client-protocol.c[39m ...
[K[7/16] Generating [32mwayland-pointer-constraints-unstable-v1-client-protocol.h[39m ...
[K[8/16] Generating [32mwayland-pointer-constraints-unstable-v1-client-protocol.c[39m ...
[K[9/16] Generating [32mwayland-idle-inhibit-unstable-v1-client-protocol.h[39m ...
[K[10/16] Generating [32mwayland-idle-inhibit-unstable-v1-client-protocol.c[39m ...
[K[11/16] Generating [32mwayland-xdg-decoration-unstable-v1-client-protocol.h[39m ...
[K[12/16] Generating [32mwayland-xdg-decoration-unstable-v1-client-protocol.c[39m ...
[K[13/16] Generating [32mwayland-primary-selection-unstable-v1-client-protocol.h[39m ...
[K[14/16] Generating [32mwayland-primary-selection-unstable-v1-client-protocol.c[39m ...
[K[15/16] Generating [32mwayland-text-input-unstable-v3-client-protocol.h[39m ...
[K[16/16] Generating [32mwayland-text-input-unstable-v3-client-protocol.c[39m ... done

[K[1/102] Compiling [32mkitty/unicode-data.c[39m ...
[K[2/102] Compiling [32mkitty/screen.c[39m ...
[K[3/102] Compiling [32m[x11] glfw/x11_window.c[39m ...
[K[4/102] Compiling [32mkitty/graphics.c[39m ...
[K[5/102] Compiling [32m[wayland] glfw/wl_window.c[39m ...
[K[6/102] Compiling [32mkitty/glfw.c[39m ...
[K[7/102] Compiling [32mkitty/fonts.c[39m ...
[K[8/102] Compiling [32mkitty/child-monitor.c[39m ...
[K[9/102] Compiling [32mkitty/parser.c[39m ...
[K[10/102] Compiling [32mkitty/parser.c[39m ...
[K[11/102] Compiling [32mkitty/shaders.c[39m ...
[K[12/102] Compiling [32mkitty/state.c[39m ...
[K[13/102] Compiling [32m[x11] glfw/input.c[39m ...
[K[14/102] Compiling [32m[wayland] glfw/input.c[39m ...
[K[15/102] Compiling [32m[x11] glfw/xkb_glfw.c[39m ...
[K[16/102] Compiling [32m[wayland] glfw/xkb_glfw.c[39m ...
[K[17/102] Compiling [32mkitty/mouse.c[39m ...
[K[18/102] Compiling [32m[x11] glfw/window.c[39m ...
[K[19/102] Compiling [32m[wayland] glfw/window.c[39m ...
[K[20/102] Compiling [32mkitty/line.c[39m ...
[K[21/102] Compiling [32mkitty/freetype.c[39m ...
[K[22/102] Compiling [32m[wayland] glfw/wl_init.c[39m ...
[K[23/102] Compiling [32mkitty/glfw-wrapper.c[39m ...
[K[24/102] Compiling [32m[x11] glfw/x11_init.c[39m ...
[K[25/102] Compiling [32mkitty/freetype_render_ui_text.c[39m ...
[K[26/102] Compiling [32m[x11] glfw/egl_context.c[39m ...
[K[27/102] Compiling [32m[wayland] glfw/egl_context.c[39m ...
[K[28/102] Compiling [32mkitty/disk-cache.c[39m ...
[K[29/102] Compiling [32m[x11] glfw/glx_context.c[39m ...
[K[30/102] Compiling [32mkitty/colors.c[39m ...
[K[31/102] Compiling [32mkitty/line-buf.c[39m ...
[K[32/102] Compiling [32mkitty/history.c[39m ...
[K[33/102] Compiling [32m[x11] glfw/x11_monitor.c[39m ...
[K[34/102] Compiling [32m[x11] glfw/context.c[39m ...
[K[35/102] Compiling [32m[wayland] glfw/context.c[39m ...
[K[36/102] Compiling [32m[wayland] glfw/wl_client_side_decorations.c[39m ...
[K[37/102] Compiling [32m[x11] glfw/ibus_glfw.c[39m ...
[K[38/102] Compiling [32m[wayland] glfw/ibus_glfw.c[39m ...
[K[39/102] Compiling [32mkitty/charsets.c[39m ...
[K[40/102] Compiling [32mkitty/charsets.c[39m ...
[K[41/102] Compiling [32mkitty/key_encoding.c[39m ...
[K[42/102] Compiling [32m[x11] glfw/monitor.c[39m ...
[K[43/102] Compiling [32m[wayland] glfw/monitor.c[39m ...
[K[44/102] Compiling [32mkitty/fontconfig.c[39m ...
[K[45/102] Compiling [32m[x11] glfw/backend_utils.c[39m ...
[K[46/102] Compiling [32m[wayland] glfw/backend_utils.c[39m ...
[K[47/102] Compiling [32m[x11] glfw/linux_joystick.c[39m ...
[K[48/102] Compiling [32m[wayland] glfw/linux_joystick.c[39m ...
[K[49/102] Compiling [32m[x11] glfw/dbus_glfw.c[39m ...
[K[50/102] Compiling [32m[wayland] glfw/dbus_glfw.c[39m ...
[K[51/102] Compiling [32m[x11] glfw/vulkan.c[39m ...
[K[52/102] Compiling [32m[wayland] glfw/vulkan.c[39m ...
[K[53/102] Compiling [32m[x11] glfw/init.c[39m ...
[K[54/102] Compiling [32m[wayland] glfw/init.c[39m ...
[K[55/102] Compiling [32m[x11] glfw/osmesa_context.c[39m ...
[K[56/102] Compiling [32m[wayland] glfw/osmesa_context.c[39m ...
[K[57/102] Compiling [32mkitty/keys.c[39m ...
[K[58/102] Compiling [32mkitty/data-types.c[39m ...
[K[59/102] Compiling [32mkitty/gl.c[39m ...
[K[60/102] Compiling [32mkitty/cursor.c[39m ...
[K[61/102] Compiling [32mkitty/ringbuf.c[39m ...
[K[62/102] Compiling [32mkittens/transfer/rsync.c[39m ...
[K[63/102] Building [32mlauncher[39m ...
[K[64/102] Compiling [32mkittens/choose/main.c[39m ...
[K[65/102] Compiling [32mkittens/diff/speedup.c[39m ...
[K[66/102] Compiling [32m[wayland] glfw/wl_monitor.c[39m ...
[K[67/102] Compiling [32mkitty/kittens.c[39m ...
[K[68/102] Compiling [32mkitty/child.c[39m ...
[K[69/102] Compiling [32mkittens/choose/score.c[39m ...
[K[70/102] Compiling [32mkitty/desktop.c[39m ...
[K[71/102] Compiling [32mkitty/png-reader.c[39m ...
[K[72/102] Compiling [32m[wayland] glfw/wayland-xdg-shell-client-protocol.c[39m ...
[K[73/102] Compiling [32m[wayland] glfw/wl_text_input.c[39m ...
[K[74/102] Compiling [32mkitty/hyperlink.c[39m ...
[K[75/102] Compiling [32m[x11] glfw/linux_notify.c[39m ...
[K[76/102] Compiling [32m[wayland] glfw/linux_notify.c[39m ...
[K[77/102] Compiling [32m[wayland] glfw/wayland-primary-selection-unstable-v1-client-protocol.c[39m ...
[K[78/102] Compiling [32mkitty/loop-utils.c[39m ...
[K[79/102] Compiling [32mkitty/wcswidth.c[39m ...
[K[80/102] Compiling [32m[wayland] glfw/wayland-pointer-constraints-unstable-v1-client-protocol.c[39m ...
[K[81/102] Compiling [32m[wayland] glfw/linux_desktop_settings.c[39m ...
[K[82/102] Compiling [32mkitty/fast-file-copy.c[39m ...
[K[83/102] Compiling [32m[wayland] glfw/wayland-text-input-unstable-v3-client-protocol.c[39m ...
[K[84/102] Compiling [32mkittens/unicode_input/unicode_names.c[39m ...
[K[85/102] Compiling [32mkittens/choose/output.c[39m ...
[K[86/102] Compiling [32m[x11] glfw/posix_thread.c[39m ...
[K[87/102] Compiling [32m[wayland] glfw/posix_thread.c[39m ...
[K[88/102] Compiling [32mkitty/window_logo.c[39m ...
[K[89/102] Compiling [32m[wayland] glfw/wayland-xdg-decoration-unstable-v1-client-protocol.c[39m ...
[K[90/102] Compiling [32m[wayland] glfw/wayland-relative-pointer-unstable-v1-client-protocol.c[39m ...
[K[91/102] Compiling [32mkitty/glyph-cache.c[39m ...
[K[92/102] Compiling [32m[wayland] glfw/wayland-idle-inhibit-unstable-v1-client-protocol.c[39m ...
[K[93/102] Compiling [32m[wayland] glfw/wayland-viewporter-client-protocol.c[39m ...
[K[94/102] Compiling [32mkitty/logging.c[39m ...
[K[95/102] Compiling [32m[wayland] glfw/wl_cursors.c[39m ...
[K[96/102] Compiling [32mkittens/choose/unix_compat.c[39m ...
[K[97/102] Compiling [32mkitty/utmp.c[39m ...
[K[98/102] Compiling [32mkitty/cleanup.c[39m ...
[K[99/102] Compiling [32m[x11] glfw/monotonic.c[39m ...
[K[100/102] Compiling [32m[wayland] glfw/monotonic.c[39m ...
[K[101/102] Compiling [32mkitty/monotonic.c[39m ...
[K[102/102] Compiling [32mkitty/gl-wrapper.c[39m ... done

[K[1/7] Linking [32mkitty/fast_data_types[39m ...
[K[2/7] Linking [32m[x11] kitty/glfw-x11[39m ...
[K[3/7] Linking [32m[wayland] kitty/glfw-wayland[39m ...
[K[4/7] Linking [32mkittens/unicode_input/unicode_names[39m ...
[K[5/7] Linking [32mkittens/diff/diff_speedup[39m ...
[K[6/7] Linking [32mkittens/transfer/rsync[39m ...
[K[7/7] Linking [32mkittens/choose/subseq_matcher[39m ... done
make docs
make -C docs man
make[1]: Entering directory '/build/source/docs'
sphinx-build -M man "." "_build" -n -q -j auto -T   
[31m/build/source/docs/changelog.rst:2344: ERROR: GitHub commit id "8dea5b3" not recognized.[39;49;00m
[31m/build/source/docs/changelog.rst:2459: ERROR: GitHub commit id "ad1109b" not recognized.[39;49;00m
[31m/build/source/docs/changelog.rst:2471: ERROR: GitHub commit id "889ca77" not recognized.[39;49;00m
make[1]: Leaving directory '/build/source/docs'
make -C docs html
make[1]: Entering directory '/build/source/docs'
sphinx-build -M html "." "_build" -n -q -j auto -T   

Traceback (most recent call last):
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/__init__.py", line 158, in _html_page_context
    _add_asset_hashes(
  File "/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/__init__.py", line 138, in _add_asset_hashes
    static[index].filename = _asset_hash(asset)  # type: ignore
  File "/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/__init__.py", line 130, in _asset_hash
    digest = hashlib.sha1(full_path.read_bytes()).hexdigest()
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/pathlib.py", line 1259, in read_bytes
    with self.open(mode='rb') as f:
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/theme/furo/static/styles/furo.css'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 529, in write
    self._write_parallel(sorted(docnames),
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 556, in _write_parallel
    self.write_doc(firstname, doctree)
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 632, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1033, in handle_page
    newtmpl = self.app.emit_firstresult('html-page-context', pagename,
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/application.py", line 464, in emit_firstresult
    return self.events.emit_firstresult(event, *args,
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/events.py", line 119, in emit_firstresult
    for result in self.emit(name, *args, allowed_exceptions=allowed_exceptions):
  File "/nix/store/13z9v2893iapkj12gk47q04w2197gysq-python3.9-sphinx-4.4.0/lib/python3.9/site-packages/sphinx/events.py", line 109, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function _html_page_context at 0x7ffff3212c10> for event 'html-page-context' threw an exception (exception: [Errno 2] No such file or directory: '/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/theme/furo/static/styles/furo.css')

[91mExtension error (furo):[39;49;00m
Handler <function _html_page_context at 0x7ffff3212c10> for event 'html-page-context' threw an exception (exception: [Errno 2] No such file or directory: '/nix/store/pppq4jc77qw9qv4rqghqa32rjdm314hq-python3.9-furo-2022.1.2/lib/python3.9/site-packages/furo/theme/furo/static/styles/furo.css')
make[1]: *** [Makefile:24: html] Error 2
make[1]: Leaving directory '/build/source/docs'
make: *** [Makefile:42: html] Error 2

```

### Notify maintainers
@tex @rvolosatovs @Luflosi

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.7, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220127_558c4ee`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Luflosi** [comment]
This was fixed by #159255, which hasn't made it's way into nixpkgs-unstable yet: https://nixpk.gs/pr-tracker.html?pr=159255.
