### ISSUE TITLE
matrix-synapse: matrix-synapse-shared-secret-auth receives unexpected argument

### ISSUE THREAD

**Issue by CRTified** [NixOS/nixpkgs#160526]
### Describe the bug

The plugin `matrix-synapse-shared-secret-auth` receives an unexpected keyword argument `account_handler`, causing `matrix-synapse` to not star.

### Steps To Reproduce
Add `matrix-synapse-shared-secret-auth` to `services.matrix-synapse.plugins` and configure it.

### Expected behavior
`matrix-synapse` should start properly

### Additional context

```
Feb 18 00:56:19 cloudbox systemd[1]: Starting Synapse Matrix homeserver...
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: This server is configured to use 'matrix.org' as its trusted key server via the
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: server since it is long-lived, stable and trusted. However, some admins may
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: wish to use another server for this purpose.
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: To suppress this warning and continue using 'matrix.org', admins should set
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: --------------------------------------------------------------------------------
Feb 18 00:56:21 cloudbox synapse[2315949]: root: [main] ***** STARTING SERVER *****
Feb 18 00:56:21 cloudbox synapse[2315949]: root: [main] Server /nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/bin/synapse_homeserver version 1.52.0
Feb 18 00:56:21 cloudbox synapse[2315949]: synapse.handlers.auth: [sentinel] Error while initializing <class 'shared_secret_authenticator.SharedSecretAuthProvider'>: __init__() got an unexpected keyword argument 'account_handler'
Feb 18 00:56:21 cloudbox synapse[2315949]: synapse.app._base: [sentinel] Error during startup
                                           Traceback (most recent call last):
                                             File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/_base.py", line 227, in wrapper
                                               await cb(*args, **kwargs)
                                             File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/homeserver.py", line 405, in start
                                               await _base.start(hs)
                                             File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/_base.py", line 444, in start
                                               load_legacy_password_auth_providers(hs)
                                             File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/handlers/auth.py", line 1909, in load_legacy_password_auth_providers
                                               load_single_legacy_password_auth_provider(
                                             File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/handlers/auth.py", line 1920, in load_single_legacy_password_auth_provider
                                               provider = module(config=config, account_handler=api)
                                           TypeError: __init__() got an unexpected keyword argument 'account_handler'
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: Error during startup:
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: Traceback (most recent call last):
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:   File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/_base.py", line 227, in wrapper
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:     await cb(*args, **kwargs)
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:   File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/homeserver.py", line 405, in start
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:     await _base.start(hs)
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:   File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/_base.py", line 444, in start
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:     load_legacy_password_auth_providers(hs)
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:   File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/handlers/auth.py", line 1909, in load_legacy_password_auth_providers
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:     load_single_legacy_password_auth_provider(
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:   File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/handlers/auth.py", line 1920, in load_single_legacy_password_auth_provider
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:     provider = module(config=config, account_handler=api)
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: TypeError: __init__() got an unexpected keyword argument 'account_handler'
Feb 18 00:56:21 cloudbox systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Feb 18 00:56:21 cloudbox systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Feb 18 00:56:21 cloudbox systemd[1]: Failed to start Synapse Matrix homeserver.
Feb 18 00:56:21 cloudbox systemd[1]: matrix-synapse.service: Consumed 2.805s CPU time, no IP traffic.
Feb 18 00:56:22 cloudbox systemd[1]: matrix-synapse.service: Scheduled restart job, restart counter is at 3.
Feb 18 00:56:22 cloudbox systemd[1]: Stopped Synapse Matrix homeserver.
Feb 18 00:56:22 cloudbox systemd[1]: matrix-synapse.service: Consumed 2.805s CPU time, no IP traffic.
```

### Notify maintainers
@sumnerevans 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.89, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220127_558c4ee`
 - channels(god): `"nur"`
 - channels(root): `"home-manager-20.09, nixos-20.09.4407.1c1f5649bb9, nixos-mailserver-20.09.tar.gz, nixos-unstable-22.05pre334685.8a308775674"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

(Older channel, system is deployed via a flake).

**Comment by CRTified** [comment]
This seems to be caused by being incompatible with 1.52.0 and not a problem for nixpkgs

**Comment by CRTified** [comment]
Upstream issue with hotfix: https://github.com/devture/matrix-synapse-shared-secret-auth/issues/16

Hotfix can be applied like this:
```nix

    (self: super: {
      matrix-shared-secret-auth =
        super.matrix-synapse.plugins.matrix-synapse-shared-secret-auth.overrideAttrs
        (o: rec {
          version = "2.0.2";
          src = self.fetchFromGitHub {
            owner = "devture";
            repo = "matrix-synapse-shared-secret-auth";
            rev = version;
            hash = "sha256-qzXKwTEOMtdvsxoU3Xh3vQyhK+Q18LfkeSts7EyDIXE=";
          };
          patches = [ ./ssap.patch ];
        });
    })
```

Note that you'll have to use `pkgs.matrix-shared-secret-auth` with this overlay.

**Comment by CRTified** [comment]
Might also be caused by `shared-secret-auth` v2.

**Comment by CRTified** [comment]
This was a user-error - I configured it wrong.
