### ISSUE TITLE
`mlflow ui` raises ModuleNotFoundError

### ISSUE THREAD

**Issue by YodaEmbedding** [NixOS/nixpkgs#161049]
### Describe the bug
Running `mlflow ui` raises `ModuleNotFoundError: No module named 'mlflow'`.

Full traceback:
```
λ mlflow ui
[2022-02-20 03:45:47 -0800] [3321112] [INFO] Starting gunicorn 20.1.0
[2022-02-20 03:45:47 -0800] [3321112] [INFO] Listening at: http://127.0.0.1:5000 (3321112)
[2022-02-20 03:45:47 -0800] [3321112] [INFO] Using worker: sync
[2022-02-20 03:45:47 -0800] [3321113] [INFO] Booting worker with pid: 3321113
[2022-02-20 03:45:47 -0800] [3321113] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/nix/store/c556v9dcfk8xrqm19mfi82d99mgclz21-python3.9-gunicorn-20.1.0/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/nix/store/c556v9dcfk8xrqm19mfi82d99mgclz21-python3.9-gunicorn-20.1.0/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/nix/store/c556v9dcfk8xrqm19mfi82d99mgclz21-python3.9-gunicorn-20.1.0/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/nix/store/c556v9dcfk8xrqm19mfi82d99mgclz21-python3.9-gunicorn-20.1.0/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/nix/store/c556v9dcfk8xrqm19mfi82d99mgclz21-python3.9-gunicorn-20.1.0/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/nix/store/c556v9dcfk8xrqm19mfi82d99mgclz21-python3.9-gunicorn-20.1.0/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/nix/store/c556v9dcfk8xrqm19mfi82d99mgclz21-python3.9-gunicorn-20.1.0/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/nix/store/2c9w4p2x6x0l64fdvcmc11app7x4xran-python3-3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mlflow'
[2022-02-20 03:45:47 -0800] [3321113] [INFO] Worker exiting (pid: 3321113)
[2022-02-20 03:45:47 -0800] [3321112] [INFO] Shutting down: Master
[2022-02-20 03:45:47 -0800] [3321112] [INFO] Reason: Worker failed to boot.
Running the mlflow server failed. Please see the logs above for details.
```

### Steps To Reproduce
Simply install `mlflow`:
```nix
{
  description = "simple mlflow flake";

  inputs.nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs-unstable }: {

    defaultPackage.x86_64-linux =
      with import nixpkgs-unstable { system = "x86_64-linux"; };
      mkShell {
        packages = [
          python3
          python3Packages.mlflow
        ];
      };

  };
}
```

### Expected behavior
No error.

### Screenshots
N/A.

### Additional context
N/A.

### Notify maintainers
@tbenst 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.96, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.333896.a640d8394f3, nixos-unstable-22.05pre335103.6daa4a5c045"`
 - channels(mulhaq): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

`flake.lock`:
```
{
  "nodes": {
    "nixpkgs-unstable": {
      "locked": {
        "lastModified": 1644613700,
        "narHash": "sha256-wLRPJclMH8vsHuFtyI78aF09lw5mbi3lMB6uiK5S2wE=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "23d785aa6f853e6cf3430119811c334025bbef55",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "nixpkgs-unstable": "nixpkgs-unstable"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

**Comment by Lucus16** [comment]
The same applies to `mlflow server`, but not when run inside `nix-shell -p python3.pkgs.mlflow`. This turns out to be because the `nix-shell` invocation puts `mlflow` in its `PYTHONPATH`. The `mlflow` command is wrapped such that it sets the site packages correctly from within python. However, the next thing it does is run an os command in order to execute `gunicorn`, which will try to load `mlflow` again and fail. The correct context is only available within the initial python process due to its wrapper and is not exposed to the shell commands it executes.

Someone seems to have tried to fix this by creating `mlflow-server` in `pkgs/servers/mlflow-server/default.nix` but this gives me the same error. Besides, it would really be much neater if `mlflow server` and `mlflow ui` would just work.

**Comment by osbm** [comment]
well i dont get this error but instead i get this:
```

Unable to display MLflow UI - landing page (index.html) not found.

You are very likely running the MLflow server using a source installation of the Python MLflow
package.

If you are a developer making MLflow source code changes and intentionally running a source
installation of MLflow, you can view the UI by running the Javascript dev server:
https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.md#running-the-javascript-dev-server

Otherwise, uninstall MLflow via 'pip uninstall mlflow', reinstall an official MLflow release
from PyPI via 'pip install mlflow', and rerun the MLflow server.
```

Maybe we can close this one and create another issue about this. It has been more than 2 years.
