### ISSUE TITLE
esphome v2022.1.4 fails to compile esp32 firmware

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#161114]
### Describe the bug
When trying to compile firmware for my esp modules I get the following error , the version on 21.11 works. but the unstable branch does not. 

2022-02-20 16:29:32,969 DEBUG > stdout: Building in release mode
2022-02-20 16:29:32,980 DEBUG > stdout: ModuleNotFoundError: No module named 'esptool':
2022-02-20 16:29:32,981 DEBUG > stdout:   File "/nix/store/81j7pziw7wiyyaqjkwdl345slykyia37-platformio-5.2.4/lib/python3.9/site-packages/platformio/builder/main.py", line 189:
2022-02-20 16:29:32,981 DEBUG > stdout:     env.SConscript(item, exports="env")
2022-02-20 16:29:32,981 DEBUG > stdout:   File "/home/mog/.platformio/packages/tool-scons/scons-local-4.3.0/SCons/Script/SConscript.py", line 597:
2022-02-20 16:29:32,982 DEBUG > stdout:     return _SConscript(self.fs, *files, **subst_kw)
2022-02-20 16:29:32,982 DEBUG > stdout:   File "/home/mog/.platformio/packages/tool-scons/scons-local-4.3.0/SCons/Script/SConscript.py", line 285:
2022-02-20 16:29:32,982 DEBUG > stdout:     exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
2022-02-20 16:29:32,982 DEBUG > stdout:   File "/home/mog/code/dotfiles/esphome/.esphome/build/fireplace/post_build.py", line 3:
2022-02-20 16:29:32,983 DEBUG > stdout:     import esptool

### Steps To Reproduce
`esphome -v  dashboard esphome/`
then try to compile any yaml file and it will fail

### Expected behavior
Compile valid yamle files 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by Artturin** [comment]
@mweinelt @dotlambda 

https://github.com/NixOS/nixpkgs/blob/bb247aaf101b6de04692cfcad7bc54a121ba5a27/pkgs/tools/misc/esphome/default.nix#L37
https://github.com/NixOS/nixpkgs/blob/bb247aaf101b6de04692cfcad7bc54a121ba5a27/pkgs/tools/misc/esphome/default.nix#L69

**Comment by mweinelt** [comment]
> ModuleNotFoundError: No module named 'esptool':

This indicates that `ESPHOME_USE_SUBPROCESS` isn't set and esphome tries to use esptool as a library.

I just built firmware today using that version and it worked fine for me. And retested on #161120, also works.

**Comment by mogorman** [comment]
i cleared out my .platformio and my .esphome dir and still am getting failure.  let me try running the latest you mentioned now. but keep getting same error 
```
INFO Reading configuration esphome/fireplace.yaml...
INFO Generating C++ source...
INFO Compiling app...
********************************************************************************
If you like PlatformIO, please:
- follow us on Twitter to stay up-to-date on the latest project news > https://twitter.com/PlatformIO_Org
- star it on GitHub > https://github.com/platformio/platformio
- try PlatformIO IDE for embedded development > https://platformio.org/platformio-ide
********************************************************************************

Processing fireplace (board: nodemcu-32s; framework: arduino; platform: platformio/espressif32 @ 3.3.2)
--------------------------------------------------------------------------------
Platform Manager: Installing platformio/espressif32 @ 3.3.2
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Platform Manager: espressif32 @ 3.3.2 has been installed!
The platform 'platformio/espressif32 @ 3.3.2' has been successfully installed!
The rest of the packages will be installed later depending on your build environment.
Tool Manager: Installing platformio/toolchain-xtensa32 @ ~2.50200.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: toolchain-xtensa32 @ 2.50200.97 has been installed!
Tool Manager: Installing platformio/framework-arduinoespressif32 @ ~3.10006.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: framework-arduinoespressif32 @ 3.10006.210326 has been installed!
Tool Manager: Installing platformio/tool-esptoolpy @ ~1.30100.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: tool-esptoolpy @ 1.30100.210531 has been installed!
Tool Manager: Installing platformio/tool-scons @ ~4.40200.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%          
Tool Manager: tool-scons @ 4.40200.0 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/nodemcu-32s.html
PLATFORM: Espressif 32 (3.3.2) > NodeMCU-32S
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 3.10006.210326 (1.0.6) 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ off, Compatibility ~ soft
Library Manager: Installing esphome/AsyncTCP-esphome @ 1.2.2

Downloading  [------------------------------------]    0%
Downloading  [############------------------------]   33%
Downloading  [########################------------]   66%
Downloading  [####################################]  100%

Unpacking  [------------------------------------]    0%
Unpacking  [##----------------------------------]    6%
Unpacking  [####--------------------------------]   12%
Unpacking  [######------------------------------]   18%
Unpacking  [#########---------------------------]   25%
Unpacking  [###########-------------------------]   31%
Unpacking  [#############-----------------------]   37%
Unpacking  [###############---------------------]   43%
Unpacking  [##################------------------]   50%
Unpacking  [####################----------------]   56%
Unpacking  [######################--------------]   62%
Unpacking  [########################------------]   68%
Unpacking  [###########################---------]   75%
Unpacking  [#############################-------]   81%
Unpacking  [###############################-----]   87%
Unpacking  [#################################---]   93%
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome @ 1.2.2 has been installed!
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0

Downloading  [------------------------------------]    0%
Downloading  [####--------------------------------]   12%
Downloading  [#########---------------------------]   25%
Downloading  [#############-----------------------]   37%
Downloading  [##################------------------]   50%
Downloading  [######################--------------]   62%
Downloading  [###########################---------]   75%
Downloading  [###############################-----]   87%
Downloading  [####################################]  100%

Unpacking  [------------------------------------]    0%
Unpacking  [#-----------------------------------]    2%
Unpacking  [##----------------------------------]    5%
Unpacking  [###---------------------------------]    8%
Unpacking  [####--------------------------------]   11%
Unpacking  [#####-------------------------------]   14%
Unpacking  [######------------------------------]   17%
Unpacking  [#######-----------------------------]   20%
Unpacking  [########----------------------------]   22%
Unpacking  [#########---------------------------]   25%
Unpacking  [##########--------------------------]   28%
Unpacking  [###########-------------------------]   31%
Unpacking  [############------------------------]   34%
Unpacking  [#############-----------------------]   37%
Unpacking  [##############----------------------]   40%
Unpacking  [###############---------------------]   42%
Unpacking  [################--------------------]   45%
Unpacking  [#################-------------------]   48%
Unpacking  [##################------------------]   51%
Unpacking  [###################-----------------]   54%
Unpacking  [####################----------------]   57%
Unpacking  [#####################---------------]   60%
Unpacking  [######################--------------]   62%
Unpacking  [#######################-------------]   65%
Unpacking  [########################------------]   68%
Unpacking  [#########################-----------]   71%
Unpacking  [##########################----------]   74%
Unpacking  [###########################---------]   77%
Unpacking  [############################--------]   80%
Unpacking  [#############################-------]   82%
Unpacking  [##############################------]   85%
Unpacking  [###############################-----]   88%
Unpacking  [################################----]   91%
Unpacking  [#################################---]   94%
Unpacking  [##################################--]   97%
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer-esphome @ 2.1.0 has been installed!
Library Manager: Installing dependencies...
Library Manager: Installing ottowinter/ESPAsyncTCP-esphome

Downloading  [------------------------------------]    0%
Downloading  [#######-----------------------------]   20%
Downloading  [##############----------------------]   40%
Downloading  [#####################---------------]   60%
Downloading  [############################--------]   80%
Downloading  [####################################]  100%

Unpacking  [------------------------------------]    0%
Unpacking  [#-----------------------------------]    3%
Unpacking  [##----------------------------------]    6%
Unpacking  [###---------------------------------]    9%
Unpacking  [####--------------------------------]   12%
Unpacking  [#####-------------------------------]   15%
Unpacking  [######------------------------------]   18%
Unpacking  [#######-----------------------------]   21%
Unpacking  [#########---------------------------]   25%
Unpacking  [##########--------------------------]   28%
Unpacking  [###########-------------------------]   31%
Unpacking  [############------------------------]   34%
Unpacking  [#############-----------------------]   37%
Unpacking  [##############----------------------]   40%
Unpacking  [###############---------------------]   43%
Unpacking  [################--------------------]   46%
Unpacking  [##################------------------]   50%
Unpacking  [###################-----------------]   53%
Unpacking  [####################----------------]   56%
Unpacking  [#####################---------------]   59%
Unpacking  [######################--------------]   62%
Unpacking  [#######################-------------]   65%
Unpacking  [########################------------]   68%
Unpacking  [#########################-----------]   71%
Unpacking  [###########################---------]   75%
Unpacking  [############################--------]   78%
Unpacking  [#############################-------]   81%
Unpacking  [##############################------]   84%
Unpacking  [###############################-----]   87%
Unpacking  [################################----]   90%
Unpacking  [#################################---]   93%
Unpacking  [##################################--]   96%
Unpacking  [####################################]  100%
Library Manager: ESPAsyncTCP-esphome @ 1.2.3 has been installed!
Library Manager: AsyncTCP-esphome @ 1.2.2 is already installed
Library Manager: Installing Hash
Library Manager: Warning! Could not install dependency {'name': 'Hash', 'platforms': ['espressif8266']} for package 'ESPAsyncWebServer-esphome'
Library Manager: Installing ESP8266WiFi
Library Manager: Warning! Could not install dependency {'name': 'ESP8266WiFi', 'platforms': ['espressif8266']} for package 'ESPAsyncWebServer-esphome'
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5

Downloading  [------------------------------------]    0%
Downloading  [###---------------------------------]    9%
Downloading  [######------------------------------]   18%
Downloading  [#########---------------------------]   27%
Downloading  [#############-----------------------]   36%
Downloading  [################--------------------]   45%
Downloading  [###################-----------------]   54%
Downloading  [######################--------------]   63%
Downloading  [##########################----------]   72%
Downloading  [#############################-------]   81%
Downloading  [################################----]   90%
Downloading  [####################################]  100%

Unpacking  [------------------------------------]    0%
Unpacking  [------------------------------------]    1%
Unpacking  [------------------------------------]    2%
Unpacking  [#-----------------------------------]    2%
Unpacking  [#-----------------------------------]    3%
Unpacking  [#-----------------------------------]    4%
Unpacking  [#-----------------------------------]    5%
Unpacking  [##----------------------------------]    5%
Unpacking  [##----------------------------------]    6%
Unpacking  [##----------------------------------]    7%
Unpacking  [##----------------------------------]    8%
Unpacking  [###---------------------------------]    8%
Unpacking  [###---------------------------------]    9%
Unpacking  [###---------------------------------]   10%
Unpacking  [####--------------------------------]   11%
Unpacking  [####--------------------------------]   12%
Unpacking  [####--------------------------------]   13%
Unpacking  [#####-------------------------------]   14%
Unpacking  [#####-------------------------------]   15%
Unpacking  [#####-------------------------------]   16%
Unpacking  [######------------------------------]   16%
Unpacking  [######------------------------------]   17%
Unpacking  [######------------------------------]   18%
Unpacking  [######------------------------------]   19%
Unpacking  [#######-----------------------------]   19%
Unpacking  [#######-----------------------------]   20%
Unpacking  [#######-----------------------------]   21%
Unpacking  [########----------------------------]   22%
Unpacking  [########----------------------------]   23%
Unpacking  [########----------------------------]   24%
Unpacking  [#########---------------------------]   25%
Unpacking  [#########---------------------------]   26%
Unpacking  [#########---------------------------]   27%
Unpacking  [##########--------------------------]   28%
Unpacking  [##########--------------------------]   29%
Unpacking  [##########--------------------------]   30%
Unpacking  [###########-------------------------]   30%
Unpacking  [###########-------------------------]   31%
Unpacking  [###########-------------------------]   32%
Unpacking  [############------------------------]   33%
Unpacking  [############------------------------]   34%
Unpacking  [############------------------------]   35%
Unpacking  [#############-----------------------]   36%
Unpacking  [#############-----------------------]   37%
Unpacking  [#############-----------------------]   38%
Unpacking  [##############----------------------]   39%
Unpacking  [##############----------------------]   40%
Unpacking  [##############----------------------]   41%
Unpacking  [###############---------------------]   42%
Unpacking  [###############---------------------]   43%
Unpacking  [################--------------------]   44%
Unpacking  [################--------------------]   45%
Unpacking  [################--------------------]   46%
Unpacking  [#################-------------------]   47%
Unpacking  [#################-------------------]   48%
Unpacking  [#################-------------------]   49%
Unpacking  [##################------------------]   50%
Unpacking  [##################------------------]   51%
Unpacking  [##################------------------]   52%
Unpacking  [###################-----------------]   53%
Unpacking  [###################-----------------]   54%
Unpacking  [####################----------------]   55%
Unpacking  [####################----------------]   56%
Unpacking  [####################----------------]   57%
Unpacking  [#####################---------------]   58%
Unpacking  [#####################---------------]   59%
Unpacking  [#####################---------------]   60%
Unpacking  [######################--------------]   61%
Unpacking  [######################--------------]   62%
Unpacking  [######################--------------]   63%
Unpacking  [#######################-------------]   64%
Unpacking  [#######################-------------]   65%
Unpacking  [#######################-------------]   66%
Unpacking  [########################------------]   66%
Unpacking  [########################------------]   67%
Unpacking  [########################------------]   68%
Unpacking  [########################------------]   69%
Unpacking  [#########################-----------]   69%
Unpacking  [#########################-----------]   70%
Unpacking  [#########################-----------]   71%
Unpacking  [##########################----------]   72%
Unpacking  [##########################----------]   73%
Unpacking  [##########################----------]   74%
Unpacking  [###########################---------]   75%
Unpacking  [###########################---------]   76%
Unpacking  [###########################---------]   77%
Unpacking  [############################--------]   77%
Unpacking  [############################--------]   78%
Unpacking  [############################--------]   79%
Unpacking  [############################--------]   80%
Unpacking  [#############################-------]   80%
Unpacking  [#############################-------]   81%
Unpacking  [#############################-------]   82%
Unpacking  [#############################-------]   83%
Unpacking  [##############################------]   83%
Unpacking  [##############################------]   84%
Unpacking  [##############################------]   85%
Unpacking  [###############################-----]   86%
Unpacking  [###############################-----]   87%
Unpacking  [###############################-----]   88%
Unpacking  [################################----]   88%
Unpacking  [################################----]   89%
Unpacking  [################################----]   90%
Unpacking  [################################----]   91%
Unpacking  [#################################---]   91%
Unpacking  [#################################---]   92%
Unpacking  [#################################---]   93%
Unpacking  [#################################---]   94%
Unpacking  [##################################--]   94%
Unpacking  [##################################--]   95%
Unpacking  [##################################--]   96%
Unpacking  [##################################--]   97%
Unpacking  [###################################-]   97%
Unpacking  [###################################-]   98%
Unpacking  [###################################-]   99%
Unpacking  [####################################]  100%
Library Manager: ArduinoJson @ 6.18.5 has been installed!
Found 31 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <AsyncTCP-esphome> 1.2.2
|-- <WiFi> 1.0
|-- <FS> 1.0
|-- <Update> 1.0
|-- <ESPAsyncWebServer-esphome> 2.1.0
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <DNSServer> 1.1.0
|-- <ESPmDNS> 1.0
|-- <ArduinoJson> 6.18.5
Building in release mode
ModuleNotFoundError: No module named 'esptool':
  File "/nix/store/w4lb9mal26spv533knlmcbj5spwg3s92-platformio-5.2.3/lib/python3.9/site-packages/platformio/builder/main.py", line 188:
    env.SConscript(item, exports="env")
  File "/home/mog/.platformio/packages/tool-scons/scons-local-4.2.0/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/mog/.platformio/packages/tool-scons/scons-local-4.2.0/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/mog/code/dotfiles/esphome/.esphome/build/fireplace/post_build.py", line 3:
    import esptool
========================= [FAILED] Took 47.26 seconds =========================
```

**Comment by mweinelt** [comment]
>   File "/home/mog/code/dotfiles/esphome/.esphome/build/fireplace/post_build.py", line 3:

The `post_build.py` does not import esptool for me and looks like this:

```python
import shutil

# pylint: disable=E0602
Import("env")  # noqa


def esp8266_copy_factory_bin(source, target, env):
    firmware_name = env.subst("$BUILD_DIR/${PROGNAME}.bin")
    new_file_name = env.subst("$BUILD_DIR/${PROGNAME}-factory.bin")

    shutil.copyfile(firmware_name, new_file_name)


# pylint: disable=E0602
env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", esp8266_copy_factory_bin)  # noqa
```

**Comment by mweinelt** [comment]
That file is dervied from https://github.com/esphome/esphome/blob/2022.1.4/esphome/components/esp8266/post_build.py.script, which looks the same for 2022.1.4. No esptool import in there.

**Comment by mogorman** [comment]
mine says
```python
# Source https://github.com/letscontrolit/ESPEasy/pull/3845#issuecomment-1005864664

import esptool
from SCons.Script import ARGUMENTS

# pylint: disable=E0602
Import("env")  # noqa

```
i have

**Comment by mogorman** [comment]
im using an esp32 which is generating from here i think https://github.com/esphome/esphome/blob/2022.1.4/esphome/components/esp32/post_build.py.script

**Comment by mogorman** [comment]
is there a way i could add esptool to the python env of the package easily? I tried adding it in a few spots but it didnt seem to resolve my issue.

**Comment by mweinelt** [comment]
Can you try the following patch against the esphome package?

```
diff --git a/esphome/components/esp32/post_build.py.script b/esphome/components/esp32/post_build.py.script
index 2bb1a6c3..44fa16f1 100644
--- a/esphome/components/esp32/post_build.py.script
+++ b/esphome/components/esp32/post_build.py.script
@@ -1,6 +1,9 @@
 # Source https://github.com/letscontrolit/ESPEasy/pull/3845#issuecomment-1005864664
 
-import esptool
+if os.environ.get("ESPHOME_USE_SUBPROCESS") is None:
+    import esptool
+else:
+    import subprocess
 from SCons.Script import ARGUMENTS
 
 # pylint: disable=E0602
@@ -42,8 +45,11 @@ def esp32_create_combined_bin(source, target, env):
         print()
         print(f"Using esptool.py arguments: {' '.join(cmd)}")
         print()
-    esptool.main(cmd)
 
+    if os.environ.get("ESPHOME_USE_SUBPROCESS") is None:
+        esptool.main(cmd)
+    else:
+        subprocess.run(["esphome"].extend(cmd))
 
 # pylint: disable=E0602
 env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", esp32_create_combined_bin)  # noqa
```

**Comment by mogorman** [comment]
that got me further. although I had to make one more small change to the patch.
```diff
diff --git a/esphome/components/esp32/post_build.py.script b/esphome/components/esp32/post_build.py.script
index 2bb1a6c3..44fa16f1 100644
--- a/esphome/components/esp32/post_build.py.script
+++ b/esphome/components/esp32/post_build.py.script
@@ -1,6 +1,10 @@
 # Source https://github.com/letscontrolit/ESPEasy/pull/3845#issuecomment-1005864664
 
-import esptool
+import os
+if os.environ.get("ESPHOME_USE_SUBPROCESS") is None:
+    import esptool
+else:
+    import subprocess
 from SCons.Script import ARGUMENTS
 
 # pylint: disable=E0602
@@ -42,8 +45,11 @@ def esp32_create_combined_bin(source, target, env):
         print()
         print(f"Using esptool.py arguments: {' '.join(cmd)}")
         print()
-    esptool.main(cmd)
 
+    if os.environ.get("ESPHOME_USE_SUBPROCESS") is None:
+        esptool.main(cmd)
+    else:
+        subprocess.run(["esptool"].extend(cmd))
 
 # pylint: disable=E0602
 env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", esp32_create_combined_bin)  # noqa
```

Merged 1 ELF section
esp32_create_combined_bin([".pioenvs/fireplace/firmware.bin"], [".pioenvs/fireplace/firmware.elf"])
*** [.pioenvs/fireplace/firmware.bin] TypeError : 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/mog/.platformio/packages/tool-scons/scons-local-4.2.0/SCons/Action.py", line 1279, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/home/mog/code/dotfiles/esphome/.esphome/build/fireplace/post_build.py", line 53, in esp32_create_combined_bin
    subprocess.run(["esptool"].extend(cmd))
  File "/nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/cgxc3jz7idrb1wnb2lard9rvcx6aw2si-python3-3.9.6/lib/python3.9/subprocess.py", line 1680, in _execute_child
    args = list(args)
TypeError: 'NoneType' object is not iterable
========================= [FAILED] Took 91.44 seconds =========================


My current error is now

**Comment by mogorman** [comment]
the `esphome/.esphome/build/fireplace/.pioenvs/fireplace/firmware.bin` and `esphome/.esphome/build/fireplace/.pioenvs/fireplace/firmware.elf` do seem to exist.

**Comment by mweinelt** [comment]
Because `["esptool"].extend(cmd)` doesn't return the complete list... New patch:

```patch
diff --git a/esphome/components/esp32/post_build.py.script b/esphome/components/esp32/post_build.py.script
index 2bb1a6c3..55a61937 100644
--- a/esphome/components/esp32/post_build.py.script
+++ b/esphome/components/esp32/post_build.py.script
@@ -1,6 +1,9 @@
 # Source https://github.com/letscontrolit/ESPEasy/pull/3845#issuecomment-1005864664
 
-import esptool
+if os.environ.get("ESPHOME_USE_SUBPROCESS") is None:
+    import esptool
+else:
+    import subprocess
 from SCons.Script import ARGUMENTS
 
 # pylint: disable=E0602
@@ -42,8 +45,11 @@ def esp32_create_combined_bin(source, target, env):
         print()
         print(f"Using esptool.py arguments: {' '.join(cmd)}")
         print()
-    esptool.main(cmd)
 
+    if os.environ.get("ESPHOME_USE_SUBPROCESS") is None:
+        esptool.main(cmd)
+    else:
+        subprocess.run(["esptool", *cmd])
 
 # pylint: disable=E0602
 env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", esp32_create_combined_bin)  # noqa
```

**Comment by mogorman** [comment]
I think you accidentally posted same patch from before

**Comment by mweinelt** [comment]
No, see the changed line here:

```
+        subprocess.run(["esptool", *cmd])
```

**Comment by mogorman** [comment]
my bad thank you let me try that.

**Comment by mogorman** [comment]
```
Retrieving maximum program size .pioenvs/fireplace/firmware.elf
Checking size .pioenvs/fireplace/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  12.8% (used 41788 bytes from 327680 bytes)
Flash: [=====     ]  51.2% (used 938746 bytes from 1835008 bytes)
Building .pioenvs/fireplace/firmware.bin
esptool.py v3.1
Merged 1 ELF section
esp32_create_combined_bin([".pioenvs/fireplace/firmware.bin"], [".pioenvs/fireplace/firmware.elf"])
*** [.pioenvs/fireplace/firmware.bin] esptool: No such file or directory
========================== [FAILED] Took 7.91 seconds ==========================
```
files exist. My guess would be that the dir its being run from somehow isnt the `esphome/.esphome/build/fireplace/` dir

**Comment by mweinelt** [comment]
I would expect it to exist in the PATH because you are calling it through the wrapped esphome executable.

**Comment by mogorman** [comment]
oh i think it needs to be esptool.py... trying that now

**Comment by mweinelt** [comment]
Oh yeah, that's it. The `esptool`package has no executable named just `esptool`.

**Comment by mogorman** [comment]
yup that did it . working now
```diff
diff --git a/esphome/components/esp32/post_build.py.script b/esphome/components/esp32/post_build.py.script
index 2bb1a6c3..55a61937 100644
--- a/esphome/components/esp32/post_build.py.script
+++ b/esphome/components/esp32/post_build.py.script
@@ -1,6 +1,10 @@
 # Source https://github.com/letscontrolit/ESPEasy/pull/3845#issuecomment-1005864664
 
-import esptool
+import os
+if os.environ.get("ESPHOME_USE_SUBPROCESS") is None:
+    import esptool
+else:
+    import subprocess
 from SCons.Script import ARGUMENTS
 
 # pylint: disable=E0602
@@ -42,8 +45,11 @@ def esp32_create_combined_bin(source, target, env):
         print()
         print(f"Using esptool.py arguments: {' '.join(cmd)}")
         print()
-    esptool.main(cmd)
 
+    if os.environ.get("ESPHOME_USE_SUBPROCESS") is None:
+        esptool.main(cmd)
+    else:
+        subprocess.run(["esptool.py", *cmd])
 
 # pylint: disable=E0602
 env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", esp32_create_combined_bin)  # noqa
```

**Comment by mweinelt** [comment]
Oh yeah, I missed that `os` import in the beginning! Glad it's working.
