### ISSUE TITLE
How can I use “guard”?

### ISSUE THREAD

**Issue by stapelberg** [NixOS/nixpkgs#16149]
## Issue description

I want to work on the RobustIRC documentation. That documentation includes a Guardfile, see https://github.com/robustirc/robustirc.github.io/blob/master/docs/Guardfile. guard is a tool to (in this case) rebuild the documentation whenever the input files change.

Since guard isn’t available in nixpkgs at the time of writing, I took a stab at packaging it, see https://gist.github.com/stapelberg/c1283482b39fcd2e92a5b3b2b9c25806

Then, I changed into my robustirc.github.io checkout and ran `nix-shell -I nixpkgs=~/nixpkgs -p asciidoctor guard-shell`. In the resulting environment, running `guard` results in the following error:

```
$ guard
19:51:02 - ERROR - Invalid Guardfile, original error is: 
> [#] 
> [#] cannot load such file -- asciidoctor, 
> [#] backtrace: 
> [#]   (dsl)> ./Guardfile:4:in `require'
> [#]   (dsl)> ./Guardfile:4:in `evaluate'
> [#]   (dsl)> /nix/store/vcg1vb4mgy2p8d53c7bsbbj8ivnf38jr-ruby2.3.1-p0-guard-2.14.0/lib/ruby/gems/2.3.1/gems/guard-2.14.0/lib/guard/dsl.rb:377:in `instance_eval'
> [#]   (dsl)> /nix/store/vcg1vb4mgy2p8d53c7bsbbj8ivnf38jr-ruby2.3.1-p0-guard-2.14.0/lib/ruby/gems/2.3.1/gems/guard-2.14.0/lib/guard/dsl.rb:377:in `evaluate'
> [#]   (dsl)> /nix/store/vcg1vb4mgy2p8d53c7bsbbj8ivnf38jr-ruby2.3.1-p0-guard-2.14.0/lib/ruby/gems/2.3.1/gems/guard-2.14.0/lib/guard/guardfile/evaluator.rb:89:in `evaluate'
> [#]   (dsl)> /nix/store/vcg1vb4mgy2p8d53c7bsbbj8ivnf38jr-ruby2.3.1-p0-guard-2.14.0/lib/ruby/gems/2.3.1/gems/guard-2.14.0/lib/guard.rb:134:in `_evaluate'
> [#]   (dsl)> /nix/store/vcg1vb4mgy2p8d53c7bsbbj8ivnf38jr-ruby2.3.1-p0-guard-2.14.0/lib/ruby/gems/2.3.1/gems/guard-2.14.0/lib/guard.rb:49:in `setup'
> [#]   (dsl)> /nix/store/vcg1vb4mgy2p8d53c7bsbbj8ivnf38jr-ruby2.3.1-p0-guard-2.14.0/lib/ruby/gems/2.3.1/gems/guard-2.14.0/lib/guard/commander.rb:32:in `start'
> [#]   (dsl)> /nix/store/vcg1vb4mgy2p8d53c7bsbbj8ivnf38jr-ruby2.3.1-p0-guard-2.14.0/lib/ruby/gems/2.3.1/gems/guard-2.14.0/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#]   (dsl)> /nix/store/vcg1vb4mgy2p8d53c7bsbbj8ivnf38jr-ruby2.3.1-p0-guard-2.14.0/lib/ruby/gems/2.3.1/gems/guard-2.14.0/lib/guard/cli.rb:122:in `start'
> [#]   (dsl)> /nix/store/kbyckjmbb675kmh65b9yxrd8cyrc83s8-ruby2.3.1-p0-thor-0.19.1/lib/ruby/gems/2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#]   (dsl)> /nix/store/kbyckjmbb675kmh65b9yxrd8cyrc83s8-ruby2.3.1-p0-thor-0.19.1/lib/ruby/gems/2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#]   (dsl)> /nix/store/kbyckjmbb675kmh65b9yxrd8cyrc83s8-ruby2.3.1-p0-thor-0.19.1/lib/ruby/gems/2.3.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#]   (dsl)> /nix/store/kbyckjmbb675kmh65b9yxrd8cyrc83s8-ruby2.3.1-p0-thor-0.19.1/lib/ruby/gems/2.3.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#]   (dsl)> /nix/store/vcg1vb4mgy2p8d53c7bsbbj8ivnf38jr-ruby2.3.1-p0-guard-2.14.0/lib/ruby/gems/2.3.1/gems/guard-2.14.0/lib/guard/aruba_adapter.rb:32:in `execute'
> [#]   (dsl)> /nix/store/vcg1vb4mgy2p8d53c7bsbbj8ivnf38jr-ruby2.3.1-p0-guard-2.14.0/lib/ruby/gems/2.3.1/gems/guard-2.14.0/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#]   (dsl)> /nix/store/vcg1vb4mgy2p8d53c7bsbbj8ivnf38jr-ruby2.3.1-p0-guard-2.14.0/lib/ruby/gems/2.3.1/gems/guard-2.14.0/bin/_guard-core:11:in `<main>'
```

I think this is because the search path of `guard` only contains `guard`’s dependencies, i.e. not `asciidoctor`.

Adding `asciidoctor` as a `guard` dependency seems like the wrong solution — that way, whenever some project uses a `Guardfile` which uses a new dependency, we’d need to include it in `guard`.

So, what is the correct solution for using `guard` in this scenario?
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
$ nixos-version
16.03.909.f199be0 (Emu)
```
- Nix version: (run `nix-env --version`)

```
$ nix-env --version
nix-env (Nix) 1.11.2
```
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.03.909.f199be0"
$ nix-instantiate -I nixpkgs=~/nixpkgs --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09.git.95c7dd7M"
```

**Comment by Profpatsch** [comment]
triage: I suspect this issue is not relevant anymore? Sorry that nobody replied.

**Comment by stapelberg** [comment]
Sorry, I can’t confirm; haven’t been using NixOS for years at this point. Feel free to close until someone else runs into this.

**Comment by Profpatsch** [comment]
Thanks
