### ISSUE TITLE
element-desktop replaces it's .config folder (if symlink?) with a JSON file

### ISSUE THREAD

**Issue by zseri** [NixOS/nixpkgs#162014]
### Describe the bug
After upgrading from 201ca9d2480f1b71a51e7a2fa17a8c8c69172eca to 5dd2075c41d132b115287209818b7f266b41fd4,
`element-desktop` only starts once after the upgrade, then refuses to start, because the first invocation replaces my `~/.config/Element` folder symlink with a JSON file.
The JSON file contents look like this:
```json
{"expect_ct":[],"sts":[{"expiry":1677434398.125693,"host":"[redacted]","mode":"force-https","sts_include_subdomains":true,"sts_observed":1645898398.125699}],"version":2}
```

### Steps To Reproduce
Steps to reproduce the behavior: not known

### Expected behavior
Element shouldn't replace

### Additional context
The entry `.config/Element` on my system is normally a symlink to another directory, established via the home-manager NixOS module.
Error message after second start:
```
Keytar isn't installed; secure key storage is disabled.
/home/zseri/.config/Element exists: no
/home/zseri/.config/Riot exists: no
App threw an error during load
Error: ENOTDIR: not a directory, open '/home/zseri/.config/Element/electron-config.json'
    at Object.openSync (node:fs:582:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.readFileSync (node:fs:450:35)
    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9148)
    at ElectronStore.get store [as store] (/nix/store/1qqdg34a67wj7z6cmc383xcjbgbw5pma-element-desktop-1.10.4/share/element/electron/node_modules/conf/dist/source/index.js:262:29)
    at new Conf (/nix/store/1qqdg34a67wj7z6cmc383xcjbgbw5pma-element-desktop-1.10.4/share/element/electron/node_modules/conf/dist/source/index.js:124:32)
    at new ElectronStore (/nix/store/1qqdg34a67wj7z6cmc383xcjbgbw5pma-element-desktop-1.10.4/share/element/electron/node_modules/electron-store/index.js:28:3)
    at Object.<anonymous> (/nix/store/1qqdg34a67wj7z6cmc383xcjbgbw5pma-element-desktop-1.10.4/share/element/electron/lib/electron-main.js:282:15)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOTDIR: not a directory, open '/home/zseri/.config/Element/electron-config.json'
    at Object.openSync (node:fs:582:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.readFileSync (node:fs:450:35)
    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9148)
    at ElectronStore.get store [as store] (/nix/store/1qqdg34a67wj7z6cmc383xcjbgbw5pma-element-desktop-1.10.4/share/element/electron/node_modules/conf/dist/source/index.js:262:29)
    at new Conf (/nix/store/1qqdg34a67wj7z6cmc383xcjbgbw5pma-element-desktop-1.10.4/share/element/electron/node_modules/conf/dist/source/index.js:124:32)
    at new ElectronStore (/nix/store/1qqdg34a67wj7z6cmc383xcjbgbw5pma-element-desktop-1.10.4/share/element/electron/node_modules/electron-store/index.js:28:3)
    at Object.<anonymous> (/nix/store/1qqdg34a67wj7z6cmc383xcjbgbw5pma-element-desktop-1.10.4/share/element/electron/lib/electron-main.js:282:15)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
[59406:0226/192745.693739:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[59406:0226/192745.693816:ERROR:select_file_dialog_impl_portal.cc(243)] Failed to read portal version property
[59441:0226/192745.806692:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

### Notify maintainers
@ma27
@fadenb
@mguentner
@ekleog
@ralith
@dandellion
@sumnerevans

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.24, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220218_9bc03ad`
 - nixpkgs: `/etc/nix-flake-channels/nixpkgs` -> `/nix/store/1g89fancpvim7ylfz3xcikjj213d5v41-source`
```

**Comment by zseri** [comment]
hm, maybe https://github.com/vector-im/element-web/issues/21118
