### ISSUE TITLE
pythonPackages.cerberus missing run-time dependency

### ISSUE THREAD

**Issue by drperceptron** [NixOS/nixpkgs#162280]
### Describe the bug
`ImportError` upon importing Cerberus.

### Steps To Reproduce
```
# from a checked out nixpkgs:master
$ git rev-parse HEAD
15e2aa70d2229ae090569f85860e78c9f117bb5b
$ nix-shell -I nixpkgs=. -p pkgs.python38Packages.cerberus
...
$ python -c "import cerberus"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/j5kbs1ki96mz8dpd97y6iahg817v0r82-python3.8-Cerberus-1.3.4/lib/python3.8/site-packages/cerberus/__init__.py", line 13, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'

$ nix-shell -I nixpkgs=. -p pkgs.python39Packages.cerberus
...
$ python -c "import cerberus"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/yppd445d20i2wxwsczb4vq6kiywbd0wy-python3.9-Cerberus-1.3.4/lib/python3.9/site-packages/cerberus/__init__.py", line 13, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'

$ nix-shell -I nixpkgs=. -p pkgs.python2Packages.cerberus
...
$ python -c "import cerberus"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/bdm4py3dz4f8fl29pi1h94hiz3i7x580-python2.7-Cerberus-1.3.4/lib/python2.7/site-packages/cerberus/__init__.py", line 13, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ImportError: No module named pkg_resources
```

Because `importlib.resources` was introduced in Python 3.7 I suspected this might only affect some Python versions but from the above example it is clear this is more widespread.

### Expected behavior
`python -c "import cerberus"` runs without error.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.101, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(qwerty): `""`
 - channels(root): `"nixos-21.11.336177.1622abf0e78"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by drperceptron** [comment]
nixos-21.11 is affected
