### ISSUE TITLE
Python `magic` module broken on Darwin

### ISSUE THREAD

**Issue by jml** [NixOS/nixpkgs#16361]
## Issue description

The Python `magic` module is broken on Darwin. It fails to find the C libraries on which it depends.
### Steps to reproduce

```
jml@mercy:~ (0)
$ nix-shell
error: getting status of ‘/Users/jml/default.nix’: No such file or directory
jml@mercy:~ (0)
$ nix-shell --help
jml@mercy:~ (0)
$ nix-shell -p pythonPackages.magic
these derivations will be built:
  /nix/store/kn7q4siix5jwqv56cb350y685qdiriq3-python2.7-file-5.25.drv
these paths will be fetched (0.71 MiB download, 0.71 MiB unpacked):
  /nix/store/9bqncnlpy90xq4fgirhfyi0gr0sfhd90-file-5.25.tar.gz
fetching path ‘/nix/store/9bqncnlpy90xq4fgirhfyi0gr0sfhd90-file-5.25.tar.gz’...

*** Downloading ‘https://cache.nixos.org/nar/0v9s955xlmp63k3hhfn6cb3gwwh722dfj8g1crwbif6cskskw8sp.nar.xz’ to ‘/nix/store/9bqncnlpy90xq4fgirhfyi0gr0sfhd90-file-5.25.tar.gz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  722k  100  722k    0     0   440k      0  0:00:01  0:00:01 --:--:--  441k

building path(s) ‘/nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25’
unpacking sources
unpacking source archive /nix/store/9bqncnlpy90xq4fgirhfyi0gr0sfhd90-file-5.25.tar.gz
source root is file-5.25
setting SOURCE_DATE_EPOCH to timestamp 1442411538 of file file-5.25/tests/Makefile.in
patching sources
configuring
building
running bdist_wheel
running build
running build_py
creating build
creating build/lib
copying magic.py -> build/lib
installing to build/bdist.macosx-10.7-x86_64/wheel
running install
running install_lib
creating build/bdist.macosx-10.7-x86_64
creating build/bdist.macosx-10.7-x86_64/wheel
copying build/lib/magic.py -> build/bdist.macosx-10.7-x86_64/wheel
running install_egg_info
running egg_info
creating Magic_file_extensions.egg-info
writing Magic_file_extensions.egg-info/PKG-INFO
writing top-level names to Magic_file_extensions.egg-info/top_level.txt
writing dependency_links to Magic_file_extensions.egg-info/dependency_links.txt
writing manifest file 'Magic_file_extensions.egg-info/SOURCES.txt'
reading manifest file 'Magic_file_extensions.egg-info/SOURCES.txt'
writing manifest file 'Magic_file_extensions.egg-info/SOURCES.txt'
Copying Magic_file_extensions.egg-info to build/bdist.macosx-10.7-x86_64/wheel/Magic_file_extensions-0.2-py2.7.egg-info
running install_scripts
creating build/bdist.macosx-10.7-x86_64/wheel/Magic_file_extensions-0.2.dist-info/WHEEL
installing
/private/var/folders/6q/jpykk8bn6dq68ynzm6c1r7c40000gn/T/nix-build-python2.7-file-5.25.drv-0/file-5.25/python/dist /private/var/folders/6q/jpykk8bn6dq68ynzm6c1r7c40000gn/T/nix-build-python2.7-file-5.25.drv-0/file-5.25/python
Ignoring indexes: https://pypi.python.org/simple
Processing ./Magic_file_extensions-0.2-py2-none-any.whl
Installing collected packages: Magic-file-extensions
Successfully installed Magic-file-extensions-0.2
/private/var/folders/6q/jpykk8bn6dq68ynzm6c1r7c40000gn/T/nix-build-python2.7-file-5.25.drv-0/file-5.25/python
post-installation fixup
stripping (with flags -S) in /nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib
strip: can't process non-object and non-archive file: /nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib/python2.7/site-packages/magic.py
strip: can't process non-object and non-archive file: /nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib/python2.7/site-packages/magic.pyc
strip: can't process non-object and non-archive file: /nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib/python2.7/site-packages/Magic_file_extensions-0.2.dist-info/DESCRIPTION.rst
strip: can't process non-object and non-archive file: /nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib/python2.7/site-packages/Magic_file_extensions-0.2.dist-info/INSTALLER
strip: can't process non-object and non-archive file: /nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib/python2.7/site-packages/Magic_file_extensions-0.2.dist-info/METADATA
strip: can't process non-object and non-archive file: /nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib/python2.7/site-packages/Magic_file_extensions-0.2.dist-info/metadata.json
strip: can't process non-object and non-archive file: /nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib/python2.7/site-packages/Magic_file_extensions-0.2.dist-info/RECORD
strip: can't process non-object and non-archive file: /nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib/python2.7/site-packages/Magic_file_extensions-0.2.dist-info/top_level.txt
strip: can't process non-object and non-archive file: /nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib/python2.7/site-packages/Magic_file_extensions-0.2.dist-info/WHEEL
patching script interpreter paths in /nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25
running install tests
running test
running egg_info
writing Magic_file_extensions.egg-info/PKG-INFO
writing top-level names to Magic_file_extensions.egg-info/top_level.txt
writing dependency_links to Magic_file_extensions.egg-info/dependency_links.txt
reading manifest file 'Magic_file_extensions.egg-info/SOURCES.txt'
writing manifest file 'Magic_file_extensions.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

[nix-shell:~]$ python
Python 2.7.11 (default, May  3 2016, 22:58:37)
[GCC 4.2.1 Compatible Clang 3.7.1 (tags/RELEASE_371/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import magic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib/python2.7/site-packages/magic.py", line 20, in <module>
    _libraries['magic'] = _init()
  File "/nix/store/r4z7sh73ky0rynwvdm561acymir7ggbh-python2.7-file-5.25/lib/python2.7/site-packages/magic.py", line 17, in _init
    return ctypes.cdll.LoadLibrary('/nix/store/zya4z254w26sss2wdajbagjb6aw7g364-file-5.25/lib/libmagic.so')
  File "/nix/store/d3bfgbmvfghl0ii24rz7qawavzssi0cj-python-2.7.11/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/nix/store/d3bfgbmvfghl0ii24rz7qawavzssi0cj-python-2.7.11/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/nix/store/zya4z254w26sss2wdajbagjb6aw7g364-file-5.25/lib/libmagic.so, 6): image not found
>>>
```
## Technical details
- System: Darwin, OS X 10.11.5
- Nix version: 1.11.2
- Nixpkgs version: "16.09pre83147.df89584"

**Comment by jml** [comment]
Maybe related to #13612 -- I came across this problem trying to run `s3cmd`.

**Comment by matthewbauer** [comment]
I think on Darwin it should be libmagic.dylib. Can you verify that /nix/store/zya4z254w26sss2wdajbagjb6aw7g364-file-5.25/lib/ has something in it?

**Comment by jml** [comment]
```
$ ls /nix/store/zya4z254w26sss2wdajbagjb6aw7g364-file-5.25/lib/
libmagic.1.dylib  libmagic.dylib  libmagic.la
```

**Comment by regnat** [comment]
(triage) @jml, is the issue still active ?

**Comment by jml** [comment]
I don't use Nix any more.

**Comment by pSub** [comment]
Closing. Please reopen if this issue is still relevant.

**Comment by matthewbauer** [comment]
It's still relevant
