### ISSUE TITLE
sfxr and sfxr-qt segfault when the gui is run

### ISSUE THREAD

**Issue by fgaz** [NixOS/nixpkgs#165010]
### Describe the bug

sfxr and sfxr-qt segfault when the gui is run.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.105, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.336515.0f85665118d"`
 - channels(fgaz): `"nixpkgs-22.05pre357729.22dc22f8ced"`
 - nixpkgs: `/home/fgaz/.nix-defexpr/channels/nixpkgs`
```

**Comment by fgaz** [comment]
Nevermind, it looks like they work in a nixos test... it must have to do with my system

**Comment by ramirez7** [comment]
@fgaz FYI I ran into this recently after bumping `sfxr-qt` as well. Deleting `~/.cache/sfxr-qt` fixed the issue. Must be some sort of Qt caching? I'm not too familiar with Qt.

**Comment by fgaz** [comment]
Can confirm, deleting `~/.cache/sfxr-qt` fixed it for me too

**Comment by ramirez7** [comment]
`sfxr` still segfaults for me. I tried to debug it with `gdb` with [`enableDebugging`](http://rski.github.io/2021/09/05/nix-debugging.html), but when I ran it that way, it just hangs:

```
$ gdb --args bash ./sfxr-debuggable/bin/sfxr 
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bash...
(No debugging symbols found in bash)
(gdb) run
Starting program: /nix/store/kk9njdamrzm05h0wywpxl718rvqy3jwq-bash-interactive-5.1-p8/bin/bash ./sfxr-debuggable/bin/sfxr
process 399813 is executing new program: /nix/store/3ajac2iikrqsbfqwf1hlshqvim991ali-sfxr-1.2.1/bin/.sfxr-wrapped
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/rir9pf0kz1mb84x5bd3yr0fx415yy423-glibc-2.33-123/lib/libthread_db.so.1".
[New Thread 0x7fffe1c43640 (LWP 399817)]
[Thread 0x7fffe1c43640 (LWP 399817) exited]
[New Thread 0x7fffe1c43640 (LWP 399818)]
^C
Thread 1 ".sfxr-wrapped" received signal SIGINT, Interrupt.
0x0000000000402493 in ddkLock () at sdlkit.h:77
77      sdlkit.h: No such file or directory.
(gdb) bt
#0  0x0000000000402493 in ddkLock () at sdlkit.h:77
#1  0x0000000000404971 in DrawScreen () at main.cpp:729
#2  0x00000000004049aa in ddkCalcFrame () at main.cpp:1117
#3  0x0000000000404a0b in loop () at sdlkit.h:227
#4  0x0000000000404d6b in main (argc=<optimized out>, argv=<optimized out>) at sdlkit.h:238
```

**Comment by fgaz** [comment]
Looks like @jwrdegoede [found the issue](https://src.fedoraproject.org/rpms/sfxr/blob/rawhide/f/sfxr-sdl-gcc8x.patch). I'll apply that patch tomorrow.

---

@camtauxe please open another issue for the sfxr-qt theming issue
