### ISSUE TITLE
Unable to run ulauncher due too libgvfsdbus loading error 

### ISSUE THREAD

**Issue by PAI5REECHO** [NixOS/nixpkgs#166054]
### Describe the bug
I'm unable to launch `ulauncher` from the command-line

### Steps To Reproduce
1. Install `ulauncher` into `home.packages` using `home-manager`
2. Run `ulauncher` from the command-line
```
/nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/wshxmgpgrx9cmk0hrbmsxsdg47nmnkc7-gvfs-1.48.1/lib/gio/modules/libgvfsdbus.so)
Failed to load module: /nix/store/wshxmgpgrx9cmk0hrbmsxsdg47nmnkc7-gvfs-1.48.1/lib/gio/modules/libgvfsdbus.so
2022-03-28 09:17:06,011 | WARNING | ulauncher.utils.image_loader: load_image() | Could not load image /home/somebody/.nix-profile/share/ulauncher/media/gear.svg. E: gdk-pixbuf-error-quark: Unable to load image-loading module: /nix/store/jpkv8c5z9fyxbl8s587zjc6winicrj8r-librsvg-2.52.6/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/jpkv8c5z9fyxbl8s587zjc6winicrj8r-librsvg-2.52.6/lib/librsvg-2.so.2) (5)
2022-03-28 09:17:06,011 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/nix/store/9y6q4kpg2jl2w9q29bjw9dzmvprxk4wb-ulauncher-5.9.0/bin/..ulauncher-wrapped-wrapped", line 29, in <module>
    main()
  File "/nix/store/9y6q4kpg2jl2w9q29bjw9dzmvprxk4wb-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/main.py", line 128, in main
    window = UlauncherWindow.get_instance()
  File "/nix/store/9y6q4kpg2jl2w9q29bjw9dzmvprxk4wb-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/nix/store/9y6q4kpg2jl2w9q29bjw9dzmvprxk4wb-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 55, in get_instance
    return cls()
  File "/nix/store/9y6q4kpg2jl2w9q29bjw9dzmvprxk4wb-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 65, in __new__
    new_object.finish_initializing(builder)
  File "/nix/store/9y6q4kpg2jl2w9q29bjw9dzmvprxk4wb-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 98, in finish_initializing
    self.init_theme()
  File "/nix/store/9y6q4kpg2jl2w9q29bjw9dzmvprxk4wb-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 237, in init_theme
    self._render_prefs_icon()
  File "/nix/store/9y6q4kpg2jl2w9q29bjw9dzmvprxk4wb-ulauncher-5.9.0/lib/python3.8/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 388, in _render_prefs_icon
    surface = Gdk.cairo_surface_create_from_pixbuf(prefs_pixbuf, scale_factor, self.get_window())
TypeError: Argument 0 does not allow None as a value
```

### Expected behavior
`ulauncher` to run

### Notify maintainers
@aaronjanse

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.11, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220318_8ad485e`
 - channels(root): `"nixos-21.05.3948.d14d83a3691, home-manager-21.05, nixos-unstable-21.11pre320334.82155ff501c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
Looks like some mismatched glibc issue perhaps and a update probably fixed it
