### ISSUE TITLE
problem when vim plugin repo uri contains `@` 

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#166007]
### Describe the bug

It's not possible to add an url with a `@` in vim-plugin-names.
For instance I tried
`pkgs/applications/editors/vim/plugins/update.py --proc=10 --debug DEBUG  --github-token=$GITHUB_TOKEN --add git@gitlab.com:yorickpeterse/nvim-pqf.git`
which triggered
```
Instantiating github repo ggandor/lightspeed.nvim
Instantiating github repo gibiansky/vim-textobj-haskell
Instantiating github repo gioele/vim-autoswap
Traceback (most recent call last):
  File "/home/teto/nixpkgs3/pkgs/applications/editors/vim/plugins/update.py", line 97, in <module>
    main()
  File "/home/teto/nixpkgs3/pkgs/applications/editors/vim/plugins/update.py", line 93, in main
    pluginupdate.update_plugins(editor, args)
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 643, in update_plugins
    redirects = update()
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 319, in update
    plugin_names = self.load_plugin_spec(config, input_file)
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 306, in load_plugin_spec
    plugin = parse_plugin_line(config, line)
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 518, in parse_plugin_line
    repo = make_repo(uri.strip(), branch.strip(), alias)
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 503, in make_repo
    repo = RepoGitHub(res[0], res[1], branch, alias)
IndexError: list index out of range
```
vim-plugin-names expects owner/repo@branch and it splits on `@`. I passed `git@gitlab.com:yorickpeterse/nvim-pqf.git` and so splitting on @ doesn't work here.

### Additional context
The format of the file itself seems limiting see https://github.com/NixOS/nixpkgs/issues/136248

In the end I use `nix-build -A vimPlugins.nvim-bqf` since it seems more active but this issue could concern other plugins.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
893ffcab6c836d58851bd1c8794789ba74545fab
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here 
```

**Comment by teto** [comment]
nvim-pqf and bqf are not similar after all, I would rather use pqf
