### ISSUE TITLE
python2.7-joblib-0.9.4 test fails on darwin

### ISSUE THREAD

**Issue by reckbo** [NixOS/nixpkgs#16611]
## Issue description

I'm trying to install joblib for python 2.7 on a Mac, but the threading and multiprocessing tests fail.

```
======================================================================
ERROR: joblib.test.test_parallel.test_dispatch_multiprocessing('multiprocessing',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/frs7yp6ggv972r8784zyvxlf2nwbf9fx-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/var/folders/v8/gwfh1xg96bxdw1pwwdv0k1r80000gn/T/nix-build-python2.7-joblib-0.9.4.drv-0/joblib-0.9.4/joblib/test/test_parallel.py", line 354, in check_dispatch_multiprocessing
    manager = mp.Manager()
  File "/nix/store/d3bfgbmvfghl0ii24rz7qawavzssi0cj-python-2.7.11/lib/python2.7/multiprocessing/__init__.py", line 99, in Manager
    m.start()
  File "/nix/store/d3bfgbmvfghl0ii24rz7qawavzssi0cj-python-2.7.11/lib/python2.7/multiprocessing/managers.py", line 528, in start
    self._address = reader.recv()
EOFError
```
### Steps to reproduce

```
nix-env -i python2.7-joblib-0.9.4
```
## Technical details
- System: Darwin Kernel Version 13.4.0
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre83147.df89584"

**Comment by FRidh** [comment]
As I mentioned in https://github.com/NixOS/nixpkgs/issues/14692 you're not supposed to install Python libraries like that.

Even so, the error is still a bug. Unfortunately I'm not using OSX myself so I can't be much of help I'm afraid. I do know there are issues with multiprocessing on OSX with Apple vecLib / Accelerate.

**Comment by reckbo** [comment]
Ok, now I know you have to use nix-shell to load python libraries.  Just adding here that

    nix-shell -p python27Packages.joblib

gives the same error.
