### ISSUE TITLE
clojure-lsp fails to build on darwin

### ISSUE THREAD

**Issue by lockejan** [NixOS/nixpkgs#166267]
### Describe the bug
Providing clojure-lsp breaks during the build. 

Seems to be related to graalvm.

### Steps To Reproduce

1. Install clojure-lsp under darwin `nix-env -iA nixpkgs.clojure-lsp`

### Additional context

```
...

patching script interpreter paths in /nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/bin/jvisualvm: interpreter directive changed from "#!/bin/sh" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/sh"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/python/lib-python/3/ctypes/macholib/fetch_macholib: interpreter directive changed from "#!/bin/sh" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/sh"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/bin/irb: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/bin/rake: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/bin/bundle: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/bin/ri: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/bin/rbs: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/bin/racc: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/bin/erb: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/bin/rdoc: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/bin/typeprof: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/bin/bundler: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/bin/gem: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/ruby/lib/truffle/post_install_hook.sh: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/lib/svm/bin/rebuild-images: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/lib/svm/bin/native-image-configure: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/lib/polyglot/bin/polyglot: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/bash"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/lib/visualvm/platform/lib/nbexec: interpreter directive changed from "#!/bin/sh" to "/nix/store/067f780bk90ghn7yhz914d5fykmll7a4-bash-5.1-p16/bin/sh"
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/libjli.dylib: fixing dylib
/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/languages/python/lib-graalpython/libpythonjni.dylib: fixing dylib

...

/nix/store/135hlcy38bs74syyrglj1p2rxbbbnh7l-graalvm11-ce/lib/libosxapp.dylib: fixing dylib
patching script interpreter paths in /nix/store/mh8g4k1azqa8xx6mnlcfknckdhaybx1i-graalvm11-ce-lib
Traceback (most recent call last):
  File "/nix/store/0jzc88szm7fsjrhzs7jbcj4ini24sj9f-auto-patchelf.py", line 322, in <module>
    with open_elf(interpreter_path) as interpreter:
  File "/nix/store/3j4k5ja8zpr7v5xiyfgjwjb8qnl4iycv-python3-3.9.10/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/nix/store/0jzc88szm7fsjrhzs7jbcj4ini24sj9f-auto-patchelf.py", line 26, in open_elf
    yield ELFFile(stream)
  File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/elf/elffile.py", line 73, in __init__
    self._identify_file()
  File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/elf/elffile.py", line 482, in _identify_file
    elf_assert(magic == b'\x7fELF', 'Magic number does not match')
  File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/common/utils.py", line 77, in elf_assert
    _assert_with_exception(cond, msg, ELFError)
  File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/common/utils.py", line 114, in _assert_with_exception
    raise exception_type(msg)
elftools.common.exceptions.ELFError: Magic number does not match
error: builder for '/nix/store/icg8i47npr9yaq92nl2jfclmm28sjcjc-graalvm11-ce.drv' failed with exit code 1;
       last 10 log lines:
       >     yield ELFFile(stream)
       >   File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/elf/elffile.py", line 73, in __init__
       >     self._identify_file()
       >   File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/elf/elffile.py", line 482, in _identify_file
       >     elf_assert(magic == b'\x7fELF', 'Magic number does not match')
       >   File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/common/utils.py", line 77, in elf_assert
       >     _assert_with_exception(cond, msg, ELFError)
       >   File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/common/utils.py", line 114, in _assert_with_exception
       >     raise exception_type(msg)
       > elftools.common.exceptions.ELFError: Magic number does not match
       For full logs, run 'nix log /nix/store/icg8i47npr9yaq92nl2jfclmm28sjcjc-graalvm11-ce.drv'.
error: 1 dependencies of derivation '/nix/store/p4ld7n2lsm4kqm0lr66ghzcx816lcdnl-clojure-lsp-2022.02.23-12.12.12.drv' failed to build
```

### Notify maintainers

@ericdallo @babariviere 

### Metadata

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.4.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(lockejan): `"home-manager, nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/lockejan/.nix-defexpr/channels/nixpkgs`
```

**Comment by ericdallo** [comment]
@lockejan I got the same error on this bump: https://github.com/NixOS/nixpkgs/pull/166149
I suspect it's not related to clojure-lsp but nix on darwin related, any thoughts @thiagokokada?

**Comment by lockejan** [comment]
Yes, seems to be under darwin only. 
The issue has been introduced with the last version bump. 
At least I can confirm that clojure-lsp is broken under darwin since then.

**Comment by thiagokokada** [comment]
Ok, it seems that the fixes on #163924 was not sufficient to fix `graalvm-ce`.

Let me take a look.

**Comment by lockejan** [comment]
> Ok, it seems that the fixes on #163924 was not sufficient to fix `graalvm-ce`.
> 
> Let me take a look.

Fails for me as well, when attempting to install it from current master.

**Comment by thiagokokada** [comment]
> Ok, it seems that the fixes on #163924 was not sufficient to fix `graalvm-ce`.
> 
> Let me take a look.

Forget it, the actual issue is that #163924 was merged in `staging`.

**Comment by lockejan** [comment]
> > Ok, it seems that the fixes on #163924 was not sufficient to fix `graalvm-ce`.
> > Let me take a look.
> 
> Forget it, the actual issue is that #163924 was merged in `staging`.

I tried installing clojure-lsp from my local nixpkgs-repo (including the mentioned PR) and it failed.
I don't expect this PR to solve the issue. 🤔

**Comment by thiagokokada** [comment]
> > > Ok, it seems that the fixes on #163924 was not sufficient to fix `graalvm-ce`.
> > > Let me take a look.
> > 
> > 
> > Forget it, the actual issue is that #163924 was merged in `staging`.
> 
> I tried installing clojure-lsp from my local nixpkgs-repo (including the mentioned PR) and it failed. I don't expect this PR to solve the issue. 🤔

Did you backport the `graalvm11-ce` changes though 🤔 ?

**Comment by lockejan** [comment]
> > > > Ok, it seems that the fixes on #163924 was not sufficient to fix `graalvm-ce`.
> > > > Let me take a look.
> > > 
> > > 
> > > Forget it, the actual issue is that #163924 was merged in `staging`.
> > 
> > 
> > I tried installing clojure-lsp from my local nixpkgs-repo (including the mentioned PR) and it failed. I don't expect this PR to solve the issue. 🤔
> 
> Did you backport the `graalvm11-ce` changes though 🤔 ?

Sry, I don't follow? Which changes?
(Anyway, I understand that graalvm11-ce breaks the whole build and clojure-lsp seems to be fine.)

**Comment by lockejan** [comment]
Closing since it's a duplicate of https://github.com/NixOS/nixpkgs/issues/165670
