### ISSUE TITLE
yubikey-manager broken on macOS

### ISSUE THREAD

**Issue by tusing** [NixOS/nixpkgs#166348]
`procps` on macOS can not include `pkill` (#141157), but it is used in the `yubikey-manager` derivation:

https://github.com/NixOS/nixpkgs/blob/57a54d6e57a0e6cd460e0a44ff784c4287df69f3/pkgs/tools/misc/yubikey-manager/default.nix#L19

This results in errors like this:

```
Traceback (most recent call last):
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/bin/.ykman-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/cli/__main__.py", line 378, in main
    cli(obj={})
  File "/nix/store/8rjqb6knk07xgbqdspibq5pq3sbjgb4d-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/8rjqb6knk07xgbqdspibq5pq3sbjgb4d-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/nix/store/8rjqb6knk07xgbqdspibq5pq3sbjgb4d-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/8rjqb6knk07xgbqdspibq5pq3sbjgb4d-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/8rjqb6knk07xgbqdspibq5pq3sbjgb4d-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/8rjqb6knk07xgbqdspibq5pq3sbjgb4d-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/8rjqb6knk07xgbqdspibq5pq3sbjgb4d-python3.9-click-8.0.3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/8rjqb6knk07xgbqdspibq5pq3sbjgb4d-python3.9-click-8.0.3/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/cli/openpgp.py", line 156, in set_pin_retries
    controller = ctx.obj["controller"]
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/cli/util.py", line 164, in __getitem__
    self.resolve()
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/cli/util.py", line 161, in resolve
    self._objects[k] = f()
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/cli/__main__.py", line 306, in <lambda>
    ctx.obj.add_resolver("conn", lambda: resolve()[0])
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/cli/__main__.py", line 301, in resolve
    items = _run_cmd_for_single(ctx, subcmd.name, connections, reader)
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/cli/__main__.py", line 197, in _run_cmd_for_single
    return retrying_connect(None, connections, state=state)
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/cli/__main__.py", line 107, in retrying_connect
    raise e
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/cli/__main__.py", line 97, in retrying_connect
    return connect_to_device(serial, connections)
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/device.py", line 216, in connect_to_device
    conn = dev.open_connection(connection_type)
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/pcsc/__init__.py", line 87, in open_connection
    return self._open_smartcard_connection()
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/pcsc/__init__.py", line 97, in _open_smartcard_connection
    if kill_scdaemon():
  File "/nix/store/gy3890h1qvmsk341ypavpida4f47dziz-python3.9-yubikey-manager-4.0.8/lib/python3.9/site-packages/ykman/pcsc/__init__.py", line 142, in kill_scdaemon
    return_code = subprocess.call(["/nix/store/22p96jcqi0f6zgazpk6kbzy1fyrjyxis-procps-1003.1-2008/bin/pkill", "-9", "scdaemon"])  # nosec
  File "/nix/store/3j4k5ja8zpr7v5xiyfgjwjb8qnl4iycv-python3-3.9.10/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/nix/store/3j4k5ja8zpr7v5xiyfgjwjb8qnl4iycv-python3-3.9.10/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/3j4k5ja8zpr7v5xiyfgjwjb8qnl4iycv-python3-3.9.10/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/22p96jcqi0f6zgazpk6kbzy1fyrjyxis-procps-1003.1-2008/bin/pkill'
```

Is it possible to use `/usr/bin/pkill` on Darwin and `${procps}/bin/pkill` elsewhere?

(@mweinelt)

**Comment by mweinelt** [comment]
Maybe like so:

```
diff --git a/pkgs/tools/misc/yubikey-manager/default.nix b/pkgs/tools/misc/yubikey-manager/default.nix
index 66fd783a00e..e4453344f84 100644
--- a/pkgs/tools/misc/yubikey-manager/default.nix
+++ b/pkgs/tools/misc/yubikey-manager/default.nix
@@ -1,4 +1,4 @@
-{ python3Packages, fetchFromGitHub, lib, yubikey-personalization, libu2f-host, libusb1, procps }:
+{ stdenv, python3Packages, fetchFromGitHub, lib, yubikey-personalization, libu2f-host, libusb1, procps }:
 
 python3Packages.buildPythonPackage rec {
   pname = "yubikey-manager";
@@ -16,7 +16,7 @@ python3Packages.buildPythonPackage rec {
     substituteInPlace pyproject.toml \
       --replace 'cryptography = "^2.1 || ^3.0"' 'cryptography = "*"'
     substituteInPlace "ykman/pcsc/__init__.py" \
-      --replace 'pkill' '${procps}/bin/pkill'
+      --replace 'pkill' '$${if stdenv.isDarwin "/usr/bin/pkill" else "${procps}/bin/pkill"}'
   '';
 
   nativeBuildInputs = with python3Packages; [ poetry-core ];
```

**Comment by Lassulus** [comment]
maybe we should just patch the line if we are on non darwin?
