### ISSUE TITLE
golangci-lint not working with go1.18

### ISSUE THREAD

**Issue by Arriven** [NixOS/nixpkgs#166700]
### Steps To Reproduce
1. Enable package override for go to go_1_18 `nixpkgs.config.packageOverrides = pkgs:{ go = pkgs.go_1_18; };`
2. Add golangci-lint to `environment.systemPackages`
3. rebuild nix with `nixos-rebuild test`
4. run `golangci-lint` and get the following error
```console
golangci-lint
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
	github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x4b4
```

### Expected behavior
working program

### Additional context
Apparently this is a bug in golangci-lint when you try to run the executable built with go1.17 while using go1.18 - see [link](https://github.com/golangci/golangci-lint/issues/2649)
What bugs me is that [nix derivation](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/golangci-lint/default.nix) for golangci-lint uses `buildGoModule` which should be using `pkgs.go` which points to `go_1_18` in my case but it doesn't seem to do so. Am I doing something wrong and is there a way to work around this that doesn't require setting up act or docker to lint my workspace?

### Notify maintainers
@anpryl
@manveru 
@Mic92 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.99, NixOS, 22.05 (Quokka), 22.05pre365448.1063244793d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Arriven** [comment]
Jumping into `nix-shell` and building it with `GOBIN=$(pwd) go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2` works but it's definitely not a nix way. With some additional digging I feel like the problem is that nix downloads most packages from the cache and doesn't detect go override as critical to retrigger the build (it did rebuild kubectl). Currently looking into what's the difference between kubectl nix derivation and golangci-lint or how I can disable nix cache for one particular package in a declarative way

**Comment by Arriven** [comment]
ok, found how to fix it locally but I'll prepare a PR to bump go version used to build it pretty soon (as soon as I finish cloning nixpkgs)

for those struggling like me you can just import following nix derivation instead of the package (a bit hacky but does the job):

```nix
with import <nixpkgs>{};

buildGo118Module rec {
  pname = "golangci-lint";
  version = "1.45.2";

  src = fetchFromGitHub {
    owner = "golangci";
    repo = "golangci-lint";
    rev = "v${version}";
    sha256 = "sha256-Mr45nJbpyzxo0ZPwx22JW2WrjyjI9FPpl+gZ7NIc6WQ=";
  };

  vendorSha256 = "sha256-pcbKg1ePN8pObS9EzP3QYjtaty27L9sroKUs/qEPtJo=";

  doCheck = false;

  subPackages = [ "cmd/golangci-lint" ];

  nativeBuildInputs = [ installShellFiles ];

  ldflags = [
    "-s" "-w" "-X main.version=${version}" "-X main.commit=v${version}" "-X main.date=19700101-00:00:00"
  ];

  postInstall = ''
    for shell in bash zsh fish; do
      HOME=$TMPDIR $out/bin/golangci-lint completion $shell > golangci-lint.$shell
      installShellCompletion golangci-lint.$shell
    done
  '';

  meta = with lib; {
    description = "Fast linters Runner for Go";
    homepage = "https://golangci-lint.run/";
    license = licenses.gpl3Plus;
    maintainers = with maintainers; [ anpryl manveru mic92 ];
  };
}
```
