### ISSUE TITLE
azure-cli: No module named 'azure.keyvault.keys'

### ISSUE THREAD

**Issue by peterromfeldhk** [NixOS/nixpkgs#167177]
### Describe the bug
```console
$ az keyvault key show --name my-vault-key --vault-name my-vault
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.keyvault.keys'
Traceback (most recent call last):
  File "/nix/store/67nbrn8qn0d9xph46dqr8z9mv0k6vlrx-python3.9-knack-0.8.2/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/nix/store/wg5mcdzvnwp1nr9wma44lydc9hyznlm4-python3.9-azure-cli-core-2.30.0/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/nix/store/wg5mcdzvnwp1nr9wma44lydc9hyznlm4-python3.9-azure-cli-core-2.30.0/lib/python3.9/site-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/nix/store/wg5mcdzvnwp1nr9wma44lydc9hyznlm4-python3.9-azure-cli-core-2.30.0/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/nix/store/67nbrn8qn0d9xph46dqr8z9mv0k6vlrx-python3.9-knack-0.8.2/lib/python3.9/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/nix/store/gcgvpdybnsim7i8kka4ndc4f71qhbcqs-python3.9-azure-cli-2.30.0/lib/python3.9/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 75, in keyvault_arguments_loader
    op = get_op_handler()
  File "/nix/store/gcgvpdybnsim7i8kka4ndc4f71qhbcqs-python3.9-azure-cli-2.30.0/lib/python3.9/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 72, in get_op_handler
    return self.command_loader.get_op_handler(operations_tmpl.format(method_name))
  File "/nix/store/wg5mcdzvnwp1nr9wma44lydc9hyznlm4-python3.9-azure-cli-core-2.30.0/lib/python3.9/site-packages/azure/cli/core/__init__.py", line 894, in get_op_handler
    op = import_module(mod_to_import)
  File "/nix/store/ghkj7bcqraixj20qafwcpj0jwx56awda-python3-3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.keys'
```

### Steps To Reproduce
the simplest way to reproduce is to add "azure.keyvault.keys" to `pythonImportsCheck` in `default.nix`

### Expected behavior
No exception

### Additional context
i was able to get it to work by adding "azure.keyvault" to `pythonNamespaces` for `azure-keyvault` in `python-packages.nix`
but then other commands stopped working:
```console
$ az keyvault key list -n my-vault -otable
The command failed with an unexpected error. Here is the traceback:
cannot import name 'KeyVaultAuthentication' from 'azure.keyvault' (unknown location)
Traceback (most recent call last):
  File "/nix/store/h2r8lj1s2igzhmxzlqi3gxc0z6m0hfsn-python3.9-knack-0.9.0/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/nix/store/7k9q5rmbxib90f4ncip5ckgjgcyfx05d-python3.9-azure-cli-core-2.34.1/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/nix/store/7k9q5rmbxib90f4ncip5ckgjgcyfx05d-python3.9-azure-cli-core-2.34.1/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/nix/store/7k9q5rmbxib90f4ncip5ckgjgcyfx05d-python3.9-azure-cli-core-2.34.1/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/nix/store/7k9q5rmbxib90f4ncip5ckgjgcyfx05d-python3.9-azure-cli-core-2.34.1/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/nix/store/j0p1n4aq2d7swpmchk7rjn7nh5y9yzn6-python3.9-azure-cli-2.34.1/lib/python3.9/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 100, in keyvault_command_handler
    client = client_factory(command_args['cmd'].cli_ctx, command_args)
  File "/nix/store/j0p1n4aq2d7swpmchk7rjn7nh5y9yzn6-python3.9-azure-cli-2.34.1/lib/python3.9/site-packages/azure/cli/command_modules/keyvault/_client_factory.py", line 147, in keyvault_data_plane_factory
    from azure.keyvault import KeyVaultAuthentication, KeyVaultClient
ImportError: cannot import name 'KeyVaultAuthentication' from 'azure.keyvault' (unknown location)
```

### Notify maintainers
@jonringer

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager, nixos-21.11.336811.0aac710801a"`
 - channels(peter): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jonringer** [comment]
__pycache__  is the culprit

**Comment by Trundle** [comment]
This is caused by `azure-cli`'s mix of namespace and non-namespace packages: [`azure-keyvault-administration`](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/keyvault/azure-keyvault-administration), [`azure-keyvault-keys`](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/keyvault/azure-keyvault-keys) and [`azure-keyvault-secrets`](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/keyvault/azure-keyvault-secrets) use `azure.keyvault` as a namespace, but [`azure-keyvault`](https://github.com/Azure/azure-sdk-for-python/tree/azure-keyvault_1.1.0/azure-keyvault) (in the version required by `azure-cli`) uses `azure.keyvault` as a regular package with a `__init__.py` (with contents, so it cannot simply deleted to make a namespace package out of it).

One fix could be to make one Python environment with all dependencies installed (e.g. `python.withPackages`).

**Comment by randymarsh77** [comment]
Any updates on this? I applied the [linked PR](https://github.com/NixOS/nixpkgs/pull/167248) to my local copy of nixpkgs, resolved a trivial conflict, and `az keyvault X` is working again. The PR seems to have stagnated, but this is still an issue AFAICT.

My repro:

```
$ az keyvault secret --help
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.keyvault.secrets'
[truncated]
```

Local copy of nixpkgs was updated to then latest on master (today): [de72df367566658cef90fecade0255e5259ad740](https://github.com/NixOS/nixpkgs/commit/de72df367566658cef90fecade0255e5259ad740) 

System info:
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixpkgs"`
 - channels(matt.preucil): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by ggPeti** [comment]
@randymarsh77 I also applied that patch and it did not work for me. Got the same error with it.
