### ISSUE TITLE
Building Python 2 packages with Meson might fail

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#167216]
Currently, `python2.pkgs.pycairo`, which is transitively depended on by GIMP, is failing on `staging-next` due to Meson crashing in configure step:

```python-traceback
Traceback (most recent call last):
  File "/nix/store/xp66zc4w184hwipy6zljah1mzk7dprqg-meson-0.61.2/bin/meson", line 6, in <module>
    from mesonbuild.mesonmain import main
  File "/nix/store/xp66zc4w184hwipy6zljah1mzk7dprqg-meson-0.61.2/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 27, in <module>
    from . import mesonlib
  File "/nix/store/xp66zc4w184hwipy6zljah1mzk7dprqg-meson-0.61.2/lib/python3.9/site-packages/mesonbuild/mesonlib/__init__.py", line 21, in <module>
    from .universal import *
  File "/nix/store/xp66zc4w184hwipy6zljah1mzk7dprqg-meson-0.61.2/lib/python3.9/site-packages/mesonbuild/mesonlib/universal.py", line 28, in <module>
    import typing as T
  File "/nix/store/sgk7zd1sqax5gh9avijwp3k7h8451b1g-python2.7-typing-3.10.0.0/lib/python2.7/site-packages/typing.py", line 782, in <module>
    AnyStr = TypeVar('AnyStr', bytes, unicode)
NameError: name 'unicode' is not defined
```

https://hydra.nixos.org/build/171372612/nixlog/31

It appears that Meson (a Python 3 app) is picking up `python2.pkgs.typing` from a transitive dependency in `checkInputs` (likely introduced in https://github.com/NixOS/nixpkgs/commit/58f636511e753e04ff07d43dc54bfbeec086e305), and we were just lucky that we did not encounter this sooner (thanks to Meson being largely self-contained). 

cc @jonringer @FRidh

**Comment by jtojnar** [comment]
Not really sure how to fix it other than by wrapping Meson with `--set PYTHONPATH ""`. That might break third party meson modules, thought I do not think we have any packaged.

**Comment by yu-re-ka** [comment]
Or maybe keep an old version of meson around that is itself using python 2?

**Comment by jtojnar** [comment]
I do not think there was a Python 2 version. And even if there were, it would be so ancient that it could not be used to build any ~current project.

**Comment by FRidh** [comment]
This was bound to happen sometime. It's surprising really we did not see this any sooner with meson though. It's this issue https://github.com/NixOS/nixpkgs/issues/118452.

Workaround in https://github.com/NixOS/nixpkgs/pull/165406/commits/4f30fc6b4d94d1099934dd3629e31c8f658ae86d.
