### ISSUE TITLE
android-studio cannot launch the Android emulator

### ISSUE THREAD

**Issue by mawis** [NixOS/nixpkgs#167343]
### Describe the bug
I tried on 21.11 and unstable to use android-studio with the Android emulator. This worked some weeks ago, but currently I cannot open the emulator. I get the following output on the terminal:

```
2022-04-05 12:07:01,583 [  83661]   WARN -            #com.android.ddmlib - Adb connection Error:EOF 
2022-04-05 12:07:01,587 [  83665]   WARN -            #com.android.ddmlib - Cannot reach ADB server, attempting to reconnect. 
2022-04-05 12:07:02,314 [  84392]   WARN -            #com.android.ddmlib - * daemon not running; starting now at tcp:5037 
2022-04-05 12:07:02,385 [  84463]   WARN -            #com.android.ddmlib - * daemon started successfully 
2022-04-05 12:07:05,380 [  87458]   WARN -            #com.android.ddmlib - Adb connection Error:EOF 
2022-04-05 12:07:05,381 [  87459]   WARN -            #com.android.ddmlib - Cannot reach ADB server, attempting to reconnect. 
2022-04-05 12:07:07,310 [  89388]   WARN -            #com.android.ddmlib - * daemon not running; starting now at tcp:5037 
2022-04-05 12:07:07,379 [  89457]   WARN -            #com.android.ddmlib - * daemon started successfully 
2022-04-05 12:07:14,344 [  96422]   WARN -            #com.android.ddmlib - Adb connection Error:EOF 
2022-04-05 12:07:14,345 [  96423]   WARN -            #com.android.ddmlib - Cannot reach ADB server, attempting to reconnect. 
2022-04-05 12:07:14,811 [  96889]   WARN -            #com.android.ddmlib - * daemon not running; starting now at tcp:5037 
2022-04-05 12:07:14,881 [  96959]   WARN -            #com.android.ddmlib - * daemon started successfully 
2022-04-05 12:09:09,818 [ 211896]   WARN - n.process.BaseOSProcessHandler - Process hasn't generated any output for a long time.
If it's a long-running mostly idle daemon process, consider overriding OSProcessHandler#readerOptions with 'BaseOutputReader.Options.forMostlySilentProcess()' to reduce CPU usage.
Command line: /home/matthias/Android/Sdk/emulator/emulator -netdelay none -netspeed full -avd Pixel_XL_API_31 -qt-hide-window -grpc-use-token -idle-grpc-timeout 300 
java.lang.Throwable: Process creation:
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:33)
	at com.android.tools.idea.avdmanager.EmulatorProcessHandler.<init>(EmulatorProcessHandler.java:36)
	at com.android.tools.idea.avdmanager.EmulatorRunner.start(EmulatorRunner.java:66)
	at com.android.tools.idea.avdmanager.AvdManagerConnection.continueToStartAvd(AvdManagerConnection.java:572)
	at com.android.tools.idea.avdmanager.AvdManagerConnection.continueToStartAvdIfAccelerationErrorIsNotBlocking(AvdManagerConnection.java:507)
	at com.android.tools.idea.avdmanager.AvdManagerConnection.lambda$startAvd$4(AvdManagerConnection.java:497)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:746)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.afterRanInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:133)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-05 12:10:41,088 [ 303166]   WARN - dea.sdk.SystemInfoStatsMonitor - CpuInfoFlags.fromExitCode(): unknown flag values '0x80' 
2022-04-05 12:12:06,361 [ 388439]   WARN -            #com.android.ddmlib - Adb connection Error:EOF 
2022-04-05 12:12:06,362 [ 388440]   WARN -            #com.android.ddmlib - Cannot reach ADB server, attempting to reconnect. 
2022-04-05 12:12:07,342 [ 389420]   WARN -            #com.android.ddmlib - * daemon not running; starting now at tcp:5037 
2022-04-05 12:12:07,412 [ 389490]   WARN -            #com.android.ddmlib - * daemon started successfully 
2022-04-05 12:12:09,615 [ 391693]   WARN - ger.EmulatorConnectionListener - Timed out after 300seconds waiting for emulator to come online. 
2022-04-05 12:12:10,033 [ 392111]   WARN -            #com.android.ddmlib - Adb connection Error:EOF 
2022-04-05 12:12:10,034 [ 392112]   WARN -            #com.android.ddmlib - Cannot reach ADB server, attempting to reconnect. 
2022-04-05 12:12:20,044 [ 402122]   WARN -            #com.android.ddmlib - * daemon not running; starting now at tcp:5037 
2022-04-05 12:12:20,112 [ 402190]   WARN -            #com.android.ddmlib - * daemon started successfully 
2022-04-05 12:12:27,917 [ 409995]   WARN -            #com.android.ddmlib - Adb connection Error:EOF 
2022-04-05 12:12:27,918 [ 409996]   WARN -            #com.android.ddmlib - Cannot reach ADB server, attempting to reconnect. 
2022-04-05 12:12:37,926 [ 420004]   WARN -            #com.android.ddmlib - * daemon not running; starting now at tcp:5037 
2022-04-05 12:12:37,995 [ 420073]   WARN -            #com.android.ddmlib - * daemon started successfully 
```

And after some time the following notification is shown:

![grafik](https://user-images.githubusercontent.com/2042030/161751291-2bffce58-0960-4bbb-857d-8a3014450775.png)

But it seems something is running:

```console
[matthias@tejo ~ ]$ ps ax|grep emu
 641229 pts/0    Sl+    0:02 /home/matthias/Android/Sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64 -netdelay none -netspeed full -avd Pixel_XL_API_31 -qt-hide-window -grpc-use-token -idle-grpc-timeout 300
 641234 pts/0    Sl+    0:00 /home/matthias/Android/Sdk/emulator/emulator64-crash-service -pipe 5 -ppid 1048 -data-dir /tmp/android-matthias/5bb3dd90-07b4-4924-ab9b-44d7d095bb1a
 642127 pts/1    S+     0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox emu
[matthias@tejo ~ ]$ 
```

Running `ldd /home/matthias/Android/Sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64` on a normal terminal results in:

```console
	linux-vdso.so.1 (0x00007fff3b191000)
	libtcmalloc_minimal.so.4 => not found
	libutil.so.1 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libutil.so.1 (0x00007f18ef7f4000)
	libc++.so.1 => not found
	libdl.so.2 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libdl.so.2 (0x00007f18ef7ef000)
	librt.so.1 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/librt.so.1 (0x00007f18ef7e4000)
	libm.so.6 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libm.so.6 (0x00007f18ef6a1000)
	libpthread.so.0 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libpthread.so.0 (0x00007f18ef681000)
	libQt5WebEngineWidgetsAndroidEmu.so.5 => not found
	libQt5WebChannelAndroidEmu.so.5 => not found
	libQt5NetworkAndroidEmu.so.5 => not found
	libQt5QmlAndroidEmu.so.5 => not found
	libQt5WebSocketsAndroidEmu.so.5 => not found
	libQt5CoreAndroidEmu.so.5 => not found
	libQt5GuiAndroidEmu.so.5 => not found
	libQt5WidgetsAndroidEmu.so.5 => not found
	libQt5SvgAndroidEmu.so.5 => not found
	libX11.so.6 => not found
	libpulse.so.0 => not found
	libgcc_s.so.1 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libgcc_s.so.1 (0x00007f18ef663000)
	libc.so.6 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libc.so.6 (0x00007f18ef48e000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib64/ld-linux-x86-64.so.2 (0x00007f18ef7fb000)
```

But I don't know whether android-studio runs the emulator in a different environmetn.

I already deleted /home/matthias/Android completely and reinstalled the SDK using android-studio.

### Steps To Reproduce
1. open `android-studio`
2. create new project
3. create new device
4. run the emulated device

### Expected behavior
Android emulator shows up as a new GUI window

### Screenshots
see above

### Additional context
I also tried this using `android-studio` from the unstable channel as well as `androidStudioPackages.dev` from unstable with the same results

### Notify maintainers
@fabianhjr

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[matthias@tejo ~ ]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.07 MiB download, 0.34 MiB unpacked):
  /nix/store/h8lf018lfkq58qr6fdjabnwln8bi8m5k-stdenv-linux
  /nix/store/jr1ywzriqw9labw6flr8j9b78w0in11d-bash-interactive-5.1-p8-dev
copying path '/nix/store/jr1ywzriqw9labw6flr8j9b78w0in11d-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/h8lf018lfkq58qr6fdjabnwln8bi8m5k-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.108, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.336820.af0a9bc0e53, unstable-22.05pre366144.bc4b9eef3ce"`
 - channels(matthias): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Casul51** [comment]
Well, still doesn't work. Either unstable - https://github.com/NixOS/nixpkgs/issues/267176
Since Genymotion doesn't work - seems there is no _easy_ way to emulate android on NixOS.
Here is more recent log from stable (starting device via device manager):
```

[nix-shell:~]$ android-studio
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
2024-01-14 10:13:14,696 [   1141] SEVERE - #c.i.i.ApplicationLoader - null
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at java.base/jdk.internal.platform.CgroupUtil.lambda$readStringValue$1(CgroupUtil.java:67)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/jdk.internal.platform.CgroupUtil.readStringValue(CgroupUtil.java:69)
        at java.base/jdk.internal.platform.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:65)
        at java.base/jdk.internal.platform.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:124)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:190)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:160)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:85)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getInstance(CgroupV1Subsystem.java:61)
        at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:121)
        at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:91)
        at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:183)
        at java.base/jdk.internal.platform.SystemMetrics.instance(SystemMetrics.java:29)
        at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:58)
        at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
        at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:183)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:280)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:199)
        at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(PlatformMBeanProvider.java:195)
        at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:687)
        at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:389)
        at com.android.tools.analytics.HostData$osBean$2.invoke(HostData.kt:31)
        at com.android.tools.analytics.HostData$osBean$2.invoke(HostData.kt:30)
        at com.android.tools.analytics.StubbableLazy.getValue(HostData.kt:83)
        at com.android.tools.analytics.StubbableLazy.getValue(HostData.kt:89)
        at com.android.tools.analytics.HostData.getOsBean(HostData.kt:30)
        at com.android.tools.idea.stats.AndroidStudioUsageTracker.getMachineDetails(AndroidStudioUsageTracker.kt:152)
        at com.android.tools.idea.stats.AndroidStudioUsageTracker.studioPing(AndroidStudioUsageTracker.kt:233)
        at com.android.tools.idea.stats.AndroidStudioUsageTracker.setup(AndroidStudioUsageTracker.kt:175)
        at com.android.tools.idea.startup.AndroidStudioInitializer.setupAnalytics(AndroidStudioInitializer.java:60)
        at com.android.tools.idea.startup.AndroidStudioInitializer.componentsInitialized(AndroidStudioInitializer.java:40)
        at com.intellij.idea.ApplicationLoader$callAppInitialized$1$1.run(ApplicationLoader.kt:485)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2024-01-14 10:13:14,704 [   1149] SEVERE - #c.i.i.ApplicationLoader - Android Studio Flamingo | 2022.2.1 Patch 1  Build #AI-222.4459.24.2221.9971841
2024-01-14 10:13:14,705 [   1150] SEVERE - #c.i.i.ApplicationLoader - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-01-14 10:13:14,705 [   1150] SEVERE - #c.i.i.ApplicationLoader - OS: Linux
2024-01-14 10:13:33,396 [  19841]   WARN - #c.a.t.i.a.HaxmAlert - Check for emulation acceleration failed
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at java.base/jdk.internal.platform.CgroupUtil.lambda$readStringValue$1(CgroupUtil.java:67)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/jdk.internal.platform.CgroupUtil.readStringValue(CgroupUtil.java:69)
        at java.base/jdk.internal.platform.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:65)
        at java.base/jdk.internal.platform.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:124)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:190)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:160)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:85)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getInstance(CgroupV1Subsystem.java:61)
        at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:121)
        at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:91)
        at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:183)
        at java.base/jdk.internal.platform.SystemMetrics.instance(SystemMetrics.java:29)
        at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:58)
        at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
        at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:183)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:280)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:199)
        at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(PlatformMBeanProvider.java:195)
        at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:687)
        at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:389)
        at com.android.tools.idea.avdmanager.AvdManagerConnection.checkMemorySize(AvdManagerConnection.java:1185)
        at com.android.tools.idea.avdmanager.AvdManagerConnection.getMemorySize(AvdManagerConnection.java:1179)
        at com.android.tools.idea.avdmanager.AvdManagerConnection.checkAcceleration(AvdManagerConnection.java:865)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
        at java.base/java.lang.Thread.run(Thread.java:833)
2024-01-14 10:17:56,755 [ 283200]   WARN - #c.a.s.i.a.AvdManager - Failed 'chattr' for /home/casual/.android/avd/Pixel_6_API_34.avd:
2024-01-14 10:17:56,755 [ 283200]   WARN - #c.a.s.i.a.AvdManager -  -- chattr: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by chattr)
2024-01-14 10:17:57,023 [ 283468]   WARN - #c.a.t.i.a.AvdManagerConnection - Unable to determine if Pixel_6_API_34 is online, assuming it's not
2024-01-14 10:17:58,942 [ 285387]   WARN - #c.a.t.i.a.AvdManagerConnection - Unable to determine if Pixel_6_API_34 is online, assuming it's not
2024-01-14 10:18:23,061 [ 309506]   WARN - #c.a.t.i.a.AvdManagerConnection - Unable to determine if Pixel_6_API_34 is online, assuming it's not
2024-01-14 10:19:11,217 [ 357662]   WARN - #c.a.s.i.a.AvdManager - Failed 'chattr' for /home/casual/.android/avd/Pixel_6_API_34_2.avd:
2024-01-14 10:19:11,217 [ 357662]   WARN - #c.a.s.i.a.AvdManager -  -- chattr: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by chattr)
2024-01-14 10:19:11,474 [ 357919]   WARN - #c.a.t.i.a.AvdManagerConnection - Unable to determine if Pixel_6_API_34_2 is online, assuming it's not
2024-01-14 10:19:14,325 [ 360770]   WARN - #c.a.t.i.a.AvdManagerConnection - Unable to determine if Pixel_6_API_34_2 is online, assuming it's not
2024-01-14 10:19:14,325 [ 360770]   WARN - #c.a.t.i.a.AvdManagerConnection - Unable to determine if Pixel_6_API_34 is online, assuming it's not

```

**Comment by kirillrdy** [comment]
```
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.11, NixOS, 24.05 (Uakari), 24.05.20240113.7e6aa7e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(kirillvr): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

works for me
![image](https://github.com/NixOS/nixpkgs/assets/12160/7c283d8d-ffc8-4548-9bd1-4fc69291d64d)

@Casul51 looking at logs it looks like your issue is unrelated for @mawis 

there are unfortunately too many variables, I can offer you to have a look at my configuration ( github:kirillrdy/dotfiles ), maybe it will help. Otherwise we can try to work on simple nixos config where android-studio emulator works

**Comment by Casul51** [comment]
@kirillrdy I was wrong. I forgot to update my flake (again) and in unstable all works fine

**Comment by kirillrdy** [comment]
@Casul51 all good

as i said, there are too many variables !

**Comment by fabianhjr** [comment]
Good to know it works, closing this issue. :3
