### ISSUE TITLE
Playonlinux: ImportError: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by danykey** [NixOS/nixpkgs#16748]
## Issue description
I had install playonlinux and try to run:
```
Looking for python... 2.7.11 - wxversion(s): 2.8-gtk2-unicode
Traceback (most recent call last):
  File "/nix/store/wnz4h30g1cdx906l5b3q1aymalxsgq9b-playonlinux-4.2.9/share/playonlinux/python/check_python.py", line 7, in <module>
    import wx
  File "/nix/store/cjxgk0gd7adqp7p5izr3j23i6d100p7f-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/nix/store/cjxgk0gd7adqp7p5izr3j23i6d100p7f-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
failed tests
Looking for python2.7... 2.7.11 - wxversion(s): 2.8-gtk2-unicode
Traceback (most recent call last):
  File "/nix/store/wnz4h30g1cdx906l5b3q1aymalxsgq9b-playonlinux-4.2.9/share/playonlinux/python/check_python.py", line 7, in <module>
    import wx
  File "/nix/store/cjxgk0gd7adqp7p5izr3j23i6d100p7f-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/nix/store/cjxgk0gd7adqp7p5izr3j23i6d100p7f-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
failed tests
Looking for python2.6... which: no python2.6 in (/nix/store/97llqmplgnfwcnpmiy1lzy6sfxhhinbr-cabextract-1.6/bin:/nix/store/34sscviv2lpz6vr308gg99rdc2hbhlis-python-2.7.11/bin:/nix/store/vrby5msla3hw8d7v18n5r6ayk0gm0ngm-gettext-0.19.7/bin:/nix/store/ygyxyaq3mkixxl488f58adgjmjjc6jz0-glxinfo-8.1.0/bin:/nix/store/d0j1rwinlh3pf8mfv6dk2hzsap00n5fa-gnupg1compat-0/bin:/nix/store/jjxd9slqd8bq6l79kclak6fyb8vpx590-icoutils-0.31.0/bin:/nix/store/bl02agjjpmawv99rkvr8a46dcygm0m95-imagemagick-6.9.3-9/bin:/nix/store/g6ki355j4vbxrhv5q118wk9az39i4v3k-netcat-gnu-0.7.1/bin:/nix/store/lf7lma87lkgf7248m07n08ydpznmb6il-p7zip-15.14.1/bin:/nix/store/mwcrf3dx41s7dq6rs4nnh35gnnkdbq4y-unzip-6.0/bin:/nix/store/ci63mwv9rhils05rhrwq95prkk2xa5jv-wget-1.17.1/bin:/nix/store/qz6xc8ri4frlqq5nv21s3gmwrba8k0rn-wine-1.8.1/bin:/nix/store/8s8hil6wc520iv0pizr55vb74jbbi4b1-xdg-user-dirs-0.15/bin:/nix/store/i5xr68k3hq647c1a5kw0wqaczrb2hzjg-xterm-320/bin:/nix/store/zzih9m5jps4d49p1l5vi4mgypzirch8c-which-2.21/bin:/nix/store/w8r4s75rld8ll3lc1xch36qy4n3ffp82-curl-7.47.1/bin:/home/danykey/bin:/var/setuid-wrappers:/home/danykey/.nix-profile/bin:/home/danykey/.nix-profile/sbin:/home/danykey/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/run/current-system/sw/bin:/run/current-system/sw/sbin:/run/current-system/sw/lib/kde4/libexec)

Looking for python2... 2.7.11 - wxversion(s): 2.8-gtk2-unicode
Traceback (most recent call last):
  File "/nix/store/wnz4h30g1cdx906l5b3q1aymalxsgq9b-playonlinux-4.2.9/share/playonlinux/python/check_python.py", line 7, in <module>
    import wx
  File "/nix/store/cjxgk0gd7adqp7p5izr3j23i6d100p7f-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/nix/store/cjxgk0gd7adqp7p5izr3j23i6d100p7f-wxPython-2.8.12.1/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
failed tests
Please install python before trying to run this program

```
### Steps to reproduce
Just install and run.

## Technical details

* System: 16.03.923.9e959ce (Emu)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.03.923.9e959ce"

**Comment by FRidh** [comment]
See https://github.com/NixOS/nixpkgs/issues/14914. It is solved on master but not on stable.

**Comment by FRidh** [comment]
A quick fix for Play On Linux on stable would be to build it against wxPython30 instead of wxPython28. I'm not sure whether backporting the changes in https://github.com/NixOS/nixpkgs/pull/15764 will be easy.

**Comment by FRidh** [comment]
Closing this since its explained how it can be fixed.
