### ISSUE TITLE
Can't use totem plugins in gnome 3.20

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#16757]
## Issue description

When enabling plugins in totem, an error message is printed to stderr and the plugin doesn't work.

### Steps to reproduce

- switch to gnome 3.20
- launch `totem`
- in the totem menu, go to `preferences` and `plugins`. Try to enable one.

You will get something like:

```
(totem:24574): libpeas-WARNING **: Error importing plugin 'opensubtitles':
Traceback (most recent call last):
  File "/nix/store/w9gwivwr7ih57b4y1dfhv64xy316p5qn-python3-3.5.1/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/nix/store/lcmys8z90c568yngraa9s6g6glwzdihh-totem-3.20.1/lib/totem/plugins/opensubtitles/opensubtitles.py", line 6, in <module>
    gi.require_version('Totem', '1.0')
  File "/nix/store/l57qb8rir38kfdqjykrnvi1yk1xd070k-pygobject-3.20.0/lib/python3.5/site-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Totem not available

(totem:24574): libpeas-WARNING **: Error loading plugin 'opensubtitles'

(totem:24574): Grilo-WARNING **: [dleyna] grl-dleyna-servers-manager.c:138: Unable to fetch the list of available servers: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.intel.dleyna-server was not provided by any .service files

(totem:24574): libpeas-WARNING **: Error importing plugin 'pythonconsole':
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/w9gwivwr7ih57b4y1dfhv64xy316p5qn-python3-3.5.1/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/nix/store/lcmys8z90c568yngraa9s6g6glwzdihh-totem-3.20.1/lib/totem/plugins/pythonconsole/pythonconsole.py", line 39, in <module>
    from gi.repository import GObject, Peas, Gtk, Totem # pylint: disable-msg=E0611
  File "/nix/store/l57qb8rir38kfdqjykrnvi1yk1xd070k-pygobject-3.20.0/lib/python3.5/site-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Totem, introspection typelib not found

(totem:24574): libpeas-WARNING **: Error loading plugin 'pythonconsole'
```

## Technical details

* System: nixos-unstable

**Comment by DamienCassou** [comment]
This issue seems fixed by #16747.
