### ISSUE TITLE
Python sysconfig gets confused with various pythons on shell, breaking some installs

### ISSUE THREAD

**Issue by Yajo** [NixOS/nixpkgs#167695]
### Describe the bug
If I open a shell that includes various python interpreters, SOABI gets confused. This makes some packages unusable.

### Steps To Reproduce
First run `nix-shell -p python38 -p python39` and then, inside the shell...

```sh
$ which python
/nix/store/5nxnvmc8lnnwyf3x748c34x76hprrbf6-python3-3.8.13/bin/python

$ python -V
Python 3.8.13

$ python -c 'import sysconfig; print(sysconfig.get_config_var("SOABI"))' -V
cpython-39-x86_64-linux-gnu
```

SOABI points to python 3.9, so some compiled packages fail:

```sh
$ python -m venv venv

$ source venv/bin/activate
(venv) 

$ pip install --no-cache-dir psycopg2
Collecting psycopg2
  Downloading psycopg2-2.9.3.tar.gz (380 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.6/380.6 KB 8.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for psycopg2, since package 'wheel' is not installed.
Installing collected packages: psycopg2
  Running setup.py install for psycopg2 ... done
Successfully installed psycopg2-2.9.3
(venv) 

$ python -c 'import sysconfig; print(sysconfig.get_config_var("SOABI"))'
cpython-39-x86_64-linux-gnu
(venv) 

$ python -c 'import psycopg2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/home/yajo/prodevel/example/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'
```

### Expected behavior
SOABI (and all other vars from sysconfig) should be consistent with the python interpreter in use.

### Additional context
Other sysconfig values get polluted. See all:

<details>

```
$ python -c 'import sysconfig, pprint; pprint.pprint(sysconfig.get_config_vars())' | grep -E '3.?9'
 'BINDIR': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/bin',
 'BINLIBDEST': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib/python3.9',
 'BLDLIBRARY': '-L. -lpython3.9',
 'CONFIG_ARGS': "'--prefix=/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10' "
                "'--bindir=/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/bin' "
                "'--sbindir=/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/sbin' "
                "'--includedir=/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/include' "
                "'--oldincludedir=/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/include' "
                "'--mandir=/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/share/man' "
                "'--infodir=/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/share/info' "
                "'--docdir=/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/share/doc/python' "
                "'--libdir=/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib' "
                "'--libexecdir=/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/libexec' "
                "'--localedir=/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/share/locale' "
 'CONFINCLUDEDIR': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/include',
 'CONFINCLUDEPY': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/include/python3.9',
 'COVERAGE_INFO': '/no-such-path/Python-3.9.10/coverage.info',
 'COVERAGE_REPORT': '/no-such-path/Python-3.9.10/lcov-report',
 'DESTDIRS': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10 '
             '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib '
             '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib/python3.9 '
             '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib/python3.9/lib-dynload',
 'DESTLIB': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib/python3.9',
 'DESTSHARED': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib/python3.9/lib-dynload',
 'EXT_SUFFIX': '.cpython-39-x86_64-linux-gnu.so',
 'HAVE_LINUX_CAN_J1939_H': 1,
 'INCLDIRSTOMAKE': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/include '
                   '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/include '
                   '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/include/python3.9 '
                   '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/include/python3.9',
 'INCLUDEDIR': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/include',
 'INCLUDEPY': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/include/python3.9',
 'INSTSONAME': 'libpython3.9.so.1.0',
 'LDLIBRARY': 'libpython3.9.so',
 'LDVERSION': '3.9',
 'LIBDEST': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib/python3.9',
 'LIBDIR': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib',
 'LIBPC': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib/pkgconfig',
 'LIBPL': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib/python3.9/config-3.9-x86_64-linux-gnu',
 'LIBRARY': 'libpython3.9.a',
 'MACHDESTLIB': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib/python3.9',
 'MANDIR': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/share/man',
 'RUNSHARED': 'LD_LIBRARY_PATH=/no-such-path/Python-3.9.10',
 'SCRIPTDIR': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/lib',
 'SO': '.cpython-39-x86_64-linux-gnu.so',
 'SOABI': 'cpython-39-x86_64-linux-gnu',
 'TESTPYTHON': 'LD_LIBRARY_PATH=/no-such-path/Python-3.9.10 ./python',
 'TESTRUNNER': 'LD_LIBRARY_PATH=/no-such-path/Python-3.9.10 ./python '
 'VERSION': '3.9',
 'abs_builddir': '/no-such-path/Python-3.9.10',
 'abs_srcdir': '/no-such-path/Python-3.9.10',
 'datarootdir': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/share',
 'exec_prefix': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10',
 'prefix': '/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10',
```

</details>

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
yajo@toolbox ~/p/example (main)> nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/c86v7bv01y5abwvqaal669hz7n99fcxm-nix-info
copying path '/nix/store/c86v7bv01y5abwvqaal669hz7n99fcxm-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.18-200.fc35.x86_64, Fedora Linux, 35 (Container Image), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(yajo): `"nixpkgs"`
 - nixpkgs: `/var/home/yajo/.nix-defexpr/channels/nixpkgs`

```

@moduon MT-83

**Comment by FRidh** [comment]
`nix-shell` gives a development environment which is similar to a build environment and therefore sets environment variables. Using multiple interpreters in a build is not supported. You really should not be using `nix-shell` in this way.

**Comment by Yajo** [comment]
Oh well, I was just simplifying the test case. In reality I just want to use some apps that are packaged for python 3.9, but I want a python 3.8 interpreter on the shell.

```sh
> nix-shell -p python38 -p pre-commit

[nix-shell:~/prodevel]$ which python3.8
/nix/store/5nxnvmc8lnnwyf3x748c34x76hprrbf6-python3-3.8.13/bin/python3.8

[nix-shell:~/prodevel]$ which python3.9
/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/bin/python3.9

[nix-shell:~/prodevel]$ which pre-commit
/nix/store/0a5v27nm781910xx6lnza1lqfk3f00c3-python3.9-pre-commit-2.17.0/bin/pre-commit

[nix-shell:~/prodevel]$ which python
/nix/store/5nxnvmc8lnnwyf3x748c34x76hprrbf6-python3-3.8.13/bin/python

[nix-shell:~/prodevel]$ python -V
Python 3.8.13

[nix-shell:~/prodevel]$ python -c 'import sysconfig; print(sysconfig.get_config_var("SOABI"))'
cpython-39-x86_64-linux-gnu
```

I don't know why `nix-shell` puts `python3.9` into my `$PATH`. I only asked for `pre-commit`, not for `python3.9`. Then this pollution happens.

Unsurprisingly, the same happens with this `shell.nix`:

```nix
{pkgs ? import <nixpkgs> {}}:
pkgs.mkShell {
  packages = [pkgs.python38 pkgs.pre-commit];
}
```

**Comment by Yajo** [comment]
I just found a workaround:

    nix-shell -p python38 -p pre-commit -p python38

By setting `python38` first, it sets the desired `python` binary. By setting it last, it sets the desired environment.

I feel like this will fail at some point, but for now it seems to work. I still wonder why python3.9 appeared in the shell. 🤔

**Comment by FRidh** [comment]
Better use `nix shell` instead which doesn't run any setup hooks. Alternatively, you can put them in a `buildEnv` which, if I recall correctly, doesn't link the setup hooks so you don't have the issue either.

**Comment by Yajo** [comment]
I've been testing with https://github.com/numtide/devshell and it doesn't have this problem. Thanks for the suggestions.
