### ISSUE TITLE
flutter 2.10.1 : non functioning `flutter devices`

### ISSUE THREAD

**Issue by msackman** [NixOS/nixpkgs#167735]
### Describe the bug
`flutter devices` no longer works.

### Steps To Reproduce
```console
# flutter -v devices
[  +69 ms] executing: uname -m
[  +35 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +6 ms] executing: [/nix/store/w34kvrzcn95zsvx2dii4b321rnrc60lh-flutter-2.10.1-unwrapped/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] db747aa1331bd95bc9b3874c842261ca2d302cd5
[        ] executing: [/nix/store/w34kvrzcn95zsvx2dii4b321rnrc60lh-flutter-2.10.1-unwrapped/] git tag --points-at db747aa1331bd95bc9b3874c842261ca2d302cd5
[  +21 ms] Exit code 0 from: git tag --points-at db747aa1331bd95bc9b3874c842261ca2d302cd5
[        ] 2.10.1
[  +13 ms] executing: [/nix/store/w34kvrzcn95zsvx2dii4b321rnrc60lh-flutter-2.10.1-unwrapped/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/nix/store/w34kvrzcn95zsvx2dii4b321rnrc60lh-flutter-2.10.1-unwrapped/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +83 ms] executing: [/nix/store/w34kvrzcn95zsvx2dii4b321rnrc60lh-flutter-2.10.1-unwrapped/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +66 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +61 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +41 ms] executing: /nix/store/yq4mcr5ykjdbgn1wnbhn2darrzhaba26-android-sdk-env/share/android-sdk/platform-tools/adb devices -l
[  +53 ms] /nix/store/yq4mcr5ykjdbgn1wnbhn2darrzhaba26-android-sdk-env/share/android-sdk/platform-tools/adb: symbol lookup error: /usr/lib/libc.so.6: undefined symbol: __nptl_change_stack_perm, version GLIBC_PRIVATE
[  +16 ms] "flutter devices" took 196ms.
[   +6 ms] Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: /nix/store/yq4mcr5ykjdbgn1wnbhn2darrzhaba26-android-sdk-env/share/android-sdk/platform-tools/adb
[   +5 ms]
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:75:7)
<asynchronous suspension>
#2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:413:54)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
<asynchronous suspension>
#4      DeviceManager.refreshAllConnectedDevices (package:flutter_tools/src/device.dart:180:40)
<asynchronous suspension>
#5      DevicesCommand.runCommand (package:flutter_tools/src/commands/devices.dart:65:34)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:276:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>


[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

### Expected behavior
```console
# /nix/store/yq4mcr5ykjdbgn1wnbhn2darrzhaba26-android-sdk-env/share/android-sdk/platform-tools/adb devices -l
List of devices attached

```

### Additional context
It looks like it's a packaging issue with flutter because when I run adb manually it works just fine, as shown above in "Expected behaviour"

### Notify maintainers
@ericdallo 
@babariviere 

### Metadata
```console
# nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 5.16.18, NixOS, 21.11 (Porcupine)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.16`
- channels(root): `"home-manager-21.11, nixos-21.11.336824.ccb90fb9e11, nixos-unstable-22.05pre367572.b6966d911da"`
- channels(matthew): `"android-nixpkgs"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by msackman** [comment]
My `shell.nix` looks like this:

```nix
{ pkgs ? import <nixpkgs> {}, pkgsUnstable ? import <nixos-unstable> { } }:

let
  android-nixpkgs = pkgs.callPackage <android-nixpkgs> { };

  android-sdk = android-nixpkgs.sdk (sdkPkgs: with sdkPkgs; [
    cmdline-tools-latest
    build-tools-32-0-0
    build-tools-31-0-0
    build-tools-30-0-3
    platform-tools
    platforms-android-31
    platforms-android-30
    system-images-android-30-default-x86-64
    emulator
  ]);

in
pkgs.mkShell {
  CHROME_EXECUTABLE = "${pkgs.google-chrome}/bin/google-chrome-stable";
  FLUTTER_SDK = "${pkgsUnstable.flutter.unwrapped}";

  buildInputs = [
    pkgsUnstable.android-studio
    pkgsUnstable.flutter
    pkgsUnstable.flutter.dart
    pkgsUnstable.jdk11_headless
    pkgsUnstable.nodePackages.firebase-tools
    android-sdk
  ];
}
```

**Comment by msackman** [comment]
Just to make clear it has nothing to do with android nixpkgs:

```console
# nix-shell -p '(import <nixos-unstable> {}).flutter'

[nix-shell:~/programming]$ which flutter
/nix/store/98ncvrvxg0h3fqlbd5j2fwqgjnwannx9-flutter-2.10.1/bin/flutter

[nix-shell:~/programming]$ flutter devices
Downloading package sky_engine...                                  617ms
Downloading flutter_patched_sdk tools...                         1,594ms
Downloading flutter_patched_sdk_product tools...                   999ms
Downloading linux-x64 tools...                                      4.9s
Downloading linux-x64/font-subset tools...                       1,094ms
Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: /nix/store/0x985s7jimd0apnx7w35km3i9j76bqix-platform-tools-31.0.3/libexec/android-sdk/platform-tools/adb
```

**Comment by ruler501** [comment]
I'm seeing the same glibc error with ninja
