### ISSUE TITLE
Keepnote: ImportError: /run/opengl-driver/lib/libEGL.so.1: undefined symbol: wl_proxy_marshal_constructor_versioned

### ISSUE THREAD

**Issue by danykey** [NixOS/nixpkgs#16774]
## Issue description
I have switched to nixos-unstable channel.
So now keepnote not works.
```
==============================================
KeepNote 0.7.8: Thu Jul  7 16:27:53 2016
Traceback (most recent call last):
  File "/nix/store/2d00d3z5hgnsy96h4sxkcgns8w2565rb-keepnote-0.7.8/bin/.keepnote-wrapped", line 438, in <module>
    main(sys.argv)
  File "/nix/store/2d00d3z5hgnsy96h4sxkcgns8w2565rb-keepnote-0.7.8/bin/.keepnote-wrapped", line 424, in main
    start_gui(argv, options, args, cmd_exec)
  File "/nix/store/2d00d3z5hgnsy96h4sxkcgns8w2565rb-keepnote-0.7.8/bin/.keepnote-wrapped", line 260, in start_gui
    import keepnote.gui
  File "/nix/store/2d00d3z5hgnsy96h4sxkcgns8w2565rb-keepnote-0.7.8/lib/python2.7/site-packages/keepnote/gui/__init__.py", line 42, in <module>
    from gtk import gdk
  File "/nix/store/b8vpvcskaj7swnl9hp7y7imc9njcib6b-python2.7-pygtk-2.24.0/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 40, in <module>
    from gtk import _gtk
ImportError: /run/opengl-driver/lib/libEGL.so.1: undefined symbol: wl_proxy_marshal_constructor_versioned

```
### Steps to reproduce
Run keepnote in nixos-unstable channel.

## Technical details

* System: 16.09pre85931.125ffff (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre85931.125ffff"

**Comment by vcunat** [comment]
I see no use to have two issues open when the underlying problem clearly seems to be the same.
