### ISSUE TITLE
Autojump fails "undefined symbol: _PyCodecInfo_GetIncrementalEncoder"

### ISSUE THREAD

**Issue by cheecheeo** [NixOS/nixpkgs#16790]
## Issue description

Autojump fails with an undefined symbol error.
### Steps to reproduce

```
% git log -p | grep commit | head -n 1
commit a2ebf45b4708d6103c77734e04d9067e57ea5cd5

% cat bisect.sh 
#!/usr/bin/env bash

set -ex

export NIXPKGS=${NIXPKGS:-$HOME/packages/nixpkgs}
nix-env --file "$NIXPKGS" -iA autojump
autojump --help

% ./bisect.sh 
+ export NIXPKGS=/home/jchee/packages/nixpkgs
+ NIXPKGS=/home/jchee/packages/nixpkgs
+ nix-env --file /home/jchee/packages/nixpkgs -iA autojump
replacing old ‘autojump-22.2.4’
installing ‘autojump-22.2.4’
+ autojump --help
Traceback (most recent call last):
  File "/home/jchee/.nix-profile/bin/autojump", line 43, in <module>
    from autojump_data import dictify
  File "/nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4/bin/autojump_data.py", line 10, in <module>
    from tempfile import NamedTemporaryFile
  File "/nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/lib/python2.7/lib-dynload/_io.so: undefined symbol: _PyCodecInfo_GetIncrementalEncoder
```
## Technical details
- System: % lsb_release -a
  LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
  Distributor ID: CentOS
  Description:    CentOS release 6.6 (Final)
  Release:        6.6
  Codename:       Final
- Nix version: % nix-env --version
  nix-env (Nix) 1.11.2
- Nixpkgs version: % nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
  "16.09pre83147.df89584"

**Comment by domenkozar** [comment]
Something strange is going on in the environment, following work for me:

```
$ nix-store -r /nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4
$ /nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4/bin/autojump --help
...
```

**Comment by cheecheeo** [comment]
```
% nix-store -r /nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4
warning: you did not specify ‘--add-root’; the result might be removed by the garbage collector
/nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4

% /nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4/bin/autojump --help
Traceback (most recent call last):
  File "/nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4/bin/autojump", line 43, in <module>
    from autojump_data import dictify
  File "/nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4/bin/autojump_data.py", line 10, in <module>
    from tempfile import NamedTemporaryFile
  File "/nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/lib/python2.7/lib-dynload/_io.so: undefined symbol: _PyCodecInfo_GetIncrementalEncoder
```

**Comment by domenkozar** [comment]
Could you run it in clean bash enviroment with `sh`?

**Comment by cheecheeo** [comment]
@domenkozar Like this?

```
% sh
sh-4.3$ env -i
sh-4.3$ nix-store -r /nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4
warning: you did not specify ‘--add-root’; the result might be removed by the garbage collector
/nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4
sh-4.3$ /nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4/bin/autojump --help
Traceback (most recent call last):
  File "/nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4/bin/autojump", line 43, in <module>
    from autojump_data import dictify
  File "/nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4/bin/autojump_data.py", line 10, in <module>
    from tempfile import NamedTemporaryFile
  File "/nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/lib/python2.7/lib-dynload/_io.so: undefined symbol: _PyCodecInfo_GetIncrementalEncoder
```

**Comment by domenkozar** [comment]
Could you pastebin `strace /nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4/bin/autojump --help`

**Comment by cheecheeo** [comment]
```
sh-4.3$ strace /nix/store/dr4sm5yc6wxddbdwvy59439p51fqyb4g-autojump-22.2.4/bin/autojump --help > /tmp/autojump.log 2>&1
```

http://lpaste.net/906162237448650752

**Comment by domenkozar** [comment]
Really no clues. Next: `/nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/bin/python -c "import io"`

**Comment by cheecheeo** [comment]
```
% sh
sh-4.3$ env -i
sh-4.3$ /nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/bin/python -c "import io"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/lib/python2.7/lib-dynload/_io.so: undefined symbol: _PyCodecInfo_GetIncrementalEncoder
```

Will update with an strace. Thanks for all the help!

**Comment by domenkozar** [comment]
to run in clean environment, the correct invocation is `env -i /nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/bin/python -c "import io"`

**Comment by cheecheeo** [comment]
Yup, that  works.

```
sh-4.3$ env -i /nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/bin/python -c "import io"
sh-4.3$ echo $?
0
```

I guess my environment is somehow messed up 😞 .

**Comment by domenkozar** [comment]
Can you pastebin `env`?

try `LD_LIBRARY_PATH= nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/bin/python -c "import io"`

**Comment by cheecheeo** [comment]
env paste: http://lpaste.net/169349

```
% LD_LIBRARY_PATH= /nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11/bin/python -c "import io"

% echo $?
0
```

LD_LIBRARY_PATH looks broken to me.

**Comment by Profpatsch** [comment]
triage: I suspect this is not relevant anymore?

**Comment by domenkozar** [comment]
Quite old version of autojump, closing.
