### ISSUE TITLE
`pycrypto-2.6.1-13.1` fails to build

### ISSUE THREAD

**Issue by dschrempf** [NixOS/nixpkgs#167972]
### Describe the bug

When building `weechat` with scripts on latest `nixpgks-unstable-small`:

```
  weechat = super.weechat.override {
    configure = { availablePlugins, ... }: {
      scripts = with super.weechatScripts; [
        buffer_autoset
        colorize_nicks
        highmon
        wee-slack
        weechat-autosort
        weechat-go
        weechat-matrix
        weechat-notify-send
        weechat-otr
      ];
    };
  };
```

I get the following error:

```
error: builder for '/nix/store/0s29dz0lw0yr0r6k4w6iyqa1sng78x9i-python3.9-pycrypto-2.6.1-13.1.drv' failed with exit code 1;
       last 10 log lines:
       >     dist.run_commands()
       >   File "/nix/store/cc6n0h7n7db2gc1x4a3vh0z6aks7gand-python3.9-setuptools-60.8.2/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
       >     self.run_command(cmd)
       >   File "/nix/store/cc6n0h7n7db2gc1x4a3vh0z6aks7gand-python3.9-setuptools-60.8.2/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
       >     cmd_obj.run()
       >   File "setup.py", line 316, in run
       >     from Crypto import SelfTest
       >   File "/build/python-crypto/build/lib.linux-x86_64-3.9/Crypto/SelfTest/__init__.py", line 35, in <module>
       >     from StringIO import StringIO
       > ModuleNotFoundError: No module named 'StringIO'
       For full logs, run 'nix log /nix/store/0s29dz0lw0yr0r6k4w6iyqa1sng78x9i-python3.9-pycrypto-2.6.1-13.1.drv'.
error: 1 dependencies of derivation '/nix/store/vmzwc5376fd7hgxpj27qabr3g3j3b00j-weechat-otr-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/43r0bkzrmgmhwyz2gi8q2pv0xbivpzlz-libpath.patch.drv' failed to build
error: 1 dependencies of derivation '/nix/store/drk6n0j55zn8zgrg96wqwd69rd77mq4s-weechat-otr-1.9.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4z2lnxd75p9yn2avxpv0zaj0f7dxfji7-weechat-headless.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cxh6pjkhm5d2z3p5ysll3ac10g26g3yc-weechat-bin-env-3.4.1.drv' failed to build
error (ignored): error: cannot unlink '/tmp/nix-build-deploy-rs-0.1.0.drv-0/xdb4am9sh2aakxilgrmb4851xc114lr5-source/target/x86_64-unknown-linux-gnu/release/deps': Directory not empty
error: 1 dependencies of derivation '/nix/store/m5a2h0ka6yr64m5013rcxdayhhayvb5b-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rsq7406lgj7ikssa3n5qr5bv8fri1vnl-home-manager-generation.drv' failed to build
error: error: 1 dependencies of derivation '/nix/store/99lhxj5avp3b27h34hbbr9ax3ka5x5s1-activatable-home-manager-generation.drv' failed to build
```

The error is caused by `pycrypto`, the last lines of the logs are:

```
running test
/nix/store/cc6n0h7n7db2gc1x4a3vh0z6aks7gand-python3.9-setuptools-60.8.2/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pi>
  warnings.warn(
Traceback (most recent call last):
  File "/build/python-crypto/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 451, in <module>
    core.setup(**kw)
  File "/nix/store/cc6n0h7n7db2gc1x4a3vh0z6aks7gand-python3.9-setuptools-60.8.2/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/nix/store/cc6n0h7n7db2gc1x4a3vh0z6aks7gand-python3.9-setuptools-60.8.2/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/nix/store/cc6n0h7n7db2gc1x4a3vh0z6aks7gand-python3.9-setuptools-60.8.2/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/nix/store/cc6n0h7n7db2gc1x4a3vh0z6aks7gand-python3.9-setuptools-60.8.2/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 316, in run
    from Crypto import SelfTest
  File "/build/python-crypto/build/lib.linux-x86_64-3.9/Crypto/SelfTest/__init__.py", line 35, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

### Steps To Reproduce
1. Build `weechat` using the provided override.

### Additional context
Building `python3Packages.pycrypto` using `nix shell nixpkgs-unstable#python3Packages.pycrypto` works. I don't exactly know why (maybe the tests are deactivated?).

### Notify maintainers
No maintainers in `pycrpto/default.nix`.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.32, NixOS, 22.05 (Quokka), 22.05.20220408.e10e367`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - nixpkgs: `/nix/store/040yq8hrrylcby60md5lsipc7mz19bik-source`
```

**Comment by oxzi** [comment]
`weechat-otr` does not use `pycrypto` - which is an alias or "drop-in replacement" for `pycryptdome`. Instead, the plugin's code relies on the "original" but outdated `pycrypto` module, which is used with Debian's patches.

https://github.com/NixOS/nixpkgs/blob/eca01bff99ffbc88b30078d291b5ae997769b076/pkgs/applications/networking/irc/weechat/scripts/weechat-otr/default.nix#L4-L9

As the maintainer of `weechat-otr`, I am going to take a look at this issue. Thanks for reporting :-)
