### ISSUE TITLE
binwalk doesn't build on macOS because of permissions

### ISSUE THREAD

**Issue by ethnt** [NixOS/nixpkgs#168231]
### Describe the bug

I'm getting permission errors when building `binwalk` on macOS:

```
Signature Exception: [Errno 1] Operation not permitted: '/private/tmp/nix-build-python3.9-binwalk-2.3.3.drv-0/source/testing/tests/input-vectors/_dirtraversal.tar.extracted'
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/ym1ds0c4dzwmp3xl66ng9zy3zd7lb72j-python3.9-binwalk-2.3.3/lib/python3.9/site-packages/binwalk/core/module.py", line 595, in main
    retval = self.run()
  File "/nix/store/ym1ds0c4dzwmp3xl66ng9zy3zd7lb72j-python3.9-binwalk-2.3.3/lib/python3.9/site-packages/binwalk/modules/signature.py", line 192, in run
    self.scan_file(fp)
  File "/nix/store/ym1ds0c4dzwmp3xl66ng9zy3zd7lb72j-python3.9-binwalk-2.3.3/lib/python3.9/site-packages/binwalk/modules/signature.py", line 171, in scan_file
    self.result(r=r)
  File "/nix/store/ym1ds0c4dzwmp3xl66ng9zy3zd7lb72j-python3.9-binwalk-2.3.3/lib/python3.9/site-packages/binwalk/core/module.py", line 489, in result
    getattr(self, dependency.attribute).callback(r)
  File "/nix/store/ym1ds0c4dzwmp3xl66ng9zy3zd7lb72j-python3.9-binwalk-2.3.3/lib/python3.9/site-packages/binwalk/modules/extractor.py", line 256, in callback
    (extraction_directory, dd_file, scan_extracted_files, extraction_utility) = self.extract(r.offset,
  File "/nix/store/ym1ds0c4dzwmp3xl66ng9zy3zd7lb72j-python3.9-binwalk-2.3.3/lib/python3.9/site-packages/binwalk/modules/extractor.py", line 628, in extract
    output_directory = self.build_output_directory(file_name)
  File "/nix/store/ym1ds0c4dzwmp3xl66ng9zy3zd7lb72j-python3.9-binwalk-2.3.3/lib/python3.9/site-packages/binwalk/modules/extractor.py", line 580, in build_output_directory
    os.chown(output_directory, self.runas_uid, self.runas_gid)
PermissionError: [Errno 1] Operation not permitted: '/private/tmp/nix-build-python3.9-binwalk-2.3.3.drv-0/source/testing/tests/input-vectors/_dirtraversal.tar.extracted'
----------------------------------------------------------------------------------------------------
```

### Steps To Reproduce
1. `nix-env -iA nixpkgs.binwalk` or `nix-env -iA nixpkgs.python39Packages.binwalk`

### Expected behavior

binwalk to be installed successfully.

### Notify maintainers

@mweinelt

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixpkgs"`
 - channels(ethan): `"nixpkgs, darwin"`
 - nixpkgs: `/Users/ethan/.nix-defexpr/channels/nixpkgs`
```

**Comment by mweinelt** [comment]
Please post the complete build output for the package (e.g. using gist).

**Comment by ethnt** [comment]
@mweinelt Sure thing! https://gist.github.com/ethnt/b4f84a35a7dffeed19917d788884aad5

**Comment by wegank** [comment]
Fixed on [Hydra](https://hydra.nixos.org/job/nixpkgs/nixpkgs-unstable-aarch64-darwin/python39Packages.binwalk.aarch64-darwin) and tested with `nix build nixpkgs#python39Packages.binwalk --rebuild`.
