### ISSUE TITLE
Can not install texlive-full from nixpkgs

### ISSUE THREAD

**Issue by phanimahesh** [NixOS/nixpkgs#16876]
## Issue description

Can not install texlive-full from nixpkgs
### Steps to reproduce

```
$ nox texlive                                                                                                               
Refreshing cache
1 texlive-beamer-2013 (nixpkgs.texLiveBeamer)
    Extra components for TeXLive: beamer class
2 texlive-cm-super-2009 (nixpkgs.texLiveCMSuper)
    Extra components for TeXLive: CM-Super fonts
3 texlive-extra-2014 (nixpkgs.texLiveExtra)
    Extra components for TeXLive
4 texlive-full (nixpkgs.texLiveFull)
    TeX distribution directory
5 texlive-latex-xcolor-2007 (nixpkgs.texLiveLatexXColor)
    Extra components for TeXLive: LaTeX color support
6 texlive-combined-basic-2015 (nixpkgs.texlive.combined.scheme-basic)
    TeX Live environment for scheme-basic
7 texlive-combined-context-2015 (nixpkgs.texlive.combined.scheme-context)
    TeX Live environment for scheme-context
8 texlive-combined-full-2015 (nixpkgs.texlive.combined.scheme-full)
    TeX Live environment for scheme-full
9 texlive-combined-gust-2015 (nixpkgs.texlive.combined.scheme-gust)
    TeX Live environment for scheme-gust
10 texlive-combined-medium-2015 (nixpkgs.texlive.combined.scheme-medium)
    TeX Live environment for scheme-medium
11 texlive-combined-minimal-2015 (nixpkgs.texlive.combined.scheme-minimal)
    TeX Live environment for scheme-minimal
12 texlive-combined-small-2015 (nixpkgs.texlive.combined.scheme-small)
    TeX Live environment for scheme-small
13 texlive-combined-tetex-2015 (nixpkgs.texlive.combined.scheme-tetex)
    TeX Live environment for scheme-tetex
14 texlive-combined-xml-2015 (nixpkgs.texlive.combined.scheme-xml)
    TeX Live environment for scheme-xml
Packages to install: 4
installing ‘texlive-full’
error: while evaluating the attribute ‘buildCommand’ of the derivation ‘TeXLive-linkdir’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/build-support/builder-defs/builder-defs.nix:505:30:
while evaluating ‘textClosure’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/build-support/builder-defs/builder-defs.nix:425:26, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/build-support/builder-defs/builder-defs.nix:506:26:
while evaluating ‘textClosureMap’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/strings-with-deps.nix:69:35, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/build-support/builder-defs/builder-defs.nix:425:33:
while evaluating ‘makeNest’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/build-support/builder-defs/builder-defs.nix:424:20, called from undefined position:
while evaluating the attribute ‘text’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/strings-with-deps.nix:73:38:
while evaluating ‘closePropagation’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:227:22, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/build-support/builder-defs/builder-defs.nix:447:17:
while evaluating ‘uniqList’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:158:14, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:227:29:
while evaluating ‘go’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:159:19, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:165:8:
while evaluating ‘innerClosePropagation’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:210:33, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:227:52:
while evaluating ‘attrByPath’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/attrsets.nix:24:35, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/build-support/builder-defs/builder-defs.nix:449:25:
while evaluating ‘attrByPath’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/attrsets.nix:24:35, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/attrsets.nix:29:12:
while evaluating the attribute ‘buildInputs’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/tools/typesetting/tex/texlive/aggregate.nix:5:3:
while evaluating ‘closePropagation’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:227:22, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/tools/typesetting/tex/texlive/aggregate.nix:5:17:
while evaluating ‘uniqList’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:158:14, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:227:29:
while evaluating ‘go’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:159:19, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:165:8:
while evaluating ‘innerClosePropagation’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:210:33, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:227:52:
while evaluating ‘foldArgs’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:22:31, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/top-level/all-packages.nix:16610:13:
while evaluating ‘setAttrMerge’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:240:43, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:25:17:
while evaluating ‘setAttr’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:235:26, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:241:5:
while evaluating ‘innerBuilderDefsPackage’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/build-support/builder-defs/builder-defs.nix:501:39, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/lib/deprecated.nix:25:45:
while evaluating ‘mkDerivation’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/stdenv/generic/default.nix:95:5, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/build-support/builder-defs/builder-defs.nix:504:9:
while evaluating ‘throwEvalHelp’ at /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/stdenv/generic/default.nix:120:23, called from /nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/stdenv/generic/default.nix:169:21:
Package ‘texlive-core-2014’ in ‘/nix/store/7nygbmc03nxm24iz59s6gwwh9j1q5ham-nixpkgs/nixpkgs/pkgs/tools/typesetting/tex/texlive/default.nix:153’ is marked as broken, refusing to evaluate.
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build` or any other Nix command you can add
  { allowBroken = true; }
to ~/.nixpkgs/config.nix.

Traceback (most recent call last):
  File "/nix/store/m01qr34jsbfp81hdm8720wyr9hh5rnra-nox-0.0.2/bin/.nox-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/wxafxxg9m2igxm89jm6hrvcq732c9ylv-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/wxafxxg9m2igxm89jm6hrvcq732c9ylv-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/nix/store/wxafxxg9m2igxm89jm6hrvcq732c9ylv-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/wxafxxg9m2igxm89jm6hrvcq732c9ylv-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/m01qr34jsbfp81hdm8720wyr9hh5rnra-nox-0.0.2/lib/python3.4/site-packages/nox/search.py", line 83, in main
    subprocess.check_call(['nix-env', '-iA', '--show-trace'] + attributes)
  File "/nix/store/aqyvrkns2ykvb83pmmbb7ban3kwgf0n9-python3-3.4.4/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nix-env', '-iA', '--show-trace', 'nixpkgs.texLiveFull']' returned non-zero exit status 1
```
## Technical details
- System:

```
$ lsb_release -a                                                                                                         1 ↵  
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:    16.04
Codename:   xenial
```
- Nix version:

```
$ nix-env --version                                                                                                           
nix-env (Nix) 1.11.2
```
- Nixpkgs version:

```
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion                                                                    
"16.09pre83147.df89584"
```

**Comment by gebner** [comment]
`texLiveFull` is deprecated and AFAIK no longer maintained.  Please use `texlive.combined.scheme-full` if you want all of texlive.  You can also customize the new texlive packages to only include the packages you need, [see the manual for details](http://nixos.org/nixpkgs/manual/#sec-language-texlive).

**Comment by phanimahesh** [comment]
Oh, okay. thanks. Is anything preventing the deprecated derivation from being removed from the channel so that new users don't get it anymore?

**Comment by copumpkin** [comment]
It might make sense to replace it with an error message telling people what to do instead, so that their old habits don't suddenly stop working with no info on how to fix it.

**Comment by phanimahesh** [comment]
`texlive.combined.scheme-full` is also bad. I tried compiling something and one of the included styles is incompatible with the version of dependency being used.

    /nix/store/pf34hrcyfdql0spfsmlzvh1n1ahg0hiz-texlive-siunitx-2.6e/tex/latex/siunitx/siunitx.sty

on line 16 has `\RequirePackage{expl3}[2015/09/11]`, and the bundled `expl3` is older.

```
LaTeX Warning: You have requested, on input line 16, version
               `2015/09/11' of package expl3,
               but only version
               `2015/03/01 v5547 L3 programming layer (loader) '
               is available.
```

Switched to an install out of nix for now.

**Comment by siddharthist** [comment]
@phanimahesh @copumpkin Maybe we can close this issue (since the relevant question has been answered) and open one for the `texlive.combined.scheme-full` issue that @phanimahesh has found and another for adding an error message in addition to a broken flag?

**Comment by luke-clifton** [comment]
At this point we should just close this.
