### ISSUE TITLE
youtube-dl : youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name

### ISSUE THREAD

**Issue by kevung** [NixOS/nixpkgs#169358]
### Describe the bug

youtube-dl does not download videos from a youtube playlist link.

```
[unger@unger tmp]$ youtube-dl https://youtube.com/playlist?list=OLAK5uy_n9bV6G3_wAm1SOcRR79jUCYET5Wrk63cE --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtube.com/playlist?list=OLAK5uy_n9bV6G3_wAm1SOcRR79jUCYET5Wrk63cE', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Lazy loading extractors enabled
[debug] Python version 3.9.11 (CPython) - Linux-5.10.109-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] OLAK5uy_n9bV6G3_wAm1SOcRR79jUCYET5Wrk63cE: Downloading webpage
[download] Downloading playlist: Sympathique
[youtube:tab] playlist Sympathique: Downloading 11 videos
[download] Downloading video 1 of 11
[youtube] l3AVD7NavZ4: Downloading webpage
[youtube] l3AVD7NavZ4: Downloading player 19eb72e4
ERROR: l3AVD7NavZ4: Traceback (most recent call last):
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1442, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1415, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1396, in _extract_n_function_name
    nfunc_and_idx = self._search_regex(
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1442, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1415, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1396, in _extract_n_function_name
    nfunc_and_idx = self._search_regex(
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1442, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1415, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1396, in _extract_n_function_name
    nfunc_and_idx = self._search_regex(
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1874, in _real_extract
    self._unthrottle_format_urls(video_id, player_url, formats)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1459, in _unthrottle_format_urls
    n_response = self._n_descramble(n_param, player_url, video_id)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1449, in _n_descramble
    raise ExtractorError(traceback.format_exc(), cause=e, video_id=video_id)
youtube_dl.utils.ExtractorError: l3AVD7NavZ4: Traceback (most recent call last):
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1442, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1415, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1396, in _extract_n_function_name
    nfunc_and_idx = self._search_regex(
  File "/nix/store/a9xxgb1cm5dn9qf2cy44bfghmfizdasx-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

### Steps To Reproduce
1. install youtube-dl (in configuration.nix)
2. `youtube-dl https://youtube.com/playlist?list=OLAK5uy_n9bV6G3_wAm1SOcRR79jUCYET5Wrk63cE`

### Expected behavior

The videos from the playlist should be downloaded

### Notify maintainers

@bluescreen303 @fpletz @Ma27 @rycee @asymmetric @peti @AndersonTorres 

### Metadata

```[unger@unger ~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.109, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.337100.7b38b03d76a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
Use yt-dlp

**Comment by Ma27** [comment]
Why did you close this even though it's an actionable thing?

We should either
* await an upstream fix
* remove or mark it as broken

But as long as this didn't happen (and it's undocumented), it's still an issue and hence the issue should remain open until it's fixed.

**Comment by hqurve** [comment]
I think this is related to https://github.com/ytdl-org/youtube-dl/issues/30856 and https://github.com/ytdl-org/youtube-dl/issues/30712

**Comment by milahu** [comment]
> Use yt-dlp

nice. [yt-dlp](https://github.com/yt-dlp/yt-dlp#new-features) also has a self-update feature via `yt-dlp -U`
(which of course is bad for security, but who cares ...)

> youtube-dl : youtube_dl.utils.RegexNotFoundError

is fixed in master

```nix
{
  nixpkgs.overlays = [
    (pkgz: pkgs: {
      youtube-dl = pkgs.youtube-dl.overrideAttrs (old: {
        # fix: Unable to extract Initial JS player n function name
        patches = [];
        version = "unstable-2022-05-10"; # not used 0__o
        src = pkgz.fetchFromGitHub {
          owner = "ytdl-org";
          repo = "youtube-dl";
          rev = "c7965b9fc2cae54f244f31f5373cb81a40e822ab";
          sha256 = "sha256-PrXo8mNlNTD+Fjcb93LUsY5huAR9UCcvR/ujb3zT+1g=";
        };
        postInstall = ""; # fix: youtube-dl.zsh no such file
      });
    })
  ];
```

**Comment by asymmetric** [comment]
I'm not a maintainer of this package, not sure why I was pinged.

**Comment by tobiasBora** [comment]
Funnily, if I download and run `youtube-dl 2021.12.17` inside steam-run, it works:
```
$ steam-run bash
$ ./youtube-dl --version
2021.12.17
$ ./youtube-dl https://www.youtube.com/watch?v=rYoZgpAEkFs
[youtube] rYoZgpAEkFs: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Bird Sounds Spectacular  - Morning Bird Song-rYoZgpAEkFs.f248.webm
[download]  14.3% of 530.47MiB at 66.66KiB/s ETA 01:56:21
```

while if I use the version in nixpkgs (also `2021.12.17`), it fails:
```
$ nix run nixpkgs#youtube-dl -- --version
2021.12.17

$ nix run nixpkgs#youtube-dl https://www.youtube.com/watch?v=rYoZgpAEkFs
[youtube] rYoZgpAEkFs: Downloading webpage
[youtube] rYoZgpAEkFs: Downloading player c5a4daa1
ERROR: rYoZgpAEkFs: Traceback (most recent call last):
  File "/nix/store/8givg10d35bhil1m2ksmqqffmbq45g4c-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1442, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/nix/store/8givg10d35bhil1m2ksmqqffmbq45g4c-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1415, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/nix/store/8givg10d35bhil1m2ksmqqffmbq45g4c-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1396, in _extract_n_function_name
    nfunc_and_idx = self._search_regex(
  File "/nix/store/8givg10d35bhil1m2ksmqqffmbq45g4c-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I'm not sure why the `2021.12.17` downloaded from github works.

**Comment by soulomoon** [comment]
Smae here

**Comment by collares** [comment]
@soulomoon Are you on 22.05? This should be fixed on unstable.

**Comment by soulomoon** [comment]
> @soulomoon Are you on 22.05? This should be fixed on unstable.

I am here
```
github:nixos/nixpkgs/6951b5c187bbf43830ef49a6f37db45882edebba
```
