### ISSUE TITLE
Unable to start Waydroid session (loop mountpoint busy)

### ISSUE THREAD

**Issue by PAI5REECHO** [NixOS/nixpkgs#169593]
### Describe the bug
I'm unable to start a Waydroid session because of a mount command error

### Steps To Reproduce
[Per the instructions on how to manually start waydroid](https://docs.waydro.id/usage/install-on-desktops#manually-starting-waydroid=):
1. `sudo waydroid init`
2. `sudo systemctl restart waydroid-container`
3. `sudo waydroid container start`
4. `waydroid session start` (`WARNING: Service manager /dev/binder has died`)

My `/var/lib/waydroid/waydroid.log` log file content is:
```
(875887) [10:45:58] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(875887) [10:45:58] *** output passed to waydroid stdout, not to this log ***
(875903) [10:46:01] % chmod 666 -R /dev/binder
(875903) [10:46:01] % chmod 666 -R /dev/vndbinder
(875903) [10:46:01] % chmod 666 -R /dev/hwbinder
(875903) [10:46:01] Container manager is waiting for session to load
(875956) [10:46:07] % chmod 666 -R /dev/binder
(875956) [10:46:07] % chmod 666 -R /dev/vndbinder
(875956) [10:46:07] % chmod 666 -R /dev/hwbinder
(875956) [10:46:07] Container manager is waiting for session to load
(875967) [10:46:08] Save session config: /var/lib/waydroid/session.cfg
(875967) [10:46:08] UserMonitor service is not even started
(875967) [10:46:08] Clipboard service is not even started
(875956) [10:46:09] % /nix/store/ygl038g51jp8qh2jgmff7dw5g0hvgnd6-waydroid-1.2.0/lib/python3.9/site-packages/data/scripts/waydroid-net.sh start
(875956) [10:46:09] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(875956) [10:46:09] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(875956) [10:46:09] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(875956) [10:46:09] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(875956) [10:46:09] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(875956) [10:46:09] % mount -o bind /home/me/.local/share/waydroid/data /var/lib/waydroid/data
(875956) [10:46:09] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(875956) [10:46:09] % chmod 777 -R /dev/ashmem
(875956) [10:46:09] % chmod 777 -R /dev/dri
(875956) [10:46:09] % chmod 777 -R /dev/fb0
(875956) [10:46:09] % chmod 777 -R /dev/video0
(875956) [10:46:09] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(875956) [10:46:09] New background process: pid=876019, output=background
(875956) [10:46:09] Save session config: /var/lib/waydroid/session.cfg
(875903) [10:46:09] % /nix/store/ygl038g51jp8qh2jgmff7dw5g0hvgnd6-waydroid-1.2.0/lib/python3.9/site-packages/data/scripts/waydroid-net.sh start
waydroid-net is already running
(875903) [10:46:09] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(875903) [10:46:09] % umount /var/lib/waydroid/rootfs/vendor
(875903) [10:46:09] % umount /var/lib/waydroid/rootfs
(875903) [10:46:09] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
mount: /var/lib/waydroid/rootfs: /dev/loop0 already mounted or mount point busy.
(875903) [10:46:09] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(875903) [10:46:09] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(875903) [10:46:09] ERROR: Command failed: % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(875903) [10:46:09] See also: <https://github.com/waydroid>
(875903) [10:46:09] Traceback (most recent call last):
  File "/nix/store/ygl038g51jp8qh2jgmff7dw5g0hvgnd6-waydroid-1.2.0/lib/python3.9/site-packages/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/nix/store/ygl038g51jp8qh2jgmff7dw5g0hvgnd6-waydroid-1.2.0/lib/python3.9/site-packages/tools/actions/container_manager.py", line 132, in start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"])
  File "/nix/store/ygl038g51jp8qh2jgmff7dw5g0hvgnd6-waydroid-1.2.0/lib/python3.9/site-packages/tools/helpers/images.py", line 90, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/system.img",
  File "/nix/store/ygl038g51jp8qh2jgmff7dw5g0hvgnd6-waydroid-1.2.0/lib/python3.9/site-packages/tools/helpers/mount.py", line 131, in mount
    tools.helpers.run.user(args, ["mount", source, destination])
  File "/nix/store/ygl038g51jp8qh2jgmff7dw5g0hvgnd6-waydroid-1.2.0/lib/python3.9/site-packages/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/nix/store/ygl038g51jp8qh2jgmff7dw5g0hvgnd6-waydroid-1.2.0/lib/python3.9/site-packages/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/nix/store/ygl038g51jp8qh2jgmff7dw5g0hvgnd6-waydroid-1.2.0/lib/python3.9/site-packages/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs

(876087) [10:46:09] UserMonitor service is not even started
(876087) [10:46:09] Clipboard service is not even started
(875956) [10:46:10] session manager stopped, stopping container and waiting...
(875956) [10:46:10] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(875956) [10:46:10] % /nix/store/ygl038g51jp8qh2jgmff7dw5g0hvgnd6-waydroid-1.2.0/lib/python3.9/site-packages/data/scripts/waydroid-net.sh stop
(875956) [10:46:10] % umount /var/lib/waydroid/data
(875956) [10:46:10] % chmod 666 -R /dev/binder
(875956) [10:46:10] % chmod 666 -R /dev/vndbinder
(875956) [10:46:10] % chmod 666 -R /dev/hwbinder
(875956) [10:46:10] Container manager is waiting for session to load
```

### Expected behavior
Should be able to start Waydroid session so I begin using the UI

### Additional context
https://github.com/waydroid/waydroid/issues/99 may be related

### Notify maintainers
@mcaju

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.1, NixOS, 22.05 (Quokka), 22.05.20220417.1ffba9f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220420_9345b4e`
```

**Comment by PAI5REECHO** [comment]
Pinged wrong GH account, meant to direct this to you @CajuM

**Comment by CajuM** [comment]
Hello, it should not be necessary to manually start the waydroid container after restarting the systemd service. Instead, after restarting the container run: `waydroid show-full-ui`.

**Comment by FedX-sudo** [comment]
This could be related to the bug I ran into today. https://github.com/NixOS/nixpkgs/issues/182279
