### ISSUE TITLE
haruna: segmentation fault on exit

### ISSUE THREAD

**Issue by klemensn** [NixOS/nixpkgs#170026]
### Describe the bug
`haruna` crashes due to `SIGSEGV` upon exit if and only if closed graphically,
i.e. starting it in the shell and using `^C` causes it to exit cleanly.

Other graphical programs in the KDE/Plasma suite do not crash like this.

### Steps To Reproduce
1. `$ nix shell -p haruna`
2. `$ haruna`
3. close the window graphically.

### Expected behavior
Clear exit without crashing (and possibly dumping core).

### Additional context
```console
$ haruna
unknown() : qrc:/qml/main.qml:105:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }

unknown() : qrc:/qml/HProgressBar.qml:209:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }

unknown() : qrc:/qml/MpvVideo.qml:308:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }

unknown() : qrc:/qml/Menus/AudioMenu.qml:34:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }

unknown() : qrc:/qml/Menus/AudioMenu.qml:34:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }

Cannot load libcuda.so.1

Segmentation fault (core dumped)
```
```console
$ coredumpctl debug -A '-q -batch -ex bt'

           PID: 21320 (.haruna-wrapped)
           UID: 1000 (kn)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Sun 2022-04-24 00:51:08 EET (8min ago)
  Command Line: /run/current-system/sw/bin/haruna
    Executable: /nix/store/7fgyqycl6nq6f383bmbrp6hgwj8rzf8m-haruna-0.7.3/bin/.haruna-wrapped
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.kde.konsole-67982889e83241a2a3c711bc1707691b.scope
          Unit: user@1000.service
     User Unit: app-org.kde.konsole-67982889e83241a2a3c711bc1707691b.scope
         Slice: user-1000.slice
     Owner UID: 1000 (kn)
       Boot ID: <redacted>
    Machine ID: <redacted>
      Hostname: <redacted>
       Storage: /var/lib/systemd/coredump/core.\x2eharuna-wrapped.1000.b129b782e4504185a59a5e4acf89a2a6.21320.1650754268000000 (present)
     Disk Size: 126.4M
       Message: Process 21320 (.haruna-wrapped) of user 1000 dumped core.
                
                Module linux-vdso.so.1 with build-id a1fd594851d4fab6351cb7deca8610d7679d4f9c
                Module libqjpeg.so without build-id.
                Module libqico.so without build-id.
                Module libqgif.so without build-id.
                Module libqsvg.so without build-id.
                Module kimg_xcf.so without build-id.
                Module kimg_tga.so without build-id.
                Module kimg_rgb.so without build-id.
                Module kimg_ras.so without build-id.
                Module kimg_psd.so without build-id.
                Module kimg_pic.so without build-id.
                Module kimg_pcx.so without build-id.
                Module kimg_ora.so without build-id.
                Module kimg_kra.so without build-id.
                Module kimg_hdr.so without build-id.
                Module libIexMath-2_5.so.25 without build-id.
                Module libIlmThread-2_5.so.25 without build-id.
                Module libImath-2_5.so.25 without build-id.
                Module libIex-2_5.so.25 without build-id.
                Module libHalf-2_5.so.25 without build-id.
                Module libIlmImf-2_5.so.25 without build-id.
                Module kimg_exr.so without build-id.
                Module kimg_eps.so without build-id.
                Module libavif.so.13 without build-id.
                Module kimg_avif.so without build-id.
                Module kimg_ani.so without build-id.
                Module libxdg-shell.so without build-id.
                Module libaspell.so.15 without build-id.
                Module sonnet_aspell.so without build-id.
                Module org.kde.desktop.so without build-id.
                Module libdrm_nouveau.so.2 without build-id.
                Module libdrm_amdgpu.so.1 without build-id.
                Module libelf.so.0 without build-id.
                Module libdrm_radeon.so.1 without build-id.
                Module libLLVM-13.so with build-id b0d994d4c8011ca12e535b02eed5526ab4329ea1
                Module iris_dri.so with build-id 1f573fbfec1d4cd944644cdd2cb97d6beffed5be
                Module libxshmfence.so.1 without build-id.
                Module libxcb-sync.so.1 without build-id.
                Module libxcb-present.so.0 without build-id.
                Module libxcb-dri3.so.0 without build-id.
                Module libxcb-dri2.so.0 without build-id.
                Module libX11-xcb.so.1 without build-id.
                Module libglapi.so.0 without build-id.
                Module libEGL_mesa.so.0 without build-id.
                Module libqt-plugin-wayland-egl.so without build-id.
                Module libQt5QuickShapes.so.5 without build-id.
                Module libqmlshapesplugin.so without build-id.
                Module libKF5SonnetCore.so.5 without build-id.
                Module libsonnetquickplugin.so without build-id.
                Module libmodelsplugin.so without build-id.
                Module libqtgraphicaleffectsprivate.so without build-id.
                Module libqqc2desktopstyleplugin.so without build-id.
                Module libqtquicktemplates2plugin.so without build-id.
                Module libKirigamiPlugin.so without build-id.
                Module libqmlplugin.so without build-id.
                Module libqtlabsplatformplugin.so without build-id.
                Module libqtgraphicaleffectsplugin.so without build-id.
                Module libqquicklayoutsplugin.so without build-id.
                Module libwindowplugin.so without build-id.
                Module libqtquickcontrols2fusionstyleplugin.so without build-id.
                Module libqtquickcontrols2plugin.so without build-id.
                Module libQt5QmlWorkerScript.so.5 without build-id.
                Module libqtquick2plugin.so without build-id.
                Module libpulse-mainloop-glib.so.0 without build-id.
                Module libdbusmenu-qt5.so.2 without build-id.
                Module libphonon4qt5.so.4 without build-id.
                Module libKF5WaylandClient.so.5 without build-id.
                Module libKF5Notifications.so.5 without build-id.
                Module KDEPlasmaPlatformTheme.so without build-id.
                Module libcomposeplatforminputcontextplugin.so without build-id.
                Module libqwayland-generic.so without build-id.
                Module libjansson.so.4 without build-id.
                Module libMESSAGING-SEND-samba4.so without build-id.
                Module libwinbind-client-samba4.so without build-id.
                Module libgpg-error.so.0 without build-id.
                Module libdatrie.so.1 without build-id.
                Module libflag-mapping-samba4.so without build-id.
                Module libclidns-samba4.so without build-id.
                Module libcli-ldap-common-samba4.so without build-id.
                Module libhcrypto-samba4.so.5 without build-id.
                Module libhx509-samba4.so.5 without build-id.
                Module libheimbase-samba4.so.1 without build-id.
                Module libroken-samba4.so.19 without build-id.
                Module libwind-samba4.so.0 without build-id.
                Module libmsghdr-samba4.so without build-id.
                Module libndr-krb5pac.so.0 without build-id.
                Module libasn1-samba4.so.8 without build-id.
                Module libcommon-auth-samba4.so without build-id.
                Module libsamba-modules-samba4.so without build-id.
                Module libwbclient.so.0 without build-id.
                Module libsamdb.so.0 without build-id.
                Module libgcrypt.so.20 without build-id.
                Module liblz4.so.1 without build-id.
                Module libthai.so.0 without build-id.
                Module libselinux.so.1 without build-id.
                Module libgmodule-2.0.so.0 with build-id 4080e7e72c752ae8ab4331f44f085a685a744094
                Module libmd.so.0 without build-id.
                Module libldb.so.2 without build-id.
                Module libldbsamba-samba4.so without build-id.
                Module libsamdb-common-samba4.so without build-id.
                Module libcli-nbt-samba4.so without build-id.
                Module libauthkrb5-samba4.so without build-id.
                Module libaddns-samba4.so without build-id.
                Module libgssapi-samba4.so.2 without build-id.
                Module libcli-cldap-samba4.so without build-id.
                Module libkrb5-samba4.so.26 without build-id.
                Module libndr-nbt.so.0 without build-id.
                Module libtdb.so.1 without build-id.
                Module libtdb-wrap-samba4.so without build-id.
                Module libutil-setid-samba4.so without build-id.
                Module libserver-role-samba4.so without build-id.
                Module libserver-id-db-samba4.so without build-id.
                Module libtalloc-report-printf-samba4.so without build-id.
                Module libsmbd-shim-samba4.so without build-id.
                Module libinterfaces-samba4.so without build-id.
                Module libiov-buf-samba4.so without build-id.
                Module libutil-reg-samba4.so without build-id.
                Module libmessages-util-samba4.so without build-id.
                Module libmessages-dgm-samba4.so without build-id.
                Module libsamba-cluster-support-samba4.so without build-id.
                Module libunwind-x86_64.so.8 without build-id.
                Module libtime-basic-samba4.so without build-id.
                Module libsys-rw-samba4.so without build-id.
                Module libsocket-blocking-samba4.so without build-id.
                Module libdbwrap-samba4.so without build-id.
                Module libndr-samba-samba4.so without build-id.
                Module libutil-tdb-samba4.so without build-id.
                Module libdcerpc-binding.so.0 without build-id.
                Module libndr-samba4.so without build-id.
                Module libsamba-sockets-samba4.so without build-id.
                Module libsmb-transport-samba4.so without build-id.
                Module libcom_err-samba4.so.0 without build-id.
                Module libasn1util-samba4.so without build-id.
                Module libkrb5samba-samba4.so without build-id.
                Module libCHARSET3-samba4.so without build-id.
                Module libcliauth-samba4.so without build-id.
                Module libgensec-samba4.so without build-id.
                Module libgenrand-samba4.so without build-id.
                Module libFLAC.so.8 without build-id.
                Module libgraphite2.so.3 without build-id.
                Module libresolv.so.2 with build-id 847b86d7c620ae7d08e842f302f10127790a9660
                Module libkeyutils.so.1 without build-id.
                Module libkrb5support.so.0 without build-id.
                Module libcom_err.so.3 without build-id.
                Module libk5crypto.so.3 without build-id.
                Module libkrb5.so.3 without build-id.
                Module libsystemd.so.0 without build-id.
                Module libGLX.so.0 without build-id.
                Module libXdmcp.so.6 without build-id.
                Module libXau.so.6 without build-id.
                Module libblkid.so.1 with build-id 9459fab4838321b9f3e8515f33f474b2584cdc22
                Module libnuma.so.1 without build-id.
                Module libmvec.so.1 with build-id 7c827e5796833344caad512799f83613f41171ef
                Module libogg.so.0 without build-id.
                Module libxcb-render.so.0 without build-id.
                Module libpixman-1.so.0 with build-id e543e4db693226a37e0c1af6b6ee9224c1b47b63
                Module libpcre.so.1 without build-id.
                Module libpango-1.0.so.0 without build-id.
                Module libpangoft2-1.0.so.0 without build-id.
                Module libpangocairo-1.0.so.0 without build-id.
                Module libgio-2.0.so.0 with build-id a68fb56a72583f7f51403d6ef1e485a4a72a7ced
                Module libgdk_pixbuf-2.0.so.0 with build-id 2479465a0d6b9071753c6883b013ed7283db85e8
                Module libcairo-gobject.so.2 with build-id 05c4ef277157c7284df9fef6c182cea2d364822a
                Module libbsd.so.0 without build-id.
                Module libsecrets3-samba4.so without build-id.
                Module libsamba-debug-samba4.so without build-id.
                Module libsamba3-util-samba4.so without build-id.
                Module libndr-standard.so.0 without build-id.
                Module libsamba-credentials.so.1 without build-id.
                Module libsamba-hostconfig.so.0 without build-id.
                Module libgse-samba4.so without build-id.
                Module libcli-smb-common-samba4.so without build-id.
                Module libdcerpc-samba-samba4.so without build-id.
                Module libtevent.so.0 without build-id.
                Module libsamba-errors.so.1 without build-id.
                Module libtevent-util.so.0 without build-id.
                Module libsamba-security-samba4.so without build-id.
                Module libsmbconf.so.0 without build-id.
                Module libreplace-samba4.so without build-id.
                Module libsamba-util.so.0 without build-id.
                Module libmsrpc3-samba4.so without build-id.
                Module liblibsmb-samba4.so without build-id.
                Module liblibcli-lsa3-samba4.so without build-id.
                Module libndr.so.2 without build-id.
                Module libtalloc.so.2 without build-id.
                Module libgmp.so.10 without build-id.
                Module libhogweed.so.6 without build-id.
                Module libnettle.so.8 without build-id.
                Module libtasn1.so.6 without build-id.
                Module libunistring.so.2 without build-id.
                Module libidn2.so.0 without build-id.
                Module libp11-kit.so.0 without build-id.
                Module libubsan.so.1 without build-id.
                Module libsodium.so.23 with build-id 3aa7ee4592a79c9c863b8688768dc44bff830782
                Module libgomp.so.1 without build-id.
                Module libXrender.so.1 without build-id.
                Module libdecor-0.so.0 without build-id.
                Module libXxf86vm.so.1 without build-id.
                Module libXi.so.6 without build-id.
                Module libXcursor.so.1 without build-id.
                Module libfftw3.so.3 without build-id.
                Module libsamplerate.so.0 without build-id.
                Module libcap.so.2 without build-id.
                Module libsndfile.so.1 without build-id.
                Module libpulsecommon-14.2.so without build-id.
                Module libatomic.so.1 without build-id.
                Module libreadline.so.6 without build-id.
                Module libepoxy.so.0 without build-id.
                Module libunwind.so.8 without build-id.
                Module libxcb-xfixes.so.0 without build-id.
                Module libxcb-shape.so.0 without build-id.
                Module libxcb-shm.so.0 without build-id.
                Module libffi.so.8 without build-id.
                Module libexpat.so.1 without build-id.
                Module libwayland-server.so.0 with build-id 611748fd13b52d47ec0537600e836dc3414879f5
                Module libsoxr.so.0 without build-id.
                Module libGLdispatch.so.0 without build-id.
                Module libdvdcss.so.2 without build-id.
                Module libncursesw.so.6 without build-id.
                Module libQt5WaylandClient.so.5 without build-id.
                Module libgthread-2.0.so.0 with build-id b4f5c65b985bccbd6328480e35fb1b525c4168fd
                Module libzstd.so.1 without build-id.
                Module libpcre2-16.so.0 without build-id.
                Module libicudata.so.70 without build-id.
                Module libicuuc.so.70 without build-id.
                Module libicui18n.so.70 without build-id.
                Module libharfbuzz.so.0 without build-id.
                Module libpng16.so.16 without build-id.
                Module libcrypto.so.1.1 with build-id 045c7bcdb176312d33bff1324d3a567655b4da20
                Module libssl.so.1.1 with build-id 0ef22347eec4807957f0b133dc07634b1f68555c
                Module libgssapi_krb5.so.2 without build-id.
                Module libQt5QuickTemplates2.so.5 without build-id.
                Module libdbus-1.so.3 without build-id.
                Module libdl.so.2 with build-id c06f3da244980c9a6e8e2a1e4d8990a085103471
                Module libudev.so.1 without build-id.
                Module libGL.so.1 without build-id.
                Module libQt5Svg.so.5 without build-id.
                Module libQt5PrintSupport.so.5 without build-id.
                Module libKF5GlobalAccel.so.5 without build-id.
                Module libxcb-keysyms.so.1 without build-id.
                Module libXfixes.so.3 without build-id.
                Module libxcb.so.1 without build-id.
                Module libQt5X11Extras.so.5 without build-id.
                Module libmount.so.1 with build-id cd0ad49160143a594d579b9a6d293517055994a3
                Module libKF5DBusAddons.so.5 without build-id.
                Module libKF5Crash.so.5 without build-id.
                Module ld-linux-x86-64.so.2 with build-id 30c57076927b082f79b8e0307c2ade477e78866b
                Module libopenh264.so.6 without build-id.
                Module libxvidcore.so.4 without build-id.
                Module libxavs.so.1 without build-id.
                Module libx265.so.199 without build-id.
                Module libx264.so.163 without build-id.
                Module libvorbisenc.so.2 without build-id.
                Module libvorbis.so.0 without build-id.
                Module libvo-amrwbenc.so.0 without build-id.
                Module libtheoradec.so.1 without build-id.
                Module libtheoraenc.so.1 without build-id.
                Module libSvtAv1Enc.so.0 without build-id.
                Module libspeex.so.1 without build-id.
                Module libopus.so.0 without build-id.
                Module libopenjp2.so.7 without build-id.
                Module libopencore-amrnb.so.0 without build-id.
                Module libmp3lame.so.0 without build-id.
                Module libgsm.so without build-id.
                Module libaom.so.3 without build-id.
                Module libcairo.so.2 with build-id c2905b7a90de8e2d0df5cf44e3efead78eb4e607
                Module libglib-2.0.so.0 with build-id 24d88f2adb3db24c34f9ad621f772b856c7d4a11
                Module libgobject-2.0.so.0 with build-id 00e12bb4b861118cda92b66a299d308a69360f3b
                Module librsvg-2.so.2 without build-id.
                Module libdav1d.so.6 without build-id.
                Module libcelt0.so.2 without build-id.
                Module liblzma.so.5 without build-id.
                Module libwebp.so.7 without build-id.
                Module libwebpmux.so.3 without build-id.
                Module libvpx.so.7 without build-id.
                Module libsmbclient.so.0 without build-id.
                Module libssh.so.4 without build-id.
                Module libsrt.so.1.4 without build-id.
                Module libgnutls.so.30 without build-id.
                Module libmodplug.so.1 without build-id.
                Module libgme.so.0 without build-id.
                Module libbz2.so.1 without build-id.
                Module libfreetype.so.6 without build-id.
                Module libfontconfig.so.1 without build-id.
                Module libzmq.so.5 without build-id.
                Module libvidstab.so.1.1 without build-id.
                Module libvmaf.so.1 without build-id.
                Module libfribidi.so.0 without build-id.
                Module libmysofa.so.1 without build-id.
                Module libbs2b.so.0 without build-id.
                Module libpostproc.so.55 without build-id.
                Module libmfx.so.1 without build-id.
                Module libz.so.1 without build-id.
                Module libzimg.so.2 without build-id.
                Module libXv.so.1 without build-id.
                Module libXrandr.so.2 without build-id.
                Module libXinerama.so.1 without build-id.
                Module libXext.so.6 without build-id.
                Module libXss.so.1 without build-id.
                Module libxkbcommon.so.0 without build-id.
                Module libwayland-cursor.so.0 with build-id 524fd5133c3a6674f347e2c4aa584acc511fcbde
                Module libvulkan.so.1 without build-id.
                Module libvdpau.so.1 without build-id.
                Module libva-x11.so.2 without build-id.
                Module libva-wayland.so.2 without build-id.
                Module libva-drm.so.2 without build-id.
                Module libva.so.2 without build-id.
                Module libuchardet.so.0 without build-id.
                Module libshaderc_shared.so.1 without build-id.
                Module libSDL2-2.0.so.0 without build-id.
                Module librubberband.so.2 without build-id.
                Module libpulse.so.0 without build-id.
                Module libopenal.so.1 without build-id.
                Module liblua.so.5.2 without build-id.
                Module librt.so.1 with build-id f610c78fef64474570c8ba2b5c00427c340d1e84
                Module libplacebo.so.192 without build-id.
                Module libbluray.so.2 without build-id.
                Module libavdevice.so.58 without build-id.
                Module libass.so.9 without build-id.
                Module libarchive.so.13 without build-id.
                Module liblcms2.so.2 without build-id.
                Module libjpeg.so.62 without build-id.
                Module libwayland-client.so.0 with build-id 45e2076feb37f91b15990758f811e5e0338a2fb3
                Module libwayland-egl.so.1 with build-id a13b79b32a09a96f5df69cc5acadbfda6a509b0f
                Module libgbm.so.1 without build-id.
                Module libswresample.so.3 without build-id.
                Module libEGL.so.1 without build-id.
                Module libdvdread.so.8 without build-id.
                Module libpthread.so.0 with build-id 7e1bb32908f70cf0fc00d66c983160c7b115f188
                Module libdvdnav.so.4 without build-id.
                Module libdrm.so.2 without build-id.
                Module libcaca.so.0 without build-id.
                Module libasound.so.2 without build-id.
                Module libattr.so.1 without build-id.
                Module libacl.so.1 without build-id.
                Module libKF5GuiAddons.so.5 without build-id.
                Module libKF5Archive.so.5 without build-id.
                Module libexslt.so.0 without build-id.
                Module libxslt.so.1 without build-id.
                Module libxml2.so.2 without build-id.
                Module libc.so.6 with build-id b2073195a02092e5988e0c88ddbe22da749f69ac
                Module libgcc_s.so.1 without build-id.
                Module libm.so.6 with build-id bb1ad44ec0afbc9acf56402168c25a629dfd7adb
                Module libstdc++.so.6 without build-id.
                Module libQt5Core.so.5 without build-id.
                Module libQt5Gui.so.5 without build-id.
                Module libQt5Network.so.5 without build-id.
                Module libQt5Qml.so.5 without build-id.
                Module libQt5QmlModels.so.5 without build-id.
                Module libQt5Quick.so.5 without build-id.
                Module libQt5QuickControls2.so.5 without build-id.
                Module libQt5DBus.so.5 without build-id.
                Module libKF5CoreAddons.so.5 without build-id.
                Module libQt5Xml.so.5 without build-id.
                Module libKF5Solid.so.5 without build-id.
                Module libQt5Widgets.so.5 without build-id.
                Module libKF5ItemViews.so.5 without build-id.
                Module libKF5Codecs.so.5 without build-id.
                Module libKF5AuthCore.so.5 without build-id.
                Module libKF5Auth.so.5 without build-id.
                Module libKF5WidgetsAddons.so.5 without build-id.
                Module libKF5I18n.so.5 without build-id.
                Module libKF5ConfigCore.so.5 without build-id.
                Module libKF5ConfigGui.so.5 without build-id.
                Module libKF5ConfigWidgets.so.5 without build-id.
                Module libKF5IconThemes.so.5 without build-id.
                Module libKF5XmlGui.so.5 without build-id.
                Module libKF5Bookmarks.so.5 without build-id.
                Module libX11.so.6 without build-id.
                Module libKF5WindowSystem.so.5 without build-id.
                Module libKF5Completion.so.5 without build-id.
                Module libKF5JobWidgets.so.5 without build-id.
                Module libKF5Service.so.5 without build-id.
                Module libQt5Concurrent.so.5 without build-id.
                Module libKF5KIOCore.so.5 without build-id.
                Module libKF5KIOGui.so.5 without build-id.
                Module libswscale.so.5 without build-id.
                Module libavcodec.so.58 without build-id.
                Module libavformat.so.58 without build-id.
                Module libavfilter.so.7 without build-id.
                Module libavutil.so.56 without build-id.
                Module libmpv.so.1 without build-id.
                Module libKF5Kirigami2.so.5 without build-id.
                Module libKF5KIONTLM.so.5 without build-id.
                Module libKF5KIOWidgets.so.5 without build-id.
                Module libKF5KIOFileWidgets.so.5 without build-id.
                Module libKF5FileMetaData.so.3 without build-id.
                Module libKF5DocTools.so.5 without build-id.
                Module .haruna-wrapped without build-id.
                Stack trace of thread 21323:
                #0  0x00007f82e80a8c4c _ZN7QObject10disconnectEPKS_PKcS1_S3_ (libQt5Core.so.5 + 0x2f8c4c)
                #1  0x00007f82e9655cd0 n/a (libQt5DBus.so.5 + 0x27cd0)
                #2  0x00007f82e96476c5 n/a (libQt5DBus.so.5 + 0x196c5)
                #3  0x00007f82e7e86441 n/a (libQt5Core.so.5 + 0xd6441)
                #4  0x00007f82e7972eb2 start_thread (libc.so.6 + 0x89eb2)
                #5  0x00007f82e79f531c __clone3 (libc.so.6 + 0x10c31c)
                
                Stack trace of thread 21321:
                #0  0x00007f82e796fc05 __futex_abstimed_wait_common (libc.so.6 + 0x86c05)
                #1  0x00007f82e79723b2 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x893b2)
                #2  0x00007f82e7e8c61b _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xdc61b)
                #3  0x00007f82de360901 n/a (libQt5WaylandClient.so.5 + 0x7c901)
                #4  0x00007f82e7e86441 n/a (libQt5Core.so.5 + 0xd6441)
                #5  0x00007f82e7972eb2 start_thread (libc.so.6 + 0x89eb2)
                #6  0x00007f82e79f531c __clone3 (libc.so.6 + 0x10c31c)
                
                Stack trace of thread 21322:
                #0  0x00007f82e79e8f89 __poll (libc.so.6 + 0xfff89)
                #1  0x00007f82de36095b n/a (libQt5WaylandClient.so.5 + 0x7c95b)
                #2  0x00007f82e7e86441 n/a (libQt5Core.so.5 + 0xd6441)
                #3  0x00007f82e7972eb2 start_thread (libc.so.6 + 0x89eb2)
                #4  0x00007f82e79f531c __clone3 (libc.so.6 + 0x10c31c)
                
                Stack trace of thread 21324:
                #0  0x00007f82e79e8f89 __poll (libc.so.6 + 0xfff89)
                #1  0x00007f82e3e7407e g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x5707e)
                #2  0x00007f82e3e7419f g_main_context_iteration (libglib-2.0.so.0 + 0x5719f)
                #3  0x00007f82e80d16c0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x3216c0)
                #4  0x00007f82e807803b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2c803b)
                #5  0x00007f82e7e8512b _ZN7QThread4execEv (libQt5Core.so.5 + 0xd512b)
                #6  0x00007f82e7e86441 n/a (libQt5Core.so.5 + 0xd6441)
                #7  0x00007f82e7972eb2 start_thread (libc.so.6 + 0x89eb2)
                #8  0x00007f82e79f531c __clone3 (libc.so.6 + 0x10c31c)
                
                Stack trace of thread 21320:
                #0  0x00007f82e796fc05 __futex_abstimed_wait_common (libc.so.6 + 0x86c05)
                #1  0x00007f82e79723b2 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x893b2)
                #2  0x00007f82e7e8c61b _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xdc61b)
                #3  0x00007f82e7e86121 _ZN7QThread4waitE14QDeadlineTimer (libQt5Core.so.5 + 0xd6121)
                #4  0x00007f82e96474d3 n/a (libQt5DBus.so.5 + 0x194d3)
                #5  0x00007f82e9647569 n/a (libQt5DBus.so.5 + 0x19569)
                #6  0x00007f82e792c225 __run_exit_handlers (libc.so.6 + 0x43225)
                #7  0x00007f82e792c3aa exit (libc.so.6 + 0x433aa)
                #8  0x00007f82e79161de __libc_start_call_main (libc.so.6 + 0x2d1de)
                #9  0x00007f82e7916297 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d297)
                #10 0x000000000041b231 _start (.haruna-wrapped + 0x1b231)
                ELF object binary architecture: AMD x86-64


warning: Can't open file /memfd:wayland-cursor (deleted) during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file /memfd:unknown-usage:QtQml (deleted) during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file /run/nscd/db639n2z (deleted) during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing
[New LWP 21323]
[New LWP 21321]
[New LWP 21322]
[New LWP 21324]
[New LWP 21320]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/6w8g7njm4mck5dmjxws0z1xnrxvl81xa-glibc-2.34-115/lib/libthread_db.so.1".
Core was generated by `/run/current-system/sw/bin/haruna'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f82e80a8c4c in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
[Current thread is 1 (Thread 0x7f82c7fff640 (LWP 21323))]
#0  0x00007f82e80a8c4c in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#1  0x00007f82e9655cd0 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5DBus.so.5
#2  0x00007f82e96476c5 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5DBus.so.5
#3  0x00007f82e7e86441 in ?? () from /nix/store/q89pzz0r5f7kz1ng3dnacmayznv54nr3-qtbase-5.15.3/lib/libQt5Core.so.5
#4  0x00007f82e7972eb2 in start_thread () from /nix/store/6w8g7njm4mck5dmjxws0z1xnrxvl81xa-glibc-2.34-115/lib/libc.so.6
#5  0x00007f82e79f531c in clone3 () from /nix/store/6w8g7njm4mck5dmjxws0z1xnrxvl81xa-glibc-2.34-115/lib/libc.so.6
```

### Notify maintainers
@jojosh

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka), 22.05pre369988.1ffba9f2f68`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(kn): `"nixos"`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
Fixed with the update
