### ISSUE TITLE
vimPlugins.coq_nvim is broken

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#170220]
### Describe the bug
Coq_nvim tries to install some dependencies in the nix store.

### Steps To Reproduce
1. Open neovim
2. Run :COQdeps
3. The installation fails because the nix store is read only

### Additional context
`Traceback (most recent call last):                                                                                 
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nix/store/lnh1fra10w28dndglpmzh5l08wq6ww7c-vimplugin-coq_nvim-2022-04-20/coq/__main__.py", line 79, in <module>
    EnvBuilder(
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/venv/__init__.py", line 67, in create
    context = self.ensure_directories(env_dir)
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/venv/__init__.py", line 116, in ensure_direc
tories
    create_if_needed(env_dir)
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/venv/__init__.py", line 105, in create_if_ne
eded
    os.makedirs(d)
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/nix/store/lnh1fra10w28dndglpmzh5l08wq6ww7c-vimplugin-coq_nvim-2022-04-20/.vars'
COQ EXITED - 1`

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.2-xanmod1, NixOS, 22.05 (Quokka), 22.05.git.159f9dfe6ab`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"home-manager, nixos"`
 - channels(quantmint): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ModdedGamers** [comment]
Please see https://github.com/NixOS/nixpkgs/issues/168928#issuecomment-1109581739 for a working solution while this is worked on.

**Comment by QuantMint** [comment]
> Please see [#168928 (comment)](https://github.com/NixOS/nixpkgs/issues/168928#issuecomment-1109581739) for a working solution while this is worked on.

Thanks i didn't see the original issue
