### ISSUE TITLE
emscriptenPackages.zlib is broken

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixpkgs#170621]
### Describe the bug
It seems like since the upgrade to Emscripten 3, this has broken.

### Steps To Reproduce
Try use `emscriptenPackages.zlib`, you get error:
```
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libstubs.a... (this will be cached in "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/cache/sysroot/lib/wasm32-emscripten/libstubs.a" for subsequent builds)
Traceback (most recent call last):
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/emcc.py", line 3863, in <module>
    sys.exit(main(sys.argv))
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/emcc.py", line 3856, in main
    ret = run(args)
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/emcc.py", line 1114, in run
    phase_calculate_system_libraries(state, linker_arguments, linker_inputs, newargs)
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/emcc.py", line 2570, in phase_calculate_system_libraries
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(linker_inputs)] + extra_files_to_link, forced=state.forced_stdlibs)
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/tools/system_libs.py", line 1721, in calculate
    add_library('libstubs')
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/tools/system_libs.py", line 1681, in add_library
    libs_to_link.append((lib.get_link_flag(), need_whole_archive))
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/tools/system_libs.py", line 320, in get_link_flag
    fullpath = self.get_path()
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/tools/system_libs.py", line 312, in get_path
    return shared.Cache.get_lib(self.get_filename(), self.build)
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/tools/cache.py", line 139, in get_lib
    return self.get(name, *args, **kwargs)
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/tools/cache.py", line 167, in get
    creator(cachename)
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/tools/system_libs.py", line 391, in build
    utils.safe_ensure_dirs(build_dir)
  File "/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/tools/utils.py", line 28, in safe_ensure_dirs
    os.makedirs(dirname, exist_ok=True)
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/nix/store/lb30znn7ahijz2mhb5449bj40g80v1ya-emscripten-3.0.0/share/emscripten/cache/build/libstubs'
```

### Expected behavior
The derivation should be built or reused from the caches properly.

### Notify maintainers
@qknight @matthewbauer 

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.94, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335665.0f316e4d72d, nixos-18.03-18.03.133402.cb0e20d6db9, nixos-18.09-18.09.2574.a7e559a5504, nixos-19.03-19.03.173691.34c7eb7545d, nixos-19.09-19.09.2522.75f4ba05c63, nixos-20.03-20.03.3330.1db42b7fe38, nixos-20.09-20.09.4407.1c1f5649bb9, nixos-unstable-22.05pre350017.efeefb2af14"`
 - channels(raskolnikov): `"nixgl, nixpkgs-22.05pre335173.56cbe42f166"`
 - nixpkgs: `/home/raskolnikov/.nix-defexpr/channels/nixpkgs`
```

**Comment by willcohen** [comment]
Should be fixed with the merge of #172207.
