### ISSUE TITLE
Protonvpn 3.11.1 couldn't find acceptable executables for nmcli

### ISSUE THREAD

**Issue by daanrs** [NixOS/nixpkgs#172831]
### Describe the bug
After the update from 2.2.6 to 3.11.1, protonvpn-cli no longer works for me. 
When running it I get the following:
```console
[user@system:~]$ protonvpn-cli
Traceback (most recent call last):
  File "/nix/store/0jzzlwp426hv1gp0z66c9pdjlmg6sqx8-protonvpn-cli-3.11.1/bin/.protonvpn-cli-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/0jzzlwp426hv1gp0z66c9pdjlmg6sqx8-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/main.py", line 20, in main
    from .cli import ProtonVPNCLI
  File "/nix/store/0jzzlwp426hv1gp0z66c9pdjlmg6sqx8-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/cli.py", line 8, in <module>
    from .cli_wrapper import CLIWrapper
  File "/nix/store/0jzzlwp426hv1gp0z66c9pdjlmg6sqx8-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/cli_wrapper.py", line 9, in <module>
    from protonvpn_nm_lib.api import protonvpn
  File "/nix/store/w0br2hw764s2r0rjcxja3k0i0rqny1kd-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/api.py", line 6, in <module>
    from .core.report import BugReport
  File "/nix/store/w0br2hw764s2r0rjcxja3k0i0rqny1kd-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/report/__init__.py", line 1, in <module>
    from .bug import BugReport
  File "/nix/store/w0br2hw764s2r0rjcxja3k0i0rqny1kd-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/report/bug.py", line 7, in <module>
    from ..subprocess_wrapper import subprocess
  File "/nix/store/w0br2hw764s2r0rjcxja3k0i0rqny1kd-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/subprocess_wrapper.py", line 123, in <module>
    subprocess = SubprocessWrapper() # noqa
  File "/nix/store/w0br2hw764s2r0rjcxja3k0i0rqny1kd-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/subprocess_wrapper.py", line 34, in __init__
    self.__ensure_executables_exist()
  File "/nix/store/w0br2hw764s2r0rjcxja3k0i0rqny1kd-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/subprocess_wrapper.py", line 81, in __ensure_executables_exist
    raise RuntimeError(
RuntimeError: Couldn't find acceptable executables for {'nmcli'}
```

### Steps To Reproduce
1. Install version 3.11.1 of protonvpn-cli
2. Run protonvpn-cli

### Expected behavior
The application to output a list of commands. 

### Notify maintainers

@WolfangAukang 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/8fvksz2ayfpm3y0sp5cv3mdf0jwlc6l6-nix-info
copying path '/nix/store/8fvksz2ayfpm3y0sp5cv3mdf0jwlc6l6-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.5, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220505_f4102de`
 - channels(daan): `""`
 - channels(root): `"nixos-21.03pre256292.296793637b2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by WolfangAukang** [comment]
I am not able to reproduce this:

```
> ./result/bin/protonvpn-cli

ProtonVPN CLI v3.11.1

For bugs and errors, please use the form https://protonvpn.com/support-form
or send a report to support@protonvpn.com.

usage:  protonvpn-cli [--version | --help] <command>

commands:
    login               Login with ProtonVPN credentials.
    logout              Disconnect, remove ProtonVPN connection and logout.
    c, connect          Connect to ProtonVPN.
    d, disconnect       Disconnect from ProtonVPN.
    s, status           Show connection status.
    r, reconnect        Reconnect to previously connected server.
    config              Configure user settings.
    ks, killswitch      Configure Kill Switch settings.
    ns, netshield       Configure NetShield settings.

optional arguments:
    -h, --help          Display help message.
    -v, --version       Display versions.
    --get-logs          Get ProtonVPN logs.

examples:
    protonvpn-cli login
    protonvpn-cli login --help
    protonvpn-cli logout
    protonvpn-cli (c | connect)
    protonvpn-cli (c | connect) --help
    protonvpn-cli (d | disconnect)
    protonvpn-cli (s | status)
    protonvpn-cli (r | reconnect)
    protonvpn-cli config
    protonvpn-cli config --help
    protonvpn-cli (-h | --help)
    protonvpn-cli (-v | --version)
    protonvpn-cli --get-logs
```

I would believe it is because I have nmcli available on my system. I believe NetworkManager probably needs to be added to the buildInputs list.

**Comment by Artturin** [comment]
> I am not able to reproduce this:
> 
> ```
> > ./result/bin/protonvpn-cli
> 
> ProtonVPN CLI v3.11.1
> 
> For bugs and errors, please use the form https://protonvpn.com/support-form
> or send a report to support@protonvpn.com.
> 
> usage:  protonvpn-cli [--version | --help] <command>
> 
> commands:
>     login               Login with ProtonVPN credentials.
>     logout              Disconnect, remove ProtonVPN connection and logout.
>     c, connect          Connect to ProtonVPN.
>     d, disconnect       Disconnect from ProtonVPN.
>     s, status           Show connection status.
>     r, reconnect        Reconnect to previously connected server.
>     config              Configure user settings.
>     ks, killswitch      Configure Kill Switch settings.
>     ns, netshield       Configure NetShield settings.
> 
> optional arguments:
>     -h, --help          Display help message.
>     -v, --version       Display versions.
>     --get-logs          Get ProtonVPN logs.
> 
> examples:
>     protonvpn-cli login
>     protonvpn-cli login --help
>     protonvpn-cli logout
>     protonvpn-cli (c | connect)
>     protonvpn-cli (c | connect) --help
>     protonvpn-cli (d | disconnect)
>     protonvpn-cli (s | status)
>     protonvpn-cli (r | reconnect)
>     protonvpn-cli config
>     protonvpn-cli config --help
>     protonvpn-cli (-h | --help)
>     protonvpn-cli (-v | --version)
>     protonvpn-cli --get-logs
> ```
> 
> I would believe it is because I have `nmcli` available on my system. I believe NetworkManager probably needs to be added to the buildInputs list. Are you able to try this @daanrs?

do `PATH= ./result/bin/protonvpn-cli`

**Comment by daanrs** [comment]
Adding networkmanager to propagatedBuildInputs for either protonvpn-cli or protonvpn-nm-lib worked. Adding it to buildInputs did not work.

I'm not sure if I did everything right, but I did the following:

* cloned nixpkgs
* added networkmanager to propagatedBuildInputs
* ran nix build '.#protonvpn-cli'
* executed ./result/bin/protonvpn

**Comment by Artturin** [comment]
wrapping or patching should be used instead of propagatedX

**Comment by WolfangAukang** [comment]
Taking a better look at the error code, and running the command provided by @Artturin, `protonvpn-nm-cli` should be fixed instead. I will post it later today.

**Comment by WolfangAukang** [comment]
@daanrs can you please check it now? The changes have been merged

**Comment by daanrs** [comment]
I can now successfully run protonvpn-cli! But I get an error when trying to connect to a server. I'm not sure if this is a nixpkgs  or upstream error though.

When trying to connect I get
```
➜  ~ protonvpn-cli c -f
Setting up ProtonVPN.

An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.
```
If I look at the logs then it says 
```
-------------------------------------------------

-----------	Initialized protonvpn-cli	-----------

-------------------------------------------------
2022-05-28 15:38:02,155 — cli.py — INFO — __init__:29 — ProtonVPN CLI v3.11.1 (protonvpn-nm-lib v3.9.0; proton-client v0.7.1)
2022-05-28 15:38:02,159 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='c', version=False, help=False, get_logs=False)
2022-05-28 15:38:02,159 — cli.py — INFO — connect:128 — Options: Namespace(servername=None, fastest=True, random=False, cc=None, sc=False, p2p=False, tor=False, protocol=None, help=False)
2022-05-28 15:38:02,983 — cli_wrapper.py — ERROR — connect:379 — Support for given configuration is not implemented
Traceback (most recent call last):
  File "/nix/store/4nnpyw3jmicjazjqwv78kb3bwk06xa13-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/cli_wrapper.py", line 277, in connect
    self.protonvpn.setup_connection(
  File "/nix/store/pzldg2m4yxg39bkzh3yq87fw62n7cvfp-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/api.py", line 158, in setup_connection
    self._env.connection_backend.setup(**data)
  File "/nix/store/pzldg2m4yxg39bkzh3yq87fw62n7cvfp-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client.py", line 51, in setup
    connection, protocol_implementation = NMPlugin.import_vpn_config(
  File "/nix/store/pzldg2m4yxg39bkzh3yq87fw62n7cvfp-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/plugin/nm_plugin.py", line 31, in import_vpn_config
    raise NotImplementedError(
NotImplementedError: Support for given configuration is not implemented
```
Listing my config settings works fine:
```
➜  ~ protonvpn-cli config -l

ProtonVPN User Settings
---------------------------
Default Protocol:	OpenVPN (UDP)
Kill Switch:		Off
Netshield:		Disabled
DNS:			Automatic
Alternative Routing:	Enabled
VPN Accelerator:	Enabled
Moderate NAT:		Off
Non Standard Ports:	Off
```
but if I try to reset it to default I get the following
```➜  ~ protonvpn-cli config -d

Are you sure you want to restore to default configurations? [y/N]: y
Restoring default ProtonVPN configurations...

org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
```

I don't know if this is related or should be a seperate issue or something

**Comment by WolfangAukang** [comment]
This one I am not able to replicate, unfortunately:

```
> PATH= ./result/bin/protonvpn-cli c
Setting up ProtonVPN.
Connecting to ProtonVPN on US-FREE#11 with UDP.

Successfully connected to ProtonVPN.

> PATH= ./result/bin/protonvpn-cli config -d
Are you sure you want to restore to default configurations? [y/N]: y
Restoring default ProtonVPN configurations...

Configurations were successfully reset to default values.
```

I am throwing my guesses in that the issue might be the same, but unfortunately I have no clues of what could be done to solve it, as NetworkManager is already on the `nativeBuildInputs`. My recommendation would be using `protonvpn-cli-2`, which uses OpenVPN instead of NetworkManager.

**Comment by daanrs** [comment]
Unfortunate, but not a problem. protonvpn-cli-2 works, so that is fine for me.

Thank you for your help regardless!
