### ISSUE TITLE
dotnetCorePackages.sdk_3_1: fails to build in latest unstable

### ISSUE THREAD

**Issue by GGG-KILLER** [NixOS/nixpkgs#173188]
### Steps To Reproduce
1. Add the following to your configuration:
```nix
{
  environment.systemPackages = [
    (with pkgs.dotnetCorePackages; combinePackages [
      sdk_6_0
      sdk_3_1
    ])
  ];
}
```
2. Attempt to build

### Build log
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/v341z9d3h8f9kxx1k84r5wh60akz3ysw-dotnet-sdk-3.1.415-linux-x64.tar.gz
source root is .
setting SOURCE_DATE_EPOCH to timestamp 1635274917 of file ./sdk/3.1.415/Sdks/NuGet.Build.Tasks.Pack/CoreCLR/NuGet.Build.Tasks.Pack.dll
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
no Makefile, doing nothing
@nix { "action": "setPhase", "phase": "installPhase" }
installing
@nix { "action": "setPhase", "phase": "fixupPhase" }
post-installation fixup
rewriting symlink /nix/store/zaak5j4w1hm1cdl4iijks8afgcb51gz0-dotnet-sdk-3.1.415/bin/dotnet to be relative to /nix/store/zaak5j4w1hm1cdl4iijks8afgcb51gz0-dotnet-sdk-3.1.415
strip is /nix/store/bg35nfwn6zd616facdywiysgpprfvsji-gcc-wrapper-11.3.0/bin/strip
stripping (with command strip and flags -S) in /nix/store/zaak5j4w1hm1cdl4iijks8afgcb51gz0-dotnet-sdk-3.1.415/bin 
patching script interpreter paths in /nix/store/zaak5j4w1hm1cdl4iijks8afgcb51gz0-dotnet-sdk-3.1.415
checking for references to /build/ in /nix/store/zaak5j4w1hm1cdl4iijks8afgcb51gz0-dotnet-sdk-3.1.415...
@nix { "action": "setPhase", "phase": "installCheckPhase" }
running install tests
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.String.ToLowerInvariant()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetArch()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
/nix/store/crpnj8ssz0va2q0p5ibv9i6k6n52gcya-stdenv-linux/setup: line 1373:   125 Aborted                 (core dumped) $out/bin/dotnet --info
```

### Additional context
No additional context available currently.

### Notify maintainers
@kuznero

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka), 22.05.20220426.e10da1c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/yyddvwq452qsvpgb104mllpq0hkkmsqx-source`
```

**Comment by GGG-KILLER** [comment]
Ok, I'll close this as fixed by #172335.
