### ISSUE TITLE
Seahub fails to start

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#173825]
### Describe the bug
I did a fresh install of Seafile, seeking a simple replacement for NextCloud, and when I installed `Seafile`, `Seahub`, the WebUI part of the project fails.

### Steps To Reproduce
1. Set up seafile:
```
{ pkgs, config, ...}:
{
  services.seafile = {
    enable = true;
    workers = 8;
    seafileSettings.fileserver = {
      port = 8082;
      host = "127.0.0.1";
    };
    adminEmail = "PFCKrutonium@gmail.com";
    initialAdminPassword = "badPassword";
    ccnetSettings.General.SERVICE_URL = "seafile.krutonium.ca";
  };
}
```
2. Get this error:
```
May 20 21:20:09 uWebServer seahub-pre-start[120986]: Traceback (most recent call last):
May 20 21:20:09 uWebServer seahub-pre-start[120986]:   File "/nix/store/635ih8cwnvwiblb8aynr80l7qi8zimxs-python3.9-django-3.2.13/lib/python3.9/site-packages/django/apps/config.py", line 244, in create
May 20 21:20:09 uWebServer seahub-pre-start[120986]:     app_module = import_module(app_name)
May 20 21:20:09 uWebServer seahub-pre-start[120986]:   File "/nix/store/wnrc4daqbd6v5ifqlxsj75ky8556zy0p-python3-3.9.12/lib/python3.9/importlib/__init__.py", line 127, in import_module
May 20 21:20:09 uWebServer seahub-pre-start[120986]:     return _bootstrap._gcd_import(name[level:], package, level)
May 20 21:20:09 uWebServer seahub-pre-start[120986]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
May 20 21:20:09 uWebServer seahub-pre-start[120986]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
May 20 21:20:09 uWebServer seahub-pre-start[120986]:   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
May 20 21:20:09 uWebServer seahub-pre-start[120986]: ModuleNotFoundError: No module named 'drafts'
May 20 21:20:09 uWebServer seahub-pre-start[120986]: During handling of the above exception, another exception occurred:
May 20 21:20:09 uWebServer seahub-pre-start[120986]: Traceback (most recent call last):
May 20 21:20:09 uWebServer seahub-pre-start[120986]:   File "/nix/store/58j0ri3sah8rxhizfgwkg239b89205m5-seahub-8.0.8/.manage.py-wrapped", line 10, in <module>
May 20 21:20:09 uWebServer seahub-pre-start[120986]:     execute_from_command_line(sys.argv)
May 20 21:20:09 uWebServer seahub-pre-start[120986]:   File "/nix/store/635ih8cwnvwiblb8aynr80l7qi8zimxs-python3.9-django-3.2.13/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execu>
May 20 21:20:09 uWebServer seahub-pre-start[120986]:     utility.execute()
May 20 21:20:09 uWebServer seahub-pre-start[120986]:   File "/nix/store/635ih8cwnvwiblb8aynr80l7qi8zimxs-python3.9-django-3.2.13/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execu>
May 20 21:20:09 uWebServer seahub-pre-start[120986]:     django.setup()
May 20 21:20:09 uWebServer seahub-pre-start[120986]:   File "/nix/store/635ih8cwnvwiblb8aynr80l7qi8zimxs-python3.9-django-3.2.13/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
May 20 21:20:09 uWebServer seahub-pre-start[120986]:     apps.populate(settings.INSTALLED_APPS)
May 20 21:20:09 uWebServer seahub-pre-start[120986]:   File "/nix/store/635ih8cwnvwiblb8aynr80l7qi8zimxs-python3.9-django-3.2.13/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
May 20 21:20:09 uWebServer seahub-pre-start[120986]:     app_config = AppConfig.create(entry)
May 20 21:20:09 uWebServer seahub-pre-start[120986]:   File "/nix/store/635ih8cwnvwiblb8aynr80l7qi8zimxs-python3.9-django-3.2.13/lib/python3.9/site-packages/django/apps/config.py", line 246, in create
May 20 21:20:09 uWebServer seahub-pre-start[120986]:     raise ImproperlyConfigured(
May 20 21:20:09 uWebServer seahub-pre-start[120986]: django.core.exceptions.ImproperlyConfigured: Cannot import 'drafts'. Check that 'seahub.drafts.apps.DraftsConfig.name' is correct.
May 20 21:20:09 uWebServer systemd[1]: seahub.service: Control process exited, code=exited, status=1/FAILURE
```
Which appears to be because it's missing a module called `drafts`?
### Expected behavior
Ideally, it starts up and works

### Notify maintainers
@greizgh @schmittlauch 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.39, NixOS, 22.05 (Quokka), 22.05.20220518.48037fd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220512_d354fc3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Elinvention** [comment]
I can reproduce this issue. It looks like an error with django configuration, but I don't know what to do about it. Probably the issue comes from https://github.com/NixOS/nixpkgs/blob/05eb51e69c993596401d0bc58ceedb5f46de40b4/nixos/modules/services/networking/seafile.nix#L273

**Comment by sbourdeauducq** [comment]
You can indeed reproduce the issue with:
```
nix-build -A seahub
CCNET_CONF_DIR=/var/lib/seafile/ccnet SEAFILE_CONF_DIR=/var/lib/seafile/data result/manage.py migrate
```

**Comment by sbourdeauducq** [comment]
I suppose this line:
https://github.com/haiwen/seahub/blob/c51346155b2f31e038c3a2a12e69dcc6665502e2/seahub/drafts/apps.py#L8
needs a ``seahub.`` prefix like elsewhere, e.g.
https://github.com/haiwen/seahub/blob/c51346155b2f31e038c3a2a12e69dcc6665502e2/seahub/two_factor/apps.py#L7

**Comment by sbourdeauducq** [comment]
You can work around this and two similar problems with:
```
seahub = super.seahub.overrideAttrs(oa: {
      patchPhase = 
        ''
        substituteInPlace seahub/drafts/apps.py --replace drafts seahub.drafts
        substituteInPlace seahub/file_tags/apps.py --replace file_tags seahub.file_tags
        substituteInPlace seahub/related_files/apps.py --replace related_files seahub.related_files
        '';
    });
```

But now it fails with
```
ImportError: cannot import name 'six' from 'django.utils' (/nix/store/wxx4kljyh01an77j0zswh8kashr837bd-python3.9-django-3.2.13/lib/python3.9/site-packages/django/utils/__init__.py)
```

Seems the seafile package isn't particularly well-maintained, which is concerning (security-wise) for an internet-facing service.

**Comment by Elinvention** [comment]
From what I can tell from https://forum.seafile.com/t/seafile-community-edition-9-0-is-ready-for-test/15430 seaf-server 9.0 switched only the http component to golang and that component is turned off by default. We can think about building and enabling the new component later and focus on packaging the new version of seaf-server and seahub.

**Comment by greizgh** [comment]
> From what I can tell from https://forum.seafile.com/t/seafile-community-edition-9-0-is-ready-for-test/15430 seaf-server 9.0 switched only the http component to golang and that component is turned off by default. We can think about building and enabling the new component later and focus on packaging the new version of seaf-server and seahub.

That's a good point, thanks for bringing that up, I assumed they already switched to the new component.

I gave a quick look at the 9.0x update, it seems to run properly in a test container (branch [here](https://github.com/greizgh/nixpkgs/tree/update-seafile) if you want to test).
What's left to do now is to figure out a proper way to run the appropriate migrations in the service.

**Comment by Elinvention** [comment]
@greizgh I tried your work and finally Seafile works for me! Thank you. I think this issue can now be closed.
