### ISSUE TITLE
Session crashes at launch

### ISSUE THREAD

**Issue by wyndon** [NixOS/nixpkgs#174002]
### Describe the bug
Session crashes at launch.

### Steps To Reproduce
1. Launch Session from cli/desktop

### Expected behavior
Session should launch.

### Additional context
```console
[user@system:~]$ session-desktop-appimage-1.8.4 
Set Windows Application User Model ID (AUMID) { appUserModelId: 'com.loki-project.messenger-desktop' }
NODE_ENV production
NODE_APP_INSTANCE undefined
NODE_CONFIG_DIR /nix/store/pl64i8zk8s8r5qg469r4cd5zlk61nkkf-session-desktop-appimage-1.8.4-extracted/resources/app.asar/config
NODE_CONFIG {}
userData: /home/wyndon/.config/Session
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
making app single instance
{"name":"log","hostname":"astronaut","pid":2,"level":30,"msg":"app ready","time":"2022-05-22T14:44:57.481Z","v":0}
{"name":"log","hostname":"astronaut","pid":2,"level":30,"msg":"starting version 1.8.4","time":"2022-05-22T14:44:57.481Z","v":0}
{"name":"log","hostname":"astronaut","pid":2,"level":30,"msg":"migrateDatabase: Migration without cipher change failed {}","time":"2022-05-22T14:44:57.484Z","v":0}
{"name":"log","hostname":"astronaut","pid":2,"level":50,"msg":"getUserVersion error {}","time":"2022-05-22T14:44:57.485Z","v":0}
{"name":"log","hostname":"astronaut","pid":2,"level":30,"msg":"migrateDatabase: migrateSchemaVersion failed {}","time":"2022-05-22T14:44:57.485Z","v":0}
{"name":"log","hostname":"astronaut","pid":2,"level":30,"msg":"Database startup error: TypeError: Cannot read property 'prepare' of null\n    at getSQLiteVersion ([REDACTED]/app.asar/app/sql.js:151:33)\n    at updateSchema ([REDACTED]/app.asar/app/sql.js:817:25)\n    at Object.initialize ([REDACTED]/app.asar/app/sql.js:1524:5)\n    at showMainWindow ([REDACTED]/app.asar/main.js:669:7)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async App.<anonymous> ([REDACTED]/app.asar/main.js:635:5)","time":"2022-05-22T14:44:57.485Z","v":0}
Unhandled Promise Rejection: TypeError: Cannot read property 'prepare' of undefined
    at getById (/nix/store/pl64i8zk8s8r5qg469r4cd5zlk61nkkf-session-desktop-appimage-1.8.4-extracted/resources/app.asar/app/sql.js:1692:44)
    at Object.getItemById (/nix/store/pl64i8zk8s8r5qg469r4cd5zlk61nkkf-session-desktop-appimage-1.8.4-extracted/resources/app.asar/app/sql.js:1659:10)
    at getSpellCheckSetting (/nix/store/pl64i8zk8s8r5qg469r4cd5zlk61nkkf-session-desktop-appimage-1.8.4-extracted/resources/app.asar/main.js:82:26)
    at showMainWindow (/nix/store/pl64i8zk8s8r5qg469r4cd5zlk61nkkf-session-desktop-appimage-1.8.4-extracted/resources/app.asar/main.js:675:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async App.<anonymous> (/nix/store/pl64i8zk8s8r5qg469r4cd5zlk61nkkf-session-desktop-appimage-1.8.4-extracted/resources/app.asar/main.js:635:5)
{"name":"log","hostname":"astronaut","pid":2,"level":50,"msg":"Unhandled Promise Rejection: {}","time":"2022-05-22T14:44:57.523Z","v":0}
```

### Notify maintainers

@Alexnortung 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.8-xanmod1, NixOS, 22.05 (Quokka), 22.05.20220518.48037fd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos"`
 - channels(wyndon): `"nixos"`
 - nixpkgs: `/nix/store/jvjjrzjc5bgvwc5nzc1pqxn2wn35vx97-source`
```

**Comment by Alexnortung** [comment]
Pretty sure this is an upstream bug.
I had the same issue, I made it work again by deleting sessions `.config` folder (`~/.config/Session`).
This will log you out so make sure you have saved your recovery phrase first.

Let me know if it works.

**Comment by wyndon** [comment]
Indeed it works. Thanks ! I didn't use Session for quite a time.

Not related but, I have a black screen upon launching on Wayland. Could you add support for adding wayland flags when `NIXOS_OZONE_WL` is set ? Something like here : https://github.com/NixOS/nixpkgs/blob/3d4e586313d292c9e764a8e88a1fdccb16ffb2d3/pkgs/applications/networking/instant-messengers/element/element-desktop.nix#L89

**Comment by Alexnortung** [comment]
I am not using wayland so I would not be able to test it right now.
Also I don't feel like I have time to add it right now, but feel free to add it in a PR :)
