### ISSUE TITLE
protonvpn-gui error: No modules named 'dbus'

### ISSUE THREAD

**Issue by rhoriguchi** [NixOS/nixpkgs#175512]
### Describe the bug
When starting `protonvpn-gui` I'm getting an error message `No modules named 'dbus'`.

### Steps To Reproduce
1. Install `protonvpn-gui`
2. Start desktop app

### Expected behavior
No error message.

### Screenshots
![image](https://user-images.githubusercontent.com/6047658/171050030-04d5f064-66cf-4b85-8c21-5477a1133257.png)

### Additional context
Running GNOME 42.

### Notify maintainers

@WolfangAukang

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.7, NixOS, 22.11 (Raccoon), 22.11pre380684.83658b28fe6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220512_d354fc3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by WolfangAukang** [comment]
Can you please provide the logs for this?

**Comment by Obikawa** [comment]
```
$ protonvpn-cli login [REDACTED]
Traceback (most recent call last):
  File "/nix/store/fj2ihsvcv6naa1w25dnsrxpha91dvi8p-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 21, in __getitem__
    stored_data = self.__keyring_backend.get_password(
  File "/nix/store/z2j949ab8r726jlfd1k0yfc4njqlkb5h-python3.9-keyring-23.5.1/lib/python3.9/site-packages/keyring/backends/kwallet.py", line 110, in get_password
    if not self.connected(service):
  File "/nix/store/z2j949ab8r726jlfd1k0yfc4njqlkb5h-python3.9-keyring-23.5.1/lib/python3.9/site-packages/keyring/backends/kwallet.py", line 94, in connected
    bus = dbus.SessionBus(mainloop=DBusGMainLoop())
NameError: name 'dbus' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/9yplkli2mlg8ncnxs9bkkra9jh2w34f5-protonvpn-cli-3.11.1/bin/.protonvpn-cli-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/9yplkli2mlg8ncnxs9bkkra9jh2w34f5-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/nix/store/9yplkli2mlg8ncnxs9bkkra9jh2w34f5-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/cli.py", line 65, in __init__
    res = getattr(self, args.command)()
  File "/nix/store/9yplkli2mlg8ncnxs9bkkra9jh2w34f5-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/cli.py", line 162, in login
    return self.cli_wrapper.login(args.username)
  File "/nix/store/9yplkli2mlg8ncnxs9bkkra9jh2w34f5-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/cli_wrapper.py", line 63, in login
    if self.protonvpn.check_session_exists():
  File "/nix/store/fj2ihsvcv6naa1w25dnsrxpha91dvi8p-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/api.py", line 356, in check_session_exists
    return self._env.api_session.is_valid
  File "/nix/store/fj2ihsvcv6naa1w25dnsrxpha91dvi8p-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/environment.py", line 56, in api_session
    self.__api_session = APISession()
  File "/nix/store/fj2ihsvcv6naa1w25dnsrxpha91dvi8p-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/session/session.py", line 224, in __init__
    self.__keyring_load_session()
  File "/nix/store/fj2ihsvcv6naa1w25dnsrxpha91dvi8p-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/session/session.py", line 253, in __keyring_load_session
    keyring_data_user = ExecutionEnvironment().keyring[
  File "/nix/store/fj2ihsvcv6naa1w25dnsrxpha91dvi8p-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 32, in __getitem__
    raise exceptions.KeyringError(e)
protonvpn_nm_lib.exceptions.KeyringError: name 'dbus' is not defined
```

**Comment by dysinger** [comment]
I've also hit this. dbus needs to be included in protonvpn's dependencies.

**Comment by WolfangAukang** [comment]
@Obikawa I see you are using an outdated version of `protonvpn-gui` (#172939 should deal with the Python `dbus` library and #174968 deals with the version bump). Can you please try it from unstable to see if the issue still persists?

**Comment by rhoriguchi** [comment]
> @Obikawa I see you are using an outdated version of `protonvpn-gui` (#172939 should deal with the Python `dbus` library and #174968 deals with the version bump). Can you please try it from unstable to see if the issue still persists?

So I've upgrade to the latest unstable release and it works again.

**Comment by dysinger** [comment]
Me too. Thank you.

------- Original Message -------

**Comment by ScottFreeCode** [comment]
Any chance of this getting backported to Nixos 22.05? It seems to affect the CLI also.

**Comment by WolfangAukang** [comment]
> Any chance of this getting backported to Nixos 22.05? It seems to affect the CLI also.

I'm backporting the new releases

**Comment by wolfsprite** [comment]
Any update on this? Just installed on 22.05 and ran into the exact same issue.

**Comment by WolfangAukang** [comment]
> but a little perturbed that I needed to switch from stable to unstable in order for a default package to function properly..

This hasn't been backported yet (#177312).

**Comment by zeorin** [comment]
@wolfsprite there's no need to change your default channel to unstable just to use a single (or a few) packages from unstable: https://nixos.wiki/wiki/FAQ#How_can_I_install_a_package_from_unstable_while_remaining_on_the_stable_channel.3F
