### ISSUE TITLE
aws-workspaces: Couldn't find a valid ICU package installed on the system.

### ISSUE THREAD

**Issue by boozedog** [NixOS/nixpkgs#176260]
### Describe the bug
```console
$ workspacesclient 
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.TimeZoneInfo.GetDisplayName(TimeZoneDisplayNameType, System.String ByRef)
   at System.TimeZoneInfo..ctor(Byte[], System.String, Boolean)
   at System.TimeZoneInfo.GetTimeZoneFromTzData(Byte[], System.String)
   at System.TimeZoneInfo.GetLocalTimeZoneFromTzFile()
   at System.TimeZoneInfo+CachedData.CreateLocal()
   at System.CurrentSystemTimeZone..ctor()
   at System.TimeZone.get_CurrentTimeZone()
   at GLib.Marshaller..cctor()
   at GLib.Marshaller.StringToPtrGStrdup(System.String)
   at GLib.Global.set_ProgramName(System.String)
   at Gtk.Application.SetPrgname()
   at Gtk.Application.Init()
   at WorkSpacesClient.Gtk.Program.Initialize()
   at WorkSpacesClient.Gtk.Program.Main(System.String[])
```

### Steps To Reproduce
run workspacesclient

### Expected behavior
I expected workspacesclient to start

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers
@mausch

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-21.11, nixos-unstable"`
 - channels(******): `"nixos-21.11.337605.43538dfb5d6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mausch** [comment]
Workaround:

`NIXPKGS_ALLOW_UNFREE=1 nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/21.11.tar.gz -p aws-workspaces --run workspacesclient`

**Comment by boozedog** [comment]
@mausch that workaround is working for me.

Any idea when your pull request might get merged? I'm not familiar with the process/workflow.

**Comment by mausch** [comment]
@boozedog  I don't have commit access, can't say really.
Sometimes it takes just days, sometimes it takes months.

**Comment by jiegec** [comment]
I am bumping aws-workspaces at pr #180854 with the fix from @mausch applied.
