### ISSUE TITLE
Protonvpn-cli don't connect

### ISSUE THREAD

**Issue by ajmasia** [NixOS/nixpkgs#178563]
### Describe the bug
Imposible connect to vpn

### Steps To Reproduce
1. install the package with home-manager 
2. log in your proton account
3. try to connect

### Expected behavior
Connect to a vpn 

### Additional context
Version: Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.10.0; proton-client v0.7.1)
Log error:
```python
Traceback (most recent call last):
  File "/nix/store/asmmczxwib8fkmnhyidrl7wfl0dzk57g-protonvpn-cli-3.12.0/lib/python3.9/site-packages/protonvpn_cli/cli_wrapper.py", line 277, in connect
    self.protonvpn.setup_connection(
  File "/nix/store/5scz60rbyq5zazgb8476wxvcw7s5q49i-python3.9-protonvpn-nm-lib-3.10.0/lib/python3.9/site-packages/protonvpn_nm_lib/api.py", line 158, in setup_connection
    self._env.connection_backend.setup(**data)
  File "/nix/store/5scz60rbyq5zazgb8476wxvcw7s5q49i-python3.9-protonvpn-nm-lib-3.10.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client.py", line 81, in setup
    self._pre_setup_connection(kwargs.get("entry_ip"))
  File "/nix/store/5scz60rbyq5zazgb8476wxvcw7s5q49i-python3.9-protonvpn-nm-lib-3.10.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client.py", line 233, in _pre_setup_connection
    ipv6_lp.manage(KillSwitchActionEnum.ENABLE)
  File "/nix/store/5scz60rbyq5zazgb8476wxvcw7s5q49i-python3.9-protonvpn-nm-lib-3.10.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/killswitch/ipv6_leak_protection.py", line 62, in manage
    self.add_leak_protection()
  File "/nix/store/5scz60rbyq5zazgb8476wxvcw7s5q49i-python3.9-protonvpn-nm-lib-3.10.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/killswitch/ipv6_leak_protection.py", line 100, in add_leak_protection
    self.run_subprocess(
  File "/nix/store/5scz60rbyq5zazgb8476wxvcw7s5q49i-python3.9-protonvpn-nm-lib-3.10.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/killswitch/ipv6_leak_protection.py", line 178, in run_subprocess
    raise exception(exception_msg)
protonvpn_nm_lib.exceptions.EnableIPv6LeakProtectionError: Unable to add IPv6 leak protection connection/interface
```
### Notify maintainers
@wolfangaukang

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.93, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(ajmasia): `"home-manager-21.11, unstable-22.11pre386147.e0a42267f73"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by WolfangAukang** [comment]
I cannot reproduce this and AFAIK it doesn't look related to the packaging, I'd rather open a ticket with protonvpn-nm-lib to see the reason why this is getting triggered.

**Comment by andreystepanov** [comment]
Having the same issue on NixOS.

I can't figure out if it's related to specific user network configuration in NixOS or lack of some dependencies needed for `protonvpn` to work properly.

@ajmasia Have you found a solution?

**Comment by andreystepanov** [comment]
Adding user to `networkmanager` group fixed the issue for me.

Here’s NixOS [documentation](https://search.nixos.org/options?channel=22.05&show=networking.networkmanager.enable&from=0&size=50&sort=relevance&type=packages&query=Networkmanager).

@ajmasia give it a try!

**Comment by WolfangAukang** [comment]
@andreystepanov that makes sense. I already insert my user on that group (although the reason is unrelated to `protonvpn`), that's why I was not able to reproduce this. Unfortunately, I'm not sure if adding this kind of option is possible on the packaging.

**Comment by rikhuijzer** [comment]
> Adding user to `networkmanager` group fixed the issue for me.
> 
> Here’s NixOS [documentation](https://search.nixos.org/options?channel=22.05&show=networking.networkmanager.enable&from=0&size=50&sort=relevance&type=packages&query=Networkmanager).
> 
> @ajmasia give it a try!

Thanks! Worked for me after I also enabled networkmanager (only adding to group was not enough; which makes sense):
```
networking.networkmanager.enable = true;
```

**Comment by ajmasia** [comment]
Sorry @andreystepanov but I stopped using protonvpn and have not tried it again :blush:

**Comment by WolfangAukang** [comment]
FYI, there is an issue on the official repo regarding this https://github.com/ProtonVPN/linux-app/issues/46#issuecomment-1667908465. Honestly, it looks like a very random issue, because I remember having it after upgrading protonvpn once, but it started working a few days later.

**Comment by Atemu** [comment]
The upstream projects have been abandoned, this is no longer recent.
