### ISSUE TITLE
pythonPackages.skia-pathops: build failure on darwin (x86_64)

### ISSUE THREAD

**Issue by dbaynard** [NixOS/nixpkgs#179200]
### Steps To Reproduce

1.   `nix build -f'<nixpkgs>' nixpkgs-x86_64.pythonPackages.skia-pathops`
    (I'm building on an m1 mac so I have to use the `x86_64` package set, i.e. nixpkgs imported with `localSystem = "x86_64-darwin"`).

The error (at this stage) looks like a problem with `skia` using `xcrun` to try to find xcode paths? I’m guessing this wasn’t tested on darwin?

### Build log

From `nix log`

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing setuptools-check-hook
Using setuptoolsCheckPhase
Sourcing pytest-check-hook
Using pytestCheckPhase
Removing setuptoolsCheckPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/q47fhlfbbfy2g6j4j8spxmpzc15ap57l-skia-pathops-0.7.2.zip
source root is skia-pathops-0.7.2
setting SOURCE_DATE_EPOCH to timestamp 1638291634 of file skia-pathops-0.7.2/src/python/skia_pathops.egg-info/top_level.txt
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing setuptoolsBuildPhase
running bdist_wheel
running build
running build_py
creating build
creating build/lib.macosx-10.12-x86_64-3.10
creating build/lib.macosx-10.12-x86_64-3.10/pathops
copying src/python/pathops/_version.py -> build/lib.macosx-10.12-x86_64-3.10/pathops
copying src/python/pathops/__init__.py -> build/lib.macosx-10.12-x86_64-3.10/pathops
copying src/python/pathops/operations.py -> build/lib.macosx-10.12-x86_64-3.10/pathops
running build_ext
Compiling src/python/pathops/_pathops.pyx because it changed.
[1/1] Cythonizing src/python/pathops/_pathops.pyx
warning: src/python/pathops/_pathops.pxd:214:6: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
warning: src/python/pathops/_pathops.pxd:216:6: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
warning: src/python/pathops/_pathops.pyx:687:6: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
warning: src/python/pathops/_pathops.pyx:696:6: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
building 'pathops._pathops' extension
creating build/temp.macosx-10.12-x86_64-3.10
creating build/temp.macosx-10.12-x86_64-3.10/src
creating build/temp.macosx-10.12-x86_64-3.10/src/python
creating build/temp.macosx-10.12-x86_64-3.10/src/python/pathops
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Isrc/cpp/skia-builder/skia -Isrc/cpp/skia-builder/skia/src -I/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/include/python3.10 -c src/python/pathops/_pathops.cpp -o build/temp.macosx-10.12-x86_64-3.10/src/python/pathops/_pathops.o -std=c++14 -stdlib=libc++ -mmacosx-version-min=10.9
clang-11: [0;1;35mwarning: [0margument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument][0m
building 'skia' library
[31m[1mERROR [0mat //gn/skia/BUILD.gn:44:7: Script returned non-zero exit code.
[2m      exec_script("../find_xcode_sysroot.py", [ "macosx" ], "trim string")
[0m[34m[1m      ^----------
[0mCurrent dir: /private/tmp/nix-build-python3.10-skia-pathops-0.7.2.drv-0/skia-pathops-0.7.2/build/temp.macosx-10.12-x86_64-3.10/src/cpp/skia-builder/skia/
Command: python /private/tmp/nix-build-python3.10-skia-pathops-0.7.2.drv-0/skia-pathops-0.7.2/src/cpp/skia-builder/skia/gn/find_xcode_sysroot.py macosx
Returned 1.
stderr:

Traceback (most recent call last):
  File "/private/tmp/nix-build-python3.10-skia-pathops-0.7.2.drv-0/skia-pathops-0.7.2/src/cpp/skia-builder/skia/gn/find_xcode_sysroot.py", line 15, in <module>
    print(subprocess.check_output(['xcrun', '--sdk', sdk, '--show-sdk-path']).decode())
  File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xcrun'

See //gn/BUILDCONFIG.gn:175:3: which caused the file to be included.
[2m  "//gn/skia:default",
[0m[34m[1m  ^------------------
[0mTraceback (most recent call last):
  File "/private/tmp/nix-build-python3.10-skia-pathops-0.7.2.drv-0/skia-pathops-0.7.2/src/cpp/skia-builder/build_skia.py", line 238, in <module>
    build_skia(
  File "/private/tmp/nix-build-python3.10-skia-pathops-0.7.2.drv-0/skia-pathops-0.7.2/src/cpp/skia-builder/build_skia.py", line 146, in build_skia
    subprocess.check_call(
  File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/jrqchdlx5m3pw2jq9gii0yjgzmsqgddj-gn-unstable-2020-03-09/bin/gn', 'gen', '/private/tmp/nix-build-python3.10-skia-pathops-0.7.2.drv-0/skia-pathops-0.7.2/build/temp.macosx-10.12-x86_64-3.10/src/cpp/skia-builder/skia', '--args=is_official_build=true is_debug=false skia_enable_pdf=false skia_enable_discrete_gpu=false skia_enable_skottie=false skia_enable_skshaper=false skia_use_dng_sdk=false skia_use_expat=false skia_use_freetype=false skia_use_fontconfig=false skia_use_fonthost_mac=false skia_use_harfbuzz=false skia_use_icu=false skia_use_libgifcodec=false skia_use_libjpeg_turbo_encode=false skia_use_libjpeg_turbo_decode=false skia_use_libpng_encode=false skia_use_libpng_decode=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_piex=false skia_use_sfntly=false skia_use_xps=false skia_use_zlib=false skia_enable_spirv_validation=false skia_use_libheif=false skia_use_lua=false skia_enable_fontmgr_empty=true skia_enable_gpu=false skia_use_gl=false']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/private/tmp/nix-build-python3.10-skia-pathops-0.7.2.drv-0/skia-pathops-0.7.2/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 409, in <module>
    setup(**setup_params)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/nix/store/fav57wk0ky518b95b5pmbav5yi7nkpc2-python3.10-wheel-0.37.1/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 216, in run
    build_ext.run(self)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/nix/store/i6r7w83zlzyxm0nni183ds12p699r11f-python3.10-Cython-0.29.28/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/nix/store/i6r7w83zlzyxm0nni183ds12p699r11f-python3.10-Cython-0.29.28/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 193, in build_extension
    libraries=self.get_libraries(ext),
  File "setup.py", line 210, in get_libraries
    library_dir = self._library_builders[library](self.build_temp)
  File "setup.py", line 279, in build_skia
    subprocess.run(build_cmd, check=True, env=env)
  File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/bin/python3.10', 'src/cpp/skia-builder/build_skia.py', '--no-fetch-gn', '--no-virtualenv', '--gn-path', '/nix/store/jrqchdlx5m3pw2jq9gii0yjgzmsqgddj-gn-unstable-2020-03-09/bin/gn', 'build/temp.macosx-10.12-x86_64-3.10/src/cpp/skia-builder/skia', '--no-sync-deps']' returned non-zero exit status 1.
```

### Additional context

Output of `nix show-derivation`

<details>

```json
{
  "/nix/store/y528i53vd37jbbhbkycr466jhxvwm5gn-python3.10-skia-pathops-0.7.2.drv": {
    "outputs": {
      "out": {
        "path": "/nix/store/s9ihbxlvkqg8r15pgsz6z7jx98g3c506-python3.10-skia-pathops-0.7.2"
      }
    },
    "inputSrcs": [
      "/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh"
    ],
    "inputDrvs": {
      "/nix/store/0c88s0qw914wbsyxg1ip9sphrgwnqyha-python3.10-setuptools-61.2.0.drv": [
        "out"
      ],
      "/nix/store/31zshn6rrydf4m595q8symmjrznr4vbr-python3.10-setuptools-scm-6.4.2.drv": [
        "out"
      ],
      "/nix/store/3iwmvadl71fnd4zgh7x9rdygg4vngp9w-python3-3.10.4.drv": [
        "out"
      ],
      "/nix/store/3sb45366833bbqdsnprhr8jc28kaxcn0-gn-unstable-2020-03-09.drv": [
        "out"
      ],
      "/nix/store/6021hyb88fkpg5wlr1fh43kadcws9lbf-pip-install-hook.drv": [
        "out"
      ],
      "/nix/store/6nq3m25bgkigd45pv1gl2gili44mrqaj-setuptools-setup-hook.drv": [
        "out"
      ],
      "/nix/store/8pdapl20axxvz086agd09wnpsbaijqwa-skia-pathops-0.7.2.zip.drv": [
        "out"
      ],
      "/nix/store/b7n1x9xznvxn9kxijiznmqvmlz02l2x4-bash-5.1-p16.drv": [
        "out"
      ],
      "/nix/store/ccylh7pibp8yclnfd7vb1x1x5q9lrxd0-pytest-check-hook.drv": [
        "out"
      ],
      "/nix/store/fxrdhjzz5981yqn7pi07f7kg4pd0qfbv-unzip-6.0.drv": [
        "out"
      ],
      "/nix/store/fzhgkdbywnrkpk3m543jh6y8nm6j40ig-python-catch-conflicts-hook.drv": [
        "out"
      ],
      "/nix/store/g6syv1lmmrm4l6kjvn8pc3iwj9dhjvzl-python-imports-check-hook.sh.drv": [
        "out"
      ],
      "/nix/store/gli35a49l3nmiq3hrv2pa4j555cbfi8z-stdenv-darwin.drv": [
        "out"
      ],
      "/nix/store/i7h5wvlpqz6550sm6rmjbhx6qi56c2n1-setuptools-check-hook.drv": [
        "out"
      ],
      "/nix/store/jj9vmx58a63fscwkbc2zmbgcs2bn5n0j-python-namespaces-hook.sh.drv": [
        "out"
      ],
      "/nix/store/kb9077lzgyxdhh8ikcidlh8n2hf5vkm7-ninja-1.10.2.drv": [
        "out"
      ],
      "/nix/store/s0dd832yqsg631xhc6kmaj39wzrbyl37-python-remove-bin-bytecode-hook.drv": [
        "out"
      ],
      "/nix/store/sc2ilyb3wgj40x01vfnwsqkkqynbdw97-python3.10-Cython-0.29.28.drv": [
        "out"
      ],
      "/nix/store/sg028xa8l1sk52lb7k0m3f48km80qljl-python-remove-tests-dir-hook.drv": [
        "out"
      ],
      "/nix/store/vvi9cc9lii2rg381959178sdm9czc1ym-hook.drv": [
        "out"
      ],
      "/nix/store/w2drw5l3p9mgy4zbd8vgx49rb9jc0422-hook.drv": [
        "out"
      ]
    },
    "system": "x86_64-darwin",
    "builder": "/nix/store/pdxssx119jci61a1ixs9k2md6wqyq6fx-bash-5.1-p16/bin/bash",
    "args": [
      "-e",
      "/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh"
    ],
    "env": {
      "LANG": "en_US.UTF-8",
      "__darwinAllowLocalNetworking": "",
      "__impureHostDeps": "/bin/sh /usr/lib/libSystem.B.dylib /usr/lib/system/libunc.dylib /dev/zero /dev/random /dev/urandom /bin/sh",
      "__propagatedImpureHostDeps": "",
      "__propagatedSandboxProfile": "",
      "__sandboxProfile": "",
      "buildInputs": "",
      "builder": "/nix/store/pdxssx119jci61a1ixs9k2md6wqyq6fx-bash-5.1-p16/bin/bash",
      "configureFlags": "",
      "depsBuildBuild": "",
      "depsBuildBuildPropagated": "",
      "depsBuildTarget": "",
      "depsBuildTargetPropagated": "",
      "depsHostHost": "",
      "depsHostHostPropagated": "",
      "depsTargetTarget": "",
      "depsTargetTargetPropagated": "",
      "disallowedReferences": "",
      "doCheck": "",
      "doInstallCheck": "1",
      "name": "python3.10-skia-pathops-0.7.2",
      "nativeBuildInputs": "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4 /nix/store/cmv5b73qyhk56gqq4hanmp023z410anx-hook /nix/store/9jr9fhplbmk906g97vzz83wyrm0a8vfj-hook /nix/store/wc6z375cg01pyfnmjbchn9lvl62pfa5b-python-remove-tests-dir-hook /nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0 /nix/store/95j5d8vbncjkrzkll31pydwnwssl4n0j-python-catch-conflicts-hook /nix/store/h01fwgvl8kkpyv1nn11mlsv0dk0qgazz-python-remove-bin-bytecode-hook /nix/store/zjh1140lf4ns00br16jd8jyy5nqplvic-unzip-6.0 /nix/store/9p7ki48lp5gkdq2qdnwayj33sbl7lp9a-setuptools-setup-hook /nix/store/sziwzi4r8xxj7hfwfcwxsjkgpq7hg9hw-pip-install-hook /nix/store/vwhg7zlf6dcap67lhnc1gap4fb517qf9-python-imports-check-hook.sh /nix/store/89jpcrdzkg2n3jfbakhfg3jk46h899hp-python-namespaces-hook.sh /nix/store/i6r7w83zlzyxm0nni183ds12p699r11f-python3.10-Cython-0.29.28 /nix/store/l1ximzfkw0cqq48jfc158isylhcq8yij-ninja-1.10.2 /nix/store/zycjm40yqd8n8xsfnfxxr5fds1p4jqab-python3.10-setuptools-scm-6.4.2 /nix/store/zwjs23iiszw30z64hjs3m0hh88h79p65-setuptools-check-hook /nix/store/3j199qq1vijm25s9ka8pq1f98439hjny-pytest-check-hook",
      "out": "/nix/store/s9ihbxlvkqg8r15pgsz6z7jx98g3c506-python3.10-skia-pathops-0.7.2",
      "outputs": "out",
      "patches": "",
      "pname": "skia-pathops",
      "postFixup": "wrapPythonPrograms\n",
      "postPatch": "substituteInPlace setup.py \\\n  --replace \"build_cmd = [sys.executable, build_skia_py, build_dir]\" \\\n    'build_cmd = [sys.executable, build_skia_py, \"--no-fetch-gn\", \"--no-virtualenv\", \"--gn-path\", \"/nix/store/jrqchdlx5m3pw2jq9gii0yjgzmsqgddj-gn-unstable-2020-03-09/bin/gn\", build_dir]'\n",
      "propagatedBuildInputs": "/nix/store/3fnlpnmgrjmnqgbr56n4kgcp31fsv2vd-python3.10-setuptools-61.2.0 /nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4",
      "propagatedNativeBuildInputs": "",
      "pythonImportsCheck": "pathops",
      "src": "/nix/store/q47fhlfbbfy2g6j4j8spxmpzc15ap57l-skia-pathops-0.7.2.zip",
      "stdenv": "/nix/store/rpjs47r3rv30y15vs58cmz4y27vfzd5d-stdenv-darwin",
      "strictDeps": "1",
      "system": "x86_64-darwin",
      "version": "0.7.2"
    }
  }
}
```

</details>

### Notify maintainers

@barinov274 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.5.0, macOS 12.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixpkgs-21.11pre300649.3e0ce8c5d47"`
 - nixpkgs: `/nix/store/kwf3lras72i27gsschvzdxlx402yaxhx-nixpkgs`

```

**Comment by dbaynard** [comment]
My workaround was to add an override to my `pythonPackages` to set `doInstallCheck = false` on `fonttools`. But yes, fixing `skia-pathops` to work on darwin is 👍 .

**Comment by siraben** [comment]
This also affects home-manager fonts.

**Comment by wegank** [comment]
The issue [seems to be gone](https://hydra.nixos.org/job/nixpkgs/trunk/python310Packages.skia-pathops.x86_64-darwin/all).
