### ISSUE TITLE
python310Packages.unrardll fails on darwin

### ISSUE THREAD

**Issue by viraptor** [NixOS/nixpkgs#179271]
### Steps To Reproduce
1. build `python310Packages.unrardll`

### Build log
```
...
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: unrardll
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/syr9np63cdhpfvv8vawzrl13w70zc8jk-python3-3.10.4/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/q14mby3jf85qci7z866fcr54k56q5j2h-python3.10-unrardll-0.1.5/lib/python3.10/site-packages/unrardll/__init__.py", line 14, in <module>
    from . import unrar
ImportError: dlopen(/nix/store/q14mby3jf85qci7z866fcr54k56q5j2h-python3.10-unrardll-0.1.5/lib/python3.10/site-packages/unrardll/unrar.cpython-310-darwin.so, 0x0002): Library not loaded: libunrar.so
  Referenced from: /nix/store/q14mby3jf85qci7z866fcr54k56q5j2h-python3.10-unrardll-0.1.5/lib/python3.10/site-packages/unrardll/unrar.cpython-310-darwin.so
  Reason: tried: 'libunrar.so' (no such file), '/usr/local/lib/libunrar.so' (no such file), '/usr/lib/libunrar.so' (no such file), '/nix/store/q14mby3jf85qci7z866fcr54k56q5j2h-python3.10-unrardll-0.1.5/libunrar.so' (no such file), '/usr/local/lib/libunrar.so' (no such file), '/usr/lib/libunrar.so' (no such file)
```

### Additional context
Happens on intel darwin.

### Notify maintainers
@nyanloutre

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.1`
 - channels(viraptor): `"home-manager-21.11.tar.gz, nixpkgs-22.05-darwin"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/viraptor/.nix-defexpr/channels/nixpkgs`
```

**Comment by jiegec** [comment]
The .so dependency should be fixed up:

```
/nix/store/k7zjjagwjz6m9lfb87i8457a17didyqq-python3.10-unrardll-0.1.5/lib/python3.10/site-packages/unrardll/unrar.cpython-310-darwin.so:
        libunrar.so (compatibility version 0.0.0, current version 0.0.0)
        /nix/store/1mxqsldzckyjw8a43fbcrkmjd0isc206-libcxx-11.1.0/lib/libc++.1.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```
