### ISSUE TITLE
Cannot restore VM snapshots with virt-manager and qemu 7.0.0

### ISSUE THREAD

**Issue by cheriimoya** [NixOS/nixpkgs#179692]
### Describe the bug

Whenever I'm trying to restore a snapshot of any VM with virt-manager, I get the error shown in screenshot (1).
In screenshot (1), 1 is the way I am trying to restore a snapshot (a simple right click and then "start snapshot"), 2 is the error I am getting and 3 is the following error message:
<details>
<pre>
Error running snapshot 'seems_to_work_now': internal error: qemu unexpectedly closed the monitor: qxl_send_events: spice-server bug: guest stopped, ignoring
2022-06-30T08:54:38.181304Z qemu-system-x86_64: warning: usb-redir connection broken during migration

2022-06-30T08:54:38.181368Z qemu-system-x86_64: usbredirparser: unserialization must use a pristine parser
2022-06-30T08:54:38.181374Z qemu-system-x86_64: Failed to load usb-redir:parser
2022-06-30T08:54:38.181379Z qemu-system-x86_64: error while loading state for instance 0x0 of device '0000:00:02.1:00.0/2/usb-redir'
2022-06-30T08:54:38.184475Z qemu-system-x86_64: Error -1 while loading VM state

Traceback (most recent call last):
  File "/nix/store/vdkdj6x9ghk73hjcpmzg5qrc5p20wq7n-virt-manager-4.0.0/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/nix/store/vdkdj6x9ghk73hjcpmzg5qrc5p20wq7n-virt-manager-4.0.0/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/nix/store/vdkdj6x9ghk73hjcpmzg5qrc5p20wq7n-virt-manager-4.0.0/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/nix/store/vdkdj6x9ghk73hjcpmzg5qrc5p20wq7n-virt-manager-4.0.0/share/virt-manager/virtManager/object/domain.py", line 1167, in revert_to_snapshot
    self._backend.revertToSnapshot(snap.get_backend())
  File "/nix/store/7l0pbxfyznl7kghi6snmcaryrpb1cya1-python3.9-libvirt-8.1.0/lib/python3.9/site-packages/libvirt.py", line 2396, in revertToSnapshot
    raise libvirtError('virDomainRevertToSnapshot() failed')
libvirt.libvirtError: internal error: qemu unexpectedly closed the monitor: qxl_send_events: spice-server bug: guest stopped, ignoring
2022-06-30T08:54:38.181304Z qemu-system-x86_64: warning: usb-redir connection broken during migration

2022-06-30T08:54:38.181368Z qemu-system-x86_64: usbredirparser: unserialization must use a pristine parser
2022-06-30T08:54:38.181374Z qemu-system-x86_64: Failed to load usb-redir:parser
2022-06-30T08:54:38.181379Z qemu-system-x86_64: error while loading state for instance 0x0 of device '0000:00:02.1:00.0/2/usb-redir'
2022-06-30T08:54:38.184475Z qemu-system-x86_64: Error -1 while loading VM state
</pre>
</details>

I searched around and I found a patch that fixes this problem for me.
If I apply [this patch](https://github.com/utmapp/UTM/commit/aef143bee75b4cedf1f9553ffe8d9138e3ab2eaf) and rebuild my system, everything works as expected.
If someone else can confirm this is an actual bug, I'd be happy to submit a PR.

### Steps To Reproduce
1. Have `[virt-manager](https://search.nixos.org/packages?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=virt-manager)` in your packages and `[virtualisation.libvirtd.enable](https://search.nixos.org/options?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=libvirt)` in configuration.nix.
2. Install any VM (you don't really have to install it all the way through, actually, you can simply start an empty VM)
3. Create a snapshot
4. Try to restore the snapshot you just created

Here is an animated version:
![qemu-bug](https://user-images.githubusercontent.com/28303440/176642560-fdd153ce-2ff9-4a0a-841c-ec9d3dd3a482.gif)

### Expected behavior

Restore the snapshot cleanly as seen in the following gif:
![qemu-no-bug](https://user-images.githubusercontent.com/28303440/176644690-1e993326-fe4d-47a9-a91a-7061f37eac7b.gif)

### Screenshots
screenshot (1): 
![image](https://user-images.githubusercontent.com/28303440/176636942-c020655d-8988-4c61-9c17-f70d04edabea.png)

### Additional context

Sorry about the gif quality.

**Comment by Artturin** [comment]
Ping the maintainers

**Comment by ajs124** [comment]
Meanwhile, the patch you linked made it to qemu master: https://github.com/qemu/qemu/commit/0631d4b448454ae8a1ab091c447e3f71ab6e088a

**Comment by cheriimoya** [comment]
on 22.11 now
