### ISSUE TITLE
Patching docker dependency of aws-sam-cli 1.52.0 forces docker to be present

### ISSUE THREAD

**Issue by chriswarbo** [NixOS/nixpkgs#179708]
### Describe the bug

The `aws-sam-cli` application depends on the `docker` Python package, version 4.2.0; but its package in nixpkgs relaxes this bound to `>= 4.2.0`, in order to use `python3Packages.docker`.

The latest versions of these in nixpkgs are aws-sam-cli version 1.52.0 and python3Packages.docker version 5.0.3 (exact commit ID given below). This combination makes the `sam` command crash if it can't connect to docker; even for commands which don't use/need docker at all.

### Steps To Reproduce

Make sure there's no `DOCKER_HOST` env var set, and that `/var/run/docker.sock` doesn't exist.

We *do not* need any AWS account/credentials to reproduce this error. We do need a file named `template.yaml`, this is the one I've been using to test:
 
```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test SAM CLI
Resources:
  TestInlineFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Test function defined via InlineCode
      PackageType: Zip
      Handler: index.handler
      InlineCode: |
        exports.handler = async (event) => {
          return {
            statusCode: 200,
            body: '"Test success"'
          };
        }

      MemorySize: 512
      Runtime: nodejs16.x
      Timeout: 30
      FunctionUrlConfig:
        AuthType: AWS_IAM
```

Here's a command to reproduce the error:

```console
nix-shell -p '(import (builtins.fetchTarball {
  name = "nixpkgs-sam-breakage";
  url = "https://github.com/nixos/nixpkgs/archive/b1cc6afe11cd643797cdf79168e0cd709eba164b.tar.gz";
  sha256 = "sha256-T0XIkF0lpS1MuZDXDtoTeyguqz9O7qSy3itRcrrcqrI=";
}) {}).aws-sam-cli' --run 'sam package --template template.yaml'
```

Running the above command will fail, since the `docker` library provided by Nixpkgs will try connecting to docker at the socket `/var/run/docker.sock` (which doesn't exist):

<details>
  <summary>Output, including backtraces</summary>

  ```console
    /nix/store/s3b6zh5m6p78k8s3wnjcqjwjyysl3igh-python3.10-watchdog-2.1.8/lib/python3.10/site-packages/watchdog/observers/__init__.py:71: UserWarning: Failed to import fsevents. Fall back to kqueue
    warnings.warn("Failed to import fsevents. Fall back to kqueue")
  Traceback (most recent call last):
    File "/nix/store/z3f7pazs4im5xmkhr15qh00x5jxqikl1-python3.10-urllib3-1.26.9/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
      httplib_response = self._make_request(
    File "/nix/store/z3f7pazs4im5xmkhr15qh00x5jxqikl1-python3.10-urllib3-1.26.9/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
      conn.request(method, url, **httplib_request_kw)
    File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/http/client.py", line 1282, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/http/client.py", line 1328, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/http/client.py", line 1277, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/http/client.py", line 1037, in _send_output
      self.send(msg)
    File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/http/client.py", line 975, in send
      self.connect()
    File "/nix/store/h6bnvah6a89y0rsxgmy28djg56x11fn2-python3.10-docker-5.0.3/lib/python3.10/site-packages/docker/transport/unixconn.py", line 30, in connect
      sock.connect(self.unix_socket)
  FileNotFoundError: [Errno 2] No such file or directory
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/nix/store/c7nvhj5bbl44n9zyxwp6rv5i2k9iaqps-python3.10-requests-2.27.1/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
      resp = conn.urlopen(
    File "/nix/store/z3f7pazs4im5xmkhr15qh00x5jxqikl1-python3.10-urllib3-1.26.9/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
      retries = retries.increment(
    File "/nix/store/z3f7pazs4im5xmkhr15qh00x5jxqikl1-python3.10-urllib3-1.26.9/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
      raise six.reraise(type(error), error, _stacktrace)
    File "/nix/store/z3f7pazs4im5xmkhr15qh00x5jxqikl1-python3.10-urllib3-1.26.9/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
      raise value.with_traceback(tb)
    File "/nix/store/z3f7pazs4im5xmkhr15qh00x5jxqikl1-python3.10-urllib3-1.26.9/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
      httplib_response = self._make_request(
    File "/nix/store/z3f7pazs4im5xmkhr15qh00x5jxqikl1-python3.10-urllib3-1.26.9/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
      conn.request(method, url, **httplib_request_kw)
    File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/http/client.py", line 1282, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/http/client.py", line 1328, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/http/client.py", line 1277, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/http/client.py", line 1037, in _send_output
      self.send(msg)
    File "/nix/store/s3xwz0p7ng23dn2ixhksrdgs3gmq8fbg-python3-3.10.4/lib/python3.10/http/client.py", line 975, in send
      self.connect()
    File "/nix/store/h6bnvah6a89y0rsxgmy28djg56x11fn2-python3.10-docker-5.0.3/lib/python3.10/site-packages/docker/transport/unixconn.py", line 30, in connect
      sock.connect(self.unix_socket)
  urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/nix/store/h6bnvah6a89y0rsxgmy28djg56x11fn2-python3.10-docker-5.0.3/lib/python3.10/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
      return self.version(api_version=False)["ApiVersion"]
    File "/nix/store/h6bnvah6a89y0rsxgmy28djg56x11fn2-python3.10-docker-5.0.3/lib/python3.10/site-packages/docker/api/daemon.py", line 181, in version
      return self._result(self._get(url), json=True)
    File "/nix/store/h6bnvah6a89y0rsxgmy28djg56x11fn2-python3.10-docker-5.0.3/lib/python3.10/site-packages/docker/utils/decorators.py", line 46, in inner
      return f(self, *args, **kwargs)
    File "/nix/store/h6bnvah6a89y0rsxgmy28djg56x11fn2-python3.10-docker-5.0.3/lib/python3.10/site-packages/docker/api/client.py", line 237, in _get
      return self.get(url, **self._set_request_timeout(kwargs))
    File "/nix/store/c7nvhj5bbl44n9zyxwp6rv5i2k9iaqps-python3.10-requests-2.27.1/lib/python3.10/site-packages/requests/sessions.py", line 542, in get
      return self.request('GET', url, **kwargs)
    File "/nix/store/c7nvhj5bbl44n9zyxwp6rv5i2k9iaqps-python3.10-requests-2.27.1/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
      resp = self.send(prep, **send_kwargs)
    File "/nix/store/c7nvhj5bbl44n9zyxwp6rv5i2k9iaqps-python3.10-requests-2.27.1/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
      r = adapter.send(request, **kwargs)
    File "/nix/store/c7nvhj5bbl44n9zyxwp6rv5i2k9iaqps-python3.10-requests-2.27.1/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
      raise ConnectionError(err, request=request)
  requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/nix/store/1h93h1wwi0ywhigk9kql39db2d8i2bqa-aws-sam-cli-1.52.0/bin/.sam-wrapped", line 9, in <module>
      sys.exit(cli())
    File "/nix/store/3pb6xldnzjchay7nmk3yh6p9rrcrcfmy-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/nix/store/3pb6xldnzjchay7nmk3yh6p9rrcrcfmy-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/nix/store/3pb6xldnzjchay7nmk3yh6p9rrcrcfmy-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/nix/store/3pb6xldnzjchay7nmk3yh6p9rrcrcfmy-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/nix/store/3pb6xldnzjchay7nmk3yh6p9rrcrcfmy-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/nix/store/1h93h1wwi0ywhigk9kql39db2d8i2bqa-aws-sam-cli-1.52.0/lib/python3.10/site-packages/samcli/lib/cli_validation/image_repository_validation.py", line 92, in wrapped
      return func(*args, **kwargs)
    File "/nix/store/3pb6xldnzjchay7nmk3yh6p9rrcrcfmy-python3.10-click-8.1.3/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
      return ctx.invoke(f, obj, *args, **kwargs)
    File "/nix/store/3pb6xldnzjchay7nmk3yh6p9rrcrcfmy-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/nix/store/1h93h1wwi0ywhigk9kql39db2d8i2bqa-aws-sam-cli-1.52.0/lib/python3.10/site-packages/samcli/lib/telemetry/metric.py", line 166, in wrapped
      raise exception  # pylint: disable=raising-bad-type
    File "/nix/store/1h93h1wwi0ywhigk9kql39db2d8i2bqa-aws-sam-cli-1.52.0/lib/python3.10/site-packages/samcli/lib/telemetry/metric.py", line 124, in wrapped
      return_value = func(*args, **kwargs)
    File "/nix/store/1h93h1wwi0ywhigk9kql39db2d8i2bqa-aws-sam-cli-1.52.0/lib/python3.10/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
      actual_result = func(*args, **kwargs)
    File "/nix/store/1h93h1wwi0ywhigk9kql39db2d8i2bqa-aws-sam-cli-1.52.0/lib/python3.10/site-packages/samcli/lib/telemetry/metric.py", line 88, in wrapped
      return func(*args, **kwargs)
    File "/nix/store/1h93h1wwi0ywhigk9kql39db2d8i2bqa-aws-sam-cli-1.52.0/lib/python3.10/site-packages/samcli/cli/main.py", line 87, in wrapper
      return func(*args, **kwargs)
    File "/nix/store/1h93h1wwi0ywhigk9kql39db2d8i2bqa-aws-sam-cli-1.52.0/lib/python3.10/site-packages/samcli/commands/_utils/cdk_support_decorators.py", line 38, in wrapped
      return func(*args, **kwargs)
    File "/nix/store/1h93h1wwi0ywhigk9kql39db2d8i2bqa-aws-sam-cli-1.52.0/lib/python3.10/site-packages/samcli/commands/package/command.py", line 109, in cli
      do_cli(
    File "/nix/store/1h93h1wwi0ywhigk9kql39db2d8i2bqa-aws-sam-cli-1.52.0/lib/python3.10/site-packages/samcli/commands/package/command.py", line 173, in do_cli
      package_context.run()
    File "/nix/store/1h93h1wwi0ywhigk9kql39db2d8i2bqa-aws-sam-cli-1.52.0/lib/python3.10/site-packages/samcli/commands/package/package_context.py", line 121, in run
      docker_client = docker.from_env()
    File "/nix/store/h6bnvah6a89y0rsxgmy28djg56x11fn2-python3.10-docker-5.0.3/lib/python3.10/site-packages/docker/client.py", line 96, in from_env
      return cls(
    File "/nix/store/h6bnvah6a89y0rsxgmy28djg56x11fn2-python3.10-docker-5.0.3/lib/python3.10/site-packages/docker/client.py", line 45, in __init__
      self.api = APIClient(*args, **kwargs)
    File "/nix/store/h6bnvah6a89y0rsxgmy28djg56x11fn2-python3.10-docker-5.0.3/lib/python3.10/site-packages/docker/api/client.py", line 197, in __init__
      self._version = self._retrieve_server_version()
    File "/nix/store/h6bnvah6a89y0rsxgmy28djg56x11fn2-python3.10-docker-5.0.3/lib/python3.10/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
      raise DockerException(
  docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
  ```
</details>

### Expected behavior

It works if we override the `aws-sam-cli` package to use version 4.2.0 of its `docker` dependency:

```console
nix-shell -p '(import (builtins.fetchTarball {
  name = "nixpkgs-sam-breakage";
  url = "https://github.com/nixos/nixpkgs/archive/b1cc6afe11cd643797cdf79168e0cd709eba164b.tar.gz";
  sha256 = "sha256-T0XIkF0lpS1MuZDXDtoTeyguqz9O7qSy3itRcrrcqrI=";
}) {}).aws-sam-cli.override (old: {
  python3 = old.python3.override {
    packageOverrides = pelf: puper: {
      docker = puper.docker.overridePythonAttrs (old: rec {
        version = "4.2.0";
        src = puper.fetchPypi {
          inherit version;
          inherit (old) pname;
          hash = "sha256-3a5mYgq19LznafZLzXk0+IDIq+aqUJhimNtWc10Pci4=";
        };
      });
    };
  };
})' --run 'sam package --template template.yaml'
```

In this case the command succeeds (outputting the contents of `template.yaml` in normalised form). There is still a warning from the `watchdog` library, but that is sent to stderr which is fine:

```console
/nix/store/s3b6zh5m6p78k8s3wnjcqjwjyysl3igh-python3.10-watchdog-2.1.8/lib/python3.10/site-packages/watchdog/observers/__init__.py:71: UserWarning: Failed to import fsevents. Fall back to kqueue
  warnings.warn("Failed to import fsevents. Fall back to kqueue")
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test SAM CLI
Resources:
  TestInlineFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Test function defined via InlineCode
      PackageType: Zip
      Handler: index.handler
      InlineCode: "exports.handler = async (event) => {\n  return {\n    statusCode:\
        \ 200,\n    body: '\"Test success\"'\n  };\n}\n"
      MemorySize: 512
      Runtime: nodejs16.x
      Timeout: 30
      FunctionUrlConfig:
        AuthType: AWS_IAM
    Metadata:
      SamResourceId: TestInlineFunction
```

### Additional context

I encountered this on macOS. Previously I'd been using a pinned version of aws-sam-cli version 1.0.0rc1, but I needed to update it to use some new AWS features; the commit used by these `nix-shell` commands is the latest change to this package.

### Notify maintainers

@lo1tuma 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.4.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.0`
 - channels(chrisw): `"darwin, nixpkgs-21.11pre297902.e8597594274"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/2jnzpprppad1rg8y0f15a3kx726b0ibx-repo2111-src`
```

**Comment by jiegec** [comment]
Maybe we should package a old version of python3Packages.docker.
