### ISSUE TITLE
Python: python310Packages.langcodes: "ModuleNotFoundError: No module named 'language_data'"

### ISSUE THREAD

**Issue by Dines97** [NixOS/nixpkgs#180712]
### Describe the bug
Langcodes requires the language_data package for some of its functions to work. When trying to use these functions, it gives the error "ModuleNotFoundError: No module named 'language_data'".

### Steps To Reproduce
Rough piece of nix code from the entire configuration:
```nix
  python-bot = p: with p; with pkgs.python310Packages; [
    langcodes
    # optionally add language-data it does not change anything
    language-data
  ];
  python-with-packages = pkgs.python310.withPackages python-bot;

  home-manager.users.${user-name} = { pkgs, ... }: {
    home.packages = with pkgs; [
       python-with-packages
   };
```
An example of Python code that throws an error:
```python
from langcodes import Language

language = Language.get("en-US")
print(language)
print(language.territory_name()) # This method requires language_data and throws error
```

### Expected behavior
No error?

### Additional context
The Python environment is used as described in the first example at https://nixos.wiki/wiki/Python

### Notify maintainers
@ixxie 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.8-xanmod1, NixOS, 22.05 (Quokka), 22.05.1490.316b762afdb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(denis): `""`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Dines97** [comment]
language-data has another maintainer, I forgot to add it @fabaff

**Comment by Dines97** [comment]
I realized that I can share even more information. Full error text:
```
➜  demo python main.py
en-US

Looking up language names now requires the `language_data` package.

Install it with:
    pip install language_data
Or as an optional feature of langcodes:
    pip install langcodes[data]

Traceback (most recent call last):
  File "/home/denis/demo/main.py", line 5, in <module>
    print(language.territory_name())
  File "/nix/store/rbsjwvm1608sb0s29sxxz7fizagkmwrc-python3-3.10.4-env/lib/python3.10/site-packages/langcodes/__init__.py", line 1094, in territory_name
    return self._get_name('territory', language, max_distance)
  File "/nix/store/rbsjwvm1608sb0s29sxxz7fizagkmwrc-python3-3.10.4-env/lib/python3.10/site-packages/langcodes/__init__.py", line 853, in _get_name
    from language_data.names import code_to_names
ModuleNotFoundError: No module named 'language_data'
```

**Comment by r3lativo** [comment]
Hello, I have your same error, did you find a solution?

**Comment by Dines97** [comment]
Hi @r3lativo, i didn't find any solution. It wasn't super important project for me. And i tested right now and same code runs perfectly. I assume i will close this issue.

**Comment by sofiadelpozo** [comment]
Hi, I had the same error and using **pip install language_data** solved it.
