### ISSUE TITLE
dotnetCorePackages.combinePackages: not generating the correct dotnet binary

### ISSUE THREAD

**Issue by GGG-KILLER** [NixOS/nixpkgs#182495]
### Steps To Reproduce
1. build the following combined package:
```nix
let
  dotnet-sdk = with pkgs.dotnetCorePackages;
    combinePackages [
      sdk_6_0
      sdk_5_0
      sdk_3_1
    ];
in {
  environment.systemPackages = [dotnet-sdk];
}
```
2. Attempt to run `dotnet --version`
3. Following error is output to console:
```
-> % dotnet --version
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
[1]    34709 IOT instruction (core dumped)  dotnet --version
```

### Build log
No actual build error. Error happens when trying to run.

#### NixOS Info
Flake input: `nixpkgs.url = github:nixos/nixpkgs/nixos-unstable;`
Flake lockfile entry:
```json
    "nixpkgs": {
      "locked": {
        "lastModified": 1658380158,
        "narHash": "sha256-DBunkegKWlxPZiOcw3/SNIFg93amkdGIy2g0y/jDpHg=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "a65b5b3f5504b8b89c196aba733bdf2b0bd13c16",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
```

#### Patchelf
```console
$ whereis dotnet  
dotnet: /nix/store/4h24pxrmglsh1d7n2hpkn0d4c836v442-system-path/bin/dotnet
$ patchelf --print-interpreter /nix/store/4h24pxrmglsh1d7n2hpkn0d4c836v442-system-path/bin/dotnet
/nix/store/mhhlymrg2m70r8h94cwhv2d7a0c8l7g6-glibc-2.34-210/lib/ld-linux-x86-64.so.2
$ patchelf --print-rpath /nix/store/4h24pxrmglsh1d7n2hpkn0d4c836v442-system-path/bin/dotnet
/nix/store/xjmm9xg5sq47q63cbf447qalz9fmwp0v-gcc-11.3.0-lib/lib
```

### Notify maintainers
@kuznero @mdarocha

### Metadata

```console
[ggg@sora:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.53, NixOS, 22.11 (Raccoon), 22.11.20220721.a65b5b3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/z0iaykmdjd9gq2xx474n0b411ya2bima-source`
```

**Comment by GGG-KILLER** [comment]
Update:  `dotnet` without `combinePackages` executes a bash file which in turn has the icu lib set:
```bash
#! /nix/store/3j18grljsyy4nxc078g00sy4cx6cf16g-bash-5.1-p16/bin/bash -e
LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+':'$LD_LIBRARY_PATH':'}
LD_LIBRARY_PATH=${LD_LIBRARY_PATH/':''/nix/store/818bg1vl0xv1vfrsn39v8wwra36b9k5k-icu4c-71.1/lib'':'/':'}
LD_LIBRARY_PATH='/nix/store/818bg1vl0xv1vfrsn39v8wwra36b9k5k-icu4c-71.1/lib'$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${LD_LIBRARY_PATH#':'}
LD_LIBRARY_PATH=${LD_LIBRARY_PATH%':'}
export LD_LIBRARY_PATH
exec -a "$0" "/nix/store/ls0rm4pwxhna5j6nawrh94qqiw57nrwl-dotnet-sdk-6.0.301/bin/.dotnet-wrapped"  "$@" 
```

However with `combinePackages`, that file is not copied, instead the actual binary is put into path.

**Comment by GGG-KILLER** [comment]
I have created a temporary fix while a proper one doesn't land in nixpkgs: https://gist.github.com/GGG-KILLER/2f06a0902748d458ebf336979c042e18

**Comment by mdarocha** [comment]
Did https://github.com/NixOS/nixpkgs/pull/187118 fix this?

**Comment by GGG-KILLER** [comment]
> Did https://github.com/NixOS/nixpkgs/pull/187118 fix this?

Oh yes, I actually forgot I opened this issue, sorry
