### ISSUE TITLE
Sushi only plays audio when previewing video files

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#182542]
### Describe the bug
When previewing a video file, Sushi only plays audio and displays a broken image.

### Steps To Reproduce
1. Select a video file in GNOME Files
2. Press `<Space>`

### Expected behavior
Sushi should play the video.

### Screenshots
![图片](https://user-images.githubusercontent.com/12882091/180592641-f8218742-d2ff-4474-99c5-a2ecbe32b37b.png)

### Additional context
Tried the following workaround, but it doesn't seem to help.
```nix
{
  nixpkgs.config.packageOverrides = pkgs: {
      gnome = pkgs.gnome.overrideScope' (gself: gsuper: {
        sushi = gsuper.sushi.overrideAttrs (oldAttrs: rec {
          buildInputs = oldAttrs.buildInputs ++ [
            pkgs.gst_all_1.gst-libav
          ];
        });
      });
  };
}
```

### Notify maintainers

@jtojnar @bobby285271 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.55, NixOS, 22.11 (Raccoon), 22.11pre393241.a65b5b3f550`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(yes): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
I can reproduce, the following appears in the journal.

```
Jul 23 13:44:08 theo .org.gnome.Naut[412514]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Jul 23 13:44:08 theo .org.gnome.Naut[412514]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jul 23 13:44:08 theo .org.gnome.Naut[412514]: gst_object_unref: assertion 'object != NULL' failed
```

I can play the files just fine when opening in Totem (GNOME Videos) rebuilt without libav codecs.

---

After patching Sushi with:

```patch
--- a/pkgs/desktops/gnome/core/sushi/default.nix
+++ b/pkgs/desktops/gnome/core/sushi/default.nix
@@ -59,6 +59,9 @@ stdenv.mkDerivation rec {
     gst_all_1.gst-plugins-ugly
   ];
 
+  dontStrip = true;
+  mesonBuildType = "debug";
+
   # See https://github.com/NixOS/nixpkgs/issues/31168
   postInstall = ''
     for file in $out/libexec/org.gnome.NautilusPreviewer
```

and running it and opening random MP4 file I downloaded:

```shell
nix-build -A gnome.sushi
env GST_PLUGIN_SYSTEM_PATH_1_0= G_MESSAGES_DEBUG=all G_DEBUG=fatal-criticals result/libexec/org.gnome.NautilusPreviewer &
result/bin/sushi ~/Videos/foo.mp4
```

the previewer crashes and I get the following trace in `coredumpctl gdb` (after entering the `bt` command):

```gdb
#1  0x00007fd4450a5aef in g_log (log_domain=log_domain@entry=0x7fd44502b4a7 "GLib-GObject", log_level=log_level@entry=G_LOG_LEVEL_CRITICAL, format=format@entry=0x7fd4450fde5d "%s: assertion '%s' failed")
    at ../glib/gmessages.c:1456
#2  0x00007fd4450a6389 in g_return_if_fail_warning (log_domain=log_domain@entry=0x7fd44502b4a7 "GLib-GObject", pretty_function=pretty_function@entry=0x7fd44502f2e8 <__func__.41> "g_object_get", 
    expression=expression@entry=0x7fd44502dbd6 "G_IS_OBJECT (object)") at ../glib/gmessages.c:2942
#3  0x00007fd445006b1a in g_object_get (_object=0x0, first_property_name=first_property_name@entry=0x7fd42c0406c1 "widget") at ../gobject/gobject.c:2751
#4  0x00007fd42c03b109 in sushi_media_bin_init_video_sink (self=self@entry=0x1e9c400) at ../src/libsushi/sushi-media-bin.c:607
#5  0x00007fd42c03cce7 in on_sushi_media_bin_realize (widget=0x1e9c400, self=0x1e9c400) at ../src/libsushi/sushi-media-bin.c:805
```

The trace points to https://gitlab.gnome.org/GNOME/sushi/-/blob/8f0191433175a90272e8e1f9a6518e7520be8470/src/libsushi/sushi-media-bin.c#L607, which means like Sushi requires a gtk sink.

Running the previewer with `GST_DEBUG="*:3"` environment variable confirms it:

```
0:00:05.753428062 437336      0x12bb6d0 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:701:gst_element_factory_make_with_properties: no such element factory "gtksink"!
```
