### ISSUE TITLE
nox crash on NixOS 22.05

### ISSUE THREAD

**Issue by AleXoundOS** [NixOS/nixpkgs#182871]
### Describe the bug
[nox](https://github.com/madjar/nox) crashes right after launching. Perhaps, we hit this issue: https://github.com/madjar/nox/issues/97.

### Steps To Reproduce
```console
nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/e3583ad6e533a9d8dd78f90bfa93812d390ea187.tar.gz -p nox --run nox
```

### Expected behavior
nox must not crash.

### Screenshots
```
Traceback (most recent call last):
  File "/nix/store/06s4i2pw69fd9scckvhvvx1ajdcnvxim-nox-0.0.6/bin/.nox-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/z1zay8mf8xiig2isyfg64gm75q1v5v3i-python3.9-click-8.1.3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/z1zay8mf8xiig2isyfg64gm75q1v5v3i-python3.9-click-8.1.3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/z1zay8mf8xiig2isyfg64gm75q1v5v3i-python3.9-click-8.1.3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/z1zay8mf8xiig2isyfg64gm75q1v5v3i-python3.9-click-8.1.3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/06s4i2pw69fd9scckvhvvx1ajdcnvxim-nox-0.0.6/lib/python3.9/site-packages/nox/search.py", line 64, in main
    results = [p for p in all_packages(force_refresh)
  File "/nix/store/06s4i2pw69fd9scckvhvvx1ajdcnvxim-nox-0.0.6/lib/python3.9/site-packages/nox/search.py", line 64, in <listcomp>
    results = [p for p in all_packages(force_refresh)
  File "/nix/store/06s4i2pw69fd9scckvhvvx1ajdcnvxim-nox-0.0.6/lib/python3.9/site-packages/nox/search.py", line 52, in <genexpr>
    return (Package(attr, v['name'], v['meta'].get('description', ''))
KeyError: 'meta'
```

### Additional context
NixOS 22.05.

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.10-xanmod1, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/store/v039w5dpnfqy2qvqq04a489s8zqvr4di-source`
```

**Comment by l0b0** [comment]
Seems to be fixed in recent nixpkgs - should this be closed?
