### ISSUE TITLE
FreeCAD Draft Workbench error

### ISSUE THREAD

**Issue by Wulfsta** [NixOS/nixpkgs#183497]
### Describe the bug
Navigating to Draft produces the following error in console:
```
<built-in function SoFieldContainer_getField> returned a result with an exception set
Traceback (most recent call last):
  File "<string>", line 149, in Activated
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_snapper.py", line 1629, in show
    self.setTrackers()
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_snapper.py", line 1673, in setTrackers
    self.grid = trackers.gridTracker()
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_trackers.py", line 972, in __init__
    pick.style.setValue(coin.SoPickStyle.UNPICKABLE)
  File "/nix/store/dq8yly6isjzq6imm0i0qjxkang5rcq84-python3.10-pivy-0.6.6/lib/python3.10/site-packages/pivy/coin.py", line 4744, in __getattr__
    field = self.getField(name)
  File "/nix/store/dq8yly6isjzq6imm0i0qjxkang5rcq84-python3.10-pivy-0.6.6/lib/python3.10/site-packages/pivy/coin.py", line 4601, in getField
    return _coin.SoFieldContainer_getField(self, name)
```

All the tools appear to be broken as well:
```
Running the Python command 'Draft_Facebinder' failed:
Traceback (most recent call last):
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_facebinders.py", line 66, in Activated
    super(Facebinder, self).Activated(name="Facebinder")
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_base_original.py", line 287, in Activated
    super(Creator, self).Activated(name, noplanesetup)
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_base_original.py", line 152, in Activated
    Gui.Snapper.setTrackers()
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_snapper.py", line 1673, in setTrackers
    self.grid = trackers.gridTracker()
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_trackers.py", line 972, in __init__
    pick.style.setValue(coin.SoPickStyle.UNPICKABLE)
  File "/nix/store/dq8yly6isjzq6imm0i0qjxkang5rcq84-python3.10-pivy-0.6.6/lib/python3.10/site-packages/pivy/coin.py", line 4744, in __getattr__
    field = self.getField(name)
  File "/nix/store/dq8yly6isjzq6imm0i0qjxkang5rcq84-python3.10-pivy-0.6.6/lib/python3.10/site-packages/pivy/coin.py", line 4601, in getField
    return _coin.SoFieldContainer_getField(self, name)

<built-in function SoFieldContainer_getField> returned a result with an exception setRunning the Python command 'Draft_Trimex' failed:
Traceback (most recent call last):
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_trimex.py", line 84, in Activated
    super(Trimex, self).Activated(name="Trimex")
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_base_original.py", line 307, in Activated
    super(Modifier, self).Activated(name, noplanesetup, is_subtool)
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_base_original.py", line 152, in Activated
    Gui.Snapper.setTrackers()
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_snapper.py", line 1673, in setTrackers
    self.grid = trackers.gridTracker()
  File "/nix/store/va42205c0jp3ik02ap2yrnrcm8j933q6-freecad-0.20/Mod/Draft/draftguitools/gui_trackers.py", line 972, in __init__
    pick.style.setValue(coin.SoPickStyle.UNPICKABLE)
  File "/nix/store/dq8yly6isjzq6imm0i0qjxkang5rcq84-python3.10-pivy-0.6.6/lib/python3.10/site-packages/pivy/coin.py", line 4744, in __getattr__
    field = self.getField(name)
  File "/nix/store/dq8yly6isjzq6imm0i0qjxkang5rcq84-python3.10-pivy-0.6.6/lib/python3.10/site-packages/pivy/coin.py", line 4601, in getField
    return _coin.SoFieldContainer_getField(self, name)

<built-in function SoFieldContainer_getField> returned a result with an exception set
```

### Steps To Reproduce
Open FreeCAD and navigate to Draft Workbench.

### Expected behavior
No errors in console.

### Notify maintainers

@viric @gebner @AndersonTorres

**Comment by Wulfsta** [comment]
Possibly related to how old `cond3d` is?
