### ISSUE TITLE
PolyMC fails to launch Minecraft versions up to 1.12.2

### ISSUE THREAD

**Issue by F0Xde** [NixOS/nixpkgs#184189]
### Describe the bug
On my system PolyMC 1.4.0 and 1.4.1 fails to launch any instance I've tested up to Minecraft 1.12.2 due to apparently missing `libXxf86vm.so`:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.UnsatisfiedLinkError: /home/me/data/polymc/instances/1.12-vanilla/natives/liblwjgl64.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at bib.I(SourceFile:2825)
	at net.minecraft.client.main.Main.main(SourceFile:38)
	... 9 more
```

Before upgrading from 1.3.2 -> 1.4.0 this did not occur.

### Steps To Reproduce
1. Install PolyMC 1.4.1 from nixos-unstable
2. Try to start any Minecraft version before 1.13 (tested with a1.0.4, 1.7.10, 1.8.9 and 1.12.2)

### Expected behavior
The game should launch.

### Additional context
This was first discussed in PolyMC/PolyMC#976, but closed by the author.

As seen in [my comment](https://github.com/PolyMC/PolyMC/issues/976#issuecomment-1199118696) over there, I also encounter a problem with versions 1.13 upwards. In those versions the game launches but fails to open an OpenAL device, resulting in sound not working. If others can reproduce this behavior I would like to include it with this bug report.

### Notify maintainers

@cleverca22 @starcraft66 @lourkeur 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.58, NixOS, 22.11 (Raccoon), 22.11.20220729.8d435fc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by F0Xde** [comment]
Fixed with #184604
