### ISSUE TITLE
npm2nix is broken

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#18442]
```
> nix-shell -p nodePackages.npm2nix

[nix-shell:~]$ npm2nix
module.js:327
    throw err;
    ^

Error: Cannot find module '/nix/store/5a8lcw2r1mjyca4n3yjrzd6d8m9ar3b2-node-npm2nix-5.12.0/lib/node_modules/npm2nix/lib/npm2nix.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/nix/store/5a8lcw2r1mjyca4n3yjrzd6d8m9ar3b2-node-npm2nix-5.12.0/lib/node_modules/npm2nix/lib/command.js:3:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

master from two or three days ago.

**Comment by domenkozar** [comment]
cc @svanderburg

**Comment by NeQuissimus** [comment]
I can confirm this. `node2nix` seems to work though (no idea what the differences are...)

**Comment by Profpatsch** [comment]
`node2nix` is brilliant. @svanderburg maybe it’s time to phase out `npm2nix`?

**Comment by svanderburg** [comment]
@Profpatsch That's already what we have been doing. The only reason why there are still files left generated by npm2nix, is because it would break a couple of non-NPM packages.

I also intend to replace these affected packages, but it will take a bit of time as some of them are a bit obscure.

**Comment by Profpatsch** [comment]
@svanderburg I’m afraid we can’t phase out the package itself. Maybe deprecate it and remove it on the next release?

**Comment by Profpatsch** [comment]
Seems to work again.
