### ISSUE TITLE
ValueError: Namespace Gtk not available - grapejuice 5.2.2 - NixosUnstable

### ISSUE THREAD

**Issue by fnxln** [NixOS/nixpkgs#184583]
### Describe the bug
When u type grapejuice app or  grapejuice player you get the following error:
`ValueError: Namespace Gtk not available`

### Steps To Reproduce
1. `nix-env -iA nixos.grapejuice`
2. `grapejuice app`

### Expected behavior
Grapejuice opens as normal

### Full log
```
[INFO] grapejuice/root:- The log file is stored at '~/.local/var/log/grapejuice/2022-08-01_12-15-03_grapejuice.log'
[INFO] grapejuice/common_prepare:- Using locale directory /nix/store/q2c8asxv9zz1im1icb8nqnd3pfbmar6r-grapejuice-5.2.2/share/locale
Fatal error: Namespace Gtk not available
Traceback (most recent call last):
  File "/nix/store/q2c8asxv9zz1im1icb8nqnd3pfbmar6r-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice/cli/main.py", line 182, in main
    cli()
  File "/nix/store/76sx92rcq1lxq0fg2v914h6ynfgrxmp0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/76sx92rcq1lxq0fg2v914h6ynfgrxmp0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/76sx92rcq1lxq0fg2v914h6ynfgrxmp0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/76sx92rcq1lxq0fg2v914h6ynfgrxmp0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/76sx92rcq1lxq0fg2v914h6ynfgrxmp0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/q2c8asxv9zz1im1icb8nqnd3pfbmar6r-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice/cli/main.py", line 48, in app
    gtk_boot(player_main, gtk_main=False)
  File "/nix/store/q2c8asxv9zz1im1icb8nqnd3pfbmar6r-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/gtk/gtk_util.py", line 16, in gtk_boot
    gi.require_version("Gtk", "3.0")
  File "/nix/store/d0m1mk1zbsjysrm1bq44087njrygnl7w-python3.10-pygobject-3.42.1/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/q2c8asxv9zz1im1icb8nqnd3pfbmar6r-grapejuice-5.2.2/bin/.grapejuice-wrapped", line 9, in <module>
    sys.exit(easy_install_main())
  File "/nix/store/q2c8asxv9zz1im1icb8nqnd3pfbmar6r-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice/cli/main.py", line 191, in easy_install_main
    main()
  File "/nix/store/q2c8asxv9zz1im1icb8nqnd3pfbmar6r-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice/cli/main.py", line 185, in main
    handle_fatal_error(e)
  File "/nix/store/q2c8asxv9zz1im1icb8nqnd3pfbmar6r-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice/cli/cli_common.py", line 17, in handle_fatal_error
    gtk_boot(make_exception_window)
  File "/nix/store/q2c8asxv9zz1im1icb8nqnd3pfbmar6r-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/gtk/gtk_util.py", line 16, in gtk_boot
    gi.require_version("Gtk", "3.0")
  File "/nix/store/d0m1mk1zbsjysrm1bq44087njrygnl7w-python3.10-pygobject-3.42.1/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
[INFO] grapejuice/grapejuice_common.wine.wineprefix_core_control:- Closing fds
```

### Notify maintainers
@Artturin

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.11-xanmod1, NixOS, 22.11 (Raccoon), 22.11pre396318.7b9be38c725`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - channels(lin): `"home-manager-22.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
gtk3 has to be added to buildInputs

**Comment by fnxln** [comment]
Adding gtk3 to  buildInputs results in the app opening but results in the following error
```
Traceback (most recent call last):
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice/cli/main.py", [REDACTED]e 182, in main
    cli()
  File "/nix/store/76sx92rcq1lxq0fg2v914h6ynfgrxmp0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", [REDACTED]e 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/76sx92rcq1lxq0fg2v914h6ynfgrxmp0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", [REDACTED]e 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/76sx92rcq1lxq0fg2v914h6ynfgrxmp0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", [REDACTED]e 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/76sx92rcq1lxq0fg2v914h6ynfgrxmp0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", [REDACTED]e 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/76sx92rcq1lxq0fg2v914h6ynfgrxmp0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", [REDACTED]e 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice/cli/main.py", [REDACTED]e 48, in app
    gtk_boot(player_main, gtk_main=False)
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/gtk/gtk_util.py", [REDACTED]e 25, in gtk_boot
    main_function(*args, **kwargs)
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice/cli/main.py", [REDACTED]e 46, in player_main
    dbus_connection().launch_app(prefix.configuration.id)
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/ipc/no_daemon_connection.py", [REDACTED]e 34, in launch_app
    _with_prefix_id(prefix_id, lambda prefix: prefix.roblox.launch_app())
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/ipc/no_daemon_connection.py", [REDACTED]e 19, in _with_prefix_id
    prefix.roblox.install_roblox(post_install_function=lambda: cb(prefix))
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/wine/wineprefix_roblox.py", [REDACTED]e 57, in install_roblox
    self._core_control.create_prefix()
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/wine/wineprefix_core_control.py", [REDACTED]e 442, in create_prefix
    self.configure_prefix()
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/wine/wineprefix_core_control.py", [REDACTED]e 438, in configure_prefix
    self.disable_mime_associations()
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/wine/wineprefix_core_control.py", [REDACTED]e 425, in disable_mime_associations
    self.load_registry_file(paths.assets_directory() / "disable_mime_assoc.reg")
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/wine/wineprefix_core_control.py", [REDACTED]e 388, in load_registry_file
    self.prepare_for_launch()
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/wine/wineprefix_core_control.py", [REDACTED]e 365, in prepare_for_launch
    wine_bin_string = str(self.wine_bin)
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/wine/wineprefix_core_control.py", [REDACTED]e 275, in wine_bin
    return self.wine_home / "bin"
  File "/nix/store/fxmg8gc0hj2n4dp90crlr7wpcqdajw3g-grapejuice-5.2.2/lib/python3.10/site-packages/grapejuice_common/wine/wineprefix_core_control.py", [REDACTED]e 251, in wine_home
    raise WineHomeInvalid(home_path, "The Wine home doesn't exist")
grapejuice_common.errors.WineHomeInvalid: Wine home path is invalid:
Wine home '/nix/store/3jwkxxn84frh11m2g513z94p6c4rss5a-wine-wow-7.13' is invalid! The Wine home doesn't exist.
```

**Comment by Artturin** [comment]
check if that Wine home path exists and it contains a bin directory (very weird if it doesn't as I have the same path)

for me after adding gtk3 to buildInputs the program starts successfully 

```
[INFO] grapejuice/root:- Log level was set to 'INFO'
[INFO] grapejuice/root:- The log file is stored at '~/.local/var/log/grapejuice/2022-08-03_15-36-07_grapejuice.log'
[INFO] grapejuice/common_prepare:- Using locale directory /nix/store/wx28ydrw10q2pb0zm8wzk408vg76i6sv-grapejuice-5.2.2/share/locale
[INFO] grapejuice/grapejuice_common.wine.wineprefix_roblox:- Writing flags for RobloxProduct.app to: ~/.local/share/grapejuice/prefixes/player/drive_c/Program Files (x86)/Roblox/Versions/version-9045f70ea522489c/ClientSettings/ClientAppSettings.json
[INFO] grapejuice/grapejuice_common.wine.wineprefix_roblox:- Writing flags for RobloxProduct.app to: ~/.local/share/grapejuice/prefixes/player/drive_c/Program Files (x86)/Roblox/Versions/version-acbc8cfc2b354d72/ClientSettings/ClientAppSettings.json
[INFO] grapejuice/grapejuice_common.wine.wineprefix_core_control:- Using Wine home '/nix/store/3jwkxxn84frh11m2g513z94p6c4rss5a-wine-wow-7.13'
[INFO] grapejuice/grapejuice_common.wine.wineprefix_core_control:- Applying environment: {"WINEDLLOVERRIDES": "dxdiagn=;winemenubuilder.exe=", "WINEPREFIX": "~/.local/share/grapejuice/prefixes/player", "WINEARCH": "win64", "WINEDEBUG": "-all"}
[INFO] grapejuice/grapejuice_common.wine.wineprefix_core_control:- Using Wine home '/nix/store/3jwkxxn84frh11m2g513z94p6c4rss5a-wine-wow-7.13'
```

**Comment by fnxln** [comment]
ater doing:
`nix-store --add  /nix/store/3jwkxxn84frh11m2g513z94p6c4rss5a-wine-wow-7.13`
fixes te issue with the wine path, gonna send the pull request for the gtk3
