### ISSUE TITLE
arrow-cpp build failure

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#185082]
### Steps To Reproduce
1. build arrow-cpp on https://github.com/NixOS/nixpkgs/commit/7b5ac19d7b5f6e029001b101cab7b73b7a45ed71

### Build log
See https://hydra.nixos.org/build/185903212.

### Additional context
See https://github.com/NixOS/nixpkgs/issues/183172.

### Notify maintainers
@tobim @veprbl @cpcloud

**Comment by SuperSandro2000** [comment]
Please include meaningful information when creating issues like relevant log parts. Just linking a failed hydra build is not enough.

----

```
Running arrow-flight-test, redirecting output into /build/apache-arrow-8.0.0/cpp/build/build/test-logs/arrow-flight-test.txt (attempt 1/1)
Traceback (most recent call last):
  File "/build/apache-arrow-8.0.0/cpp/build-support/asan_symbolize.py", line 368, in <module>
Running main() from /build/source/googletest/src/gtest_main.cc
Note: Google Test filter = -S3OptionsTest.FromUri:S3RegionResolutionTest.NonExistentBucket:S3RegionResolutionTest.PublicBucket:S3RegionResolutionTest.RestrictedBucket:TestMinioServer.Connect:TestS3FS.*:TestS3FSGeneric.*
```

```
[----------] 7 tests from GrpcDoPutTest
[ RUN      ] GrpcDoPutTest.TestInts
/build/apache-arrow-8.0.0/cpp/src/arrow/flight/test_definitions.cc:690: Failure
Failed
    loop.process_stdin()
  File "/build/apache-arrow-8.0.0/cpp/build-support/asan_symbolize.py", line 348, in process_stdin
    print(self.current_line)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 83-89: surrogates not allowed
/build/apache-arrow-8.0.0/cpp/build/src/arrow/flight
```

**Comment by SuperSandro2000** [comment]
Also there is #185124 which probably fixes this.

**Comment by risicle** [comment]
Bisect suggests 9c6b1fbce39382b152f068f364af85dad96b7eab is the culprit

**Comment by risicle** [comment]
#185082
