### ISSUE TITLE
Lapce errors with lacking either libGL or libEGL 

### ISSUE THREAD

**Issue by hanckmann** [NixOS/nixpkgs#185099]
### Describe the bug
The lapce editor does not start after installation. It shows the following error:

```
~  > lapce
thread '<unnamed>' panicked at 'Error Occurred: Os { code: 2, kind: NotFound, message: "No such file or directory" }', lapce-proxy/src/lsp.rs:425:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'launch failed: Other(window build error: Received multiple errors. Errors: `[NotSupported("lacking either libGL or libEGL so could not fallback to other"), NotSupported("both libGL and libEGL are not present")]` srgb false)', lapce-ui/src/app.rs:54:27
```

### Steps To Reproduce
1. add lapce to the configuration.nix `{ environment.systemPackages = with pkgs; [ lapce ]; }`
2. start lapce from the terminal: `$ lapce`
3. the error is shown in the terminal

### Expected behavior
The lapce editor should start

### Screenshots
Not applicable, but the terminal output of the error is shown above.

### Additional context
```
Machine     -  LENOVO ThinkPad T14s Gen 1 20UHCTO1WW
Kernel      -  5.18.14-zen1
Distro      -  NixOS 22.05 (Quokka)
WM          -  Sway (Wayland)
Terminal    -  foot
Shell       -  zsh
CPU         -  AMD Ryzen 7 PRO 4750U with Radeon Graphics (16)
Resolution  -  1920x1080
CPU Load    -  3%
Memory      -  1.2 GB/32.1 GB
```

### Notify maintainers
@elliot
[nixpkgs](https://github.com/NixOS/nixpkgs/tree/nixos-22.05)/[pkgs](https://github.com/NixOS/nixpkgs/tree/nixos-22.05/pkgs)/[applications](https://github.com/NixOS/nixpkgs/tree/nixos-22.05/pkgs/applications)/[editors](https://github.com/NixOS/nixpkgs/tree/nixos-22.05/pkgs/applications/editors)/[lapce](https://github.com/NixOS/nixpkgs/tree/nixos-22.05/pkgs/applications/editors/lapce)/default.nix

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.14-zen1, NixOS, 22.05 (Quokka), 22.05.2167.a9f66ae6401`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - channels(patrick): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mausch** [comment]
Works for me on nixpkgs-unstable: `nix run github:nixos/nixpkgs/nixpkgs-unstable#lapce`
so this was probably fixed around https://github.com/NixOS/nixpkgs/pull/179562
