### ISSUE TITLE
xpra: "ValueError: Namespace Gtk not available" (gobject-introspection vs gtk3)

### ISSUE THREAD

**Issue by eddyb** [NixOS/nixpkgs#185651]
### Describe the bug
Any (client-side) `xpra` command results in an error (failing to use `gtk3` via `gobject-introspection`).

### Steps To Reproduce
```console
$ xpra
xpra main error:
Traceback (most recent call last):
  File "/nix/store/lmawgjvinhb1qkbg04pis8sn54ws6436-xpra-4.3.3/lib/python3.10/site-packages/xpra/scripts/main.py", line 142, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/nix/store/lmawgjvinhb1qkbg04pis8sn54ws6436-xpra-4.3.3/lib/python3.10/site-packages/xpra/scripts/main.py", line 420, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/nix/store/lmawgjvinhb1qkbg04pis8sn54ws6436-xpra-4.3.3/lib/python3.10/site-packages/xpra/scripts/main.py", line 516, in do_run_mode
    check_gtk()
  File "/nix/store/lmawgjvinhb1qkbg04pis8sn54ws6436-xpra-4.3.3/lib/python3.10/site-packages/xpra/scripts/main.py", line 317, in check_gtk
    gi.require_version("Gtk", "3.0")
  File "/nix/store/gipin543iy3insvp27jp1f4cycjcsm1h-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

### Additional context
[Looking at similar issues](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+ValueError%3A+Namespace+Gtk+not+available+is%3Aclosed), these are likely related:
* #183609
* #183865
* #184583

They seem to all have been fallout from this PR:
* #177538

### Notify maintainers
@Artturin

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.58, NixOS, 22.11 (Raccoon), 22.11pre397509.168d1c57890`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - channels(eddy): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eddyb** [comment]
As a workaround, doing this in `~/.nixpkgs/config.nix` seems to work:
```nix
{
  packageOverrides = super: {
    xpra = super.xpra.overrideAttrs (orig: {
      nativeBuildInputs = orig.nativeBuildInputs ++ [super.gobject-introspection];
    });
  };
}
```

Trying this specifically was inspired by:
* #184567

I am very likely to forget about this btw (just wanted to get this working somehow so I can GC the old generation), so feel free to open a PR if you run into this (should just require adding `gobject-introspection` to `xpra`'s `nativeBuildInputs`).
