### ISSUE TITLE
Unable to build Jekyll site due to Nokogiri failures

### ISSUE THREAD

**Issue by j-hui** [NixOS/nixpkgs#185841]
I'm trying to set up a project to build Github Pages/Jekyll sites on NixOS. I'm following [this tutorial](https://matthewrhone.dev/jekyll-in-nixos) (though there are several similar ones), and am unable to get things to work.

### Steps To Reproduce

1. Populate `Gemfile`:

```Gemfile
source 'https://rubygems.org'
gem 'github-pages'
# gem "nokogiri", "~> 1.10.10"
```

2. Populate `default.nix`:

```nix
with (import <nixpkgs> {});
let
  env = bundlerEnv {
    name = "jekyllProject";
    inherit ruby;
    gemfile = ./Gemfile;
    lockfile = ./Gemfile.lock;
    gemset = ./gemset.nix;
  };
in stdenv.mkDerivation {
  name = "your-package";
  buildInputs = [env ruby];

  shellHook = ''
      exec ${env}/bin/jekyll serve --watch
  '';
}
```

3. Generate `Gemfile.lock` and `gemset.nix` by running:

```console
nix-shell -p bundler -p bundix --run 'bundler update; bundler lock; bundler package --no-install --path vendor; bundix; rm -rf vendor'
```

4. Run `nix-shell`

Without setting nokogiri to version 1.10.10, I seem to get a hash mismatch error:

```
error: hash mismatch in fixed-output derivation '/nix/store/8bd1wx7i98l4mbj67vhl8anpqj4hrp7x-nokogiri-1.13.8.gem.drv':
         specified: sha256-NE8bxm/qx4flsgU8bpCV0fM2BQg+WN3yuNTu8le8zF8=
            got:    sha256-ecJ5KYsvIv1Odg9JmQx5MENrrBsc/v97rP8ZLzDt6jw=
error: 1 dependencies of derivation '/nix/store/zzjbc0jsmvaijzcasimc2wa13rhndxb9-ruby2.7.6-nokogiri-1.13.8.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bjs1hvlb0641crrybxrf0q69wbjf3r0j-jekyllProject.drv' failed to build
```

When I set nokogiri to version 1.10.10 according to the advice of the article, I get a compilation error; from the build log:

```
xml_document.c: At top level:
xml_document.c:495:14: error: conflicting types for 'canonicalize'; have 'VALUE(int,  VALUE *, VALUE)' {aka 'long unsigned int(int,  long unsigned int *, long unsigned int)'}
  495 | static VALUE canonicalize(int argc, VALUE* argv, VALUE self)
      |              ^~~~~~~~~~~~
In file included from /nix/store/dwsi3wsqpqm0hpzdm9fsxc7q732p9xwi-glibc-2.34-210-dev/include/features.h:490,
                 from /nix/store/dwsi3wsqpqm0hpzdm9fsxc7q732p9xwi-glibc-2.34-210-dev/include/bits/libc-header-start.h:33,
                 from /nix/store/dwsi3wsqpqm0hpzdm9fsxc7q732p9xwi-glibc-2.34-210-dev/include/stdlib.h:25,
                 from ./nokogiri.h:4,
                 from ./xml_document.h:4,
                 from xml_document.c:1:
/nix/store/dwsi3wsqpqm0hpzdm9fsxc7q732p9xwi-glibc-2.34-210-dev/include/bits/mathcalls.h:368:1: note: previous declaration of 'canonicalize' with type 'int(double *, const double *)'
  368 | __MATHDECL_1 (int, canonicalize,, (_Mdouble_ *__cx, const _Mdouble_ *__x));
      | ^~~~~~~~~~~~
In file included from /nix/store/5j7phyqix1lxswbfynq1gazyiqxy3aan-ruby-2.7.6/include/ruby-2.7.0/ruby.h:33,
                 from ./nokogiri.h:33,
                 from ./xml_document.h:4,
                 from xml_document.c:1:
xml_document.c: In function 'canonicalize':
/nix/store/5j7phyqix1lxswbfynq1gazyiqxy3aan-ruby-2.7.6/include/ruby-2.7.0/ruby/ruby.h:2510:62: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
 2510 |                      (rb_scan_args_verify(fmt, varc), vars), (char *)fmt, varc)
      |                                                              ^
/nix/store/5j7phyqix1lxswbfynq1gazyiqxy3aan-ruby-2.7.6/include/ruby-2.7.0/ruby/ruby.h:2342:9: note: in expansion of macro 'rb_scan_args0'
 2342 |         rb_scan_args0(argc,argvp,fmt,\
      |         ^~~~~~~~~~~~~
xml_document.c:511:3: note: in expansion of macro 'rb_scan_args'
  511 |   rb_scan_args(argc, argv, "03", &mode, &incl_ns, &with_comments);
      |   ^~~~~~~~~~~~
make: *** [Makefile:245: xml_document.o] Error 1
```

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.49, NixOS, 22.05 (Quokka), 22.05.1377.09c32b0bda4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05.1377.09c32b0bda4, nixpkgs-unstable-22.11pre389376.660ac43ff9a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by quinn-dougherty** [comment]
I have a similar issue, I can't hello world in rails. https://github.com/nix-community/bundix/issues/88 for reference, though the solution there doesn't work for me.

**Comment by peterhoeg** [comment]
Try blowing away `Gemfile.lock` and then running `bundle install` again *after* making that change. You may have to add additional constraints in the `Gemfile` in order to get the versions to match your current situation.

**Comment by siriobalmelli** [comment]
As a temporary solution, try replacing `nokogiri`'s hash in `gemset.nix` with ` sha256-ecJ5KYsvIv1Odg9JmQx5MENrrBsc/v97rP8ZLzDt6jw=` and re-running?

**Comment by DrPyser** [comment]
I am also getting build failures on nokogiri(`ruby3.1.2-nokogiri-1.13.8`) when trying to create a simple rails development environment. It does not seem to be the same failure though, so I'll create a separate issue.

**Comment by FabHof** [comment]
I have exactly the same error. Specifying `gem "nokogiri", "~> 1.10.10"` results in a conflict with github-pages.
So I have no way to get this to run.

Can anyone help?

**Comment by j-hui** [comment]
I haven't been able to fix this; I didn't have time to try out everyone's detailed suggestions, though I did try various combinations of deleting the Gemfile.lock, adding constraints, playing around with hashes, etc. I moved on because I just wanted something that "Just Works:tm:".

My workaround is to use Docker. In particular, I just needed something that would build and serve my github-pages site, so that I can preview my site locally. Do that, I just run:

```sh
docker run -it --rm -v $(PWD)/docs:/usr/src/app -p "4000:4000" starefossen/github-pages
```

I stuck this in a Makefile for convenient access.

In the meantime, I'll leave this issue open since there the underlying issue still does not seem to have been fixed.

**Comment by delta1** [comment]
> As a temporary solution, try replacing `nokogiri`'s hash in `gemset.nix` with ` sha256-ecJ5KYsvIv1Odg9JmQx5MENrrBsc/v97rP8ZLzDt6jw=` and re-running?

Nix noob here: I tried this, it got further and then errored on: 

```
/nix/store/czca9a081q3dpd8qp5nzqz2581pw7336-ruby-2.7.6/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'mini_portile2' (~> 2.8.0) among 56 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/nix/store/53kzvld7j8bzc6513szk91s8187zbmlm-ruby2.7.6-racc-1.6.0/lib/ruby/gems/2.7.0:/nix/store/czca9a081q3dpd8qp5nzqz2581pw7336-ruby-2.7.6/lib/ruby/gems/2.7.0:/nix/store/yya1pfng5cdx2pf953iy0y6xvsw2b8aw-ruby2.7.6-nokogiri-1.13.9/lib/ruby/gems/2.7.0' , execute `gem env` for more information
        from /nix/store/czca9a081q3dpd8qp5nzqz2581pw7336-ruby-2.7.6/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
        from /nix/store/czca9a081q3dpd8qp5nzqz2581pw7336-ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
        from extconf.rb:420:in `process_recipe'
        from extconf.rb:933:in `<main>'

```
