### ISSUE TITLE
python310Packages.psycopg: fails to install on darwin

### ISSUE THREAD

**Issue by deejayem** [NixOS/nixpkgs#185918]
### Steps To Reproduce
1. nix-env -iA nixpkgs.pgcli

### Build log
```
strip is /nix/store/nq7dispfy6jj8m56963b5w990djs431y-cctools-binutils-darwin-949.0.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/5lyyfvw44wr9fzn1n6fmgj75znvgac0d-python3.10-psycopg-3.0.16/lib
patching script interpreter paths in /nix/store/5lyyfvw44wr9fzn1n6fmgj75znvgac0d-python3.10-psycopg-3.0.16
find: ‘/nix/store/gpmklzz1f2ryfmljjyzaaiys29d633w5-python3.10-psycopg-3.0.16-doc’: No such file or directory
strip is /nix/store/nq7dispfy6jj8m56963b5w990djs431y-cctools-binutils-darwin-949.0.1/bin/strip
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
running install tests
no Makefile or custom installCheckPhase, doing nothing
pythonCatchConflictsPhase
pythonRemoveBinBytecodePhase
pythonImportsCheckPhase
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: psycopg
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/rs23kn5r3qm96cq26b6bzy2w7rs5r39d-python3-3.10.5/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/5lyyfvw44wr9fzn1n6fmgj75znvgac0d-python3.10-psycopg-3.0.16/lib/python3.10/site-packages/psycopg/__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
  File "/nix/store/5lyyfvw44wr9fzn1n6fmgj75znvgac0d-python3.10-psycopg-3.0.16/lib/python3.10/site-packages/psycopg/pq/__init__.py", line 114, in <module>
    import_from_libpq()
  File "/nix/store/5lyyfvw44wr9fzn1n6fmgj75znvgac0d-python3.10-psycopg-3.0.16/lib/python3.10/site-packages/psycopg/pq/__init__.py", line 106, in import_from_libpq
    raise ImportError(
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: dlopen(/nix/store/9zzdsi078dfvwk3c8mp0ah4n11qdhbnj-postgresql-14.4-lib/lib/libpq.so, 6): image not found
error: builder for '/nix/store/0mra8pnkgn7800bsdsiji856zvh871ha-python3.10-psycopg-3.0.16.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/yvf9l87k4i5564k79xjfl1291sgxy21d-python3.10-pgspecial-2.0.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1rr2x51srx48fa4lkjic6p7047h62is7-python3.10-pgcli-3.4.1.drv' failed to build
```
(full output here: http://ix.io/47c6)

### Notify maintainers
@dywedir  @SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - channels(djm): `"home-manager, nixpkgs"`
 - nixpkgs: `/Users/djm/.nix-defexpr/channels/nixpkgs`
```

**Comment by SuperSandro2000** [comment]
The error is not in pgcli but in psycopg which tries to import a .so which does not work under darwin.
