### ISSUE TITLE
python310Packages.shapely test fails with segmentation fault on aarch64-darwin

### ISSUE THREAD

**Issue by lf-** [NixOS/nixpkgs#185996]
### Steps To Reproduce

1. `nix-build -A python310Packages.shapely`

### Build log

https://gist.github.com/5dee86a455e3d36b4909aa3abb2e7642

### Notify maintainers

@knedlsepp 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

repro'd on commit id 08ca24c9f28a02c52ca0bc9ffe18c1b69bae2c59

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.5.0, macOS 12.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixpkgs"`
 - channels(jade): `""`
 - nixpkgs: `/nix/store/laymyq0d4724hm86igwdbsv0vl1hxfgz-nixpkgs-src
```

**Comment by lf-** [comment]
backtrace:

<details>
<summary>Backtrace from lldb</summary>

```
[nix-shell:/tmp/shapely/Shapely-1.8.2]$ lldb -- python -m pytest
(lldb) target create "python"
Current executable set to 'python' (arm64).
(lldb) settings set -- target.run-args  "-m" "pytest"
(lldb) c
error: invalid process
(lldb) r
Process 17719 launched: '/nix/store/v4iwl6az3wax9nw0wl42kjpq4vfdd7j4-python3-3.10.5/bin/python' (arm64)
warning: (arm64) /nix/store/v4iwl6az3wax9nw0wl42kjpq4vfdd7j4-python3-3.10.5/bin/python3.10(0x0000000100000000) address 0x0000000100000000 ma
ps to more than one section: python3.10.__TEXT and python3.10.__TEXT
warning: (arm64) /nix/store/v4iwl6az3wax9nw0wl42kjpq4vfdd7j4-python3-3.10.5/bin/python3.10(0x0000000100000000) address 0x0000000100008000 ma
ps to more than one section: python3.10.__DATA_CONST and python3.10.__DATA_CONST
warning: (arm64) /nix/store/v4iwl6az3wax9nw0wl42kjpq4vfdd7j4-python3-3.10.5/bin/python3.10(0x0000000100000000) address 0x000000010000c000 ma
ps to more than one section: python3.10.__DATA and python3.10.__DATA
============================= test session starts ==============================
platform darwin -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
numpy: 1.23.1
rootdir: /private/tmp/shapely/Shapely-1.8.2, configfile: setup.cfg, testpaths: tests
collected 484 items

tests/test_affinity.py ..............                                    [  2%]
tests/test_binascii_hex.txt .                                            [  3%]
tests/test_box.py ...                                                    [  3%]
tests/test_buffer.py ........                                            [  5%]
tests/test_cga.py ....                                                   [  6%]
tests/test_clip_by_rect.py .......xx                                     [  8%]
tests/test_collection.py ................                                [ 11%]
tests/test_coords.py ...                                                 [ 11%]
tests/test_create_inconsistent_dimensionality.py ...........             [ 14%]
tests/test_default_impl.py ..                                            [ 14%]
tests/test_delaunay.py ...                                               [ 15%]
tests/test_delegated.py ..                                               [ 15%]
tests/test_dlls.py ..                                                    [ 16%]
tests/test_doctests.py .                                                 [ 16%]
tests/test_emptiness.py ...............                                  [ 19%]
tests/test_empty_polygons.py ....                                        [ 20%]
tests/test_equality.py ...                                               [ 20%]
tests/test_geointerface.py .Exception ignored in: <function BaseGeometry.__del__ at 0x105a29e10>
Traceback (most recent call last):
  File "/nix/store/v2hk13i6i6ljz0sbdkslbqy73dw3g1qs-python3.10-Shapely-1.8.2/lib/python3.10/site-packages/shapely/geometry/base.py", line 20
9, in __del__
    self._empty(val=None)
  File "/nix/store/v2hk13i6i6ljz0sbdkslbqy73dw3g1qs-python3.10-Shapely-1.8.2/lib/python3.10/site-packages/shapely/geometry/base.py", line 19
9, in _empty
    self._is_empty = True
  File "/nix/store/v2hk13i6i6ljz0sbdkslbqy73dw3g1qs-python3.10-Shapely-1.8.2/lib/python3.10/site-packages/shapely/geometry/proxy.py", line 4
4, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute '_is_empty'
...                                          [ 21%]
tests/test_geometry_base.py ............                                 [ 24%]
tests/test_geomseq.py .                                                  [ 24%]
tests/test_geos_err_handler.py FF..F.                                    [ 25%]
tests/test_getitem.py ...........                                        [ 27%]
tests/test_hash.py ....                                                  [ 28%]
tests/test_invalid_geometries.py .                                       [ 28%]
tests/test_iterops.py ....                                               [ 29%]
tests/test_linear_referencing.py .........                               [ 31%]
tests/test_linemerge.py .                                                [ 31%]
tests/test_linestring.py ..............................                  [ 38%]
tests/test_locale.py .                                                   [ 38%]
tests/test_make_valid.py ..                                              [ 38%]
tests/test_mapping.py ..                                                 [ 39%]
tests/test_minimum_clearance.py FProcess 17719 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x7ff0000000000008)
    frame #0: 0x000000010057c0b0 libpython3.10.dylib`find_name_in_mro + 36
libpython3.10.dylib`find_name_in_mro:
->  0x10057c0b0 <+36>: ldr    x8, [x1, #0x8]
    0x10057c0b4 <+40>: adrp   x9, 498
    0x10057c0b8 <+44>: add    x9, x9, #0x240            ; PyUnicode_Type
    0x10057c0bc <+48>: cmp    x8, x9
Target 0: (python3.10) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x7ff0000000000008)
  * frame #0: 0x000000010057c0b0 libpython3.10.dylib`find_name_in_mro + 36
    frame #1: 0x000000010057bfa0 libpython3.10.dylib`_PyType_Lookup + 144
    frame #2: 0x00000001005f4af4 libpython3.10.dylib`_PyEval_EvalFrameDefault + 15612
    frame #3: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #4: 0x0000000100529c14 libpython3.10.dylib`property_descr_get + 128
    frame #5: 0x000000010056a288 libpython3.10.dylib`_PyObject_GenericGetAttrWithDict + 200
    frame #6: 0x00000001005699f0 libpython3.10.dylib`PyObject_GetAttr + 100
    frame #7: 0x00000001005f4c18 libpython3.10.dylib`_PyEval_EvalFrameDefault + 15904
    frame #8: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #9: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #10: 0x00000001005f6d68 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24432
    frame #11: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #12: 0x000000010051f4b0 libpython3.10.dylib`_PyObject_FastCallDictTstate + 312
    frame #13: 0x000000010051fffc libpython3.10.dylib`_PyObject_Call_Prepend + 148
    frame #14: 0x0000000100585984 libpython3.10.dylib`slot_tp_call + 224
    frame #15: 0x000000010051f6c0 libpython3.10.dylib`_PyObject_MakeTpCall + 360
    frame #16: 0x00000001005f96bc libpython3.10.dylib`call_function + 524
    frame #17: 0x00000001005f6df8 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24576
    frame #18: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #19: 0x0000000100529c14 libpython3.10.dylib`property_descr_get + 128
    frame #20: 0x000000010056a288 libpython3.10.dylib`_PyObject_GenericGetAttrWithDict + 200
    frame #21: 0x00000001005699f0 libpython3.10.dylib`PyObject_GetAttr + 100
    frame #22: 0x00000001005f4c18 libpython3.10.dylib`_PyEval_EvalFrameDefault + 15904
    frame #23: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #24: 0x00000001005f7078 libpython3.10.dylib`_PyEval_EvalFrameDefault + 25216
    frame #25: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #26: 0x00000001005f7078 libpython3.10.dylib`_PyEval_EvalFrameDefault + 25216
    frame #27: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #28: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #29: 0x00000001005f6d88 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24464
    frame #30: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #31: 0x0000000100521e94 libpython3.10.dylib`method_vectorcall + 168
    frame #32: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #33: 0x00000001005f6d88 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24464
    frame #34: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #35: 0x000000010051f414 libpython3.10.dylib`_PyObject_FastCallDictTstate + 156
    frame #36: 0x000000010051fffc libpython3.10.dylib`_PyObject_Call_Prepend + 148
    frame #37: 0x0000000100585984 libpython3.10.dylib`slot_tp_call + 224
    frame #38: 0x000000010051f6c0 libpython3.10.dylib`_PyObject_MakeTpCall + 360
    frame #39: 0x00000001005f96bc libpython3.10.dylib`call_function + 524
    frame #40: 0x00000001005f6e68 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24688
    frame #41: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #42: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #43: 0x00000001005f6d68 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24432
    frame #44: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #45: 0x00000001005f7078 libpython3.10.dylib`_PyEval_EvalFrameDefault + 25216
    frame #46: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #47: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #48: 0x00000001005f6d88 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24464
    frame #49: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #50: 0x0000000100521e94 libpython3.10.dylib`method_vectorcall + 168
    frame #51: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #52: 0x00000001005f6d88 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24464
    frame #53: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #54: 0x000000010051f414 libpython3.10.dylib`_PyObject_FastCallDictTstate + 156
    frame #55: 0x000000010051fffc libpython3.10.dylib`_PyObject_Call_Prepend + 148
    frame #56: 0x0000000100585984 libpython3.10.dylib`slot_tp_call + 224
    frame #57: 0x000000010051fc94 libpython3.10.dylib`_PyObject_Call + 172
    frame #58: 0x00000001005f7078 libpython3.10.dylib`_PyEval_EvalFrameDefault + 25216
    frame #59: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #60: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #61: 0x00000001005f6df8 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24576
    frame #62: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #63: 0x0000000100521e94 libpython3.10.dylib`method_vectorcall + 168
    frame #64: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #65: 0x00000001005f6e68 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24688
    frame #66: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #67: 0x00000001005f7078 libpython3.10.dylib`_PyEval_EvalFrameDefault + 25216
    frame #68: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #69: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #70: 0x00000001005f6df8 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24576
    frame #71: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #72: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #73: 0x00000001005f6e68 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24688
    frame #74: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #75: 0x00000001005f7078 libpython3.10.dylib`_PyEval_EvalFrameDefault + 25216
    frame #76: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #77: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #78: 0x00000001005f6d88 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24464
    frame #79: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #80: 0x0000000100521e94 libpython3.10.dylib`method_vectorcall + 168
    frame #81: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #82: 0x00000001005f6d88 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24464
    frame #83: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #84: 0x000000010051f414 libpython3.10.dylib`_PyObject_FastCallDictTstate + 156
    frame #85: 0x000000010051fffc libpython3.10.dylib`_PyObject_Call_Prepend + 148
    frame #86: 0x0000000100585984 libpython3.10.dylib`slot_tp_call + 224
    frame #87: 0x000000010051f6c0 libpython3.10.dylib`_PyObject_MakeTpCall + 360
    frame #88: 0x00000001005f96bc libpython3.10.dylib`call_function + 524
    frame #89: 0x00000001005f6e68 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24688
    frame #90: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #91: 0x00000001005f7078 libpython3.10.dylib`_PyEval_EvalFrameDefault + 25216
    frame #92: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #93: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #94: 0x00000001005f6d88 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24464
    frame #95: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #96: 0x0000000100521e94 libpython3.10.dylib`method_vectorcall + 168
    frame #97: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #98: 0x00000001005f6d88 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24464
    frame #99: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #100: 0x000000010051f414 libpython3.10.dylib`_PyObject_FastCallDictTstate + 156
    frame #101: 0x000000010051fffc libpython3.10.dylib`_PyObject_Call_Prepend + 148
    frame #102: 0x0000000100585984 libpython3.10.dylib`slot_tp_call + 224
    frame #103: 0x000000010051f6c0 libpython3.10.dylib`_PyObject_MakeTpCall + 360
    frame #104: 0x00000001005f96bc libpython3.10.dylib`call_function + 524
    frame #105: 0x00000001005f6e68 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24688
    frame #106: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #107: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #108: 0x00000001005f6df8 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24576
    frame #109: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #110: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #111: 0x00000001005f6df8 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24576
    frame #112: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #113: 0x00000001005f7078 libpython3.10.dylib`_PyEval_EvalFrameDefault + 25216
    frame #114: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #115: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #116: 0x00000001005f6d88 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24464
    frame #117: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #118: 0x0000000100521e94 libpython3.10.dylib`method_vectorcall + 168
    frame #119: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #120: 0x00000001005f6d88 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24464
    frame #121: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #122: 0x000000010051f414 libpython3.10.dylib`_PyObject_FastCallDictTstate + 156
    frame #123: 0x000000010051fffc libpython3.10.dylib`_PyObject_Call_Prepend + 148
    frame #124: 0x0000000100585984 libpython3.10.dylib`slot_tp_call + 224
    frame #125: 0x000000010051f6c0 libpython3.10.dylib`_PyObject_MakeTpCall + 360
    frame #126: 0x00000001005f96bc libpython3.10.dylib`call_function + 524
    frame #127: 0x00000001005f6e68 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24688
    frame #128: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #129: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #130: 0x00000001005f6df8 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24576
    frame #131: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #132: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #133: 0x00000001005f6d88 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24464
    frame #134: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #135: 0x00000001005f0c38 libpython3.10.dylib`PyEval_EvalCode + 124
    frame #136: 0x00000001005ed7d4 libpython3.10.dylib`builtin_exec + 708
    frame #137: 0x0000000100564fa0 libpython3.10.dylib`cfunction_vectorcall_FASTCALL + 232
    frame #138: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #139: 0x00000001005f6df8 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24576
    frame #140: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #141: 0x00000001005f965c libpython3.10.dylib`call_function + 428
    frame #142: 0x00000001005f6df8 libpython3.10.dylib`_PyEval_EvalFrameDefault + 24576
    frame #143: 0x00000001005f0cfc libpython3.10.dylib`_PyEval_Vector + 148
    frame #144: 0x000000010065c130 libpython3.10.dylib`pymain_run_module + 216
    frame #145: 0x000000010065b71c libpython3.10.dylib`Py_RunMain + 764
    frame #146: 0x000000010065bfa4 libpython3.10.dylib`pymain_main + 340
    frame #147: 0x000000010065c030 libpython3.10.dylib`Py_BytesMain + 56
    frame #148: 0x000000010001908c dyld`start + 520
(lldb)
```

</details>

**Comment by maximbaz-maersk** [comment]
@lf- shapely 1.8.4 with the fix is now in pypi, I saw you wanted to upgrade it, did you get around to do it? 🙂

**Comment by lf-** [comment]
thanks for the reminder, committed it
