### ISSUE TITLE
`pkgs.vagrant`: Out-of-date 2.2.19 -> 2.3.0.

### ISSUE THREAD

**Issue by VergeDX** [NixOS/nixpkgs#186606]
###### Checklist
- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: vagrant
current version: 2.2.19
desired version: 2.3.0

###### Notify maintainers

maintainers: @Ma27

**Comment by SebTM** [comment]
I've tried to update vagrant as described in the `default.nix` with not only adjusting the version but also try to re-bundle the vagrant and vagrant-libvirt dependencies via bundix where I encountered different problems:

1. The hashes of different dependencies like google-protobuf, grpc, ... (only a few) are reported wrong while building. Changing them solves the problem. It doesn't matter if I use "-l", "-m "-dm" or no parameters for bundix.
2. After that it seems that dependencies are missing/recognized or I did something wrong:
```
 these 30 derivations will be built:
   /nix/store/ixkjl1kv2rqdlgfnc199dj3fw0aj9f7x-ruby2.7.6-ffi-1.15.5.drv
   /nix/store/08nb65r9nywl1alw7bji1mdd1i9h8ny1-ruby2.7.6-gssapi-1.3.1.drv
   /nix/store/pf68h7h7f3ixgknhg7gy0al8s8x1x1l4-ruby2.7.6-google-protobuf-3.21.5.drv
   /nix/store/wakm86zdp1n4rjx1ry9skczvinpkj582-ruby2.7.6-googleapis-common-protos-types-1.3.2.drv
   /nix/store/a60by6zfy8asgfwrl6fqzifp5lcm5ay9-ruby2.7.6-grpc-1.48.0.drv
   /nix/store/awir1rhx15q4w2hpkxih7ydr4qc66lir-ruby2.7.6-winrm-2.3.6.drv
   /nix/store/63savqc8d3c9h8cg17xr5vb2xy7zz6s3-ruby2.7.6-rb-inotify-0.10.1.drv
   /nix/store/b3jy4p3306gshrvhcwwznrgq19hgc6fi-ruby2.7.6-listen-3.7.1.drv
   /nix/store/v54zh2xm5mc71srfaqag35zmkm255aab-ruby2.7.6-winrm-fs-1.3.5.drv
   /nix/store/rc2gmg0a6fmcsjybpqvwwismi96s2grq-ruby2.7.6-winrm-elevated-1.2.3.drv
   /nix/store/x5sfpk8m624b8xg979x7mrbs18d443c4-ruby2.7.6-rb-kqueue-0.2.8.drv
   /nix/store/09wlp885dxds6f5p70nn1kpkypqgjfdy-ruby2.7.6-vagrant-2.3.1.dev.drv
   /nix/store/5938lbg8h3hahc3kl9wmdx3hfrg2ns9d-ruby2.7.6-nokogiri-1.13.8.drv
   /nix/store/8wfmnx31447992nzhpr4jaz90cph00sr-ruby2.7.6-fog-xml-0.1.4.drv
   /nix/store/rvf0arv4kc3ax5s2vk7n60qfrcyvv1ii-ruby2.7.6-vagrant-spec-0.0.1.drv
   /nix/store/zgcccryd4swp0z1cf19f39qwxds7llf8-ruby2.7.6-ruby-libvirt-0.8.0.drv
   /nix/store/yzy05cswn161ivvzq3ng1byh0w348zwq-ruby2.7.6-fog-libvirt-0.9.0.drv
   /nix/store/bbk02jdp4lwx2qpi7bpj040jwafm5k61-vagrant-2.3.0.drv
   /nix/store/kdanpyprlgabxcilwl7wkq9jmm00vphq-vagrant-2.3.0.drv
   /nix/store/2kr174b3jabq1awi5iwkxjw20rpg9w51-system-path.drv
   /nix/store/hx3iw1r87hvpnympyni56j896i5d7xvc-unit-systemd-fsck-.service.drv
   /nix/store/wchxkmjvkl2qxf0r22yh6lqdz3sz3ja5-dbus-1.drv
   /nix/store/lzfwc94qpqkcgdkwg512cihiv921a2qh-unit-dbus.service.drv
   /nix/store/nz16xim4ykvwpwl9kv69kkhy9jx69fs4-unit-accounts-daemon.service.drv
   /nix/store/pg3cfdi6mqmdw57xdlvvhvch7vsly0ja-unit-polkit.service.drv
   /nix/store/hl8wfs8givkczknzl329s41jqrar8y2w-system-units.drv
   /nix/store/nis70jwpbw4z7sl6phpdi8dy5v1wb0w2-unit-dbus.service.drv
   /nix/store/wyxsbwvm7cym2rcnh5995wyff1msd7c1-user-units.drv
   /nix/store/lg8vv5mj2q41973s4g4qb83wkhrx9wsl-etc.drv
   /nix/store/ydg1ifqp88059vmxkpcl6953dfcfvskk-nixos-system-XXXXXX-22.11pre-git.drv
 building '/nix/store/ixkjl1kv2rqdlgfnc199dj3fw0aj9f7x-ruby2.7.6-ffi-1.15.5.drv'...
 building '/nix/store/pf68h7h7f3ixgknhg7gy0al8s8x1x1l4-ruby2.7.6-google-protobuf-3.21.5.drv'...
 building '/nix/store/5938lbg8h3hahc3kl9wmdx3hfrg2ns9d-ruby2.7.6-nokogiri-1.13.8.drv'...
 building '/nix/store/zgcccryd4swp0z1cf19f39qwxds7llf8-ruby2.7.6-ruby-libvirt-0.8.0.drv'...
 building '/nix/store/rvf0arv4kc3ax5s2vk7n60qfrcyvv1ii-ruby2.7.6-vagrant-spec-0.0.1.drv'...
 unpacking sources
 unpacking sources
 patching sources
 patching sources
 configuring
 configuring
 unpacking sources
 no configure script, doing nothing
 no configure script, doing nothing
 installing
 patching sources
 installing
 buildFlags:
 configuring
 buildFlags:
 no configure script, doing nothing
 installing
 buildFlags: --use-system-libraries --with-zlib-lib=/nix/store/z18zgvspmxi88ipmk3f3nicvasfq3199-zlib-1.2.12/lib --with-zlib-include=/nix/store/py1w6vgg66qyjal27g6yzhaa2mp3rg3g-zlib-1.2.12-dev/include --with-xml2-lib=/nix/store/rqg79h5w8lzrw1a774z2fdkyakyjnr8n-libxml2-2.9.14/lib --with-xml2-include=/nix/store/036fl56k5xqbsqi9sm7ik3l6dbra4n45-libxml2-2.9.14-dev/include/libxml2 --with-xslt-lib=/nix/store/x1aqrbn4qxxkrhg2lwdj6w951c3j7ydf-libxslt-1.1.35/lib --with-xslt-include=/nix/store/8kpap8pd9g5cas277nxivh7pwhzxd48z-libxslt-1.1.35-dev/include --with-exslt-lib=/nix/store/x1aqrbn4qxxkrhg2lwdj6w951c3j7ydf-libxslt-1.1.35/lib --with-exslt-include=/nix/store/8kpap8pd9g5cas277nxivh7pwhzxd48z-libxslt-1.1.35-dev/include
 unpacking sources
 patching sources
 configuring
 no configure script, doing nothing
 installing
 buildFlags: --with-libvirt-include=/nix/store/riw4a9ffy9v75dk43386rrbn873b6pzn-libvirt-8.5.0/include --with-libvirt-lib=/nix/store/riw4a9ffy9v75dk43386rrbn873b6pzn-libvirt-8.5.0/lib
 unpacking sources
 unpacking source archive /nix/store/g2z7hb2vwfh5bd390zfpd8mp01v95gzf-vagrant-spec-a88825f
 source root is vagrant-spec-a88825f
 patching sources
 configuring
 no configure script, doing nothing
 building
 hint: Using 'master' as the name for the initial branch. This default branch name
 hint: is subject to change. To configure the initial branch name to use in all
 hint: of your new repositories, which will suppress this warning, call:
 hint:
 hint:   git config --global init.defaultBranch <name>
 hint:
 hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
 hint: 'development'. The just-created branch can be renamed via this command:
 hint:
 hint:   git branch -m <name>
 Initialized empty Git repository in /build/vagrant-spec-a88825f/.git/
 installing
 buildFlags:
 WARNING:  You build with buildroot.
   Build root: /
   Bin dir: /nix/store/609rr7inzf5jggqx19bpf3da1whz6laa-ruby2.7.6-google-protobuf-3.21.5/lib/ruby/gems/2.7.0/bin
   Gem home: /nix/store/609rr7inzf5jggqx19bpf3da1whz6laa-ruby2.7.6-google-protobuf-3.21.5/lib/ruby/gems/2.7.0
   Plugins dir: /nix/store/609rr7inzf5jggqx19bpf3da1whz6laa-ruby2.7.6-google-protobuf-3.21.5/lib/ruby/gems/2.7.0/plugins
 WARNING:  You build with buildroot.
   Build root: /
   Bin dir: /nix/store/8cxzf4y0mslkj7i4q2320gidxnqz9caz-ruby2.7.6-ffi-1.15.5/lib/ruby/gems/2.7.0/bin
   Gem home: /nix/store/8cxzf4y0mslkj7i4q2320gidxnqz9caz-ruby2.7.6-ffi-1.15.5/lib/ruby/gems/2.7.0
   Plugins dir: /nix/store/8cxzf4y0mslkj7i4q2320gidxnqz9caz-ruby2.7.6-ffi-1.15.5/lib/ruby/gems/2.7.0/plugins
 Building native extensions. This could take a while...
 WARNING:  You build with buildroot.
   Build root: /
   Bin dir: /nix/store/0z4d2lbr595qk0nlb4gjgxgr7yaw33v1-ruby2.7.6-ruby-libvirt-0.8.0/lib/ruby/gems/2.7.0/bin
   Gem home: /nix/store/0z4d2lbr595qk0nlb4gjgxgr7yaw33v1-ruby2.7.6-ruby-libvirt-0.8.0/lib/ruby/gems/2.7.0
   Plugins dir: /nix/store/0z4d2lbr595qk0nlb4gjgxgr7yaw33v1-ruby2.7.6-ruby-libvirt-0.8.0/lib/ruby/gems/2.7.0/plugins
 WARNING:  You build with buildroot.
   Build root: /
   Bin dir: /nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0/bin
   Gem home: /nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0
   Plugins dir: /nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0/plugins
 Building native extensions with: '--with-libvirt-include=/nix/store/riw4a9ffy9v75dk43386rrbn873b6pzn-libvirt-8.5.0/include --with-libvirt-lib=/nix/store/riw4a9ffy9v75dk43386rrbn873b6pzn-libvirt-8.5.0/lib'
 This could take a while...
 Building native extensions with: '--use-system-libraries --with-zlib-lib=/nix/store/z18zgvspmxi88ipmk3f3nicvasfq3199-zlib-1.2.12/lib --with-zlib-include=/nix/store/py1w6vgg66qyjal27g6yzhaa2mp3rg3g-zlib-1.2.12-dev/include --with-xml2-lib=/nix/store/rqg79h5w8lzrw1a774z2fdkyakyjnr8n-libxml2-2.9.14/lib --with-xml2-include=/nix/store/036fl56k5xqbsqi9sm7ik3l6dbra4n45-libxml2-2.9.14-dev/include/libxml2 --with-xslt-lib=/nix/store/x1aqrbn4qxxkrhg2lwdj6w951c3j7ydf-libxslt-1.1.35/lib --with-xslt-include=/nix/store/8kpap8pd9g5cas277nxivh7pwhzxd48z-libxslt-1.1.35-dev/include --with-exslt-lib=/nix/store/x1aqrbn4qxxkrhg2lwdj6w951c3j7ydf-libxslt-1.1.35/lib --with-exslt-include=/nix/store/8kpap8pd9g5cas277nxivh7pwhzxd48z-libxslt-1.1.35-dev/include'
 This could take a while...
 Using vagrant-spec 0.0.1 from https://github.com/hashicorp/vagrant-spec (at a88825f@a88825f)
 Building native extensions. This could take a while...
 post-installation fixup
 shrinking RPATHs of ELF executables and libraries in /nix/store/lm4xiv6md2xaaa1zsqw99zbcqkg7bg61-ruby2.7.6-vagrant-spec-0.0.1
 rewriting symlink /nix/store/lm4xiv6md2xaaa1zsqw99zbcqkg7bg61-ruby2.7.6-vagrant-spec-0.0.1/nix-support/gem-meta/spec to be relative to /nix/store/lm4xiv6md2xaaa1zsqw99zbcqkg7bg61-ruby2.7.6-vagrant-spec-0.0.1
 strip is /nix/store/kia8xygy2r9iblwbjrl163j4bpz84wz7-gcc-wrapper-11.3.0/bin/strip
 stripping (with command strip and flags -S) in /nix/store/lm4xiv6md2xaaa1zsqw99zbcqkg7bg61-ruby2.7.6-vagrant-spec-0.0.1/lib  /nix/store/lm4xiv6md2xaaa1zsqw99zbcqkg7bg61-ruby2.7.6-vagrant-spec-0.0.1/bin
 ERROR:  Error installing /nix/store/96w491sd9rcc2k6ridkai5qr982bndss-nokogiri-1.13.8.gem:
         ERROR: Failed to build gem native extension.

     current directory: /nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8/ext/nokogiri
 /nix/store/31171zm830653xgdn3ckwxlg6shpxc70-ruby-2.7.6/bin/ruby -I /nix/store/31171zm830653xgdn3ckwxlg6shpxc70-ruby-2.7.6/lib/ruby/2.7.0 -r ./siteconf20220816-18-up9nlq.rb extconf.rb --use-system-libraries --with-zlib-lib\=/nix/store/z18zgvspmxi88ipmk3f3nicvasfq3199-zlib-1.2.12/lib --with-zlib-include\=/nix/store/py1w6vgg66qyjal27g6yzhaa2mp3rg3g-zlib-1.2.12-dev/include --with-xml2-lib\=/nix/store/rqg79h5w8lzrw1a774z2fdkyakyjnr8n-libxml2-2.9.14/lib --with-xml2-include\=/nix/store/036fl56k5xqbsqi9sm7ik3l6dbra4n45-libxml2-2.9.14-dev/include/libxml2 --with-xslt-lib\=/nix/store/x1aqrbn4qxxkrhg2lwdj6w951c3j7ydf-libxslt-1.1.35/lib --with-xslt-include\=/nix/store/8kpap8pd9g5cas277nxivh7pwhzxd48z-libxslt-1.1.35-dev/include --with-exslt-lib\=/nix/store/x1aqrbn4qxxkrhg2lwdj6w951c3j7ydf-libxslt-1.1.35/lib --with-exslt-include\=/nix/store/8kpap8pd9g5cas277nxivh7pwhzxd48z-libxslt-1.1.35-dev/include
 checking for whether -std=c99 is accepted as CFLAGS... yes
 checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... yes
 checking for whether -g is accepted as CFLAGS... yes
 checking for whether -Winline is accepted as CFLAGS... yes
 checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
 Building nokogiri using system libraries.
 checking for gzdopen() in -lz... yes
 checking for xmlParseDoc() in -lxml2... yes
 checking for xsltParseStylesheetDoc() in -lxslt... yes
 checking for exsltFuncRegister() in -lexslt... yes
 *** extconf.rb failed ***
 Could not create Makefile due to some reason, probably lack of necessary
 libraries and/or headers.  Check the mkmf.log file for more details.  You may
 need configuration options.

 Provided configuration options:
         --with-opt-dir
         --without-opt-dir
         --with-opt-include
         --without-opt-include=${opt-dir}/include
         --with-opt-lib
         --without-opt-lib=${opt-dir}/lib
         --with-make-prog
         --without-make-prog
         --srcdir=.
         --curdir
         --ruby=/nix/store/31171zm830653xgdn3ckwxlg6shpxc70-ruby-2.7.6/bin/$(RUBY_BASE_NAME)
         --help
         --clean
         --prevent-strip
         --enable-system-libraries
         --disable-system-libraries
         --use-system-libraries
         --enable-system-libraries
         --disable-system-libraries
         --use-system-libraries
         --with-zlib-dir
         --without-zlib-dir
         --with-zlib-include=${zlib-dir}/include
         --with-zlib-lib=${zlib-dir}/lib
         --with-z-dir
         --without-z-dir
         --with-z-include
         --without-z-include=${z-dir}/include
         --with-z-lib
         --without-z-lib=${z-dir}/lib
         --with-zlib
         --without-zlib
         --with-xml2-dir
         --without-xml2-dir
         --with-xml2-include=${xml2-dir}/include
         --with-xml2-lib=${xml2-dir}/lib
         --with-xml2lib
         --without-xml2lib
         --with-xslt-dir
         --without-xslt-dir
         --with-xslt-include=${xslt-dir}/include
         --with-xslt-lib=${xslt-dir}/lib
         --with-xsltlib
         --without-xsltlib
         --with-exslt-dir
         --without-exslt-dir
         --with-exslt-include=${exslt-dir}/include
         --with-exslt-lib=${exslt-dir}/lib
         --with-exsltlib
         --without-exsltlib
 /nix/store/31171zm830653xgdn3ckwxlg6shpxc70-ruby-2.7.6/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'mini_portile2' (~> 2.8.0) among 56 total gem(s) (Gem::MissingSpecError)
 Checked in 'GEM_PATH=/nix/store/lyds5d5r7rwv0kiw6y9aq0m7q74wyhi8-ruby2.7.6-racc-1.6.0/lib/ruby/gems/2.7.0:/nix/store/31171zm830653xgdn3ckwxlg6shpxc70-ruby-2.7.6/lib/ruby/gems/2.7.0:/nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0' , execute `gem env` for more information
         from /nix/store/31171zm830653xgdn3ckwxlg6shpxc70-ruby-2.7.6/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
         from /nix/store/31171zm830653xgdn3ckwxlg6shpxc70-ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
         from extconf.rb:420:in `process_recipe'
         from extconf.rb:920:in `<main>'

 To see why this extension failed to compile, please check the mkmf.log which can be found here:

   /nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/nokogiri-1.13.8/mkmf.log

 extconf failed, exit code 1

 Gem files will remain installed in /nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8 for inspection.
 Results logged to /nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/nokogiri-1.13.8/gem_make.out
 error: builder for '/nix/store/5938lbg8h3hahc3kl9wmdx3hfrg2ns9d-ruby2.7.6-nokogiri-1.13.8.drv' failed with exit code 1
 error: 1 dependencies of derivation '/nix/store/bbk02jdp4lwx2qpi7bpj040jwafm5k61-vagrant-2.3.0.drv' failed to build
 error: 1 dependencies of derivation '/nix/store/kdanpyprlgabxcilwl7wkq9jmm00vphq-vagrant-2.3.0.drv' failed to build
 error: 1 dependencies of derivation '/nix/store/2kr174b3jabq1awi5iwkxjw20rpg9w51-system-path.drv' failed to build
 error: 1 dependencies of derivation '/nix/store/ydg1ifqp88059vmxkpcl6953dfcfvskk-nixos-system-XXXXXX-22.11pre-git.drv' failed to build
 Build failed: Child process exited with error code: 100
       | Failed: Child process exited with error code: 100
[ERROR] Failed to complete requested operation - Last 1 lines of logs:
[ERROR]  failure) Child process exited with error code: 100
[ERROR] Failed to build XXXXXX - Last 20 lines of logs:
[ERROR]   stderr) Checked in 'GEM_PATH=/nix/store/lyds5d5r7rwv0kiw6y9aq0m7q74wyhi8-ruby2.7.6-racc-1.6.0/lib/ruby/gems/2.7.0:/nix/store/31171zm830653xgdn3ckwxlg6shpxc70-ruby-2.7.6/lib/ruby/gems/2.7.0:/nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0' , execute `gem env` for more information
[ERROR]   stderr)         from /nix/store/31171zm830653xgdn3ckwxlg6shpxc70-ruby-2.7.6/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
[ERROR]   stderr)         from /nix/store/31171zm830653xgdn3ckwxlg6shpxc70-ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
[ERROR]   stderr)         from extconf.rb:420:in `process_recipe'
[ERROR]   stderr)         from extconf.rb:920:in `<main>'
[ERROR]   stderr)
[ERROR]   stderr) To see why this extension failed to compile, please check the mkmf.log which can be found here:
[ERROR]   stderr)
[ERROR]   stderr)   /nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/nokogiri-1.13.8/mkmf.log
[ERROR]   stderr)
[ERROR]   stderr) extconf failed, exit code 1
[ERROR]   stderr)
[ERROR]   stderr) Gem files will remain installed in /nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8 for inspection.
[ERROR]   stderr) Results logged to /nix/store/39ajl6ln1dd5czasdhr3i3f97wkhhqcl-ruby2.7.6-nokogiri-1.13.8/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/nokogiri-1.13.8/gem_make.out
[ERROR]   stderr) error: builder for '/nix/store/5938lbg8h3hahc3kl9wmdx3hfrg2ns9d-ruby2.7.6-nokogiri-1.13.8.drv' failed with exit code 1
[ERROR]   stderr) error: 1 dependencies of derivation '/nix/store/bbk02jdp4lwx2qpi7bpj040jwafm5k61-vagrant-2.3.0.drv' failed to build
[ERROR]   stderr) error: 1 dependencies of derivation '/nix/store/kdanpyprlgabxcilwl7wkq9jmm00vphq-vagrant-2.3.0.drv' failed to build
[ERROR]   stderr) error: 1 dependencies of derivation '/nix/store/2kr174b3jabq1awi5iwkxjw20rpg9w51-system-path.drv' failed to build
[ERROR]   stderr) error: 1 dependencies of derivation '/nix/store/ydg1ifqp88059vmxkpcl6953dfcfvskk-nixos-system-XXXXXX-22.11pre-git.drv' failed to build
[ERROR]  failure) Child process exited with error code: 100
[ERROR] -----
[ERROR] Operation failed with error: Child process exited with error code: 100
```

I've also used https://github.com/NixOS/nixpkgs/pull/65800 an bundix docs as reference. You can find my current state with manual adjusted hashes here: https://github.com/SebTM/nixpkgs/tree/update/vagrant230_dev

**Comment by Nebucatnetzer** [comment]
The current version would be 2.3.3 btw.

**Comment by bryanasdev000** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/225136.
