### ISSUE TITLE
Numpy fails without black

### ISSUE THREAD

**Issue by ethanabrooks** [NixOS/nixpkgs#186724]
### Describe the bug
Importing numpy fails unless imported alongside black.

### Steps To Reproduce
```nix
# flake.nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    utils.url = "github:numtide/flake-utils";
  };

  outputs = {
    self,
    nixpkgs,
    utils,
  }:
    utils.lib.eachDefaultSystem (system: let
      pkgs = import nixpkgs { inherit system; };
    in {
      devShell = pkgs.mkShell {
        buildInputs = [pkgs.pre-commit] ++ (with pkgs.python39.pkgs; [numpy]);
      };
    });
}
```
Then run
```
nix-develop
python -c 'import numpy'
```

### Expected behavior
`numpy` should import without errors
Instead we get
```
Traceback (most recent call last):
  File "/nix/store/qg0d8c64ky1zvwa14rmaqd7m38jcg832-python3.9-numpy-1.21.6/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/nix/store/qg0d8c64ky1zvwa14rmaqd7m38jcg832-python3.9-numpy-1.21.6/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/nix/store/qg0d8c64ky1zvwa14rmaqd7m38jcg832-python3.9-numpy-1.21.6/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/qg0d8c64ky1zvwa14rmaqd7m38jcg832-python3.9-numpy-1.21.6/lib/python3.9/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/nix/store/qg0d8c64ky1zvwa14rmaqd7m38jcg832-python3.9-numpy-1.21.6/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/nix/store/ddhcwc8k9ma093n5vlpa9l617p4q2cax-python3-3.10.5/bin/python"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Additional context
I found that adding black as in:
```
buildInputs = [pkgs.pre-commit] ++ (with pkgs.python39.pkgs; [numpy black]);
```
eliminates the error if that's any clue, although the version is still 1.21.6.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-120-generic, Ubuntu, 20.04.4 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(ethanbro): `"home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```

**Comment by ethanabrooks** [comment]
Sorry for the false alarm here! The issue was that I was running `python3.10` when `numpy` was failing! Running `numpy` inside `python3.9` works :)
