### ISSUE TITLE
piper fails to launch

### ISSUE THREAD

**Issue by samhh** [NixOS/nixpkgs#187508]
### Describe the bug

```console
$ piper
(.piper-wrapped:7422): dbind-WARNING **: 21:50:26.443: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Traceback (most recent call last):
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/bin/..piper-wrapped-wrapped", line 37, in <module>
    from piper.application import Application
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/lib/python3.10/site-packages/piper/application.py", line 4, in <module>
    from .window import Window
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/lib/python3.10/site-packages/piper/window.py", line 8, in <module>
    from .mouseperspective import MousePerspective
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/lib/python3.10/site-packages/piper/mouseperspective.py", line 5, in <module>
    from .buttonspage import ButtonsPage
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/lib/python3.10/site-packages/piper/buttonspage.py", line 6, in <module>
    from .mousemap import MouseMap
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/lib/python3.10/site-packages/piper/mousemap.py", line 12, in <module>
    gi.require_version("Rsvg", "2.0")
  File "/nix/store/a6p6gmp659yyn4zhhw4k9b147xl2k486-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available
```

Happens regardless of whether or not the `ratbagd` service is active.

### Notify maintainers

@mvnetbiz @r-ryantm

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.0, NixOS, 22.11 (Raccoon), 22.11.20220816.762b003`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - channels(sam): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by samhh** [comment]
It does launch via `nix-shell`...

I'm missing something obvious aren't I? I have it installed via Home Manager `home.packages` at the moment.

**Comment by jtojnar** [comment]
That looks like it is improperly packaged. https://github.com/NixOS/nixpkgs/blob/287e8bfb2dc42c15836c458b5a7adc1eef17181a/pkgs/os-specific/linux/piper/default.nix#L20 should contain `librsvg` and `strictDeps = false;` should be passed to `mkDerivation` as per https://nixos.org/manual/nixpkgs/stable/#ssec-gnome-hooks-gobject-introspection.

**Comment by samhh** [comment]
Success: https://github.com/samhh/dotfiles/commit/18cd8f8c9a79aa7648751e2a9db894fd9ee04471 Cheers!

It looks like it's out of date as well. I'll take this as an opportunity to start contributing to nixpkgs. Maybe I'll get a PR up today :slightly_smiling_face:
