### ISSUE TITLE
Emscripten/binaryen failing to build (so caches are also invalid)

### ISSUE THREAD

**Issue by dsyer** [NixOS/nixpkgs#188143]
Emscripten 3.1.17 is now the default in nixpkgs but it has been failing to build for a few days and isn't in the nixos.org binary cache (https://hydra.nixos.org/build/188061887/nixlog/1, https://hydra.nixos.org/search?query=emscripten). The failure is actually in `binaryen`, which is a build input for `emscripten`. The same build failure happens to me locally when the build is triggered by a cache miss (e.g. with `nix-shell -p emscripten`).

```
$ nix-shell -p emscripten
...
[PassRunner] (final validation)
executing:  /nix/store/0bchzrkaqk548zd1b1361mrk9szp8d33-nodejs-slim-18.7.0/bin/node --experimental-modules --no-warnings --loader /tmp/nix-build-binaryen-109.drv-0/source/scripts/test/node-esm-loader.mjs a.2asm.mjs
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_LOADER_CHAIN_INCOMPLETE]: "/tmp/nix-build-binaryen-109.drv-0/source/scripts/test/node-esm-loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:860:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:7)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:78:21)
    at async Promise.all (index 0)
    at async link (node:internal/modules/esm/module_job:83:9) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'
}

Node.js v18.7.0
Traceback (most recent call last):
  File "/tmp/nix-build-binaryen-109.drv-0/source/build/../check.py", line 416, in <module>
    sys.exit(main())
  File "/tmp/nix-build-binaryen-109.drv-0/source/build/../check.py", line 399, in main
    TEST_SUITES[test]()
  File "/tmp/nix-build-binaryen-109.drv-0/source/scripts/test/wasm2js.py", line 146, in test_wasm2js
    test_wasm2js_output()
  File "/tmp/nix-build-binaryen-109.drv-0/source/scripts/test/wasm2js.py", line 105, in test_wasm2js_output
    out = support.run_command(cmd)
  File "/tmp/nix-build-binaryen-109.drv-0/source/scripts/test/support.py", line 182, in run_command
    raise Exception(('run_command failed (%s)' % code, out + str(err or '')))
Exception: ('run_command failed (1)', '')
error: builder for '/nix/store/kcmyi5ivjicbzyr221azkz0b6344dfiz-binaryen-109.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/24lhjan4b9xkh5acdanjyjdafn2pfy07-emscripten-3.1.17.drv' failed to build
```

It looks to me with a shallow search on the internet that maybe Node 18 is the problem, and `emscripten` should depend on `node-16_x` explicitly (or something). I don't know how to do that, so I'm opening an issue. If I figure it out, maybe I'll send a PR.

**Comment by dsyer** [comment]
This seems to work locally (as `shell.nix`):

```
with import <nixpkgs> { };
mkShell {

  name = "env";
  buildInputs = [
    (emscripten.override { binaryen = (binaryen.override { nodejs = nodejs-14_x; }); })
  ];

  shellHook = ''
    echo ":emscripten:"
  '';

}
```

```
$ nix-shell
...

------------------------------------------------------------------

emcc: supported targets: llvm bitcode, WebAssembly, NOT elf
(autoconf likes to see elf above to enable shared object support)


[nix-shell:]$
```
