### ISSUE TITLE
Can't import plotnine in Python

### ISSUE THREAD

**Issue by jariji** [NixOS/nixpkgs#188918]
### Describe the bug

Can't import plotnine on Python 3.10 with nixos-unstable.

### Steps To Reproduce
```
nix-shell -p '(import <nixos-unstable> {}).python310.withPackages(ps: with ps; [ plotnine pandas patsy  matplotlib mizani])' --run 'python -c "import plotnine"'
```

### Expected behavior

Exit without error.

### Screenshots

```
% nix-shell -p '(import <nixos-unstable> {}).python310.withPackages(ps: with ps; [ plotnine pandas patsy  matplotlib mizani])' --run 'python -c "import plotnine"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/plotnine/__init__.py", line 1, in <module>
    from .qplot import qplot            # noqa: F401
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/plotnine/qplot.py", line 9, in <module>
    from .ggplot import ggplot
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/plotnine/ggplot.py", line 18, in <module>
    from .facets import facet_null
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/plotnine/facets/__init__.py", line 1, in <module>
    from .facet_grid import facet_grid
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/plotnine/facets/facet_grid.py", line 6, in <module>
    from .facet import facet, layout_null, combine_vars, add_missing_facets
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/plotnine/facets/facet.py", line 14, in <module>
    from ..scales.scales import Scales
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/plotnine/scales/__init__.py", line 2, in <module>
    from .scale_alpha import scale_alpha
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/plotnine/scales/scale_alpha.py", line 4, in <module>
    from mizani.palettes import rescale_pal
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/mizani/palettes.py", line 24, in <module>
    from palettable import colorbrewer
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/palettable/__init__.py", line 11, in <module>
    from . import colorbrewer
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/palettable/colorbrewer/__init__.py", line 3, in <module>
    from .colorbrewer import *
  File "/nix/store/09mnkg7hdr7k57nmbm4qc12n8z3lrpg5-python3-3.10.6-env/lib/python3.10/site-packages/palettable/colorbrewer/colorbrewer.py", line 7, in <module>
    from pkg_resources import resource_string
ModuleNotFoundError: No module named 'pkg_resources'
```

### Notify maintainers

@onny 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.9, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.337975.eabc3821918, nixos-unstable-22.11pre404572.a63021a330d, home-manager-21.05"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jariji** [comment]
Caused by https://github.com/NixOS/nixpkgs/issues/188919
