### ISSUE TITLE
hedgedoc manage_users looks for a git repository, fails to start

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#189213]
### Describe the bug
```
$ manage_users 
fatal: not a git repository (or any of the parent directories): .git
```

### Steps To Reproduce
1. nix-shell -p hedgedoc
2. manage_users

### Expected behavior
manage_user runs.

**Comment by SuperSandro2000** [comment]
No idea, I would guess the code is broken and needs a fix. I don't really have time to dig into this right now.

**Comment by grwlf** [comment]
Still broken, unfortunately..

**Comment by MangoIV** [comment]
I suspect this is because node can't find the required modules on nixos.

**Comment by MangoIV** [comment]
but perhaps I'm wrong, I don't have an idea about how node works

**Comment by MangoIV** [comment]
the odd thing about this is, that `node` runs "successfully" but just doesn't do anything

**Comment by SuperSandro2000** [comment]
FYI #283501 but it still does not fully work in the module. Please contribute that.

**Comment by thomasfire** [comment]
> Also does not work outside the module with:

What are the steps to reproduce? And what are the channels you are using?

**Comment by thomasfire** [comment]
For now I would blame e91a7b7a4e9513f4a2741b1a38c52fb81d4c9415

**Comment by neumantm** [comment]
I started debugging a bit:

- Script seems to exit when trying to load `../lib/models/`
- When manually trying to run `/path/to/node ../lib/models/` I get the following error:

```
2026-06-04T19:21:03.958Z warn: 	Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
2026-06-04T19:21:03.960Z warn: 	Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
2026-06-04T19:21:03.962Z error: 	uncaughtException: Dialect needs to be explicitly supplied as of v4.0.0
Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (/nix/store/v650ymlf91ycvqyyh2xc99gdmllhpqlr-hedgedoc-1.10.8/share/hedgedoc/node_modules/sequelize/lib/sequelize.js:275:13)
    at Object.<anonymous> (/nix/store/v650ymlf91ycvqyyh2xc99gdmllhpqlr-hedgedoc-1.10.8/share/hedgedoc/lib/models/index.js:27:15)
    at Module._compile (node:internal/modules/cjs/loader:1830:14)
    at Object..js (node:internal/modules/cjs/loader:1961:10)
    at Module.load (node:internal/modules/cjs/loader:1553:32)
    at Module._load (node:internal/modules/cjs/loader:1355:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47
``` 

The option `dialect` is part of the database config.
Turns out `manage_users` needs to access the database and therefore needs the configuration specifying the database connection. 
When running hedgedoc using the nixos module, the config file lives at `/run/hedgedoc/config.json` and is only readable by root.

-> I found I can use the following workaround to run `manage-users`:

```
nix-shell -p hedgedoc --command 'sudo CMD_CONFIG_FILE=/run/hedgedoc/config.json manage_users --add example@example.com'
```
