### ISSUE TITLE
SFTP deployment is boken in JetBrains IDEs on unstable (since 2022.2 versions)

### ISSUE THREAD

**Issue by NetaliDev** [NixOS/nixpkgs#189298]
### Describe the bug
Since the newest JetBrains updates in #186976, it seems like SFTP deployment is broken. I have tested it in PhpStorm and PyCharm and it occurs in both programs.

### Steps To Reproduce
1. Start a JetBrains IDE (like PhpStorm)
2. Add a SFTP deployment (Tools --> Deployment --> Configurations)
3. Create an SSH configuration
4. Click on "Test Connection" in the SSH Configuration
5. The error "Connection to '[my-deployment-target]' failed. Connection failed" occurs.

### Expected behavior
The SSH connection should work

### Notify maintainers

Since the JetBrains packages have no maintainers, I will notify the person who opened the PR:
@GenericNerdyUsername 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@erza:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.63, NixOS, 22.11 (Raccoon), 22.11pre405311.97747d3209e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(netali): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by drupol** [comment]
Same issue.

**Comment by Fryuni** [comment]
There are some other issues introduced on those new versions, those are actual issues on the new version and not on the packing for Nixpkgs. It seems like there were quite a few related to SSH (remote debugger, SFTP, remote interpreter, etc.)

Some of them were fixes on patch releases, we need another update.
It would be great to have a parameter allowing overwriting the version. Something like:
```nix
pkgs.jetbrains.<product>.withVersion {
  version = "2022.2.2"
  sha256 = "..."
}
```

**Comment by fabianhjr** [comment]
>  It would be great to have a parameter allowing overwriting the version. Something like:

You can `overrideAttrs` to override version/src attributes.

**Comment by GenericNerdyUsername** [comment]
Is this SFTP in particular, or a general SSH issue? Connecting to git@github.com over ssh works fine for me. Can you put `~/.cache/JetBrains/PyCharm2022.2/log/idea.log` in a gist and send the link?

**Comment by NetaliDev** [comment]
I think this is the interesting part:
```
2022-09-01 17:39:25,307 [  38972]   INFO - c.j.p.w.c.RemoteConnectionManager$3 - Using "/tmp/vfs_cache" as temporary files store.
2022-09-01 17:39:25,336 [  39001]   FINE - #c.j.p.w.c.RemoteConnection - Opening connection to sftp://[censored]/ in @526e4fc7
2022-09-01 17:39:25,358 [  39023]   WARN - #c.j.p.w.c.RemoteConnection - java/lang/constant/Constable
java.lang.NoClassDefFoundError: java/lang/constant/Constable
	at com.intellij.ssh.config.ProductionSshConnectionConfigDelegate.a(SshConnectionConfigService.kt:251)
	at com.intellij.ssh.config.ProductionSshConnectionConfigDelegate.get(SshConnectionConfigService.kt:219)
	at com.intellij.ssh.config.SshConnectionConfigService.get(SshConnectionConfigService.kt:50)
	at com.intellij.ssh.ConnectionBuilder.buildConnectionConfig(ssh.kt:152)
	at com.intellij.ssh.ConnectionBuilder.buildSessionConfig(ssh.kt:159)
	at com.jetbrains.plugins.webDeployment.connections.platform.PlatformSftpFileProvider.doCreateFileSystem(PlatformSftpFileProvider.java:77)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.tryToCreateFileSystem(AbstractOriginatingFileProvider.java:142)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.getFileSystem(AbstractOriginatingFileProvider.java:89)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:69)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:54)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:649)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:592)
	at com.jetbrains.plugins.webDeployment.connections.RemoteConnectionPool.lambda$createConnection$0(RemoteConnectionPool.java:252)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: java.lang.constant.Constable
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:209)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 23 more
2022-09-01 17:39:25,361 [  39026]   WARN - #c.j.p.w.u.WebServerConfigForm - Connection failed
com.jetbrains.plugins.webDeployment.CustomFileSystemException: Connection failed
	at com.jetbrains.plugins.webDeployment.connections.RemoteConnectionPool.lambda$createConnection$0(RemoteConnectionPool.java:271)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: java/lang/constant/Constable
	at com.intellij.ssh.config.ProductionSshConnectionConfigDelegate.a(SshConnectionConfigService.kt:251)
	at com.intellij.ssh.config.ProductionSshConnectionConfigDelegate.get(SshConnectionConfigService.kt:219)
	at com.intellij.ssh.config.SshConnectionConfigService.get(SshConnectionConfigService.kt:50)
	at com.intellij.ssh.ConnectionBuilder.buildConnectionConfig(ssh.kt:152)
	at com.intellij.ssh.ConnectionBuilder.buildSessionConfig(ssh.kt:159)
	at com.jetbrains.plugins.webDeployment.connections.platform.PlatformSftpFileProvider.doCreateFileSystem(PlatformSftpFileProvider.java:77)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.tryToCreateFileSystem(AbstractOriginatingFileProvider.java:142)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.getFileSystem(AbstractOriginatingFileProvider.java:89)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:69)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:54)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:649)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:592)
	at com.jetbrains.plugins.webDeployment.connections.RemoteConnectionPool.lambda$createConnection$0(RemoteConnectionPool.java:252)
	... 10 more
Caused by: java.lang.ClassNotFoundException: java.lang.constant.Constable
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:209)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 23 more
2022-09-01 17:39:25,613 [  39278]   INFO - #c.i.d.d.s.DbSrcModificationSession$CountedThreadExecutor - DbSrcWriter stopped
2022-09-01 17:39:32,265 [  45930] SEVERE - #c.i.o.a.i.ApplicationImpl - java/lang/constant/Constable
java.lang.NoClassDefFoundError: java/lang/constant/Constable
	at com.intellij.ssh.config.ProductionSshConnectionConfigDelegate.a(SshConnectionConfigService.kt:251)
	at com.intellij.ssh.config.ProductionSshConnectionConfigDelegate.get(SshConnectionConfigService.kt:219)
	at com.intellij.ssh.config.SshConnectionConfigService.get(SshConnectionConfigService.kt:50)
	at com.intellij.ssh.ConnectionBuilder.buildConnectionConfig(ssh.kt:152)
	at com.intellij.ssh.ConnectionBuilder.buildSessionConfig(ssh.kt:159)
	at com.intellij.ssh.ConnectionBuilder.checkCanAuthenticate(ssh.kt:107)
	at com.intellij.ssh.ui.unified.SshCredentialsEditorEx$1.a(SshCredentialsEditorEx.java:72)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: java.lang.constant.Constable
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:209)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 17 more
2022-09-01 17:39:32,269 [  45934] SEVERE - #c.i.o.a.i.ApplicationImpl - PhpStorm 2022.2.1  Build #PS-222.3739.61
2022-09-01 17:39:32,269 [  45934] SEVERE - #c.i.o.a.i.ApplicationImpl - JDK: 11.0.13; VM: OpenJDK 64-Bit Server VM; Vendor: Oracle Corporation
2022-09-01 17:39:32,269 [  45934] SEVERE - #c.i.o.a.i.ApplicationImpl - OS: Linux
```

**Comment by GenericNerdyUsername** [comment]
`java/lang/constant/Constable` was added in [java 12](https://stackoverflow.com/a/68541202), but the jetbrains jdk in nixpkgs is version 11. #183763 should fix this.

**Comment by fabianhjr** [comment]
Hi @NetaliDev, the mentioned PR has been merged. Could you check if the issue was fixed?

**Comment by NetaliDev** [comment]
Yes, it seems to work now
