### ISSUE TITLE
yarn2nix "Couldn't find any versions that matches in our cache"

### ISSUE THREAD

**Issue by GuillaumeDesforges** [NixOS/nixpkgs#190681]
### Describe the bug

I'm trying to package `marp-cli` with `yarn2nix`: https://github.com/marp-team/marp-cli

However build complains with

```
error: builder for '/nix/store/9af4bw297961rx7wc8a2yyzap2fqn0wh-marp-team-marp-cli-modules-2.1.4.drv' failed with exit code 1;
       last 10 log lines:
       > warning Lockfile has incorrect entry for "pug-runtime@^2.0.4". Ignoring it.
       > error Couldn't find any versions for "pug" that matches "^2.0.3" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
       > info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
       > Error: Couldn't find any versions for "pug-runtime" that matches "^2.0.4" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
       >     at MessageError.ExtendableBuiltin (/nix/store/8lajm4glg9v9f7lzpz4r4gm02rqwgnkl-yarn-1.22.18/libexec/yarn/lib/cli.js:721:66)
       >     at new MessageError (/nix/store/8lajm4glg9v9f7lzpz4r4gm02rqwgnkl-yarn-1.22.18/libexec/yarn/lib/cli.js:750:123)
       >     at NpmResolver.<anonymous> (/nix/store/8lajm4glg9v9f7lzpz4r4gm02rqwgnkl-yarn-1.22.18/libexec/yarn/lib/cli.js:50430:15)
       >     at Generator.next (<anonymous>)
       >     at step (/nix/store/8lajm4glg9v9f7lzpz4r4gm02rqwgnkl-yarn-1.22.18/libexec/yarn/lib/cli.js:310:30)
       >     at /nix/store/8lajm4glg9v9f7lzpz4r4gm02rqwgnkl-yarn-1.22.18/libexec/yarn/lib/cli.js:321:13
       For full logs, run 'nix log /nix/store/9af4bw297961rx7wc8a2yyzap2fqn0wh-marp-team-marp-cli-modules-2.1.4.drv'.
error: 1 dependencies of derivation '/nix/store/9lxxd3250h492b4s2lvxcf53ral42mcn-marp-cli.drv' failed to build
```

### Steps To Reproduce

```nix
{
  nixConfig.bash-prompt-prefix = "(nix) ";

  inputs.flake-utils = {
    url = "github:numtide/flake-utils";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        packages.default = pkgs.mkYarnPackage {
          name = "marp-cli";
          version = "2.1.4";
          src = pkgs.fetchFromGitHub {
            owner = "marp-team";
            repo = "marp-cli";
            rev = "v2.1.4";
            sha256 = "TkjaCiKrorYF8Ml8Xps3xZxcN5ePTpv2Jw1c2Icqtm8=";
          };
        };
      }
    );
}
```

### Expected behavior

It should build.

### Additional context

Discourse post: https://discourse.nixos.org/t/mkyarnpackage-lockfile-has-incorrect-entry/21586

It seems that it could be related to pugjs being a monorepo using yarn workspaces: https://github.com/pugjs/pug

### Notify maintainers

Latest contributors: @SuperSandro2000 @sumnerevans @roberth 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.11 (Raccoon), 22.11.20220608.04dcb53`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220530_af23d38`
 - channels(theo): `"home-manager"`
 - channels(root): `"nixos-21.11pre319271.31ffc50c571"`
 - channels(arsleust): `"home-manager"`
 - nixpkgs: `/nix/store/78n6xdchpc0ykc9vpm4vmfmlxvsqnair-source`
```

**Comment by aidalgol** [comment]
I  think this is because that package (`pug-runtime`) is in the `resolutions` section of the `package.json`, which yarn2nix does not seem to pick up on.  I'm running into this with a package I maintain that added a `resolutions` to its `package.json` in the last release.

**Comment by GuillaumeDesforges** [comment]
If I remember correctly, the issue is that mkYarnPackage does not import the workspace resolutions.
See https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/
In this case https://github.com/marp-team/marp-cli/blob/d31219521c9adba7366121f1deaf05394f14c2af/package.json#L162-L165

See https://github.com/NixOS/nixpkgs/pull/214952#issuecomment-1498713830
