### ISSUE TITLE
PySolFC: does not start: "ModuleNotFoundError: No module named 'time.clock'; 'time' is not a package"

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#190799]
### Describe the bug
The package PySolFC is broken: It does not even start but throws an exception.
Looks like noone has ever tested this. :(

### Steps To Reproduce
1. nix-shell -p pysolfc
2. pysol.py
Traceback (most recent call last):
  File "/nix/store/y3xs17qmzs898jyjcbp9vbcj2kkjqhgz-PySolFC-2.6.4/bin/.pysol.py-wrapped", line 37, in <module>
    from pysollib.main import main  # noqa: E402,I202
  File "/nix/store/y3xs17qmzs898jyjcbp9vbcj2kkjqhgz-PySolFC-2.6.4/lib/python3.9/site-packages/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/nix/store/y3xs17qmzs898jyjcbp9vbcj2kkjqhgz-PySolFC-2.6.4/lib/python3.9/site-packages/pysollib/app.py", line 31, in <module>
    from pysollib.gamedb import GAME_DB, GI, loadGame
  File "/nix/store/y3xs17qmzs898jyjcbp9vbcj2kkjqhgz-PySolFC-2.6.4/lib/python3.9/site-packages/pysollib/gamedb.py", line 28, in <module>
    from pysollib.mfxutil import Struct, print_err
  File "/nix/store/y3xs17qmzs898jyjcbp9vbcj2kkjqhgz-PySolFC-2.6.4/lib/python3.9/site-packages/pysollib/mfxutil.py", line 146, in <module>
    uclock = time.clock
AttributeError: module 'time' has no attribute 'clock'

### Notify maintainers
@kierdavis

**Comment by m0rg-dev** [comment]
Just ran into this as well. Looks like `time.clock` was removed in Python 3.8, but also the version of PySolFC in `nixpkgs` is three and a half years (and ten minor versions) old so decent chance bumping the package version takes care of it
