### ISSUE TITLE
protonvpn-gui / protonvpn-cli failing to launch

### ISSUE THREAD

**Issue by nullishamy** [NixOS/nixpkgs#191860]
### Describe the bug
When launching the protonvpn cli / gui tools, they error out with various errors.

### Steps To Reproduce
1. Install the protonvpn tools
2. Launch one of them
3. Observe

### Expected behavior
The tools should launch without issue

### Screenshots
N/A

### Additional context
The mentioned errors:
```py
[nix-shell:~]$ protonvpn
Traceback (most recent call last):
  File "/nix/store/rlrjgw5pc61h4f661j0j0z141664p38r-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 21, in __getitem__
    stored_data = self.__keyring_backend.get_password(
  File "/nix/store/clkgdj9mpr2ips9qv9ymf87fkg6cv9i3-python3.9-keyring-23.5.1/lib/python3.9/site-packages/keyring/backends/kwallet.py", line 110, in get_password
    if not self.connected(service):
  File "/nix/store/clkgdj9mpr2ips9qv9ymf87fkg6cv9i3-python3.9-keyring-23.5.1/lib/python3.9/site-packages/keyring/backends/kwallet.py", line 94, in connected
    bus = dbus.SessionBus(mainloop=DBusGMainLoop())
NameError: name 'dbus' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/xwbpfig11lq1bbyxiawhvixfbdrw58iy-protonvpn-gui-1.8.0/lib/python3.9/site-packages/protonvpn_gui/main.py", line 262, in do_activate
    if not protonvpn.check_session_exists():
  File "/nix/store/rlrjgw5pc61h4f661j0j0z141664p38r-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/api.py", line 356, in check_session_exists
    return self._env.api_session.is_valid
  File "/nix/store/rlrjgw5pc61h4f661j0j0z141664p38r-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/environment.py", line 56, in api_session
    self.__api_session = APISession()
  File "/nix/store/rlrjgw5pc61h4f661j0j0z141664p38r-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/session/session.py", line 224, in __init__
    self.__keyring_load_session()
  File "/nix/store/rlrjgw5pc61h4f661j0j0z141664p38r-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/session/session.py", line 253, in __keyring_load_session
    keyring_data_user = ExecutionEnvironment().keyring[
  File "/nix/store/rlrjgw5pc61h4f661j0j0z141664p38r-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 32, in __getitem__
    raise exceptions.KeyringError(e)
protonvpn_nm_lib.exceptions.KeyringError: name 'dbus' is not defined
```

### Notify maintainers
@WolfangAukang

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
amy:~/ $ nix-shell -p nix-info --run "nix-info -m"                                                                                                                                [0:55:59]
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.67, NixOS, 22.05 (Quokka), 22.05.3050.d86a4619b7e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05"`
 - channels(amy): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by nullishamy** [comment]
update: it works on unstable

**Comment by WolfangAukang** [comment]
#172939 Already solves the issue. Last time I tried to backport, it wasn't able to do that automatically. I will try it once more on #191761
