### ISSUE TITLE
pleroma: could not lookup Ecto repo Pleroma.Repo 

### ISSUE THREAD

**Issue by walkah** [NixOS/nixpkgs#192090]
### Describe the bug

Following the merge of #191237 my pleroma instance no longer starts with the following errors:

```
Sep 19 21:43:47 plato systemd[1]: Started Pleroma social network.
Sep 19 21:43:49 plato pleroma[3078019]: 21:43:49.840 [info] Found emoji packs:
Sep 19 21:43:49 plato pleroma[3078019]: 21:43:49.842 [notice] Application pleroma exited: exited in: Pleroma.Application.start(:normal, [])
Sep 19 21:43:49 plato pleroma[3078019]:     ** (EXIT) an exception was raised:
Sep 19 21:43:49 plato pleroma[3078019]:         ** (RuntimeError) could not lookup Ecto repo Pleroma.Repo because it was not started or it does not exist
Sep 19 21:43:49 plato pleroma[3078019]:             (ecto 3.6.2) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1
Sep 19 21:43:49 plato pleroma[3078019]:             (ecto 3.6.2) lib/ecto/adapter.ex:132: Ecto.Adapter.lookup_meta/1
Sep 19 21:43:49 plato pleroma[3078019]:             (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:409: Ecto.Adapters.SQL.query/4
Sep 19 21:43:49 plato pleroma[3078019]:             (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:367: Ecto.Adapters.SQL.query!/4
Sep 19 21:43:49 plato pleroma[3078019]:             (pleroma 2.4.3) lib/pleroma/application.ex:120: Pleroma.Application.set_postgres_server_version/0
Sep 19 21:43:49 plato pleroma[3078019]:             (pleroma 2.4.3) lib/pleroma/application.ex:113: Pleroma.Application.start/2
Sep 19 21:43:49 plato pleroma[3078019]:             (kernel 8.2) application_master.erl:293: :application_master.start_it_old/4
Sep 19 21:43:51 plato pleroma[3078019]: {"Kernel pid terminated",application_controller,"{application_start_failure,pleroma,{bad_return,{{'Elixir.Pleroma.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<\"could not lookup Ecto repo Pleroma.Repo because it was not started or it does not exist\">>},[{'Elixir.Ecto.Repo.Registry',lookup,1,[{file,\"lib/ecto/repo/registry.ex\"},{line,22},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Adapter',lookup_meta,1,[{file,\"lib/ecto/adapter.ex\"},{line,132}]},{'Elixir.Ecto.Adapters.SQL',query,4,[{file,\"lib/ecto/adapters/sql.ex\"},{line,409}]},{'Elixir.Ecto.Adapters.SQL','query!',4,[{file,\"lib/ecto/adapters/sql.ex\"},{line,367}]},{'Elixir.Pleroma.Application',set_postgres_server_version,0,[{file,\"lib/pleroma/application.ex\"},{line,120}]},{'Elixir.Pleroma.Application',start,2,[{file,\"lib/pleroma/application.ex\"},{line,113}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}}"}
Sep 19 21:43:51 plato pleroma[3078019]: Kernel pid terminated (application_controller) ({application_start_failure,pleroma,{bad_return,{{'Elixir.Pleroma.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"could not lookup Ecto repo Pleroma.Repo because it was not started or it does not exist">>},[{'Elixir.Ecto.Repo.Registry',lookup,1,[{file,"lib/ecto/repo/registry.ex"},{line,22},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Adapter',lookup_meta,1,[{file,"lib/ecto/adapter.ex"},{line,132}]},{'Elixir.Ecto.Adapters.SQL',query,4,[{file,"lib/ecto/adapters/sql.ex"},{line,409}]},{'Elixir.Ecto.Adapters.SQL','query!',4,[{file,"lib/ecto/adapters/sql.ex"},{line,367}]},{'Elixir.Pleroma.Application',set_postgres_server_version,0,[{file,"lib/pleroma/application.ex"},{line,120}]},{'Elixir.Pleroma.Application',start,2,[{file,"lib/pleroma/application.ex"},{line,113}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}}})
Sep 19 21:43:51 plato pleroma[3078019]:
Sep 19 21:43:51 plato pleroma[3078019]: Crash dump is being written to: erl_crash.dump...done
Sep 19 21:43:51 plato systemd[1]: pleroma.service: Main process exited, code=exited, status=1/FAILURE
Sep 19 21:43:51 plato systemd[1]: pleroma.service: Failed with result 'exit-code'.
Sep 19 21:43:51 plato systemd[1]: pleroma.service: Consumed 6.607s CPU time, received 52.3K IP traffic, sent 10.1K IP traffic.
```

I am still able to connect to the database (`postgresql_12`) as the `pleroma` user. I deployed the commit hash just before that change - 684a9bc32a249f7a7f278e889a37e4fcd8ea965b - and it works. Updating to 

### Steps To Reproduce
1. Deploy pleroma using this config: https://github.com/walkah/athens/blob/main/modules/pleroma/default.nix) and nixpkgs 684a9bc32a249f7a7f278e889a37e4fcd8ea965b
2. Update nixpkgs to 9afb94475819cf490d8d024a29f6f374560041e5
3. pleroma fails to restart

### Expected behavior
Pleroma should start and run.

### Notify maintainers

@ninjatrappeur
@yu-re-ka 
@Kloenk 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.55, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager, nixos-21.11pre319562.c21ba4f7bb4"`
 - channels(walkah): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by walkah** [comment]
Well, as of de3758e31a3a1bc79d569f5deb5dac39791bf9b6 the issue seems to no longer occur. Perhaps it was just a glitch on my server 👻
