### ISSUE TITLE
Semgrep crashes on `semgrep scan`

### ISSUE THREAD

**Issue by spagy** [NixOS/nixpkgs#192149]
### Describe the bug
When you run `semgrep scan` it crashes with `Permission denied`, due to it trying to execute the `semgrep-core` binary, which doesn't have  that doesn't have it's executable bit set.
The `semgrep-core` binary has permissions `-r--r--r--`.

### Steps To Reproduce
1. Get a hold of `semgrep` packaged by nix
  `nix-shell -p semgrep`
2. Make a valid semgrep config file, otherwise `semgrep` complains about this and exits before it has the chance to crash.
    ```sh
    cat <<EOF > rule.yaml
    rules:
      - id: test-rule
        patterns:
          - pattern: "test"
        message: This is a message
        severity: WARNING
        languages:
          - typescript
    EOF
    ```
4. Make an empty directory for semgrep to look through, this helps it to crash quickly.
    `mkdir emptydir`
5. Run semgrep
    `semgrep scan --config=rule.yaml emptydir`
6. See that semgrep crashed which `Permission denied: '/nix/store/...-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/bin/semgrep-core'`

### Expected behavior
Semgrep doesn't crash, and reports/acts as specified in the config file.

### Additional context
<details>
<summary>Full stderr output</summary>

```
[Errno 13] Permission denied: '/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/bin/semgrep-core'
Traceback (most recent call last):
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/commands/scan.py", line 817, in scan
    ) = semgrep.semgrep_main.main(
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 410, in main
    ) = run_rules(
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 168, in run_rules
    ) = core_runner.invoke_semgrep(
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/core_runner.py", line 951, in invoke_semgrep
    ) = self._run_rules_direct_to_semgrep_core(
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/core_runner.py", line 869, in _run_rules_direct_to_semgrep_core
    returncode = runner.execute()
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/core_runner.py", line 396, in execute
    rc = asyncio.run(self._stream_exec_subprocess())
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/core_runner.py", line 307, in _stream_exec_subprocess
    process = await asyncio.create_subprocess_exec(
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/unix_events.py", line 799, in _start
    self._proc = subprocess.Popen(
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/bin/semgrep-core'
```
</details>

### Notify maintainers
@06kellyjac @ambroisie 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.5, NixOS, 22.11 (Raccoon), 22.11pre405560.2da64a81275`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(user): `"home-manager"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by 06kellyjac** [comment]
Thanks for raising this.
It's installed with 755 perms so it should end up executable in the nix store...

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/semgrep/semgrep-core.nix#L14

I'm guessing it's actually a linking issue if you double check the permissions of the file. Their pre-built semgrep-core is meant to be static so its a bit odd that it's started having issues

`ldd` or `file` might show something

Im away from my dev machine right now so i cant do any debugging

**Comment by spagy** [comment]
Thanks for the quick reply!

It looks like that link is to the `semgrep-core` package. For me that package provides a `semgrep-core` binary, with executable permissions (although 555 not 755 seemingly). That doesn't seem to be the copy of `semgrep-core` that the `semgrep` package uses though.

If just install `semgrep` there's no copy of the `semgrep-core` _package_ on my machine, just a copy of the `semgrep-core` binary with 444 permissions with this path /nix/store/...-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/bin/semgrep-core.

If I install both the `semgrep-core` package and the `semgrep` package, then I have two `semgrep-core` binaries. The one provided by the `semgrep-core` package has 555 permissions, but isn't used by the `semgrep` python script.

Let me know if there's any more info I could provide to help.

**Comment by 06kellyjac** [comment]
Ahh i see.


https://github.com/returntocorp/semgrep/blob/v0.114.0/cli/setup.py#L90

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/semgrep/default.nix#L21

It should use "our" semgrep-core because of these bits. Im not sure why its changed since this file seems unchanged.
Might be a change in their "wrapper"
