### ISSUE TITLE
pymol complains that Qt is not available

### ISSUE THREAD

**Issue by sepiabrown** [NixOS/nixpkgs#192555]
### Steps To Reproduce
1. `nix run` the following `flake.nix`.
```
{
  description = "A very basic flake";

  outputs = { self, nixpkgs }: {

    packages.x86_64-linux.pymol = nixpkgs.legacyPackages.x86_64-linux.pymol;

    defaultPackage.x86_64-linux = self.packages.x86_64-linux.pymol;

  };
}
```
### Build log
```
warning: creating lock file '/home/sepiabrown/Desktop/AIDrugDiscoveryDay2/flake.lock'
Qt not available (pymol.Qt), using GLUT/Tk interface Traceback (most recent call last):
   File "/nix/store/1qm4npwi0k57pr2mjvjpvmcqprp62lnf-pymol-2.5.0/lib/python/pymol/__init__.py", line 73, in <module>     sys.exit(pymol.launch(args))
   File "/nix/store/1qm4npwi0k57pr2mjvjpvmcqprp62lnf-pymol-2.5.0/lib/python/pymol/__init__.py", line 429, in launch     _cmd.runpymol(None, block_input_hook)
NotImplementedError: compile with --glut
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.19, NixOS, 22.11 (Raccoon), 22.11.20220918.f677051`
 - multi-user?: `yes`  
 - sandbox: `yes`  
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sepiabrown** [comment]
@samlich

**Comment by samlich** [comment]
Thanks; should be fixed by that pull request. `nix run "github:samlich/nixpkgs#pymol"` should work. Since I'm not on unstable, I have to use `QT_PLUGIN_PATH="" nix run "github:samlich/nixpkgs#pymol"` though.
