### ISSUE TITLE
RuntimeError: PyTorch is not linked with support for X devices

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#192596]
### Describe the bug

I'm testing https://github.com/NixOS/nixpkgs/pull/192391 and would like to use my AMD GPU. Since i don't have HIP setup yet (CUDA translation), i tried OpenCL, Vulkan and OpenGL. All fail with this error.

```
[davidak@gaming:~]$ whisper --device opencl --model medium --language de test.mp4
Traceback (most recent call last):
  File "/nix/store/c1fkpcpz17mccwk9q586a6y2smlwzsbd-python3.10-whisper-unstable-2022-09-21/bin/.whisper-wrapped", line 9, in <module>
    sys.exit(cli())
  File "/nix/store/c1fkpcpz17mccwk9q586a6y2smlwzsbd-python3.10-whisper-unstable-2022-09-21/lib/python3.10/site-packages/whisper/transcribe.py", line 276, in cli
    model = load_model(model_name).to(device)
  File "/nix/store/0rz5lf0gzlc7a5zsigbk354bdwmnaxl8-python3.10-torch-1.12.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/nix/store/0rz5lf0gzlc7a5zsigbk354bdwmnaxl8-python3.10-torch-1.12.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/nix/store/0rz5lf0gzlc7a5zsigbk354bdwmnaxl8-python3.10-torch-1.12.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/nix/store/0rz5lf0gzlc7a5zsigbk354bdwmnaxl8-python3.10-torch-1.12.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/nix/store/0rz5lf0gzlc7a5zsigbk354bdwmnaxl8-python3.10-torch-1.12.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: PyTorch is not linked with support for opencl devices
```

### Steps To Reproduce
1. `nix run nixpkgs#nixpkgs-review pr 192391`
2. open another shell and run the result there (it fails in nixpkgs-review shell)
3. 

```
[nix-shell:~/.cache/nixpkgs-review/pr-192391]$ ll results/
total 4
lrwxrwxrwx 1 davidak users 82 Sep 23 10:15 openai-whisper -> /nix/store/c1fkpcpz17mccwk9q586a6y2smlwzsbd-python3.10-whisper-unstable-2022-09-21
```
4. `/nix/store/c1fkpcpz17mccwk9q586a6y2smlwzsbd-python3.10-whisper-unstable-2022-09-21/bin/whisper --device opencl --model medium --language de test.wav`

### Expected behavior

>Options for --device appear to include: cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, ort, mps, xla, lazy, vulkan, meta, hpu, privateuseone

Source: https://github.com/openai/whisper/discussions/55

I don't know what most of these are, but if most PyTorch distributions support them, ours should too.

`cpu` works, but is slow. `cuda` might work on nvidia, when `cudaSupport` is enabled for PyTorch.

### Notify maintainers
@mweinelt @teh @thoughtpolice 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.67, NixOS, 22.05 (Quokka), 22.05.3065.178fea1414a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Madouura** [comment]
Planning to implement ROCm support for pytorch.
Related:  #197885

**Comment by Madouura** [comment]
We added ROCm support to torch in e539c148f39d7450c6ac701f0ec3404568764859.
I'm not sure how OpenCL support is going to go, but if you use an AMD GPU you should be set for now.

**Comment by LunNova** [comment]
torch with ROCm is actively maintained so closing this as the main request should be satisfied.

While torch does have a USE_OPENCL flag, it's not in a usable state so there's not any actionable work on our side unless upstream improve it. https://github.com/pytorch/pytorch/issues/87350
