### ISSUE TITLE
Thunderbird doesn't start with grsecurity enabled

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#19403]
## Issue description
When grsecurity is enabled with ```security.grsecurity.enable = true;``` thunderbird fails to start: 
```
$ thunderbird
out of memory
Assertion failure: [unhandlable oom] OOM in createJitRuntime, at /tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/js/src/jscntxt.cpp:1228
[1]    15386 segmentation fault  thunderbird
```
An extract from ```strace -f -ff  -e mmap,munmap,mprotect,open thunderbird```:
```
[pid  1712] mmap(NULL, 65536, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 EPERM (Operation not permitted)
out of memory
Assertion failure: [unhandlable oom] OOM in createJitRuntime, at /tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/js/src/jscntxt.cpp:1228
[pid  1712] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
```

### Steps to reproduce
* rebuild with ```security.grsecurity.enable = true;```  and reboot
* launch thunderbird

## Technical details

* System: 16.09.695.45b2a6d (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.695.45b2a6d
* Thunderbird 45.3.0

**Comment by joachifm** [comment]
Probably needs a `paxmark m`

**Comment by joachifm** [comment]
@symphorien can you test that #19515 fixes the issue for you?

**Comment by symphorien** [comment]
I did that : 
```
$ git clone github:joachifm/nixpkgs
$ cd nixpkgs
$ git checkout thunderbird-pax
$ nix-env -i thunderbird -f default.nix
[ enable security.grsecurity.enable = true; and reboot ]
$ thunderbird
out of memory
Assertion failure: [unhandlable oom] OOM in createJitRuntime, at /tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/js/src/jscntxt.cpp:1228
[1]    3859 segmentation fault  thunderbird
$ paxctl -v $(where thunderbird)
- PaX flags: -------x-e-- [/home/symphorien/.nix-profile/bin/thunderbird]
	RANDEXEC is disabled
	EMUTRAMP is disabled
```
Apparently it doesn't work. Should I compile thunderbird while the kernel is hardened ? Does it make any difference ?

**Comment by symphorien** [comment]
I tried to build with the hardened kernel : the build failed.
```
[...]
77:16.35 We know it took a while, but your build finally finished successfully!
To view resource usage of the build, run |mach resource-usage|.
To take your build for a test drive, run: |mach run|
glibPreInstallPhase
installing
 0:01.35 /nix/store/zyg42aqgxxr289qh6dsbg3m9643c65v8-gnumake-4.2.1/bin/make -C . -j1 -s -w install
 0:01.37 make: Entering directory '/tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/objdir'
 0:01.41 make[1]: Entering directory '/tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/objdir/mail/installer'
 0:12.86 Executing /tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/objdir/dist/bin/xpcshell -g /tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/objdir/dist/bin/ -a /tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/objdir/dist/bin/ -f /tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/toolkit/mozapps/installer/precompile_cache.js -e precompile_startupcache("resource://gre/");
 0:15.27 out of memory
 0:15.27 Assertion failure: [unhandlable oom] OOM in createJitRuntime, at /tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/js/src/jscntxt.cpp:1228
 0:15.28 Traceback (most recent call last):
 0:15.28   File "/tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/toolkit/mozapps/installer/packager.py", line 406, in <module>
 0:15.28     main()
 0:15.28   File "/tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/toolkit/mozapps/installer/packager.py", line 400, in main
 0:15.28     args.source, gre_path, base)
 0:15.28   File "/tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/toolkit/mozapps/installer/packager.py", line 161, in precompile_cache
 0:15.28     errors.fatal('Error while running startup cache precompilation')
 0:15.28   File "/tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/python/mozbuild/mozpack/errors.py", line 103, in fatal
 0:15.36     self._handle(self.FATAL, msg)
 0:15.36   File "/tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/python/mozbuild/mozpack/errors.py", line 98, in _handle
 0:15.36     raise ErrorMessage(msg)
 0:15.36 mozpack.errors.ErrorMessage: Error: Error while running startup cache precompilation
 0:15.38 make[1]: *** [/tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/toolkit/mozapps/installer/packager.mk:41: stage-package] Error 1
 0:15.38 make[1]: Leaving directory '/tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/objdir/mail/installer'
 0:15.38 make: *** [/tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/mozilla/../mail/build.mk:19: install] Error 2
 0:15.38 make: Leaving directory '/tmp/nix-build-thunderbird-45.3.0.drv-0/thunderbird-45.3.0/objdir'
builder for ‘/nix/store/blgj4gvzsg5056r41jm91cvwpdrhsznx-thunderbird-45.3.0.drv’ failed with exit code 2
error: build of ‘/nix/store/blgj4gvzsg5056r41jm91cvwpdrhsznx-thunderbird-45.3.0.drv’ failed
```

**Comment by joachifm** [comment]
Okay. Thank you for testing.

Whether hardening is enabled during the build shouldn't matter here.

The `paxctl` output you showed suggests the marking didn't "take" for some reason, how vexing ... Forcibly setting `m` on the thunderbird binary does work (this is how I tested it, building thunderbird is infeasible for me). 

All I can think of right now is that `paxctl` and `patchelf` may be interacting badly, so `paxctl` might need to run after the fixup phase.

**Comment by symphorien** [comment]
How can I set "forcibly" the -m flag on the binary as you did ? paxctl fails with "Read-only file system"

**Comment by joachifm** [comment]
You'd have to remount it read-write, as in `mount -o remount,rw /nix/store`, but it's not something I recommend doing :)
