### ISSUE TITLE
Cannot use nixops 1.7 from nixos 22.05 channel

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#194235]
### Describe the bug
After migrating nixos channel from `21.11` to `22.05`, `nixops` stop working. The problem happens when trying to upload the keys to the machine:

```console
mymachine> uploading key ‘mysecret’...
mymachine> scp: Connection closed
mymachine> error: Traceback (most recent call last):
  File "/nix/store/s4c0ra1f4p7y9hv2cljwnfwngid4x5yl-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 727, in worker
    m.send_keys()
  File "/nix/store/s4c0ra1f4p7y9hv2cljwnfwngid4x5yl-nixops-1.7/lib/python2.7/site-packages/nixops/backends/__init__.py", line 243, in send_keys
    self.upload_file(tmp, tmp_outfile)
  File "/nix/store/s4c0ra1f4p7y9hv2cljwnfwngid4x5yl-nixops-1.7/lib/python2.7/site-packages/nixops/backends/__init__.py", line 394, in upload_file
    return self._logged_exec(cmdline)
  File "/nix/store/s4c0ra1f4p7y9hv2cljwnfwngid4x5yl-nixops-1.7/lib/python2.7/site-packages/nixops/backends/__init__.py", line 324, in _logged_exec
    return nixops.util.logged_exec(command, self.logger, **kwargs)
  File "/nix/store/s4c0ra1f4p7y9hv2cljwnfwngid4x5yl-nixops-1.7/lib/python2.7/site-packages/nixops/util.py", line 152, in logged_exec
    raise CommandFailed(err, res)
CommandFailed: command ‘['scp', '-P', '22', '-o', 'StrictHostKeyChecking=accept-new', '-i', '/run/user/1000/nixops-tmposzcAx/id_nixops-mymachine', '-oControlPath=/run/user/1000/nixops-ssh-tmpEzTDhl/master-socket', u'/run/user/1000/nixops-tmposzcAx/key-mymachine', u'root@mymachine.example.com:/var/keys/.mysecret.tmp']’ failed on machine ‘mymachine’ (exit code 255)
```

I believe this due to PR https://github.com/NixOS/nixpkgs/pull/154715.

### Expected behavior
Should just work as before

### Notify maintainers

@adisbladis: any idea what is happening?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.70, NixOS, 22.05 (Quokka), 22.05.3389.9cac4585028`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(me): `"home-manager-22.05.tar.gz"`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
> mymachine> scp: Connection closed

This is likely a problem with your specific setup, that you cannot login via ssh into the machine.
