### ISSUE TITLE
Nixpkgs documentation fails to build on `x86_64-darwin`

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixpkgs#195346]
### Steps To Reproduce
On `x86_64-darwin`
```console
cd doc
nix-build
```

### Build log

<details>

```log
building '/nix/store/swak37kf67jx3l47s53km3lmiq001bdx-python3.10-bootstrapped-pip-22.2.2.drv'...
Sourcing pip-install-hook
Sourcing setuptools-build-hook
Using setuptoolsShellHook
unpacking sources
unpacking source archive /nix/store/3dki8ikais8yg1npyrznzd39vpg66d79-wheel-0.37.1-source
unpacking source archive /nix/store/a859qkahn9df557sbvi4nl18clpqdwsa-pip-22.2.2-source
unpacking source archive /nix/store/q8xnkf2y40dmxqbrb6f19iffg5bskzck-setuptools-65.3.0-sdist.tar.gz
source root is .
patching sources
configuring
no configure script, doing nothing
installing
Building setuptools wheel...
/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/setuptools /private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0
Traceback (most recent call last):
  File "/nix/store/4vv7gsn0x97gw4383bs4a3qs3l8ky537-python3-minimal-3.10.7/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/4vv7gsn0x97gw4383bs4a3qs3l8ky537-python3-minimal-3.10.7/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_internal/configuration.py", line 20, in <module>
    from pip._internal.exceptions import (
  File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_internal/exceptions.py", line 13, in <module>
    from pip._vendor.requests.models import Request, Response
  File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_vendor/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_vendor/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_vendor/requests/compat.py", line 35, in <module>
    from http import cookiejar as cookielib
  File "/nix/store/4vv7gsn0x97gw4383bs4a3qs3l8ky537-python3-minimal-3.10.7/lib/python3.10/http/cookiejar.py", line 36, in <module>
    import urllib.parse, urllib.request
  File "/nix/store/4vv7gsn0x97gw4383bs4a3qs3l8ky537-python3-minimal-3.10.7/lib/python3.10/urllib/request.py", line 2622, in <module>
    from _scproxy import _get_proxy_settings, _get_proxies
ModuleNotFoundError: No module named '_scproxy'
error: builder for '/nix/store/swak37kf67jx3l47s53km3lmiq001bdx-python3.10-bootstrapped-pip-22.2.2.drv' failed with exit code 1;
       last 10 log lines:
       >     from .exceptions import RequestsDependencyWarning
       >   File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_vendor/requests/exceptions.py", line 9, in <module>
       >     from .compat import JSONDecodeError as CompatJSONDecodeError
       >   File "/private/tmp/nix-build-python3.10-bootstrapped-pip-22.2.2.drv-0/pip/src/pip/_vendor/requests/compat.py", line 35, in <module>
       >     from http import cookiejar as cookielib
       >   File "/nix/store/4vv7gsn0x97gw4383bs4a3qs3l8ky537-python3-minimal-3.10.7/lib/python3.10/http/cookiejar.py", line 36, in <module>
       >     import urllib.parse, urllib.request
       >   File "/nix/store/4vv7gsn0x97gw4383bs4a3qs3l8ky537-python3-minimal-3.10.7/lib/python3.10/urllib/request.py", line 2622, in <module>
       >     from _scproxy import _get_proxy_settings, _get_proxies
       > ModuleNotFoundError: No module named '_scproxy'
       For full logs, run 'nix log /nix/store/swak37kf67jx3l47s53km3lmiq001bdx-python3.10-bootstrapped-pip-22.2.2.drv'.
error: 1 dependencies of derivation '/nix/store/hdyc7mlcalqd45qjxix8rfbc6ima3lfw-python3.10-pip-22.2.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zv91q0sb3ykf23y8d8nixkqbynpvswv0-python3.10-setuptools-65.3.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pawa60sjzcxha38iykpbcipnamjzk2gc-python3.10-wheel-0.37.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mk7vwydr6nawwr2z7z7ng8w4cw5iiiqm-python3.10-mistune-2.0.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lkzq9yirxaa8qr6nlr2p92hq3xx24ajq-python3-minimal-3.10.7-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qqqayhw6m5gl398ww5iq86fsnz5b1p0y-options.json.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wk62nf4iafi1plwkvnwkg278vvshiymd-options.xml.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wlbmhbg4z9nqh13ax6jxb9xcpgsxdfi8-options-docbook.xml.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bzfga6cci2zw28m4i4kb5l8bpb8fpqwf-doc-support.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8d1ch1iizfgdrkjr2yykfd4cmrjq3yz0-nixpkgs-manual.drv' failed to build
```
</details>

### Additional context

This precludes contributions to Nixpkgs documentation by Intel Darwin users!

Same problem as here: https://github.com/NixOS/nixpkgs/issues/101229#issuecomment-1086295309

### Notify maintainers

@NixOS/darwin-maintainers 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by winterqt** [comment]
This is fixed by #185351. I just need to fix the comment explaining the issue, then I'll merge.
