### ISSUE TITLE
roxterm segfault

### ISSUE THREAD

**Issue by aristidb** [NixOS/nixpkgs#19579]
## Issue description

roxterm segmentation fault after repeating a message about VTE for a few seconds:

```
** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable

** (roxterm:2880): WARNING **: VTE's inner-border property unavailable
Segmentation fault
```

Roxterm info:

```
$ which roxterm
/run/current-system/sw/bin/roxterm
$ ls -l /run/current-system/sw/bin/roxterm
lrwxrwxrwx 2 root root 69  1. Jan 1970  /run/current-system/sw/bin/roxterm -> /nix/store/m8ihm02qlnbindvgniqyx4ykrj8pz07j-roxterm-2.9.4/bin/roxterm
```

Backtrace:

```
#0  0x00007fffedfd4fd0 in vfprintf () from /nix/store/23vndix3mzcyw84kag06h8fh464g32nq-glibc-2.24/lib/libc.so.6
#1  0x00007fffedfd8063 in buffered_vfprintf () from /nix/store/23vndix3mzcyw84kag06h8fh464g32nq-glibc-2.24/lib/libc.so.6
#2  0x00007fffedfd512d in vfprintf () from /nix/store/23vndix3mzcyw84kag06h8fh464g32nq-glibc-2.24/lib/libc.so.6
#3  0x00007fffee0843f9 in __fprintf_chk () from /nix/store/23vndix3mzcyw84kag06h8fh464g32nq-glibc-2.24/lib/libc.so.6
#4  0x00007fffee80ccea in g_log_writer_standard_streams () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libglib-2.0.so.0
#5  0x00007fffee80cdd7 in g_log_writer_default () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libglib-2.0.so.0
#6  0x00007fffee80b2fc in g_log_structured_array () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libglib-2.0.so.0
#7  0x00007fffee80b7bc in g_log_default_handler () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libglib-2.0.so.0
#8  0x00007fffee80bae4 in g_logv () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libglib-2.0.so.0
#9  0x00007fffee80bcef in g_log () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libglib-2.0.so.0
#10 0x00000000004191e2 in roxterm_get_vte_padding ()
#11 0x00000000004193a1 in roxterm_geometry_func ()
#12 0x000000000041975d in roxterm_update_geometry.isra ()
#13 0x00007fffeece79df in g_closure_invoke () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#14 0x00007fffeecf9a71 in signal_emit_unlocked_R () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#15 0x00007fffeed0281c in g_signal_emit_valist () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#16 0x00007fffeed02b4f in g_signal_emit () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#17 0x00007ffff6d21933 in _gtk_widget_set_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#18 0x00007ffff6a64864 in gtk_widget_get_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#19 0x00007ffff7b544fc in vte_terminal_set_font_full_internal () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#20 0x00007ffff7b543dd in vte_terminal_ensure_font () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#21 0x00007ffff7b64dd8 in vte_terminal_get_char_width () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#22 0x00000000004193a9 in roxterm_geometry_func ()
#23 0x000000000041975d in roxterm_update_geometry.isra ()
#24 0x00007fffeece79df in g_closure_invoke () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#25 0x00007fffeecf9a71 in signal_emit_unlocked_R () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26 0x00007fffeed0281c in g_signal_emit_valist () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#27 0x00007fffeed02b4f in g_signal_emit () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#28 0x00007ffff6d21933 in _gtk_widget_set_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#29 0x00007ffff6a64864 in gtk_widget_get_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#30 0x00007ffff7b544fc in vte_terminal_set_font_full_internal () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#31 0x00007ffff7b543dd in vte_terminal_ensure_font () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#32 0x00007ffff7b64dd8 in vte_terminal_get_char_width () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#33 0x00000000004193a9 in roxterm_geometry_func ()
#34 0x000000000041975d in roxterm_update_geometry.isra ()
#35 0x00007fffeece79df in g_closure_invoke () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#36 0x00007fffeecf9a71 in signal_emit_unlocked_R () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#37 0x00007fffeed0281c in g_signal_emit_valist () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#38 0x00007fffeed02b4f in g_signal_emit () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#39 0x00007ffff6d21933 in _gtk_widget_set_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#40 0x00007ffff6a64864 in gtk_widget_get_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#41 0x00007ffff7b544fc in vte_terminal_set_font_full_internal () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#42 0x00007ffff7b543dd in vte_terminal_ensure_font () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#43 0x00007ffff7b64dd8 in vte_terminal_get_char_width () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#44 0x00000000004193a9 in roxterm_geometry_func ()
#45 0x000000000041975d in roxterm_update_geometry.isra ()
#46 0x00007fffeece79df in g_closure_invoke () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#47 0x00007fffeecf9a71 in signal_emit_unlocked_R () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#48 0x00007fffeed0281c in g_signal_emit_valist () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#49 0x00007fffeed02b4f in g_signal_emit () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#50 0x00007ffff6d21933 in _gtk_widget_set_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#51 0x00007ffff6a64864 in gtk_widget_get_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#52 0x00007ffff7b544fc in vte_terminal_set_font_full_internal () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#53 0x00007ffff7b543dd in vte_terminal_ensure_font () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#54 0x00007ffff7b64dd8 in vte_terminal_get_char_width () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#55 0x00000000004193a9 in roxterm_geometry_func ()
#56 0x000000000041975d in roxterm_update_geometry.isra ()
...
#26355 0x00007ffff7b64dd8 in vte_terminal_get_char_width () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#26356 0x00000000004193a9 in roxterm_geometry_func ()
#26357 0x000000000041975d in roxterm_update_geometry.isra ()
#26358 0x00007fffeece79df in g_closure_invoke () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26359 0x00007fffeecf9a71 in signal_emit_unlocked_R () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26360 0x00007fffeed0281c in g_signal_emit_valist () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26361 0x00007fffeed02b4f in g_signal_emit () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26362 0x00007ffff6d21933 in _gtk_widget_set_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#26363 0x00007ffff6a64864 in gtk_widget_get_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#26364 0x00007ffff7b544fc in vte_terminal_set_font_full_internal () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#26365 0x00007ffff7b543dd in vte_terminal_ensure_font () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#26366 0x00007ffff7b64dd8 in vte_terminal_get_char_width () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#26367 0x00000000004193a9 in roxterm_geometry_func ()
#26368 0x000000000041975d in roxterm_update_geometry.isra ()
#26369 0x00007fffeece79df in g_closure_invoke () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26370 0x00007fffeecf9a71 in signal_emit_unlocked_R () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26371 0x00007fffeed0281c in g_signal_emit_valist () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26372 0x00007fffeed02b4f in g_signal_emit () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26373 0x00007ffff6d21933 in _gtk_widget_set_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#26374 0x00007ffff6a64864 in gtk_widget_get_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#26375 0x00007ffff7b544fc in vte_terminal_set_font_full_internal () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#26376 0x00007ffff7b543dd in vte_terminal_ensure_font () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#26377 0x00007ffff7b64dd8 in vte_terminal_get_char_width () from /nix/store/ljdx357fj5513a7kpcsglnps0hvrv6nn-vte-0.36.3/lib/libvte2_90.so.9
#26378 0x00000000004193a9 in roxterm_geometry_func ()
#26379 0x000000000041975d in roxterm_update_geometry.isra ()
#26380 0x00007fffeece79df in g_closure_invoke () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26381 0x00007fffeecf9a71 in signal_emit_unlocked_R () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26382 0x00007fffeed0281c in g_signal_emit_valist () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26383 0x00007fffeed02b4f in g_signal_emit () from /nix/store/9k4q6dk53sq5nxql8sn8rlc98ikdg4l8-glib-2.50.1/lib/libgobject-2.0.so.0
#26384 0x00007ffff6d21933 in _gtk_widget_set_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
#26385 0x00007ffff6a64864 in gtk_widget_get_style () from /nix/store/vk9hiipr0fpwbvybajxbkmc65ripvmgn-gtk+3-3.22.1/lib/libgtk-3.so.0
...
```

Clearly infinite recursion related to VTE!
### Steps to reproduce

Run "roxterm" from inside X11
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
]$ nixos-version 
17.03.git.d2238cc (Gorilla)
```
- Nix version: (run `nix-env --version`)

```
$ nix-env --version
nix-env (Nix) 1.11.4
```
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03.git.d2238cc"
```

**Comment by aristidb** [comment]
Probably relevant: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838586

**Comment by aristidb** [comment]
I tried updating to roxterm 2.9.7 and it did not fix it. We might need to switch to roxterm 3, but that brings new dependencies which I don't fully understand (like "po4a"), so not sure what to do about this...

I switched to using gnome-terminal for now.
