### ISSUE TITLE
Guake broken

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#19576]
## Issue description

Guake doesn't start. I followed the instructions [here](https://nixos.org/wiki/Solve_GConf_errors_when_running_GNOME_applications) and [here](https://gist.github.com/joepie91/ce9267788fdcb37f5941be5a04fcdd0f#guake-doesnt-start-because-of-a-gconf-issue) with no effect. (Had to use `services.dbus.packages = [ pkgs.gnome3.gconf ];` instead of what was instructed.)
### Steps to reproduce

Add `guake` to system packages. Then try to run it:

```
$ guake
```

You should see the following output (and guake terminal doesn't appear):

```
(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2128): libglade-WARNING **: unknown attribute `swapped' for <signal>.
INFO:guake.guake_app:Logging configuration complete
/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/guake_app.py:1749: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
  self.mainframe.pack_start(self.notebook, expand=True, fill=True, padding=0)
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 390, in reload_global
    key = entry.get_value().get_string()
AttributeError: 'NoneType' object has no attribute 'get_string'
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 415, in reload_accelerators
    self.load_accelerators()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 422, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('reset_terminal'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 257, in fstyle_changed
    font = FontDescription(entry.value.get_string())
AttributeError: 'NoneType' object has no attribute 'get_string'
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 266, in fcolor_changed
    fgcolor = gtk.gdk.color_parse(entry.value.get_string())
AttributeError: 'NoneType' object has no attribute 'get_string'
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 282, in fpalette_changed
    client.get_string(KEY('/style/font/color')))
TypeError: color_parse() argument 1 must be string, not None
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 243, in allow_bold_toggled
    term.set_allow_bold(entry.value.get_bool())
AttributeError: 'NoneType' object has no attribute 'get_bool'
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 312, in bgcolor_changed
    bgcolor = gtk.gdk.color_parse(entry.value.get_string())
AttributeError: 'NoneType' object has no attribute 'get_string'
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 323, in bgimage_changed
    self.guake.set_background_image(entry.value.get_string())
AttributeError: 'NoneType' object has no attribute 'get_string'
Traceback (most recent call last):
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/gconfhandler.py", line 330, in bgtransparency_changed
    self.guake.set_background_transparency(entry.value.get_int())
AttributeError: 'NoneType' object has no attribute 'get_int'
Traceback (most recent call last):
  File "/nix/store/w9020qsqapllmfcdh2x686y8ng6n15mh-python-2.7.12/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/nix/store/w9020qsqapllmfcdh2x686y8ng6n15mh-python-2.7.12/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/main.py", line 239, in <module>
    exec_main()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/main.py", line 235, in exec_main
    if not main():
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/main.py", line 151, in main
    instance = Guake()
  File "/nix/store/9s1xyfrnwk5rqsp431lmk2qlgxqn0ibj-guake-0.8.3/lib/python2.7/site-packages/guake/guake_app.py", line 339, in __init__
    keyval, mask = gtk.accelerator_parse(key)
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None
```
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
$ nixos-version
17.03pre92039.adfcc2d (Gorilla)
```
- Nix version: (run `nix-env --version`)

```
$ nix-env --version
nix-env (Nix) 1.11.4
```
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03pre92039.adfcc2d"
```

**Comment by Mic92** [comment]
Does it work with a clean configuration?

**Comment by PanAeon** [comment]
Hi, does adding `services.dbus.packages = [ pkgs.gnome3.gconf ];` solved the issue?

**Comment by jluttine** [comment]
I think it didn't solve it. But I moved to KDE and Yakuake, so I'm not using Guake anymore. Perhaps I'll just close this but if someone experiences this bug, then this can be reopened.

**Comment by PanAeon** [comment]
Please, don't close this issue. I'm experiencing the same problem on `17.03.1152.22da5d0246` with guake and pomodoro timer.

**Comment by jluttine** [comment]
Ah, ok! :)

**Comment by PanAeon** [comment]
@jluttine Hi, I have recently installed fresh nixos and guake installed almost correctly.
It had stilled complained about missing schema, but the build file explicitly mentions this:

> After starting Guake it will give the error message "Guake can not init! Gconf Error. Have you installed  guake.schemas properly?",
> which will have to be resolved manually, because I have not found a way to automate this, without  being impure.

So I believe this ticket can be closed, except maybe, we can take the risks and actually install the schemas by default (not sure what impact does this have). I wonder how nixos manages (should manage?) the gnome schemas and other impure assets.

**Comment by jtojnar** [comment]
Could you please try https://github.com/NixOS/nixpkgs/pull/38642, GConf is no longer used.
