### ISSUE TITLE
[snapper-gui] ValueError: Namespace Gtk not available

### ISSUE THREAD

**Issue by luochen1990** [NixOS/nixpkgs#196778]
### Describe the bug

snapper-gui  not works on kde-plasma: `ValueError: Namespace Gtk not available`

### Steps To Reproduce
1. `nix-shell -p snapper-gui --command snapper-gui`

### Expected behavior

The application startup normally.

### Screenshots

```
$ snapper-gui
Traceback (most recent call last):
File "/nix/store/s9v70c6srg9qw9yx35pnnll2w1fv0011-snapper-gui-2020-10-20/bin/..snapper-gui-wrapped-wrapped", line 6, in <module>
from snappergui.application import start_ui
File "/nix/store/s9v70c6srg9qw9yx35pnnll2w1fv0011-snapper-gui-2020-10-20/lib/python3.10/site-packages/snappergui/__init__.py", line 4, in <module>
gi.require_version("Gtk", "3.0")
File "/nix/store/g8c79yyi962wgsg9vnfkbvf5b1y25fyk-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

### Additional context

```
    "nixpkgs": {
      "locked": {
        "lastModified": 1665580254,
        "narHash": "sha256-hO61XPkp1Hphl4HGNzj1VvDH5URt7LI6LaY/385Eul4=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "f634d427b0224a5f531ea5aa10c3960ba6ec5f0f",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },

```

### Notify maintainers

@alesya-h 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

- system: `"x86_64-linux"`
- host os: `Linux 5.19.12-zen1, NixOS, 22.11 (Raccoon), 22.11.20221012.f634d42`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.11.0`
- nixpkgs: `/nix/store/4lbmf3pbrsb0a5l4713mal64w8hp6na9-source`
```

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/196787
