### ISSUE TITLE
nixpkgs-review inspect source attribute and fail if source is missing

### ISSUE THREAD

**Issue by Et7f3** [NixOS/nixpkgs#197236]
### Describe the bug
I just wanted to review HEAD so no package should be build.

Ok when trying to debug I found I have a `NIXPKGS_ALLOW_BROKEN` variable set. I did find because when launching other variant `nix run .#nixpkgs-review -- rev HEAD` it does the same thing.

However `nix shell .#nixpkgs-review .#nixUnstable .#gitMinimal -i -c nix run .#nixpkgs-review rev HEAD` worked because -I but I had to list dependencies.

### Steps To Reproduce

```
$ git rev-parse HEAD
73d70fc8924787b702b18356c7d26aea8a6179d6 (should be head 2 minutes ago)
$ nix shell .#nixpkgs-review -c nix run .#nixpkgs-review rev HEAD
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
remote: Enumerating objects: 100, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 46 (delta 36), reused 18 (delta 12), pack-reused 0
Dépaquetage des objets: 100% (46/46), 5.56 Kio | 113.00 Kio/s, fait.
Depuis https://github.com/NixOS/nixpkgs
   a2d5dc2c465..6302d3cf80f  master     -> refs/nixpkgs-review/0
$ git worktree add /Users/Et7f3/.cache/nixpkgs-review/rev-73d70fc8924787b702b18356c7d26aea8a6179d6/nixpkgs 6302d3cf80f48ab97b8f5b6f91abb846e763f9f6
Préparation de l'arbre de travail (HEAD détachée 6302d3cf80f)
Mise à jour des fichiers: 100% (32419/32419), fait.
HEAD est maintenant à 6302d3cf80f Merge pull request #197128 from r-ryantm/auto-update/minio-client
$ nix-env --option system x86_64-darwin -f /Users/Et7f3/.cache/nixpkgs-review/rev-73d70fc8924787b702b18356c7d26aea8a6179d6/nixpkgs -qaP --xml --out-path --show-trace
error: attribute 'x86_64-darwin' missing

       at /Users/Et7f3/.cache/nixpkgs-review/rev-73d70fc8924787b702b18356c7d26aea8a6179d6/nixpkgs/pkgs/applications/graphics/sane/backends/brscan4/default.nix:15:9:

           14|   version = "0.4.10-1";
           15|   src = {
             |         ^
           16|     "i686-linux" = fetchurl {

       … while evaluating the attribute 'src' of the derivation 'brscan4-0.4.10-1'

       at /Users/Et7f3/.cache/nixpkgs-review/rev-73d70fc8924787b702b18356c7d26aea8a6179d6/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:270:7:

          269|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          270|       name =
             |       ^
          271|         let

       … while querying the derivation named 'brscan4-0.4.10-1'
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/rrcx5752r9zwnvmndj5kqhvgf8pdil8i-nixpkgs-review-2.7.0/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/rrcx5752r9zwnvmndj5kqhvgf8pdil8i-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/rrcx5752r9zwnvmndj5kqhvgf8pdil8i-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/cli/__init__.py", line 294, in main
    return cast(str, args.func(args))
  File "/nix/store/rrcx5752r9zwnvmndj5kqhvgf8pdil8i-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/cli/rev.py", line 12, in rev_command
    return review_local_revision(f"rev-{commit}", args, commit)
  File "/nix/store/rrcx5752r9zwnvmndj5kqhvgf8pdil8i-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 474, in review_local_revision
    review.review_commit(builddir.path, args.branch, commit, staged)
  File "/nix/store/rrcx5752r9zwnvmndj5kqhvgf8pdil8i-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 250, in review_commit
    self.start_review(self.build_commit(branch_rev, reviewed_commit, staged), path)
  File "/nix/store/rrcx5752r9zwnvmndj5kqhvgf8pdil8i-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 145, in build_commit
    base_packages = list_packages(str(self.worktree_dir()), self.system)
  File "/nix/store/rrcx5752r9zwnvmndj5kqhvgf8pdil8i-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 317, in list_packages
    subprocess.run(cmd, stdout=tmp, check=True)
  File "/nix/store/q6x5bz1k6xiylk7hiv58dw9akai2ixpz-python3-3.10.7/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-env', '--option', 'system', 'x86_64-darwin', '-f', '/Users/Et7f3/.cache/nixpkgs-review/rev-73d70fc8924787b702b18356c7d26aea8a6179d6/nixpkgs', '-qaP', '--xml', '--out-path', '--show-trace']' returned non-zero exit status 1.
```

### Expected behavior
I am on master so the package did not change

### Notify maintainers

@Mic92 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixpkgs-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by Artturin** [comment]
Report in the nixpkgs-review repo instead of here
