### ISSUE TITLE
ansible-lint fails to invoke ansible-config dump

### ISSUE THREAD

**Issue by lstrojny** [NixOS/nixpkgs#197213]
### Setup
`cat flake.nix`
```nix
{
  description = "Ansible environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system};
      in { devShell = pkgs.mkShell { buildInputs = [ pkgs.ansible pkgs.ansible-lint ]; }; });
}
```

### What happens
Executing `ansible-lint` shows this error:

```
Traceback (most recent call last):
  File "/nix/store/phcgygmn0grvp3mzivyfc8ngnfjgvr0d-python3.10-ansible-core-2.13.5/bin/.ansible-config-wrapped", line 6, in <module>
    from ansible.cli.config import main
ImportError: cannot import name 'main' from 'ansible.cli.config' (/nix/store/jycwh6vb03x2ak1dn5x39dzfvz92shz6-python3.10-ansible-core-2.12.6/lib/python3.10/site-packages/ansible/cli/config.py)
Traceback (most recent call last):
  File "/nix/store/091gq2myvrjlyg0ypvlfdyblyf3wdh7l-python3.10-ansible-lint-6.8.2/bin/.ansible-lint-wrapped", line 9, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/nix/store/091gq2myvrjlyg0ypvlfdyblyf3wdh7l-python3.10-ansible-lint-6.8.2/lib/python3.10/site-packages/ansiblelint/__main__.py", line 314, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/nix/store/091gq2myvrjlyg0ypvlfdyblyf3wdh7l-python3.10-ansible-lint-6.8.2/lib/python3.10/site-packages/ansiblelint/__main__.py", line 194, in main
    app = get_app(offline=options.offline)
  File "/nix/store/091gq2myvrjlyg0ypvlfdyblyf3wdh7l-python3.10-ansible-lint-6.8.2/lib/python3.10/site-packages/ansiblelint/app.py", line 325, in get_app
    app = App(options=default_options)
  File "/nix/store/091gq2myvrjlyg0ypvlfdyblyf3wdh7l-python3.10-ansible-lint-6.8.2/lib/python3.10/site-packages/ansiblelint/app.py", line 47, in __init__
    self.runtime = Runtime(isolated=True)
  File "/nix/store/2djmd1s3vl1pr53sv6p3avff2dd3g6pp-python3.10-ansible-compat-2.2.1/lib/python3.10/site-packages/ansible_compat/runtime.py", line 96, in __init__
    self.config = AnsibleConfig()
  File "/nix/store/2djmd1s3vl1pr53sv6p3avff2dd3g6pp-python3.10-ansible-compat-2.2.1/lib/python3.10/site-packages/ansible_compat/config.py", line 425, in __init__
    config_dump = subprocess.check_output(
  File "/nix/store/pg1za7jn6cl9nlkvg51hclwxyiswiq34-python3-3.10.7/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/pg1za7jn6cl9nlkvg51hclwxyiswiq34-python3-3.10.7/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ansible-config', 'dump']' returned non-zero exit status 
```

### Steps To Reproduce
1. Run `flake develop`
2. Run `ansible-lint`

### Expected behavior
`ansible-lint` should run

**Comment by sengaya** [comment]
@lstrojny could you test this one again with latest nixos?

**Comment by lstrojny** [comment]
Works now, thank you!
