### ISSUE TITLE
bundlerEnv doesn't work with local "unbuilt" gems ("path" source)

### ISSUE THREAD

**Issue by telent** [NixOS/nixpkgs#197556]
### Describe the bug

Running `nix-shell` on a derivation that references a gemset.nix created from a Gemfile with a ["path" gem](https://bundler.io/man/gemfile.5.html#PATH) fails with an error message 

```
/nix/store/npp6x63wjgnh2yarmva01i678x7l7nzz-bundler-2.3.9/lib/ruby/gems/3.0.0/gems/bundler-2.3.9/lib/bundler/source/path.rb:209:in `load_spec_files': The path `/nix/store/mn46x6k95dwib0w1nkvf4al1lkwr21qn-gemfile-and-lockfile/gems/foo` does not exist. (Bundler::PathError)
```

### Steps To Reproduce

Given a Gemfile containing the line

```
gem 'foo', path: 'gems/foo'
```

when I run `bundix` this generates something like the following stanza in the gemset.nix

```
  foo = {
    dependencies = [];
    groups = ["default"];
    platforms = [];
    source = {
      path = gems/foo;
      type = "path";
    };
  };
```

and when I run `nix-shell` on a derivation that references this gemset.nix:

1. it doesn't install this gem anywhere - which is fine, because it's right here in my working directory

2. but: all of the created "wrapped" commands in the gemset - "rake" or "rails" or "bundle" etc - fail with

```
/nix/store/npp6x63wjgnh2yarmva01i678x7l7nzz-bundler-2.3.9/lib/ruby/gems/3.0.0/gems/bundler-2.3.9/lib/bundler/source/path.rb:209:in `load_spec_files': The path `/nix/store/mn46x6k95dwib0w1nkvf4al1lkwr21qn-gemfile-and-lockfile/gems/foo` does not exist. (Bundler::PathError)
```

As far as I can tell, this is because the wrapping copied my Gemfile{.lock} to a location in the store and set `$BUNDLE_GEMFILE` to that location. Ruby then decides to resolve the pathname in the Gemfile  'gems/foo' relative to that store location instead of the current directory.

### Expected behavior

For interactive nix-shell use I think the behaviour I would like is to resolve the pathname relative to the working directory (or more precisely, to the directory that the Gemfile was copied from)

* if there were some way to generate wrappers that don't set `$BUNDLE_GEMFILE`, that would actually work fine for this use case.  I don't know what the purpose of copying `Gemfile*` to the store is, but I assume it's needed for actual packaging when running nix-build instead of nix-shell.

* alternatively maybe the copied Gemfile could be rewritten to do something like

```
gem 'foo', path: "#{ENV['PWD']}/gems/foo"
```

but TBH that seems like it would make things more brittle.

As a general observation, the Bundler docs say

> gemfile (BUNDLE_GEMFILE): The name of the file that bundler should use as the Gemfile. *This location of this file also sets the root of the project, which is used to resolve relative paths in the Gemfile, among other things*. By default, bundler will search up from the current working directory until it finds a Gemfile.

(emphasis mine) which makes me think that setting it to someplace else is probably going "against the grain" of how the bundler authors expect things to work. But :shrug: it's ruby

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by telent** [comment]
Guessing tags based on history, apologies if I've summoned anyone who doesn't do this any more

@alyssais @nyarly @manveru @lheckemann

**Comment by telent** [comment]
It looks like it would be not impossible to remove BUNDLE_GEMFILE from the wrapper, but at the expense of making installPhase in derivations a bit more drawn out. For example

```
diff --git a/pkgs/tools/networking/maphosts/default.nix b/pkgs/tools/networking/maphosts/default.nix
index 6632485b709..acf9cf779d8 100644
--- a/pkgs/tools/networking/maphosts/default.nix
+++ b/pkgs/tools/networking/maphosts/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, lib, bundlerEnv, ruby, bundlerUpdateScript }:
+{ stdenv, lib, bundlerEnv, makeWrapper, ruby, bundlerUpdateScript }:
 
 let
   env = bundlerEnv {
@@ -10,11 +10,14 @@ in stdenv.mkDerivation {
   pname = "maphosts";
   version = env.gems.maphosts.version;
 
+  nativeBuildInputs = [ makeWrapper ];
+
   dontUnpack = true;
 
   installPhase = ''
     mkdir -p "$out/bin"
-    ln -s "${env}/bin/maphosts" "$out/bin/maphosts"
+    makeWrapper "${env}/bin/maphosts" "$out/bin/maphosts" \
+      --set BUNDLE_GEMFILE ${env.confFiles}/Gemfile
   '';
 
   passthru.updateScript = bundlerUpdateScript "maphosts";

``` 

Has to be said that wrapping a wrapper doesn't feel _good_, but in the grand scheme of things it's probably not a really big deal

Another approach might be to change the wrapper to be something like

```
ENV["BUNDLE_GEMFILE"] = #{gemfile.dump} unless ENV.key?('IN_NIX_SHELL')
```

though again I'm dubious about this, because it introduces differences between nix-shell and regular derivations

**Comment by sagittaros** [comment]
I have made a flake that is based on builderEnv [here](https://github.com/sagittaros/ruby-nix), mostly for my own learning

**Comment by zarelit** [comment]
Related: https://github.com/nix-community/bundix/issues/84

**Comment by zarelit** [comment]
@sagittaros I will look into it, is ruby-nix specific to ruby development or could it also work for packaging? (assuming that the path of the gem is inside the application source)

**Comment by sagittaros** [comment]
[ruby-nix](https://github.com/sagittaros/ruby-nix) is simply a modified `bundlerEnv`, exposed as flake. It is designed for ruby development.

@zarelit  can you clarify what you meant by packaging? Are you writing a public gem?
