### ISSUE TITLE
Portmod does not build mods for Fallout: New Vegas.

### ISSUE THREAD

**Issue by Birdthatcantfly** [NixOS/nixpkgs#197624]
### Describe the bug
Portmod does not build mods for Fallout NV. It works correctly with OpenMW. 

### Steps To Reproduce
1. Try to install mod for Fallout NV.
2. Installation fails with this error:
`>>> Executing pkg_pretend for package assets-meshes/remastered-bodies-1.2
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmodlib/_wrapper.py", line 203, in main
    args.func(args)
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmodlib/_wrapper.py", line 67, in wrapper_pybuild
    pkg_func(pkg, "pkg_pretend")
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmodlib/_wrapper.py", line 55, in pkg_func
    return func()
  File "/tmp/portmod/tmpdb/common/bsa/bsa-0.4-r1.pybuild", line 25, in pkg_pretend
    if not shutil.which("bsatool2") and "linux" not in self.USE:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmod/_cli/main.py", line 468, in main
    args.func(args)
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmod/_cli/search.py", line 35, in search_main
    configure(selection)
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmod/merge.py", line 369, in configure
    _sandbox_execute_pybuild(
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmod/loader.py", line 363, in _sandbox_execute_pybuild
    result = _sandbox_execute(
  File "/nix/store/7hwrbm35l6n6s6j1s2m839xd4wigbi54-portmod-2.1.0/lib/python3.10/site-packages/portmod/loader.py", line 302, in _sandbox_execute
    raise SandboxedError(
portmod.loader.SandboxedError: /home/user/.local/share/portmod/repos/fallout-nv/assets-meshes/remastered-bodies/remastered-bodies-1.2.pybuild pretend failed!
ERROR: /home/user/.local/share/portmod/repos/fallout-nv/assets-meshes/remastered-bodies/remastered-bodies-1.2.pybuild pretend failed!`

### Notify maintainers
@marius851000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.70-xanmod1, NixOS, 22.11 (Raccoon), 22.11pre419369.301aada7a64`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager-22.05.tar.gz, nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by marius851000** [comment]
Turns out it need a forked version of bsatool (from OpenMW) at https://gitlab.com/bmwinger/bsatool2/-/tree/main. I’ll add it while also updating portmod.

**Comment by marius851000** [comment]
Turns out that a precompiled bsatool2 is fetched from portmod, and that it isn’t required. I’m a bit hesitant on keeping or removing it (knowing it could be usefull for some toying around in Skyrim. already had issue decompiled modern bsa in the past).

The other issues with fallout are all issues with the metadata repo. I’ll make a PR upstream of my change, but it won’t require change in NixPkgs, as it fetch it at runtime.

**Comment by marius851000** [comment]
Fix 1 is here: https://gitlab.com/portmod/fallout-nv/-/merge_requests/57
Fix 2 is here: https://gitlab.com/portmod/bsa/-/merge_requests/8
It might require portmod 2.4.2

**Comment by zimward** [comment]
Is this still relevant? If so #353046 should definitely contain the patches mentioned above.
