### ISSUE TITLE
bash: SIGILL in sh_chkwrite

### ISSUE THREAD

**Issue by collares** [NixOS/nixpkgs#199164]
### Describe the bug

After updating Nixpkgs to 412b9917cea092f3d39f9cd5dead4effd5bc4053 (Linux 6.0.5), tty logins started failing for me on an AMD Ryzen 7 4700U. Graphical login works, but interactive use of terminal emulators doesn't (tested with xterm, kitty and Konsole). Luckily I use emacs, so I can still use eshell. This is an eshell session log:

```
~ $ bash
illegal instruction (core dumped)
~ $ gdb bash
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bash...
(No debugging symbols found in bash)
(gdb) r
Starting program: /nix/store/bqq1fdk7j80gn8c2xvnrwpfpkw8ba7fb-system-path/bin/bash 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/g8d5bnh9mh1364x17mjyc731fsi9a61m-glibc-2.35-163/lib/libthread_db.so.1".
[Detaching after fork from child process 5422]

Program received signal SIGILL, Illegal instruction.
0x000000000048d002 in sh_chkwrite ()
(gdb) bt
#0  0x000000000048d002 in sh_chkwrite ()
#1  0x0000000000000000 in ?? ()
```

### Additional context
f994293d1eb8812f032e8919e10a594567cf6ef7 (Linux 6.0.3) didn't have this bug. I don't have time to bisect this today, but I will do it tomorrow.

### Notify maintainers
@dtzWill

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

nix-shell uses bash and therefore crashes, but running nix-info directly returns:

```console
[user@system:~]$ nix-info -m
~/nixpkgs/pkgs/shells/bash $ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.5, NixOS, 22.11 (Raccoon), 22.11.20221030.412b991`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(collares): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by collares** [comment]
I ca no longer reproduce this on 412b9917cea092f3d39f9cd5dead4effd5bc4053. Maybe some file got corrupted earlier? Either way, closing the bug. Sorry for the noise.
