### ISSUE TITLE
"No module named 'blib2to3'" running Black 22.10.0 with Python 3.9 with nixpkgs 22.05

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#199285]
### Describe the bug

```console
$ nix-shell --pure --run black
Traceback (most recent call last):
  File "/nix/store/19w1d4gx5fb0mr9lx10pslnnrrwxzaki-python3.9-black-22.10.0/bin/.black-wrapped", line 6, in <module>
    from black import patched_main
  File "/nix/store/639k9wgp2ch5akap7xyylcifnq1ip4a4-python3-3.9.13-env/lib/python3.9/site-packages/black/__init__.py", line 37, in <module>
    from black.comments import normalize_fmt_off
  File "/nix/store/639k9wgp2ch5akap7xyylcifnq1ip4a4-python3-3.9.13-env/lib/python3.9/site-packages/black/comments.py", line 12, in <module>
    from black.nodes import (
  File "/nix/store/639k9wgp2ch5akap7xyylcifnq1ip4a4-python3-3.9.13-env/lib/python3.9/site-packages/black/nodes.py", line 21, in <module>
    from blib2to3 import pygram
ModuleNotFoundError: No module named 'blib2to3'
```

See for example [this PR](https://gitlab.com/engmark/mypy-exercises/-/merge_requests/257/diffs).

[blib2to3 is part of the Black repo](https://github.com/psf/black/tree/main/src/blib2to3), so maybe nixpkgs 3e3ef781eab85d41e4b6f0c2a4e7ed5d22aab04c is accidentally excluding it from the outputs?

If I change `nixpkgs.json` below to instead include [current master](https://github.com/NixOS/nixpkgs/archive/053f15b2fbf0dbad7c89a133c75970b42da8d471.tar.gz), the build succeeds. Also confirmed that this error only occurs with 22.10, [not with the previous release, 22.8](https://gitlab.com/engmark/mypy-exercises/-/merge_requests/281).

### Steps To Reproduce
1. Set up the environment:
   - `shell.nix`
   ```
   { pkgs ? import
       (
         fetchTarball (
           builtins.fromJSON (
             builtins.readFile ./nixpkgs.json)))
       { }
   }:
   let
   
     poetryEnv = pkgs.poetry2nix.mkPoetryEnv {
       python = pkgs.python39;
       projectDir = ./.;
       overrides = pkgs.poetry2nix.overrides.withDefaults (self: super: {
         black = super.black.overridePythonAttrs (
           old: {
             nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ [
               self.hatch-fancy-pypi-readme
               self.hatchling
               self.hatch-vcs
             ];
           }
         );
       });
     };
   in
   poetryEnv.env
   ```
   
   - `pyproject.toml`
   ```
   [tool.poetry]
   name = "tmp.wlvznrf39j"
   version = "0.1.0"
   description = ""
   authors = ["Victor Engmark <vengmark@linz.govt.nz>"]
   
   [tool.poetry.dependencies]
   python = "^3.9"
   black = "^22.10.0"
   
   [tool.poetry.dev-dependencies]
   
   [build-system]
   requires = ["poetry-core>=1.0.0"]
   build-backend = "poetry.core.masonry.api"
   ```
   
   - `poetry.lock`
   ```
   [[package]]
   name = "black"
   version = "22.10.0"
   description = "The uncompromising code formatter."
   category = "main"
   optional = false
   python-versions = ">=3.7"
   
   [package.dependencies]
   click = ">=8.0.0"
   mypy-extensions = ">=0.4.3"
   pathspec = ">=0.9.0"
   platformdirs = ">=2"
   tomli = {version = ">=1.1.0", markers = "python_full_version < \"3.11.0a7\""}
   typing-extensions = {version = ">=3.10.0.0", markers = "python_version < \"3.10\""}
   
   [package.extras]
   colorama = ["colorama (>=0.4.3)"]
   d = ["aiohttp (>=3.7.4)"]
   jupyter = ["ipython (>=7.8.0)", "tokenize-rt (>=3.2.0)"]
   uvloop = ["uvloop (>=0.15.2)"]
   
   [[package]]
   name = "click"
   version = "8.1.3"
   description = "Composable command line interface toolkit"
   category = "main"
   optional = false
   python-versions = ">=3.7"
   
   [package.dependencies]
   colorama = {version = "*", markers = "platform_system == \"Windows\""}
   
   [[package]]
   name = "colorama"
   version = "0.4.5"
   description = "Cross-platform colored terminal text."
   category = "main"
   optional = false
   python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"
   
   [[package]]
   name = "mypy-extensions"
   version = "0.4.3"
   description = "Experimental type system extensions for programs checked with the mypy typechecker."
   category = "main"
   optional = false
   python-versions = "*"
   
   [[package]]
   name = "pathspec"
   version = "0.10.1"
   description = "Utility library for gitignore style pattern matching of file paths."
   category = "main"
   optional = false
   python-versions = ">=3.7"
   
   [[package]]
   name = "platformdirs"
   version = "2.5.2"
   description = "A small Python module for determining appropriate platform-specific dirs, e.g. a \"user data dir\"."
   category = "main"
   optional = false
   python-versions = ">=3.7"
   
   [package.extras]
   docs = ["furo (>=2021.7.5b38)", "proselint (>=0.10.2)", "sphinx-autodoc-typehints (>=1.12)", "sphinx (>=4)"]
   test = ["appdirs (==1.4.4)", "pytest-cov (>=2.7)", "pytest-mock (>=3.6)", "pytest (>=6)"]
   
   [[package]]
   name = "tomli"
   version = "2.0.1"
   description = "A lil' TOML parser"
   category = "main"
   optional = false
   python-versions = ">=3.7"
   
   [[package]]
   name = "typing-extensions"
   version = "4.4.0"
   description = "Backported and Experimental Type Hints for Python 3.7+"
   category = "main"
   optional = false
   python-versions = ">=3.7"
   
   [metadata]
   lock-version = "1.1"
   python-versions = "^3.9"
   content-hash = "b1883ca21e575dd901ea5bc6cf89e661db77450b3bbff3b1c83dffc2c1d0e32e"
   
   [metadata.files]
   black = [
       {file = "black-22.10.0-1fixedarch-cp310-cp310-macosx_11_0_x86_64.whl", hash = "sha256:5cc42ca67989e9c3cf859e84c2bf014f6633db63d1cbdf8fdb666dcd9e77e3fa"},
       {file = "black-22.10.0-1fixedarch-cp311-cp311-macosx_11_0_x86_64.whl", hash = "sha256:5d8f74030e67087b219b032aa33a919fae8806d49c867846bfacde57f43972ef"},
       {file = "black-22.10.0-1fixedarch-cp37-cp37m-macosx_10_16_x86_64.whl", hash = "sha256:197df8509263b0b8614e1df1756b1dd41be6738eed2ba9e9769f3880c2b9d7b6"},
       {file = "black-22.10.0-1fixedarch-cp38-cp38-macosx_10_16_x86_64.whl", hash = "sha256:2644b5d63633702bc2c5f3754b1b475378fbbfb481f62319388235d0cd104c2d"},
       {file = "black-22.10.0-1fixedarch-cp39-cp39-macosx_11_0_x86_64.whl", hash = "sha256:e41a86c6c650bcecc6633ee3180d80a025db041a8e2398dcc059b3afa8382cd4"},
       {file = "black-22.10.0-cp310-cp310-macosx_11_0_arm64.whl", hash = "sha256:2039230db3c6c639bd84efe3292ec7b06e9214a2992cd9beb293d639c6402edb"},
       {file = "black-22.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:14ff67aec0a47c424bc99b71005202045dc09270da44a27848d534600ac64fc7"},
       {file = "black-22.10.0-cp310-cp310-win_amd64.whl", hash = "sha256:819dc789f4498ecc91438a7de64427c73b45035e2e3680c92e18795a839ebb66"},
       {file = "black-22.10.0-cp311-cp311-macosx_11_0_arm64.whl", hash = "sha256:5b9b29da4f564ba8787c119f37d174f2b69cdfdf9015b7d8c5c16121ddc054ae"},
       {file = "black-22.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:b8b49776299fece66bffaafe357d929ca9451450f5466e997a7285ab0fe28e3b"},
       {file = "black-22.10.0-cp311-cp311-win_amd64.whl", hash = "sha256:21199526696b8f09c3997e2b4db8d0b108d801a348414264d2eb8eb2532e540d"},
       {file = "black-22.10.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:1e464456d24e23d11fced2bc8c47ef66d471f845c7b7a42f3bd77bf3d1789650"},
       {file = "black-22.10.0-cp37-cp37m-win_amd64.whl", hash = "sha256:9311e99228ae10023300ecac05be5a296f60d2fd10fff31cf5c1fa4ca4b1988d"},
       {file = "black-22.10.0-cp38-cp38-macosx_11_0_arm64.whl", hash = "sha256:fba8a281e570adafb79f7755ac8721b6cf1bbf691186a287e990c7929c7692ff"},
       {file = "black-22.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:915ace4ff03fdfff953962fa672d44be269deb2eaf88499a0f8805221bc68c87"},
       {file = "black-22.10.0-cp38-cp38-win_amd64.whl", hash = "sha256:444ebfb4e441254e87bad00c661fe32df9969b2bf224373a448d8aca2132b395"},
       {file = "black-22.10.0-cp39-cp39-macosx_11_0_arm64.whl", hash = "sha256:974308c58d057a651d182208a484ce80a26dac0caef2895836a92dd6ebd725e0"},
       {file = "black-22.10.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:72ef3925f30e12a184889aac03d77d031056860ccae8a1e519f6cbb742736383"},
       {file = "black-22.10.0-cp39-cp39-win_amd64.whl", hash = "sha256:432247333090c8c5366e69627ccb363bc58514ae3e63f7fc75c54b1ea80fa7de"},
       {file = "black-22.10.0-py3-none-any.whl", hash = "sha256:c957b2b4ea88587b46cf49d1dc17681c1e672864fd7af32fc1e9664d572b3458"},
       {file = "black-22.10.0.tar.gz", hash = "sha256:f513588da599943e0cde4e32cc9879e825d58720d6557062d1098c5ad80080e1"},
   ]
   click = [
       {file = "click-8.1.3-py3-none-any.whl", hash = "sha256:bb4d8133cb15a609f44e8213d9b391b0809795062913b383c62be0ee95b1db48"},
       {file = "click-8.1.3.tar.gz", hash = "sha256:7682dc8afb30297001674575ea00d1814d808d6a36af415a82bd481d37ba7b8e"},
   ]
   colorama = [
       {file = "colorama-0.4.5-py2.py3-none-any.whl", hash = "sha256:854bf444933e37f5824ae7bfc1e98d5bce2ebe4160d46b5edf346a89358e99da"},
       {file = "colorama-0.4.5.tar.gz", hash = "sha256:e6c6b4334fc50988a639d9b98aa429a0b57da6e17b9a44f0451f930b6967b7a4"},
   ]
   mypy-extensions = [
       {file = "mypy_extensions-0.4.3-py2.py3-none-any.whl", hash = "sha256:090fedd75945a69ae91ce1303b5824f428daf5a028d2f6ab8a299250a846f15d"},
       {file = "mypy_extensions-0.4.3.tar.gz", hash = "sha256:2d82818f5bb3e369420cb3c4060a7970edba416647068eb4c5343488a6c604a8"},
   ]
   pathspec = [
       {file = "pathspec-0.10.1-py3-none-any.whl", hash = "sha256:46846318467efc4556ccfd27816e004270a9eeeeb4d062ce5e6fc7a87c573f93"},
       {file = "pathspec-0.10.1.tar.gz", hash = "sha256:7ace6161b621d31e7902eb6b5ae148d12cfd23f4a249b9ffb6b9fee12084323d"},
   ]
   platformdirs = [
       {file = "platformdirs-2.5.2-py3-none-any.whl", hash = "sha256:027d8e83a2d7de06bbac4e5ef7e023c02b863d7ea5d079477e722bb41ab25788"},
       {file = "platformdirs-2.5.2.tar.gz", hash = "sha256:58c8abb07dcb441e6ee4b11d8df0ac856038f944ab98b7be6b27b2a3c7feef19"},
   ]
   tomli = [
       {file = "tomli-2.0.1-py3-none-any.whl", hash = "sha256:939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc"},
       {file = "tomli-2.0.1.tar.gz", hash = "sha256:de526c12914f0c550d15924c62d72abc48d6fe7364aa87328337a31007fe8a4f"},
   ]
   typing-extensions = [
       {file = "typing_extensions-4.4.0-py3-none-any.whl", hash = "sha256:16fa4864408f655d35ec496218b85f79b3437c829e93320c7c9215ccfd92489e"},
       {file = "typing_extensions-4.4.0.tar.gz", hash = "sha256:1511434bb92bf8dd198c12b1cc812e800d4181cfcb867674e0f8279cc93087aa"},
   ]
   ```
   
   - `nixpkgs.json`
   ```
   {
     "name": "release-22.05-2022-10-14T15-12-55Z",
     "url": "https://github.com/NixOS/nixpkgs/archive/3e3ef781eab85d41e4b6f0c2a4e7ed5d22aab04c.tar.gz",
     "sha256": "19h67w81mknj6izcah2hicgjnh318b83hvgpap5kwzx8hzx01hhg"
   }
   ```
2. Run `nix-shell --pure --run black`
3. Observe traceback saying "ModuleNotFoundError: No module named 'blib2to3'"

### Expected behavior
Black should run as normal.

### Additional context

Copied from [poetry2nix issue](https://github.com/nix-community/poetry2nix/issues/775).

### Notify maintainers
@sveitser @autophagy

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.75, NixOS, 22.05 (Quokka), 22.05.3935.b3a8f7ed267`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - channels(victor): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by SuperSandro2000** [comment]
Importing blib2to3 works in nixpkgs master and is installed correct. This is probably an issue in poetry2nix or more likely your nix code, so closing this.
