### ISSUE TITLE
rare fails at runtime

### ISSUE THREAD

**Issue by rapenne-s** [NixOS/nixpkgs#199544]
### Describe the bug

on nixpkgs-unstable, rare fails to start

### Steps To Reproduce

1. `nix-shell -p rare`
2. `rare`

### Expected behavior

should display a GUI

### Additional context

```
$ rare
Traceback (most recent call last):
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/bin/.rare-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/lib/python3.10/site-packages/rare/__main__.py", line 104, in main
    from rare.app import start
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/lib/python3.10/site-packages/rare/app.py", line 15, in <module>
    from rare.components.dialogs.launch_dialog import LaunchDialog
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/lib/python3.10/site-packages/rare/components/dialogs/launch_dialog.py", line 10, in <module>
    from rare.components.dialogs.login import LoginDialog
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/lib/python3.10/site-packages/rare/components/dialogs/login/__init__.py", line 13, in <module>
    from .import_login import ImportLogin
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/lib/python3.10/site-packages/rare/components/dialogs/login/import_login.py", line 8, in <module>
    from legendary.utils.wine_helpers import read_registry, get_shell_folders
ModuleNotFoundError: No module named 'legendary.utils.wine_helpers'
```

### Notify maintainers

@WolfangAukang 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.6, NixOS, 22.11 (Raccoon), 22.11.20221103.a2a7775`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/store/brqf6qdrsq5s3k0siv47wbgrgz1i9dxz-source`
```

**Comment by rapenne-s** [comment]
a bisect led to this faulty commit:

```
e82d8ad758a651ead3495e37e1ced2c4389f46c6 is the first bad commit
commit e82d8ad758a651ead3495e37e1ced2c4389f46c6
Author: R. Ryantm <ryantm-bot@ryantm.com>
Date:   Wed Oct 26 19:56:44 2022 +0000

    legendary-gl: 0.20.29 -> 0.20.30

 pkgs/games/legendary-gl/default.nix | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

**Comment by SuperSamus** [comment]
Reported upstream: https://github.com/Dummerle/Rare/issues/257.
