### ISSUE TITLE
Can't install bitbucket-api for python35

### ISSUE THREAD

**Issue by igsha** [NixOS/nixpkgs#19988]
## Issue description

I get the error:

``` sh
running build_ext
oauth2 (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: oauth2 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: oauth2
Traceback (most recent call last):
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/tmp/nix-build-python3.5-requests-oauth2-0.1.1.drv-0/requests-oauth2-0.1.1/oauth2/__init__.py", line 1, in <module>
    from oauth2 import OAuth2
ImportError: cannot import name 'OAuth2'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
builder for ‘/nix/store/ybrhk3n3i0nh0mdk746k6k06prvllkyb-python3.5-requests-oauth2-0.1.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/6mnapbpbg3l1fd5wq4ksmj0v3vvkl7b3-python3.5-bitbucket-api-0.4.4.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/6mnapbpbg3l1fd5wq4ksmj0v3vvkl7b3-python3.5-bitbucket-api-0.4.4.drv’ failed
```

It seems that this problem is related to `python35Packages.requests_oauthlib`
### Steps to reproduce

`nix-build '<nixpkgs>' -A python35Packages.bitbucket_api`
There is no problem for `python27`
## Technical details
- System: 17.03pre94121.210b3b3 (Gorilla) and on master
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: 17.03pre94121.210b3b3

**Comment by FRidh** [comment]
it seems the tests depend on a package like https://pypi.org/project/oauth2
