### ISSUE TITLE
tweepy can't be built for python35

### ISSUE THREAD

**Issue by igsha** [NixOS/nixpkgs#19987]
## Issue description
On the last stage when calling `test` I get the next errors:
```sh
[10:37] igor@nixos-pc tweepy-3.5.0 [nix-shell] % python3 setup.py test
running test
running egg_info
writing requirements to tweepy.egg-info/requires.txt
writing tweepy.egg-info/PKG-INFO
writing dependency_links to tweepy.egg-info/dependency_links.txt
writing top-level names to tweepy.egg-info/top_level.txt
reading manifest file 'tweepy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'tweepy.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    zip_safe=True)
  File "/nix/store/1c2lsmy2g76kbs7r3y4m46qy9yd9s9xs-python3-3.5.2/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/1c2lsmy2g76kbs7r3y4m46qy9yd9s9xs-python3-3.5.2/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nix/store/1c2lsmy2g76kbs7r3y4m46qy9yd9s9xs-python3-3.5.2/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/ah75wrpyp7fvs3jqxlfrbrnydf75cww4-python3.5-bootstrapped-pip-8.1.2/lib/python3.5/site-packages/setuptools/command/test.py", line 172, in run
    self.run_tests()
  File "/nix/store/ah75wrpyp7fvs3jqxlfrbrnydf75cww4-python3.5-bootstrapped-pip-8.1.2/lib/python3.5/site-packages/setuptools/command/test.py", line 193, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/nix/store/1c2lsmy2g76kbs7r3y4m46qy9yd9s9xs-python3-3.5.2/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/nix/store/1c2lsmy2g76kbs7r3y4m46qy9yd9s9xs-python3-3.5.2/lib/python3.5/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/nix/store/1c2lsmy2g76kbs7r3y4m46qy9yd9s9xs-python3-3.5.2/lib/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/nix/store/1c2lsmy2g76kbs7r3y4m46qy9yd9s9xs-python3-3.5.2/lib/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/nix/store/1c2lsmy2g76kbs7r3y4m46qy9yd9s9xs-python3-3.5.2/lib/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/nix/store/1c2lsmy2g76kbs7r3y4m46qy9yd9s9xs-python3-3.5.2/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/nix/store/ah75wrpyp7fvs3jqxlfrbrnydf75cww4-python3.5-bootstrapped-pip-8.1.2/lib/python3.5/site-packages/setuptools/command/test.py", line 40, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/1c2lsmy2g76kbs7r3y4m46qy9yd9s9xs-python3-3.5.2/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/tt/tweepy-3.5.0/examples/oauth.py", line 29, in <module>
    print(api.me().name)
  File "/tmp/tt/tweepy-3.5.0/tweepy/api.py", line 338, in me
    return self.get_user(screen_name=self.auth.get_username())
  File "/tmp/tt/tweepy-3.5.0/tweepy/auth.py", line 134, in get_username
    user = api.verify_credentials()
  File "/tmp/tt/tweepy-3.5.0/tweepy/api.py", line 631, in verify_credentials
    )(**kargs)
  File "/tmp/tt/tweepy-3.5.0/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/tmp/tt/tweepy-3.5.0/tweepy/binder.py", line 229, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'message': 'Bad Authentication data.', 'code': 215}]
```
### Steps to reproduce
`nix-build '<nixpkgs>' -A python35Packages.tweepy`
There is no problem for the `python27`. I noticed that for `python27` tests are not performed:
```sh
[10:36] igor@nixos-pc tweepy-3.5.0 [nix-shell] % python setup.py test
running test
running egg_info
writing requirements to tweepy.egg-info/requires.txt
writing tweepy.egg-info/PKG-INFO
writing top-level names to tweepy.egg-info/top_level.txt
writing dependency_links to tweepy.egg-info/dependency_links.txt
reading manifest file 'tweepy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'tweepy.egg-info/SOURCES.txt'
running build_ext
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```
## Technical details

* System: NixOS: 17.03pre94121.210b3b3 (Gorilla) and on master
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre94121.210b3b3

**Comment by FRidh** [comment]
there are no tests in the archive, so it needs `doCheck = false;`.

**Comment by FRidh** [comment]
cc maintainer @garbas

**Comment by garbas** [comment]
:+1: disabled the tests in commit mentioned above
