### ISSUE TITLE
Can't install mezzanine for python35

### ISSUE THREAD

**Issue by igsha** [NixOS/nixpkgs#19989]
## Issue description

I get this message:

``` sh
running build_ext
Traceback (most recent call last):
  File "/tmp/nix-build-python3.5-filebrowser_safe-0.3.6.drv-0/filebrowser_safe-0.3.6/filebrowser_safe/settings.py", line 13, in <module>
    import tinymce.settings
ImportError: No module named 'tinymce'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nix_run_setup.py", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 18, in <module>
    zip_safe=False,
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 180, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/abvccgrm8ipq568xy2a3101z739n7rsa-python3-3.5.2/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/nix-build-python3.5-filebrowser_safe-0.3.6.drv-0/filebrowser_safe-0.3.6/filebrowser_safe/views.py", line 29, in <module>
    from filebrowser_safe.settings import *
  File "/tmp/nix-build-python3.5-filebrowser_safe-0.3.6.drv-0/filebrowser_safe-0.3.6/filebrowser_safe/settings.py", line 17, in <module>
    DEFAULT_URL_TINYMCE = settings.STATIC_URL + "grappelli/tinymce/jscripts/tiny_mce/"
  File "/nix/store/q8a7dl0h4k9bs81jfr3fn1yq7mynxax7-python3.5-Django-1.10.2/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/nix/store/q8a7dl0h4k9bs81jfr3fn1yq7mynxax7-python3.5-Django-1.10.2/lib/python3.5/site-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting STATIC_URL, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
builder for ‘/nix/store/zvh08g6pd78lwfw0p8h4i8f9g6ajhalz-python3.5-filebrowser_safe-0.3.6.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/hf4nzqppwy1dfkg2ng0m4pxss4wqrsbn-python3.5-mezzanine-3.1.10.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/hf4nzqppwy1dfkg2ng0m4pxss4wqrsbn-python3.5-mezzanine-3.1.10.drv’ failed
```

It seems that the original problem is related to the `filebrowser_safe` package.
### Steps to reproduce

`nix-build '<nixpkgs>' -A python35Packages.mezzanine`
There is no problem for `python27`
## Technical details
- System: NixOS: 17.03pre94121.210b3b3 (Gorilla) and on master
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: 17.03pre94121.210b3b3

**Comment by FRidh** [comment]
@lsix knows more about Django on Nix.

**Comment by FRidh** [comment]
But a first step would be to add the tinymce module

**Comment by lsix** [comment]
I’ll look into that ASAP

**Comment by lsix** [comment]
I have a PR (#20019) related to this issue.

At this point, mezzanine WILL NOT WORK with python-3.5. The mezzanine version we have is using django-1.6 which does not support python-3.5 (see .https://docs.djangoproject.com/en/1.10/releases/1.6/).

We will need to update mezzanine version in nixpkgs at some point to fix this properly.

**Comment by FRidh** [comment]
@lsix okay, thanks!

**Comment by FRidh** [comment]
can this be closed?

**Comment by igsha** [comment]
No, from current master I've received the same problem for `python35`:
```sh
running build_ext
Traceback (most recent call last):
  File "/tmp/nix-build-python3.5-filebrowser_safe-0.3.6.drv-0/filebrowser_safe-0.3.6/filebrowser_safe/settings.py", line 13, in <module>
    import tinymce.settings
ImportError: No module named 'tinymce'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nix_run_setup.py", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 18, in <module>
    zip_safe=False,
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 180, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/y23hsampcyaad80f126482zpzpw8jspv-python3-3.5.2/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/nix-build-python3.5-filebrowser_safe-0.3.6.drv-0/filebrowser_safe-0.3.6/filebrowser_safe/views.py", line 29, in <module>
    from filebrowser_safe.settings import *
  File "/tmp/nix-build-python3.5-filebrowser_safe-0.3.6.drv-0/filebrowser_safe-0.3.6/filebrowser_safe/settings.py", line 17, in <module>
    DEFAULT_URL_TINYMCE = settings.STATIC_URL + "grappelli/tinymce/jscripts/tiny_mce/"
  File "/nix/store/jxw9yiqqzmi511f8gv0mgz0i5pb04yrs-python3.5-Django-1.10.2/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/nix/store/jxw9yiqqzmi511f8gv0mgz0i5pb04yrs-python3.5-Django-1.10.2/lib/python3.5/site-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting STATIC_URL, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
builder for ‘/nix/store/3188gzsrwa73blm33fb50ak719f4611h-python3.5-filebrowser_safe-0.3.6.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/dwxm15sw7a4inxcmc77fb9acdbahi7fn-python3.5-mezzanine-3.1.10.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/dwxm15sw7a4inxcmc77fb9acdbahi7fn-python3.5-mezzanine-3.1.10.drv’ failed
```
It is a `filebrowser_safe` problem.

**Comment by igsha** [comment]
However, it works for `python33`:
```sh
[14:07] igor@nixos-pc nixpkgs (master) $ nix-shell -I nixpkgs=~/nixpkgs -p python33Packages.mezzanine
[14:07] igor@nixos-pc nixpkgs (master) [nix-shell] % python3
Python 3.3.6 (default, Oct 12 2014, 07:03:57) 
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mezzanine
>>> from mezzanine import utils
>>> 
```
