### ISSUE TITLE
systemd-boot: installation hard-fails when no bootloader was previously installed

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#201677]
### Describe the bug

I wanted to switch to systemd-boot from GRUB but, upon activating the generation, I was met with the following message:

```
systemd-boot not installed in ESP.
No default/fallback boot loader installed in ESP.
Traceback (most recent call last):
  File "/nix/store/vi82fnapgkq97w3kbl7lwb4g6dh6pmcm-systemd-boot", line 315, in <module>
    main()
  File "/nix/store/vi82fnapgkq97w3kbl7lwb4g6dh6pmcm-systemd-boot", line 256, in main
    raise Exception("could not find any previously installed systemd-boot")
Exception: could not find any previously installed systemd-boot
warning: error(s) occurred while switching to the new configuration
```

This can be reproduced by removing the state from `/boot` and re-activating your generation.

The cause is here:
https://github.com/NixOS/nixpkgs/blob/ee4d3df08b1c79e7608064741a6e07ebc1b6f197/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L221-L257

It makes the script raise an exception and fail if `NIXOS_INSTALL_BOOTLOADER` isn't `1` and no bootloader was installed previously.

`nixos-rebuild` apparently has a `--install-bootloader` flag that I never even knew existed. It is documented in the man page but nowhere else AFAICT.

This is a terrible UX. 

### Expected behavior

For one, the script should fail gracefully rather than in a backtrace and give the user an obvious message which at least points them to the magic environment variable required to have the script try to install the bootloader.

IMO though, the bootloader should always either be clean-installed unless explicitly told not to.

Why are we bothering with `bootctl update` and all the complexity it entails?  
I don't need any special version handling; if you i.e. roll back to a previous generation because the new one broke your bootloader for some reason, you wouldn't want the new bootloader to remain installed, you'd want the old one to be installed in again. This breaks the principle of least surprise and requires unnecessary complexity in the script.

### Additional context

GRUB always gets re-installed every time by default AFAIK and that's been working great for me.

### Notify maintainers

@Mic92 @jian-lin @winterqt @waldheinz 

### Metadata

NixOS/nixpkgs@667e5581d16745bcda791300ae7e2d73f49fff25

**Comment by waldheinz** [comment]
When I modified the code in question I focused on keeping the original functionality while fixing only the bug at hand. So I really can't tell what's the reason for doing the `NIXOS_INSTALL_BOOTLOADER` dance, maybe someone was surprised that his bootloader was replaced when he just wanted to change his NixOS installation? I think which is the outcome of "least surprise" is not entirely clear in this case. 

I fully agree that there is room for improvement with the UX / error message in this case, though. Also, I think switching the bootloader is a rare enough endeavor for 99.9% of the users that the minor inconvenience of having that env variable set (or passing the `--install-bootloader` argument) seems acceptable.

**Comment by willcohen** [comment]
I'm hitting this trying to bring up a NixOS install using QEMU/UTM -- loosely following the process from the Makefile in https://github.com/mitchellh/nixos-config, which generally follows the manual with some automation as well.

I'm able to successfully run `nixos-install`, but can't `nixos-rebuild` without hitting this. If I try to add `NIXOS_INSTALL_BOOTLOADER=1` to the install phase, I then still have issues with my first run of `nixos-rebuild switch`, since `/boot` only exists in `/mnt/boot`, and mounting the boot partition twice doesn't seem to work correctly (and feels a little hacky besides). I haven't tried running an older install image to make this work, but it does seem like it'd be good to allow for UEFI virtualized instead of falling back to grub, which I assume is the only current path forward for this virtualization use case.

**Comment by winterqt** [comment]
@willcohen I've never run into this for a clean install of systemd-boot in UTM, FWIW, if that's what you mean.

Can you provide (loose/quick even) reproduction steps?

**Comment by willcohen** [comment]
The fact that it works for you leads me to believe it's then 100% a me problem. I had an old creakily-built QEMU thing working a while back but I had to go with grub because I could never get UEFI working.

I'll work on a repro or try to figure what I'm omitting from my config. @winterqt are there places where you have to deviate heavily from https://nixos.org/manual/nixos/stable/index.html#sec-installation to get UTM working with systemd-boot, or does it pretty much work as is?

**Comment by Atemu** [comment]
If you use `nixos-install`, it should work just fine as that should set the magic env var.

You should only hit this bug if you're trying to switch bootloaders.

**Comment by Shados** [comment]
@waldheinz
> When I modified the code in question I focused on keeping the original functionality while fixing only the bug at hand. So I really can't tell what's the reason for doing the NIXOS_INSTALL_BOOTLOADER dance, maybe someone was surprised that his bootloader was replaced when he just wanted to change his NixOS installation? I think which is the outcome of "least surprise" is not entirely clear in this case.

In the context of Nix and NixOS it is quite surprising to me that `nixos-rebuild` _isn't_ effectively idempotent if using systemd-boot. This goes against the largely declarative nature of NixOS modules, and is particularly painful given it isn't documented in either the manual or the `boot.loader.systemd-boot` options.

**Comment by mmlb** [comment]
I just ran into this after effectively `dd if=/dev/zero /dev/sda` where sda is gpt partitioned with 2G partition, formatted vfat for /boot and the rest is btrfs. I caught it pretty quickly so don't feel too bad (and can reinstall if needed). I was able to recover by using gdisk to recover the main headers/table from the backup. Then had btrfs check and repair itself. Finally I created a new vfat on /dev/sda1 and figured `nixos-switch` would do the trick. It did not, and I did not want to reboot or otherwise run `nixos-install`. Once I found this issue adding `--install-bootloader` seems to get me back to a fully working setup.

Just wanted to add a data point that this behaviour isn't a problem just for change in bootloader. I want to echo @Shados' point re:
> In the context of Nix and NixOS it is quite surprising to me that nixos-rebuild isn't effectively idempotent if using systemd-boot.

**Comment by ThinkChaos** [comment]
I hit this and worked around it by temporarily setting `boot.loader.systemd-boot.graceful = true;`.  
That passes `--graceful` to `bootctl` which makes it exit 0/succeed.
