### ISSUE TITLE
Gephi can't initialize graph window

### ISSUE THREAD

**Issue by akamaus** [NixOS/nixpkgs#202025]
### Describe the bug
I tried several versions of gephi from nixos-20.03, nixos-21.11 and current master(1c8216d074). All have the same fatal issue: window stuck with 'initializing...' caption and no graph is displayed.

### Steps To Reproduce
1. Install gephi
2. Load example graph
3. Observe no drawing is shown.

### Additional context
I found precisely the same issue upstream. https://github.com/gephi/gephi/issues/2189
Both proposed solutions (setting either MESA_LOADER_DRIVER_OVERRIDE=i965 or LIBGL_ALWAYS_SOFTWARE=1) work for me. 

### Notify maintainers
@Radvendii

### Metadata

```console
% nix-shell -p nix-info --run "nix-info -m"                                                                                                                                                                         ~/nixpkgs 
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.102, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/opt/nixpkgs`
```

```
% glxinfo
name of display: :1
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_no_error, 
    GLX_ARB_create_context_profile, GLX_ARB_create_context_robustness, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_libglvnd, GLX_EXT_no_config_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, GLX_OML_swap_method, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control
...
```

```
% lspci | grep -i vga                                                                                                                                                                                               
00:02.0 VGA compatible controller: Intel Corporation CometLake-U GT2 [UHD Graphics] (rev 02)
```

**Comment by importantblimp** [comment]
Good news: this has been fixed on master since April, under commit ae5b53747bc06f479f1cf8164c7cadb1ee291d92.
I haven't been able to tell which commit on master/staging/staging-next originally fixed the issue though.

**Comment by Alizter** [comment]
Any fix for this? None of the fixes in the gephi issue worked for me. I get
```
/nix/store/4w42z3xzhsr0zxqy9w3mag42n73n1xwz-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so: undefined symbol: g_assertion_message_cmpint
Failed to load module: /nix/store/4w42z3xzhsr0zxqy9w3mag42n73n1xwz-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so
/nix/store/9la894yvmmksqlapd4v16wvxpaw3rg70-glibc-2.37-8/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/iv9bfnnnycgpsbsx4k9ncn6dpwrmrmmm-gvfs-1.52.2/lib/gio/modules/libgvfsdbus.so)
Failed to load module: /nix/store/iv9bfnnnycgpsbsx4k9ncn6dpwrmrmmm-gvfs-1.52.2/lib/gio/modules/libgvfsdbus.so
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.core.windows.view.ui.MainWindow (jar:file:/nix/store/8l84g5g93djycc9402vnaw8av1dmwkp0-gephi-0.10.1/platform/modules/org-netbeans-core-windows.jar!/) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of org.netbeans.core.windows.view.ui.MainWindow
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
not really sure what to make of that.

**Comment by MMesch** [comment]
@importantblimp is this still working for you? After a brief phase where I was able to use gephi it stopped working again for me now. I also struggle to find a past commit that works, which makes me wonder whether a system driver update can influence this.

**Comment by MMesch** [comment]
Gephi shows, in the bottom right corner when clicking on a red street sign, this error message:

```
com.jogamp.opengl.GLException: Profile GL2 is not available on null, but: []
```

The `export LIBGL_ALWAYS_SOFTWARE=1` doesn't have any effect but maybe I am not using it right.

**Comment by MMesch** [comment]
Workaround by @ErinvanderVeen :

> Download the latest release here: https://github.com/gephi/gephi/releases/tag/v0.10.1
> Extract it.

```
cd gephi-0.10.1-linux-x64/gephi-0.10.1/bin
NIXPKGS_ALLOW_UNFREE=1 nix run nixpkgs#steam-run --impure -- ./gephi
```

works for me and another colleague confirmed as well :+1:

**Comment by importantblimp** [comment]
@MMesch, I think you're right, it's something environmental.

The commit that was previously working for me and the current version of unstable don't work for me now, although with a slightly different warning to Alizter. I see same behaviour as akamaus on the earlier commit, and a blank graph area with the latest unstable.

Outputs:
Previously working for me (https://github.com/NixOS/nixpkgs/commit/ae5b53747bc06f479f1cf8164c7cadb1ee291d92):
```
/nix/store/ri1mxak4lk2k3l6zyb228ck354awlv2z-gephi-0.9.6
Detected KDE; adding awt.useSystemAAFontSettings=on
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/nix/store/ri1mxak4lk2k3l6zyb228ck354awlv2z-gephi-0.9.6/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release

```

Latest unstable (fb96cbf93f08):
```
/nix/store/g06l7i9kl06aw8kf042478psvi49rmvq-gephi-0.10.1
Detected KDE; adding awt.useSystemAAFontSettings=on
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.core.windows.view.ui.MainWindow (jar:file:/home/gy/src/nixpkgs/result/platform/modules/org-netbeans-core-windows.jar!/) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of org.netbeans.core.windows.view.ui.MainWindow
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by nanophilip** [comment]
Looking for solutions I came across [this comment](https://github.com/gephi/gephi/issues/2189#issuecomment-636691238):

> Do you have an "one way street sign" in the right bottom corner of your gephi window?

I also have a warning sign, the log is:
```
-------------------------------------------------------------------------------
>Log Session: Sunday, March 30, 2025 at [...]
>System Info: 
  Product Version         = Gephi 0.10.1 202503181241
  Operating System        = Linux version 6.6.84 running on amd64
  Java; VM; Vendor        = 11.0.25; OpenJDK 64-Bit Server VM 11.0.25+0-adhoc..source; Oracle Corporation
  Runtime                 = OpenJDK Runtime Environment 11.0.25+0-adhoc..source
  Java Home               = /nix/store/mycb2cm8w4qww2nxa7vlggfwrdcp7lpi-openjdk-11.0.25+9/lib/openjdk
  System Locale; Encoding = en_US (gephi); UTF-8
  Home Directory          = [...]
  Current Directory       = [...]
  User Directory          = [...]/.gephi/0.10
  Cache Directory         = [...]/.cache/gephi/0.10
  Installation            = /nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/extra
                            /nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/gephi
                            /nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform
                            /nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform
  Boot & Ext. Classpath   = 
  Application Classpath   = /nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/lib/boot.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/lib/org-openide-modules.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/lib/org-openide-util.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/lib/org-openide-util-lookup.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/lib/org-openide-util-ui.jar
  Startup Classpath       = /nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/core/core.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/core/asm-tree-9.3.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/core/core-base.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/core/asm-9.3.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/core/org-openide-filesystems.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/core/asm-commons-9.3.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/core/org-netbeans-libs-asm.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform/core/org-openide-filesystems-compat8.jar:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/gephi/core/locale/core_gephi.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.52 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.util [9.26 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.util.ui [9.26 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.modules [7.66 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.annotations.common/1 [1.46 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.filesystems [9.30 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.awt [7.86 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.progress/1 [1.66 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.progress.nb [1.66 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.dialogs [7.64 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.nodes [7.63 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.windows [6.95 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.batik.read [1.11.0.1 1 Netbeans/netbeans-TLP/netbeans/release160-11-on-20221119]
	org.openide.util.ui.svg [1.12 Netbeans/netbeans-TLP/netbeans/release160-11-on-20221119]
	org.netbeans.modules.editor.mimelookup/1 [1.58 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.text [6.86 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.scripting [1.15 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.swing.tabcontrol [1.75 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.swing.outline [1.52 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.explorer [6.80 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.actions [6.57 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.queries/1 [1.61 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.templates [1.26 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.filesystems.nb [9.28 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.loaders [7.88 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.intent [1.20 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.io [1.21 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.io [1.67 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.filesystems.compat8 [9.27 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.swing.plaf [1.60 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.keyring [1.42 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.asm [5.21 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.bootstrap/1 [2.96 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.startup.base [1.80.0.1 1 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.startup/1 [1.80.0.1 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.sampler [1.32 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core/2 [3.69 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.spi.quicksearch [1.45 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.options.api/1 [1.63 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.flatlaf/1 [1.12 2.6 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.swing.laf.flatlaf [1.11 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.swing.laf.dark/1 [2.13.0.2 2 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.templates/1 [1.25 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.settings/1 [1.67 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.sendopts/2 [2.54 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.progress.ui [1.51 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.print [7.44 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.options.keymap [1.55 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.masterfs/2 [2.73.0.2 2 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.masterfs.ui [2.21.0.2 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.masterfs.nio2 [1.33 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.jna/2 [2.13 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.masterfs.linux [1.31 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.keyring.fallback [1.26 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.keyring.impl [1.42 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.janitor [1.11 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.favorites/1 [1.64 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.autoupdate.services [1.73 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.autoupdate.cli [1.32 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.windows/2 [2.103 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.ui/1 [1.63 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.osgi [1.40 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.felix [2.33 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.autoupdate.ui [1.64 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.core.kit [1.49 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.jna.platform/2 [2.13 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.output2/1 [1.60 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.network [1.30 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.nativeaccess/1 [1.49 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.multitabs/1 [1.30.0.1 1 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.io.ui/1 [1.48 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.gephi.core.library.wrapper [0.10.1 0.10.1 202503181241]
	org.gephi.utils.longtask [0.10.1 0.10.1 202503181241]
	org.gephi.project.api [0.10.1 0.10.1 202503181241]
	org.gephi.graph.api [0.10.1 0.10.1 202503181241]
	org.gephi.utils [0.10.1 0.10.1 202503181241]
	org.gephi.ui.library.wrapper [0.10.1 0.10.1 202503181242]
	org.gephi.ui.utils [0.10.1 0.10.1 202503181242]
	org.gephi.desktop.icons [0.10.1 0.10.1 202503181242]
	org.gephi.ui.components [0.10.1 0.10.1 202503181242]
	org.gephi.db.drivers [0.10.1 0.10.1 202503181242]
	org.gephi.io.importer.api [0.10.1 0.10.1 202503181242]
	org.gephi.mostrecentfiles.api [0.10.1 0.10.1 202503181242]
	org.gephi.desktop.project [0.10.1 0.10.1 202503181242]
	org.gephi.welcome.screen [0.10.1 0.10.1 202503181242]
	org.gephi.datalab.api [0.10.1 0.10.1 202503181241]
	org.gephi.visualization.api [0.10.1 0.10.1 202503181241]
	org.gephi.tools.api [0.10.1 0.10.1 202503181242]
	org.gephi.visualization [0.10.1 0.10.1 202503181242]
	org.gephi.algorithms.plugin [0.10.1 0.10.1 202503181242]
	org.gephi.tools.plugin [0.10.1 0.10.1 202503181242]
	org.gephi.statistics.api [0.10.1 0.10.1 202503181242]
	org.gephi.statistics.plugin [0.10.1 0.10.1 202503181242]
	org.gephi.filters.api [0.10.1 0.10.1 202503181242]
	org.gephi.appearance.api [0.10.1 0.10.1 202503181242]
	org.gephi.filters.plugin [0.10.1 0.10.1 202503181242]
	org.gephi.timeline.api [0.10.1 0.10.1 202503181242]
	org.gephi.statistics.plugin.ui [0.10.1 0.10.1 202503181242]
	org.gephi.settings.upgrader [0.10.1 0.10.1 202503181242]
	org.gephi.batik.wrapper [0.10.1 0.10.1 202503181241]
	org.gephi.preview.api [0.10.1 0.10.1 202503181241]
	org.gephi.preview.plugin [0.10.1 0.10.1 202503181242]
	org.gephi.io.exporter.api [0.10.1 0.10.1 202503181241]
	org.gephi.io.exporter.preview [0.10.1 0.10.1 202503181242]
	org.gephi.preview.export.ui [0.10.1 0.10.1 202503181242]
	org.gephi.perspective.api [0.10.1 0.10.1 202503181242]
	org.gephi.layout.api [0.10.1 0.10.1 202503181243]
	org.gephi.layout.plugin [0.10.1 0.10.1 202503181243]
	org.gephi.io.importer.plugin [0.10.1 0.10.1 202503181242]
	org.gephi.io.generator.api [0.10.1 0.10.1 202503181243]
	org.gephi.io.generator.plugin [0.10.1 0.10.1 202503181243]
	org.gephi.io.exporter.plugin [0.10.1 0.10.1 202503181242]
	org.gephi.import.plugin.ui [0.10.1 0.10.1 202503181243]
	org.gephi.generator.plugin.ui [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.window [0.10.1 0.10.1 202503181242]
	org.gephi.filters.plugin.ui [0.10.1 0.10.1 202503181243]
	org.gephi.filters.impl [0.10.1 0.10.1 202503181243]
	org.gephi.export.plugin.ui [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.tools [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.timeline [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.statistics [0.10.1 0.10.1 202503181243]
	org.gephi.datalab.plugin [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.io.export [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.datalab [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.search [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.preview [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.layout [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.import [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.generate [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.filters [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.context [0.10.1 0.10.1 202503181242]
	org.gephi.desktop.branding [0.10.1 0.10.1 202503181243]
	org.gephi.appearance.plugin [0.10.1 0.10.1 202503181243]
	org.gephi.appearance.plugin.ui [0.10.1 0.10.1 202503181243]
	org.gephi.desktop.appearance [0.10.1 0.10.1 202503181243]
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: no suitable found, using fallback.
INFO [org.netbeans.core.network.proxy.fallback.FallbackNetworkProxy]: Fallback system proxy resolver: no http_proxy variable found
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
INFO: Current Version is gephi
SEVERE [global]
java.lang.UnsatisfiedLinkError: /tmp/jogamp_0000/file_cache/jln5293921551562999878/jln2382219670606333562/natives/linux-amd64/libnativewindow_awt.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2450)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2506)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2705)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2635)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1854)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:604)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at jogamp.nativewindow.NWJNILibLoader.access$000(NWJNILibLoader.java:39)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:49)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:41)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.util.SecurityUtil.doPrivileged(SecurityUtil.java:82)
	at jogamp.nativewindow.NWJNILibLoader.loadNativeWindow(NWJNILibLoader.java:41)
	at jogamp.nativewindow.jawt.JAWTUtil.<clinit>(JAWTUtil.java:351)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.jogamp.nativewindow.NativeWindowFactory$2.run(NativeWindowFactory.java:391)
	at com.jogamp.nativewindow.NativeWindowFactory$2.run(NativeWindowFactory.java:387)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.util.SecurityUtil.doPrivileged(SecurityUtil.java:82)
	at com.jogamp.nativewindow.NativeWindowFactory.initSingleton(NativeWindowFactory.java:387)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1742)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:239)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.util.SecurityUtil.doPrivileged(SecurityUtil.java:82)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:225)
	at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2334)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1009)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1025)
	at org.gephi.visualization.swing.GLAbstractListener.getCaps(GLAbstractListener.java:179)
	at org.gephi.visualization.swing.NewtGraphCanvas.initDrawable(NewtGraphCanvas.java:68)
	at org.gephi.visualization.swing.GLAbstractListener.getGraphComponent(GLAbstractListener.java:548)
	at org.gephi.visualization.component.GraphTopComponent$1.lambda$run$1(GraphTopComponent.java:131)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused: java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at org.gephi.visualization.component.GraphTopComponent$1.lambda$run$2(GraphTopComponent.java:128)
Caused: java.lang.RuntimeException
	at org.gephi.visualization.component.GraphTopComponent$1.lambda$run$2(GraphTopComponent.java:136)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[catch] at java.base/java.lang.Thread.run(Thread.java:829)
Diagnostic information
Input arguments:
	-Djdk.home=/nix/store/mycb2cm8w4qww2nxa7vlggfwrdcp7lpi-openjdk-11.0.25+9
	-Dnetbeans.dirs=/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/extra:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/gephi:/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform:
	-Dnetbeans.home=/nix/store/9j8vp2v1fmzvvpsc48i5f2wq81dbbkaw-gephi-0.10.1/platform
	-Dsun.java2d.metal=true
	-Dsun.java2d.noddraw=true
	-Dsun.awt.noerasebackground=true
	-Dapple.awt.graphics.UseQuartz=true
	-Dnetbeans.indexing.noFileRefresh=true
	-Dnetbeans.winsys.hideEmptyDocArea=true
	-Dplugin.manager.check.interval=EVERY_DAY
	-Dapple.awt.application.appearance=system
	--add-opens=java.base/java.net=ALL-UNNAMED
	--add-exports=java.desktop/sun.awt=ALL-UNNAMED
	--add-opens=java.desktop/javax.swing=ALL-UNNAMED
	--add-opens=java.base/java.nio=ALL-UNNAMED
	--add-exports=java.desktop/sun.awt=ALL-UNNAMED
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=.../.gephi/0.10/var/log/heapdump.hprof
	-Djava.security.manager=allow
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 246.0MB maximum 3924.0MB
Non heap memory usage: initial 7.3MB maximum -1b
Garbage collector: G1 Young Generation (Collections=6 Total time spent=0s)
Garbage collector: G1 Old Generation (Collections=0 Total time spent=0s)
Classes: loaded=9930 total loaded=9930 unloaded 0
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 16,456,560,640
INFO [null]: Total physical memory 16,456,560,640
WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/View/ marked with the position attribute: [org-netbeans-core-windows-actions-ToggleFullScreenAction.instance\position], but some are: [ToggleFullScreenAction.shadow]
```

**Comment by importantblimp** [comment]
I get the same error you do @nanophilip on that commit and I've found the proximate cause: we're missing `xorg.libXxf86vm`.
This can be "fixed" with a small modification to the solution suggested by Erin:
```
nix shell nixpkgs#xorg.libXxf86vm nixpkgs#gephi
nix run github:nix-community/nixGL --impure -- gephi
```

_Why_ we're missing this library isn't clear to me, however.
It's present in the `buildInputs` for `jogl`, which is the dependency that this error is thrown from. And although there are suspicious looking changes to the `jogl` and `gluegen` jars in the `gephi` install step: they don't make a difference at least for this commit - the jars are exactly the as the packaged ones.

Without using nixGL I now get the same problem as MMesch, and `LIBGL_ALWAYS_SOFTWARE=1` also doesn't work for me.

```
com.jogamp.opengl.GLException: Profile GL2 is not available on null, but: []
```

The sweethome3d package had a similar problem:
```
com.jogamp.opengl.GLException: Profiles [GL4bc, GL3bc, GL2, GLES1] not available on device null
```

They swapped out `mesa` (used by `jogl`) for `libGL` in #284982
https://discourse.nixos.org/t/force-opengl-version-on-nvidia-or-force-usage-of-mesa-opengl/37436

**Comment by offray** [comment]
> nix shell nixpkgs#xorg.libXxf86vm nixpkgs#gephi
> nix run github:nix-community/nixGL --impure -- gephi

This was the solution that worked for me finally, after testing the previous ones. 

I'm a newbie on NixOS and after decades using other GNU/Linux distros I feel like a newbie again, but it's a pretty empowering experience, despite of "glitches" and its uniqueness. And finding threads like this one makes a huge difference. I was pretty well located in the first search results and it shows the vitality of the Nix community.

Thanks,
