### ISSUE TITLE
twmnd cant find libQt5Widgets.so.5

### ISSUE THREAD

**Issue by navilan** [NixOS/nixpkgs#20387]
## Issue description
twmnd does not launch because qt5 library path is missing.

### Steps to reproduce

Install the twmn package and run twmnd.

## Technical details

twmnd works when I manually set the LD_LIBRARY_PATH to <qtbase>/lib.

* System: NixOS 16.09.931.33c388c4
* Nix version: 1.11.4
* Nixpkgs version:16.09.931.33c388c4

**Comment by jb55** [comment]
I noticed the same or similar thing when trying to run twmnd as a systemd user service. It just SIGABRTs:

I could reproduce with `nix-shell --pure -p twmn --run twmnd`

Although `nix-shell -p twmn --run twmnd` works fine... So clearly there is some impurity in my local
environment which is making twmnd work "by accident?"

Possibly related?: #15498

```
#0  0x00007ffff57ae384 in raise () from /nix/store/20msidpx6ydhif01jzaqlj31c83m4173-glibc-2.25/lib/libc.so.6
#1  0x00007ffff57af7ea in abort () from /nix/store/20msidpx6ydhif01jzaqlj31c83m4173-glibc-2.25/lib/libc.so.6
#2  0x00007ffff68dce01 in QMessageLogger::fatal(char const*, ...) const ()
   from /nix/store/0jm9d2lsd69x8q2kwr8ddh63k2khshm5-qtbase-5.9.0/lib/libQt5Core.so.5
#3  0x00007ffff6e886c9 in QGuiApplicationPrivate::createPlatformIntegration() ()
   from /nix/store/0jm9d2lsd69x8q2kwr8ddh63k2khshm5-qtbase-5.9.0/lib/libQt5Gui.so.5
#4  0x00007ffff6e888bd in QGuiApplicationPrivate::createEventDispatcher() ()
   from /nix/store/0jm9d2lsd69x8q2kwr8ddh63k2khshm5-qtbase-5.9.0/lib/libQt5Gui.so.5
#5  0x00007ffff6a95ea8 in QCoreApplicationPrivate::init() () from /nix/store/0jm9d2lsd69x8q2kwr8ddh63k2khshm5-qtbase-5.9.0/lib/libQt5Core.so.5
#6  0x00007ffff6e89b2e in QGuiApplicationPrivate::init() () from /nix/store/0jm9d2lsd69x8q2kwr8ddh63k2khshm5-qtbase-5.9.0/lib/libQt5Gui.so.5
#7  0x00007ffff7389c29 in QApplicationPrivate::init() () from /nix/store/0jm9d2lsd69x8q2kwr8ddh63k2khshm5-qtbase-5.9.0/lib/libQt5Widgets.so.5
#8  0x0000000000408ba1 in main ()
```
