### ISSUE TITLE
python3Packages.rapidfuzz: fails to build on darwin

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#204022]
### Steps To Reproduce
1. build *python3Packages.rapidfuzz*

### Build log
```
pythonImportsCheckPhase
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: rapidfuzz.fuzz rapidfuzz.string_metric rapidfuzz.process rapidfuzz.utils
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/ns32408gw33gfjvkgnrfbv2h3l0vnzd6-python3-3.10.8/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/4ssl9ka93spsdj6wir60qywqr2xwlikq-python3.10-rapidfuzz-2.13.2/lib/python3.10/site-packages/rapidfuzz/__init__.py", line 8, in <module>
    from rapidfuzz import distance, fuzz, process, string_metric, utils
  File "/nix/store/4ssl9ka93spsdj6wir60qywqr2xwlikq-python3.10-rapidfuzz-2.13.2/lib/python3.10/site-packages/rapidfuzz/distance/__init__.py", line 6, in <module>
    from . import (
  File "/nix/store/4ssl9ka93spsdj6wir60qywqr2xwlikq-python3.10-rapidfuzz-2.13.2/lib/python3.10/site-packages/rapidfuzz/distance/OSA.py", line 13, in <module>
    distance = _fallback_import(_mod, "distance", cached_scorer_call=_dist_attr)
  File "/nix/store/4ssl9ka93spsdj6wir60qywqr2xwlikq-python3.10-rapidfuzz-2.13.2/lib/python3.10/site-packages/rapidfuzz/_utils.py", line 71, in fallback_import
    cpp_mod = importlib.import_module(module + "_cpp")
  File "/nix/store/ns32408gw33gfjvkgnrfbv2h3l0vnzd6-python3-3.10.8/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nix/store/4ssl9ka93spsdj6wir60qywqr2xwlikq-python3.10-rapidfuzz-2.13.2/lib/python3.10/site-packages/rapidfuzz/distance/OSA_cpp.py", line 4, in <module>
    from rapidfuzz.distance.metrics_cpp import osa_distance as distance
ImportError: dynamic module does not define module export function (PyInit_metrics_cpp)
```

### Additional context

Introduced in #191025.

### Notify maintainers

@dotlambda

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.1.0, macOS 13.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(user): `"darwin, home-manager, nixpkgs, nur-packages"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by maxbachmann** [comment]
It appears that cmake selects an incorrect linker. I am currently unsure what's the reason for this. Following https://github.com/emscripten-core/emscripten/issues/11143 I think I might need to set:
```
set(CMAKE_C_COMPILER_AR "${CMAKE_AR}")
set(CMAKE_CXX_COMPILER_AR "${CMAKE_AR}")
set(CMAKE_C_COMPILER_RANLIB "${CMAKE_RANLIB}")
set(CMAKE_CXX_COMPILER_RANLIB "${CMAKE_RANLIB}")
```

@dotlambda I have zero experience with nix os + no access to a mac. Is there any way to patch `rapidfuzz` in the build system here to check whether this solves the issue?
