### ISSUE TITLE
cider: unable to start with --ozone-platform=wayland

### ISSUE THREAD

**Issue by hexagonal-sun** [NixOS/nixpkgs#204488]
### Describe the bug
When starting cider, if i use the option `--ozone-platform=wayland` to get native wayland rendering, I no longer see the main screen of Cider.  I know that the program is running as I see notifications pop up.  If I omit the option, cider starts up as expected.  This used to work with v1.5.6 but I think the upgrade to v1.5.7 (in #196751) caused this regression.

### Steps To Reproduce
1. nix shell "nixpkgs#cider"
2. cider --ozone-platform=wayland
3. No main window appears.

### Expected behavior
The app should start with native wayland support.

### Additional context
Output when starting (note that I think the errors described here may be a red herring since they also appear when I omit the option):

```
[15:09:10.196] [info]  [AppEvents] App started
[15:09:10.421] [info]  [Plugin][Music Recommendations] Loading Complete
[15:09:10.421] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'playbackNotifications.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js',
  'MusicRecommendationsPlugin'
]
[15:09:10.484] [info]  [AppEvents] App ready
[15:09:10.485] [info]  [Cider] Application is Ready. Creating Window.
[15:09:10.497] [info]  Setting up handlers for local files
[15:09:10.501] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[15:09:10.513] [info]  WebSocketServer started on port: 26369
[15:09:10.516] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2449.0'
  }
}
[2:1204/150910.533175:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[15:09:10.541] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: false,
      cudaComputeCapabilityMajor: 0,
      deviceId: 0,
      gpuPreference: 0,
      vendorId: 0
    }
  ]
}
[15:09:10.542] [info]  From here can you check for real changes, the initial scan has been completed.
[15:09:10.542] [info]  Cider client port: 9000
[15:09:10.543] [info]  Cider remote port: 6942
[15:09:10.545] [info]  remote broadcasted
[143:1204/150910.554326:ERROR:gl_surface_egl.cc(479)] eglCreateWindowSurface failed with error EGL_BAD_NATIVE_WINDOW
[143:1204/150910.557936:ERROR:x11_software_bitmap_presenter.cc(142)] XGetWindowAttributes failed for window 1
[15:09:10.903] [info]  [Plugin][Music Recommendations] Ready
[15:09:11.769] [info]  [Plugin][Music Recommendations] Renderer Ready
[15:09:11.806] [info]  /home/matthew/.config/Cider/Plugins/gh_462093451
[15:09:11.846] [warn]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[15:09:11.846] [error] Error: An object could not be cloned.
    at t.ipcRendererInternal.send (node:electron/js2c/sandbox_bundle:49:353)
    at EventEmitter.<anonymous> (node:electron/js2c/sandbox_bundle:45:357)
[15:09:11.847] [error] (node:2) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
    at t.ipcRendererInternal.send (node:electron/js2c/sandbox_bundle:49:353)
    at EventEmitter.<anonymous> (node:electron/js2c/sandbox_bundle:45:357)
(Use `cider --trace-warnings ...` to show where the warning was created)
[15:09:11.847] [error] (node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```
### Notify maintainers
@cigrainger 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.9, NixOS, 23.05 (Stoat), 23.05.20221127.b45ec95`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(matthew): `"home-manager-21.05"`
 - nixpkgs: `/nix/store/4c3fpmp1dz2icgf152sps2y4bv3l69xh-by2a22ch57a07qwxmd7w9jx4glwgn5pz-source`
```

**Comment by CobaltCause** [comment]
Trying to navigate upstream's diff between 1.5.7 and 1.5.8 was unnecessarily difficult:

* Upstream archived that repo and renamed it to https://github.com/ciderapp/Cider
* Upstream doesn't have a changelog
* Upstream flipflops on version numbers in their `package.json` (i.e. `1.5.7` -> `1.5.8` -> `1.5.7` again) so I'm not even sure which `1.5.7` commit is the real one
* Upstream most commonly writes nonsensical commit messages, at least in the range that I suspect are the real `1.5.6` to the real `1.5.7`: https://github.com/ciderapp/Cider/compare/ee4892ce1267f61cf8d3b4ac9bc6b67e907ed107...861845b22652c01e5342f3a31444bb5f77b3b554
* But at least they happened to write something barely descriptive enough that I was able to find out that `1.5.8` is *probably* using Electron 19, for whatever that's worth, because...

Currently nixpkgs (both 23.05 and unstable) has Cider 1.6.1 packaged, [which looks to be using Electron 24](https://github.com/ciderapp/Cider/blob/9dc14bfed90876f6e5a6e6196f931e16b1dcf3f8/package.json#L113). Downgrading to Electron 24 is actually one of the fixes for element-desktop (see https://github.com/NixOS/nixpkgs/issues/238416#issuecomment-1618662374), so I think this should be working now, and in my extremely brief testing on i915, it indeed works. I'd be tempted to close this as fixed because of that, *but* [Cider 1.6.2 upgraded to Electron 25](https://github.com/ciderapp/Cider/blob/58a2eefcda991772020b86c400ee52bc670e6364/package.json#L114), which would likely reintroduce the problem, leading to this exact issue again.

 I think the root cause of this is going to be the same as the root cause of:

* https://github.com/NixOS/nixpkgs/issues/237978
* https://github.com/NixOS/nixpkgs/issues/238416
* https://github.com/NixOS/nixpkgs/issues/159267

As empirically discovered in https://github.com/NixOS/nixpkgs/issues/238416#issuecomment-1646373750, once Cider 1.6.2 lands in nixpkgs, your best bet is probably to run the program like this (replacing `program` with the actual name of the executable in `$PATH`):

```
env -u NIXOS_OZONE_WL program --use-gl=desktop
```

But also, this particular program seems to be packaged using appimage stuff which I have no knowledge of, so that may or may not further complicate things.

**Comment by MangoIV** [comment]
this can be closed, I think

**Comment by danielpza** [comment]
> this can be closed, I think

I'm having the same issue on nixos 24.11, doesn't seem fixed yet

**Comment by MangoIV** [comment]
@danielpza have you tried with NIXOS_OZONE_WL=1 ?

**Comment by danielpza** [comment]
> @danielpza have you tried with NIXOS_OZONE_WL=1 ?

This is what I get:
<details><summary>NIXOS_OZONE_WL=1 nix run nixpkgs#cider</summary>
<p>

```
❯ NIXOS_OZONE_WL=1 nix run nixpkgs#cider 
[19:33:40.711] [info]  [AppEvents] App started
[19:33:40.778] [info]  [PluginHandler] Loaded plugins: []
[12180:1016/193341.099388:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
[19:33:41.823] [info]  [AppEvents] App ready
[19:33:41.823] [info]  [Cider] Application is Ready. Creating Window.
[19:33:41.823] [info]  aa
[19:33:41.824] [info]  [Cider] Creating Window.
[19:33:41.830] [info]  Setting up handlers for local files
[19:33:41.835] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[19:33:41.915] [info]  WebSocketServer started on port: 26369
[19:33:41.923] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    status: 'new',
    title: 'Widevine Content Decryption Module',
    version: '4.10.2830.0'
  }
}
[19:33:41.941] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glImplementationParts: '(gl=none,angle=none)',
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    isClangCoverage: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    subpixelFontRendering: true,
    targetCpuBits: 64,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 32069,
      gpuPreference: 0,
      vendorId: 32902
    }
  ]
}
[19:33:41.942] [info]  From here can you check for real changes, the initial scan has been completed.
[19:33:41.943] [info]  Cider client port: 9000
[19:33:41.945] [info]  Cider remote port: 6942
[19:33:41.946] [info]  remote broadcasted
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading '0')
    at Function.getLocale (file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/base/utils.ts:122:29)
    at AppEvents.setTray (file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/base/app.ts:326:23)
    at AppEvents.InitTray (file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/base/app.ts:282:10)
    at AppEvents.bwCreated (file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/base/app.ts:154:12)
    at file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/index.ts:60:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[19:34:11.042] [error] [chromecast.js] An error was encountered: TypeError: Cannot read properties of undefined (reading 'webContents')
[19:34:11.042] [error] TypeError: Cannot read properties of undefined (reading 'webContents')
    at ChromecastPlugin.onRendererReady (file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/plugins/chromecast.ts:350:15)
    at Plugins.callPlugins (file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/base/plugins.ts:108:42)
    at file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/index.ts:77:13
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:84060)
    at WebContents.emit (node:events:518:28)
    at WebContents.emit (node:domain:488:12)
    at WebContents.emitter.emit (file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/node_modules/@sentry/electron/src/main/integrations/electron-breadcrumbs.ts:146:16)

```

</p>
</details> 

I see the icon in the system tray, but no window appear.

I also tried `env -u NIXOS_OZONE_WL nix run nixpkgs#cider -- --use-gl=desktop` and doesn't work either.

<details><summary>env -u NIXOS_OZONE_WL nix run nixpkgs#cider -- --use-gl=desktop</summary>
<p>

```
❯ env -u NIXOS_OZONE_WL nix run nixpkgs#cider -- --use-gl=desktop
[19:37:35.451] [info]  [AppEvents] App started
[19:37:35.518] [info]  [PluginHandler] Loaded plugins: []
[12847:1016/193735.567783:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[12847:1016/193735.568824:ERROR:viz_main_impl.cc(198)] Exiting GPU process due to errors during initialization
[12866:1016/193735.709560:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[12866:1016/193735.710606:ERROR:viz_main_impl.cc(198)] Exiting GPU process due to errors during initialization
[12875:1016/193735.792291:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[12875:1016/193735.793533:ERROR:viz_main_impl.cc(198)] Exiting GPU process due to errors during initialization
[19:37:36.226] [info]  [AppEvents] App ready
[19:37:36.226] [info]  [Cider] Application is Ready. Creating Window.
[19:37:36.227] [info]  aa
[19:37:36.227] [info]  [Cider] Creating Window.
[19:37:36.233] [info]  Setting up handlers for local files
[19:37:36.238] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
[19:37:36.309] [info]  WebSocketServer started on port: 26369
[19:37:36.313] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    status: 'new',
    title: 'Widevine Content Decryption Module',
    version: '4.10.2830.0'
  }
}
[19:37:36.332] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glImplementationParts: '(gl=none,angle=none)',
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    isClangCoverage: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    subpixelFontRendering: true,
    targetCpuBits: 64,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 32069,
      gpuPreference: 0,
      vendorId: 32902
    }
  ]
}
[19:37:36.333] [info]  From here can you check for real changes, the initial scan has been completed.
[19:37:36.333] [info]  Cider client port: 9000
[19:37:36.335] [info]  Cider remote port: 6942
[19:37:36.337] [info]  remote broadcasted
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading '0')
    at Function.getLocale (file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/base/utils.ts:122:29)
    at AppEvents.setTray (file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/base/app.ts:326:23)
    at AppEvents.InitTray (file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/base/app.ts:282:10)
    at AppEvents.bwCreated (file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/base/app.ts:154:12)
    at file:///nix/store/bwdadna124h56mir93r214pqnz7d827v-cider-1.6.3-extracted/resources/app.asar/src/main/index.ts:60:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```


</p>
</details>
