### ISSUE TITLE
jellyfinmediaplayer segfaults

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#205141]
### Describe the bug

jellyfinmediaplayer is unuseable as it either segfaults immediately on startup, or when trying to play some media.

It worked fine in NixOS 22.05, but in 22.11 it crashes.

### Steps To Reproduce
1. Start app: `cd nixpkgs && git checkout 2d10e73416ec1449ef74aeac7faf2cf8c556ff5a && nix-build -A jellyfin-media-player && ./result/bin/jellyfinmediaplayer`
2. It might segfault immediately.
3. Or you might have to try playing some media for the segfault to happen.

### Expected behavior
No segfault.

### Additional context

Backtrace:

```
$ coredumpctl debug
[...]
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ffbc43ac9bb in core_event_demarshal_remove_id ()
   from /nix/store/b6im0vdj81hs3yqa3biw68dlvjj3gkx3-pipewire-0.3.60-lib/lib/pipewire-0.3/libpipewire-module-protocol-native.so
[Current thread is 1 (Thread 0x7ffbad7fa640 (LWP 3372))]
(gdb) bt
#0  0x00007ffbc43ac9bb in core_event_demarshal_remove_id ()
   from /nix/store/b6im0vdj81hs3yqa3biw68dlvjj3gkx3-pipewire-0.3.60-lib/lib/pipewire-0.3/libpipewire-module-protocol-native.so
#1  0x00007ffbc43a886c in process_remote ()
   from /nix/store/b6im0vdj81hs3yqa3biw68dlvjj3gkx3-pipewire-0.3.60-lib/lib/pipewire-0.3/libpipewire-module-protocol-native.so
#2  0x00007ffbc43a8e68 in on_remote_data ()
   from /nix/store/b6im0vdj81hs3yqa3biw68dlvjj3gkx3-pipewire-0.3.60-lib/lib/pipewire-0.3/libpipewire-module-protocol-native.so
#3  0x00007ffbc4430ece in loop_iterate () from /nix/store/b6im0vdj81hs3yqa3biw68dlvjj3gkx3-pipewire-0.3.60-lib/lib/spa-0.2/support/libspa-support.so
#4  0x00007ffbd4ffa2c2 in do_loop () from /nix/store/b6im0vdj81hs3yqa3biw68dlvjj3gkx3-pipewire-0.3.60-lib/lib/libpipewire-0.3.so.0
#5  0x00007ffbd7c17e86 in start_thread () from /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libc.so.6
#6  0x00007ffbd7c9ec60 in clone3 () from /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libc.so.6
(gdb)
```

### Metadata
NixOS 22.11. (Regression, worked fine in NixOS 22.05.)

**Comment by bjornfor** [comment]
Could it be a poor handling of version mismatch between server and client?

**Comment by bjornfor** [comment]
> Could it be a poor handling of version mismatch between server and client?

No, I don't think so, I managed to reproduce the segfault using jellyfin server also from NixOS 22.11. (Initially I was using server on 22.05 and client on 22.11.)

**Comment by bjornfor** [comment]
Bisected to b97cda7d44aa78fe915df7b0c18e3d6ed9edd157 being the first bad commit.

**Comment by bjornfor** [comment]
Upstream issue about the same thing: https://github.com/jellyfin/jellyfin-media-player/issues/341
