### ISSUE TITLE
Emacs and X server crashes after upgrade to 16.09

### ISSUE THREAD

**Issue by mz-pdm** [NixOS/nixpkgs#20535]
## Issue description

After I had upgraded to 16.09, Emacs 25.1 started to crash quite frequently (several times per week) and the X server also crashes from time to time. This has never happened to me before the upgrade although I used the same Emacs version (25.1 and 25 pretests). I tried to apply the Emacs patches from https://github.com/NixOS/nixpkgs/pull/20305/commits/db402312a32edd3b5ea39c4d2ef35a3a56d7e4e4, but Emacs still crashes.

Here are two backtraces from recent Emacs crashes

```
#0  0x00007f5ff4d87d64 in raise () from /nix/store/jm1n87rp8vr90j9ahcrfzr57nc2r8vgf-glibc-2.24/lib/libpthread.so.0
#1  0x00000000004ee233 in terminate_due_to_signal ()
#2  0x0000000000507fb3 in emacs_abort ()
#3  0x000000000045140d in redisplay_internal ()
#4  0x0000000000453cde in redisplay_preserve_echo_area ()
#5  0x00000000005a3958 in Fdelete_process ()
#6  0x00000000005ab895 in kill_buffer_processes ()
#7  0x00000000004ee033 in shut_down_emacs ()
#8  0x00000000004c1ff2 in x_connection_closed ()
#9  0x00000000004c2154 in x_io_error_quitter ()
#10 0x00007f5ff70d515e in _XIOError () from /nix/store/69z1pislpsflvjh6s4ipargmjg0jd3w3-libX11-1.6.4/lib/libX11.so.6
#11 0x00007f5ff70d29ad in _XEventsQueued () from /nix/store/69z1pislpsflvjh6s4ipargmjg0jd3w3-libX11-1.6.4/lib/libX11.so.6
#12 0x00007f5ff70c43f7 in XPending () from /nix/store/69z1pislpsflvjh6s4ipargmjg0jd3w3-libX11-1.6.4/lib/libX11.so.6
#13 0x00007f5ff941a1ee in gdk_event_prepare () from /nix/store/by68pzb1f68vcxzbns95wp3yz9c6ry1c-gtk+-2.24.31/lib/libgdk-x11-2.0.so.0
#14 0x00007f5ff783ee0d in g_main_context_prepare () from /nix/store/624597s5chn14ifvcqyw7qw2yfkgcp0f-glib-2.48.2/lib/libglib-2.0.so.0
#15 0x00007f5ff783f7bb in g_main_context_iterate.isra () from /nix/store/624597s5chn14ifvcqyw7qw2yfkgcp0f-glib-2.48.2/lib/libglib-2.0.so.0
#16 0x00007f5ff783f947 in g_main_context_pending () from /nix/store/624597s5chn14ifvcqyw7qw2yfkgcp0f-glib-2.48.2/lib/libglib-2.0.so.0
#17 0x00007f5ff97a7459 in gtk_events_pending () from /nix/store/by68pzb1f68vcxzbns95wp3yz9c6ry1c-gtk+-2.24.31/lib/libgtk-x11-2.0.so.0
#18 0x00000000004c21cb in XTread_socket ()
#19 0x00000000004f7669 in gobble_input ()
#20 0x00000000004f7a45 in process_pending_signals ()
#21 0x000000000054abc2 in Fmake_list ()
#22 0x000000000056a604 in concat ()
#23 0x000000000056a74c in Fcopy_sequence ()
#24 0x00000000004f3369 in timer_check ()
#25 0x00000000004f3969 in readable_events ()
#26 0x00000000004f77e8 in get_input_pending ()
#27 0x00000000004f79cf in detect_input_pending_run_timers ()
#28 0x00000000005a92a9 in wait_reading_process_output ()
#29 0x00000000004f964c in read_char ()
#30 0x00000000004fb54b in read_key_sequence.constprop ()
#31 0x00000000004fd2ce in command_loop_1 ()
#32 0x0000000000562bc6 in internal_condition_case ()
#33 0x00000000004ee6f4 in command_loop_2 ()
#34 0x0000000000562b4b in internal_catch ()
#35 0x00000000004ee69d in command_loop ()
#36 0x00000000004f18c3 in recursive_edit_1 ()
#37 0x00000000004f1c03 in Frecursive_edit ()
#38 0x0000000000415bb4 in main ()
```

```
#0  0x00007fc25855dd64 in raise () from /nix/store/jm1n87rp8vr90j9ahcrfzr57nc2r8vgf-glibc-2.24/lib/libpthread.so.0
#1  0x00000000004ee233 in terminate_due_to_signal ()
#2  0x0000000000507fb3 in emacs_abort ()
#3  0x0000000000564c71 in Fsignal ()
#4  0x0000000000564c89 in xsignal ()
#5  0x0000000000564cb7 in xsignal1 ()
#6  0x0000000000533cc3 in compile_pattern ()
#7  0x000000000053608f in fast_string_match_internal ()
#8  0x000000000051d61c in Ffind_file_name_handler ()
#9  0x000000000051eb66 in Fexpand_file_name ()
#10 0x00000000005246b8 in Fdo_auto_save ()
#11 0x00000000004ee03f in shut_down_emacs ()
#12 0x00000000004ee204 in terminate_due_to_signal ()
#13 0x0000000000506c5e in handle_fatal_signal ()
#14 0x0000000000506e89 in deliver_thread_signal.constprop ()
#15 0x0000000000506ef7 in handle_sigsegv ()
#16 <signal handler called>
#17 0x000000000054bb90 in mark_object ()
#18 0x00000000005b4bf9 in traverse_intervals_noorder ()
#19 0x00000000005b4be7 in traverse_intervals_noorder ()
#20 0x00000000005b4be7 in traverse_intervals_noorder ()
#21 0x00000000005b4be7 in traverse_intervals_noorder ()
#22 0x00000000005b4be7 in traverse_intervals_noorder ()
#23 0x00000000005b4be7 in traverse_intervals_noorder ()
#24 0x00000000005b4be7 in traverse_intervals_noorder ()
#25 0x00000000005b4be7 in traverse_intervals_noorder ()
#26 0x00000000005b4be7 in traverse_intervals_noorder ()
#27 0x00000000005b4be7 in traverse_intervals_noorder ()
#28 0x00000000005b4be7 in traverse_intervals_noorder ()
#29 0x00000000005b4be7 in traverse_intervals_noorder ()
#30 0x000000000054bf86 in mark_buffer ()
#31 0x000000000054d4bb in mark_localized_symbol ()
#32 0x000000000054bcb8 in mark_object ()
#33 0x000000000054bc89 in mark_object ()
#34 0x000000000054bc89 in mark_object ()
#35 0x000000000054bece in mark_vectorlike ()
#36 0x000000000054bf62 in mark_buffer ()
#37 0x000000000054d4bb in mark_localized_symbol ()
#38 0x000000000054bcb8 in mark_object ()
#39 0x000000000054bc89 in mark_object ()
#40 0x000000000054bc89 in mark_object ()
#41 0x000000000054baf1 in mark_object ()
#42 0x000000000054bc89 in mark_object ()
#43 0x000000000054bc89 in mark_object ()
#44 0x000000000054bac5 in mark_object ()
#45 0x000000000054bc89 in mark_object ()
#46 0x000000000054bc89 in mark_object ()
#47 0x000000000054bc89 in mark_object ()
#48 0x000000000054bac5 in mark_object ()
#49 0x000000000054bece in mark_vectorlike ()
#50 0x000000000054babc in mark_object ()
#51 0x000000000054bac5 in mark_object ()
#52 0x000000000054d138 in mark_compiled ()
#53 0x000000000054bdd8 in mark_object ()
#54 0x000000000054babc in mark_object ()
#55 0x000000000054d138 in mark_compiled ()
#56 0x000000000054bdd8 in mark_object ()
#57 0x000000000054babc in mark_object ()
#58 0x000000000054bc89 in mark_object ()
#59 0x000000000054bc89 in mark_object ()
#60 0x000000000054bece in mark_vectorlike ()
#61 0x000000000054bf62 in mark_buffer ()
#62 0x000000000054d4bb in mark_localized_symbol ()
#63 0x000000000054bcb8 in mark_object ()
#64 0x000000000054bece in mark_vectorlike ()
#65 0x000000000054babc in mark_object ()
#66 0x000000000054bc89 in mark_object ()
#67 0x000000000054bac5 in mark_object ()
#68 0x000000000054bece in mark_vectorlike ()
#69 0x000000000054babc in mark_object ()
#70 0x000000000054bece in mark_vectorlike ()
#71 0x000000000054babc in mark_object ()
#72 0x000000000054bc89 in mark_object ()
#73 0x000000000054bac5 in mark_object ()
#74 0x000000000054bc89 in mark_object ()
#75 0x000000000054bac5 in mark_object ()
#76 0x000000000054bc89 in mark_object ()
#77 0x000000000054bc89 in mark_object ()
#78 0x000000000054bc89 in mark_object ()
#79 0x000000000054bc89 in mark_object ()
#80 0x000000000054bc89 in mark_object ()
#81 0x000000000054bac5 in mark_object ()
#82 0x000000000054bc89 in mark_object ()
#83 0x000000000054bac5 in mark_object ()
#84 0x000000000054bece in mark_vectorlike ()
#85 0x000000000054babc in mark_object ()
#86 0x000000000054bece in mark_vectorlike ()
#87 0x000000000054babc in mark_object ()
#88 0x000000000054bc89 in mark_object ()
#89 0x000000000054bc89 in mark_object ()
#90 0x000000000054bac5 in mark_object ()
#91 0x000000000054bc89 in mark_object ()
#92 0x000000000054bc89 in mark_object ()
#93 0x000000000054bac5 in mark_object ()
#94 0x000000000054bc89 in mark_object ()
#95 0x000000000054bc89 in mark_object ()
#96 0x000000000054bac5 in mark_object ()
#97 0x000000000054bece in mark_vectorlike ()
#98 0x000000000054babc in mark_object ()
#99 0x000000000054babc in mark_object ()
#100 0x000000000054bece in mark_vectorlike ()
#101 0x000000000054babc in mark_object ()
#102 0x000000000054bece in mark_vectorlike ()
#103 0x000000000054babc in mark_object ()
#104 0x000000000054bece in mark_vectorlike ()
#105 0x000000000054babc in mark_object ()
#106 0x000000000054bc89 in mark_object ()
#107 0x000000000054bac5 in mark_object ()
#108 0x000000000054bc89 in mark_object ()
#109 0x000000000054bac5 in mark_object ()
#110 0x000000000054bece in mark_vectorlike ()
#111 0x000000000054babc in mark_object ()
#112 0x000000000054bc89 in mark_object ()
#113 0x000000000054baf1 in mark_object ()
#114 0x000000000054bc89 in mark_object ()
#115 0x000000000054bac5 in mark_object ()
#116 0x000000000054bc89 in mark_object ()
#117 0x000000000054d138 in mark_compiled ()
#118 0x000000000054bdd8 in mark_object ()
#119 0x000000000054babc in mark_object ()
#120 0x000000000054bece in mark_vectorlike ()
#121 0x000000000054babc in mark_object ()
#122 0x000000000054bc89 in mark_object ()
#123 0x000000000054bac5 in mark_object ()
#124 0x000000000054bece in mark_vectorlike ()
#125 0x000000000054b9f7 in mark_object ()
#126 0x000000000054bece in mark_vectorlike ()
#127 0x000000000054b9f7 in mark_object ()
#128 0x000000000054bece in mark_vectorlike ()
#129 0x000000000054bd65 in mark_object ()
#130 0x000000000054bece in mark_vectorlike ()
#131 0x000000000054b9f7 in mark_object ()
#132 0x000000000054baf1 in mark_object ()
#133 0x000000000054bece in mark_vectorlike ()
#134 0x000000000054babc in mark_object ()
#135 0x000000000054bece in mark_vectorlike ()
#136 0x000000000054babc in mark_object ()
#137 0x000000000054bece in mark_vectorlike ()
#138 0x000000000054babc in mark_object ()
#139 0x000000000054bac5 in mark_object ()
#140 0x000000000054bc89 in mark_object ()
#141 0x000000000054bc89 in mark_object ()
#142 0x000000000054bac5 in mark_object ()
#143 0x000000000054bece in mark_vectorlike ()
#144 0x000000000054babc in mark_object ()
#145 0x000000000054bece in mark_vectorlike ()
#146 0x000000000054babc in mark_object ()
#147 0x000000000054bc89 in mark_object ()
#148 0x000000000054bc89 in mark_object ()
#149 0x000000000054bac5 in mark_object ()
#150 0x000000000054bc89 in mark_object ()
#151 0x000000000054bc89 in mark_object ()
#152 0x000000000054bac5 in mark_object ()
#153 0x000000000054bc89 in mark_object ()
#154 0x000000000054bc89 in mark_object ()
#155 0x000000000054bac5 in mark_object ()
#156 0x000000000054bc89 in mark_object ()
#157 0x000000000054bc89 in mark_object ()
#158 0x000000000054bac5 in mark_object ()
#159 0x000000000054bc89 in mark_object ()
#160 0x000000000054bac5 in mark_object ()
#161 0x000000000054bc89 in mark_object ()
#162 0x000000000054bac5 in mark_object ()
#163 0x000000000054bc89 in mark_object ()
#164 0x000000000054bac5 in mark_object ()
#165 0x000000000054bece in mark_vectorlike ()
#166 0x000000000054bece in mark_vectorlike ()
#167 0x000000000054bc89 in mark_object ()
#168 0x000000000054bac5 in mark_object ()
#169 0x000000000054bc89 in mark_object ()
#170 0x000000000054bc89 in mark_object ()
#171 0x000000000054bc89 in mark_object ()
#172 0x000000000054bac5 in mark_object ()
#173 0x000000000054bc89 in mark_object ()
#174 0x000000000054bc89 in mark_object ()
#175 0x000000000054bac5 in mark_object ()
#176 0x000000000054bc89 in mark_object ()
#177 0x000000000054bc89 in mark_object ()
#178 0x000000000054bac5 in mark_object ()
#179 0x000000000054bc89 in mark_object ()
#180 0x000000000054bac5 in mark_object ()
#181 0x000000000054bc89 in mark_object ()
#182 0x000000000054bac5 in mark_object ()
#183 0x000000000054bc89 in mark_object ()
#184 0x000000000054bac5 in mark_object ()
#185 0x000000000054bece in mark_vectorlike ()
#186 0x000000000054babc in mark_object ()
#187 0x000000000054bc89 in mark_object ()
#188 0x000000000054bac5 in mark_object ()
#189 0x000000000054bc89 in mark_object ()
#190 0x000000000054bac5 in mark_object ()
#191 0x000000000054bc89 in mark_object ()
#192 0x000000000054bc89 in mark_object ()
#193 0x000000000054bac5 in mark_object ()
#194 0x000000000054bc89 in mark_object ()
#195 0x000000000054bc89 in mark_object ()
#196 0x000000000054bac5 in mark_object ()
#197 0x000000000054bc89 in mark_object ()
#198 0x000000000054bac5 in mark_object ()
#199 0x000000000054bc89 in mark_object ()
#200 0x000000000054bac5 in mark_object ()
#201 0x000000000054bc89 in mark_object ()
#202 0x000000000054bc89 in mark_object ()
#203 0x000000000054bac5 in mark_object ()
#204 0x000000000054bc89 in mark_object ()
#205 0x000000000054bc89 in mark_object ()
#206 0x000000000054bac5 in mark_object ()
#207 0x000000000054bc89 in mark_object ()
#208 0x000000000054bac5 in mark_object ()
#209 0x000000000054bc89 in mark_object ()
#210 0x000000000054bc89 in mark_object ()
#211 0x000000000054bac5 in mark_object ()
#212 0x000000000054bc89 in mark_object ()
#213 0x000000000054bc89 in mark_object ()
#214 0x000000000054bac5 in mark_object ()
#215 0x000000000054bc89 in mark_object ()
#216 0x000000000054bc89 in mark_object ()
#217 0x000000000054bac5 in mark_object ()
#218 0x000000000054bc89 in mark_object ()
#219 0x000000000054bac5 in mark_object ()
#220 0x000000000054bece in mark_vectorlike ()
#221 0x000000000054babc in mark_object ()
#222 0x000000000054bece in mark_vectorlike ()
#223 0x000000000054babc in mark_object ()
#224 0x000000000054bc89 in mark_object ()
#225 0x000000000054bac5 in mark_object ()
#226 0x000000000054bc89 in mark_object ()
#227 0x000000000054bc89 in mark_object ()
#228 0x000000000054bac5 in mark_object ()
#229 0x000000000054bc89 in mark_object ()
#230 0x000000000054bac5 in mark_object ()
#231 0x000000000054bc89 in mark_object ()
#232 0x000000000054bac5 in mark_object ()
#233 0x000000000054bc89 in mark_object ()
#234 0x000000000054babc in mark_object ()
#235 0x000000000054bc89 in mark_object ()
#236 0x000000000054bc89 in mark_object ()
#237 0x000000000054bece in mark_vectorlike ()
#238 0x000000000054bf62 in mark_buffer ()
#239 0x000000000054d4bb in mark_localized_symbol ()
#240 0x000000000054bcb8 in mark_object ()
#241 0x000000000054bece in mark_vectorlike ()
#242 0x000000000054babc in mark_object ()
#243 0x000000000054bc89 in mark_object ()
#244 0x000000000054bece in mark_vectorlike ()
#245 0x000000000054bf62 in mark_buffer ()
#246 0x000000000054d4bb in mark_localized_symbol ()
#247 0x000000000054bcb8 in mark_object ()
#248 0x000000000054bece in mark_vectorlike ()
#249 0x000000000054babc in mark_object ()
#250 0x000000000054bece in mark_vectorlike ()
#251 0x000000000054babc in mark_object ()
#252 0x000000000054bc89 in mark_object ()
#253 0x000000000054d138 in mark_compiled ()
#254 0x000000000054bdd8 in mark_object ()
#255 0x000000000054babc in mark_object ()
#256 0x000000000054bece in mark_vectorlike ()
#257 0x000000000054babc in mark_object ()
#258 0x000000000054bece in mark_vectorlike ()
#259 0x000000000054babc in mark_object ()
#260 0x000000000054bc89 in mark_object ()
#261 0x000000000054bac5 in mark_object ()
#262 0x000000000054bc89 in mark_object ()
#263 0x000000000054bac5 in mark_object ()
#264 0x000000000054bece in mark_vectorlike ()
#265 0x000000000054babc in mark_object ()
#266 0x000000000054bc89 in mark_object ()
#267 0x000000000054bac5 in mark_object ()
#268 0x000000000054bc89 in mark_object ()
#269 0x000000000054bac5 in mark_object ()
#270 0x000000000054bc89 in mark_object ()
#271 0x000000000054bac5 in mark_object ()
#272 0x000000000054bc89 in mark_object ()
#273 0x000000000054bac5 in mark_object ()
#274 0x000000000054bc89 in mark_object ()
#275 0x000000000054bac5 in mark_object ()
#276 0x000000000054bc89 in mark_object ()
#277 0x000000000054bac5 in mark_object ()
#278 0x000000000054bc89 in mark_object ()
#279 0x000000000054bac5 in mark_object ()
#280 0x000000000054bc89 in mark_object ()
#281 0x000000000054bac5 in mark_object ()
#282 0x000000000054bc89 in mark_object ()
#283 0x000000000054bac5 in mark_object ()
#284 0x000000000054bece in mark_vectorlike ()
#285 0x000000000054bf62 in mark_buffer ()
#286 0x000000000054c3f3 in Fgarbage_collect ()
#287 0x000000000059d993 in exec_byte_code ()
#288 0x000000000056439b in Ffuncall ()
#289 0x000000000059d6d3 in exec_byte_code ()
#290 0x000000000056439b in Ffuncall ()
#291 0x000000000059d6d3 in exec_byte_code ()
#292 0x000000000056439b in Ffuncall ()
#293 0x000000000059d6d3 in exec_byte_code ()
#294 0x000000000056439b in Ffuncall ()
#295 0x000000000059d6d3 in exec_byte_code ()
#296 0x000000000056439b in Ffuncall ()
#297 0x0000000000564609 in funcall_nil ()
#298 0x0000000000562ded in run_hook_with_args ()
#299 0x0000000000562f58 in run_hook ()
#300 0x0000000000562f85 in Frun_hooks ()
#301 0x00000000005644b1 in Ffuncall ()
#302 0x000000000059d6d3 in exec_byte_code ()
#303 0x000000000056439b in Ffuncall ()
#304 0x000000000059d6d3 in exec_byte_code ()
#305 0x000000000056439b in Ffuncall ()
#306 0x000000000059d488 in bcall0 ()
#307 0x000000000056319a in unbind_to ()
#308 0x000000000059d728 in exec_byte_code ()
#309 0x000000000056439b in Ffuncall ()
#310 0x000000000059d6d3 in exec_byte_code ()
#311 0x000000000056439b in Ffuncall ()
#312 0x000000000059d6d3 in exec_byte_code ()
#313 0x000000000056439b in Ffuncall ()
#314 0x000000000059d6d3 in exec_byte_code ()
#315 0x000000000056439b in Ffuncall ()
#316 0x000000000056597c in Fapply ()
#317 0x00000000005644b1 in Ffuncall ()
#318 0x000000000059d6d3 in exec_byte_code ()
#319 0x0000000000563f9d in funcall_lambda ()
#320 0x000000000056439b in Ffuncall ()
#321 0x00000000005646aa in call1 ()
#322 0x00000000004f353d in timer_check ()
#323 0x00000000004f3969 in readable_events ()
#324 0x00000000004f77e8 in get_input_pending ()
#325 0x00000000004f79cf in detect_input_pending_run_timers ()
#326 0x00000000005a92a9 in wait_reading_process_output ()
#327 0x000000000041fb35 in sit_for ()
#328 0x00000000004fa921 in read_char ()
#329 0x00000000004fb54b in read_key_sequence.constprop ()
#330 0x00000000004fd2ce in command_loop_1 ()
#331 0x0000000000562bc6 in internal_condition_case ()
#332 0x00000000004ee6f4 in command_loop_2 ()
#333 0x0000000000562b4b in internal_catch ()
#334 0x00000000004ee62b in command_loop ()
#335 0x00000000004f18c3 in recursive_edit_1 ()
#336 0x000000000051c5b1 in read_minibuf ()
#337 0x000000000051cd66 in Fread_from_minibuffer ()
#338 0x0000000000564529 in Ffuncall ()
#339 0x000000000059d6d3 in exec_byte_code ()
#340 0x000000000056439b in Ffuncall ()
#341 0x000000000059d6d3 in exec_byte_code ()
#342 0x000000000056439b in Ffuncall ()
#343 0x00000000005657e0 in Fapply ()
#344 0x00000000005644b1 in Ffuncall ()
#345 0x000000000059d6d3 in exec_byte_code ()
#346 0x000000000056439b in Ffuncall ()
#347 0x00000000005657e0 in Fapply ()
#348 0x00000000005644b1 in Ffuncall ()
#349 0x000000000059d6d3 in exec_byte_code ()
#350 0x000000000056439b in Ffuncall ()
#351 0x000000000059d6d3 in exec_byte_code ()
#352 0x000000000056439b in Ffuncall ()
#353 0x000000000059d6d3 in exec_byte_code ()
#354 0x000000000056439b in Ffuncall ()
#355 0x000000000059d6d3 in exec_byte_code ()
#356 0x000000000056439b in Ffuncall ()
#357 0x00000000005657e0 in Fapply ()
#358 0x00000000005644b1 in Ffuncall ()
#359 0x000000000059d6d3 in exec_byte_code ()
#360 0x000000000056439b in Ffuncall ()
#361 0x000000000051b272 in Fcompleting_read ()
#362 0x0000000000564529 in Ffuncall ()
#363 0x000000000059d6d3 in exec_byte_code ()
#364 0x0000000000563add in eval_sub ()
#365 0x0000000000567037 in Feval ()
#366 0x0000000000560673 in Fcall_interactively ()
#367 0x0000000000564593 in Ffuncall ()
#368 0x000000000059d6d3 in exec_byte_code ()
#369 0x000000000056439b in Ffuncall ()
#370 0x00000000005646aa in call1 ()
#371 0x00000000004fd4d8 in command_loop_1 ()
#372 0x0000000000562bc6 in internal_condition_case ()
#373 0x00000000004ee6f4 in command_loop_2 ()
#374 0x0000000000562b4b in internal_catch ()
#375 0x00000000004ee69d in command_loop ()
#376 0x00000000004f18c3 in recursive_edit_1 ()
#377 0x00000000004f1c03 in Frecursive_edit ()
#378 0x0000000000415bb4 in main ()
```

### Steps to reproduce

I can't reproduce the problem, the crashes happen randomly.

## Technical details

* System: 16.09.1038.a6728e1 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.1038.a6728e1"

**Comment by AndersonTorres** [comment]
It is also occurring in my local install (NixOS 17.03pre95306.a24728f)

**Comment by yegortimoshenko** [comment]
@AndersonTorres Does it work now?

**Comment by AndersonTorres** [comment]
I'll try now.

**Comment by AndersonTorres** [comment]
18.03pre123130.1bc288591ea (Impala)

OK for me!

**Comment by yegortimoshenko** [comment]
Great! Thanks.
