### ISSUE TITLE
Spyder crash: ModuleNotFoundError: No module named 'zmq'

### ISSUE THREAD

**Issue by Lurux** [NixOS/nixpkgs#205497]
### Describe the bug
Tried installing Spyder with `nix-env -iA nixpkgs.spyder`, but the following error shows up when trying to launch it:

```
Traceback (most recent call last):
  File "/nix/store/7wp2ylazliy5w2naqird53m23qq81ixv-python3.10-spyder-5.4.0/bin/..spyder-wrapped-wrapped", line 6, in <module>
    from spyder.app.start import main
  File "/nix/store/7wp2ylazliy5w2naqird53m23qq81ixv-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/app/start.py", line 42, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
```

### Environnement

Installed Nix in multi-user mode on Linux Mint 21 (Ubuntu 22.04) using [these instructions](https://nixos.org/download.html)

### Steps To Reproduce
1. Install Nix
2.  `nix-env -iA nixpkgs.spyder`
3. Launch Spyder (in terminal)

### Expected behavior
Hopefully I didn't misunderstand something here, but I would expect Spyder to launch normally.

### Additional context
I tried installing pyzmq manually with `nix-env -iA nixpkgs.python310Packages.pyzmq`, but the same error still shows up.

### Notify maintainers
@gebner

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-56-generic, Linux Mint, 21 (Vanessa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by nanophilip** [comment]
### Describe the bug
I experience the same on NixOS 22.11.

### Steps To Reproduce
Steps to reproduce the behavior:
```
$ nix-shell -p spyder
[nix-shell:~]$ spyder
Traceback (most recent call last):
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/bin/..spyder-wrapped-wrapped", line 6, in <module>
    from spyder.app.start import main
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/app/start.py", line 42, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
```

I also tried another approach that fails with a different error message.
```
$ cat shell.nix
{ pkgs ? import <nixpkgs> {} }:
let
  my-python = pkgs.python3;
  python-with-my-packages = my-python.withPackages (p: with p; [
    pandas
    # requests
    # other python packages you want
    spyder
  ]);
in
pkgs.mkShell {
  packages = [
    python-with-my-packages
    # other dependencies
  ];
}
$ nix-shell shell.nix
[nix-shell:~]$ spyder
Traceback (most recent call last):
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/bin/..spyder-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/app/start.py", line 248, in main
    from spyder.app import mainwindow
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/app/mainwindow.py", line 40, in <module>
    requirements.check_path()
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/requirements.py", line 39, in check_path
    show_warning("Spyder must be installed properly "
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/requirements.py", line 32, in show_warning
    raise RuntimeError(message)
RuntimeError: Spyder must be installed properly (e.g. from source: 'python setup.py install'),
or directory '/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages' must be in PYTHONPATH environment variable.
```

### Expected behavior
On NixOS 22.05, Spyder started normally.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.80, NixOS, 22.11 (Raccoon), 22.11.758.e8ec26f41fd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.11"`
 - channels(x): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by nanophilip** [comment]
### Describe the bug
I experience the same on NixOS 22.11.

### Steps To Reproduce
Steps to reproduce the behavior:
```
$ nix-shell -p spyder
[nix-shell:~]$ spyder
Traceback (most recent call last):
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/bin/..spyder-wrapped-wrapped", line 6, in <module>
    from spyder.app.start import main
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/app/start.py", line 42, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
```

I also tried another approach that fails with a different error message.
```
$ cat shell.nix
{ pkgs ? import <nixpkgs> {} }:
let
  my-python = pkgs.python3;
  python-with-my-packages = my-python.withPackages (p: with p; [
    pandas
    # requests
    # other python packages you want
    spyder
  ]);
in
pkgs.mkShell {
  packages = [
    python-with-my-packages
    # other dependencies
  ];
}
$ nix-shell shell.nix
[nix-shell:~]$ spyder
Traceback (most recent call last):
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/bin/..spyder-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/app/start.py", line 248, in main
    from spyder.app import mainwindow
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/app/mainwindow.py", line 40, in <module>
    requirements.check_path()
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/requirements.py", line 39, in check_path
    show_warning("Spyder must be installed properly "
  File "/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/requirements.py", line 32, in show_warning
    raise RuntimeError(message)
RuntimeError: Spyder must be installed properly (e.g. from source: 'python setup.py install'),
or directory '/nix/store/gxjygi935d1q6325v00vprpxscvi47vd-python3.10-spyder-5.4.0/lib/python3.10/site-packages' must be in PYTHONPATH environment variable.
```

### Expected behavior
On NixOS 22.05, Spyder started normally.

### Metadata
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.80, NixOS, 22.11 (Raccoon), 22.11.758.e8ec26f41fd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.11"`
 - channels(x): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by nanophilip** [comment]
I now tried:
```
$ nix-shell -p python310Packages.pip
$ python -m venv .venv
$ source .venv/bin/activate
(.venv) $ pip install --no-binary spyder spyder
(.venv) $ spyder
```
This produces
```
Traceback (most recent call last):
  File "/home/user/.venv/bin/spyder", line 33, in <module>
    sys.exit(load_entry_point('spyder==5.4.0', 'gui_scripts', 'spyder')())
  File "/home/user/.venv/bin/spyder", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/nix/store/lbn7f0d2k36i4bgfdrjdwj7npy3r3h5d-python3-3.10.8/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/nix/store/lbn7f0d2k36i4bgfdrjdwj7npy3r3h5d-python3-3.10.8/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/.venv/lib/python3.10/site-packages/spyder/app/start.py", line 42, in <module>
    import zmq
  File "/home/user/.venv/lib/python3.10/site-packages/zmq/__init__.py", line 103, in <module>
    from zmq import backend
  File "/home/user/.venv/lib/python3.10/site-packages/zmq/backend/__init__.py", line 31, in <module>
    raise original_error from None
  File "/home/user/.venv/lib/python3.10/site-packages/zmq/backend/__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "/home/user/.venv/lib/python3.10/site-packages/zmq/backend/select.py", line 31, in select_backend
    mod = import_module(name)
  File "/nix/store/lbn7f0d2k36i4bgfdrjdwj7npy3r3h5d-python3-3.10.8/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/.venv/lib/python3.10/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
```

I then found [https://nixos.wiki/wiki/Packaging/Quirks_and_Caveats#ImportError:_libstdc.2B.2B.so.6:_cannot_open_shared_object_file:_No_such_file](https://nixos.wiki/wiki/Packaging/Quirks_and_Caveats#ImportError:_libstdc.2B.2B.so.6:_cannot_open_shared_object_file:_No_such_file) and tried
```
$ cat shell.nix 
{ pkgs ? (import <nixpkgs> {}).pkgs }:
with pkgs;
mkShell {
  buildInputs = [
    # python3Packages.virtualenv # run virtualenv .
    # python3Packages.pyqt5 # avoid installing via pip
    # python3Packages.pyusb # fixes the pyusb 'No backend available' when installed directly via pip
    python310Packages.virtualenv # run virtualenv .
    python310Packages.spyder
    python310Packages.pyzmq
    # python310Packages.pip
  ];
  shellHook = ''
    # fixes libstdc++ issues and libgl.so issues
    LD_LIBRARY_PATH=${stdenv.cc.cc.lib}/lib/:/run/opengl-driver/lib/
    # fixes xcb issues :
    QT_PLUGIN_PATH=${qt5.qtbase}/${qt5.qtbase.qtPluginPrefix}
  '';
}
$ nix-shell shell.nix
$ spyder
```
This produces
```
Traceback (most recent call last):
  File "/nix/store/yxmyyvpimj4rilwk9s5vcjwpnc86bz3s-python3.10-spyder-5.4.0/bin/..spyder-wrapped-wrapped", line 6, in <module>
    from spyder.app.start import main
  File "/nix/store/yxmyyvpimj4rilwk9s5vcjwpnc86bz3s-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/app/start.py", line 42, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
```

Then I tried
```
$ cat shell.nix 
{ pkgs ? (import <nixpkgs> {}).pkgs }:
with pkgs;
mkShell {
  buildInputs = [
    # python3Packages.virtualenv # run virtualenv .
    # python3Packages.pyqt5 # avoid installing via pip
    # python3Packages.pyusb # fixes the pyusb 'No backend available' when installed directly via pip
    python310Packages.virtualenv # run virtualenv .
    # python310Packages.spyder
    # python310Packages.pyzmq
    python310Packages.pip
  ];
  shellHook = ''
    # fixes libstdc++ issues and libgl.so issues
    LD_LIBRARY_PATH=${stdenv.cc.cc.lib}/lib/:/run/opengl-driver/lib/
    # fixes xcb issues :
    QT_PLUGIN_PATH=${qt5.qtbase}/${qt5.qtbase.qtPluginPrefix}
  '';
}
$ nix-shell shell.nix
$ python -m venv .venv
$ source .venv/bin/activate
(.venv) $ pip install --no-binary spyder spyder
(.venv) $ spyder
```

This produces
```
Traceback (most recent call last):
  File "/home/user//.venv/bin/spyder", line 33, in <module>
    sys.exit(load_entry_point('spyder==5.4.0', 'gui_scripts', 'spyder')())
  File "/home/user//.venv/bin/spyder", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/nix/store/lbn7f0d2k36i4bgfdrjdwj7npy3r3h5d-python3-3.10.8/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/nix/store/lbn7f0d2k36i4bgfdrjdwj7npy3r3h5d-python3-3.10.8/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user//.venv/lib/python3.10/site-packages/spyder/app/start.py", line 42, in <module>
    import zmq
  File "/home/user//.venv/lib/python3.10/site-packages/zmq/__init__.py", line 103, in <module>
    from zmq import backend
  File "/home/user//.venv/lib/python3.10/site-packages/zmq/backend/__init__.py", line 31, in <module>
    raise original_error from None
  File "/home/user//.venv/lib/python3.10/site-packages/zmq/backend/__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "/home/user//.venv/lib/python3.10/site-packages/zmq/backend/select.py", line 31, in select_backend
    mod = import_module(name)
  File "/nix/store/lbn7f0d2k36i4bgfdrjdwj7npy3r3h5d-python3-3.10.8/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user//.venv/lib/python3.10/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
```
Although `echo echo $LD_LIBRARY_PATH` gives `/nix/store/mdck89nsfisflwjv6xv8ydj7dj0sj2pn-gcc-11.3.0-lib/lib/:/run/opengl-driver/lib/` and `ls /nix/store/mdck89nsfisflwjv6xv8ydj7dj0sj2pn-gcc-11.3.0-lib/lib/` produces
```
libasan.la          libgcc_s.so.1     libquadmath.la        libstdc++.so.6.0.29
libasan.so          libgomp.la        libquadmath.so        libstdc++.so.6.0.29-gdb.py
libasan.so.6        libgomp.so        libquadmath.so.0      libsupc++.la
libasan.so.6.0.0    libgomp.so.1      libquadmath.so.0.0.0  libtsan.la
libatomic.la        libgomp.so.1.0.0  libssp.la             libtsan.so
libatomic.so        libitm.la         libssp_nonshared.la   libtsan.so.0
libatomic.so.1      libitm.so         libssp.so             libtsan.so.0.0.0
libatomic.so.1.2.0  libitm.so.1       libssp.so.0           libubsan.la
libcc1.la           libitm.so.1.0.0   libssp.so.0.0.0       libubsan.so
libcc1.so           liblsan.la        libstdc++fs.la        libubsan.so.1
libcc1.so.0         liblsan.so        libstdc++.la          libubsan.so.1.0.0
libcc1.so.0.0.0     liblsan.so.0      libstdc++.so
libgcc_s.so         liblsan.so.0.0.0  libstdc++.so.6
```

Perhaps @fabaff or @jonringer would know how to fix this?

**Comment by fabaff** [comment]
The same issue happens on NixOS:

```bash
$ nix-env -iA nixos.spyder
$ spyder
Traceback (most recent call last):
  File "/nix/store/icbklw22yrzy7s8k2ai8chkhrvna8pxr-python3.10-spyder-5.4.0/bin/..spyder-wrapped-wrapped", line 6, in <module>
    from spyder.app.start import main
  File "/nix/store/icbklw22yrzy7s8k2ai8chkhrvna8pxr-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/app/start.py", line 42, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
```

`pyzmg` is presnet but not detected by spyder.

**Comment by bjornfor** [comment]
See https://github.com/NixOS/nixpkgs/pull/208734
