### ISSUE TITLE
nodejs-14_x ships with broken node-gyp on darwin

### ISSUE THREAD

**Issue by jgresty** [NixOS/nixpkgs#206231]
### Describe the bug

It looks like the version of node-gyp has been updated upstream in nodejs-14_x which now checks the system for xcode tools. The patch that nodejs-16_x and up uses: [bypass-darwin-xcrun-node16.patch](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/web/nodejs/bypass-darwin-xcrun-node16.patch) looks like it will resolve this issue.

Currently any attempt to build a package with node-gyp will result in the error:
```
> node-gyp-build

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/nix/store/9qrji1g1yfdyn6c3vvqa4x2pw9lmzg0f-nodejs-14.21.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Darwin 22.1.0
gyp ERR! command "/nix/store/9qrji1g1yfdyn6c3vvqa4x2pw9lmzg0f-nodejs-14.21.1/bin/node" "/nix/store/9qrji1g1yfdyn6c3vvqa4x2pw9lmzg0f-nodejs-14.21.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jgresty/registry/node_modules/@snyk/node-dump-stacks
gyp ERR! node -v v14.21.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

### Steps To Reproduce
1. install nodejs-14_x on darwin into your shell
2. try to build a package which uses node-gyp

### Expected behavior
Packages build successfully

### Notify maintainers

@cillianderoiste @gilligan @cko @marsam 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.1.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(jgresty): `""`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by winterqt** [comment]
The node-gyp version in Node 14 [hasn't changed since 2020](https://github.com/nodejs/node/commit/6cea3152fe5cb9d3238a47f422f43714a98e517b), so if this was working before, I find it weird that it suddenly broke. You *are* using the bundled node-gyp though, so...

cc @lilyinstarlight, did it ever work on Node 14?

**Comment by lilyinstarlight** [comment]
It was supposed to be working on Node 14 after bbfc913c6aadc9f792f94340216012ac7b1587b2 and the patch is definitely still making it to the output of the `nodejs-14_x.x86_64-darwin` build on Hydra, but it looks like that patch never overrode the call to `CLTVersion` in `xcode_emulation.py` and that's what's producing the errors in the above log

So it is possible that it just never worked or node2nix did something to work around that (making `nodePackages` unaffected). I suppose the patch could be adjusted to also avoid calling `CLTVersion` and set a static version, like the newer patch does

**Comment by jgresty** [comment]
version 14 is way past EOL and is no longer in nixpkgs
