### ISSUE TITLE
prismlauncher: OpenAL fails to initialize, no audio in-game

### ISSUE THREAD

**Issue by lambdadog** [NixOS/nixpkgs#206378]
### Describe the bug
When using prismlauncher to launch Minecraft, OpenAL doesn't initialize correctly, leading to the game having no sound.

### Steps To Reproduce
  1. Install `prismlauncher` from nixpkgs.
  2. Start prismlauncher
  3. Login to minecraft account and create a new instance
  4. Launch the instance

### Expected behavior
OpenAL initializes, audio works in game.

### Additional context
<details>
<summary>Minecraft error message</summary>

```console
[05:18:38] [Render thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: Failed to open OpenAL device
	at dym.a(SourceFile:283) ~[minecraft-1.19.2-client.jar:?]
	at dym.a(SourceFile:153) ~[minecraft-1.19.2-client.jar:?]
	at fnw.h(SourceFile:113) ~[minecraft-1.19.2-client.jar:?]
	at fnw.a(SourceFile:103) ~[minecraft-1.19.2-client.jar:?]
	at fnz.a(SourceFile:112) ~[minecraft-1.19.2-client.jar:?]
	at fnz.a(SourceFile:38) ~[minecraft-1.19.2-client.jar:?]
	at air.a(SourceFile:13) ~[minecraft-1.19.2-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at ais.a(SourceFile:69) ~[minecraft-1.19.2-client.jar:?]
	at ayz.execute(SourceFile:103) ~[minecraft-1.19.2-client.jar:?]
	at ais.a(SourceFile:68) ~[minecraft-1.19.2-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:211) [minecraft-1.19.2-client.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:198) [minecraft-1.19.2-client.jar:?]
	at dzu.e(SourceFile:315) [minecraft-1.19.2-client.jar:?]
	at efu.f(SourceFile:1205) [minecraft-1.19.2-client.jar:?]
	at efu.e(SourceFile:768) [minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:244) [minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) [minecraft-1.19.2-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
```
</details>

<details>
<summary>OpenAL log (<code>ALSOFT_LOGLEVEL=3 ALSOFT_LOGFILE=/tmp/alsoft.log</code>)</summary>

```console
[ALSOFT] (II) Initializing library v1.21.1-2290817 master
[ALSOFT] (II) Supported backends: jack, pulse, alsa, oss, port, null, wave
[ALSOFT] (II) Loading config /etc/openal/alsoft.conf...
[ALSOFT] (II)  found 'drivers' = 'pulse'
[ALSOFT] (II) Loading config /run/current-system/sw/etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /nix/var/nix/profiles/default/etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /etc/profiles/per-user/lambdadog/etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /home/lambdadog/.nix-profile/etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /home/lambdadog/.config/kdedefaults/alsoft.conf...
[ALSOFT] (II) Loading config /nix/store/3xz31hkj2l06s3ay7xq0gcsw3f0yvr06-kxmlgui-5.95.0-bin/etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /nix/store/10ra62np95pby2cqw2idpfnndbwqrizl-kio-5.95.0/etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /nix/store/vq9w0ydqz53wbgn4isb6l5sw9mixhga4-kservice-5.95.0-bin/etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /nix/store/kn958hng86iq0nmjk0ldpdpn7d64ihg8-baloo-5.95.0/etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /nix/store/whscnmn5shjgy9f2cghsyh8lra604l1z-kdelibs4support-5.95.0/etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /nix/store/7b14lcrnrwcw4qmvxr17wna8xrnp5mfk-plasma-workspace-5.25.0/etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /home/lambdadog/.alsoftrc...
[ALSOFT] (II) Loading config /home/lambdadog/.config/alsoft.conf...
[ALSOFT] (II) Got binary: /nix/store/q7f1lbardp324n0dayiqnjddgzwwx374-openjdk-17.0.3+7/lib/openjdk/bin, java
[ALSOFT] (II) Loading config /nix/store/q7f1lbardp324n0dayiqnjddgzwwx374-openjdk-17.0.3+7/lib/openjdk/bin/alsoft.conf...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Vendor ID: ""
[ALSOFT] (II) Name: "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Found drivers = "pulse"
[ALSOFT] (WW) Failed to load libpulse.so.0
[ALSOFT] (WW) Failed to initialize backend "pulse"
[ALSOFT] (WW) No playback backend available!
[ALSOFT] (WW) No capture backend available!
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (WW) Error generated on device (nil), code 0xa004
[ALSOFT] (WW) Error generated on device (nil), code 0xa004
```
</details>

### Notify maintainers
@Minion3665 @Scrumplex

### Metadata
```console
[lambdadog@taiga:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.49, NixOS, 22.11 (Raccoon), 22.11pre388062.f2537a505d4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - channels(lambdadog): `"nixpkgs-unstable"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lambdadog** [comment]
Obviously there are a handful of "stateful" `alsoft.conf` includes here, but it seems to me they're unrelated to the issue and the core issue is 

```console
[ALSOFT] (WW) Failed to load libpulse.so.0
[ALSOFT] (WW) Failed to initialize backend "pulse"
[ALSOFT] (WW) No playback backend available!
[ALSOFT] (WW) No capture backend available!
```

which should be unrelated to all of these configs and has to do with the context minecraft is launching in being unable to discover the libpulse.so.0 provided to prismlauncher, for some reason.

It seems that it should be provided by the `wrapQtApp` invocation setting `LD_LIBRARY_PATH`, but for some reason it's not being discovered?

**Comment by janTasija** [comment]
is there any solution to this yet?

**Comment by lambdadog** [comment]
As a workaround you can install the `alsa-oss` package to your environment and add it as a wrapper command in the prismlauncher config:

![wrapper](https://user-images.githubusercontent.com/36526063/213885797-a3426bcd-76e7-41c1-b7b2-8e6500b2ebf0.png)

This will let OpenAL load with its OSS backend, with the alsa-oss package bridging OSS to ALSA. I use this on a Pipewire system with both the ALSA and PulseAudio adapters enabled as described in the blog post below and [here](https://nixos.wiki/wiki/PipeWire), as opposed to a PulseAudio system on top of ALSA, so I haven't tested it with that setup but I don't see why it wouldn't work, although you may get worse mixing on your system with applications that connect to ALSA directly vs PulseAudio on top of ALSA.

Credit to this (Chinese) blogpost: [Minecraft on NixOS/Linux cannot initialize OpenAL](https://frnks.top/2022/10/13/2022-10-14-linux_minecraft%E6%97%A0%E6%B3%95%E5%88%9D%E5%A7%8B%E5%8C%96openal%20/) [[Google Translated](https://frnks-top.translate.goog/2022/10/13/2022-10-14-linux_minecraft%E6%97%A0%E6%B3%95%E5%88%9D%E5%A7%8B%E5%8C%96openal%20/?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)]

**Comment by NovaViper** [comment]
@lambdadog I just tried this and it didn't work for me, in fact it just makes Minecraft instantly crash with
```
java: alsa-oss.c:313: open64: Assertion `fds[fd] == NULL' failed.
Process crashed with exitcode 6.
```

... I wasn't having issues before with the audio for a long while up until [I updated my flake to address that xz backdoor](https://github.com/NovaViper/NixConfig/commit/8c54cb61aa2938e5279a2880c5ed1160d3ce8d66); now the sound isn't work at all for Minecraft with the same error. I'm completely unsure what exactly is causing the problem but trying the `alas-oss` solution didn't work for me 😓

**Comment by returnofblank** [comment]
Thanks for your solution, can confirm this solution worked.

**Comment by khaneliman** [comment]
> EDIT: I got it fixed! I had to tell PrismLauncher to update the Java path, doing so fixed the issues!

Strange, but appeared to have worked for me, too. I just went into the Settings -> Java --> Auto-Detect --> Select Java 17 again. Appreciate the tip.

**Comment by iogrt** [comment]
I tried all of the above but I've been facing this issue:
```Assertion 'p' failed at ../src/pulse/simple.c:273, function pa_simple_write(). Aborting.```

This error also occurs without the previous setup... I understand it's a pulseaudio issue. What can I do to solve it?

**Comment by TornaxO7** [comment]
lol, I didn't expect to find an issue with this :D Neverthless, I'm having this problem as well :(

**Comment by TornaxO7** [comment]
Hm... I can't 

> @lambdadog I just tried this and it didn't work for me, in fact it just makes Minecraft instantly crash with
> 
> ```
> java: alsa-oss.c:313: open64: Assertion `fds[fd] == NULL' failed.
> Process crashed with exitcode 6.
> ```
> 
> ... I wasn't having issues before with the audio for a long while up until [I updated my flake to address that xz backdoor](https://github.com/NovaViper/NixConfig/commit/8c54cb61aa2938e5279a2880c5ed1160d3ce8d66); now the sound isn't work at all for Minecraft with the same error. I'm completely unsure what exactly is causing the problem but trying the `alas-oss` solution didn't work for me 😓
> 
> EDIT: I got it fixed! I had to tell PrismLauncher to update the Java path, doing so fixed the issues!

sadly this didn't work for me.
I chose the `1.17` version with the `/nix/store` but also the `java` path version doesn't work either.

![image](https://github.com/NixOS/nixpkgs/assets/50843046/9bb2373b-1109-4ae7-9d8c-f65513358a53)

I'm on 24.04 stable.

**Comment by returnofblank** [comment]
Just to ask, did you click refresh? The paths may still be outdated otherwise.

**Comment by TornaxO7** [comment]
> Just to ask, did you click refresh? The paths may still be outdated otherwise.

Just did that and reselcted the second entry, pressed `Ok` and launched it again. I'm still getting the error if I try to enter a world.

**Comment by lambdadog** [comment]
@TornaxO7 I suspect the issue here is that the Java version you're using links to a different version of OSS than alsa-oss does? Although I can't be certain about that. Try updating both alsa-oss and your Java install in your environment. Nixpkgs should have them both pinned to the same version if they're installed from the same snapshot.

**Comment by StealthyKamereon** [comment]
Still have the issue :/
Both packages are up to date on the nixkpkg unstable flake, I have openjdk-17.0.11 and alsa-oss-1.1.8.
Does anybody has a fix for this bug ?

**Comment by StealthyKamereon** [comment]
Never mind I found how to solve the original bug. I got inspired by https://gist.github.com/danbst/a335b93f515606975bc1e6425ce9fecb and found that I was missing `libpulseaudio`.
I then enabled `nix-ld` with :
```nix
  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    ...
    libpulseaudio
  ];
```
You may also need `libGL` and `glfw` (I do but I don't want to clutter the paste for those who are interested only in the bug).

**Comment by jasper-clarke** [comment]
@StealthyKamereon 
nix-ld doesn't seem to be working for me.
I'm developing Minecraft Mods with IntelliJ and OpenAL outputs it can't find, pulse, alsa or jack!
```
    nix-ld = {
      enable = true;
      libraries = with pkgs; [
        alsa-lib
        at-spi2-atk
        at-spi2-core
        atk
        cairo
        cups
        curl
        dbus
        expat
        fontconfig
        freetype
        fuse3
        gdk-pixbuf
        glib
        gtk3
        icu
        wayland
        libGL
        libGLU
        glfw
        glew
        libappindicator-gtk3
        libdrm
        libglvnd
        libnotify
        libpulseaudio
        libunwind
        libusb1
        libuuid
        libxkbcommon
        libxml2
        mesa
        nspr
        nss
        openssl
        pango
        pipewire
        stdenv.cc.cc
        systemd
        vulkan-loader
        xorg.libX11
        xorg.libXScrnSaver
        xorg.libXcomposite
        xorg.libXcursor
        xorg.libXdamage
        xorg.libXext
        xorg.libXfixes
        xorg.libXi
        xorg.libXrandr
        xorg.libXrender
        xorg.libXtst
        xorg.libxcb
        xorg.libxkbfile
        xorg.libxshmfence
        zlib
      ];
    };
```

**Comment by Scrumplex** [comment]
> nix-ld doesn't seem to be working for me.
> I'm developing Minecraft Mods with IntelliJ and OpenAL outputs it can't find, pulse, alsa or jack!

Isn't IntelliJ running in a fhsenv? It wouldn't use your host (nix-ld) ld-linux.so in that case

**Comment by jasper-clarke** [comment]
@Scrumplex 
Thanks for getting back to me.
What solves it for me is specifying the path to OpenAL as a JVM argument to IntelliJ when it launches Minecraft.

If I could ask another question since you seem to know more about NixOS then me, I have that massive Nix-ld library list in my config but for some reason when I am developing any say a Golang program it never finds the X11 libraries unless I create a flake.nix shell in the directory of the project I am working with, why is that?

**Comment by Scrumplex** [comment]
I'd recommend you create shells for each of your projects, or alternatively create shells for each kind of project. The big advantage of Nix is that you don't need to have all your development dependencies installed globally. Many people create a Nix Flake in every project that is tailored to the specific use case. That way, you have a portable and reproducible development environment.

You can also integrate these devShells into your usual shell/IDE using https://github.com/nix-community/nix-direnv.

**Comment by donottellmetonottellyou** [comment]
Hi, I also have a similar issue, however, I am running Lost Era, a 1.7.10 mod pack. I'm not using any fancy flakes or anything, just a regular addition to my home-manager packages. 24.11 branch.

What I noticed, is that it works the first time. Then I quit and leave my PC, and come back later. I will launch Minecraft again, and my audio will crash on my whole desktop, and restart. I am using KDE, and all my audio outputs disappear except for the dummy output. Sometimes the outputs come back, but no sound is audible even when I restart the plasma environment. The only thing that fixes it is rebooting, after which sound works normally.

Can anyone else confirm their audio is working after a clean reboot, at least on 1.7.10?

This may be Minecraft version specific, since newer versions of Minecraft handle native libraries differently. @Scrumplex [I found this](https://github.com/PrismLauncher/PrismLauncher/issues/513),  is it possibly related?

I am not really using the system openal for anything so it's fine for me to disable it, but crashing the entire audio system seems a bit unintended lol.

Sorry if this turns out to be unrelated

**Comment by jacks0n9** [comment]
in my case, this issue only applies past minecraft version 1.20.1. after that version, they updated lwjgl from 3.3.1 to 3.3.2 in which it always fails to initialize the default audio device. also in this lwjgl update they updated openal: https://github.com/LWJGL/lwjgl3/blob/master/doc/notes/3.3.2.md. it's bizarre because it does this even after i install pulse with nix-ld and in my minimal test program, the only way i could get this to work was to set LD_LIBRARY_PATH=$NIX_LD_LIBRARY_PATH when running java.
the aoss wrapper program method does not work for me and the audio continues to not work
