### ISSUE TITLE
blueman fails to execute ps

### ISSUE THREAD

**Issue by erdnaxe** [NixOS/nixpkgs#206676]
### Describe the bug

Blueman is unable to connect to serial ports as it fails to execute the `ps` command.

### Steps To Reproduce
1. Open Bluetooth Manager (blueman-manager)
2. Right click on a device that support serial port
3. Choose "Connect To > Serial Port"

Blueman warns that the connection failed with the following error message:
```
Connection Failed: File "/nix/store/nfdjp8l8ifl0amz8sh620jsxy67y5bk5-blueman-2.3.4/lib/python3.10/site-packages/blueman/main/DbusService.py", line 154, in _handle_method_call
    method(*(args + (ok, lambda exception: self._return_dbus_error(invocation, exception))))
  File "/nix/store/nfdjp8l8ifl0amz8sh620jsxy67y5bk5-blueman-2.3.4/lib/python3.10/site-packages/blueman/plugins/applet/DBusService.py", line 87, in connect_service
    service.connect(reply_handler=lambda port: ok(), error_handler=err)
  File "/nix/store/nfdjp8l8ifl0amz8sh620jsxy67y5bk5-blueman-2.3.4/lib/python3.10/site-packages/blueman/services/meta/SerialService.py", line 96, in connect
    self.try_replace_root_watcher(mon, filename, port_id)
  File "/nix/store/nfdjp8l8ifl0amz8sh620jsxy67y5bk5-blueman-2.3.4/lib/python3.10/site-packages/blueman/services/meta/SerialService.py", line 63, in try_replace_root_watcher
    Mechanism().CloseRFCOMM('(d)', port)
  File "/nix/store/r2dz7qsrk6ziiqw2krrcixfk0wgx8qsx-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/overrides/Gio.py", line 349, in __call__
    result = self.dbus_proxy.call_sync(self.method_name, arg_variant,
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Failed: Traceback (most recent call last):
  File "/nix/store/nfdjp8l8ifl0amz8sh620jsxy67y5bk5-blueman-2.3.4/lib/python3.10/site-packages/blueman/main/DbusService.py", line 156, in _handle_method_call
    ok(method(*args))
  File "/nix/store/nfdjp8l8ifl0amz8sh620jsxy67y5bk5-blueman-2.3.4/lib/python3.10/site-packages/blueman/plugins/mechanism/Rfcomm.py", line 19, in _close_rfcomm
    out, err = subprocess.Popen(['ps', '-e', 'o', 'pid,args'], stdout=subprocess.PIPE).communicate()
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ps'
```

### Expected behavior

Blueman should not fail to connect to the serial port.

### Notify maintainers

@abbradar 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.80, NixOS, 22.11 (Raccoon), 22.11.740.7a6a010c3a1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - channels(erdnaxe): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by bjornfor** [comment]
I can't even reproduce as the blueman-manager UI is empty and the menus don't expand to anything when clicked. In the terminal I see this:

```
$ git checkout nixpkgs-unstable && nix-build -A blueman && ./result/bin/blueman-manager 
Already on 'nixpkgs-unstable'
Your branch is up to date with 'origin/nixpkgs-unstable'.
/nix/store/wm1da52hi10mh75d53m750bzjzwkvxvn-blueman-2.3.4
Traceback (most recent call last):
  File "/nix/store/wm1da52hi10mh75d53m750bzjzwkvxvn-blueman-2.3.4/lib/python3.10/site-packages/blueman/main/Manager.py", line 140, in on_dbus_name_appeared
    check_bluetooth_status(_("Bluetooth needs to be turned on for the device manager to function"),
  File "/nix/store/wm1da52hi10mh75d53m750bzjzwkvxvn-blueman-2.3.4/lib/python3.10/site-packages/blueman/Functions.py", line 65, in check_bluetooth_status
    if "PowerManager" not in applet.QueryPlugins():
  File "/nix/store/1psjx5nf2gglgd59cjrnqkqpxyy5qy9p-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/overrides/Gio.py", line 349, in __call__
    result = self.dbus_proxy.call_sync(self.method_name, arg_variant,
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.blueman.Applet was not provided by any .service files (2)
```

**Comment by cnf** [comment]
As a note for people having this issue, and @erdnaxe if you still need it, I solve this with:

```nix
let
    blueman-patched = pkgs.blueman.overrideAttrs (finalAttrs: previousAttrs: {
        buildInputs = previousAttrs.buildInputs ++ [pkgs.procps];
      });
in
```

So really, the blueman pkg just need propc added to the buildInputs

**Comment by bjornfor** [comment]
@cnf: Create PR?

**Comment by cnf** [comment]
I figured it's a small change, I might as well just create a PR, I can always create new PRs for the other stuff
