### ISSUE TITLE
Mountable folders from GNOME online accounts disappear and must be disabled and enabled to appear again

### ISSUE THREAD

**Issue by tfc** [NixOS/nixpkgs#206970]
### Describe the bug

I have two google accounts in my gnome "online accounts" dialog in the GNOME settings configured.
The "Files" setting is activated for them.

Typically, the "Files" application then shows me the folders in its sidebar like this:

![Screenshot from 2022-12-20 07-40-05-](https://user-images.githubusercontent.com/29044/208600857-419b636b-89a9-4576-9465-01743e704cdf.png)

When i suspend&wakeup my laptop or reboot it, the remote folders disappear from the sidebar:

![Screenshot from 2022-12-20 07-39-34](https://user-images.githubusercontent.com/29044/208600929-30a9e8a7-1948-46ab-ae10-054d22ade4e8.png)

In order to fix it, i need to *disable* one account in the "online accounts" dialog, which then *freezes*. After restarting the GNOME settings app and entering "online accounts" again, i can enable the account again.
After doing this with only one of both google accounts, *both* of them appear in the file application's sidebar again. 

### Steps To Reproduce
1. Configure at least one Google account, i guess, and activate "files" access
2. Check that the "Files" app shows the folder in the left sidebar
3. reboot the laptop
4. Observe that the item disappeared from the sidebar.
5. Disable & enable the "files" access from this account. The GNOME Settings app will freeze while doing that.
6. "Files" app sidebar icon is back again.

### Expected behavior

The files access to this account in the "Files" app should never disappear.
The GNOME Settings "Online Accounts" dialog should never freeze when unchecking settings of a google account 

### Screenshots

-already embedded in the text-

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.83, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager-21.11.tar.gz, nixos-21.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by m911t** [comment]
@jtojnar is probably the right person to ping as maintainer

**Comment by jtojnar** [comment]
It appears that goa-daemon crashes on resume:

```
Dec 20 21:23:29 theo org.gnome.OnlineAccounts[543942]: Rest:ERROR:../rest/rest-proxy-call.c:628:finish_call: assertion failed: (payload)
Dec 20 21:23:29 theo org.gnome.OnlineAccounts[543942]: Bail out! Rest:ERROR:../rest/rest-proxy-call.c:628:finish_call: assertion failed: (payload)
```

Likely will be fixed by https://gitlab.gnome.org/GNOME/librest/-/merge_requests/28.

I can reproduce the Control Center “freeze” upon toggling any of the `GtkSwitch`es. It is not really freezing but opening another instance of the dialogue making the original one remaining on the top inaccessible. You can move it by holding the <kbd>Super</kbd> key and dragging the dialogue, and then continue to interact with the newly opened on the bottom.

I would guess the dialog is opened because of this:

https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/4ddfecc79d1e5711f976ed706b79fb8f7eaee610/panels/online-accounts/cc-online-accounts-panel.c#L658

**Comment by jtojnar** [comment]
```gdb
(gdb) bt
#0  show_account (object=0x7fc95000d420, self=0x22db070) at ../panels/online-accounts/cc-online-accounts-panel.c:317
#1  on_account_changed_cb (client=0x7fc97008b470, object=0x7fc95000d420, self=0x22db070) at ../panels/online-accounts/cc-online-accounts-panel.c:658
#2  0x00007fc99406f5af in g_closure_invoke (closure=0x24e12d0, return_value=return_value@entry=0x0, n_param_values=2, param_values=param_values@entry=0x7fff1fc48da0, 
    invocation_hint=invocation_hint@entry=0x7fff1fc48d20) at ../gobject/gclosure.c:832
#3  0x00007fc994082917 in signal_emit_unlocked_R (node=node@entry=0x24ef050, detail=detail@entry=0, instance=instance@entry=0x7fc97008b470, emission_return=emission_return@entry=0x0, 
    instance_and_params=instance_and_params@entry=0x7fff1fc48da0) at ../gobject/gsignal.c:3796
#4  0x00007fc9940896ba in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fff1fc48f40) at ../gobject/gsignal.c:3549
#5  0x00007fc99408994f in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3606
#6  0x00007fc9941428a4 in _g_cclosure_marshal_VOID__OBJECT_OBJECT_VARIANT_BOXEDv (closure=closure@entry=0x24e1190, return_value=return_value@entry=0x0, instance=instance@entry=0x3505190, 
    args=args@entry=0x7fff1fc49290, marshal_data=marshal_data@entry=0x0, n_params=n_params@entry=4, param_types=0x23f5b60) at ../gio/gmarshal-internal.c:1605
#7  0x00007fc99406f7d9 in _g_closure_invoke_va (closure=closure@entry=0x24e1190, return_value=return_value@entry=0x0, instance=instance@entry=0x3505190, args=args@entry=0x7fff1fc49290, n_params=4, 
    param_types=0x23f5b60) at ../gobject/gclosure.c:895
#8  0x00007fc99408964d in g_signal_emit_valist (instance=0x3505190, signal_id=237, detail=<optimized out>, var_args=var_args@entry=0x7fff1fc49290) at ../gobject/gsignal.c:3456
#9  0x00007fc99408994f in g_signal_emit (instance=instance@entry=0x3505190, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3606
#10 0x00007fc9941e5ca9 in signal_cb (connection=<optimized out>, sender_name=<optimized out>, object_path=<optimized out>, interface_name=<optimized out>, signal_name=<optimized out>, 
    parameters=<optimized out>, user_data=0x3505190) at ../gio/gdbusobjectmanagerclient.c:1090
#11 0x00007fc9941c380b in emit_signal_instance_in_idle_cb (data=0x7fc97008b060) at ../gio/gdbusconnection.c:3791
#12 0x00007fc993f738e4 in g_main_dispatch (context=0x1fa8a20) at ../glib/gmain.c:3444
#13 g_main_context_dispatch (context=context@entry=0x1fa8a20) at ../glib/gmain.c:4162
#14 0x00007fc993f73c88 in g_main_context_iterate (context=context@entry=0x1fa8a20, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4238
#15 0x00007fc993f73d3f in g_main_context_iteration (context=context@entry=0x1fa8a20, may_block=may_block@entry=1) at ../glib/gmain.c:4303
#16 0x00007fc99419e19d in g_application_run (application=0x1f7d110, argc=argc@entry=1, argv=argv@entry=0x7fff1fc49738) at ../gio/gapplication.c:2571
#17 0x000000000045cd64 in main (argc=1, argv=0x7fff1fc49738) at ../shell/main.c:60

(gdb) bt full
#0  show_account (object=0x7fc95000d420, self=0x22db070) at ../panels/online-accounts/cc-online-accounts-panel.c:317
        account = <optimized out>
#1  on_account_changed_cb (client=0x7fc97008b470, object=0x7fc95000d420, self=0x22db070) at ../panels/online-accounts/cc-online-accounts-panel.c:658
No locals.
#2  0x00007fc99406f5af in g_closure_invoke (closure=0x24e12d0, return_value=return_value@entry=0x0, n_param_values=2, param_values=param_values@entry=0x7fff1fc48da0, 
    invocation_hint=invocation_hint@entry=0x7fff1fc48d20) at ../gobject/gclosure.c:832
        marshal = 0x7fc9940727f0 <g_cclosure_marshal_VOID__OBJECT>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x24e12b0
        __func__ = "g_closure_invoke"
#3  0x00007fc994082917 in signal_emit_unlocked_R (node=node@entry=0x24ef050, detail=detail@entry=0, instance=instance@entry=0x7fc97008b470, emission_return=emission_return@entry=0x0, 
    instance_and_params=instance_and_params@entry=0x7fff1fc48da0) at ../gobject/gsignal.c:3796
        tmp = <optimized out>
        handler = 0x25d24c0
        accumulator = 0x0
        emission = {next = 0x7fff1fc49190, instance = 0x7fc97008b470, ihint = {signal_id = 243, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, 
          chain_type = 4}
        class_closure = 0x0
        hlist = <optimized out>
        handler_list = 0x25d24c0
        return_accu = 0x0
        accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, 
              v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 243
        max_sequential_handler_number = 4083
        return_value_altered = 0
        EMIT_RESTART = <optimized out>
#4  0x00007fc9940896ba in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fff1fc48f40) at ../gobject/gsignal.c:3549
        instance_and_params = 0x7fff1fc48da0
        signal_return_type = <optimized out>
        param_values = 0x7fff1fc48db8
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#5  0x00007fc99408994f in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3606
        var_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fff1fc49020, reg_save_area = 0x7fff1fc48f60}}
#6  0x00007fc9941428a4 in _g_cclosure_marshal_VOID__OBJECT_OBJECT_VARIANT_BOXEDv (closure=closure@entry=0x24e1190, return_value=return_value@entry=0x0, instance=instance@entry=0x3505190, 
    args=args@entry=0x7fff1fc49290, marshal_data=marshal_data@entry=0x0, n_params=n_params@entry=4, param_types=0x23f5b60) at ../gio/gmarshal-internal.c:1605
        cc = <optimized out>
        data1 = <optimized out>
        data2 = <optimized out>
        callback = 0x7fc992de55f0 <on_interface_proxy_properties_changed>
        arg0 = 0x7fc95000d420
        arg1 = 0x24f1080
        arg2 = 0x7fc97005c580
        arg3 = 0x7fc97004a630
        args_copy = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fff1fc49378, reg_save_area = 0x7fff1fc492b0}}
#7  0x00007fc99406f7d9 in _g_closure_invoke_va (closure=closure@entry=0x24e1190, return_value=return_value@entry=0x0, instance=instance@entry=0x3505190, args=args@entry=0x7fff1fc49290, n_params=4, 
    param_types=0x23f5b60) at ../gobject/gclosure.c:895
        marshal = 0x7fc994142740 <_g_cclosure_marshal_VOID__OBJECT_OBJECT_VARIANT_BOXEDv>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x24e1170
        __func__ = "_g_closure_invoke_va"
#8  0x00007fc99408964d in g_signal_emit_valist (instance=0x3505190, signal_id=237, detail=<optimized out>, var_args=var_args@entry=0x7fff1fc49290) at ../gobject/gsignal.c:3456
        return_accu = <optimized out>
        accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, 
              v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x0
        emission = {next = 0x0, instance = 0x3505190, ihint = {signal_id = 237, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = 38743824}
        instance_type = <optimized out>
        emission_return = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, 
              v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        hlist = <optimized out>
        l = <optimized out>
        fastpath = 1
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#9  0x00007fc99408994f in g_signal_emit (instance=instance@entry=0x3505190, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3606
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fff1fc49370, reg_save_area = 0x7fff1fc492b0}}
#10 0x00007fc9941e5ca9 in signal_cb (connection=<optimized out>, sender_name=<optimized out>, object_path=<optimized out>, interface_name=<optimized out>, signal_name=<optimized out>, 
    parameters=<optimized out>, user_data=0x3505190) at ../gio/gdbusobjectmanagerclient.c:1090
        property_iter = {x = {140503144580480, 1, 1, 0, 37216016, 1, 0, 3579507750, 140733726788170, 2072753768733532672, 37216016, 37420688, 140733726364752, 140733726364744, 37420688, 140733726364864}}
        property_name = 0x7fc9700910e8 "PhotosDisabled"
        property_value = 0x7fc97007d550
        n = <optimized out>
        properties_interface_name = 0x7fc9700910c0 "org.gnome.OnlineAccounts.Account"
        changed_properties = 0x7fc97005c580
        invalidated_properties = 0x25c93b0
        manager = 0x3505190
        object_proxy = 0x7fc95000d420
        interface = 0x24f1080
        out = <optimized out>
#11 0x00007fc9941c380b in emit_signal_instance_in_idle_cb (data=0x7fc97008b060) at ../gio/gdbusconnection.c:3791
        signal_instance = 0x7fc97008b060
        parameters = 0x7fc97008caa0
        has_subscription = 1
#12 0x00007fc993f738e4 in g_main_dispatch (context=0x1fa8a20) at ../glib/gmain.c:3444
        dispatch = 0x7fc993f6f950 <g_idle_dispatch>
        prev_source = 0x0
        begin_time_nsec = 0
        was_in_call = 0
        user_data = 0x7fc97008b060
        callback = 0x7fc9941c3790 <emit_signal_instance_in_idle_cb>
        cb_funcs = <optimized out>
        cb_data = <optimized out>
        need_destroy = <optimized out>
        source = 0x7fc97008ba00
        current = 0x1fbd120
        i = 0
        __func__ = "g_main_dispatch"
#13 g_main_context_dispatch (context=context@entry=0x1fa8a20) at ../glib/gmain.c:4162
No locals.
#14 0x00007fc993f73c88 in g_main_context_iterate (context=context@entry=0x1fa8a20, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4238
        max_priority = 2147483647
        timeout = -1
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = <optimized out>
        fds = 0x24e2c50
        begin_time_nsec = 0
#15 0x00007fc993f73d3f in g_main_context_iteration (context=context@entry=0x1fa8a20, may_block=may_block@entry=1) at ../glib/gmain.c:4303
        retval = <optimized out>
#16 0x00007fc99419e19d in g_application_run (application=0x1f7d110, argc=argc@entry=1, argv=argv@entry=0x7fff1fc49738) at ../gio/gapplication.c:2571
        arguments = 0x1fa79c0
        status = 0
        context = 0x1fa8a20
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#17 0x000000000045cd64 in main (argc=1, argv=0x7fff1fc49738) at ../shell/main.c:60
        application = 0x1f7d110
```
