### ISSUE TITLE
python3Packages.zope_schema fails to build on current master

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#20791]
## Issue description
Test fails
```
patching script interpreter paths in /nix/store/kklkplv7scdbxiflf92ddani5x2dsh6f-python3.5-zope.schema-4.4.2
running install tests
running test
running egg_info
writing src/zope.schema.egg-info/PKG-INFO
writing namespace_packages to src/zope.schema.egg-info/namespace_packages.txt
writing top-level names to src/zope.schema.egg-info/top_level.txt
writing requirements to src/zope.schema.egg-info/requires.txt
writing dependency_links to src/zope.schema.egg-info/dependency_links.txt
reading manifest file 'src/zope.schema.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
writing manifest file 'src/zope.schema.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "nix_run_setup.py", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 121, in <module>
    'testing': TESTS_REQUIRE + ['nose', 'coverage'],
  File "/nix/store/a5pfc3665h6h2nfshqgphk4wc1rywcxy-python3-3.5.2/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/a5pfc3665h6h2nfshqgphk4wc1rywcxy-python3-3.5.2/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nix/store/a5pfc3665h6h2nfshqgphk4wc1rywcxy-python3-3.5.2/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/jqlizmc0nib54474mk40vlfs51p184vp-python3.5-bootstrapped-pip-9.0.1/lib/python3.5/site-packages/setuptools/command/test.py", line 210, in run
    self.run_tests()
  File "/nix/store/jqlizmc0nib54474mk40vlfs51p184vp-python3.5-bootstrapped-pip-9.0.1/lib/python3.5/site-packages/setuptools/command/test.py", line 231, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/nix/store/a5pfc3665h6h2nfshqgphk4wc1rywcxy-python3-3.5.2/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/nix/store/a5pfc3665h6h2nfshqgphk4wc1rywcxy-python3-3.5.2/lib/python3.5/unittest/main.py", line 140, in parseArgs
    self.createTests()
  File "/nix/store/a5pfc3665h6h2nfshqgphk4wc1rywcxy-python3-3.5.2/lib/python3.5/unittest/main.py", line 147, in createTests
    self.module)
  File "/nix/store/a5pfc3665h6h2nfshqgphk4wc1rywcxy-python3-3.5.2/lib/python3.5/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/nix/store/a5pfc3665h6h2nfshqgphk4wc1rywcxy-python3-3.5.2/lib/python3.5/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/nix/store/a5pfc3665h6h2nfshqgphk4wc1rywcxy-python3-3.5.2/lib/python3.5/unittest/loader.py", line 204, in loadTestsFromName
    test = obj()
  File "setup.py", line 59, in alltests
    {}, {}, ['*'])
  File "/tmp/nix-build-python3.5-zope.schema-4.4.2.drv-0/zope.schema-4.4.2/src/zope/schema/__init__.py", line 17, in <module>
    from zope.schema._field import ASCII
  File "/tmp/nix-build-python3.5-zope.schema-4.4.2.drv-0/zope.schema-4.4.2/src/zope/schema/_field.py", line 26, in <module>
    from zope.event import notify
ImportError: No module named 'zope.event'
builder for ‘/nix/store/xwvj6xjr094xzj3z7b69d0ynvn7296s9-python3.5-zope.schema-4.4.2.drv’ failed with exit code 1
error: build of ‘/nix/store/xwvj6xjr094xzj3z7b69d0ynvn7296s9-python3.5-zope.schema-4.4.2.drv’ failed

```

### Steps to reproduce
```nix-build  '<nixpkgs>' --option build-use-chroot true -A python3Packages.zope_schema```

After a quick git bisect the issue appears with the following commit: https://github.com/NixOS/nixpkgs/commit/d83d2ba4f3b831ded72c7b29a2ddb9b7a528efca ( @FRidh )

## Technical details

* System: 17.03.git.755fadd (Gorilla)
* Nix version: nix-env (Nix) 1.11.2

**Comment by FRidh** [comment]
cc maintainer @cillianderoiste 
The module actually works, it just can't find the tests during the `checkPhase`.
This is likely an issue for upstream, either setuptools, or zope.schema.

**Comment by FRidh** [comment]
I've disabled the tests for now in https://github.com/NixOS/nixpkgs/commit/7d44426ccd2cbef148fd4afada6568b04b952bf0.

**Comment by FRidh** [comment]
zope_configuration fails as well now. It seems to be a namespace package.

**Comment by FRidh** [comment]
It is a setuptools issue as can be read in https://github.com/pypa/setuptools/issues/870. The issue hasn't been properly fixed yet.

**Comment by matthewbauer** [comment]
Zope is fixed in current nixpkgs-unstable.
