### ISSUE TITLE
[NixOS]: Can't boot after Switching from KDE to xfce

### ISSUE THREAD

**Issue by ERAGON007** [NixOS/nixpkgs#208075]
### Steps To Reproduce
1. Install a clean build of NixOS using the Calamares, it installs NixOS with KDE desktop
2. Boot into your newly installed build
3. Change your desktop manager to xfce, and `nixos-rebuild switch`
4. reboot your system, and boom it's gone. it logs into `tty1` for me, i can't even log into the `root` account!

### Build log
```
[nixos@nixos:/run/media/nixos/NixOS_Root/@/etc/nixos]$ sudo nixos-install --root /run/media/nixos/NixOS_Root/@
copying channel...
building the configuration in /run/media/nixos/NixOS_Root/@/etc/nixos/configuration.nix...
/nix/store/mbbcvl0z7s19p8pbgbnh8872j27v2c42-nixos-system-unnamed-22.11.1008.0938d73bb14
installing the boot loader...
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /nix/store/snb4523ghvw9917q15j401fz26d5plh3-update-users-groups.pl line 10.
Activation script snippet 'users' failed (255)
setting up /etc...
chown: invalid user: ‘root:root’
Activation script snippet 'var' failed (1)
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:messagebus’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
chown: invalid user: ‘root:root’
Activation script snippet 'wrappers' failed (1)
/etc/tmpfiles.d/systemd.conf:22: Failed to resolve group 'systemd-journal'.
/etc/tmpfiles.d/systemd.conf:23: Failed to resolve group 'systemd-journal'.
Failed to parse ACL "d:group::r-x,d:group:adm:r-x,d:group:wheel:r-x,group::r-x,group:adm:r-x,group:wheel:r-x": Invalid argument. Ignoring
Failed to parse ACL "d:group:adm:r-x,d:group:wheel:r-x,group:adm:r-x,group:wheel:r-x": Invalid argument. Ignoring
Failed to parse ACL "group:adm:r--,group:wheel:r--": Invalid argument. Ignoring
/etc/tmpfiles.d/systemd.conf:28: Failed to resolve group 'systemd-journal'.
/etc/tmpfiles.d/systemd.conf:29: Failed to resolve group 'systemd-journal'.
/etc/tmpfiles.d/systemd.conf:30: Failed to resolve group 'systemd-journal'.
Failed to parse ACL "d:group::r-x,d:group:adm:r-x,d:group:wheel:r-x,group::r-x,group:adm:r-x,group:wheel:r-x": Invalid argument. Ignoring
Failed to parse ACL "d:group:adm:r-x,d:group:wheel:r-x,group:adm:r-x,group:wheel:r-x": Invalid argument. Ignoring
Failed to parse ACL "group:adm:r--,group:wheel:r--": Invalid argument. Ignoring
/etc/tmpfiles.d/var.conf:15: Failed to resolve group 'utmp'.
/etc/tmpfiles.d/var.conf:16: Failed to resolve group 'utmp'.
/etc/tmpfiles.d/var.conf:17: Failed to resolve group 'utmp'.
File system "/boot/efi" is not a FAT EFI System Partition (ESP) file system.
Traceback (most recent call last):
  File "/nix/store/jksq5yphz84zajzlgmf0pg65ndfl95g3-systemd-boot", line 315, in <module>
    main()
  File "/nix/store/jksq5yphz84zajzlgmf0pg65ndfl95g3-systemd-boot", line 243, in main
    subprocess.check_call(["/nix/store/3lnnsz95cvijw5mb5s074h8jk8ld51r2-systemd-251.7/bin/bootctl", "--esp-path=/boot/efi"] + flags + ["install"])
  File "/nix/store/lbn7f0d2k36i4bgfdrjdwj7npy3r3h5d-python3-3.10.8/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/3lnnsz95cvijw5mb5s074h8jk8ld51r2-systemd-251.7/bin/bootctl', '--esp-path=/boot/efi', 'install']' returned non-zero exit status 1.
```

### Additional context
I've tried using a live usb stick to get it working, but when i'm trying to build it i got the above error

My configuration.nix: https://gist.github.com/ERAGON007/e16defdb5051a6a6178f1f6a1db63e62

### Notify maintainers

@romildo

### Metadata
I'VE RUN THIS COMMAND IN LIVE USB STICK

```console
[nixos@nixos:/run/media/nixos/NixOS_Root/@/etc]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.83, NixOS, 22.11 (Raccoon), 22.11.1008.0938d73bb14`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.11.1008.0938d73bb14"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by ERAGON007** [comment]
I've re-installed the NixOS by removing the old root partition and building a clean nixos and then got my old configuration and my packages.

but the problem couldn't be solved without forcing me to re-install the whole NixOS

it seems that the problem was with some writing operations. because before running the actual `nixos-rebuild switch`, i've run a `nixos-rebuild test` to see if it's working and cancelled it in middle of the process.

so i think someone has to prevent file corruption happenning to users related stuff when users cancels `nixos-rebuild` commands.
