### ISSUE TITLE
Newly released unstable small breaks stable nixops

### ISSUE THREAD

**Issue by greaka** [NixOS/nixpkgs#208123]
### Steps To Reproduce
1. build `nixos-unstable-small release nixos-23.05pre438170.57dbff4228a`

### Build log
```console
greaka@greaka-arch-desktop ~ % nixops deploy
/nix/store/av5h6kal9lbvpvhvdbj23qqvczaijpf7-python2.7-apache-libcloud-2.8.3/lib/python2.7/site-packages/libcloud/common/google.py:93: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the
next release.
  from cryptography.hazmat.backends import default_backend
trace: warning: The extraArgs argument to eval-config.nix is deprecated. Please set config._module.args instead.
building all machine configurations...
trace: warning: The extraArgs argument to eval-config.nix is deprecated. Please set config._module.args instead.
error: undefined variable 'loaOf' at /nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/share/nix/nixops/gce.nix:405:26
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
    f()
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1003, in _deploy
    self.configs_path = self.build_configs(dry_run=dry_run, repair=repair, include=include, exclude=exclude)
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 671, in build_configs
    raise Exception("unable to build all machine configurations")
Exception: unable to build all machine configurations
1 greaka@greaka-arch-desktop ~ %                                                                                                                   :(
```

### Additional context
I updated nixpkgs and now nixops does not work anymore. I don't even use gce, so I'm baffled why it's failing. `nixos-23.05pre437680.aac1f0b25e6` was still working. In both cases I used the same nixops version 1.7. My config did not change and can be found at https://github.com/greaka/ops

### Metadata

```console
greaka@greaka-arch-desktop /git/ops (git)-[master] % nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.12-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixpkgs-23.05pre438170.57dbff4228a"`
 - channels(greaka): `"nixpkgs-23.05pre438170.57dbff4228a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by winterqt** [comment]
In the future, please ping the maintainers as instructed in the template.

cc @AmineChikhaoui @edolstra @rbvermaa

**Comment by greaka** [comment]
Thanks for doing that, I didn't know who to ping

**Comment by Artturin** [comment]
loaOf was removed in https://github.com/nixos/nixpkgs/commit/c8c538f2ab2432f2dd1eb637657c1bf5b54a147f after many years of being deprecated

nixops at 1.7 still had loaOf being used as it was released(2019) before the type was deprecated https://github.com/NixOS/nixops/blob/v1.7/nix/gce.nix#L405

also cc @roberth

**Comment by greaka** [comment]
I've switched to morph in the meantime. I keep this issue open for if someone wants to fix it.

**Comment by roberth** [comment]
Not everyone may be able to switch away easily. Simple nixops deployment without cloud resources and static hosts may be easy, but that's not all deployments. Reverting in #208171
