### ISSUE TITLE
Cinnamon crashes when trying to restart from panel

### ISSUE THREAD

**Issue by bobby285271** [NixOS/nixpkgs#208122]
### Describe the bug

Restart cinnamon from the panel freezes the desktop, from the journal you will find cinnamon crashes.

### Steps To Reproduce

1. Right click the panel
2. Click trouble shooting
3. Restart cinnamon

### Expected behavior

No crash.

### Additional context

```gdb
#0  0x00007f57010062ea in clutter_actor_destroy (self=0xb76b40) at ../clutter/clutter/clutter-actor.c:8927
        __inst = 0xb76b40
        __t = 10529936
        __r = <optimized out>
        _g_boolean_var_ = <optimized out>
        __func__ = "clutter_actor_destroy"
#1  0x00007f5700d66c29 in meta_compositor_dispose (object=0x7124f0) at ../src/compositor/compositor.c:1386
        _pp = 0x7124a8
        _ptr = <optimized out>
        compositor = <optimized out>
        priv = 0x712450
#2  0x00007f57012560c9 in g_object_run_dispose (object=0x7124f0) at ../gobject/gobject.c:1448
        __func__ = "g_object_run_dispose"
#3  0x00007f5700d66f06 in meta_compositor_destroy (compositor=0x7124f0) at ../src/compositor/compositor.c:194
No locals.
#4  0x00007f5700d85a66 in meta_display_close (display=0xb32030, timestamp=0) at ../src/core/display.c:1139
        _pp = 0xb32230
        _ptr = <optimized out>
        __func__ = "meta_display_close"
#5  0x00007f57014e2b33 in cinnamon_global_real_restart (global=0xa6c0c0) at ../src/cinnamon-global.c:1213
        arr = 0x33ad5a0
        len = 46
        buf = 0x22cd200 "/run/current-system/sw/bin/cinnamon"
        buf_p = <optimized out>
        buf_end = <optimized out>
        error = 0x0
#6  0x00007f56ff9208aa in ffi_call_unix64 () from /nix/store/2infxahfp9lj084xn3q9ib5ajks8447i-libffi-3.4.4/lib/libffi.so.8
No symbol table info available.
#7  0x00007f56ff91f8bb in ffi_call_int () from /nix/store/2infxahfp9lj084xn3q9ib5ajks8447i-libffi-3.4.4/lib/libffi.so.8
No symbol table info available.
#8  0x00007f56ff92033e in ffi_call () from /nix/store/2infxahfp9lj084xn3q9ib5ajks8447i-libffi-3.4.4/lib/libffi.so.8
No symbol table info available.
#9  0x00007f570095a8e7 in Gjs::Function::invoke(JSContext*, JS::CallArgs const&, JS::Handle<JSObject*>, _GIArgument*) [clone .localalias] () from /nix/store/04hw6nbz64jghq635kj84f475qdfzgxw-cjs-5.6.1/lib/libcjs.so.0
No symbol table info available.
#10 0x00007f570095afdf in Gjs::Function::call(JSContext*, unsigned int, JS::Value*) () from /nix/store/04hw6nbz64jghq635kj84f475qdfzgxw-cjs-5.6.1/lib/libcjs.so.0
No symbol table info available.
#11 0x00007f56fe72433e in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct, js::CallReason) () from /nix/store/z58m0vvnj1ndv7a5xdh3ci3dy5lmrfmw-spidermonkey-78.15.0/lib/libmozjs-78.so
No symbol table info available.
#12 0x00007f56fe7172b4 in Interpret(JSContext*, js::RunState&) () from /nix/store/z58m0vvnj1ndv7a5xdh3ci3dy5lmrfmw-spidermonkey-78.15.0/lib/libmozjs-78.so
No symbol table info available.
#13 0x00007f56fe723afe in js::RunScript(JSContext*, js::RunState&) () from /nix/store/z58m0vvnj1ndv7a5xdh3ci3dy5lmrfmw-spidermonkey-78.15.0/lib/libmozjs-78.so
No symbol table info available.
#14 0x00007f56fe723ef6 in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct, js::CallReason) () from /nix/store/z58m0vvnj1ndv7a5xdh3ci3dy5lmrfmw-spidermonkey-78.15.0/lib/libmozjs-78.so
No symbol table info available.
#15 0x00007f56fe724ff3 in js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>, js::CallReason) () from /nix/store/z58m0vvnj1ndv7a5xdh3ci3dy5lmrfmw-spidermonkey-78.15.0/lib/libmozjs-78.so
No symbol table info available.
#16 0x00007f56fe7c1e1a in JS_CallFunction(JSContext*, JS::Handle<JSObject*>, JS::Handle<JSFunction*>, JS::HandleValueArray const&, JS::MutableHandle<JS::Value>) () from /nix/store/z58m0vvnj1ndv7a5xdh3ci3dy5lmrfmw-spidermonkey-78.15.0/lib/libmozjs-78.so
No symbol table info available.
#17 0x00007f57009544ec in Gjs::Closure::invoke(JS::Handle<JSObject*>, JS::HandleValueArray const&, JS::MutableHandle<JS::Value>) () from /nix/store/04hw6nbz64jghq635kj84f475qdfzgxw-cjs-5.6.1/lib/libcjs.so.0
No symbol table info available.
#18 0x00007f5700981941 in Gjs::Closure::marshal(_GValue*, unsigned int, _GValue const*, void*, void*) () from /nix/store/04hw6nbz64jghq635kj84f475qdfzgxw-cjs-5.6.1/lib/libcjs.so.0
No symbol table info available.
#19 0x00007f570124f5af in g_closure_invoke (closure=0x1d07030, return_value=return_value@entry=0x7ffe88f489e0, n_param_values=1, param_values=param_values@entry=0x7ffe88f48a40, invocation_hint=invocation_hint@entry=0x7ffe88f489c0) at ../gobject/gclosure.c:832
        marshal = 0x7f57009494d0 <Gjs::Closure::marshal_cb(_GClosure*, _GValue*, unsigned int, _GValue const*, void*, void*)>
        marshal_data = 0x97
        in_marshal = 0
        real_closure = 0x1d07010
        __func__ = "g_closure_invoke"
#20 0x00007f5701262917 in signal_emit_unlocked_R (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0xb32030, emission_return=emission_return@entry=0x7ffe88f48b10, instance_and_params=instance_and_params@entry=0x7ffe88f48a40) at ../gobject/gsignal.c:3796
        tmp = <optimized out>
        handler = 0x1ffa480
        accumulator = 0xc39a20
        emission = {next = 0x0, instance = 0xb32030, ihint = {signal_id = 151, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = 4}
        class_closure = 0x0
        hlist = <optimized out>
        handler_list = 0x1ffa480
        return_accu = 0x7ffe88f489e0
        accu = {g_type = 20, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 151
        max_sequential_handler_number = 49086
        return_value_altered = 0
        EMIT_RESTART = <optimized out>
#21 0x00007f5701268eef in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffe88f48bc0) at ../gobject/gsignal.c:3559
        return_value = {g_type = 20, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        error = 0x0
        rtype = 20
        static_scope = 0
        instance_and_params = 0x7ffe88f48a40
        signal_return_type = <optimized out>
        param_values = 0x7ffe88f48a58
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#22 0x00007f570126994f in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3606
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ffe88f48ca0, reg_save_area = 0x7ffe88f48be0}}
#23 0x00007f5700d8603e in meta_display_request_restart (display=<optimized out>) at ../src/core/display.c:2938
        result = 0
#24 0x00007f5700d99905 in restart_check_ready () at ../src/core/restart.c:62
No locals.
#25 restart_check_ready () at ../src/core/restart.c:59
No locals.
#26 restart_message_painted (data=<optimized out>) at ../src/core/restart.c:94
No locals.
#27 0x00007f570104ebdc in _clutter_run_repaint_functions (flags=flags@entry=CLUTTER_REPAINT_FLAGS_POST_PAINT) at ../clutter/clutter/clutter-main.c:2468
        res = 0
        context = 0x801db0
        repaint_func = 0x229a960
        invoke_list = 0xde9b80
        reinvoke_list = 0x0
        l = 0x11b9460
#28 0x00007f57010507b7 in master_clock_update_stages (master_clock=<optimized out>, stages=0xf03610) at ../clutter/clutter/clutter-master-clock-default.c:390
        stages_updated = <optimized out>
        l = <optimized out>
        stages_updated = <optimized out>
        l = <optimized out>
#29 clutter_clock_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ../clutter/clutter/clutter-master-clock-default.c:517
        clock_source = <optimized out>
        master_clock = <optimized out>
        stages = 0xf03610
#30 0x00007f57011519db in g_main_dispatch (context=0x708d00) at ../glib/gmain.c:3444
        dispatch = 0x7f5701050610 <clutter_clock_dispatch>
        prev_source = 0x0
        begin_time_nsec = 0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = <optimized out>
        cb_data = <optimized out>
        need_destroy = <optimized out>
        source = 0xc2b920
        current = 0x784f90
        i = 0
        __func__ = "g_main_dispatch"
#31 g_main_context_dispatch (context=context@entry=0x708d00) at ../glib/gmain.c:4162
No locals.
#32 0x00007f5701151c88 in g_main_context_iterate (context=0x708d00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4238
        max_priority = 150
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = <optimized out>
        fds = 0xb97cd0
        begin_time_nsec = 0
#33 0x00007f5701151f73 in g_main_loop_run (loop=0xa4d250) at ../glib/gmain.c:4438
        self = <optimized out>
        __func__ = "g_main_loop_run"
#34 0x00007f5700d8fa9c in meta_run () at ../src/core/main.c:663
No locals.
#35 0x00000000004027e7 in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.c:388
        ctx = <optimized out>
        error = 0x0
        ecode = <optimized out>
        session_running = 1
```

**Comment by bobby285271** [comment]
Okay, I guess I need upstream help for this, going to forward this to upstream...
