### ISSUE TITLE
nixops 1.4 is broken

### ISSUE THREAD

**Issue by abuibrahim** [NixOS/nixpkgs#20823]
## Issue description

$ nixops --version
Traceback (most recent call last):
  File "/nix/store/ni55r1wq3wp907bii23wzxnji0myd296-nixops-1.4/bin/..nixops-wrapped-wrapped", line 5, in <module>
    from nixops import deployment
  File "/nix/store/ni55r1wq3wp907bii23wzxnji0myd296-nixops-1.4/lib/python2.7/site-packages/nixops/deployment.py", line 15, in <module>
    import nixops.statefile
  File "/nix/store/ni55r1wq3wp907bii23wzxnji0myd296-nixops-1.4/lib/python2.7/site-packages/nixops/statefile.py", line 6, in <module>
    import sqlite3
  File "/nix/store/rawxj3af8l2sbxv6kpclwx5f1gdxi631-python-2.7.12/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/nix/store/rawxj3af8l2sbxv6kpclwx5f1gdxi631-python-2.7.12/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

## Technical details

* System: (NixOS: 16.09.1149.e360c72 (Flounder))
* Nix version: (1.11.4)
* Nixpkgs version: (16.09.1149.e360c72)

**Comment by abuibrahim** [comment]
copy @domenkozar

**Comment by Mic92** [comment]
Looks like it cannot find python C extensions for sqlite3.

**Comment by nlewo** [comment]
It seems this pysqlite which is broken:
```
 nix-shell -I nixpkgs=`pwd` -p sqlite -p pythonPackages.pysqlite --command "python -c 'import sqlite3'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/rawxj3af8l2sbxv6kpclwx5f1gdxi631-python-2.7.12/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/nix/store/rawxj3af8l2sbxv6kpclwx5f1gdxi631-python-2.7.12/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
```

But pythonPackage.sqlite3 is ok. If you replace the pysqlite dep by sqlite3 in nixops expression, nixops works again. 
Sorry, I don't really know why pysqlite is borken...

**Comment by domenkozar** [comment]
Fixed

**Comment by abuibrahim** [comment]
Thanks!
