### ISSUE TITLE
graphiteWeb broke on NixOS-16.09

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixpkgs#20885]
After upgrading NixOS-16.09 from 33287d9 to 18ff275 my graphiteWeb service broke with the following messages in my journal:

```
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]: Could not import graphite.local_settings, using defaults!
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]: /nix/store/qvsx37660rq9m6qmyvrc5v9y8s2kz8mj-python-2.7.12-env/lib/python2.7/site-packages/opt/graphite/webapp/graphite/settings.py:246: UserWarning: SEC
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]: Traceback (most recent call last):
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/a5v1w92l6bwmj7scqwcjibjqibdqdmrf-python2.7-waitress-0.8.9/bin/.waitress-serve-wrapped", line 12, in <module>
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     sys.exit(run())
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/a5v1w92l6bwmj7scqwcjibjqibdqdmrf-python2.7-waitress-0.8.9/lib/python2.7/site-packages/waitress/runner.py", line 211, in run
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     app = app()
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/qvsx37660rq9m6qmyvrc5v9y8s2kz8mj-python-2.7.12-env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     self.load_middleware()
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/qvsx37660rq9m6qmyvrc5v9y8s2kz8mj-python-2.7.12-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 56, in load_middle
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     mw_class = import_string(middleware_path)
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/qvsx37660rq9m6qmyvrc5v9y8s2kz8mj-python-2.7.12-env/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_st
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     module = import_module(module_path)
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/f6pqagsjzvcl96jx36dxp8cnrril7syb-python-2.7.12/lib/python2.7/importlib/__init__.py", line 37, in import_module
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     __import__(name)
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/qvsx37660rq9m6qmyvrc5v9y8s2kz8mj-python-2.7.12-env/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 4, in <module
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     from django.contrib.auth.backends import RemoteUserBackend
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/qvsx37660rq9m6qmyvrc5v9y8s2kz8mj-python-2.7.12-env/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 4, in <module>
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     from django.contrib.auth.models import Permission
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/qvsx37660rq9m6qmyvrc5v9y8s2kz8mj-python-2.7.12-env/lib/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/qvsx37660rq9m6qmyvrc5v9y8s2kz8mj-python-2.7.12-env/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 52, in <module
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     class AbstractBaseUser(models.Model):
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/qvsx37660rq9m6qmyvrc5v9y8s2kz8mj-python-2.7.12-env/lib/python2.7/site-packages/django/db/models/base.py", line 105, in __new__
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     app_config = apps.get_containing_app_config(module)
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/qvsx37660rq9m6qmyvrc5v9y8s2kz8mj-python-2.7.12-env/lib/python2.7/site-packages/django/apps/registry.py", line 237, in get_containing_
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     self.check_apps_ready()
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:   File "/nix/store/qvsx37660rq9m6qmyvrc5v9y8s2kz8mj-python-2.7.12-env/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_read
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]:     raise AppRegistryNotReady("Apps aren't loaded yet.")
Dec 03 14:47:49 bas.van.dijk.lumi waitress-serve[25784]: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
Dec 03 14:47:49 bas.van.dijk.lumi dhcpcd[25771]: enp0s3: rebinding lease of 10.0.2.15
Dec 03 14:47:49 bas.van.dijk.lumi systemd[1]: graphiteWeb.service: Main process exited, code=exited, status=1/FAILURE
Dec 03 14:47:49 bas.van.dijk.lumi systemd[1]: graphiteWeb.service: Unit entered failed state.
Dec 03 14:47:49 bas.van.dijk.lumi systemd[1]: graphiteWeb.service: Failed with result 'exit-code'.
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] Unable to write to plugin cache /nix/store/8qjl9x6hrzif45cakimj2qsmy1kl9l79-python-2.7.12-env/lib/python2.7/site-packages/twisted/plugins/dropin
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] Unable to write to plugin cache /nix/store/8qjl9x6hrzif45cakimj2qsmy1kl9l79-python-2.7.12-env/lib/python2.7/site-packages/opt/graphite/lib/twist
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] Using sorted write strategy for cache
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] twistd 16.4.0 (/nix/store/f6pqagsjzvcl96jx36dxp8cnrril7syb-python-2.7.12/bin/python2.7 2.7.12) starting up.
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] reactor class: twisted.internet.epollreactor.EPollReactor.
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] ServerFactory starting on 2003
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x7fa2cf22d440>
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] ServerFactory starting on 2004
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x7fa2cf211dd0>
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] ServerFactory starting on 7002
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x7fa2cf211e18>
Dec 03 14:47:49 bas.van.dijk.lumi carbon-cache[25850]: [console] Installing SIG_IGN for SIGHUP
```

The only directly related patch in that range is: cab144faf59943092683dcf7850b50f71c10141e.

@cko any idea how to fix this?

**Comment by grahamc** [comment]
FWIW I think your hashes were reversed, here is the compare: https://github.com/NixOS/nixpkgs/compare/18ff275f171ac8d9048aca976a14ab13d55d3ed7...33287d9a8a334ba4113e7da02d6b97aba72785f7

**Comment by basvandijk** [comment]
@grahamc thanks for the compare.

Can anybody confirm the graphiteWeb failure that I'm seeing?
