### ISSUE TITLE
python3Packages.tensorflow: build failure with mklSupport = true

### ISSUE THREAD

**Issue by Minnozz** [NixOS/nixpkgs#209465]
### Steps To Reproduce
Tested both in `master` and `nixos-22.11`; log is from `master`:
```console
$ cd nixpkgs
$ git rev-parse HEAD
e6511f5503234a094d9901a20f5397324e4b36db
$ nix-build -E 'with import ./. {}; python3Packages.tensorflow.override { mklSupport = true; }'
```

### Build log
```
(...)
Analyzing: 2 targets (444 packages loaded, 9991 targets configured)
INFO: Repository llvm_openmp instantiated at:
  /build/source/WORKSPACE:15:14: in <toplevel>
  /build/source/tensorflow/workspace2.bzl:889:21: in workspace
  /build/source/tensorflow/workspace2.bzl:530:20: in _tf_repositories
  /build/source/third_party/repo.bzl:136:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /build/source/third_party/repo.bzl:89:35: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: storage.googleapis.com
WARNING: Download from https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: github.com
ERROR: An error occurred during the fetch of repository 'llvm_openmp':
   Traceback (most recent call last):
        File "/build/source/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz, https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz] to /build/output/external/llvm_openmp/temp591189578435327633/openmp-10.0.1.src.tar.xz: Unknown host: github.com
ERROR: /build/source/WORKSPACE:15:14: fetching _tf_http_archive rule //external:llvm_openmp: Traceback (most recent call last):
        File "/build/source/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz, https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz] to /build/output/external/llvm_openmp/temp591189578435327633/openmp-10.0.1.src.tar.xz: Unknown host: github.com
ERROR: /build/source/third_party/mkl/BUILD:77:11: //third_party/mkl:mkl_libs_linux depends on @llvm_openmp//:libiomp5.so in repository @llvm_openmp which failed to fetch. no such package '@llvm_openmp//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz, https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz] to /build/output/external/llvm_openmp/temp591189578435327633/openmp-10.0.1.src.tar.xz: Unknown host: github.com
ERROR: /build/source/third_party/mkl/BUILD:77:11: //third_party/mkl:mkl_libs_linux depends on @llvm_openmp//:config_omp in repository @llvm_openmp which failed to fetch. no such package '@llvm_openmp//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz, https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/openmp-10.0.1.src.tar.xz] to /build/output/external/llvm_openmp/temp591189578435327633/openmp-10.0.1.src.tar.xz: Unknown host: github.com
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: 
INFO: Elapsed time: 10.053s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (449 packages loaded, 10733 targets configured)
FAILED: Build did NOT complete successfully (449 packages loaded, 10733 targets configured)
```

### Notify maintainers
@jyp @abbradar

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.75, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(bart.schuurmans): `""`
 - nixpkgs: `/nix/store/ma8is0jvl1j69anc5aydg2y5qxa480ad-nixpkgs-src`
```

**Comment by Minnozz** [comment]
I'm working on updating #162763 to fix this.
