### ISSUE TITLE
beets: ImportError: "six"

### ISSUE THREAD

**Issue by kierdavis** [NixOS/nixpkgs#20946]
## Issue description

After updating to the latest version of the `nixos-unstable` channel, I found that `beets` crashes on startup with the following stacktrace:

```
Traceback (most recent call last):
  File "/nix/store/7jhnkwyidrgmarakhdp4mxx23mv7xp04-beets-1.4.1/bin/.beet-wrapped", line 8, in <module>
    from beets.ui import main
  File "/nix/store/7jhnkwyidrgmarakhdp4mxx23mv7xp04-beets-1.4.1/lib/python2.7/site-packages/beets/__init__.py", line 20, in <module>
    from beets.util import confit
  File "/nix/store/7jhnkwyidrgmarakhdp4mxx23mv7xp04-beets-1.4.1/lib/python2.7/site-packages/beets/util/__init__.py", line 31, in <module>
    import six
ImportError: No module named six
```

This issue also appears to be present on nixpkgs master branch.

### Steps to reproduce

```bash
git clone https://github.com/NixOS/nixpkgs.git
cd nixpkgs
nix-build -A beets
result/bin/beet
```

## Technical details

* System: NixOS 17.03pre96717.69bee1b (Gorilla)
* Nix version: 1.11.4
* Nixpkgs version: 17.03pre96799.571cf4f2

**Comment by kierdavis** [comment]
cc the maintainers @aszlig @domenkozar @pjones @Profpatsch

**Comment by FRidh** [comment]
Maybe related to the regression I caused (https://github.com/NixOS/nixpkgs/issues/20943). Testing now.

**Comment by FRidh** [comment]
Nope, six was simply missing. I'll push a fix.

**Comment by kierdavis** [comment]
Thanks, that fixed it.
