### ISSUE TITLE
service.gitlab doesn't install with grsecurity enabled

### ISSUE THREAD

**Issue by pingberlin** [NixOS/nixpkgs#20959]
## Issue description

When enabling both grsecurity and the gitlab service in "/etc/nixos/configuration.nix" "nixos-rebuild switch" will fail with:

```
/tmp/nix-build-gitlab-8.13.5.drv-0/gitlabhq-v8.13.5-src/Rakefile:5:in `<top (required)>'
U
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/ffi-1.9.10/lib/ffi/library.rb:263:in `attach'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/ffi-1.9.10/lib/ffi/library.rb:263:in `attach_function'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem/functions.rb:13:in `<module:Functions>'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem/functions.rb:5:in `<class:Filesystem>'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem/functions.rb:4:in `<module:Sys>'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem/functions.rb:3:in `<top (required)>'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem.rb:3:in `require_relative'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem.rb:3:in `<top (required)>'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/filesystem.rb:11:in `require_relative'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/filesystem.rb:11:in `<top (required)>'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys-filesystem.rb:1:in `require_relative'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys-filesystem.rb:1:in `<top (required)>'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/tmp/nix-build-gitlab-8.13.5.drv-0/gitlabhq-v8.13.5-src/config/application.rb:5:in `<top (required)>'
/tmp/nix-build-gitlab-8.13.5.drv-0/gitlabhq-v8.13.5-src/Rakefile:5:in `require'
/tmp/nix-build-gitlab-8.13.5.drv-0/gitlabhq-v8.13.5-src/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
D, [2016-12-07T00:59:22.168370 #152] DEBUG -- sentry: ** [Raven] There was an error while trying to load the gem 'sys-filesystem'.
Gem Load Error is: U
Backtrace for gem load error is:
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/ffi-1.9.10/lib/ffi/library.rb:263:in `attach'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/ffi-1.9.10/lib/ffi/library.rb:263:in `attach_function'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem/functions.rb:13:in `<module:Functions>'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem/functions.rb:5:in `<class:Filesystem>'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem/functions.rb:4:in `<module:Sys>'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem/functions.rb:3:in `<top (required)>'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem.rb:3:in `require_relative'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/unix/sys/filesystem.rb:3:in `<top (required)>'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/filesystem.rb:11:in `require_relative'
/nix/store/31ix5vk3sk75khk9nw2k05smz7x568l1-ruby2.3.1-p0-sys-filesystem-1.1.6/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys/filesystem.rb:11:in `<top (required)>'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys-filesystem.rb:1:in `require_relative'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/sys-filesystem-1.1.6/lib/sys-filesystem.rb:1:in `<top (required)>'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/nix/store/35g60x82qhd2pwy020y3f9jl36vx7wp7-bundler-1.12.5/lib/ruby/gems/2.3.1/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/tmp/nix-build-gitlab-8.13.5.drv-0/gitlabhq-v8.13.5-src/config/application.rb:5:in `<top (required)>'
/tmp/nix-build-gitlab-8.13.5.drv-0/gitlabhq-v8.13.5-src/Rakefile:5:in `require'
/tmp/nix-build-gitlab-8.13.5.drv-0/gitlabhq-v8.13.5-src/Rakefile:5:in `<top (required)>'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/lib/ruby/gems/2.3.1/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/bin/rake:18:in `load'
/nix/store/8jr7yh79k1fmwyxby9i52mg38y23v6ap-gitlab/bin/rake:18:in `<main>'
Bundler Error Backtrace:
 excluded from capture due to environment or should_capture callback
builder for ‘/nix/store/p2qicjhdvjhbmk8vfiyb6rxn9zzfmx2n-gitlab-8.13.5.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/hiz4dzyx71zy5pysyhmbmyxhrag95jdq-gitlab-rake.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/ycswda9ss2rfry0zxxyz4aj8w5j1z94d-unit-gitlab-sidekiq.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/njiv0gcx26kywv34kiid1j447a4l5172-unit-gitlab-workhorse.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/546k4w775c33d84sskqbycq40wkr47y9-unit-gitlab.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/g0sl2l6l9vsd6xjvny1drav2s9l6zrrw-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/nishrhq1cga6qy2npkwci5hyyhvjv3ww-system-units.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/kpz3aw9mhrzps2wv5kxls0gqpwl3p3zq-nixos-system-nixos-16.09.1098.6fe0069.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/kpz3aw9mhrzps2wv5kxls0gqpwl3p3zq-nixos-system-nixos-16.09.1098.6fe0069.drv’ failed
```

This Russian site suggests it may be fixed with paxctl:

http://www.linux.org.ru/forum/web-development/12862656

### Steps to reproduce

Set the following in /etc/nixos/configuration.nix:

```
security.grsecurity.enable = true;
services.gitlab = {
  enable = true;
  databasePassword = "eXaMpl3";
  initialRootPassword = "UseNixOS!";
  secrets = {
     db = "uPgq1gtwwHiatiuE0YHqbGa5lEIXH7fMsvuTNgdzJi8P0Dg12gibTzBQbq5LT7PNzcc3BP9P1snHVnduqtGF43PgrQtU7XL93ts6gqe9CBNhjtaqUwutQUDkygP5NrV6";
    secret = "devzJ0Tz0POiDBlrpWmcsjjrLaltyiAdS8TtgT9YNBOoUcDsfppiY3IXZjMVtKgXrFImIennFGOpPN8IkP8ATXpRgDD5rxVnKuTTwYQaci2NtaV1XxOQGjdIE50VGsR3";
    otp = "e1GATJVuS2sUh7jxiPzZPre4qtzGGaS22FR50Xs1TerRVdgI3CBVUi5XYtQ38W4xFeS4mDqi5cQjExE838iViSzCdcG19XSL6qNsfokQP9JugwiftmhmCadtsnHErBMI";
  };
};
```

## Technical details

* System: (NixOS: `16.09.1098.6fe0069 (Flounder)`)
* Nix version: (run `nix-env (Nix) 1.11.4`)
* Nixpkgs version: ("16.09.1098.6fe0069")

**Comment by joachifm** [comment]
See https://github.com/NixOS/nixpkgs/pull/19953

**Comment by joachifm** [comment]
Disabling mprotect hardening for ruby due to a single gem is unacceptable. What you can do is define a dedicated ruby for gitlab, which does `paxmark m $out/bin/ruby` or whatever is needed to get the gem in question working. Setting PaX flags via RBAC policy is another possibility, but requires more setup and is currently poorly supported.

**Comment by pingberlin** [comment]
I get your point. Thanks again. I'll try with paxmark.

Do you think building a dedicated version of ruby for $application should be documented somewhere for users to find this "best practice" faster? And if yes where? The ruby or grsecurity wiki page?

Since "nodejs" seems to be another dependency, I'll link this here.
#20727

**Comment by joachifm** [comment]
I'd try something like
```
pwnableRuby = super.ruby.overideAttrs (attrs: {
  postFixup = ''
    paxmark m $out/bin/ruby
   '';
});
```
where `super` refers to the original package set. Then it's a matter of making gitlab use that ruby variant.

If you get something working, feel free to submit a PR that describes the general procedure to the grsecurity chapter in the manual.

**Comment by joachifm** [comment]
I believe nodejs cannot work with mprotect hardening at all, in which case disabling it is justified.

**Comment by joachifm** [comment]
As far as I can tell, the gitlab module supports specifying the desired interpreter via
```
services.gitlab.packages.gitlab.ruby
```

**Comment by joachifm** [comment]
I've described how to do this in https://github.com/joachifm/nixpkgs/commit/09918bcf246fa3d7f4d5d7ef02008b2a9b272112. Can you test it?

**Comment by pingberlin** [comment]
I'm using the following config now for gitlab:

```
  security.grsecurity.enable = true;

  services.gitlab = {
    enable = true;
    databasePassword = "eXaMpl3";
    initialRootPassword = "UseNixOS!";
    https = true;
    host = "gitlab.example.org";
    port = 443;
    user = "git";
    group = "git";
    smtp = {
      enable = true;
      address = "localhost";
      port = 25;
    };
    secrets = {
      db = "uPgq1gtwwHiatiuE0YHqbGa5lEIXH7fMsvuTNgdzJi8P0Dg12gibTzBQbq5LT7PNzcc3BP9P1snHVnduqtGF43PgrQtU7XL93ts6gqe9CBNhjtaqUwutQUDkygP5NrV6";
      secret = "devzJ0Tz0POiDBlrpWmcsjjrLaltyiAdS8TtgT9YNBOoUcDsfppiY3IXZjMVtKgXrFImIennFGOpPN8IkP8ATXpRgDD5rxVnKuTTwYQaci2NtaV1XxOQGjdIE50VGsR3";
      otp = "e1GATJVuS2sUh7jxiPzZPre4qtzGGaS22FR50Xs1TerRVdgI3CBVUi5XYtQ38W4xFeS4mDqi5cQjExE838iViSzCdcG19XSL6qNsfokQP9JugwiftmhmCadtsnHErBMI";
  };
    extraConfig = {
      gitlab = {
        email_from = "gitlab-no-reply@gitlab.example.org";
        email_display_name = "GitLab Intern";
        email_reply_to = "gitlab-no-reply@gitlab.example.org";
        default_projects_features = { builds = false; };
      };
    };
    # Use separate vulnerable ruby version for gitlab needed by some gems
    packages.gitlab = pkgs.gitlab.override {
      ruby = pkgs.ruby.overrideAttrs (attrs: {
        postFixup = "paxmark m $out/bin/ruby";
      });
    };
  };
```


And I'm getting the following error message when doing "nixos-rebuild switch":

```
building Nix...
building the system configuration...
error: attribute ‘overrideAttrs’ missing, at /etc/nixos/configuration.nix:125:14
(use ‘--show-trace’ to show detailed location information)
```


With the following configuration it seems to work:

```
  security.grsecurity.enable = true;

  services.gitlab = {
    enable = true;
    databasePassword = "eXaMpl3";
    initialRootPassword = "UseNixOS!";
    https = true;
    host = "gitlab.club.berlin.ccc.de";
    port = 443;
    user = "git";
    group = "git";
    smtp = {
      enable = true;
      address = "localhost";
      port = 25;
    };
    secrets = {
      db = "uPgq1gtwwHiatiuE0YHqbGa5lEIXH7fMsvuTNgdzJi8P0Dg12gibTzBQbq5LT7PNzcc3BP9P1snHVnduqtGF43PgrQtU7XL93ts6gqe9CBNhjtaqUwutQUDkygP5NrV6";
      secret = "devzJ0Tz0POiDBlrpWmcsjjrLaltyiAdS8TtgT9YNBOoUcDsfppiY3IXZjMVtKgXrFImIennFGOpPN8IkP8ATXpRgDD5rxVnKuTTwYQaci2NtaV1XxOQGjdIE50VGsR3";
      otp = "e1GATJVuS2sUh7jxiPzZPre4qtzGGaS22FR50Xs1TerRVdgI3CBVUi5XYtQ38W4xFeS4mDqi5cQjExE838iViSzCdcG19XSL6qNsfokQP9JugwiftmhmCadtsnHErBMI";
  };
    extraConfig = {
      gitlab = {
        email_from = "gitlab-no-reply@gitlab.club.berlin.ccc.de";
        email_display_name = "GitLab Intern";
        email_reply_to = "gitlab-no-reply@gitlab.club.berlin.ccc.de";
        default_projects_features = { builds = false; };
      };
    };
    # Use separate vulnerable ruby version for gitlab needed by some gems
    packages.gitlab = pkgs.gitlab.override {
      ruby = pkgs.stdenv.lib.overrideDerivation pkgs.ruby (oldAttrs : {
        postFixup = "paxmark m $out/bin/ruby";
      });
    };
  };
```

I'm still no Nix expert sadly, but hopefully get better soon. More reading will propably tell me the difference between "overrideAttrs" and "overrideDerivation". 

So does my working config do the same thing you wanted it to do?

**Comment by pingberlin** [comment]
Sorry, I was on a non-grsec-kernel while doing the "nixos-rebuild switch". I'll retest this now.

**Comment by pingberlin** [comment]
Everything seems to be working now. Thank for you blazingly fast help.

**Comment by joachifm** [comment]
Great. I'll put the snippet in the documentation for future reference. Thanks for testing.

**Comment by dtzWill** [comment]
Thanks for the workaround and for documenting it!

Could this snippet be put in the official gitlab service definition, so that it's built, tested, and cached? (and so gitlab works OOB regardless?)

Since the two ruby derivations would be largely identical (the ruby binary itself is a tiny 12K (!)), an optimized nix-store would make the cost minimal for non-PaX users.

**Comment by joachifm** [comment]
@dtzWill sure, please open a PR to that effect; if nobody complains I'll probably integrate it.

**Comment by pingberlin** [comment]
Wouldn't it be a good idea to have a vulnerable version of ruby in the nix store as an alternative ruby package for services like gitlab, so users of the gitlab service wouldn't need to recompile everytime due to overriding things in their "configuration.nix"?

**Comment by dtzWill** [comment]
@pingberlin I think you're suggesting the same thing I suggested? Although I wasn't planning on adding a 'ruby-insecure' explicitly but I suppose might as well :).  I'm not sure when I'll get to this, but it should be straightforward--feel free to submit the PR if you'd like!

**Comment by joachifm** [comment]
The simplest solution is perhaps to pass a modified ruby via the top-level gitlab binding, as in
```nix
let
gitlab = callPackage ... { ruby = ruby.overrideAttrs (attrs: /* ... */); }
```
