### ISSUE TITLE
`git-bz file` doesn't work - "Import of PyCrypto failed"

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#21013]
```
> nix-shell -p gitAndTools.git-bz --run 'git bz file "gtk+/general" HEAD'
Import of PyCrypto failed, please make sure AES and PBKDF2 modules are available in your PyCrypto package
Traceback (most recent call last):
  File "/nix/store/4ll70mn24lp4npz2gd2dcbay33pbgd5c-git-bz-3.2015-09-08/bin/.git-bz-wrapped", line 2665, in <module>
    do_file(*args)
  File "/nix/store/4ll70mn24lp4npz2gd2dcbay33pbgd5c-git-bz-3.2015-09-08/bin/.git-bz-wrapped", line 2451, in do_file
    bug = Bug.create(get_tracker(), product, component, summary, description)
  File "/nix/store/4ll70mn24lp4npz2gd2dcbay33pbgd5c-git-bz-3.2015-09-08/bin/.git-bz-wrapped", line 1518, in create
    server = get_bug_server(host, path, https, auth_user, auth_password)
  File "/nix/store/4ll70mn24lp4npz2gd2dcbay33pbgd5c-git-bz-3.2015-09-08/bin/.git-bz-wrapped", line 1209, in get_bug_server
    servers[identifier] = BugServer(host, path, https, auth_user, auth_password)
  File "/nix/store/4ll70mn24lp4npz2gd2dcbay33pbgd5c-git-bz-3.2015-09-08/bin/.git-bz-wrapped", line 1064, in __init__
    self.cookies = get_bugzilla_cookies(host)
  File "/nix/store/4ll70mn24lp4npz2gd2dcbay33pbgd5c-git-bz-3.2015-09-08/bin/.git-bz-wrapped", line 807, in get_bugzilla_cookies
    return do_get_cookies(host)
  File "/nix/store/4ll70mn24lp4npz2gd2dcbay33pbgd5c-git-bz-3.2015-09-08/bin/.git-bz-wrapped", line 779, in get_bugzilla_cookies_chromium
    config_dir)
  File "/nix/store/4ll70mn24lp4npz2gd2dcbay33pbgd5c-git-bz-3.2015-09-08/bin/.git-bz-wrapped", line 770, in get_bugzilla_cookies_chr
    "select name,encrypted_value,path,expires_utc from cookies where host_key in (:host, '.'||:host)")
  File "/nix/store/4ll70mn24lp4npz2gd2dcbay33pbgd5c-git-bz-3.2015-09-08/bin/.git-bz-wrapped", line 641, in get_cookies_from_sqlite
    result = do_get_cookies_from_sqlite(host, cookies_sqlite, browser, query)
  File "/nix/store/4ll70mn24lp4npz2gd2dcbay33pbgd5c-git-bz-3.2015-09-08/bin/.git-bz-wrapped", line 608, in do_get_cookies_from_sqlite
    cookies = decrypt_cookie_values(cookies, browser)
  File "/nix/store/4ll70mn24lp4npz2gd2dcbay33pbgd5c-git-bz-3.2015-09-08/bin/.git-bz-wrapped", line 754, in decrypt_cookie_values
    key = PBKDF2(password, salt, length, iterations)
UnboundLocalError: local variable 'PBKDF2' referenced before assignment
```

## Technical details

nixpkgs 16.09

**Comment by FRidh** [comment]
#21014
