### ISSUE TITLE
Pillow fails to build on Darwin

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixpkgs#21121]
While trying to install `nixops` from the current unstable channel (17.03pre96825.497e6d2) I get this error. I'm on macOS.

```shell
======================================================================
ERROR: TestFileIcns.test_save
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/Tests/test_file_icns.py", line 31, in test_save
    im.save(temp_file)
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/PIL/Image.py", line 1698, in save
    save_handler(self, fp, filename)
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/PIL/IcnsImagePlugin.py", line 334, in _save
    convert_proc = Popen(convert_cmd, stdout=PIPE, stderr=stderr)
  File "/nix/store/i2q1z1zxgk4i7pkg5nva7dia742jwh5x-python-2.7.12/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/nix/store/i2q1z1zxgk4i7pkg5nva7dia742jwh5x-python-2.7.12/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
-------------------- >> begin captured logging << --------------------
PIL.PngImagePlugin: DEBUG: STREAM IHDR 84847 13
PIL.PngImagePlugin: DEBUG: STREAM iCCP 84872 2625
PIL.PngImagePlugin: DEBUG: iCCP profile name ICC Profile
PIL.PngImagePlugin: DEBUG: Compression method 0
PIL.PngImagePlugin: DEBUG: STREAM pHYs 87509 9
PIL.PngImagePlugin: DEBUG: STREAM IDAT 87530 16384
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: TestFileIm.test_roundtrip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/Tests/test_file_im.py", line 39, in test_roundtrip
    reread = Image.open(out)
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/PIL/Image.py", line 2319, in open
    % (filename if filename else fp))
IOError: cannot identify image file '/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/tempSYrDL1.im'

======================================================================
ERROR: TestImageGrab.test_grab
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/Tests/test_imagegrab.py", line 12, in test_grab
    im = ImageGrab.grab()
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/PIL/ImageGrab.py", line 36, in grab
    subprocess.call(['screencapture', '-x', filepath])
  File "/nix/store/i2q1z1zxgk4i7pkg5nva7dia742jwh5x-python-2.7.12/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/nix/store/i2q1z1zxgk4i7pkg5nva7dia742jwh5x-python-2.7.12/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/nix/store/i2q1z1zxgk4i7pkg5nva7dia742jwh5x-python-2.7.12/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: TestImageGrab.test_grab2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/Tests/test_imagegrab.py", line 17, in test_grab2
    im = ImageGrab.grab()
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/PIL/ImageGrab.py", line 36, in grab
    subprocess.call(['screencapture', '-x', filepath])
  File "/nix/store/i2q1z1zxgk4i7pkg5nva7dia742jwh5x-python-2.7.12/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/nix/store/i2q1z1zxgk4i7pkg5nva7dia742jwh5x-python-2.7.12/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/nix/store/i2q1z1zxgk4i7pkg5nva7dia742jwh5x-python-2.7.12/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: TestModeI16.test_basic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/Tests/test_mode_i16.py", line 77, in test_basic
    basic("L")
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/Tests/test_mode_i16.py", line 45, in basic
    imOut = Image.open(filename)
  File "/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/Pillow-3.4.2/PIL/Image.py", line 2319, in open
    % (filename if filename else fp))
IOError: cannot identify image file '/private/var/folders/wk/z6156zjd63sgwkrbkx3s7rnh0000gn/T/nix-build-python2.7-Pillow-3.4.2.drv-0/tempnrIXYT.im'

----------------------------------------------------------------------
Ran 785 tests in 10.841s

FAILED (errors=5, skipped=82)
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 3.4.2
platform     darwin 2.7.12 (default, Dec  1 2016, 04:18:48)
             [GCC 4.2.1 Compatible Clang 3.7.1 (tags/RELEASE_371/final)]
--------------------------------------------------------------------
--- JPEG support available
*** OPENJPEG (JPEG2000) support not available
--- ZLIB (PNG/ZIP) support available
*** LIBIMAGEQUANT support not available
--- LIBTIFF support available
--- FREETYPE2 support available
--- LITTLECMS2 support available
--- WEBP support available
--- WEBPMUX support available
--------------------------------------------------------------------
To add a missing option, make sure you have the required
library and headers.
See https://pillow.readthedocs.io/en/latest/installation.html#building-from-source

To check the build, run the selftest.py script.

builder for ‘/nix/store/jv1x2w7533j2nwd7z6wpmrq61qmqpski-python2.7-Pillow-3.4.2.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/zlc47xfpapmnklb299ml0dzk6xj1cihw-python2.7-datadog-0.10.0.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/hvbb10l88d9wfahgjwp8dipss3f7nhhr-python2.7-pyjwt-1.4.2’
killing process 25811
cannot build derivation ‘/nix/store/xfvb6nm5ir5q4yd5s82kvcqc8va6fqra-nixops-1.4.drv’: 1 dependencies couldn't be built
```

**Comment by LnL7** [comment]
Looks like the tests are trying to call `screencapture`, might be missing from the buildInputs.

**Comment by LnL7** [comment]
We should disable the ImageGrab tests, not sure what's going on with the other failures.

**Comment by mdaiter** [comment]
https://github.com/NixOS/nixpkgs/commit/6343fef5469863d99208a336048cc2a8cba9dd52

^^Maybe this can provide some insight?

**Comment by mdaiter** [comment]
https://github.com/NixOS/nixpkgs/pull/21293

^^ @3noch @LnL7 this builds on my machine. Maybe we want to pull this? NixOps works well with this enabled on my Mac.

**Comment by mdaiter** [comment]
@3noch should be fixed now.

**Comment by 3noch** [comment]
@mdaiter Woot! Thank you.

**Comment by mdaiter** [comment]
@3noch no prob, glad to help
