### ISSUE TITLE
ACME stopped working in 16.09

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#21144]
## Issue description

If I set up an nginx vhost that uses ACME for certificates, the acme client crashes.

### Steps to reproduce

In `configuration.nix` import:
```nix
{ config, pkgs, ...}:
{
  services.openssh = {
    enable = true;
    passwordAuthentication = false;
  };

  services.nginx = {
    enable = true;
    recommendedGzipSettings = true;
    recommendedOptimisation = true;
    recommendedProxySettings = true;
    recommendedTlsSettings = true;
    virtualHosts = {
      "arianvp.me" = {
        enableACME = true;
        forceSSL = true;
        locations."/" = {
          root = "/var/www/arianvp.me";
          index = "index.html";
        };
      };
    };
  };
}

```
Now:

```bash
# nixos-rebuild switch
● acme-arianvp.me.service - Renew ACME Certificate for arianvp.me
   Loaded: loaded (/nix/store/j3z4asccx41hz4hlrp65qwbpfjp82882-unit-acme-arianvp.me.service/acme-arianvp.me.service; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2016-12-14 12:46:38 UTC; 30ms ago
  Process: 17881 ExecStart=/nix/store/7idrrg571y9c8bj84b36wnp0axqd5ppk-unit-script/bin/acme-arianvp.me-start (code=exited, status=2)
  Process: 17872 ExecStartPre=/nix/store/bxmkggxfi0iqs3jk3fzj804r06i9ivp6-unit-script/bin/acme-arianvp.me-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 17881 (code=exited, status=2)

Dec 14 12:46:38 nixos acme-arianvp.me-start[17881]:     self.net.get(directory).json())
Dec 14 12:46:38 nixos acme-arianvp.me-start[17881]:   File "/nix/store/fwr3rv5z3s5x6pgwrcna7jf6cpc8pd82-python2.7-acme-0.5.0/lib/python2.7/site-packages/acme/messages.py", line 169, in from_json
Dec 14 12:46:38 nixos acme-arianvp.me-start[17881]:     raise jose.DeserializationError(str(error))
Dec 14 12:46:38 nixos acme-arianvp.me-start[17881]: DeserializationError: Deserialization error: Wrong directory fields
Dec 14 12:46:38 nixos acme-arianvp.me-start[17881]: Unhandled error has happened, traceback is above
Dec 14 12:46:38 nixos acme-arianvp.me-start[17881]: Debugging tips: -v improves output verbosity. Help is available under --help.
Dec 14 12:46:38 nixos systemd[1]: acme-arianvp.me.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 14 12:46:38 nixos systemd[1]: Failed to start Renew ACME Certificate for arianvp.me.
Dec 14 12:46:38 nixos systemd[1]: acme-arianvp.me.service: Unit entered failed state.
Dec 14 12:46:38 nixos systemd[1]: acme-arianvp.me.service: Failed with result 'exit-code'.
warning: error(s) occurred while switching to the new configuration

```

## Technical details

* System: 16.09.1229.f52eaf4 (Flounder)

* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.1229.f52eaf4

**Comment by arianvp** [comment]
https://github.com/NixOS/nixpkgs/blob/632282300a9ecbdd8506554aa04c516c64994c84/nixos/modules/services/web-servers/nginx/vhost-options.nix#L35

the following directory does not exist ^
and is not created.
Which is then used as an option for: https://nixos.org/nixos/manual/options.html#opt-security.acme.certs._name__.webroot it seems

So I manually tried:
`mkdir /var/lib/acme/acme-challenge`

and retried.

it still fails with the same error.   

https://nixos.org/nixos/manual/options.html#opt-security.acme.certs._name__.webroot says that a subdirectory `.well-known/acme-challenge` is automatically created  however, when I open
`/var/lib/acme/acme-challenge` it is empty.

So there seems to be a bug where the directory is not created

  Also http://arianvp.me/.well-known/acme-challenge gives a **404 not found**

**Comment by arianvp** [comment]
If I manually create the directory `/var/lib/acme/acme-challenge/.well-known/acme-challenge` then it still fails with the same error

**Comment by arianvp** [comment]
Maybe seems to be fixed in : https://github.com/NixOS/nixpkgs/pull/21102

Trying out now

**Comment by regnat** [comment]
I just ran onto the same issue.
I confirm #21102 fixes it.

**Comment by arianvp** [comment]
so I tried to packageOverride the changes in #21102 but the issue still persists unfortunately (in a clean box, where `/var/lib/acme/acme-challenge` does _not_ exist yet

**Comment by arianvp** [comment]
Error: 

```
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]: 2016-12-15 11:44:52,067:DEBUG:root:611: Received <Response [200]>. Headers: {'Content-Length': '352', 'Expires': 'Thu, 15 Dec 2016 11:44:52 GMT', 'Boulder-Request-Id': 'CENSORED', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 15 Dec 2016 11:44:52 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'SENSORED'}. Content: '{\n  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]: 2016-12-15 11:44:52,069:DEBUG:acme.client:551: Received response <Response [200]> (headers: {'Content-Length': '352', 'Expires': 'Thu, 15 Dec 2016 11:44:52 GMT', 'Boulder-Request-Id': 'CENSORED-', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 15 Dec 2016 11:44:52 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'CENCORED'}): '{\n  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]: Traceback (most recent call last):
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:   File "/nix/store/87sfbwxk40p17qyh81h88ym56a3iakyy-simp_le-2016-04-17/lib/python2.7/site-packages/simp_le.py", line 1401, in main
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:     return main_with_exceptions(cli_args)
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:   File "/nix/store/87sfbwxk40p17qyh81h88ym56a3iakyy-simp_le-2016-04-17/lib/python2.7/site-packages/simp_le.py", line 1386, in main_with_exceptions
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:     persist_new_data(args, existing_data)
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:   File "/nix/store/87sfbwxk40p17qyh81h88ym56a3iakyy-simp_le-2016-04-17/lib/python2.7/site-packages/simp_le.py", line 1282, in persist_new_data
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:     client = registered_client(args, existing_data.account_key)
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:   File "/nix/store/87sfbwxk40p17qyh81h88ym56a3iakyy-simp_le-2016-04-17/lib/python2.7/site-packages/simp_le.py", line 1224, in registered_client
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:     client = acme_client.Client(directory=args.server, key=key, net=net)
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:   File "/nix/store/fwr3rv5z3s5x6pgwrcna7jf6cpc8pd82-python2.7-acme-0.5.0/lib/python2.7/site-packages/acme/client.py", line 63, in __init__
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:     self.net.get(directory).json())
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:   File "/nix/store/fwr3rv5z3s5x6pgwrcna7jf6cpc8pd82-python2.7-acme-0.5.0/lib/python2.7/site-packages/acme/messages.py", line 169, in from_json
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]:     raise jose.DeserializationError(str(error))
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]: DeserializationError: Deserialization error: Wrong directory fields
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]: Unhandled error has happened, traceback is above
Dec 15 11:44:52 arianvp.me acme-arianvp.me-start[4919]: Debugging tips: -v improves output verbosity. Help is available under --help.
Dec 15 11:44:52 arianvp.me systemd[1]: acme-arianvp.me.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 15 11:44:52 arianvp.me systemd[1]: Failed to start Renew ACME Certificate for arianvp.me.
Dec 15 11:44:52 arianvp.me systemd[1]: acme-arianvp.me.service: Unit entered failed state.
Dec 15 11:44:52 arianvp.me systemd[1]: acme-arianvp.me.service: Failed with result 'exit-code'.

```

**Comment by arianvp** [comment]
nevermind, I made a mistake in the packageOverride. I can confirm that #21102 fixes it
