### ISSUE TITLE
`waydroid first-launch` fails to launch

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#211741]
### Describe the bug
`waydroid first-launch` fails with `ERROR: Namespace Gtk not available`

### Steps To Reproduce
```
sudo waydroid init
sudo waydroid first-launch
```

### Expected behavior
A GUI pops open

### Additional context
This in a sway session

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.2, NixOS, 22.11 (Raccoon), 22.11.20230106.2dea899`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by jgonyea** [comment]
I get the following on my KDE NixOS install:
```bash
$ sudo waydroid first-launch
[09:28:20] ERROR: Namespace Gtk not available
[09:28:20] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

```

**Comment by jgonyea** [comment]
Tail of `waydroid log` has the following:

```
% mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(013844) [09:28:08] ERROR: Namespace Gtk not available
(013844) [09:28:08] See also: <https://github.com/waydroid>
(013844) [09:28:08] Traceback (most recent call last):
  File "/nix/store/7c0jjr0jid4xhfdsv13jiwp7q4jl9khi-waydroid-1.3.3/lib/waydroid/tools/__init__.py", line 113, in main
    actions.remote_init_client(args)
  File "/nix/store/7c0jjr0jid4xhfdsv13jiwp7q4jl9khi-waydroid-1.3.3/lib/waydroid/tools/actions/initializer.py", line 205, in remote_init_client
    gi.require_version("Gtk", "3.0")
  File "/nix/store/y09awdg92zm58958q6bc6chacw35pfgm-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

```

**Comment by samueldr** [comment]
I can reproduce on Plasma Mobile.

I expect that environmental pollution from a GNOME or Phosh system made the required bindings available to previous users and testers.
