### ISSUE TITLE
rich-cli: --pager does not work

### ISSUE THREAD

**Issue by schuelermine** [NixOS/nixpkgs#211987]
### Describe the bug
```
Traceback (most recent call last):
  File "/nix/store/a3a7lldql51bm2cb57173mv9q0z12dh1-rich-cli-1.8.0/bin/.rich-wrapped", line 9, in <module>
    sys.exit(run())
  File "/nix/store/a3a7lldql51bm2cb57173mv9q0z12dh1-rich-cli-1.8.0/lib/python3.10/site-packages/rich_cli/__main__.py", line 935, in run
    main()
  File "/nix/store/whih1qwwfq8a4zyzx2kdnpjvwdr9b83k-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/whih1qwwfq8a4zyzx2kdnpjvwdr9b83k-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/whih1qwwfq8a4zyzx2kdnpjvwdr9b83k-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/whih1qwwfq8a4zyzx2kdnpjvwdr9b83k-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/a3a7lldql51bm2cb57173mv9q0z12dh1-rich-cli-1.8.0/lib/python3.10/site-packages/rich_cli/__main__.py", line 704, in main
    from .pager import PagerApp, PagerRenderable
  File "/nix/store/a3a7lldql51bm2cb57173mv9q0z12dh1-rich-cli-1.8.0/lib/python3.10/site-packages/rich_cli/pager.py", line 10, in <module>
    from textual.widgets import ScrollView
  File "/nix/store/4qmbz4wlx2x8xqmylansqyy5fi5m2c3w-python3.10-textual-0.9.1/lib/python3.10/site-packages/textual/widgets/__init__.py", line 62, in __getattr__
    raise ImportError(f"Package 'textual.widgets' has no class '{widget_class}'")
ImportError: Package 'textual.widgets' has no class 'ScrollView'
```

### Steps To Reproduce
1. `nix shell nixpkgs#rich-cli`
2. `rich --pager README.md`

### Expected behavior
Rich starts its pager

### Notify maintainers
@joelkoen

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.3, NixOS, 23.05 (Stoat), 23.05.20230119.d7705c0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos, nixpkgs"`
 - channels(anselmschueler): `""`
 - nixpkgs: `/nix/store/ci0324339l5i3x7q68vigpfcf1jicsgs-source`

**Comment by joelkoen** [comment]
This issue occurs because rich-cli isn't compatible with the newer rich version we have in nixpkgs. I'm not sure what the go is here as rich-cli hasn't been updated for a while (since Jun 21, 2022).

**Comment by schuelermine** [comment]
Ah, interesting. Maybe we should remove `rich-cli`?

**Comment by joelkoen** [comment]
I've done some more troubleshooting and the only thing I can find that doesn't seem to work is `--pager`. If another issue comes up I'll mark it as broken, but I don't think this breaks the whole package as piping into another pager works fine.

**Comment by schuelermine** [comment]
I'd argue it is core functionality as from what I can gather it isn't just piping to your pager program but using a rich-specific pager.
