### ISSUE TITLE
mastodon: fails to build webpush-f14a4d5

### ISSUE THREAD

**Issue by nifoc** [NixOS/nixpkgs#212263]
### Steps To Reproduce
1. build `mastodon` (from `nixpkgs-unstable`)

### Build log
```
$ nix log /nix/store/vfh7cbg4qlcmv8acg0a5m4m76ghz9afx-ruby3.0.4-webpush-0.3.8.drv

@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/64qhrmpp6chr645k8rjs7ramqx7800pj-webpush-f14a4d5
source root is webpush-f14a4d5
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
@nix { "action": "setPhase", "phase": "installPhase" }
installing
buildFlags:
/nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:494:in `realpath': No such file or directory @ rb_check_realpath_internal - ./.git (Errno::ENOENT)
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:494:in `copy_entry'
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:471:in `block in cp_r'
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:1597:in `block in fu_each_src_dest'
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:1613:in `fu_each_src_dest0'
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:470:in `cp_r'
        from /nix/store/ra15vw7xx7vk2y6m5y1dzpr578bsrpdw-nix-bundle-install.rb:93:in `checkout'
        from /nix/store/87pvcgx32h611c341lzph1apdsk43fls-bundler-2.4.3/lib/ruby/gems/2.7.0/gems/bundler-2.4.3/lib/bundler/source/git.rb:324:in `fetch'
        from /nix/store/87pvcgx32h611c341lzph1apdsk43fls-bundler-2.4.3/lib/ruby/gems/2.7.0/gems/bundler-2.4.3/lib/bundler/source/git.rb:166:in `specs'
        from /nix/store/ra15vw7xx7vk2y6m5y1dzpr578bsrpdw-nix-bundle-install.rb:120:in `<main>'
```

### Additional context
I'm not sure if it's related to this issue, but I find it weird that bundler mentions `2.7.0` in its path, but the Ruby version (a few lines higher in the stacktrace) is `3.0.4`.

I'm also not sure if this is specifically a `mastodon` issue or a general issue with `git`-based bundler dependencies.

### Notify maintainers
@happy-river @erictapen @izorkin @ghuntley

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.80, NixOS, 23.05 (Stoat), 23.05.20230111.68e03ab`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/cj56wbd66yvwsphxycyirixnaszlkx14-source`
```

**Comment by nifoc** [comment]
This is a general problem with "gems" that are fetched via `git`.

I will open a new issue that notifies the appropriate people. Sorry for the noise!

**Comment by Izorkin** [comment]
@nifoc this error is already fixed in the master branch.
