### ISSUE TITLE
ruby/nix-bundle-install: all packages with git sources are broken

### ISSUE THREAD

**Issue by nifoc** [NixOS/nixpkgs#212277]
### Steps To Reproduce

1. build `anystyle-cli` from `nixpkgs-unstable` (because of `language_detector`)

This can be reproduced with any package that has a `git` source in its `gemset.nix`. So for example:

1. build `mastodon` from `nixpkgs-unstable` (because of `webpush`)
2. build `metasploit` from `nixpkgs-unstable`

Will fail in basically the same way.

### Build log
```
# anystyle-cli
$ nix log /nix/store/xjp41jpaai00sbqb66gynm792fn5acbh-ruby2.7.6-language_detector-0.1.2.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/zalsw51z2pgjappb479h2r3krsa0z18a-language_detector-8910279
source root is language_detector-8910279
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
@nix { "action": "setPhase", "phase": "installPhase" }
installing
buildFlags:
Traceback (most recent call last):
        10: from /nix/store/ra15vw7xx7vk2y6m5y1dzpr578bsrpdw-nix-bundle-install.rb:120:in `<main>'
         9: from /nix/store/d86l83x4xzj291pzicrja5r8d494wdsr-bundler-2.4.3/lib/ruby/gems/2.7.0/gems/bundler-2.4.3/lib/bundler/source/git.rb:166:in `specs'
         8: from /nix/store/d86l83x4xzj291pzicrja5r8d494wdsr-bundler-2.4.3/lib/ruby/gems/2.7.0/gems/bundler-2.4.3/lib/bundler/source/git.rb:324:in `fetch'
         7: from /nix/store/ra15vw7xx7vk2y6m5y1dzpr578bsrpdw-nix-bundle-install.rb:93:in `checkout'
         6: from /nix/store/2md8drwdkv4x7vgvmiwh7sb0zvgvd2vv-ruby-2.7.6/lib/ruby/2.7.0/fileutils.rb:467:in `cp_r'
         5: from /nix/store/2md8drwdkv4x7vgvmiwh7sb0zvgvd2vv-ruby-2.7.6/lib/ruby/2.7.0/fileutils.rb:1587:in `fu_each_src_dest'
         4: from /nix/store/2md8drwdkv4x7vgvmiwh7sb0zvgvd2vv-ruby-2.7.6/lib/ruby/2.7.0/fileutils.rb:1605:in `fu_each_src_dest0'
         3: from /nix/store/2md8drwdkv4x7vgvmiwh7sb0zvgvd2vv-ruby-2.7.6/lib/ruby/2.7.0/fileutils.rb:1589:in `block in fu_each_src_dest'
         2: from /nix/store/2md8drwdkv4x7vgvmiwh7sb0zvgvd2vv-ruby-2.7.6/lib/ruby/2.7.0/fileutils.rb:468:in `block in cp_r'
         1: from /nix/store/2md8drwdkv4x7vgvmiwh7sb0zvgvd2vv-ruby-2.7.6/lib/ruby/2.7.0/fileutils.rb:491:in `copy_entry'
/nix/store/2md8drwdkv4x7vgvmiwh7sb0zvgvd2vv-ruby-2.7.6/lib/ruby/2.7.0/fileutils.rb:491:in `realpath': No such file or directory @ rb_check_realpath_internal - ./.git (Errno::ENOENT)

# mastodon
$ nix log /nix/store/vfh7cbg4qlcmv8acg0a5m4m76ghz9afx-ruby3.0.4-webpush-0.3.8.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/64qhrmpp6chr645k8rjs7ramqx7800pj-webpush-f14a4d5
source root is webpush-f14a4d5
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
@nix { "action": "setPhase", "phase": "installPhase" }
installing
buildFlags:
/nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:494:in `realpath': No such file or directory @ rb_check_realpath_internal - ./.git (Errno::ENOENT)
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:494:in `copy_entry'
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:471:in `block in cp_r'
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:1597:in `block in fu_each_src_dest'
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:1613:in `fu_each_src_dest0'
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
        from /nix/store/wy09lv0h9m5187smfyq4yfmkiafhmzvc-ruby-3.0.4/lib/ruby/3.0.0/fileutils.rb:470:in `cp_r'
        from /nix/store/ra15vw7xx7vk2y6m5y1dzpr578bsrpdw-nix-bundle-install.rb:93:in `checkout'
        from /nix/store/87pvcgx32h611c341lzph1apdsk43fls-bundler-2.4.3/lib/ruby/gems/2.7.0/gems/bundler-2.4.3/lib/bundler/source/git.rb:324:in `fetch'
        from /nix/store/87pvcgx32h611c341lzph1apdsk43fls-bundler-2.4.3/lib/ruby/gems/2.7.0/gems/bundler-2.4.3/lib/bundler/source/git.rb:166:in `specs'
        from /nix/store/ra15vw7xx7vk2y6m5y1dzpr578bsrpdw-nix-bundle-install.rb:120:in `<main>'
```

### Additional context

I can reproduce this on `nixpkgs-unstable` on Linux and on macOS.

It looks like the `.git` folder used to be part of the "unpacked" gem before, but now it isn't anymore?

### Notify maintainers

@manveru @marsam @zimbatm

(Hopefully tagging the `bundix` maintainers is correct ...)

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.2.0, macOS 13.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(daniel): `"darwin"`
 - channels(root): `"nixpkgs-22.05pre340506.5c37ad87222"`
 - nixpkgs: `/nix/store/m6vc32j0zinnkd9n2wff8y4zc78f7yfy-source`
```

**Comment by CorbanR** [comment]
I believe my issue is similar / caused by the same bug you are experiencing 

### Steps To Reproduce
Steps to reproduce the behavior:
Just trying to install bundix is broken.
1. `nix shell nixpkgs#bundix`

### Build log
```
https://gist.github.com/CorbanR/7e1ec1d6376dce2ea9348f0e015202e4

```

### Additional context
n/a

### Notify maintainers
Maintainers already notified .

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.6.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/qvkzwk5awk8np49w7yd8alisl316l2dr-source`
```

**Comment by marsam** [comment]
Would you mind trying reverting https://github.com/NixOS/nixpkgs/pull/211899?

**Comment by nifoc** [comment]
I don't think #211899 has landed in `nixpkgs-unstable` yet?

**Comment by MForster** [comment]
FWIW, my mastodon build broke as well with the same `webpush` error message. I've binary-searched the first failing commit to be https://github.com/NixOS/nixpkgs/commit/b591671a5051f2ae2667f17f225c7ec82e1a666b, which seemed innocuous to me at first glance. It does update a GitHub source, though.

**Comment by Artturin** [comment]
> Would you mind trying reverting #211899?

that pr fixed the issues

its now in nixos-unstable
