### ISSUE TITLE
Puddletag fails to run

### ISSUE THREAD

**Issue by dschrempf** [NixOS/nixpkgs#212738]
### Describe the bug
Recently, we fixed `puddletag`: https://github.com/NixOS/nixpkgs/pull/201599. However, on `nixpkgs-unstable`, `puddletag` still fails to run on my machine throughing the dreaded:

```
puddletag Version: 2.2.0
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

### Steps To Reproduce
1. nix run nixpkgs#puddletag

### Additional context
The application seems to be correctly wrapped:

```
! /nix/store/pj1hnyxhcsw1krmhnbb9rjvqssbzliw8-bash-5.2-p15/bin/bash -e
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/41yj61kv18cpx7rh4gbrzankxb0r1xd2-python3.10-PyQt5-5.15.7/bin'':'/':'}
PATH='/nix/store/41yj61kv18cpx7rh4gbrzankxb0r1xd2-python3.10-PyQt5-5.15.7/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
```
but still, it does not work.

### Notify maintainers
@peterhoeg and myself.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.89, NixOS, 23.05 (Stoat), 23.05.20230124.e10dc5b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.1`
 - nixpkgs: `/nix/store/6m80n2j1kc4px881n75sp3yx6gblsc56-source`
```

**Comment by peterhoeg** [comment]
There’s definitely an impurity somewhere - it’s working perfectly fine here.

I hadn’t used it in a while, but it runs with `nix run nixpkgs#puddletag' as well as from my slightly outdated `nixos-unstable` currently on this machine.

**Comment by dschrempf** [comment]
This is interesting. The command definitely fails for me. (I was incorrectly saying `nixpkgs-unstable`, but I am also using `nixos-unstable`).

**Comment by peterhoeg** [comment]
That seems to indicate an impurity then.

**Comment by tejing1** [comment]
This is also happening on nixos-22.11, not just unstable.

A friend is having this issue, so I tested it out for myself and got the same thing. For what it's worth, we both use i3, so the impurity may be related to things a DE would normally set up.

**Comment by tejing1** [comment]
```nix
pkgs.puddletag.overrideAttrs (old: { preFixup = (old.preFixup or "") + "\nwrapQtApp $out/bin/puddletag"; })
```
runs fine for me.

**Comment by peterhoeg** [comment]
So definitely a purity thing then.

Care to do a PR?

**Comment by tejing1** [comment]
Sure, I suppose. Just a minute.

**Comment by dschrempf** [comment]
Hi! Thanks for looking into this! I could not test the PR directly because the review process starts to build Python Pandas an whatnot. However, I could start `puddletag` using the fix of @tejing1. Some remarks:

The `puddletag` wrapper without the fix is:
```bash
#! /nix/store/pj1hnyxhcsw1krmhnbb9rjvqssbzliw8-bash-5.2-p15/bin/bash -e
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/41yj61kv18cpx7rh4gbrzankxb0r1xd2-python3.10-PyQt5-5.15.7/bin'':'/':'}
PATH='/nix/store/41yj61kv18cpx7rh4gbrzankxb0r1xd2-python3.10-PyQt5-5.15.7/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/8f3z0gfzckvz9ry8zjqrk0n8ww7pvd6r-qtdeclarative-5.15.8-bin/bin'':'/':'}
PATH='/nix/store/8f3z0gfzckvz9ry8zjqrk0n8ww7pvd6r-qtdeclarative-5.15.8-bin/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/ly0fa35r8iwlp2fzifwx6hqqrsh6il95-python3.10-charset-normalizer-3.0.1/bin'':'/':'}
PATH='/nix/store/ly0fa35r8iwlp2fzifwx6hqqrsh6il95-python3.10-charset-normalizer-3.0.1/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/c3b90b6z9vrffjqabzc03ynmnk8zgidx-python3.10-mutagen-1.46.0/bin'':'/':'}
PATH='/nix/store/c3b90b6z9vrffjqabzc03ynmnk8zgidx-python3.10-mutagen-1.46.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/jirzlk538n9bbbwp54rd9wcsb8nf3rf0-python3.10-numpy-1.23.5/bin'':'/':'}
PATH='/nix/store/jirzlk538n9bbbwp54rd9wcsb8nf3rf0-python3.10-numpy-1.23.5/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/jdl88wn1z9s87as4qq75wqv22swba3xf-puddletag-2.2.0/bin'':'/':'}
PATH='/nix/store/jdl88wn1z9s87as4qq75wqv22swba3xf-puddletag-2.2.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/bin'':'/':'}
PATH='/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/jdl88wn1z9s87as4qq75wqv22swba3xf-puddletag-2.2.0/bin/.puddletag-wrapped"  "$@"
```

The file with the fix (adding the Qt wrapper line):
```bash
#! /nix/store/pj1hnyxhcsw1krmhnbb9rjvqssbzliw8-bash-5.2-p15/bin/bash -e
QT_PLUGIN_PATH=${QT_PLUGIN_PATH:+':'$QT_PLUGIN_PATH':'}
QT_PLUGIN_PATH=${QT_PLUGIN_PATH/':''/nix/store/irnsm3y5mljd3z7v8sqlbc3vvgjkimz5-qtbase-5.15.8-bin/lib/qt->
QT_PLUGIN_PATH='/nix/store/irnsm3y5mljd3z7v8sqlbc3vvgjkimz5-qtbase-5.15.8-bin/lib/qt-5.15.8/plugins'$QT_P>
QT_PLUGIN_PATH=${QT_PLUGIN_PATH#':'}
QT_PLUGIN_PATH=${QT_PLUGIN_PATH%':'}
export QT_PLUGIN_PATH
QT_PLUGIN_PATH=${QT_PLUGIN_PATH:+':'$QT_PLUGIN_PATH':'}
QT_PLUGIN_PATH=${QT_PLUGIN_PATH/':''/nix/store/0vm1m2i3fp1143m2rv8vmrz5blni2imb-qtsvg-5.15.8-bin/lib/qt-5>
QT_PLUGIN_PATH='/nix/store/0vm1m2i3fp1143m2rv8vmrz5blni2imb-qtsvg-5.15.8-bin/lib/qt-5.15.8/plugins'$QT_PL>
QT_PLUGIN_PATH=${QT_PLUGIN_PATH#':'}
QT_PLUGIN_PATH=${QT_PLUGIN_PATH%':'}
export QT_PLUGIN_PATH
QT_PLUGIN_PATH=${QT_PLUGIN_PATH:+':'$QT_PLUGIN_PATH':'}
QT_PLUGIN_PATH=${QT_PLUGIN_PATH/':''/nix/store/8f3z0gfzckvz9ry8zjqrk0n8ww7pvd6r-qtdeclarative-5.15.8-bin/>
QT_PLUGIN_PATH='/nix/store/8f3z0gfzckvz9ry8zjqrk0n8ww7pvd6r-qtdeclarative-5.15.8-bin/lib/qt-5.15.8/plugin>
QT_PLUGIN_PATH=${QT_PLUGIN_PATH#':'}
QT_PLUGIN_PATH=${QT_PLUGIN_PATH%':'}
export QT_PLUGIN_PATH
QML2_IMPORT_PATH=${QML2_IMPORT_PATH:+':'$QML2_IMPORT_PATH':'}
QML2_IMPORT_PATH=${QML2_IMPORT_PATH/':''/nix/store/8f3z0gfzckvz9ry8zjqrk0n8ww7pvd6r-qtdeclarative-5.15.8->
QML2_IMPORT_PATH='/nix/store/8f3z0gfzckvz9ry8zjqrk0n8ww7pvd6r-qtdeclarative-5.15.8-bin/lib/qt-5.15.8/qml'>
QML2_IMPORT_PATH=${QML2_IMPORT_PATH#':'}
QML2_IMPORT_PATH=${QML2_IMPORT_PATH%':'}
export QML2_IMPORT_PATH
QML2_IMPORT_PATH=${QML2_IMPORT_PATH:+':'$QML2_IMPORT_PATH':'}
QML2_IMPORT_PATH=${QML2_IMPORT_PATH/':''/nix/store/s08ykifcnar6n0qpdh26yc2dya4qhmvz-qtquickcontrols-5.15.>
QML2_IMPORT_PATH='/nix/store/s08ykifcnar6n0qpdh26yc2dya4qhmvz-qtquickcontrols-5.15.8/lib/qt-5.15.8/qml'$Q>
QML2_IMPORT_PATH=${QML2_IMPORT_PATH#':'}
QML2_IMPORT_PATH=${QML2_IMPORT_PATH%':'}
export QML2_IMPORT_PATH
QT_PLUGIN_PATH=${QT_PLUGIN_PATH:+':'$QT_PLUGIN_PATH':'}
QT_PLUGIN_PATH=${QT_PLUGIN_PATH/':''/nix/store/k7s7r94k22l9br1xzdxnj1ii731qlfww-qtwayland-5.15.8-bin/lib/>
QT_PLUGIN_PATH='/nix/store/k7s7r94k22l9br1xzdxnj1ii731qlfww-qtwayland-5.15.8-bin/lib/qt-5.15.8/plugins'$Q>
QT_PLUGIN_PATH=${QT_PLUGIN_PATH#':'}
QT_PLUGIN_PATH=${QT_PLUGIN_PATH%':'}
export QT_PLUGIN_PATH
QML2_IMPORT_PATH=${QML2_IMPORT_PATH:+':'$QML2_IMPORT_PATH':'}
QML2_IMPORT_PATH=${QML2_IMPORT_PATH/':''/nix/store/k7s7r94k22l9br1xzdxnj1ii731qlfww-qtwayland-5.15.8-bin/>
QML2_IMPORT_PATH='/nix/store/k7s7r94k22l9br1xzdxnj1ii731qlfww-qtwayland-5.15.8-bin/lib/qt-5.15.8/qml'$QML>
QML2_IMPORT_PATH=${QML2_IMPORT_PATH#':'}
QML2_IMPORT_PATH=${QML2_IMPORT_PATH%':'}
export QML2_IMPORT_PATH
XDG_DATA_DIRS=${XDG_DATA_DIRS:+':'$XDG_DATA_DIRS':'}
XDG_DATA_DIRS=${XDG_DATA_DIRS/':''/nix/store/av11brm0kvh2aiasaga4jd077p69xv75-puddletag-2.2.0/share'':'/'>
XDG_DATA_DIRS='/nix/store/av11brm0kvh2aiasaga4jd077p69xv75-puddletag-2.2.0/share'$XDG_DATA_DIRS
XDG_DATA_DIRS=${XDG_DATA_DIRS#':'}
XDG_DATA_DIRS=${XDG_DATA_DIRS%':'}
export XDG_DATA_DIRS
exec -a "$0" "/nix/store/av11brm0kvh2aiasaga4jd077p69xv75-puddletag-2.2.0/bin/.puddletag-wrapped"  "$@"
```

So there is a substantial difference, and wrapping doesn't seem to work properly without the extra line, even though it should work.

Further, when opening `puddletag` on `nixpkgs-unstable` using the fix, the program crashes when clicking `Help -> About puddletag` with the following error:
```
puddletag Version: 2.2.0
Locale: en_US
Traceback (most recent call last):
  File "/nix/store/av11brm0kvh2aiasaga4jd077p69xv75-puddletag-2.2.0/lib/python3.10/site-packages/puddlestuff/mainwin/funcs.py", line 493, in show_about
    win = about.AboutPuddletag(parent)
  File "/nix/store/av11brm0kvh2aiasaga4jd077p69xv75-puddletag-2.2.0/lib/python3.10/site-packages/puddlestuff/about.py", line 97, in __init__
    ['%s: %s' % (lib, version) for (lib, version) in versions().items()]
  File "/nix/store/av11brm0kvh2aiasaga4jd077p69xv75-puddletag-2.2.0/lib/python3.10/site-packages/puddlestuff/about.py", line 67, in versions
    'Chromaprint': get_module_version('chromaprint'),
  File "/nix/store/av11brm0kvh2aiasaga4jd077p69xv75-puddletag-2.2.0/lib/python3.10/site-packages/puddlestuff/about.py", line 50, in get_module_version
    module = import_module(module_name)
  File "/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/hn3l9hgbh202vs0h3mi993zv0k6l1bbh-python3.10-pyacoustid-1.2.2/lib/python3.10/site-packages/chromaprint.py", line 57, in <module>
    raise ImportError("couldn't find libchromaprint")
ImportError: couldn't find libchromaprint
Aborted (core dumped)
```
I do not think this is related to the wrapping, but it should definitely also be fixed. Somehow, `chromaprint` is not found.

**Comment by tejing1** [comment]
> So there is a substantial difference

My version wraps twice, so the original wrapper and all its settings are still there, in `.puddletag-wrapped`, while the real puddletag script is now in `..puddletag-wrapped-wrapped`.
> and wrapping doesn't seem to work properly without the extra line, even though it should work.

There's a note at the bottom of [the qt section of the nixpkgs manual](https://nixos.org/manual/nixpkgs/stable/#qt-runtime-dependencies) which says that `wrapQtAppsHook` doesn't wrap scripts, only ELF binaries. I don't know what the reasoning for that is, but apparently invoking the wrapping manually is "what you're supposed to do". At least as far as I could tell.

**Comment by dschrempf** [comment]
Ok I see. So the first wrapper handles the python dependencies, and the second one the qt dependencies. Is that so?

**Comment by tejing1** [comment]
Counting the layers outward from the core (rather than, say, in execution order), yes, that's correct.

**Comment by peterhoeg** [comment]
Then we should modify the wrapper args instead to avoid double-wrapping.

**Comment by tejing1** [comment]
Well, to do that, I believe you'd need to reimplement either the python wrapping or the qt wrapping systems, which seems prone to breakage.
