### ISSUE TITLE
mpv: Randomly segfaulting on startup in pipewire

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#212995]
### Describe the bug
`mpv` (at least on 22.11) randomly segfaults on startup.

### Steps To Reproduce
1. `mpv something.ext`
2. Goto 1. until segfault, seemingly random

### Expected behavior
No segfaulting.

### Screenshots
![image](https://user-images.githubusercontent.com/23431373/215158413-251bb9ba-aec8-4373-9d34-8d90e5596f29.png)

### Additional context
Seems to happen somewhere in pipewire stuff.
```
Starting program: /nix/store/m389vh276q5mcw9lm64fsvpddjjk806m-mpv-0.35.0/bin/mpv /home/bt1cn/Musik/Takako_Mamiya-Love_Trip/01.Love_Trip.ogg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libthread_db.so.1".
[New Thread 0x7ffff0bb0640 (LWP 43557)]
[New Thread 0x7ffff03af640 (LWP 43558)]
[New Thread 0x7fffefbae640 (LWP 43559)]
[New Thread 0x7fffef3ad640 (LWP 43560)]
[New Thread 0x7fffeebac640 (LWP 43561)]
[New Thread 0x7fffee3ab640 (LWP 43562)]
[Thread 0x7fffee3ab640 (LWP 43562) exited]
[New Thread 0x7fffee3ab640 (LWP 43563)]
[Thread 0x7fffee3ab640 (LWP 43563) exited]
[New Thread 0x7fffee3ab640 (LWP 43564)]
[New Thread 0x7fffecfaf640 (LWP 43565)]
 (+) Audio --aid=1 'Love Trip' (vorbis 2ch 44100Hz)
File tags:
 Artist: Takako Mamiya
 Album: Love Trip
 Date: 2012
 Genre: Funk / Soul
 Title: Love Trip
 Track: 01
[New Thread 0x7fffd7fff640 (LWP 43566)]
[New Thread 0x7fffd77fe640 (LWP 43567)]
[ao/pipewire] Could not connect to context '(null)': Host is down
[Thread 0x7fffd7fff640 (LWP 43566) exited]

Thread 12 "mpv" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd77fe640 (LWP 43567)]
0x00007fffec7a6520 in impl_pollfd_wait () from /nix/store/wfi3pk89p0mzp1gb067by595nqlrpax2-pipewire-0.3.60-lib/lib/spa-0.2/support/libspa-support.so
(gdb) bt
#0  0x00007fffec7a6520 in impl_pollfd_wait ()
   from /nix/store/wfi3pk89p0mzp1gb067by595nqlrpax2-pipewire-0.3.60-lib/lib/spa-0.2/support/libspa-support.so
#1  0x00007fffec799d4b in loop_iterate ()
   from /nix/store/wfi3pk89p0mzp1gb067by595nqlrpax2-pipewire-0.3.60-lib/lib/spa-0.2/support/libspa-support.so
#2  0x00007ffff59e0f94 in do_loop () from /nix/store/wfi3pk89p0mzp1gb067by595nqlrpax2-pipewire-0.3.60-lib/lib/libpipewire-0.3.so.0
#3  0x00007ffff49aae86 in start_thread () from /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6
#4  0x00007ffff4a31d70 in clone3 () from /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6
```

As mentioned in https://github.com/NixOS/nixpkgs/pull/201367#issuecomment-1319356087, I'm (still) not using pipewire. Forcing it to not use pipewire with `--ao=pulse` seems to, again, prevent it from happening.

### Notify maintainers
@AndersonTorres
@fpletz
@globin
@ma27
@tadeokondrak

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.89-xanmod1, NixOS, 22.11 (Raccoon), 22.11.2028.def9e420d27`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(bt1cn): `"unstable"`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by fpletz** [comment]
Thanks for bringing up this issue again. @leungbk. I've also used mpv with pipewire for quite some time now and have not encountered any issues. I'm closing this for now. Feel free to reopen if this issue persists.
