### ISSUE TITLE
code-server and openvscode-server both broken

### ISSUE THREAD

**Issue by Quantenzitrone** [NixOS/nixpkgs#212956]
### Steps To Reproduce
1. build `code-server` or `openvscode-server`

### Build log
see:
https://hydra.nixos.org/build/207062651
https://hydra.nixos.org/build/207038352

### Additional context
Can someone nail the problem down to a specific pr or commit?

### Notify maintainers

@offlinehacker @henkery @dguenther @ghuntley @emilytrau

**Comment by henkery** [comment]
Broken because of PR https://github.com/NixOS/nixpkgs/pull/211330

**Comment by hacker1024** [comment]
```
[12:20:02] 'vscode-reh-web-linux-x64-min' errored after 6.95 min
[12:20:02] Error: Command failed: /nix/store/b860q13vl4y1rx4zp16xc22cnlrxgdyn-nodejs-16.19.0/bin/node /build/source/lib/vscode/extensions/notebook-renderers/esbuild.js --outputRoot /build/source/lib/vscode/.build/extensions/notebook-renderers
panic: interface conversion: interface {} is nil, not bool

goroutine 21 [running]:
main.(*serviceType).handleBuildRequest(0xc00011bda0, 0x0?, 0xc00011be30?)
        github.com/evanw/esbuild/cmd/esbuild/service.go:576 +0x1066
main.(*serviceType).handleIncomingPacket.func2()
        github.com/evanw/esbuild/cmd/esbuild/service.go:235 +0x68
created by main.(*serviceType).handleIncomingPacket
        github.com/evanw/esbuild/cmd/esbuild/service.go:233 +0xfda

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:552:15)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:552:15)
    at Pipe.<anonymous> (node:net:301:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error: builder for '/nix/store/qsv37r10hgdmgadpjl43953g7j0c0iqm-code-server-4.8.3.drv' failed with exit code 1
```

**Comment by louwers** [comment]
Now broken because `nodejs-16.20.1` is insecure.

**Comment by henkery** [comment]
> Now broken because `nodejs-16.20.1` is insecure.

waiting for https://github.com/coder/code-server/issues/6230
as nodejs 18 migration is blocked
