### ISSUE TITLE
"Permission denied" running `er-patcher`

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#214134]
### Describe the bug

Running any seemingly valid `er-patcher` command seems to result in the same issue:

```
$ er-patcher -- %command%
/etc/profiles/per-user/username/bin/er-patcher:133: DeprecationWarning: pathlib.Path.link_to() is deprecated and is scheduled for removal in Python 3.12. Use pathlib.Path.hardlink_to() instead.
  f.link_to(game_dir_patched / f)
Traceback (most recent call last):
  File "/etc/profiles/per-user/username/bin/er-patcher", line 138, in <module>
    subprocess.run(steam_cmd, cwd=steam_cmd[-1].parent.absolute())
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/mnt/foo/SteamLibrary/steamapps/common/ELDEN RING/Game/er-patcher-tmp/eldenring.exe')
```

### Steps To Reproduce
1. Verify integrity of game files in Steam
2. `cd` into the Elden Ring `Game` directory
3. Run `er-patcher -- %command%`

### Expected behavior

Should run the game.

### Additional context

I have unpacked [Elden Mod Loader 3.2](https://www.nexusmods.com/eldenring/mods/117?tab=files) into my `Game` folder, in case that's relevant.

See also https://github.com/techiew/EldenRingModLoader/issues/8.

### Notify maintainers

@IvarWithoutBones

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90, NixOS, 22.11 (Raccoon), 22.11.2203.285b3ff0660`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by l0b0** [comment]
Looks like I can't run `er-patcher` from the command line, but changing the launch options within Steam to `er-patcher -c -v -s -- %command%` worked. This should probably be documented.
