### ISSUE TITLE
`nixopsUnstable` fails to build due to `libvirt` error

### ISSUE THREAD

**Issue by nightkr** [NixOS/nixpkgs#214280]
### Steps To Reproduce
1. `nix build -f'<nixpkgs>' nixopsUnstable`

### Build log
[/nix/store/9g78i9dr3p4gmw7fjifbgmm9nl4snjvg-python3.10-libvirt-python-8.10.0.drv](https://gist.github.com/nightkr/edc33acbc68e4731ef4493e8de2937c3)

In particular, the wheel build for libvirt-python fails with the following error:

```
Building wheels for collected packages: libvirt-python
  Running command python setup.py bdist_wheel
  running bdist_wheel
  running build
  running build_py
  Missing type converters:
  int *:1
  ERROR: failed virDomainFDAssociate
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/build/libvirt-python-8.10.0/setup.py", line 337, in <module>
      setup(name = 'libvirt-python',
    File "/nix/store/yvv04lrgq2m4vkwlzs9jv720vj9jhdzy-python3.10-setuptools-65.6.3/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
...skipping...
      super().run_command(command)
    File "/nix/store/yvv04lrgq2m4vkwlzs9jv720vj9jhdzy-python3.10-setuptools-65.6.3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/build/libvirt-python-8.10.0/setup.py", line 155, in run
      subprocess.check_call([sys.executable, "generator.py", "libvirt", apis[0], "py"])
    File "/nix/store/sp5x6s8n36gjlwck74xhj1i61p66vcpa-python3-3.10.9/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/nix/store/sp5x6s8n36gjlwck74xhj1i61p66vcpa-python3-3.10.9/bin/python3.10', 'generator.py', 'libvirt', '/nix/store/4bn5xygrcqnnjcgw7x3bi2dfrzs3ic8c-libvirt-9.0.0/share/l>
  error: subprocess-exited-with-error
```

### Notify maintainers
@adisbladis @aminechikhaoui

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
bash: warning: setlocale: LC_ALL: cannot change locale (en_DK.UTF-8)
/nix/store/qqa28hmysc23yy081d178jfd9a1yk8aw-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_DK.UTF-8)
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.8-zen1-1-zen, Arch Linux, noversion, rolling`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(n): `"nixpkgs, nixpkgs-21.11-21.11"`
 - nixpkgs: `/home/teo/.nix-defexpr/channels/nixpkgs`
```

I'm running on the latest nixpkgs-unstable, which is `23.05pre450316.79feedf3853`.

**Comment by roberth** [comment]
Oddly, the identifier from the error, `virDomainFDAssociate`, is listed in the changelog for libvirt 9.0.0, not 8.10, but downgrading to 8.0 makes things worse, adding errors for two more identifiers. This suggests that something, probably the native `libvirt` library, has been updated, and is somehow demanding these features to be present in the python binding. I don't think that is right, but it seems that upgrading libvirt-python to 9.0 fixes the problem.
