### ISSUE TITLE
`yubikey-manager` breaks on PIV reset

### ISSUE THREAD

**Issue by nathantypanski** [NixOS/nixpkgs#214436]
### Describe the bug

```
$ ykman piv reset
ERROR: An unexpected error has occuredTraceback (most recent call last):
  File "/nix/store/spgxbrbjlfhrmaljjpzyi9jzi55s105g-python3.10-yubikey-manager-5.0.0/lib/python3.10/site-packages/ykman/_cli/__main__.py", line 364, in main
    cli(obj={})
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/mb94x06narsvx5pmsah24asj238kqmq5-python3.10-click-8.1.3/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/spgxbrbjlfhrmaljjpzyi9jzi55s105g-python3.10-yubikey-manager-5.0.0/lib/python3.10/site-packages/ykman/_cli/piv.py", line 221, in reset
    force or click.confirm(
TypeError: confirm() got an unexpected keyword argument 'prompt'
```

It seems like `ykman` was written against a different version of the `click` library than the one it's packaged with in Nixpkgs. Alternatively (haven't root caused this yet), the bug is present upstream and needs to be resolved upstream.

### Steps To Reproduce
1. Run `ykman piv reset`.

### Expected behavior
The Yubikey PIV slot would reset.

### Notify maintainers
- @benley
- @Lassulus 
- @pinpox 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.8, NixOS, 22.11 (Raccoon), 22.11.2203.285b3ff0660`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-22.11, nixos-22.11.2203.285b3ff0660"`
 - channels(ndt): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dotlambda** [comment]
Upstream issue: https://github.com/Yubico/yubikey-manager/issues/524
Fixed in Nixpkgs by https://github.com/NixOS/nixpkgs/pull/215271.
