### ISSUE TITLE
pgadmin4 crashes on launch

### ISSUE THREAD

**Issue by squalus** [NixOS/nixpkgs#214892]
### Describe the bug
pgadmin4 crashes on launch.

NixOS x86_64-linux

nixpkgs master@887743a2734

### Steps To Reproduce
1. Open pgadmin

### Additional context
```ERROR  : Failed to create the directory /var/lib/pgadmin:
           [Errno 13] Permission denied: '/var/lib/pgadmin'
HINT :   Create the directory /var/lib/pgadmin, ensure it is writeable by
         'user', and try again, or, create a config_local.py file
         and override the SQLITE_PATH setting per
         https://www.pgadmin.org/docs/pgadmin4/6.18/config_py.html
Traceback (most recent call last):
  File "/nix/store/j9j9v0swfi207gajgs8n8jwvg22w5q45-pgadmin-6.18/lib/python3.10/site-packages/pgadmin4/pgadmin/setup/data_directory.py", line 33, in create_app_data_directory
    is_directory_created = _create_directory_if_not_exists(
  File "/nix/store/j9j9v0swfi207gajgs8n8jwvg22w5q45-pgadmin-6.18/lib/python3.10/site-packages/pgadmin4/pgadmin/setup/data_directory.py", line 20, in _create_directory_if_not_exists
    os.mkdir(_path)
PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/j9j9v0swfi207gajgs8n8jwvg22w5q45-pgadmin-6.18/bin/.pgadmin4-wrapped", line 6, in <module>
    from pgadmin4.pgAdmin4 import main
  File "/nix/store/j9j9v0swfi207gajgs8n8jwvg22w5q45-pgadmin-6.18/lib/python3.10/site-packages/pgadmin4/pgAdmin4.py", line 93, in <module>
    app = create_app()
  File "/nix/store/j9j9v0swfi207gajgs8n8jwvg22w5q45-pgadmin-6.18/lib/python3.10/site-packages/pgadmin4/pgadmin/__init__.py", line 265, in create_app
    create_app_data_directory(config)
  File "/nix/store/j9j9v0swfi207gajgs8n8jwvg22w5q45-pgadmin-6.18/lib/python3.10/site-packages/pgadmin4/pgadmin/setup/data_directory.py", line 46, in create_app_data_directory
    sys.exit(1)
NameError: name 'sys' is not defined
```

### Notify maintainers

@gador
### Metadata
```console
 - system: `0`
 - host os: `Linux 5.4.230, NixOS, 22.11 (Raccoon), 22.11.20230130.f413457`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `""`
 - channels(user): `""`

```

**Comment by squalus** [comment]
It works if I run it like this: `PGADMIN_SERVER_MODE=OFF ./result/bin/pgadmin4`

**Comment by gador** [comment]
Did you create the directory mentioned `/var/lib/pgadmin`?
This is necessary for the app to work.
If you run in desktop Mode, it uses the homedir.

Are you on NixOS? Then you should really use the NixOSmodule

**Comment by squalus** [comment]
Yes, it's on NixOS. I didn't realize there was a module that had to be enabled. Thanks!
