### ISSUE TITLE
calibre fails to run (html5lib related)

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#21504]
## Issue description

When attempting to run a version of calibre built some time after the 20th, you get the following backtrace:

```
mdorman@aching:~$ calibre
Traceback (most recent call last):
  File "/nix/store/cywfl37grsx3jrgz4igalf29xprr2q0y-calibre-2.75.1/lib/calibre/calibre/gui2/ui.py", line 233, in initialize
    ac.do_genesis()
  File "/nix/store/cywfl37grsx3jrgz4igalf29xprr2q0y-calibre-2.75.1/lib/calibre/calibre/gui2/actions/__init__.py", line 145, in do_genesis
    self.genesis()
  File "/nix/store/cywfl37grsx3jrgz4igalf29xprr2q0y-calibre-2.75.1/lib/calibre/calibre/gui2/actions/add.py", line 83, in genesis
    from calibre.ebooks.oeb.polish.create import valid_empty_formats
  File "/nix/store/cywfl37grsx3jrgz4igalf29xprr2q0y-calibre-2.75.1/lib/calibre/calibre/ebooks/oeb/polish/create.py", line 18, in <module>
    from calibre.ebooks.oeb.polish.parsing import parse
  File "/nix/store/cywfl37grsx3jrgz4igalf29xprr2q0y-calibre-2.75.1/lib/calibre/calibre/ebooks/oeb/polish/parsing.py", line 16, in <module>
    from html5lib.treebuilders._base import TreeBuilder as BaseTreeBuilder
ImportError: No module named _base
```

### Steps to reproduce

Run the executable.

## Technical details

* System: NixOS 17.03.git.28ea063
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03.git.28ea063018"

Based strictly on the fact that it's something named 'html5lib' complaining, I'm pulling @phanimahesh in, since he updated that python lib 7 days ago.  I'll try to isolate the failure further.

**Comment by mdorman** [comment]
If I revert just that change, indeed, it starts to work again.

**Comment by mdorman** [comment]
It would appear that calibre is built to run against (and by default carries a local copy of) a 0.999999-dev version of html5lib.  That is, unfortunately, pretty old; I don't know how reasonable it is to try and patch calibre to work against the newer release.  For the moment, I've altered the derivation locally to use the locally-included copy.

**Comment by siddharthist** [comment]
Might be worth filing a bug with calibre: https://bugs.launchpad.net/calibre

**Comment by FRidh** [comment]
The html5lib stuff is a mess; I wish I never merged that commit. Many developers don't seem to be too eager to update to the latest html5lib, especially as long as they're only releasing "beta's". Unfortunately the html5lib authors aren't planning any real release either.

**Comment by phanimahesh** [comment]
Oh god. That update created a chain of mess. :/
