### ISSUE TITLE
`graph-cli` crashes at runtime

### ISSUE THREAD

**Issue by sir4ur0n** [NixOS/nixpkgs#215079]
### Describe the bug
The package `graph-cli` (binary `graph`) is unusable at runtime: it always crashes.

### Steps To Reproduce
1.
```
$ cat test-graph-cli.csv
date,added,deleted,commits
2019-05-17,445,0,2
2019-05-20,155,3,2
```
2.
```
$ graph test-graph-cli.csv
```
results in an error:
```
Traceback (most recent call last):
  File "/nix/store/1l26pvib4gzjpn1gfaajkqwhzi40pjql-graph-cli-0.1.18/bin/.graph-wrapped", line 9, in <module>
    sys.exit(main.main())
  File "/nix/store/1l26pvib4gzjpn1gfaajkqwhzi40pjql-graph-cli-0.1.18/lib/python3.10/site-packages/graph_cli/main.py", line 17, in main
    create_graph(graphs)
  File "/nix/store/1l26pvib4gzjpn1gfaajkqwhzi40pjql-graph-cli-0.1.18/lib/python3.10/site-packages/graph_cli/graph.py", line 261, in create_graph
    fig, ax = plt.subplots(figsize=(Graph.figsize))
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1442, in subplots
    fig = figure(**fig_kw)
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 783, in figure
    manager = new_figure_manager(
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 358, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 336, in _warn_if_gui_out_of_main_thread
    if _get_required_interactive_framework(_get_backend_mod()):
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 207, in _get_backend_mod
    switch_backend(dict.__getitem__(rcParams, "backend"))
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 265, in switch_backend
    backend_mod = importlib.import_module(
  File "/nix/store/sp5x6s8n36gjlwck74xhj1i61p66vcpa-python3-3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/backends/backend_qt5agg.py", line 7, in <module>
    from .backend_qtagg import (    # noqa: F401, E402 # pylint: disable=W0611
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/backends/backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum, _setDevicePixelRatio
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    raise ImportError(
ImportError: Failed to import any of the following Qt binding modules: PyQt6, PySide6, PyQt5, PySide2
```

### Expected behavior
The application works.

### Screenshots
N/A.

### Notify maintainers
* @leungbk 
* Maybe @kilianar ? As they committed a version upgrade

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.1, NixOS, 23.05 (Stoat), 23.05.20221229.677ed08`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/store/7m0y4s8bd0pj7mazwdxrwa2m14hplims-source`
```

**Comment by kilianar** [comment]
The error appears to be caused by `matplotlib`. Replacing it with `matplotlib.override{enableQt = true;}` resolves the error, but results in the following messages:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
It seems to be a wrapping issue in `matplotlib`.

**Comment by kilianar** [comment]
cc @lovek323 @veprbl (as maintainers of `matplotlib`)

**Comment by veprbl** [comment]
You'll also need a `wrapQtAppHook` for the entry point exectables.

**Comment by sir4ur0n** [comment]
Thank you @veprbl your last message was correct! I have opened https://github.com/NixOS/nixpkgs/pull/218533 with that fix, it works on my machine now
