### ISSUE TITLE
VeraCrypt crashes when opening file dialog

### ISSUE THREAD

**Issue by blm768** [NixOS/nixpkgs#216439]
### Describe the bug

For the past few weeks, I've been having an issue where VeraCrypt crashes after clicking the "Select File" button.

### Steps To Reproduce
1. Launch VeraCrypt.
2. Click the "Select File" button near the bottom right side of the main dialog.
3. Experience a crash.

### Expected behavior
The file dialog should open without crashing.

### Additional context

If VeraCrypt is started from a terminal, right before the crash, the following log message appears:

```
(veracrypt:38175): GLib-GIO-ERROR **: 21:24:33.313: No GSettings schemas are installed on the system
```

In a debugger, the program hits a `SIGTRAP` with the following trace:

```
0x00007ffff5dfddcf in g_log_structured_array () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff5dfddcf in g_log_structured_array () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libglib-2.0.so.0
#1  0x00007ffff5dfe1e5 in g_log_default_handler () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libglib-2.0.so.0
#2  0x00007ffff5dfe43d in g_logv () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libglib-2.0.so.0
#3  0x00007ffff5dfe71f in g_log () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libglib-2.0.so.0
#4  0x00007ffff5fd80aa in g_settings_set_property () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgio-2.0.so.0
#5  0x00007ffff70afa37 in object_set_property () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#6  0x00007ffff70b0328 in g_object_new_internal () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#7  0x00007ffff70b1ec1 in g_object_new_valist () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#8  0x00007ffff70b24e9 in g_object_new () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#9  0x00007ffff6388dbc in _gtk_file_chooser_get_settings_for_widget () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#10 0x00007ffff6389db7 in gtk_file_chooser_widget_get_default_size () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#11 0x00007ffff6384346 in file_chooser_widget_default_size_changed () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#12 0x00007ffff70aa5af in g_closure_invoke () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#13 0x00007ffff70bd917 in signal_emit_unlocked_R () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#14 0x00007ffff70c46ba in g_signal_emit_valist () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#15 0x00007ffff70c4b7e in g_signal_emit_by_name () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#16 0x00007ffff70aa7d9 in _g_closure_invoke_va () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#17 0x00007ffff70c464d in g_signal_emit_valist () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#18 0x00007ffff70c494f in g_signal_emit () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#19 0x00007ffff70aa7d9 in _g_closure_invoke_va () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#20 0x00007ffff70c464d in g_signal_emit_valist () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#21 0x00007ffff70c494f in g_signal_emit () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#22 0x00007ffff64a87a5 in gtk_style_context_validate () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#23 0x00007ffff635abc9 in gtk_css_widget_node_validate () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#24 0x00007ffff633e1aa in gtk_css_node_validate_internal.part () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#25 0x00007ffff633e1db in gtk_css_node_validate_internal.part () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#26 0x00007ffff633e1db in gtk_css_node_validate_internal.part () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#27 0x00007ffff656267a in gtk_window_show () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#28 0x00007ffff70aa5af in g_closure_invoke () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#29 0x00007ffff70bd56d in signal_emit_unlocked_R () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#30 0x00007ffff70c46ba in g_signal_emit_valist () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#31 0x00007ffff70c494f in g_signal_emit () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#32 0x00007ffff654ee56 in gtk_widget_show () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#33 0x00007ffff79b4815 in wxWindow::Show(bool) () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_gtk3u_core-3.2.so.0
#34 0x00007ffff799d4a6 in wxTopLevelWindowGTK::Show(bool) () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_gtk3u_core-3.2.so.0
#35 0x00007ffff79f149c in wxDialog::Show(bool) () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_gtk3u_core-3.2.so.0
#36 0x00007ffff79f1712 in wxDialog::ShowModal() () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_gtk3u_core-3.2.so.0
#37 0x00007ffff79f61a0 in wxFileDialog::ShowModal() () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_gtk3u_core-3.2.so.0
#38 0x000000000050fb93 in VeraCrypt::GraphicUserInterface::SelectFiles (this=this@entry=0x8dec40, parent=parent@entry=0xa29280, caption=..., saveMode=saveMode@entry=false, allowMultiple=allowMultiple@entry=false, fileExtensions=std::__cxx11::list = {...}, directory=...) at GraphicUserInterface.cpp:1710
#39 0x00000000005083ff in VeraCrypt::GraphicUserInterface::SelectVolumeFile (this=<optimized out>, parent=0xa29280, saveMode=<optimized out>, directory=...) at GraphicUserInterface.cpp:1732
#40 0x00000000005655f0 in VeraCrypt::MainFrame::OnSelectFileButtonClick (this=0xa29280, event=...) at Forms/MainFrame.cpp:1352
#41 0x00007ffff740a046 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#42 0x00007ffff740a4b6 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#43 0x00007ffff740a840 in wxEvtHandler::TryHereOnly(wxEvent&) () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#44 0x00007ffff740a8eb in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#45 0x00007ffff740a9f1 in wxEvtHandler::ProcessEvent(wxEvent&) () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#46 0x00007ffff740c187 in wxEvtHandler::SafelyProcessEvent(wxEvent&) () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#47 0x00007ffff79e655a in wxgtk_button_clicked_callback () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_gtk3u_core-3.2.so.0
#48 0x00007ffff70aa7d9 in _g_closure_invoke_va () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#49 0x00007ffff70c464d in g_signal_emit_valist () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#50 0x00007ffff70c494f in g_signal_emit () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#51 0x00007ffff62e6550 in gtk_real_button_released () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#52 0x00007ffff70aa7d9 in _g_closure_invoke_va () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#53 0x00007ffff70c464d in g_signal_emit_valist () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#54 0x00007ffff70c494f in g_signal_emit () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#55 0x00007ffff62e48b0 in multipress_released_cb () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#56 0x00007ffff62a4459 in _gtk_marshal_VOID__INT_DOUBLE_DOUBLEv () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#57 0x00007ffff70aa7d9 in _g_closure_invoke_va () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#58 0x00007ffff70c464d in g_signal_emit_valist () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#59 0x00007ffff70c494f in g_signal_emit () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#60 0x00007ffff63b1004 in gtk_gesture_multi_press_end () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#61 0x00007ffff70ad642 in g_cclosure_marshal_VOID__BOXEDv () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#62 0x00007ffff70aa7d9 in _g_closure_invoke_va () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#63 0x00007ffff70c464d in g_signal_emit_valist () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#64 0x00007ffff70c494f in g_signal_emit () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#65 0x00007ffff63ae0a7 in _gtk_gesture_check_recognized () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#66 0x00007ffff63af733 in gtk_gesture_handle_event () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#67 0x00007ffff63b27df in gtk_gesture_single_handle_event () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#68 0x00007ffff6378c1c in gtk_event_controller_handle_event () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#69 0x00007ffff6543d2d in _gtk_widget_run_controllers () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#70 0x00007ffff629d909 in _gtk_marshal_BOOLEAN__BOXED () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#71 0x00007ffff70aa5af in g_closure_invoke () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#72 0x00007ffff70bd2fc in signal_emit_unlocked_R () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#73 0x00007ffff70c3eef in g_signal_emit_valist () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#74 0x00007ffff70c494f in g_signal_emit () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libgobject-2.0.so.0
#75 0x00007ffff6545674 in gtk_widget_event_internal.part () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#76 0x00007ffff63f97a0 in propagate_event () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#77 0x00007ffff63fb1fd in gtk_main_do_event () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#78 0x00007ffff7132b85 in _gdk_event_emit () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgdk-3.so.0
#79 0x00007ffff7166722 in gdk_event_source_dispatch () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgdk-3.so.0
#80 0x00007ffff5df69db in g_main_context_dispatch () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libglib-2.0.so.0
#81 0x00007ffff5df6c88 in g_main_context_iterate.constprop () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libglib-2.0.so.0
#82 0x00007ffff5df6f73 in g_main_loop_run () from /nix/store/24pc1c07rqc5fk7v0skrwjgicilagm52-glib-2.74.3/lib/libglib-2.0.so.0
#83 0x00007ffff63fa3c5 in gtk_main () from /nix/store/4sv3php9ln38hampir0v7mjm1xhazp51-gtk+3-3.24.35/lib/libgtk-3.so.0
#84 0x00007ffff7984035 in wxGUIEventLoop::DoRun() () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_gtk3u_core-3.2.so.0
#85 0x00007ffff72dc06d in wxEventLoopBase::Run() () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#86 0x00007ffff72a6b2b in wxAppConsoleBase::MainLoop() () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#87 0x00007ffff7324286 in wxEntry(int&, wchar_t**) () from /nix/store/g9i8jc1664ji2dblprmd7v12gd6vkkig-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#88 0x00000000004a4654 in main (argc=<optimized out>, argv=0x7fffffff6e58) at Unix/Main.cpp:107
```

Based on the error message and the following issue with a similar stack trace, it seems like there may be a problem with missing GSettings schemas.

- [Evolution bug](https://gitlab.gnome.org/GNOME/evolution/-/issues/1998)
- [Corresponding `nixpkgs` PR](https://github.com/NixOS/nixpkgs/pull/190960)

### Notify maintainers

@dsferruzza (if this is a VeraCrypt issue)
@tfmoraes (if this is a wxGTK issue)

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.10, NixOS, 22.11 (Raccoon), 22.11.20230209.49efda9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - channels(user): `""`
 - nixpkgs: `/nix/store/0ww6l2a68jv8pq99scbmjqinwrh941x0-source`
```

**Comment by Artturin** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/221768
