### ISSUE TITLE
blueman fail to apply network settings

### ISSUE THREAD

**Issue by xieby1** [NixOS/nixpkgs#216610]
### Describe the bug

Fail to apply Network Access Point (NAP) in blueman.
The error message is

```
g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Failed: Traceback (most recent call last):
  File "/nix/store/md2gipa5vf8g2hgrsjbwj16fibgb37hd-blueman-2.3.4/lib/python3.10/site-packages/blueman/main/DbusService.py", line 156, in _handle_method_call
    ok(method(*args))
  File "/nix/store/md2gipa5vf8g2hgrsjbwj16fibgb37hd-blueman-2.3.4/lib/python3.10/site-packages/blueman/plugins/mechanism/Network.py", line 53, in _enable_network
    nc.apply_settings()
  File "/nix/store/md2gipa5vf8g2hgrsjbwj16fibgb37hd-blueman-2.3.4/lib/python3.10/site-packages/blueman/main/NetConf.py", line 426, in apply_settings
    raise NetworkSetupError(
blueman.main.NetConf.NetworkSetupError: Neither ifconfig or ip commands are found. Please install net-tools or iproute2
 (0)
```

### Steps To Reproduce
1. enable blueman in configuration.nix by `services.blueman.enable = true;`
2. blueman -> view -> local services -> Network Access Point (NAP) -> apply
3. Error message pops out

### Expected behavior

The bluetooth NAP network should be enabled

### Notify maintainers

@abbradar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.92, NixOS, 22.11 (Raccoon), 22.11.2523.1b82144edfc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(xieby1): `"nixpkgs-2205-22.05, nixpkgs-unstable"`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ProggerX** [comment]
same problem

**Comment by TotalChaos05** [comment]
Issue still happening in Feb 2024

**Comment by TheFlameFish** [comment]
Still happening to me in Sep 2026.
