### ISSUE TITLE
syncthing-gtk cannot start: "ImportError: cannot import name Gtk"

### ISSUE THREAD

**Issue by jpdoyle** [NixOS/nixpkgs#21717]
## Issue description
After successfully setting up syncthing, I installed syncthing-gtk (python27Packages.syncthing-gtk). It installed without errors, but it won't start when I try to run it.

### Steps to reproduce
 - Install python27Packages.syncthing-gtk
 - Run `syncthing-gtk`

The full traceback I saw was:

    Traceback (most recent call last):
      File "/nix/store/gx1g39b3ifp5v2cjxs812klx37n04six-python2.7-syncthing-gtk-0.6.3/bin/.syncthing-gtk-wrapped", line 15, in <module>
        from syncthing_gtk.tools import init_logging
      File "/nix/store/gx1g39b3ifp5v2cjxs812klx37n04six-python2.7-syncthing-gtk-0.6.3/lib/python2.7/site-packages/syncthing_gtk/__init__.py", line 13, in <module>
        from uibuilder                      import UIBuilder
      File "/nix/store/gx1g39b3ifp5v2cjxs812klx37n04six-python2.7-syncthing-gtk-0.6.3/lib/python2.7/site-packages/syncthing_gtk/uibuilder.py", line 16, in <module>
        from gi.repository import Gtk
    ImportError: cannot import name Gtk

## Technical details

* System: NixOS 16.09.1437.4e7f235 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.1437.4e7f235

**Comment by jokogr** [comment]
@jpdoyle  Could you report back the syncthing and syncthing-gtk versions you are using?

**Comment by FRidh** [comment]
how is it since #21721 has been merged?

**Comment by jpdoyle** [comment]
syncthing-gtk is now working like a charm. Thanks!
