### ISSUE TITLE
unityhub: cannot create new project

### ISSUE THREAD

**Issue by mainrs** [NixOS/nixpkgs#217326]
### Describe the bug
I installed the Unity game engine through the Unityhub program. However, when creating a new project, the hub closes/crashes. 
I cannot find a way to actually create a project and use unity. The engine cannot be started without creating a project first.

### Steps To Reproduce
1. Install unityhub
2. Login and download 2022.1.23f1
3. Create a new project

### Expected behavior
A new project gets created and the engine opens.

### Additional context
```console
❱ unityhub-2.3.2
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Checking for update
Found version 3.4.1 (url: UnityHub.AppImage)
Downloading update from UnityHub.AppImage
updater cache dir: /home/me/.cache/unityhub-updater
No cached update info available
Error: Error: APPIMAGE env is not defined
    at newError (/nix/store/ywdfa4rmvnnjkqzxy0x97g05nbygzf00-unityhub-2.3.2-extracted/resources/app.asar/node_modules/builder-util-runtime/out/index.js:212:17)
    at Object.task (/nix/store/ywdfa4rmvnnjkqzxy0x97g05nbygzf00-unityhub-2.3.2-extracted/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:106:52)
    at AppImageUpdater.executeDownload (/nix/store/ywdfa4rmvnnjkqzxy0x97g05nbygzf00-unityhub-2.3.2-extracted/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:741:25)
```

### Notify maintainers

@tesq0

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.9, NixOS, 22.11 (Raccoon), 22.11.20230204.8e82401`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/store/f30dcvgm875ksqbhmp97wqvxmrzlbbjc-source`
```

**Comment by huantianad** [comment]
Can you try again with the updated unityhub version 3.4.1?

**Comment by FlafyDev** [comment]
Experiencing the same issue on Unity Hub 3.4.2

**Comment by mainrs** [comment]
It worked for me after moving to the nightly `unityhub` version.

**Comment by huantianad** [comment]
@mainrs awesome!

@FlafyDev if there's nothing that stands out in the console logs, can you send the log file located at `~/.config/unityhub/logs/info-log.json` too?
