### ISSUE TITLE
samba-tool broken?

### ISSUE THREAD

**Issue by fegies** [NixOS/nixpkgs#218258]
### Describe the bug

samba-tool broken on nixos 22.11

```
$ nix-shell -p samba4Full

[nix-shell:~]$ samba-tool
Traceback (most recent call last):
  File "/nix/store/msy7pjb95vr745wiy6n0lckin0qhsaap-samba-4.17.5/bin/.samba-tool-wrapped", line 34, in <module>
    from samba.netcmd.main import cmd_sambatool
  File "/nix/store/msy7pjb95vr745wiy6n0lckin0qhsaap-samba-4.17.5/lib/python3.10/site-packages/samba/__init__.py", line 28, in <module>
    import ldb
ModuleNotFoundError: No module named 'ldb'
```

### Steps To Reproduce
1. nix-shell -p samba4full
2. execute samba-tool
3. observe the tool crashing

### Expected behavior
The tool starts correctly

### Additional context

This occurs on NixOS 22.11.

### Notify maintainers

@aneeshusa 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.12, NixOS, 22.11 (Raccoon), 22.11.2720.50c23cd4ff6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(felix): `"home-manager-22.05.tar.gz, nixos-unstable, nixos-old-22.05"`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tcheneau** [comment]
Same error here. The derivation is missing the lbd and talloc "packages".

The fix is straightforward and works for me:
`pythonPath = [ python3Packages.dnspython tdb ldb talloc ];`

I'll try submit a MR on unstable, but I need to reproduce the issue on this branch first.

**Comment by tcheneau** [comment]
Could not reproduce on up to date systems.

Seems that PR #221726 fixed it.
