### ISSUE TITLE
improve vim plugin updater

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#218584]
## Issue description

I would like to be able to call the vim updater to update specific plugins and only these plugins (same for luarocks updater).
For instance in https://github.com/NixOS/nixpkgs/pull/218578, I would like to just update these plugins without regenerating the full set.

Which is anyway impossible at the moment because github flagged some github accounts as suspicious and made those repositories unavailable:
https://github.com/orgs/community/discussions/48173#discussioncomment-5117119
```
1183 plugins were checked, 3 plugin(s) could not be downloaded:

PluginDesc(repo=Repo(Spacegray.vim, https://github.com/ackyshake/Spacegray.vim/), branch='', alias=''): HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 602, in prefetch
    plugin, redirect = prefetch_plugin(pluginDesc, cache)
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 477, in prefetch_plugin
    commit, date = repo.latest_commit()
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 71, in f_retry
    return f(*args, **kwargs)
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 187, in latest_commit
    with urllib.request.urlopen(commit_req, timeout=10) as req:
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
PluginDesc(repo=Repo(VimCompletesMe, https://github.com/ackyshake/VimCompletesMe/), branch='', alias=''): HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 602, in prefetch
    plugin, redirect = prefetch_plugin(pluginDesc, cache)
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 477, in prefetch_plugin
    commit, date = repo.latest_commit()
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 71, in f_retry
    return f(*args, **kwargs)
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 187, in latest_commit
    with urllib.request.urlopen(commit_req, timeout=10) as req:
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
PluginDesc(repo=Repo(Vundle.vim, https://github.com/VundleVim/Vundle.vim/), branch='', alias=''): HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 602, in prefetch
    plugin, redirect = prefetch_plugin(pluginDesc, cache)
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 477, in prefetch_plugin
    commit, date = repo.latest_commit()
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 71, in f_retry
    return f(*args, **kwargs)
  File "/home/teto/nixpkgs3/maintainers/scripts/pluginupdate.py", line 187, in latest_commit
    with urllib.request.urlopen(commit_req, timeout=10) as req:
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

On a sidenote, I wondered if we could add the script to the root's flake.nix's application, so that one can run `nix run .#update-vim-plugins`. This way we can enjoy nix autocompletion, it helps with discovery and one doesn't need to `fd update.py` to find the updater script 

### Steps to reproduce
`$ pkgs/applications/editors/vim/plugins/update.py --proc 5`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by teto** [comment]
I am starting a PR to add subcommands (update.py add / update.py update), this will help making the CLI evolve. For instance I would like to run `update.py update plenary.nvim ` to update ONLY 'plenary.nvim'.  
`update.py add plugin1.vim` should just add the plugin without updating everything.
