### ISSUE TITLE
Build failure: AWSCLI2

### ISSUE THREAD

**Issue by dinko-pehar** [NixOS/nixpkgs#218667]
### Steps To Reproduce

1. build *awscli2*
2. Build fails due to package `cryptography` version is incorrect

### Build log

```
Traceback (most recent call last):
  File "/nix/store/7rjqb838snvvxcmpvck1smfxhkwzqal5-python3-3.10.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/7rjqb838snvvxcmpvck1smfxhkwzqal5-python3-3.10.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/private/tmp/nix-build-awscli2-2.10.1.drv-0/source/./backends/build_system/__main__.py", line 125, in <module>
    main()
  File "/private/tmp/nix-build-awscli2-2.10.1.drv-0/source/./backends/build_system/__main__.py", line 121, in main
    parsed_args.func(parsed_args)
  File "/private/tmp/nix-build-awscli2-2.10.1.drv-0/source/./backends/build_system/__main__.py", line 49, in validate
    validate_env(parsed_args.artifact)
  File "/private/tmp/nix-build-awscli2-2.10.1.drv-0/source/./backends/build_system/validate_env.py", line 39, in validate_env
    raise UnmetDependenciesException(unmet_deps, in_venv)
utils.UnmetDependenciesException: Environment requires following Python dependencies:

cryptography (required: ('>=3.3.2', '<38.0.5')) (version installed: 39.0.1)

We recommend using --with-download-deps flag to automatically create a virtualenv and download the dependencies.

If you want to manage the dependencies yourself instead, run the following pip command:
/nix/store/7rjqb838snvvxcmpvck1smfxhkwzqal5-python3-3.10.10/bin/python -m pip install --prefer-binary 'cryptography>=3.3.2,<38.0.5'

We noticed you are not in a virtualenv.
If not using --with-download-deps we highly recommend using a virtualenv to prevent dependencies from being installed into your global Python environment.

```

### Additional context

`pyproject.toml` specifies `cryptography` from specific version up to specific version, but cryptography package installed is not in that range

### Notify maintainers

@bhipple @davegallant @bryanasdev000 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.3.0, macOS 13.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(raziel): `"darwin, home-manager, unstable"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by wegank** [comment]
Closed by #218602.
