### ISSUE TITLE
hugo fails to open /etc/mime.types

### ISSUE THREAD

**Issue by ptman** [NixOS/nixpkgs#218801]
### Describe the bug
```
hugo
Total in 15 ms
panic: read /etc/mime.types: is a directory

goroutine 1 [running]:
mime.loadMimeFile({0x21eebb9?, 0x8020104?})
	mime/type_unix.go:102 +0x1b2
mime.initMimeUnix()
	mime/type_unix.go:115 +0x85
mime.initMime()
	mime/type.go:88 +0x47
sync.(*Once).doSlow(0xc00083f910?, 0x2?)
	sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	sync/once.go:65
mime.AddExtensionType({0xc0006c3c70?, 0x5?}, {0xc0007af520?, 0x1f?})
	mime/type.go:171 +0x6b
github.com/gohugoio/hugo/hugolib.(*Site).RegisterMediaTypes(0xc000473ad0?)
	github.com/gohugoio/hugo/hugolib/site.go:935 +0x2ca
github.com/gohugoio/hugo/commands.initializeConfig(0x0?, 0x0?, 0x0?, 0x0?, {0x2860ca0?, 0xc000622610?}, 0x0?)
	github.com/gohugoio/hugo/commands/hugo.go:132 +0x9f
github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0xc00079c900, {0x21b67ef?, 0x0?, 0x0?})
	github.com/gohugoio/hugo/commands/commands.go:165 +0x135
github.com/spf13/cobra.(*Command).execute(0xc00079c900, {0xc000040220, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00079c900)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/gohugoio/hugo/commands.Execute({0xc000040220, 0x0, 0x0})
	github.com/gohugoio/hugo/commands/hugo.go:92 +0xbd
main.main()
	github.com/gohugoio/hugo/main.go:23 +0x56
make: *** [Makefile:5: build] Error 2
```

### Steps To Reproduce
1. Run `hugo`

### Expected behavior
I would expect this to be handled since we have https://github.com/rnhmjoj/nixpkgs/blob/master/pkgs/development/compilers/go/mailcap-1.17.patch

### Notify maintainers

@schneefux @Frostman @Br1ght0ne 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.81, NixOS, 22.11 (Raccoon), 22.11.2555.a45a8916243`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11-small, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ptman** [comment]
Sorry for the noise. I just found out that /etc/mime.types/ is empty, I removed it and nixos-rebuild switch didn't recreate it. So I don't know what left it there. hugo works when it isn't present
