### ISSUE TITLE
Build failure: awscli2

### ISSUE THREAD

**Issue by adrianord** [NixOS/nixpkgs#218848]
### Steps To Reproduce

1. use `nixos-unstable`
2. add `awscli2` to packages home packages
3. `darwin-rebuild build`

### Build log

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing pytest-check-hook
Using pytestCheckPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/kmn4b6bdvb82kabsp7jicdhydysxjnqm-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/tox.ini
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
configure flags: --prefix=/nix/store/d217hi07xj42cbz11ljba0dr6jisyipm-awscli2-2.10.1 --bindir=/nix/store/d217hi07xj42cbz11ljba0dr6jisyipm-awscli2-2.10.1/bin --sbindir=/nix/store/d217hi07xj42cbz11ljba0dr6jisyipm-awscli2-2.10.1/sbin --includedir=/nix/store/d217hi07xj42cbz11ljba0dr6jisyipm-awscli2-2.10.1/include --oldincludedir=/nix/store/d217hi07xj42cbz11ljba0dr6jisyipm-awscli2-2.10.1/include --mandir=/nix/store/d217hi07xj42cbz11ljba0dr6jisyipm-awscli2-2.10.1/share/man --infodir=/nix/store/d217hi07xj42cbz11ljba0dr6jisyipm-awscli2-2.10.1/share/info --docdir=/nix/store/d217hi07xj42cbz11ljba0dr6jisyipm-awscli2-2.10.1/share/doc/awscli --libdir=/nix/store/d217hi07xj42cbz11ljba0dr6jisyipm-awscli2-2.10.1/lib --libexecdir=/nix/store/d217hi07xj42cbz11ljba0dr6jisyipm-awscli2-2.10.1/libexec --localedir=/nix/store/d217hi07xj42cbz11ljba0dr6jisyipm-awscli2-2.10.1/share/locale
checking for a Python interpreter with version >= 3.8... python
checking for python... /nix/store/7rjqb838snvvxcmpvck1smfxhkwzqal5-python3-3.10.10/bin/python
checking for python version... 3.10
checking for python platform... darwin
checking for GNU default python prefix... ${prefix}
checking for GNU default python exec_prefix... ${exec_prefix}
checking for python script directory (pythondir)... ${PYTHON_PREFIX}/lib/python3.10/site-packages
checking for python extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib/python3.10/site-packages
checking for sqlite3... yes
checking for --with-install-type... system-sandbox
checking for --with-download-deps... Traceback (most recent call last):
  File "/nix/store/7rjqb838snvvxcmpvck1smfxhkwzqal5-python3-3.10.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/7rjqb838snvvxcmpvck1smfxhkwzqal5-python3-3.10.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/private/tmp/nix-build-awscli2-2.10.1.drv-0/source/./backends/build_system/__main__.py", line 125, in <module>
    main()
  File "/private/tmp/nix-build-awscli2-2.10.1.drv-0/source/./backends/build_system/__main__.py", line 121, in main
    parsed_args.func(parsed_args)
  File "/private/tmp/nix-build-awscli2-2.10.1.drv-0/source/./backends/build_system/__main__.py", line 49, in validate
    validate_env(parsed_args.artifact)
  File "/private/tmp/nix-build-awscli2-2.10.1.drv-0/source/./backends/build_system/validate_env.py", line 39, in validate_env
    raise UnmetDependenciesException(unmet_deps, in_venv)
utils.UnmetDependenciesException: Environment requires following Python dependencies:

cryptography (required: ('>=3.3.2', '<38.0.5')) (version installed: 39.0.1)

We recommend using --with-download-deps flag to automatically create a virtualenv and download the dependencies.

If you want to manage the dependencies yourself instead, run the following pip command:
/nix/store/7rjqb838snvvxcmpvck1smfxhkwzqal5-python3-3.10.10/bin/python -m pip install --prefer-binary 'cryptography>=3.3.2,<38.0.5'

We noticed you are not in a virtualenv.
If not using --with-download-deps we highly recommend using a virtualenv to prevent dependencies from being installed into your global Python environment.

configure: error: "Python dependencies not met."
```

### Notify maintainers

@bhipple 
@davegallant 
@bryanasdev000 
@devusb 
@anthonyroussel 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.3.0, macOS 13.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixpkgs"`
 - channels(aordonez): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by chasecaleb** [comment]
Already fixed by #218602, but nixos-unstable seems to be blocked on build failures or something along those lines :roll_eyes: https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-status

This PR status tracker is a nice way to tell when the fix makes it to nixos-unstable: https://nixpk.gs/pr-tracker.html?pr=218602

**Comment by chasecaleb** [comment]
Also already reported in these duplicate issues:
- #218667
- #218648

**Comment by adrianord** [comment]
Oop, thank you @chasecaleb. Sorry for the duplicate issue, not sure how I didn't see those two other issues when searching.
