### ISSUE TITLE
system-config-printer missing cairo

### ISSUE THREAD

**Issue by jbgi** [NixOS/nixpkgs#21947]
## Issue description
`system-config-printer` fails to start with error:
```
Traceback (most recent call last):
  File "/nix/store/84iqcxj7ayxqr6jgcbppl9n2i43g5c0f-system-config-printer-1.5.7/share/system-config-printer/system-config-printer.py", line 91, in <module>
    import printerproperties
  File "/nix/store/84iqcxj7ayxqr6jgcbppl9n2i43g5c0f-system-config-printer-1.5.7/share/system-config-printer/printerproperties.py", line 42, in <module>
    import gtkinklevel
  File "/nix/store/84iqcxj7ayxqr6jgcbppl9n2i43g5c0f-system-config-printer-1.5.7/share/system-config-printer/gtkinklevel.py", line 23, in <module>
    import cairo
ImportError: No module named 'cairo'
```

## Technical details

* System: NixOS: `17.03pre98682.f673243 (Gorilla)`
* Nix version: `1.11.5`

**Comment by bjornfor** [comment]
Fixed in 19dc19690b00b3a8d9440749c465c6424e8c6cbf (master, a few days ago) and d2f4afc7a07ef08c3b9ed1bcb2bb1ab382aaf655 (release-16.09, just now).
