### ISSUE TITLE
Update request: calibre 6.11.0 → 6.14.1

### ISSUE THREAD

**Issue by kilianar** [NixOS/nixpkgs#220636]
- Package name: [calibre](https://github.com/kovidgoyal/calibre/)
- Latest released version: [6.14.1](https://github.com/kovidgoyal/calibre/releases/tag/v6.14.1)
- Current version on the unstable channel: [6.11.0](https://github.com/kovidgoyal/calibre/releases/tag/v6.11.0)
- Current version on the stable/release channel: [6.8.0](https://github.com/kovidgoyal/calibre/releases/tag/v6.8.0)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@pSub @AndersonTorres 

I attempted to update the version myself, but encountered an issue:
```
Installing calibre environment module: /nix/store/f2nbww9a81pjzbxx6xpyfj5iwqs99byp-calibre-6.14.0/lib/python3.10/site-packages/init_calibre.py
Traceback (most recent call last):
  File "/build/calibre-6.14.0/setup.py", line 119, in <module>
    sys.exit(main())
  File "/build/calibre-6.14.0/setup.py", line 104, in main
    command.run_all(opts)
  File "/build/calibre-6.14.0/setup/__init__.py", line 239, in run_all
    self.run_cmd(self, opts)
  File "/build/calibre-6.14.0/setup/__init__.py", line 233, in run_cmd
    cmd.run(opts)
  File "/build/calibre-6.14.0/setup/install.py", line 153, in run
    self.run_postinstall()
  File "/build/calibre-6.14.0/setup/install.py", line 180, in run_postinstall
    PostInstall(self.opts, info=self.info, warn=self.warn,
  File "/build/calibre-6.14.0/src/calibre/linux.py", line 758, in __init__
    scripts = msgpack_loads(P('scripts.calibre_msgpack', data=True))
  File "/build/calibre-6.14.0/src/calibre/utils/resources.py", line 89, in get_path
    with open(fpath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/build/calibre-6.14.0/resources/scripts.calibre_msgpack'
```

Unfortunately, I don't have the time to investigate further at the moment. Therefore, I would appreciate it if someone else could take it from here.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by kilianar** [comment]
I've updated the issue to reflect that the same error persists even with version [6.14.1](https://github.com/kovidgoyal/calibre/releases/tag/v6.14.1).
