### ISSUE TITLE
Tutanota: unexpected error

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#221379]
### Describe the bug
Each time I open a Tutanota window, there is an error dialog:
```
An unexpected error occurred. Please try again later.
```
```
Feedback v3.110.0 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.110.0
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.110.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
Error
 Error message: Module did not self-register: '/nix/store/68njn99b2axvxhlbaj3xvbdrxvi54ndb-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node'.
Stacktrace: 
Error: Module did not self-register: '/nix/store/68njn99b2axvxhlbaj3xvbdrxvi54ndb-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node'.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at new Au (/nix/store/68njn99b2axvxhlbaj3xvbdrxvi54ndb-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:131802)
    at Nu.openDb (/nix/store/68njn99b2axvxhlbaj3xvbdrxvi54ndb-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:137406)
```

### Steps To Reproduce
1. Open Tutanota

### Expected behavior
No error dialog

### Screenshots
![image](https://user-images.githubusercontent.com/10415894/225452867-c5fcacbd-83bf-41f2-aa53-cfccbdb9ba7b.png)

### Notify maintainers

@WolfangAukang 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.102, NixOS, 22.11 (Raccoon), 22.11.3160.c4aec3c0216`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(aroun): `""`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by WolfangAukang** [comment]
This deserves a ticket on the main repository. Just by looking at the error, it is totally unknown the reason the module was not able to self-register.

**Comment by WolfangAukang** [comment]
Also, I'm not able to reproduce this issue. This is my current system setup:
```
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.19, NixOS, 23.05 (Stoat), 23.05.20230312.5a1dc8a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Zahrun** [comment]
@WolfangAukang Please see the response in tutanota repo https://github.com/tutao/tutanota/issues/5273#issuecomment-1475897347

**Comment by WolfangAukang** [comment]
> @WolfangAukang Please see the response in tutanota repo [tutao/tutanota#5273 (comment)](https://github.com/tutao/tutanota/issues/5273#issuecomment-1475897347)
> this is a problem with nix package (of which there are plenty and we don't want to track them here)

We've come full circle :). No specifics on why this issue is happening to you.

**Comment by Zahrun** [comment]
Hum actually using the version from PR https://github.com/NixOS/nixpkgs/pull/222399 does not have the issue. I guess installing unstable software on 22.11 base can have some side effects. We can close this when the PR is merged.

**Comment by Zahrun** [comment]
Sorry, I am reopening this because in between I updated my whole system to unstable and I get this error again. I also tried in a VM freshly installed snowflakeos and installed tutanota-desktop from `nix profile install github:WolfgangAukang/nixpkgs/tutanota-fix#tutanota-desktop` to get the fix for libstdc++.so, to get the same error. There is an additionnal line in the error message now that I had not put in the original issue post:
```
[ApplicationWindow] closing offline db for LwrSqi5----2
[2023-04-20T07:15:17.994Z] unhandled rejection
[2023-04-20T07:15:17.994Z] unexpected error: Error: Module did not self-register: '/nix/store/59syw33qiy276nsb24dj3ci4b7ywz4y8-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node'.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1326:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:937:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at new Au (/nix/store/59syw33qiy276nsb24dj3ci4b7ywz4y8-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:131802)
    at Nu.openDb (/nix/store/59syw33qiy276nsb24dj3ci4b7ywz4y8-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:137406) {
  code: 'ERR_DLOPEN_FAILED'
}
```
ERR_DLOPEN_FAILED suggests some missing library?

**Comment by WolfangAukang** [comment]
Unfortunately, I still can't reproduce this issue. I'm just thinking out loud trying to troubleshoot what is going on, but what if you run this? The idea is to see why you get that self-register error:
```
export LD_DEBUG=libs
nix build github:WolfangAukang/nixpkgs/tutanota-fix#tutanota-desktop
./result/bin/tutanota-desktop
```

**Comment by Zahrun** [comment]
Hum interesting. There seem to be many different errors (1950 lines with "error:". I think the relevant ones are:
```
     40342:	/nix/store/59syw33qiy276nsb24dj3ci4b7ywz4y8-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node: error: symbol lookup error: undefined symbol: node_register_module_v114 (fatal)
     40342:	/nix/store/59syw33qiy276nsb24dj3ci4b7ywz4y8-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node: error: symbol lookup error: undefined symbol: node_register_module_v114 (fatal)
     40342:	/nix/store/59syw33qiy276nsb24dj3ci4b7ywz4y8-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node: error: symbol lookup error: undefined symbol: napi_register_module_v1 (fatal)
```
[log.txt](https://github.com/NixOS/nixpkgs/files/11287095/log.txt)

**Comment by icodeforyou-dot-net** [comment]
I just wanted to chime in here and state that I too have encountered this error. I'd appreciate any ideas to fix it, even though it is more of an annoyance.

**Comment by Zahrun** [comment]
I was not having this error in stable 22.11, but now that stable is 23.05, I get the error either in stable or in unstable.
I would also like to see this fixed.

**Comment by matt1432** [comment]
After getting tired of all the issues with Tutanota on NixOS, I made my own derivation that extracts the AppImage and runs it with steam-run. Not the cleanest thing but it works.

Here is the file, any changes or improvements are welcome.

### tutanota.nix
```nix
{ lib
, pkgs
, stdenv
, appimageTools
, makeWrapper
, fetchurl
, libGL
, libsecret
, xorg
, ffmpeg
, curl
, alsa-lib
, udev
}:

let
  pname = "tutanota-desktop";
  version = "3.114.1";
  name = "${pname}-${version}";

  src = fetchurl {
    url = "https://github.com/tutao/tutanota/releases/download/tutanota-desktop-release-${version}/tutanota-desktop-linux.AppImage";
    hash = "sha256-cWK95F3/zRyKt2fN/uN/dfDNnSiXgJq6mlGjtD3W7VY=";
  };

  extracted = appimageTools.extractType2 {
    inherit pname version src;
  };

in 

appimageTools.wrapType2 {
  inherit name src;

  profile = ''
    export LD_LIBRARY_PATH=${libGL}:${libsecret}:${ffmpeg}:${curl}:${alsa-lib}:${udev}:$LD_LIBRARY_PATH
  '';

  targetPkgs = pkgs: [ libGL libsecret ffmpeg curl alsa-lib udev ];

  extraInstallCommands = ''
    mkdir -p $out/bin $out/share/applications
    
    cp -r ${extracted}/* $out/

    ln -s $out/tutanota-desktop $out/bin/tutanota-desktop
    
    mv $out/tutanota-desktop.desktop $out/share/applications/
    substituteInPlace $out/share/applications/tutanota-desktop.desktop \
      --replace AppRun ${pname}
    
    source "${makeWrapper}/nix-support/setup-hook"
    wrapProgram $out/bin/${pname} \
      --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [ libsecret stdenv.cc.cc.lib ]}

    sed -i 's#exec -a "$0"#exec -a "$0" "${pkgs.steam-run}/bin/steam-run"#' "$out/bin/${pname}"
  '';
}
```

**Comment by hhydraa** [comment]
I'm experiencing this too; the "show more" button seen in the screenshot above lists this:

```
Feedback v3.113.3 - Error - UNKNOWN - linux
 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.113.3
 Timestamp (UTC): Fri, 11 Aug 2023 20:59:16 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.113.3 Chrome/114.0.5735.106 Electron/25.1.1 Safari/537.36
Error
 Error message: Module did not self-register: '/nix/store/4r12079zc5caalyf2pxkdvlqa923c6ry-tutanota-desktop-3.113.3/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node'.
Stacktrace: 
Error: Module did not self-register: '/nix/store/4r12079zc5caalyf2pxkdvlqa923c6ry-tutanota-desktop-3.113.3/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node'.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at new ou (/nix/store/4r12079zc5caalyf2pxkdvlqa923c6ry-tutanota-desktop-3.113.3/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:125867)
    at fu.openDb (/nix/store/4r12079zc5caalyf2pxkdvlqa923c6ry-tutanota-desktop-3.113.3/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:137889)
```

```
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 23.11 (Tapir), 23.11.20230531.9cfaa8a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

My home-manager and my nixpkgs use the unstable channel; most recently I bumped my flake versions about a month ago. (I just recently installed tutanota.) I can update them and report back if something changes.

**Comment by martantoine** [comment]
Hello

I am also experiencing this
When I launch tutanota desktop for the first time since restarting, I get an could not open the secret storage message, then once connected I get like you this error:
```
Feedback v3.112.6 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.112.6
 Timestamp (UTC): Thu, 21 Sep 2023 09:47:34 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.112.6 Chrome/116.0.5845.188 Electron/26.2.1 Safari/537.36
Error
 Error message: Module did not self-register: '/nix/store/40v6y4mrn18d93f7j9yyfy15drp3314r-tutanota-desktop-3.112.6/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node'.
Stacktrace: 
Error: Module did not self-register: '/nix/store/40v6y4mrn18d93f7j9yyfy15drp3314r-tutanota-desktop-3.112.6/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better_sqlite3.node'.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1869)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2096)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at new iu (/nix/store/40v6y4mrn18d93f7j9yyfy15drp3314r-tutanota-desktop-3.112.6/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:125867)
    at lu.openDb (/nix/store/40v6y4mrn18d93f7j9yyfy15drp3314r-tutanota-desktop-3.112.6/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:137889)
```

My system:
```
ix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.53, NixOS, 23.05 (Stoat), 23.05.3580.5d017a8822e0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by WolfangAukang** [comment]
Tutanota is now using the AppImage. The module issue (the original report from @Zahrun) should now be fixed.

**Comment by Zahrun** [comment]
I can confirm, thank you 🙏
