### ISSUE TITLE
Problems running pip for python 3.10

### ISSUE THREAD

**Issue by 2010person** [NixOS/nixpkgs#222093]
### Describe the bug
There is a bug when I am using NixOS in Replit. I am using Python, HTML and CSS in this project, so my replit.nix looks like this:
```
{ pkgs }: {
    deps = [
        pkgs.python310Packages.pip
        pkgs.python310
        pkgs.htmltest
        pkgs.csslint
    ];
}
```
my .replit looks like this: 
```
run = "python askit.py"

[nix]
channel = "stable-22_11"
```
and my output when I try to install this module (Scrape Search Engine0 is this:
```
 python -m pip install scrape-search-engine --user
Collecting scrape-search-engine
  Using cached scrape_search_engine-0.2.2-py3-none-any.whl
Installing collected packages: scrape-search-engine
Successfully installed scrape-search-engine-0.2.2
--- Logging error ---
Traceback (most recent call last):
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1673, in print
    extend(render(renderable, render_options))
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1305, in render
    for render_output in iter_render:
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_vendor/rich/segment.py", line 249, in split_lines
    for segment in segments:
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1283, in render
    renderable = rich_cast(renderable)
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/bin/pip'
Call stack:
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 190, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 236, in pip_self_version_check
    logger.warning("[present-rich] %s", upgrade_prompt)
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/logging/__init__.py", line 1489, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/nix/store/zzapsinnv4f5mz3kqidd3il61951s534-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.2.2', new='23.0.1'),)
```

### Steps To  Reproduce
1. Configure a blank repl in replit
2. Configure your .replit and replit.nix to the ones above
3. In the shell get pip to run something

### Expected behavior
You will get a shell response as above. Whatever you tried to do with pip would have failed.

### Notify maintainers
Acoording to the NixOS website, pip for Python 3.10 has no maintainers

### Metadata
It dosen't seem to work

**Comment by fricklerhandwerk** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/198059

**Comment by augustebaum** [comment]
According to https://github.com/NixOS/nixpkgs/issues/198059 this might be solved by using a newer version of `pip`, which can be achieved by using a more up-to-date version of nixpkgs:
```ini
# In .replit
run = "python askit.py"

[nix]
channel = "stable-23_05"
```
