### ISSUE TITLE
Build failure: bibata-extra-cursors

### ISSUE THREAD

**Issue by sogreatandpowerfull** [NixOS/nixpkgs#222111]
### Steps To Reproduce

1. build *bibata-extra-cursors*

### Build log

```bash
 inflating: bitmaps/Bibata-Original-Turquoise/left_ptr_watch-0019.png
  inflating: bitmaps/Bibata-Original-Turquoise/move.png
  inflating: bitmaps/Bibata-Original-Turquoise/left_ptr_watch-0084.png
Traceback (most recent call last):
  File "/build/source/builder/build.py", line 7, in <module>
    from bebuild.configure import get_config
  File "/build/source/builder/bebuild/configure.py", line 7, in <module>
    from clickgen.util import PNGProvider
ModuleNotFoundError: No module named 'clickgen.util'
Traceback (most recent call last):
  File "/build/source/builder/build.py", line 7, in <module>
    from bebuild.configure import get_config
  File "/build/source/builder/bebuild/configure.py", line 7, in <module>
    from clickgen.util import PNGProvider
ModuleNotFoundError: No module named 'clickgen.util'
Traceback (most recent call last):
  File "/build/source/builder/build.py", line 7, in <module>
    from bebuild.configure import get_config
  File "/build/source/builder/bebuild/configure.py", line 7, in <module>
    from clickgen.util import PNGProvider
ModuleNotFoundError: No module named 'clickgen.util'
Traceback (most recent call last):
  File "/build/source/builder/build.py", line 7, in <module>
    from bebuild.configure import get_config
  File "/build/source/builder/bebuild/configure.py", line 7, in <module>
    from clickgen.util import PNGProvider
ModuleNotFoundError: No module named 'clickgen.util'
make: *** [Makefile:33: build_modern_unix] Error 1
error: builder for '/nix/store/9siw4ybj05p16pggg27bmxs7alhk1zv5-bibata-extra-cursors-1.0.1.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/c4254lan8ac1abq69f0wlr3h3mw53157-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hvccddhzi22xgfz3dbhfdgq6kmm24cz3-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gd6xfdj2qqrs9wm3h2f6qcb3hz85ps85-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/p25hx5qra75gjg5wgzap4i307r2idkl1-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9ssxg57721hpz1xkyrbpb2n0azjwdh55-nixos-system-ProbabilityWaveFunction-23.05pre465442.b573a7f6948.drv' failed to build
```

### Additional context

Tried to use biba-extra-cursors in my home-manager config (`home-manager.users.sogreatandpowerful.gtk.cursorTheme.package = pkgs.bibata-extra-cursors;`) but it fails to build.

### Notify maintainers
@dtzWill, @AdsonCicilioti

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[sogreatandpowerful@ProbabilityWaveFunction:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/pw17yc3mwmsci4jygwalj8ppg0drz31v-stdenv-linux
copying path '/nix/store/pw17yc3mwmsci4jygwalj8ppg0drz31v-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.3-xanmod1, NixOS, 23.05 (Stoat), 23.05pre465442.b573a7f6948`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(sogreatandpowerful): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kilianar** [comment]
The package was marked as broken in #212461. The project was archived and doesn't support newer versions of `clickgen`.
