### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/boot/efi/nixos'

### ISSUE THREAD

**Issue by andreoss** [NixOS/nixpkgs#222116]
### Describe the bug
/boot is a FAT partition for EFI. 
If it is being mounted with `iocharset=utf8`, the following error occurs during `nixos-rebuild switch`

```
Copied "/nix/store/hhp5rgz71srhcpfh9l3kxal5yh0k4bd4-systemd-252.5/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
Random seed file /boot/loader/random-seed successfully written (32 bytes).
Traceback (most recent call last):
  File "/nix/store/x0mpg5c5q97xji3vx0x1vxvmidqac37s-systemd-boot", line 337, in <module>
    main()
  File "/nix/store/x0mpg5c5q97xji3vx0x1vxvmidqac37s-systemd-boot", line 289, in main
    mkdir_p("/boot/efi/nixos")
  File "/nix/store/x0mpg5c5q97xji3vx0x1vxvmidqac37s-systemd-boot", line 153, in mkdir_p
    os.makedirs(path)
  File "/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/boot/efi/nixos'
warning: error(s) occurred while switching to the new configuration

```

### Steps To Reproduce
1. Mount boot with `iocharset=utf8`
```
sudo umount /boot
sudo mount -o iocharset=utf8 /dev/sda1 /boot
```
2. Run `nixos-rebuild switch --install-bootloader`

### Expected behavior
/boot should be able to have `utf8` charset 

### Screenshots
-

### Additional context
In `configuration.nix`
```
boot.loader.efi.efiSysMountPoint="/boot";
```
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 * nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/a2mfyh90szmc055ivfnv182b5a4naq90-nix-info
copying path '/nix/store/a2mfyh90szmc055ivfnv182b5a4naq90-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.0-rc3, NixOS, 23.05 (Stoat), 23.05.20230318.1603d11`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(a): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by aktaboot** [comment]
According to the kernel documentation on vfat, iocharset=utf8 is not recommended.
 > iocharset=utf8 is not recommended. If unsure, you should consider the utf8 option instead.
 
 using the uft8 option instead does not cause this issue: 
 `sudo mount -o utf8 /dev/sdaX /boot `

https://www.kernel.org/doc/html/latest/filesystems/vfat.html

**Comment by andreoss** [comment]
@aktaboot Using `utf8` option fixes the issue
