### ISSUE TITLE
Platformio permission denied[13]

### ISSUE THREAD

**Issue by MordragT** [NixOS/nixpkgs#224895]
### Describe the bug
Platformio cannot be run by a normal user,
only by superuser.

### Steps To Reproduce
1. Install platformio
2. Run `platformio -t upload` without sudo in your platformio project

### Expected behavior
I would expect for it to run flawlessly even as normal user

### Additional context
Platformio is added to `services.udev.packages = [ pkgs.platformio  ]`
I tried to add my user to the groups `lock uucp dialout plugdev`,
as explained in the platformio docs.
This was more of a desperate attempt, as I am unsure how nixos is working with
udev permissions.
For context: My endgoal is to use platformio-ide extension for vcscode, which is now possible
due to platformio-core  being exposed.
This is the ouput I am getting:

```console
Processing disco_f407vg (platform: ststm32; board: disco_f407vg; framework: stm32cube)
----------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/disco_f407vg.html
PLATFORM: ST STM32 (15.6.0) > ST STM32F4DISCOVERY
HARDWARE: STM32F407VGT6 168MHz, 128KB RAM, 1MB Flash
DEBUG: Current (stlink) On-board (stlink) External (blackmagic, cmsis-dap, jlink)
PACKAGES: 
 - framework-stm32cubef4 @ 1.26.2 
 - tool-dfuutil @ 1.11.0 
 - tool-ldscripts-ststm32 @ 0.2.0 
 - tool-openocd @ 2.1100.211028 (11.0) 
 - tool-stm32duino @ 1.0.1 
 - toolchain-gccarmnoneeabi @ 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 52 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
*** [.pio/build/disco_f407vg/firmware.elf] /home/tom/Desktop/Mordrag/nix-templates/stm32-platformio/.pio/build/disco_f407vg/firmware.elf: Permission denied
PermissionError: [Errno 13] Permission denied: '/home/tom/Desktop/Mordrag/nix-templates/stm32-platformio/.pio/build/disco_f407vg/.sconsign310.tmp':
  File "/home/tom/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Script/Main.py", line 1402:
    _exec_main(parser, values)
  File "/home/tom/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Script/Main.py", line 1365:
    _main(parser)
  File "/home/tom/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Script/Main.py", line 1134:
    nodes = _build_targets(fs, options, targets, target_top)
  File "/home/tom/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Script/Main.py", line 1340:
    jobs.run(postfunc = jobs_postfunc)
  File "/home/tom/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Job.py", line 110:
    postfunc()
  File "/home/tom/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Script/Main.py", line 1337:
    SCons.SConsign.write()
  File "/home/tom/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/SConsign.py", line 133:
    syncmethod()
  File "/home/tom/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/dblite.py", line 148:
    with self._open(self._tmp_name, "wb", self._mode) as f:
Exception ignored in: <function dblite.__del__ at 0x7f8568fa5510>
Traceback (most recent call last):
  File "/home/tom/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/dblite.py", line 144, in __del__
  File "/home/tom/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/dblite.py", line 141, in close
  File "/home/tom/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/dblite.py", line 148, in sync
PermissionError: [Errno 13] Permission denied: '/home/tom/Desktop/Mordrag/nix-templates/stm32-platformio/.pio/build/disco_f407vg/.sconsign310.tmp'
======================== [FAILED] Took 3.62 seconds ========================

```

### Notify maintainers
I am unsure whos is mog

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.9, NixOS, 23.05 (Stoat), 23.05.20230403.53dad94`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by MordragT** [comment]
I believe i fixed it, by adding `pkgs.openocd` to `services.udev.packages`
