### ISSUE TITLE
Build failure: LLVM 15.0.7 on macOS

### ISSUE THREAD

**Issue by punkeel** [NixOS/nixpkgs#225573]
### Steps To Reproduce

1. MacOS M1
2. Install `llvm`

### Build log

https://gist.github.com/punkeel/b3419e2635d4429131b0b1b5489eb3b0

```
[4029/4029] Linking CXX executable unittests/tools/llvm-exegesis/LLVMExegesisTests
buildPhase completed in 13 minutes 47 seconds
@nix { "action": "setPhase", "phase": "checkPhase" }
running tests
check flags: -j10 check-all
[1/2] Preparing lit tests
[1/2] Running all regression tests
llvm-lit: /private/tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/utils/lit/lit/TestingConfig.py:136: fatal: unable to parse config file '/private/tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/test/lit.cfg.py', traceback: Traceback (most recent call last):
  File "/private/tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/utils/lit/lit/TestingConfig.py", line 125, in load_from_path
    exec(compile(data, path, 'exec'), cfg_globals, None)
  File "/private/tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/test/lit.cfg.py", line 447, in <module>
    sysctl_cmd = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/nix/store/cc705zcw6dly3zghdhd0m3cf1cn9a4r4-python3-3.10.9/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/cc705zcw6dly3zghdhd0m3cf1cn9a4r4-python3-3.10.9/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sysctl'

FAILED: CMakeFiles/check-all /tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/build/CMakeFiles/check-all 
cd /tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/build && /nix/store/2k748c8555bj2s4l4c2zan6rbshiqdpq-python3-3.10.9-env/bin/python3.10 /tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/build/./bin/llvm-lit -svj10 --no-progress-bar --param polly_site_config=/tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/build/tools/polly/test/lit.site.cfg --param polly_unit_site_config=/tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/build/tools/polly/test/Unit/lit.site.cfg /tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/build/tools/polly/test /tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/build/utils/lit /tmp/nix-build-llvm-15.0.7.drv-0/llvm-src-15.0.7/llvm/build/test
ninja: build stopped: subcommand failed.
```

### Additional context

It seems to build properly, but fails when running tests.

I encounter this error when upgrading from LLVM 14.0.6 to LLVM 15.0.7.
I first encountered this issue when using the `22.11` channel. I am using the `unstable` channel, still broken.

### Notify maintainers

@dtzWill
@ericson2314
@lovek323
@primeos
@qyliss
@raitobezarius
@rrbutani
@sternenseemann

### Metadata

```console
~ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.5.0, macOS 13.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.9.1`
 - channels(maxime): `"stable-22.11-darwin, unstable"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by rrbutani** [comment]
Thanks for the bug report.

I cannot reproduce this on `master` (fc6da83c94885b34a2691809d0afedf0711c19be) and I recall us ["fixing"](https://github.com/NixOS/nixpkgs/blob/f0a2e06ad29cac466635d746178c11b828e50224/pkgs/development/compilers/llvm/15/llvm/default.nix#L100) this particular issue.

Can you please post the nixpkgs versions  you are using (i.e. something like `nix eval --expr "(import <nixpkgs> {}).lib.version" --impure`) or perhaps the `.drv`s of `llvmPackages_15.llvm` that you end up trying to build?

Also, are you using any special nixpkgs config options/overlays/etc? (I believe `llvmPackages_15.llvm` from `unstable` and `22.11` is in `cache.nixos.org` and should just get substituted)

**Comment by punkeel** [comment]
```console
~ ❯ nix eval --expr "(import <nixpkgs> {}).lib.version" --impure
"22.11pre387031.a0edeb02ae5"
```

Commit: a0edeb02ae5, which seems ancient.

I added `unstable` today after hitting the LLVM error, looks like I didn't do it properly (aka: I didn't remove `22.11`):
```console
~ ❯ nix-channel --list
stable https://nixos.org/channels/nixpkgs-22.11-darwin # <--- ...
unstable https://nixos.org/channels/nixpkgs-unstable
```

Installing LLVN 15.0.7 worked once I removed the `22.11` channel. 👍  Apologies, user issue.
