### ISSUE TITLE
.NET workloads fail to install

### ISSUE THREAD

**Issue by JamieMagee** [NixOS/nixpkgs#226107]
### Describe the bug
Since .NET 5.0, .NET has shipped as a 'slim' SDK with support for optional workloads[^1]. Optional workloads are expected to be installed by the user.

### Steps To Reproduce
1. `nix-shell -p dotnet-sdk_6`
2. `dotnet workload install android`
3. 
<details>
<summary>Error</summary>

```shell
Unhandled exception: System.IO.IOException: Read-only file system : '/nix/store/r04bnvsq19hpds9i7cdrlzcn2cbrs701-dotnet-sdk-6.0.407/metadata'
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallerFactory.CanWriteToDotnetRoot(String dotnetDir)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallerFactory.GetWorkloadInstaller(IReporter reporter, SdkFeatureBand sdkFeatureBand, IWorkloadResolver workloadResolver, VerbosityOptions verbosity, String userProfileDir, Boolean verifySignatures, INuGetPackageDownloader nugetPackageDownloader, String dotnetDir, String tempDirPath, PackageSourceLocation packageSourceLocation, RestoreActionConfig restoreActionConfig, Boolean elevationRequired)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version, IReadOnlyCollection`1 workloadIds, String installedFeatureBand)
   at Microsoft.DotNet.Cli.WorkloadInstallCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult)
   at Microsoft.DotNet.Cli.ParseResultCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

</details>

### Expected behavior
Workloads to be enabled using nix configuration

### Screenshots
N/A

### Additional context
With the following .NET SDKs installed

```
6.0.407 [/nix/store/85fshpgixw0r5a8ar901z9i4xqs6izwg-dotnet-core-combined/sdk]
7.0.202 [/nix/store/85fshpgixw0r5a8ar901z9i4xqs6izwg-dotnet-core-combined/sdk]
8.0.100-preview.2.23157.25 [/nix/store/85fshpgixw0r5a8ar901z9i4xqs6izwg-dotnet-core-combined/sdk]
```

The following workloads are available

```sh
$ dotnet workload search

Workload ID                 Description                                         
--------------------------------------------------------------------------------
android                     .NET SDK Workload for building Android applications.
macos                       .NET SDK Workload for building macOS applications.  
maui-android                .NET MAUI SDK for Android                           
maui-tizen                  .NET MAUI SDK for Tizen                             
maui-windows                .NET MAUI SDK for Windows                           
runtimes-windows            workloads/runtimes-windows/description              
runtimes-windows-net6       workloads/runtimes-windows-net6/description         
runtimes-windows-net7       workloads/runtimes-windows-net7/description         
wasi-experimental           workloads/wasi-experimental/description             
wasm-experimental           workloads/wasm-experimental/description             
wasm-experimental-net7      workloads/wasm-experimental-net7/description        
wasm-tools                  .NET WebAssembly build tools                        
wasm-tools-net6             .NET WebAssembly build tools                        
wasm-tools-net7             workloads/wasm-tools-net7/description
```

### Notify maintainers

@kuznero @mdarocha

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.10, NixOS, 23.05 (Stoat), 23.05.20230412.fe2ecaf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/qyyw6dd6lqlhz3cqap31d071cbyh34bf-source`
```

[^1]: https://github.com/dotnet/designs/blob/main/accepted/2020/workloads/workloads.md

**Comment by JamieMagee** [comment]
A mapping of .NET workload to NuGet packages required is here:
- [.NET 6][1]
- [.NET 7][2]
- [Current (.NET 8)][3]

[1]: https://github.com/dotnet/runtime/blob/main/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest/WorkloadManifest.json.in
[2]: https://github.com/dotnet/runtime/blob/main/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.net7.Manifest/WorkloadManifest.json.in
[3]: https://github.com/dotnet/runtime/blob/main/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Current.Manifest/WorkloadManifest.json.in

**Comment by mdarocha** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/181636

**Comment by JamieMagee** [comment]
@mdarocha thanks!

@Smaug123 it looks like you had more success with dotnet workloads in https://github.com/Smaug123/nix-maui. Would you be interested in upstreaming your work to nixpkgs?

**Comment by Smaug123** [comment]
I'm afraid this isn't something I'd be happy to maintain - it mostly works but is definitely suboptimal and would probably be a decent amount of work to upstream.

**Comment by mdarocha** [comment]
If I'll find the time, I'll attempt to expand on @Smaug123's work

**Comment by adamreed90** [comment]
Since the dotnet workload installer now supports installing to a user directory, could it be possible to simply relocate the dotnet-sdk nixpkg to user space?

**Comment by Smaug123** [comment]
A possible spanner in the works: PublishAot pulls down some binaries from NuGet, and therefore fails out of the box on NixOS. So there's always going to have to be *some* amount of Nix wrangling somewhere.

**Comment by srs-adamr** [comment]
> A possible spanner in the works: PublishAot pulls down some binaries from NuGet, and therefore fails out of the box on NixOS because the AOT compiler can't find the linker (or something like that, it's been a while). So there's always going to have to be _some_ amount of Nix wrangling somewhere.

This makes me so very sad, I only recently started using NixOS and I am a .NET developer by trade, I want to daily drive this so badly :(

**Comment by float3** [comment]
does no solution to this exist?

**Comment by anpin** [comment]
@float3 take a look at workaround [here](https://discourse.nixos.org/t/dotnet-maui-workload/20370), seems to work for some

**Comment by devurandom** [comment]
Copied from: https://github.com/NixOS/nixpkgs/issues/325667

### Describe the bug

It is currently impossible to install .NET workloads on NixOS:
```console
❯ dotnet workload install maui
Unhandled exception: System.IO.IOException: Read-only file system : '/nix/store/as1j1inzdjdaca6gdcfdr2bdsppgr3px-dotnet-sdk-8.0.300/metadata'
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallerFactory.CanWriteToDotnetRoot(String dotnetDir)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallerFactory.GetWorkloadInstaller(IReporter reporter, SdkFeatureBand sdkFeatureBand, IWorkloadResolver workloadResolver, VerbosityOptions verbosity, String userProfileDir, Boolean verifySignatures, INuGetPackageDownloader nugetPackageDownloader, String dotnetDir, String tempDirPath, PackageSourceLocation packageSourceLocation, RestoreActionConfig restoreActionConfig, Boolean elevationRequired, Boolean shouldLog)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolverFactory workloadResolverFactory, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String tempDirPath, IReadOnlyCollection`1 workloadIds)
   at Microsoft.DotNet.Cli.WorkloadInstallCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

### Steps To Reproduce

Steps to reproduce the behavior:
1. Install the .NET Core 8 SDK: `environment.systemPackages = [ pkgs.dotnet-sdk_8 ];`
2. Try to install a workload: `dotnet workload install maui`
3. Observe error

### Expected behavior

`dotnet workload install maui` should install the workload in a user-writeable location.

### Additional context

According to https://github.com/dotnet/sdk/pull/18823 this can be fixed by writing a file `<DOTNET_ROOT>/metadata/workloads/<sdkfeatureband>/userlocal`.  https://discourse.nixos.org/t/dotnet-maui-workload/20370 contains shell code examples how to do that.

### Notify maintainers

@kuznero, @mdarocha

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.05 (Uakari), 24.05.20240702.706eef5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/0z4i8wyg3ymm7kkb1gk2wyh08x230c6z-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by EmVee381** [comment]
> @float3 take a look at workaround [here](https://discourse.nixos.org/t/dotnet-maui-workload/20370), seems to work for some

thanks, it helped me with android workflow

**Comment by anpin** [comment]
@EmVee381 have you found a workaround? Could you please share? Safely I never got it to work on my nixos machine

**Comment by EmVee381** [comment]
> @EmVee381 have you found a workaround? Could you please share? Safely I never got it to work on my nixos machine

i use devenv, but you can use it similar way

is it clear? it is just copy pasted from from your link :) it works for me very well, you just define overrieded package in between "let" block then use it as package in your derivation or shell.nix or anything and set environment variable DOTNET_ROOT 


```
{ pkgs, lib, config, inputs, ... }:

let
  pkgs-stable = import inputs.nixpkgs-stable { system = pkgs.stdenv.system; };
  dotnet-combined = (with pkgs.dotnetCorePackages; combinePackages [
    sdk_8_0
  ]).overrideAttrs (finalAttrs: previousAttrs: {
    # This is needed to install workload in $HOME
    # https://discourse.nixos.org/t/dotnet-maui-workload/20370/2
    postBuild = (previousAttrs.postBuild or '''') + ''
       for i in $out/sdk/*
       do
         i=$(basename $i)
         length=$(printf "%s" "$i" | wc -c)
         substring=$(printf "%s" "$i" | cut -c 1-$(expr $length - 2))
         i="$substring""00"
         mkdir -p $out/metadata/workloads/''${i/-*}
         touch $out/metadata/workloads/''${i/-*}/userlocal
      done
    '';
  });
in
rec
{
  env.GREET = "avalonia";
  env.DOTNET_ROOT = "${dotnet-combined}";
  languages.dotnet.enable = true;
  languages.dotnet.package = dotnet-combined;
  packages = [
    pkgs.git
    pkgs.omnisharp-roslyn
  ];

}
```

**Comment by anpin** [comment]
Above workaround and the one posted on discourse no longer works due to a change in sdk wrapper and folder structure

**Comment by EmVee381** [comment]
> Above workaround and the one posted on discourse no longer works due to a change in sdk wrapper and folder structure

Use

pkgs.dotnetCorePackages.dotnet_8.sdk

This package works the same way as the one in the workaround. I use it without any problems

**Comment by 34j** [comment]
> > Above workaround and the one posted on discourse no longer works due to a change in sdk wrapper and folder structure
> 
> Use following package directly: pkgs.dotnetCorePackages.dotnet_8.sdk
> 
> No workaround is needed if you use it.
> 
> This package works the same way as the workaround did. I’ve been using it without any issues.

The docs also seems to recommend using `pkgs.dotnetCorePackages`:

https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/dotnet.section.md#dotnet-sdk-vs-dotnetcorepackagessdk-dotnet-sdk-vs-dotnetcorepackagessdk

**Comment by oatberry** [comment]
I noticed that while using a single `dotnet_X.sdk` package allowed installation of workloads locally, using `dotnetCorePackages.combinePackages` didn't.

I submitted [a patch](https://github.com/NixOS/nixpkgs/pull/396181) to fix this and it appears to be in branch nixos-24.11 now, so this should now work using a devshell like so:

```nix
{ pkgs }:

let
  dotnet = (with pkgs.dotnetCorePackages; combinePackages [ dotnet_9.sdk dotnet_8.sdk ]);
in

pkgs.mkShell {
  packages = [ dotnet ];

  DOTNET_PATH = "${dotnet}/bin/dotnet";
  DOTNET_ROOT = "${dotnet}/share/dotnet";
}
```

being sure to use the `dotnet_X.sdk` packages. Hope this is useful!

**Comment by anpin** [comment]
@oatberry something changed, your fix worked for a little while, but now I'm no longer able to install android workload. It is not even listed in the search.

```console
$ dotnet workload search

Workload ID                 Description
----------------------------------------------------------------------------
aspire                      .NET Aspire SDK
wasi-experimental           workloads/wasi-experimental/description
wasi-experimental-net8      workloads/wasi-experimental-net8/description
wasm-experimental           .NET WebAssembly experimental tooling
wasm-experimental-net7      .NET WebAssembly experimental tooling for net7.0
wasm-experimental-net8      .NET WebAssembly experimental tooling for net8.0
wasm-tools                  .NET WebAssembly build tools
wasm-tools-net6             .NET WebAssembly build tools for net6.0
wasm-tools-net7             .NET WebAssembly build tools for net7.0
wasm-tools-net8             .NET WebAssembly build tools for net8.0

$ dotnet --info
.NET SDK:
 Version:           9.0.105
 Commit:            b7deac6d42
 Workload version:  9.0.100-manifests.3b27a542
 MSBuild version:   17.12.32+b7deac6d4

Runtime Environment:
 OS Name:     nixos
 OS Version:  25.05
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /nix/store/hzdqc45clz93vdrhwmdd87zc92r2bwwc-dotnet-sdk-9.0.105/share/dotnet/sdk/9.0.105/

.NET workloads installed:
 [wasi-experimental]
   Installation Source: SDK 9.0.100
   Manifest Version:    9.0.4/9.0.100
   Manifest Path:       /nix/store/rldjjlk1fywl0y19vl567jrmj3v2j6pn-dotnet-combined/share/dotnet/sdk-manifests/9.0.100/microsoft.net.workload.mono.toolchain.current/9.0.4/WorkloadManifest.json
   Install Type:        FileBased

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.4
  Architecture: x64
  Commit:       b7deac6d42

.NET SDKs installed:
  8.0.115 [/nix/store/rldjjlk1fywl0y19vl567jrmj3v2j6pn-dotnet-combined/share/dotnet/sdk]
  9.0.105 [/nix/store/rldjjlk1fywl0y19vl567jrmj3v2j6pn-dotnet-combined/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.15 [/nix/store/rldjjlk1fywl0y19vl567jrmj3v2j6pn-dotnet-combined/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.4 [/nix/store/rldjjlk1fywl0y19vl567jrmj3v2j6pn-dotnet-combined/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.15 [/nix/store/rldjjlk1fywl0y19vl567jrmj3v2j6pn-dotnet-combined/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.4 [/nix/store/rldjjlk1fywl0y19vl567jrmj3v2j6pn-dotnet-combined/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/nix/store/681ch41kmvr61nkr57rlsy9zw16aa3if-dotnet-wrapped-combined/share/dotnet]

global.json file:
  /home/a/projects/openstrava/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
