### ISSUE TITLE
Tutanota fail to start : « org.freedesktop.portal.FileChooser » is missing

### ISSUE THREAD

**Issue by 0b11stan** [NixOS/nixpkgs#226493]
### Describe the bug

Tutanota fail to start, i'm pretty sure I started tutanota a few days ago without an error but I can not guarantee, it would be strange as the derivation did not change since then (i update every day).

Looks like it complains about a missing FileChooser interface. I'll look into it in the following days.

### Steps To Reproduce

Run `tutanota-desktop` in terminal.

### Expected behavior

Tutanota is starting without errors.

### Screenshots

Here is my output when running `tutanota-desktop` in the shell

```
[tristan@master:~]$ tutanota-desktop
[2023-04-16T15:20:49.036Z] App threw an error during load
[2023-04-16T15:20:49.039Z] Error: libstdc++.so.6: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/nix/store/xm0vpzm7h9ybfrqk4lcfc344s8jfyxr7-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:1:424031)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libstdc++.so.6: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/nix/store/xm0vpzm7h9ybfrqk4lcfc344s8jfyxr7-tutanota-desktop-3.110.0/share/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:1:424031)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
[1690:0416/172049.077097:ERROR:object_proxy.cc(622)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: L’interface « org.freedesktop.portal.FileChooser » n’existe pas
[1690:0416/172049.077147:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
did not find extension DRI_Mesa version 1
failed to bind extensions
MESA-LOADER: failed to open zink: /run/opengl-driver/lib/dri/zink_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)
did not find extension DRI_Mesa version 1
failed to bind extensions
did not find extension DRI_Mesa version 1
failed to bind extensions
```

The process hang there, whithout closing.

### Additional context

If it's relevant, i'm on **Wayland** (sway), and i'm on channel **unstable**.

### Notify maintainers

@WolfangAukang 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[tristan@master:~]$ nix-shell -p nix-info --run "nix-info -m"
these 4 paths will be fetched (0.70 MiB download, 9.46 MiB unpacked):
  /nix/store/576iqyz893c8zg0qy92is04cgcjanqky-file-5.43
  /nix/store/hnwgz78qripqnnnprar3lzmp7ymkv90x-gnumake-4.3
  /nix/store/ifiygfv17dzpbssxwrld6a57iclzrb09-stdenv-linux
  /nix/store/qbbh33w8jwr1pb6vxp2aplcsdlj6hvvk-patchelf-0.15.0
copying path '/nix/store/576iqyz893c8zg0qy92is04cgcjanqky-file-5.43' from 'https://cache.nixos.org'...
copying path '/nix/store/hnwgz78qripqnnnprar3lzmp7ymkv90x-gnumake-4.3' from 'https://cache.nixos.org'...
copying path '/nix/store/qbbh33w8jwr1pb6vxp2aplcsdlj6hvvk-patchelf-0.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/ifiygfv17dzpbssxwrld6a57iclzrb09-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.106, NixOS, 22.11 (Raccoon), 22.11.3689.fda0d99c2cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - channels(tristan): `"home-manager-22.11.tar.gz, nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by WolfangAukang** [comment]
Can confirm I'm seeing the same issue when building from nixpkgs-unstable.

**Comment by WolfangAukang** [comment]
Luckily it was just adding `stdenv.cc.cc.lib` to the LD_LIBRARY_PATH. From there I get a working window. Posting PR soon.

**Comment by 0b11stan** [comment]
Great ! Thank you for the quick response and for maintaining the tutanota derivation !!
