### ISSUE TITLE
kodi: youtube plugin is failing

### ISSUE THREAD

**Issue by dschrempf** [NixOS/nixpkgs#226613]
### Describe the bug
When using Kodi with the YouTube plugin , I get the following error:

```
2023-04-17 11:25:54.137 T:6006    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'infotagger'
                                                   Traceback (most recent call last):
                                                     File "/nix/store/wc8y1w830in0q9l1zyn5i161d3cmwk15-kodi-20.1-env/share/kodi/addons/plugin.video.youtube/resources/lib/startup.py", line 11, in <module>
                                                       from youtube_plugin.kodion import service
                                                     File "/nix/store/zycslxp5fkzgnfhly0yws6mdb9zzzvrw-kodi-youtube-7.0.1/share/kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 21, in <module>
                                                       from .impl import Context
                                                     File "/nix/store/zycslxp5fkzgnfhly0yws6mdb9zzzvrw-kodi-youtube-7.0.1/share/kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/__init__.py", line 12, in <module>
                                                       from .xbmc.xbmc_context import XbmcContext as Context
                                                     File "/nix/store/zycslxp5fkzgnfhly0yws6mdb9zzzvrw-kodi-youtube-7.0.1/share/kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_context.py", line 29, in <module>
                                                       from .xbmc_playlist import XbmcPlaylist
                                                     File "/nix/store/zycslxp5fkzgnfhly0yws6mdb9zzzvrw-kodi-youtube-7.0.1/share/kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_playlist.py", line 15, in <module>
                                                       from . import xbmc_items
                                                     File "/nix/store/zycslxp5fkzgnfhly0yws6mdb9zzzvrw-kodi-youtube-7.0.1/share/kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_items.py", line 13, in <module>
                                                       from infotagger.listitem import ListItemInfoTag
                                                   ModuleNotFoundError: No module named 'infotagger'
                                                   -->End of Python script error report<--
```

### Steps To Reproduce
1. Use `pkgs.kodi-gbm.withPackages (p: with p; [ youtube ]);`
2. Start `kodi`

### Additional context
- The YouTube plugin used to work perfectly.
- https://github.com/anxdpanic/plugin.video.youtube/blame/master/addon.xml shows that the `inputstream.adaptive` dependency was added but that the `infotagger` dependency is an old one.
- The `infotagger` wrapper is here: https://github.com/jurialmunkey/script.module.infotagger

### Notify maintainers
@aanderse
@cpages
@edwtjo
@minijackson
@peterhoeg
@sephalon

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.23, NixOS, 23.05 (Stoat), 23.05.20230411.10193ca`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - nixpkgs: `/nix/store/67iks6k4id77nzqqbc1w9bi4dcghxfp6-source`
```

**Comment by aanderse** [comment]
Thanks for catching this. Looks like a pretty straight forward addon to package. Is this something you'd be interested in tackling @dschrempf?

**Comment by dschrempf** [comment]
I can, if I find the time! One thing I do not understand is that the `infotagger` library is an old one. I could see that the YouTube plugin is failing because the new dependency `inputstream.adaptive` is missing, but it seems to fail because of `infotagger` (which is also not provided, but why didn't it fail before?).

**Comment by ryantrinkle** [comment]
I have tested this and it works for me.  Thanks @dschrempf!
