### ISSUE TITLE
pythonPackages.argparse was blocking 16.09 channel update

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#22697]
## Issue description

The Python 2 package `argparse` has been blocking channel updates of 16.09 for quite some time it seems. I cannot reproduce the failure locally.

### Steps to reproduce

```
$ nix-build -A pythonPackages.argparse  https://github.com/NixOS/nixpkgs/archive/release-17.03.tar.gz
```

```
unpacking sources
unpacking source archive /nix/store/v9c3wqwkssvafncqwry8ghmvdvpnshzf-argparse-1.4.0.tar.gz
source root is argparse-1.4.0
setting SOURCE_DATE_EPOCH to timestamp 1442089334 of file argparse-1.4.0/setup.cfg
patching sources
configuring
building
Traceback (most recent call last):
  File "nix_run_setup.py", line 3, in <module>
    import setuptools
  File "/nix/store/zl2zaz6k6caq4ybc57fywh8691acrhy1-python2.7-bootstrapped-pip-8.1.2/lib/python2.7/site-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extern.six.moves import filterfalse, map
  File "/nix/store/zl2zaz6k6caq4ybc57fywh8691acrhy1-python2.7-bootstrapped-pip-8.1.2/lib/python2.7/site-packages/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
  File "/nix/store/zl2zaz6k6caq4ybc57fywh8691acrhy1-python2.7-bootstrapped-pip-8.1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import email.parser
  File "/nix/store/hm23w22w20lwgik2lmxzv02n1qys2rhz-python-2.7.13/lib/python2.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser
  File "/nix/store/hm23w22w20lwgik2lmxzv02n1qys2rhz-python-2.7.13/lib/python2.7/email/feedparser.py", line 27, in <module>
    from email import message
  File "/nix/store/hm23w22w20lwgik2lmxzv02n1qys2rhz-python-2.7.13/lib/python2.7/email/message.py", line 16, in <module>
    import email.charset
  File "/nix/store/hm23w22w20lwgik2lmxzv02n1qys2rhz-python-2.7.13/lib/python2.7/email/charset.py", line 13, in <module>
    import email.base64mime
  File "/nix/store/hm23w22w20lwgik2lmxzv02n1qys2rhz-python-2.7.13/lib/python2.7/email/base64mime.py", line 40, in <module>
    from email.utils import fix_eols
  File "/nix/store/hm23w22w20lwgik2lmxzv02n1qys2rhz-python-2.7.13/lib/python2.7/email/utils.py", line 27, in <module>
    import random
  File "/nix/store/hm23w22w20lwgik2lmxzv02n1qys2rhz-python-2.7.13/lib/python2.7/random.py", line 885, in <module>
    _inst = Random()
  File "/nix/store/hm23w22w20lwgik2lmxzv02n1qys2rhz-python-2.7.13/lib/python2.7/random.py", line 97, in __init__
    self.seed(x)
  File "/nix/store/hm23w22w20lwgik2lmxzv02n1qys2rhz-python-2.7.13/lib/python2.7/random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
OSError: [Errno 38] Function not implemented

builder for ‘/nix/store/98a4ddvjqm6xwihdmmr2j8dk1rq72hcy-python2.7-argparse-1.4.0.drv’ failed with exit code 1
```

**Comment by FRidh** [comment]
Could it be related to the grsecurity update?

http://hydra.nixos.org/api/scmdiff?rev1=d2cd8a07cfbd6e7c57a226c0798cde71304a1095&type=git&branch=&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&rev2=4f876a4a47fa15692659a6a0ca4044f91449d3eb

cc @joachifm

**Comment by RonnyPfannschmidt** [comment]
why is argparse more than a noop for any python > 2.6 - python2.7 has argparse as part of the stdlib

**Comment by FRidh** [comment]
Good point. I've pushed c901d5bc6030823ce68d1b22fd9014d35e75d016 so that should get the channel going again.

Even so, its odd this error occurs, and even worse, that I cannot reproduce it.

**Comment by vcunat** [comment]
Could it have been just some transient problem?  I have a feeling that I saw it and restarting the Hydra job fixed it.

**Comment by FRidh** [comment]
Could be. Actually, I hope so, since this change breaks `unittest2` (which I didn't expect at all), breaking a lot more other things.

**Comment by FRidh** [comment]
I've reverted this on both 16.09 and staging.

**Comment by RonnyPfannschmidt** [comment]
@FRidh since unittest2 has a python2.6 only dependency on argparse, it may help to make argparse a python 2.6 only dependency at first

**Comment by RonnyPfannschmidt** [comment]
taking a quick looks, im also under the impression that most things that depend on argparse are unmaintained messes

**Comment by FRidh** [comment]
> since unittest2 has a python2.6 only dependency on argparse, it may help to make argparse a python 2.6 only dependency at first

that's not what the `setup.py` says though.

> taking a quick looks, im also under the impression that most things that depend on argparse are unmaintained messes

Yep...

**Comment by RonnyPfannschmidt** [comment]
sorry, i checked with pypi again, and its indeed not there - the hg repo i took a look at had it tho

this is quite unfortunate

**Comment by FRidh** [comment]
@RonnyPfannschmidt we can apply the patch that is in the repo

**Comment by RonnyPfannschmidt** [comment]
https://hg.python.org/unittest2/rev/d091f0086b03

**Comment by FRidh** [comment]
The channel has updated. Even though, I am wondering what actually caused it. Furthermore, we need to get rid of these old packages https://github.com/NixOS/nixpkgs/issues/22701

**Comment by vcunat** [comment]
`ENOSYS` is a really strange code for a transient error.  I'm used to errors pointing to resource exhaustion, such as fork being denied, out-of-space, etc.
