### ISSUE TITLE
tuxguitar fails to start

### ISSUE THREAD

**Issue by rumpelsepp** [NixOS/nixpkgs#227206]
### Describe the bug

Tuxguitar fails to start on `nixpkgs-unstable`, Gnome.

### Steps To Reproduce

```
$ tuxguitar
Invalid MIT-MAGIC-COOKIE-1 keyorg.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
        at org.eclipse.swt.SWT.error(SWT.java:4517)
        at org.eclipse.swt.widgets.Display.createDisplay(Display.java:908)
        at org.eclipse.swt.widgets.Display.create(Display.java:892)
        at org.eclipse.swt.graphics.Device.<init>(Device.java:156)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:512)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:503)
        at org.herac.tuxguitar.ui.swt.SWTApplication.createDisplay(SWTApplication.java:73)
        at org.herac.tuxguitar.ui.swt.SWTApplication.<init>(SWTApplication.java:18)
        at org.herac.tuxguitar.ui.swt.SWTApplicationFactory.createApplication(SWTApplicationFactory.java:9)
        at org.herac.tuxguitar.app.ui.TGApplication.<init>(TGApplication.java:27)
        at org.herac.tuxguitar.app.ui.TGApplication$1.createInstance(TGApplication.java:64)
        at org.herac.tuxguitar.app.ui.TGApplication$1.createInstance(TGApplication.java:62)
        at org.herac.tuxguitar.util.singleton.TGSingletonUtil.getInstance(TGSingletonUtil.java:12)
        at org.herac.tuxguitar.app.ui.TGApplication.getInstance(TGApplication.java:62)
        at org.herac.tuxguitar.app.synchronizer.TGSynchronizerControllerImpl.<init>(TGSynchronizerControllerImpl.java:18)
        at org.herac.tuxguitar.app.TuxGuitar.createUIContext(TuxGuitar.java:114)
        at org.herac.tuxguitar.app.TuxGuitar.createApplication(TuxGuitar.java:100)
        at org.herac.tuxguitar.app.TGMainSingleton.launchTuxGuitar(TGMainSingleton.java:57)
        at org.herac.tuxguitar.app.TGMainSingleton.launchSingleton(TGMainSingleton.java:45)
        at org.herac.tuxguitar.app.TGMainSingleton.main(TGMainSingleton.java:35)
```

### Notify maintainers

@ardumont 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.04 MiB unpacked):
  /nix/store/viwmk7z6fxrd1xc09dximdk3w37kx1qn-stdenv-linux
copying path '/nix/store/viwmk7z6fxrd1xc09dximdk3w37kx1qn-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.10, NixOS, 23.05 (Stoat), 23.05.20230417.f00994e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bjornfor** [comment]
`tuxguitar` works for me[1] on NixOS 22.11 and unstable. Running GNOME.

[1] GUI opens, no errors from stdout/stderr.

**Comment by lhanson** [comment]
Stable works for me, unstable fails to start and provides no output:

```shell
$ tuxguitar
$ echo $?
0
$  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.96, NixOS, 23.11 (Tapir), 23.11.20240709.205fd42`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by c31io** [comment]
Failed to start on unstable. Error message:
```
which: no java in (/run/wrappers/bin:/home/c31io/.nix-profile/bin:/nix/profile/bin:/home/c31io/.local/state/nix/profile/bin:/etc/profiles/per-user/c31io/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin)
/nix/store/63liy12zpnqrn27ddk9dcv0w0x5c2jcw-tuxguitar-1.6.4/bin/.tuxguitar-wrapped: line 20: -Xmx512m: command not found
```
Program wrapper is breached by a `which java` introduced in version 1.6.1:
https://github.com/helge17/tuxguitar/blob/1.6.4/desktop/build-scripts/common-resources/common-linux/tuxguitar.sh
