### ISSUE TITLE
qutebrowser-qt6: crash on startup

### ISSUE THREAD

**Issue by dschrempf** [NixOS/nixpkgs#227275]
### Describe the bug
Qutebrowser crashes during startup with the following error message:

```
Traceback (most recent call last):
  File "/nix/store/lsj64m90fd43ljnasaw98z1kij7cqy3i-qutebrowser-unstable-2023-03-19/bin/.qutebrowser-wrapped", line 34, in <module>
    sys.exit(load_entry_point('qutebrowser==2.5.4', 'gui_scripts', 'qutebrowser')())
  File "/nix/store/lsj64m90fd43ljnasaw98z1kij7cqy3i-qutebrowser-unstable-2023-03-19/lib/python3.10/site-packages/qutebrowser/qutebrowser.py", line 245, in main
    return app.run(args)
  File "/nix/store/lsj64m90fd43ljnasaw98z1kij7cqy3i-qutebrowser-unstable-2023-03-19/lib/python3.10/site-packages/qutebrowser/app.py", line 95, in run
    app = Application(args)
  File "/nix/store/lsj64m90fd43ljnasaw98z1kij7cqy3i-qutebrowser-unstable-2023-03-19/lib/python3.10/site-packages/qutebrowser/app.py", line 552, in __init__
    qt_args = qtargs.qt_args(args)
  File "/nix/store/lsj64m90fd43ljnasaw98z1kij7cqy3i-qutebrowser-unstable-2023-03-19/lib/python3.10/site-packages/qutebrowser/config/qtargs.py", line 86, in qt_args
    argv += list(_qtwebengine_args(versions, namespace, special_flags))
  File "/nix/store/lsj64m90fd43ljnasaw98z1kij7cqy3i-qutebrowser-unstable-2023-03-19/lib/python3.10/site-packages/qutebrowser/config/qtargs.py", line 284, in _qtwebengine_args
    enabled_features, disabled_features = _qtwebengine_features(versions, special_flags)
  File "/nix/store/lsj64m90fd43ljnasaw98z1kij7cqy3i-qutebrowser-unstable-2023-03-19/lib/python3.10/site-packages/qutebrowser/config/qtargs.py", line 101, in _qtwebengine_features
    assert versions.chromium_major is not None
AssertionError
```

### Steps To Reproduce
```
nix run github:NixOS/nixpkgs/nixos-unstable-small#qutebrowser-qt6
```

### Additional context
The `qutebrowser-qt6` derivation did not change for a while, and so I expect the reason is some changes in `qt6.qtwebengine`. 

### Notify maintainers
@jagajaga
@rnhmjoj
@ebzzry
@dotlambda
@nrdxp

### Metadata
`nixos-unstable-small` commit hash: https://github.com/NixOS/nixpkgs/commit/cafa2f02fbbcade5c5c257c190061da555d90913
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.24, NixOS, 23.05 (Stoat), 23.05.20230417.061715a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - nixpkgs: `/nix/store/q6m43p7pgx6c5ikxbwf4mpjl72m12wrh-source````

**Comment by wegank** [comment]
> ### Additional context
> The `qutebrowser-qt6` derivation did not change for a while, and so I expect the reason is some changes in `qt6.qtwebengine`.

Yes, Qt 6.5.0 comes with a huge Chromium version jump.

It's probably time to tag the PyQt6 maintainers? These packages are still at version 6.4 IIRC.
