### ISSUE TITLE
Hyper fails with `innerError Error: Cannot find module '../build/Debug/pty.node'`

### ISSUE THREAD

**Issue by jankaifer** [NixOS/nixpkgs#227872]
### Describe the bug

I updated to latest `nixos-unstable` and I'm not able to run `hyper` anymore, I get this:

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js
- /nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js
- /nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/ui/window.js
- /nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js',
    '/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/ui/window.js',
    '/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/index.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js:39:34)
    at Object.<anonymous> (/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js:46:11)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

### Steps To Reproduce
1. install `hyper` with the latest `nixos-unstable`

### Notify maintainers

cc @puffnfresh @FabianGD 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.12, NixOS, 23.05 (Stoat), 23.05.git.6c43a3495a1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/persist/home/pearman/dev/jankaifer/nixos/modules/nixpkgs`
```

**Comment by jankaifer** [comment]
There is already one quite old hyper issue, but that seems to be unrelated: https://github.com/NixOS/nixpkgs/issues/105961

**Comment by jankaifer** [comment]
Oh so the issue actually is with `Release/pty.node`, and that debug is just a fallback:

https://github.com/microsoft/node-pty/blob/7217b42f1189cc9969f0633348850f9d61eb1bd1/src/unixTerminal.ts#L15-L27

**Comment by jankaifer** [comment]
Oh, It rethrows the original error, so the relevant part of the log is just this:

```
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js:39:34)
    at Object.<anonymous> (/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js:46:11)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/nix/store/w7xdsx4cpzvvlp2c85k89l1lgvn42mnl-hyper-3.4.1/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by jankaifer** [comment]
That was already mentioned in the original issue, will close this as a duplicate.
