### ISSUE TITLE
nginx module: fails to generate config containing non ascii characters

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#22883]
## Issue description
German Umlaut in supplied verbatim nginx config causes build to fail.
Issue introduced with commit e362a3d5c94ba379d428fbd2cc40470719a61556 (@Baughn)

```
these derivations will be built:
  /nix/store/8j94mkvz2ixcnwpd2sxka59jv3ykcmxi-nginx.conf.drv
  /nix/store/p60wl0b03w8bh8fhpqpfv4m2syfq4f4l-unit-script.drv
  /nix/store/b9sznpl8jv76fd6m49hay88yj8y2187c-unit-nginx.service.drv
  /nix/store/d5z88mx4am95sywc0bgrpgsi3sy1wksf-system-units.drv
  /nix/store/6zh9jbr7k8yyqsza7p3invz205a51xca-etc.drv
  /nix/store/pfdibp71jpm0rp8al52rnggb33kwhini-nixos-system-unnamed-17.03pre-git.drv
  /nix/store/jxchka3kalga7nzgmq75d2256ypagiyg-azure-image.drv
building path(s) ‘/nix/store/dsdjiyk6sggbgy3v7x5kw0qxibh2248q-nginx.conf’
Traceback (most recent call last):
  File "/nix/store/3f5x8q6j7a6cs78wzw3bidc97xvpmp6j-nginx-config-formatter-2016-06-16/bin/nginxfmt", line 104, in <module>
    original_file_content = config_file.read()
  File "/nix/store/plg35wicknz82iijqwc742803f8y3wva-python3-3.5.3/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2781: ordinal not in range(128)
builder for ‘/nix/store/8j94mkvz2ixcnwpd2sxka59jv3ykcmxi-nginx.conf.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/b9sznpl8jv76fd6m49hay88yj8y2187c-unit-nginx.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/d5z88mx4am95sywc0bgrpgsi3sy1wksf-system-units.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/6zh9jbr7k8yyqsza7p3invz205a51xca-etc.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/pfdibp71jpm0rp8al52rnggb33kwhini-nixos-system-unnamed-17.03pre-git.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/jxchka3kalga7nzgmq75d2256ypagiyg-azure-image.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/jxchka3kalga7nzgmq75d2256ypagiyg-azure-image.drv’ failed

```

### Steps to reproduce

```
      services.nginx.config = ''
        http {
            server {
                listen 80 default_server;
                server_name example.com;

                # redirect auf https://www....
                location / {
                  return 301 https://www.example.com$request_uri;
                }

                # Statusseite für Monitoring freigeben
                # line above contains german umlaut causing problems
                location /nginx_status {
                  stub_status on;
                  access_log off;
                  allow 127.0.0.1;
                  deny all;
                }
            }
        }
      '';
```

**Comment by Baughn** [comment]
I've reported this upstream. Not sure the guy who wrote it is still around, though.

**Comment by globin** [comment]
I'll revert temporarily

**Comment by BjornMelgaard** [comment]
Have same error

**Comment by nh2** [comment]
@Baughn what's the state of this? The upstream issue sounds like there's no bug.

> Have same error

@BjornMelgaard Which error? The commit was reverted 9 months before you posted, so not sure what you're referring to.

I would really like to get formatted nginx configs, it's very hard to debug a running nginx and figure out why it reacts a certain way using just SSH to the server when it's all on one level.

And the formatting should probably be made optional, so that those that don't like it are also accomodated for: https://github.com/NixOS/nixpkgs/commit/e362a3d5c94ba379d428fbd2cc40470719a61556#commitcomment-20787179

**Comment by Baughn** [comment]
A commit was added that should fix this, and then I lost track of this issue while waiting for a new release. I'll take a poke.

**Comment by Baughn** [comment]
@globin, can you reopen this issue?

**Comment by Baughn** [comment]
https://github.com/NixOS/nixpkgs/pull/34985
