### ISSUE TITLE
`weechat-otr` fails on nixpkgs-unstable (Python 3.10)

### ISSUE THREAD

**Issue by pzant** [NixOS/nixpkgs#229690]
### Describe the bug
The `weechat` plugin `weechat-otr` fails to load.

### Steps To Reproduce
1. Activate `weechat-otr` plugin.
2. Start `weechat`.

The following error is thrown:
```
 python: loading script "/nix/store/y0w5d975x1yghqi30yrbizw5nsw2pblg-weechat-otr-1.9.2/share/weechat_otr.py"
  python: stdout/stderr (?): Traceback (most recent call last):
  python: stdout/stderr (?):   File "/nix/store/y0w5d975x1yghqi30yrbizw5nsw2pblg-weechat-otr-1.9.2/share/weechat_otr.py", line 46, in <module>
  python: stdout/stderr (?):     import potr
  python: stdout/stderr (?):   File "/nix/store/xkmcws2sl1hhl97s9ihc5n3r3jp7z2lj-weechat-otr-env/lib/python3.10/site-packages/potr/__init__.py", line 21, in <module>
  python: stdout/stderr (?):     from potr import context
  python: stdout/stderr (?):   File "/nix/store/xkmcws2sl1hhl97s9ihc5n3r3jp7z2lj-weechat-otr-env/lib/python3.10/site-packages/potr/context.py", line 43, in <module>
  python: stdout/stderr (?):     from potr import crypt
  python: stdout/stderr (?):   File "/nix/store/xkmcws2sl1hhl97s9ihc5n3r3jp7z2lj-weechat-otr-env/lib/python3.10/site-packages/potr/crypt.py", line 25, in <module>
  python: stdout/stderr (?):     from potr.compatcrypto import SHA256, SHA1, SHA1HMAC, SHA256HMAC, \
  python: stdout/stderr (?):   File "/nix/store/xkmcws2sl1hhl97s9ihc5n3r3jp7z2lj-weechat-otr-env/lib/python3.10/site-packages/potr/compatcrypto/__init__.py", line 21, in <module>
  python: stdout/stderr (?):     from potr.compatcrypto.pycrypto import *
  python: stdout/stderr (?):   File "/nix/store/xkmcws2sl1hhl97s9ihc5n3r3jp7z2lj-weechat-otr-env/lib/python3.10/site-packages/potr/compatcrypto/pycrypto.py", line 27, in <module>
  python: stdout/stderr (?):     from Crypto.PublicKey import DSA
  python: stdout/stderr (?):   File "/nix/store/xkmcws2sl1hhl97s9ihc5n3r3jp7z2lj-weechat-otr-env/lib/python3.10/site-packages/Crypto/PublicKey/DSA.py", line 88, in <module>
  python: stdout/stderr (?):     from Crypto.PublicKey import _DSA, _slowmath, pubkey
  python: stdout/stderr (?):   File "/nix/store/xkmcws2sl1hhl97s9ihc5n3r3jp7z2lj-weechat-otr-env/lib/python3.10/site-packages/Crypto/PublicKey/_DSA.py", line 53
  python: stdout/stderr (?):     if pow(2,159L) < q < pow(2,160L):
  python: stdout/stderr (?):                ^
  python: stdout/stderr (?): SyntaxError: invalid decimal literal
 python: unable to parse file "/nix/store/y0w5d975x1yghqi30yrbizw5nsw2pblg-weechat-otr-1.9.2/share/weechat_otr.py"
```

### Notify maintainers
@oxzi 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.12-zen1, NixOS, 23.05 (Stoat), 23.05pre480050.1a411f23ba2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by oxzi** [comment]
Unfortunately, `weechat-otr` and its required crypto module is kind of outdated. This has resulted in the [`knownVulnerabilites`](https://github.com/NixOS/nixpkgs/blob/50a183182d7ae39133555414d48d5d609a28a57d/pkgs/applications/networking/irc/weechat/scripts/weechat-otr/default.nix#L72-L75).

If anyone wants to create (upstream) patches, I'd be happy to take another look.

**Comment by pzant** [comment]
```
unpacking 1 channels...
building the system configuration...
error: builder for '/nix/store/1v31g2lwwqxg5yi6r618z8nvlid6i79n-python3.12-pycrypto-2.6.1-13.1.drv' failed with exit code 1;
       last 25 log lines:
       >         Please consider removing the following classifiers in favor of a SPDX license expression:
       >
       >         License :: Public Domain
       >
       >         See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
       >         ********************************************************************************
       >
       > !!
       >   self._finalize_license_expression()
       > In file included from /nix/store/8w718rm43x7z73xhw9d6vh8s4snrq67h-python3-3.12.10/include/python3.12/Python.h:87,
       >                  from src/_fastmath.c:31:
       > /nix/store/8w718rm43x7z73xhw9d6vh8s4snrq67h-python3-3.12.10/include/python3.12/cpython/pytime.h:216:60: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
       >   216 | PyAPI_FUNC(int) _PyTime_FromTimespec(_PyTime_t *tp, struct timespec *ts);
       >       |                                                            ^~~~~~~~
       > /nix/store/8w718rm43x7z73xhw9d6vh8s4snrq67h-python3-3.12.10/include/python3.12/cpython/pytime.h:221:56: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
       >   221 | PyAPI_FUNC(int) _PyTime_AsTimespec(_PyTime_t t, struct timespec *ts);
       >       |                                                        ^~~~~~~~
       > /nix/store/8w718rm43x7z73xhw9d6vh8s4snrq67h-python3-3.12.10/include/python3.12/cpython/pytime.h:225:63: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
       >   225 | PyAPI_FUNC(void) _PyTime_AsTimespec_clamp(_PyTime_t t, struct timespec *ts);
       >       |                                                               ^~~~~~~~
       > src/_fastmath.c:33:10: fatal error: longintrepr.h: No such file or directory
       >    33 | #include <longintrepr.h>                                /* for conversions */
       >       |          ^~~~~~~~~~~~~~~
       > compilation terminated.
       > error: command '/nix/store/0fsnicvfpf55nkza12cjnad0w84d6ba7-gcc-wrapper-14.2.1.20250322/bin/gcc' failed with exit code 1
       For full logs, run:
         nix log /nix/store/1v31g2lwwqxg5yi6r618z8nvlid6i79n-python3.12-pycrypto-2.6.1-13.1.drv
error: 1 dependencies of derivation '/nix/store/0rvh4a29jjf7ivciqg89sd3g0n2wkn5v-weechat-otr-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/minckp6dj353kpcal081vg8i08slih91-libpath.patch.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rjmf7n65rq7mj3qwa0jhk6dd73662kql-weechat-otr-1.9.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/h1kgkr23h4aswiva3d899r2dyk53d7yn-weechat-headless.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dk1d3rml4m1351ahvs6g1hmzxdj9hgiz-weechat-bin-env-4.6.3.drv' failed to build
```
