### ISSUE TITLE
Flask-Login: Exception during build

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#22978]
## Issue description

I tried to install this package because it uses nose and i have problems packaging a package that uses nose too. But here is a different issue than https://github.com/nose-devs/nose/issues/1037 .

```
...
patching script interpreter paths in /nix/store/0jpp643y7yfxknzxlbd2l5a6b9z3zgjx-python3.5-Flask-Login-0.4.0
running install tests
..........................................[2017-02-19 00:36:48,962] ERROR in app: Exception on /login-notch-remember [GET]
Traceback (most recent call last):
  File "/tmp/nix-build-python3.5-Flask-Login-0.4.0.drv-0/flask-login-0.4.0-src/flask_login/login_manager.py", line 405, in _set_cookie
    expires = datetime.utcnow() + duration
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/sgr18sag2b2q4myi4g0bbqmk8j3aihsv-python3.5-flask-0.12/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/nix/store/sgr18sag2b2q4myi4g0bbqmk8j3aihsv-python3.5-flask-0.12/lib/python3.5/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/nix/store/sgr18sag2b2q4myi4g0bbqmk8j3aihsv-python3.5-flask-0.12/lib/python3.5/site-packages/flask/app.py", line 1632, in finalize_request
    response = self.process_response(response)
  File "/nix/store/sgr18sag2b2q4myi4g0bbqmk8j3aihsv-python3.5-flask-0.12/lib/python3.5/site-packages/flask/app.py", line 1856, in process_response
    response = handler(response)
  File "/tmp/nix-build-python3.5-Flask-Login-0.4.0.drv-0/flask-login-0.4.0-src/flask_login/login_manager.py", line 384, in _update_remember_cookie
    self._set_cookie(response)
  File "/tmp/nix-build-python3.5-Flask-Login-0.4.0.drv-0/flask-login-0.4.0-src/flask_login/login_manager.py", line 409, in _set_cookie
    duration))
Exception: REMEMBER_COOKIE_DURATION must be a datetime.timedelta, instead got: 123
...............................................
----------------------------------------------------------------------
Ran 89 tests in 1.466s

OK
building path(s) ‘/nix/store/cnvwg8k66x50w9hk1b2ilq7axygyp6wc-user-environment’
created 2 symlinks in user environment
```

### Steps to reproduce

1. have nixpkgs master checked out
2. install Flask-Login for python 3: `nix-env -i python3.5-Flask-Login-0.4.0 -f ~/nixpkgs/`

`python2.7-Flask-Login-0.4.0` has no problems.

@Mic92 

## Technical details

* System: NixOS 16.09.1698.2da8a5d (Flounder) and OS X 10.10.5
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 7274fc32d2af261f2d0884152140a821b005b56f

**Comment by FRidh** [comment]
Sounds like a broken test. This is an issue for upstream (Flask-Login) to fix. Until then, you might want to disable this single test in the Nixpkgs expression using the NOSE_EXCLUDE env variable. Grep Nixpkgs for this env var and you will see it is used several times.

**Comment by FRidh** [comment]
cc maintainer @abbradar

**Comment by davidak** [comment]
Not reproducible anymore in 17.09 channel and on master.
