### ISSUE TITLE
Build failure: onagre

### ISSUE THREAD

**Issue by jfvillablanca** [NixOS/nixpkgs#230604]
### Steps To Reproduce

1. `nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz -p onagre --run onagre`

### Build log

```
these 3 paths will be fetched (4.29 MiB download, 15.32 MiB unpacked):
  /nix/store/1ksy5354710dyaidw6l7s77plr8sn2x2-libpng-apng-1.6.39
  /nix/store/c0s9cv2xlz1hzichcp0cvrvc27z0c9v0-freetype-2.13.0
  /nix/store/c6484l9wbfkm03mq00mfn2hwk4zr35pc-onagre-1.0.0-alpha.0
copying path '/nix/store/1ksy5354710dyaidw6l7s77plr8sn2x2-libpng-apng-1.6.39' from 'https://cache.nixos.org'...
copying path '/nix/store/c0s9cv2xlz1hzichcp0cvrvc27z0c9v0-freetype-2.13.0' from 'https://cache.nixos.org'...
copying path '/nix/store/c6484l9wbfkm03mq00mfn2hwk4zr35pc-onagre-1.0.0-alpha.0' from 'https://cache.nixos.org'...
Failed to parse theme:
Failed to open config file
Failing back to default theme
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libX11.so.6: cannot open shared object file: No such file or directory); opening library failed (libX11.so: cannot open shared object file: No such file or directory)" })', /build/cargo-vendor-dir/winit-0.26.1/src/platform_impl/linux/mod.rs:619:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

### Additional context

The GUI library used by [onagre](https://github.com/oknozor/onagre), [iced](https://github.com/iced-rs/iced), has library dependencies that are not readily available in NixOS. The package compiles but it panics at runtime.

Relevant issues that mention the problem
https://github.com/iced-rs/iced/issues/677
https://github.com/iced-rs/iced/issues/256
https://github.com/iced-rs/iced/issues/333

### Notify maintainers
@jfvillablanca 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.27, NixOS, 23.05 (Stoat), 23.05.20230506.897876e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by jfvillablanca** [comment]
I don't know what the dependencies are so I am spraying and praying my build inputs

```nix
{ lib
, rustPlatform
, fetchFromGitHub
, cmake
, pkgconfig
, freetype
, expat
, fontconfig
, gperf
, libGL
, libxkbcommon
, vulkan-headers
, vulkan-loader
, vulkan-tools
, wayland
, wayland-protocols
, swiftshader
, xorg
}:

rustPlatform.buildRustPackage rec {
  pname = "onagre";
  version = "1.0.0-alpha.0";

  src = fetchFromGitHub {
    owner = "oknozor";
    repo = pname;
    rev = version;
    hash = "sha256-hP+slfCWgsTgR2ZUjAmqx9f7+DBu3MpSLvaiZhqNK1Q=";
  };

  cargoLock = {
    lockFile = ./Cargo.lock;
    outputHashes = {
      "pop-launcher-1.2.1" = "sha256-LeKaJIvooD2aUlY113P0mzxOcj63sGkrA0SIccNqCLY=";
    };
  };

  cargoSha256 = "sha256-IOhAGrAiT2mnScNP7k7XK9CETUr6BjGdQVdEUvTYQT4=";

  postPatch = ''
    cp ${./Cargo.lock} Cargo.lock
  '';

  nativeBuildInputs = [ cmake pkgconfig ];
  buildInputs = [
    freetype
    expat
    fontconfig
    gperf
    libGL
    libxkbcommon
    vulkan-headers
    vulkan-loader
    vulkan-tools
    wayland
    wayland-protocols
    swiftshader
  ] ++ (with xorg; [
    libX11
    libXcursor
    libXi
    libXrandr
    libxcb
  ]);

  LD_LIBRARY_PATH = "${lib.makeLibraryPath buildInputs}";

  meta = with lib; {
    description = "A general purpose application launcher for X and wayland inspired by rofi/wofi and alfred";
    homepage = "https://github.com/oknozor/onagre";
    license = licenses.mit;
    maintainers = [ maintainers.jfvillablanca ];
    platforms = platforms.linux;
  };
}
```

I have a new panic error, so a step in the right direction (?) maybe

```console
[user@system:~]$ RUST_BACKTRACE=1 ./result/bin/onagre
Failed to parse theme:
Failed to open config file
Failing back to default theme
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Other, error: "could not acquire lock on \"/home/jmfv/.local/share/onagre/db\": Os { code: 11, kind: WouldBlock, message: \"Resource temporarily unavailable\" }" })', src/db/mod.rs:29:37
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: onagre::app::run
   4: onagre::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by a-kenji** [comment]
Onagre has `pop-launcher` as a runtime dependency.

**Comment by jfvillablanca** [comment]
I tried compiling it with `pop-launcher` as one of the `buildInputs` (then `propagatedBuildInputs`). The issue remains, unfortunately.

**Comment by a-kenji** [comment]
```
It looks like this fails:
```
        Database {
            inner: sled::open(path).unwrap(),
        }
```
Have you tried deleting the `db`, maybe it is in a weird state?

**Comment by jfvillablanca** [comment]
How were you able to get that? How can i delete the database? I'm not familiar with the code. Can I ask for some pointers on how you inferred the point of failure so I can investigate accordingly? Thank you

**Comment by a-kenji** [comment]
The panic message:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Other, error: "could not acquire lock on \"/home/jmfv/.local/share/onagre/db\": Os { code: 11, kind: WouldBlock, message: \"Resource temporarily unavailable\" }" })', src/db/mod.rs:29:37
```

It shows there is an error at:
`/home/jmfv/.local/share/onagre/db`, the error is: `Os { code: 11, kind: WouldBlock, message: \"Resource temporarily unavailable\" }" }`

The line in the project is: 
```
src/db/mod.rs:29:37
```

The corresponding line in `onagre` is:
https://github.com/oknozor/onagre/blob/8d4ffe9f7f38cb2d1eb3023a128856c209100cf1/src/db/mod.rs#L29

It shows this:
```
        Database {
            inner: sled::open(path).unwrap(),
        }
```

Sled is a library for a mostly in memory database. The unwrap here makes the application crash, because `sled::open(path)` returns an error.
I'm not sure what the error is, but maybe you can alleviate it with:

```
rm /home/jmfv/.local/share/onagre/db
```
This will delete the database.

**Comment by jfvillablanca** [comment]
Gotcha, I follow where you're going.
Oddly enough, I was not able to replicate that `db` error and I used the code here https://github.com/NixOS/nixpkgs/issues/230604#issuecomment-1537669632 

This was the new error:
```console
[user@system:~]$ RUST_BACKTRACE=full ./result/bin/onagre
Failed to parse theme:
Failed to open config file
Failing back to default theme
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/app/subscriptions/pop_launcher.rs:78:14
stack backtrace:
   0:     0x56330694291c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1792633461806265
   1:     0x5633065f2fae - core::fmt::write::h86858dfe747be413
   2:     0x563306957dd4 - std::io::Write::write_fmt::h74e0842d6f1ebf1a
   3:     0x5633069426ef - std::sys_common::backtrace::print::h18201883e81727b4
   4:     0x5633069581af - std::panicking::default_hook::{{closure}}::he7684422edfb8e5d
   5:     0x563306958de1 - std::panicking::rust_panic_with_hook::hb89fb9ee5a2c564f
   6:     0x563306942c84 - std::panicking::begin_panic_handler::{{closure}}::hc641e1ce95f25c1f
   7:     0x563306942be6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6a9bb70d00ab18d8
   8:     0x563306958681 - rust_begin_unwind
   9:     0x5633063e5a52 - core::panicking::panic_fmt::h71a20a5609c5aabf
  10:     0x5633063e5ee2 - core::result::unwrap_failed::h44ca259f10509f8c
  11:     0x56330653df89 - <onagre::app::subscriptions::pop_launcher::PopLauncherSubscription as iced_futures::subscription::Recipe<H,I>>::stream::h7fcf580e3fe90633
  12:     0x56330644c42a - <iced_futures::subscription::Map<H,E,A,B> as iced_futures::subscription::Recipe<H,E>>::stream::hc87b7105e53f04c9
  13:     0x56330644dbb3 - iced_futures::runtime::Runtime<Hasher,Event,Executor,Sender,Message>::track::h18aa28765cefc295
  14:     0x563306544b2e - onagre::app::run::h0bc5a1f1348a8441
  15:     0x5633065743ca - onagre::main::h7b9e2de1c5bfe731
  16:     0x563306471203 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6298e3476a961586
  17:     0x56330657db60 - main
  18:     0x7f121bbb6ace - __libc_start_call_main
  19:     0x7f121bbb6b89 - __libc_start_main@@GLIBC_2.34
  20:     0x5633064262b5 - _start
  21:                0x0 - <unknown>

```

I checked the relevant line from source

```rust
fn stream(self: Box<Self>, _: BoxStream<I>) -> BoxStream<Self::Output> {
    debug!("Starting `pop-launcher` subscription");
    let child = Command::new("pop-launcher")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())         
        .spawn()
        .unwrap();
```
So `pop-launcher` is not in the PATH.

So I added `makeWrapper` to the `nativeBuildInputs` and `pop-launcher` to a `postFixup`:

```nix
postFixup = ''
  wrapProgram "$out/bin/${pname}" \
    --prefix PATH : "${lib.makeBinPath [ pop-launcher ]}"
'';
```

Compiling and running it again:
```console
[user@system:~]$ RUST_BACKTRACE=full ./result/bin/onagre
Failed to parse theme:
Failed to open config file
Failing back to default theme
Error: GraphicsAdapterNotFound
```

I'm assuming this must be the same Vulkan library problem mentioned here: https://github.com/iced-rs/iced/issues/677
