### ISSUE TITLE
Package request: zwave-js-ui

### ISSUE THREAD

**Issue by Thra11** [NixOS/nixpkgs#230686]
**Project description**

"Full featured Z-Wave Control Panel UI and MQTT gateway. Built using Nodejs, and Vue/Vuetify"

I want to try to use the ZWave-JS MQTT gateway with domoticz, as the library which I currently use with domoticz, OpenZWave, is unmaintained / abandoned.

I tried writing my own nix package using mkYarnPackage, but I just got a cryptic error which I didn't understand (not sure if mkYarnPackage is even the right approach?)

**Metadata**

* homepage URL: https://zwave-js.github.io/zwave-js-ui/#/
* source URL: https://github.com/zwave-js/zwave-js-ui/
* license: mit
* platforms: linux, not sure about any others

**Comment by Thra11** [comment]
My unsuccessful attempt at a package: https://github.com/Thra11/nixpkgs/commit/0a7cdd5dafb7e69933661ed17a145bf496f5b996

The error I get when I run `nix build`:
```
/nix/store/hiyvsgkszm1g378yn2d17jckrpmr42zv-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/@yarnpkg/lockfile/index.js:5064
    throw new SyntaxError(`${msg} ${this.token.line}:${this.token.col} in ${this.fileLoc}`);
    ^

SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile
    at Parser.unexpected (/nix/store/hiyvsgkszm1g378yn2d17jckrpmr42zv-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/@yarnpkg/lockfile/index.js:5064:11)
    at Parser.parse (/nix/store/hiyvsgkszm1g378yn2d17jckrpmr42zv-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/@yarnpkg/lockfile/index.js:5193:14)
    at parse (/nix/store/hiyvsgkszm1g378yn2d17jckrpmr42zv-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/@yarnpkg/lockfile/index.js:5262:17)
    at module.exports.exports.default (/nix/store/hiyvsgkszm1g378yn2d17jckrpmr42zv-yarn2nix-1.0.0/libexec/yarn2nix/node_modules/@yarnpkg/lockfile/index.js:4835:96)
    at Object.<anonymous> (/nix/store/hiyvsgkszm1g378yn2d17jckrpmr42zv-yarn2nix-1.0.0/libexec/yarn2nix/deps/yarn2nix/bin/yarn2nix.js:48:23)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

Node.js v18.16.0
```

**Comment by presto8** [comment]
Caused by v2 yarn.lock I think, see #148042
