### ISSUE TITLE
Torchrun does not have propagatedBuiltInputs in its PYTHONPATH

### ISSUE THREAD

**Issue by hinshun** [NixOS/nixpkgs#231349]
### Describe the bug
When building `nixpkgs#python3Packages.torch`, it has a `bin/torchrun` that fails with the following:
```sh
Traceback (most recent call last):
  File "/nix/store/bi4fmk1kv9jczyy5iwk39gr956810bk1-python3.10-torch-2.0.0/bin/.torchrun-wrapped", line 6, in <module>
    from torch.distributed.run import main
  File "/nix/store/bi4fmk1kv9jczyy5iwk39gr956810bk1-python3.10-torch-2.0.0/lib/python3.10/site-packages/torch/__init__.py", line 1122, in <module>
    from .serialization import save, load
  File "/nix/store/bi4fmk1kv9jczyy5iwk39gr956810bk1-python3.10-torch-2.0.0/lib/python3.10/site-packages/torch/serialization.py", line 17, in <module>
    from typing_extensions import TypeAlias  # Python 3.10+
ModuleNotFoundError: No module named 'typing_extensions'
```

But `typing_extensions` is in the derivation's `propagatedBuildInputs`:
https://github.com/NixOS/nixpkgs/blob/0af87b4399ec344cafe5bd7b490dc23f7c6aaf41/pkgs/development/python-modules/torch/default.nix#L304

I investigated, and the crux of the problem is that the `python3Packages.torch` derivation has a `dev` output, which places `nix-support/propagated-build-inputs` into the `dev` output. The `wrapPythonPrograms` setup hook that runs for the `out` output for `bin/torchrun` depends on this file existing to build the `program_PYTHONPATH` but since its in the `dev` output it doesn't build the correct PYTHONPATH.

This doesn't just affect `python3Packages.torch` but any call to `buildPythonPackage` that has binaries in `bin/*` and a `dev` output.

### Steps To Reproduce
1. `$(nix build --print-out-paths --no-link "nixpkgs#python3Packages.torch")/bin/torchrun`

### Expected behavior
No PYTHONPATH related errors.

### Additional context
Somewhat related issue: https://github.com/NixOS/nixpkgs/issues/83667

### Notify maintainers
@teh @thoughtpolice @tscholak

**Comment by clotodex** [comment]
Also facing a version of this
```
Traceback (most recent call last):
  File "/nix/store/0xkyni1ik0pnqi3wlb3v666k3ap34qca-python3.13-torch-2.8.0/bin/.torchrun-wrapped", line 6, in <module>
    from torch.distributed.run import main
  File "/nix/store/0xkyni1ik0pnqi3wlb3v666k3ap34qca-python3.13-torch-2.8.0/lib/python3.13/site-packages/torch/__init__.py", line 35, in <module>
    from typing_extensions import ParamSpec as _ParamSpec
ModuleNotFoundError: No module named 'typing_extensions'
```
