### ISSUE TITLE
GTK apps not working

### ISSUE THREAD

**Issue by hanckmann** [NixOS/nixpkgs#233186]
### Describe the bug
I was trying to improve my audio handling, and therefore I installed a few tools including `mictray` and `volctl`.
When starting both give a similar error:

```console
 Gtk-CRITICAL **: 10:48:30.345: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

To be more precise:
```console
~  ➜ volctl 
PulseAudio: Connection ready

(.volctl-wrapped:2377): Gtk-CRITICAL **: 10:48:30.345: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
^CTraceback (most recent call last):
  File "/nix/store/xr1jiqfxlq8sr52fa3vw0i32z288vqrl-volctl-0.8.2/bin/..volctl-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/xr1jiqfxlq8sr52fa3vw0i32z288vqrl-volctl-0.8.2/lib/python3.10/site-packages/volctl/__main__.py", line 22, in main
    Gtk.main()
  File "/nix/store/hl66fvyvk8gq5vmsfs2wjsrbv038ikm0-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 1687, in main
    with register_sigint_fallback(Gtk.main_quit):
  File "/nix/store/rpri9nb8xpwwqakyrqbg8zdslkjs2hd3-python3-3.10.11/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/nix/store/hl66fvyvk8gq5vmsfs2wjsrbv038ikm0-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

~ took 3m18s  ➜ mictray              

(mictray:3481): Gtk-CRITICAL **: 10:51:52.868: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(mictray:3481): Gtk-CRITICAL **: 10:51:52.876: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(mictray:3481): Gtk-CRITICAL **: 10:51:52.876: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
^C
~ took 15s  ➜ 
```

### Steps To Reproduce
1. add `volctl` and/or `mictray` to the nixos configuration.
2. rebuild nixos
3. start `volctl` and/or `mictray` from the terminal

### Expected behavior
I expect to see a GTK Window and/or a systemtray icon. Both do not show up.

### Screenshots
See my terminal output above.

### Additional context
```console
Machine     -  LENOVO ThinkPad T14s Gen 1 20UHCTO1WW
Kernel      -  6.0.10-zen2
Distro      -  NixOS 22.11 (Raccoon)
WM          -  Sway (Wayland)
Terminal    -  foot
Shell       -  zsh
Uptime      -  11m
CPU         -  AMD Ryzen 7 PRO 4750U with Radeon Graphics (16)
Resolution  -  1920x1080, 1920x1080
Brightness  -  100%
CPU Load    -  14%
Memory      -  1.7 GB/32.1 GB
```

### Notify maintainers

@romildo ()
@anpryl 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.10-zen2, NixOS, 22.11 (Raccoon), 22.11.4286.7dc71aef32e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - channels(patrick): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bobby285271** [comment]
> volctl and/or mictray

> WM          -  Sway (Wayland)

On cinnamon both opens fine, I expect both are system tray apps and I imagine this can happen if these apps don't support the type of status icon that's probably supported in sway (StatusNotifier? I don't know)
