### ISSUE TITLE
rapid-photo-downloader: ValueError: Namespace Notify not available

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#233215]
### Describe the bug

Program does not start.

### Steps To Reproduce

```
[davidak@gaming:~]$ rapid-photo-downloader 
Traceback (most recent call last):
  File "/nix/store/zgp0lr9lvrkfhnz6bvzdn3mn71ng8hl8-rapid-photo-downloader-0.9.18/bin/.rapid-photo-downloader-wrapped", line 6, in <module>
    from raphodo.rapid import main
  File "/nix/store/zgp0lr9lvrkfhnz6bvzdn3mn71ng8hl8-rapid-photo-downloader-0.9.18/lib/python3.10/site-packages/raphodo/rapid.py", line 62, in <module>
    gi.require_version('Notify', '0.7')
  File "/nix/store/8c68lgmlxi34qws9za8l4cri8f0vq4ga-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

### Expected behavior
working program

### Additional context

The version from unstable works:

`nix run nixpkgs#rapid-photo-downloader`

Maybe backport the update, so the channel has a working package.

### Notify maintainers

@jfrankenau

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.10, NixOS, 22.11 (Raccoon), 22.11.3689.fda0d99c2cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by davidak** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/208249.
