### ISSUE TITLE
Package request: tabby

### ISSUE THREAD

**Issue by webbb82** [NixOS/nixpkgs#233509]
**Project description**
[Tabby](https://tabby.sh/) (formerly Terminus) is a highly configurable terminal emulator, SSH and serial client for Windows, macOS and Linux

1. Integrated SSH and Telnet client and connection manager
2. Integrated serial terminal
3. Theming and color schemes
4. Fully configurable shortcuts and multi-chord shortcuts
5. Split panes
6. Remembers your tabs
7. PowerShell (and PS Core), WSL, Git-Bash, Cygwin, MSYS2, Cmder and CMD support
8. Direct file transfer from/to SSH sessions via Zmodem
9. Full Unicode support including double-width characters
10. Doesn't choke on fast-flowing outputs
11. Proper shell experience on Windows including tab completion (via Clink)
12. Integrated encrypted container for SSH secrets and configuration
13. SSH, SFTP and Telnet client available as a [web app](https://tabby.sh/app) (also [self-hosted](https://github.com/Eugeny/tabby-web)).

**Metadata**

* homepage URL:https://github.com/Eugeny/tabby
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by AndersonTorres** [comment]
Let's keep this one.

**Comment by tyriis** [comment]
out of curiosity what is preventing this to happen?

**Comment by AndersonTorres** [comment]
To me? Seriously I'm afraid of Javascript.

**Comment by tyriis** [comment]
@AndersonTorres I am not aware of the process on how applications get packaged in nix, or is it just that no javascript based applications will be added to the package system?

**Comment by randoneering** [comment]
I cannot stress this enough: please please please make this a package.

**Comment by yswtrue** [comment]
waiting too

**Comment by pluiedev** [comment]
I actually attempted to build Tabby myself today — however, the package.json and yarn.lock seem to be mildly malformed: `yarn2nix` relies on `package.json` having a `name` field, for example, which Tabby's doesn't have; even after I manually patched in name information, building still results in an indecipherable error that reads like this:
```console
tabby-modules> Running phase: patchPhase
tabby-modules> Running phase: updateAutotoolsGnuConfigScriptsPhase
tabby-modules> Running phase: configurePhase
tabby-modules> Running phase: buildPhase
tabby-modules> yarn config v1.22.19
tabby-modules> success Set "yarn-offline-mirror" to "/nix/store/lcb2fn41id44a0qzsabznhjhw7ikdmnb-offline".
tabby-modules> Done in 0.02s.
tabby-modules> yarn install v1.22.19
tabby-modules> [1/4] Resolving packages...
tabby-modules> warning Lockfile has incorrect entry for "pug@^2.0.0-alpha7". Ignoring it.
tabby-modules> warning Lockfile has incorrect entry for "pug@^2.0.0-rc.2". Ignoring it.
tabby-modules> error Couldn't find any versions for "pug" that matches "^2.0.0-alpha7" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
tabby-modules> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
tabby-modules> Error: Couldn't find any versions for "pug" that matches "^2.0.0-rc.2" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
tabby-modules>     at MessageError.ExtendableBuiltin (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:721:66)
tabby-modules>     at new MessageError (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:750:123)
tabby-modules>     at NpmResolver.<anonymous> (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:50438:15)
tabby-modules>     at Generator.next (<anonymous>)
tabby-modules>     at step (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:310:30)
tabby-modules>     at /nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:321:13
tabby-modules> Error: Couldn't find any versions for "pug" that matches "^2.0.0-rc.2" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
tabby-modules>     at MessageError.ExtendableBuiltin (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:721:66)
tabby-modules>     at new MessageError (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:750:123)
tabby-modules>     at NpmResolver.<anonymous> (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:50438:15)
tabby-modules>     at Generator.next (<anonymous>)
tabby-modules>     at step (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:310:30)
tabby-modules>     at /nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:321:13
error: builder for '/nix/store/7sq20dmx8ha9k9phww3q60v0i9fg0ys8-tabby-modules-1.0.205.drv' failed with exit code 1;
       last 10 log lines:
       >     at Generator.next (<anonymous>)
       >     at step (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:310:30)
       >     at /nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:321:13
       > Error: Couldn't find any versions for "pug" that matches "^2.0.0-rc.2" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
       >     at MessageError.ExtendableBuiltin (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:721:66)
       >     at new MessageError (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:750:123)
       >     at NpmResolver.<anonymous> (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:50438:15)
       >     at Generator.next (<anonymous>)
       >     at step (/nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:310:30)
       >     at /nix/store/fpi2d88hrwazxm7ign8ivapcnwfzaj1g-yarn-1.22.19/libexec/yarn/lib/cli.js:321:13
       For full logs, run 'nix log /nix/store/7sq20dmx8ha9k9phww3q60v0i9fg0ys8-tabby-modules-1.0.205.drv'.
error: 1 dependencies of derivation '/nix/store/k0a1vn4hy2706plbs1fryxwa0v08danm-tabby-1.0.205.drv' failed to build
```

I don't use Yarn myself so I really have no idea what's going on. I inspected the lockfile myself and nothing appears to be missing, and I don't know if there's a way to see what exactly went wrong in Yarn's end. But honestly, it's this kind of difficulty that really dissuades Nixpkgs maintainers from packaging Tabby correctly — we're definitely in help wanted territory, I suspect

**Comment by pluiedev** [comment]
I think my next move would be try to repro this in offline mode outside of Nix, since if it doesn't build in offline mode at all then we've got bigger problems; additionally I would also try to generate a new lockfile that hopefully makes things build

**Comment by pluiedev** [comment]
It does build when cloned manually outside of Nix. However it was doing way more than what I saw with Nix and it also downloaded a lot more dependencies, so I think this might be due to Tabby being a Yarn monorepo that I unfortunately have no idea how to build correctly — definitely need some guidance from people more familiar with `yarn2nix` and building monorepo Node.js projects in general

**Comment by goodosoft** [comment]
waiting for it!

**Comment by ChocolateLoverRaj** [comment]
I don't have any experience adding packages to nixpkgs, but I did create a `flake.nix` for building tabby from source: https://github.com/ChocolateLoverRaj/tabby/blob/nix/flake.nix. If someone wants to take it from here and create a package that would be great. I will also try doing that if no one else is doing it. Tabby imo is the best Terminal app I've used, the main feature being the smart Ctrl+C feature.

**Comment by ChocolateLoverRaj** [comment]
I think packaging shouldn't be too hard. I ran `tabby` from the linux `.tar.gz` inside the `nix develop` environment and it opened.

**Comment by pluiedev** [comment]
> I think packaging shouldn't be too hard. I ran `tabby` from the linux `.tar.gz` inside the `nix develop` environment and it opened.

There's currently a push against using pre-packaged versions of Electron-based software at #296939, and really, ideally we should be able to compile it from source in a `mkDerivation` (note: NOT in a dev shell with manually run commands) to be maximally reproducible.

However, I think making an exception this time is somewhat justified — Tabby has been very highly requested and it appears that the demand is there to add it to Nixpkgs as quickly as possible. If someone figures out a from-source approach then that would very certainly be welcome, however I'd wager we'd need help from a bonafide Yarn wizard.

**Comment by ChocolateLoverRaj** [comment]
I just followed the instructions in https://github.com/Eugeny/tabby/blob/master/HACKING.md:
- `yarn run build`
- `yarn start`
and it works. Is the issue with Yarn that Nix requires the yarn commands to work without internet connection?

**Comment by ChocolateLoverRaj** [comment]
Even when using a `.tar.gz` downloaded from Tabby releases idk how to make `tabby` use the `.so` files
![image](https://github.com/NixOS/nixpkgs/assets/52586855/01243b2b-d207-4e5b-97f8-da9d723992c4)

**Comment by ChocolateLoverRaj** [comment]
This is my `default.nix`:
```nix
{ stdenv, fetchurl, pkgs }:

stdenv.mkDerivation rec {
  name = "tabby";
  src = fetchurl {
    url = "https://github.com/Eugeny/tabby/releases/download/v1.0.207/tabby-1.0.207-linux-x64.deb";
    hash = "sha256-PTTkL3+mYb7KM8fDUmgCuAF2lU88fYOstGWp/O5WZas=";
  };

  nativeBuildInputs = with pkgs; [
    dpkg
    autoPatchelfHook
  ];

  unpackPhase = ''
    runHook preUnpack

    dpkg -x $src .

    runHook postUnpack
  '';

  buildInputs = with pkgs; [
    glib
    glibc
    nss
    nspr
    atk
    cups
    dbus
    libdrm
    gtk3
    pango
    cairo
    xorg.libX11
    xorg.libXcomposite
    xorg.libXdamage
    xorg.libXext
    xorg.libXfixes
    xorg.libXrandr
    libxkbcommon
    mesa
    expat
    xorg.libxcb
    alsaLib
    libGL
    libsecret
    musl
  ];

  postInstall = ''
    mkdir -p $out/{usr,opt}
    cp -r opt $out
    cp -r usr $out
  '';
}
```
Except when running `tabby` I get this error: `Could not dlopen libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory`

**Comment by pluiedev** [comment]
> I just followed the instructions in https://github.com/Eugeny/tabby/blob/master/HACKING.md:
> 
> * `yarn run build`
> * `yarn start`
>   and it works. Is the issue with Yarn that Nix requires the yarn commands to work without internet connection?

Yes, Nix builds everything with a sandbox by default and so derivations cannot access the internet. Additionally, the dependencies should be guarded by a hash so that we ensure the dependencies we're using are the same each time. I know how to do this with pnpm but absolutely no clue with Yarn monorepos, hence the need for a Yarn expert in packaging this.

**Comment by pluiedev** [comment]
> This is my `default.nix`:
> 
> ```nix
> { stdenv, fetchurl, pkgs }:
> 
> stdenv.mkDerivation rec {
>   name = "tabby";
>   src = fetchurl {
>     url = "https://github.com/Eugeny/tabby/releases/download/v1.0.207/tabby-1.0.207-linux-x64.deb";
>     hash = "sha256-PTTkL3+mYb7KM8fDUmgCuAF2lU88fYOstGWp/O5WZas=";
>   };
> 
>   nativeBuildInputs = with pkgs; [
>     dpkg
>     autoPatchelfHook
>   ];
> 
>   unpackPhase = ''
>     runHook preUnpack
> 
>     dpkg -x $src .
> 
>     runHook postUnpack
>   '';
> 
>   buildInputs = with pkgs; [
>     glib
>     glibc
>     nss
>     nspr
>     atk
>     cups
>     dbus
>     libdrm
>     gtk3
>     pango
>     cairo
>     xorg.libX11
>     xorg.libXcomposite
>     xorg.libXdamage
>     xorg.libXext
>     xorg.libXfixes
>     xorg.libXrandr
>     libxkbcommon
>     mesa
>     expat
>     xorg.libxcb
>     alsaLib
>     libGL
>     libsecret
>     musl
>   ];
> 
>   postInstall = ''
>     mkdir -p $out/{usr,opt}
>     cp -r opt $out
>     cp -r usr $out
>   '';
> }
> ```
> 
> Except when running `tabby` I get this error: `Could not dlopen libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory`

Hmm.... try running `ldd` on the tabby executable. It would show every dynamically linked library it's expecting, and libGL should turn out blank. I suspect it's because you aren't using the dev outputs for these libs — try using `libGL.dev` instead of `libGL`.

**Comment by eclairevoyant** [comment]
> try using `libGL.dev` instead of `libGL`.

That won't address anything. Ultimately for precompiled programs, you either need to modify `RPATH`, wrap the binary, or set up an FHS env (depending on how the program tries to access the shared lib, and whether `patchelf` even works).

Easiest option to try first is

```nix
appendRunpaths = [ ( lib.makeLibraryPath [ libGL ] ) ];
```

**Comment by Lite5h4dow** [comment]
would genuinely love to see this, but its above my paygrade

**Comment by D3st0ny** [comment]
when

**Comment by Th1nkK1D** [comment]
This is my first time trying to make Nix packages, I made some progress and found out that the big problem is tabby upstream is a monorepo without using yarn's `workspace`. They have many packages in separated sub-folders with individual `yarn.lock`. 

## 1st attempt: Using `mkYarnPackage` and `fetchYarnDeps`

```nix
{ mkYarnPackage, fetchgit, jq, runCommand, fetchYarnDeps, git }:

mkYarnPackage rec {
  pname = "tabby-terminal";
  version = "1.0.215";

  src = fetchgit {
    url = "https://github.com/Eugeny/tabby";
    rev = "refs/tags/v${version}";
    hash = "sha256-JLOVw2B3bTOcjE2qVId8pITqy0KgxegXLsFky6ggs3E=";
    leaveDotGit = true;
  };

  # mkYarnPackage required name and version in package.json which is missing from tabby upstream
  packageJSON = runCommand "package.json" { } ''
    cat ${src}/package.json | ${jq}/bin/jq '.name="tabby" | .version="${version}"' > $out
  '';

  # bump pug dependency version in lockfile to v3
  # (already set in package.json resolutions, but yarn install still throw an error without the patch)
  yarnLock = runCommand "yarn.lock" { } ''
    cat ${src}/yarn.lock | sed -rE 's/pug@\^2.0.0-alpha7,\ pug@\^2.0.0-rc.2,\ //g' | sed -rE 's/2.0.0-alpha7|2.0.0-rc.2/3/g' > $out
  '';

  offlineCache = fetchYarnDeps {
    inherit yarnLock;
    hash = "sha256-9LIeuafM+460eZENrkiWzNkgibCpvwTYpRRFaengPn0=";
  };

  yarnFlags = [ "--no-progress" ];

  configurePhase = ''
    ln -s $node_modules node_modules
  '';

  extraBuildInputs = [ git ];

  buildPhase = ''
    git tag v${version}
    yarn --offline build
  '';

  doDist = false;
}
```

With the current implementation of `mkYarnPackage` and `fetchYarnDeps`, only root `node_modules` corresponding to the root `package.json` and `yarn.lock` will be created. The build failed because `node_modules` in every sub-package does not exist.

## 2nd attempt: Use `fetchYarnDeps` with concatenated `yarn.lock` in `mkDerivation`

```nix

{ stdenv, fetchgit, runCommand, fetchYarnDeps, git, fixup_yarn_lock, yarn
, nodejs }:
stdenv.mkDerivation rec {
  pname = "tabby-terminal";
  version = "1.0.215";

  nativeBuildInputs = [ git yarn nodejs ];

  src = fetchgit {
    url = "https://github.com/Eugeny/tabby";
    rev = "refs/tags/v${version}";
    hash = "sha256-JLOVw2B3bTOcjE2qVId8pITqy0KgxegXLsFky6ggs3E=";
    leaveDotGit = true;
  };

  offlineCache = fetchYarnDeps {
    # concat yan.lock and bump pug dependency version in lockfile to v3
    yarnLock = runCommand "yarn.lock" { } ''
      cat ${src}/yarn.lock ${src}/*/yarn.lock |
      sed -rE 's/pug@\^2.0.0-alpha7,\ pug@\^2.0.0-rc.2,\ //g' |
      sed -rE 's/2.0.0-alpha7|2.0.0-rc.2/3/g' > $out
    '';
    hash = "sha256-uJRJRn2cWR6+pfxW5+Q//g5rYzr5CoUDcnVUACUMRPg=";
  };

  configurePhase = ''
    export HOME=$PWD/yarn_home
    yarn config --offline set yarn-offline-mirror $offlineCache
    git tag v${version}
  '';

  buildPhase = ''
    find . -type f -name 'yarn.lock' -exec ${fixup_yarn_lock}/bin/fixup_yarn_lock {} \;

    yarn install --offline --prefer-offline --frozen-lockfile --ignore-scripts --no-progress --non-interactive

    yarn --offline build
  '';
}
```

This failed because `yarn install` couldn't find some packages inside the offline cache created by `fetchYarnDeps`. I think naively concatenated `yarn.lock` was processed differently between `fetchYarnDeps` and `yarn install`.

## Suggestion (from what I found)
Manual patching non-standard mono repo on the Nix side looks like painful work (at least for me who do it for the first time). If we can refactor the upstream repo to use yarn workspace as suggested in https://github.com/Eugeny/tabby/issues/2334, packaging in Nix should be easier.

They also use `yarn-berry` on the upstream, I'm not sure if we will have an incompatibility issue with `yarn2nix`.

**Comment by tyriis** [comment]
@Th1nkK1D thank you for taking your time and digging into it, sad to see that it is not possible yet :/
