### ISSUE TITLE
sysdig: segfaults

### ISSUE THREAD

**Issue by markus1189** [NixOS/nixpkgs#23404]
## Issue description

I would be happy for any pointers for possible reasons or ways to debug this further myself, I just don't know how to begin.

When starting `sysdig` it exits with a segfault:

```
> sudo sysdig
zsh: segmentation fault  sudo sysdig
```

tail from a `strace`:

```
open("/proc/27132/task/27135/cgroup", O_RDONLY) = 13
fstat(13, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(13, "9:memory:/system.slice/ntpd.serv"..., 1024) = 260
read(13, "", 1024)                      = 0
close(13)                               = 0
ioctl(3, _IOC(0, 0x73, 0x0a, 0x00), 0x69ff) = 27135
ioctl(3, _IOC(0, 0x73, 0x0b, 0x00), 0x69ff) = 27132
readlink("/proc/27132/task/27135/root", "/", 1024) = 1
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x10} ---
+++ killed by SIGSEGV +++
```

### Steps to reproduce

add this to the `configuration.nix`:

```
boot = {
  extraModulePackages = with boot.kernelPackages; [ sysdig ];
};
```

then run:

```
> sudo sysdig
zsh: segmentation fault  sudo sysdig
```

## Technical details

* System:
```
> nixos-version
17.03pre101839.53a2baa (Gorilla)
* Nix version:
`nix-env (Nix) 1.11.6`
* Nixpkgs version: `"17.03pre101839.53a2baa"`

**Comment by Mic92** [comment]
Sysdig was upgraded in nixos unstable recently. Does it still happen with the latest version? 

```
$ sysdig --version                         
sysdig version 0.15.0
```

**Comment by markus1189** [comment]
Unfortunately yes:

```
[markus@nixos]$ sysdig --version
sysdig version 0.15.0

[markus@nixos]$ sudo sysdig
Segmentation fault
```

**Comment by Mic92** [comment]
To get a meaningful upstream bug report, you should generate a backtrace with debug symbols included:

```
# configuration.nix
environment.systemPackages = [
  (sysdig.overrideDerivation (old: { dontStrip = true; }))
  # ...
];
```

```
$ ulimit -c unlimited
$ sysdig # should generate a file named 'core' on crash
$ gdb sysdig core
gdb> backtrace
```

**Comment by markus1189** [comment]
@Mic92 Thanks for the pointers, I now have a backtrace: 

```
(gdb) backtrace
#0  0x000000000059eabb in scap_proc_get ()
#1  0x000000000053d5ed in sinsp::get_thread(long, bool, bool) ()
#2  0x00000000005370e2 in sinsp_threadinfo::set_cwd(char const*, unsigned int) ()
#3  0x0000000000539dc6 in sinsp_threadinfo::init(scap_threadinfo*) ()
#4  0x000000000053d8e3 in sinsp::on_new_entry_from_proc(void*, long, scap_threadinfo*, scap_fdinfo*, scap*) ()
#5  0x000000000059e259 in scap_proc_scan_proc_dir ()
#6  0x000000000059de68 in scap_proc_scan_proc_dir ()
#7  0x0000000000597954 in scap_open_live_int ()
#8  0x0000000000542a51 in sinsp::open(unsigned int) ()
#9  0x0000000000542e6d in sinsp::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#10 0x000000000046893d in sysdig_init(int, char**) ()
#11 0x0000000000453730 in main ()
```

What is the best way to submit this in a reproducible way to the sysdig repo?

**Comment by markus1189** [comment]
After an upgrade to nixos 17.03 sysdig works again. Closing.
