### ISSUE TITLE
python setuptools broken, taking out a number of python packages

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#23483]
## Issue description

Fails to build for lack of `pyexpat`

### Steps to reproduce

[http://hydra.nixos.org/build/49592549/nixlog/1](Hydra log)

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by FRidh** [comment]
Fixes are already in master and if I am correct also 17.03.

**Comment by mdorman** [comment]
@FRidh I'm afraid that's not true:

```building path(s) ‘/nix/store/p3mha6n09lnl7vbkw71g6db5snfs3rfn-python3.4-setuptools-30.2.0’
unpacking sources
unpacking source archive /nix/store/70xydxh5ik64fc3r7rswhqqgly512n26-setuptools-30.2.0.tar.gz
source root is setuptools-30.2.0
setting SOURCE_DATE_EPOCH to timestamp 1480866953 of file setuptools-30.2.0/setuptools.egg-info/top_level.txt
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/tmp/nix-build-python3.4-setuptools-30.2.0.drv-0/setuptools-30.2.0/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, filterfalse, map
  File "/tmp/nix-build-python3.4-setuptools-30.2.0.drv-0/setuptools-30.2.0/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
  File "/tmp/nix-build-python3.4-setuptools-30.2.0.drv-0/setuptools-30.2.0/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/nix/store/xqs40n8lq4faidjgj3y1lq25qarzrns0-python3-3.4.6/lib/python3.4/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/nix/store/xqs40n8lq4faidjgj3y1lq25qarzrns0-python3-3.4.6/lib/python3.4/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: No module named 'pyexpat'
builder for ‘/nix/store/f1dw36idhfhav9b4vaq1429b8b6n4wiy-python3.4-setuptools-30.2.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/4hys2a9ia42bw6gy0h4dk4zc3zn28hmc-borgbackup-1.0.9.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/wj9mkghslzlzhkivj8mc9z8pkc46q56n-everything.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/wj9mkghslzlzhkivj8mc9z8pkc46q56n-everything.drv’ failed
nix-env failed with error code 100.
~/src/nixpkgs $ 
```

This is a tree that is synced to master as of about five seconds ago.

**Comment by FRidh** [comment]
master at cd18b65432df1ac3888bb63b78c0af19232c8a14 produces
```
$ nix-build -A python34Packages.setuptools
/nix/store/nc458vvm045sz3imid2ykc7w5ba060j0-python3.4-setuptools-30.2.0
```
