### ISSUE TITLE
python3Packages.matplotlib: Can't find a usable tk.tcl

### ISSUE THREAD

**Issue by TheDelus** [NixOS/nixpkgs#234962]
### Describe the bug
Matplotlib cant find TK

### Steps To Reproduce
1. Using this flake to get a devShell:

```nix
{
  inputs = { nixpkgs.url = "github:nixos/nixpkgs/5e871d8aa6f57cc8e0dc087d1c5013f6e212b4ce"; };
  outputs = { self, nixpkgs }:
    let
      pkgs = nixpkgs.legacyPackages.x86_64-linux;
    in
    {
      packages.x86_64-linux.python-matplotlib = pkgs.python3Packages.matplotlib.override { enableTk = true; };
      devShell.x86_64-linux = pkgs.mkShell {
        buildInputs = [
          self.packages.x86_64-linux.python-matplotlib
        ];
      };
    };
}
```
2. `$ nix develop`
3. `$ python3 -c "import matplotlib.pyplot as plt; plt.figure(); "`

### Expected behavior
An empty plot should be shown. Instead an exception was thrown:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/pyplot.py", line 813, in figure
    manager = new_figure_manager(
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/pyplot.py", line 383, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 3570, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 3575, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1738, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/backends/_backend_tk.py", line 483, in create_with_canvas
    window = tk.Tk(className="matplotlib")
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable tk.tcl in the following directories:
    /nix/store/ax09cbfj991hn856w1pmk68mxbf6lcfl-tcl-8.6.13/lib/tcl8.6/tk8.6 /nix/store/ax09cbfj991hn856w1pmk68mxbf6lcfl-tcl-8.6.13/lib/tk8.6 /nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/tk8.6 /nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/tk8.6 /nix/store/lib/tk8.6 /nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/library



This probably means that tk wasn't installed properly.
```

### Notify maintainers

@lovek323 @veprbl 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.24, NixOS, 23.05 (Stoat), 23.05.20230417.f00994e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(user): `""`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/store/9gyra3774fp9bdzchrvq2v4y9nia0pc3-source`
```

**Comment by JordiSalaJuarez** [comment]
I'm getting a similar error when using tkinter with the nixos-23.05 channel using flakes.
1. Using this flake using devShell

```nix
{
  description = "A very basic flake";
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-23.05";
  outputs = { self, nixpkgs }: 
    let
      pkgs = nixpkgs.legacyPackages.x86_64-linux;
      pythonPackages = pkgs.python3Packages;
    in {
      devShells.x86_64-linux.default = pkgs.mkShell {
        buildInputs = [
	  pythonPackages.python
	  pythonPackages.tkinter
	];
      };
    };
}
```

2. `nix develop`
3.  ` python -c "import tkinter; tkinter.Tk()" `
```bash
[user@system:~]$ python -c "import tkinter; tkinter.Tk()" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
    /nix/store/ax09cbfj991hn856w1pmk68mxbf6lcfl-tcl-8.6.13/lib/tcl8.6/tk8.6 /nix/store/ax09cbfj991hn856w1pmk68mxbf6lcfl-tcl-8.6.13/lib/tk8.6 /nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/tk8.6 /nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/tk8.6 /nix/store/lib/tk8.6 /nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/library



This probably means that tk wasn't installed properly.
```

```bash
[user@system:~]$ nix flake metadata
Resolved URL:  path:/tmp/tmp.1uoYrmkL5w
Locked URL:    path:/tmp/tmp.1uoYrmkL5w?lastModified=1685447429&narHash=sha256-g70zfe9lJfh2FfX0p8R8ZZy0H+pOPJ6aQBlU4sxtO+8=
Description:   A very basic flake
Path:          /nix/store/327nmdaiyz1hdgisc7j6x3bbjiyhvsxc-source
Last modified: 2023-05-30 13:50:29
Inputs:
└───nixpkgs: github:nixos/nixpkgs/0f7f5ca1cdec8dea85bb4fa60378258171d019ad
```



Seems like tkinter is breaking with 23.05

**Comment by TheDelus** [comment]
Adding the `TK_LIBRARY` var to `mkShell` seems to fix it. 
```
shellHook = ''
    export TK_LIBRARY="${pkgs.tk}/lib/${pkgs.tk.libPrefix}"
'';
```
But why is it needed? 
There is still no plot showing up when calling `python3 -c "import matplotlib.pyplot as plt; plt.figure().show;"`

**Comment by wegank** [comment]
Sorry for the inconvenience. A patch has been merged into the staging branches, it will probably take a week or two for it to get into the stable/unstable channels.

**Comment by TheDelus** [comment]
@wegank Thx for your help. I can confirm that your PR fixed the issue.
