### ISSUE TITLE
dropbox: No module named 'gi'

### ISSUE THREAD

**Issue by brianmay** [NixOS/nixpkgs#235345]
### Describe the bug
Dropbox fails to install in new 23.05 install.

### Steps To Reproduce

```
$ dropbox start -i
Starting Dropbox...dropbox: locating interpreter
dropbox: logging to /tmp/dropbox-antifreeze-CAYLlO
dropbox: initializing
dropbox: initializing python 3.7.9
dropbox: setting program path '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/dropbox'
dropbox: setting python path '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447:/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/python-packages.zip'
dropbox: python initialized
dropbox: running dropbox
dropbox: setting args
dropbox: enabling allocator metrics
dropbox: applying overrides
dropbox: running main script
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/cryptography.hazmat.bindings._constant_time.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/cryptography.hazmat.bindings._openssl.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/cryptography.hazmat.bindings._padding.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/psutil._psutil_linux.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/psutil._psutil_posix.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/apex._apex.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/tornado.speedups.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/wrapt._wrappers.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/PyQt5.QtWidgets.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/PyQt5.QtCore.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/PyQt5.QtGui.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/PyQt5.QtNetwork.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/brian/.dropbox-dist/dropbox-lnx.x86_64-111.3.447/PyQt5.QtDBus.cpython-37m-x86_64-linux-gnu.so'

Traceback (most recent call last):
  File "/home/brian/.nix-profile/bin/dropbox", line 1452, in start
    download()
  File "/home/brian/.nix-profile/bin/dropbox", line 294, in download
    import gi
ModuleNotFoundError: No module named 'gi'
```

### Expected behavior
It should start without errors.

### Screenshots
As above.

### Additional context

This is a new install of nixos 23.05, and dropbox installed using home-manager.

### Notify maintainers

@ttuegel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.20230531.3a70dd9`
 - multi-user?: `yes`
```

**Comment by peterhoeg** [comment]
This is admittedly off-topic, but unless you absolutely need the actual dropbox client, I cannot strongly enough recommend maestral. Been using that for years as there is a limit to the number of clients you can use with the free plan, but maestral doesn't count against that.

**Comment by brianmay** [comment]
@peterhoeg Do you by any chance have a sample home-manager config for maestral that will automatically start it in a systemd user based service?

**Comment by peterhoeg** [comment]
I have a nixos module which still supports the proprietary dropbox package.

{ config, lib, pkgs, ... }:

let
  cfg = config.hoeg.programs.dropbox;

  inherit (lib)
    mkEnableOption mkIf mkMerge mkOption types;

  commonServiceConfig = {
    KillMode = "control-group"; # dropbox upstream recommends process
    NotifyAccess = "main";
    Restart = "on-failure";
    PrivateTmp = true;
    ProtectSystem = "strict";
    Nice = 10;
    Slice = "background.slice";
  };

  environment = {
    HOME = "%h";
  };

  wantedBy = [ "graphical-session.target" ];

  ini = pkgs.formats.ini { };

  defaultKeyring = "keyring.backends.kwallet.DBusKeyring";
  # defaultKeyring = "automatic";
  # defaultKeyring = "keyring.backends.SecretService.Keyring";

  maestralIni = ini.generate "maestral-override.ini" {
    app = {
      # if we pass a bool here, it will end up as false which makes
maestral blow up
      analytics = "False";
      notification_level = 30; # SYNCISSUE
      update_notification_interval = 0;
    };

    # kwallet has support for SecretService, but it doesn't seem to work
    auth = {
      keyring = defaultKeyring;
    };
  };

  keyringIni = ini.generate "keyringrc.cfg" {
    backend.default-keyring = defaultKeyring;
  };

in
{
  meta.maintainers = with lib.maintainers; [ peterhoeg ];

  options.hoeg.programs.dropbox = {
    enable = mkEnableOption "Dropbox/Maestral";

    preferMaestral = mkOption {
      description = "Prefer maestral";
      type = types.bool;
      default = true;
    };

    runGUI = mkEnableOption "Run GUI tool";

    folderPath = mkOption {
      description = "Path to local dropbox folder";
      type = types.nullOr types.str;
      default = null;
    };
  };

  config = mkIf cfg.enable (mkMerge [
    (mkIf cfg.preferMaestral {
      environment.systemPackages = [
        (pkgs.maestral.overrideAttrs (old: {
          # doCheck = false;
        }))
      ];

      systemd.user.services = {
        maestral = rec {
          description = "Maestral - OpenSource Dropbox client";
          conflicts = [ "dropbox.service" ];
          restartTriggers = [ maestralIni ];
          wants = [ ]; # [ "kwalletd5.service" ];
          # we need kwallet to be running before maestral can fetch the auth
          # token, so we *need* this to be a graphical session
          after = wantedBy ++ wants;
          inherit environment wantedBy;

          unitConfig = {
            ConditionUser = ***@***.***";
            ConditionPathExists = [
              "%h/.config/maestral/maestral.ini"
              # do not set this here as each machine has its own path and
thus sets it itself
            ] ++ lib.optional (cfg.folderPath != null) cfg.folderPath;
          };

          serviceConfig = with pkgs; (
            commonServiceConfig // {
              Type = "notify";
              ExecStartPre = "/bin/sh -c '${pkgs.crudini}/bin/crudini
--merge $HOME/.config/maestral/maestral.ini < ${maestralIni}'";
              ExecStart = "${lib.getBin maestral}/bin/maestral start
--foreground";
              ExecStop = "${lib.getBin maestral}/bin/maestral stop";
              # ExecStopPost = ''/bin/sh -c "test "$SERVICE_RESULT" !=
"success" && ${pkgs.libnotify}/bin/notify-send Maestral 'Daemon failed'"'';
              ExecReload = "${lib.getBin coreutils}/bin/kill -HUP $MAINPID";
              EnvironmentFile = "-%t/keys/maestral";
              WatchdogSec = "60s";
              RuntimeDirectory = "maestral";
            }
          );
        };
      };
    })

    (mkIf (! cfg.preferMaestral) {
      networking.firewall = {
        allowedTCPPorts = [ 17500 ];
        allowedUDPPorts = [ 17500 ];
      };

      environment.systemPackages = [ pkgs.dropbox-cli ];

      systemd.user.services.dropbox = rec {
        description = "Dropbox";
        after = wants ++ wantedBy;
        wants = [ "xembed-sni-proxy.service" ];
        conflicts = [ "maestral.service" "maestral-gui.service" ];
        inherit environment wantedBy;

        unitConfig = {
          ConditionPathExists = mkIf (cfg.folderPath != null)
cfg.folderPath;
          ConditionUser = ***@***.***";
        };

        serviceConfig = with pkgs; (
          commonServiceConfig // {
            ExecStart = "${lib.getBin dropbox}/bin/dropbox";
            ExecReload = "${lib.getBin coreutils}/bin/kill -HUP $MAINPID";
          }
        );
      };
    })
  ]);
}

**Comment by peterhoeg** [comment]
OK, so the previous mail looked terrible. Let me try this again from a proper mail client:

┌────
│ { config, lib, pkgs, ... }:
│ 
│ let
│   cfg = config.hoeg.programs.dropbox;
│ 
│   inherit (lib)
│     mkEnableOption mkIf mkMerge mkOption types;
│ 
│   commonServiceConfig = {
│     KillMode = "control-group"; # dropbox upstream recommends process
│     NotifyAccess = "main";
│     Restart = "on-failure";
│     PrivateTmp = true;
│     ProtectSystem = "strict";
│     Nice = 10;
│     Slice = "background.slice";
│   };
│ 
│   environment = {
│     HOME = "%h";
│   };
│ 
│   wantedBy = [ "graphical-session.target" ];
│ 
│   ini = pkgs.formats.ini { };
│ 
│   defaultKeyring = "keyring.backends.kwallet.DBusKeyring";
│   # defaultKeyring = "automatic";
│   # defaultKeyring = "keyring.backends.SecretService.Keyring";
│ 
│   maestralIni = ini.generate "maestral-override.ini" {
│     app = {
│       # if we pass a bool here, it will end up as false which makes maestral blow up
│       analytics = "False";
│       notification_level = 30; # SYNCISSUE
│       update_notification_interval = 0;
│     };
│ 
│     # kwallet has support for SecretService, but it doesn't seem to work
│     auth = {
│       keyring = defaultKeyring;
│     };
│   };
│ 
│   keyringIni = ini.generate "keyringrc.cfg" {
│     backend.default-keyring = defaultKeyring;
│   };
│ 
│ in
│ {
│   meta.maintainers = with lib.maintainers; [ peterhoeg ];
│ 
│   options.hoeg.programs.dropbox = {
│     enable = mkEnableOption "Dropbox/Maestral";
│ 
│     preferMaestral = mkOption {
│       description = "Prefer maestral";
│       type = types.bool;
│       default = true;
│     };
│ 
│     folderPath = mkOption {
│       description = "Path to local dropbox folder";
│       type = types.nullOr types.str;
│       default = null;
│     };
│   };
│ 
│   config = mkIf cfg.enable (mkMerge [
│     (mkIf cfg.preferMaestral {
│       environment.systemPackages = [
│         (pkgs.maestral.overrideAttrs (old: {
│           # doCheck = false;
│         }))
│       ];
│ 
│       systemd.user.services = {
│         maestral = rec {
│           description = "Maestral - OpenSource Dropbox client";
│           conflicts = [ "dropbox.service" ];
│           restartTriggers = [ maestralIni ];
│           wants = [ ]; # [ "kwalletd5.service" ];
│           # we need kwallet to be running before maestral can fetch the auth
│           # token, so we *need* this to be a graphical session
│           after = wantedBy ++ wants;
│           inherit environment wantedBy;
│ 
│           unitConfig = {
│             ConditionUser = ***@***.***";
│             ConditionPathExists = [
│               "%h/.config/maestral/maestral.ini"
│               # do not set this here as each machine has its own path and thus sets it itself
│             ] ++ lib.optional (cfg.folderPath != null) cfg.folderPath;
│           };
│ 
│           serviceConfig = with pkgs; (
│             commonServiceConfig // {
│               Type = "notify";
│               ExecStartPre = "/bin/sh -c '${pkgs.crudini}/bin/crudini --merge $HOME/.config/maestral/maestral.ini < ${maestralIni}'";
│               ExecStart = "${lib.getBin maestral}/bin/maestral start --foreground";
│               ExecStop = "${lib.getBin maestral}/bin/maestral stop";
│               # ExecStopPost = ''/bin/sh -c "test "$SERVICE_RESULT" != "success" && ${pkgs.libnotify}/bin/notify-send Maestral 'Daemon failed'"'';
│               ExecReload = "${lib.getBin coreutils}/bin/kill -HUP $MAINPID";
│               EnvironmentFile = "-%t/keys/maestral";
│               WatchdogSec = "60s";
│               RuntimeDirectory = "maestral";
│             }
│           );
│         };
│       };
│     })
│ 
│     (mkIf (! cfg.preferMaestral) {
│       networking.firewall = {
│         allowedTCPPorts = [ 17500 ];
│         allowedUDPPorts = [ 17500 ];
│       };
│ 
│       environment.systemPackages = [ pkgs.dropbox-cli ];
│ 
│       systemd.user.services.dropbox = rec {
│         description = "Dropbox";
│         after = wants ++ wantedBy;
│         wants = [ "xembed-sni-proxy.service" ];
│         conflicts = [ "maestral.service" "maestral-gui.service" ];
│         inherit environment wantedBy;
│ 
│         unitConfig = {
│           ConditionPathExists = mkIf (cfg.folderPath != null) cfg.folderPath;
│           ConditionUser = ***@***.***";
│         };
│ 
│         serviceConfig = with pkgs; (
│           commonServiceConfig // {
│             ExecStart = "${lib.getBin dropbox}/bin/dropbox";
│             ExecReload = "${lib.getBin coreutils}/bin/kill -HUP $MAINPID";
│           }
│         );
│       };
│     })
│   ]);
│ }
└────

**Comment by carlthome** [comment]
Backticks for easier skimming:

```nix
{ config, lib, pkgs, ... }:

let
  cfg = config.hoeg.programs.dropbox;

  inherit (lib)
    mkEnableOption mkIf mkMerge mkOption types;

  commonServiceConfig = {
    KillMode = "control-group"; # dropbox upstream recommends process
    NotifyAccess = "main";
    Restart = "on-failure";
    PrivateTmp = true;
    ProtectSystem = "strict";
    Nice = 10;
    Slice = "background.slice";
  };

  environment = {
    HOME = "%h";
  };

  wantedBy = [ "graphical-session.target" ];

  ini = pkgs.formats.ini { };

  defaultKeyring = "keyring.backends.kwallet.DBusKeyring";
  # defaultKeyring = "automatic";
  # defaultKeyring = "keyring.backends.SecretService.Keyring";

  maestralIni = ini.generate "maestral-override.ini" {
    app = {
      # if we pass a bool here, it will end up as false which makes
maestral blow up
      analytics = "False";
      notification_level = 30; # SYNCISSUE
      update_notification_interval = 0;
    };

    # kwallet has support for SecretService, but it doesn't seem to work
    auth = {
      keyring = defaultKeyring;
    };
  };

  keyringIni = ini.generate "keyringrc.cfg" {
    backend.default-keyring = defaultKeyring;
  };

in
{
  meta.maintainers = with lib.maintainers; [ peterhoeg ];

  options.hoeg.programs.dropbox = {
    enable = mkEnableOption "Dropbox/Maestral";

    preferMaestral = mkOption {
      description = "Prefer maestral";
      type = types.bool;
      default = true;
    };

    runGUI = mkEnableOption "Run GUI tool";

    folderPath = mkOption {
      description = "Path to local dropbox folder";
      type = types.nullOr types.str;
      default = null;
    };
  };

  config = mkIf cfg.enable (mkMerge [
    (mkIf cfg.preferMaestral {
      environment.systemPackages = [
        (pkgs.maestral.overrideAttrs (old: {
          # doCheck = false;
        }))
      ];

      systemd.user.services = {
        maestral = rec {
          description = "Maestral - OpenSource Dropbox client";
          conflicts = [ "dropbox.service" ];
          restartTriggers = [ maestralIni ];
          wants = [ ]; # [ "kwalletd5.service" ];
          # we need kwallet to be running before maestral can fetch the auth
          # token, so we *need* this to be a graphical session
          after = wantedBy ++ wants;
          inherit environment wantedBy;

          unitConfig = {
            ConditionUser = ***@***.***";
            ConditionPathExists = [
              "%h/.config/maestral/maestral.ini"
              # do not set this here as each machine has its own path and
thus sets it itself
            ] ++ lib.optional (cfg.folderPath != null) cfg.folderPath;
          };

          serviceConfig = with pkgs; (
            commonServiceConfig // {
              Type = "notify";
              ExecStartPre = "/bin/sh -c '${pkgs.crudini}/bin/crudini
--merge $HOME/.config/maestral/maestral.ini < ${maestralIni}'";
              ExecStart = "${lib.getBin maestral}/bin/maestral start
--foreground";
              ExecStop = "${lib.getBin maestral}/bin/maestral stop";
              # ExecStopPost = ''/bin/sh -c "test "$SERVICE_RESULT" !=
"success" && ${pkgs.libnotify}/bin/notify-send Maestral 'Daemon failed'"'';
              ExecReload = "${lib.getBin coreutils}/bin/kill -HUP $MAINPID";
              EnvironmentFile = "-%t/keys/maestral";
              WatchdogSec = "60s";
              RuntimeDirectory = "maestral";
            }
          );
        };
      };
    })

    (mkIf (! cfg.preferMaestral) {
      networking.firewall = {
        allowedTCPPorts = [ 17500 ];
        allowedUDPPorts = [ 17500 ];
      };

      environment.systemPackages = [ pkgs.dropbox-cli ];

      systemd.user.services.dropbox = rec {
        description = "Dropbox";
        after = wants ++ wantedBy;
        wants = [ "xembed-sni-proxy.service" ];
        conflicts = [ "maestral.service" "maestral-gui.service" ];
        inherit environment wantedBy;

        unitConfig = {
          ConditionPathExists = mkIf (cfg.folderPath != null)
cfg.folderPath;
          ConditionUser = ***@***.***";
        };

        serviceConfig = with pkgs; (
          commonServiceConfig // {
            ExecStart = "${lib.getBin dropbox}/bin/dropbox";
            ExecReload = "${lib.getBin coreutils}/bin/kill -HUP $MAINPID";
          }
        );
      };
    })
  ]);
}
```

**Comment by kciredor** [comment]
Hi @eyJhb, I see you are listed as the Dropbox nix package maintainer.

Can confirm that dropbox is broken on latest stable and unstable NixOS.

Would you be willing to take a look? I'm using home-manager which doesn't say anything, but a manual `dropbox start -i` results in `No module named 'gi'`, which blocks Dropbox from running and syncing.

**Comment by carlthome** [comment]
Same issue here.

**Comment by eyJhb** [comment]
Sorry, I no longer use Dropbox. I should most likely remove myself as maintainer :/

**Comment by AlexChalk** [comment]
It would be great if a maestral user who's configured a working systemd user service to run the daemon could add a code snippet to https://nixos.wiki/wiki/Dropbox :pray:.

**Comment by amacfie** [comment]
there's [this](https://github.com/abhibansal530/dotfiles/blob/43dbf5416a08f94d76c710ee82ef700e9596c601/common.nix#L127) but I haven't tried it myself

**Comment by AlexChalk** [comment]
I'm also on 23.05 and dropbox (the actual client) is working fine for me. The only change is that dropbox-cli reports 'Dropbox isn't running!' if I call `dropbox status`, even though I can update files and manually verify the changes have synced. This is my `configuration.nix`:
```
  systemd.user.services.dropbox = {
    description = "Dropbox";
    wantedBy = [ "default.target" ];
    environment = {
      QT_PLUGIN_PATH = "/run/current-system/sw/" + pkgs.qt5.qtbase.qtPluginPrefix;
      QML2_IMPORT_PATH = "/run/current-system/sw/" + pkgs.qt5.qtbase.qtQmlPrefix;
    };
    serviceConfig = {
      ExecStart = "${lib.getBin pkgs.dropbox}/bin/dropbox";
      ExecReload = "${lib.getBin pkgs.coreutils}/bin/kill -HUP $MAINPID";
      KillMode = "control-group";
      Restart = "on-failure";
      PrivateTmp = true;
      ProtectSystem = "full";
      Nice = 10;
    };
  };
```

**Comment by AlexChalk** [comment]
@amacfie I found a few snippets like that on github, but they seem to store credentials in plaintext by default. I don't think the native dropbox daemon does that?

**Comment by brianmay** [comment]
I translated the maestral snippet above to work with home manager:

```nix
systemd.user.services.maestral = {
    Unit.Description = "Maestral daemon";
    Install.WantedBy = [ "default.target" ];
    Service = {
      ExecStart = "${pkgs.maestral}/bin/maestral start -f";
      ExecStop = "${pkgs.maestral}/bin/maestral stop";
      Restart = "on-failure";
      Nice = 10;
    };
  };
```

So far seems to work.

I think a built in module that lets you do `services.maestral.enabled = true;` would be better.

@AlexChalk not sure I understand your concern, this doesn't do anything with passwords. Unless you are saying Meastral is insecure in the way it stores the credentials?

**Comment by brianmay** [comment]
@AlexChalk I note you are not using the home manager module, i.e. `dropbox.service.enable = true;` - wonder if this is why it works for you...

**Comment by carlthome** [comment]
On migrating from the official Dropbox client to Maestral I've also been having troubles with needing to reauthenticate often (about weekly?), and not being able to sync files with sizes over 350 GB. Assume these are limitations enforced by Dropbox but might be good to be aware of that the clients don't have feature parity.

**Comment by kciredor** [comment]
Perhaps Maestral needs it's own Github issue ;-)

I'm not planning on migrating away from the official Dropbox client and currently the official client is broken on stable NixOS.

**Comment by denibertovic** [comment]
I'm also experiencing this issue right on 23.05 (with home-manager).

**Comment by SuperSandro2000** [comment]
> ModuleNotFoundError: No module named 'gi'

This line https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/dropbox/cli.nix#L47 is missing at runtime
