### ISSUE TITLE
pypi2nix - cannot import nix_prefetch_github

### ISSUE THREAD

**Issue by mbledkowski** [NixOS/nixpkgs#235620]
### Describe the bug
```console
Traceback (most recent call last):
  File "/nix/store/bjj873dgwsnmj1fav012fqxzia4r46in-pypi2nix-2.0.4/bin/.pypi2nix-wrapped", line 6, in <module>
    from pypi2nix.cli import main
  File "/nix/store/bjj873dgwsnmj1fav012fqxzia4r46in-pypi2nix-2.0.4/lib/python3.10/site-packages/pypi2nix/cli.py", line 8, in <module>
    from pypi2nix.configuration import ApplicationConfiguration
  File "/nix/store/bjj873dgwsnmj1fav012fqxzia4r46in-pypi2nix-2.0.4/lib/python3.10/site-packages/pypi2nix/configuration.py", line 8, in <module>
    from pypi2nix.overrides import Overrides
  File "/nix/store/bjj873dgwsnmj1fav012fqxzia4r46in-pypi2nix-2.0.4/lib/python3.10/site-packages/pypi2nix/overrides.py", line 15, in <module>
    from .utils import cmd
  File "/nix/store/bjj873dgwsnmj1fav012fqxzia4r46in-pypi2nix-2.0.4/lib/python3.10/site-packages/pypi2nix/utils.py", line 12, in <module>
    from nix_prefetch_github import nix_prefetch_github
ImportError: cannot import name 'nix_prefetch_github' from 'nix_prefetch_github' (/nix/store/xff0lap7m8d9qddck5rhv21k8irvhw9n-python3.10-nix-prefetch-github-6.0.1/lib/python3.10/site-packages/nix_prefetch_github/__init__.py)
```

### Steps To Reproduce
1. Run `pypi2nix`

### Expected behavior
Command should execute without an error

### Notify maintainers
None?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.1-zen1, NixOS, 23.11 (Tapir), 23.11pre488860.e10802309bf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos, nixos-hardware"`
 - channels(mble): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by figsoda** [comment]
#235631
