### ISSUE TITLE
Bookletimposer throws an GTK3 error

### ISSUE THREAD

**Issue by waot** [NixOS/nixpkgs#235952]
### Describe the bug
The package bookletimposer doesn't work, something with GTK not being in the namespace.

### Steps To Reproduce
1.  nix-shell -p bookletimposer
2. bookletimposer

### Expected behavior
It should open the GUI.

### Screenshots

```
 <nix-shell> bookletimposer                                                                 
Traceback (most recent call last):
  File "/nix/store/5kkr6riy52bq28db6f0vhqxvvbkff8df-bookletimposer-0.3.1/bin/..bookletimposer-wrapped-wrapped", line 166, in <module>
    main()
  File "/nix/store/5kkr6riy52bq28db6f0vhqxvvbkff8df-bookletimposer-0.3.1/bin/..bookletimposer-wrapped-wrapped", line 140, in main
    import bookletimposer.gui as gui
  File "/nix/store/5kkr6riy52bq28db6f0vhqxvvbkff8df-bookletimposer-0.3.1/lib/python3.10/site-packages/bookletimposer/gui.py", line 37, in <module>
    gi.require_version('Gtk', '3.0')
  File "/nix/store/4rqabjjzzxi8dmyh2abvr6lvh6c2iad7-python3-3.10.11-env/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

### Notify maintainers

@necessarily-equal 
@afontaine 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.108, NixOS, 22.11 (Raccoon), 22.11.20230424.f536431`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixpkgs"`
 - channels(wout): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/235974
