### ISSUE TITLE
Build failure: python310

### ISSUE THREAD

**Issue by happysalada** [NixOS/nixpkgs#236170]
### Steps To Reproduce

using latest nixpkgs-unstable, I'm getting a runtime error on python310
the error is `ValueError: bad marshal data (unknown type code)`

### logs

```
Traceback (most recent call last):
  File "/nix/store/ixqb34mrwk6dpqp9hk88zr91m5s1g6gd-python3.10-mypy-1.0.1/bin/.mypy-wrapped", line 6, in >
    from mypy.__main__ import console_entry
  File "/nix/store/ixqb34mrwk6dpqp9hk88zr91m5s1g6gd-python3.10-mypy-1.0.1/lib/python3.10/site-packages/my>
    from mypy.main import main, process_options
  File "mypy/main.py", line 14, in <module>
  File "mypy/build.py", line 47, in <module>
  File "mypy/semanal_main.py", line 35, in <module>
  File "mypy/checker.py", line 27, in <module>
  File "mypy/checkexpr.py", line 13, in <module>
  File "mypy/applytype.py", line 5, in <module>
  File "mypy/subtypes.py", line 8, in <module>
  File "mypy/constraints.py", line 9, in <module>
  File "mypy/typeops.py", line 13, in <module>
  File "mypy/copytype.py", line 5, in <module>
  File "mypy/types.py", line 23, in <module>
    CellType = type(_cell_factory())
  File "mypy/nodes.py", line 27, in <module>
  File "mypy/strconv.py", line 10, in <module>
  File "mypy/util.py", line 8, in <module>
  File "/nix/store/yhpwdgqsrfm5r4x7ycbgj04aq7063rli-python3-3.10.11/lib/python3.10/pathlib.py", line 14, >
    from urllib.parse import quote_from_bytes as urlquote_from_bytes
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
```

### Additional context

the logs are coming from systemd-boot, any derivation using python encounters this runtime error

### Notify maintainers

@FRidh I'm not sure if you are the right person for this issue, happy to ping others if you think this is related to something else.

I can't figure out if this is something particular to my setup, but I don't think it would be.
Happy to give more information about anything, as this prevents me from updating my system.

**Comment by kirillrdy** [comment]
greetings ! @happysalada 
is error reproducible in `nixos-rebuild build-vm` ? if so, maybe you can provide minimal setup to reproduce
