### ISSUE TITLE
Lutris: Fails to start since 23.05

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#236231]
### Describe the bug
Starting Lutris fails since upgrading to NixOS 23.05.
```
$ lutris
Traceback (most recent call last):
  File "/nix/store/3jyl9g4p1skw9m3h7lnjfnk30b2sk1h0-lutris-unwrapped-0.5.13/bin/.lutris-wrapped", line 53, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/nix/store/3jyl9g4p1skw9m3h7lnjfnk30b2sk1h0-lutris-unwrapped-0.5.13/lib/python3.10/site-packages/lutris/gui/application.py", line 35, in <module>
    from lutris import settings
  File "/nix/store/3jyl9g4p1skw9m3h7lnjfnk30b2sk1h0-lutris-unwrapped-0.5.13/lib/python3.10/site-packages/lutris/settings.py", line 9, in <module>
    from lutris.util.settings import SettingsIO
  File "/nix/store/3jyl9g4p1skw9m3h7lnjfnk30b2sk1h0-lutris-unwrapped-0.5.13/lib/python3.10/site-packages/lutris/util/settings.py", line 6, in <module>
    from lutris.util.log import logger
  File "/nix/store/3jyl9g4p1skw9m3h7lnjfnk30b2sk1h0-lutris-unwrapped-0.5.13/lib/python3.10/site-packages/lutris/util/log.py", line 14, in <module>
    os.makedirs(CACHE_DIR)
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/var/tmp'
```

### Additional context
/var/tmp is not read-only on the system.
Starting the latest Lutris from 22.11 is working fine, even on 23.05:
```
$ /nix/store/xizksg1yqssabhbrwbhpz4ab5g39hsjs-lutris/bin/lutris
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/98sq0hkrbda37k9iayqdqchkibp8530y-llvm-15.0.7-lib/lib/libLLVM-15.so) (search paths /run/opengl-driver/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/98sq0hkrbda37k9iayqdqchkibp8530y-llvm-15.0.7-lib/lib/libLLVM-15.so) (search paths /run/opengl-driver/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  72
  Current serial number in output stream:  73
2023-06-06 10:27:18,836: ['glxinfo', '-B'] command failed: Command '['glxinfo', '-B']' returned non-zero exit status 1.
2023-06-06 10:27:18,837: No available glxinfo output
2023-06-06 10:27:18,837: Invalid glxinfo received
2023-06-06 10:27:21,409: Starting Lutris 0.5.11
2023-06-06 10:27:21,500: glxinfo is not available on your system, unable to detect driver version
2023-06-06 10:27:21,500: GPU: 1002:1638 17AA:3AB1 (amdgpu drivers)
2023-06-06 10:27:21,501: GPU: 1002:73FF 17AA:3AB1 (amdgpu drivers)
2023-06-06 10:27:21,565: Vulkan is not available or your system isn't Vulkan capable
2023-06-06 10:27:22,972: Startup complete
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.553.e7603eba51f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by StefanSchroeder** [comment]
I am running 23.05 (installed from scratch). `lutris`works on my machine. 0.5.13.
```

- system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.533.c37ca420157`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - channels(bert): `"home-manager-23.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tokudan** [comment]
I think I've figured out what's going on.
$ ls -lad ~/.cache
lrwxrwxrwx 1 myuser users 22 10. Jul 2022  /home/myuser/.cache -> /var/tmp/myuser/.cache
Since the update to 23.05 Lutris apparently wants to use ~/.cache/lutris. Which breaks, because the Lutris-wrapper remounts pretty much everything read-only.
So /var/tmp should be added to the writeable mounts
