### ISSUE TITLE
pypi2nix: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by rasendubi** [NixOS/nixpkgs#23656]
## Issue description
```
rasen@Larry ~/nixpkgs> nix-build -A pypi2nix
/nix/store/i92z0s0w9a7k9p3wd2zz8fglcd7f134r-pypi2nix-1.6.0
rasen@Larry ~/nixpkgs> ./result/bin/pypi2nix 
Traceback (most recent call last):
  File "/nix/store/i92z0s0w9a7k9p3wd2zz8fglcd7f134r-pypi2nix-1.6.0/bin/.pypi2nix-wrapped", line 2, in <module>
    import pypi2nix.cli
  File "/nix/store/i92z0s0w9a7k9p3wd2zz8fglcd7f134r-pypi2nix-1.6.0/pkgs/pypi2nix/cli.py", line 9, in <module>
    import pypi2nix.stage2
  File "/nix/store/i92z0s0w9a7k9p3wd2zz8fglcd7f134r-pypi2nix-1.6.0/pkgs/pypi2nix/stage2.py", line 9, in <module>
    import pkg_resources
ImportError: No module named 'pkg_resources'
```

### Steps to reproduce

```
nix-build -A pypi2nix
./result/bin/pypi2nix
```

## Technical details

* System: 17.03.git.1aa77d0519 (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 17.09.git.3c02be6

/cc @garbas

**Comment by garbas** [comment]
@rasendubi can you try pypi2nix master[1] and see if the problem already exists.

also please report pypi2nix issues to pypi2nix issue tracker.

[1] https://github.com/garbas/pypi2nix

**Comment by rasendubi** [comment]
I have tried the following and I don't see the issue:
```
git clone https://github.com/garbas/pypi2nix.git
cd pypi2nix
nix-build shell.nix
./result/bin/pypi2nix
```

As for the issue tracker, the reason I chose nixpkgs over pypi2nix is that the problem looks like packaging error rather than programming one.
