### ISSUE TITLE
flare-signal broken on unstable

### ISSUE THREAD

**Issue by SharkLava** [NixOS/nixpkgs#236603]
### Describe the bug
flare-signal crashes on launch

### Steps To Reproduce
1. run `flare`

### Expected behavior
flare-signal should launch as per usual

### Additional context
when I launch it from the terminal with RUST_BACKTRACE=1 I get this 
```console
➜  ~ flare                        
thread 'main' panicked at 'Failed to retrieve template child. Please check that it has been bound and has a #[template_child] attribute.', /build/cargo-vendor-dir/gtk4-0.4.8/src/subclass/widget.rs:1305:17
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <flare::gui::channel_messages::imp::ChannelMessages as gtk4::subclass::widget::CompositeTemplate>::check_template_children
   3: glib::subclass::types::instance_init
   4: g_type_create_instance
   5: g_object_new_internal
   6: g_object_new_with_properties
   7: g_object_new
   8: _gtk_builder_construct
   9: builder_construct
  10: end_element
  11: proxy_end_element
  12: _gtk_buildable_parser_replay_precompiled
  13: _gtk_builder_parser_parse_buffer
  14: gtk_builder_extend_with_template
  15: gtk_widget_init_template
  16: glib::subclass::types::instance_init
  17: g_type_create_instance
  18: g_object_new_internal
  19: g_object_newv
  20: glib::object::Object::new_internal
  21: glib::object::Object::with_type
  22: glib::object::Object::new
  23: flare::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

when I run it with RUST_BACKTRACE=full
```console
➜  ~ flare                     
thread 'main' panicked at 'Failed to retrieve template child. Please check that it has been bound and has a #[template_child] attribute.', /build/cargo-vendor-dir/gtk4-0.4.8/src/subclass/widget.rs:1305:17
stack backtrace:
   0:     0x5576a33dd5da - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1792633461806265
   1:     0x5576a340d88e - core::fmt::write::h86858dfe747be413
   2:     0x5576a33f35e5 - std::io::Write::write_fmt::h74e0842d6f1ebf1a
   3:     0x5576a33dd3a5 - std::sys_common::backtrace::print::h18201883e81727b4
   4:     0x5576a33f3f6f - std::panicking::default_hook::{{closure}}::he7684422edfb8e5d
   5:     0x5576a33f3c35 - std::panicking::default_hook::h0f55305c4c7e7f71
   6:     0x5576a33f4438 - std::panicking::rust_panic_with_hook::hb89fb9ee5a2c564f
   7:     0x5576a33ddc62 - std::panicking::begin_panic_handler::{{closure}}::hc641e1ce95f25c1f
   8:     0x5576a33dd6e6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6a9bb70d00ab18d8
   9:     0x5576a33f4122 - rust_begin_unwind
  10:     0x5576a2b7d4a3 - core::panicking::panic_fmt::h71a20a5609c5aabf
  11:     0x5576a2e1cb70 - <flare::gui::channel_messages::imp::ChannelMessages as gtk4::subclass::widget::CompositeTemplate>::check_template_children::h9502b250ae3075b4
  12:     0x5576a2d03bf8 - glib::subclass::types::instance_init::h6657183d28de568a
  13:     0x7fa53a85c7e1 - g_type_create_instance
  14:     0x7fa53a8400b0 - g_object_new_internal
  15:     0x7fa53a84180c - g_object_new_with_properties
  16:     0x7fa53a842411 - g_object_new
  17:     0x7fa53ad0e4d9 - _gtk_builder_construct
  18:     0x7fa53ad10055 - builder_construct
  19:     0x7fa53ad129a2 - end_element
  20:     0x7fa53ad101df - proxy_end_element
  21:     0x7fa53aeb4778 - _gtk_buildable_parser_replay_precompiled
  22:     0x7fa53ad1338c - _gtk_builder_parser_parse_buffer
  23:     0x7fa53ad0bb7f - gtk_builder_extend_with_template
  24:     0x7fa53ae90d2f - gtk_widget_init_template
  25:     0x5576a2d0456e - glib::subclass::types::instance_init::he0f4183fbdb124cd
  26:     0x7fa53a85c7e1 - g_type_create_instance
  27:     0x7fa53a8400b0 - g_object_new_internal
  28:     0x7fa53a841a20 - g_object_newv
  29:     0x5576a33c44c0 - glib::object::Object::new_internal::h6189e5c9a1db6ecb
  30:     0x5576a33c402f - glib::object::Object::with_type::hd3b419f1430affd3
  31:     0x5576a2ea75eb - glib::object::Object::new::h80337d10b643fde2
  32:     0x5576a2dd4b0b - flare::main::he41faf6cbad0fd72
  33:     0x5576a2b898c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h74e1f82731880c14
  34:     0x5576a2dfced9 - std::rt::lang_start::{{closure}}::ha9edb6f92b6d19c3
  35:     0x5576a33e93c8 - std::rt::lang_start_internal::h34bd518f25d68bbe
  36:     0x5576a2dd5215 - main
  37:     0x7fa53a249ace - __libc_start_call_main
  38:     0x7fa53a249b89 - __libc_start_main@@GLIBC_2.34
  39:     0x5576a2b7d9f5 - _start
  40:                0x0 - <unknown>
```
### Notify maintainers

@dotlambda @tomfitzhenry 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
➜  ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.3, NixOS, 23.05 (Stoat), 23.05.20230518.48a0fb7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/h2mn9hkw60rhlv4fyhz287127dim9r01-source`
```

**Comment by FliegendeWurst** [comment]
I think this was fixed by #244659
