### ISSUE TITLE
`nixosTests.systemd-boot.update` fails

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#237073]
### Steps To Reproduce

```
[nixpkgs]$ nix-build -A nixosTests.systemd-boot.update
```

### Build log

```
[...]
machine # Traceback (most recent call last):
machine #   File "/nix/store/8c27ljrks2590wmdr1pcg3a7l3j4nhxm-systemd-boot", line 341, in <module>
machine #     main()
machine #   File "/nix/store/8c27ljrks2590wmdr1pcg3a7l3j4nhxm-systemd-boot", line 276, in main
machine #     installed_version = version.parse(installed_match.group(1))
machine #   File "/nix/store/29hqagzwk37gc430pdrf21fpzwsld08l-python3-3.10.11-env/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
machine #     return Version(version)
machine #   File "/nix/store/29hqagzwk37gc430pdrf21fpzwsld08l-python3-3.10.11-env/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
machine #     raise InvalidVersion(f"Invalid version: '{version}'")
machine # packaging.version.InvalidVersion: Invalid version: '000.0-1-notnixos'
[...]
Exception: command `/run/current-system/bin/switch-to-configuration boot` failed (exit code 1)
```

### Notify maintainers

@danielfullmer 

### Metadata

Nixpkgs commit: a30520bf8eabf8a5c37889d661e67a2dbcaa59e6

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by RaitoBezarius** [comment]
This is a running gag and has something upstream saying that `bootctl` output should not be relied upon.
