### ISSUE TITLE
opensearch-cli cannot find java "in bundled sdk"

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#237057]
### Describe the bug
```shell
# opensearch-cli  --help
could not find java in bundled jdk at /nix/store/149bqp23jjml2mngdvw9alamf0znsg1r-opensearch-2.7.0/jdk/bin/java
```

### Steps To Reproduce
1. Set up opensearch
2. Try to run `opensearch-cli`

### Expected behavior
The CLI should be working.

### Additional information

After symlinking `jre_headless` into `$out/jdk` I get

```
# opensearch-cli  --help
Error: Could not find or load main class 
Caused by: java.lang.ClassNotFoundException: 
```

### Notify maintainers

@shyim 

### Metadata
nixos-23.05/nixos-unstable

**Comment by shyim** [comment]
wrapping is missing for `opensearch-cli` https://github.com/NixOS/nixpkgs/blob/21951114383770f96ae528d0ae68824557768e81/pkgs/servers/search/opensearch/default.nix#L41

**Comment by shyim** [comment]
I can reproduce that also outside of Nix. I asked in Opensearch Slack if someone has an idea 😅

**Comment by shyim** [comment]
![image](https://github.com/NixOS/nixpkgs/assets/6224096/71901277-439c-4d93-aebd-ee3317c89674)

seems like bundled by mistake. I will make a PR to delete that file. Maybe we should package then opensearch-cli as separate package :)

**Comment by mweinelt** [comment]
Do you still plan to do that PR? :wink:

**Comment by colemickens** [comment]
I've installed `opensearch` and `opensearch-cli` but it seems they still don't really work. I'm guessing `opensearch` is calling `opensearch-keystore` which is calling `opensearch-cli` in the wrong location.

```

╭ zeph  ~/work/code/flakehub/experimental dev-env 10sec 175ms
╰🡒  opensearch
/nix/store/gi9ar6wrkdfv1y8qhd1jlmwpv9g0cpsh-opensearch-2.11.1/bin/opensearch-keystore: line 5: /nix/store/gi9ar6wrkdfv1y8qhd1jlmwpv9g0cpsh-opensearch-2.11.1/bin/open
search-cli: No such file or directory
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.000s][error][logging] Error opening log file 'logs/gc.log': No such file or directory
[0.000s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.opensearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:125)
        at org.opensearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:87)
        at org.opensearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:70)
        at org.opensearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:150)
        at org.opensearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:108)

╭ zeph  ~/work/code/flakehub/experimental dev-env 244ms ✘1
╰🡒  /nix/store/gi9ar6wrkdfv1y8qhd1jlmwpv9g0cpsh-opensearch-2.11.1/bin/opensearch-keystore
/nix/store/gi9ar6wrkdfv1y8qhd1jlmwpv9g0cpsh-opensearch-2.11.1/bin/opensearch-keystore: line 5: /nix/store/gi9ar6wrkdfv1y8qhd1jlmwpv9g0cpsh-opensearch-2.11.1/bin/open
search-cli: No such file or directory
```

**Comment by dacevedo12** [comment]
I'm experiencing the same error. opensearch-keystore calls the bundled opensearch-cli but fails as it is removed in the installPhase script.

From the message above, are you sure the bundled cli is a mistake? If so, can opensearch-keystore work with the separate cli package introduced in https://github.com/NixOS/nixpkgs/pull/277065?

**Comment by dm-kialo** [comment]
Has anyone figured out how to fix this? I'm seeing the same error.

**Comment by shyim** [comment]
You cannot all `opensearch` without creating a "data dir" on your own.  See here https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/search/opensearch.nix#L197

You should use the service, that does everything for you

**Comment by toddmowen** [comment]
After a fair bit of investigation, I believe the confusion here is because "`opensearch-cli` bundled with the distribution" (in the words used in the screenshot above) and `opensearch-cli` provided by the new package added in #277065 are _two completely different programs_.

The first one (which has now been deleted from the `opensearch` nix package) is merely a 32-line bash script that is used to set some java-related environment variables. Removing it is the cause of #319323 (`opensearch-plugin` tool no longer works).

**Comment by toddmowen** [comment]
Until it is fixed in master, here is an example of adapting the `opensearch` derivative to (a) fix the "opensearch-cli: No such file or directory" error, and (b) install several plugins.

```
  opensearch-with-plugins = nixpkgs.opensearch.overrideAttrs (old: {
    # Workaround for packaging bug (deleting opensearch-cli breaks opensearch-plugin command)
    installPhase = builtins.replaceStrings ["rm $out/bin/opensearch-cli\n"] [""] old.installPhase;

    postInstall = ''
      # Install some plugins
      $out/bin/opensearch-plugin install analysis-icu analysis-smartcn analysis-kuromoji analysis-stempel
    '';
  });
```
