### ISSUE TITLE
Neovim 0.9.1 Python3 provider errors No module named 'greenlet'

### ISSUE THREAD

**Issue by DanielSiepmann** [NixOS/nixpkgs#237311]
### Steps To Reproduce
1. Install neovim 0.9.1 from unstable (/nix/store/v777qfyiinf796rgghiidn5fswgv3jyy-neovim-0.9.1/bin/nvim)
2. Start neovim with healthcheck `nvim -c "checkhealth"`
3. Check section "Python 3 provider (optional)"

### Expected behavior
There should be no error shown

### Screenshots
I'll post the text output of the section, should be better than a screenshot.
```
Python 3 provider (optional) ~
- Using: g:python3_host_prog = "/nix/store/v777qfyiinf796rgghiidn5fswgv3jyy-neovim-0.9.1/bin/nvim-python3"
- Executable: /nix/store/v777qfyiinf796rgghiidn5fswgv3jyy-neovim-0.9.1/bin/nvim-python3
- ERROR Command error (job=6, exit code 1): `'/nix/store/v777qfyiinf796rgghiidn5fswgv3jyy-neovim-0.9.1/bin/nvim-python3' -c 'import sys; sys.path = [p for p in sys.path if p != ""]; import neovim; print(neovim.__file__)'` (in '/home/daniels/Projects/company/customer/werkraum-media/hamburger-edition/project')
  stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>  File "/nix/store/vdmq8cy144647g0kjnc7yp2v0sylysr0-python3-3.10.11-env/lib/python3.10/site-packages/neovim/__init__.py", line 5, in <module>    import pynvim  File "/nix/store/vdmq8cy144647g0kjnc7yp2v0sylysr0-python3-3.10.11-env/lib/python3.10/site-packages/pynvim/__init__.py", line 11, in <module>    from pynvim.msgpack_rpc import (ErrorResponse, child_session, socket_session,  File "/nix/store/vdmq8cy144647g0kjnc7yp2v0sylysr0-python3-3.10.11-env/lib/python3.10/site-packages/pynvim/msgpack_rpc/__init__.py", line 10, in <module>    from pynvim.msgpack_rpc.session import ErrorResponse, Session  File "/nix/store/vdmq8cy144647g0kjnc7yp2v0sylysr0-python3-3.10.11-env/lib/python3.10/site-packages/pynvim/msgpack_rpc/session.py", line 7, in <module>    import greenletModuleNotFoundError: No module named 'greenlet'
- Python version: 3.10.11
- pynvim version: unable to load neovim Python module
- ERROR pynvim is not installed.
  Error: unable to load neovim Python module
  - ADVICE:
    - Run in shell: /nix/store/v777qfyiinf796rgghiidn5fswgv3jyy-neovim-0.9.1/bin/nvim-python3 -m pip install pynvim
```

### Notify maintainers

@manveru, @rvolosatovs, @wamserma, @lovesegfault 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/h78a7vdyqqx6c24ywlwirkblncqf4jqh-nix-info
copying path '/nix/store/h78a7vdyqqx6c24ywlwirkblncqf4jqh-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-150-generic, Ubuntu, 20.04.6 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(daniels): `"home-manager, nixpkgs, phps"`
 - nixpkgs: `/home/daniels/.nix-defexpr/channels/nixpkgs`
```

**Comment by figsoda** [comment]
seems to be broken by #237077, opened #237357 to fix it
