### ISSUE TITLE
Build failure: jenkins-job-builder

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#238226]
### Steps To Reproduce

1. `nix-build -A jenkins-job-builder`

### Build log

```
[...]
tests.test_plugins.PluginsTestScenarios.test_plugin_version_object_comparison(base_url2,s13)
--------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/build/python-jenkins-1.7.0/tests/test_plugins.py", line 311, in test_plugin_version_object_comparison
    plugin_info = j.get_plugins()[plugin_name]

      File "/build/python-jenkins-1.7.0/jenkins/__init__.py", line 939, in get_plugins
    plugins_data[keys] = plugins.Plugin(**plugin_data)

      File "/build/python-jenkins-1.7.0/jenkins/plugins.py", line 59, in __init__
    self['version'] = version

      File "/build/python-jenkins-1.7.0/jenkins/plugins.py", line 66, in __setitem__
    value = PluginVersion(value)

      File "/build/python-jenkins-1.7.0/jenkins/plugins.py", line 79, in __init__
    self.parsed_version = pkg_resources.parse_version(

      File "/nix/store/basb8wsyinlwbcawx0v9lklvv06qpph6-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")

    pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.0a.preview'
[...]
======                                                                                                                 
Totals                                                                                                                 
======                                                                                                                 
Ran: 600 tests in 4.0974 sec.                                                                                          
 - Passed: 592                                                                                                         
 - Skipped: 0                                                                                                          
 - Expected Fail: 0                                                                                                    
 - Unexpected Success: 0                                                                                               
 - Failed: 8                                                                                                           
[...]
error: builder for '/nix/store/6p6xqf08cd3fj5lnz2yhlhhp74q10j6f-python3.10-python-jenkins-1.7.0.drv' failed with exit code 1;
       last 10 log lines:
       >
       > ==============
       > Worker Balance
       > ==============
       >  - Worker 0 (94 tests) => 0:00:04.199205
       >  - Worker 1 (139 tests) => 0:00:04.257260
       >  - Worker 2 (91 tests) => 0:00:00.617901
       >  - Worker 3 (92 tests) => 0:00:04.147683
       >  - Worker 4 (92 tests) => 0:00:04.156221
       >  - Worker 5 (92 tests) => 0:00:04.181178
       For full logs, run 'nix log /nix/store/6p6xqf08cd3fj5lnz2yhlhhp74q10j6f-python3.10-python-jenkins-1.7.0.drv'.
error: 1 dependencies of derivation '/nix/store/17m131aya6dd610k58fa056nakfidnzm-python3.10-jenkins-job-builder-4.3.0.drv' failed to build
```

### Additional context

It's 8 tests blocking it from completing the build. It's a regression since release-22.11 -- now it's broken in both master and release-23.05 branches.

I think it's caused by 451c63214766d3bb8d078620cff4dc74463c5bc8 ("python310Packages.setuptools: 65.0.3 -> 67.4.0") and upstream did https://opendev.org/jjb/jenkins-job-builder/commit/571df29fd752cf80570f9648e1502d4571f9aaa6 to fix it (downgrading setuptools).

### Notify maintainers

There are no maintainers listed for jenkins-job-builder, but since it's technically python-jenkins that fails to build: CC @gador.

**Comment by bjornfor** [comment]
Upstream issue: https://github.com/pypa/setuptools/issues/3772 ("InvalidVersion exception when invalid version used on Setuptools 66").

**Comment by bjornfor** [comment]
> I think it's caused by https://github.com/NixOS/nixpkgs/commit/451c63214766d3bb8d078620cff4dc74463c5bc8 ("python310Packages.setuptools: 65.0.3 -> 67.4.0") [...]

Yes. Confirmed by git bisect. CC @mweinelt.

**Comment by bjornfor** [comment]
Fix (by disabling failing tests and relaxing setuptools version requirement): https://github.com/NixOS/nixpkgs/pull/238316
