### ISSUE TITLE
Redmine fails to start in fresh installation

### ISSUE THREAD

**Issue by wentasah** [NixOS/nixpkgs#238748]
### Describe the bug

See the steps and log below. According to <https://nixos.wiki/wiki/Redmine>, `services.redmine.enable = true;` should be sufficient.

### Steps To Reproduce
1. Add `services.redmine.enable = true;` to `configuration.nix`.
2. Run `nixos-rebuild switch`.
3. `redmine.service` fails

### Expected behavior
Redmine service starts.

### Additional context
`journalctl -u redmine` shows the following output:
```
systemd[1]: Starting redmine.service...
redmine-pre-start[18591]: bundler: failed to load command: rake (/nix/store/blk4f6gp615dd0nqs8qwrwvsqpan8575-redmine-env-5.0.5/lib/ruby/gems/3.1.0/bin/rake)
redmine-pre-start[18591]: /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/definition.rb:403:in `ensure_equivalent_gemfile_and_lockfile': You are trying to install in deployment mode after changing (Bundler
redmine-pre-start[18591]: your Gemfile. Run `bundle install` elsewhere and add the
redmine-pre-start[18591]: updated ../../../7arw0hdyyjgz9jqr0d94ig6m8ncz78g3-gemfile-and-lockfile/Gemfile.lock to version control.
redmine-pre-start[18591]: The dependencies in your gemfile changed
redmine-pre-start[18591]: You have added to the Gemfile:
redmine-pre-start[18591]: * rexml
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/runtime.rb:13:in `setup'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler.rb:161:in `setup'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/setup.rb:20:in `block in <top (required)>'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/ui/shell.rb:136:in `with_level'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/ui/shell.rb:88:in `silence'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/setup.rb:20:in `<top (required)>'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/cli/exec.rb:56:in `require_relative'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/cli/exec.rb:56:in `kernel_load'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/cli.rb:486:in `exec'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:48:in `block in <top (required)>'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
redmine-pre-start[18591]:         from /nix/store/d3mglw6m4ikwf7aw0rxz3abj5cv176ha-ruby-3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:36:in `<top (required)>'
redmine-pre-start[18591]:         from /nix/store/389iqi86wxiyhw3rsg1w925ncr4xpqmh-redmine-5.0.5/share/redmine/bin/bundle:4:in `load'
redmine-pre-start[18591]:         from /nix/store/389iqi86wxiyhw3rsg1w925ncr4xpqmh-redmine-5.0.5/share/redmine/bin/bundle:4:in `<main>'
```

### Notify maintainers

@aanderse @felixsinger @megheaiulian

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.34, NixOS, 23.05 (Stoat), 23.05.1156.ad157fe26e7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aanderse** [comment]
see https://github.com/NixOS/nixpkgs/pull/235668

**Comment by felixsinger** [comment]
Sorry, unfortunately I got busy. I will finish the PR tomorrow.
