### ISSUE TITLE
Current NetworkManager in `master` causes a build failure by creating/accessing /homeless-shelter

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#23928]
## Issue description

Due to installing `megatools` from `master`, I had a copy of NetworkManager being installed from `master` as well, but the build failed and caused my entire rebuild to fail. One of the errors I ran into was as follows:

```
  CCLD     libtest-crypto.la
[ 967/2913] Compiling librpc/rpc/binding_handle.c
[ 968/2913] Compiling source4/lib/http/http.c
/nix/store/5pwz6vmsmg4phpfahs904fmn6ki2vp91-binutils-2.27/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  GISCAN   NetworkManager-1.0.gir
Traceback (most recent call last):
  File "/nix/store/5g7wqn16ilv5pj7b9sa8n30yahbp1w6s-gobject-introspection-1.50.0-dev/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/nix/store/p67vgw9c4l4hbcx3b1r4sjkl88l3h1kb-gobject-introspection-1.50.0/lib/gobject-introspection/giscanner/scannermain.py", line 563, in scanner_main
    transformer = create_transformer(namespace, options)
  File "/nix/store/p67vgw9c4l4hbcx3b1r4sjkl88l3h1kb-gobject-introspection-1.50.0/lib/gobject-introspection/giscanner/scannermain.py", line 420, in create_transformer
    symbol_filter_cmd=options.symbol_filter_cmd)
  File "/nix/store/p67vgw9c4l4hbcx3b1r4sjkl88l3h1kb-gobject-introspection-1.50.0/lib/gobject-introspection/giscanner/transformer.py", line 54, in __init__
    self._cachestore = CacheStore()
  File "/nix/store/p67vgw9c4l4hbcx3b1r4sjkl88l3h1kb-gobject-introspection-1.50.0/lib/gobject-introspection/giscanner/cachestore.py", line 61, in __init__
    self._check_cache_version()
  File "/nix/store/p67vgw9c4l4hbcx3b1r4sjkl88l3h1kb-gobject-introspection-1.50.0/lib/gobject-introspection/giscanner/cachestore.py", line 77, in _check_cache_version
    with open(version, 'r') as version_file:
IOError: [Errno 13] Permission denied: u'/homeless-shelter/.cache/g-ir-scanner/.cache-version'
make[4]: *** [/nix/store/p67vgw9c4l4hbcx3b1r4sjkl88l3h1kb-gobject-introspection-1.50.0/share/gobject-introspection-1.0/Makefile.introspection:156: NetworkManager-1.0.gir] Error 1
make[4]: Leaving directory '/tmp/nix-build-network-manager-1.4.4.drv-0/NetworkManager-1.4.4/libnm-util'
make[3]: *** [Makefile:1013: all-recursive] Error 1
make[3]: Leaving directory '/tmp/nix-build-network-manager-1.4.4.drv-0/NetworkManager-1.4.4/libnm-util'
make[2]: *** [Makefile:736: all] Error 2
make[2]: Leaving directory '/tmp/nix-build-network-manager-1.4.4.drv-0/NetworkManager-1.4.4/libnm-util'
make[1]: *** [Makefile:654: all-recursive] Error 1
make[1]: Leaving directory '/tmp/nix-build-network-manager-1.4.4.drv-0/NetworkManager-1.4.4'
make: *** [Makefile:563: all] Error 2
builder for ‘/nix/store/pin99m2acl3cj9w8y26s1qd9j6p7c1r0-network-manager-1.4.4.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/lb96i67nl6r8aln16gkfffr0hf3hqq2q-libproxy-0.4.13.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/6wn02alg5f9r84kdh71vkg1dx9vf42i4-glib-networking-2.50.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/z5g6566j1blaxzmmigrymcypg2fj5ss5-megatools-1.9.98.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/9ys7w35hv326a1228qld2rwjaqfppzhz-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/48r5g1vsfj8mjk5sn4n74xg5g8wbp41f-nixos-system-desktop-home-16.09.1836.067e66a.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/48r5g1vsfj8mjk5sn4n74xg5g8wbp41f-nixos-system-desktop-home-16.09.1836.067e66a.drv’ failed
```

A grep through the contents of `/homeless-shelter` turned up the following:

```
[root@desktop-home:/homeless-shelter/.cache/g-ir-scanner]# cat * | grep store
V/nix/store/ywxrbwmf462bmlkbxafn4bflaf8wvi7b-gtk+-2.24.31/lib/libgdk-x11-2.0.so.0
V/nix/store/1dkib0zqk3kg9z2hhh5kr6gliqv6f09q-atk-2.22.0/lib/libatk-1.0.so.0
V/nix/store/9kr53z2fv6svfwlliqm36chakz4ga3p2-gdk-pixbuf-2.36.5/lib/libgdk_pixbuf-2.0.so.0
V/nix/store/0cyypmsk5wmq97gqxzwwsv1b628lal55-glib-2.50.3/lib/libgmodule-2.0.so.0
V/nix/store/0cyypmsk5wmq97gqxzwwsv1b628lal55-glib-2.50.3/lib/libgobject-2.0.so.0
aV/nix/store/0cyypmsk5wmq97gqxzwwsv1b628lal55-glib-2.50.3/lib/libglib-2.0.so.0
V/nix/store/0qk514ghbw9kdm5ghw071hf16zjm307a-pango-1.40.3/lib/libpango-1.0.so.0
V/nix/store/0cyypmsk5wmq97gqxzwwsv1b628lal55-glib-2.50.3/lib/libgio-2.0.so.0
S'g_list_store_get_type'
S'list_store'
V/nix/store/0cyypmsk5wmq97gqxzwwsv1b628lal55-glib-2.50.3/lib/libgobject-2.0.so.0
```

I *suspect* that the NetworkManager process created the /homeless-shelter directory as a part of its build process. Checking out my copy of the repository at `57e768f` instead of `master` and rebuilding (after removing /homeless-shelter) made the issue disappear, and after that my build succeeded.

I am __not__ certain that NetworkManager was what originally created the /homeless-shelter directory - it might also have been trying to use it because it was there. But really, I don't have a better lead on this issue than the output above, and the library references in the grepped files match up with NetworkManager.

### Steps to reproduce

1. Check out at `master`, probably 1ea6860cc7352ad739c5a4ac2244c5895a60a21b specifically.
2. Install `megatools` (with `nix-daemon` set up, eg. on NixOS)

## Technical details

* System: 16.09.1836.067e66a (Flounder)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: Unsure, but *probably* reproducible at 1ea6860cc7352ad739c5a4ac2244c5895a60a21b.

**Comment by copumpkin** [comment]
I'm guessing someone does `mkdir -p $HOME/...` at some point. Curious how it even had the permissions needed to create a directory in root though...

**Comment by joepie91** [comment]
Well...

```
$ ls -al /
total 112
drwxr-xrwx  17 root root  4096 Mar 15 16:48 .
[...]
```

Not sure why that's world-writable.

**Comment by globin** [comment]
Cannot reproduce on `master`, `release-16.09`, `release-17.03`

**Comment by joepie91** [comment]
How would I track down where the `$HOME` creation originates from? `inotify` won't watch non-existent directory creation, `auditd` refuses to track filesystem events on `/`.
