### ISSUE TITLE
Unable to use 32-bit wine and launch some emulator games after an update

### ISSUE THREAD

**Issue by MarkGhanz** [NixOS/nixpkgs#239515]
### Describe the bug
After a `nixos-rebuild switch --recreate-lock-file --commit-lock-file`, I find both the kernel and mesa have a version bump, but I am unable to play games through 32-bit wine and switch emulators (flatpaks). And `xdg-desktop-portal-hyprland` keeps complaining 
```
Jun 23 23:38:05 D-DREAM-1 xdg-desktop-portal-hyprland[4377]: DRI driver not from this Mesa build ('23.1.2' vs '23.1.1')
Jun 23 23:38:05 D-DREAM-1 xdg-desktop-portal-hyprland[4377]: failed to bind extensions
Jun 23 23:38:05 D-DREAM-1 xdg-desktop-portal-hyprland[4377]: DRI driver not from this Mesa build ('23.1.2' vs '23.1.1')
Jun 23 23:38:05 D-DREAM-1 xdg-desktop-portal-hyprland[4377]: failed to bind extensions
Jun 23 23:38:05 D-DREAM-1 xdg-desktop-portal-hyprland[4377]: DRI driver not from this Mesa build ('23.1.2' vs '23.1.1')
Jun 23 23:38:05 D-DREAM-1 xdg-desktop-portal-hyprland[4377]: failed to bind extensions
Jun 23 23:38:05 D-DREAM-1 xdg-desktop-portal-hyprland[4377]: DRI driver not from this Mesa build ('23.1.2' vs '23.1.1')
Jun 23 23:38:05 D-DREAM-1 xdg-desktop-portal-hyprland[4377]: failed to bind extensions
Jun 23 23:38:05 D-DREAM-1 xdg-desktop-portal-hyprland[4377]: 2023/06/23 23:38:05 [ERROR] - System doesn't support gbm!
```

### Steps To Reproduce
1. `sudo nixos-rebuild switch --recreate-lock-file --commit-lock-file` given `nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable"` in `flake.nix`.
2. Check if there's a version bump of the kernel or mesa.
3. `cd` into the directory of `Wine-GE-Proton-8-8` used by heroic, and `cd bin`, and run `ldd wine`
4. Check `systemctl --user status xdg-desktop-portal-hyprland`
5. Run a game in yuzu or ryujinx

### Expected behavior
`xdg-desktop-portal-hyprland` does not complains about version difference, and 32-bit wine is usable (`ldd wine` returns a list of shared libraries instead of `not a dynamic executable`

### Additional context
`ldd wine64` in the same directory of `wine` do return a list of shared libraries, and Cemu works fine while the switch emulators fails.
The output of the command used by heroic to launch Fall Guys, for example:
```
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 0a2d9f6403244d12969e11da6713137b...
Traceback (most recent call last):
  File "/nix/store/l1qk2arzpsk8mwhh5hahb4bc1dfz9y0m-legendary-gl-0.20.32/bin/.legendary-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/l1qk2arzpsk8mwhh5hahb4bc1dfz9y0m-legendary-gl-0.20.32/lib/python3.10/site-packages/legendary/cli.py", line 2976, in main
    cli.launch_game(args, extra)
  File "/nix/store/l1qk2arzpsk8mwhh5hahb4bc1dfz9y0m-legendary-gl-0.20.32/lib/python3.10/site-packages/legendary/cli.py", line 697, in launch_game
    subprocess.Popen(full_params, cwd=params.working_directory, env=full_env)
  File "/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/karm2/.config/heroic/tools/wine/Wine-GE-Proton8-8/bin/wine'
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.3.9, NixOS, 23.11 (Tapir), 23.11.20230623.3ae20aa`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `""`
 - nixpkgs: `not found`
```

**Comment by MarkGhanz** [comment]
Well...After removing `programs.steam` configuration everything starts to work again. I really wonder what happens in the steam configuration to prevent wine from working.
