### ISSUE TITLE
Build failure: kanjidraw

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#240103]
### Steps To Reproduce

`nix build .#kanjidraw`

### Build log

```
log here if short otherwise a link to a gist
trace: /nix/store/z56pw70zn945wp6dx2zhvbflncd4fw4r-vim-pack-dir
note: keeping build directory '/tmp/nix-build-kanjidraw-0.2.3.drv-0'
error: builder for '/nix/store/zkic1k4b14wg4p0w90f1gbl8dcmd1naf-kanjidraw-0.2.3.drv' failed with exit code 2;
       last 60 log lines:
       > writing dependency_links to kanjidraw.egg-info/dependency_links.txt
       > writing entry points to kanjidraw.egg-info/entry_points.txt
       > writing top-level names to kanjidraw.egg-info/top_level.txt
       > writing manifest file 'kanjidraw.egg-info/SOURCES.txt'
       > reading manifest file 'kanjidraw.egg-info/SOURCES.txt'
       > reading manifest template 'MANIFEST.in'
       > adding license file 'LICENSE.AGPLv3'
       > writing manifest file 'kanjidraw.egg-info/SOURCES.txt'
       > Copying kanjidraw.egg-info to build/bdist.linux-x86_64/wheel/kanjidraw-0.2.3-py3.10.egg-info
       > running install_scripts
       > creating build/bdist.linux-x86_64/wheel/kanjidraw-0.2.3.dist-info/WHEEL
       > creating 'dist/kanjidraw-0.2.3-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
       > adding 'kanjidraw/__init__.py'
       > adding 'kanjidraw/data.json'
       > adding 'kanjidraw/gui.py'
       > adding 'kanjidraw/lib.py'
       > adding 'kanjidraw-0.2.3.dist-info/LICENSE.AGPLv3'
       > adding 'kanjidraw-0.2.3.dist-info/METADATA'
       > adding 'kanjidraw-0.2.3.dist-info/WHEEL'
       > adding 'kanjidraw-0.2.3.dist-info/entry_points.txt'
       > adding 'kanjidraw-0.2.3.dist-info/top_level.txt'
       > adding 'kanjidraw-0.2.3.dist-info/RECORD'
       > removing build/bdist.linux-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/source/dist /build/source
       > Processing ./kanjidraw-0.2.3-py3-none-any.whl
       > Installing collected packages: kanjidraw
       > Successfully installed kanjidraw-0.2.3
       > /build/source
       > Finished executing pipInstallPhase
       > pythonOutputDistPhase
       > Executing pythonOutputDistPhase
       > Finished executing pythonOutputDistPhase
       > post-installation fixup
       > shrinking RPATHs of ELF executables and libraries in /nix/store/lj63p383hrgjcsivlqk5zinslli3z576-kanjidraw-0.2.3
       > checking for references to /build/ in /nix/store/lj63p383hrgjcsivlqk5zinslli3z576-kanjidraw-0.2.3...
       > patching script interpreter paths in /nix/store/lj63p383hrgjcsivlqk5zinslli3z576-kanjidraw-0.2.3
       > stripping (with command strip and flags -S -p) in  /nix/store/lj63p383hrgjcsivlqk5zinslli3z576-kanjidraw-0.2.3/lib /nix/store/lj63p383hrgjcsivlqk5zinslli3z576-kanjidraw-0.2.3/bin
       > shrinking RPATHs of ELF executables and libraries in /nix/store/lajnz2l4vb59cpydf1vff22i99pn19z7-kanjidraw-0.2.3-dist
       > checking for references to /build/ in /nix/store/lajnz2l4vb59cpydf1vff22i99pn19z7-kanjidraw-0.2.3-dist...
       > patching script interpreter paths in /nix/store/lajnz2l4vb59cpydf1vff22i99pn19z7-kanjidraw-0.2.3-dist
       > Rewriting #!/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/bin/python3.10 to #!/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12
       > wrapping `/nix/store/lj63p383hrgjcsivlqk5zinslli3z576-kanjidraw-0.2.3/bin/kanjidraw'...
       > Executing pythonRemoveTestsDir
       > Finished executing pythonRemoveTestsDir
       > running install tests
       > python3 -m kanjidraw.gui --verbose --doctest
       > Traceback (most recent call last):
       >   File "/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/lib/python3.10/runpy.py", line 196, in _run_module_as_main
       >     return _run_code(code, main_globals, None,
       >   File "/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/lib/python3.10/runpy.py", line 86, in _run_code
       >     exec(code, run_globals)
       >   File "/build/source/kanjidraw/gui.py", line 25, in <module>
       >     import tkinter as tk
       >   File "/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/lib/python3.10/tkinter/__init__.py", line 37, in <module>
       >     import _tkinter # If this fails your Python may not be configured for Tk
       > ModuleNotFoundError: No module named '_tkinter'
       > make: *** [Makefile:12: test] Error 1
       For full logs, run 'nix log /nix/store/zkic1k4b14wg4p0w90f1gbl8dcmd1naf-kanjidraw-0.2.3.drv'.
note: keeping build directory '/tmp/nix-build-source.drv-1'
note: keeping build directory '/tmp/nix-build-source.drv-0'
error: 1 dependencies of derivation '/nix/store/zmpvnnkrhvn6az9ld8zl97k17b2p
```

### Additional context
I wanted to install jiten that used to work a few weeks ago

### Notify maintainers

@obfusk 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nixos-unstable with sandbox
```

**Comment by natsukium** [comment]
This is related to #238990.
I can build it on the current HEAD bf0b22ff023d0628270ac6f14a9c75a91cfdd11a.

**Comment by teto** [comment]
indeed it builds and works. Thanks
