### ISSUE TITLE
pypi2nix seems to be broken 

### ISSUE THREAD

**Issue by nlewo** [NixOS/nixpkgs#24111]
## Issue description
```
./result/bin/pypi2nix -h
Traceback (most recent call last):
  File "/nix/store/rp9hdj02sibvvdryhpv7qz01yzah260n-pypi2nix-1.6.0/bin/.pypi2nix-wrapped", line 2, in <module>
    import pypi2nix.cli
  File "/nix/store/rp9hdj02sibvvdryhpv7qz01yzah260n-pypi2nix-1.6.0/pkgs/pypi2nix/cli.py", line 9, in <module>
    import pypi2nix.stage2
  File "/nix/store/rp9hdj02sibvvdryhpv7qz01yzah260n-pypi2nix-1.6.0/pkgs/pypi2nix/stage2.py", line 9, in <module>
    import pkg_resources
ImportError: No module named 'pkg_resources'
```

### Steps to reproduce
On master,
```
nix-build ./ -A  pypi2nix
./result/bin/pypi2nix -h
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
15.09.706.45128de

**Comment by Mic92** [comment]
cc @garbas

**Comment by garbas** [comment]
this should be fixed in current master of pypi2nix, a release is pending. I will do the release once I'm out of the hospital (2-4 days)
