### ISSUE TITLE
Nixops 1.7: failed build

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#241492]
### Describe the bug
Erro build nixops 1.7:
```
nix build -f ./default.nix nixops
```
```
error: builder for '/nix/store/kcqw920b34jfp6fla1iic1rg1xqk3w1a-python2.7-flit-core-3.8.0.drv' failed with exit code 2;
       last 10 log lines:
       >     backend=self.pep517_backend,
       >   File "/nix/store/583q1g0p0vb6dvshr05pj0mfh13xczfv-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
       >     metadata_dir
       >   File "/nix/store/583q1g0p0vb6dvshr05pj0mfh13xczfv-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 196, in prepare_metadata_for_build_wheel
       >     '_allow_fallback': _allow_fallback,
       >   File "/nix/store/583q1g0p0vb6dvshr05pj0mfh13xczfv-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 284, in _call_hook
       >     raise BackendUnavailable(data.get('traceback', ''))
       > BackendUnavailable
       > Removed file:///build/source/flit_core from build tracker '/build/pip-req-tracker-QT4eGz'
       > Removed build tracker: '/build/pip-req-tracker-QT4eGz'
       For full logs, run 'nix log /nix/store/kcqw920b34jfp6fla1iic1rg1xqk3w1a-python2.7-flit-core-3.8.0.drv'.
error: 1 dependencies of derivation '/nix/store/fwmyjcizrkqigpbfwkdd8fmk75hqc7br-python2.7-urllib3-1.26.8.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r7nkv6ni735wwlprc9ma5vd2svgxpf21-python2.7-botocore-1.20.112.drv' failed to build
error: 1 dependencies of derivation '/nix/store/84abwymsxq5plilh4s7dmk03f45w1867-python2.7-requests-2.27.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jsl6827lzwdy4wx3drifgbfdh9bqsn4h-python2.7-adal-1.2.7.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vx7d8q4i6m8m278zcr7pji533vixj248-nixops-1.7.drv' failed to build
```
Probably a problem with the pythonPackages.flit-core package:
```
nix build -f ./default.nix pythonPackages.flit-core
```
```
python2.7-flit-core> Sourcing python-remove-tests-dir-hook
python2.7-flit-core> Sourcing python-catch-conflicts-hook.sh
python2.7-flit-core> Sourcing python-remove-bin-bytecode-hook.sh
python2.7-flit-core> Sourcing pip-build-hook
python2.7-flit-core> Using pipBuildPhase
python2.7-flit-core> Using pipShellHook
python2.7-flit-core> Sourcing pip-install-hook
python2.7-flit-core> Using pipInstallPhase
python2.7-flit-core> Sourcing python-imports-check-hook.sh
python2.7-flit-core> Using pythonImportsCheckPhase
python2.7-flit-core> Sourcing python-catch-conflicts-hook.sh
python2.7-flit-core> unpacking sources
python2.7-flit-core> unpacking source archive /nix/store/bj390985mf200rxs4z5626lgpw6vmsaf-source
python2.7-flit-core> source root is source
python2.7-flit-core> setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/tox.ini
python2.7-flit-core> patching sources
python2.7-flit-core> updateAutotoolsGnuConfigScriptsPhase
python2.7-flit-core> configuring
python2.7-flit-core> no configure script, doing nothing
python2.7-flit-core> building
python2.7-flit-core> Executing pipBuildPhase
python2.7-flit-core> Creating a wheel...
python2.7-flit-core> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
python2.7-flit-core> WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
python2.7-flit-core> Ignoring indexes: https://pypi.org/simple
python2.7-flit-core> Created temporary directory: /build/pip-ephem-wheel-cache-7AODUK
python2.7-flit-core> Created temporary directory: /build/pip-req-tracker-wOUHYb
python2.7-flit-core> Initialized build tracking at /build/pip-req-tracker-wOUHYb
python2.7-flit-core> Created build tracker: /build/pip-req-tracker-wOUHYb
python2.7-flit-core> Entered build tracker: /build/pip-req-tracker-wOUHYb
python2.7-flit-core> Created temporary directory: /build/pip-wheel-f17onB
python2.7-flit-core> Processing /build/source/flit_core
python2.7-flit-core>   Created temporary directory: /build/pip-req-build-hG9EFH
python2.7-flit-core>   Added file:///build/source/flit_core to build tracker '/build/pip-req-tracker-wOUHYb'
python2.7-flit-core>     Created temporary directory: /build/pip-modern-metadata-S81h_E
python2.7-flit-core>     Running command /nix/store/j2x9iyb14rhw60ph591vz7lkx4z883nw-python-2.7.18.6/bin/python2.7 /nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /build/tmpHDIw5H
python2.7-flit-core>     Preparing wheel metadata ... done
python2.7-flit-core> ERROR: Exception:
python2.7-flit-core> Traceback (most recent call last):
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
python2.7-flit-core>     status = self.run(options, args)
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
python2.7-flit-core>     return func(self, options, args)
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/commands/wheel.py", line 163, in run
python2.7-flit-core>     reqs, check_supported_wheels=True
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 180, in resolve
python2.7-flit-core>     discovered_reqs.extend(self._resolve_one(requirement_set, req))
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 385, in _resolve_one
python2.7-flit-core>     dist = self._get_dist_for(req_to_install)
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 337, in _get_dist_for
python2.7-flit-core>     dist = self.preparer.prepare_linked_requirement(req)
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
python2.7-flit-core>     return self._prepare_linked_requirement(req, parallel_builds)
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
python2.7-flit-core>     req, self.req_tracker, self.finder, self.build_isolation,
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
python2.7-flit-core>     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
python2.7-flit-core>     self.req.prepare_metadata()
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
python2.7-flit-core>     self.metadata_directory = self._generate_metadata()
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 542, in _generate_metadata
python2.7-flit-core>     backend=self.pep517_backend,
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
python2.7-flit-core>     metadata_dir
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 196, in prepare_metadata_for_build_wheel
python2.7-flit-core>     '_allow_fallback': _allow_fallback,
python2.7-flit-core>   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 284, in _call_hook
python2.7-flit-core>     raise BackendUnavailable(data.get('traceback', ''))
python2.7-flit-core> BackendUnavailable
python2.7-flit-core> Removed file:///build/source/flit_core from build tracker '/build/pip-req-tracker-wOUHYb'
python2.7-flit-core> Removed build tracker: '/build/pip-req-tracker-wOUHYb'
error: builder for '/nix/store/qvrcj0qcrfksrgj73hf594dxnaf8qg1f-python2.7-flit-core-3.8.0.drv' failed with exit code 2;
       last 10 log lines:
       >     backend=self.pep517_backend,
       >   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
       >     metadata_dir
       >   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 196, in prepare_metadata_for_build_wheel
       >     '_allow_fallback': _allow_fallback,
       >   File "/nix/store/qpdgjrn9dggh7qjkja78h0pd4swwpysr-python2.7-pip-20.3.4/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 284, in _call_hook
       >     raise BackendUnavailable(data.get('traceback', ''))
       > BackendUnavailable
       > Removed file:///build/source/flit_core from build tracker '/build/pip-req-tracker-wOUHYb'
       > Removed build tracker: '/build/pip-req-tracker-wOUHYb'
       For full logs, run 'nix log /nix/store/qvrcj0qcrfksrgj73hf594dxnaf8qg1f-python2.7-flit-core-3.8.0.drv'.
```

### Steps To Reproduce
1. Update to master branch.
2. Build nixops package.

### Notify maintainers
cc @fridh @SuperSandro2000

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.36, NixOS, 23.11 (Tapir)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(lafiel): `"nixos1-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by SuperSandro2000** [comment]
python2.7 is EOL, we probably need some extra override(s) here <https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/nixops/default.nix>.

I am not planning to invest any time into python2.7 things at this point.

**Comment by Izorkin** [comment]
At the moment in NixopsUnstable does not work some functions that me need. So all the time I worked with the stable version.

**Comment by bryango** [comment]
I believe the build is broken by https://github.com/NixOS/nixpkgs/pull/246963. It lands on master via https://github.com/NixOS/nixpkgs/pull/248496, and I can get python2 to build on [its parent](https://github.com/NixOS/nixpkgs/commit/bceafd3a3ad0494c87922993a271606acabccf3d) but afterward, not anymore. Maybe it's time to give up python2 and mark it as broken...

**Comment by Izorkin** [comment]
After this PR 240439 I have no nixops building.
