### ISSUE TITLE
snipe-it fails to build

### ISSUE THREAD

**Issue by leona-ya** [NixOS/nixpkgs#241556]
### Steps To Reproduce

Try to build `snipe-it` on current master or nixos-unstable (e.g. f50ca4172a82b27a7782ae304d6977a772dcc09d)

### Build log

```
[...]
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   TypeError

  Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98

  at vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:928
    924▕      * @param array $lastErrors
    925▕      *
    926▕      * @return void
    927▕      */
  ➜ 928▕     private static function setLastErrors(array $lastErrors)
    929▕     {
    930▕         static::$lastErrors = $lastErrors;
    931▕     }
    932▕

   Whoops\Exception\ErrorException

  Using ${var} in strings is deprecated, use {$var} instead

  at vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
     48▕     }
     49▕
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }

   Symfony\Component\ErrorHandler\Error\FatalError

  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/composer/ClassLoader.php(576): Whoops\Run->handleError(8192, 'Using ${var} in...', '/nix/store/s7kh...', 52)
#1 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/composer/ClassLoader.php(576): include()
#2 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/nix/store/s7kh...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Facade\\Ignition...')
#4 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements('Facade\\Ignition...')
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}('Facade\\Ignition...', 10)
#6 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter(Array, Object(Closure), 1)
#7 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(358): Illuminate\Support\Arr::where(Array, Object(Closure))
#8 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter(Object(Closure))
#9 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable(Object(Whoops\Exception\ErrorException))
#10 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable(Object(Whoops\Exception\ErrorException))
#11 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution(Object(Whoops\Exception\Inspector))
#12 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write(Object(Whoops\Exception\Inspector))
#13 /nix/store/s7kh387x1c0ql0vkmy11m6jj913v8w3i-snipe-it/vendor/filp/whoops/src/Whoops/Run.php(370): NunoMaduro\Collision\Handler->handle(Object(Whoops\Exception\ErrorException))
#14 [internal function]: Whoops\Run->handleException(Object(Whoops\Exception\ErrorException))
#15 {main}
  thrown

  at vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
     48▕     }
     49▕
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
error: builder for '/nix/store/mbmpb1frlsmlbmbfd10qb01fih89x810-snipe-it.drv' failed with exit code 255;
       last 10 log lines:
       >      48▕     }
       >      49▕
       >      50▕     protected function getCurrentBranch(string $directory): string
       >      51▕     {
       >   ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
       >      53▕
       >      54▕         if ($branch === "''") {
       >      55▕             $branch = 'current branch';
       >      56▕         }
       > Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
```

### Notify maintainers

@yayayayaka 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.9, NixOS, 23.11 (Tapir), [...]`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

nixpkgs commit: f50ca4172a82b27a7782ae304d6977a772dcc09d

**Comment by yayayayaka** [comment]
Thanks for the report! :heart: 

I'll start debugging tomorrow

**Comment by yayayayaka** [comment]
A bisect points to 3bb38590495. I'm going to pin PHP to 8.1 now.
