### ISSUE TITLE
kodiAddons.steam-library: No such file or directory 'which'

### ISSUE THREAD

**Issue by Soupstraw** [NixOS/nixpkgs#241746]
### Describe the bug
When I try to launch the kodi steam library, I get an error and the games do not show up. 
```
2023-07-05 21:48:47.360 T:1590    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'FileNotFoundError'>
                                                   Error Contents: [Errno 2] No such file or directory: 'which'
                                                   Traceback (most recent call last):
                                                     File "/home/telku/.kodi/addons/script.steam.launcher/default.py", line 2, in <module>
                                                       import resources.main
                                                     File "/home/telku/.kodi/addons/script.steam.launcher/resources/main.py", line 393, in <module>
                                                       fileChecker()
                                                     File "/home/telku/.kodi/addons/script.steam.launcher/resources/main.py", line 173, in fileChecker
                                                       if subprocess.call(["which", "xdotool"]) != 0:
                                                     File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/subprocess.py", line 345, in call
                                                       with Popen(*popenargs, **kwargs) as p:
                                                     File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/subprocess.py", line 971, in __init__
                                                       self._execute_child(args, executable, preexec_fn, close_fds,
                                                     File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/subprocess.py", line 1863, in _execute_child
                                                       raise child_exception_type(errno_num, err_msg, err_filename)
                                                   FileNotFoundError: [Errno 2] No such file or directory: 'which'
                                                   -->End of Python script error report<--
```

### Steps To Reproduce
1. enable the `steam-library` addon for Kodi
2. open the Steam Library plugin in Kodi

### Expected behavior
I expected my library of games to show up

### Notify maintainers

@aanderse 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.4, NixOS, 23.11 (Tapir), 23.11pre489472.5e871d8aa6f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aanderse** [comment]
Did you want to report a bug against the `steam-library` or the `steam-launcher` plugin? You have installed `steam-launcher` but the issue mentions `steam-library`.

**Comment by Soupstraw** [comment]
> Did you want to report a bug against the `steam-library` or the `steam-launcher` plugin? You have installed `steam-launcher` but the issue mentions `steam-library`.

Thanks for pointing that out, fixed it now
