### ISSUE TITLE
Backintime errors out on launch (Module 'packaging' not found)

### ISSUE THREAD

**Issue by DrymarchonShaun** [NixOS/nixpkgs#241966]
### Describe the bug
Backintime gives the following error when launched 
```
 backintime
Traceback (most recent call last):
  File "/nix/store/nsp76fn0fp8lh0jkkn8c0y4bz3zzrljw-backintime-common-1.3.3/lib/python3.10/site-packages/backintime/common/backintime.py", line 28, in <module>
    import config
  File "/nix/store/nsp76fn0fp8lh0jkkn8c0y4bz3zzrljw-backintime-common-1.3.3/lib/python3.10/site-packages/backintime/common/config.py", line 45, in <module>
    import tools
  File "/nix/store/nsp76fn0fp8lh0jkkn8c0y4bz3zzrljw-backintime-common-1.3.3/lib/python3.10/site-packages/backintime/common/tools.py", line 37, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

### Steps To Reproduce
1. `nix shell nixpkgs#backintime` (or `nix-shell -p backintime`)
2. run `backintime-qt`
3. application does not launch, giving the above error

### Expected behavior
The application to launch, without errors.

### Notify maintainers

Maintainers list is empty, last change was from the @r-ryantm bot 

### Metadata

```console
shaun@natrix ~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.20230610.d3bb401`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/0yzh1r9mhsr4vp5w96y3i0jgz3m2qzv6-source`
```

**Comment by DrymarchonShaun** [comment]
@bjornfor Update on this - it seems `backintime-common` has the same issue. 

```
backintime                                                    
Traceback (most recent call last):
  File "/nix/store/0vph10hp0j136rlx8khd7rz11m3gkpsy-backintime-common-1.3.3/lib/python3.10/site-packages/backintime/common/backintime.py", line 28, in <module>
    import config
  File "/nix/store/0vph10hp0j136rlx8khd7rz11m3gkpsy-backintime-common-1.3.3/lib/python3.10/site-packages/backintime/common/config.py", line 45, in <module>
    import tools
  File "/nix/store/0vph10hp0j136rlx8khd7rz11m3gkpsy-backintime-common-1.3.3/lib/python3.10/site-packages/backintime/common/tools.py", line 37, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

same steps to reproduce, just replacing `nix shell nixpkgs#backintime` with `nix shell nixpkgs#backintime-common` and executing`backintime` instead of `backintime-qt`

**Comment by bjornfor** [comment]
New PR: https://github.com/NixOS/nixpkgs/pull/246095
