### ISSUE TITLE
Build failure: python310Packages.omegaconf failure to build on darwwin

### ISSUE THREAD

**Issue by happysalada** [NixOS/nixpkgs#242249]
### Steps To Reproduce

build on darwin x86_64

### Build log

```
Removing setuptoolsCheckPhase
omegaconf> unpacking sources
omegaconf> unpacking source archive /nix/store/1whwzdq40b2xyjraxwmzvx21n1wp1s04-source
omegaconf> source root is source
omegaconf> setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/tests/test_utils.py
omegaconf> patching sources
omegaconf> applying patch /nix/store/rlhz6zhcbx5ha5ln8b9x9g4xq40cna9a-antlr4.patch
omegaconf> patching file build_helpers/build_helpers.py
omegaconf> removed 'build_helpers/bin/antlr-4.9.3-complete.jar'
omegaconf> configuring
omegaconf> no configure script, doing nothing
omegaconf> building
omegaconf> Executing setuptoolsBuildPhase
omegaconf> running bdist_wheel
omegaconf> running build
omegaconf> running build_py
omegaconf> running clean
omegaconf> Generating parsers with antlr4
omegaconf> running antlr
omegaconf> Generating parser for Python3: ['java', '-jar', '/nix/store/l5pz0hwfazxhj838qfpxbc8wq9bbg5kd-an
omegaconf> Traceback (most recent call last):
omegaconf>   File "/private/tmp/nix-build-python3.10-omegaconf-2.3.0.drv-0/source/nix_run_setup", line 8,
omegaconf>     exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __f
omegaconf>   File "setup.py", line 34, in <module>
omegaconf>     setuptools.setup(
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     return distutils.core.setup(**attrs)
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     return run_commands(dist)
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     dist.run_commands()
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     self.run_command(cmd)
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     super().run_command(command)
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     cmd_obj.run()
omegaconf>   File "/nix/store/i8zqi02dpc0sljnsn6azgb73jig7bnj8-python3.10-wheel-0.38.4/lib/python3.10/site
omegaconf>     self.run_command("build")
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     self.distribution.run_command(command)
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     super().run_command(command)
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     cmd_obj.run()
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     self.run_command(cmd_name)
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     self.distribution.run_command(command)
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     super().run_command(command)
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10
omegaconf>     cmd_obj.run()
omegaconf>   File "/private/tmp/nix-build-python3.10-omegaconf-2.3.0.drv-0/source/build_helpers/build_helpers.py", line 60, in run
omegaconf>     run_antlr(self)
omegaconf>   File "/private/tmp/nix-build-python3.10-omegaconf-2.3.0.drv-0/source/build_helpers/build_helpers.py", line 185, in run_antlr
omegaconf>     cmd.run_command("antlr")
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
omegaconf>     self.distribution.run_command(command)
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
omegaconf>     super().run_command(command)
omegaconf>   File "/nix/store/90vgvw70vlqj933grw0qvpad2ac9rhq7-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
omegaconf>     cmd_obj.run()
omegaconf>   File "/private/tmp/nix-build-python3.10-omegaconf-2.3.0.drv-0/source/build_helpers/build_helpers.py", line 47, in run
omegaconf>     subprocess.check_call(command)
omegaconf>   File "/nix/store/5cxanhipcbfxnrqgw2qsr3zqr4z711bj-python3-3.10.12/lib/python3.10/subprocess.py", line 369, in check_call
omegaconf>     raise CalledProcessError(retcode, cmd)
omegaconf> subprocess.CalledProcessError: Command '['java', '-jar', '/nix/store/l5pz0hwfazxhj838qfpxbc8wq9bbg5kd-antlr-4.12.0/share/java/antlr-4.12.0-complete.jar', '-Dlanguage=Python3', '-o', '/private/tmp/nix-build-python3.10-omegaconf-2.3.0.drv-0/source/omegaconf/grammar/gen', '-Xexact-output-dir', '-visitor', '/private/tmp/nix-build-python3.10-omegaconf-2.3.0.drv-0/source/omegaconf/grammar/OmegaConfGrammarLexer.g4']' died with <Signals.SIGKILL: 9>.
```

### Notify maintainers

@bcdarwin should we just mark it broken for darwin ?
(not sure if this is supposed to work, I was just surprised by the build failure).

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by bcdarwin** [comment]
This does seem a bit strange -- is it possible the build is getting OOM-killed?  Unfortunately I don't have a Mac to test on currently -- maybe we want to let Hydra take this up once `pydevd` is building on OS X again?

**Comment by happysalada** [comment]
Sounds good to me, i just submitted a PR to remove the tests that were failing on darwin for pydevd, ill check again on this after its merged
