### ISSUE TITLE
dendrite 0.13.1 - level=panic msg="failed to connect to room server db" error="unable to insert executed migrations: unable to prepare insert statement: database is locked"

### ISSUE THREAD

**Issue by sanderhollaar** [NixOS/nixpkgs#243621]
### Describe the bug

Matrix server dendrite does not start after upgrade to 0.13.1
This is fixed in https://github.com/matrix-org/dendrite/pull/3144 - Prepare statement on an existing transaction

### Steps To Reproduce
1. have dendrite < 0.13.1 running as a service with sqlite as database backend
2. run `nixos-rebuild switch --upgrade` which upgrades dendrite to 0.13.1 as per https://github.com/NixOS/nixpkgs/pull/242183

### Expected behavior
Matrix server dendrite not crashing

### Screenshots
```console
systemd[1]: Starting Dendrite Matrix homeserver...
systemd[1]: Started Dendrite Matrix homeserver.
dendrite[3295831]: time="2023-07-14T22:03:41.127612580Z" level=info msg="Dendrite version 0.13.1"
dendrite[3295831]: time="2023-07-14T22:03:46.389018889Z" level=panic msg="failed to connect to room server db" error="unable to insert executed migrations: unable to prepare insert statement: database is locked"
dendrite[3295831]: panic: (*logrus.Entry) 0xc000394380
dendrite[3295831]: goroutine 1 [running]:
dendrite[3295831]: github.com/sirupsen/logrus.(*Entry).log(0xc000394310, 0x0, {0xc00048c090, 0x23})
dendrite[3295831]:         github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x4d6
dendrite[3295831]: github.com/sirupsen/logrus.(*Entry).Log(0xc000394310, 0x0, {0xc00016d318?, 0xf43425?, 0x0?})
dendrite[3295831]:         github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x4f
dendrite[3295831]: github.com/sirupsen/logrus.(*Entry).Panic(...)
dendrite[3295831]:         github.com/sirupsen/logrus@v1.9.3/entry.go:342
dendrite[3295831]: github.com/MFAshby/stdemuxerhook.(*StdDemuxerHook).Fire(0x0?, 0xc000394230)
dendrite[3295831]:         github.com/MFAshby/stdemuxerhook@v1.0.0/stdemuxerhook.go:58 +0x19e
dendrite[3295831]: github.com/sirupsen/logrus.LevelHooks.Fire(0xc00016d458?, 0x16d428?, 0x4?)
dendrite[3295831]:         github.com/sirupsen/logrus@v1.9.3/hooks.go:28 +0x7a
dendrite[3295831]: github.com/sirupsen/logrus.(*Entry).fireHooks(0xc000394230)
dendrite[3295831]:         github.com/sirupsen/logrus@v1.9.3/entry.go:280 +0x1f0
dendrite[3295831]: github.com/sirupsen/logrus.(*Entry).log(0xc000394070, 0x0, {0xc00048c060, 0x23})
dendrite[3295831]:         github.com/sirupsen/logrus@v1.9.3/entry.go:242 +0x3c5
dendrite[3295831]: github.com/sirupsen/logrus.(*Entry).Log(0xc000394070, 0x0, {0xc00016d718?, 0x0?, 0x0?})
dendrite[3295831]:         github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x4f
dendrite[3295831]: github.com/sirupsen/logrus.(*Entry).Logf(0xc000394070, 0x0, {0x183fd05?, 0x1616760?}, {0x0?, 0x5a?, 0x2?})
dendrite[3295831]:         github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0x85
dendrite[3295831]: github.com/sirupsen/logrus.(*Entry).Panicf(...)
dendrite[3295831]:         github.com/sirupsen/logrus@v1.9.3/entry.go:387
dendrite[3295831]: github.com/matrix-org/dendrite/roomserver.NewInternalAPI(0xc000134320, 0xc000510000, {0x0, {0x0, 0x0}, {{0x0, 0x0}, 0x5a, 0x2, 0xffffffffffffffff}, ...}, ...)
dendrite[3295831]:         github.com/matrix-org/dendrite/roomserver/roomserver.go:41 +0x145
dendrite[3295831]: main.main()
dendrite[3295831]:         github.com/matrix-org/dendrite/cmd/dendrite/main.go:152 +0xc25
systemd[1]: dendrite.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: dendrite.service: Failed with result 'exit-code'.
```

### Additional context
fixed in https://github.com/matrix-org/dendrite/pull/3144

### Notify maintainers
@sefidel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.1, NixOS, 23.11 (Tapir), 23.11pre504215.af59b3fb98b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - channels(ookhoi): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sefidel** [comment]
@sanderhollaar I've proposed PR #243634 to address this issue.
Let me know if the issue still occurs after applying the commit.

**Comment by sanderhollaar** [comment]
Works :partying_face: thanks a lot for the quick fix !! :hugs:

```@console
systemd[1]: Starting Dendrite Matrix homeserver...
systemd[1]: Started Dendrite Matrix homeserver.
dendrite[3876561]: time="2023-07-15T13:32:27.417739333Z" level=info msg="Dendrite version 0.13.1"
dendrite[3876561]: time="2023-07-15T13:32:28.177982412Z" level=info msg="Starting nats-server" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.178176452Z" level=info msg="  Version:  2.9.19" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.178222003Z" level=info msg="  Git:      [not set]" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.178290293Z" level=info msg="  Name:     monolith" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.178334578Z" level=info msg="  Node:     XXXXXXXXX" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.178373548Z" level=info msg="  ID:       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.178481413Z" level=warning msg="Maximum payloads over 8.00 MB are generally discouraged and could lead to poor performance" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.178659449Z" level=info msg="Starting JetStream" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.179785942Z" level=info msg="    _ ___ _____ ___ _____ ___ ___   _   __  __" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.179898778Z" level=info msg=" _ | | __|_   _/ __|_   _| _ \\ __| /_\\ |  \\/  |" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.179987333Z" level=info msg="| || | _|  | | \\__ \\ | | |   / _| / _ \\| |\\/| |" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.180069833Z" level=info msg=" \\__/|___| |_| |___/ |_| |_|_\\___/_/ \\_\\_|  |_|" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.180151228Z" level=info component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.180231444Z" level=info msg="         https://docs.nats.io/jetstream" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.180334524Z" level=info component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.180405479Z" level=info msg="---------------- JETSTREAM ----------------" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.180497954Z" level=info msg="  Max Memory:      94.28 GB" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.180582510Z" level=info msg="  Max Storage:     44.43 GB" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.180675160Z" level=info msg="  Store Directory: \"/tmp/nats/jetstream\"" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.180755715Z" level=info msg=------------------------------------------- component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.181674128Z" level=info msg="Server is ready" component=jetstream
dendrite[3876561]: time="2023-07-15T13:32:28.336907628Z" level=info msg="Enabling shared secret registration at /_synapse/admin/v1/register"
dendrite[3876561]: time="2023-07-15T13:32:28.400687387Z" level=info msg="Starting external listener on :8448"
dendrite[3876561]: time="2023-07-15T13:32:28.400907388Z" level=info msg="Starting external listener on :8008"
```
