### ISSUE TITLE
Build failure: scvi_tools v.1.0.2

### ISSUE THREAD

**Issue by JRR3** [NixOS/nixpkgs#245096]
### Steps To Reproduce
nix-shell scivi_tools_der.nix

where

scivi_tools_der.nix is given by the following derivation:
#------------------------------------------------------
with (import <nixpkgs> { });
let

  scvitools = (
    python3.pkgs.buildPythonPackage rec {
      pname = "scvi_tools";
      version = "1.0.2";
      format = "pyproject";
      src = fetchPypi {
          inherit pname version;
          sha256 = "2aa9b6cb57e8fa8bb90de025c22d01fe1e61607b48df8be4a2d4bc5d60114fd4";
      };
      doCheck = false;
      propagatedBuildInputs = [
        #pkgs.python3Packages.dm-tree
        pkgs.python3Packages.optax
        pkgs.python3Packages.sparse
        pkgs.python3Packages.hatchling
      ];
    }
  );

  pythonEnv = pkgs.python3.withPackages (p: with p; [
    scvitools
  ]);

in mkShell {

  buildInputs = [
    python3

    pythonEnv
  ];

}
#------------------------------------------------------
### Build log
Check whether the following modules can be imported: tree
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/79mn78vhybpkklj9vmgfrm5vk98jyg9q-python3-3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/lg1hyiwvx0i408204wrlvbyq8n714fi5-python3.10-dm-tree-0.1.8/lib/python3.10/site-packages/tree/__init__.py", line 23, in <module>
    from .sequence import _is_attrs
  File "/nix/store/lg1hyiwvx0i408204wrlvbyq8n714fi5-python3.10-dm-tree-0.1.8/lib/python3.10/site-packages/tree/sequence.py", line 19, in <module>
    from tree import _tree
ImportError: dynamic module does not define module export function (PyInit__tree)
error: builder for '/nix/store/66rj93c99vb9pkw42fw294qvwvnlkfpb-python3.10-dm-tree-0.1.8.drv' failed with exit code 1;
       last 10 log lines:
       >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
       >   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
       >   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
       >   File "/nix/store/lg1hyiwvx0i408204wrlvbyq8n714fi5-python3.10-dm-tree-0.1.8/lib/python3.10/site-packages/tree/__init__.py", line 23, in <module>
       >     from .sequence import _is_attrs
       >   File "/nix/store/lg1hyiwvx0i408204wrlvbyq8n714fi5-python3.10-dm-tree-0.1.8/lib/python3.10/site-packages/tree/sequence.py", line 19, in <module>
       >     from tree import _tree
       > ImportError: dynamic module does not define module export function (PyInit__tree)
       For full logs, run 'nix-store -l /nix/store/66rj93c99vb9pkw42fw294qvwvnlkfpb-python3.10-dm-tree-0.1.8.drv'.
error: 1 dependencies of derivation '/nix/store/dnpwng8ak0csmrxhl672r3civvwzf8ia-python3-3.10.12-env.drv' failed to build

### Additional context

macOS Monterey 12.6

Any help would be appreciated.

Regards,

Javier

**Comment by Aleksanaa** [comment]
Not a part of Nixpkgs.
