### ISSUE TITLE
ACME breaks in 17.03 stable

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#24529]
## Issue description

I was upgrading from nixos-17.03 prerelase (commit `c64c26af`) to the newly released nixos-17.03 stable (commit `0c041520`). Deploying with nixops, it got stuck when activating the systemd service for ACME.

## Technical details

In `journalctl`, first:

```
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: 2017-04-01 11:11:54,529:DEBUG:requests.packages.urllib3.connectionpool:395: https://acme-v01.api.letsencrypt.or
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: 2017-04-01 11:11:54,530:DEBUG:acme.client:641: Received response:
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: HTTP 409
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Server: nginx
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Content-Type: application/problem+json
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Content-Length: 107
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Boulder-Request-Id: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Boulder-Requester: 1234567
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Location: https://acme-v01.api.letsencrypt.org/acme/reg/1234567
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Replay-Nonce: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-Ww
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Expires: Sat, 01 Apr 2017 11:11:54 GMT
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Cache-Control: max-age=0, no-cache, no-store
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Pragma: no-cache
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Date: Sat, 01 Apr 2017 11:11:54 GMT
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: Connection: close
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: {
Apr 01 11:11:54 machine1 acme-example.com-start[11283]:   "type": "urn:acme:error:malformed",
Apr 01 11:11:54 machine1 acme-example.com-start[11283]:   "detail": "Registration key is already in use",
Apr 01 11:11:54 machine1 acme-example.com-start[11283]:   "status": 409
Apr 01 11:11:54 machine1 acme-example.com-start[11283]: }
```

then 5 minutes later the failure:

```
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: 2017-04-01 11:16:09,350:DEBUG:requests.packages.urllib3.connectionpool:395: https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-authz HTTP/1.1" 201 1001
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: 2017-04-01 11:16:09,350:DEBUG:acme.client:641: Received response:
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: HTTP 201
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Server: nginx
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Content-Type: application/json
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Content-Length: 1001
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Boulder-Request-Id: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Boulder-Requester: 8807399
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Location: https://acme-v01.api.letsencrypt.org/acme/authz/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Replay-Nonce: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: X-Frame-Options: DENY
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Strict-Transport-Security: max-age=604800
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Expires: Sat, 01 Apr 2017 11:16:09 GMT
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Cache-Control: max-age=0, no-cache, no-store
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Pragma: no-cache
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Date: Sat, 01 Apr 2017 11:16:09 GMT
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Connection: keep-alive
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: {
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   "identifier": {
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     "type": "dns",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     "value": "example.com"
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   },
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   "status": "pending",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   "expires": "2017-04-08T11:16:09.230426009Z",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   "challenges": [
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     {
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "type": "http-01",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "status": "pending",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/123456789",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "token": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     },
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     {
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "type": "tls-sni-01",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "status": "pending",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/123456787",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "token": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     },
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     {
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "type": "dns-01",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "status": "pending",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/123456789",
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       "token": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     }
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   ],
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   "combinations": [
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     [
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       2
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     ],
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     [
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       0
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     ],
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     [
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:       1
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     ]
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   ]
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: }
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: 2017-04-01 11:16:09,350:DEBUG:acme.client:666: Storing nonce: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Traceback (most recent call last):
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   File "/nix/store/8s4lhfv87hq8w104jp2qgk9a7msvpz1a-simp_le-client-0.1.1/lib/python2.7/site-packages/simp_le.py", line 1401, in main
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     return main_with_exceptions(cli_args)
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   File "/nix/store/8s4lhfv87hq8w104jp2qgk9a7msvpz1a-simp_le-client-0.1.1/lib/python2.7/site-packages/simp_le.py", line 1386, in main_with_exceptions
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     persist_new_data(args, existing_data)
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   File "/nix/store/8s4lhfv87hq8w104jp2qgk9a7msvpz1a-simp_le-client-0.1.1/lib/python2.7/site-packages/simp_le.py", line 1297, in persist_new_data
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     save_validation(roots[name], challb, validation)
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:   File "/nix/store/8s4lhfv87hq8w104jp2qgk9a7msvpz1a-simp_le-client-0.1.1/lib/python2.7/site-packages/simp_le.py", line 982, in save_validation
Apr 01 11:16:09 machine1 acme-example.com-start[11283]:     with open(path, 'w') as validation_file:
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: IOError: [Errno 13] Permission denied: u'/var/lib/acme/acme-challenge/.well-known/acme-challenge/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Unhandled error has happened, traceback is above
Apr 01 11:16:09 machine1 acme-example.com-start[11283]: Debugging tips: -v improves output verbosity. Help is available under --help.
Apr 01 11:16:09 machine1 systemd[1]: acme-example.com.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 01 11:16:09 machine1 systemd[1]: Failed to start Renew ACME Certificate for example.com.
Apr 01 11:16:09 machine1 systemd[1]: acme-example.com.timer: Adding 10min 21.272622s random time.
Apr 01 11:16:09 machine1 systemd[1]: acme-example.com.service: Unit entered failed state.
Apr 01 11:16:09 machine1 systemd[1]: acme-example.com.timer: Adding 40min 11.287818s random time.
Apr 01 11:16:09 machine1 systemd[1]: acme-example.com.service: Failed with result 'exit-code'.
Apr 01 11:16:10 machine1 nixos[10872]: switching to system configuration /nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-nixos-system-machine1-17.03pre-git failed (status 4)
```

**Comment by nh2** [comment]
Looking at `/etc/systemd/system/acme-example.com.service`, I see `User=nginx`, but the dir it wants to write to is writable only by root:

```
ls -lah /var/lib/acme/acme-challenge/.well-known/acme-challenge/
drwxr-xr-x 2 root root 4.0K Apr  1 11:54 .
```

**Comment by nh2** [comment]
I guess the question is where `User=nginx` comes from.

[`acme.nix` defines:](https://github.com/NixOS/nixpkgs/blob/fb50cde71e3ffd149faca1a1762c245542a24875/nixos/modules/security/acme.nix#L30)

```nix
      user = mkOption {
        type = types.str;
        default = "root";
        description = "User running the ACME client.";
      };
```

I haven't figured out yet where that gets set to nginx; in my settings, I use:

```nix
    services.nginx = {
      enable = true;
      recommendedGzipSettings = true;
      recommendedOptimisation = true;
      recommendedProxySettings = true;
      recommendedTlsSettings = true;
      virtualHosts."myhost.example.com" = {
        enableACME = true;
        forceSSL = true;
        locations."/".proxyPass = "http://127.0.0.1:8080";
      };
    };
```

**Comment by nh2** [comment]
> I haven't figured out yet where that gets set to nginx

I think it's [here in `nginx/default.nix`](https://github.com/NixOS/nixpkgs/blob/0c041520/nixos/modules/services/web-servers/nginx/default.nix#L439):

```nix
        acmePairs = map (vhostConfig: { name = vhostConfig.serverName; value = {
        user = cfg.user;
```

where `cfg.user` is from above:

```nix
      user = mkOption {
        type = types.str;
        default = "nginx";
        description = "User account under which nginx runs.";
};
```

**Comment by nh2** [comment]
Ah, I think I understand what is happening:

```
# ls -lah /var/lib/acme/acme-challenge/
drwxr-xr-x 3 root  root  4.0K Jan 26 21:49 .
drwxr-xr-x 4 nginx nginx 4.0K Jan 26 21:49 ..
drwxr-xr-x 3 root  root  4.0K Jan 26 21:49 .well-known
```

See how `/var/lib/acme/` is owned by `nginx` but the subdir `/var/lib/acme/acme-challenge/` is owned by `root`?

Commit https://github.com/NixOS/nixpkgs/commit/75f131da02c00027b9a8240fb74d117cb0f9d9cf#diff-3ac514cd8063d3114597ce7aa42b27cfR181 added `chown 'nginx:nginx' '/var/lib/acme'` to the pre-start script, but since it doesn't use `chown -R`, it is possible that there are older existing subdirs (like `acme-challenge` from my example) that are owned to `root` from before that commit went it.

I believe that should be `chown -R`.

@domenkozar do you agree?

**Comment by domenkozar** [comment]
Yes :)

**Comment by nh2** [comment]
Adding `-R`, my nixops deploy has finsihed now.

It took a long time though (hanging at the systemd service activation for ~10 minutes or so).

In `journalctl`, the line

`Apr 01 12:53:22 myhost1 acme-example.com-start[14016]: 2017-04-01 12:53:22,957:DEBUG:requests.packages.urllib3.connectionpool:395: https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-authz HTTP/1.1" 201 1001`

which is much later than when the systemd service activation started at around `Apr 01 12:44:19 myhost1 systemd[1]: Started Nix Daemon.`

**Comment by nh2** [comment]
PR for `release-17.03` at https://github.com/NixOS/nixpkgs/pull/24531 to fix the permissions error (but not the delay problem).

Should I make a PR for `master` too?

**Comment by domenkozar** [comment]
Please :)

**Comment by nh2** [comment]
> Should I make a PR for master too?

https://github.com/NixOS/nixpkgs/pull/24532
