### ISSUE TITLE
Build failure: `nodePackages."@bitwarden/cli"`

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#245337]
### Steps To Reproduce

Seems like the bitwarden-cli entry disappeared so now I have to use:
`nix-build -A nodePackages."@bitwarden/cli"`

### Build log

```
      last 60 log lines:
       > npm ERR! gyp info ok
       > npm ERR! gyp info it worked if it ends with ok
       > npm ERR! gyp info using node-gyp@9.3.1
       > npm ERR! gyp info using node@18.16.1 | linux | x64
       > npm ERR! gyp info find Python using Python version 3.10.12 found at "/nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/bin/python3"
       > npm ERR! gyp WARN read config.gypi ENOENT: no such file or directory, open '/nix/store/07smw26n2cr22dshgal90vynslkx9lsj-node-sources/include/node/config.gypi'
       > npm ERR! gyp info spawn /nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/bin/python3
       > npm ERR! gyp info spawn args [
       > npm ERR! gyp info spawn args   '/nix/store/y85811fai07h16xqwh99wnql0cwgb17c-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
       > npm ERR! gyp info spawn args   'binding.gyp',
       > npm ERR! gyp info spawn args   '-f',
       > npm ERR! gyp info spawn args   'make',
       > npm ERR! gyp info spawn args   '-I',
       > npm ERR! gyp info spawn args   '/nix/store/r8182zbf05ndqhx3nbnj1ashvb6kcyah-_at_bitwarden_slash_cli-2023.7.0/lib/node_modules/@bitwarden/cli/node_modules/canvas/build/config.gypi',
       > npm ERR! gyp info spawn args   '-I',
       > npm ERR! gyp info spawn args   '/nix/store/y85811fai07h16xqwh99wnql0cwgb17c-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
       > npm ERR! gyp info spawn args   '-I',
       > npm ERR! gyp info spawn args   '/nix/store/07smw26n2cr22dshgal90vynslkx9lsj-node-sources/common.gypi',
       > npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
       > npm ERR! gyp info spawn args   '-Dvisibility=default',
       > npm ERR! gyp info spawn args   '-Dnode_root_dir=/nix/store/07smw26n2cr22dshgal90vynslkx9lsj-node-sources',
       > npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/nix/store/y85811fai07h16xqwh99wnql0cwgb17c-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp',
       > npm ERR! gyp info spawn args   '-Dnode_lib_file=/nix/store/07smw26n2cr22dshgal90vynslkx9lsj-node-sources/$(Configuration)/node.lib',
       > npm ERR! gyp info spawn args   '-Dmodule_root_dir=/nix/store/r8182zbf05ndqhx3nbnj1ashvb6kcyah-_at_bitwarden_slash_cli-2023.7.0/lib/node_modules/@bitwarden/cli/node_modules/canvas',
       > npm ERR! gyp info spawn args   '-Dnode_engine=v8',
       > npm ERR! gyp info spawn args   '--depth=.',
       > npm ERR! gyp info spawn args   '--no-parallel',
       > npm ERR! gyp info spawn args   '--generator-output',
       > npm ERR! gyp info spawn args   'build',
       > npm ERR! gyp info spawn args   '-Goutput_dir=.'
       > npm ERR! gyp info spawn args ]
       > npm ERR! /nix/store/p6dlr3skfhxpyphipg2bqnj52999banh-bash-5.2-p15/bin/sh: line 1: pkg-config: command not found
       > npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
       > npm ERR! gyp ERR! configure error
       > npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
       > npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/nix/store/y85811fai07h16xqwh99wnql0cwgb17c-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
       > npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
       > npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
       > npm ERR! gyp ERR! System Linux 6.4.4
       > npm ERR! gyp ERR! command "/nix/store/y85811fai07h16xqwh99wnql0cwgb17c-nodejs-18.16.1/bin/node" "/nix/store/y85811fai07h16xqwh99wnql0cwgb17c-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/nix/store/r8182zbf05ndqhx3nbnj1ashvb6kcyah-_at_bitwarden_slash_cli-2023.7.0/lib/node_modules/@bitwarden/cli/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/nix/store/r8182zbf05ndqhx3nbnj1ashvb6kcyah-_at_bitwarden_slash_cli-2023.7.0/lib/node_modules/@bitwarden/cli/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108" "--nodedir=/nix/store/07smw26n2cr22dshgal90vynslkx9lsj-node-sources"
       > npm ERR! gyp ERR! cwd /nix/store/r8182zbf05ndqhx3nbnj1ashvb6kcyah-_at_bitwarden_slash_cli-2023.7.0/lib/node_modules/@bitwarden/cli/node_modules/canvas
       > npm ERR! gyp ERR! node -v v18.16.1
       > npm ERR! gyp ERR! node-gyp -v v9.3.1
       > npm ERR! gyp ERR! not ok
       > npm ERR! node-pre-gyp ERR! build error
       > npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/nix/store/y85811fai07h16xqwh99wnql0cwgb17c-nodejs-18.16.1/bin/node /nix/store/y85811fai07h16xqwh99wnql0cwgb17c-nodejs-18.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/nix/store/r8182zbf05ndqhx3nbnj1ashvb6kcyah-_at_bitwarden_slash_cli-2023.7.0/lib/node_modules/@bitwarden/cli/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/nix/store/r8182zbf05ndqhx3nbnj1ashvb6kcyah-_at_bitwarden_slash_cli-2023.7.0/lib/node_modules/@bitwarden/cli/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108 --nodedir=/nix/store/07smw26n2cr22dshgal90vynslkx9lsj-node-sources' (1)
       > npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/nix/store/r8182zbf05ndqhx3nbnj1ashvb6kcyah-_at_bitwarden_slash_cli-2023.7.0/lib/node_modules/@bitwarden/cli/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
       > npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
       > npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
       > npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
       > npm ERR! node-pre-gyp ERR! System Linux 6.4.4
       > npm ERR! node-pre-gyp ERR! command "/nix/store/y85811fai07h16xqwh99wnql0cwgb17c-nodejs-18.16.1/bin/node" "/nix/store/r8182zbf05ndqhx3nbnj1ashvb6kcyah-_at_bitwarden_slash_cli-2023.7.0/lib/node_modules/@bitwarden/cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
       > npm ERR! node-pre-gyp ERR! cwd /nix/store/r8182zbf05ndqhx3nbnj1ashvb6kcyah-_at_bitwarden_slash_cli-2023.7.0/lib/node_modules/@bitwarden/cli/node_modules/canvas
       > npm ERR! node-pre-gyp ERR! node -v v18.16.1
       > npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
       > npm ERR! node-pre-gyp ERR! not ok
       > 
       > npm ERR! A complete log of this run can be found in:
       > npm ERR!     /build/.npm/_logs/2023-07-25T08_09_32_339Z-debug-0.log
       > 
       For full logs, run 'nix log /nix/store/j75vj6sla58zqr5n3m5gzsk136l1abav-_at_bitwarden_slash_cli-2023.7.0.drv'.
```

### Notify maintainers

cc @dotlambda 

### Metadata
this is on master 6f098631f6f06b93c17f49abdf677790e017778d

**Comment by figsoda** [comment]
> Seems like the bitwarden-cli entry disappeared

It still exists for me, is there some way I can reproduce this?

that aside, this works

```patch
--- a/pkgs/development/node-packages/overrides.nix
+++ b/pkgs/development/node-packages/overrides.nix
@@ -25,6 +25,17 @@ final: prev: {
     '';
   };
 
+  "@bitwarden/cli" = prev."@bitwarden/cli".override {
+    nativeBuildInputs = [
+      pkgs.pkg-config
+    ];
+    buildInputs = [
+      pkgs.cairo
+      pkgs.pango
+      pkgs.pixman
+    ];
+  };
+
   "@electron-forge/cli" = prev."@electron-forge/cli".override {
     buildInputs = [ final.node-gyp-build ];
   };
```

I'm not submiting this as a PR since we probably shouldn't do this if bitwarden-cli is still intended to be used
