### ISSUE TITLE
localstack fails at runtime because of read-only filesystem (nix store)

### ISSUE THREAD

**Issue by ParetoOptimalDev** [NixOS/nixpkgs#245591]
### Describe the bug

I think localstack tries to create folders in it's directories? Maybe we just need to patch and set a data directory for it to use or something?

```
~ $ nix run nixpkgs#localstack start

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 1.4.0

[14:36:49] starting LocalStack in Docker mode 🐳                                                                      localstack.py:138
──────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ────────────────────────────────────────────
Traceback (most recent call last):
  File "/nix/store/lxpvyq102x5di64vc8b2jw6wfr9lfwkg-python3.10-localstack-1.4.0/bin/.localstack-wrapped", line 24, in <module>
    main()
  File "/nix/store/lxpvyq102x5di64vc8b2jw6wfr9lfwkg-python3.10-localstack-1.4.0/bin/.localstack-wrapped", line 20, in main
    main.main()
  File "/nix/store/lxpvyq102x5di64vc8b2jw6wfr9lfwkg-python3.10-localstack-1.4.0/lib/python3.10/site-packages/localstack/cli/main.py", line 11, in main
    cli()
  File "/nix/store/lxpvyq102x5di64vc8b2jw6wfr9lfwkg-python3.10-localstack-1.4.0/lib/python3.10/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/nix/store/hai9rgnpcl8j8qv9fnlr6mwsmcacla30-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/hai9rgnpcl8j8qv9fnlr6mwsmcacla30-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/hai9rgnpcl8j8qv9fnlr6mwsmcacla30-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/hai9rgnpcl8j8qv9fnlr6mwsmcacla30-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/hai9rgnpcl8j8qv9fnlr6mwsmcacla30-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/lxpvyq102x5di64vc8b2jw6wfr9lfwkg-python3.10-localstack-1.4.0/lib/python3.10/site-packages/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
    return fn(*args, **kwargs)
  File "/nix/store/lxpvyq102x5di64vc8b2jw6wfr9lfwkg-python3.10-localstack-1.4.0/lib/python3.10/site-packages/localstack/cli/localstack.py", line 159, in cmd_start
    bootstrap.start_infra_in_docker()
  File "/nix/store/lxpvyq102x5di64vc8b2jw6wfr9lfwkg-python3.10-localstack-1.4.0/lib/python3.10/site-packages/localstack/utils/bootstrap.py", line 629, in start_infra_in_docker
    prepare_docker_start()
  File "/nix/store/lxpvyq102x5di64vc8b2jw6wfr9lfwkg-python3.10-localstack-1.4.0/lib/python3.10/site-packages/localstack/utils/bootstrap.py", line 530, in prepare_docker_start
    mkdir(config.dirs.tmp)
  File "/nix/store/lxpvyq102x5di64vc8b2jw6wfr9lfwkg-python3.10-localstack-1.4.0/lib/python3.10/site-packages/localstack/utils/files.py", line 101, in mkdir
    os.makedirs(folder, exist_ok=True)
  File "/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/nix/store/lxpvyq102x5di64vc8b2jw6wfr9lfwkg-python3.10-localstack-1.4.0/lib/python3.10/site-packages/.filesystem'
```

### Expected behavior
The above runs localstack successfully.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by evenbrenden** [comment]
Ran into this myself and found that when running LocalStack in host mode, `FILESYSTEM_ROOT` defaults to `./.filesystem`, which is relative to the executable and therefore in the Nix store. Something like seems to work:
```
FILESYSTEM_ROOT=~/.cache/localstack/volume localstack start
```
Maybe this setting should be part of the installed wrapper.

**Comment by evenbrenden** [comment]
See https://docs.localstack.cloud/references/filesystem/#host-mode.

**Comment by ankhers** [comment]
How were you able to install localstack in a way that allows you to run in host mode? The default installation only seems to allow for using with docker.

**Comment by evenbrenden** [comment]
My mistake, I did not run it in host mode. `/var` and `/usr` is restricted on NixOS, so you'll need to point `FILESYSTEM_ROOT` to a user-writable path.

**Comment by Cloudef** [comment]
It might make sense to package lockalstack with runtime instead of the light localstack that needs docker.
