### ISSUE TITLE
systemd-boot-builder.py fails to parse systemd version with Fedora-specific suffix

### ISSUE THREAD

**Issue by pluiedev** [NixOS/nixpkgs#246195]
### Describe the bug
When I ran `sudo nixos-rebuild switch`, I got this cryptic error message that looks like it came from a Python script:
```console
$ sudo nixos-rebuild switch --flake ~/flake
warning: Git tree '/home/leah/flake' is dirty
building the system configuration...
warning: Git tree '/home/leah/flake' is dirty
Traceback (most recent call last):
  File "/nix/store/854bkz11n09hf929ny7hyay8hv9kyc7b-systemd-boot", line 341, in <module>
    main()
  File "/nix/store/854bkz11n09hf929ny7hyay8hv9kyc7b-systemd-boot", line 276, in main
    installed_version = version.parse(installed_match.group(1))
  File "/nix/store/4p3r14jgvyy4knlck0isbcjq09ss1a2j-python3-3.10.12-env/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/nix/store/4p3r14jgvyy4knlck0isbcjq09ss1a2j-python3-3.10.12-env/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '253.5-1.fc38'
warning: error(s) occurred while switching to the new configuration
error: Recipe `switch` failed on line 36 with exit code 1
```

I've managed to track it down to [line 276 in `systemd-boot-builder.py`](https://github.com/NixOS/nixpkgs/blob/2a9d660ff0f7ffde9d73be328ee6e6f10ef66b28/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L276), which uses `packaging` for parsing the systemd version.

I assume it has to do with my Fedora 38 install interfering with my boot config, judging by the `fc38` suffix in the version string. In the end, I consider this the script's problem given that this version string works just fine in other parts of the system, and that `packaging` follows a particular versioning scheme as defined by [PEP 440](https://peps.python.org/pep-0440/), which is not strictly compatible with the SemVer versions systemd accepts.

### Steps To Reproduce
I'm not sure if this is reproducible — this bug just happened randomly to me on one boot up and it has stuck ever since.
However, one can simply run this in a Python REPL to reproduce the core issue: 
```console
>>> from packaging import version
>>> version.parse("253.5-1.fc38")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/fc1a5dd4c19n0m37crzmasdbpzdq5ax2-python3-3.10.12-env/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/nix/store/fc1a5dd4c19n0m37crzmasdbpzdq5ax2-python3-3.10.12-env/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '253.5-1.fc38'
```

### Expected behavior
I expect the switch to succeed without this error.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.11 (Tapir), 23.11.20230716.6cee3b5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Scrumplex** [comment]
Looks like the script queries `bootctl status` and finds the first occurrence of `^\W+File:.*/EFI/(?:BOOT|systemd)/.*\.efi \(systemd-boot ([\d.]+[^)]*)\)$`

If Fedora's bootloader happens to be the first that matches, this error is going to happen.

Relevant code: https://github.com/NixOS/nixpkgs/blob/2f4e3f6fa553264d3b8bcf4d3561c0134b625afa/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L260-L287
