### ISSUE TITLE
python3.pkgs.pex vendoring fails

### ISSUE THREAD

**Issue by phaer** [NixOS/nixpkgs#246448]
### Describe the bug

[pex](https://pex.readthedocs.io/en/v2.1.140/) fails to run most basic commands when installed via nix, due to an error seemingly related to it's vendoring of some dependencies.

### Steps To Reproduce

On a NixOS machine or Darwin with Nix installed, run:

<details>
<summary>PEX_VERBOSE=9 nix shell nixpkgs#python3.pkgs.pex -c pex</summary>

```
pex: Installed VendorImporter(root='/nix/store/0wy2js5y1hw45zlv3m2d2jc1rdzcqdav-python3.10-pex-2.1.137/lib/python3.10/site-packages', importables=(_Importable(module='attrs', is_pkg=True, path='pex/vendor/_vendored/attrs', prefix='pex.third_party'), _Importable(module='attr', is_pkg=True, path='pex/vendor/_vendored/attrs', prefix='pex.third_party'), _Importable(module='pyparsing', is_pkg=False, path='pex/vendor/_vendored/packaging_21_3', prefix='pex.third_party'), _Importable(module='packaging', is_pkg=True, path='pex/vendor/_vendored/packaging_21_3', prefix='pex.third_party'), _Importable(module='toml', is_pkg=True, path='pex/vendor/_vendored/toml', prefix='pex.third_party'), _Importable(module='pip', is_pkg=True, path='pex/vendor/_vendored/pip', prefix='pex.third_party'), _Importable(module='easy_install', is_pkg=False, path='pex/vendor/_vendored/setuptools', prefix='pex.third_party'), _Importable(module='setuptools', is_pkg=True, path='pex/vendor/_vendored/setuptools', prefix='pex.third_party'), _Importable(module='pkg_resources', is_pkg=True, path='pex/vendor/_vendored/setuptools', prefix='pex.third_party'), _Importable(module='wheel', is_pkg=True, path='pex/vendor/_vendored/wheel', prefix='pex.third_party')))
pex: Exposed _Importable(module='attrs', is_pkg=True, path='pex/vendor/_vendored/attrs', prefix='pex.third_party')
pex: Exposed _Importable(module='attr', is_pkg=True, path='pex/vendor/_vendored/attrs', prefix='pex.third_party')
pex: pex.third_party.attr imported via _Loader(module_name='pex.third_party.attr', vendor_module_name='pex.vendor._vendored.attrs.attr')
pex: pex.third_party.packaging imported via _Loader(module_name='pex.third_party.packaging', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging')
pex: pex.third_party.packaging.utils imported via _Loader(module_name='pex.third_party.packaging.utils', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.utils')
pex: pex.third_party.pyparsing imported via _Loader(module_name='pex.third_party.pyparsing', vendor_module_name='pex.vendor._vendored.packaging_21_3.pyparsing')
pex: pex.third_party.packaging.markers imported via _Loader(module_name='pex.third_party.packaging.markers', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.markers')
pex: pex.third_party.packaging.requirements imported via _Loader(module_name='pex.third_party.packaging.requirements', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.requirements')
pex: pex.third_party.packaging.specifiers imported via _Loader(module_name='pex.third_party.packaging.specifiers', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.specifiers')
pex: attr imported via _Loader(module_name='attr', vendor_module_name='pex.vendor._vendored.attrs.attr')
pex: attr._make imported via _Loader(module_name='attr._make', vendor_module_name='pex.vendor._vendored.attrs.attr._make')
pex: pex.third_party.packaging.tags imported via _Loader(module_name='pex.third_party.packaging.tags', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.tags')
pex: pex.third_party.packaging.version imported via _Loader(module_name='pex.third_party.packaging.version', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.version')
pex: pex.third_party.toml imported via _Loader(module_name='pex.third_party.toml', vendor_module_name='pex.vendor._vendored.toml.toml')
pex: pex.third_party.toml.tz imported via _Loader(module_name='pex.third_party.toml.tz', vendor_module_name='pex.vendor._vendored.toml.toml.tz')
pex: pex.third_party.toml.decoder imported via _Loader(module_name='pex.third_party.toml.decoder', vendor_module_name='pex.vendor._vendored.toml.toml.decoder')
pex: pex.third_party.toml imported via _Loader(module_name='pex.third_party.toml', vendor_module_name='pex.vendor._vendored.toml.toml')
pex: Searching for pyenv root...
pex: No pyenv installation was found.
pex: Searching for pyenv root...: 0.2ms
pex: Building pex
pex: Building pex :: Resolving distributions ()
pex: Building pex :: Resolving distributions () :: Resolving requirements.
pex: Building pex: 0.5ms
pex:   Resolving distributions (): 0.2ms
pex:     Resolving requirements.: 0.2ms
pex: Vendoring attr from VendorSpec(key='attrs', requirement='git+https://github.com/python-attrs/attrs@947bfb542104209a587280701d8cb389c813459d#egg=attrs', import_path='attrs', rewrite=True, constrain=False, constraints=()) @ /nix/store/0wy2js5y1hw45zlv3m2d2jc1rdzcqdav-python3.10-pex-2.1.137/lib/python3.10/site-packages/pex/vendor/_vendored/attrs
Traceback (most recent call last):
  File "/nix/store/0wy2js5y1hw45zlv3m2d2jc1rdzcqdav-python3.10-pex-2.1.137/lib/python3.10/site-packages/pex/result.py", line 105, in catch
    return func(*args, **kwargs)
  File "/nix/store/0wy2js5y1hw45zlv3m2d2jc1rdzcqdav-python3.10-pex-2.1.137/lib/python3.10/site-packages/pex/bin/pex.py", line 789, in do_main
    pex_builder.freeze(bytecode_compile=options.compile)
  File "/nix/store/0wy2js5y1hw45zlv3m2d2jc1rdzcqdav-python3.10-pex-2.1.137/lib/python3.10/site-packages/pex/pex_builder.py", line 611, in freeze
    self._prepare_bootstrap()
  File "/nix/store/0wy2js5y1hw45zlv3m2d2jc1rdzcqdav-python3.10-pex-2.1.137/lib/python3.10/site-packages/pex/pex_builder.py", line 556, in _prepare_bootstrap
    vendor.vendor_runtime(
  File "/nix/store/0wy2js5y1hw45zlv3m2d2jc1rdzcqdav-python3.10-pex-2.1.137/lib/python3.10/site-packages/pex/vendor/__init__.py", line 293, in vendor_runtime
    chroot.copy(src, dest, label)
  File "/nix/store/0wy2js5y1hw45zlv3m2d2jc1rdzcqdav-python3.10-pex-2.1.137/lib/python3.10/site-packages/pex/common.py", line 508, in copy
    shutil.copy(src, os.path.join(self.chroot, dst))
  File "/nix/store/bq1q4gk52gsx4fg4pf07f2kxqgazkcls-python3-3.10.12/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/nix/store/bq1q4gk52gsx4fg4pf07f2kxqgazkcls-python3-3.10.12/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/private/tmp/tmpbgl4cefe/.bootstrap/pex/__init__.py'
[Errno 13] Permission denied: '/private/tmp/tmpbgl4cefe/.bootstrap/pex/__init__.py'

```

</details>

### Expected behavior

A pex-managed python repl should open, same behavior as in a venv. For comparision:

<details>
<summary>nix shell nixpkgs#python3 -c sh -c "python -m venv ./venv; ./venv/bin/pip install pex; ./venv/bin/pex"</summary>

```
Collecting pex
  Using cached pex-2.1.140-py2.py3-none-any.whl (3.0 MB)
Installing collected packages: pex
Successfully installed pex-2.1.140

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Python 3.10.12 (main, Jul 18 2023, 17:17:22) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
```

</details>

### Additional context

* the site-packages path where pex lies is in the /nix/store, so read-only.
  however, the the vendored dependencies are included in the closure; `${pkgs.python3.pkgs.pex}/lib/python3.10/site-packages/pex/vendor/_vendored/` exists and includes attrs, pip, etc.
  maybe @jsirois could help us interpret the error and/or how to debug this efficiently? :) 

* some simple commands such as `pex --help` do work.
* same commands run fine in a venv on the same machines using the same python intepreter.
* same symptoms on NixOS and when installed via nixpkgs unstable on darwin.
* the tempdir path mentioned in the error message is writeable, but non existent or cleaned up.
* the alternative `pex3` script/entrypoint shows similar symptoms:

<details>
<summary>PEX_VERBOSE=9 nix shell nixpkgs#python3.pkgs.pex -c pex3  lock create requests</summary>

```
pex: Installed VendorImporter(root='/nix/store/0wy2js5y1hw45zlv3m2d2jc1rdzcqdav-python3.10-pex-2.1.137/lib/python3.10/site-packages', importables=(_Importable(module='attrs', is_pkg=True, path='pex/vendor/_vendored/attrs', prefix='pex.third_party'), _Importable(module='attr', is_pkg=True, path='pex/vendor/_vendored/attrs', prefix='pex.third_party'), _Importable(module='pyparsing', is_pkg=False, path='pex/vendor/_vendored/packaging_21_3', prefix='pex.third_party'), _Importable(module='packaging', is_pkg=True, path='pex/vendor/_vendored/packaging_21_3', prefix='pex.third_party'), _Importable(module='toml', is_pkg=True, path='pex/vendor/_vendored/toml', prefix='pex.third_party'), _Importable(module='pip', is_pkg=True, path='pex/vendor/_vendored/pip', prefix='pex.third_party'), _Importable(module='easy_install', is_pkg=False, path='pex/vendor/_vendored/setuptools', prefix='pex.third_party'), _Importable(module='setuptools', is_pkg=True, path='pex/vendor/_vendored/setuptools', prefix='pex.third_party'), _Importable(module='pkg_resources', is_pkg=True, path='pex/vendor/_vendored/setuptools', prefix='pex.third_party'), _Importable(module='wheel', is_pkg=True, path='pex/vendor/_vendored/wheel', prefix='pex.third_party')))
pex: Exposed _Importable(module='attrs', is_pkg=True, path='pex/vendor/_vendored/attrs', prefix='pex.third_party')
pex: Exposed _Importable(module='attr', is_pkg=True, path='pex/vendor/_vendored/attrs', prefix='pex.third_party')
pex: pex.third_party.attr imported via _Loader(module_name='pex.third_party.attr', vendor_module_name='pex.vendor._vendored.attrs.attr')
pex: pex.third_party.packaging imported via _Loader(module_name='pex.third_party.packaging', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging')
pex: pex.third_party.packaging.tags imported via _Loader(module_name='pex.third_party.packaging.tags', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.tags')
pex: pex.third_party.pyparsing imported via _Loader(module_name='pex.third_party.pyparsing', vendor_module_name='pex.vendor._vendored.packaging_21_3.pyparsing')
pex: pex.third_party.packaging.utils imported via _Loader(module_name='pex.third_party.packaging.utils', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.utils')
pex: pex.third_party.packaging.markers imported via _Loader(module_name='pex.third_party.packaging.markers', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.markers')
pex: pex.third_party.packaging.requirements imported via _Loader(module_name='pex.third_party.packaging.requirements', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.requirements')
pex: pex.third_party.packaging.specifiers imported via _Loader(module_name='pex.third_party.packaging.specifiers', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.specifiers')
pex: attr imported via _Loader(module_name='attr', vendor_module_name='pex.vendor._vendored.attrs.attr')
pex: attr._make imported via _Loader(module_name='attr._make', vendor_module_name='pex.vendor._vendored.attrs.attr._make')
pex: pex.third_party.packaging.version imported via _Loader(module_name='pex.third_party.packaging.version', vendor_module_name='pex.vendor._vendored.packaging_21_3.packaging.version')
pex: pex.third_party.toml imported via _Loader(module_name='pex.third_party.toml', vendor_module_name='pex.vendor._vendored.toml.toml')
pex: pex.third_party.toml.tz imported via _Loader(module_name='pex.third_party.toml.tz', vendor_module_name='pex.vendor._vendored.toml.toml.tz')
pex: pex.third_party.toml.decoder imported via _Loader(module_name='pex.third_party.toml.decoder', vendor_module_name='pex.vendor._vendored.toml.toml.decoder')
pex: pex.third_party.toml imported via _Loader(module_name='pex.third_party.toml', vendor_module_name='pex.vendor._vendored.toml.toml')
pex: Searching for pyenv root...
pex: No pyenv installation was found.
pex: Searching for pyenv root...: 0.1ms
pex: Resolving for:
  /nix/store/bq1q4gk52gsx4fg4pf07f2kxqgazkcls-python3-3.10.12/bin/python3.10
pex: Spawning a maximum of 8 parallel jobs to process:
  /nix/store/bq1q4gk52gsx4fg4pf07f2kxqgazkcls-python3-3.10.12/bin/python3.10
pex: Hashing pex
pex: Hashing pex: 50.5ms
pex: Isolating pex
pex: Isolating pex: 0.0ms
pex: Vendoring attr from VendorSpec(key='attrs', requirement='git+https://github.com/python-attrs/attrs@947bfb542104209a587280701d8cb389c813459d#egg=attrs', import_path='attrs', rewrite=True, constrain=False, constraints=()) @ /nix/store/0wy2js5y1hw45zlv3m2d2jc1rdzcqdav-python3.10-pex-2.1.137/lib/python3.10/site-packages/pex/vendor/_vendored/attrs
Failed to spawn a job for /nix/store/bq1q4gk52gsx4fg4pf07f2kxqgazkcls-python3-3.10.12/bin/python3.10: [Errno 13] Permission denied: '/Users/paulharle/.pex/pip-20.3.4-patched.pex/89e0a0a38d2f52dd7043b67251793de5cc87bd0a.lck.work/.bootstrap/pex/__init__.py'
```

</details>

### Notify maintainers

Hope you don't mind the pings

@copumpkin (maintainer)
@fabaff (done multiple recent updates)
@jsirois (pex developer)

### Metadata

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.6.0, macOS 13.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/nhk2gnp8jf1xshlym3g63m6k7v35p21h-source`
```

**Comment by jsirois** [comment]
@phaer NixOS is pretty exotic in my world. Can you confirm that I can use a container to emulate this? I assume I can, but just to check. I'll be back at a keyboard August 3rd to repro, but I expect the workaround for now is to set PEX_ROOT somewhere writable. Pex does try to detect the default `~/.pex` is unwritable and fall back to tmp, but perhaps all these measures are foiled in this environment.

**Comment by phaer** [comment]
@jsirois wow, that was fast! :)

Should be able to emulate in a container or almost anywhere you can get a recent nix with flakes enabled running. Let me know if can assist you with that! (contact info in profile)

>  but I expect the workaround for now is to set PEX_ROOT somewhere writable. Pex does try to detect the default ~/.pex is unwritable and fall back to tmp, but perhaps all these measures are foiled in this environment.

Many environment variables like `PATH` and `PYTHONPATH` are different when run via nix (symlinks to /nix/store), but "~/" and other filesystems are not namespaced or sandboxed in any way here.

I've tried with PEX_ROOT set, but that didn't incfluence the output. Going to have another look tomorrow, but it's quite late already here in CEST.

```
mkdir -p ./pex_root && PEX_ROOT=$(PWD)/pex_root PEX_VERBOSE=9 nix shell nixpkgs#python3.pkgs.pex -c pex
```

**Comment by phaer** [comment]
I don't think notifications are sent for linked issues; think I found a fix in https://github.com/pantsbuild/pex/pull/2202.

Thanks to @adisbladis for pointing me into the right direction

**Comment by jsirois** [comment]
Ok, this works perfectly fine in nixos:
```
$ docker run --rm -it --privileged -v $PWD/nix.conf:/etc/nix/nix.conf nixos/nix
bash-5.1# cat /etc/nix/nix.conf
build-users-group = nixbld
sandbox = true
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

bash-5.1# nix-channel --update
unpacking channels...
bash-5.1# nix-env --install --attr nixpkgs.nix-info
installing 'nix-info'
these 15 paths will be fetched (10.54 MiB download, 46.68 MiB unpacked):
  /nix/store/jhgjl8i6bpf156904f3dimzbdms9qkqb-acl-2.3.1
  /nix/store/0pw2hzr37sw46l5cadw4qb7aw3zxqlbn-attr-2.5.1
  /nix/store/p6dlr3skfhxpyphipg2bqnj52999banh-bash-5.2-p15
  /nix/store/cbzwjj38mvy6sz7k9wpl33sa5mgxx5j3-coreutils-9.3
  /nix/store/w34ybgxqmq1wr8wq9igf000ysb8rr7g5-findutils-4.9.0
  /nix/store/2fpmbk0g0ggm9zq89af7phvvvv8dnm7n-gcc-12.3.0-lib
  /nix/store/m6kphh9rh424vbw5wq84jcg0r4is4sc5-gcc-12.3.0-libgcc
  /nix/store/1x4ijm9r1a88qk7zcmbbfza324gx1aac-glibc-2.37-8
  /nix/store/ivzg9hiq88a8zgf6kfp7hsmbbw4s3bxr-gmp-with-cxx-6.2.1
  /nix/store/7ch1llcm71yxakj661n576rjw2ms34d9-gnugrep-3.11
  /nix/store/a9mxddm4a5p4kp84vys4n2nrmwqgk7kr-libidn2-2.3.4
  /nix/store/ic9wnagwh22yhqh3lcdlnv5m178w6f0f-libunistring-1.1
  /nix/store/sr8iirgqnzi8z88lzdy22cm0c28vxjif-nix-info
  /nix/store/jrcj27qywmj1fh9bjrkx1aacs4a5n249-pcre2-10.42
  /nix/store/2y9zl8ky5ac28ali6ly1zfz11d4fq48b-xgcc-12.3.0-libgcc
copying path '/nix/store/2y9zl8ky5ac28ali6ly1zfz11d4fq48b-xgcc-12.3.0-libgcc' from 'https://cache.nixos.org'...
copying path '/nix/store/m6kphh9rh424vbw5wq84jcg0r4is4sc5-gcc-12.3.0-libgcc' from 'https://cache.nixos.org'...
copying path '/nix/store/ic9wnagwh22yhqh3lcdlnv5m178w6f0f-libunistring-1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/a9mxddm4a5p4kp84vys4n2nrmwqgk7kr-libidn2-2.3.4' from 'https://cache.nixos.org'...
copying path '/nix/store/1x4ijm9r1a88qk7zcmbbfza324gx1aac-glibc-2.37-8' from 'https://cache.nixos.org'...
copying path '/nix/store/0pw2hzr37sw46l5cadw4qb7aw3zxqlbn-attr-2.5.1' from 'https://cache.nixos.org'...
copying path '/nix/store/jrcj27qywmj1fh9bjrkx1aacs4a5n249-pcre2-10.42' from 'https://cache.nixos.org'...
copying path '/nix/store/p6dlr3skfhxpyphipg2bqnj52999banh-bash-5.2-p15' from 'https://cache.nixos.org'...
copying path '/nix/store/2fpmbk0g0ggm9zq89af7phvvvv8dnm7n-gcc-12.3.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/jhgjl8i6bpf156904f3dimzbdms9qkqb-acl-2.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/7ch1llcm71yxakj661n576rjw2ms34d9-gnugrep-3.11' from 'https://cache.nixos.org'...
copying path '/nix/store/ivzg9hiq88a8zgf6kfp7hsmbbw4s3bxr-gmp-with-cxx-6.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/cbzwjj38mvy6sz7k9wpl33sa5mgxx5j3-coreutils-9.3' from 'https://cache.nixos.org'...
copying path '/nix/store/w34ybgxqmq1wr8wq9igf000ysb8rr7g5-findutils-4.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/sr8iirgqnzi8z88lzdy22cm0c28vxjif-nix-info' from 'https://cache.nixos.org'...
building '/nix/store/w9k1d4qnfbwm8vbhk6b18b2shpr9sr32-user-environment.drv'...
bash-5.1# nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90.1-microsoft-standard-WSL2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

bash-5.1# nix-env --install --attr nixpkgs.python3.pkgs.pex
installing 'python3.10-pex-2.1.137'
these 13 paths will be fetched (37.69 MiB download, 115.87 MiB unpacked):
  /nix/store/k0r87f1hh9bxf6s2vkkkrrlwfkxsn1jx-expat-2.5.0
  /nix/store/ad8ivr9pkzw1w01mvq88q3ra601zpd6c-gdbm-1.23
  /nix/store/9w5faa08asvglqhywg43nrz2vh0asfn0-libffi-3.4.4
  /nix/store/nhnxylvmaisx7pw8pyyx3a8cq93xanpx-libxcrypt-4.4.36
  /nix/store/q3lnkq87ckh490dplz1rg8l90xnp3h25-mailcap-2.1.53
  /nix/store/9gyhjdryy7g26frwsxsbs0gdffjbaxr4-ncurses-6.4
  /nix/store/fvzc0n5c4r13mpqv5jrq0vkjw7r5jndn-openssl-3.0.9
  /nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12
  /nix/store/hsjy0mbj4j7kyd0ycsrfadlp6r367inf-python3.10-pex-2.1.137
  /nix/store/mklyrxivl9ij7wnwd2hjxg1yq55ng50f-python3.10-pex-2.1.137-dist
  /nix/store/iddgks1c4nd16vm50pfxj0ivlm4awl1k-readline-8.2p1
  /nix/store/fr2hlcmhwwbrxyzidbmgsam8b6nd7lr1-sqlite-3.42.0
  /nix/store/hwdckdgh3y73qravhmx7dmkv825zbipi-tzdata-2023c
copying path '/nix/store/mklyrxivl9ij7wnwd2hjxg1yq55ng50f-python3.10-pex-2.1.137-dist' from 'https://cache.nixos.org'...
copying path '/nix/store/q3lnkq87ckh490dplz1rg8l90xnp3h25-mailcap-2.1.53' from 'https://cache.nixos.org'...
copying path '/nix/store/hwdckdgh3y73qravhmx7dmkv825zbipi-tzdata-2023c' from 'https://cache.nixos.org'...
copying path '/nix/store/k0r87f1hh9bxf6s2vkkkrrlwfkxsn1jx-expat-2.5.0' from 'https://cache.nixos.org'...
copying path '/nix/store/ad8ivr9pkzw1w01mvq88q3ra601zpd6c-gdbm-1.23' from 'https://cache.nixos.org'...
copying path '/nix/store/9w5faa08asvglqhywg43nrz2vh0asfn0-libffi-3.4.4' from 'https://cache.nixos.org'...
copying path '/nix/store/nhnxylvmaisx7pw8pyyx3a8cq93xanpx-libxcrypt-4.4.36' from 'https://cache.nixos.org'...
copying path '/nix/store/9gyhjdryy7g26frwsxsbs0gdffjbaxr4-ncurses-6.4' from 'https://cache.nixos.org'...
copying path '/nix/store/fvzc0n5c4r13mpqv5jrq0vkjw7r5jndn-openssl-3.0.9' from 'https://cache.nixos.org'...
copying path '/nix/store/fr2hlcmhwwbrxyzidbmgsam8b6nd7lr1-sqlite-3.42.0' from 'https://cache.nixos.org'...
copying path '/nix/store/iddgks1c4nd16vm50pfxj0ivlm4awl1k-readline-8.2p1' from 'https://cache.nixos.org'...
copying path '/nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12' from 'https://cache.nixos.org'...
copying path '/nix/store/hsjy0mbj4j7kyd0ycsrfadlp6r367inf-python3.10-pex-2.1.137' from 'https://cache.nixos.org'...
building '/nix/store/hqamfiyffssr6a5b1rl2ibkrin40dxkc-user-environment.drv'...
bash-5.1# pex3 lock create cowsay --indent 2 -o lock.json
running egg_info
writing cowsay.egg-info/PKG-INFO
writing dependency_links to cowsay.egg-info/dependency_links.txt
writing entry points to cowsay.egg-info/entry_points.txt
writing top-level names to cowsay.egg-info/top_level.txt
reading manifest file 'cowsay.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cowsay.egg-info/SOURCES.txt'
running dist_info
creating /tmp/tmpu6z7uizz/build/cowsay.egg-info
writing /tmp/tmpu6z7uizz/build/cowsay.egg-info/PKG-INFO
writing dependency_links to /tmp/tmpu6z7uizz/build/cowsay.egg-info/dependency_links.txt
writing entry points to /tmp/tmpu6z7uizz/build/cowsay.egg-info/entry_points.txt
writing top-level names to /tmp/tmpu6z7uizz/build/cowsay.egg-info/top_level.txt
writing manifest file '/tmp/tmpu6z7uizz/build/cowsay.egg-info/SOURCES.txt'
reading manifest file '/tmp/tmpu6z7uizz/build/cowsay.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file '/tmp/tmpu6z7uizz/build/cowsay.egg-info/SOURCES.txt'
creating '/tmp/tmpu6z7uizz/build/cowsay.dist-info'
adding license file "LICENSE.txt" (matched pattern "LICEN[CS]E*")
bash-5.1# cat lock.json
{
  "allow_builds": true,
  "allow_prereleases": false,
  "allow_wheels": true,
  "build_isolation": true,
  "constraints": [],
  "locked_resolves": [
    {
      "locked_requirements": [
        {
          "artifacts": [
            {
              "algorithm": "sha256",
              "hash": "c00e02444f5bc7332826686bd44d963caabbaba9a804a63153822edce62bbbf3",
              "url": "https://files.pythonhosted.org/packages/6b/b8/9f497fd045d74fe21d91cbe8debae0b451229989e35b539d218547d79fc6/cowsay-5.0.tar.gz"
            }
          ],
          "project_name": "cowsay",
          "requires_dists": [],
          "requires_python": null,
          "version": "5.0"
        }
      ],
      "platform_tag": [
        "cp310",
        "cp310",
        "manylinux_2_37_x86_64"
      ]
    }
  ],
  "path_mappings": {},
  "pex_version": "2.1.137",
  "pip_version": "20.3.4-patched",
  "prefer_older_binary": false,
  "requirements": [
    "cowsay"
  ],
  "requires_python": [],
  "resolver_version": "pip-legacy-resolver",
  "style": "strict",
  "target_systems": [],
  "transitive": true,
  "use_pep517": null
}
bash-5.1# pex --lock lock.json cowsay -c cowsay -- 'Moo!'
  ____
| Moo! |
  ====
    \
     \
       ^__^
       (oo)\_______
       (__)\       )\/\
           ||----w |
           ||     ||
bash-5.1# pex --lock lock.json cowsay -c cowsay -o cowsay.pex
bash-5.1# pex --lock lock.json cowsay -c cowsay --venv -o cowsay.venv.pex
bash-5.1# ./cowsay.pex 'Moo!'
/usr/bin/env: 'python3.10': No such file or directory
bash-5.1# nix-env --install --attr nixpkgs.python3.pkgs.python
installing 'python3-3.10.12'
this path will be fetched (9.56 MiB download, 11.25 MiB unpacked):
  /nix/store/6vrgaf4xxy89jc8zxi3s1w23cizkk12p-python3-3.10.12-debug
copying path '/nix/store/6vrgaf4xxy89jc8zxi3s1w23cizkk12p-python3-3.10.12-debug' from 'https://cache.nixos.org'...
building '/nix/store/13iind9c62lvlfcmpj22yg4qfsjbd2dy-user-environment.drv'...
bash-5.1# ./cowsay.pex 'Moo!'
  ____
| Moo! |
  ====
    \
     \
       ^__^
       (oo)\_______
       (__)\       )\/\
           ||----w |
           ||     ||
bash-5.1# ./cowsay.venv.pex 'Moo!'
  ____
| Moo! |
  ====
    \
     \
       ^__^
       (oo)\_______
       (__)\       )\/\
           ||----w |
           ||     ||
bash-5.1#
```

So I'll try to repro using `nix shell ...`.

**Comment by jsirois** [comment]
Ok, after following the multi-user install instructions for the `nix` command here: https://nixos.org/download.html and enabling flakes, etc - I do repro:
```
$ cat ~/.config/nix/nix.conf
experimental-features = nix-command flakes
$ nix shell nixpkgs#python3.pkgs.pex
$ which pex
/nix/store/hsjy0mbj4j7kyd0ycsrfadlp6r367inf-python3.10-pex-2.1.137/bin/pex
$ pex
[Errno 13] Permission denied: '/tmp/tmp5kwm0by3/.bootstrap/pex/__init__.py'
```

So, for someone with knowledge of nixos vs nix shell vs flakes, this would presumably mean something.

I'll continue to dig in my shell to see what's up.

**Comment by jsirois** [comment]
Alright, Pex 2.1.141 should fix. Please let me know either way @phaer:
+ https://pypi.org/project/pex/2.1.141/
+ https://github.com/pantsbuild/pex/releases/tag/v2.1.141

**Comment by adisbladis** [comment]
> sandbox = true

Sandboxed builds do not work inside Docker as we can't create required namespaces from an unprivileged container.

**Comment by adisbladis** [comment]
> Alright, Pex 2.1.141 should fix. Please let me know either way @phaer:
> 
>     * https://pypi.org/project/pex/2.1.141/
> 
>     * https://github.com/pantsbuild/pex/releases/tag/v2.1.141

I've tested a build against your tag and that works just fine on NixOS (with sandboxing enabled).

**Comment by jsirois** [comment]
Ok, great.

> Sandboxed builds do not work inside Docker as we can't create required namespaces from an unprivileged container.

I used `--privileged` in addition to mounting in that custom nix config.
