### ISSUE TITLE
python or-tools library looks for dylib in incorrect location on darwin 

### ISSUE THREAD

**Issue by majiru** [NixOS/nixpkgs#246615]
### Describe the bug
When attempting to use the or-tools python package, it attempts to load the incorrect dylib on macosx. The following error is generated:

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    from ortools.constraint_solver import pywrapcp
  File "/nix/store/xc83wrjzg0vq81akm14qjkczqwf9avhq-python3-3.10.12-env/lib/python3.10/site-packages/ortools/constraint_solver/pywrapcp.py", line 13, in <module>
    from . import _pywrapcp
ImportError: dlopen(/nix/store/xc83wrjzg0vq81akm14qjkczqwf9avhq-python3-3.10.12-env/lib/python3.10/site-packages/ortools/constraint_solver/_pywrapcp.so, 0x0002): Library not loaded: /tmp/nix-build-or-tools-9.4.drv-0/source/build/nix/store/ix51ykq5gi6zi76hm070zidpvbcz1d7q-or-tools-9.4/lib/libortools.9.dylib
  Referenced from: <no uuid> /nix/store/6n6vn3b39p7iw9swvwl434nxv9n0d8y4-or-tools-9.4-python/lib/python3.10/site-packages/ortools/constraint_solver/_pywrapcp.so
  Reason: tried: '/tmp/nix-build-or-tools-9.4.drv-0/source/build/nix/store/ix51ykq5gi6zi76hm070zidpvbcz1d7q-or-tools-9.4/lib/libortools.9.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/tmp/nix-build-or-tools-9.4.drv-0/source/build/nix/store/ix51ykq5gi6zi76hm070zidpvbcz1d7q-or-tools-9.4/lib/libortools.9.dylib' (no such file), '/tmp/nix-build-or-tools-9.4.drv-0/source/build/nix/store/ix51ykq5gi6zi76hm070zidpvbcz1d7q-or-tools-9.4/lib/libortools.9.dylib' (no such file), '/usr/local/lib/libortools.9.dylib' (no such file), '/usr/lib/libortools.9.dylib' (no such file, not in dyld cache)
```

### Steps To Reproduce
1. Create an environment with or-tools and (python3.withPackages ortools)
2. echo "from ortools.constraint_solver import pywrapcp" > test.py
3.  python test.py

### Expected behavior
python code should use the libortools.9.dylib in the nix store.

### Additional context

Using revision ac1acba43b2f9db073943ff5ed883ce7e8a40a2c of nixos-23.05.

It seems to me that the code is linking specifically against the version of
the library it sees during buildtime. But I am really not too familiar with
how the python build stuff works in nixpkgs.

### Notify maintainers

@andersk

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/qpb0w1pwqlp111sqs3g13i1qbhlj5n3s-DarwinTools-1
  /nix/store/ddp615qivr9hld5x0m4q046d64rkj361-nix-info
copying path '/nix/store/qpb0w1pwqlp111sqs3g13i1qbhlj5n3s-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/ddp615qivr9hld5x0m4q046d64rkj361-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by Iluvmagick** [comment]
A hack to fix it by @cab404:
adding `DYLD_LIBRARY_PATH = "${pkgs.python3Packages.ortools}/lib/python3.12/site-packages/ortools/.libs"` worked on my Mac.
