### ISSUE TITLE
whipper: FileNotFoundError when using `whipper cd rip`

### ISSUE THREAD

**Issue by collinarnett** [NixOS/nixpkgs#246675]
### Describe the bug
https://github.com/whipper-team/whipper/issues/594

### Steps To Reproduce
`whipper cd rip`

### Expected behavior
Ripped CD

### Screenshots
```shell
$ whipper cd rip       
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
Traceback (most recent call last):
  File "/nix/store/rcbk5p4ykxy82xh4pjsb6iivj5bl4lvk-whipper-0.10.0/lib/python3.10/site-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
  File "/nix/store/rcbk5p4ykxy82xh4pjsb6iivj5bl4lvk-whipper-0.10.0/lib/python3.10/site-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/nix/store/rcbk5p4ykxy82xh4pjsb6iivj5bl4lvk-whipper-0.10.0/lib/python3.10/site-packages/whipper/program/cdrdao.py", line 153, in _done
    self.toc.parse()
  File "/nix/store/rcbk5p4ykxy82xh4pjsb6iivj5bl4lvk-whipper-0.10.0/lib/python3.10/site-packages/whipper/image/toc.py", line 202, in parse
    with open(self._path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp0whbrp7t.cdrdao.read-toc.whipper.task'
CRITICAL:whipper.command.main:exception FileNotFoundError at /nix/store/rcbk5p4ykxy82xh4pjsb6iivj5bl4lvk-whipper-0.10.0/lib/python3.10/site-packages/whipper/image/toc.py:202: parse(): [Errno 2] No such file or directory: '/tmp/tmp0whbrp7t.cdrdao.read-toc.whipper.task'
Traceback (most recent call last):
  File "/nix/store/rcbk5p4ykxy82xh4pjsb6iivj5bl4lvk-whipper-0.10.0/lib/python3.10/site-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
  File "/nix/store/rcbk5p4ykxy82xh4pjsb6iivj5bl4lvk-whipper-0.10.0/lib/python3.10/site-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/nix/store/rcbk5p4ykxy82xh4pjsb6iivj5bl4lvk-whipper-0.10.0/lib/python3.10/site-packages/whipper/program/cdrdao.py", line 153, in _done
    self.toc.parse()
  File "/nix/store/rcbk5p4ykxy82xh4pjsb6iivj5bl4lvk-whipper-0.10.0/lib/python3.10/site-packages/whipper/image/toc.py", line 202, in parse
    with open(self._path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp0whbrp7t.cdrdao.read-toc.whipper.task'
```

### Additional context
The original issue:
https://github.com/whipper-team/whipper/issues/594
The fix linked in the issue:
https://github.com/whipper-team/whipper/issues/594

So the fix seems to be either downgrade `cdrdao` to 1.2.4 or apply the patch listed in the arch repo.

### Notify maintainers
@emilazy 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.21, NixOS, 23.11 (Tapir), 23.11.20230713.e74e684`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(collin): `""`
 - channels(root): `"nixos-21.11.335130.386234e2a61"`
 - nixpkgs: `/nix/store/xckzwlwa4abf9r3b71fvlyk9889gfrl2-source`
 ```

**Comment by emilazy** [comment]
It's hard to imagine how this specific error could be related to an encoding issue... both of your links point to the same place, do you have a link to the fix you're talking about?

**Comment by emilazy** [comment]
Ah, I found the one used in the Arch package. I'm not presently able to test the fix myself, however; if I give you an amended Nixpkgs branch and instructions to try it, would you be able to see if it works correctly?

**Comment by collinarnett** [comment]
I applied the downgrade and it works. If you can give me the patch I can test it as well.

**Comment by emilazy** [comment]
Thanks; please try https://github.com/emilazy/nixpkgs/tree/cdrdao-fixes (patch: https://github.com/emilazy/nixpkgs/compare/9e1960bc196baf6881340d53dccb203a951745a2...cdrdao-fixes.diff).

Sadly it seems like neither cdrdao nor whipper get very much upstream maintainer attention these days...

**Comment by emilazy** [comment]
Thanks for testing; opened https://github.com/NixOS/nixpkgs/pull/247063.
