### ISSUE TITLE
PM2 not a startup process

### ISSUE THREAD

**Issue by adminy** [NixOS/nixpkgs#246807]
### Describe the bug
When running `pm2 startup` it will attempt to create it as a startup service as that wasn't done in the setup step.
```
Command list
[ 'systemctl enable pm2-root' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-root.service
Error:

[PM2][ERROR] Failure when trying to write startup script
EROFS: read-only file system, open '/etc/systemd/system/pm2-root.service'
```

### Steps To Reproduce
1. Install pm2 nodejs package
2. run any pm2 script and save the state of the script
3. reboot, you will loose everything as `pm2 startup` script wasn't run during setup.

### Expected behavior
PM2 should be a startup daemon run by systemd.

### Additional context
pm2 startup is a setup script, so it needs to run as as part of package install.

### Notify maintainers

@jeremyschlatter, @jtojnar, @pingpwned

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.49-linuxkit-pr`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
```console
[user@system:~]$ nix-shell -p nodePackages."pm2" --run "pm2 startup" 
```
```
[PM2][ERROR] Init system not found
/nix/store/kp4jprgxfkr2byxnav6didr8lmypvj65-pm2-5.3.0/lib/node_modules/pm2/lib/API/Startup.js:209
      throw new Error('Init system not found');
      ^

Error: Init system not found
    at CLI.startup (/nix/store/kp4jprgxfkr2byxnav6didr8lmypvj65-pm2-5.3.0/lib/node_modules/pm2/lib/API/Startup.js:209:13)
    at Command.<anonymous> (/nix/store/kp4jprgxfkr2byxnav6didr8lmypvj65-pm2-5.3.0/lib/node_modules/pm2/lib/binaries/CLI.js:707:9)
    at Command.listener (/nix/store/kp4jprgxfkr2byxnav6didr8lmypvj65-pm2-5.3.0/lib/node_modules/pm2/node_modules/commander/index.js:315:8)
    at Command.emit (node:events:513:28)
    at Command.parseArgs (/nix/store/kp4jprgxfkr2byxnav6didr8lmypvj65-pm2-5.3.0/lib/node_modules/pm2/node_modules/commander/index.js:651:12)
    at Command.parse (/nix/store/kp4jprgxfkr2byxnav6didr8lmypvj65-pm2-5.3.0/lib/node_modules/pm2/node_modules/commander/index.js:474:21)
    at Timeout._onTimeout (/nix/store/kp4jprgxfkr2byxnav6didr8lmypvj65-pm2-5.3.0/lib/node_modules/pm2/lib/binaries/CLI.js:206:15)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.16.1
```

**Comment by louwers** [comment]
Not a bug. 

`pm2 startup` is just a convenience for creating a systemd unit, but you can create this yourself.

**Comment by adminy** [comment]
how? Should we not have a flag that sets that up on the install time?

**Comment by louwers** [comment]
Do you mean a configuration option? Yes that is possible, but that should be considered a feature request.

Yes that is possible, but the implementation of that won't run `pm2 startup`. NixOS is not listed as one of the supported distributions: https://pm2.keymetrics.io/docs/usage/startup/ This makes sense because this would need to be declaratively configured in the case of NixOS.

**Comment by louwers** [comment]
@adminy Try adding this to your `configuration.nix`.

```
  systemd.services.pm2 = {
    enable = true;
    description = "pm2";
    unitConfig = {
      Type = "simple";
    };
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.nodePackages_latest.pm2}/bin/pm2 resurrect";
      ExecReload = "${pkgs.nodePackages_latest.pm2}/bin/pm2 reload all";
      ExecStop = "${pkgs.nodePackages_latest.pm2}/bin/pm2 kill";
    };
  };
```

This can probably be polished a bit more.

**Comment by adminy** [comment]
Its funny I just defined this:
```nix
 systemd.user.services.pm2 = {
    enable = true;
    Unit = {
      Description   = "PM2 process manager";
      Documentation = "https://pm2.keymetrics.io/";
      After         = ["network.target"];
    };

    Service = {
      Type        = "forking";
      User        = "root";
      LimitNOFILE = "infinity";
      LimitNPROC  = "infinity";
      LimitCORE   = "infinity";
      Environment = "PM2_HOME=/root/.pm2";
      PIDFile     = "/root/.pm2/pm2.pid";
      Restart     = "on-failure";
      ExecStart   = "${pkgs.pm2}/lib/node_modules/pm2/bin/pm2 resurrect";
      ExecReload  = "${pkgs.pm2}/lib/node_modules/pm2/bin/pm2 reload all";
      ExecStop    = "${pkgs.pm2}/lib/node_modules/pm2/bin/pm2 kill";
    };
    Install.WantedBy = ["multi-user.target"];
  };
```
and was just about to test it

**Comment by adminy** [comment]
Thank you @louwers, that worked!
