### ISSUE TITLE
IntelliJ Bundled Markdown Plugin Broken

### ISSUE THREAD

**Issue by jamesward** [NixOS/nixpkgs#247148]
### Steps To Reproduce
1. Open a `.md` file in IntelliJ 2023.2
2. Notice there is no button to preview the markdown
3. Check the IntelliJ logs and see:
    ```
    2023-08-04 10:48:56,483 [ 407490]   WARN - #c.i.i.p.n.PluginLogo - Cannot load plugin icon (file=/nix/store/88idkg7wyqg6marjr053rs9bma4qcgyw-idea-ultimate-2023.2/idea-ultimate/plugins/markdown/lib/markdown.jar/META-INF/pluginIcon.svg)
    java.nio.file.FileSystemException: /nix/store/88idkg7wyqg6marjr053rs9bma4qcgyw-idea-ultimate-2023.2/idea-ultimate/plugins/markdown/lib/markdown.jar/META-INF/pluginIcon.svg: Not a directory
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
	at com.intellij.ide.plugins.newui.PluginLogoKt.tryLoadIcon(PluginLogo.kt:346)
	at com.intellij.ide.plugins.newui.PluginLogoKt.tryLoadDirIcons(PluginLogo.kt:259)
	at com.intellij.ide.plugins.newui.PluginLogoKt.loadPluginIconsFromFile(PluginLogo.kt:242)
	at com.intellij.ide.plugins.newui.PluginLogoKt.access$loadPluginIconsFromFile(PluginLogo.kt:1)
	at com.intellij.ide.plugins.newui.PluginLogoLoader$schedulePluginIconLoading$1$1.invokeSuspend(PluginLogo.kt:392)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
    ```

### Expected behavior
Bundled Markdown plugin should work.

### Notify maintainers
@edwtjo @gytis-ivaskevicius @steinybot @AnatolyPopov

### Metadata
```console
~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.7, NixOS, 23.05 (Stoat), 23.05.2517.e9ca92b55be`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(jw): `""`
 - channels(root): `"android-nixpkgs, home-manager-23.05.tar.gz, nixos-23.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by chasecaleb** [comment]
I can confirm this as well. Another way to check:
1. Open IntelliJ IDEA's settings (`ctrl+alt+s`)
2. On left-hand menu, go to Languages & Frameworks -> Markdown
3. Top of the Markdown settings area says "There are no available preview providers"

**Comment by dritter** [comment]
Hmm. This should AFAIR be fixed by #245717 (which is already merged and in [unstable](https://nixpk.gs/pr-tracker.html?pr=245717)).

**Comment by dritter** [comment]
Btw. @jamesward @chasecaleb @MartinRamm could any of you confirm that this bug is fixed?

**Comment by kshinson** [comment]
@chasecaleb had commented this on my behalf, and I can confirm it's fixed for me.
