### ISSUE TITLE
docker: SIGSEGV

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#24796]
## Issue description
Trying to push with Docker 17.04-ce results in a SIGSEGV

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x89f670]

goroutine 1 [running]:
panic(0x9fa720, 0xc420010110)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.7.4/share/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/docker/vendor/github.com/Nvveen/Gotty.(*TermInfo).GetAttribute(0x0, 0xaa4fe2, 0x3, 0x0, 0xc42006e400, 0x10, 0x7fb0afc4c960)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/vendor/github.com/Nvveen/Gotty/gotty.go:94 +0x140
github.com/docker/docker/vendor/github.com/Nvveen/Gotty.(*TermInfo).Parse(0x0, 0xaa4fe2, 0x3, 0xc4203f2220, 0x1, 0x1, 0xc420179400, 0x462285, 0xc42040e000, 0xc4203fe140)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/vendor/github.com/Nvveen/Gotty/parser.go:42 +0x5a
github.com/docker/docker/pkg/jsonmessage.cursorUp(0xfb1540, 0xc4202daed0, 0xfb1ac0, 0x0, 0x1)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go:144 +0xec
github.com/docker/docker/pkg/jsonmessage.DisplayJSONMessagesStream(0xfb2640, 0xc4203fc040, 0xfb1540, 0xc4202daed0, 0x1, 0xc420179601, 0xc4201798c8, 0xa10960, 0xa649a0)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go:263 +0x3e8
github.com/docker/docker/pkg/jsonmessage.DisplayJSONMessagesToStream(0xfb2640, 0xc4203fc040, 0xfb7d80, 0xc4202daed0, 0xc4201798c8, 0xc4203b48a0, 0x30)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go:292 +0xd5
github.com/docker/docker/cli/command/image.PushTrustedReference(0xc42031f570, 0xc4203b4630, 0xfb7200, 0xc4203ba1e0, 0xc42039a6a0, 0xa, 0xc42039a6ab, 0xc, 0x0, 0x0, ...)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/cli/command/image/trust.go:90 +0x403
github.com/docker/docker/cli/command/image.trustedPush(0x7fb0afbf0028, 0xc420010310, 0xc42031f570, 0xc4203b4630, 0xfb7200, 0xc4203ba1e0, 0xc42039a6a0, 0xa, 0xc42039a6ab, 0xc, ...)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/cli/command/image/trust.go:40 +0x1bb
github.com/docker/docker/cli/command/image.runPush(0xc42031f570, 0x7fffdb9e5b1c, 0x27, 0x0, 0x0)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/cli/command/image/push.go:51 +0x40e
github.com/docker/docker/cli/command/image.NewPushCommand.func1(0xc420394d80, 0xc42035d700, 0x1, 0x1, 0x0, 0x0)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/cli/command/image/push.go:21 +0x4a
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc420394d80, 0xc42000c260, 0x1, 0x1, 0xc420394d80, 0xc42000c260)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x26d
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420099200, 0xc420099680, 0xc4202f74c0, 0xc42003c498)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x377
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420099200, 0xc420099200, 0xfb2a00)
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
	/tmp/nix-build-docker-17.04.0-ce.drv-0/docker-v17.04.0-ce-src/.gopath/src/github.com/docker/docker/cmd/docker/docker.go:168 +0xcb
```

### Steps to reproduce
- Enable Docker content trust `export DOCKER_CONTENT_TRUST="1"`
- Push an image to a registry

## Technical details

* System: 17.03.917.12a39478fd (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.917.12a39478fd"

**Comment by Fuuzetsu** [comment]
On 93d364f4f50ce54cd216361e4a4dd683c1933a10 with 0a4c43065c5fe4bd599399c02321bb6dd39421af reverted, still a problem today.

**Comment by Fuuzetsu** [comment]
OK, on https://github.com/NixOS/nixpkgs/commit/93d364f4f50ce54cd216361e4a4dd683c1933a10 no segfault on `docker push`; I suppose we can close then, re-open if happens on master.
