### ISSUE TITLE
SoapUI crashes on macOS

### ISSUE THREAD

**Issue by jacekszymanski** [NixOS/nixpkgs#247966]
### Describe the bug
`SoapUI` crashes on macOS (Monterey) with the following log:

```console
================================
=
= SOAPUI_HOME = /nix/store/xlr4y1ga8ppl9ghpiwnncwcq6z6rci5r-soapui-5.7.0/share/java
=
================================
Configuring log4j from [/nix/store/xlr4y1ga8ppl9ghpiwnncwcq6z6rci5r-soapui-5.7.0/share/java/bin/soapui-log4j.xml]
17:23:52,236 INFO  [DefaultSoapUICore] Creating new settings at [/Users/jsz/soapui-settings.xml]
17:23:53,601 INFO  [PluginManager] 0 plugins loaded in 3 ms
17:23:53,602 INFO  [DefaultSoapUICore] All plugins loaded
17:23:54,283 INFO  [DefaultSoapUICore] Defaulting to native L&F for Mac OS X
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
17:23:55,692 INFO  [SoapUI] Used java version: 11.0.11
Aug 08, 2023 5:23:58 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5748fbd5'
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:224)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:224)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

### Steps To Reproduce
1. `nix-shell -p soapui` (or otherwise get from Nixpkgs)
2. `soapui`
3. SoapUI opens, shows "tip of the day", crashes before it's possible to open/create a project.

### Expected behavior
SoapUI doesn't crash.

### Notify maintainers
@Gerschtli 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

**Comment by tricktron** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/251808
