### ISSUE TITLE
Package request: Conan 1.60

### ISSUE THREAD

**Issue by kuznetsss** [NixOS/nixpkgs#249790]
**Project description**

Decentralized, open-source (MIT), C/C++ package manager.

**Metadata**

* homepage URL: https://conan.io/
* source URL: https://github.com/conan-io/conan/tree/release/1.60
* license: mit
* platforms: unix, linux, darwin

I know that conan v2.0 exists, but some projects require the old one.

**Comment by kuznetsss** [comment]
I tried to backport it by myself, but I'm only started to learn nix. But the problem is the old conan requires python package `node-semver v0.6.1` which was called `semver` at that version.

<details>
  <summary>
    My conan_1.60.2.nix file
  </summary>
  
```nix
let
  pkgs = import <nixpkgs> {};
in with pkgs;

python3.pkgs.buildPythonApplication rec {
  pname = "conan";
  version = "1.60.2";
  format = "setuptools";

  src = fetchFromGitHub {
    owner = "conan-io";
    repo = "conan";
    rev = "refs/tags/${version}";
    sha256 = "054l4bv864id1c3pp6plc6af63cbpi9x9xznbqi0zfl8i35ipv3j";
  };

  postPatch = ''
    substituteInPlace conans/requirements.txt \
      --replace 'node-semver==0.6.1' 'node-semver>=0.6.1'
  '';

  nativeBuildInputs = with python3.pkgs; [
    pythonRelaxDepsHook
  ];

  propagatedBuildInputs = with python3.pkgs; [
    bottle
    colorama
    python-dateutil
    deprecation
    distro
    fasteners
    node-semver
    future
    jinja2
    patch-ng
    pluginbase
    pygments
    pyjwt
    pylint # Not in `requirements.txt` but used in hooks, see https://github.com/conan-io/conan/pull/6152
    pyyaml
    requests
    six
    tqdm
    urllib3
  ] ++ lib.optionals stdenv.isDarwin [
    idna
    cryptography
    pyopenssl
  ];

  pythonRelaxDeps = [
    # This can be removed once conan is updated to 2.0.7+
    "PyYAML"
  ];

  nativeCheckInputs = [
    git
    pkg-config
    zlib
  ] ++ (with python3.pkgs; [
    mock
    parameterized
    pytest-xdist
    pytestCheckHook
    webtest
  ]);

  __darwinAllowLocalNetworking = true;

  pythonImportsCheck = [
    "conan"
  ];

  pytestFlagsArray = [
    "-n"
    "$NIX_BUILD_CORES"
  ];

  disabledTests = [
    # Tests require network access
    "TestFTP"
  ] ++ lib.optionals stdenv.isDarwin [
    # Rejects paths containing nix
    "test_conditional_os"
    # Requires Apple Clang
    "test_detect_default_compilers"
    "test_detect_default_in_mac_os_using_gcc_as_default"
    # Incompatible with darwin.xattr and xcbuild from nixpkgs
    "test_dot_files"
    "test_xcrun"
    "test_xcrun_in_required_by_tool_requires"
    "test_xcrun_in_tool_requires"
  ];

  disabledTestPaths = [
    # Requires cmake, meson, autotools, apt-get, etc.
    "conans/test/functional/command/new_test.py"
    "conans/test/functional/command/test_install_deploy.py"
    "conans/test/functional/graph/test_transitive_build_scripts.py"
    "conans/test/functional/layout/test_editable_cmake_components.py"
    "conans/test/functional/layout/test_editable_cmake.py"
    "conans/test/functional/layout/test_in_subfolder.py"
    "conans/test/functional/layout/test_source_folder.py"
    "conans/test/functional/toolchains/"
    "conans/test/functional/tools_versions_test.py"
    "conans/test/functional/tools/scm/test_git.py"
    "conans/test/functional/tools/system/package_manager_test.py"
    "conans/test/functional/util/test_cmd_args_to_string.py"
    "conans/test/integration/command_v2/list_test.py"
    "conans/test/unittests/tools/env/test_env_files.py"
  ];

  meta = with lib; {
    description = "Decentralized and portable C/C++ package manager";
    homepage = "https://conan.io";
    changelog = "https://github.com/conan-io/conan/releases/tag/${version}";
    license = licenses.mit;
    maintainers = with maintainers; [ HaoZeke ];
  };
}
```

</details>

So my build process is falling on trying to import conan module.
<details>
 <summary>Build log</summary>
 
```
Check whether the following modules can be imported: conan
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/6xmv46hawz0iqgvzwllmagzqc9pws00d-python3-3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/sdwjf8472cljcwxhm7npkbbf6m6vdlla-conan-1.60.2/lib/python3.10/site-packages/conan/__init__.py", line 1, in <module>
    from conans.model.conan_file import ConanFile
  File "/nix/store/sdwjf8472cljcwxhm7npkbbf6m6vdlla-conan-1.60.2/lib/python3.10/site-packages/conans/__init__.py", line 4, in <module>
    from conans.client.build.msbuild import MSBuild
  File "/nix/store/sdwjf8472cljcwxhm7npkbbf6m6vdlla-conan-1.60.2/lib/python3.10/site-packages/conans/client/build/msbuild.py", line 15, in <module>
    from conans.tools import vcvars_command as tools_vcvars_command
  File "/nix/store/sdwjf8472cljcwxhm7npkbbf6m6vdlla-conan-1.60.2/lib/python3.10/site-packages/conans/tools.py", line 31, in <module>
    from conans.client.tools.version import Version
  File "/nix/store/sdwjf8472cljcwxhm7npkbbf6m6vdlla-conan-1.60.2/lib/python3.10/site-packages/conans/client/tools/version.py", line 5, in <module>
    from semver import SemVer
ModuleNotFoundError: No module named 'semver'
```

</details>

I think I should somehow install the old version of node-semver as [it is done in homebrew](https://github.com/Homebrew/homebrew-core/blob/8e192cbecc4562faf4cb7058ecdf99e8e5fcefc8/Formula/c/conan@1.rb#L76-L79), but I don't know how to do the same thing in nix. So I would be happy for any help.

**Comment by kuznetsss** [comment]
I got conan 1.60.2 compiling at least on darwin aarch64.
