### ISSUE TITLE
Build failure: python3.10-pypandoc-1.10

### ISSUE THREAD

**Issue by lo2dev** [NixOS/nixpkgs#249946]
### Steps To Reproduce

1. `nix build --no-link --print-build-logs github:nixos/nixpkgs#python310Packages.pypandoc`

### Build log

```
python3.10-pypandoc> ======================================================================
python3.10-pypandoc> FAIL: test_ensure_pandoc_maximal_version (tests.TestPypandoc)
python3.10-pypandoc> ----------------------------------------------------------------------
python3.10-pypandoc> Traceback (most recent call last):
python3.10-pypandoc>   File "/build/source/tests.py", line 173, in test_ensure_pandoc_maximal_version
python3.10-pypandoc>     assert pypandoc.ensure_pandoc_maximal_version(1,1) == False
python3.10-pypandoc> AssertionError
python3.10-pypandoc> ======================================================================
python3.10-pypandoc> FAIL: test_ensure_pandoc_minimal_version (tests.TestPypandoc)
python3.10-pypandoc> ----------------------------------------------------------------------
python3.10-pypandoc> Traceback (most recent call last):
python3.10-pypandoc>   File "/build/source/tests.py", line 165, in test_ensure_pandoc_minimal_version
python3.10-pypandoc>     assert pypandoc.ensure_pandoc_minimal_version(1) == True
python3.10-pypandoc> AssertionError
python3.10-pypandoc> ----------------------------------------------------------------------
python3.10-pypandoc> Ran 40 tests in 9.740s
python3.10-pypandoc> FAILED (failures=3, errors=1, skipped=1)
python3.10-pypandoc> Test failed: <unittest.runner.TextTestResult run=40 errors=1 failures=3>
python3.10-pypandoc> error: Test failed: <unittest.runner.TextTestResult run=40 errors=1 failures=3>
error: builder for '/nix/store/42igrm26chfpl6ia4vs4adhh5r1zam1r-python3.10-pypandoc-1.10.drv' failed with exit code 1;
       last 10 log lines:
       >   File "/build/source/tests.py", line 165, in test_ensure_pandoc_minimal_version
       >     assert pypandoc.ensure_pandoc_minimal_version(1) == True
       > AssertionError
       >
       > ----------------------------------------------------------------------
       > Ran 40 tests in 9.740s
       >
       > FAILED (failures=3, errors=1, skipped=1)
       > Test failed: <unittest.runner.TextTestResult run=40 errors=1 failures=3>
       > error: Test failed: <unittest.runner.TextTestResult run=40 errors=1 failures=3>
       For full logs, run 'nix log /nix/store/42igrm26chfpl6ia4vs4adhh5r1zam1r-python3.10-pypandoc-1.10.drv'.
```

### Notify maintainers
@sternenseemann
@bennofs

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.11 (Tapir), 23.11.20230816.caac0eb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/hwp2x4k2p6ar2xpzbmjbl278sqxmxv0s-source`
```

**Comment by sternenseemann** [comment]
https://github.com/JessicaTegner/pypandoc/issues/331

**Comment by austinbutler** [comment]
Closing this, upstream issue is closed and this builds now.
