### ISSUE TITLE
NixOps deploy build fails when using +1000 keys - bash argument list too long

### ISSUE THREAD

**Issue by 4levels** [NixOS/nixpkgs#25057]
## Issue description
When deploying a machine with lots of keys, the deploy fails with a bash "argument list too long" error.

### Steps to reproduce
Create 2 nix files as explained in the sample from the manual:
test.nix:
```
{
  network.description = "Web server";
  webserver =
    { config, pkgs, ... }:
    { services.httpd.enable = true;
      services.httpd.adminAddr = "alice@example.org";
      networking.firewall.allowedTCPPorts = [ 80 ];
    };
}
```

test-servers.nix:
```
webserver =
  { config, pkgs, ... }:
  {
    deployment.targetEnv = "virtualbox";
    deployment.virtualbox.memorySize = 1024; # megabytes
    deployment.virtualbox.vcpu = 2; # number of cpus
    };
  }
```

Add a lot of keys to test-servers.nix, in the form below (example)
```
    deployment.keys."phpmyadmin.password" = {
      text = fileContents (./keys/phpmyadmin.password);
      group = "keys";
      permissions = "0640";
    };
```

Create a new deployment:
```
$ nixops create -dtest test.nix test-servers.nix
```

The build never succeeds
```
$ nixops deploy -dtest --build-only:
building path(s) ‘/nix/store/lv40g4brdfa187x3h08jbxgwrs12gmpm-nixos-system-webserver-17.03.890.ce3ab704b2’
while setting up the build environment: executing ‘/nix/store/86blj9iqyxwmdgkn3dyrpib1gkbmz91v-bash-4.4-p5/bin/bash’: Argument list too long
builder for ‘/nix/store/apmw3a1pb7imlw7p6vls9hs6glj4n44h-nixos-system-webserver-17.03.890.ce3ab704b2.drv’ failed with exit code 1
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
  **17.03.890.ce3ab704b2 (Gorilla)**
* Nix version: (run `nix-env --version`)
  **nix-env (Nix) 1.11.8**
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
  **17.03.890.ce3ab704b2**

**Comment by pbogdan** [comment]
Apologies for butting in as I know next to nothing about nixops but could you confirm how many keys are you using? I'm on 17.03 as well and tried to reproduce with 10000 keys (`phpmyadmin1` - `phpmyadmin10000`)  and, while very slow, `nixops deploy -dtest --build-only` has been happily chugging along for the last 40 minutes whereas it seems to abort immediately for you.

**Comment by domenkozar** [comment]
The issue is that our builder is bash and it the file used for the builder is too long, you'll get this error.

Here is the derivation that fails to build: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/activation/top-level.nix#L106

Try adding somewhere below (inside the `mkDerivation` call):

```
passAsFile = [ "buildCommand" ];
```

This will pass the builder as a file, instead of a string.

**Comment by 4levels** [comment]
Hi @pbogdan,

I ran the deploy task several times, so it doesn't build all the derivations anymore (it takes some time indeed as nixops seems to generate derivations and services for every single key file)
So it goes immediately to the last step (the failing bash call).

@domenkozar How would I go about testing your addition to the mentioned file?  Should I fork this repo, adjust the file and use that as -I parameter to the nixops deploy call?
Currently I'm using 
```
nixops deploy -dtest --build-only -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-16.09.tar.gz
```

As a side note: I'm still using 16.09 as somehow phpfpm is no longer available as package in 17.03 (or I haven't figured out what to do to use phpfpm in 17.03)

Kind regards,

Erik

**Comment by domenkozar** [comment]
Fork, change the file, use `-I nixpkgs=/path/to/nixpkgs`, profit.

**Comment by 4levels** [comment]
Hi Domen,

I'm just from trying this out: I forked the nixpkgs-channels repo, adjusted the file in https://github.com/4levels/nixpkgs-channels/blob/nixos-16.09/nixos/modules/system/activation/top-level.nix#L105

and used `-I nixpkgs=https://github.com/4levels/nixpkgs-channels/archive/nixos-16.09.tar.gz` but to no avail :-(

I verified the contents of the tar.gz archive and the file inside `nixos/modules/system/activation/top-level.nix` is the correct one (with the passAsFile addition).

So either I'm still doing something wrong, or the passAsFile command doesn't seem to help

**Comment by 4levels** [comment]
Hi @domenkozar,

even after running nix-collect-garbage -d (it took about 20 minutes to regenerate all direvations) the same error still pops up :-(

Am I doing something wrong or is the passAsFile option not the correct one?

Kind regards and thanks again already!

**Comment by domenkozar** [comment]
Can you make a diff how you added the flag?

**Comment by 4levels** [comment]
I just added 1 single line:

```
passAsFile = [ "buildCommand" ];
```

here: https://github.com/4levels/nixpkgs-channels/blob/nixos-16.09/nixos/modules/system/activation/top-level.nix#L105

Or was I supposed to replace "buildCommand" with something else?  I'm on totally uncharted territory here ;-)

**Comment by 4levels** [comment]
Hi @domenkozar,

I'm just trying now with changing `buildCommand` to `buildCommandPath` as I found references of one of your PR's adding a check for this in setup.sh - https://github.com/NixOS/nixpkgs/pull/15803/files

So I commented out the previous passAsFile line and changed buildCommand to buildCommandPath here: https://github.com/4levels/nixpkgs-channels/blob/nixos-16.09/nixos/modules/system/activation/top-level.nix#L108

I did another `nix-collect-garbage -d` but after rebuilding all derivations, this fails again with the exact same error..

Thanks again..

**Comment by 4levels** [comment]
I'm giving it another try, this time with
```
passAsFile = [ "buildCommand" "activationScript" ];
```
after removing the previous try with buildCommandPath

https://github.com/4levels/nixpkgs-channels/blob/nixos-16.09/nixos/modules/system/activation/top-level.nix#L105

New test running...

**Comment by 4levels** [comment]
@domenkozar 

Adding the activationScript to the passAsFile list seems to work!
I'm trying this asap in my "real" deployment setup and report back here ;-)

If this actually solves my issue, I'm definitely buying you a beer (or a coffee or a tea)!

Fingers crossed!

**Comment by 4levels** [comment]
Hi @domenkozar,

So the build runs fine now, but the copying closures call seems to fail now:

```
secure........> copying closure...
error: [Errno 7] Argument list too long
```

**Comment by domenkozar** [comment]
It's failing eithere here https://github.com/NixOS/nixops/blob/master/nixops/backends/__init__.py#L336 or a few lines lower.

**Comment by 4levels** [comment]
Hi @domenkozar,

Exactly what I thought as well! I just found the same line in the same file by searching the NixOps repository..

But how to resolve?  It seems like all closures are joined as a string, but how to work around that?

Fiew, now I'm diving into Python code as well, more uncharted territories..

**Comment by 4levels** [comment]
Hi @domenkozar,

All I can see with my limited python skills is that the function `logged_exec` seems related as well:

https://github.com/NixOS/nixops/blob/master/nixops/util.py#L46

But I'm sure you've already seen that as well.  I hope there is a similar workaround for this!

Kind regards,

**Comment by dezgeg** [comment]
I think it's better to fix this in nixops by instead of generating a huge `system.activationScripts.nixops-keys` script, rather put the huge part into its own file and source it from the activation script.

**Comment by 4levels** [comment]
Hi @dezgeg,

How would I go about that? I obviously have no idea how to put this part into a file and source it :-(

Kind regards,

**Comment by dezgeg** [comment]
Something like this to nixops (completely untested):
````
diff --git a/nix/keys.nix b/nix/keys.nix
index b6a1e6b..65c55bc 100644
--- a/nix/keys.nix
+++ b/nix/keys.nix
@@ -123,33 +123,35 @@ in
       "things to break."
     )];
 
-    system.activationScripts.nixops-keys = stringAfter [ "users" "groups" ]
-      ''
-        mkdir -p /run/keys -m 0750
-        chown root:keys /run/keys
-
-        ${optionalString config.deployment.storeKeysOnMachine
-            (concatStrings (mapAttrsToList (name: value:
-              let
-                # FIXME: The key file should be marked as private once
-                # https://github.com/NixOS/nix/issues/8 is fixed.
-                keyFile = pkgs.writeText name value.text;
-              in "ln -sfn ${keyFile} /run/keys/${name}\n")
-              config.deployment.keys)
-            + ''
-              # FIXME: delete obsolete keys?
-              touch /run/keys/done
-            '')
-        }
-
-        ${concatStringsSep "\n" (flip mapAttrsToList config.deployment.keys (name: value:
-          # Make sure each key has correct ownership, since the configured owning
-          # user or group may not have existed when first uploaded.
-          ''
-            [[ -f "/run/keys/${name}" ]] && chown '${value.user}:${value.group}' "/run/keys/${name}"
-          ''
-        ))}
-      '';
+    system.activationScripts.nixops-keys =
+      let script = ''
+          mkdir -p /run/keys -m 0750
+          chown root:keys /run/keys
+
+          ${optionalString config.deployment.storeKeysOnMachine
+              (concatStrings (mapAttrsToList (name: value:
+                let
+                  # FIXME: The key file should be marked as private once
+                  # https://github.com/NixOS/nix/issues/8 is fixed.
+                  keyFile = pkgs.writeText name value.text;
+                in "ln -sfn ${keyFile} /run/keys/${name}\n")
+                config.deployment.keys)
+              + ''
+                # FIXME: delete obsolete keys?
+                touch /run/keys/done
+              '')
+          }
+
+          ${concatStringsSep "\n" (flip mapAttrsToList config.deployment.keys (name: value:
+            # Make sure each key has correct ownership, since the configured owning
+            # user or group may not have existed when first uploaded.
+            ''
+              [[ -f "/run/keys/${name}" ]] && chown '${value.user}:${value.group}' "/run/keys/${name}"
+            ''
+          ))}
+        '';
+      # Generate the script in a separate file to avoid a "Argument list too long" with a huge number of keys.
+      in stringAfter [ "users" "groups" ] "source ${pkgs.writeText "setup-keys.sh" script}";
 
     systemd.services = (
       { nixops-keys =
````

**Comment by 4levels** [comment]
Hi @dezgeg,

Thank you so much for this patch.

Could you be so kind to instruct me how to use my own forked version of the NixOps package in my deploy machine?  I'm not too sure how I can tell nix to use my forked version of NixOps instead of the standard one.

I have already forked the nixpkgs repo as well and I'm using that for now..

Kind regards,

Erik

**Comment by 4levels** [comment]
Hi All,

I've been trying really hard to get my version of Nixops in my local nixos machine running, but I'm failing miserably.  Everything I try results in failures, wrong packages being downloaded and what more, sigh

Even when I try this (from the manual):

file: **my-nixops.nix**
```
with import <nixpkgs> {}; # bring all of Nixpkgs into scope

stdenv.mkDerivation rec {
  name = "nixops";
  src = fetchurl {
    url = "https://github.com/4levels/nixops/archive/master.tar.gz";
    sha256 = "02p19r970dg3xyskicml5v2vps2r5mms2s8sv596ij3g33ym7jhc";
  };
}
```
Then this fails: 
```
$ nix-build my-nixops.nix`
these derivations will be built:
  /nix/store/7am2z9w20b0ryp751sb8nziy8y8lzk38-master.tar.gz.drv
  /nix/store/17vnz9and9qii2rkqbm8vdlf3ysxlhkq-nixops.drv
building path(s) ‘/nix/store/jibakjw535nxgqwz2krcik8xfyvh5ky0-master.tar.gz’

trying https://github.com/4levels/nixops/archive/master.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122    0   122    0     0    198      0 --:--:-- --:--:-- --:--:--   198
100  268k  100  268k    0     0   102k      0  0:00:02  0:00:02 --:--:--  220k
building path(s) ‘/nix/store/kwdfrr02pzyyvkaxmx6a6gfsdd5x14g1-nixops’
unpacking sources
unpacking source archive /nix/store/jibakjw535nxgqwz2krcik8xfyvh5ky0-master.tar.gz
source root is nixops-master
setting SOURCE_DATE_EPOCH to timestamp 1493112297 of file nixops-master/tests/unit/test_split_openssh_args.py
warning: file nixops-master/tests/unit/test_split_openssh_args.py may be generated; SOURCE_DATE_EPOCH may be non-deterministic
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
install flags: install    
make: *** No rule to make target 'install'.  Stop.
```

The documentation in the Nixops readme seems very outdated as well: eg, the installation instructions link leads to a 404 and the Google groups seems very dead.

Hope someone can help, I'm really close to solving this issue!

As a sidenote: isn't it a good change to have the nixops-keys script always use a file based process as suggested by @dezgeg? If this change would make it in the official repo, I wouldn't even have to go through this struggle..

Kind regards,

Erik aka 4levels

**Comment by domenkozar** [comment]
https://nixos.org/nixops/manual/#chap-hacking

**Comment by 4levels** [comment]
Hi @domenkozar, thanks a lot, I totally overlooked this appendix in the manual..

Maybe this should go in the Nixops readme instead of the 404 link ;-)

**Comment by 4levels** [comment]
Hi @dezgeg,

your fix doesn't seem to change anything, the copying closure call still fails with
[Error 7] Argument list too long

I'm currently checking if I can adjust the copy closure part just as you did adjusted the activationScript

Kind regards,

Erik

**Comment by domenkozar** [comment]
Fixed: https://github.com/NixOS/nixops#nixops

**Comment by 4levels** [comment]
Hi @domenkozar, you fixed the documentation links, right?  Or did you also manage to fix this actual issue?

As this is all so confusing and new for me, I'm giving up to see this resolved anytime soon.  If no-one else cares to fix this, I guess it will remain broken untill someone with the needed skills runs into this limitation and creates a fix.  
I'll resort to ecnrypting and packaging the key files and try to get them in the keystore myself :-(

Too bad though as I felt like I was almost there to workaround this bug!

Thanks again for all your support!

Erik

**Comment by domenkozar** [comment]
I wish I had time to help you. Add some print statements around that code so that you can see how the code is being invoked.

**Comment by 4levels** [comment]
Hi Domen, like I said before, I have never written a single line of python code.  Besides that, I don't even understand how nixops / nix works / is built.  So this is clearly out of my leage, let alone me trying to debug this..

**Comment by domenkozar** [comment]
If you can create a gist that I can simply run that reproduces the issue I can look into it soon :)

**Comment by 4levels** [comment]
Hi Domen,

I can create a gist, but I cannot add +1000 key files to it, right?
I can create a tar archive with the 2 forementioned nix expressions (test.nix and test-server.nix) and the related key files.

**Comment by dezgeg** [comment]
Would be useful to have the full Python stack trace as well.

**Comment by 4levels** [comment]
Hi Domen,

I wouldn't know how to get to that point.  It seems like @pbogdan found a quick way to test this with 10k files, maybe he can shed some light how he set this up...

**Comment by domenkozar** [comment]
@4levels can you reproduce nixops error by passing `--debug`?

**Comment by 4levels** [comment]
HI @domenkozar ,

I collected all garbage so now the rebuild takes a while.  As soon as it's done, I'll create a gist with the results.  You ment adding "--debug" to the file __init__.py right? (not the nixops --debug switch)
Or do I need to do both?  Adding --debug to the nixops deploy call generates a huge XML file.

**Comment by domenkozar** [comment]
`nixops --debug` is what I meant.

**Comment by 4levels** [comment]
Hi Domen, I added --debug to the ssh call in the file mentioned before (the __ init __ script) with the default nixops (so not the updated version with your passAsFile addition):

```
building path(s) ‘/nix/store/bmaiaw7pxawc8ndq1k9c219ma3wqjdqy-nixos-system-secure-16.09pre-git’
while setting up the build environment: executing ‘/nix/store/gabjbkwga2dhhp2wzyaxl83r8hjjfc37-bash-4.3-p48/bin/bash’: Argument list too long
builder for ‘/nix/store/61jrly4lw1yfxbyp8cvhvwaachbdnmzq-nixos-system-secure-16.09pre-git.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/c2va29jcnaja43g534kd7n56hqhsdlfr-nixops-machines.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/c2va29jcnaja43g534kd7n56hqhsdlfr-nixops-machines.drv’ failed
Traceback (most recent call last):
  File "/nix/store/pw63rhnxibm3n4wdvkyzla20n8ydjlbs-nixops-1.5/bin/..nixops-wrapped-wrapped", line 951, in <module>
    args.op()
  File "/nix/store/pw63rhnxibm3n4wdvkyzla20n8ydjlbs-nixops-1.5/bin/..nixops-wrapped-wrapped", line 379, in op_deploy
    repair=args.repair, dry_activate=args.dry_activate)
  File "/nix/store/pw63rhnxibm3n4wdvkyzla20n8ydjlbs-nixops-1.5/lib/python2.7/site-packages/nixops/deployment.py", line 989, in deploy
    self._deploy(**kwargs)
  File "/nix/store/pw63rhnxibm3n4wdvkyzla20n8ydjlbs-nixops-1.5/lib/python2.7/site-packages/nixops/deployment.py", line 957, in _deploy
    self.configs_path = self.build_configs(repair=repair, include=include, exclude=exclude)
  File "/nix/store/pw63rhnxibm3n4wdvkyzla20n8ydjlbs-nixops-1.5/lib/python2.7/site-packages/nixops/deployment.py", line 633, in build_configs
    raise Exception("unable to build all machine configurations")
Exception: unable to build all machine configurations
```

I'll add the output of the other calls in separate comments below

**Comment by domenkozar** [comment]
I meant that you test with `passAsFile` change since that fixes the first bug :)

**Comment by 4levels** [comment]
This is the output of the nixops deploy call with the passAsFile additions and the extra --debug in the __ init __.py script in nixops/backends

```
secure........> copying closure...
Traceback (most recent call last):
  File "/nix/store/v5wgxmfhawxq725ny2fx2hrh4z3yhd6i-nixops-1.5pre0_abcdef/bin/..nixops-wrapped-wrapped", line 951, in <module>
    args.op()
  File "/nix/store/v5wgxmfhawxq725ny2fx2hrh4z3yhd6i-nixops-1.5pre0_abcdef/bin/..nixops-wrapped-wrapped", line 379, in op_deploy
    repair=args.repair, dry_activate=args.dry_activate)
  File "/nix/store/v5wgxmfhawxq725ny2fx2hrh4z3yhd6i-nixops-1.5pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 989, in deploy
    self._deploy(**kwargs)
  File "/nix/store/v5wgxmfhawxq725ny2fx2hrh4z3yhd6i-nixops-1.5pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 964, in _deploy
    max_concurrent_copy=max_concurrent_copy)
  File "/nix/store/v5wgxmfhawxq725ny2fx2hrh4z3yhd6i-nixops-1.5pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 656, in copy_closures
    tasks=self.active.itervalues(), worker_fun=worker)
  File "/nix/store/v5wgxmfhawxq725ny2fx2hrh4z3yhd6i-nixops-1.5pre0_abcdef/lib/python2.7/site-packages/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/nix/store/v5wgxmfhawxq725ny2fx2hrh4z3yhd6i-nixops-1.5pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 652, in worker
    m.copy_closure_to(m.new_toplevel)
  File "/nix/store/v5wgxmfhawxq725ny2fx2hrh4z3yhd6i-nixops-1.5pre0_abcdef/lib/python2.7/site-packages/nixops/backends/__init__.py", line 336, in copy_closure_to
    ssh.run_command("nix-store -j 4 -r --debug --ignore-unknown " + ' '.join(closure), check=False)
  File "/nix/store/v5wgxmfhawxq725ny2fx2hrh4z3yhd6i-nixops-1.5pre0_abcdef/lib/python2.7/site-packages/nixops/ssh_util.py", line 286, in run_command
    return nixops.util.logged_exec(cmd, self._logger, **kwargs)
  File "/nix/store/v5wgxmfhawxq725ny2fx2hrh4z3yhd6i-nixops-1.5pre0_abcdef/lib/python2.7/site-packages/nixops/util.py", line 76, in logged_exec
    stderr=subprocess.STDOUT)
  File "/nix/store/acsc2d6r6x6z9cdnks4ff5n0n84sw96z-python-2.7.13/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/nix/store/acsc2d6r6x6z9cdnks4ff5n0n84sw96z-python-2.7.13/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
```

**Comment by 4levels** [comment]
If I could only figure out how to rewrite this line:

```
ssh.run_command("nix-store -j 4 -r --debug --ignore-unknown " + ' '.join(closure), check=False)
```

to use a file containing the joined closures...

**Comment by 4levels** [comment]
Maybe we should move this issue to the NixOps repo instead?  Its's getting quite long already, what do you suggest?

**Comment by domenkozar** [comment]
You can workaround this by setting `deployment.hasFastConnection = true` in nixops expression

**Comment by 4levels** [comment]
OMG! THAT WORKS!

**Comment by 4levels** [comment]
@domenkozar, it seems like the change in the nixpkgs repo (with the passAsFile statements isn't even required.  I did adjust the nixops repo with the change from @dezgeg and that seems to be sufficient.

This means I can use the official nixpkgs repo and only need to patch the nixops repo.

The change as proposed by @dezgeg seems to work the magic!

Thanks for your kind support and for bearing here with me!

Kind regards,

Erik

**Comment by domenkozar** [comment]
@dezgeg @4levels can you make a PR for the fix?

**Comment by 4levels** [comment]
Hi @domenkozar,

All credit goes to @dezgeg so I consider it not fair creating a PR with his code change..
I don't mind if he agrees, I consider it an honor to have my first PR in a Nix repo ;-)

Kind regards,

Erik

**Comment by wmertens** [comment]
@4levels since https://github.com/NixOS/nixops/pull/915 was merged, I presume this can be closed?
