### ISSUE TITLE
Bazarr doesn't start: no module named 'pkgs_resources'

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#251588]
### Describe the bug

Bazarr doesn't start.

### Steps To Reproduce
1. `nix run 'nixpkgs/nixos-unstable#bazarr'

### Expected behavior

Bazarr starts and work

### Stacktrace

```
Bazarr starting...
Traceback (most recent call last):
  File "/nix/store/70bbkyb1lm2sgqaz3b2r6wwz6ny4h619-bazarr-1.2.4/share/bazarr/bazarr/main.py", line 20, in <module>
    from app.check_update import apply_update, check_releases, check_if_new_update  # noqa E402
  File "/nix/store/70bbkyb1lm2sgqaz3b2r6wwz6ny4h619-bazarr-1.2.4/share/bazarr/bazarr/app/check_update.py", line 14, in <module>
    from .config import settings
  File "/nix/store/70bbkyb1lm2sgqaz3b2r6wwz6ny4h619-bazarr-1.2.4/share/bazarr/bazarr/app/config.py", line 8, in <module>
    from subliminal.cache import region
  File "/nix/store/70bbkyb1lm2sgqaz3b2r6wwz6ny4h619-bazarr-1.2.4/share/bazarr/bazarr/../libs/subliminal/__init__.py", line 12, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/nix/store/70bbkyb1lm2sgqaz3b2r6wwz6ny4h619-bazarr-1.2.4/share/bazarr/bazarr/../libs/subliminal/core.py", line 29, in <module>
    from babelfish import Language, LanguageReverseError
  File "/nix/store/70bbkyb1lm2sgqaz3b2r6wwz6ny4h619-bazarr-1.2.4/share/bazarr/bazarr/../libs/babelfish/__init__.py", line 14, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/nix/store/70bbkyb1lm2sgqaz3b2r6wwz6ny4h619-bazarr-1.2.4/share/bazarr/bazarr/../libs/babelfish/converters/__init__.py", line 5, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
ModuleNotFoundError: No module named 'pkg_resources'
Bazarr exited.
```

### Notify maintainers

@d-xo

**Comment by yannick-mayeur** [comment]
While you wait that the PR is merged you can add this overlay to fix the issue:
```
  nixpkgs.overlays = [
    (final: prev: {
      bazarr = prev.bazarr.overrideAttrs (old: {
        buildInputs = [
          (prev.python3.withPackages (ps: [ ps.lxml ps.numpy ps.gevent ps.gevent-websocket ps.pillow ps.setuptools ]))
        ] ++ [ prev.ffmpeg prev.unar ];
      });
    })
  ];
```

I wanted to come up with a way to merge in the old buildInputs and only add setuptools but I wasn't able to come up with a way. If someone has an better solution I am eager to learn how to do it.
