### ISSUE TITLE
google-cloud-sdk-gce: install fails on python38 not supported by numpy

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#252234]
### Describe the bug
google-cloud-sdk-gce uses python38 which is no longer supported by numpy. Switching to python39 fixes the error.

### Steps To Reproduce
```
$ nix-shell -p google-cloud-sdk-gce
...
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 22, in <module>
    raise RuntimeError("Python version >= 3.9 required.")
RuntimeError: Python version >= 3.9 required.
/nix/store/1qxkj91n172qnypdrqdybh4p203nax7g-stdenv-linux/setup: line 1596: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/lwn29l6b0jbkhwnan3qqqdz21p2rqaq7-python3.8-numpy-1.25.1.drv' failed with exit code 1;
       last 10 log lines:
       > no configure script, doing nothing
       > building
       > Executing setuptoolsBuildPhase
       > Traceback (most recent call last):
       >   File "nix_run_setup", line 8, in <module>
       >     exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
       >   File "setup.py", line 22, in <module>
       >     raise RuntimeError("Python version >= 3.9 required.")
       > RuntimeError: Python version >= 3.9 required.
       > /nix/store/1qxkj91n172qnypdrqdybh4p203nax7g-stdenv-linux/setup: line 1596: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/lwn29l6b0jbkhwnan3qqqdz21p2rqaq7-python3.8-numpy-1.25.1.drv'.
```
```
$ nix-shell -p '(google-cloud-sdk-gce.override {python = python39;})'
# succeeds
```

### Notify maintainers
@iammrinal0 
@pradyuman 
@stephenmw 
@zimbatm

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.47, NixOS, 23.11 (Tapir), 23.11pre519597.a999c1cc0c9e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by natsukium** [comment]
Why are you using python 3.8? The default python version is 3.10 and will be going up to 3.11 in the near future.
The error log says that numpy does not support python 3.8 anymore.

**Comment by alexvorobiev** [comment]
@natsukium I am not using it. Here is how this is defined (https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L8721). This is precisely why I opened this issue.
```
 google-cloud-sdk-gce = google-cloud-sdk.override {
    python = python38;
    with-gce = true;
  };
```

**Comment by natsukium** [comment]
It looks like https://github.com/NixOS/nixpkgs/pull/135505 pinned the python version, but we no longer need to do that.
