### ISSUE TITLE
gns3-server Docker resources missing execute permission

### ISSUE THREAD

**Issue by g00pix** [NixOS/nixpkgs#252569]
### Describe the bug
gns3 with Docker is currently broken on 23.05. Starting any Docker appliance fail with the following error:

Docker has returned an error: 400 failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/gns3/init.sh": permission denied: unknown

In the gns3-server package there is a folder mounted to every Docker container started with gns3 to provide init scripts. For some reason, the scripts are missing the execute permission.

The files that miss the flag are in
- `$out/lib/python3.10/site-packages/gns3server/compute/docker/resources`
- `$out/lib/python3.10/site-packages/gns3server/compute/docker/resources/bin`

### Steps To Reproduce
1. Open GNS3
2. In the preferences, add a Docker appliance with the `alpine` image for example
3. Drag the appliance in the project
4. Start the appliance

### Expected behavior
The Docker appliances should start normally.

### Notify maintainers
@anthonyroussel 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.37, NixOS, 23.05 (Stoat), 23.05.20230703.aed4b19`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by g00pix** [comment]
I could provide a patch that runs the correct chmod but I'm not sure it's the correct fix as I don't understand how this issue was introduced.

**Comment by anthonyroussel** [comment]
Hello @g00pix 

Thanks for reporting this issue.
I will try to take a look at this issue during the weekend.

**Comment by pmanolak** [comment]
I am facing something similar to that issue, but here I cannot start any container with an error message "No busybox executable could be found" and after checking the above I found that my folder "/usr/lib/python3.10/site-packages/gns3server/compute/docker/resources" is totally empty!!! 
Is this expected when no container run, or this is the route cause of the error message I see? If yes, how can I put back the needed contents of that folder?

**Comment by auspham** [comment]
Having this same issue here, looks like asyncio does not have permission to execute docker?


```
2025-04-12 19:29:47 ERROR route.py:221 Node error detected: DockerError
Traceback (most recent call last):
  File "/nix/store/wfv9m3vbysd032lhxs60wb96mp8wq1zq-gns3-server-2.2.50/lib/python3.12/site-packages/gns3server/compute/docker/docker_vm.py", line 602, in _fix_permissions
    process = await asyncio.subprocess.create_subprocess_exec(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/dzi9r3xn0ny4l4gwnyqpncljq40pdk6f-python3-3.12.8/lib/python3.12/asyncio/subprocess.py", line 224, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/dzi9r3xn0ny4l4gwnyqpncljq40pdk6f-python3-3.12.8/lib/python3.12/asyncio/base_events.py", line 1749, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/dzi9r3xn0ny4l4gwnyqpncljq40pdk6f-python3-3.12.8/lib/python3.12/asyncio/unix_events.py", line 211, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/dzi9r3xn0ny4l4gwnyqpncljq40pdk6f-python3-3.12.8/lib/python3.12/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/nix/store/dzi9r3xn0ny4l4gwnyqpncljq40pdk6f-python3-3.12.8/lib/python3.12/asyncio/unix_events.py", line 820, in _start
    self._proc = subprocess.Popen(
                 ^^^^^^^^^^^^^^^^^
  File "/nix/store/dzi9r3xn0ny4l4gwnyqpncljq40pdk6f-python3-3.12.8/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/dzi9r3xn0ny4l4gwnyqpncljq40pdk6f-python3-3.12.8/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/wfv9m3vbysd032lhxs60wb96mp8wq1zq-gns3-server-2.2.50/lib/python3.12/site-packages/gns3server/web/route.py", line 200, in control_schema
    await func(request, response)
  File "/nix/store/wfv9m3vbysd032lhxs60wb96mp8wq1zq-gns3-server-2.2.50/lib/python3.12/site-packages/gns3server/handlers/api/compute/docker_handler.py", line 107, in stop
    await container.stop()
  File "/nix/store/wfv9m3vbysd032lhxs60wb96mp8wq1zq-gns3-server-2.2.50/lib/python3.12/site-packages/gns3server/compute/docker/docker_vm.py", line 834, in stop
    await self._fix_permissions()
  File "/nix/store/wfv9m3vbysd032lhxs60wb96mp8wq1zq-gns3-server-2.2.50/lib/python3.12/site-packages/gns3server/compute/docker/docker_vm.py", line 618, in _fix_permissions
    raise DockerError("Could not fix permissions for {}: {}".format(volume, e))
```

**Comment by auspham** [comment]
i was able to fix by adding pkgs.docker to path

```
systemd.services.gns3-server.path = [pkgs.docker]
```

not the most elegant way but works so far.
