### ISSUE TITLE
ModuleNotFoundError when running semanage from selinux-python

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#252620]
### Describe the bug
`semanage` from `selinux-python` fails to start with:
```
Traceback (most recent call last):
  File "/nix/store/bacdh74yaadq3far3s65376p60lwzk1z-selinux-python-3.3/bin/.semanage-wrapped", line 30, in <module>
    import seobject
  File "/nix/store/bacdh74yaadq3far3s65376p60lwzk1z-selinux-python-3.3/lib/python3.10/site-packages/seobject.py", line 31, in <module>
    from semanage import *
ModuleNotFoundError: No module named 'semanage'
```

### Steps To Reproduce
1. install `selinux-python`
2. run `semanage`

### Expected behavior
`semanage` runs

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.42-hardened1, NixOS, 23.05 (Stoat), 23.05.20230813.9049721`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.15.1`
 - channels(corin): `"nixos"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by codeiimon** [comment]
Were you able to get this fixed?

**Comment by lunik1** [comment]
I didn't, just gave up on selinux :/

**Comment by codeiimon** [comment]
> I didn't, just gave up on selinux :/

😢

**Comment by Magnie** [comment]
Found this while trying to solve an issue with the same error message because it was failing my Ansible scripts. Installing `python3-libsemanage` worked for me on AlmaLinux 9. It looks like `libsemanage` is available for [NixOS](https://search.nixos.org/packages?channel=24.05&show=libsemanage&from=0&size=50&sort=relevance&type=packages&query=libsemanage) and it says one of the outputs is `py`? Maybe that'll work?
