### ISSUE TITLE
Jekyll package broken, also wont build from ruby gems

### ISSUE THREAD

**Issue by johnramsden** [NixOS/nixpkgs#25282]
## Issue description

**Package:** nixos.jekyll, jekyll-3.0.1

The jekyll packages broken currently on nixos, and to make matters worse i can't build it using ruby gems either. 

### Steps to reproduce

After installing it from nix and attempting to run it I get the error:

```
jekyll build                                    john@atom
Configuration file: /home/john/Workspace/Blog/ramsdenj.com/_config.yml
/nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- jekyll-redirect-from (LoadError)
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `each'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `require_gems'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /nix/store/i665j98js86xgdf0a9i5p8p5rmzh254i-jekyll-3.0.1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
        from /run/current-system/sw/bin/jekyll:18:in `load'
        from /run/current-system/sw/bin/jekyll:18:in `<main>'
```

When I do attempt to install it from ruby gems I get a build problem saying I'm missing zlib. I tried installing it but continue to get the error.

## Technical details

* System: (NixOS: 17.03.928.69d9061908 (Gorilla))
* Nix version: (nix-env (Nix) 1.11.8)
* Nixpkgs version: ("17.03.928.69d9061908")

**Comment by srhb** [comment]
I cannot reproduce this error with a minimal jekyll site example and the same version of nixpkgs. Can you?

**Comment by johnramsden** [comment]
@srhb Well I tried setting up a brand new jekyll site and it **did** work. 

---

I think maybe the problem is that I'm using the github-pages gem. I tried building though and ran into another Ruby error: 

```
gem install github-pages                        john@atom
Building native extensions.  This could take a while...
ERROR:  Error installing github-pages:
        ERROR: Failed to build gem native extension.

    current directory: /home/john/.gem/ruby/2.3.0/gems/ffi-1.9.18/ext/ffi_c
/nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/bin/ruby -r ./siteconf20170428-27606-1rb9kgl.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:587:in `try_cpp'
        from /nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
        from /nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from /nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from /nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from /nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from /nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from /nix/store/nmwczzzdhk1lzi1ldxr0ivy13yrm1a5h-ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
        from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/john/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.18/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/john/.gem/ruby/2.3.0/gems/ffi-1.9.18 for inspection.
Results logged to /home/john/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.18/gem_make.out

```
