### ISSUE TITLE
flyway: Broken since 9.18.0

### ISSUE THREAD

**Issue by kai-tub** [NixOS/nixpkgs#252926]
### Describe the bug
The application `flyway` has been broken since version 9.21.0.
The previous and last working version was 9.18.0 (d457cf2601d73dbfb047e874221d76cbb74f43ab).

### Steps To Reproduce

Simply call `flyway --version`, and you will be greeted with the error message: `java.lang.NoClassDefFoundError`.

For the current version (9.21.2) run:

`nix-shell -p flyway -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz --command "flyway --version"`

Full output:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/Versioned
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.flywaydb.commandline.Main.main(Main.java:107)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.Versioned
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more
```

### Expected behavior
To get the correct version output of `flyway`

### Notify maintainers

@cmcdragonkai

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.12, NixOS, 23.11 (Tapir), 23.11.20230827.cddebdb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by kai-tub** [comment]
@marsam Thank you for the extremely quick response! :o 
Sorry that I didn't catch that a couple of files weren't correctly copied :facepalm: 
Do you have a buymeacoffe link or similar? :hugs:
