### ISSUE TITLE
ansible-lint: ModuleNotFoundError: No module named 'ruamel.yaml'  when run

### ISSUE THREAD

**Issue by ssmendon** [NixOS/nixpkgs#252984]
### Describe the bug
Running ansible-lint fails with a ModuleNotFoundError for ruamel.yaml when using nixos-unstable. 

### Steps To Reproduce
The minimal example for reproducing this seems to be:
```
[user@system:~]$ nix-shell --pure -p ansible-lint --run ansible-lint
Traceback (most recent call last):
  File "/nix/store/r5vgxn8y82zxhqz9mzgkncg10g9gax6h-ansible-lint-6.18.0/bin/.ansible-lint-wrapped", line 6, in <module>
    from ansiblelint.__main__ import _run_cli_entrypoint
  File "/nix/store/r5vgxn8y82zxhqz9mzgkncg10g9gax6h-ansible-lint-6.18.0/lib/python3.10/site-packages/ansiblelint/__main__.py", line 39, in <module>
    from ansiblelint import cli
  File "/nix/store/r5vgxn8y82zxhqz9mzgkncg10g9gax6h-ansible-lint-6.18.0/lib/python3.10/site-packages/ansiblelint/cli.py", line 29, in <module>
    from ansiblelint.yaml_utils import clean_json
  File "/nix/store/r5vgxn8y82zxhqz9mzgkncg10g9gax6h-ansible-lint-6.18.0/lib/python3.10/site-packages/ansiblelint/yaml_utils.py", line 15, in <module>
    import ruamel.yaml.events
ModuleNotFoundError: No module named 'ruamel.yaml'
```

### Expected behavior
The program should not fail with a ModuleNotFound exception.

### Notify maintainers

@sengaya

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0, NixOS, 23.11 (Tapir), 23.11pre521245.aa8aa7e2ea35`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by badele** [comment]
Hi, i have same issue with the nixos-unstable-20230614, i updated to nixos-unstable-20230908, it's seem work like a charm 

`> nix-info -m`
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.51, NixOS, 23.11 (Tapir), 23.11.20230908.db9208a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(badele): `"nixpkgs"`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/home/badele/.nix-defexpr/channels/nixpkgs`
 ```

`> ansible-lint /tmp/test.yaml`
```
WARNING  Listing 1 violation(s) that are fatal
yaml[line-length]: Line too long (184 > 160 characters)
/tmp/test.yaml:21

Read documentation for instructions on how to ignore specific rule violations.

                Rule Violation Summary
 count tag               profile rule associated tags
     1 yaml[line-length] basic   formatting, yaml

Failed: 1 failure(s), 0 warning(s) on 1 files. Last profile that met the validation criteria was 'min'.
A new release of ansible-lint is available: 6.18.0 → 6.19.0
```

**Comment by sengaya** [comment]
Would you mind to test again with ansible-lint 6.19.0 which was merged earlier today?

**Comment by ssmendon** [comment]
ansible-lint 6.19.0 looks good to me, on 20230917.970a59b.
