### ISSUE TITLE
Build failure: neovim on arm

### ISSUE THREAD

**Issue by RyanGibb** [NixOS/nixpkgs#253450]
### Steps To Reproduce

- `nix build github:nixos/nixpkgs/31f39945d3#legacyPackages.x86_64-linux.pkgsCross.remarkable2.neovim`
- or `nix build github:nixos/nixpkgs/31f39945d3#legacyPackages.x86_64-linux.pkgsCross.armv7-hf-multiplatform.neovim`

### Build log

```
$ nix build github:nixos/nixpkgs/31f39945d3#legacyPackages.x86_64-linux.pkgsCross.remarkable2.neovim
error: builder for '/nix/store/frk2xmxg59cs1ny3rabfklddqwq5nyx4-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf.drv' failed with exit code 1;
       last 10 log lines:
       >  from extconf.rb:3:in `<main>'
       >
       > To see why this extension failed to compile, please check the mkmf.log which can be found here:
       >
       >   /nix/store/klh6ssghc5fqbwhg0j65pwddc5bnrlan-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/msgpack-1.5.1/mkmf.log
       >
       > extconf failed, exit code 1
       >
       > Gem files will remain installed in /nix/store/klh6ssghc5fqbwhg0j65pwddc5bnrlan-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf/lib/ruby/gems/3.1.0/gems/msgpack-1.5.1 for inspection.
       > Results logged to /nix/store/klh6ssghc5fqbwhg0j65pwddc5bnrlan-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/msgpack-1.5.1/gem_make.out
       For full logs, run 'nix log /nix/store/frk2xmxg59cs1ny3rabfklddqwq5nyx4-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf.drv'.
error: 1 dependencies of derivation '/nix/store/sf3yfnfqa3lrkpfxi0jj9jcfhnfs8v4y-neovim-ruby-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mai1dmlvjnwh6gl83rjxzsrsd6v0m5hk-neovim-0.9.1.drv' failed to build
```

```
nix log /nix/store/frk2xmxg59cs1ny3rabfklddqwq5nyx4-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "installPhase" }
installing
buildFlags:
WARNING:  You build with buildroot.
  Build root: /
  Bin dir: /nix/store/klh6ssghc5fqbwhg0j65pwddc5bnrlan-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf>
  Gem home: /nix/store/klh6ssghc5fqbwhg0j65pwddc5bnrlan-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabih>
  Plugins dir: /nix/store/klh6ssghc5fqbwhg0j65pwddc5bnrlan-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnuea>
Building native extensions. This could take a while...
ERROR:  Error installing /nix/store/k1998ssx9acqbvg5nxsglz97v4kk5qk2-msgpack-1.5.1.gem:
        ERROR: Failed to build gem native extension.

    current directory: /nix/store/klh6ssghc5fqbwhg0j65pwddc5bnrlan-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-lin>
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/bin/ruby extconf.rb
checking for ruby/st.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/bin/$(RUBY_BASE_NAME)
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/lib
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:490:in `try_do': The compiler failed to generate an executable>
You have to install development tools first.
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:616:in `block in try_compile'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:565:in `with_werror'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:616:in `try_compile'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:1157:in `block in have_header'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:989:in `block in checking_for'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:354:in `block (2 levels) in postpone'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:324:in `open'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:354:in `block in postpone'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:324:in `open'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:350:in `postpone'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:988:in `checking_for'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:1156:in `have_header'
        from extconf.rb:3:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

lines 34-66
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/bin/$(RUBY_BASE_NAME)
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/lib
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:490:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:616:in `block in try_compile'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:565:in `with_werror'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:616:in `try_compile'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:1157:in `block in have_header'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:989:in `block in checking_for'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:354:in `block (2 levels) in postpone'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:324:in `open'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:354:in `block in postpone'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:324:in `open'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:350:in `postpone'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:988:in `checking_for'
        from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib/ruby/3.1.0/mkmf.rb:1156:in `have_header'
        from extconf.rb:3:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /nix/store/klh6ssghc5fqbwhg0j65pwddc5bnrlan-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/msgpack-1.5.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /nix/store/klh6ssghc5fqbwhg0j65pwddc5bnrlan-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf/lib/ruby/gems/3.1.0/gems/msgpack-1.5.1 for inspection.
Results logged to /nix/store/klh6ssghc5fqbwhg0j65pwddc5bnrlan-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/msgpack-1.5.1/gem_make.out
```

```
$ cat /nix/store/klh6ssghc5fqbwhg0j65pwddc5bnrlan-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/msgpack-1.5.1/mkmf.log
LD_LIBRARY_PATH=.:/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib "armv7l-unknown-linux-gnueabihf-gcc -o conftest -I/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/x86_64-linux -I/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/backward -I/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0 -I.    -O3 -fPIC conftest.c  -L. -L/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib -Wl,-rpath,/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed     -Wl,-rpath,/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib -L/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib -lruby-3.1.4  -lm  -lc"
In file included from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/value.h:23,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/intern/class.h:24,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/anyargs.h:76,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/ruby.h:26,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby.h:38,
                 from conftest.c:1:
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/static_assert.h:51:46: error: static assertion failed: "sizeof_long: SIZEOF_LONG == sizeof(long)"
   51 | # define RBIMPL_STATIC_ASSERT0 __extension__ _Static_assert
      |                                              ^~~~~~~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/static_assert.h:70:5: note: in expansion of macro 'RBIMPL_STATIC_ASSERT0'
   70 |     RBIMPL_STATIC_ASSERT0(expr, # name ": " # expr)
      |     ^~~~~~~~~~~~~~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/value.h:129:1: note: in expansion of macro 'RBIMPL_STATIC_ASSERT'
  129 | RBIMPL_STATIC_ASSERT(sizeof_long, SIZEOF_LONG == sizeof(long));
      | ^~~~~~~~~~~~~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/static_assert.h:51:46: error: static assertion failed: "sizeof_voidp: SIZEOF_VOIDP == sizeof(void *)"
   51 | # define RBIMPL_STATIC_ASSERT0 __extension__ _Static_assert
      |                                              ^~~~~~~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/static_assert.h:70:5: note: in expansion of macro 'RBIMPL_STATIC_ASSERT0'
   70 |     RBIMPL_STATIC_ASSERT0(expr, # name ": " # expr)
      |     ^~~~~~~~~~~~~~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/value.h:131:1: note: in expansion of macro 'RBIMPL_STATIC_ASSERT'
  131 | RBIMPL_STATIC_ASSERT(sizeof_voidp, SIZEOF_VOIDP == sizeof(void *));
      | ^~~~~~~~~~~~~~~~~~~~
In file included from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/arithmetic/st_data_t.h:31,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/arithmetic.h:36,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/ruby.h:27:
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/st.h:58:14: error: size of array 'st_check_for_sizeof_st_index_t' is negative
   58 | typedef char st_check_for_sizeof_st_index_t[SIZEOF_VOIDP == (int)sizeof(st_index_t) ? 1 : -1];
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/config.h:22,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/ruby.h:15:
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/memory.h: In function 'rb_mul_size_overflow':
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/x86_64-linux/ruby/config.h:222:28: error: '__int128' is not supported on this target
  222 | #define uint128_t unsigned __int128
      |                            ^~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/memory.h:92:18: note: in expansion of macro 'uint128_t'
   92 | # define DSIZE_T uint128_t
      |                  ^~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/memory.h:528:23: note: in expansion of macro 'DSIZE_T'
  528 |     RB_GNUC_EXTENSION DSIZE_T da, db, c2;
      |                       ^~~~~~~
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

### Additional context

I'm not sure how to go about debugging this yet. I'm not too familiar with Nixpkgs cross compilation and I can only find one reference to `pkgsCross` in the Nixpkgs manual. It would be good to see if this cross-compiles without ruby support but I can't find an easy way of disabling it https://github.com/NixOS/nixpkgs/blob/da5adce0ffaff10f6d0fee72a02a5ed9d01b52fc/pkgs/applications/editors/neovim/utils.nix#L29

### Notify maintainers

@tadfisher @siraben @nickhu

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.10, NixOS, 23.05 (Stoat)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-21.11"`
 - channels(ryan): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by RyanGibb** [comment]
For `armv7-hf-multiplatform`:
```
$ cat /nix/store/5qamsfsv5jcvpqcs6ab647pl2k3bp9y1-ruby-armv7l-unknown-linux-gnueabihf3.1.4-msgpack-1.5.1-armv7l-unknown-linux-gnueabihf/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/msgpack-1.5.1/mkmf.log
LD_LIBRARY_PATH=.:/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib "armv7l-unknown-linux-gnueabihf-gcc -o conftest -I/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/x86_64-linux -I/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/backward -I/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0 -I.    -O3 -fPIC conftest.c  -L. -L/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib -Wl,-rpath,/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed     -Wl,-rpath,/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib -L/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/lib -lruby-3.1.4  -lm  -lc"
In file included from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/value.h:23,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/intern/class.h:24,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/anyargs.h:76,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/ruby.h:26,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby.h:38,
                 from conftest.c:1:
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/static_assert.h:51:46: error: static assertion failed: "sizeof_long: SIZEOF_LONG == sizeof(long)"
   51 | # define RBIMPL_STATIC_ASSERT0 __extension__ _Static_assert
      |                                              ^~~~~~~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/static_assert.h:70:5: note: in expansion of macro 'RBIMPL_STATIC_ASSERT0'
   70 |     RBIMPL_STATIC_ASSERT0(expr, # name ": " # expr)
      |     ^~~~~~~~~~~~~~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/value.h:129:1: note: in expansion of macro 'RBIMPL_STATIC_ASSERT'
  129 | RBIMPL_STATIC_ASSERT(sizeof_long, SIZEOF_LONG == sizeof(long));
      | ^~~~~~~~~~~~~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/static_assert.h:51:46: error: static assertion failed: "sizeof_voidp: SIZEOF_VOIDP == sizeof(void *)"
   51 | # define RBIMPL_STATIC_ASSERT0 __extension__ _Static_assert
      |                                              ^~~~~~~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/static_assert.h:70:5: note: in expansion of macro 'RBIMPL_STATIC_ASSERT0'
   70 |     RBIMPL_STATIC_ASSERT0(expr, # name ": " # expr)
      |     ^~~~~~~~~~~~~~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/value.h:131:1: note: in expansion of macro 'RBIMPL_STATIC_ASSERT'
  131 | RBIMPL_STATIC_ASSERT(sizeof_voidp, SIZEOF_VOIDP == sizeof(void *));
      | ^~~~~~~~~~~~~~~~~~~~
In file included from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/arithmetic/st_data_t.h:31,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/arithmetic.h:36,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/ruby.h:27:
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/st.h:58:14: error: size of array 'st_check_for_sizeof_st_index_t' is negative
   58 | typedef char st_check_for_sizeof_st_index_t[SIZEOF_VOIDP == (int)sizeof(st_index_t) ? 1 : -1];
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/config.h:22,
                 from /nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/ruby.h:15:
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/memory.h: In function 'rb_mul_size_overflow':
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/x86_64-linux/ruby/config.h:222:28: error: '__int128' is not supported on this target
  222 | #define uint128_t unsigned __int128
      |                            ^~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/memory.h:92:18: note: in expansion of macro 'uint128_t'
   92 | # define DSIZE_T uint128_t
      |                  ^~~~~~~~~
/nix/store/6iynbmq1yzx4ywicizda4g3q3fhmdf2k-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/memory.h:528:23: note: in expansion of macro 'DSIZE_T'
  528 |     RB_GNUC_EXTENSION DSIZE_T da, db, c2;
      |                       ^~~~~~~
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

**Comment by teto** [comment]
Please comment on https://github.com/NixOS/nixpkgs/pull/245477

**Comment by onny** [comment]
Cross compilation also fails on riscv64

```
       > created 12 symlinks in user environment
       > /build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 2: /nix/store/3n8nfwbyk04vpqqlfxr3ham654hwdn99-ruby-riscv64-unknown-linux-gnu-3.1.5/bin/ruby: cannot execute binary file: Exec format error
```
