### ISSUE TITLE
Build failure: bazel-watcher

### ISSUE THREAD

**Issue by kyleconroy** [NixOS/nixpkgs#253706]
### Steps To Reproduce

1. `nix-build -A bazel-watcher`

### Build log

https://gist.github.com/kyleconroy/ff7de358868ddc33e4803392c8f947d4

### Additional context

The builds are also failing on Hydra

- https://hydra.nixos.org/job/nixpkgs/trunk/bazel-watcher.aarch64-darwin
- https://hydra.nixos.org/job/nixpkgs/trunk/bazel-watcher.x86_64-darwin

### Notify maintainers

@kalbasit 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
warning: ignoring untrusted substituter 'https://devenv.cachix.org', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/x51zvbgb5ymr7bmpcc34x3rh7v949f4l-nix-info
copying path '/nix/store/x51zvbgb5ymr7bmpcc34x3rh7v949f4l-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.6.0, macOS 13.5.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by kolloch** [comment]
Several errors like this locally and in https://hydra.nixos.org/build/245701308/nixlog/7:

```
ERROR: An error occurred during the fetch of repository 'com_github_mattn_go_shellwords':
   Traceback (most recent call last):
        File "/private/tmp/nix-build-bazel-watcher-0.23.1-deps.tar.gz.drv-0/output/external/bazel_gazelle/internal/go_repository.bzl", line 247, column 17, in _go_repository_impl
                fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_mattn_go_shellwords: fetch_repo: github.com/mattn/go-shellwords@v1.0.10: GOPROXY list is not the empty string, but contains no entries
ERROR: /private/tmp/nix-build-bazel-watcher-0.23.1-deps.tar.gz.drv-0/source/WORKSPACE:78:16: fetching go_repository rule //external:com_github_mattn_go_shellwords: Traceback (most recent call last):
        File "/private/tmp/nix-build-bazel-watcher-0.23.1-deps.tar.gz.drv-0/output/external/bazel_gazelle/internal/go_repository.bzl", line 247, column 17, in _go_repository_impl
                fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_mattn_go_shellwords: fetch_repo: github.com/mattn/go-shellwords@v1.0.10: GOPROXY list is not the empty string, but contains no entries
ERROR: /private/tmp/nix-build-bazel-watcher-0.23.1-deps.tar.gz.drv-0/source/internal/ibazel/lifecycle_hooks/BUILD:3:11: no such package '@com_github_mattn_go_shellwords//': failed to fetch com_github_mattn_go_shellwords: fetch_repo: github.com/mattn/go-shellwords@v1.0.10: GOPROXY list is not the empty string, but contains no entries
 and referenced by '//internal/ibazel/lifecycle_hooks:lifecycle_hooks'
ERROR: /private/tmp/nix-build-bazel-watcher-0.23.1-deps.tar.gz.drv-0/source/internal/ibazel/live_reload/BUILD:3:11: no such package '@com_github_jaschaephraim_lrserver//': failed to fetch com_github_jaschaephraim_lrserver: fetch_repo: github.com/jaschaephraim/lrserver@v0.0.0-20171129202958-50d19f603f71: GOPROXY list is not the empty string, but contains no entries
 and referenced by '//internal/ibazel/live_reload:live_reload'
ERROR: /private/tmp/nix-build-bazel-watcher-0.23.1-deps.tar.gz.drv-0/source/internal/ibazel/fswatcher/fsnotify/BUILD:17:11: no such package '@com_github_fsnotify_fsnotify//': failed to fetch com_github_fsnotify_fsnotify: fetch_repo: github.com/fsnotify/fsnotify@v1.5.4: GOPROXY list is not the empty string, but contains no entries
 and referenced by '//internal/ibazel/fswatcher/fsnotify:fsnotify'
```

**Comment by kolloch** [comment]
`GOPROXY` is not set on the system outside the nix-shell and also does not seem to be set when the bazel command is executed within the nix-build.

On the same system, with bazelisk, `bazel-watcher` version 0.23.1 builds from source: `bazelisk build //cli/ibazel`

**Comment by kolloch** [comment]
merge 8c7c922cc7ae240219da83b8cf4a90fa468ff761 introduced a build failure (found via git bisect) which merged this change:

https://github.com/NixOS/nixpkgs/commit/0d8594ef0dea6a07e03c8b37f0d71ea3490ac991

Reverting it on master makes it work but also reverts bazel-watcher to an older version.

Maybe [divanorama](https://github.com/NixOS/nixpkgs/commits?author=divanorama) can help out fixing it...

**Comment by kolloch** [comment]
The `fetchAttrs.sha256` makes it hard to bisect since it will "hide" all fetch affecting changes behind that cached results. Long live fixed output derivations!

**Comment by kolloch** [comment]
I was wrong. The fetchAttrs.sha256 hid that it was, in fact, broken before https://github.com/NixOS/nixpkgs/commit/8c7c922cc7ae240219da83b8cf4a90fa468ff761/https://github.com/NixOS/nixpkgs/pull/231839

```console
$ git checkout  8c7c922^

**Comment by kolloch** [comment]
I bisected this to the following commit: 1bb67a90bad7

with this bisect script:

```
#!/usr/bin/env bash

set -euf -o pipefail

set -x

git checkout -- pkgs/development/tools/bazel-watcher/

{ 
    nix build -L --impure --expr 'let pkgs = import ./.{}; in pkgs.bazel-watcher.deps.overrideAttrs (x: y: { outputHash="";}) ' 2>&1 \
    || true; 
} | tee build.log
cp build.log ..

if grep -q -e 'error: hash mismatch in fixed-output derivation.*bazel-watcher-.*-deps.tar.gz.drv'"'"':' build.log; then
    echo "SUCCESS: fixed-output derivation mismatch for dependencies -- fetching dependencies worked."
    exit 0
fi

if grep -q -e 'error: builder for .*bazel-watcher-.*-deps.tar.gz.drv'"'"' failed' build.log; then
    echo "FAILURE"
    exit 1
fi

echo "SKIP"
exit 125
```

Unfortunately, it is a huge merge.

**Comment by kolloch** [comment]
Okay fetching broke when go was unpinned: dc6ea0a4f702a

**Comment by kolloch** [comment]
Maybe related to https://github.com/golang/go/issues/61928

**Comment by kolloch** [comment]
@kalbasit : Could you maybe merge  #279898? It would be appreciated.
