### ISSUE TITLE
meson: build fails with python 3.12

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#253751]
### Describe the bug

> error: builder for '/nix/store/mk0py0cfw91phxhihpfgana0pjmqhzpw-meson-1.2.0.drv' failed with exit code 8;

<details>
  <summary>See log</summary>
 
  
  ```
...
Executing subproject bar 

Project name: bar
Project version: undefined
C++ compiler for the host machine: g++ (gcc 12.3.0 "g++ (GCC) 12.3.0")
C++ linker for the host machine: g++ ld.bfd 2.40
C++ compiler for the build machine: g++ (gcc 12.3.0 "g++ (GCC) 12.3.0")
C++ linker for the build machine: g++ ld.bfd 2.40
Could not introspect Python (['/nix/store/q5fi2vmnii9vjpqynp56vp0734yhpaig-python3-3.12.0b4/bin/python3', '/build/source/mesonbuild/scripts/python_info.py']): exit code 1
Program stdout:


Program stderr:

Traceback (most recent call last):
  File "/build/source/mesonbuild/scripts/python_info.py", line 16, in <module>
    import distutils.command.install
ModuleNotFoundError: No module named 'distutils'


test cases/python/6 failing subproject/subprojects/bar/meson.build:3:26: Exception: <PythonExternalProgram 'python3' -> ['/nix/store/q5fi2vmnii9vjpqynp56vp0734yhpaig-python3-3.12.0b4/bin/python3']> is not a valid python or it is missing distutils

Subproject subprojects/bar is buildable: NO (disabling)
Dependency bar from subproject bar found: NO (subproject failed to configure)
Could not introspect Python (['/nix/store/q5fi2vmnii9vjpqynp56vp0734yhpaig-python3-3.12.0b4/bin/python3', '/build/source/mesonbuild/scripts/python_info.py']): exit code 1
Program stdout:


Program stderr:

Traceback (most recent call last):
  File "/build/source/mesonbuild/scripts/python_info.py", line 16, in <module>
    import distutils.command.install
ModuleNotFoundError: No module named 'distutils'


test cases/python/6 failing subproject/meson.build:5:26: ERROR: <PythonExternalProgram 'python3' -> ['/nix/store/q5fi2vmnii9vjpqynp56vp0734yhpaig-python3-3.12.0b4/bin/python3']> is not a valid python or it is missing distutils
 

Traceback (most recent call last):
  File "/build/source/run_tests.py", line 315, in run_configure_inprocess
    returncode = mesonmain.run(commandlist, get_meson_script())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/mesonmain.py", line 285, in run
    return CommandLineParser().run(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/mesonmain.py", line 196, in run
    return errorhandler(e, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/mesonmain.py", line 40, in errorhandler
    raise e
  File "/build/source/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/msetup.py", line 358, in run
    app.generate()
  File "/build/source/mesonbuild/msetup.py", line 183, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/msetup.py", line 228, in _generate
    intr.run()
  File "/build/source/mesonbuild/interpreter/interpreter.py", line 2997, in run
    super().run()
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 164, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 198, in evaluate_statement
    self.assignment(cur)
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 635, in assignment
    value = self.evaluate_statement(node.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.method_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 535, in method_call
    obj = self.evaluate_statement(invocable)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.method_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 550, in method_call
    res = obj.method_call(method_name, args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreter/interpreterobjects.py", line 814, in method_call
    ret = method(state, args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/decorators.py", line 109, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/decorators.py", line 596, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/modules/python.py", line 437, in find_installation
    python = self._find_installation_impl(state, display_name, name_or_path, required)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/modules/python.py", line 398, in _find_installation_impl
    raise mesonlib.MesonException(sanitymsg)
mesonbuild.utils.core.MesonException: <PythonExternalProgram 'python3' -> ['/nix/store/q5fi2vmnii9vjpqynp56vp0734yhpaig-python3-3.12.0b4/bin/python3']> is not a valid python or it is missing distutils
 


====================================== python: 7 install path ======================================
 

(inprocess) $ setup --prefix /usr --libdir lib 'test cases/python/7 install path' '/build/source/b 87a5fe311e' --backend=ninja
Build started at 2023-09-07T00:26:10.979266
Main binary: /nix/store/q5fi2vmnii9vjpqynp56vp0734yhpaig-python3-3.12.0b4/bin/python
Build Options: -Dprefix=/usr -Dlibdir=lib -Dbackend=ninja
Python system: Linux
The Meson build system
Version: 1.2.0
Source dir: /build/source/test cases/python/7 install path
Build dir: /build/source/b 87a5fe311e
Build type: native build
Project name: install path
Project version: undefined
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Could not introspect Python (['/nix/store/q5fi2vmnii9vjpqynp56vp0734yhpaig-python3-3.12.0b4/bin/python', '/build/source/mesonbuild/scripts/python_info.py']): exit code 1
Program stdout:


Program stderr:

Traceback (most recent call last):
  File "/build/source/mesonbuild/scripts/python_info.py", line 16, in <module>
    import distutils.command.install
ModuleNotFoundError: No module named 'distutils'


test cases/python/7 install path/meson.build:9:22: ERROR: <PythonExternalProgram 'python3' -> ['/nix/store/q5fi2vmnii9vjpqynp56vp0734yhpaig-python3-3.12.0b4/bin/python']> is not a valid python or it is missing distutils
 

Traceback (most recent call last):
  File "/build/source/run_tests.py", line 315, in run_configure_inprocess
    returncode = mesonmain.run(commandlist, get_meson_script())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/mesonmain.py", line 285, in run
    return CommandLineParser().run(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/mesonmain.py", line 196, in run
    return errorhandler(e, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/mesonmain.py", line 40, in errorhandler
    raise e
  File "/build/source/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/msetup.py", line 358, in run
    app.generate()
  File "/build/source/mesonbuild/msetup.py", line 183, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/msetup.py", line 228, in _generate
    intr.run()
  File "/build/source/mesonbuild/interpreter/interpreter.py", line 2997, in run
    super().run()
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 164, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 198, in evaluate_statement
    self.assignment(cur)
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 635, in assignment
    value = self.evaluate_statement(node.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.method_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/interpreterbase.py", line 550, in method_call
    res = obj.method_call(method_name, args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreter/interpreterobjects.py", line 814, in method_call
    ret = method(state, args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/decorators.py", line 109, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/interpreterbase/decorators.py", line 596, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/modules/python.py", line 437, in find_installation
    python = self._find_installation_impl(state, display_name, name_or_path, required)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/modules/python.py", line 398, in _find_installation_impl
    raise mesonlib.MesonException(sanitymsg)
mesonbuild.utils.core.MesonException: <PythonExternalProgram 'python3' -> ['/nix/store/q5fi2vmnii9vjpqynp56vp0734yhpaig-python3-3.12.0b4/bin/python']> is not a valid python or it is missing distutils
  ```
  
</details>

### Steps To Reproduce
1. `nix-shell -I nixpkgs=./ -p python312Packages.meson`

### Expected behavior
build successful

### Additional context

the python 3.12 version of meson is not shown in the search. maybe this is known not to work. i don't see it marked as broken

https://search.nixos.org/packages?channel=unstable&show=python311Packages.meson&from=0&size=50&sort=relevance&type=packages&query=meson

### Notify maintainers

@AndersonTorres

### Metadata

nixpkgs @ 48992ab9b6173baa5a39f93d06c81f22c42920e8

 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.8, NixOS, 22.11 (Raccoon), 22.11.4588.93fddcf640c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ConnorBaker** [comment]
Maybe related: https://docs.python.org/3.12/whatsnew/3.12.html#distutils

**Comment by dnicolodi** [comment]
The released meson version depends on `distutils` which has been removed from Python 3.12. The next meson version will remove the dependency on `distutils`. `setuptools` embeds a copy of `distutils`, thus, until the next meson version is released, you may want to install `setuptools` on Python 3.12 to get the `distutils` module.

**Comment by haampie** [comment]
Installing `setuptools` is not enough, you have to import it too to let setuptools mess with `sys.path` s.t. `import disutils` works.

So, meson should import setuptools before importing disutils if distutils fails to import directly, and meson doesn't do this

**Comment by dnicolodi** [comment]
No, it is not necessary to import `setuptools`. `setuptools` have some magic (details provided on request) to inject its `distutils` copy in the Python path. The solution I proposed is tested. Do you have any evidence that it does not work?

**Comment by haampie** [comment]
I'm not an expert on how nix deals with python package installs, but the setuptools hack where `sys.path` is modified through 

```<setuptools prefix>/lib/pythonX.Y/site-packages/distutils-precedence.pth```

at startup only works when `setuptools prefix == python prefix`. That is, setuptools must be installed as a system site package.

That assumption may not hold in nix, it certainly does not in the Spack package manager which like nix also puts python packages in its own prefix, and make Python locate those through `PYTHONPATH`.

**Comment by AndersonTorres** [comment]
Should we wait the next release that fixes this?

**Comment by qedpi** [comment]
wondering if this is fixed yet?

**Comment by dwilliam62** [comment]
https://github.com/NixOS/nixpkgs/issues/253751

**Comment by jwillikers** [comment]
This has been fixed, right?

**Comment by voidus** [comment]
Works for me

**Comment by sylvorg** [comment]
> Works for me

Doesn't seem to work for me, unfortunately:

```
[0/1] Regenerating build files.
The Meson build system
Version: 1.6.0
Source dir: /build/source/test cases/common/273 both libraries
Build dir: /build/source/b 2e568769ad
Build type: native build
Project name: test both libraries
Project version: undefined
C compiler for the host machine: gcc (gcc 13.3.0 "gcc (GCC) 13.3.0")
C linker for the host machine: gcc ld.bfd 2.43.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 5

test both libraries undefined

  User defined options
    backend               : ninja
    default_both_libraries: shared
    default_library       : both
    libdir                : lib
    prefix                : /usr
    use_dep               : False

Found ninja-1.12.1 at /nix/store/10zc8k79ajzisvcngfljff4q1ck6r4s4-ninja-1.12.1/bin/ninja

ERROR: Clock skew detected. File /build/source/b 2e568769ad/../test cases/common/273 both libraries/meson.build has a time stamp 0.2770s in the future.

A full log can be found at /build/source/b 2e568769ad/meson-logs/meson-log.txt
FAILED: build.ninja
/nix/store/3alx4nrhy7ss32i6fmfgj0hp96pfjvx6-python3-3.11.11/bin/python /build/source/meson.py --internal regenerate '/build/source/test cases/common/273 both libraries' .


ninja explain: output build.ninja older than most recent input ../test cases/common/273 both libraries/meson.build (1739061568421619314 vs 1739061569071619326)
Traceback (most recent call last):
  File "/build/source/meson.py", line 27, in <module>
    sys.exit(mesonmain.main())
             ^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/mesonmain.py", line 293, in main
    return run(sys.argv[1:], launcher)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/mesonmain.py", line 279, in run
    return errorhandler(e, 'setup')
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/mesonmain.py", line 34, in errorhandler
    raise e
  File "/build/source/mesonbuild/mesonmain.py", line 277, in run
    return msetup.run(['--reconfigure'] + args[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/msetup.py", line 365, in run
    app.generate()
  File "/build/source/mesonbuild/msetup.py", line 188, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/msetup.py", line 253, in _generate
    captured_compile_args = intr.backend.generate(capture, vslite_ctx)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/backend/ninjabackend.py", line 682, in generate
    self.generate_ending()
  File "/build/source/mesonbuild/backend/ninjabackend.py", line 3752, in generate_ending
    deps = self.get_regen_filelist()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/mesonbuild/backend/backends.py", line 1371, in get_regen_filelist
    self.check_clock_skew(deps)
  File "/build/source/mesonbuild/backend/backends.py", line 1398, in check_clock_skew
    raise MesonException(f'Clock skew detected. File {absf} has a time stamp {delta:.4f}s in the future.')
mesonbuild.utils.core.MesonException: Clock skew detected. File /build/source/b 2e568769ad/../test cases/common/273 both libraries/meson.build has a time stamp 0.2770s in the future.
ninja: error: rebuilding 'build.ninja': subcommand failed



Total passed tests:  477
Total failed tests:  1
Total skipped tests: 102

All failures:
  -> common: 273 both libraries    (default_library=both default_both_libraries=shared use_dep=False)
  CC       libshadow_la-getdate.lo
In file included from sizeof.h:15,
                 from utmp.c:26:
must_be.h:53:17: warning: anonymous struct declared inside parameter list will not be visible outside of this definition or declaration
   53 |                 struct {                                                      \
      |                 ^~~~~~
must_be.h:96:31: note: in expansion of macro 'must_be'
   96 | #define must_be_array(a)      must_be(is_array(a))
      |                               ^~~~~~~
sizeof.h:20:43: note: in expansion of macro 'must_be_array'
   20 | #define SIZEOF_ARRAY(a)      (sizeof(a) + must_be_array(a))
      |                                           ^~~~~~~~~~~~~
sizeof.h:21:31: note: in expansion of macro 'SIZEOF_ARRAY'
   21 | #define NITEMS(a)            (SIZEOF_ARRAY((a)) / sizeof((a)[0]))
      |                               ^~~~~~~~~~~~
utmp.c:34:23: note: in expansion of macro 'NITEMS'
   34 | #define UTX_LINESIZE  NITEMS(memberof(struct utmpx, ut_line))
      |                       ^~~~~~
utmp.c:41:26: note: in expansion of macro 'UTX_LINESIZE'
   41 | is_my_tty(const char tty[UTX_LINESIZE])
      |                          ^~~~~~~~~~~~
```

**Comment by voidus** [comment]
I did try this on arch linux, so that might be an issue. Could you share the exact command you used, just so we're sure there's no misunderstanding about that?

**Comment by eli-schwartz** [comment]
> on `nixos-24.11` on WSL2

The error here was,

> ERROR: Clock skew detected. File /build/source/b 2e568769ad/../test cases/common/273 both libraries/meson.build has a time stamp 0.2770s in the future.

This is not an issue in the distribution packaging. Basically everyone packages meson for python 3.12 just fine, your system clock issues aren't an issue with meson's 3.12 support.

**Comment by sylvorg** [comment]
Got it. Do you have any advice on how to fix it? Perhaps add an overlay to touch all files before building the package?
