### ISSUE TITLE
certbot cannot import pkg_resources

### ISSUE THREAD

**Issue by con-f-use** [NixOS/nixpkgs#253850]
### Describe the bug
The [certbot](https://search.nixos.org/packages?channel=unstable&show=certbot&from=0&size=50&sort=relevance&type=packages&query=certbot) package seems to be missing a `propagatedBuildInput` and thus cannot import pkg-resources.

### Steps To Reproduce
```shell
$ nix-shell -p certbot --run 'certbot --help'
Traceback (most recent call last):
  File "/nix/store/flxx63jq4crx4wq38f93hjc5clkq8a91-python3.10-certbot-2.4.0/bin/.certbot-wrapped", line 6, in <module>
    from certbot.main import main
  File "/nix/store/flxx63jq4crx4wq38f93hjc5clkq8a91-python3.10-certbot-2.4.0/lib/python3.10/site-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/nix/store/flxx63jq4crx4wq38f93hjc5clkq8a91-python3.10-certbot-2.4.0/lib/python3.10/site-packages/certbot/_internal/main.py", line 28, in <module>
    from certbot import configuration
  File "/nix/store/flxx63jq4crx4wq38f93hjc5clkq8a91-python3.10-certbot-2.4.0/lib/python3.10/site-packages/certbot/configuration.py", line 11, in <module>
    from certbot import util
  File "/nix/store/flxx63jq4crx4wq38f93hjc5clkq8a91-python3.10-certbot-2.4.0/lib/python3.10/site-packages/certbot/util.py", line 26, in <module>
    from certbot._internal import constants
  File "/nix/store/flxx63jq4crx4wq38f93hjc5clkq8a91-python3.10-certbot-2.4.0/lib/python3.10/site-packages/certbot/_internal/constants.py", line 6, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

### Notify maintainers
@domenkozar 

### Metadata
```shell
$ nix-shell -p nix-info --run "nix-info -m" -I nixpkgs=/etc/nixpkgs
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.46, NixOS, 23.11 (Tapir), 23.11.20230904.3c15fee`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 ```
 Broken since at least `23.11.20230821.91a22f7`.

**Comment by con-f-use** [comment]
Closed by  #253857
