### ISSUE TITLE
Build failure: `pkgsCross.aarch64-multiplatform.klipper` fails when cross compiling on x86_64

### ISSUE THREAD

**Issue by cyber-murmel** [NixOS/nixpkgs#253914]
### Steps To Reproduce

1. Save as `default.nix`
```nix
{ pkgs ? import
    (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/da5adce.tar.gz")
    { }
}:

pkgs.pkgsCross.aarch64-multiplatform.klipper

```

2. run `nix-build`

#### Problem 1
```
building '/nix/store/ppyd9cxzg08wh0ybrccpirj4c842zcs7-klipper-aarch64-unknown-linux-gnu-unstable-2023-04-24.drv'...
unpacking sources
unpacking source archive /nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source
source root is source/klippy
patching sources
substituteStream(): WARNING: pattern '/usr/bin/env python2' doesn't match anything in file 'parsedump.py'
updateAutotoolsGnuConfigScriptsPhase
configuring
no configure script, doing nothing
building
no Makefile or custom buildPhase, doing nothing
sh: gcc: not found
ERROR:root:Unable to build C code module (error=32512)
Traceback (most recent call last):
  File "/build/source/klippy/./chelper/__init__.py", line 309, in <module>
    get_ffi()
  File "/build/source/klippy/./chelper/__init__.py", line 275, in get_ffi
    do_build_code(cmd % (destlib, ' '.join(srcfiles)))
  File "/build/source/klippy/./chelper/__init__.py", line 251, in do_build_code
    raise Exception(msg)
Exception: Unable to build C code module (error=32512)
/nix/store/8s2l5yq2zzqkrx1hd6883rzzl379q68r-stdenv-linux/setup: line 146: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/ppyd9cxzg08wh0ybrccpirj4c842zcs7-klipper-aarch64-unknown-linux-gnu-unstable-2023-04-24.drv' failed with exit code 1;
       last 10 log lines:
       > ERROR:root:Unable to build C code module (error=32512)
       > Traceback (most recent call last):
       >   File "/build/source/klippy/./chelper/__init__.py", line 309, in <module>
       >     get_ffi()
       >   File "/build/source/klippy/./chelper/__init__.py", line 275, in get_ffi
       >     do_build_code(cmd % (destlib, ' '.join(srcfiles)))
       >   File "/build/source/klippy/./chelper/__init__.py", line 251, in do_build_code
       >     raise Exception(msg)
       > Exception: Unable to build C code module (error=32512)
       > /nix/store/8s2l5yq2zzqkrx1hd6883rzzl379q68r-stdenv-linux/setup: line 146: pop_var_context: head of shell_variables not a function context
```

#### Problem 2

```
building '/nix/store/9j37l3b78div5qh009bnv7giif7idvfr-klipper-aarch64-unknown-linux-gnu-unstable-2023-04-24.drv'...
unpacking sources
unpacking source archive /nix/store/xc0cg69yq7r6kj2azwpnnqkqg0g3i0i9-source
source root is source/klippy
patching sources
substituteStream(): WARNING: pattern '/usr/bin/env python2' doesn't match anything in file 'parsedump.py'
updateAutotoolsGnuConfigScriptsPhase
configuring
no configure script, doing nothing
building
no Makefile or custom buildPhase, doing nothing
Traceback (most recent call last):
  File "/build/source/klippy/./chelper/__init__.py", line 309, in <module>
    get_ffi()
  File "/build/source/klippy/./chelper/__init__.py", line 279, in get_ffi
    FFI_lib = FFI_main.dlopen(destlib)
  File "/nix/store/p4lis1rahl48mvvvkhfm7yn7y0zi73ih-python3-aarch64-unknown-linux-gnu-3.10.12-env/lib/python3.10/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/nix/store/p4lis1rahl48mvvvkhfm7yn7y0zi73ih-python3-aarch64-unknown-linux-gnu-3.10.12-env/lib/python3.10/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/nix/store/p4lis1rahl48mvvvkhfm7yn7y0zi73ih-python3-aarch64-unknown-linux-gnu-3.10.12-env/lib/python3.10/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/build/source/klippy/chelper/c_helper.so': /build/source/klippy/chelper/c_helper.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/build/source/klippy/chelper/c_helper.so'
/nix/store/8s2l5yq2zzqkrx1hd6883rzzl379q68r-stdenv-linux/setup: line 146: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/9j37l3b78div5qh009bnv7giif7idvfr-klipper-aarch64-unknown-linux-gnu-unstable-2023-04-24.drv' failed with exit code 1;
       last 10 log lines:
       >   File "/build/source/klippy/./chelper/__init__.py", line 279, in get_ffi
       >     FFI_lib = FFI_main.dlopen(destlib)
       >   File "/nix/store/p4lis1rahl48mvvvkhfm7yn7y0zi73ih-python3-aarch64-unknown-linux-gnu-3.10.12-env/lib/python3.10/site-packages/cffi/api.py", line 150, in dlopen
       >     lib, function_cache = _make_ffi_library(self, name, flags)
       >   File "/nix/store/p4lis1rahl48mvvvkhfm7yn7y0zi73ih-python3-aarch64-unknown-linux-gnu-3.10.12-env/lib/python3.10/site-packages/cffi/api.py", line 832, in _make_ffi_library
       >     backendlib = _load_backend_lib(backend, libname, flags)
       >   File "/nix/store/p4lis1rahl48mvvvkhfm7yn7y0zi73ih-python3-aarch64-unknown-linux-gnu-3.10.12-env/lib/python3.10/site-packages/cffi/api.py", line 827, in _load_backend_lib
       >     raise OSError(msg)
       > OSError: cannot load library '/build/source/klippy/chelper/c_helper.so': /build/source/klippy/chelper/c_helper.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/build/source/klippy/chelper/c_helper.so'
       > /nix/store/8s2l5yq2zzqkrx1hd6883rzzl379q68r-stdenv-linux/setup: line 146: pop_var_context: head of shell_variables not a function context
```

### Additional context

The first problem arises due to missing `gcc`.
This can be fixed by adding `buildPackages.stdenv.cc` to the `nativeBuildInputs`.

```nix
...


pkgs.pkgsCross.aarch64-multiplatform.klipper.overrideAttrs(old: {
  nativeBuildInputs = old.nativeBuildInputs ++ (with pkgs; [
    buildPackages.stdenv.cc
  ]);
})
```

The second problem - I think - is caused by the binary being compiled for aarch64 and trying to be loaded on the x86 machine.

On workaround it to ignore the failing python script, since this successfully builds the `c_helper.so`, but fails at loading it.
```nix
...

pkgs.pkgsCross.aarch64-multiplatform.klipper.overrideAttrs(old: {
  nativeBuildInputs = old.nativeBuildInputs ++ (with pkgs; [
    buildPackages.stdenv.cc
  ]);
  postBuild = ''
    python ./chelper/__init__.py || true
  '';
})
```

A better approach might be to patch away the offending file when cross compiling or something.

### Notify maintainers

@lovesegfault 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.47, NixOS, 23.05 (Stoat), 23.05.3023.74e5bdc5478e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - channels(marble): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cyber-murmel** [comment]
Another approach might be just to build the `c_helper.so` with `gcc` and the same flags as in the `__init__.py`, not running the script at all.

**Comment by Artturin** [comment]
nativeBuildInputs should be depsBuildBuild in your fixes

**Comment by Artturin** [comment]
Assuming the code has to built for running during build, if not then gcc is hardcoded wrongly and the build script should be fixed.

**Comment by cyber-murmel** [comment]
I just noticed that this either way still compiles the file for `x86-64`
```shell
$ file result/lib/klipper/chelper/c_helper.so
result/lib/klipper/chelper/c_helper.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, with debug_info, not stripped
```

I'm a little out of my depth. How do I make it compile the binary for the target platform?

**Comment by Artturin** [comment]
Check edit

**Comment by cyber-murmel** [comment]
`${stdenv.cc.targetPrefix}` seems to resolve to an empty string.

**Comment by Artturin** [comment]
> `${stdenv.cc.targetPrefix}` seems to resolve to an empty string. looking at the patched sources, I can see that I can change the offending line in the source, but the targetPrefix variable seems empty

It's an empty string when not cross-compiling on purpose.

**Comment by cyber-murmel** [comment]
That fixed it!

I'm actually working on an RPi image.

```nix
  # cross compile
  nixpkgs.crossSystem = lib.systems.elaborate lib.systems.examples.aarch64-multiplatform;
  ...
  # fix klipper for cross compilation
  services.klipper = {
    ...
    package = pkgs.klipper.overrideAttrs(old: {
      postPatch = old.postPatch + ''
      substituteInPlace ./chelper/__init__.py \
        --replace "GCC_CMD = \"gcc\"" "GCC_CMD = \"${pkgs.stdenv.cc.targetPrefix}gcc\""
      '';
    });
  };
```

**Comment by Artturin** [comment]
You should create a PR
