### ISSUE TITLE
fetchYarnDeps doesn't support v2 (YAML) lockfiles

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#254369]
### Describe the bug
When trying to get `fetchYarnDeps` to consume the `yarn.lock` from Grafana (https://github.com/grafana/grafana/blob/main/yarn.lock), it dies with a parsing error:

```
SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile
    at Parser.unexpected (/nix/store/b1wnrddjgg85i1w4kzgsp8mksa344abx-prefetch-yarn-deps/libexec/yarnpkg-lockfile.js:5064:11)
    at Parser.parse (/nix/store/b1wnrddjgg85i1w4kzgsp8mksa344abx-prefetch-yarn-deps/libexec/yarnpkg-lockfile.js:5193:14)
    at parse (/nix/store/b1wnrddjgg85i1w4kzgsp8mksa344abx-prefetch-yarn-deps/libexec/yarnpkg-lockfile.js:5262:17)
    at module.exports.exports.default (/nix/store/b1wnrddjgg85i1w4kzgsp8mksa344abx-prefetch-yarn-deps/libexec/yarnpkg-lockfile.js:4835:96)
    at prefetchYarnDeps (/nix/store/b1wnrddjgg85i1w4kzgsp8mksa344abx-prefetch-yarn-deps/libexec/index.js:133:28)
    at main (/nix/store/b1wnrddjgg85i1w4kzgsp8mksa344abx-prefetch-yarn-deps/libexec/index.js:187:9)
```

I suspect that this is because it's a new-style yarn.lock file using the YAML syntax, and not the old "custom" syntax. The yarnpkg-lockfile npm package can't parse it for that reason.

### Notify maintainers

cc @lilyinstarlight (not technically maintainer I think, but you touched it last :p)

**Comment by lilyinstarlight** [comment]
Our tooling still won't actually work with yarn-berry yet, even if it did parse the lockfile. I do want proper yarn-berry support soon though, given a lot of things are starting to use it now

> not technically maintainer I think, but you touched it last :p

No I'm not technically maintainer, but unless someone else steps up I'm probably going to be the one to add yarn-berry support to our tooling anyway 🙈

**Comment by delroth** [comment]
Yeah, I hacked around to add YAML parsing support and found out that there's (unsurprisingly) a lot more things to fix, and I'm very out of my depth with 0 knowledge of that ecosystem unfortunately :) Thank you!

**Comment by ashkitten** [comment]
i looked into this more with some digging into the yarn codebase and it seems like we've got a few issues:
- newer yarn has a `resolution` key instead of a URL, in the format of `name@protocol:version`, (ex. `@aashutoshrathi/word-wrap@npm:1.2.6`) so we have to construct the URL to download ourselves
- checksums are now hex encoded and based on, from what i could tell, a zipfile of the actual files on disk. what confuses me is that the zipfile compression seems to be configurable, which i can only assume will interfere with the hashes...

this is possible to fix but imo the better solution would be to find some way to use yarn cli to do the actual fetching and validation because this is much more complicated

**Comment by ashkitten** [comment]
UPDATE: the checksum thing is ridiculous. i did some testing and yes, changing the compression ratio in the yarn config will change the hashes of every single lockfile entry, or fail if --immutable is passed.

the default compress ratio is 0, so it's not like this will always break...

i'm leaning towards just running `yarn install --immutable --mode skip-scripts` instead of reimplementing their own logic but worse. i'm not entirely sure why we don't always just do that, i think it's probably because we operate off of only the lockfile and yarn itself requires the presence of a package.json as well.

**Comment by dotlambda** [comment]
> i'm not entirely sure why we don't always just do that

We need to use a format that's guaranteed to be stable across different versions of Yarn.

**Comment by ShamrockLee** [comment]
If `builtins.fromYaml` (NixOS/nix#4910) gets merged, would it be possible to use the hashes from `yarn.lock` directly and get rid of other sort of vendor hashs?

**Comment by Atemu** [comment]
I don't see us using `fromYAML` any time soon even if it was merged tomorrow because it'd break eval with old versions of Nix.

**Comment by ShamrockLee** [comment]
> I don't see us using `fromYAML` any time soon even if it was merged tomorrow because it'd break eval with old versions of Nix.

Not sure about the process to determine when to use a built-in function, but it's sensible to wait at least until the stable branch-off after it hits Nixpkgs.

https://discourse.nixos.org/t/when-is-a-nix-builtin-function-builtins-considered-ready-to-be-used-inside-nixpkgs/35369/2

**Comment by eclairevoyant** [comment]
There's a sizable chunk of users still on nix 2.3. I don't see a good reason to break eval for them.

**Comment by szlend** [comment]
This might not check off all the stability requirements for `nixpkgs`, but if you need to package something for personal use, you can do something like this:

<details>
  <summary>Expand source</summary>

```nix
{ fetchFromGitHub
, stdenvNoCC
, yarn-berry
, nodejs
, cacert
}:

stdenvNoCC.mkDerivation (finalAttrs: {
  pname = "spectral";
  version = "6.11.1";

  src = fetchFromGitHub {
    owner = "stoplightio";
    repo = "spectral";
    rev = "v${finalAttrs.version}";
    sha256 = "sha256-ivuu7kpVJIn2RiFAe/slMffcisVeq7yeG1TwoXMOMeA=";
  };

  nativeBuildInputs = [ yarn-berry nodejs ];

  yarnOfflineCache = stdenvNoCC.mkDerivation {
    name = "spectral-deps";
    nativeBuildInputs = [ yarn-berry ];
    inherit (finalAttrs) src;

    NODE_EXTRA_CA_CERTS = "${cacert}/etc/ssl/certs/ca-bundle.crt";

    buildPhase = ''
      mkdir -p $out

      export HOME="$NIX_BUILD_TOP"
      export YARN_ENABLE_TELEMETRY=0
      export YARN_COMPRESSION_LEVEL=mixed

      yarn config set enableGlobalCache false
      yarn config set cacheFolder $out
      yarn install --immutable --mode skip-build
    '';

    dontInstall = true;

    outputHashAlgo = "sha256";
    outputHash = "sha256-GMoou1AXIm6zRu0bCOFwvr9OXqtVu2w7jdOhLi1P3uI=";
    outputHashMode = "recursive";
  };

  configurePhase = ''
    runHook preConfigure

    export HOME="$NIX_BUILD_TOP"
    export YARN_ENABLE_TELEMETRY=0
    export YARN_COMPRESSION_LEVEL=mixed

    yarn config set enableGlobalCache false
    yarn config set cacheFolder $yarnOfflineCache

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild

    yarn install --immutable --immutable-cache
    yarn build
    yarn workspaces focus --all --production

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/{bin,lib}

    cp -r node_modules $out/lib/

    for package in packages/*; do
      mkdir -p $out/lib/$package
      cp -r $package/{dist,package.json} $out/lib/$package/
    done

    ln -s $out/lib/node_modules/.bin/spectral $out/bin/spectral

    runHook postInstall
  '';

  fixupPhase = ''
    runHook preFixup

    patchShebangs $out/lib

    runHook postFixup
  '';

  doInstallCheck = true;
  installCheckPhase = ''
    $out/bin/spectral --version
  '';
})

```

</details>

**Comment by dotlambda** [comment]
@delroth Why was this closed?

**Comment by szlend** [comment]
Still an issue.

Turns out you can make the deps reproducible by predefining the list of supported architecture like so:
```
supportedArchitectures = builtins.toJSON {
  os = [ "darwin" "linux" ];
  cpu = [ "arm" "arm64" "ia32" "x64" ];
  libc = [ "glibc" "musl" ];
};

configurePhase = ''
  # ...
  yarn config set supportedArchitectures --json "$supportedArchitectures"
'';
```

**Comment by gador** [comment]
I faced the same issue when `pgadmin4` decided to switch to `v2` versions of `yarn.lock`. The hacky way I circumvented the issue for `nixpkgs`  was to use the `yarn-lock-converter` https://github.com/VHT/yarn-lock-converter in my update script to convert the newer v2 to v1. https://github.com/NixOS/nixpkgs/blob/343b0a2225308ff6b8f2a1638f8664bc4bc7037b/pkgs/tools/admin/pgadmin/update.sh#L57 This way I converted the yarn file for the newer version. The problem here is

>The modern yarn lockfile does not contain the registry metadata needed to fill in hte yarn v1 resolved and integrity fields, nor does yarn store this in the local cache. To fill in these fields, this package needs to make HTTPS requests to the npm registry.

So it won't work in builders with no internet connection. 
@szlend wouldn't it be possible to implement a `v2` version of `yarnOfflineCache` as you did in your example and use it for projects which utilize `v2` lockfiles and leave the older `yarnOfflineCache` for the existing v1 versions?

This way newer projects could use the newer `yarn.lock` files while older projects (and their derivations) won't break?

**Comment by szlend** [comment]
@gador I think we should just copy what we did for pnpm in #290715. I just don't have all that much interest in this platform to do it myself.

**Comment by gador** [comment]
@szlend thanks for the pointer. I'm not to familiar with the whole javascript ecosystem and its unclear to me what you mean with "just copy what we did for pnpm".. Doesn't this PR just use the `package.json` ? How would we apply this to yarn and the problem with a new version of `yarn.lock`? Or do you propose we use an upstream `package.json` file instead of a `yarn.lock`?

**Comment by szlend** [comment]
See my comment https://github.com/NixOS/nixpkgs/issues/254369#issuecomment-2080460150 for how to build a yarn berry application. It splits the build into two stages/derivations:

1. Fetch the yarn deps with a Nix fixed-output derivation. This allows using the network and the result is verified using a hash for reproducibility.
2. In a regular Nix offline build, configure Yarn to point at the deps and run a build

There's a big problem with this a approach though. If Yarn ever gets updated and ever so slightly changes how it generates the dependencies, then the fixed-output derivation suddenly becomes non-reproducible and fails the hash check. This may go unnoticed for a while because it's binary cached... until it's not.

The way this is handled in `pnpm.fetchDeps` #290715 is that it explicitly requires you to pick the version of pnpm to fetch the deps with (e.g. `pnpm_8`, `pnpm_9`). I would suggest taking the same approach when formalizing a solution for yarn berry.

**Comment by gador** [comment]
ah ok. So we would implement something along the lines of your example here (https://github.com/NixOS/nixpkgs/issues/254369#issuecomment-2080460150) and fix it with a certain `yarn` version, right?

As far as I understand it, yarn only uses either `v1` or `v2` lockfiles. So would it not be enough pass pass this as an argument and default to `v1`?

Also, we could implement an argument passed to the builder for the compression level. This way, if an upstream developer uses a different compression level by default, we could pass that along and default to `0` as it is the standard upstream

**Comment by szlend** [comment]
> As far as I understand it, yarn only uses either v1 or v2 lockfiles. So would it not be enough pass pass this as an argument and default to v1?

It's not just about lock files, but also the generated deps/cache directories. I'm not sure about the stability guarantees of yarn, but yarn berry is at [v4 now](https://github.com/yarnpkg/berry/releases). Btw yarn (v1) and yarn berry (v2) are distinct projects.

**Comment by euank** [comment]
Now that https://github.com/NixOS/nixpkgs/pull/399404 has landed, you can use `fetchYarnBerryDeps` instead for v2 lockfiles.
