### ISSUE TITLE
hedgedoc: sqlite3 backend is broken

### ISSUE THREAD

**Issue by malte-v** [NixOS/nixpkgs#254384]
### Describe the bug
When attempting to start hedgedoc with the sqlite3 backend, it exits with the following error message:
```
error: 	uncaughtException: Please install sqlite3 package manually
2023-09-10 13:24:57.592114602  Error: Please install sqlite3 package manually
2023-09-10 13:24:57.592118454      at ConnectionManager._loadDialectModule (/nix/store/cqv0pd3pbk2vzd2g6ki15gmqn7njiqmc-hedgedoc-1.9.9/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:88:15)
2023-09-10 13:24:57.592121862      at new ConnectionManager (/nix/store/cqv0pd3pbk2vzd2g6ki15gmqn7njiqmc-hedgedoc-1.9.9/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)
2023-09-10 13:24:57.592124751      at new SqliteDialect (/nix/store/cqv0pd3pbk2vzd2g6ki15gmqn7njiqmc-hedgedoc-1.9.9/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
2023-09-10 13:24:57.592127473      at new Sequelize (/nix/store/cqv0pd3pbk2vzd2g6ki15gmqn7njiqmc-hedgedoc-1.9.9/node_modules/sequelize/lib/sequelize.js:334:20)
2023-09-10 13:24:57.592130065      at Object.<anonymous> (/nix/store/cqv0pd3pbk2vzd2g6ki15gmqn7njiqmc-hedgedoc-1.9.9/lib/models/index.js:27:15)
2023-09-10 13:24:57.592132139      at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-09-10 13:24:57.592134232      at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2023-09-10 13:24:57.592136195      at Module.load (node:internal/modules/cjs/loader:1119:32)
2023-09-10 13:24:57.592138176      at Module._load (node:internal/modules/cjs/loader:960:12)
2023-09-10 13:24:57.592140176      at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-09-10 13:24:57.592142084      at require (node:internal/modules/cjs/helpers:121:18)
2023-09-10 13:24:57.592144398      at Object.<anonymous> (/nix/store/cqv0pd3pbk2vzd2g6ki15gmqn7njiqmc-hedgedoc-1.9.9/app.js:27:16)
2023-09-10 13:24:57.592146398      at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-09-10 13:24:57.592148435      at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2023-09-10 13:24:57.592150380      at Module.load (node:internal/modules/cjs/loader:1119:32)
2023-09-10 13:24:57.592152306      at Module._load (node:internal/modules/cjs/loader:960:12)
2023-09-10 13:24:57.592154528      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2023-09-10 13:24:57.592156343      at node:internal/main/run_main_module:23:47
```

### Steps To Reproduce
start hedgedoc with the sqlite3 backend configured

### Notify maintainers

@SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.93-0-rpi4, Alpine Linux, noversion, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```

**Comment by SuperSandro2000** [comment]
I am not planning to invest time into this right now. Feel free to provide a PR.
