### ISSUE TITLE
NixOS taskserver module broken in nixos-unstable

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#25529]
I have in `configuration.nix`:

    taskserver = {
      enable = true;
      fqdn = "taskserver.example.org";
      listenHost = "0.0.0.0";
      trust = "strict";
      organisations = {
        private = { groups = ["staff"]; users = ["peter"]; };
      };
    };

and that used to work fine in 2839b10 and before, but after updating to the current `nixos-unstable` at c5badb123a, the task server is broken:

~~~
# systemctl stop taskserver.service 
# systemctl start taskserver.service
Job for taskserver.service failed because the control process exited with error code.
See "systemctl status taskserver.service" and "journalctl -xe" for details.
# systemctl status taskserver.service
● taskserver.service - Taskwarrior Server
   Loaded: loaded (/nix/store/sjvqbh7l8za6gbg3bwmgz3vyv8whl9ns-unit-taskserver.service/taskserver.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2017-05-05 10:03:19 CEST; 2s ago
  Process: 2991 ExecStartPre=/nix/store/4b3i4nzqqgnqaslgky3g5pc12f6xx513-unit-script/bin/taskserver-pre-start (code=exited, status=1/FAILURE)
      CPU: 34ms

May 05 10:03:19 peti systemd[1]: taskserver.service: Unit entered failed state.
May 05 10:03:19 peti systemd[1]: taskserver.service: Failed with result 'exit-code'.
May 05 10:03:19 peti systemd[1]: taskserver.service: Service hold-off time over, scheduling restart.
May 05 10:03:19 peti systemd[1]: Stopped Taskwarrior Server.
May 05 10:03:19 peti systemd[1]: taskserver.service: Start request repeated too quickly.
May 05 10:03:19 peti systemd[1]: Failed to start Taskwarrior Server.
May 05 10:03:19 peti systemd[1]: taskserver.service: Unit entered failed state.
May 05 10:03:19 peti systemd[1]: taskserver.service: Failed with result 'exit-code'.
~~~

The journal says:

~~~
May 05 10:03:19 peti taskserver-pre-start[2991]: Traceback (most recent call last):
May 05 10:03:19 peti taskserver-pre-start[2991]:   File "/nix/store/ypqmj0d2zpvgl9c7229i4z9lra88qscq-nixos-taskserver/bin/.nixos-taskserver-wrapped", line 8, in <module>
May 05 10:03:19 peti taskserver-pre-start[2991]:     from main import cli
May 05 10:03:19 peti taskserver-pre-start[2991]:   File "/nix/store/ypqmj0d2zpvgl9c7229i4z9lra88qscq-nixos-taskserver/lib/python2.7/site-packages/main.py", line 16, in <module>
May 05 10:03:19 peti taskserver-pre-start[2991]:     IS_AUTO_CONFIG = true # NOQA
May 05 10:03:19 peti taskserver-pre-start[2991]: NameError: name 'true' is not defined
May 05 10:03:19 peti systemd[1]: taskserver.service: Control process exited, code=exited status=1
~~~

Ping @aszlig and @fpletz, who modified that module recently.

Personally, I assume 953616907493c5b81ba3ec9dd86f1422f4d1fcd3 and 3ab45f4b369c9c741b55ddedeaac4c797dc61c04 are to blame.

**Comment by joachifm** [comment]
Looks to me like the `boolToString` helper turned what was previously a Python bool literal into a variable lookup (`True` turned into `true`).
