### ISSUE TITLE
Impacket (mssqlclient.py): SSL routines - legacy sigalg disallowed or unsupported

### ISSUE THREAD

**Issue by Casul51** [NixOS/nixpkgs#255563]
### Describe the bug
Can't connect to MySQL machine with TLS encryption.

### Steps To Reproduce
1. Run TLS requered MySQL server (hackthebox's Archetype)
2. Try to connect using windows-auth `mssqlclient.py -windows-auth ARCHETYPE/sql_svc@10.129.130.206 -debug`
3. 

### Expected behavior
```
┌──(root㉿kali)-[/home/casual/impacket/examples]
└─# ./mssqlclient.py -windows-auth ARCHETYPE/sql_svc@10.129.130.206 -debug
Impacket v0.11.0 - Copyright 2023 Fortra

[+] Impacket Library Installation Path: /usr/lib/python3/dist-packages/impacket
Password:
[*] Encryption required, switching to TLS
[*] ENVCHANGE(DATABASE): Old Value: master, New Value: master
[*] ENVCHANGE(LANGUAGE): Old Value: , New Value: us_english
[*] ENVCHANGE(PACKETSIZE): Old Value: 4096, New Value: 16192
[*] INFO(ARCHETYPE): Line 1: Changed database context to 'master'.
[*] INFO(ARCHETYPE): Line 1: Changed language setting to us_english.
[*] ACK: Result: 1 - Microsoft SQL Server (140 3232)
[!] Press help for extra shell commands
SQL (ARCHETYPE\sql_svc  dbo@master)>

```

### Log
```
$ mssqlclient.py -windows-auth ARCHETYPE/sql_svc@10.129.130.206 -debug
Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

[+] Impacket Library Installation Path: /nix/store/9jy27cn2m5i2a5mjamrx3g2srkbn6nm7-python3.11-impacket-0.10.0/lib/python3.11/site-packages/impacket
Password:
[*] Encryption required, switching to TLS
[+] Exception:
Traceback (most recent call last):
  File "/nix/store/9jy27cn2m5i2a5mjamrx3g2srkbn6nm7-python3.11-impacket-0.10.0/bin/.mssqlclient.py-wrapped", line 176, in <module>
    res = ms_sql.login(options.db, username, password, domain, options.hashes, options.windows_auth)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9jy27cn2m5i2a5mjamrx3g2srkbn6nm7-python3.11-impacket-0.10.0/lib/python3.11/site-packages/impacket/tds.py", line 881, in login
    tls.do_handshake()
  File "/nix/store/8kzd3kwk7y5dh05i8vgfk77ay525j1g3-python3.11-pyopenssl-23.1.1/lib/python3.11/site-packages/OpenSSL/SSL.py", line 2074, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/nix/store/8kzd3kwk7y5dh05i8vgfk77ay525j1g3-python3.11-pyopenssl-23.1.1/lib/python3.11/site-packages/OpenSSL/SSL.py", line 1715, in _raise_ssl_error
    _openssl_assert(
  File "/nix/store/8kzd3kwk7y5dh05i8vgfk77ay525j1g3-python3.11-pyopenssl-23.1.1/lib/python3.11/site-packages/OpenSSL/_util.py", line 71, in openssl_assert
    exception_from_error_queue(error)
  File "/nix/store/8kzd3kwk7y5dh05i8vgfk77ay525j1g3-python3.11-pyopenssl-23.1.1/lib/python3.11/site-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', '', 'legacy sigalg disallowed or unsupported')]
[-] [('SSL routines', '', 'legacy sigalg disallowed or unsupported')]
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.2-zen1, NixOS, 23.11 (Tapir), 23.11.20230908.db9208a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos-23.05, nixpkgs"`
 - channels(casual): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by Mag1cByt3s** [comment]
Does the impacket package support passing an OpenSSL config via a --prefix parameter?

I fixed the openssl legacy ciphers issue for evil-winrm by creating an overlay that creates a wrapper around evil-winrm which exports the openssl config with legacy ciphers enabled using the OPENSSL_CONF env variable.

**Comment by Mag1cByt3s** [comment]
I just created an overlay for impacket to enable the OpenSSL legacy ciphers and also patch impacket to add dacledit.py

```nix
# impacket-overlay.nix
final: prev:
{
  python312 = prev.python312.override {
    packageOverrides = pyfinal: pyprev: {
      impacket-patched = pyprev.impacket.overrideAttrs (oldAttrs: rec {
        dacleditSrc = prev.fetchurl {
          url = "https://raw.githubusercontent.com/ShutdownRepo/impacket/04518279ef663e80195b61d4d864d6e9e8ac5d9f/examples/dacledit.py";
          sha256 = "sha256-24txUlNLSD7ZZs2VV77QgxBrRI/upeBtaWPAvXsoL0A="; # Replace with the correct SHA-256 hash
        };

        msadaGuidsSrc = prev.fetchurl {
          url = "https://raw.githubusercontent.com/ShutdownRepo/impacket/04518279ef663e80195b61d4d864d6e9e8ac5d9f/impacket/msada_guids.py";
          sha256 = "sha256-XAZUOjLi85e9iBYy9/pAkEd8Ks0xbQB7jU33YcHfsjY="; # Replace with the correct SHA-256 hash
        };

        # Add OpenSSL configuration
        openssl_conf = prev.writeText "openssl.conf" ''
          openssl_conf = openssl_init

          [openssl_init]
          providers = provider_sect

          [provider_sect]
          default = default_sect
          legacy = legacy_sect

          [default_sect]
          activate = 1

          [legacy_sect]
          activate = 1
        '';

        postInstall =
          (oldAttrs.postInstall or "")
          + ''
            cp ${dacleditSrc} $out/bin/dacledit.py
            chmod +x $out/bin/dacledit.py
            cp ${msadaGuidsSrc} $out/lib/python3.12/site-packages/impacket/msada_guids.py
          '';

        # Modify postFixup to include OpenSSL configuration
        postFixup = ''
          ${oldAttrs.postFixup or ""}
          wrapProgram $out/bin/mssqlclient.py \
            --prefix OPENSSL_CONF : ${openssl_conf}
        '';
      });
    };
  };
}
```
