### ISSUE TITLE
Build failure: azure-cli

### ISSUE THREAD

**Issue by flexwie** [NixOS/nixpkgs#256050]
### Steps To Reproduce

1. add `azure-cli` to your shell or home-manager configuration.
2. Build

### Build log

```
error: builder for '/nix/store/4lid9k6f945w6pqkqa4fzag6yr98j6hi-python3.10-fabric-3.0.0.drv' failed with exit code 1;
       last 10 log lines:
       >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
       >   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
       >   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
       >   File "/nix/store/pxz18izhy02l1hvkqy1pl8p0d3ini86h-python3.10-fabric-3.0.0/lib/python3.10/site-packages/fabric/__init__.py", line 3, in <module>
       >     from .connection import Config, Connection
       >   File "/nix/store/pxz18izhy02l1hvkqy1pl8p0d3ini86h-python3.10-fabric-3.0.0/lib/python3.10/site-packages/fabric/connection.py", line 9, in <module>
       >     from decorator import decorator
       > ModuleNotFoundError: No module named 'decorator'
```

### Additional context

I tried to install the `decorator` package in my shell but that didn't help. 

### Notify maintainers

@jonringer 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.0.0, macOS 14.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/flexwie/.nix-defexpr/channels/nixpkgs`
```

**Comment by kirillrdy** [comment]
@flexwie  greetings!

azure-cli builds for me on latest master 9b331a0ae55afbaeb3369d2e36c397b981c5ff28 and on nixpkgs-unstable ( tested on x86_64-linux )

can you try those, otherwise could be something darwin specifuc

**Comment by netthier** [comment]
Also experiencing this on unstable NixOS:
```
$ sudo nix-channel --list
home-manager https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz
nixos https://nixos.org/channels/nixos-unstable
nixos-unstable https://nixos.org/channels/nixos-unstable
$ sudo nix-channel --update
unpacking channels...
$ sudo nix-shell -p azure-cli
[...]
Check whether the following modules can be imported: fabric
pythonRemoveBinBytecodePhase
pythonImportsCheckPhase
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: azure.mgmt.maps
Traceback (most recent call last):
  File "/nix/store/14zdvn6s5qbgw4agza6a8sx4y4lfgbg1-python3.10-fabric-3.0.0/lib/python3.10/site-packages/fabric/connection.py", line 7, in <module>
    from invoke.vendor.decorator import decorator
ModuleNotFoundError: No module named 'invoke.vendor.decorator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/lx8vhp4fxclp494svlfis3sb2g8z4l9h-python3-3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/14zdvn6s5qbgw4agza6a8sx4y4lfgbg1-python3.10-fabric-3.0.0/lib/python3.10/site-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/nix/store/14zdvn6s5qbgw4agza6a8sx4y4lfgbg1-python3.10-fabric-3.0.0/lib/python3.10/site-packages/fabric/connection.py", line 9, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
error: builder for '/nix/store/17x6f4mz90hdj3gyhwy5q2i0qbs44rrw-python3.10-fabric-3.0.0.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/vsq7ia5gypjszndxlfgs4swv6c65sccr-python3.10-azure-cli-2.52.0.drv' failed to build
```

**Comment by flexwie** [comment]
Hey @kirillrdy, thanks for your fast reply!

Unstable is not building for me:

```
{ pkgs ? import <nixos-unstable> {} }:
pkgs.mkShell {
  buildInputs = [
    pkgs.azure-cli
  ];
}
```
where `nixos-unstable` is `https://nixos.org/channels/nixos-unstable`.

Using 9b331a0 works!

```
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/9b331a0ae55afbaeb3369d2e36c397b981c5ff28.tar.gz") {} }:
pkgs.mkShell {
  buildInputs = [
    pkgs.azure-cli
  ];
}
```
 
Is it something in my config? I just recently switched to nix and home-manager and am still trying to figure everything out.

**Comment by kirillrdy** [comment]
@flexwie fast moving world indeed !

if https://github.com/NixOS/nixpkgs/commit/9b331a0ae55afbaeb3369d2e36c397b981c5ff28 works then unstable should work as well

nixos-unstable is not same as nixpkgs-unstable ( there is a bit of a lag to get nixos tests passing )

there are a lot of new things so it's lots of things to learn, but welcome to the journey !

**Comment by flexwie** [comment]
I get the same error on `https://nixos.org/channels/nixpkgs-unstable`, is this still not the correct channel?

**Comment by mdarocha** [comment]
According to https://nixpk.gs/pr-tracker.html?pr=255669, the fix is not in `nixpkgs-unstable` yet

**Comment by flexwie** [comment]
That solves it for me. Thanks everyone for your help!
