### ISSUE TITLE
Android Studio Beta failed to start

### ISSUE THREAD

**Issue by Cryolitia** [NixOS/nixpkgs#256681]
### Describe the bug

I installed Android Studio Beta for the first time, but it failed to start.

### Steps To Reproduce
1. Add `androidStudioPackages.beta` into `environment.systemPackages`
2. `sudo nixos-rebuild boot --flake . -v -L`
3. Reboot system
4. Click `Android Studio (beta channel)` in menu

### Expected behavior

Android Studio to launch

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/23723294/be6bbd76-ebfb-4968-8ea6-cdb46cfee5f1)

### Additional context
```
Internal error. Please refer to https://code.google.com/p/android/issues

java.lang.NullPointerException
    at java.base/java.util.Objects.requireNonNull(Objects.java:209)
    at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
    at java.base/java.nio.file.Path.of(Path.java:147)
    at java.base/java.nio.file.Paths.get(Paths.java:69)
    at java.base/jdk.internal.platform.CgroupUtil.lambda$readStringValue$1(CgroupUtil.java:67)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
    at java.base/jdk.internal.platform.CgroupUtil.readStringValue(CgroupUtil.java:69)
    at java.base/jdk.internal.platform.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:65)
    at java.base/jdk.internal.platform.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:124)
    at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:190)
    at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:160)
    at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:85)
    at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getInstance(CgroupV1Subsystem.java:61)
    at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:121)
    at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:91)
    at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:183)
    at java.base/jdk.internal.platform.SystemMetrics.instance(SystemMetrics.java:29)
    at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:58)
    at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
    at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:183)
    at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:280)
    at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:199)
    at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(PlatformMBeanProvider.java:195)
    at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:687)
    at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:389)
    at com.android.tools.analytics.HostData$osBean$2.invoke(HostData.kt:31)
    at com.android.tools.analytics.HostData$osBean$2.invoke(HostData.kt:30)
    at com.android.tools.analytics.StubbableLazy.getValue(HostData.kt:83)
    at com.android.tools.analytics.StubbableLazy.getValue(HostData.kt:89)
    at com.android.tools.analytics.HostData.getOsBean(HostData.kt:30)
    at com.android.tools.idea.stats.AndroidStudioUsageTracker.getMachineDetails(AndroidStudioUsageTracker.kt:154)
    at com.android.tools.idea.stats.AndroidStudioUsageTracker.studioPing(AndroidStudioUsageTracker.kt:237)
    at com.android.tools.idea.stats.AndroidStudioUsageTracker.setup(AndroidStudioUsageTracker.kt:177)
    at com.android.tools.idea.startup.AndroidStudioInitializer.setupAnalytics(AndroidStudioInitializer.java:85)
    at com.android.tools.idea.startup.AndroidStudioInitializer.componentsInitialized(AndroidStudioInitializer.java:47)
    at com.intellij.ide.ApplicationInitializedListener.execute$suspendImpl(ApplicationInitializedListener.kt:22)
    at com.intellij.ide.ApplicationInitializedListener.execute(ApplicationInitializedListener.kt)
    at com.intellij.idea.ApplicationLoader$callAppInitialized$1.invokeSuspend(ApplicationLoader.kt:431)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

-----
Your JRE: 17.0.7+0-17.0.7b1000.6-10550314 amd64 (JetBrains s.r.o.)
/nix/store/px0my3cfcypd1i2l778pffxw99h787d1-android-studio-beta-2023.1.1.17-unwrapped/jbr
```

### Notify maintainers

@alapshin

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.3-zen1, NixOS, 23.11 (Tapir), 23.11.20230915.ace5093`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `not found`
```

**Comment by kirillrdy** [comment]
greetings,
unfortunately I am unable to reproduce the issue with neither beta or stable android studio

```
nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.54, NixOS, 23.11 (Tapir), 23.11.20230920.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(kirillvr): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

are you able to reproduce the issue in nixos-rebuild build-vm ?

**Comment by Cryolitia** [comment]
works today……so weird
