### ISSUE TITLE
tg v0.19 unable to run

### ISSUE THREAD

**Issue by flexwie** [NixOS/nixpkgs#256704]
### Describe the bug
tg failes to run once I entered my phone number.

Might be related to paul-nameless/tg#284 but I can't verify because tdlib v1.8.3 (611bf8f183e6360c2a215fa70dfd659943a9857f ) fails to build on aarch64 (#140751 related)

Installing the same version via home-brew works without issues.

### Steps To Reproduce
1. install tg
2. start and enter your phone number

### Expected behavior
tg should send and ask me for a code

### Additional context
Stacktrace:

```console
Traceback (most recent call last):
  File "/nix/store/vf9g738227b655ll9llda5zyfsj48yc9-tg-0.19.0/bin/.tg-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/vf9g738227b655ll9llda5zyfsj48yc9-tg-0.19.0/lib/python3.10/site-packages/tg/__main__.py", line 69, in main
    tg.login()
  File "/nix/store/scrq869jrzdrbfh5f35m3fhmchw5cq82-python3.10-python-telegram-0.15.0/lib/python3.10/site-packages/telegram/client.py", line 583, in login
    self.authorization_state = self._wait_authorization_result(result)
  File "/nix/store/scrq869jrzdrbfh5f35m3fhmchw5cq82-python3.10-python-telegram-0.15.0/lib/python3.10/site-packages/telegram/client.py", line 513, in _wait_authorization_result
    result.wait(raise_exc=True)
  File "/nix/store/scrq869jrzdrbfh5f35m3fhmchw5cq82-python3.10-python-telegram-0.15.0/lib/python3.10/site-packages/telegram/utils.py", line 45, in wait
    raise RuntimeError(f'Telegram error: {self.error_info}')
RuntimeError: Telegram error: {'@type': 'error', 'code': 400, 'message': 'Valid api_id must be provided. Can be obtained at https://my.telegram.org', '@extra': {'request_id': 'updateAuthorizationState'}
```

### Notify maintainers
@sikmir 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.0.0, macOS 14.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/flexwie/.nix-defexpr/channels/nixpkgs`
```

**Comment by flexwie** [comment]
works like a charm! thanks a lot :)
