### ISSUE TITLE
python36Packages.flake8 does not build

### ISSUE THREAD

**Issue by mythmon** [NixOS/nixpkgs#25678]
## Issue description

Flake8 with Python 3.6 fails to build with `AttributeError: 'Checker' object has no attribute 'JOINEDSTR'`

### Steps to reproduce

```
$ nix-shell -p python36Packages.flake8 --pure
```

```
these derivations will be built:
  /nix/store/9ssajjb3320b9xlafnr5yn98p9qgrqj7-python3.6-pyflakes-1.3.0.drv
  /nix/store/ad04p26yqzvrncqbs50z6k3fj4q7w3qr-python3.6-flake8-3.2.1.drv
building path(s) ‘/nix/store/jf12y2m6zav194pnfcg8izyispafw3pz-python3.6-pyflakes-1.3.0’
unpacking sources
unpacking source archive /nix/store/zrjhkrmxb5cqajni5ihcw014wgphma9x-pyflakes-1.3.0.tar.gz
source root is pyflakes-1.3.0
setting SOURCE_DATE_EPOCH to timestamp 1472760221 of file pyflakes-1.3.0/setup.cfg
patching sources
configuring
building

<...snip...>

======================================================================
ERROR: test_f_string (pyflakes.test.test_other.TestUnusedAssignment)
Test PEP 498 f-strings are treated as a usage.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-pyflakes-1.3.0.drv-0/pyflakes-1.3.0/pyflakes/test/test_other.py", line 1686, in test_f_string
    ''')
  File "/tmp/nix-build-python3.6-pyflakes-1.3.0.drv-0/pyflakes-1.3.0/pyflakes/test/harness.py", line 25, in flakes
    w = checker.Checker(tree, withDoctest=self.withDoctest, **kw)
  File "/tmp/nix-build-python3.6-pyflakes-1.3.0.drv-0/pyflakes-1.3.0/pyflakes/checker.py", line 494, in __init__
    self.handleChildren(tree)
  File "/tmp/nix-build-python3.6-pyflakes-1.3.0.drv-0/pyflakes-1.3.0/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/tmp/nix-build-python3.6-pyflakes-1.3.0.drv-0/pyflakes-1.3.0/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/tmp/nix-build-python3.6-pyflakes-1.3.0.drv-0/pyflakes-1.3.0/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/tmp/nix-build-python3.6-pyflakes-1.3.0.drv-0/pyflakes-1.3.0/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/tmp/nix-build-python3.6-pyflakes-1.3.0.drv-0/pyflakes-1.3.0/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/tmp/nix-build-python3.6-pyflakes-1.3.0.drv-0/pyflakes-1.3.0/pyflakes/checker.py", line 862, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/tmp/nix-build-python3.6-pyflakes-1.3.0.drv-0/pyflakes-1.3.0/pyflakes/checker.py", line 696, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'Checker' object has no attribute 'JOINEDSTR'

----------------------------------------------------------------------
Ran 602 tests in 0.838s

FAILED (errors=1, skipped=33)
builder for ‘/nix/store/9ssajjb3320b9xlafnr5yn98p9qgrqj7-python3.6-pyflakes-1.3.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/ad04p26yqzvrncqbs50z6k3fj4q7w3qr-python3.6-flake8-3.2.1.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/ad04p26yqzvrncqbs50z6k3fj4q7w3qr-python3.6-flake8-3.2.1.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies


```

## Technical details

* System: 17.09pre106916.c5badb123a (Hummingbird)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: 17.09pre106916.c5badb123a
* Sandboxing enabled: build-use-sandbox = false

**Comment by FRidh** [comment]
Try upgrading the pyflakes expression to the latest version

**Comment by mythmon** [comment]
I can produce this same problem using nixpkgs commit 0e93069c7f40c98cc41de32335846fc5a6eb79f6 (latest master as of this writing).
