### ISSUE TITLE
Build failure: surrealdb

### ISSUE THREAD

**Issue by BridgerB** [NixOS/nixpkgs#257539]
### Steps To Reproduce

1. Nixos with unstable.
2. Rebuild

### Build log

```
Compiling surrealdb v1.0.0 (/build/source/lib)
warning: unused import: `crate::key::debug`
  --> lib/src/kvs/tx.rs:10:5
   |
10 | use crate::key::debug;
   |     ^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `surrealdb` (lib) generated 1 warning (run `cargo fix --lib -p surrealdb` to apply 1 suggestion)
   Compiling surreal v1.0.0 (/build/source)
warning: `surrealdb` (lib) generated 1 warning (1 duplicate)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cargo-auditable/src/rustc_wrapper.rs:91:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `surreal` (bin "surreal")
warning: build failed, waiting for other jobs to finish...
error: builder for '/nix/store/wzrfhxg6b7pr3zj477sq61nnvsm43sr6-surrealdb-1.0.0.drv' failed with exit code 101
error: 1 dependencies of derivation '/nix/store/zy9051cihjbsvqpwpqcmz233s8nznszk-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0ppz8jzqi5fg2n70dfpbfym1fyr959q8-nixos-system-nixos-23.11pre527911.e35dcc04a3
```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.54, NixOS, 23.11 (Tapir), 23.11pre527911.e35dcc04a385`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FliegendeWurst** [comment]
Build works by now, but there's a test failure:

```
test ws_integration::live_live_endpoint ... FAILED
test ws_integration::variable_auth_live_query ... ok

failures:

---- ws_integration::live_live_endpoint stdout ----
thread 'ws_integration::live_live_endpoint' panicked at 'Error waiting for messages: Some("Expected 2 messages but got 1 after 500ms: [Object {\"result\": Array [Object {\"result\": Array [Object {\"id\": String(\"table_FD40A9A361884C56B5908A934164884A:⟨an-id-goes-here⟩\"), \"name\": String(\"ok\")}], \"status\": String(\"OK\"), \"time\": String(\"57.541µs\")}], \"id\": String(\"1\")}]")', tests/ws_integration.rs:617:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by AsbjornOlling** [comment]
I encounter a different test failure, but also on related to websockets:

```
running 25 tests
test ws_integration::create ... ok
test ws_integration::authenticate ... ok
test ws_integration::format_json ... ok
test ws_integration::delete ... ok
test ws_integration::format_pack ... ok
test ws_integration::insert ... ok
test ws_integration::format_cbor ... ok
test ws_integration::info ... ok
test ws_integration::let_and_set ... ok
test ws_integration::invalidate ... ok
test ws_integration::kill_query_endpoint ... ok
test ws_integration::merge ... ok
test ws_integration::kill_kill_endpoint ... ok
test ws_integration::live_query_endpoint ... ok
test ws_integration::live_live_endpoint ... ok
test ws_integration::signin ... FAILED
test ws_integration::patch ... ok
test ws_integration::ping ... ok
test ws_integration::query ... ok
test ws_integration::select ... ok
test ws_integration::unset ... ok
test ws_integration::signup ... ok
test ws_integration::update ... ok
test ws_integration::version ... ok
test ws_integration::variable_auth_live_query ... ok
   Vendoring foundationdb-gen v0.8.0 (/build/source/cargo-home.L1d/registry/src/index.crate
failures:
-gen
---- ws_integration::signin stdout ----
thread 'ws_integration::signin' panicked at tests/ws_integration.rs:171:9:
result: Err(Protocol(ResetWithoutClosingHandshake))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
s.io-6f17d22bba15001f/foundationdb-sys-0.8.0) to surrealdb-1.0.0-vendor.tar.gz/foundationdb
-sys
failures:
    ws_integration::signin
```

**Comment by gepbird** [comment]
The websocket test failure was fixed by https://github.com/NixOS/nixpkgs/pull/281791
