### ISSUE TITLE
qutebrowser: restart doesn't work

### ISSUE THREAD

**Issue by igsha** [NixOS/nixpkgs#25832]
## Issue description

I restart `qutebrowser` through its command `:restart`. It is closed successfully but does not start again.

### Steps to reproduce
Start `qutebrowser`:
```sh
[17:58] igor@nixos-pc ~ $ qutebrowser 
17:59:33 INFO: Run :adblock-update to get adblock lists.
```
Then restart it through `:restart` in GUI. I receive this in the terminal:
```sh
Traceback (most recent call last):
  File "/nix/store/ngfvnb22lh72z8prslmfdd2aiis5z08p-python3-3.5.3/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nix/store/ngfvnb22lh72z8prslmfdd2aiis5z08p-python3-3.5.3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nix/store/2xrbf5qbkgpgb1c9bq8mw4hxxr03wki6-qutebrowser-0.10.1/lib/python3.5/site-packages/qutebrowser/__main__.py", line 25, in <module>
    import qutebrowser.qutebrowser
  File "/nix/store/2xrbf5qbkgpgb1c9bq8mw4hxxr03wki6-qutebrowser-0.10.1/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 26, in <module>
    from qutebrowser.utils import log
  File "/nix/store/2xrbf5qbkgpgb1c9bq8mw4hxxr03wki6-qutebrowser-0.10.1/lib/python3.5/site-packages/qutebrowser/utils/log.py", line 34, in <module>
    from PyQt5 import QtCore
ImportError: No module named 'PyQt5'
```
But if I follow the same steps in `nix-shell`:
```sh
[18:00] igor@nixos-pc ~ $ nix-shell -p qutebrowser --run qutebrowser
18:25:42 INFO: Run :adblock-update to get adblock lists.
18:25:47 INFO: Run :adblock-update to get adblock lists.
```
all is fine.

## Technical details

* System: `17.09pre107265.0afb6d789c (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.9`
* Nixpkgs version: `"17.09pre107265.0afb6d789c"`
* Sandboxing enabled: `build-use-sandbox = false`

**Comment by The-Compiler** [comment]
qutebrowser upstream here - what `:restart` does is essentially qutebrowser trying to restart itself by [finding out how it's been launched](https://github.com/qutebrowser/qutebrowser/blob/v0.10.1/qutebrowser/app.py#L514-L541) and then relaunching itself that way and quitting.

That might interfer with how NixOS isolates things from each other, but I really have no idea how NixOS actually works.

Is this something NixOS can solve? Is it something qutebrowser should be more intelligent about? Should it just run `nix-shell -p qutebrowser --run qutebrowser` to rerun itself when it finds out it's on NixOS?

**Comment by fpletz** [comment]
I haven't yet looked at the code, but the problem here is probably that the environment variables (PYTHONPATH in particular) aren't passed to the new process so it can't find the python modules it depends upon. I'll have a look later.

**Comment by FRidh** [comment]
That should have been fixed in the past by I think https://github.com/NixOS/nixpkgs/pull/17749. @abbradar would know.

**Comment by abbradar** [comment]
I think this boils down to:

1. At some point we broken argv[0] patching for qutebrowser -- from `qutebrowser` it becase `.qutebrowser-wrapped`;
2. qutebrowser uses heuristic to determine how to restart itself (see link from @The-Compiler). When it detects that application name is `qutebrowser` it just uses its own `argv[0]` (which is what we want);
3. When the name is strange-looking it instead runs basically `python -m qutebrowser`, bypassing our patching that adds necessary paths.

The solution here is to make sure we set proper `argv[0]` -- I'll look at this later.

@The-Compiler I think the heuristic you use currently is good enough -- it's rather us having a complex and flaky solution for isolating Python apps (which involves patching them). It's difficult to make better; @FRidh has some ideas about this (we can build `virtualenv`-like environments and use `PYTHONHOME` instead of patching library paths to applications).

**Comment by FRidh** [comment]
I suppose its broken by
```
  postFixup = ''
    wrapQtProgram $out/bin/qutebrowser \
      ${lib.optionalString withWebEngineDefault ''--add-flags "--backend webengine"''}
  '';
```
@abbradar my suggestion is that `wrapProgram` not just uses `exec -a` by default but also always sets an env variable, e.g.,  `NIX_PROGRAM_NAME`. Then we can patch our scripts to set `sys.argv0]` to that env variable. See https://github.com/NixOS/nixpkgs/issues/24525

**Comment by baracoder** [comment]
(triage) I have tested on current unstable, the `:restart` command closed the window and opens it again. @igsha can you confirm?

**Comment by igsha** [comment]
@baracoder I've got the same error on current master when type `:restart`:
```
Traceback (most recent call last):
  File "/nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nix/store/icqx7sw9w9azwj3h5cfwz1iak8gk2h28-qutebrowser-1.5.1/lib/python3.6/site-packages/qutebrowser/__main__.py", line 25, in <module>
    import qutebrowser.qutebrowser
  File "/nix/store/icqx7sw9w9azwj3h5cfwz1iak8gk2h28-qutebrowser-1.5.1/lib/python3.6/site-packages/qutebrowser/qutebrowser.py", line 54, in <module>
    from qutebrowser.utils import log
  File "/nix/store/icqx7sw9w9azwj3h5cfwz1iak8gk2h28-qutebrowser-1.5.1/lib/python3.6/site-packages/qutebrowser/utils/log.py", line 35, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5'
```
Tested on:
* `19.03.git.fe91334 (Koi)`
* `qutebrowser v1.5.1`
