### ISSUE TITLE
Neo4j launch failure: Read-only file system

### ISSUE THREAD

**Issue by MelihDarcanxyz** [NixOS/nixpkgs#259542]
### Steps To Reproduce
1. Install and configure `neo4j` with this config:
```nix
{ config, pkgs, ... }: {
  services.neo4j = {
    enable = true;
  };
}
```
2. Neither works:
2.1 `neo4j console --verbose`
2.2 `systemctl start neo4j`
2.3 Try to access web interface

### Expected behavior
Neo4j to launch

### Current behavior
```console
Directories in use:
home:         /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j
config:       /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/conf
logs:         /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/logs
plugins:      /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/plugins
import:       /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/import
data:         /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/data
certificates: /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/certificates
licenses:     /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/licenses
run:          /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/run
Starting Neo4j.
Executing command line: /nix/store/k0wfgwiz9m6zzjwxq462brwpjflgrh20-openjdk-11.0.19+7/lib/openjdk/bin/java -cp /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/plugins/*:/nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/conf/*:/nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/lib/* -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -XX:MaxInlineLevel=15 -XX:-UseBiasedLocking -Djdk.nio.maxCachedBufferSize=262144 -Dio.netty.tryReflectionSetAccessible=true -Djdk.tls.ephemeralDHKeySize=2048 -Djdk.tls.rejectClientInitiatedRenegotiation=true -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -Dlog4j2.disable.jmx=true -Dfile.encoding=UTF-8 org.neo4j.server.CommunityEntryPoint --home-dir=/nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j --config-dir=/nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/conf
org.neo4j.server.startup.BootFailureException: Unexpected error while starting. Aborting. FileSystemException : /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/run/neo4j.pid: Read-only file system
	at org.neo4j.server.startup.ProcessManager.run(ProcessManager.java:209)
	at org.neo4j.server.startup.BootloaderOsAbstraction.console(BootloaderOsAbstraction.java:74)
	at org.neo4j.server.startup.UnixBootloaderOs.console(UnixBootloaderOs.java:57)
	at org.neo4j.server.startup.Bootloader.console(Bootloader.java:151)
	at org.neo4j.server.startup.Neo4jCommand$Console.call(Neo4jCommand.java:56)
	at org.neo4j.server.startup.Neo4jCommand$Console.call(Neo4jCommand.java:47)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.neo4j.server.startup.Neo4jCommand.main(Neo4jCommand.java:166)
Caused by: java.nio.file.FileSystemException: /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/run/neo4j.pid: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
	at java.base/java.nio.file.Files.write(Files.java:3425)
	at org.neo4j.server.startup.PidFileHelper.storePid(PidFileHelper.java:56)
	at org.neo4j.server.startup.ProcessManager.storePid(ProcessManager.java:292)
	at org.neo4j.server.startup.ProcessManager.run(ProcessManager.java:172)
	... 13 more
```

### Notify maintainers
@patternspandemic @jonringer 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.05 (Stoat), 23.05.20230930.32dcb45`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/store/anh1m8q5k4b32aic8fnlzlpy07yb0ydh-source`
```

**Comment by Artturin** [comment]
As seen in the Directories in use maybe the run directory could be changed with `-Dapp.run`?

https://github.com/neo4j/neo4j/blob/60f235e37443d4820c5c5c2a251a4096cf18a430/packaging/standalone/standalone-community/src/main/appassembler/unix-template#L102-L108

I think you should report the issue upstream

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/blob/965f3a22ad779fd2b7ceb48d742ba24491fc9bce/nixos/modules/services/databases/neo4j.nix#L56

It's already being done but in the module config which maybe isn't used when running outside the systemd service
https://github.com/NixOS/nixpkgs/blob/965f3a22ad779fd2b7ceb48d742ba24491fc9bce/nixos/modules/services/databases/neo4j.nix#L593-L625
