### ISSUE TITLE
casperjs is broken in 17.03

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#25977]
Using http://nixos.org/channels/nixos-17.03/nixexprs.tar.xz `casperjs` fails with:

```
======================================================================
FAIL: test_node_module_require_json (__main__.RequireWithOnlyScriptNameTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/clitests/runtests.py", line 258, in test_node_module_require_json
  File "tests/clitests/runtests.py", line 164, in assertCommandOutputEquals
AssertionError: u'Fontconfig error: line 1: no element found\nFontconfig error: Cannot load default config file\n42' != '42'
```

**Comment by 0xABAB** [comment]
@bluescreen303 Can you fix this package, since you are listed as maintainer?

**Comment by pSub** [comment]
casperjs builds fine for me on release-17.03. Please try building / installing it again.

**Comment by 0xABAB** [comment]
@pSub Yes, it's now fixed.
