### ISSUE TITLE
theano-with-cuda: patchPhase insertion of from builtins import bytes is throwing an exception

### ISSUE THREAD

**Issue by twhitehead** [NixOS/nixpkgs#26103]
## Issue description

@FRidh The `patchPhase` for theano-with-cuda does the following in *theano/sandbox/gpuarray*

```bash
sed -i -re '2s/^/from builtins import bytes\n/g' dnn.py
sed -i -re "s/(b'30')/int(bytes(\1))/g" dnn.py
sed -i -re "s/(ctx.bin_id\[\-2:\])/int(\1)/g" dnn.py
```

The inserted import throws an exception under Python 2.7 when importing the module

```
File "/nix/store/ccsqw7w9cha27ji8vgyhlfz8xxa260nn-python-2.7.13-env/lib/python2.7/site-packages/theano/sandbox/gpuarray/dnn.py", line 2, in <module>
  from builtins import bytes
ImportError: No module named builtins
```

### Steps to reproduce

```bash
nix-env -iE 'pkgs: (pkgs.nixpkgs {}).python27.withPackages (ppkgs: [ppkgs.TheanoWithCuda])'
THEANO_FLAGS='device=gpu,floatX=float32' python
```
```python
import theano.sandbox.gpuarray.dnn
```
```
Using gpu device 0: Tesla M2070 (CNMeM is disabled, cuDNN not available)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/ccsqw7w9cha27ji8vgyhlfz8xxa260nn-python-2.7.13-env/lib/python2.7/site-packages/theano/sandbox/gpuarray/__init__.py", line 31, in <module>
    from . import dnn, opt, nerv, extra_ops
  File "/nix/store/ccsqw7w9cha27ji8vgyhlfz8xxa260nn-python-2.7.13-env/lib/python2.7/site-packages/theano/sandbox/gpuarray/dnn.py", line 2, in <module>
    from builtins import bytes
ImportError: No module named builtins
```

## Technical details

* System:

```
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.7 (Final)
Release:        6.7
Codename:       Final
```

* Nix version: `nix-env (Nix) 1.11.4`
* Nixpkgs version: `17.03.326.d919f7db77`
* Sandboxing enabled: `build-use-sandbox = true`

**Comment by twhitehead** [comment]
From googling around a bit, it seems the problem is you need to have a dependency on the `future` package in order to import `builtins` in Python 2.7.

I've verified that if I add this to the list of installed packages, then the import succeeds okay

```bash
nix-env -iE 'pkgs: (pkgs.nixpkgs {}).python27.withPackages (ppkgs: [ppkgs.TheanoWithCuda ppkgs.future])'
THEANO_FLAGS='device=gpu,floatX=float32' python
```
```
Python 2.7.13 (default, Dec 17 2016, 20:05:07) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano.sandbox.gpuarray.dnn
Using gpu device 0: Tesla M2070 (CNMeM is disabled, cuDNN not available)
>>> 
```

**Comment by FRidh** [comment]
@twhitehead then future should be added to the expression, conditionally. Could you open a PR?

**Comment by twhitehead** [comment]
@FRidh I can certainly add it and submit a pull request.

What do you mean by conditionally though (i.e., what would you make it conditional on)?

**Comment by FRidh** [comment]
Interpreter version if, as you said, it is only needed with 2.7

**Comment by twhitehead** [comment]
Got you, that makes sense. :smile:
