### ISSUE TITLE
Build failure: hyper

### ISSUE THREAD

**Issue by Shiroikage** [NixOS/nixpkgs#261209]
### Steps To Reproduce

1. build current hyper (version 3.4.1)
2. start hyper

### Build log

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js
- /nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js
- /nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/ui/window.js
- /nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js',
    '/nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/ui/window.js',
    '/nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/index.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js:39:34)
    at Object.<anonymous> (/nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js:46:11)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/nix/store/wjaznsd2vmcyq4lsxq70pm8mr7w50dvy-hyper-3.4.1/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)

```

### Additional context

- nothing really to add... put hyper in nixos config and it will error at start.

### Notify maintainers

@puffnfresh (maintainer as of [Nix Package Search](https://search.nixos.org/packages?channel=unstable&show=hyper&from=0&size=50&sort=relevance&type=packages&query=Hyper))
@FabianGD (maintainer as of [Nix Package Search](https://search.nixos.org/packages?channel=unstable&show=hyper&from=0&size=50&sort=relevance&type=packages&query=Hyper))
@r-ryantm (last commit)

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.56, NixOS, 23.05 (Stoat), 23.05.4172.bd1cde45c778`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment]
Can't seem to repro on current master, current nixos-23.05, nor the revision that your system is on 🤔

**Comment by kirillrdy** [comment]
I can reproduce on latest master

`
nix run github:nixos/nixpkgs/a3b35afc2df6bd7a94187f9a3215d8e6477c6979#hyper
`

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js
- /nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js
- /nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/ui/window.js
- /nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js',
    '/nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/ui/window.js',
    '/nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/index.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js:39:34)
    at Object.<anonymous> (/nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js:46:11)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/nix/store/dw6jmnag62al9vjhhvvllq3bccjcfh97-hyper-3.4.1/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)

```

**Comment by eclairevoyant** [comment]
ah runtime, not buildtime.

**Comment by kerdamon** [comment]
Anyone managed to fix the issue? I don't see any activity there and I am wondering if this package is deprecated?

**Comment by eclairevoyant** [comment]
If it was fixed, the issue'd be closed.

**Comment by midirhee12** [comment]
Seems to be relevant: #334971

**Comment by midirhee12** [comment]
From the error log, it looks like it is missing node-pty. However, this should have been fetched by npm but is not found in their [package.json](https://github.com/vercel/hyper/blob/canary/package.json). So this may be an issue on their part. However, it should be easy to package node-pty separately and include it as a part of `nativeBuildInputs`.
