### ISSUE TITLE
"stack smashing detected" since recent 23.05 upstream change when entering nix-shell with buildFHSUserEnv

### ISSUE THREAD

**Issue by phip1611** [NixOS/nixpkgs#262080]
### Describe the bug

I'm on a flake-based system with NixOS 23.05 on a x86_64 machine.

I have a reproducible bug that came in very lately in NixOS 23.05 stable. When opening a nix-shell in a specific project, the nix-shell itself creates a  `pkgs.buildFHSUserEnv` with many inputs and end's up with the following error: 

![image](https://github.com/NixOS/nixpkgs/assets/5737016/4dc1d5ae-24f8-4813-8c1e-8deb96c423c0)

It's hard to create a minimal example and I can't provide you the original nix-shell as it relies on some company-internal Nix files.

I know that rev 5a237aecb57296f67276ac9ab296a41c23981f56 (nixos-23.05 branch) from October 7th works and the NixOS 23.05 branch head from October 18th doesn't work. I verified that the issue is not caused by the Linux kernel update from `6.5.5` to `6.5.7`. I think it's glibc or another very basic component.

I tried to do some kind of "manual bisecting" by going commit by commit through the log and build my NixOS system based on that nixpkgs version, but this failed as my system tried to build like everything from nixpkgs, i.e., all the derivations aren't cached (anymore).

### Steps To Reproduce

I'm sorry that I can't provide a real reproducer now due to the limitations mentioned above.

### Expected behavior
A normal nix-shell should open.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/5737016/4dc1d5ae-24f8-4813-8c1e-8deb96c423c0)

### Additional context
None.

### Notify maintainers

Not sure who is in charge as it is not clear what the problem is.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.58, NixOS, 23.05 (Stoat), 23.05.20231017.b5f8ec6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(pschuster): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/37yxpbic78zskxf2di9nbkf0673gjh1p-source`
```

**Comment by phip1611** [comment]
The message comes from the stack protector compiled into the binary by gcc, if I'm not mistaken. Maybe this is the root cause as something has changed their?

**Comment by Hermitter** [comment]
![image](https://github.com/NixOS/nixpkgs/assets/17160717/45d2929f-db5a-404c-9ab6-f63e92fe4a05)
I'm encountering the same issue when I use `vscode-fhs`

**Comment by NateWright** [comment]
I am having a similar problem when using vscode-fhs or unstable vscode-fhs. Plugins are crashing and terminal isn't working saying stack smashing detected.

**Comment by phip1611** [comment]
@NateWright @Hermitter Do you both mean that the bug on your side also just occurs very recently?

**Comment by NateWright** [comment]
@phip1611  Yes as of a few days ago.

**Comment by Hermitter** [comment]
@phip1611 For me it started 2 days ago

**Comment by dverlan** [comment]
Same here - getting this error when trying to open terminal / github / etc. in intellij-idea (both community and ultimate)  via flake.nix that defines fhs

flake.nix file:
```
{
  # Flake.nix with FHSEnv to run idea-community so that github copilot plugin works
  # Made for SD class in IST, feel free to improve it
  # You can run idea-community by typing "nix run .#fhs_env" in the dev shell
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
  };

  
outputs = { nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        devShell = pkgs.mkShell {
          buildInputs = with pkgs; [
          ];
        };
        apps.fhs_env = {
          type = "app";
          program = let drv = pkgs.buildFHSUserEnv {
            name = "idea-ultimate";
            targetPkgs = pkgs: ( with pkgs; [
              jetbrains.idea-ultimate
            ]);
            runScript = "idea-ultimate";
          }; in "${drv}/bin/idea-ultimate";
        };
      }
    );
}
```

Running this as:
```
cdc <folder with flake.nix>
nix develop
export NIXPKGS_ALLOW_UNFREE=1 && nix run .#fhs_env --impure &> /tmp/idea-run-log &
```


**Not** getting the "stack smashing detected" error when running idea without fhs - however this doesn't work for me for another reason, github copilot login is not working, so I am using a variation of [this](https://gist.github.com/creaaidev/a4e6b47d7f8199065fe87f22890d8028) workaround.

Example of stack trace:

```
2023-10-23 11:21:02,445 [   6323]   WARN - #git4idea.repo.GitUntrackedFilesHolder - *** stack smashing detected ***: terminated
com.intellij.openapi.vcs.VcsException: *** stack smashing detected ***: terminated
        at git4idea.commands.GitCommandResult.throwOnError(GitCommandResult.java:156)
        at git4idea.commands.GitCommandResult.getOutputOrThrow(GitCommandResult.java:145)
        at git4idea.index.GitIndexStatusUtilKt.getFileStatus(GitIndexStatusUtil.kt:84)
        at git4idea.repo.GitUntrackedFilesHolder.refreshFiles(GitUntrackedFilesHolder.java:351)
        at git4idea.repo.GitUntrackedFilesHolder.update(GitUntrackedFilesHolder.java:249)
        at com.intellij.util.ui.update.DisposableUpdate$1.doRun(DisposableUpdate.java:31)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
        at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:361)
        at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:339)
        at com.intellij.util.ui.update.DisposableUpdate.run(DisposableUpdate.java:19)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:350)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:340)
        at com.intellij.util.ui.update.MergingUpdateQueue.doExecute(MergingUpdateQueue.java:297)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:280)
        at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:245)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:249)
        at com.intellij.util.Alarm$Request.runSafely(Alarm.java:365)
        at com.intellij.util.Alarm$Request.run(Alarm.java:354)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
        at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
        at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
        at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by danc86** [comment]
I started seeing this today in my `buildFHSUserEnv` shells also. Just an empty environment is enough to see the "stack smashing detected". Here is a minimal shell.nix to reproduce (I use a version of this shell.nix with extra packages and hacks, to compile buildroot packages):

```
let
  pkgs = import <nixpkgs> { };
in (pkgs.buildFHSUserEnv {
  name = "issue-262080-repro";
}).env
```

Previous behaviour (good):

```
$ nix-shell shell-test.nix

[dan@host:~/src/buildroot]$
```

New behaviour (bad):

```
$ nix-shell shell-test.nix
*** stack smashing detected ***: terminated

[dan@host:~/src/buildroot]$ 
```

I'm not sure what exactly is crashing with the stack smashing error, I assume it's just some program being executed inside the various shell startup scripts for `buildFHSUserEnv`.

The regression range is 32dcb45f66c0487e92db8303a798ebc548cadedc..5550a85a087c04ddcace7f892b0bdc9d8bb080c8 on nixos-23.05. I'm bisecting now but it's taking some time to build everything from source on some commits.

**Comment by danc86** [comment]
I realised I can do `git bisect --first-parent` to first find the PR merge commit which introduced the problem. That pointed to https://github.com/NixOS/nixpkgs/pull/260159 which included a glibc update https://github.com/NixOS/nixpkgs/pull/260159/commits/894988b6276a0185c0f36fdfd309bb1489d7813f which is the most likely culprit. I'm just checking it now.

**Comment by danc86** [comment]
After quite a bit of rebuilding the world, I confirmed that the `glibc: 2.37-8 -> 2.37-39` update https://github.com/NixOS/nixpkgs/commit/894988b6276a0185c0f36fdfd309bb1489d7813f is the commit which introduced this problem.

The crash when entering the `buildFHSUserEnv` shell, shown in my previous comments, comes from `dircolors` which is executed by `/etc/bashrc`. But many other programs die in the same way when they're executed in the FHS shell.

Issue #262775 points out that `LD_LIBRARY_PATH` is being set by `buildFHSUserEnv` and I found that if I `unset LD_LIBRARY_PATH` then the crashes go away. But I'm not sure how the glibc update from 2.37-8 to 2.37-39 is related.

**Comment by phip1611** [comment]
@danc86 thanks for the investigation! @blitz and I try to debug the issue further in a session today - let's see if we trace down the root cause and possibly find solution

**Comment by blitz** [comment]
I can reproduce the crash. I get the following `LD_LIBRARY_PATH`:

```
/run/opengl-driver/lib:/run/opengl-driver-32/lib:/usr/lib:/usr/lib32:/nix/store/jv2zvh0h6ippks9ib0ii6gwxmnypfi5r-pipewire-0.3.71-jack/lib
```

If I remove `/usr/lib`, the crash disappears.

The crashdump I get says this:

```
                #0  0x00007f9878dfdadc __pthread_kill_implementation (/nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6 + 0x87adc)
                #1  0x00007f9878daecb6 raise (/nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6 + 0x38cb6)
                #2  0x00007f9878d988ba abort (/nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6 + 0x228ba)
                #3  0x00007f9878d995f5 __libc_message.cold (/nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6 + 0x235f5)
                #4  0x00007f9878e8d629 __fortify_fail (/nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6 + 0x117629)
                #5  0x00007f9878e8d604 __stack_chk_fail (/nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6 + 0x117604)
                #6  0x00007f9878df86c1 __lll_elision_init (/nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6 + 0x826c1)
                #7  0x00007f987915bfa3 dl_main (ld-linux-x86-64.so.2 + 0x1dfa3)
                #8  0x00007f9879158703 _dl_sysdep_start (ld-linux-x86-64.so.2 + 0x1a703)
                #9  0x00007f9879159e1e _dl_start (ld-linux-x86-64.so.2 + 0x1be1e)
                #10 0x00007f9879158cd8 _start (ld-linux-x86-64.so.2 + 0x1acd8)
```

**Comment by Atemu** [comment]
Could someone do a first-parent bisect to figure out what triggered this?

**Comment by blitz** [comment]
@Atemu See https://github.com/NixOS/nixpkgs/issues/262080#issuecomment-1776123277.

But depending on the reproducer this either introduces or fixes the issue. My current hypothesis is that the real issue is #262775 and the glibc update just shuffles things around a bit to make it work/fail depending on the circumstance.

**Comment by Atemu** [comment]
Ah, missed that, thanks. Yeah, I suspect the latter too.

**Comment by Atemu** [comment]
The above is not related to buildFHSEnv.

Does anyone still experience this?

**Comment by danc86** [comment]
I had been doing this as a workaround:

```
  profile = ''
    unset LD_LIBRARY_PATH
  '';
```

With latest `nixos-23.05` branch my workaround isn't needed. Looks like https://github.com/NixOS/nixpkgs/pull/263378 has fixed this.
