### ISSUE TITLE
pdfstudio2022 builds ok but does not run - Java error messages

### ISSUE THREAD

**Issue by bluesangel** [NixOS/nixpkgs#262470]
Environment : Fedora Silver Blue 39 (so Gnome) with Nix packages : 
Installed program through **nix-shell -p pdfstudio2022**

Program does not run : 
Java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:87)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:75)
	at java.desktop/java.awt.Font.getFont2D(Font.java:526)
	at java.desktop/java.awt.Font$FontAccessImpl.getFont2D(Font.java:265)
	at java.desktop/sun.font.FontUtilities.getFont2D(FontUtilities.java:148)
	at java.desktop/sun.font.FontUtilities.getCompositeFontUIResource(FontUtilities.java:396)
	at java.desktop/com.sun.java.swing.plaf.gtk.PangoFonts.lookupFont(PangoFonts.java:204)
	at java.desktop/com.sun.java.swing.plaf.gtk.GTKLookAndFeel.getGTKStyleFactory(GTKLookAndFeel.java:1582)
	at java.desktop/com.sun.java.swing.plaf.gtk.GTKLookAndFeel.loadStyles(GTKLookAndFeel.java:1546)
	at java.desktop/com.sun.java.swing.plaf.gtk.GTKLookAndFeel.initialize(GTKLookAndFeel.java:1439)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:592)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:639)
	at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1411)
	at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1524)
	at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1490)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1062)
	at java.desktop/javax.swing.JLabel.updateUI(JLabel.java:288)
	at java.desktop/javax.swing.JLabel.<init>(JLabel.java:180)
	at java.desktop/javax.swing.JLabel.<init>(JLabel.java:251)
	at com.exe4j.runtime.gui.AwtSplashScreen.<init>(AwtSplashScreen.java:26)
	at com.exe4j.runtime.gui.AwtSplashScreen.<init>(AwtSplashScreen.java:10)
	at com.exe4j.runtime.gui.AwtSplashScreen$Invoker.create(AwtSplashScreen.java:92)
	at com.exe4j.runtime.splash.SplashEngine.setJavaSplashScreenConfig(SplashEngine.java:15)
	at com.install4j.runtime.launcher.UnixLauncher.prepareLaunch(UnixLauncher.java:122)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:68)
	at install4j.com.qoppa.pdfStudio.pub.PDFStudio.main(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:85)
	... 26 more
Caused by: java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:224)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:106)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:706)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:358)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:315)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:315)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 32 more

**Comment by FliegendeWurst** [comment]
#104935 looks similar. Which channel (23.05 / 23.11 / unstable) do you use?

**Comment by bluesangel** [comment]
Thanks for your quick reply. 
**nix-info** 
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.16.1, channels(root): "nixpkgs", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixpkgs

nix-channel --list returns nothing. Don't know if this is normal - I started using Nix a couple of months ago.

**Comment by chewblacka** [comment]
> Thanks for your quick reply. **nix-info** system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.16.1, channels(root): "nixpkgs", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixpkgs
> 
> nix-channel --list returns nothing. Don't know if this is normal - I started using Nix a couple of months ago.

What is the output of the following command? :

`nix-shell -p nix-info --run "nix-info -m"`

**Comment by bluesangel** [comment]
```
nix-shell -p nix-info --run "nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.6-300.fc39.x86_64, Fedora Linux, 39.20231019.n.0 (Silverblue), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```
