### ISSUE TITLE
Calibre-web doesn't work 

### ISSUE THREAD

**Issue by LamprosPitsillos** [NixOS/nixpkgs#262996]
### Describe the bug
Calibre-web doesnt work throwing python errors.

https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/calibre-web/default.nix#L103

### Steps To Reproduce
1. Add `calibre-web` to nixos-config packages

### Expected behavior
I installed `calibre-web` through nixos config and it isnt working 

```
Traceback (most recent call last):
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/z4yl4pqxz1ha863wr2x4s7w4rph5pz5y-calibre-web-0.6.20/bin/.calibre-web-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/z4yl4pqxz1ha863wr2x4s7w4rph5pz5y-calibre-web-0.6.20/lib/python3.10/site-packages/calibreweb/cps/main.py", line 31, in main
    app = create_app()
  File "/nix/store/z4yl4pqxz1ha863wr2x4s7w4rph5pz5y-calibre-web-0.6.20/lib/python3.10/site-packages/calibreweb/cps/__init__.py", line 115, in create_app
    ub.init_db(cli_param.settings_path)
  File "/nix/store/z4yl4pqxz1ha863wr2x4s7w4rph5pz5y-calibre-web-0.6.20/lib/python3.10/site-packages/calibreweb/cps/ub.py", line 838, in init_db
    Base.metadata.create_all(engine)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 4930, in create_all
    bind._run_ddl_visitor(
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3227, in _run_ddl_visitor
    with self.begin() as conn:
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3143, in begin
    conn = self.connect(close_with_result=close_with_result)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/nix/store/k67p7vim6vhh0v4mfnm4anv1crqk0wgw-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)

```

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.58, NixOS, 23.11 (Tapir), 23.11.20231019.7c9cc5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by h7x4** [comment]
If you're using NixOS, I'd recommend you use the calibre-web module instead. However, that doesn't mean we shouldn't fix the package.

According to the stack trace, this was the function that failed: https://github.com/janeczku/calibre-web/blob/3d07efbb4f67cd43c9dd7fd6f06b4499a40773ac/cps/ub.py#L834

Moving through some abstraction layers, it seems to come down to the lines in https://github.com/janeczku/calibre-web/blob/3d07efbb4f67cd43c9dd7fd6f06b4499a40773ac/cps/constants.py

```python
# if installed via pip this variable is set to true (empty file with name .HOMEDIR present)
HOME_CONFIG = os.path.isfile(os.path.join(os.path.dirname(os.path.abspath(__file__)), '.HOMEDIR'))

[...]

# Base dir is parent of current file, necessary if called from different folder
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir))

[...]

if HOME_CONFIG:
    home_dir = os.path.join(os.path.expanduser("~"), ".calibre-web")
    if not os.path.exists(home_dir):
        os.makedirs(home_dir)
    CONFIG_DIR = os.environ.get('CALIBRE_DBPATH', home_dir)
else:
    CONFIG_DIR = os.environ.get('CALIBRE_DBPATH', BASE_DIR)
```

I'm not entirely sure what's the best action to take here. Maybe we should just create the `.HOMEDIR` file during packaging? It's at least better than having it try writing to the nix store by default.
