### ISSUE TITLE
k3s: service fails to start, wrong go version is probably used for build

### ISSUE THREAD

**Issue by jakuzure** [NixOS/nixpkgs#263580]
### Describe the bug
Tried updating to latest nixos-unstable, but k3s service won't start due to bug described here (https://github.com/k3s-io/k3s/issues/8293#issuecomment-1714750513):

```
time="2023-09-04T17:58:35Z" level=info msg="Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log"
panic: flag alsologtostderr set at github.com/k3s-io/k3s/pkg/cli/cmds/log.go:78 before being defined
```

According to the issue golang 1.20 should be used for building.

### Steps To Reproduce
1. update to latest nixos-unstable
2. have k3s service enabled
3. service won't start

### Expected behavior
k3s is starting without errors

### Additional context
I downgraded to k3s_1_25 for the time being, this version seems unaffected by the bug, 1.26 and 1.27 both seem to not work properly

### Notify maintainers

@euank @mic92 @yajo

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
﻿﻿ - system: `"x86_64-linux"`
 - host os: `Linux 6.1.57, NixOS, 23.11 (Tapir), 23.11.20231024.8efd5d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by euank** [comment]
Thanks for the clear report, and digging up the upstream issue! Appreciated!

I moved it to be built with go_1_20 in this pr: https://github.com/NixOS/nixpkgs/pull/263780

Since the tests pass there, that seems like a good sign the service starts up after that fix

**Comment by jakuzure** [comment]
@euank Thank you for the quick fix, I tried to build your branch on my kind of weak Linux server, but I think it ran out of memory, so I can't test it right now unfortunately.

Are there any tests in place for the module that check if it can start correctly? Maybe implementing something like that could save time in the future

**Comment by euank** [comment]
There are such tests, yup.

On current nixpkgs master:

```
$ nix-build -A k3s.passthru.tests.single-node
...
machine # [    9.806518] k3s[925]: time="2023-10-27T14:01:35Z" level=info msg="Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd"

machine # [    9.837871] k3s[925]: panic: flag alsologtostderr set at github.com/k3s-io/k3s/pkg/cli/cmds/log.go:78 before being defined
machine # [    9.839209] k3s[925]: goroutine 3303 [running]:
machine # [    9.839956] k3s[925]: flag.(*FlagSet).Var(0xc000128150, {0xa5d3a28, 0xe08daa9}, {0x9888c5a, 0xf}, {0x9a7caf8, 0x49})
machine # [    9.842124] k3s[925]:      flag/flag.go:1031 +0x33a
machine # [    9.842628] k3s[925]: k8s.io/klog/v2.InitFlags.func1(0xc0002811a0?)
machine # [    9.845121] k3s[925]:      k8s.io/klog/v2@v2.100.1/klog.go:437 +0x31
machine # [    9.845753] k3s[925]: flag.(*FlagSet).VisitAll(0xe08ace0?, 0xc00138ef30)
machine # [    9.846450] k3s[925]:      flag/flag.go:458 +0x42
machine # [    9.846938] k3s[925]: k8s.io/klog/v2.InitFlags(0xa60aa80?)
machine # [    9.850388] k3s[925]:      k8s.io/klog/v2@v2.100.1/klog.go:436 +0x45
machine # [    9.852087] k3s[925]: github.com/k3s-io/k3s/pkg/daemons/executor.(*Embedded).Bootstrap.func1()
machine # [    9.852948] k3s[925]:      github.com/k3s-io/k3s/pkg/daemons/executor/embed.go:61 +0x55
machine # [    9.854838] k3s[925]: created by github.com/k3s-io/k3s/pkg/daemons/executor.(*Embedded).Bootstrap in goroutine 1
machine # [    9.856134] k3s[925]:      github.com/k3s-io/k3s/pkg/daemons/executor/embed.go:54 +0x8f
machine # [    9.859256] systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
machine # [    9.860407] systemd[1]: k3s.service: Failed with result 'exit-code'.
machine # [    9.969818] systemd[1]: Failed to start k3s service.

<... test hangs forever and never passes>
```

In https://github.com/NixOS/nixpkgs/pull/254878, only package builds were tested, not individual packages. I think it just impacted so many packages total it wasn't practical to run all the package's tests.

**Comment by jakuzure** [comment]
Ah, that makes a lot of sense, my next question would have been why it didn't show up as failing earlier 😄

Thanks for the explanation! Did you have a chance to test it with the service? If not, I can boot up my slightly beefier NAS and see if it works there.

**Comment by euank** [comment]
The k3s tests in the PR pass, which means the service starts and a pod runs!
The tests cover enough that I'm fine trusting them for this fix.
