### ISSUE TITLE
arandr broken in nixos-unstable

### ISSUE THREAD

**Issue by miallo** [NixOS/nixpkgs#263761]
### Describe the bug
the shipped version 0.1.10 of arandr is incompatible with Python 3.11. A fix for this is in arandr version 0.1.11

This bug report is mainly there, so others looking for this bug will have an easier time finding it. Open MRs fixing it are https://github.com/NixOS/nixpkgs/pull/243463 and https://github.com/NixOS/nixpkgs/pull/263632

### Steps To Reproduce
```console
> python3 --version
Python 3.11.5
> arandr --version
Traceback (most recent call last):
  File "/nix/store/31fva7xfs324zblzgh3sk392m0dhn8ga-arandr-0.1.10/bin/..arandr-wrapped-wrapped", line 42, in <module>
    from screenlayout.gui import main
  File "/nix/store/31fva7xfs324zblzgh3sk392m0dhn8ga-arandr-0.1.10/lib/python3.11/site-packages/screenlayout/gui.py", line 76, in <module>
    class Application:
  File "/nix/store/31fva7xfs324zblzgh3sk392m0dhn8ga-arandr-0.1.10/lib/python3.11/site-packages/screenlayout/gui.py", line 185, in Application
    @actioncallback
     ^^^^^^^^^^^^^^
  File "/nix/store/31fva7xfs324zblzgh3sk392m0dhn8ga-arandr-0.1.10/lib/python3.11/site-packages/screenlayout/gui.py", line 48, in actioncallback
    argnames = inspect.getargspec(function)[0]
               ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

### Expected behavior
arandr should be able to start

### Notify maintainers
@domenkozar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.20231027.3065bed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/pull/243463
