### ISSUE TITLE
insync first start GUI can't open web browser to setup account, no icon on panel

### ISSUE THREAD

**Issue by jotapesse** [NixOS/nixpkgs#264124]
### Describe the bug
Trying to run first time insync I get a blank/empty icon on the panel but the app/widget runs on the panel. The insync window opens on the desktop but when clicking to setup any account it will try to open the web browser but fails without any error on screen.

OS: NixOS 23.11 (unstable)
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Windows system: Wayland
NixOS Package: [insync](https://search.nixos.org/packages?channel=unstable&show=insync&from=0&size=50&sort=relevance&type=packages&query=insync) installed via nixos/configuration.nix
Default Web browser: Google Chrome

### Steps To Reproduce
1. Logon to KDE/Plasma Wayland desktop;
2. insync will start automatically, widget on panel and window open on desktop;
3. Or, run "insync start" via Krunner or the terminal;
4. First time configuration window for insync will open;
5. insync systraywidget on panel works with a blank icon (known issue);
6. Try to click any of "Add Google Drive", "Add OneDrive" or "Add Dropbox" accounts to configure:
7. A warning from KIO Client window will appear with "This will start the program: Google Chrome", click "Continue" to proceed;
8. Nothing happens;

### Expected behavior
Progression on the configuration of new accounts on insync, authentication sign-in via web browser

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/56384317/dc95bde4-cf96-488a-8658-96b429147fde)

### Additional context
Trying to run on terminal we get the following errors:

```$ insync start --no-daemon
Unsetting QT_STYLE_OVERRIDE=
Unsetting QT_QPA_PLATFORMTHEME=
XKB_CONFIG_ROOT=/nix/store/096yg7fc67py86w0bm6g7a32npgyh5ic-xkeyboard-config-2.39/share/X11/xkb/
Using Wayland-EGL
xkbcommon: ERROR: couldn't find a Compose file for locale "en_GB.UTF-8" (mapped to "en_GB.UTF-8")
QSystemTrayIcon::setVisible: No Icon set
INFO     2023-10-29 07:42:43,888 [mainlogs:_log_run:138] Core(app_version=3.8.6.50504, platform=Linux-x86_64-nixos/23.11) initialized
INFO     2023-10-29 07:42:43,906 [mainsettings:_load_settings:236] Loaded settings, machine fingerprint = KM9Z9KIhCeUEneLd-8lp-G2IUIg=
Using the 'xdg-shell' shell integration
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
INFO     2023-10-29 07:42:44,013 [app:start_core:65] core started
INFO     2023-10-29 07:42:44,015 [unix_socket_server:start:106] unix socket server thread start
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 6000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 6000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 6000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 6000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 12000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 12000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 12000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 12000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 24000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 48000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 6000
kf.service.sycoca: Service type not found: "application/vnd.insync.link.drive.slides"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.dropbox.paper"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.dropbox.papert"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.dropbox.gsheet"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.drive.map"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.drive.form"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.drive.doc"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.drive.script"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.drive.note"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.dropbox.gslides"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.dropbox.gdoc"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.drive.draw"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.dropbox.web"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.drive.table"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.drive.link"
kf.service.sycoca: Service type not found: "application/vnd.insync.link.drive.sheet"
kf.config.core: Access to ' "/run/current-system/sw/share/applications/google-chrome.desktop" ' denied, not owned by root and executable flag not set.
kf.kio.core: Unable to open replacement file for "/run/current-system/sw/share/applications/google-chrome.desktop" "Existing file /run/current-system/sw/share/applications/google-chrome.desktop is not writable"
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 12000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 24000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 96000
js: Bad HTTP status: 0 
js: Enqueued failed request for retry in 96000
INFO     2023-10-29 07:44:18,422 [app:quit:80] quitting
INFO     2023-10-29 07:44:18,423 [unix_socket_server:stop:126] unix socket server thread stop
ERROR    2023-10-29 07:44:18,433 [workbase:__run:257] While running ExternalLogin(cloud='gd')
Traceback (most recent call last):
  File "idesksync/workbase.py", line 246, in __run
  File "ideskcore/loginwork.py", line 77, in _do
  File "ideskcore/loginwork.py", line 152, in read_line
  File "idesknet/httpclient.py", line 608, in read
  File "idesknet/httpclient.py", line 589, in read1
idesknet.httpclient.HTTPClosedError
ERROR    2023-10-29 07:44:18,434 [workbase:_log_task_exception:449] While running ExternalLogin(cloud='gd')
Traceback (most recent call last):
  File "idesksync/workbase.py", line 246, in __run
  File "ideskcore/loginwork.py", line 77, in _do
  File "ideskcore/loginwork.py", line 152, in read_line
  File "idesknet/httpclient.py", line 608, in read
  File "idesknet/httpclient.py", line 589, in read1
idesknet.httpclient.HTTPClosedError
ERROR    2023-10-29 07:44:18,435 [uidata:__await_and_return_result:163] Unexpected error while calling 'add_account'
Traceback (most recent call last):
  File "ideskui/uidata.py", line 155, in __await_and_return_result
  File "ideskui/appui.py", line 125, in add_account
  File "ideskapi/apibase.py", line 73, in __call__
  File "ideskcore/mainsync.py", line 297, in setup_account
  File "ideskcore/mainsync.py", line 146, in external_login
  File "idesksync/workbase.py", line 246, in __run
  File "ideskcore/loginwork.py", line 77, in _do
  File "ideskcore/loginwork.py", line 152, in read_line
  File "idesknet/httpclient.py", line 608, in read
  File "idesknet/httpclient.py", line 589, in read1
idesknet.httpclient.HTTPClosedError
js: Uncaught (in promise) #<Object>
INFO     2023-10-29 07:44:18,439 [app:stop:75] core stopped
INFO     2023-10-29 07:44:18,440 [app:stop:77] clean exit
```

### Notify maintainers
@hellwolf 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11pre537656.7c9cc5a6e5d3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jotapesse** [comment]
Updated recently to latest NixOS unstable updates. Same issue, no changes.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9, NixOS, 23.11 (Tapir), 23.11pre541036.63678e9f3d3a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hellwolf** [comment]
Hi @jotapesse, thanks for the reporting, I will be taking a deeper look as soon as I can!

**Comment by hellwolf** [comment]
Hi folks, sorry for the delays.

I am working on a fix and an upgrade to 3.8.7.50508, here is a work-in-progress draft: https://github.com/NixOS/nixpkgs/pull/277937/files

If you are able to test it during development, that'd be helpful!

Happy new year!

**Comment by hellwolf** [comment]
Instead, please give a upvote to this pull request instead: https://github.com/NixOS/nixpkgs/pull/279426

This one should have fixed many issues.

**Comment by hellwolf** [comment]
Is it still an issue?

FYI: Also, a new package for nautilus users: https://github.com/NixOS/nixpkgs/pull/302422 please give a :+1: for faster merging!

**Comment by jotapesse** [comment]
Sorry, to clarify: not exactly the same behaviour - I no longer get errors on terminal, and trying to open Google Chrome by pressing the button on the KIO Client window results in a failure with the following error:
![image](https://github.com/NixOS/nixpkgs/assets/56384317/a6e89afe-6632-4a53-bb4b-68ac952643eb)

**Comment by hellwolf** [comment]
Hi, the latest version from nixpkgs-unstable should be:

```
$ insync version
3.8.7.50516
```

**Comment by jotapesse** [comment]
Ok, let me update to it and I'll report back. Thanks.

**Comment by jotapesse** [comment]
Ok, just updated verything and rebooted the system. I'm now on:
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.4, NixOS, 24.05 (Uakari), 24.05pre608655.ff0dbd94265a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
With KDE Plasma 6.0.3:
```
Operating System: NixOS 24.05
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.3
Kernel Version: 6.8.4 (64-bit)
Graphics Platform: Wayland
```
And insync version:
```
$ insync version
3.8.7.50516
```

⚠️ But still the same KIO Client error as reported above. Are you not able to replicate this behaviour? Something missing on my system?

**Comment by hellwolf** [comment]
Okay, thanks for trying! I don't have KDE setup. I will keep this bug open and see anyone or me will be able to reproduce and find a fix.

**Comment by jotapesse** [comment]
Thank you for following this up. _it would be great if you could try it on KDE Plasma and check this behaviour. I'm guessing something related with the XDG Portals integration and/or the KIO Client use. But my setup is pretty much default so it should work fine out of the box.  It doesn't unfortunately and for many months now.

**Comment by jotapesse** [comment]
Hi! An update here: I have confirmed as I suspected that this was a XDG Portals integration issue. Eventually I resolved it by making sure the elevant configuration was added to the `/etc/nixos/configuration.nix` file:

```
# XDG Portal
xdg.portal.enable = true;
xdg.portal.xdgOpenUsePortal = true; #  This will make `xdg-open` use the portal to open programs, which resolves bugs involving programs opening...
```

I  am now updated to the following with the above XDG Portal configuration and opening the web browser to proceed with authentication of the Cloud accounts now works fine:

**Operating System:** NixOS 24.05
**KDE Plasma Version:** 6.0.4
**KDE Frameworks Version:** 6.1.0
**Qt Version:** 6.7.0
**Kernel Version:** 6.8.9 (64-bit)
**Graphics Platform:** Wayland

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05pre621993.25865a40d14b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

$ insync version
3.8.7.50516
```

⚠️ Still missing is the insync systray icon. Insync works on the systray but the icon is empty/blank. Any help here?
