### ISSUE TITLE
GitLab fails to create backups

### ISSUE THREAD

**Issue by CobaltCause** [NixOS/nixpkgs#264392]
### Describe the bug

`gitlab-backup.service` fails to create backups. Similarly, doing it manually as the gitlab user also fails in the same way. This is happening to me while using GitLab 16.4.1; I didn't test other versions. This reminds me of <https://github.com/NixOS/nixpkgs/issues/255201>, but I don't think that issue was hitting the same logging code path.

<details>
<summary>Click to view logs</summary>

```
Oct 30 07:44:47 blue systemd[1]: Started gitlab-backup.service.
Oct 30 07:44:56 blue gitlab-rake[685460]: WARNING: The Rust extension for prometheus-client-mmap is unavailable, falling back to the legacy C extension.
Oct 30 07:44:56 blue gitlab-rake[685460]:   The Rust extension will be required in the next version. If you are compiling this gem from source,
Oct 30 07:44:56 blue gitlab-rake[685460]:   ensure your build system has a Rust compiler and clang: https://gitlab.com/gitlab-org/ruby/gems/prometheus-client-mmap
Oct 30 07:44:57 blue gitlab-rake[685460]: /nix/store/pfkjbayhfiw64f7x4d8kfvyz93mfnhf4-gitlab-env-16.4.1/lib/ruby/gems/3.0.0/gems/unleash-3.2.2/lib/unleash/strategy/util.rb:8: warning: already initialized constant Unleash::Strategy::Util::NORMALIZER
Oct 30 07:44:57 blue gitlab-rake[685460]: /nix/store/b8v7vd3mb5ndf7lgbj84s0z976g18wp2-ruby3.0.6-unleash-3.2.2/lib/ruby/gems/3.0.0/gems/unleash-3.2.2/lib/unleash/strategy/util.rb:8: warning: previous definition of NORMALIZER was here
Oct 30 07:44:59 blue gitlab-rake[685460]:           ██     ██  █████  ██████  ███    ██ ██ ███    ██  ██████ 
Oct 30 07:44:59 blue gitlab-rake[685460]:           ██     ██ ██   ██ ██   ██ ████   ██ ██ ████   ██ ██      
Oct 30 07:44:59 blue gitlab-rake[685460]:           ██  █  ██ ███████ ██████  ██ ██  ██ ██ ██ ██  ██ ██   ███ 
Oct 30 07:44:59 blue gitlab-rake[685460]:           ██ ███ ██ ██   ██ ██   ██ ██  ██ ██ ██ ██  ██ ██ ██    ██ 
Oct 30 07:44:59 blue gitlab-rake[685460]:            ███ ███  ██   ██ ██   ██ ██   ████ ██ ██   ████  ██████  
Oct 30 07:44:59 blue gitlab-rake[685460]: ******************************************************************************
Oct 30 07:44:59 blue gitlab-rake[685460]:   Your database has a single connection, and single connections were
Oct 30 07:44:59 blue gitlab-rake[685460]:   deprecated in GitLab 15.9 https://docs.gitlab.com/ee/update/deprecations.html#single-database-connection-is-deprecated.
Oct 30 07:44:59 blue gitlab-rake[685460]:   Please add a :ci section to your database, following these instructions:
Oct 30 07:44:59 blue gitlab-rake[685460]:   https://docs.gitlab.com/ee/install/installation.html#configure-gitlab-db-settings.
Oct 30 07:44:59 blue gitlab-rake[685460]: ******************************************************************************
Oct 30 07:45:00 blue gitlab-rake[685460]: I, [2023-10-30T07:45:00.749434 #685460]  INFO -- : Raven 3.1.2 configured not to capture errors: DSN not set
Oct 30 07:45:02 blue gitlab-rake[685460]: rake aborted!
Oct 30 07:45:02 blue gitlab-rake[685460]: Errno::EACCES: Permission denied @ rb_sysopen - /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/log/backup_json.log
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/bxnhbacb2dwgbzxc9kkhcf0id0zrsfgr-ruby3.0.6-gitlab-labkit-0.34.0/lib/ruby/gems/3.0.0/gems/gitlab-labkit-0.34.0/lib/labkit/logging/json_logger.rb:36:in `initialize'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/gitlab/json_logger.rb:33:in `new'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/gitlab/json_logger.rb:33:in `build'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/gitlab/json_logger.rb:28:in `info'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/backup/manager.rb:631:in `puts_time'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/backup/manager.rb:360:in `cleanup'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/backup/manager.rb:239:in `ensure in run_all_create_tasks'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/backup/manager.rb:240:in `run_all_create_tasks'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/backup/manager.rb:47:in `create'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/tasks/gitlab/backup.rake:13:in `block in create_backup'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/tasks/gitlab/backup.rake:62:in `lock_backup'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/tasks/gitlab/backup.rake:10:in `create_backup'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/tasks/gitlab/backup.rake:101:in `block (3 levels) in <top (required)>'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/yh2dav9ghbfsr6gla5mv696qpnkyg8kg-ruby3.0.6-sentry-ruby-5.8.0/lib/ruby/gems/3.0.0/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:26:in `execute'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/pfkjbayhfiw64f7x4d8kfvyz93mfnhf4-gitlab-env-16.4.1/lib/ruby/gems/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Oct 30 07:45:02 blue gitlab-rake[685460]: Caused by:
Oct 30 07:45:02 blue gitlab-rake[685460]: Errno::EACCES: Permission denied @ rb_sysopen - /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/log/backup_json.log
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/bxnhbacb2dwgbzxc9kkhcf0id0zrsfgr-ruby3.0.6-gitlab-labkit-0.34.0/lib/ruby/gems/3.0.0/gems/gitlab-labkit-0.34.0/lib/labkit/logging/json_logger.rb:36:in `initialize'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/gitlab/json_logger.rb:33:in `new'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/gitlab/json_logger.rb:33:in `build'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/gitlab/json_logger.rb:28:in `info'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/backup/manager.rb:631:in `puts_time'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/backup/manager.rb:70:in `run_create_task'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/backup/manager.rb:227:in `block in run_all_create_tasks'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/backup/manager.rb:226:in `each_key'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/backup/manager.rb:226:in `run_all_create_tasks'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/backup/manager.rb:47:in `create'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/tasks/gitlab/backup.rake:13:in `block in create_backup'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/tasks/gitlab/backup.rake:62:in `lock_backup'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/tasks/gitlab/backup.rake:10:in `create_backup'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/qpm9z5z07lj2vjc7r5qi1fwj6i5nw30x-gitlab-16.4.1/share/gitlab/lib/tasks/gitlab/backup.rake:101:in `block (3 levels) in <top (required)>'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/yh2dav9ghbfsr6gla5mv696qpnkyg8kg-ruby3.0.6-sentry-ruby-5.8.0/lib/ruby/gems/3.0.0/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:26:in `execute'
Oct 30 07:45:02 blue gitlab-rake[685460]: /nix/store/pfkjbayhfiw64f7x4d8kfvyz93mfnhf4-gitlab-env-16.4.1/lib/ruby/gems/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Oct 30 07:45:02 blue gitlab-rake[685460]: Tasks: TOP => gitlab:backup:create
Oct 30 07:45:02 blue gitlab-rake[685460]: (See full trace by running task with --trace)
Oct 30 07:45:02 blue systemd[1]: gitlab-backup.service: Main process exited, code=exited, status=1/FAILURE
Oct 30 07:45:02 blue systemd[1]: gitlab-backup.service: Failed with result 'exit-code'.
Oct 30 07:45:02 blue systemd[1]: gitlab-backup.service: Consumed 15.036s CPU time, received 832.0K IP traffic, sent 87.0K IP traffic.
```

</details>

### Steps To Reproduce
1. Either of the following:
   * Wait for the systemd timer to trigger an automatic backup
   * Run `sudo -u git gitlab-rake gitlab:backup:create RAILS_ENV=production`
3. Kaboom

### Expected behavior
I expect GitLab to successfully create a backup when running as its intended user.

### Additional context
Running it as root makes it work, but at the cost of writing logs to the nix store, and other side effects of running it as root.

### Notify maintainers

@globin @krav @talyz @yayayayaka @yu-re-ka

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9, NixOS, 23.11 (Tapir), 23.11.20231026.63678e9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/35dcag44a0ymww0vy0s4jjgxwpv9g62d-source`
```

**Comment by yu-re-ka** [comment]
This is weird since the nixos test also includes doing a backup and restoring it. Can you maybe use this to isolate the difference between your setup and the nixos test?

**Comment by CobaltCause** [comment]
Oh, neat. I initially suspected the NixOS test might be doing it as root which avoids the problem, but it looks like it's going through the systemd unit, so that's good.

A/the commit of my configuration where GitLab is exhibiting this problem is here, pointing at the directory containing my GitLab configuration: https://or.computer.surgery/charles/servy-fleet/-/tree/9480f67cee8e35c7a55a5d30894ccfb85bdf85d1/config/gitlab

The only thing that really jumps out to me is that I'm overriding the linux user and group from `gitlab` to `git`.

**Comment by CobaltCause** [comment]
I don't know Ruby at all but [this](https://gitlab.com/gitlab-org/gitlab/-/blob/v16.4.1-ee/lib/gitlab/backup_logger.rb?ref_type=tags#L4) looks like the backup logger is always the JSON logger, which is the thing that I changed in my PR to make it work for me. I'm at a loss for how this could be working in the NixOS test.

**Comment by CobaltCause** [comment]
Well, it works in fine in gitlab 16.7.2, so I guess this can be closed.
