### ISSUE TITLE
Freenet plugin WebofTrust fails to install

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#264890]
### Describe the bug
WoT fails to install, even after multiple attempts

### Steps To Reproduce
1. Open Freenet page
2. Install WoT plugin
3. Java exception pops up:

```console
The plugin WebOfTrust could not be loaded: class com.db4o.ext.ObjectNotStorableException: Add constructor that won't throw exceptions, configure constructor calls, or provide a translator to class 'plugins.WebOfTrust.Configuration' and make sure the class is deployed to the server with the same package/namespace + assembly name.
       at com.db4o.internal.ClassMetadata.createConstructor(ClassMetadata.java:557)
       at com.db4o.internal.ClassMetadata.init(ClassMetadata.java:977)
       at com.db4o.internal.PartialObjectContainer.createClassMetadata(PartialObjectContainer.java:441)
       at com.db4o.internal.ClassMetadataRepository.createClassMetadata(ClassMetadataRepository.java:117)
       at com.db4o.internal.ClassMetadataRepository.produceClassMetadata(ClassMetadataRepository.java:222)
       at com.db4o.internal.PartialObjectContainer.produceClassMetadata(PartialObjectContainer.java:970)
       at com.db4o.internal.query.processor.QConClass.<init>(QConClass.java:49)
       at com.db4o.internal.query.processor.QConClass.<init>(QConClass.java:58)
       at com.db4o.internal.query.processor.QQueryBase.addClassConstraint(QQueryBase.java:190)
       at com.db4o.internal.query.processor.QQueryBase.constrain(QQueryBase.java:129)
       at plugins.WebOfTrust.WebOfTrust.peekDatabaseFormatVersion(WebOfTrust.java:1553)
       at plugins.WebOfTrust.WebOfTrust.openDatabase(WebOfTrust.java:676)
       at plugins.WebOfTrust.WebOfTrust.runPlugin(WebOfTrust.java:242)
       at freenet.pluginmanager.PluginHandler.startPlugin(PluginHandler.java:44)
       at freenet.pluginmanager.PluginManager.realStartPlugin(PluginManager.java:381)
       at freenet.pluginmanager.PluginManager.startPluginOfficial(PluginManager.java:351)
       at freenet.pluginmanager.PluginManager.startPluginOfficial(PluginManager.java:343)
       at freenet.clients.http.PproxyToadlet$2.run(PproxyToadlet.java:142)
       at freenet.support.PooledExecutor$MyThread.innerRun(PooledExecutor.java:259)
       at freenet.support.PooledExecutor$MyThread.realRun(PooledExecutor.java:197)
       at freenet.support.io.NativeThread.run(NativeThread.java:156)
```

### Expected behavior
The plugins should work as expected

### Screenshots
\-

### Additional context
\-

### Notify maintainers
@nagy 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.11 (Tapir), 23.11pre542330.0cbe9f69c234`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(ashvith): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by nagy** [comment]
Confirming, that this is reproducible.

>        at plugins.WebOfTrust.WebOfTrust.openDatabase(WebOfTrust.java:676)

my guess would be, that it tries to open a new database in the nix store dir, which is read-only.
