### ISSUE TITLE
Tracking packages that use electron

### ISSUE THREAD

**Issue by IogaMaster** [NixOS/nixpkgs#265125]
## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by IogaMaster** [comment]
This issue is mostly for me, so I can begin work on fixing these packages.

**Comment by eddyb** [comment]
I suspect Electron 25 is largely broken on Wayland w/ fractional scaling, but I'm not 100% sure on the factors.
I first started seeing issues with VSCode:
- https://github.com/NixOS/nixpkgs/issues/237978

When I last checked I couldn't find any relevant Chrome or Electron bug reports, and I've been working around it by both disabling Wayland (`env WAYLAND_DISPLAY= ...`)and passing `--disable-gpu`, for both Obsidian and VSCode.

I don't use other Electron apps, and with bugs like this I'm avoiding them even more.

Maybe if I get weird XWayland (e.g. performance) problems, or text quality, I might try harder to repro with e.g. vscodium (which should allow debugging into Electron/Chromium code, instead of getting useless backtraces).
(it is a bit odd though, that I couldn't reproduce with VSCode on a fresh profile - supposedly it requires multiple windows/actually opening some projects - but Obsidian's single window did cause crashes right away).

**Comment by eddyb** [comment]
Likely relevant:
- https://github.com/electron/electron/issues/39449

**Comment by woffs** [comment]
is this related? (jitsi-meet-electron-2022.10.1 with electron-27.0.0)
```
$ nix run nixpkgs#jitsi-meet-electron 
Electron could not be found. No hard resets for you!
17:35:37.579 › APPIMAGE env is not defined, current application is not an AppImage

(electron:48250): dbind-WARNING **: 17:35:37.622: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
17:35:37.656 › checkForUpdatesAndNotify called, downloadPromise is null
(node:48250) electron: Failed to load URL: file:///home/user/build/index.html with error: ERR_FILE_NOT_FOUND
(Use `electron --trace-warnings ...` to show where the warning was created)
```

**Comment by IogaMaster** [comment]
@woffs What is the last version that worked for you?

**Comment by woffs** [comment]
> @woffs What is the last version that worked for you?

that from nixos-23.05, that is jitsi-meet-electron-2022.10.1 with electron-26.3.0

**Comment by jtrees** [comment]
FYI: Logseq fixed [this issue](https://github.com/logseq/logseq/issues/10681) about [five days ago](https://github.com/logseq/logseq/pull/10689). The latest nightly should include the fix.

I don't know if that's relevant for nixpkgs (probably just have to sit it out and wait for the next stable release) but might help someone who needs a quick workaround.

**Comment by eddyb** [comment]
Regarding the Electron 25 crashes that affected VSCode, I posted this elsewhere:
> I'm increasingly confident Electron 27 (used by VSCode Insiders) fixed the crashes *I* was observing, and I was even able to use my reproducer automation (KWin Window Rules to force maximization states without manually interacting with an app) to make stable VSCode (on Electron 25) not crash.
>
> For both versions of VSCode I was able to get working again, I can confirm fractional scaling support (crisp pixel-perfect font rendering only when a window is fully contained within one monitor, that becomes slightly fuzzy while transiting between monitors).
And I also tested closing/opening windows, and all of that with `window.titleBarStyle` set to both `"native"` and `"custom"` (I normally use `"custom"` but for my crashes I never saw it make a difference).
>
> I wrote up all the details in a much longer comment on the Electron issue: https://github.com/electron/electron/issues/39449#issuecomment-1871357712

Given the workaround works for both crashy apps I use stuck on Electron 25 (VSCode and Obsidian), and Electron 27 fixes those crashes for me (I think Element Desktop also had this problem before it was bumped to Electron 27), the only fix is probably to expedite migrating all Electron apps to at least 27.

**Comment by IogaMaster** [comment]
This sounds like a good idea.
I will draft a plan with pr tracking.

**Comment by xusiai** [comment]
Feishin has been updated to electron 27 [upstream](https://github.com/jeffvli/feishin/issues/383).

**Comment by ciferkey** [comment]
I started working on Feishin [here](https://github.com/NixOS/nixpkgs/compare/master...ciferkey:nixpkgs:master).

It looks like its failing: 
 1. to find the icon file
 2. something with the mesa version its built against being too old

```
❯ feishin
12:22:46.039 › APPIMAGE env is not defined, current application is not an AppImage
Error: Failed to load image from path '/nix/store/07x42k2rgldgrpivmcjvc6alljamsj4l-feishin-0.5.3/share/feishin/app.asar/assets/icons/icon.png'
    at /nix/store/07x42k2rgldgrpivmcjvc6alljamsj4l-feishin-0.5.3/share/feishin/app.asar/dist/main/main.js:14:524522
    at /nix/store/07x42k2rgldgrpivmcjvc6alljamsj4l-feishin-0.5.3/share/feishin/app.asar/dist/main/main.js:14:525223
DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
failed to bind extensions
DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
failed to bind extensions
DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
failed to bind extensions
```

For 1 it looks like the directory might be `app.asar.unpacked` rather than `app.asar`. Does that involve a change somewhere in the `installPhase`?

**Comment by nadir-ishiguro** [comment]
> I started working on Feishin [here](https://github.com/NixOS/nixpkgs/compare/master...ciferkey:nixpkgs:master).
> 
> It looks like its failing:
> 
>     1. to find the icon file
> 
>     2. something with the mesa version its built against being too old
> 
> 
> ```
> ❯ feishin
> 12:22:46.039 › APPIMAGE env is not defined, current application is not an AppImage
> Error: Failed to load image from path '/nix/store/07x42k2rgldgrpivmcjvc6alljamsj4l-feishin-0.5.3/share/feishin/app.asar/assets/icons/icon.png'
>     at /nix/store/07x42k2rgldgrpivmcjvc6alljamsj4l-feishin-0.5.3/share/feishin/app.asar/dist/main/main.js:14:524522
>     at /nix/store/07x42k2rgldgrpivmcjvc6alljamsj4l-feishin-0.5.3/share/feishin/app.asar/dist/main/main.js:14:525223
> DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
> failed to bind extensions
> DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
> failed to bind extensions
> DRI driver not from this Mesa build ('23.1.9' vs '23.3.3')
> failed to bind extensions
> ```
> 
> For 1 it looks like the directory might be `app.asar.unpacked` rather than `app.asar`. Does that involve a change somewhere in the `installPhase`?

Just got here after having the same issue as you do. Was about to open an update request issue. Should I still go forward with that?

**Comment by IogaMaster** [comment]
Go ahead, link this issue as a comment
