### ISSUE TITLE
Python: error when running tests

### ISSUE THREAD

**Issue by erictapen** [NixOS/nixpkgs#26588]
## Issue description

I'm trying to nixify [`gkwebapp`](https://gitlab.com/gnukhata/gkwebapp), the webapp for an FOSS accounting software. In the process of building I encounter the following stack trace. As the error seems to occur in `nix_run_setup.py`, I thought it might be a bug in `nixpkgs`.

```
...
running build_ext
Traceback (most recent call last):
  File "nix_run_setup.py", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 67, in <module>
    """,
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/nix/store/v891hzbmwqn9jqimykfy7qa4b3543pv8-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/command/test.py", line 210, in run
    self.run_tests()
  File "/nix/store/v891hzbmwqn9jqimykfy7qa4b3543pv8-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/command/test.py", line 231, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/nix/store/v891hzbmwqn9jqimykfy7qa4b3543pv8-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/command/test.py", line 42, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/nix/store/v891hzbmwqn9jqimykfy7qa4b3543pv8-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/command/test.py", line 42, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'godown'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/nix/store/vfslyi6039fxw7csjs9mac8hm4cg028w-python2.7-openpyxl-2.3.5/lib/python2.7/site-packages/openpyxl/writer/write_only.py", line 38, in _openpyxl_shutdown
    for path in ALL_TEMP_FILES:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/nix/store/zq0lf0fdc7n12zcdcs2qq3viz6mc87vr-python-2.7.13/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/nix/store/vfslyi6039fxw7csjs9mac8hm4cg028w-python2.7-openpyxl-2.3.5/lib/python2.7/site-packages/openpyxl/writer/write_only.py", line 38, in _openpyxl_shutdown
    for path in ALL_TEMP_FILES:
TypeError: 'NoneType' object is not iterable
builder for ‘/nix/store/cx9jc89bizwxvfh19ppy8p9hzvr6m9i3-python2.7-gkwebapp.drv’ failed with exit code 1
error: build of ‘/nix/store/cx9jc89bizwxvfh19ppy8p9hzvr6m9i3-python2.7-gkwebapp.drv’ failed
```

### Steps to reproduce

Build this nix-expression:

```
with import <nixpkgs> {};

let
  wsgicors = pkgs.python27Packages.buildPythonPackage rec{
    pname = "wsgicors";
    version = "0.7.0";
    name = "${pname}-${version}";
    src = pkgs.fetchurl {
      url = "https://pypi.python.org/packages/0a/94/022f1ca2838e854fd526012d888d50e391a8332b48ee6ad665d75763ebb3/wsgicors-0.7.0.tar.gz";
      sha256 = "169x3w3pny6vw1l4cz9nz7fmzf4bh4wrj814ixa1v5q21zb47ayc";
    };
    buildInputs = with pkgs.python27Packages; [
      nose
    ];
    propagatedBuildInputs = with pkgs.python27Packages; [
      backports_functools_lru_cache
    ];

  };
in
pkgs.python27Packages.buildPythonPackage rec {
  name = "gkwebapp";

  buildInputs = with pkgs.pythonPackages; [
    pyramid
    openpyxl
    pyramid_jinja2
    webob
    waitress
    wsgicors
    requests2
    pillow
    supervisor
    Babel
  ];

  src = fetchFromGitLab {
    owner = "gnukhata";
    repo = "gkwebapp";
    rev = "3.5.2";
    sha256 = "1j4m3cv7acyqd3q27724ivciz74md4c8xkpik4hicwmi9gz74w8h";
  };
}
```

## Technical details

* System: 17.03.git.412b0a1 (Gorilla)
* Nix version: nix-env (Nix) 1.11.10
* Nixpkgs version: "17.03.git.412b0a17aa"
* Sandboxing enabled: build-use-sandbox = false

**Comment by FRidh** [comment]
The issue here is the default test runner. By default we run `python setup.py test` which isn't well defined here it seems. Since you're using `nose` you should likely add 
```nix
checkPhase = ''
  nosetests
'';
```

**Comment by erictapen** [comment]
Nice, that was it. Thanks alot.
