### ISSUE TITLE
OneGadget still broken ?

### ISSUE THREAD

**Issue by Ryzzen** [NixOS/nixpkgs#266289]
### Describe the bug
I'm getting the same bug as the previous issue
```
/nix/store/kggkzxpnp6ywqzr1gza95j8gh8qycn3h-ruby3.1.4-elftools-1.1.0/lib/ruby/gems/3.1.0/gems/elftools-1.1.0/lib/elftools/structs.rb:28:in `new': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /nix/store/jp9jw6qiz4yrjcg5km74ncjni2rhs2xx-ruby3.1.4-bindata-2.4.4/lib/ruby/gems/3.1.0/gems/bindata-2.4.4/lib/bindata/dsl.rb:286:in `block in override_new_in_class'
	from /nix/store/jp9jw6qiz4yrjcg5km74ncjni2rhs2xx-ruby3.1.4-bindata-2.4.4/lib/ruby/gems/3.1.0/gems/bindata-2.4.4/lib/bindata/dsl.rb:283:in `block in override_new_in_class'
	from /nix/store/kggkzxpnp6ywqzr1gza95j8gh8qycn3h-ruby3.1.4-elftools-1.1.0/lib/ruby/gems/3.1.0/gems/elftools-1.1.0/lib/elftools/note.rb:17:in `<module:Note>'
	from /nix/store/kggkzxpnp6ywqzr1gza95j8gh8qycn3h-ruby3.1.4-elftools-1.1.0/lib/ruby/gems/3.1.0/gems/elftools-1.1.0/lib/elftools/note.rb:13:in `<module:ELFTools>'
	from /nix/store/kggkzxpnp6ywqzr1gza95j8gh8qycn3h-ruby3.1.4-elftools-1.1.0/lib/ruby/gems/3.1.0/gems/elftools-1.1.0/lib/elftools/note.rb:4:in `<top (required)>'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /nix/store/kggkzxpnp6ywqzr1gza95j8gh8qycn3h-ruby3.1.4-elftools-1.1.0/lib/ruby/gems/3.1.0/gems/elftools-1.1.0/lib/elftools/sections/note_section.rb:1:in `<top (required)>'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /nix/store/kggkzxpnp6ywqzr1gza95j8gh8qycn3h-ruby3.1.4-elftools-1.1.0/lib/ruby/gems/3.1.0/gems/elftools-1.1.0/lib/elftools/sections/sections.rb:6:in `<top (required)>'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /nix/store/kggkzxpnp6ywqzr1gza95j8gh8qycn3h-ruby3.1.4-elftools-1.1.0/lib/ruby/gems/3.1.0/gems/elftools-1.1.0/lib/elftools/elf_file.rb:4:in `<top (required)>'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /nix/store/kggkzxpnp6ywqzr1gza95j8gh8qycn3h-ruby3.1.4-elftools-1.1.0/lib/ruby/gems/3.1.0/gems/elftools-1.1.0/lib/elftools.rb:2:in `<top (required)>'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /nix/store/vhhh797lg49h8kdfzkrhk3fhzh4pia5w-ruby3.1.4-one_gadget-1.7.2/lib/ruby/gems/3.1.0/gems/one_gadget-1.7.2/lib/one_gadget/helper.rb:8:in `<top (required)>'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /nix/store/vhhh797lg49h8kdfzkrhk3fhzh4pia5w-ruby3.1.4-one_gadget-1.7.2/lib/ruby/gems/3.1.0/gems/one_gadget-1.7.2/lib/one_gadget/logger.rb:5:in `<top (required)>'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /nix/store/vhhh797lg49h8kdfzkrhk3fhzh4pia5w-ruby3.1.4-one_gadget-1.7.2/lib/ruby/gems/3.1.0/gems/one_gadget-1.7.2/lib/one_gadget/cli.rb:5:in `<top (required)>'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/nix/store/wrsxvl654vsq8a70xi1jkv3f46l94ada-ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /nix/store/a3a79cm7b5lfir82q71mjw4pl33aidag-one_gadget-1.7.2/lib/ruby/gems/3.1.0/gems/one_gadget-1.7.2/bin/one_gadget:4:in `<top (required)>'
	from /home/ryzzen/.nix-profile/bin/one_gadget:35:in `load'
	from /home/ryzzen/.nix-profile/bin/one_gadget:35:in `<main>'
```

### Steps To Reproduce
Start one_gadget

### Expected behavior
printing one_gadgets
 

### Notify maintainers
@artemist 

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61, NixOS, 23.11 (Tapir), 23.11.20231104.85f1ba3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(ryzzen): `"home-manager-23.05.tar.gz"`
 - nixpkgs: `/nix/store/c8aplaf4cij0zr4bca19y1k2vi9qhslz-source`
```

**Comment by Ryzzen** [comment]
Nevermind my home manager version was the issue, I switch to github:nix-community/home-manager/master instead of 23.05 and it works much better, sorry for the ping!
