### ISSUE TITLE
nixos/lib test driver: wait_for_unit: error handling, obscure KeyError: 'ActiveState'

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#266690]
### Describe the bug

The error currently does not even elaborate which unit it's been inquiring about, and overall it looks like the test driver is failing, rather than the service being tested:

```
(finished: cleanup, in 0.31 seconds)
Traceback (most recent call last):
  File "/nix/store/vk9z0l2w86w5n0cfmdh5kzpk5qx1blqc-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
...
  File "/nix/store/vk9z0l2w86w5n0cfmdh5kzpk5qx1blqc-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 451, in check_active
    state = info["ActiveState"]
            ~~~~^^^^^^^^^^^^^^^
KeyError: 'ActiveState'
kill vlan (pid 7)
```

One can see the same behaviour in e.g. https://github.com/NixOS/nixpkgs/issues/241938. 

### Steps To Reproduce

This is far from a minimal example, but it works for me:

1. Add `dbd.wait_for_unit("slurmdbd.service")` after https://github.com/NixOS/nixpkgs/blob/edfad58322dae6ceead104134d481f54fe4d62ef/nixos/tests/slurm.nix#L129-L130
2. `nix-build -A nixosTests.slurm` (`nix-build --check -A nixosTests.slurm`) until you observe the driver failing with `KeyError` (the error isn't deterministic)

### Expected behavior

The test work or fail deterministically. Instead of `KeyError` in the driver, a message about the unit should be displayed

### Additional context

I suspect the systemctl might be running into this branch and then we're not seeing the message, because the driver only captures the stdout: https://github.com/systemd/systemd/blob/aa25e19b474bb08ab607b363f83f0626a96c8d85/src/systemctl/systemctl-show.c#L2186-L2188. I couldn't confirm though.

### Notify maintainers

The SLURM test: @markuskowa.
Recently edited `nixos/lib/test-driver/test_driver/machine.py`: @tfc 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by SomeoneSerge** [comment]
Possibly a better reproducer: try `wait_for_unit("multi-user.target")` (or any `.target`). When I run `systemctl show multi-user.target` locally/outsdie the VM I observe `ActiveState=active`. It fails pretty consistently inside the VM for me
