### ISSUE TITLE
Android Emulator not working on NixOS unstable

### ISSUE THREAD

**Issue by mairs8** [NixOS/nixpkgs#267176]
### Describe the bug
I am trying to run emulator in android studio but getting error "The emulator process for AVD has terminated". I have installed the `android-studio` package in home-manger. Android studio opens but it is just the emulator that is not working.

Is there any additional configuration i need to declare in my nix files in order to get the emulator to run?

### Steps To Reproduce
1. Add `android-studio` package to home-manager and run `home-manager switch`.
2. Launch Android Studio.
3. Open new project. 
4. Run app

### Expected behavior
Android Emulator should launch and show on screen. 

### Notify maintainers
@alapshin

### Metadata
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61, NixOS, 23.11 (Tapir), 23.11.20231104.85f1ba3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Some other points that I think could be causing the issue:
- do i need to change any environment variables.
- do i need to change any setting in android studio e.g. to make sure it works with the nixos file hierachy.
- i do not have Wifi working. i know this is needed for a physical device but didn't think i need this for an avd.
- I am using hyprland desktop which is Wayland compositor (the emulator was working on my arch + hyprland setup however).
- I am using flakes and home-manager.

**Comment by MikaelFangel** [comment]
I've just tested on my android-studio setup (stable-channel) and it works as expected. Can you provide some more info and preferably a log file showing the error?

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61, NixOS, 23.11 (Tapir), 23.11.20231104.85f1ba3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `""`
 - channels(mikael): `""`
 - nixpkgs: `/nix/store/kcmipm57ph9bpzz8bs80iiijiwbyzwy3-source`
```

**Comment by mairs8** [comment]
I have added system info at the top. How can i add a log file? 

On the official android site it mentions you can run `emulator -avd avd_name -gpu mode' but when i run this in my terminal i get 'emulator command not found'. Do i need any other packages/configuration on top of `android-studio` for the emulator to work? I feel like i am missing something basic.

**Comment by MikaelFangel** [comment]
I'm a bit confused. Are you trying to run it from the commandline or through the terminal? I assume, based on your initial post, you are trying to get it up and running inside android studio. By that assumption, my next question is: Did you follow the steps for installing a virtual machine? ([https://developer.android.com/studio/run/managing-avds#createavd](https://developer.android.com/studio/run/managing-avds#createavd))

**Comment by mairs8** [comment]
yes I followed the guidelines to create virtual device in android studio. I only mentioned the command line as I was trying different options/debugging. 

I tried getting an error log from android studio but it doesn't show anything in the logcat. It looks like it is not even able to connect to the avd and hence no error log. 

Some other points that I think could be causing the issue:
- do i need to change any environment variables.
- do i need to change any setting in android studio e.g. to make sure it works with the nixos file hierachy.
- i do not have Wifi working. i know this is needed for a physical device but didn't think i need this for an avd. 
- I am using hyprland desktop which is Wayland compositor (the emulator was working on my arch + hyprland setup however).
- I am using flakes and home-manager.

Are you able to share the working .nix xonfiguration you are using? If this doesn't work on my machine then I can only imagine it is something outside of nix configuration (android studio settings/environment variables).

**Comment by mairs8** [comment]
@MikaelFangel so i managed to get an error log by going to Android/Sdk/emulator and running `./emulator @Pixel_5_API_33`. It gives me the below output:

`Android/Sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory`

Still not sure what to do with this.... it looks like i am missing a dependency?

**Comment by MikaelFangel** [comment]
@mairs8 you can find my config [here](https://github.com/MikaelFangel/.dotfiles), but I'm not sure if it helps.

It's a bit difficult to debug as I can't replicate the issue, but it helps that you have posted the log. Thanks (:

**Comment by Casul51** [comment]
Here is my error :)
```
~ ➤ android-studio
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
2024-01-14 07:07:06,590 [    564]   WARN - #c.i.o.v.n.p.l.VfsLog - VFS Log version differs from the implementation version: log null vs implementation -43
2024-01-14 07:07:06,823 [    797]   WARN - #c.i.o.a.i.ActionManagerImpl - keymap "VSCode" not found PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, descriptorPath=plugin.xml, path=/nix/store/51qj1qsns3arj8lj3izngkb7vxk1zcnw-android-studio-stable-2023.1.1.26-unwrapped/plugins/terminal, version=231.9392.1.2311.11076708, package=null, isBundled=true)
2024-01-14 07:07:06,907 [    881]   WARN - #c.i.n.i.NotificationGroupManagerImpl - Notification group Logcat is already registered (group=com.intellij.notification.NotificationGroup@4193f6c6). Plugin descriptor: PluginDescriptor(name=Android, id=org.jetbrains.android, descriptorPath=plugin.xml, path=/nix/store/51qj1qsns3arj8lj3izngkb7vxk1zcnw-android-studio-stable-2023.1.1.26-unwrapped/plugins/android, version=231.9392.1.2311.11076708, package=null, isBundled=true)
2024-01-14 07:07:12,285 [   6259]   WARN - #com.android.ddmlib - * daemon not running; starting now at tcp:5037
2024-01-14 07:07:12,532 [   6506]   WARN - #com.android.ddmlib - * daemon started successfully
2024-01-14 07:07:15,010 [   8984] SEVERE - Emulator: Pixel 7 API 34 - Emulator terminated with exit code 1
java.lang.Throwable: Emulator terminated with exit code 1
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
        at com.android.tools.idea.avdmanager.EmulatorProcessHandler$ConsoleListener.onTextAvailable(EmulatorProcessHandler.kt:89)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:252)
        at jdk.proxy2/jdk.proxy2.$Proxy36.onTextAvailable(Unknown Source)
        at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:226)
        at com.intellij.execution.process.ProcessTerminatedListener.processTerminated(ProcessTerminatedListener.java:56)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:252)
        at jdk.proxy2/jdk.proxy2.$Proxy36.processTerminated(Unknown Source)
        at com.intellij.execution.process.ProcessHandler.lambda$notifyTerminated$2(ProcessHandler.java:210)
        at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:285)
        at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:193)
        at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:189)
        at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
        at com.intellij.execution.process.BaseOSProcessHandler$1.lambda$startNotified$0(BaseOSProcessHandler.java:84)
        at com.intellij.execution.process.ProcessWaitFor.lambda$new$0(ProcessWaitFor.java:45)
        at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
        at com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:23)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
        at java.base/java.lang.Thread.run(Thread.java:833)
2024-01-14 07:07:15,014 [   8988] SEVERE - Emulator: Pixel 7 API 34 - Android Studio Hedgehog | 2023.1.1  Build #AI-231.9392.1.2311.11076708
2024-01-14 07:07:15,014 [   8988] SEVERE - Emulator: Pixel 7 API 34 - JDK: 17.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-01-14 07:07:15,015 [   8989] SEVERE - Emulator: Pixel 7 API 34 - OS: Linux
2024-01-14 07:07:15,017 [   8991]   WARN - #c.i.u.j.JBCefApp - JCefAppConfig.class is not from a JBR module, url: jar:file:/nix/store/51qj1qsns3arj8lj3izngkb7vxk1zcnw-android-studio-stable-2023.1.1.26-unwrapped/lib/app.jar!/com/jetbrains/cef/JCefAppConfig.class (Use JBR bundled with the IDE)

```

**Comment by Casul51** [comment]
I was wrong. I forgot to update my flake (again) and in unstable all works fine

**Comment by kirillrdy** [comment]
android studio was recently updated and emulator worked ( at least for me )
https://github.com/NixOS/nixpkgs/pull/292501#pullrequestreview-1910729547

feel free to reopen if there are issues

**Comment by ShreyBana** [comment]
Running into the same issue as the OP. 
nix-info:
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.84, NixOS, 24.05 (Uakari), 24.05pre609462.4cba8b53da47`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(shrey_bana): `"home-manager"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 
Android studio(canary) is installed via home manager.
I tried to run emulator via cli:
```
./emulator -list-avds
./emulator: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
```
Seems like it can't find libx11. Any suggestions ?

**Comment by kirillrdy** [comment]
@ShreyBana can you test https://github.com/NixOS/nixpkgs/pull/303462

**Comment by kirillrdy** [comment]
> @ShreyBana can you test #303462

also how are you running ? `./emulator -list-avds` this will not work unless you run it from inside of android-studio

**Comment by ShreyBana** [comment]
@kirillrdy Yeah so I just did a fresh install & I think I used to be able to run it, but that was maybe w/ `steam-run`. It's been a while since I've had to run it with cli so I just thought it's supposed to run as is. My bad there :(
Also I see that #303462 is merged to master, so just upgrading should work right ?

**Comment by kirillrdy** [comment]
@ShreyBana steam-run not going to work anymore, but it should work from android-studio, you can also use terminal from inside android-studio to run `./emulator -list-avds`

as for that PR 
it's in master but not yet in unstable 

you can track progress here https://nixpk.gs/pr-tracker.html?pr=303462

**Comment by ShreyBana** [comment]
@kirillrdy #303462 is working! Thanks for the help!!!

**Comment by sjcobb2022** [comment]
For those running on wayland (hyprland for me), you will need to run `QT_QPA_PLATFORM=xcb android-studio` because the wayland qpa platform does not work.

**Comment by kirillrdy** [comment]
> For those running on wayland (hyprland for me), you will need to run `QT_QPA_PLATFORM=xcb android-studio` because the wayland qpa platform does not work.

maybe we can add something to wrapper to make this automatic, thoughts ? @sjcobb2022

**Comment by sjcobb2022** [comment]
I realise now that this is because I override QT_QPA_PLATFORM=wayland in my config. For those who have this variable set, it is necessary to override it.

You can do this with the previous solution, or something like `env -u QT_QPA_PLATFORM android-studio`

**Comment by kirillrdy** [comment]
@sjcobb2022 ok, i see, I think for now, no action will be taken, and hopefully this information helps others

**Comment by kjkent** [comment]
Ran into this just now, it seems setting `QT_QPA_PLATFORM` is recommended for Wayland compatibility, but it's incompatible with Android Studio... +1 for the idea of a wrapper fix (unless wayland is entirely broken as an option for `QT_QPA_PLATFORM` ofc)
