### ISSUE TITLE
awscli2-2.13.33 failing due to urllib3 2.0

### ISSUE THREAD

**Issue by fitzgibbon** [NixOS/nixpkgs#267864]
### Describe the bug
In nixpkgs-unstable, `awscli` is broken because it has pulled in `urllib3` 2.0 which it doesn't yet support. In the source for `awscli2`, the derivation attempts to override `urllib3` to an older version (1.26.18) but this doesn't seem to work. I'm not sure why.

The end result is that when running `awscli2` I receive the following error and no commands are processed:
```
❯ aws
Traceback (most recent call last):
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/bin/.aws-wrapped", line 20, in <module>
    import awscli.clidriver
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/lib/python3.11/site-packages/awscli/clidriver.py", line 21, in <module>
    import botocore.session
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/session.py", line 27, in <module>
    import botocore.client
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/client.py", line 16, in <module>
    from botocore import UNSIGNED, waiter, xform_name
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/waiter.py", line 17, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/docs/client.py", line 16, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/utils.py", line 33, in <module>
    import botocore.httpsession
  File "/nix/store/p24hwf6pycs9h8rsm2fq5iflc8abhw29-awscli2-2.13.33/lib/python3.11/site-packages/awscli/botocore/httpsession.py", line 21, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/nix/store/2h9jfrb402bfga02h9v1m2wfrjrrsj17-python3.11-urllib3-2.0.5/lib/python3.11/site-packages/urllib3/util/ssl_.py)
```

### Steps To Reproduce
1. Install `awscli2` from `nixpkgs-unstable`.
2. Run `awscli2` with any command-line parameters.
3. Observe error text.

### Expected behavior
`awscli2` should function as intended.

### Notify maintainers
@bhipple @davegallant @bryanasdev000 @devusb @anthonyroussel

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these 6 paths will be fetched (0.96 MiB download, 10.18 MiB unpacked):
  /nix/store/h5pshzq92r2xcv6w1p10cmkar4nyv0xp-file-5.45
  /nix/store/azkk9647ivcaa29fpb8viwj879q7yjw4-gnu-config-2023-07-31
  /nix/store/9dh2csn531by6b1vr9jv85v4k17xwkid-gnumake-4.4.1
  /nix/store/znqwpxy9jlxcgi2ms2hga0ch87bbbr9g-patchelf-0.15.0
  /nix/store/bbxdw4rgwwl3gnajri82yidr1nlsfskf-stdenv-linux
  /nix/store/6g3mnziija245czxdqvs4k4sc6lad0sw-update-autotools-gnu-config-scripts-hook
copying path '/nix/store/azkk9647ivcaa29fpb8viwj879q7yjw4-gnu-config-2023-07-31' from 'https://cache.iog.io'...
copying path '/nix/store/h5pshzq92r2xcv6w1p10cmkar4nyv0xp-file-5.45' from 'https://cache.iog.io'...
copying path '/nix/store/9dh2csn531by6b1vr9jv85v4k17xwkid-gnumake-4.4.1' from 'https://cache.iog.io'...
copying path '/nix/store/znqwpxy9jlxcgi2ms2hga0ch87bbbr9g-patchelf-0.15.0' from 'https://cache.iog.io'...
copying path '/nix/store/6g3mnziija245czxdqvs4k4sc6lad0sw-update-autotools-gnu-config-scripts-hook' from 'https://cache.iog.io'...
copying path '/nix/store/bbxdw4rgwwl3gnajri82yidr1nlsfskf-stdenv-linux' from 'https://cache.iog.io'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1, NixOS, 23.11 (Tapir), 23.11.20231115.592047f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(niall): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FliegendeWurst** [comment]
(all tests done on nixpkgs master)

The overrides seem to work. `strace aws 2>&1 | rg urllib3` reports `/nix/store/ikc6ld5g58ky0xqkcq8bq3af0jqlmcbj-python3.11-urllib3-2.0.5/lib/python3.11/site-packages`. The store path has a misleading name since only the src attribute is overriden (not the version).

Contents of `/nix/store/ikc6ld5g58ky0xqkcq8bq3af0jqlmcbj-python3.11-urllib3-2.0.5/lib/python3.11/site-packages/urllib3/_version.py`: `__version__ = "1.26.18"`

> `/nix/store/2h9jfrb402bfga02h9v1m2wfrjrrsj17-python3.11-urllib3-2.0.5/`

I'm not sure where this store path comes from. It might be from the default Python 3 pkgs set.

How did you install awscli2 from nixpkgs-unstable?

**Comment by fitzgibbon** [comment]
You're right, and now that I run strace I see it actually using the wrong urllib3. Some more investigation revealed the problem was with my `PYTHONPATH` that I had set to include a different copy of urllib3 that I had installed. So there's no problem at all -- sorry for the time waste!

**Comment by mplanchard** [comment]
This seems to be a problem if you have both python packages installed via nix (which set PYTHONPATH) and the AWS CLI installed. Anyone know of a workaround for that?

**Comment by mplanchard** [comment]
Worked around with:

```nix
{ config, lib, pkgs, ... }:

pkgs.awscli2.overrideAttrs (oldAttrs: {
  nativeBuildInputs = oldAttrs.nativeBuildInputs ++ [ pkgs.makeWrapper ];

  doCheck = false;

  # Run any postInstall steps from the original definition, and then wrap the
  # aws program with a wrapper that sets the PYTHONPATH env var to the empty
  # string
  postInstall = ''
    ${oldAttrs.postInstall}
    wrapProgram $out/bin/aws --set PYTHONPATH=
  '';
})
```

**Comment by pmorch** [comment]
May I ask: How is this fixed?

If I enter a `nix-shell` with this `shell.nix`:

```
let
  unstable = import (fetchTarball https://github.com/NixOS/nixpkgs/tarball/nixos-unstable/) {};
in
unstable.mkShellNoCC {
  packages = with unstable; [
    borgmatic
    awscli2
  ];
}
```

As far as I can tell, even on unstable it only works if I use `PYTHONPATH= aws`, which I hope we agree is broken.

My newbie assumption (that I'm too newbie to test) is that if this got fixed on Nov 16, 2023, the fix would have made it to unstable by now.

```
$ nix-shell --run 'PYTHONPATH= aws --version'
aws-cli/2.15.43 Python/3.11.9 Linux/6.1.87 source/x86_64.nixos.23 prompt/off

$ nix-shell --run 'aws --version'            
Traceback (most recent call last):
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/bin/.aws-wrapped", line 20, in <module>
    import awscli.clidriver
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/lib/python3.11/site-packages/awscli/clidriver.py", line 21, in <module>
    import botocore.session
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/lib/python3.11/site-packages/awscli/botocore/session.py", line 27, in <module>
    import botocore.client
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/lib/python3.11/site-packages/awscli/botocore/client.py", line 16, in <module>
    from botocore import UNSIGNED, waiter, xform_name
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/lib/python3.11/site-packages/awscli/botocore/waiter.py", line 17, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/lib/python3.11/site-packages/awscli/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/lib/python3.11/site-packages/awscli/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/lib/python3.11/site-packages/awscli/botocore/docs/client.py", line 16, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/lib/python3.11/site-packages/awscli/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/lib/python3.11/site-packages/awscli/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/lib/python3.11/site-packages/awscli/botocore/utils.py", line 35, in <module>
    import botocore.httpsession
  File "/nix/store/w76l4fpgnlakpzm6cp4780p26lyb7fy9-awscli2-2.15.43/lib/python3.11/site-packages/awscli/botocore/httpsession.py", line 21, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/nix/store/sq2gpzqg6l4pv0saazr3kr1sqmyr06a3-python3.11-urllib3-2.2.1/lib/python3.11/site-packages/urllib3/util/ssl_.py)
```

**Comment by MatthiasScholzTW** [comment]
It is still an issue for:
`aws-cli/2.17.13 Python/3.11.9 Darwin/23.5.0 source/arm64`

**Comment by asimpson** [comment]
Just ran into this for the first time. I resolved it by adding this to my `shell.nix`:

```nix
  shellHook = ''
    export PYTHONPATH=""
  '';
```
