### ISSUE TITLE
John - ssh2john: AttributeError: module 'base64' has no attribute 'decodestring'

### ISSUE THREAD

**Issue by ca5ua1** [NixOS/nixpkgs#267978]
### Describe the bug
ssh2john produce error while trying to process ssh key 

### Steps To Reproduce
1. Install john in any way - `nix-shell -p john`
2. Generate ssh key with password - `ssh-keygen  -f ./id_test`
3. run - `ssh2john.py ./id_test` 

### Expected behavior
KALI:
```
$ ssh-keygen  -f ./id_rsa
Generating public/private rsa key pair.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in ./id_rsa
Your public key has been saved in ./id_rsa.pub
The key fingerprint is:
SHA256:YSodrYxUJ1T1O9iK5Gtg3Ry4QWCDl0ZD/gM6oi/8JWA casual@kali
The key's randomart image is:
+---[RSA 3072]----+
|     =@+o..      |
|    .++*.  .     |
|    .o+.+.  .    |
|   . = Bo..o .   |
| E. = =.S=..+    |
|.... oooooo. .   |
|o  . o .o .      |
|.o  o   ..       |
| .o.   ..        |
+----[SHA256]-----+

kali% ssh2john  ./id_rsa
./id_rsa:$sshng$6$16$bfb281aa033491761246051e98e0cdea$1894$6f70656e7373682d6b65792d7631000000000a6165733235362d637472000000066263727970740000001800000010bfb281aa033491761246051e98e0cdea000000180000000100000197000000077373682d727361000000030100010000018100ba09be022e5d14ec5d787bd3ddd6495674de42ecde262418db1906558e6a0d1973f1996ff51ab1e2310462d56ba6bff59044cbf5311c6a03be1c6a1d78880ed879c40d0aa2bbe466084d01d197aad53908e4d03044bc4797eed6f8f880c583fe6ec5159f91662f237772828162fed881398b73fb22f473f3e1850bbde3180e6fe1659f0882eeeb243de29e08ec49ebdb63c571de7e4950c1bdfe70f32e0c2aa307ea3ab3f705bb42d1fc63695a20437fa615ddc2a44451de17d5ce81943b583efc29459fc7bec3081161dec237660ab9f9621b4b6c2e151adfefe6d1da94d7214e3c27f63b2a8cf1ed7c8d4b2b85b210fcadba406ff4b8407292e2151b0546fee2d1c090c6aa806eaab9478df9f69fa94df31a87bcdc1d94caedca2dc5a18a538927b4e78e4f0f0ea3c3a79a0bc2a6c2dcbfc4bdc6c1669035ea10b81505fe69d54f4a21b922c02a67cc571ef5ea90e7763b79efbfe59ae7220e4e22d7bfd1442c561f3ec16dab0df6c3f9b375248aa800a10140cba4cb609fed2a68fc9ae88f000005805cb2a240fa5d0f4c8f15e25fee453341f29f9a50ebe2eb2399462bbc0b45f505081f52c11be73a65f3daf466a166d43ac4e02d1db7ea10a66e943d9378be50fc7c06c061db6f46852f4e291fe4fbf59c7540f09e86c810570ec8ff674d3c4da8f88cfa35a65cacf80d9f475d0d79a28d62e355f6bdbe03db19fdb766dcb5363f34ae886e786cf4275cc91c3139e6b17516f03ffc32c90698bdd9c9ec162d37bace397206f5dac7299281386b142ea790e434bf9fc0e6da33553bd93e6ebb33539933689303704027b0e6eeecbac1fcb2290a7c2582b295504d083e8fc370dd32326ae5e08a7d458085cca2853f0c283532bde49ff3e455ce0bc1f0faca6f48db04d293a50d3502062011881393f57e93d1573119ca301bd6e101c6ad61bfa4ff5d644e4091de82f38824b747c24c938edb828faa1c474d507a5234482d4e6f06672f1f9180415796d842c5c4eeb08f548dafc661e9b57b544783fc9113e964411e309743c140069ce32de817377d7436d3c9bf296d8200bd83d2075888b8197dd2cda5718683beb0c05f10ee8a4919bbc71e9061575e25551be7fb50fbc6643a5dc11d069f1038b0d198a41c402d2f822dc095a32c5898c94a89dfe9388b3449fc58b3755678519877527cc0aa35a4e859278dc1e979e2fcebc10e08a47f0480422986cc1b9012e15db319a728473f278f01a01155c22e42223e1e7c95d96a4bb9d7bdab26090f71e54bc7c917e47ba0c03e0489ec0e790a7a60bb4673970b5e868f82bdd4484aaff2e42caee23e6145ca1c6c2c103e1dc8418a25727e8b3b9471a052bb342a3b48056536d770f342329bb1aa7aa27502fbbe42e67a997087f4f8023e53b7037ae30b774fe867d59aefd90c94f071a43fcb4342cd7b4621bb0cb4340df0a7cc39e3017c8f169070ed9d26ab378b26bc24c7f70c6874b11d940e56eb5b7e0301b098ccc7025312188e60e1887e3d91890c1d234a9ecbc075ec067370e419d7c947e0339c594a9a261e32a8963bce7bcb401bbdb54fdfafa4b7354c346a888afcbd2dba4c681fd31fa70052fc61462e4b9e8096c34913d6f745989ce1c34a91eeff22ebf05fd30c0664c996e975ff4bbc9d1b553f2f2933103503bdd8e7f1991ddd5d54b88516f0e3529170e2b91db1a20377e03ec83fb7486c4a9ee1897cb94c6911774ad6b8ce7b028ddc6146eeab23d74ca194e64b9d6cab3b8c71659edb97512476f99792c6874b9c66c23de9e036b107c1c8ff0bf82afcf28a769ec1e2b18df09f17c6fec237ce19b21cf5c7d60c2e9647e05df53faa2088c5adb0ea9dd495e8362c7e96cfb69c0b1d87b0dd75ae61dfc7f8ee4460e8a635adddcb0ff2c45da66f354f29925cf3c94bacbed8947e75bced86388c848b88e29e25cd7ce2d6159b6d2bacf25b30e24a41eeb87c39d9f7fcbab01996ca299421c73f016403d350465c5035fe3a9e72d11b7cee5c494d38278aaabc3b496bf6b742a4d4c19690ba4d81949c5b2f44ea88b9b8127c33b3b42c47f79d3cba5dc74c417f0f12805882b19f2481a85bf53c80a58889aabe4fe75dc3fc4e02e0054c3daf2281d9f101c3301671fcd356e4227977858fee5d8febd49fef5db795b173a3e5d781d15840ba14806c2396f999aad9e4af5ef04a9dbab749a5710d063a36fc0e174ad2656a39ebf1b139006cd560bc4c6fbfed2a576232c510de19519e19ea8214542046eac23819922523e1c1d0a6d9d0f3335fdcf49a94077a9561e68c75b09c11db4e198cb781da9225f3552aaba34ade79c5f47166fc53678b7f1861ba3bf444bfd8d4e788ed93a572318eb5926c3398e3d01c8404a4e8f3ba5f7d6f28fcd9f1edc1aad4571351979c29d9ed9ca35b7f6a26879074e4ba7fb45855c9107d64c6add526294f97fccffb548f93963180adcb59779ddb41af4c655a9a1128292d899b5c8b734ad943227301ee1b51218c51f29dd4bc973615d15e0dc2b74f$24$486

```

### Screenshots
```
tmp ➤ ssh-keygen  -f ./id_rsa -t rsa
Generating public/private rsa key pair.
./id_rsa already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in ./id_rsa
Your public key has been saved in ./id_rsa.pub
The key fingerprint is:
SHA256:Cj13/mPjbTBnT0zKOA94Otz8MQNkPxiEZO8TgcCoaiU casual@Casual-PC
The key's randomart image is:
+---[RSA 3072]----+
|       o.oooo    |
|      . ..oo .   |
|     .      *    |
|  E o.     + =  .|
|   +. o S ..=oo+ |
|  o  . + o. Bo=.o|
| .    .  ..= O+o |
|          +.*.o+.|
|           +o=o  |
+----[SHA256]-----+
tmp ➤ ssh2john.py  ./id_rsa
Traceback (most recent call last):
  File "/nix/store/vprysv8g6xxzn5y56ndhqz3dk77l5inn-john-1.9.0-jumbo-1/bin/.ssh2john.py-wrapped", line 194, in <module>
    read_private_key(filename)
  File "/nix/store/vprysv8g6xxzn5y56ndhqz3dk77l5inn-john-1.9.0-jumbo-1/bin/.ssh2john.py-wrapped", line 104, in read_private_key
    data = base64.decodestring(data)
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'base64' has no attribute 'decodestring'

```

### Notify maintainers

@offlinehacker 
@matthewbauer 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1-zen1, NixOS, 23.11 (Tapir), 23.11.20231112.e44462d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05, nixpkgs"`
 - channels(casual): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by h7x4** [comment]
This seems like an upstream issue. [`base64.decodestring` has been deprecated since python 3.1 and was removed completely in python 3.9](https://github.com/python/cpython/issues/83532)

See https://github.com/openwall/john/issues/4564

**Comment by Casul51** [comment]
This issue 2 years long!

Can we bundle older python with john or apply workaround stated in mentioned issue?

`$ sed 's/decodestring/decodebytes/' /usr/bin/ssh2john | python3.9 - id_rsa`

**Comment by h7x4** [comment]
In the meantime, I believe you should be able to work around this by overriding the python version locally:

```shell
nix-shell -p 'john.override { python3Packages = python39Packages; }'
```
