### ISSUE TITLE
Package Python Playwright with Browser

### ISSUE THREAD

**Issue by Yubo-Cao** [NixOS/nixpkgs#268004]
### Describe the bug
When using `playwright` package from `python311Packages`, Playwright could not detect the browser to use in the NixOS, despite being installed.

### Steps To Reproduce

```nix
{ pkgs, ... }: {
  home.packages = with pkgs;
    [
      (python311.withPackages (ps:
        with ps; [
          jupyter
          playwright
        ]))
      chromium
    ];
}
```

Afterward, create some notebook file `.ipynb`. Then run `jupyter nbconvert main.ipynb --to webpdf`

Then

```
RuntimeError: No suitable chromium executable found on the system. Please use '--allow-chromium-download' to allow downloading one,or install it using `playwright install chromium`.
```

Obviously `playwright install chromium` won't work on NixOS.

### Expected behavior

I expect the above command to convert `webpdf`

### Notify maintainers

@techknowlogick @yrd @SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.11-xanmod1, NixOS, 23.11 (Tapir), 23.11.20231112.e44462d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment]
you could do as here https://github.com/NixOS/nixpkgs/blob/b6ed7946a7917d29df2c3979b0b7c230f727119b/pkgs/development/web/playwright-test/wrapped.nix#L24 I suppose.

**Comment by Yubo-Cao** [comment]
I don't see how I can override `browsers` attribute from `playwright-driver`? Technically speaking, isn't it supposed to work already since Chromium seems to be packaged with a playwright?

**Comment by BenediktSeidl** [comment]
This problem still persists.

When executing 
```
python -c "
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    p.firefox.launch()"
```

The following error will be shown:

```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/nix/store/1aw5hsnk4pqf1wy3chm32gf1rshingnz-python3-3.12.8-env/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 14440, in launch
    self._sync(
  File "/nix/store/1aw5hsnk4pqf1wy3chm32gf1rshingnz-python3-3.12.8-env/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/nix/store/1aw5hsnk4pqf1wy3chm32gf1rshingnz-python3-3.12.8-env/lib/python3.12/site-packages/playwright/_impl/_browser_type.py", line 95, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1aw5hsnk4pqf1wy3chm32gf1rshingnz-python3-3.12.8-env/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1aw5hsnk4pqf1wy3chm32gf1rshingnz-python3-3.12.8-env/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/name/.cache/ms-playwright/firefox-1465/firefox/firefox
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
```

My current workaround is (as teto indicated):

```
{
  description = "playwright";
  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        devShells.default = pkgs.mkShell {
          PLAYWRIGHT_BROWSERS_PATH = "${pkgs.playwright-driver.passthru.browsers}";  # <---- FIX
          buildInputs = [
            (pkgs.python3.withPackages (
              python-pkgs: with python-pkgs; [
                playwright
              ]
            ))
          ];
        };
      }
    );
}
```

**Comment by BedHedd** [comment]
I am also experiencing this issue. I think it is because the browsers.json file is out of sync with my local drivers. Is there a nix command to manually to download and update the drivers stored in `pkgs.playwright-driver.browsers`? 

## error encountered
When i run this code in a jupyter notebook in uv, 
```py
from playwright.async_api import async_playwright
async with async_playwright() as p:
    browser = await p.chromium.launch(headless=False)
    page    = await browser.new_page()
    await page.goto("https://nixos.org")
    print("Title:", await page.title())
    await browser.close()
```
I get the following error
```py
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Cell In[16], line 3
      1 from playwright.async_api import async_playwright
      2 async with async_playwright() as p:
----> 3     browser = await p.chromium.launch(headless=False)
      4     page    = await browser.new_page()
      5     await page.goto("https://nixos.org/")

File ~/Documents/development_projects/bedhedd_projects/playwright-debug/.venv/lib/python3.13/site-packages/playwright/async_api/_generated.py:14438, in BrowserType.launch(self, executable_path, channel, args, ignore_default_args, handle_sigint, handle_sigterm, handle_sighup, timeout, env, headless, devtools, proxy, downloads_path, slow_mo, traces_dir, chromium_sandbox, firefox_user_prefs)
  14317 async def launch(
  14318     self,
  14319     *,
   (...)  14340     ] = None,
  14341 ) -> "Browser":
  14342     """BrowserType.launch
  14343 
  14344     Returns the browser instance.
   (...)  14434     Browser
  14435     """
  14437     return mapping.from_impl(
> 14438         await self._impl_obj.launch(
  14439             executablePath=executable_path,
  14440             channel=channel,
  14441             args=mapping.to_impl(args),
  14442             ignoreDefaultArgs=mapping.to_impl(ignore_default_args),
  14443             handleSIGINT=handle_sigint,
  14444             handleSIGTERM=handle_sigterm,
  14445             handleSIGHUP=handle_sighup,
  14446             timeout=timeout,
  14447             env=mapping.to_impl(env),
  14448             headless=headless,
  14449             devtools=devtools,
  14450             proxy=proxy,
  14451             downloadsPath=downloads_path,
  14452             slowMo=slow_mo,
  14453             tracesDir=traces_dir,
  14454             chromiumSandbox=chromium_sandbox,
  14455             firefoxUserPrefs=mapping.to_impl(firefox_user_prefs),
  14456         )
  14457     )

File ~/Documents/development_projects/bedhedd_projects/playwright-debug/.venv/lib/python3.13/site-packages/playwright/_impl/_browser_type.py:98, in BrowserType.launch(self, executablePath, channel, args, ignoreDefaultArgs, handleSIGINT, handleSIGTERM, handleSIGHUP, timeout, env, headless, devtools, proxy, downloadsPath, slowMo, tracesDir, chromiumSandbox, firefoxUserPrefs)
     93 params = locals_to_params(locals())
     94 normalize_launch_params(params)
     95 browser = cast(
     96     Browser,
     97     from_channel(
---> 98         await self._channel.send(
     99             "launch", TimeoutSettings.launch_timeout, params
    100         )
    101     ),
    102 )
    103 browser._connect_to_browser_type(
    104     self, str(tracesDir) if tracesDir is not None else None
    105 )
    106 return browser

File ~/Documents/development_projects/bedhedd_projects/playwright-debug/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:69, in Channel.send(self, method, timeout_calculator, params, is_internal, title)
     61 async def send(
     62     self,
     63     method: str,
   (...)     67     title: str = None,
     68 ) -> Any:
---> 69     return await self._connection.wrap_api_call(
     70         lambda: self._inner_send(method, timeout_calculator, params, False),
     71         is_internal,
     72         title,
     73     )

File ~/Documents/development_projects/bedhedd_projects/playwright-debug/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:558, in Connection.wrap_api_call(self, cb, is_internal, title)
    556     return await cb()
    557 except Exception as error:
--> 558     raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
    559 finally:
    560     self._api_zone.set(None)

Error: BrowserType.launch: Executable doesn't exist at /nix/store/42axmwmwydsh8kzznd1mz7lnmg0a1zkk-playwright-browsers/chromium-1179/chrome-linux/chrome
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
```

## local code patch
I can make the error go away if I set a custom executable path. I reuse the environment variable set as `PLAYWRIGHT_BROWSERS_PATH =  "${pkgs.playwright-driver.browsers}";` per the wiki's instructions
https://wiki.nixos.org/wiki/Playwright#Installing_browsers_for_playwright_under_NixOS
```PY
playwright_browsers_path = os.environ['PLAYWRIGHT_BROWSERS_PATH']
firefox_executable_path = os.path.join(playwright_browsers_path, "firefox-1482", "firefox", "firefox")
firefox_executable_path
```
prints
```
'/nix/store/42axmwmwydsh8kzznd1mz7lnmg0a1zkk-playwright-browsers/firefox-1482/firefox/firefox'
```
```py
from playwright.async_api import async_playwright
async with async_playwright() as p:
    browser = await p.firefox.launch(headless=False, executable_path=firefox_executable_path)
    page    = await browser.new_page()
    await page.goto("https://nixos.org")
    print("Title:", await page.title())
    await browser.close()
```
This codeblock returns 
```
Title: Nix & NixOS | Declarative builds and deployments
```
rather than the error

## further digging
I did some digging and I found that the python playwright api will store the available browsers in `./.venv/lib/python3.13/site-packages/playwright/driver/package/browsers.json`. 

```json
{
  "comment": "Do not edit this file, use utils/roll_browser.js",
  "browsers": [
    {
      "name": "chromium",
      "revision": "1179",
      "installByDefault": true,
      "browserVersion": "138.0.7204.23"
    },
    {
      "name": "chromium-headless-shell",
      "revision": "1179",
      "installByDefault": true,
      "browserVersion": "138.0.7204.23"
    },
    {
      "name": "chromium-tip-of-tree",
      "revision": "1337",
      "installByDefault": false,
      "browserVersion": "139.0.7216.0"
    },
    {
      "name": "chromium-tip-of-tree-headless-shell",
      "revision": "1337",
      "installByDefault": false,
      "browserVersion": "139.0.7216.0"
    },
    {
      "name": "firefox",
      "revision": "1488",
      "installByDefault": true,
      "browserVersion": "139.0"
    },
    {
      "name": "firefox-beta",
      "revision": "1482",
      "installByDefault": false,
      "browserVersion": "138.0b10"
    },
    {
      "name": "webkit",
      "revision": "2182",
      "installByDefault": true,
      "revisionOverrides": {
        "debian11-x64": "2105",
        "debian11-arm64": "2105",
        "mac10.14": "1446",
        "mac10.15": "1616",
        "mac11": "1816",
        "mac11-arm64": "1816",
        "mac12": "2009",
        "mac12-arm64": "2009",
        "mac13": "2140",
        "mac13-arm64": "2140",
        "ubuntu20.04-x64": "2092",
        "ubuntu20.04-arm64": "2092"
      },
      "browserVersion": "18.5"
    },
    {
      "name": "ffmpeg",
      "revision": "1011",
      "installByDefault": true,
      "revisionOverrides": {
        "mac12": "1010",
        "mac12-arm64": "1010"
      }
    },
    {
      "name": "winldd",
      "revision": "1007",
      "installByDefault": false
    },
    {
      "name": "android",
      "revision": "1001",
      "installByDefault": false
    }
  ]
}
```

If we follow the instructions to set a environment variable of `PLAYWRIGHT_BROWSERS_PATH =  "${pkgs.playwright-driver.browsers}";`. The latest browser versions stored in the directory will be out of date with the `browsers.json`.

if I run a ls for the variable `PLAYWRIGHT_BROWSERS_PATH `, it will show out of date browsers, which will cause the errors previously

``` bash
ls $PLAYWRIGHT_BROWSERS_PATH 
chromium-1169@  chromium_headless_shell-1169@  ffmpeg-1011@  firefox-1482@  webkit-2158@
```

The custom executable path works, however if playwright is embedded as a library, for example crawl4ai, it is a little harder to modify the executable path
https://docs.crawl4ai.com/basic/installation/#playwright-installation-note-for-ubuntu

## building my environment 
The specific file that houses all my python specific configurations (UV, playwright, and selenium is the following:
```nix
# modules/development.nix  ── always-on Home-Manager module
{ pkgs, lib, ... }:

let
  # Pick your default interpreter here (swap for python312, python310, …)
  python = pkgs.python311;
in
{
  ##########################################################################
  # Packages added to the user profile
  ##########################################################################
  home.packages = with pkgs; [
    uv
    nodejs_20                       # helper scripts used by Playwright
    playwright-driver.browsers      # patched Chromium / Firefox / WebKit
    gcc                             # compile native wheels
    fastfetch                       # misc CLI goodies
    # selenium dependencies
    chromium                        # for selenium
    chromedriver
    undetected-chromedriver
    glib                            
    cacert

    # Wrapper so wheels can find libstdc++, libgcc_s, etc. at runtime
    (pkgs.writeShellScriptBin "python3" ''
      export LD_LIBRARY_PATH=$NIX_LD_LIBRARY_PATH
      exec ${python}/bin/python3 "$@"
    '')
  ];

  ##########################################################################
  # Environment variables for every shell (bash, zsh, fish …)
  ##########################################################################
  home.sessionVariables = {
    SSL_CERT_FILE = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";
    LD_LIBRARY_PATH =
      "${pkgs.lib.makeLibraryPath [ pkgs.stdenv.cc.cc.lib ]}:$LD_LIBRARY_PATH";
    
    PLAYWRIGHT_BROWSERS_PATH =
      "${pkgs.playwright-driver.browsers}";
    
    PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS = "true";
    
    SE_CHROMEDRIVER = "${pkgs.chromedriver}/bin/chromedriver";
  };

  ##########################################################################
  # Extra initialisation for fish (runs only when the interactive shell is fish)
  ##########################################################################
  programs.fish.shellInit = ''
    set -gx SSL_CERT_FILE ${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt
    set -gx SE_CHROMEDRIVER ${pkgs.chromedriver}/bin/chromedriver

    # Tell uv to prefer its own managed runtimes; unset hard pins
    if not set -q UV_PYTHON_PREFERENCE
        set -Ux UV_PYTHON_PREFERENCE only-managed
    end
    set -e UV_PYTHON
  '';
}

```

If you would like to fully replicate my environment, download my repo and install using the flake
https://github.com/BedHedd/nix-config/blob/master/flake.nix
run `sudo nixos-rebuild switch --flake .#master-of-cooling ` or any of the machines, since `./modules/development.nix` is imported into my `bedhedd.nix`

For the full write up and to replicate my issues, see my notebook
https://github.com/BedHedd/nix-playwright-debug/blob/master/playwright-test.ipynb
