### ISSUE TITLE
quarto on darwin is missing `bin/tools/` subdirectory and can't run Deno scripts

### ISSUE THREAD

**Issue by wch** [NixOS/nixpkgs#268427]
### Describe the bug

Quarto is missing the `bin/tools/` subdirectory, and can't run scripts using Deno.

You should be able to call `quarto run script.ts`, and it will execute that script using `deno`, which is normally installed in `bin/tools/`

This is the help page for `quarto run`:

```
$ quarto run --help

  Usage:   quarto run [script] [args...]
  Version: 1.3.450                      

  Description:

    Run a TypeScript, R, Python, or Lua script.                              
                                                                             
    Run a utility script written in a variety of languages. For details, see:
    https://quarto.org/docs/projects/scripts.html#periodic-scripts           

  Options:

    -h, --help              - Show this help.                             
    --log         <level>   - Path to log file                            
    --log-level   <level>   - Log level (info, warning, error, critical)  
    --log-format  <format>  - Log format (plain, json-stream)             
    --quiet                 - Suppress console output.                    
    --profile               - Active project profile(s)                   

  Commands:

    help  [command]  - Show this help or the help of a sub-command.
```

### Steps To Reproduce

Run the following:

```
echo 'console.log("hello");' > script.ts
quarto run script.ts
```

It will result in this error:

```
WARNING: Specified QUARTO_DENO does not exist, using built in deno
ERROR: Error executing '/nix/store/g39cfbmkga19nxc1izgp21zrhxn4fv07-quarto-1.3.450/bin/tools/deno': No such file or directory (os error 2)

Error: Error executing '/nix/store/g39cfbmkga19nxc1izgp21zrhxn4fv07-quarto-1.3.450/bin/tools/deno': No such file or directory (os error 2)
    at execProcess (file:///nix/store/g39cfbmkga19nxc1izgp21zrhxn4fv07-quarto-1.3.450/bin/quarto.js:5630:15)
    at Object.run (file:///nix/store/g39cfbmkga19nxc1izgp21zrhxn4fv07-quarto-1.3.450/bin/quarto.js:122732:22)
    at runScript (file:///nix/store/g39cfbmkga19nxc1izgp21zrhxn4fv07-quarto-1.3.450/bin/quarto.js:103932:26)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async quarto (file:///nix/store/g39cfbmkga19nxc1izgp21zrhxn4fv07-quarto-1.3.450/bin/quarto.js:127524:26)
    at async file:///nix/store/g39cfbmkga19nxc1izgp21zrhxn4fv07-quarto-1.3.450/bin/quarto.js:127563:9
```

### Expected behavior

It should print `hello`.

### Additional context

Being able to call `quarto run script.ts` is needed for some extensions. For example, the shinylive extension (which I maintain) calls it here:
https://github.com/quarto-ext/shinylive/blob/213a995285e5f8c46293532f6cd9ac3e0d050b7a/_extensions/quarto-ext/shinylive/shinylive.lua#L417-L421

The cause of the problem is that, for darwin, it is downloading the linux tarball, and then removing the `bin/tools/` directory here:
https://github.com/NixOS/nixpkgs/blob/985a00b9c3bd235f99e9b6f07ca754b605ee9a50/pkgs/development/libraries/quarto/default.nix#L59

I believe the solution is to download the Mac tarball and then _not_ remove `bin/tools/`

### Notify maintainers

@minijackson @mrtarantoga

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.0.0, macOS 14.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/mrckm9b3v6wg2fljdp3z4pja1sz07g3z-source`

**Comment by wch** [comment]
Another possible fix is to add this to the `preFixup`:

```
--prefix QUARTO_DENO : ${prev.deno}/bin/deno
```

This might be a cleaner solution.

**Comment by BerriJ** [comment]
Sorry for hijacking this old issue, but today I also ran into a Pandoc issue and solved that using an override that removes `rm -r bin/tools ` from the `installPhase`. What is the rationale behind removing `bin/tools`?

The discussion about `bin/tools` is also related to https://github.com/NixOS/nixpkgs/issues/210826 and https://github.com/NixOS/nixpkgs/issues/256074

Thanks in advace.

I'm happy to make a PR that modifies the quarto `installPhase` accordingly, so that the `tools` stay included.

**Comment by PeterWang-dev** [comment]
> Sorry for hijacking this old issue, but today I also ran into a Pandoc issue and solved that using an override that removes `rm -r bin/tools ` from the `installPhase`. What is the rationale behind removing `bin/tools`?
> 
> The discussion about `bin/tools` is also related to [#210826](https://github.com/NixOS/nixpkgs/issues/210826) and [#256074](https://github.com/NixOS/nixpkgs/issues/256074)
> 
> Thanks in advace.
> 
> I'm happy to make a PR that modifies the quarto `installPhase` accordingly, so that the `tools` stay included.

Same issue here. Pandoc variable not set at runtime and `bin/tools ` make VSCode extension not work any more.
