### ISSUE TITLE
afew: Missing setuptools at runtime

### ISSUE THREAD

**Issue by korrat** [NixOS/nixpkgs#268680]
### Describe the bug

The `afew` package seems to be missing `setuptools` in `propagatedBuildInputs`.

### Steps To Reproduce

```console
$ nix shell nixpkgs#afew
$ afew --help
Traceback (most recent call last):
  File "/nix/store/89mmgs98kpvxm80jplhnpqpwzc9qlxl1-afew-3.0.1/bin/.afew-wrapped", line 6, in <module>
    from afew.commands import main
  File "/nix/store/89mmgs98kpvxm80jplhnpqpwzc9qlxl1-afew-3.0.1/lib/python3.11/site-packages/afew/commands.py", line 11, in <module>
    from afew.FilterRegistry import all_filters
  File "/nix/store/89mmgs98kpvxm80jplhnpqpwzc9qlxl1-afew-3.0.1/lib/python3.11/site-packages/afew/FilterRegistry.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

### Expected behavior

Something like the following help output:

```console
$ afew --help
usage: afew [-h] [-V] [-t] [-w] [-m] [-a] [-n] [-C NOTMUCH_CONFIG] [-e ENABLE_FILTERS] [-d] [-R REFERENCE_SET_SIZE]
            [-T DAYS] [-v] [-N NOTMUCH_ARGS]
            [query ...]

options:
  -h, --help            show this help message and exit
  -V, --version         show program's version number and exit

Actions:
  Please specify exactly one action.

  -t, --tag             run the tag filters
  -w, --watch           continuously monitor the mailbox for new files
  -m, --move-mails      move mail files between maildir folders

Query modifiers:
  Please specify either --all or --new or a query string.

  -a, --all             operate on all messages
  -n, --new             operate on all new messages
  query                 a notmuch query to find messages to work on

General options:
  -C NOTMUCH_CONFIG, --notmuch-config NOTMUCH_CONFIG
                        path to the notmuch configuration file [default: $NOTMUCH_CONFIG or ~/.notmuch-config]
  -e ENABLE_FILTERS, --enable-filters ENABLE_FILTERS
                        filter classes to use, separated by ',' [default: filters specified in afew's config]
  -d, --dry-run         don't change the db [default: False]
  -R REFERENCE_SET_SIZE, --reference-set-size REFERENCE_SET_SIZE
                        size of the reference set [default: 1000]
  -T DAYS, --reference-set-timeframe DAYS
                        do not use mails older than DAYS days [default: 30]
  -v, --verbose         be more verbose, can be given multiple times
  -N NOTMUCH_ARGS, --notmuch-args NOTMUCH_ARGS
                        arguments for notmuch new (in move mode)
```

### Additional context

Searching for the error message suggests that `pkg_resources` is from `setuptools` and overriding the derivation to include `setuptools` in `propagatedBuildInputs` seems to fix the issue. However, I do not have enough experience with Python packaging in NixOS to know whether that is sufficient/the right thing to do.

### Notify maintainers

- @flokli 
- @erictapen 
- @mweinelt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-info -m
 - host os: `Linux 6.6.1-zen1-1-zen, Arch Linux, noversion, rolling`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(korrat): `"nixpkgs"`
 - channels(root): `""`
 - nixpkgs: `not found`
```

**Comment by flokli** [comment]
This probably regressed in https://github.com/NixOS/nixpkgs/pull/268138 - cc @RaitoBezarius @mweinelt

**Comment by mweinelt** [comment]
Provided a fix, PTAL.
