### ISSUE TITLE
Build failure: django_4

### ISSUE THREAD

**Issue by chayleaf** [NixOS/nixpkgs#269155]
### Steps To Reproduce

1. build django_4
2. build fails

### Build log

On my machine, it failed with the following:

```
...
python3.11-Django> .............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s................................................s.......sss...ss.........................................................................................s...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................sssss.ss...................ssssssssssssssssssssssssssssssssssssssssssssssssssssss...........................................................s..................................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.s.....s............................s........................s.......................s...s...s......sss.................................................................................................................................................sss.....................................................................................................s............s.....................ss................................s..........s.............s.....s..........s....s.s.............s.s................................................................................................................................s.s...s..........................s..s..s..s.....................................s............................................................s...........s...........................s..................................................................................................sssssss............................................................................s.............................................................s................................................x.............................................................................................................s.............................................ss........................s................................................................................................................................................................................................................................................s...................................................................s.................................................................................................................................................................................................................................................................................................................................................................s.....s...s............ssss..............................s..................................................ssss....................................................................................................s.s...............s................................................................................................................................ss............s..s..............................................................................................................s...................................................................................................................s...................................................................................................................................................................................................................................................................................ss.sss.s....................s..........s................................................................ss...........................................................................................................................s........................................................................................................................................................x.................................................................................................................................................................ssssss........ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss......ssssssssssssssssssssssssssssssssssssssssssssssssssssssssss...........................................................................................................................s...............................................................................s..ss.s....................................................s........................................................s......x....x....................................................................................................................................s....s....ss.....s....s......s..................s.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s.....................ssss..........................ssss.............................................................................................................................................s.s.s.................................................................................................ssssssss.....................................................................ssssssssssss...........................................................................................................................................................................................................sss........sssssssssssssssssssssssssss.....ss............................................sssssss......ssssss.......ssss...............................................................E........................................................................................s........................................................ssss..............................................................ssssssssssssssssssssssssss..................ss................................sss.s...s.........s..s......................s.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................sss........s.........s.....................................................................................................................................................s....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s....................................................................................................................................................................................................................................................................................................................................................Exception ignored in: <function SpooledTemporaryFile.__del__ at 0xfffff7140180>
python3.11-Django> Traceback (most recent call last):
python3.11-Django>   File "/nix/store/7ahkv87jj59z90yal5dcrgagz58cqmz6-python3-3.11.6/lib/python3.11/tempfile.py", line 732, in __del__
python3.11-Django>     _warnings.warn(
python3.11-Django> ResourceWarning: Unclosed file <tempfile.SpooledTemporaryFile object at 0xfffff530f790>
python3.11-Django> Exception ignored in: <function SpooledTemporaryFile.__del__ at 0xfffff7140180>
python3.11-Django> Traceback (most recent call last):
python3.11-Django>   File "/nix/store/7ahkv87jj59z90yal5dcrgagz58cqmz6-python3-3.11.6/lib/python3.11/tempfile.py", line 732, in __del__
python3.11-Django>     _warnings.warn(
python3.11-Django> ResourceWarning: Unclosed file <tempfile.SpooledTemporaryFile object at 0xfffff530fc10>
python3.11-Django> ...................s..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................ss............................sss..sssssssssssss.....sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss..ss......................................................ssss...................sssssssssssss.......ss............................sss...............................................................................................................................................................................................................................................................................................................................................................s.............s...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.........ss......................................................................................................................................................................................................................................................................sss.................................s........s..............................................x..............................ss........................................................................................................................s....................................................................................................................................................s................s.................................................................ssssssssssssssssssss.s.sssss.ssssssss...............................................................................................................s...s............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s........................................................................................................................................................................................................................................................................................................................................................s..........................................................................................................s...............................s.................s...............s..............................................................................................................................................................................................................................................................................................................ssssssssssssssssssss.................................................................................................................................................................................................................................................................................................................................................................................ss....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s.ss...............sss...s.ss.....s.ss.ss.sss..s......ss.s.s.................s........s.....................ss..ss...................s..s....s...s.....................s.....s..........s.......s...s...sss............................................
python3.11-Django> ======================================================================
python3.11-Django> ERROR: test_concurrent_async_uses_multiple_thread_pools (asgi.tests.ASGITest.test_concurrent_async_uses_multiple_thread_pools)
python3.11-Django> ----------------------------------------------------------------------
python3.11-Django> Traceback (most recent call last):
python3.11-Django>   File "/nix/store/7ahkv87jj59z90yal5dcrgagz58cqmz6-python3-3.11.6/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
python3.11-Django>     yield
python3.11-Django>   File "/nix/store/7ahkv87jj59z90yal5dcrgagz58cqmz6-python3-3.11.6/lib/python3.11/unittest/case.py", line 623, in run
python3.11-Django>     self._callTestMethod(testMethod)
python3.11-Django>     ^^^^^^^^^^^^^^^^^
python3.11-Django>   File "/nix/store/7ahkv87jj59z90yal5dcrgagz58cqmz6-python3-3.11.6/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
python3.11-Django>     if method() is not None:
python3.11-Django>     ^^^^^^^^^^^^^^^^^
python3.11-Django>   File "/nix/store/8n2m7q0aqcm9msvddcglq69mfcbhxsil-python3.11-asgiref-3.7.2/lib/python3.11/site-packages/asgiref/sync.py", line 277, in __call__
python3.11-Django>     return call_result.result()
python3.11-Django>     ^^^^^^^^^^^^^^^^^
python3.11-Django>   File "/nix/store/7ahkv87jj59z90yal5dcrgagz58cqmz6-python3-3.11.6/lib/python3.11/concurrent/futures/_base.py", line 449, in result
python3.11-Django>     return self.__get_result()
python3.11-Django>     ^^^^^^^^^^^^^^^^^
python3.11-Django>   File "/nix/store/7ahkv87jj59z90yal5dcrgagz58cqmz6-python3-3.11.6/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
python3.11-Django>     raise self._exception
python3.11-Django>     ^^^^^^^^^^^^^^^^^
python3.11-Django>   File "/nix/store/8n2m7q0aqcm9msvddcglq69mfcbhxsil-python3.11-asgiref-3.7.2/lib/python3.11/site-packages/asgiref/sync.py", line 353, in main_wrap
python3.11-Django>     result = await self.awaitable(*args, **kwargs)
python3.11-Django>     ^^^^^^^^^^^^^^^^^
python3.11-Django>   File "/build/Django-4.2.7/tests/asgi/tests.py", line 306, in test_concurrent_async_uses_multiple_thread_pools
python3.11-Django>     response_start = await communicator.receive_output()
python3.11-Django>     ^^^^^^^^^^^^^^^^^
python3.11-Django>   File "/nix/store/8n2m7q0aqcm9msvddcglq69mfcbhxsil-python3.11-asgiref-3.7.2/lib/python3.11/site-packages/asgiref/testing.py", line 85, in receive_output
python3.11-Django>     raise e
python3.11-Django>   File "/nix/store/8n2m7q0aqcm9msvddcglq69mfcbhxsil-python3.11-asgiref-3.7.2/lib/python3.11/site-packages/asgiref/testing.py", line 73, in receive_output
python3.11-Django>     async with async_timeout(timeout):
python3.11-Django>     ^^^^^^^^^^^^^^^^^
python3.11-Django>   File "/nix/store/8n2m7q0aqcm9msvddcglq69mfcbhxsil-python3.11-asgiref-3.7.2/lib/python3.11/site-packages/asgiref/timeout.py", line 71, in __aexit__
python3.11-Django>     self._do_exit(exc_type)
python3.11-Django>     ^^^^^^^^^^^^^^^^^
python3.11-Django>   File "/nix/store/8n2m7q0aqcm9msvddcglq69mfcbhxsil-python3.11-asgiref-3.7.2/lib/python3.11/site-packages/asgiref/timeout.py", line 108, in _do_exit
python3.11-Django>     raise asyncio.TimeoutError
python3.11-Django>     ^^^^^^^^^^^^^^^^^
python3.11-Django> TimeoutError
python3.11-Django> ----------------------------------------------------------------------
python3.11-Django> Ran 16329 tests in 7549.892s
python3.11-Django> FAILED (errors=1, skipped=1316, expected failures=5)
...
```

It could be a failing test, or it could be an issue with machine speed

### Additional context

See https://hydra.nixos.org/job/nixpkgs/staging-next/python311Packages.django_4.aarch64-linux and https://hydra.nixos.org/job/nixpkgs/staging-next/python311Packages.django_4.x86_64-linux

### Notify maintainers

@mweinelt 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.6.0-rc1, NixOS, 23.11 (Tapir), 23.11.20231020.77ba482`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
The build failure on staging was 6 days ago, I restarted it and it succeeded. Also, `python311Packages.django_4` is cached on master and staging-next for me right now.

What is weird about your test run is that it apparently took just over two hours. Is this reproducible? If so, on which branch?

On my local RK3588 machine the test run on master looks like this:

```
Django> running install tests
Django> /build/Django-4.2.7/tests /build/Django-4.2.7
Django> Testing against Django installed in '/nix/store/fr7qqflwdss78930spns3cmc1gz5fdc1-python3.11-Django-4.2.7/lib/python3.11/site-packages/django' with up to 8 processes
Django> Found 16331 test(s).
Django> Creating test database for alias 'default'...
Django> Cloning test database for alias 'default'...
Django> Cloning test database for alias 'default'...
Django> Cloning test database for alias 'default'...
Django> Cloning test database for alias 'default'...
Django> Cloning test database for alias 'default'...
Django> Cloning test database for alias 'default'...
Django> Cloning test database for alias 'default'...
Django> Cloning test database for alias 'default'...
Django> Creating test database for alias 'other'...
Django> Cloning test database for alias 'other'...
Django> Cloning test database for alias 'other'...
Django> Cloning test database for alias 'other'...
Django> Cloning test database for alias 'other'...
Django> Cloning test database for alias 'other'...
Django> Cloning test database for alias 'other'...
Django> Cloning test database for alias 'other'...
Django> Cloning test database for alias 'other'...
Django> System check identified no issues (17 silenced).
Django>..................................s..................................................................................................................................s.....................................................................................................................................................................................................................................................ss.sss.s....................s..........s...................................................................................................................................................................................................................................................s............................................................................................................s.s...ss...s...s.s............s....s.s........................................s..............................................................................................s.........................................................................s..s..s..s............................................................s.................................................................................................................................................................................................................................................................ss.sssssssssssssssssssssssssssssssssssssssssssssssssssssssssss..............................................................................ss............s..s..................................s....................................................................................................................................................................................................................................................................................................................ssssss.....................x............s...............ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss......sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss................................................................sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss..............ssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.............s..........................................................................................................................................................................................................................................s..ss.s.......................s...............................................................................................................x.............................................................s..........................x.......................................................................................................s....s....ss.....s....s......s...........................................s.............................................................................................................................................................................................................................................................................................................................................................sss...ss.......................................................................................................ssss.................s.............................................ss................................................s.s.s......................................................................................................................s..........................................s..........................................................................s...............................................s..................................................................................sss.................................................................................................s........s...................s.............................................................................................................................................s.......ss......................................................ssss...............................................................................................................................................................................................x.........................sssssss...................................................................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss...............ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.....................................................................................................................................................................s.......................................s...............................................................................................................................................................................................s...................................................................................................................................................................................................................................................................................s..........s...s...s..........................................................................................................s............ssss....................................s..................................................ssss......................................................................s.s...............s...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s.........s.......................s...s...s......sss.................................................................s..................................................................................................................................................................................s............................................................................................ssssssss.....................s...................s...s.............s......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................ssss.....................................sssssssssssss................................................ssss..........................................................ssssssssssssssssssssssssss...............................................sss........sss........s.........s..s.........sss........s..............s.............................................................................................ss.....................................................................................................................................................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.....................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss....................................................x..............................ss.................................................................................................s.................................................ssssssssssssssssssss.s.sssss.ssssssss......................................s............................................................................................................................................................................................................ssssssssssss................................................................................................................('127.0.0.1', 58044) unrecognised: #
Django> ................................................................................................................................ss...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s.......................s..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s.................................................................................................................................................................................s............................................................................................................................................................................................................................................................................................................................................................s................s................................................................................................................................................................................................................s...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s.............s..............................................................................................................................................................................................................................................................ss........sssssss....................................ssssss.................................................................................ssssssssssssssssssss.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s...s......................................................................................................................sss.......................................ssssssssss....sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss..............................................................................................................................................................................................................................................................................................ss...................................................................................................................................................................................................................................................................................sss...............................sss.sssssssssssssssssssssssssss.........ssss.........................................................................................................................................................................................................................................................................................s.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s.............................s.ss...............sss...s.ss.....s.ss.ss.sss..s......ss.s.s.................s........s.....................ss..ss...................s..s....s...s.....................s.....s..........s.......s...s...sss...
Django> ----------------------------------------------------------------------
Django> Ran 16329 tests in 161.916s
Django> 
Django> OK (skipped=1316, expected failures=5)
Django> Destroying test database for alias 'default'...
Django> Destroying test database for alias 'default'...
Django> Destroying test database for alias 'default'...
Django> Destroying test database for alias 'default'...
Django> Destroying test database for alias 'default'...
Django> Destroying test database for alias 'default'...
Django> Destroying test database for alias 'default'...
Django> Destroying test database for alias 'default'...
Django> Destroying test database for alias 'default'...
Django> Destroying test database for alias 'other'...
Django> Destroying test database for alias 'other'...
Django> Destroying test database for alias 'other'...
Django> Destroying test database for alias 'other'...
Django> Destroying test database for alias 'other'...
Django> Destroying test database for alias 'other'...
Django> Destroying test database for alias 'other'...
Django> Destroying test database for alias 'other'...
Django> Destroying test database for alias 'other'...
Django> /build/Django-4.2.7
Django> installCheckPhase completed in 3 minutes 11 seconds
```
