### ISSUE TITLE
csvs-to-sqlite does not run

### ISSUE THREAD

**Issue by Alexnortung** [NixOS/nixpkgs#269412]
### Describe the bug
The program fails as soon as you try to run it, with or withour arguments

### Steps To Reproduce
1. nix run nixpkgs#csvs-to-sqlite
2. see error

```
Traceback (most recent call last):
  File "/nix/store/jzq6d3bpdsnv91r83aadrj5iyvhbd1ma-csvs-to-sqlite-1.3/bin/.csvs-to-sqlite-wrapped", line 6, in <module>
    from csvs_to_sqlite.cli import cli
  File "/nix/store/jzq6d3bpdsnv91r83aadrj5iyvhbd1ma-csvs-to-sqlite-1.3/lib/python3.11/site-packages/csvs_to_sqlite/cli.py", line 4, in <module>
    from .utils import (
  File "/nix/store/jzq6d3bpdsnv91r83aadrj5iyvhbd1ma-csvs-to-sqlite-1.3/lib/python3.11/site-packages/csvs_to_sqlite/utils.py", line 6, in <module>
    import pandas as pd
  File "/nix/store/z0vn54dcb7yy9d9cx2hbl8b74gpqpk7a-devenv-profile/lib/python3.10/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy:
```

### Expected behavior
I expected the program to run normally

### Additional context
I think numpy needs to be added to the dependencies

### Notify maintainers

@costrouc 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Alexnortung** [comment]
Sorry, I think this has something to do with the nix shell that I was using, that causes the issue. However I am not sure why this happens.
