### ISSUE TITLE
jupyter-book: Default template build fails

### ISSUE THREAD

**Issue by danteu** [NixOS/nixpkgs#270728]
### Describe the bug
When I try to build the Jupyter template book (https://jupyterbook.org/en/stable/start/create.html) the build fails due to a Python runtime error.

### Steps To Reproduce
1. Create the template book: `jupyter-book create mynewbook/`
2. Switch to the created directory and try to build the book using the `jupyter-book` package. The build will fail as shown below.
```console
$ nix-shell -p python311Packages.jupyter-book
$ cd mynewbook && jupyter-book build .
Running Jupyter-Book v0.15.1
Source Folder: /home/daniel/jupyter/mynewbook
Config Path: /home/daniel/jupyter/mynewbook/_config.yml
Output Path: /home/daniel/jupyter/mynewbook/_build/html
Running Sphinx v7.2.6
WARNING: while setting up extension sphinx_jupyterbook_latex: [sphinx-jupyterbook-latex]: myst-nb version not compatible with >=0.13,<0.18: 1.0.0
making output directory... done
[etoc] Changing master_doc to 'intro'
checking bibtex cache... out of date
parsing bibtex file /home/daniel/jupyter/mynewbook/references.bib... parsed 5 entries
myst v2.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'colon_fence', 'linkify', 'substitution', 'tasklist', 'dollarmath'}, disable_syntax=[], all_links_external=False, url_schemes=('mailto', 'http', 'https'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
myst-nb v1.0.0: NbParserConfig(custom_formats={}, metadata_key='mystnb', cell_metadata_key='mystnb', kernel_rgx_aliases={}, eval_name_regex='^[a-zA-Z_][a-zA-Z0-9_]*$', execution_mode='force', execution_cache_path='', execution_excludepatterns=[], execution_timeout=30, execution_in_temp=False, execution_allow_errors=False, execution_raise_on_error=False, execution_show_tb=False, merge_streams=False, render_plugin='default', remove_code_source=False, remove_code_outputs=False, code_prompt_show='Show code cell {type}', code_prompt_hide='Hide code cell {type}', number_source_lines=False, output_stderr='show', render_text_lexer='myst-ansi', render_error_lexer='ipythontb', render_image_options={}, render_figure_options={}, render_markdown_format='commonmark', output_folder='build', append_css=True, metadata_to_fm=False)
Using jupyter-cache at: /home/daniel/jupyter/mynewbook/_build/.jupyter_cache
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 4 source files that are out of date
updating environment: [new config] 4 added, 0 changed, 0 removed
/home/daniel/jupyter/mynewbook/markdown-notebooks.md: Executing notebook using local CWD [mystnb]
[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
/home/daniel/jupyter/mynewbook/markdown-notebooks.md: Executed notebook in 1.11 seconds [mystnb]
/home/daniel/jupyter/mynewbook/notebooks.ipynb: Executing notebook using local CWD [mystnb]
[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled

/home/daniel/jupyter/mynewbook/notebooks.ipynb: WARNING: Executing notebook failed: CellExecutionError [mystnb.exec]
/home/daniel/jupyter/mynewbook/notebooks.ipynb: WARNING: Notebook exception traceback saved in: /home/daniel/jupyter/mynewbook/_build/html/reports/notebooks.err.log [mystnb.exec]
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [ 25%] intro
Theme error:
An error happened in rendering the page intro.
Reason: AttributeError("'str' object has no attribute 'joinpath'")
Traceback (most recent call last):
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1127, in handle_page
    output = self.templates.render(templatename, ctx)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/jinja2glue.py", line 200, in render
    return self.environment.get_template(template).render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ihhyyis0vm1i3wif4v05cd3s5prc9h16-python3.11-Jinja2-3.1.2/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/nix/store/ihhyyis0vm1i3wif4v05cd3s5prc9h16-python3.11-Jinja2-3.1.2/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/c1prsljknynyhnsi3n2fh3jykgzbha84-python3.11-sphinx-book-theme-1.0.1/lib/python3.11/site-packages/sphinx_book_theme/theme/sphinx_book_theme/layout.html", line 1, in top-level template code
    {% extends "pydata_sphinx_theme/layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/mz1vakavn1h2mx8rpsc6s1wqiiv5cxky-python3.11-pydata-sphinx-theme-0.14.3/lib/python3.11/site-packages/pydata_sphinx_theme/theme/pydata_sphinx_theme/../pydata_sphinx_theme/layout.html", line 23, in top-level template code
    {% set remove_sidebar_secondary = (meta is defined and meta is not none
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/themes/basic/../basic/layout.html", line 114, in top-level template code
    {%- block css %}
^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/mz1vakavn1h2mx8rpsc6s1wqiiv5cxky-python3.11-pydata-sphinx-theme-0.14.3/lib/python3.11/site-packages/pydata_sphinx_theme/theme/pydata_sphinx_theme/../pydata_sphinx_theme/layout.html", line 36, in block 'css'
    {{- css() }}
  ^^^^^^^^^^^^^^^
  File "/nix/store/ihhyyis0vm1i3wif4v05cd3s5prc9h16-python3.11-Jinja2-3.1.2/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ihhyyis0vm1i3wif4v05cd3s5prc9h16-python3.11-Jinja2-3.1.2/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/themes/basic/../basic/layout.html", line 95, in template
    {{ css_tag(css) }}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ihhyyis0vm1i3wif4v05cd3s5prc9h16-python3.11-Jinja2-3.1.2/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1063, in css_tag
    if checksum := _file_checksum(outdir, css.filename):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/html/_assets.py", line 141, in _file_checksum
    content = outdir.joinpath(filename).read_bytes().translate(None, b'\r')
              ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'joinpath'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/qa9li26d6cl88kw661c6hkfvilw161ix-python3.11-jupyter-book-0.15.1/lib/python3.11/site-packages/jupyter_book/sphinx.py", line 171, in build_sphinx
    app.build(force_all, filenames)
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 363, in build
    self.write(docnames, list(updated_docnames), method)
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 571, in write
    self._write_serial(sorted(docnames))
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 581, in _write_serial
    self.write_doc(docname, doctree)
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 655, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/nix/store/vj2i33l4cssf4lnx0a993k3vv3yhh6a6-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1134, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page intro.
Reason: AttributeError("'str' object has no attribute 'joinpath'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/qa9li26d6cl88kw661c6hkfvilw161ix-python3.11-jupyter-book-0.15.1/bin/.jupyter-book-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/2z0jalw27lp6zm642aqvnlydlqblhcdf-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/2z0jalw27lp6zm642aqvnlydlqblhcdf-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/2z0jalw27lp6zm642aqvnlydlqblhcdf-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/2z0jalw27lp6zm642aqvnlydlqblhcdf-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/2z0jalw27lp6zm642aqvnlydlqblhcdf-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qa9li26d6cl88kw661c6hkfvilw161ix-python3.11-jupyter-book-0.15.1/lib/python3.11/site-packages/jupyter_book/cli/main.py", line 317, in build
    builder_specific_actions(
  File "/nix/store/qa9li26d6cl88kw661c6hkfvilw161ix-python3.11-jupyter-book-0.15.1/lib/python3.11/site-packages/jupyter_book/cli/main.py", line 525, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError:
===============================================================================

There was an error in building your book. Look above for the cause.

===============================================================================
```

The behavior is virtually identical when using Python 3.10, in particular the AttributeError:
```
Reason: AttributeError("'str' object has no attribute 'joinpath'")
```
 I will provide the full output for that if required.

### Expected behavior
The book should be built. Using the current `jupyter-book` pip package builds the book correctly:
```console
$ pip install --upgrade jupyter-book
[...]
$ jupyter-book build .
Running Jupyter-Book v0.15.1
Source Folder: /home/daniel/jupyter/mynewbook
Config Path: /home/daniel/jupyter/mynewbook/_config.yml
Output Path: /home/daniel/jupyter/mynewbook/_build/html
[sphinxcontrib-bibtex] Beware that docutils versions 0.18 and 0.19 (you are running 0.18.1) are known to generate invalid html for citations. If this issue affects you, please use docutils<0.18 (or >=0.20 once released) instead. For more details, see https://sourceforge.net/p/docutils/patches/195/
Running Sphinx v5.0.2
making output directory... done
[etoc] Changing master_doc to 'intro'
checking bibtex cache... out of date
parsing bibtex file /home/daniel/jupyter/mynewbook/references.bib... parsed 5 entries
myst v0.18.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist'], disable_syntax=[], all_links_external=False, url_schemes=['mailto', 'http', 'https'], ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
myst-nb v0.17.2: NbParserConfig(custom_formats={}, metadata_key='mystnb', cell_metadata_key='mystnb', kernel_rgx_aliases={}, execution_mode='force', execution_cache_path='', execution_excludepatterns=[], execution_timeout=30, execution_in_temp=False, execution_allow_errors=False, execution_raise_on_error=False, execution_show_tb=False, merge_streams=False, render_plugin='default', remove_code_source=False, remove_code_outputs=False, code_prompt_show='Show code cell {type}', code_prompt_hide='Hide code cell {type}', number_source_lines=False, output_stderr='show', render_text_lexer='myst-ansi', render_error_lexer='ipythontb', render_image_options={}, render_figure_options={}, render_markdown_format='commonmark', output_folder='build', append_css=True, metadata_to_fm=False)
Using jupyter-cache at: /home/daniel/jupyter/mynewbook/_build/.jupyter_cache
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 4 source files that are out of date
updating environment: [new config] 4 added, 0 changed, 0 removed
/home/daniel/jupyter/mynewbook/markdown-notebooks.md: Executing notebook using local CWD [mystnb]
/home/daniel/jupyter/mynewbook/markdown-notebooks.md: Executed notebook in 1.16 seconds [mystnb]
/home/daniel/jupyter/mynewbook/notebooks.ipynb: Executing notebook using local CWD [mystnb]

/home/daniel/jupyter/mynewbook/notebooks.ipynb: WARNING: Executing notebook failed: CellExecutionError [mystnb.exec]
/home/daniel/jupyter/mynewbook/notebooks.ipynb: WARNING: Notebook exception traceback saved in: /home/daniel/jupyter/mynewbook/_build/html/reports/notebooks.err.log [mystnb.exec]
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] notebooks
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
[etoc] missing index.html written as redirect to 'intro.html'
build succeeded, 2 warnings.

The HTML pages are in _build/html.

===============================================================================

Finished generating HTML for book.
Your book's HTML pages are here:
    _build/html/
You can look at your book by opening this file in a browser:
    _build/html/index.html
Or paste this line directly into your browser bar:
    file:///home/daniel/jupyter/mynewbook/_build/html/index.html

===============================================================================
```

### Additional context
The most obvious difference between the current nix and pip version seems to be that the nix version is running a newer version of Sphinx (`v7.2.6` instead of `v5.0.2`), though I can't be sure if that causes the problem. The warning about an incompatible myst-nb version was addressed by #241503 and #246220.

### Notify maintainers

@marsam 

### Metadata

```console
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/2bk3cqpj26fi3fwgshgg3k0fxwz0h55g-nix-info
copying path '/nix/store/2bk3cqpj26fi3fwgshgg3k0fxwz0h55g-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.0-362.8.1.el9_3.x86_64, Rocky Linux, 9.3 (Blue Onyx), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs
```

**Comment by kirillrdy** [comment]
cc @natsukium

**Comment by natsukium** [comment]
Could you please check with the master branch?
I can confirm that `jupyter-book create` has a problem, but I can't reproduce such an error log.

**Comment by danteu** [comment]
> From my perspective, since `jupyter-book` uses `shutil.copy` to copy the template with permissions, it is read-only and `jupyter-book create` fails. https://github.com/executablebooks/jupyter-book/blob/04b7b65485de989baba495a456d9f619dded44d6/jupyter_book/cli/main.py#L329-L334

Sorry for my ambiguous wording - `jupyter-book create` was run using the pip package. When using the nix package, the directory/files have incorrect permissions. So after running `jupyter-book create mynewbook/`, one has to `chmod u+x mynewbook` and `chmod u+rw mynewbook/*`. After that, however, the error shown above happens.

I re-tried it with the master branch (`nix-shell -p python311Packages.jupyter-book -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz`) and get the same error.

**Comment by danteu** [comment]
With jupyter-book having been bumped to 1.0.0 (https://github.com/NixOS/nixpkgs/commit/3ea831439603fbd999aebf4cba597c004b06883d), which supports Sphinx versions >= 7, this issue has been resolved.
