### ISSUE TITLE
spyder IDE crashes on start

### ISSUE THREAD

**Issue by NANASHI0X74** [NixOS/nixpkgs#270899]
### Describe the bug
when I install spyder with `nix shell nixpkgs#spyder` and then launch it, it throws an error with the following traceback+log:
```python-traceback
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
fromIccProfile: failed minimal tag size sanity
Traceback (most recent call last):
  File "/nix/store/2wic2q14skrd304510lyxdxmzv5jpldp-python3.11-spyder-5.5.0/bin/..spyder-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/2wic2q14skrd304510lyxdxmzv5jpldp-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/start.py", line 244, in main
    mainwindow.main(options, args)
  File "/nix/store/2wic2q14skrd304510lyxdxmzv5jpldp-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 1847, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/2wic2q14skrd304510lyxdxmzv5jpldp-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/utils.py", line 289, in create_window
    main.setup()
  File "/nix/store/2wic2q14skrd304510lyxdxmzv5jpldp-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 752, in setup
    internal_plugins = find_internal_plugins()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/2wic2q14skrd304510lyxdxmzv5jpldp-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/find_plugins.py", line 40, in find_internal_plugins
    mod = importlib.import_module(entry_point.module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/2wic2q14skrd304510lyxdxmzv5jpldp-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/plugin.py", line 22, in <module>
    from spyder.plugins.pylint.confpage import PylintConfigPage
  File "/nix/store/2wic2q14skrd304510lyxdxmzv5jpldp-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/confpage.py", line 16, in <module>
    from spyder.plugins.pylint.main_widget import (MAX_HISTORY_ENTRIES,
  File "/nix/store/2wic2q14skrd304510lyxdxmzv5jpldp-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/main_widget.py", line 90, in <module>
    class CategoryItem(QTreeWidgetItem):
  File "/nix/store/2wic2q14skrd304510lyxdxmzv5jpldp-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/main_widget.py", line 102, in CategoryItem
    'icon': ima.icon("convention")
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/2wic2q14skrd304510lyxdxmzv5jpldp-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/utils/icon_manager.py", line 439, in icon
    kwargs['color_disabled'] = QStylePalette.COLOR_DISABLED
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DarkPalette' has no attribute 'COLOR_DISABLED'
```
This seems to be a manifestation of this issue: https://github.com/spyder-ide/spyder/issues/21507
where QDarkStyle needed to be updated for the reporter's IDE.

### Steps To Reproduce
1. launch `spyder`

### Expected behavior
spyder IDE starts

### Additional context
As mentioned, this seems to be a manifestation of  https://github.com/spyder-ide/spyder/issues/21507

### Notify maintainers
@gebner 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
(Note, I'm using flakes for my os configuration)

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
warning: Nix search path entry '/nix/store/ljg8h42v5d1s9yyqpzqcr54brn965176-source/overlays' does not exist, ignoring
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 24.05 (Uakari), 24.05.20231124.5a09cb4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/6h04ab83y72nm16hh9g3llgg0s296ynl-source`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nanophilip** [comment]
I experience the same.
```
$ spyder
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
fromIccProfile: failed minimal tag size sanity
Traceback (most recent call last):
  File "/nix/store/si71rk12j45s8blqc7rfzjywklqy7g31-python3.11-spyder-5.5.0/bin/..spyder-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/si71rk12j45s8blqc7rfzjywklqy7g31-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/start.py", line 244, in main
    mainwindow.main(options, args)
  File "/nix/store/si71rk12j45s8blqc7rfzjywklqy7g31-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 1847, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/si71rk12j45s8blqc7rfzjywklqy7g31-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/utils.py", line 289, in create_window
    main.setup()
  File "/nix/store/si71rk12j45s8blqc7rfzjywklqy7g31-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 752, in setup
    internal_plugins = find_internal_plugins()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/si71rk12j45s8blqc7rfzjywklqy7g31-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/find_plugins.py", line 40, in find_internal_plugins
    mod = importlib.import_module(entry_point.module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/si71rk12j45s8blqc7rfzjywklqy7g31-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/plugin.py", line 22, in <module>
    from spyder.plugins.pylint.confpage import PylintConfigPage
  File "/nix/store/si71rk12j45s8blqc7rfzjywklqy7g31-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/confpage.py", line 16, in <module>
    from spyder.plugins.pylint.main_widget import (MAX_HISTORY_ENTRIES,
  File "/nix/store/si71rk12j45s8blqc7rfzjywklqy7g31-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/main_widget.py", line 90, in <module>
    class CategoryItem(QTreeWidgetItem):
  File "/nix/store/si71rk12j45s8blqc7rfzjywklqy7g31-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/main_widget.py", line 102, in CategoryItem
    'icon': ima.icon("convention")
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/si71rk12j45s8blqc7rfzjywklqy7g31-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/utils/icon_manager.py", line 439, in icon
    kwargs['color_disabled'] = QStylePalette.COLOR_DISABLED
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DarkPalette' has no attribute 'COLOR_DISABLED'
```

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 23.11 (Tapir), 23.11.750.7c4c20509c43`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

If according to https://github.com/spyder-ide/spyder/issues/21507#issuecomment-1804051355 Spyder 5.5.0 depends on QDarkstyle 3.2.0, do we users have to roll back to NixOS 23.05, or could QDarkstyle be updated from 3.1 to 3.2 on NixOS 23.11?

**Comment by nanophilip** [comment]
Could QDarkStyle 3.2.3 be backported to NixOS 23.11 to have a working Spyder IDE?

In the meantime, I figured out that I can start Spyder using a `nix-shell -I nixpkgs=channel:nixpkgs-unstable -p python311Packages.qdarkstyle python311Packages.spyder`.

Spyder then gives the message `/nix/store/5k91mg4qjylxbfvrv748smfh51ppjq0g‑python3𔂭.11.6/bin/python3.11: Error while finding module specification for 'spyder_kernels.console' (ModuleNotFoundError: No module named 'spyder_kernels')`.

But I can run `python -m spyder_kernels.console` in a terminal, use the hamburger menu of the iPython console within Spyder (lower right pane), click on 'Connect to an existing kernel', choose the `.json` file generated with `python -m spyder_kernels.console`, and finally have a working Spyder.

However, in my opinion Spyder and all declaratively installed libraries should work out of the box on a stable NixOS release.

**Comment by NANASHI0X74** [comment]
I'm not quite sure how the backporting process works 😅 but I can look into it.

Personally I got my setup working with this flake.nix (using https://github.com/nix-community/pyproject.nix):
```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/master";
    systems.url = "github:nix-systems/default";
    pyproject-nix = {
      url = "github:nix-community/pyproject.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    devenv.url = "github:cachix/devenv";
  };

  nixConfig = {
    extra-trusted-public-keys = "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=";
    extra-substituters = "https://devenv.cachix.org";
  };

  outputs = { self, nixpkgs, devenv, systems, pyproject-nix, ... } @ inputs:
    let
      forEachSystem = nixpkgs.lib.genAttrs (import systems);
    in
    {
      packages = forEachSystem (system: {
        devenv-up = self.devShells.${system}.default.config.procfileScript;
      });

      devShells = forEachSystem
        (system:
          let
            pkgs = nixpkgs.legacyPackages.${system};
            project = pyproject-nix.lib.project.loadPyproject {
              projectRoot = ./.;
            };
            python = pkgs.python3;
            pythonEnv = python.withPackages (project.renderers.withPackages { inherit python; });
          in
          {
            default = devenv.lib.mkShell {
              inherit inputs pkgs;
              modules = [
                {
                  packages =
                    (with pkgs; [ ruff ])
                    ++ [ pythonEnv ];
                }
              ];
            };
          });
    };
}

```
and this pyproject.toml:
```toml
[project]
name = "[redacted]"
version = "0.0.0"
description = "[redacted]"
readme = "README.md"

dependencies = [
  "ortools",
  "requests",
  "parse",
  "python-lsp-server",
  "python-lsp-ruff",
  "pylsp-mypy",
  "flake8",
  "spyder-kernels",
  "pyls-spyder",
  "spyder",
]

[tool.pylsp-mypy]
strict = true

```

not guaranteed to be minimal
