### ISSUE TITLE
Fusuma package is broken

### ISSUE THREAD

**Issue by jjpe** [NixOS/nixpkgs#271651]
### Steps To Reproduce
1. Install "fusuma" package
2. Try to run fusuma

### Expected behavior
I expected fusuma to start running.
I
### Screenshots
-

### Additional context
Instead of displaying the expected behavior, the program crashes:
```
[j@lear:~]$ fusuma
/nix/store/fqkm6wvfwqc61zrdhj70idxh433k7s9f-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/definition.rb:418:in `ensure_equivalent_gemfile_and_lockfile': Your lock file has an invalid dependency "fusuma-plugin-keypress", but the lockfile can't be updated because frozen mode is set (Bundler::ProductionError)

Run `bundle install` elsewhere and add the updated ../../nix/store/cxvnqijdzqzvcgzfr3yfbd747rayyyax-gemfile-and-lockfile/Gemfile to version control.
        from /nix/store/fqkm6wvfwqc61zrdhj70idxh433k7s9f-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/runtime.rb:13:in `setup'
        from /nix/store/fqkm6wvfwqc61zrdhj70idxh433k7s9f-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler.rb:162:in `setup'
        from /nix/store/bmnv77d88lrwc4v87n7hg8yv5g5xn2rd-fusuma-3.1.0/bin/.fusuma-wrapped:33:in `<main>'

[j@lear:~]$ 
```

### Notify maintainers
@wegank
@ebardie
@katexochen 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
[j@lear:~]$ nix-shell -p nix-info --run "nix-info -m"
these 5 paths will be fetched (0.68 MiB download, 9.97 MiB unpacked):
  /nix/store/qmfxld7qhk8qxlkx1cm4bkplg1gh6jgj-file-5.45
  /nix/store/c54kyc3vn0jbq5hznimvx6wz15jxw8jq-gnu-config-2023-09-19
  /nix/store/v4iswb5kwj33l46dyh2zqh0nkxxlr3mz-gnumake-4.4.1
  /nix/store/wr08yanv2bjrphhi5aai12hf2qz5kvic-stdenv-linux
  /nix/store/9vk5fqaik9zx14zpfxipg7lxkdk8c5g9-update-autotools-gnu-config-scripts-hook
copying path '/nix/store/c54kyc3vn0jbq5hznimvx6wz15jxw8jq-gnu-config-2023-09-19' from 'https://cache.nixos.org'...
copying path '/nix/store/qmfxld7qhk8qxlkx1cm4bkplg1gh6jgj-file-5.45' from 'https://cache.nixos.org'...
copying path '/nix/store/v4iswb5kwj33l46dyh2zqh0nkxxlr3mz-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/9vk5fqaik9zx14zpfxipg7lxkdk8c5g9-update-autotools-gnu-config-scripts-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/wr08yanv2bjrphhi5aai12hf2qz5kvic-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 24.05 (Uakari), 24.05pre554114.e92039b55bcd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(j): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jjpe** [comment]
@wegank 
Is there supposed to be a delay between this merge and availability updating?
I can clearly see this PR is merged, when I update my system the new version isn't in there.

**Comment by wegank** [comment]
Yes, see https://status.nixos.org.

**Comment by ed0c** [comment]
@wegank 
One month later, I don't see the updated package. How long can this take ?

**Comment by wegank** [comment]
> @wegank One month later, I don't see the updated package. How long can this take ?

The update is already on master, but I don't think it's been backported yet. Are you on NixOS 23.11 instead of unstable?

**Comment by ed0c** [comment]
> Are you on NixOS 23.11 instead of unstable?

Yes.

**Comment by wegank** [comment]
Backported in #282066, should take a few days to land.

**Comment by ed0c** [comment]
Many thanks for the commit !
