### ISSUE TITLE
RuneLite no longer able to use GPU (GPU/117 HD plugins fail)

### ISSUE THREAD

**Issue by robwhitaker** [NixOS/nixpkgs#271739]
### Describe the bug

Plugins that try to use the GPU now fail with an error.

### Steps To Reproduce

1. Try to enable the GPU plugin; it immediately toggles off again

### Expected behavior

Toggling on GPU-based plugins (GPU/117 HD) should cause RuneLite to use the GPU and stay toggled on.

### Additional context

NVidia driver version: 545.29.02

Error from trying to start the GPU plugin:

```console
2023-12-02 14:55:24 EST [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.UnsatisfiedLinkError: /tmp/17324334379689574841librlawt.so: libGL.so.1: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2404)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:2011)
	at net.runelite.rlawt.AWTContext.loadNatives(AWTContext.java:92)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:293)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:218)
	at client.ro(client.java:59434)
	at client.bm(client.java)
	at bm.ln(bm.java:394)
	at bm.nl(bm.java)
	at bm.run(bm.java:13847)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

Error from trying to start the 117 HD plugin:

```console
2023-12-02 14:56:51 EST [Client] ERROR rs117.hd.HdPlugin - Error while starting 117HD
java.lang.UnsatisfiedLinkError: /tmp/5432491938978681856librlawt.so: libGL.so.1: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2404)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:2011)
	at net.runelite.rlawt.AWTContext.loadNatives(AWTContext.java:92)
	at rs117.hd.HdPlugin.lambda$startUp$1(HdPlugin.java:458)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:218)
	at client.ro(client.java:59434)
	at client.bm(client.java)
	at bm.ln(bm.java:394)
	at bm.nl(bm.java)
	at bm.run(bm.java:13847)
	at java.base/java.lang.Thread.run(Thread.java:1589)
2023-12-02 14:56:51 EST [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.GL15C
	at rs117.hd.overlays.FrameTimer.lambda$destroy$2(FrameTimer.java:52)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:218)
	at client.ro(client.java:59434)
	at client.bm(client.java)
	at bm.ln(bm.java:394)
	at bm.nl(bm.java)
	at bm.run(bm.java:13847)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: libGL.so.1 [in thread "Client"]
	at org.lwjgl.system.Library.loadNative(Library.java:346)
	at org.lwjgl.system.Library.loadNative(Library.java:435)
	at org.lwjgl.system.Library.loadNative(Library.java:402)
	at org.lwjgl.opengl.GL.create(GL.java:101)
	at org.lwjgl.opengl.GL.<clinit>(GL.java:85)
	at org.lwjgl.opengl.GL11C.<clinit>(GL11C.java:38)
	... 11 common frames omitted
2023-12-02 14:56:51 EST [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.GL15C
	at rs117.hd.overlays.FrameTimer.lambda$destroy$2(FrameTimer.java:52)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:218)
	at client.ro(client.java:59434)
	at client.bm(client.java)
	at bm.ln(bm.java:394)
	at bm.nl(bm.java)
	at bm.run(bm.java:13847)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: libGL.so.1 [in thread "Client"]
	at org.lwjgl.system.Library.loadNative(Library.java:346)
	at org.lwjgl.system.Library.loadNative(Library.java:435)
	at org.lwjgl.system.Library.loadNative(Library.java:402)
	at org.lwjgl.opengl.GL.create(GL.java:101)
	at org.lwjgl.opengl.GL.<clinit>(GL.java:85)
	at org.lwjgl.opengl.GL11C.<clinit>(GL11C.java:38)
	... 11 common frames omitted
```

### Notify maintainers

@Kmeakin @majiru 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 24.05 (Uakari), 24.05.20231128.010c729`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - channels(rob): `""`
 - nixpkgs: `/nix/store/19kjl5p3hx3l51yfnii653a3qzm4l6hf-source`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by majiru** [comment]
Sorry thought I had tested for this, taking a look now.

**Comment by robwhitaker** [comment]
@majiru Done! https://github.com/NixOS/nixpkgs/pull/271774
