### ISSUE TITLE
Seahub doesn't start on NixOS 23.11

### ISSUE THREAD

**Issue by Elinvention** [NixOS/nixpkgs#272025]
### Describe the bug
I upgraded to NixOS 23.11 from 23.05 and I didn't touch seafile configuration files. Now Seahub doesn't start anymore.

### Steps To Reproduce
1. Upgrade to NixOS 23.11
2. seahub fails
3. `sudo systemctl restart seahub.service`
4. `systemctl --failed`

### Expected behavior
Seahub should start normally, the same as NixOS 23.05.

### Log
```console
Starting Seafile Server Web Frontend...
Started Seafile Server Web Frontend.
Traceback (most recent call last):
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/bin/.gunicorn-wrapped", line 9, in <module>
    sys.exit(run())
             ^^^^^
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
    ^^^^^^^^^^^^^
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/7yz0pmbxldv4sdm7gb8vxazyc0af0xh5-seahub-9.0.10/seahub/__init__.py", line 2, in <module>
    from .signals import repo_created, repo_deleted, clean_up_repo_trash, \
  File "/nix/store/7yz0pmbxldv4sdm7gb8vxazyc0af0xh5-seahub-9.0.10/seahub/signals.py", line 5, in <module>
    repo_created = django.dispatch.Signal(providing_args=["org_id", "creator", "repo_id", "repo_name", "library_template"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Signal.__init__() got an unexpected keyword argument 'providing_args'
seahub.service: Main process exited, code=exited, status=1/FAILURE
seahub.service: Failed with result 'exit-code'.
```

### Notify maintainers

@greizgh @schmittlauch

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61-hardened1, NixOS, 23.11 (Tapir), 23.11.1250.f8a9aa9ca646`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11-small, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Elinvention** [comment]
After searching more about this issue, I found #249523, which should solve this once merged.
