### ISSUE TITLE
Shattered Pixel Dungeon, unable to initialize graphics display version 2.2.1

### ISSUE THREAD

**Issue by bigshaq9999** [NixOS/nixpkgs#273261]
### Describe the bug
unable to launch shattered pixel dungeon, crashes. 

### Steps To Reproduce
1. install shattered-pixel-dungeon with `nix-shell -p shattered-pixel-dungeon`
2. launch shattered-pixel-dungeon in nix-shell 
3. ... 

### Expected behavior
the game launches

### Additional context
```
[nix-shell:~]$ shattered-pixel-dungeon 
[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[LWJGL] GLFW_API_UNAVAILABLE error
        Description : GLX: Failed to load GLX
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:520)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
                com.shatteredpixel.shatteredpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:188)
[GAME] com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
        at com.shatteredpixel.shatteredpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:188)



missing software! (we will try basic console input)
 ___________
/           \ 
| tiny file |
|  dialogs  |
\_____  ____/
      \|
tiny file dialogs on UNIX needs:
   applescript or kdialog or yad or Xdialog
or zenity (or matedialog or shellementary or qarma)
or python (2 or 3) + tkinter + python-dbus (optional)
or dialog (opens console if needed)
or xterm + bash (opens console for basic input)
or existing console for basic input


Shattered Pixel Dungeon Has Crashed!

Shattered Pixel Dungeon was not able to initialize its graphics display, sorry about that!

This usually happens when your graphics card does not support OpenGL 2.0+, or has misconfigured graphics drivers.

If you are certain the game should be working on your computer, feel free to message the developer (Evan@ShatteredPixel.com)

version: 2.2.1

press enter to continue
```

### Notify maintainers
@fgaz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 24.05 (Uakari), 24.05pre554642.f5c27c6136db`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(kunny): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/kunny/.nix-defexpr/channels/nixpkgs`

```

---

**Comment by AbleTheAbove** [comment]
This is also the case with `experienced-pixel-dungeon` and `summoning-pixel-dungeon`

**Comment by fgaz** [comment]
@AbleTheAbove  #273579 should fix all of them
