### ISSUE TITLE
`msfconsole` of `metasploit` reported undefined method

### ISSUE THREAD

**Issue by oluceps** [NixOS/nixpkgs#273306]
### Describe the bug
`msfconsole` of `metasploit` seems not working.

### Steps To Reproduce
```
> msfconsole
Metasploit tip: Open an interactive Ruby terminal with irb
/nix/store/d8v8d30s62x9g1i25sjyzr71d0qzj8j6-metasploit-framework-6.3.45/share/msf/lib/msf/core/framework.rb:88:in `initialize': undefined method `_install_global_resolver' for Rex::Socket:Module (NoMethodError)
	from /nix/store/d8v8d30s62x9g1i25sjyzr71d0qzj8j6-metasploit-framework-6.3.45/share/msf/lib/msf/base/simple/framework.rb:71:in `new'
	from /nix/store/d8v8d30s62x9g1i25sjyzr71d0qzj8j6-metasploit-framework-6.3.45/share/msf/lib/msf/base/simple/framework.rb:71:in `create'
	from /nix/store/d8v8d30s62x9g1i25sjyzr71d0qzj8j6-metasploit-framework-6.3.45/share/msf/lib/msf/ui/console/driver.rb:93:in `initialize'
	from /nix/store/d8v8d30s62x9g1i25sjyzr71d0qzj8j6-metasploit-framework-6.3.45/share/msf/lib/metasploit/framework/command/console.rb:66:in `new'
	from /nix/store/d8v8d30s62x9g1i25sjyzr71d0qzj8j6-metasploit-framework-6.3.45/share/msf/lib/metasploit/framework/command/console.rb:66:in `driver'
	from /nix/store/d8v8d30s62x9g1i25sjyzr71d0qzj8j6-metasploit-framework-6.3.45/share/msf/lib/metasploit/framework/command/console.rb:54:in `start'
	from /nix/store/d8v8d30s62x9g1i25sjyzr71d0qzj8j6-metasploit-framework-6.3.45/share/msf/lib/metasploit/framework/command/base.rb:82:in `start'
	from /nix/store/d8v8d30s62x9g1i25sjyzr71d0qzj8j6-metasploit-framework-6.3.45/share/msf/msfconsole:23:in `<main>'
```

### Expected behavior
Works.

### Notify maintainers
@makefu 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.12, NixOS, 24.05 (Uakari), 24.05.20231204.2c7f3c0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by makefu** [comment]
can confirm, PR above seems to introduce issue (or something between the last and this package bump)

**Comment by fabaff** [comment]
The issue is that I keep `mini_portile2` for `sqlite3` in the update from 6.3.44 to 6.3.45.
