### ISSUE TITLE
spyder-ide crashes on startup (python311)

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#273358]
### Describe the bug
Spyder IDE crashes on startup on 23.11.

### Steps To Reproduce
1. install spyder

```nix
  environment.systemPackages = [
    pkgs.python311Packages.spyder
  ];
```

### Expected behavior
the program starts without crashing.

### Notify maintainers

@gebner 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
➜  ~ nix-shell -p nix-info --run 'nix-info -m'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.3, NixOS, 23.11 (Tapir), 23.11.1115.5de0b32be6e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(hervyqa): `""`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```console
➜  ~ spyder
fromIccProfile: failed minimal tag size sanity
Traceback (most recent call last):
  File "/nix/store/rc88hjv9rbjvcmp92mlxi7vj9qi5xm7k-python3.11-spyder-5.5.0/bin/..spyder-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/rc88hjv9rbjvcmp92mlxi7vj9qi5xm7k-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/start.py", line 244, in main
    mainwindow.main(options, args)
  File "/nix/store/rc88hjv9rbjvcmp92mlxi7vj9qi5xm7k-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 1847, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rc88hjv9rbjvcmp92mlxi7vj9qi5xm7k-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/utils.py", line 289, in create_window
    main.setup()
  File "/nix/store/rc88hjv9rbjvcmp92mlxi7vj9qi5xm7k-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 752, in setup
    internal_plugins = find_internal_plugins()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rc88hjv9rbjvcmp92mlxi7vj9qi5xm7k-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/app/find_plugins.py", line 40, in find_internal_plugins
    mod = importlib.import_module(entry_point.module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/rc88hjv9rbjvcmp92mlxi7vj9qi5xm7k-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/plugin.py", line 22, in <module>
    from spyder.plugins.pylint.confpage import PylintConfigPage
  File "/nix/store/rc88hjv9rbjvcmp92mlxi7vj9qi5xm7k-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/confpage.py", line 16, in <module>
    from spyder.plugins.pylint.main_widget import (MAX_HISTORY_ENTRIES,
  File "/nix/store/rc88hjv9rbjvcmp92mlxi7vj9qi5xm7k-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/main_widget.py", line 90, in <module>
    class CategoryItem(QTreeWidgetItem):
  File "/nix/store/rc88hjv9rbjvcmp92mlxi7vj9qi5xm7k-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/plugins/pylint/main_widget.py", line 102, in CategoryItem
    'icon': ima.icon("convention")
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rc88hjv9rbjvcmp92mlxi7vj9qi5xm7k-python3.11-spyder-5.5.0/lib/python3.11/site-packages/spyder/utils/icon_manager.py", line 439, in icon
    kwargs['color_disabled'] = QStylePalette.COLOR_DISABLED
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DarkPalette' has no attribute 'COLOR_DISABLED'
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hervyqa** [comment]
duplicate #270899
