### ISSUE TITLE
Ludusavi v0.21.0 requires setting ICED_BACKEND variable to tiny-skia in order to function/Vulkan support is broken

### ISSUE THREAD

**Issue by NovaViper** [NixOS/nixpkgs#273626]
### Describe the bug
When trying to open ludusavi since v0.21.0, it immediately crashes with a segmentation fault error. Found this [issue](https://github.com/mtkennerly/ludusavi/issues/271) and asked about it there as well. The main developer came out and said that it may be necessary to switch the software renderer for Rust (by setting `ICED_BACKEND` set to `tiny-skia`); which did fix the issue. But now the package itself requires the change in order for ludusavi to function properly. My system's using a Nvidia RTX 2600 6GB with a AMD Ryzen 5600G

### Steps To Reproduce
1. Install ludusavi v0.21.0
2. Try to open ludusavi
3. Error occurs

### Expected behavior
The applications should just open normally

### Screenshots
N/A

### Additional context
This is the particular segmentation fault I had
```
❯ ludusavi
libEGL warning: egl: failed to create dri2 screen
thread 'main' panicked at 'Failed to call XMapRaised: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 147, minor_code: 4 }', /build/ludusavi-0.21.0-vendor.tar.gz/winit/src/platform_impl/linux/x11/window.rs:1028:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /build/ludusavi-0.21.0-vendor.tar.gz/winit/src/platform_impl/linux/x11/window.rs:513:34
stack backtrace:
   0:     0x5633d8aa6000 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0f67236053551eca
   1:     0x5633d8ad5e9f - core::fmt::write::h13a8faf14f1ccf50
   2:     0x5633d8a9e027 - std::io::Write::write_fmt::ha1e4f1bb6310f8b3
   3:     0x5633d8aa5e05 - std::sys_common::backtrace::print::hda0e459003c3497e
   4:     0x5633d8a8ad71 - std::panicking::default_hook::{{closure}}::h9fb0f39f8a4b4896
   5:     0x5633d8a8aa0f - std::panicking::default_hook::h74777d9c83f82eb3
   6:     0x5633d8a8b219 - std::panicking::rust_panic_with_hook::h5a53706624030272
   7:     0x5633d8aa62e7 - std::panicking::begin_panic_handler::{{closure}}::h3941e21c138a8c98
   8:     0x5633d8aa60d6 - std::sys_common::backtrace::__rust_end_short_backtrace::h5d3e0e241a65e49e
   9:     0x5633d8a8af42 - rust_begin_unwind
  10:     0x5633d7c38b43 - core::panicking::panic_fmt::h396c35e980c19b34
  11:     0x5633d7c38fd3 - core::result::unwrap_failed::h788e567f8340e094
  12:     0x5633d83a96b2 - <winit::window::Window as core::ops::drop::Drop>::drop::hcae3b48a3e84cf8e
  13:     0x5633d7e9f5bd - core::ptr::drop_in_place<winit::window::Window>::ha7663fbebb120c55
  14:     0x5633d7e982a0 - iced_winit::application::run::{{closure}}::h0843cf3c0b01f12c
  15:     0x5633d7dc9faf - winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration::h91adf92b4cb4f4dd
  16:     0x5633d7dca78b - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h86fdb6d28c54c5f1
  17:     0x5633d7e6ca23 - iced_winit::application::run::h8852d96e0d85bc9b
  18:     0x5633d7dc8509 - iced::application::Application::run::he544ecadb1525e0a
  19:     0x5633d7f3c70a - ludusavi::gui::run::h68416a04a7288720
  20:     0x5633d7daca94 - ludusavi::main::h341e2647d050c622
  21:     0x5633d7e71f03 - std::sys_common::backtrace::__rust_begin_short_backtrace::h68a43dd8b10dd4db
  22:     0x5633d7d0b779 - std::rt::lang_start::{{closure}}::h7ace8141350a8b79
  23:     0x5633d8a7fc27 - std::rt::lang_start_internal::h7910e71d80e7bec3
  24:     0x5633d7daef95 - main
  25:     0x7fe12a979fce - __libc_start_call_main
  26:     0x7fe12a97a089 - __libc_start_main_impl
  27:     0x5633d7c39215 - _start
  28:                0x0 - <unknown>
thread 'main' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:     0x5633d8aa6000 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0f67236053551eca
   1:     0x5633d8ad5e9f - core::fmt::write::h13a8faf14f1ccf50
   2:     0x5633d8a9e027 - std::io::Write::write_fmt::ha1e4f1bb6310f8b3
   3:     0x5633d8aa5e05 - std::sys_common::backtrace::print::hda0e459003c3497e
   4:     0x5633d8a8ad71 - std::panicking::default_hook::{{closure}}::h9fb0f39f8a4b4896
   5:     0x5633d8a8aa0f - std::panicking::default_hook::h74777d9c83f82eb3
   6:     0x5633d8a8b219 - std::panicking::rust_panic_with_hook::h5a53706624030272
   7:     0x5633d8aa62a1 - std::panicking::begin_panic_handler::{{closure}}::h3941e21c138a8c98
   8:     0x5633d8aa60d6 - std::sys_common::backtrace::__rust_end_short_backtrace::h5d3e0e241a65e49e
   9:     0x5633d8a8af42 - rust_begin_unwind
  10:     0x5633d7c38b83 - core::panicking::panic_nounwind_fmt::hef637a7d457f403d
  11:     0x5633d7c38c27 - core::panicking::panic_nounwind::h23ae16224ab91a02
  12:     0x5633d7c38cc3 - core::panicking::panic_cannot_unwind::h7c2525e4b42392b3
  13:     0x5633d7e9837f - iced_winit::application::run::{{closure}}::h0843cf3c0b01f12c
  14:     0x5633d7dc9faf - winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration::h91adf92b4cb4f4dd
  15:     0x5633d7dca78b - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h86fdb6d28c54c5f1
  16:     0x5633d7e6ca23 - iced_winit::application::run::h8852d96e0d85bc9b
  17:     0x5633d7dc8509 - iced::application::Application::run::he544ecadb1525e0a
  18:     0x5633d7f3c70a - ludusavi::gui::run::h68416a04a7288720
  19:     0x5633d7daca94 - ludusavi::main::h341e2647d050c622
  20:     0x5633d7e71f03 - std::sys_common::backtrace::__rust_begin_short_backtrace::h68a43dd8b10dd4db
  21:     0x5633d7d0b779 - std::rt::lang_start::{{closure}}::h7ace8141350a8b79
  22:     0x5633d8a7fc27 - std::rt::lang_start_internal::h7910e71d80e7bec3
  23:     0x5633d7daef95 - main
  24:     0x7fe12a979fce - __libc_start_call_main
  25:     0x7fe12a97a089 - __libc_start_main_impl
  26:     0x5633d7c39215 - _start
  27:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
[1]    41147 abort (core dumped)  ludusavi
```

### Notify maintainers
@pasqui23

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.4, NixOS, 24.05 (Uakari), 24.05.20231204.2c7f3c0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/aiv01710wqn2b7hms2253d1cq89kdzh8-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NovaViper** [comment]
> Can't reproduce. Ludusavi launches with no problem on my end.
> 
> Using KDE Plasma, tested both X11 and Wayland.
> 
> Since you mentioned GPUs in the other issue, my GPU is an AMD RX 6700 XT.
> 
> 

I think that has to be the core of the issue, because on my laptop it works fine (it has a Intel iGPU) while the desktop on the other hand, the one that has the issue, has an Nvidia RTX 2600 🤔

**Comment by KucharczykL** [comment]
Hi, I have just ran into this or similar issue. Switching to OpenGL backend via setting `WGPU_BACKEND=gl` makes it possible to run the application but UI interaction is slow.

I have an internal AMD GPU and dedicated Nvidia GPU (default).

```
>ludusavi
[destroyed object]: error 7: importing the supplied dmabufs failed
Protocol error 7 on object @0: 

thread 'main' panicked at /build/ludusavi-0.28.0-vendor/wgpu-core-0.19.4/src/device/global.rs:1859:21:
internal error: entered unreachable code: Fallback system failed to choose present mode. This is a bug. Mode: AutoVsync, Options: []
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tokio-runtime-worker' panicked at /build/ludusavi-0.28.0-vendor/futures-util-0.3.31/src/stream/stream/select_next_some.rs:32:9:
SelectNextSome polled after terminated
```

**Comment by KucharczykL** [comment]
For reference:
- https://github.com/mtkennerly/ludusavi/issues/481
- https://github.com/NixOS/nixpkgs/issues/402395
- https://github.com/gfx-rs/wgpu/issues/6159

**Comment by KucharczykL** [comment]
> Does setting the `WGPU_POWER_PREF` environment variable to `high` work for you? I'm planning to make that enabled by default in the next release.

Yes, it works for me!

**Comment by NovaViper** [comment]
🤔 I actually had the issue go away for me randomly one day a bit ago (apparently last year [based on my commit history](https://github.com/NovaViper/NixConfig/commit/d195d2b2a032330e08db5825d5c90d143cbb6c70)?) I completely forgot to report on it 😭

**Comment by mtkennerly** [comment]
Ludusavi v0.30.0 now automatically sets `WGPU_POWER_PREF=high`. I'm sure this won't fix it on all systems, but hopefully it will help!
