### ISSUE TITLE
rustPlatform: unsupported features causing build failure

### ISSUE THREAD

**Issue by nyabinary** [NixOS/nixpkgs#274490]
### Describe the bug
rustPlatform doesn't support all workspaces features that Iced-rs requires.
Specifically, I believe it's this commit (but I'm not entirely sure if that is the problem) that the tooling doesn't support: https://github.com/iced-rs/iced/commit/f468e25

### Steps To Reproduce
1. Clone #271805
2. Execute ``nix build .#cosmic-settings``
3. Profit

### Expected behavior
That the build executes successfully.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/97130632/643eb18a-1fda-4418-887c-e65045c7070d)

### Additional context
Console output:
```console
~/Documents/nixpkgs/pkgs/by-name/co/cosmic-settings> nix build .#cosmic-settings                                                                                                                           
path '/home/binary/Documents/nixpkgs/pkgs/by-name/co/cosmic-settings' does not contain a 'flake.nix', searching up
warning: found empty hash, assuming 'sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
error: builder for '/nix/store/ccpng856vmppibiddr81yzagf1zvxcnk-iced_futures-0.12.0.drv' failed with exit code 1;
       last 10 log lines:
       > Traceback (most recent call last):
       >   File "/nix/store/j2sb5wf41x4z7cb8ywvhdigk729kywid-replace-workspace-values", line 108, in <module>
       >     main()
       >   File "/nix/store/j2sb5wf41x4z7cb8ywvhdigk729kywid-replace-workspace-values", line 88, in main
       >     changed |= replace_key(
       >                ^^^^^^^^^^^^
       >   File "/nix/store/j2sb5wf41x4z7cb8ywvhdigk729kywid-replace-workspace-values", line 32, in replace_key
       >     workspace_copy = workspace_manifest[section][key]
       >                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^
       > KeyError: 'package'
       For full logs, run 'nix log /nix/store/ccpng856vmppibiddr81yzagf1zvxcnk-iced_futures-0.12.0.drv'.
warning: killing stray builder process 978897 ()...
warning: killing stray builder process 979072 ()...
warning: killing stray builder process 978788 ()...
warning: killing stray builder process 979249 ()...
warning: killing stray builder process 979250 ()...
warning: killing stray builder process 979251 ()...
warning: killing stray builder process 978749 (bash -e /nix/store/v6x3cs394jgqfbi0a42pam708flxaphh-default-builder.sh)...
warning: killing stray builder process 979261 ()...
warning: killing stray builder process 978719 ()...
warning: killing stray builder process 979267 ()...
warning: killing stray builder process 978693 ()...
warning: killing stray builder process 979258 ()...
error: 1 dependencies of derivation '/nix/store/1sxhc8wjzcnfqpcywrfx08hpcmxf2gv6-cargo-vendor-dir.drv' failed to build
warning: killing stray builder process 978858 ()...
warning: killing stray builder process 979009 ()...
error: 1 dependencies of derivation '/nix/store/b37czlr5lzg15wki69f80kbgbg9c3hdl-cosmic-settings-unstable-2023-12-14.drv' failed to build
```

### Notify maintainers
@alyssais 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.6, NixOS, 24.05 (Uakari), 24.05.20231211.a9bf124`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lilyinstarlight** [comment]
Fix is in #276072
