### ISSUE TITLE
playwright-driver.browsers broken on Darwin

### ISSUE THREAD

**Issue by zupo** [NixOS/nixpkgs#274537]
### Describe the bug

Installing `playwright-driver.browsers` fails on Darwin for both 23.11 and unstable channels.

### Steps To Reproduce

```console
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz nix-shell -p playwright-driver.browsers
```

<details open>
  <summary>Log</summary>

  ```
  ➜  ~ NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz nix-shell -p playwright-driver.browsers

  this derivation will be built:
    /nix/store/6wa7bzlp5a128jgk2kfapi8k4908f9rr-playwright-browsers-1.40.0.drv
  this path will be fetched (1.02 MiB download, 8.06 MiB unpacked):
    /nix/store/8rxm4jzw1dddm53rpc2zdqgafadn7d5n-bash-interactive-5.2-p21
  copying path '/nix/store/8rxm4jzw1dddm53rpc2zdqgafadn7d5n-bash-interactive-5.2-p21' from 'https://cache.nixos.org'...
  building '/nix/store/6wa7bzlp5a128jgk2kfapi8k4908f9rr-playwright-browsers-1.40.0.drv'...
  Running phase: patchPhase
  Running phase: updateAutotoolsGnuConfigScriptsPhase
  Running phase: configurePhase
  no configure script, doing nothing
  Running phase: buildPhase
  no Makefile or custom buildPhase, doing nothing
  Running phase: installPhase
  Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip
  Error: self-signed certificate in certificate chain
      at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
      at TLSSocket.emit (node:events:514:28)
      at TLSSocket._finishInit (node:_tls_wrap:1085:8)
      at ssl.onhandshakedone (node:_tls_wrap:871:12) {
    code: 'SELF_SIGNED_CERT_IN_CHAIN'
  }
  Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright-akamai.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip
  Error: self-signed certificate in certificate chain
      at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
      at TLSSocket.emit (node:events:514:28)
      at TLSSocket._finishInit (node:_tls_wrap:1085:8)
      at ssl.onhandshakedone (node:_tls_wrap:871:12) {
    code: 'SELF_SIGNED_CERT_IN_CHAIN'
  }
  Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright-verizon.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip
  Error: self-signed certificate in certificate chain
      at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
      at TLSSocket.emit (node:events:514:28)
      at TLSSocket._finishInit (node:_tls_wrap:1085:8)
      at ssl.onhandshakedone (node:_tls_wrap:871:12) {
    code: 'SELF_SIGNED_CERT_IN_CHAIN'
  }
  Failed to install browsers
  Error: Failed to download Chromium 120.0.6099.28 (playwright build v1091), caused by
  Error: Download failure, code=1
      at ChildProcess.<anonymous> (/nix/store/rmz79vwif3iccnsjf5s0yzsj8v1iqnv7-playwright-driver-1.40.0/package/lib/server/registry/browserFetcher.js:91:16)
      at ChildProcess.emit (node:events:514:28)
      at ChildProcess._handle.onexit (node:internal/child_process:294:12)
  error: builder for '/nix/store/6wa7bzlp5a128jgk2kfapi8k4908f9rr-playwright-browsers-1.40.0.drv' failed with exit code 1;
        last 25 log lines:
        >     at ssl.onhandshakedone (node:_tls_wrap:871:12) {
        >   code: 'SELF_SIGNED_CERT_IN_CHAIN'
        > }
        > Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright-akamai.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip
        > Error: self-signed certificate in certificate chain
        >     at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
        >     at TLSSocket.emit (node:events:514:28)
        >     at TLSSocket._finishInit (node:_tls_wrap:1085:8)
        >     at ssl.onhandshakedone (node:_tls_wrap:871:12) {
        >   code: 'SELF_SIGNED_CERT_IN_CHAIN'
        > }
        > Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright-verizon.azureedge.net/builds/chromium/1091/chromium-mac-arm64.zip
        > Error: self-signed certificate in certificate chain
        >     at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
        >     at TLSSocket.emit (node:events:514:28)
        >     at TLSSocket._finishInit (node:_tls_wrap:1085:8)
        >     at ssl.onhandshakedone (node:_tls_wrap:871:12) {
        >   code: 'SELF_SIGNED_CERT_IN_CHAIN'
        > }
        > Failed to install browsers
        > Error: Failed to download Chromium 120.0.6099.28 (playwright build v1091), caused by
        > Error: Download failure, code=1
        >     at ChildProcess.<anonymous> (/nix/store/rmz79vwif3iccnsjf5s0yzsj8v1iqnv7-playwright-driver-1.40.0/package/lib/server/registry/browserFetcher.js:91:16)
        >     at ChildProcess.emit (node:events:514:28)
        >     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
        For full logs, run 'nix log /nix/store/6wa7bzlp5a128jgk2kfapi8k4908f9rr-playwright-browsers-1.40.0.drv'.
  ```
</details>

```console
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-23.11.tar.gz nix-shell -p playwright-driver.browsers
```

<details open>
  <summary>Log</summary>

  ```
➜  ~ NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-23.11.tar.gz nix-shell -p playwright-driver.browsers
this derivation will be built:
  /nix/store/28cxrks9hx6rb9kixbiijgn2sifwnxkr-playwright-browsers-1.38.0.drv
building '/nix/store/28cxrks9hx6rb9kixbiijgn2sifwnxkr-playwright-browsers-1.38.0.drv'...
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
no configure script, doing nothing
building
no Makefile or custom buildPhase, doing nothing
installing
Downloading Chromium 117.0.5938.62 (playwright build v1080) from https://playwright.azureedge.net/builds/chromium/1080/chromium-mac-arm64.zip
Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket._finishInit (node:_tls_wrap:1017:8)
    at ssl.onhandshakedone (node:_tls_wrap:803:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
Downloading Chromium 117.0.5938.62 (playwright build v1080) from https://playwright-akamai.azureedge.net/builds/chromium/1080/chromium-mac-arm64.zip
Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket._finishInit (node:_tls_wrap:1017:8)
    at ssl.onhandshakedone (node:_tls_wrap:803:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
Downloading Chromium 117.0.5938.62 (playwright build v1080) from https://playwright-verizon.azureedge.net/builds/chromium/1080/chromium-mac-arm64.zip
Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket._finishInit (node:_tls_wrap:1017:8)
    at ssl.onhandshakedone (node:_tls_wrap:803:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
Failed to install browsers
Error: Failed to download Chromium 117.0.5938.62 (playwright build v1080), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (/nix/store/r28nfi7lcnw07ypv0fwvkwa3cllf2707-playwright-driver-1.38.0/package/lib/server/registry/browserFetcher.js:91:16)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
error: builder for '/nix/store/28cxrks9hx6rb9kixbiijgn2sifwnxkr-playwright-browsers-1.38.0.drv' failed with exit code 1;
       last 25 log lines:
       >     at ssl.onhandshakedone (node:_tls_wrap:803:12) {
       >   code: 'SELF_SIGNED_CERT_IN_CHAIN'
       > }
       > Downloading Chromium 117.0.5938.62 (playwright build v1080) from https://playwright-akamai.azureedge.net/builds/chromium/1080/chromium-mac-arm64.zip
       > Error: self-signed certificate in certificate chain
       >     at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)
       >     at TLSSocket.emit (node:events:517:28)
       >     at TLSSocket._finishInit (node:_tls_wrap:1017:8)
       >     at ssl.onhandshakedone (node:_tls_wrap:803:12) {
       >   code: 'SELF_SIGNED_CERT_IN_CHAIN'
       > }
       > Downloading Chromium 117.0.5938.62 (playwright build v1080) from https://playwright-verizon.azureedge.net/builds/chromium/1080/chromium-mac-arm64.zip
       > Error: self-signed certificate in certificate chain
       >     at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)
       >     at TLSSocket.emit (node:events:517:28)
       >     at TLSSocket._finishInit (node:_tls_wrap:1017:8)
       >     at ssl.onhandshakedone (node:_tls_wrap:803:12) {
       >   code: 'SELF_SIGNED_CERT_IN_CHAIN'
       > }
       > Failed to install browsers
       > Error: Failed to download Chromium 117.0.5938.62 (playwright build v1080), caused by
       > Error: Download failure, code=1
       >     at ChildProcess.<anonymous> (/nix/store/r28nfi7lcnw07ypv0fwvkwa3cllf2707-playwright-driver-1.38.0/package/lib/server/registry/browserFetcher.js:91:16)
       >     at ChildProcess.emit (node:events:517:28)
       >     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
       For full logs, run 'nix log /nix/store/28cxrks9hx6rb9kixbiijgn2sifwnxkr-playwright-browsers-1.38.0.drv'.
  ```
</details>

### Expected behavior

Installation works fine on Linux. 

<details open>
  <summary>Log</summary>

```
runner@hafq3vr2v84pk:~/work/app/app$ NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz nix-shell -p playwright-driver.browsers

[nix-shell:~/work/app/app]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/zzjrl1zzc0lbwlc8dvs98l5k906cwd7z-nix-info
copying path '/nix/store/zzjrl1zzc0lbwlc8dvs98l5k906cwd7z-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/store/yxld2qw84ka591fay1xkh5jflbgxjqa1-source`

[nix-shell:~/work/app/app]$ 
```
</details>

### Notify maintainers

@yrd
@techknowlogick

### Metadata

  ```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
➜  ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.1.0, macOS 14.1.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/chi01x4fh8hx7wwh0rqd7m1c8583iyhv-source`
  ```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by phaer** [comment]
Should be fixed for unstable as of https://github.com/NixOS/nixpkgs/pull/274477.
