### ISSUE TITLE
Qutebrowser breaks when python is installed with matplotlib

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#27460]
## Issue description
Qutebrowser has run fine for me for a while now, but at some point recently I needed matplotlib for something, so I added it to my python package (which should in theory be completely isolated from qutebrowser) and qutebrowser stopped being able to open new windows (though old windows still worked)

### Steps to reproduce
Put both `qutebrowser` and `(python.withPackages (p: with p; [ matplotlib ]))` in your `/etc/nixos/configuration.nix`, and then try to run `qutebrowser` from the command line.
I get this error:
```
Traceback (most recent call last):
  File "/nix/store/sph31ba4yz6is3diypl4pic71hdm5lh3-qutebrowser-0.10.1/bin/..qutebrowser-wrapped-wrapped", line 8, in <module>
    from qutebrowser.qutebrowser import main
  File "/nix/store/sph31ba4yz6is3diypl4pic71hdm5lh3-qutebrowser-0.10.1/lib/python3.6/site-packages/qutebrowser/qutebrowser.py", line 43, in <module>
    from qutebrowser.misc import earlyinit
  File "/nix/store/sph31ba4yz6is3diypl4pic71hdm5lh3-qutebrowser-0.10.1/lib/python3.6/site-packages/qutebrowser/misc/earlyinit.py", line 39, in <module>
    import pkg_resources
  File "/run/current-system/sw/lib/python2.7/site-packages/setuptools-36.0.1-py2.7.egg/pkg_resources/__init__.py", line 33, in <module>
  File "/nix/store/v96ayp4hp476fqabmx86vgvwcn8wb7f9-python3-3.6.1/lib/python3.6/platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "/nix/store/v96ayp4hp476fqabmx86vgvwcn8wb7f9-python3-3.6.1/lib/python3.6/subprocess.py", line 136, in <module>
    import _posixsubprocess
ImportError: dynamic module does not define module export function (PyInit__posixsubprocess)
```

## Technical details

* System: 17.09pre110213.01c3847b9c (Hummingbird)
* Nix version: nix-env (Nix) 1.11.11
* Nixpkgs version: "17.09pre110213.01c3847b9c"
* Sandboxing enabled: build-use-sandbox = true

**Comment by Radvendii** [comment]
@jagajaga I'm tagging you because you're listed as the maintainer of the package.

**Comment by FRidh** [comment]
Likely an impurity / broken wrapper in qutebrowser. cc @abbradar

**Comment by manveru** [comment]
Is this still an issue? I can't reproduce it.
