### ISSUE TITLE
Tutanota Desktop not saving credentials (better-sqlite3.node different Node.js version error)

### ISSUE THREAD

**Issue by CactiChameleon9** [NixOS/nixpkgs#278072]
### Describe the bug
When I open tutanota-desktop I am asked for my credentials every time despite ticking "Store Password"
After signing in with my details I get an error prompt (which I can dismiss) containing the following details:

```
Feedback v3.119.3 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.119.3
 Timestamp (UTC): Mon, 01 Jan 2024 14:21:32 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.119.3 Chrome/120.0.6099.109 Electron/28.1.0 Safari/537.36
Error
 Error message: The module '/nix/store/8b7azpr9zc9nhyx92qaampdp55p04dww-tutanota-desktop-3.119.3/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better-sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 116. This version of Node.js requires
NODE_MODULE_VERSION 119. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
Stacktrace: 
Error: The module '/nix/store/8b7azpr9zc9nhyx92qaampdp55p04dww-tutanota-desktop-3.119.3/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better-sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 116. This version of Node.js requires
NODE_MODULE_VERSION 119. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2238)
    at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2465)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at new V (/nix/store/8b7azpr9zc9nhyx92qaampdp55p04dww-tutanota-desktop-3.119.3/share/tutanota-desktop/resources/app.asar/desktop/sqlworker.js:1:10680)
    at H.openDb (/nix/store/8b7azpr9zc9nhyx92qaampdp55p04dww-tutanota-desktop-3.119.3/share/tutanota-desktop/resources/app.asar/desktop/sqlworker.js:1:22632)
```

I am assuming this means that Tutanota store any data, including my login details, because the database is broken

### Steps To Reproduce
1. Open Tutanota
2. Login, store password
3. See error dialog
4. Close Tutanota
5. Reopen Tutanota, and you will need to sign in again

### Expected behavior
No errors, and I don't need to sign in every time

### Notify maintainers

@WolfangAukang

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 23.11 (Tapir), 23.11.2413.32f63574c85f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by WolfangAukang** [comment]
The main problem here is that we use the binaries offered by Tuta to package this, so we are not compiling anything. According to what I've checked, there could be two reasons:
- As we wrap the `app.asar` with Electron, the `NODE_MODULE_VERSION` from Electron might collide with the one expected by the application. Problem here is that we use the latest Electron version on nixpkgs for packaging Tutanota. You could try it from unstable to see if it works, but it is just a shot in the dark.
- Improbable, but this could be a packaging issue from Tutanota.

**Comment by WolfangAukang** [comment]
Testing with what I currently have (building from nixpkgs-unstable, Tutanota 3.119.3), I get another issue, also about `better-sqlite`, but is related with self-registering:

```
Feedback v3.119.10 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.119.10
 Timestamp (UTC): Fri, 05 Jan 2024 16:07:24 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.119.10 Chrome/120.0.6099.109 Electron/28.1.0 Safari/537.36
Error
 Error message: Module did not self-register: '/nix/store/cq47p45445fd39i21m23vj5jmhf6nppb-tutanota-desktop-3.119.10/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better-sqlite3.node'.
Stacktrace: 
Error: Module did not self-register: '/nix/store/cq47p45445fd39i21m23vj5jmhf6nppb-tutanota-desktop-3.119.10/share/tutanota-desktop/resources/app.asar.unpacked/desktop/better-sqlite3.node'.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2238)
    at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2465)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at new V (/nix/store/cq47p45445fd39i21m23vj5jmhf6nppb-tutanota-desktop-3.119.10/share/tutanota-desktop/resources/app.asar/desktop/sqlworker.js:1:10681)
    at H.openDb (/nix/store/cq47p45445fd39i21m23vj5jmhf6nppb-tutanota-desktop-3.119.10/share/tutanota-desktop/resources/app.asar/desktop/sqlworker.js:1:22587)
```

Password get stored though.
