### ISSUE TITLE
RuntimeError: The Secret Service daemon is neither running nor activatable through D-Bus

### ISSUE THREAD

**Issue by Xbz-24** [NixOS/nixpkgs#280203]
### Describe the bug
I get this screen when opening protonvpn-gui

❯ protonvpn-app
2024-01-11T06:50:17.769260 | proton.vpn.app.gtk.app:58 | INFO | APP:PROCESS_START | self=<app.App object at 0x7f19c015a940 (proton+vpn+app+gtk+app+App at 0x12b57c0)>
Traceback (most recent call last):
  File "/nix/store/mq257mjiz6d92ggnpx41401cvsmivjib-python3.11-secretstorage-3.3.3/lib/python3.11/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.ServiceUnknown] ('The name org.freedesktop.secrets was not provided by any .service files',)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/lhgzgiiydx87gygn65wq021sw7487k1x-python3.11-keyring-24.3.0/lib/python3.11/site-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collection
    collection = secretstorage.get_default_collection(bus)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/mq257mjiz6d92ggnpx41401cvsmivjib-python3.11-secretstorage-3.3.3/lib/python3.11/site-packages/secretstorage/collection.py", line 177, in get_default_collection
    return Collection(connection)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/mq257mjiz6d92ggnpx41401cvsmivjib-python3.11-secretstorage-3.3.3/lib/python3.11/site-packages/secretstorage/collection.py", line 45, in __init__
    self._collection.get_property('Label')
  File "/nix/store/mq257mjiz6d92ggnpx41401cvsmivjib-python3.11-secretstorage-3.3.3/lib/python3.11/site-packages/secretstorage/util.py", line 67, in get_property
    (signature, value), = self.send_and_get_reply(msg)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/mq257mjiz6d92ggnpx41401cvsmivjib-python3.11-secretstorage-3.3.3/lib/python3.11/site-packages/secretstorage/util.py", line 58, in send_and_get_reply
    raise SecretServiceNotAvailableException(data) from resp
secretstorage.exceptions.SecretServiceNotAvailableException: The name org.freedesktop.secrets was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/kjndhnlzhjx78js1bcqkkn2c8k4k2q1l-python3.11-proton-keyring-linux-0.0.1-unstable-2023-04-14/lib/python3.11/site-packages/proton/keyring_linux/core/keyring_linux.py", line 99, in _is_backend_working
    keyring_backend.get_password(
  File "/nix/store/lhgzgiiydx87gygn65wq021sw7487k1x-python3.11-keyring-24.3.0/lib/python3.11/site-packages/keyring/backends/SecretService.py", line 78, in get_password
    collection = self.get_preferred_collection()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lhgzgiiydx87gygn65wq021sw7487k1x-python3.11-keyring-24.3.0/lib/python3.11/site-packages/keyring/backends/SecretService.py", line 63, in get_preferred_collection
    raise InitError("Failed to create the collection: %s." % e)
keyring.errors.InitError: Failed to create the collection: The name org.freedesktop.secrets was not provided by any .service files.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/934c0kp3k4wkg89s4ckw7gpklq3mpn77-protonvpn-gui-4.1.0-unstable-2023-10-25/lib/python3.11/site-packages/proton/vpn/app/gtk/app.py", line 97, in do_activate
    self.tray_indicator = self._build_tray_indicator_if_possible(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/934c0kp3k4wkg89s4ckw7gpklq3mpn77-protonvpn-gui-4.1.0-unstable-2023-10-25/lib/python3.11/site-packages/proton/vpn/app/gtk/app.py", line 198, in _build_tray_indicator_if_possible
    return TrayIndicator(controller, main_window)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/934c0kp3k4wkg89s4ckw7gpklq3mpn77-protonvpn-gui-4.1.0-unstable-2023-10-25/lib/python3.11/site-packages/proton/vpn/app/gtk/widgets/main/tray_indicator.py", line 118, in __init__
    self._menu = self._build_menu()
                 ^^^^^^^^^^^^^^^^^^
  File "/nix/store/934c0kp3k4wkg89s4ckw7gpklq3mpn77-protonvpn-gui-4.1.0-unstable-2023-10-25/lib/python3.11/site-packages/proton/vpn/app/gtk/widgets/main/tray_indicator.py", line 221, in _build_menu
    if self._controller.user_logged_in:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/934c0kp3k4wkg89s4ckw7gpklq3mpn77-protonvpn-gui-4.1.0-unstable-2023-10-25/lib/python3.11/site-packages/proton/vpn/app/gtk/controller.py", line 119, in user_logged_in
    return self._api.is_user_logged_in()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/c3pzwy2c9134kakd8blw7m7fisb1armf-python3.11-proton-vpn-api-core-0.20.1-unstable-2023-10-10/lib/python3.11/site-packages/proton/vpn/core/api.py", line 73, in is_user_logged_in
    return self._session_holder.session.logged_in
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/c3pzwy2c9134kakd8blw7m7fisb1armf-python3.11-proton-vpn-api-core-0.20.1-unstable-2023-10-10/lib/python3.11/site-packages/proton/vpn/core/session.py", line 76, in session
    self._session = self._proton_sso.get_default_session(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rvy3vjyksnv4ij3isivavnrpkbaa77r8-python3.11-proton-core-0.1.15-unstable-2023-10-24/lib/python3.11/site-packages/proton/sso/sso.py", line 192, in get_default_session
    sessions = self.sessions
               ^^^^^^^^^^^^^
  File "/nix/store/rvy3vjyksnv4ij3isivavnrpkbaa77r8-python3.11-proton-core-0.1.15-unstable-2023-10-24/lib/python3.11/site-packages/proton/sso/sso.py", line 130, in sessions
    keyring = self._keyring
              ^^^^^^^^^^^^^
  File "/nix/store/rvy3vjyksnv4ij3isivavnrpkbaa77r8-python3.11-proton-core-0.1.15-unstable-2023-10-24/lib/python3.11/site-packages/proton/sso/sso.py", line 111, in _keyring
    self.__keyring_backend = Keyring.get_from_factory()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rvy3vjyksnv4ij3isivavnrpkbaa77r8-python3.11-proton-core-0.1.15-unstable-2023-10-24/lib/python3.11/site-packages/proton/keyring/_base.py", line 49, in get_from_factory
    keyring_backend = Loader.get("keyring", class_name=backend)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rvy3vjyksnv4ij3isivavnrpkbaa77r8-python3.11-proton-core-0.1.15-unstable-2023-10-24/lib/python3.11/site-packages/proton/loader/loader.py", line 105, in get
    if entry.cls._validate():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/l0cbcfva25rv0v35mr8byms900fvwjkh-python3.11-proton-keyring-linux-secretservice-0.0.1-unstable-2023-04-14/lib/python3.11/site-packages/proton/keyring_linux/secretservice/secretservice_backend.py", line 40, in _validate
    return cls._is_backend_working(SecretService.Keyring())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kjndhnlzhjx78js1bcqkkn2c8k4k2q1l-python3.11-proton-keyring-linux-0.0.1-unstable-2023-04-14/lib/python3.11/site-packages/proton/keyring_linux/core/keyring_linux.py", line 108, in _is_backend_working
    logger.exception(f"Keyring \"{keyring_backend}\" error")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lhgzgiiydx87gygn65wq021sw7487k1x-python3.11-keyring-24.3.0/lib/python3.11/site-packages/keyring/backend.py", line 95, in __str__
    keyring_class.__module__, keyring_class.__name__, keyring_class.priority
                                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/82ly1bicbjy8nj7069z1x354p86a3mf4-python3.11-jaraco-classes-3.3.0/lib/python3.11/site-packages/jaraco/classes/properties.py", line 151, in __get__
    return self.fget.__get__(None, owner)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lhgzgiiydx87gygn65wq021sw7487k1x-python3.11-keyring-24.3.0/lib/python3.11/site-packages/keyring/backends/SecretService.py", line 43, in priority
    raise RuntimeError(
RuntimeError: The Secret Service daemon is neither running nor activatable through D-Bus

### Steps To Reproduce
just "protonvpn-app"

### Expected behavior
I was expecting to just open the protonvpn client!
### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/68678258/bc04dfdb-0fa4-46c1-aca9-b51696f8707f)
### Notify maintainers

@WolfangAukang

**Comment by Xbz-24** [comment]
this is from the unstable channel though

**Comment by Xbz-24** [comment]
nvm was missing keyring demon, added kwallet and it works now, sorry for the nuisance

**Comment by Atemu** [comment]
For those not wanting to run kwallet or *shudder* gnome-keyring for testing, keepassxc has an easy secret service integration.
