### ISSUE TITLE
python27Packes.acme tests fail on some hosts

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#28042]
## Issue description
Hi,

on one of my hosts the build of python27Packages.acme fails due to test errors (see below). On 2 other hosts it is working fine.

### Steps to reproduce
```
export NIX_PATH=nixpkgs=https://github.com/nixos/nixpkgs/archive/2f9724e804188bfbdf184631795fb130930cb0ec.tar.gz
nix-build '<nixpkgs>' --option build-use-chroot true --option build-use-sandbox true --keep-going -K -A python27Packages.acme
```

## Technical details
```
test_json_loads (acme.jose.interfaces_test.JSONDeSerializableTest) ... ok
test_to_json (acme.jose.interfaces_test.JSONDeSerializableTest) ... ok
test_to_json_mapping (acme.jose.interfaces_test.JSONDeSerializableTest) ... ok
test_to_json_nested (acme.jose.interfaces_test.JSONDeSerializableTest) ... ok
test_to_json_other (acme.jose.interfaces_test.JSONDeSerializableTest) ... ok
test_to_json_sequence (acme.jose.interfaces_test.JSONDeSerializableTest) ... ok
test_from_json (acme.jose.jwk_test.JWKOctTest) ... ok
test_from_json_hashable (acme.jose.jwk_test.JWKOctTest) ... ok
test_load (acme.jose.jwk_test.JWKOctTest) ... ok
test_public_key (acme.jose.jwk_test.JWKOctTest) ... ok
test_thumbprint_private (acme.jose.jwk_test.JWKOctTest) ... ok
test_thumbprint_public (acme.jose.jwk_test.JWKOctTest) ... ok
test_to_partial_json (acme.jose.jwk_test.JWKOctTest) ... ok
test_encode_param_zero (acme.jose.jwk_test.JWKRSATest) ... ok
test_equals (acme.jose.jwk_test.JWKRSATest) ... ok
test_from_json (acme.jose.jwk_test.JWKRSATest) ... ok
test_from_json_hashable (acme.jose.jwk_test.JWKRSATest) ... ok
test_from_json_missing_one_additional (acme.jose.jwk_test.JWKRSATest) ... ok
test_from_json_non_schema_errors (acme.jose.jwk_test.JWKRSATest) ... ok
test_from_json_private_small (acme.jose.jwk_test.JWKRSATest) ... ok
test_init_auto_comparable (acme.jose.jwk_test.JWKRSATest) ... ok
test_load (acme.jose.jwk_test.JWKRSATest) ... ok
test_not_equals (acme.jose.jwk_test.JWKRSATest) ... ok
test_public_key (acme.jose.jwk_test.JWKRSATest) ... ok
test_thumbprint_go_jose (acme.jose.jwk_test.JWKRSATest) ... ok
test_thumbprint_private (acme.jose.jwk_test.JWKRSATest) ... ok
test_thumbprint_public (acme.jose.jwk_test.JWKRSATest) ... ok
test_to_partial_json (acme.jose.jwk_test.JWKRSATest) ... ok
test_load (acme.jose.jwk_test.JWKTest) ... ok
test_load_subclass_wrong_type (acme.jose.jwk_test.JWKTest) ... ok
test_input_with_padding (acme.jose.b64_test.B64DecodeTest) ... ok
test_input_without_padding (acme.jose.b64_test.B64DecodeTest) ... ok
test_non_ascii_unicode_fails (acme.jose.b64_test.B64DecodeTest) ... ok
test_type_error_no_unicode_or_bytes (acme.jose.b64_test.B64DecodeTest) ... ok
test_unicode_with_ascii (acme.jose.b64_test.B64DecodeTest) ... ok
test_unsafe_url (acme.jose.b64_test.B64DecodeTest) ... ok
test_different_paddings (acme.jose.b64_test.B64EncodeTest) ... ok
test_empty (acme.jose.b64_test.B64EncodeTest) ... ok
test_unicode_fails_with_type_error (acme.jose.b64_test.B64EncodeTest) ... ok
test_unsafe_url (acme.jose.b64_test.B64EncodeTest) ... ok
test_404 (acme.standalone_test.HTTP01ServerTest) ... ERROR
test_http01_found (acme.standalone_test.HTTP01ServerTest) ... WARNING:acme.challenges:Using non-standard port for http-01 verification: 39113
ERROR:acme.challenges:Unable to reach http://localhost:39113/.well-known/acme-challenge/eHh4eHh4eHh4eHh4eHh4eA: HTTPConnectionPool(host='localhost', port=39113): Max retries exceeded with url: /.well-known/acme-challenge/eHh4eHh4eHh4eHh4eHh4eA (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fffefbb51d0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable',))
FAIL
test_http01_not_found (acme.standalone_test.HTTP01ServerTest) ... WARNING:acme.challenges:Using non-standard port for http-01 verification: 38897
ERROR:acme.challenges:Unable to reach http://localhost:38897/.well-known/acme-challenge/eHh4eHh4eHh4eHh4eHh4eA: HTTPConnectionPool(host='localhost', port=38897): Max retries exceeded with url: /.well-known/acme-challenge/eHh4eHh4eHh4eHh4eHh4eA (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fffefbb5ed0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable',))
ok
test_index (acme.standalone_test.HTTP01ServerTest) ... ERROR
test_it (acme.standalone_test.TLSSNI01ServerTest) ... ok
test_bind (acme.standalone_test.TLSServerTest) ... ok
test_it (acme.standalone_test.TestSimpleTLSSNI01Server) ... ok

======================================================================
ERROR: test_404 (acme.standalone_test.HTTP01ServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-acme-0.11.1.drv-5/certbot-v0.11.1-src/acme/acme/standalone_test.py", line 92, in test_404
    'http://localhost:{0}/foo'.format(self.port), verify=False)
  File "/nix/store/4czdg6vm1rfa08v50m7ypi6xhnk9wg4i-python2.7-requests-2.13.0/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/nix/store/4czdg6vm1rfa08v50m7ypi6xhnk9wg4i-python2.7-requests-2.13.0/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/nix/store/4czdg6vm1rfa08v50m7ypi6xhnk9wg4i-python2.7-requests-2.13.0/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/nix/store/4czdg6vm1rfa08v50m7ypi6xhnk9wg4i-python2.7-requests-2.13.0/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/nix/store/4czdg6vm1rfa08v50m7ypi6xhnk9wg4i-python2.7-requests-2.13.0/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=45183): Max retries exceeded with url: /foo (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fffefbc6b10>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable',))

======================================================================
ERROR: test_index (acme.standalone_test.HTTP01ServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-acme-0.11.1.drv-5/certbot-v0.11.1-src/acme/acme/standalone_test.py", line 85, in test_index
    'http://localhost:{0}'.format(self.port), verify=False)
  File "/nix/store/4czdg6vm1rfa08v50m7ypi6xhnk9wg4i-python2.7-requests-2.13.0/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/nix/store/4czdg6vm1rfa08v50m7ypi6xhnk9wg4i-python2.7-requests-2.13.0/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/nix/store/4czdg6vm1rfa08v50m7ypi6xhnk9wg4i-python2.7-requests-2.13.0/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/nix/store/4czdg6vm1rfa08v50m7ypi6xhnk9wg4i-python2.7-requests-2.13.0/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/nix/store/4czdg6vm1rfa08v50m7ypi6xhnk9wg4i-python2.7-requests-2.13.0/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=43237): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fffefba8f10>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable',))

======================================================================
FAIL: test_http01_found (acme.standalone_test.HTTP01ServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-acme-0.11.1.drv-5/certbot-v0.11.1-src/acme/acme/standalone_test.py", line 109, in test_http01_found
    self.assertTrue(self._test_http01(add=True))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 356 tests in 11.123s

FAILED (failures=1, errors=2)
Test failed: <unittest.runner.TextTestResult run=356 errors=2 failures=1>
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7ffff321d810>> ignored
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7ffff32d8710>> ignored
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7ffff108d0d0>> ignored
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7ffff101f490>> ignored
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7ffff0ffd1d0>> ignored
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7ffff109aed0>> ignored
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7ffff1072890>> ignored
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7ffff104e5d0>> ignored
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7ffff11dcf90>> ignored
error: Test failed: <unittest.runner.TextTestResult run=356 errors=2 failures=1>
note: keeping build directory ‘/tmp/nix-build-python2.7-acme-0.11.1.drv-5’
builder for ‘/nix/store/zsnlgjjdbpq1h4hxnj28fd76jn053z4h-python2.7-acme-0.11.1.drv’ failed with exit code 1
error: build of ‘/nix/store/zsnlgjjdbpq1h4hxnj28fd76jn053z4h-python2.7-acme-0.11.1.drv’ failed

```

**Comment by dotlambda** [comment]
@fadenb Is this still an issue? The acme package has been updated a couple of times.

**Comment by fadenb** [comment]
Have not seen this issue for a long time. But I also no longer have access to this machine. Let's close the issue for now :)
