### ISSUE TITLE
pypy derivations produce broken python installation for x86_64-linux

### ISSUE THREAD

**Issue by jab** [NixOS/nixpkgs#280855]
## Issue description

The `x86_64-linux` pypy installations provided by the `pypy3.10` and `pypy3.9` derivations are broken such that `python -m sysconfig` (or equivalently `pypy3 -m sysconfig`) fails with:

    ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'

This causes lots of other functionality in the standard library to fail, e.g. `python -m venv foo`, `python -m ensurepip`, etc.

<details>
<summary>(Click to toggle example trace from a GitHub Actions 'ubuntu-latest' runner)</summary>

```
(nix:nix-shell-env) runner@fv-az1498-25:~$ pypy3.10 -VV
Python 3.10.12 (af44d0b8114cb82c40a07bb9ee9c1ca8a1b3688c, Jan 03 2024, 06:33:26)
[PyPy 7.3.12 with GCC 13.2.0]

(nix:nix-shell-env) runner@fv-az1498-25:~$ pypy3.10 -m sysconfig
Platform: "linux-x86_64"
Python version: "3.10"
Current installation scheme: "posix_prefix"

Traceback (most recent call last):
  File "/nix/store/m9iaqdg9qhj2qja69g0ni103ds6dax10-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/runpy.py", line 199, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/m9iaqdg9qhj2qja69g0ni103ds6dax10-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/nix/store/m9iaqdg9qhj2qja69g0ni103ds6dax10-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 832, in <module>
    _main()
  File "/nix/store/m9iaqdg9qhj2qja69g0ni103ds6dax10-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 826, in _main
    _print_dict('Paths', get_paths())
                         ^^^^^^^^^^^
  File "/nix/store/m9iaqdg9qhj2qja69g0ni103ds6dax10-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 586, in get_paths
    return _expand_vars(scheme, vars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/m9iaqdg9qhj2qja69g0ni103ds6dax10-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 225, in _expand_vars
    _extend_dict(vars, get_config_vars())
                       ^^^^^^^^^^^^^^^^^
  File "/nix/store/m9iaqdg9qhj2qja69g0ni103ds6dax10-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 642, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/nix/store/m9iaqdg9qhj2qja69g0ni103ds6dax10-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 498, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'

(nix:nix-shell-env) runner@fv-az1498-25:~$ echo $?
1
```
</details>

### Steps to reproduce

Locally I can only test on 'aarch64-darwin' and this does not occur there, but I consistently reproduce this in GitHub Actions' 'ubuntu-latest' runners (which are x86_64) with Nix installed via https://github.com/DeterminateSystems/nix-installer-action, by running the following in an [SSH session](https://github.com/marketplace/actions/debugging-with-ssh):

1. `nix-shell -p pypy3.10 -p pypy3.9`
2. `pypy3.10 -m sysconfig`
3. `pypy3.9 -m sysconfig`

<details>
<summary>(Here is an associated `flake.lock` as well)</summary>

```json
{
  "nodes": {
    "nixpkgs": {
      "locked": {
        "lastModified": 1705175803,
        "narHash": "sha256-u+WX/r8j+jKef3IAVNWW8fznj7pn9kkaMtzjten2Qec=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "2284e61bd9df081fb2d4cc162b1d6b3d9752b02d",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "nixpkgs": "nixpkgs"
      }
    }
  },
  "root": "root",
  "version": 7
}
```
</details>

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.0-1018-azure, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/g16z4fs1mrbkxc4x6wm8xbrh13nc7aw4-source`
```

**Comment by kirillrdy** [comment]
hi, I cant reproduce the issue on nixos

```
 git checkout 2284e61bd9df081fb2d4cc162b1d6b3d9752b02d
 nix-build -A pypy310
./result/bin/pypy3 -m sysconfig

Platform: "linux-x86_64"
Python version: "3.10"
Current installation scheme: "posix_prefix"

Paths: 
	data = "/home/kirillvr/nixpkgs/result/pypy3.10-c"
	include = "/home/kirillvr/nixpkgs/result/pypy3.10-c/include/pypy3.10"
	platinclude = "/home/kirillvr/nixpkgs/result/pypy3.10-c/include/pypy3.10"
	platlib = "/home/kirillvr/nixpkgs/result/pypy3.10-c/lib/pypy3.10/site-packages"
	platstdlib = "/home/kirillvr/nixpkgs/result/pypy3.10-c/lib/pypy3.10"
	purelib = "/home/kirillvr/nixpkgs/result/pypy3.10-c/lib/pypy3.10/site-packages"
	scripts = "/home/kirillvr/nixpkgs/result/pypy3.10-c/bin"
	stdlib = "/home/kirillvr/nixpkgs/result/pypy3.10-c/lib/pypy3.10"
```

**Comment by jab** [comment]
Thanks for testing. Can you share your `nix-shell -p nix-info --run "nix-info -m"` output, and is there any chance you're getting different results due to a difference there?

**Comment by kirillrdy** [comment]
```
nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.11, NixOS, 24.05 (Uakari), 24.05.20240113.7e6aa7e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(kirillvr): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by undefined-moe** [comment]
It's now 

```
nix-repl> pypy3
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'pypy3.9-7.3.12'
         whose name attribute is located at /nix/store/pw3hllgllk54qir2zvahrdb0a5rrmih4-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'C_INCLUDE_PATH' of derivation 'pypy3.9-7.3.12'

         at /nix/store/pw3hllgllk54qir2zvahrdb0a5rrmih4-source/pkgs/development/interpreters/python/pypy/default.nix:74:3:

           73|
           74|   C_INCLUDE_PATH = lib.makeSearchPathOutput "dev" "include" buildInputs;
             |   ^
           75|   LIBRARY_PATH = lib.makeLibraryPath buildInputs;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: pycparser-2.22 not supported for interpreter pypy
«derivation 
```

on rev ac34158a823c7596e0106c806d0b7df47885fa73.

**Comment by wrdls** [comment]
Seeing a similar error as @undefined-moe on mac os.

```
❯ nix-shell -p pypy
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'shell'
         whose name attribute is located at /nix/store/y4p1bzzriaprvvy6fd9nz3kifjdiblq8-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'buildInputs' of derivation 'shell'

         at /nix/store/y4p1bzzriaprvvy6fd9nz3kifjdiblq8-source/pkgs/stdenv/generic/make-derivation.nix:378:7:

          377|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          378|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          379|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: pycparser-2.22 not supported for interpreter pypy
```

```
❯ nix-shell -p nix-info --run "nix-info -m"
these 3 paths will be fetched (1.03 MiB download, 8.17 MiB unpacked):
  /nix/store/598vvx2b3lk4p6gh90329mv0fh0a4inm-DarwinTools-1
  /nix/store/x2hwnm42a41wgf8zk53aay78vrklrsxq-bash-interactive-5.2p26
  /nix/store/1ysw4h9l4gclh46sk1jmvsh8jxjnwmk9-nix-info
copying path '/nix/store/x2hwnm42a41wgf8zk53aay78vrklrsxq-bash-interactive-5.2p26' from 'https://cache.nixos.org'...
copying path '/nix/store/598vvx2b3lk4p6gh90329mv0fh0a4inm-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/1ysw4h9l4gclh46sk1jmvsh8jxjnwmk9-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/y4p1bzzriaprvvy6fd9nz3kifjdiblq8-source`
 ```

**Comment by bvnierop** [comment]
I see this as well on Ubuntu 24.04:

```
12:41:05$ cat flake.nix 
{
  description = "foo";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/release-24.11";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
        };
      in
      {
        devShells.default = pkgs.mkShell {
          buildInputs = [
            pkgs.python310
            pkgs.pypy310
          ];
        };
      }
    );
}
```

```
12:44:43$ pypy3 -m sysconfig
Platform: "linux-x86_64"
Python version: "3.10"
Current installation scheme: "posix_prefix"

Traceback (most recent call last):
  File "/nix/store/y3qq860m77cb9ykcz08cxavfv4k437ky-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/runpy.py", line 199, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/y3qq860m77cb9ykcz08cxavfv4k437ky-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/nix/store/y3qq860m77cb9ykcz08cxavfv4k437ky-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 832, in <module>
    _main()
  File "/nix/store/y3qq860m77cb9ykcz08cxavfv4k437ky-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 826, in _main
    _print_dict('Paths', get_paths())
                         ^^^^^^^^^^^
  File "/nix/store/y3qq860m77cb9ykcz08cxavfv4k437ky-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 586, in get_paths
    return _expand_vars(scheme, vars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/y3qq860m77cb9ykcz08cxavfv4k437ky-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 225, in _expand_vars
    _extend_dict(vars, get_config_vars())
                       ^^^^^^^^^^^^^^^^^
  File "/nix/store/y3qq860m77cb9ykcz08cxavfv4k437ky-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 642, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/nix/store/y3qq860m77cb9ykcz08cxavfv4k437ky-pypy3.10-7.3.12/pypy3.10-c/lib-python/3/sysconfig.py", line 498, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'

```

```
12:43:37$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-51-generic, Ubuntu, 24.04.1 LTS (Noble Numbat), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by FliegendeWurst** [comment]
With #370527 (upgrading to 7.3.17) this seems to be fixed.

```
> pypy3 -m sysconfig
Platform: "linux-x86_64"
Python version: "3.10"
Current installation scheme: "posix_prefix"

Paths: 
	data = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c"
	include = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/include/pypy3.10"
	platinclude = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/include/pypy3.10"
	platlib = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/lib/pypy3.10/site-packages"
	platstdlib = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/lib/pypy3.10"
	purelib = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/lib/pypy3.10/site-packages"
	scripts = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/bin"
	stdlib = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/lib/pypy3.10"

Variables: 
	ABIFLAGS = ""
	AR = "ar"
	ARFLAGS = "rc"
	CC = "gcc -pthread"
	CCSHARED = "-fPIC"
	CFLAGS = "-DNDEBUG -O2"
	CONFINCLUDEPY = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/include/pypy3.10"
	CXX = "g++ -pthread"
	EXE = ""
	EXT_SUFFIX = ".pypy310-pp73-x86_64-linux-gnu.so"
	GNULD = "yes"
	INCLUDEPY = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/include/pypy3.10"
	LDCXXSHARED = "c++ -shared -Wl,-O1 -Wl,-Bsymbolic-functions"
	LDFLAGS = "-Wl,-Bsymbolic-functions"
	LDLIBRARY = "libpypy3.9-c.so"
	LDSHARED = "gcc -pthread -shared -Wl,-Bsymbolic-functions"
	LDVERSION = "3.10"
	LIBDIR = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/bin"
	LIBRARY = ""
	MULTIARCH = "x86_64-linux-gnu"
	OPT = "-DNDEBUG -O2"
	Py_DEBUG = "0"
	Py_ENABLE_SHARED = "0"
	SHLIB_SUFFIX = ".so"
	SIZEOF_VOID_P = "8"
	SO = ".pypy310-pp73-x86_64-linux-gnu.so"
	SOABI = "pypy310-pp73"
	TZPATH = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/share/zoneinfo:/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/lib/zoneinfo:/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/share/lib/zoneinfo:/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c/../etc/zoneinfo:/usr/share/zoneinfo:/usr/lib/zoneinfo:/usr/share/lib/zoneinfo:/etc/zoneinfo"
	VERSION = "3.10"
	abiflags = ""
	base = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c"
	exec_prefix = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c"
	implementation = "PyPy"
	implementation_lower = "pypy"
	installed_base = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c"
	installed_platbase = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c"
	platbase = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c"
	platlibdir = "lib"
	prefix = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c"
	projectbase = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c"
	py_version = "3.10.14"
	py_version_nodot = "310"
	py_version_nodot_plat = ""
	py_version_short = "3.10"
	srcdir = "/nix/store/l9dp1qfg2nbzkjk3w2yj40hjf4wy7bq5-pypy3.10-7.3.17/pypy3.10-c"
```

**Comment by bvnierop** [comment]
How can I follow when this actually hits `unstable`?

**Comment by FliegendeWurst** [comment]
> How can I follow when this actually hits `unstable`?

https://nixpk.gs/pr-tracker.html?pr=370527
