### ISSUE TITLE
pgadmin4 test suite fails on MacOS running aarch64 cpus

### ISSUE THREAD

**Issue by fullykubed** [NixOS/nixpkgs#281214]
### Describe the bug

The test suite for `pgadmin4` fails on MacOS running aarch64 cpus.

The actual pgadmin4 binary appears to work correctly. It is just the test suite that fails. 

### Steps To Reproduce
1. Try to utilize the `pgadmin4` or `pgadmin4-desktopmode` packages on MacOS running aarch64 cpus.

### Expected behavior

Package should not throw error during test phase.

### Screenshots

Summary section from error log from `source/pip-build/pgadmin4/regression/regression.log`:

```
[10787876864] 2024-01-15 20:04:54,883: ERROR	STDERR:	=============Completed the test cases for 'PostgreSQL 9.4'=============
[8172969472] 2024-01-15 20:04:54,883: ERROR	STDERR:	
[8172969472] 2024-01-15 20:04:54,883: ERROR	STDERR:	======================================================================
[8172969472] 2024-01-15 20:04:54,883: ERROR	STDERR:	Test Result Summary
[8172969472] 2024-01-15 20:04:54,883: ERROR	STDERR:	======================================================================
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:	PostgreSQL 9.4:
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:	
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:		1270 tests passed
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:		7 tests failed:
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			ServersConnectTestCase (connect to a server using password,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while creating server restore point)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			IsPasswordSaved (Connect server with 'save password)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			AllServersGetTestCase (Get the all children of server,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get the all available servers,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get the all available server of server group,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get the all connected servers)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:		156 tests skipped:
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			LanguagesGetFunctionAndTemplateTestCase (Error while getting language template)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			PackageEDBFuncsGetTestCase (Fetch Package Functions/Procedures URL)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			PackageAddTestCase (Fetch Package Node URL)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			PackageDeleteTestCase (Fetch Package Node URL)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			PackageDeleteMultipleTestCase (Fetch Package Node URL)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			PackageGetTestCase (Fetch Package Node URL)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			PackagePutTestCase (Fetch Package Node URL)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			SynonymAddTestCase (Default Node URL)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			SynonymDeleteTestCase (Fetch synonym Node URL)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			SynonymDeleteMultipleTestCase (Fetch synonym Node URL)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			SynonymGetTestCase (Fetch synonym Node URL)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			SynonymPutTestCase (Fetch synonym Node URL)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			CompoundTriggersAddTestCase (Create compound compound trigger for all events,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Create compound compound trigger for insert and delete,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Create compound compound trigger for insert with when condition,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Create compound compound trigger for insert or update on columns,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Create compound compound trigger for truncate,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Create compound trigger for insert delete and update on view,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Create compound trigger for instead of each row,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while adding a compound trigger using wrong table id,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while adding a compound trigger,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while while fetching the compound trigger id using compound trigger name,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Exception while adding a compound trigger)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			CompoundTriggersDeleteTestCase (Delete a compound trigger URL,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while fetching a compound trigger to delete,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while deleting the compound trigger,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						compound trigger not found while deleting a compound trigger)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			CompoundTriggersDeleteMultipleTestCase (Delete multiple compound trigger)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			CompoundTriggersGetTestCase (Get a selected compound trigger URL,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get a selected compound trigger URL using wrong compound trigger id,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while fetching a selected compound trigger node properties,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get a properties of all compound triggers under table nodes,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while fetching a compound trigger properties under table nodes,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get a compound trigger Node,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get a compound trigger Node using wrong compound trigger id,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get a compound trigger Node dependants,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get a compound trigger Node dependency,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while fetching the compound trigger under the table nodes using wrong table id,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get all the compound trigger under the table nodes,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get all the compound trigger under the table nodes using wrong table id,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while fetching all the compound trigger under the table nodes using wrong table id,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get a compound trigger SQL using wrong compound trigger id,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Fetch MSQL of compound trigger,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Fetch msql of compound trigger using wrong compound trigger id,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while generating  msql of compound trigger,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Get the modified SQL by passing an argument)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			CompoundTriggersUpdateTestCase (Exception while fetching a compound trigger to update,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while getting sql of Updated trigger,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Updated compound trigger not found,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						update a compound trigger URL,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Update event and code,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Enable Replica compound compound trigger,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Disable compound compound trigger,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Enable a compound trigger,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Enable a compound trigger using wrong compound trigger id,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while fetching a compound trigger to enable/disable,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while enabling a compound trigger,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Exception while enabling a compound trigger,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while updating the compound trigger,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Error while updating the new compound trigger id in object explorer)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			TypesAddTestCase (Create Nested types: With valid data for Advanced Server.,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Create Varray types: With valid data for Advanced Server.)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			MViewsUpdateParameterTestCase (Refresh Mview: With data.,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Refresh Mview: With no data.,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Refresh Mview: With data (concurrently).,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Refresh Mview: With no data (concurrently).,
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:						Refresh Mview: With invalid oid.)
[8172969472] 2024-01-15 20:04:54,884: ERROR	STDERR:			ViewsGetTestCase (Get view: With existing view having brackets (>=16).)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			ViewsSqlTestCase (Get view sql: With existing view having compound trigger.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentAddScheduleTestCase (Create schedule: With exception in pgAgent job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Create schedule: With existing pgAgent job while server is down.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentDeleteScheduleTestCase (Delete schedule: With existing pgAgent job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Delete multiple schedules: With existing pgAgent job.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentGetMsqlScheduleTestCase (Get schedule msql: For existing pgAgent job.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentGetNodesScheduleTestCase (Get schedule node: With existing pgAgent job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get schedules nodes: With multiple existing pgAgent jobs.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentGetScheduleTestCase (Get schedule: With existing pgAgent job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get schedules: With multiple existing pgAgent jobs.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get schedule: With existing pgAgent job while server down.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentPutScheduleTestCase (Update schedule: With start and end time.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update schedule: With repeat.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update schedule: Add exception.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update schedule: Change exception date and time.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update schedule: Delete exception.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentAddStepTestCase (Create step: For existing pgAgent job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Create step: For existing pgAgent job while server id down.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentDeleteStepTestCase (Delete step: For existing pgAgent job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Delete multiple steps: For existing pgAgent steps.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentGetNodesStepTestCase (Get step nodes: For existing pgAgent job step.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get multiple steps nodes: For existing pgAgent steps.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get step node: For non-existing pgAgent job step.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentGetStepTestCase (Get step: For existing pgAgent job step.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get multiple steps: For existing pgAgent steps.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get step: For existing pgAgent job step while server is down.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get step: For non-existing pgAgent job step.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get step stats: For existing pgAgent job step.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get step  stats: For existing pgAgent job step while server is down.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentPutStepTestCase (Update step: For existing pgAgent job step with kind, description, code and error.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update step: For existing pgAgent job step with connection type and string.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update step: For existing pgAgent job step with connection string.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update step: For non-existing pgAgent job step.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update step: For existing pgAgent job step while server is down.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentAddTestCase (Create pgagent job: With valid data.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Create pgagent job: With invalid data.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Create pgagent job: With valid data while server down.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentDeleteTestCase (Delete pgagent job: With existing job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Delete pgagent jobs: With existing jobs.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentGetTestCase (Get pgagent job: With existing job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get pgagent jobs: With existing job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get pgagent jobs: With Non-existing job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get pgagent jobs: With existing job while server down.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentGetMsqlTestCase (Get pgagent job msql: With existing job with description.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get pgagent job msql: With existing job to add schedule.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get pgagent job msql: With existing job to add steps with local connection.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentGetNodesTestCase (Get pgagent job nodes: With existing job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get pgagent jobs nodes: With existing job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get pgagent jobs nodes: With Non-existing job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get pgagent jobs nodes: With existing job while server down.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentGetStatsTestCase (Get pgagent job stats: With existing job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get pgagent job stats: With existing job while server down.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentPutTestCase (Update pgagent job: With existing job with description.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update pgagent job: With existing job to add schedule.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update pgagent job: With existing job to add steps with local connection.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update pgagent job: With existing job to add steps with remote connection.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Run pgagent job: Run ith existing job with description while server down.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Run pgagent job: Run existing job.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			PgAgentSqlTestCase (Get pgagent job sql: With existing job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get pgagent jobs sql: With Non-existing job.,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get pgagent jobs sql: With existing job while server down.)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			ResourceGroupsAddTestCase (Add resource groups)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			ResourceGroupsDeleteTestCase (Delete resource groups,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Delete multiple resource groups)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			ResourceGroupsPutTestCase (Put resource groups)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			ResourceGroupsGetTestCase (Get resource groups)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			TableSpaceAddTestCase (Check Tablespace Node)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			TableSpaceDeleteTestCase (Check Tablespace Node)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			TablespaceGetTestCase (Check Tablespace Node)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			TableSpaceUpdateTestCase (Check Tablespace Node)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			TestSSLConnection (Test for SSL connection)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			SharedServersGetTestCase (Get a shared server,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get a all shared server,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Get the all available shared server)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			SharedServerUpdateTestCase (update a server name,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						update a server details without data,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Update server with wrong server id,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						update a server , make server shared,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Clear saved password when login user is not owner of server,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Clear saved password with wrong server id,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Clear ssh tunnel password,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Clear ssh tunnel password with wrong server id,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						error while clearing a ssh password)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			MasterPasswordTestCase (TestCase for Create master password dialog,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						TestCase for Setting Master Password)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			Oauth2LoginMockTestCase (Oauth2 External Authentication,
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:						Oauth2 Authentication)
[8172969472] 2024-01-15 20:04:54,885: ERROR	STDERR:			WebserverLoginMockTestCase (Webserver Authentication)
[8172969472] 2024-01-15 20:04:54,889: ERROR	STDERR:	======================================================================
```

### Additional context

Workaround:

```nix
pkgs.pgadmin4-desktopmode.overrideAttrs (finalAttrs: previousAttrs: {
  # The checks do not work on arm machines
  doCheck = false;
  doInstallCheck = false;
})

```

### Notify maintainers

@gador 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.5.0, macOS 13.4.1`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gador** [comment]
It seems it fails due to an error on macOS keyring:
```
pgadmin> runTest (pgadmin.browser.server_groups.servers.tests.test_all_server_get.AllServersGetTestCase.runTest)
pgadmin> Get the all children of server ... 2024-04-09 09:08:41,738: ERROR      pgadmin:        Can't store password on keychain: (-61, 'Unknown Error')
pgadmin> Traceback (most recent call last):
pgadmin>   File "/nix/store/gakb84k1cc699r9hip9wipn31570w75w-python3.11-keyring-24.3.1/lib/python3.11/site-packages/keyring/backends/macOS/__init__.py", line 52, in set_password
pgadmin>     api.set_generic_password(self.keychain, service, username, password)
pgadmin>   File "/nix/store/gakb84k1cc699r9hip9wipn31570w75w-python3.11-keyring-24.3.1/lib/python3.11/site-packages/keyring/backends/macOS/api.py", line 162, in set_generic_password
pgadmin>     Error.raise_for_status(status)
pgadmin>   File "/nix/store/gakb84k1cc699r9hip9wipn31570w75w-python3.11-keyring-24.3.1/lib/python3.11/site-packages/keyring/backends/macOS/api.py", line 115, in raise_for_status
pgadmin>     raise cls(status, "Unknown Error")
pgadmin> keyring.backends.macOS.api.Error: (-61, 'Unknown Error')
pgadmin>
pgadmin> During handling of the above exception, another exception occurred:
pgadmin>
pgadmin> Traceback (most recent call last):
pgadmin>   File "/private/tmp/nix-build-pgadmin-8.5.drv-2/source/pip-build/pgadmin4/pgadmin/browser/server_groups/servers/__init__.py", line 1313, in create
pgadmin>     keyring.set_password(
pgadmin>   File "/nix/store/gakb84k1cc699r9hip9wipn31570w75w-python3.11-keyring-24.3.1/lib/python3.11/site-packages/keyring/core.py", line 61, in set_password
pgadmin>     get_keyring().set_password(service_name, username, password)
pgadmin>   File "/nix/store/gakb84k1cc699r9hip9wipn31570w75w-python3.11-keyring-24.3.1/lib/python3.11/site-packages/keyring/backends/macOS/__init__.py", line 24, in wrapper
pgadmin>     return func(self, *args, **kwargs)
pgadmin>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
pgadmin>   File "/nix/store/gakb84k1cc699r9hip9wipn31570w75w-python3.11-keyring-24.3.1/lib/python3.11/site-packages/keyring/backends/macOS/__init__.py", line 56, in set_password
pgadmin>     raise PasswordSetError("Can't store password on keychain: " "{}".format(e))
pgadmin> keyring.errors.PasswordSetError: Can't store password on keychain: (-61, 'Unknown Error')
```
This fails for me for both `x86_64-darwin` and `aarch64-darwin`.
Will look into it
