### ISSUE TITLE
Build failure: ibus-engines.mozc

### ISSUE THREAD

**Issue by linyinfeng** [NixOS/nixpkgs#281553]
### Steps To Reproduce

1. nix build github:nixos/nixpkgs/5026f74653024e4d8e4fcf681b82a52cffbced40#ibus-engines.mozc

(5026f74653024e4d8e4fcf681b82a52cffbced40 is current master)

### Build log

```
...
ibus-mozc> [87/245] CXX obj/protocol/gen/proto_out/protocol/commands_proto.commands.pb.o
ibus-mozc> clang-16: warning: argument unused during compilation: '-stdlib=libc++' [-Wunused-command-line-argument]
ibus-mozc> ninja: build stopped: subcommand failed.
ibus-mozc> Traceback (most recent call last):
ibus-mozc>   File "/build/source/src/build_mozc.py", line 887, in <module>
ibus-mozc>     sys.exit(main())
ibus-mozc>              ^^^^^^
ibus-mozc>   File "/build/source/src/build_mozc.py", line 872, in main
ibus-mozc>     BuildMain(cmd_opts, cmd_args)
ibus-mozc>   File "/build/source/src/build_mozc.py", line 612, in BuildMain
ibus-mozc>     BuildWithNinja(options, targets)
ibus-mozc>   File "/build/source/src/build_mozc.py", line 586, in BuildWithNinja
ibus-mozc>     RunOrDie([ninja, '-C', build_arg, target_name])
ibus-mozc>   File "/build/source/src/build_tools/util.py", line 96, in RunOrDie
ibus-mozc>     raise RunOrDieError('\n'.join(['',
ibus-mozc> build_tools.util.RunOrDieError:
ibus-mozc> ==========
ibus-mozc>  ERROR: ninja -C out_linux/Release ibus_mozc
ibus-mozc> ==========
```

### Notify maintainers

@gebner @ericsagnes

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0, NixOS, 24.05 (Uakari), 24.05.20240108.317484b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/pull/281674
