### ISSUE TITLE
Studio not working in Vinegar?

### ISSUE THREAD

**Issue by Ryoschin** [NixOS/nixpkgs#282315]
### Describe the bug
The "Studio" option is not working in Vinegar. The application does download, the application does launch. However, once it is open, the window is almost unusable.

### Steps To Reproduce
1. Download vinegar from nixpkgs (unstable)
2. Run `vinegar studio` in the terminal
3. Enjoy the mess in front of your eyes...

### Expected behavior
So, instead of getting the usual Studio look, I see the username, question cicrle, notification bell, and "FILE" buttons (all of the mentioned buttons do work, so I AM able to click on them and get a popup, as well as use the options from there, as well as hover effects). Everything else looks like a badly margined css page. (Replaced the actual username with "username" in the picture below, might not be perfectly aligned, just to make no misconceptions, the button IS properly aligned in the original image!)

### Screenshots
![2024-01-20-130051_hyprshot](https://github.com/NixOS/nixpkgs/assets/126424816/1d5f1845-b5df-4a3d-9f34-8e3b28bf5745)

### Notify maintainers
@nyabinary

### Metadata
```console
[xceptional@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.72, NixOS, 24.05 (Uakari), 24.05.20240115.c3e128f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SystematicError** [comment]
I was able to reproduce this, and I believe [this](https://vinegarhq.org/Troubleshooting/index.html#your-gpu-is-incompatible-error) is the issue you are getting.

The Vinegar wiki states that you need the `childwindow` patch to fix this issue, however the problem is that all the upstream vinegar patches are on an older version of wine (except for the `segregrevert` patch which was rebased to 9.0rc2). Currently the Vinegar team is working on porting these patches to 9.0 stable.

**Comment by Ryoschin** [comment]
I see, thank you. Unless you told me not to, I'll leave the issue until it is resolved (mostly so that people know what's going on, in case they're experiencing it as well).

**Comment by SystematicError** [comment]
Also, if you want to test studio out for now, you can get wine-ge from the nix-gaming flake and override the vinegar package with it.

**Comment by Ryoschin** [comment]
Oh, thank you, I'll get to learning how to right away!

**Comment by Ryoschin** [comment]
Oh, thank you. I'm not quite sure how to override vinegar's wine though.. Here is what fellas who were nice enough to help me came up with:
```nix
(vinegar.overrideAttrs (self: {
  buildInputs =
    map (v: if v.pname != "wine-wow" then v else gamePkgs.wine-ge)
    self.buildInputs;
}))
```
And it does build. However, when I run `vinegar studio`, here's the bunch of nonsense I get:
```console
2024/01/26 00:03:31 vinegar.go:161: Logging to file: /home/xceptional/.cache/vinegar/logs/Studio-2024-01-26T00:03:31+01:00.log
panic: runtime error: index out of range [4] with length 3

goroutine 36 [running]:
gioui.org/text.(*Shaper).NextGlyph(0xc00016c580)
	gioui.org@v0.4.1/text/shaper.go:454 +0x72d
gioui.org/widget.Label.LayoutDetailed({0x0, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0}, {{{0x0, 0x0}, {0x16a, ...}}, ...}, ...)
	gioui.org@v0.4.1/widget/label.go:82 +0x75b
gioui.org/widget.Label.Layout(...)
	gioui.org@v0.4.1/widget/label.go:43
gioui.org/widget/material.LabelStyle.Layout({{{0xa33e29, 0x12}, 0x0, 0x0}, {0x77, 0x77, 0x77, 0xff}, {0x8f, 0xbc, ...}, ...}, ...)
	gioui.org@v0.4.1/widget/material/label.go:153 +0x7ae
github.com/vinegarhq/vinegar/splash.(*Splash).drawDesc(0x14a580?, {{{0x0, 0x0}, {0x16a, 0x60}}, {0x3f800000, 0x3f800000}, {0xb25be0, 0xc0001c66c8}, {0xc164d811101df7f5, ...}, ...})
	github.com/vinegarhq/vinegar/splash/widgets.go:54 +0x1db
github.com/vinegarhq/vinegar/splash.(*Splash).drawCompact.func1.1.1.1({{{0x0, 0x0}, {0x16a, 0x60}}, {0x3f800000, 0x3f800000}, {0xb25be0, 0xc0001c66c8}, {0xc164d811101df7f5, 0x42636eb5, ...}, ...})
	github.com/vinegarhq/vinegar/splash/styles.go:54 +0x38
gioui.org/layout.Flex.Layout({0x0?, 0x0?, 0x0?, 0x0?}, {{{0x0, 0x0}, {0x16a, 0x76}}, {0x3f800000, 0x3f800000}, ...}, ...)
	gioui.org@v0.4.1/layout/flex.go:99 +0x295
github.com/vinegarhq/vinegar/splash.(*Splash).drawCompact.func1.1.1({{{0x0, 0x0}, {0x16a, 0x76}}, {0x3f800000, 0x3f800000}, {0xb25be0, 0xc0001c66c8}, {0xc164d811101df7f5, 0x42636eb5, ...}, ...})
	github.com/vinegarhq/vinegar/splash/styles.go:50 +0x4f4
gioui.org/layout.Flex.Layout({0x0?, 0x0?, 0x0?, 0x0?}, {{{0x1a0, 0x0}, {0x1a0, 0x76}}, {0x3f800000, 0x3f800000}, ...}, ...)
	gioui.org@v0.4.1/layout/flex.go:99 +0x295
github.com/vinegarhq/vinegar/splash.(*Splash).drawCompact.func1.1({{{0x1a0, 0x0}, {0x1a0, 0x76}}, {0x3f800000, 0x3f800000}, {0xb25be0, 0xc0001c66c8}, {0xc164d811101df7f5, 0x42636eb5, ...}, ...})
	github.com/vinegarhq/vinegar/splash/styles.go:43 +0x37a
gioui.org/layout.Flex.Layout({0x20?, 0x3f?, 0x9a?, 0x0?}, {{{0x1a0, 0x76}, {0x1a0, 0x76}}, {0x3f800000, 0x3f800000}, ...}, ...)
	gioui.org@v0.4.1/layout/flex.go:99 +0x295
github.com/vinegarhq/vinegar/splash.(*Splash).drawCompact.func1({{{0x1a0, 0x76}, {0x1a0, 0x76}}, {0x3f800000, 0x3f800000}, {0xb25be0, 0xc0001c66c8}, {0xc164d811101df7f5, 0x42636eb5, ...}, ...})
	github.com/vinegarhq/vinegar/splash/styles.go:38 +0x274
gioui.org/layout.Inset.Layout({0x109bda0?, 0x0?, 0x0?, 0x0?}, {{{0x1a0, 0x76}, {0x1a0, 0x76}}, {0x3f800000, 0x3f800000}, ...}, ...)
	gioui.org@v0.4.1/layout/layout.go:169 +0x39b
github.com/vinegarhq/vinegar/splash.(*Splash).drawCompact(0xc000126310?, {{{0x1c0, 0x96}, {0x1c0, 0x96}}, {0x3f800000, 0x3f800000}, {0xb25be0, 0xc0001c66c8}, {0xc164d811101df7f5, ...}, ...})
	github.com/vinegarhq/vinegar/splash/styles.go:35 +0x72
github.com/vinegarhq/vinegar/splash.(*Splash).Run(0xc0001263f0)
	github.com/vinegarhq/vinegar/splash/splash.go:200 +0x555
main.(*Binary).Main.func1()
	github.com/vinegarhq/vinegar/cmd/vinegar/vinegar.go:197 +0x25
created by main.(*Binary).Main in goroutine 1
	github.com/vinegarhq/vinegar/cmd/vinegar/vinegar.go:196 +0x5e7
```

**Comment by jbgi** [comment]
@Ryoschin 
`postInstall` need to also be overriden:
```nix
  (pkgs-unstable.vinegar.overrideAttrs (self: {
    buildInputs =
      map (v: if v.pname != "wine-wow" then v else pkgs-gaming.wine-ge)
      self.buildInputs;
    postInstall = ''
      wrapProgram $out/bin/vinegar \
        --prefix PATH : ${lib.makeBinPath [gamePkgs.wine-ge]}
      '';
  }))
```

**Comment by Ryoschin** [comment]
Oh, got it! Thank you
