### ISSUE TITLE
emscripten: attempts to write to /nix/store at runtime

### ISSUE THREAD

**Issue by WesleyAC** [NixOS/nixpkgs#282509]
### Describe the bug

When building https://github.com/joeycastillo/Sensor-Watch/ with the NixOS `emscripten` package, I get the following error:

### Steps To Reproduce
1. Clone https://github.com/joeycastillo/Sensor-Watch/
2. cd `movement/make` in that repo
3. `emmake make COLOR=RED`

This gets the following result:

```
make: make COLOR=RED
git submodule update --init
CC build-sim/movement.o
HTML build-sim/watch.html
Traceback (most recent call last):
  File "/nix/store/6lc4aphmkrxl8azmqacza29d926pz4ns-emscripten-3.1.47/share/emscripten/emcc.py", line 4495, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6lc4aphmkrxl8azmqacza29d926pz4ns-emscripten-3.1.47/share/emscripten/emcc.py", line 4488, in main
    ret = run(args)
          ^^^^^^^^^
  File "/nix/store/6lc4aphmkrxl8azmqacza29d926pz4ns-emscripten-3.1.47/share/emscripten/emcc.py", line 1321, in run
    js_info = get_js_sym_info()
              ^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6lc4aphmkrxl8azmqacza29d926pz4ns-emscripten-3.1.47/share/emscripten/emcc.py", line 541, in get_js_sym_info
    with filelock.FileLock(cache.get_path(cache.get_path('symbol_lists.lock'))):
  File "/nix/store/6lc4aphmkrxl8azmqacza29d926pz4ns-emscripten-3.1.47/share/emscripten/tools/filelock.py", line 330, in __enter__
    self.acquire()
  File "/nix/store/6lc4aphmkrxl8azmqacza29d926pz4ns-emscripten-3.1.47/share/emscripten/tools/filelock.py", line 278, in acquire
    self._acquire()
  File "/nix/store/6lc4aphmkrxl8azmqacza29d926pz4ns-emscripten-3.1.47/share/emscripten/tools/filelock.py", line 391, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/nix/store/6lc4aphmkrxl8azmqacza29d926pz4ns-emscripten-3.1.47/share/emscripten/cache/symbol_lists.lock'
make: *** [../../rules.mk:19: build-sim/watch.html] Error 1
emmake: error: 'make COLOR=RED' failed (returned 2)
```

It seems like this caching in emscripten is [somewhat new](https://chromium.googlesource.com/external/github.com/emscripten-core/emscripten/+log/b4786b63e11477419fd4386e62c923da3f4f2f5a/emcc.py). It's been a problem in #241304, and we should disable this by default on NixOS if possible (or else set the cache directory to be somewhere writable, but I don't think NixOS has anywhere like that, for understandable reasons)

### Expected behavior

Code successfully builds (as it has with previous emscripten versions)

### Notify maintainers

@qknight @matthewbauer @raitobezarius @willcohen

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.144, NixOS, 23.11 (Tapir), 23.11.2171.0b3d61817311`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware"`
 - channels(wesleyac): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by WesleyAC** [comment]
For anyone who runs into this in the meantime, setting `EM_CACHE` to somewhere writable should get you up and running.

**Comment by jvcarli** [comment]
I'm facing the same problem, the solution provided by @WesleyAC works.
