### ISSUE TITLE
ibus-1.5.14 hangs during build (lt-emoji-parser never finishes)

### ISSUE THREAD

**Issue by akamaus** [NixOS/nixpkgs#28404]
## Issue description
After switching to nixos-17.03 branch of channels repo (commit 28e8894a89835)  `nixos-rebuild boot` hangs.

## Technical details
```
nix % nixos-version
17.03.git.b22198e (Gorilla)
nix % nix-env --version
nix-env (Nix) 1.11.13
nix % nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion    
"17.03.git.a69da2ffb2"
```

## Build log

```
nix % s -E nixos-rebuild boot  
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/sxsm8fd5knh6cmrlsqhgmqfb77hs0y85-ibus-1.5.14.drv
  /nix/store/mpjzbkh96c7yrhivwhalsx9rirmxmak7-kdeplasma-addons-5.8.6.drv
  /nix/store/pdsbl3fg0v6zf20c7q95x85vr90xj38v-plasma-desktop-5.8.6.drv
  /nix/store/g1s24csfp6j4gxzrmbizqxnxcqxa71zh-system-path.drv
  /nix/store/3ak2c1342sg5b7dmapmyhhb8b2skn3ii-dbus-1.drv
  /nix/store/a9ccz2cz121ns0xqwaihf9lzbvh7m7hn-unit-polkit.service.drv
  /nix/store/bk6pcws8yi6mlzz64ddrbsdg12z8hxhm-unit-dbus.service.drv
  /nix/store/g28mjpk2hb2db938qyn9pvmhzyr552hs-unit-systemd-fsck-.service.drv
  /nix/store/6n65i1d8l4rrwg2j1z0rwb2046s3lrs9-system-units.drv
  /nix/store/hwlmnkg9n1dn3f1qzpqvirg4yw9kj9p1-user-units.drv
  /nix/store/azb9gd98d3rw9xcvn2n1w0z2qff9pham-etc.drv
  /nix/store/z4m52iqfwamqs88z8m9xqwkkdxgwf2v1-nixos-system-maunix-17.03.git.a69da2f.drv
building path(s) ‘/nix/store/mbhynhris3nwk8xz4l7y2w9gag7pwhs0-ibus-1.5.14-dev’, ‘/nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14’
unpacking sources
unpacking source archive /nix/store/5b6rnxrxgf0myjafniinxz463yf93pw8-ibus-1.5.14.tar.gz
source root is ibus-1.5.14
setting SOURCE_DATE_EPOCH to timestamp 1470368753 of file ibus-1.5.14/NEWS
patching sources
configuring
fixing libtool script ./ltmain.sh
configure flags: --disable-static --disable-dependency-tracking --prefix=/nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14         --bindir=/nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14/bin --sbindir=/nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14/sbin         --includedir=/nix/store/mbhynhris3nwk8xz4l7y2w9gag7pwhs0-ibus-1.5.14-dev/include --oldincludedir=/nix/store/mbhynhris3nwk8xz4l7y2w9gag7pwhs0-ibus-1.5.14-dev/include         --mandir=/nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14/share/man --infodir=/nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14/share/info         --docdir=/nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14/share/doc/ibus         --libdir=/nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14/lib --libexecdir=/nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14/libexec         --localedir=/nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14/share/locale         --disable-gconf --enable-dconf --disable-memconf --enable-ui --enable-python-library --with-emoji-json-file=/nix/store/g5lywb4dllqb28qrkva9bk5shmlypwpc-node-emojione-3.1.2/lib/node_modules/emojione/emoji.json 
checking for a BSD-compatible install... /nix/store/c07gdr6cm43j1cphadzafq185k711vx4-coreutils-8.26/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /nix/store/c07gdr6cm43j1cphadzafq185k711vx4-coreutils-8.26/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /nix/store/r6s8rcd28wsk4gwviyc93343bq5zwlqq-gnugrep-3.0/bin/grep
checking for egrep... /nix/store/r6s8rcd28wsk4gwviyc93343bq5zwlqq-gnugrep-3.0/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether make supports nested variables... (cached) yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... /nix/store/s70cbg1lh45h3gl6xplz6bi2qdszi2cf-gettext-0.19.8/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... /nix/store/s70cbg1lh45h3gl6xplz6bi2qdszi2cf-gettext-0.19.8/bin/msgfmt
checking for xgettext... /nix/store/s70cbg1lh45h3gl6xplz6bi2qdszi2cf-gettext-0.19.8/bin/xgettext
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) none
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking for valac... valac
configure: WARNING: no proper vala compiler found
configure: WARNING: you will not be able to compile vala source files
checking whether make sets $(MAKE)... (cached) yes
checking for locale.h... (cached) yes
checking for LC_MESSAGES... (cached) yes
checking for libintl.h... (cached) yes
checking for ngettext in libc... (cached) yes
checking for dgettext in libc... (cached) yes
checking for bind_textdomain_codeset... (cached) yes
checking for msgfmt... (cached) /nix/store/s70cbg1lh45h3gl6xplz6bi2qdszi2cf-gettext-0.19.8/bin/msgfmt
checking for dcgettext... (cached) yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /nix/store/s70cbg1lh45h3gl6xplz6bi2qdszi2cf-gettext-0.19.8/bin/msgfmt
checking for xgettext... (cached) /nix/store/s70cbg1lh45h3gl6xplz6bi2qdszi2cf-gettext-0.19.8/bin/xgettext
checking for library containing strerror... none required
checking for ANSI C header files... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /nix/store/xk38vw7z7bfr8173vdwfrfamxqcaj7hi-gnused-4.4/bin/sed
checking for fgrep... /nix/store/r6s8rcd28wsk4gwviyc93343bq5zwlqq-gnugrep-3.0/bin/grep -F
checking for ld used by gcc... /nix/store/j1yn1np5g2vgm5yp8qmqg67x8riwy2kr-gcc-wrapper-5.4.0/bin/ld
checking if the linker (/nix/store/j1yn1np5g2vgm5yp8qmqg67x8riwy2kr-gcc-wrapper-5.4.0/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /nix/store/3iggy4d1wdwivs4kx9ic90npiwxvnrr8-binutils-2.27/bin/nm -B
checking the name lister (/nix/store/3iggy4d1wdwivs4kx9ic90npiwxvnrr8-binutils-2.27/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /nix/store/j1yn1np5g2vgm5yp8qmqg67x8riwy2kr-gcc-wrapper-5.4.0/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /nix/store/3iggy4d1wdwivs4kx9ic90npiwxvnrr8-binutils-2.27/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /nix/store/c07gdr6cm43j1cphadzafq185k711vx4-coreutils-8.26/bin/dd
checking how to truncate binary pipes... /nix/store/c07gdr6cm43j1cphadzafq185k711vx4-coreutils-8.26/bin/dd bs=4096 count=1
./configure: line 10112: /usr/bin/file: No such file or directory
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/nix/store/j1yn1np5g2vgm5yp8qmqg67x8riwy2kr-gcc-wrapper-5.4.0/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether NLS is requested... yes
checking for intltool >= 0.35.0... 0.51.0 found
checking for intltool-update... /nix/store/5kxw9z5cx4hvg8pg5dc6264rv8sm7hfq-intltool-0.51.0/bin/intltool-update
checking for intltool-merge... /nix/store/5kxw9z5cx4hvg8pg5dc6264rv8sm7hfq-intltool-0.51.0/bin/intltool-merge
checking for intltool-extract... /nix/store/5kxw9z5cx4hvg8pg5dc6264rv8sm7hfq-intltool-0.51.0/bin/intltool-extract
checking for xgettext... (cached) /nix/store/s70cbg1lh45h3gl6xplz6bi2qdszi2cf-gettext-0.19.8/bin/xgettext
checking for msgmerge... /nix/store/s70cbg1lh45h3gl6xplz6bi2qdszi2cf-gettext-0.19.8/bin/msgmerge
checking for msgfmt... (cached) /nix/store/s70cbg1lh45h3gl6xplz6bi2qdszi2cf-gettext-0.19.8/bin/msgfmt
checking for gmsgfmt... (cached) /nix/store/s70cbg1lh45h3gl6xplz6bi2qdszi2cf-gettext-0.19.8/bin/msgfmt
checking for perl... /nix/store/76lhp1gvc3wbl6q4p2qgn2n7245imyvr-perl-5.22.3/bin/perl
checking for perl >= 5.8.1... 5.22.3
checking for XML::Parser... ok
checking for daemon... yes
checking for pkg-config... /nix/store/clvw27qshazq458waarrjqj0k5qpnjkn-pkg-config-0.29/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.0.0... yes (version 2.50.3)
checking for GLIB2... yes
checking for GOBJECT2... yes
checking for GIO2... yes
checking for GTHREAD2... yes
checking for GTK2... yes
checking for GTK3... yes
checking for X11... yes
checking X11/XKBlib.h usability... yes
checking X11/XKBlib.h presence... yes
checking for X11/XKBlib.h... yes
checking for KDE5 appindicator engine icon... no
checking for gobject-introspection... yes
checking for pkg-config... (cached) /nix/store/clvw27qshazq458waarrjqj0k5qpnjkn-pkg-config-0.29/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for vapigen... no
checking for gtk-doc... no
configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.9 is not found.
checking for gtkdoc-check... no
checking for gtkdoc-check... no
checking for gtkdoc-rebase... no
checking for gtkdoc-mkpdf... no
checking whether to build gtk-doc documentation... no
checking for GTKDOC_DEPS... yes
checking for DBUS... yes
checking for DCONF... yes
checking for pkg-config... (cached) /nix/store/clvw27qshazq458waarrjqj0k5qpnjkn-pkg-config-0.29/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for env... /nix/store/c07gdr6cm43j1cphadzafq185k711vx4-coreutils-8.26/bin/env
checking for a Python interpreter with version >= 2.5... python
checking for python... /nix/store/58kwrs1w21lxxk1d2v25k7wprmlrr6jj-python3-3.5.3/bin/python
checking for python version... 3.5
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.5/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.5/site-packages
checking for python2... no
checking for PYTHON... yes
checking for python3.5-config... /nix/store/58kwrs1w21lxxk1d2v25k7wprmlrr6jj-python3-3.5.3/bin/python3.5-config
checking for X11... yes
checking for LIBNOTIFY... yes
checking for JSON_GLIB1... yes
checking for ISOCODES... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating po/Makefile.in
config.status: creating Makefile
config.status: creating ibus-1.0.pc
config.status: WARNING:  'ibus-1.0.pc.in' seems to ignore the --datarootdir setting
config.status: creating ibus.spec
config.status: creating client/Makefile
config.status: creating client/gtk2/Makefile
config.status: creating client/gtk3/Makefile
config.status: creating client/x11/Makefile
config.status: creating client/wayland/Makefile
config.status: creating src/Makefile
config.status: creating src/ibusversion.h
config.status: creating src/tests/Makefile
config.status: creating bus/Makefile
config.status: creating engine/Makefile
config.status: creating util/Makefile
config.status: creating util/IMdkit/Makefile
config.status: creating data/Makefile
config.status: creating data/annotations/Makefile
config.status: creating data/icons/Makefile
config.status: creating data/keymaps/Makefile
config.status: creating data/dconf/Makefile
config.status: creating docs/Makefile
config.status: creating docs/reference/Makefile
config.status: creating docs/reference/ibus/ibus-docs.sgml
config.status: creating docs/reference/ibus/Makefile
config.status: creating m4/Makefile
config.status: creating ibus/_config.py
config.status: creating ibus/Makefile
config.status: creating ibus/interface/Makefile
config.status: creating ui/Makefile
config.status: creating ui/gtk3/Makefile
config.status: creating setup/Makefile
config.status: creating setup/ibus-setup
config.status: creating bindings/Makefile
config.status: creating bindings/pygobject/Makefile
config.status: creating bindings/vala/Makefile
config.status: creating conf/Makefile
config.status: creating conf/gconf/Makefile
config.status: creating conf/dconf/Makefile
config.status: creating conf/memconf/Makefile
config.status: creating tools/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing default-1 commands
config.status: executing default-2 commands
config.status: executing libtool commands
config.status: executing po/stamp-it commands

Build options:
  Version                       1.5.14
  Install prefix                /nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14
  Build shared libs             yes
  Build static libs             no
  CFLAGS                        -g -O2
  PYTHON                        /nix/store/58kwrs1w21lxxk1d2v25k7wprmlrr6jj-python3-3.5.3/bin/python
  PYTHON2                       /nix/store/58kwrs1w21lxxk1d2v25k7wprmlrr6jj-python3-3.5.3/bin/python
  Gtk2 immodule dir             /nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14/lib/gtk-2.0/2.10.0/immodules
  Gtk3 immodule dir             /nix/store/zzianmdp54iss3ijws8kl3l8z0xrap0h-ibus-1.5.14/lib/gtk-3.0/3.0.0/immodules
  Build gtk2 immodule           yes
  Build gtk3 immodule           yes
  Build XIM agent server        yes
  Build wayland support         no (disabled, use --enable-wayland to enable)
  Build appindicator support    yes (enabled, use --disable-appindicator to disable)
  Build appindicator engine icon no (disabled, need qtbase-devel 5.4 or later)
  Build python library          yes
  Build gconf modules           no (disabled, use --enable-gconf to enable)
  Build memconf modules         no
  Build dconf modules           yes (enabled, use --disable-dconf to disable)
  Build introspection           yes
  IBus-1.0.gir scannerflags     "--warn-all --identifier-prefix=IBus --symbol-prefix=ibus"
  Build vala binding            no
  Build document                no (disabled, use --enable-gtk-doc to enable)
  Build UI                      yes (enabled, use --disable-ui to disable)
  Build engine                  yes (enabled, use --disable-engine to disable)
  Enable key snooper            yes
  No snooper regexes            "firefox.*,.*chrome.*,.*chromium.*,terminator"
  Panel icon                    "ibus-keyboard"
  Enable surrounding-text       yes
  Enable libnotify              yes (enabled, use --disable-libnotify to disable)
  Enable Emoji dict             yes (enabled, use --disable-emoji-dict to disable)
  emoji.json path               /nix/store/g5lywb4dllqb28qrkva9bk5shmlypwpc-node-emojione-3.1.2/lib/node_modules/emojione/emoji.json
  Run test cases                yes

building
make flags: SHELL=/nix/store/lpk84rsbha199vm3k54498lqv2jswqj8-bash-4.4-p5/bin/bash    
make  all-recursive
make[1]: Entering directory '/tmp/nix-build-ibus-1.5.14.drv-0/ibus-1.5.14'
Making all in src
make[2]: Entering directory '/tmp/nix-build-ibus-1.5.14.drv-0/ibus-1.5.14/src'
  GEN      ibusmarshalers.h
  GEN      ibusmarshalers.c
make  all-recursive
make[3]: Entering directory '/tmp/nix-build-ibus-1.5.14.drv-0/ibus-1.5.14/src'
Making all in .
make[4]: Entering directory '/tmp/nix-build-ibus-1.5.14.drv-0/ibus-1.5.14/src'
  CC       ibusmarshalers.lo
  CC       ibuscomposetable.lo
  CC       ibusenumtypes.lo
  CC       ibusshare.lo
  CC       ibusobject.lo
  CC       ibusserializable.lo
  CC       ibusproxy.lo
  CC       ibusservice.lo
  CC       ibusfactory.lo
  CC       ibusengine.lo
  CC       ibuserror.lo
  CC       ibustext.lo
  CC       ibuskeymap.lo
  CC       ibusattribute.lo
  CC       ibusattrlist.lo
  CC       ibusproperty.lo
  CC       ibusproplist.lo
  CC       ibuslookuptable.lo
  CC       ibusinputcontext.lo
  CC       ibusconfig.lo
  CC       ibusconfigservice.lo
  CC       ibuspanelservice.lo
  CC       ibusbus.lo
  CC       ibuskeynames.lo
  CC       ibuskeyuni.lo
  CC       ibushotkey.lo
  CC       ibusxml.lo
  CC       ibusenginedesc.lo
  CC       ibusobservedpath.lo
  CC       ibuscomponent.lo
  CC       ibusutil.lo
  CC       ibusenginesimple.lo
  CC       ibusregistry.lo
  CC       emoji_parser-emoji-parser.o
  CCLD     libibus-1.0.la
  GISCAN   IBus-1.0.gir
  CCLD     emoji-parser
./emoji-parser --xml ./../data/annotations/en.xml \
--json /nix/store/g5lywb4dllqb28qrkva9bk5shmlypwpc-node-emojione-3.1.2/lib/node_modules/emojione/emoji.json --out emoji.dict
  GICOMP   IBus-1.0.gir

^Cerror: interrupted by the user
```

## Preliminary gdb run
I tried to attach gdb to hanging process and saw this:

```
nix$ sudo gdb            
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) attach 11459
Attaching to process 11459
Reading symbols from target:/tmp/nix-build-ibus-1.5.14.drv-0/ibus-1.5.14/src/.libs/lt-emoji-parser...done.
Reading symbols from target:/nix/store/hkrpznhdm99jlahxryr67b7bb379zrvp-json-glib-1.2.0/lib/libjson-glib-1.0.so.0...(no debugging symbols found)...done.
Reading symbols from target:/tmp/nix-build-ibus-1.5.14.drv-0/ibus-1.5.14/src/.libs/libibus-1.0.so.5...done.
Reading symbols from target:/nix/store/jfg4a7hla1zvwih2zs6bj1gwf6sw0vzp-glib-2.50.3/lib/libgio-2.0.so.0...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/jfg4a7hla1zvwih2zs6bj1gwf6sw0vzp-glib-2.50.3/lib/libgmodule-2.0.so.0...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/kjwbqnh13dxh6w4pk2gb3ddmhpiaihqg-glibc-2.25/lib/libdl.so.2...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/sg6ri2jj92sbv7f4rvchzr00d24pi4nq-zlib-1.2.11/lib/libz.so.1...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/kjwbqnh13dxh6w4pk2gb3ddmhpiaihqg-glibc-2.25/lib/libresolv.so.2...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/sr1nyqmj35dqnrzj3vmd1ycdykidsav0-util-linux-2.29.2/lib/libmount.so.1...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/sr1nyqmj35dqnrzj3vmd1ycdykidsav0-util-linux-2.29.2/lib/libblkid.so.1...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/sr1nyqmj35dqnrzj3vmd1ycdykidsav0-util-linux-2.29.2/lib/libuuid.so.1...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/kjwbqnh13dxh6w4pk2gb3ddmhpiaihqg-glibc-2.25/lib/librt.so.1...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/jfg4a7hla1zvwih2zs6bj1gwf6sw0vzp-glib-2.50.3/lib/libgobject-2.0.so.0...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/qfjhjpk7rx8wz0y6k2fl4c6g1pis46hl-libffi-3.2.1/lib/../lib64/libffi.so.6...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/jfg4a7hla1zvwih2zs6bj1gwf6sw0vzp-glib-2.50.3/lib/libglib-2.0.so.0...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/fwxgxaclys016hlvk68lbl0ipx5nc95l-pcre-8.40/lib/libpcre.so.1...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/kjwbqnh13dxh6w4pk2gb3ddmhpiaihqg-glibc-2.25/lib/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/kjwbqnh13dxh6w4pk2gb3ddmhpiaihqg-glibc-2.25/lib/libthread_db.so.1".
Reading symbols from target:/nix/store/kjwbqnh13dxh6w4pk2gb3ddmhpiaihqg-glibc-2.25/lib/libc.so.6...(no debugging symbols found)...done.
Reading symbols from target:/nix/store/kjwbqnh13dxh6w4pk2gb3ddmhpiaihqg-glibc-2.25/lib/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
0x00007ffff5dac797 in g_hash_table_lookup () from target:/nix/store/jfg4a7hla1zvwih2zs6bj1gwf6sw0vzp-glib-2.50.3/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff5dac797 in g_hash_table_lookup () from target:/nix/store/jfg4a7hla1zvwih2zs6bj1gwf6sw0vzp-glib-2.50.3/lib/libglib-2.0.so.0
#1  0x00000000004025c0 in update_emoji_dict (data=data@entry=0x7fffffff6710) at emoji-parser.c:62
#2  0x0000000000402111 in parse_emojione_element (data=0x7fffffff6710, node=<optimized out>) at emoji-parser.c:453
#3  emojione_parse_json_file (dict=0x606180, filename=0x6118e0 "/nix/store/g5lywb4dllqb28qrkva9bk5shmlypwpc-node-emojione-3.1.2/lib/node_modules/emojione/emoji.json") at emoji-parser.c:491
#4  main (argc=1, argv=0x7fffffff6918) at emoji-parser.c:562
(gdb) n
Single stepping until exit from function g_hash_table_lookup,
which has no line number information.
update_emoji_dict (data=data@entry=0x7fffffff6710) at emoji-parser.c:63
63              if (emojis) {
(gdb) n
62              GSList *emojis = g_hash_table_lookup (data->dict, annotation);
(gdb) n
63              if (emojis) {
(gdb) n
64                  GSList *duplicated = g_slist_find_custom (emojis,
(gdb) n
67                  if (duplicated != NULL)
(gdb) list
62              GSList *emojis = g_hash_table_lookup (data->dict, annotation);
63              if (emojis) {
64                  GSList *duplicated = g_slist_find_custom (emojis,
65                                                            data->emoji,
66                                                            (GCompareFunc) g_strcmp0);
67                  if (duplicated != NULL)
68                       continue;
69                  emojis = g_slist_copy_deep (emojis, (GCopyFunc) g_strdup, NULL);
70              }
71              emojis = g_slist_append (emojis, g_strdup (data->emoji));
(gdb) fin
Run till exit from #0  update_emoji_dict (data=data@entry=0x7fffffff6710) at emoji-parser.c:67

^C <hangs>
```

**Comment by bkchr** [comment]
I remember having the same problem, I think that the following commit fixed it: https://github.com/NixOS/nixpkgs/commit/38625a8b1e67c2b4dc10b1c3f2ac5be5732e3c51

But I don't know if that could be backported?

**Comment by akamaus** [comment]
@bkchr Cherry-picking that commit helped indeed, many thanks.

**Comment by ttuegel** [comment]
We can backport 38625a8. I don't understand why the Node packages were updated on the release branch. I thought the purpose of the release branch was not making major version bumps. I will backport this if someone can explain our version policy to me.

**Comment by globin** [comment]
Wrt b590b82: @svanderburg why was this backported to 17.03, were there security fixes or any other larger issue? Otherwise I'd prefer reverting this, as this obviously is causing some issues..

Wrt 38625a8: we had the same issue that is occuring now, as the emoji handling broke due to a emojione update and ibus changed the build to not use that anymore with this version update.

**Comment by Mic92** [comment]
related pull request https://github.com/NixOS/nixpkgs/pull/28541

**Comment by vcunat** [comment]
Worked around by that PR. 

I'm also not convinced that node packages need to get all updated to latest versions in 17.03, but I'm not acting on that.
