### ISSUE TITLE
fetchYarnDeps fails if yarn lock has link lockentry 

### ISSUE THREAD

**Issue by berberman** [NixOS/nixpkgs#284157]
### Describe the bug

I found this issue while I was trying to update `typst-preview` to 0.10.7. In [this commit](https://github.com/Enter-tainer/typst-preview/commit/755156b3bb4ca6c74573e5e2e7b49c9c9bcc3465), the author changed the dependency type of the local package `typst-dom` from `file` to `link`:

```diff
--- a/addons/frontend/package.json
+++ b/addons/frontend/package.json
@@ -14,11 +14,11 @@
   "dependencies": {
     "@myriaddreamin/typst-ts-renderer": "0.4.2-rc5",
     "@myriaddreamin/typst.ts": "0.4.2-rc5",
-    "typst-dom": "file:../typst-dom",
+    "typst-dom": "link:../typst-dom",
     "rxjs": "^7.8.1"
   },
```

with the follow changing in the lock file:
```diff
--- a/addons/frontend/yarn.lock
+++ b/addons/frontend/yarn.lock
-"typst-dom@file:../typst-dom":
+"typst-dom@link:../typst-dom":
   version "0.0.0"
+  uid ""
 
```

However, it seems that `fetchYarnDeps` only skips for downloading for `file`:
https://github.com/NixOS/nixpkgs/blob/c7a9d44dc76e1843542da9ab19cd0a1bafbbcd18/pkgs/build-support/node/fetch-yarn-deps/index.js#L90-L126

And building the following drv:
```nix
let
  version = "0.10.7";
  src = fetchFromGitHub {
    owner = "Enter-tainer";
    repo = "typst-preview";
    rev = "v${version}";
    hash = "sha256-32GYsUMXYCoVNZzgALMR0XpFmHBPw8FQQkurKWdMQcc=";
    fetchSubmodules = true;
  };
fetchYarnDeps {
      yarnLock = "${src}/addons/frontend/yarn.lock";
      hash = "";
};
```

would fail with:

```
error: builder for '/nix/store/skvlzybc5518pngplb4ar0yjw6y4zrdi-offline.drv' failed with exit code 1;
       last 10 log lines:
       > downloading https://registry.yarnpkg.com/type-detect/-/type-detect-4.0.8.tgz
       > downloading https://registry.yarnpkg.com/typescript/-/typescript-5.3.3.tgz
       > Error: The lockfile entry with key "typst-dom@link:../typst-dom" cannot be downloaded because it is missing the "resolved" attribute, which should contain the URL to download from. The lockfile might be invalid.
       >     at downloadPkg (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/index.js:101:9)
       >     at /nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/index.js:145:32
       >     at worker (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/index.js:130:47)
       >     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
       >     at async Promise.all (index 1)
       >     at async prefetchYarnDeps (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/index.js:143:2)
       >     at async main (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/index.js:187:3)
       For full logs, run 'nix log /nix/store/skvlzybc5518pngplb4ar0yjw6y4zrdi-offline.drv'.
```

IIUC, we should also check and skip for downloading if the path in an lockentry is a link. 

### Notify maintainers

@lorenzleutgeb

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.73, NixOS, 24.05 (Uakari), 24.05.20240117.842d9d8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/gyjzpkp0g6xa2rj105nbgm7cki1d682m-wcidiyklj0nrljlz5m3qlkvhv8f2ddv8-source`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lorenzleutgeb** [comment]
cc @yu-re-ka @lilyinstarlight

**Comment by drupol** [comment]
Encountered the issue and fixed it using `substituteInPlace` in https://github.com/NixOS/nixpkgs/pull/290207

**Comment by lorenzleutgeb** [comment]
@drupol thanks for mentioning the workaround! :)
