### ISSUE TITLE
Build failure: python3.pkgs.spacy

### ISSUE THREAD

**Issue by azazel75** [NixOS/nixpkgs#284774]
### Steps To Reproduce

`nix build 'nixpkgs#python3.pkgs.spacy'`

### Build log

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pypa-build-hook
Using pypaBuildPhase
Sourcing python-runtime-deps-check-hook
Using pythonRuntimeDepsCheckHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/d9q39zwc63mjq9wxvdkhh2ixh3zgvpzs-spacy-3.7.2.tar.gz
source root is spacy-3.7.2
setting SOURCE_DATE_EPOCH to timestamp 1697462098 of file spacy-3.7.2/setup.cfg
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
substituteStream(): WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'setup.cfg')
substituteStream(): WARNING: pattern thinc\>=8.1.8\,\<8.2.0 doesn't match anything in file 'setup.cfg'
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing pypaBuildPhase
Creating a wheel...
[1m* Getting build dependencies for wheel...[0m
Copied /build/spacy-3.7.2/setup.cfg -> /build/spacy-3.7.2/spacy/tests/package
Copied /build/spacy-3.7.2/pyproject.toml -> /build/spacy-3.7.2/spacy/tests/package
Cythonizing sources
Compiling spacy/training/alignment_array.pyx because it changed.
Compiling spacy/training/example.pyx because it changed.
Compiling spacy/parts_of_speech.pyx because it changed.
Compiling spacy/strings.pyx because it changed.
Compiling spacy/lexeme.pyx because it changed.
Compiling spacy/vocab.pyx because it changed.
Compiling spacy/attrs.pyx because it changed.
Compiling spacy/kb/candidate.pyx because it changed.
Compiling spacy/kb/kb.pyx because it changed.
Compiling spacy/kb/kb_in_memory.pyx because it changed.
Compiling spacy/ml/parser_model.pyx because it changed.
Compiling spacy/morphology.pyx because it changed.
Compiling spacy/pipeline/dep_parser.pyx because it changed.
Compiling spacy/pipeline/_edit_tree_internals/edit_trees.pyx because it changed.
Compiling spacy/pipeline/morphologizer.pyx because it changed.
Compiling spacy/pipeline/multitask.pyx because it changed.
Compiling spacy/pipeline/ner.pyx because it changed.
Compiling spacy/pipeline/pipe.pyx because it changed.
Compiling spacy/pipeline/trainable_pipe.pyx because it changed.
Compiling spacy/pipeline/sentencizer.pyx because it changed.
Compiling spacy/pipeline/senter.pyx because it changed.
Compiling spacy/pipeline/tagger.pyx because it changed.
Compiling spacy/pipeline/transition_parser.pyx because it changed.
Compiling spacy/pipeline/_parser_internals/arc_eager.pyx because it changed.
Compiling spacy/pipeline/_parser_internals/ner.pyx because it changed.
Compiling spacy/pipeline/_parser_internals/nonproj.pyx because it changed.
Compiling spacy/pipeline/_parser_internals/_state.pyx because it changed.
Compiling spacy/pipeline/_parser_internals/stateclass.pyx because it changed.
Compiling spacy/pipeline/_parser_internals/transition_system.pyx because it changed.
Compiling spacy/pipeline/_parser_internals/_beam_utils.pyx because it changed.
Compiling spacy/tokenizer.pyx because it changed.
Compiling spacy/training/align.pyx because it changed.
Compiling spacy/training/gold_io.pyx because it changed.
Compiling spacy/tokens/doc.pyx because it changed.
Compiling spacy/tokens/span.pyx because it changed.
Compiling spacy/tokens/token.pyx because it changed.
Compiling spacy/tokens/span_group.pyx because it changed.
Compiling spacy/tokens/graph.pyx because it changed.
Compiling spacy/tokens/morphanalysis.pyx because it changed.
Compiling spacy/tokens/_retokenize.pyx because it changed.
Compiling spacy/matcher/matcher.pyx because it changed.
Compiling spacy/matcher/phrasematcher.pyx because it changed.
Compiling spacy/matcher/dependencymatcher.pyx because it changed.
Compiling spacy/symbols.pyx because it changed.
Compiling spacy/vectors.pyx because it changed.
[ 1/45] Cythonizing spacy/attrs.pyx
[ 2/45] Cythonizing spacy/kb/candidate.pyx
[ 3/45] Cythonizing spacy/kb/kb.pyx
[ 4/45] Cythonizing spacy/kb/kb_in_memory.pyx
[ 5/45] Cythonizing spacy/lexeme.pyx
[ 6/45] Cythonizing spacy/matcher/dependencymatcher.pyx
[ 7/45] Cythonizing spacy/matcher/matcher.pyx
[ 8/45] Cythonizing spacy/matcher/phrasematcher.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        self._validate = validate

        self.mem = Pool()
        self.c_map = <MapStruct*>self.mem.alloc(1, sizeof(MapStruct))
        self._terminal_hash = 826361138722620965
        map_init(self.mem, self.c_map, 8)
               ^
------------------------------------------------------------

spacy/matcher/phrasematcher.pyx:48:16: Call with wrong number of arguments (expected 2, got 3)

Error compiling Cython file:
------------------------------------------------------------
...
                    warnings.warn(Warnings.W021)
                    break
                result = <MapStruct*>map_get(current_node, token)
                if not result:
                    internal_node = <MapStruct*>self.mem.alloc(1, sizeof(MapStruct))
                    map_init(self.mem, internal_node, 8)
                           ^
------------------------------------------------------------

spacy/matcher/phrasematcher.pyx:224:28: Call with wrong number of arguments (expected 2, got 3)

Error compiling Cython file:
------------------------------------------------------------
...
                    break
                result = <MapStruct*>map_get(current_node, token)
                if not result:
                    internal_node = <MapStruct*>self.mem.alloc(1, sizeof(MapStruct))
                    map_init(self.mem, internal_node, 8)
                    map_set(self.mem, current_node, token, internal_node)
                          ^
------------------------------------------------------------

spacy/matcher/phrasematcher.pyx:225:27: Call with wrong number of arguments (expected 3, got 4)

Error compiling Cython file:
------------------------------------------------------------
...
                    result = internal_node
                current_node = <MapStruct*>result
            result = <MapStruct*>map_get(current_node, self._terminal_hash)
            if not result:
                internal_node = <MapStruct*>self.mem.alloc(1, sizeof(MapStruct))
                map_init(self.mem, internal_node, 8)
                       ^
------------------------------------------------------------

spacy/matcher/phrasematcher.pyx:231:24: Call with wrong number of arguments (expected 2, got 3)

Error compiling Cython file:
------------------------------------------------------------
...
                current_node = <MapStruct*>result
            result = <MapStruct*>map_get(current_node, self._terminal_hash)
            if not result:
                internal_node = <MapStruct*>self.mem.alloc(1, sizeof(MapStruct))
                map_init(self.mem, internal_node, 8)
                map_set(self.mem, current_node, self._terminal_hash, internal_node)
                      ^
------------------------------------------------------------

spacy/matcher/phrasematcher.pyx:232:23: Call with wrong number of arguments (expected 3, got 4)

Error compiling Cython file:
------------------------------------------------------------
...
            if not result:
                internal_node = <MapStruct*>self.mem.alloc(1, sizeof(MapStruct))
                map_init(self.mem, internal_node, 8)
                map_set(self.mem, current_node, self._terminal_hash, internal_node)
                result = internal_node
            map_set(self.mem, <MapStruct*>result, self.vocab.strings[key], NULL)
                  ^
------------------------------------------------------------

spacy/matcher/phrasematcher.pyx:234:19: Call with wrong number of arguments (expected 3, got 4)
Traceback (most recent call last):
  File "/nix/store/naw86kmy92335k30fv11cfyydxbicva8-python3.11-pyproject-hooks-1.0.0/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/nix/store/naw86kmy92335k30fv11cfyydxbicva8-python3.11-pyproject-hooks-1.0.0/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/naw86kmy92335k30fv11cfyydxbicva8-python3.11-pyproject-hooks-1.0.0/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/dyl7f7v3cfi7j9d4z42pn2ss0bgw0r33-python3.11-setuptools-69.0.2/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/dyl7f7v3cfi7j9d4z42pn2ss0bgw0r33-python3.11-setuptools-69.0.2/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/nix/store/dyl7f7v3cfi7j9d4z42pn2ss0bgw0r33-python3.11-setuptools-69.0.2/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 221, in <module>
  File "<string>", line 208, in setup_package
  File "/nix/store/swcsynzqd5d82yzmykc94wc1gsz4z6bv-python3.11-cython-0.29.36/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1115, in cythonize
    cythonize_one(*args)
  File "/nix/store/swcsynzqd5d82yzmykc94wc1gsz4z6bv-python3.11-cython-0.29.36/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1238, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: spacy/matcher/phrasematcher.pyx

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

### Additional context

The error is caused by dependency `preshed` which is  at the unsupported version 4.0.0,  but version 4.0.0 of that package has been yanked, see #284758 . With previous version 3.0.9 it builds flawlessly.

### Notify maintainers

@GaetanLepage 
@mweinelt 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.1, NixOS, 24.05 (Uakari), 24.05.20240125.ae5c332`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.3`
 - channels(root): `"nixos"`
 - channels(azazel): `"home-manager, old"`
 - nixpkgs: `/nix/store/b9c11c60n2svicqc6zhk5wdngzym8daq-9s5qs4hni9fj88x79iw6im7amv7ghb76-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by azazel75** [comment]
I don't understand why this tries to compile when the package lists a dependency for preshed like `"preshed>=3.0.2,<3.1.0"`, shouldn't the build stop earlier because the requirements with preshed 4.0.0 aren't met?

**Comment by mweinelt** [comment]
The dependencies are checked on the resulting wheel, because that provides the metadata in a unified way.

EIther way: spacy builds again after reverting preshed.
