### ISSUE TITLE
Build failure: cobang

### ISSUE THREAD

**Issue by me00001** [NixOS/nixpkgs#285482]
### Steps To Reproduce

1. Be in nixos-unstable chanale
2. Run `nix-shell -p cobang`

### Build log

```
these 2 derivations will be built:
  /nix/store/1jn2vaf89nlkhc4i5vvk1cjw6jllzzxs-python3.11-kiss-headers-2.4.3.drv
  /nix/store/1zsq2qg3wxa6jqbz5yawq4as4mg55i68-cobang-0.10.1.drv
these 2 paths will be fetched (0.17 MiB download, 0.51 MiB unpacked):
  /nix/store/csi8s5hvdr9z8kna4f2i6h2ha8qkv47j-python3.11-python-zbar-0.23.90
  /nix/store/ivllm3fwdawqfsn1fg0dpjldc72ls9i0-zbar-0.23.92-lib
copying path '/nix/store/ivllm3fwdawqfsn1fg0dpjldc72ls9i0-zbar-0.23.92-lib' from 'https://cache.nixos.org'...
building '/nix/store/1jn2vaf89nlkhc4i5vvk1cjw6jllzzxs-python3.11-kiss-headers-2.4.3.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing setuptools-check-hook
Using setuptoolsCheckPhase
Sourcing pytest-check-hook
Using pytestCheckPhase
Removing setuptoolsCheckPhase
Running phase: unpackPhase
unpacking source archive /nix/store/0gb5w08f46wavqb80y86qmaqpk3v8bwv-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/tests/test_with_http_request.py
Running phase: patchPhase
substituteStream(): WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'setup.cfg')
substituteStream(): WARNING: pattern --cov=kiss_headers\ --doctest-modules\ --cov-report=term-missing\ -rxXs doesn't match anything in file 'setup.cfg'
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
no configure script, doing nothing
Running phase: buildPhase
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "/build/source/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/w4fvvhkzb0ssv0fw5j34pw09f0qw84w8-python3-3.11.7/lib/python3.11/tokenize.py", line 396, in open
    buffer = _builtin_open(filename, 'rb')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
/nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 1582: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/1jn2vaf89nlkhc4i5vvk1cjw6jllzzxs-python3.11-kiss-headers-2.4.3.drv' failed with exit code 1;
       last 10 log lines:
       > Executing setuptoolsBuildPhase
       > Traceback (most recent call last):
       >   File "/build/source/nix_run_setup", line 8, in <module>
       >     exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
       >                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/w4fvvhkzb0ssv0fw5j34pw09f0qw84w8-python3-3.11.7/lib/python3.11/tokenize.py", line 396, in open
       >     buffer = _builtin_open(filename, 'rb')
       >              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       > FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
       > /nix/store/bknngadwym46j65qs14ic2w79rpav888-stdenv-linux/setup: line 1582: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix-store -l /nix/store/1jn2vaf89nlkhc4i5vvk1cjw6jllzzxs-python3.11-kiss-headers-2.4.3.drv'.
error: 1 dependencies of derivation '/nix/store/1zsq2qg3wxa6jqbz5yawq4as4mg55i68-cobang-0.10.1.drv' failed to build

```

### Notify maintainers
@WolfangAukang

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.73, NixOS, 24.05 (Uakari), 24.05pre572380.842d9d80cfd4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(suliman): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
Can confirm that `cobang` builds and launches successfully after the fix is applied.
