### ISSUE TITLE
Unable to launch Setzer in foreign distro

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#285474]
### Describe the bug
```console
(process:6577): Gtk-WARNING **: 12:50:31.384: Locale not supported by C library.
	Using the fallback 'C' locale.
Fontconfig error: Cannot load default config file: No such file: (null)

** (.setzer-wrapped:6577): WARNING **: 12:50:32.279: Failed to load shared library '/nix/store/v4nvvybjiskhjmdrpy975mlsha4rbqgd-webkitgtk-2.42.4+abi=6.0/lib/libwebkitgtk-6.0.so.4' referenced by the typelib: /gnu/store/6ncav55lbk5kqvwwflrzcr41hp5jbq0c-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/v4nvvybjiskhjmdrpy975mlsha4rbqgd-webkitgtk-2.42.4+abi=6.0/lib/libwebkitgtk-6.0.so.4)

** (.setzer-wrapped:6577): WARNING **: 12:50:32.280: Failed to load shared library '/nix/store/v4nvvybjiskhjmdrpy975mlsha4rbqgd-webkitgtk-2.42.4+abi=6.0/lib/libjavascriptcoregtk-6.0.so.1' referenced by the typelib: /gnu/store/6ncav55lbk5kqvwwflrzcr41hp5jbq0c-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/v4nvvybjiskhjmdrpy975mlsha4rbqgd-webkitgtk-2.42.4+abi=6.0/lib/libjavascriptcoregtk-6.0.so.1)
/nix/store/g6l9y20628gridb0g2kypvn2n4m5rdfd-setzer-62/lib/python3.11/site-packages/setzer/workspace/help_panel/help_panel_viewgtk.py:92: Warning: cannot retrieve class for invalid (unclassed) type 'void'
  self.content = WebKit.WebView()
Traceback (most recent call last):
  File "/nix/store/g6l9y20628gridb0g2kypvn2n4m5rdfd-setzer-62/bin/..setzer-wrapped-wrapped", line 87, in do_activate
    self.activate()
  File "/nix/store/g6l9y20628gridb0g2kypvn2n4m5rdfd-setzer-62/lib/python3.11/site-packages/setzer/helpers/timer.py", line 25, in new_function
    return_value = original_function(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g6l9y20628gridb0g2kypvn2n4m5rdfd-setzer-62/bin/..setzer-wrapped-wrapped", line 123, in activate
    self.main_window.create_widgets()
  File "/nix/store/g6l9y20628gridb0g2kypvn2n4m5rdfd-setzer-62/lib/python3.11/site-packages/setzer/workspace/workspace_viewgtk.py", line 66, in create_widgets
    self.help_panel = help_panel_view.HelpPanelView()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g6l9y20628gridb0g2kypvn2n4m5rdfd-setzer-62/lib/python3.11/site-packages/setzer/workspace/help_panel/help_panel_viewgtk.py", line 92, in __init__
    self.content = WebKit.WebView()
                   ^^^^^^^^^^^^^^^^
TypeError: could not get a reference to type class
```

### Steps To Reproduce
1. Install Nix on a foreign distro (Guix System in my case)
2. Run `nix develop` to enable dev shell
3. Launch `setzer` from the CLI

### Expected behavior
Setzer should launch without any issues

### Additional context
I am on Guix System, trying to use access the dev shell I've set in a project that uses Nix flakes

### Notify maintainers

@dotlambda 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, Guix System, noversion, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/home/ashvith/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ashvith10** [comment]
To add more detail to the above post, this app works when I run it with `sudo`. However, I am no longer able to access fonts in the home directory. The CLI does not crash, however, no window is created.

**Comment by Ashvith10** [comment]
Closing this issue as #288042 describes the issue better.
