### ISSUE TITLE
`nixos-rebuild switch --upgrade` behaviour should be consistent when installing the bootloader fails

### ISSUE THREAD

**Issue by pvonmoradi** [NixOS/nixpkgs#286552]
### Describe the bug
I have a boot loader setup that can be thought of as ... "not ideal", to put it mildly. I was on NixOS `22.05`. Tried upgrading to `23.11`. `sudo nixos-rebuild switch --upgrade` gave me the following error and exited with 1:

```
...
updating systemd-boot from 250.4 to 254.6
Copied "/nix/store/qgjsvm3c4131qasxqbzphhd62j0lvvwh-systemd-254.6/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/efi/EFI/systemd/systemd-bootx64.efi".
Skipping "/boot/efi/EFI/BOOT/BOOTX64.EFI", it's owned by another boot loader (no version info found).
Traceback (most recent call last):
  File "/nix/store/v55r9ww078799y1q3ds4df88pnklxhl3-systemd-boot/bin/systemd-boot-builder", line 344, in <module>
    main()
  File "/nix/store/v55r9ww078799y1q3ds4df88pnklxhl3-systemd-boot/bin/systemd-boot-builder", line 332, in main
    install_bootloader(args)
  File "/nix/store/v55r9ww078799y1q3ds4df88pnklxhl3-systemd-boot/bin/systemd-boot-builder", line 280, in install_bootloader
    subprocess.check_call(["/nix/store/qgjsvm3c4131qasxqbzphhd62j0lvvwh-systemd-254.6/bin/bootctl", "--esp-path=/boot/efi"] + bootctl_flags + ["update"])
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/qgjsvm3c4131qasxqbzphhd62j0lvvwh-systemd-254.6/bin/bootctl', '--esp-path=/boot/efi', 'update']' returned non-zero exit status 1.
warning: error(s) occurred while switching to the new configuration
```
So I assumed the upgrade was unsuccessful. But, I tried running the command again but this time it exited successfully. Actually the upgrade was successful since I rebooted and checked the version.

### Expected behavior

IMO, the behaviour should have been consistent. Either `sudo nixos-rebuild switch --upgrade` should have produced an error both times or it shouldn't have produced an error altogether.

### Additional context
Follow up of a discussion with @ElvishJerricco 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.76, NixOS, 23.11 (Tapir), 23.11.3920.25e3d4c0d359`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ElvishJerricco** [comment]
To clarify, here's what happened.

`BOOTX64.EFI` was owned by another boot loader, i.e. not a systemd-boot binary. This caused `bootctl update` to exit non-zero even though it did update `systemd-bootx64.efi`, which terminated `systemd-boot-builder.py` before it was finished. On subsequent rebuilds, `bootctl update` was not invoked at all because `systemd-bootx64.efi` was found with the up-to-date version, so `systemd-boot-builder.py` was able to finish.

This inconsistency is problematic, but I'm not sure what to do about it.

**Comment by samueldr** [comment]
I'll add a note that assuming ownership of the default fallback location is likely undesirable "spec-wise", though also somewhat understandable pragmatically.

(This ownership of the default fallback location is a `systemd-boot` issue. Likely an upstream one. And isn't the point of resolving this discussion...)
