### ISSUE TITLE
symbol lookup error: UC_PROPERTY_BIDK_CONTROL

### ISSUE THREAD

**Issue by h3x3d** [NixOS/nixpkgs#286640]
### Describe the bug

I'm using flake based nixos installation with nix-pkgs unstable. After running nix flake update i got the following error on rebuild:

```
/nix/store/dsqs4fpljrws4ikzfriyixcp0n7kxrmk-nix-2.18.1/bin/nix-env: symbol lookup error: /nix/store/mgkvalznvc8ik2r9p93445vjbd80ax00-libunistring-1.1/lib/libunistring.so.5: undefined symbol: UC_PROPERTY_BIDK_CONTROL
Traceback (most recent call last):
  File "/nix/store/vlnh20ybha91fzd8x85q7c8my98j59i8-systemd-boot/bin/systemd-boot-builder", line 356, in <module>
    main()
  File "/nix/store/vlnh20ybha91fzd8x85q7c8my98j59i8-systemd-boot/bin/systemd-boot-builder", line 344, in main
    install_bootloader(args)
  File "/nix/store/vlnh20ybha91fzd8x85q7c8my98j59i8-systemd-boot/bin/systemd-boot-builder", line 297, in install_bootloader
    gens = get_generations()
           ^^^^^^^^^^^^^^^^^
  File "/nix/store/vlnh20ybha91fzd8x85q7c8my98j59i8-systemd-boot/bin/systemd-boot-builder", line 182, in get_generations
    gen_list = subprocess.check_output([
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/w4fvvhkzb0ssv0fw5j34pw09f0qw84w8-python3-3.11.7/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/w4fvvhkzb0ssv0fw5j34pw09f0qw84w8-python3-3.11.7/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/dsqs4fpljrws4ikzfriyixcp0n7kxrmk-nix-2.18.1/bin/nix-env', '--list-generations', '-p', '/nix/var/nix/profiles/system', '--option', 'build-users-group', '']' returned non-zero exit status 127.
warning: error(s) occurred while switching to the new configuration
```

### Expected behavior
System should rebuild without errors

### Additional context

Build is fine when flake.lock points to:
```json
{
    "nixpkgs": {
      "locked": {
        "lastModified": 1705133751,
        "narHash": "sha256-rCIsyE80jgiOU78gCWN3A0wE0tR2GI5nH6MlS+HaaSQ=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "9b19f5e77dd906cb52dade0b7bd280339d2a1f3d",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    }
}
```

But fails after i run `nix flake update` and initiate rebuild:
```json
{
    "nixpkgs": {
      "locked": {
        "lastModified": 1706191920,
        "narHash": "sha256-eLihrZAPZX0R6RyM5fYAWeKVNuQPYjAkCUBr+JNvtdE=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "ae5c332cbb5827f6b1f02572496b141021de335f",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    }
}
```

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
  /nix/store/v5irq7wvkr7kih0hhnch5nnv2dcq8c4f-stdenv-linux
copying path '/nix/store/v5irq7wvkr7kih0hhnch5nnv2dcq8c4f-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.73, NixOS, 24.05 (Uakari), 24.05.20240119.bbe7d8f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - channels(h3x3d): `""`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by h3x3d** [comment]
Issue fixed after updating to d934204a0f8d9198e1e4515dd6fec76a139c87f0
