### ISSUE TITLE
nixos-rebuild failure

### ISSUE THREAD

**Issue by sss123next** [NixOS/nixpkgs#286670]
### Describe the bug
nixos-rebuild  failing on nixos-23.11

```
nixos-rebuild  switch 
building Nix...
building the system configuration...
Traceback (most recent call last):
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 344, in <module>
    main()
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 332, in main
    install_bootloader(args)
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 288, in install_bootloader
    remove_old_entries(gens)
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 197, in remove_old_entries
    bootspec = get_bootspec(gen.profile, gen.generation)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 105, in get_bootspec
    return bootspec_from_json(bootspec_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 110, in bootspec_from_json
    return BootSpec(**bootspec_json['org.nixos.bootspec.v1'], specialisations=specialisations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BootSpec.__init__() missing 1 required positional argument: 'initrdSecrets'
warning: error(s) occurred while switching to the new configuration
```

```
nixos-rebuild  boot   
building Nix...
building the system configuration...
Traceback (most recent call last):
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 344, in <module>
    main()
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 332, in main
    install_bootloader(args)
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 288, in install_bootloader
    remove_old_entries(gens)
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 197, in remove_old_entries
    bootspec = get_bootspec(gen.profile, gen.generation)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 105, in get_bootspec
    return bootspec_from_json(bootspec_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ji9jb9nbixag1l8awcivlfri95g7yjf-systemd-boot/bin/systemd-boot-builder", line 110, in bootspec_from_json
    return BootSpec(**bootspec_json['org.nixos.bootspec.v1'], specialisations=specialisations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BootSpec.__init__() missing 1 required positional argument: 'initrdSecrets'
warning: error(s) occurred while switching to the new configuration

```

### Steps To Reproduce
1. run `nixos-rebuild switch` or `nixos-rebuild  boot`

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.3, NixOS, 24.05 (Uakari), 24.05pre579369.79a13f1437e1`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"alien, android-nixpkgs, nixgl, nixos-23.11-small, nixpkgs1809-18.09-small, nixpkgs2003-20.03-small, nixpkgs2009-20.09-small, nixpkgs2105-21.05-small, nixpkgs2111-21.11-small, nixpkgs2205-22.05-small, nixpkgs2211-22.11-small, nixpkgs2305-23.05-small, nixpkgs2311-23.11-small, nixpkgsmaster, nixpkgsunstable, nur"`
 - channels(sss): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.3, NixOS, 24.05 (Uakari), 24.05pre579369.79a13f1437e1`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"alien, android-nixpkgs, nixgl, nixos-23.11-small, nixpkgs1809-18.09-small, nixpkgs2003-20.03-small, nixpkgs2009-20.09-small, nixpkgs2105-21.05-small, nixpkgs2111-21.11-small, nixpkgs2205-22.05-small, nixpkgs2211-22.11-small, nixpkgs2305-23.05-small, nixpkgs2311-23.11-small, nixpkgsmaster, nixpkgsunstable, nur"`
 - channels(sss): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos````

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
CC @JulienMalka

**Comment by dotlambda** [comment]
@sss123next You should post the relevant parts of your configuration.

**Comment by ghpzin** [comment]
Probably relevant:
https://github.com/NixOS/nixpkgs/pull/278609#issuecomment-1880753177
https://github.com/NixOS/nixpkgs/pull/286739

**Comment by sss123next** [comment]
> @sss123next You should post the relevant parts of your configuration.

```
   boot = {
    loader = {
    systemd-boot = {
    enable = true;
    configurationLimit = 5;
#        memtest86.enable = true;
};
efi.canTouchEfiVariables = true;
timeout = 10;
};
initrd = {
compressor = "xz";
};
consoleLogLevel = 5;
};
```

**Comment by eclairevoyant** [comment]
23.11 is no longer relevant, closing.
