### ISSUE TITLE
pysol.py crashes with "module 'PIL.Image' has no attribute 'ANTIALIAS'"

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#286931]
### Describe the bug

As above.

### Steps To Reproduce
1. Run `nix-shell -p pysolfc`
2. Run `pysol.py`

### Expected behavior

The application should start.

### Additional context
Full log:

```
❯ pysol.py 
Traceback (most recent call last):
  File "/nix/store/4imqpk91g8w6m27533gcbp2d3cqrw24m-PySolFC-2.20.1/bin/.pysol.py-wrapped", line 37, in <module>
    from pysollib.main import main  # noqa: E402,I202
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/4imqpk91g8w6m27533gcbp2d3cqrw24m-PySolFC-2.20.1/lib/python3.11/site-packages/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/nix/store/4imqpk91g8w6m27533gcbp2d3cqrw24m-PySolFC-2.20.1/lib/python3.11/site-packages/pysollib/app.py", line 32, in <module>
    from pysollib.actions import PysolMenubar
  File "/nix/store/4imqpk91g8w6m27533gcbp2d3cqrw24m-PySolFC-2.20.1/lib/python3.11/site-packages/pysollib/actions.py", line 28, in <module>
    from pysollib.help import help_about, help_html
  File "/nix/store/4imqpk91g8w6m27533gcbp2d3cqrw24m-PySolFC-2.20.1/lib/python3.11/site-packages/pysollib/help.py", line 29, in <module>
    from pysollib.pysoltk import HTMLViewer
  File "/nix/store/4imqpk91g8w6m27533gcbp2d3cqrw24m-PySolFC-2.20.1/lib/python3.11/site-packages/pysollib/pysoltk.py", line 28, in <module>
    from pysollib.ui.tktile.tkutil import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/4imqpk91g8w6m27533gcbp2d3cqrw24m-PySolFC-2.20.1/lib/python3.11/site-packages/pysollib/ui/tktile/tkutil.py", line 250, in <module>
    class PIL_Image(ImageTk.PhotoImage):
  File "/nix/store/4imqpk91g8w6m27533gcbp2d3cqrw24m-PySolFC-2.20.1/lib/python3.11/site-packages/pysollib/ui/tktile/tkutil.py", line 291, in PIL_Image
    def resize(self, xf, yf, resample=Image.ANTIALIAS):
                                      ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

Running nixos-unstable.

### Notify maintainers

@kierdavis 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, NixOS, 24.05 (Uakari), 24.05pre577948.97b17f32362e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
This should be fixed by a simple update: https://github.com/shlomif/PySolFC/issues/323

**Comment by l0b0** [comment]
Same result after bumping:

```console
❯ ./result/bin/pysol.py 
Traceback (most recent call last):
  File "/nix/store/q8rq6zzmdyfppjsiyi8w7ip475vmrrjh-PySolFC-2.21.0/bin/.pysol.py-wrapped", line 37, in <module>
    from pysollib.main import main  # noqa: E402,I202
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/q8rq6zzmdyfppjsiyi8w7ip475vmrrjh-PySolFC-2.21.0/lib/python3.11/site-packages/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/nix/store/q8rq6zzmdyfppjsiyi8w7ip475vmrrjh-PySolFC-2.21.0/lib/python3.11/site-packages/pysollib/app.py", line 32, in <module>
    from pysollib.actions import PysolMenubar
  File "/nix/store/q8rq6zzmdyfppjsiyi8w7ip475vmrrjh-PySolFC-2.21.0/lib/python3.11/site-packages/pysollib/actions.py", line 28, in <module>
    from pysollib.help import help_about, help_html
  File "/nix/store/q8rq6zzmdyfppjsiyi8w7ip475vmrrjh-PySolFC-2.21.0/lib/python3.11/site-packages/pysollib/help.py", line 29, in <module>
    from pysollib.pysoltk import HTMLViewer
  File "/nix/store/q8rq6zzmdyfppjsiyi8w7ip475vmrrjh-PySolFC-2.21.0/lib/python3.11/site-packages/pysollib/pysoltk.py", line 28, in <module>
    from pysollib.ui.tktile.tkutil import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/q8rq6zzmdyfppjsiyi8w7ip475vmrrjh-PySolFC-2.21.0/lib/python3.11/site-packages/pysollib/ui/tktile/tkutil.py", line 250, in <module>
    class PIL_Image(ImageTk.PhotoImage):
  File "/nix/store/q8rq6zzmdyfppjsiyi8w7ip475vmrrjh-PySolFC-2.21.0/lib/python3.11/site-packages/pysollib/ui/tktile/tkutil.py", line 291, in PIL_Image
    def resize(self, xf, yf, resample=Image.ANTIALIAS):
                                      ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```
