### ISSUE TITLE
social-engineer-toolkit: broken tool usage due to read-only file system

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#287896]
### Describe the bug
When the tool is run by `sudo setoolkit`, we get the following error:
```
Traceback (most recent call last):
  File "/nix/store/qqsxbl0y0i6n60cklvw42nlyh61dbqhi-social-engineer-toolkit-8.0.3/bin/.setoolkit-wrapped", line 77, in <module>
    os.makedirs("src/logs/")
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: 'src/logs/'
```
How to fix it?

### Steps To Reproduce
1. `nix-shell -p social-engineer-toolkit`
2. `sudo setoolkit`

### Expected behavior
Not getting error on launching the tool.

### Notify maintainers

@emilytrau 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, Athena OS, 23.11 (Tapir), 23.11.3805.53fbe41cf76b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
https://github.com/trustedsec/social-engineer-toolkit/blob/master/setoolkit simply isn't compatible with Nix

**Comment by D3vil0p3r** [comment]
> https://github.com/trustedsec/social-engineer-toolkit/blob/master/setoolkit simply isn't compatible with Nix

Mm.. why it has been packaged for Nix if is not compatible?

**Comment by D3vil0p3r** [comment]
Since currently it is a package in Nix, I would keep the ticket opened. @emilytrau this constraint can be fixed by a patch file?

**Comment by D3vil0p3r** [comment]
@emilytrau is it possible to apply a patch file to it?
