### ISSUE TITLE
asynk.py does not work

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#28790]
## Issue description
global name 'vobject' is not defined

### Steps to reproduce

install asynk.py (either with nix-env -iA nixos.asynk or adding it to environment.systemPackages and switching to the configuration)

 creare a profile

`asynk.py --op=create-profile --name testbbcd --user-dir=~/.asynk.cd --db bb cd --folder default default --store <opath-to-bbdb-file> <CardDAV URL> --cduser=<username>`
try to sync
`asynk.py --op=sync --user-dir=~/.asynk.cd --name testbbcd --dry-run`

cc: @DamienCassou 

## Technical details

* System: 18.03pre114421.799435b7ca (Impala) (was the same on 17.09)
* Nix version: nix-env (Nix) 1.11.14 
* Nixpkgs version: "18.03pre114421.799435b7ca"
* Sandboxing enabled: build-use-sandbox = true (tried with sandboxing false, still the same)

edit: used template

**Comment by FRidh** [comment]
You will need to give more information. Please use the template and describe how you "install".

**Comment by DamienCassou** [comment]
I'm not using NixOS anymore. I can't help you.

**Comment by nico202** [comment]
@frerich updated the first post. I can provide a temporary account to try the sync, but that really should not matter. He just can't see the python dependency

**Comment by FRidh** [comment]
@nico202 thank you. Can you give the entire error/trace.

**Comment by nico202** [comment]
```
[11:20:53.840    ERROR] Error (global name 'vobject' is not defined) parsing vCard object for 571e65e2-178b-4d34-a713-51a40cdd8739                                                                
Traceback (most recent call last):              
  File "/nix/store/frsz5fwf82jpqa438rzh7632w09lyk5c-ASynK-2.0.0/bin/.asynk.py-wrapped", line 1125, in <module>                                                                                    
    main()                                      
  File "/nix/store/frsz5fwf82jpqa438rzh7632w09lyk5c-ASynK-2.0.0/bin/.asynk.py-wrapped", line 80, in main                                                                                          
    asynk.dispatch()                            
  File "/nix/store/frsz5fwf82jpqa438rzh7632w09lyk5c-ASynK-2.0.0/bin/.asynk.py-wrapped", line 511, in dispatch                                                                                     
    res = getattr(self, self.get_op())()        
  File "/nix/store/frsz5fwf82jpqa438rzh7632w09lyk5c-ASynK-2.0.0/bin/.asynk.py-wrapped", line 795, in op_sync                                                                                      
    sync.prep_lists(self.get_sync_dir())        
  File "/nix/store/frsz5fwf82jpqa438rzh7632w09lyk5c-ASynK-2.0.0/asynk/sync.py", line 283, in prep_lists                                                                                           
    return self._prep_lists_2_way(self.get_f1(), self.get_f2())                                  
  File "/nix/store/frsz5fwf82jpqa438rzh7632w09lyk5c-ASynK-2.0.0/asynk/sync.py", line 179, in _prep_lists_2_way                                                                                    
    f2.prep_sync_lists(f1.get_dbid(), f2sl)     
  File "/nix/store/frsz5fwf82jpqa438rzh7632w09lyk5c-ASynK-2.0.0/asynk/folder_cd.py", line 66, in prep_sync_lists                                                                                  
    curi  = self.get_itemids(pname, destid)     
  File "/nix/store/frsz5fwf82jpqa438rzh7632w09lyk5c-ASynK-2.0.0/asynk/folder_cd.py", line 119, in get_itemids                                                                                     
    self._refresh_contacts()                    
  File "/nix/store/frsz5fwf82jpqa438rzh7632w09lyk5c-ASynK-2.0.0/asynk/folder_cd.py", line 309, in _refresh_contacts                                                                               
    cons  = self.find_items(hrefs)              
  File "/nix/store/frsz5fwf82jpqa438rzh7632w09lyk5c-ASynK-2.0.0/asynk/folder_cd.py", line 182, in find_items                                                                                      
    cd = CDContact(self, vco=vobject.readOne(vcf.text), itemid=key)                              
NameError: global name 'vobject' is not defined 
```

**Comment by nico202** [comment]
It seems (from [here](https://github.com/skarra/ASynK/blob/05b8118039aa2d8193a7f738b03e559e5d2becce/.gitmodules) and [the author response](https://github.com/skarra/ASynK/issues/113)) that it's using vobject from a submodule

**Comment by tomodachi94** [comment]
`asynk` was removed in https://github.com/NixOS/nixpkgs/pull/95356.
