### ISSUE TITLE
tandoor-recipes: Import error when running manage.py

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#287956]
### Describe the bug

I'm trying to write a [test for Tandoor](https://github.com/NixOS/nixpkgs/pull/262892/files), and as part of that I need to create a user using `manage.py`. However, the interpreter for this script does not seem to include Django.

### Steps To Reproduce
1. Apply [this patch](https://github.com/NixOS/nixpkgs/pull/262892/commits/848581d442df2a6e1c55af862adc70116eb89dce)
2. Run `nix-build -A nixosTests.tandoor-recipes-script-name`

### Expected behavior

`manage.py` should run without installing any further dependencies.

### Additional context

Log excerpt:

```console
machine: must succeed: DJANGO_SUPERUSER_PASSWORD='any password' /nix/store/m0zagkqzpkxnd9ryxy14f5s8pqai73fc-python3.11-tandoor-recipes-1.5.12/lib/tandoor-recipes/manage.py createsuperuser --no-input --username='any_username' --email=nobody@example.com
machine # Traceback (most recent call last):
machine #   File "/nix/store/m0zagkqzpkxnd9ryxy14f5s8pqai73fc-python3.11-tandoor-recipes-1.5.12/lib/tandoor-recipes/manage.py", line 8, in <module>
machine #     from django.core.management import execute_from_command_line
machine # ModuleNotFoundError: No module named 'django'
machine # 
machine # The above exception was the direct cause of the following exception:
machine # 
machine # Traceback (most recent call last):
machine #   File "/nix/store/m0zagkqzpkxnd9ryxy14f5s8pqai73fc-python3.11-tandoor-recipes-1.5.12/lib/tandoor-recipes/manage.py", line 10, in <module>
machine #     raise ImportError(
machine # ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
machine: output: 
cleanup
kill machine (pid 9)
machine # qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/bin/python3.11)
(finished: cleanup, in 0.03 seconds)
Traceback (most recent call last):
  File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/__init__.py", line 126, in main
    driver.run_tests()
  File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 159, in run_tests
    self.test_script()
  File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 151, in test_script
    exec(self.tests, symbols, None)
  File "<string>", line 16, in <module>
  File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 706, in succeed
    raise Exception(f"command `{command}` failed (exit code {status})")
Exception: command `DJANGO_SUPERUSER_PASSWORD='any password' /nix/store/m0zagkqzpkxnd9ryxy14f5s8pqai73fc-python3.11-tandoor-recipes-1.5.12/lib/tandoor-recipes/manage.py createsuperuser --no-input --username='any_username' --email=nobody@example.com` failed (exit code 1)
kill vlan (pid 7)
error: builder for '/nix/store/8lz53z36x371bc8ywc2qywycqhnc00jy-vm-test-run-tandoor-recipes-script-name.drv' failed with exit code 1;
       last 25 log lines:
       > machine # 
       > machine # Traceback (most recent call last):
       > machine #   File "/nix/store/m0zagkqzpkxnd9ryxy14f5s8pqai73fc-python3.11-tandoor-recipes-1.5.12/lib/tandoor-recipes/manage.py", line 10, in <module>
       > machine #     raise ImportError(
       > machine # ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
       > machine: output:
       > cleanup
       > kill machine (pid 9)
       > machine # qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/bin/python3.11)
       > (finished: cleanup, in 0.03 seconds)
       > Traceback (most recent call last):
       >   File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
       >     sys.exit(main())
       >              ^^^^^^
       >   File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/__init__.py", line 126, in main
       >     driver.run_tests()
       >   File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 159, in run_tests
       >     self.test_script()
       >   File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 151, in test_script
       >     exec(self.tests, symbols, None)
       >   File "<string>", line 16, in <module>
       >   File "/nix/store/xbnrwrrmjmjzb6wg6z56wdblvydfq358-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 706, in succeed
       >     raise Exception(f"command `{command}` failed (exit code {status})")
       > Exception: command `DJANGO_SUPERUSER_PASSWORD='any password' /nix/store/m0zagkqzpkxnd9ryxy14f5s8pqai73fc-python3.11-tandoor-recipes-1.5.12/lib/tandoor-recipes/manage.py createsuperuser --no-input --username='any_username' --email=nobody@example.com` failed (exit code 1)
       > kill vlan (pid 7)
       For full logs, run 'nix log /nix/store/8lz53z36x371bc8ywc2qywycqhnc00jy-vm-test-run-tandoor-recipes-script-name.drv'.
```

Related issue: #262857 - I can't seem to get Tandoor to work with a subdirectory, so I'm trying to write a test to check whether it's actually possible to do it.

### Notify maintainers

@ambroisie 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, NixOS, 24.05 (Uakari), 24.05pre577948.97b17f32362e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ambroisie** [comment]
You should not use `manage.py` but the wrapper that is installed by the module at `/var/lib/tandoor-recipes/tandoor-recipes-manage`.

**Comment by l0b0** [comment]
> You should not use `manage.py` but the wrapper that is installed by the module at `/var/lib/tandoor-recipes/tandoor-recipes-manage`.

Wouldn't it be preferable to wrap `manage.py` in place? That way everything works the way the upstream docs say they should.

**Comment by ambroisie** [comment]
@l0b0 you can't have a package depend on the module.

This is the way it's done for all Django service in NixOS (paperless, photoprism, etc...).

**Comment by ambroisie** [comment]
> That way everything works the way the upstream docs say they should.

But it doesn't, because the environment variables (i.e: the configuration) is not going to be the same outside the service and inside the service. That's why we add the wrapper.

And in general, the documentation does _not_ apply for NixOS, so whether one should spell it `manage.py` or something else is really not an issue.
