### ISSUE TITLE
libgioenvironment: loads the host system's (e.g. Guix's) libstdc++

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#288042]
### Describe the bug

(Edited by @SomeoneSerge)

Nixpkgs software loads GIO plugins impurely (e.g. from `/run`, probably based on configuration in `/etc` or something, which is intended) and with them it risks loading an impure libstdc++. If the nixpkgs program doesn't link libstdc++ directly, but loads a GIO plugin first (with the host system's libstdc++), and later loads another C++-based dependency from Nixpkgs, the loading fails depending on the host system's libstdc++ version.

Assuming that nixpkgs' libstdc++ is always newer than the host system's (which it's generally not), consider special-casing libc and libstdc++ by pre-loading them?

### Original description by @Ashvith10

<details>

I have a Nix flake that is supposed to load a bunch of required TexLive packages as well as Setzer to build a document. `libstdc++.so.6` should be found by Nix, but instead it uses foreign distro's `libstdc++.so.6`. The issue is that Setzer simply does not work inside `nix develop` with both `23.05` and `23.11`. However, it works when I use `22.11`, because it happens to match the libstdc++ version. Here's the log:

```console
$ setzer 

(process:19847): Gtk-WARNING **: 19:41:50.257: Locale not supported by C library.
	Using the fallback 'C' locale.
Fontconfig error: Cannot load default config file: No such file: (null)

** (.setzer-wrapped:19847): WARNING **: 19:41:51.014: Failed to load shared library '/nix/store/rkdck16zm3zpbpy2c8a1vm4bc935v6s8-webkitgtk-2.42.5+abi=6.0/lib/libwebkitgtk-6.0.so.4' referenced by the typelib: /gnu/store/6ncav55lbk5kqvwwflrzcr41hp5jbq0c-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/rkdck16zm3zpbpy2c8a1vm4bc935v6s8-webkitgtk-2.42.5+abi=6.0/lib/libwebkitgtk-6.0.so.4)

** (.setzer-wrapped:19847): WARNING **: 19:41:51.016: Failed to load shared library '/nix/store/rkdck16zm3zpbpy2c8a1vm4bc935v6s8-webkitgtk-2.42.5+abi=6.0/lib/libjavascriptcoregtk-6.0.so.1' referenced by the typelib: /gnu/store/6ncav55lbk5kqvwwflrzcr41hp5jbq0c-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/rkdck16zm3zpbpy2c8a1vm4bc935v6s8-webkitgtk-2.42.5+abi=6.0/lib/libjavascriptcoregtk-6.0.so.1)
/nix/store/dzf369ynm2k3mcpm2p1b8cijp5yr15s8-setzer-62/lib/python3.11/site-packages/setzer/workspace/help_panel/help_panel_viewgtk.py:92: Warning: cannot retrieve class for invalid (unclassed) type 'void'
  self.content = WebKit.WebView()
Traceback (most recent call last):
  File "/nix/store/dzf369ynm2k3mcpm2p1b8cijp5yr15s8-setzer-62/bin/..setzer-wrapped-wrapped", line 87, in do_activate
    self.activate()
  File "/nix/store/dzf369ynm2k3mcpm2p1b8cijp5yr15s8-setzer-62/lib/python3.11/site-packages/setzer/helpers/timer.py", line 25, in new_function
    return_value = original_function(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/dzf369ynm2k3mcpm2p1b8cijp5yr15s8-setzer-62/bin/..setzer-wrapped-wrapped", line 123, in activate
    self.main_window.create_widgets()
  File "/nix/store/dzf369ynm2k3mcpm2p1b8cijp5yr15s8-setzer-62/lib/python3.11/site-packages/setzer/workspace/workspace_viewgtk.py", line 66, in create_widgets
    self.help_panel = help_panel_view.HelpPanelView()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/dzf369ynm2k3mcpm2p1b8cijp5yr15s8-setzer-62/lib/python3.11/site-packages/setzer/workspace/help_panel/help_panel_viewgtk.py", line 92, in __init__
    self.content = WebKit.WebView()
                   ^^^^^^^^^^^^^^^^
TypeError: could not get a reference to type class
```

Here's what happening: Setzer is unable to find libstdc++.so.6 inside the Nix directory. However, setting `LD_PRELOAD="${stdenv.cc.cc.lib}/lib/libstdc++.so.6"` does not resolve the issue - yes, Setzer launches, but building document with TexLive no longer works.

</details>

Here's the [dump.log](https://gist.github.com/Ashvith10/467c68a7d85afc6f4e5167479fe08aca). Part of the conversation is available at the end of #287764.

### Steps To Reproduce
1. Boot Guix System.
2. Run `nix develop` for flake
3. Launch `setzer`

### Expected behavior
`libstdc++.so.6` should not use foreign distro's `libstdc++.so.6`. The app should launch without any issues.

### Screenshots
\-

### Additional context
I am on Guix System

### Notify maintainers
@edolstra 
@fabaff 
@SuperSandro2000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/k3bdc93j9farp9wpxp9lwjzwvss5jsy4-nix-info
copying path '/nix/store/k3bdc93j9farp9wpxp9lwjzwvss5jsy4-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, Guix System, noversion, nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/home/ashvith/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
duplicate of issues like #287764

**Comment by SomeoneSerge** [comment]
@SuperSandro2000 partly my fault, I suggested opening a new issue, but didn't explain what to emphasize. I edited the description and reopen the issue for now. I'm not sure there's anything to be actually done about it, but I think it's good to at least to document the edge-case (in the form of a gh issue)
