### ISSUE TITLE
Build failure: veusz

### ISSUE THREAD

**Issue by fastfailure** [NixOS/nixpkgs#288235]
### Steps To Reproduce

`nix-shell -p veusz`

### Build log

```
Traceback (most recent call last):
  File "/build/veusz-3.6.2/tests/.runselftest.py-wrapped", line 319, in <module>
    runTests(
  File "/build/veusz-3.6.2/tests/.runselftest.py-wrapped", line 246, in runTests
    renderVszTest(infile, outfile, test_saves=test_saves,
  File "/build/veusz-3.6.2/tests/.runselftest.py-wrapped", line 184, in renderVszTest
    ifc.Export(outfile)
  File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/document/commandinterface.py", line 810, in Export
    e.add(filename, pages)
  File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/document/export.py", line 453, in add
    self.doc.paintTo(phelper, page)
  File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/document/doc.py", line 369, in paintTo
    self.basewidget.draw(painthelper, page)
  File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/widgets/root.py", line 144, in draw
    page.draw( posn, painthelper )
  File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/widgets/page.py", line 371, in draw
    bounds = widget.Widget.draw(
             ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/widgets/widget.py", line 298, in draw
    c.draw(bounds, painthelper, outerbounds=outerbounds)
  File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/widgets/scene3d.py", line 220, in draw
    root = self.makeObjects(painter, bounds, painthelper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/widgets/scene3d.py", line 174, in makeObjects
    obj = c.drawToObject(painter, painthelper)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/widgets/graph3d.py", line 236, in drawToObject
    self.addBorder(painter, cont)
  File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/widgets/graph3d.py", line 169, in addBorder
    ls = threed.LineSegments(
         ^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  LineSegments(x1: ValVector, y1: ValVector, z1: ValVector, x2: ValVector, y2: ValVector, z2: ValVector, prop: Optional[LineProp]): argument 2 has unexpected type 'ValVector'
  LineSegments(pts1: ValVector, pts2: ValVector, prop: Optional[LineProp]): argument 2 has unexpected type 'ValVector'
  LineSegments(a0: LineSegments): argument 1 has unexpected type 'ValVector'
error: builder for '/nix/store/p1mw9fz1jj383shwxcxvp53g7ksmlzrb-veusz-3.6.2.drv' failed with exit code 1;
       last 10 log lines:
       >           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/widgets/graph3d.py", line 236, in drawToObject
       >     self.addBorder(painter, cont)
       >   File "/nix/store/1h7fccsz5xc5zfqwh1s8m3facg6565cj-veusz-3.6.2/lib/python3.11/site-packages/veusz/widgets/graph3d.py", line 169, in addBorder
       >     ls = threed.LineSegments(
       >          ^^^^^^^^^^^^^^^^^^^^
       > TypeError: arguments did not match any overloaded call:
       >   LineSegments(x1: ValVector, y1: ValVector, z1: ValVector, x2: ValVector, y2: ValVector, z2: ValVector, prop: Optional[LineProp]): argument 2 has unexpected type 'ValVector'
       >   LineSegments(pts1: ValVector, pts2: ValVector, prop: Optional[LineProp]): argument 2 has unexpected type 'ValVector'
       >   LineSegments(a0: LineSegments): argument 1 has unexpected type 'ValVector'
       For full logs, run 'nix-store -l /nix/store/p1mw9fz1jj383shwxcxvp53g7ksmlzrb-veusz-3.6.2.drv'.
```

### Notify maintainers

@laikq

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.6.15, NixOS, 23.11 (Tapir), 23.11.4117.6832d0d99649`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.1`
- channels(root): `"home-manager-23.11.tar.gz, nixos-23.11, nixos-unstable"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ocfox** [comment]
Unable to reproduce on master branch.

**Comment by ghpzin** [comment]
Seems to only fail on 23.11 (and was never successfully built after 23.11 branch was created at all):
https://hydra.nixos.org/job/nixos/release-23.11/nixpkgs.veusz.x86_64-linux/all
It was failing on unstable with same error between `2023-10-23` and `2023-12-12`:
https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.veusz.x86_64-linux
```
TypeError: arguments did not match any overloaded call:
  LineSegments(x1: ValVector, y1: ValVector, z1: ValVector, x2: ValVector, y2: ValVector, z2: ValVector, prop: Optional[LineProp]): argument 2 has unexpected type 'ValVector'
  LineSegments(pts1: ValVector, pts2: ValVector, prop: Optional[LineProp]): argument 2 has unexpected type 'ValVector'
  LineSegments(a0: LineSegments): argument 1 has unexpected type 'ValVector'
```
But builds fine on unstable after build on `2024-01-13`.
