### ISSUE TITLE
Build failure: Django

### ISSUE THREAD

**Issue by sss123next** [NixOS/nixpkgs#288280]
### Steps To Reproduce

1. build Django

### Build log

```
Destroying test database for alias 'other'...
Traceback (most recent call last):
  File "/build/Django-4.2.9/tests/runtests.py", line 773, in <module>
    failures = django_tests(
               ^^^^^^^^^^^^^
  File "/build/Django-4.2.9/tests/runtests.py", line 432, in django_tests
    failures = test_runner.run_tests(test_labels)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/cvgdm50pk7lsalv7m9dpglhq2bb5qg56-python3.11-Django-4.2.9/lib/python3.11/site-packages/django/test/runner.py", line 1061, in run_tests
    result = self.run_suite(suite)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/cvgdm50pk7lsalv7m9dpglhq2bb5qg56-python3.11-Django-4.2.9/lib/python3.11/site-packages/django/test/runner.py", line 983, in run_suite
    return runner.run(suite)
           ^^^^^^^^^^^^^^^^^
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/unittest/runner.py", line 217, in run
    test(result)
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/cvgdm50pk7lsalv7m9dpglhq2bb5qg56-python3.11-Django-4.2.9/lib/python3.11/site-packages/django/test/runner.py", line 510, in run
    pool = multiprocessing.Pool(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
               ^^^^^^^^^
OSError: [Errno 12] Cannot allocate memory
error: build of '/nix/store/wmqw2lm8ig6yfzxgpcg8hzldcr040s5y-python3.11-Django-4.2.9.drv' on 'ssh://nix-builder@192.168.0.22' failed: builder for '/nix/store/wmqw2lm8ig6yfzxgpcg8hzldcr040s5y-python3.11-Django-4.2.9.drv' failed with exit code 1;
       last 10 log lines:
       >                   ^^^^^^^^^^^^^^^^^
       >   File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/context.py", line 281, in _Popen
       >     return Popen(process_obj)
       >            ^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
       >     self._launch(process_obj)
       >   File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/popen_fork.py", line 66, in _launch
       >     self.pid = os.fork()
       >                ^^^^^^^^^
       > OSError: [Errno 12] Cannot allocate memory
       For full logs, run 'nix log /nix/store/wmqw2lm8ig6yfzxgpcg8hzldcr040s5y-python3.11-Django-4.2.9.drv'.
error: builder for '/nix/store/wmqw2lm8ig6yfzxgpcg8hzldcr040s5y-python3.11-Django-4.2.9.drv' failed with exit code 1;
       last 10 log lines:
       >                   ^^^^^^^^^^^^^^^^^
       >   File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/context.py", line 281, in _Popen
       >     return Popen(process_obj)
       >            ^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
       >     self._launch(process_obj)
       >   File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/lib/python3.11/multiprocessing/popen_fork.py", line 66, in _launch
       >     self.pid = os.fork()
       >                ^^^^^^^^^
       > OSError: [Errno 12] Cannot allocate memory
       For full logs, run 'nix log /nix/store/wmqw2lm8ig6yfzxgpcg8hzldcr040s5y-python3.11-Django-4.2.9.drv'.
```

### Additional context

on machine with 1TB free ram

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.3, NixOS, 23.11 (Tapir), 23.11.4144.c1a3b4e3ddda`
 - multi-user?: `no`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"alien, android-nixpkgs, nixgl, nixos-23.11-small, nixpkgs1809-18.09-small, nixpkgs2003-20.03-small, nixpkgs2009-20.09-small, nixpkgs2105-21.05-small, nixpkgs2111-21.11-small, nixpkgs2205-22.05-small, nixpkgs2211-22.11-small, nixpkgs2305-23.05-small, nixpkgs2311-23.11-small, nixpkgsmaster, nixpkgsunstable, nur"`
 - channels(sss): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
Can't reproduce, especially not without a git revision and a command to run.

**Comment by sss123next** [comment]
most probably problem caused by hardware configuration, in log i see this:
```
Running phase: installCheckPhase
/build/Django-4.2.11/tests /build/Django-4.2.11
Testing against Django installed in '/nix/store/nic67ay21dbd5qv226bp8jj2w7n0kvl9-python3.11-Django-4.2.11/lib/python3.11/site-packages/django' with up to 128 processes
Found 16335 test(s).
```

i do not think it bound to specific revision, problem still happening right now on current 23.11 revision
