### ISSUE TITLE
Build failure: tikzplotlib

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#289305]
### Steps To Reproduce

1. build `tikzplotlib` using this `flake.nix` and `nix develop .`:
```
 {
  description = "my project description";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem
      (system:
        let pkgs = nixpkgs.legacyPackages.${system}; in
        {
          devShells.default = pkgs.mkShell {
            buildInputs = with pkgs; [
              (python3.withPackages (ps: with ps; [matplotlib tikzplotlib]))
            ];
          };
        }
      );
}
```
(tested on rev `a4d4fe8c5002202493e87ec8dbc91335ff55552c`)

### Build log

```
$ nix develop .
error: builder for '/nix/store/4p8zvnnqm6lnlqxnhs30smyb5yz4s7fc-python3.11-tikzplotlib-0.10.1.drv' failed with exit code 1;
       last 10 log lines:
       >   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
       >   File "/build/source/src/tikzplotlib/__init__.py", line 5, in <module>
       >     from ._save import Flavors, get_tikz_code, save
       >   File "/build/source/src/tikzplotlib/_save.py", line 11, in <module>
       >     from . import _axes
       >   File "/build/source/src/tikzplotlib/_axes.py", line 3, in <module>
       >     from matplotlib.backends.backend_pgf import (
       > ImportError: cannot import name 'common_texification' from 'matplotlib.backends.backend_pgf' (/nix/store/sqrahcfiwwgf2i7517d5brdbgy91yngz-python3.11-matplotlib-3.8.2/lib/python3.11/site-packages/matplotlib/backends/backend_pgf.py)
       >
       > ERROR Backend subprocess exited when trying to invoke build_wheel
       For full logs, run 'nix log /nix/store/4p8zvnnqm6lnlqxnhs30smyb5yz4s7fc-python3.11-tikzplotlib-0.10.1.drv'.
error: 1 dependencies of derivation '/nix/store/7x8ssalc5w50wa3pxm1ckkd39h04qj21-python3-3.11.7-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5wxryg6sgd6vpvm4q1r13bj663g7m7h1-nix-shell-env.drv' failed to build

```

### Additional context

Not sure if the issue is from matplotlib or tikzplotlib…

### Notify maintainers

@doronbehar @lovek323 @veprbl

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by veprbl** [comment]
cc @xworld21

**Comment by veprbl** [comment]
Not a latex issue, maybe? Need bump for compatibility with recent matplotlib?

**Comment by tobiasBora** [comment]
What do you mean? Is LaTeX really needed to generate the file? I thought that LaTeX would be needed only when inputting the file.

Also, I tried to use `pip` + `virtualenv`, I also get a similar issue:
```
>>> import tikzplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/python/venv/lib/python3.10/site-packages/tikzplotlib/__init__.py", line 5, in <module>
    from ._save import Flavors, get_tikz_code, save
  File "/tmp/python/venv/lib/python3.10/site-packages/tikzplotlib/_save.py", line 11, in <module>
    from . import _axes
  File "/tmp/python/venv/lib/python3.10/site-packages/tikzplotlib/_axes.py", line 3, in <module>
    from matplotlib.backends.backend_pgf import (
ImportError: cannot import name 'common_texification' from 'matplotlib.backends.backend_pgf' (/tmp/python/venv/lib/python3.10/site-packages/matplotlib/backends/backend_pgf.py)
>>> 

```

**Comment by tobiasBora** [comment]
Ok, I can confirm it is an upstream bug:
https://github.com/nschloe/tikzplotlib/issues/559
https://github.com/nschloe/tikzplotlib/issues/595

The "solution" is to use matplotlib 3.6, but I guess in nixpkgs a single version is used at a time. The last working upgrade is from 09116080bca0c6836c08b4718783185383b8a13d I guess (I tried using virtualenv + pip + nix-ld + `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$NIX_LD_LIBRARY_PATH"`)

**Comment by doronbehar** [comment]
Upstream seems to warn the users that their development efforts are low at the moment, so I think we need to provide an intermediate, Nixpkgs solution. We can provide a `python311Packages.matplotlib3_6` that will be used just for `tikzplotlib`.

**Comment by tobiasBora** [comment]
That might be a good idea indeed, maybe the only one unless someone manages.to fix upstream.

**Comment by doronbehar** [comment]
I'll be too busy in the near future to do it myself, but would gladly review and merge such a PR.
