### ISSUE TITLE
nixos-generate-config seemed to set efiSysMountPoint to `/boot` isntead of `/boot/efi` in inappropriate situations

### ISSUE THREAD

**Issue by makoConstruct** [NixOS/nixpkgs#289848]
Rephrasing/summary of https://github.com/NixOS/nixpkgs/issues/275365.

### Describe the bug
One day, I woke up and couldn't rebuild my config. It would complain that it could not find the bootloader. This seemed to be due to a failing regex search over the output of a `bootctl` query.

Eventually I set my hardware config's `boot.loader.efi.efiSysMountPoint = "/boot/efi";` and the problem went away.

I [made a little effort](https://github.com/NixOS/nixpkgs/issues/275365#issuecomment-1869852970) to figure out whether nixos-generate-config still produces this issue, and it seems like it does, but I identified [a mysterious commented out line](https://github.com/NixOS/nixpkgs/blame/6a9bfbfa1001235034f486b52791830451bf0bf1/nixos/modules/installer/tools/nixos-generate-config.pl#L678) that used to set `efiSysMountPoint` to `/boot/efi` as required, which gives me hope that someone, at some point, understood what might have gone wrong here.

The problem might reside in generate-config, or it might just require making that regex a bit more flexible.

### Additional context
See the prior issue https://github.com/NixOS/nixpkgs/issues/275365 where I was more confused for whole investigation.

### Notify maintainers

I initially tried to notify @obadz, who was git blamed for [the commented out line](https://github.com/NixOS/nixpkgs/blame/6a9bfbfa1001235034f486b52791830451bf0bf1/nixos/modules/installer/tools/nixos-generate-config.pl#L678) in generate-config, but they didn't respond.
@lheckemann might understand this aspect of generate-config's responsibilities.
@waldheinz is [blamed for the systemd-boot regex](https://github.com/NixOS/nixpkgs/blame/a44665ce2c16a24bd048baf21594e5930d2da131/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L276).

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by grerrg** [comment]
run into this error after installing nixos 23.11 via graphical installer. i've selected `delete entire disk and install nixos`.

# error

```hardware-configuration.nix
{ config, lib, pkgs, modulesPath, ... }:

{
[...]
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e11e255e-c419-45fa-99fa-cc1a819b8d82";
      fsType = "ext4";
    };
[...]
}

```

```lsblk.bash
$ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda      8:0    0 931,5G  0 disk 
├─sda1   8:1    0 897,1G  0 part /nix/store
│                                /
└─sda2   8:2    0  34,4G  0 part [SWAP]

```

```error.bash
$ sudo nixos-rebuild switch --flake .#
[...]
File system "/boot" is not a FAT EFI System Partition (ESP) file system.
systemd-boot not installed in ESP.
No default/fallback boot loader installed in ESP.
Traceback (most recent call last):
  File "/nix/store/62rk7fv5m3rbi5jiwlhs45iahw1ghjjg-systemd-boot/bin/systemd-boot-builder", line 343, in <module>
    main()
  File "/nix/store/62rk7fv5m3rbi5jiwlhs45iahw1ghjjg-systemd-boot/bin/systemd-boot-builder", line 331, in main
    install_bootloader(args)
  File "/nix/store/62rk7fv5m3rbi5jiwlhs45iahw1ghjjg-systemd-boot/bin/systemd-boot-builder", line 269, in install_bootloader
    raise Exception("could not find any previously installed systemd-boot")
Exception: could not find any previously installed systemd-boot
warning: error(s) occurred while switching to the new configuration

```

haven't tested with nixos-24.05 installer since wi-fi drivers won't come up.

# possible solution

fresh install with manual partitioning.

**Comment by lheckemann** [comment]
@grerrg that looks to me like you haven't created an EFI System Partition, which is required for booting a system via UEFI (and systemd-boot only supports EFI). Try adding an ESP or switching to GRUB.

**Comment by Atemu** [comment]
@grerrg you must set NIXOS_INSTALL_BOOTLOADER=1 in order to install systemd-boot. `nixos-install` sets this by default.
