### ISSUE TITLE
Cozy 

### ISSUE THREAD

**Issue by balacy** [NixOS/nixpkgs#291085]
### Describe the bug
A modern audio book player for Linux using GTK 3

### Steps To Reproduce
1. Install:   environment.systemPackages = [
    pkgs.cozy
  ];

2. Start cozy, and typed this into the terminal:

[nix-shell:~]$ cozy
['/nix/store/azhm1hs8vyirp80nc5mbi6ng9617mang-cozy-1.2.1/bin/.com.github.geigi.cozy-wrapped']
09:34:27 [MainThread  ] [applicatio] [INFO ]  ('nixos', '23.11', 'Tapir')
09:34:27 [MainThread  ] [applicatio] [INFO ]  Starting up cozy 1.2.1
09:34:27 [MainThread  ] [db        ] [INFO ]  SQLite version: 3.43.2
09:34:27 [Thread-1 (ru] [peewee.sql] [INFO ]  writer received shutdown request, exiting.

(.com.github.geigi.cozy-wrapped:70855): Handy-WARNING **: 09:34:27.419: Using GtkSettings:gtk-application-prefer-dark-theme together with HdyStyleManager is unsupported. Please use HdyStyleManager:color-scheme instead.
09:34:27 [MainThread  ] [applicatio] [INFO ]  libhandy version: 1
handle exception
Traceback (most recent call last):
  File "/nix/store/azhm1hs8vyirp80nc5mbi6ng9617mang-cozy-1.2.1/lib/python3.11/site-packages/cozy/application.py", li
ne 99, in do_activate
    self.app_controller = AppController(self, main_window_builder, self.ui)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/azhm1hs8vyirp80nc5mbi6ng9617mang-cozy-1.2.1/lib/python3.11/site-packages/cozy/architecture/singleton.py", line 5, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/azhm1hs8vyirp80nc5mbi6ng9617mang-cozy-1.2.1/lib/python3.11/site-packages/cozy/app_controller.py", line 52, in __init__
    self.whats_new_window: WhatsNewWindow = WhatsNewWindow()
                                            ^^^^^^^^^^^^^^^^
  File "/nix/store/azhm1hs8vyirp80nc5mbi6ng9617mang-cozy-1.2.1/lib/python3.11/site-packages/cozy/ui/widgets/whats_new_window.py", line 36, in __init__
    self._fill_window()
  File "/nix/store/azhm1hs8vyirp80nc5mbi6ng9617mang-cozy-1.2.1/lib/python3.11/site-packages/cozy/ui/widgets/whats_new_window.py", line 54, in _fill_window
    last_launched_version = version.parse(self.app_settings.last_launched_version)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/j6ns4jq162wyp4zdpi3zjiz9im6rchb5-python3.11-packaging-23.1/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/nix/store/j6ns4jq162wyp4zdpi3zjiz9im6rchb5-python3.11-packaging-23.1/lib/python3.11/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None'

### Notify maintainers

@makefu 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

[nix-shell:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.78, NixOS, 23.11 (Tapir), 23.11.4621.3cb4ae6689d2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by simonhollingshead** [comment]
It looks like patch https://github.com/geigi/cozy/pull/762 needs to be merged in.
