### ISSUE TITLE
`audible-cli` missing setup tools dependency 

### ISSUE THREAD

**Issue by fedeinthemix** [NixOS/nixpkgs#291154]
### Describe the bug
The `audible` command crashes complaining about a missing module

### Steps To Reproduce
1. $ nix shell nixpkgs#audible-cli
2. $ audible

the ouutput I get is
```nix
Traceback (most recent call last):
  File "/nix/store/4j9pb0bvqanw2i9bmg5n3f4myilisxh3-audible-cli-0.2.6/bin/.audible-wrapped", line 6, in <module>
    from audible_cli import main
  File "/nix/store/4j9pb0bvqanw2i9bmg5n3f4myilisxh3-audible-cli-0.2.6/lib/python3.11/site-packages/audible_cli/__init__.py", line 5, in <module>
    from .cli import main, quickstart
  File "/nix/store/4j9pb0bvqanw2i9bmg5n3f4myilisxh3-audible-cli-0.2.6/lib/python3.11/site-packages/audible_cli/cli.py", line 3, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

### Notify maintainers

@jvanbruegge 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.78, NixOS, 23.11 (Tapir), 23.11.4621.3cb4ae6689d2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(beffa): `""`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Please take a look at #291830
