### ISSUE TITLE
Build failure: pyradio

### ISSUE THREAD

**Issue by aaronpkelly** [NixOS/nixpkgs#291331]
### Steps To Reproduce

1. `nix-shell -p pyradio`

### Build log

```
nix-shell -p pyradio
this derivation will be built:
  /nix/store/0s6bnxda0r02wa6q2c5sc15sa4isg7f6-pyradio-0.9.1.drv
building '/nix/store/0s6bnxda0r02wa6q2c5sc15sa4isg7f6-pyradio-0.9.1.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing setuptools-check-hook
Running phase: unpackPhase
unpacking source archive /nix/store/vc2cmjs9jghggpfl0ss4pw6090q5wj2a-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/windows.md
Running phase: patchPhase
Running phase: configurePhase
no configure script, doing nothing
Running phase: buildPhase
Executing setuptoolsBuildPhase
/nix/store/nq1q5lrxwnb8a5gx03q2whv9xz5pbwiw-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:75: _MissingDynamic: `license` defined outside of `pyproject.toml` is ignored.
!!

        ********************************************************************************
        The following seems to be defined outside of `pyproject.toml`:

        `license = 'MIT'`

        According to the spec (see the link below), however, setuptools CANNOT
        consider this value unless `license` is listed as `dynamic`.

        https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

        To prevent this problem, you can list `license` under `dynamic` or alternatively
        remove the `[project]` table from your file and rely entirely on other means of
        configuration.
        ********************************************************************************

!!
  _handle_missing_dynamic(dist, project_table)
Traceback (most recent call last):
  File "/private/tmp/nix-build-pyradio-0.9.1.drv-0/source/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 43, in <module>
    setup(**meta)
  File "/nix/store/nq1q5lrxwnb8a5gx03q2whv9xz5pbwiw-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/nq1q5lrxwnb8a5gx03q2whv9xz5pbwiw-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/nix/store/nq1q5lrxwnb8a5gx03q2whv9xz5pbwiw-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/dist.py", line 627, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/nix/store/nq1q5lrxwnb8a5gx03q2whv9xz5pbwiw-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 67, in apply_configuration
    return _apply(dist, config, filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/nq1q5lrxwnb8a5gx03q2whv9xz5pbwiw-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 56, in apply
    _apply_project_table(dist, config, root_dir)
  File "/nix/store/nq1q5lrxwnb8a5gx03q2whv9xz5pbwiw-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 82, in _apply_project_table
    corresp(dist, value, root_dir)
  File "/nix/store/nq1q5lrxwnb8a5gx03q2whv9xz5pbwiw-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 183, in _license
    _set_config(dist, "license", val["text"])
                                 ~~~^^^^^^^^
KeyError: 'text'
/nix/store/3jfs2509ipygw5qbd5yaawmnrmx7xh8n-stdenv-darwin/setup: line 1591: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/0s6bnxda0r02wa6q2c5sc15sa4isg7f6-pyradio-0.9.1.drv' failed with exit code 1;
       last 10 log lines:
       >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/nq1q5lrxwnb8a5gx03q2whv9xz5pbwiw-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 56, in apply
       >     _apply_project_table(dist, config, root_dir)
       >   File "/nix/store/nq1q5lrxwnb8a5gx03q2whv9xz5pbwiw-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 82, in _apply_project_table
       >     corresp(dist, value, root_dir)
       >   File "/nix/store/nq1q5lrxwnb8a5gx03q2whv9xz5pbwiw-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 183, in _license
       >     _set_config(dist, "license", val["text"])
       >                                  ~~~^^^^^^^^
       > KeyError: 'text'
       > /nix/store/3jfs2509ipygw5qbd5yaawmnrmx7xh8n-stdenv-darwin/setup: line 1591: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix-store -l /nix/store/0s6bnxda0r02wa6q2c5sc15sa4isg7f6-pyradio-0.9.1.drv'.
```

### Additional context

I'm using `nixpkgs-unstable`

### Notify maintainers

@contrun 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by luzpaz** [comment]
Just a heads-up that the latest stable is https://github.com/coderholic/pyradio/releases/tag/0.9.2.25 and has dropped python2 support.
