### ISSUE TITLE
woeusbgui fails to start (package "woeusb-ng")

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#291932]
`woeusbgui` fails to start ( package: `woeusb-ng` )

I am using NixOS 23.11 and Gnome. System is up to date, nothing special installed.

Error =>

```
[user:~]$ woeusbgui 
Traceback (most recent call last):
  File "/nix/store/hs4r4kavb72qgzz8xs9d22689aqmnyd9-woeusb-ng-0.2.12/bin/..woeusbgui-wrapped-wrapped", line 34, in <module>
    import WoeUSB.gui
  File "/nix/store/hs4r4kavb72qgzz8xs9d22689aqmnyd9-woeusb-ng-0.2.12/lib/python3.11/site-packages/WoeUSB/gui.py", line 17, in <module>
    app = wx.App()
          ^^^^^^^^
  File "/nix/store/2798pwc36wnsv8mbzximn76n3p5p9d18-python3.11-wxPython-4.2.1/lib/python3.11/site-packages/wx/core.py", line 2197, in __init__
    raise SystemExit(msg)
SystemExit: Unable to access the X Display, is $DISPLAY set properly?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/hs4r4kavb72qgzz8xs9d22689aqmnyd9-woeusb-ng-0.2.12/bin/..woeusbgui-wrapped-wrapped", line 39, in <module>
    WoeUSB.utils.update_policy_to_allow_for_running_gui_as_root(__file__)
  File "/nix/store/hs4r4kavb72qgzz8xs9d22689aqmnyd9-woeusb-ng-0.2.12/lib/python3.11/site-packages/WoeUSB/utils.py", line 385, in update_policy_to_allow_for_running_gui_as_root
    with open("/nix/store/hs4r4kavb72qgzz8xs9d22689aqmnyd9-woeusb-ng-0.2.12/share/polkit-1/actions/com.github.woeusb.woeusb-ng.policy", "w") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/nix/store/hs4r4kavb72qgzz8xs9d22689aqmnyd9-woeusb-ng-0.2.12/share/polkit-1/actions/com.github.woeusb.woeusb-ng.policy'
```

**Comment by IogaMaster** [comment]
Please run 
```
nix-shell -p nix-info --run "nix-info -m"
```

**Comment by boustanihani** [comment]
Here is the output of `nix-info`:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.79, NixOS, 23.11 (Tapir), 23.11.4801.b7ee09cf5614`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by onny** [comment]
could you please try with the latest nixos 24.11. it is starting for me

**Comment by boustanihani** [comment]
Still same error using `NixOS 24.11`.
By the way, I am using `XORG` (not `WAYLAND`) !

```
Traceback (most recent call last):
  File "/nix/store/c8mzyq1vwikw8sqzgwsngsdapcs6a2fq-woeusb-ng-0.2.12/bin/..woeusbgui-wrapped-wrapped", line 34, in <module>
    import WoeUSB.gui
  File "/nix/store/c8mzyq1vwikw8sqzgwsngsdapcs6a2fq-woeusb-ng-0.2.12/lib/python3.12/site-packages/WoeUSB/gui.py", line 17, in <module>
    app = wx.App()
          ^^^^^^^^
  File "/nix/store/gchy6n7gc42hyamg0my4ldzyx857crq9-python3.12-wxpython-4.2.2/lib/python3.12/site-packages/wx/core.py", line 2197, in __init__
    raise SystemExit(msg)
SystemExit: Unable to access the X Display, is $DISPLAY set properly?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/c8mzyq1vwikw8sqzgwsngsdapcs6a2fq-woeusb-ng-0.2.12/bin/..woeusbgui-wrapped-wrapped", line 39, in <module>
    WoeUSB.utils.update_policy_to_allow_for_running_gui_as_root(__file__)
  File "/nix/store/c8mzyq1vwikw8sqzgwsngsdapcs6a2fq-woeusb-ng-0.2.12/lib/python3.12/site-packages/WoeUSB/utils.py", line 385, in update_policy_to_allow_for_running_gui_as_root
    with open("/nix/store/c8mzyq1vwikw8sqzgwsngsdapcs6a2fq-woeusb-ng-0.2.12/share/polkit-1/actions/com.github.woeusb.woeusb-ng.policy", "w") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/nix/store/c8mzyq1vwikw8sqzgwsngsdapcs6a2fq-woeusb-ng-0.2.12/share/polkit-1/actions/com.github.woeusb.woeusb-ng.policy'
```

**Comment by bcye** [comment]
It must be started with sudo directly. If started without sudo it will prompt for a password, but fail regardless. Running `sudo woeusbgui` fixed the issue for me.

**Comment by boustanihani** [comment]
Thank you for your feedback.

I am closing this because woeusbgui seems dead (last commit two years ago).
