### ISSUE TITLE
Build failure: drawio

### ISSUE THREAD

**Issue by MoritzR** [NixOS/nixpkgs#292092]
### Steps To Reproduce

1.  build `nix build nixpkgs#drawio`

### Build log

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/x5qb35xqx70i24aqby48f1wxg1kk8hl4-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
yarn config v1.22.19
success Set "yarn-offline-mirror" to "/nix/store/7q437pn40zhs44sn1zxg99hbmz55ajs5-offline".
✨  Done in 0.05s.
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
warning Ignored scripts due to flag.
✨  Done in 10.73s.
patching script interpreter paths in node_modules/
node_modules/dmg-license/bin/dmg-license.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7q>
node_modules/node-addon-api/tools/conversion.js: interpreter directive changed from "#! /usr/bin/env node" to "/nix/store>
node_modules/rimraf/bin.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn4lhz8hz>
node_modules/extract-zip/cli.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn4l>
node_modules/jake/bin/bash_completion.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/mg966h6cir056vn>
node_modules/jake/bin/cli.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn4lhz8>
node_modules/typescript/bin/tsserver: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymi>
node_modules/typescript/bin/tsc: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn4l>
node_modules/is-ci/bin.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn4lhz8hzd>
node_modules/js-yaml/bin/js-yaml.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymig>
node_modules/ejs/bin/cli.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn4lhz8h>
node_modules/semver/bin/semver.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn>
node_modules/electron-builder/install-app-deps.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/stor>
node_modules/electron-builder/cli.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymi>
node_modules/json5/lib/cli.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn4lhz>
node_modules/mime/cli.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn4lhz8hzdk>
node_modules/config-file-ts/node_modules/glob/dist/esm/bin.mjs: interpreter directive changed from "#!/usr/bin/env node" >
node_modules/electron/cli.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn4lhz8>
node_modules/which/bin/node-which: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn>
node_modules/mkdirp/bin/cmd.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzvymigkn4lh>
node_modules/@electron/get/node_modules/semver/bin/semver.js: interpreter directive changed from "#!/usr/bin/env node" to>
node_modules/@electron/asar/bin/asar.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwzv>
node_modules/@electron/osx-sign/bin/electron-osx-flat.js: interpreter directive changed from "#!/usr/bin/env node" to "/n>
node_modules/@electron/osx-sign/bin/electron-osx-sign.js: interpreter directive changed from "#!/usr/bin/env node" to "/n>
node_modules/@electron/fuses/dist/bin.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/xr7qgwz>
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
yarn run v1.22.19
$ /private/tmp/nix-build-drawio-23.1.5.drv-0/source/node_modules/.bin/electron-builder --dir --config electron-builder-li>
  • electron-builder  version=24.9.1 os=23.3.0
  • loaded configuration  file=/private/tmp/nix-build-drawio-23.1.5.drv-0/source/electron-builder-linux-mac.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=arm64 electron=28.0.0 appOutDir=dist/mac-arm64
  • copying Electron  source=/private/tmp/nix-build-drawio-23.1.5.drv-0/source/Electron.app destination=/private/tmp/nix->
Flipping fuses for:  /private/tmp/nix-build-drawio-23.1.5.drv-0/source/dist/mac-arm64/draw.io.app
  ⨯ Cannot read properties of null (reading 'toString')  failedTask=build stackTrace=TypeError: Cannot read properties of>
    at flipFuses (/private/tmp/nix-build-drawio-23.1.5.drv-0/source/node_modules/@electron/fuses/src/index.ts:181:35)
    at addElectronFuses (/private/tmp/nix-build-drawio-23.1.5.drv-0/source/build/fuses.js:31:5)
    at module.exports (/private/tmp/nix-build-drawio-23.1.5.drv-0/source/build/fuses.js:50:5)
    at Packager.afterPack (/private/tmp/nix-build-drawio-23.1.5.drv-0/source/node_modules/app-builder-lib/src/packager.ts>
    at MacPackager.doPack (/private/tmp/nix-build-drawio-23.1.5.drv-0/source/node_modules/app-builder-lib/src/platformPac>
    at MacPackager.pack (/private/tmp/nix-build-drawio-23.1.5.drv-0/source/node_modules/app-builder-lib/src/macPackager.t>
    at Packager.doBuild (/private/tmp/nix-build-drawio-23.1.5.drv-0/source/node_modules/app-builder-lib/src/packager.ts:4>
    at executeFinally (/private/tmp/nix-build-drawio-23.1.5.drv-0/source/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/private/tmp/nix-build-drawio-23.1.5.drv-0/source/node_modules/app-builder-lib/src/packager.ts:37>
    at Packager.build (/private/tmp/nix-build-drawio-23.1.5.drv-0/source/node_modules/app-builder-lib/src/packager.ts:337>
    at executeFinally (/private/tmp/nix-build-drawio-23.1.5.drv-0/source/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional context

drawio version 22.1.18 built successfully for me. This failure happens on drawio version 22.0.3.

### Notify maintainers
@alyssais @DarkOnion0 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.3.0, macOS 14.3.1`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MoritzR** [comment]
> Hello, could you please check if the issue is still occurring in the latest version (see #295384 or just run `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 295384`)?

Unfortunately, this fails with the same error:
```
error: builder for '/nix/store/f1rx6232rkhwq29arnakfk2gypbv85x0-drawio-24.0.4.drv' failed with exit code 1;
       last 10 log lines:
       >     at Packager.afterPack (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/packager.ts:546:7)
       >     at MacPackager.doPack (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/platformPackager.ts:312:5)
       >     at MacPackager.pack (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/macPackager.ts:198:9)
       >     at Packager.doBuild (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/packager.ts:445:9)
       >     at executeFinally (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/builder-util/src/promise.ts:12:14)
       >     at Packager._build (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/packager.ts:379:31)
       >     at Packager.build (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/packager.ts:340:12)
       >     at executeFinally (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/builder-util/src/promise.ts:12:14)
       > error Command failed with exit code 1.
       > info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       For full logs, run 'nix log /nix/store/f1rx6232rkhwq29arnakfk2gypbv85x0-drawio-24.0.4.drv'.
error: 1 dependencies of derivation '/nix/store/dzzhfk07qdwk4sp17jdigzadbmdccd82-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/295384

6 packages marked as broken and skipped:
pandoc-drawio-filter pandoc-drawio-filter.dist python311Packages.mkdocs-drawio-exporter python311Packages.mkdocs-drawio-exporter.dist python312Packages.mkdocs-drawio-exporter python312Packages.mkdocs-drawio-exporter.dist

1 package failed to build:
drawio
```
Logs:
```
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
yarn run v1.22.22
$ /private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/.bin/electron-builder --dir --config electron-builder-linux-mac.json -c.electronDist=. -c.electronVersion>
  • electron-builder  version=24.13.3 os=23.4.0
  • loaded configuration  file=/private/tmp/nix-build-drawio-24.0.4.drv-0/source/electron-builder-linux-mac.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=arm64 electron=28.0.0 appOutDir=dist/mac-arm64
  • copying Electron  source=/private/tmp/nix-build-drawio-24.0.4.drv-0/source/Electron.app destination=/private/tmp/nix-build-drawio-24.0.4.drv-0/source/dist/mac-arm64/E>
Flipping fuses for:  /private/tmp/nix-build-drawio-24.0.4.drv-0/source/dist/mac-arm64/draw.io.app
  ⨯ Cannot read properties of null (reading 'toString')  failedTask=build stackTrace=TypeError: Cannot read properties of null (reading 'toString')
    at flipFuses (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/@electron/fuses/src/index.ts:181:35)
    at addElectronFuses (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/build/fuses.js:31:5)
    at module.exports (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/build/fuses.js:50:5)
    at Packager.afterPack (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/packager.ts:546:7)
    at MacPackager.doPack (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/platformPackager.ts:312:5)
    at MacPackager.pack (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/macPackager.ts:198:9)
    at Packager.doBuild (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/packager.ts:445:9)
    at executeFinally (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/packager.ts:379:31)
    at Packager.build (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/app-builder-lib/src/packager.ts:340:12)
    at executeFinally (/private/tmp/nix-build-drawio-24.0.4.drv-0/source/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
```

Thanks for the tip with `nixpkgs-review` 👍
