### ISSUE TITLE
Build Failure: `biopython`

### ISSUE THREAD

**Issue by AmeerTaweel** [NixOS/nixpkgs#292138]
### Steps To Reproduce

Minimal flake to reproduce the issue:

`flake.nix`:

```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

  outputs = {
    self,
    nixpkgs,
  }: let
    forAllSystems = nixpkgs.lib.genAttrs [
      "aarch64-linux"
      "aarch64-darwin"
      "x86_64-darwin"
      "x86_64-linux"
    ];
    mkPkgs = system:
      import nixpkgs {
        inherit system;
        overlays = [
          # Uncomment this overlay and the issue will be fixed
          # (final: prev: {
          #   python3 = prev.python3.override {
          #     packageOverrides = pyfinal: pyprev: {
          #       biopython = pyprev.biopython.overrideAttrs (_: {
          #         doInstallCheck = false;
          #       });
          #     };
          #   };
          # })
        ];
      };
  in {
    # Development environment
    # Acessible through `nix develop`
    devShells = forAllSystems (system: let
      pkgs = mkPkgs system;
    in {
      default = pkgs.mkShell {
        nativeBuildInputs = [(pkgs.python3.withPackages (ps: [ps.biopython]))];
      };
    });
  };
}
```

`flake.lock`:

```nix
{
  "nodes": {
    "nixpkgs": {
      "locked": {
        "lastModified": 1708976803,
        "narHash": "sha256-yvRygcySjjSvj5JTaCdo7lPqJ/2mBV2XQ94Oaq/14qw=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "548a86b335d7ecd8b57ec617781f5e652ab0c38e",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixpkgs-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "nixpkgs": "nixpkgs"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

### Build log

[fail.log](https://github.com/NixOS/nixpkgs/files/14438672/fail.log)

### Additional context

Disabling install checks using `doInstallCheck = false` fixes the issue. If you uncomment the commented overlay in the minimal flake I provided, the build will succeed and the package will work properly.

### Notify maintainers

@luispedro 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.74, NixOS, 24.05 (Uakari), 24.05.20240125.ae5c332`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/9s5qs4hni9fj88x79iw6im7amv7ghb76-source`
```

**Comment by idlip** [comment]
+1 Same issue with same log.

@luispedro (tagging, as you are in maintainers list)

**Comment by micked** [comment]
Looks like a bug upstream: https://github.com/biopython/biopython/issues/4640

**Comment by peterjc** [comment]
As per the Biopython issue linked, Debian sid is failing in the same way. Specifically, converting two annotated sequence files (one in EMBL format, one in Genbank format) into SeqXML format and then attempting to read this XML file back fails. Narrower tests from that issue:

```
$ python -c "from Bio import SeqIO; SeqIO.convert('Tests/EMBL/SC10H5.embl', 'embl', 'check_me.xml', 'seqxml')"
$ md5sum check_me.xml
12e128f5a5449a076d790be5c624d9e4  check_me.xml
```

File expected is here (with .txt added to the filename): [check_me.xml.txt](https://github.com/NixOS/nixpkgs/files/14494416/check_me.xml.txt)

This seems to fail (but shouldn't):

```
$ python -c "from Bio import SeqIO; print(SeqIO.read('check_me.xml', 'seqxml').id)"
AL031232
```

This appears to be something breaking via the XML SAX expat parser. Can you see anything relevant which has changed on your platform to help narrow this down?

**Comment by emollier** [comment]
Hi, I tracked this issue down to a libexpat.so.1 upgrade from 2.5.0 to 2.6.1 from Debian testing to sid.  [Debian CI] suggests this could also cause regression in Python tests.  Is this consistent with what you observe on Nix?

If so, I strongly believe the root cause of the Biopython issue is ingrained in a bad interaction between the newer expat version and the Python interpreter, notably:
```
2510s ======================================================================
2510s FAIL: test_simple_xml (test.test_xml_etree.XMLPullParserTest.test_simple_xml) (chunk_size=1)
2510s ----------------------------------------------------------------------
2510s Traceback (most recent call last):
2510s   File "/usr/lib/python3.11/test/test_xml_etree.py", line 1415, in test_simple_xml
2511s     self.assert_event_tags(parser, [('end', 'element')])
2511s   File "/usr/lib/python3.11/test/test_xml_etree.py", line 1400, in assert_event_tags
2511s     self.assertEqual([(action, elem.tag) for action, elem in events],
2511s AssertionError: Lists differ: [] != [('end', 'element')]
2511s 
2511s Second list contains 1 additional elements.
2511s First extra element 0:
2511s ('end', 'element')
2511s 
2511s - []
2511s + [('end', 'element')]
2511s 
2511s ======================================================================
2511s FAIL: test_simple_xml (test.test_xml_etree.XMLPullParserTest.test_simple_xml) (chunk_size=5)
2511s ----------------------------------------------------------------------
2511s Traceback (most recent call last):
2511s   File "/usr/lib/python3.11/test/test_xml_etree.py", line 1418, in test_simple_xml
2511s     self.assert_event_tags(parser, [
2511s   File "/usr/lib/python3.11/test/test_xml_etree.py", line 1400, in assert_event_tags
2511s     self.assertEqual([(action, elem.tag) for action, elem in events],
2511s AssertionError: Lists differ: [('end', 'element')] != [('end', 'element'), ('end', 'empty-element')]
2511s 
2511s Second list contains 1 additional elements.
2511s First extra element 1:
2511s ('end', 'empty-element')
2511s 
2511s - [('end', 'element')]
2511s + [('end', 'element'), ('end', 'empty-element')]
```

[Debian CI]: https://ci.debian.net/packages/p/python3.11/testing/amd64/43739090/

In hope this helps,
Étienne.

**Comment by idlip** [comment]
I can confirm that latest 1.84-dev works.

We have to wait for update to be tagged.

Until then, you can modify on `biopython.nix` to use

```nix
  src = fetchFromGitHub {
    owner = "biopython";
    repo = "biopython";
    rev = "0bf30315fafcef2a499f40d9d42b5e5b06fc9336";
    hash = "sha256-i57c8CQEsUin0u9zsFKfxJ6D4w+lHLUGUOV6r0ENKtQ=";
  };
```

**Comment by peterjc** [comment]
We have a few NumPy 2.0 test incompatibilities to fix (due to their scalar repr changes), and then we want to release Biopython 1.84 which would include the libexpat fix (moving a close earlier):

https://github.com/biopython/biopython/commit/3f9bda7ef44f533dadbaa0de29ac21929bc0b2f1
