### ISSUE TITLE
Update request: ejabberd 23.10 → 24.02

### ISSUE THREAD

**Issue by jpds** [NixOS/nixpkgs#292339]
- Package name: ejabberd
- Latest released version: 24.02
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

I tried updating this myself, but something is erroring with `mix`:

```patch
diff --git a/pkgs/servers/xmpp/ejabberd/default.nix b/pkgs/servers/xmpp/ejabberd/default.nix
index 9e0601fbd093..b712e3f0b68d 100644
--- a/pkgs/servers/xmpp/ejabberd/default.nix
+++ b/pkgs/servers/xmpp/ejabberd/default.nix
@@ -2,6 +2,9 @@
 , erlang, openssl, expat, libyaml, bash, gnused, gnugrep, coreutils, util-linux, procps, gd
 , flock, autoreconfHook
 , gawk
+, hex
+, elixir
+, rebar3
 , nixosTests
 , withMysql ? false
 , withPgsql ? false
@@ -17,7 +20,7 @@ let
   ctlpath = lib.makeBinPath [ bash gnused gnugrep gawk coreutils util-linux procps ];
 in stdenv.mkDerivation rec {
   pname = "ejabberd";
-  version = "23.10";
+  version = "24.02";

   nativeBuildInputs = [ makeWrapper autoreconfHook ];

@@ -29,7 +32,7 @@ in stdenv.mkDerivation rec {

   src = fetchurl {
     url = "https://www.process-one.net/downloads/downloads-action.php?file=/${version}/ejabberd-${version}.tar.gz";
-    hash = "sha256-DW5/DYLZHNqJ4lddmag1B0E9ov/eObIVGASUeioPolg=";
+    hash = "sha256-ttSNO/K+82jpMh41Q2OByG14REuQQmScbEqrAIk5XAc=";
     # remember to update the deps FOD hash & its pinned ejabberd-po commit
   };

@@ -48,13 +51,13 @@ in stdenv.mkDerivation rec {
       substituteInPlace rebar.config \
         --replace \
           '{git, "https://github.com/processone/ejabberd-po", {branch, "main"}}' \
-          '{git, "https://github.com/processone/ejabberd-po", {tag, "26d6463386588d39f07027dabff3cb8dd938bf6b"}}'
+          '{git, "https://github.com/processone/ejabberd-po", {tag, "fd0e059de4c0772de37339a0a95f9a474d107b59"}}'
     '';

     configureFlags = [ "--enable-all" "--with-sqlite3=${sqlite.dev}" ];

     nativeBuildInputs = [
-      git erlang openssl expat libyaml sqlite pam zlib autoreconfHook
+      git erlang openssl expat libyaml sqlite pam zlib autoreconfHook rebar3 elixir hex
     ];

     GIT_SSL_CAINFO = "${cacert}/etc/ssl/certs/ca-bundle.crt";
@@ -83,7 +86,7 @@ in stdenv.mkDerivation rec {

     outputHashAlgo = "sha256";
     outputHashMode = "recursive";
-    outputHash = "sha256-HrLu3wTF+cUxpGX0yK3nbB57SRM2ND3Crlxs5/8FIwI=";
+    outputHash = "";
   };

   configureFlags = [
```

```
$ nix log /nix/store/6rs8v1q55mvkfrc8fgvfw0j0rlb5qiwi-ejabberd-deps-24.02.drv
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/6rs8v1q55mvkfrc8fgvfw0j0rlb5qiwi-ejabberd-deps-24.02.drv^*'
Running phase: unpackPhase
unpacking source archive /nix/store/0jyy5r7zh5w3lb8vwpv83795zbyy2rj8-ejabberd-24.02.tar.gz
source root is ejabberd-24.02
setting SOURCE_DATE_EPOCH to timestamp 1709026375 of file ejabberd-24.02/vars.config.in
Running phase: patchPhase
substituteStream(): WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'rebar.config')
Running phase: autoreconfPhase
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /nix/store/wxsibxw4kdzmnfxh4zgrzsr8dp4q2v7k-autoconf-2.72/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: configure.ac: not using Automake
autoreconf: './install-sh' is updated
autoreconf: Leaving directory '.'
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
patching script interpreter paths in ./configure
./configure: interpreter directive changed from "#! /bin/sh" to "/nix/store/087167dfxal194pm54cmcbbxsfy3cjgn-bash-5.2p26/bin/sh"
configure flags: --prefix=/nix/store/pjrxa9hp072hcqc6qw90g6k4db72b57q-ejabberd-deps-24.02 --enable-all --with-sqlite3=/nix/store/gasjbdsd06j8pmb07mk3azpl4aj8sg>
checking whether make sets $(MAKE)... yes
checking for gawk... gawk
checking for a BSD-compatible install... /nix/store/x1xcjw5628crkk1pwr12y7nwbzkc3969-coreutils-9.4/bin/install -c
checking for a race-free mkdir -p... /nix/store/x1xcjw5628crkk1pwr12y7nwbzkc3969-coreutils-9.4/bin/mkdir -p
checking for a sed that does not truncate output... /nix/store/y1y3rml47qnh0giqd32mj07qxxqy13qg-gnused-4.9/bin/sed
checking for erl... /nix/store/xang45qlfdvpcfmc4l84dz981blnk1dl-erlang-25.3.2.9/bin/erl
checking for erlc... /nix/store/xang45qlfdvpcfmc4l84dz981blnk1dl-erlang-25.3.2.9/bin/erlc
checking for epmd... /nix/store/xang45qlfdvpcfmc4l84dz981blnk1dl-erlang-25.3.2.9/bin/epmd
checking for rebar... no
checking for rebar3... /nix/store/mpxg7y3sl8cn0kc8hxfky9r0x02klvrx-rebar3-3.22.1/bin/rebar3
checking for elixir... /nix/store/4yy7bh6f9bq3pcz1yv9lnxcvnxsqs9cy-elixir-1.15.7/bin/elixir
checking for iex... /nix/store/4yy7bh6f9bq3pcz1yv9lnxcvnxsqs9cy-elixir-1.15.7/bin/iex
checking for mix... /nix/store/4yy7bh6f9bq3pcz1yv9lnxcvnxsqs9cy-elixir-1.15.7/bin/mix
checking for erl... (cached) /nix/store/xang45qlfdvpcfmc4l84dz981blnk1dl-erlang-25.3.2.9/bin/erl
checking for erlc... (cached) /nix/store/xang45qlfdvpcfmc4l84dz981blnk1dl-erlang-25.3.2.9/bin/erlc
checking for Erlang/OTP root directory... /nix/store/xang45qlfdvpcfmc4l84dz981blnk1dl-erlang-25.3.2.9/lib/erlang
checking for escript... /nix/store/xang45qlfdvpcfmc4l84dz981blnk1dl-erlang-25.3.2.9/lib/erlang/bin/escript
checking for make... make
checking Erlang/OTP version... ok
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for SQLite3 library >= 3.6.19... yes
grep: warning: stray \ before "
build tool to use (change using --with-rebar): /nix/store/4yy7bh6f9bq3pcz1yv9lnxcvnxsqs9cy-elixir-1.15.7/bin/mix
configure: creating ./config.status
config.status: creating Makefile
config.status: creating vars.config
Running phase: buildPhase
build flags: SHELL=/nix/store/087167dfxal194pm54cmcbbxsfy3cjgn-bash-5.2p26/bin/bash deps
rm -rf _build/dev/lib/.got
rm -rf _build/dev/lib/.built
/nix/store/x1xcjw5628crkk1pwr12y7nwbzkc3969-coreutils-9.4/bin/mkdir -p _build/dev/lib
/nix/store/4yy7bh6f9bq3pcz1yv9lnxcvnxsqs9cy-elixir-1.15.7/bin/mix deps.get && :> _build/dev/lib/.got
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UT>
** (File.Error) could not make directory (with -p) "/homeless-shelter/.mix/archives/hex-2.0.6": no such file or directory
    (elixir 1.15.7) lib/file.ex:319: File.mkdir_p!/1
    (mix 1.15.7) lib/mix/tasks/archive.install.ex:118: Mix.Tasks.Archive.Install.install/3
    (mix 1.15.7) lib/mix/local/installer.ex:107: Mix.Local.Installer.local_install/3
    (mix 1.15.7) lib/mix/dep/loader.ex:188: Mix.Dep.Loader.with_scm_and_app/5
    (mix 1.15.7) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/4
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (mix 1.15.7) lib/mix/dep/loader.ex:364: Mix.Dep.Loader.mix_children/3
    (mix 1.15.7) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/1
make: *** [Makefile:211: _build/dev/lib/.got] Error 1
```

Relevant upstream `rebar3` PR: https://github.com/processone/ejabberd/pull/4143

**Notify maintainers**

@svanderburg @abbradar 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jpds** [comment]
Dup of #292110
