### ISSUE TITLE
sdkmanager package bug: ANDROID_HOME environment variable is not set correctly

### ISSUE THREAD

**Issue by jmarmstrong1207** [NixOS/nixpkgs#292695]
### Describe the bug
When running sdkmanager, this error occurs: `FileNotFoundError: ANDROID_HOME "/opt/android-sdk" does not exist!`

I was able to fix it by changing the ANDROID_HOME variable to another dir such as ~/androidhome but not sure if it's a complete fix

### Steps To Reproduce
1. run `nix-shell -p sdkmanager`
2. run `sdkmanager`
3. Error occurs

### Expected behavior
sdkmanager to work as normal.

### Error log
```console
Traceback (most recent call last):
  File "/nix/store/dymwfan93vk05kjn2lr90gfr22q7kik6-python3.11-sdkmanager-0.6.5/bin/..sdkmanager-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/dymwfan93vk05kjn2lr90gfr22q7kik6-python3.11-sdkmanager-0.6.5/lib/python3.11/site-packages/sdkmanager.py", line 1193, in main
    method(args.packages)
  File "/nix/store/dymwfan93vk05kjn2lr90gfr22q7kik6-python3.11-sdkmanager-0.6.5/lib/python3.11/site-packages/sdkmanager.py", line 1000, in install
    android_home = get_android_home()
                   ^^^^^^^^^^^^^^^^^^
  File "/nix/store/dymwfan93vk05kjn2lr90gfr22q7kik6-python3.11-sdkmanager-0.6.5/lib/python3.11/site-packages/sdkmanager.py", line 543, in get_android_home
    raise FileNotFoundError('ANDROID_HOME "%s" does not exist!' % android_home)
FileNotFoundError: ANDROID_HOME "/opt/android-sdk" does not exist!

```

### Notify maintainers
@linsui

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.79, NixOS, 23.11 (Tapir), 23.11.20240229.068d4db`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11, nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by linsui** [comment]
This is expected. You need to set ANDROID_HOME to tell it where you want to install sdk.
