### ISSUE TITLE
Build failure: python312Packages.pynvml 11.5.0

### ISSUE THREAD

**Issue by sarahec** [NixOS/nixpkgs#293168]
### Steps To Reproduce

1. Build python312Packages.pynvml

### Build log

```console
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/6jpp5rzkq6dyl6jbxalfpxawv4magrqs-python3.12-pynvml-11.5.0.drv^*'
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/l0cgnizcxf4k6b5r3blvw4fjywmal9mg-pynvml-11.5.0.tar.gz
source root is pynvml-11.5.0
setting SOURCE_DATE_EPOCH to timestamp 1676432198 of file pynvml-11.5.0/pynvml/_version.py
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
applying patch /nix/store/r9ddrnj2x0rfgic1myrvfxcp845nw6f1-0001-locate-libnvidia-ml.so.1-on-NixOS.patch
patching file pynvml/nvml.py
Hunk #1 succeeded at 1795 (offset 320 lines).
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing setuptoolsBuildPhase
/build/pynvml-11.5.0/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "/build/pynvml-11.5.0/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 20, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/pynvml-11.5.0/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/build/pynvml-11.5.0/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/pynvml-11.5.0/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
/nix/store/3qnm3nwjajgqa771dmi2dnwxrw0kzq5m-stdenv-linux/setup: line 1578: pop_var_context: head of shell_variables not a function context
```

### Additional context

python311Packages.pynvml builds fine by itself.

This package is central to anyone using CUDA 12 (i.e. pretty much any ML projects).

### Notify maintainers

@bcdarwin 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.18, NixOS, 24.05 (Uakari), 24.05.20240229.1536926`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - channels(sec): `""`
 - nixpkgs: `/nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source
 ````

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bcdarwin** [comment]
I'll try to find time to look into this at some point relatively soon, but note that machine learning using 3.12 is probably not generally feasible in Nixpkgs yet (e.g. not all `torch` dependencies build).

**Comment by sarahec** [comment]
No worries. I was reporting it as it shows up in nixos-review

**Comment by Wolfsauge** [comment]
> I'll try to find time to look into this at some point relatively soon, but note that machine learning using 3.12 is probably not generally feasible in Nixpkgs yet (e.g. not all `torch` dependencies build).

That might be true. I am a user who cannot build nvitop on a recent CUDA 12.4 system. There aren't any other dependencies, that's a tool like nvtop or nvidia-smi, to see the load of a GPU. Thanks for investing the time and effort to make it work. CUDA 12.4 is being rolled out to cloud providers.

**Comment by sarahec** [comment]
@bcdarwin this came up again as part of the Zero Hydra Failures campaign. See #309533

**Comment by sarahec** [comment]
Fixed some time AGO.
