### ISSUE TITLE
roon-server cannot be connected to, missing binaries

### ISSUE THREAD

**Issue by Ramblurr** [NixOS/nixpkgs#293282]
### Describe the bug

A fresh roon-server cannot be connected to due to some missing binaries:

```
...
03/04 16:34:06 Trace: [remoting/remotingserverv2] SENT NONFINAL DistributedBroker.UpdatesChangedResponse={ IsSupported=True WasJustUpdated=False Status='Installing' HasChangeLog=False AvailableVersion={ MachineValue=200001368 DisplayValue='2.0 (build 1368) production' Branch='production' } CurrentVersion={ MachineValue=200001272 DisplayValue='2.0 (build 1272) production' Branch='production' } }
03/04 16:34:06 Error: [appupdater] While installing update: System.ArgumentException: Executable 'tar' doesn't exist
   at Base.ChildProcessBase.Start()
   at Base.ChildProcess.Start()
   at Sooloos.Updater.<>c__DisplayClass42_0.<InstallUpdate>b__0(Object <p0>)
```

### Steps To Reproduce
1. Start a fresh roon-server using nixos modules
2. Open roon app and try to connect to it
3. see the error

### Expected behavior

I should be able to connect to the fresh roon server.

### Screenshots

![signal-2024-03-04-163842](https://github.com/NixOS/nixpkgs/assets/14830/b931d693-7a21-4483-b09b-7f7617c131b4)

### Additional context
n/a

### Notify maintainers

@lovesegfault @Steell

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.13, NixOS, 24.05 (Uakari), 24.05.20240224.73de017`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/gzv0nsm8d5js3wzq2mr1sv9lfp1iyail-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ramblurr** [comment]
Ok.. so I figured this would be an easy one to submit a PR for.. 


I started out by adding

```
  systemd.services.roon-server = {
...snip...
    path = with pkgs; [
      gnutar
      lbzip2
    ];
...snip...
```

(I found out `lbzip2` was needed after just adding `gnutar`).

However now it won't start because of another error:

```
03/04 16:51:25 Error: [appupdater] While installing update: System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/tmp/7c3b03d9-6907-4f59-83b8-3d43ff8f6c1b/RoonServer/start.sh' with working directory '/nix/store/2fv65fcvdwj486d2fd9yfmxg0yysvgny-roon-server-2.0-1272/Appliance'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Base.DotNetChildProcess.StartImp(String filename)
   at Base.ChildProcessBase.Start()
   at Base.ChildProcess.Start()
   at Sooloos.Updater.<>c__DisplayClass42_0.<InstallUpdate>b__0(Object <p0>)
```

That tmp file doesn't exist, but that could be because it was cleaned up when the process exited. The working directory definitely exists.

**Comment by Ramblurr** [comment]
Ok yea that's what I was thinking. Closing sorry for the noise.
