### ISSUE TITLE
GitLab cannot upload group/project avatar

### ISSUE THREAD

**Issue by bengcooper** [NixOS/nixpkgs#29377]
## Issue description

GitLab returns a 500 error when uploading a group/avatar image.

The log reveals that GitLab is attempting to write to `share/gitlab/tmp/` in the store:

    Errno::EROFS (Read-only file system @ dir_s_mkdir - /nix/store/h3d3ws1fipkphczdmzhd7nxk1638y1vn-gitlab-9.5.2/share/gitlab/tmp/1505401963-2016-0001-6237):
      app/services/groups/update_service.rb:17:in `execute'
      app/controllers/groups_controller.rb:92:in `update'
      lib/gitlab/i18n.rb:46:in `with_locale'
      lib/gitlab/i18n.rb:52:in `with_user_locale'
      app/controllers/application_controller.rb:326:in `set_locale'
      lib/gitlab/middleware/multipart.rb:98:in `block in call'
      lib/gitlab/middleware/multipart.rb:53:in `with_open_files'
      lib/gitlab/middleware/multipart.rb:97:in `call'
      lib/gitlab/request_profiler/middleware.rb:14:in `call'
      lib/gitlab/middleware/go.rb:16:in `call'
      lib/gitlab/etag_caching/middleware.rb:11:in `call'
      lib/gitlab/request_context.rb:18:in `call'
      lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'

Is it possible to get GitLab to respect the `GITLAB_UPLOADS_PATH` variable in this case?

### Steps to reproduce

1. Create group
2. Go to group settings
3. Attempt to upload an image as the group avatar 

## Technical details

* System: 18.03pre115166.1b1fc65505
* Nix version: 1.11.14
* Nixpkgs version: 18.03pre115166.1b1fc65505
* Sandboxing enabled: false

**Comment by bengcooper** [comment]
This is now fixed by 60b0db0e08197b9fd773a417ed96000841a905a5
