### ISSUE TITLE
Arion operations error with "unexpected keyword argument 'ssl_version'"

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#294381]
### Describe the bug
`arion up` and other operations fail with
```
Traceback (most recent call last):
  File "/nix/store/zs39wd2200l8wn0nih3jg1z2nz1lsd2z-docker-compose-1.29.2/bin/.docker-compose-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/zs39wd2200l8wn0nih3jg1z2nz1lsd2z-docker-compose-1.29.2/lib/python3.11/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/nix/store/zs39wd2200l8wn0nih3jg1z2nz1lsd2z-docker-compose-1.29.2/lib/python3.11/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zs39wd2200l8wn0nih3jg1z2nz1lsd2z-docker-compose-1.29.2/lib/python3.11/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
           ^^^^^^^^^^^^
  File "/nix/store/zs39wd2200l8wn0nih3jg1z2nz1lsd2z-docker-compose-1.29.2/lib/python3.11/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
             ^^^^^^^^^^^
  File "/nix/store/zs39wd2200l8wn0nih3jg1z2nz1lsd2z-docker-compose-1.29.2/lib/python3.11/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
             ^^^^^^^^^^^^^^
  File "/nix/store/zs39wd2200l8wn0nih3jg1z2nz1lsd2z-docker-compose-1.29.2/lib/python3.11/site-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
```
See upstream bug report https://github.com/hercules-ci/arion/issues/230

### Steps To Reproduce
1. Install arion
2. Run `arion up` on a basic `arion-compose.nix`, e.g.
```
{ pkgs, ... }:
{
  project.name = "test";

  services.mariadb = {
    service.image = "mariadb:latest";
    service.hostname = "mariadb";
    service.restart = "always";
    service.volumes = ["/mariadbfiles:/var/lib/mysql"];
    service.env_file = [".mariadb.env"];
    service.networks = ["db_connect"];
  };
}
```

### Expected behavior
Arion is operations complete succesfully

### Notify maintainers
@roberth - you seem to think this is a docker compose issue, should those maintainers be pinged?

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.19, NixOS, 24.05 (Uakari), 24.05.20240306.9df3e30`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.1`
 - channels(lunik): `"nixos"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/gig8j85kj7ybjy3ksn6k3aich8j2k59y-source`
 ```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by KiaraGrouwstra** [comment]
weird, the fix to #306398 semed not to fix this one for me yet
