### ISSUE TITLE
slither is broken due to eth-utils version 4

### ISSUE THREAD

**Issue by thedavidmeister** [NixOS/nixpkgs#294418]
### Describe the bug

Slither requires eth-utils 2 or 3 and only v4 is provided in nixpkgs currently.

### Steps To Reproduce

Can see failing CI here https://github.com/rainlanguage/rain.interpreter/actions/runs/8211912787/job/22461475436?pr=179#step:8:31

### Expected behavior

Slither should build and run.

### Notify maintainers

@arcz 
@fabaff 
@hellwolf

**Comment by hellwolf** [comment]
Indeed. I just tried with the latest nixpkgs:

```
nix-shell$ slither --version
Traceback (most recent call last):
  File "/nix/store/yladq6jv21yxppyg4vp7r6lbd8rhp1rp-python3.11-slither-analyzer-0.10.1/bin/.slither-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/yladq6jv21yxppyg4vp7r6lbd8rhp1rp-python3.11-slither-analyzer-0.10.1/lib/python3.11/site-packages/slither/__main__.py", line 746, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/nix/store/yladq6jv21yxppyg4vp7r6lbd8rhp1rp-python3.11-slither-analyzer-0.10.1/lib/python3.11/site-packages/slither/__main__.py", line 760, in main_impl
    args = parse_args(all_detector_classes, all_printer_classes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/yladq6jv21yxppyg4vp7r6lbd8rhp1rp-python3.11-slither-analyzer-0.10.1/lib/python3.11/site-packages/slither/__main__.py", line 301, in parse_args
    version=require("slither-analyzer")[0].version,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bvqadys5w6dallgim0y8y98h05b7kfn7-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bvqadys5w6dallgim0y8y98h05b7kfn7-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bvqadys5w6dallgim0y8y98h05b7kfn7-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 4.0.0 (/nix/store/lkdxb340q100lzg9adkf33vy84knmjlf-python3.11-eth-utils-4.0.0/lib/python3.11/site-packages), Requirement.parse('eth-utils<3,>=2.0.0'), {'eth-keyfile', 'eth-keys', 'eth-rlp', 'rlp'})
```

I'm gonna also CC @dotlambda too. According to the log, it was introduced 2 weeks ago.

We should also update these:

- eth-utils
- eth-keyfile
- eth-rlp
- rlp

Also, I think slither packaging should have a basic sanity check too, so that we would have known during build time.

**Comment by dotlambda** [comment]
Where is the code that restricts the eth-utils version? It's not https://github.com/crytic/slither/blob/0.10.1/setup.py#L23.

**Comment by hellwolf** [comment]
> Where is the code that restricts the eth-utils version? It's not https://github.com/crytic/slither/blob/0.10.1/setup.py#L23.

My comment was not very clear. It's not slither itself, it's their dependencies that I mentioned above.

**Comment by dotlambda** [comment]
Please point me to the code.

**Comment by hellwolf** [comment]
@dotlambda 

I have made the fixes: https://github.com/NixOS/nixpkgs/pull/298687
