### ISSUE TITLE
install_bootloader() in systemd-boot-builder.py cannot detect previous systemd-boot version

### ISSUE THREAD

**Issue by turtton** [NixOS/nixpkgs#296563]
### Describe the bug
If multiple efi files exist in`/EFI/systemd/`, the install_bootloader function will output the following error
```sql
Traceback (most recent call last):
  File "/nix/store/0ky2fq2qv0qbgnaqfmc3mc0pb5vcpdnn-systemd-boot/bin/systemd-boot-builder", line 394, in <module>
    main()
  File "/nix/store/0ky2fq2qv0qbgnaqfmc3mc0pb5vcpdnn-systemd-boot/bin/systemd-boot-builder", line 377, in main
    install_bootloader(args)
  File "/nix/store/0ky2fq2qv0qbgnaqfmc3mc0pb5vcpdnn-systemd-boot/bin/systemd-boot-builder", line 305, in install_bootloader
    raise Exception("could not find any previously installed systemd-boot")
Exception: could not find any previously installed systemd-boot
```

### Steps To Reproduce
1. Add an efi file with a name higher in display order than systemd-bootx64.efi with the `bootctl status` command like
  ```nix
  boot.loader.systemd-boot.extraFiles = {
    # I know this is not the correct usage of memtest, but I am doing this for convenience
    "EFI/systemd/Memtest.efi" = "${pkgs.memtest86plus}/memtest.efi";
  };
  ```
2. Run `sudo nixos-rebuild boot`

### Expected behavior
The process ends normally.

### Additional context
I discovered this problem when I tried to install PreLoader for secure boot in my environment.
https://github.com/turtton/dotnix/commit/1462de43bc3f4352cbefbcce5ebc4e179394eb08#diff-7359f47b50b637cb65f4127ae3f44af2885ca97dcac333b3f8f80e2fedc06f59

It seems to be caused by the fact that the regular expression in `installed_match` only looks at the first file in the bootloader list output by `bootctl status`
https://github.com/NixOS/nixpkgs/blob/7fc13a0d56ffc5d848876d0c9105a925782e40f9/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L299
Regex result
https://regex101.com/r/usstKD/2

### Workaround
Add `--install-bootloader` option every time
or 
Apply this patch
https://github.com/turtton/nixpkgs/commit/c0f29cee5621026857062faad73ffbf74b70c0f4

Regex result
https://regex101.com/r/1e2XRk/1

### Notify maintainers
@Mic92 @waldheinz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21-xanmod1, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by turtton** [comment]
Fixed in #326701
