### ISSUE TITLE
Build failure: catppuccin-gtk

### ISSUE THREAD

**Issue by zspher** [NixOS/nixpkgs#298043]
### Steps To Reproduce

1. build catppuccin-gtk

### Build log

```
error: builder for '/nix/store/vlxyr01rb4myzzg44jsylqc5dzhy3mx8-catppuccin-gtk-0.7.1.drv' failed with exit code 1;
       last 10 log lines:
       > colloid/install.sh: interpreter directive changed from "#! /usr/bin/env bash" to "/nix/store/5lr5n3qa4day8l1ivbwlcby2nknczqkq-bash-5.2p26/bin/bash"
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: glibPreInstallPhase
       > Running phase: installPhase
       > Traceback (most recent call last):
       >   File "/build/source/install.py", line 12, in <module>
       >     from scripts.ctp_colors import ctp_colors, get_all_accent
       >   File "/build/source/scripts/ctp_colors.py", line 1, in <module>
       >     from catppuccin import Flavour
       > ImportError: cannot import name 'Flavour' from 'catppuccin' (/nix/store/1y5kbppc2d4f9zsfaim4lp59aa1zis13-python3-3.11.8-env/lib/python3.11/site-packages/catppuccin/__init__.py)
       For full logs, run 'nix log /nix/store/vlxyr01rb4myzzg44jsylqc5dzhy3mx8-catppuccin-gtk-0.7.1.drv'.
error: 1 dependencies of derivation '/nix/store/2lm0iznjlgbkmwnwpxwhmf1plnqbbbmw-hm_gtk4.0gtk.css.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zr1i436wd9nbpvvjab5qg9jnvwb0dln9-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/51sfrffqmy4bx4dxjgiy73d6psn3wnz9-home-manager-generation.drv' failed to build

```

### Additional context

related to https://github.com/catppuccin/gtk/issues/152
incompatible dependency to python312Packages.catppuccin 2.0.0

### Notify maintainers

@fufexan @dixslyf 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05.20240321.20f77aa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/wa8lhchql76i6czzvad3bqz6lvnjnbr5-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by khaneliman** [comment]
Overlay until https://github.com/NixOS/nixpkgs/pull/297683 hits nixos-unstable. 

```nix
_: final: prev: {
  pythonPackagesExtensions = prev.pythonPackagesExtensions ++ [
    (
      python-final: python-prev: {
        catppuccin = python-prev.catppuccin.overridePythonAttrs (oldAttrs: rec {
          version = "1.3.2";

          src = prev.fetchFromGitHub {
            owner = "catppuccin";
            repo = "python";
            rev = "refs/tags/v${version}";
            hash = "sha256-spPZdQ+x3isyeBXZ/J2QE6zNhyHRfyRQGiHreuXzzik=";
          };

          # can be removed next version
          disabledTestPaths = [
            "tests/test_flavour.py" # would download a json to check correctness of flavours
          ];
        });
      }
    )
  ];
}
```

**Comment by RustLover2910** [comment]
Like this?

```
nixpkgs.overlays = [
    (final: prev: {
      pythonPackagesExtensions =
        prev.pythonPackagesExtensions
        ++ [
          (
            python-final: python-prev: {
              catppuccin = python-prev.catppuccin.overridePythonAttrs (oldAttrs: rec {
                version = "1.3.2";
                src = prev.fetchFromGitHub {
                  owner = "catppuccin";
                  repo = "python";
                  rev = "refs/tags/v${version}";
                  hash = "sha256-spPZdQ+x3isyeBXZ/J2QE6zNhyHRfyRQGiHreuXzzik=";
                };

                # can be removed next version
                disabledTestPaths = [
                  "tests/test_flavour.py" # would download a json to check correctness of flavours
                ];
              });
            }
          )
        ];
    })
  ];
```

**Comment by Svenum** [comment]
The PR is in unstable and works for me: https://nixpk.gs/pr-tracker.html?pr=297683

**Comment by khaneliman** [comment]
fixed in unstable now
