### ISSUE TITLE
Build failure: tere

### ISSUE THREAD

**Issue by timon-schelling** [NixOS/nixpkgs#298489]
### Steps To Reproduce

1. build tere

### Build log

```
failures:

---- app_state::tests::test_case_sensitive_mode_change stdout ----
thread 'app_state::tests::test_case_sensitive_mode_change' panicked at src/app_state.rs:1711:9:
assertion `left == right` failed
  left: [2]
 right: [1]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    app_state::tests::test_case_sensitive_mode_change

test result: FAILED. 90 passed; 1 failed;
```

### Additional context

after 49f83b701e7939079c529f378c79fa8544f4db72 

### Notify maintainers

@ProducerMatt

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05.20240319.b06025f`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ProducerMatt** [comment]
This bug was apparently [fixed here](https://github.com/mgunyho/tere/commit/8cadf56d5a835da844c70c54f026a22f6c640c8f), but upgrading to the latest release (or git commit) just gives new errors, which have been [mentioned but not fixed here](https://github.com/mgunyho/tere/issues/93).

I assume that these errors starting, especially in the Nix build system, show that it's some kind of issue with upgrades to dependencies.

```
running 4 tests
test output_on_exit_without_cd ... FAILED
test first_run_prompt_accept ... FAILED
test first_run_prompt_cancel ... FAILED
test basic_run ... FAILED

failures:

---- output_on_exit_without_cd stdout ----
thread 'output_on_exit_without_cd' panicked at tests/cli.rs:76:5:
assertion `left == right` failed
  left: "Error: Io(Os { code: 2, kind: NotFound, message: \"No such file or directory\" })\r\n"
 right: "tere: Exited without changing folder\r\n"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- first_run_prompt_accept stdout ----
thread 'first_run_prompt_accept' panicked at tests/cli.rs:126:5:
assertion failed: ptn.find(&output).is_some()

---- first_run_prompt_cancel stdout ----
thread 'first_run_prompt_cancel' panicked at tests/cli.rs:96:5:
assertion failed: ptn.find(&output).is_some()

---- basic_run stdout ----
thread 'basic_run' panicked at tests/cli.rs:61:5:
assertion `left == right` failed
  left: "Error: Io(Os { code: 2, kind: NotFound, message: \"No such file or directory\" })\r\n"
 right: "/build/.tmpbctZr0\r\n"


failures:
    basic_run
    first_run_prompt_accept
    first_run_prompt_cancel
    output_on_exit_without_cd

test result: FAILED. 0 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.11s
```

**Comment by ProducerMatt** [comment]
Will be fixed by https://github.com/NixOS/nixpkgs/pull/298527
