### ISSUE TITLE
graphite crashes on nixos-17.09

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixpkgs#29961]
After upgrading nixpkgs to nixos-17.09-small I noticed that graphite crashes when started:
```
journalctl -b -u graphiteWeb
Sep 30 18:40:42 bassbox systemd[1]: Starting Graphite Web Interface...
Sep 30 18:40:42 bassbox systemd[1]: Started Graphite Web Interface.
Sep 30 18:40:42 bassbox waitress-serve[971]: Could not import graphite.local_settings, using defaults!
Sep 30 18:40:42 bassbox waitress-serve[971]: /nix/store/yx51c8waxp9jjvcbgxhshxkwbacfsdgh-python-2.7.14-env/lib/python2.7/site-packages/opt/graphite/webapp/graphite/settings.py:246: UserWarning: SECRET_KEY 
Sep 30 18:40:42 bassbox waitress-serve[971]:   warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
Sep 30 18:40:42 bassbox waitress-serve[971]: Traceback (most recent call last):
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/kcd3r63jhdp0lp31zcc04lpfilgdv6ww-python2.7-waitress-0.8.9/bin/.waitress-serve-wrapped", line 12, in <module>
Sep 30 18:40:42 bassbox waitress-serve[971]:     sys.exit(run())
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/kcd3r63jhdp0lp31zcc04lpfilgdv6ww-python2.7-waitress-0.8.9/lib/python2.7/site-packages/waitress/runner.py", line 211, in run
Sep 30 18:40:42 bassbox waitress-serve[971]:     app = app()
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/yx51c8waxp9jjvcbgxhshxkwbacfsdgh-python-2.7.14-env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
Sep 30 18:40:42 bassbox waitress-serve[971]:     self.load_middleware()
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/yx51c8waxp9jjvcbgxhshxkwbacfsdgh-python-2.7.14-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 56, in load_middleware
Sep 30 18:40:42 bassbox waitress-serve[971]:     mw_class = import_string(middleware_path)
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/yx51c8waxp9jjvcbgxhshxkwbacfsdgh-python-2.7.14-env/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
Sep 30 18:40:42 bassbox waitress-serve[971]:     module = import_module(module_path)
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/2ap5wpmzb2l1cwmcmra5m28qq47ln7dh-python-2.7.14/lib/python2.7/importlib/__init__.py", line 37, in import_module
Sep 30 18:40:42 bassbox waitress-serve[971]:     __import__(name)
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/yx51c8waxp9jjvcbgxhshxkwbacfsdgh-python-2.7.14-env/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 4, in <module>
Sep 30 18:40:42 bassbox waitress-serve[971]:     from django.contrib.auth.backends import RemoteUserBackend
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/yx51c8waxp9jjvcbgxhshxkwbacfsdgh-python-2.7.14-env/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 4, in <module>
Sep 30 18:40:42 bassbox waitress-serve[971]:     from django.contrib.auth.models import Permission
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/yx51c8waxp9jjvcbgxhshxkwbacfsdgh-python-2.7.14-env/lib/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
Sep 30 18:40:42 bassbox waitress-serve[971]:     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/yx51c8waxp9jjvcbgxhshxkwbacfsdgh-python-2.7.14-env/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
Sep 30 18:40:42 bassbox waitress-serve[971]:     class AbstractBaseUser(models.Model):
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/yx51c8waxp9jjvcbgxhshxkwbacfsdgh-python-2.7.14-env/lib/python2.7/site-packages/django/db/models/base.py", line 110, in __new__
Sep 30 18:40:42 bassbox waitress-serve[971]:     app_config = apps.get_containing_app_config(module)
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/yx51c8waxp9jjvcbgxhshxkwbacfsdgh-python-2.7.14-env/lib/python2.7/site-packages/django/apps/registry.py", line 247, in get_containing_app_conf
Sep 30 18:40:42 bassbox waitress-serve[971]:     self.check_apps_ready()
Sep 30 18:40:42 bassbox waitress-serve[971]:   File "/nix/store/yx51c8waxp9jjvcbgxhshxkwbacfsdgh-python-2.7.14-env/lib/python2.7/site-packages/django/apps/registry.py", line 125, in check_apps_ready
Sep 30 18:40:42 bassbox waitress-serve[971]:     raise AppRegistryNotReady("Apps aren't loaded yet.")
Sep 30 18:40:42 bassbox waitress-serve[971]: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
Sep 30 18:40:42 bassbox systemd[1]: graphiteWeb.service: Main process exited, code=exited, status=1/FAILURE
Sep 30 18:40:42 bassbox systemd[1]: graphiteWeb.service: Unit entered failed state.
Sep 30 18:40:42 bassbox systemd[1]: graphiteWeb.service: Failed with result 'exit-code'.
```

**Comment by basvandijk** [comment]
I'm trying to upgrade graphite from 0.9.15 to 1.0.2 to see if that fixes things:
https://github.com/NixOS/nixpkgs/compare/release-17.09...LumiGuide:graphite-1.0.2_nixos-17.09-small. 

Fortunately `graphiteWeb` now starts. However `localhost:7200` returns a web page with the following error:

```
Traceback (most recent call last):
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/opt/graphite/webapp/graphite/composer/views.py", line 35, in composer
    profile = getProfile(request)
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/opt/graphite/webapp/graphite/user_util.py", line 22, in getProfile
    if request.user.is_authenticated():
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    self._setup()
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/django/utils/functional.py", line 376, in _setup
    self._wrapped = self._setupfunc()
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 167, in get_user
    user_id = _get_user_session_key(request)
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 150, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/nix/store/qgv2kf2zkdds8yq2zkv26npv7n8qjrln-python-2.7.14-env/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by basvandijk** [comment]
@makefu, @offlinehacker any ideas how to fix this?

**Comment by makefu** [comment]
@basvandijk may be related to https://stackoverflow.com/questions/25537905/django-1-7-throws-django-core-exceptions-appregistrynotready-models-arent-load ,django 1.7 seems to have changed how wsgi applications are loaded

**Comment by basvandijk** [comment]
I've now [managed](https://github.com/NixOS/nixpkgs/compare/release-17.09...LumiGuide:graphite-1.0.2_nixos-17.09-small) to successfully start graphiteWeb. 

The only problem remaining is that graphiteWeb is returning 404s for static files.

@rickynils @offlinehacker @makefu any idea how to fix that?
