### ISSUE TITLE
hg-git is broken

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#30154]
## Issue description
hggit shipped with nixos support mercurial 3.7,while mercurial shipped with nixos is 4.3.2

### Steps to reproduce
- Install package `mercurialFull`
- `hg clone https://github.com/adamgundry/type-inference.git`
- result:
```
destination directory: type-inference
** Unknown exception encountered with possibly-broken third-party extension hggit
** which supports versions 3.7 of Mercurial.
** Please disable hggit and try your action again.
** If that fixes the bug please report it to https://bitbucket.org/durin42/hg-git/issues
** Python 2.7.14 (default, Sep 16 2017, 17:49:51) [GCC 6.4.0]
** Mercurial Distributed SCM (version 4.3.2)
** Extensions loaded: hggit
Traceback (most recent call last):
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/bin/..hg-wrapped-wrapped", line 46, in <module>
    mercurial.dispatch.run()
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/dispatch.py", line 81, in run
    status = (dispatch(req) or 0) & 255
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/dispatch.py", line 162, in dispatch
    ret = _runcatch(req)
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/dispatch.py", line 302, in _runcatch
    return _callcatch(ui, _runcatchfunc)
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/dispatch.py", line 310, in _callcatch
    return scmutil.callcatch(ui, func)
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/scmutil.py", line 150, in callcatch
    return func()
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/dispatch.py", line 292, in _runcatchfunc
    return _dispatch(req)
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/dispatch.py", line 896, in _dispatch
    cmdpats, cmdoptions)
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/dispatch.py", line 658, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/dispatch.py", line 904, in _runcommand
    return cmdfunc()
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/dispatch.py", line 893, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/util.py", line 1077, in check
    return func(*args, **kwargs)
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/commands.py", line 1410, in clone
    shareopts=opts.get('shareopts'))
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/hg.py", line 631, in clone
    streamclonerequested=stream)
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/extensions.py", line 322, in closure
    return func(*(args + a), **kw)
  File "/nix/store/p3bq04knmgxgwi5kzh38xb3bgf4p8z1f-python2.7-hg-git-0.8.5/lib/python2.7/site-packages/hggit/util.py", line 52, in inner
    return f(*args, **kwargs)
  File "/nix/store/p3bq04knmgxgwi5kzh38xb3bgf4p8z1f-python2.7-hg-git-0.8.5/lib/python2.7/site-packages/hggit/__init__.py", line 331, in exchangepull
    pullop.cgresult = repo.githandler.fetch(remote.path, heads)
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/repoview.py", line 239, in __getattr__
    return getattr(self._unfilteredrepo, attr)
  File "/nix/store/9g3x71wpia7cvnss7aqvymkq59cs2s6w-mercurial-4.3.2/lib/python2.7/site-packages/mercurial/util.py", line 823, in __get__
    result = self.func(obj)
  File "/nix/store/p3bq04knmgxgwi5kzh38xb3bgf4p8z1f-python2.7-hg-git-0.8.5/lib/python2.7/site-packages/hggit/hgrepo.py", line 66, in githandler
    return GitHandler(self, self.ui)
  File "/nix/store/p3bq04knmgxgwi5kzh38xb3bgf4p8z1f-python2.7-hg-git-0.8.5/lib/python2.7/site-packages/hggit/git_handler.py", line 110, in __init__
    self.gitdir = self.repo.join('git')
AttributeError: 'hgrepo' object has no attribute 'join'
```

## Technical details

* System: Nixos 18.03pre117013.aebdc892d6 (Impala)
* Nix version:nix-env (Nix) 1.12pre5619_346aeee1
* Nixpkgs version:18.03pre117013.aebdc892d6
* Sandboxing enabled: true

**Comment by marsam** [comment]
This is a bug in hg-git upstream https://bitbucket.org/durin42/hg-git/issues/220/hg-git-broken-with-mercurial-431
