### ISSUE TITLE
twtxt gives a "ModuleNotFoundError: No module named 'pkg_resources'" error outside a devel enviroment

### ISSUE THREAD

**Issue by orahcio** [NixOS/nixpkgs#301588]
### Describe the bug
When we try to install twtxt package on environment.systempackages = with pkgs;[ twtxt ]; the twtxt application does not work with the output on the title.

### Steps To Reproduce
1. Type this flake.nix based on twtxt nixpkgs reference
```nix
{
  description = "A twtxt build schema";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, ... }: flake-utils.lib.eachDefaultSystem (system:
    let

      pkgs = import nixpkgs {
        inherit system;
      };

      my_twtxt = pkgs.python3Packages.buildPythonApplication rec {
        pname = "twtxt";
        version = "1.3.1";

        src = pkgs.fetchFromGitHub {
          owner = "buckket";
          repo = pname;
          rev = "refs/tags/v${version}";
          sha256 = "sha256-CbFh1o2Ijinfb8X+h1GP3Tp+8D0D3/Czt/Uatd1B4cw=";
        };

        # Relax some dependencies
        postPatch = ''
          substituteInPlace setup.py \
            --replace 'aiohttp>=2.2.5,<3' 'aiohttp' \
            --replace 'click>=6.7,<7' 'click' \
            --replace 'humanize>=0.5.1,<1' 'humanize'
        '';

        propagatedBuildInputs = with pkgs.python3Packages;[ aiohttp python-dateutil humanize click ];

        nativeCheckInputs = with pkgs.python3Packages; [ pytestCheckHook tox ];

        disabledTests = [
          # Disable test using relative date and time
          "test_tweet_relative_datetime"
        ];

        meta = with pkgs.lib; {
          description = "Decentralised, minimalist microblogging service for hackers";
          homepage = "https://github.com/buckket/twtxt";
          license = licenses.mit;
          maintainers = with maintainers; [ siraben ];
          mainProgram = "twtxt";
        };
      };

      packageName = "twtxt";

    in {
      packages.${packageName} = my_twtxt;
      defaultPackage = self.packages.${system}.${packageName};
    }
  );
}
```
3. Run `nix run .# -- --version` to run the equivalent to `twtxt --version`

### Expected behavior

The result from command above should be
```console
[user@system:~]$ nix run .# -- --version
twtxt, version 1.3.1
```

### Screenshots
But the output will be something like
```console
Traceback (most recent call last):
  File "/nix/store/dq9bgw3rgs5ck6whqkh64qa97yzj7cd2-twtxt-1.3.1/bin/.twtxt-wrapped", line 6, in <module>
    from twtxt.cli import main
  File "/nix/store/dq9bgw3rgs5ck6whqkh64qa97yzj7cd2-twtxt-1.3.1/lib/python3.11/site-packages/twtxt/cli.py", line 22, in <module>
    from twtxt.helper import run_pre_tweet_hook, run_post_tweet_hook
  File "/nix/store/dq9bgw3rgs5ck6whqkh64qa97yzj7cd2-twtxt-1.3.1/lib/python3.11/site-packages/twtxt/helper.py", line 17, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

### Additional context
The steuptools needs to be referenced on propagatedBuildInputs, maybe another python applications have the same bug.

### Notify maintainers
@siraben 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.311, NixOS, 24.05 (Uakari), 24.05.20240403.fd281bd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/n2g5cqwv8qf5p6vjxny6pg3blbdij12k-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fabaff** [comment]
Could you please take a look at #301767? Feedback would be much appreciated as I'm not a `twtxt` user.
