### ISSUE TITLE
puddletag: starting fails with TypeError

### ISSUE THREAD

**Issue by antonmosich** [NixOS/nixpkgs#301857]
### Describe the bug
Puddletag fails to start properly and fails with a python error message instead of starting. See Additional context for the Traceback.

### Steps To Reproduce
1. `nix run nixpkgs#puddletag` or `nix-shell -p puddletag --run puddletag` or something like that. You need to have a graphical environment.

### Expected behavior
I expected puddletag to start and present its GUI

### Additional context
```
puddletag Version: 2.3.0
Locale: en_US
Traceback (most recent call last):
  File "/nix/store/njrandvpg5j38ngrsjx8waa49q13ih3v-puddletag-2.3.0/bin/..puddletag-wrapped-wrapped", line 353, in <module>
    from puddlestuff.puddletag import MainWin
  File "/nix/store/njrandvpg5j38ngrsjx8waa49q13ih3v-puddletag-2.3.0/lib/python3.11/site-packages/puddlestuff/puddletag.py", line 14, in <module>
    from . import mainwin
  File "/nix/store/njrandvpg5j38ngrsjx8waa49q13ih3v-puddletag-2.3.0/lib/python3.11/site-packages/puddlestuff/mainwin/__init__.py", line 4, in <module>
    from . import dirview
  File "/nix/store/njrandvpg5j38ngrsjx8waa49q13ih3v-puddletag-2.3.0/lib/python3.11/site-packages/puddlestuff/mainwin/dirview.py", line 12, in <module>
    from ..tagmodel import has_previews
  File "/nix/store/njrandvpg5j38ngrsjx8waa49q13ih3v-puddletag-2.3.0/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 32, in <module>
    from .audio_filter import parse as filter_audio
  File "/nix/store/njrandvpg5j38ngrsjx8waa49q13ih3v-puddletag-2.3.0/lib/python3.11/site-packages/puddlestuff/audio_filter.py", line 183, in <module>
    bool_expr.enablePackrat()
  File "/nix/store/68g0072fj371qjmik5qlwlbiwgidsnfi-python3.11-pyparsing-3.1.2/lib/python3.11/site-packages/pyparsing/util.py", line 265, in _inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/68g0072fj371qjmik5qlwlbiwgidsnfi-python3.11-pyparsing-3.1.2/lib/python3.11/site-packages/pyparsing/core.py", line 1132, in enable_packrat
    ParserElement.packrat_cache = _FifoCache(cache_size_limit)  # type: ignore[assignment]
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/68g0072fj371qjmik5qlwlbiwgidsnfi-python3.11-pyparsing-3.1.2/lib/python3.11/site-packages/pyparsing/util.py", line 105, in __init__
    keyring = [object()] * size
              ~~~~~~~~~~~^~~~~~
TypeError: can't multiply sequence by non-int of type 'Forward'
```

### Notify maintainers
@peterhoeg @dschrempf 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.3, NixOS, 24.05 (Uakari), 24.05.20240403.fd281bd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - channels(anton): `""`
 - nixpkgs: `/nix/store/n2g5cqwv8qf5p6vjxny6pg3blbdij12k-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by peterhoeg** [comment]
Yep the referenced PR fixes this.
