### ISSUE TITLE
HomeAssistant: Setup failed for 'smartthings'

### ISSUE THREAD

**Issue by techyporcupine** [NixOS/nixpkgs#303483]
### Describe the bug
Recently, after updating my HA instance that is running on NixOS, I get `Setup failed for 'smartthings': Unable to import component: No module named 'pkg_resources'` when I start HA and I cannot use the SmartThings integration.

### Steps To Reproduce
1. Enable HA on NixOS
2. Have SmartThings set up
3. Update to whatever version caused it (I haven't been able to determine what version it was that broke)

### Expected behavior
I expect the SmartThings integration to successfully run and connect to the devices it should and be usable, instead I get an entirely non-functional integration.

### Additional context
I do not think this is an HA wide issue after doing some Google searching with the issue, I think it is NixOS related, but someone can correct me if I'm wrong.

### Notify maintainers
Can't tell exactly who to ping here, but I think at least @mweinelt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.4, NixOS, 24.05 (Uakari), 24.05.20240406.ff0dbd9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/j10523yhkcc34478azkgcl70yzcx6j2j-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
Please post a complete traceback if available, so we can determine what exactly requires `pkg_resources`.

**Comment by techyporcupine** [comment]
```
Logger: homeassistant.setup
Source: setup.py:316
First occurred: 6:47:06 PM (1 occurrences)
Last logged: 6:47:06 PM

Setup failed for 'smartthings': Unable to import component: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/nix/store/akxl9vmy8ka66zxlnpyy5038csvy6faf-homeassistant-2024.4.0/lib/python3.12/site-packages/homeassistant/loader.py", line 979, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fmwqa8nvva4sh18bqayzrilrzxq9fm0f-python3-3.12.2/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/akxl9vmy8ka66zxlnpyy5038csvy6faf-homeassistant-2024.4.0/lib/python3.12/site-packages/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fmwqa8nvva4sh18bqayzrilrzxq9fm0f-python3-3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/nix/store/akxl9vmy8ka66zxlnpyy5038csvy6faf-homeassistant-2024.4.0/lib/python3.12/site-packages/homeassistant/components/smartthings/__init__.py", line 12, in <module>
    from pysmartapp.event import EVENT_TYPE_DEVICE
  File "/nix/store/8b27ra0gjfpz2yy0x5v8ck33xjzjw335-python3.12-pysmartapp-0.3.5/lib/python3.12/site-packages/pysmartapp/__init__.py", line 3, in <module>
    from pysmartapp.config import (
  File "/nix/store/8b27ra0gjfpz2yy0x5v8ck33xjzjw335-python3.12-pysmartapp-0.3.5/lib/python3.12/site-packages/pysmartapp/config.py", line 6, in <module>
    from .request import Request, Response
  File "/nix/store/8b27ra0gjfpz2yy0x5v8ck33xjzjw335-python3.12-pysmartapp-0.3.5/lib/python3.12/site-packages/pysmartapp/request.py", line 3, in <module>
    from httpsig.verify import HeaderVerifier
  File "/nix/store/81kbji79cxg0jy7hvnh3qqbw3q30v21x-python3.12-httpsig-1.3.0/lib/python3.12/site-packages/httpsig/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/akxl9vmy8ka66zxlnpyy5038csvy6faf-homeassistant-2024.4.0/lib/python3.12/site-packages/homeassistant/setup.py", line 316, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/akxl9vmy8ka66zxlnpyy5038csvy6faf-homeassistant-2024.4.0/lib/python3.12/site-packages/homeassistant/loader.py", line 997, in async_get_component
    self._component_future.result()
  File "/nix/store/akxl9vmy8ka66zxlnpyy5038csvy6faf-homeassistant-2024.4.0/lib/python3.12/site-packages/homeassistant/loader.py", line 989, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/akxl9vmy8ka66zxlnpyy5038csvy6faf-homeassistant-2024.4.0/lib/python3.12/site-packages/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fmwqa8nvva4sh18bqayzrilrzxq9fm0f-python3-3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/nix/store/akxl9vmy8ka66zxlnpyy5038csvy6faf-homeassistant-2024.4.0/lib/python3.12/site-packages/homeassistant/components/smartthings/__init__.py", line 12, in <module>
    from pysmartapp.event import EVENT_TYPE_DEVICE
  File "/nix/store/8b27ra0gjfpz2yy0x5v8ck33xjzjw335-python3.12-pysmartapp-0.3.5/lib/python3.12/site-packages/pysmartapp/__init__.py", line 3, in <module>
    from pysmartapp.config import (
  File "/nix/store/8b27ra0gjfpz2yy0x5v8ck33xjzjw335-python3.12-pysmartapp-0.3.5/lib/python3.12/site-packages/pysmartapp/config.py", line 6, in <module>
    from .request import Request, Response
  File "/nix/store/8b27ra0gjfpz2yy0x5v8ck33xjzjw335-python3.12-pysmartapp-0.3.5/lib/python3.12/site-packages/pysmartapp/request.py", line 3, in <module>
    from httpsig.verify import HeaderVerifier
  File "/nix/store/81kbji79cxg0jy7hvnh3qqbw3q30v21x-python3.12-httpsig-1.3.0/lib/python3.12/site-packages/httpsig/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by mweinelt** [comment]
https://nixpk.gs/pr-tracker.html?pr=303491

**Comment by techyporcupine** [comment]
Thank you!
