### ISSUE TITLE
Packaging gpgme python bindings: how to run ./configure while creating the python package

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#30392]
## Issue description
I am trying to package gpg python bindings that are available here https://dev.gnupg.org/source/gpgme/browse/master/lang/python/ . As you can see there is no setup.py but a setup.py.in  so I need to first run the ./configure before letting the python bindings kick in. I couldn't do it within the buildPythonPackage, also it means that the same ./configure is called twice, one for gpgme, the other for its bindings so I wonder if both shouldn't reside in the same file with sthg like:
```
let 
version= X.X
in
gpgme = mkDerviation {
...
version = version
pythonPkg = buildPythonPackage {
     version = version
    src= "gpgme.src}/lang/python"
}
....
}
```
and then in python-packages.nix
`   gpgme = gpg.pythonPkg;`

My first attempt was using 2 separate files but it's not too successful, here is the new gpg.nix python file:
https://github.com/teto/nixpkgs/blob/50b9f3b5aeb415f6e3cbc6df8731ae9806bd1e21/pkgs/development/python-modules/gpg/default.nix

NB: Notmuch also has bindings as part of its main repository but the setup.py already exists so that's not helpful.

**Comment by srhb** [comment]
Perhaps something like this? I had to tweak some paths for the includes, as the setup.py isn't compatible with the split derivations of gpgme and libgpgerror.

`
{ stdenv, buildPythonPackage, gpgme, libgpgerror, swig2 }:

buildPythonPackage rec {
  version = "1.9.0";
  pname = "pgpgme";
  name = "${pname}-${version}";

  src = "${gpgme.src}";

  buildInputs = [ libgpgerror gpgme swig2 ];

  preConfigure = ''
    ./configure --enable-languages=python
    cd lang/python
    substituteInPlace setup.py \
      --replace \
      'gpg_error_prefix = getconfig("prefix", config=gpg_error_config)[0]' \
      'gpg_error_prefix = "${libgpgerror.dev}"' \
      --replace \
      'gpgme_h = ""' \
      'gpgme_h = "${gpgme.dev}/include/gpgme.h"'
  '';
}
`

**Comment by teto** [comment]
Thanks that worked great, I've updated my branch
https://github.com/teto/nixpkgs/tree/alot

Before opening up a PR, I wanted to have a try fixing the 3 failing tests. The first one doesn't find the gpg binary but the others leave surprise me more, I've tried changing the locale to `    LC_ALL = "en_US.utf8";` and I wonder if it might be shell-related ?
I tried to look into the testing setup here https://github.com/pazz/alot/blob/master/.travis.yml for clues but I am blind:
```
======================================================================
ERROR: test_valid_signature_generated (tests.crypto_test.TestDetachedSignatureFor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-alot-0.6.drv-3/alot-0.6-src/tests/crypto_test.py", line 127, in test_valid_signature_generated
    stdout=DEVNULL, stderr=DEVNULL)
  File "/nix/store/casmpqw8aypdw2cfs2lvgklbqjzfq9q2-python-2.7.14/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/nix/store/casmpqw8aypdw2cfs2lvgklbqjzfq9q2-python-2.7.14/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/nix/store/casmpqw8aypdw2cfs2lvgklbqjzfq9q2-python-2.7.14/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/nix/store/casmpqw8aypdw2cfs2lvgklbqjzfq9q2-python-2.7.14/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test_encrypt (tests.crypto_test.TestEncrypt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-alot-0.6.drv-3/alot-0.6-src/tests/crypto_test.py", line 372, in test_encrypt
    stderr=DEVNULL)
  File "/nix/store/casmpqw8aypdw2cfs2lvgklbqjzfq9q2-python-2.7.14/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/nix/store/casmpqw8aypdw2cfs2lvgklbqjzfq9q2-python-2.7.14/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/nix/store/casmpqw8aypdw2cfs2lvgklbqjzfq9q2-python-2.7.14/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: tearDownModule (tests.crypto_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-alot-0.6.drv-3/alot-0.6-src/tests/utilities.py", line 132, in wrapper
    teardown()
  File "/tmp/nix-build-alot-0.6.drv-3/alot-0.6-src/tests/crypto_test.py", line 60, in tearDownModule
    out = subprocess.check_output(['ps', 'xo', 'pid,cmd'], stderr=DEVNULL)
  File "/nix/store/casmpqw8aypdw2cfs2lvgklbqjzfq9q2-python-2.7.14/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/nix/store/casmpqw8aypdw2cfs2lvgklbqjzfq9q2-python-2.7.14/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/nix/store/casmpqw8aypdw2cfs2lvgklbqjzfq9q2-python-2.7.14/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

======================================================================
FAIL: test_no_stdin_unicode (tests.helper_test.TestCallCmd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-alot-0.6.drv-3/alot-0.6-src/tests/helper_test.py", line 327, in test_no_stdin_unicode
    self.assertEqual(out, u'�')
AssertionError: u'\ufffd\ufffd\ufffd' != u'\ufffd'
- \ufffd\ufffd\ufffd
+ \ufffd

checkPhase
  # Python packages don't have a checkPhase, only an installCheckPhase


======================================================================
FAIL: test_stdin (tests.helper_test.TestCallCmd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-alot-0.6.drv-3/alot-0.6-src/tests/helper_test.py", line 333, in test_stdin
    self.assertEqual(out, u'�')
AssertionError: u'\ufffd\ufffd\ufffd' != u'\ufffd'
- \ufffd\ufffd\ufffd
+ \ufffd

```

I will try asking on #alot but if you have already seen this, feel free to share.

**Comment by teto** [comment]
Initial issue solved. Test failures remain but it's another problem.
