### ISSUE TITLE
mailman service does not start

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#304550]
### Describe the bug
The `mailman` service fails to start with an unhelpful message.
```console
/nix/store/1mblbvzr9nxx86lzafzdb1ird4sj79k7-python3-3.11.8-env/bin/mailman start
Traceback (most recent call last):
  File "/nix/store/1pld9jg5jzj9anz9all8ydhpy6w471h6-python3.11-mailman-3.3.9/bin/mailman", line 5, in <module>
    from mailman.bin.mailman import main
ModuleNotFoundError: No module named 'mailman'
```

### Steps To Reproduce
1. Install the `mailman` package
2. Attempt to start the `mailman` service

### Expected behavior
Even on a machine where the service isn't really installed, you should at least see a far different set of errors:
```console
/nix/store/r3q8phfmj33n1i132np763dv6xrxz5xf-python3-3.11.8-env/bin/mailman start
Starting Mailman's master runner
Generating MTA alias maps
Traceback (most recent call last):
  File "/nix/store/hbxsfxy579immalpa4accc51ykf5m39k-python3.11-mailman-3.3.9/bin/mailman", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/r3q8phfmj33n1i132np763dv6xrxz5xf-python3-3.11.8-env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/r3q8phfmj33n1i132np763dv6xrxz5xf-python3-3.11.8-env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/r3q8phfmj33n1i132np763dv6xrxz5xf-python3-3.11.8-env/lib/python3.11/site-packages/mailman/bin/mailman.py", line 69, in invoke
    return super().invoke(ctx)
...
```

### Additional context
The `mailman` package itself was not modified.  I know the failure is somewhere in the range of ed8d50fbfc4ef0d559c62d3ee3d40e6067c1524b and 0ef93bf950cf0184a64ec0ceeeaa6e00b04860b3.  0ef93bf950cf0184a64ec0ceeeaa6e00b04860b3 seems like an obvious candidate.

### Notify maintainers

@alyssais  is the mailman maintainer. @adisbladis is responsible for the rewrite of `mk-python-derivation`.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
bash-5.2$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.2, NixOS, 24.05 (Uakari), 24.05.20240416.807ac81`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/k621wfhjqjs1xk5diahdrf572rnli67a-source````
---
```

:+1:

**Comment by mdorman** [comment]
This seems to have been fixed.
