### ISSUE TITLE
home-assistant component openweathermap fails to set up

### ISSUE THREAD

**Issue by 9R** [NixOS/nixpkgs#305243]
### Describe the bug

The `home-assistant` integration `openweathermap` seem to require the missing python module `pkg_resources` and currently fails with this error message:

```
ERROR (MainThread) [homeassistant.setup] Setup failed for 'openweathermap': Unable to import component: No module named 'pkg_resources'
```

`pkg_resources` is provided by python `setuptools`.

Adding `setuptools` to `openweathermap` in the `component-packeges`.

Maybe this missing dependency could be resolved in pyowm as well. I would appreciate some input from somebody with more experience. 

### Steps To Reproduce
1. install home-assistant with openweathermap component

### Expected behavior
No Error message and working openweathermap component

### Notify maintainers

@fabaff
@mweinelt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.26, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 9R** [comment]
PR #305244

**Comment by mweinelt** [comment]
Please post the full stacktrace.

**Comment by 9R** [comment]
```
ERROR (MainThread) [homeassistant.setup] Setup failed for 'openweathermap': Unable to import component: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/nix/store/6kmbyl9xs5li5dgwwqrr7v17xrh6vlcp-homeassistant-2024.4.1/lib/python3.12/site-packages/homeassistant/loader.py", line 979, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fmwqa8nvva4sh18bqayzrilrzxq9fm0f-python3-3.12.2/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6kmbyl9xs5li5dgwwqrr7v17xrh6vlcp-homeassistant-2024.4.1/lib/python3.12/site-packages/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fmwqa8nvva4sh18bqayzrilrzxq9fm0f-python3-3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/nix/store/6kmbyl9xs5li5dgwwqrr7v17xrh6vlcp-homeassistant-2024.4.1/lib/python3.12/site-packages/homeassistant/components/openweathermap/__init__.py", line 8, in <module>
    from pyowm import OWM
  File "/nix/store/y89lfwgaggx4xbq25v62bq0h622nfcbm-python3.12-pyowm-3.3.0/lib/python3.12/site-packages/pyowm/__init__.py", line 4, in <module>
    from pyowm.owm import OWM
  File "/nix/store/y89lfwgaggx4xbq25v62bq0h622nfcbm-python3.12-pyowm-3.3.0/lib/python3.12/site-packages/pyowm/owm.py", line 14, in <module>
    from pyowm.commons import cityidregistry
  File "/nix/store/y89lfwgaggx4xbq25v62bq0h622nfcbm-python3.12-pyowm-3.3.0/lib/python3.12/site-packages/pyowm/commons/cityidregistry.py", line 7, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/6kmbyl9xs5li5dgwwqrr7v17xrh6vlcp-homeassistant-2024.4.1/lib/python3.12/site-packages/homeassistant/setup.py", line 316, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6kmbyl9xs5li5dgwwqrr7v17xrh6vlcp-homeassistant-2024.4.1/lib/python3.12/site-packages/homeassistant/loader.py", line 997, in async_get_component
    self._component_future.result()
  File "/nix/store/6kmbyl9xs5li5dgwwqrr7v17xrh6vlcp-homeassistant-2024.4.1/lib/python3.12/site-packages/homeassistant/loader.py", line 989, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6kmbyl9xs5li5dgwwqrr7v17xrh6vlcp-homeassistant-2024.4.1/lib/python3.12/site-packages/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fmwqa8nvva4sh18bqayzrilrzxq9fm0f-python3-3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/nix/store/6kmbyl9xs5li5dgwwqrr7v17xrh6vlcp-homeassistant-2024.4.1/lib/python3.12/site-packages/homeassistant/components/openweathermap/__init__.py", line 8, in <module>
    from pyowm import OWM
  File "/nix/store/y89lfwgaggx4xbq25v62bq0h622nfcbm-python3.12-pyowm-3.3.0/lib/python3.12/site-packages/pyowm/__init__.py", line 4, in <module>
    from pyowm.owm import OWM
  File "/nix/store/y89lfwgaggx4xbq25v62bq0h622nfcbm-python3.12-pyowm-3.3.0/lib/python3.12/site-packages/pyowm/owm.py", line 14, in <module>
    from pyowm.commons import cityidregistry
  File "/nix/store/y89lfwgaggx4xbq25v62bq0h622nfcbm-python3.12-pyowm-3.3.0/lib/python3.12/site-packages/pyowm/commons/cityidregistry.py", line 7, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by 9R** [comment]
There also was an upstream issue that may be related:
https://github.com/home-assistant/core/issues/105064

**Comment by mweinelt** [comment]
The fix is to add `setuptools` to pyowm's dependencies.

**Comment by 9R** [comment]
ok. Thanks for your help. I will create another PR later
