### ISSUE TITLE
dub-to-nix: fails to build lockfile with `git+https://...` dependencies

### ISSUE THREAD

**Issue by tomodachi94** [NixOS/nixpkgs#305440]
### Describe the bug
`dub-to-nix` fails to build a lockfile with dependencies in the format `{version: "asdf1234...", repository: "git+https://github.com/..."}` ([example](https://github.com/Dadoum/Sideloader/blob/570a3a63b75ce1ae4eacac3dfc19da522b270947/dub.selections.json)).

Here's the error:

```
Fetching argparse@1.3.0
Fetching arsd-official@10.9.10
Fetching automem@0.6.9
Fetching bindbc-freetype@1.0.5
Fetching bindbc-loader@1.0.3
Fetching bindbc-opengl@1.0.5
Fetching bindbc-sdl@1.0.1
Fetching botan@1.13.6
Fetching botan-math@1.0.4
Fetching cachetools@0.4.1
Fetching concepts@0.0.9
Fetching concurrency@5.0.4
Fetching dfl@{'version': '224d9348286620c8ea4854690a09e7380d6f5b2f', 'repository': 'git+https://github.com/Dadoum/dfl.git'}
Traceback (most recent call last):
  File "/tmp/Sideloader/./dub-to-nix.py", line 35, in <module>
    sha256 = subprocess.run(command, check=True, text=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout.rstrip()
             ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9snphnqp8g228a6jywfhhirrvn492y4r-python3-3.13.0a5/lib/python3.13/subprocess.py", line 575, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['nix-prefetch-url', '--type', 'sha256', "https://code.dlang.org/packages/dfl/{'version': '224d9348286620c8ea4854690a09e7380d6f5b2f', 'repository': 'git+https://github.com/Dadoum/dfl.git'}.zip"]' returned non-zero exit status 1.
```

### Steps To Reproduce
1. Clone any repository whose `dub.selections.json` contains a dependency that fetches from Git, e.g. https://github.com/Dadoum/Sideloader.
2. Run `dub-to-nix`, e.g. `nix-shell -p dub-to-nix --command "dub-to-nix"`.
3. Wait a few moments, then see error.

### Expected behavior
A generated lockfile containing the Git dependency.

### Notify maintainers

@TomaSajt

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.24, NixOS, 24.05 (Uakari), 24.05.20240404.23ff7d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/zgbsrwmv78jc9l40jd3lbv2ggmbjq9zp-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
Thanks for reporting this bug, I'll try to extend the lockfile logic later today, (the current one is pretty primitive, as you might have seen)
