### ISSUE TITLE
Build failure: python312Packages.tensorflow

### ISSUE THREAD

**Issue by ViZiD** [NixOS/nixpkgs#305827]
### Steps To Reproduce
run in master branch
```console
nix-build -A python312Packages.tensorflow
```

1. build python312Packages.tensorflow

### Build log

```
Running phase: installCheckPhase
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/build/tensorflow-2.13.0-python/tensorflow/__init__.py", line 29, in <module>
    import distutils as _distutils
ModuleNotFoundError: No module named 'distutils'
error: builder for '/nix/store/mb5p1gbgn6mfzniwl1bn01dfx0ff264c-python3.12-tensorflow-2.13.0.drv' failed with exit code 1;
       last 25 log lines:
       > checking for references to /build/ in /nix/store/c8qf6y3xky3f5kriwg5mhgjf4m4lqqp0-python3.12-tensorflow-2.13.0-dist...
       > patching script interpreter paths in /nix/store/c8qf6y3xky3f5kriwg5mhgjf4m4lqqp0-python3.12-tensorflow-2.13.0-dist
       > Rewriting #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3/bin/python3.12 to #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3
       > wrapping `/nix/store/cih6kp0fx8wym91aqsmphggvp2zpsyn8-python3.12-tensorflow-2.13.0/bin/estimator_ckpt_converter'...
       > Rewriting #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3/bin/python3.12 to #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3
       > wrapping `/nix/store/cih6kp0fx8wym91aqsmphggvp2zpsyn8-python3.12-tensorflow-2.13.0/bin/toco'...
       > Rewriting #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3/bin/python3.12 to #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3
       > wrapping `/nix/store/cih6kp0fx8wym91aqsmphggvp2zpsyn8-python3.12-tensorflow-2.13.0/bin/tflite_convert'...
       > Rewriting #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3/bin/python3.12 to #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3
       > wrapping `/nix/store/cih6kp0fx8wym91aqsmphggvp2zpsyn8-python3.12-tensorflow-2.13.0/bin/saved_model_cli'...
       > Rewriting #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3/bin/python3.12 to #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3
       > wrapping `/nix/store/cih6kp0fx8wym91aqsmphggvp2zpsyn8-python3.12-tensorflow-2.13.0/bin/import_pb_to_tensorboard'...
       > Rewriting #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3/bin/python3.12 to #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3
       > wrapping `/nix/store/cih6kp0fx8wym91aqsmphggvp2zpsyn8-python3.12-tensorflow-2.13.0/bin/tf_upgrade_v2'...
       > Rewriting #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3/bin/python3.12 to #!/nix/store/m51f0kclg01xdc0mjxqs5cpyaxqbqhg5-python3-3.12.3
       > wrapping `/nix/store/cih6kp0fx8wym91aqsmphggvp2zpsyn8-python3.12-tensorflow-2.13.0/bin/toco_from_protos'...
       > Executing pythonRemoveTestsDir
       > Finished executing pythonRemoveTestsDir
       > fixupPhase completed in 1 minutes 17 seconds
       > Running phase: installCheckPhase
       > Traceback (most recent call last):
       >   File "<stdin>", line 2, in <module>
       >   File "/build/tensorflow-2.13.0-python/tensorflow/__init__.py", line 29, in <module>
       >     import distutils as _distutils
       > ModuleNotFoundError: No module named 'distutils'
       For full logs, run 'nix log /nix/store/mb5p1gbgn6mfzniwl1bn01dfx0ff264c-python3.12-tensorflow-2.13.0.drv'.
```

### Notify maintainers
@abbradar

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.2`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pyrox0** [comment]
This has the same issue as #303325, where distutils has been removed from python 3.12, and we're waiting on upstream to remove their usages of it to fix this error. There's a tracking issue on tensorflow's repo here to follow progress: https://github.com/tensorflow/tensorflow/issues/58073

**Comment by zimward** [comment]
the `distutils` issue seems to be fixed upstream, so tf needs to be bumped to pull those changes which would also fix the incompatibility with python 3.12 (`error: tensorflow-2.13.0 not supported for interpreter python3.12`).

@jyp @abbradar
