### ISSUE TITLE
system-config-printer can't find urllib3

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#30596]
## Issue description
I have system-config-printer installed via home-manager yet when I try to launch it, I get

```~
Traceback (most recent call last):
  File "/nix/store/n98kgmh96iljgr4dw9x9r1qpnclvnlwh-system-config-printer-1.5.9/share/system-config-printer/system-config-printer.py", line 77, in <module>
    import cupshelpers
  File "/nix/store/n98kgmh96iljgr4dw9x9r1qpnclvnlwh-system-config-printer-1.5.9/lib/python3.6/site-packages/cupshelpers/__init__.py", line 60, in <module>
    from . import openprinting
  File "/nix/store/n98kgmh96iljgr4dw9x9r1qpnclvnlwh-system-config-printer-1.5.9/lib/python3.6/site-packages/cupshelpers/openprinting.py", line 22, in <module>
    import requests, urllib.request, urllib.parse, urllib.error, platform, threading, tempfile, traceback
  File "/nix/store/vj59nc1fbpxkf8br1jzaa42vslki5wcw-python3.6-requests-2.18.4/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
```
though requests appear in the package
```
  pythonPath = with pythonPackages;
    [ pycups pycurl dbus-python pygobject3 requests pycairo pysmbc ];
```

## Technical details
nixos-version=18.03.git.3999ff9 (Impala)
nix version: nix-env (Nix) 1.11.15
Nixpkgs version: "18.03.git.8bed062ba0"
sandboxing disabled

**Comment by FRidh** [comment]
The reason it cannot find `urllib3` is because dependencies of the items in `pythonPath` are not included. That's because the Python setup hook doesn't recurse.

**Comment by teto** [comment]
so I should add urllib3 to pythonPath then ?

2017-10-20 16:38 GMT+09:00 Frederik Rietdijk <notifications@github.com>:

**Comment by FRidh** [comment]
@teto you would need to recurse into the Python dependencies.

Could you test https://github.com/NixOS/nixpkgs/pull/30606? Note that it requires some rebuilding...

**Comment by FRidh** [comment]
The fix is in master so I am closing this.

**Comment by teto** [comment]
thanks for the hard work
