### ISSUE TITLE
Waydroid: ERROR: <urlopen error [Errno -3] Temporary failure in name resolution>

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#306193]
### Describe the bug

```
╰───❯ sudo waydroid init
[sudo: authenticate] Password:
[08:37:29] ERROR: <urlopen error [Errno -3] Temporary failure in name resolution>
[08:37:29] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
╰───❯ waydroid log
(054954) [08:40:07] Traceback (most recent call last):
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/http/client.py", line 1298, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/http/client.py", line 1344, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/http/client.py", line 1293, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/http/client.py", line 1052, in _send_output
    self.send(msg)
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/http/client.py", line 990, in send
    self.connect()
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/http/client.py", line 1463, in connect
    super().connect()
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/http/client.py", line 956, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/hdpm8y2l0nkjv1mhj69zrxsbkqy96hw7-waydroid-1.4.2/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/nix/store/hdpm8y2l0nkjv1mhj69zrxsbkqy96hw7-waydroid-1.4.2/lib/waydroid/tools/actions/initializer.py", line 124, in init
    helpers.images.get(args)
  File "/nix/store/hdpm8y2l0nkjv1mhj69zrxsbkqy96hw7-waydroid-1.4.2/lib/waydroid/tools/helpers/images.py", line 36, in get
    images_zip = helpers.http.download(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hdpm8y2l0nkjv1mhj69zrxsbkqy96hw7-waydroid-1.4.2/lib/waydroid/tools/helpers/http.py", line 110, in download
    with urllib.request.urlopen(url) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

(056740) [08:41:37] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(056740) [08:41:37] *** output passed to waydroid stdout, not to this log ***
```

### Steps To Reproduce
0. Set `virtualisation.waydroid.enable = true;` in your NixOS config and reboot
1. Invoke `sudo waydroid init` and expect the shown failure

### Expected behavior

Just work

### Additional context

My DNS seems to be working without issues as tested in various websites and including changing the DNS for cloudflare and libreDNS.

---

Doing it through the waydroid app seems to work:

![image](https://github.com/NixOS/nixpkgs/assets/11302521/2cbf4d2a-6f15-4a76-ac03-ba0a10aa42e6)

### Notify maintainers

CC @CajuM

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.6-xanmod1, NixOS, 23.11 (Tapir), 23.11.20240417.e402c3e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - channels(raptor): `"home-manager-23.05.tar.gz, nixpkgs-23.05, nixpkgs-unstable-23.05"`
 - nixpkgs: `/home/kreyren/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by CajuM** [comment]
I can't reproduce the issue. Could you check DNS using wireshark?

**Comment by Kreyren** [comment]
> I can't reproduce the issue. Could you check DNS using wireshark? -- @CajuM (https://github.com/NixOS/nixpkgs/issues/306193#issuecomment-2072043138)

![image](https://github.com/NixOS/nixpkgs/assets/11302521/b1ed884d-08a8-416e-9eff-ae2bdd2de3e6)

It seems to work today.. I guess it might have been an issue on the sourceforge's side yesterday.
