### ISSUE TITLE
Pycryptodome build fails (due to some unit test) on unstable on 32bit

### ISSUE THREAD

**Issue by shak-mar** [NixOS/nixpkgs#30613]
## Issue description

```
..................................................................
======================================================================
ERROR: test2 (Crypto.SelfTest.Protocol.test_KDF.scrypt_Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/lib.linux-i686-2.7/Crypto/SelfTest/Protocol/test_KDF.py", line 395, in test2
    output = scrypt(tv.P, tv.S, tv.dkLen, tv.N, tv.r, tv.p)
  File "build/lib.linux-i686-2.7/Crypto/Protocol/KDF.py", line 376, in scrypt
    raise ValueError("Error %X while running scrypt" % result)
ValueError: Error 2 while running scrypt

----------------------------------------------------------------------
Ran 22205 tests in 720.337s

FAILED (errors=1)
Traceback (most recent call last):
  File "nix_run_setup.py", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 607, in <module>
    sources=['src/strxor.c']),
  File "/nix/store/d5cjkpik1vw9z9638246z508y2zbsdgf-python-2.7.14/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/nix/store/d5cjkpik1vw9z9638246z508y2zbsdgf-python-2.7.14/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/nix/store/d5cjkpik1vw9z9638246z508y2zbsdgf-python-2.7.14/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 420, in run
    SelfTest.run(module=moduleObj, verbosity=self.verbose, stream=sys.stdout, config=self.config)
  File "build/lib.linux-i686-2.7/Crypto/SelfTest/__init__.py", line 76, in run
    raise SelfTestError("Self-test failed", result)
Crypto.SelfTest.SelfTestError: ('Self-test failed', <unittest.runner.TextTestResult run=22205 errors=1 failures=0>)
builder for ‘/nix/store/faz07c6m5ibqiby3s0r9msj0fmmdphix-python2.7-pycryptodome-3.4.7.drv’ failed with exit code 1                                                      
error: build of ‘/nix/store/faz07c6m5ibqiby3s0r9msj0fmmdphix-python2.7-pycryptodome-3.4.7.drv’ failed   
```

### Steps to reproduce

```
git checkout b17ec549a14a4b3fb8cdfff914afddd65fee942e
nix-build -A pythonPackages.pycryptodome
```

## Technical details

* System: `18.03.git.1b1fc65 (Impala)`
* Nix version: `nix-env (Nix) 1.11.14` (But this probably doesn't matter, since Nix from nixpkgs is used?)
* Nixpkgs version: `git describe HEAD`: `17.09-beta-3915-gb17ec549a1`
* Sandboxing enabled: yes

**Comment by shak-mar** [comment]
Same on `6991438df9669de5ff50f514025f89585b180771`.

**Comment by FRidh** [comment]
32-bit is no longer supported so I marked it as `wontfix`

**Comment by shak-mar** [comment]
Oh, that's sad news I didn't know yet... For the record, it's here: https://groups.google.com/d/topic/nix-devel/m7ikFjor24Y/discussion

Well, this renders Nix and NixOS completely useless to me (Since the only machine I run, except at work, is 32bit), so I'll probably switch away as soon as I find the time for it;  man, I don't like that fact, but that's how it is.  Having to build everything myself would suck enormously, but it would be manageable;  having to fix a soon-growing number of packages is a show-stopper.

Not blaming you though;  thanks for replying with that information.
