### ISSUE TITLE
Update request: galaxy-buds-client 4.5.4 → 5.1.0

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#306670]
- Package name: galaxy-buds-client
- Latest released version: 5.1.0

- Current version on the unstable channel: 4.5.4
- Current version on the stable/release channel: 4.5.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Icy-Thought

-----

Note for maintainers: Please tag this issue in your PR.

---
4.6.0 announces macos support, so maybe this package can add darwin

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Icy-Thought** [comment]
I'll get to it at some point this week or the week after. (very busy schedule)

But don't get your hopes up for the Darwin support, because I've never owned a Darwin based computer before.

**Comment by MisileLab** [comment]
I have macbook so maybe I can test package

**Comment by Icy-Thought** [comment]
So updating the file `version` and the `hash` and then using `fetch-deps` (did not work for me but someone else in the NixOS contribution matrix room sent the deps.nix file to me after tweaking with it) did not work. We wound up with the error provided below. Do note that both of us are not well versed in dotnet and therefore I personally lack the necessary information required to resolve this issue.

So external help would be very much desired at this point! Apologies for the inconvenience everyone.

Credits: Ghpzin (NixOS Contribution room)
https://gist.github.com/ghpzin/0f54d6e4b5dd6c4dfdc3fb756baf019e

```
[23:39:53 INF] Using settings file at: /home/icy-thought/.local/share/GalaxyBudsClient/config.json
[23:39:54 DBG] BluetoothImpl: Using Linux.BluetoothService
[23:39:54 INF] IpcService: Service listening on the session bus
[23:39:54 ERR] Unhandled exception in main thread
System.ArgumentException: An item with the same key has already been added. Key: /i18n/cn.xaml
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Avalonia.Platform.Internal.AssemblyDescriptor..ctor(Assembly assembly)
   at Avalonia.Platform.StandardAssetLoader..ctor(IAssemblyDescriptorResolver resolver, Assembly assembly)
   at Avalonia.Platform.StandardAssetLoader..ctor(Assembly assembly)
   at Avalonia.Platform.StandardRuntimePlatformServices.Register(Assembly assembly)
   at Avalonia.AppBuilder.<UseStandardRuntimePlatformSubsystem>b__63_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at GalaxyBudsClient.Program.Main(String[] args) in /build/source/GalaxyBudsClient/Program.cs:line 75

**Comment by MisileLab** [comment]
I resolved that error adding simple line
```nix
  postPatch = ''
    substituteInPlace "GalaxyBudsClient/GalaxyBudsClient.csproj" \
      --replace-fail '<AvaloniaVersion>11.1.999-cibuild0045273-beta</AvaloniaVersion>' '<AvaloniaVersion>11.1.0-beta1</AvaloniaVersion>'
    substituteInPlace "GalaxyBudsClient/GalaxyBudsClient.csproj" \
      --replace-fail '<AvaloniaResource Include="i18n\*" />' ""
  '';
```
I think it added twice from original code
[line 68](https://github.com/timschneeb/GalaxyBudsClient/blob/03742b2902d50a7f13b00c1450cf47298f60fc67/GalaxyBudsClient/GalaxyBudsClient.csproj#L68) and [line 76~78](https://github.com/timschneeb/GalaxyBudsClient/blob/03742b2902d50a7f13b00c1450cf47298f60fc67/GalaxyBudsClient/GalaxyBudsClient.csproj#L76-L78)
but I'm facing error that similar with https://github.com/NixOS/nixpkgs/issues/306671
~~I'm not english native, so my english is not good~~

**Comment by Icy-Thought** [comment]
I don't think the second `substituteInPlace` is a valid change considering how it creates another issue that we were not expecting.

Also, somehow the [flatpak package](https://github.com/flathub/me.timschneeberger.GalaxyBudsClient) is being built with only with the `AvaloniaVersion` patch.

**Comment by Sporesirius** [comment]
There is a new major version [5.0.0](https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0).
AFAIK there are no new dependencies, so maybe the effort to update to 4.6.0 can be used.

**Comment by Icy-Thought** [comment]
There is a semi complete commit in nh forked branch, but it fails at i18n due to it being imported twice. Haven't had the time to tinker with it tbh, but perhaps someone could expand on that PR?

**Comment by vigress8** [comment]
The error persists on 5.0.1 as well. I'm assuming it's Nix-specific since I couldn't find an issue that looked relevant in the upstream repo

**Comment by Icy-Thought** [comment]
Me neither and I am confused because I lack the required dotnet info for this PR to be merged. Maybe I should start fidgeting with it on my spare time.

**Comment by vigress8** [comment]
I think an issue should be opened upstream
