### ISSUE TITLE
protonup-qt 2.9.2 does not start

### ISSUE THREAD

**Issue by as3ii** [NixOS/nixpkgs#307019]
### Describe the bug
The latest (nixos unstable) build of protonup-qt (2.9.2) is broken:

```
Traceback (most recent call last):
  File "/nix/store/1vh3h8aphnl4a06a220fhi13fjy723qd-protonup-qt-2.9.2-extracted/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/1vh3h8aphnl4a06a220fhi13fjy723qd-protonup-qt-2.9.2-extracted/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/nix/store/1vh3h8aphnl4a06a220fhi13fjy723qd-protonup-qt-2.9.2-extracted/usr/lib/python3.10/site-packages/pupgui2/__main__.py", line 1, in <module>
    from pupgui2.pupgui2 import main
  File "/nix/store/1vh3h8aphnl4a06a220fhi13fjy723qd-protonup-qt-2.9.2-extracted/usr/lib/python3.10/site-packages/pupgui2/pupgui2.py", line 8, in <module>
    from PySide6.QtCore import Qt, QCoreApplication, QObject, QThread, QWaitCondition, QMutex, QDataStream
ImportError: libzstd.so.1: cannot open shared object file: No such file or directory
```

### Steps To Reproduce
1. add `protonup-qt` to the `configuration.nix`
2. run `nixos-rebuild switch`
3. run `protonup-qt`

### Expected behavior
`protonup-qt` starts without errors or crashes

### Notify maintainers
@michaelBelsanti @r-ryantm

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.7, NixOS, 24.05 (Uakari), 24.05.20240425.7bb2ccd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos, nixos-23.11-23.11"`
 - nixpkgs: `/nix/store/370qy3d3wg9zhbn5a3dcv6k1q1iigfh4-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by guttermonk** [comment]
I have protonup-qt 2.9.2 installed on stable 24.05, and it fails to start. Which version of nixos should this be working on?
