### ISSUE TITLE
Package request: rquickshare

### ISSUE THREAD

**Issue by HannesGitH** [NixOS/nixpkgs#307840]
**Project description**

quickshare is the airdrop equivalent for android and windows, and works there like a charm.
unfortunately there is no official linux-variant, but there is [rquickshare](https://github.com/Martichou/rquickshare), a working effort to get quickshare on linux. 

**Current best efforts [HELP NEEDED]**

But as stated in https://github.com/Martichou/rquickshare/issues/54 this is't yet packaged for nix.
I tried my best to get it working, but i cannot package the frontend with `mkYarnPackage` as it depends on `../core_lib`, all my efforts on getting that working can be seen in https://github.com/Martichou/rquickshare/pull/66. 

Any Help, maybe from the `yarn2nix` maintainers (which unfortunatly isnt given in nixpkgs) would be very appreciated.
It currently fails, since `../core_lib` depends on typescript which isnt in the yarn offline cache, although I also built it with `mkYarnPackage` and even tried to merge it into the offline cache as seen in the PR, with the following error:
```log
rquickshare-modules> yarn install v1.22.22
rquickshare-modules> [1/4] Resolving packages...
rquickshare-modules> error Couldn't find any versions for "typescript" that matches "^5.0.4" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
rquickshare-modules> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
rquickshare-modules> Error: Package "" refers to a non-existing file '"/build/deps/core_lib"'.
rquickshare-modules>     at MessageError.ExtendableBuiltin (/nix/store/v2rcrwzc7xsqxg9mzk9h7sxisr2v01xp-yarn-1.22.22/libexec/yarn/lib/cli.js:721:66)
rquickshare-modules>     at new MessageError (/nix/store/v2rcrwzc7xsqxg9mzk9h7sxisr2v01xp-yarn-1.22.22/libexec/yarn/lib/cli.js:750:123)
rquickshare-modules>     at FileResolver.<anonymous> (/nix/store/v2rcrwzc7xsqxg9mzk9h7sxisr2v01xp-yarn-1.22.22/libexec/yarn/lib/cli.js:50037:15)
rquickshare-modules>     at Generator.next (<anonymous>)
rquickshare-modules>     at step (/nix/store/v2rcrwzc7xsqxg9mzk9h7sxisr2v01xp-yarn-1.22.22/libexec/yarn/lib/cli.js:310:30)
rquickshare-modules>     at /nix/store/v2rcrwzc7xsqxg9mzk9h7sxisr2v01xp-yarn-1.22.22/libexec/yarn/lib/cli.js:321:13
```

**Metadata**

* homepage URL: https://github.com/Martichou/rquickshare
* source URL: https://github.com/Martichou/rquickshare
* license: gpl3
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by HannesGitH** [comment]
@spinus @moretea
* https://github.com/nix-community/yarn2nix/issues/122
* https://github.com/nix-community/yarn2nix/issues/2

**Comment by purepani** [comment]
I haven't worked a ton in the node ecosystem, but I vaguely remember there being a mkNpmWorkspace function or something if you want to try looking for that(though that might be my memory making that up) 
Unfortunately it looks like the node documentation isn't super great; I'd see if you can find another package that can package a dependency like this to see how it's done, because I'm sure this isn't the only one.

**Comment by purepani** [comment]
I just realized..is there a reason you're using the yarn tooling? The project uses pnpm, which there is currently no tooling for. In that case, you should probably try to use the normal npm tooling.

**Comment by HannesGitH** [comment]
> I just realized..is there a reason you're using the yarn tooling? The project uses pnpm, which there is currently no tooling for. In that case, you should probably try to use the normal npm tooling.

Well, yarn and pnpm are quick drop-in replacements for npm. All I need is bit-exact reproducible dependency fetching for the dependencies needed by the project. I opted for yarn, as the produced yarn.lock is precise enough to always fetch the exact same dependency and therefor already implemented in nixpkgs with yarn2nix
Idk if package-lock produced by (p)npm suffices for that use case, and even if it does it's harder, as I haven't find a solution that provides me all the fetched dependencies in a derivation like yarn2nix does.

But if anyone can tell me how to build a FOD (fixed output derivation) that has all the dependencies needed by the project **including the local, relative path one** I am happy, no matter if it uses pnpm, yarn or whatever. Sure it would even be better if it's pnpm as the project maintainer of rquickshare is already using that, but that's not necessary I'd say.

**Comment by purepani** [comment]
So, Im unsure how to deal with local deps; probably requires some sort of patching to the package.json. However, I will say that instead of using local deps, the "correct" thing to do would probably for upstream to use workspaces. However, because we don't have pnpm tooling, that wouldn't quite work for us atm since pnpm uses its own separate workspaces files rather than a field in the package.json, so we wouldn't be able to use the workspaces support that yarn2nix has.

With that knowledge here's what i would do, at least conceptually:
1. Make a derivation for the core_libs package separately. 
2.  Use the pkgConfig properly in mkYarnPackage to override the dependency to that derivation.

**Comment by purepani** [comment]
So, Im unsure how to deal with local deps; probably requires some sort of patching to the package.json. However, I will say that instead of using local deps, the "correct" thing to do would probably for upstream to use workspaces. However, because we don't have pnpm tooling, that wouldn't quite work for us atm since pnpm uses its own separate workspaces files rather than a field in the package.json, so we wouldn't be able to use the workspaces support that yarn2nix has.

With that knowledge here's what i would do, at least conceptually:
1. Make a derivation for the core_libs package separately. 
2.  Use the pkgConfig properly in mkYarnPackage to override the dependency to that derivation.

**Comment by HannesGitH** [comment]
> so we wouldn't be able to use the workspaces support that yarn2nix has.

is there some docs on that workspace support? so I might be able to edit upstream

> 1. Make a derivation for the core_libs package separately.

Done.

> 2. Use the pkgConfig property in mkYarnPackage to override the dependency to that derivation.

care to elaborate? I havent used that property yet, and i cannot see how that should be done.. , sorry

**Comment by purepani** [comment]
I don't think there is but yarn2nix is the only thing that supports it.

https://github.com/NixOS/nixpkgs/blob/master/doc%2Flanguages-frameworks%2Fjavascript.section.md
There's an example for how the pkgConfig property is used in there, but I *think* you can just replace it with the new derivation.

**Comment by HannesGitH** [comment]
> I don't think there is but yarn2nix is the only thing that supports it.
> 
> https://github.com/NixOS/nixpkgs/blob/master/doc%2Flanguages-frameworks%2Fjavascript.section.md There's an example for how the pkgConfig property is used in there, but I _think_ you can just replace it with the new derivation.
> 
> pkgConfig.core_libs = derivation

Okay, that works like a charm, thanks a lot

Now I'm stuck building the tauri-app but i think i wont try that soon unfortunately
