### ISSUE TITLE
Build failure: jd-cli

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#308260]
### Steps To Reproduce

1. build jd-cli

### Build log

```
Running phase: buildPhase
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.github.kwart.jd:build-tools:jar:1.2.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ line 11, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Build Tools                                                        [jar]
[INFO] jd-cli-root                                                        [pom]
[INFO] jd-lib                                                             [jar]
[INFO] jd-cli                                                             [jar]
[INFO] 
[INFO] ------------------< com.github.kwart.jd:build-tools >-------------------
[INFO] Building Build Tools 1.2.1                                         [1/4]
[INFO]   from build-tools/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ build-tools ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 3 resources from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ build-tools ---
[INFO] No sources to compile
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ build-tools ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /build/source/build-tools/src/test/resources
[INFO] 
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ build-tools ---
[INFO] No sources to compile
[INFO] 
[INFO] --- surefire:3.2.2:test (default-test) @ build-tools ---
[INFO] No tests to run.
[INFO] 
[INFO] --- jar:3.3.0:jar (default-jar) @ build-tools ---
[INFO] Building jar: /build/source/build-tools/target/build-tools-1.2.1.jar
[INFO] 
[INFO] ------------------< com.github.kwart.jd:jd-cli-root >-------------------
[INFO] Building jd-cli-root jd-cli-1.2.1                                  [2/4]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- checkstyle:3.1.2:checkstyle (check-style) @ jd-cli-root ---
[INFO] 
[INFO] ---------------------< com.github.kwart.jd:jd-lib >---------------------
[INFO] Building jd-lib 1.2.1                                              [3/4]
[INFO]   from jd-lib/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ jd-lib ---
[INFO] skip non existing resourceDirectory /build/source/jd-lib/src/main/resources
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ jd-lib ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 22 source files with javac [debug target 1.8] to target/classes
[WARNING] bootstrap class path not set in conjunction with -source 8
[WARNING] source value 8 is obsolete and will be removed in a future release
[WARNING] target value 8 is obsolete and will be removed in a future release
[WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
[INFO] 
[INFO] --- checkstyle:3.1.2:checkstyle (check-style) @ jd-lib ---
[WARNING] Old version of checkstyle detected. Consider updating to >= v8.30
[WARNING] For more information see: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html
[INFO] Starting audit...
Audit done.
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ jd-lib ---
[INFO] Copying 1 resource from src/test/resources to target/test-classes
[INFO] 
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ jd-lib ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 2 source files with javac [debug target 1.8] to target/test-classes
[WARNING] bootstrap class path not set in conjunction with -source 8
[WARNING] source value 8 is obsolete and will be removed in a future release
[WARNING] target value 8 is obsolete and will be removed in a future release
[WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
[INFO] /build/source/jd-lib/src/test/java/com/github/kwart/jd/JavaDecompilerTest.java: /build/source/jd-lib/src/test/java/com/github/kwart/jd/JavaDecompilerTest.java uses or overrides a deprecated API.
[INFO] /build/source/jd-lib/src/test/java/com/github/kwart/jd/JavaDecompilerTest.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- surefire:3.2.2:test (default-test) @ jd-lib ---
[INFO] Using auto detected provider org.apache.maven.surefire.junit4.JUnit4Provider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.github.kwart.jd.JavaDecompilerTest
12:06:13.093 DEBUG com.github.kwart.jd.input.DirInput - Initializing decompilation of directory target/test-classes
12:06:13.103 INFO  com.github.kwart.jd.output.DirOutput - Directory output will be initialized for path /tmp/junit4098663993388924434/flat
12:06:13.108 INFO  com.github.kwart.jd.output.DirOutput - Directory output will be initialized for path /tmp/junit4098663993388924434/struct
12:06:13.109 DEBUG com.github.kwart.jd.input.DirInput - Processing resource file target/test-classes/logback.xml
12:06:13.115 DEBUG com.github.kwart.jd.input.DirInput - Decompiling target/test-classes/com/github/kwart/jd/HelloWorld.class
12:06:13.118 DEBUG com.github.kwart.jd.JavaDecompiler - Decompiling class com/github/kwart/jd/HelloWorld
12:06:13.172 ERROR com.github.kwart.jd.JavaDecompiler - Can't decompile com/github/kwart/jd/HelloWorld
java.lang.NullPointerException: Cannot invoke "org.jd.core.v1.model.classfile.constant.ConstantUtf8.getValue()" because "cutf8" is null
        at org.jd.core.v1.model.classfile.ConstantPool.getConstantUtf8(ConstantPool.java:39)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadParameters(ClassFileDeserializer.java:568)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadAttributes(ClassFileDeserializer.java:281)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadMethods(ClassFileDeserializer.java:214)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadClassFile(ClassFileDeserializer.java:107)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.innerLoadClassFile(ClassFileDeserializer.java:41)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.innerLoadClassFile(ClassFileDeserializer.java:53)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadClassFile(ClassFileDeserializer.java:28)
        at org.jd.core.v1.service.deserializer.classfile.DeserializeClassFileProcessor.process(DeserializeClassFileProcessor.java:27)
        at org.jd.core.v1.ClassFileToJavaSourceDecompiler.decompile(ClassFileToJavaSourceDecompiler.java:53)
        at org.jd.core.v1.ClassFileToJavaSourceDecompiler.decompile(ClassFileToJavaSourceDecompiler.java:38)
        at com.github.kwart.jd.JavaDecompiler.decompileClass(JavaDecompiler.java:59)
        at com.github.kwart.jd.input.DirInput.processFile(DirInput.java:88)
        at com.github.kwart.jd.input.DirInput.processFile(DirInput.java:74)
        at com.github.kwart.jd.input.DirInput.processFile(DirInput.java:74)
        at com.github.kwart.jd.input.DirInput.processFile(DirInput.java:74)
        at com.github.kwart.jd.input.DirInput.processFile(DirInput.java:74)
        at com.github.kwart.jd.input.DirInput.decompile(DirInput.java:63)
        at com.github.kwart.jd.JavaDecompilerTest.basicTest(JavaDecompilerTest.java:72)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
12:06:13.173 WARN  com.github.kwart.jd.output.DirOutput - Class name or java source is null
12:06:13.173 WARN  com.github.kwart.jd.output.DirOutput - Class name or java source is null
12:06:13.174 DEBUG com.github.kwart.jd.input.DirInput - Decompiling target/test-classes/com/github/kwart/jd/JavaDecompilerTest.class
12:06:13.176 DEBUG com.github.kwart.jd.JavaDecompiler - Decompiling class com/github/kwart/jd/JavaDecompilerTest
12:06:13.656 INFO  com.github.kwart.jd.output.DirOutput - Finished with 1 class file(s) and 1 resource file(s) written.
12:06:13.656 INFO  com.github.kwart.jd.output.DirOutput - Finished with 1 class file(s) and 1 resource file(s) written.
12:06:13.684 DEBUG com.github.kwart.jd.input.DirInput - Initializing decompilation of directory target/test-classes
12:06:13.684 INFO  com.github.kwart.jd.output.DirOutput - Directory output will be initialized for path /tmp/junit11292705135612043189
12:06:13.684 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path logback.xml as it doesn't match the pattern .*Not.*Matching.*
12:06:13.684 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path com/github/kwart/jd/HelloWorld$StaticClass.class as it doesn't match the pattern .*Not.*Matching.*
12:06:13.685 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path com/github/kwart/jd/HelloWorld$PrivateClass.class as it doesn't match the pattern .*Not.*Matching.*
12:06:13.686 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path com/github/kwart/jd/HelloWorld$1.class as it doesn't match the pattern .*Not.*Matching.*
12:06:13.686 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path com/github/kwart/jd/HelloWorld.class as it doesn't match the pattern .*Not.*Matching.*
12:06:13.689 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path com/github/kwart/jd/JavaDecompilerTest$1.class as it doesn't match the pattern .*Not.*Matching.*
12:06:13.689 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path com/github/kwart/jd/JavaDecompilerTest.class as it doesn't match the pattern .*Not.*Matching.*
12:06:13.690 INFO  com.github.kwart.jd.output.DirOutput - Finished with 0 class file(s) and 0 resource file(s) written.
12:06:13.696 DEBUG com.github.kwart.jd.input.DirInput - Initializing decompilation of directory target/test-classes
12:06:13.701 INFO  com.github.kwart.jd.output.DirOutput - Directory output will be initialized for path /tmp/junit3467808805456869236
12:06:13.702 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path logback.xml as it doesn't match the pattern .*jd.Hello.*World\..*
12:06:13.703 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path com/github/kwart/jd/HelloWorld$StaticClass.class as it doesn't match the pattern .*jd.Hello.*World\..*
12:06:13.704 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path com/github/kwart/jd/HelloWorld$PrivateClass.class as it doesn't match the pattern .*jd.Hello.*World\..*
12:06:13.705 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path com/github/kwart/jd/HelloWorld$1.class as it doesn't match the pattern .*jd.Hello.*World\..*
12:06:13.705 DEBUG com.github.kwart.jd.input.DirInput - Decompiling target/test-classes/com/github/kwart/jd/HelloWorld.class
12:06:13.705 DEBUG com.github.kwart.jd.JavaDecompiler - Decompiling class com/github/kwart/jd/HelloWorld
12:06:13.707 ERROR com.github.kwart.jd.JavaDecompiler - Can't decompile com/github/kwart/jd/HelloWorld
java.lang.NullPointerException: Cannot invoke "org.jd.core.v1.model.classfile.constant.ConstantUtf8.getValue()" because "cutf8" is null
        at org.jd.core.v1.model.classfile.ConstantPool.getConstantUtf8(ConstantPool.java:39)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadParameters(ClassFileDeserializer.java:568)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadAttributes(ClassFileDeserializer.java:281)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadMethods(ClassFileDeserializer.java:214)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadClassFile(ClassFileDeserializer.java:107)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.innerLoadClassFile(ClassFileDeserializer.java:41)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.innerLoadClassFile(ClassFileDeserializer.java:53)
        at org.jd.core.v1.service.deserializer.classfile.ClassFileDeserializer.loadClassFile(ClassFileDeserializer.java:28)
        at org.jd.core.v1.service.deserializer.classfile.DeserializeClassFileProcessor.process(DeserializeClassFileProcessor.java:27)
        at org.jd.core.v1.ClassFileToJavaSourceDecompiler.decompile(ClassFileToJavaSourceDecompiler.java:53)
        at org.jd.core.v1.ClassFileToJavaSourceDecompiler.decompile(ClassFileToJavaSourceDecompiler.java:38)
        at com.github.kwart.jd.JavaDecompiler.decompileClass(JavaDecompiler.java:59)
        at com.github.kwart.jd.input.DirInput.processFile(DirInput.java:88)
        at com.github.kwart.jd.input.DirInput.processFile(DirInput.java:74)
        at com.github.kwart.jd.input.DirInput.processFile(DirInput.java:74)
        at com.github.kwart.jd.input.DirInput.processFile(DirInput.java:74)
        at com.github.kwart.jd.input.DirInput.processFile(DirInput.java:74)
        at com.github.kwart.jd.input.DirInput.decompile(DirInput.java:63)
        at com.github.kwart.jd.JavaDecompilerTest.patternMatchingTest(JavaDecompilerTest.java:94)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
12:06:13.713 WARN  com.github.kwart.jd.output.DirOutput - Class name or java source is null
12:06:13.716 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path com/github/kwart/jd/JavaDecompilerTest$1.class as it doesn't match the pattern .*jd.Hello.*World\..*
12:06:13.717 DEBUG c.g.k.jd.input.AbstractFileJDInput - Skipping the path com/github/kwart/jd/JavaDecompilerTest.class as it doesn't match the pattern .*jd.Hello.*World\..*
12:06:13.717 INFO  com.github.kwart.jd.output.DirOutput - Finished with 0 class file(s) and 0 resource file(s) written.
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.672 s <<< FAILURE! -- in com.github.kwart.jd.JavaDecompilerTest
[ERROR] com.github.kwart.jd.JavaDecompilerTest.basicTest -- Time elapsed: 1.344 s <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at com.github.kwart.jd.JavaDecompilerTest.assertDecompiled(JavaDecompilerTest.java:100)
        at com.github.kwart.jd.JavaDecompilerTest.basicTest(JavaDecompilerTest.java:73)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

[ERROR] com.github.kwart.jd.JavaDecompilerTest.patternMatchingTest -- Time elapsed: 0.033 s <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at com.github.kwart.jd.JavaDecompilerTest.assertDecompiled(JavaDecompilerTest.java:100)
        at com.github.kwart.jd.JavaDecompilerTest.patternMatchingTest(JavaDecompilerTest.java:95)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JavaDecompilerTest.basicTest:73->assertDecompiled:100
[ERROR]   JavaDecompilerTest.patternMatchingTest:95->assertDecompiled:100
[INFO] 
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Build Tools 1.2.1 .................................. SUCCESS [  3.993 s]
[INFO] jd-cli-root jd-cli-1.2.1 ........................... SUCCESS [  2.423 s]
[INFO] jd-lib 1.2.1 ....................................... FAILURE [ 10.000 s]
[INFO] jd-cli 1.2.1 ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.769 s
[INFO] Finished at: 2024-05-01T12:06:13Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.2:test (default-test) on project jd-lib: There are test failures.
[ERROR] 
[ERROR] Please refer to /build/source/jd-lib/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jd-lib

error: builder for '/nix/store/4lm2cxrwkv63z7lpancsn70dlf51msaw-jd-cli-1.2.1.drv' failed with exit code 1;
       last 10 log lines:
       > [ERROR]
       > [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
       > [ERROR] Re-run Maven using the -X switch to enable full debug logging.
       > [ERROR]
       > [ERROR] For more information about the errors and possible solutions, please read the following articles:
       > [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
       > [ERROR]
       > [ERROR] After correcting the problems, you can resume the build with the command
       > [ERROR]   mvn <args> -rf :jd-lib
       > 
       For full logs, run 'nix log /nix/store/4lm2cxrwkv63z7lpancsn70dlf51msaw-jd-cli-1.2.1.drv'.
```

### Notify maintainers

@Majiir 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05pre617818.58a1abdbae32`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager, nixos, nixpkgs"`
 - nixpkgs: `/home/athena/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by applePrincess** [comment]
https://hydra.nixos.org/eval/1808691 seems as if it builds on hydra and I can confirm it builds on the current HEAD. Could you check that?

**Comment by D3vil0p3r** [comment]
Should I rebuild it?

**Comment by applePrincess** [comment]
Yep! And if it builds successfully, close this issue please.

**Comment by D3vil0p3r** [comment]
By `nix-shell -p jd-cli`, it seems to work correctly. Thanks
