### ISSUE TITLE
Problem using SWT with 

### ISSUE THREAD

**Issue by bbarker** [NixOS/nixpkgs#30826]
## Issue description

When I run an SWT java app using nixpkg's OpenJDK from IntelliJ's run dialog, I get the following error:

```
/nixenv/brandon/JDK/bin/java -javaagent:/nix/store/irl7vpgswq7gl840w5z90k65j6hqbi6p-idea-local/idea-IU-172.4343.14/lib/idea_rt.jar=34273:/nix/store/irl7vpgswq7gl840w5z90k65j6hqbi6p-idea-local/idea-IU-172.4343.14/bin -Dfile.encoding=UTF-8 -classpath  ...
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi-gtk-4528 in java.library.path
	no swt-pi-gtk in java.library.path
	/home/brandon/.swt/lib/linux/x86_64/libswt-pi-gtk-4528.so: libXtst.so.6: cannot open shared object file: No such file or directory
	Can't load library: /home/brandon/.swt/lib/linux/x86_64/libswt-pi-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
	at edu.cornell.ansci.dairy.econ.ui.MainWindow$.main(MainWindow.scala:176)
	at edu.cornell.ansci.dairy.econ.ui.MainWindow.main(MainWindow.scala)
```

When I run the app with Zulu's OpenJDK instead I get a similar error but for a different library:

```
/usr/lib/jvm/zulu-8-amd64/bin/java -javaagent:/nix/store/irl7vpgswq7gl840w5z90k65j6hqbi6p-idea-local/idea-IU-172.4343.14/lib/idea_rt.jar=41147:/nix/store/irl7vpgswq7gl840w5z90k65j6hqbi6p-idea-local/idea-IU-172.4343.14/bin -Dfile.encoding=UTF-8 -classpath ...
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi-gtk-4528 in java.library.path
	no swt-pi-gtk in java.library.path
	/home/brandon/.swt/lib/linux/x86_64/libswt-pi-gtk-4528.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
	Can't load library: /home/brandon/.swt/lib/linux/x86_64/libswt-pi-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
	at edu.cornell.ansci.dairy.econ.ui.MainWindow$.main(MainWindow.scala:176)
	at edu.cornell.ansci.dairy.econ.ui.MainWindow.main(MainWindow.scala)

```
### Steps to reproduce

I'm not exactly sure: I could supply my dockerfile which has my nix environment, but the application itself is closed source for now - I suspect any SWT app would work as a suitable test, though.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

* Nix version: (run `nix-env --version`): `nix-env (Nix) 1.11.14`

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
warning: Nix search path entry ‘/nix/var/nix/profiles/per-user//nixenv/brandon/channels/’ does not exist, ignoring
"18.03pre118061.69607d7662"
```
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by bbarker** [comment]
I guess patchelf might be a solution - I assume java.exe is what would need to be patched?

**Comment by NilsIrl** [comment]
If you want an app to test this on, try [openaudible](https://github.com/openaudible/openaudible).

**Comment by NilsIrl** [comment]
@bbarker 

Here's the solution:
```bash
$ java -Djava.library.path=/nix/store/x0a0zfj8shw2fdy4drzyaf4bw9qyc597-swt-4.5/lib -cp "target/openaudible-jar-with-dependencies.jar:/nix/store/x0a0zfj8shw2fdy4drzyaf4bw9qyc597-swt-4.5/jars/swt.jar" org.openaudible.desktop.Application
```

An example can be found here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/p2p/vuze/default.nix

**Comment by petabyteboy** [comment]
To get the path for the current swt package:

```
$ java -Djava.library.path=$(nix-build --no-out-link "<nixpkgs>" -A swt)/lib/ -cp "target/openaudible-jar-with-dependencies.jar:$(nix-build --no-out-link "<nixpkgs>" -A swt)/jars/swt.jar" org.openaudible.desktop.Application
```

I'll close this, if this is still an issue please comment.
