### ISSUE TITLE
Build failure: clojure-lsp

### ISSUE THREAD

**Issue by Ramblurr** [NixOS/nixpkgs#308790]
Hi folks,

I saw that clojure-lsp was out of date I tried to build the new version (2024.04.22-11.50.26)

Unfortunately after bumping the version and fixing the hashes, we have a build error. Specifically the version check that was recently added is failing.

### Steps To Reproduce

1. build clojure-lsp with version `2024.04.22-11.50.26` (see https://github.com/Ramblurr/nixpkgs/commit/832b07ac1c7d6bdef5598442e13e6d753b1ef160)

### Build log

Full build log: http://0x0.st/XXWG.log

```
...snip...
Finished generating 'clojure-lsp' in 19.8s.
@nix { "action": "setPhase", "phase": "checkPhase" }
Running phase: checkPhase
Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.lang.Namespace.<init>(Namespace.java:34)
	at clojure.lang.Namespace.findOrCreate(Namespace.java:176)
	at clojure.lang.Var.internPrivate(Var.java:156)
	at clojure_lsp.main.<clinit>(Unknown Source)
	at java.base@22/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:285)
	at java.base@22/java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:335)
Caused by: java.io.FileNotFoundException: Could not locate clojure/core__init.class, clojure/core.clj or clojure/core.cljc on classpath.
	at clojure.lang.RT.load(RT.java:462)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.lang.RT.<clinit>(RT.java:338)
	... 6 more
```

### Notify maintainers

@ericdallo @babariviere @jcf 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.29, NixOS, 24.05 (Uakari), 24.05.20240502.63c3a29`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/p69bcs7ma6ijj8v9xsrg3nq3nn8ryn95-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mnikkel** [comment]
Adding "--features=clj_easy.graal_build_time.InitClojureClasses" to extraNativeImageBuildArgs seems to fix it. I found that in the [clojure-lsp repo](https://github.com/clojure-lsp/clojure-lsp/blob/0ac5e4965bf59426c44bbcec5d3f65ba59e2b81d/cli/build.clj#L144).
