### ISSUE TITLE
Package request: carburetor

### ISSUE THREAD

**Issue by Thatoo** [NixOS/nixpkgs#308739]
**Project description**

Carburetor isn’t your just average app — it’s a sleek graphical interface carefully crafted for [Tractor](https://tractor.frama.io/tractor), using the cutting-edge [GTK4](https://docs.gtk.org/gtk4) and [Libadwaita](https://gnome.pages.gitlab.gnome.org/libadwaita) tech. Initially aimed at simplifying life for GNOME enthusiasts on their mobiles, Carburetor’s magic isn’t limited to small screens. Surprise! Desktop users, you’re in luck too. Carburetor lets you set up a TOR proxy hassle-free, without getting your hands dirty with system files.

**Metadata**

* homepage URL: https://tractor.frama.io/carburetor/
* source URL: https://framagit.org/tractor/carburetor
* license: gplv3
* platforms:  linux
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mksafavi** [comment]
I took a stab at this. It depends on a cli app called `tractor` that's not in the nixpkgs as well.
It's not complete yet. I'll send a draft PR.

have you used it on another distro?

I get this error while running it:
```
Traceback (most recent call last):
  File "/nix/store/fs3k5s2f2nryipy4d6vgn7qwlijj8l37-carburetor-4.5.1/bin/.carburetor-wrapped", line 6, in <module>
    from carburetor.carburetor import main
  File "/nix/store/fs3k5s2f2nryipy4d6vgn7qwlijj8l37-carburetor-4.5.1/lib/python3.11/site-packages/carburetor/carburetor.py", line 13, in <module>
    gi.require_versions({"Adw": "1", "Gtk": "4.0"})
  File "/nix/store/40cddha2iiqzbqd6dpal3rlrgvb4p0yc-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/__init__.py", line 145, in require_versions
    require_version(module_name, module_version)
  File "/nix/store/40cddha2iiqzbqd6dpal3rlrgvb4p0yc-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Adw not available
```

**Comment by Thatoo** [comment]
No, sorry. I hope to be able to get a tor web-browser on my nixos phone (arm).

**Comment by mksafavi** [comment]
> No, sorry. I hope to be able to get a tor web-browser on my nixos phone (arm).

cool 👍
I'll try it again in the weekend to see if I can get it working.

btw, are these the only devices supported by nixos mobile? https://mobile.nixos.org/devices/

**Comment by Thatoo** [comment]
I guess but I'm not sure.
I'm trying on the very oldd original Pinephone and works very well. I'm very impressed, it's smoother than mobian.

**Comment by danialbehzadi** [comment]
> I get this error while running it:
> 
> ```
> Traceback (most recent call last):
>   File "/nix/store/fs3k5s2f2nryipy4d6vgn7qwlijj8l37-carburetor-4.5.1/bin/.carburetor-wrapped", line 6, in <module>
>     from carburetor.carburetor import main
>   File "/nix/store/fs3k5s2f2nryipy4d6vgn7qwlijj8l37-carburetor-4.5.1/lib/python3.11/site-packages/carburetor/carburetor.py", line 13, in <module>
>     gi.require_versions({"Adw": "1", "Gtk": "4.0"})
>   File "/nix/store/40cddha2iiqzbqd6dpal3rlrgvb4p0yc-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/__init__.py", line 145, in require_versions
>     require_version(module_name, module_version)
>   File "/nix/store/40cddha2iiqzbqd6dpal3rlrgvb4p0yc-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/__init__.py", line 122, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace Adw not available
> ```

It uses `libadwaita`, so you need it to be present.
