### ISSUE TITLE
zodb-5.3.0 broken on master (python35, python36)

### ISSUE THREAD

**Issue by ckauhaus** [NixOS/nixpkgs#30892]
## Issue description

I tried to build python35Packages.zodb and python36Packages.zodb but without success. Relevant part of the error message:

```
running build_ext
Traceback (most recent call last):
  File "nix_run_setup.py", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 149, in <module>
    python_requires='>=2.7,!=3.0.*,!=3.1.*,!=3.2.*',
  File "/nix/store/2mza45s5l0524l86d1ky176j4byz6wia-python3-3.5.4/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
[...]
  File "setup.py", line 88, in alltests
    _unittests_only(suite, mod.test_suite())
AttributeError: module 'ZODB.tests.test_mvccadapter' has no attribute 'test_suite'
builder for ‘/nix/store/xxplkgs0gab6z40c57kmc03mixdsa743-python3.5-ZODB-5.3.0.drv’ failed with exit code 1
```

Tried to do it on current master.

### Steps to reproduce

nix-build -I nixpkgs=. -A pkgs.python36Packages.zodb

## Technical details

* System: Local nixpkgs checkout eb3f736 on Gentoo
* Nix version: 1.11.15
* Nixpkgs version: 17.09.1880.ac2bb5684c
* Sandboxing enabled: true

**Comment by ckauhaus** [comment]
Same problem on a native NixOS machine.
