### ISSUE TITLE
Trying to package Manager.io

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#30926]
I'm trying to package Manager which is built ontop of Mono.

They are now distributing versioned debian archives. It's debian information is:

```
[nix-shell:~/Projects/manager]$ dpkg -I ./Manager.deb 
 new debian package, version 2.0.
 size 8167230 bytes: control archive=1586 bytes.
     561 bytes,    13 lines      control              
    2440 bytes,    31 lines      md5sums              
 Package: manager-accounting
 Version: 17.10.66
 Architecture: amd64
 Maintainer: Lubos Hasko <lubos@luboshasko.com>
 Installed-Size: 19790
 Depends: libc6 (>= 2.14), mono-runtime, libmono-system-xaml4.0-cil, mono-devel, libgtk2.0-cil-dev, libwebkit1.1-cil
 Section: misc
 Priority: extra
 Homepage: http://www.manager.io/
 Description: Accounting software
  Manager is free accounting software for Ubuntu. It features an intuitive
  and innovative user interface with modules such as cashbook, invoicing,
  receivables, payables, taxes and comprehensive financial reports.
```

It relies on the mono-runtime and mono-devel, which I think is provided by `mono` package, and the `libgtk2.0-cil-dev` which I think is supplied by `gtk-sharp-2_0`. However the other dependencies, I'm not sure about. That is `libmono-system-xaml4.0-cil`, and `libwebkit1.1-cil`. I think the `libwebkit1.1-cil` should be provided by a `webkit-sharp` package, but nobody has done this yet.

My only reference for how to do this would be: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/tomboy/default.nix

But I'm not sure how difficult it is to get libwebkit-sharp packaged since libwebkit doesn't even exist in nixpkgs at the moment?

Is the xaml dependency available as well, or already part of the mono package?

Also what's the difference between `*-sharp` packages and `dotnetPackages.*` packages?

**Comment by CMCDragonkai** [comment]
Since I posted this last year, Manager has been updated.

Now when you download the source package: https://d2ap5zrlkavzl7.cloudfront.net/18.11.5/manager-accounting.zip

You can see that its debian files state that its dependencies are now:

```
Depends: libc6 (>= 2.14), mono-runtime, mono-devel, libgtk3.0-cil, libwebkit2gtk-4.0-37
```

This is alot easier as now Nixpkgs has al l these dependencies.

* `libgtk3.0-cil` - https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/gtk-sharp/3.0.nix
* `libwebkit2gtk-4.0-37` - https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/webkitgtk

However currently `libgtk3.0-cil` is marked as broken, so it won't be possible to use at this moment.

As a side note:

The `manager-accounting` that is being executed is a shell script inside `/opt/manager-accounting/manager-accounting`. The shell script uses the `cli` which is the common language infrastructure interpreter and calls the `/opt/manager-accounting/ManagerDesktop.exe`. I'm guessing we have the same issue when using the `ManagerServer.exe` as well. And we can expose both. And that's a PE32 executable GUI for MS Windows.

**Comment by CMCDragonkai** [comment]
In Debian they have "packages" and "source packages". For example `libgtk3.0-cil` is a "package" that is based off a source package called `gtk-sharp3`. In Nixpkgs, we do not have this difference, we have packages and derivations. But we name them the same thing (even `src` is itself a derivation of some sort). So when a Debian package wants `libgtk3.0-cil`, you look this up and find that Debian says it is based on a source package called `gtk-sharp3`. Then you can search Nixpkgs for something that looks like `gtk-sharp3`.

**Comment by CMCDragonkai** [comment]
Manager.io is now an app image.

I've followed the nixpkgs manual to wrap it.

```nix
  manager = self.appimageTools.wrapType2 {
    name = "manager";
    src = self.fetchurl {
      url = "https://github.com/Manager-io/Manager.AppImage/releases/download/21.11.58/Manager-x64.AppImage";
      sha256 = "17vxy69ifdxdm2ylfhc3vqmlya4szjszg4kb539kp1mj147mmxr2";
    };
    extraPkgs = pkgs: with pkgs; [ icu webkit2-sharp webkitgtk ];
  };
```

This gives us an executable that doesn't complain but produces a blank screen.

```
»» /nix/store/l0ld2xkizlirb2bv13xwb3p9xr8lcddz-manager/bin
 ♜ ./manager                                                                                                 pts/4 19:32:36
Gtk-Message: 19:32:38.093: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 19:32:38.094: Failed to load module "colorreload-gtk-module"
Gtk-Message: 19:32:38.330: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 19:32:38.330: Failed to load module "colorreload-gtk-module"
```

Not sure what's missing here.

**Comment by CMCDragonkai** [comment]
Shooting in the dark, but still no luck:

```nix
  manager = self.appimageTools.wrapType2 {
    name = "manager";
    src = self.fetchurl {
      url = "https://github.com/Manager-io/Manager.AppImage/releases/download/21.11.58/Manager-x64.AppImage";
      sha256 = "17vxy69ifdxdm2ylfhc3vqmlya4szjszg4kb539kp1mj147mmxr2";
    };
    extraPkgs = pkgs: with pkgs; [ icu webkit2-sharp webkitgtk gtk-sharp-3_0 gtk3 mono ];
  };
```

**Comment by CMCDragonkai** [comment]
Recent attempt!

```
»» ~/Downloads
 ♖ nix-shell -p appimage-run                              ⚡(master) pts/3 8:49:28

[nix-shell:~/Downloads]$ appimage-run ./Manager-linux-x64.AppImage 
Uncompress Manager-linux-x64.AppImage of type 02 @ offset 594264
[===================================================================|] 863/863 100%
Manager-linux-x64.AppImage is now installed in /home/cmcdragonkai/.cache/appimage-run/a31f1a257d112e75841c6aa6a86cab75f3f18bcf39a34583bb97295049c9653d
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at System.Reflection.AssemblyName..ctor(System.Reflection.NativeAssemblyNameParts*)
   at System.RuntimeTypeHandle.GetTypeByName(System.String, Boolean, Boolean, System.Runtime.CompilerServices.StackCrawlMarkHandle, System.Runtime.CompilerServices.ObjectHandleOnStack, System.Runtime.CompilerServices.ObjectHandleOnStack, System.Runtime.CompilerServices.ObjectHandleOnStack)
   at System.RuntimeTypeHandle.GetTypeByName(System.String, Boolean, Boolean, System.Threading.StackCrawlMark ByRef, System.Runtime.Loader.AssemblyLoadContext)
   at System.Type.GetType(System.String)
   at Eto.OperatingSystemPlatform..ctor()
   at Eto.EtoEnvironment.get_Platform()
   at Eto.Platform.get_Detect()
   at Eto.Forms.Application..ctor()
   at ManagerDesktop.Program.Main(System.String[])
/home/cmcdragonkai/.cache/appimage-run/a31f1a257d112e75841c6aa6a86cab75f3f18bcf39a34583bb97295049c9653d/AppRun: line 4:    72 Aborted                 (core dumped) ${HERE}/opt/manager/ManagerDesktop
```

How does one use `appimage-run` with additional libraries? I think I already know about `icu` above.

**Comment by tomodachi94** [comment]
> How does one use `appimage-run` with additional libraries? I think I already know about `icu` above.

I'd approach this by extracting the AppImage (`./Manager-linux-x64.AppImage --appimage-extract`) and then using `autoPatchelfHook`.

**Comment by CMCDragonkai** [comment]
There's still a missing library dependency though.

**Comment by tomodachi94** [comment]
You can use this command from the `patchelf` package to determine what dependencies are needed by the binary. (Upstreams occasionally don't list some libraries assumed to be available on all machines):
```
patchelf --print-needed path/to/binary/in-extracted/manager
```

**Comment by CMCDragonkai** [comment]
> This seems to be working for me:
> 
> ```
> { config, pkgs, lib, ... }:
> 
> let
>   managerServer = pkgs.stdenv.mkDerivation rec {
>     pname = "ManagerServer";
>     version = "{{ args['app_template_args']['managerserver_version'] }}";
> 
>     src = pkgs.fetchurl {
>       url = "https://github.com/Manager-io/Manager/releases/download/{{ args['app_template_args']['managerserver_version'] }}/ManagerServer-linux-x64.tar.gz";
>       hash = "{{ args['app_template_args']['managerserver_hash'] }}";
>     };
> 
>     buildInputs = [ pkgs.patchelf pkgs.dotnet-runtime_8 ];
> 
>     unpackPhase = ''
>       # Create the destination directory and move everything there
>       mkdir -p $out
>       tar -xzf $src -C $out
>     '';
> 
>     installPhase = let
>       # we prepare our library path in the let clause to avoid it becoming part of the input of mkDerivation
>       rpath = lib.makeLibraryPath [
>         pkgs.stdenv.cc.cc # Correct reference for libgcc
>         pkgs.icu # Globalization support
>         pkgs.openssl # SSL support
>       ];
>     in ''
>       # Apply patchelf
>       patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" \
>                --set-rpath "${rpath}" $out/ManagerServer
> 
>       # Create bin directory
>       mkdir -p $out/bin
> 
>       # Create a wrapper script in $out/bin
>       cat > $out/bin/ManagerServer <<EOF
>       #!${pkgs.bash}/bin/bash
>       cd $out
>       exec ./ManagerServer "\$@"
>       EOF
> 
>       chmod +x $out/bin/ManagerServer
>     '';
> 
>     # Optionally, you can set executable permissions
>     meta = {
>       description = "ManagerServer (manager.io) Accounting Software";
>       homepage = "https://manager.io/server";
>       license = pkgs.lib.licenses.unfree; # Adjust license as appropriate
>     };
>   };
> in
> {
>   nixpkgs.config.allowUnfree = true;
>   environment.systemPackages = with pkgs; [
>     managerServer
>   ];
> 
>   users.groups.managerserver.gid = 9002;
> 
>   users.users.managerserver = {
>     uid = 9002;
>     group = "managerserver";
>     isSystemUser = true;
>     description = "ManagerServer User";
>     home = "/var/lib/managerserver";
>     createHome = true;
>   };
> 
>   systemd.services.managerServer = {
>     description = "ManagerServer Service";
>     after = [ "network.target" ];
>     wantedBy = [ "multi-user.target" ];
> 
>     serviceConfig = {
>       User = "managerserver";
>       Group = "managerserver";
>       ExecStart = "${managerServer}/bin/ManagerServer -path /var/lib/managerserver -port 8080";
>       WorkingDirectory = "/var/lib/managerserver";
>       Restart = "always";
>       RestartSec = "5s";
>       Environment = [
>         "ASPNETCORE_ENVIRONMENT=Production"
>         "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0"
>         "LD_LIBRARY_PATH=${lib.makeLibraryPath [ pkgs.icu pkgs.openssl ]}"
>       ];
>       ReadWritePaths = [ "/var/lib/managerserver" ];
>     };
>   };
> ```
> 
> This gets templated with jinja2 before it's deployed onto the server, so, the version and hash that are surrounded in `{{ ... }}` should be replaced with the version and the hash you want.

That's cool, I realise the desktop app is just a browser wrapper looking at the server. Is that something you could submit a PR to nixpkgs for?

**Comment by CMCDragonkai** [comment]
So I got a proper derivation for this, and it works. This can be submitted to Nixpkgs proper under `ManagerServer/default.nix` somewhere.

```nix
{ lib
, stdenvNoCC
, fetchurl
, patchelf
, makeWrapper
, bash
, icu
, openssl
, zlib
, stdenv
}:

let
  pname = "manager-server";
  version = "25.12.21.3153";

  arch =
    if stdenvNoCC.hostPlatform.isAarch64 then "arm64"
    else if stdenvNoCC.hostPlatform.isx86_64 then "x64"
    else throw "Unsupported platform: ${stdenvNoCC.hostPlatform.system}";

  src = fetchurl {
    url = "https://github.com/Manager-io/Manager/releases/download/${version}/ManagerServer-linux-${arch}.tar.gz";
    hash = "sha256-JbdFJzFOdik2bfp6xNIOPi50Vru8YAqskSqX+a2fJ/4=";
  };

  rpath = lib.makeLibraryPath [
    stdenv.cc.cc
    icu
    openssl
    zlib
  ];
in
stdenvNoCC.mkDerivation {
  inherit pname version src;

  nativeBuildInputs = [ patchelf makeWrapper ];
  # Important: don't let generic fixups strip/patch more than we intend.
  dontStrip = true;
  dontPatchELF = true;

  unpackPhase = "true";

  installPhase = ''
    runHook preInstall

    mkdir -p "$out/libexec/${pname}"
    tar -xzf "$src" -C "$out/libexec/${pname}"

    chmod +x "$out/libexec/${pname}/ManagerServer"

    runHook postInstall
  '';

  postFixup = ''
    appDir="$out/libexec/${pname}"
    bin="$appDir/ManagerServer"

    patchelf --set-interpreter "$(cat ${stdenv.cc}/nix-support/dynamic-linker)" "$bin"
    patchelf --set-rpath "${rpath}" "$bin"

    mkdir -p "$out/bin"

    # Primary entrypoint matches upstream name
    makeWrapper "$bin" "$out/bin/ManagerServer" \
      --set ASPNETCORE_ENVIRONMENT Production \
      --set DOTNET_SYSTEM_GLOBALIZATION_INVARIANT 0 \
      --prefix LD_LIBRARY_PATH : "$appDir:${rpath}"
  '';

  meta = with lib; {
    description = "Manager.io Server Edition (ManagerServer)";
    homepage = "https://www.manager.io/server-edition";
    license = licenses.unfree;
    platforms = [ "x86_64-linux" "aarch64-linux" ];
    mainProgram = "ManagerServer";
  };
}
```
