### ISSUE TITLE
Add a way to add/modify devices in libratbag

### ISSUE THREAD

**Issue by ImUrX** [NixOS/nixpkgs#309453]
Currently libratbag hasn't made a new release in a while and I have a Logitech mouse that is supported but isn't in the list (libratbag/libratbag#1389) so it would be nice to have a way to add devices manually

I guess the alternative would be to overrideAttrs of the package and make a new one and manually add it to systemd as the service.ratbagd doesn't add a way to modify the package.

**Comment by tomodachi94** [comment]
Pinging @mvnetbiz, who appears to have created the module and maintains the package.

**Comment by captainepoch** [comment]
I just tested this with my current device, which I'm trying to add to `libratbag`, and it doesn't work.

Also, the nix file of libratbag doesn't seem to work properly, as I get this error if I try to execute `ratbagctl`:

```
Traceback (most recent call last):
  File "/run/current-system/sw/bin/ratbagctl", line 40, in <module>
    from gi.repository import Gio, GLib, GObject
  File "/nix/store/czg030czd0sc7vmwjf71afhd9zskf5n2-python3-3.11.9-env/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Gio, introspection typelib not found
```

I'm trying to compile it from master as this:

```
{ config, lib, pkgs, ... }:

let
  libratbag = pkgs.libratbag.overrideAttrs (oldAttrs: {
    version = "1c9662043f4a11af26537e394bbd90e38994066a";
    src = pkgs.fetchFromGitHub {
      owner = "libratbag";
      repo = "libratbag";
      rev = "1c9662043f4a11af26537e394bbd90e38994066a";
      sha256 = "sha256-IpN97PPn9p1y+cAh9qJAi5f4zzOlm6bjCxRrUTSXNqM=";
    };
  });

  piper = pkgs.piper.overrideAttrs (oldAttrs: {
    version = "efa2712fcbc4ac1e9e9d1a7a85334c2a5dc9bab4";
    src = pkgs.fetchFromGitHub {
      owner = "libratbag";
      repo = "piper";
      rev = "efa2712fcbc4ac1e9e9d1a7a85334c2a5dc9bab4";
      sha256 = "0jsvfy0ihdcgnqljfgs41lys1nlz18qvsa0a8ndx3pyr41f8w8wf";
    };
  });
in {
  environment.systemPackages = with pkgs; [
    libratbag
    piper
    usbutils
    (pkgs.writeTextDir "share/libratbag/steelseries-prime.device" ''
      # G102, G103 and G203 (USB)
      [Device]
      Name=SteelSeries Prime
      DeviceMatch=usb:1038:182e
      Driver=steelseries
      DeviceType=mouse

      [Driver/steelseries]
      DeviceVersion=1
      Buttons=6
      Leds=1
      DpiList=100:18000@100
      MacroLength=0
    '')
  ];

  services.dbus.packages = [ pkgs.libratbag ];
  services.ratbagd = { enable = true; };
}
```

**Comment by mvnetbiz** [comment]
That error should be fixed by this PR. https://github.com/NixOS/nixpkgs/pull/316717

**Comment by captainepoch** [comment]
Then I don't know if I'm doing anything wrong with my way of installing it from the latest master commit.

**Comment by captainepoch** [comment]
@mvnetbiz Sorry for the doble comment, but in master, the changes of that commit aren't applied.

**Comment by TheWrongMensch** [comment]
Hi, I have tried the config from mvnetbiz and if I run ratbag in verbose mode (sudo ratbagd --verbose=raw) I get the following output:

```
ratbag debug: New device: Logitech PRO 2 MOUSE
ratbag debug: Using data directory '/nix/store/bh3cp4ihyqmcyikb5lc9475bsybmb6bb-libratbag-0.18/share/libratbag'
ratbag debug: No data file found for 046d:40a8
``` 
but the file created via writeTextDir is in /nix/store/cgx4xnmaf84f7ra2a6ybn6l2z2waqgfz-logitech-pro-2-lightspeed.device

how can I redirect the data directory from ratbag

(that is the first time that I comment on github so please correct me, if I did something wrong)

**Comment by mvnetbiz** [comment]
It looks like the daemon data prefix defaults to its own nix store path, so my previous config example was incomplete.
I think the following should work. I can add an option to the module to create a merged directory, this way it won't require `environment.pathsToLink` if you don't already have it.

```
environment.pathsToLink = [ "/share" ]; # if you have a desktop environment enabled, this is probably set already

systemd.services.ratbagd = {
  environment.LIBRATBAG_DATA_DIR = "/run/current-system/sw/share/libratbag";


  serviceConfig.ExecStart = [  # optional for debugging
    ""
    "${config.services.ratbagd.package}/sbin/ratbagd --verbose=raw"
  ];
};

environment.systemPackages = [
    (pkgs.writeTextDir "share/libratbag/logitech-g102-g203.device" ''
      # G102, G103 and G203 (USB)
      [Device]
      Name=Logitech Gaming Mouse G102/G103/G203
      DeviceMatch=usb:046d:c084;usb:046d:c092;usb:046d:c09d
      Driver=hidpp20
      LedTypes=logo;side;
    '')
];
```

**Comment by mvnetbiz** [comment]
Introduced an `extraDevices` option. https://github.com/NixOS/nixpkgs/pull/533006

With this module update you can add a new device as follow:

```nix
{
  services.ratbagd = {
    enable = true;
    verbose = "debug";
    extraDevices = {
      logitech-g102-g203 = ''
        # G102, G103 and G203 (USB)
        [Device]
        Name=Logitech Gaming Mouse G102/G103/G203
        DeviceMatch=usb:046d:c084;usb:046d:c092;usb:046d:c09d
        Driver=hidpp20
        LedTypes=logo;side;
      '';
    };
  };
}
```

The `verbose` option is also new.

**Comment by TheWrongMensch** [comment]
thanks
