### ISSUE TITLE
throttled: service fails to start (python/ introspection typelib missing at runtime)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#310408]
### Describe the bug

This is on nixos-unstable: b211b392

### Steps To Reproduce
1. try to activate a system with throttled enabled

```

× throttled.service - Stop Intel throttling
     Loaded: loaded (/etc/systemd/system/throttled.service; enabled; preset: enabled)
    Drop-In: /nix/store/vv1i9gmp6pshdjzhbicwd6vrimh8dffl-system-units/throttled.service.d
             └─overrides.conf
     Active: failed (Result: exit-code) since Thu 2024-05-09 11:49:45 PDT; 87ms ago
   Duration: 112ms
    Process: 117803 ExecStart=/nix/store/0h35zm7gfa42sy5rvy523wryxgg6mwp1-throttled-0.10.0/bin/throttled.py (code=exited, status=1/FAILURE)
   Main PID: 117803 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 95ms

May 09 11:49:45 xeep systemd[1]: Started Stop Intel throttling.
May 09 11:49:45 xeep throttled.py[117803]: Traceback (most recent call last):
May 09 11:49:45 xeep throttled.py[117803]:   File "/nix/store/0h35zm7gfa42sy5rvy523wryxgg6mwp1-throttled-0.10.0/bin/.throttled.py-wrapped", line 25, in <module>
May 09 11:49:45 xeep throttled.py[117803]:     from gi.repository import GLib
May 09 11:49:45 xeep throttled.py[117803]:   File "/nix/store/40cddha2iiqzbqd6dpal3rlrgvb4p0yc-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
May 09 11:49:45 xeep throttled.py[117803]:     raise ImportError('cannot import name %s, '
May 09 11:49:45 xeep throttled.py[117803]: ImportError: cannot import name GLib, introspection typelib not found
May 09 11:49:45 xeep systemd[1]: throttled.service: Main process exited, code=exited, status=1/FAILURE
May 09 11:49:45 xeep systemd[1]: throttled.service: Failed with result 'exit-code'.
```

### Expected behavior
It works.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jdev082** [comment]
Seeing the same error when attempting to backup with `deja-dup`. Seems to be a problem with the `pyobject` Python library.
```
BackendException: Could not initialize backend: cannot import name Gio, introspection typelib not found
```

**Comment by jtojnar** [comment]
Will probably need similar fix as https://github.com/NixOS/nixpkgs/issues/310492

**Comment by hauskens** [comment]
I had the same problem, this pr fixed the issue https://github.com/NixOS/nixpkgs/pull/309377
