### ISSUE TITLE
python3Packages.tubeup: cannot launch due to `TypeError: 'module' object is not callable`

### ISSUE THREAD

**Issue by UlyssesZh** [NixOS/nixpkgs#311257]
### Describe the bug
Trying to run `tubeup` and get this:
```
Traceback (most recent call last):
  File "/nix/store/491nxbz4mzi3naxa4pbmmskqfkfxm4bf-python3.11-tubeup-2023.9.19/bin/.tubeup-wrapped", line 9, in <module>
    sys.exit(__main__())
             ^^^^^^^^^^
TypeError: 'module' object is not callable
```

### Steps To Reproduce
1. Install the package `python3Packages.tubeup`.
2. Run command `tubeup`.

### Additional context

Tried both 23.11 and master. The same result.

### Notify maintainers

@marsam 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.86, NixOS, 23.11 (Tapir), 23.11.7071.71bae31b7dbc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adrianmgg** [comment]
patching tubeup's `pyproject.toml` to reference the `main` function instead of the overall `__main__` module fixes it

```nix
pkgs.python312Packages.tubeup
/* $ tubeup
Traceback (most recent call last):
  File "/nix/store/jlm90dd1jaslf1q8aqpr5cih04aw7m75-python3.12-tubeup-2023.9.19/bin/.tubeup-wrapped", line 9, in <module>
    sys.exit(__main__())
             ^^^^^^^^^^
TypeError: 'module' object is not callable
*/


(pkgs.python312Packages.tubeup.overrideAttrs (finalAttrs: previousAttrs: {
  postPatch = ''
    substituteInPlace pyproject.toml --replace-fail $'[project.scripts]\ntubeup = "tubeup:__main__"' $'[project.scripts]\ntubeup = "tubeup:__main__.main"'
  '';
}))
/* $ tubeup
Usage:
  tubeup <url>... [--username <user>] [--password <pass>]
                  [--metadata=<key:value>...]
                  [--cookies=<filename>]
                  [--proxy <prox>]
                  [--quiet] [--debug]
                  [--use-download-archive]
                  [--output <output>]
                  [--ignore-existing-item]
  tubeup -h | --help
  tubeup --version
*/
```

```diff
diff --git a/pyproject.toml b/pyproject.toml
index bd9db5f..510300d 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -16,7 +16,7 @@ dependencies = [
 ]
 
 [project.scripts]
-tubeup = "tubeup:__main__"
+tubeup = "tubeup:__main__.main"
 
 [tool.setuptools.dynamic]
 version = {attr = "tubeup.__version__"}
```
