### ISSUE TITLE
ArchiSteamFarm module does not work without enabling the web-ui

### ISSUE THREAD

**Issue by yunfachi** [NixOS/nixpkgs#312242]
### Describe the bug
When `services.archisteamfarm.web-ui.enable = false` the service and ArchiSteamFarm itself does not start because of the error `UnhandledException() System.IO.IOException: Read-only file system : '/nix/store/...-ArchiSteamFarm-6.0.1.1.24/lib/ArchiSteamFarm/www'`.

### Steps To Reproduce
```nix
services.archisteamfarm = {
  enable = true;
  web-ui.enable = false;
};
```

### Expected behavior
No errors, as happens with `services.archisteamfarm.web-ui.enable = true`.

### Additional context
```log
May 16 17:52:29 dekomori ArchiSteamFarm[149021]: 2024-05-16 17:52:29|ArchiSteamFarm-149021|INFO|ASF|Start() Starting IPC server...
May 16 17:52:30 dekomori ArchiSteamFarm[149021]: 2024-05-16 17:52:29|ArchiSteamFarm-149021|FATAL|ASF|OnUnhandledException() System.IO.IOException: Read-only file system : '/nix/store/ca9ifbl5y5jzxwj5bzgprfv9wq2anfik-ArchiSteamFarm-6.0.1.24/lib/ArchiSteamFarm/www'
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at System.IO.FileSystem.CreateDirectory(String, UnixFileMode)
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at System.IO.FileSystem.CreateDirectory(String)
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at System.IO.Directory.CreateDirectory(String)
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at Microsoft.AspNetCore.Hosting.HostingEnvironmentExtensions.Initialize(IWebHostEnvironment, String, WebHostOptions, IHostEnvironment )
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at Microsoft.AspNetCore.Hosting.WebHostBuilderBase.GetWebHostBuilderContext(HostBuilderContext)
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at Microsoft.AspNetCore.Hosting.SlimWebHostBuilder.<.ctor>b__0_1(HostBuilderContext context, IServiceCollection services)
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks()
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at Microsoft.AspNetCore.Builder.WebApplicationBuilder.InitializeHosting(BootstrapHostBuilder)
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions, Boolean, Boolean, Action`1 ) 1462
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at Microsoft.AspNetCore.Builder.WebApplication.CreateEmptyBuilder(WebApplicationOptions)
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at ArchiSteamFarm.IPC.ArchiKestrel.CreateWebApplication()
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at ArchiSteamFarm.IPC.ArchiKestrel.Start()
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at ArchiSteamFarm.Core.ASF.Init()
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at ArchiSteamFarm.Program.InitASF()
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at ArchiSteamFarm.Program.Init(IReadOnlyCollection`1 args)
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at ArchiSteamFarm.Program.Main(String[] args)
May 16 17:52:30 dekomori ArchiSteamFarm[149021]:    at ArchiSteamFarm.Program.<Main>(String[] args)
May 16 17:52:30 dekomori ArchiSteamFarm[149021]: 2024-05-16 17:52:30|ArchiSteamFarm-149021|ERROR|ASF|Exit() Exiting with 1 error code!
May 16 17:52:30 dekomori systemd[1]: archisteamfarm.service: Main process exited, code=exited, status=1/FAILURE
May 16 17:52:30 dekomori systemd[1]: archisteamfarm.service: Failed with result 'exit-code'.
May 16 17:52:30 dekomori systemd[1]: archisteamfarm.service: Consumed 1.617s CPU time, no IP traffic.
May 16 17:52:30 dekomori systemd[1]: archisteamfarm.service: Scheduled restart job, restart counter is at 1.
```
My `services.archisteamfarm` configuration: https://github.com/yunfachi/nix-config/blob/d3554d394721ac589330449502deb0e7fde76e63/modules/services/archisteamfarm.nix

### Notify maintainers
@SuperSandro2000

### Metadata
```console
dekomori* in nix-config ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05.20240427.58a1abd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/801l7gvdz7yaibhjsxqx82sc7zkakjbq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
#313228 should fix that

**Comment by JustArchi** [comment]
Next time report upstream :slightly_smiling_face: 

https://github.com/JustArchiNET/ArchiSteamFarm/commit/b9beb6ec16ac849ece68e4abb337c328e2bc0eb9
