### ISSUE TITLE
Groovy scripts failed to execute after switched to unstable channel.

### ISSUE THREAD

**Issue by hzfsls** [NixOS/nixpkgs#312679]
### Describe the bug
The Groovy package in unstable channel use jdk21, leading to scripts failed to execute.
Maybe the package version is too old.

### Steps To Reproduce
1. Add channel with `nix-channel --add https://nixos.org/channels/nixos-23.11 nixpkgs` and `nix-channel --update`.
2. Create a Groovy script called `test.groovy`, with content: `new File("foo.txt").text = "foo"`.
3. Run `nix-shell -p groovy`, the `groovy --version`, should report `Groovy Version: 3.0.11 JVM: 19.0.2 Vendor: Oracle Corporation OS: Linux`.
4. Run `groovy test.groovy`, now the script can be executed successfully.
5. Switch channel with `nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs` and `nix-channel --update`.
6. Run `nix-shell -p groovy`, the `groovy --version`, should report `Groovy Version: 3.0.11 JVM: 21 Vendor: Oracle Corporation OS: Linux`.
7. Run `groovy test.groovy`, execution failed and return:
```
Caught: BUG! exception in phase 'semantic analysis' in source unit '/mnt/sda/ytr/Generation/test.groovy' Unsupported class file major version 65
BUG! exception in phase 'semantic analysis' in source unit '/mnt/sda/ytr/Generation/test.groovy' Unsupported class file major version 65
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
        ... 1 more
```

### Expected behavior
Should execute successfully as before switching to unstable channel.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-26-generic, Ubuntu, 23.10 (Mantic Minotaur), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.20.4`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by hzfsls** [comment]
[#315856](https://github.com/NixOS/nixpkgs/pull/315856) Should solve the problem in unstable channel.
In nixos-24.05, use `(pkgs.groovy.override { jdk = pkgs.jdk19; })` instead.
