### ISSUE TITLE
deluge fails to start with python error "pyasn1 0.6.0 ... requirement 'pyasn1<0.6.0,>=0.4.6'"

### ISSUE THREAD

**Issue by lodi** [NixOS/nixpkgs#312717]
### Describe the bug
`deluge` builds but fails to run due to a runtime package versioning problem.  I did a git bisect and commit 2544167a82ff99e00a8de68fa529701a30648128 introduced this problem.

### Steps To Reproduce
```
> git checkout 2544167a82ff99e00a8de68fa529701a30648128
> nix-shell -I nixpkgs=. -p deluge --run 'deluge -v'
Traceback (most recent call last):
  File "/nix/store/4kn81r47yfvciivmr5xyyia2ijrm6v4d-python3.11-deluge-gtk-2.1.1/bin/..deluge-wrapped-wrapped", line 9, in <module>
    sys.exit(start_ui())
             ^^^^^^^^^^
  File "/nix/store/4kn81r47yfvciivmr5xyyia2ijrm6v4d-python3.11-deluge-gtk-2.1.1/lib/python3.11/site-packages/deluge/ui/ui_entry.py", line 39, in start_ui
    ui_entrypoints[entrypoint.name] = entrypoint.load()
                                      ^^^^^^^^^^^^^^^^^
  File "/nix/store/07p7lg2s9q9zs4n7lh21p01bwkx99ixj-python3.11-setuptools-69.5.1/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2481, in load
    self.require(*args, **kwargs)
  File "/nix/store/07p7lg2s9q9zs4n7lh21p01bwkx99ixj-python3.11-setuptools-69.5.1/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2504, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/07p7lg2s9q9zs4n7lh21p01bwkx99ixj-python3.11-setuptools-69.5.1/lib/python3.11/site-packages/pkg_resources/__init__.py", line 798, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/07p7lg2s9q9zs4n7lh21p01bwkx99ixj-python3.11-setuptools-69.5.1/lib/python3.11/site-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.6.0 (/nix/store/ld3ywvbk19575dc04dqlzzb55jyc3gs9-python3.11-pyasn1-0.6.0/lib/python3.11/site-packages), Requirement.parse('pyasn1<0.6.0,>=0.4.6'), {'pyasn1-modules'})

```

### Expected behavior
```
> git checkout 1aae0909b02ffb4d0d4a45db322df7a8c9fdd34e
> nix-shell -I nixpkgs=. -p deluge --run 'deluge -v'
.deluge-wrapped 2.1.1
libtorrent: 2.0.10.0
Python: 3.11.9
OS: Linux 6.6.29

```

### Notify maintainers

@vcunat, @domenkozar, @ebzzry

**Comment by vcunat** [comment]
The error was surely not introduced by this commit in particular.  I'd guess some a bit earlier commit (probably f9e5f5d9d6e0), but I don't expect it makes that much difference.

**Comment by lodi** [comment]
Thanks @vcunat, yes f9e5f5d9d6e079b133ba8ae810eeb08438e0e16b looks very suspicious given the error message.  I don't know enough about python packaging to determine what needs to be updated for deluge specifically though; @domenkozar, @ebzzry, could you please take a look?
