### ISSUE TITLE
Getting Things Gnome synchronisation method can't be added

### ISSUE THREAD

**Issue by necessarily-equal** [NixOS/nixpkgs#312977]
### Describe the bug
The synchronisation methods in getting things done (the `gtg` package) are not usable because they can't be added.

### Steps To Reproduce
1. start the app
2. click on the hamburger menu
3. cilck on "Synchronisation" in the menu
4. click on the [+] button on the bottom left

```
**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/nix/store/4vbaaxbsman57px5pcv28pzwjnns2gk6-gtg-0.6/lib/python3.11/site-packages/GTG/gtk/backends/__init__.py", line 231, in on_add_button
    self.add_panel.refresh_backends()
  File "/nix/store/4vbaaxbsman57px5pcv28pzwjnns2gk6-gtg-0.6/lib/python3.11/site-packages/GTG/gtk/backends/addpanel.py", line 141, in refresh_backends
    self.combo_types.refresh()
  File "/nix/store/4vbaaxbsman57px5pcv28pzwjnns2gk6-gtg-0.6/lib/python3.11/site-packages/GTG/gtk/backends/backendscombo.py", line 81, in refresh
    pixbuf = self.dialog.get_pixbuf_from_icon_name(module.Backend.get_icon(), 16)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/4vbaaxbsman57px5pcv28pzwjnns2gk6-gtg-0.6/lib/python3.11/site-packages/GTG/gtk/backends/__init__.py", line 121, in get_pixbuf_from_icon_name
    return Gtk.IconTheme.get_default().load_icon(name, height, 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'applications-internet' not present in theme Adwaita (0)
```

**Software versions:**
* Getting Things GNOME! 0.6.0
* CPython 3.11.9 (main, Apr  2 2024, 08:25:04) [GCC 13.2.0]
* GTK 3.24.41, GLib 2.78.4
* PyGLib 3.46.0, PyGObject 3.46.0
* Linux-6.8.6-zen1-x86_64-with-glibc2.39
```

I tested both with NixOS 23.11 and Unstable

### Expected behavior
A clear and concise description of what you expected to happen.

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/59283660/31a7844b-e18f-4e67-b51c-e7fed4c4580a)

### Notify maintainers

@oyren

**Comment by necessarily-equal** [comment]
This seems to be a purely graphical problem.

One thing I tried to fix it, inspired by https://stackoverflow.com/questions/35794241/meld-gi-glib-gerror-icon-meld-change-apply-right-not-present-in-theme-wha#53890252, is to put `gnome-icon-theme` in `propagatedBuildInputs` but without success.

**Comment by necessarily-equal** [comment]
It seems to be a known issue upstream. There seem to be an issue opened, but the url 404 at least for me: https://github.com/getting-things-gnome/gtg/issues/846

Closed as duplicates:
* https://github.com/getting-things-gnome/gtg/issues/947
* https://github.com/getting-things-gnome/gtg/issues/934
* https://github.com/getting-things-gnome/gtg/issues/896
* https://github.com/getting-things-gnome/gtg/issues/879

I just asked there https://github.com/getting-things-gnome/gtg/issues/934#issuecomment-2119341349 for more info.
