### ISSUE TITLE
Beeper 3.104.7 broken on unstable

### ISSUE THREAD

**Issue by Andreas02-dev** [NixOS/nixpkgs#313338]
### Describe the bug
Shader compilation fails with Beeper 3.104.7, causing the application to not display anything in the opened window.

### Steps To Reproduce
1. Install Beeper from NixOS Unstable revision 6c0b7a92c30122196a761b440ac0d46d3d9954f1
2. Run `beeper` in the terminal
3. Check the logs

### Expected behavior
Shaders should compile and the app should work as expected.

### Screenshots
N.a.

### Additional context
Logs (truncated, as it was too large)
```log
Initializing todesktop runtime
@todesktop/runtime: skipping autoUpdater initialization because application is not in AppImage.
09:59:55.854 › @todesktop/runtime: AutoUpdater: @todesktop/runtime: skipping autoUpdater initialization because application is not in AppImage.
09:59:55.937 › @todesktop/runtime: AutoUpdater: electron will-finish-launching event emitted { appVersion: '3.104.7', runtimeVersion: '1.4.0' }
Web App Path is /nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/webapp.asar/
iconsPath path is /nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/icons/
Loading vector config for brand Beeper
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/language-helper.js
- /nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/electron-main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/browser_init:2:116646)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at AppLocalization.fetchTranslationJson (/nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/language-helper.js:76:20)
    at /nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/language-helper.js',
    '/nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
DRI driver not from this Mesa build ('23.1.9' vs '24.0.6')
failed to bind extensions
DRI driver not from this Mesa build ('23.1.9' vs '24.0.6')
failed to bind extensions
DRI driver not from this Mesa build ('23.1.9' vs '24.0.6')
failed to bind extensions
Resetting the UI components after locale change
Resetting the UI components after locale change
sending browser-window-focus to react
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/language-helper.js
- /nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/electron-main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/browser_init:2:116646)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at AppLocalization.fetchTranslationJson (/nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/language-helper.js:76:20)
    at /nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/language-helper.js',
    '/nix/store/2kka5r7k91k6xqjl2pvbpn0gr27zs5pv-beeper-3.104.7-extracted/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
[38919:0521/095957.747639:ERROR:shared_context_state.cc(98)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;uniform float3x3 umatrix_S1_c0;in float2 position;in half4 color;in float2 localCoord;flat out half4 vcolor_S0;noperspective out float2 vTransformedCoords_3_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
vcolor_S0 = color;sk_Position = position.xy01;{
vTransformedCoords_3_S0 = float3x2(umatrix_S1_c0) * localCoord.xy1;
}
}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 uclamp_S1_c0_c0;uniform float3x3 umatrix_S1_c0;sampler2D uTextureSampler_0_S1;
flat in half4 vcolor_S0;noperspective in float2 vTransformedCoords_3_S0;half4 TextureEffect_S1_c0_c0(half4 _input) {
float2 inCoord = vTransformedCoords_3_S0;float2 subsetCoord;subsetCoord.x = inCoord.x;subsetCoord.y = inCoord.y;float2 clampedCoord;clampedCoord = clamp(subsetCoord, uclamp_S1_c0_c0.xy, uclamp_S1_c0_c0.zw);half4 textureColor = sample(uTextureSampler_0_S1, clampedCoord);return textureColor;}

half4 MatrixEffect_S1_c0(half4 _input) {
return TextureEffect_S1_c0_c0(_input);
}

half4 DisableCoverageAsAlpha_S1(half4 _input) {
_input = MatrixEffect_S1_c0(_input);
half4 _tmp_0_inColor = _input;
return half4(_input);
}

void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0;outputColor_S0 = vcolor_S0;const half4 outputCoverage_S0 = half4(1);half4 output_S1;output_S1 = DisableCoverageAsAlpha_S1(outputColor_S0);{ // Xfer Processor: Porter Duff
sk_FragColor = output_S1 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
uniform highp mat3 umatrix_S1_c0;
in highp vec2 position;
in mediump vec4 color;
in highp vec2 localCoord;
flat out mediump vec4 vcolor_S0;
noperspective out highp vec2 vTransformedCoords_3_S0;
void main() {
    vcolor_S0 = color;
    gl_Position = vec4(position, 0.0, 1.0);
    {
        vTransformedCoords_3_S0 = mat3x2(umatrix_S1_c0) * vec3(localCoord, 1.0);
    }
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
uniform highp vec4 uclamp_S1_c0_c0;
uniform highp mat3 umatrix_S1_c0;
uniform sampler2D uTextureSampler_0_S1;
flat in mediump vec4 vcolor_S0;
noperspective in highp vec2 vTransformedCoords_3_S0;
void main() {
    mediump vec4 outputColor_S0 = vcolor_S0;
    mediump vec4 _8_input = outputColor_S0;
    highp vec2 _9_inCoord = vTransformedCoords_3_S0;
    highp vec2 _10_subsetCoord;
    _10_subsetCoord.x = _9_inCoord.x;
    _10_subsetCoord.y = _9_inCoord.y;
    highp vec2 _11_clampedCoord = clamp(_10_subsetCoord, uclamp_S1_c0_c0.xy, uclamp_S1_c0_c0.zw);
    mediump vec4 _12_textureColor = texture(uTextureSampler_0_S1, _11_clampedCoord, -0.5);
    _8_input = _12_textureColor;
    mediump vec4 output_S1 = _8_input;
    {
        sk_FragColor = output_S1;
    }
}


Errors:
link failed but did not provide an info log
[38919:0521/095957.748223:ERROR:shared_context_state.cc(98)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float2 position;in float2 localCoord;noperspective out float2 vlocalCoord_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
vlocalCoord_S0 = localCoord;sk_Position = position.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
sampler2D uTextureSampler_0_S0;
noperspective in float2 vlocalCoord_S0;void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0 = half4(1);float2 texCoord;texCoord = vlocalCoord_S0;outputColor_S0 = (blend_modulate(sample(uTextureSampler_0_S0, texCoord), half4(1)));const half4 outputCoverage_S0 = half4(1);{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
in highp vec2 position;
in highp vec2 localCoord;
noperspective out highp vec2 vlocalCoord_S0;
void main() {
    vlocalCoord_S0 = localCoord;
    gl_Position = vec4(position, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
uniform sampler2D uTextureSampler_0_S0;
noperspective in highp vec2 vlocalCoord_S0;
void main() {
    mediump vec4 outputColor_S0 = vec4(1.0);
    highp vec2 texCoord = vlocalCoord_S0;
    outputColor_S0 = texture(uTextureSampler_0_S0, texCoord, -0.5);
    {
        sk_FragColor = outputColor_S0;
    }
}


Errors:
link failed but did not provide an info log
[38919:0521/095957.749031:ERROR:shared_context_state.cc(98)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float2 position;in half4 color;flat out half4 vcolor_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
vcolor_S0 = color;sk_Position = position.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
flat in half4 vcolor_S0;void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0;outputColor_S0 = vcolor_S0;const half4 outputCoverage_S0 = half4(1);{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
in highp vec2 position;
in mediump vec4 color;
flat out mediump vec4 vcolor_S0;
void main() {
    vcolor_S0 = color;
    gl_Position = vec4(position, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
flat in mediump vec4 vcolor_S0;
void main() {
    mediump vec4 outputColor_S0 = vcolor_S0;
    {
        sk_FragColor = outputColor_S0;
    }
}


Errors:
link failed but did not provide an info log
[38919:0521/095957.749447:ERROR:shared_context_state.cc(98)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float2 position;in float2 localCoord;noperspective out float2 vlocalCoord_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
vlocalCoord_S0 = localCoord;sk_Position = position.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
sampler2D uTextureSampler_0_S0;
noperspective in float2 vlocalCoord_S0;void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0 = half4(1);float2 texCoord;texCoord = vlocalCoord_S0;outputColor_S0 = (blend_modulate(sample(uTextureSampler_0_S0, texCoord), half4(1)));const half4 outputCoverage_S0 = half4(1);{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
in highp vec2 position;
in highp vec2 localCoord;
noperspective out highp vec2 vlocalCoord_S0;
void main() {
    vlocalCoord_S0 = localCoord;
    gl_Position = vec4(position, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
uniform sampler2D uTextureSampler_0_S0;
noperspective in highp vec2 vlocalCoord_S0;
void main() {
    mediump vec4 outputColor_S0 = vec4(1.0);
    highp vec2 texCoord = vlocalCoord_S0;
    outputColor_S0 = texture(uTextureSampler_0_S0, texCoord, -0.5);
    {
        sk_FragColor = outputColor_S0;
    }
}


Errors:
link failed but did not provide an info log
[38919:0521/095957.749749:ERROR:shared_context_state.cc(98)] Skia shader compilation error
```

### Notify maintainers
@jshcmpbll @mjm @edmundmiller 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
┌─ ~ 
└─> nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.91, NixOS, 23.11 (Tapir), 23.11.20240520.a8695cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/etc/nixPath`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Andreas02-dev** [comment]
It seems to have been an issue in the GPUCache, likely caused by Electron. Deleting all files in `~/.config/Beeper/GPUCache` has solved it for me, so I'm closing the issue.
