### ISSUE TITLE
"it seems like blueman-manager could not get activated via D-BUS"

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#315173]
### Describe the bug

blueman used to work out perfectly fine (though I miss the tray icon for some reason):
```
May 27 21:21:21 laptop blueman-applet[2232]: blueman-applet 21.21.21 ERROR    DBusProxies:62 activate  : Call to org.blueman.Manager failed
May 27 21:21:21 laptop blueman-applet[2232]: Traceback (most recent call last):
May 27 21:21:21 laptop blueman-applet[2232]:   File "/nix/store/3q6vwm5b9y5iqkm5wps7iw38h988aj50-blueman-2.4.1/lib/python3.11/site-packages/blueman/main/DBusProxies.py", line 57, in activate
May 27 21:21:21 laptop blueman-applet[2232]:     self.call_sync("Activate", param, Gio.DBusCallFlags.NONE, -1, None)
May 27 21:21:21 laptop blueman-applet[2232]: gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.blueman.Manager was not provi>
May 27 21:21:21 laptop .waybar-wrapped[2231]: [207B blob data]
```

```

### Steps To Reproduce
Steps to reproduce the behavior: I've got this in my nixos configuration
```
  services.blueman-applet.enable = true;
   hardware.bluetooth = {
      enable = true;
      powerOnBoot = true;
      # hsphfpd.enable = false; # conflicts with pipewire
    };

```

### Expected behavior
Be able to use the tray icon to connect my headset. 

### Screenshots
If applicable, add screenshots to help explain your problem.
![image](https://github.com/NixOS/nixpkgs/assets/886074/280a0804-67ea-4000-a204-b1faebd94960)

### COntext
I suspect it sopped working after the dbus backend switch but I haven't checked. I am not familiar enough with dbus to preoperly diagnose.

### Notify maintainers
@abbradar 
<!--
Please @ people who are in the `meta.maintainers` list of the offending package or module.
If in doubt, check `git blame` for whoever last touched something.
-->

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nixos-unstable
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by superherointj** [comment]
Consider checking if [Bluetooth](https://wiki.gentoo.org/wiki/Bluetooth) driver is initializing correctly at `dmesg` and `hciconfig`.
On my case, it wasn't.

**Comment by Aleksanaa** [comment]
I only have `hardware.bluetooth.enable = true;` and `services.blueman.enable = true;`, and it works perfectly for me.

**Comment by Ralith** [comment]
This broke for me as well when upgrading to 24.05. Nothing weird looking in bluetooth or hciconfig.

**Comment by Ralith** [comment]
Slightly different errors in the journal for me:
```
Aug 07 13:17:56 flow dbus-daemon[1884]: [session uid=1000 pid=1884] Activating via systemd: service name='org.blueman.Manager' unit='blueman-manager.service' requested by ':1.20' (uid=1000 pid=1873 comm="/nix/store/pfv4raslwhi3101k342752v65zxkwrxq-python" label="kernel")
Aug 07 13:17:56 flow systemd[1841]: Starting Bluetooth Manager...
Aug 07 13:17:56 flow dbus-daemon[1884]: [session uid=1000 pid=1884] Successfully activated service 'org.blueman.Manager'
Aug 07 13:17:56 flow systemd[1841]: Started Bluetooth Manager.
Aug 07 13:18:21 flow blueman-tray[2246]: Traceback (most recent call last):
Aug 07 13:18:21 flow blueman-tray[2246]:   File "/nix/store/969y31x2b218wy4ldc8zmp3lmfi1czfs-blueman-2.4.1/lib/python3.11/site-packages/blueman/main/indicators/GtkStatusIcon.py", line 64, in <lambda>
Aug 07 13:18:21 flow blueman-tray[2246]:     self.indicator.connect('activate', lambda _status_icon: tray.activate_status_icon())
Aug 07 13:18:21 flow blueman-tray[2246]:                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 07 13:18:21 flow blueman-tray[2246]:   File "/nix/store/969y31x2b218wy4ldc8zmp3lmfi1czfs-blueman-2.4.1/lib/python3.11/site-packages/blueman/main/Tray.py", line 65, in activate_status_icon
Aug 07 13:18:21 flow blueman-tray[2246]:     AppletService().Activate()
Aug 07 13:18:21 flow blueman-tray[2246]:   File "/nix/store/4bkc91biqigm1rdyk3dhbhq0fxlpcgas-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/overrides/Gio.py", line 349, in __call__
Aug 07 13:18:21 flow blueman-tray[2246]:     result = self.dbus_proxy.call_sync(self.method_name, arg_variant,
Aug 07 13:18:21 flow blueman-tray[2246]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 07 13:18:21 flow blueman-tray[2246]: gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)
Aug 07 13:18:21 flow blueman-applet[1873]: blueman-applet 13.18.21 ERROR    DBusProxies:62 activate  : Call to org.blueman.Manager failed
Aug 07 13:18:21 flow blueman-applet[1873]: Traceback (most recent call last):
Aug 07 13:18:21 flow blueman-applet[1873]:   File "/nix/store/969y31x2b218wy4ldc8zmp3lmfi1czfs-blueman-2.4.1/lib/python3.11/site-packages/blueman/main/DBusProxies.py", line 57, in activate
Aug 07 13:18:21 flow blueman-applet[1873]:     self.call_sync("Activate", param, Gio.DBusCallFlags.NONE, -1, None)
Aug 07 13:18:21 flow blueman-applet[1873]: gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)
```

**Comment by Ralith** [comment]
Killing the `..blueman-manager-wrapped-wrapped` process seems to have resolved it. I guess something got wedged?
