### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by BjornMelgaard** [NixOS/nixpkgs#31539]
## Issue description
I getting this error with my home project only when installing with `nixos-rebuild`

```sh
 ✘  ~/.config/dotfiles   master ●  sudo nixos-rebuild switch
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/4m8q9kzim99kswv8wfdpbyyldsmxw055-lingualeo2anki-0.0.1.drv
  /nix/store/kblmcdpw4agy6pq2fm05717dvr9sqbgl-system-path.drv
  /nix/store/r5ax239d2lvgfnd4lf4v4xxiv1x25wa8-dbus-1.drv
  /nix/store/y922n05ijias0izf2ngq6y6h8bsm2hwx-unit-dbus.service.drv
  /nix/store/4r7cf54ml8saacmd9pzhg1jih7nsd1ax-user-units.drv
  /nix/store/kswizni5lvp8jp4wllq224nzbldchgbk-xsession.drv
  /nix/store/d6rwmz0b5kab1pbginrg4sldsnm6ah0c-desktops.drv
  /nix/store/61s4vic6jhqwfapbmi9pw0p2r8m52r3s-lightdm.conf.drv
  /nix/store/in1bkv60fh3xpn58n04yvw2fxdy5kf4c-unit-systemd-fsck-.service.drv
  /nix/store/q6gd5b2qqr90lhpnzllfldgwqyahgjzx-unit-polkit.service.drv
  /nix/store/wcaihqav5l69gjzsjsp8mp6waascw3n4-system-units.drv
  /nix/store/mj9g4vrjvc8ysv2ql6m256v33n35cm39-etc.drv
  /nix/store/iblrw34y7lxhzvr2mbqhp7m6y87brw75-nixos-system-machine-17.09.1880.ac2bb5684c.drv
building path(s) ‘/nix/store/j1wlss8jf7afw967q23b3l6y3137a9hy-lingualeo2anki-0.0.1’
unpacking sources
unpacking source archive /nix/store/4ixa94y2p46dci6ipwgckjz1pjz8xqa0-lingualeo2anki
source root is lingualeo2anki
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file lingualeo2anki/tests/test.py
patching sources
configuring
building
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/nix/store/0wbiaz7p34z6b9lhinfncrn7a32jfmni-python3.6-pbr-3.1.1/lib/python3.6/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/nix/store/0wbiaz7p34z6b9lhinfncrn7a32jfmni-python3.6-pbr-3.1.1/lib/python3.6/site-packages/pbr/util.py", line 251, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/nix/store/0wbiaz7p34z6b9lhinfncrn7a32jfmni-python3.6-pbr-3.1.1/lib/python3.6/site-packages/pbr/util.py", line 315, in setup_cfg_to_setup_kwargs
    value += description_file.read().strip() + '\n\n'
  File "/nix/store/9zriyh8kgflvpp4xmd7ai36rs120lksi-python3-3.6.3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 21: ordinal not in range(128)
error in setup command: Error parsing /tmp/nix-build-lingualeo2anki-0.0.1.drv-0/lingualeo2anki/setup.cfg: UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 21: ordinal not in range(128)
builder for ‘/nix/store/4m8q9kzim99kswv8wfdpbyyldsmxw055-lingualeo2anki-0.0.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/kblmcdpw4agy6pq2fm05717dvr9sqbgl-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/iblrw34y7lxhzvr2mbqhp7m6y87brw75-nixos-system-machine-17.09.1880.ac2bb5684c.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/iblrw34y7lxhzvr2mbqhp7m6y87brw75-nixos-system-machine-17.09.1880.ac2bb5684c.drv’ failed
```

### Steps to reproduce

[Project](https://github.com/BjornMelgaard/lingualeo2anki)
[and how I adding it to system-packages](https://github.com/BjornMelgaard/dotfiles/blob/a92daaf891e039201cfc8d8f300ba508e5c6748f/nixos/root/system-packages.nix#L85)

project config:
```nix
{ pkgs ? import <nixpkgs> {}}:

with pkgs;

let
  python = python3;
  pythonPackages = python.pkgs;

  # generated with `pip2nix generate -r requirements.txt`
  generatePipPackages = import ./python-packages.nix {
    inherit pkgs;
    inherit (pkgs) fetchurl fetchgit fetchhg;
  };

  pipPackages =  generatePipPackages pipPackages pythonPackages;
in

pythonPackages.buildPythonApplication rec {
  pname = "lingualeo2anki";
  version = "0.0.1";
  name = "${pname}-${version}";

  src = ./.;

  buildInputs = with pipPackages; with pythonPackages; [
    python
    pbr
    git

    colorama
    requests
    beautifulsoup4
    memoized-property
  ];

  # this could help, but nix throws error `/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)`
  # preConfigure = ''
  #   export LC_ALL="en_US.UTF-8"
  # '';

  meta = {
    homepage = https://github.com/BjornMelgaard/lingualeo2anki;
    description = "Hack lingualeo chrome plugin and save dictionary locally, ready to anki import";
    license = lib.licenses.mit;
    platforms = lib.platforms.all;
  };
}
```

Though  tests are working fine from `nix-shell` in project dir, they are failing on test phase on install (if I move data from `setup.cfg` to `setup.py` to unblock myself slightly [like I did in this branch](https://github.com/BjornMelgaard/lingualeo2anki/blob/with-removed-setup-cfg/setup.py)) with the similar error
```
  File "/tmp/nix-build-lingualeo2anki-0.0.1.drv-1/lingualeo2anki/server/utils.py", line 16, in debug
    print("DEBUG: ", data.format(*args))
UnicodeEncodeError: 'ascii' codec can't encode character '\u02c8' in position 214: ordinal not in range(128)

```

## Technical details

* System:  (NixOS: `nixos-version`) 17.09.1880.ac2bb5684c (Hummingbird)
* Nix version:  (run `nix-env --version`) nix-env (Nix) 1.11.15
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.09.1880.ac2bb5684c" 
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`) build-use-sandbox = false

**Comment by FRidh** [comment]
You should indeed export `LC_ALL` like you did. But you need `glibcLocales` in your `buildInputs`.

**Comment by BjornMelgaard** [comment]
@FRidh many thanks, it was hard

can you help me with another error?

nix throws `Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name lingualeo2anki was given, but was not able to be found.` when I trying to [install from repo](https://github.com/BjornMelgaard/dotfiles/blob/master/nixos/root/system-packages.nix#L87-L92)

Though all works fine when I installing from local dir

```nix
    lingualeo2anki = callPackage (fetchFromGitHub {
      owner = "BjornMelgaard";
      repo = "lingualeo2anki";
      rev = "81faa0e198fcb167369416c3b4657544ce84c7d4";
      sha256 = "1pi46zsbjw2zkd29d95cpy2llmc5djpmaa7cmb1v4bf7gxb6ihgb";
    }) {};
```

```sh
 ~/.config/dotfiles   master ●  sudo nixos-rebuild switch
building Nix...
building the system configuration...
building path(s) ‘/nix/store/wcr039dsd2zvngqy3gb44l5m590krd9s-lingualeo2anki-81faa0e198fcb167369416c3b4657544ce84c7d4-src’

trying https://github.com/BjornMelgaard/lingualeo2anki/archive/81faa0e198fcb167369416c3b4657544ce84c7d4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170    0   170    0     0    170      0 --:--:-- --:--:-- --:--:--   287
100 10106    0 10106    0     0  10106      0 --:--:--  0:00:01 --:--:-- 60514
unpacking source archive /tmp/nix-build-lingualeo2anki-81faa0e198fcb167369416c3b4657544ce84c7d4-src.drv-0/81faa0e198fcb167369416c3b4657544ce84c7d4.tar.gz
these derivations will be built:
  /nix/store/7fiiwx1gz09k2vglhvjjk3dhcsr7m6l0-lingualeo2anki-0.0.1.drv
  /nix/store/w4wgbs687k0qcr1w6gg0wnxzagnlzkfk-system-path.drv
  /nix/store/j8wgb89bw4zsqi4v576bghzn1vhwkc1m-dbus-1.drv
  /nix/store/1kyssmab9p3gb8svkzyi59ycl8pay2mr-unit-dbus.service.drv
  /nix/store/90n3jqxcdhg0kxxda1rdxki55ry7x7yz-unit-systemd-fsck-.service.drv
  /nix/store/xbfbx8qsdkxsw9q02jy2hpyl4c0var22-unit-polkit.service.drv
  /nix/store/4rhd8x0pijc9qb0z6prabgg3pmlkfib2-system-units.drv
  /nix/store/n6wfi1kp7lfpbqnam1ba7yp3lnxb5skg-xsession.drv
  /nix/store/r8vvz3w17plydjjy5kxgxwjm2zdcglkv-desktops.drv
  /nix/store/pgsls2dlk132nb9myjhh5nr34ml272ca-lightdm.conf.drv
  /nix/store/z7ygmi7yxwq84h29l0z0isjknsv4s21h-user-units.drv
  /nix/store/jpdkv4a8x5id8hyh0r0s5j5wgkr5561p-etc.drv
  /nix/store/xajx2aypmjlvsb4jknz08rs7z2l9cyz7-nixos-system-machine-17.09.2034.78eed74497.drv
building path(s) ‘/nix/store/rpq7lpbmb1ig9vl4f1n1mj3c3khzrf0g-lingualeo2anki-0.0.1’
unpacking sources
unpacking source archive /nix/store/qbhnmvn4qn93n5p2fik90py74sgjlmaz-wcr039dsd2zvngqy3gb44l5m590krd9s-lingualeo2anki-81faa0e198fcb167369416c3b4657544ce84c7d4-src
source root is wcr039dsd2zvngqy3gb44l5m590krd9s-lingualeo2anki-81faa0e198fcb167369416c3b4657544ce84c7d4-src
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file wcr039dsd2zvngqy3gb44l5m590krd9s-lingualeo2anki-81faa0e198fcb167369416c3b4657544ce84c7d4-src/tests/test.py
patching sources
configuring
building
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/nix/store/0q99vx7qyfacq5fyq26vv3l1gfdcdj9a-python3.6-pbr-3.1.1/lib/python3.6/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/nix/store/0q99vx7qyfacq5fyq26vv3l1gfdcdj9a-python3.6-pbr-3.1.1/lib/python3.6/site-packages/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/nix/store/0q99vx7qyfacq5fyq26vv3l1gfdcdj9a-python3.6-pbr-3.1.1/lib/python3.6/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/nix/store/0q99vx7qyfacq5fyq26vv3l1gfdcdj9a-python3.6-pbr-3.1.1/lib/python3.6/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/nix/store/0q99vx7qyfacq5fyq26vv3l1gfdcdj9a-python3.6-pbr-3.1.1/lib/python3.6/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/nix/store/0q99vx7qyfacq5fyq26vv3l1gfdcdj9a-python3.6-pbr-3.1.1/lib/python3.6/site-packages/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name lingualeo2anki was given, but was not able to be found.
error in setup command: Error parsing /tmp/nix-build-lingualeo2anki-0.0.1.drv-0/wcr039dsd2zvngqy3gb44l5m590krd9s-lingualeo2anki-81faa0e198fcb167369416c3b4657544ce84c7d4-src/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name lingualeo2anki was given, but was not able to be found.
builder for ‘/nix/store/7fiiwx1gz09k2vglhvjjk3dhcsr7m6l0-lingualeo2anki-0.0.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/w4wgbs687k0qcr1w6gg0wnxzagnlzkfk-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/xajx2aypmjlvsb4jknz08rs7z2l9cyz7-nixos-system-machine-17.09.2034.78eed74497.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/xajx2aypmjlvsb4jknz08rs7z2l9cyz7-nixos-system-machine-17.09.2034.78eed74497.drv’ failed
```

I have seen this error before and I have resolved it by adding `git` to `buildInputs` (inspiration was drawn from [nox](https://github.com/NixOS/nixpkgs/blob/139d931d4dc6f7da75cb66094c204526961a9633/pkgs/tools/package-management/nox/default.nix))

[this](https://github.com/BjornMelgaard/lingualeo2anki/commit/b68330b04a32989cbdf88242246c516bda8f59ab)  [this](https://github.com/BjornMelgaard/lingualeo2anki/commit/d1ad5515b7dba7cc62aa1c661f82be873781dd77) [this](https://github.com/BjornMelgaard/lingualeo2anki/commit/81faa0e198fcb167369416c3b4657544ce84c7d4) changes didn't help

**Comment by FRidh** [comment]
Judging from the `setup.cfg` you wrote you should not use `pbr`. Or do you use it elsewhere?

**Comment by BjornMelgaard** [comment]
@FRidh I'm doing all like in [nox](https://github.com/madjar/nox/blob/master/setup.py)

[Removing prb didn't help](https://github.com/BjornMelgaard/lingualeo2anki/commit/3b6bb950ca2364fe4dac37202557e3d2861b1431)

**Comment by FRidh** [comment]
> Removing prb didn't help

Saying this isn't helpful either. You have to be more specific otherwise its not possible to help. Your previous post shows an error raised by pbr. Why are you using pbr?

**Comment by BjornMelgaard** [comment]
> Why are you using pbr?

Why I shouldn't? I'm not familiar with python much, but pbr parses `setup.cfg`, [without it](https://github.com/BjornMelgaard/lingualeo2anki/commit/58e0f98a1a9cce2f9333a498109940778ddfafe7) nix does not create executables

```
 ~/projects/lingualeo2anki   master  lingualeo2anki
lingualeo2anki: command not found
```

But now I see that `pythonPackages.pbr` is not required in `buildInputs` (seems like `pbr` integrated in `setuptools`), but `git` is required, without it I am getting error `Versioning for this project requires either an sdist tarball`, the question is why I'm getting this error when installing from github, though `git` in `buildInputs`

**Comment by FRidh** [comment]
Both `pbr` and `setuptools` can use a `setup.cfg`, however, they use different attributes. No, `pbr` is not integrated in `setuptools`; they just use the same file.

**Comment by FRidh** [comment]
I will close this because it is not a Nixpkgs issue. In any case, if you have more follow-up questions, feel free to post them here or, perhaps even better, on the #nixos IRC channel.

**Comment by BjornMelgaard** [comment]
@FRidh so you basically saying to find way without `pbr`, and I'm okay with that, without `pbr` it worked. Thanks for help.

P.S.
I don't like to ask questions in irc, since it impossible then to find solutions :)
