### ISSUE TITLE
How to make rails find libcurl?

### ISSUE THREAD

**Issue by srghma** [NixOS/nixpkgs#31607]
## Issue description
With config 

```nix
# This is the user configuration file,
# use it with https://github.com/rycee/home-manager
#
# import it in your `$HOME/.config/nixpkgs/config.nix` like this:
# ```
# let
#   dotfilesDir=/home/bjorn/.config/dotfiles;
# in
#   import "${dotfilesDir}/nixos/home/config.nix"
# ```

{ pkgs, ... }:

{
  packageOverrides = pkgs : with pkgs; {

    # \curl -L https://get.rvm.io | bash -s stable --rails --auto-dotfiles
    # gem install bundle
    # gem install pg
    # gem install nokogiri -- --use-system-libraries
    # bundle config build.nokogiri --use-system-libraries
    # bundle install

    rvmEnv = pkgs.myEnvFun {
      name = "rvm";
      buildInputs = [ stdenv pkgconfig python pythonPackages.boto procps which libyaml readline zlib openssl libxml2 libxslt libiconv postgresql curl ];
      extraCmds = ''
        unset http_proxy
        unset ftp_proxy

        # fix curl
        export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt

        # start postgresql
        export PGDATA=~/.mytmp/pgdata
        # initdb
        # pg_ctl start
        # createdb nuuz_dev

        export LIBXML2_DIR=${libxml2}
        export LIBXSLT_DIR=${libxslt}
        export LIBICONV_DIR=${libiconv}
        export OPENSSL_DIR=${openssl}
        export READLINE_DIR=${readline}
        export LIBYAML_DIR=${libyaml}
        export LOCAL_REDIS=true
        . ~/.rvm/scripts/rvm
      '';
    };

  };
}
```

I have error 

```sh
 ~/work/nuuz-backend   sergey  load-env-rvm
/nix/store/x35rjd62j6nzcmlhrdgnszyaagn69fqr-env-rvm/nix-support/setup-new-modified: line 2: u: command not found
Error: _assignFirst found no valid variant!
Error: _assignFirst found no valid variant!
/nix/store/scf9318hx6pad0wf0qx8a79h635aamfb-multiple-outputs.sh: line 13: : bad substitution
Error: _assignFirst found no valid variant!
Error: _assignFirst found no valid variant!
/nix/store/scf9318hx6pad0wf0qx8a79h635aamfb-multiple-outputs.sh: line 13: : bad substitution
/nix/store/scf9318hx6pad0wf0qx8a79h635aamfb-multiple-outputs.sh: line 13: : bad substitution
/nix/store/scf9318hx6pad0wf0qx8a79h635aamfb-multiple-outputs.sh: line 13: : bad substitution
env-rvm loaded

rvm:[bjorn@machine:~/work/nuuz-backend]$ rails s
^N/home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/ffi-1.9.14/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libcurl': libcurl: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libcurl.so': libcurl.so: cannot open shared object file: No such file or directory.
Could not open library 'libcurl.so.4': libcurl.so.4: cannot open shared object file: No such file or directory
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/ffi-1.9.14/lib/ffi/library.rb:100:in `map'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/ffi-1.9.14/lib/ffi/library.rb:100:in `ffi_lib'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/ethon-0.9.1/lib/ethon/curls/settings.rb:6:in `<module:Curl>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/ethon-0.9.1/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/ethon-0.9.1/lib/ethon/curls/settings.rb:1:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/ethon-0.9.1/lib/ethon/curl.rb:27:in `<module:Curl>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/ethon-0.9.1/lib/ethon/curl.rb:13:in `<module:Ethon>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/ethon-0.9.1/lib/ethon/curl.rb:8:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/ethon-0.9.1/lib/ethon.rb:15:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/typhoeus-1.1.0/lib/typhoeus.rb:2:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/image_info-1.1.2/lib/image_info/processor.rb:1:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/image_info-1.1.2/lib/image_info.rb:2:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/image_parser.rb:1:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/models/image.rb:2:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/base.rb:4:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/default/base.rb:1:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/default/title.rb:1:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scraper.rb:7:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/page.rb:2:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer.rb:5:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `each'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
        from /home/bjorn/work/nuuz-backend/config/application.rb:7:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from /home/bjorn/work/nuuz-backend/bin/rails:9:in `require'
        from /home/bjorn/work/nuuz-backend/bin/rails:9:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
        from /home/bjorn/.rvm/gems/ruby-2.3.0@nuuz-backend/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
        from /home/bjorn/work/nuuz-backend/bin/spring:13:in `require'
        from /home/bjorn/work/nuuz-backend/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

rvm:[bjorn@machine:~/work/nuuz-backend]$
```

How to make rails find libcurl?

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by peterhoeg** [comment]
I am using ```direnv``` to load the dependencies - this also means you no longer have to use rvm/rbenv.

**Comment by BjornMelgaard** [comment]
@peterhoeg can you show how you using it?

**Comment by peterhoeg** [comment]
It's been a long week but I was pinged on matrix so let's get this sorted.

First of all, have a look at the wiki article on [packaging ruby](https://nixos.wiki/wiki/Packaging/Ruby) applications from where most of this is copied:

Stick this in ```shell.nix```:

``` nix
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "env";
  buildInputs = [
    ruby
    curl
    git
    sqlite
    libxml2
    libxslt
    bundix
  ];
}
```

Then ```default.nix```:

```nix
{ stdenv, bundlerEnv, ruby }:

let
  gems = bundlerEnv {
    name = "app-env";
    inherit ruby;
    gemdir  = ./.;
  };

in stdenv.mkDerivation {
  name = "my-app";

  src = ./.;

  buildInputs = [ gems ruby ];

  installPhase = ''
    mkdir -p $out
    
    # bla bla bla 
  '';
}
```

And lastly, the following goes into ```.envrc```:

```sh
use nix
layout ruby
```

Now run:

```sh
direnv allow
bundle install
bundix --magic
```

```direnv``` should have loaded the environment needed for all the gems to install. If you get compilation errors, you will need to add the missing dependencies to ```shell.nix```.

**Comment by srghma** [comment]
Tnx, @peterhoeg
