### ISSUE TITLE
`briar-desktop` fails to start, reports missing `libGL.so.1`

### ISSUE THREAD

**Issue by whentze** [NixOS/nixpkgs#316116]
### Describe the bug
The `briar-desktop` package appears to be broken in unstable, 24.05 and 23.11.
At startup, it emits an error such as
```
java.lang.UnsatisfiedLinkError: /home/wanja/.skiko/27a3e4e3655eceb6ce90e5fce6b6e0a4eb1d2d60b0811e8dc617f4aca3f7b926/libskiko-linux-x64.so: libGL.so.1: cannot open shared object file: No such file or directory
```

It seems like it writes a shared library called `libskiko` to `~./skiko` at runtime that requires libGL, along with libX11 and libfontconfig.
Because this is not from the nix package, it's never patchelf-ed and thus doesn't have a `RUNPATH`.

### Steps To Reproduce
1. attempt to run `briar-desktop` on NixOS

### Expected behavior
The application starts up.

### Screenshots

Log output from trying to start the app:
```
2024-05-31 12:15:29,238 [main] INFO  org.briarproject.briar.desktop.Main - This is briar-desktop version 0.5.0-beta
2024-05-31 12:15:29,239 [main] INFO  org.briarproject.briar.desktop.Main - Build info:
2024-05-31 12:15:29,240 [main] INFO  org.briarproject.briar.desktop.Main -   Git hash 50cccb716940208c2a71257e3109d9c1cad5d53e
2024-05-31 12:15:29,240 [main] INFO  org.briarproject.briar.desktop.Main -   Commit time 2023-06-28 13:08:48
2024-05-31 12:15:29,241 [main] INFO  org.briarproject.briar.desktop.Main -   Tag 0.5.0-beta
2024-05-31 12:15:29,972 [main] WARN  org.briarproject.briar.desktop.Main - Uncaught exception in thread main
java.lang.UnsatisfiedLinkError: /home/wanja/.skiko/27a3e4e3655eceb6ce90e5fce6b6e0a4eb1d2d60b0811e8dc617f4aca3f7b926/libskiko-linux-x64.so: libGL.so.1: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2021)
	at org.jetbrains.skiko.Library.loadLibraryOrCopy(Library.kt:20)
	at org.jetbrains.skiko.Library.findAndLoad(Library.kt:113)
	at org.jetbrains.skiko.Library.load(Library.kt:59)
	at org.jetbrains.skiko.SkiaLayer.<clinit>(SkiaLayer.awt.kt:29)
	at androidx.compose.ui.awt.ComposeLayer.<init>(ComposeLayer.desktop.kt:92)
	at androidx.compose.ui.awt.ComposeWindowDelegate.<init>(ComposeWindowDelegate.desktop.kt:54)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:61)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:59)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:162)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:156)
	at androidx.compose.ui.window.Window_desktopKt$Window$10$1.invoke(Window.desktop.kt:378)
	at androidx.compose.ui.window.Window_desktopKt$Window$10$1.invoke(Window.desktop.kt:377)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:75)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:74)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1091)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:818)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:839)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:978)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Notify maintainers

@onny 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1, NixOS, 23.11 (Tapir), 23.11.7313.9d29cd266ceb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by onny** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/316361 should fix the issue :)

**Comment by whentze** [comment]
Can confirm, briar-desktop starts fine with that one :+1:

**Comment by onny** [comment]
Fixed with https://github.com/NixOS/nixpkgs/pull/395152
