### ISSUE TITLE
Calibre not launching

### ISSUE THREAD

**Issue by Soupstraw** [NixOS/nixpkgs#316346]
### Describe the bug

`calibre` does not run and gives the following error:
```
Traceback (most recent call last):
  File "/nix/store/sl6sxknc03rhsdd7ywzhzf3g52kigcj0-calibre-7.10.0/bin/.calibre-wrapped", line 22, in <module>
    sys.exit(calibre())
             ^^^^^^^^^
  File "/nix/store/sl6sxknc03rhsdd7ywzhzf3g52kigcj0-calibre-7.10.0/lib/calibre/calibre/gui_launch.py", line 74, in calibre
    main(args)
  File "/nix/store/sl6sxknc03rhsdd7ywzhzf3g52kigcj0-calibre-7.10.0/lib/calibre/calibre/gui2/main.py", line 547, in main
    run_main(app, opts, args, gui_debug, si, retry_communicate=True)
  File "/nix/store/sl6sxknc03rhsdd7ywzhzf3g52kigcj0-calibre-7.10.0/lib/calibre/calibre/gui2/main.py", line 559, in run_main
    return run_gui(opts, args, app, gui_debug=gui_debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/sl6sxknc03rhsdd7ywzhzf3g52kigcj0-calibre-7.10.0/lib/calibre/calibre/gui2/main.py", line 397, in run_gui
    run_gui_(opts, args, app, gui_debug)
  File "/nix/store/sl6sxknc03rhsdd7ywzhzf3g52kigcj0-calibre-7.10.0/lib/calibre/calibre/gui2/main.py", line 407, in run_gui_
    from calibre.gui2.ui import Main
  File "/nix/store/sl6sxknc03rhsdd7ywzhzf3g52kigcj0-calibre-7.10.0/lib/calibre/calibre/gui2/ui.py", line 50, in <module>
    from calibre.gui2.init import LayoutMixin, LibraryViewMixin
  File "/nix/store/sl6sxknc03rhsdd7ywzhzf3g52kigcj0-calibre-7.10.0/lib/calibre/calibre/gui2/init.py", line 37, in <module>
    from calibre.gui2.library.alternate_views import GridView
  File "/nix/store/sl6sxknc03rhsdd7ywzhzf3g52kigcj0-calibre-7.10.0/lib/calibre/calibre/gui2/library/alternate_views.py", line 18, in <module>
    from PIL import Image
  File "/nix/store/bnkg9gk85zn8q37phhiiacrr407lqp7k-python3.11-pillow-10.3.0/lib/python3.11/site-packages/PIL/Image.py", line 88, in <module>
    from . import _imaging as core
ImportError: /nix/store/ic5bx78h039m3lfxxb6bl64qlbdxzzj9-libtiff-4.6.0/lib/libtiff.so.6: undefined symbol: jpeg12_read_raw_data, version LIBJPEG_6.2
```

### Steps To Reproduce
Run `nix run nixpkgs#calibre`

### Expected behavior
I expect `calibre` to launch

### Notify maintainers

@kilianar @pSub 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.05 (Stoat), 23.05.20240103.70bdade`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(sherk): `"nixos-23.05, unstable"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
This is most likely the issue:

> host os: `Linux 6.1.69, **NixOS, 23.05** (Stoat)

Have you thought about upgrading to a more recent version, e.g. 24.05 which just came out?

**Comment by Soupstraw** [comment]
Oh nice, that fixed the error, thanks!
