### ISSUE TITLE
anki fails to start with No module named BeautifulSoup

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#31786]
## Issue description

Wanted to try anki so I installed it but on launch anki triggers
```

Traceback (most recent call last):
  File "/nix/store/lw7z3zdwcz57x3p7485vv3kvvn608mrc-anki-2.0.47/bin/.anki-wrapped", line 3, in <module>
    import aqt
  File "/nix/store/lw7z3zdwcz57x3p7485vv3kvvn608mrc-anki-2.0.47/lib/python2.7/site-packages/aqt/__init__.py", line 79, in <module>
    dialogs = DialogManager()
  File "/nix/store/lw7z3zdwcz57x3p7485vv3kvvn608mrc-anki-2.0.47/lib/python2.7/site-packages/aqt/__init__.py", line 46, in __init__
    from aqt import addcards, browser, editcurrent
  File "/nix/store/lw7z3zdwcz57x3p7485vv3kvvn608mrc-anki-2.0.47/lib/python2.7/site-packages/aqt/addcards.py", line 13, in <module>
    import aqt.editor, aqt.modelchooser, aqt.deckchooser
  File "/nix/store/lw7z3zdwcz57x3p7485vv3kvvn608mrc-anki-2.0.47/lib/python2.7/site-packages/aqt/editor.py", line 21, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup

```
beautfiulsoup is packaged but I suspect it' due to python oddities
@the-kenny

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.12, NixOS, 18.03.git.203c952 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.1502.19879836d1"`
 - channels(teto): `"nixos-18.03pre120249.9ea242c617"`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by adisbladis** [comment]
This is fixed in commit https://github.com/NixOS/nixpkgs/commit/c28911e0f99100b588b5392c9a9d86435957c2c6

I can see your channel is at https://github.com/NixOS/nixpkgs-channels/commit/9ea242c617 which does not contain this fix.

**Comment by teto** [comment]
indeed that fixed it thanks !
