### ISSUE TITLE
The `rerun` binary from `rerun-sdk` fail to start the standalone viewer and the web viewer

### ISSUE THREAD

**Issue by breakds** [NixOS/nixpkgs#319165]
### Describe the bug

On 24.05, I was able to use the binary `rerun` from `pkgs.rerun` to start rerun with or without `--web-viewer`. 

```console
$ rerun --web-viewer /path/to/my.rrd
```

```console
$ rerun /path/to/my.rrd
```

Both commands above works.

The python package [rerun-sdk](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/python-modules/rerun-sdk/default.nix) provides a `rerun` binary as well. However, this binary cannot start the viewer in either way:

```console
$ rerun --web-viewer /path/to/my.rrd
[2024-06-11T23:26:52Z INFO  re_data_source::load_file] Loading "/home/breakds/tmp/aloha_sim_transfer/lerobot_aloha_sim_transfer_cube_human_episode_0.rrd"…
Traceback (most recent call last):
  File "/nix/store/jfsqj2gybc4rc1b9lyrfgbxv81p48z0s-python3.11-rerun-sdk-0.13.0/bin/.rerun-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
RuntimeError: Can't host web-viewer - rerun was not compiled with the 'web_viewer' feature
```
```console
$ rerun /path/to/my.rrd
[2024-06-11T23:38:52Z INFO  re_data_source::load_file] Loading "/home/breakds/tmp/aloha_sim_transfer/lerobot_aloha_sim_transfer_cube_human_episode_0.rrd"…
Traceback (most recent call last):
  File "/nix/store/jfsqj2gybc4rc1b9lyrfgbxv81p48z0s-python3.11-rerun-sdk-0.13.0/bin/.rerun-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
RuntimeError: winit EventLoopError: the requested operation is not supported by Winit -> the requested operation is not supported by Winit
```

### Steps To Reproduce

```nix
# This will not work
let python-env = pkgs.python3.withPackages (pyPkgs: with pyPkgs; [
          rerun-sdk
        ]);

        name = "myproject";
      in pkgs.mkShell {
        inherit name;

        packages = [
          python-env
        ];
      };
```

```nix
# This works
let name = "myproject";
      in pkgs.mkShell {
        inherit name;

        packages = [
          pkgs.rerun
        ];
      };
```

### Expected behavior

The `rerun` binary from both the standard package `pkgs.rerun` and `python3Packages.rerun-sdk` should both work as expected.

### Notify maintainers

@SomeoneSerge Forgive me if I am notifying the wrong maintainer. 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.81, NixOS, 23.11 (Tapir), 23.11.20240308.2be119a`

 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SomeoneSerge** [comment]
To begin with, I think we should split `python3Packages.rerun-sdk`'s outputs, at the least, into `[ "out" "bin" ]`. Then you could use the full-featured binary from the top-level along with the python module

RE: web viewer

H'm, I think we're letting `maturin` select default features.

RE: standalone viewer

Seems to work for me:

<details>

```
❯ nix flake metadata nixpkgs
...
Path:          /nix/store/z71lmgd0ydfnax1b13zbrls5idf1y7ak-source
Revision:      bfb7a882678e518398ce9a31a881538679f6f092
Last modified: 2024-05-24 00:06:08
❯ nix shell nixpkgs#python3Packages.rerun-sdk
❯ rerun
[2024-06-12T16:30:56Z INFO  egui_wgpu] There were 2 available wgpu adapters: {backend: Vulkan, device_type: IntegratedGpu, name: "Intel(R) Xe Graphics (TGL GT2)", driver: "Intel open-source Mesa driver", driver_info: "Mesa 24.0.7", vendor: 0x8086, device: 0x9A49}, {backend: Vulkan, device_type: Cpu, name: "llvmpipe (LLVM 17.0.6, 256 bits)", driver: "llvmpipe", driver_info: "Mesa 24.0.7 (LLVM 17.0.6)", vendor: 0x10005}
[2024-06-12T16:30:56Z INFO  tracing::span] perform;
[2024-06-12T16:30:56Z INFO  zbus::handshake] write_command; command=Auth(Some(External), Some([49, 48, 48, 48]))
[2024-06-12T16:30:56Z INFO  tracing::span] read_command;
[2024-06-12T16:30:56Z INFO  zbus::handshake] write_command; command=NegotiateUnixFD
[2024-06-12T16:30:56Z INFO  tracing::span] read_command;
[2024-06-12T16:30:56Z INFO  zbus::handshake] write_command; command=Begin
[2024-06-12T16:30:56Z INFO  tracing::span] socket reader;
[2024-06-12T16:30:56Z INFO  tracing::span] perform;
[2024-06-12T16:30:56Z INFO  zbus::handshake] write_command; command=Auth(Some(External), Some([49, 48, 48, 48]))
[2024-06-12T16:30:56Z INFO  tracing::span] read_command;
[2024-06-12T16:30:56Z INFO  zbus::handshake] write_command; command=NegotiateUnixFD
[2024-06-12T16:30:56Z INFO  tracing::span] read_command;
[2024-06-12T16:30:56Z INFO  zbus::handshake] write_command; command=Begin
[2024-06-12T16:30:56Z INFO  tracing::span] socket reader;
[2024-06-12T16:30:56Z INFO  zbus::connection] {}; obj_server_task_name="ObjectServer task"
[2024-06-12T16:30:56Z INFO  zbus::object_server] dispatch_message; msg=Msg { type: MethodCall, sender: UniqueName(Str(Borrowed(":1.1"))), path: ObjectPath("/org/a11y/atspi/accessible/root"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus.Properties"))), member: MemberName(Str(Borrowed("Set"))), body: Signature("ssv") }
[2024-06-12T16:30:56Z INFO  zbus::object_server] dispatch_method_call; msg=Msg { type: MethodCall, sender: UniqueName(Str(Borrowed(":1.1"))), path: ObjectPath("/org/a11y/atspi/accessible/root"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus.Properties"))), member: MemberName(Str(Borrowed("Set"))), body: Signature("ssv") }
[2024-06-12T16:30:56Z INFO  zbus::object_server] dispatch_method_call_try; msg=Msg { type: MethodCall, sender: UniqueName(Str(Borrowed(":1.1"))), path: ObjectPath("/org/a11y/atspi/accessible/root"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus.Properties"))), member: MemberName(Str(Borrowed("Set"))), body: Signature("ssv") }
```

Same when I use `github:NixOS/nixpkgs-unstable` and for `github:NixOS/nixos-24.05`

</details>

Could something be wrong with your local X/Wayland set-up?

**Comment by breakds** [comment]
> To begin with, I think we should split python3Packages.rerun-sdk's outputs, at the least, into [ "out" "bin" ]. Then you could use the full-featured binary from the top-level along with the python module

I was under the impression that python packages do not in general split the outputs. Thanks for mentioning that. My understanding is that in this case I can probably just ignore `rerun-sdk`'s bin and put `pkgs.rerun` in my devshell.

> Could something be wrong with your local X/Wayland set-up?

It could be, although I think the likelihood is low because 

1. `pkgs.rerun` works as expected
2. I am not running Wayland
3. The `web-viewer` error message `rerun was not compiled with the 'web_viewer' feature` seems to suggest this is not about X

I tried the same, which leads to:

```console
$ nix flake metadata nixpkgs
Resolved URL:  github:NixOS/nixpkgs/nixpkgs-unstable
Locked URL:    github:NixOS/nixpkgs/e913ae340076bbb73d9f4d3d065c2bca7caafb16
Description:   A collection of packages for the Nix package manager
Path:          /nix/store/63lvc59rjz075kb1f11xww2x2xqpw1pn-source
Revision:      e913ae340076bbb73d9f4d3d065c2bca7caafb16
Last modified: 2024-06-11 16:38:24
```

and 

```console
$ nix shell nixpkgs#python3Packages.rerun-sdk
$ rerun
Traceback (most recent call last):
  File "/nix/store/9ks8mlfihd9rcn2nvim56yq0ylbq03bj-python3.11-rerun-sdk-0.13.0/bin/.rerun-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
RuntimeError: winit EventLoopError: the requested operation is not supported by Winit -> the requested operation is not supported by Winit
```

and

```console
$ rerun --web-viewer ~/tmp/xarm/lerobot_xarm_lift_medium_image_episode_0.rrd
[2024-06-12T16:55:05Z INFO  re_data_source::load_file] Loading "/home/breakds/tmp/xarm/lerobot_xarm_lift_medium_image_episode_0.rrd"…
Traceback (most recent call last):
  File "/nix/store/9ks8mlfihd9rcn2nvim56yq0ylbq03bj-python3.11-rerun-sdk-0.13.0/bin/.rerun-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
RuntimeError: Can't host web-viewer - rerun was not compiled with the 'web_viewer' feature
```

I am not sure whether it is because the nixpkgs branch is too new.

**Comment by SomeoneSerge** [comment]
> The web-viewer error message rerun was not compiled with the 'web_viewer' feature seems to suggest this is not about X

As I already suggested, the `--web-viewer` issue must be independent of the standalone mode. The `--web-viewer` is disabled because that's how `maturin` built the project. You need to figure out how to pass the extra `--feature` options through to make it work.

The standalone app must be breaking because of something like  X/Wayland/GL/Vulkan. The standalone app works fine for me on wayland with intel integrated graphics. Why don't you start by describing your set-up and by running `LD_DEBUG=libs rerun` (no `--web-viewer`)

**Comment by breakds** [comment]
> The --web-viewer is disabled because that's how maturin built the project. You need to figure out how to pass the extra --feature options through to make it work.

I see, I can try to figure that out.

> The standalone app must be breaking because of something like X/Wayland/GL/Vulkan. The standalone app works fine for me on wayland with intel integrated graphics. Why don't you start by describing your set-up and by running LD_DEBUG=libs rerun (no --web-viewer)

I tried `LD_DEBUG=libs` but it does not provide more information. The only useful message so far is about `Winit`. What confuses me is that `pkgs.rerun` works fine.
