### ISSUE TITLE
Calibre: sending mails fails

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#31935]
## Issue description

Sending a file via mails fails

```
calibre, version 3.7.0 (linux2, embedded-python: False)
Failed to email book: Failed: Email LWN.net Weekly Edition to [private]@kindle.com

Starting job: Email LWN.net Weekly Edition to [private]@kindle.com 

Sending failed...
 
Traceback (most recent call last):
  File "/nix/store/4fwyi4ch9lk4lg4556rm06kg1jkgmrwz-calibre-3.7.0/lib/calibre/calibre/gui2/email.py", line 44, in run
    self.func(*self.args)
  File "/nix/store/4fwyi4ch9lk4lg4556rm06kg1jkgmrwz-calibre-3.7.0/lib/calibre/calibre/gui2/email.py", line 134, in sendmail
    debug_output=safe_debug)
  File "/nix/store/4fwyi4ch9lk4lg4556rm06kg1jkgmrwz-calibre-3.7.0/lib/calibre/calibre/utils/smtp.py", line 135, in sendmail
    return sendmail_direct(from_, x, msg, timeout, localhost, verbose)
  File "/nix/store/4fwyi4ch9lk4lg4556rm06kg1jkgmrwz-calibre-3.7.0/lib/calibre/calibre/utils/smtp.py", line 108, in sendmail_direct
    hosts = get_mx(to.split('@')[-1].strip(), verbose)
  File "/nix/store/4fwyi4ch9lk4lg4556rm06kg1jkgmrwz-calibre-3.7.0/lib/calibre/calibre/utils/smtp.py", line 96, in get_mx
    import dns.resolver
ImportError: No module named dns.resolver
 
[...]
```

### Steps to reproduce

Add ebook, configure E-Mail support, send E-Book via Mail.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.63, NixOS, 17.09.git.3c5ed8d (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2138.48bf1f43cd, nixos-unstable-18.03pre120540.b8f7027360"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Moredread** [comment]
Adding dns as a dependency fixes it, I'll create a PR.

**Comment by FRidh** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/31936.
