### ISSUE TITLE
Build failure: salt version override on channel 24.05

### ISSUE THREAD

**Issue by dgengtek** [NixOS/nixpkgs#319613]
### Steps To Reproduce

Did python install change?

Python package salt override with older versions on channel 24.05 does not work.

```
:b (import
    (builtins.fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/nixos-24.05.tar.gz";
    })
    {
      overlays = [
        (final: prev:
          {
            salt = prev.salt.overrideAttrs (old: rec {
              name = "${pname}-${version}";
              pname = "salt";
              version = "3006.8";
              src = prev.fetchPypi {
                inherit pname version;
                hash = "sha256-MWKZBcjXhL25eGtqP3f5qHMwvFbXtovryaGUctnv2GY=";
              };
            });
          })
      ];
    }).salt
```

### Build log

```
adding 'salt-3006.8.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Finished executing setuptoolsBuildPhase
@nix { "action": "setPhase", "phase": "installPhase" }
Running phase: installPhase
Executing pypaInstallPhase
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/nix/store/jiy26cv72hl813md1v29k7673va0q0ka-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/nix/store/jiy26cv72hl813md1v29k7673va0q0ka-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/__main__.py", line 94, in _main
    installer.install(source, destination, {})
  File "/nix/store/jiy26cv72hl813md1v29k7673va0q0ka-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/_core.py", line 109, in install
    record = destination.write_file(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jiy26cv72hl813md1v29k7673va0q0ka-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/destinations.py", line 203, in write_file
    return self.write_to_fs(
           ^^^^^^^^^^^^^^^^^
  File "/nix/store/jiy26cv72hl813md1v29k7673va0q0ka-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/destinations.py", line 167, in write_to_fs
    raise FileExistsError(message)
FileExistsError: File already exists: /nix/store/dxwma3h7cp4h28p84kv3z1gkfqb6cscg-salt-3006.8/bin/salt
```

### Additional context

The override works with channel 23.11

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
It's unreasonable to expect that nixpkgs would support versions of a package that _aren't_ in nixpkgs. If you need an older version, you may have to just copy the package expression, edit, and `callPackage` it yourself.

**Comment by dgengtek** [comment]
You are correct. Was pretty new to nix and now I know that an override is not enough when package definitions change. Eg using nixpkgs rev 336eda0d07dc5e2be1f923990ad9fdb6bc8e28e3 works
