### ISSUE TITLE
Build failure: zed-editor

### ISSUE THREAD

**Issue by tqwewe** [NixOS/nixpkgs#320084]
### Steps To Reproduce

Zed-editor fails to build for MaxOS Intel using `NIXPKGS_ALLOW_BROKEN=1 nix-shell -p zed-editor -I nixpkgs=channel:nixos-unstable`

### Build log

```
  ...
  cargo:rerun-if-changed=/nix/store/xz8j1amvgwas4nbfqgpmcz147pkd391s-apple-framework-VideoToolbox/Library/Frameworks/VideoToolbox.framework/Headers/VTBase.h
  cargo:rerun-if-changed=/nix/store/wahwaqbn6f57ybai7akc5920vrln9s2j-apple-framework-CoreFoundation/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h
  cargo:rerun-if-changed=/nix/store/xz8j1amvgwas4nbfqgpmcz147pkd391s-apple-framework-VideoToolbox/Library/Frameworks/VideoToolbox.framework/Headers/VTErrors.h

  --- stderr
  thread 'main' panicked at /private/tmp/nix-build-zed-0.137.6.drv-0/cargo-vendor-dir/bindgen-0.65.1/ir/ty.rs:1074:22:
  Not able to resolve array element?: Continue
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: builder for '/nix/store/dv6kd8ljw54aw4j728cy97mqg0jxlv6y-zed-0.137.6.drv' failed with exit code 101;
       last 10 log lines:
       >   cargo:rerun-if-changed=/nix/store/a5swqw43q2yahpawgwbrsgildzqni5n1-apple-framework-CoreMedia/Library/Frameworks/CoreMedia.framework/Headers/CMBase.h
       >   cargo:rerun-if-changed=/nix/store/xz8j1amvgwas4nbfqgpmcz147pkd391s-apple-framework-VideoToolbox/Library/Frameworks/VideoToolbox.framework/Headers/VTBase.h
       >   cargo:rerun-if-changed=/nix/store/wahwaqbn6f57ybai7akc5920vrln9s2j-apple-framework-CoreFoundation/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h
       >   cargo:rerun-if-changed=/nix/store/xz8j1amvgwas4nbfqgpmcz147pkd391s-apple-framework-VideoToolbox/Library/Frameworks/VideoToolbox.framework/Headers/VTErrors.h
       >
       >   --- stderr
       >   thread 'main' panicked at /private/tmp/nix-build-zed-0.137.6.drv-0/cargo-vendor-dir/bindgen-0.65.1/ir/ty.rs:1074:22:
       >   Not able to resolve array element?: Continue
       >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/dv6kd8ljw54aw4j728cy97mqg0jxlv6y-zed-0.137.6.drv'.
```

### Notify maintainers

@GaetanLepage 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - channels(ari): `"darwin"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by matteo-pacini** [comment]
More about the build error here: https://github.com/NixOS/nixpkgs/pull/303233#issuecomment-2048650618

The Swift package is in `crates/live_kit_client/LiveKitBridge` - perhaps removing `xcrun` and adding `swift swiftpm` to the build inputs may fix this.
Another possibility is to integrate `swiftpm2nix`.

**Comment by niklaskorz** [comment]
Building the Swift package will soon become unnecessary, as mentioned in my comment referenced by Gaétan. Unfortunately we'll have to wait for https://github.com/NixOS/nixpkgs/pull/229210 as Livekit depends on ScreenCaptureKit on macOS.

**Comment by jvmncs** [comment]
Looks like https://github.com/NixOS/nixpkgs/pull/326406 merged early support for apple_sdks 12.3 -- would that resolve the blocker you mentioned @niklaskorz?

**Comment by niklaskorz** [comment]
> Looks like #326406 merged early support for apple_sdks 12.3 -- would that resolve the blocker you mentioned @niklaskorz?

Draft PR is available at #329653 but is blocked until https://github.com/zed-industries/zed/pull/13343 is merged and released. As the draft is based on that PR branch, it however already builds and runs:

```
$ nix build "github:nixos/nixpkgs?ref=pull/329653/head#zed-editor"
$ result/libexec/zed-editor
```

<img width="1136" alt="grafik" src="https://github.com/user-attachments/assets/11a3ecf0-4a03-4307-aa17-ecf769a40f44">

**Comment by niklaskorz** [comment]
#329653 is now ready for review, fixing the latest Zed release on macOS. Livekit (and thus collaboration features) remains disabled on both macOS and Linux until https://github.com/zed-industries/zed/pull/13343 is released.

**Comment by niklaskorz** [comment]
This was fixed a few months ago in #329653
