### ISSUE TITLE
AttributeError when running vimPluginUpdater

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#320151]
### Describe the bug
An uncaught `AttributeError` exception is raised when running the vimPluginUpdater script

### Steps To Reproduce
1. Run the vim plugin update script with
```shell
nix run .\#vimPluginsUpdater                                                                                                      :(
```

### Expected behavior
The script should not raise an exception

### Additional context
Eception:
```
Traceback (most recent call last):
  File "/nix/store/lhrlb9zgxp114d7m8x0zqhxaq2xgvp8x-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 174, in <module>
    main()
  File "/nix/store/lhrlb9zgxp114d7m8x0zqhxaq2xgvp8x-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 170, in main
    editor.run()
  File "/nix/store/lhrlb9zgxp114d7m8x0zqhxaq2xgvp8x-vim-plugins-updater-0.1/lib/pluginupdate.py", line 567, in run
    getattr(self, command)(args)
  File "/nix/store/lhrlb9zgxp114d7m8x0zqhxaq2xgvp8x-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 129, in update
    pluginupdate.update_plugins(self, args)
  File "/nix/store/lhrlb9zgxp114d7m8x0zqhxaq2xgvp8x-vim-plugins-updater-0.1/lib/pluginupdate.py", line 791, in update_plugins
    redirects = update()
                ^^^^^^^^
  File "/nix/store/lhrlb9zgxp114d7m8x0zqhxaq2xgvp8x-vim-plugins-updater-0.1/lib/pluginupdate.py", line 432, in update
    plugins = self.load_plugin_spec(config, input_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lhrlb9zgxp114d7m8x0zqhxaq2xgvp8x-vim-plugins-updater-0.1/lib/pluginupdate.py", line 421, in load_plugin_spec
    return load_plugins_from_csv(config, plugin_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lhrlb9zgxp114d7m8x0zqhxaq2xgvp8x-vim-plugins-updater-0.1/lib/pluginupdate.py", line 324, in load_plugins_from_csv
    plugin = PluginDesc.load_from_csv(config, line)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lhrlb9zgxp114d7m8x0zqhxaq2xgvp8x-vim-plugins-updater-0.1/lib/pluginupdate.py", line 270, in load_from_csv
    repo = make_repo(row["repo"], branch.strip())
                                  ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 24.11 (Vicuña), 24.11.20240605.e8057b6`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - channels(lunik1): `""`
 - nixpkgs: `/nix/store/8s55w0927lh3mdbkxf434zb0c5hqsz8z-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nicolas-goudry** [comment]
This is because the `vim-plugin-names` file has been corrupted by [this PR](https://github.com/NixOS/nixpkgs/commit/3802a937da577a99662c86ba36398b588e501f59).

I’ll send a PR to fix this in a bit.

**Comment by rkochar** [comment]
I seem to have the problem again. Followed the steps [here](https://discourse.nixos.org/t/adding-new-neovim-to-nixpkgs/34834/2).
```
[nix-shell:/home/rkochar/Projects/nixpkgs]# vim-plugins-updater
Traceback (most recent call last):
  File "/nix/store/p6vsfgajikjdlbspv37yaid1iv0l0w96-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 183, in <module>
    main()
  File "/nix/store/p6vsfgajikjdlbspv37yaid1iv0l0w96-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 179, in main
    editor.run()
  File "/nix/store/xibmvar7r9228dhpgl5bbzpq5r5n26s5-pluginupdate-py/pluginupdate.py", line 691, in run
    getattr(self, command)(args)
  File "/nix/store/p6vsfgajikjdlbspv37yaid1iv0l0w96-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 132, in update
    pluginupdate.update_plugins(self, args)
  File "/nix/store/xibmvar7r9228dhpgl5bbzpq5r5n26s5-pluginupdate-py/pluginupdate.py", line 929, in update_plugins
    update = editor.get_update(
             ^^^^^^^^^^^^^^^^^^
  File "/nix/store/xibmvar7r9228dhpgl5bbzpq5r5n26s5-pluginupdate-py/pluginupdate.py", line 500, in get_update
    current_plugin_specs = self.load_plugin_spec(config, input_file)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xibmvar7r9228dhpgl5bbzpq5r5n26s5-pluginupdate-py/pluginupdate.py", line 450, in load_plugin_spec
    return load_plugins_from_csv(config, plugin_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xibmvar7r9228dhpgl5bbzpq5r5n26s5-pluginupdate-py/pluginupdate.py", line 324, in load_plugins_from_csv
    plugin = PluginDesc.load_from_csv(config, line)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xibmvar7r9228dhpgl5bbzpq5r5n26s5-pluginupdate-py/pluginupdate.py", line 265, in load_from_csv
    repo = make_repo(row["repo"], branch.strip())
                                  ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```
