### ISSUE TITLE
Package request: terminalizer

### ISSUE THREAD

**Issue by jab** [NixOS/nixpkgs#320310]
**Project description**

Record your terminal and generate animated gif images or share a web player

**Metadata**

* homepage URL: https://www.terminalizer.com
* source URL: https://github.com/faressoft/terminalizer
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jkachmar** [comment]
naïve attempt:

<details> <summary> derivation.nix </summary>

```nix
{
    lib,
    mkYarnPackage,
    fetchFromGitHub,
    fetchYarnDeps,
    makeWrapper,
    electron,
}: mkYarnPackage rec {
  dontStrip = true;

  pname = "terminalizer";
  version = "0.12.0";

  src = fetchFromGitHub {
    owner = "faressoft";
    repo = "terminalizer";
    rev = "refs/tags/v${version}";
    hash = "sha256-voyWAQMS+L8I2OR32YysRr9l2yNJ87Ffl6Svh1JbY9I=";
  };

  packageJSON = "${src}/package.json";
  yarnLock = "${src}/yarn.lock";

  offlineCache = fetchYarnDeps {
    yarnLock = "${src}/yarn.lock";
    hash = "sha256-kTAi3ucCjKctQqnWgtqb7cG+ICvD27r8tq4WbfGTCkU=";
  };

  nativeBuildInputs = [ makeWrapper ];

  postInstall = ''
    rm $out/bin/terminalizer
    makeWrapper ${electron}/bin/electron "$out/bin/terminalizer" \
      --add-flags "$out/libexec/terminalizer/deps/terminalizer/bin/app.js"
  '';
}
```

</details>

failed with the following error:

<details> <summary> node-pty error </summary>

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/prebuild-loader.js
- /nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/unixTerminal.js
- /nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/index.js
- /nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/deps/terminalizer/app.js
- /nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/deps/terminalizer/bin/app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:124107)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/prebuild-loader.js:10:15)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/prebuild-loader.js',
    '/nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/unixTerminal.js',
    '/nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/index.js',
    '/nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/deps/terminalizer/app.js',
    '/nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/deps/terminalizer/bin/app.js'
  ]
}
App threw an error during load
Error: Cannot find module '../build/Release/pty.node'
Require stack:
- /nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/prebuild-loader.js
- /nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/unixTerminal.js
- /nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/index.js
- /nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/deps/terminalizer/app.js
- /nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/deps/terminalizer/bin/app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:124107)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/nix/store/wygcykwbhk99c3yyhlbjymqsc8dlxy7d-terminalizer-0.12.0/libexec/terminalizer/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/prebuild-loader.js:6:11)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
```

</details>

presumably there's a way to get `node-pty` to build as-expected, or perhaps I didn't cargo-cult the `yarn` package build quite right.
