### ISSUE TITLE
libvirt: Can't migrate a VM to NixOS

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#32086]
## Issue description

I have a VM running on my Ubuntu 16.04 machine using `libvirt`/`virt-manager`.

I want to use `virt-manager`'s migration feature to move the VM to another host. The other host is a NixOS machine.

If I start the migration, I immediately get `Unable to migrate guest: Cannot check QEMU binary /usr/bin/kvm-spice: No such file or directory`.

Looks like the migrator expects certain programs in certain locations.

I wonder what we can do to make this work.

**Comment by nh2** [comment]
Details:

```
Unable to migrate guest: Cannot check QEMU binary /usr/bin/kvm-spice: No such file or directory

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 90, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/migrate.py", line 438, in _async_migrate
    meter=meter)
  File "/usr/share/virt-manager/virtManager/domain.py", line 1488, in migrate
    self._backend.migrate(libvirt_destconn, flags, None, interface, 0)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 1535, in migrate
    if ret is None:raise libvirtError('virDomainMigrate() failed', dom=self)
libvirtError: Cannot check QEMU binary /usr/bin/kvm-spice: No such file or directory
```

**Comment by nh2** [comment]
Hmm, looks like that the specific path `/usr/bin/kvm-spice` is something that's part of my VM.

In my case, `/etc/libvirt/qemu/MSEdge.xml` contains:

```
...
<emulator>/usr/bin/kvm-spice</emulator>
...
```

**Comment by nh2** [comment]
Does anybody know which nixpkg would provide me with `kvm-spice`?

**Comment by nh2** [comment]
> Does anybody know which nixpkg would provide me with kvm-spice?

Ah. It's just a symlink.

```
% ls -lah /usr/bin/kvm-spice 
lrwxrwxrwx 1 root root 3 Sep 20 16:02 /usr/bin/kvm-spice -> kvm*
```

**Comment by orivej** [comment]
It's `qemu-system-x86_64` on NixOS.

**Comment by teto** [comment]
nh2, you can install nix-index/nix-locate to find the package from the binary name

**Comment by volth** [comment]
AFAIR, migration requires same ```qemu``` version installed at the same location.
There were similar  issues with ```CentOS```<->```Debian``` migratrions

**Comment by Syndamia** [comment]
On NixOS the *best* path to the binary is `/run/current-system/sw/bin/qemu-system-x86_64`. Since every package is stored in `/nix/store/hash-packagename-version`, and the hash can change with package versions or with different compile-time settings, `/run/current-system/sw` provides a "generic" path to all binaries.

Just modify the config file with `virsh edit MSEdge` (you can list the names of your virtual machines with `virsh list --all`) and update

```xml
<emulator>/usr/bin/kvm-spice</emulator>
```

to 

```xml
<emulator>/run/current-system/sw/bin/qemu-system-x86_64</emulator>
```

If you are using the virtual machine on more than one OS, and you need that line to stay the same, then it may be worth creating an identical config, with the difference being that `emulator` line (you may need to run these commands with `sudo`):

```bash
virsh dumpxml MSEdge > newvm.xml  # Copy MSEdge config to newvm.xml
$EDITOR newvm.xml                 # Edit newvm.xml (change the emulator line; feel free to use your text editor of choice, instead of $EDITOR)
virsh create newvm.xml            # Add the new virtual machine
```

Finally, there is the possibility of updating the `/usr/bin/kvm-spice` symlink, so it points to the aforementioned path, but I would vote against it.

In any case, this is more of a personal configuration issue than a NixOS issue, so I would say this can be marked as resolved.

**Comment by tomodachi94** [comment]
It looks like libvirt has a NixOS module; is there any way we can preset a working configuration value in that file?

If not, I agree with the previous comment that this should be closed.
