### ISSUE TITLE
`shell_interact` issue collection

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#320919]
### Describe the bug

The shell produced by running `NODE.shell_interact()` in a NixOS test is difficult to use, because it behaves differently from a "normal" shell in various ways.

### Steps To Reproduce

1. Run `sed --in-place --expression='/start_all()/a\      server.shell_interact()' nixos/tests/ssh-audit.nix`
2. `"$(nix-build -A nixosTests.ssh-audit.driver)/bin/nixos-test-driver"`
3. Interact with the debug shell

### Expected behavior

The debug shell should work more or less like a normal Bash shell.

### Additional context

Issues found so far:

- No prompt appears until I start typing (this seems to be a known issue, as the last message before the prompt is "Terminal is ready (there is no initial prompt)").
- Pressing <kbd>Enter</kbd> on the inner shell adds the empty command to the shell history. Combined with the issue above this means if I press <kbd>Enter</kbd> to check whether the command has finished yet (by checking for a prompt appearing), that adds noise to the shell history.
- Pressing <kbd>Ctrl-c</kbd> on the inner shell terminates the entire test run, when instead it should simply cancel the current shell command and print another prompt. I assume this means the signal is caught by one of the surrounding processes rather than the inner shell.
- After exiting the test driver by pressing <kbd>Ctrl-c</kbd>, the outer shell is also broken in *some* situations. The last time I was able to reproduce this I waited for the boot messages to quiet down, pressed <kbd>Enter</kbd> to redraw the prompt, *typed* "pwd" but didn't run it, then pressed <kbd>Ctrl-c</kbd>. At this point, anything I type no longer shows up in the terminal, although the cursor indicates that *something* is still registering key presses. The test driver output:

   ```
   $ pwd
   /tmp
    terminating on signal 2qemu-kvm:
    terminating on signal 2
   server: waiting for TCP port 22 on localhost
   cleanup
   kill machine (pid 3256455)
   kill machine (pid 3256478)
   (finished: cleanup, in 0.00 seconds)
   Traceback (most recent call last):
     File "/nix/store/9k4sa6w3mv8s6n97an3g63f5mkrhbxz6-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
       sys.exit(main())
                ^^^^^^
     File "/nix/store/9k4sa6w3mv8s6n97an3g63f5mkrhbxz6-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/__init__.py", line 146, in main
       driver.run_tests()
     File "/nix/store/9k4sa6w3mv8s6n97an3g63f5mkrhbxz6-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 166, in run_tests
       self.test_script()
     File "/nix/store/9k4sa6w3mv8s6n97an3g63f5mkrhbxz6-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 158, in test_script
       exec(self.tests, symbols, None)
     File "<string>", line 4, in <module>
     File "/nix/store/9k4sa6w3mv8s6n97an3g63f5mkrhbxz6-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 762, in wait_for_open_port
       retry(port_is_open, timeout)
     File "/nix/store/9k4sa6w3mv8s6n97an3g63f5mkrhbxz6-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 129, in retry
       if fn(False):
          ^^^^^^^^^
     File "/nix/store/9k4sa6w3mv8s6n97an3g63f5mkrhbxz6-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 758, in port_is_open
       status, _ = self.execute(f"nc -z {addr} {port}")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/nix/store/9k4sa6w3mv8s6n97an3g63f5mkrhbxz6-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 534, in execute
       self.shell.send(out_command.encode())
   BrokenPipeError: [Errno 32] Broken pipe
   kill vlan (pid 3256453)
   ```

### Notify maintainers

@alyssais @ElvishJerricco @K900

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.11 (Vicuña), 24.11pre638038.57d6973abba7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
It's a debug tool, and not a particularly good one. Why not just use the serial console in QEMU?

**Comment by l0b0** [comment]
> It's a debug tool, and not a particularly good one. Why not just use the serial console in QEMU?

Considering the first several search engine results for "serial console in QEMU" don't come up with any trivial answers, would you be willing to give a hint as to how to find more information?

**Comment by K900** [comment]
You probably want to build `.driverInteractive`, then run that. It'll give you an interactive QEMU window, where you can just switch to a serial console and get a real shell.
