### ISSUE TITLE
kitty terminal needs xsel

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#32155]
## Issue description
Launch the terminal emulator kitty from another terminal, try to select some text and you will see
```

Traceback (most recent call last):
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/boss.py", line 292, in set_primary_selection
    set_primary_selection(text)
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/utils.py", line 156, in set_primary_selection
    p = subprocess.Popen(['xsel', '-i', '-p'], stdin=s
Traceback (most recent call last):
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/boss.py", line 292, in set_primary_selection
    set_primary_selection(text)
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/utils.py", line 156, in set_primary_selection
    p = subprocess.Popen(['xsel', '-i', '-p'], stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/nix/store/166s7l3yjqfc8dj5hfqjb09dbfvp1850-python3-3.6.3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/nix/store/166s7l3yjqfc8dj5hfqjb09dbfvp1850-python3-3.6.3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xsel': 'xsel'
Traceback (most recent call last):
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/boss.py", line 292, in set_primary_selection
    set_primary_selection(text)
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/utils.py", line 156, in set_primary_selection
    p = subprocess.Popen(['xsel', '-i', '-p'], stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/nix/store/166s7l3yjqfc8dj5hfqjb09dbfvp1850-python3-3.6.3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/nix/store/166s7l3yjqfc8dj5hfqjb09dbfvp1850-python3-3.6.3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xsel': 'xsel'ubprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/nix/store/166s7l3yjqfc8dj5hfqjb09dbfvp1850-python3-3.6.3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/nix/store/166s7l3yjqfc8dj5hfqjb09dbfvp1850-python3-3.6.3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xsel': 'xsel'
Traceback (most recent call last):
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/boss.py", line 292, in set_primary_selection
    set_primary_selection(text)
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/utils.py", line 156, in set_primary_selection
    p = subprocess.Popen(['xsel', '-i', '-p'], stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/nix/store/166s7l3yjqfc8dj5hfqjb09dbfvp1850-python3-3.6.3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/nix/store/166s7l3yjqfc8dj5hfqjb09dbfvp1850-python3-3.6.3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xsel': 'xsel'
```

I believe it needs xsel as buildInput @tex 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.2, NixOS, 18.03pre121255.45a85eaceb (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(teto): `"nixos-unstable-18.03pre120398.aeff3080d0, nixos-17.09.2075.ac35504065"`
 - channels(root): `"nixos-17.09.2075.ac35504065"`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by jtojnar** [comment]
Fixed in #32193
