### ISSUE TITLE
switcherooctl fails with "ImportError: cannot import name Gio, introspection typelib not found"

### ISSUE THREAD

**Issue by schuelermine** [NixOS/nixpkgs#321590]
### Describe the bug
```none
$ switcherooctl
Traceback (most recent call last):
  File "/nix/store/33kxplyhyjw512pp47h1zaw7sjm58qq7-switcheroo-control-2.6/bin/.switcherooctl-wrapped", line 4, in <module>
    from gi.repository import Gio, GLib
  File "/nix/store/ak80bykk8halwf1klflhvpncq9lw2f8s-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Gio, introspection typelib not found
```

### Additional context
Hardware: Framework Laptop 16  
Using nixos-hardware

### Notify maintainers
`pkgs.switcheroo-control.meta.maintainers = [ ]`

### Metadata
- system: `"x86_64-linux"`
- host os: `Linux 6.9.5, NixOS, 24.11 (Vicuna), 24.11.20240620.d603719`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.2`
- nixpkgs: `/nix/store/xfpiyfgf6y30fxk5ngv0cjn474qfr3sj-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by alyraffauf** [comment]
Still experiencing this on unstable as of 19/01/2025.
