### ISSUE TITLE
bug: gpustat executate failure

### ISSUE THREAD

**Issue by jackyliu16** [NixOS/nixpkgs#322629]
### Describe the bug
direct execution error

### Steps To Reproduce
1. nix-shell -p 
2. gpustat

### Screenshots
```
➜  nix-shell -p gpustat    
this path will be fetched (3.65 MiB download, 14.19 MiB unpacked):
  /nix/store/zmpm0irzqxzrrjrk38pfdl2fndfcwy5f-gpustat-0.1.5
copying path '/nix/store/zmpm0irzqxzrrjrk38pfdl2fndfcwy5f-gpustat-0.1.5' from 'https://mirror.sjtu.edu.cn/nix-channels/store'...

[nix-shell:~/nixpkgs]$ gpustat
thread 'main' panicked at src/data/mod.rs:17:33:
called `Result::unwrap()` on an `Err` value: LibloadingError(DlOpen { desc: "libnvidia-ml.so: cannot open shared object file: No such file or directory" })
stack backtrace:
   0:     0x557ec6c59bd5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4a5853078ed6ad5e
   1:     0x557ec6c9eb0c - core::fmt::write::hcb5164cc0001627e
   2:     0x557ec6c596e5 - std::io::Write::write_fmt::h4f047c3956a46825
   3:     0x557ec6c599a4 - std::sys_common::backtrace::print::h33b76037fd95b2fe
   4:     0x557ec6c69403 - std::panicking::default_hook::{{closure}}::hd7fd2e4913eae4ac
   5:     0x557ec6c6915a - std::panicking::default_hook::h13a9a2eb684db87c
   6:     0x557ec6c6988d - std::panicking::rust_panic_with_hook::hda39260d38680d2a
   7:     0x557ec6c5a242 - std::panicking::begin_panic_handler::{{closure}}::h150d47ece314bd47
   8:     0x557ec6c59de6 - std::sys_common::backtrace::__rust_end_short_backtrace::hf5ef31e5afaaca81
   9:     0x557ec6c69584 - rust_begin_unwind
  10:     0x557ec6595925 - core::panicking::panic_fmt::h9a659e19ee4930b5
  11:     0x557ec6595863 - core::result::unwrap_failed::h41e1e19f38ed1e8d
  12:     0x557ec65a7da3 - gpustat::data::GpuMonitoringData::new::h0362a001f67fb03e
  13:     0x557ec65b06fe - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha1451160fa74444d
  14:     0x557ec6712912 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he3aaf47a8205eb6f
  15:     0x557ec66ff244 - eframe::native::glow_integration::GlowWinitApp::init_run_state::h61358d110b771b45
  16:     0x557ec67038c6 - <eframe::native::glow_integration::GlowWinitApp as eframe::native::winit_integration::WinitApp>::on_event::had23fc78bbba5ef0
  17:     0x557ec65ec792 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h8a27ff03e2c70f30
  18:     0x557ec6675c69 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events::h729c6b198b9ae741
  19:     0x557ec666e77b - winit::platform_impl::platform::EventLoop<T>::run_on_demand::hdf1eb688fa533957
  20:     0x557ec65fb78e - eframe::run_native::h4a9c276b598ca5ac
  21:     0x557ec65b23ac - gpustat::gui::run_gpu_app::haad21da3e10e27b4
  22:     0x557ec65b83d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1c274de0fac34b53
  23:     0x557ec65bcc89 - std::rt::lang_start::{{closure}}::hfb20ff949e3632fb
  24:     0x557ec6c69484 - std::panicking::try::h9134436c64049e5f
  25:     0x557ec6c4de9b - std::rt::lang_start_internal::hf4417b67ea9bae52
  26:     0x557ec65bcc75 - main
  27:     0x7f4a3016810e - __libc_start_call_main
  28:     0x7f4a301681c9 - __libc_start_main@@GLIBC_2.34
  29:     0x557ec6595e35 - _start
  30:                0x0 - <unknown>
```

### Notify maintainers
@arduano

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
[nix-shell:~/nixpkgs]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/kjhgwsnn7wkacncxhrcgc4mx0v82kbdf-nix-info
copying path '/nix/store/kjhgwsnn7wkacncxhrcgc4mx0v82kbdf-nix-info' from 'https://mirror.sjtu.edu.cn/nix-channels/store'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.34, NixOS, 24.05 (Uakari), 24.05.20240619.dd457de`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/home/jacky/.nix-defexpr/channels/nixpkgs`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arduano** [comment]
I'll close this issue for now because it's a gpustat issue rather than anything nix related. Feel free to open an issue on my repo though

**Comment by jackyliu16** [comment]
> Hey, I'm the maintainer of gpustat and I believe this error happens when there's no nvidia driver found. Are you on an AMD GPU? I haven't implemented AMD support yet. I need to have a more graceful/descriptive error though yes.

 To be honest, I don't know much about using gpu on linux right now.  Can you specify some commands or methods to help me provide information? 

First of all, the graphics card configured on my current computer is definitely not AMD, according to the following information 

<details>
<summary>lspci</summary>

```
➜  dotfiles git:(master) lspci               
00:00.0 Host bridge: Intel Corporation 10th Gen Core Processor Host Bridge/DRAM Registers (rev 02)
00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 02)
00:02.0 VGA compatible controller: Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 02)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Comet Lake PCH Thermal Controller
00:14.0 USB controller: Intel Corporation Comet Lake USB 3.1 xHCI Host Controller
00:14.2 RAM memory: Intel Corporation Comet Lake PCH Shared SRAM
00:14.3 Network controller: Intel Corporation Comet Lake PCH CNVi WiFi
00:15.0 Serial bus controller: Intel Corporation Comet Lake PCH Serial IO I2C Controller #0
00:15.1 Serial bus controller: Intel Corporation Comet Lake PCH Serial IO I2C Controller #1
00:16.0 Communication controller: Intel Corporation Comet Lake HECI Controller
00:17.0 SATA controller: Intel Corporation Device 06d3
00:1b.0 PCI bridge: Intel Corporation Comet Lake PCI Express Root Port #21 (rev f0)
00:1d.0 PCI bridge: Intel Corporation Device 06b5 (rev f0)
00:1f.0 ISA bridge: Intel Corporation Comet Lake LPC Controller
00:1f.3 Audio device: Intel Corporation Comet Lake PCH cAVS
00:1f.4 SMBus: Intel Corporation Comet Lake PCH SMBus Controller
00:1f.5 Serial bus controller: Intel Corporation Comet Lake PCH SPI Controller
01:00.0 VGA compatible controller: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)
01:00.1 Audio device: NVIDIA Corporation Device 10fa (rev a1)
06:00.0 Non-Volatile memory controller: Sandisk Corp SanDisk Ultra 3D / WD Blue SN550 NVMe SSD (rev 01)
07:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. Killer E2600 GbE Controller (rev 21)   
```

</details>

<details>

<summary> lshw -c Display </summary>

```
  *-display                 
       description: i915drmfb
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: /dev/fb0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list rom fb
       configuration: depth=32 driver=nouveau latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:600-5ff iomemory:600-5ff irq:149 memory:a0000000-a0ffffff memory:6000000000-600fffffff memory:6010000000-6011ffffff ioport:4000(size=128) memory:a1080000-a10fffff
  *-display
       product: i915drmfb
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 05
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1920,1080
       resources: iomemory:600-5ff iomemory:400-3ff irq:150 memory:6012000000-6012ffffff memory:4000000000-400fffffff ioport:5000(size=64) memory:c0000-dffff
```

</details>

and after i configuration my [flakes](https://bitbucket.org/jackyliu16/dotfiles/src/master/nixos/Acer/hardware-configuration.nix) base on [nixos wiki](https://nixos.wiki/wiki/Nvidia), the game performance significantly improved, CPU usage significantly reduced may prove that the graphics card is being used correctly .

 Another thing is, it shows that no dynamic library can be found.  
(I don't know about the GPU side, but shouldn't these libraries theoretically appear in dependencies?) 

 Sorry, I am a pure newcomer, these two days ready to try to play the game to begin to understand the gpu related content, if there is any common sense error, please correct.

**Comment by jackyliu16** [comment]
> Hey, I'm the maintainer of gpustat and I believe this error happens when there's no nvidia driver found. Are you on an AMD GPU? I haven't implemented AMD support yet. I need to have a more graceful/descriptive error though yes.

 To be honest, I don't know much about using gpu on linux right now.  Can you specify some commands or methods to help me provide information? 

First of all, the graphics card configured on my current computer is definitely not AMD, according to the following information 

<details>
<summary>lspci</summary>

```
➜  dotfiles git:(master) lspci               
00:00.0 Host bridge: Intel Corporation 10th Gen Core Processor Host Bridge/DRAM Registers (rev 02)
00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 02)
00:02.0 VGA compatible controller: Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 02)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Comet Lake PCH Thermal Controller
00:14.0 USB controller: Intel Corporation Comet Lake USB 3.1 xHCI Host Controller
00:14.2 RAM memory: Intel Corporation Comet Lake PCH Shared SRAM
00:14.3 Network controller: Intel Corporation Comet Lake PCH CNVi WiFi
00:15.0 Serial bus controller: Intel Corporation Comet Lake PCH Serial IO I2C Controller #0
00:15.1 Serial bus controller: Intel Corporation Comet Lake PCH Serial IO I2C Controller #1
00:16.0 Communication controller: Intel Corporation Comet Lake HECI Controller
00:17.0 SATA controller: Intel Corporation Device 06d3
00:1b.0 PCI bridge: Intel Corporation Comet Lake PCI Express Root Port #21 (rev f0)
00:1d.0 PCI bridge: Intel Corporation Device 06b5 (rev f0)
00:1f.0 ISA bridge: Intel Corporation Comet Lake LPC Controller
00:1f.3 Audio device: Intel Corporation Comet Lake PCH cAVS
00:1f.4 SMBus: Intel Corporation Comet Lake PCH SMBus Controller
00:1f.5 Serial bus controller: Intel Corporation Comet Lake PCH SPI Controller
01:00.0 VGA compatible controller: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)
01:00.1 Audio device: NVIDIA Corporation Device 10fa (rev a1)
06:00.0 Non-Volatile memory controller: Sandisk Corp SanDisk Ultra 3D / WD Blue SN550 NVMe SSD (rev 01)
07:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. Killer E2600 GbE Controller (rev 21)   
```

</details>

<details>

<summary> lshw -c Display </summary>

```
  *-display                 
       description: i915drmfb
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: /dev/fb0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list rom fb
       configuration: depth=32 driver=nouveau latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:600-5ff iomemory:600-5ff irq:149 memory:a0000000-a0ffffff memory:6000000000-600fffffff memory:6010000000-6011ffffff ioport:4000(size=128) memory:a1080000-a10fffff
  *-display
       product: i915drmfb
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 05
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1920,1080
       resources: iomemory:600-5ff iomemory:400-3ff irq:150 memory:6012000000-6012ffffff memory:4000000000-400fffffff ioport:5000(size=64) memory:c0000-dffff
```

</details>

and after i configuration my [flakes](https://bitbucket.org/jackyliu16/dotfiles/src/master/nixos/Acer/hardware-configuration.nix) base on [nixos wiki](https://nixos.wiki/wiki/Nvidia), the game performance significantly improved, CPU usage significantly reduced may prove that the graphics card is being used correctly .

 Another thing is, it shows that no dynamic library can be found.  
(I don't know about the GPU side, but shouldn't these libraries theoretically appear in dependencies?) 

 Sorry, I am a pure newcomer, these two days ready to try to play the game to begin to understand the gpu related content, if there is any common sense error, please correct.

**Comment by arduano** [comment]
I see, are you able to run `nvidia-smi`? If not then it's a configuration issue. Try following Nvidia setup guides for nix

**Comment by jackyliu16** [comment]
roger, I will search the manual for this.

best wishes,

在 2024-06-27 04:13:37，arduano ***@***.***> 写道：


I see, are you able to run nvidia-smi? If not then it's a configuration issue. Try following Nvidia setup guides for nix

**Comment by nicdumz** [comment]
@arduano are you saying that `gpustat` should panic if `services.xserver.videoDrivers = ["nvidia"];` is not enabled?

I wonder if we could make:

```shell
$ gpustat 
thread 'main' panicked at src/data/mod.rs:17:33:
called `Result::unwrap()` on an `Err` value: LibloadingError(DlOpen { desc: "libnvidia-ml.so: cannot open shared object file: No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

A better user experience, e.g. either by failing package activation or by patching to display a useful error.

**Comment by arduano** [comment]
I unfortunately don't have the capacity to fix it at the moment

https://github.com/arduano/gpustat
PRs welcome though
