### ISSUE TITLE
Docker swarm stacks sometimes stuck on boot, docker may start too early (suspecting systemd service's after property)

### ISSUE THREAD

**Issue by MatthieuBarthel** [NixOS/nixpkgs#323841]
### Describe the bug
I manage a few docker hosts on NixOS in "swarm mode" (however they are all working as single nodes, they are not clustered).

It randomly happened multiple times that the docker stacks were stuck on reboot, the containers are running (or restarting in loop, depending how they work), but they don't see each other and output those kind of logs:  `could not translate host name "xxx" to address: Name or service not known`

When it happens I have to kill/redeploy the stack (`docker stack rm` + `docker stack deploy`), or restart docker (`systemctl restart docker`), both works.

The issue happened today, here are the kind of logs I had in loop (I just stripped irrelevant ruby stuff).

<details>
  <summary>Logs</summary>  

  ```log
Jul 01 10:07:29 dok02-staging kernel: br0: port 3(veth5146) entered disabled state
Jul 01 10:07:29 dok02-staging kernel: vethf717dc1: renamed from eth0
Jul 01 10:07:29 dok02-staging kernel: docker_gwbridge: port 3(vethda6355c) entered disabled state
Jul 01 10:07:29 dok02-staging kernel: veth5385a27: renamed from eth1
Jul 01 10:07:29 dok02-staging systemd-networkd[707]: vethda6355c: Lost carrier
Jul 01 10:07:29 dok02-staging systemd-networkd[707]: vethda6355c: Link DOWN
Jul 01 10:07:29 dok02-staging kernel: docker_gwbridge: port 3(vethda6355c) entered disabled state
Jul 01 10:07:29 dok02-staging kernel: vethda6355c (unregistering): left allmulticast mode
Jul 01 10:07:29 dok02-staging kernel: vethda6355c (unregistering): left promiscuous mode
Jul 01 10:07:29 dok02-staging kernel: docker_gwbridge: port 3(vethda6355c) entered disabled state
Jul 01 10:07:29 dok02-staging kernel: br0: port 3(veth5146) entered disabled state
Jul 01 10:07:29 dok02-staging kernel: veth5146 (unregistering): left allmulticast mode
Jul 01 10:07:29 dok02-staging kernel: veth5146 (unregistering): left promiscuous mode
Jul 01 10:07:29 dok02-staging kernel: br0: port 3(veth5146) entered disabled state
Jul 01 10:07:29 dok02-staging systemd[1]: run-docker-netns-5a3701bcde80.mount: Deactivated successfully.
Jul 01 10:07:29 dok02-staging systemd[1]: var-lib-docker-overlay2-1189ccf7608343eb0421839b386d335f5d40c7bee0fc1359060fe5fdb17d19c5-merged.mount: Deactivated successfully.
Jul 01 10:07:29 dok02-staging (udev-worker)[577862]: vethf717dc1: Process '/nix/store/5jw69mbaj5dg4l2bj58acg3gxywfszpj-bash-5.2p26/bin/sh -c 'echo 2 > /proc/sys/net/ipv6/conf/vethf717dc1/use_tempaddr'' failed with exit code 1.
Jul 01 10:07:29 dok02-staging (udev-worker)[577865]: veth5385a27: Process '/nix/store/5jw69mbaj5dg4l2bj58acg3gxywfszpj-bash-5.2p26/bin/sh -c 'echo 2 > /proc/sys/net/ipv6/conf/veth5385a27/use_tempaddr'' failed with exit code 1.
Jul 01 10:07:30 dok02-staging dockerd[732]: time="2024-07-01T10:07:30.011073223+02:00" level=error msg="fatal task error" error="task: non-zero exit (1)" module=node/agent/taskmanager node.id=ht9wmogtle2ayhvkk9ypmmsft service.id=qmzvzokilvem4tbcc1j16ffy5 task.id=i4rum2nugabqerk9rpby9pfk9
Jul 01 10:07:30 dok02-staging 0eac2c5c0b47[732]: /app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:72:in `rescue in new_client': could not translate host name "postgres" to address: Name or service not known (ActiveRecord::ConnectionNotEstablished)
Jul 01 10:07:30 dok02-staging 0eac2c5c0b47[732]: /app/vendor/bundle/ruby/3.2.0/gems/pg-1.5.6/lib/pg/connection.rb:828:in `connect_start': could not translate host name "postgres" to address: Name or service not known (PG::ConnectionBad)
Jul 01 10:07:30 dok02-staging systemd[1]: docker-0eac2c5c0b47344119a6107499761b8a268ee0a24389111c0c2d2666f9e331a5.scope: Deactivated successfully.
Jul 01 10:07:30 dok02-staging systemd[1]: docker-0eac2c5c0b47344119a6107499761b8a268ee0a24389111c0c2d2666f9e331a5.scope: Consumed 5.884s CPU time, received 5.3K IP traffic, sent 30.0K IP traffic.
Jul 01 10:07:30 dok02-staging dockerd[732]: time="2024-07-01T10:07:30.600669598+02:00" level=info msg="ignoring event" container=0eac2c5c0b47344119a6107499761b8a268ee0a24389111c0c2d2666f9e331a5 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jul 01 10:07:30 dok02-staging dockerd[749]: time="2024-07-01T10:07:30.601866566+02:00" level=info msg="shim disconnected" id=0eac2c5c0b47344119a6107499761b8a268ee0a24389111c0c2d2666f9e331a5 namespace=moby
Jul 01 10:07:30 dok02-staging dockerd[749]: time="2024-07-01T10:07:30.601926471+02:00" level=warning msg="cleaning up after shim disconnected" id=0eac2c5c0b47344119a6107499761b8a268ee0a24389111c0c2d2666f9e331a5 namespace=moby
Jul 01 10:07:30 dok02-staging dockerd[749]: time="2024-07-01T10:07:30.601950095+02:00" level=info msg="cleaning up dead shim" namespace=moby
Jul 01 10:07:30 dok02-staging kernel: br0: port 10(veth5148) entered disabled state
Jul 01 10:07:30 dok02-staging kernel: veth6215ce3: renamed from eth0
Jul 01 10:07:30 dok02-staging systemd-networkd[707]: veth11dcea2: Lost carrier
Jul 01 10:07:30 dok02-staging kernel: docker_gwbridge: port 10(veth11dcea2) entered disabled state
Jul 01 10:07:30 dok02-staging kernel: veth2cb9245: renamed from eth1
Jul 01 10:07:30 dok02-staging kernel: docker_gwbridge: port 10(veth11dcea2) entered disabled state
Jul 01 10:07:30 dok02-staging kernel: veth11dcea2 (unregistering): left allmulticast mode
Jul 01 10:07:30 dok02-staging kernel: veth11dcea2 (unregistering): left promiscuous mode
Jul 01 10:07:30 dok02-staging kernel: docker_gwbridge: port 10(veth11dcea2) entered disabled state
Jul 01 10:07:30 dok02-staging systemd-networkd[707]: veth11dcea2: Link DOWN
Jul 01 10:07:30 dok02-staging (udev-worker)[577865]: veth2cb9245: Process '/nix/store/5jw69mbaj5dg4l2bj58acg3gxywfszpj-bash-5.2p26/bin/sh -c 'echo 2 > /proc/sys/net/ipv6/conf/veth2cb9245/use_tempaddr'' failed with exit code 1.
Jul 01 10:07:30 dok02-staging kernel: br0: port 10(veth5148) entered disabled state
Jul 01 10:07:30 dok02-staging kernel: veth5148 (unregistering): left allmulticast mode
Jul 01 10:07:30 dok02-staging kernel: veth5148 (unregistering): left promiscuous mode
Jul 01 10:07:30 dok02-staging kernel: br0: port 10(veth5148) entered disabled state
Jul 01 10:07:30 dok02-staging 8d0c31ea4a36[732]: 2024-07-01 08:07:30.792 WRN Redis connection failed nodeid=LWuu_7 context=broadcast provider=redis error="dial tcp: lookup redis_websocket on 127.0.0.11:53: no such host"
Jul 01 10:07:30 dok02-staging systemd[1]: run-docker-netns-2d6414f36d29.mount: Deactivated successfully.
Jul 01 10:07:30 dok02-staging systemd[1]: var-lib-docker-overlay2-769ebbf591c9640709be2b08d59c763477cc8480655449bbccc3a32fba465d6d-merged.mount: Deactivated successfully.
  ```
</details>

I am not sure if this is related to NixOS or Docker, I already made multiple attempts to understand this issue but I cannot reproduce it (a server has been restarted hundreds of times without being able to reproduce it).

### Steps To Reproduce

I cannot reproduce the error, but it happened a few times this year.

### Expected behavior

Docker swarm stacks should start and work.

### Additional context

The host where the issue happened today has cloudinit network config enabled, I am unfortunately not sure if the same issue already happened on hosts with other kind of network config, or even on non-NixOS hosts (I had so many docker troubles over the years, I'm confused).

However I have the feeling it may come from docker starting too early, I had a look at the systemd config for docker.service and it seems that NixOS overrides the unit's `After=` property:

```sh
# cat /etc/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target docker.socket firewalld.service containerd.service time-set.target
Wants=network-online.target containerd.service
Requires=docker.socket
...

# cat /etc/systemd/system/docker.service.d/overrides.conf
[Unit]
After=network.target docker.socket
Requires=docker.socket
...
```

I don't know why this override is done, for now I will try to restore the missing services in `After=` and be patient to see if the issue happens again. Here is what I've had to my config:

```nix
systemd.services.docker.after = [
  "network-online.target" "firewalld.service" "containerd.service" "time-set.target"
];
```

### Notify maintainers

@offlinehacker @vdemeester @periklis @teutat3s

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.05 (Uakari), 24.05.20240630.7dca152`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MatthieuBarthel** [comment]
I had this bug back and it finally turns out to seem not related with cloud-init, but rather a combination of restarting docker (with swarm enabled) and rebooting right after it. It happens more often on some hosts than others, it can probably be reproduced with `systemctl restart docker.service; sleep 2; reboot` (the bug doesn't occur everytime).
