### ISSUE TITLE
/dev/root is not created under some circumstances and prevents profile switching

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#32406]
## Issue description

I am doing some kernel development via nixops/libvirtd. When trying to deploy, nixops would keep failing with
```
server> ssh -oControlPath=/run/user/1000/nixops-ssh-tmpTc8_7k/master-socket -p 22 -o StrictHostKeyChecking=no -i /run/user/1000/nixops-tmp930uqp/id_nixops-server -p 22 -o StrictHostKeyChecking=no -i /run/user/1000/nixops-tmp930uqp/id_nixops-server -x root@192.168.122.169 -- /nix/var/nix/profiles/system/bin/switch-to-configuration switch
client> updating GRUB 2 menu...
server> updating GRUB 2 menu...
client> Failed to get blkid info (returned 512) for / on /dev/root at /nix/store/rhysr5f7x04pkifz1zvl6jlcp5fwpg53-install-grub.pl line 185.
client> error: Traceback (most recent call last):
  File "/home/teto/nixops/nixops/deployment.py", line 708, in worker
    raise Exception("unable to activate new configuration")
Exception: unable to activate new configuration

server> Failed to get blkid info (returned 512) for / on /dev/root at /nix/store/rhysr5f7x04pkifz1zvl6jlcp5fwpg53-install-grub.pl line 185.
server> error: Traceback (most recent call last):
  File "/home/teto/nixops/nixops/deployment.py", line 708, in worker
    raise Exception("unable to activate new configuration")
Exception: unable to activate new configuration
```

After some investigation, I found out that it failed because /dev/root didn't exist. I believe this is possible due to the way I launch the VM. I use the capability of qemu to specify on the command line a kernel with the ` -kernel ` flag. I don't use an initramfs, here are libvirtd parameters:

```
    <kernel>/home/teto/mptcp/build/arch/x86_64/boot/bzImage</kernel>
    <cmdline>root=/dev/sda1 earlycon=ttyS0 console=ttyS0 init=/nix/var/nix/profiles/system/init boot.debug=1 boot.consoleLogLevel=1 </cmdline>
```

During the kernel boot, I see 
```
When used in 
[    1.376054] Freeing unused kernel memory: 532K
/nix/var/nix/profiles/system/init: line 9: /proc/cmdline: No such file or directory

<<< NixOS Stage 2 >>>

[    1.439946] EXT4-fs (sda1): re-mounted. Opts: (null)
[    1.453333] usb 1-2: New USB device found, idVendor=0627, i
```
which matches this part of the code, aka the one resonsible for symlinking /dev/root
```
for o in $(</proc/cmdline); do
    case $o in
        boot.debugtrace)
            # Show each command.
            set -x
            ;;
        resume=*)
            set -- $(IFS==; echo $o)
            resumeDevice=$2
            ;;
        root=*)
            # If a root device is specified on the kernel command
            # line, make it available through the symlink /dev/root.
            # Recognise LABEL= and UUID= to support UNetbootin.
            set -- $(IFS==; echo $o)
            if [ $2 = "LABEL" ]; then
                root="/dev/disk/by-label/$3"
            elif [ $2 = "UUID" ]; then
                root="/dev/disk/by-uuid/$3"
            else
            ln -s "$root" /dev/root
            ;;
    esac
done
```

To sum up, init stage1 can't open `/proc/cmdline` and thus doesn't ` ln -s "$root" /dev/root` so when nixops tries to run in the VM  `/nix/var/nix/profiles/system/bin/switch-to-configuration switch`, it fails because of the absence of /dev/root.
When I create it manually, nixops works fine. /dev/root doesn't seem much used in stage1 so I wonder if I could move its creation to some stage where it could actually access /proc/cmdline ? or if there are any better proposition ?

### Steps to reproduce

Not sure that's worth it but the nixops fork is at https://github.com/teto/nixops/tree/kernel
and you need to create the deployment with
```
deployment.libvirtd = {
      headless = true;
      extraDevicesXML = ''
        <serial type='pty'>
        <target port='0'/>
        </serial>
        <console type='pty'>
        <target type='serial' port='0'/>
        </console>
      '';
      extraDomainXML = ''
        <on_crash>preserve</on_crash>
      '';
      # don't need the ip=dhcp anymore
      # boot.trace to look at startup commands
      cmdline="root=/dev/sda1 earlycon=ttyS0 console=ttyS0 init=/nix/var/nix/profiles/system/init boot.debug=1 boot.consoleLogLevel=1 ";
      kernel="/home/teto/mptcp/build/arch/x86_64/boot/bzImage";
    };
```
Then deploy the network and observe the failure.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.3, NixOS, 18.03.git.3d3e8ea (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(teto): `"nixos-unstable-18.03pre120398.aeff3080d0, nixos-17.09.2075.ac35504065"`
 - channels(root): `"nixos-17.09.2075.ac35504065"`
 - nixpkgs: `/home/teto/nixpkgs`

Ps: With the same setup I get another though minor problem 
```
 [    1.496700] booting system configuration /nix/store/6rpgwsskz7n8xnk2bnjv49m02jwfc52n-nixos-system-client-18.03.git.3d3e8ea
/nix/var/nix/profiles/system/init: line 118: /dev/fd/62: No such file or directory
running activation script...
setting up /etc...
```
which corresponds to
```
# Log the script output to /dev/kmsg or /run/log/stage-2-init.log.
# Only at this point are all the necessary prerequisites ready for these commands.
exec {logOutFd}>&1 {logErrFd}>&2
if test -w /dev/kmsg; then
    exec > >(tee -i /proc/self/fd/"$logOutFd" | while read -r line; do
        if test -n "$line"; then
            echo "<7>stage-2-init: $line" > /dev/kmsg
        fi
    done) 2>&1
else
    mkdir -p /run/log
    exec > >(tee -i /run/log/stage-2-init.log) 2>&1
fi

```

**Comment by edolstra** [comment]
Got the same, not using /dev/root however:
```
lucifer> updating GRUB 2 menu...
lucifer> Failed to get blkid info (returned 512) for / on /dev/disk/by-label/nixos at /nix/store/w0rzdivvrf2ydrwi7jzk5bnrxm75zyzc-install-grub.pl line 185.
lucifer> error: unable to activate new configuration
```

I'm not sure if you should rely on /dev/root existing BTW.

**Comment by teto** [comment]
I patched nixops and my VMs to create the symlink instead.
```
  boot.postBootCommands = ''
    ln -s /dev/sda1 /dev/root
  '';
```
I am not sure anymore what could be a clean patch. Closing this.
