### ISSUE TITLE
Unable to use fingerprint for reader `10a5:9800`

### ISSUE THREAD

**Issue by pinarruiz** [NixOS/nixpkgs#324624]
### Describe the bug
Upon following [Fingerprint Scanner](https://wiki.nixos.org/wiki/Fingerprint_scanner), I try to enroll and I get the following error:

> Impossible to enroll: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: No devices available

### Steps To Reproduce
```nix
{ pkgs, ... }: {
  systemd.services.fprintd = {
    wantedBy = [ "multi-user.target" ];
    serviceConfig.Type = "simple";
  };

  services.fprintd = {
    enable = true;
    tod = {
      enable = true;
      driver = pkgs.libfprint-2-tod1-goodix-550a;
    };
  };
}
```

Then rebuild and switch (I rebooted just in case), then run:
```console
sudo fprintd-enroll
```

This is probably related to missing libraries or drivers.

### Expected behavior
The fingreprint enroll process starts.

### Additional context
This is a Lenovo Thinkpad E16 (`LENOVO 21JN00D3SP`).
On `lsusb` th device looks like:
```console
Bus 001 Device 002: ID 10a5:9800 FPC FPC Sensor Controller L:0002 FW:27.26.23.31
```

### Notify maintainers

Based on https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/libraries/libfprint-2-tod1-goodix-550a/default.nix#L43: @utkarshgupta137

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.05 (Uakari), 24.05.20240702.706eef5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/0z4i8wyg3ymm7kkb1gk2wyh08x230c6z-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pinarruiz** [comment]
Please let me know if more feedback is required.
Thanks.

**Comment by pinarruiz** [comment]
It seems that the aur package [libfprint-fpcmoh-git](https://aur.archlinux.org/packages/libfprint-fpcmoh-git) makes it work acording to:
[This thread](https://bbs.archlinux.org/viewtopic.php?pid=2180949#p2180949).

**Comment by pinarruiz** [comment]
Not so sure but it seems updating the version on https://github.com/NixOS/nixpkgs/blob/435020cb46c2c7d88b3e6ffbbbd1086ce11ce0fa/pkgs/development/libraries/libfprint-tod/default.nix to at least `v1.94.6+tod1` (same as aur), latest version available being `v1.94.7+tod1`.

**Comment by KCynk** [comment]
Hello I also have Lenovo E16
Maybe you need add firmware section?
Here is my full config
```
{ config, pkgs, ... }:

{
  # Hardware
  imports =
    [ 
      ./hardware-configuration.nix
      <home-manager/nixos>
    ];

  hardware.bluetooth.enable = false;
  hardware.pulseaudio.enable = false;
  hardware.enableRedistributableFirmware = true;
  hardware.enableAllFirmware = true;

  # System version
  system.stateVersion = "24.11";
  system.copySystemConfiguration = true;
  system.autoUpgrade = {
    enable = true;
    flags = [ "--update-input" "nixpkgs" "-L" ];
    dates = "02:00";
    randomizedDelaySec = "45min";
  };

  # Bootloader with plymouth
  boot = {
    # Enable "Silent Boot"
    consoleLogLevel = 0;
    initrd.verbose = false;
    initrd.systemd.enable = true;
    kernelParams = [
      "quiet"
      "splash"
      "boot.shell_on_fail"
      "loglevel=3"
      "rd.systemd.show_status=false"
      "rd.udev.log_level=3"
      "udev.log_priority=3"
    ];
    loader = {
      timeout = 0;
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };

    # Hardening
    kernel.sysctl = {
      "kernel.exec-shield" = "2";
      "fs.protected_hardlinks" = "1";
      "fs.protected_symlinks" = "1";
      "kernel.randomize_va_space" = "2";
      "fs.file-max" = "65535";
      "kernel.pid_max" = "65536";
      "net.ipv4.ip_local_port_range" = "2000 65000";
      "net.ipv4.tcp_rfc1337" = "1";
      "net.ipv4.icmp_ignore_bogus_error_responses" = "1";
      "net.ipv4.tcp_rmem" = "4096 87380 8388608";
      "net.ipv4.tcp_wmem" = "4096 87380 8388608";
      "net.core.netdev_max_backlog" = "5000";
      "net.ipv4.tcp_window_scaling" = "1";
      "net.ipv4.ip_forward" = "0";
      "net.ipv4.conf.all.rp_filter" = "1";
      "net.ipv4.conf.default.rp_filter" = "1";
      "kernel.core_uses_pid" = "1";
      "kernel.yama.ptrace_scope" = "2";
      "net.ipv4.tcp_syncookies" = "1";
      "net.ipv4.tcp_synack_retries" = "5";
      "net.ipv4.conf.all.send_redirects" = "0";
      "net.ipv4.conf.default.send_redirects" = "0";
      "net.ipv4.conf.all.accept_redirects" = "0";
      "net.ipv4.conf.all.secure_redirects" = "0";
      "net.ipv4.conf.all.log_martians" = "1";
      "net.ipv4.conf.default.accept_source_route" = "0";
      "net.ipv4.conf.default.accept_redirects" = "0";
      "net.ipv4.conf.default.secure_redirects" = "0";
      "net.ipv4.icmp_echo_ignore_broadcasts" = "1";
      "net.ipv6.conf.all.disable_ipv6" = "1";
      "net.ipv6.conf.default.disable_ipv6" = "1";
      "net.ipv6.conf.all.accept_ra" = "0";
      "net.ipv6.conf.default.accept_ra" = "0";
      "net.ipv4.tcp_sack" = "0";
      "net.ipv4.tcp_dsack" = "0";
      "net.ipv4.tcp_fack" = "0";
      "vm.swappiness" = "0";
      "vm.mmap_rnd_bits" = "32";
      "vm.mmap_rnd_compat_bits" = "16";
    };
    plymouth = {
      enable = true;
      theme = "breeze";
    };
  };

  virtualisation.libvirtd.enable = true;
  virtualisation.libvirtd.qemu.package = pkgs.qemu_kvm;
  virtualisation.libvirtd.qemu.runAsRoot = true;
  virtualisation.libvirtd.qemu.swtpm.enable = true;
  virtualisation.libvirtd.qemu.ovmf.enable = true;
  virtualisation.libvirtd.qemu.ovmf.packages = [(pkgs.OVMF.override {
    secureBoot = true;
    tpmSupport = true;
  }).fd];

  networking.hostName = "87a9f8f3b6a231";
  networking.networkmanager.enable = true;
  networking.firewall.enable  = true;
  networking.firewall.allowPing  = false;

  time.timeZone = "Europe/Warsaw";

  console.keyMap = "pl2";
  i18n.defaultLocale = "en_GB.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "pl_PL.UTF-8";
    LC_IDENTIFICATION = "pl_PL.UTF-8";
    LC_MEASUREMENT = "pl_PL.UTF-8";
    LC_MONETARY = "pl_PL.UTF-8";
    LC_NAME = "pl_PL.UTF-8";
    LC_NUMERIC = "pl_PL.UTF-8";
    LC_PAPER = "pl_PL.UTF-8";
    LC_TELEPHONE = "pl_PL.UTF-8";
    LC_TIME = "pl_PL.UTF-8";
  };

  services.displayManager.autoLogin.enable = true;
  services.displayManager.autoLogin.user = "nix";
  services.gnome.core-utilities.enable = false;
  services.pipewire.alsa.enable = true;
  services.pipewire.alsa.support32Bit = true;
  services.pipewire.enable = true;
  services.pipewire.pulse.enable = true;
  services.power-profiles-daemon.enable = true;
  services.printing.enable = false;
  services.thermald.enable = true;
  services.xserver.desktopManager.gnome.enable = true;
  services.xserver.desktopManager.xterm.enable = false;
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.enable = true;
  services.xserver.excludePackages = with pkgs; [ xterm ];
  services.xserver.xkb.layout = "pl";
  services.xserver.xkb.variant = "";
  services.fprintd.enable = true;
  services.fprintd.tod.enable = true;
  services.fprintd.tod.driver = pkgs.libfprint-2-tod1-goodix-550a; # Goodix 550a driver (from Lenovo)

  systemd.services."autovt@tty1".enable = false;
  systemd.services."getty@tty1".enable = false;
  systemd.services.fprintd = {
    wantedBy = [ "multi-user.target" ];
    serviceConfig.Type = "simple";
  };

  security.rtkit.enable = true;
  # security.apparmor.enable = true;

  users.users.nix = {
    isNormalUser = true;
    description = "admin";
    extraGroups = [ "networkmanager" "wheel" "libvirtd" "docker" ];
  };

  home-manager.users.nix = { pkgs, ... }: {
    home.stateVersion = "24.11";
    home.packages = [ ];
  };

  nix.settings.experimental-features = "nix-command flakes";
  nix.settings.auto-optimise-store = true;
  
  nix.optimise.automatic = true;
  nix.optimise.dates = [ "20:00" ];

  nix.gc.automatic = true;
  nix.gc.dates = "weekly";
  nix.gc.options = "--delete-older-than 7d";

  programs.firefox.enable = true;
  programs.neovim.enable = true;
  programs.neovim.defaultEditor = true;
  programs.dconf.enable = true;
  programs.bash.promptInit = ''
    PS1="[\u@\h:\w] "
  '';

  nixpkgs.config.allowUnfree = true;

  # Problems with 'graphane-hardened' and "scudo" option any browser can't be initized
  # environment.memoryAllocator.provider = "scudo";

  environment.sessionVariables = {
    CALIBRE_USE_SYSTEM_THEME = "true";
    QT_STYLE_OVERRIDE = "adwaita";
    QT_WAYLAND_DECORATION = "adwaita";
    QT_QPA_PLATFORM = "wayland";
  };

  qt.enable = true;
  qt.platformTheme = "gnome";
  qt.style = "adwaita";
  
  environment.gnome.excludePackages = with pkgs; [
    nixos-render-docs
    gnome.yelp
    gnome-tour
    gnome-extension-manager
    gnome-extensions-cli
    gnome.gnome-backgrounds
    xterm
    nano
    cups
  ];

  environment.systemPackages = with pkgs; [
    gnome.nautilus
    gnome-console
    loupe
    gnome.gnome-tweaks
    gnome.gnome-themes-extra
    gnome.gnome-calendar
    gnomeExtensions.just-perfection
    nixos-bgrt-plymouth
    nix-bash-completions
    bash-completion
    keepassxc
    cherrytree
    ticktick
    protonvpn-gui
    ibm-plex
    virt-manager
    cloud-init
    calibre
    xorriso
    usbutils
    krita
    evince
    git
    home-manager
    qgnomeplatform
  ];
}
```

![Screenshot from 2024-07-04 22-42-41](https://github.com/NixOS/nixpkgs/assets/23100970/70aa8185-c99e-4a3e-b224-36f8c7535662)

![Screenshot from 2024-07-04 22-43-08](https://github.com/NixOS/nixpkgs/assets/23100970/ebbb912b-8334-479c-a7bd-157f73cce214)

**Comment by pinarruiz** [comment]
Hi @KCynk I just tried that, did not work sadly.

I however tried @andrevmatos nix file on the comment on this issue https://gitlab.freedesktop.org/libfprint/libfprint/-/merge_requests/396 and it worked, although it feels like a workaraound. I wonder if you and i have the exact same hardware as from what I have, mine is the intel one, i believe there is an amd one, but dont know if the fingerprint scanner changes tho.

Anyways i left both firmware options you suggested on, it cannot hurt. for the time being i will use that nix snippet, that i will also add to this reply in case someone stumbles upon this issue and finds it useful, all credit for that goes to @andrevmatos:

```nix
{pkgs, ...}: let
  fpcbep = pkgs.fetchzip {
    url = "https://download.lenovo.com/pccbbs/mobiles/r1slm01w.zip";
    hash = "sha256-/buXlp/WwL16dsdgrmNRxyudmdo9m1HWX0eeaARbI3Q=";
    stripRoot = false;
  };
  libfprint = pkgs.libfprint.overrideAttrs (attrs: {
    patches = attrs.patches or [] ++ [
      (pkgs.fetchpatch {
        url = "https://gitlab.freedesktop.org/libfprint/libfprint/-/merge_requests/396.patch";
        sha256 = "sha256-+5B5TPrl0ZCuuLvKNsGtpiU0OiJO7+Q/iz1+/2U4Taw=";
      })
    ];
    postPatch = (attrs.postPatch or "") + ''
      substituteInPlace meson.build \
        --replace "find_library('fpcbep', required: true)" "find_library('fpcbep', required: true, dirs: '$out/lib')"
    '';
    preConfigure = (attrs.preConfigure or "") + ''
      install -D "${fpcbep}/FPC_driver_linux_27.26.23.39/install_fpc/libfpcbep.so" "$out/lib/libfpcbep.so"
    '';
    postInstall = (attrs.postInstall or "") + ''
      install -Dm644 "${fpcbep}/FPC_driver_linux_libfprint/install_libfprint/lib/udev/rules.d/60-libfprint-2-device-fpc.rules" "$out/lib/udev/rules.d/60-libfprint-2-device-fpc.rules"
      substituteInPlace "$out/lib/udev/rules.d/70-libfprint-2.rules" --replace "/bin/sh" "${pkgs.runtimeShell}"
    '';
  });
  fprintd = pkgs.fprintd.override {inherit libfprint;};
in {
  services.fprintd = {
    enable = true;
    package = fprintd;
  };
  services.udev.packages = [libfprint];
}
```

**Comment by qlexqndru** [comment]
Closest I got it working for me is with this method

```
services.fprintd = let
  libfprint-tod = pkgs.libfprint.overrideAttrs (_: rec {
    pname = "libfprint-tod";
    version = "1.94.7+tod1";
    src = pkgs.fetchFromGitLab {
    domain = "gitlab.freedesktop.org";
    owner = "3v1n0";
    repo = "libfprint";
    rev = "v${version}";
    sha256 = "sha256-rtkZ1q5A8MxaDjrdVCqLUUuA6v1ob07v95/U9wV+ydk=";
   };
 });
in {
  enable = true;
  package = pkgs.fprintd.override { libfprint = libfprint-tod; };
  tod = {
    enable = true;
    driver = pkgs.libfprint-2-tod1-goodix-550a.override { libfprint-tod = libfprint-tod; };
   };
 };
```

with the result:
```
~ ❯ sudo fprintd-enroll                                                                                            ⏎
Using device /net/reactivated/Fprint/Device/0
Enrolling right-index-finger finger.
Enroll result: enroll-unknown-error
```

everything else, even the methods you provided, only show me this: 
```
~ ❯ sudo fprintd-enroll
[sudo] password for qlexqndru: 
Impossible to enroll: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: No devices available
```

I really have no idea anymore, what else can I do, maybe you have some ideas or suggestions? I will be very grateful

**Comment by pinarruiz** [comment]
Hi @qlexqndru. I honestly have no clue, all the info I have gathered has been obtain digging a lot, I could not give yours a try, as it would fail on compilation.

I have found that for at least mine it looks like fpcmoh (which i believe stands for something like match on hardware) is the driver i apparently need, but its nowhere to be found on the nixpkgs.

**Comment by qlexqndru** [comment]
Thank you! I will keep digging then, there is always a solution. So far, the fpcmoh sounds like the only lead

**Comment by andrew-isakov** [comment]
i'm use hint https://github.com/NixOS/nixpkgs/issues/324624?ysclid=m2r6wt0onc689895423#issuecomment-2225370110  make ovrerlay from https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libfprint-tod/default.nix
but 
```
Installing libfprint/tod/libfprint-2-tod.so.1 to /nix/store/4c774ahh874ky21944bmgxzv48npmryc-libfprint-tod-1.94.7+tod1/lib
Installing libfprint/tod/fpi-enums.h to /nix/store/4c774ahh874ky21944bmgxzv48npmryc-libfprint-tod-1.94.7+tod1/include/libfprint-2/tod-1
Installing libfprint/libfprint-2.so.2.0.0 to /nix/store/4c774ahh874ky21944bmgxzv48npmryc-libfprint-tod-1.94.7+tod1/lib
Installing libfprint/70-libfprint-2.rules to /nix/store/cw7m8vly5kqgygrsy3yfishcavsaiqvp-systemd-minimal-libs-256.6/lib/udev/rules.d
Traceback (most recent call last):
  File "/nix/store/rrpijgwiw3y1qfvbyzi18qiap02fkp3r-meson-1.5.2/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 191, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rrpijgwiw3y1qfvbyzi18qiap02fkp3r-meson-1.5.2/lib/python3.12/site-packages/mesonbuild/minstall.py", line 869, in run
    installer.do_install(datafilename)
  File "/nix/store/rrpijgwiw3y1qfvbyzi18qiap02fkp3r-meson-1.5.2/lib/python3.12/site-packages/mesonbuild/minstall.py", line 549, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/nix/store/rrpijgwiw3y1qfvbyzi18qiap02fkp3r-meson-1.5.2/lib/python3.12/site-packages/mesonbuild/minstall.py", line 746, in install_targets
    file_copied = self.do_copyfile(fname, outname, makedirs=(dm, outdir))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rrpijgwiw3y1qfvbyzi18qiap02fkp3r-meson-1.5.2/lib/python3.12/site-packages/mesonbuild/minstall.py", line 415, in do_copyfile
    dirmaker.makedirs(outdir, exist_ok=True)
  File "/nix/store/rrpijgwiw3y1qfvbyzi18qiap02fkp3r-meson-1.5.2/lib/python3.12/site-packages/mesonbuild/minstall.py", line 108, in makedirs
    self.makedirs_impl(path, exist_ok=exist_ok)
  File "/nix/store/rrpijgwiw3y1qfvbyzi18qiap02fkp3r-meson-1.5.2/lib/python3.12/site-packages/mesonbuild/minstall.py", line 315, in makedirs
    os.makedirs(*args, **kwargs)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/nix/store/cw7m8vly5kqgygrsy3yfishcavsaiqvp-systemd-minimal-libs-256.6/lib/udev'

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
error: builder for '/nix/store/jk2lqcn2br61mmcdl4iavf51y5sx2pbi-libfprint-tod-1.94.7+tod1.drv' failed with exit code 13
error: 1 dependencies of derivation '/nix/store/r9844k432b24mvbrskfp6j93y7lbbnql-fprintd-tod-1.90.9.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cnj80pgspzrrncb3ijg6pznng37v7sp9-libfprint-2-tod1-goodix-0.0.6.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nsic0l7wlkhbi0m8mihb3avq41ly6xvr-chfn.pam.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sal2cc0kj38fym1d9jk8gbyxwkl37fr5-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/filj47zsdgfwnf8yzapzgpc98sav7nrp-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/66jmr549q9jcz1312yc3y3c6pygii0v2-nixos-system-andrew-24.11pre697431.86e78d3d2084.drv' failed to build
```

**Comment by qlexqndru** [comment]
Actually, for me what worked was this, I defined the pkgs:

    fprintd-tod
    libfprint-2-tod1-goodix-550a
    
Then the services:

  services.fprintd.enable = true;

  services.fprintd.tod = {
    enable = true;
    driver = pkgs.libfprint-2-tod1-goodix-550a;
  };
  
Then it just worked. There was no need for anything extra. Not sure if something changed with nix or pkgs. 

I use a:
-  Lenovo ThinkPad E14 Gen 5 

and driver: 
- 27c6:550a Shenzhen Goodix Technology Co.,Ltd. FingerPrint

**Comment by andrew-isakov** [comment]
https://github.com/NixOS/nixpkgs/issues/324624#issuecomment-2439930168 i'm try available. i have 27c6:5125

**Comment by utkarshgupta137** [comment]
I've switched back from Windows to NixOS & I can confirm that this driver continues to work for me on Lenovo Legion 16ARHA7: https://github.com/utkarshgupta137/nix-config/blob/main/hosts/nixos/hardware-configuration.nix#L57-L63.
I'm no driver expert, but this driver worked for me on my device. I'm afraid I can't help you in fixing this driver for your device. If you're able to figure out how to get it working outside nix, then I maybe able to assist you in writing a corresponding nix file.

**Comment by furcom** [comment]
I built a package back then for Fedora with the patched libfprint to make the fprint reader (10a5:9800) work in Fedora. You can find the patched libfprint file here: https://github.com/furcom/libfprint-patched. Maybe someone could build a Nix package? I don't know how to build Nix packages. I'm new to Nix. 😅

**Comment by andrevmatos** [comment]
My module still works, although I had to download the MR patch and adjust it locally, since it doesn't apply cleanly since then.
Download these 2 files, `default.nix` and `fpcmoh.patch`, to the same folder, I call it `profiles/fprint-fpcmoh/`, and import it from your system:  `imports = [./profiles/fpprint-fpcmoh];` 

- [fpcmoh.patch](https://github.com/user-attachments/files/19038507/fpcmoh.txt)

```nix
{pkgs, ...}: let
  fpcbep = pkgs.fetchzip {
    url = "https://download.lenovo.com/pccbbs/mobiles/r1slm01w.zip"; # /mnt/sec/Dev/libfprint-fpcmoh-fpcpeb.zip
    hash = "sha256-/buXlp/WwL16dsdgrmNRxyudmdo9m1HWX0eeaARbI3Q=";
    stripRoot = false;
  };
  overlay = final: prev: {
    libfprint = prev.libfprint.overrideAttrs (attrs: {
      doCheck = false;
      patches =
        (attrs.patches or [])
        ++ [./fpcmoh.patch]; # https://gitlab.freedesktop.org/libfprint/libfprint/-/merge_requests/396
      postPatch =
        (attrs.postPatch or "")
        + ''
          substituteInPlace meson.build \
            --replace-fail "find_library('fpcbep', required: true)" "find_library('fpcbep', required: true, dirs: '$out/lib')"
        '';
      preConfigure =
        (attrs.preConfigure or "")
        + ''
          install -D "${fpcbep}/FPC_driver_linux_27.26.23.39/install_fpc/libfpcbep.so" "$out/lib/libfpcbep.so"
        '';
      postInstall =
        (attrs.postInstall or "")
        + ''
          install -Dm644 "${fpcbep}/FPC_driver_linux_libfprint/install_libfprint/lib/udev/rules.d/60-libfprint-2-device-fpc.rules" "$out/lib/udev/rules.d/60-libfprint-2-device-fpc.rules"
          substituteInPlace "$out/lib/udev/rules.d/70-libfprint-2.rules" --replace-fail "/bin/sh" "${pkgs.runtimeShell}"
        '';
    });
    fprintd = prev.fprintd.overrideAttrs (attrs: {
      doCheck = false;
      nativeBuildInputs = (attrs.nativeBuildInputs or []) ++ attrs.nativeCheckInputs;
    });
  };
in {
  nixpkgs.overlays = [overlay];
  services.fprintd.enable = true;
  services.udev.packages = [pkgs.libfprint];
}
```

**Comment by furcom** [comment]
It is working. Thank you so much 🫶🏼

**Comment by andrew-isakov** [comment]
can i rewrite /etc/udev/rules.d/60-libfprint-2-device-fpc.rules
```
# FPC Sensors
SUBSYSTEM=="usb", ATTRS{idVendor}=="10a5", ATTRS{idProduct}=="9800", ATTRS{dev}=="*", TEST=="power/control", ATTR{power/control}="auto"
SUBSYSTEM=="usb", ATTRS{idVendor}=="10a5", ATTRS{idProduct}=="9800", ENV{LIBFPRINT_DRIVER}="FPC Sensors"
```
with 27c6:5125 ?

**Comment by Aleksanaa** [comment]
> with 27c6:5125 ?

https://gitlab.freedesktop.org/libfprint/libfprint/-/issues/497

Is it displayed as a fpc sensor after all?
