### ISSUE TITLE
frigate: fails when using /run/secrets

### ISSUE THREAD

**Issue by danielrolls** [NixOS/nixpkgs#325228]
### Describe the bug
When deployed through NixOS with `services.frigate`, Frigate fails start if `/run/secrets` is in use since it tries to read from there but doesn't have access. Either it should have access, it shouldn't try to read from there or should be fault tolerant. This hits NixOS users using SOPS.

### Steps To Reproduce
- Have your `/run/secrets` directory readable only to root (as it should be). E.g. By using Sops for secret management.
- Deploy frigate with Nixos e.g.:
```
  services.frigate = rec {
      enable = true;
      hostname = "myhost";
      settings = {
        cameras = rec {
          mycam = {
            enabled = true;

            ffmpeg = {
              inputs = [{
                path = "rtsp://usename.password@192.168.0.100:554/cam/realmonitor?channel=1&subtype=1";
                roles = [ "detect" ];
              }];
            };
          };
        }; 
      };
    };
```
3. Switch into this NixOS build
4. Run `journalctl --follow -u frigate.service`
5. You'll see if fail with this:
```
Jul 07 11:16:48 lam python3.11[32555]: Traceback (most recent call last):
Jul 07 11:16:48 lam python3.11[32555]:   File "<frozen runpy>", line 198, in _run_module_as_main
Jul 07 11:16:48 lam python3.11[32555]:   File "<frozen runpy>", line 88, in _run_code
Jul 07 11:16:48 lam python3.11[32555]:   File "/nix/store/55df0p9fy23nw396z9s6psz8ni51hx9w-frigate-0.13.2/lib/python3.11/site-packages/frigate/__main__.py", line 6, in <module>
Jul 07 11:16:48 lam python3.11[32555]:     from frigate.app import FrigateApp
Jul 07 11:16:48 lam python3.11[32555]:   File "/nix/store/55df0p9fy23nw396z9s6psz8ni51hx9w-frigate-0.13.2/lib/python3.11/site-packages/frigate/app.py", line 20, in <module>
Jul 07 11:16:48 lam python3.11[32555]:     from frigate.comms.dispatcher import Communicator, Dispatcher
Jul 07 11:16:48 lam python3.11[32555]:   File "/nix/store/55df0p9fy23nw396z9s6psz8ni51hx9w-frigate-0.13.2/lib/python3.11/site-packages/frigate/comms/dispatcher.py", line 7, in <module>
Jul 07 11:16:48 lam python3.11[32555]:     from frigate.config import BirdseyeModeEnum, FrigateConfig
Jul 07 11:16:48 lam python3.11[32555]:   File "/nix/store/55df0p9fy23nw396z9s6psz8ni51hx9w-frigate-0.13.2/lib/python3.11/site-packages/frigate/config.py", line 55, in <module>
Jul 07 11:16:48 lam python3.11[32555]:     for secret_file in os.listdir("/run/secrets"):
Jul 07 11:16:48 lam python3.11[32555]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 07 11:16:48 lam python3.11[32555]: PermissionError: [Errno 13] Permission denied: '/run/secrets'
Jul 07 11:16:48 lam systemd[1]: frigate.service: Main process exited, code=exited, status=1/FAILURE
Jul 07 11:16:48 lam systemd[1]: frigate.service: Failed with result 'exit-code'.
```

### Expected behavior
Frigate should run without needing to access `/run/secrets` as an unprivileged user.

### Screenshots
n/a

### Notify maintainers

@mweinelt

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.05 (Uakari), 24.05.20240704.c0d0be0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"home-manager-21.11.tar.gz, nixos"`
 - channels(dan): `""`
 - nixpkgs: `/nix/store/gwdrgcmnnxji8laxiv7zyhi8s1iijcgw-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
This happens due to this code path.

https://github.com/blakeblackshear/frigate/blob/188a7de467ca378136ecadc71cbcee2a7226a045/frigate/config.py#L61-L67

I doubt they'll want a patch for that, so I'm applying one downstream.

**Comment by mweinelt** [comment]
Nevermind. Looks like I can fetch https://github.com/blakeblackshear/frigate/commit/a1424bad6c0163e790129ade7a9784514d0bf89d.
