### ISSUE TITLE
Build failure: quodlibet-full

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#325537]
### Steps To Reproduce

On a nixpkgs repo:

`$ nix build .#quodlibet-full`

### Build log

First error

```
quodlibet-full> Running phase: installCheckPhase
quodlibet-full> evaling implicit 'preCheck' string hook
quodlibet-full> ImportError while loading conftest '/build/source/tests/conftest.py'.
quodlibet-full> tests/__init__.py:25: in <module>
quodlibet-full>     import quodlibet
quodlibet-full> quodlibet/__init__.py:21: in <module>
quodlibet-full>     from .util.i18n import _, C_, N_, ngettext, npgettext
quodlibet-full> quodlibet/util/__init__.py:28: in <module>
quodlibet-full>     from senf import fsnative
quodlibet-full> E   ModuleNotFoundError: No module named 'senf'
```

This can be fixed by using patch https://github.com/quodlibet/quodlibet/pull/4358/files .

However, after that the test suite can't find various shared libs: https://gist.github.com/SFrijters/03805ad8d6894ec194987dab8895643d and I have not managed to fix those errors.

After setting `doCheck = false;` the doc build fails with

```
quodlibet-full> Executing sphinx-build with html builder
quodlibet-full> /nix/store/m101dg80ngyjdb02g6jwy80sr7kzj26g-bash-5.2p26/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
quodlibet-full> Traceback (most recent call last):
quodlibet-full>   File "/nix/store/sr1q620p6mv77ihx6cikihxi7g6a4xbg-python3.12-sphinx-7.3.7/bin/.sphinx-build-wrapped", line 9, in <module>
quodlibet-full>     sys.exit(main())
quodlibet-full>              ^^^^^^
quodlibet-full>   File "/nix/store/sr1q620p6mv77ihx6cikihxi7g6a4xbg-python3.12-sphinx-7.3.7/lib/python3.12/site-packages/sphinx/cmd/build.py", line 369, in main
quodlibet-full>     locale.setlocale(locale.LC_ALL, '')
quodlibet-full>   File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/locale.py", line 615, in setlocale
quodlibet-full>     return _setlocale(category, locale)
quodlibet-full>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
quodlibet-full> locale.Error: unsupported locale setting
error: builder for '/nix/store/viyz2law73d0dn21v6i2dbzxvapw2451-quodlibet-full-4.6.0.drv' failed with exit code 1;
       last 10 log lines:
       > Traceback (most recent call last):
       >   File "/nix/store/sr1q620p6mv77ihx6cikihxi7g6a4xbg-python3.12-sphinx-7.3.7/bin/.sphinx-build-wrapped", line 9, in <module>
       >     sys.exit(main())
       >              ^^^^^^
       >   File "/nix/store/sr1q620p6mv77ihx6cikihxi7g6a4xbg-python3.12-sphinx-7.3.7/lib/python3.12/site-packages/sphinx/cmd/build.py", line 369, in main
       >     locale.setlocale(locale.LC_ALL, '')
       >   File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/locale.py", line 615, in setlocale
       >     return _setlocale(category, locale)
       >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       > locale.Error: unsupported locale setting
       For full logs, run 'nix log /nix/store/viyz2law73d0dn21v6i2dbzxvapw2451-quodlibet-full-4.6.0.drv'.
```

After removing `sphinxHook` from `nativeBuildInputs` and `"doc"` from `outputs` the build finished succesfully.

However, trying to run the execuable has the same problem loading libs as the test suite did.

### Notify maintainers

@coroa @pbogdan 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by paveloom** [comment]
> This can be fixed by using patch https://github.com/quodlibet/quodlibet/pull/4358/files .
> 
> However, after that the test suite can't find various shared libs: https://gist.github.com/SFrijters/03805ad8d6894ec194987dab8895643d and I have not managed to fix those errors.

`distutils` is gone from the `stdlib` in Python 3.12, and upstream also fixed this issue in https://github.com/quodlibet/quodlibet/pull/4364.

However, those patches won't apply cleanly, so that would require even more patches... At this point, it would be reasonable to stick with Python 3.11 until a new Quod Libet release comes out. So, I think that your pull request https://github.com/NixOS/nixpkgs/pull/326051 is the way to go.

**Comment by SFrijters** [comment]
Bit late, but fixed via https://github.com/NixOS/nixpkgs/pull/326924 .
