### ISSUE TITLE
Build failure: awscli2

### ISSUE THREAD

**Issue by deejayem** [NixOS/nixpkgs#325574]
### Steps To Reproduce

1. build awscli2

### Build log

```
* Getting build dependencies for wheel...
* Building wheel...
Traceback (most recent call last):
  File "/nix/store/j3xg6ln22ng7b3qcs1dpha12x1kyldzd-python3.12-pyproject-hooks-1.0.0/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/nix/store/j3xg6ln22ng7b3qcs1dpha12x1kyldzd-python3.12-pyproject-hooks-1.0.0/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/j3xg6ln22ng7b3qcs1dpha12x1kyldzd-python3.12-pyproject-hooks-1.0.0/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/backends/pep517.py", line 64, in build_wheel
    _inject_wheel_extras(os.path.join(wheel_directory, whl_filename))
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/backends/pep517.py", line 189, in _inject_wheel_extras
    _build_and_inject_ac_index(BUILD_DIR, extracted_wheel_dir)
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/backends/pep517.py", line 217, in _build_and_inject_ac_index
    ac_index_build_name = _build_ac_index(build_dir)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/backends/pep517.py", line 228, in _build_ac_index
    from awscli.autocomplete.generator import generate_index
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/autocomplete/generator.py", line 17, in <module>
    from awscli.autocomplete.serverside.indexer import APICallIndexer
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/autocomplete/serverside/indexer.py", line 18, in <module>
    import awscli.clidriver
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/clidriver.py", line 22, in <module>
    import botocore.session
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/session.py", line 27, in <module>
    import botocore.client
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/client.py", line 16, in <module>
    from botocore import UNSIGNED, waiter, xform_name
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/waiter.py", line 17, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/docs/service.py", line 13, in <module>
    from botocore.docs.bcdoc.restdoc import DocumentStructure
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/docs/bcdoc/restdoc.py", line 15, in <module>
    from botocore.compat import OrderedDict
  File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/compat.py", line 36, in <module>
    from botocore.vendored.six.moves import http_client
ModuleNotFoundError: No module named 'botocore.vendored.six.moves'

ERROR Backend subprocess exited when trying to invoke build_wheel
error: builder for '/nix/store/9jl3s028w0ck5s7lzx2y4llgq5yphaa3-awscli2-2.17.5.drv' failed with exit code 1;
       last 25 log lines:
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/backends/pep517.py", line 228, in _build_ac_index
       >     from awscli.autocomplete.generator import generate_index
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/autocomplete/generator.py", line 17, in <module>
       >     from awscli.autocomplete.serverside.indexer import APICallIndexer
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/autocomplete/serverside/indexer.py", line 18, in <module>
       >     import awscli.clidriver
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/clidriver.py", line 22, in <module>
       >     import botocore.session
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/session.py", line 27, in <module>
       >     import botocore.client
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/client.py", line 16, in <module>
       >     from botocore import UNSIGNED, waiter, xform_name
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/waiter.py", line 17, in <module>
       >     from botocore.docs.docstring import WaiterDocstring
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/docs/__init__.py", line 15, in <module>
       >     from botocore.docs.service import ServiceDocumenter
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/docs/service.py", line 13, in <module>
       >     from botocore.docs.bcdoc.restdoc import DocumentStructure
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/docs/bcdoc/restdoc.py", line 15, in <module>
       >     from botocore.compat import OrderedDict
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/compat.py", line 36, in <module>
       >     from botocore.vendored.six.moves import http_client
       > ModuleNotFoundError: No module named 'botocore.vendored.six.moves'
       >
       > ERROR Backend subprocess exited when trying to invoke build_wheel)

```

### Additional context
Possibly this is darwin-specific.

### Notify maintainers

@bhipple @davegallant @bryanasdev000 @devusb @anthonyroussel

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/dmorgan/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by devusb** [comment]
Should be resolved by https://github.com/NixOS/nixpkgs/pull/325207 once it progresses to unstable -- can watch status [here](https://nixpk.gs/pr-tracker.html?pr=325207).

**Comment by deejayem** [comment]
Yes, that fixed it, sorry for missing that PR when searching.
