### ISSUE TITLE
auto-cpufreq has runtime error.

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#325514]
### Describe the bug
auto-cpufreq has runtime error.

### Steps To Reproduce
1. run `auto-cpufreq` in terminal

### Expected behavior
give command not found error or help message

### Additional context
error:
```py
Traceback (most recent call last):
  File "/nix/store/325f4xs1wzw9m28wbzfsjy27j9wgiccd-python3.12-auto-cpufreq-2.3.0/bin/..auto-cpufreq-wrapped-wrapped", line 6, in <module>
    from auto_cpufreq.bin.auto_cpufreq import main
  File "/nix/store/325f4xs1wzw9m28wbzfsjy27j9wgiccd-python3.12-auto-cpufreq-2.3.0/lib/python3.12/site-packages/auto_cpufreq/bin/auto_cpufreq.py", line 14, in <module>
    from auto_cpufreq.core import *
  File "/nix/store/325f4xs1wzw9m28wbzfsjy27j9wgiccd-python3.12-auto-cpufreq-2.3.0/lib/python3.12/site-packages/auto_cpufreq/core.py", line 28, in <module>
    from auto_cpufreq.utils.config import config
  File "/nix/store/325f4xs1wzw9m28wbzfsjy27j9wgiccd-python3.12-auto-cpufreq-2.3.0/lib/python3.12/site-packages/auto_cpufreq/utils/config.py", line 2, in <module>
    from auto_cpufreq.utils.config_event_handler import ConfigEventHandler
  File "/nix/store/325f4xs1wzw9m28wbzfsjy27j9wgiccd-python3.12-auto-cpufreq-2.3.0/lib/python3.12/site-packages/auto_cpufreq/utils/config_event_handler.py", line 1, in <module>
    import pyinotify
  File "/nix/store/8bxngdzbnzig8ddw0ypdg1plsmrpqmi2-python3.12-pyinotify-0.9.6/lib/python3.12/site-packages/pyinotify.py", line 71, in <module>
    import asyncore
ModuleNotFoundError: No module named 'asyncore'
```

### Notify maintainers

I mentioned sarcasticadmin because [this pr.](https://github.com/NixOS/nixpkgs/pull/323192)
@sarcasticadmin @Technical27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.11 (Vicuna), 24.11.20240708.5f736f2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/ah7v6nyzkvcb0dm3cfiihpv47s3pj9yb-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sarcasticadmin** [comment]
Closing #325571 upon digging into this deeper: it looks like this error is due to the removal of asyncore from python 3.12 which is effecting pyinotify. See: https://github.com/seb-m/pyinotify/issues/204 and https://peps.python.org/pep-0594/

This probably means anything running on python 3.12 with pyinotify is also broken. Ill make the fix there.
