### ISSUE TITLE
Add `<DOTNET_ROOT>/metadata/workloads/<sdkfeatureband>/userlocal` for dotnet SDKs

### ISSUE THREAD

**Issue by devurandom** [NixOS/nixpkgs#325667]
### Describe the bug

It is currently impossible to install .NET workloads on NixOS:
```console
❯ dotnet workload install maui
Unhandled exception: System.IO.IOException: Read-only file system : '/nix/store/as1j1inzdjdaca6gdcfdr2bdsppgr3px-dotnet-sdk-8.0.300/metadata'
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallerFactory.CanWriteToDotnetRoot(String dotnetDir)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallerFactory.GetWorkloadInstaller(IReporter reporter, SdkFeatureBand sdkFeatureBand, IWorkloadResolver workloadResolver, VerbosityOptions verbosity, String userProfileDir, Boolean verifySignatures, INuGetPackageDownloader nugetPackageDownloader, String dotnetDir, String tempDirPath, PackageSourceLocation packageSourceLocation, RestoreActionConfig restoreActionConfig, Boolean elevationRequired, Boolean shouldLog)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolverFactory workloadResolverFactory, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String tempDirPath, IReadOnlyCollection`1 workloadIds)
   at Microsoft.DotNet.Cli.WorkloadInstallCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

### Steps To Reproduce

1. Install the .NET Core 8 SDK: `environment.systemPackages = [ pkgs.dotnet-sdk_8 ];`
2. Try to install a workload: `dotnet workload install maui`
3. Observe error

### Expected behavior

`dotnet workload install maui` should install the workload in a user-writeable location.

### Additional context

According to https://github.com/dotnet/sdk/pull/18823 this can be fixed by writing a file `<DOTNET_ROOT>/metadata/workloads/<sdkfeatureband>/userlocal`.  https://discourse.nixos.org/t/dotnet-maui-workload/20370 contains shell code examples how to do that.

### Notify maintainers

@kuznero, @mdarocha

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.05 (Uakari), 24.05.20240702.706eef5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/0z4i8wyg3ymm7kkb1gk2wyh08x230c6z-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by devurandom** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/226107.

**Comment by devurandom** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/226107

**Comment by devurandom** [comment]
Duplicate of #226107
