### ISSUE TITLE
python3Packages.pyarrow segmentation faults depening on import order

### ISSUE THREAD

**Issue by dali99** [NixOS/nixpkgs#326230]
### Describe the bug

similar to #278106 

```python
import polars
import pyarrow
```
segfaults with
```
Fatal Python error: Segmentation fault

Current thread 0x00007f2c8282b740 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1233 in create_module
  File "<frozen importlib._bootstrap>", line 573 in module_from_spec
  File "<frozen importlib._bootstrap>", line 676 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176 in _find_and_load
  File "/nix/store/2k98kxfz5frfgg606x4wqz35h5p1czfp-python3.11-pyarrow-16.0.0/lib/python3.11/site-packages/pyarrow/__init__.py", line 65 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940 in exec_module
  File "<frozen importlib._bootstrap>", line 690 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176 in _find_and_load
  File "./testarrow.py", line 5 in <module>
zsh: segmentation fault (core dumped)  PYTHONFAULTHANDLER=1 ./testarrow.py
```

```python
import pyarrow
import polars
```

or even

```python
import pyarrow.lib
import polars
```

works fine.

The last last lines of code running according to the python fault handler:

```
# ARROW-8684: Disable GC while initializing Cython extension module,
# to workaround Cython bug in https://github.com/cython/cython/issues/3603
_gc_enabled = _gc.isenabled()
_gc.disable()
import pyarrow.lib as _lib
if _gc_enabled:
    _gc.enable()
```

Ive tested this on master and stable (311 and 312).

I've also tried updating both polars and arrow-cpp (and therefore pyarrow) to their latest versions.

### Notify maintainers
@veprbl @cpcloud
@happysalada

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.05 (Uakari), 24.05.2472.c0d0be00d4ec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by charmoniumQ** [comment]
I'm hitting a very similar fault:

```py
import polars
import sklearn
```

causes segmentation fault

```py
import sklearn
import polars
```

is completely fine.

I'm using Nixpkgs `ef7226d68ba45b2de3e428e5d4bb4532caffec7b`.

```
$ nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.25.0pre20240920_ca3fc169, nixpkgs: /home/sam/.nix-defexpr/channels/nixpkgs
```

**Comment by veprbl** [comment]
Would help to run under gdb and get a backtrace.

**Comment by charmoniumQ** [comment]
```
bash @ gdb --args python -c 'import polars; import sklearn'
GNU gdb (GDB) 15.1
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
(No debugging symbols found in python)
(gdb) r
Starting program: /nix/store/p3fmi28a93f5yvdm0wjcip4rzcqp6wpb-python3-3.12.5-env/bin/python -c import\ polars\;\ import\ sklearn
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libthread_db.so.1".
process 354979 is executing new program: /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/bin/python3.12
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007fffe3c1fe88 in _rjem_je_free_default () from /nix/store/nsb0hk0c5kswidvhnw7fiwf32h3q9xny-jemalloc-5.3.0/lib/libjemalloc.so.2
(gdb) bt
#0  0x00007fffe3c1fe88 in _rjem_je_free_default () from /nix/store/nsb0hk0c5kswidvhnw7fiwf32h3q9xny-jemalloc-5.3.0/lib/libjemalloc.so.2
#1  0x00007fff5c4c23a3 in void std::vector<SpecFun_UFunc, std::allocator<SpecFun_UFunc> >::_M_realloc_insert<SpecFun_UFunc>(__gnu_cxx::__normal_iterator<SpecFun_UFunc*, std::vector<SpecFun_UFunc, std::allocator<SpecFun_UFunc> > >, SpecFun_UFunc&&) ()
   from /nix/store/p3fmi28a93f5yvdm0wjcip4rzcqp6wpb-python3-3.12.5-env/lib/python3.12/site-packages/scipy/special/_special_ufuncs.cpython-312-x86_64-linux-gnu.so
#2  0x00007fff5c45529f in SpecFun_NewUFunc(SpecFun_UFunc, int, char const*, char const*) ()
   from /nix/store/p3fmi28a93f5yvdm0wjcip4rzcqp6wpb-python3-3.12.5-env/lib/python3.12/site-packages/scipy/special/_special_ufuncs.cpython-312-x86_64-linux-gnu.so
#3  0x00007fff5c45534e in SpecFun_NewUFunc(SpecFun_UFunc, char const*, char const*) ()
   from /nix/store/p3fmi28a93f5yvdm0wjcip4rzcqp6wpb-python3-3.12.5-env/lib/python3.12/site-packages/scipy/special/_special_ufuncs.cpython-312-x86_64-linux-gnu.so
#4  0x00007fff5c45596c in PyInit__special_ufuncs ()
   from /nix/store/p3fmi28a93f5yvdm0wjcip4rzcqp6wpb-python3-3.12.5-env/lib/python3.12/site-packages/scipy/special/_special_ufuncs.cpython-312-x86_64-linux-gnu.so
#5  0x00007ffff7b70db0 in _imp_create_dynamic ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#6  0x00007ffff7995184 in cfunction_vectorcall_FASTCALL ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#7  0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#8  0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#9  0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#10 0x00007ffff796bdca in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#11 0x00007fff5c7d6e9e in __pyx_pymod_exec__ufuncs ()
   from /nix/store/p3fmi28a93f5yvdm0wjcip4rzcqp6wpb-python3-3.12.5-env/lib/python3.12/site-packages/scipy/special/_ufuncs.cpython-312-x86_64-linux-gnu.so
#12 0x00007ffff7b77676 in PyModule_ExecDef () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#13 0x00007ffff7b7ab00 in _imp_exec_dynamic () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#14 0x00007ffff798252b in cfunction_vectorcall_O ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#15 0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#16 0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#17 0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#18 0x00007ffff796bdca in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#19 0x00007ffff79949b7 in cfunction_vectorcall_FASTCALL_KEYWORDS ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#20 0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#21 0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#22 0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#23 0x00007ffff796b8a7 in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#24 0x00007ffff790f768 in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#25 0x00007ffff7b6574d in PyEval_EvalCode () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#26 0x00007ffff7bc84cd in builtin_exec () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#27 0x00007ffff79949b7 in cfunction_vectorcall_FASTCALL_KEYWORDS ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#28 0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#29 0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#30 0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#31 0x00007ffff796bdca in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#32 0x00007ffff790f768 in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#33 0x00007ffff7b6574d in PyEval_EvalCode () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#34 0x00007ffff7bc84cd in builtin_exec () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#35 0x00007ffff79949b7 in cfunction_vectorcall_FASTCALL_KEYWORDS ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#36 0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#37 0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#38 0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#39 0x00007ffff796bdca in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#40 0x00007ffff790f768 in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#41 0x00007ffff7b6574d in PyEval_EvalCode () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#42 0x00007ffff7bc84cd in builtin_exec () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#43 0x00007ffff79949b7 in cfunction_vectorcall_FASTCALL_KEYWORDS ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#44 0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#45 0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#46 0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#47 0x00007ffff796bdca in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#48 0x00007ffff790f768 in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#49 0x00007ffff7b6574d in PyEval_EvalCode () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#50 0x00007ffff7bc84cd in builtin_exec () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#51 0x00007ffff79949b7 in cfunction_vectorcall_FASTCALL_KEYWORDS ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#52 0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#53 0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#54 0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#55 0x00007ffff796bdca in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#56 0x00007ffff790f768 in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#57 0x00007ffff7b6574d in PyEval_EvalCode () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#58 0x00007ffff7bc84cd in builtin_exec () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#59 0x00007ffff79949b7 in cfunction_vectorcall_FASTCALL_KEYWORDS ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#60 0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#61 0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#62 0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#63 0x00007ffff796bdca in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#64 0x00007ffff790f768 in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#65 0x00007ffff7b6574d in PyEval_EvalCode () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#66 0x00007ffff7bc84cd in builtin_exec () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#67 0x00007ffff79949b7 in cfunction_vectorcall_FASTCALL_KEYWORDS ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#68 0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#69 0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#70 0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#71 0x00007ffff796bdca in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#72 0x00007ffff79949b7 in cfunction_vectorcall_FASTCALL_KEYWORDS ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#73 0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#74 0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#75 0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#76 0x00007ffff796bdca in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#77 0x00007ffff790f768 in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#78 0x00007ffff7b6574d in PyEval_EvalCode () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#79 0x00007ffff7bc84cd in builtin_exec () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#80 0x00007ffff79949b7 in cfunction_vectorcall_FASTCALL_KEYWORDS ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#81 0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#82 0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#83 0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#84 0x00007ffff796bdca in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#85 0x00007ffff790f768 in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#86 0x00007ffff7b6574d in PyEval_EvalCode () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#87 0x00007ffff7bc84cd in builtin_exec () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#88 0x00007ffff79949b7 in cfunction_vectorcall_FASTCALL_KEYWORDS ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#89 0x00007ffff7905a1b in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#90 0x00007ffff7a1a087 in object_vacall () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#91 0x00007ffff7a2e527 in PyObject_CallMethodObjArgs ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#92 0x00007ffff796bdca in PyImport_ImportModuleLevelObject ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#93 0x00007ffff790f768 in _PyEval_EvalFrameDefault ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#94 0x00007ffff7b6574d in PyEval_EvalCode () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#95 0x00007ffff7b69d10 in run_eval_code_obj () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#96 0x00007ffff7bc793d in run_mod () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#97 0x00007ffff7c070a4 in PyRun_SimpleStringFlags ()
   from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#98 0x00007ffff7c074bf in Py_RunMain () from /nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/libpython3.12.so.1.0
#99 0x00007ffff754d14e in __libc_start_call_main () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#100 0x00007ffff754d209 in __libc_start_main_impl () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#101 0x0000000000401075 in _start ()
(gdb) 
```

**Comment by veprbl** [comment]
Interesting. See also: https://github.com/pytorch/pytorch/issues/124656
Looks like a polars/jemalloc bug

**Comment by D4ndellion** [comment]
I can't reproduce this anymore so I'm closing this for now
