### ISSUE TITLE
gcalcli: Runtime error “No module named 'google.api_core'”

### ISSUE THREAD

**Issue by AndrewKvalheim** [NixOS/nixpkgs#326353]
### Describe the bug

gcalcli fails to run due to a missing dependency:

```console
$ nix-shell --packages 'gcalcli' --run 'gcalcli --help'
Traceback (most recent call last):
  File "/nix/store/8q80dnfzn6gm10ps7c5xv14bnalmrxds-gcalcli-4.3.0/bin/.gcalcli-wrapped", line 6, in <module>
    from gcalcli.cli import main
  File "/nix/store/8q80dnfzn6gm10ps7c5xv14bnalmrxds-gcalcli-4.3.0/lib/python3.11/site-packages/gcalcli/cli.py", line 30, in <module>
    from gcalcli.gcal import GoogleCalendarInterface
  File "/nix/store/8q80dnfzn6gm10ps7c5xv14bnalmrxds-gcalcli-4.3.0/lib/python3.11/site-packages/gcalcli/gcal.py", line 31, in <module>
    from apiclient.discovery import build
  File "/nix/store/wjf5fh0s5iq56852n7qxkv7m07018k27-python3.11-google-api-python-client-2.126.0/lib/python3.11/site-packages/apiclient/__init__.py", line 3, in <module>
    from googleapiclient import channel, discovery, errors, http, mimeparse, model
  File "/nix/store/wjf5fh0s5iq56852n7qxkv7m07018k27-python3.11-google-api-python-client-2.126.0/lib/python3.11/site-packages/googleapiclient/discovery.py", line 42, in <module>
    import google.api_core.client_options
ModuleNotFoundError: No module named 'google.api_core'
```

### Notify maintainers

@nocoolnametom

### Metadata

```console
$ nix-shell --packages 'nix-info' --run 'nix-info --markdown'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.35, NixOS, 24.05 (Uakari), 24.05.2150.89c49874fb15`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nix-math, nixos-24.05, nixos-hardware, nixseparatedebuginfod"`
 - channels(ak): `"community-vscode-extensions, home-manager-23.11.tar.gz, nix-colors, rust-overlay, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
This is simply a problem with how `nix-shell` works. Its supposed use is for a development environment. Use `nix run` instead.

**Comment by AndrewKvalheim** [comment]
> This is simply a problem with how `nix-shell` works. Its supposed use is for a development environment.

So these instructions are just wrong?

```console
$ gcalcli
The program 'gcalcli' is not in your PATH. You can make it available in an
ephemeral shell by typing:
  nix-shell -p gcalcli
```

> Use `nix run` instead.

I assume this isn’t what you expect to happen:

```console
$ nix run gcalcli
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
```

**Comment by dotlambda** [comment]
> I assume this isn’t what you expect to happen:

It is.

**Comment by AndrewKvalheim** [comment]
To confirm, this is the correct behavior as well?

```nix
installCheckPhase = ''
  $out/bin/gcalcli --help > /dev/null
'';
```

```
Running phase: installCheckPhase
Traceback (most recent call last):
  File "/nix/store/4y61mj1rj4cznwh0z7g4gyy3gnbarlfv-gcalcli-4.3.0/bin/.gcalcli-wrapped", line 6, in <module>
    from gcalcli.cli import main
  File "/nix/store/4y61mj1rj4cznwh0z7g4gyy3gnbarlfv-gcalcli-4.3.0/lib/python3.12/site-packages/gcalcli/cli.py", line 30, in <mo>
    from gcalcli.gcal import GoogleCalendarInterface
  File "/nix/store/4y61mj1rj4cznwh0z7g4gyy3gnbarlfv-gcalcli-4.3.0/lib/python3.12/site-packages/gcalcli/gcal.py", line 31, in <m>
    from apiclient.discovery import build
  File "/nix/store/91nxk20nnl21s3micpsypv0pfb9gzrqf-python3.12-google-api-python-client-2.135.0/lib/python3.12/site-packages/ap>
    from googleapiclient import channel, discovery, errors, http, mimeparse, model
  File "/nix/store/91nxk20nnl21s3micpsypv0pfb9gzrqf-python3.12-google-api-python-client-2.135.0/lib/python3.12/site-packages/go>
    import google.api_core.client_options
ModuleNotFoundError: No module named 'google.api_core'
```

**Comment by dotlambda** [comment]
> To confirm, this is the correct behavior as well?

Yes. The point is that `nix-shell` recreates the environment that the package is built in, which sets `$PYTHONPATH`.

If there is a way to fix this without unsetting `$PYTHONPATH` then I'm happy to accept it but I don't see one right now.
