### ISSUE TITLE
fails compiling clang/llvm

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#32656]
## Issue description
On nixos unstable, I have to compile clang apparently  but one test fail
```
-- Testing: 21404 tests, 4 threads --
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70..
UNRESOLVED: LLVM :: Other/lit-unicode.txt (16749 of 21404)
******************** TEST 'LLVM :: Other/lit-unicode.txt' FAILED ********************
Exception during script execution:
Traceback (most recent call last):
  File "/tmp/nix-build-llvm-5.0.0.drv-0/llvm/utils/lit/lit/run.py", line 192, in _execute_test_impl
    result = test.config.test_format.execute(test, lit_config)
  File "/tmp/nix-build-llvm-5.0.0.drv-0/llvm/utils/lit/lit/formats/shtest.py", line 25, in execute
    self.execute_external)
  File "/tmp/nix-build-llvm-5.0.0.drv-0/llvm/utils/lit/lit/TestRunner.py", line 1181, in executeShTest
    res = _runShTest(test, litConfig, useExternalSh, script, tmpBase)
  File "/tmp/nix-build-llvm-5.0.0.drv-0/llvm/utils/lit/lit/TestRunner.py", line 1127, in _runShTest
    res = executeScript(test, litConfig, tmpBase, script, execdir)
  File "/tmp/nix-build-llvm-5.0.0.drv-0/llvm/utils/lit/lit/TestRunner.py", line 720, in executeScript
    f.write('{ ' + '; } &&\n{ '.join(commands) + '; }')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-11: ordinal not in range(128)


********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
Testing Time: 261.61s
********************
Unresolved Tests (1):
    LLVM :: Other/lit-unicode.txt

  Expected Passes    : 20587
  Expected Failures  : 131
  Unsupported Tests  : 685
  Unresolved Tests   : 1
make[3]: *** [CMakeFiles/check-all.dir/build.make:58: CMakeFiles/check-all] Error 1
make[3]: Leaving directory '/tmp/nix-build-llvm-5.0.0.drv-0/llvm/build'
make[2]: *** [CMakeFiles/Makefile2:158: CMakeFiles/check-all.dir/all] Error 2
make[2]: Leaving directory '/tmp/nix-build-llvm-5.0.0.drv-0/llvm/build'
make[1]: *** [CMakeFiles/Makefile2:165: CMakeFiles/check-all.dir/rule] Error 2
make[1]: Leaving directory '/tmp/nix-build-llvm-5.0.0.drv-0/llvm/build'
make: *** [Makefile:199: check-all] Error 2

```
Here is my locale, but my keyboard follows the US layout
```
$ locale                                                                                                                 
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.3, NixOS, 18.03pre122433.8a7b2f889dd (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(teto): `"nixos-17.09.2356.cb751f9b1c3, nixos-unstable-18.03pre121925.3eccd0b11d1"`
 - channels(root): `"nixos-17.09.2356.cb751f9b1c3"`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by dtzWill** [comment]
Hmm, that's strange.

Unfortunately, I can't reproduce using either of the mentioned 18.03 hashes listed:

```
$ NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/8a7b2f889dd.tar.gz nix-build '<nixpkgs>' -A llvmPackages_5.llvm
/nix/store/3h97nnrgzsxa7khvjrvii8vk4xrkfjc5-llvm-5.0.0
$ NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/3eccd0b11d1.tar.gz nix-build '<nixpkgs>' -A llvmPackages_5.llvm
/nix/store/mbl8yykmd0ysmb1b3p6xqllpb4lxd7sn-llvm-5.0.0
```

**Comment by teto** [comment]
this kind of python error usually happens because there is some `éè`  character appearing in a coomand line, in this case I suppose in the commands in ` f.write('{ ' + '; } &&\n{ '.join(commands) + '; }')`. I will try to compile US locale. Thanks for trying.

**Comment by dtzWill** [comment]
Err, if you're building in the sandbox ... why does your locale matter?

There have been some fixes re:python3 upstream but since we build with python2 I'm not sure they'd help.  But maybe :).

Also 5.0.1 should be released soon, might want to try that (think -rc3 is latest).

If you have ideas how I might reproduce it, would be interested in sorting this out :).

**Comment by dtzWill** [comment]
For example: https://github.com/llvm-mirror/llvm/commit/d0c8c6186c1ccb90938e3d80e7ac55f2bf1aa241#diff-2b6b3ddda4b5576cc164cff90baf4c2d looks possibly relevant.

**Comment by teto** [comment]
True, enabling sandbox is a recent move so forgot about it. The commit you link could very well solve that, I hope I can get away with just changing tag/hash to test rc3

**Comment by teto** [comment]
I rebuild nixos, then home-manager with an updated nixpkgs and it seems fixed :/
