### ISSUE TITLE
system-config-printer fails to start

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#32666]
## Issue description
```
system-config-printer
Traceback (most recent call last):
  File "/nix/store/zg9fxfb9zaqm9fbvwi4gi1h3q23dcaql-system-config-printer-1.5.9/share/system-config-printer/system-config-printer.py", line 77, in <module>
    import cupshelpers
  File "/nix/store/zg9fxfb9zaqm9fbvwi4gi1h3q23dcaql-system-config-printer-1.5.9/lib/python3.6/site-packages/cupshelpers/__init__.py", line 60, in <module>
    from . import openprinting
  File "/nix/store/zg9fxfb9zaqm9fbvwi4gi1h3q23dcaql-system-config-printer-1.5.9/lib/python3.6/site-packages/cupshelpers/openprinting.py", line 22, in <module>
    import requests, urllib.request, urllib.parse, urllib.error, platform, threading, tempfile, traceback
  File "/nix/store/0dhdwl0jr4ghick8nhfpyyvqq2x7djrf-python3.6-requests-2.18.4/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
```

### Steps to reproduce
run system-config-printer

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by teto** [comment]
fixed on unstable see https://github.com/NixOS/nixpkgs/issues/30596

**Comment by coretemp** [comment]
I checked that it works on master. If it's cherry picked, the issue can be closed.

**Comment by bjornfor** [comment]
I belive the cherry-picked commit is this: 992dee07c6b71b5fd7bbe83d6c1ebc0ca65277de (plus some revert + re-revert after, but nevermind that). system-config-printer works for me on release-17.09 branch.
