### ISSUE TITLE
klee error: No module named 'distutils'

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#326927]
### Describe the bug
Klee installation returns the following error:
```
...
-- Performing Test HAVE_C_FLAG_-fPIC
-- Performing Test HAVE_C_FLAG_-fPIC - Success
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'
CMake Error at bindings/python/stp/CMakeLists.txt:57 (message):
  Failed to determine python site package directory


-- Configuring incomplete, errors occurred!
error: builder for '/nix/store/p3n56bnf2y3sgxg0y2znn6dfjkkv0x5m-stp-2.3.3.drv' failed with exit code 1;
       last 10 log lines:
       > -- Performing Test HAVE_C_FLAG_-fPIC
       > -- Performing Test HAVE_C_FLAG_-fPIC - Success
       > Traceback (most recent call last):
       >   File "<string>", line 1, in <module>
       > ModuleNotFoundError: No module named 'distutils'
       > CMake Error at bindings/python/stp/CMakeLists.txt:57 (message):
       >   Failed to determine python site package directory
       >
       > 
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/p3n56bnf2y3sgxg0y2znn6dfjkkv0x5m-stp-2.3.3.drv'.
error (ignored): error: cannot unlink '/tmp/nix-build-compiler-rt-libc-13.0.1.drv-0/build/source': Directory not empty
error: 1 dependencies of derivation '/nix/store/p787rj0mqb048aac3rcf5x30lvsghanq-klee-3.1.drv' failed to build
```

### Steps To Reproduce
1. `nix-shell -p klee`

### Notify maintainers

@numinit 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, Athena OS, 24.11 (Vicuna), 24.11pre652179.7e7c39ea35c5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager, nixos, nixpkgs"`
 - nixpkgs: `/home/athena/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by numinit** [comment]
Thanks for the report; looking into it.

**Comment by numinit** [comment]
Looks like a STP issue, @McSinyx any ideas?

**Comment by numinit** [comment]
@D3vil0p3r KLEE works on 24.05, try that in the meantime.

**Comment by numinit** [comment]
See also: #326296, #326120, and others. Seems like this is treewide.

**Comment by numinit** [comment]
It looks like there's an update to `stp`; I'll bump it after #327037 gets merged but those two changes should fix klee.
