### ISSUE TITLE
Stardew Valley doesn't open in Heroic Launcher

### ISSUE THREAD

**Issue by arthsmn** [NixOS/nixpkgs#327153]
### Describe the bug
Stardew Valley isn't opening in the nixpkgs' Heroic Launcher, and I think there're missing dependencies.

### Steps To Reproduce
1. Open the Heroic Launcher and installs Stardew Valley from GOG
2. Try running the game

### Expected behavior
The game would open as usual

### Additional context
The logs:
``` log
Launching "Stardew Valley" (gog)
Native? Yes
Installed in: /home/arthur/Jogos/Heroic/Stardew Valley

System Info:
CPU: 16x AMD Ryzen 7 5700U with Radeon Graphics
Memory: 16.12 GB (used: 3.93 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne
    IDs: D=164c V=1002 SD=undefined SV=undefined
    Driver: undefined
OS: NixOS 24.11 (Vicuna) (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.1.0
  Nile: 1.1.0 Will A. Zeppeli

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallDxvkNvapi": false,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableMsync": false,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"useSteamRuntime": false,
	"battlEyeRuntime": true,
	"eacRuntime": true,
	"language": "",
	"beforeLaunchScriptPath": "",
	"afterLaunchScriptPath": "",
	"wineVersion": {
		"bin": "",
		"name": "Default Wine - Not Found",
		"type": "wine"
	},
	"winePrefix": "/home/arthur/Games/Heroic/Prefixes/default",
	"gamescope": {
		"enableUpscaling": false,
		"enableLimiter": false,
		"windowType": "fullscreen",
		"gameWidth": "",
		"gameHeight": "",
		"upscaleHeight": "",
		"upscaleWidth": "",
		"upscaleMethod": "fsr",
		"fpsLimiter": "",
		"fpsLimiterNoFocus": "",
		"additionalOptions": ""
	}
}

Game launched at: Sun Jul 14 2024 13:35:51 GMT-0300 (GMT-03:00)

Launch Command: HEROIC_APP_NAME=1453375253 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog STEAM_COMPAT_INSTALL_PATH="/home/arthur/Jogos/Heroic/Stardew Valley" LD_PRELOAD= /nix/store/x1sbg4sz4lw0lgs3pp1xl64cy1aaf4r6-heroic-unwrapped-2.14.1/share/heroic/build/bin/linux/gogdl launch "/home/arthur/Jogos/Heroic/Stardew Valley" 1453375253 --platform linux

Game Log:
Running Stardew Valley
./StardewValley: linha 7: sw_vers: comando não encontrado
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at StardewValley.Program.Main(System.String[])
./StardewValley, linha 27: 365066 Aborted                 (imagem do núcleo gravada)./"Stardew Valley" $@
Launch command: ['/home/arthur/Jogos/Heroic/Stardew Valley/start.sh']
All processes exited
============= End of log =============
```

### Notify maintainers
@aidalgol 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
fetching path input 'path:/nix/store/qmh8bas1qni03drm0lnjas2azh7h87cn-source'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8, NixOS, 24.11 (Vicuna), 24.11.20240712.7e7c39e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0`
 - nixpkgs: `/nix/store/qmh8bas1qni03drm0lnjas2azh7h87cn-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by IncredibleLaser** [comment]
Stardew Valley depends on an outdated version of OpenSSL that is insecure IIRC (see also https://forums.stardewvalley.net/threads/no-supported-version-of-libssl-was-found-ubuntu-22-04.12155/) I just play the Windows version via Wine, also from Heroic Launcher (on the Steam Deck) and that works just fine, if it's acceptable to you I'd just do that instead of trying to hunt down an ancient version of a library.

**Comment by arthsmn** [comment]
Thanks for the explanation! Installing the Windows version worked as expected.

**Comment by aidalgol** [comment]
That turns out not to be the case here.  I happen to own the GOG version of this game, so I was able to test this.  It complains about missing ICU; once I added that to the Heroic FHS environment, it launched just fine.  Will submit a PR.
