### ISSUE TITLE
Onlykey-cli fails to connect to onlykey

### ISSUE THREAD

**Issue by doolphin** [NixOS/nixpkgs#327244]
### Describe the bug
Just got an onlykey (duo model), and tried to set it up. Using the cli with it plugged in errors out

### Steps To Reproduce
1.  plug in onlykey
2. $ nix shell nixpkgs#onlykey-cli -c onlykey-cli
3.  ctrl+c when bored of error output loop

### Expected behavior
Normal output

### Buggy behavior
```
[user@system:~]$ nix-shell -p onlykey-cli --run "onlykey-cli"
fetching path input 'path:/nix/store/0z4i8wyg3ymm7kkb1gk2wyh08x230c6z-source'
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/dd7nxjnni7nzm0846fq5xrm89ais5lwz-stdenv-linux
copying path '/nix/store/dd7nxjnni7nzm0846fq5xrm89ais5lwz-stdenv-linux' from 'https://cache.nixos.org'...
failed to connect
Traceback (most recent call last):
  File "/nix/store/83mcy6w720jvnwk6hj5hdpsmkkhf7db0-onlykey-cli-1.2.10/lib/python3.11/site-packages/onlykey/client.py", line 275, in _connect
    self._hid.open_path(self.path)
  File "hid.pyx", line 157, in hid.device.open_path
OSError: open failed
failed to connect
Traceback (most recent call last):
  File "/nix/store/83mcy6w720jvnwk6hj5hdpsmkkhf7db0-onlykey-cli-1.2.10/lib/python3.11/site-packages/onlykey/client.py", line 275, in _connect
    self._hid.open_path(self.path)
  File "hid.pyx", line 157, in hid.device.open_path
OSError: open failed
^CTraceback (most recent call last):
  File "/nix/store/83mcy6w720jvnwk6hj5hdpsmkkhf7db0-onlykey-cli-1.2.10/lib/python3.11/site-packages/onlykey/client.py", line 275, in _connect
    self._hid.open_path(self.path)
  File "hid.pyx", line 157, in hid.device.open_path
OSError: open failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/83mcy6w720jvnwk6hj5hdpsmkkhf7db0-onlykey-cli-1.2.10/lib/python3.11/site-packages/onlykey/client.py", line 245, in __init__
    self._connect()
  File "/nix/store/83mcy6w720jvnwk6hj5hdpsmkkhf7db0-onlykey-cli-1.2.10/lib/python3.11/site-packages/onlykey/client.py", line 280, in _connect
    raise OnlyKeyUnavailableException()
onlykey.client.OnlyKeyUnavailableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/83mcy6w720jvnwk6hj5hdpsmkkhf7db0-onlykey-cli-1.2.10/bin/.onlykey-cli-wrapped", line 6, in <module>
    from onlykey.cli import main
  File "/nix/store/83mcy6w720jvnwk6hj5hdpsmkkhf7db0-onlykey-cli-1.2.10/lib/python3.11/site-packages/onlykey/cli.py", line 30, in <module>
    only_key = OnlyKey()
               ^^^^^^^^^
  File "/nix/store/83mcy6w720jvnwk6hj5hdpsmkkhf7db0-onlykey-cli-1.2.10/lib/python3.11/site-packages/onlykey/client.py", line 251, in __init__
    time.sleep(1.5)
KeyboardInterrupt
```

### Additional context
Error occurs in hyprland and kde plasma
onlykey-cli also installed via home-manager (nixpkgs unstable branch) with same error

### Notify maintainers
@kalbasit 
@ranfdev 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
fetching path input 'path:/nix/store/0z4i8wyg3ymm7kkb1gk2wyh08x230c6z-source'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.05 (Uakari), 24.05.20240702.706eef5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-rc1`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05, nixpkgs-unstable"`
 - channels(username): `""`
 - nixpkgs: `/nix/store/0z4i8wyg3ymm7kkb1gk2wyh08x230c6z-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doolphin** [comment]
fixed with hardware.onlykey.enable my bad
