### ISSUE TITLE
parsedmarc: Runtime error “No module named 'google.auth'”

### ISSUE THREAD

**Issue by AndrewKvalheim** [NixOS/nixpkgs#327774]
### Describe the bug

parsedmarc fails to run with a `ModuleNotFoundError`:

```console
$ nix-shell --packages 'parsedmarc' --run 'parsedmarc --help'
Traceback (most recent call last):
  File "/nix/store/nmhb6blcf8bqj8j88qyyy9n6qhrrjiyh-python3.11-parsedmarc-8.11.0/bin/.parsedmarc-wrapped", line 6, in <module>
    from parsedmarc.cli import _main
  File "/nix/store/nmhb6blcf8bqj8j88qyyy9n6qhrrjiyh-python3.11-parsedmarc-8.11.0/lib/python3.11/site-packages/parsedmarc/__init__.py", line 31, in <module>
    from parsedmarc.mail import MailboxConnection
  File "/nix/store/nmhb6blcf8bqj8j88qyyy9n6qhrrjiyh-python3.11-parsedmarc-8.11.0/lib/python3.11/site-packages/parsedmarc/mail/__init__.py", line 3, in <module>
    from parsedmarc.mail.gmail import GmailConnection
  File "/nix/store/nmhb6blcf8bqj8j88qyyy9n6qhrrjiyh-python3.11-parsedmarc-8.11.0/lib/python3.11/site-packages/parsedmarc/mail/gmail.py", line 7, in <module>
    from google.auth.transport.requests import Request
ModuleNotFoundError: No module named 'google.auth'
```

### Notify maintainers

@talyz

### Metadata

```console
$ nix-shell --packages 'nix-info' --run 'nix-info --markdown'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.39, NixOS, 24.05 (Uakari), 24.05.2780.53e81e790209`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nix-math, nixos-24.05, nixos-hardware, nixseparatedebuginfod"`
 - channels(ak): `"community-vscode-extensions, home-manager-23.11.tar.gz, nix-colors, rust-overlay, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndrewKvalheim** [comment]
This is a [bug in the Nix ecosystem](https://github.com/NixOS/nixpkgs/issues/326353#issuecomment-2307913215) that should be resolved when `nix run` is stabilized.
