### ISSUE TITLE
`services.meilisearch` doesn't respect `system.stateVersion`

### ISSUE THREAD

**Issue by sodiboo** [NixOS/nixpkgs#327978]
### Describe the bug

- Meilisearch fails to start after https://github.com/NixOS/nixpkgs/pull/325354 was merged.
  It gives me the following error upon a rebuild
  
      Error: Your database version (1.8.3) is incompatible with your current engine version (1.9.0).
      To migrate data between Meilisearch versions, please follow our guide on https://www.meilisearch.com/docs/learn/update_and_migration/updating.

### Steps To Reproduce

1. Set `services.meilisearch.enable = true` one week ago, e.g. prior to https://github.com/NixOS/nixpkgs/pull/325354 being merged, and populate its database. This uses `meilisearch-1.8.3`
2. Switch to an up-to-date `nixos-unstable`, This uses `meilisearch-1.9.0`
3. Rebuild your system.
4. Observe that Meilisearch fails to start.

### Expected behavior

- I expect it to either use an old version of the `meilisearch` package, according to [`system.stateVersion`](https://search.nixos.org/options?show=system.stateVersion) such that the database is still compatible, or to otherwise migrate it automatically such that there is no issue (similar to [what i do with my own sharkey package](https://github.com/sodiboo/nix-config/blob/5704cabee1d81c461994b44c4b9673abd3296863/sharkey/module.nix#L190C50-L190C65))

### Screenshots

![An screenshot of the activation output, showing that it's stopping meilisearch.service, doing various other things, then starting meilisearch.service. Starting it fails for the reason given above.](https://github.com/user-attachments/assets/94f21512-8308-4e6e-bf98-289a62171a82)

### Additional context

- I maintain a private sharkey instance. As part of this, [i use the `services.meilisearch` module](https://github.com/sodiboo/nix-config/blob/5704cabee1d81c461994b44c4b9673abd3296863/sharkey/module.nix#L226-L231). It doesn't do much fancy. I've simply enabled meilisearch, and it complained after a recent system update.
- My system has had [`system.stateVersion = "23.11";`](https://github.com/sodiboo/nix-config/blob/5704cabee1d81c461994b44c4b9673abd3296863/nix.mod.nix#L19) since far before i ever touched the Meilisearch module

### Notify maintainers

@Br1ght0ne and @happysalada are [the maintainers for the meilisearch module](https://github.com/NixOS/nixpkgs/blob/35a24e21b5d0fc7aa528f061ffdc68b16d45d596/nixos/modules/services/search/meilisearch.nix#L11).

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
oxygen ~ $ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, NixOS, 24.11 (Vicuna), 24.11.20240714.693bc46`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/iqxdbcjlg9wx8gdc8bdhy9nsd5imcbjp-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by happysalada** [comment]
This should definitely be improved. I think to be honest, meilisearch is creating problems in the first place by making all minor versions not compatible with each other. However we could improve upon that, no one had the time to do that yet.
If you had time to make that improvement , merging should come relatively fast.

**Comment by sodiboo** [comment]
For now, to workaround this, [I'm just pinning meilisearch to 1.8.3](https://github.com/sodiboo/nix-config/blob/feefe662605b0e3c84439856177277bdea365a4b/sharkey/import.mod.nix#L7) on my system until a real fix is implemented

**Comment by diogotcorreia** [comment]
Seems like Meilisearch now supports a dumpless upgrade from 1.12 to newer versions: https://www.meilisearch.com/docs/learn/update_and_migration/updating#dumpless-upgrade

It's still experimental tho, and requires a CLI flag, but a step in the right direction.

**Comment by happysalada** [comment]
We should try to enable it after the stable release is done. If we get 6 months of use for it, it should be ready to release for the next stable 25.11 after that

**Comment by diogotcorreia** [comment]
@happysalada we would need to upgrade meilisearch to 1.12.X at least before 25.05 then. It's currently at 1.11.3 on unstable

**Comment by happysalada** [comment]
Right, i tried the update a while back but got a compilation failure and didnt push through.
Someone is doing a conversion to using cargo vendor, was thinking of waiting for that before trying again.

**Comment by happysalada** [comment]
Yeah, just tried briefly and it looks there is a problem with a file not vendored properly. It looks like a git dependency.

**Comment by diogotcorreia** [comment]
Seems like the same crate is included twice with the same version:
https://github.com/meilisearch/meilisearch/blob/v1.13.3/Cargo.lock#L394-L431

```
Unpacking to /nix/store/69fx0hw1g7z6mb70mlvakfy218pszbar-meilisearch-1.13.3-vendor/arroy-0.5.0
Copying to /nix/store/69fx0hw1g7z6mb70mlvakfy218pszbar-meilisearch-1.13.3-vendor/arroy-0.5.0
Traceback (most recent call last):
  File "/nix/store/h536wymibaydldashx6s1ccpw9cbyb75-fetch-cargo-vendor-util/bin/fetch-cargo-vendor-util", line 318, in <module>
    main()
  File "/nix/store/h536wymibaydldashx6s1ccpw9cbyb75-fetch-cargo-vendor-util/bin/fetch-cargo-vendor-util", line 314, in main
    subcommand_func()
  File "/nix/store/h536wymibaydldashx6s1ccpw9cbyb75-fetch-cargo-vendor-util/bin/fetch-cargo-vendor-util", line 306, in <lambda>
    "create-vendor": lambda: create_vendor(vendor_staging_dir=Path(sys.argv[2]), out_dir=Path(sys.argv[3]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/h536wymibaydldashx6s1ccpw9cbyb75-fetch-cargo-vendor-util/bin/fetch-cargo-vendor-util", line 263, in create_vendor
    copy_and_patch_git_crate_subtree(git_tree, pkg["name"], crate_out_dir)
  File "/nix/store/h536wymibaydldashx6s1ccpw9cbyb75-fetch-cargo-vendor-util/bin/fetch-cargo-vendor-util", line 202, in copy_and_patch_git_crate_subtree
    shutil.copytree(crate_tree, crate_out_dir, ignore_dangling_symlinks=True)
  File "/nix/store/f2krmq3iv5nibcvn4rw7nrnrciqprdkh-python3-3.12.9/lib/python3.12/shutil.py", line 600, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/f2krmq3iv5nibcvn4rw7nrnrciqprdkh-python3-3.12.9/lib/python3.12/shutil.py", line 498, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/nix/store/69fx0hw1g7z6mb70mlvakfy218pszbar-meilisearch-1.13.3-vendor/arroy-0.5.0'
```

Not sure how cargo behaves in this case, but perhaps this could be considered a bug in fetchCargoVendor?

**Comment by happysalada** [comment]
Yeah, lets try again with 1.14 then

**Comment by diogotcorreia** [comment]
1.14 has been release, I've opened a PR: https://github.com/NixOS/nixpkgs/pull/398526

**Comment by happysalada** [comment]
Im in favor of it
