### ISSUE TITLE
[Linux, x86_64] Deno crashes when using npm package (libstdc++.so.6: cannot open shared object file)

### ISSUE THREAD

**Issue by zakyum** [NixOS/nixpkgs#328668]
### Describe the bug
Deno 1.45.2 crashes saying that it can't find `libstdc++.so.6` when trying to use it with the npm:duckdb package.

Think that this is primarily caused by using Deno with an npm library which uses a binary, the DuckDB binary to be precise. The DuckDB binary probably depends on `libstdc++.so.6` and Deno can't find it because of Nix's isolating properties?

Works when installing Deno via their installer, i.e. without using Nix. Am not a Nix pro and don't know how to debug further, but would be willing to test more if provided instructions. Also I don't expect a fix, just wanted to mention this so that the problem is at least logged somewhere.

### Steps To Reproduce
1. Get Deno via Nix
2. Crete `nix-repro.ts` file:
```typescript
import { Database } from "npm:duckdb-async@1.0.0";

const db = await Database.create(":memory:");
```

3. Run file `deno run -A ./nix-repro.ts`
4. Get below error message
```console
$ deno run -A ./nix-repro.ts
error: Uncaught (in promise) TypeError: libstdc++.so.6: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:module:774:20)
    at Module.load (node:module:655:32)
    at Function.Module._load (node:module:523:12)
    at Module.require (node:module:674:19)
    at require (node:module:785:16)
    at Object.<anonymous> (file:///home/[project-name]/node_modules/.deno/duckdb@1.0.0/node_modules/duckdb/lib/duckdb-binding.js:4:15)
    at Object.<anonymous> (file:///home/[project-name]/node_modules/.deno/duckdb@1.0.0/node_modules/duckdb/lib/duckdb-binding.js:7:4)
    at Module._compile (node:module:730:34)
    at Object.Module._extensions..js (node:module:744:10)
    at Module.load (node:module:655:32)
```

### Expected behavior
Should not crash. Works when installing Deno via their installer, i.e. without using Nix. 

### Additional context
Works on macOS.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.20.5`
 - nixpkgs: `/Users/jkscx/.nix-defexpr/channels/nixpkgs`
```

### Notify maintainers
@06kellyjac 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
- system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-41-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.20.5`
 - nixpkgs: `/nix/store/qq257kq159smq2ais6i5halvssmc0g83-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
<details>
<summary>Interestingly enough, I got a different error:</summary>

```
error: Uncaught (in promise) Error: Cannot find module '/tmp/tmp.6CdaLl095N/home/.cache/deno/npm/registry.npmjs.org/duckdb/1.0.0/lib/binding/duckdb.node'
Require stack:
- /tmp/tmp.6CdaLl095N/home/.cache/deno/npm/registry.npmjs.org/duckdb/1.0.0/lib/duckdb-binding.js
- /tmp/tmp.6CdaLl095N/home/.cache/deno/npm/registry.npmjs.org/duckdb/1.0.0/lib/duckdb.js
- /tmp/tmp.6CdaLl095N/home/.cache/deno/npm/registry.npmjs.org/duckdb-async/1.0.0/dist/duckdb-async.js
- /tmp/tmp.6CdaLl095N/home/.cache/deno/npm/registry.npmjs.org/duckdb-async/1.0.0/dist/duckdb-async.js
    at Function.Module._resolveFilename (node:module:608:15)
    at Function.Module._load (node:module:486:27)
    at Module.require (node:module:674:19)
    at require (node:module:785:16)
    at Object.<anonymous> (file:///tmp/tmp.6CdaLl095N/home/.cache/deno/npm/registry.npmjs.org/duckdb/1.0.0/lib/duckdb-binding.js:4:15)
    at Object.<anonymous> (file:///tmp/tmp.6CdaLl095N/home/.cache/deno/npm/registry.npmjs.org/duckdb/1.0.0/lib/duckdb-binding.js:7:4)
    at Module._compile (node:module:730:34)
    at Object.Module._extensions..js (node:module:744:10)
    at Module.load (node:module:655:32)
    at Function.Module._load (node:module:523:12)
```

</details>

**Comment by 06kellyjac** [comment]
Yes. On nixos there is no /usr/lib dynamic libraries to pick up, that's not specific to the deno package in nixpkgs.

Because that `.node` file is dynamically linked it wont work unless you either patch it or provide it the dynamic path it wants via an FHS env, nix-alien, or something similar.

The easiest test would just to throw `steam-run` in front of your command.
That wraps around any command you give it and runs it in a more typical linux filestructure (FHS) so the program can find libs.

**Comment by deftdawg** [comment]
I got a very similar error in Electron's console running Joplin Desktop dev mode w/ `ELECTRON_OVERRIDE_DIST_PATH=$(dirname $(which electron)) yarn start`:
```
Uncaught Error: libstdc++.so.6: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2559)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at s._load (node:electron/js2c/renderer_init:2:30981)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/deftdawg/source/joplin/packages/app-desktop/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
```

Thanks to @06kellyjac suggestion of `steam-run`, I was able to workaround it:
```
ELECTRON_OVERRIDE_DIST_PATH=$(dirname $(which electron)) steam-run yarn start
```
