### ISSUE TITLE
homepage-dashboard: Failed to update prerender cache

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#328621]
### Steps To Reproduce
1. Use and configure `services.homepage-dashboard`, with:

```nix
services.homepage-dashboard = {
    enable = true;
    
    environmentFile = let
      file = pkgs.writeText "homepage-dashboard-env" ''
        LOG_LEVEL=debug
      '';
    in "${file}";

    # more if you like
};
```

3. Rebuild
4. Observe logs: `journalctl -eu homepage-dashboard`:

```
Jul 20 11:01:25 homepage-matthias homepage[150]: [2024-07-20T09:01:25.994Z] warn: Failed to update prerender cache for /en [Error: EROFS: read-only file system, open '/nix/store/9c74gwiq9w550jg7i2csv6ybxx41m94f-homepage-dashboard-0.8.13/share/homepage/.next/server/pages/en.html'] {
Jul 20 11:01:25 homepage-matthias homepage[150]:   errno: -30,
Jul 20 11:01:25 homepage-matthias homepage[150]:   code: 'EROFS',
Jul 20 11:01:25 homepage-matthias homepage[150]:   syscall: 'open',
Jul 20 11:01:25 homepage-matthias homepage[150]:   path: '/nix/store/9c74gwiq9w550jg7i2csv6ybxx41m94f-homepage-dashboard-0.8.13/share/homepage/.next/server/pages/en.html'
Jul 20 11:01:25 homepage-matthias homepage[150]: }
```

I am not sure whether this means that the service is unavailable, as the page opens as expected... but my configured `adguard` widget does not work although adguard is reachable from the `homepage-dashboard` instance...

### Notify maintainers

@jnsgruk 

---

Possibly related: https://github.com/NixOS/nixpkgs/issues/297168

**Comment by vifino** [comment]
Hi, I am also affected by this.
I cannot update my config once the initial deployment happened. Restarting does nothing.

**Comment by jnsgruk** [comment]
I think this is just the `environmentFile` option being used slightly wrong. This option is specifically for Homepage's support for passing secrets/values (see https://gethomepage.dev/latest/installation/docker/#using-environment-secrets)

Notably:

> - Environment variables must start with HOMEPAGE_VAR_ or HOMEPAGE_FILE_
> - The value of env var HOMEPAGE_VAR_XXX will replace {{HOMEPAGE_VAR_XXX}} in any config
> -The value of env var HOMEPAGE_FILE_XXX must be a file path, the contents of which will be used to replace {{HOMEPAGE_FILE_XXX}} in any config

If you want to change arbitrary env vars, try modifying the systemd unit directly?

```nix
systemd.services.homepage-dashboard.environment = lib.mkForce {
  FOO = "BAR";
  # ...
};
```

**Comment by jnsgruk** [comment]
Interesting, I'm not sure what's causing that. I'll try to take a look over the coming few days - I need to try and get a reproducer first, as I've not yet seen that behaviour.

**Comment by jnsgruk** [comment]
Hmm, okay I did finally get to repro this, but only when using the `customJS` option. Looking at it, this seems like an internal function of NextJS, and not something I'm sure I can fix from a packaging perspective -- that said, the log message is "only" a warning, and as far as I can tell my dashboard remains completely functional - if anything this might just result in slightly degraded performance, but I didn't notice anything in my instance.

**Comment by joegilkes** [comment]
Hi, I'm also having this problem. I've been trying to set this up for the first time today with widgets for Jellyfin, AdGuard and Glance (config [here](https://github.com/joegilkes/nixos-config/blob/2c269797da617be1efed0fa6d4305066ed6a2634/systems/x86_64-linux/giants-deep/homepage.nix)), but when I re-`nixos-rebuild switch` and restart the `homepage-dashboard` service, I get this:

```
Aug 27 23:25:24 giants-deep systemd[1]: Started Homepage Dashboard.
Aug 27 23:25:24 giants-deep homepage[31457]: Listening on port 8082
Aug 27 23:25:29 giants-deep homepage[31457]: [2024-08-27T22:25:29.769Z] warn: Failed to update prerender cache for /en Error: EROFS: read-only file system, open '/nix/store/2p733ck0n0byi6f5s4qwc0phd2mf7w26-homepage-dashboard-0.9.6/share/homepage/.next/server/pages/en.html'
Aug 27 23:25:29 giants-deep homepage[31457]:     at async open (node:internal/fs/promises:639:25)
Aug 27 23:25:29 giants-deep homepage[31457]:     at async Object.writeFile (node:internal/fs/promises:1219:14)
Aug 27 23:25:29 giants-deep homepage[31457]:     at async FileSystemCache.set (/nix/store/2p733ck0n0byi6f5s4qwc0phd2mf7w26-homepage-dashboard-0.9.6/share/homepage/node_modules/next/dist/server/lib/incremental-cache/file-system-cache.js:69:13)
Aug 27 23:25:29 giants-deep homepage[31457]:     at async IncrementalCache.set (/nix/store/2p733ck0n0byi6f5s4qwc0phd2mf7w26-homepage-dashboard-0.9.6/share/homepage/node_modules/next/dist/server/lib/incremental-cache/index.js:113:13)
Aug 27 23:25:29 giants-deep homepage[31457]:     at async /nix/store/2p733ck0n0byi6f5s4qwc0phd2mf7w26-homepage-dashboard-0.9.6/share/homepage/node_modules/next/dist/server/response-cache/index.js:98:25 {
Aug 27 23:25:29 giants-deep homepage[31457]:   errno: -30,
Aug 27 23:25:29 giants-deep homepage[31457]:   code: 'EROFS',
Aug 27 23:25:29 giants-deep homepage[31457]:   syscall: 'open',
Aug 27 23:25:29 giants-deep homepage[31457]:   path: '/nix/store/2p733ck0n0byi6f5s4qwc0phd2mf7w26-homepage-dashboard-0.9.6/share/homepage/.next/server/pages/en.html'
Aug 27 23:25:29 giants-deep homepage[31457]: }
```

This is the only error I see, and it gets printed again when I refresh the page with the button in the bottom right. Weirdly I don't see any errors on the web page, but the AdGuard module and all of the Glance modules fail to show up at all. Not sure if that's similar to what @vifino was seeing when they said

> I cannot update my config once the initial deployment happened. Restarting does nothing.

since it could be the page not updating properly from the state it was initially created in. For reference, I've attached a screenshot of the page that the linked config is currently generating.

![image](https://github.com/user-attachments/assets/6981ec0c-8da7-47a9-9be2-af4b40394d74)

**Comment by jnsgruk** [comment]
Okay, I think I've got a fix in #337902

**Comment by jnsgruk** [comment]
I think this is now addressed, and once #337902 trickles through to `unstable` it'll be easier to test out. Please feel free to report back if it hasn't solved the problem - locally it seemed good to me!

You can track the PR's progress here: https://nixpkgs-tracker.ocfox.me/?pr=337902

**Comment by matthiasbeyer** [comment]
Ah nice, I only knew https://nixpk.gs/pr-tracker.html?pr=337902
