### ISSUE TITLE
Package request: yt-dlp-dearrow

### ISSUE THREAD

**Issue by 0n-s** [NixOS/nixpkgs#329748]
(note that packaging yt-dlp plugins has its own special procedure: https://github.com/yt-dlp/yt-dlp#installing-plugins)

**Project description**
Post-processor plugin to use [DeArrow](https://dearrow.ajay.app) video titles in yt-dlp.

**Metadata**

* homepage URL: https://github.com/QuantumWarpCode/yt-dlp-dearrow
* source URL: https://github.com/QuantumWarpCode/yt-dlp-dearrow
* license: MIT
* platforms: same as yt-dlp

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 0n-s** [comment]
It's _technically_ packaged, yes, but it's currently unusable:
```
$ yt-dlp --use-postprocessor DeArrow:when=pre_process
Traceback (most recent call last):
  File "/nix/store/b5wz4vi8paggp19ni0395yzrna3as10z-yt-dlp-2024.8.6/bin/.yt-dlp-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/b5wz4vi8paggp19ni0395yzrna3as10z-yt-dlp-2024.8.6/lib/python3.12/site-packages/yt_dlp/__init__.py", line 1081, in main
    _exit(*variadic(_real_main(argv)))
                    ^^^^^^^^^^^^^^^^
  File "/nix/store/b5wz4vi8paggp19ni0395yzrna3as10z-yt-dlp-2024.8.6/lib/python3.12/site-packages/yt_dlp/__init__.py", line 979, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
         ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/b5wz4vi8paggp19ni0395yzrna3as10z-yt-dlp-2024.8.6/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 809, in __init__
    get_postprocessor(pp_def.pop('key'))(self, **pp_def),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/b5wz4vi8paggp19ni0395yzrna3as10z-yt-dlp-2024.8.6/lib/python3.12/site-packages/yt_dlp/postprocessor/__init__.py", line 42, in get_postprocessor
    return globals()[key + 'PP']
           ~~~~~~~~~^^^^^^^^^^^^
KeyError: 'DeArrowPP'
```
So it'll probably need SMTH like `wrapOBS` to actually work.
