### ISSUE TITLE
prismlauncher: 1.20.5+ of minecraft (java 21) cannot locate libpipewire-0.3.so.0 (openal)

### ISSUE THREAD

**Issue by TheAwesome98-Real** [NixOS/nixpkgs#330154]
### Describe the bug
when launching 1.20.5+ versions of minecraft (these use java 21), soundsystem cannot load because openal cannot find libpipewire-0.3.so.0

### Steps To Reproduce
1. create an instance of the latest version of minecraft (i used 1.21 with quilt)
2. go to instance settings and add the env vars `ALSOFT_LOGLEVEL=3` and `ALSOFT_LOGFILE=/tmp/openal.log` (this is used for later debugging, it's not part of the issue)
3. launch the game until you see the title screen, then quit
4. search through the logs - you will eventually find an openal exception, with not much information
5. open /tmp/openal.log - it will fail to load several .so files, one of which is libpipewire-0.3.so.0

### Expected behavior
openal should be able to open the .so files it mentions it cannot open

### Additional context
it also fails to load narrator, which i seem to remember it being able to do before, also because of .so files it cannot locate. i also updated from 23.11 to 24.05. i'm not 100% confident with nix, but there could be some leftover things in the /nix folder causing this? the paths it was looking for seem real

### Notify maintainers
haven't made an issue here so apologies if these are the wrong people
@Minion3665
@Scrumplex 
@getchoo

### Metadata

```console
[lily@dawn:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.40, NixOS, 24.05 (Uakari), 24.05.2933.c716603a63ac`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by getchoo** [comment]
I can't reproduce this, but based on my local `/tmp/openal.log`

```
[ALSOFT] (WW) Failed to load libpipewire-0.3.so.0
[ALSOFT] (WW) Failed to initialize backend "pipewire"
[ALSOFT] (II) Key pulse/spawn-server not found
[ALSOFT] (II) Initialized backend "pulse"
[ALSOFT] (II) Added "pulse" for playback
[ALSOFT] (II) Added "pulse" for capture
```

I can assume that it works in my case because i have `pipewire-pulse` enabled and we [include](https://github.com/NixOS/nixpkgs/blob/a1cc729dcbc31d9b0d11d86dc7436163548a9665/pkgs/games/prismlauncher/wrapper.nix#L99) libpulseaudio in the wrapper. Could you check for config for [services.pipewire.pulse.enable](https://search.nixos.org/options?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=pipewire.pulse)? Another workaround is to go to instance settings>workarounds and check "Use system installation of OpenAL."

For maintainer: the top of the log output for Mojang's prebuild binaries reports

> [ALSOFT] (II) Supported backends: pipewire, pulse, alsa, oss, jack, port, null, wave

We should be linking libraries for all of these. I'll probably make a PR soon :p

**Comment by TheAwesome98-Real** [comment]
> Could you check for config for [services.pipewire.pulse.enable](https://search.nixos.org/options?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=pipewire.pulse)?
yep, i have it
> Another workaround is to go to instance settings>workarounds and check "Use system installation of OpenAL."
i tried this before opening the issue but it caused the game not to open at all (i think it said the .so files were missing? i'll send a log later)

**Comment by TheAwesome98-Real** [comment]
> go to instance settings>workarounds and check "Use system installation of OpenAL."

when i try this, i get this stack trace:
<details>
<summary>long stack trace</summary>

```
java.lang.UnsatisfiedLinkError: Failed to dynamically load library: /nix/store/8dv3xrdxc29f8isssp31ac2g9dbr1xc6-openal-soft-1.23.1/lib/libopenal.so(error = null)
	at org.lwjgl.system.linux.LinuxLibrary.loadLibrary(LinuxLibrary.java:33)
	at org.lwjgl.system.linux.LinuxLibrary.<init>(LinuxLibrary.java:20)
	at org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:128)
	at org.lwjgl.system.Library.loadNative(Library.java:251)
	at org.lwjgl.system.Library.loadNative(Library.java:236)
	at org.lwjgl.openal.ALC.create(ALC.java:119)
	at org.lwjgl.openal.ALC.create(ALC.java:76)
	at org.lwjgl.openal.ALC.<clinit>(ALC.java:55)
	at org.lwjgl.openal.ALC10.nalcIsExtensionPresent(ALC10.java:256)
	at org.lwjgl.openal.ALC10.alcIsExtensionPresent(ALC10.java:292)
	at net.minecraft.class_4225.method_38500(class_4225.java:258)
	at net.minecraft.class_4225.<init>(class_4225.java:150)
	at net.minecraft.class_1140.<init>(class_1140.java:65)
	at net.minecraft.class_1144.<init>(class_1144.java:64)
	at net.minecraft.class_310.<init>(class_310.java:550)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

</details>

but the file exists:
```console
[lily@dawn:~]$ stat /nix/store/8dv3xrdxc29f8isssp31ac2g9dbr1xc6-openal-soft-1.23.1/lib/libopenal.so
  File: /nix/store/8dv3xrdxc29f8isssp31ac2g9dbr1xc6-openal-soft-1.23.1/lib/libopenal.so -> libopenal.so.1
  Size: 14        	Blocks: 0          IO Block: 4096   symbolic link
Device: 8,19	Inode: 19146647    Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-07-19 18:26:06.339979133 +0100
Modify: 1970-01-01 01:00:01.000000000 +0100
Change: 2024-07-19 18:25:14.426174926 +0100
 Birth: 2024-07-19 18:25:12.585217366 +0100
```
and i'm not sure what else would cause that error (or how to find out more information on why it failed to load)

**Comment by TheAwesome98-Real** [comment]
this isn't fixed, even after running `sudo nixos-rebuild switch --upgrade`

**Comment by pbsds** [comment]
consider re-opening the issue if you want a backport to stable

**Comment by TheAwesome98-Real** [comment]
a backport to stable would be nice considering that's what most people would install, and sound is a pretty important feature for most users

unfortunately i can't re-open the issue, do you want me to remake it?

**Comment by getchoo** [comment]
This was included in 24.11, which is now the stable release
