### ISSUE TITLE
Missing `xdotool` dependency in `smile` package

### ISSUE THREAD

**Issue by agersant** [NixOS/nixpkgs#330372]
### Describe the bug

The `smile` emoji picker terminates unexpectedly upon clicking an emoji.

### Steps To Reproduce

1. Install any X desktop environment, and make sure `xdotool` is not installed
2. Run `nix-shell -p smile`
3. Run `smile`
4. Click an emoji
5. Observe error message: 

```console
Traceback (most recent call last):
  File "/nix/store/gjc79ly6zxs5hwii0m86d1b5a5z1kgmh-smile-2.9.5/share/smile/smile/Picker.py", line 303, in handle_emoji_button_click
    self.copy_and_quit(widget)
  File "/nix/store/gjc79ly6zxs5hwii0m86d1b5a5z1kgmh-smile-2.9.5/share/smile/smile/Picker.py", line 633, in copy_and_quit
    self.default_hiding_action()
  File "/nix/store/gjc79ly6zxs5hwii0m86d1b5a5z1kgmh-smile-2.9.5/share/smile/smile/Picker.py", line 498, in default_hiding_action
    self.send_paste_signal()
  File "/nix/store/gjc79ly6zxs5hwii0m86d1b5a5z1kgmh-smile-2.9.5/share/smile/smile/Picker.py", line 478, in send_paste_signal
    subprocess.check_output(['xdotool', 'key', 'ctrl+v'])
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdotool'
```

### Expected behavior

The emoji is inserted in the current window and the emoji picker exits gracefully.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers

@koppor 
@Aleksanaa 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
:::
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41, NixOS, 24.11 (Vicuna), 24.11.20240721.68c9ed8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/afawjm6nv8m5aagkcqxlxgrr5qpyh6cm-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by agersant** [comment]
Thank you!
