### ISSUE TITLE
python3-venv broken

### ISSUE THREAD

**Issue by MrQubo** [NixOS/nixpkgs#330583]
### Describe the bug

python3-venv is broken on unstable. 24.05.3164.63d37ccd2d17 works.

### Steps To Reproduce

1. `nix run 'nixpkgs#python3' -- -m venv venv_dir`
2. `. ./venv_dir/bin/activate`
3. `pip install -U pip` (or any other package)
<details>
<summary>Error Output</summary>

```
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 326, in run
    session = self.get_default_session(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
    self._session = self.enter_context(self._build_session(options))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/network/session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/importlib/_envs.py", line 188, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/importlib/_envs.py", line 183, in <genexpr>
    matches = (
              ^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    for dist in finder.find_eggs(location):
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/importlib/_envs.py", line 144, in find_eggs
    yield from self._find_eggs_in_dir(location)
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/importlib/_envs.py", line 111, in _find_eggs_in_dir
    from pip._vendor.pkg_resources import find_distributions
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
Traceback (most recent call last):
  File "/home/nix/tmp/freeGPT/venv_dir/bin/pip", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    self.handle_pip_version_check(options)
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 179, in handle_pip_version_check
    session = self._build_session(
              ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/network/session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/importlib/_envs.py", line 188, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/importlib/_envs.py", line 183, in <genexpr>
    matches = (
              ^
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    for dist in finder.find_eggs(location):
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/importlib/_envs.py", line 144, in find_eggs
    yield from self._find_eggs_in_dir(location)
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/metadata/importlib/_envs.py", line 111, in _find_eggs_in_dir
    from pip._vendor.pkg_resources import find_distributions
  File "/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```
</details>

### Additional context

I wanted to use venv to install pip package not packaged in nix.

### Notify maintainers

Dunno.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32-hardened1, NixOS, 24.05 (Uakari), 24.05.3164.63d37ccd2d17`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(nix): `""`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05, nixos-hardware, nixos-unstable, nur"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by natsukium** [comment]
I can't reproduce this problem.

> `/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/base_command.py`

Since you don't seem to use pip from venv, could you check your $PATH?

**Comment by MrQubo** [comment]
That's how `./venv_dir/bin/pip` looks like:
```python3
#!/home/nix/tmp/venv_dir/bin/python3.12
# -*- coding: utf-8 -*-
import re
import sys
from pip._internal.cli.main import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

It looks like `from pip` import resolves to `/nix/store/bk06jpp1hswx6i8zyzbk4lgkfyq92qic-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip`, which is completely incorrect python version.

When I run the "Steps to Reproduce" I was already in a `nix-shell` shell with python3.10. `nix-shell` sets $PYTHONPATH. `nix shell` didn't set $PYTHONPATH. That's why import was resolved incorrectly.

**Comment by MrQubo** [comment]
We could fix this issue in nix by patching venv so it sets `PYTHONPATH` correctly in `activate` script.
Though I feel like venv should do this by itself and maybe it would be better to fix it upstream?

**Comment by MrQubo** [comment]
Seems like this was fixed, I can no longer reproduce.
