### ISSUE TITLE
Build failure: skia-aseprite (aarch64-darwin)

### ISSUE THREAD

**Issue by LeFlorians** [NixOS/nixpkgs#332312]
### Steps To Reproduce

Build the package with
```
nix build nixpkgs#skia-aseprite
```
(Most certainly a platform-specific build failure)

### Build log

```
error: builder for '/nix/store/srml7zl7xq763758r36hgwsdvm1paabk-skia-aseprite-m102-861e4743af.drv' failed with exit code 1;
       last 25 log lines:
       > Current dir: /private/tmp/nix-build-skia-aseprite-m102-861e4743af.drv-0/source/lib/
       > Command: python3 /private/tmp/nix-build-skia-aseprite-m102-861e4743af.drv-0/source/gn/find_xcode_sysroot.py macosx
       > Returned 1.
       > stderr:
       >
       > Traceback (most recent call last):
       >   File "/private/tmp/nix-build-skia-aseprite-m102-861e4743af.drv-0/source/gn/find_xcode_sysroot.py", line 15, in <module>
       >     print(subprocess.check_output([
       >           ^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/3swy1vadi125g0c1vxqp8ykdr749803j-python3-3.12.4/lib/python3.12/subprocess.py", line 466, in check_output
       >     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
       >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/3swy1vadi125g0c1vxqp8ykdr749803j-python3-3.12.4/lib/python3.12/subprocess.py", line 548, in run
       >     with Popen(*popenargs, **kwargs) as process:
       >          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/3swy1vadi125g0c1vxqp8ykdr749803j-python3-3.12.4/lib/python3.12/subprocess.py", line 1026, in __init__
       >     self._execute_child(args, executable, preexec_fn, close_fds,
       >   File "/nix/store/3swy1vadi125g0c1vxqp8ykdr749803j-python3-3.12.4/lib/python3.12/subprocess.py", line 1955, in _execute_child
       >     raise child_exception_type(errno_num, err_msg, err_filename)
       > FileNotFoundError: [Errno 2] No such file or directory: 'xcrun'
       >
       > See //gn/BUILDCONFIG.gn:178:3: which caused the file to be included.
       >   "//gn/skia:default",
       >   ^------------------
       >
       For full logs, run 'nix log /nix/store/srml7zl7xq763758r36hgwsdvm1paabk-skia-aseprite-m102-861e4743af.drv'.
```

### Additional context

As this is a dependency of aseprite / aseprite-unfree, that package can't be built either.

The file causing the issue seems to be part of aseprite's fork of skia (which seems to be unmaintained):
https://github.com/aseprite/skia/blob/bbcd043092bfc6e3eaa7037202652155e6bd0722/gn/find_xcode_sysroot.py#L4

I can run the xcrun command from my shell, but since nix builds are reproducible, it can't pick it up...

### Notify maintainers

@orivej 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix run nixpkgs#nix-info -- -m

 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `not found` # (it's actually the latest unstable nixpkgs version)
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kashw2** [comment]
Is the output log still accurate for you. Taking a look at this I get:

```
 ❄️ | home | nixpkgs |  master [?]  : nix build --system "aarch64-darwin" --print-out-paths .#skia-aseprite
error:
       … while evaluating an expression to select 'drvPath' on it
         at «internal»:1:552:
       … while evaluating strict
         at «internal»:1:552:
       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Package ‘libdrm-2.4.124’ in /nix/store/plnrxkc07i8qrk55r3jnm6zhpy42jasy-source/pkgs/by-name/li/libdrm/package.nix:71 is not available on the requested hostPlatform:
         hostPlatform.config = "arm64-apple-darwin"
         package.meta.platforms = [
           "i686-cygwin"
           "x86_64-cygwin"
           "i686-freebsd"
           "x86_64-freebsd"
           "aarch64-freebsd"
           "x86_64-solaris"
           "aarch64-linux"
           "armv5tel-linux"
           "armv6l-linux"
           "armv7a-linux"
           "armv7l-linux"
           "i686-linux"
           "loongarch64-linux"
           "m68k-linux"
           "microblaze-linux"
           "microblazeel-linux"
           "mips-linux"
           "mips64-linux"
           "mips64el-linux"
           "mipsel-linux"
           "powerpc64-linux"
           "powerpc64le-linux"
           "riscv32-linux"
           "riscv64-linux"
           "s390-linux"
           "s390x-linux"
           "x86_64-linux"
           "aarch64-netbsd"
           "armv6l-netbsd"
           "armv7a-netbsd"
           "armv7l-netbsd"
           "i686-netbsd"
           "m68k-netbsd"
           "mipsel-netbsd"
           "powerpc-netbsd"
           "riscv32-netbsd"
           "riscv64-netbsd"
           "x86_64-netbsd"
           "i686-openbsd"
           "x86_64-openbsd"
           "x86_64-redox"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
```
