### ISSUE TITLE
apache-directory-studio unable to run

### ISSUE THREAD

**Issue by Ypnose** [NixOS/nixpkgs#333377]
### Describe the bug

`apache-directory-studio` can't be launched. I have this error :

```
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
	no swt-pi4-gtk-4940r23 in java.library.path: /nix/store/krmmziid35mj6qpzdsbrbcfgvzpfnal5-webkitgtk-2.44.2+abi=4.0/lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4-gtk in java.library.path: /nix/store/krmmziid35mj6qpzdsbrbcfgvzpfnal5-webkitgtk-2.44.2+abi=4.0/lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
```

### Steps To Reproduce

1. Launch `apache-directory-studio` as usual
2. It says :

```
ApacheDirectoryStudio:
An error has occurred. See the log file
/home/foo/.eclipse/1465834203_linux_gtk_x86_64/configuration/1723184305864.log
```

### Expected behavior

The GUI should start. 

### Additional context

`apache-directory-studio` is installed with `home-manager`. It was working since October 2023.

### Fix

`swt` should be added to this line :

```
{ lib, stdenv, fetchurl, jdk, makeWrapper, autoPatchelfHook, makeDesktopItem, glib, libsecret, webkitgtk }:
```

And adding lines in this block does the trick :

```
    makeWrapper "$dest/ApacheDirectoryStudio" \
        "$out/bin/ApacheDirectoryStudio" \
        --prefix PATH : "${jdk}/bin" \
        --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath ([ glib ])} \
        --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath ([ swt ])} \
        --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath ([ webkitgtk ])}
```

### Notify maintainers

@bjornfor 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.43, NixOS, 24.11 (Vicuna), 24.11.20240804.cb9a96f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bjornfor** [comment]
I ran `mkdir /tmp/SWT-GDBusServer/` and now it works. Hm...

**Comment by bjornfor** [comment]
> `/tmp/SWT-GDBusServer/`

Searching for this path lead to this interesting comment: https://github.com/adoptium/adoptium-support/issues/785#issuecomment-1866680133

**Comment by Ypnose** [comment]
Thanks for taking the time to take a look. It sounds sketchy. What could we do ?

**Comment by bjornfor** [comment]
I looked at upgrading swt, but got stuck.

We can add swt and glib and use a/the wrapper to create the temporary directory. But other programs using swt will still have the bug.

**Comment by Ypnose** [comment]
Are you using a Wayland compositor ? On `sway`, I was able to reproduce what you said. But on X11 with `i3`, `apache-directory-studio` starts without issue here.

**Comment by bjornfor** [comment]
Yes, I'm using Wayland (in GNOME desktop).

**Comment by Ypnose** [comment]
Creating a wrapper would do the trick, isn't it ? I am thinking about creating a local `apache-directory-studio` with a wrapper.

**Comment by bjornfor** [comment]
> Creating a wrapper would do the trick, isn't it ?

Yes.

>I am thinking about creating a local `apache-directory-studio` with a wrapper.

What? Where? Just create the directory `/tmp/SWT-GDBusServer/` and it'll work.

**Comment by Ypnose** [comment]
I was talking about the local `apache-directory-studio` because you didn't merge the `lib.makeLibraryPath` and `swt` lines we discussed earlier. I do not want to be a bore.

**Comment by Thatoo** [comment]
I face the same issue on unstable under Cosmic (Wayland).

**Comment by TafkaMax** [comment]
Same issue on 24.11 Gnome (Wayland)

**Comment by volker-schukai** [comment]
I have the same bug, Apache-Directory-Studio no longer starts for me. I use X and i3 (no home-manager).

 nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.72, NixOS, 24.11 (Vicuna), 24.11.713549.035f8c0853c2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`


!SESSION 2025-01-26 15:30:10.263 -----------------------------------------------
eclipse.buildId=unknown
java.version=21.0.5
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  /studio-rcp/resources/icons/linux/studio.xpm
Command-line arguments:  -os linux -ws gtk -arch x86_64 /studio-rcp/resources/icons/linux/studio.xpm

!ENTRY org.eclipse.osgi 4 0 2025-01-26 15:30:10.984
!MESSAGE Anwendungsfehler
!STACK 1
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4940r23 in java.library.path: /nix/store/wqflihshmaarwdcksncblcyminzd8pwg-webkitgtk-2.46.5+abi=4.0/lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4-gtk in java.library.path: /nix/store/wqflihshmaarwdcksncblcyminzd8pwg-webkitgtk-2.46.5+abi=4.0/lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:338)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:96)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
....

**Comment by bjornfor** [comment]
There's a fix at https://github.com/NixOS/nixpkgs/pull/384524, ready for review.
