### ISSUE TITLE
python3Packages.dasbus: Namespace GLib not available when importing package during runtime

### ISSUE THREAD

**Issue by pacjo** [NixOS/nixpkgs#334089]
### Describe the bug
I'm trying to package [lnxlink](https://github.com/bkbilly/lnxlink). I got it mostly working, but one of the dependencies is `dasbus`. When program tries to import it I get: `Namespace GLib not available`

### Steps To Reproduce
1. Create `lnxlink` executable with the expression (is this the right term?) below
2. Run with `lnxlink -c lnxlink.yaml`
3. See error

### Expected behavior
No error.

### Additional context
It my first time packaging anything for nix, so I'm not really sure what I'm doing.

`lnxlink.nix`:
```nix
{ lib
, python3Packages
, fetchPypi
}:

python3Packages.buildPythonApplication rec {
  pname = "lnxlink";
  version = "2024.8.1";
  pyproject = true;

  src = fetchPypi {
    inherit pname version;
    hash  = "sha256-cEm+ha4oz5CGe9cqVKX8TAmY7y7GnqMnwVuuNx31EE4=";
  };

  postPatch = ''
    substituteInPlace pyproject.toml \
      --replace-fail "setuptools~=68.0.0" "setuptools" \
      --replace-fail "wheel~=0.40.0" "wheel"
  '';

  nativeBuildInputs = with python3Packages; [
    setuptools
    wheel
  ];

  propagatedBuildInputs = with python3Packages; [
    pyyaml
    distro
    inotify
    jc
    paho-mqtt
    psutil
    requests
    pygobject3
    speechrecognition
    dasbus
    ewmh
    mss
    numpy
    opencv4
    pulsectl
    xlib
  ];

  meta = with lib; {
    description = "Effortlessly manage your Linux machine using MQTT.";
    homepage = "https://github.com/bkbilly/lnxlink";
    license = licenses.mit;
  };
}
```

<details>
  <summary><code>logs</code></summary>

```console
INFO:lnxlink:LNXlink 2024.8.1, Python 3.12.4
ERROR:lnxlink:Can't import package dasbus: Namespace GLib not available
ERROR:lnxlink:Can't use DBus for system monitor
INFO:lnxlink:Installing 'dbus-networkdevices>=2024.0.7'...
ERROR:lnxlink:Can't install package dbus-networkdevices
ERROR:lnxlink:Error with addon sys_updates, please remove it from your config: System commands not found for package manager
INFO:lnxlink:Loaded addons: required_restart, bluetooth, temperature, shutdown, disk_usage, microphone_used, mounts, speaker_used, restart, display_env, memory, statistics, camera_used, wifi, interfaces, update, cpu, suspend, active_window, gamepad
INFO:lnxlink:MQTT connection: Connection Accepted.
ERROR:lnxlink:Error with addon WiFi: 'NoneType' object has no attribute 'DBUSNetworkDevices', Traceback (most recent call last):
  File "/nix/store/pk314m2adnjs94pdwjfclgx22ab4sm17-lnxlink-2024.8.1/lib/python3.12/site-packages/lnxlink/__main__.py", line 130, in run_module
    pub_data = method()
               ^^^^^^^^
  File "/nix/store/pk314m2adnjs94pdwjfclgx22ab4sm17-lnxlink-2024.8.1/lib/python3.12/site-packages/lnxlink/modules/wifi.py", line 43, in get_info
    devices = self.lib["dbus_nd"].DBUSNetworkDevices().get_network_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'DBUSNetworkDevices'

^CINFO:lnxlink:stopped gracefully
INFO:lnxlink:Power Down detected.
INFO:lnxlink:Disconnected from MQTT.
```
  
ignore `dbus-networkdevices` related errors, I have it in works, but it has the same issues as `dasbus`.

</details>

### Notify maintainers
@moni-dz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.43, NixOS, 24.11 (Vicuna), 24.11pre659698.52ec9ac3b123`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos, nixos-unstable, plasma-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


took 3s 
~ ❯
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
Try adding `wrapGAppsHook4` (or 3) to `nativeBuildInputs`.

**Comment by pacjo** [comment]
Oh my... it works! `wrapGAppsHook4` fixed it. Thanks so much!

I pretty sure I tried it before with `wrapGAppsHook` and it didn't work. Do you know why could that be?

Also, is it something I can add to nixpkgs, or should it be used to tools like `poetry2nix` instead?
Alongside `lnxlink` I packaged `dbus-idle`, `dbus-mediaplayer`, `dbus-networkdevices`, `dbus-notification`, `nvsmi`, `pyalsaaudio` and `pyamdgpuinfo` to get it working. Those latter could make a nice addition to the repo in my opinion.

**Comment by dotlambda** [comment]
> Also, is it something I can add to nixpkgs

Definitely!

**Comment by pacjo** [comment]
Awesome, can I do it all in one PR? Most initial PRs I've seen only affected one package.

**Comment by dotlambda** [comment]
Anything that's a dependency of lnxlink should be put in the same PR, everything else not.

**Comment by KennethHoff** [comment]
I've been trying to install lnxlink as well; 

Did you ever solve it? What was the final expression? I tried copying the one you had in the description and I get this error:

```
/home/kennethhoff/dotfiles/nix % sudo nixos-rebuild switch --show-trace --flake ~/dotfiles/nix
error:
       … while calling the 'seq' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:334:18:
          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          335|         _module = checked (config._module);

       … while evaluating a branch condition
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:273:9:
          272|       checkUnmatched =
          273|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [] then
             |         ^
          274|           let

       … in the left operand of the AND (&&) operator
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:273:72:
          272|       checkUnmatched =
          273|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [] then
             |                                                                        ^
          274|           let

       … in the left operand of the AND (&&) operator
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:273:33:
          272|       checkUnmatched =
          273|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [] then
             |                                 ^
          274|           let

       … while evaluating a branch condition
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:266:12:
          265|
          266|         in if declaredConfig._module.freeformType == null then declaredConfig
             |            ^
          267|           # Because all definitions that had an associated option ended in

       … from call site
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:254:28:
          253|           # For definitions that have an associated option
          254|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                            ^
          255|

       … while calling 'mapAttrsRecursiveCond'
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/attrsets.nix:1200:5:
         1199|     f:
         1200|     set:
             |     ^
         1201|     let

       … while calling the 'mapAttrs' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/attrsets.nix:1209:5:
         1208|     in
         1209|     recurse [ ] set;
             |     ^
         1210|

       … while evaluating the attribute 'matchedOptions'
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:692:15:
          691|     in {
          692|       inherit matchedOptions;
             |               ^
          693|

       … while calling the 'mapAttrs' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:683:24:
          682|
          683|       matchedOptions = mapAttrs (n: v: v.matchedOptions) resultsByName;
             |                        ^
          684|

       … while calling the 'mapAttrs' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:636:23:
          635|
          636|       resultsByName = mapAttrs (name: decls:
             |                       ^
          637|         # We're descending into attribute ‘name’.

       … while calling the 'zipAttrsWith' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:553:9:
          552|       declsByName =
          553|         zipAttrsWith
             |         ^
          554|           (n: concatLists)

       … while calling the 'map' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:555:12:
          554|           (n: concatLists)
          555|           (map
             |            ^
          556|             (module: let subtree = module.options; in

       … from call site
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:246:33:
          245|           ({ inherit lib options config specialArgs; } // specialArgs);
          246|         in mergeModules prefix (reverseList collected);
             |                                 ^
          247|

       … while calling 'reverseList'
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/lists.nix:1116:17:
         1115|   */
         1116|   reverseList = xs:
             |                 ^
         1117|     let l = length xs; in genList (n: elemAt xs (l - n - 1)) l;

       … while calling the 'genList' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/lists.nix:1117:27:
         1116|   reverseList = xs:
         1117|     let l = length xs; in genList (n: elemAt xs (l - n - 1)) l;
             |                           ^
         1118|

       … while evaluating the second argument passed to builtins.genList

       … while calling the 'length' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/lists.nix:1117:13:
         1116|   reverseList = xs:
         1117|     let l = length xs; in genList (n: elemAt xs (l - n - 1)) l;
             |             ^
         1118|

       … from call site
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:241:25:
          240|       merged =
          241|         let collected = collectModules
             |                         ^
          242|           class

       … while calling anonymous lambda
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:452:37:
          451|
          452|     in modulesPath: initialModules: args:
             |                                     ^
          453|       filterModules modulesPath (collectStructuredModules unknownModule "" initialModules args);

       … from call site
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:453:7:
          452|     in modulesPath: initialModules: args:
          453|       filterModules modulesPath (collectStructuredModules unknownModule "" initialModules args);
             |       ^
          454|

       … while calling 'filterModules'
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:420:36:
          419|       # modules recursively. It returns the final list of unique-by-key modules
          420|       filterModules = modulesPath: { disabled, modules }:
             |                                    ^
          421|         let

       … while calling the 'map' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:447:12:
          446|           keyFilter = filter (attrs: ! elem attrs.key disabledKeys);
          447|         in map (attrs: attrs.module) (genericClosure {
             |            ^
          448|           startSet = keyFilter modules;

       … while calling the 'genericClosure' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:447:39:
          446|           keyFilter = filter (attrs: ! elem attrs.key disabledKeys);
          447|         in map (attrs: attrs.module) (genericClosure {
             |                                       ^
          448|           startSet = keyFilter modules;

       … while calling the 'filter' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:448:22:
          447|         in map (attrs: attrs.module) (genericClosure {
          448|           startSet = keyFilter modules;
             |                      ^
          449|           operator = attrs: keyFilter attrs.modules;

       … while calling anonymous lambda
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:446:31:
          445|           disabledKeys = concatMap ({ file, disabled }: map (moduleKey file) disabled) disabled;
          446|           keyFilter = filter (attrs: ! elem attrs.key disabledKeys);
             |                               ^
          447|         in map (attrs: attrs.module) (genericClosure {

       … in the argument of the not operator
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:446:40:
          445|           disabledKeys = concatMap ({ file, disabled }: map (moduleKey file) disabled) disabled;
          446|           keyFilter = filter (attrs: ! elem attrs.key disabledKeys);
             |                                        ^
          447|         in map (attrs: attrs.module) (genericClosure {

       … while calling the 'elem' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:446:40:
          445|           disabledKeys = concatMap ({ file, disabled }: map (moduleKey file) disabled) disabled;
          446|           keyFilter = filter (attrs: ! elem attrs.key disabledKeys);
             |                                        ^
          447|         in map (attrs: attrs.module) (genericClosure {

       … while calling the 'concatMap' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:445:26:
          444|
          445|           disabledKeys = concatMap ({ file, disabled }: map (moduleKey file) disabled) disabled;
             |                          ^
          446|           keyFilter = filter (attrs: ! elem attrs.key disabledKeys);

       … while calling the 'concatLists' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:402:24:
          401|           collectResults = modules: {
          402|             disabled = concatLists (catAttrs "disabled" modules);
             |                        ^
          403|             inherit modules;

       … while evaluating the attribute 'disabled'
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:402:13:
          401|           collectResults = modules: {
          402|             disabled = concatLists (catAttrs "disabled" modules);
             |             ^
          403|             inherit modules;

       … while calling the 'concatLists' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:402:24:
          401|           collectResults = modules: {
          402|             disabled = concatLists (catAttrs "disabled" modules);
             |                        ^
          403|             inherit modules;

       … while evaluating the attribute 'disabled'
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:402:13:
          401|           collectResults = modules: {
          402|             disabled = concatLists (catAttrs "disabled" modules);
             |             ^
          403|             inherit modules;

       … while calling the 'concatLists' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:402:24:
          401|           collectResults = modules: {
          402|             disabled = concatLists (catAttrs "disabled" modules);
             |                        ^
          403|             inherit modules;

       … while evaluating the attribute 'disabled'
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:402:13:
          401|           collectResults = modules: {
          402|             disabled = concatLists (catAttrs "disabled" modules);
             |             ^
          403|             inherit modules;

       … while calling the 'concatLists' builtin
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:402:24:
          401|           collectResults = modules: {
          402|             disabled = concatLists (catAttrs "disabled" modules);
             |                        ^
          403|             inherit modules;

       … while evaluating a branch condition
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:413:25:
          412|             modules = collectedImports.modules;
          413|             disabled = (if module.disabledModules != [] then [{ file = module._file; disabled = module.disabledModules; }] else []) ++ collectedImports.disabled;
             |                         ^
          414|           }) initialModules);

       … from call site
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:407:22:
          406|           let
          407|             module = checkModule (loadModule args parentFile "${parentKey}:anon-${toString n}" x);
             |                      ^
          408|             collectedImports = collectStructuredModules module._file module.key module.imports args;

       … while calling anonymous lambda
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:366:11:
          365|         then
          366|           m:
             |           ^
          367|             if m._class != null -> m._class == class

       … while evaluating a branch condition
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:367:13:
          366|           m:
          367|             if m._class != null -> m._class == class
             |             ^
          368|             then m

       … in the left operand of the IMPL (->) operator
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:367:33:
          366|           m:
          367|             if m._class != null -> m._class == class
             |                                 ^
          368|             then m

       … from call site
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:407:35:
          406|           let
          407|             module = checkModule (loadModule args parentFile "${parentKey}:anon-${toString n}" x);
             |                                   ^
          408|             collectedImports = collectStructuredModules module._file module.key module.imports args;

       … while calling 'loadModule'
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:348:53:
          347|       # Like unifyModuleSyntax, but also imports paths and calls functions if necessary
          348|       loadModule = args: fallbackFile: fallbackKey: m:
             |                                                     ^
          349|         if isFunction m then

       … from call site
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:361:14:
          360|           throw "Module imports can't be nested lists. Perhaps you meant to remove one level of lists? Definitions: ${showDefs defs}"
          361|         else unifyModuleSyntax (toString m) (toString m) (applyModuleArgsIfFunction (toString m) (import m) args);
             |              ^
          362|

       … while calling 'unifyModuleSyntax'
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:461:34:
          460|      of ‘options’, ‘config’ and ‘imports’ attributes. */
          461|   unifyModuleSyntax = file: key: m:
             |                                  ^
          462|     let

       … while evaluating a branch condition
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:470:5:
          469|     in
          470|     if m ? config || m ? options then
             |     ^
          471|       let badAttrs = removeAttrs m ["_class" "_file" "key" "disabledModules" "imports" "options" "config" "meta" "freeformType"]; in

       … in the left operand of the OR (||) operator
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:470:19:
          469|     in
          470|     if m ? config || m ? options then
             |                   ^
          471|       let badAttrs = removeAttrs m ["_class" "_file" "key" "disabledModules" "imports" "options" "config" "meta" "freeformType"]; in

       … from call site
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:361:59:
          360|           throw "Module imports can't be nested lists. Perhaps you meant to remove one level of lists? Definitions: ${showDefs defs}"
          361|         else unifyModuleSyntax (toString m) (toString m) (applyModuleArgsIfFunction (toString m) (import m) args);
             |                                                           ^
          362|

       … while calling 'applyModuleArgsIfFunction'
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:495:39:
          494|
          495|   applyModuleArgsIfFunction = key: f: args@{ config, ... }:
             |                                       ^
          496|     if isFunction f then applyModuleArgs key f args else f;

       … from call site
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:496:26:
          495|   applyModuleArgsIfFunction = key: f: args@{ config, ... }:
          496|     if isFunction f then applyModuleArgs key f args else f;
             |                          ^
          497|

       … while calling 'applyModuleArgs'
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:498:29:
          497|
          498|   applyModuleArgs = key: f: args@{ config, ... }:
             |                             ^
          499|     let

       … from call site
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:522:8:
          521|       # works.
          522|     in f (args // extraArgs);
             |        ^
          523|

       … while calling anonymous lambda
         at /nix/store/pqs9cq39xy1hq05yalnh77qz8z503iib-source/nix/nixosModules/services/lnxlink.nix:1:1:
            1| {
             | ^
            2|   lib,

       … from call site
         at /nix/store/pqs9cq39xy1hq05yalnh77qz8z503iib-source/nix/nixosModules/services/lnxlink.nix:8:1:
            7|
            8| python3Packages.buildPythonApplication rec {
             | ^
            9|   pname = "lnxlink";

       … while calling anonymous lambda
         at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:513:35:
          512|       context = name: ''while evaluating the module argument `${name}' in "${key}":'';
          513|       extraArgs = mapAttrs (name: _:
             |                                   ^
          514|         addErrorContext (context name)

       … while evaluating the module argument `python3Packages' in "/nix/store/pqs9cq39xy1hq05yalnh77qz8z503iib-source/nix/nixosModules/services/lnxlink.nix":

       error: infinite recursion encountered
       at /nix/store/w17b5dshfd7jk4qmd94jzqp40il0x9cz-source/lib/modules.nix:515:28:
          514|         addErrorContext (context name)
          515|           (args.${name} or config._module.args.${name})
             |                            ^
          516|       ) (functionArgs f);

```

```
// lnxlink.nix
{
  lib,
  python3Packages,
  fetchPypi,
  ... // Added this to hinder an issue with Nix Flakes (error: function 'anonymous lambda' called with unexpected argument 'config')
}:
python3Packages.buildPythonApplication rec {
  pname = "lnxlink";
  version = "2024.8.1";
  pyproject = true;
  src = fetchPypi {
    inherit pname version;
    hash = "sha256-cEm+ha4oz5CGe9cqVKX8TAmY7y7GnqMnwVuuNx31EE4=";
  };
  postPatch = ''
    substituteInPlace pyproject.toml \
      --replace-fail "setuptools~=68.0.0" "setuptools" \
      --replace-fail "wheel~=0.40.0" "wheel"
  '';
  nativeBuildInputs = with python3Packages; [
    setuptools
    wheel
    wrapGAppsHook4 // Added according to comment
  ];
  propagatedBuildInputs = with python3Packages; [
    pyyaml
    distro
    inotify
    jc
    paho-mqtt
    psutil
    requests
    pygobject3
    speechrecognition
    dasbus
    ewmh
    mss
    numpy
    opencv4
    pulsectl
    xlib
  ];
  meta = with lib; {
    description = "Effortlessly manage your Linux machine using MQTT.";
    homepage = "https://github.com/bkbilly/lnxlink";
    license = licenses.mit;
  };
}
```

(The above file is importing into the configuration.nix with flakes)

---

What ever happened to that PR to add it to nixpkgs?

**Comment by KennethHoff** [comment]
Using more-or-less exclusively ChatGPT I was able to create this monster, and it seemingly works

```nix
{
  lib,
  config,
  pkgs,
  ...
}:
let
  cfg = config.lnxlink;
  python3Packages = pkgs.python3Packages;
  fetchPypi = pkgs.fetchPypi;
in
{
  # Options for the lnxlink module
  options.lnxlink = {
    enable = lib.mkEnableOption "Enable lnxlink (Effortlessly manage your Linux machine using MQTT)";
  };

  config = lib.mkIf cfg.enable {
    # Ensure the Python package is installed when lnxlink is enabled
    environment.systemPackages = [
      (python3Packages.buildPythonApplication rec {
        pname = "lnxlink";
        version = "2024.8.1";
        pyproject = true;

        src = fetchPypi {
          inherit pname version;
          hash = "sha256-cEm+ha4oz5CGe9cqVKX8TAmY7y7GnqMnwVuuNx31EE4=";
        };

        postPatch = ''
          substituteInPlace pyproject.toml \
            --replace-fail "setuptools~=68.0.0" "setuptools" \
            --replace-fail "wheel~=0.40.0" "wheel"
        '';

        nativeBuildInputs = [
          python3Packages.setuptools
          python3Packages.wheel
        ];

        propagatedBuildInputs = [
          python3Packages.pyyaml
          python3Packages.distro
          python3Packages.inotify
          python3Packages.jc
          python3Packages.paho-mqtt
          python3Packages.psutil
          python3Packages.requests
          python3Packages.pygobject3
          python3Packages.speechrecognition
          python3Packages.dasbus
          python3Packages.ewmh
          python3Packages.mss
          python3Packages.numpy
          python3Packages.opencv4
          python3Packages.pulsectl
          python3Packages.xlib
        ];

        meta = {
          description = "Effortlessly manage your Linux machine using MQTT.";
          homepage = "https://github.com/bkbilly/lnxlink";
          license = lib.licenses.mit;
        };
      })
    ];
  };
}

```

```
/home/kennethhoff/dotfiles/nix % lnxlink
usage: lnxlink [-h] [-c CONFIG] [-i] [-e EXCLUDE] [-l {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [-s] [-v]

LNXlink 2024.8.1 bridges this OS with Home Assistant through an MQTT broker.

options:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        Configuration file
  -i, --ignore-systemd  Runs without setting up SystemD service
  -e EXCLUDE, --exclude EXCLUDE
                        Exclude modules from running
  -l {DEBUG,INFO,WARNING,ERROR,CRITICAL}, --logging {DEBUG,INFO,WARNING,ERROR,CRITICAL}
                        Set the logging level
  -s, --setup           Runs only the setup configuration workflow
  -v, --version         Shows current version of LNXlink

Something went wrong, --config condition was not set
/home/kennethhoff/dotfiles/nix % lnxlink -v
2024.8.1

```

**Comment by pacjo** [comment]
I did get that working, but I didn't have time to upstream to nixpkgs. Those files are still laying somewhere.

If I'll remember I'll send them when I find some time.

**Comment by jjramsey** [comment]
> Try adding `wrapGAppsHook4` (or 3) to `nativeBuildInputs`.

Ok, that may work if building a Nix package of a Python app, but what to do if calling `dasbus` from a regular Python script?'

FYI, I've installed `dasbus` by adding
```nix
(python3.withPackages (python-pkgs: with python-pkgs; [
      numpy
      pandas
      pydbus
      dasbus
      pygobject3
      ]))
```
to `environment.systemPackages` in my configuration.nix.
