### ISSUE TITLE
safeeyes won't run under Python 3.12

### ISSUE THREAD

**Issue by jezcope** [NixOS/nixpkgs#334819]
### Describe the bug
[safeeyes](https://slgobinath.github.io/SafeEyes/) builds and installs, but fails at runtime due to missing `distutils`.

### Steps To Reproduce
1. `nix run nixpkgs#safeeyes`

```
Traceback (most recent call last):
  File "/nix/store/px8glnhmg21qisdk39r56lfgdh1qygx3-safeeyes-2.1.9/bin/.safeeyes-wrapped", line 6, in <module>
    from safeeyes.__main__ import main
  File "/nix/store/px8glnhmg21qisdk39r56lfgdh1qygx3-safeeyes-2.1.9/lib/python3.12/site-packages/safeeyes/__main__.py", line 32, in <module>
    from safeeyes import utility
  File "/nix/store/px8glnhmg21qisdk39r56lfgdh1qygx3-safeeyes-2.1.9/lib/python3.12/site-packages/safeeyes/utility.py", line 35, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

### Expected behavior
The app starts.

### Additional context
`distutils` has been deprecated for a while, and was removed in Python 3.12, so I assume this is caused by that: overriding to use `python311` works (`nix run --expr let pkgs = (builtins.getFlake "nixpkgs").legacyPackages.x86_64-linux; in pkgs.safeeyes.override {python3 = pkgs.python311;} --impure`). 

The recommended solution from https://github.com/slgobinath/SafeEyes/issues/574 is to install `setuptools`, which for Nix I guess means adding that to the dependencies.

### Notify maintainers

@srghma 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jezcope** [comment]
Oh, never mind, looks like this should be fixed by https://github.com/NixOS/nixpkgs/commit/b361684c722b0b78a1058e2492381eb22d2e147d.
