### ISSUE TITLE
leo-editor does not run

### ISSUE THREAD

**Issue by zeronobody0** [NixOS/nixpkgs#334923]
### Describe the bug
A config file is read-only, which causes the program to fail entirely.

### Steps To Reproduce
```console
~ > nix-shell -p leo-editor --run leo
fetching path input 'path:/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source'
setting leoID from os.getenv('USER'): 'axolotl'
read only: /nix/store/h6nlr03gfwicim9h8ychq67212lh44n1-leo-editor-6.7.8/share/leo-editor/leo/config/leoSettings.leo
/tmp/nix-shell-25713-0/rc: line 3: 28562 Segmentation fault      (core dumped) leo
```

### Expected behavior
The leo text editor should run when invoked.

### Notify maintainers

@leonardoce @kashw2

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
fetching path input 'path:/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.1, NixOS, 24.11 (Vicuna), 24.11.20240727.b73c222`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zeronobody0** [comment]
@leonardoce Not fixed:
```
~ > nix-shell -p leo-editor --run leo                                                                                                   
fetching path input 'path:/nix/store/d9gbq853jvbccrz5g3y0irbwgc57w137-source'
Error starting Leo!
Please verify you've installed the required dependencies:
https://leo-editor.github.io/leo-editor/installing.html
Please ask for help at https://groups.google.com/g/leo-editor

Traceback (most recent call last):
  File "/nix/store/2902wng4hilllppnkhl4vzq42anwsbn3-leo-editor-6.8.1/share/leo-editor/leo/core/runLeo.py", line 45, in <module>
    from leo.core import leoApp
  File "/nix/store/2902wng4hilllppnkhl4vzq42anwsbn3-leo-editor-6.8.1/share/leo-editor/leo/core/leoApp.py", line 21, in <module>
    from leo.core.leoQt import QCloseEvent
  File "/nix/store/2902wng4hilllppnkhl4vzq42anwsbn3-leo-editor-6.8.1/share/leo-editor/leo/core/leoQt.py", line 5, in <module>
    from PyQt6 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt6'
```

**Comment by kashw2** [comment]
@zeronobody0 this has been fixed on the master branch however has not been backported.

I'll create a PR to backport this, in the meantime if using flakes you can update nixpkgs to follow master or nixpkgs-unstable otherwise you can update your channel to follow unstable.

`nix run github:nixos/nixpkgs#leo-editor` works fine for me.

**Comment by zeronobody0** [comment]
@kashw2
> if using flakes you can update nixpkgs to follow master or nixpkgs-unstable
Are you sure?
```
/etc/nixos > nix flake update nixpkgs
warning: Git tree '/etc/nixos' is dirty
warning: updating lock file '/etc/nixos/flake.lock':
• Updated input 'nixpkgs':
    'github:NixOS/nixpkgs/8a3354191c0d7144db9756a74755672387b702ba' (2024-08-18)
  → 'github:NixOS/nixpkgs/c374d94f1536013ca8e92341b540eba4c22f9c62' (2024-08-21)
warning: Git tree '/etc/nixos' is dirty
/etc/nixos > doas nixos-rebuild test
warning: Git tree '/etc/nixos' is dirty
building the system configuration...
warning: Git tree '/etc/nixos' is dirty
stopping the following units: cpufreq.service
activating the configuration...
setting up /etc...
reloading user units for axolotl...
restarting sysinit-reactivation.target
reloading the following units: dbus.service
restarting the following units: home-manager-axolotl.service, polkit.service
starting the following units: cpufreq.service
/etc/nixos > leo
Error starting Leo!
Please verify you've installed the required dependencies:
https://leo-editor.github.io/leo-editor/installing.html
Please ask for help at https://groups.google.com/g/leo-editor

Traceback (most recent call last):
  File "/nix/store/2902wng4hilllppnkhl4vzq42anwsbn3-leo-editor-6.8.1/share/leo-editor/leo/core/runLeo.py", line 45, in <module>
    from leo.core import leoApp
  File "/nix/store/2902wng4hilllppnkhl4vzq42anwsbn3-leo-editor-6.8.1/share/leo-editor/leo/core/leoApp.py", line 21, in <module>
    from leo.core.leoQt import QCloseEvent
  File "/nix/store/2902wng4hilllppnkhl4vzq42anwsbn3-leo-editor-6.8.1/share/leo-editor/leo/core/leoQt.py", line 5, in <module>
    from PyQt6 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt6'
Exception: leo exited with 1
  [tty 7]:1:1-3: leo
```

Are you sure?

**Comment by kashw2** [comment]
![image](https://github.com/user-attachments/assets/f9f8237b-18c7-47cd-ae7c-eb091b432e1b)

**Comment by zeronobody0** [comment]
@kashw2 `nix run github:nixos/nixpkgs#leo-editor` works on my machine, which makes it extra strange that installing it locally with a flake that is pinned to `nixos-unstable` does not.
