### ISSUE TITLE
mermaid-cli not functional - possibly missing dependencies

### ISSUE THREAD

**Issue by ldesousa** [NixOS/nixpkgs#335148]
### Describe the bug

The executable mmdc, provided by the [mermaid-cli](https://search.nixos.org/packages?channel=24.05&show=mermaid-cli&from=0&size=50&sort=relevance&type=packages&query=mermaid) package, fails with an error.

### Steps To Reproduce
```
$ nix-shell -p mermaid-cli

$ mmdc

No input file specified, reading from stdin. If you want to specify an input file, please use `-i <input>.` You can use `-i -` to read from stdin and to suppress this warning.


Error: Failed to launch the browser process!
[0816/165219.308352:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /nix/store/brdqw7gxkaadq3144in040jiil0j0jg3-chromium-127.0.6533.88-sandbox/bin/__chromium-suid-sandbox is owned by root and has mode 4755.


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (file:///nix/store/h6l4bxd7pgmh0n7jdrp4kbbj7wcq2i4d-mermaid-cli-10.9.0/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/@puppeteer/browsers/lib/esm/launch.js:253:24)
    at ChildProcess.emit (node:events:531:35)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

### Expected behavior
The mmdc executable should not issue error messages.

### Additional context
The error message points to a troubleshooting page that indicates this error to be caused by missing dependencies.

### Notify maintainers

@javaes 

@ysndr 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/9j1f45904jshhlsmb9ljqaxdkg86ajl2-nix-info
copying path '/nix/store/9j1f45904jshhlsmb9ljqaxdkg86ajl2-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-40-generic, Ubuntu, 24.04 LTS (Noble Numbat), nobuild`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.2`
 - nixpkgs: `/home/lads/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by samueltardieu** [comment]
I cannot reproduce this.

**Comment by starptr** [comment]
I'm getting a slightly different error where it fails to find Chromium.
```
[nix-shell:~/.cache]$ mmdc

No input file specified, reading from stdin. If you want to specify an input file, please use `-i <input>.` You can use `-i -` to read from stdin and to suppress this warning.


Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /Users/yuto/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///nix/store/jga5fg35rzqpl2q3f288kqkngan0wqsa-mermaid-cli-10.9.0/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:263:27)
    at ChromeLauncher.executablePath (file:///nix/store/jga5fg35rzqpl2q3f288kqkngan0wqsa-mermaid-cli-10.9.0/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:176:25)
    at ChromeLauncher.computeLaunchArguments (file:///nix/store/jga5fg35rzqpl2q3f288kqkngan0wqsa-mermaid-cli-10.9.0/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:93:37)
    at async ChromeLauncher.launch (file:///nix/store/jga5fg35rzqpl2q3f288kqkngan0wqsa-mermaid-cli-10.9.0/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:57:28)
    at async run (file:///nix/store/jga5fg35rzqpl2q3f288kqkngan0wqsa-mermaid-cli-10.9.0/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:416:19)
    at async cli (file:///nix/store/jga5fg35rzqpl2q3f288kqkngan0wqsa-mermaid-cli-10.9.0/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:192:3)
```
I'm also finding it strange that my cache path is an impure directory. Is that expected? I don't have any Puppeteer configuration files going up the filesystem tree.

**Comment by msgilligan** [comment]
I'm seeing the same failure as @starptr. I'm on macOS 13 with nixos-unstable.

**Comment by MJWcodr** [comment]
seeing the same issue here with nixos-unstable

**Comment by dsully** [comment]
I'm seeing it on Darwin. This provides some insight: https://discourse.nixos.org/t/mermaid-cli-on-macos/45096

**Comment by tw-360vier** [comment]
As far as i can understand, it does not work on `aarch64-darwin` because chromium is not available on this platform.

It works when i provide my google-chrome binary manually:

```
PUPPETEER_EXECUTABLE_PATH=$(which google-chrome-stable) mmdc
```

I think it could be fixed by using the google-chrome package on `aarch64-darwin` instead of chromium, but that would make it unfree, wouldn't it?
