### ISSUE TITLE
warp-terminal crash after execution

### ISSUE THREAD

**Issue by midischwarz12** [NixOS/nixpkgs#336434]
### Describe the bug

Running the following provides the resulting errors:

```console
$ warp-terminal
/nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/h51pc1y5sdfcw5mqwdwivig1blj7dnb4-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp)
17:50:53 [INFO] Spawning terminal server process...
/nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/h51pc1y5sdfcw5mqwdwivig1blj7dnb4-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp)
thread 'main' panicked at /home/runner/work/warp-internal/warp-internal/ui/src/windowing/winit/app.rs:165:14:
should be able to create event loop: NotSupported(NotSupportedError)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
17:50:53 [INFO] Received empty message; assuming the connection has been closed.
```

```console
$ export RUST_BACKTRACE=1
$ warp-terminal
/nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/h51pc1y5sdfcw5mqwdwivig1blj7dnb4-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp)
/nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/h51pc1y5sdfcw5mqwdwivig1blj7dnb4-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp)
19:12:55 [INFO] Spawning terminal server process...
thread 'main' panicked at /home/runner/work/warp-internal/warp-internal/ui/src/windowing/winit/app.rs:165:14:
should be able to create event loop: NotSupported(NotSupportedError)
stack backtrace:
/nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/h51pc1y5sdfcw5mqwdwivig1blj7dnb4-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp)
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
19:12:55 [INFO] Received empty message; assuming the connection has been closed.
```

```console
$ export RUST_BACKTRACE=full
$ warp-terminal
/nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/h51pc1y5sdfcw5mqwdwivig1blj7dnb4-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp)
/nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/h51pc1y5sdfcw5mqwdwivig1blj7dnb4-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp)
19:13:25 [INFO] Spawning terminal server process...
thread 'main' panicked at /home/runner/work/warp-internal/warp-internal/ui/src/windowing/winit/app.rs:165:14:
should be able to create event loop: NotSupported(NotSupportedError)
stack backtrace:
/nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/h51pc1y5sdfcw5mqwdwivig1blj7dnb4-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/04pj7dp48i44w0pbkjjd4mz1al2is30h-warp-terminal-0.2024.07.09.08.01.stable_00/opt/warpdotdev/warp-terminal/warp)
   0:     0x5632414fce0b - <unknown>
   1:     0x563240c256d0 - <unknown>
   2:     0x5632414f8393 - <unknown>
   3:     0x5632414fcba4 - <unknown>
   4:     0x5632414ff120 - <unknown>
   5:     0x5632414fee3f - <unknown>
   6:     0x5632414ff63e - <unknown>
   7:     0x5632414ff542 - <unknown>
   8:     0x5632414fd306 - <unknown>
   9:     0x5632414ff2b0 - <unknown>
  10:     0x5632408ba825 - <unknown>
  11:     0x5632408bad73 - <unknown>
  12:     0x5632426abaae - <unknown>
  13:     0x563241c5431e - <unknown>
  14:     0x563241c53778 - <unknown>
  15:     0x5632414cfdd3 - <unknown>
  16:     0x5632414cfded - <unknown>
  17:     0x5632414eeb55 - <unknown>
  18:     0x5632414d047c - <unknown>
  19:     0x7f61844e810e - __libc_start_call_main
  20:     0x7f61844e81c9 - __libc_start_main@@GLIBC_2.34
  21:     0x563240a1824e - <unknown>
  22:                0x0 - <unknown>
19:13:25 [INFO] Received empty message; assuming the connection has been closed.
```

### Steps To Reproduce

1. `nix-shell -p warp-terminal` or whatever means to add the the package.
2. Run `warp-terminal`.

### Expected behavior

`warp-terminal` should run as expected without error.

### Additional context

Might be related to #332957

### Notify maintainers

- @emilytrau
- @Enzime
- @imadnyc
- @donteatoreo

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.42, NixOS, 24.05 (Uakari), 24.05.20240727.8c50662`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05, nixos-hardware"`
 - nixpkgs: `/nix/store/d6533m6b80n3c9lia5kvaz59ad3fynwk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DontEatOreo** [comment]
Is this still an issue?

**Comment by DontEatOreo** [comment]
Tested on version `v0.2025.03.26.08.10.stable_02` on Gnome 47, Kernel 6.12.20 on Wayland and everything works, let me know if this still occurs

**Comment by danielgafni** [comment]
`warp-terminal-v0.2025.05.07.08.12.stable_02-1` doesn't work on Wayland (Hyprland) for me: 

```shell
› WARP_ENABLE_WAYLAND=1 RUST_BACKTRACE=full warp-terminal
01:33:04 [INFO] Spawning terminal server process...

thread 'main' panicked at /home/runner/work/warp-internal/warp-internal/ui/src/windowing/winit/app.rs:169:14:
should be able to create event loop: Os(OsError { line: 81, file: "/home/runner/.cargo/git/checkouts/winit-c765dfcd1a6e8925/dce1fa3/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoWaylandLib)) })
stack backtrace:
   0:     0x562f669beec0 - <unknown>
   1:     0x562f65ea9cc3 - <unknown>
   2:     0x562f669b9b43 - <unknown>
   3:     0x562f669bed22 - <unknown>
   4:     0x562f669c0756 - <unknown>
   5:     0x562f669c05f0 - <unknown>
   6:     0x562f669c1162 - <unknown>
   7:     0x562f669c0f2a - <unknown>
   8:     0x562f669bf3a9 - <unknown>
   9:     0x562f669c0bcd - <unknown>
  10:     0x562f6597b0a0 - <unknown>
  11:     0x562f6597b4d6 - <unknown>
  12:     0x562f6817471d - <unknown>
  13:     0x562f67c7aeb5 - <unknown>
  14:     0x562f67c7a092 - <unknown>
  15:     0x562f6698aa23 - <unknown>
  16:     0x562f6698aa3d - <unknown>
  17:     0x562f669b07f1 - <unknown>
  18:     0x562f6698b2ec - <unknown>
  19:     0x7fd64902a47e - __libc_start_call_main
  20:     0x7fd64902a539 - __libc_start_main_impl
  21:     0x562f65ac5f2e - <unknown>
  22:                0x0 - <unknown>
01:33:04 [INFO] Received empty message; assuming the connection has been closed.
```

**Comment by ttimasdf** [comment]
I'm running a fork (openwarp 0.2026.05.13.1008) and see a similar crash.

The crashing version: https://github.com/ttimasdf/nixos-config/blob/c56efd0866f71d3a7f6ca50d69847bc5dc5de70f/packages/openwarp/default.nix

the interesting thing is, the crash did not happen before I update the version.

The old version that works well: https://github.com/ttimasdf/nixos-config/blob/7de83670151305092a2e609022ef91c8c4590854/packages/openwarp/default.nix
