### ISSUE TITLE
security.pam.usb seems to be broken on unstable

### ISSUE THREAD

**Issue by balsoft** [NixOS/nixpkgs#33699]
## Issue description

The usb pam module is broken (it requires udisks 1.0, which is not available on DBUS)

### Steps to reproduce

- Add `security.pam.usb.enable = true;` to configuration.nix;
- Rebuild the system;
- Try to run `# pamusb-conf --add-device=MyDev`
Get the following output:
```
Traceback (most recent call last):
  File "/nix/store/kn70lc5x66p0i407xd4i9cg3nn4368f5-pam_usb-0.5.0/bin/.pamusb-conf-wrapped", line 252, in <module>
    '/org/freedesktop/UDisks')
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files
```

- Add a line `services.dbus.packages = [ pkgs.udisks ];`
- Rebuild the system;
- Try to run `# pamusb-conf --add-device=MyDev`
Get the following output:
```
Traceback (most recent call last):
  File "/nix/store/kn70lc5x66p0i407xd4i9cg3nn4368f5-pam_usb-0.5.0/bin/.pamusb-conf-wrapped", line 252, in <module>
    '/org/freedesktop/UDisks')
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/nix/store/s5ra7c0w9f8pfbw0mpxzxc6zb11ksqm2-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.UDisks': timed out

```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.10, NixOS, 18.03pre124015.f59a0f7f1a6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre124015.f59a0f7f1a6"`
 - channels(balsoft): `"nixpkgs-18.03pre124015.f59a0f7f1a6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

- My config (long & dirty): https://gist.github.com/balsoft/43b00a0de43ca602ef71ac71114bc642

**Comment by stefano-m** [comment]
@balsoft [pam_usb](https://github.com/aluzzardi/pam_usb) seems to be unmaintained. The GitHub and SourceForge pages seem to have no activity since 2015.

It may be worth considering to deprecate and then remove the module.


Cc
@fpletz @grahamc of the NixOS security group (since this may be a security issue too)

**Comment by j0hax** [comment]
Coincidentally ran into this issue today.

+1 for removing the package or marking it as broken.
