### ISSUE TITLE
plots: GLSL 3.30 is not supported

### ISSUE THREAD

**Issue by MichaelBrunn3r** [NixOS/nixpkgs#336981]
### Describe the bug
`plots` crashes upon startup with the error (it's massive, here is the relevant bit):
```sh
> plots
OpenGL ES version: 3.2
Traceback (most recent call last):
  File "/nix/store/zjl19r0hwarxcz7ijw4i5i3nand7a8d4-plots-0.8.5/lib/python3.11/site-packages/plots/plots.py", line 227, in update_shader
    attempt(good + bad + unknown)
  File "/nix/store/zjl19r0hwarxcz7ijw4i5i3nand7a8d4-plots-0.8.5/lib/python3.11/site-packages/plots/plots.py", line 222, in attempt
    self.gl_area.update_fragment_shader(formulae)
  File "/nix/store/zjl19r0hwarxcz7ijw4i5i3nand7a8d4-plots-0.8.5/lib/python3.11/site-packages/plots/graph.py", line 293, in update_fragment_shader
    self.shader = shaders.compileProgram(self.vertex_shader, fragment_shader)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/grp6vpyzra48garak7hwzzhm5bh3qif3-python3.11-pyopengl-3.1.7/lib/python3.11/site-packages/OpenGL/GL/shaders.py", line 211, in compileProgram
    program.check_validate()
  File "/nix/store/grp6vpyzra48garak7hwzzhm5bh3qif3-python3.11-pyopengl-3.1.7/lib/python3.11/site-packages/OpenGL/GL/shaders.py", line 109, in check_validate
    raise ShaderValidationError(
OpenGL.GL.shaders.ShaderValidationError: Validation failure (0):
...
```

### Steps To Reproduce
- Install `plots` from `24.05` or `unstable` channel
- Execute: `> plots`

### Expected behavior
Launch the `plots` App.

### Additional context
The project repo of `plots` already has a workardound (https://github.com/alexhuntley/Plots/issues/151):
```sh
> GDK_DEBUG=gl-prefer-gl plots
```

### Notify maintainers
@sund3RRR

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.5, NixOS, 24.05 (Uakari), 24.05.20240819.f1bad50`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/1lwg74im5q4fmdk3zf5az570kixzk3vb-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sund3RRR** [comment]
idk what can I do with this issue. This is a dependency error with OpenGL.

**Comment by MichaelBrunn3r** [comment]
I thought as a hotfix there might be a possibility to wrap the binary with an environment that has that environment variable set. I'm not an expert on derivations, don't know if that's possible.
Otherwise, this should be fixed in the next release of `plots` as the developers are already aware of it
