### ISSUE TITLE
Pipenv doesn't propagate packages like pip

### ISSUE THREAD

**Issue by sid-kap** [NixOS/nixpkgs#33713]
## Issue description

I'm trying to install numpy using pipenv (rather than using the nix package), and I'm getting the following error: 

```
Creating a Pipfile for this project…
Installing numpy…
⠧
Error:  An error occurred while installing numpy!
/bin/sh: /bin/pip: No such file or directory
```

Full stack trace:
```
Creating a virtualenv for this project…
⠋Using base prefix '/nix/store/y95dd7cmw2xlf6hvg2j93b227pblpaaq-python3-3.6.4'
New python executable in /home/sidharth/.local/share/virtualenvs/numpy-test-s0o2G1-0/bin/python3.6m
Also creating executable in /home/sidharth/.local/share/virtualenvs/numpy-test-s0o2G1-0/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/sidharth/.loca...2G1-0/bin/python3.6m - setuptools pip wheel:       
  Collecting setuptools                                                                                  
Exception:                                                                                               
Traceback (most recent call last):                                                                       
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 215, in main              
    status = self.run(options, args)                                                                     
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/commands/install.py", line 324, in run          
    requirement_set.prepare_files(finder)                                                                
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py", line 380, in prepare_files     
    ignore_dependencies=self.ignore_dependencies))                                                       
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py", line 620, in _prepare_file     
    session=self.session, hashes=hashes)                                                                 
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 821, in unpack_url           
    hashes=hashes                                                                                        
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 659, in unpack_http_url      
    hashes)                                                                                              
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 853, in _download_http_url   
    stream=True,                                                                                         
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 488, in get 
    return self.request('GET', url, **kwargs)                                                            
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 386, in request              
    return super(PipSession, self).request(method, url, *args, **kwargs)                                 
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 475, in request                                                                                                      
    resp = self.send(prep, **send_kwargs)                                                                
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)                                                                  
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/cachecontrol/adapter.py", line 37, in send                                                                                                       
    cached_response = self.controller.cached_request(request)                                            
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/cachecontrol/controller.py", line 111, in cached_request                                                                                         
    resp = self.serializer.loads(request, cache_data)                                                    
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/cachecontrol/serialize.py", line 114, in loads                                                                                                   
    return getattr(self, "_loads_v{0}".format(ver))(request, data)                                       
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/cachecontrol/serialize.py", line 176, in _loads_v2                                                                                               
    cached = json.loads(zlib.decompress(data).decode("utf8"))                                            
zlib.error: Error -3 while decompressing data: incorrect data check                                      
----------------------------------------                                                                 
...Installing setuptools, pip, wheel...done.                                                             
Traceback (most recent call last):                                                                       
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/bin/.virtualenv-wrapped", line 12, in <module>                                                                                    
    sys.exit(main())                                                                                     
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/nix/store/ivhiacy4kzk3pn0rkzm8v6358xrdmbaz-python3.6-virtualenv-15.1.0/lib/python3.6/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/sidharth/.loca...2G1-0/bin/python3.6m - setuptools pip wheel failed with error code 2
```

### Steps to reproduce

```
nix-shell -p pipenv
pipenv install numpy
```

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.9.73, NixOS, 18.03pre124015.f59a0f7f1a6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(sidharth): `""`
 - channels(root): `"nixos-18.03pre124015.f59a0f7f1a6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by sid-kap** [comment]
@das-g I don't think I got that error! Anyway, I figured out how to make pipenv install wheels instead of building from source, which solved all my problems and also makes installing packages much faster.
I wrote a blog post on how to do this: https://sid-kap.github.io/posts/2018-03-08-nix-pipenv.html.

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixpkgs/pull/38655#issuecomment-398814646

**Comment by sid-kap** [comment]
@domenkozar thanks for the update! I've been pretty happy with my FHS env setup, but I'll try in a normal nix-shell to see if the new version fixes the problems I was having.

**Comment by baracoder** [comment]
@sid-kap do you have any updates on this issue?

**Comment by sid-kap** [comment]
@baracoder I don't have this problem anymore

**Comment by danbst** [comment]
then let's mark this resolved!
