### ISSUE TITLE
JavaFX can not find glassgtk3

### ISSUE THREAD

**Issue by Kiyotoko** [NixOS/nixpkgs#338165]
### Describe the bug
The JavaFX application can not find the glassgtk3 library.

### Steps To Reproduce
1. `git clone https://github.com/Kiyotoko/dionysius.git`
2. `mvn compile exec:java`

### Expected behavior
The JavaFX application should find the library, as it is located at exect the location it is searching for. For more, look at [Additional context](#Additional-context).

### Stacktrace

```java
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /home/karlz/.openjfx/cache/19+11/amd64/libprism_es2.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/MyUserName/.openjfx/cache/19+11/amd64/libprism_es2.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
        at java.base/java.lang.Runtime.load0(Runtime.java:852)
        at java.base/java.lang.System.load(System.java:2025)
        at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
        at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:421)
        at java.base/java.lang.Class.forName(Class.java:412)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Loading library glassgtk3 from resource failed: java.lang.UnsatisfiedLinkError: /home/MyUserName/.openjfx/cache/19+11/amd64/libglassgtk3.so: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/MyUserName/.openjfx/cache/19+11/amd64/libglassgtk3.so: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
        at java.base/java.lang.Runtime.load0(Runtime.java:852)
        at java.base/java.lang.System.load(System.java:2025)
        at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:221)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:200)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1583)
[WARNING] 
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
    at com.sun.javafx.tk.quantum.QuantumToolkit.startup (QuantumToolkit.java:300)
    at com.sun.javafx.application.PlatformImpl.startup (PlatformImpl.java:293)
    at com.sun.javafx.application.PlatformImpl.startup (PlatformImpl.java:163)
    at com.sun.javafx.application.LauncherImpl.startToolkit (LauncherImpl.java:659)
    at com.sun.javafx.application.LauncherImpl.launchApplication1 (LauncherImpl.java:679)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2 (LauncherImpl.java:196)
    at java.lang.Thread.run (Thread.java:1583)
Caused by: java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
    at java.lang.ClassLoader.loadLibrary (ClassLoader.java:2458)
    at java.lang.Runtime.loadLibrary0 (Runtime.java:916)
    at java.lang.System.loadLibrary (System.java:2063)
    at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal (NativeLibLoader.java:166)
    at com.sun.glass.utils.NativeLibLoader.loadLibrary (NativeLibLoader.java:54)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6 (GtkApplication.java:221)
    at java.security.AccessController.doPrivileged (AccessController.java:319)
    at com.sun.glass.ui.gtk.GtkApplication.<init> (GtkApplication.java:200)
    at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication (GtkPlatformFactory.java:41)
    at com.sun.glass.ui.Application.run (Application.java:146)
    at com.sun.javafx.tk.quantum.QuantumToolkit.startup (QuantumToolkit.java:290)
    at com.sun.javafx.application.PlatformImpl.startup (PlatformImpl.java:293)
    at com.sun.javafx.application.PlatformImpl.startup (PlatformImpl.java:163)
    at com.sun.javafx.application.LauncherImpl.startToolkit (LauncherImpl.java:659)
    at com.sun.javafx.application.LauncherImpl.launchApplication1 (LauncherImpl.java:679)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2 (LauncherImpl.java:196)
    at java.lang.Thread.run (Thread.java:1583)
```

### Additional context

I have the following nix packages installed:

```nix
maven
openjdk
javaPackages.openjfx11
gtk3
libGL
```

If I run the folliwing commands,

```
cd /home/MyUserName/.openjfx
tree
```

I get the following output:

```
.
└── cache
    └── 19+11
        └── amd64
            ├── libglassgtk3.so
            ├── libglass.so
            ├── libprism_es2.so
            └── libprism_sw.so
```

I already tried to use the oracle and jetbrains jdks, as described in #50418, however it did not change anything,

If this does matter, I have a separate home partition.

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.47, NixOS, 24.11 (Vicuna), 24.11.20240821.c374d94`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/j8pbrsb3nybdap3hhg9kw0ffqd4rlbx6-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by leana8959** [comment]
I had the same problem and I managed to make it work, here's my devshell.
https://github.com/leana8959/.files/blob/68e8298ffd6c6173812fa2bcc80bd5b6e1cfd81b/nix/devShells/default.nix#L8-L16

Hope this helps ^^

source: [discord thread](https://discord.com/channels/568306982717751326/1269736687387414642/1269737767169032299)

**Comment by GHOSCHT** [comment]
In my case it was enough to edit the LD_LIBRARY_PATH.
```
LD_LIBRARY_PATH = "${pkgs.libGL}/lib:${pkgs.gtk3}/lib:${pkgs.glib.out}/lib:${pkgs.xorg.libXtst}/lib";
```
I think libXtst would probably be enough to add, but I left the others there for compatibility/laziness reasons.
source: [some random blog I found](https://thangqt.com/notes/nixos/javafx)

**Comment by Frontear** [comment]
`javaPackages.openjfx11` is not even a package anymore, at least on current master, so I cannot begin to reproduce this. Furthermore, it seems what you wanted to do was use a `jdk` derivation with `.overrideAttrs { withJavaFX = true; }` instead of whatever you're currently doing.

I'm also not quite sure what you're trying to do. It seems you're trying to compile some software? It's usually expected that software fails to link without the appropriate environment setup, either in a devshell or via a derivation. I'm not particularly sure where JavaFX played a part in causing things to fail.

**Comment by Kiyotoko** [comment]
The issue was that the native libraries were not linked correctly because of a false environment setup. I resolved this by simply NOT doing this with nix. The problem with nix here is, that the library installs files to the user folder. But when a program which was installed in the nix store is called, it can not properly resolve the path. I tried using a different jdk (in fact, multiple ones with many different attributes), but as expected, this changed nothing. Editing the library path as proposed by @GHOSCHT could fix this issue, but could potentially create new issues with other projects, because the native libraries that were downloaded from the maven library are not the same as the nix packages. In fact, using SDKMAN partly resolved this issue, but not because it fixed the issues with nix, instead it completely bypassed nix. I have currently solved the problem for myself, even if the solution is rather unattractive, so I am closing the issue. If I find a better solution, I will post it here. And again: simply installing a different jdk did not resolve anything for me, as this issue is not related to the jdk!

**Comment by Kiyotoko** [comment]
> Was anyone able to find a solution? I have just encountered this...

For me personally, the best solution was something inspired by @leana8959 by adding this to my nix shell build inputs:

```nix
buildInputs = [
    (pkgs.jdk17.override { enableJavaFX = true; })
  ];
```

This works because it directly includes JavaFX into the JDK. I have used and tested JDK 17, but I think you should be able to use any other version.

Again, this does not fix the underlying issue that Java can not find the libraries in your home directory. Instead, it directly includes the libraries into your JDK and  uses them.

**Comment by Kiyotoko** [comment]
> Sorry, I forgot to comment I managed to fix this by doing the following in my devshell:
> 
> ```nix
> {pkgs, ...}:
> pkgs.mkShell {
>   buildInputs = with pkgs; [
>     javaPackages.openjfx21
>     libglibutil
>     xorg.libXxf86vm
>     glibc
>     glib
>     gsettings-desktop-schemas
>     (pkgs.jdk21.override {enableJavaFX = true;})
>   ];
>   GSETTINGS_SCHEMA_DIR = "${pkgs.gtk3}/share/gsettings-schemas/${pkgs.gtk3.name}/glib-2.0/schemas";
> }
> ```

Thanks for sharing your solution!

**Comment by SimonBrandner** [comment]
No problem :)
