### ISSUE TITLE
DVC: No module named 'google.auth'

### ISSUE THREAD

**Issue by akesson** [NixOS/nixpkgs#338146]
### Describe the bug
After adding 
```nix
buildInputs = [
   (dvc.override { enableGoogle = true; })
   # ... 
]
```

to my `flake.nix` and loading it with `nix develop` 

it works fine, except for:
`dvc push` which returns with:
> unexpected error - No module named 'google.auth'

### Steps To Reproduce
See above

### Expected behavior
It should be able to load the google.auth module (well, it should work...)

### Additional context

I don't know much about Nix, but from what I can see [dvc-gs](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/python-modules/dvc-gs/default.nix) uses [gcsfs](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/python-modules/gcsfs/default.nix) which uses google-auth.

What stands out to me is that **gcsfs** sets `propagatedBuildInputs` to include `google-auth` and **dvc-gs** set it to include `gcsfs` but **dvc** doesn't set it at all. I don't know if that is important or not...

<details><summary>Output of dvc push -v</summary>
<pre>
024-08-29 11:32:00,539 DEBUG: v3.54.1, CPython 3.12.4 on macOS-14.6.1-arm64-arm-64bit
2024-08-29 11:32:00,539 DEBUG: command: /nix/store/x8hrn3qa32v37wn7jg4b7lzbh3d4q2n7-python3.12-dvc-3.54.1/bin/dvc push -v
2024-08-29 11:32:01,302 ERROR: unexpected error - No module named 'google.auth'
Traceback (most recent call last):
  File "/nix/store/x8hrn3qa32v37wn7jg4b7lzbh3d4q2n7-python3.12-dvc-3.54.1/lib/python3.12/site-packages/dvc/cli/__init__.py", line 211, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "/nix/store/x8hrn3qa32v37wn7jg4b7lzbh3d4q2n7-python3.12-dvc-3.54.1/lib/python3.12/site-packages/dvc/cli/command.py", line 27, in do_run
    return self.run()
           ^^^^^^^^^^
  File "/nix/store/x8hrn3qa32v37wn7jg4b7lzbh3d4q2n7-python3.12-dvc-3.54.1/lib/python3.12/site-packages/dvc/commands/data_sync.py", line 64, in run
    processed_files_count = self.repo.push(
                            ^^^^^^^^^^^^^^^
  File "/nix/store/x8hrn3qa32v37wn7jg4b7lzbh3d4q2n7-python3.12-dvc-3.54.1/lib/python3.12/site-packages/dvc/repo/__init__.py", line 58, in wrapper
    return f(repo, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/x8hrn3qa32v37wn7jg4b7lzbh3d4q2n7-python3.12-dvc-3.54.1/lib/python3.12/site-packages/dvc/repo/push.py", line 92, in push
    _remote = self.cloud.get_remote(name=remote)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/x8hrn3qa32v37wn7jg4b7lzbh3d4q2n7-python3.12-dvc-3.54.1/lib/python3.12/site-packages/dvc/data_cloud.py", line 92, in get_remote
    cls, config, fs_path = get_cloud_fs(self.repo.config, name=name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/x8hrn3qa32v37wn7jg4b7lzbh3d4q2n7-python3.12-dvc-3.54.1/lib/python3.12/site-packages/dvc/fs/__init__.py", line 167, in get_cloud_fs
    extras = cls._get_kwargs_from_urls(url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/azq2r0n0bri6b44an6zb7bfil05msybf-python3.12-dvc-gs-3.0.1/lib/python3.12/site-packages/dvc_gs/__init__.py", line 90, in _get_kwargs_from_urls
    from gcsfs import GCSFileSystem
  File "/nix/store/dfa0mv20v9i7a4vqbr5mljyf32li15ps-python3.12-gcsfs-2024.2.0/lib/python3.12/site-packages/gcsfs/__init__.py", line 5, in <module>
    from .core import GCSFileSystem
  File "/nix/store/dfa0mv20v9i7a4vqbr5mljyf32li15ps-python3.12-gcsfs-2024.2.0/lib/python3.12/site-packages/gcsfs/core.py", line 25, in <module>
    from .checkers import get_consistency_checker
  File "/nix/store/dfa0mv20v9i7a4vqbr5mljyf32li15ps-python3.12-gcsfs-2024.2.0/lib/python3.12/site-packages/gcsfs/checkers.py", line 6, in <module>
    from .retry import ChecksumError
  File "/nix/store/dfa0mv20v9i7a4vqbr5mljyf32li15ps-python3.12-gcsfs-2024.2.0/lib/python3.12/site-packages/gcsfs/retry.py", line 7, in <module>
    import google.auth.exceptions
ModuleNotFoundError: No module named 'google.auth'

2024-08-29 11:32:01,328 DEBUG: Version info for developers:
DVC version: 3.54.1
-------------------
Platform: Python 3.12.4 on macOS-14.6.1-arm64-arm-64bit
Subprojects:
        dvc_data = 3.16.5
        dvc_objects = 5.1.0
        dvc_render = 1.0.2
        dvc_task = 0.4.0
        scmrepo = 3.3.7
Supports:
        gs (gcsfs = 2024.2.0),
        http (aiohttp = 3.10.2, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.10.2, aiohttp-retry = 2.8.3)
Config:
        Global: /Users/hakesson/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: gs
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/0c097259c25324814e8f324c880871d4

</pre>
</details> 

### Notify maintainers

@fabaff @CMCDragonkai 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.23.3`
 - nixpkgs: `/nix/store/h1v7aq3k9wy0i5l53cirm7kka7fsipji-source`
 
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by cameronraysmith** [comment]
I get the same issue and it also occurs with `dvc pull`. Adding `google-auth`directly to the dvc `propagatedBuildInputs` via override with something like

```nix
  dvcWithOptionalRemotes = pkgs.dvc.override {
    enableGoogle = true;
  };

  dvcWithGoogleAuth = dvcWithOptionalRemotes.overrideAttrs (oldAttrs: {
    propagatedBuildInputs = oldAttrs.propagatedBuildInputs ++ [
      pkgs.python3Packages.google-auth
      pkgs.python3Packages.google-auth-oauthlib
    ];
  });
```

does not seem to resove it either.

Maybe one of the maintainers of dvc-gs ( @melling  ) 
https://github.com/NixOS/nixpkgs/blob/6e282518d2a7a44be706b67c176d31a655f88c7a/pkgs/development/python-modules/dvc-gs/default.nix#L45
or gcsfs ( @nbren12 ) 
https://github.com/NixOS/nixpkgs/blob/6e282518d2a7a44be706b67c176d31a655f88c7a/pkgs/development/python-modules/gcsfs/default.nix#L77
in addition to the dvc maintainers have some idea of how to fix it.

**Comment by cameronraysmith** [comment]
The same error still arises even if you manually override both the python dependencies and the buildInputs of the top-level dvc package that should be receiving the transitively propagated build inputs from both gcsfs and dvc-gs

```nix
  dvcPackage = pkgs.python312Packages.dvc;
  dvcWithGoogleAuth = (dvcPackage.overrideAttrs (oldAttrs: {
    buildInputs = oldAttrs.buildInputs ++ (with pkgs.python312Packages; [
      dvc-gs
      gcsfs
      dvc-objects
      aiohttp
      crcmod
      decorator
      fsspec
      google-auth
      google-auth-oauthlib
      google-cloud-storage
      requests
      ujson
    ]);
  })).overridePythonAttrs (oldAttrs: {
    dependencies = oldAttrs.dependencies ++ (with pkgs.python312Packages; [
      dvc-gs
      gcsfs
      dvc-objects
      aiohttp
      crcmod
      decorator
      fsspec
      google-auth
      google-auth-oauthlib
      google-cloud-storage
      requests
      ujson
    ]);
    pythonImportsCheck = [
      "dvc"
      "dvc.api"
      "dvc_gs"
      "google.auth"
    ];
  });
```

even though the additional import checks for `dvc_gs` and `google.auth` pass during the build. That is to say the runtime error `ModuleNotFoundError: No module named 'google.auth'` still arises.

I note, in contrast to using via a flake-managed devShell above, when installing dvc with `enableGoogle = true` via home-manager

```
  dvcWithOptionalRemotes = pkgs.dvc.override {
    enableGoogle = true;
  };
```

the program works as expected.

**Comment by cameronraysmith** [comment]
@NickCao @fabaff, not suggesting you should be responsible to fix it, but just noting this issue persists following #382322 #373441

**Comment by cameronraysmith** [comment]
The resulting

<details><summary>propagated build inputs from devshell-installed dvc with `enableGoogle = true`</summary>
<p>

```sh
❯ which dvc
/nix/store/h4hb3pdl007hbwsg0n9ci5qnjx128qra-python3.12-dvc-3.59.1/bin/dvc

❯ readlink -f /nix/store/h4hb3pdl007hbwsg0n9ci5qnjx128qra-python3.12-dvc-3.59.1/bin/dvc                                    
/nix/store/h4hb3pdl007hbwsg0n9ci5qnjx128qra-python3.12-dvc-3.59.1/bin/dvc

❯ cat /nix/store/h4hb3pdl007hbwsg0n9ci5qnjx128qra-python3.12-dvc-3.59.1/nix-support/propagated-build-inputs | 
  tr ' ' '\n' |
  bat
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ /nix/store/83wbzf7nma45dlvai2rhj0942y6w5hq1-python3.12-appdirs-1.4.4
   2   │ /nix/store/bn2gr8j5x14fabs1ryfq3skl4lx5rg7m-python3.12-colorama-0.4.6
   3   │ /nix/store/2vc2l8mi18gwidnhgdii8jjwa858rwh7-python3.12-configobj-5.0.9
   4   │ /nix/store/gqfs276aq8r9558l16jyndlpakcldrl7-python3.12-distro-1.9.0
   5   │ /nix/store/8hn4d7h3hwqqh4qgkh902mbhyn1hgdlg-python3.12-dpath-2.2.0
   6   │ /nix/store/fkpiymjjnhg41y9qspf9vkf7vzmvbbqc-python3.12-dvc-data-3.16.9
   7   │ /nix/store/ncl0p3220gi1s071q0yijap8ckxipka1-python3.12-dvc-http-2.32.0
   8   │ /nix/store/nsjyqn2b2ngcqvcrj6s1g5rhfwp4ijhp-python3.12-dvc-render-1.0.2
   9   │ /nix/store/g7szjcylxy4rxa26fj52a5a5jrh9p0z7-python3.12-dvc-studio-client-0.21.0
  10   │ /nix/store/1a03l3phciaqjyxqjfahgfz3snz0yim4-python3.12-dvc-task-0.40.2
  11   │ /nix/store/kz5j6zbqhgsxilxa7ah58jjiqcggh242-python3.12-flatten-dict-0.4.2
  12   │ /nix/store/a8w30zcxzhdn1nf1ip8kwyswgl17845h-python3.12-flufl-lock-8.1.0
  13   │ /nix/store/mbb6y291s4fklpc7qiqxs87pgg9632hm-python3.12-funcy-2.0
  14   │ /nix/store/gc0arrd2dbi3zip0pjcj37dqgp7zmdcg-python3.12-grandalf-0.7
  15   │ /nix/store/dspib7fv4wql2yr2k5skhlr42mhx7g64-python3.12-gto-1.7.2
  16   │ /nix/store/s29mz8y6l1i8jk0b1gcy09pypsclzvbf-python3.12-hydra-core-1.3.2
  17   │ /nix/store/fk36aw4339p1v1gmqh0b49ffdncsl76m-python3.12-iterative-telemtry-0.0.10
  18   │ /nix/store/15xb808wj0fcb7m55kzqc8jafyg6c90q-python3.12-networkx-3.4.2
  19   │ /nix/store/m91wfh65qw1675pwxbrqmlaz03qxqzhc-python3.12-packaging-24.2
  20   │ /nix/store/41j9vn7vd94nvs2lrapagxww4p56wyvg-python3.12-pathspec-0.12.1
  21   │ /nix/store/pmp8nahy0i342akqm5slffkrv99ajlv4-python3.12-platformdirs-4.3.6
  22   │ /nix/store/w510y8mmq32y9lxvrzmw7pmyd3navyyz-python3.12-psutil-6.1.1
  23   │ /nix/store/7hp0ngvnhwknkp1fwkah21xr76fjxp5c-python3.12-pydot-3.0.4
  24   │ /nix/store/b11cacgfqivnkj5lpa6hjb00aazp0b0m-python3.12-pygtrie-2.5.0
  25   │ /nix/store/2ja4x3bnf7mb11by1ks9khazqyy8gkf6-python3.12-pyparsing-3.2.1
  26   │ /nix/store/jlg6w336v198mj252p29qfikiby71pbm-python3.12-requests-2.32.3
  27   │ /nix/store/abm4pvc09npi4cilw1748mrfcb7cih4v-python3.12-rich-13.9.4
  28   │ /nix/store/sg6dl02a0fs2q4wyd1blgqds8rr8wzc8-python3.12-ruamel-yaml-0.18.10
  29   │ /nix/store/xlcxx6pxkpzqhc4pjhwshl1wls5lj8gd-python3.12-scmrepo-3.3.10
  30   │ /nix/store/qdaj8r8ild2n3byfpqky1ziy23x6437l-python3.12-shortuuid-1.0.13
  31   │ /nix/store/70gz4p3ll6hl6bzzcdcpr60bzdfr3681-python3.12-shtab-1.7.1
  32   │ /nix/store/inl71gg2r96w0q84gzkx56j6qdhh26d0-python3.12-tabulate-0.9.0
  33   │ /nix/store/hzjawvjm97fxk6y0x3mar2w8f37gv1m7-python3.12-tomlkit-0.13.2
  34   │ /nix/store/axcqfwiz46wgqwiym61sip7ci8c2d9nx-python3.12-tqdm-4.67.1
  35   │ /nix/store/wc32q4p3qqiq9fh1q6rs32zznadnja67-python3.12-typing-extensions-4.12.2
  36   │ /nix/store/sdaaa6v4v9bxsjrhm4f7vk34hw4gkvi0-python3.12-voluptuous-0.15.2
  37   │ /nix/store/d7b8qng4ckn874akagabb9asybdxyjp5-python3.12-zc-lockfile-3.0.post1
  38   │ /nix/store/160y1psk4b6m4s17yvkgagawgb399azy-python3.12-dvc-gs-3.0.1
  39   │ /nix/store/ps62pllxa4g0l48miwkcwdxmpjqcxfdz-python3.12-dvc-s3-3.2.0
  40   │ /nix/store/j9fqllydmrjv0rl3cb7h2hgm81l4ilcs-python3.12-dvc-azure-3.1.0
  41   │ /nix/store/n7v1fz2lw8rmc5rv0frl78ya78az706x-python3.12-dvc-ssh-4.1.1
  42   │ /nix/store/wwqdmdr2f5wrjnsjs64bny8df471rh9b-python3-3.12.9
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

❮ cat /nix/store/160y1psk4b6m4s17yvkgagawgb399azy-python3.12-dvc-gs-3.0.1/nix-support/propagated-build-inputs |
  tr ' ' '\n' |
  bat
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ /nix/store/ra5c38yc5ibw7b5m7vhais5kzmp5xr5m-python3.12-gcsfs-2024.2.0
   2   │ /nix/store/n2ydzfaizwchpsx6i00y4q1a2l3b3m62-python3.12-dvc-objects-5.1.0
   3   │ /nix/store/wwqdmdr2f5wrjnsjs64bny8df471rh9b-python3-3.12.9
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

❮ cat /nix/store/ra5c38yc5ibw7b5m7vhais5kzmp5xr5m-python3.12-gcsfs-2024.2.0/nix-support/propagated-build-inputs |
  tr ' ' '\n' |
  bat
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ /nix/store/n8pf0ffsnnxm3janwy5r8qc88zzic0an-python3.12-aiohttp-3.11.12
   2   │ /nix/store/pr8lhvc06jmprakbmk5sdh8bp20hfd1y-python3.12-crcmod-1.7
   3   │ /nix/store/wsv2wcs5pkq5b0984wh3fvg0wwgbfwj1-python3.12-decorator-5.1.1
   4   │ /nix/store/xypj5nzr10p6163s7fmqyzijvdfx8ya2-python3.12-fsspec-2024.12.0
   5   │ /nix/store/6mi8qzcprhcf2yhn8rm18bz6f1krarxw-python3.12-google-auth-2.37.0
   6   │ /nix/store/szrp0w85wgs0syhwf3lqsq266xky9ymg-python3.12-google-auth-oauthlib-1.2.1
   7   │ /nix/store/89v9zrb0cbsjy427mhln7l5kkdr2qlni-python3.12-google-cloud-storage-2.19.0
   8   │ /nix/store/jlg6w336v198mj252p29qfikiby71pbm-python3.12-requests-2.32.3
   9   │ /nix/store/kk932j6bvpzfbacyd3vkj5swfk0bqk8l-python3.12-ujson-5.10.0
  10   │ /nix/store/wwqdmdr2f5wrjnsjs64bny8df471rh9b-python3-3.12.9
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

</p>
</details> 

seem to be correct.
