### ISSUE TITLE
Build failure: `teams-for-linux`

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#338394]
### Steps To Reproduce

1. allow insecure package `electron-29.4.6`
2. build `teams-for-linux`

### Build log

```
error: builder for '/nix/store/w6npgp9zxljdgfpi2wr9p9z5lvb90fbs-teams-for-linux-1.4.27.drv' failed with exit code 1;
       last 25 log lines:
       > node_modules/yarn/bin/yarnpkg: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/v14k93caffbf0xz2g7bqr964grxxqlmj-nodejs-20.15.1/bin/node"
       > node_modules/yarn/bin/yarn: interpreter directive changed from "#!/bin/sh" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/sh"
       > node_modules/yarn/bin/yarn.js: interpreter directive changed from "#!/usr/bin/env node" to "/nix/store/v14k93caffbf0xz2g7bqr964grxxqlmj-nodejs-20.15.1/bin/node"
       > Running phase: buildPhase
       > yarn run v1.22.22
       > $ /build/source/node_modules/.bin/electron-builder --dir --linux --x64 -c.electronDist=/nix/store/0xfk2rllpsh92hk0lpncxf80wf3ydj6g-electron-29.4.6/libexec/electron -c.electronVersion=29.4.6
       >   • electron-builder  version=24.13.3 os=6.10.6
       >   • loaded configuration  file=package.json ("build" field)
       >   • writing effective config  file=dist/builder-effective-config.yaml
       >   • packaging       platform=linux arch=x64 electron=29.4.6 appOutDir=dist/linux-unpacked
       >   • copying Electron  source=/nix/store/0xfk2rllpsh92hk0lpncxf80wf3ydj6g-electron-29.4.6/libexec/electron destination=/build/source/dist/linux-unpacked
       > afterPack error:  Error: Could not find sentinel in the provided Electron binary, fuses are only supported in Electron 12 and higher
       >     at setFuseWire (/build/source/node_modules/@electron/fuses/src/index.ts:79:13)
       >     at flipFuses (/build/source/node_modules/@electron/fuses/src/index.ts:171:22)
       >     at afterPack (/build/source/scripts/afterpack.js:25:3)
       >     at Packager.afterPack (/build/source/node_modules/app-builder-lib/src/packager.ts:546:7)
       >     at LinuxPackager.doPack (/build/source/node_modules/app-builder-lib/src/platformPackager.ts:312:5)
       >     at LinuxPackager.pack (/build/source/node_modules/app-builder-lib/src/platformPackager.ts:140:5)
       >     at Packager.doBuild (/build/source/node_modules/app-builder-lib/src/packager.ts:445:9)
       >     at executeFinally (/build/source/node_modules/builder-util/src/promise.ts:12:14)
       >     at Packager._build (/build/source/node_modules/app-builder-lib/src/packager.ts:379:31)
       >     at Packager.build (/build/source/node_modules/app-builder-lib/src/packager.ts:340:12)
       >     at executeFinally (/build/source/node_modules/builder-util/src/promise.ts:12:14)
       > error Command failed with exit code 1.
       > info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       For full logs, run 'nix log /nix/store/w6npgp9zxljdgfpi2wr9p9z5lvb90fbs-teams-for-linux-1.4.27.drv'.
error: 1 dependencies of derivation '/nix/store/3g7sspzaxbh94y9f2sfp9d4k51aqlfk5-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qwkdzwylxk6mc38ffn700fnsj3jg321k-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/slki7sk70y2h3prafh6vivanj6f40p6h-teams-for-linux-1.4.27-fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ypb73dxa1kvisr2cfrhmjm2vipf0ap4n-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8rf6akpxl2mih2cnliawl5gvv5jyig20-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7wvcryx22b58jivyl7x04yvrjfc0s4sp-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1jcnm8fx7bdszkzrimcwddahmj2fll3x-nixos-system-dell-pc-24.11.20240828.71e91c4.drv' failed to build
```

### Notify maintainers

@muscaln
@lilyinstarlight
@qjoly 
@chvp 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.10.6, NixOS, 24.11 (Vicuna), 24.11.20240828.71e91c4`
- multi-user?: `yes`
- sandbox: `relaxed`
- version: `nix-env (Nix) 2.25.0pre20240807_cfe66dbe`
- nixpkgs: `/nix/store/887hpp8a2i99n9jjwcvz6qkhhhqsvzkg-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ClementBaziret** [comment]
I had the same problem

**Comment by DamienCassou** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/337868.
