### ISSUE TITLE
lima fault when using docker template with go < 1.23.0

### ISSUE THREAD

**Issue by gdw2vs** [NixOS/nixpkgs#339296]
### Describe the bug
When running `limactl` with the docker template, I get a "segmentation violation" (see Screenshots below)

### Steps To Reproduce
1. Install the latest `lima` package from unstable (0.22.0)
2. Create a VM (see screenshot section below)

### Expected behavior
VM should be created successfully.

### Screenshots

Full output:

```
$ limactl create --name default template://docker
? Creating an instance "default" Proceed with the current configuration
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x840df3]

goroutine 1 [running]:
github.com/lima-vm/lima/pkg/limayaml.executeGuestTemplate({0xc000128a10, 0x5e}, {0xc000112030, 0x1b})
        github.com/lima-vm/lima/pkg/limayaml/defaults.go:749 +0x193
github.com/lima-vm/lima/pkg/limayaml.FillDefault(0xc000130008, 0xc000130288, 0xc000130508, {0xc000112030, 0x25})
        github.com/lima-vm/lima/pkg/limayaml/defaults.go:403 +0x1ecb
github.com/lima-vm/lima/pkg/limayaml.Load({0xc0005ed000, 0xe56, 0x1000}, {0xc000112030, 0x25})
        github.com/lima-vm/lima/pkg/limayaml/load.go:89 +0x525
main.createInstance({0x1377678, 0x2202ca0}, 0xc000621b98, 0x1)
        github.com/lima-vm/lima/cmd/limactl/start.go:326 +0x1c5
main.loadOrCreateInstance(0xc000466c08, {0xc0004e91a0?, 0x0?, 0x0?}, 0x1)
        github.com/lima-vm/lima/cmd/limactl/start.go:278 +0x1778
main.createAction(0xc000466c08, {0xc0004e91a0, 0x1, 0x3})
        github.com/lima-vm/lima/cmd/limactl/start.go:479 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc000466c08, {0xc0004e9110, 0x3, 0x3})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc000466908)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        github.com/lima-vm/lima/cmd/limactl/main.go:26 +0x18
```

### Additional context

I'm installing this package on Ubuntu via [devbox](https://www.jetify.com/devbox).  I'm really trying to get colima running.  Colima uses lima with the docker template.  

I don't see this issue with the colima/lima package on macos.  

### Notify maintainers

@r-ryantm @zowoq 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/9j1f45904jshhlsmb9ljqaxdkg86ajl2-nix-info
copying path '/nix/store/9j1f45904jshhlsmb9ljqaxdkg86ajl2-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-1023-aws, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/home/gwarner/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gdw2vs** [comment]
When I build the binaries on my host with go v1.22.0 (e.g. clone the repo, run `make`), the resulting binaries also produce the same stack trace.  

But, when I build with go v1.23.0, the resulting binaries work.

Although I'm learning, I don't know how to tweak the lima derivation to always build with go > 1.23.x.

(I tried this approach after seeing [this line](https://github.com/lima-vm/lima/blob/master/.github/workflows/release.yml#L33) in the lima github actions.  I was looking for possible differences to how the official binary is build and how nix might be building it).

**Comment by gdw2vs** [comment]
Something's fishy.  When I build lima with the unstable go v1.23.0 I still get the stack trace.  When I build with the go provided by `devbox global add go@1.23.0`, it works.  I would've expected these to be the same derivation.  I have more learning to do.  

It would be helpful if someone running on nixos proper can let me know whether `limactl` is working for them with the docker template.

**Comment by kachick** [comment]
I've tried the command with draft v1.1.1 https://github.com/NixOS/nixpkgs/pull/415093 on nixos-25.05, it seems working.

```console
> limactl --version
limactl version 1.1.1

> limactl create --name nixpkgs-339296 template://docker
? Creating an instance "nixpkgs-339296" Proceed with the current configuration
INFO[0003] Attempting to download the image              arch=x86_64 digest="sha256:8d6161defd323d24d66f85dda40e64e2b9021aefa4ca879dcbc4ec775ad1bbc5" location="https://cloud-images.ubuntu.com/releases/noble/release-20250516/ubuntu-24.04-server-cloudimg-amd64.img"
INFO[0004] Using cache "/home/kachick/.cache/lima/download/by-url-sha256/1fd71ea0c23d063af1143a67202ebe07aa7f44e6a71a6a37ca115ab538ab6edd/data"
INFO[0004] Run `limactl start nixpkgs-339296` to start the instance.
```

I think it also works on current v1.0.7. Please try it with newer versions.

**Comment by SuperSandro2000** [comment]
I would expect that you must compile that plugin with the go version Lima is using.
