### ISSUE TITLE
`luarocks-packages-updater` script is flaky

### ISSUE THREAD

**Issue by GaetanLepage** [NixOS/nixpkgs#339236]
### Describe the bug
The `luarocks-packages-updater` script has a very flaky behavior and crashes.
Because of that, I have not able to update the `luaPackages` package set for a while and it starts to affect the `vimPlugins` set as well.

Logs:
<details>
```
Traceback (most recent call last):
  File "/nix/store/pm87llw5n1j6ygfkzs5zcvzjwgyb988r-luarocks-packages-updater-0.1/bin/..luarocks-packages-updater-wrapped-wrapped", line 222, in <module>
    main()
  File "/nix/store/pm87llw5n1j6ygfkzs5zcvzjwgyb988r-luarocks-packages-updater-0.1/bin/..luarocks-packages-updater-wrapped-wrapped", line 218, in main
    editor.run()
  File "/nix/store/pm87llw5n1j6ygfkzs5zcvzjwgyb988r-luarocks-packages-updater-0.1/lib/pluginupdate.py", line 568, in run
    getattr(self, command)(args)
  File "/nix/store/pm87llw5n1j6ygfkzs5zcvzjwgyb988r-luarocks-packages-updater-0.1/bin/..luarocks-packages-updater-wrapped-wrapped", line 101, in update
    update_plugins(self, args)
  File "/nix/store/pm87llw5n1j6ygfkzs5zcvzjwgyb988r-luarocks-packages-updater-0.1/lib/pluginupdate.py", line 803, in update_plugins
    redirects = update()
                ^^^^^^^^
  File "/nix/store/pm87llw5n1j6ygfkzs5zcvzjwgyb988r-luarocks-packages-updater-0.1/bin/..luarocks-packages-updater-wrapped-wrapped", line 138, in update
    results = pool.map(_prefetch, sorted_plugin_specs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/pgb120fb7srbh418v4i2a70aq1w9dawd-python3-3.12.5/lib/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/pgb120fb7srbh418v4i2a70aq1w9dawd-python3-3.12.5/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/nix/store/pgb120fb7srbh418v4i2a70aq1w9dawd-python3-3.12.5/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/pgb120fb7srbh418v4i2a70aq1w9dawd-python3-3.12.5/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/nix/store/pm87llw5n1j6ygfkzs5zcvzjwgyb988r-luarocks-packages-updater-0.1/bin/..luarocks-packages-updater-wrapped-wrapped", line 204, in generate_pkg_nix
    output = subprocess.check_output(cmd, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/pgb120fb7srbh418v4i2a70aq1w9dawd-python3-3.12.5/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/pgb120fb7srbh418v4i2a70aq1w9dawd-python3-3.12.5/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['luarocks', 'nix', '--maintainers=vyp', 'lpeg']' returned non-zero exit status 99.
```
</details>

### Steps To Reproduce
1. `nix run .#luarocks-packages-updater` (from a clone of `nixpkgs`)

### Expected behavior
The script runs fine and does not crash.

### Notify maintainers

cc @mrcjkb @teto 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.47, NixOS, 24.11 (Vicuna), 24.11.20240831.12228ff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/bd4fmzws6n5542khxbifbkr6nrygi232-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GaetanLepage** [comment]
The package listed in the final stacktrace is not always the same by the way.

Also, earlier during the execution, those error messages appear several times (although they do not directly stop execution):
```
Error: LuaRocks dev bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
...0-unstable-2024-04-29/share/lua/5.2/luarocks/cmd/nix.lua:350: attempt to concatenate local 'src_str' (a nil value)
stack traceback:
	...0-unstable-2024-04-29/share/lua/5.2/luarocks/cmd/nix.lua:350: in function 'convert_spec2nix'
	...0-unstable-2024-04-29/share/lua/5.2/luarocks/cmd/nix.lua:544: in function <...0-unstable-2024-04-29/share/lua/5.2/luarocks/cmd/nix.lua:483>
	(...tail calls...)
	[C]: in function 'xpcall'
	...nix-0-unstable-2024-04-29/share/lua/5.2/luarocks/cmd.lua:672: in function 'run_command'
	...luarocks-nix-0-unstable-2024-04-29/bin/.luarocks-wrapped:39: in main chunk
	[C]: in ?
Error: https://api.github.com/repos/leafo/moonscript/commits?per_page=1: status code 403
Call to nurl --indent 2 https://github.com/leafo/moonscript.git failed with status: nil
```

**Comment by teto** [comment]
try running it with --debug=DEBUG and you might see the real error. It runs updates in parallel, which might explain why you dont see the same output everytime

**Comment by GaetanLepage** [comment]
Thanks, I have done that, along with `-p 1`.
I confirm that the script reliably fails on `lpeg`.

**Comment by GaetanLepage** [comment]
The issue is caused by [lpeg's src](https://luarocks.org/manifests/gvvaughan/lpeg-1.1.0-1.rockspec): [http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz](http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz) being 404.
The script calls [`luarocks nix --maintainers=vyp`](https://github.com/NixOS/nixpkgs/blob/280db3decab4cbeb22a4599bd472229ab74d25e1/pkgs/by-name/lu/luarocks-packages-updater/updater.py#L169-L200) which itself calls [`nix-prefetch-url`](https://github.com/nix-community/luarocks-nix/blob/9d0440da358eac11afdbef392e2cf3272a8c7101/src/luarocks/cmd/nix.lua#L100) which fails to download the source and returns `null`.

I propose to remove the package. Does someone has a better solution ?

**Comment by GaetanLepage** [comment]
Actually, the prior release is still online. Maybe the author has yanked the latest one but forgot to remove it from luarocks...

**Comment by mrcjkb** [comment]
> The issue is caused by [lpeg's src](https://luarocks.org/manifests/gvvaughan/lpeg-1.1.0-1.rockspec): http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz being 404.

The URL works fine on my end :thinking:

**Comment by GaetanLepage** [comment]
I actually don't have a 404, but rather a 301, sorry:

```
✗ nix-prefetch-url http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz
warning: error: unable to download 'http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz': HTTP error 301 (curl error: SSL peer certificate or SSH remote key was not OK); retrying in 296 ms
warning: error: unable to download 'http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz': HTTP error 301 (curl error: SSL peer certificate or SSH remote key was not OK); retrying in 552 ms
warning: error: unable to download 'http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz': HTTP error 301 (curl error: SSL peer certificate or SSH remote key was not OK); retrying in 1092 ms
warning: error: unable to download 'http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz': HTTP error 301 (curl error: SSL peer certificate or SSH remote key was not OK); retrying in 2658 ms
error: unable to download 'http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz': HTTP error 301 (curl error: SSL peer certificate or SSH remote key was not OK)
```

**Comment by GaetanLepage** [comment]
My web browser (firefox) doesn't complain, but `wget`/`nix-prefetch-url` does.

**Comment by teto** [comment]
301 is for redirection: 
```
➜ curl 'http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz'
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz">here</a>.</p>
</body></html>
```
If I follow the redirection:
```
curl 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz'
curl: (35) OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
```
Note sure what that means. certificate issue ? firefox is fine with https://www.inf.puc-rio.br/~roberto/lpeg/ . No big warning about a self-signed certificate (website is let's encrypt).

Several options:
1. ideally someone asks them to fix it. I've done my fair deal of lua ecosystem fixup so I pass. They should at least 
2. you can modify in the luarocks csv file to use an alternate valid rockspec (towards one of your fork for instance, I've done it in the past for faulty packages. Not great but well..)
3. remove lpeg from the update list and add it back. Or move it to lua/overrides.nix so it doesn't get autoupdated for now

**Comment by mrcjkb** [comment]
I'd suggest we go with option 3. (move to overrides) as a temporary hotfix and bug [the rockspec maintainer](https://luarocks.org/modules/gvvaughan) for a fix (I've just sent them an e-mail).

**Comment by gvvaughan** [comment]
LPeg rockspec maintainer here.  i released a new revision of the rockspec earlier, updating all the URLs to https.

**Comment by GaetanLepage** [comment]
> LPeg rockspec maintainer here. i released a new revision of the rockspec earlier, updating all the URLs to https.

Thank you for helping us with this !

Unfortunately, `nix-prefetch-url` still complains as follows:
```
✗ nix-prefetch-url https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz
warning: error: unable to download 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz': SSL peer certificate or SSH remote key was not OK (60); retrying in 254 ms
warning: error: unable to download 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz': SSL peer certificate or SSH remote key was not OK (60); retrying in 503 ms
warning: error: unable to download 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz': SSL peer certificate or SSH remote key was not OK (60); retrying in 1132 ms
warning: error: unable to download 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz': SSL peer certificate or SSH remote key was not OK (60); retrying in 2676 ms
error: unable to download 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz': SSL peer certificate or SSH remote key was not OK (60)
```

**Comment by gvvaughan** [comment]
I don't think this can be an issue with the rockspec.  If there's an issue with the website certificate, I believe that site is maintained by @lhf (on GitHub).  However, I have no trouble downloading the lpeg tarball using curl, wget, or clicking the link with my browser from either the http:// or https:// protocols.

Maybe nix-prefetch-url is tripping over 301's or something?

**Comment by dustyhorizon** [comment]
Just wanting to chime in here that it seems to be 301 being the issue here, I am facing something similar when attempting to build Semgrep.

```
+nix-store-export-outpath-oidc-s3 *failed* |        last 7 log lines:
+nix-store-export-outpath-oidc-s3 *failed* |        > exporting https://github.com/semgrep/semgrep.git (rev v1.89.0) into /nix/store/ibn8xawg0yjc8c49zg2xyf4630klgrv4-source
+nix-store-export-outpath-oidc-s3 *failed* |        > Initialized empty Git repository in /nix/store/ibn8xawg0yjc8c49zg2xyf4630klgrv4-source/.git/
+nix-store-export-outpath-oidc-s3 *failed* |        > fatal: unable to access 'https://github.com/semgrep/semgrep.git/': OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
+nix-store-export-outpath-oidc-s3 *failed* |        > fatal: unable to access 'https://github.com/semgrep/semgrep.git/': OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
+nix-store-export-outpath-oidc-s3 *failed* |        > fatal: unable to access 'https://github.com/semgrep/semgrep.git/': OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
+nix-store-export-outpath-oidc-s3 *failed* |        > fatal: unable to access 'https://github.com/semgrep/semgrep.git/': OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
+nix-store-export-outpath-oidc-s3 *failed* |        > Unable to checkout refs/tags/v1.89.0 from https://github.com/semgrep/semgrep.git.
+nix-store-export-outpath-oidc-s3 *failed* |        For full logs, run 'nix log /nix/store/mk81q6nzyzjhf7v9pvm2zcrx4q6wa73z-source.drv'.
+nix-store-export-outpath-oidc-s3 *failed* | error: 1 dependencies of derivation '/nix/store/7ly9ikhz0cbkpbhqgpsgfrxbs089lnn5-ocaml5.2.0-semgrep-core-1.89.0.drv' failed to build
```

Oddly enough was that other ocaml packages seem to build fine (also sourced from github) so I am not entirely sure what's wrong here.

**Comment by teto** [comment]
```
$ nix flake prefetch 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz' -vvvv
using cache entry 'file:{"name":"flake-registry.json","store":"/nix/store","url":"https://doctor.novadiscovery.net/main/flake-registry.json"}' -> '{"etag":"\"fd250cec34a66700cd8cecb34de2d831\"","storePath":"vzqix6akr8d16k325w31038inxv4hnwd-flake-registry.json","url":"https://doctor.novadiscovery.net/main/flake-registry.json"}'
performing daemon worker op: 11
acquiring write lock on '/nix/var/nix/temproots/2691282'
performing daemon worker op: 1
using cache entry 'file:{"name":"flake-registry.json","store":"/nix/store","url":"https://doctor.novadiscovery.net/main/flake-registry.json"}' -> '{"etag":"\"fd250cec34a66700cd8cecb34de2d831\"","url":"https://doctor.novadiscovery.net/main/flake-registry.json"}', '/nix/store/vzqix6akr8d16k325w31038inxv4hnwd-flake-registry.json'
performing daemon worker op: 11
performing daemon worker op: 12
looked up 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz' -> 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz'
did not find cache entry for 'tarball:{"url":"https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz"}'
unpacking 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz' into the Git cache...
downloading 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz'...
starting download of https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz
finished download of 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz'; curl status = 60, HTTP status = 0, body = 0 bytes, duration = 0.47 s
warning: error: unable to download 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz': SSL peer certificate or SSH remote key was not OK (60); retrying in 283 ms
starting download of https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz
finished download of 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz'; curl status = 60, HTTP status = 0, body = 0 bytes, duration = 1.22 s
```
and `man curl` says `60     Peer certificate cannot be authenticated with known CA certificates.`. I cant look at it right now but either we have outdated list of CA or the website is using some "not" traditional CA

**Comment by dustyhorizon** [comment]
If it helps, my previously known working `nixpkgs` was pinned to commit `ad416d066ca1222956472ab7d0555a6946746a80`.

**Comment by teto** [comment]
even after the rockspec update I get. 
```
wget 'https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz'
--2024-11-12 13:54:55--  https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz
Resolving www.inf.puc-rio.br (www.inf.puc-rio.br)... 139.82.16.205
Connecting to www.inf.puc-rio.br (www.inf.puc-rio.br)|139.82.16.205|:443... connected.
ERROR: cannot verify www.inf.puc-rio.br's certificate, issued by ‘CN=R10,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
To connect to www.inf.puc-rio.br insecurely, use `--no-check-certificate'.
```

firefox doesn't seem to mind though but firefox embeds its own certficiate store I think.
I dont know how "lets encrypt" operates but I would assume it's one of the most dynamic out there ?
the `cacert` package is a tag NSS_3_104_RTM. The repo contains lots of tags but does that mean we need https://github.com/nss-dev/nss/tree/NSS_3_106_RTM ? I tried `nix-shell maintainers/scripts/update.nix --argstr package cacert` which didn't seem to do anything, so I updated the package to NSS_3_106_RTM but as it's a core package, I am afraid it's rebuilding the work.
Any insight @fpletz @lukegb ?

**Comment by lukegb** [comment]
```
$ nix-shell -p openssl

[nix-shell:~]$ openssl s_client -connect www.inf.puc-rio.br:443
Connecting to 139.82.16.205
CONNECTED(00000003)
depth=0 CN=www.inf.puc-rio.br
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN=www.inf.puc-rio.br
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN=www.inf.puc-rio.br
verify return:1
```

They appear to be missing the leaf->intermediate chain, so we can't chain it back to the root store. wget doesn't implement AIA chasing so we can't resolve the certificate.

Note that on MacOS the system wget uses Secure Transport, which _does_ implement AIA chasing.

**Comment by teto** [comment]
Pinging @gvvaughan just in case he missed the previous comment

**Comment by gvvaughan** [comment]
Thanks for the ping.

While I do package Roberto's lpeg distribution as a luarock, I guess you would need to ask @hishamhm (luarocks maintainer) or @leafo (luarocks.org maintainer) about technical aspects of certs with package downloading, depending on whether you are fetching with luarocks itself or otherwise interacting with luarocks.org.

**Comment by teto** [comment]
thanks for the follow up. I've sent an email to the first link on the contact page of http://www.inf.puc-rio.br/, hopefully it gets forwarded to the webmaster

**Comment by teto** [comment]
yep `luarocks nix lpeg` works now. Shall we close this ? I find the script quite stable lately. Errors can still be confusing but running with `--debug DEBUG` or `luarocks nix <PACKAGE>` usually clears up any misunderstanding ?!

**Comment by GaetanLepage** [comment]
Sure.
