### ISSUE TITLE
Build failure: qtwebkit

### ISSUE THREAD

**Issue by kashw2** [NixOS/nixpkgs#339510]
### Steps To Reproduce

1. nix build github:nixos/nixpkgs#libsForQt5.qt5.qtwebkit

### Build log

```
[  1%] Building CXX object Source/WTF/wtf/CMakeFiles/WTF.dir/UniStdExtras.cpp.o
[  1%] Building CXX object Source/WTF/wtf/CMakeFiles/WTF.dir/qt/WorkQueueQt.cpp.o
[  1%] Building CXX object Source/WTF/wtf/CMakeFiles/WTF.dir/glib/GRefPtr.cpp.o
[  1%] Linking CXX static library ../../../lib/libWTF.a
[  1%] Built target WTF
[  1%] Generating ../../DerivedSources/JavaScriptCore/Bytecodes.h, ../../DerivedSources/JavaScriptCore/InitBytecodes.asm
[  1%] Generating ../../DerivedSources/JavaScriptCore/LLIntDesiredOffsets.h
/tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:587:in `block in parseSequence': undefined method `=~' for an instance of Annotation (NoMethodEr>
        from <internal:kernel>:187:in `loop'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:586:in `parseSequence'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:654:in `block in parseSequence'
        from <internal:kernel>:187:in `loop'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:586:in `parseSequence'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:814:in `parseData'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:818:in `parse'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:780:in `block in parseSequence'
        from <internal:kernel>:187:in `loop'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:586:in `parseSequence'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:625:in `block in parseSequence'
        from <internal:kernel>:187:in `loop'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:586:in `parseSequence'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:814:in `parseData'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/parser.rb:818:in `parse'
        from /tmp/nix-build-qtwebkit-5.212.0-alpha4.drv-0/source/Source/JavaScriptCore/offlineasm/generate_offset_extractor.rb:68:in `<main>'
make[2]: *** [Source/JavaScriptCore/CMakeFiles/LLIntOffsetsExtractor.dir/build.make:96: DerivedSources/JavaScriptCore/LLIntDesiredOffsets.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:1637: Source/JavaScriptCore/CMakeFiles/LLIntOffsetsExtractor.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

### Notify maintainers

@qknight @ttuegel @periklis @bkchr 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.6-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20240826.33895f7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.25.0pre20240903_a6e6da3`
 - nixpkgs: `/nix/store/3fwrpvwnzfkxkgyzfw43fpjwrfnm3as9-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by UlyssesZh** [comment]
Related: #297646.

**Comment by mrbitt** [comment]
add https://src.fedoraproject.org/rpms/qt5-qtwebkit/raw/rawhide/f/webkit-offlineasm-warnings-ruby27.patch
