### ISSUE TITLE
Flutter app build error, Cmake PkgConfig::GTK and graphite2 include missing.

### ISSUE THREAD

**Issue by MROvaiz** [NixOS/nixpkgs#341147]
### Describe the bug
Error while running `flutter run` in unstable nixpkgs
```console
[mro@nixbin:~/github/mrovaiz/flutter/my_app]$ flutter run
Launching lib/main.dart on Linux in debug mode...
CMake Error in CMakeLists.txt:
  Imported target "PkgConfig::GTK" includes non-existent path

    "/nix/store/bbp2rgd41n030a1wrr1k8ci7p41w82db-graphite2-1.3.14/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Generate step failed.  Build files cannot be regenerated correctly.
Building Linux application...                                           
Error: Unable to generate build files
```

### Steps To Reproduce
1. add environment pkg `flutter`.
2. new folder `flutter create my_app`.
3. run `flutter run` inside my_app.
4. you will receive above error.

### Expected behavior
App should be build and show the linux app or web. 

### Additional context
`/nix/store/bbp2rgd41n030a1wrr1k8ci7p41w82db-graphite2-1.3.14` folder exist, but no include inside graphite2.
this issue was also raise in forums
[nixos-forum](https://discourse.nixos.org/t/build-error-when-running-flutter-app/51394)
[stackoverflow](https://stackoverflow.com/questions/78934628/build-error-when-running-flutter-app-in-nixos)

### Notify maintainers
@RossComputerGuy 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[mro@nixbin:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.49, NixOS, 24.11 (Vicuna), 24.11.20240906.574d1ea`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/5w3dp0m37794iffsbm9vd9f1xmmhda6i-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RossComputerGuy** [comment]
> `/nix/store/bbp2rgd41n030a1wrr1k8ci7p41w82db-graphite2-1.3.14` folder exist, but no include inside graphite2.
> this issue was also raise in forums

What is in the graphite2 directory?

CC @NixOS/flutter

**Comment by RossComputerGuy** [comment]
Hmm, you might need to try `flutter run` with verbose and share the log.

**Comment by MROvaiz** [comment]
> `flutter run` with verbose

```console
[mro@nixbin:~/github/mrovaiz/flutter/my_app]$ flutter run --verbose
[  +24 ms] Unable to locate an Android SDK.
[  +76 ms] Skipping pub get: version match.
[  +73 ms] Generating /home/mro/github/mrovaiz/flutter/my_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +48 ms] No packages with native assets. Skipping native assets compilation.
[   +1 ms] Initializing file store
[   +2 ms] Skipping target: gen_localizations
[   +1 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/mro/github/mrovaiz/flutter/my_app/.dart_tool/package_config_subset}
[  +30 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[        ] complete
[   +2 ms] Launching lib/main.dart on Linux in debug mode...
[   +1 ms] /nix/store/wp7165dbyc8w8ng10qaxkfsrrr9rc5hs-flutter-wrapped-3.24.1-sdk-links/bin/cache/dart-sdk/bin/dartaotruntime
--disable-dart-dev
/nix/store/wp7165dbyc8w8ng10qaxkfsrrr9rc5hs-flutter-wrapped-3.24.1-sdk-links/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snaps
hot --sdk-root
/nix/store/wp7165dbyc8w8ng10qaxkfsrrr9rc5hs-flutter-wrapped-3.24.1-sdk-links/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.OGPOOU/flutter_tool.VJQPGM/app.dill
--packages /home/mro/github/mrovaiz/flutter/my_app/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
--verbosity=error --enable-experiment=alternative-invalidation-strategy
[   +9 ms] Building Linux application...
[   +3 ms] <- compile package:my_app/main.dart
[        ] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64
/home/mro/github/mrovaiz/flutter/my_app/linux
[  +53 ms] -- Configuring done (0.0s)
[   +9 ms] CMake Error in CMakeLists.txt:
[   +1 ms]   Imported target "PkgConfig::GTK" includes non-existent path
[        ]     "/nix/store/bbp2rgd41n030a1wrr1k8ci7p41w82db-graphite2-1.3.14/include"
[        ]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[        ]   * The path was deleted, renamed, or moved to another location.
[        ]   * An install or uninstall procedure did not complete successfully.
[        ]   * The installation package was faulty and references files it does not
[        ]   provide.
[   +1 ms] -- Generating done (0.0s)
[   +1 ms] CMake Generate step failed.  Build files cannot be regenerated correctly.
[   +9 ms] Building Linux application... (completed in 77ms)
[+2525 ms] Error: Unable to generate build files
[        ] "flutter run" took 2,826ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:874:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[  +56 ms] ensureAnalyticsSent: 54ms
[        ] Running 2 shutdown hooks
[  +12 ms] Shutdown hooks complete
[  +69 ms] exiting with code 1
```
I also checked in project created where `PkgConfig::GTK` is present.
`linux/flutter/CMakeLists.txt` and `linux/CMakeLists.txt`.
`flutter create my_app`
Please have a look, it might also be the project require some pkg related to gtk!

**Comment by FlafyDev** [comment]
This usually happens when using flutter from `nix shell` instead of creating a dev shell and `nix develop`ing into it

**Comment by MROvaiz** [comment]
> This usually happens when using flutter from `nix shell` instead of creating a dev shell and `nix develop`ing into it

As i mentioned, i have added flutter in environment pkg.
```nix
{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    flutter
  ];
}
```
[git-flutter-file](https://github.com/MROvaiz/nixos-config/blob/af8e687bd00cbc04d62ab3d7c698b8688ee83928/modules/nixos/development/flutter.nix)

I want to develop for linux and web for now.

**Comment by MROvaiz** [comment]
> Yeah, that may be the same bug I decribed. Try to make a devshell with flutter and `nix develop`ing into it. Maybe that'll work

I have this, and still same error.
```nix
{
  description = "Flutter 3.13.x";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/23.11";
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = {
    self,
    nixpkgs,
    flake-utils,
  }:
    flake-utils.lib.eachDefaultSystem (system: let
      pkgs = import nixpkgs {
        inherit system;
        config = {
          allowUnfree = true;
        };
      };
    in {
      devShell = with pkgs;
        mkShell rec {
          buildInputs = [
            flutter
            jdk17
          ];
        };
    });
}
```
i dont want android development, only linux.
Same error.

**Comment by MROvaiz** [comment]
I want to add one more point, i have hyprland.
is it also related to desktop manager? error for gtk?

**Comment by RossComputerGuy** [comment]
> I want to add one more point, i have hyprland.

Very unrelated, Hyprland would have absolutely no effect here. Have you tried adding GTK 3 to the dev shell inputs?

**Comment by Andyson007** [comment]
I had the same issue, and found [this](https://www.reddit.com/r/NixOS/comments/1ab77ht/comment/kjq75jz/)
```nix
{
description = "Flutter 3.13.x";
inputs = {
  nixpkgs.url = "github:NixOS/nixpkgs/23.11";
  flake-utils.url = "github:numtide/flake-utils";
};
outputs = { self, nixpkgs, flake-utils }:
  flake-utils.lib.eachDefaultSystem (system:
    let
      pkgs = import nixpkgs {
        inherit system;
        config = {
          android_sdk.accept_license = true;
          allowUnfree = true;
        };
      };
      buildToolsVersion = "34.0.0";
      androidComposition = pkgs.androidenv.composeAndroidPackages {
        buildToolsVersions = [ buildToolsVersion "30.0.3" ];
        platformVersions = [ "29" "30" "31" "32" "33" "34" "28" ];
        abiVersions = [ "armeabi-v7a" "arm64-v8a" ];
      };
      androidSdk = androidComposition.androidsdk;
    in
    {
      devShell =
        with pkgs; mkShell rec {
          ANDROID_SDK_ROOT = "${androidSdk}/libexec/android-sdk";
          GRADLE_OPTS = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${androidSdk}/libexec/android-sdk/build-tools/34.0.0/aapt2";
          buildInputs = [
            flutter
            androidSdk
            jdk17
          ];
        };
    });
}``` which seems to work for me

**Comment by medanisjbara** [comment]
So this is indeed a bug ? I thought I'm just too stupid to do this correctly!

For anyone looking for a workaround, here's a temporary solution I have been using:

- Add `pkg-config` and `gtk3` to your `buildInputs`
- `nix develop`
- `flutter clean`
- `flutter run`

Should work with no problems, if you ignore the repetitive warning on the first run, which seems to only appear in the first run.

The warning is as follows
```
Package libpcre2-8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre2-8.pc'
to the PKG_CONFIG_PATH environment variable
```
but does not seem to affect anything as far as I can tell.

**Comment by emanueljg** [comment]
I ran into the same error and managed to solve it by adding `pkg-config` and `gtk3` to `buildInputs`, just as suggested bove. As a bonus, I've finally compiled a list of all other packages needed to stop that "one-time nagging" mentioned above:

```nix
  buildInputs = [
    # emulator hwdecode
    vulkan-loader 
    libGL        

    # build shell hook
    pkg-config

    # needed to not crash
    gtk3

    # fixes nagging
    pcre2.dev
    util-linux.dev
    libselinux
    libsepol
    libthai
    libdatrie
    xorg.libXdmcp
    xorg.libXtst
    lerc.dev
    libxkbcommon
    libepoxy
  ];
```
This smells like a bug though, you shouldn't need to do all this.

**Comment by MROvaiz** [comment]
tried with adding extra pkgs from above, same error: related to GL
```console
(my_app:9861): Gtk-WARNING **: 18:48:03.893: Theme directory apps@2x/22 of theme WhiteSur has no size field
(my_app:9861): Gtk-WARNING **: 18:48:03.893: Theme directory apps@2x/32 of theme WhiteSur has no size field
(my_app:9861): Gtk-WARNING **: 18:48:03.893: Theme directory preferences@2x/22 of theme WhiteSur has no size field
(my_app:9861): Gdk-CRITICAL **: 18:48:03.930: gdk_gl_context_make_current: assertion 'GDK_IS_GL_CONTEXT (context)' failed
** (my_app:9861): WARNING **: 18:48:03.930: Failed to initialize GLArea: No GL implementation is available
** (my_app:9861): CRITICAL **: 18:48:11.806: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed
```

**Comment by hakan-demirli** [comment]
Adding pkg-config and gtk3 does solve the issue however you need to first reset the `build` cache by deleting the `./build` dir. Otherwise, the issue persists.

**Comment by rafaeloledo** [comment]
@hakan-demirli here i don't even need separated `gtk3` on my Hyprland. I was able to run with both mkShell and buildFHSEnv. I spent about 2 days fiddling Flutter and the main problem is what you described. You don't need to do `rm -rf build/`. `flutter clean` will remove it and the other cache folders. 

The deps not listed in the standard wiki shell are somewhat already detected globally and successfully used or installed by `flutter run`.

I recommend always reading the verbose output, you can see things like if the program encountered dependencies on the system or not.

Making a dev shell with a ton of dependencies like `pkg-config` is a bit hacky since the philosophy is to not be `Docker`. Overriding `critical` ones is the goal for me.

```nix
# nix-channel --add https://tadfisher.github.io/android-nixpkgs android-nixpkgs
# nix-channel --update android-nixpkgs

{ pkgs ? import <nixpkgs> {} }:

let
  pinnedJDK = pkgs.jdk23;
  android-nixpkgs = pkgs.callPackage <android-nixpkgs> {
    channel = "stable";
  };
  android-sdk = android-nixpkgs.sdk (sdkPkgs: with sdkPkgs; [
    cmdline-tools-latest
    build-tools-33-0-0
    platform-tools
    platforms-android-33
  ]);
in

(pkgs.buildFHSEnv {
  name = "flutter-env";

  targetPkgs = pkgs: ([
    pinnedJDK
    android-sdk

    pkgs.flutter
    pkgs.dart
  ]); 

  runScript = "fish";

  profile = ''
    export ANDROID_HOME=${android-sdk}/share/android-sdk
    export JAVA_HOME=${pinnedJDK}
    export NIX_SHELL="1"
  '';
}).env
```

```nix
{
  inputs = {
    android-nixpkgs.url = "github:tadfisher/android-nixpkgs";
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, android-nixpkgs, nixpkgs, ... } @ inputs:

  let
    android-pkgs = with pkgs; callPackage android-nixpkgs {};
    system = "x86_64-linux";
    pkgs = import nixpkgs { inherit system; config.allowUnfree = true; } ;
    android-sdk = android-pkgs.sdk (p: with p; [
      cmdline-tools-latest
      build-tools-33-0-0
      platform-tools
      platforms-android-33
    ]);
    pinnedJDK = pkgs.jdk23;
  in

  {
    shell = pkgs.mkShell {
      packages = [
        pkgs.flutter
        pkgs.dart
        
        pinnedJDK
        
        android-sdk

        pkgs.python313
      ];

      JAVA_HOME = pinnedJDK;

      ANDROID_HOME = "${android-sdk}/share/android-sdk";
      ANDROID_SDK_ROOT = "${android-sdk}/share/android-sdk";

      NIX_SHELL = "1";
    };
  };
}
```

I've not tested on Android. But i really recommend every time you add another deps on the shell you rather run both commands combined: `flutter clean` and `flutter run -v`.

Both above are running even on new projects, it was not needed to override `gradle` flags since it already came with `gradlew`.

It's my `2-day` experience, hope i can help someone.

**Comment by gs-101** [comment]
I went some steps further to get the Android licenses accepted, but not sure how to get the emulator running:

```nix
# See the following issues and repositories:
# <https://github.com/NixOS/nixpkgs/issues/23910>
# <https://github.com/stuzenz/flutter-with-devenv.sh>
# <https://github.com/NixOS/nixpkgs/pull/89775>

{
  description = "Flutter dev environment";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {
          inherit system;
          config = {
            android_sdk.accept_license = true;
            allowUnfree = true;
          };
        };
        buildToolVersion = "34.0.0";
        androidComposition = pkgs.androidenv.composeAndroidPackages {
          buildToolsVersions = [
            buildToolVersion
            "33.0.1"
            "30.0.3"
          ];
          platformVersions = [
            "34"
            "33"
            "32"
            "31"
          ];
          abiVersions = [ "x86_64" ];
          extraLicenses = [
            # Already accepted for you with accept_license = true.
            # "android-sdk-license"

            # These aren't, but are useful for more uncommon setups.
            "android-sdk-preview-license"
            "android-googletv-license"
            "android-sdk-arm-dbt-license"
            "google-gdk-license"
            "intel-android-extra-license"
            "intel-android-sysimage-license"
            "mips-android-sysimage-license"
          ];
        };
        androidSdk = androidComposition.androidsdk;
        flutter_pkg = pkgs.flutter;
      in
        {
          devShell =
            with pkgs;
          mkShell rec {
            ANDROID_SDK_ROOT = "${androidSdk}/libexec/android-sdk";
            GRADLE_OPTS = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${androidSdk}/libexec/android-sdk/build-tools/${buildToolVersion}/aapt2";
            ANDROID_HOME = "${androidSdk}/libexec/android-sdk";
            JAVA_HOME = "${pkgs.jdk17}";
            buildInputs = [
              flutter_pkg
              androidSdk
              jdk17
              # extra deps https://github.com/NixOS/nixpkgs/issues/341147#issuecomment-2359171650
              libsysprof-capture
              pkg-config
              gtk3
              pcre2.dev
              util-linux.dev
              libselinux
              libsepol
              libthai
              libdatrie
              xorg.libXdmcp
              xorg.libXtst
              lerc.dev
              libxkbcommon
              libepoxy
              chromium
            ];

            shellHook = ''
              export PATH=$PATH:${androidSdk}/libexec/android-sdk/platform-tools
              export PATH=$PATH:${androidSdk}/libexec/android-sdk/cmdline-tools/latest/bin
              export PATH=$PATH:${androidSdk}/libexec/android-sdk/emulator
              export PATH="$PATH:$HOME/.pub-cache/bin"
              export CHROME_EXECUTABLE=$(which chromium)

              echo "Flutter SDK: ${flutter_pkg.version}"
              echo "Android SDK: ${androidSdk.version}"
              if [ -n "$BASH" ]; then
                ${pkgs.flutter}/bin/flutter bash-completion > .flutter-completions
                source .flutter-completions
              fi
            '';
          };
        }
    );
}
```

I also added a browser for WebDev, but `buildInputs` seems to be the wrong place for it.

I did this because I still can't get the Linux app to build properly, I get:

<details>

```
[ +105 ms] executing: /nix/store/hp9mkijqwmzd27155sv7a4bf4cm4lccm-androidsdk/libexec/android-sdk/platform-tools/adb devices -l
[  +26 ms] List of devices attached
[   +6 ms] Connected devices:
[  +43 ms] Linux (desktop) • linux  • linux-x64      • Guix System 6.13.11
[        ] Chrome (web)    • chrome • web-javascript • Chromium 135.0.7049.95
[        ] [1]: Linux (linux)
[        ] [2]: Chrome (chrome)
[        ] Please choose one (or "q" to quit)
[        ] :

[Irrelevant context removed]

[ +228 ms] Fontconfig error: Cannot load default config file: No such file: (null)
[   +4 ms] (com.example.app:21935): Gdk-CRITICAL **: 17:16:11.278: gdk_gl_context_make_current: assertion 'GDK_IS_GL_CONTEXT (context)' failed
[        ] ** (com.example.app:21935): WARNING **: 17:16:11.278: Failed to initialize GLArea: No GL implementation is available
[        ] ** (com.example.app:21935): CRITICAL **: 17:16:11.279: FlutterEngineDisplayId fl_display_monitor_get_display_id(FlDisplayMonitor *, GdkMonitor *): assertion 'FL_IS_DISPLAY_MONITOR(self)' failed
[  +18 ms] ** (com.example.app:21935): CRITICAL **: 17:16:11.297: FlutterEngineDisplayId fl_display_monitor_get_display_id(FlDisplayMonitor *, GdkMonitor *): assertion 'FL_IS_DISPLAY_MONITOR(self)' failed
[  +20 ms] ** (com.example.app:21935): CRITICAL **: 17:16:11.317: FlutterEngineDisplayId
fl_display_monitor_get_display_id(FlDisplayMonitor *, GdkMonitor *): assertion
'FL_IS_DISPLAY_MONITOR(self)' failed
[        ] ** (com.example.app:21935): CRITICAL **: 17:16:11.317: FlutterEngineDisplayId
fl_display_monitor_get_display_id(FlDisplayMonitor *, GdkMonitor *): assertion
'FL_IS_DISPLAY_MONITOR(self)' failed
[ +341 ms] ** (com.example.app:21935): CRITICAL **: 17:16:11.659: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[ +359 ms] ** (com.example.app:21935): CRITICAL **: 17:16:12.018: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[  +39 ms] ** (com.example.app:21935): CRITICAL **: 17:16:12.058: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[  +16 ms] ** (com.example.app:21935): CRITICAL **: 17:16:12.075: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[+1047 ms] ** (com.example.app:21935): CRITICAL **: 17:16:13.122: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[   +7 ms] ** (com.example.app:21935): CRITICAL **: 17:16:13.130: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[   +7 ms] ** (com.example.app:21935): CRITICAL **: 17:16:13.138: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[   +8 ms] ** (com.example.app:21935): CRITICAL **: 17:16:13.146: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[   +7 ms] ** (com.example.app:21935): CRITICAL **: 17:16:13.154: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[   +8 ms] ** (com.example.app:21935): CRITICAL **: 17:16:13.162: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[   +7 ms] ** (com.example.app:21935): CRITICAL **: 17:16:13.170: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[   +8 ms] ** (com.example.app:21935): CRITICAL **: 17:16:13.178: void
fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion
'FL_IS_KEYBOARD_MANAGER(self)' failed
[+9058 ms] ** (com.example.app:21935): CRITICAL **: 17:16:22.236: FlutterEngineDisplayId
fl_display_monitor_get_display_id(FlDisplayMonitor *, GdkMonitor *): assertion
'FL_IS_DISPLAY_MONITOR(self)' failed
```
</details>
