### ISSUE TITLE
Build failure: quickgui

### ISSUE THREAD

**Issue by LuNeder** [NixOS/nixpkgs#341893]
### Steps To Reproduce

1. build *quickgui*

### Build log

https://gist.github.com/LuNeder/271b9a730e039e8e12a3296ddea6936a

### Additional context

```
Failed obtaining PRETTY_NAME for Linux: PathNotFoundException: Cannot open file, path = '/usr/lib/os-release' (OS Error: No such file or directory
, errno = 2)
[...]
 /nix/store/4wj8q7c8fjk9j7xw6iiz7r4qrpg6gc6y-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1915:39: Error: Method not found: 'SchemeRainbo
w'.
[        ] [   +1 ms]       DynamicSchemeVariant.rainbow => SchemeRainbow(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
[        ] [        ]                                       ^^^^^^^^^^^^^
[        ] [        ] /nix/store/4wj8q7c8fjk9j7xw6iiz7r4qrpg6gc6y-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1916:42: Error: Method not found: 'SchemeFruitS
alad'.
```
### Notify maintainers

@flexiondotorg  @heyimnova 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 ✘ luana@Luana-X670E  ~  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.6, NixOS, 24.11 (Vicuna), 24.11.20240821.c374d94`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/j8pbrsb3nybdap3hhg9kw0ffqd4rlbx6-source`


```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by llakala** [comment]
Can confirm, just swapped to 24.11 and encountered this.

**Comment by Andreas02-dev** [comment]
> [quickemu-project/quickgui#242](https://github.com/quickemu-project/quickgui/pull/242) will fix this upstream and then we can bump.

Looks like it's merged now, is anything still blocking a fix? I've also encountered this: `quickgui> [        ] [   +4 ms] Failed obtaining PRETTY_NAME for Linux: PathNotFoundException: Cannot open file, path = '/usr/lib/os-release' (OS Error: No such file or directory, errno = 2)`

**Comment by RossComputerGuy** [comment]
Nothing is blocking, just low on bandwidth for myself to create a PR. That error isn't a blocker and is non fatal, every Flutter build runs into that error.

**Comment by llakala** [comment]
> Nothing is blocking, just low on bandwidth for myself to create a PR. That error isn't a blocker and is non fatal, every Flutter build runs into that error.

This is showing up as a fatal error for me when trying to build after changing the revision. Full logs: 

```
[        ] [   +7 ms] Failed obtaining PRETTY_NAME for Linux: PathNotFoundException: Cannot open file, path = '/usr/lib/os-release' (OS Error: No such file or directory, errno = 2)
[        ] [   +9 ms] Unable to locate an Android SDK.
[        ] [  +63 ms] Initializing file store
[        ] [  +13 ms] Skipping target: gen_localizations
[        ] [   +2 ms] invalidated build due to missing files: /build/source/.dart_tool/package_config_subset
[        ] [   +1 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputMissing: The following inputs were missing: /build/source/.dart_tool/package_config_subset}
[        ] [   +4 ms] unpack_linux: Starting due to {}
[        ] [  +45 ms] unpack_linux: Complete
[        ] [ +145 ms] Found plugin shared_preferences_foundation at /nix/store/0sv2j1z4kmvghapw6zhpf611a3fj638v-pub-shared_preferences_foundation-2.4.0/
[        ] [   +6 ms] Found plugin window_size at /nix/store/281pj1qkmwsbzmn02r6q9icaj11x15ab-pub-window_size-0.1.0/plugins/window_size/
[        ] [   +4 ms] Found plugin shared_preferences_android at /nix/store/36mbsh7g74j65sc2mpflp1sgqykz6dbz-pub-shared_preferences_android-2.2.3/
[        ] [   +2 ms] Found plugin shared_preferences_linux at /nix/store/602xl16ciy9nh5v05yigvaabllifcgh7-pub-shared_preferences_linux-2.3.2/
[        ] [   +1 ms] Found plugin path_provider_linux at /nix/store/6r85azf4l96yfy0b950sbp90ygxiqap0-pub-path_provider_linux-2.2.1/
[        ] [   +2 ms] Found plugin url_launcher_linux at /nix/store/76zc8zsq3cvimmjivzmbivcc7zq6sm3i-pub-url_launcher_linux-3.1.1/
[        ] [   +9 ms] Found plugin package_info_plus at /nix/store/cmdzyh2kjsg0ihv7akj99f2q91g0jcj8-pub-package_info_plus-8.0.0/
[        ] [   +2 ms] Found plugin url_launcher at /nix/store/d8cg5dk9xwdwim8jwnvrw8nmijr3iv39-pub-url_launcher-6.3.0/
[        ] [   +2 ms] Found plugin url_launcher_macos at /nix/store/dwn48qwaid32b34iczyhm343fcyimd5d-pub-url_launcher_macos-3.2.0/
[        ] [   +1 ms] Found plugin url_launcher_ios at /nix/store/fcqj5jjjblla640qwp6fyss8q6zr5n7d-pub-url_launcher_ios-6.3.0/
[        ] [        ] Found plugin shared_preferences_web at /nix/store/fwhqzisbkvp08wgks38pda4yrha9viqb-pub-shared_preferences_web-2.3.0/
[        ] [  +21 ms] Found plugin shared_preferences at /nix/store/m33wwmrhdiwq9r6lym6nnrxk7xfcxd27-pub-shared_preferences-2.2.3/
[        ] [   +5 ms] Found plugin flutter_plugin_android_lifecycle at /nix/store/n3v1dangini95nmf8qlnlkvip2s5sd51-pub-flutter_plugin_android_lifecycle-2.0.20/
[        ] [   +4 ms] Found plugin url_launcher_android at /nix/store/nlqazhkh1xv1qda4s0mdzf6zb905lagd-pub-url_launcher_android-6.3.3/
[        ] [   +3 ms] Found plugin file_picker at /nix/store/pmsshjvm2a4mcyrbfcjfb3ynva9y3m8p-file_picker-8.0.6/
[        ] [   +1 ms] Found plugin shared_preferences_windows at /nix/store/qidlkg4vjwjmch6w595n8bziw4m9cml4-pub-shared_preferences_windows-2.3.2/
[        ] [   +4 ms] Found plugin path_provider_windows at /nix/store/wpx8wfbislwv8zzygrpnbj2yfhdpw0bc-pub-path_provider_windows-2.2.1/
[        ] [        ] Found plugin url_launcher_web at /nix/store/wqh6k1g8gqhi30ixlnn73cnymx2wimrj-pub-url_launcher_web-2.3.1/
[        ] [   +5 ms] Found plugin url_launcher_windows at /nix/store/zap879f3mvgncq3nnq9a0z57cq0n9gzr-pub-url_launcher_windows-3.1.1/
[        ] [   +5 ms] Package file_picker:linux references file_picker:linux as the default plugin, but it does not provide an inline implementation.
[        ]            Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: linux: default_package: file_picker` or add an inline implementation to file_picker via `platforms: linux:` `pluginClass` or `dartPluginClass`.
[        ] [   +1 ms] Package file_picker:macos references file_picker:macos as the default plugin, but it does not provide an inline implementation.
[        ]            Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: macos: default_package: file_picker` or add an inline implementation to file_picker via `platforms: macos:` `pluginClass` or `dartPluginClass`.
[        ] [        ] Package file_picker:windows references file_picker:windows as the default plugin, but it does not provide an inline implementation.
[        ]            Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: windows: default_package: file_picker` or add an inline implementation to file_picker via `platforms: windows:` `pluginClass` or `dartPluginClass`.
[        ] [  +12 ms] gen_dart_plugin_registrant: Complete
[        ] [        ] kernel_snapshot_program: Starting due to {}
[   +2 ms] [   +5 ms] /nix/store/z1za1hwdayfcl4pgk6cxq2nmvy2bk5fi-flutter-wrapped-3.27.1-sdk-links/bin/cache/dart-sdk/bin/dartaotruntime /nix/store/z1za1hwdayfcl4pgk6cxq2nmvy2bk5fi-flutter-wrapped-3.27.1-sdk-links/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root /nix/store/z1za1hwdayfcl4pgk6cxq2nmvy2bk5fi-flutter-wrapped-3.27.1-sdk-links/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --delete-tostring-package-uri=dart:ui --delete-tostring-package-uri=package:flutter --aot --tfa --target-os linux --packages /build/source/.dart_tool/package_config.json --output-dill /build/source/.dart_tool/flutter_build/e50b9596a524fb6e714d2c428e5aea8d/program.dill --depfile /build/source/.dart_tool/flutter_build/e50b9596a524fb6e714d2c428e5aea8d/kernel_snapshot_program.d --source file:///build/source/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///build/source/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error package:quickgui/main.dart
[        ] [+2760 ms] /nix/store/7iy1sgjphvl92c8xniyza9z0c346hj26-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1919:39: Error: Method not found: 'SchemeRainbow'.
[        ] [        ]       DynamicSchemeVariant.rainbow => SchemeRainbow(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
[        ] [        ]                                       ^^^^^^^^^^^^^
[        ] [        ] /nix/store/7iy1sgjphvl92c8xniyza9z0c346hj26-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1920:42: Error: Method not found: 'SchemeFruitSalad'.
[        ] [        ]       DynamicSchemeVariant.fruitSalad => SchemeFruitSalad(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
[        ] [        ]                                          ^^^^^^^^^^^^^^^^
[        ] [+4433 ms] Persisting file store
[        ] [   +1 ms] Done persisting file store
[        ] [   +1 ms] Target kernel_snapshot_program failed: Exception
[        ]            #0      KernelSnapshotProgram.build (package:flutter_tools/src/build_system/targets/common.dart:274:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:891:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:520:21)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:829:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart:520:21)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:829:32)
[        ]            <asynchronous suspension>
[        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart:520:21)
[   +2 ms]            <asynchronous suspension>
[        ]            #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:829:32)
[        ]            <asynchronous suspension>
[        ]            #8      Future.wait.<anonymous closure> (dart:async/future.dart:520:21)
[        ]            <asynchronous suspension>
[        ]            #9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:829:32)
[        ]            <asynchronous suspension>
[        ]            #10     Future.wait.<anonymous closure> (dart:async/future.dart:520:21)
[        ]            <asynchronous suspension>
[        ]            #11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:829:32)
[        ]            <asynchronous suspension>
[        ]            #12     Future.wait.<anonymous closure> (dart:async/future.dart:520:21)
[        ]            <asynchronous suspension>
[        ]            #13     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:829:32)
[        ]            <asynchronous suspension>
[        ]            #14     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:651:16)
[        ]            <asynchronous suspension>
[        ]            #15     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:329:32)
[        ]            <asynchronous suspension>
[        ]            #16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
[        ]            <asynchronous suspension>
[        ]            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #18     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:417:9)
[        ]            <asynchronous suspension>
[        ]            #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
[        ]            <asynchronous suspension>
[        ]            #22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
[        ]            <asynchronous suspension>
[        ]            #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #24     main (package:flutter_tools/executable.dart:94:3)
[        ]            <asynchronous suspension>
[        ] [   +4 ms] "flutter assemble" took 7,563ms.
[        ] [   +1 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:346:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:417:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:94:3)
[        ]            <asynchronous suspension>
[        ] [        ] Running 1 shutdown hook
[        ] [        ] Shutdown hooks complete
[        ] [   +1 ms] exiting with code 1
[        ] ninja: build stopped: subcommand failed.
[   +7 ms] Building Linux application... (completed in 9.2s)
[        ] "flutter linux" took 9,494ms.
[   +1 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:210:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:83:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:87:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:417:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[   +2 ms] exiting with code 1
error: builder for '/nix/store/q7c6p0y139f4srhgz2gsjv22ifdh5mrg-quickgui-1.2.10-unstable-2024-12-30.drv' failed with exit code 1;
       last 25 log lines:
       >            #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:87:5)
       >            <asynchronous suspension>
       >            #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
       >            <asynchronous suspension>
       >            #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
       >            <asynchronous suspension>
       >            #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
       >            <asynchronous suspension>
       >            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:417:9)
       >            <asynchronous suspension>
       >            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
       >            <asynchronous suspension>
       >            #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
       >            <asynchronous suspension>
       >            #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
       >            <asynchronous suspension>
       >            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
       >            <asynchronous suspension>
       >            #12     main (package:flutter_tools/executable.dart:94:3)
       >            <asynchronous suspension>
       >            
       >            
       > [        ] Running 1 shutdown hook
       > [        ] Shutdown hooks complete
       > [   +2 ms] exiting with code 1
```
