### ISSUE TITLE
firefly-iii & firefly-iii-data-importer NixOS Module fail to start

### ISSUE THREAD

**Issue by kai-tub** [NixOS/nixpkgs#342285]
### Describe the bug

Hey :wave: 
I have been running the firefly-iii and firefly-iii-data-importer service for some time now but after updating last night, I receive the following error messages from the services:

<details>
  <summary>Firefly-iii</summary>

```
Sep 16 14:01:59 nixos-workstation systemd[1]: Starting firefly-iii-setup.service...
░░ Subject: A start job for unit firefly-iii-setup.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit firefly-iii-setup.service has begun execution.
░░ 
░░ The job identifier is 221945.
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910422]: Warning: require(/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): Failed to open stream: No such file or directory in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910422]: Fatal error: Uncaught Error: Failed opening required '/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/nix/store/myrj28a2cncjaxdv8q33fgqsm51hgrbr-php-8.3.11/lib/php') in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php:41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910422]: Stack trace:
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910422]: #0 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php(45): {closure}('0e6d7bf4a5811bf...', '/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910422]: #1 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/autoload.php(25): ComposerAutoloaderInita3648ab093343dd83bf7e728034ab46c::getLoader()
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910422]: #2 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/artisan(18): require('/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910422]: #3 {main}
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910422]:   thrown in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910471]: Warning: require(/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): Failed to open stream: No such file or directory in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910471]: Fatal error: Uncaught Error: Failed opening required '/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/nix/store/myrj28a2cncjaxdv8q33fgqsm51hgrbr-php-8.3.11/lib/php') in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php:41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910471]: Stack trace:
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910471]: #0 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php(45): {closure}('0e6d7bf4a5811bf...', '/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910471]: #1 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/autoload.php(25): ComposerAutoloaderInita3648ab093343dd83bf7e728034ab46c::getLoader()
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910471]: #2 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/artisan(18): require('/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910471]: #3 {main}
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910471]:   thrown in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910503]: Warning: require(/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): Failed to open stream: No such file or directory in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910503]: Fatal error: Uncaught Error: Failed opening required '/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/nix/store/myrj28a2cncjaxdv8q33fgqsm51hgrbr-php-8.3.11/lib/php') in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php:41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910503]: Stack trace:
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910503]: #0 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php(45): {closure}('0e6d7bf4a5811bf...', '/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910503]: #1 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/autoload.php(25): ComposerAutoloaderInita3648ab093343dd83bf7e728034ab46c::getLoader()
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910503]: #2 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/artisan(18): require('/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910503]: #3 {main}
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910503]:   thrown in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910534]: Warning: require(/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): Failed to open stream: No such file or directory in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910534]: Fatal error: Uncaught Error: Failed opening required '/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/nix/store/myrj28a2cncjaxdv8q33fgqsm51hgrbr-php-8.3.11/lib/php') in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php:41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910534]: Stack trace:
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910534]: #0 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php(45): {closure}('0e6d7bf4a5811bf...', '/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910534]: #1 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/autoload.php(25): ComposerAutoloaderInita3648ab093343dd83bf7e728034ab46c::getLoader()
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910534]: #2 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/artisan(18): require('/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910534]: #3 {main}
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910534]:   thrown in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910548]: Warning: require(/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): Failed to open stream: No such file or directory in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910548]: Fatal error: Uncaught Error: Failed opening required '/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/nix/store/myrj28a2cncjaxdv8q33fgqsm51hgrbr-php-8.3.11/lib/php') in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php:41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910548]: Stack trace:
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910548]: #0 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php(45): {closure}('0e6d7bf4a5811bf...', '/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910548]: #1 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/autoload.php(25): ComposerAutoloaderInita3648ab093343dd83bf7e728034ab46c::getLoader()
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910548]: #2 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/artisan(18): require('/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910548]: #3 {main}
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910548]:   thrown in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910549]: Warning: require(/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): Failed to open stream: No such file or directory in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910549]: Fatal error: Uncaught Error: Failed opening required '/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/nix/store/myrj28a2cncjaxdv8q33fgqsm51hgrbr-php-8.3.11/lib/php') in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php:41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910549]: Stack trace:
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910549]: #0 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php(45): {closure}('0e6d7bf4a5811bf...', '/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910549]: #1 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/autoload.php(25): ComposerAutoloaderInita3648ab093343dd83bf7e728034ab46c::getLoader()
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910549]: #2 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/artisan(18): require('/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910549]: #3 {main}
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910549]:   thrown in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910552]: Warning: require(/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): Failed to open stream: No such file or directory in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910552]: Fatal error: Uncaught Error: Failed opening required '/nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/nix/store/myrj28a2cncjaxdv8q33fgqsm51hgrbr-php-8.3.11/lib/php') in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php:41
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910552]: Stack trace:
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910552]: #0 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php(45): {closure}('0e6d7bf4a5811bf...', '/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910552]: #1 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/autoload.php(25): ComposerAutoloaderInita3648ab093343dd83bf7e728034ab46c::getLoader()
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910552]: #2 /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/artisan(18): require('/nix/store/ayvf...')
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910552]: #3 {main}
Sep 16 14:01:59 nixos-workstation fb973hnqpgady9a6kklrbgwdcq2pvw38-firefly-iii-maintenance.sh[2910552]:   thrown in /nix/store/ayvfgsw3j411f0haxfx6iv4ib2hxdpl0-firefly-iii-6.1.19/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation systemd[1]: firefly-iii-setup.service: Main process exited, code=exited, status=255/EXCEPTION
░░ Subject: Unit process exited
```

</details>

<details>
<summary>Data importer</summary>

```
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910551]: Warning: require(/nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): Failed to open stream: No such file or directory in /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910551]: Fatal error: Uncaught Error: Failed opening required '/nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/nix/store/myrj28a2cncjaxdv8q33fgqsm51hgrbr-php-8.3.11/lib/php') in /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php:41
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910551]: Stack trace:
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910551]: #0 /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php(45): {closure}('0e6d7bf4a5811bf...', '/nix/store/lpn9...')
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910551]: #1 /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/autoload.php(25): ComposerAutoloaderInit5e97d14bc220a6acc1d0cdb90b71ee13::getLoader()
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910551]: #2 /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/artisan(18): require('/nix/store/lpn9...')
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910551]: #3 {main}
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910551]:   thrown in /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910553]: Warning: require(/nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): Failed to open stream: No such file or directory in /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910553]: Fatal error: Uncaught Error: Failed opening required '/nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/nix/store/myrj28a2cncjaxdv8q33fgqsm51hgrbr-php-8.3.11/lib/php') in /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php:41
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910553]: Stack trace:
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910553]: #0 /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php(45): {closure}('0e6d7bf4a5811bf...', '/nix/store/lpn9...')
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910553]: #1 /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/autoload.php(25): ComposerAutoloaderInit5e97d14bc220a6acc1d0cdb90b71ee13::getLoader()
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910553]: #2 /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/artisan(18): require('/nix/store/lpn9...')
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910553]: #3 {main}
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910553]:   thrown in /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910557]: Warning: require(/nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): Failed to open stream: No such file or directory in /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910557]: Fatal error: Uncaught Error: Failed opening required '/nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/nix/store/myrj28a2cncjaxdv8q33fgqsm51hgrbr-php-8.3.11/lib/php') in /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php:41
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910557]: Stack trace:
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910557]: #0 /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php(45): {closure}('0e6d7bf4a5811bf...', '/nix/store/lpn9...')
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910557]: #1 /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/autoload.php(25): ComposerAutoloaderInit5e97d14bc220a6acc1d0cdb90b71ee13::getLoader()
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910557]: #2 /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/artisan(18): require('/nix/store/lpn9...')
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910557]: #3 {main}
Sep 16 14:01:59 nixos-workstation 6vlcbk07w12icf8ffakzw8d6ya1qq84j-data-importer-maintenance.sh[2910557]:   thrown in /nix/store/lpn928zhx0i9ky662m0vsyqy38pqllyh-firefly-iii-data-importer-1.5.5/vendor/composer/autoload_real.php on line 41
Sep 16 14:01:59 nixos-workstation systemd[1]: firefly-iii-data-importer-setup.service: Main process exited, code=exited, status=255/EXCEPTION
░░ Subject: Unit process exited
```

</details>

### Steps To Reproduce
1. Update to current nixpkgs version and use the `service.firefly-iii` and `service.firefly-iii-data-importer` nixos modules.

### Expected behavior
Successfull startup

### Additional context
I have reverted my firefly-iii package by using the previous commit from `github:NixOS/nixpkgs?ref=ad0111043c09f7d0f6b9f039882cbf350d4f7d49` and that seems to fix the problem.

But reverting the data-importer does not make it functional again.

### Notify maintainers

@savyajha @patrickdag

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.10.3, NixOS, 24.11 (Vicuna), 24.11.20240915.9299cdf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.3`
 - nixpkgs: `/nix/store/i6ljzmbd9jk67xnxlwqs7kv3wap56j05-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kai-tub** [comment]
Ah, never mind. I got confused with firefly-iii and firefly-iii-data-importer error messages.
One can simply overlay `firefly-iii-data-importer` with the git commit from the previous version and it works.
Sorry for the noise :bow:

**Comment by kai-tub** [comment]
Yep, works! :tada:

**Comment by savyajha** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/343900
