### ISSUE TITLE
home-assistant: Setup failed for dependencies: ['map']

### ISSUE THREAD

**Issue by luochen1990** [NixOS/nixpkgs#342726]
### Describe the bug

```
9-18 14:10:03 home systemd[1]: Started Home Assistant.
9-18 14:10:08 home hass[245768]: 2024-09-18 14:10:08.242 WARNING (MainThread) [homeassistant.bootstrap] Skipping pip installation of required modules. This may cause issues
9-18 14:10:08 home hass[245768]: 2024-09-18 14:10:08.309 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
9-18 14:10:08 home hass[245768]: 2024-09-18 14:10:08.606 WARNING (MainThread) [aiohttp_fast_zlib] zlib_ng and isal are not available, falling back to zlib, performance will be degraded.
9-18 14:10:09 home hass[245768]: 2024-09-18 14:10:09.802 ERROR (MainThread) [homeassistant.setup] Error during setup of component map
9-18 14:10:09 home hass[245768]: Traceback (most recent call last):
9-18 14:10:09 home hass[245768]:   File "/nix/store/xhyzp75p6szxhqxscqbdjphlkwyv3biy-homeassistant-2024.9.1/lib/python3.12/site-packages/homeassistant/setup.py", line 416, in _async_setup_component
9-18 14:10:09 home hass[245768]:     result = await task
9-18 14:10:09 home hass[245768]:              ^^^^^^^^^^
9-18 14:10:09 home hass[245768]:   File "/nix/store/xhyzp75p6szxhqxscqbdjphlkwyv3biy-homeassistant-2024.9.1/lib/python3.12/site-packages/homeassistant/components/map/__init__.py", line 49, in async_setup
9-18 14:10:09 home hass[245768]:     await _create_map_dashboard(hass)
9-18 14:10:09 home hass[245768]:   File "/nix/store/xhyzp75p6szxhqxscqbdjphlkwyv3biy-homeassistant-2024.9.1/lib/python3.12/site-packages/homeassistant/components/lovelace/__init__.py", line 282, in _create_map_dashboard
9-18 14:10:09 home hass[245768]:     await dashboards_collection.async_create_item(
9-18 14:10:09 home hass[245768]:   File "/nix/store/xhyzp75p6szxhqxscqbdjphlkwyv3biy-homeassistant-2024.9.1/lib/python3.12/site-packages/homeassistant/helpers/collection.py", line 316, in async_create_item
9-18 14:10:09 home hass[245768]:     validated_data = await self._process_create_data(data)
9-18 14:10:09 home hass[245768]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9-18 14:10:09 home hass[245768]:   File "/nix/store/xhyzp75p6szxhqxscqbdjphlkwyv3biy-homeassistant-2024.9.1/lib/python3.12/site-packages/homeassistant/components/lovelace/dashboard.py", line 283, in _process_create_data
9-18 14:10:09 home hass[245768]:     raise vol.Invalid("Panel url path needs to be unique")
9-18 14:10:09 home hass[245768]: voluptuous.error.Invalid: Panel url path needs to be unique
9-18 14:10:09 home hass[245768]: 2024-09-18 14:10:09.935 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'default_config'. Setup failed for dependencies: ['map']
9-18 14:10:09 home hass[245768]: 2024-09-18 14:10:09.936 ERROR (MainThread) [homeassistant.setup] Setup failed for 'default_config': Could not setup dependencies: map
9-18 14:10:40 home hass[245768]: 2024-09-18 14:10:40.200 ERROR (MainThread) [homeassistant.components.homeassistant_alerts.coordinator] Timeout fetching homeassistant_alerts data
```

### Notify maintainers

@Princemachiavelli 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

- system: `"x86_64-linux"`
- host os: `Linux 6.11.0, NixOS, 24.11 (Vicuna), 24.11.20240914.6ca042d`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.24.6`
- nixpkgs: `/nix/store/asmpdfb2aixsjl95a557c269ybzybjm3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndreasBVB** [comment]
Fixed this by deleting the existing Map dashboard and restart HomeAssistant.

**Comment by luochen1990** [comment]
> Fixed this by deleting the existing Map dashboard and restarting HomeAssistant.

@AndreasBVB Could you please tell me the specific path to delete? Because I'm basically starting from a fresh installation (even though I did install it once before) and encountering this error

**Comment by AndreasBVB** [comment]
> > Fixed this by deleting the existing Map dashboard and restarting HomeAssistant.
> 
> @AndreasBVB Could you please tell me the specific path to delete? Because I'm basically starting from a fresh installation (even though I did install it once before) and encountering this error

In UI, upper right corner: edit icon (pen), then manage dashboards

**Comment by luochen1990** [comment]
@AndreasBVB 

Here is my config:

```nix
    services.home-assistant.lovelaceConfigWritable = false;
    services.home-assistant.lovelaceConfig = {
      title = "My Awesome Home (111)";
      views = [ {
        title = "Example (222)";
        cards = [ {
          type = "markdown";
          title = "Lovelace (333)";
          content = "Welcome to your **Lovelace UI**. (444)";
        } ];
      } ];
    };
```

Seems like there is nothing to delete for me..

**Comment by AndreasBVB** [comment]
> @AndreasBVB
> 
> Here is my config:
> 
> ```nix
>     services.home-assistant.lovelaceConfigWritable = false;
>     services.home-assistant.lovelaceConfig = {
>       title = "My Awesome Home (111)";
>       views = [ {
>         title = "Example (222)";
>         cards = [ {
>           type = "markdown";
>           title = "Lovelace (333)";
>           content = "Welcome to your **Lovelace UI**. (444)";
>         } ];
>       } ];
>     };
> ```
> 
> Seems like there is nothing to delete for me..

No it's not in any config file. Go to this link https://www.home-assistant.io/getting-started/onboarding_dashboard/
and find this image:
https://www.home-assistant.io/images/dashboards/dashboard-manage-02.png
Follow those instructions to kill the existing "Map" dashboard, then restart the HomeAssistant.
