### ISSUE TITLE
`ruby_3_3`: LoadError: linked to incompatible libruby-3.3.4.so.3.3

### ISSUE THREAD

**Issue by UlyssesZh** [NixOS/nixpkgs#343922]
### Describe the bug
There is fatal error happening when using bundler with `ruby_3_3`.

### Steps To Reproduce

```shell
nix-shell -p ruby_3_3 --run 'bundle init && bundle add stringio'
```

<details><summary>Output</summary>

````md
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
LoadError: linked to incompatible /nix/store/xm0j3wwkm75j9vv40d5qb8hwz50rmc8s-ruby-3.3.4/lib/libruby-3.3.4.so.3.3 - /home/ulysses/.local/share/gem/ruby/3.3.0/gems/stringio-3.1.1/lib/stringio.so
  <internal:/nix/store/qf84ji7b4zh7338a7yprx2q03k2qfa72-ruby-3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          <internal:/nix/store/qf84ji7b4zh7338a7yprx2q03k2qfa72-ruby-3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
          /nix/store/qf84ji7b4zh7338a7yprx2q03k2qfa72-ruby-3.3.5/lib/ruby/3.3.0/rubygems/remote_fetcher.rb:78:in `initialize'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/fetcher.rb:211:in `new'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/fetcher.rb:211:in `gem_remote_fetcher'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/fetcher.rb:232:in `block in fetchers'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/fetcher.rb:232:in `map'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/fetcher.rb:232:in `fetchers'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/fetcher.rb:205:in `api_fetcher?'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/source/rubygems.rb:400:in `select'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/source/rubygems.rb:400:in `api_fetchers'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/source/rubygems.rb:405:in `block in remote_specs'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/index.rb:9:in `build'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/source/rubygems.rb:404:in `remote_specs'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/source/rubygems.rb:138:in `specs'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:41:in `block in setup_solver'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:256:in `all_versions_for'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:54:in `block in setup_solver'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:360:in `filtered_versions_for'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:58:in `block in setup_solver'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:450:in `select_sorted_versions'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:426:in `block in prepare_dependencies'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:420:in `each'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:420:in `map'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:420:in `prepare_dependencies'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:63:in `setup_solver'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/resolver.rb:28:in `start'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/definition.rb:637:in `start_resolution'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/definition.rb:306:in `resolve'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/definition.rb:179:in `resolve_remotely!'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/injector.rb:44:in `block in inject'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/settings.rb:158:in `temporary'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/injector.rb:29:in `inject'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/injector.rb:9:in `inject'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/cli/add.rb:30:in `inject_dependencies'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/cli/add.rb:16:in `run'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/cli.rb:359:in `add'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/cli.rb:35:in `dispatch'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/cli.rb:29:in `start'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/exe/bundle:28:in `block in <top (required)>'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          /home/ulysses/.local/share/gem/ruby/3.3.0/gems/bundler-2.5.18/exe/bundle:20:in `<top (required)>'
          /home/ulysses/.local/share/gem/ruby/3.1.0/bin/bundle:25:in `load'
          /home/ulysses/.local/share/gem/ruby/3.1.0/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.5.18
  Platforms   ruby, x86_64-linux
Ruby          3.3.5p100 (2024-09-03 revision ef084cc8f4958c1b6e4ead99136631bef6d8ddba) [x86_64-linux]
  Full Path   /nix/store/qf84ji7b4zh7338a7yprx2q03k2qfa72-ruby-3.3.5/bin/ruby
  Config Dir  /nix/store/qf84ji7b4zh7338a7yprx2q03k2qfa72-ruby-3.3.5/etc
RubyGems      3.5.9
  Gem Home    /home/ulysses/.local/share/gem/ruby/3.3.0
  Gem Path    /nix/store/qf84ji7b4zh7338a7yprx2q03k2qfa72-ruby-3.3.5/lib/ruby/gems/3.3.0:/home/ulysses/.local/share/gem/ruby/3.3.0
  User Home   /home/ulysses
  User Path   /home/ulysses/.local/share/gem/ruby/3.3.0
  Bin Dir     /home/ulysses/.local/share/gem/ruby/3.3.0/bin
OpenSSL       
  Compiled    OpenSSL 3.0.14 4 Jun 2024
  Loaded      OpenSSL 3.0.14 4 Jun 2024
  Cert File   /etc/ssl/certs/ca-certificates.crt
  Cert Dir    /nix/store/0d6qbqbgq8vl0nb3fy6wi9gfn6j3023d-openssl-3.0.14/etc/ssl/certs
Tools         
  Git         2.44.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-08-26
Git SHA           c218aab519
Released Version  true
```

## Gemfile

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
```

### Gemfile.lock

```
<No /home/ulysses/test/test-bundler/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=linked+to+incompatible+%2Fnix%2Fstore%2Fxm0j3wwkm75j9vv40d5qb8hwz50rmc8s-ruby-3.3.4%2Flib%2Flibruby-3.3.4.so.3.3+-+%2Fhome%2Fulysses%2F.local%2Fshare%2Fgem%2Fruby%2F3.3.0%2Fgems%2Fstringio-3.1.1%2Flib%2Fstringio.so&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
````

</details>

### Expected behavior
Installs gem stringio.

### Additional context
`ruby_3_2` seems good. `ruby` fails due to #336736.

### Notify maintainers

@vrthra @manveru

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.111, NixOS, 24.05 (Uakari), 24.05.5197.944b2aea7f0a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
works for me 

```
nix-shell -p ruby_3_3 --run 'bundle init && bundle add stringio'
Writing new Gemfile to /home/kirillvr/Gemfile
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
```

i am on unstable

```
nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.11, NixOS, 24.11 (Vicuna), 24.11.20240921.40540dd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - nixpkgs: `/nix/store/yqnfkr9pwy2kja1qnvinzlggc6pi7vyh-source`
```

**Comment by UlyssesZh** [comment]
Ha, then this seems to be only a problem with NixOS 24.05. I tried the master branch, and it worked too.

**Comment by UlyssesZh** [comment]
This issue happens again with master branch. Reproducible for `ruby_3_3` and `ruby_3_2`. Not reproduced for `ruby_3_1` and `ruby_3_4`.

**Comment by kirillrdy** [comment]
@UlyssesZh can you remove you $HOME/.local/gem and try again

**Comment by UlyssesZh** [comment]
You mean `~/.local/share/gem` right? Yes it is good now. Thank you.

I think it is because some files there are linked to libraries that no longer exist in /nix/store after a GC.

**Comment by kirillrdy** [comment]
yes, when you use `bundle install` for gems with C extensions it will compile gem at the time of installation, and that will point to /nix/store

if you use gems built by bundix you not going to have that issue, but we do sometimes need to run bundle install to update Gemfile.lock , so just need to be aware of this
