### ISSUE TITLE
nixos/nextjs-ollama-llm-ui: Failed to write image to cache ... Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mschwaig** [NixOS/nixpkgs#344316]
### Describe the bug

The `nextjs-ollama-llm-ui` package is built using the next.js framework.
At least when using the NixOS module, it seems to use next.js to cache something in the project directory, which when using Nix is of course inside `/nix/store`.

To me it looks like this completely breaks at least `services.nextjs-ollama-llm-ui`:

```
Sep 19 00:26:01 hydralisk nextjs-ollama-llm-ui[168012]:   ▲ Next.js 14.2.3
Sep 19 00:26:01 hydralisk nextjs-ollama-llm-ui[168012]:   - Local:        http://127.0.0.1:8080
Sep 19 00:26:01 hydralisk nextjs-ollama-llm-ui[168012]:   - Network:      http://127.0.0.1:8080
Sep 19 00:26:01 hydralisk nextjs-ollama-llm-ui[168012]:  ✓ Starting...
Sep 19 00:26:01 hydralisk nextjs-ollama-llm-ui[168012]:  ✓ Ready in 46ms
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:  ⨯ Failed to write image to cache sBmRGIurxiwgDA8-qXZHHXC3v5cqpuaAip-jNCD8zC8= Error: ENOENT: no such file or directory, mkdir '/nix/store/zrnk64rkf4nlsvab9>
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:     at async Object.mkdir (node:internal/fs/promises:858:10)
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:     at async writeToCacheDir (/nix/store/zrnk64rkf4nlsvab9700n9z04l1wyyng-nextjs-ollama-llm-ui-1.0.1/share/homepage/node_modules/next/dist/server/image-opti>
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:     at async ImageOptimizerCache.set (/nix/store/zrnk64rkf4nlsvab9700n9z04l1wyyng-nextjs-ollama-llm-ui-1.0.1/share/homepage/node_modules/next/dist/server/im>
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:     at async /nix/store/zrnk64rkf4nlsvab9700n9z04l1wyyng-nextjs-ollama-llm-ui-1.0.1/share/homepage/node_modules/next/dist/server/response-cache/index.js:121>
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:     at async /nix/store/zrnk64rkf4nlsvab9700n9z04l1wyyng-nextjs-ollama-llm-ui-1.0.1/share/homepage/node_modules/next/dist/lib/batcher.js:45:32 {
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:   errno: -2,
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:   code: 'ENOENT',
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:   syscall: 'mkdir',
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:   path: '/nix/store/zrnk64rkf4nlsvab9700n9z04l1wyyng-nextjs-ollama-llm-ui-1.0.1/share/homepage/.next/cache'
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]: }
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:  ⨯ Failed to write image to cache B0Z3FnWKAAGjZHJa171iie+KPfLVSPJajqE+M39emDk= Error: ENOENT: no such file or directory, mkdir '/nix/store/zrnk64rkf4nlsvab9>
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:     at async Object.mkdir (node:internal/fs/promises:858:10)
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:     at async writeToCacheDir (/nix/store/zrnk64rkf4nlsvab9700n9z04l1wyyng-nextjs-ollama-llm-ui-1.0.1/share/homepage/node_modules/next/dist/server/image-opti>
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:     at async ImageOptimizerCache.set (/nix/store/zrnk64rkf4nlsvab9700n9z04l1wyyng-nextjs-ollama-llm-ui-1.0.1/share/homepage/node_modules/next/dist/server/im>
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:     at async /nix/store/zrnk64rkf4nlsvab9700n9z04l1wyyng-nextjs-ollama-llm-ui-1.0.1/share/homepage/node_modules/next/dist/server/response-cache/index.js:121>
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:     at async /nix/store/zrnk64rkf4nlsvab9700n9z04l1wyyng-nextjs-ollama-llm-ui-1.0.1/share/homepage/node_modules/next/dist/lib/batcher.js:45:32 {
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:   errno: -2,
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:   code: 'ENOENT',
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:   syscall: 'mkdir',
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]:   path: '/nix/store/zrnk64rkf4nlsvab9700n9z04l1wyyng-nextjs-ollama-llm-ui-1.0.1/share/homepage/.next/cache'
Sep 19 00:26:06 hydralisk nextjs-ollama-llm-ui[168012]: }
```

Is anybody actually running this successfully?
It seems like the cache directory might not even be configurable: https://github.com/vercel/next.js/discussions/58864

### Steps To Reproduce

1. enable the module like so
```
services.nextjs-ollama-llm-ui = {
  enable = true;
  port = 8080;
};
```

### Expected behavior

I would expect the module to just run with some minimal configuration.

### Metadata

```console
mschwaig@hydralisk ~/nixos-config (main)> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.10, NixOS, 24.11 (Vicuna), 24.11.20240916.99dc878`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-21.03pre261422.1a57d96edd1"`
 - nixpkgs: `/nix/store/cjz8w4dgc3rd2n3dqv5c208vygndjyba-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by womfoo** [comment]
@mschwaig I hit this too. See #347856 for fix
