### ISSUE TITLE
protonvpn-gui: Fails to start, AttributeError

### ISSUE THREAD

**Issue by chitoroagad** [NixOS/nixpkgs#344913]
### Describe the bug
Trying to run the app anyway produces a Python AttrubuteError.

### Steps To Reproduce
1. Run `protonvpn-app` from terminal

### Expected behavior
Opens that app.

### Additional context
Python Traceback:
```
Traceback (most recent call last):
  File "/nix/store/si65f15j3kp2jr75d45zg90rwgd5ajnw-protonvpn-gui-4.4.4/bin/..protonvpn-app-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/si65f15j3kp2jr75d45zg90rwgd5ajnw-protonvpn-gui-4.4.4/lib/python3.12/site-packages/proton/vpn/app/gtk/__main__.py", line 34, in main
    controller = Controller.get(executor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/si65f15j3kp2jr75d45zg90rwgd5ajnw-protonvpn-gui-4.4.4/lib/python3.12/site-packages/proton/vpn/app/gtk/controller.py", line 61, in get
    executor.submit(controller.initialize_vpn_connector).result()
  File "/nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/nix/store/si65f15j3kp2jr75d45zg90rwgd5ajnw-protonvpn-gui-4.4.4/lib/python3.12/site-packages/proton/vpn/app/gtk/controller.py", line 94, in initialize_vpn_connector
    self._connector = await self._api.get_vpn_connector()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rvz6xapj2gw1zdbmw2jgv9z87lni1av5-python3.12-proton-vpn-api-core-0.32.2/lib/python3.12/site-packages/proton/vpn/core/api.py", line 68, in get_vpn_connector
    vpn_connector = await VPNConnector.get(credentials, settings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rvz6xapj2gw1zdbmw2jgv9z87lni1av5-python3.12-proton-vpn-api-core-0.32.2/lib/python3.12/site-packages/proton/vpn/connection/vpnconnector.py", line 61, in get
    await connector.initialize_state()
  File "/nix/store/rvz6xapj2gw1zdbmw2jgv9z87lni1av5-python3.12-proton-vpn-api-core-0.32.2/lib/python3.12/site-packages/proton/vpn/connection/vpnconnector.py", line 158, in initialize_state
    state = await self._get_current_connection_state()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rvz6xapj2gw1zdbmw2jgv9z87lni1av5-python3.12-proton-vpn-api-core-0.32.2/lib/python3.12/site-packages/proton/vpn/connection/vpnconnector.py", line 147, in _get_current_connection_state
    current_connection = await VPNConnection.get_current_connection()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rvz6xapj2gw1zdbmw2jgv9z87lni1av5-python3.12-proton-vpn-api-core-0.32.2/lib/python3.12/site-packages/proton/vpn/connection/vpnconnection.py", line 205, in get_current_connection
    current_connection = backend.get_persisted_connection(persisted_parameters)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'LinuxNetworkManager' has no attribute 'get_persisted_connection'. Did you mean: 'get_current_connection'?

```

### Notify maintainers

@SebTM 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.0, NixOS, 24.11 (Vicuna), 24.11.20240923.30439d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - nixpkgs: `/nix/store/p2hby44a0qzrnd1vxcpcgfav6160rmcv-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SebTM** [comment]
https://github.com/NixOS/nixpkgs/pull/343204#issuecomment-2377962465

**Comment by chitoroagad** [comment]
> https://github.com/NixOS/nixpkgs/pull/343204#issuecomment-2377962465

Thanks 👍
