### ISSUE TITLE
openshot-qt does not start: ModuleNotFoundError: No module named 'openshot'

### ISSUE THREAD

**Issue by raas** [NixOS/nixpkgs#345314]
### Steps To Reproduce
1. nix-shell -p openshot-qt
2. openshot-qt
3. ModuleNotFoundError: No module named 'openshot'

### Expected behavior

openshot should start

### Additional context

```bash
$ openshot-qt 
Loaded modules from: /nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt
INFO sentry: No sentry_sdk module detected (error reporting is disabled)
INFO app: ------------------------------------------------
INFO app:             Sun Sep 29 17:51:16 2024            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
ModuleNotFoundError: No module named 'openshot'
Traceback (most recent call last):
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/launch.py", line 202, in main
    app = OpenShotApp(argv)
          ^^^^^^^^^^^^^^^^^
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
ModuleNotFoundError: No module named 'openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/bin/.openshot-qt-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/launch.py", line 204, in main
    app.show_errors()
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Sun Sep 29 17:51:16 2024            
INFO app: ================================================
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.11 (Vicuna), 24.11.20240926.1925c60`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/fpivx4sjcp2vk4rp9nhliln5cwcp3kc6-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MMesch** [comment]
Did you find an older version that works?

**Comment by raas** [comment]
I haven't tried. I'm fairly new to nixos, what would be a quick way to bisect versions?

**Comment by MMesch** [comment]
I used this script before to do a date based bisect:

```
startdate=$1
enddate=$2

# date format is 'YYYY-MM-DD'
c1=$(git log --before $startdate --format='format:%H' | head -n1)
c2=$(git log --after $enddate --format='format:%H' | head -n1)

echo $c1
echo $c2

git bisect start
git bisect bad $c2
git bisect good $c1
git bisect run nix run .#openshot-qt
```

for the bad commit that should work fine but not sure whether you need a slightly different command line option for the good so that it doesn't hang when it works. I don't have time, compute and disk space to do it :\ 

Also, I don't really understand where the `openshot` library comes from. Is it from `libopenshot` or is it within the package?

Maybe @AndersonTorres knows better since he is tagged as maintainer.

**Comment by MMesch** [comment]
@raas . I found a good version in latest stable:

`nix run github:nixos/nixpkgs/nixos-24.05#openshot-qt` << this one works for me. Does it work for you?

**Comment by raas** [comment]
@MMesch the version from stable does indeed work, thank you!

**Comment by gepbird** [comment]
I started bisecting it but ran into a staging merge.
Known good commit: fa4b81d8e9ad1f7b35c9f2cdb41318e3487eaf9a
Known bad commit: 149a15141ad00c1b525ac02dacdb526b62c53e50
Diff: https://github.com/nixos/nixpkgs/compare/fa4b81d8e9ad1f7b35c9f2cdb41318e3487eaf9a...149a15141ad00c1b525ac02dacdb526b62c53e50

cc @AndersonTorres as the package maintainer

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/pull/404562
