### ISSUE TITLE
Openshot-qt not working

### ISSUE THREAD

**Issue by MMesch** [NixOS/nixpkgs#345591]
### Describe the bug

`nix run nixpkgs#openshot-qt` fails with

```
➜ nix run nixpkgs#openshot-qt
Loaded modules from: /nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt
INFO sentry: No sentry_sdk module detected (error reporting is disabled)
INFO app: ------------------------------------------------
INFO app:             Mon Sep 30 22:03:48 2024            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
ModuleNotFoundError: No module named 'openshot'
Traceback (most recent call last):
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/launch.py", line 202, in main
    app = OpenShotApp(argv)
          ^^^^^^^^^^^^^^^^^
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/classes/app.py", line 100, in __init__
    from classes import settings, project_data, updates, sentry
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/classes/project_data.py", line 48, in <module>
    import openshot
ModuleNotFoundError: No module named 'openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/bin/.openshot-qt-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/gpfhhd1d5sbxgx7j6162f6k920rjbff3-openshot-qt-3.2.1/lib/python3.11/site-packages/openshot_qt/launch.py", line 204, in main
    app.show_errors()
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Mon Sep 30 22:03:48 2024            
INFO app: ================================================
```

It seems the culprit is:

```
import openshot
ModuleNotFoundError: No module named 'openshot'`
```

### Steps To Reproduce

1.  `nix run nixpkgs#openshot-qt`

### Notify maintainers

@AndersonTorres 

### Metadata

`nix registry list` shows

```
➜ nix registry list
system flake:nixpkgs path:/nix/store/fpivx4sjcp2vk4rp9nhliln5cwcp3kc6-source?lastModified=1727348695&narHash=sha256-J%2BPeFKSDV%2BpHL7ukkfpVzCOO7mBSrrpJ3svwBFABbhI%3D&rev=1925c603f17fc89f4c8f6bf6f631a802ad85d784
```

```
➜ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.11 (Vicuna), 24.11.20240926.1925c60`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.8`
...
 - nixpkgs: `/etc/channels/nixpkgs`
 -
```

**Comment by MMesch** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/345314
