### ISSUE TITLE
pkgs.testers.runNixOSTest failure (OSError: AF_UNIX path too long) when test name is "long" on macOS

### ISSUE THREAD

**Issue by krostar** [NixOS/nixpkgs#345911]
### Describe the bug
Hello !

I'm playing with `pkgs.testers.runNixOSTest` on `aarch64-darwin` system.

Here is the code I'm using
```nix
pkgs.testers.runNixOSTest {
  name = "foo";

  nodes = {
    machine = {};
  };

  testScript = ''
    machine.wait_for_unit("network-online.target")
    machine.succeed("ping -c 1 machine")
  '';
}
```

This code works, and I don't have no issues when running it using both system `aarch64-darwin`, and `aarch64-linux` (though builder).

But if I decide to name the test to equal something longer, like `name = "assert invalid configs are indeed invalid"`, then on `aarch64-darwin` the test is failing with following error: `OSError: AF_UNIX path too long`.

```console
Machine state will be reset. To keep it, pass --keep-vm-state
start all VLans
start vlan
running vlan (pid 49171; ctl /private/tmp/nix-build-vm-test-run-assert-invalid-configs-are-indeed-invalid.drv-0/vde1.ctl)
(finished: start all VLans, in 0.02 seconds)
Test will time out and terminate in 3600 seconds
run the VM test script
additionally exposed symbols:
    machine,
    vlan1,
    start_all, test_script, machines, vlans, driver, log, os, create_machine, subtest, run_tests, join_all, retry, serial_stdout_off, serial_stdout_on, polling_condition, Machine
machine: waiting for unit network-online.target
machine: waiting for the VM to finish booting
machine: starting vm
cleanup
(finished: cleanup, in 0.00 seconds)
Traceback (most recent call last):
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/__init__.py", line 146, in main
    driver.run_tests()
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 167, in run_tests
    self.test_script()
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 159, in test_script
    exec(self.tests, symbols, None)
  File "<string>", line 1, in <module>
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 374, in wait_for_unit
    retry(check_active, timeout)
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 129, in retry
    if fn(False):
       ^^^^^^^^^
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 355, in check_active
    state = self.get_unit_property(unit, "ActiveState", user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 404, in get_unit_property
    status, lines = self.systemctl(
                    ^^^^^^^^^^^^^^^
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 448, in systemctl
    return self.execute(f"systemctl {q}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 518, in execute
    self.connect()
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 824, in connect
    self.start()
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 1079, in start
    monitor_socket = create_socket(clear(self.monitor_path))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/78hf55kd2pf6pywqwbajbrxqd4zimrqr-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 1075, in create_socket
    s.bind(str(path))
OSError: AF_UNIX path too long
kill vlan (pid 49171)
```

the test still work using the builder (`aarch64-linux`).

### Expected behavior
Either no failures when using long names, or a warning/assert complaining about name length if length matters.

### Notify maintainers

@tfc helped me on NixOS tests on macOS months ago, I don't know who else to notify.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$> nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.5`
 - channels($USER): `"darwin, home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/2bgr2mxzslxfn3cd4ifjw7s68x91dki5-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tfc** [comment]
This might be related to the change that I once upstreamed to `nixos-rebuild`: https://github.com/NixOS/nixpkgs/blob/e46dc3b8343f627532ba881965b053d3bbec4235/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L438

The problem on macOS is often that you sometimes get extremely long tempdir prefixes out of `mktemp`, which *might* be the same problem here.

In `nixos-rebuild` this is solved by unsetting `TMPDIR` before calling `mktemp`.

Is this a helpful enough pointer for you to further debug this or do you need more assistance?

**Comment by tfc** [comment]
@zupo You are correctly setting `TMPDIR` *outside* the sandbox, but the command suggests that the test runs inside the sandbox. So this means you would have to set `TMPDIR` inside the sandbox.

This can be done e.g. with a quick override if you like to test it, like `test.overrideAttrs (_: { TMPDIR = "/tmp"; }` (nothing for production, but it might help as a quick fix before we fixed it for good)

@krostar plz note that you nowadays also need to start the network target, like [here](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/bittorrent.nix#L153).

**Comment by zupo** [comment]
I must be misunderstanding something:
 * nix-darwin does not use sandbox (IIC), so TMPDIR set before I run my command should work
 * inside the linux builder, `OSError: AF_UNIX path too long` shouldn't happen, as this is a macOS limitation.
 
Here's the full test case for completeness sake: https://github.com/ParetoSecurity/agent/blob/d6eede57f8608f3b9256442ed3dfe2d51afe8c17/test/integration/luks.nix

**Comment by tfc** [comment]
> * nix-darwin does not use sandbox (IIUC), so TMPDIR set before I run my command should work

That's correct, but the env variables of the build process (regardless of sandbox status) are reset anyway.

> * inside the linux builder, `OSError: AF_UNIX path too long` shouldn't happen, as this is a macOS limitation.

Does the error look like @krostar's excerpt? Because that error did not happen inside the Linux builder, it happened for the Python process that runs the test driver on macOS.

**Comment by zupo** [comment]
> > * nix-darwin does not use sandbox (IIUC), so TMPDIR set before I run my command should work
> 
> That's correct, but the env variables of the build process (regardless of sandbox status) are reset anyway.

Ahh, that makes sense then!

> > * inside the linux builder, `OSError: AF_UNIX path too long` shouldn't happen, as this is a macOS limitation.
> 
> Does the error look like @krostar's excerpt? Because that error did not happen inside the Linux builder, it happened for the Python process that runs the test driver on macOS.

Yep, looks like exactly that!

**Comment by zupo** [comment]
I started to get this error on Linux as well, so it doesn't seem to be nix-darwin specific. 

And, I now have a workaround: make the test `name` shorter. That's it. That's the fix.
