### ISSUE TITLE
Discourse fails to build (discourse-assets)

### ISSUE THREAD

**Issue by drupol** [NixOS/nixpkgs#346094]
### Describe the bug
Trying to deploy discourse on a machine and it fails while building `discourse`, more specifically at `discourse-assets`.

```
🚀 ℹ [deploy] [INFO] Building profile `system` for node `discourse`
error: builder for '/nix/store/5f8q37zl57558br2ls3aa06q7bx1ys86-discourse-assets-3.2.5.drv' failed with exit code 1;
       last 50 log lines:
       > babel-plugin-debug-macros@0.3.4 ✔
       > content-tag@1.2.2 ✔
       > ember-cli@5.0.0 ✔
       > ember-this-fallback@0.4.0 (1 deprecation-name) ✔
       > ember-this-fallback@0.4.0 (2 themes) ✔
       > ember-this-fallback@0.4.0 (3 exclude-strict-mode) ✔
       > virtual-dom@2.1.1 ✔
       > Done in 0.51s.
       > Waiting for Redis and PostgreSQL to be ready..
       > 2024-10-03 06:45:35.664 UTC [839] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 13.3.0, 64-bit
       > 2024-10-03 06:45:35.665 UTC [839] LOG:  listening on IPv4 address "127.0.0.1", port 5432
       > 2024-10-03 06:45:35.665 UTC [839] LOG:  listening on Unix socket "/build/.s.PGSQL.5432"
       > 2024-10-03 06:45:35.667 UTC [844] LOG:  database system was shut down at 2024-10-03 06:45:35 UTC
       > 2024-10-03 06:45:35.670 UTC [839] LOG:  database system is ready to accept connections
       > CREATE ROLE
       > CREATE DATABASE
       > CREATE EXTENSION
       > CREATE EXTENSION
       > rake aborted!
       > LoadError: /nix/store/3bjyslnparihj8jy605ghq7vn41q251c-discourse-ruby-env-3.2.5/lib/ruby/gems/3.2.0/extensions/x86_64-linux/3.2.0/mini_racer-0.8.0/mini_racer_extension.so: undefined symbol: _ZNK2v88TryCatch13HasTerminatedEv (LoadError)
       > /nix/store/capx3cdaj0c7329ysap16a69k8psraf7-ruby3.2-mini_racer-0.8.0/lib/ruby/gems/3.2.0/gems/mini_racer-0.8.0/lib/mini_racer.rb:14:in `load'
       > /nix/store/capx3cdaj0c7329ysap16a69k8psraf7-ruby3.2-mini_racer-0.8.0/lib/ruby/gems/3.2.0/gems/mini_racer-0.8.0/lib/mini_racer.rb:14:in `<main>'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:60:in `require'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:55:in `each'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:55:in `block in require'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:44:in `each'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:44:in `require'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler.rb:212:in `require'
       > /build/source/config/application.rb:69:in `<top (required)>'
       > <internal:/nix/store/lvvvw0rgwif46lzdyhb42d8xk2f5hkn6-ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
       > <internal:/nix/store/lvvvw0rgwif46lzdyhb42d8xk2f5hkn6-ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
       > /build/source/Rakefile:7:in `<top (required)>'
       > /nix/store/3bjyslnparihj8jy605ghq7vn41q251c-discourse-ruby-env-3.2.5/lib/ruby/gems/3.2.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli/exec.rb:58:in `load'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli/exec.rb:58:in `kernel_load'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli/exec.rb:23:in `run'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli.rb:455:in `exec'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli.rb:35:in `dispatch'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli.rb:29:in `start'
       > /nix/store/3bjyslnparihj8jy605ghq7vn41q251c-discourse-ruby-env-3.2.5/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/exe/bundle:28:in `block in <top (required)>'
       > /nix/store/r205qrqpixlf6gp3s3kzhlqfmpkflini-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
       > /nix/store/3bjyslnparihj8jy605ghq7vn41q251c-discourse-ruby-env-3.2.5/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/exe/bundle:20:in `<top (required)>'
       > /nix/store/lvvvw0rgwif46lzdyhb42d8xk2f5hkn6-ruby-3.2.4/bin/bundle:25:in `load'
       > /nix/store/lvvvw0rgwif46lzdyhb42d8xk2f5hkn6-ruby-3.2.4/bin/bundle:25:in `<main>'
       > (See full trace by running task with --trace)
       For full logs, run 'nix log /nix/store/5f8q37zl57558br2ls3aa06q7bx1ys86-discourse-assets-3.2.5.drv'.
error: 1 dependencies of derivation '/nix/store/gc91p3yrwhi4xbk4r9b769bfd4csbp8a-discourse-3.2.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6qvgmaswqs6lssw2p90pnhfc4dww3dbh-discourse-rake.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zv4qkg7y7pl4vmwhdli2s9idj93na5aq-nginx.conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/si823mrmw8jz6v0hba9y913wyamywg82-unit-discourse.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0b6r6hw6cngb939mgrn93wx6mfsdgw2n-discourse-rake_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/67d2p28kn6jj4pl74w0bqv579r6j0nnj-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sss68nvc2sslic4a8bnc6w5whmpxdrzy-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ynh0yna0kicbh4a0l5xz915372alz7d6-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/88dv0d0d27rk0svr42pz8g0ylb33gjf6-nixos-system-discourse-24.11.20241001.27e30d1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/h6s7nxn2fywh639rl762x2wadds1ais7-activatable-nixos-system-discourse-24.11.20241001.27e30d1.drv' failed to build
🚀 ❌ [deploy] [ERROR] Failed to build profile on node discourse: discourse
~/C
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment]
This appears to be fixed by #337360 (tested by cherry-picking b991caf31e5b51d97c0b6d1558b075c8f2c18342 onto master).

**Comment by drupol** [comment]
Added the PR to my watchlist, I'll close the issue when it's fixed on my side.

**Comment by Atemu** [comment]
https://github.com/NixOS/nixpkgs/pull/337360 is now in unstable and `discourse` builds fine for me

**Comment by drupol** [comment]
Thanks for closing this !
