### ISSUE TITLE
Espanso not working on Wayland with NVIDIA GPU

### ISSUE THREAD

**Issue by pbek** [NixOS/nixpkgs#346221]
### Describe the bug

@pitkling, I tried on another system with NVDIA GPU.

[Espanso](https://search.nixos.org/packages?channel=unstable&show=espanso-wayland&from=0&size=50&sort=relevance&type=packages&query=espanso) is failing to start on Wayland with NVIDIA GPU. Works fine with Intel/AMD integrated graphics, tested on two different systems with different NVIDIA GPUs.
This is a follow-up to https://github.com/NixOS/nixpkgs/issues/249364#issuecomment-2390686018.

### Steps To Reproduce
1. Turn on Wayland and Espanso on a system like [this](https://github.com/pbek/nixcfg/blob/2e46e5d08271330f2518f6312a6023c0c48ed98c/flake.nix#L111-L123) (but with Wayland turned on) with an NVIDIA GPU
2. Espanso is unable to start as service or unmanaged

`espanso log`:

```
20:20:13 [daemon(3136)] [INFO] reading configs from: "/home/omega/.config/espanso"
20:20:13 [daemon(3136)] [INFO] reading packages from: "/home/omega/.config/espanso/match/packages"
20:20:13 [daemon(3136)] [INFO] using runtime dir: "/home/omega/.cache/espanso"
20:20:13 [daemon(3136)] [INFO] system info: NixOS v24.11 - kernel: 6.6.52
20:20:13 [daemon(3136)] [WARN] keyboard layout watcher couldn't determine active layout.
20:20:13 [daemon(3136)] [INFO] watching for changes in path: "/home/omega/.config/espanso"
20:20:13 [daemon(3136)] [INFO] espanso version: 2.2.1
20:20:13 [daemon(3136)] [INFO] spawning the worker process...
20:20:13 [daemon(3136)] [INFO] binded to IPC unix socket: /home/omega/.cache/espanso/espansodaemonv2.sock
20:20:13 [worker(3150)] [INFO] reading configs from: "/home/omega/.config/espanso"
20:20:13 [worker(3150)] [INFO] reading packages from: "/home/omega/.config/espanso/match/packages"
20:20:13 [worker(3150)] [INFO] using runtime dir: "/home/omega/.cache/espanso"
20:20:13 [worker(3150)] [INFO] system info: NixOS v24.11 - kernel: 6.6.52
20:20:13 [worker(3150)] [INFO] binded to IPC unix socket: /home/omega/.cache/espanso/espansoworkerv2.sock
20:20:13 [worker(3150)] [INFO] using WaylandAppInfoProvider
20:20:13 [worker(3150)] [WARN] EVDEV backend is being used, but without enabling linux capabilities.
20:20:13 [worker(3150)] [WARN]   Although you CAN run espanso EVDEV backend as root, it's not recommended due
20:20:13 [worker(3150)] [WARN]   to security reasons. Espanso supports linux capabilities to limit the attack surface
20:20:13 [worker(3150)] [WARN]   area by only leveraging on the CAP_DAC_OVERRIDE capability (needed to work with
20:20:13 [worker(3150)] [WARN]   /dev/input/* devices to detect and inject text) and disabling it as soon as the
20:20:13 [worker(3150)] [WARN]   initial setup is completed.
20:20:13 [worker(3150)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
20:20:13 [worker(3150)] [INFO] using EVDEVSource
20:20:13 [worker(3150)] [INFO] monitoring the status of the daemon process
20:20:14 [worker(3150)] [INFO] Querying modifier status...
20:20:14 [worker(3150)] [ERROR] thread 'detect thread' panicked at 'called `Result::unwrap()` on an `Err` value: NoCompositor': espanso-detect/src/evdev/sync/wayland.rs:42
20:20:14 [worker(3150)] [ERROR] thread 'engine thread' panicked at 'unable to receive from the init_rx channel: RecvError': espanso/src/cli/worker/engine/funnel/mod.rs:124
20:20:14 [worker(3150)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
20:20:14 [worker(3150)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
20:20:14 [daemon(3136)] [ERROR] received unexpected exit code from worker 101, exiting
```

`journalctl --user -u espanso -b`:

[journalctl-espanso.log](https://github.com/user-attachments/files/17248631/journalctl-espanso.log)

`dmesg`:

[dmesg.log](https://github.com/user-attachments/files/17248606/dmesg.log)

### Expected behavior

Espanso is working like on Wayland systems without NVIDIA GPU, like mentioned [here](https://github.com/NixOS/nixpkgs/issues/249364#issuecomment-2390686018).

### Notify maintainers

@kimat @pyrox0 @n8henrie

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.11 (Vicuna), 24.11.20240929.06cf0e1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.8`
 - channels(root): `"nixos"`
 - nixpkgs: `/run/current-system/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by n8henrie** [comment]
Hmm, while everything else is on Wayland, I run X on my desktop with an nvidia GPU
specifically because all the Wayland setups explicitly don't work well with nvidia.

what is your setup?

**Comment by pbek** [comment]
> all the Wayland setups explicitly don't work well with nvidia

That's true. 😁 

Config like [this](https://github.com/pbek/nixcfg/blob/2e46e5d08271330f2518f6312a6023c0c48ed98c/flake.nix#L111-L123). 

```
OS: NixOS 24.11.20240929.06cf0e1 (Vicuna) x86_64
Host: B550M AORUS ELITE
Kernel: Linux 6.6.52
Uptime: 55 mins
Packages: 2169 (nix-system), 484 (nix-user)
Shell: fish 3.7.1
Display (SONY TV  *30): 3840x2160 @ 60 Hz in 75″ [External] *
Display (ASUS PB278): 2560x1440 @ 60 Hz in 27″ [External]
DE: KDE Plasma
WM: KWin (X11)
WM Theme: plastik
Theme: Breeze (Classic) [Qt], Breeze-Dark [GTK2/3]
Icons: breeze [Qt], breeze [GTK2/3/4]
Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK2/3/4]
Cursor: breeze (24px)
Terminal: qc
CPU: AMD Ryzen 5 5600X (12) @ 3.70 GHz
GPU: NVIDIA GeForce RTX 2070 SUPER [Discrete]
Memory: 14.19 GiB / 62.70 GiB (23%)
Locale: en_US.UTF-8
```

The other system I tested was a Lenovo Thinkstation with an NVIDIA Quadro P400.

**Comment by pbek** [comment]
> WM: KWin (X11)

Hah, this got me thinking. And then I found my error. I was not selecting the Plasma Wayland session at the login screen, I thought `services.displayManager.defaultSession = "plasma";` will do that automatically.

Espanso actually does work, sorry for the noise!

```
21:44:46 [daemon(2540)] [INFO] reading configs from: "/home/omega/.config/espanso"
21:44:46 [daemon(2540)] [INFO] reading packages from: "/home/omega/.config/espanso/match/packages"
21:44:46 [daemon(2540)] [INFO] using runtime dir: "/home/omega/.cache/espanso"
21:44:46 [daemon(2540)] [INFO] system info: NixOS v24.11 - kernel: 6.6.52
21:44:46 [daemon(2540)] [WARN] keyboard layout watcher couldn't determine active layout.
21:44:46 [daemon(2540)] [INFO] watching for changes in path: "/home/omega/.config/espanso"
21:44:46 [daemon(2540)] [INFO] espanso version: 2.2.1
21:44:46 [daemon(2540)] [INFO] spawning the worker process...
21:44:46 [daemon(2540)] [INFO] binded to IPC unix socket: /home/omega/.cache/espanso/espansodaemonv2.sock
21:44:46 [worker(2556)] [INFO] reading configs from: "/home/omega/.config/espanso"
21:44:46 [worker(2556)] [INFO] reading packages from: "/home/omega/.config/espanso/match/packages"
21:44:46 [worker(2556)] [INFO] using runtime dir: "/home/omega/.cache/espanso"
21:44:46 [worker(2556)] [INFO] system info: NixOS v24.11 - kernel: 6.6.52
21:44:46 [worker(2556)] [INFO] binded to IPC unix socket: /home/omega/.cache/espanso/espansoworkerv2.sock
21:44:46 [worker(2556)] [INFO] using WaylandAppInfoProvider
21:44:46 [worker(2556)] [WARN] EVDEV backend is being used, but without enabling linux capabilities.
21:44:46 [worker(2556)] [INFO] monitoring the status of the daemon process
21:44:46 [worker(2556)] [WARN]   Although you CAN run espanso EVDEV backend as root, it's not recommended due
21:44:46 [worker(2556)] [WARN]   to security reasons. Espanso supports linux capabilities to limit the attack surface
21:44:46 [worker(2556)] [WARN]   area by only leveraging on the CAP_DAC_OVERRIDE capability (needed to work with
21:44:46 [worker(2556)] [WARN]   /dev/input/* devices to detect and inject text) and disabling it as soon as the
21:44:46 [worker(2556)] [WARN]   initial setup is completed.
21:44:46 [worker(2556)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
21:44:46 [worker(2556)] [INFO] using EVDEVSource
21:44:47 [worker(2556)] [INFO] Querying modifier status...
21:44:47 [worker(2556)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
21:44:47 [worker(2556)] [INFO] using EVDEVInjector
21:44:47 [worker(2556)] [INFO] using WaylandFallbackClipboard
21:44:50 [worker(2556)] [ERROR] Unable to show notification: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by pbek** [comment]
But my session still doesn't survive suspend to RAM with the NVIDIA GPU under Wayland. Too bad. 😬
