### ISSUE TITLE
Build failure: nodejs_22

### ISSUE THREAD

**Issue by emilazy** [NixOS/nixpkgs#346243]
Broken on `staging-next`:

```
Failed to build addon in /build/node-v22.8.0/test/js-native-api/3_callbacks:
Traceback (most recent call last):
  File "/build/node-v22.8.0/deps/npm/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/build/node-v22.8.0/deps/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 688, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/build/node-v22.8.0/deps/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 680, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/build/node-v22.8.0/deps/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 647, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/build/node-v22.8.0/deps/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 103, in Load
    generator = __import__(generator_name, globals(), locals(), generator_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/node-v22.8.0/deps/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 220, in <module>
    """ % {'python': sys.executable}  # noqa: E501
                     ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'?
```

Full log: https://hydra.nixos.org/build/274032408/nixlog/5

cc @aduh95

**Comment by aduh95** [comment]
https://github.com/NixOS/nixpkgs/pull/342653 seems to have a passing build, let me rebase that on top of staging-next

**Comment by aduh95** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/346371
