### ISSUE TITLE
freeplane fails on startup

### ISSUE THREAD

**Issue by nilsalex** [NixOS/nixpkgs#346419]
### Describe the bug
freeplane from `nixos-unstable` fails on startup with the error message
```
java.io.FileNotFoundException: /nix/store/q8rj5bznm7nxpkcid9rsr2ga4qkrjjd3-freeplane-1.11.14/share/freeplane/core/org.freeplane.core/META-INF/MANIFEST.MF (No such file or directory)
```

### Steps To Reproduce
1. From `nixos-unstable` run freeplane, e.g. `nix run nixpkgs#freeplane`. Does not need to be graphical, `freeplane -h` will also show the error.

### Expected behavior
freeplane starts

### Screenshots
```
$ nix run nixpkgs#freeplane
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
WARNING: package sun.swing.shell not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.freeplane.launcher.Launcher (file:/nix/store/q8rj5bznm7nxpkcid9rsr2ga4qkrjjd3-freeplane-1.11.14/share/freeplane/freeplanelauncher.jar)
WARNING: Please consider reporting this to the maintainers of org.freeplane.launcher.Launcher
WARNING: System::setSecurityManager will be removed in a future release
Knopflerfish OSGi framework launcher, version <unknown>
Copyright 2003-2020 Knopflerfish. All Rights Reserved.
See http://www.knopflerfish.org for more information.

Created Framework: org.knopflerfish.framework, version=8.0.11.
java.io.FileNotFoundException: /nix/store/q8rj5bznm7nxpkcid9rsr2ga4qkrjjd3-freeplane-1.11.14/share/freeplane/core/org.freeplane.core/META-INF/MANIFEST.MF (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.knopflerfish.framework.bundlestorage.file.Archive.downloadArchive(Archive.java:226)
	at org.knopflerfish.framework.bundlestorage.file.BundleArchiveImpl.<init>(BundleArchiveImpl.java:134)
	at org.knopflerfish.framework.bundlestorage.file.BundleStorageImpl.insertBundleJar(BundleStorageImpl.java:219)
	at org.knopflerfish.framework.Bundles.install0(Bundles.java:161)
	at org.knopflerfish.framework.SecurePermissionOps$14.run(SecurePermissionOps.java:737)
	at org.knopflerfish.framework.SecurePermissionOps$14.run(SecurePermissionOps.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.knopflerfish.framework.SecurePermissionOps.callInstall0(SecurePermissionOps.java:732)
	at org.knopflerfish.framework.Bundles.install(Bundles.java:118)
	at org.knopflerfish.framework.BundleContextImpl.installBundle(BundleContextImpl.java:125)
	at org.knopflerfish.framework.Main.handleArgs(Main.java:549)
	at org.knopflerfish.framework.Main.start(Main.java:224)
	at org.freeplane.launcher.Launcher.startFramework(Launcher.java:335)
	at org.freeplane.launcher.Launcher.launchWithoutUICheck(Launcher.java:303)
	at org.freeplane.launcher.Launcher.main(Launcher.java:88)
Error: Command "-istart org.freeplane.core" failed, Failed to install bundle: java.io.FileNotFoundException: /nix/store/q8rj5bznm7nxpkcid9rsr2ga4qkrjjd3-freeplane-1.11.14/share/freeplane/core/org.freeplane.core/META-INF/MANIFEST.MF (No such file or directory)
```

### Additional context
I bisected the issue and found this commit from #272380 to be the culprit: https://github.com/NixOS/nixpkgs/commit/2029c93adfe222a59d4d448bf7fd26b667322fe2

It makes sense, because this commit is a complete overhaul of the packaging process. Sadly, I am not experienced enough in building java applications to see why it would fail after these changes.

### Notify maintainers

@charles-dyfis-net 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.53, NixOS, 24.11 (Vicuna), 24.11.20241001.27e30d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(nils): `"home-manager-23.05.tar.gz"`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/lryfc8mhk1czqsa421di2y5nzz5c3b8m-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chayleaf** [comment]
This issue is nondeterminism-related. When I build it myself without using the binary cache, it works fine.

**Comment by raboof** [comment]
I see we have already reported this issue upstream at https://github.com/freeplane/freeplane/issues/2064, but they assumed it was a problem with the packaging.

Now that we've identified that it's a nondeterminism in the Gradle build, I'm not so sure - I'll add a note there.

(disabling parallelism indeed appears to work, but is more of a workaround than a fix, and it's hard to say it'll fix it reliably)
