### ISSUE TITLE
xpra attach fails with "NameError: name 'xsync' is not defined"

### ISSUE THREAD

**Issue by jchv** [NixOS/nixpkgs#347294]
(Note: if you're looking for a workaround, try setting `GDK_BACKEND=x11`.)

### Describe the bug
Xpra crashes during attach.

```console
$ nix run nixpkgs#xpra -- attach ...
2024-10-08 10:46:35,268 Xpra GTK3 X11 client version 6.1.2
2024-10-08 10:46:35,271  running on Linux 6.11.1
2024-10-08 10:46:35,271  cpython 3.12
2024-10-08 10:46:35,271  window manager is 'sway on wayland'
2024-10-08 10:46:35,828 GStreamer version 1.24.3
2024-10-08 10:46:35,844 Warning: failed to load the GObject notifier
2024-10-08 10:46:35,844  Namespace Notify not available
2024-10-08 10:46:35,848 created unix domain sockets:
2024-10-08 10:46:35,848  '/run/user/1000/xpra/clients/curly-299510'
2024-10-08 10:46:36,017 removing unix domain socket '/run/user/1000/xpra/clients/curly-299510'
xpra main error:
Traceback (most recent call last):
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/scripts/main.py", line 138, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/scripts/main.py", line 507, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, full_mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/scripts/main.py", line 604, in do_run_mode
    return run_client(script_file, cmdline, error_cb, options, args, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/scripts/main.py", line 1484, in run_client
    app = get_client_app(cmdline, error_cb, opts, extra_args, mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/scripts/main.py", line 1653, in get_client_app
    app = get_client_gui_app(error_cb, opts, request_mode, extra_args, mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/scripts/main.py", line 1725, in get_client_gui_app
    app.init_ui(opts)
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/client/gui/ui_client_base.py", line 224, in init_ui
    self.keyboard_helper = self.keyboard_helper_class(send_keyboard, opts.keyboard_sync,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/client/gtk3/keyboard_helper.py", line 31, in __init__
    self.update()
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/client/gtk3/keyboard_helper.py", line 84, in update
    super().update()
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/client/gui/keyboard_helper.py", line 300, in update
    self.query_xkbmap()
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/client/gui/keyboard_helper.py", line 278, in query_xkbmap
    self.layout, self.layouts, self.variant, self.variants, self.options = self.get_layout_spec()
                                                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/client/gui/keyboard_helper.py", line 231, in get_layout_spec
    layout, layouts, variant, variants, options = self.keyboard.get_layout_spec()
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/k442kmivv1v9i051xka9a4dk7wfcpaip-xpra-6.1.2/lib/python3.12/site-packages/xpra/platform/posix/keyboard.py", line 274, in get_layout_spec
    with xsync:
         ^^^^^
NameError: name 'xsync' is not defined
```

Happens in either XWayland or Wayland.

### Steps To Reproduce
1. `xpra attach ...`

### Expected behavior
Shouldn't crash.

### Screenshots
Can't.

### Additional context
No time to dig into this yet, sorry. I can at least begin a bisect since that is ~zero effort on my part.

### Notify maintainers
@offlinehacker @numinit @mvnetbiz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.1, NixOS, 24.11 (Vicuna), 24.11.20241004.bc947f5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos"`
 - channels(john): `""`
 - nixpkgs: `/nix/store/sdzpqjwx7pdx6lsq6llyfqqf7hspp83c-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jasom** [comment]
FWIW, I just tried xpra from nixpkgs unstable (634fd46801442d760e09493a794c4f15db2d0cbb)

**Comment by jchv** [comment]
Yeah, it should be working in nixpkgs-unstable; the fix was released a bit ago and the xpra derivation was since updated. I think this issue can be closed.
