### ISSUE TITLE
Build failure: csvkit

### ISSUE THREAD

**Issue by alejolagosm** [NixOS/nixpkgs#347341]
### Steps To Reproduce

1. build csvkit

### Build log

```
/private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/dbf-0.99.9/dbf/test.py:35: DbfWarning: test if warning is an exception
  warnings.warn('test if warning is an exception', dbf.DbfWarning, stacklevel=1)

Testing dbf version 0.99.009 on darwin with Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 16.0.6 ]

...............s...............................F.................................................................................................................
======================================================================
FAIL: test_mismatched_extensions (__main__.TestDbfFunctions.test_mismatched_extensions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/dbf-0.99.9/dbf/test.py", line 4822, in test_mismatched_extensions
    self.assertEqual(table._meta.memoname, new_memo_name)
AssertionError: '/private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/tmphnv9ufsa/temptable.dbt' != '/private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/tmphnv9ufsa/temptable.Dbt'
- /private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/tmphnv9ufsa/temptable.dbt
?                                                                          ^
+ /private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/tmphnv9ufsa/temptable.Dbt
?                                                                          ^


----------------------------------------------------------------------
Ran 161 tests in 44.659s

FAILED (failures=1, skipped=1)
error: builder for '/nix/store/p2qkfy3m72n1bsxzlvzn3fks8pz70p1l-python3.11-dbf-0.99.9.drv' failed with exit code 1;
       last 25 log lines:
       > Finished executing pythonRemoveTestsDir
       > Running phase: installCheckPhase
       > /private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/dbf-0.99.9/dbf/test.py:35: DbfWarning: test if warning is an exception
       >   warnings.warn('test if warning is an exception', dbf.DbfWarning, stacklevel=1)
       >
       > Testing dbf version 0.99.009 on darwin with Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 16.0.6 ]
       >
       > ...............s...............................F.................................................................................................................
       > ======================================================================
       > FAIL: test_mismatched_extensions (__main__.TestDbfFunctions.test_mismatched_extensions)
       > ----------------------------------------------------------------------
       > Traceback (most recent call last):
       >   File "/private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/dbf-0.99.9/dbf/test.py", line 4822, in test_mismatched_extensions
       >     self.assertEqual(table._meta.memoname, new_memo_name)
       > AssertionError: '/private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/tmphnv9ufsa/temptable.dbt' != '/private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/tmphnv9ufsa/temptable.Dbt'
       > - /private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/tmphnv9ufsa/temptable.dbt
       > ?                                                                          ^
       > + /private/tmp/nix-build-python3.11-dbf-0.99.9.drv-0/tmphnv9ufsa/temptable.Dbt
       > ?                                                                          ^
       >
       >
       > ----------------------------------------------------------------------
       > Ran 161 tests in 44.659s
       >
       > FAILED (failures=1, skipped=1)
       For full logs, run 'nix-store -l /nix/store/p2qkfy3m72n1bsxzlvzn3fks8pz70p1l-python3.11-dbf-0.99.9.drv'.
error: 1 dependencies of derivation '/nix/store/67xy2n5p7xq7wyrj9kxckf7vjm027d3i-python3.11-agate-dbf-0.2.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y1r8jlbbvw44ciqpd0jh72z4fxvlj1gq-csvkit-2.0.0.drv' failed to build
```

### Additional context

I am unable to build a derivation using nixpkgs csvkit on macOS.

Related [issue](https://github.com/NixOS/nixpkgs/issues/281150)

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.23.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

**Comment by t4ccer** [comment]
Seems darwin specific, can build `python3Packages.dbf` and `csvkit` just fine on x86_64-linux

**Comment by alejolagosm** [comment]
yes, I forgot to clarify that this is darwin specific. On linux the build works just fine.

**Comment by viraptor** [comment]
This is already reported upstream in https://github.com/ethanfurman/dbf/issues/48 with a temporary fix at https://github.com/NixOS/nixpkgs/pull/298070
