### ISSUE TITLE
 virtiofsd: Unable to find a satisfying virtiofsd when starting VM

### ISSUE THREAD

**Issue by joygnu** [NixOS/nixpkgs#347942]
### Issue: Unable to find a satisfying virtiofsd when starting Windows VM

When I add a `virtiofsd` system to my Windows VM and then try to start it, I get the following error:

Error starting domain: operation failed: Unable to find a satisfying virtiofsd

Traceback (most recent call last):
  File "/nix/store/a3ij5xh85j7v07s2w2adgyp4lmhbmzm3-virt-manager-4.1.0/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/nix/store/a3ij5xh85j7v07s2w2adgyp4lmhbmzm3-virt-manager-4.1.0/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/nix/store/85fyh54p20h8262dgvqkzcqi5xf7dphk-python3.12-libvirt-10.5.0/lib/python3.12/site-packages/libvirt.py", line 1379, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: operation failed: Unable to find a satisfying virtiofsd

The temporary fix is to add this line in the filesystem XML 

 `<binary path="/run/current-system/sw/bin/virtiofsd"/>`

### Steps to Reproduce
1. Add a `virtiofsd` to a Windows VM.
2. Launch the VM.

### Expected Behavior
The VM should boot up normally.

### Additional Context
- **System:** x86_64-linux
- **Host OS:** Linux 6.6.54, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf
- **Multi-user?:** yes
- **Sandbox:** yes
- **Version:** nix-env (Nix) 2.18.8
- **Channels (root):** nixos-23.11
- **Nixpkgs:** /nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source

### Notify Maintainers

@astro

**Comment by devurandom** [comment]
I run into the same error, but using Vagrant with the libvirt provider.

I downloaded https://github.com/buildroot/buildroot/blob/2024.11.1/support/misc/Vagrantfile and applied the settings suggested on https://vagrant-libvirt.github.io/vagrant-libvirt/examples.html#synced-folders for Libvirt >= 6.9.0:
```diff
--- Vagrantfile.orig	2025-01-26 14:34:34.857791311 +0100
+++ Vagrantfile	2025-01-26 14:34:05.143923582 +0100
@@ -32,8 +32,11 @@
 	config.vm.provider :libvirt do |v, override|
 		v.memory = VM_MEMORY
 		v.cpus = VM_CORES
+		v.memorybacking :access, :mode => "shared"
 	end

+	config.vm.synced_folder "./", "/vagrant", type: "virtiofs"
+
 	config.vm.provision 'shell' do |s|
 		s.inline = 'echo Setting up machine name'
 
```

Running `vagrant up` I get:

```
==> default: Removing virtiofs devices for shared folders...
==> default: Configuring virtiofs devices for shared folders...
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Removing domain...
==> default: Deleting the machine folder
/nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/fog-libvirt-0.13.1/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `create': Call to virDomainCreate failed: operation failed: Unable to find a satisfying virtiofsd (Libvirt::Error)
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/fog-libvirt-0.13.1/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `vm_action'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/fog-libvirt-0.13.1/lib/fog/libvirt/models/compute/server.rb:81:in `start'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/start_domain.rb:608:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/set_boot_order.rb:22:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/share_folders.rb:22:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:21:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builtin/synced_folders.rb:90:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builtin/delayed.rb:22:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builtin/synced_folder_cleanup.rb:31:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/plugins/synced_folders/nfs/action_cleanup.rb:28:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:14:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:117:in `block in finalize_action'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builder.rb:183:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/runner.rb:104:in `block in run'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/util/busy.rb:22:in `busy'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/runner.rb:104:in `run'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builtin/call.rb:56:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:117:in `block in finalize_action'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builder.rb:183:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/runner.rb:104:in `block in run'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/util/busy.rb:22:in `busy'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/runner.rb:104:in `run'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builtin/call.rb:56:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/create_network_interfaces.rb:169:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/create_networks.rb:98:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/create_domain.rb:466:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/resolve_disk_settings.rb:143:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/create_domain_volume.rb:98:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/handle_box_image.rb:129:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builtin/handle_box.rb:58:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/handle_storage_pool.rb:63:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builtin/provision.rb:83:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/032vs52lac7wnppnl7lj94f151ns4b29-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/cleanup_on_failure.rb:21:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:117:in `block in finalize_action'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builder.rb:183:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/runner.rb:104:in `block in run'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/util/busy.rb:22:in `busy'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/runner.rb:104:in `run'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builtin/call.rb:56:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builtin/box_check_outdated.rb:98:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builtin/config_validate.rb:28:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/builder.rb:183:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/runner.rb:104:in `block in run'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/util/busy.rb:22:in `busy'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/action/runner.rb:104:in `run'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/machine.rb:246:in `action_raw'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/machine.rb:215:in `block in action'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/environment.rb:649:in `lock'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/machine.rb:201:in `call'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/machine.rb:201:in `action'
	from /nix/store/c93g0957cg9na8103n6zsp6rwv3ziczp-vagrant-2.4.3/lib/ruby/gems/3.3.0/gems/vagrant-2.4.3/lib/vagrant/batch_action.rb:88:in `block (2 levels) in run'
```

**Comment by RogerWeihrauch** [comment]
Hi all.
I ran into the same issue on Debian 12.
Following did solve my issue:
1) 09:42 28.02[debian@bigdeb:~] _0_ $> sudo apt search virtiofsd
librust-virtiofsd-dev/testing 1.13.0-5 amd64
  Virtio-fs vhost-user device daemon - Rust source code

virtiofsd/testing,now 1.13.0-5 amd64
  Virtio-fs vhost-user device daemon

09:43 28.02[debian@bigdeb:~] _0_ $>
2) sudo apt install virtiofsd
Regards,
Roger

**Comment by Aleksanaa** [comment]
Quoting from the discourse post: https://discourse.nixos.org/t/virt-manager-cannot-find-virtiofsd/26752/10

The solution is:

```nix
virtualisation.libvirtd = {
  enable = true;
  qemu.vhostUserPackages = with pkgs; [ virtiofsd ];
};
```
