### ISSUE TITLE
Package request: Docker plugin for JetBrains

### ISSUE THREAD

**Issue by ASHGOLDOFFICIAL** [NixOS/nixpkgs#348587]
**Project description**

Can someone please package this plugin (and maybe [this one](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea) too?) for JetBrains IDEs? I tried to run `plugins/update_plugins.py` as described [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/jetbrains/readme.md), but script crashes with:

```
Traceback (most recent call last):
  File "/home/ashgoldofficial/Projects/nixpkgs/pkgs/applications/editors/jetbrains/plugins/./update_plugins.py", line 391, in <module>
    main()
  File "/home/ashgoldofficial/Projects/nixpkgs/pkgs/applications/editors/jetbrains/plugins/./update_plugins.py", line 380, in main
    result["files"] = get_file_hashes(file_list, refetch_all)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashgoldofficial/Projects/nixpkgs/pkgs/applications/editors/jetbrains/plugins/./update_plugins.py", line 238, in get_file_hashes
    file_hashes[file] = get_hash(file)
                        ^^^^^^^^^^^^^^
  File "/home/ashgoldofficial/Projects/nixpkgs/pkgs/applications/editors/jetbrains/plugins/./update_plugins.py", line 195, in get_hash
    path = path_process.stdout.decode().split("\n")[1]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Metadata**

* homepage URL: https://plugins.jetbrains.com/plugin/7724-docker

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by obvionaoe** [comment]
The [terraform plugin](https://plugins.jetbrains.com/plugin/7808-terraform-and-hcl/) would be helpful as well
