### ISSUE TITLE
`build-composefs-dump.py` permission denied

### ISSUE THREAD

**Issue by oluceps** [NixOS/nixpkgs#348650]
### Describe the bug
Overlayfs etc, immutable
```
> nix build .#nixosConfigurations.hastur.config.system.build.toplevel
error: builder for '/nix/store/saq6yqc4h3x1gk0wcwx4yikvgjrnsh52-etc-dump.drv' failed with exit code 1;
       last 12 log lines:
       > Traceback (most recent call last):
       >   File "/nix/store/5mya528646z2viacq91bccy04cnygvbl-build-composefs-dump.py", line 18, in <module>
       >     from pathlib import Path
       >   File "/nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/python3.12/pathlib.py", line 20, in <module>
       >     from urllib.parse import quote_from_bytes as urlquote_from_bytes
       >   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
       >   File "<frozen importlib._bootstrap_external>", line 991, in exec_module
       >   File "<frozen importlib._bootstrap_external>", line 1104, in get_code
       >   File "<frozen importlib._bootstrap_external>", line 1186, in get_data
       > PermissionError: [Errno 13] Permission denied: '/nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/python3.12/urllib/__init__.py'
       For full logs, run 'nix log /nix/store/saq6yqc4h3x1gk0wcwx4yikvgjrnsh52-etc-dump.drv'.
error: 1 dependencies of derivation '/nix/store/9lcz0hyz22inzk4wz9yppamnnvw6zyp0-etc-metadata.erofs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/074nisfpyym17z9ziwpzw1gmp9nfnac8-nixos-system-hastur-24.11.20240917.46dc692.drv' failed to build
```

### Steps To Reproduce
1. ...
2. ...
3. ...

### Notify maintainers
@nikstur

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.0-cachyos, NixOS, 24.11 (Vicuna), 24.11.20240917.46dc692`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.92.0-dev-pre20240909-c14486a
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /root/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/root/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/root/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/root/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/25k1fs3m1ivnnlwbfg62syz99lgd171f-lix-2.92.0-dev-pre20240909-c14486a/share`
 - nixpkgs: `/nix/store/1lb7pkxhpzs4y1kzqx7lgvbadk1hcphf-21asjvqjhmy385ki1zrvb0n18alr1knv-source`
```
seems things start after last switch. Since then I cannot switch ever.

FWIW there is also some other issue that seems related to that.
```
> systemctl --failed 
  UNIT                     LOAD   ACTIVE SUB    DESCRIPTION                                         >
● mautrix-telegram.service loaded failed failed Mautrix-Telegram, a Matrix-Telegram hybrid puppeting>
● user@1000.service        loaded failed failed User Manager for UID 1000

Legend: LOAD   → Reflects whether the unit definition was properly loaded.
        ACTIVE → The high-level unit activation state, i.e. generalization of SUB.
        SUB    → The low-level unit activation state, values depend on unit type.
```

```
> journalctl -fu user@1000.service 
Oct 15 08:14:18 hastur systemd[1]: user@1000.service: Main process exited, code=exited, status=203/EXEC
Oct 15 08:14:18 hastur systemd[1]: user@1000.service: Failed with result 'exit-code'.
Oct 15 08:14:18 hastur systemd[1]: Failed to start User Manager for UID 1000.
Oct 15 08:19:35 hastur systemd[1]: Starting User Manager for UID 1000...
Oct 15 08:19:35 hastur (systemd)[11709]: pam_unix(systemd-user:session): session opened for user riro(uid=1000) by (uid=0)
Oct 15 08:19:35 hastur (systemd)[11709]: user@1000.service: Failed to execute /nix/store/1lbc6v5p1a3rn4rjaqnz0694xfbq8dxq-systemd-256.4/lib/systemd/systemd: Permission denied
Oct 15 08:19:35 hastur (systemd)[11709]: user@1000.service: Failed at step EXEC spawning /nix/store/1lbc6v5p1a3rn4rjaqnz0694xfbq8dxq-systemd-256.4/lib/systemd/systemd: Permission denied
Oct 15 08:19:35 hastur systemd[1]: user@1000.service: Main process exited, code=exited, status=203/EXEC
Oct 15 08:19:35 hastur systemd[1]: user@1000.service: Failed with result 'exit-code'.
Oct 15 08:19:35 hastur systemd[1]: Failed to start User Manager for UID 1000.
``` 
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by oluceps** [comment]
That may not caused by `etc overlay` part, I found the permission inconsistent in store, which

```
.rwxr-----  135k root  1 Jan  1970   systems
```
should be 555, verified by another machine with the same path.

**Comment by oluceps** [comment]
This is not directly related to etc overlay mechanism, thus I'll close this issue.
