### ISSUE TITLE
Present tool fails immediately upon launching.

### ISSUE THREAD

**Issue by vendion** [NixOS/nixpkgs#348788]
### Describe the bug
After installing `present` it crashes immediately with the following stacktrace upon launching.

```
/nix/store/nqgh04fmz613xg5is60ivrlrxkhabq57-python3.12-present-0.6.0/lib/python3.12/site-packages/present/markdown.py:75: UserWarning: (Slide 1) BlankLine is not supported
  warnings.warn(f"(Slide {sliden + 1}) {element_name} is not supported")
Traceback (most recent call last):
  File "/nix/store/nqgh04fmz613xg5is60ivrlrxkhabq57-python3.12-present-0.6.0/bin/.present-wrapped", line 9, in <module>
    sys.exit(cli())
             ^^^^^
  File "/nix/store/6iw1m117dyw6dhdga3iddyy0bxw5j9bm-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6iw1m117dyw6dhdga3iddyy0bxw5j9bm-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/6iw1m117dyw6dhdga3iddyy0bxw5j9bm-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6iw1m117dyw6dhdga3iddyy0bxw5j9bm-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/nqgh04fmz613xg5is60ivrlrxkhabq57-python3.12-present-0.6.0/lib/python3.12/site-packages/present/cli.py", line 18, in cli
    show.play()
  File "/nix/store/nqgh04fmz613xg5is60ivrlrxkhabq57-python3.12-present-0.6.0/lib/python3.12/site-packages/present/slideshow.py", line 146, in play
    Slide(self, self.get_effects(slide), slide.fg_color, slide.bg_color)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/nqgh04fmz613xg5is60ivrlrxkhabq57-python3.12-present-0.6.0/lib/python3.12/site-packages/present/slideshow.py", line 124, in get_effects
    effects.extend(_base(self.screen, e, row, fg_color, bg_color))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/nqgh04fmz613xg5is60ivrlrxkhabq57-python3.12-present-0.6.0/lib/python3.12/site-packages/present/effects.py", line 125, in _base
    if element.type == "heading" and element.obj["level"] == 3:
                                     ~~~~~~~~~~~^^^^^^^^^
KeyError: 'level'
```

### Steps To Reproduce
1. Install `presnet`
2. Grab the [sample slides from the project's github](https://raw.githubusercontent.com/vinayak-mehta/present/refs/heads/master/examples/sample.md)
3. Try to run the sample slide deck

### Expected behavior
The slide deck to be usable.

### Notify maintainers

@legendofmiracles

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
✗ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by errnoh** [comment]
Related issue on the projects repo: https://github.com/vinayak-mehta/present/issues/120

**Comment by errnoh** [comment]
`mistune` on nixpkgs 24.05 and forward is on version 3.x so that's likely the issue.

**Comment by errnoh** [comment]
@vendion I added PR for the fix (https://github.com/NixOS/nixpkgs/pull/348837), feel free to check it out and confirm that it fixes the issue.
