### ISSUE TITLE
Package request: linux-npu-driver

### ISSUE THREAD

**Issue by vunnyso** [NixOS/nixpkgs#348739]
**Project description**

Intel® NPU (Neural Processing Unit) Driver

**Metadata**

* homepage URL: https://github.com/intel/linux-npu-driver
* source URL: https://github.com/intel/linux-npu-driver/releases
* license: mit
* platforms: unix, linux

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ferrine** [comment]
hey there, I managed to make it work on a fresh Intel Ultra 7 155H (thinkpad X1 12Gen)

the package. It still uses some vendored static dependencies, others are linked to the ones from nixpkgs
```nix
{pkgs, ...}:
pkgs.stdenv.mkDerivation {
  pname = "linux-npu-driver";
  version = "1.10.0"; # Modify as needed

  src = pkgs.fetchFromGitHub {
    fetchSubmodules = true;
    fetchLFS = true;
    owner = "intel";
    repo = "linux-npu-driver";
    rev = "v1.10.0";
    hash = "sha256-/WVj7k6v52Kp1mNU8n2mrql27fo9jVoEYja3zBowITk=";
  };
  outputs = ["out" "firmware"];
  postPatch = ''
    substituteInPlace firmware/CMakeLists.txt \
      --replace-fail "DESTINATION /lib/firmware/updates/intel/vpu/" \
      "DESTINATION $firmware/lib/firmware/intel/vpu/"
  '';
  nativeBuildInputs = [ pkgs.cmake ];
  buildInputs = with pkgs; [
    udev
    boost
    openssl
  ];
  # Optionally provide a meta section for metadata
  meta = {
    description = "Intel® NPU (Neural Processing Unit) Driver";
    homepage = "https://github.com/intel/linux-npu-driver";
    license = pkgs.lib.licenses.mit;
  };
}
```

and ofc the module to add to nixos configuration

```
  boot.extraModulePackages = [
    intel-npu-driver
  ];
  hardware.firmware = [
    intel-npu-driver.firmware
  ];
```

**Comment by ferrine** [comment]
Ok, I managed to build everything. However, I see the issue coming from an unexpected place:

```
>>> core.get_property("NPU", props.device.full_name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Exception from src/inference/src/cpp/core.cpp:214:
Cannot load library '/nix/store/9fgniggdbmqfz1i849fbvfc7a02j7qih-openvino-2024.4.1/runtime/lib/intel64/libopenvino_intel_npu_plugin.so': /nix/store/zrf9waqkpibfp8rlcc92zi2md8isprpx-gcc-12.4.0-lib/lib/li
bstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /nix/store/in99fi35k65maz0n521sinwqgbqqbkrl-level-zero-1.18.3/lib/libze_loader.so.1)

>>> 
>>> ldd /nix/store/in99fi35k65maz0n521sinwqgbqqbkrl-level-zero-1.18.3/lib/libze_loader.so.1
  File "<stdin>", line 1
    ldd /nix/store/in99fi35k65maz0n521sinwqgbqqbkrl-level-zero-1.18.3/lib/libze_loader.so.1
                                                                   ^^
SyntaxError: invalid syntax
>>> 

[nix-shell:~/lore]# ldd /nix/store/in99fi35k65maz0n521sinwqgbqqbkrl-level-zero-1.18.3/lib/libze_loader.so.1
        linux-vdso.so.1 (0x00007f48e5476000)
        libdl.so.2 => /nix/store/3bvxjkkmwlymr0fssczhgi39c3aj1l7i-glibc-2.40-36/lib/libdl.so.2 (0x00007f48e535f000)
        libstdc++.so.6 => /nix/store/s94fwp43xhzkvw8l8nqslskib99yifzi-gcc-13.3.0-lib/lib/libstdc++.so.6 (0x00007f48e5000000)
        libm.so.6 => /nix/store/3bvxjkkmwlymr0fssczhgi39c3aj1l7i-glibc-2.40-36/lib/libm.so.6 (0x00007f48e5278000)
        libgcc_s.so.1 => /nix/store/s94fwp43xhzkvw8l8nqslskib99yifzi-gcc-13.3.0-lib/lib/libgcc_s.so.1 (0x00007f48e4fdb000)
        libc.so.6 => /nix/store/3bvxjkkmwlymr0fssczhgi39c3aj1l7i-glibc-2.40-36/lib/libc.so.6 (0x00007f48e4de2000)
        /nix/store/3bvxjkkmwlymr0fssczhgi39c3aj1l7i-glibc-2.40-36/lib64/ld-linux-x86-64.so.2 (0x00007f48e5478000)
```

**Comment by ferrine** [comment]
If there is anyone knowledgeable of such kind of issues, that would be amazing

**Comment by ferrine** [comment]
CC @ziguana is in level-zero maintainers, maybe there is something relevant to know

**Comment by ferrine** [comment]
after reading https://github.com/NixOS/nixpkgs/issues/287764 I think the issue is in a different place, CC @SomeoneSerge

**Comment by ferrine** [comment]
Finally, I've fixed weird openvino stdenv and the rest of the puzzle started working

```
root@nixos:~/ > LD_LIBRARY_PATH=/nix/var/nix/profiles/system/sw/lib/ python -c 'import openvino as ov;import openvino.properties as props;core = ov.Core();print(core.get_property("NPU", props.device.full_name))'
Intel(R) AI Boost
```

**Comment by ferrine** [comment]
it was late night, and I was browsing wrong repo for issues, referenced this issue by mistake
