### ISSUE TITLE
conky segfaults

### ISSUE THREAD

**Issue by layus** [NixOS/nixpkgs#35006]
## Issue description

Since last update (https://github.com/NixOS/nixpkgs/commit/943e32abb7999e50d0cb6f2548965ea1bd7368b3) conky segfaults on execution.

### Steps to reproduce

run conky

## Technical details

```
gdb conky
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from conky...(no debugging symbols found)...done.
(gdb) start
Temporary breakpoint 1 at 0x4294d0
Starting program: /nix/store/d5p7xccmv06jnj19i4vi31g7kq7lvb9j-gmaudoux-package-set/bin/conky 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/4h0allsz28x9mdirzb4wv51algacxzr7-glibc-2.26-131/lib/libthread_db.so.1".
warning: File "/nix/store/kzqrxkxs6lcbhxlalcim7zz6xay0i2f2-gcc-6.4.0-lib/lib/libstdc++.so.6.0.22-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/home/gmaudoux/projets/gecko-dev/.gdbinit".
To enable execution of this file add
	add-auto-load-safe-path /nix/store/kzqrxkxs6lcbhxlalcim7zz6xay0i2f2-gcc-6.4.0-lib/lib/libstdc++.so.6.0.22-gdb.py
line to your configuration file "/home/gmaudoux/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/gmaudoux/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"

Temporary breakpoint 1, 0x00000000004294d0 in main ()
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff721ef7d in XQueryExtension () from /nix/store/pir9gyi4s5ly7n0sr6n1vwgmjvz5z8zv-libX11-1.6.5/lib/libX11.so.6
(gdb) bt
#0  0x00007ffff721ef7d in XQueryExtension () from /nix/store/pir9gyi4s5ly7n0sr6n1vwgmjvz5z8zv-libX11-1.6.5/lib/libX11.so.6
#1  0x00007ffff7212be6 in XInitExtension () from /nix/store/pir9gyi4s5ly7n0sr6n1vwgmjvz5z8zv-libX11-1.6.5/lib/libX11.so.6
#2  0x00007ffff6fe12ff in XextAddDisplay () from /nix/store/2py2kqlvdrz64bl2mnm1mccpgq06mzzi-libXext-1.3.3/lib/libXext.so.6
#3  0x00007ffff6fdb7d8 in XShapeQueryVersion () from /nix/store/2py2kqlvdrz64bl2mnm1mccpgq06mzzi-libXext-1.3.3/lib/libXext.so.6
#4  0x0000000000437a4d in main_loop() ()
#5  0x0000000000429d90 in main ()
(gdb) 
```

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results: 
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.81, NixOS, 18.03.git.53fb6baa88 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0pre5943_52c777a7`
 - channels(layus): `"nixpkgs-17.03pre99938.3ccc139"`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

/cc @fpletz

**Comment by layus** [comment]
Sorry for the fuss, apparently the fix is already released in 1.10.8: https://github.com/brndnmtthws/conky/commit/562c7375883445acb58388ff16d9eb126b7e12a1
