### ISSUE TITLE
Build failure: azure-cli

### ISSUE THREAD

**Issue by matdibu** [NixOS/nixpkgs#350181]
### Steps To Reproduce

1. try to build `azure-cli` on `nixos-unstable`

note: it works on `nixos-24.05`

### Build log

```
error: builder for '/nix/store/dqn1gxci2qg165ymj8xichazan5pf4j0-python3.12-fabric-3.2.2.drv' failed with exit code 1;
       last 25 log lines:
       > Executing pythonImportsCheckPhase
       > Check whether the following modules can be imported: fabric
       > Traceback (most recent call last):
       >   File "<string>", line 1, in <module>
       >   File "<string>", line 1, in <lambda>
       >   File "/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/importlib/__init__.py", line 90, in import_module
       >     return _bootstrap._gcd_import(name[level:], package, level)
       >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
       >   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
       >   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
       >   File "/nix/store/0qqgcr7xvw922xqg7rkbzyg10ymgj6c5-python3.12-fabric-3.2.2/lib/python3.12/site-packages/fabric/__init__.py", line 3, in <module>
       >     from .connection import Config, Connection
       >   File "/nix/store/0qqgcr7xvw922xqg7rkbzyg10ymgj6c5-python3.12-fabric-3.2.2/lib/python3.12/site-packages/fabric/connection.py", line 9, in <module>
       >     from paramiko.agent import AgentRequestHandler
       >   File "/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/__init__.py", line 22, in <module>
       >     from paramiko.transport import (
       >   File "/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/transport.py", line 99, in <module>
       >     from paramiko.ed25519key import Ed25519Key
       >   File "/nix/store/hdsahpv8zxkcgl16gmkkxnks1f0dv8xw-python3.12-paramiko-3.5.0/lib/python3.12/site-packages/paramiko/ed25519key.py", line 22, in <module>
       >     import nacl.signing
       > ModuleNotFoundError: No module named 'nacl'
```

### Additional context

Might be a problem in `paramiko` or `fabric`, but ultimately it's `azure-cli` that broke on my machine

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.14, NixOS, 24.11 (Vicuna), 24.11.20241018.4c2fcb0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/riqkpszjqk02bi1wppfg8ip5xvh102qd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by matdibu** [comment]
nevermind, found #350160 and #348995
