### ISSUE TITLE
Build failure: python312Packages.librespot

### ISSUE THREAD

**Issue by jukremer** [NixOS/nixpkgs#350243]
### Steps To Reproduce

1. build zotify

### Build log

Last few line of the log. Can provide more if needed.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/nix/store/2y3a18lr8z385yq77sspqzabvnp7ya1h-python3.12-librespot-0.0.9/lib/python3.12/site-packages/librespot/__init__.py", line 3, in >
    from librespot.proto.Keyexchange_pb2 import BuildInfo, Platform, Product, ProductFlags
  File "/nix/store/2y3a18lr8z385yq77sspqzabvnp7ya1h-python3.12-librespot-0.0.9/lib/python3.12/site-packages/librespot/proto/Keyexchange_pb2.py">
    _descriptor.EnumValueDescriptor(
  File "/nix/store/3sgy4wi9zab1j5cpb595aw12d7qjkbkc-python3.12-protobuf-5.28.2/lib/python3.12/site-packages/google/protobuf/descriptor.py", lin>
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

### Notify maintainers

@onny 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jukremer** [comment]
Could we apply the [same fix as Arch](https://github.com/zotify-dev/zotify/issues/147#issuecomment-2212393115) did? 

> As the error message states, the easiest workaround for running zotify would be setting the environment variable (i.e. PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python zotify ...).
