### ISSUE TITLE
GraalVM Native Image is broken on Mac

### ISSUE THREAD

**Issue by pshirshov** [NixOS/nixpkgs#350909]
When I attempt to build an app with `native-image` installed from Nix store I'm getting

```
[info] [1/8] Initializing...                                                                                    (0.0s @ 0.24GB)
Error:  Error: Unable to detect supported DARWIN native software development toolchain.
Error:  Querying with command '/nix/store/5dbia7q27b3j96pfjv0fnkglc7457g35-clang-wrapper-16.0.6/bin/cc -v' prints:
Error:    clang version 16.0.6
Error:    Target: x86_64-apple-darwin22.6.0
Error:    Thread model: posix
Error:    InstalledDir: /nix/store/6ccjdf3miyls5k7vb192nr4ibyb6wvxl-clang-16.0.6/bin
Error:  Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
Error:  com.oracle.svm.core.util.UserError$UserException: Unable to detect supported DARWIN native software development toolchain.
Error:  Querying with command '/nix/store/5dbia7q27b3j96pfjv0fnkglc7457g35-clang-wrapper-16.0.6/bin/cc -v' prints:
Error:    clang version 16.0.6
Error:    Target: x86_64-apple-darwin22.6.0
Error:    Thread model: posix
Error:    InstalledDir: /nix/store/6ccjdf3miyls5k7vb192nr4ibyb6wvxl-clang-16.0.6/bin
Error:  To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:138)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.CCompilerInvoker.addSkipCheckingInfo(CCompilerInvoker.java:107)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.CCompilerInvoker.<init>(CCompilerInvoker.java:75)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.CCompilerInvoker$DarwinCCompilerInvoker.<init>(CCompilerInvoker.java:280)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.CCompilerInvoker.create(CCompilerInvoker.java:85)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:973)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:569)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:537)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:526)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:701)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:140)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:95)
```

If I disable the toolchain check the error would be

```
 Error:  Error: Error compiling query code (in /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c). Compiler command '/nix/store/c1ib07kj7baid3s3wf5m98hcpbvgs8mk-clang-wrapper-16.0.6/bin/cc -Wall -Werror -Wno-tautological-compare -ObjC -o /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c' output included error: /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c:34:10: fatal error: 'Foundation/Foundation.h' file not found
Error:      C file contents around line 34:
Error:      /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c:33: #include <unistd.h>
Error:      /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c:34: #include <Foundation/Foundation.h>
Error:      /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c:35: #include <mach/mach.h>
Error:  com.oracle.svm.core.util.UserError$UserException: Error compiling query code (in /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c). Compiler command '/nix/store/c1ib07kj7baid3s3wf5m98hcpbvgs8mk-clang-wrapper-16.0.6/bin/cc -Wall -Werror -Wno-tautological-compare -ObjC -o /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c' output included error: /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c:34:10: fatal error: 'Foundation/Foundation.h' file not found
Error:      C file contents around line 34:
Error:      /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c:33: #include <unistd.h>
Error:      /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c:34: #include <Foundation/Foundation.h>
Error:      /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/SVM-14881555311105086393/PosixDirectives.c:35: #include <mach/mach.h>
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:138)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.reportErrors(NativeLibraries.java:380)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1791)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1237)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:979)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:569)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:537)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:526)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:701)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:140)
Error:  	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:95)
```

**Comment by hlolli** [comment]
I really should take myself off the graalvm maintainer list, but it looks like a simple fix to add the missing apple sdk Framework into build dependencies:

"fatal error: 'Foundation/Foundation.h' file not found"

**Comment by pshirshov** [comment]
`darwin.CF`? Ok, thank you, will try.

**Comment by hlolli** [comment]
I'd go for

```
nix-repl> darwin.apple_sdk.frameworks.Foundation
«derivation /nix/store/aadqc8mysg7y7h3k75rihsjjaqxb88yd-apple-framework-Foundation-11.0.0.drv»
```

look out for if there are already Frameworks passed into the derivation, it's often destructured because it's a long reference path.

**Comment by pshirshov** [comment]
I've tried to add it into `nativeBuildInputs`, it didn't help:

```nix
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/24.05.tar.gz") { } }:

pkgs.mkShell {
  nativeBuildInputs = with pkgs.buildPackages; [
    ncurses
    graalvm-ce
    sbt
    dotnet-sdk_7
    darwin.apple_sdk.frameworks.Foundation
  ];
}
```

Will try to play more

**Comment by pshirshov** [comment]
Interesting. If I invoke `cc` manually, it works:

```
# cat test.cpp

#include <Foundation/Foundation.h>

int main() {
    return 0;
}

# nix-shell --pure shell-mac.nix --run "cc -Wall -Werror -Wno-tautological-compare -ObjC test.cpp" && echo ok
ok
```

**Comment by hlolli** [comment]
Yeh I'm getting flashback on native-image and the substrate-vm systems. These are self-contained compiler environments, it sounds like hands dirty kind of work here. I think if you compile unsandboxed, the Foundation headers will be found on your own system. But in this compiler in a compiler environment, it's probably not found. Does it work if you disable nix_sandbox?

**Comment by pshirshov** [comment]
This didn't work:

```nix
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/24.05.tar.gz") { } }:

pkgs.mkShell {
  nativeBuildInputs = with pkgs.buildPackages; [
    ncurses

    (graalvm-ce.overrideDerivation (oldAttrs: {
                name = "graalvm-customized";
                buildInputs = oldAttrs.buildInputs ++ [ darwin.apple_sdk.frameworks.Foundation ];
              }))

    sbt
    dotnet-sdk_7
    darwin.apple_sdk.frameworks.Foundation
  ];
}
```

This didn't work either:

```nix
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/24.05.tar.gz") { } }:

pkgs.mkShell {
  nativeBuildInputs = with pkgs.buildPackages; [
    ncurses

    (graalvm-ce.overrideDerivation (oldAttrs: {
                name = "graalvm-customized";
                nativeBuildInputs = oldAttrs.nativeBuildInputs ++ [ darwin.apple_sdk.frameworks.Foundation ];
              }))

    sbt
    dotnet-sdk_7
    darwin.apple_sdk.frameworks.Foundation
  ];
}
```

Regarding the sandbox - I've tried to run `nix-shell` with `--impure`, it doesn't change anything. Not sure if that's what you are talking about.

**Comment by hlolli** [comment]
Maybe --impure was just for passing environment variables down to the nix build context. Try "nix ... --no-sandbox" or "nix ... --option sandbox false"

**Comment by pshirshov** [comment]
Tried. Unfortunately, nothing changes.

**Comment by pshirshov** [comment]
Also, from what I can see, the frameworks package is already there: https://github.com/NixOS/nixpkgs/blob/c5636b77afb8194e3cc3bc4a0eb5f6cc66313376/pkgs/development/compilers/graalvm/community-edition/buildGraalvm.nix#L109

**Comment by pshirshov** [comment]
Another observation: if I use the same `native-image` outside of `nix shell` - it just works.

**Comment by pshirshov** [comment]
Aha, `NATIVE_IMAGE_DEPRECATED_BUILDER_SANITATION` helps. That issue I linked was relevant.

**Comment by pshirshov** [comment]
By the way, on amd64 Macs these two variables are necessary:

```
                                        "-ENIX_CC_WRAPPER_TARGET_HOST_x86_64_apple_darwin",
                                        "-ENIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_apple_darwin",
```

**Comment by thiagokokada** [comment]
So to clarify the current situation of `graalvm-ce` in `darwin`: it mostly exists to build packages inside `nixpkgs`, we don't explicit support usage of it outside with e.g.: `buildGraalvmNativeImage` functions.

> I think this should be somehow incorporated into graalvm-ce formula itself.

If you want to do so feel free. We probably want to wrap `native-image` binary with those flags.

**Comment by pshirshov** [comment]
If someone happens to come across this issue, this patch fixes it for me:

```
                (graalvm-ce.overrideDerivation (oldAttrs: {

                  postInstall = let darwinArgs =  pkgs.lib.optionals stdenv.hostPlatform.isDarwin [
                                                       "-ENIX_BINTOOLS"
                                                       "-ENIX_CC"
                                                       "-ENIX_CFLAGS_COMPILE"
                                                       "-ENIX_LDFLAGS"
                                                       "-EbuildInputs"
                                                       "-EcmakeFlags"
                                                       "-EnativeBuildInputs"
                                                       "-EpropagatedBuildInputs"
                                                       "-EpropagatedNativeBuildInputs"
                                                       "-ENIX_CC_WRAPPER_TARGET_HOST_${pkgs.stdenv.cc.suffixSalt}"
                                                       "-ENIX_BINTOOLS_WRAPPER_TARGET_HOST_${pkgs.stdenv.cc.suffixSalt}"
                                               ];

                                                darwinFlags = (map (f: "--add-flags '${f}'") darwinArgs);
                                                in

                  pkgs.lib.replaceStrings ["/bin/native-image"] ["/bin/native-image ${toString (darwinFlags)}"] oldAttrs.postInstall;
                }))
```

This can be easily converted into a patch for the formula itself, although I am frightened by the idea of opening a P/R into nixpkgs.

**Comment by pshirshov** [comment]
Ok, I've opened a P/R. If I am to be humiliated again for formatting or some other murky convention, this will be my last attempt to contribute anything into nixpkgs.

**Comment by fzakaria** [comment]
Came across this; thank you for the fix. 
I was on 24-05 -- will try unstable.
