### ISSUE TITLE
pgadmin4 fails to start: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by tinou98** [NixOS/nixpkgs#351274]
### Describe the bug
`pgadmin4-desktopmode` (and `pgadmin4`) fails to start due to a missing module : `ModuleNotFoundError: No module named 'pkg_resources'` 

### Steps To Reproduce
1. `nix run nixpkgs#pgadmin4-desktopmode`

### Expected behavior
The application to run

### Screenshots
```bash
❯ nix run nixpkgs#pgadmin4-desktopmode
Traceback (most recent call last):
  File "/nix/store/0j1w4f5x2wbygg3hz4if2irlj2rrk2bf-pgadmin-8.12/bin/.pgadmin4-wrapped", line 6, in <module>
    from pgadmin4.pgAdmin4 import main
  File "/nix/store/0j1w4f5x2wbygg3hz4if2irlj2rrk2bf-pgadmin-8.12/lib/python3.12/site-packages/pgadmin4/pgAdmin4.py", line 48, in <module>
    import config
  File "/nix/store/0j1w4f5x2wbygg3hz4if2irlj2rrk2bf-pgadmin-8.12/lib/python3.12/site-packages/pgadmin4/config.py", line 33, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/nix/store/0j1w4f5x2wbygg3hz4if2irlj2rrk2bf-pgadmin-8.12/lib/python3.12/site-packages/pgadmin4/pgadmin/__init__.py", line 32, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore, current_user
  File "/nix/store/rpp6k594x68s4w50vngfbg069pyq49lf-python3.12-flask-security-5.5.2/lib/python3.12/site-packages/flask_security/__init__.py", line 16, in <module>
    from .core import (
  File "/nix/store/rpp6k594x68s4w50vngfbg069pyq49lf-python3.12-flask-security-5.5.2/lib/python3.12/site-packages/flask_security/core.py", line 88, in <module>
    from .totp import Totp
  File "/nix/store/rpp6k594x68s4w50vngfbg069pyq49lf-python3.12-flask-security-5.5.2/lib/python3.12/site-packages/flask_security/totp.py", line 18, in <module>
    from passlib.pwd import genword
  File "/nix/store/a920dbsqj9v3qmxlzr8z5qdgaqyfjlk0-python3.12-passlib-1.7.4/lib/python3.12/site-packages/passlib/pwd.py", line 16, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

### Additional context
It seems that `passlib` require `pkg_resources` / `setuptools`, a fix like #334190

### Notify maintainers

@dotlambda 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241023.2768c7d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gador** [comment]
I'm the maintainer, not @dotlambda ..
