### ISSUE TITLE
Build failure: upower-1.90.4 (from master branch after staging was merged #348827)

### ISSUE THREAD

**Issue by spiage** [NixOS/nixpkgs#352556]
### Steps To Reproduce

1. build from master branch

### Build log

```
error: builder for '/nix/store/64yi8y17a3xksjzzcz9nzbrxckvpz56z-upower-1.90.4.drv' failed with exit code 1;
       last 25 log lines:
       > 57/68 Tests.test_bluetooth_mouse_reconnect                               OK              9.01s
       > 58/68 Tests.test_headset_wireless_status                                 OK              6.37s
       > 59/68 Tests.test_unknown_battery_status_no_ac                            OK              4.04s
       > 60/68 Tests.test_virtual_unparented_device                               OK              4.07s
       > 61/68 Tests.test_vendor_strings                                          OK              4.31s
       > 62/68 Tests.test_usb_joypad                                              OK              4.45s
       > 63/68 Tests.test_wacom_dongle                                            OK              4.13s
       > 64/68 Tests.test_hidpp_touchpad                                          OK              8.90s
       > 65/68 Tests.test_macbook_uevent                                          OK              8.46s
       > 66/68 Tests.test_prevent_sleep_until_critical_action_is_executed         OK             23.06s
       > 67/68 Tests.test_critical_action_is_taken_repeatedly                     OK             45.73s
       > 68/68 Tests.test_battery_state_guessing                                  OK             71.88s
       >
       > Summary of Failures:
       >
       > 12/68 Tests.test_bluetooth_hidpp_mouse                           FAIL            3.12s   exit status 1
       >
       > Ok:                 67
       > Expected Fail:      0
       > Fail:               1
       > Unexpected Pass:    0
       > Skipped:            0
       > Timeout:            0
       >
       > Full log written to /build/source/build/meson-logs/testlog.txt
       For full logs, run 'nix log /nix/store/64yi8y17a3xksjzzcz9nzbrxckvpz56z-upower-1.90.4.drv'.
error: 1 dependencies of derivation '/nix/store/qghn64sfln3ssibg03dmww0hm2zqlw8x-power-profiles-daemon-0.23.drv' failed to build
```
```
stderr:
E
======================================================================
ERROR: test_bluetooth_hidpp_mouse (__main__.Tests.test_bluetooth_hidpp_mouse)
Logitech Bluetooth LE mouse with HID++ kernel support
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/build/../src/linux/integration-test.py", line 2337, in test_bluetooth_hidpp_mouse
    self.assertEqual(self.get_dbus_dev_property(bat0_up, 'Model'), alias)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/build/../src/linux/integration-test.py", line 273, in get_dbus_dev_property
    return self.dbus.call_sync(UP, device,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/UPower/devices/mouse_dev_11_22_33_44_AA_BB” (19)

----------------------------------------------------------------------
Ran 1 test in 2.153s

FAILED (errors=1)
```

### Notify maintainers

@vcunat 

### Metadata

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5, NixOS, 24.11 (Vicuna), 24.11.20241031.ca6305b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `""`
 - nixpkgs: `/nix/store/rv1na2yjsird2710l1m3smyb7sn5212d-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by spiage** [comment]
@NixOS/freedesktop

**Comment by vcunat** [comment]
I think I've seen something like this in the past and it was transient, disappearing after a retry or two.  Though yes, it's nice to fix such flakiness, too.  I tried now locally and it succeeded on the first try (on x86_64-linux).

**Comment by spiage** [comment]
I do not understand how but second run of nixos-rebuild switch shows no errors...
You was right, I have the same
May I close this issue?

**Comment by appsforartists** [comment]
When upgrading to `release-24.11`:

```
building the system configuration...
error: builder for '/nix/store/wl1i9lzdnam4apma76rflgj4ivmaxb76-power-profiles-daemon-0.23.drv' failed with exit code 3;
       last 10 log lines:
       > 110/115 Tests.test_amd_pstate_upower                                                      FAIL            8.31s   exit status 1
       >
       > Ok:                 112
       > Expected Fail:      0
       > Fail:               3
       > Unexpected Pass:    0
       > Skipped:            0
       > Timeout:            0
       >
       > Full log written to /build/source/build/meson-logs/testlog.txt
       For full logs, run 'nix log /nix/store/wl1i9lzdnam4apma76rflgj4ivmaxb76-power-profiles-daemon-0.23.drv'.
error: 1 dependencies of derivation '/nix/store/79x94fg729pd5x38m2kkrlsqj36n1hkl-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mvx663bbr6849xzwv32r2q4bkgc6hqfk-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/apv5ihvljphxzf5d1jp9njpb1szfy7hx-udev-rules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zqdirqpjbqdb463przg3yplb5lgf2fyj-nixos-system-brenton-go-24.11.20241121.aa2d10c.drv' failed to build
nixos-rebuild failed with exit status 1.
```

Ran the same `nixos-rebuild switch` command again, and looks like it's working…

**Comment by spiage** [comment]
known workaround: to build second time

**Comment by Pleune** [comment]
It seems like this still happens. I ran into this building from current master. Maybe we should disable this test?
