### ISSUE TITLE
Packaging request: Portfolio Performance

### ISSUE THREAD

**Issue by oyren** [NixOS/nixpkgs#35267]
Packaging request for https://github.com/buchen/portfolio

Feel free to comment here if you start working on it.

**Comment by oyren** [comment]
I tried to package it today, after `patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" PortfolioPerformance`, I get:
    $ ./PortfolioPerformance   
    PortfolioPerformance:
    An error has occurred. See the log file
    /home/user/test/portfolio/configuration/1542307604668.log.

1542307604668.log
```
!SESSION 2018-11-15 19:46:44.584 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.1-internal
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2018-11-15 19:46:45.867
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: org.eclipse.swt.internal.gtk.OS._cachejvmptr()V
	at org.eclipse.swt.internal.gtk.OS._cachejvmptr(Native Method)
	at org.eclipse.swt.internal.gtk.OS.cachejvmptr(OS.java:481)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:92)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:134)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:80)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:142)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:144)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
```
