### ISSUE TITLE
commix: No module named 'src.thirdparty.six.moves'

### ISSUE THREAD

**Issue by Mag1cByt3s** [NixOS/nixpkgs#352878]
### Describe the bug
The python module six / six.moves seems to be missing from the package commix. I found the same issue on Kali Linux here: https://gitlab.com/kalilinux/packages/commix/-/issues/2. On Kali the issue was fixed by this commit: https://gitlab.com/kalilinux/packages/commix/-/commit/1947c44d8219ed63b5c0426479c58ead34670fd0

### Steps To Reproduce
1. install commix
2. run commix with any parameter or no parameters at all
3. get the error:
```bash
Traceback (most recent call last):
  File "/nix/store/bmn5h3kcrp7jc1j2qdfcjw48xw92wlgi-commix-3.9/bin/.commix-wrapped", line 6, in <module>
    from src.core.main import entry_point
  File "/nix/store/bmn5h3kcrp7jc1j2qdfcjw48xw92wlgi-commix-3.9/lib/python3.12/site-packages/src/core/main.py", line 20, in <module>
    from src.thirdparty.six.moves import http_client as _http_client
ModuleNotFoundError: No module named 'src.thirdparty.six.moves'
```

### Expected behavior
commix should be able to import the python module six.moves without issues.

### Notify maintainers

@fabaff 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, Red Flake, rolling, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fabaff** [comment]
Hmm, the proper fix would be to not vendorize modules.

- https://github.com/NixOS/nixpkgs/pull/359227
