### ISSUE TITLE
bug: error running vimUpdatePlugins

### ISSUE THREAD

**Issue by AxerTheAxe** [NixOS/nixpkgs#353044]
### Describe the bug
When following the steps listed [here](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs-adding-new-plugins-to-nixpkgs) to generate a `generated.nix` I get an error.

### Steps To Reproduce
1. run `nix-shell -p vimPluginsUpdater --run vim-plugins-updater`

### Expected behavior
Successfully run vimPluginsUpdater 

### Additional context
Here is the full error that I receive upon calling the command.
```
kat@desktop:~/nixpkgs/pkgs/applications/editors/vim/plugins/ > nix-shell -p vimPluginsUpdater --run vim-plugins-updater
error:
       … from call site
         at «string»:1:6:
            1| with import <localpkgs> { };
             |      ^
            2| let

       error: function 'anonymous lambda' called without required argument 'vimUtils'
       at /home/kat/nixpkgs/pkgs/applications/editors/vim/plugins/default.nix:2:1:
            1| # TODO check that no license information gets lost
            2| { callPackage, config, lib, vimUtils, vim, darwin, llvmPackages
             | ^
            3| , neovim-unwrapped
Traceback (most recent call last):
  File "/nix/store/l763dfigfg10p4kk2kyx70jfryb5ms1d-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 182, in <module>
    main()
  File "/nix/store/l763dfigfg10p4kk2kyx70jfryb5ms1d-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 178, in main
    editor.run()
  File "/nix/store/13f71n783zs7d9ac63bkdazx8kr14dd0-pluginupdate-py/pluginupdate.py", line 568, in run
    getattr(self, command)(args)
  File "/nix/store/l763dfigfg10p4kk2kyx70jfryb5ms1d-vim-plugins-updater-0.1/bin/..vim-plugins-updater-wrapped-wrapped", line 137, in update
    pluginupdate.update_plugins(self, args)
  File "/nix/store/13f71n783zs7d9ac63bkdazx8kr14dd0-pluginupdate-py/pluginupdate.py", line 800, in update_plugins
    update = editor.get_update(args.input_file, args.outfile, fetch_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/13f71n783zs7d9ac63bkdazx8kr14dd0-pluginupdate-py/pluginupdate.py", line 429, in get_update
    cache: Cache = Cache(self.get_current_plugins(self.nixpkgs), self.cache_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/13f71n783zs7d9ac63bkdazx8kr14dd0-pluginupdate-py/pluginupdate.py", line 413, in get_current_plugins
    data = run_nix_expr(self.get_plugins, nixpkgs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/13f71n783zs7d9ac63bkdazx8kr14dd0-pluginupdate-py/pluginupdate.py", line 351, in run_nix_expr
    out = subprocess.check_output(cmd, **args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wfbjq35kxs6x83c3ncpfxdyl5gbhdx4h-python3-3.12.6/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix', 'eval', '--extra-experimental-features', 'nix-command', '--impure', '--json', '--expr', 'with import <localpkgs> { };\nlet\n  inherit (vimUtils.override { inherit vim; }) buildVimPlugin;\n  inherit (neovimUtils) buildNeovimPlugin;\n\n  generated = callPackage <localpkgs/pkgs/applications/editors/vim/plugins/generated.nix> {\n    inherit buildNeovimPlugin buildVimPlugin;\n  } { } { };\n  hasChecksum =\n    value:\n    lib.isAttrs value\n    && lib.hasAttrByPath [\n      "src"\n      "outputHash"\n    ] value;\n  getChecksum =\n    name: value:\n    if hasChecksum value then\n      {\n        submodules = value.src.fetchSubmodules or false;\n        sha256 = value.src.outputHash;\n        rev = value.src.rev;\n      }\n    else\n      null;\n  checksums = lib.mapAttrs getChecksum generated;\nin\nlib.filterAttrs (n: v: v != null) checksums\n', '--nix-path', 'localpkgs=/home/kat/nixpkgs/pkgs/applications/editors/vim/plugins']' returned non-zero exit status 1.
```

### Notify maintainers

@teto 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5, NixOS, 24.11 (Vicuna), 24.11.20241025.18536bf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
there is probably something odd in your nix channels. What if you use the flake version `nix run github:nixos/nixpkgs/nixos-unstable#vimPluginsUpdater` ?

**Comment by AxerTheAxe** [comment]
> there is probably something odd in your nix channels. What if you use the flake version `nix run github:nixos/nixpkgs/nixos-unstable#vimPluginsUpdater` ?

Same exact issue with that command.

**Comment by AxerTheAxe** [comment]
Seems to have fixed itself on it's own. You were probably right about it being something weird in my channels.
