### ISSUE TITLE
ssh-mitm: No module named 'nacl'

### ISSUE THREAD

**Issue by Mag1cByt3s** [NixOS/nixpkgs#353292]
### Describe the bug
The python package nacl seems to be missing from the package ssh-mitm.

### Steps To Reproduce
1. install ssh-mitm
2. run ssh-mitm with any parameter or no parameters at all
3. get the error:
```
/nix/store/9jv0p1wl18940nr036acp3gvq5xhm4lc-python3.12-paramiko-3.3.1/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
Traceback (most recent call last):
  File "/nix/store/s64h4swcn6mqypl4si3rmm8ax45a093n-ssh-mitm-4.1.1/bin/.ssh-mitm-wrapped", line 6, in <module>
    from sshmitm.cli import main
  File "/nix/store/s64h4swcn6mqypl4si3rmm8ax45a093n-ssh-mitm-4.1.1/lib/python3.12/site-packages/sshmitm/cli.py", line 42, in <module>
    from paramiko import Transport
  File "/nix/store/9jv0p1wl18940nr036acp3gvq5xhm4lc-python3.12-paramiko-3.3.1/lib/python3.12/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import (
  File "/nix/store/9jv0p1wl18940nr036acp3gvq5xhm4lc-python3.12-paramiko-3.3.1/lib/python3.12/site-packages/paramiko/transport.py", line 94, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/nix/store/9jv0p1wl18940nr036acp3gvq5xhm4lc-python3.12-paramiko-3.3.1/lib/python3.12/site-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
ModuleNotFoundError: No module named 'nacl'
```

### Expected behavior
ssh-mitm / paramiko should be able to import the python module nacl without issues.

### Notify maintainers

@fabaff 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, Red Flake, rolling, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Mag1cByt3s** [comment]
Issue has apparently been fixed in staging recently: https://github.com/NixOS/nixpkgs/pull/353306#issuecomment-2453345689

Closing this.

**Comment by Mag1cByt3s** [comment]
Issue apparently has been recently fixed in staging: https://github.com/NixOS/nixpkgs/pull/353306#issuecomment-2453345689

Therefore closing this issue.
