### ISSUE TITLE
social-engineer-toolkit: Read-only file system: 'src/logs/'

### ISSUE THREAD

**Issue by Mag1cByt3s** [NixOS/nixpkgs#353307]
### Describe the bug
The package social-engineer-toolkit tries to create the logs directory in the nix store and tries to write logs into it. This fails since the nix store is read-only.

### Steps To Reproduce
1. install social-engineer-toolkit
2. run `setoolkit` as root with any parameter or no parameters at all
3. get the following error:
```bash
❯ sudo setoolkit --help
/nix/store/ay21kqpkx69q4r70rkk0srb2a5pndgbj-social-engineer-toolkit-8.0.3/share/social-engineer-toolkit/src/core/setcore.py:1358: SyntaxWarning: invalid escape sequence '\d'
  a = re.search("\d+/%s" % (flag), stdout_value)
/nix/store/ay21kqpkx69q4r70rkk0srb2a5pndgbj-social-engineer-toolkit-8.0.3/share/social-engineer-toolkit/src/core/setcore.py:1853: SyntaxWarning: invalid escape sequence '\.'
  p = re.compile("^([0-9]{1,3}\.){0,3}[0-9]{1,3}(/[0-9]{1,2}){1}$")
Traceback (most recent call last):
  File "/nix/store/ay21kqpkx69q4r70rkk0srb2a5pndgbj-social-engineer-toolkit-8.0.3/bin/.setoolkit-wrapped", line 77, in <module>
    os.makedirs("src/logs/")
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: 'src/logs/'
``` 

### Expected behavior
social-engineer-toolkit should write the logs outside of the nix-store, e.g. into /tmp, /var/tmp or into a different writable path.

### Notify maintainers

@emilytrau 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, Red Flake, rolling, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Mag1cByt3s** [comment]
I just noticed this issue was reported already and is a duplicate of: https://github.com/NixOS/nixpkgs/issues/287896. My bad will close this one.
