### ISSUE TITLE
Build failure: cargo-sweep

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#353443]
### Steps To Reproduce

1. build *cargo-sweep*

### Build log

```
     Running unittests src/main.rs (target/x86_64-unknown-linux-gnu/release/deps/cargo_sweep-3b5537329f9cf5bb)

running 4 tests
test fingerprint::tests::test_custom_toolchain ... ok
test util::tests::test_format_bytes ... ok
test cli::tests::test_maxsize_argument_parsing ... ok
test cli::tests::test_argparsing ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/integration.rs (target/x86_64-unknown-linux-gnu/release/deps/integration-ed96b2426c2beae1)

running 11 tests
test multiple_paths_and_stamp_errors ... ok
Testing tests/standalone-usage.trycmd:2 ... ok
Testing tests/usage-long.trycmd:2 ... ok
Testing tests/usage.trycmd:2 ... ok
test usage ... ok
test error_status ... ok
test empty_project_output ... FAILED
test hidden ... ok
test error_output ... ok
test stamp_file ... ok
test path ... ok
test multiple_paths ... ok
test all_flags ... ok
test recursive_multiple_root_workspaces ... ok

failures:

---- empty_project_output stdout ----
   Compiling sample-project v0.1.0 (/build/source/tests/sample-project)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.10s
[DEBUG] cleaning: "/build/.tmpCtUnAQ" with remove_older_until_fits
[DEBUG] size_to_remove: 48188
[DEBUG] Sizing: "/build/.tmpCtUnAQ/x86_64-unknown-linux-gnu/debug" with total_disk_space_in_a_profile
[DEBUG] Hashs by time: [
    (
        8.876279ms,
        "991194c9885d6152",
    ),
]
[DEBUG] Sizing: "/build/.tmpCtUnAQ/debug" with total_disk_space_in_a_profile
[DEBUG] Hashs by time: []
[DEBUG] cleaning: "/build/.tmpCtUnAQ/x86_64-unknown-linux-gnu/debug" with remove_not_built_with_in_a_profile
[DEBUG] Successfully removed: "/build/.tmpCtUnAQ/x86_64-unknown-linux-gnu/debug/deps/libsample_project-991194c9885d6152.rmeta"
[DEBUG] Successfully removed: "/build/.tmpCtUnAQ/x86_64-unknown-linux-gnu/debug/deps/sample_project-991194c9885d6152.d"
[DEBUG] Successfully removed: "/build/.tmpCtUnAQ/x86_64-unknown-linux-gnu/debug/deps/libsample_project-991194c9885d6152.rlib"
[DEBUG] Successfully removed: "/build/.tmpCtUnAQ/x86_64-unknown-linux-gnu/debug/.fingerprint/sample-project-991194c9885d6152"
[DEBUG] cleaning: "/build/.tmpCtUnAQ/debug" with remove_not_built_with_in_a_profile
[INFO] Cleaned 9.28 KiB from "/build/.tmpCtUnAQ"
thread 'empty_project_output' panicked at tests/integration.rs:260:5:
failed to output with regex pattern
pattern = \[DEBUG\] cleaning: ".+" with remove_older_until_fits
\[DEBUG\] size_to_remove: .+
\[DEBUG\] Sizing: ".+debug" with total_disk_space_in_a_profile
\[DEBUG\] Hashs by time: \[
    \(
        .+,
        ".+",
    \),
\]
\[DEBUG\] cleaning: ".+debug" with remove_not_built_with_in_a_profile
\[DEBUG\] Successfully removed: ".+sample_project.+"
(\s*\S*)*
\[INFO\] Cleaned .+ from ".+"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    empty_project_output

test result: FAILED. 10 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.46s

error: test failed, to rerun pass `--test integration`
error: builder for '/nix/store/g7s5hn9wk9fnjrmjjz8bw3ckcsi3w1hz-cargo-sweep-0.7.0.drv' failed with exit code 101;
       last 25 log lines:
       > [INFO] Cleaned 9.28 KiB from "/build/.tmpCtUnAQ"
       > thread 'empty_project_output' panicked at tests/integration.rs:260:5:
       > failed to output with regex pattern
       > pattern = \[DEBUG\] cleaning: ".+" with remove_older_until_fits
       > \[DEBUG\] size_to_remove: .+
       > \[DEBUG\] Sizing: ".+debug" with total_disk_space_in_a_profile
       > \[DEBUG\] Hashs by time: \[
       >     \(
       >         .+,
       >         ".+",
       >     \),
       > \]
       > \[DEBUG\] cleaning: ".+debug" with remove_not_built_with_in_a_profile
       > \[DEBUG\] Successfully removed: ".+sample_project.+"
       > (\s*\S*)*
       > \[INFO\] Cleaned .+ from ".+"
       > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       >
       >
       > failures:
       >     empty_project_output
       >
       > test result: FAILED. 10 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.46s
       >
       > error: test failed, to rerun pass `--test integration`
       For full logs, run 'nix log /nix/store/g7s5hn9wk9fnjrmjjz8bw3ckcsi3w1hz-cargo-sweep-0.7.0.drv'.
```

### Notify maintainers

@xrelkd @matthiasbeyer 

### Metadata

---

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5, NixOS, 24.11 (Vicuna), 24.11.20241029.807e915`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-lixpre20240527-0b91a4b`
 - nixpkgs: `/run/current-system/nixpkgs`

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by thefossguy** [comment]
What's weird is that for my commit of nixpkgs (`nixos-unstable`) in use, `cargo-sweep` wasn't modified in the last few days [0]. 


[0]: https://github.com/NixOS/nixpkgs/commits/7ffd9ae656aec493492b44d0ddfb28e79a1ea25d/pkgs/development/tools/rust/cargo-sweep/default.nix

**Comment by bbigras** [comment]
Thanks everyone!
