### ISSUE TITLE
yubikey-manager-qt: yubikey doesn't detected with error

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#353582]
### Describe the bug
Yubikey doesn't detected with error.

### Steps To Reproduce
1. insert yubikey
2. run `ykman-gui`

### Expected behavior
Yubikey should be detected.

### Screenshots
![image](https://github.com/user-attachments/assets/1cb16155-4db6-4074-a1d2-61921dace375)

### Additional context
log
```
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 53, in <module>\n    from ykman.otp import (\n\nImportError: cannot import name '_PrepareUploadFailed' from 'ykman.otp' (/nix/store/cl63jh46vfk5cr6xrp172s44zvlbk69p-python3.12-yubikey-manager-5.5.1/lib/python3.12/site-packages/ykman/otp.py)\n"
qml: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 53, in <module>
    from ykman.otp import (

ImportError: cannot import name '_PrepareUploadFailed' from 'ykman.otp' (/nix/store/cl63jh46vfk5cr6xrp172s44zvlbk69p-python3.12-yubikey-manager-5.5.1/lib/python3.12/site-packages/ykman/otp.py)
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.init' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.refresh' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:/qml/YubiKey.qml:208: TypeError: Cannot read property 'success' of undefined
```

### Notify maintainers

@avdv 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.6, NixOS, 24.11 (Vicuna), 24.11.20241104.8a759c9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/2fj8ibynfsmpbrrj3zvqhp84zx50gdfr-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by avdv** [comment]
This seems to be related to https://github.com/NixOS/nixpkgs/issues/345391

From the yubikey-manager-qt github project:

> This project is no longer under active development. We recommend [Yubico Authenticator](https://github.com/Yubico/yubioath-flutter/) to configure a YubiKey.

**Comment by MisileLab** [comment]
> This seems to be related to #345391
> 
> From the yubikey-manager-qt github project:
> 
> > This project is no longer under active development. We recommend [Yubico Authenticator](https://github.com/Yubico/yubioath-flutter/) to configure a YubiKey.

then can we drop package like https://github.com/NixOS/nixpkgs/pull/353156 (or at least warning)

**Comment by Pandapip1** [comment]
Might be worth marking it as insecure instead. Users trust their yubikeys, and any software that interacts with them should be kept up-to-date. This has been deprecated by `yubioath-flutter`, and therefore shouldn't be used anymore.

**Comment by avdv** [comment]
> Might be worth marking it as insecure instead. Users trust their yubikeys, and any software that interacts with them should be kept up-to-date. This has been deprecated by `yubioath-flutter`, and therefore shouldn't be used anymore.

Good call. Done in https://github.com/NixOS/nixpkgs/pull/372205
