### ISSUE TITLE
Build failure: python3Packages.hikari

### ISSUE THREAD

**Issue by Shawn8901** [NixOS/nixpkgs#353691]
### Steps To Reproduce

1.  get a recent master
2. nix build .#python3Packages.hikari

### Build log
See https://hydra.nixos.org/build/276680955

```
[...]
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.3, pluggy-1.5.0
Using --randomly-seed=2222187566
rootdir: /build/source
configfile: pyproject.toml
plugins: asyncio-0.23.8, cov-nixpkgs-stub-1.0.0, pytest_randomly-3.13.0
asyncio: mode=Mode.STRICT
collected 3563 items                                                           
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/nix/store/bbvmyfhblj6ilf2yiik2cch5ark4imry-python3.11-pytest-8.3.3/lib/python3.11/site-packages/_pytest/main.py", line 283, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/nix/store/bbvmyfhblj6ilf2yiik2cch5ark4imry-python3.11-pytest-8.3.3/lib/python3.11/site-packages/_pytest/main.py", line 336, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/nix/store/4salglmd2wxr0giw6f48qrqm15srrkzj-python3.11-pluggy-1.5.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/nix/store/4salglmd2wxr0giw6f48qrqm15srrkzj-python3.11-pluggy-1.5.0/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/nix/store/4salglmd2wxr0giw6f48qrqm15srrkzj-python3.11-pluggy-1.5.0/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/nix/store/4salglmd2wxr0giw6f48qrqm15srrkzj-python3.11-pluggy-1.5.0/lib/python3.11/site-packages/pluggy/_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/nix/store/bbvmyfhblj6ilf2yiik2cch5ark4imry-python3.11-pytest-8.3.3/lib/python3.11/site-packages/_pytest/logging.py", line 790, in pytest_collection
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/nix/store/4salglmd2wxr0giw6f48qrqm15srrkzj-python3.11-pluggy-1.5.0/lib/python3.11/site-packages/pluggy/_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/nix/store/bbvmyfhblj6ilf2yiik2cch5ark4imry-python3.11-pytest-8.3.3/lib/python3.11/site-packages/_pytest/warnings.py", line 121, in pytest_collection
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/nix/store/4salglmd2wxr0giw6f48qrqm15srrkzj-python3.11-pluggy-1.5.0/lib/python3.11/site-packages/pluggy/_callers.py", line 124, in _multicall
INTERNALERROR>     teardown.send(result)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/nix/store/bbvmyfhblj6ilf2yiik2cch5ark4imry-python3.11-pytest-8.3.3/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1419, in pytest_collection
INTERNALERROR>     self._validate_config_options()
INTERNALERROR>   File "/nix/store/bbvmyfhblj6ilf2yiik2cch5ark4imry-python3.11-pytest-8.3.3/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1441, in _validate_config_options
INTERNALERROR>     self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
INTERNALERROR>   File "/nix/store/bbvmyfhblj6ilf2yiik2cch5ark4imry-python3.11-pytest-8.3.3/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1480, in _warn_or_fail_if_strict
INTERNALERROR>     self.issue_config_time_warning(PytestConfigWarning(message), stacklevel=3)
INTERNALERROR>   File "/nix/store/bbvmyfhblj6ilf2yiik2cch5ark4imry-python3.11-pytest-8.3.3/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1532, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR>   File "/build/source/tests/hikari/__init__.py", line 80, in warn
INTERNALERROR>     _warn(*args, **kwargs)
INTERNALERROR> pytest.PytestConfigWarning: Unknown config option: asyncio_default_fixture_loop_scope
```

### Notify maintainers
@tomodachi94  @sigmanificient

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Shawn8901** [comment]
FYI: As workaround i applied https://github.com/Shawn8901/nixpkgs/commit/4c492aac343b5dcff58be28f9f22c612b31065d7 on my fork, tho that is not new and i am absolutely not sure why it now break.

**Comment by Shawn8901** [comment]
i noticed that it never built since it was bumped from 2.0.0-dev to 2.1.0 (which is the tag that included the commit adding the option). As no one else was willing to dig deeper or raise a PR, i stepped now into place, as ZH fail time windows will end soon and i would like not having hikari marked as broken.
