### ISSUE TITLE
pythonPackages311.bugwarrior not working

### ISSUE THREAD

**Issue by TimShilov** [NixOS/nixpkgs#353713]
### Describe the bug
The `pythonPackages311.bugwarrior` package is simply not working. Seems like some dependency is missing.

### Steps To Reproduce
1. Run `nix-shell -p python311Packages.bugwarrior`
2. Inside the shell run `bugwarrior-pull --dry-run` => error is logged

### Expected behavior
The package should work without errors.

### Additional context
Logged error:
```
Traceback (most recent call last):
  File "/nix/store/fdlrgd5g5bzw3xzjs8agddgjl2p305c5-python3.11-bugwarrior-1.8.0/bin/.bugwarrior-pull-wrapped", line 9, in <module>
    sys.exit(pull())
             ^^^^^^
  File "/nix/store/j07fha9kiiwvg1nks4vi5r5056a3dk6q-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/j07fha9kiiwvg1nks4vi5r5056a3dk6q-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/j07fha9kiiwvg1nks4vi5r5056a3dk6q-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/j07fha9kiiwvg1nks4vi5r5056a3dk6q-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fdlrgd5g5bzw3xzjs8agddgjl2p305c5-python3.11-bugwarrior-1.8.0/lib/python3.11/site-packages/bugwarrior/command.py", line 62, in pull
    config = _try_load_config(main_section, interactive)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fdlrgd5g5bzw3xzjs8agddgjl2p305c5-python3.11-bugwarrior-1.8.0/lib/python3.11/site-packages/bugwarrior/command.py", line 35, in _try_load_config
    return load_config(main_section, interactive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fdlrgd5g5bzw3xzjs8agddgjl2p305c5-python3.11-bugwarrior-1.8.0/lib/python3.11/site-packages/bugwarrior/config.py", line 239, in load_config
    validate_config(config, main_section)
  File "/nix/store/fdlrgd5g5bzw3xzjs8agddgjl2p305c5-python3.11-bugwarrior-1.8.0/lib/python3.11/site-packages/bugwarrior/config.py", line 183, in validate_config
    if not get_service(service):
           ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fdlrgd5g5bzw3xzjs8agddgjl2p305c5-python3.11-bugwarrior-1.8.0/lib/python3.11/site-packages/bugwarrior/services/__init__.py", line 41, in get_service
    return epoint.load()
           ^^^^^^^^^^^^^
  File "/nix/store/rgr6i0lk26qgza4f3zracmydm1j9z9h4-python3.11-setuptools-72.1.0/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2770, in load
    self.require(*args, **kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rgr6i0lk26qgza4f3zracmydm1j9z9h4-python3.11-setuptools-72.1.0/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2798, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rgr6i0lk26qgza4f3zracmydm1j9z9h4-python3.11-setuptools-72.1.0/lib/python3.11/site-packages/pkg_resources/__init__.py", line 896, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rgr6i0lk26qgza4f3zracmydm1j9z9h4-python3.11-setuptools-72.1.0/lib/python3.11/site-packages/pkg_resources/__init__.py", line 937, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pbr>=2.0.0' distribution was not found and is required by stevedore
```

### Notify maintainers

@booxter

### Metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `""`
 - nixpkgs: `/nix/store/0z5aw6jjbjq9sqcd03gfa7zkk25nzwgc-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by panurg** [comment]
3.12 package also does not work:

``` console
~ ❯ bugwarrior-pull --dry-run
Traceback (most recent call last):
  File "/nix/store/hnagvjf6ibwjvacjbxjlfhf23a3xdkfv-python3.12-bugwarrior-1.8.0/bin/.bugwarrior-pull-wrapped", line 9, in <module>
    sys.exit(pull())
             ^^^^^^
  File "/nix/store/mjsdffm6i6w4hgyxp5i576fv8dc54qqg-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/mjsdffm6i6w4hgyxp5i576fv8dc54qqg-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/mjsdffm6i6w4hgyxp5i576fv8dc54qqg-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/mjsdffm6i6w4hgyxp5i576fv8dc54qqg-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hnagvjf6ibwjvacjbxjlfhf23a3xdkfv-python3.12-bugwarrior-1.8.0/lib/python3.12/site-packages/bugwarrior/command.py", line 62, in pull
    config = _try_load_config(main_section, interactive)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hnagvjf6ibwjvacjbxjlfhf23a3xdkfv-python3.12-bugwarrior-1.8.0/lib/python3.12/site-packages/bugwarrior/command.py", line 35, in _try_load_config
    return load_config(main_section, interactive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hnagvjf6ibwjvacjbxjlfhf23a3xdkfv-python3.12-bugwarrior-1.8.0/lib/python3.12/site-packages/bugwarrior/config.py", line 235, in load_config
    config.readfp(codecs.open(path, "r", "utf-8",))
    ^^^^^^^^^^^^^
AttributeError: 'BugwarriorConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
```

**Comment by miguelpduarte** [comment]
`pythonPackages312.bugwarrior` still does not work for me, and `python313Packages.bugwarrior` also has issues:

```
$ nix shell nixpkgs\#python313Packages.bugwarrior
error:
       … while evaluating the attribute 'drvPath'
         at /nix/store/g3z13ffr1wzw8m9wivqyni2nbjl956wj-source/lib/customisation.nix:418:7:
          417|     // {
          418|       drvPath =
             |       ^
          419|         assert condition;

       … while evaluating the attribute 'drvPath'
         at /nix/store/g3z13ffr1wzw8m9wivqyni2nbjl956wj-source/lib/customisation.nix:418:7:
          417|     // {
          418|       drvPath =
             |       ^
          419|         assert condition;

       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:37:12:
           36|
           37|   strict = derivationStrict drvAttrs;
             |            ^
           38|

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: future-1.0.0 not supported for interpreter python3.13
```

cc @nbp
