### ISSUE TITLE
Build failure: nixos/gotosocial tests

### ISSUE THREAD

**Issue by blakesmith** [NixOS/nixpkgs#353896]
### Steps To Reproduce

```
$ nix run '.#nixosTests.gotosocial.driver'
```

### Build log

```
machine # Connection to localhost (127.0.0.1) 8081 port [tcp/sunproxyadmin] succeeded!
(finished: waiting for TCP port 8081 on localhost, in 10.31 seconds)
machine: must succeed: curl -sS -f http://localhost:8081/nodeinfo/2.0 | jq '.usage.users.total' | grep -q '^0$'
machine # [   18.020403] gotosocial[895]: timestamp="05/11/2024 19:43:57.095" func=server.init.func1.Logger.13.1 level=INFO latency="2.479365ms" userAgent=curl/8.10.1 method=GET statusCode=200 path=/nodeinfo/2.0 clientIP=127.0.0.1 requestID=mkrdnzcj04000660k0j0 msg="OK: wrote 222B"
(finished: must succeed: curl -sS -f http://localhost:8081/nodeinfo/2.0 | jq '.usage.users.total' | grep -q '^0$', in 0.03 seconds)
machine: must succeed: gotosocial-admin account create --username nickname --email email@example.com --password kurtz575VPeBgjVm
machine # [   18.046857] systemd[1]: Starting /nix/store/lxmp31j6rw54dzvx9qbyhqz63w8ad9ss-gotosocial-0.17.0/bin/gotosocial --config-path /nix/store/15ygiwfqvdvs73wckss6f876151v268q-config.yml admin account create --username nickname --email email@example.com --password kurtz575VPeBgjVm...
machine # [   18.066386] systemd[1]: Started /nix/store/lxmp31j6rw54dzvx9qbyhqz63w8ad9ss-gotosocial-0.17.0/bin/gotosocial --config-path /nix/store/15ygiwfqvdvs73wckss6f876151v268q-config.yml admin account create --username nickname --email email@example.com --password kurtz575VPeBgjVm.
machine # [   18.271955] systemd[1]: gotosocial-admin.service: Deactivated successfully.
(finished: must succeed: gotosocial-admin account create --username nickname --email email@example.com --password kurtz575VPeBgjVm, in 0.26 seconds)
machine: must succeed: curl -sS -f http://localhost:8081/nodeinfo/2.0 | jq '.usage.users.total' | grep -q '^1$'
machine # [   18.300332] gotosocial[895]: timestamp="05/11/2024 19:43:57.375" func=server.init.func1.Logger.13.1 level=INFO latency="68.724µs" userAgent=curl/8.10.1 method=GET statusCode=200 path=/nodeinfo/2.0 clientIP=127.0.0.1 requestID=qzrxnzcj040005wae7vg msg="OK: wrote 222B"
machine: output:
cleanup
kill machine (pid 2443946)
qemu-kvm: terminating on signal 15 from pid 2435823 (/nix/store/901c80rlps5q05bnjk1sj4zaz5k736nc-python3-3.12.7/bin/python3.12)
kill vlan (pid 2443944)
(finished: cleanup, in 0.01 seconds)
Traceback (most recent call last):
  File "/nix/store/srymsadvv6spa497nadazbnlj1rfmj9f-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/srymsadvv6spa497nadazbnlj1rfmj9f-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/__init__.py", line 146, in main
    driver.run_tests()
  File "/nix/store/srymsadvv6spa497nadazbnlj1rfmj9f-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/driver.py", line 175, in run_tests
    self.test_script()
  File "/nix/store/srymsadvv6spa497nadazbnlj1rfmj9f-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/driver.py", line 167, in test_script
    exec(self.tests, symbols, None)
  File "<string>", line 8, in <module>
  File "/nix/store/srymsadvv6spa497nadazbnlj1rfmj9f-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/machine.py", line 611, in succeed
    raise Exception(f"command `{command}` failed (exit code {status})")
Exception: command `curl -sS -f http://localhost:8081/nodeinfo/2.0 | jq '.usage.users.total' | grep -q '^1$'` failed (exit code 1)
```

The test shows that the admin user was never created:

```
$ nix run '.#nixosTests.gotosocial.driverInteractive'
>>> start_all()
>>> run_tests()
>>> machine.execute("curl -sS -f http://localhost:8081/nodeinfo/2.0 | jq -c '.'")
machine # [   90.753716] gotosocial[868]: timestamp="04/11/2024 14:14:39.775" func=server.init.func1.Logger.13.1 level=INFO latency="64.534µs" userAgent=curl/8.9.1 method=GET statusCode=200 path=/nodeinfo/2.0 clientIP=127.0.0.1 requestID=krdrfxwj04000sg75seg msg="OK: wrote 222B"
(0, '{"version":"2.0","software":{"name":"gotosocial","version":"0.17.0"},"protocols":["activitypub"],"services":{"inbound":[],"outbound":[]},"openRegistrations":false,"usage":{"users":{"total":0},"localPosts":0},"metadata":{}}\n')
```

### Additional context

Related to: https://github.com/NixOS/nixpkgs/pull/352632. Encountered while attempting to update gotosocial to latest.

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by blakesmith** [comment]
Looks like the issue might be something in upstream gotosocial (need to confirm). With the latest nixos-unstable, the existing tests pass when rolling back to gotosocial 0.16.0 (and building with Golang 1.22). Going to go through the gotosocial changelog and see if anything jumps out, or if something else is going on.

From latest nixos-unstable, tests pass with the last version, but not latest version:

```
diff --git a/pkgs/servers/gotosocial/default.nix b/pkgs/servers/gotosocial/default.nix
index ef7646e9dd4a..aae1241660d3 100644
--- a/pkgs/servers/gotosocial/default.nix
+++ b/pkgs/servers/gotosocial/default.nix
@@ -2,28 +2,28 @@
   lib,
   fetchurl,
   fetchFromGitHub,
-  buildGoModule,
+  buildGo122Module,
   nixosTests,
 }:
 let
   owner = "superseriousbusiness";
   repo = "gotosocial";

-  version = "0.17.0";
+  version = "0.16.0";

   web-assets = fetchurl {
     url = "https://github.com/${owner}/${repo}/releases/download/v${version}/${repo}_${version}_web-assets.tar.gz";
-    hash = "sha256-ASqPIf98qdnkh3j72ifQN3mWnzNCTRcUegmrStvQ08Q=";
+    hash = "sha256-aZQpd5KvoZvXEMVzGbWrtGsc+P1JStjZ6U5mX6q7Vb0=";
   };
 in
-buildGoModule rec {
+buildGo122Module rec {
   inherit version;
   pname = repo;

   src = fetchFromGitHub {
     inherit owner repo;
     rev = "refs/tags/v${version}";
-    hash = "sha256-uyqP3zhjcXKejGFAwZoTn2kY8IpX0QAAXNzb1VG6ve8=";
+    hash = "sha256-QoG09+jmq5e5vxDVtkhY35098W/9B1HsYTuUnz43LV4=";
   };

   vendorHash = null;
```
