### ISSUE TITLE
Build failure: qtwebengine-6.8.0 fails to build.

### ISSUE THREAD

**Issue by victorhooi** [NixOS/nixpkgs#353924]
### Steps To Reproduce

This is on a macOS 15.0.1 machine, using [this NixOS template](https://github.com/dustinlyons/nixos-config).

_I don't know if this is related to the recent updates to the macOS SDK? I did notice in the log files, it says:_

```
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/p3hq1kd6lw5zwqznwzsh4gy72mmhriwp-apple-sdk-15.0/Toolchains/XcodeDefault.xctoolchain/usr/bin/metal'
```

In my case, it seems I need `qtwebengine` due to `sdrangel`

1. Run `nix run ./#build-switch)
2. Which then builds qtwebengine

### Build log

Output at the console:

```
❯ nix run ./#build-switch
warning: Git tree '/Users/foobar/nixos-config' is dirty
Running build-switch for aarch64-darwin
Starting build...
warning: Git tree '/Users/foobar/nixos-config' is dirty
error: builder for '/nix/store/p9icf7i27d4cx2cbcz8a7v9qvihrjr46-qtwebengine-6.8.0.drv' failed with exit code 1;
       last 25 log lines:
       >     return subprocess.run(args, stdout=subprocess.PIPE, text=True).returncode
       >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/2djmffykchgm4q4j7ylv7xgkg441mp2j-python3-3.12.7/lib/python3.12/subprocess.py", line 548, in run
       >     with Popen(*popenargs, **kwargs) as process:
       >          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/2djmffykchgm4q4j7ylv7xgkg441mp2j-python3-3.12.7/lib/python3.12/subprocess.py", line 1026, in __init__
       >     self._execute_child(args, executable, preexec_fn, close_fds,
       >   File "/nix/store/2djmffykchgm4q4j7ylv7xgkg441mp2j-python3-3.12.7/lib/python3.12/subprocess.py", line 1955, in _execute_child
       >     raise child_exception_type(errno_num, err_msg, err_filename)
       > FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/p3hq1kd6lw5zwqznwzsh4gy72mmhriwp-apple-sdk-15.0/Toolchains/XcodeDefault.xctoolchain/usr/bin/metal'
       > [5009/29770] CXX obj/net/third_party/quiche/quiche/oblivious_http_request.o
       > [5010/29770] CXX obj/net/third_party/quiche/quiche/encapsulated_web_transport.o
       > [5011/29770] CXX obj/net/tools/huffman_trie/huffman_trie_generator_sources/huffman_builder.o
       > [5012/29770] CXX obj/net/third_party/quiche/quiche/oblivious_http_response.o
       > [5013/29770] CXX obj/net/third_party/quiche/quiche/binary_http_message.o
       > [5014/29770] CXX obj/net/tools/huffman_trie/huffman_trie_generator_sources/trie_entry.o
       > [5015/29770] CXX obj/net/third_party/quiche/quiche/oblivious_http_client.o
       > [5016/29770] CXX obj/net/third_party/quiche/quiche/oblivious_http_gateway.o
       > [5017/29770] CXX obj/net/tools/huffman_trie/huffman_trie_generator_sources/trie_writer.o
       > [5018/29770] CXX obj/net/third_party/quiche/quiche/web_transport_priority_scheduler.o
       > [5019/29770] CXX obj/net/third_party/quiche/quiche/oblivious_http_header_key_config.o
       > ninja: build stopped: subcommand failed.
       > FAILED: src/core/Release/arm64/QtWebEngineCore.stamp src/core/Release/arm64/obj/tools/v8_context_snapshot/v8_context_snapshot.stamp src/core/Release/arm64/QtWebEngineCore /nix/store/k5cgyifvfcq2j1dxcxp6yzm8iqdxgfbr-qtwebengine-6.8.0/.build/qtwebengine-everywhere-src-6.8.0/build/src/core/Release/arm64/QtWebEngineCore.stamp /nix/store/k5cgyifvfcq2j1dxcxp6yzm8iqdxgfbr-qtwebengine-6.8.0/.build/qtwebengine-everywhere-src-6.8.0/build/src/core/Release/arm64/obj/tools/v8_context_snapshot/v8_context_snapshot.stamp /nix/store/k5cgyifvfcq2j1dxcxp6yzm8iqdxgfbr-qtwebengine-6.8.0/.build/qtwebengine-everywhere-src-6.8.0/build/src/core/Release/arm64/QtWebEngineCore
       > cd /nix/store/k5cgyifvfcq2j1dxcxp6yzm8iqdxgfbr-qtwebengine-6.8.0/.build/qtwebengine-everywhere-src-6.8.0/build/src/core && /nix/store/fm05zym1mwczjmg3y37z36cpfjh34x3f-ninja-1.12.1/bin/ninja -j12 -C /nix/store/k5cgyifvfcq2j1dxcxp6yzm8iqdxgfbr-qtwebengine-6.8.0/.build/qtwebengine-everywhere-src-6.8.0/build/src/core/Release/arm64 QtWebEngineCore
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/p9icf7i27d4cx2cbcz8a7v9qvihrjr46-qtwebengine-6.8.0.drv'.
error: 1 dependencies of derivation '/nix/store/4vaqfrr9rj2shglisz4q8xv6qisk9w18-sdrangel-7.22.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/h4vqw6sw312mgnqqi8biyrdwksa46m9v-home-manager-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qiijcaiywwkp4amx860s91gbr7lk92ls-home-manager-fonts.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rc5iigy1dfgwgjcb96l8dd3aawvhzqmg-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ykxc1k7vfggsqwmfyyd7f4v4nyq3mqvj-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rzsj4a0znl3njvfvvs2j4kfsg31fcmrs-sdrangel-7.22.2-fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2csv3xgkydmzwyjkmfr4j0rx4jx6sp41-system-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3y7zhpnhgnvsclr84ql2pd8qiwdvdcz1-darwin-system-24.11.20241102.7ffd9ae+darwin4.0e3f3f0.drv' failed to build
```

The build logs:

```
❯ nix log /nix/store/p9icf7i27d4cx2cbcz8a7v9qvihrjr46-qtwebengine-6.8.0.drv
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/p9icf7i27d4cx2cbcz8a7v9qvihrjr46-qtwebengine-6.8.0.drv^*'
Running phase: moveBuildDir
@nix { "action": "setPhase", "phase": "moveBuildDir" }
Running phase: qtPreHook
@nix { "action": "setPhase", "phase": "qtPreHook" }
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/30l78nr5l63fa0fhm395z6ff2w6g86z6-qtwebengine-everywhere-src-6.8.0.tar.xz
source root is qtwebengine-everywhere-src-6.8.0
setting SOURCE_DATE_EPOCH to timestamp 1727938699 of file qtwebengine-everywhere-src-6.8.0/.QT-ENTERPRISE-LICENSE-AGREEMENT
unpackPhase completed in 1 minutes 31 seconds
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
applying patch /nix/store/f5w51allfna0wvvckp1cmnzvcjnnjxfy-qtwebengine-xkb-includes.patch
patching file src/3rdparty/chromium/ui/events/ozone/layout/xkb/xkb_keyboard_layout_engine.cc
Hunk #1 succeeded at 639 (offset 2 lines).
applying patch /nix/store/314csygr8wl7r3sx3nrdpbmw6yl3jd2r-qtwebengine-link-pulseaudio.patch
patching file src/core/CMakeLists.txt
applying patch /nix/store/pkx20brdkm43f66gycc79lpcmz1bmn3b-qtwebengine-locales-path.patch
patching file src/core/api/CMakeLists.txt
Hunk #1 succeeded at 214 (offset 24 lines).
patching file src/core/web_engine_library_info.cpp
substituteStream() in derivation qtwebengine-6.8.0: WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'third_party/harfbuzz-ng/src/src/update-unicode-tables.make')
patching script interpreter paths in .
./v8/tools/draw_instruction_graph.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/rj7zvmif800bgg3sbznq6g5g438jx104-bash-5.2p37/bin/bash"
./v8/tools/testrunner/standard_runner.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/testrunner/local/statusfile_test.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/testrunner/local/testsuite_test.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/testrunner/local/pool_test.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/testrunner/testproc/shard_test.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/testrunner/testproc/variant_test.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/testrunner/testproc/loader_test.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/testrunner/num_fuzzer.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/android-sync.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/rj7zvmif800bgg3sbznq6g5g438jx104-bash-5.2p37/bin/bash"
./v8/tools/mac-nm: interpreter directive changed from "#!/bin/sh" to "/nix/store/rj7zvmif800bgg3sbznq6g5g438jx104-bash-5.2p37/bin/sh"
./v8/tools/gc-nvp-to-csv.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/builtins-pgo/download_profiles.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/builtins-pgo/profile_only.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/builtins-pgo/generate.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/builtins-pgo/combine_hints.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/builtins-pgo/get_hints.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/run.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/gen-v8-gn.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/generate_shim_headers/generate_shim_headers.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/bash-completion.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/rj7zvmif800bgg3sbznq6g5g438jx104-bash-5.2p37/bin/bash"
./v8/tools/sanitizers/sancov_formatter.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/sanitizers/sanitize_pcs.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/sanitizers/sancov_merger.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/objdump-v8: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/eval_gc_time.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/rj7zvmif800bgg3sbznq6g5g438jx104-bash-5.2p37/bin/bash"
./v8/tools/find-builtin: interpreter directive changed from "#!/bin/bash" to "/nix/store/rj7zvmif800bgg3sbznq6g5g438jx104-bash-5.2p37/bin/bash"
./v8/tools/check-static-initializers.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/rj7zvmif800bgg3sbznq6g5g438jx104-bash-5.2p37/bin/bash"
./v8/tools/memory/rss.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/get_landmines.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/run-clang-tidy.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/cross_build_gcc.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/rj7zvmif800bgg3sbznq6g5g438jx104-bash-5.2p37/bin/sh"
./v8/tools/generate-builtins-tests.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/wasm/update-wasm-fuzzers.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/rj7zvmif800bgg3sbznq6g5g438jx104-bash-5.2p37/bin/bash"
./v8/tools/wasm/update-wasm-spec-tests.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/rj7zvmif800bgg3sbznq6g5g438jx104-bash-5.2p37/bin/bash"
./v8/tools/wasm/code-size-factors.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/stats-viewer.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/system-analyzer/local-server.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/rj7zvmif800bgg3sbznq6g5g438jx104-bash-5.2p37/bin/bash"
./v8/tools/unittests/run_perf_test.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/unittests/predictable_wrapper_test.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/unittests/v8_presubmit_test.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/update-object-macros-undef.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
./v8/tools/v8_presubmit.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3"
...skipping...
[4974/29770] CXX obj/net/third_party/quiche/quiche/quic_session.o
[4975/29770] CXX obj/net/third_party/quiche/quiche/array_output_buffer.o
[4976/29770] CXX obj/net/third_party/quiche/quiche/quic_time_wait_list_manager.o
[4977/29770] CXX obj/net/third_party/quiche/quiche/quic_versions.o
[4978/29770] CXX obj/net/third_party/quiche/quiche/tls_chlo_extractor.o
[4979/29770] CXX obj/net/third_party/quiche/quiche/quic_write_blocked_list.o
[4980/29770] CXX obj/net/third_party/quiche/quiche/quic_socket_address.o
[4981/29770] CXX obj/net/third_party/quiche/quiche/hpack_entry.o
[4982/29770] CXX obj/net/third_party/quiche/quiche/uber_received_packet_manager.o
[4983/29770] CXX obj/net/third_party/quiche/quiche/hpack_constants.o
[4984/29770] CXX obj/net/third_party/quiche/quiche/hpack_output_stream.o
[4985/29770] CXX obj/net/third_party/quiche/quiche/tls_client_handshaker.o
[4986/29770] CXX obj/net/third_party/quiche/quiche/hpack_decoder_adapter.o
[4987/29770] CXX obj/net/third_party/quiche/quiche/tls_handshaker.o
[4988/29770] CXX obj/net/third_party/quiche/quiche/uber_quic_stream_id_manager.o
[4989/29770] CXX obj/net/third_party/quiche/quiche/hpack_encoder.o
[4990/29770] CXX obj/net/third_party/quiche/quiche/web_transport_stats.o
[4991/29770] CXX obj/net/third_party/quiche/quiche/tls_server_handshaker.o
[4992/29770] CXX obj/net/third_party/quiche/quiche/hpack_header_table.o
[4993/29770] CXX obj/net/third_party/quiche/quiche/spdy_alt_svc_wire_format.o
[4994/29770] CXX obj/net/third_party/quiche/quiche/hpack_static_table.o
[4995/29770] CXX obj/net/third_party/quiche/quiche/recording_headers_handler.o
[4996/29770] CXX obj/net/third_party/quiche/quiche/http2_frame_decoder_adapter.o
[4997/29770] CXX obj/net/third_party/quiche/quiche/spdy_frame_builder.o
[4998/29770] CXX obj/net/third_party/quiche/quiche/complete_buffer_visitor.o
[4999/29770] CXX obj/net/third_party/quiche/quiche/spdy_no_op_visitor.o
[5000/29770] CXX obj/net/third_party/quiche/quiche/spdy_framer.o
[5001/29770] CXX obj/net/third_party/quiche/quiche/spdy_protocol.o
[5002/29770] CXX obj/net/third_party/quiche/quiche/web_transport_headers.o
[5003/29770] CXX obj/net/tools/huffman_trie/huffman_trie_generator_sources/bit_writer.o
[5004/29770] CXX obj/net/tools/huffman_trie/huffman_trie_generator_sources/trie_bit_buffer.o
[5005/29770] STAMP obj/net/tools/transport_security_state_generator/transport_security_state_generator_sources.inputdeps.stamp
[5006/29770] STAMP obj/skia/public/mojom/mojom__type_mappings__validator.stamp
[5007/29770] STAMP obj/third_party/jpeg_includes.stamp
[5008/29770] ACTION //third_party/angle/src/libANGLE/renderer/metal:angle_metal_internal_shaders_to_air(//build/toolchain/mac:clang_arm64)
FAILED: gen/angle/mtl_internal_shaders_autogen.air 
/nix/store/sgmh5fy4b2idsmy788cz747mjam4vrcp-python3-3.12.7-env/bin/python3 ../../../../../src/3rdparty/chromium/third_party/angle/src/libANGLE/renderer/metal/shaders/metal_wrapper.py /nix/store/p3hq1kd6lw5zwqznwzsh4gy72mmhriwp-apple-sdk-15.0/To>
Traceback (most recent call last):
  File "/nix/store/k5cgyifvfcq2j1dxcxp6yzm8iqdxgfbr-qtwebengine-6.8.0/.build/qtwebengine-everywhere-src-6.8.0/build/src/core/Release/arm64/../../../../../src/3rdparty/chromium/third_party/angle/src/libANGLE/renderer/metal/shaders/metal_wrapper.>
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/nix/store/k5cgyifvfcq2j1dxcxp6yzm8iqdxgfbr-qtwebengine-6.8.0/.build/qtwebengine-everywhere-src-6.8.0/build/src/core/Release/arm64/../../../../../src/3rdparty/chromium/third_party/angle/src/libANGLE/renderer/metal/shaders/metal_wrapper.>
    return subprocess.run(args, stdout=subprocess.PIPE, text=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/2djmffykchgm4q4j7ylv7xgkg441mp2j-python3-3.12.7/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/2djmffykchgm4q4j7ylv7xgkg441mp2j-python3-3.12.7/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/2djmffykchgm4q4j7ylv7xgkg441mp2j-python3-3.12.7/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/p3hq1kd6lw5zwqznwzsh4gy72mmhriwp-apple-sdk-15.0/Toolchains/XcodeDefault.xctoolchain/usr/bin/metal'
[5009/29770] CXX obj/net/third_party/quiche/quiche/oblivious_http_request.o
[5010/29770] CXX obj/net/third_party/quiche/quiche/encapsulated_web_transport.o
[5011/29770] CXX obj/net/tools/huffman_trie/huffman_trie_generator_sources/huffman_builder.o
[5012/29770] CXX obj/net/third_party/quiche/quiche/oblivious_http_response.o
[5013/29770] CXX obj/net/third_party/quiche/quiche/binary_http_message.o
[5014/29770] CXX obj/net/tools/huffman_trie/huffman_trie_generator_sources/trie_entry.o
[5015/29770] CXX obj/net/third_party/quiche/quiche/oblivious_http_client.o
[5016/29770] CXX obj/net/third_party/quiche/quiche/oblivious_http_gateway.o
[5017/29770] CXX obj/net/tools/huffman_trie/huffman_trie_generator_sources/trie_writer.o
[5018/29770] CXX obj/net/third_party/quiche/quiche/web_transport_priority_scheduler.o
[5019/29770] CXX obj/net/third_party/quiche/quiche/oblivious_http_header_key_config.o
ninja: build stopped: subcommand failed.
FAILED: src/core/Release/arm64/QtWebEngineCore.stamp src/core/Release/arm64/obj/tools/v8_context_snapshot/v8_context_snapshot.stamp src/core/Release/arm64/QtWebEngineCore /nix/store/k5cgyifvfcq2j1dxcxp6yzm8iqdxgfbr-qtwebengine-6.8.0/.build/qtwe>
cd /nix/store/k5cgyifvfcq2j1dxcxp6yzm8iqdxgfbr-qtwebengine-6.8.0/.build/qtwebengine-everywhere-src-6.8.0/build/src/core && /nix/store/fm05zym1mwczjmg3y37z36cpfjh34x3f-ninja-1.12.1/bin/ninja -j12 -C /nix/store/k5cgyifvfcq2j1dxcxp6yzm8iqdxgfbr-qt>
ninja: build stopped: subcommand failed.
```

### Notify maintainers

@milahu @NickCao @K900 @reckenrode @Artturin @emilazy 

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sikmir** [comment]
qtwebengine-5.15.17 is broken as well on darwin.

**Comment by azuwis** [comment]
The maintaners did not get the ping because of a markdown syntax error:

```
ninja: build stopped: subcommand failed.```
```

should be:

````
ninja: build stopped: subcommand failed.
```
````

@victorhooi Can you please edit the OP?

The latest build on Hydra nixpkgs thunk

❌ https://hydra.nixos.org/job/nixpkgs/trunk/qt5.qtwebengine.aarch64-darwin
❌ https://hydra.nixos.org/job/nixpkgs/trunk/qt5.qtwebengine.x86_64-darwin
❌ https://hydra.nixos.org/job/nixpkgs/trunk/qt6.qtwebengine.aarch64-darwin
❌ https://hydra.nixos.org/job/nixpkgs/trunk/qt6.qtwebengine.x86_64-darwin
