### ISSUE TITLE
silverbullet crashes after restarting the service

### ISSUE THREAD

**Issue by gepbird** [NixOS/nixpkgs#354003]
### Describe the bug
After restarting the silverbullet service, it crashes. The first start works when there is no data in `/var/lib/silverbullet`, but as soon as that gets generated, trying to start silverbullet again fails.

### Steps To Reproduce
1. Go into your fork of nixpkgs and apply this patch to the existing nixos test:

```diff
diff --git a/nixos/tests/silverbullet.nix b/nixos/tests/silverbullet.nix
index e7e3cf536558..995eec7128e9 100644
--- a/nixos/tests/silverbullet.nix
+++ b/nixos/tests/silverbullet.nix
@@ -43,5 +43,9 @@ import ./make-test-python.nix ({ lib, ... }: {
     assert int(configured.succeed(f"curl --max-time 5 -s -o /dev/null -w '%{{http_code}}' -XPUT -d 'test' --fail http://{ADDRESS}:{PORT}/test.md -H'Authorization: Bearer test'")) == 200
     assert int(configured.fail(f"curl --max-time 5 -s -o /dev/null -w '%{{http_code}}' -XPUT -d 'test' --fail http://{ADDRESS}:{PORT}/test.md -H'Authorization: Bearer wrong'")) == 401
     configured.succeed(f"test -d '{SPACEDIR}'")
+
+    configured.succeed("systemctl restart silverbullet.service")
+    configured.execute("sleep 15") # wait_for_unit doesn't seem to work here
+    assert int(configured.succeed(f"curl --max-time 5 -s -o /dev/null -w '%{{http_code}}' -XPUT -d 'test' --fail http://{ADDRESS}:{PORT}/test.md -H'Authorization: Bearer test'")) == 200
   '';
 })
```

2. Run `nix build .#nixosTests.silverbullet`
3. Observe the failure

### Logs

<details><summary>silverbullet.service log after restart (trimmed)</summary>

```
Using KV as a database backend (/home/test/silverbullet/.silverbullet.db).
Going to start SilverBullet binding to localhost:3001
Using local disk as a storage backend: /home/test/silverbullet
Unhandled rejection: PromiseRejectionEvent {
  bubbles: false,
  cancelable: true,
  composed: false,
  currentTarget: Window {},
  defaultPrevented: false,
  eventPhase: 2,
  srcElement: null,
  target: Window {},
  returnValue: true,
  timeStamp: 0,
  type: "unhandledrejection",
  promise: Promise {
    <rejected> ReferenceError: window is not defined
    at IV.hashSHA256 (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:87:33860)
    at IV.init (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:87:33272)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async zX.init (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:2384:18073)
    at async rX.start (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:2385:7437)
    at async F.gj [as actionHandler] (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:2385:13469244)
    at async F.execute (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:24:8601)
    at async F.parseCommand (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:24:6314)
    at async file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:2418:6541
  },
  reason: ReferenceError: window is not defined
    at IV.hashSHA256 (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:87:33860)
    at IV.init (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:87:33272)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async zX.init (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:2384:18073)
    at async rX.start (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:2385:7437)
    at async F.gj [as actionHandler] (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:2385:13469244)
    at async F.execute (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:24:8601)
    at async F.parseCommand (file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:24:6314)
    at async file:///nix/store/w55cjcm10y9qidjxcjd5kq6x1mj9bh76-silverbullet-0.9.4/lib/silverbullet.js:2418:6541
}
```

</details>

### Expected behavior
Test should pass.

### Additional context
I noticed this issue when trying to set up silverbullet on our raspberry pi 4. Another thing is this issue doesn't happen without setting `SB_USER` and `SB_AUTH_TOKEN` environment variables.

### Notify maintainers

cc @aorith

### Metadata

```
 - system: `"aarch64-linux"`
 - host os: `Linux 6.11.5, NixOS, 24.11 (Vicuna), 24.11.20241025.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: aarch64-linux
Additional system types:
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/gep/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/gep/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/gep/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user
/gep/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/f109fmh4i01j5h5l5b5qd2lmas1v8y8j-lix-2.91.1/share`
 - nixpkgs: `/nix/store/chnzzrb2jz9998kwxlwy43sm9rayd9l0-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aorith** [comment]
Upstream already supports deno2 on their "edge" version so it's a matter of time until they release the next version :)

**Comment by gepbird** [comment]
Thanks for finding this out!

Works when I pin it to `deno_1`, this might be useful for other people:
```nix
services.silverbullet = {
  package = pkgs.silverbullet.override {
    deno = pkgs.deno_1;
  };
};
```

I assume downgrading it to `deno_1` in nixpkgs doesn't help much because it will be dropped soon. So we could either switch to that less stable edge version or wait for a new release depending on how far is that.

**Comment by victorb** [comment]
This (or something similar) seems to be happening again, after restarting the silverbullet service, it crashes:

```
Feb 27 18:17:25 processor systemd[1]: Starting Silverbullet service...
Feb 27 18:17:25 processor systemd[1]: Started Silverbullet service.
Feb 27 18:17:26 processor silverbullet[53586]: Using KV as a database backend (/storage/docs/main/.silverbullet.db).
Feb 27 18:17:26 processor silverbullet[53586]: Going to start SilverBullet binding to 10.0.0.79:4693
Feb 27 18:17:26 processor silverbullet[53586]: Using local disk as a storage backend: /storage/docs/main
Feb 27 18:17:26 processor silverbullet[53586]: Unhandled rejection: PromiseRejectionEvent {
Feb 27 18:17:26 processor silverbullet[53586]:   bubbles: false,
Feb 27 18:17:26 processor silverbullet[53586]:   cancelable: true,
Feb 27 18:17:26 processor silverbullet[53586]:   composed: false,
Feb 27 18:17:26 processor silverbullet[53586]:   currentTarget: Window {},
Feb 27 18:17:26 processor silverbullet[53586]:   defaultPrevented: false,
Feb 27 18:17:26 processor silverbullet[53586]:   eventPhase: 2,
Feb 27 18:17:26 processor silverbullet[53586]:   srcElement: null,
Feb 27 18:17:26 processor silverbullet[53586]:   target: Window {},
Feb 27 18:17:26 processor silverbullet[53586]:   returnValue: true,
Feb 27 18:17:26 processor silverbullet[53586]:   timeStamp: 0,
Feb 27 18:17:26 processor silverbullet[53586]:   type: "unhandledrejection",
Feb 27 18:17:26 processor silverbullet[53586]:   promise: Promise {
Feb 27 18:17:26 processor silverbullet[53586]:     <rejected> ReferenceError: window is not defined
Feb 27 18:17:26 processor silverbullet[53586]:     at IV.hashSHA256 (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:87:33860)
Feb 27 18:17:26 processor silverbullet[53586]:     at IV.init (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:87:33272)
Feb 27 18:17:26 processor silverbullet[53586]:     at eventLoopTick (ext:core/01_core.js:175:7)
Feb 27 18:17:26 processor silverbullet[53586]:     at async zX.init (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:2384:18073)
Feb 27 18:17:26 processor silverbullet[53586]:     at async rX.start (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:2385:7437)
Feb 27 18:17:26 processor silverbullet[53586]:     at async F.gj [as actionHandler] (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:2385:13469244)
Feb 27 18:17:26 processor silverbullet[53586]:     at async F.execute (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:24:8601)
Feb 27 18:17:26 processor silverbullet[53586]:     at async F.parseCommand (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:24:6314)
Feb 27 18:17:26 processor silverbullet[53586]:     at async file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:2418:6541
Feb 27 18:17:26 processor silverbullet[53586]:   },
Feb 27 18:17:26 processor silverbullet[53586]:   reason: ReferenceError: window is not defined
Feb 27 18:17:26 processor silverbullet[53586]:     at IV.hashSHA256 (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:87:33860)
Feb 27 18:17:26 processor silverbullet[53586]:     at IV.init (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:87:33272)
Feb 27 18:17:26 processor silverbullet[53586]:     at eventLoopTick (ext:core/01_core.js:175:7)
Feb 27 18:17:26 processor silverbullet[53586]:     at async zX.init (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:2384:18073)
Feb 27 18:17:26 processor silverbullet[53586]:     at async rX.start (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:2385:7437)
Feb 27 18:17:26 processor silverbullet[53586]:     at async F.gj [as actionHandler] (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:2385:13469244)
Feb 27 18:17:26 processor silverbullet[53586]:     at async F.execute (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:24:8601)
Feb 27 18:17:26 processor silverbullet[53586]:     at async F.parseCommand (file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:24:6314)
Feb 27 18:17:26 processor silverbullet[53586]:     at async file:///nix/store/i26s6ip3qjzb80bdwnijzjnz0mmkhzqy-silverbullet-0.9.4/lib/silverbullet.js:2418:6541
Feb 27 18:17:26 processor silverbullet[53586]: }
``` 

Seemingly, `deno_1` has been dropped in `nixos-24.11` as the fix highlighted by @gepbird no longer can be applied.

```
building Nix...
building the system configuration...
error:
       … while calling the 'head' builtin
         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:1:35741:
       … while evaluating the attribute 'value'
         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:1:33591:
       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `warnings':

       … while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/boot/systemd.nix':

       … while evaluating the option `systemd.services.silverbullet.serviceConfig':

       … while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/web-apps/silverbullet.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'deno_1' missing
       at /etc/nixos/modules/silverbullet.nix:17:14:
           16|     package = pkgs.silverbullet.override {
           17|       deno = pkgs.deno_1;
             |              ^
           18|     };
       Did you mean one of deno or dune_1?
make: *** [Makefile:75: server-rebuild-nixos] Error 1

```

AFAIK, Deno2 migration happened at version `0.10.1` of Silverbullet (latest was `0.10.4`), nixos `24.11` is currently packaging `0.9.4` it seems. https://github.com/NixOS/nixpkgs/blob/5d7db4668d7a0c6cc5fc8cf6ef33b008b2b1ed8b/pkgs/by-name/si/silverbullet/package.nix#L9-L15

**Comment by gepbird** [comment]
Discussion in https://github.com/NixOS/nixpkgs/pull/356163 could be useful, any updates about trying to upgrade to a newer silverbulltet @aorith ?

**Comment by aorith** [comment]
I've been a bit disconnected but AFAIK nixpkgs doesn't have a deno2 builder yet (https://github.com/NixOS/nixpkgs/pull/326003), with a builder and a small change in upstream it could be packaged again properly.

For the moment, I'm overriding the version manually plus some required fixes in the `serviceConfig` : https://github.com/aorith/nixconf/blob/3b1d3d174499b3b5422fc3a10cc09b11fb79ae2d/hosts/arcadia/silverbullet.nix

**Comment by victorb** [comment]
@aorith muchas thank you's for that, that did the trick to make it work with `SB_USER` again! 👍
