### ISSUE TITLE
Build failure: cdktf-cli

### ISSUE THREAD

**Issue by webframp** [NixOS/nixpkgs#354841]
### Steps To Reproduce

1. build cdktf-cli

### Build log
Short version:
<details>
<summary>Short build error</summary>

```
error: builder for '/nix/store/0aabvkhsiahx78aaxw3sqxjhqg73hxyw-cdktf-cli-0.20.8.drv' failed with exit code 1;
       last 25 log lines:
       > npm error ../../../nan/nan_persistent_12_inl.h:12:40: note: 'class Nan::Persistent<v8::Function>' declared here
       > npm error    12 | template<typename T, typename M> class Persistent :
       > npm error       |                                        ^~~~~~~~~~
       > npm error ../src/unix/pty.cc: At global scope:
       > npm error /nix/store/737ndilqdjq5ki46ifs1b59iw541wz72-node-sources/src/node.h:1232:7: warning: cast between incompatible function types from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       > npm error  1232 |       (node::addon_register_func) (regfunc),
  \
       > npm error       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > npm error /nix/store/737ndilqdjq5ki46ifs1b59iw541wz72-node-sources/src/node.h:1266:3: note: in expansion of macro 'NODE_MODULE_X'
       > npm error  1266 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
       > npm error       |   ^~~~~~~~~~~~~
       > npm error ../src/unix/pty.cc:734:1: note: in expansion of macro 'NODE_MODULE'
       > npm error   734 | NODE_MODULE(pty, init)
       > npm error       | ^~~~~~~~~~~
       > npm error make: *** [pty.target.mk:106: Release/obj.target/pty/src/unix/pty.o] Error 1
       > npm error gyp ERR! build error
       > npm error gyp ERR! stack Error: `make` failed with exit code: 2
       > npm error gyp ERR! stack at ChildProcess.<anonymous> (/nix/store/bc1blqcb391vjj251had3dbrnq5rb7md-nodejs-23.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:216:23)
       > npm error gyp ERR! System Linux 5.15.153.1-microsoft-standard-WSL2
       > npm error gyp ERR! command "/nix/store/bc1blqcb391vjj251had3dbrnq5rb7md-nodejs-23.1.0/bin/node" "/nix/store/bc1blqcb391vjj251had3dbrnq5rb7md-nodejs-23.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       > npm error gyp ERR! cwd /nix/store/371yc8jzhafs2w3gqfhjsx00srcggr2i-cdktf-cli-0.20.8/lib/node_modules/cdktf-cli/node_modules/@cdktf/node-pty-prebuilt-multiarch
       > npm error gyp ERR! node -v v23.1.0
       > npm error gyp ERR! node-gyp -v v10.2.0
       > npm error gyp ERR! not ok
       > |npm error A complete log of this run can be found in: /build/.npm/_logs/2024-11-09T19_36_26_140Z-debug-0.log
       > |
       For full logs, run 'nix log /nix/store/0aabvkhsiahx78aaxw3sqxjhqg73hxyw-cdktf-cli-0.20.8.drv'.
```

</details>

Full log: https://gist.github.com/webframp/c3f9a8c1bc2c1764cedf256c746cdd08

### Additional context
Broken on latest, unclear how to debug

### Notify maintainers
No maintainers

### Metadata

```
these 5 paths will be fetched (0.68 MiB download, 9.98 MiB unpacked):
  /nix/store/a6nsbir3y5ni3wwkw933aqvcmyyywnnz-file-5.45
  /nix/store/ga0gqnv6qyzvg08jqw0pc2fkyzlv1qrv-gnu-config-2024-01-01
  /nix/store/21y3gqgm2a3w94m0wcrz1xxshks80z7p-gnumake-4.4.1
  /nix/store/ncv68hjnidcd2bm5abkhklrijhn0cgn6-stdenv-linux
  /nix/store/n9iajmgf6z1rvwrdxy3fp8q9xa16j7x7-update-autotools-gnu-config-scripts-hook
copying path '/nix/store/a6nsbir3y5ni3wwkw933aqvcmyyywnnz-file-5.45' from 'https://cache.nixos.org'...
copying path '/nix/store/ga0gqnv6qyzvg08jqw0pc2fkyzlv1qrv-gnu-config-2024-01-01' from 'https://cache.nixos.org'...
copying path '/nix/store/21y3gqgm2a3w94m0wcrz1xxshks80z7p-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/n9iajmgf6z1rvwrdxy3fp8q9xa16j7x7-update-autotools-gnu-config-scripts-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/ncv68hjnidcd2bm5abkhklrijhn0cgn6-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.153.1-microsoft-standard-WSL2, NixOS, 24.11 (Vicuna), 24.11.20241014.a3c0b3b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/xnjw9gmfmpppdj6bxpw6cfkspc3h6xwl-source`
 ```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by webframp** [comment]
A new release is available: https://github.com/hashicorp/terraform-cdk/releases

**Comment by FKouhai** [comment]
seems to be failing from any version newer than v0.19.1 for aarch64-darwin for both nodePackages and nodePackages_latest
```
npm warn config production Use `--omit=dev` instead.
\|/-\|/-\|/-\npm error code 1
\npm error path /nix/store/02rs2yas0hcw7axh0p5l1q38y5n5f96c-cdktf-cli-0.20.11/lib/node_modules/cdktf-cli/node_modules/@cdktf/node-pty-prebuilt-multiarch
\npm error command failed
\npm error command sh -c node scripts/check-prebuild.js || prebuild-install || node scripts/install.js
\npm error make: Entering directory '/nix/store/02rs2yas0hcw7axh0p5l1q38y5n5f96c-cdktf-cli-0.20.11/lib/node_modules/cdktf-cli/node_modules/@cdktf/node-pty-prebuilt-multiarch/build'
npm error   CXX(target) Release/obj.target/pty/src/unix/pty.o
npm error make: Leaving directory '/nix/store/02rs2yas0hcw7axh0p5l1q38y5n5f96c-cdktf-cli-0.20.11/lib/node_modules/cdktf-cli/node_modules/@cdktf/node-pty-prebuilt-multiarch/build'
\npm error Prebuild binary missing for platform darwin
npm error prebuild-install warn install unable to get local issuer certificate
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@11.0.0
npm error gyp info using node@23.10.0 | darwin | arm64
npm error gyp info find Python using Python version 3.12.9 found at "/nix/store/ibnllhp7pc88kgcrxa2gddxcbyl0vngk-python3-3.12.9/bin/python3"
npm error gyp WARN read config.gypi ENOENT: no such file or directory, open '/nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/include/node/config.gypi'
npm error gyp info spawn /nix/store/ibnllhp7pc88kgcrxa2gddxcbyl0vngk-python3-3.12.9/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/nix/store/yph39j7h2a593qmfrnqd4ajpapr4z01z-nodejs-23.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/nix/store/02rs2yas0hcw7axh0p5l1q38y5n5f96c-cdktf-cli-0.20.11/lib/node_modules/cdktf-cli/node_modules/@cdktf/node-pty-prebuilt-multiarch/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/nix/store/yph39j7h2a593qmfrnqd4ajpapr4z01z-nodejs-23.10.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources',
npm error gyp info spawn args '-Dnode_gyp_dir=/nix/store/yph39j7h2a593qmfrnqd4ajpapr4z01z-nodejs-23.10.0/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/$(Configuration)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/nix/store/02rs2yas0hcw7axh0p5l1q38y5n5f96c-cdktf-cli-0.20.11/lib/node_modules/cdktf-cli/node_modules/@cdktf/node-pty-prebuilt-multiarch',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn make
npm error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm error ../src/unix/pty.cc:669:10: error: use of undeclared identifier 'openpty'
npm error   669 |   return openpty(amaster, aslave, name, (termios *)termp, (winsize *)winp);
npm error       |          ^
npm error ../src/unix/pty.cc:717:10: error: use of undeclared identifier 'forkpty'
npm error   717 |   return forkpty(amaster, name, (termios *)termp, (winsize *)winp);
npm error       |          ^
npm error ../src/unix/pty.cc:734:1: warning: cast from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' (aka 'void (*)(Local<v8::Object>)') to 'node::addon_register_func' (aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void *)') converts to incompatible function type [-Wcast-function-type-mismatch]
npm error   734 | NODE_MODULE(pty, init)
npm error       | ^~~~~~~~~~~~~~~~~~~~~~
npm error /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/src/node.h:1261:3: note: expanded from macro 'NODE_MODULE'
npm error  1261 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm error       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/src/node.h:1227:7: note: expanded from macro 'NODE_MODULE_X'
npm error  1227 |       (node::addon_register_func) (regfunc),                          \
npm error       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error In file included from ../src/unix/pty.cc:20:
npm error In file included from ../../../nan/nan.h:62:
npm error In file included from /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/src/node.h:73:
npm error In file included from /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/deps/v8/include/v8.h:24:
npm error In file included from /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/deps/v8/include/v8-array-buffer.h:13:
npm error In file included from /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/deps/v8/include/v8-object.h:11:
npm error /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/deps/v8/include/v8-persistent-handle.h:493:26: warning: cast from 'typename WeakCallbackInfo<ObjectWrap>::Callback' (aka 'void (*)(const WeakCallbackInfo<ObjectWrap> &)') to 'Callback' (aka 'void (*)(const WeakCallbackInfo<void> &)') converts to incompatible function type [-Wcast-function-type-mismatch]
npm error   493 |                          reinterpret_cast<Callback>(callback), type);
npm error       |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/src/node_object_wrap.h:85:18: note: in instantiation of function template specialization 'v8::PersistentBase<v8::Object>::SetWeak<node::ObjectWrap>' requested here
npm error    85 |     persistent().SetWeak(this, WeakCallback, v8::WeakCallbackType::kParameter);
npm error       |                  ^
npm error In file included from ../src/unix/pty.cc:20:
npm error In file included from ../../../nan/nan.h:62:
npm error In file included from /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/src/node.h:73:
npm error In file included from /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/deps/v8/include/v8.h:24:
npm error In file included from /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/deps/v8/include/v8-array-buffer.h:13:
npm error In file included from /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/deps/v8/include/v8-object.h:11:
npm error /nix/store/3280sikvpfss6cjfxxbm6g9cxq3xrvjj-node-sources/deps/v8/include/v8-persistent-handle.h:493:26: warning: cast from 'typename WeakCallbackInfo<ObjectWrap>::Callback' (aka 'void (*)(const WeakCallbackInfo<ObjectWrap> &)') to 'Callback' (aka 'void (*)(const WeakCallbackInfo<void> &)') converts to incompatible function type [-Wcast-function-type-mismatch]
npm error   493 |                          reinterpret_cast<Callback>(callback), type);
npm error       |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error ../../../nan/nan_object_wrap.h:64:50: note: in instantiation of function template specialization 'v8::PersistentBase<v8::Object>::SetWeak<Nan::ObjectWrap>' requested here
npm error    64 |     persistent().v8::PersistentBase<v8::Object>::SetWeak(
npm error       |                                                  ^
npm error 3 warnings and 2 errors generated.
npm error make: *** [pty.target.mk:124: Release/obj.target/pty/src/unix/pty.o] Error 1
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `make` failed with exit code: 2
npm error gyp ERR! stack at ChildProcess.<anonymous> (/nix/store/yph39j7h2a593qmfrnqd4ajpapr4z01z-nodejs-23.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:216:23)
npm error gyp ERR! System Darwin 24.3.0
npm error gyp ERR! command "/nix/store/yph39j7h2a593qmfrnqd4ajpapr4z01z-nodejs-23.10.0/bin/node" "/nix/store/yph39j7h2a593qmfrnqd4ajpapr4z01z-nodejs-23.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm error gyp ERR! cwd /nix/store/02rs2yas0hcw7axh0p5l1q38y5n5f96c-cdktf-cli-0.20.11/lib/node_modules/cdktf-cli/node_modules/@cdktf/node-pty-prebuilt-multiarch
npm error gyp ERR! node -v v23.10.0
npm error gyp ERR! node-gyp -v v11.0.0
npm error gyp ERR! not ok
\npm error A complete log of this run can be found in: /private/tmp/nix-build-cdktf-cli-0.20.11.drv-0/.npm/_logs/2025-03-19T21_16_32_562Z-debug-0.log
```

**Comment by FKouhai** [comment]
added the darwin topic since it seems like the package builds on v0.20.11 in amd64 at least using nixOS
