### ISSUE TITLE
nodejs: corepack internal error

### ISSUE THREAD

**Issue by sikmir** [NixOS/nixpkgs#355480]
### Steps To Reproduce
```sh
$ corepack enable
Internal Error: EACCES: permission denied, symlink '../../m1ymz3alwqc71yrmzl8sas2m8ksqhhsh-nodejs-20.18.0/lib/node_modules/corepack/dist/pnpm.js' -> '/nix/store/c97fnlj74scj8jxz5mzrw0hifbl3vcz7-user-environment/bin/pnpm'
    at async Object.symlink (node:internal/fs/promises:1000:10)
    at async EnableCommand.generatePosixLink (/nix/store/m1ymz3alwqc71yrmzl8sas2m8ksqhhsh-nodejs-20.18.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22608:5)
    at async Promise.all (index 0)
    at async EnableCommand.execute (/nix/store/m1ymz3alwqc71yrmzl8sas2m8ksqhhsh-nodejs-20.18.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22595:5)
    at async EnableCommand.validateAndExecute (/nix/store/m1ymz3alwqc71yrmzl8sas2m8ksqhhsh-nodejs-20.18.0/lib/node_modules/corepack/dist/lib/corepack.cjs:19835:22)
    at async _Cli.run (/nix/store/m1ymz3alwqc71yrmzl8sas2m8ksqhhsh-nodejs-20.18.0/lib/node_modules/corepack/dist/lib/corepack.cjs:20772:18)
    at async Object.runMain (/nix/store/m1ymz3alwqc71yrmzl8sas2m8ksqhhsh-nodejs-20.18.0/lib/node_modules/corepack/dist/lib/corepack.cjs:23091:19)
```

### Notify maintainers
@aduh95

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sikmir** [comment]
There is `--install-directory` argument, so closing.
