### ISSUE TITLE
Rubocop does not run on nixos-24.05

### ISSUE THREAD

**Issue by seabass-labrax** [NixOS/nixpkgs#355927]
1. Install a fresh copy of Nix with flake support (I used the Determinate Nix Installer)
2. `nix run github:NixOS/nixpkgs/nixos-24.05#pkgs.rubocop`

Stacktrace:

```
/nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/resolver.rb:228:in `search_for': Unable to resolve dependency: 'rexml (>= 3.2.5, < 4.0)' requires 'strscan (>= 3.0.9)' (Gem::UnsatisfiableDependencyError)
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/resolver.rb:282:in `block in sort_dependencies'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/resolver.rb:276:in `each'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/resolver.rb:276:in `sort_by'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/resolver.rb:276:in `with_index'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/resolver.rb:276:in `sort_dependencies'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/vendor/molinillo/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/vendor/molinillo/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/vendor/molinillo/lib/molinillo/resolution.rb:727:in `activate_new_spec'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/vendor/molinillo/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/vendor/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/vendor/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/vendor/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/resolver.rb:186:in `resolve'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/request_set.rb:413:in `resolve'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems/request_set.rb:425:in `resolve_current'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems.rb:224:in `finish_resolve'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems.rb:281:in `block in activate_bin_path'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems.rb:279:in `synchronize'
	from /nix/store/dxdq7mgbrh95w6w43r0xz09p94qgdc78-ruby-3.1.6/lib/ruby/3.1.0/rubygems.rb:279:in `activate_bin_path'
	from /nix/store/p8f06851k6gnjkvk94pd7nplk2jbz17z-ruby3.1-rubocop-1.62.1/bin/rubocop:18:in `<main>
```

This happens both on my host system (Debian 12 Bookworm, amd64) as well as on containers running on the system. I can't tell where `strscan` is required; RubyGems doesn't list it as a dependency of Rubocop. This error did not occur with nixos-23.05.

**Comment by seabass-labrax** [comment]
Good news; already fixed in 5ba6bb7ad9710e6aeb9a2b23d45d24ed5055d59a. Tested working with `nix run github:NixOS/nixpkgs/nixos-unstable#pkgs.rubocop`.
