### ISSUE TITLE
krb5: binary krb5-config is missing from final package

### ISSUE THREAD

**Issue by Mag1cByt3s** [NixOS/nixpkgs#355915]
## Describe the bug

The binary `krb5-config` does not get included in the final bin folder of the package:
```nix
# not via outputBin, due to reference from libkrb5.so
  postInstall = ''
    moveToOutput bin/krb5-config "$dev"
  '';
```

Thus `krb5-config` is not available on causes other external programs to fails which rely on `krb5-config` to be present on the system.

I am not quite sure why the krb5-config binary got excluded in the first place.

Is there any way to fix that and get `krb5-config` working?

## Steps To Reproduce

1. install `krb5` package
2. try to run `krb5-config`
3. binary is not available

Here is an example where it fails because the binary is missing:
```bash
❯ pip install -r requirements.txt
Processing /home/pascal/Git/autobloody
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bloodyad==1.0.5 (from autobloody==0.2.2->-r requirements.txt (line 1))
  Downloading bloodyad-1.0.5-py3-none-any.whl.metadata (7.8 kB)
Collecting neo4j>=4.4.6 (from autobloody==0.2.2->-r requirements.txt (line 1))
  Using cached neo4j-5.26.0-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: cryptography>=37.0.2 in ./.venv/lib/python3.12/site-packages (from bloodyad==1.0.5->autobloody==0.2.2->-r requirements.txt (line 1)) (43.0.3)
Collecting gssapi>=1.8.1 (from bloodyad==1.0.5->autobloody==0.2.2->-r requirements.txt (line 1))
  Downloading gssapi-1.9.0.tar.gz (94 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      /nix/store/mm0pa3z7kk6jh1i9rkxqxjqmd8h1qpxf-bash-5.2p37/bin/sh: line 1: krb5-config: command not found
      Traceback (most recent call last):
        File "/home/pascal/Git/autobloody/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/pascal/Git/autobloody/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/pascal/Git/autobloody/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xv576s6m/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xv576s6m/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-xv576s6m/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 109, in <module>
        File "<string>", line 22, in get_output
        File "/run/current-system/sw/lib/python3.12/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/run/current-system/sw/lib/python3.12/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
error: subprocess-exited-with-error
```

## Expected behavior

The package krb5 should package the binary `krb5-config`.

## Metadata

```bash
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, Red Flake, rolling, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source`
```

## Notify maintainers

Package krb5 has no maintainer.
The person who last touched it was @tobim 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Mag1cByt3s** [comment]
I just tried to also install `krb5.dev` and it worked. `krb5-config` is now available. Thanks!

```bash
❯ krb5-config
Usage: /run/current-system/sw/bin/krb5-config [OPTIONS] [LIBRARIES]
Options:
        [--help]          Help
        [--all]           Display version, vendor, and various values
        [--version]       Version information
        [--vendor]        Vendor information
        [--prefix]        Kerberos installed prefix
        [--exec-prefix]   Kerberos installed exec_prefix
        [--defccname]     Show built-in default ccache name
        [--defktname]     Show built-in default keytab name
        [--defcktname]    Show built-in default client keytab name
        [--cflags]        Compile time CFLAGS
        [--libs]          List libraries required to link [LIBRARIES]
Libraries:
        krb5              Kerberos 5 application
        gssapi            GSSAPI application with Kerberos 5 bindings
        gssrpc            GSSAPI RPC application
        kadm-client       Kadmin client
        kadm-server       Kadmin server
        kdb               Application that accesses the kerberos database
```
