### ISSUE TITLE
[staging] Build failure: paperless-ngx

### ISSUE THREAD

**Issue by FliegendeWurst** [NixOS/nixpkgs#357315]
## Steps To Reproduce

1. build `paperless-ngx` on staging

## Build log

<details>

<summary>Build Log</summary>

```
...
[1mnpm[22m [31merror[39m [94mcode[39m [33m1[39m
[1mnpm[22m [31merror[39m [94mpath[39m /build/source/src-ui/node_modules/canvas
[1mnpm[22m [31merror[39m command failed
[1mnpm[22m [31merror[39m [94mcommand[39m sh -c node-pre-gyp install --fallback-to-build --update-binary
[1mnpm[22m [31merror[39m make: Entering directory '/build/source/src-ui/node_modules/canvas/build'
[1mnpm[22m [31merror[39m   SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
[1mnpm[22m [31merror[39m   COPY Release/canvas-postbuild.node
[1mnpm[22m [31merror[39m   CXX(target) Release/obj.target/canvas/src/backend/Backend.o
[1mnpm[22m [31merror[39m make: Leaving directory '/build/source/src-ui/node_modules/canvas/build'
[1mnpm[22m [31merror[39m Failed to execute '/nix/store/g8my913fwp7nsx7n10z6kd37gzsbmx40-nodejs-22.11.0/bin/node /nix/store/g8my913fwp7nsx7n10z6kd37gzsbmx40-nodejs-22.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/build/source/src-ui/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/build/source/src-ui/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
[1mnpm[22m [31merror[39m node-pre-gyp info it worked if it ends with ok
[1mnpm[22m [31merror[39m node-pre-gyp info using node-pre-gyp@1.0.11
[1mnpm[22m [31merror[39m node-pre-gyp info using node@22.11.0 | linux | x64
[1mnpm[22m [31merror[39m (node:708) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
[1mnpm[22m [31merror[39m (Use `node --trace-deprecation ...` to show where the warning was created)
[1mnpm[22m [31merror[39m node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz
[1mnpm[22m [31merror[39m node-pre-gyp ERR! install request to https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz failed, reason: getaddrinfo EAI_AGAIN github.com 
[1mnpm[22m [31merror[39m node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@22.11.0 (node-v127 ABI, glibc) (falling back to source compile with node-gyp) 
[1mnpm[22m [31merror[39m node-pre-gyp WARN Hit error request to https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz failed, reason: getaddrinfo EAI_AGAIN github.com 
[1mnpm[22m [31merror[39m gyp info it worked if it ends with ok
[1mnpm[22m [31merror[39m gyp info using node-gyp@10.2.0
[1mnpm[22m [31merror[39m gyp info using node@22.11.0 | linux | x64
[1mnpm[22m [31merror[39m gyp info ok 
[1mnpm[22m [31merror[39m gyp info it worked if it ends with ok
[1mnpm[22m [31merror[39m gyp info using node-gyp@10.2.0
[1mnpm[22m [31merror[39m gyp info using node@22.11.0 | linux | x64
[1mnpm[22m [31merror[39m gyp info find Python using Python version 3.12.7 found at "/nix/store/qlmjxxsgpmhksccd89f29saww0garvf6-python3-3.12.7/bin/python3"
[1mnpm[22m [31merror[39m gyp WARN read config.gypi ENOENT: no such file or directory, open '/nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/include/node/config.gypi'
[1mnpm[22m [31merror[39m gyp info spawn /nix/store/qlmjxxsgpmhksccd89f29saww0garvf6-python3-3.12.7/bin/python3
[1mnpm[22m [31merror[39m gyp info spawn args [
[1mnpm[22m [31merror[39m gyp info spawn args '/nix/store/g8my913fwp7nsx7n10z6kd37gzsbmx40-nodejs-22.11.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
[1mnpm[22m [31merror[39m gyp info spawn args 'binding.gyp',
[1mnpm[22m [31merror[39m gyp info spawn args '-f',
[1mnpm[22m [31merror[39m gyp info spawn args 'make',
[1mnpm[22m [31merror[39m gyp info spawn args '-I',
[1mnpm[22m [31merror[39m gyp info spawn args '/build/source/src-ui/node_modules/canvas/build/config.gypi',
[1mnpm[22m [31merror[39m gyp info spawn args '-I',
[1mnpm[22m [31merror[39m gyp info spawn args '/nix/store/g8my913fwp7nsx7n10z6kd37gzsbmx40-nodejs-22.11.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
[1mnpm[22m [31merror[39m gyp info spawn args '-I',
[1mnpm[22m [31merror[39m gyp info spawn args '/nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/common.gypi',
[1mnpm[22m [31merror[39m gyp info spawn args '-Dlibrary=shared_library',
[1mnpm[22m [31merror[39m gyp info spawn args '-Dvisibility=default',
[1mnpm[22m [31merror[39m gyp info spawn args '-Dnode_root_dir=/nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source',
[1mnpm[22m [31merror[39m gyp info spawn args '-Dnode_gyp_dir=/nix/store/g8my913fwp7nsx7n10z6kd37gzsbmx40-nodejs-22.11.0/lib/node_modules/npm/node_modules/node-gyp',
[1mnpm[22m [31merror[39m gyp info spawn args '-Dnode_lib_file=/nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/$(Configuration)/node.lib',
[1mnpm[22m [31merror[39m gyp info spawn args '-Dmodule_root_dir=/build/source/src-ui/node_modules/canvas',
[1mnpm[22m [31merror[39m gyp info spawn args '-Dnode_engine=v8',
[1mnpm[22m [31merror[39m gyp info spawn args '--depth=.',
[1mnpm[22m [31merror[39m gyp info spawn args '--no-parallel',
[1mnpm[22m [31merror[39m gyp info spawn args '--generator-output',
[1mnpm[22m [31merror[39m gyp info spawn args 'build',
[1mnpm[22m [31merror[39m gyp info spawn args '-Goutput_dir=.'
[1mnpm[22m [31merror[39m gyp info spawn args ]
[1mnpm[22m [31merror[39m gyp info ok 
[1mnpm[22m [31merror[39m gyp info it worked if it ends with ok
[1mnpm[22m [31merror[39m gyp info using node-gyp@10.2.0
[1mnpm[22m [31merror[39m gyp info using node@22.11.0 | linux | x64
[1mnpm[22m [31merror[39m gyp info spawn make
[1mnpm[22m [31merror[39m gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
[1mnpm[22m [31merror[39m In file included from ../src/backend/Backend.h:6,
[1mnpm[22m [31merror[39m                  from ../src/backend/Backend.cc:1:
[1mnpm[22m [31merror[39m ../../nan/nan.h: In function 'void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, GetterCallback, SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, imp::Sig)':
[1mnpm[22m [31merror[39m ../../nan/nan.h:2548:19: error: no matching function for call to 'v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>&, void (*&)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&), void (*&)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::Object>&, v8::AccessControl&, v8::PropertyAttribute&)'
[1mnpm[22m [31merror[39m  2548 |   tpl->SetAccessor(
[1mnpm[22m [31merror[39m       |   ~~~~~~~~~~~~~~~~^
[1mnpm[22m [31merror[39m  2549 |       name
[1mnpm[22m [31merror[39m       |       ~~~~         
[1mnpm[22m [31merror[39m  2550 |     , getter_
[1mnpm[22m [31merror[39m       |     ~~~~~~~~~      
[1mnpm[22m [31merror[39m  2551 |     , setter_
[1mnpm[22m [31merror[39m       |     ~~~~~~~~~      
[1mnpm[22m [31merror[39m  2552 |     , obj
[1mnpm[22m [31merror[39m       |     ~~~~~          
[1mnpm[22m [31merror[39m  2553 |     , settings
[1mnpm[22m [31merror[39m       |     ~~~~~~~~~~     
[1mnpm[22m [31merror[39m  2554 |     , attribute
[1mnpm[22m [31merror[39m       |     ~~~~~~~~~~~    
[1mnpm[22m [31merror[39m  2555 | #if (NODE_MODULE_VERSION < NODE_16_0_MODULE_VERSION)
[1mnpm[22m [31merror[39m       | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1mnpm[22m [31merror[39m  2556 |     , signature
[1mnpm[22m [31merror[39m       |     ~~~~~~~~~~~    
[1mnpm[22m [31merror[39m  2557 | #endif
[1mnpm[22m [31merror[39m       | ~~~~~~             
[1mnpm[22m [31merror[39m  2558 |   );
[1mnpm[22m [31merror[39m       |   ~                
[1mnpm[22m [31merror[39m In file included from /nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/deps/v8/include/v8-function.h:15,
[1mnpm[22m [31merror[39m                  from /nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/deps/v8/include/v8.h:33,
[1mnpm[22m [31merror[39m                  from /nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/src/node.h:73,
[1mnpm[22m [31merror[39m                  from ../../nan/nan.h:62:
[1mnpm[22m [31merror[39m /nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/deps/v8/include/v8-template.h:1049:8: note: candidate: 'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)'
[1mnpm[22m [31merror[39m  1049 |   void SetAccessor(
[1mnpm[22m [31merror[39m       |        ^~~~~~~~~~~
[1mnpm[22m [31merror[39m /nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/deps/v8/include/v8-template.h:1052:61: note:   no known conversion for argument 5 from 'v8::AccessControl' to 'v8::PropertyAttribute'
[1mnpm[22m [31merror[39m  1052 |       Local<Value> data = Local<Value>(), PropertyAttribute attribute = None,
[1mnpm[22m [31merror[39m       |                                           ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
[1mnpm[22m [31merror[39m /nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/deps/v8/include/v8-template.h:1055:8: note: candidate: 'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)'
[1mnpm[22m [31merror[39m  1055 |   void SetAccessor(
[1mnpm[22m [31merror[39m       |        ^~~~~~~~~~~
[1mnpm[22m [31merror[39m /nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/deps/v8/include/v8-template.h:1058:61: note:   no known conversion for argument 5 from 'v8::AccessControl' to 'v8::PropertyAttribute'
[1mnpm[22m [31merror[39m  1058 |       Local<Value> data = Local<Value>(), PropertyAttribute attribute = None,
[1mnpm[22m [31merror[39m       |                                           ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
[1mnpm[22m [31merror[39m ../../nan/nan.h: In function 'void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, GetterCallback, SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)':
[1mnpm[22m [31merror[39m ../../nan/nan.h:2594:19: error: no matching function for call to 'v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>&, void (*&)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&), void (*&)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::Object>&, v8::AccessControl&, v8::PropertyAttribute&)'
[1mnpm[22m [31merror[39m  2594 |   tpl->SetAccessor(
[1mnpm[22m [31merror[39m       |   ~~~~~~~~~~~~~~~~^
[1mnpm[22m [31merror[39m  2595 |       name
[1mnpm[22m [31merror[39m       |       ~~~~         
[1mnpm[22m [31merror[39m  2596 |     , getter_
[1mnpm[22m [31merror[39m       |     ~~~~~~~~~      
[1mnpm[22m [31merror[39m  2597 |     , setter_
[1mnpm[22m [31merror[39m       |     ~~~~~~~~~      
[1mnpm[22m [31merror[39m  2598 |     , obj
[1mnpm[22m [31merror[39m       |     ~~~~~          
[1mnpm[22m [31merror[39m  2599 |     , settings
[1mnpm[22m [31merror[39m       |     ~~~~~~~~~~     
[1mnpm[22m [31merror[39m  2600 |     , attribute
[1mnpm[22m [31merror[39m       |     ~~~~~~~~~~~    
[1mnpm[22m [31merror[39m  2601 |   );
[1mnpm[22m [31merror[39m       |   ~                
[1mnpm[22m [31merror[39m /nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/deps/v8/include/v8-template.h:1049:8: note: candidate: 'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)'
[1mnpm[22m [31merror[39m  1049 |   void SetAccessor(
[1mnpm[22m [31merror[39m       |        ^~~~~~~~~~~
[1mnpm[22m [31merror[39m /nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/deps/v8/include/v8-template.h:1052:61: note:   no known conversion for argument 5 from 'v8::AccessControl' to 'v8::PropertyAttribute'
[1mnpm[22m [31merror[39m  1052 |       Local<Value> data = Local<Value>(), PropertyAttribute attribute = None,
[1mnpm[22m [31merror[39m       |                                           ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
[1mnpm[22m [31merror[39m /nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/deps/v8/include/v8-template.h:1055:8: note: candidate: 'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)'
[1mnpm[22m [31merror[39m  1055 |   void SetAccessor(
[1mnpm[22m [31merror[39m       |        ^~~~~~~~~~~
[1mnpm[22m [31merror[39m /nix/store/7kvb9viig5dh1glgyz9pi7mhn12cxys9-nodejs-22.11.0-source/deps/v8/include/v8-template.h:1058:61: note:   no known conversion for argument 5 from 'v8::AccessControl' to 'v8::PropertyAttribute'
[1mnpm[22m [31merror[39m  1058 |       Local<Value> data = Local<Value>(), PropertyAttribute attribute = None,
[1mnpm[22m [31merror[39m       |                                           ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
[1mnpm[22m [31merror[39m make: *** [canvas.target.mk:139: Release/obj.target/canvas/src/backend/Backend.o] Error 1
[1mnpm[22m [31merror[39m gyp ERR! build error 
[1mnpm[22m [31merror[39m gyp ERR! stack Error: `make` failed with exit code: 2
[1mnpm[22m [31merror[39m gyp ERR! stack at ChildProcess.<anonymous> (/nix/store/g8my913fwp7nsx7n10z6kd37gzsbmx40-nodejs-22.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:216:23)
[1mnpm[22m [31merror[39m gyp ERR! System Linux 6.6.60
[1mnpm[22m [31merror[39m gyp ERR! command "/nix/store/g8my913fwp7nsx7n10z6kd37gzsbmx40-nodejs-22.11.0/bin/node" "/nix/store/g8my913fwp7nsx7n10z6kd37gzsbmx40-nodejs-22.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--update-binary" "--module=/build/source/src-ui/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/build/source/src-ui/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v127"
[1mnpm[22m [31merror[39m gyp ERR! cwd /build/source/src-ui/node_modules/canvas
[1mnpm[22m [31merror[39m gyp ERR! node -v v22.11.0
[1mnpm[22m [31merror[39m gyp ERR! node-gyp -v v10.2.0
[1mnpm[22m [31merror[39m gyp ERR! not ok 
[1mnpm[22m [31merror[39m node-pre-gyp ERR! build error 
[1mnpm[22m [31merror[39m node-pre-gyp ERR! stack Error: Failed to execute '/nix/store/g8my913fwp7nsx7n10z6kd37gzsbmx40-nodejs-22.11.0/bin/node /nix/store/g8my913fwp7nsx7n10z6kd37gzsbmx40-nodejs-22.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/build/source/src-ui/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/build/source/src-ui/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
[1mnpm[22m [31merror[39m node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/build/source/src-ui/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
[1mnpm[22m [31merror[39m node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
[1mnpm[22m [31merror[39m node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1104:16)
[1mnpm[22m [31merror[39m node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
[1mnpm[22m [31merror[39m node-pre-gyp ERR! System Linux 6.6.60
[1mnpm[22m [31merror[39m node-pre-gyp ERR! command "/nix/store/g8my913fwp7nsx7n10z6kd37gzsbmx40-nodejs-22.11.0/bin/node" "/build/source/src-ui/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
[1mnpm[22m [31merror[39m node-pre-gyp ERR! cwd /build/source/src-ui/node_modules/canvas
[1mnpm[22m [31merror[39m node-pre-gyp ERR! node -v v22.11.0
[1mnpm[22m [31merror[39m node-pre-gyp ERR! node-pre-gyp -v v1.0.11
[1mnpm[22m [31merror[39m node-pre-gyp ERR! not ok
[1mnpm[22m [31merror[39m Log files were not written due to an error writing to the directory: /nix/store/0cww052vxnpz022i7a2irr37h2s725qr-paperless-ngx-frontend-2.13.5-npm-deps/_logs
[1mnpm[22m [31merror[39m You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

</details>

## Additional context

Probably broken by #352123

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.05 (Uakari), 24.05.20241109.fd66cd1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`

## Notify maintainers

@leona-ya @SuperSandro2000 @erikarvstedt

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

It is okay to file bug reports for the staging branch, right? Especially for leaf packages like this.

**Comment by FliegendeWurst** [comment]
I suppose you could try nodejs 22 on master. I will try downgrading to nodejs 20 on staging.

**Comment by leona-ya** [comment]
I'll try 22 on master

**Comment by Kernald** [comment]
This reached the 24.11 branches - https://hydra.nixos.org/build/280100659/nixlog/1

**Comment by FliegendeWurst** [comment]
That's a different failure, I think. The original issue was about incompatible node versions, not test failures.

**Comment by Kernald** [comment]
Ugh sorry, I should have actually read the error...

**Comment by SuperSandro2000** [comment]
This seems to be fixed in the meantime
