### ISSUE TITLE
mkYarnPackage: ENOENT in fixup_bin due to bad node_modules -> deps symlink

### ISSUE THREAD

**Issue by the-sun-will-rise-tomorrow** [NixOS/nixpkgs#357880]
## Describe the bug

It looks like in some cases, `mkYarnPackage` can fail due to creating an incorrect symlink from the `deps` directory to the `node_modules` directory. This later causes `fixup_bin` to fail due to a broken symlink.

## Steps To Reproduce

1. Create a `package.json` with:
   ```json
   {
     "name": "postgraphile-test",
     "dependencies": {
       "postgraphile": "^4.13.0"
     }
   }
   ```
2. Create a `yarn.lock` by running `yarn install` using Yarn v1 (I used v1.22.19)
3. Create a `default.nix` with:
   ```nix
   { pkgs ? import <nixpkgs> {} }:
   pkgs.mkYarnPackage rec {
     version = "1.0";
     src = ./.;
     offlineCache = pkgs.fetchYarnDeps {
       yarnLock = src + "/yarn.lock";
       hash = "sha256-feFxX3d9GVlMIzdkwLHe9ogOi/Uz5nT6p55yby04b74=";
     };
   }
   ```
4. `nix-build`

Full example here: https://gist.github.com/the-sun-will-rise-tomorrow/3838cb6e88c428f22beb15f86b5f9afb

## Expected behavior

Should work, or fail is a less unreasonable way.

## Screenshots

```
this derivation will be built:    
  /nix/store/khzbnq8pmc9vrzsz8gbxixggnzgca8xz-postgraphile-test-1.0.drv
building '/nix/store/khzbnq8pmc9vrzsz8gbxixggnzgca8xz-postgraphile-test-1.0.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/hy38hkaq15c67a8rmqqnqw3v3q08l3n0-enoent-bug
source root is enoent-bug
Running phase: patchPhase
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
Running phase: buildPhase
no Makefile or custom buildPhase, doing nothing
Running phase: installPhase
fixup_bin: Processing  postgraphile-test
node:fs:573
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open '/nix/store/bgcm4sbadawq48nz9mnqmwsrnrwbkh90-postgraphile-test-1.0/libexec/postgraphile-test/node_modules/postgraphile-test/package.json'
    at Object.openSync (node:fs:573:18)
    at Object.readFileSync (node:fs:452:35)
    at processPackage (/nix/store/pby2lh0dg27nk1yzgcfx8529lf6zjj30-fixup_bin.js:19:37)
    at /nix/store/pby2lh0dg27nk1yzgcfx8529lf6zjj30-fixup_bin.js:52:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/nix/store/pby2lh0dg27nk1yzgcfx8529lf6zjj30-fixup_bin.js:51:22)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/nix/store/bgcm4sbadawq48nz9mnqmwsrnrwbkh90-postgraphile-test-1.0/libexec/postgraphile-test/node_modules/postgraphile-test/package.json'
}

Node.js v20.18.0
error: builder for '/nix/store/khzbnq8pmc9vrzsz8gbxixggnzgca8xz-postgraphile-test-1.0.drv' failed with exit code 1;
       last 25 log lines:
       > no Makefile or custom buildPhase, doing nothing
       > Running phase: installPhase
       > fixup_bin: Processing  postgraphile-test
       > node:fs:573
       >   return binding.open(
       >                  ^
       >
       > Error: ENOENT: no such file or directory, open '/nix/store/bgcm4sbadawq48nz9mnqmwsrnrwbkh90-postgraphile-test-1.0/libexec/postgraphile-test/node_modules/postgraphile-test/package.json'
       >     at Object.openSync (node:fs:573:18)
       >     at Object.readFileSync (node:fs:452:35)
       >     at processPackage (/nix/store/pby2lh0dg27nk1yzgcfx8529lf6zjj30-fixup_bin.js:19:37)
       >     at /nix/store/pby2lh0dg27nk1yzgcfx8529lf6zjj30-fixup_bin.js:52:3
       >     at Array.forEach (<anonymous>)
       >     at Object.<anonymous> (/nix/store/pby2lh0dg27nk1yzgcfx8529lf6zjj30-fixup_bin.js:51:22)
       >     at Module._compile (node:internal/modules/cjs/loader:1469:14)
       >     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
       >     at Module.load (node:internal/modules/cjs/loader:1288:32)
       >     at Module._load (node:internal/modules/cjs/loader:1104:12) {
       >   errno: -2,
       >   code: 'ENOENT',
       >   syscall: 'open',
       >   path: '/nix/store/bgcm4sbadawq48nz9mnqmwsrnrwbkh90-postgraphile-test-1.0/libexec/postgraphile-test/node_modules/postgraphile-test/package.json'
       > }
       >
       > Node.js v20.18.0
       For full logs, run 'nix-store -l /nix/store/khzbnq8pmc9vrzsz8gbxixggnzgca8xz-postgraphile-test-1.0.drv'.
```

## Additional context

The bad symlink seems to be created here:

https://github.com/NixOS/nixpkgs/blob/d533f739c47f139829327955f49a4daa48587829/pkgs/development/tools/yarn2nix-moretea/yarn2nix/default.nix#L354

The line creates a symlink going to `node_modules/deps/...`, but it looks like in this case, the `deps` directory is at the same level as `node_modules`, not inside it.

## Notify maintainers

@SuperSandro2000 @WilliButz @gador

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Please try the new yarn tooling and see if it works with that https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#yarn-javascript-yarn

**Comment by the-sun-will-rise-tomorrow** [comment]
Seems to work fine with those, thanks.
