### ISSUE TITLE
Build failure: pythonPackages.dbus-next

### ISSUE THREAD

**Issue by matdibu** [NixOS/nixpkgs#357979]
## Steps To Reproduce

1. build `moonraker-0.8.0-unstable-2023-12-27`

## Build log

<details>

<summary>Build Log</summary>

```
creating build/lib/dbus_next/aio
...skipping...
                return True
    
        bus1.add_message_handler(message_handler)
    
        reply = await bus2.call(msg)
>       assert reply.body == ['got it']
E       AssertionError: assert ['The name :1...ervice files'] == ['got it']
E         
E         At index 0 diff: 'The name :1.44 was not provided by any .service files' != 'got it'
E         
E         Full diff:
E           [
E         -     'got it',
E         +     'The name :1.44 was not provided by any .service files',
E           ]

test/test_fd_passing.py:103: AssertionError
------------------------------ Captured log call -------------------------------
ERROR    asyncio:base_events.py:1820 Future exception was never retrieved
future: <Future finished exception=OSError(9, 'Bad file descriptor')>
Traceback (most recent call last):
  File "/build/source/test/test_disconnect.py", line 56, in test_unexpected_disconnect
    await bus.wait_for_disconnect()
  File "/build/source/dbus_next/aio/message_bus.py", line 342, in wait_for_disconnect
    return await self._disconnect_future
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/dbus_next/aio/message_bus.py", line 63, in write_callback
    self.offset += self.sock.send(self.buf[self.offset:])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor
=============================== warnings summary ===============================
test/test_aio_low_level.py:103
  test/test_aio_low_level.py:103: PytestDeprecationWarning: test_sending_signals_between_buses is asynchronous and >
    @pytest.mark.asyncio

test/test_disconnect.py:9
  test/test_disconnect.py:9: PytestDeprecationWarning: test_bus_disconnect_before_reply is asynchronous and explici>
    @pytest.mark.asyncio

test/test_disconnect.py:34
  test/test_disconnect.py:34: PytestDeprecationWarning: test_unexpected_disconnect is asynchronous and explicitly r>
    @pytest.mark.asyncio

test/test_fd_passing.py:114
  test/test_fd_passing.py:114: PytestDeprecationWarning: test_high_level_service_fd_passing is asynchronous and exp>
    @pytest.mark.asyncio

test/test_fd_passing.py:214
  test/test_fd_passing.py:214: PytestDeprecationWarning: test_sending_file_descriptor_with_proxy is asynchronous an>
    @pytest.mark.asyncio

test/test_tcp_address.py:10
  test/test_tcp_address.py:10: PytestDeprecationWarning: test_tcp_connection_with_forwarding is asynchronous and ex>
    @pytest.mark.asyncio

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED test/test_fd_passing.py::test_sending_file_descriptor_low_level - AssertionError: assert ['The name :1...erv>
====== 1 failed, 72 passed, 7 skipped, 2 deselected, 6 warnings in 6.69s =======
```

</details>

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.11 (Vicuna), 24.11.20241111.dc460ec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/4r8s42c9mwfvgdlxv0izb1cmlzrsb5nz-source`
```

## Notify maintainers
@SFrijters 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by matdibu** [comment]
looks to be related https://github.com/altdesktop/python-dbus-next/issues/161

**Comment by SFrijters** [comment]
Also related: https://github.com/NixOS/nixpkgs/pull/355880 .
With all the flakiness maybe it's better to try to get consumers to migrate to dbus-fast, which is maintained.

**Comment by matdibu** [comment]
interestingly enough, it stopped failing on the last ~5 builds
I guess it really is just flaky

**Comment by SFrijters** [comment]
Should be "fixed" by https://github.com/NixOS/nixpkgs/pull/360361 .

**Comment by matdibu** [comment]
thank you!
