### ISSUE TITLE
Build failure: bencodetools on nixos-24.11

### ISSUE THREAD

**Issue by braack** [NixOS/nixpkgs#358572]
## Steps To Reproduce

ianb@brione ~ % nix-shell --builders "" -p bencodetools                                                                                                                                                                     :(
this derivation will be built:
  /nix/store/fx8f8c1sdy94kiddcigblf8z4nmx3bc0-bencodetools-unstable-2022-05-11.drv
building '/nix/store/fx8f8c1sdy94kiddcigblf8z4nmx3bc0-bencodetools-unstable-2022-05-11.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/kh1s43j34z6lsz1vb2556ppvysk209n7-source
source root is source
Running phase: patchPhase
patching script interpreter paths in configure
configure: interpreter directive changed from "#!/bin/bash" to "/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash"
substituteStream() in derivation bencodetools-unstable-2022-05-11: WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'configure')
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
patching script interpreter paths in ./configure
configure flags: --prefix=/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11

Install prefix:  /nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11
Library path:    /nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/lib
Compiler:        gcc
Python:          python3
Targets:         c python 

Configure successful
Running phase: buildPhase
build flags: -j8 SHELL=/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash
gcc -Wall -O2 -g -fPIC -shared -Iinclude  -c bencode.c
gcc -shared -Wl,-soname,libbencodetools.so -o "libbencodetools.so" bencode.o
gcc -Wall -O2 -g -Iinclude  -o "bencodetest" bencodetest.c -L. -Wl,-rpath,. -lbencodetools
gcc -Wall -O2 -g -Iinclude  -o "bencat" -L.  bencat.c -lbencodetools
Running phase: installPhase
install flags: -j8 SHELL=/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash install
Installing C library

mkdir -p -m 755 "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/lib" "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/include/bencodetools" "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/bin"
Installing Python packages
python3 setup.py install --prefix=/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11
install -m 644 include/bencodetools/*.h "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/include/bencodetools/"
install -m 644 libbencodetools.so "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/lib"
install bencat "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/bin/"
Traceback (most recent call last):
  File "/build/source/setup.py", line 3, in <module>
    from distutils.core import setup
  File "/nix/store/b51wasnpznffy17nw31i9p8mg6dyhk95-python3-3.12.7-env/lib/python3.12/site-packages/distutils/core.py", line 17, in <module>
    from .dist import Distribution
  File "/nix/store/b51wasnpznffy17nw31i9p8mg6dyhk95-python3-3.12.7-env/lib/python3.12/site-packages/distutils/dist.py", line 17, in <module>
    from packaging.utils import canonicalize_name, canonicalize_version
ModuleNotFoundError: No module named 'packaging'
make: *** [Makefile:51: install-python] Error 1
error: builder for '/nix/store/fx8f8c1sdy94kiddcigblf8z4nmx3bc0-bencodetools-unstable-2022-05-11.drv' failed with exit code 2;
       last 25 log lines:
       > build flags: -j8 SHELL=/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash
       > gcc -Wall -O2 -g -fPIC -shared -Iinclude  -c bencode.c
       > gcc -shared -Wl,-soname,libbencodetools.so -o "libbencodetools.so" bencode.o
       > gcc -Wall -O2 -g -Iinclude  -o "bencodetest" bencodetest.c -L. -Wl,-rpath,. -lbencodetools
       > gcc -Wall -O2 -g -Iinclude  -o "bencat" -L.  bencat.c -lbencodetools
       > Running phase: installPhase
       > install flags: -j8 SHELL=/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash install
       > Installing C library
       >
       >
       > mkdir -p -m 755 "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/lib" "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/include/bencodetools" "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/bin"
       > Installing Python packages
       > python3 setup.py install --prefix=/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11
       > install -m 644 include/bencodetools/*.h "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/include/bencodetools/"
       > install -m 644 libbencodetools.so "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/lib"
       > install bencat "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/bin/"
       > Traceback (most recent call last):
       >   File "/build/source/setup.py", line 3, in <module>
       >     from distutils.core import setup
       >   File "/nix/store/b51wasnpznffy17nw31i9p8mg6dyhk95-python3-3.12.7-env/lib/python3.12/site-packages/distutils/core.py", line 17, in <module>
       >     from .dist import Distribution
       >   File "/nix/store/b51wasnpznffy17nw31i9p8mg6dyhk95-python3-3.12.7-env/lib/python3.12/site-packages/distutils/dist.py", line 17, in <module>
       >     from packaging.utils import canonicalize_name, canonicalize_version
       > ModuleNotFoundError: No module named 'packaging'
       > make: *** [Makefile:51: install-python] Error 1
       For full logs, run 'nix log /nix/store/fx8f8c1sdy94kiddcigblf8z4nmx3bc0-bencodetools-unstable-2022-05-11.drv'.

## Build log

<details>

<summary>Build Log</summary>
```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/kh1s43j34z6lsz1vb2556ppvysk209n7-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
patching script interpreter paths in configure
configure: interpreter directive changed from "#!/bin/bash" to "/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash"
substituteStream() in derivation bencodetools-unstable-2022-05-11: WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'configure')
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
patching script interpreter paths in ./configure
configure flags: --prefix=/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11

Install prefix:  /nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11
Library path:    /nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/lib
Compiler:        gcc
Python:          python3
Targets:         c python 

Configure successful
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
build flags: -j8 SHELL=/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash
gcc -Wall -O2 -g -fPIC -shared -Iinclude  -c bencode.c
gcc -shared -Wl,-soname,libbencodetools.so -o "libbencodetools.so" bencode.o
gcc -Wall -O2 -g -Iinclude  -o "bencodetest" bencodetest.c -L. -Wl,-rpath,. -lbencodetools
gcc -Wall -O2 -g -Iinclude  -o "bencat" -L.  bencat.c -lbencodetools
Running phase: installPhase
@nix { "action": "setPhase", "phase": "installPhase" }
install flags: -j8 SHELL=/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash install
Installing C library


mkdir -p -m 755 "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/lib" "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/include/bencodetools" "/nix/store/9k8zjq9g3bwsf>
Installing Python packages
python3 setup.py install --prefix=/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11
install -m 644 include/bencodetools/*.h "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/include/bencodetools/"
install -m 644 libbencodetools.so "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/lib"
install bencat "/nix/store/9k8zjq9g3bwsflwmb96v75kycl7j8by4-bencodetools-unstable-2022-05-11/bin/"
Traceback (most recent call last):
  File "/build/source/setup.py", line 3, in <module>
    from distutils.core import setup
  File "/nix/store/b51wasnpznffy17nw31i9p8mg6dyhk95-python3-3.12.7-env/lib/python3.12/site-packages/distutils/core.py", line 17, in <module>
    from .dist import Distribution
  File "/nix/store/b51wasnpznffy17nw31i9p8mg6dyhk95-python3-3.12.7-env/lib/python3.12/site-packages/distutils/dist.py", line 17, in <module>
    from packaging.utils import canonicalize_name, canonicalize_version
ModuleNotFoundError: No module named 'packaging'
make: *** [Makefile:51: install-python] Error 1

```

</details>

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.11 (Vicuna), 24.11beta708443.057f63b6dc1a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/ianb/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/ianb/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/ianb/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/ianb/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf:/nix/store/v1c1alg3dzwmkwz31znxz5w7k3vhdkla-gnome-settings-daemon-47.1/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/kqpjnkkpv1drbnvrqbhnyd2ixy9dymzb-lix-2.91.1/share`
 - channels(root): `"home-manager-24.11.tar.gz, impermanence, lanzaboote, nixos-24.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

@OPNA2608 
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by OPNA2608** [comment]
Didn't notice that #352867 got in after the branch-off. Backporting it to 24.11 in #358742.
