### ISSUE TITLE
`flutterPackages-source.*.engine`: no `/out/host_*/gen/` in engine output?

### ISSUE THREAD

**Issue by sodiboo** [NixOS/nixpkgs#358937]
## Describe the bug

When trying to use `flutterPackages-source` to create a Flutter application using a custom embedder, [i need to run the command `flutter build bundle` to generate the required assets to instantiate the flutter engine](https://github.com/flutter/engine/blob/ce1eb371eafa791d3d25e5a031bfc47885859c4d/examples/glfw/run.sh#L30). This command fails with the following error message:

<details>

<summary>
Expand this to show the stacktrace

```
Target copy_flutter_bundle failed: PathNotFoundException: Cannot open file, path =
'/nix/store/ac3bxkinmi0210zx8cxqxxbq4hq2p8p3-flutter-engine-36335019a8eab588c3c2ea783c618d90505be233/out/host_debug_unopt/gen/flutter/lib/snapshot/vm_isolate_snapshot.bin' (OS Error: No such file or directory, errno = 2)
```
</summary>

```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      ForwardingFile.openSync (package:file/src/forwarding/forwarding_file.dart:74:16)
#3      ErrorHandlingFile.copySync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:324:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#5      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:323:5)
#6      CopyFlutterBundle.build (package:flutter_tools/src/build_system/targets/common.dart:74:12)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:27)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
<asynchronous suspension>
#9      BundleBuilder.build (package:flutter_tools/src/bundle_builder.dart:85:32)
<asynchronous suspension>
#10     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:145:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Failed to build bundle.
```

</details>

## Steps To Reproduce

1. Open any disposable working directory
2. Ensure `flutterPackages-source.stable` is in path.
3. `flutter --local-engine=host_debug_unopt --local-engine-host=host_debug_unopt create app`
4. `cd app`
5. `flutter --local-engine=host_debug_unopt --local-engine-host=host_debug_unopt build bundle`
6. Observe the above error.

## Expected behavior

The build should succeed and create a debug bundle of my app.

It looks like this is because the Flutter engine package is missing the `/out/host_*/gen/flutter/` directory, which is otherwise expected to be present in the engiine build root. Judging by the name, this is generated at build time, so the packaging is likely missing a step. I'd expect this step to be done during the build of the `flutterPackages-source.stable` package.

## Additional context

Currently, `flutterPackages-source.stable` doesn't build in nixpkgs. I observed the above behaviour with `flutterPackages-source` from 8c64c8887fd3c24b97781b49cc8ef87b283fc3bd.

Release builds work just fine (`flutter build bundle --release`; it doesn't matter which engine blob you specify in this case). The stacktrace points to [this line](https://github.com/flutter/flutter/blob/a0c3060c68d6f53970b6928f520f00128e2c122c/packages/flutter_tools/lib/src/build_system/targets/common.dart#L74) in the flutter source code. This makes it immediately obvious why the issue is only present in debug mode, because that whole section is wrapped in an `if (buildMode == BuildMode.debug)`.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.59, NixOS, 24.11 (Vicuna), 24.11.20241109.76612b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - channels(sodiboo): `""`
 - nixpkgs: `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source`

## Notify maintainers

@RossComputerGuy

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RossComputerGuy** [comment]
You need to run `flutter --local-engine=host_debug_unopt --local-engine-host=host_debug_unopt build bundle` with `--debug`.

**Comment by RossComputerGuy** [comment]
Hmm, it looks like we remove the gen directory.

https://github.com/NixOS/nixpkgs/blob/8c64c8887fd3c24b97781b49cc8ef87b283fc3bd/pkgs/development/compilers/flutter/engine/package.nix#L305

I think this was to save space, upstream doesn't have any information on packaging the engine so I'm not surprised we ran into this. Although, this is the first time I've seen this fail like this.

**Comment by sodiboo** [comment]
hm. I think it probably should be removed by default, like it currently is, but have an option to keep it, since it doesn't currently seem necessary in order to build apps in general (release mode), but it does seem necessary in order to use the actual flutter tool to iterate on debug builds in a dev shell. it would indeed save space on most end users' computers, using apps built with the stripped down engine output.

just how heavy is that folder anyways? how much of an improvement is achieved by removing it in the first place?
