### ISSUE TITLE
fetchCargoVendor not working for rustdesk-flutter

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#359340]
## Describe the bug

Wanted to switch the rustdesk-flutter build to the new cargo fetcher. Doesn't work.

```
Traceback (most recent call last):
  File "/nix/store/wadx2h6yard87zgvddshm3mx2nimagwc-fetch-cargo-vendor-util/bin/fetch-cargo-vendor-util", line 293, in <module>
    main()
  File "/nix/store/wadx2h6yard87zgvddshm3mx2nimagwc-fetch-cargo-vendor-util/bin/fetch-cargo-vendor-util", line 289, in main
    subcommand_func()
  File "/nix/store/wadx2h6yard87zgvddshm3mx2nimagwc-fetch-cargo-vendor-util/bin/fetch-cargo-vendor-util", line 281, in <lambda>
    "create-vendor": lambda: create_vendor(vendor_staging_dir=Path(sys.argv[2]), out_dir=Path(sys.argv[3]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wadx2h6yard87zgvddshm3mx2nimagwc-fetch-cargo-vendor-util/bin/fetch-cargo-vendor-util", line 238, in create_vendor
    copy_and_patch_git_crate_subtree(git_tree, pkg["name"], crate_out_dir)
  File "/nix/store/wadx2h6yard87zgvddshm3mx2nimagwc-fetch-cargo-vendor-util/bin/fetch-cargo-vendor-util", line 179, in copy_and_patch_git_crate_subtree
    shutil.copytree(crate_tree, crate_out_dir)
  File "/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/lib/python3.12/shutil.py", line 600, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/lib/python3.12/shutil.py", line 498, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/nix/store/0zn7mrd3dld2dmj2fxgpjb8skx45dx1w-cargo-deps-vendor/core-foundation-sys-0.8.6'
```

## Steps To Reproduce

1. ```nix
   cargoDeps = rustPlatform.fetchCargoVendor {
     inherit src; # hash fits for 1.3.3 but the problem happens on every release
     hash = "sha256-K9E2x01Y2WU0DewwKWXtnE92Jw2+uJOBUopHLvNs8Ew=";
   };
   ```
2. `nix-build`

## Expected behavior

It works

## Screenshots

Pretty much the text from above but rendered in my terminal

## Additional context

Don't know how the clownish developers were able to misuse their cargo so much but they somehow created a lock file with duplicate entries:

- https://github.com/rustdesk/rustdesk/blob/1.3.3/Cargo.lock#L1195
- https://github.com/rustdesk/rustdesk/blob/1.3.3/Cargo.lock#L1201

They don't seem to be aware of that and cargo seems to be fine with it.

## Metadata

<!-- Please insert the output of running `nix-shell -p nix-info --run "nix-info -m"` below this line -->

## Notify maintainers

<!--
Please @ people who are in the `meta.maintainers` list of the offending package or module.
If in doubt, check `git blame` for whoever last touched something.
-->

@TomaSajt @Bot-wxt1221 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
What's funny is that not even `cargo vendor` (the official vendor implementation) can handle this:
```
error: failed to sync

Caused by:
  found duplicate version of package `core-foundation-sys v0.8.6` vendored from two sources:

  	source 1: registry `crates-io`
  	source 2: https://github.com/madsmtm/core-foundation-rs.git?rev=7d593d016175755e492a92ef89edca68ac3bd5cd#7d593d01
 ```

**Comment by gepbird** [comment]
For now a patch to the lock file was added to work around this: https://github.com/NixOS/nixpkgs/blob/19224425817fb5368492bea791c7f434c6d2422c/pkgs/by-name/ru/rustdesk-flutter/update-cargo-lock.patch

**Comment by FliegendeWurst** [comment]
This also affects https://github.com/mediar-ai/screenpipe

**Comment by dotlambda** [comment]
... and https://github.com/deltachat/deltachat-desktop

**Comment by TomaSajt** [comment]
- Related: https://github.com/NixOS/nixpkgs/pull/387337

**Comment by TomaSajt** [comment]
> ... and https://github.com/deltachat/deltachat-desktop

Could you share which dependency is duplicated?

**Comment by dotlambda** [comment]
> > ... and https://github.com/deltachat/deltachat-desktop
> 
> Could you share which dependency is duplicated?

```
tauri-utils 2.2.0 (git+https://github.com/Simon-Laux/tauri?branch=add-is-always-on-top)
tauri-utils 2.2.0 (registry+https://github.com/rust-lang/crates.io-index)
```

**Comment by TomaSajt** [comment]
Ah, I see. It's both an electron app and a tauri app, but it is currently packaged as an electron app. I'm assuming building the tauri app would be better, but you aren't able to due to the duplication.

**Comment by dotlambda** [comment]
> I'm assuming building the tauri app would be better, but you aren't able to due to the duplication.

It's not better yet because the electron version is more stable. But I wanted to package the tauri version as a second option. I will try again on top of your PR.

**Comment by TomaSajt** [comment]
Also affects `oxide-rs`
(currently has a patch)
(the latest version no longer has duplication)

**Comment by elzorrorebelde** [comment]
I get this error when the source code of a dependency is used twice, i.e.:

```
sui-graphql-client = { git = "https://github.com/MystenLabs/sui-rust-sdk.git", rev = "7d485ababecf7282dc7d772316ccdb07b9b24753" }
sui-graphql-client-build = { git = "https://github.com/MystenLabs/sui-rust-sdk.git", rev = "7d485ababecf7282dc7d772316ccdb07b9b24753" }
```
