### ISSUE TITLE
sourcehut: gitsrht produces errors due to deprecated usage of pygit2.Oid.hex

### ISSUE THREAD

**Issue by selkie-diligent** [NixOS/nixpkgs#360939]
## Describe the bug

On https://github.com/NixOS/nixpkgs/commit/62c435d93bf046a5396f3016472e8f7c8e2aed65 (nixos-24.11) the gitsrht service reports several tracebacks with the same error ` AttributeError: '_pygit2.Oid' object has no attribute 'hex'`

Here an excerpt from the journal:
```
Traceback (most recent call last):
  File "/nix/store/43w1n2hfdq4p88bh0f379w4dlddqlgmf-python3-3.12.7-env/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/43w1n2hfdq4p88bh0f379w4dlddqlgmf-python3-3.12.7-env/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/43w1n2hfdq4p88bh0f379w4dlddqlgmf-python3-3.12.7-env/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/43w1n2hfdq4p88bh0f379w4dlddqlgmf-python3-3.12.7-env/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/43w1n2hfdq4p88bh0f379w4dlddqlgmf-python3-3.12.7-env/lib/python3.12/site-packages/gitsrht/blueprints/repo.py", line 146, in summary
    readme = get_readme(repo, git_repo, tip,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/43w1n2hfdq4p88bh0f379w4dlddqlgmf-python3-3.12.7-env/lib/python3.12/site-packages/gitsrht/blueprints/repo.py", line 90, in get_readme
    return get_formatted_readme("git.sr.ht:git", file_finder, content_getter,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/43w1n2hfdq4p88bh0f379w4dlddqlgmf-python3-3.12.7-env/lib/python3.12/site-packages/scmsrht/formatting.py", line 27, in get_formatted_readme
    content_hash, user_obj = file_finder(name)
                             ^^^^^^^^^^^^^^^^^
  File "/nix/store/43w1n2hfdq4p88bh0f379w4dlddqlgmf-python3-3.12.7-env/lib/python3.12/site-packages/gitsrht/blueprints/repo.py", line 84, in file_finder
    return blob.id.hex, blob
           ^^^^^^^^^^^
AttributeError: '_pygit2.Oid' object has no attribute 'hex'
```

## Steps To Reproduce

1. Setup sourcehut with gitsrht
2. Create a repository
3. Try accessing created repository on the web-frontend

## Additional context

It seems like this is fixed upstream https://git.sr.ht/~sircmpwn/git.sr.ht/commit/478457affd15f760c59944e0d73736ebfeaa2f4c and the gitsrht package just needs an update?

## Notify maintainers

@christoph-heiss @eadwu 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by selkie-diligent** [comment]
Fixed with https://github.com/NixOS/nixpkgs/pull/404203
