### ISSUE TITLE
Build failure: paperless-ngx

### ISSUE THREAD

**Issue by Kernald** [NixOS/nixpkgs#361006]
## Steps To Reproduce

1. build `paperless-ngx` from `release-24.11`

## Build log

https://hydra.nixos.org/build/280100659/nixlog/1

## Notify maintainers

@leona-ya @SuperSandro2000 @erikarvstedt 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Kernald** [comment]
For what it's worth, I'm getting the same error on my NixOS machine. That's with `9223372036854775807` as my `/proc/sys/fs/file-max`, which intuitively sounds like a _lot_... `lsof | wc -l` gives me `679705`, so nowhere close to the actual limit. I wonder if Nix builds run in a more limited sandbox?

**Comment by SuperSandro2000** [comment]
I have been deploying paperless-ngx since months on unstable without any issues so I am wondering from where this is coming from.

**Comment by puyral** [comment]
I have the same problem with what looks to me to be the same error log.

Doubling the number of available open file didn't resolve it (so I either failed at that, or the sandboxing does something)

The last working commit for me predates 24.11 and is 6f6076c37180ea3a916f84928cf3a714c5207a30 .

**Comment by SuperSandro2000** [comment]
I saw a similar problem today with black so it could be pytest or kennel related which I don't hop it is.

**Comment by Kernald** [comment]
Similar to the above, I can't manage to increase opened files (as reported by `ulimit`, on top of what's reported by `/proc/sys/fs/file-max` or `lsof`) in any way that makes any difference.

**Comment by Kernald** [comment]
Weirdly enough, increasing the nix-daemon file limit (`systemd.services.nix-daemon.serviceConfig.LimitNOFILE = lib.mkForce 16777216;`) also doesn't change anything. I have no clue where the limit actually comes from.

**Comment by SuperSandro2000** [comment]
I cannot reproduce it locally. No idea how to proceed.

**Comment by Kernald** [comment]
Do you happen to have sandboxing disabled or anything like that maybe?

**Comment by fabian-thomas** [comment]
I see the same behavior. After I upgraded my nixos-24.05 system to nixos-24.11, paperless-ngx wouldn't build anymore. I then disabled that service and switched to 24.11. Today I tried if I could simply use the 24.05 paperless-ngx package via `services.paperless.pkg`. Switching to that configuration made my entire system unusable because apparenlty also the 24.05 paperless-ngx opens too many files.

From that I can imagine two sources of this issue:
- Either nixos-24.11 changed the default file limits somehow that now paperless always triggers the limit (during build and in normal service).
- or, what I find more probable, paperless triggers some weird behavior in some system package. Pretty sure not kernel because I think that I couldnt build the 24.11 paperless-ngx even on the old 24.05 kernel.
- In particular, this means that if there is a bug in the paperless package, the bug was there in 24.05 already but only surfaced now. 

I hope that helps somehow in finding the root cause.

**Comment by SuperSandro2000** [comment]
> Do you happen to have sandboxing disabled or anything like that maybe?

Absolutely not. That is fully unsupported on x86_64-linux.

> Either nixos-24.11 changed the default file limits somehow that now paperless always triggers the limit (during build and in normal service).


I am not aware of anything like that.

> In particular, this means that if there is a bug in the paperless package, the bug was there in 24.05 already but only surfaced now.

I mean we already disabled pytest-xdist due to bugs...

**Comment by htngr** [comment]
> I cannot reproduce it locally. No idea how to proceed.

I upgraded from 24.05 to 24.11 and this error occurred. Rebuilt some minutes later without any config changes and it worked...

**Comment by Kernald** [comment]
I tried disabling paperless, upgrading to 24.11, rebooting and re-enabling it - still get the same error.

**Comment by mrVanDalo** [comment]
I have the same issue, but  on unstable-small. 

```
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/3d58debbb538678cf297954e520d4a4ea3ff2e15?narHash=sha256-NctMbHnOGW8ESuJ3UO5wz4/HnQXhx55ENRLMOtyJY88%3D' (2024-12-08)
  → 'github:nixos/nixpkgs/b356fafe02dd1d01d58153ae02326268ed584a51?narHash=sha256-2if5elTeQl08PNfyr4QNT1f3UDfdkEL4OtqS6aOkBPY%3D' (2024-12-09)
```

This is the first time the error appears for me. ( Update build my nix configuration every 6 hours to update my flake.lock, on success). Since 2024-12-09 i run in this error.

But this is long after this ticket was created. I guess it has to do with build-box divergence which is crucial now 🤷‍♂️
(hope this helps)

**Comment by diogotcorreia** [comment]
Seems like there's a different build error now? It's related to SQLite
https://hydra.nixos.org/build/281577640/nixlog/2

**Comment by SuperSandro2000** [comment]
That's a strange race condition I have encountered once before.

**Comment by SuperSandro2000** [comment]
Anyone has any idea how to fix this? If not I have literally no idea what to do here and would blame a general flakiness problem in upstreams tests.

**Comment by mrVanDalo** [comment]
> Anyone has any idea how to fix this? If not I have literally no idea what to do here and would blame a general flakiness problem in upstreams tests.

we could involve the developers, if they experienced and solved this issue 🤷

**Comment by pSub** [comment]
I stumbled upon this issue yesterday when updating my machine that runs paperless. It is an aarch64-linux machine and the build fails with `KeyError: 'getgrgid(): gid not found: 30000'` in the `path_check` test case (https://github.com/pSub/configs/actions/runs/12575376181/job/35050288279#step:10:2252). That is the only error on my machine. The latest hydra build (https://hydra.nixos.org/build/283307027/nixlog/1) has those "too many open files" problem, but not the "gid problem".

**Comment by mrVanDalo** [comment]
I could verify that on my build-server I run in the same problem like hybris "too many open files".
This comment could help me https://discourse.nixos.org/t/unable-to-fix-too-many-open-files-error/27094/7

After I stopped almost all my nixos-containers (I'm running around 10 containers usually on that machine) I could run

```
nix-build -E 'with import <nixpkgs> {} ; callPackage ./package.nix {}';
```
in `nixpkgs/pkgs/by-name/pa/paperless-ngx` only one error (a pdf is missing or something).

```
Executing pytestCheckPhase
bringing up nodes...
........................................................................ [  6%]
........................................................................ [ 12%]
........................................................................ [ 19%]
.......................................................s................ [ 25%]
........................................................................ [ 32%]
........................................................................ [ 38%]
........................................................................ [ 45%]
........................................................................ [ 51%]
...............................................................s........ [ 58%]
.......................ss............................................... [ 64%]
........................................................................ [ 70%]
........................................................................ [ 77%]
...............................................ssss..................... [ 83%]
......................................................F................. [ 90%]
........................................................................ [ 96%]
...........sssss....s................                                    [100%]
```

After starting all the nixos-containers again. The same command resulted again in the "too many open files" Errors.

```
Executing pytestCheckPhase
bringing up nodes...
........................................................................ [  6%]
........................................................................ [ 12%]
........................................................................ [ 19%]
.......................................................s................ [ 25%]
........................................................................ [ 32%]
........................................................................ [ 38%]
........................................................................ [ 45%]
........................................................................ [ 51%]
...............................................s........................ [ 58%]
...........................ss........................................... [ 64%]
........................................................................ [ 70%]
........................................................................ [ 77%]
...........................................ssss............F............ [ 83%]
............F..F.F.F...............F................................F... [ 90%]
........................................................................ [ 96%]
...............ssssss.........F...FFF                                    [100%]
````


I will continue my investigation tomorrow.

**Comment by mrVanDalo** [comment]
Hmm, I couldn't make the package build on that machine. But on one of my laptops it builds without problems. As a hotfix, because I couldn't update for a Month now, I just use nix-copy-closure for now.

One thing in which my laptop an my build-server is that the bulid server uses the hardnend profile https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/hardened.nix (but haven't checked if that is the problem solver)

**Comment by sersorrel** [comment]
For me, only `src/documents/tests/test_migration_document_pages_count.py::TestMigrateDocumentPageCount::testDocumentPageCountMigrated` fails, with `FileNotFoundError: [Errno 2] No such file or directory: '/build/tmpnl2vkz70/file1.pdf'`. It's trying to write to that file, so the temporary directory is either not getting created or is deleted too soon; I wonder therefore if this is related to the recent PR to enable pytest-xdist: #364966 

aha, yes, it succeeded on the third try, so that is just flaky rather than outright broken. (IMO xdist should still be disabled, if it does not consistently work.)

**Comment by Kernald** [comment]
This is a different issue than the too many open files, which started earlier than this PR was merged, and fails 100% of the time on machines where it fails.

**Comment by SuperSandro2000** [comment]
> IMO xdist should still be disabled, if it does not consistently work

I am not a big fan of that because without it the tests take a really long time and I would try to avoid it.

---

As already said earlier, I cannot reproduce this issue so it is probably some configuration issue like kernel or maybe sysctl settings. I really have no clue.

**Comment by Kernald** [comment]
> well, it clearly does not fail 100% of the time for me :)

Because you're hitting a different problem than the one this issue is about - that's exactly what I'm saying. This issue is specifically about `test_consume_existing_file` failing with a `Too many open files` error, which seems like a system limit which got introduced somehow at some point only on specific machines but fails 100% of the time on machines where it fails, when you're having a `xdist` related issue on another, different test (`testDocumentPageCountMigrated`), that's not 100% reproducible on the same machine.

**Comment by bachp** [comment]
@rrix I can confirm that increasing `fs.inotify.max_user_watches` and `fs.inotify.max_user_instances` now makes the build pass on the machine it consistently failed before.

**Comment by SuperSandro2000** [comment]
That's a nice observation! Can we globally bump this by default?

**Comment by pschmitt** [comment]
> @rrix I can confirm that increasing `fs.inotify.max_user_watches` and `fs.inotify.max_user_instances` now makes the build pass on the machine it consistently failed before.

What did you set it to?

**Comment by SuperSandro2000** [comment]
probably to something like https://github.com/NixOS/nixpkgs/blob/e6914ee14cc9ef2221e9ac323c59cab1ae029684/nixos/modules/services/misc/graphical-desktop.nix#L24-L30

**Comment by pSub** [comment]
>  if it was up to me i'd just cram it in hydra builders' default system configurations.

That sounds like the way to go 👍

**Comment by SuperSandro2000** [comment]
We could just skip tests in the package for the module 🤔

**Comment by alarsyo** [comment]
I'm getting a real test failure when building on my machine now:

<details>
```
=================================== FAILURES ===================================
________________________ TestMail.test_error_skip_rule _________________________

self = <paperless_mail.tests.test_mail.TestMail testMethod=test_error_skip_rule>

    def test_error_skip_rule(self):
        account = MailAccount.objects.create(
            name="test2",
            imap_server="",
            username="admin",
            password="secret",
        )
        _ = MailRule.objects.create(
            name="testrule",
            account=account,
            action=MailRule.MailAction.MOVE,
            action_parameter="spam",
            filter_subject="Claim",
            order=1,
            folder="uuuhhhh",
        )
        _ = MailRule.objects.create(
            name="testrule2",
            account=account,
            action=MailRule.MailAction.MOVE,
            action_parameter="spam",
            filter_subject="Claim",
            order=2,
        )
    
        self.mail_account_handler.handle_mail_account(account)
        self.mailMocker.apply_mail_actions()
    
>       self.assertEqual(len(self.mailMocker.bogus_mailbox.messages), 2)
E       AssertionError: 1 != 2

src/paperless_mail/tests/test_mail.py:1093: AssertionError
----------------------------- Captured stderr call -----------------------------
[2025-03-15 15:56:04,819] [ERROR] [paperless_mail] Unable to access folder uuuhhhh, attempting folder listing
[2025-03-15 15:56:04,819] [ERROR] [paperless_mail] Exception during folder listing, unable to provide list folders: 'BogusFolderManager' object has no attribute 'list'
[2025-03-15 15:56:04,819] [ERROR] [paperless_mail] Rule test2.testrule: Error while processing rule: Rule test2.testrule: Folder uuuhhhh does not exist in account test2
Traceback (most recent call last):
  File "/build/source/src/paperless_mail/mail.py", line 601, in _handle_mail_rule
    M.folder.set(folder)
  File "/build/source/src/paperless_mail/tests/test_mail.py", line 54, in set
    raise MailboxFolderSelectError(None, "uhm")
imap_tools.errors.MailboxFolderSelectError: <exception str() failed>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/build/source/src/paperless_mail/mail.py", line 564, in handle_mail_account
    total_processed_files += self._handle_mail_rule(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/src/paperless_mail/mail.py", line 615, in _handle_mail_rule
    raise MailError(
paperless_mail.mail.MailError: Rule test2.testrule: Folder uuuhhhh does not exist in account test2
------------------------------ Captured log call -------------------------------
DEBUG    paperless_mail:mail.py:462 Skipping mail preprocessor MailMessageDecryptor
DEBUG    paperless_mail:mail.py:526 Processing mail account test2
DEBUG    paperless_mail:mail.py:549 GMAIL Label Support: False
DEBUG    paperless_mail:mail.py:550 AUTH=PLAIN Support: False
DEBUG    paperless_mail:mail.py:554 Account test2: Processing 2 rule(s)
DEBUG    paperless_mail:mail.py:600 Rule test2.testrule: Selecting folder spam
DEBUG    paperless_mail:mail.py:600 Rule test2.testrule: Selecting folder uuuhhhh
ERROR    paperless_mail:mail.py:603 Unable to access folder uuuhhhh, attempting folder listing
ERROR    paperless_mail:mail.py:610 Exception during folder listing, unable to provide list folders: 'BogusFolderManager' object has no attribute 'list'
ERROR    paperless_mail:mail.py:570 Rule test2.testrule: Error while processing rule: Rule test2.testrule: Folder uuuhhhh does not exist in account test2
Traceback (most recent call last):
  File "/build/source/src/paperless_mail/mail.py", line 601, in _handle_mail_rule
    M.folder.set(folder)
  File "/build/source/src/paperless_mail/tests/test_mail.py", line 54, in set
    raise MailboxFolderSelectError(None, "uhm")
imap_tools.errors.MailboxFolderSelectError: <exception str() failed>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/build/source/src/paperless_mail/mail.py", line 564, in handle_mail_account
    total_processed_files += self._handle_mail_rule(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/src/paperless_mail/mail.py", line 615, in _handle_mail_rule
    raise MailError(
paperless_mail.mail.MailError: Rule test2.testrule: Folder uuuhhhh does not exist in account test2
DEBUG    paperless_mail:mail.py:600 Rule test2.testrule2: Selecting folder spam
DEBUG    paperless_mail:mail.py:600 Rule test2.testrule2: Selecting folder INBOX
DEBUG    paperless_mail:mail.py:622 Rule test2.testrule2: Searching folder with criteria (SINCE 13-Feb-2025 SUBJECT "Claim")
DEBUG    paperless_mail:mail.py:682 Rule test2.testrule2: Processing mail Claim your $10M price now! from amazon@amazon-some-indian-site.org with 1 attachment(s)
INFO     paperless_mail:mail.py:808 Rule test2.testrule2: Consuming attachment file_0.pdf from mail Claim your $10M price now! from amazon@amazon-some-indian-site.org
DEBUG    paperless_mail:mail.py:665 Rule test2.testrule2: Processed 1 matching mail(s)
```
</details>

**Comment by SuperSandro2000** [comment]
There is going to be a new minor update soon. Let's take that opportunity to try to do something about this. I cannot observe similar issues on my deployment but I also have the default limits for all my systems increased.

**Comment by alarsyo** [comment]
I was wrong, retrying the build worked after a few tries, so that's definitely related. Sorry for the noise!

**Comment by SuperSandro2000** [comment]
Is this still happening? I haven't seen this in a while myself. If not I would like to close this issue because for me it is not really actionable.

**Comment by bachp** [comment]
I haven't seen the issue, but I am running build on a machine with increased `fs.inotify.max_user_watches` and `fs.inotify.max_user_instances`

**Comment by SuperSandro2000** [comment]
Isn't the nix-daemon already increasing that via LimitNOFILE?
