### ISSUE TITLE
open-webui missing emoji dependency

### ISSUE THREAD

**Issue by mentalblock** [NixOS/nixpkgs#361295]
## Describe the bug

Attempting to upload an epub document for RAG causes an error about the Python module `emoji` not being available.

This is running on Nixpkgs on revision `ac35b104800bff9028425fec3b6e8a41de2bbfff`. The version of open-webui is `v0.4.6`.

Here is the log
```
Dec 02 20:27:18 shonuff open-webui[41853]: INFO  [open_webui.apps.webui.routers.files] file.content_type: application/epub+zip
Dec 02 20:27:18 shonuff open-webui[41853]: ERROR [open_webui.apps.retrieval.main] No module named 'emoji'
Dec 02 20:27:18 shonuff open-webui[41853]: Traceback (most recent call last):
Dec 02 20:27:18 shonuff open-webui[41853]:   File "/nix/store/35bq4z96b19f9l1khm1f9900q9n8nxld-open-webui-0.4.6/lib/python3.12/site-packages/open_webui/apps/retrieval/main.py", line 954, in process_file
Dec 02 20:27:18 shonuff open-webui[41853]:     docs = loader.load(
Dec 02 20:27:18 shonuff open-webui[41853]:            ^^^^^^^^^^^^
Dec 02 20:27:18 shonuff open-webui[41853]:   File "/nix/store/35bq4z96b19f9l1khm1f9900q9n8nxld-open-webui-0.4.6/lib/python3.12/site-packages/open_webui/apps/retrieval/loaders/main.py", line 125, in load
Dec 02 20:27:18 shonuff open-webui[41853]:     docs = loader.load()
Dec 02 20:27:18 shonuff open-webui[41853]:            ^^^^^^^^^^^^^
Dec 02 20:27:18 shonuff open-webui[41853]:   File "/nix/store/d87c3irw7lnri42w3lizsrji4mmfva9j-python3.12-langchain-core-0.3.15/lib/python3.12/site-packages/langchain_core/document_loaders/base.py", li>
Dec 02 20:27:18 shonuff open-webui[41853]:     return list(self.lazy_load())
Dec 02 20:27:18 shonuff open-webui[41853]:            ^^^^^^^^^^^^^^^^^^^^^^
Dec 02 20:27:18 shonuff open-webui[41853]:   File "/nix/store/xfh6k36hayglrvlqk58dk5c4ysnz7g34-python3.12-langchain-community-0.3.6/lib/python3.12/site-packages/langchain_community/document_loaders/uns>
Dec 02 20:27:18 shonuff open-webui[41853]:     elements = self._get_elements()
Dec 02 20:27:18 shonuff open-webui[41853]:                ^^^^^^^^^^^^^^^^^^^^
Dec 02 20:27:18 shonuff open-webui[41853]:   File "/nix/store/xfh6k36hayglrvlqk58dk5c4ysnz7g34-python3.12-langchain-community-0.3.6/lib/python3.12/site-packages/langchain_community/document_loaders/epu>
Dec 02 20:27:18 shonuff open-webui[41853]:     from unstructured.partition.epub import partition_epub
Dec 02 20:27:18 shonuff open-webui[41853]:   File "/nix/store/1il3n26rgnfqz76xjhm6w66k786whx0x-python3.12-unstructured-0.16.8/lib/python3.12/site-packages/unstructured/partition/epub.py", line 6, in <m>
Dec 02 20:27:18 shonuff open-webui[41853]:     from unstructured.file_utils.file_conversion import convert_file_to_html_text_using_pandoc
Dec 02 20:27:18 shonuff open-webui[41853]:   File "/nix/store/1il3n26rgnfqz76xjhm6w66k786whx0x-python3.12-unstructured-0.16.8/lib/python3.12/site-packages/unstructured/file_utils/file_conversion.py", l>
Dec 02 20:27:18 shonuff open-webui[41853]:     from unstructured.partition.common.common import exactly_one
Dec 02 20:27:18 shonuff open-webui[41853]:   File "/nix/store/1il3n26rgnfqz76xjhm6w66k786whx0x-python3.12-unstructured-0.16.8/lib/python3.12/site-packages/unstructured/partition/common/common.py", line>
Dec 02 20:27:18 shonuff open-webui[41853]:     import emoji
Dec 02 20:27:18 shonuff open-webui[41853]: ModuleNotFoundError: No module named 'emoji'
```

## Steps To Reproduce

1. When starting a new chat, hit the `+` icon and upload an epub.

or

1. Create a new knowledge base in the Workspace and try and upload an epub.

An error pops up in the UI and checking the logs show errors like the above

## Expected behavior

No errors when uploading epub documents and the capability to query against the document.

## Notify maintainers

@shivaraj-bh 
@drupol 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
Thanks for the report.

The module is also missing from upstream's pyproject.toml. (cc @tbjck).

Can you create a PR and add the missing dependency? Ideally 2 PRs needs to be made, one in nixpkgs, the other in open-webui.

**Comment by shivaraj-bh** [comment]
That was quick! Thanks @drupol

**Comment by mentalblock** [comment]
Similar to https://github.com/NixOS/nixpkgs/issues/361550#issuecomment-2515798212

this dependency actually needs to be added for the `unstructured` package. 

The upstream package declaration is https://github.com/Unstructured-IO/unstructured/blob/0fb814db6188813df61fd3aeb1905a9dae21771c/requirements/base.txt#L39

@happysalada
