### ISSUE TITLE
Unifi controller fails to load sdnotify

### ISSUE THREAD

**Issue by suominen** [NixOS/nixpkgs#361381]
## Describe the bug

During a restore from backup, the Unifi Controller fails during shutdown because sdnotify cannot be loaded. This leaves the controller down.

Manually starting the controller with `systemctl start unifi` succeeds, but the logs show an error trying to load sdnotify.

## Steps To Reproduce

1. `systemctl start unifi`

## Expected behavior

There should be no errors about failing to load dynamic libraries. A restore should successfully restart the controller.

## Screenshots

Logs when restoring from backup:

```
[2024-12-03T09:30:58,763+02:00] <webapi-1> INFO  setup  - Restoring backup on UDM device: false, backup contains UDM device: false
[2024-12-03T09:30:58,788+02:00] <webapi-1> INFO  setup  - Restoring system.properties from backup
[2024-12-03T09:30:58,835+02:00] <webapi-1> INFO  setup  - Restoring debug.setting_preference=auto
[2024-12-03T09:30:58,850+02:00] <webapi-1> INFO  setup  - Restoring debug.mgmt=warn
[2024-12-03T09:30:58,860+02:00] <webapi-1> INFO  setup  - Restoring debug.device=warn
[2024-12-03T09:30:58,869+02:00] <webapi-1> INFO  setup  - Restoring debug.system=warn
[2024-12-03T09:30:58,879+02:00] <webapi-1> INFO  setup  - Restoring debug.sdn=warn
[2024-12-03T09:30:59,243+02:00] <shutdown-listener> ERROR sdnotify - failed to load ubnt_sdnotify_jni
java.lang.UnsatisfiedLinkError: /var/lib/unifi/lib/native/Linux/x86_64/libubnt_sdnotify_jni.so: libsystemd.so.0: cannot open shared object file: No such file or directory
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1970)
        at com.ubnt.sdnotify.SDNotify.loadLibrary(Unknown Source)
        at com.ubnt.sdnotify.SDNotify.notify(Unknown Source)
        at com.ubnt.sdnotify.SDNotify.stopping(Unknown Source)
        at com.ubnt.sdnotify.C.class(Unknown Source)
        at com.ubnt.service.ooOO.õÕ0000(Unknown Source)
        at com.ubnt.service.ooOO.nullnew(Unknown Source)
        at com.ubnt.service.system.o0ooo.ÓÖØ000(Unknown Source)
        at com.ubnt.service.system.o0ooo.ÔÒØ000(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:840)
[2024-12-03T09:30:59,369+02:00] <shutdown-listener> WARN  system - cannot stop task stat-processor (is running?)
[2024-12-03T09:30:59,369+02:00] <shutdown-listener> WARN  system - cannot stop task crash-report (is running?)
```

There is a long list of `WARN` messages about _cannot stop task_.

----

Log entry when starting the controller:

```
[2024-12-03T09:41:31,843+02:00] <launcher> ERROR sdnotify - failed to load ubnt_sdnotify_jni
java.lang.UnsatisfiedLinkError: /var/lib/unifi/lib/native/Linux/x86_64/libubnt_sdnotify_jni.so: libsystemd.so.0: cannot open shared object file: No such file or directory
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1970)
        at com.ubnt.sdnotify.SDNotify.loadLibrary(Unknown Source)
        at com.ubnt.sdnotify.SDNotify.notify(Unknown Source)
        at com.ubnt.sdnotify.SDNotify.ready(Unknown Source)
        at com.ubnt.sdnotify.C.Ó00000(Unknown Source)
        at com.ubnt.sdnotify.C.Ô00000(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
        at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
        at com.google.common.eventbus.EventBus.post(EventBus.java:270)
        at com.ubnt.service.system.event.O0OO.Ô00000(Unknown Source)
        at com.ubnt.net.Object.oÓ0000(Unknown Source)
        at com.ubnt.net.Object.ÔÓ0000(Unknown Source)
        at com.ubnt.service.ooOO.returnObject(Unknown Source)
        at com.ubnt.ace.Launcher.Object(Unknown Source)
        at com.ubnt.ace.Launcher.main(Unknown Source)
```

## Additional context

I was upgrading from 24.05 to 24.11 when I ran into this issue. In anticipation of MongoDB possibly failing to upgrade its database automatically, I downloaded a settings backup from the controller before the upgrade.

MongoDB did not upgrade successfully to 6.0 (due to `featureCompatibilityVersion` being set to `4.4` in the database), so I rebuilt with 7.0 before restoring the controller from the backup.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 24.11 (Vicuna), 24.11.710050.62c435d93bf0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos-24.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

@globin @Patryk27 @qubitnano 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by qubitnano** [comment]
I was able to patchelf libubnt_sdnotify_jni.so which loads it now, and setting `Type = "notify";` in the service seems to use it.

However setting `Restart = "always";` to the unifi service actually fixes the restoring from backup and is still needed even with sdnotify patched. But I may have missed some other systemd settings.

I've opened https://github.com/NixOS/nixpkgs/pull/361945 for testing
