### ISSUE TITLE
open-webui and NLTK problems

### ISSUE THREAD

**Issue by mentalblock** [NixOS/nixpkgs#361566]
## Describe the bug

Attempting to upload an epub document for RAG causes multiple errors regarding NLTK. The following errors are present:

1. A temporary directory is needed for the NLTK library to function.
2. After the above issue is resolved (see below), the NLTK tokenizer `punkt_tab` is not available

logs:
```
Dec 03 14:41:03 shonuff open-webui[97083]: INFO  [open_webui.apps.webui.routers.files] file.content_type: application/epub+zip
Dec 03 14:41:25 shonuff open-webui[97083]: ERROR [open_webui.apps.retrieval.main] [Errno 30] Read-only file system: '/nltk_data'
Dec 03 14:41:25 shonuff open-webui[97083]: Traceback (most recent call last):
Dec 03 14:41:25 shonuff open-webui[97083]:   File "/nix/store/zakikqrx0kr5yqy58q0bsl2xh1ds13lm-open-webui-0.4.7/lib/python3.12/site-packages/open_webui/apps/retrieval/main.py", line 960, in process_file
Dec 03 14:41:25 shonuff open-webui[97083]:     docs = loader.load(
Dec 03 14:41:25 shonuff open-webui[97083]:            ^^^^^^^^^^^^
Dec 03 14:41:25 shonuff open-webui[97083]:   File "/nix/store/zakikqrx0kr5yqy58q0bsl2xh1ds13lm-open-webui-0.4.7/lib/python3.12/site-packages/open_webui/apps/retrieval/loaders/main.py", line 125, in load
Dec 03 14:41:25 shonuff open-webui[97083]:     docs = loader.load()
Dec 03 14:41:25 shonuff open-webui[97083]:            ^^^^^^^^^^^^^
```

This is resolved by setting the NLTK_DATA variable. See https://www.nltk.org/data.html#command-line-installation. I set it temporarily like so:
```
      NLTK_DATA = "${config.services.open-webui.stateDir}";
```

The second error from not having the `punkt_tab` tokenizer:
```
Dec 03 15:09:20 shonuff open-webui[104973]: INFO  [open_webui.apps.webui.routers.files] file.content_type: application/epub+zip
Dec 03 15:09:42 shonuff open-webui[104973]: ERROR [open_webui.apps.retrieval.main]
Dec 03 15:09:42 shonuff open-webui[104973]: **********************************************************************
Dec 03 15:09:42 shonuff open-webui[104973]:   Resource punkt_tab not found.
Dec 03 15:09:42 shonuff open-webui[104973]:   Please use the NLTK Downloader to obtain the resource:
Dec 03 15:09:42 shonuff open-webui[104973]:   >>> import nltk
Dec 03 15:09:42 shonuff open-webui[104973]:   >>> nltk.download('punkt_tab')
Dec 03 15:09:42 shonuff open-webui[104973]:
Dec 03 15:09:42 shonuff open-webui[104973]:   For more information see: https://www.nltk.org/data.html
Dec 03 15:09:42 shonuff open-webui[104973]:   Attempted to load tokenizers/punkt_tab/english/
Dec 03 15:09:42 shonuff open-webui[104973]:   Searched in:
Dec 03 15:09:42 shonuff open-webui[104973]:     - '/var/lib/open-webui'
Dec 03 15:09:42 shonuff open-webui[104973]:     - '/nltk_data'
Dec 03 15:09:42 shonuff open-webui[104973]:     - '/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/nltk_data'
Dec 03 15:09:42 shonuff open-webui[104973]:     - '/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/share/nltk_data'
Dec 03 15:09:42 shonuff open-webui[104973]:     - '/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/nltk_data'
Dec 03 15:09:42 shonuff open-webui[104973]:     - '/usr/share/nltk_data'
Dec 03 15:09:42 shonuff open-webui[104973]:     - '/usr/local/share/nltk_data'
Dec 03 15:09:42 shonuff open-webui[104973]:     - '/usr/lib/nltk_data'
Dec 03 15:09:42 shonuff open-webui[104973]:     - '/usr/local/lib/nltk_data'
```

## Steps To Reproduce

1. When starting a new chat, hit the + icon and upload an epub.

or

1. Create a new knowledge base in the Workspace and upload an epub.

## Notify maintainers

@shivaraj-bh
@drupol

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mentalblock** [comment]
I think you replied to the wrong issue. I do not explicitly mention any missing dependencies here. Perhaps you meant to reply on https://github.com/NixOS/nixpkgs/issues/361550?

I do not know the correct solution for this specific issue. I was hoping someone with more Nix experience could help here.

**Comment by mentalblock** [comment]
To add more context, I am running Nixpkgs revision `55d15ad12a74eb7d4646254e13638ad0c4128776`.

I think there are a couple of issues here:
* The version of the `unstructured` Python dependency used `0.16.8` when the upstream open-webui project uses [0.15.9](https://github.com/open-webui/open-webui/blob/c4ea31357f49d08a14c86b2bd85fdcd489512e91/pyproject.toml#L68)
* There has been a refactoring of the NLTK code in the `unstructured` module with version [0.16.9](https://github.com/Unstructured-IO/unstructured/releases/tag/0.16.9), so that may hold some promise

This is a rabbit hole much deeper than I anticipated and will not be able to investigate more anytime soon.

**Comment by drupol** [comment]
Is there an environment variable to set this? Have you checked if the module NLTK is using one?

**Comment by dojoca** [comment]
Having the same problem here on 0.6.13. Can't upload any files.

**Comment by drupol** [comment]
🤷
