### ISSUE TITLE
esphome: Component not found: font

### ISSUE THREAD

**Issue by amarshall** [NixOS/nixpkgs#362193]
## Describe the bug

Font component seems to no longer work, possibly due to Python dependency upgrades or incompatibilities (see additional context below).

## Steps To Reproduce

1. Build some esphome config that uses the font module (sorry don’t currently have a minimal repro)
2. Gives error:

```
ERROR Unable to load component font:
Traceback (most recent call last):
  File "/nix/store/sdpvvh15i4am2dncrmikfilz5myxchyd-esphome-2024.11.1/lib/python3.12/site-packages/esphome/loader.py", line 177, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/nix/store/sdpvvh15i4am2dncrmikfilz5myxchyd-esphome-2024.11.1/lib/python3.12/site-packages/esphome/components/font/__init__.py", line 10, in <module>
    import glyphsets
  File "/nix/store/82xg1fkdbawldvn5l4qmrzfljcsf0460-python3.12-glyphsets-1.0.0/lib/python3.12/site-packages/glyphsets/__init__.py", line 4, in <module>
    import gflanguages
  File "/nix/store/sns5i2pry9f5x29bzkszgw8kzqb87yib-python3.12-gflanguages-0.6.5/lib/python3.12/site-packages/gflanguages/__init__.py", line 26, in <module>
    from gflanguages import languages_public_pb2
  File "/nix/store/sns5i2pry9f5x29bzkszgw8kzqb87yib-python3.12-gflanguages-0.6.5/lib/python3.12/site-packages/gflanguages/languages_public_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/nix/store/qs1dq3148cidflfqkl7nlg8qij0m77ja-python3.12-protobuf-5.28.3/lib/python3.12/site-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Failed config
```

## Expected behavior

No error.

## Additional context

- See possibly related previous issue https://github.com/NixOS/nixpkgs/issues/272334
- Works on dc460ec76cbff0e66e269457d7b728432263166c, where pillow is 10.4.0

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 25.05 (Warbler), 25.05.20241128.fa42b5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`

## Notify maintainers

@globin @mweinelt 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
This is all due to gflanguages pinning to protobuf<4 for fontbakery.

This will get worse, since the next aioesphomeapi project (required by home-assistant 2024.12.1) brings aioesphomeapi==28.0.0, which wants protobuf>=4.

https://github.com/esphome/aioesphomeapi/commit/6a6ae4a708226ec34364877619ecaf2a6e0b61a0

I guess we"ll go for the python protobuf implementation for now. Preparing a PR in a minute.
