### ISSUE TITLE
Camelot fails because of missing ghostscript dependency

### ISSUE THREAD

**Issue by matthuszagh** [NixOS/nixpkgs#362939]
Take the following flake (nixpkgs rev is 1e56a3b5efd3c4c1451f891863cfb72e471687f7):

```
{
  inputs.nixpkgs.url = github:nixos/nixpkgs;

  outputs =
    { self
    , nixpkgs
    }: {
      devShell.x86_64-linux =
        let
          system = "x86_64-linux";
          pkgs = (import nixpkgs { inherit system; }).pkgs;
        in
        pkgs.mkShell {
          buildInputs = (with pkgs; [
            (python3.withPackages (p: with p; [
              camelot
            ]))
          ]);
        };
    };
}
```

Now, start python and

```
import camelot
tables = camelot.read_pdf("tlv3511-q1.pdf")
```

This emits the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/8kbmmpb8r84y89132q6bpcj85an1n0sv-python3-3.12.7-env/lib/python3.12/site-packages/camelot/io.py", line 113, in read_pdf
    tables = p.parse(
             ^^^^^^^^
  File "/nix/store/8kbmmpb8r84y89132q6bpcj85an1n0sv-python3-3.12.7-env/lib/python3.12/site-packages/camelot/handlers.py", line 176, in parse
    t = parser.extract_tables(
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8kbmmpb8r84y89132q6bpcj85an1n0sv-python3-3.12.7-env/lib/python3.12/site-packages/camelot/parsers/lattice.py", line 421, in extract_tables
    self.backend.convert(self.filename, self.imagename)
  File "/nix/store/8kbmmpb8r84y89132q6bpcj85an1n0sv-python3-3.12.7-env/lib/python3.12/site-packages/camelot/backends/ghostscript_backend.py", line 31, in convert
    raise OSError(
OSError: Ghostscript is not installed. You can install it using the instructions here: https://camelot-py.readthedocs.io/en/master/user/install-deps.html
```

I can explicitly provide ghostscript in the flake with (though it should be a runtime dependency)

```
{
  inputs.nixpkgs.url = github:nixos/nixpkgs;

  outputs =
    { self
    , nixpkgs
    }: {
      devShell.x86_64-linux =
        let
          system = "x86_64-linux";
          pkgs = (import nixpkgs { inherit system; }).pkgs;
        in
        pkgs.mkShell {
          buildInputs = (with pkgs; [
            (python3.withPackages (p: with p; [
              camelot
            ]))
            ghostscript
          ]);
        };
    };
}
```

Then, the error is

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/8kbmmpb8r84y89132q6bpcj85an1n0sv-python3-3.12.7-env/lib/python3.12/site-packages/camelot/io.py", line 113, in read_pdf
    tables = p.parse(
             ^^^^^^^^
  File "/nix/store/8kbmmpb8r84y89132q6bpcj85an1n0sv-python3-3.12.7-env/lib/python3.12/site-packages/camelot/handlers.py", line 176, in parse
    t = parser.extract_tables(
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8kbmmpb8r84y89132q6bpcj85an1n0sv-python3-3.12.7-env/lib/python3.12/site-packages/camelot/parsers/lattice.py", line 421, in extract_tables
    self.backend.convert(self.filename, self.imagename)
  File "/nix/store/8kbmmpb8r84y89132q6bpcj85an1n0sv-python3-3.12.7-env/lib/python3.12/site-packages/camelot/backends/ghostscript_backend.py", line 36, in convert
    import ghostscript
ModuleNotFoundError: No module named 'ghostscript'
```

@2gn @bcdarwin

**Comment by 2gn** [comment]
We might need to package the [ghostscript Python package](https://pypi.org/project/ghostscript/) to successfully build the package—apologies for the inconvenience. In the meantime, you could consider using a tool like [devenv](https://devenv.sh/) to run your program.

**Comment by matthuszagh** [comment]
Thanks for the suggestion. I'm not too familiar with devenv but (among other things) it sounds like it makes it easy to use packages from various versions of nixpkgs. Is that right? In that case, are you suggesting I take an old version of camelot, or that the ghostscript python package was previously available in nixpkgs?

I tried pinning nixpkgs to rev b6dbd73a77ba76f2d14ac3b7e319c3dae1132a7b (the commit in which camelot was introduced), but I still get the same "No module named 'ghostscript'" error in that case.

**Comment by 2gn** [comment]
> it sounds like it makes it easy to use packages from various versions of nixpkgs. 

Maybe, but I used it for managing my python projects. See: https://devenv.sh/supported-languages/python/#languagespythondirectory

specifying camelot somewhere like `languages.python.uv.package` should work because this way the package installation doesn't depend on Nix, but will still be managed by Nix ecosystem.
