### ISSUE TITLE
Update request: tribler 7.14.0 → 8.0.6

### ISSUE THREAD

**Issue by ISibboI** [NixOS/nixpkgs#363228]
## Package Information

- Package name: tribler
- Latest released version: 8.0.6
- Current version on the unstable channel: 7.14.0
- Current version on the stable/release channel: 7.14.0

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@xvapx
@mkg20001

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ISibboI** [comment]
I tried it myself with [this patch](https://github.com/ISibboI/nixpkgs/commit/009a9e3e02d310a1a6110b2e854922effc5471ca) applied to current stable, but it gives me the following error:

```
$ tribler --help
********************************************************************************
A AttributeError occurred
********************************************************************************
Traceback (most recent call last):
  File "/nix/store/rs1b76w8bb1kwvddk9pgkgik4k2a71dz-tribler-8.0.6/src/run_tribler.py", line 64, in <module>
    from tribler.core.session import Session
  File "/nix/store/rs1b76w8bb1kwvddk9pgkgik4k2a71dz-tribler-8.0.6/src/tribler/core/session.py", line 29, in <module>
    from tribler.core.libtorrent.download_manager.download_manager import DownloadManager
  File "/nix/store/rs1b76w8bb1kwvddk9pgkgik4k2a71dz-tribler-8.0.6/src/tribler/core/libtorrent/download_manager/download_manager.py", line 53, in <module>
    lt.create_ut_metadata_plugin,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'libtorrent' has no attribute 'create_ut_metadata_plugin'

********************************************************************************
Error while showing a message box: [Errno 2] No such file or directory: 'xmessage'
```

**Comment by marek287** [comment]
Latest released version: 8.1.3

**Comment by ISibboI** [comment]
@marek287 if you are able to tell me what's wrong with my patch for 7.0.6 then we can surely also apply that to 7.1.3 🙂
