### ISSUE TITLE
Harlequin fails to start with theme-related error message

### ISSUE THREAD

**Issue by Naxdy** [NixOS/nixpkgs#364867]
## Describe the bug

Harlequin fails to start with theme-related error message:

```
Traceback (most recent call last):
  File "/nix/store/dvaw51k5c8jy6znnhmv134b7l3bgvqkr-harlequin-1.25.2/bin/.harlequin-wrapped", line 9, in <module>
    sys.exit(harlequin())
             ^^^^^^^^^^^
  File "/nix/store/dvaw51k5c8jy6znnhmv134b7l3bgvqkr-harlequin-1.25.2/lib/python3.12/site-packages/harlequin/cli.py", line 414, in harlequin
    cli()
  File "/nix/store/9l7cdymnw9ck7l7hk1d7n6yc2ql3a0j0-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/5l86rgi0bh4qsq9nx02yry49lmqdclb0-python3.12-rich-click-1.8.4/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/9l7cdymnw9ck7l7hk1d7n6yc2ql3a0j0-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9l7cdymnw9ck7l7hk1d7n6yc2ql3a0j0-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9l7cdymnw9ck7l7hk1d7n6yc2ql3a0j0-python3.12-click-8.1.7/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/dvaw51k5c8jy6znnhmv134b7l3bgvqkr-harlequin-1.25.2/lib/python3.12/site-packages/harlequin/cli.py", line 371, in inner_cli
    tui = Harlequin(
          ^^^^^^^^^^
  File "/nix/store/dvaw51k5c8jy6znnhmv134b7l3bgvqkr-harlequin-1.25.2/lib/python3.12/site-packages/harlequin/app.py", line 206, in __init__
    self.theme = theme
    ^^^^^^^^^^
  File "/nix/store/hz7m3hlp8m2drds2m45za58vzk5pqi4y-python3.12-textual-0.86.1/lib/python3.12/site-packages/textual/reactive.py", line 336, in __set__
    self._set(obj, value)
  File "/nix/store/hz7m3hlp8m2drds2m45za58vzk5pqi4y-python3.12-textual-0.86.1/lib/python3.12/site-packages/textual/reactive.py", line 307, in _set
    value = private_validate_function(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hz7m3hlp8m2drds2m45za58vzk5pqi4y-python3.12-textual-0.86.1/lib/python3.12/site-packages/textual/app.py", line 1249, in _validate_theme
    raise InvalidThemeError(message)
textual.app.InvalidThemeError: Theme 'harlequin' has not been registered. Call 'App.register_theme' before setting the 'App.theme' attribute.
```

This also happens when using any other theme name, e.g. `bw`, `default`, `lightbulb`, etc. as per https://pygments.org/styles/

## Steps To Reproduce

1. Launch `harlequin`

## Expected behavior

Application launches and TUI appears, without any error message.

## Notify maintainers

@pcboy 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pcboy** [comment]
Curious indeed, used to work fine, I wonder when it started to break. :thinking: 

I think maybe the `textual` dep got updated at some point, and current harlequin code is breaking with it.

Commit 9f3d02d510042068aee542cf27e66c1dc919e711 was still working fine. It's textual 0.82.0

While current harlequin on master seems to be using textual-0.86.1. Could be the reason.

It started to fail at this commit [f673b779338786f6553c7118ed1703fa6072260e](https://github.com/NixOS/nixpkgs/commit/f673b779338786f6553c7118ed1703fa6072260e)

You can see the `pythonRelaxDeps = [ "textual" ];`, if I remove it, we get:

```
Checking runtime dependencies for harlequin-1.25.2-py3-none-any.whl
  - textual==0.85.0 not satisfied by version 0.86.1
```

So seems like it's likely that harlequin is not compatible with the textual currently in master. Would likely need to be fixed upstream. A patch could also be added. I don't know much about textual. :thinking: 
I use harlequin from time to time so that bother me too. I can potentially give it a deeper look next week.

**Comment by pcboy** [comment]
I asked Harlequin's main dev, and the upgrade to 0.86 is in progress. We will have to wait before we can update (possibly will be fixed early next year). Seems like the changes are significant.

https://github.com/tconbeer/harlequin/discussions/712#discussioncomment-11566744

In the mean time, harlequin can run with:

```bash
nix run github:nixos/nixpkgs/9f3d02d510042068aee542cf27e66c1dc919e711#harlequin
```

**Comment by Naxdy** [comment]
In the meantime, we could also inline textual 0.82.0 for harlequin specifically. Other packages have been doing similar things in the past. [Prusa Slicer](https://github.com/NixOS/nixpkgs/blob/3566ab7246670a43abd2ffa913cc62dad9cdf7d5/pkgs/applications/misc/prusa-slicer/default.nix#L43-L66) comes to mind.

**Comment by pcboy** [comment]
I assumed this was a bit frowned upon. But that's for sure better than a broken package, and as it's temporary that may be okay. 

I created the PR. I have no write access though, so we will see if it gets accepted.

https://github.com/NixOS/nixpkgs/pull/365766
