### ISSUE TITLE
meson: mesonconf broken

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#36492]
## Issue description
```shell-session
$ nix run -f '<nixpkgs>' meson ninja -c mesonconf build
Traceback (most recent call last):
  File "/nix/store/fir23185m103db7ddwjmhnqb2jd7baqa-meson-0.44.0/bin/mesonconf", line 18, in <module>
    from mesonbuild import mesonmain
  File "/nix/store/fir23185m103db7ddwjmhnqb2jd7baqa-meson-0.44.0/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 18, in <module>
    from . import environment, interpreter, mesonlib
  File "/nix/store/fir23185m103db7ddwjmhnqb2jd7baqa-meson-0.44.0/lib/python3.6/site-packages/mesonbuild/environment.py", line 17, in <module>
    from . import coredata
  File "/nix/store/fir23185m103db7ddwjmhnqb2jd7baqa-meson-0.44.0/lib/python3.6/site-packages/mesonbuild/coredata.py", line 20, in <module>
    from .mesonlib import MesonException, commonpath
  File "/nix/store/fir23185m103db7ddwjmhnqb2jd7baqa-meson-0.44.0/lib/python3.6/site-packages/mesonbuild/mesonlib.py", line 60, in <module>
    meson_command = python_command + [detect_meson_py_location()]
  File "/nix/store/fir23185m103db7ddwjmhnqb2jd7baqa-meson-0.44.0/lib/python3.6/site-packages/mesonbuild/mesonlib.py", line 51, in detect_meson_py_location
    raise RuntimeError('Could not determine how to run Meson. Please file a bug with details.')
RuntimeError: Could not determine how to run Meson. Please file a bug with details.
```

Fortunately `meson configure` still works.

## Technical details
Nixpkgs: b19c50cec9dd811b27d6141ecac1ac3b2697b096

**Comment by jtojnar** [comment]
This was removed in 0.48.0
