### ISSUE TITLE
aider-chat crashes on start because of pillow dependency error

### ISSUE THREAD

**Issue by meditans** [NixOS/nixpkgs#364944]
## Describe the bug
When using the version of `aider-chat` currently on unstable `"rev": "dc460ec76cbff0e66e269457d7b728432263166c"`:
```
$ aider
Traceback (most recent call last):
  File "/nix/store/x0vvalzlz5y90iqm7b1mkxdjafzw447q-aider-chat-0.66.0/bin/.aider-wrapped", line 6, in <module>
    from aider.main import main
  File "/nix/store/x0vvalzlz5y90iqm7b1mkxdjafzw447q-aider-chat-0.66.0/lib/python3.11/site-packages/aider/main.py", line 17, in <module>
    from aider import __version__, models, urls, utils
  File "/nix/store/x0vvalzlz5y90iqm7b1mkxdjafzw447q-aider-chat-0.66.0/lib/python3.11/site-packages/aider/models.py", line 14, in <module>
    from PIL import Image
  File "/nix/store/q59yp3fx266n0kx18har1rc7ym6kwz2r-python3-3.12.6-env/lib/python3.12/site-packages/PIL/Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/nix/store/q59yp3fx266n0kx18har1rc7ym6kwz2r-python3-3.12.6-env/lib/python3.12/site-packages/PIL/__init__.py)
```
## Metadata
```
nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.228, NixOS, 25.05 (Warbler), 25.05.20241211.5d67ea6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/rhn4fkh7hqjlqs9j6naaq623qpl62yz0-source`
```
## Notify maintainers
@taha-yassine 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by taha-yassine** [comment]
Can you try again with the current version on unstable?

**Comment by mausch** [comment]
Works for me with a recent unstable:

`nix run github:nixos/nixpkgs/18dd725c29603f582cf1900e0d25f9f1063dbf11#aider-chat`

I think this can be closed now.

**Comment by yzx9** [comment]
Closed as stale and not reproducible. Feel free to reopen if the issue persists.
