### ISSUE TITLE
Build failure: quickgui

### ISSUE THREAD

**Issue by UlyssesZh** [NixOS/nixpkgs#365276]
## Steps To Reproduce

1. build `quickgui`.

## Build log

<details>

<summary>Build Log</summary>

```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/72igdr4x2jvjsv9jrhq1p42837svircm-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Executing dartConfigHook
Setting up SDK
Installing dependencies
Finished dartConfigHook
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
[   +7 ms] Failed obtaining PRETTY_NAME for Linux: PathNotFoundException: Cannot open file, path = '/usr/lib/os-release' (OS Error: No such file or directory, errno = 2)
[  +10 ms] Unable to locate an Android SDK.
[  +89 ms] Skipping pub get: generated by third-party.
[  +50 ms] Found plugin shared_preferences_android at /nix/store/1k96mg6rq0fmjnazrn01wb49d6fw1cq1-pub-shared_preferences_android-2.2.3/
[   +5 ms] Found plugin url_launcher_ios at /nix/store/1vkkkx92yl5aj9s3ii31pdgvh3vfr63w-pub-url_launcher_ios-6.3.0/
[   +3 ms] Found plugin window_size at /nix/store/281pj1qkmwsbzmn02r6q9icaj11x15ab-pub-window_size-0.1.0/plugins/window_size/
[   +4 ms] Found plugin shared_preferences_windows at /nix/store/407k5jmg8izy1cgr19qqwzp1kwdp12jj-pub-shared_preferences_windows-2.3.2/
[  +15 ms] Found plugin shared_preferences at /nix/store/7mjqwqwd0kiyr78hmwampsmyim30h62w-pub-shared_preferences-2.2.3/
[   +1 ms] Found plugin url_launcher at /nix/store/86ia0h0wg611vf5k35d9qgm15ynqiczi-pub-url_launcher-6.3.0/
[   +2 ms] Found plugin url_launcher_android at /nix/store/89gmd7fwz037y4xfajqgmmzjpyvzsqc9-pub-url_launcher_android-6.3.3/
[  +10 ms] Found plugin path_provider_linux at /nix/store/92gyzbddcks109k39v6d458wxzl58lvx-pub-path_provider_linux-2.2.1/
[  +22 ms] Found plugin shared_preferences_linux at /nix/store/d620zvsr5yz4kvm819myx96c5v1qmz89-pub-shared_preferences_linux-2.3.2/
[   +3 ms] Found plugin url_launcher_web at /nix/store/dwypvhxjaf1j4w101v1nndv4jllz2wn4-pub-url_launcher_web-2.3.1/
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at /nix/store/dxhvqiprdm9gagccy9ln75ba2qzjzc17-pub-flutter_plugin_android_lifecycle-2.0.20/
[   +5 ms] Found plugin url_launcher_macos at /nix/store/hi7bk9faqg2l41fbghzkzz56vf2kkcn7-pub-url_launcher_macos-3.2.0/
[   +3 ms] Found plugin path_provider_windows at /nix/store/hslm677j2zn7y9nvjhbqp3hl9sk528rd-pub-path_provider_windows-2.2.1/
[  +10 ms] Found plugin shared_preferences_foundation at /nix/store/jbmpn3i19fvi99462ypg5q1fz2r4ac0z-pub-shared_preferences_foundation-2.4.0/
[  +27 ms] Found plugin shared_preferences_web at /nix/store/rcaj2ii6fq3vsz4xrbf4y8yk72q1snda-pub-shared_preferences_web-2.3.0/
[   +2 ms] Found plugin package_info_plus at /nix/store/rl1wlkicwvmhs3h9vzgxw224icjyypbf-pub-package_info_plus-8.0.0/
[   +4 ms] Found plugin url_launcher_windows at /nix/store/w6dgildw2069q5bbh1xbx9fv21q28sn8-pub-url_launcher_windows-3.1.1/
[   +4 ms] Found plugin url_launcher_linux at /nix/store/xjlblszjzp3vvcmrxfy9p9vsa4sjwgq2-pub-url_launcher_linux-3.1.1/
[   +4 ms] Found plugin file_picker at /nix/store/z7x8ccaqsz25shj9dv9dw9wnas8qd5bv-file_picker-8.0.6/
[  +35 ms] Found plugin shared_preferences_android at /nix/store/1k96mg6rq0fmjnazrn01wb49d6fw1cq1-pub-shared_preferences_android-2.2.3/
[        ] Found plugin url_launcher_ios at /nix/store/1vkkkx92yl5aj9s3ii31pdgvh3vfr63w-pub-url_launcher_ios-6.3.0/
[   +1 ms] Found plugin window_size at /nix/store/281pj1qkmwsbzmn02r6q9icaj11x15ab-pub-window_size-0.1.0/plugins/window_size/
[   +1 ms] Found plugin shared_preferences_windows at /nix/store/407k5jmg8izy1cgr19qqwzp1kwdp12jj-pub-shared_preferences_windows-2.3.2/
[   +8 ms] Found plugin shared_preferences at /nix/store/7mjqwqwd0kiyr78hmwampsmyim30h62w-pub-shared_preferences-2.2.3/
[   +1 ms] Found plugin url_launcher at /nix/store/86ia0h0wg611vf5k35d9qgm15ynqiczi-pub-url_launcher-6.3.0/
[   +1 ms] Found plugin url_launcher_android at /nix/store/89gmd7fwz037y4xfajqgmmzjpyvzsqc9-pub-url_launcher_android-6.3.3/
[   +3 ms] Found plugin path_provider_linux at /nix/store/92gyzbddcks109k39v6d458wxzl58lvx-pub-path_provider_linux-2.2.1/
[   +8 ms] Found plugin shared_preferences_linux at /nix/store/d620zvsr5yz4kvm819myx96c5v1qmz89-pub-shared_preferences_linux-2.3.2/
[   +1 ms] Found plugin url_launcher_web at /nix/store/dwypvhxjaf1j4w101v1nndv4jllz2wn4-pub-url_launcher_web-2.3.1/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at /nix/store/dxhvqiprdm9gagccy9ln75ba2qzjzc17-pub-flutter_plugin_android_lifecycle-2.0.20/
[   +3 ms] Found plugin url_launcher_macos at /nix/store/hi7bk9faqg2l41fbghzkzz56vf2kkcn7-pub-url_launcher_macos-3.2.0/
[   +1 ms] Found plugin path_provider_windows at /nix/store/hslm677j2zn7y9nvjhbqp3hl9sk528rd-pub-path_provider_windows-2.2.1/
[   +2 ms] Found plugin shared_preferences_foundation at /nix/store/jbmpn3i19fvi99462ypg5q1fz2r4ac0z-pub-shared_preferences_foundation-2.4.0/
[  +16 ms] Found plugin shared_preferences_web at /nix/store/rcaj2ii6fq3vsz4xrbf4y8yk72q1snda-pub-shared_preferences_web-2.3.0/
[   +1 ms] Found plugin package_info_plus at /nix/store/rl1wlkicwvmhs3h9vzgxw224icjyypbf-pub-package_info_plus-8.0.0/
[   +2 ms] Found plugin url_launcher_windows at /nix/store/w6dgildw2069q5bbh1xbx9fv21q28sn8-pub-url_launcher_windows-3.1.1/
[   +2 ms] Found plugin url_launcher_linux at /nix/store/xjlblszjzp3vvcmrxfy9p9vsa4sjwgq2-pub-url_launcher_linux-3.1.1/
[   +3 ms] Found plugin file_picker at /nix/store/z7x8ccaqsz25shj9dv9dw9wnas8qd5bv-file_picker-8.0.6/
[  +45 ms] [1mBuilding Linux application...[22m
[   +4 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64 /build/source/linux
[[1m +418 ms[22m] -- The CXX compiler identification is Clang 18.1.8
[  +43 ms] -- Detecting CXX compiler ABI info
[[1m +218 ms[22m] -- Detecting CXX compiler ABI info - done
[  +51 ms] -- Check for working CXX compiler: /nix/store/03bq5hc45d5wkw8pajmz4vgd5s0ivyq8-clang-wrapper-18.1.8/bin/clang++ - skipped
[   +7 ms] -- Detecting CXX compile features
[   +1 ms] -- Detecting CXX compile features - done
[   +6 ms] -- Found PkgConfig: /nix/store/16h31npnbgpkhxp1041dsifiklbw4mpr-pkg-config-wrapper-0.29.2/bin/pkg-config (found version "0.29.2")
[        ] -- Checking for module 'gtk+-3.0'
[  +66 ms] --   Found gtk+-3.0, version 3.24.43
[[1m +255 ms[22m] -- Checking for module 'glib-2.0'
[  +24 ms] --   Found glib-2.0, version 2.82.1
[  +57 ms] -- Checking for module 'gio-2.0'
[  +24 ms] --   Found gio-2.0, version 2.82.1
[  +93 ms] -- Configuring done (1.3s)
[  +28 ms] -- Generating done (0.0s)
[        ] -- Build files have been written to: /build/source/build/linux/x64/release
[   +8 ms] executing: ninja -C build/linux/x64/release install
[  +10 ms] ninja: Entering directory `build/linux/x64/release'
[[1m+9828 ms[22m] [1/10] Generating /build/source/linux/flutter/ephemeral/libflutter_linux_gtk.so, /build/source/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_value.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_view.h, /build/source/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +2 ms] FAILED: /build/source/linux/flutter/ephemeral/libflutter_linux_gtk.so /build/source/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_engine.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_call.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_response.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_value.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_view.h /build/source/linux/flutter/ephemeral/flutter_linux/flutter_linux.h flutter/_phony_ /build/source/build/linux/x64/release/flutter/_phony_ 
[        ] cd /build/source/build/linux/x64/release/flutter && /nix/store/4k2h9qsps52n1v56zq03yi67dwmxa81i-cmake-3.30.5/bin/cmake -E env FLUTTER_ROOT=/nix/store/0bkyzdkk762bxs70rlgygpljmg2dl5l3-flutter-wrapped-3.24.4-sdk-links PROJECT_DIR=/build/source DART_OBFUSCATION=false SPLIT_DEBUG_INFO=/nix/store/mpiz8qz50d7zfac9747yykv9rb5yz8q6-quickgui-1.2.10-debug TRACK_WIDGET_CREATION=true TREE_SHAKE_ICONS=true PACKAGE_CONFIG=/build/source/.dart_tool/package_config.json FLUTTER_TARGET=lib/main.dart /nix/store/0bkyzdkk762bxs70rlgygpljmg2dl5l3-flutter-wrapped-3.24.4-sdk-links/packages/flutter_tools/bin/tool_backend.sh linux-x64 Release
[31m[        ] [1m[   +7 ms] Failed obtaining PRETTY_NAME for Linux: PathNotFoundException: Cannot open file, path = '/usr/lib/os-release' (OS Error: No such file or directory, errno = 2)[22m[39m
[   +1 ms] [  +10 ms] Unable to locate an Android SDK.
[        ] [  +96 ms] Initializing file store
[        ] [  +14 ms] Skipping target: gen_localizations
[        ] [   +3 ms] invalidated build due to missing files: /build/source/.dart_tool/package_config_subset
[        ] [   +1 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputMissing: The following inputs were missing: /build/source/.dart_tool/package_config_subset}
[        ] [   +4 ms] unpack_linux: Starting due to {}
[        ] [  +69 ms] unpack_linux: Complete
[        ] [ +159 ms] Found plugin shared_preferences_android at /nix/store/1k96mg6rq0fmjnazrn01wb49d6fw1cq1-pub-shared_preferences_android-2.2.3/
[        ] [   +3 ms] Found plugin url_launcher_ios at /nix/store/1vkkkx92yl5aj9s3ii31pdgvh3vfr63w-pub-url_launcher_ios-6.3.0/
[        ] [   +3 ms] Found plugin window_size at /nix/store/281pj1qkmwsbzmn02r6q9icaj11x15ab-pub-window_size-0.1.0/plugins/window_size/
[        ] [   +4 ms] Found plugin shared_preferences_windows at /nix/store/407k5jmg8izy1cgr19qqwzp1kwdp12jj-pub-shared_preferences_windows-2.3.2/
[        ] [  +13 ms] Found plugin shared_preferences at /nix/store/7mjqwqwd0kiyr78hmwampsmyim30h62w-pub-shared_preferences-2.2.3/
[        ] [   +1 ms] Found plugin url_launcher at /nix/store/86ia0h0wg611vf5k35d9qgm15ynqiczi-pub-url_launcher-6.3.0/
[        ] [   +2 ms] Found plugin url_launcher_android at /nix/store/89gmd7fwz037y4xfajqgmmzjpyvzsqc9-pub-url_launcher_android-6.3.3/
[        ] [   +5 ms] Found plugin path_provider_linux at /nix/store/92gyzbddcks109k39v6d458wxzl58lvx-pub-path_provider_linux-2.2.1/
[        ] [  +15 ms] Found plugin shared_preferences_linux at /nix/store/d620zvsr5yz4kvm819myx96c5v1qmz89-pub-shared_preferences_linux-2.3.2/
[        ] [   +5 ms] Found plugin url_launcher_web at /nix/store/dwypvhxjaf1j4w101v1nndv4jllz2wn4-pub-url_launcher_web-2.3.1/
[        ] [   +2 ms] Found plugin flutter_plugin_android_lifecycle at /nix/store/dxhvqiprdm9gagccy9ln75ba2qzjzc17-pub-flutter_plugin_android_lifecycle-2.0.20/
[        ] [   +4 ms] Found plugin url_launcher_macos at /nix/store/hi7bk9faqg2l41fbghzkzz56vf2kkcn7-pub-url_launcher_macos-3.2.0/
[        ] [   +2 ms] Found plugin path_provider_windows at /nix/store/hslm677j2zn7y9nvjhbqp3hl9sk528rd-pub-path_provider_windows-2.2.1/
[        ] [   +3 ms] Found plugin shared_preferences_foundation at /nix/store/jbmpn3i19fvi99462ypg5q1fz2r4ac0z-pub-shared_preferences_foundation-2.4.0/
[        ] [  +24 ms] Found plugin shared_preferences_web at /nix/store/rcaj2ii6fq3vsz4xrbf4y8yk72q1snda-pub-shared_preferences_web-2.3.0/
[        ] [   +1 ms] Found plugin package_info_plus at /nix/store/rl1wlkicwvmhs3h9vzgxw224icjyypbf-pub-package_info_plus-8.0.0/
[        ] [   +3 ms] Found plugin url_launcher_windows at /nix/store/w6dgildw2069q5bbh1xbx9fv21q28sn8-pub-url_launcher_windows-3.1.1/
[        ] [   +4 ms] Found plugin url_launcher_linux at /nix/store/xjlblszjzp3vvcmrxfy9p9vsa4sjwgq2-pub-url_launcher_linux-3.1.1/
[        ] [   +4 ms] Found plugin file_picker at /nix/store/z7x8ccaqsz25shj9dv9dw9wnas8qd5bv-file_picker-8.0.6/
[        ] [  +28 ms] gen_dart_plugin_registrant: Complete
[        ] [        ] kernel_snapshot_program: Starting due to {}
[   +1 ms] [   +8 ms] /nix/store/0bkyzdkk762bxs70rlgygpljmg2dl5l3-flutter-wrapped-3.24.4-sdk-links/bin/cache/dart-sdk/bin/dartaotruntime --disable-dart-dev /nix/store/0bkyzdkk762bxs70rlgygpljmg2dl5l3-flutter-wrapped-3.24.4-sdk-links/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root /nix/store/0bkyzdkk762bxs70rlgygpljmg2dl5l3-flutter-wrapped-3.24.4-sdk-links/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --delete-tostring-package-uri=dart:ui --delete-tostring-package-uri=package:flutter --aot --tfa --target-os linux --packages /build/source/.dart_tool/package_config.json --output-dill /build/source/.dart_tool/flutter_build/e37e87eb83d36008b5cd86f30ae5344d/program.dill --depfile /build/source/.dart_tool/flutter_build/e37e87eb83d36008b5cd86f30ae5344d/kernel_snapshot_program.d --source file:///build/source/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///build/source/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error package:quickgui/main.dart
[31m[        ] [1m[+3030 ms] /nix/store/27l1g0jj6q7id108d8pac5wr18d5j31b-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1915:39: Error: Method not found: 'SchemeRainbow'.[22m[39m
[        ] [   +1 ms]       DynamicSchemeVariant.rainbow => SchemeRainbow(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
[        ] [        ]                                       ^^^^^^^^^^^^^
[31m[        ] [1m[        ] /nix/store/27l1g0jj6q7id108d8pac5wr18d5j31b-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1916:42: Error: Method not found: 'SchemeFruitSalad'.[22m[39m
[        ] [        ]       DynamicSchemeVariant.fruitSalad => SchemeFruitSalad(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
[        ] [        ]                                          ^^^^^^^^^^^^^^^^
[        ] [+5959 ms] Persisting file store
[        ] [   +2 ms] Done persisting file store
[        ] [   +1 ms] Target kernel_snapshot_program failed: Exception
[        ]            #0      KernelSnapshotProgram.build (package:flutter_tools/src/build_system/targets/common.dart:276:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
[        ]            <asynchronous suspension>
[        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
[        ]            <asynchronous suspension>
[        ]            #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
[        ]            <asynchronous suspension>
[        ]            #8      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
[        ]            <asynchronous suspension>
[   +1 ms]            #9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
[        ]            <asynchronous suspension>
[        ]            #10     Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
[        ]            <asynchronous suspension>
[        ]            #11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
[        ]            <asynchronous suspension>
[        ]            #12     Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
[        ]            <asynchronous suspension>
[        ]            #13     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
[        ]            <asynchronous suspension>
[        ]            #14     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
[        ]            <asynchronous suspension>
[   +2 ms]            #15     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:328:32)
[        ]            <asynchronous suspension>
[        ]            #16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
[        ]            <asynchronous suspension>
[        ]            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #18     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:9)
[        ]            <asynchronous suspension>
[        ]            #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
[        ]            <asynchronous suspension>
[        ]            #22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
[        ]            <asynchronous suspension>
[        ]            #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #24     main (package:flutter_tools/executable.dart:93:3)
[        ]            <asynchronous suspension>
[        ] [   +6 ms] "flutter assemble" took 9,455ms.
[        ] [   +2 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:345:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:93:3)
[        ]            <asynchronous suspension>
[        ] [        ] Running 1 shutdown hook
[        ] [        ] Shutdown hooks complete
[        ] [   +2 ms] exiting with code 1
[        ] ninja: build stopped: subcommand failed.
[   +8 ms] Building Linux application... (completed in 11.2s)
[        ] "flutter linux" took 11,562ms.
[31m[   +2 ms] [1mBuild process failed[22m[39m
[31m[        ] [1m[22m[39m
[31m[1m           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)[22m[39m
[31m[1m           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:210:5)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:83:5)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:87:5)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:9)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #12     main (package:flutter_tools/executable.dart:93:3)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           [22m[39m
[31m[1m           [22m[39m
[   +1 ms] Running 1 shutdown hook
[        ] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

</details>

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.64, NixOS, 24.05 (Uakari), 24.05.7101.64e9404f308e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

@flexiondotorg @heyimnova 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by UlyssesZh** [comment]
Duplicate of #341893.

Sorry, but that issue didn't pop up in front when I searched it. I should've searched with `label:"0.kind: build failure"` filter.
