### ISSUE TITLE
AD-miner: 1.6.1, 1.7.0 always fails to render report with permission denied errors

### ISSUE THREAD

**Issue by AkechiShiro** [NixOS/nixpkgs#365638]
## Describe the bug
Running the tool leads to permission denied no matter where it is run.

I believe this is due to the fact that it seems to be copying the file from the store and is preserving some of the rights on them.

## Steps To Reproduce

1. `nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz -p ad-miner` or `nix-shell -p ad-miner`
2. export `NEO4J_HOME=/tmp/` 
3. Run `nix-shell -p neo4j --run 'neo4j start'`
4. cd `/tmp` which is world writeable
5. Run `AD-miner -c -cf myReport -u $USER -p $PASSWD`

Even by trying to `chmod u+rw -R render_myReport/`  the folder (and all subfolders), relaunching the script changes back the permissions to the wrong ones.

## Expected behavior

Permission needs to be changed after files are copied by the tool, I think the tool needs an additional patch to work maybe on `shutil.copy2` or `copyfile` functions in the source code (I may try to submit a fix/PR if I can find time to)

## Additional context

All files timestamp are those from the store and the permission are probably too.

```
.r--r--r-- <username> users 4.1 MB Thu Jan  1 01:00:01 1970
```
Traceback : 
```py
Traceback (most recent call last):
  File "/nix/store/mh57g5n5hjdnn06vxxwnxxi36y64n98n-ad-miner-1.7.0/bin/.AD-miner-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/mh57g5n5hjdnn06vxxwnxxi36y64n98n-ad-miner-1.7.0/lib/python3.12/site-packages/ad_miner/__main__.py", line 164, in main
    prepare_render(arguments)
  File "/nix/store/mh57g5n5hjdnn06vxxwnxxi36y64n98n-ad-miner-1.7.0/lib/python3.12/site-packages/ad_miner/__main__.py", line 142, in prepare_render
    shutil.copy2(js_file, folder_name / "js")
  File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/shutil.py", line 475, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'render_myReport/js/main_circle.js'
```

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 24.05 (Uakari), 24.05.7139.bcba2fbf6963`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers
@fabaff 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AkechiShiro** [comment]
I've managed to do a fix but I believe it's a bit dirty, I also saw that neo4j should be pinned, it seems that the results are not showing up despite the permission error being workaround for now :
``` 
[+] Your neo4j database uses neo4j version 5.19.0
[!] Your neo4j database version must be 4.4.X in order to fully use AD Miner
```
