### ISSUE TITLE
Build failure: esphome

### ISSUE THREAD

**Issue by Kernald** [NixOS/nixpkgs#365717]
## Steps To Reproduce

1. build *esphome* (on `nixos-24.11`)

## Build log

<details>

<summary>Build Log</summary>

```
# ...
adding 'esphome/dashboard/status/__init__.py'
adding 'esphome/dashboard/status/mdns.py'
adding 'esphome/dashboard/status/mqtt.py'
adding 'esphome/dashboard/status/ping.py'
adding 'esphome/dashboard/util/__init__.py'
adding 'esphome/dashboard/util/file.py'
adding 'esphome/dashboard/util/itertools.py'
adding 'esphome/dashboard/util/password.py'
adding 'esphome/dashboard/util/subprocess.py'
adding 'esphome/dashboard/util/text.py'
adding 'esphome-2024.11.3.dist-info/LICENSE'
adding 'esphome-2024.11.3.dist-info/METADATA'
adding 'esphome-2024.11.3.dist-info/WHEEL'
adding 'esphome-2024.11.3.dist-info/entry_points.txt'
adding 'esphome-2024.11.3.dist-info/top_level.txt'
adding 'esphome-2024.11.3.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
[1m[92mSuccessfully built [4mesphome-2024.11.3-py3-none-any.whl[0m[1m[92m[0m
Finished creating a wheel...
/build/source/dist /build/source
Unpacking to: unpacked/esphome-2024.11.3...OK
Repacking wheel as ./esphome-2024.11.3-py3-none-any.whl...OK
/build/source
Finished executing pypaBuildPhase
Running phase: pythonRuntimeDepsCheckHook
@nix { "action": "setPhase", "phase": "pythonRuntimeDepsCheckHook" }
Executing pythonRuntimeDepsCheck
Checking runtime dependencies for esphome-2024.11.3-py3-none-any.whl
Finished executing pythonRuntimeDepsCheck
Running phase: glibPreInstallPhase
@nix { "action": "setPhase", "phase": "glibPreInstallPhase" }
Running phase: glibPreInstallPhase
@nix { "action": "setPhase", "phase": "glibPreInstallPhase" }
Running phase: installPhase
@nix { "action": "setPhase", "phase": "installPhase" }
Executing pypaInstallPhase
Successfully installed esphome-2024.11.3-py3-none-any.whl
Finished executing pypaInstallPhase
Running phase: pythonOutputDistPhase
@nix { "action": "setPhase", "phase": "pythonOutputDistPhase" }
Executing pythonOutputDistPhase
Finished executing pythonOutputDistPhase
Running phase: glibPreFixupPhase
@nix { "action": "setPhase", "phase": "glibPreFixupPhase" }
Running phase: glibPreFixupPhase
@nix { "action": "setPhase", "phase": "glibPreFixupPhase" }
Running phase: fixupPhase
@nix { "action": "setPhase", "phase": "fixupPhase" }
shrinking RPATHs of ELF executables and libraries in /nix/store/2y5zabc9pibly8wrv16rlqb26zy6p99i-esphome-2024.11.3
checking for references to /build/ in /nix/store/2y5zabc9pibly8wrv16rlqb26zy6p99i-esphome-2024.11.3...
patching script interpreter paths in /nix/store/2y5zabc9pibly8wrv16rlqb26zy6p99i-esphome-2024.11.3
stripping (with command strip and flags -S -p) in  /nix/store/2y5zabc9pibly8wrv16rlqb26zy6p99i-esphome-2024.11.3/lib /nix/store/2y5zabc9pibly8wrv16rlqb26zy6p99i-esphome-2024.11.3/bin
shrinking RPATHs of ELF executables and libraries in /nix/store/sjfd46wk1g25b1rc18524aqdfab6m6d6-esphome-2024.11.3-dist
checking for references to /build/ in /nix/store/sjfd46wk1g25b1rc18524aqdfab6m6d6-esphome-2024.11.3-dist...
patching script interpreter paths in /nix/store/sjfd46wk1g25b1rc18524aqdfab6m6d6-esphome-2024.11.3-dist
Rewriting #!/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/bin/python3.12 to #!/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7
wrapping `/nix/store/2y5zabc9pibly8wrv16rlqb26zy6p99i-esphome-2024.11.3/bin/esphome'...
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
Running phase: installCheckPhase
@nix { "action": "setPhase", "phase": "installCheckPhase" }
no Makefile or custom installCheckPhase, doing nothing
Running phase: pythonCatchConflictsPhase
@nix { "action": "setPhase", "phase": "pythonCatchConflictsPhase" }
Running phase: pythonRemoveBinBytecodePhase
@nix { "action": "setPhase", "phase": "pythonRemoveBinBytecodePhase" }
Running phase: pythonImportsCheckPhase
@nix { "action": "setPhase", "phase": "pythonImportsCheckPhase" }
Executing pythonImportsCheckPhase
Running phase: pytestCheckPhase
@nix { "action": "setPhase", "phase": "pytestCheckPhase" }
Executing pytestCheckPhase
[1m============================= test session starts ==============================[0m
platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
rootdir: /build/source
configfile: pyproject.toml
testpaths: tests
plugins: hypothesis-6.112.2, asyncio-0.23.8, cov-nixpkgs-stub-1.0.0, mock-3.14.0
asyncio: mode=Mode.STRICT
[1mcollecting ... [0m[1m
collecting 36 items                                                            [0m[1m
collecting 337 items                                                           [0m[1m
collected 481 items                                                            [0m

tests/component_tests/binary_sensor/test_binary_sensor.py [32m.[0m[32m.[0m[32m.[0m[32m            [  0%][0m
tests/component_tests/button/test_button.py [32m.[0m[32m.[0m[32m.[0m[32m                          [  1%][0m
tests/component_tests/deep_sleep/test_deep_sleep.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m                 [  2%][0m
tests/component_tests/packages/test_packages.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m           [  4%][0m
tests/component_tests/sensor/test_sensor.py [32m.[0m[32m                            [  5%][0m
tests/component_tests/text/test_text.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m                            [  6%][0m
tests/component_tests/text_sensor/test_text_sensor.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m               [  7%][0m
tests/dashboard/test_web_server.py [32m.[0m[31mF[0m[31m                                    [  7%][0m
tests/dashboard/util/test_file.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                   [  8%][0m
tests/unit_tests/test_codegen.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m [ 16%]
[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                                   [ 20%][0m
tests/unit_tests/test_config_validation.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m [ 27%]
[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                                [ 32%][0m
tests/unit_tests/test_core.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m [ 40%]
[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m [ 55%]
[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m            [ 68%][0m
tests/unit_tests/test_cpp_generator.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m [ 75%]
[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                             [ 81%][0m
tests/unit_tests/test_cpp_helpers.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                [ 82%][0m
tests/unit_tests/test_helpers.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m [ 90%]
[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                                    [ 94%][0m
tests/unit_tests/test_wizard.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                   [ 99%][0m
tests/unit_tests/test_yaml_util.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                  [100%][0m

=================================== FAILURES ===================================
[31m[1m______________________________ test_devices_page _______________________________[0m

dashboard = <dashboard.test_web_server.DashboardTestHelper object at 0x7ffff498b0e0>

    @pytest.mark.asyncio
    async def test_devices_page(dashboard: DashboardTestHelper) -> None:
        response = await dashboard.fetch("/devices")
        assert response.code == 200
        assert response.headers["content-type"] == "application/json"
        json_data = json.loads(response.body.decode())
        configured_devices = json_data["configured"]
>       first_device = configured_devices[0]
[1m[31mE       IndexError: list index out of range[0m

[1m[31mtests/dashboard/test_web_server.py[0m:78: IndexError
---------------------------- Captured log teardown -----------------------------
[31m[1mERROR   [0m asyncio:base_events.py:1820 Task was destroyed but it is pending!
task: <Task pending name='Task-18' coro=<AsyncEngine._async_setup() running at /nix/store/6gjjymnl5v496a6i9s4iay3d7qbb1p50-python3.12-zeroconf-0.136.0/lib/python3.12/site-packages/zeroconf/_engine.py:88> wait_for=<Future finished result=None>>
[31m[1mERROR   [0m asyncio:base_events.py:1820 Task was destroyed but it is pending!
task: <Task cancelling name='Task-12' coro=<ESPHomeDashboard.async_run() running at /build/source/esphome/dashboard/core.py:168>>
[33m=============================== warnings summary ===============================[0m
tests/dashboard/test_web_server.py::test_devices_page
  /nix/store/ziygfgrrfki93xcr567isy6j2431qp7i-python3.12-pytest-8.3.3/lib/python3.12/site-packages/_pytest/unraisableexception.py:85: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7ffff49736b0>
  
  Traceback (most recent call last):
    File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/asyncio/base_events.py", line 1439, in create_datagram_endpoint
      await waiter
  GeneratorExit
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/nix/store/6gjjymnl5v496a6i9s4iay3d7qbb1p50-python3.12-zeroconf-0.136.0/lib/python3.12/site-packages/zeroconf/_engine.py", line 88, in _async_setup
      await self._async_create_endpoints()
    File "/nix/store/6gjjymnl5v496a6i9s4iay3d7qbb1p50-python3.12-zeroconf-0.136.0/lib/python3.12/site-packages/zeroconf/_engine.py", line 108, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(  # type: ignore[type-var]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/asyncio/base_events.py", line 1441, in create_datagram_endpoint
      transport.close()
    File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/asyncio/selector_events.py", line 875, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
      self._check_closed()
    File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
[36m[1m=========================== short test summary info ============================[0m
[31mFAILED[0m tests/dashboard/test_web_server.py::[1mtest_devices_page[0m - IndexError: list index out of range
[31m=================== [31m[1m1 failed[0m, [32m480 passed[0m, [33m1 warning[0m[31m in 3.41s[0m[31m ===================[0m

```

</details>

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 24.11 (Vicuna), 24.11.20241213.314e12b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/0xbni69flk8380w0apw4h640n37wn1i9-source`

## Notify maintainers

@globin @mweinelt 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
Cannot reproduce on 01b0f13c394038a267a4b54e4c63c0eaf07dc761.

**Comment by mweinelt** [comment]
And master tests also fine with 2024.11.3

```
esphome> Executing pytestCheckPhase
esphome> ============================= test session starts ==============================
esphome> platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
esphome> rootdir: /build/source
esphome> configfile: pyproject.toml
esphome> testpaths: tests
esphome> plugins: hypothesis-6.112.2, asyncio-0.23.8, cov-nixpkgs-stub-1.0.0, mock-3.14.0
esphome> asyncio: mode=Mode.STRICT
esphome> collected 481 items                                                            
esphome> 
esphome> tests/component_tests/binary_sensor/test_binary_sensor.py ...            [  0%]
esphome> tests/component_tests/button/test_button.py ...                          [  1%]
esphome> tests/component_tests/deep_sleep/test_deep_sleep.py ....                 [  2%]
esphome> tests/component_tests/packages/test_packages.py ..............           [  4%]
esphome> tests/component_tests/sensor/test_sensor.py .                            [  5%]
esphome> tests/component_tests/text/test_text.py .....                            [  6%]
esphome> tests/component_tests/text_sensor/test_text_sensor.py ....               [  7%]
esphome> tests/dashboard/test_web_server.py ..                                    [  7%]
esphome> tests/dashboard/util/test_file.py ....                                   [  8%]
esphome> tests/unit_tests/test_codegen.py ....................................... [ 16%]
esphome> ......................                                                   [ 20%]
esphome> tests/unit_tests/test_config_validation.py ............................. [ 27%]
esphome> .........................                                                [ 32%]
esphome> tests/unit_tests/test_core.py .......................................... [ 40%]
esphome> ........................................................................ [ 55%]
esphome> .............................................................            [ 68%]
esphome> tests/unit_tests/test_cpp_generator.py ................................. [ 75%]
esphome> ............................                                             [ 81%]
esphome> tests/unit_tests/test_cpp_helpers.py ....                                [ 82%]
esphome> tests/unit_tests/test_helpers.py ....................................... [ 90%]
esphome> .....................                                                    [ 94%]
esphome> tests/unit_tests/test_wizard.py ......................                   [ 99%]
esphome> tests/unit_tests/test_yaml_util.py ....                                  [100%]
esphome> 
esphome> ============================= 481 passed in 7.56s ==============================
esphome> Finished executing pytestCheckPhase
esphome> Running phase: pytestcachePhase
esphome> Running phase: pytestRemoveBytecodePhase

**Comment by Kernald** [comment]
Sorry, I forgot I had an override for esphome to track `nixpkgs-unstable` instead. It seems to be fixed now though.

**Comment by nagisa** [comment]
It does still fail on nixpkgs-unstable with the reported failure:

```
$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/d3c42f187194c26d9f0309a8ecc469d6c878ce33.tar.gz -p esphome
```

**Comment by mweinelt** [comment]
Master has 2024.12.1 now. Please retry.

**Comment by mweinelt** [comment]
> `$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/d3c42f187194c26d9f0309a8ecc469d6c878ce33.tar.gz -p esphome`

Builds fine for me as well.
