### ISSUE TITLE
framework-tool: /dev/cros_ec not found error for most commands

### ISSUE THREAD

**Issue by me-and** [NixOS/nixpkgs#365709]
## Describe the bug

The `framework_tool` binary in `pkgs.framework-tool` produces "No such file or directory" errors when I try to run some commands.

## Steps To Reproduce

This is all on a Framework 16 laptop running NixOS 24.11:

Working fine:

```
$ sudo nix-shell -p framework-tool --run 'framework_tool --info'
BIOS Information
  Vendor:       INSYDE Corp.
  Version:      03.03
  Release Date: 03/27/2024
System Information
  Version:      MassProduction (AJ)
  Manufacturer: Framework
  Product Name: Laptop 16 (AMD Ryzen 7040 Series)
  Wake-Up-Type: PowerSwitch
  SKU Number:   FRAGAACP0J
  Family:       16in Laptop
```

Error example:

```
$ sudo nix-shell -p framework-tool --run 'framework_tool --thermal'
Failed to open /dev/cros_ec. Because: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread 'main' panicked at framework_lib/src/chromium_ec/cros_ec.rs:70:34:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Error example with full trace:

```
$ sudo nix-shell -p framework-tool --run 'RUST_BACKTRACE=full framework_tool --test'
Self-Test
  SMBIOS Platform:     Framework16
  Dump EC memory region
Failed to open /dev/cros_ec. Because: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread 'main' panicked at framework_lib/src/chromium_ec/cros_ec.rs:70:34:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x562494625689 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h9754a6437f1de22a
   1:     0x56249451f6fb - core::fmt::write::hb706a393bb60a06f
   2:     0x56249462743e - std::io::Write::write_fmt::h9b447dc5d824d0bd
   3:     0x562494650ecb - std::panicking::default_hook::{{closure}}::h227952daede9dd84
   4:     0x5624946519c1 - std::panicking::rust_panic_with_hook::h76d2aa694a00748e
   5:     0x562494625be2 - std::panicking::begin_panic_handler::{{closure}}::h8855a344ffa1638b
   6:     0x562494625b79 - std::sys::backtrace::__rust_end_short_backtrace::h3110d0cbfbf26886
   7:     0x5624946510f4 - rust_begin_unwind
   8:     0x562494497102 - core::panicking::panic_fmt::h3af706d0346c1c60
   9:     0x5624944970cb - core::panicking::panic::h8fa9c73fac331fdb
  10:     0x562494497088 - core::option::unwrap_failed::had2d05111e3e145c
  11:     0x562494551c53 - <framework_lib::chromium_ec::CrosEc as framework_lib::chromium_ec::CrosEcDriver>::read_memory::h06e6c8348125f499
  12:     0x562494535703 - framework_lib::commandline::selftest::hdf7a551c116d5c17
  13:     0x56249453272a - framework_lib::commandline::run_with_args::habad4b845a6122d8
  14:     0x56249449fc79 - framework_tool::main::h6126cbc5ccf049e3
  15:     0x56249449dc83 - std::sys::backtrace::__rust_begin_short_backtrace::h784e3ffc980074fc
  16:     0x5624944a1049 - main
  17:     0x7f8caf09827e - __libc_start_call_main
  18:     0x7f8caf098339 - __libc_start_main_alias_2
  19:     0x56249449dbb5 - _start
  20:                0x0 - <unknown>
```

## Expected behavior

No errors, `--thermal` displays system thermal information, `--power` displays status of the power supply and battery, etc.

## Additional context

I've also tried updating to the latest upstream release of this tool, per https://github.com/NixOS/nixpkgs/commit/4a865ab6e3a547711d8cbeaae222d6fbe59588df, but see the same behaviour there. 

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 24.11 (Vicuna), 24.11.710486.4dc2fc4e62db`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"home-manager-24.11.tar.gz, nixos-24.11, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

@NickCao @leona-ya @kloenk 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by me-and** [comment]
Upstream bug report, which I note seems to have a disproportionate number of NixOS users reporting the same behaviour: FrameworkComputer/framework-system#43

**Comment by me-and** [comment]
Adding `boot.kernelPackages = pkgs.linuxKernel.packages.linux_6_11;` to my NixOS configuration seems to get this working again; I'm not sure if there's any good way to note a package is only compatible with certain kernel versions. At the very least, maybe it would be sensible to wrap the executable with a script that checks the kernel version?

**Comment by NickCao** [comment]
> Upstream bug report, which I note seems to have a disproportionate number of NixOS users reporting the same behaviour: [FrameworkComputer/framework-system#43](https://github.com/FrameworkComputer/framework-system/issues/43)

Likely due to us using LTS kernel by default.

**Comment by NickCao** [comment]
> I'm not sure if there's any good way to note a package is only compatible with certain kernel versions

It would only be possible if it's installed via a nixos module.

> At the very least, maybe it would be sensible to wrap the executable with a script that checks the kernel version?

Or simpler: just leave this issue open until we default to the new LTS kernel (6.12).

**Comment by me-and** [comment]
I've not checked explicitly, but given the discussion above it seems very likely this is now resolved.
