### ISSUE TITLE
linux: updateScript: use upstream declarations and website generation scripts rather than parsing the website

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#365900]
## Issue description

Currently, the kernel updates script parses the kernel.org website to figure out which releases are supported and which is the newest version for each.
 
I had a look at how that website is generated and it appears it's [this script](https://git.kernel.org/pub/scm/docs/kernel/website.git/tree/plugins/releases.py?id=e6083565a79c3d711c1a76d9312b8c00e06b826b) which uses [this python config file](https://git.kernel.org/pub/scm/docs/kernel/website.git/tree/pelicanconf.py?id=e6083565a79c3d711c1a76d9312b8c00e06b826b) as its ground truth.

The upstream script looks well engineered at a glance and likely could be used for our purposes without requiring any upstream changes but I didn't look too closely.

The current script seems to be working just fine, so there isn't any urgent need to change it but IMHO this would make for a much better API than parsing the HTML which this script generates and it's python on both ends too.

cc @K900 @alyssais @TredwellGit @Ma27 @NeQuissimus

**Comment by Ma27** [comment]
I think this would imply a very specific directory structure with kernel checkouts in it. While every member of the kernel team has probably at least one checkout lying around, this would make it harder for other people to use the updater.

Also, when I look at https://git.kernel.org/pub/scm/docs/kernel/website.git/tree/pelicanconf.py?id=e6083565a79c3d711c1a76d9312b8c00e06b826b#n28

> NB: Don't add a kernel to longterm if it's the only stable kernel currently
>     listed on www.kernel.org. This will break people's scripts, so we don't
>     support doing it. Wait till there's an x.x.1 of the next stable branch.

It looks like we're not the only people using kernel.org to fetch releases.
Of course, structured data would be nicer, but I wouldn't expect the script to break soon, but I'm not sure if it's worth the effort.

**Comment by Atemu** [comment]
> I think this would imply a very specific directory structure with kernel checkouts in it

AFAICT you can just give it a `GIT_REPO` env var that can just simply be `https://git.kernel.org/`.

> It looks like we're not the only people using kernel.org to fetch releases.

Hyrum's Law strikes again...

**Comment by Ma27** [comment]
> Hyrum's Law strikes again...

I mean, the comment says that they know about the issue, so I don't really understand, why we can't have something like `curl kernel.org -L -H 'Accept: application/json'`.

> AFAICT you can just give it a GIT_REPO env var that can just simply be https://git.kernel.org/.

On a first glance it looks like `GitPython` is expecting a local path, but I may be holding it wrong:

```
>>> from git import Repo
>>> Repo("https://github.com/nixos/nixpkgs")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/gi5ads3qkknzhpvw9x55bpjrzb2jw6lk-python3.12-gitpython-3.1.43/lib/python3.12/site-packages/git/repo/base.py", line 236, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /home/ma27/https:/github.com/nixos/nixpkgs
```

Even if remote URLs are supported, wouldn't it still mean a _massive_ increase in execution time (as opposed to now) given that a clone (or at least partial clone) is necessary?

**Comment by K900** [comment]
Yeah we can't clone the entire repo for this.

**Comment by Atemu** [comment]
> given that a clone (or at least partial clone) is necessary

Is it? Doesn't it only need to look at the tags (pointers)?
