### ISSUE TITLE
Oterm 0.6.9: runtime error: No module named 'textualeffects' 

### ISSUE THREAD

**Issue by gaelj** [NixOS/nixpkgs#366021]
## Describe the bug

```sh
> oterm                                        
Traceback (most recent call last):
  File "/nix/store/fqlbycsggrl1mz5wwnxghjbbbq31948q-oterm-0.6.9/bin/.oterm-wrapped", line 6, in <module>
    from oterm.cli.oterm import cli
  File "/nix/store/fqlbycsggrl1mz5wwnxghjbbbq31948q-oterm-0.6.9/lib/python3.12/site-packages/oterm/cli/oterm.py", line 7, in <module>
    from oterm.app.oterm import app
  File "/nix/store/fqlbycsggrl1mz5wwnxghjbbbq31948q-oterm-0.6.9/lib/python3.12/site-packages/oterm/app/oterm.py", line 13, in <module>
    from oterm.app.splash import splash
  File "/nix/store/fqlbycsggrl1mz5wwnxghjbbbq31948q-oterm-0.6.9/lib/python3.12/site-packages/oterm/app/splash.py", line 4, in <module>
    from textualeffects.effects import EffectType
ModuleNotFoundError: No module named 'textualeffects'
```

## Steps To Reproduce

```nix
    environment.systemPackages = with pkgs; [
      ollama
      oterm
    ];
```

## Notify maintainers

@suhr 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by suhr** [comment]
I would like pass the maintenance of this package to someone else.

**Comment by gaelj** [comment]
@suhr what steps have you taken to pass on the maintenance of this package to someone else ? Or are you just abandoning this ?

**Comment by suhr** [comment]
I'm waiting for someone else to take care of it. When a PR appears, I will ask for passing the maintenance of this package.

**Comment by gaelj** [comment]
Fix has been merged
