### ISSUE TITLE
Package request: Grayjay Desktop

### ISSUE THREAD

**Issue by vfosnar** [NixOS/nixpkgs#366543]
## Project description

Grayjay is an [..] app that serves as a video player and source aggregator. It allows you to stream and organize videos from various sources, providing a unified platform for your entertainment needs.

https://grayjay.app/#faq

## Metadata

* homepage URL: https://grayjay.app/ and https://grayjay.app/desktop/
* source URL: https://gitlab.futo.org/videostreaming/Grayjay.Desktop
* license: FUTO Source First License 1.1 https://gitlab.futo.org/videostreaming/Grayjay.Desktop/-/blob/master/LICENSE.md
* platforms: linux
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mraxilus** [comment]
In the meantime, does anyone have instructions on how to get something like this running without an existing package being made available? I assume their will be many updates to Grayjay as the Desktop version is quite nascent.

**Comment by vytskalt** [comment]
The README has a NixOS configuration to create a FHS environment: https://gitlab.futo.org/videostreaming/Grayjay.Desktop#nixos-config

Basically, download the Linux version from the official website and add a `shell.nix` file:
```nix
{ pkgs ? import <nixpkgs> {} }:

(pkgs.buildFHSUserEnv {
  name = "fhs";
  targetPkgs = _: with pkgs; [
    libz
    icu
    openssl # For updater

    xorg.libX11
    xorg.libXcomposite
    xorg.libXdamage
    xorg.libXext
    xorg.libXfixes
    xorg.libXrandr
    xorg.libxcb

    gtk3
    glib
    nss
    nspr
    dbus
    atk
    cups
    libdrm
    expat
    libxkbcommon
    pango
    cairo
    udev
    alsa-lib
    mesa
    libGL
    libsecret
  ];
}).env
```

Now run `nix-shell` to get into the FHS environment and then run `./Grayjay`

**Comment by esibun** [comment]
The release system Grayjay uses is not great for packaging.  I think the only good way to package this would be to use the GitLab and build from source.  Looking at the build script it looks like it requires .NET 8 to build (in addition to the provided dependencies in their README).

Their git repository is here: https://gitlab.futo.org/videostreaming/Grayjay.Desktop

Luckily they do tag releases on GitLab.

**Comment by mraxilus** [comment]
> The README has a NixOS configuration to create a FHS environment: https://gitlab.futo.org/videostreaming/Grayjay.Desktop#nixos-config
> 
> Basically, download the [Linux version from the official website](https://updater.grayjay.app/Apps/Grayjay.Desktop/Grayjay.Desktop-linux-x64.zip), unzip it and add this `shell.nix` file:
> ```nix
> { pkgs ? import <nixpkgs> {} }:
> 
> (pkgs.buildFHSUserEnv {
>   name = "fhs";
>   targetPkgs = _: with pkgs; [
>     libz
>     icu
>     openssl # For updater
> 
>     xorg.libX11
>     xorg.libXcomposite
>     xorg.libXdamage
>     xorg.libXext
>     xorg.libXfixes
>     xorg.libXrandr
>     xorg.libxcb
> 
>     gtk3
>     glib
>     nss
>     nspr
>     dbus
>     atk
>     cups
>     libdrm
>     expat
>     libxkbcommon
>     pango
>     cairo
>     udev
>     alsa-lib
>     mesa
>     libGL
>     libsecret
>   ];
> }).env
> ```
> 
> cd into the directory, run `nix-shell` to get into the FHS environment and then start Grayjay with `./Grayjay`

Thanks for this. Out of curiosity, how did you determine that dependency listing?

**Comment by Krutonium** [comment]
>snip

It's at the bottom of the GrayJay Readme.

**Comment by Electrostasy** [comment]
I've been trying to get this to work, and while it compiles successfully with the derivation provided below (note that I've never packaged dotnet programs before, and I haven't gotten to runtime dependencies yet), Grayjay writes a LOT of files (logging, temp files, state...) to the `$out/lib/grayjay` directory. In a lot of areas of the source code, it is expected that `$out/lib/grayjay` is writable and I have no idea how to fix it short of patching out all the relevant code.

Any ideas? Maybe we need to take it up with upstream because these paths (specifically paths pointed to by [`Directories.Base` and `Directories.Temporary`](https://github.com/futo-org/Grayjay.Desktop/blob/373cd8448cb0ede78a0a1f8a0cf25ca7666f56d4/Grayjay.ClientServer/Constants/Directories.cs)) point to a directory in the Nix store, and I've been trying to point them to outside it.

```nix
{ buildDotnetModule
, fetchFromGitLab
, dotnetCorePackages
}:

buildDotnetModule (finalAttrs: {
  pname = "grayjay";
  version = "2";

  src = fetchFromGitLab {
    domain = "gitlab.futo.org";
    owner = "videostreaming";
    repo = "Grayjay.Desktop";
    rev = "refs/tags/${finalAttrs.version}";
    hash = "sha256-dkX1eJDgyhPSeNuZengon8MMw7UwNM1pP45lQYggqVs=";
    fetchSubmodules = true;
  };

  postPatch = ''
    # Workaround for Grayjay logging in $out/lib/grayjay/log.txt.
    substituteInPlace 'Grayjay.ClientServer/Logger.cs' \
      --replace '_logFile = Path.Combine(Directories.Base, "log.txt");' '_logFile = Path.Combine(Directories.User, "log.txt");'

    # Workaround for Grayjay storing temporary files in $out/lib/grayjay/temp_files.
    substituteInPlace 'Grayjay.ClientServer/Constants/Directories.cs' \
      --replace 'string dir = Path.Combine(Base, "temp_files");' 'string dir = Path.Combine(Path.GetTempPath(), "grayjay");'

    # Workaround for Grayjay storing the starting up file in $out/lib/grayjay/starting.
    substituteInPlace 'Grayjay.Desktop.CEF/Program.cs' \
      --replace 'StartingUpFile = Path.Combine(Directories.Base, StartingUpFileName);' 'StartingUpFile = Path.Combine(Directories.Temporary, StartingUpFileName);'

    # Workaround for Grayjay storing all the state in $out/lib/grayjay/{downloads_playlists, ...}.
    # Not an acceptable change since it messes up the CEF paths too.
    # substituteInPlace 'Grayjay.ClientServer/States/StateApp.cs' \
    #   --replace 'return new DirectoryInfo(Directories.Base);' 'return new DirectoryInfo(Directories.User);'
  '';

  projectFile = "Grayjay.Desktop.sln";
  nugetDeps = ./deps.json;

  dotnet-runtime = dotnetCorePackages.aspnetcore_8_0;

  executables = [ "Grayjay" ];

  # TODO: Add dependencies later once the paths are figured out.
  # runtimeDeps = [];

  meta = {

  };
})
```

**Comment by esibun** [comment]
Agreed, I went ahead and filed a bug for it, these files should live in $XDG_DATA_DIR or similar.  Thanks for filling in the gaps.

**Comment by normalcea** [comment]
@mraxilus 

> In the meantime, does anyone have instructions on how to get something like this running without an existing package being made available? I assume their will be many updates to Grayjay as the Desktop version is quite nascent.

I hacked together a Nix `buildFHSEnv` derivation that integrates Grayjay as much as possible. You can take the (pkgs.buildFHSEnv) part and place it directly in `home.packages` if you're using home-manager. This requires downloading the pre-compiled grayjay from [their website](https://updater.grayjay.app/Apps/Grayjay.Desktop/Grayjay.Desktop-linux-x64.zip) and unpacking its contents which should be located in `installDir` as an absolute path. 

I've tested this on NixOS 24.11 with GNOME and it works with the caveat that exiting the application will require you to wait until it fully quits out in the background. 

```nix
{
  pkgs ? import <nixpkgs> { },
}:
(pkgs.buildFHSEnv rec {
  pname = "grayjay";
  version = "2";
  # Absolute path to where the contents of Grayjay.Desktop-linux-x64-v{x} is located
  installDir = "/home/user/Grayjay";

  # grayjay script wrapper that sets cwd to `installdir'
  start-grayjay = pkgs.writeShellScriptBin "start-grayjay" ''cd ${installDir} && ./Grayjay'';

  # grayjay desktop file.
  grayjay-desktop-file = pkgs.makeDesktopItem {
    name = "Grayjay";
    type = "Application";
    desktopName = "Grayjay";
    genericName = "Desktop Client for Grayjay";
    comment = "A desktop client for Grayjay to stream and download video content";
    icon = "${installDir}/grayjay.png";
    exec = pname;
    path = "${installDir}";
    terminal = false;
    categories = [ "Network" ];
    keywords = [
      "YouTube"
      "Player"
    ];
    startupNotify = true;
    startupWMClass = "Grayjay";
    prefersNonDefaultGPU = false;
  };

  targetPkgs =
    _: with pkgs; [
      start-grayjay
      grayjay-desktop-file
      libz
      icu
      openssl # For updater

      xorg.libX11
      xorg.libXcomposite
      xorg.libXdamage
      xorg.libXext
      xorg.libXfixes
      xorg.libXrandr
      xorg.libxcb

      gtk3
      glib
      nss
      nspr
      dbus
      atk
      cups
      libdrm
      expat
      libxkbcommon
      pango
      cairo
      udev
      alsa-lib
      mesa
      libGL
      libsecret

    ];
  runScript = "start-grayjay";
  extraInstallCommands = ''
    mkdir -p $out/share/applications/
    cp ${grayjay-desktop-file}/share/applications/Grayjay.desktop $out/share/applications/
  '';
})
```

**Comment by esibun** [comment]
Per upstream, as of version 3 if we remove Grayjay.Desktop.CEF/Portable prior to compilation, the package should write out to a directory in $HOME instead of writing to the working directory.

**Comment by Electrostasy** [comment]
> Per upstream, as of version 3 if we remove Grayjay.Desktop.CEF/Portable prior to compilation, the package should write out to a directory in $HOME instead of writing to the working directory.

Yes, it seems to write to the user directory now. However, it seems CEF still sets `$out/lib/grayjay/cef` as its working directory, and fails:
```
Directories:Base Directory: /home/electro/Grayjay
Directories:Temporary Directory: /home/electro/Grayjay/temp_files
Directories:Log file path: /home/electro/Grayjay/log.txt
T:PortFile path: /home/electro/Grayjay/port
T:StartingUpFile path: /home/electro/Grayjay/starting
T:Found StartingUpFile, waiting for PortFile and process
T:No PortFile after waiting, killing any lingering (stuck) process
T:Created StartingUpFile, removed PortFile
Program:Main: StateApp.Startup
StateApp:Startup: Initializing PluginEncryptionProvider
StateApp:Startup: Initializing DatabaseConnection
StateApp:Startup: Ensuring Table DBSubscriptionCache
StateApp:Startup: Ensuring Table DBHistory
StateApp:Startup: Initializing Download Cycle
StateDownloads:Started downloading cycle
StateDownloads:Ended downloading cycle
Program:Main: StateApp.Startup finished (67ms)
Program:Extra args: 
Program:Main: Starting DotCefProcess
CEF:Searching for dotcefnative, search paths:
CEF: - /nix/store/j3mn7cz41cs3pk0n9w0j17hslqq54qpr-grayjay-3/lib/grayjay/cef/dotcefnative
CEF: - /nix/store/j3mn7cz41cs3pk0n9w0j17hslqq54qpr-grayjay-3/lib/grayjay/dotcefnative
CEF: - /home/electro/dotcefnative
CEF: - /home/electro/cef/dotcefnative
CEF:Working directory '/nix/store/j3mn7cz41cs3pk0n9w0j17hslqq54qpr-grayjay-3/lib/grayjay/cef'.
CEF:CEF exe path '/nix/store/j3mn7cz41cs3pk0n9w0j17hslqq54qpr-grayjay-3/lib/grayjay/cef/dotcefnative'.
--change-stack-guard-on-fork=disable --disable-chrome-runtime --parent-to-child 111 --child-to-parent 114 --disable-web-security --use-views 
Unhandled exception. System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/nix/store/j3mn7cz41cs3pk0n9w0j17hslqq54qpr-grayjay-3/lib/grayjay/cef/dotcefnative' with working directory '/nix/store/j3mn7cz41cs3pk0n9w0j17hslqq54qpr-grayjay-3/lib/grayjay/cef'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at DotCef.DotCefProcess.Start(String args)
   at Grayjay.Desktop.Program.Main(String[] args)
   at Grayjay.Desktop.Program.<Main>(String[] args)
fish: Job 1, './result/bin/Grayjay' terminated by signal SIGABRT (Abort)
```

I'm not sure where to go from here, maybe I'll dig around the source some more. I see [here](https://gitlab.futo.org/videostreaming/Grayjay.Desktop/-/blob/master/Grayjay.Desktop.CEF/Program.cs?ref_type=heads#L276) that this should be where CEF is first invoked from presumably their [wrapper library](https://gitlab.futo.org/videostreaming/JustCef/-/blob/master/DotCefProcess.cs?ref_type=heads#L233), which is where the working directory is set. Might be patchable.

**Comment by Electrostasy** [comment]
Also, it seems that you can't remove the Portable file prior to compilation as it errors out:
```
...
> CSC : error CS2001: Source file '/build/source/Grayjay.Desktop.CEF/Portable' could not be found. [/build/source/Grayjay.Desktop.CEF/Grayjay.Desktop.CEF.csproj]
...
```

Removing it after compiling does work, however.

For completeness, I've attached the updated WIP derivation below, as I noticed I could not build all the subprojects using just the solution (previously the CEF project would not build and it kept looking for CEF in my home directory). They are taken from the [`Grayjay.Desktop.sln` file](https://gitlab.futo.org/videostreaming/Grayjay.Desktop/-/blob/7279b53d81ca62820ba030f34540e6e0ef7d9198/Grayjay.Desktop.sln).
<details>

```nix
{ buildDotnetModule
, fetchFromGitLab
, dotnetCorePackages
}:

buildDotnetModule (finalAttrs: {
  pname = "grayjay";
  version = "3";

  src = fetchFromGitLab {
    domain = "gitlab.futo.org";
    owner = "videostreaming";
    repo = "Grayjay.Desktop";
    rev = "refs/tags/${finalAttrs.version}";
    hash = "sha256-NC6rwgnw0w/87jWU8WyylK/5XMTanWEUDPp9AHdNhI0=";
    fetchSubmodules = true;
  };

  projectFile = [
    "Grayjay.ClientServer/Grayjay.ClientServer.csproj"
    "Grayjay.Engine/Grayjay.Engine/Grayjay.Engine.csproj"
    "Grayjay.Desktop.CEF/Grayjay.Desktop.CEF.csproj"
    "FUTO.MDNS/FUTO.MDNS/FUTO.MDNS.csproj"
    "JustCef/DotCef.csproj"
  ];

  testProjectFile = [
    "Grayjay.Desktop.Tests/Grayjay.Desktop.Tests.csproj"
    "Grayjay.Engine/Grayjay.Engine.Tests/Grayjay.Engine.Tests.csproj"
  ];

  nugetDeps = ./deps.json;

  dotnet-runtime = dotnetCorePackages.aspnetcore_8_0;

  executables = [ "Grayjay" ];

  postInstall = ''
    rm $out/lib/grayjay/Portable
  '';

  # TODO: Add dependencies later once the paths are figured out.
  # runtimeDeps = [];

  meta = {

  };
})
```

</details>

**Comment by float3** [comment]
> @mraxilus
> 
> > In the meantime, does anyone have instructions on how to get something like this running without an existing package being made available? I assume their will be many updates to Grayjay as the Desktop version is quite nascent.
> 
> I hacked together a Nix `buildFHSEnv` derivation that integrates Grayjay as much as possible. You can take the `(pkgs.buildFHSEnv)` part and place it directly in `home.packages` if you're using home-manager. This requires downloading the pre-compiled grayjay from [their website](https://updater.grayjay.app/Apps/Grayjay.Desktop/Grayjay.Desktop-linux-x64.zip) and unpacking its contents which should be located in `installDir` as an absolute path.
> 
> I've tested this on NixOS 24.11-x86_64 with GNOME and it works with the caveat that exiting the application will require you to wait until it fully quits out in the background. It also has the side-effect of creating a `Grayjay` directory in the user's homedir, so I just set that as the `installDir` and moved the zip's contents to it.
> 
> **EDIT**: You can also use `nix profile install -f grayjay.nix` which is what I'm doing currently. Or you can use grayjay as a proper package variable with `grayjay = pkgs.callPackage grayjay.nix {};`
> 
> ```nix
> {
>   pkgs ? import <nixpkgs> { },
> }:
> (pkgs.buildFHSEnv rec {
>   pname = "grayjay";
>   version = "2";
>   # Absolute path to where the contents of Grayjay.Desktop-linux-x64-v{x} is located
>   installDir = "/home/user/Grayjay";
> 
>   # grayjay script wrapper that sets cwd to `installdir'
>   start-grayjay = pkgs.writeShellScriptBin "start-grayjay" ''cd ${installDir} && ./Grayjay'';
> 
>   # grayjay desktop file.
>   grayjay-desktop-file = pkgs.makeDesktopItem {
>     name = "Grayjay";
>     type = "Application";
>     desktopName = "Grayjay";
>     genericName = "Desktop Client for Grayjay";
>     comment = "A desktop client for Grayjay to stream and download video content";
>     icon = "${installDir}/grayjay.png";
>     exec = pname;
>     path = installDir;
>     terminal = false;
>     categories = [ "Network" ];
>     keywords = [
>       "YouTube"
>       "Player"
>     ];
>     startupNotify = true;
>     startupWMClass = "Grayjay";
>     prefersNonDefaultGPU = false;
>   };
> 
>   targetPkgs =
>     _: with pkgs; [
>       start-grayjay
>       grayjay-desktop-file
>       libz
>       icu
>       openssl # For updater
> 
>       xorg.libX11
>       xorg.libXcomposite
>       xorg.libXdamage
>       xorg.libXext
>       xorg.libXfixes
>       xorg.libXrandr
>       xorg.libxcb
> 
>       gtk3
>       glib
>       nss
>       nspr
>       dbus
>       atk
>       cups
>       libdrm
>       expat
>       libxkbcommon
>       pango
>       cairo
>       udev
>       alsa-lib
>       mesa
>       libGL
>       libsecret
> 
>     ];
>   runScript = "start-grayjay";
>   extraInstallCommands = ''
>     mkdir -p $out/share/applications/
>     cp ${grayjay-desktop-file}/share/applications/Grayjay.desktop $out/share/applications/
>   '';
> })
> ```
```
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
```

I get this error

**Comment by michaelBelsanti** [comment]
seems they've fixed the hardcoded paths and the changes will be in the next release: https://github.com/futo-org/Grayjay.Desktop/issues/63#issuecomment-2588115934

I'm trying to get a working package that builds it from master but I can't build this app for the life of me.

**Comment by michaelBelsanti** [comment]
I packaged it from source* here: https://codeberg.org/quasigod/nur/src/branch/main/packages/grayjay-desktop/default.nix

\* It currently pulls the cef directory from the binary. FUTO has hit their Github LFS limit, which is preventing it from being built. I'll change this once they fix that.

There are still some small patches that I'll try to upstream. If the LFS issue is fixed by the next release I'll make a PR to add it to nixpkgs. In the meantime, you should be able to install it from my flake.

**Comment by spudnut2000** [comment]
Any updates on this?

**Comment by sigboe** [comment]
@spudnut2000 People are working on it! There is a package in a Pull Request to nixpkgs, it was almost merged earlier, but then it was discovered that it doesn't build for ARM-Linux. This has been corrected in the package now, but there is an update to v5, and also some improvements to the wrapper that has been suggested. 

So, there is a PR, there are two known things needed before the PR is accepted, and there is a suggested edit that shows how to do these changes.
