### ISSUE TITLE
Immich upgrades might fail because of pgvectors indices

### ISSUE THREAD

**Issue by Zocker1999NET** [NixOS/nixpkgs#367967]
## Describe the bug

I upgraded Immich installed via the NixOS module from version 119.1 to 123.0. (To install Immich on NixOS 24.05, I "sideloaded" the NixOS module & the package from the unstable branch at that time.) I then upgraded my VM now to 24.11, but Immich could not start because the pgvectors indices were broken due to the upgrade.

I am aware that I was using an unstable & unsupported setup before, but I still want to report this because I assume this might happen in future upgrades as well.

## Steps To Reproduce

1. Install Immich into a NixOS 24.05 image
  - import Immich module from NixOS unstable tree
  - import `immich` package via an overlay
  - configure `services.immich` according to the module’s doc
3. Upgrade to NixOS 24.11, where sideloading the module & applying the overlay are no longer required
4. See that Immich can no longer start

## Expected behavior

A smooth upgrade experience without (undocumented) hands-on required.

## Logs

```
Dec 24 16:13:10 immich systemd[1]: Started Immich backend server (Self-hosted photo and video backup solution).
Dec 24 16:13:12 immich immich[814]: Starting api worker
Dec 24 16:13:12 immich immich[814]: Starting microservices worker
Dec 24 16:13:14 immich immich[814]: [Nest] 814  - 12/24/2024, 4:13:14 PM     LOG [Microservices:EventRepository] Initialized websocket server
Dec 24 16:13:14 immich immich[814]: [Nest] 814  - 12/24/2024, 4:13:14 PM    WARN [Microservices:DatabaseService] Could not run vector reindexing checks. If the extension was updated, please restart the Postgres instance.
Dec 24 16:13:14 immich immich[814]: QueryFailedError: pgvecto.rs: The extension is upgraded so all index files are outdated.
Dec 24 16:13:14 immich immich[814]: ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`
Dec 24 16:13:14 immich immich[814]:     at PostgresQueryRunner.query (/nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
Dec 24 16:13:14 immich immich[814]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Dec 24 16:13:14 immich immich[814]:     at async DataSource.query (/nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/node_modules/typeorm/data-source/DataSource.js:350:20)
Dec 24 16:13:14 immich immich[814]:     at async DatabaseRepository.shouldReindex (/nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/dist/repositories/database.repository.js:136:25)
Dec 24 16:13:14 immich immich[814]:     at async DatabaseService.checkReindexing (/nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/dist/services/database.service.js:144:17)
Dec 24 16:13:14 immich immich[814]:     at async /nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/dist/services/database.service.js:93:13
Dec 24 16:13:14 immich immich[814]:     at async /nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/dist/repositories/database.repository.js:197:23 {
Dec 24 16:13:14 immich immich[814]:   query: 'SELECT idx_status FROM pg_vector_index_stat WHERE indexname = $1',
Dec 24 16:13:14 immich immich[814]:   parameters: [ 'clip_index' ],
Dec 24 16:13:14 immich immich[814]:   driverError: error: pgvecto.rs: The extension is upgraded so all index files are outdated.
Dec 24 16:13:14 immich immich[814]:   ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`
Dec 24 16:13:14 immich immich[814]:       at /nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/node_modules/pg/lib/client.js:535:17
Dec 24 16:13:14 immich immich[814]:       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Dec 24 16:13:14 immich immich[814]:       at async PostgresQueryRunner.query (/nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
Dec 24 16:13:14 immich immich[814]:       at async DataSource.query (/nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/node_modules/typeorm/data-source/DataSource.js:350:20)
Dec 24 16:13:14 immich immich[814]:       at async DatabaseRepository.shouldReindex (/nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/dist/repositories/database.repository.js:136:25)
Dec 24 16:13:14 immich immich[814]:       at async DatabaseService.checkReindexing (/nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/dist/services/database.service.js:144:17)
Dec 24 16:13:14 immich immich[814]:       at async /nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/dist/services/database.service.js:93:13
Dec 24 16:13:14 immich immich[814]:       at async /nix/store/5hhz708v6r03r6bbb5g2fzf4ylvk8nd9-immich-1.123.0/dist/repositories/database.repository.js:197:23 {
Dec 24 16:13:14 immich immich[814]:     length: 234,
Dec 24 16:13:14 immich immich[814]:     severity: 'ERROR',
Dec 24 16:13:14 immich immich[814]:     code: 'XX000',
Dec 24 16:13:14 immich immich[814]:     detail: undefined,
Dec 24 16:13:14 immich immich[814]:     hint: undefined,
Dec 24 16:13:14 immich immich[814]:     position: undefined,
Dec 24 16:13:14 immich immich[814]:     internalPosition: undefined,
Dec 24 16:13:14 immich immich[814]:     internalQuery: undefined,
Dec 24 16:13:14 immich immich[814]:     where: undefined,
Dec 24 16:13:14 immich immich[814]:     schema: undefined,
Dec 24 16:13:14 immich immich[814]:     table: undefined,
Dec 24 16:13:14 immich immich[814]:     column: undefined,
Dec 24 16:13:14 immich immich[814]:     dataType: undefined,
Dec 24 16:13:14 immich immich[814]:     constraint: undefined,
Dec 24 16:13:14 immich immich[814]:     file: 'error.rs',
Dec 24 16:13:14 immich immich[814]:     line: '125',
Dec 24 16:13:14 immich immich[814]:     routine: 'vectors::error::check_client'
Dec 24 16:13:14 immich immich[814]:   },
Dec 24 16:13:14 immich immich[814]:   length: 234,
Dec 24 16:13:14 immich immich[814]:   severity: 'ERROR',
Dec 24 16:13:14 immich immich[814]:   code: 'XX000',
Dec 24 16:13:14 immich immich[814]:   detail: undefined,
Dec 24 16:13:14 immich immich[814]:   hint: undefined,
Dec 24 16:13:14 immich immich[814]:   position: undefined,
Dec 24 16:13:14 immich immich[814]:   internalPosition: undefined,
Dec 24 16:13:14 immich immich[814]:   internalQuery: undefined,
Dec 24 16:13:14 immich immich[814]:   where: undefined,
Dec 24 16:13:14 immich immich[814]:   schema: undefined,
Dec 24 16:13:14 immich immich[814]:   table: undefined,
Dec 24 16:13:14 immich immich[814]:   column: undefined,
Dec 24 16:13:14 immich immich[814]:   dataType: undefined,
Dec 24 16:13:14 immich immich[814]:   constraint: undefined,
Dec 24 16:13:14 immich immich[814]:   file: 'error.rs',
Dec 24 16:13:14 immich immich[814]:   line: '125',
Dec 24 16:13:14 immich immich[814]:   routine: 'vectors::error::check_client'
Dec 24 16:13:14 immich immich[814]: }
Dec 24 16:13:14 immich immich[814]: microservices worker error: QueryFailedError: pgvecto.rs: The extension is upgraded so all index files are outdated.
Dec 24 16:13:14 immich immich[814]: ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`
Dec 24 16:13:14 immich immich[814]: microservices worker exited with code 1
Dec 24 16:13:14 immich immich[814]: Killing api process
Dec 24 16:13:14 immich systemd[1]: immich-server.service: Main process exited, code=exited, status=1/FAILURE
Dec 24 16:13:14 immich systemd[1]: immich-server.service: Failed with result 'exit-code'.
Dec 24 16:13:14 immich systemd[1]: immich-server.service: Consumed 6.541s CPU time, 616.6M memory peak, 137.9M read from disk.
Dec 24 16:13:17 immich systemd[1]: immich-server.service: Scheduled restart job, restart counter is at 1.
```

## Additional context

I solved this via following the upgrade step documented [here](https://docs.pgvecto.rs/admin/upgrading.html#upgrading). In full, this was:

- logging into the affected server
- `sudo -u postgres psql`
  - these lines to get access to the extension: https://github.com/NixOS/nixpkgs/blob/1807c2b91223227ad5599d7067a61665c52d1295/nixos/modules/services/web-apps/immich.nix#L239-L244
  - then `ALTER EXTENSION vectors UPDATE;`
  - finally `SELECT pgvectors_upgrade();`
- `systemctl restart postgresql && systemctl restart immich-server`

## Metadata

(sorry, I cannot yet provide this for this VM, as is has no way to access the internet.)

## Notify maintainers

@jvanbruegge as maintainer of the module & package

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Why would this be considered a bug? It's state that's managed by the application, not NixOS.

**Comment by Zocker1999NET** [comment]
To be clear, I’m not completely sure whether this bug is more or less the issue of Immich or of NixOS.

Reporting this bug to Immich itself feels wrong to me as NixOS seems to deploy Immich in a "unsupported" way (the [Immich docs](https://immich.app/docs/install/requirements) make it clear that they see Docker Compose as a hard requirement, while NixOS runs Immich outside of Docker). I have searched for this bug on Immich’s issues at time of writing & have not found any, despite that this Immich version I deployed was not relatively new.

Also, neither Immich’s docs nor bug reports have given me the solution, but the documentation of a library/framework Immich uses itself. I cannot pinpoint it due to the lack of time, but I assume that given the lack of reports from users using Immich’s Docker image and the lack of instructions in the release notes from Immich, that the official Docker Compose deployment is managing the state of its database (plugins) correctly. And that this part is missing from the deployment in NixOS. So in case my assumption is right, IMO this is something which has to be fixed in NixOS as the Immich devs would probably just say "use the official Docker Compose, its fixed there".

**Comment by dotlambda** [comment]
> * finally `SELECT pgvectors_upgrade();`

That should be done by Immich regardless of the Docker setup: https://github.com/immich-app/immich/blob/v1.123.0/server/src/repositories/database.repository.ts#L104

> To install Immich on NixOS 24.05, I "sideloaded" the NixOS module & the package from the unstable branch at that time.

Maybe the Postgres version on 24.05 was too old.

> I then upgraded my VM now to 24.11

Or more likely, this upgrade changed the default Postgres version.
Does someone know if Immich stores the version of Postgres used so we can run this upgrade if it changes?
Does it make sense to always run `pgvectors_upgrade()` in `immich-pgvectors-setup.sql`?

**Comment by eclairevoyant** [comment]
Well in any case `pgvectors_upgrade()` didn't seem to suffice, I solved it via https://discourse.nixos.org/t/cant-run-immich-because-psql-broke-itself/53914/3

> Turns out I needed to restart the psql service, then run the below, then restart it again
> 
> ```
> $ sudo -u postgres psql -d immich                                 
> psql (16.4)
> Type "help" for help.
> 
> immich=# SELECT
>         I.relname AS indexname
>     FROM pg_index X JOIN
>          pg_class I ON I.oid = X.indexrelid JOIN
>          pg_am A ON A.oid = I.relam
>     WHERE A.amname = 'vectors';
>  indexname  
> ------------
>  clip_index
>  face_index
> (2 rows)
> 
> immich=# REINDEX INDEX clip_index;
> REINDEX
> immich=# REINDEX INDEX face_index;
> REINDEX
> ```

**Comment by dotlambda** [comment]
> I solved it

I'm confused. You're not the OP.

**Comment by dotlambda** [comment]
> immich=# REINDEX INDEX clip_index;
> REINDEX
> immich=# REINDEX INDEX face_index;
> REINDEX

That's also done by Immich: https://github.com/immich-app/immich/blob/v1.123.0/server/src/repositories/database.repository.ts#L107-L108
But it's only executed if Immich is updated to a new version: https://github.com/immich-app/immich/blob/v1.123.0/server/src/services/database.service.ts#L102-L103
So we should consider writing a patch for upstream that also runs this whenever Postgres is upgraded.

**Comment by eclairevoyant** [comment]
> > I solved it
> 
> I'm confused. You're not the OP.

Sure, I just happened to have encountered that same error last year and had shared my approach to diagnosis and resolution that I used at that time, in the hopes of unblocking them (and perhaps informing the current approach). Good to know upstream has something in place already for this.

**Comment by kevincox** [comment]
I have edited the original description to reference a copy on Archive.org rather than `docs.pgvecto.rs` as the latter appears to have expired, does not provide the desired information and you never know who will buy the domain next.

**Comment by eclairevoyant** [comment]
The current instructions are at https://docs.vectorchord.ai/admin/upgrading.html#upgrading
