### ISSUE TITLE
Build failure: matrix-synapse (unwrapped)

### ISSUE THREAD

**Issue by jcaesar** [NixOS/nixpkgs#369303]
## Steps To Reproduce

1. build matrix-synapse
  Doing so is currently somewhat difficult, because of #367976. Try e.g. `nix build --expr 'let nixpkgs = builtins.getFlake "github:NixOS/nixpkgs/adaa9f280329b5f814e8dc83eceddd42b20f72f4"; pkgs = import nixpkgs { overlays = [(final: prev: { python312 = prev.python312.override { packageOverrides = final: prev: { pysaml2 = final.toPythonModule pkgs.emptyDirectory; }; }; })]; system = "x86_64-linux"; }; in pkgs.matrix-synapse'` 

## Build log

<details>

<summary>Build Log</summary>

(last 28 lines)
```
…
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/nix/store/nmhc5z32ibymjaj7kqhf8ns3139q782z-python3.12-twisted-24.10.0/lib/python3.12/site-packages/twisted/logger/_observer.py", line 81, in __call__
    observer(event)
  File "/nix/store/nmhc5z32ibymjaj7kqhf8ns3139q782z-python3.12-twisted-24.10.0/lib/python3.12/site-packages/twisted/logger/_legacy.py", line 90, in __call__
    self.legacyObserver(event)
  File "/nix/store/nmhc5z32ibymjaj7kqhf8ns3139q782z-python3.12-twisted-24.10.0/lib/python3.12/site-packages/twisted/trial/_dist/workertrial.py", line 44, in emit
    self.protocol.callRemote(managercommands.TestWrite, out=text)
  File "/nix/store/nmhc5z32ibymjaj7kqhf8ns3139q782z-python3.12-twisted-24.10.0/lib/python3.12/site-packages/twisted/protocols/amp.py", line 951, in callRemote
    return co._doCommand(self)
  File "/nix/store/nmhc5z32ibymjaj7kqhf8ns3139q782z-python3.12-twisted-24.10.0/lib/python3.12/site-packages/twisted/protocols/amp.py", line 1973, in _doCommand
    d = proto._sendBoxCommand(
  File "/nix/store/nmhc5z32ibymjaj7kqhf8ns3139q782z-python3.12-twisted-24.10.0/lib/python3.12/site-packages/twisted/protocols/amp.py", line 884, in _sendBoxCommand
    box._sendTo(self.boxSender)
  File "/nix/store/nmhc5z32ibymjaj7kqhf8ns3139q782z-python3.12-twisted-24.10.0/lib/python3.12/site-packages/twisted/protocols/amp.py", line 713, in _sendTo
    proto.sendBox(self)
  File "/nix/store/nmhc5z32ibymjaj7kqhf8ns3139q782z-python3.12-twisted-24.10.0/lib/python3.12/site-packages/twisted/protocols/amp.py", line 2358, in sendBox
    self.transport.write(box.serialize())
  File "/nix/store/nmhc5z32ibymjaj7kqhf8ns3139q782z-python3.12-twisted-24.10.0/lib/python3.12/site-packages/twisted/protocols/amp.py", line 692, in serialize
    raise TooLong(False, True, v, k)
twisted.protocols.amp.TooLong: 

tests.storage.databases.main.test_events_worker.DatabaseOutageTestCase.test_recovery
-------------------------------------------------------------------------------
Ran 3914 tests in 126.022s

FAILED (skips=180, errors=1, successes=3733)
```

</details>

## Metadata

```plain
➜ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.3, NixOS, 25.05 (Warbler), j_93110e1_20241209082912`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/mxv25ag637gkza620ff80pfhc6wii21z-source`
```

## Notify maintainers

@Ralith  (sorry, picked you at random, no idea how to highlight a team)

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ralith** [comment]
I'm not currently active in Matrix maintenance. @fadenb?

**Comment by transgirllucy** [comment]
#370253

**Comment by transgirllucy** [comment]
#370253

**Comment by jcaesar** [comment]
Some more tests started breaking.

<details><summary>Log</summary>

```plain
…
========================================================================
[ERROR]
Traceback (most recent call last):
  File "/nix/store/c9m6yd8fg1flz2j5r4bif1ib5j20a0cy-python3-3.12.8/lib/python3.12/unittest/mock.py", line 1861, in _inner
    return f(*args, **kw)
  File "/build/source/tests/http/test_proxyagent.py", line 869, in test_proxy_with_http_scheme
    self.assertEqual(proxy_ep._hostStr, "proxy.com")
builtins.AttributeError: 'HostnameEndpoint' object has no attribute '_hostStr'

tests.http.test_proxyagent.MatrixFederationAgentTests.test_proxy_with_http_scheme
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/nix/store/c9m6yd8fg1flz2j5r4bif1ib5j20a0cy-python3-3.12.8/lib/python3.12/unittest/mock.py", line 1861, in _inner
    return f(*args, **kw)
  File "/build/source/tests/http/test_proxyagent.py", line 857, in test_proxy_with_no_scheme
    self.assertEqual(proxy_ep._hostStr, "proxy.com")
builtins.AttributeError: 'HostnameEndpoint' object has no attribute '_hostStr'

tests.http.test_proxyagent.MatrixFederationAgentTests.test_proxy_with_no_scheme
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/nix/store/c9m6yd8fg1flz2j5r4bif1ib5j20a0cy-python3-3.12.8/lib/python3.12/unittest/mock.py", line 1861, in _inner
    return f(*args, **kw)
  File "/build/source/tests/http/test_proxyagent.py", line 876, in test_proxy_with_https_scheme
    self.assertEqual(proxy_ep._wrappedEndpoint._hostStr, "proxy.com")
builtins.AttributeError: 'HostnameEndpoint' object has no attribute '_hostStr'

tests.http.test_proxyagent.MatrixFederationAgentTests.test_proxy_with_https_scheme
-------------------------------------------------------------------------------
Ran 3914 tests in 210.400s

FAILED (skips=181, errors=3, successes=3730)
```

(That's with a workaround for the breakage in the initial report, so that's still present but doesn't appear here.)

</details>
