### ISSUE TITLE
Tensorflow (python 2.7) breaks at runtime if listed after protobuf in buildInputs

### ISSUE THREAD

**Issue by traleig1** [NixOS/nixpkgs#37609]
## Issue description
Tensorflow fails at runtime if `protobuf` and `tensorflow` are listed in alphabetical order in `buildInputs`, giving the error `TypeError: __init__() got an unexpected keyword argument 'syntax'` (full error below).

Changing the order of `tensorflow` and `protobuf`, so that tensorflow comes first, resolves the issue.

### Steps to reproduce
On nixpkgs `17.09.3129.1dcd022f01b`, using this shell.nix file:
```
{ pkgs ? import <nixpkgs> {} }:
  with pkgs;
  python27Packages.buildPythonApplication {
    name = "test";
    buildInputs =  (with python27Packages; [
      protobuf
      tensorflow
   ]);
 }
```
Run the following commands:
```
echo 'import tensorflow' > test.py
nix-shell --pure
python test.py
````

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.85, NixOS, 17.09.3129.1dcd022f01b (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```
Full Error:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import tensorflow
  File "/nix/store/cakkcf60mkjf5kifxnwvyaxkkjwmykwr-python2.7-tensorflow-1.1.0/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/nix/store/cakkcf60mkjf5kifxnwvyaxkkjwmykwr-python2.7-tensorflow-1.1.0/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 54, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/nix/store/cakkcf60mkjf5kifxnwvyaxkkjwmykwr-python2.7-tensorflow-1.1.0/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/nix/store/cakkcf60mkjf5kifxnwvyaxkkjwmykwr-python2.7-tensorflow-1.1.0/lib/python2.7/site-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/nix/store/cakkcf60mkjf5kifxnwvyaxkkjwmykwr-python2.7-tensorflow-1.1.0/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/nix/store/cakkcf60mkjf5kifxnwvyaxkkjwmykwr-python2.7-tensorflow-1.1.0/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/nix/store/cakkcf60mkjf5kifxnwvyaxkkjwmykwr-python2.7-tensorflow-1.1.0/lib/python2.7/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"m\n\x0eResourceHandle\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB4\n\x18org.tensorflow.frameworkB\x13ResourceHandleProtoP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

**Comment by FRidh** [comment]
cc @abbradar @jyp

**Comment by abbradar** [comment]
That's most likely because Tensorflow includes its own build of Protobuf, and `PYTHONPATH` interferes with that. I'm not yet sure what exactly happens, will try to investigate -- but most likely there's no simple fix.
