### ISSUE TITLE
go: "TestWritevError" hangs on some machines

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#37704]
## Issue description

Just to keep track, I will investigate it further.

On some machines building ```go_1_9``` and ```go_1_10``` hang when performing "net" test.
On other machines there is no problem.

### Steps to reproduce

```
nix-build -E "(import <nixpkgs> {}).go_1_9"
```

**Comment by volth** [comment]
Stacktrace:

```
panic: test timed out after 9m0s

goroutine 1764 [running]:
testing.startAlarm.func1()
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:1145 +0xf9
created by time.goFunc
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive, 8 minutes]:
testing.(*T).Run(0xc420114000, 0x68352c, 0xf, 0x692798, 0x484401)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc420114000)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc420114000, 0xc420065dc0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc4200a6260, 0x7c4dc0, 0xc1, 0xc1, 0x7ffff7fb26c8)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420065f18, 0x608091)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:921 +0x111
net.TestMain(0xc420065f18)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/main_test.go:50 +0x39
main.main()
        net/_test/_testmain.go:492 +0xdb

goroutine 1687 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc4204082d0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestAcceptTimeoutMustNotReturn(0xc4204082d0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:258 +0x43
testing.tRunner(0xc4204082d0, 0x691e00)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1686 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc4204081e0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestAcceptTimeoutMustReturn(0xc4204081e0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:212 +0x43
testing.tRunner(0xc4204081e0, 0x691e10)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 208 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc4203a01e0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestCloseUnblocksRead(0xc4203a01e0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/net_test.go:503 +0x2b
testing.tRunner(0xc4203a01e0, 0x691e90)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1762 [IO wait, 8 minutes]:
internal/poll.runtime_pollWait(0x7ffff7f56c70, 0x77, 0xc420165500)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4203dc718, 0x77, 0xc420165500, 0xc420037300, 0xc420054d60)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitWrite(0xc4203dc718, 0x0, 0xc420320000, 0x3fe)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/internal/poll/fd_poll_runtime.go:94 +0x3d
internal/poll.(*FD).Writev(0xc4203dc700, 0xc420296ba0, 0x0, 0x0, 0x0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/internal/poll/writev.go:68 +0x3f2
net.(*netFD).writeBuffers(0xc4203dc700, 0xc420296ba0, 0x6000, 0xc420054e10, 0x4102ad)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/writev_unix.go:26 +0x3b
net.(*conn).writeBuffers(0xc42009a130, 0xc420296ba0, 0x0, 0x0, 0x0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/writev_unix.go:18 +0x56
net.(*Buffers).WriteTo(0xc420296ba0, 0x7a2ce0, 0xc42009a130, 0x7a2ce0, 0xc42009a130, 0x400)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/net.go:636 +0x1b4
net.TestWritevError(0xc420408f00)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/writev_test.go:223 +0x461
testing.tRunner(0xc420408f00, 0x692798)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1698 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc420120c30)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestReadWriteDeadlineRace(0xc420120c30)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:1006 +0x40
testing.tRunner(0xc420120c30, 0x692470)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1681 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc420120b40)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestReadWriteProlongedTimeout(0xc420120b40)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:926 +0x40
testing.tRunner(0xc420120b40, 0x692488)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1675 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc4201204b0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestReadTimeoutFluctuation(0xc4201204b0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:673 +0x43
testing.tRunner(0xc4201204b0, 0x692400)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1678 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc420120780)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestVariousDeadlines(0xc420120780)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:781 +0x2b
testing.tRunner(0xc420120780, 0x692750)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1677 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc420120690)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestWriteTimeoutFluctuation(0xc420120690)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:739 +0x43
testing.tRunner(0xc420120690, 0x692760)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1674 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc4201203c0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestWriteToTimeout(0xc4201203c0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:620 +0x43
testing.tRunner(0xc4201203c0, 0x692780)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1676 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc4201205a0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestReadFromTimeoutFluctuation(0xc4201205a0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:706 +0x43
testing.tRunner(0xc4201205a0, 0x6923f0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1673 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc4201202d0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestWriteTimeoutMustNotReturn(0xc4201202d0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:549 +0x43
testing.tRunner(0xc4201202d0, 0x692770)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1672 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc4201201e0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestWriteTimeout(0xc4201201e0)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:506 +0x43
testing.tRunner(0xc4201201e0, 0x692778)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de

goroutine 1669 [chan receive, 8 minutes]:
testing.(*T).Parallel(0xc420120000)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:677 +0x127
net.TestReadTimeoutMustNotReturn(0xc420120000)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/net/timeout_test.go:363 +0x43
testing.tRunner(0xc420120000, 0x692410)
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /nix/store/0p2qh5w7kb1ylwd7v9vi7y5vd7asya2r-go-1.9.4/share/go/src/testing/testing.go:789 +0x2de
FAIL    net     540.010s

```
