### ISSUE TITLE
chromium crashes on copy (ctrl + c)

### ISSUE THREAD

**Issue by MasseGuillaume** [NixOS/nixpkgs#38464]
## Issue description

chromium crashes when copying text

### Steps to reproduce

select some text
hit ctrl + c or right click + copy
tab crashes with: Aw, Snap!

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3222.21693048d72 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(gui): `""`
 - channels(root): `"nixos-17.09.3222.21693048d72"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

Chromium: Version 65.0.3325.162 (Developer Build) (64-bit)

**Comment by Mic92** [comment]
Please put:

```nix
systemd.coredump.enable = true;
environment.systemPackages = [
  gdb
];
```

into `configuration.nix`

Then reproduce the crash and run:

```console
$ coredumpctl gdb
....
# type bt
(gdb) bt 
Using host libthread_db library "/nix/store/84h2zni7h805k0i1ys2bba3dsp1cqnhh-glibc-2.26-131/lib/libthread_db.so.1".
Core was generated by `/nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f16485a483d in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
[Current thread is 1 (Thread 0x7f16385f9700 (LWP 10824))]
(gdb) bt
#0  0x00007f16485a483d in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#1  0x00007f16485b6769 in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#2  0x00007f16484e5de9 in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#3  0x00007f16484e59f4 in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#4  0x00007f16484e541d in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#5  0x00007f164851beb1 in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#6  0x00007f164865b222 in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#7  0x00007f1648c8429a in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#8  0x00007f16580af2a7 in start_thread ()
   from /nix/store/84h2zni7h805k0i1ys2bba3dsp1cqnhh-glibc-2.26-131/lib/libpthread.so.0
#9  0x00007f16570f757f in clone () from /nix/store/84h2zni7h805k0i1ys2bba3dsp1cqnhh-glibc-2.26-131/lib/libc.so.6
(gdb) bt
#0  0x00007f16485a483d in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#1  0x00007f16485b6769 in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#2  0x00007f16484e5de9 in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#3  0x00007f16484e59f4 in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#4  0x00007f16484e541d in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#5  0x00007f164851beb1 in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#6  0x00007f164865b222 in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#7  0x00007f1648c8429a in ?? ()
   from /nix/store/57xcrd8bzdr2ncxs30xp2vyannlyb9nm-firefox-release-bin-unwrapped-59.0.1/usr/lib/firefox-bin-59.0.1/libxul.so
#8  0x00007f16580af2a7 in start_thread ()
   from /nix/store/84h2zni7h805k0i1ys2bba3dsp1cqnhh-glibc-2.26-131/lib/libpthread.so.0
#9  0x00007f16570f757f in clone () from /nix/store/84h2zni7h805k0i1ys2bba3dsp1cqnhh-glibc-2.26-131/lib/libc.so.6
```

(Under the assumption that it throws a coredump)

**Comment by Mic92** [comment]
Maybe this gives some insights, but I cannot promise this.

**Comment by 7c6f434c** [comment]
I think it is a duplicate of #37314

**Comment by MasseGuillaume** [comment]
@7c6f434c yup, closing.
