### ISSUE TITLE
Mongodb segfaults after channel update (18.03)

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#39816]
## Issue description
Yesterday I set up a VM with Nixos 18.03. Today I configured some services and rebuild the system several times. I did execute a `nix-channel --update` and did another `nixos-rebuild switch`. 

To reproduce the issue I booted into an older (working) version and did
```
[root@graylog:~]# nixos-version 
18.03.131807.489a14add9a (Impala)

[root@graylog:~]# 

[root@graylog:~]# nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131807.489a14add9a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`


[root@graylog:~]# nixos-rebuild switch
building Nix...
building the system configuration...
updating GRUB 2 menu...
stopping the following units: audit.service, fail2ban.service, kmod-static-nodes.service, mongodb.service, network-local-commands.service, network-setup.service, nix-daemon.service, nix-daemon.socket, nscd.service, stunnel.service, systemd-modules-load.service, systemd-sysctl.service, systemd-timesyncd.service, systemd-tmpfiles-clean.timer, systemd-tmpfiles-setup-dev.service, systemd-udev-trigger.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, systemd-udevd.service
NOT restarting the following changed units: getty@tty1.service, systemd-journal-flush.service, systemd-logind.service, systemd-random-seed.service, systemd-remount-fs.service, systemd-tmpfiles-setup.service, systemd-update-utmp.service, systemd-user-sessions.service, user@1000.service
activating the configuration...
setting up /etc...
restarting systemd...
setting up tmpfiles
reloading the following units: dbus.service, dev-hugepages.mount, dev-mqueue.mount, firewall.service, sys-kernel-debug.mount
restarting the following units: dhcpcd.service, nginx.service, sshd.service, systemd-journald.service
starting the following units: audit.service, fail2ban.service, kmod-static-nodes.service, mongodb.service, network-local-commands.service, network-setup.service, nix-daemon.socket, nscd.service, stunnel.service, systemd-modules-load.service, systemd-sysctl.service, systemd-timesyncd.service, systemd-tmpfiles-clean.timer, systemd-tmpfiles-setup-dev.service, systemd-udev-trigger.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket
Job for mongodb.service failed because a fatal signal was delivered to the control process.
See "systemctl status mongodb.service" and "journalctl -xe" for details.
the following new units were started: elasticsearch.service, graylog.service
warning: the following units failed: mongodb.service

● mongodb.service - MongoDB server
   Loaded: loaded (/nix/store/1b2fawkp2yp4c4m3kq0fjh255f41yz5p-unit-mongodb.service/mongodb.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Tue 2018-05-01 15:00:48 UTC; 2s ago
  Process: 3550 ExecStart=/nix/store/s2f7xpsm177d1gn75ybqyiad7nb27frx-mongodb-3.4.10/bin/mongod --config /nix/store/2g7lwryjpimw3s35mjm2mc2mzimhv507-mongodb.conf --fork --pidfilepath /var/run/mongodb.pid (code=killed, signal=SEGV)
  Process: 3527 ExecStartPre=/nix/store/pm682q401j9h013y9hqkfjs3xs5m8kja-unit-script/bin/mongodb-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 2375 (code=exited, status=0/SUCCESS)

May 01 15:00:48 graylog systemd[1]: Starting MongoDB server...
May 01 15:00:48 graylog systemd[1]: mongodb.service: Control process exited, code=killed status=11
May 01 15:00:48 graylog systemd[1]: mongodb.service: Failed with result 'signal'.
May 01 15:00:48 graylog systemd[1]: Failed to start MongoDB server.
warning: error(s) occurred while switching to the new configuration

[root@graylog:~]# nix^C

[root@graylog:~]# nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.132192.ce0d9d638de (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`


[root@graylog:~]# 

```

## Technical details
Working: 
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131807.489a14add9a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

Broken:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.132192.ce0d9d638de (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by fadenb** [comment]
Some more debug info
```
Reading symbols from /nix/store/s2f7xpsm177d1gn75ybqyiad7nb27frx-mongodb-3.4.10/bin/mongod...(no debugging symbols found)...done.
(gdb) r
Starting program: /nix/store/s2f7xpsm177d1gn75ybqyiad7nb27frx-mongodb-3.4.10/bin/mongod 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7de36f3 in _dl_relocate_object () from /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/ld-linux-x86-64.so.2
(gdb) bt full
#0  0x00007ffff7de36f3 in _dl_relocate_object () from /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/ld-linux-x86-64.so.2
No symbol table info available.
#1  0x00007ffff7ddbefa in dl_main () from /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/ld-linux-x86-64.so.2
No symbol table info available.
#2  0x00007ffff7df0579 in _dl_sysdep_start () from /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/ld-linux-x86-64.so.2
No symbol table info available.
#3  0x00007ffff7dd9d4a in _dl_start () from /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/ld-linux-x86-64.so.2
No symbol table info available.
#4  0x00007ffff7dd8ea8 in _start () from /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/ld-linux-x86-64.so.2
No symbol table info available.
#5  0x0000000000000001 in ?? ()
No symbol table info available.
#6  0x00007fffffffe0af in ?? ()
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) quit
```

**Comment by fadenb** [comment]
I can no longer reproduce the issue since I trashed the server and set it up again?
