### ISSUE TITLE
matrix-synapse module: Problematic default config value for url_preview_url_blacklist

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#40017]
## Issue description
services.matrix-synapse.url_preview_url_blacklist default value causes previews to fail.

### Steps to reproduce

* `services.matrix-synapse.enable = true;` + the usual homeserver config
* `services.matrix-synapse.url_preview_enabled = true;`
* Do not configure `services.matrix-synapse.url_preview_url_blacklist` (so that the default value is used)
* Post URL into a preview enabled room
* Find similar error in synapse log:
```
synapse.http.server: [GET-1095] Failed handle request synapse.rest.media.v1.preview_url_resource._async_render_GET on <synapse.rest.media.v1.preview_url_resource.PreviewUrlResource instance at 0x7f2dcdf6db90>: <XForwardedForRequest at 0x7f2d8c281518 method=GET uri=/_matrix/media/r0/preview_url?url=http%3A%2F%2Fneverssl.com&ts=1525558276495 clientproto=HTTP/1.0 site=8008>: Traceback (most recent call last):
                                      File "/nix/store/jjv1c7jjrr44h620crl6hcjyl7gb9s4r-python2.7-Twisted-17.9.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
                                        return _inlineCallbacks(None, gen, Deferred())
                                      File "/nix/store/jjv1c7jjrr44h620crl6hcjyl7gb9s4r-python2.7-Twisted-17.9.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
                                        result = g.send(result)
                                      File "/nix/store/h86vgsar8fl17psn1wmsc4qywzwf7lmn-matrix-synapse-0.28.1/lib/python2.7/site-packages/synapse/http/server.py", line 170, in wrapped_request_handler
                                        yield request_handler(self, request)
                                      File "/nix/store/jjv1c7jjrr44h620crl6hcjyl7gb9s4r-python2.7-Twisted-17.9.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
                                        return _inlineCallbacks(None, gen, Deferred())
                                    --- <exception caught here> ---
                                      File "/nix/store/jjv1c7jjrr44h620crl6hcjyl7gb9s4r-python2.7-Twisted-17.9.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
                                        result = g.send(result)
                                      File "/nix/store/h86vgsar8fl17psn1wmsc4qywzwf7lmn-matrix-synapse-0.28.1/lib/python2.7/site-packages/synapse/rest/media/v1/preview_url_resource.py", line 110, in _async_render_GET
                                        pattern = entry[attrib]
                                    exceptions.TypeError: string indices must be integers, not str
```

The option defaults to `[ "127.0.0.0/8" "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" "169.254.0.0/16" ]`.
Were those values intended as default for the `url_preview_ip_range_blacklist` option?

Excerpt from a working configuration:
```nix
      url_preview_enabled = true;
      url_preview_url_blacklist = [ ];
      url_preview_ip_range_blacklist = ["127.0.0.0/8" "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" "169.254.0.0/16" ];
```

/cc @eqyiel, @Ralith (as you discussed the security implications in #20609)

**Comment by Ralith** [comment]
Seems like a good bet.
