### ISSUE TITLE
web-ext does not work

### ISSUE THREAD

**Issue by mt-caret** [NixOS/nixpkgs#40271]
## Issue description

Attempting to run web-ext results in a TypeError.

### Steps to reproduce

```
$ nix-shell -p nodePackages.web-ext --run 'web-ext --version'
/nix/store/ya9dwhy7xdckhpfgax59bfxc0lw10wyb-node-web-ext-2.6.0/lib/node_modules/web-ext/node_modules/chalk/index.js:72
ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
                                                                         ^
TypeError: Cannot read property 'close' of undefined
    at Object.<anonymous> (/nix/store/ya9dwhy7xdckhpfgax59bfxc0lw10wyb-node-web-ext-2.6.0/lib/node_modules/web-ext/node_modules/chalk/index.js:72:74)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/nix/store/ya9dwhy7xdckhpfgax59bfxc0lw10wyb-node-web-ext-2.6.0/lib/node_modules/web-ext/node_modules/pino/pretty.js:5:13)
    at Module._compile (module.js:577:32)
```

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.14.38, NixOS, 18.03.132229.7cbf6ca1c84 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6148_a4aac7f`
 - channels(root): `"nixos-18.03.132275.2352d46904d"`
 - channels(delta): `"nixpkgs-18.03.132275.2352d46904d, nixpkgs-unstable-18.09pre139198.9d0b6b9dfc9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by mt-caret** [comment]
I just tried adding web-ext to nodePackages_8_x, but got the same error:
```
$ nix-build -A nodePackages_8_x.web-ext
...
$ result/bin/web-ext
/nix/store/msi02d29lp8qcbksj52mynbgpxj0m6lz-node-web-ext-2.6.0/lib/node_modules/web-ext/node_modules/chalk/index.js:72
ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
                                                                          ^
TypeError: Cannot read property 'close' of undefined
    at Object.<anonymous> (/nix/store/msi02d29lp8qcbksj52mynbgpxj0m6lz-node-web-ext-2.6.0/lib/node_modules/web-ext/node_modules/chalk/index.js:72:75)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/nix/store/msi02d29lp8qcbksj52mynbgpxj0m6lz-node-web-ext-2.6.0/lib/node_modules/web-ext/node_modules/pino/pretty.js:5:13)
    at Module._compile (module.js:652:30)
```

**Comment by prusnak** [comment]
@mt-caret is this still an issue?

**Comment by mt-caret** [comment]
I can confirm that web-ext works as expected (on nixos-20.03), closing.
