### ISSUE TITLE
Atom: Failed to spawn command

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#40715]
## Issue description

Atom editor can't execute external command.

### Steps to reproduce

1. install atom with nix
1. install go with nix
2. install [go-imports](https://atom.io/packages/go-imports) atom package
3. install `goimports` like described in readme
4. i had to edit my `~/.bashrc` to be able to run it in terminal

```
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
```

6. hit <kbd>STRG</kbd>+<kbd>SHIFT</kbd>+<kbd>I</kbd> while go source code is opened in atom to run goimports
7. get this error

![screenshot from 2018-05-18 09-00-27](https://user-images.githubusercontent.com/91113/40220817-c72f5a86-5a7a-11e8-96f8-4a3cb521b157.png)

```
Uncaught Error: Failed to spawn command `goimports`. Make sure `goimports` is installed and on your PATH
    at BufferedProcess.handleError (/nix/store/snwy743aa4q0y7dll09bzvvzjvf8daas-atom-1.25.1/share/atom/resources/app/src/buffered-process.js:316:21)
    at ChildProcess.process.on (/nix/store/snwy743aa4q0y7dll09bzvvzjvf8daas-atom-1.25.1/share/atom/resources/app/src/buffered-process.js:302:18)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.40, NixOS, 18.03.132336.ef74cafd3e5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.03.132336.ef74cafd3e5, nixos-hardware, unstable-18.09pre133640.ea145b68a01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by davidak** [comment]
I can still reproduce this problem.

cc maintainer @Synthetica9 @ysndr

Atom 1.30.0

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.84, NixOS, 18.09.1446.db561c90ef3 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.09.1446.db561c90ef3, nixos-hardware, nixos-unstable-19.03pre159472.80738ed9dc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FliegendeWurst** [comment]
Atom was removed in #258440.
