### ISSUE TITLE
setuptools-scm was unable to detect version

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#41136]
## Issue description
I am trying to bump a python package. I switched the source from pypi to github in order to get the latest patch but then creating the python environment python.withPackages(ps: [ ps.myPackage]), it triggers 
```
these derivations will be built:
  /nix/store/n9rybrvj8yrgsjjzqjkk1sn3wh1a3igw-python2.7-PyBindGen-0.18.0.drv
  /nix/store/gn1mfm69a2s6yv8rnwb74wp4cd46lmz1-python-2.7.14-env.drv
building '/nix/store/n9rybrvj8yrgsjjzqjkk1sn3wh1a3igw-python2.7-PyBindGen-0.18.0.drv'...
unpacking sources
unpacking source archive /nix/store/hp6zhvyla76c5lsrqwc2my7d3g7sl8mb-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/wutils.py
patching sources
configuring
building
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 27, in <module>
    'Programming Language :: Python :: 3',
  File "/nix/store/hf7ls1fdzs5qpr1kl083agyhhv15wfa7-python2.7-bootstrapped-pip-9.0.3/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/l9j2jsc9flrbmpf799nw9wdq59gpwms8-python-2.7.14/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/nix/store/hf7ls1fdzs5qpr1kl083agyhhv15wfa7-python2.7-bootstrapped-pip-9.0.3/lib/python2.7/site-packages/setuptools/dist.py", line 372, in __init__
    _Distribution.__init__(self, attrs)
  File "/nix/store/l9j2jsc9flrbmpf799nw9wdq59gpwms8-python-2.7.14/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/nix/store/hf7ls1fdzs5qpr1kl083agyhhv15wfa7-python2.7-bootstrapped-pip-9.0.3/lib/python2.7/site-packages/setuptools/dist.py", line 528, in finalize_options
    ep.load()(self, ep.name, value)
  File "/nix/store/npprm7wpsh1913zvn7xplhxf9vi2slds-python2.7-setuptools_scm-1.17.0/lib/python2.7/site-packages/setuptools_scm/integration.py", line 22, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/nix/store/npprm7wpsh1913zvn7xplhxf9vi2slds-python2.7-setuptools_scm-1.17.0/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 119, in get_version
    parsed_version = _do_parse(root, parse)
  File "/nix/store/npprm7wpsh1913zvn7xplhxf9vi2slds-python2.7-setuptools_scm-1.17.0/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 97, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % root)
LookupError: setuptools-scm was unable to detect version for '/build/source'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
note: keeping build directory '/tmp/nix-build-python2.7-PyBindGen-0.18.0.drv-3'

```
I tried replacing the url with the one given  to no avail (with fetchgit and builtins.fetchGit) 
When googling for the error, it seemed like a bug in setuptools_scm . The version 2.1.0 is out https://github.com/pypa/setuptools_scm while nixpkgs contains 1.17.0. Any reason not to bump it ?

### Steps to reproduce
create a python environment with pybindgen and override its src with
```
  src = fetchFromGitHub {
    owner = "gjcarneiro";
    repo = "pybindgen";
    rev = "ef30ba23dd23afe41aef5bc9aced71c112ccc22e";
    sha256 = "1x6paa2r7brmfi4wpx9vvjs64n71k4viy8rq91x9ri0fss1666vj";
  };

```

## Technical details

nixos-unstable 5da85431fb1df4fb3ac36730b2591ccc9bdf5c21

**Comment by dotlambda** [comment]
> The version 2.1.0 is out https://github.com/pypa/setuptools_scm while nixpkgs contains 1.17.0. Any reason not to bump it ?

The bump will be hopefully be included in the next (automatic) update of the python package set. However, such an update only makes sense as soon the staging branch is merged into master.

> I tried replacing the url with the one given to no avail (with fetchgit and builtins.fetchGit)

You'll probably have to use `fetchgit` with `leaveDotGit = true`. But I'm wondering why you don't simply stick with `fetchPypi`.

**Comment by teto** [comment]
seems like I had to add git as a buildinput too.

I realized the ns3 python bindings package was broken, but to fix it I need a feature which is not available in the pypi version, only the github one. I can wait for the feature to be on pypi before sending a PR but I wanted to confirm it worked first.

Closing since I was able to get rid of the error. Thanks for the advice !

**Comment by dotlambda** [comment]
So the solution included both, `leaveDotGit = true` and adding `git` to `natriveBuildInputs`?

**Comment by teto** [comment]
I think so, seems like setuptools use the git folder to generate/fetch the version.

As a follow up this breaks ns3 capability to check the version  number so I am not quite there yet :'(
```
Checking for python module 'pybindgen'                             : 0.0.post1+gef30ba2.d20180527 
Checking for pybindgen version                                     : 0.0.post1+gef30ba2.d20180527 
Traceback (most recent call last):
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 110, in waf_entry_point
    run_commands()
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 171, in run_commands
    ctx=run_command(cmd_name)
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 162, in run_command
    ctx.execute()
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Configure.py", line 87, in execute
    super(ConfigurationContext,self).execute()
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/home/teto/scratch/source/wscript", line 464, in configure
    conf.recurse('bindings/python')
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/home/teto/scratch/source/bindings/python/wscript", line 198, in configure
    if not (split_version(pybindgen_version) >= split_version(REQUIRED_PYBINDGEN_VERSION)):
  File "/home/teto/scratch/source/bindings/python/wscript", line 75, in split_version
    return (int(ver[0]), int(ver[1]), int(ver[2]), int(ver[3].split('post')[1]))
ValueError: invalid literal for int() with base 10: 'post1'

```

**Comment by deliciouslytyped** [comment]
The misleading error message may be resolved in https://github.com/pypa/setuptools_scm/issues/465 .

**Comment by L-as** [comment]
For future readers: Something like `sed -i -e 's/use_scm_version=scm_version..,//g' setup.py` in `prePatch` is likely the easiest way to solve this without depending on the repository being present in the sandbox.

**Comment by dotlambda** [comment]
I suggest using `SETUPTOOLS_SCM_PRETEND_VERSION`.

**Comment by raboof** [comment]
Thanks! I ran into this when a module started using setuptools-scm in an upgrade, so in my case besides adding `SETUPTOOLS_SCM_PRETEND_VERSION = version` I also had to add `nativeBuildInputs = [ setuptools-scm ];`.
