### ISSUE TITLE
trash-cli cannot find libc.so outside nix-shell

### ISSUE THREAD

**Issue by mnacamura** [NixOS/nixpkgs#41637]
### Steps to reproduce

```
% touch aaaaa                                                                                            [~]
% nix-shell -p trash-cli --run 'trash aaaaa'                                                             [~]
% nix-shell -p trash-cli --run 'trash-list'                                                              [~]
2018-06-08 01:41:21 /home/mnacamura/aaaaa
% touch bbbbb                                                                                            [~]
% nix build -f '<nixpkgs>' trash-cli                                                                     [~]
% ./result/bin/trash bbbbb                                                                               [~]
% ./result/bin/trash-list                                                                                [~]
2018-06-08 01:41:21 /home/mnacamura/aaaaa
2018-06-08 01:41:47 /home/mnacamura/bbbbb
Traceback (most recent call last):
  File "/nix/store/yzlsskpvsadglqhvagyy1k6n57d322vr-trash-cli-0.17.1.14/bin/..trash-list-wrapped-wrapped", line 6, in <module>
    sys.exit(main())
  File "/nix/store/yzlsskpvsadglqhvagyy1k6n57d322vr-trash-cli-0.17.1.14/lib/python3.6/site-packages/trashcli/cmds.py", line 51, in list
    ).run(*sys.argv)
  File "/nix/store/yzlsskpvsadglqhvagyy1k6n57d322vr-trash-cli-0.17.1.14/lib/python3.6/site-packages/trashcli/list.py", line 37, in run
    parse(argv)
  File "/nix/store/yzlsskpvsadglqhvagyy1k6n57d322vr-trash-cli-0.17.1.14/lib/python3.6/site-packages/trashcli/trash.py", line 110, in __call__
    self.default_action()
  File "/nix/store/yzlsskpvsadglqhvagyy1k6n57d322vr-trash-cli-0.17.1.14/lib/python3.6/site-packages/trashcli/list.py", line 51, in list_trash
    trashdirs.list_trashdirs()
  File "/nix/store/yzlsskpvsadglqhvagyy1k6n57d322vr-trash-cli-0.17.1.14/lib/python3.6/site-packages/trashcli/trash.py", line 151, in list_trashdirs
    self._for_each_volume_trashcan()
  File "/nix/store/yzlsskpvsadglqhvagyy1k6n57d322vr-trash-cli-0.17.1.14/lib/python3.6/site-packages/trashcli/trash.py", line 157, in _for_each_volume_trashcan
    for volume in self.mount_points():
  File "/nix/store/yzlsskpvsadglqhvagyy1k6n57d322vr-trash-cli-0.17.1.14/lib/python3.6/site-packages/trashcli/list_mount_points.py", line 5, in mount_points
    return list(mount_points_from_getmnt())
  File "/nix/store/yzlsskpvsadglqhvagyy1k6n57d322vr-trash-cli-0.17.1.14/lib/python3.6/site-packages/trashcli/list_mount_points.py", line 10, in mount_points_from_getmnt
    for elem in _mounted_filesystems_from_getmnt():
  File "/nix/store/yzlsskpvsadglqhvagyy1k6n57d322vr-trash-cli-0.17.1.14/lib/python3.6/site-packages/trashcli/list_mount_points.py", line 57, in _mounted_filesystems_from_getmnt
    libc = cdll.LoadLibrary(libc_name)
  File "/nix/store/rsa1rsd6c6szy0dmi61599b33aqiy269-python3-3.6.5/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/nix/store/rsa1rsd6c6szy0dmi61599b33aqiy269-python3-3.6.5/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/libc.so.6: cannot open shared object file: No such file or directory
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.0, NixOS, 18.09.git.4ec1edf (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre140920.5b468ea6b1d"`
 - channels(mnacamura): `"nixpkgs-18.09pre140731.c29d2fde74d"`
 - nixpkgs: `/home/mnacamura/repos/nixpkgs`

**Comment by matthewbauer** [comment]
Reverted https://github.com/NixOS/nixpkgs/commit/c923e938a3de8738ac881bd8762a18961aadc796 so hopefully it's fixed.

I was trying to get trash-cli to work on my mac - but for some reason python's find_library is broken and it requires that patch.

**Comment by mnacamura** [comment]
It works again. Thanks.
