### ISSUE TITLE
nixos-rebuild switch fails on cython?

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#42181]
## Issue description

(.text+0x3468): warning: the use of `tmpnam_r' is dangerous, better use `mkstemp'
/nix/store/nwsww2h72aa6040sg3yzprl9qrhkgymx-python-2.7.15/bin/../lib/python2.7/config/libpython2.7.a(posixmodule.o): In function `posix_tempnam':
(.text+0x53f): warning: the use of `tempnam' is dangerous, better use `mkstemp'
======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (c) and running fstring
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 1114, in run
    ext_so_path = self.runCompileTest()
  File "runtests.py", line 803, in runCompileTest
    self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)
  File "runtests.py", line 1038, in compile
    self._match_output(expected_errors, errors, tostderr)
  File "runtests.py", line 1084, in _match_output
    self.assertEqual(None, unexpected)
AssertionError: None != u"509:0: Expected path '//AddNode' not found in result tree"

======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (cpp) and running fstring
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 1114, in run
    ext_so_path = self.runCompileTest()
  File "runtests.py", line 803, in runCompileTest
    self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)
  File "runtests.py", line 1038, in compile
    self._match_output(expected_errors, errors, tostderr)
  File "runtests.py", line 1084, in _match_output
    self.assertEqual(None, unexpected)
AssertionError: None != u"509:0: Expected path '//AddNode' not found in result tree"

----------------------------------------------------------------------
Ran 10780 tests in 8492.292s

FAILED (errors=2, skipped=50)
Following tests excluded because of missing dependencies on your system:
   Cython.Coverage
   run.asyncio_generators
   run.coverage_api
   run.coverage_cmd
   run.coverage_nogil
   run.numpy_pythran
   run.py35_asyncio_async_def
~~~~~~~~~
unused_args.cpp:1275:18: warning: ‘PyObject* __pyx_f_11unused_args_c_unused_simple(PyObject*, PyObject*, PyObject*)’ defined but not used [-Wunused-function]
 static PyObject *__pyx_f_11unused_args_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ALL DONE
builder for '/nix/store/fcl49wccz1vdm925fnpc2y1icvh8bz9m-python2.7-Cython-0.28.3.drv' failed with exit code 1
cannot build derivation '/nix/store/ppj8qvj24p1qmz9wxpvyhb45kwqq9ka8-libplist-2.0.0.drv': 1 dependencies couldn't be built
building '/nix/store/rxq4ab0xzvpg1k9ddds4yd1scc333mf3-python3.6-PyQt-5.10.1.drv'...
cannot build derivation '/nix/store/a83adhm1xvgg67rfldghh5ycaaszpppj-libimobiledevice-1.2.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/15byjvj9c8kcvavj3lsv496pkvfcmw19-gvfs-1.36.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/7s4ar7yhpandkq9vy5fm1pmw8fvfyjl1-gvfs-1.36.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fyxqkdd8bzywzpm21w19irrlqcn0lmkn-etc-profile.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ary79kr7rpfy5n58k7ynnfaw4s160arh-etc-zshenv.drv': 1 dependencies couldn't be built
building '/nix/store/k0li7bjgq8nivjmzra8q1qqz5kwwq45l-qpdf-8.0.2.drv'...
building '/nix/store/mzp0wivmynpx5qr8b6fmhammwla7wk78-reload-container.drv'...
building '/nix/store/csldxmg1hid9q4bniln8ibzjhqkbj294-snmp.conf.drv'...
cannot build derivation '/nix/store/7wkqny74by4b3ll74vdp7fv8p0vipwvl-system-path.drv': 1 dependencies couldn't be built
building '/nix/store/wyzgb52lmixcskm97lyga0nq428i6scn-systemd-user.pam.drv'...
cannot build derivation '/nix/store/614kdfwxz7lm4jhqzw49yhf31636xx3w-nixos-system-nixos-18.09.git.42a88a4.drv': 1 dependencies couldn't be built
error: build of '/nix/store/614kdfwxz7lm4jhqzw49yhf31636xx3w-nixos-system-nixos-18.09.git.42a88a4.drv' failed

### Steps to reproduce

nixos-rebuild switch

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

these paths will be fetched (0.56 MiB download, 2.75 MiB unpacked):
  /nix/store/30fscxjwkzdrkmaa9x02ynkk63xwaaad-bash-interactive-4.4-p19-dev
  /nix/store/hyv6kgmqihysgki7m6pz0h0f7kn70h6g-bash-4.4-p19-dev
  /nix/store/l9a6jki6difa8z684j0lx82inyjk57dw-bash-4.4-p19-man
  /nix/store/ns477r8lqplyvwk64lahcvj78h3pwiz7-bash-4.4-p19-doc
  /nix/store/v33if8knlqv86931izhcg7z5sbxgbg8w-bash-4.4-p19-info
copying path '/nix/store/v33if8knlqv86931izhcg7z5sbxgbg8w-bash-4.4-p19-info' from 'https://cache.nixos.org'...
copying path '/nix/store/ns477r8lqplyvwk64lahcvj78h3pwiz7-bash-4.4-p19-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/hyv6kgmqihysgki7m6pz0h0f7kn70h6g-bash-4.4-p19-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/l9a6jki6difa8z684j0lx82inyjk57dw-bash-4.4-p19-man' from 'https://cache.nixos.org'...
copying path '/nix/store/30fscxjwkzdrkmaa9x02ynkk63xwaaad-bash-interactive-4.4-p19-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.8, NixOS, 18.09.git.ec709cf (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(milan): `"nixos-17.03pre96925.1c50bdd"`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by vcunat** [comment]
Hydra link: https://hydra.nixos.org/job/nixpkgs/trunk/python27Packages.cython.x86_64-linux

**Comment by dtzWill** [comment]
staging seems to have fixes for this, most recently: b9b18ded57842d24ef05bfe33aa7dba95b77babf but possibly a few others.

**Comment by tex** [comment]
This is on current master branch (nixpkgs).

**Comment by vcunat** [comment]
Yes, on staging fce640473 it succeeds for me locally.

**Comment by peti** [comment]
This error blocks a `nixos-unstable` channel update because it prevents `nixos.tests.gnome3` from building: https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents.

**Comment by vcunat** [comment]
@FRidh: perhaps we should revert beedfbea657 now on master and re-revert it on staging?

**Comment by tex** [comment]
Fixed. Thanks!
