### ISSUE TITLE
Scikit-learn build failed

### ISSUE THREAD

**Issue by haposik** [NixOS/nixpkgs#43466]
## Issue description
I am trying to build python36 interpreter with scikit-learn package in it, but it fails with this error: 
```
.................................................................
======================================================================
FAIL: sklearn.linear_model.tests.test_logistic.test_max_iter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/8wbvq1w96h4mmgrn0nxixlkmjd84biii-python3.6-nose-1.3.7/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/nix/store/a4hmi7338y3738lyklvps2ab687wypdm-python3.6-scikit-learn-0.19.1/lib/python3.6/site-packages/sklearn/utils/testing.py", line 291, in wrapper                                                                                                                             
    return fn(*args, **kwargs)
  File "/nix/store/a4hmi7338y3738lyklvps2ab687wypdm-python3.6-scikit-learn-0.19.1/lib/python3.6/site-packages/sklearn/linear_model/tests/test_logistic.py", line 1023, in test_max_iter                                                                                                   
    assert_equal(lr.n_iter_[0], max_iter)
AssertionError: 0 != 1
    '0 != 1' = '%s != %s' % _common_shorten_repr(0, 1)
    '0 != 1' = self._formatMessage('0 != 1', '0 != 1')
>>  raise self.failureException('0 != 1')


----------------------------------------------------------------------
Ran 8229 tests in 170.089s

FAILED (SKIP=62, failures=1)
builder for '/nix/store/j6q7i7vaynv4cfpq7rwqr3qng8w6yiw3-python3.6-scikit-learn-0.19.1.drv' failed with exit code 1
cannot build derivation '/nix/store/b8zf7b5hd3gzzc9xwrnn0pji5bz9rdi2-python3-3.6.5-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/b8zf7b5hd3gzzc9xwrnn0pji5bz9rdi2-python3-3.6.5-env.drv' failed
```

### Steps to reproduce
My default.nix:
```
with import <nixpkgs> {};

(let
  python = let
    packageOverrides = self: super: rec {
    };
  in pkgs.python3.override {inherit packageOverrides;};

in python.withPackages(ps: with ps; [
  scikitlearn
])).env
```

Just run `nix-shell` in dir with default.nix

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

- system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-130-generic, Ubuntu, 16.04.4 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(user): `"nixpkgs-18.09pre144939.14a9ca27e69"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`

**Comment by FRidh** [comment]
This is an upstream issue. Check whether upstream has fixed this. We could disable the test for now. If I recall correctly our `scikitlearn` expression is without maintainer. I suggest opening a PR to solve this.

**Comment by Ma27** [comment]
I stumbled upon this as well. I'll check if I can find an easy fix for this :)
