### ISSUE TITLE
notmuch and bindings to ruby

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#43965]
## Issue description

How to get / use notmuch bindings to ruby? I want to use notmuch plugin in vim which requires ruby binding.

### Steps to reproduce

```
> nix-shell -p ruby notmuch
> ruby -e 'require "notmuch"'
/nix/store/f3svdpbdciz3c91nc8bj8qi0adc6p5zl-ruby-2.4.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- notmuch (LoadError)
        from /nix/store/f3svdpbdciz3c91nc8bj8qi0adc6p5zl-ruby-2.4.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from -e:1:in `<main>'
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.2, NixOS, 18.09.git.c51ac5e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(milan): `"nixos-17.03pre96925.1c50bdd"`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by andir** [comment]
I also ran into this today. We are building the notmuch ruby binaries but we are never packaging them. They are just being discarded at the end of the build. I am not familiar with the ruby tooling to figure out how to install them properly. I can probably botcher it somehow...

**Comment by teto** [comment]
this was fixed recently
