### ISSUE TITLE
[fatal urgent buggy] nix openjdk 8 can't run on Linux  2.6.32-431.el6.x86_64

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nixpkgs#44070]
```

hi, i can't run nixpkgs jdk 8 on my redhat 6 server.

but it can run succesfullly on readhat 7.
when i use system jdk 8, it also can work well.

readhat 6 server is still main stream for our environment.

can you figure it how to run openjdk 8 on it?

[op@nn ~] uname -a
Linux nn 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux


[op@nn ~] cat  /home/op/my-env/nix.var/data/zookeeper-3.4.12/2181/zoo.cfg
tickTime=2000
initLimit=10
syncLimit=5
server.1=10.132.37.33:2888:3888
server.2=10.132.37.34:2888:3888
server.3=10.132.37.35:2888:3888
# server.1=zoo1:2888:3888
dataDir=/home/op/my-env/nix.var/data/zookeeper-3.4.12/2181
dataLogDir=/home/op/my-env/nix.var/log/zookeeper-3.4.12/2181
clientPort=2181
```

```shell
[op@nn ~] export JAVA_HOME=/nix/store/f6s6xd2cvcqhaw8i3hkb481ywdxn24l6-openjdk-8u172b11
[op@nn ~]  /home/op/my-env/nix.var/data/zookeeper-3.4.12/2181/../*/bin/zkServer.sh start-foreground /home/op/my-env/nix.var/data/zookeeper-3.4.12/2181/zoo.cfg
ZooKeeper JMX enabled by default
Using config: /home/op/my-env/nix.var/data/zookeeper-3.4.12/2181/zoo.cfg
Jul 25, 2018 9:24:27 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44296] throws
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)

Jul 25, 2018 9:24:27 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44296] throws
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)

Jul 25, 2018 9:24:27 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44296] throws
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)

Jul 25, 2018 9:24:27 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44296] throws
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)

Jul 25, 2018 9:24:27 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44296] throws
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)

Jul 25, 2018 9:24:27 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44296] throws
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)

Jul 25, 2018 9:24:27 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44296] throws
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)

Jul 25, 2018 9:24:27 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44296] throws
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)

Jul 25, 2018 9:24:27 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44296] throws
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)

Jul 25, 2018 9:24:27 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44296] throws
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)

Jul 25, 2018 9:24:27 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=44296] throws
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
        at java.lang.Thread.run(Thread.java:748)

2018-07-25 09:24:27,069 [myid:] - INFO  [main:QuorumPeerConfig@136] - Reading configuration from: /home/op/my-env/nix.var/data/zookeeper-3.4.12/2181/zoo.cfg
2018-07-25 09:24:27,078 [myid:] - INFO  [main:QuorumPeer$QuorumServer@184] - Resolved hostname: 10.132.37.35 to address: /10.132.37.35
2018-07-25 09:24:27,079 [myid:] - INFO  [main:QuorumPeer$QuorumServer@184] - Resolved hostname: 10.132.37.34 to address: /10.132.37.34
2018-07-25 09:24:27,079 [myid:] - INFO  [main:QuorumPeer$QuorumServer@184] - Resolved hostname: 10.132.37.33 to address: /10.132.37.33
2018-07-25 09:24:27,079 [myid:] - INFO  [main:QuorumPeerConfig@398] - Defaulting to majority quorums
2018-07-25 09:24:27,090 [myid:1] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
2018-07-25 09:24:27,090 [myid:1] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
2018-07-25 09:24:27,090 [myid:1] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
2018-07-25 09:24:27,107 [myid:1] - INFO  [main:QuorumPeerMain@130] - Starting quorum peer
Exception in thread "main" java.lang.ExceptionInInitializerError
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:69)
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
        at java.nio.channels.Selector.open(Selector.java:227)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.<clinit>(NIOServerCnxnFactory.java:48)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.zookeeper.server.ServerCnxnFactory.createFactory(ServerCnxnFactory.java:115)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:132)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:114)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:81)
Caused by: java.io.IOException: Function not implemented
        at sun.nio.ch.IOUtil.fdLimit(Native Method)
        at sun.nio.ch.EPollArrayWrapper.<clinit>(EPollArrayWrapper.java:73)
        ... 10 more

```

```shell
[op@nn ~] unset JAVA_HOME
[op@nn ~] which java
/usr/java/jdk1.8.0_60/bin/java
[op@nn ~] java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
[op@nn ~]  /home/op/my-env/nix.var/data/zookeeper-3.4.12/2181/../*/bin/zkServer.sh start-foreground /home/op/my-env/nix.var/data/zookeeper-3.4.12/2181/zoo.cfg
ZooKeeper JMX enabled by default
Using config: /home/op/my-env/nix.var/data/zookeeper-3.4.12/2181/zoo.cfg
2018-07-25 09:27:57,245 [myid:] - INFO  [main:QuorumPeerConfig@136] - Reading configuration from: /home/op/my-env/nix.var/data/zookeeper-3.4.12/2181/zoo.cfg
2018-07-25 09:27:57,256 [myid:] - INFO  [main:QuorumPeer$QuorumServer@184] - Resolved hostname: 10.132.37.35 to address: /10.132.37.35
2018-07-25 09:27:57,256 [myid:] - INFO  [main:QuorumPeer$QuorumServer@184] - Resolved hostname: 10.132.37.34 to address: /10.132.37.34
2018-07-25 09:27:57,257 [myid:] - INFO  [main:QuorumPeer$QuorumServer@184] - Resolved hostname: 10.132.37.33 to address: /10.132.37.33
2018-07-25 09:27:57,257 [myid:] - INFO  [main:QuorumPeerConfig@398] - Defaulting to majority quorums
2018-07-25 09:27:57,259 [myid:1] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
2018-07-25 09:27:57,260 [myid:1] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
2018-07-25 09:27:57,260 [myid:1] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
2018-07-25 09:27:57,269 [myid:1] - INFO  [main:QuorumPeerMain@130] - Starting quorum peer
2018-07-25 09:27:57,274 [myid:1] - INFO  [main:ServerCnxnFactory@117] - Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
2018-07-25 09:27:57,277 [myid:1] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
2018-07-25 09:27:57,287 [myid:1] - INFO  [main:QuorumPeer@1158] - tickTime set to 2000
2018-07-25 09:27:57,287 [myid:1] - INFO  [main:QuorumPeer@1204] - initLimit set to 10
2018-07-25 09:27:57,288 [myid:1] - INFO  [main:QuorumPeer@1178] - minSessionTimeout set to -1
2018-07-25 09:27:57,288 [myid:1] - INFO  [main:QuorumPeer@1189] - maxSessionTimeout set to -1
2018-07-25 09:27:57,294 [myid:1] - INFO  [main:QuorumPeer@1467] - QuorumPeer communication is not secured!
2018-07-25 09:27:57,295 [myid:1] - INFO  [main:QuorumPeer@1496] - quorum.cnxn.threads.size set to 20
2018-07-25 09:27:57,296 [myid:1] - INFO  [main:FileSnap@86] - Reading snapshot /home/op/my-env/nix.var/data/zookeeper-3.4.12/2181/version-2/snapshot.1000000a4
2018-07-25 09:27:57,305 [myid:1] - INFO  [ListenerThread:QuorumCnxManager$Listener@736] - My election bind port: /10.132.37.33:3888
2018-07-25 09:27:57,311 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumPeer@909] - LOOKING
2018-07-25 09:27:57,312 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:FastLeaderElection@813] - New election. My id =  1, proposed zxid=0x1000000a4
2018-07-25 09:27:57,314 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@595] - Notification: 1 (message format version), 1 (n.leader), 0x1000000a4 (n.zxid), 0x1 (n.round), LOOKING (n.state), 1 (n.sid), 0x1 (n.peerEpoch) LOOKING (my state)
2018-07-25 09:27:57,318 [myid:1] - INFO  [WorkerSender[myid=1]:QuorumCnxManager@347] - Have smaller server identifier, so dropping the connection: (2, 1)
2018-07-25 09:27:57,318 [myid:1] - INFO  [/10.132.37.33:3888:QuorumCnxManager$Listener@743] - Received connection request /10.132.37.34:33100
2018-07-25 09:27:57,318 [myid:1] - INFO  [WorkerSender[myid=1]:QuorumCnxManager@347] - Have smaller server identifier, so dropping the connection: (3, 1)
2018-07-25 09:27:57,319 [myid:1] - INFO  [/10.132.37.33:3888:QuorumCnxManager$Listener@743] - Received connection request /10.132.37.35:58483
2018-07-25 09:27:57,320 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@595] - Notification: 1 (message format version), 2 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LEADING (n.state), 2 (n.sid), 0x1 (n.peerEpoch) LOOKING (my state)
2018-07-25 09:27:57,320 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@595] - Notification: 1 (message format version), 2 (n.leader), 0x0 (n.zxid), 0x1 (n.round), FOLLOWING (n.state), 3 (n.sid), 0x1 (n.peerEpoch) LOOKING (my state)
2018-07-25 09:27:57,321 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@595] - Notification: 1 (message format version), 2 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LEADING (n.state), 2 (n.sid), 0x1 (n.peerEpoch) LOOKING (my state)
2018-07-25 09:27:57,321 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@595] - Notification: 1 (message format version), 2 (n.leader), 0x0 (n.zxid), 0x1 (n.round), FOLLOWING (n.state), 3 (n.sid), 0x1 (n.peerEpoch) LOOKING (my state)
2018-07-25 09:27:57,322 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumPeer@979] - FOLLOWING
2018-07-25 09:27:57,325 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Learner@86] - TCP NoDelay set to: true
2018-07-25 09:27:57,330 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:zookeeper.version=3.4.12-e5259e437540f349646870ea94dc2658c4e44b3b, built on 03/27/2018 03:55 GMT
2018-07-25 09:27:57,330 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:host.name=nn
2018-07-25 09:27:57,330 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.version=1.8.0_60
2018-07-25 09:27:57,330 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.vendor=Oracle Corporation
2018-07-25 09:27:57,330 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.home=/usr/java/jdk1.8.0_60/jre
2018-07-25 09:27:57,331 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.class.path=/home/op/my-env/nix.var/data/zookeeper-3.4.12/zookeeper-3.4.12/bin/../build/classes:/home/op/my-env/nix.var/data/zookeeper-3.4.12/zookeeper-3.4.12/bin/../build/lib/*.jar:/home/op/my-env/nix.var/data/zookeeper-3.4.12/zookeeper-3.4.12/bin/../lib/slf4j-log4j12-1.7.25.jar:/home/op/my-env/nix.var/data/zookeeper-3.4.12/zookeeper-3.4.12/bin/../lib/slf4j-api-1.7.25.jar:/home/op/my-env/nix.var/data/zookeeper-3.4.12/zookeeper-3.4.12/bin/../lib/netty-3.10.6.Final.jar:/home/op/my-env/nix.var/data/zookeeper-3.4.12/zookeeper-3.4.12/bin/../lib/log4j-1.2.17.jar:/home/op/my-env/nix.var/data/zookeeper-3.4.12/zookeeper-3.4.12/bin/../lib/jline-0.9.94.jar:/home/op/my-env/nix.var/data/zookeeper-3.4.12/zookeeper-3.4.12/bin/../lib/audience-annotations-0.5.0.jar:/home/op/my-env/nix.var/data/zookeeper-3.4.12/zookeeper-3.4.12/bin/../zookeeper-3.4.12.jar:/home/op/my-env/nix.var/data/zookeeper-3.4.12/zookeeper-3.4.12/bin/../src/java/lib/*.jar:/home/op/my-env/nix.var/data/zookeeper-3.4.12/zookeeper-3.4.12/bin/../conf:
2018-07-25 09:27:57,332 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2018-07-25 09:27:57,332 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.io.tmpdir=/tmp
2018-07-25 09:27:57,332 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:java.compiler=<NA>
2018-07-25 09:27:57,332 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:os.name=Linux
2018-07-25 09:27:57,332 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:os.arch=amd64
2018-07-25 09:27:57,332 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:os.version=2.6.32-431.el6.x86_64
2018-07-25 09:27:57,332 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:user.name=op
2018-07-25 09:27:57,332 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:user.home=/home/op
2018-07-25 09:27:57,332 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Environment@100] - Server environment:user.dir=/home/op
2018-07-25 09:27:57,334 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:ZooKeeperServer@173] - Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 datadir /home/op/my-env/nix.var/log/zookeeper-3.4.12/2181/version-2 snapdir /home/op/my-env/nix.var/data/zookeeper-3.4.12/2181/version-2
2018-07-25 09:27:57,335 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Follower@65] - FOLLOWING - LEADER ELECTION TOOK - 23
2018-07-25 09:27:57,336 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumPeer$QuorumServer@184] - Resolved hostname: 10.132.37.34 to address: /10.132.37.34
2018-07-25 09:27:57,340 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:Learner@332] - Getting a diff from the leader 0x1000000a4
^C[op@nn ~] 
```

**Comment by clojurians-org** [comment]
as i know, the following component all report this same error!
zookeeper-3.4.12
apache-kafka-2.12-1.1.0
elasticsearch-6.2.4

**Comment by clojurians-org** [comment]
how to do it? can you offer me more detail?
it''s the same error still
```shell
[op@cms ~] export LD_PRELOAD=/usr/lib64/libc.so
[op@cms ~] bash /nix/store/*-apache-kafka-2.12-1.1.0/bin/kafka-server-start.sh /home/op/my-env/nix.var/data/apache-kafka-2.12-1.1.0/9092/server.properties
ERROR: ld.so: object '/usr/lib64/libc.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/usr/lib64/libc.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/lib64/libc.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.

...
..
Caused by: java.io.IOException: Function not implemented
        at sun.nio.ch.IOUtil.fdLimit(Native Method)
        at sun.nio.ch.EPollArrayWrapper.<clinit>(EPollArrayWrapper.java:73)
        ... 23 more
[2018-07-26 09:12:50,198] INFO shutting down (kafka.server.KafkaServer)
[2018-07-26 09:12:50,200] WARN  (kafka.utils.CoreUtils$)
java.lang.NullPointerException
        at kafka.server.KafkaServer.$anonfun$shutdown$6(KafkaServer.scala:569)
        at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:85)
        at kafka.server.KafkaServer.shutdown(KafkaServer.scala:569)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:326)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
        at kafka.Kafka$.main(Kafka.scala:92)
        at kafka.Kafka.main(Kafka.scala)
[2018-07-26 09:12:50,204] INFO shut down completed (kafka.server.KafkaServer)
[2018-07-26 09:12:50,205] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
[2018-07-26 09:12:50,206] INFO shutting down (kafka.server.KafkaServer)

```

**Comment by symphorien** [comment]
Related: https://discourse.nixos.org/t/problems-with-java-version-8-oracle-and-openjdk-on-centos-6-9-glibc-issue/317/8

**Comment by vcunat** [comment]
Oh, thanks.  I knew I've read a related topic but I couldn't find it here on GitHub :-)
