### ISSUE TITLE
kibana permission denied

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nixpkgs#44080]
[op@srm ~] /nix/store/nx4qmh1l4llsdyr0r65lwkidp2k2fxlv-kibana-6.2.4/bin/kibana --config test -l test
fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/nix/store/nx4qmh1l4llsdyr0r65lwkidp2k2fxlv-kibana-6.2.4/libexec/kibana/optimize/.babelcache.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.writeFileSync (fs.js:1356:33)
    at save (/nix/store/nx4qmh1l4llsdyr0r65lwkidp2k2fxlv-kibana-6.2.4/libexec/kibana/node_modules/babel-register/lib/cache.js:45:16)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:613:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3

**Comment by clojurians-org** [comment]
it's okay now
```base
export BABEL_CACHE_PATH=$(pwd)/.babelcache.json
[larluo@larluo-nixos:~/my-env]$ cat nix.conf/kibana-6.2.4/kibana.yml.template 
path.data: ${_id_data}/data
```
