### ISSUE TITLE
Bazel 0.15.1 fails with Auto-Configuration Error: Cannot find gcc or CC

### ISSUE THREAD

**Issue by mebubo** [NixOS/nixpkgs#44105]
## Issue description

After a recent update to bazel 0.15.1 in nixpkgs, I'm unable to build any project. Bazel fails with 

> Auto-Configuration Error: Cannot find gcc or CC; either correct your path or set the CC environment variable

### Steps to reproduce

```
$ nix-env -q --out-path bazel
bazel-0.15.1  /nix/store/92gjr65zj472m6is2hzq9nyy0kr9glv3-bazel-0.15.1

$ mkdir /tmp/bazel-test
$ cd /tmp/bazel-test
$ touch WORKSPACE
$ bazel build
Starting local Bazel server and connecting to it...
...................
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "/home/me/.cache/bazel/_bazel_me/95fc1ed1afdc0650f9a0db1c7a4b7c34/external/bazel_tools/tools/cpp/cc_configure.bzl", line 56
                configure_unix_toolchain(repository_ctx, cpu_value, overriden...)
        File "/home/me/.cache/bazel/_bazel_me/95fc1ed1afdc0650f9a0db1c7a4b7c34/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 484, in configure_unix_toolchain
                _find_generic(repository_ctx, "gcc", "CC", overriden...)
        File "/home/me/.cache/bazel/_bazel_me/95fc1ed1afdc0650f9a0db1c7a4b7c34/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 466, in _find_generic
                auto_configure_fail(msg)
        File "/home/me/.cache/bazel/_bazel_me/95fc1ed1afdc0650f9a0db1c7a4b7c34/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 109, in auto_configure_fail
                fail(("\n%sAuto-Configuration Error:%...)))

Auto-Configuration Error: Cannot find gcc or CC; either correct your path or set the CC environment variable
INFO: Elapsed time: 1.924s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)

```

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.5, NixOS, 18.09pre145679.dae9cf6106d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d"`
 - channels(me): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by DerGernTod** [comment]
this still fails with 0.15.3, why was it closed?
