### ISSUE TITLE
springboot run with Invalid value for MonthOfYear[jarsigner error]

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nixpkgs#44304]
i build the springboot project, it report the following error:
```bash
[larluo@larluo-nixos:~/my-tmp/java-exmaple]$ java -jar /nix/store/sf1f0i4lgm82rzv5ax06pbzgy1141zzs-first-rest-0.0.1/share/java/first-rest-0.0.1.jar
Exception in thread "main" java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
        at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
        at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703)
        at java.time.LocalDate.of(LocalDate.java:267)
        at java.time.LocalDateTime.of(LocalDateTime.java:336)
        at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.decodeMsDosFormatDateTime(CentralDirectoryFileHeader.java:130)
        at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.getTime(CentralDirectoryFileHeader.java:119)
        at org.springframework.boot.loader.jar.JarEntry.<init>(JarEntry.java:55)
        at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:252)
        at org.springframework.boot.loader.jar.JarFileEntries.access$400(JarFileEntries.java:45)
        at org.springframework.boot.loader.jar.JarFileEntries$EntryIterator.next(JarFileEntries.java:302)
        at org.springframework.boot.loader.jar.JarFileEntries$EntryIterator.next(JarFileEntries.java:286)
        at org.springframework.boot.loader.jar.JarFile$2.nextElement(JarFile.java:196)
        at org.springframework.boot.loader.jar.JarFile$2.nextElement(JarFile.java:187)
        at org.springframework.boot.loader.archive.JarFileArchive$EntryIterator.next(JarFileArchive.java:186)
        at org.springframework.boot.loader.archive.JarFileArchive$EntryIterator.next(JarFileArchive.java:171)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:84)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:70)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

this is my build file:
```text
[larluo@larluo-nixos:~/my-tmp/java-exmaple]$ cat first-rest/default.nix 
{ fetchFromGitHub, maven, jdk, makeWrapper, stdenv, ... }:
stdenv.mkDerivation rec {
  name = "first-rest-${version}" ;
  version = "0.0.1";
  rev = "9bb2448803c5befe3dcf8e77ac02876784467574" ;

  src = fetchFromGitHub {
    owner = "clojurians-org" ;
    repo = "java-example" ; 
    rev = rev ;
    sha256 = "017jmd00g1g06agdmhjh6csfxh7p6697m5li0pbxyn2lck4y5lf5" ;
  } ;

  fetchedMavenDeps = stdenv.mkDerivation {
    name = "${name}-maven-deps";
    inherit src nativeBuildInputs;
    buildPhase = ''
      cd first-rest
      while timeout --kill-after=21m 20m mvn package -Dmaven.repo.local=$out/.m2; [ $? = 124 ]; do
        echo "maven hangs while downloading :("
      done
    '';
    installPhase = ''find $out/.m2 -type f \! -regex '.+\(pom\|jar\|xml\|sha1\)' -delete''; # delete files with lastModified timestamps inside
    outputHashAlgo = "sha256";
    outputHashMode = "recursive";
    outputHash = "030xfmp01krzgci49m0asnrwvwi57y0sdaajxgyjbx0ag9y3pih7" ;
  };

  nativeBuildInputs = [ maven ];
  buildInputs = [ makeWrapper ];
  buildPhase = ''
      cd first-rest
      mvn package --offline -Dmaven.repo.local=$(cp -dpR ${fetchedMavenDeps}/.m2 ./ && chmod +w -R .m2 && pwd)/.m2
  '';
  meta = with stdenv.lib; {
    homepage = "https://github.com/clojurians-org/java-example" ;
    description = "first-rest" ;
    license = licenses.asl20;
    platforms = platforms.unix;
  };

  installPhase = ''
    mkdir -p $out/bin
    mkdir -p $out/share/java
    mv target/first-rest-0.0.1-SNAPSHOT.jar $out/share/java/$name.jar
    makeWrapper ${jdk}/bin/java $out/bin/start-first-rest.sh --add-flags "-jar $out/share/java/$name.jar" --suffix PATH : ${stdenv.lib.makeBinPath [ jdk ]}
  '';
}
```
and my build code:
```bash
    nix-build -E 'with import <nixpkgs> {}; callPackage ./first-rest/default.nix {}'
[larluo@larluo-nixos:~/my-tmp/java-exmaple]$ uname -a
Linux larluo-nixos 4.14.55 #1-NixOS SMP Wed Jul 11 14:29:25 UTC 2018 x86_64 GNU/Linux
[larluo@larluo-nixos:~/my-tmp/java-exmaple]$ nix --version
nix (Nix) 2.0.4

```

it seems related to:
https://stackoverflow.com/questions/46508081/jarsigner-error-java-time-datetimeexception-invalid-value-for-monthofyear-val

**Comment by clojurians-org** [comment]
@volth  can you help look into this problem?

**Comment by githubslayer** [comment]
Hi,

I have the same issue. Did anyone find a solution?

**Comment by clojurians-org** [comment]
@githubslayer  unzip jar and jar those files again can work.

**Comment by khumba** [comment]
I'm also building a Spring project, using gradle2nix, and hit this issue.  Simply rebuilding the index on the JAR makes it able to run for me:

    postBuild = "${jdk}/bin/jar i build/libs/foo.jar";
