### ISSUE TITLE
kafka java.net.UnknownHostException:

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nixpkgs#44798]
when i run kafka-console-consumer or kafka-server-start, it report the error sometimes.
i want to change the /etc/hosts to add the mapping to localhost, but the file is readonly.
```bash
[larluo@larluo-nixos:~/my-env]$ hostname
larluo-nixos
java.net.UnknownHostException: larluo-nixos: larluo-nixos: System error
        at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
        at kafka.server.KafkaServer$$anonfun$5.apply(KafkaServer.scala:397)
        at kafka.server.KafkaServer$$anonfun$5.apply(KafkaServer.scala:395)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at kafka.server.KafkaServer.createBrokerInfo(KafkaServer.scala:395)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:256)
        at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:117)
        at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:66)
Caused by: java.net.UnknownHostException: larluo-nixos: System error
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
        ... 12 more
```

**Comment by clojurians-org** [comment]
i add configuration and rebuild nixos, it's okay now.
```nix
  networking.hostName = "larluo-nixos"; # Define your hostname.
  networking.extraHosts = 
    ''
      127.0.0.1 larluo-nixos
    '' ;
```
