### ISSUE TITLE
Theano stopped working: attempts to use a wrapped linker at runtime

### ISSUE THREAD

**Issue by ilya-kolpakov** [NixOS/nixpkgs#45463]
## Update
I can't reproduce the problem anymore. I tried setting-up environments using previous versions of nixpkgs tree and `python -c 'import theano`'worked just fine each time. It also now works with the unstable channel. I apologize for saying that it is likely that recent commits were breaking. Apparently they were not.

## Issue description
Theano module stopped working (I am using it on a machine wthout GPU from nix-shell but I don't think the problem is specific to nix-shell). Theano compiles and links C files at runtime and I believe it is currently packaged to use nix-wrapped gcc (or ld directly) which does not allow linking with impure paths.

I am 99% sure this is caused by changes to Theano package following commit f2adf2059a8cce (Apr 2018) when I packaged `pymc3`. I see recent commits by @smatting and @twhitehead which could have changed that and, specifically, the last commit https://github.com/NixOS/nixpkgs/commit/303a3f972eabd1eda0b3fbd4051d31d258402ad3#diff-9ce4da9e817d057187c991d35f9b525d aiming to "get theano to use a captured build environment". IMO, this shouldn't be the case as long as captured environment contains nix-wrapped linker.

I think it would be ideal to enable some basic checks in the package to prevent this from happening. 

@Fridh

### Steps to reproduce
```
[pymc3-env]$ nix-channel --list && nix-channel --update                                                                   
nixpkgs https://nixos.org/channels/nixpkgs-unstable                                                                                   
unpacking channels...                                                                                                                 
[pymc3-env]$ nix-shell -p 'pkgs.python36.withPackages(ps: [ps.TheanoWithoutCuda])'                                        
                                                                                                                                      
[nix-shell:~/repos/pymc3-env]$ python -c 'import theano'                                                                              
# omitted                                              
 Traceback (most recent call last):                                                                                                    
  File "<string>", line 1, in <module>                                                                                                
  File "/nix/store/5v2ixqnjrm7mdx4acw2kp0pizppz2kgf-python3-3.6.6-env/lib/python3.6/site-packages/theano/__init__.py", line 110, in <$
odule>                                                                                                                                
    from theano.compile import (                                                                                                      
  File "/nix/store/5v2ixqnjrm7mdx4acw2kp0pizppz2kgf-python3-3.6.6-env/lib/python3.6/site-packages/theano/compile/__init__.py", line 1$
, in <module>                                                                                                                         
    from theano.compile.mode import *                                                                                                 
  File "/nix/store/5v2ixqnjrm7mdx4acw2kp0pizppz2kgf-python3-3.6.6-env/lib/python3.6/site-packages/theano/compile/mode.py", line 11, in
 <module>
    import theano.gof.vm
  File "/nix/store/5v2ixqnjrm7mdx4acw2kp0pizppz2kgf-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/vm.py", line 674, in <mod
ule>
    from . import lazylinker_c
  File "/nix/store/5v2ixqnjrm7mdx4acw2kp0pizppz2kgf-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 14
0, in <module>
    preargs=args)
  File "/nix/store/5v2ixqnjrm7mdx4acw2kp0pizppz2kgf-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/cmodule.py", line 2388, i
n compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): impure path `/raid/data1/home/ilya/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-wi
th-centos-7.5.1804-Core--3.6.6-64/lazylinker_ext/lazylinker_ext.so' used in link. collect2: error: ld returned 1 exit status.
```
The path of the wrapped linker is hardcoded in installed theano package and is not introduced by nix-shell:
```
[nix-shell:~/repos/pymc3-env]$ which ld
/nix/store/kbzrrfix320x71icljxg0vpgiqq8f55a-gcc-wrapper-7.3.0/bin/ld

[nix-shell:~/repos/pymc3-env]$ PATH=$(echo $PATH | tr ':' '\n' | grep -v wrapper | tr '\n' ':')

[nix-shell:~/repos/pymc3-env]$ which ld
/nix/store/553rihc190vsyy8b22iqcq25a6489h8y-binutils-2.30/bin/ld

[nix-shell:~/repos/pymc3-env]$ python -c 'import theano'
# same error
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-693.11.6.el7.x86_64, CentOS Linux, 7 (Core)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(ilya): `"nixpkgs"`
 - nixpkgs: `/home/ilya/.nix-defexpr/channels/nixpkgs`
```

**Comment by twhitehead** [comment]
Glad to here it is working for you now as it was puzzling because I did test it and it worked for me.

My best guess as to what happened is you was maybe your `HOME` environment variable wasn't set? The impure error occurs when something outside of nix or `$HOME/.theano` gets linked in.

**Comment by gabysbrain** [comment]
This exact problem seems to have reappeared in 18.09. I have checked the value of my `HOME` env variable and it is set correctly. Do you know what else my cause this problem?

## Technical details

Results of `nix-shell -p nix-info --run "nix-info -m"`:

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.892.c06f5302f63 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.892.c06f5302f63"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by twhitehead** [comment]
Just letting you know that I have seen your report.  I haven't had a chance to update myself to 18.09 yet though to check it out due to other very pressing deadlines that I'm working on.  Thanks.

**Comment by ilya-kolpakov** [comment]
Maybe the problem is indeed due to paths. On this machine I am using `/home/ilya` is a symlink to `/raid/data1/home/ilya`. This was always the case though and theano used to work at some point in time.

```
Python 3.6.6 (default, Jun 27 2018, 05:47:41)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano

You can find the C code in this temporary file: /run/user/1063/theano_compilation_error_h4nj6359
Traceback (most recent call last):
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 81, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 105, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/__init__.py", line 110, in <module>
    from theano.compile import (
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/compile/__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/vm.py", line 674, in <module>
    from . import lazylinker_c
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 140, in <module>
    preargs=args)
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/cmodule.py", line 2388, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): impure path `/raid/data1/home/ilya/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.5.1804-Core--3.6.6-64/lazylinker_ext/lazylinker_ext.so' used in link. collect2: error: ld returned 1 exit status.
```

**Comment by ilya-kolpakov** [comment]
Thanks for the tip! I checked and actually theano derivation from old `nixos-17.09` works just fine. The one from unstable does not build (`libgpuarray`) so I cannot check what goes on with it. The key point (as discussed in the original post) is that I have a feeling that the `theano` derivation was initially specifically made not to use wrapped linker and later this was broken. I am not sure if this is indeed the case though.

The version I am having problems with is the one I am using from nix-shell. I am not quite sure what the exact version since theano lib is stored directly in `/nix/store/XXX-env` and I do not see any version info there. Python symlinks to
```
libpython3.6m.so -> /nix/store/p9x1rhy513pxdp34x07hrdrqdjlvszqi-python3-3.6.6/lib/libpython3.6m.so*
```
On this machine I am using `home/ilya` was always a symlink to `/raid/data1/home/ilya/.theano`.

When `$HOME` is set to `/home/ilya` I get this
```py
Python 3.6.6 (default, Jun 27 2018, 05:47:41)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano

You can find the C code in this temporary file: /run/user/1063/theano_compilation_error_vls9a3yl
Traceback (most recent call last):
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 81, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 105, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/__init__.py", line 110, in <module>
    from theano.compile import (
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/compile/__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/vm.py", line 674, in <module>
    from . import lazylinker_c
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 140, in <module>
    preargs=args)
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/cmodule.py", line 2388, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): impure path `/raid/data1/home/ilya/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.5.1804-Core--3.6.6-64/lazylinker_ext/lazylinker_ext.so' used in link. collect2: error: ld returned 1 exit status.
```

If I set it to the real location theano attempts to link something in `/run/user` and also fails
```py
>>> import os
>>> os.environ['HOME']
'/raid/data1/home/ilya'
>>> import theano

You can find the C code in this temporary file: /run/user/1063/theano_compilation_error_zzmyw06s
Traceback (most recent call last):
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 81, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 105, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/__init__.py", line 110, in <module>
    from theano.compile import (
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/compile/__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/vm.py", line 674, in <module>
    from . import lazylinker_c
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 140, in <module>
    preargs=args)
  File "/nix/store/ajc5zsmx5ljjk4i1d9amrxvvy31f49xh-python3-3.6.6-env/lib/python3.6/site-packages/theano/gof/cmodule.py", line 2388, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): impure path `/run/user/1063/cc6ZDuUm.o' used in link. collect2: error: ld returned 1 exit status.
```

**Comment by twhitehead** [comment]
Hummm.  That second failure is odd.  I wonder why it is using `/run/user/1063`.  Is there something else set in your environment or is something new Theano.  What do you get if you do
```
declare -p | fgrep /run/user/1063
```
In my environment, the only reference I have to /run/user is `XDG_RUNTIME_DIR`.  Maybe Theano is now using `XDG_RUNTIME_DIR` as a place for object files too?

Thanks!  -Tyson

**Comment by ilya-kolpakov** [comment]
I have
```
[ilya@seaseq theano]$ declare -p | fgrep /run/user
declare -x XDG_RUNTIME_DIR="/run/user/1063"
```
in the normal shell and the following in `nix-shell` pulling `TheanoWithoutCuda`:
```
[ilya@seaseq theano]$ echo $NIXCH
/home/ilya/.nix-defexpr/channels/nixos-
[ilya@seaseq theano]$ nix-shell -I nixpkgs="${NIXCH}17.09" -p 'pkgs.python3.withPackages(ps: [ps.TheanoWithoutCuda])' --command 'declare -p | fgrep /run/user'
declare -x NIX_BUILD_TOP="/run/user/1063"
declare -x TEMP="/run/user/1063"
declare -x TEMPDIR="/run/user/1063"
declare -x TMPDIR="/run/user/1063"
declare -x XDG_RUNTIME_DIR="/run/user/1063"
```
These are exactly the same for 18.09 (I cannot test 18.03 as it cannot pull some cudaDNN files and asks to register with NVidia).

Given the test script
```
[ilya@seaseq theano]$ cat theano_test.py 
import theano as t
import theano.tensor as tt

state = t.shared(0)
inc = tt.iscalar('inc')
acc = t.function([inc], state, updates=[(state, state+inc)])

assert state.get_value() == 0
acc(1)
assert state.get_value() == 1
```
Theano 17.09 works if I do not change the `$HOME`
```
[ilya@seaseq theano]$ nix-shell -I nixpkgs="${NIXCH}17.09" -p 'pkgs.python3.withPackages(ps: [ps.TheanoWithoutCuda])' --command 'python theano_test.py'

[ilya@seaseq theano]$ nix-shell -I nixpkgs="${NIXCH}18.09" -p 'pkgs.python3.withPackages(ps: [ps.TheanoWithoutCuda])'
[nix-shell:~/tmp/theano]$ export HOME=/raid/data1/home/ilya/
[nix-shell:/home/ilya/tmp/theano]$ python theano_test.py 
...
Exception: Compilation failed (return status=1): impure path `/raid/data1/home/ilya/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.5.1804-Core--3.6.6-64/lazylinker_ext/lazylinker_ext.so' used in link. collect2: error: ld returned 1 exit status.
```

while 18.09 fails in any case
```
[ilya@seaseq theano]$ nix-shell -I nixpkgs="${NIXCH}18.09" -p 'pkgs.python3.withPackages(ps: [ps.TheanoWithoutCuda])' --command 'python theano_test.py'
...
Exception: Compilation failed (return status=1): impure path `/raid/data1/home/ilya/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.5.1804-Core--3.6.6-64/lazylinker_ext/lazylinker_ext.so' used in link. collect2: error: ld returned 1 exit status.

[ilya@seaseq theano]$ nix-shell -I nixpkgs="${NIXCH}18.09" -p 'pkgs.python3.withPackages(ps: [ps.TheanoWithoutCuda])'
[nix-shell:~/tmp/theano]$ export HOME=/raid/data1/home/ilya/
[nix-shell:/home/ilya/tmp/theano]$ python theano_test.py 
...
Exception: Compilation failed (return status=1): impure path `/raid/data1/home/ilya/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.5.1804-Core--3.6.6-64/lazylinker_ext/lazylinker_ext.so' used in link. collect2: error: ld returned 1 exit status.
```

The location of the problematic file in my previous post is indeed weird. I can only get `ld` to complain about linking to something in `/run/user` if try to use theano from my running `nix-shell` environment and set `$HOME` to `/raid1/data/home/ilya`.

**Comment by twhitehead** [comment]
I think I'm a bit confused about when exactly you get the complaint about `/run/user`.   In particular, from this last post, it looks like you just consistently get complaints about `/raid/data1/home/ilya`

What exactly do you mean your "running `nix-shell` environment"?  How is this different from the very last example you gave?  What is it you have to do to get the complaints about `/run/user`?

**Comment by ilya-kolpakov** [comment]
Sorry, I guess I didn't explain this very well.

I have a nix-shell environment which I use for research at work and which I rarely exit. I only get theano compilation errors with `/run/user` in there and only if I change the `$HOME`.

As I mentioned, I am not sure which version of `theano` (or `nixpkgs` in general) it uses since `theano` is installed directly in the environment derivation. I guess it is one from a (currently) stale version of `unstable`.

Unless we can track down the specific version of `theano` used there and unless the upstream version is susceptible to the same problem I don't think there is anything to resolve.

**Comment by gabysbrain** [comment]
Sorry I'm sort of lost. But here is the full error on 18.09. 

```
You can find the C code in this temporary file: /run/user/1000/theano_compilation_error_9zwp5irb

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/nix/store/n2bbi94d9d9qym8akcjx757kqm7x3ry8-python3.6-Theano-1.0.2/lib/python3.6/site-packages/theano/gof/lazylinker_c.py in <module>()
     80                     version,
---> 81                     actual_version, force_compile, _need_reload))
     82 except ImportError:

ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
/nix/store/n2bbi94d9d9qym8akcjx757kqm7x3ry8-python3.6-Theano-1.0.2/lib/python3.6/site-packages/theano/gof/lazylinker_c.py in <module>()
    104                         version,
--> 105                         actual_version, force_compile, _need_reload))
    106         except ImportError:

ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-1-652bdaab9372> in <module>()
      4 
      5 import numpy as np
----> 6 import pymc3 as mc
      7 
      8 from bokeh.plotting import figure, show

/nix/store/h1054bj3l73f2qxljn74b7mzd5yqkrj7-python3.6-pymc3-3.5/lib/python3.6/site-packages/pymc3/__init__.py in <module>()
      3 
      4 from .blocking import *
----> 5 from .distributions import *
      6 from .external import *
      7 from .glm import *

/nix/store/h1054bj3l73f2qxljn74b7mzd5yqkrj7-python3.6-pymc3-3.5/lib/python3.6/site-packages/pymc3/distributions/__init__.py in <module>()
----> 1 from . import timeseries
      2 from . import transforms
      3 
      4 from .continuous import Uniform
      5 from .continuous import Flat

/nix/store/h1054bj3l73f2qxljn74b7mzd5yqkrj7-python3.6-pymc3-3.5/lib/python3.6/site-packages/pymc3/distributions/timeseries.py in <module>()
----> 1 import theano.tensor as tt
      2 from theano import scan
      3 
      4 from pymc3.util import get_variable_name
      5 from .continuous import get_tau_sd, Normal, Flat

/nix/store/n2bbi94d9d9qym8akcjx757kqm7x3ry8-python3.6-Theano-1.0.2/lib/python3.6/site-packages/theano/__init__.py in <module>()
    108     object2, utils)
    109 
--> 110 from theano.compile import (
    111     SymbolicInput, In,
    112     SymbolicOutput, Out,

/nix/store/n2bbi94d9d9qym8akcjx757kqm7x3ry8-python3.6-Theano-1.0.2/lib/python3.6/site-packages/theano/compile/__init__.py in <module>()
     10 from theano.compile.function_module import *
     11 
---> 12 from theano.compile.mode import *
     13 
     14 from theano.compile.io import *

/nix/store/n2bbi94d9d9qym8akcjx757kqm7x3ry8-python3.6-Theano-1.0.2/lib/python3.6/site-packages/theano/compile/mode.py in <module>()
      9 import theano
     10 from theano import gof
---> 11 import theano.gof.vm
     12 from theano import config
     13 from six import string_types

/nix/store/n2bbi94d9d9qym8akcjx757kqm7x3ry8-python3.6-Theano-1.0.2/lib/python3.6/site-packages/theano/gof/vm.py in <module>()
    672     if not theano.config.cxx:
    673         raise theano.gof.cmodule.MissingGXX('lazylinker will not be imported if theano.config.cxx is not set.')
--> 674     from . import lazylinker_c
    675 
    676     class CVM(lazylinker_c.CLazyLinker, VM):

/nix/store/n2bbi94d9d9qym8akcjx757kqm7x3ry8-python3.6-Theano-1.0.2/lib/python3.6/site-packages/theano/gof/lazylinker_c.py in <module>()
    138             args = cmodule.GCC_compiler.compile_args()
    139             cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
--> 140                                              preargs=args)
    141             # Save version into the __init__.py file.
    142             init_py = os.path.join(loc, '__init__.py')

/nix/store/n2bbi94d9d9qym8akcjx757kqm7x3ry8-python3.6-Theano-1.0.2/lib/python3.6/site-packages/theano/gof/cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2386             # difficult to read.
   2387             raise Exception('Compilation failed (return status=%s): %s' %
-> 2388                             (status, compile_stderr.replace('\n', '. ')))
   2389         elif config.cmodule.compilation_warning and compile_stderr:
   2390             # Print errors just below the command line.

Exception: Compilation failed (return status=1): impure path `/run/user/1000/ccCXVPxS.o' used in link. collect2: error: ld returned 1 exit status. 
```
​
I have run `declare -p | fgrep /run/user/1063`

and the only thing I get is not just `XDG_RUNTIME_DIR`. Here is the full output:

```
declare -x NIX_BUILD_TOP="/run/user/1000"
declare -x TEMP="/run/user/1000"
declare -x TEMPDIR="/run/user/1000"
declare -x TMP="/run/user/1000"
declare -x TMPDIR="/run/user/1000"
declare -x XDG_RUNTIME_DIR="/run/user/1000"
```

I don't see any reference to `$HOME/theano`

**Comment by ilya-kolpakov** [comment]
The workaround works, thank you.

I am positive that on my machine theano from 18.09 tries to build in `$HOME/.theano` which is actually the expected behavior ([docs][doc], [source][src]). I do not have ".theanorc" files or environment variables that could affect the build dir.

The env variables are similar to what you have shown
```
declare -x NIX_BUILD_TOP="/run/user/1063"
declare -x TEMP="/run/user/1063"
declare -x TEMPDIR="/run/user/1063"
declare -x TMPDIR="/run/user/1063"
declare -x XDG_RUNTIME_DIR="/run/user/1063"
```
but I do not get how these are relevant. Theano tries to build under `config.base_compiledir` which is `$HOME/.theano` by default and this default setting for it is not modified by the derivation.

[doc]: http://deeplearning.net/software/theano_versions/dev/library/config.html#config.base_compiledir
[src]: https://github.com/Theano/Theano/blob/3b51141a46affe9505f0e3f283020820b2c0251e/theano/configdefaults.py#L1903-L1906

I get the same errors regardless of whether I am a `theano`-only environment or a one with `pymc3` and `theano`.

**Comment by Shimuuar** [comment]
@twhitehead Whole point theano is code generation at runtime. So shouldn't purity check be switched off by default?

**Comment by twhitehead** [comment]
@Shimuuar the `NIX_ENFORCE_PURITY` settiing, as seen [here in the cc-wrapper script](../blob/master/pkgs/build-support/cc-wrapper/cc-wrapper.sh#L84) and [here in the ld-wrapper script](../blob/master/pkgs/build-support/bintools-wrapper/ld-wrapper.sh#L24), causes non-nix paths to be filtered out from the compiler options.

The reason for enabling this is to avoid cases where Theano pulls in bits an pieces from the user's environments (e.g., different versions of libraries than Theano itself was compiled against) causing it's code generation to fail. That is, the intent was to make Theano more robust, not less, by ensuring that the code it generates is compiled in the same environment that Theano itself was compiled in.

The issue some people have run into is that the ld-wrapper fails if passed a object outside of the [acceptable paths](../blob/master/pkgs/build-support/wrapper-common/utils.bash#L61)

- a relative path
- an absolute path to `$NIX_STORE`
- an absolute path to `$NIX_BUILD_TOP` (set to `$HOME/.theano` by the [Theano g++ wrapper](../blob/master/pkgs/development/python-modules/Theano/default.nix#L40))

and they effectively have two NIX_BUILD_TOP locations (e.g., where Theano builds in binaries) because their home directory is hidden behind a symlink. For example, if I understand an original posters setup correctly, they had

`/home/ilya -> /raid/data1/home/ilya`

so then both `/home/ilya/.theano` and `/raid/data1/home/ilya/.theano` are technically okay paths from a purity standpoint, but there is unfortunately no way to tell the wrapper this as nix only supports one setting for `NIX_BUILD_TOP`.

That said, I would highly recommend not using a symlink as above because it is fraught with its own issues. As a small example, you can see Theano must be inserting expanded paths `/raid/data1/home` into binaries, which means you cannot change the symlink in the future and expect things to work. It also means relative paths break in a variety of ways as `/home/ilya/..` is `/raid/data1/home` and not `/home`.

For this reason, if you want to overlay some critical part of your filesystem, I would really recommend using a bind mount (see the [mount man page](https://linux.die.net/man/8/mount)) as it is almost entirely transparent (technically I believe you can still detect it by comparing inode numbers, but that is much much less likely to trip up a program than).

Anyway, hope that explains things a bit better. Thoughts?

**Comment by twhitehead** [comment]
@gabysbrain in looking at this ticket again, I noticed that I forgot to respond to you. I spent a bit of time digging into it and it appears the issue is that `nix-shell` sets

```

**Comment by twhitehead** [comment]
@gabysbrain just a note that I accidentally press `ctrl+enter` and posted the prior note before I was done (use slack at work and it uses `ctrl+enter` to add a newline). I've edited the posting to complete it, so please see the thread and not the email you would have received for the full details.

**Comment by gabysbrain** [comment]
oh I see. Thanks so much!

**Comment by twhitehead** [comment]
I'm going to close this one as per ilya-kolpakov's update to the initial comment that the issue is not occurring anymore. Thanks everyone for all the input.
