### ISSUE TITLE
Unable to Install PyTorch CUDA on non NixOS Machines

### ISSUE THREAD

**Issue by kendricktan** [NixOS/nixpkgs#45692]
## Issue description
I'm currently trying to install PyTorch CUDA (v0.3.1) with cuda enabled through Nix on Ubuntu 16.04,  however it keeps throwing an impure error

```
impure path /usr/local/cuda/lib64/libcudart.so' used in link
```

### Steps to reproduce

1. Download contents of the two files below. (pytorch.nix is in ./env/ folder).
2. Run `nix-shell`

__./nix/pytorch.nix__
```nix
{ buildPythonPackage,
  cudaSupport ? false, cudatoolkit ? null, cudnn ? null,
  fetchFromGitHub, fetchpatch, lib, numpy, pyyaml, cffi, typing, cmake,
  stdenv, linkFarm, symlinkJoin,
  utillinux, which }:

assert cudnn == null || cudatoolkit != null;
assert !cudaSupport || cudatoolkit != null;

let
  cudatoolkit_joined = symlinkJoin {
    name = "${cudatoolkit.name}-unsplit";
    paths = [ cudatoolkit.out cudatoolkit.lib ];
  };

  # Normally libcuda.so.1 is provided at runtime by nvidia-x11 via
  # LD_LIBRARY_PATH=/run/opengl-driver/lib.  We only use the stub
  # libcuda.so from cudatoolkit for running tests, so that we don’t have
  # to recompile pytorch on every update to nvidia-x11 or the kernel.
  cudaStub = linkFarm "cuda-stub" [{
    name = "libcuda.so.1";
    path = "${cudatoolkit}/lib/stubs/libcuda.so";
  }];
  cudaStubEnv = lib.optionalString cudaSupport
    "LD_LIBRARY_PATH=${cudaStub}\${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH} ";

in buildPythonPackage rec {
  version = "0.3.1";
  pname = "torch";
  name = "${pname}-${version}";

  doCheck = false;

  src = fetchFromGitHub {
    owner  = "pytorch";
    repo   = "pytorch";
    rev    = "v${version}";
    fetchSubmodules = true;
    sha256 = "1k8fr97v5pf7rni5cr2pi21ixc3pdj3h3lkz28njbjbgkndh7mr3";
  };

  patches = [
    (fetchpatch {
      # make sure stdatomic.h is included when checking for ATOMIC_INT_LOCK_FREE
      # Fixes this test failure:
      # RuntimeError: refcounted file mapping not supported on your system at /tmp/nix-build-python3.6-pytorch-0.3.0.drv-0/source/torch/lib/TH/THAllocator.c:525
      url = "https://github.com/pytorch/pytorch/commit/502aaf39cf4a878f9e4f849e5f409573aa598aa9.patch";
      stripLen = 3;
      extraPrefix = "torch/lib/";
      sha256 = "1miz4lhy3razjwcmhxqa4xmlcmhm65lqyin1czqczj8g16d3f62f";
    })
  ];

  postPatch = ''
    substituteInPlace test/run_test.sh --replace \
      "INIT_METHOD='file://'\$TEMP_DIR'/shared_init_file' \$PYCMD ./test_distributed.py" \
      "echo Skipped for Nix package"
  '';

  preConfigure = lib.optionalString cudaSupport ''
    export CC=${cudatoolkit.cc}/bin/gcc CXX=${cudatoolkit.cc}/bin/g++
  '' + lib.optionalString (cudaSupport && cudnn != null) ''
    export CUDNN_INCLUDE_DIR=${cudnn}/include
  '';

  buildInputs = [
     cmake
     numpy.blas
     utillinux
     which
  ] ++ lib.optionals cudaSupport [cudatoolkit_joined cudnn];

  propagatedBuildInputs = [
    cffi
    numpy
    pyyaml
  ];

  checkPhase = ''
    ${cudaStubEnv}${stdenv.shell} test/run_test.sh
  '';

  meta = {
    description = "Tensors and Dynamic neural networks in Python with strong GPU acceleration.";
    homepage = http://pytorch.org/;
    license = lib.licenses.bsd3;
    platforms = lib.platforms.linux;
    maintainers = with lib.maintainers; [ teh ];
  };
}
```

__default.nix__
```nix
{ pkgs ? import <nixpkgs> {}}:

with pkgs;let
  pytorch_0_3_10 = pkgs.callPackage ./nix/pytorch.nix {   
    buildPythonPackage = python36Packages.buildPythonPackage;
    numpy = python36Packages.numpy;
    pyyaml = python36Packages.pyyaml;
    cffi = lispPackages.cffi;
    typing = pkgs.typing;
    cudaSupport = false;
    cudatoolkit = pkgs.cudatoolkit8;
    cudnn = pkgs.cudnn_cudatoolkit8;
  };
in
  stdenv.mkDerivation rec {
  name = "pytorchenv";

  # Boilderplate for builable env
  env = buildEnv { name = name; paths = buildInputs; };
  builder = builtins.toFile "builder.sh" ''
    source $stdenv/setup; ln -s $env $out
  '';

  buildInputs = [
    (python36.buildEnv.override {
      extraLibs = with python36Packages; [
        pytorch_0_3_10
      ];
    })
  ];
}
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-1066-aws, Ubuntu, 16.04.3 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(ubuntu): `"nixpkgs-18.09pre150352.7c826371c49"`
 - nixpkgs: `/home/ubuntu/.nix-defexpr/channels/nixpkgs`
```

**Comment by jyp** [comment]
Can you say what error you get? Note that pytorch is already packaged in nix. It currently fails with this error:

```
======================================================================
FAIL: test_gesv (test_autograd.TestAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-pytorch-0.4.0.drv-0/source/test/common.py", line 66, in wrapper
    fn(*args, **kwargs)
  File "/tmp/nix-build-python3.6-pytorch-0.4.0.drv-0/source/test/test_autograd.py", line 3152, in do_test
    check(name)
  File "/tmp/nix-build-python3.6-pytorch-0.4.0.drv-0/source/test/test_autograd.py", line 3078, in check
    self.assertEqual(unpack_variables(output_variable), output_tensor)
  File "/tmp/nix-build-python3.6-pytorch-0.4.0.drv-0/source/test/common.py", line 251, in assertEqual
    self.assertEqual(x_, y_, prec, message)
  File "/tmp/nix-build-python3.6-pytorch-0.4.0.drv-0/source/test/common.py", line 243, in assertEqual
    assertTensorsEqual(x, y)
  File "/tmp/nix-build-python3.6-pytorch-0.4.0.drv-0/source/test/common.py", line 235, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(2.5489) not less than or equal to 1e-05 :

----------------------------------------------------------------------
Ran 784 tests in 69.388s

FAILED (failures=1, errors=1, skipped=7)
Traceback (most recent call last):
  File "test/run_test.py", line 354, in <module>
    main()
  File "test/run_test.py", line 346, in main
    raise RuntimeError(message)
RuntimeError: test_autograd failed!
```
https://hydra.nixos.org/build/80376800/nixlog/1

Perhaps the maintainer @teh will have some idea.

**Comment by kendricktan** [comment]
Hi there, the error I get is: (Its on the original post)
```
impure path /usr/local/cuda/lib64/libcudart.so' used in link
```

I've tried to add 
```nix
{ sandbox = true; }
```
 it as per the suggestions from the IRC to `config.nix` but the same error still surfaces.

**Comment by teh** [comment]
@jyp seems to be down to this:

```
Error: failed to parse the list of possible procesors in /sys/devices/system/cpu/possible
Error: failed to parse the list of present procesors in /sys/devices/system/cpu/present
```

which would explain why it builds locally. I'll try removing just that test, and disabling tests in general if that doesn't work.

@kendricktan building pytorch is a bit fiddly, I recommend basing your derivation on the [existing package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/pytorch/default.nix)

**Comment by teh** [comment]
@kendricktan is this still an issue?

**Comment by prusnak** [comment]
Let's close this
