### ISSUE TITLE
statsd 0.8.0: fails to start up (runtime error)

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#45946]
## Issue description

Since nodePackages: 6_x -> 8_x  (#45700) was merged,  `statsd` fails to start up:

```
$ result/bin/statsd
util.js:939
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.inherits (util.js:939:11)
    at Object.<anonymous> (/nix/store/1i2v5g0b33sdp2y98gqs0s009z2ngkpl-node-statsd-0.8.0/lib/node_modules/statsd/lib/config.js:33:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/nix/store/1i2v5g0b33sdp2y98gqs0s009z2ngkpl-node-statsd-0.8.0/lib/node_modules/statsd/stats.js:4:14)

```

### Steps to reproduce

`nix-build nixos/release.nix -A tests.statsd.x86_64-linux`, or just execute `statsd` manually.

## Technical details

master @ 4d3ed9f5d56179e75999371b0df4b4db73b68249 , NixOS, x86_64-linux

--

cc @Mic92 who authored the nodePackages update, statsd has no listed maintainer.

**Comment by xeji** [comment]
Upstream project https://github.com/etsy/statsd looks dead, last release May 2016,  last commit Nov 2016. 
Maybe we should just mark it as broken or even drop it?

**Comment by xeji** [comment]
cc ZHF #45960

**Comment by xeji** [comment]
Well, since some other nixos modules reference statsd, I will just mark it broken for now, not drop it yet.
