### ISSUE TITLE
tensorflow-tensorboard-1.9.0 from master fails on start during locale setting

### ISSUE THREAD

**Issue by akamaus** [NixOS/nixpkgs#46641]
## Issue description
I installed tensorboard from master branch (at 24aea25528961d3) and found some weird behavior on start:
```
% nix-shell-unstable -p python36Packages.tensorflow-tensorboard -p python36Packages.tensorflowWithoutCuda  --run 'tensorboard --logdir logs'         
Traceback (most recent call last):
  File "/nix/store/8w94iidz1pmcqda6mswq3ra0azgp8v86-python3.6-tensorflow-tensorboard-1.9.0/bin/.tensorboard-wrapped", line 12, in <module>
    sys.exit(run_main())
  File "/nix/store/8w94iidz1pmcqda6mswq3ra0azgp8v86-python3.6-tensorflow-tensorboard-1.9.0/lib/python3.6/site-packages/tensorboard/main.py", line 46, in run_main
    tf.app.run(main)
  File "/nix/store/rsf4l1rff96ahssk1vswxi6kz1m1602b-python3.6-tensorflow-1.9.0/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/nix/store/8w94iidz1pmcqda6mswq3ra0azgp8v86-python3.6-tensorflow-tensorboard-1.9.0/lib/python3.6/site-packages/tensorboard/main.py", line 55, in main
    default.get_assets_zip_provider())
  File "/nix/store/8w94iidz1pmcqda6mswq3ra0azgp8v86-python3.6-tensorflow-tensorboard-1.9.0/lib/python3.6/site-packages/tensorboard/program.py", line 167, in main
    util.setup_logging()
  File "/nix/store/8w94iidz1pmcqda6mswq3ra0azgp8v86-python3.6-tensorflow-tensorboard-1.9.0/lib/python3.6/site-packages/tensorboard/util.py", line 50, in setup_logging
    locale.setlocale(locale.LC_ALL, '')
  File "/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
I decided to manually execute setlocale and found it works perfectly:
```
% nix-shell-unstable -p python36 --pure                                                                                                                   ~/ML 

[nix-shell:~/ML]$ python3
Python 3.6.6 (default, Jun 27 2018, 05:47:41) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_ALL, '') # Testing the actual cmd
'C'
>>> locale.setlocale('') # trigger the error so path to interpreter is shown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
TypeError: an integer is required (got type str)
```
So Python is the same but behavior differs. Any ideas?

## Technical details
% nix-shell -p nix-info --run "nix-info -m"                                                                                                  
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.65, NixOS, 18.03.git.6adb065 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `""`
 - channels(test): `""`
 - channels(dvyal): `""`
 - nixpkgs: `/home/dvyal/nixpkgs`

**Comment by akamaus** [comment]
It turns out it has nothing to do with tensorboard.
If I instantiate --pure shell it works, if I run nix-shell without --pure, I get error from locale.setlocale.
The difference is locale settings. In my regular shells they're:
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME=ru_RU.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

and for nix-shell --pure:
```
$ locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME=POSIX
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
If I manually reset the variables to "POSIX" setlocale works and tensorboard starts successfully.
