### ISSUE TITLE
tensorflow 1.9.0:  libforestprotos.so: cannot open shared object file

### ISSUE THREAD

**Issue by baracoder** [NixOS/nixpkgs#46841]
## Issue description

On loading `tensorflow.contrib`, the library `libforestprotos.so` can not be found.

### Steps to reproduce

```
% nix-shell -p 'python36.withPackages (p: with p; [ tensorflowWithCuda ])' --run 'python -c "import tensorflow.contrib"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
...
  File "/nix/store/mwcxhmw4dib7g33ly2hwyxlgqwwha8l8-python3-3.6.6-env/lib/python3.6/site-packages/tensorflow/contrib/tensor_forest/python/ops/tensor_forest_ops.py", line 28, in <module>
    resource_loader.get_path_to_datafile('_tensor_forest_ops.so'))
  File "/nix/store/mwcxhmw4dib7g33ly2hwyxlgqwwha8l8-python3-3.6.6-env/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/nix/store/mwcxhmw4dib7g33ly2hwyxlgqwwha8l8-python3-3.6.6-env/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libforestprotos.so: cannot open shared object file: No such file or directory
```

Though the file exists in the module directory
```
% find /nix/store/mwcxhmw4dib7g33ly2hwyxlgqwwha8l8-python3-3.6.6-env/lib/python3.6/site-packages/tensorflow/ -iname libforestprotos.so
/nix/store/mwcxhmw4dib7g33ly2hwyxlgqwwha8l8-python3-3.6.6-env/lib/python3.6/site-packages/tensorflow/contrib/tensor_forest/libforestprotos.so
```

## Technical details

```
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.67, NixOS, 18.09pre150708.083220867c7 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(bara): `""`
 - channels(root): `"nixos-19.03pre152634.218ce4de508, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by baracoder** [comment]
@jyp seen your name on #44599 and #45709 do you have an idea where to look?

**Comment by baracoder** [comment]
@jyp thank you for the help.
I have added `contrib/tensor_forest` to the rpath and it is working https://github.com/NixOS/nixpkgs/compare/master...baracoder:tf-fix-contrib

Would you add it to your pull request for tensorflow 1.10.1 or should it be a different pull request?

I have checked for any other missing libraries with
```
find /nix/store/pns825s1pbqkihavqi6cmclhb6mv64xn-python3.6-tensorflow-1.9.0/ -iname '*.so*' -exec bash -c 'echo {} ; ldd {}' \;|grep -C 6 'not found'
```
There is `libnvinfer.so.4` missing, it is nowhere on my system, but I don't know what the effect of it is.

**Comment by jyp** [comment]
Thanks for debugging this!

The tensorflow 1.10.1 PR has been queued for a very long time now. You may
have a better chance with a separate PR.
