### ISSUE TITLE
Zim pkg fails to start - 

### ISSUE THREAD

**Issue by rand00** [NixOS/nixpkgs#4786]
Zim fails to start (but it builds) - I'm using the 'nixos-unstable' channel

```
** (process:1938): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:1938): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:1938): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
WARNING: Can not import 'xdg.Mime' - falling back to 'mimetypes'
Traceback (most recent call last):
  File "/nix/store/bv6x3wwywwrnaal8nnfi89dnjw8igzln-zim-0.60/bin/.zim-wrapped", line 38, in <module>
    import zim
  File "/nix/store/bv6x3wwywwrnaal8nnfi89dnjw8igzln-zim-0.60/lib/python2.7/site-packages/zim/__init__.py", line 192, in <module>
    % map(str, zim.config.data_dirs())
AssertionError: ERROR: Could not find data files in path: 
['/root/.local/share/zim', '/root/.nix-profile/share/zim', '/nix/var/nix/profiles/default/share/zim', '/run/current-system/sw/share/zim']
Try setting XDG_DATA_DIRS

```

pkg-link https://github.com/NixOS/nixpkgs/tree/701cd705024d81b137f2ce0f3abf4730ec760b9a/pkgs/applications/office/zim

**Comment by bobvanderlinden** [comment]
I have the same problem since some time. My `XDG_DATA_DIRS` is:
```
/nix/store/szc6nb8vnf7bxpwjbzl1anzn7pfasafa-gsettings-desktop-schemas-3.12.2/share/gsettings-schemas/gsettings-desktop-schemas-3.12.2:/nix/store/850ckfidvg48a4b4ysq6f0xx83vwaf8b-gtk+3-3.12.2/share/gsettings-schemas/gtk+3-3.12.2:/home/bob/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
```
