### ISSUE TITLE
awscli reads in the environment's PYTHONPATH (it should ignore it to avoid issues when you have PYTHONPATH set inside a nix-shell)

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#47900]
## Issue description

If you are in a nix-shell using Python 3 with PYTHONPATH set. And you also bring in `awscli` package and try to run `aws`, most likely it will fail.

Currently I see an error like:

```
Traceback (most recent call last):
  File "/nix/store/hv342l77q68hknq2g4ngqki9v0cjmz95-awscli-1.14.50/bin/.aws-wrapped", line 20, in <module>
    import awscli.clidriver
  File "/nix/store/hv342l77q68hknq2g4ngqki9v0cjmz95-awscli-1.14.50/lib/python2.7/site-packages/awscli/clidriver.py", line 36, in <module>
    from awscli.help import ProviderHelpCommand
  File "/nix/store/hv342l77q68hknq2g4ngqki9v0cjmz95-awscli-1.14.50/lib/python2.7/site-packages/awscli/help.py", line 20, in <module>
    from docutils.core import publish_string
  File "/nix/store/fvfhzwvyy8qbcn4d7x2091zh8b4c9yxn-python3.6-docutils-0.14/lib/python3.6/site-packages/docutils/core.py", line 246
    print('\n::: Runtime settings:', file=self._stderr)
                                         ^
SyntaxError: invalid syntax
```

The solution is to run aws without a PYTHONPATH environment variable: `PYTHONPATH='' aws`. Since awscli currently is installed as a CLI program, and not as a library, then it should make sense to create a make wrapper around the `aws` script which sets the `PYTHONPATH` environment variable that ignores external `PYTHONPATH` variables.

### Steps to reproduce

Get into a `nix-shell` with Python 3, and then use awscli `aws`.

---

I believe fixing this, should also fix: https://github.com/NixOS/nixpkgs/issues/42903

**Comment by CMCDragonkai** [comment]
I have a workaround temporarily:

```nix
        (buildEnv {
          name = "wrapped-awscli-${awscli.version}";
          paths = [ awscli ];
          pathsToLink = [ "/bin" ];
          buildInputs = [ makeWrapper ];
          postBuild = ''
            wrapProgram $out/bin/aws --unset PYTHONPATH
          '';
        })
```

And installing that instead.

**Comment by chreekat** [comment]
+1 to wrapping awscli

**Comment by jamesottaway** [comment]
I'm using that workaround in an overlay, but would it be feasible to merge that into the official derivation?

**Comment by CMCDragonkai** [comment]
Yes this should be merged into the official derivation. Wrap the awscli executable to avoid inheriting the PYTHONPATH from the environment. This makes the most sense.

Unless one is actually developing on awscli...

**Comment by liff** [comment]
Encountered this as well. I use this in my `buildInputs` (effectively same as the above wrapper thing):

```nix
(awscli2.overrideAttrs (old: {
  makeWrapperArgs = (old.makeWrapperArgs or []) ++ ["--unset" "PYTHONPATH"];
}))
```

**Comment by pandaman64** [comment]
This issue affects in the other direction. In other words, introducing `awscli2` into the development shell using `nix-shell` or `nix develop` pollutes the shell's `PYTHONPATH`, which causes other Python scripts to fail. This includes `nixos-test-driver` ([link](https://nixos.org/manual/nixos/stable/index.html#sec-nixos-tests)).

For example,
```console
# clean PYTHONPATH
$ echo $PYTHONPATH

# runs successfully
$ ./result/bin/nixos-test-driver

# awscli2 introduces conflicting package (prompt-toolkit-2.0.10) to PYTHONPATH,
$ nix-shell -p awscli2
$ echo $PYTHONPATH
/nix/store/2hpzy5p770xivzp02igjaqyh009dvwfn-awscli2-2.3.4/lib/python3.9/site-packages:/nix/store/nb5v9mhafkgkzn9mvjfrq2bg3c1h976c-python3.9-awscrt-0.12.4/lib/python3.9/site-packages:/nix/store/5bh6rpya1ar6l49vrhx1rg58dsa42906-python3-3.9.6/lib/python3.9/site-packages:/nix/s
tore/lgxyj89524zyplrma87309qspw219q4h-python3.9-bcdoc-0.16.0/lib/python3.9/site-packages:/nix/store/dsbl7kb2ayq9svnk3ll3bpll2p0kcvbi-python3.9-botocore-2.0.0dev155/lib/python3.9/site-packages:/nix/store/4szmsas2djzc6iqsqxffrxxcrbbgs6n3-python3.9-python-dateutil-2.8.2/lib/py
thon3.9/site-packages:/nix/store/j3s61z5mdrhizcwcb41g38i3yga4kq5p-python3.9-six-1.16.0/lib/python3.9/site-packages:/nix/store/ss20fkw3isgf1dm7s7vagh659g902ad0-python3.9-jmespath-0.10.0/lib/python3.9/site-packages:/nix/store/9pf3f0hai749x097mpjd53fahdadydjj-python3.9-ply-3.1
1/lib/python3.9/site-packages:/nix/store/ymm2cb622sls6i5i46k8cybd8dm6av9j-python3.9-docutils-0.17.1/lib/python3.9/site-packages:/nix/store/g01hz7ap9jysga10mm56w0z15p12whh4-python3.9-ordereddict-1.1/lib/python3.9/site-packages:/nix/store/njjd21pi4akpvxkkvd7z4svyg76vxs3f-pyth
on3.9-simplejson-3.17.5/lib/python3.9/site-packages:/nix/store/jl18pq80zm0i4hxfx6igrl6abw4ybv26-python3.9-urllib3-1.26.7/lib/python3.9/site-packages:/nix/store/shng6prqxs67q3wn2bmv4lisnji0k5xr-python3.9-brotli-1.0.9/lib/python3.9/site-packages:/nix/store/hx41qhkpybrzyr972jk
7b84nhrpxfcw5-python3.9-pysocks-1.7.1/lib/python3.9/site-packages:/nix/store/f6lq4va011bnkxy2vxj2ggr22bdaq23g-python3.9-colorama-0.4.4/lib/python3.9/site-packages:/nix/store/iqyx4fqax9qhiyxkqq0qra5y0pwagzq3-python3.9-packaging-20.9/lib/python3.9/site-packages:/nix/store/yky
lz2jhp37dak53a5ds77f7vxqp7xmd-python3.9-pyparsing-2.4.7/lib/python3.9/site-packages:/nix/store/nrf62pcs9fgjkhx1kxqiavgrdqsm8qsn-python3.9-pycparser-2.20/lib/python3.9/site-packages:/nix/store/c8lq7y7fiknvsp5xiqmyizjyk9y5xgkd-python3.9-cffi-1.14.6/lib/python3.9/site-packages
:/nix/store/yd07gq5480rcg6pz67a2sn3q05i0w9g9-python3.9-cryptography-3.4.8/lib/python3.9/site-packages:/nix/store/8n39rvcmi754zadvh9b24s1kaq0my1l0-python3.9-distro-1.6.0/lib/python3.9/site-packages:/nix/store/l9gr0jv778714mpck9zwg5nw6y0pf1bz-python3.9-prompt-toolkit-2.0.10/l
ib/python3.9/site-packages:/nix/store/6n8f61w67x2hs8vizspmfals44cj6zgv-python3.9-wcwidth-0.2.5/lib/python3.9/site-packages:/nix/store/v0sq1qcn6sywrxn7cw7nbpy426g7kzgi-python3.9-setuptools-57.2.0/lib/python3.9/site-packages:/nix/store/yjkf7d9phc2ibyyq4blbmvjbafk3bqb4-python3
.9-PyYAML-5.4.1.1/lib/python3.9/site-packages:/nix/store/nvxp7d6ikbga2abrd0ndqwqci6q0f8bs-python3.9-rsa-4.7.2/lib/python3.9/site-packages:/nix/store/jdhbjdfyi0xryj2fv2kb3cksd98an5ik-python3.9-pyasn1-0.4.8/lib/python3.9/site-packages:/nix/store/lhiy16vy3f75l267zykg6gyc56xnfb
d6-python3.9-ruamel-yaml-0.17.16/lib/python3.9/site-packages:/nix/store/axnrwjrdfc8wmy8555sarm47ai0mvfaw-python3.9-ruamel-base-1.0.0/lib/python3.9/site-packages:/nix/store/wl9ymwfs58849qa1xrzrakjhf1x52v43-python3.9-ruamel-yaml-clib-0.2.4/lib/python3.9/site-packages:/nix/sto
re/5wz8g5jb1hkjik9zywbn5mpdix59k3ns-python3.9-s3transfer-0.4.2/lib/python3.9/site-packages

# which breaks nixos-test-driver
$ ./result/bin/nixos-test-driver
Traceback (most recent call last):
  File "/nix/store/wf1lz21604ivlv19zvgh0jdjidl93vqw-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 15, in <module>
    import ptpython.repl
  File "/nix/store/ysrxss08nx2ch5lsh4y8lw89fabxwjm4-python3-3.9.6-env/lib/python3.9/site-packages/ptpython/__init__.py", line 1, in <module>
    from .repl import embed
  File "/nix/store/ysrxss08nx2ch5lsh4y8lw89fabxwjm4-python3-3.9.6-env/lib/python3.9/site-packages/ptpython/repl.py", line 21, in <module>
    from prompt_toolkit.formatted_text import (
ImportError: cannot import name 'AnyFormattedText' from 'prompt_toolkit.formatted_text' (/nix/store/l9gr0jv778714mpck9zwg5nw6y0pf1bz-python3.9-prompt-toolkit-2.0.10/lib/python3.9/site-packages/prompt_toolkit/formatted_text/__init__.py)
```

The workaround is unsetting `PYTHONPATH`, as shown in https://github.com/kreisys/nur-packages/commit/3df38aaae420fd9c7b0fe895d918511c2e67a8f2.
