### ISSUE TITLE
pytorch-0.4.1 fails to build

### ISSUE THREAD

**Issue by kwohlfahrt** [NixOS/nixpkgs#48158]
## Issue description

I cannot build pytorch (cuda enabled or disabled), due to failing tests. I'm not sure why this is built locally instead of taken from the cache.

### Steps to reproduce

`> nix run "(with import <nixpkgs> {}; python3.withPackages (ps: with ps; [ pytorch ]))"`

I expect to get a shell where `python3` can be run and `pytorch` can be imported. Instead, I get an error:

```
builder for '/nix/store/zj90cf6xa9p0m2lv701rhr5z7ddg8mwy-python3.6-pytorch-0.4.1.drv' failed with exit code 1; last 10 log lines:
  ----------------------------------------------------------------------
  Ran 41 tests in 482.056s
  
  FAILED (failures=32, skipped=9)
  Traceback (most recent call last):
    File "test/run_test.py", line 345, in <module>
      main()
    File "test/run_test.py", line 337, in main
      raise RuntimeError(message)
  RuntimeError: test_distributed failed!
```

Full log is too long for pastebin, but the errors mostly look like:

```
Process process 2:
Traceback (most recent call last):
  File "/nix/store/1c4zshbxizcsvyj46fwf5jj10h41wf6i-python3-3.6.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/nix/store/1c4zshbxizcsvyj46fwf5jj10h41wf6i-python3-3.6.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test_distributed.py", line 950, in _run
    world_size=int(WORLD_SIZE))
  File "/nix/store/plrqrhi0npp7ba80chq1a49nhl5vnk5d-python3.6-pytorch-0.4.1/lib/python3.6/site-packages/torch/distributed/__init__.py", lin
e 94, in init_process_group
    group_name, rank)
RuntimeError: could not establish connection with other processes at /build/source/torch/lib/THD/process_group/General.cpp:17
F
======================================================================
FAIL: test_DistributedDataParallelCPU (__main__.TestDistBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_distributed.py", line 911, in wrapper
    self._join_and_reduce(fn)
  File "test_distributed.py", line 971, in _join_and_reduce
    self.assertEqual(p.exitcode, first_process.exitcode)
  File "/build/source/test/common.py", line 364, in assertEqual
    super(TestCase, self).assertEqual(x, y, message)
AssertionError: 1 != None : 
```

With these probably relevant lines near the beginning:

```
Error: failed to parse the list of possible procesors in /sys/devices/system/cpu/possible
Error: failed to parse the list of present procesors in /sys/devices/system/cpu/present
```

Those two files both contain `0-11` in my user shell.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 19.03pre154487.0a7e258012b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(kai): `""`
 - channels(root): `"nixos-19.03pre154487.0a7e258012b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by matthewbauer** [comment]
I think it might be a sandboxing thing. Could you try running with ```--option sandbox false```?

**Comment by kwohlfahrt** [comment]
That doesn't help, I still get the same error with `nix --option sandbox false run "(with import <nixpkgs> {}; pkgs.python3.withPackages (ps: [ ps.pytorch ]))"`

However, a sample nix that just does `ls -l /sys` as its `checkPhase` also fails:

```
> nix --option sandbox false build "(with import <nixpkgs> {}; callPackage ./sample.nix {})"
builder for '/nix/store/65pq51vizgiwip3nyrfpvndimvl91irs-sys-test.drv' failed with exit code 2; last 9 log lines:
  unpacking sources
  unpacking source archive /nix/store/bdazkyrw6v4p6mrycrs8ddpvwr6gzrdy-nix
  source root is nix
  patching sources
  configuring
  no configure script, doing nothing
  building
  running tests
  ls: cannot access '/sys': No such file or directory
[0 built (1 failed)]
error: build of '/nix/store/65pq51vizgiwip3nyrfpvndimvl91irs-sys-test.drv' failed
```

`sample.nix`:

```
{ stdenv }:

stdenv.mkDerivation {
  name = "sys-test";

  src = ./.;

  buildInputs = [];
  propagatedBuildInputs = [];

  buildPhase = ''
    mkdir -p $out/bin
  '';
  installPhase = ''
    touch $out/bin/foo
  '';

  doCheck = true;

  checkPhase = ''
    ls -l /sys
  '';
}
```

Am I doing something wrong here?

**Comment by matthewbauer** [comment]
Oops, I think you do need to be a "trusted user" to disable sandbox. You can try it by running:

```
sudo nix --option sandbox false run "(with import <nixpkgs> {}; pkgs.python3.withPackages (ps: [ ps.pytorch ]))"
```

(or adding your user to nix.trustedUsers)

**Comment by kwohlfahrt** [comment]
Yes, that works. Is there anything I can do to fix the package for other users? I could disable the problematic tests (I think they were enabled in #46562), or is there some way of saying a package must be built without sandboxing?

**Comment by kwohlfahrt** [comment]
I have `cudaSupport = true` in my `~/.config/nixpkgs/config.nix` - can you see if you see if it works for you then? If yes, I think there is some other package that `pytorchWithCuda` needs with cuda enabled but it doesn't correctly depend on.

**Comment by juliendehos** [comment]
Tried with `cudaSupport = true` but same error.
Tensorflow and tensorflowWithCuda work with my config.

**Comment by juliendehos** [comment]
Adding cudnn solved the problem. :champagne: 
```
nix --option sandbox false run "(with import <nixpkgs> {}; python3.withPackages (ps: [ cudnn ps.pytorchWithCuda ]))"
```

**Comment by kwohlfahrt** [comment]
It is very odd that your initial command works for me without problems:

```
> nix --option sandbox false run "(with import <nixpkgs> {}; python3.withPackages (ps: [ ps.pytorchWithCuda ]))" -c python3
Python 3.6.6 (default, Jun 27 2018, 05:47:41) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.Tensor([1]).cuda()
tensor([1.], device='cuda:0')
>>> 
```

**Comment by juliendehos** [comment]
Indeed, I get lost in the different configurations that I tried.
```
nix --option sandbox false run "(with import <nixpkgs> {}; python3.withPackages (ps: [ ps.pytorchWithCuda ]))"
```
with `cudaSupport=true` works fine.
Thanks.
