### ISSUE TITLE
`parity-ui` fails to start

### ISSUE THREAD

**Issue by kevroletin** [NixOS/nixpkgs#48483]
## Issue description

Attempt to run `parity-ui` on `nixos-18.09` fails with the error:

``` sh
parity-ui: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
```

I've tried to add `gtk3` as a runtime dependency to a `parity-ui`derivation like this:

``` diff
diff --git a/pkgs/applications/altcoins/parity-ui/default.nix b/pkgs/applications/altcoins/parity-ui/default.nix
index ec2e571e..8c556cc1 100644
--- a/pkgs/applications/altcoins/parity-ui/default.nix
+++ b/pkgs/applications/altcoins/parity-ui/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, pkgs, fetchurl, makeWrapper, nodePackages }:
+{ stdenv, pkgs, fetchurl, makeWrapper, nodePackages, gtk3 }:
 
 let
 
@@ -29,7 +29,7 @@ in stdenv.mkDerivation rec {
     fixupPhase
 
     patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" \
-      --set-rpath "${uiEnv.libPath}:$out/share/parity-ui" \
+      --set-rpath "${uiEnv.libPath}:$out/share/parity-ui:${gtk3}/lib" \
       $out/share/parity-ui/parity-ui
 
     find $out/share/parity-ui -name "*.node" -exec patchelf --set-rpath "${uiEnv.libPath}:$out/share/parity-ui" {} \;
```

That time UI has rendered but I immediately got another error:

``` sh
TypeError: Cannot read property 'files' of undefined
    at /nix/store/zjdwcxf8b72amzzlvlraypj173amzchr-parity-ui-0.3.4/share/parity-ui/resources/app.asar/.build/electron.js:3593:26
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Steps to reproduce

Just install and run `parity-ui`

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 18.09.821.4dd9cd3f69e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(behemoth): `""`
 - channels(root): `"nixos-18.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kevroletin** [comment]
Hey, @sorpaas could you please look at this issue

**Comment by sorpaas** [comment]
@kevroletin I tested and it still works on unstable. Probably need some help to test on `18.09`.

**Comment by kevroletin** [comment]
I've tried to install `parity-ui` from the `master` *(rev da46be3ae56)* branch like this:
```
git clone https://github.com/NixOS/nixpkgs.git ~/nixpkgs-unstable
nix-env -iA nixos.firefox -f ~/nixpkgs-unstable
```
And got the same results.

I forgot to mention that once I added `gtk2` as a runtime dependency I got not only an error message into a console but also a dialog box saying "An error occured while fetching parity." with some addition info about `parity-ui` version.

**Comment by locallycompact** [comment]
Also seeing this problem on unstable.

    parity-ui: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

**Comment by NCrashed** [comment]
The problem still persists.

**Comment by jluttine** [comment]
Still relevant.
