### ISSUE TITLE
sage jupyter notebook not working

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#48544]
## Issue description

When I run `sage -n jupyter`, I have the jupyter website that opens, however when I open a sage notebook, the sage kernel fails to start, and I've an error

```
$ sage -n jupyter
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 8.3, Release Date: 2018-08-03                     │
│ Type "notebook()" for the browser-based notebook interface.        │
│ Type "help()" for help.                                            │
└────────────────────────────────────────────────────────────────────┘
Please wait while the Sage Jupyter Notebook server starts...
[I 10:52:39.260 NotebookApp] Serving notebooks from local directory: /home/leo
[I 10:52:39.260 NotebookApp] The Jupyter Notebook is running at:
[I 10:52:39.260 NotebookApp] http://localhost:8888/?token=49343703088717cbc2c60d28521f8dba438cef350285649d
[I 10:52:39.260 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:52:39.260 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=49343703088717cbc2c60d28521f8dba438cef350285649d
[I 10:52:39.719 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 10:52:56.456 NotebookApp] Notebook Documents/ownCloud-lip6/Documents/Code/Sampling_small_basis/sampling_small_basis.ipynb is not trusted
[E 10:53:00.206 NotebookApp] Failed to run command:
    [u'/build/sage-src-8.3/bin/sage', u'--python', u'-m', u'sage.repl.ipython_kernel', u'-f', u'/run/user/1000/jupyter/kernel-97e8248f-d6a2-4ebb-8467-d5fe18c51e32.json']
        PATH='/nix/store/yxb0yfy4j3hnyif42fwpzq76qp2kpwbr-sage-with-env-8.3/bin:/nix/store/yxb0yfy4j3hnyif42fwpzq76qp2kpwbr-sage-with-env-8.3/build/bin:/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/bin:/nix/store/mvykw5s11w12mi32nkk7cf5pl7jnsn72-python3-3.6.6-env/bin:/nix/store/mvfh8jj5200308mv2wms2bnwzy96yi3c-gfortran-wrapper-7.3.0/bin:/nix/store/iw94llkj05wgaz268mlzvgx8jkbi1ss0-gcc-wrapper-7.3.0/bin:/nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23/bin:/nix/store/wm8va53fh5158ipi0ic9gir64hrvqv1z-coreutils-8.29/bin:/nix/store/ny5p32137wfyzdm485xfdck21w1gyl3g-gnused-4.5/bin:/nix/store/9f89z51na7w931aja8lqlmhqny9h16cj-gnugrep-3.1/bin:/nix/store/h0lbngpv6ln56hjj59i6l77vxq25flbz-binutils-2.30/bin:/nix/store/dj3sdmwgfqbnn09bdf6spzw5p58ck0jq-pkg-config-0.29.2/bin:/nix/store/xh79gzzar4rag76ycbdb1b8w38npgkg8-pari-2.11.0/bin:/nix/store/9a7nyvdz01q737s5z4jfzi67qfzb0805-libgap-gap-4r8p6/bin:/nix/store/jd9dh10iw52ng41f5s2p3s9qk6w08m1v-libgap-4.8.6/bin:/nix/store/vxlli02yr2zg8bk2my6c41qph7lmps5j-ecl-16.1.2/bin:/nix/store/3klw3b84s5q76mnsi47qhs38kdn3692s-maxima-5.41.0/bin:/nix/store/n8nr2wx29j0yihpxf123z3pgvkp1x351-singular-4.1.1p2/bin:/nix/store/fxnk9rajqm0sfzzak40qbv5inlk7hph5-giac-1.4.9-59/bin:/nix/store/rr3ixb80najx3pfh886rx0rviwd36g0d-palp-2.1/bin:/nix/store/mwrkfvvbf5p5nwmrvnwk1inkn7rsw5nr-R-3.4.4-wrapper/bin:/nix/store/7w3hnhm7h37q53v8vkg0h5rb2yi9frhj-gfan-0.6.2/bin:/nix/store/6b9l87jnv7qjy0sisaky3l10204mk25l-cddlib-0.94j/bin:/nix/store/63z65kj8q1wg8gq0mk6xds2ag1kimyw7-jmol-14.29.17/bin:/nix/store/dkzc98sw9l4s8qppvcz9y4xwqvh91m1q-tachyon-0.99b2/bin:/nix/store/94kd3x6gpxgn78kj9krnh9mcpjslglg6-glpk-4.65/bin:/nix/store/69mdmnc0wlf1sbmjqlikrivi702d5yxv-eclib-20180815/bin:/nix/store/bgvca1jyx20m05slvwv41hlxsgcy292a-sympow-1.018.1/bin:/nix/store/8a4523mgkla62qdgig7y84a7g9q6wg6a-nauty-26r10/bin:/nix/store/hvy9r5llyscrs99408xfpx6bh66n6zml-sqlite-3.24.0-bin/bin:/nix/store/w6nnqdafvi75bjm0lpyi2xq1rirxy5dh-ppl-1.2/bin:/nix/store/kaas1f9r3s6z84n9cpvsn1kzkm8kx6kg-ecm-7.0.4/bin:/nix/store/rm6nwkdp668ck14lln8kjmkkqxw4xlh6-lcalc-1.23/bin:/nix/store/ykgs3899cb5j21x2sidc97cb9mrbljhz-rubiks-20070912/bin:/nix/store/95xwp9kcqhgf71sp78b3i7r8np7yy36w-flintqs-1.0/bin:/home/leo/bin:/run/wrappers/bin:/home/leo/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/etc/profiles/per-user/leo/bin'
        with kwargs:
    {'cwd': u'/home/leo/Documents/ownCloud-lip6/Documents/Code/Sampling_small_basis', 'stdin': -1, 'preexec_fn': <function <lambda> at 0x7f4e29760668>, 'stderr': None, 'stdout': None}
    
[E 10:53:00.277 NotebookApp] Uncaught exception POST /api/sessions (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
        raise_exc_info(self._exc_info)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
        type=mtype))
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
        raise_exc_info(self._exc_info)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
        raise_exc_info(self._exc_info)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
        raise_exc_info(self._exc_info)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
        **kw)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/subprocess.py", line 394, in __init__
        errread, errwrite)
      File "/nix/store/4l2ld8s0qnv8rriknmsmz70z0hdg3832-python-2.7.15-env/lib/python2.7/subprocess.py", line 1047, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
[W 10:53:00.301 NotebookApp] Unhandled error
[E 10:53:00.302 NotebookApp] {
      "Content-Length": "164", 
      "Accept-Language": "en-US,en;q=0.5", 
      "Accept-Encoding": "gzip, deflate", 
      "X-Xsrftoken": "2|bf6b489d|9ea39628e62de82a62a4b62ce21ddc22|1539678701", 
      "X-Requested-With": "XMLHttpRequest", 
      "Host": "localhost:8888", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0", 
      "Connection": "keep-alive", 
      "Referer": "http://localhost:8888/notebooks/Documents/ownCloud-lip6/Documents/Code/Sampling_small_basis/sampling_small_basis.ipynb", 
      "Cookie": "_xsrf=2|bf6b489d|9ea39628e62de82a62a4b62ce21ddc22|1539678701; username-localhost-8888=\"2|1:0|10:1539678797|23:username-localhost-8888|44:OGEyZDhlM2VkNTA3NDM4Yjg4ZDg1NjBmNTAwNjdhYzg=|34c95451e7a2fbf81615c4286a276726e1b28052df0baa54e77404d40ff8f029\"", 
      "Content-Type": "application/json"
    }
[E 10:53:00.302 NotebookApp] 500 POST /api/sessions (::1) 201.46ms referer=http://localhost:8888/notebooks/Documents/ownCloud-lip6/Documents/Code/Sampling_small_basis/sampling_small_basis.ipynb
[W 10:53:05.082 NotebookApp] 404 GET /static/components/MathJax/fonts/HTML-CSS/TeX/otf/MathJax_Script-Regular.otf (::1) 41.06ms referer=http://localhost:8888/notebooks/Documents/ownCloud-lip6/Documents/Code/Sampling_small_basis/sampling_small_basis.ipynb
[W 10:53:05.084 NotebookApp] 404 GET /static/components/MathJax/fonts/HTML-CSS/TeX/otf/MathJax_AMS-Regular.otf (::1) 1.16ms referer=http://localhost:8888/notebooks/Documents/ownCloud-lip6/Documents/Code/Sampling_small_basis/sampling_small_basis.ipynb
^C[I 10:55:44.376 NotebookApp] interrupted
```

### Steps to reproduce

Install sage, tested on both latest nixos-unstable (that took ages to compile), and using the one provided here:

```
let pinnedPkgs1809 = import (builtins.fetchTarball { url = https://releases.nixos.org/nixos/18.09/nixos-18.09.888.08005ede0fc/nixexprs.tar.xz; }) {};
[...]
environment.systemPackages = [ pinnedPkgs1809.sage ];
[...]
```

Then run `sage -n jupyter` and try to open a sage notebook. You should see on the top right a red error "Kernel error", and the console should display the above errors

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.75, NixOS, 19.03pre155123.32bcd72bf28 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(leo): `""`
 - channels(root): `"nixos-19.03pre155123.32bcd72bf28"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by timokau** [comment]
Thanks for the report :)

The immediate cause for the error is that `<sage.lib>/share/jupyter/kernels/sagemath/kernel.json` contains ` "argv": ["/build/sage-src-8.3/bin/sage, ..."` while it should be ` "argv": ["<sage>/bin/sage", ...`.

I have never used jupyter so I'm not sure if that is all. Integrating with https://github.com/NixOS/nixpkgs/pull/33673 would probably be good / maybe be necessary. I don't know when/if I'll get to debugging this since I don't currently use it myself, but I'll happily help you do it if you want to try.

Note that the regular sage cli does work.

**Comment by timokau** [comment]
This is now fixed in master.
