### ISSUE TITLE
"nox-review wip" fails with "_gdbm.error: Malformed database file header"

### ISSUE THREAD

**Issue by das-g** [NixOS/nixpkgs#48878]
## Issue description

`nox-review wip` fails with `_gdbm.error: Malformed database file header`.

### Steps to reproduce

On NixOS 18.09:

1. `cd` to a clone of https://github.com/NixOS/nixpkgs 
2. `nix-shell -p nox --run "nox-review wip --against HEAD^"`

#### Expected

The builds affected by the last commit are being tested.

#### Observed

```
Traceback (most recent call last):
  File "/nix/store/ffpdsda5hm017fx48170ad2wxhllk3r4-nox-0.0.6/bin/.nox-review-wrapped", line 12, in <module>
    sys.exit(cli())
  File "/nix/store/7v2xsnl1svflfqm73hnbbmhmm4mvwi0s-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/7v2xsnl1svflfqm73hnbbmhmm4mvwi0s-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nix/store/7v2xsnl1svflfqm73hnbbmhmm4mvwi0s-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/7v2xsnl1svflfqm73hnbbmhmm4mvwi0s-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/7v2xsnl1svflfqm73hnbbmhmm4mvwi0s-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/7v2xsnl1svflfqm73hnbbmhmm4mvwi0s-python3.6-click-6.7/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/ffpdsda5hm017fx48170ad2wxhllk3r4-nox-0.0.6/lib/python3.6/site-packages/nox/review.py", line 71, in _
    f(*args, **kwargs)
  File "/nix/store/ffpdsda5hm017fx48170ad2wxhllk3r4-nox-0.0.6/lib/python3.6/site-packages/nox/review.py", line 106, in wip
    attrs = differences(packages_for_sha(sha),
  File "/nix/store/bkfmsfnzpvgy07ajis3zwpslic75g7pg-python3.6-dogpile.cache-0.6.7/lib/python3.6/site-packages/dogpile/cache/region.py", line 1270, in decorate
    should_cache_fn)
  File "/nix/store/bkfmsfnzpvgy07ajis3zwpslic75g7pg-python3.6-dogpile.cache-0.6.7/lib/python3.6/site-packages/dogpile/cache/region.py", line 864, in get_or_create
    async_creator) as value:
  File "/nix/store/bkfmsfnzpvgy07ajis3zwpslic75g7pg-python3.6-dogpile.cache-0.6.7/lib/python3.6/site-packages/dogpile/lock.py", line 186, in __enter__
    return self._enter()
  File "/nix/store/bkfmsfnzpvgy07ajis3zwpslic75g7pg-python3.6-dogpile.cache-0.6.7/lib/python3.6/site-packages/dogpile/lock.py", line 86, in _enter
    value = value_fn()
  File "/nix/store/bkfmsfnzpvgy07ajis3zwpslic75g7pg-python3.6-dogpile.cache-0.6.7/lib/python3.6/site-packages/dogpile/cache/region.py", line 819, in get_value
    value = self.backend.get(key)
  File "/nix/store/bkfmsfnzpvgy07ajis3zwpslic75g7pg-python3.6-dogpile.cache-0.6.7/lib/python3.6/site-packages/dogpile/cache/backends/file.py", line 220, in get
    with self._dbm_file(False) as dbm:
  File "/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/nix/store/bkfmsfnzpvgy07ajis3zwpslic75g7pg-python3.6-dogpile.cache-0.6.7/lib/python3.6/site-packages/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/lib/python3.6/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: Malformed database file header
```

This also occurs without `--against HEAD^` if there are uncommitted changes.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.932.09195057114"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by symphorien** [comment]
iirc nox has a cache in /tmp, remove it and everything should work.

**Comment by das-g** [comment]
Yep, that worked:
```bash
rm /tmp/nox.dbm.${USER}
```

I guess `nox` could attempt that itself or at least give a hint, but that'd probably be more of a feature request for https://github.com/madjar/nox, so I'm closing this bug report.
