### ISSUE TITLE
ranger: NameError: name 're' is not defined

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nixpkgs#49372]
## Issue description

`ranger` crashes on start:

```
❯ ranger /mnt/stick/
ranger version: ranger-master 1.9.1
Python version: 3.6.6 (default, Jun 27 2018, 05:47:41) [GCC 7.3.0]
Locale: en_US.UTF-8
Traceback (most recent call last):
  File "/nix/store/v4z90cjcbnyj584432d5fdr69n6dz5sg-ranger-1.9.1/lib/python3.6/site-packages/ranger/core/main.py", line 120, in main
    load_settings(fm, args.clean)
  File "/nix/store/v4z90cjcbnyj584432d5fdr69n6dz5sg-ranger-1.9.1/lib/python3.6/site-packages/ranger/core/main.py", line 350, in load_settings
    import commands as commands_custom
  File "/home/asymmetric/.config/ranger/commands.py", line 348, in <module>
    class setlocal(set_):
  File "/home/asymmetric/.config/ranger/commands.py", line 353, in setlocal
    PATH_RE = re.compile(r'^\s*path="?(.*?)"?\s*$')
NameError: name 're' is not defined
ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

### Steps to reproduce

```
$ nix-shell -p ranger
$ ranger
```

## Technical details

```
❯ nixos-version
18.09.892.c06f5302f63 (Jellyfish)
```

**Comment by jethrokuan** [comment]
I suspect that your local ranger config, in `commands.py`, does not have an `import re` statement
