### ISSUE TITLE
gnu-crypt.h missing, causes `pip install bcrypt==1.0.2` to fail

### ISSUE THREAD

**Issue by numinit** [NixOS/nixpkgs#49724]
## Issue description

`pip install bcrypt` fails on NixOS 18.09.

### Steps to reproduce

run `pip install bcrypt==1.0.2` or something that depends on it, such as `realms-wiki`

```
Collecting bcrypt==1.0.2 (from realms-wiki)
  Using cached https://files.pythonhosted.org/packages/50/17/ba03213ec9542b259af9b67433f3017ea31e382af98e466aee5fcb1718cb/bcrypt-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    In file included from /nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/include/python2.7/Python.h:47:0,
                     from bcrypt/__pycache__/_cffi_677459_d17cc0.c:2:
    bcrypt/crypt_blowfish-1.2/crypt.h:17:10: fatal error: gnu-crypt.h: No such file or directory
     #include <gnu-crypt.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-UjDQia/bcrypt/setup.py", line 28, in <module>
        from bcrypt import __about__, _ffi
      File "bcrypt/__init__.py", line 71, in <module>
        ).hexdigest()[:6],
      File "/nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/lib/python2.7/site-packages/cffi/api.py", line 451, in verify
        lib = self.verifier.load_library()
      File "/nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/lib/python2.7/site-packages/cffi/verifier.py", line 104, in load_library
        self._compile_module()
      File "/nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/lib/python2.7/site-packages/cffi/verifier.py", line 201, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
      File "/nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

If I forcibly link `crypt.h` to `gnu-crypt.h`, then there is a different error:

```
Collecting bcrypt==1.0.2 (from realms-wiki)
  Downloading https://files.pythonhosted.org/packages/50/17/ba03213ec9542b259af9b67433f3017ea31e382af98e466aee5fcb1718cb/bcrypt-1.0.2.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 3.9MB/s
    Complete output from command python setup.py egg_info:
    In file included from bcrypt/__pycache__/_cffi_677459_d17cc0.c:212:0:
    bcrypt/crypt_blowfish-1.2/ow-crypt.h:27:14: error: conflicting types for ‘crypt_r’
     extern char *crypt_r(__const char *key, __const char *setting, void *data);
                  ^~~~~~~
    In file included from bcrypt/crypt_blowfish-1.2/crypt.h:17:0,
                     from /nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/include/python2.7/Python.h:47,
                     from bcrypt/__pycache__/_cffi_677459_d17cc0.c:2:
    /nix/store/akak0rxhbi4n87z3nx78ipv76frvj841-glibc-2.27-dev/include/gnu-crypt.h:60:14: note: previous declaration of ‘crypt_r’ was here
     extern char *crypt_r (const char *__key, const char *__salt,
                  ^~~~~~~
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-D5WZAs/bcrypt/setup.py", line 28, in <module>
        from bcrypt import __about__, _ffi
      File "bcrypt/__init__.py", line 71, in <module>
        ).hexdigest()[:6],
      File "/nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/lib/python2.7/site-packages/cffi/api.py", line 451, in verify
        lib = self.verifier.load_library()
      File "/nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/lib/python2.7/site-packages/cffi/verifier.py", line 104, in load_library
        self._compile_module()
      File "/nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/lib/python2.7/site-packages/cffi/verifier.py", line 201, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
      File "/nix/store/kl6d5j90idkjn6vhy30sg9qm39n5bm10-python-2.7.15-env/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1

    ----------------------------------------
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.78, NixOS, 18.09.1023.06fb0253afa (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment]
Running `pip` is not supported. You already provide a Python environment that includes `bcrypt`, so why run `pip` again?

**Comment by numinit** [comment]
`realms-wiki` seems to be pinned to a specific version of bcrypt that isn't provided by nixpkgs.

**Comment by FRidh** [comment]
You can provide your own bcrypt Python package.

**Comment by Artturin** [comment]
i assume this is some legacy header name which isn't used anymore and should be fixed upstream/ is probably already fixed as its 2023
