### ISSUE TITLE
nextcloud: make upgrades more robust

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#50251]
## Issue description

Currently, nextcloud is a bit unreliable in doing its upgrades unattended, as `phpfpm-nextcloud.service` issuing the `${occ}/bin/nextcloud-occ upgrade` might get executed before the database is able to accept requests:

```
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: An unhandled exception has been thrown:
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/DB/Connection.php:64
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: Stack trace:
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #0 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #1 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #2 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #3 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #4 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #5 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #6 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/DB/ConnectionFactory.php(152): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #7 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/Server.php(630): OC\DB\ConnectionFactory->getConnection('mysql', Array)
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #8 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #9 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OCP\\IDBConnecti...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #10 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDBConnecti...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #11 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OCP\\IDBConnecti...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #12 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #13 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('DatabaseConnect...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #14 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #15 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/Server.php(1532): OC\ServerContainer->query('DatabaseConnect...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #16 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/Server.php(352): OC\Server->getDatabaseConnection()
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #17 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #18 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #19 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #20 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(68): OC\ServerContainer->query('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #21 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #22 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #23 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #24 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(68): OC\ServerContainer->query('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #25 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #26 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #27 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #28 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #29 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #30 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #31 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #32 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/Server.php(364): OC\ServerContainer->query('OC\\Authenticati...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #33 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #34 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OCP\\IUserSessio...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #35 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IUserSessio...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #36 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OCP\\IUserSessio...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #37 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #38 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('UserSession')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #39 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #40 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/Server.php(1408): OC\ServerContainer->query('UserSession')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #41 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/Server.php(683): OC\Server->getUserSession()
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #42 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #43 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\App\\AppManag...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #44 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\App\\AppManag...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #45 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OC\\App\\AppManag...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #46 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #47 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('AppManager')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #48 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #49 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/Server.php(1703): OC\ServerContainer->query('AppManager')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #50 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/legacy/app.php(342): OC\Server->getAppManager()
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #51 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/private/legacy/app.php(113): OC_App::getEnabledApps()
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #52 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/base.php(654): OC_App::loadApps(Array)
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #53 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/lib/base.php(1068): OC::init()
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #54 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/console.php(46): require_once('/nix/store/q437...')
Nov 11 22:27:45 nextcloud 4sj0rmdsaf2yffdpgdjhd643g4zy44z2-unit-script-nextcloud-setup-start[191]: #55 /nix/store/q437s4v9456ppvfyq8wndp5c6rdq563g-nextcloud-14.0.3/occ(11): require_once('/nix/store/q437...')
```

### Steps to reproduce
Upgrade from nextcloud 14.0.1 to 14.0.3 (used a local mysql database).

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.74, NixOS, 19.03pre-git (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre158246.6141939d6e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

cc @globin @fpletz

**Comment by flokli** [comment]
We could probably fix this by adding dependencies to the mysql / postgresql database if dbhost is localhost, or add some more `RestartSec` to the nextcloud units, I wanted to collect opinions first :-)
