### ISSUE TITLE
xfce4 and dbus issues

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#50355]
## Issue description
I cannot suspend, reboot, or mess with bluetooth on my xfce4 environment. I believe these issues all stem from some issue with my dbus setup.

### Steps to reproduce
issue a reboot command
```
[mog@ford:~]$ reboot
Failed to set wall message, ignoring: Interactive authentication required.
Failed to reboot system via logind: Interactive authentication required.
Failed to talk to init daemon.
```
run blueman-applet
```
[mog@ford:~]$ blueman-applet 

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.008: Theme parsing error: gtk-widgets.css:153:27: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.008: Theme parsing error: gtk-widgets.css:154:26: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.008: Theme parsing error: gtk-widgets.css:578:27: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.008: Theme parsing error: gtk-widgets.css:579:28: The style property GtkWidget:interior-focus is deprecated and shouldn't be used anymore. It will be removed in a future version

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.008: Theme parsing error: gtk-widgets.css:580:28: The style property GtkButton:default-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.008: Theme parsing error: gtk-widgets.css:581:26: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.009: Theme parsing error: gtk-widgets.css:1333:25: The style property GtkRange:slider-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.009: Theme parsing error: gtk-widgets.css:1334:25: The style property GtkRange:stepper-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.009: Theme parsing error: gtk-widgets.css:1335:34: The style property GtkScrollbar:min-slider-length is deprecated and shouldn't be used anymore. It will be removed in a future version

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.009: Theme parsing error: gtk-widgets.css:1336:28: The style property GtkRange:stepper-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.009: Theme parsing error: gtk-widgets.css:1337:34: The style property GtkRange:trough-under-steppers is deprecated and shouldn't be used anymore. It will be removed in a future version

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.010: Theme parsing error: gtk-widgets.css:1594:13: not a number

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.010: Theme parsing error: gtk-widgets.css:1594:13: Expected a string.

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.010: Theme parsing error: gtk-widgets.css:1976:11: not a number

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.010: Theme parsing error: gtk-widgets.css:1976:11: Expected a string.

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.011: Theme parsing error: gtk-widgets.css:2526:11: not a number

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.011: Theme parsing error: gtk-widgets.css:2526:11: Expected a string.

(.blueman-applet-wrapped:7867): Gtk-WARNING **: 12:34:16.011: Theme parsing error: applications.css:21:0: Expected a valid selector
blueman-applet version 2.0.6 starting
Stale PID, overwriting
_________
Load (/nix/store/53ym0lplhxjj8x1ad97fwv9670wsv8wr-blueman-2.0.6/lib/python3.6/site-packages/blueman/main/PluginManager.py:60)
['StandardItems', 'PPPSupport', 'StatusIcon', 'RecentConns', 'Networking', 'NMDUNSupport', 'AuthAgent', 'TransferService', 'PowerManager', 'KillSwitch', 'SerialManager', 'ShowConnected', 'NMPANSupport', 'NetUsage', 'Headset', 'AppIndicator', 'DhcpClient', 'Menu', 'GameControllerWakelock', 'DiscvManager', 'DBusService', 'ExitItem'] 
ERROR:dbus.proxies:Introspect error on :1.2:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 3 matched rules; type="method_call", sender=":1.77" (uid=1000 pid=7867 comm="/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.2" (uid=0 pid=887 comm="/nix/store/h6vhiy33wc9gvfbb3zbv0ii3fkij19s0-bluez-")
Traceback (most recent call last):
  File "/nix/store/53ym0lplhxjj8x1ad97fwv9670wsv8wr-blueman-2.0.6/bin/..blueman-applet-wrapped-wrapped", line 122, in <module>
    BluemanApplet()
  File "/nix/store/53ym0lplhxjj8x1ad97fwv9670wsv8wr-blueman-2.0.6/bin/..blueman-applet-wrapped-wrapped", line 64, in __init__
    self.Plugins.Load()
  File "/nix/store/53ym0lplhxjj8x1ad97fwv9670wsv8wr-blueman-2.0.6/lib/python3.6/site-packages/blueman/main/PluginManager.py", line 90, in Load
    __import__(self.module_path.__name__ + ".%s" % plugin, None, None, [])
  File "/nix/store/53ym0lplhxjj8x1ad97fwv9670wsv8wr-blueman-2.0.6/lib/python3.6/site-packages/blueman/plugins/applet/AuthAgent.py", line 9, in <module>
    import blueman.main.applet.BluezAgent as BluezAgent
  File "/nix/store/53ym0lplhxjj8x1ad97fwv9670wsv8wr-blueman-2.0.6/lib/python3.6/site-packages/blueman/main/applet/BluezAgent.py", line 23, in <module>
    from blueman.bluez.Agent import Agent, AgentMethod
  File "/nix/store/53ym0lplhxjj8x1ad97fwv9670wsv8wr-blueman-2.0.6/lib/python3.6/site-packages/blueman/bluez/Agent.py", line 48, in <module>
    class Agent(dbus.service.Object):
  File "/nix/store/53ym0lplhxjj8x1ad97fwv9670wsv8wr-blueman-2.0.6/lib/python3.6/site-packages/blueman/bluez/Agent.py", line 56, in Agent
    @AgentMethod
  File "/nix/store/53ym0lplhxjj8x1ad97fwv9670wsv8wr-blueman-2.0.6/lib/python3.6/site-packages/blueman/bluez/Agent.py", line 38, in AgentMethod
    if BlueZInterface.get_interface_version()[0] < 5:
  File "/nix/store/53ym0lplhxjj8x1ad97fwv9670wsv8wr-blueman-2.0.6/lib/python3.6/site-packages/blueman/bluez/BlueZInterface.py", line 17, in get_interface_version
    introspection = dbus.Interface(obj, 'org.freedesktop.DBus.Introspectable').Introspect()
  File "/nix/store/pa51jkhyiflx6b4r0w1pnzgnawn2dcwk-python3.6-dbus-python-1.2.4/lib/python3.6/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/nix/store/pa51jkhyiflx6b4r0w1pnzgnawn2dcwk-python3.6-dbus-python-1.2.4/lib/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/nix/store/pa51jkhyiflx6b4r0w1pnzgnawn2dcwk-python3.6-dbus-python-1.2.4/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 3 matched rules; type="method_call", sender=":1.77" (uid=1000 pid=7867 comm="/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.2" (uid=0 pid=887 comm="/nix/store/h6vhiy33wc9gvfbb3zbv0ii3fkij19s0-bluez-")

```
## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
[mog@ford:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.35 MiB download, 1.59 MiB unpacked):
  /nix/store/63j8mi5vjyxfc89rhjknwxaxqg3a2sx2-paxctl-0.9
  /nix/store/bqp3d4yhpx6h60fv8jww5id0nkm44034-patchelf-0.9
  /nix/store/i6vl5lwlz5jbkg4r6p340dwmj6fha3xq-stdenv-linux
  /nix/store/kic17fw8wil74k04kzh3dha43izrr9j3-bash-interactive-4.4-p23-dev
  /nix/store/ql3azyviwyc6w73h6prk1j2945skfapf-gnumake-4.2.1
copying path '/nix/store/kic17fw8wil74k04kzh3dha43izrr9j3-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/ql3azyviwyc6w73h6prk1j2945skfapf-gnumake-4.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/bqp3d4yhpx6h60fv8jww5id0nkm44034-patchelf-0.9' from 'https://cache.nixos.org'...
copying path '/nix/store/63j8mi5vjyxfc89rhjknwxaxqg3a2sx2-paxctl-0.9' from 'https://cache.nixos.org'...
copying path '/nix/store/i6vl5lwlz5jbkg4r6p340dwmj6fha3xq-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.17, NixOS, 18.09.1228.a4c4cbb613c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1228.a4c4cbb613c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by worldofpeace** [comment]
@mogorman
For now you should just delete your user dconf database at `$HOME/.config/dconf/user`.

**Comment by mogorman** [comment]
I don't have a dconf dir? in my $HOME/.config

**Comment by worldofpeace** [comment]
Sorry I somehow misread your issue and read dbus as `dconf` :smile: 

Though that's also strange that you don't have that directory.

**Comment by mogorman** [comment]
more info about commands not working for me 
```
Nov 14 23:34:41 ford pkexec[2670]: mog: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/] [COMMAND=/nix/store/0mjwvqrzrzfdrqnxdcykymqx5gsr2m6g-xfce4-power-manager-1.4.4/sbin/xfpm-power-backlight-helper --set-brightness 1364]
Nov 14 23:30:55 ford xsession[1228]: ERROR:dbus.proxies:Introspect error on :1.2:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 3 matched rules; type="method_call", sender=":1.66" (uid=1000 pid=2448 comm="/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.2" (uid=0 pid=885 comm="/nix/store/h6vhiy33wc9gvfbb3zbv0ii3fkij19s0-bluez-")
```

**Comment by mogorman** [comment]
looking into it more I assume its related to this https://github.com/NixOS/nixpkgs/issues/18012

**Comment by mogorman** [comment]
also I just tried swapping to gdm and then flipped back to lightdm and the problem has gone away. I am not sure if it will come back in a reboot though as it has before. I can provide any journal logs if you think it might help

**Comment by mogorman** [comment]
this issue seems to have been resolved by updates
