### ISSUE TITLE
spidermonkey_52 doesn't cross compile

### ISSUE THREAD

**Issue by eburimu** [NixOS/nixpkgs#51134]
## Issue description

```
 9915 these derivations will be built:
 9916   /nix/store/is6ydjhpkbnan086v5hrgwdp4x33pnks-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf.drv
 9917 building '/nix/store/is6ydjhpkbnan086v5hrgwdp4x33pnks-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf.drv'...
 9918 unpacking sources
 9919 unpacking source archive /nix/store/frbpzhpy3kd4ry3pdrlivk80xfyc5jhl-firefox-52.9.0esr.source.tar.xz
 9920 source root is firefox-52.9.0esr
 9921 setting SOURCE_DATE_EPOCH to timestamp 1529607259 of file firefox-52.9.0esr/sourcestamp.txt
 9922 patching sources
 9923 applying patch /nix/store/sygypj8py0wmg6rpjj0689fjcgbjflpr-mozjs52-disable-mozglue.patch
 9924 patching file js/src/old-configure.in
 9925 patching file mozglue/build/moz.build
 9926 updateAutotoolsGnuConfigScriptsPhase
 9927 Updating Autotools / GNU config script to a newer upstream version: ./build/autoconf/config.sub
 9928 Updating Autotools / GNU config script to a newer upstream version: ./js/src/ctypes/libffi/config.sub
 9929 Updating Autotools / GNU config script to a newer upstream version: ./modules/freetype2/builds/unix/config.sub
 9930 Updating Autotools / GNU config script to a newer upstream version: ./intl/icu/source/config.sub
 9931 Updating Autotools / GNU config script to a newer upstream version: ./toolkit/crashreporter/google-breakpad/autotools/config.sub
 9932 Updating Autotools / GNU config script to a newer upstream version: ./nsprpub/build/autoconf/config.sub
 9933 Updating Autotools / GNU config script to a newer upstream version: ./ipc/chromium/src/third_party/libevent/config.sub
 9934 Updating Autotools / GNU config script to a newer upstream version: ./memory/jemalloc/src/build-aux/config.sub
 9935 Updating Autotools / GNU config script to a newer upstream version: ./build/autoconf/config.guess
 9936 Updating Autotools / GNU config script to a newer upstream version: ./js/src/ctypes/libffi/config.guess
 9937 Updating Autotools / GNU config script to a newer upstream version: ./modules/freetype2/builds/unix/config.guess
 9938 Updating Autotools / GNU config script to a newer upstream version: ./intl/icu/source/config.guess
 9939 Updating Autotools / GNU config script to a newer upstream version: ./toolkit/crashreporter/google-breakpad/autotools/config.guess
 9940 Updating Autotools / GNU config script to a newer upstream version: ./nsprpub/build/autoconf/config.guess
 9941 Updating Autotools / GNU config script to a newer upstream version: ./ipc/chromium/src/third_party/libevent/config.guess
 9942 Updating Autotools / GNU config script to a newer upstream version: ./memory/jemalloc/src/build-aux/config.guess
 9943 configuring
 9944 fixing libtool script ./ctypes/libffi/ltmain.sh
 9945 configure flags: --prefix=/nix/store/4wy3i41gv360n1grnx7wipp88nh6r7cc-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf --with-system-nspr --with-system-zlib --with-system-icu --with-intl-api --enable-readline --enable-shared-js --\
      build=x86_64-unknown-linux-gnu --host=armv7l-unknown-linux-gnueabihf --includedir=/nix/store/w980pzix89040x8shxv44ylvr5infmj2-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf-dev/include
 9946 Creating Python environment
 9947 Traceback (most recent call last):
 9948   File "./../../configure.py", line 107, in <module>
 9949     sys.exit(main(sys.argv))
 9950   File "./../../configure.py", line 26, in main
 9951     sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
 9952   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/configure/__init__.py", line 334, in run
 9953     self.include_file(path)
 9954   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/configure/__init__.py", line 325, in include_file
 9955     exec_(code, self)
 9956   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/util.py", line 59, in exec_
 9957     exec(object, globals, locals)
 9958   File "/build/firefox-52.9.0esr/moz.configure", line 7, in <module>
 9959     include('build/moz.configure/init.configure')
 9960   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/configure/__init__.py", line 627, in include_impl
 9961     self.include_file(what)
 9962   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/configure/__init__.py", line 325, in include_file
 9963     exec_(code, self)
 9964   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/util.py", line 59, in exec_
 9965     exec(object, globals, locals)
 9966   File "/build/firefox-52.9.0esr/build/moz.configure/init.configure", line 137, in <module>
 9967     @imports('distutils.sysconfig')
 9968   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/configure/__init__.py", line 610, in decorator
 9969     depends = DependsFunction(self, func, dependencies, when=when)
 9970   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/configure/__init__.py", line 69, in __init__
 9971     sandbox._value_for(self)
 9972   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/configure/__init__.py", line 406, in _value_for
 9973     return self._value_for_depends(obj, need_help_dependency)
 9974   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/util.py", line 925, in method_call
 9975     cache[args] = self.func(instance, *args)
 9976   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/configure/__init__.py", line 416, in _value_for_depends
 9977     return obj.result
 9978   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/util.py", line 943, in __get__
 9979     setattr(instance, name, self.func(instance))
 9980   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/configure/__init__.py", line 90, in result
  9981     return self.func(*resolved_args)
  9982   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/configure/__init__.py", line 932, in wrapped
  9983     return new_func(*args, **kwargs)
  9984   File "/build/firefox-52.9.0esr/build/moz.configure/init.configure", line 184, in virtualenv_python
  9985     manager.build(python)
  9986   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/virtualenv.py", line 439, in build
  9987     self.create(python)
  9988   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/virtualenv.py", line 199, in create
  9989     result = self._log_process_output(args, env=env)
  9990   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/virtualenv.py", line 174, in _log_process_output
  9991     stderr=subprocess.STDOUT, **kwargs)
  9992   File "/nix/store/h8i5qadlm6vfxayiizyk37k7f2m1a4h1-python-2.7.15/lib/python2.7/subprocess.py", line 394, in __init__
  9993     errread, errwrite)
  9994   File "/nix/store/h8i5qadlm6vfxayiizyk37k7f2m1a4h1-python-2.7.15/lib/python2.7/subprocess.py", line 1047, in _execute_child
  9995     raise child_exception
  9996 OSError: [Errno 8] Exec format error
  9997 builder for '/nix/store/is6ydjhpkbnan086v5hrgwdp4x33pnks-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf.drv' failed with exit code 1
  9998 error: build of '/nix/store/is6ydjhpkbnan086v5hrgwdp4x33pnks-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf.drv' failed
```

### Steps to reproduce
```
  9996 [void@fermat:~/pi]$ cat ./spidermonkey.sh
  9997 #!/bin/sh
  9998 nix-build -I nixpkgs=/home/void/nixpkgs -E 'let t1 = import <nixpkgs> {}; in let pkgs = import <nixpkgs> { crossSystem = t1.lib.systems.examples.armv7l-hf-multiplatform // { system = "armv7l-linux"; }; }; in pkgs.spidermonkey_52 ' \
       --show-trace
  9999 

```

I'm on staging. I believe this is very similar to https://github.com/NixOS/nixpkgs/issues/50925 . Any Mozilla folks willing to help?

**Comment by eburimu** [comment]
ping @garbas

**Comment by jtojnar** [comment]
Looking at

```ShellSession
$ cat $(nix-instantiate -E 'let t1 = import <nixpkgs> {}; in let pkgs = import <nixpkgs> { crossSystem = t1.lib.systems.examples.armv7l-hf-multiplatform // { system = "armv7l-linux"; }; }; in pkgs.spidermonkey_52') | indent
Derive ([("dev",
	  "/nix/store/wfws2nqq5vrcjxaxa4i227hq8axc24aw-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf-dev",
	  "", ""), ("out",
		    "/nix/store/arnjjlpalaqrabwb6g5gz4qhi38bkrlg-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf",
		    "", "")],
	[("/nix/store/03p6drczzfbrwmw1fyns6ivv29k0c3sx-perl-5.28.0.drv",
	  ["out"]),
	 ("/nix/store/2bkwlv3j63d4rsaz86ni87z3gg6r7amb-nspr-4.20-armv7l-unknown-linux-gnueabihf.drv",
	  ["dev"]),
	 ("/nix/store/4f0d8522wd2p4gwvg651qv3pk4pk6asr-pkg-config-0.29.2.drv",
	  ["out"]),
	 ("/nix/store/aarqym4rvviwpmhiy0l8x91qwqh2dv6c-firefox-52.9.0esr.source.tar.xz.drv",
	  ["out"]),
	 ("/nix/store/c138ri2w891963izlnmpsr4hz1vncxr5-stdenv-linux.drv",
	  ["out"]),
	 ("/nix/store/dgqxc1mx4hpyma16srwfdk580qbyw84n-python-2.7.15.drv",
	  ["out"]),
	 ("/nix/store/diclkjfwxx6lk26v4d21960j1qmbf6k9-zlib-1.2.11-armv7l-unknown-linux-gnueabihf.drv",
	  ["dev"]),
	 ("/nix/store/fd19dd52b1qgc1xy2kj373mwxkxi4dkh-mozjs52-disable-mozglue.patch.drv",
	  ["out"]),
	 ("/nix/store/mqggaqbm6vjr120yf5scpa53qw49rwq9-which-2.21.drv",
	  ["out"]),
	 ("/nix/store/plxz9z09l8gp0bvv52wrhjv67ifim975-readline-6.3p08-armv7l-unknown-linux-gnueabihf.drv",
	  ["dev"]),
	 ("/nix/store/pmpf0ypg8hlbxz0rf3lzq31h85p0zkcm-zip-3.0.drv",["out"]),
	 ("/nix/store/q3a7ckkwg1p1kw8xyz53hasfgjsp6yf9-python-2.7.15-armv7l-unknown-linux-gnueabihf.drv",
	  ["out"]),
	 ("/nix/store/qfhi53mcjirl4k7x6ahh0b7f4pnxxnlv-icu4c-59.1-armv7l-unknown-linux-gnueabihf.drv",
	  ["dev"]),
	 ("/nix/store/wlmr9cbm9zsn6bxx204zpxpbpwg7vxiq-bash-4.4-p23.drv",
	  ["out"]),
	 ("/nix/store/xxsyal223j47byx0zxchw7abqpkjiim8-autoconf-2.13.drv",
	  ["out"])],
	["/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh"],
	"x86_64-linux",
	"/nix/store/r47p5pzx52m3n34vdgqpk5rvqgm0m24m-bash-4.4-p23/bin/bash",
	["-e",
	 "/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh"],
	[("NIX_CFLAGS_COMPILE",
	  "-fno-delete-null-pointer-checks -fno-strict-aliasing -fno-tree-vrp"),
	 ("buildInputs",
	  "/nix/store/r6sb9dswisqvc0yy4qs2rvv9ijlgv7am-readline-6.3p08-armv7l-unknown-linux-gnueabihf-dev /nix/store/dic4xv7fwrz9gycy5v6jr8gx4zkcan0b-icu4c-59.1-armv7l-unknown-linux-gnueabihf-dev /nix/store/lmkrm1l898kmqf728y298g884zns1kxv-zlib-1.2.11-armv7l-unknown-linux-gnueabihf-dev /nix/store/rd0y7ka4xa2r0rm6kkjmd0rwzm7cih0h-nspr-4.20-armv7l-unknown-linux-gnueabihf-dev"),
	 ("builder",
	  "/nix/store/r47p5pzx52m3n34vdgqpk5rvqgm0m24m-bash-4.4-p23/bin/bash"),
	 ("cmakeFlags",
	  "-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=armv7l -DCMAKE_HOST_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_PROCESSOR=x86_64"),
	 ("configureFlags",
	  "--with-system-nspr --with-system-zlib --with-system-icu --with-intl-api --enable-readline --enable-shared-js --build=x86_64-unknown-linux-gnu --host=armv7l-unknown-linux-gnueabihf"),
	 ("depsBuildBuild", ""), ("depsBuildBuildPropagated", ""),
	 ("depsBuildTarget", ""), ("depsBuildTargetPropagated", ""),
	 ("depsHostHost", ""), ("depsHostHostPropagated", ""),
	 ("depsTargetTarget", ""), ("depsTargetTargetPropagated", ""), ("dev",
									"/nix/store/wfws2nqq5vrcjxaxa4i227hq8axc24aw-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf-dev"),
	 ("doCheck", ""), ("doInstallCheck", ""), ("enableParallelBuilding",
						   "1"),
	 ("enableParallelChecking", "1"), ("name",
					   "spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf"),
	 ("nativeBuildInputs",
	  "/nix/store/yjmybx3s76ndijlcjlqj1f9lnirc2gbv-autoconf-2.13 /nix/store/sbg7j9ghnhl3kiw5gck9khhr2wwd5y8f-pkg-config-0.29.2 /nix/store/0ingn8cwwnl84i374hcl6nafsm2c5m2p-perl-5.28.0 /nix/store/gdwjcjydlv4ji4bw8c09rd144rnhb61n-which-2.21 /nix/store/2brlr94ahy3a9mvcjy0qbqpv8zrb7b7s-python-2.7.15 /nix/store/6wbb28y86k69kyx0ikkaa7wq848jsrgg-zip-3.0"),
	 ("out",
	  "/nix/store/arnjjlpalaqrabwb6g5gz4qhi38bkrlg-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf"),
	 ("outputs", "out dev"), ("patches",
				  "/nix/store/sygypj8py0wmg6rpjj0689fjcgbjflpr-mozjs52-disable-mozglue.patch"),
	 ("postInstall",
	  "moveToOutput bin/js52-config \"$dev\"\n# Nuke a static lib.\nrm $out/lib/libjs_static.ajs\n"),
	 ("preConfigure",
	  "export CXXFLAGS=\"-fpermissive\"\nexport LIBXUL_DIST=$out\nexport PYTHON=\"/nix/store/jg2bac7yy6c1x65fcilicwa85l0qv7ws-python-2.7.15-armv7l-unknown-linux-gnueabihf/bin/python2.7\"\nconfigureFlagsArray+=(\"--includedir=$dev/include\")\n\ncd js/src\n\nautoconf\n"),
	 ("propagatedBuildInputs", ""), ("propagatedNativeBuildInputs", ""),
	 ("setOutputFlags", ""), ("src",
				  "/nix/store/frbpzhpy3kd4ry3pdrlivk80xfyc5jhl-firefox-52.9.0esr.source.tar.xz"),
	 ("stdenv",
	  "/nix/store/xj38dq8xhfiz4g688gb1z2yzqs65kdz7-stdenv-linux"),
	 ("strictDeps", "1"), ("system", "x86_64-linux")])
```

it seems that

https://github.com/NixOS/nixpkgs/blob/2570da807715a9027c96a99c17ebc0f860894aaa/pkgs/development/interpreters/spidermonkey/52.nix#L37

pints to a host python instead of the build one. We could probably be explicit `buildPackages.python2.interpreter` but I am not sure it is the correct way.

**Comment by jtojnar** [comment]
Cannot test it due to nspr build failure.

**Comment by eburimu** [comment]
@jtojnar See https://github.com/NixOS/nixpkgs/pull/50807

**Comment by eburimu** [comment]
@jtojnar replcng python2 from buildPackages I get the following:

```
  9943 
  9944 [void@fermat:~/pi]$ sh ./spidermonkey.sh
  9945 these derivations will be built:
  9946   /nix/store/ji3izg5dpr3b2dzv8033crfjzb53nlhg-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf.drv
  9947 building '/nix/store/ji3izg5dpr3b2dzv8033crfjzb53nlhg-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf.drv'...
  9948 unpacking sources
  9949 unpacking source archive /nix/store/frbpzhpy3kd4ry3pdrlivk80xfyc5jhl-firefox-52.9.0esr.source.tar.xz
  9950 source root is firefox-52.9.0esr
  9951 setting SOURCE_DATE_EPOCH to timestamp 1529607259 of file firefox-52.9.0esr/sourcestamp.txt
  9952 patching sources
  9953 applying patch /nix/store/sygypj8py0wmg6rpjj0689fjcgbjflpr-mozjs52-disable-mozglue.patch
  9954 patching file js/src/old-configure.in
  9955 patching file mozglue/build/moz.build
  9956 updateAutotoolsGnuConfigScriptsPhase
  9957 Updating Autotools / GNU config script to a newer upstream version: ./build/autoconf/config.sub
  9958 Updating Autotools / GNU config script to a newer upstream version: ./js/src/ctypes/libffi/config.sub
  9959 Updating Autotools / GNU config script to a newer upstream version: ./modules/freetype2/builds/unix/config.sub
  9960 Updating Autotools / GNU config script to a newer upstream version: ./intl/icu/source/config.sub
  9961 Updating Autotools / GNU config script to a newer upstream version: ./toolkit/crashreporter/google-breakpad/autotools/config.sub
  9962 Updating Autotools / GNU config script to a newer upstream version: ./nsprpub/build/autoconf/config.sub
  9963 Updating Autotools / GNU config script to a newer upstream version: ./ipc/chromium/src/third_party/libevent/config.sub
  9964 Updating Autotools / GNU config script to a newer upstream version: ./memory/jemalloc/src/build-aux/config.sub
  9965 Updating Autotools / GNU config script to a newer upstream version: ./build/autoconf/config.guess
  9966 Updating Autotools / GNU config script to a newer upstream version: ./js/src/ctypes/libffi/config.guess
  9967 Updating Autotools / GNU config script to a newer upstream version: ./modules/freetype2/builds/unix/config.guess
  9968 Updating Autotools / GNU config script to a newer upstream version: ./intl/icu/source/config.guess
  9969 Updating Autotools / GNU config script to a newer upstream version: ./toolkit/crashreporter/google-breakpad/autotools/config.guess
  9970 Updating Autotools / GNU config script to a newer upstream version: ./nsprpub/build/autoconf/config.guess
  9971 Updating Autotools / GNU config script to a newer upstream version: ./ipc/chromium/src/third_party/libevent/config.guess
  9972 Updating Autotools / GNU config script to a newer upstream version: ./memory/jemalloc/src/build-aux/config.guess
  9973 configuring
  9974 fixing libtool script ./ctypes/libffi/ltmain.sh
  9975 configure flags: --prefix=/nix/store/y3aqbadvpm9k9ifbqx5nls85p18vnlsa-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf --with-system-nspr --with-system-zlib --with-system-icu --with-intl-api --enable-readline --enable-shared-js -\
       -build=x86_64-unknown-linux-gnu --host=armv7l-unknown-linux-gnueabihf --includedir=/nix/store/7dwdqfjvi7dc49gbmggxqzgh2s5d7v3y-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf-dev/include
  9976 Creating Python environment
  9977 New python executable in /build/firefox-52.9.0esr/_virtualenv/bin/python2.7
  9978 Also creating executable in /build/firefox-52.9.0esr/_virtualenv/bin/python
  9979 Installing setuptools, pip, wheel...done.
  9980 running build_ext
  9981 copying build/lib.linux-x86_64-2.7/psutil/_psutil_linux.so -> psutil
  9982 copying build/lib.linux-x86_64-2.7/psutil/_psutil_posix.so -> psutil
  9983 
  9984 Reexecuting in the virtualenv
  9985 checking for a shell... /nix/store/06vmwfva8phjx2s8a53xvq0p062kyqsf-bash-4.4-p23/bin/bash
  9986 checking for host system type... armv7l-unknown-linux-gnueabihf
  9987 checking for target system type... armv7l-unknown-linux-gnueabihf
  9988 checking for the Android toolchain directory... not found
  9989 Traceback (most recent call last):
  9990   File "./../../configure.py", line 107, in <module>
  9991     sys.exit(main(sys.argv))
  9992   File "./../../configure.py", line 26, in main
  9993     sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  9994   File "/build/firefox-52.9.0esr/python/mozbuild/mozbuild/configure/__init__.py", line 359, in run
  9995     raise InvalidOptionError('Unknown option: %s' % without_value)
  9996 mozbuild.configure.options.InvalidOptionError: Unknown option: --build
  9997 builder for '/nix/store/ji3izg5dpr3b2dzv8033crfjzb53nlhg-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf.drv' failed with exit code 1
  9998 error: build of '/nix/store/ji3izg5dpr3b2dzv8033crfjzb53nlhg-spidermonkey-52.9.0-armv7l-unknown-linux-gnueabihf.drv' failed
```

**Comment by jtojnar** [comment]
We should probably upgrade to spdiermonkey 60 like Arch https://www.archlinux.org/packages/extra/x86_64/js60/ (cc @hedning), though I doubt it will fix this.

**Comment by erictapen** [comment]
Right now on `nixos-unstable`, I can successfully run `nix build nixpkgs.pkgsCross.aarch64-multiplatform.spidermonkey_52` so I guess this can be closed.
