### ISSUE TITLE
Older minecraft versions don't start

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#51348]
## Issue description

The game don't start and i get this messages in console:

```
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
OpenJDK 64-Bit Server VM warning: You have loaded library /home/davidak/.minecraft/versions/1.11.2/1.11.2-natives-48756259345294/liblwjgl.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/davidak/.minecraft/versions/1.11.2/1.11.2-natives-48756259345294/liblwjgl64.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at bes.I(SourceFile:2777)
	at net.minecraft.client.main.Main.main(SourceFile:39)
```

See full terminal output: https://gist.github.com/davidak/a5c8bba4162b1bc680fff2522e165a57

The Launcher is version 1.6.89-j but my friend on windows has 2.x, so we might be able to fix this with an update.

@Infinisil 

### Steps to reproduce

1. install minecraft
2. start older version of game <1.13.x

I tested 1.10.2,  1.11.2,  1.12.2,  1.6.4 and 1.7.10.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.84, NixOS, 18.09.1446.db561c90ef3 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.09.1446.db561c90ef3, nixos-hardware, nixos-unstable-19.03pre159472.80738ed9dc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Infinisil** [comment]
Yeah that was my mistake, see above PR for a fix

**Comment by davidak** [comment]
@Infinisil Thanks for the fast fix!

I used [MultiMC](https://multimc.org/) now which is an open source Launcher where you can install plugins and mods directly.
