### ISSUE TITLE
yubikey-manager list fails

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#51362]
## Issue description

When I run `ykman list` as a regular user or root, it fails
```
$ ykman list
Traceback (most recent call last):
  File "/nix/store/x97jzk0j73jx1cvmnsqpmkkjr2biyafd-python2.7-yubikey-manager-1.0.0/bin/.ykman-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/x97jzk0j73jx1cvmnsqpmkkjr2biyafd-python2.7-yubikey-manager-1.0.0/lib/python2.7/site-packages/ykman/cli/__main__.py", line 212, in main
    cli(obj={})
  File "/nix/store/d4aaw6k3m9bxg1qq8zacp026xzanvjvy-python2.7-click-6.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/d4aaw6k3m9bxg1qq8zacp026xzanvjvy-python2.7-click-6.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nix/store/d4aaw6k3m9bxg1qq8zacp026xzanvjvy-python2.7-click-6.7/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/d4aaw6k3m9bxg1qq8zacp026xzanvjvy-python2.7-click-6.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/d4aaw6k3m9bxg1qq8zacp026xzanvjvy-python2.7-click-6.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/d4aaw6k3m9bxg1qq8zacp026xzanvjvy-python2.7-click-6.7/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/x97jzk0j73jx1cvmnsqpmkkjr2biyafd-python2.7-yubikey-manager-1.0.0/lib/python2.7/site-packages/ykman/cli/__main__.py", line 172, in list_keys
    for dev in list_devices():
  File "/nix/store/x97jzk0j73jx1cvmnsqpmkkjr2biyafd-python2.7-yubikey-manager-1.0.0/lib/python2.7/site-packages/ykman/descriptor.py", line 152, in list_devices
    for d in _list_drivers(transports):
  File "/nix/store/x97jzk0j73jx1cvmnsqpmkkjr2biyafd-python2.7-yubikey-manager-1.0.0/lib/python2.7/site-packages/ykman/descriptor.py", line 138, in _list_drivers
    for dev in open_ccid():
  File "/nix/store/x97jzk0j73jx1cvmnsqpmkkjr2biyafd-python2.7-yubikey-manager-1.0.0/lib/python2.7/site-packages/ykman/driver_ccid.py", line 273, in open_devices
    readers = _list_readers()
  File "/nix/store/x97jzk0j73jx1cvmnsqpmkkjr2biyafd-python2.7-yubikey-manager-1.0.0/lib/python2.7/site-packages/ykman/driver_ccid.py", line 263, in _list_readers
    return System.readers()
  File "/nix/store/ry26hpjw90q30xvbiz79p2aljpimml5b-python2.7-pyscard-1.9.7/lib/python2.7/site-packages/smartcard/System.py", line 42, in readers
    return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
  File "/nix/store/ry26hpjw90q30xvbiz79p2aljpimml5b-python2.7-pyscard-1.9.7/lib/python2.7/site-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
    zreaders += fm(groups)
  File "/nix/store/ry26hpjw90q30xvbiz79p2aljpimml5b-python2.7-pyscard-1.9.7/lib/python2.7/site-packages/smartcard/pcsc/PCSCReader.py", line 108, in readers
    hcontext = PCSCContext().getContext()
  File "/nix/store/ry26hpjw90q30xvbiz79p2aljpimml5b-python2.7-pyscard-1.9.7/lib/python2.7/site-packages/smartcard/pcsc/PCSCContext.py", line 53, in __init__
    PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
  File "/nix/store/ry26hpjw90q30xvbiz79p2aljpimml5b-python2.7-pyscard-1.9.7/lib/python2.7/site-packages/smartcard/pcsc/PCSCContext.py", line 40, in __init__
    raise EstablishContextException(hresult)
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'
```

### Steps to reproduce

1. Install yubikey-manager
1. `ykman list`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.43, NixOS, 18.09.git.a4c4cbb (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `""`
 - channels(ryantm): `""`
 - nixpkgs: `/home/ryantm/p/nixpkgs`
```

cc @beley as maintainer and @dtzWill as last updater

**Comment by ryantm** [comment]
Configuring NixOS with
```
services.pcscd.enable = true;
```
Fixed it.
