### ISSUE TITLE
Cannot depend on pytorch + CUDA in sandboxed build

### ISSUE THREAD

**Issue by kwohlfahrt** [NixOS/nixpkgs#51671]
## Issue description

Sandboxed builds cannot depend on pytorch + CUDA, or their build fails with:

```
    from torch._C import *
ImportError: /nix/store/qbphwmip0jymg66csbm322i63xx10azd-python3.7-pytorch-0.4.1/lib/python3.7/site-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: nvrtcGetProgramLogSize

```

### Steps to reproduce

`default.nix`:

```
let
  overlay = self: super: {
    python3 = super.python3.override {
      packageOverrides = self: super: {
        hello = super.callPackage ./hello.nix {};
      };
    };
  };

  pkgs = import ~/Documents/code/nixpkgs {
    overlays = [ overlay ];
    config = { allowUnfree = true; cudaSupport = true; };
  };

in pkgs.python3.pkgs.hello
```

`setup.py`:

```
from setuptools import setup

setup(
    name="hello",
    install_requires=["torch"],
)
```

`hello.nix`:
```
{ buildPythonPackage, pytest, pytorch, cudatoolkit, tree }:

buildPythonPackage {
  name = "hello";
  src = ./.;

  buildInputs = [ tree ];
  propagatedBuildInputs = [ pytorch cudatoolkit ];
  checkInputs = [ pytest ];
  doCheck = true;
  checkPhase = ''
    python3 -c "import torch"
  '';
}
```

In this folder, running `nix-shell --command 'python3 -c "import torch"'` is OK, but `nix build` gives the error described above.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.2, NixOS, 19.03pre159472.80738ed9dc0 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(kai): `""`
 - channels(root): `"nixos-19.03pre159472.80738ed9dc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by kwohlfahrt** [comment]
The error from `torch._C` is misleading, the actual error is in `import torch._nvrtc`, which cannot find `libcuda.so.1`.

**Comment by teh** [comment]
Hi - is this still an issue on current master?  Based on this discussion https://github.com/NixOS/nixpkgs/issues/46032 it sounds like cuda is working for other people.

**Comment by kwohlfahrt** [comment]
It doesn't seem to work on cac756d3703cf727d9a2b4753fb5d6281ae38c96 (though it does build):

```
> nix run -I nixpkgs=. "(with import <nixpkgs> {}; python3.withPackages (ps: with ps; [ pytorchWithCuda ]))" --command python3

Python 3.7.2 (default, Dec 24 2018, 03:41:55) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.tensor([1, 2, 3]).to("cuda")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/0qap1cpnl1i426za43wbmpmg1zgyypvj-python3-3.7.2-env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    _check_driver()
  File "/nix/store/0qap1cpnl1i426za43wbmpmg1zgyypvj-python3-3.7.2-env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

I have CUDA: 

```
> nvidia-smi
Mon Apr 15 09:47:33 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 415.27       Driver Version: 415.27       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0 Off |                  N/A |
| 28%   23C    P5    15W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by teh** [comment]
What does 

```
echo $LD_LIBRARY_PATH                                                                                                                                                                     
```

say on your machine? For someone who has it working:

```
echo $LD_LIBRARY_PATH                                                                                                                                                                     
/run/opengl-driver/lib:/run/opengl-driver-32/lib
```

**Comment by kwohlfahrt** [comment]
Looks good to me:

```
> echo $LD_LIBRARY_PATH
/nix/store/8xdz8smf4jlzy2dj155xw6f266sbvdnb-sane-config/lib/sane /run/opengl-driver/lib /run/opengl-driver-32/lib
```

**Comment by kwohlfahrt** [comment]
Souldn't `LD_LIBRARY_PATH` be clobbered during the build anyway? Which is where the problem seems to be, since the error is `Torch not compiled with CUDA enabled` - not an issue finding CUDA at runtime.

**Comment by jyp** [comment]
I believe that this is fixed by #60002

**Comment by prusnak** [comment]
This should be closed as https://github.com/NixOS/nixpkgs/pull/60002 was merged

**Comment by prusnak** [comment]
Closing as per #60002
