### ISSUE TITLE
liquibase fails: NoClassDefFoundError

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#52561]
## Issue description

Starting liquibase results in:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at liquibase.logging.core.Slf4JLoggerFactory.getLog(Slf4JLoggerFactory.java:9)
        at liquibase.logging.LogService.getLog(LogService.java:39)
        at liquibase.integration.commandline.Main.<clinit>(Main.java:67)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
```

### Steps to reproduce

```
nix-shell -p liquibase --run "liquibase --help"
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.88, NixOS, 19.03pre162590.562b7a7702c (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(philipp): `""`
 - channels(root): `"nixos-19.03pre162590.562b7a7702c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by pmiddend** [comment]
This is fixed in:

https://github.com/liquibase/liquibase/pull/842

So the next release should have this. Alternatives seem to be:

- Manually download the slf4j jar file and include it in the classpath
- Use an older version (3.5.* seems to work)
- Include the PR in the derivation. This would mean building liquibase from source.
- Keep it broken until it's released.

I'm a little baffled that nobody actually tried to execute liquibase apparently.
