### ISSUE TITLE
python37Packages.dateparser tests fail

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#52766]
## Issue description

`python36Packages.dateparser` tests pass, while `python37Packages.dateparser` tests fail with:

```
======================================================================
FAIL: test_detection_24_es (tests.test_search.TestTranslateSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/5v7lfgvnwl87vp4x18w1bhp14s7sw12m-python3.7-parameterized-0.6.1/lib/python3.7/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/build/dateparser/tests/test_search.py", line 619, in test_detection
    self.assertEqual(result, shortname)
AssertionError: 'eo' != 'es'
- eo
+ es


======================================================================
FAIL: test_search_and_parse_26_es (tests.test_search.TestTranslateSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/5v7lfgvnwl87vp4x18w1bhp14s7sw12m-python3.7-parameterized-0.6.1/lib/python3.7/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/build/dateparser/dateparser/conf.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/build/dateparser/tests/test_search.py", line 413, in test_search_and_parse
    self.assertEqual(result, expected)
AssertionError: Lists differ: [('a', datetime.datetime(2000, 1, 1, 0, 0)),[479 chars] 0))] != [('de 1939', datetime.datetime(1939, 1, 1, 0[51 chars] 0))]

First differing element 0:
('a', datetime.datetime(2000, 1, 1, 0, 0))
('de 1939', datetime.datetime(1939, 1, 1, 0, 0))

First list contains 10 additional elements.
First extra element 2:
('a', datetime.datetime(2000, 1, 1, 0, 0))

Diff is 670 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_search_date_string_31_es (tests.test_search.TestTranslateSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/5v7lfgvnwl87vp4x18w1bhp14s7sw12m-python3.7-parameterized-0.6.1/lib/python3.7/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/build/dateparser/tests/test_search.py", line 210, in test_search_date_string
    self.assertEqual(result, datetime_string)
AssertionError: 'M' != 'Miércoles 31 Diciembre 2014'
- M
+ Miércoles 31 Diciembre 2014


----------------------------------------------------------------------
Ran 209 tests in 3.805s

FAILED (failures=3)
```

Official Hydra sees the same thing: https://hydra.nixos.org/eval/1497276?filter=dateparser&compare=1497263&full=

[Upstream's tests pass on Python 3.7](https://travis-ci.org/scrapinghub/dateparser/jobs/470433986) with their Travis setup.  (That is a build of a recent commit, but I still see the same failures after pointing `src =` at a checkout of https://github.com/scrapinghub/dateparser)

Does anyone have any ideas?

### Steps to reproduce

With nixpkgs master, `nix-env -iA python37Packages.dateparser`

**Comment by dotlambda** [comment]
See scrapinghub/dateparser#489, scrapinghub/dateparser#490 and scrapinghub/dateparser#493.

**Comment by dotlambda** [comment]
As long as this problem remains, the best thing to do is use `python36` for affected application. Simply skipping the tests does not make much sense since these are real incompatibilities.
