### ISSUE TITLE
mwic fails to start with ModuleNotFoundError: No module named 'enchant'

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#53108]
## Issue description

[mwic](https://github.com/jwilk/mwic) can't import enchant:

```
# nix-env -f ~/code/system/nixpkgs -iA mwic
replacing old 'mwic-0.7.7'
installing 'mwic-0.7.7'
these paths will be fetched (14.73 MiB download, 78.44 MiB unpacked):
  /nix/store/4ag8gng51y7yw6nr3imwyppqfci3j643-python3-3.7.2
  /nix/store/bz0n8sklvj2v0wm8cslab5hgjxfxx9h3-python3.7-setuptools-40.6.2
  /nix/store/iw0ybgfkmg7w6n1g716l14vqizkxd3ff-aspell-0.60.6.1
  /nix/store/k2cl7p0cnzvgz36fb7ibj4fpamdg3sax-glib-2.58.1
  /nix/store/m3hppiczw3bmdz34cpj7nimbg0z75js2-mwic-0.7.7
  /nix/store/m3zzrg7sk9njjzagq6l1vkkr3dszwafr-enchant-1.6.1
  /nix/store/mzm751bzn2az5fbn2ygapaz9zqbs0pm3-hunspell-1.7.0
  /nix/store/qwwlhvmdg2fk5gvylc9vlkky5cszw7gi-hspell-1.1
  /nix/store/s1bpbdci12jlzff3a7jrax5l9rlcnpzl-python3.7-pyenchant-2.0.0
  /nix/store/s7mgfyqb135jxdiikd9zj2r7iyq8zpdn-python3.7-regex-2018.11.07
  /nix/store/v4i35a0bhbxb146vsbd8fd66wg74zqk4-libselinux-2.7
  /nix/store/z0x40kmai1daywwv9v1p2d1wvc6wzhpw-util-linux-2.33
copying path '/nix/store/4ag8gng51y7yw6nr3imwyppqfci3j643-python3-3.7.2' from 'https://cache.nixos.org'...
copying path '/nix/store/iw0ybgfkmg7w6n1g716l14vqizkxd3ff-aspell-0.60.6.1' from 'https://cache.nixos.org'...
copying path '/nix/store/qwwlhvmdg2fk5gvylc9vlkky5cszw7gi-hspell-1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/mzm751bzn2az5fbn2ygapaz9zqbs0pm3-hunspell-1.7.0' from 'https://cache.nixos.org'...
copying path '/nix/store/v4i35a0bhbxb146vsbd8fd66wg74zqk4-libselinux-2.7' from 'https://cache.nixos.org'...
copying path '/nix/store/bz0n8sklvj2v0wm8cslab5hgjxfxx9h3-python3.7-setuptools-40.6.2' from 'https://cache.nixos.org'...
copying path '/nix/store/z0x40kmai1daywwv9v1p2d1wvc6wzhpw-util-linux-2.33' from 'https://cache.nixos.org'...
copying path '/nix/store/s7mgfyqb135jxdiikd9zj2r7iyq8zpdn-python3.7-regex-2018.11.07' from 'https://cache.nixos.org'...
copying path '/nix/store/k2cl7p0cnzvgz36fb7ibj4fpamdg3sax-glib-2.58.1' from 'https://cache.nixos.org'...
copying path '/nix/store/m3zzrg7sk9njjzagq6l1vkkr3dszwafr-enchant-1.6.1' from 'https://cache.nixos.org'...
copying path '/nix/store/s1bpbdci12jlzff3a7jrax5l9rlcnpzl-python3.7-pyenchant-2.0.0' from 'https://cache.nixos.org'...
copying path '/nix/store/m3hppiczw3bmdz34cpj7nimbg0z75js2-mwic-0.7.7' from 'https://cache.nixos.org'...
building '/nix/store/ry179ply4v85023mh09bzq0xh48875r6-user-environment.drv'...
created 2306 symlinks in user environment

# mwic --help
Traceback (most recent call last):
  File "/home/at/.nix-profile/bin/mwic", line 30, in <module>
    import lib.cli  # pylint: disable=wrong-import-position
  File "/nix/store/m3hppiczw3bmdz34cpj7nimbg0z75js2-mwic-0.7.7/share/mwic/lib/cli.py", line 32, in <module>
    import enchant.tokenize
ModuleNotFoundError: No module named 'enchant'
```

### Steps to reproduce

With nixpkgs master:

```
nix-env -f ~/nixpkgs -iA mwic
mwic
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.0-64-amd64, Debian GNU/Linux, 9 (stretch)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(at): `""`
 - nixpkgs: `/home/at/code/system/nixpkgs`

**Comment by Lenin1917** [comment]
same issue

**Comment by ivan** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/95119
