### ISSUE TITLE
Prosody: error build configuration

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#53131]
## Issue description
Error build configuration with nixops

### Steps to reproduce
Add to configuration 
`services.prosody = { enable = true; };`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.20.0, NixOS, 19.03.git.a4e0985 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2pre6526_9f99d624`
 - channels(root): `"nixos-19.03pre164737.a4e098519b3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

## Error
```
building all machine configurations...
error: while evaluating the attribute 'buildCommand' of the derivation 'nixops-machines' at /nix/store/q3yfic0j8ys30i3f1dp0na59aivrbgvv-nixos-19.03pre164737.a4e098519b3/nixos/pkgs/stdenv/generic/make-derivation.nix:185:11:
while evaluating anonymous function at /nix/store/ywaf5rfyl491n0xqbyp88aw4z7lbbq7f-nixops-1.6.1pre2706_d5ad09c/share/nix/nixops/eval-machine-info.nix:368:46, called from undefined position:
while evaluating the attribute 'config.system.build.toplevel' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/activation/top-level.nix:276:5:
while evaluating 'foldr' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:39:20, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/activation/top-level.nix:140:12:
while evaluating 'fold'' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:42:15, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:46:8:
while evaluating 'showWarnings' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/activation/top-level.nix:133:18, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/activation/top-level.nix:137:10:
while evaluating 'foldr' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:39:20, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/activation/top-level.nix:133:23:
while evaluating 'fold'' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:42:15, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:46:8:
while evaluating the attribute 'warnings' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:336:9:
while evaluating the option `warnings':
while evaluating the attribute 'isDefined' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:374:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:362:9:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:348:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:348:17:
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:416:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:349:62:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:232:58:
while evaluating the attribute 'config.warnings' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/boot/systemd.nix:735:5:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/attrsets.nix:234:10, called from undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/boot/systemd.nix:735:51, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/attrsets.nix:234:16:
while evaluating 'optional' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:241:20, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/boot/systemd.nix:736:7:
while evaluating the attribute 'serviceConfig.Type' at undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:336:9:
while evaluating the option `systemd.services.prosody.serviceConfig':
while evaluating the attribute 'mergedValue' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:369:5:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:369:32, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:369:19:
while evaluating 'merge' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/types.nix:282:20, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:372:8:
while evaluating 'filterAttrs' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/attrsets.nix:124:23, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/types.nix:283:35:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/attrsets.nix:125:29, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/attrsets.nix:125:18:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/types.nix:283:51, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/attrsets.nix:125:62:
while evaluating the attribute 'ExecStart' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/attrsets.nix:344:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/types.nix:283:86, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/attrsets.nix:344:15:
while evaluating the attribute 'optionalValue' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:376:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:362:9:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:458:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:348:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:348:17:
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:416:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/modules.nix:349:62:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/types.nix:288:55:
while evaluating the attribute 'ExecStart' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/services/networking/prosody.nix:515:9:
while evaluating the attribute 'buildInputs' of the derivation 'prosody-0.11.1' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:185:11:
while evaluating the attribute 'buildInputs' of the derivation 'lua5.2-luadbi-0.6' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:185:11:
cannot coerce a set to a string, at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:185:11
Traceback (most recent call last):
  File "/nix/store/ywaf5rfyl491n0xqbyp88aw4z7lbbq7f-nixops-1.6.1pre2706_d5ad09c/bin/..nixops-wrapped-wrapped", line 990, in <module>
    args.op()
  File "/nix/store/ywaf5rfyl491n0xqbyp88aw4z7lbbq7f-nixops-1.6.1pre2706_d5ad09c/bin/..nixops-wrapped-wrapped", line 411, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/ywaf5rfyl491n0xqbyp88aw4z7lbbq7f-nixops-1.6.1pre2706_d5ad09c/lib/python2.7/site-packages/nixops/deployment.py", line 1057, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/ywaf5rfyl491n0xqbyp88aw4z7lbbq7f-nixops-1.6.1pre2706_d5ad09c/lib/python2.7/site-packages/nixops/deployment.py", line 1046, in run_with_notify
    f()
  File "/nix/store/ywaf5rfyl491n0xqbyp88aw4z7lbbq7f-nixops-1.6.1pre2706_d5ad09c/lib/python2.7/site-packages/nixops/deployment.py", line 1057, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/ywaf5rfyl491n0xqbyp88aw4z7lbbq7f-nixops-1.6.1pre2706_d5ad09c/lib/python2.7/site-packages/nixops/deployment.py", line 997, in _deploy
    self.configs_path = self.build_configs(dry_run=dry_run, repair=repair, include=include, exclude=exclude)
  File "/nix/store/ywaf5rfyl491n0xqbyp88aw4z7lbbq7f-nixops-1.6.1pre2706_d5ad09c/lib/python2.7/site-packages/nixops/deployment.py", line 665, in build_configs
    raise Exception("unable to build all machine configurations")
Exception: unable to build all machine configurations

```

**Comment by Izorkin** [comment]
With nixpkg rev 74854265b18 - normal build, with rev 641ef3ab237 - error
