### ISSUE TITLE
calibre fails to start: ImportError: No module named css_parser.css

### ISSUE THREAD

**Issue by Pneumaticat** [NixOS/nixpkgs#53973]
## Issue description

When Calibre starts on latest nixos-unstable (3.37), it gives the error: "There was an error during calibre startup. Parts of calibre may not function." With the detailed text:

```
calibre, version 3.37.0
ERROR: Startup error: There was an error during calibre startup. Parts of calibre may not function. Click Show details to learn more.

Traceback (most recent call last):
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/gui2/main.py", line 290, in initialize_db_stage2
    self.start_gui(db)
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/gui2/main.py", line 229, in start_gui
    main = self.main = Main(self.opts, gui_debug=self.gui_debug)
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/gui2/ui.py", line 157, in __init__
    ac = self.init_iaction(action)
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/gui2/ui.py", line 171, in init_iaction
    ac = action.load_actual_plugin(self)
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/customize/__init__.py", line 612, in load_actual_plugin
    ac = getattr(importlib.import_module(mod), cls)(gui,
  File "/nix/store/l95nkqp7bdimqnz9ixay1aahljzsz7vc-python-2.7.15/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/gui2/actions/catalog.py", line 13, in <module>
    from calibre.gui2.tools import generate_catalog
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/gui2/tools.py", line 16, in <module>
    from calibre.gui2.convert.single import Config as SingleConfig
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/gui2/convert/single.py", line 18, in <module>
    from calibre.gui2.convert.look_and_feel import LookAndFeelWidget
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/gui2/convert/look_and_feel.py", line 13, in <module>
    from calibre.gui2.convert.look_and_feel_ui import Ui_Form
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/gui2/convert/look_and_feel_ui.py", line 286, in <module>
    from calibre.gui2.css_transform_rules import RulesWidget
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/gui2/css_transform_rules.py", line 13, in <module>
    from calibre.ebooks.css_transform_rules import (
  File "/nix/store/x0c3c5lb21zxlzxbw29ilv1fnvsdln1y-calibre-3.37.0/lib/calibre/calibre/ebooks/css_transform_rules.py", line 11, in <module>
    from css_parser.css import Property, CSSRule
ImportError: No module named css_parser.css
```

Might be due to https://github.com/kovidgoyal/calibre/commit/dd7d8ea3c4f47e315623d882d6b68339da959ab9 switching Calibre to use css-parser, which seems like it isn't packaged in nixpkgs?

Seems like #53636 didn't catch the issue.

### Steps to reproduce

Run Calibre.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.14, NixOS, 19.03.git.f1cc4b7 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`
```

**Comment by dotlambda** [comment]
resolved by #53865
