### ISSUE TITLE
Python dask and distributed has an import error on 18.09-small

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#54875]
## Issue description

The python packages `dask` and `distributed` are meant to work together (the distributed package is meant to be usable by dask). When using them together with Python, trying to do `import dask.distributed` results in an import error.

I think this means `distributed` is an "optional" dependency of `dask`. And the `dask` Nix expression doesn't mention `distributed`. So it ends up being impossible to import `distributed` package code because it falls under the `dask` namespace.

I think this requires some sort of override to the `dask` expression so that `distributed` is made available to it.

### Steps to reproduce

Use the below as `shell.nix`.

```
{
  pkgs ? import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/06808d4a14017e4e1a3cbc20d50644549710286f.tar.gz) {},
  pythonPath ? "python36"
}:
  with pkgs;
  let
    python = lib.getAttrFromPath (lib.splitString "." pythonPath) pkgs;
  in
    python.pkgs.buildPythonApplication (rec {
      name = "dask-test";
      src = null;
      propagatedBuildInputs = (with python.pkgs; [
        distributed
        dask
      ]);
      shellHook = ''
        echo 'Entering ${name}'
        set -v

        # extra pip packages
        unset SOURCE_DATE_EPOCH

        set +v
      '';
    })
```

Then try:

```
import dask.distributed
```

You get an error like:

```
Python 3.6.8 (default, Dec 24 2018, 03:01:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask.distributed
Traceback (most recent call last):
  File "/nix/store/llxbz2kb543cxmi2hn4zbrjzhjfy4hqp-python3.6-dask-0.18.2/lib/python3.6/site-packages/dask/distributed.py", line 5, in <module>
    from distributed import *
  File "/nix/store/p7rx2rgf0p38wq8ximvdlv6798y1jz1b-python3.6-distributed-1.15.1/lib/python3.6/site-packages/distributed/__init__.py", line 5, in <module>
    from .deploy import LocalCluster
  File "/nix/store/p7rx2rgf0p38wq8ximvdlv6798y1jz1b-python3.6-distributed-1.15.1/lib/python3.6/site-packages/distributed/deploy/__init__.py", line 3, in <module>
    from .local import LocalCluster
  File "/nix/store/p7rx2rgf0p38wq8ximvdlv6798y1jz1b-python3.6-distributed-1.15.1/lib/python3.6/site-packages/distributed/deploy/local.py", line 14, in <module>
    from ..client import Client
  File "/nix/store/p7rx2rgf0p38wq8ximvdlv6798y1jz1b-python3.6-distributed-1.15.1/lib/python3.6/site-packages/distributed/client.py", line 21, in <module>
    from dask.base import tokenize, normalize_token, Base
ImportError: cannot import name 'Base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/llxbz2kb543cxmi2hn4zbrjzhjfy4hqp-python3.6-dask-0.18.2/lib/python3.6/site-packages/dask/distributed.py", line 11, in <module>
    raise ImportError(msg)
ImportError: Dask's distributed scheduler is not installed.

Please either conda or pip install dask distributed:

  conda install dask distributed          # either conda install
  pip install dask distributed --upgrade  # or pip install
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.6, Form Bay ML, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/nixpkgs`
```

**Comment by dotlambda** [comment]
This is way easer to reproduce using
```bash
nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/06808d4a14017e4e1a3cbc20d50644549710286f.tar.gz -p "python3.withPackages (ps: with ps; [ dask distributed ])" --run "python -c 'import dask.distributed'"
```
`git bisect` hints at commit 4f70170f8ab2b97f371f018e89e157219d22dcb6 being the first one after which this is working properly. If you need this, please open a PR backporting that commit to the `release-18.09` branch.

**Comment by CMCDragonkai** [comment]
Yea it would be good to backport this to release-18.09. Is it sufficient to just cherry pick that commit?

**Comment by dotlambda** [comment]
Just apply 027b9beb583935a734c3d81dbf09862af3ee8293 as well.

**Comment by CMCDragonkai** [comment]
@dotlambda Please merge: https://github.com/NixOS/nixpkgs/pull/54974

**Comment by CMCDragonkai** [comment]
Done.
