### ISSUE TITLE
Link failure in wxWidgets component when building wxPython 4.0

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#55426]
Related: #54235
Mentioning:
@FRidh (blame shows as committer?)

I'm totally stumped on the following:

I'm trying to build the latest WikidPad alpha, which has switched to python 3.4 and wxPython 4.0 using the following preliminary snippet: 

```nix
#TODO clean up
{lib, fetchFromGitHub, stdenv, python34, python34Packages, callPackage, pkgs, gtk3, libjpeg, libtiff, SDL, gst-plugins-base, libnotify, freeglut, xorg, which, pkgconfig}:
let
  orig-wx = callPackage <nixos/pkgs/development/python-modules/wxPython/4.0.nix> { inherit pkgconfig gtk3 libjpeg libtiff SDL gst-plugins-base libnotify freeglut xorg which; inherit (python34Packages) fetchPypi buildPythonPackage; };
  new-wx = orig-wx.overrideAttrs(old: {
    #needs extra
    #src = fetchFromGitHub {inherit (lib.importJSON ./phoenix.json) owner repo rev sha256;};

    #still gets 4.0.3 for some reason
    src = python34Packages.fetchPypi { pname="wxPython"; version="4.0.4"; sha256 = "0d9ef4260cb2f3e23ed9dcf6baa905ba585ac7d631613cddc299c4c83463ae29"; };
    });
  python = python34.withPackages (ps: [ new-wx ]);
  exe = src: python: pkgs.writeShellScriptBin "wikidpad" ''
    cd ${src}
    ${python}/bin/python ${src}/WikidPadStarter.py
    '';
in
  #buildPythonApplication isnt used because its supposed to be just run from source
  stdenv.mkDerivation rec {
    name = "wikidpad-${version}";
    version = "2_4alpha01";

    src = fetchFromGitHub {inherit (lib.importJSON ./WikidPad.json) owner repo rev sha256;};
    unpackPhase = "true"; #workaround
    propagatedBuildInputs = [ (exe src python) ];
    }
```
 
The json files are acquired via 
```
nix-shell -p nix-prefetch-github --run 'nix-prefetch-github WikidPad WikidPad --rev ac56b60fcdea9af8a4447204dae69c043d7e0595 > WikidPad.json'
```
and  
```
nix-shell -p nix-prefetch-github --run 'nix-prefetch-github wxWidgets Phoenix --rev edefe4da6d28f93b470c37d31219d4b05984df82 > phoenix.json'
```
respectiviely.

I'm running it via ` nix-build -E "with import <nixpkgs> {}; callPackage ./wikidpad.nix {}" -v` and I'm running into this linking error:
```
[...SNIP...]
/build/wxPython-4.0.4/build/wxbld/gtk3/bk-make-pch ./.pch/wxprec_advdll/wx/wxprec.h.gch wx/wxprec.h g++ -I./.pch/wxprec_advdll -D__WXGTK__      -DWXBUILDING      -I/build/wxPython-4.0.4/ext/wxWidgets/src/regex  -DWXUSINGDLL -DWXMAKINGDLL_ADV -fPIC -DPIC -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -D_FILE_OFFSET_BITS=64 -I/build/wxPython-4.0.4/build/wxbld/gtk3/lib/wx/include/gtk3-unicode-3.0 -I/build/wxPython-4.0.4/ext/wxWidgets/include -pthread -I/nix/store/q1gmscfbpakql3r351y497j75psb6335-gtk+3-3.22.30-dev/include/gtk-3.0 -I/nix/store/wbw7l6584paf8a16kzfh2zxd6dfqj2rd-glib-2.56.0-dev/include/glib-2.0 -I/nix/store/k1blarc01qvva2k9w4a441j056wr4d6z-glib-2.56.0/lib/glib-2.0/include -I/nix/store/0449k5h5iyk6xjiglsvnccylsxim3055-cairo-1.15.12-dev/include/cairo -I/nix/store/nlhnfs5mmdynrgh7xniii8saqa59mr0g-freetype-2.9-dev/include/freetype2 -I/nix/store/nlhnfs5mmdynrgh7xniii8saqa59mr0g-freetype-2.9-dev/include -I/nix/store/nwrsqsg44hz1pb1i2093d9qz01z3g4gn-pango-1.42.1-dev/include/pango-1.0 -I/nix/store/ylf41xd9pdznv2pm8bfv0bq4pa5zvs5r-fribidi-1.0.5/include/fribidi -I/nix/store/fmww3cr4hwb74bzakxy8ycz7plak7qld-gdk-pixbuf-2.36.12-dev/include/gdk-pixbuf-2.0 -I/nix/store/8xbix3x7za82axv48aiyw2r6djpnp1m0-atk-2.28.1-dev/include/atk-1.0 -pthread -I/nix/store/wbw7l6584paf8a16kzfh2zxd6dfqj2rd-glib-2.56.0-dev/include/glib-2.0 -I/nix/store/k1blarc01qvva2k9w4a441j056wr4d6z-glib-2.56.0/lib/glib-2.0/include -I/nix/store/zpprms1zmbrdyhiwzl1qq0dkcrnvn8bh-gst-plugins-base-0.10.36-dev/include/gstreamer-0.10 -I/nix/store/ra2167lbc897w38xxwj1lhibf9ilmhli-gstreamer-0.10.36-dev/include/gstreamer-0.10 -I/nix/store/d1y7pzd43zgmq58vkqrkfykk46zma1gn-libxml2-2.9.8-dev/include/libxml2 -DWX_PRECOMP -pthread -O2 -fno-strict-aliasing -I/nix/store/wbw7l6584paf8a16kzfh2zxd6dfqj2rd-glib-2.56.0-dev/include/glib-2.0 -I/nix/store/k1blarc01qvva2k9w4a441j056wr4d6z-glib-2.56.0/lib/glib-2.0/include -I/nix/store/fmww3cr4hwb74bzakxy8ycz7plak7qld-gdk-pixbuf-2.36.12-dev/include/gdk-pixbuf-2.0 -I/nix/store/m3m6vqr13hb3wi8j7g4acv02nxrqwg5x-libnotify-0.7.7/include -I/nix/store/q1gmscfbpakql3r351y497j75psb6335-gtk+3-3.22.30-dev/include/gtk-3.0/unix-print -I/nix/store/q1gmscfbpakql3r351y497j75psb6335-gtk+3-3.22.30-dev/include/gtk-3.0 -I/nix/store/wbw7l6584paf8a16kzfh2zxd6dfqj2rd-glib-2.56.0-dev/include/glib-2.0 -I/nix/store/k1blarc01qvva2k9w4a441j056wr4d6z-glib-2.56.0/lib/glib-2.0/include -I/nix/store/0449k5h5iyk6xjiglsvnccylsxim3055-cairo-1.15.12-dev/include/cairo -I/nix/store/nlhnfs5mmdynrgh7xniii8saqa59mr0g-freetype-2.9-dev/include/freetype2 -I/nix/store/nlhnfs5mmdynrgh7xniii8saqa59mr0g-freetype-2.9-dev/include -I/nix/store/nwrsqsg44hz1pb1i2093d9qz01z3g4gn-pango-1.42.1-dev/include/pango-1.0 -I/nix/store/ylf41xd9pdznv2pm8bfv0bq4pa5zvs5r-fribidi-1.0.5/include/fribidi -I/nix/store/fmww3cr4hwb74bzakxy8ycz7plak7qld-gdk-pixbuf-2.36.12-dev/include/gdk-pixbuf-2.0 -I/nix/store/8xbix3x7za82axv48aiyw2r6djpnp1m0-atk-2.28.1-dev/include/atk-1.0 -I/nix/store/0fzzqipzq48fr0670zi6f5yw8iq8kag3-SDL-1.2.15-dev/include/SDL -I/nix/store/0fzzqipzq48fr0670zi6f5yw8iq8kag3-SDL-1.2.15-dev/include/SDL -I/nix/store/0fzzqipzq48fr0670zi6f5yw8iq8kag3-SDL-1.2.15-dev/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -fvisibility=hidden -fvisibility-inlines-hidden
/nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/crt1.o: In function `_start':
/build/glibc-2.27/csu/../sysdeps/x86_64/start.S:104: undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:15570: .pch/wxprec_basedll/wx/wxprec.h.gch] Error 1
make: *** Waiting for unfinished jobs....
/nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/crt1.o: In function `_start':
/build/glibc-2.27/csu/../sysdeps/x86_64/start.S:104: undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:15607: .pch/wxprec_netdll/wx/wxprec.h.gch] Error 1
/nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/crt1.o: In function `_start':
/build/glibc-2.27/csu/../sysdeps/x86_64/start.S:104: undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:15644: .pch/wxprec_coredll/wx/wxprec.h.gch] Error 1
/nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/crt1.o: In function `_start':
/build/glibc-2.27/csu/../sysdeps/x86_64/start.S:104: undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:15681: .pch/wxprec_advdll/wx/wxprec.h.gch] Error 1
Error building
ERROR: failed building wxWidgets
Traceback (most recent call last):
  File "build.py", line 1321, in cmd_build_wx
    wxbuild.main(wxDir(), build_options)
  File "/build/wxPython-4.0.4/buildtools/build_wxwidgets.py", line 500, in main
    exitIfError(wxBuilder.build(dir=buildDir, options=args), "Error building")
  File "/build/wxPython-4.0.4/buildtools/build_wxwidgets.py", line 85, in exitIfError
    raise builder.BuildError(msg)
buildtools.builder.BuildError: Error building
Finished command: build_wx (1m50.119s)
Finished command: build (1m50.119s)
WARNING: Building this way assumes that all generated files have been
generated already.  If that is not the case then use build.py directly
to generate the source and perform the build stage.  You can use
--skip-build with the bdist_* or install commands to avoid this
message and the wxWidgets and Phoenix build steps in the future.

"/nix/store/rfcndyp9w3ldsymbr2ws40cqacyw6rnr-python3-3.4.9/bin/python3.4m" -u build.py build
Command '"/nix/store/rfcndyp9w3ldsymbr2ws40cqacyw6rnr-python3-3.4.9/bin/python3.4m" -u build.py build' failed with exit code 1.
builder for '/nix/store/ibj42riwm4qsy20nzra4lvsw6s1phagk-python3.4-wxPython-4.0.3.drv' failed with exit code 1
cannot build derivation '/nix/store/yiafsmz93wwfqjpff8s7lqz7zv0vgyx5-python3-3.4.9-env.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ivfaxjfhqfaanrr5x8gr34v9h50v7qgp-wikidpad.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1frzj9gm1flcfrdf8vp7zm1ik7r882s7-wikidpad-2_4alpha01.drv': 1 dependencies couldn't be built
error: build of '/nix/store/1frzj9gm1flcfrdf8vp7zm1ik7r882s7-wikidpad-2_4alpha01.drv' failed
```

The ld call that I dug out using strace (from a previous run, /may/ be inaccurate) is:
```
/nix/store/b0yc8vswfzcanhdm6dgmfmdcgjmxvxa0-binutils-2.30/bin/ld
-z now
-z relro
-plugin /nix/store/nly6dg3af8ycqn1x87ns1r3mrcjpv43a-gcc-7.3.0/libexec/gcc/x86_64-unknown-linux-gnu/7.3.0/liblto_plugin.so
-plugin-opt=/nix/store/nly6dg3af8ycqn1x87ns1r3mrcjpv43a-gcc-7.3.0/libexec/gcc/x86_64-unknown-linux-gnu/7.3.0/lto-wrapper
-plugin-opt=-fresolution=/run/user/1000/ccG4yKTa.res
-plugin-opt=-pass-through=-lgcc_s
-plugin-opt=-pass-through=-lgcc
-plugin-opt=-pass-through=-lpthread
-plugin-opt=-pass-through=-lc
-plugin-opt=-pass-through=-lgcc_s
-plugin-opt=-pass-through=-lgcc
--eh-frame-hdr
-m elf_x86_64
-dynamic-linker /nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib64/ld-linux-x86-64.so.2
-o ./.pch/wxprec_coredll/wx/wxprec.h.gch
/nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/crt1.o
/nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/crti.o
/nix/store/nly6dg3af8ycqn1x87ns1r3mrcjpv43a-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/crtbegin.o
-L/nix/store/vp7mwr3wx0a8a6bg7ifg9iq1wk6n0w6j-python3-3.6.8/lib
-L/nix/store/qgmwbnzihwzrdg3wnfkcl44zb3anpfpj-libffi-3.2.1/lib
-L/nix/store/vp7mwr3wx0a8a6bg7ifg9iq1wk6n0w6j-python3-3.6.8/lib
-L/nix/store/qgmwbnzihwzrdg3wnfkcl44zb3anpfpj-libffi-3.2.1/lib
-L/nix/store/rfcndyp9w3ldsymbr2ws40cqacyw6rnr-python3-3.4.9/lib
-L/nix/store/hpb0is2l0s87b26r313lhwnzqlm7qp55-expat-2.2.6/lib
-L/nix/store/3s920c43pgzi6vdabjs90in308jnbckv-zlib-1.2.11/lib
-L/nix/store/qgmwbnzihwzrdg3wnfkcl44zb3anpfpj-libffi-3.2.1/lib
-L/nix/store/j1jcx95p61pjr3sgbqgixrbs0fsw579r-gettext-0.19.8.1/lib
-L/nix/store/k1blarc01qvva2k9w4a441j056wr4d6z-glib-2.56.0/lib
-L/nix/store/hz6r1rk2vfgcizxr49bn51nafl0qjkmh-libXau-1.0.8/lib
-L/nix/store/arqlvxhxsivqdnjpmn9clqb683hh1sxi-libXext-1.3.3/lib
-L/nix/store/xgk63lh5nlc76cpm2ak1rx2l7lxqlk9n-bzip2-1.0.6.0.1/lib
-L/nix/store/k4ackqr7yl9fi4b7x038qc3h0pkpj01s-libpng-apng-1.6.35/lib
-L/nix/store/8zqlwy2388xfc1m225zma04i3n3irf7l-freetype-2.9/lib
-L/nix/store/r510mp6mhxdz4k927sn0r7b9ajv1b83y-fontconfig-2.12.6-lib/lib
-L/nix/store/p8j5i0a3r5ipv2yjqly7wm664s5qr5cl-pixman-0.34.0/lib
-L/nix/store/992mmwzy25xwlwc1s64ph1pvghy205w1-libxcb-1.12/lib
-L/nix/store/h89ql6qir0j8mv07x9nl9pi8rcq3gcjf-libX11-1.6.6/lib
-L/nix/store/hqxlagw7dpgd1aykkhck6s471m30n79q-libXrender-0.9.10/lib
-L/nix/store/w7qrmcmgzrrv9jysbzi2fydgva7ihw8m-xcb-util-0.4.0/lib
-L/nix/store/d2bikgsldaq13nfhn6an0vskiq3pdkv7-libGL-1.0.0/lib
-L/nix/store/j3974dvdm3cp1gifqiy9pqy1n9v578ib-cairo-1.15.12/lib
-L/nix/store/hn8xjiwh5pz2d22jcmqqwsqb1wrzi0xh-graphite2-1.3.6/lib
-L/nix/store/alqn91q6w31vzr7na27biwmbwn36qs6h-harfbuzz-1.8.8/lib
-L/nix/store/x0vvpv253r7h5l5p4kphbadid6naf3az-libXft-2.3.2/lib
-L/nix/store/ylf41xd9pdznv2pm8bfv0bq4pa5zvs5r-fribidi-1.0.5/lib
-L/nix/store/8yzqrfb5w7akdm0y7pd9vxc2v9giqlf9-pango-1.42.1/lib
-L/nix/store/hrkvcqgavwmpcckk3mhajgvk8azah6jx-libjpeg-turbo-2.0.1/lib
-L/nix/store/jrzx61apa5js1pll43q7q5gxacz8whjj-xz-5.2.4/lib
-L/nix/store/r4b189c3v46w6pd6kdnxvwxzxpvcs778-libtiff-4.0.10/lib
-L/nix/store/sr0kg36fgladmsy0q9av33vhz5k0jyr8-jasper-2.0.14/lib
-L/nix/store/fb65ghs5231v5qwjybyd7hx8d1q3bbhl-gdk-pixbuf-2.36.12/lib
-L/nix/store/9s2yxvwzawnjgz0xk9yy2d4nssb5yys9-atk-2.28.1/lib
-L/nix/store/hhw2rmyb2hgsw6y28pdqxrw2ww8x6c39-at-spi2-atk-2.26.2/lib
-L/nix/store/m94iyqz0ys3ln5sd2cp485k6mf1h4sa2-libXrandr-1.5.1/lib
-L/nix/store/rns2qgks5r1shm5pviva2vci7zagwcz0-libXfixes-5.0.3/lib
-L/nix/store/cgwkxbgmq5ckrxz471hsbs360blnw1zl-libXcomposite-0.4.4/lib
-L/nix/store/fwlp60q901x2ik3y97i943iadvyrmvia-libXi-1.7.9/lib
-L/nix/store/ahw30nvyf220mzgvb5p2yirhwg3dk9jy-libXcursor-1.1.15/lib
-L/nix/store/cx585b089rkkyih0358fjv1cs699sq76-libICE-1.0.9/lib
-L/nix/store/hbp0kfc22br6i1k9si8w7hbahx4dxzm9-libSM-1.2.2/lib
-L/nix/store/jcjkycg4fvgscnpi8rq7bym5d5rxcyhn-libXdamage-1.1.4/lib
-L/nix/store/rsagacynhsb6z2qr8949bxpflzdvjg2v-libXxf86vm-1.1.4/lib
-L/nix/store/7qcc3xllhc2pqiw2l37rg45hngg525qx-libdrm-2.4.93/lib
-L/nix/store/3x32p2lkd9ga1258x8bhlxvmx64jl92k-mesa-noglu-18.1.7/lib
-L/nix/store/lw7fabjjrkmirawfq8g1l178wz2kxlsw-wayland-1.15.0/lib
-L/nix/store/g93jd13mahngi8gzlnvhrsnf40znb3y6-libXinerama-1.1.3/lib
-L/nix/store/077sn4sz2mxzjm5zqlxxag2170jkkc5n-gmp-6.1.2/lib
-L/nix/store/p0d9v3qfrz781zqdi08imflrlbj1bqyn-cups-2.2.6-lib/lib
-L/nix/store/hqgs95p9axh2g5fl5k92kxd72dif5p09-gtk+3-3.22.30/lib
-L/nix/store/y2574qr6gs3s0qqdjg6lhsgn76bablz5-attr-2.4.47/lib
-L/nix/store/p1w8i3gbs8hr0diibk6bcs8wr2h56zjk-libcap-2.25-lib/lib
-L/nix/store/1a41hgzm9v1r8dcl0qz6hnsvrz87cp0r-glu-9.0.0/lib
-L/nix/store/chimcw80rlb98kb1arhfdvxvw6klz3a1-alsa-lib-1.1.6/lib
-L/nix/store/dqcdmamkgy96rv3rlv10nxdv36scp14v-libpulseaudio-12.2/lib
-L/nix/store/mj1hyp91p746wrzacj4gzm6zksx9j4bb-SDL-1.2.15/lib
-L/nix/store/6iv718x87ir12ljvkpi6nxqccbp4b0ik-libxml2-2.9.8/lib
-L/nix/store/01bwf138158z8y8qzg491ikzxpldzws8-gstreamer-0.10.36/lib
-L/nix/store/6xr27hfjqcahm384pinqksyfqkm5kvcw-gst-plugins-base-0.10.36/lib
-L/nix/store/m3m6vqr13hb3wi8j7g4acv02nxrqwg5x-libnotify-0.7.7/lib
-L/nix/store/gfyz27igijhjk2436s6zngcwqp7q7glw-freeglut-3.0.0/lib
-L/nix/store/rfcndyp9w3ldsymbr2ws40cqacyw6rnr-python3-3.4.9/lib
-L/nix/store/rfcndyp9w3ldsymbr2ws40cqacyw6rnr-python3-3.4.9/lib
-L/nix/store/hpb0is2l0s87b26r313lhwnzqlm7qp55-expat-2.2.6/lib
-L/nix/store/3s920c43pgzi6vdabjs90in308jnbckv-zlib-1.2.11/lib
-L/nix/store/qgmwbnzihwzrdg3wnfkcl44zb3anpfpj-libffi-3.2.1/lib
-L/nix/store/j1jcx95p61pjr3sgbqgixrbs0fsw579r-gettext-0.19.8.1/lib
-L/nix/store/k1blarc01qvva2k9w4a441j056wr4d6z-glib-2.56.0/lib
-L/nix/store/hz6r1rk2vfgcizxr49bn51nafl0qjkmh-libXau-1.0.8/lib
-L/nix/store/arqlvxhxsivqdnjpmn9clqb683hh1sxi-libXext-1.3.3/lib
-L/nix/store/xgk63lh5nlc76cpm2ak1rx2l7lxqlk9n-bzip2-1.0.6.0.1/lib
-L/nix/store/k4ackqr7yl9fi4b7x038qc3h0pkpj01s-libpng-apng-1.6.35/lib
-L/nix/store/8zqlwy2388xfc1m225zma04i3n3irf7l-freetype-2.9/lib
-L/nix/store/r510mp6mhxdz4k927sn0r7b9ajv1b83y-fontconfig-2.12.6-lib/lib
-L/nix/store/p8j5i0a3r5ipv2yjqly7wm664s5qr5cl-pixman-0.34.0/lib
-L/nix/store/992mmwzy25xwlwc1s64ph1pvghy205w1-libxcb-1.12/lib
-L/nix/store/h89ql6qir0j8mv07x9nl9pi8rcq3gcjf-libX11-1.6.6/lib
-L/nix/store/hqxlagw7dpgd1aykkhck6s471m30n79q-libXrender-0.9.10/lib
-L/nix/store/w7qrmcmgzrrv9jysbzi2fydgva7ihw8m-xcb-util-0.4.0/lib
-L/nix/store/d2bikgsldaq13nfhn6an0vskiq3pdkv7-libGL-1.0.0/lib
-L/nix/store/j3974dvdm3cp1gifqiy9pqy1n9v578ib-cairo-1.15.12/lib
-L/nix/store/hn8xjiwh5pz2d22jcmqqwsqb1wrzi0xh-graphite2-1.3.6/lib
-L/nix/store/alqn91q6w31vzr7na27biwmbwn36qs6h-harfbuzz-1.8.8/lib
-L/nix/store/x0vvpv253r7h5l5p4kphbadid6naf3az-libXft-2.3.2/lib
-L/nix/store/ylf41xd9pdznv2pm8bfv0bq4pa5zvs5r-fribidi-1.0.5/lib
-L/nix/store/8yzqrfb5w7akdm0y7pd9vxc2v9giqlf9-pango-1.42.1/lib
-L/nix/store/hrkvcqgavwmpcckk3mhajgvk8azah6jx-libjpeg-turbo-2.0.1/lib
-L/nix/store/jrzx61apa5js1pll43q7q5gxacz8whjj-xz-5.2.4/lib
-L/nix/store/r4b189c3v46w6pd6kdnxvwxzxpvcs778-libtiff-4.0.10/lib
-L/nix/store/sr0kg36fgladmsy0q9av33vhz5k0jyr8-jasper-2.0.14/lib
-L/nix/store/fb65ghs5231v5qwjybyd7hx8d1q3bbhl-gdk-pixbuf-2.36.12/lib
-L/nix/store/9s2yxvwzawnjgz0xk9yy2d4nssb5yys9-atk-2.28.1/lib
-L/nix/store/hhw2rmyb2hgsw6y28pdqxrw2ww8x6c39-at-spi2-atk-2.26.2/lib
-L/nix/store/m94iyqz0ys3ln5sd2cp485k6mf1h4sa2-libXrandr-1.5.1/lib
-L/nix/store/rns2qgks5r1shm5pviva2vci7zagwcz0-libXfixes-5.0.3/lib
-L/nix/store/cgwkxbgmq5ckrxz471hsbs360blnw1zl-libXcomposite-0.4.4/lib
-L/nix/store/fwlp60q901x2ik3y97i943iadvyrmvia-libXi-1.7.9/lib
-L/nix/store/ahw30nvyf220mzgvb5p2yirhwg3dk9jy-libXcursor-1.1.15/lib
-L/nix/store/cx585b089rkkyih0358fjv1cs699sq76-libICE-1.0.9/lib
-L/nix/store/hbp0kfc22br6i1k9si8w7hbahx4dxzm9-libSM-1.2.2/lib
-L/nix/store/jcjkycg4fvgscnpi8rq7bym5d5rxcyhn-libXdamage-1.1.4/lib
-L/nix/store/rsagacynhsb6z2qr8949bxpflzdvjg2v-libXxf86vm-1.1.4/lib
-L/nix/store/7qcc3xllhc2pqiw2l37rg45hngg525qx-libdrm-2.4.93/lib
-L/nix/store/3x32p2lkd9ga1258x8bhlxvmx64jl92k-mesa-noglu-18.1.7/lib
-L/nix/store/lw7fabjjrkmirawfq8g1l178wz2kxlsw-wayland-1.15.0/lib
-L/nix/store/g93jd13mahngi8gzlnvhrsnf40znb3y6-libXinerama-1.1.3/lib
-L/nix/store/077sn4sz2mxzjm5zqlxxag2170jkkc5n-gmp-6.1.2/lib
-L/nix/store/p0d9v3qfrz781zqdi08imflrlbj1bqyn-cups-2.2.6-lib/lib
-L/nix/store/hqgs95p9axh2g5fl5k92kxd72dif5p09-gtk+3-3.22.30/lib
-L/nix/store/y2574qr6gs3s0qqdjg6lhsgn76bablz5-attr-2.4.47/lib
-L/nix/store/p1w8i3gbs8hr0diibk6bcs8wr2h56zjk-libcap-2.25-lib/lib
-L/nix/store/1a41hgzm9v1r8dcl0qz6hnsvrz87cp0r-glu-9.0.0/lib
-L/nix/store/chimcw80rlb98kb1arhfdvxvw6klz3a1-alsa-lib-1.1.6/lib
-L/nix/store/dqcdmamkgy96rv3rlv10nxdv36scp14v-libpulseaudio-12.2/lib
-L/nix/store/mj1hyp91p746wrzacj4gzm6zksx9j4bb-SDL-1.2.15/lib
-L/nix/store/6iv718x87ir12ljvkpi6nxqccbp4b0ik-libxml2-2.9.8/lib
-L/nix/store/01bwf138158z8y8qzg491ikzxpldzws8-gstreamer-0.10.36/lib
-L/nix/store/6xr27hfjqcahm384pinqksyfqkm5kvcw-gst-plugins-base-0.10.36/lib
-L/nix/store/m3m6vqr13hb3wi8j7g4acv02nxrqwg5x-libnotify-0.7.7/lib
-L/nix/store/gfyz27igijhjk2436s6zngcwqp7q7glw-freeglut-3.0.0/lib
-L/nix/store/rfcndyp9w3ldsymbr2ws40cqacyw6rnr-python3-3.4.9/lib
-L/nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib
-L/nix/store/95i38z61425xrci8h178blwff88p0a4h-gcc-7.3.0-lib/lib
-L/nix/store/95i38z61425xrci8h178blwff88p0a4h-gcc-7.3.0-lib/lib
-L/nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib
-L/nix/store/nwy73lby94rv8jql92xhxp0wx6gxwjb2-gcc-wrapper-7.3.0/bin
-L/nix/store/nly6dg3af8ycqn1x87ns1r3mrcjpv43a-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0
-L/nix/store/nly6dg3af8ycqn1x87ns1r3mrcjpv43a-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../lib64
-L/nix/store/nly6dg3af8ycqn1x87ns1r3mrcjpv43a-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../..
-dynamic-linker /nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/ld-linux-x86-64.so.2
-rpath /nix/store/xch88b18bndxidjj1zhww3mgpc810xgh-shell/lib64
-rpath /nix/store/xch88b18bndxidjj1zhww3mgpc810xgh-shell/lib
-rpath /nix/store/khv2akja4vz2rij681lhqgq72329q2qr-python3.4-wxPython-4.0.3/lib64
-rpath /nix/store/khv2akja4vz2rij681lhqgq72329q2qr-python3.4-wxPython-4.0.3/lib
-rpath /nix/store/58yg658n37786aybl47h38gfwimp0gf1-shell/lib64
-rpath /nix/store/58yg658n37786aybl47h38gfwimp0gf1-shell/lib
-lstdc++
-lm
-lgcc_s
-lgcc
-lpthread
-lc
-lgcc_s
-lgcc
/nix/store/nly6dg3af8ycqn1x87ns1r3mrcjpv43a-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/crtend.o
/nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/crtn.o
-rpath /nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib
-rpath /nix/store/95i38z61425xrci8h178blwff88p0a4h-gcc-7.3.0-lib/lib
```
I'd continue but I'm out of time for today.

**Comment by deliciouslytyped** [comment]
Googling the errors very tangentially suggests that this may be related to position independent code but that may be completely wrong.

**Comment by deliciouslytyped** [comment]
There is also a general run-down of the/a build process at https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/

**Comment by veprbl** [comment]
> #still gets 4.0.3 for some reason

likely need to update sha256 hash

**Comment by deliciouslytyped** [comment]
Well, I'll check. Unless I somehow failed to correctly get the hash from Pypi, it should be the right one... (You are probably correct)

**Comment by deliciouslytyped** [comment]
Should probably be closed if https://github.com/NixOS/nixpkgs/pull/61253 or similar is merged.

**Comment by deliciouslytyped** [comment]
I haven't followed up on why this linking problem was happening, but I'm closing this because @tbenst 's PR thread seems to resolve it.
