### ISSUE TITLE
python37Packages.yapf fails on Darwin (nixpkgs-18.09-darwin)

### ISSUE THREAD

**Issue by supersven** [NixOS/nixpkgs#55752]
## Issue description

Building `python37Packages.yapf` fails on my MacBook while running tests. This problem occurs with `nixpkgs-18.09-darwin` and `nixpkgs-unstable`.

```
➜  ~ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-18.09-darwin
➜  ~ nix-channel --update
unpacking channels...
➜  ~ nix-shell "<nixpkgs>" -p python37Packages.yapf
these derivations will be built:
  /nix/store/1r2j6xh5k42a8f0diwb62f8lbif2bbl5-python3.7-yapf-0.22.0.drv
building '/nix/store/1r2j6xh5k42a8f0diwb62f8lbif2bbl5-python3.7-yapf-0.22.0.drv'...
unpacking sources
unpacking source archive /nix/store/ha2ihc01sqapqy9nfa1z40jbdrgqn8qk-yapf-0.22.0.tar.gz
source root is yapf-0.22.0
setting SOURCE_DATE_EPOCH to timestamp 1526448334 of file yapf-0.22.0/yapf.egg-info/top_level.txt
patching sources
configuring
building
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/yapf
copying yapf/__init__.py -> build/lib/yapf
copying yapf/__main__.py -> build/lib/yapf
creating build/lib/yapf/yapflib
copying yapf/yapflib/object_state.py -> build/lib/yapf/yapflib
copying yapf/yapflib/yapf_api.py -> build/lib/yapf/yapflib
copying yapf/yapflib/py3compat.py -> build/lib/yapf/yapflib
copying yapf/yapflib/format_decision_state.py -> build/lib/yapf/yapflib
copying yapf/yapflib/pytree_visitor.py -> build/lib/yapf/yapflib
copying yapf/yapflib/style.py -> build/lib/yapf/yapflib
copying yapf/yapflib/unwrapped_line.py -> build/lib/yapf/yapflib
copying yapf/yapflib/pytree_utils.py -> build/lib/yapf/yapflib
copying yapf/yapflib/comment_splicer.py -> build/lib/yapf/yapflib
copying yapf/yapflib/__init__.py -> build/lib/yapf/yapflib
copying yapf/yapflib/reformatter.py -> build/lib/yapf/yapflib
copying yapf/yapflib/blank_line_calculator.py -> build/lib/yapf/yapflib
copying yapf/yapflib/line_joiner.py -> build/lib/yapf/yapflib
copying yapf/yapflib/split_penalty.py -> build/lib/yapf/yapflib
copying yapf/yapflib/file_resources.py -> build/lib/yapf/yapflib
copying yapf/yapflib/format_token.py -> build/lib/yapf/yapflib
copying yapf/yapflib/errors.py -> build/lib/yapf/yapflib
copying yapf/yapflib/pytree_unwrapper.py -> build/lib/yapf/yapflib
copying yapf/yapflib/subtype_assigner.py -> build/lib/yapf/yapflib
copying yapf/yapflib/identify_container.py -> build/lib/yapf/yapflib
copying yapf/yapflib/continuation_splicer.py -> build/lib/yapf/yapflib
copying yapf/yapflib/verifier.py -> build/lib/yapf/yapflib
creating build/lib/yapftests
copying yapftests/comment_splicer_test.py -> build/lib/yapftests
copying yapftests/pytree_utils_test.py -> build/lib/yapftests
copying yapftests/reformatter_python3_test.py -> build/lib/yapftests
copying yapftests/reformatter_basic_test.py -> build/lib/yapftests
copying yapftests/blank_line_calculator_test.py -> build/lib/yapftests
copying yapftests/unwrapped_line_test.py -> build/lib/yapftests
copying yapftests/reformatter_style_config_test.py -> build/lib/yapftests
copying yapftests/__init__.py -> build/lib/yapftests
copying yapftests/reformatter_verify_test.py -> build/lib/yapftests
copying yapftests/reformatter_facebook_test.py -> build/lib/yapftests
copying yapftests/pytree_unwrapper_test.py -> build/lib/yapftests
copying yapftests/format_token_test.py -> build/lib/yapftests
copying yapftests/utils.py -> build/lib/yapftests
copying yapftests/subtype_assigner_test.py -> build/lib/yapftests
copying yapftests/pytree_visitor_test.py -> build/lib/yapftests
copying yapftests/main_test.py -> build/lib/yapftests
copying yapftests/reformatter_buganizer_test.py -> build/lib/yapftests
copying yapftests/split_penalty_test.py -> build/lib/yapftests
copying yapftests/style_test.py -> build/lib/yapftests
copying yapftests/yapf_test.py -> build/lib/yapftests
copying yapftests/line_joiner_test.py -> build/lib/yapftests
copying yapftests/yapf_test_helper.py -> build/lib/yapftests
copying yapftests/reformatter_pep8_test.py -> build/lib/yapftests
copying yapftests/file_resources_test.py -> build/lib/yapftests
copying yapftests/format_decision_state_test.py -> build/lib/yapftests
installing to build/bdist.macosx-10.6-x86_64/wheel
running install
running install_lib
creating build/bdist.macosx-10.6-x86_64
creating build/bdist.macosx-10.6-x86_64/wheel
creating build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/comment_splicer_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/pytree_utils_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/reformatter_python3_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/reformatter_basic_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/blank_line_calculator_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/unwrapped_line_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/reformatter_style_config_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/__init__.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/reformatter_verify_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/reformatter_facebook_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/pytree_unwrapper_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/format_token_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/utils.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/subtype_assigner_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/pytree_visitor_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/main_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/reformatter_buganizer_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/split_penalty_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/style_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/yapf_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/line_joiner_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/yapf_test_helper.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/reformatter_pep8_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/file_resources_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
copying build/lib/yapftests/format_decision_state_test.py -> build/bdist.macosx-10.6-x86_64/wheel/yapftests
creating build/bdist.macosx-10.6-x86_64/wheel/yapf
copying build/lib/yapf/__init__.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf
creating build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/object_state.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/yapf_api.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/py3compat.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/format_decision_state.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/pytree_visitor.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/style.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/unwrapped_line.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/pytree_utils.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/comment_splicer.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/__init__.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/reformatter.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/blank_line_calculator.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/line_joiner.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/split_penalty.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/file_resources.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/format_token.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/errors.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/pytree_unwrapper.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/subtype_assigner.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/identify_container.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/continuation_splicer.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/yapflib/verifier.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf/yapflib
copying build/lib/yapf/__main__.py -> build/bdist.macosx-10.6-x86_64/wheel/yapf
running install_egg_info
running egg_info
writing yapf.egg-info/PKG-INFO
writing dependency_links to yapf.egg-info/dependency_links.txt
writing entry points to yapf.egg-info/entry_points.txt
writing top-level names to yapf.egg-info/top_level.txt
reading manifest file 'yapf.egg-info/SOURCES.txt'
writing manifest file 'yapf.egg-info/SOURCES.txt'
Copying yapf.egg-info to build/bdist.macosx-10.6-x86_64/wheel/yapf-0.22.0-py3.7.egg-info
running install_scripts
creating build/bdist.macosx-10.6-x86_64/wheel/yapf-0.22.0.dist-info/WHEEL
creating 'dist/yapf-0.22.0-py2.py3-none-any.whl' and adding 'build/bdist.macosx-10.6-x86_64/wheel' to it
adding 'yapf/__init__.py'
adding 'yapf/__main__.py'
adding 'yapf/yapflib/__init__.py'
adding 'yapf/yapflib/blank_line_calculator.py'
adding 'yapf/yapflib/comment_splicer.py'
adding 'yapf/yapflib/continuation_splicer.py'
adding 'yapf/yapflib/errors.py'
adding 'yapf/yapflib/file_resources.py'
adding 'yapf/yapflib/format_decision_state.py'
adding 'yapf/yapflib/format_token.py'
adding 'yapf/yapflib/identify_container.py'
adding 'yapf/yapflib/line_joiner.py'
adding 'yapf/yapflib/object_state.py'
adding 'yapf/yapflib/py3compat.py'
adding 'yapf/yapflib/pytree_unwrapper.py'
adding 'yapf/yapflib/pytree_utils.py'
adding 'yapf/yapflib/pytree_visitor.py'
adding 'yapf/yapflib/reformatter.py'
adding 'yapf/yapflib/split_penalty.py'
adding 'yapf/yapflib/style.py'
adding 'yapf/yapflib/subtype_assigner.py'
adding 'yapf/yapflib/unwrapped_line.py'
adding 'yapf/yapflib/verifier.py'
adding 'yapf/yapflib/yapf_api.py'
adding 'yapftests/__init__.py'
adding 'yapftests/blank_line_calculator_test.py'
adding 'yapftests/comment_splicer_test.py'
adding 'yapftests/file_resources_test.py'
adding 'yapftests/format_decision_state_test.py'
adding 'yapftests/format_token_test.py'
adding 'yapftests/line_joiner_test.py'
adding 'yapftests/main_test.py'
adding 'yapftests/pytree_unwrapper_test.py'
adding 'yapftests/pytree_utils_test.py'
adding 'yapftests/pytree_visitor_test.py'
adding 'yapftests/reformatter_basic_test.py'
adding 'yapftests/reformatter_buganizer_test.py'
adding 'yapftests/reformatter_facebook_test.py'
adding 'yapftests/reformatter_pep8_test.py'
adding 'yapftests/reformatter_python3_test.py'
adding 'yapftests/reformatter_style_config_test.py'
adding 'yapftests/reformatter_verify_test.py'
adding 'yapftests/split_penalty_test.py'
adding 'yapftests/style_test.py'
adding 'yapftests/subtype_assigner_test.py'
adding 'yapftests/unwrapped_line_test.py'
adding 'yapftests/utils.py'
adding 'yapftests/yapf_test.py'
adding 'yapftests/yapf_test_helper.py'
adding 'yapf-0.22.0.dist-info/METADATA'
adding 'yapf-0.22.0.dist-info/WHEEL'
adding 'yapf-0.22.0.dist-info/entry_points.txt'
adding 'yapf-0.22.0.dist-info/top_level.txt'
adding 'yapf-0.22.0.dist-info/RECORD'
removing build/bdist.macosx-10.6-x86_64/wheel
installing
/private/var/folders/xd/jx99wbcx2cj5clyb60bbjmk40000gn/T/nix-build-python3.7-yapf-0.22.0.drv-0/yapf-0.22.0/dist /private/var/folders/xd/jx99wbcx2cj5clyb60bbjmk40000gn/T/nix-build-python3.7-yapf-0.22.0.drv-0/yapf-0.22.0
Processing ./yapf-0.22.0-py2.py3-none-any.whl
Installing collected packages: yapf
  The script yapf is installed in '/nix/store/3ixf0djz5appn42myqcfzzhhx82f7ids-python3.7-yapf-0.22.0/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed yapf-0.22.0
/private/var/folders/xd/jx99wbcx2cj5clyb60bbjmk40000gn/T/nix-build-python3.7-yapf-0.22.0.drv-0/yapf-0.22.0
post-installation fixup
strip is /nix/store/s0rd1fic9x9nb9vwv0lymlmjq6w11f7q-cctools-binutils-darwin/bin/strip
stripping (with command strip and flags -S) in /nix/store/3ixf0djz5appn42myqcfzzhhx82f7ids-python3.7-yapf-0.22.0/lib  /nix/store/3ixf0djz5appn42myqcfzzhhx82f7ids-python3.7-yapf-0.22.0/bin
patching script interpreter paths in /nix/store/3ixf0djz5appn42myqcfzzhhx82f7ids-python3.7-yapf-0.22.0
wrapping `/nix/store/3ixf0djz5appn42myqcfzzhhx82f7ids-python3.7-yapf-0.22.0/bin/yapf'...
running install tests
running test
.............................................................................................................F.....................................................................................................................................................................................................................................................................................ssss.....................................................................................................
======================================================================
FAIL: testAsyncAsNonKeyword (yapftests.reformatter_basic_test.BasicReformatterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/folders/xd/jx99wbcx2cj5clyb60bbjmk40000gn/T/nix-build-python3.7-yapf-0.22.0.drv-0/yapf-0.22.0/yapftests/reformatter_basic_test.py", line 2489, in testAsyncAsNonKeyword
    self.assertCodeEqual(code, reformatter.Reformat(uwlines, verify=False))
  File "/private/var/folders/xd/jx99wbcx2cj5clyb60bbjmk40000gn/T/nix-build-python3.7-yapf-0.22.0.drv-0/yapf-0.22.0/yapftests/yapf_test_helper.py", line 57, in assertCodeEqual
    self.fail('\n'.join(msg))
AssertionError: Code format mismatch:
Expected:
 > from util import async
 >
 >
 > class A(object):
 >     def foo(self):
 >         async.run()
 >
 >     def bar(self):
 >         pass
Actual:
 > from util import async
 >
 >
 > class A(object):
 >     def foo(self):
 >         async .run()
 >
 >     def bar(self):
 >         pass
Diff:
--- actual
+++ expected
@@ -3,7 +3,7 @@

 class A(object):
     def foo(self):
-        async .run()
+        async.run()

     def bar(self):
         pass

----------------------------------------------------------------------
Ran 492 tests in 6.457s

FAILED (failures=1, skipped=4)
builder for '/nix/store/1r2j6xh5k42a8f0diwb62f8lbif2bbl5-python3.7-yapf-0.22.0.drv' failed with exit code 1
error: build of '/nix/store/1r2j6xh5k42a8f0diwb62f8lbif2bbl5-python3.7-yapf-0.22.0.drv' failed
```

### Steps to reproduce

Run `nix-shell -p python37Packages.yapf` on MacOs.

## Technical details
```
➜  ~ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/brfh40lnfbp0sjq4h7fjmgqk62g98jdr-nix-info
  /nix/store/hiqp87px3ki8xipkz3n0yi0fs2v2nj22-DarwinTools-1
copying path '/nix/store/hiqp87px3ki8xipkz3n0yi0fs2v2nj22-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/brfh40lnfbp0sjq4h7fjmgqk62g98jdr-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.3`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2`
 - channels(sventennie): `"nixpkgs-18.09pre153724.89bf7472a15, unstable-19.03pre169106.1a88aa9e0cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/sventennie/channels/nixpkgs`
```

**Comment by smancill** [comment]
This should be closed:

```
$ nix-shell -p python3Packages.yapf
these paths will be fetched (0.20 MiB download, 1.37 MiB unpacked):
  /nix/store/35s9kqnljjw4wcsr06i7dnxmxb0k5s60-python3.8-yapf-0.31.0
copying path '/nix/store/35s9kqnljjw4wcsr06i7dnxmxb0k5s60-python3.8-yapf-0.31.0' from 'https://cache.nixos.org'...
```
