### ISSUE TITLE
Cozy-0.6.7 fails to run

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#57029]
## Issue description
i tried installing the version of cozy that is in nixpkgs git repo. It crashes on running. 

### Steps to reproduce
nix-env -i cozy -f ~/code/nixos/nixpkgs/
cozy
Traceback (most recent call last):
  File "/nix/store/jjz2dzbd4i1yrwnq26g8490zcn6dd9ip-cozy-0.6.7/bin/..com.github.geigi.cozy-wrapped-wrapped", line 36, in <module>
    from cozy.ui import CozyUI
  File "/nix/store/jjz2dzbd4i1yrwnq26g8490zcn6dd9ip-cozy-0.6.7/lib/python3.7/site-packages/cozy/ui.py", line 5, in <module>
    gi.require_version('Gst', '1.0')
  File "/nix/store/kiw47xswi1041sbvbgrlfy0xs0zlwyvk-python3.7-pygobject-3.30.4/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.26, NixOS, 18.09.2318.4c089d328fe (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2318.4c089d328fe"`
 - channels(mog): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by mweinelt** [comment]
Broken in 19.03 as well.

```
$ cozy                                                                                                ✔  5123  20:39:54 
Traceback (most recent call last):
  File "/nix/store/bhyhk39yxiszg8rx0rsmkrl633jywips-cozy-0.6.7/bin/..com.github.geigi.cozy-wrapped-wrapped", line 36, in <module>
    from cozy.ui import CozyUI
  File "/nix/store/bhyhk39yxiszg8rx0rsmkrl633jywips-cozy-0.6.7/lib/python3.7/site-packages/cozy/ui.py", line 5, in <module>
    gi.require_version('Gst', '1.0')
  File "/nix/store/qilk9npmnbgnp0ypf7s0bjh20qh3ylqh-python3.7-pygobject-3.30.4/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available
```

```
$ nix-info                                                                                            ✔  5122  20:39:51 
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.2.2, channels(root): "nixos-19.03.173052.aef662d2eb5, nixos-hardware, nixos-unstable-19.09pre182971.a1dd419c1ff", channels(hexa): "", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
````

**Comment by worldofpeace** [comment]
https://github.com/NixOS/nixpkgs/commit/a203bc741e59fd54475aaa0327acc08efde6a444 has fixed this
