### ISSUE TITLE
cura-lulzbot: 15.02.1-1.03-5064 -> 3.6.3

### ISSUE THREAD

**Issue by aaronjanse** [NixOS/nixpkgs#57207]
I'm trying to update [cura-lulzbot](https://github.com/NixOS/nixpkgs/blob/2b5659dc04c4d163aca087bb0653337845bbdf34/pkgs/applications/misc/cura/lulzbot.nix) to version 3.6.3 (which is newer than the current version 15.02.1-1.03-5064).

This is what I've got so far: [gist](https://gist.github.com/aaronduino/0f35ca4ad6d39248c7480eda3c13e19f)

While it build without failing, I get the following error when trying to run its binary `cura` ([full log](https://gist.github.com/aaronduino/50c34b6860123e69cc9a7d0bbca1a0c8)):

```
Traceback (most recent call last):
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3.5/site-packages/numpy/core/__init__.py", line 16, in <module>
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3.5/site-packages/cx_Freeze-6.0b1-py3.5-linux-x86_64.egg/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3.5/site-packages/cx_Freeze-6.0b1-py3.5-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 26, in run
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/bin/cura-lulzbot", line 86, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3/dist-packages/cura/CuraApplication.py", line 7, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3/dist-packages/UM/Qt/QtApplication.py", line 18, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3/dist-packages/UM/FileHandler/ReadFileJob.py", line 5, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3/dist-packages/UM/Application.py", line 9, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3/dist-packages/UM/Controller.py", line 4, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3/dist-packages/UM/Scene/Scene.py", line 4, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3/dist-packages/UM/Scene/SceneNode.py", line 5, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3/dist-packages/UM/Math/Matrix.py", line 7, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
  File "/home/buildbot/slave/CuraLEDevel-debian-jessie-64/build/build/inst/lib/python3.5/site-packages/numpy/core/__init__.py", line 24, in <module>
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control). Otherwise reinstall numpy.
```

If anyone is willing to offer assistance, the help would be greatly appreciated. I'd love to have an updated version of Cura on NixOS.

**Comment by gebner** [comment]
Fixed in #61054.
