### ISSUE TITLE
kazam on Linux throws error on first run

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#57660]
## Issue description

Running Kazam gives me an error:

```
~ $ nix-env -iA nixpkgs.kazam
installing 'kazam-1.4.5'
these paths will be fetched (1.03 MiB download, 1.68 MiB unpacked):
  /nix/store/isckn9q6sxgxnn9xqiw3vmic0db96ian-kazam-1.4.5
copying path '/nix/store/isckn9q6sxgxnn9xqiw3vmic0db96ian-kazam-1.4.5' from 'https://cache.nixos.org'...
building '/nix/store/69vbx35bq8pn8dhsz5zgr3kxyqk60z2d-user-environment.drv'...
created 2936 symlinks in user environment
~ $ kazam
Traceback (most recent call last):
  File "/nix/store/kiw47xswi1041sbvbgrlfy0xs0zlwyvk-python3.7-pygobject-3.30.4/lib/python3.7/site-packages/gi/importer.py", line 138, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/nix/store/kiw47xswi1041sbvbgrlfy0xs0zlwyvk-python3.7-pygobject-3.30.4/lib/python3.7/site-packages/gi/module.py", line 265, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/nix/store/kiw47xswi1041sbvbgrlfy0xs0zlwyvk-python3.7-pygobject-3.30.4/lib/python3.7/site-packages/gi/module.py", line 117, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Typelib file for namespace 'Pango', version '1.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/isckn9q6sxgxnn9xqiw3vmic0db96ian-kazam-1.4.5/bin/..kazam-wrapped-wrapped", line 33, in <module>
    from gi.repository import Gtk
  File "/nix/store/kiw47xswi1041sbvbgrlfy0xs0zlwyvk-python3.7-pygobject-3.30.4/lib/python3.7/site-packages/gi/importer.py", line 140, in load_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'Pango', version '1.0' not found
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by worldofpeace** [comment]
@matthewbauer Maybe this is https://github.com/NixOS/nixpkgs/issues/56943?

**Comment by matthewbauer** [comment]
Ah yeah that looks like the cause.

**Comment by madhukar93** [comment]
I'm still getting this on the latest unstable channel, does not seem fixed
