### ISSUE TITLE
PyTorch with CUDA broken "AssertionError: Torch not compiled with CUDA enabled"

### ISSUE THREAD

**Issue by smatting** [NixOS/nixpkgs#58934]
## Issue description

@teh @thoughtpolice 

The python package PyTorch (with Cuda support) `pytorchWithCuda` fails with` AssertionError: Torch not compiled with CUDA enabled`:

```
$ $(nix-build -A python problem.nix)/bin/python -c 'import torch; torch.rand(1).cuda()'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/1fjvk90rwqk67zwbv5n64nsgb912mriy-python3-3.7.2-env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    _check_driver()
  File "/nix/store/1fjvk90rwqk67zwbv5n64nsgb912mriy-python3-3.7.2-env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

```
I'm reproducing this error with a recent `nixpkgs` (commit from Mar 22, 2019) from the `nixos/unstable` channel (see `problem.nix` below).

Here's a snippet from `__init__.py` from pytorch where the `AssertionError` is raised in line 75
```python
def _check_driver():
    if not hasattr(torch._C, '_cuda_isDriverSufficient'):
        raise AssertionError("Torch not compiled with CUDA enabled")
```

### No cudatoolkit in closure of pytorchWithCuda

I'm not sure if it's relevant, but suprisiingly the closure of `pytorchWithCuda` also doesn't contain any derivation from `cudatoolkit` or `cudnn`:

```
$ nix-store -qR $(nix-build -A pytorch problem.nix)
/nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27
/nix/store/2xb0wphs5h89i0k1r8lya9fpsjwkn7xm-openssl-1.0.2r
/nix/store/cinw572b38aln37glr0zb8lxwrgaffl4-bash-4.4-p23
/nix/store/iiymx8j7nlar3gc23lfkcscvr61fng8s-zlib-1.2.11
/nix/store/g4rgyrkq7yfnqfmv5hxsc32x6cydh1nc-sqlite-3.26.0
/nix/store/k0y9nrym785l61pjw0lp0qk90v2nbpqs-ncurses-6.1-20190112
/nix/store/kbbiky87bsdndh63m7919sxkf3gsh5zq-libffi-3.2.1
/nix/store/kmxlgixizhxv8llspci6l1j9dh2gpnam-gdbm-1.18.1
/nix/store/mibh7947iwgf5yiqc7njn0igfzlxzdf1-xz-5.2.4
/nix/store/wlivxbc4ny21gzq9a561bwx9b4p08m4m-bzip2-1.0.6.0.1
/nix/store/xjzx54lx91bmhbpwccsygv01a1zf25y9-expat-2.2.6
/nix/store/xmkywjhcgvrhpkggv26b4dc438k2dd2y-readline-6.3p08
/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2
/nix/store/hqjvxjk61nsv2rlpb2d5ry3miipy9a9h-python3.7-setuptools-40.8.0
/nix/store/2zs46xf1cf621bc6czrdhzc1yf7dffm8-python3.7-pycparser-2.19
/nix/store/ikk8jjnhhgvg0asid5m0k7jwyf8qkl7l-libffi-3.2.1-dev
/nix/store/p4l3x7hy6gwldhiya2svfig753mw14z3-python3.7-cffi-1.12.1
/nix/store/8a36yi82pxfykpli6cra8w8p93nl7r4s-python3.7-cffi-1.12.1-dev
/nix/store/ckdny7g7w0s07bxkjp5k9a00vbcw7pk4-numactl-2.0.12
/nix/store/l3fbpz66yfjvamy0bi9fjlhwpp57g14y-gcc-7.4.0-lib
/nix/store/zmj4mkv32vpi9d9ips1fhgjlppjziknw-gfortran-7.4.0-lib
/nix/store/x2bijqr1l5hivs9h990ms6xlwvmp3asc-openblas-0.3.5
/nix/store/rxvw3i2kmnjc3yc41xg4xfc0k2sygr2c-python3.7-numpy-1.16.1
/nix/store/qykwgnnfa0y4scilb7qi7bfsgskmhwl7-libyaml-0.2.1
/nix/store/xw55n4dzy46qxcfl7qqzg4zsy4dvv1i9-python3.7-PyYAML-3.13
/nix/store/kcvcis3hfvf22kkvsaaya8z7y5m916cy-python3.7-pytorch-1.0.0
```

In contrast the closure of older iterations of `pytorchWithCuda` contains `cudatoolkit` and `cudnn`.

### Success with previous iterations of the package

I'm able to sucessfully use `pytorchWithCuda` from an older commit from `nixpkgs` where the pytorch version is `0.4.1`. The python script `import torch; torch.rand(1).cuda()` will produce no output if everything works. To make it work however I have to explicitly load the CUDA libs drivers from the nvidia drivers:
Snippets from nixos `configuration.nix`:
```nix
{
services.xserver.videoDrivers = [ "nvidia" ];
    environment.variables = {
        LD_PRELOAD = "${pkgs.linuxPackages.nvidia_x11}/lib/libcuda.so:${pkgs.linuxPackages.nvidia_x11}/lib/libnvidia-fatbinaryloader.so";
    };
}
```
I can reproduce the problem with and without setting `LD_PRELOAD` like above.

### Steps to reproduce

Save the following snippet as `problem.nix`
```nix
let
  bootstrap = import <nixpkgs> { };

  nixpkgSrc = 
    bootstrap.fetchFromGitHub {
      owner = "NixOS";
      repo  = "nixpkgs";

      # https://releases.nixos.org/nixos/unstable/nixos-19.09pre173349.07b42ccf2de/git-revision
      rev = "07b42ccf2de451342982b550657636d891c4ba35";
      sha256 = "1a7ga18pwq0y4p9r787622ry8gssw1p6wsr5l7dl8pqnj1hbbzwh";

    };

  config = { allowUnfree = true; };

  pkgs = import nixpkgSrc { inherit config; };

in {
  pytorch = pkgs.python37Packages.pytorchWithCuda;
  python = pkgs.python37.withPackages (ps: with ps; [pytorchWithCuda]);
}
```
then run commands
```sh
$(nix-build -A python problem.nix)/bin/python -c 'import torch; torch.rand(1).cuda()'
```
```sh
nix-store -qR $(nix-build -A pytorch problem.nix)
```

**Comment by smatting** [comment]
I can upload the binary caches to cachix if this helps you.

**Comment by teh** [comment]
I'm not using CUDA so haven't tested that path. Does this work for you? https://github.com/NixOS/nixpkgs/pull/57438/files If yes might be worth getting that PR cleaned up and merged.

**Comment by smatting** [comment]
Yes that worked! See my comments on that pull request.

**Comment by andersk** [comment]
This was resolved by #60002, right?

**Comment by ashkan-leo** [comment]
I am facing the same issue when installing torch with CUDA support. Torch is not compiled with CUDA support. I am using the latest version of nix and torch.

**Comment by ConnorBaker** [comment]
Apologies for the bump -- @ashkan-leo is this still a problem you're encountering? If so, would you mind sharing a reproducer?
