### ISSUE TITLE
home-assistant no longer automatically includes proper dependencies

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#59251]
## Issue description

On 0.91.1, many components have stopped working as the required python dependencies are not being pulled in correctly. Manually adding them to ```extraPackages``` in the package override makes things work again.

Here are some examples:

```
Error setting up platform unifi

Traceback (most recent call last):
  File "/nix/store/mp3vi175h7dfcvgkd1n45gk3wlrhyhjx-homeassistant-0.91.1/lib/python3.7/site-packages/homeassistant/components/device_tracker/__init__.py", line 177, in async_setup_platform
    platform.get_scanner, hass, {DOMAIN: p_config})
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nix/store/mp3vi175h7dfcvgkd1n45gk3wlrhyhjx-homeassistant-0.91.1/lib/python3.7/site-packages/homeassistant/components/unifi/device_tracker.py", line 66, in get_scanner
    from pyunifi.controller import Controller, APIError
ModuleNotFoundError: No module named 'pyunifi'

Error while setting up platform onkyo

Traceback (most recent call last):
  File "/nix/store/mp3vi175h7dfcvgkd1n45gk3wlrhyhjx-homeassistant-0.91.1/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nix/store/mp3vi175h7dfcvgkd1n45gk3wlrhyhjx-homeassistant-0.91.1/lib/python3.7/site-packages/homeassistant/components/onkyo/media_player.py", line 100, in setup_platform
    import eiscp
ModuleNotFoundError: No module named 'eiscp'

darksky: Error on device update!

Traceback (most recent call last):
  File "/nix/store/mp3vi175h7dfcvgkd1n45gk3wlrhyhjx-homeassistant-0.91.1/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/nix/store/mp3vi175h7dfcvgkd1n45gk3wlrhyhjx-homeassistant-0.91.1/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 379, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nix/store/mp3vi175h7dfcvgkd1n45gk3wlrhyhjx-homeassistant-0.91.1/lib/python3.7/site-packages/homeassistant/components/darksky/weather.py", line 197, in update
    self._dark_sky.update()
  File "/nix/store/mp3vi175h7dfcvgkd1n45gk3wlrhyhjx-homeassistant-0.91.1/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/nix/store/mp3vi175h7dfcvgkd1n45gk3wlrhyhjx-homeassistant-0.91.1/lib/python3.7/site-packages/homeassistant/components/darksky/weather.py", line 223, in update
    import forecastio
ModuleNotFoundError: No module named 'forecastio'
```

There are several more.

This is when deploying 0.91.1 from unstable on 19.03

**Comment by dotlambda** [comment]
I thought 971187eadaf00a86a57951823ab844e9c23694ac had made it into `release-19.03`. But it seems it didn't. Can you check whether cherry picking that works?

**Comment by dotlambda** [comment]
We might also want to backport it to `release-18.09`.

**Comment by peterhoeg** [comment]
Yep, that works.
