### ISSUE TITLE
wicd is unable to finilize connection due to error.

### ISSUE THREAD

**Issue by Gonzih** [NixOS/nixpkgs#59359]
## Issue description

On my fresh installation of nixos with wicd enabled instead of networkmanager I get following error at the end of connection process in wicd. Wicd is able to connect to a network, but wicd-gtk ui is stuck in "Done connecting" state.

My attempts at googling this issue pointed me at the old issues in wicd when it was crashing due to hidden networks being present. Seems like this issue was patched some time ago now.

```
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: Starting automatic reconnect process
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: Throttling autoreconnect
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: Caught exception org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:   File "/nix/store/vbwj8csx5nrrh3dp378qs9ci8qv7ja9q-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/service.py", line 751, in _message_cb
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:     _method_reply_return(connection, message, method_name, signature, *retval)
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:   File "/nix/store/vbwj8csx5nrrh3dp378qs9ci8qv7ja9q-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/service.py", line 254, in _method_reply_return
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:     reply.append(signature=signature, *retval)
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: TypeError: expected string without null bytes
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: Caught exception org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:   File "/nix/store/vbwj8csx5nrrh3dp378qs9ci8qv7ja9q-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/service.py", line 751, in _message_cb
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:     _method_reply_return(connection, message, method_name, signature, *retval)
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:   File "/nix/store/vbwj8csx5nrrh3dp378qs9ci8qv7ja9q-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/service.py", line 254, in _method_reply_return
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:     reply.append(signature=signature, *retval)
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: TypeError: expected string without null bytes
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: Caught exception org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:   File "/nix/store/vbwj8csx5nrrh3dp378qs9ci8qv7ja9q-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/service.py", line 751, in _message_cb
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:     _method_reply_return(connection, message, method_name, signature, *retval)
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:   File "/nix/store/vbwj8csx5nrrh3dp378qs9ci8qv7ja9q-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/service.py", line 254, in _method_reply_return
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:     reply.append(signature=signature, *retval)
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: TypeError: expected string without null bytes
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: Caught exception org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:   File "/nix/store/vbwj8csx5nrrh3dp378qs9ci8qv7ja9q-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/service.py", line 751, in _message_cb
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:     _method_reply_return(connection, message, method_name, signature, *retval)
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:   File "/nix/store/vbwj8csx5nrrh3dp378qs9ci8qv7ja9q-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/service.py", line 254, in _method_reply_return
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:     reply.append(signature=signature, *retval)
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: TypeError: expected string without null bytes
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: Caught exception org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:   File "/nix/store/vbwj8csx5nrrh3dp378qs9ci8qv7ja9q-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/service.py", line 751, in _message_cb
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:     _method_reply_return(connection, message, method_name, signature, *retval)
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:   File "/nix/store/vbwj8csx5nrrh3dp378qs9ci8qv7ja9q-python2.7-dbus-python-1.2.4/lib/python2.7/site-packages/dbus/service.py", line 254, in _method_reply_return
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]:     reply.append(signature=signature, *retval)
Apr 12 11:07:00 nixos krvqc6pwinsw452757wlpnlilvcx5aqw-unit-script-wicd-start[9038]: TypeError: expected string without null bytes
```

### Steps to reproduce

Setup clean nixos stable installation with wicd support. 
Relevant networking section of my config:

```nix
{ config, pkgs, ... }:

{
  networking = {
    # Open ports in the firewall.
    # firewall.allowedTCPPorts = [ ... ];
    # firewall.allowedUDPPorts = [ ... ];
    # Or disable the firewall altogether.
    # firewall.enable = false;

    hostName = "nixos"; # Define your hostname.
    useDHCP = false; # Don't run dhclient on wlan0
    wireless.enable = false;  # Enables wireless support via wpa_supplicant.
    networkmanager.enable = false;
    wicd.enable = true;

    # Configure network proxy if necessary
    # proxy.default = "http://user:password@proxy:port/";
    # proxy.noProxy = "127.0.0.1,localhost,internal.domain";
  };
}
```

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/ial8a56ys2rswfq4j2abm3cl99li5b6p-bash-interactive-4.4-p23-dev
copying path '/nix/store/ial8a56ys2rswfq4j2abm3cl99li5b6p-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.110, NixOS, 18.09.2474.222950952f1 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Gonzih** [comment]
Switched this installation to `nixos-unstable` channel and issue is gone now.

**Comment by Gonzih** [comment]
Closing this since it seems to be fixed in unstable and reproducing it might be a bit tricky.

**Comment by Gonzih** [comment]
Same issue no `19.03`.

**Comment by jul1u5** [comment]
How did you solve it in `19.03`?
