### ISSUE TITLE
Package request: manim

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#60284]
# Manim - Mathematical Animation Engine

Manim is an animation engine for explanatory math videos. It's used to create precise animations programmatically, as seen in the videos at [3Blue1Brown](https://www.3blue1brown.com/).

Upstream repository: https://github.com/3b1b/manim

This is a state-of-the-art mathematics animation utility installed with Python.

**Comment by JohnAZoidberg** [comment]
It's not trivial... I'm trying.
They don't have a `setup.py` and it tries to write to the installation location, which is not possible in the nix-store.

In the meantime you can get a nix-shell with the dependencies like this:
`nix-shell -p cairo sox ffmpeg xdg_utils "python3.withPackages(ps: with ps; [ opencv numpy pillow progressbar scipy tqdm pycairo pydub ])"`

**Comment by JohnAZoidberg** [comment]
Got it! https://github.com/JohnAZoidberg/nixpkgs/commit/17463b9c40411cbc001f52205998a688607ea0b9
I'll wait for feedback from upstream until I proceed with a PR here.
I'm not sure if I packaged all python scripts.

**Comment by ajs124** [comment]
What happened to this after the PR was merged upstream?

**Comment by JohnAZoidberg** [comment]
I was going to write some documentation on how the usage is different than upstream, as they expect it to be run from a git clone.
I'll try it out again and make a PR to nixpkgs ASAP.

**Comment by sorokin** [comment]
I tried using this package and got this error message:

```
sh: latex: команда не найдена
Traceback (most recent call last):
  File "/nix/store/z0y0vajvszj398n2i9vz6njzd73fim2i-manim-0.1.10/lib/python3.7/site-packages/manimlib/extract_scene.py", line 150, in main
    scene = SceneClass(**scene_kwargs)
  File "/nix/store/z0y0vajvszj398n2i9vz6njzd73fim2i-manim-0.1.10/lib/python3.7/site-packages/manimlib/scene/scene.py", line 52, in __init__
    self.construct()
  File "1.py", line 20, in construct
    title = TextMobject("This is some \\LaTeX")
  File "/nix/store/z0y0vajvszj398n2i9vz6njzd73fim2i-manim-0.1.10/lib/python3.7/site-packages/manimlib/mobject/svg/tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "/nix/store/z0y0vajvszj398n2i9vz6njzd73fim2i-manim-0.1.10/lib/python3.7/site-packages/manimlib/mobject/svg/tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "/nix/store/z0y0vajvszj398n2i9vz6njzd73fim2i-manim-0.1.10/lib/python3.7/site-packages/manimlib/utils/tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/nix/store/z0y0vajvszj398n2i9vz6njzd73fim2i-manim-0.1.10/lib/python3.7/site-packages/manimlib/utils/tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: Tex/081b5f87a6472151.log
```

Apparently manim tries to execute command latex without specifying absolute path in /nix/store/.../bin/latex.
