### ISSUE TITLE
dropbox-cli: No module named 'gi'

### ISSUE THREAD

**Issue by mnacamura** [NixOS/nixpkgs#60714]
## Issue description

Running `dropbox start -i` fails with message `ModuleNotFoundError: No module named 'gi'`.
https://github.com/NixOS/nixpkgs/pull/59115#issuecomment-488167567

### Steps to reproduce

```
> mv ~/.dropbox-dist ~/.dropbox-dist.bk
> nix-shell -p dropbox-cli --run 'dropbox start -i'
Starting Dropbox...Traceback (most recent call last):
  File "/nix/store/b4k8y53y9lk6avgqbpavm188vqmx1hxs-dropbox-cli-2019.02.14/bin/dropbox", line 1443, in start
    download()
  File "/nix/store/b4k8y53y9lk6avgqbpavm188vqmx1hxs-dropbox-cli-2019.02.14/bin/dropbox", line 294, in download
    import gi
ModuleNotFoundError: No module named 'gi'
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.9, NixOS, 19.09pre177249.dfd8f84aef1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre177249.dfd8f84aef1"`
 - channels(mnacamura): `"nixpkgs-19.09pre177248.ed1b59a98e7"`
 - nixpkgs: `/home/mnacamura/repos/nixpkgs`

**Comment by mnacamura** [comment]
I tried this patch:
```diff
diff --git a/pkgs/applications/networking/dropbox/cli.nix b/pkgs/applications/networking/dropbox/cli.nix
index 73977b82047..6ee1c589e57 100644
--- a/pkgs/applications/networking/dropbox/cli.nix
+++ b/pkgs/applications/networking/dropbox/cli.nix
@@ -1,4 +1,6 @@
-{ stdenv, pkgconfig, fetchurl, python3, dropbox }:
+{ stdenv, pkgconfig, fetchurl, python3, dropbox
+, gobject-introspection, gtk3, wrapGAppsHook
+}:
 let
   version = "2019.02.14";
   dropboxd = "${dropbox}/bin/dropbox";
@@ -11,8 +13,13 @@ stdenv.mkDerivation {
     sha256 = "09yg7q45sycl88l3wq0byz4a9k6sxx3m0r3szinvisfay9wlj35f";
   };
 
-  nativeBuildInputs = [ pkgconfig ];
-  buildInputs = [ python3 ];
+  nativeBuildInputs = [ pkgconfig wrapGAppsHook ];
+
+  buildInputs = [
+    (python3.withPackages (ps: with ps; [ pygobject3 ]))
+    gobject-introspection
+    gtk3
+  ];
 
   phases = "unpackPhase installPhase";
 
@@ -29,6 +36,7 @@ stdenv.mkDerivation {
     sed -i 's:db_path = .*:db_path = "${dropboxd}":' $out/bin/dropbox
     chmod +x "$out/bin/"*
     patchShebangs "$out/bin"
+    wrapGAppsHook
   '';
 
   meta = {
```
Then, it says
```
> nix-shell -p dropbox-cli --run 'dropbox start -i'
Starting Dropbox.../nix/store/7399k04lym3qaza6izlkma3pjpjxqhn6-dropbox-cli-2019.02.14/bin/.dropbox-wrapped:303: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
/nix/store/7399k04lym3qaza6izlkma3pjpjxqhn6-dropbox-cli-2019.02.14/bin/.dropbox-wrapped:453: PyGTKDeprecationWarning: Stock items are deprecated. Please use: Gtk.Button.new_with_mnemonic(label)
  self.ok = ok = Gtk.Button(stock=Gtk.STOCK_OK)
/nix/store/7399k04lym3qaza6izlkma3pjpjxqhn6-dropbox-cli-2019.02.14/bin/.dropbox-wrapped:458: PyGTKDeprecationWarning: Stock items are deprecated. Please use: Gtk.Button.new_with_mnemonic(label)
  cancel = Gtk.Button(stock=Gtk.STOCK_CANCEL)
Traceback (most recent call last):
  File "/nix/store/7399k04lym3qaza6izlkma3pjpjxqhn6-dropbox-cli-2019.02.14/bin/.dropbox-wrapped", line 1443, in start
    download()
  File "/nix/store/7399k04lym3qaza6izlkma3pjpjxqhn6-dropbox-cli-2019.02.14/bin/.dropbox-wrapped", line 526, in download
    dialog = DownloadDialog()
  File "/nix/store/7399k04lym3qaza6izlkma3pjpjxqhn6-dropbox-cli-2019.02.14/bin/.dropbox-wrapped", line 465, in __init__
    self.box_logo = Gtk.Image.new_from_pixbuf(box_logo_pixbuf)
TypeError: argument pixbuf: Expected GdkPixbuf.Pixbuf, but got str
```
It seems that the module is now visible from python but another problem has popped up.

**Comment by jtojnar** [comment]
```python
def load_serialized_images():
    global box_logo_pixbuf, window_icon
    import gi
    gi.require_version('GdkPixbuf', '2.0')
    from gi.repository import GdkPixbuf
    box_logo_pixbuf = "too-lazy-to-fix"
    window_icon = "too-lazy-to-fix"
```

looks like an intentional bug in the program. Try running `dropbox` without `DISPLAY` variable in the environment to trigger the alternative branch.

**Comment by jtojnar** [comment]
Oh, it comes from our packaging.
