### ISSUE TITLE
[19.03] tensorflow-tensorboard requires tensorflow python module to be importable

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#61173]
## Issue description

In the latest 19.03, the new `tensorflow-tensorboard` Nix package exports an executable called `tensorboard`. To run this executable it needs to be able to import `tensorflow`. Otherwise it comes up with an error:

```
Traceback (most recent call last):
  File "/nix/store/4hpsjw1a9yvw2skx5kjjc0kp3lqy57ad-python3.6-tensorflow-tensorboard-1.13.0/bin/.tensorboard-wrapped", line 7, in <module>
    from tensorboard.main import run_main
  File "/nix/store/4hpsjw1a9yvw2skx5kjjc0kp3lqy57ad-python3.6-tensorflow-tensorboard-1.13.0/lib/python3.6/site-packages/tensorboard/main.py", line 42, in <module>
    import tensorflow as tf  # pylint: disable=unused-import
ModuleNotFoundError: No module named 'tensorflow'
```

Now usually I solved this inside `nix-shell` where I just add `tensorflowWithoutCuda` as a `propagatedBuildInput`, and then `tensorboard` works inside the nix-shell.

However if I'm trying build a custom package that calls `tensorboard` via `subprocess.run` in Python, even if my own package has `tensorboardWithoutCuda` in the `propagatedBuildInputs`, this Python package is not added to the PYTHONPATH for the `tensorboard` executable.

### Steps to reproduce

```
{
  pkgs ? import ./pkgs.nix,
  pythonPath ? "python36"
}:
  with pkgs;
  let
    python = lib.getAttrFromPath (lib.splitString "." pythonPath) pkgs;
  in
    python.pkgs.buildPythonApplication rec {
      pname = "tensorboard-dashboard";
      version = "0.0.1";
      src = lib.cleanSourceWith {
        filter = (path: type:
          ! (builtins.any
              (r: (builtins.match r (builtins.baseNameOf path)) != null)
              [
                "pip_packages"
                ".*\.egg-info"
                "\.env"
                "tmp"
                "logs"
              ])
        );
        src = lib.cleanSource ./.;
      };
      nativeBuildInputs = [
        makeWrapper
        python.pkgs.pip
      ];
      propagatedNativeBuildInputs = (with python.pkgs;[
        tensorflow-tensorboard
      ]);
      propagatedBuildInputs = (with python.pkgs; [
        setuptools
        tensorflowWithoutCuda # tensorboard requires tensorflow
      ]);
      # remove this when setuptools becomes compatible with tensorflow's setuptools requirement
      installFlags = [ "--no-deps" ];
    }
```

If you have a `setup.py` that registers this executable:

```
#!/usr/bin/env python3

import subprocess

def main():
    print('Running')
    subprocess.run(['tensorboard', '--help'])
    print('Ran')

if __name__ == '__main__':
    main()
```

**Comment by CMCDragonkai** [comment]
Additionally if I try to override the tensorflow-tensorboard derivation, I end up with really different results:

```
{
  pkgs ? import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/cf3e277dd0bd710af0df667e9364f4bd80c72713.tar.gz) {},
  pythonPath ? "python36"
}:
  with pkgs;
  let
    python = lib.getAttrFromPath (lib.splitString "." pythonPath) pkgs;
  in
    {
      old = python.pkgs.tensorflow-tensorboard;
      new = python.pkgs.tensorflow-tensorboard.overridePythonAttrs (attrs: {
        propagatedBuildInputs = [
          python.pkgs.tensorflowWithoutCuda
        ] ++ attrs.propagatedBuildInputs;
      });
    }
```

Building the `old` produces:

```
/nix/store/4hpsjw1a9yvw2skx5kjjc0kp3lqy57ad-python3.6-tensorflow-tensorboard-1.13.0
├── bin
├── lib
└── nix-support

3 directories, 0 files
```

Building the `new` produces:

```
/nix/store/r8gg7wf3li6kh3nblvd2bvjnb3lgfhbr-python3.6-tensorflow-tensorboard-1.13.0
├── lib
└── nix-support

2 directories, 0 files
```

How can overriding the `propagatedBuildInputs` end up changing whether the `bin` directory exists or not?

**Comment by CMCDragonkai** [comment]
It is possible to get `tensorboard` CLI executable executed by a custom script as long as you use `propagatedBuildInputs` with `python.pkgs.tensorflow`. However if you are able to run it, the `tensorboard` script ends up reporting with:

```
Traceback (most recent call last):
  File "/nix/store/4hpsjw1a9yvw2skx5kjjc0kp3lqy57ad-python3.6-tensorflow-tensorboard-1.13.0/bin/.tensorboard-wrapped", line 7, in <module>
    from tensorboard.main import run_main
  File "/nix/store/4hpsjw1a9yvw2skx5kjjc0kp3lqy57ad-python3.6-tensorflow-tensorboard-1.13.0/lib/python3.6/site-packages/tensorboard/main.py", line 42, in <module>
    import tensorflow as tf  # pylint: disable=unused-import
ModuleNotFoundError: No module named 'tensorflow'
```

This looks like its a bug in the `tensorflow-tensorboard` expression itself. It is a dependency of `tensorflow` expression, but when used transitively, it is not able to find the `tensorflow` Python module.

**Comment by stites** [comment]
I'm currently investigating bumping tensorboard (which is backed-up by bumping protobuf and failing protobuf test suites for anything over 3.x, see #71889) and am not sure this is an issue for more recent versions of tensorboard.

Of note, tensorboard has a [`compat` module](https://github.com/tensorflow/tensorboard/blob/dc71eeea403eb027612422ab6cd3061d4f9a10f3/tensorboard/compat/__init__.py#L15) which is explicitly created to break circular dependencies. Tensorflow does seem to be required, however, for almost all plugins. which are bundled with tensorboard.

I'm fairly invested in how this ticket will turn out. In truth, I'm trying to fix the test suite for pytorch-1.3.0 now that #65041 is merged. Pytorch-1.3.0 has added a tensorboard test suite which I believe requires tensorboard-2.0. Pulling in a transitive tensorflow dependency would be unfortunate overhead.
