### ISSUE TITLE
Jinja2 tests fail

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#61183]
## Issue description

The tests for python27Packages.jinja2 fail and thereby the derivation fails to evaluate.

```
builtins.Failed: [pytest] section in setup.cfg files is no longer supported, change to [tool:pytest] instead.
```
(Full log below)

### Steps to reproduce

I'm crosscompiling an aarch64 sd image with `services.octoprint.enable = true`.

## Technical details

```
building '/nix/store/dmga5m047h3xsi7xi92vki0b96afns1g-python2.7-Jinja2-2.8.1.drv'...
unpacking sources
unpacking source archive /nix/store/iqjlvb13wk3lg5jdsxfkihzvwr3hfdak-Jinja2-2.8.1.tar.gz
source root is Jinja2-2.8.1
setting SOURCE_DATE_EPOCH to timestamp 1483017377 of file Jinja2-2.8.1/setup.cfg
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
building
running bdist_wheel
The [wheel] section is deprecated. Use [bdist_wheel] instead.
running build
running build_py
creating build
creating build/lib
creating build/lib/jinja2
copying jinja2/debug.py -> build/lib/jinja2
copying jinja2/lexer.py -> build/lib/jinja2
copying jinja2/constants.py -> build/lib/jinja2
copying jinja2/meta.py -> build/lib/jinja2
copying jinja2/visitor.py -> build/lib/jinja2
copying jinja2/parser.py -> build/lib/jinja2
copying jinja2/__init__.py -> build/lib/jinja2
copying jinja2/sandbox.py -> build/lib/jinja2
copying jinja2/optimizer.py -> build/lib/jinja2
copying jinja2/_compat.py -> build/lib/jinja2
copying jinja2/ext.py -> build/lib/jinja2
copying jinja2/bccache.py -> build/lib/jinja2
copying jinja2/utils.py -> build/lib/jinja2
copying jinja2/environment.py -> build/lib/jinja2
copying jinja2/exceptions.py -> build/lib/jinja2
copying jinja2/_stringdefs.py -> build/lib/jinja2
copying jinja2/tests.py -> build/lib/jinja2
copying jinja2/defaults.py -> build/lib/jinja2
copying jinja2/compiler.py -> build/lib/jinja2
copying jinja2/runtime.py -> build/lib/jinja2
copying jinja2/loaders.py -> build/lib/jinja2
copying jinja2/filters.py -> build/lib/jinja2
copying jinja2/nodes.py -> build/lib/jinja2
running egg_info
writing requirements to Jinja2.egg-info/requires.txt
writing Jinja2.egg-info/PKG-INFO
writing top-level names to Jinja2.egg-info/top_level.txt
writing dependency_links to Jinja2.egg-info/dependency_links.txt
writing entry points to Jinja2.egg-info/entry_points.txt
reading manifest file 'Jinja2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'run-tests.py'
warning: no files found matching '*' under directory 'custom_fixers'
warning: no files found matching '*' under directory 'jinja2/testsuite/res'
warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
writing manifest file 'Jinja2.egg-info/SOURCES.txt'
installing to build/bdist.linux-aarch64/wheel
running install
running install_lib
creating build/bdist.linux-aarch64
creating build/bdist.linux-aarch64/wheel
creating build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/debug.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/lexer.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/constants.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/meta.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/visitor.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/parser.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/__init__.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/sandbox.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/optimizer.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/_compat.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/ext.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/bccache.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/utils.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/environment.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/exceptions.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/_stringdefs.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/tests.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/defaults.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/compiler.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/runtime.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/loaders.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/filters.py -> build/bdist.linux-aarch64/wheel/jinja2
copying build/lib/jinja2/nodes.py -> build/bdist.linux-aarch64/wheel/jinja2
running install_egg_info
Copying Jinja2.egg-info to build/bdist.linux-aarch64/wheel/Jinja2-2.8.1-py2.7.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
adding license file "AUTHORS" (matched pattern "AUTHORS*")
creating build/bdist.linux-aarch64/wheel/Jinja2-2.8.1.dist-info/WHEEL
creating 'dist/Jinja2-2.8.1-py2.py3-none-any.whl' and adding 'build/bdist.linux-aarch64/wheel' to it
adding 'jinja2/__init__.py'
adding 'jinja2/_compat.py'
adding 'jinja2/_stringdefs.py'
adding 'jinja2/bccache.py'
adding 'jinja2/compiler.py'
adding 'jinja2/constants.py'
adding 'jinja2/debug.py'
adding 'jinja2/defaults.py'
adding 'jinja2/environment.py'
adding 'jinja2/exceptions.py'
adding 'jinja2/ext.py'
adding 'jinja2/filters.py'
adding 'jinja2/lexer.py'
adding 'jinja2/loaders.py'
adding 'jinja2/meta.py'
adding 'jinja2/nodes.py'
adding 'jinja2/optimizer.py'
adding 'jinja2/parser.py'
adding 'jinja2/runtime.py'
adding 'jinja2/sandbox.py'
adding 'jinja2/tests.py'
adding 'jinja2/utils.py'
adding 'jinja2/visitor.py'
adding 'Jinja2-2.8.1.dist-info/AUTHORS'
adding 'Jinja2-2.8.1.dist-info/LICENSE'
adding 'Jinja2-2.8.1.dist-info/METADATA'
adding 'Jinja2-2.8.1.dist-info/WHEEL'
adding 'Jinja2-2.8.1.dist-info/entry_points.txt'
adding 'Jinja2-2.8.1.dist-info/top_level.txt'
adding 'Jinja2-2.8.1.dist-info/RECORD'
removing build/bdist.linux-aarch64/wheel
installing
/build/Jinja2-2.8.1/dist /build/Jinja2-2.8.1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Processing ./Jinja2-2.8.1-py2.py3-none-any.whl
Requirement already satisfied: MarkupSafe in /nix/store/xb8mfbqgq2983fxc40gi3dik2l62zgkl-python2.7-MarkupSafe-1.1.1/lib/python2.7/site-packages (from Jinja2==2.8.1) (1.1.1)
Installing collected packages: Jinja2
Successfully installed Jinja2-2.8.1
/build/Jinja2-2.8.1
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/i2awlcln1mhsglc07srz7nmq615p718i-python2.7-Jinja2-2.8.1
strip is /nix/store/q68bqrywsnamwdjw86f60zxgw26jpw4j-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/i2awlcln1mhsglc07srz7nmq615p718i-python2.7-Jinja2-2.8.1/lib
patching script interpreter paths in /nix/store/i2awlcln1mhsglc07srz7nmq615p718i-python2.7-Jinja2-2.8.1
checking for references to /build/ in /nix/store/i2awlcln1mhsglc07srz7nmq615p718i-python2.7-Jinja2-2.8.1...
running install tests
Traceback (most recent call last):
  File "/nix/store/i33qvbmfsw5zl25zkb88zziwkk16ab1h-python2.7-pytest-4.2.1/bin/.pytest-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/i33qvbmfsw5zl25zkb88zziwkk16ab1h-python2.7-pytest-4.2.1/lib/python2.7/site-packages/_pytest/config/__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "/nix/store/i33qvbmfsw5zl25zkb88zziwkk16ab1h-python2.7-pytest-4.2.1/lib/python2.7/site-packages/_pytest/config/__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/nix/store/2fyagxnljg85hkzxn3x1aa8rwnarpp89-python2.7-pluggy-0.8.1/lib/python2.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/nix/store/2fyagxnljg85hkzxn3x1aa8rwnarpp89-python2.7-pluggy-0.8.1/lib/python2.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/nix/store/2fyagxnljg85hkzxn3x1aa8rwnarpp89-python2.7-pluggy-0.8.1/lib/python2.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/nix/store/2fyagxnljg85hkzxn3x1aa8rwnarpp89-python2.7-pluggy-0.8.1/lib/python2.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/nix/store/i33qvbmfsw5zl25zkb88zziwkk16ab1h-python2.7-pytest-4.2.1/lib/python2.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/nix/store/2fyagxnljg85hkzxn3x1aa8rwnarpp89-python2.7-pluggy-0.8.1/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/nix/store/2fyagxnljg85hkzxn3x1aa8rwnarpp89-python2.7-pluggy-0.8.1/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/nix/store/i33qvbmfsw5zl25zkb88zziwkk16ab1h-python2.7-pytest-4.2.1/lib/python2.7/site-packages/_pytest/config/__init__.py", line 655, in pytest_cmdline_parse
    self.parse(args)
  File "/nix/store/i33qvbmfsw5zl25zkb88zziwkk16ab1h-python2.7-pytest-4.2.1/lib/python2.7/site-packages/_pytest/config/__init__.py", line 841, in parse
    self._preparse(args, addopts=addopts)
  File "/nix/store/i33qvbmfsw5zl25zkb88zziwkk16ab1h-python2.7-pytest-4.2.1/lib/python2.7/site-packages/_pytest/config/__init__.py", line 778, in _preparse
    self._initini(args)
  File "/nix/store/i33qvbmfsw5zl25zkb88zziwkk16ab1h-python2.7-pytest-4.2.1/lib/python2.7/site-packages/_pytest/config/__init__.py", line 709, in _initini
    config=self,
  File "/nix/store/i33qvbmfsw5zl25zkb88zziwkk16ab1h-python2.7-pytest-4.2.1/lib/python2.7/site-packages/_pytest/config/findpaths.py", line 122, in determine_setup
    rootdir, inifile, inicfg = getcfg([ancestor], config=config)
  File "/nix/store/i33qvbmfsw5zl25zkb88zziwkk16ab1h-python2.7-pytest-4.2.1/lib/python2.7/site-packages/_pytest/config/findpaths.py", line 41, in getcfg
    pytrace=False,
  File "/nix/store/i33qvbmfsw5zl25zkb88zziwkk16ab1h-python2.7-pytest-4.2.1/lib/python2.7/site-packages/_pytest/outcomes.py", line 113, in fail
    raise Failed(msg=msg, pytrace=pytrace)
builtins.Failed: [pytest] section in setup.cfg files is no longer supported, change to [tool:pytest] instead.
builder for '/nix/store/dmga5m047h3xsi7xi92vki0b96afns1g-python2.7-Jinja2-2.8.1.drv' failed with exit code 1
cannot build derivation '/nix/store/zf9gv3s367h32qlb5x1rk3nidwrlf0jd-python2.7-Flask-0.10.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/76jxavcmxh9jkdibx898jssf6qg8i7zc-python2.7-Flask-Babel-0.12.2.drv': 1 dependencies couldn't be built
```

I'm crosscompiling aarch64 with nixpkgs 475b4d1d42e72e46c3c829c3290a5f646bb2fc83.

**Comment by mvnetbiz** [comment]
I had the same issue to, this fixes it for me. https://github.com/NixOS/nixpkgs/pull/61407

**Comment by marsam** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/61407
