### ISSUE TITLE
[19.03] Backport cudnn_cudatoolkit_10: 7.3.1 -> 7.4.2 to 19.03 

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#61538]
## Issue description

The 19.03 cudnn is still on 7.3.1. If you use the 19.03 commit and try to use Tensorflow with CUDA, we get an error like:

```
2019-05-15 20:02:32.901988: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-05-15 20:02:33.560815: E tensorflow/stream_executor/cuda/cuda_dnn.cc:324] Loaded runtime CuDNN library: 7.3.1 but source was compiled with: 7.4.2.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2019-05-15 20:02:33.561847: E tensorflow/stream_executor/cuda/cuda_dnn.cc:324] Loaded runtime CuDNN library: 7.3.1 but source was compiled with: 7.4.2.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Traceback (most recent call last):
  File "./bin/test3.py", line 190, in <module>
    results = model.detect(images)
  File "/home/cmcdragonkai/Projects/object-detection/mrcnn/model.py", line 2524, in detect
    self.keras_model.predict([molded_images, image_metas, anchors], verbose=0)
  File "/nix/store/md0540jsdy4hfsdpg9hiplalcw7a27w8-python3.6-Keras-2.2.4/lib/python3.6/site-packages/keras/engine/training.py", line 1169, in predict
    steps=steps)
  File "/nix/store/md0540jsdy4hfsdpg9hiplalcw7a27w8-python3.6-Keras-2.2.4/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "/nix/store/md0540jsdy4hfsdpg9hiplalcw7a27w8-python3.6-Keras-2.2.4/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/nix/store/md0540jsdy4hfsdpg9hiplalcw7a27w8-python3.6-Keras-2.2.4/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/nix/store/r3d7jxawph0qdi0g1hdwrgf2hddfv13d-python3.6-tensorflow-1.13.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/nix/store/r3d7jxawph0qdi0g1hdwrgf2hddfv13d-python3.6-tensorflow-1.13.1/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv1/convolution}}]]
         [[{{node mrcnn_detection/map/TensorArrayUnstack/range}}]]
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.42, Matrix Central, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`
```

**Comment by marsam** [comment]
Closing because 19.03 has reached end of support
