### ISSUE TITLE
pkgsStatic.talloc fails to build

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#62540]
## Issue description

So today I tried to build `proot` on unstable as described in the [nix install guide](https://nixos.wiki/wiki/Nix_Installation_Guide). This fails on the dependency `talloc`.

@symphorien Thanks for your information in that guide! I tried to build `proot` according to the guide on `unstable` and (with slight modifications for compatibility) on `19-03` they both fail in `talloc` at this point. Do you have any insights as to how you managed to get it to build? e.g. a nixpkgs commit?

```
~> nix-build -I nixpkgs=channel:nixos-unstable -E '(import <nixpkgs>{}).pkgsStatic.talloc'
these derivations will be built:
  /nix/store/8z9a0nky395slqk08x62jw0myrn5d2zf-talloc-2.1.14-x86_64-unknown-linux-musl.drv
building '/nix/store/8z9a0nky395slqk08x62jw0myrn5d2zf-talloc-2.1.14-x86_64-unknown-linux-musl.drv'...
unpacking sources
unpacking source archive /nix/store/vhibvjl3g3rgi9hl0ik068w70gsv02bq-talloc-2.1.14.tar.gz
source root is talloc-2.1.14
setting SOURCE_DATE_EPOCH to timestamp 1531374876 of file talloc-2.1.14/wscript
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
configure flags: --cross-compile --cross-execute=/nix/store/x0mlaj4z4ciycaycfwc36l1932mwywfj-bash-4.4-p23/bin/bash\ -c\ \'\'\ -- --prefix=/nix/store/3nkxychr5q7k9y3ndy3xagy4aby82jfb-talloc-2.1.14-x86_64-unknown-linux-musl --enable-talloc-compat1 --bundled-libraries=NONE --builtin-libraries=replace configure
Checking for program gcc or cc           : x86_64-unknown-linux-musl-gcc
Checking for program cpp                 : not found
Checking for program ar                  : x86_64-unknown-linux-musl-ar
Checking for program ranlib              : x86_64-unknown-linux-musl-ranlib
Checking for gcc                         : ok
Checking for program git                 : not found
Check for -MD                            : yes
Checking for program gdb                 : not found
Checking for header sys/utsname.h        : yes
Checking uname sysname type              : Traceback (most recent call last):
  File "buildtools/bin/waf", line 76, in <module>
    Scripting.prepare(t, cwd, VERSION, wafdir)
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Scripting.py", line 145, in prepare
    prepare_impl(t, cwd, ver, wafdir)
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Scripting.py", line 135, in prepare_impl
    main()
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Scripting.py", line 188, in main
    fun(ctx)
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Scripting.py", line 241, in configure
    conf.sub_config([''])
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Configure.py", line 237, in sub_config
    self.recurse(k, name='configure')
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Utils.py", line 656, in recurse
    f(self)
  File "/build/talloc-2.1.14/wscript", line 38, in configure
    conf.RECURSE('lib/replace')
  File "./buildtools/wafsamba/samba_utils.py", line 452, in RECURSE
    return ctx.sub_config(relpath)
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Configure.py", line 237, in sub_config
    self.recurse(k, name='configure')
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Utils.py", line 656, in recurse
    f(self)
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Utils.py", line 743, in wrap
    ret = fun(k)
  File "/build/talloc-2.1.14/lib/replace/wscript", line 28, in configure
    conf.RECURSE('buildtools/wafsamba')
  File "./buildtools/wafsamba/samba_utils.py", line 452, in RECURSE
    return ctx.sub_config(relpath)
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Configure.py", line 237, in sub_config
    self.recurse(k, name='configure')
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Utils.py", line 656, in recurse
    f(self)
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Utils.py", line 743, in wrap
    ret = fun(k)
  File "/build/talloc-2.1.14/lib/replace/../../buildtools/wafsamba/wscript", line 317, in configure
    conf.CHECK_UNAME()
  File "./buildtools/wafsamba/samba_conftests.py", line 452, in CHECK_UNAME
    msg="Checking uname %s type" % v):
  File "./buildtools/wafsamba/samba_autoconf.py", line 456, in CHECK_CODE
    conf.COMPOUND_END(conf.env[define])
  File "./buildtools/wafsamba/samba_autoconf.py", line 69, in COMPOUND_END
    p(result)
  File "/build/talloc-2.1.14/third_party/waf/wafadmin/Configure.py", line 299, in check_message_2
    self.log.write(sr)
TypeError: expected a string or other character buffer object
builder for '/nix/store/8z9a0nky395slqk08x62jw0myrn5d2zf-talloc-2.1.14-x86_64-unknown-linux-musl.drv' failed with exit code 1
error: build of '/nix/store/8z9a0nky395slqk08x62jw0myrn5d2zf-talloc-2.1.14-x86_64-unknown-linux-musl.drv' failed
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.45, NixOS, 19.03.172783.a0b7a7913c4 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172783.a0b7a7913c4"`
 - channels(maralorn): `"unstable-19.09pre180832.c7bcd4277cc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by matthewbauer** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/62618
