### ISSUE TITLE
syncthing-gtk fails to start (ValueError: Namespace Notify not available)

### ISSUE THREAD

**Issue by reanimus** [NixOS/nixpkgs#62747]
## Issue description
Syncthing-GTK fails to launch entirely due to an issue importing a dependency. When run, the app outputs an error to the console:

```
Traceback (most recent call last):
  File "/nix/store/grwbfwsjhrihl34cfv4xfd1bz3hkjbnr-syncthing-gtk-0.9.4/bin/..syncthing-gtk-wrapped-wrapped", line 38, in <module>
    from syncthing_gtk.app import App
  File "/nix/store/grwbfwsjhrihl34cfv4xfd1bz3hkjbnr-syncthing-gtk-0.9.4/lib/python2.7/site-packages/syncthing_gtk/app.py", line 17, in <module>
    from syncthing_gtk.notifications import Notifications, HAS_DESKTOP_NOTIFY
  File "/nix/store/grwbfwsjhrihl34cfv4xfd1bz3hkjbnr-syncthing-gtk-0.9.4/lib/python2.7/site-packages/syncthing_gtk/notifications.py", line 19, in <module>
    gi.require_version('Notify', '0.7')
  File "/nix/store/b4xz3qddhvy1jw9jjavrgj5vsanhiljn-python2.7-pygobject-3.30.4/lib/python2.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

### Steps to reproduce
1. Run `syncthing-gtk`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.47, NixOS, 19.03.172801.1a27474d474 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(animus): `""`
 - channels(root): `"nixos-19.03.172801.1a27474d474"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by hedning** [comment]
Right, that's a consequence of #56943. Setting `strictDeps = false;` to the derivation should fix it.

**Comment by glittershark** [comment]
this is still important to me

**Comment by jtojnar** [comment]
I cannot reproduce this any more, libnotify is added to `GI_TYPELIB_PATH` by the wrapper:

```
/nix/store/0lfpnvv38s1sb4daqfsva183w4xpdl66-gtk+3-3.24.20/lib/girepository-1.0
/nix/store/6rxanvhn8hyvbj30jcxl0yfsv3cs6h37-librsvg-2.48.4/lib/girepository-1.0
/nix/store/gc0q6wbniz1znf3m4bdl80i194q7v4q3-gobject-introspection-1.64.1/lib/girepository-1.0
/nix/store/ja85v8i7345cydqa69zsy1xglvxdb898-pango-1.44.7/lib/girepository-1.0
/nix/store/v88zn7n1505aabi9baxixmnnzyrxs9x7-gdk-pixbuf-2.40.0/lib/girepository-1.0
/nix/store/vgg099k0pkn80h8qh8pk7vznz3jkbw7p-atk-2.36.0/lib/girepository-1.0
/nix/store/9pq1zn8q4r89g4h4rfgf1psxhkbg0bml-libnotify-0.7.9/lib/girepository-1.0
```

If I disable `strictDeps`:

```patch
diff --git a/pkgs/applications/networking/syncthing-gtk/default.nix b/pkgs/applications/networking/syncthing-gtk/default.nix
index cf1e053dd53..76d2b7a380e 100644
--- a/pkgs/applications/networking/syncthing-gtk/default.nix
+++ b/pkgs/applications/networking/syncthing-gtk/default.nix
@@ -33,6 +33,8 @@ buildPythonApplication rec {
     dateutil pyinotify pygobject3 bcrypt
   ];
 
+  strictDeps = false; # https://github.com/NixOS/nixpkgs/issues/56943
+
   patches = [
     (substituteAll {
       src = ./paths.patch;
```

Some extra paths are added but they do not seem to be necessary:

```
/nix/store/knj16f2s51s87ma61gzfm5ycrjfsq11k-gsettings-desktop-schemas-3.36.1/lib/girepository-1.0
/nix/store/310hfxmvmai7xravkpg5zj6pa433acni-libdbusmenu-gtk3-16.04.0/lib/girepository-1.0
/nix/store/lkm8lm653xlq11xfsc1gqj9iq2aqkb1r-libappindicator-gtk3-12.10.0/lib/girepository-1.0
/nix/store/0lfpnvv38s1sb4daqfsva183w4xpdl66-gtk+3-3.24.20/lib/girepository-1.0
/nix/store/6rxanvhn8hyvbj30jcxl0yfsv3cs6h37-librsvg-2.48.4/lib/girepository-1.0
/nix/store/gc0q6wbniz1znf3m4bdl80i194q7v4q3-gobject-introspection-1.64.1/lib/girepository-1.0
/nix/store/ja85v8i7345cydqa69zsy1xglvxdb898-pango-1.44.7/lib/girepository-1.0
/nix/store/v88zn7n1505aabi9baxixmnnzyrxs9x7-gdk-pixbuf-2.40.0/lib/girepository-1.0
/nix/store/vgg099k0pkn80h8qh8pk7vznz3jkbw7p-atk-2.36.0/lib/girepository-1.0
/nix/store/9pq1zn8q4r89g4h4rfgf1psxhkbg0bml-libnotify-0.7.9/lib/girepository-1.0
/nix/store/knj16f2s51s87ma61gzfm5ycrjfsq11k-gsettings-desktop-schemas-3.36.1/lib/girepository-1.0
/nix/store/310hfxmvmai7xravkpg5zj6pa433acni-libdbusmenu-gtk3-16.04.0/lib/girepository-1.0
/nix/store/lkm8lm653xlq11xfsc1gqj9iq2aqkb1r-libappindicator-gtk3-12.10.0/lib/girepository-1.0
/nix/store/0lfpnvv38s1sb4daqfsva183w4xpdl66-gtk+3-3.24.20/lib/girepository-1.0
/nix/store/6rxanvhn8hyvbj30jcxl0yfsv3cs6h37-librsvg-2.48.4/lib/girepository-1.0
/nix/store/gc0q6wbniz1znf3m4bdl80i194q7v4q3-gobject-introspection-1.64.1/lib/girepository-1.0
/nix/store/ja85v8i7345cydqa69zsy1xglvxdb898-pango-1.44.7/lib/girepository-1.0
/nix/store/v88zn7n1505aabi9baxixmnnzyrxs9x7-gdk-pixbuf-2.40.0/lib/girepository-1.0
/nix/store/vgg099k0pkn80h8qh8pk7vznz3jkbw7p-atk-2.36.0/lib/girepository-1.0
/nix/store/9pq1zn8q4r89g4h4rfgf1psxhkbg0bml-libnotify-0.7.9/lib/girepository-1.0
/nix/store/knj16f2s51s87ma61gzfm5ycrjfsq11k-gsettings-desktop-schemas-3.36.1/lib/girepository-1.0
/nix/store/310hfxmvmai7xravkpg5zj6pa433acni-libdbusmenu-gtk3-16.04.0/lib/girepository-1.0
/nix/store/lkm8lm653xlq11xfsc1gqj9iq2aqkb1r-libappindicator-gtk3-12.10.0/lib/girepository-1.0
```

**Comment by jtojnar** [comment]
This was likely fixed and syncthing-gtk is broken anyway.
