### ISSUE TITLE
Emacs Lucid segfaults when making a window

### ISSUE THREAD

**Issue by Warbo** [NixOS/nixpkgs#62778]
## Issue description

I use the Lucid build of Emacs, due to the long-standing X-reconnecting bug in GTK. I do this with `emacs.override { withGTK2 = false; withGTK3 = false; }` and this has been working fine for years.

After upgrading to NixOS 19.03 I can no longer run Emacs graphically, since it segfaults when trying to create a window. I can use `emacs -nw` to run the console version, and that's fine. I'm currently pinning the version from 18.09, since that works fine.

### Steps to reproduce

I can reproduce the crash with the following command, running in an Xorg display (I also tried it in Xvfb and it crashes there too):

```
$ nix-shell -p gdb -p '(emacs.override { withGTK2 = false; withGTK3 = false; })' --run 'gdb emacs'
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "i686-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from emacs...
warning: Loadable section ".dynstr" outside of ELF segments
(no debugging symbols found)...done.
(gdb) run
Starting program: /nix/store/kmpm8r6r2pyv3ikshi84gwk360bw6djg-emacs-26.1/bin/emacs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/sjsvwd9sqxjflmslnf8xs48aqpkb2sjy-glibc-2.27/lib/libthread_db.so.1".
[New Thread 0xb58b2b40 (LWP 20885)]

(process:20765): GLib-GIO-CRITICAL **: 16:52:09.947: g_settings_schema_source_lookup: assertion 'source != NULL' failed

Thread 1 "emacs" received signal SIGSEGV, Segmentation fault.
0xb7be923a in XrmPermStringToQuark ()
   from /nix/store/40j5z6dyc75ibgmagm50r1mb2v9yaykh-libX11-1.6.7/lib/libX11.so.6
(gdb) backtrace
#0  0xb7be923a in XrmPermStringToQuark ()
   from /nix/store/40j5z6dyc75ibgmagm50r1mb2v9yaykh-libX11-1.6.7/lib/libX11.so.6
#1  0xb7d79344 in _XtCompileResourceList ()
   from /nix/store/b7nm37ln9cycd6dr3skf6lr1blsvcadc-libXt-1.1.5/lib/libXt.so.6
#2  0xb7d75017 in ObjectClassPartInitialize ()
   from /nix/store/b7nm37ln9cycd6dr3skf6lr1blsvcadc-libXt-1.1.5/lib/libXt.so.6
#3  0xb7d61b59 in CallClassPartInit.isra.0 ()
   from /nix/store/b7nm37ln9cycd6dr3skf6lr1blsvcadc-libXt-1.1.5/lib/libXt.so.6
#4  0xb7d61b72 in CallClassPartInit.isra.0 ()
   from /nix/store/b7nm37ln9cycd6dr3skf6lr1blsvcadc-libXt-1.1.5/lib/libXt.so.6
#5  0xb7d61b72 in CallClassPartInit.isra.0 ()
   from /nix/store/b7nm37ln9cycd6dr3skf6lr1blsvcadc-libXt-1.1.5/lib/libXt.so.6
#6  0xb7d61b72 in CallClassPartInit.isra.0 ()
   from /nix/store/b7nm37ln9cycd6dr3skf6lr1blsvcadc-libXt-1.1.5/lib/libXt.so.6
#7  0xb7d61b72 in CallClassPartInit.isra.0 ()
   from /nix/store/b7nm37ln9cycd6dr3skf6lr1blsvcadc-libXt-1.1.5/lib/libXt.so.6
#8  0xb7d61d75 in XtInitializeWidgetClass ()
   from /nix/store/b7nm37ln9cycd6dr3skf6lr1blsvcadc-libXt-1.1.5/lib/libXt.so.6
#9  0xb7d627d1 in _XtCreateWidget ()
   from /nix/store/b7nm37ln9cycd6dr3skf6lr1blsvcadc-libXt-1.1.5/lib/libXt.so.6
#10 0xb7d62a2a in XtCreateWidget ()
   from /nix/store/b7nm37ln9cycd6dr3skf6lr1blsvcadc-libXt-1.1.5/lib/libXt.so.6
#11 0x081194fa in x_window ()
#12 0x0811a6c6 in Fx_create_frame ()
#13 0x081a4624 in Ffuncall ()
#14 0x081dff30 in exec_byte_code ()
#15 0x081a6c7e in funcall_lambda ()
#16 0x081a459c in Ffuncall ()
#17 0x081dff30 in exec_byte_code ()
#18 0x081a6c7e in funcall_lambda ()
#19 0x081a459c in Ffuncall ()
#20 0x081a636c in Fapply ()
#21 0x081a4624 in Ffuncall ()
#22 0x081dff30 in exec_byte_code ()
#23 0x081a6c7e in funcall_lambda ()
#24 0x081a459c in Ffuncall ()
#25 0x081dff30 in exec_byte_code ()
#26 0x081a6c7e in funcall_lambda ()
#27 0x081a459c in Ffuncall ()
#28 0x081dff30 in exec_byte_code ()
#29 0x081a6c7e in funcall_lambda ()
#30 0x081a459c in Ffuncall ()
#31 0x081dff30 in exec_byte_code ()
#32 0x081a6c7e in funcall_lambda ()
#33 0x081a459c in Ffuncall ()
#34 0x081dff30 in exec_byte_code ()
#35 0x081a6c7e in funcall_lambda ()
#36 0x081a70b9 in apply_lambda ()
#37 0x081a6717 in eval_sub ()
#38 0x081a8681 in Feval ()
#39 0x0812ed72 in top_level_2 ()
#40 0x081a37cc in internal_condition_case ()
#41 0x08130223 in top_level_1 ()
#42 0x081a3716 in internal_catch ()
#43 0x0812eca4 in command_loop ()
#44 0x081320a9 in recursive_edit_1 ()
#45 0x081323f4 in Frecursive_edit ()
#46 0x08059905 in main ()
```

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"i686-linux"`
 - host os: `Linux 4.9.52, NixOS, 19.03.172786.606306e0eaa (Koi)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172786.606306e0eaa"`
 - channels(chris): `"nixos-17.09.2875.c2b668ee726"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by Atemu** [comment]
When I still used Lucid earlier this year, multiple windows were working for me.
