### ISSUE TITLE
pytorch-1.1.0

### ISSUE THREAD

**Issue by juliendehos** [NixOS/nixpkgs#63073]
Hi,
I'm trying to build pytorch-1.1.0 on NixOS 19.03 and unstable but it fails. Any idea ?

nix config: https://github.com/juliendehos/nixpkgs/commit/db04f3e9269251e4979ce230beddfb3abe27450c

full log: https://gist.github.com/juliendehos/25653c6286001007e52ebbed466fbfab

partial log:
```
Building wheel torch-1.1.0
-- Building version 1.1.0
['cmake',
 '-DBUILDING_WITH_TORCH_LIBS=ON',
 '-DBUILD_BINARY=False',
 '-DBUILD_CAFFE2_OPS=True',
 '-DBUILD_PYTHON=True',
 '-DBUILD_SHARED_LIBS=ON',
 '-DBUILD_TEST=True',
 '-DBUILD_TORCH=ON',
 '-DCAFFE2_STATIC_LINK_CUDA=False',
 '-DCMAKE_BUILD_TYPE=Release',
 '-DCMAKE_CXX_FLAGS= ',
 '-DCMAKE_C_FLAGS= ',
 '-DCMAKE_EXE_LINKER_FLAGS=',
 '-DCMAKE_INSTALL_PREFIX=/build/source/torch',
 '-DCMAKE_PREFIX_PATH=/nix/store/7yw89ki05nsw4kz05hqnqccnk6m3wpam-openblas-0.3.6:/nix/store/ars3pcklw0gan1hvjz9a07bgysfjb66v-numactl-2.0.12:/nix/store/szxc9q0vbzfixbgmwwb99dasf1j8065x-python3.7-bootstrapped-pip-19.0.3:/nix/store/wvwmzd5ab015276vvnif907aqgjnc80l-python3.7-cffi-1.12.3-dev:/nix/store/pyx1bq09y1bdhwili4anwgcizvmyj51j-libffi-3.2.1-dev:/nix/store/kwl4klw1a0mqgarxqa8bq25kf7i6c5k9-libffi-3.2.1:/nix/store/js4lkkp5725vd0nasrqj8vdc5qx3c7zn-python3.7-pycparser-2.19:/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3:/nix/store/zhhnxn9np7ly8gdycldvkdkzc7sgkjrq-python3.7-setuptools-41.0.1:/nix/store/zhhnxn9np7ly8gdycldvkdkzc7sgkjrq-python3.7-setuptools-41.0.1:/nix/store/x7qqhwj2jx30bvcy0lif47wa97kfzqgb-python3.7-cffi-1.12.3:/nix/store/gch9w32080lpnxixcabmwnl1gdrkz6n3-python3.7-numpy-1.16.3:/nix/store/z4rbwzhmws8ds2dca4diwvncw0qf4113-python3.7-PyYAML-5.1',
 '-DCMAKE_SHARED_LINKER_FLAGS=',
 '-DINSTALL_TEST=True',
 '-DNCCL_EXTERNAL=False',
 '-DNUMPY_INCLUDE_DIR=/nix/store/gch9w32080lpnxixcabmwnl1gdrkz6n3-python3.7-numpy-1.16.3/lib/python3.7/site-packages/numpy/core/include',
 '-DONNX_ML=False',
 '-DONNX_NAMESPACE=onnx_torch',
 '-DPYTHON_EXECUTABLE=/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3/bin/python3.7',
 '-DPYTHON_INCLUDE_DIR=/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3/include/python3.7m',
 '-DPYTHON_LIBRARY=/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3/lib/libpython3.7m.so.1.0',
 '-DTHD_SO_VERSION=1',
 '-DTORCH_BUILD_VERSION=1.1.0',
 '-DUSE_CUDA=False',
 '-DUSE_DISTRIBUTED=True',
 '-DUSE_FBGEMM=True',
 '-DUSE_FFMPEG=False',
 '-DUSE_LEVELDB=False',
 '-DUSE_LMDB=False',
 '-DUSE_MKLDNN=True',
 '-DUSE_NCCL=False',
 '-DUSE_NNPACK=True',
 '-DUSE_NUMPY=True',
 '-DUSE_OPENCV=False',
 '-DUSE_QNNPACK=True',
 '-DUSE_ROCM=False',
 '-DUSE_SYSTEM_EIGEN_INSTALL=OFF',
 '-DUSE_SYSTEM_NCCL=False',
 '-DUSE_TENSORRT=False',
 '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON',
 '/build/source']
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 725, in <module>
    build_deps()
  File "setup.py", line 285, in build_deps
    build_dir='build')
  File "/build/source/tools/build_pytorch_libs.py", line 259, in build_caffe2
    my_env)
  File "/build/source/tools/build_pytorch_libs.py", line 239, in run_cmake
    check_call(cmake_args, cwd=build_dir, env=my_env)
  File "/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DBUILDING_WITH_TORCH_LIBS=ON', '-DBUILD_BINARY=False', '-DBUILD_CAFFE2_OPS=True', '-DBUILD_PYTHON=True', '-DBUILD_SHARED_LIBS=ON', '-DBUILD_TEST=True', '-DBUILD_TORCH=ON', '-DCAFFE2_STATIC_LINK_CUDA=False', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_FLAGS= ', '-DCMAKE_C_FLAGS= ', '-DCMAKE_EXE_LINKER_FLAGS=', '-DCMAKE_INSTALL_PREFIX=/build/source/torch', '-DCMAKE_PREFIX_PATH=/nix/store/7yw89ki05nsw4kz05hqnqccnk6m3wpam-openblas-0.3.6:/nix/store/ars3pcklw0gan1hvjz9a07bgysfjb66v-numactl-2.0.12:/nix/store/szxc9q0vbzfixbgmwwb99dasf1j8065x-python3.7-bootstrapped-pip-19.0.3:/nix/store/wvwmzd5ab015276vvnif907aqgjnc80l-python3.7-cffi-1.12.3-dev:/nix/store/pyx1bq09y1bdhwili4anwgcizvmyj51j-libffi-3.2.1-dev:/nix/store/kwl4klw1a0mqgarxqa8bq25kf7i6c5k9-libffi-3.2.1:/nix/store/js4lkkp5725vd0nasrqj8vdc5qx3c7zn-python3.7-pycparser-2.19:/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3:/nix/store/zhhnxn9np7ly8gdycldvkdkzc7sgkjrq-python3.7-setuptools-41.0.1:/nix/store/zhhnxn9np7ly8gdycldvkdkzc7sgkjrq-python3.7-setuptools-41.0.1:/nix/store/x7qqhwj2jx30bvcy0lif47wa97kfzqgb-python3.7-cffi-1.12.3:/nix/store/gch9w32080lpnxixcabmwnl1gdrkz6n3-python3.7-numpy-1.16.3:/nix/store/z4rbwzhmws8ds2dca4diwvncw0qf4113-python3.7-PyYAML-5.1', '-DCMAKE_SHARED_LINKER_FLAGS=', '-DINSTALL_TEST=True', '-DNCCL_EXTERNAL=False', '-DNUMPY_INCLUDE_DIR=/nix/store/gch9w32080lpnxixcabmwnl1gdrkz6n3-python3.7-numpy-1.16.3/lib/python3.7/site-packages/numpy/core/include', '-DONNX_ML=False', '-DONNX_NAMESPACE=onnx_torch', '-DPYTHON_EXECUTABLE=/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3/bin/python3.7', '-DPYTHON_INCLUDE_DIR=/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3/include/python3.7m', '-DPYTHON_LIBRARY=/nix/store/4w1rxv6wfkv728jzmm6pqq3jsqd4yvi7-python3-3.7.3/lib/libpython3.7m.so.1.0', '-DTHD_SO_VERSION=1', '-DTORCH_BUILD_VERSION=1.1.0', '-DUSE_CUDA=False', '-DUSE_DISTRIBUTED=True', '-DUSE_FBGEMM=True', '-DUSE_FFMPEG=False', '-DUSE_LEVELDB=False', '-DUSE_LMDB=False', '-DUSE_MKLDNN=True', '-DUSE_NCCL=False', '-DUSE_NNPACK=True', '-DUSE_NUMPY=True', '-DUSE_OPENCV=False', '-DUSE_QNNPACK=True', '-DUSE_ROCM=False', '-DUSE_SYSTEM_EIGEN_INSTALL=OFF', '-DUSE_SYSTEM_NCCL=False', '-DUSE_TENSORRT=False', '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON', '/build/source']' returned non-zero exit status 1.
builder for '/nix/store/0j949x31b7fg26m8kbqar4ynl54qq5b1-python3.7-pytorch-1.1.0.drv' failed with exit code 1
error: build of '/nix/store/0j949x31b7fg26m8kbqar4ynl54qq5b1-python3.7-pytorch-1.1.0.drv' failed
```

**Comment by juliendehos** [comment]
pytorch seems to build using commit 556af7c19db90465703a9acc0b437cbcfb018ee0
https://github.com/juliendehos/nixpkgs/commit/470166a4bd13fd16426852c996401b8c6cfce3b9

**Comment by tbenst** [comment]
@juliendehos there’s a few problems.
- https://github.com/NixOS/nixpkgs/pull/61347
- https://github.com/NixOS/nixpkgs/issues/61728
- https://github.com/NixOS/nixpkgs/issues/61820

I can’t work on this for a bit but hopefully this will help set you in the right direction

**Comment by stites** [comment]
I have built pytorch-1.1 and passed all testing but sidestepped a few features. Things I've added:
- For expediency, I've disabled FBGEMM (I believe GEMM will simply get substituted with a different library). I tried to work with your WIP @tbenst, but I couldn't get cmake to read source environment variables. I also tried to drop down to just building dependencies, but ran into some issues where cmake couldn't find a googlebench VERSION variable.
- I've had to bump magma to magma-2.4.0 (but not 2.5.0) with cuda-10 -- cuda-9 throws out some undefined reference errors.
- I added mkl support (with an `mklSupport ? false`), but mkl doesn't seem to play nice with CUDA. I've confirmed that mkl + mkldnn works without cuda, but this all needs to be disabled (explicitly with USE_MKLDNN=0) when adding cuda support.

Most unfortunate: I've had to disable multi-gpu (nccl) and distributed libraries (gloo, I think, with `USE_DISTRIBUTED=0` -- this was a paranoia move) -- so pytorch is single-gpu only : ( I view this as a huge loss and could use some help patching this up.

---

The error I could use help with is when building the nccl_external dependency. It's a little hard to figure out the root cause since the cmake logs are asynchrnous (It was a multi-hour build), but I've noticed that there are a large number of undefined reference errors like the following:
```
nvlink error   : Undefined reference to '_Z24ncclReduceTreeLL_sum_f32P14CollectiveArgs' in '/build/source/build/nccl/obj/collectives/device/functions.o' (target: sm_30)
```
@jpy, @akamaus, @thoughtpolice I've read #46032 a few times -- would you have any pointers here with respect to these build errors? I am using `pkgs.nccl_cudatoolkit_10` (ie, I'm using cuda 10) and I was thinking that, perhaps, nccl deps need to be merged or stubbed in the same way that cudnn and cudatoolkit are -- does that sound about right? I would imagine the tensorflow package does the same sort of thing.

Also, an aside, is there a lighter-weight way to build projects like this? My successful build took just under two hours and I'm pretty sure the multi-gpu and (maybe) distributed build errors happen around 1h30m.

I'll submit a PR soon.

**Comment by tbenst** [comment]
@stites glad to hear of the progress :). Let me know when you submit the pull request--I'm happy to put another pair of eyes on multi-gpu and FBGEMM (do you clone sub-sub-dependencies like amsjit due to #61820?). Also, for magma, did you try my version of 2.5 here: https://github.com/NixOS/nixpkgs/pull/61347/files ?

**Comment by stites** [comment]
ran into a little infrastructure hitch, so I'm a little delayed. PR's ETA will be tomorrow.

@tbenst: I did not see your magma PR, very cool! As someone who has run into issues with magma, I would ask that you turn `magma/default.nix` into a `magma/generic.nix` and export the last two or three magma version, but perhaps this 2.5 derivation will work out of the box.

RE: FBGEMM -- I actually tried to build this directly from https://github.com/pytorch/FBGEMM with the commit you referenced in https://gist.github.com/tbenst/15495f97ffe2a71dc18c49e247af8f51 This way there is no `setup.py` intermediary. I may have also tried the asmjit `fetchFromGitHub` bit from that gist. Unfortunately, I decided it was more than a day's worth of work figuring out how nix interacts with cmake, so I opted to punt. Specifically, I was unable to get `export ASMJIT_SRC_DIR=${amsjit}/src` to be understood by cmake.
