### ISSUE TITLE
python package xgboost: libxgboost.so, 6: image not found?

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nixpkgs#63094]
## Issue description

i can use numpy package to enter the repl, but it failed with xgboost.
even i add system library dependecy in default.nix, it still fail with "image not found"
in fact, it's dylib format on my mac os
```
larrys-MBP:tmp larluo$ ls -l /nix/store/nxvar5633zkqfkg23mkd5f27pp2avsl9-xgboost-0.72/lib/
total 4120
-r-xr-xr-x  1 larluo  wheel  2106704 Jan  1  1970 libxgboost.dylib
```

### Steps to reproduce
```
nix-shell -p python37Packages.numpy --run "python3"
nix-shell -p python37Packages.xgboost --run "python3"

larrys-MBP:tmp larluo$ cat default.nix 
with import <nixpkgs> {}; 
with python37Packages;

buildPythonPackage rec {
  name = "larluo";
  src = ./. ;

  buildInputs = [ pkgs.xgboost ];
  propagatedBuildInputs = [ xgboost  ];

}

nix-shell
```

the log:
```
adding 'xgboost-0.72.dist-info/METADATA'                                                                                                                          
adding 'xgboost-0.72.dist-info/WHEEL'                                                                                                                             
adding 'xgboost-0.72.dist-info/top_level.txt'                                                                                                                     
adding 'xgboost-0.72.dist-info/RECORD'                                                                                                                            
removing build/bdist.macosx-10.6-x86_64/wheel                                                                                                                     
installing                                                                                                                                                        
/private/var/folders/_3/80s5534109d2j83cfgtwjcjc0000gn/T/nix-build-python3.7-xgboost-0.72.drv-0/xgboost/python-package/dist /private/var/folders/_3/80s5534109d2j8
3cfgtwjcjc0000gn/T/nix-build-python3.7-xgboost-0.72.drv-0/xgboost/python-package                                                                                  
Processing ./xgboost-0.72-py3-none-any.whl                                                                                                                        
Requirement already satisfied: scipy in /nix/store/mhgmmg0bb3q8b37l7p2qfhfcrsw8kw89-python3.7-scipy-1.2.1/lib/python3.7/site-packages (from xgboost==0.72) (1.2.1$
Requirement already satisfied: numpy in /nix/store/6xh6gincdymys2wkzl2mwgf0742njad2-python3.7-numpy-1.16.2/lib/python3.7/site-packages (from xgboost==0.72) (1.16$
2)                                                                                                                                                                
Installing collected packages: xgboost                                                                                                                            
Successfully installed xgboost-0.72                                                                                                                               
/private/var/folders/_3/80s5534109d2j83cfgtwjcjc0000gn/T/nix-build-python3.7-xgboost-0.72.drv-0/xgboost/python-package                                            
post-installation fixup                                                                                                                                           
strip is /nix/store/xcvvrjbck0n51603nnkyba3dszmhndi0-cctools-binutils-darwin/bin/strip                                                                            
stripping (with command strip and flags -S) in /nix/store/kfr460zka09dh3va1xkpyijqx9q7859k-python3.7-xgboost-0.72/lib                                             
patching script interpreter paths in /nix/store/kfr460zka09dh3va1xkpyijqx9q7859k-python3.7-xgboost-0.72                                                           
/nix/store/kfr460zka09dh3va1xkpyijqx9q7859k-python3.7-xgboost-0.72/lib/python3.7/site-packages/xgboost/build-python.sh: interpreter directive changed from "/bin/s
h" to "/nix/store/yvw6l7vm91jnm2rb3ypzp563vnlns30s-bash-4.4-p23/bin/sh"                                                                                           

...
...
/nix/store/kfr460zka09dh3va1xkpyijqx9q7859k-python3.7-xgboost-0.72/lib/python3.7/site-packages/xgboost/rabit/test/local_recover.py: interpreter directiv[496/1883]
from "/usr/bin/python" to "/nix/store/8kzdflq0v06fq0mh9m2fd73gnyqp57xr-python3-3.7.3/bin/python"
running install tests
EEEEEEEEEEEEEE
======================================================================
ERROR: Failure: OSError (dlopen(/nix/store/nxvar5633zkqfkg23mkd5f27pp2avsl9-xgboost-0.72/lib/libxgboost.so, 6): image not found)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/d5b785bkqal1vnfbv8scjqqizfcgk5wj-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/nix/store/d5b785bkqal1vnfbv8scjqqizfcgk5wj-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/nix/store/d5b785bkqal1vnfbv8scjqqizfcgk5wj-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/nix/store/d5b785bkqal1vnfbv8scjqqizfcgk5wj-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/nix/store/8kzdflq0v06fq0mh9m2fd73gnyqp57xr-python3-3.7.3/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/nix/store/8kzdflq0v06fq0mh9m2fd73gnyqp57xr-python3-3.7.3/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/private/var/folders/_3/80s5534109d2j83cfgtwjcjc0000gn/T/nix-build-python3.7-xgboost-0.72.drv-0/xgboost/tests/python/test_basic.py", line 3, in <module>
    import xgboost as xgb
  File "/private/var/folders/_3/80s5534109d2j83cfgtwjcjc0000gn/T/nix-build-python3.7-xgboost-0.72.drv-0/xgboost/python-package/xgboost/__init__.py", line 11, in <
module>
    from .core import DMatrix, Booster
  File "/private/var/folders/_3/80s5534109d2j83cfgtwjcjc0000gn/T/nix-build-python3.7-xgboost-0.72.drv-0/xgboost/python-package/xgboost/core.py", line 115, in <mod
ule>
    _LIB = _load_lib()
  File "/private/var/folders/_3/80s5534109d2j83cfgtwjcjc0000gn/T/nix-build-python3.7-xgboost-0.72.drv-0/xgboost/python-package/xgboost/core.py", line 109, in _loa
d_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/nix/store/8kzdflq0v06fq0mh9m2fd73gnyqp57xr-python3-3.7.3/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/nix/store/8kzdflq0v06fq0mh9m2fd73gnyqp57xr-python3-3.7.3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/nix/store/nxvar5633zkqfkg23mkd5f27pp2avsl9-xgboost-0.72/lib/libxgboost.so, 6): image not found
```

## Technical details
```
larrys-MBP:tmp larluo$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/qdgab1z17d2pff5ipzrlhhmhcpv8zyrr-nix-info
  /nix/store/w6j2wz4dkb2ma2v64ramg0z7nngisi2r-DarwinTools-1
copying path '/nix/store/w6j2wz4dkb2ma2v64ramg0z7nngisi2r-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/qdgab1z17d2pff5ipzrlhhmhcpv8zyrr-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.0.0, macOS 10.12`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(larluo): `"nixpkgs-19.09pre178484.8bc70c937b3"`
 - nixpkgs: `/Users/larluo/.nix-defexpr/channels/nixpkgs`
```

**Comment by bcdarwin** [comment]
Closed in  #122234.
