### ISSUE TITLE
xpra faults on startup

### ISSUE THREAD

**Issue by ornxk** [NixOS/nixpkgs#63631]
## Issue description
xpra version 2.5 as of commit d77e3bd661354ea775a8cacc97bb59ddde513c09 (the commit that marked xpra as not broken) fails to start, giving a type error. The latest commit failed to build at all.

This happens after I loaded the uinput module with modprobe, and set its device node to be owned by my user.

```
$ Entering daemon mode; any further errors will be reported to:
  /run/user/1000/xpra/:100.log
$ cat /run/user/1000/xpra/:100.log
xpra main error:
Traceback (most recent call last):
  File "/nix/store/1lms1r8fqjxsdziqmshv0mp2r7ir410x-xpra-2.5/lib/python3.7/site-packages/xpra/scripts/main.py", line 93, in main
    return run_mode(script_file, err, options, args, mode, defaults)
  File "/nix/store/1lms1r8fqjxsdziqmshv0mp2r7ir410x-xpra-2.5/lib/python3.7/site-packages/xpra/scripts/main.py", line 421, in run_mode
    return run_server(error_cb, options, mode, script_file, args, current_display)
  File "/nix/store/1lms1r8fqjxsdziqmshv0mp2r7ir410x-xpra-2.5/lib/python3.7/site-packages/xpra/scripts/server.py", line 617, in run_server
    return do_run_server(error_cb, opts, mode, xpra_file, extra_args, desktop_display)
  File "/nix/store/1lms1r8fqjxsdziqmshv0mp2r7ir410x-xpra-2.5/lib/python3.7/site-packages/xpra/scripts/server.py", line 895, in do_run_server
    uinput_uuid = get_rand_chars(UINPUT_UUID_LEN)
  File "/nix/store/1lms1r8fqjxsdziqmshv0mp2r7ir410x-xpra-2.5/lib/python3.7/site-packages/xpra/os_util.py", line 219, in get_rand_chars
    return b"".join(chars[random.randint(0, len(chars)-1)] for _ in range(l))
TypeError: sequence item 0: expected a bytes-like object, int found
```

## Technical details
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.41, NixOS, 19.03.172883.1601f559e89 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(marisa): `"nixos-19.03.172883.1601f559e89, nixos-unstable-19.09pre182743.7815c86c104, nixpkgs-unstable-19.09pre182717.b58ada326aa"`
 - channels(alice): `"nixos-19.03.172883.1601f559e89"`
 - channels(root): `"nixos-19.03.172883.1601f559e89, unstable-19.09pre179307.bc94dcf5002"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by offlinehacker** [comment]
Does this error still persists?

**Comment by samueldr** [comment]
Closing, as with #87985, it is assumed this issue should be fixed.

If *this particular issue* is not fixed, feel free to reopen. For another problem, open a new issue, and CC the relevant people working on better Xpra support (see #86164).

Thanks!
