### ISSUE TITLE
BPF Compiler Collection package broken

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#63924]
## Issue description
None of the tools from `linuxPackages.bcc` seem to actually work

### Steps to reproduce

```
[arian@t490s:~]$ nix run nixpkgs.linuxPackages.bcc

[arian@t490s:~]$ biolatency 
chdir(/nix/store/5ldvscyj0ms5a730s88r52qx0h1wsgvm-linux-4.19.50-dev/lib/modules/4.19.55/build): No such file or directory
Traceback (most recent call last):
  File "/nix/store/dld56xqsg19njqs8sb4zliz59xy2v0lb-bcc-0.8.0/share/bcc/tools/.biolatency-wrapped", line 116, in <module>
    b = BPF(text=bpf_text)
  File "/nix/store/dld56xqsg19njqs8sb4zliz59xy2v0lb-bcc-0.8.0/lib/python3.7/site-packages/bcc/__init__.py", line 320, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text

[arian@t490s:~]$ tcpconnect 
chdir(/nix/store/5ldvscyj0ms5a730s88r52qx0h1wsgvm-linux-4.19.50-dev/lib/modules/4.19.55/build): No such file or directory
Traceback (most recent call last):
  File "/nix/store/dld56xqsg19njqs8sb4zliz59xy2v0lb-bcc-0.8.0/share/bcc/tools/.tcpconnect-wrapped", line 248, in <module>
    b = BPF(text=bpf_text)
  File "/nix/store/dld56xqsg19njqs8sb4zliz59xy2v0lb-bcc-0.8.0/lib/python3.7/site-packages/bcc/__init__.py", line 320, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text


```

## Technical details
Nixos 19.03

**Comment by arianvp** [comment]
Seems fixed:

```
$ biolatency 
could not open bpf map: start, error: Operation not permitted
Traceback (most recent call last):
  File "/nix/store/kapsi074mf66vg8231z0258aa9is0k4j-bcc-0.12.0/share/bcc/tools/.biolatency-wrapped", line 135, in <module>
    b = BPF(text=bpf_text)
  File "/nix/store/kapsi074mf66vg8231z0258aa9is0k4j-bcc-0.12.0/lib/python3.7/site-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
$ sudo biolatency
[sudo] password for arian: 
Tracing block device I/O... Hit Ctrl-C to end.
^C
     usecs               : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 0        |                                        |
         8 -> 15         : 0        |                                        |
        16 -> 31         : 7        |****************************            |
        32 -> 63         : 4        |****************                        |
        64 -> 127        : 2        |********                                |
       128 -> 255        : 0        |                                        |
       256 -> 511        : 0        |                                        |
       512 -> 1023       : 10       |****************************************|
      1024 -> 2047       : 0        |                                        |
      2048 -> 4095       : 1        |****                                    |
      4096 -> 8191       : 0        |                                        |
      8192 -> 16383      : 1        |****                                    |

```
