### ISSUE TITLE
virt-manager now completely broken: GtkSource not available

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#64970]
## Issue description

Nothing seems to work in virt-manager. I can't open connection details, or details about a domain.

If I try this: `virt-manager --show-domain-editor some_vm_name --connect 'qemu:///system'`
then I get:

```
Namespace GtkSource not available

Traceback (most recent call last):
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/engine.py", line 36, in newfn
    return fn(self, *args, **kwargs)
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/engine.py", line 518, in _launch_cli_window
    self._cli_show_vm_helper(uri, clistr, show_window)
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/engine.py", line 480, in _cli_show_vm_helper
    from .vmwindow import vmmVMWindow
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/vmwindow.py", line 15, in <module>
    from .details.details import vmmDetails
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/details/details.py", line 18, in <module>
    from ..addhardware import vmmAddHardware
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/addhardware.py", line 23, in <module>
    from .device.fsdetails import vmmFSDetails
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/device/fsdetails.py", line 14, in <module>
    from ..storagebrowse import vmmStorageBrowser
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/storagebrowse.py", line 11, in <module>
    from .hoststorage import vmmHostStorage
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/hoststorage.py", line 17, in <module>
    from .createpool import vmmCreatePool
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/createpool.py", line 18, in <module>
    from .xmleditor import vmmXMLEditor
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/xmleditor.py", line 6, in <module>
    gi.require_version('GtkSource', '4')
  File "/nix/store/lkgx00g07rcwn8pj4hk2v3ywhvhvl0if-python3.7-pygobject-3.32.1/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by colemickens** [comment]
fixed by: https://github.com/NixOS/nixpkgs/pull/64627/commits
