### ISSUE TITLE
virt-manager: "ValueError: Namespace GtkSource not available"

### ISSUE THREAD

**Issue by jchv** [NixOS/nixpkgs#65209]
## Issue description
When attempting to open the detail view for a VM in virt-manager 2.2.0, nothing happens. In the terminal, the following output is observed:

```
Traceback (most recent call last):
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/manager.py", line 489, in row_activated
    self.show_vm(_src)
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/manager.py", line 474, in show_vm
    vmmenu.VMActionUI.show(self, self.current_vm())
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/vmmenu.py", line 329, in show
    from .vmwindow import vmmVMWindow
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/vmwindow.py", line 15, in <module>
    from .details.details import vmmDetails
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/details/details.py", line 18, in <module>
    from ..addhardware import vmmAddHardware
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/addhardware.py", line 23, in <module>
    from .device.fsdetails import vmmFSDetails
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/device/fsdetails.py", line 14, in <module>
    from ..storagebrowse import vmmStorageBrowser
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/storagebrowse.py", line 11, in <module>
    from .hoststorage import vmmHostStorage
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/hoststorage.py", line 17, in <module>
    from .createpool import vmmCreatePool
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/createpool.py", line 18, in <module>
    from .xmleditor import vmmXMLEditor
  File "/nix/store/lns9955rnrzg4lhq1f314imik62706a4-virt-manager-2.2.0/share/virt-manager/virtManager/xmleditor.py", line 6, in <module>
    gi.require_version('GtkSource', '4')
  File "/nix/store/lkgx00g07rcwn8pj4hk2v3ywhvhvl0if-python3.7-pygobject-3.32.1/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
```

Some information about this on the web suggests it is missing a dependency on gtksourceview4. (Attempting to install it in the local nix-env did not change things, probably for good reasons.)

### Steps to reproduce

1. Install `virt-manager` 2.2.0.

2. Try to open a VM window by double clicking on a VM.

(virt-manager 2.1.0 still works.)

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.58, NixOS, 19.09pre185259.362be9608c3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre185259.362be9608c3"`
 - channels(john): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jchv** [comment]
Whoops. This one's already fixed, but I guess nixos-unstable has just fallen behind a bit.
