### ISSUE TITLE
bazel-watcher is broken on Darwin

### ISSUE THREAD

**Issue by kalbasit** [NixOS/nixpkgs#65268]
**Describe the bug**

`bazel-watcher` is not building on Darwin.

**To Reproduce**
1. `nix-build -A bazel-watcher`

**Expected behavior**
Bazel watcher correctly built.

**Additional context**

`bazel-watcher` was broken by 4dad0ae560708fee5d081c3f02bf94e4c6f4dfce. cc @guibou @Profpatsch @abbradar.

<details>
<summary>Build log</summary>

```console
unpacking sources
unpacking source archive /nix/store/6waa28r78jwaarcbwh14vd2i8lzgrnhl-source
source root is source
patching sources
applying patch /nix/store/jh9xn6gchwxn479l63aqrhgv3cr43n4n-use-go-in-path.patch
patching file WORKSPACE
applying patch /nix/store/c2nssk695bl2scdfvb0idrna2w12298k-686130f50cea274f7453f6abc8c5249654047462.patch
patching file WORKSPACE
applying patch /nix/store/fn6v9qklx9pbz974868pws1dhjkx7qfi-18bdb44832ccc533e0ab3923ef80060eeb24582d.patch
patching file WORKSPACE
configuring
no configure script, doing nothing
building
patching script interpreter paths in .
./release/release.sh: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/d9wxsyxsj3ssjcbywwm35254d14yv87a-bash-4.4-p23/bin/bash"
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
Analyzing: target //ibazel:ibazel (1 packages loaded, 0 targets configured)
Analyzing: target //ibazel:ibazel (50 packages loaded, 6806 targets configured)
Analyzing: target //ibazel:ibazel (53 packages loaded, 7648 targets configured)
INFO: Analyzed target //ibazel:ibazel (53 packages loaded, 7784 targets configured).
INFO: Found 1 target...
[0 / 53] [Prepa] Writing file external/go_sdk/packages.txt [for host] ... (3 actions, 0 running)
INFO: From Executing genrule @net_zlib//:copy_public_headers [for host]:
/nix/store/9a77gahrjfv86qj3d396j1jm6ypvyhac-bash/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.ISO-8859-1): No such file or directory
INFO: From Executing genrule @com_google_protobuf//:_internal_wkt_protos_genrule:
/nix/store/9a77gahrjfv86qj3d396j1jm6ypvyhac-bash/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.ISO-8859-1): No such file or directory
[10 / 278] [Scann] Compiling external/net_zlib/uncompr.c [for host] ... (2 actions, 0 running)
ERROR: /private/var/folders/ck/ht80_l5d4c9_tnwmd5lqsxj40000gn/T/nix-build-bazel-watcher-0.10.3.drv-0/output/external/com_google_protobuf/BUILD:388:1: C++ compilation of rule '@com_google_protobuf//:protoc' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 38 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/nix/store/9a77gahrjfv86qj3d396j1jm6ypvyhac-bash/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.ISO-8859-1): No such file or directory
/nix/store/d9wxsyxsj3ssjcbywwm35254d14yv87a-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.ISO-8859-1): No such file or directory
In file included from external/com_google_protobuf/src/google/protobuf/compiler/main.cc:33:
external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_generator.h:40:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
Target //ibazel:ibazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /private/var/folders/ck/ht80_l5d4c9_tnwmd5lqsxj40000gn/T/nix-build-bazel-watcher-0.10.3.drv-0/source/ibazel/BUILD:17:1 C++ compilation of rule '@com_google_protobuf//:protoc' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 38 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 7.600s, Critical Path: 0.24s
INFO: 2 processes: 2 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
builder for '/nix/store/cayv9fpjg09kr5i9mmriyd7nhdscn0dq-bazel-watcher-0.10.3.drv' failed with exit code 1
error: build of '/nix/store/cayv9fpjg09kr5i9mmriyd7nhdscn0dq-bazel-watcher-0.10.3.drv' failed
```
</details>

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.6.0, macOS 10.14.5`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(yl): `"darwin, nixpkgs-19.09pre185256.5b8b5a694c7"`
 - nixpkgs: `/run/current-system/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: bazel-watcher
```

**Comment by Profpatsch** [comment]
Didn’t we put a reverse test on that into bazel?

**Comment by kalbasit** [comment]
It was never merged. #63645.

**Comment by Profpatsch** [comment]
> It was never merged. #63645.

Good grief, you are right.

**Comment by Profpatsch** [comment]
I fixed up https://github.com/NixOS/nixpkgs/pull/63645, but the package is still failing on it. PTAL

**Comment by kalbasit** [comment]
On second attempt, it's actually 4dad0ae560708fee5d081c3f02bf94e4c6f4dfce that broke and not 950da6263f7f861246ac284e45f51ff0073e9d8d. I've updated the description of the issue.

**Comment by booninite** [comment]
This is still broken for me on bazel-watcher-0.13.1 on OSX.  I tried enabling sandboxing per the linked PR and the build fails due to inability to bind to IPv4 and IPv6 localhosts:

```
building '/nix/store/va8x85zd32pnz0h6jkvwsyi0s0r2fkcg-bazel-watcher-0.13.1.drv'...
unpacking sources
unpacking source archive /nix/store/1dw90hj9j41w9rkbblljs7xwwn70g113-source
source root is source
patching sources
applying patch /nix/store/jh9xn6gchwxn479l63aqrhgv3cr43n4n-use-go-in-path.patch
patching file WORKSPACE
Hunk #1 succeeded at 72 (offset 11 lines).
configuring
no configure script, doing nothing
building
patching script interpreter paths in .
./release/release.sh: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/smimdn17mp2ih6nfxwl78mswwdkmcm56-bash-4.4-p23/bin/bash"
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Reading 'startup' options from /nix/store/aqxyciipajhj3ywq25icvbs8km693drb-bazel-rc: --server_javabase=/nix/store/n4xi57vd657v40mmmga8wp9vcp91xv9q-zulu11.2.3-jdk11.0.1
Server crashed during startup. Now printing /private/var/folders/ks/xncg97q12j9gszw89d6cr9140000gn/T/nix-build-bazel-watcher-0.13.1.drv-0/output/server/jvm.out
gRPC server failed to bind to IPv4 and IPv6 localhosts on port 0: [IPv4] Failed to bind
[IPv6] Failed to bind
com.google.devtools.build.lib.util.AbruptExitException: gRPC server failed to bind to IPv4 and IPv6 localhosts on port 0: [IPv4] Failed to bind
[IPv6] Failed to bind
        at com.google.devtools.build.lib.server.GrpcServerImpl.serve(GrpcServerImpl.java:467)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:1077)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:769)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:84)
Caused by: java.io.IOException: Failed to bind
        at io.grpc.netty.NettyServer.start(NettyServer.java:251)
        at io.grpc.internal.ServerImpl.start(ServerImpl.java:177)
        at io.grpc.internal.ServerImpl.start(ServerImpl.java:85)
        at com.google.devtools.build.lib.server.GrpcServerImpl.serve(GrpcServerImpl.java:464)
        ... 3 more
Caused by: java.net.SocketException: Operation not permitted
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:461)
        at java.base/sun.nio.ch.Net.bind(Net.java:453)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:130)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:563)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:488)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:473)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
builder for '/nix/store/va8x85zd32pnz0h6jkvwsyi0s0r2fkcg-bazel-watcher-0.13.1.drv' failed with exit code 37
error: build of '/nix/store/1hf1pb3anv45h3k3d0pgsyclmxdnd6yy-vscode-1.49.3.drv', '/nix/store/va8x85zd32pnz0h6jkvwsyi0s0r2fkcg-bazel-watcher-0.13.1.drv' failed
```
