### ISSUE TITLE
rustracer: fails to compile

### ISSUE THREAD

**Issue by matthias-t** [NixOS/nixpkgs#65554]
**Describe the bug**
`rustracer` fails to compile because of test failures

<details><summary>Log tail</summary>

```
---- completes_methods_for_global_enum stdout ----
thread 'completes_methods_for_global_enum' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', tests/system.rs:182:5

---- let_then_try_with_struct stdout ----
thread 'let_then_try_with_struct' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `0`', tests/system.rs:3441:5

---- let_try stdout ----
thread 'let_try' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21

---- try_operator stdout ----
thread 'try_operator' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21

---- try_operator_struct stdout ----
thread 'try_operator_struct' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `0`', tests/system.rs:3410:5


failures:
    completes_for_let_if_let
    completes_for_match_type_inference_let_expr
    completes_for_match_type_inference_let_expr_with_block
    completes_for_match_type_inference_let_expr_with_return
    completes_for_match_type_inference_with_if
    completes_methods_after_raw_string
    completes_methods_for_global_enum
    let_then_try_with_struct
    let_try
    try_operator
    try_operator_struct

test result: FAILED. 171 passed; 11 failed; 5 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test system'
builder for '/nix/store/pi2r0hpvdmxv9b7pg960z6vfz6dw90mp-racer-2.0.14.drv' failed with exit code 101
```

</details>

**To Reproduce**
```console
$ nix-build -A rustracer
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.2, NixOS, 19.09 (Loris)`
 - multi-user?: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173193.112f522d48c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- rustracer

# a list of nixos modules affected by the problem
module:
```

**Comment by arcnmx** [comment]
Yeah I looked into it recently, it seems like it just hasn't been touched in ages since it started requiring nightly rust - most derivations that depend on racer (like say rls) just pull it in via crates.io instead. I didn't bother to throw a pr together because it had a few tests that seemed to be failing, but if it helps: #65596

**Comment by matthias-t** [comment]
thanks!
