### ISSUE TITLE
services/unifi: unifi crashes immediately on aarch64 (Raspberry Pi)

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#66005]
**Describe the bug**
Unifi service starts then crashes on Raspberry Pi

**To Reproduce**
```
  services.unifi = {
    enable = true;
    unifiPackage = pkgs.unifiStable;
    openPorts = true;
  };
```
Here is the tail of the java exceptions the service throws:

```
Aug 04 19:17:20 rpi java[1106]: Caused by: java.io.FileNotFoundException: /var/lib/unifi/data/db/version (No such file or directory)
Aug 04 19:17:20 rpi java[1106]:         at java.io.FileOutputStream.open0(Native Method)
Aug 04 19:17:20 rpi java[1106]:         at java.io.FileOutputStream.open(FileOutputStream.java:270)
Aug 04 19:17:20 rpi java[1106]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
Aug 04 19:17:20 rpi java[1106]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
Aug 04 19:17:20 rpi java[1106]:         at java.io.FileWriter.<init>(FileWriter.java:90)
Aug 04 19:17:20 rpi java[1106]:         at com.ubnt.service.new.OOoo.afterPropertiesSet(Unknown Source)
Aug 04 19:17:20 rpi java[1106]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(Abstra$
Aug 04 19:17:20 rpi java[1106]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractA$
Aug 04 19:17:20 rpi java[1106]:         ... 61 more
Aug 04 19:17:20 rpi systemd[1]: unifi.service: Main process exited, code=exited, status=1/FAILURE
Aug 04 19:17:20 rpi systemd[1]: unifi.service: Failed with result 'exit-code'.
```
So it looks like the database is missing. 

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```
 - system: `"aarch64-linux"`
 - host os: `Linux 5.2.5, NixOS, 19.09pre187507.525eaf407d4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre187507.525eaf407d4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: unifi-controller
# a list of nixos modules affected by the problem
module: unifi
```

**Comment by WilliButz** [comment]
Should be fixed by #66073, thank you for reporting this :+1:
