### ISSUE TITLE
nodePackages: browserify is broken

### ISSUE THREAD

**Issue by manpages** [NixOS/nixpkgs#6618]
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'xtend'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/nix/store/8hg1lg6b1fwamfx65vbi8v7wl5a8b453-bin-module-deps-3.7.1/lib/node_modules/m
odule-deps/index.js:13:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

In module-deps project.

**Comment by manpages** [comment]
``npm install`` works correctly —

```
└── module-deps@3.7.2 (xtend@4.0.0, minimist@0.2.0, subarg@0.0.1, through2@0.4.2, stream-combiner2@1.0.2, JSONStream@0.7.4, detective@4.0.0)
```

**Comment by offlinehacker** [comment]
This should work from current master, you seem to have old nixpkgs

**Comment by offlinehacker** [comment]
Yup, i tested it in nixpkgs master and it works.

**Comment by manpages** [comment]
I am very sorry.

**Comment by offlinehacker** [comment]
Don't be, nodePackages are still kinda experimental ;)
