### ISSUE TITLE
Can't build bazel on non-NixOS

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#66311]
**Describe the bug**
I am trying to install tensorflow (nixpkgs-unstable) which depends on bazel. I am on RHEL7. It looks like bazel is not in the binary cache so nix starts building it and fails:

```
...
[1,797 / 1,797] checking cached actions
INFO: Build completed successfully, 1797 total actions
INFO: Build completed successfully, 1797 total actions
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
DEBUG: /opt/revr/tmp/nix-build-bazel-0.28.0.drv-0/bazel_keln5Uso/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /opt/revr/tmp/nix-build-bazel-0.28.0.drv-0/bazel_keln5Uso/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5: Make sure that you are running at least Bazel 0.17.1.

Build successful! Binary is here: /opt/revr/tmp/nix-build-bazel-0.28.0.drv-0/bazel_src/output/bazel
FATAL: $USER is not set, and unable to look up name of current user: (error: 0): Success
builder for '/nix/store/lklxx2jnrx3ad7h78ic18vda66p17g7w-bazel-0.28.0.drv' failed with exit code 36
```

**To Reproduce**

0. RedHat Enterprise Linux 7.4
1. nix-env -iA nixpkgs.bazel

**Additional context**
The inability to determine current user points to LDAP/SSSD on RedHat. Why would the build process for bazel need to query the user's info? bazel is the only package that experiences this issue.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-693.33.1.el7.x86_64, Red Hat Enterprise Linux Server, 7.4 (Maipo)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(nixadm): `"nixpkgs-19.09pre187222.002b853782e"`
 - nixpkgs: `/u/nixadm/.nix-defexpr/channels_nixadm/nixpkgs`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
bazel
```

**Comment by FRidh** [comment]
Please enable the sandbox for building and try again.

**Comment by alexvorobiev** [comment]
I can't use the sandboxed builds (I believe it has something to do with user namespaces being disabled due to an RH Enterprise security policy I can do nothing about):

```
installing 'bazel-0.28.0'
these derivations will be built:
  /nix/store/lklxx2jnrx3ad7h78ic18vda66p17g7w-bazel-0.28.0.drv
error: cloning builder process: Invalid argument
error: unable to start build process
```
As I mentioned no other package from nixpkgs I installed (a lot) has this problem on my system. On the other hand I am not customizing bazel in any way so the binary cache would solve the issue for me. Is there a way to diagnose why it is not available for bazel?

**Comment by veprbl** [comment]
Here on RHEL6-like (without LDAP or such) I get a bit further into the build:
```
...
[1,797 / 1,797] checking cached actions
INFO: Build completed successfully, 1797 total actions
INFO: Build completed successfully, 1797 total actions
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
DEBUG: /tmp/veprbl/nix-build-bazel-0.28.0.drv-0/bazel_5uxAfaU7/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /tmp/veprbl/nix-build-bazel-0.28.0.drv-0/bazel_5uxAfaU7/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5: Make sure that you are running at least Bazel 0.17.1.

Build successful! Binary is here: /tmp/veprbl/nix-build-bazel-0.28.0.drv-0/bazel_src/output/bazel
WARNING: failed to get resource limit 7: Function not implemented
WARNING: failed to get resource limit 6: Function not implemented
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
installing
post-installation fixup
patching script interpreter paths in /nix/store/gfjwdkkdfq0c5vvgbx4kmsh48bk4qz2h-bazel-0.28.0
checking for references to /tmp/veprbl/nix-build-bazel-0.28.0.drv-0/ in /nix/store/gfjwdkkdfq0c5vvgbx4kmsh48bk4qz2h-bazel-0.28.0...
running install tests
$TEST_TMPDIR defined: output root default is '/tmp/veprbl/nix-build-bazel-0.28.0.drv-0' and max_idle_secs default is '15'.
WARNING: failed to get resource limit 7: Function not implemented
WARNING: failed to get resource limit 6: Function not implemented
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Server crashed during startup. Now printing /tmp/veprbl/nix-build-bazel-0.28.0.drv-0/_bazel_veprbl/3dcbaef91c45d8a67978b731bb174c0b/server/jvm.out
library initialization failed - unable to get max # of allocated fds
builder for '/nix/store/vn3iql98l0hv32aj6zc5hqb164h5xy2h-bazel-0.28.0.drv' failed with exit code 37
```

@alexvorobiev What happens if you set USER attribute in the bazel derivation?

**Comment by alexvorobiev** [comment]
@veprbl Your suggestion actually helped - I created an overlay to add USER attribute to bazel derivation and it succeeded. But now it looks like any derivation that wants to use this new bazel (in my case tensorflow-gpu) seems to want this attribute as well. Is there any way to make it global or to make bazel remember it?

**Comment by alexvorobiev** [comment]
Now getting this error trying to build tensorflow-gpu:
```
patching sources
applying patch /nix/store/gaw6r3fclx1icvfmyndbxcvk8dbj3hgs-no-saved-proto.patch
patching file tensorflow/cc/saved_model/BUILD
Hunk #1 succeeded at 50 (offset 1 line).
applying patch /nix/store/wjksbxyzb9lwlsm3aziqvjsvvwnaafd3-system-jsoncpp.patch
patching file third_party/systemlibs/jsoncpp.BUILD
applying patch /nix/store/5kxyvwnxy0s2hi6i9fq34ghmhpah0d7d-fix-compile-with-cuda-and-mpi.patch
patching file tensorflow/contrib/mpi_collectives/kernels/ring.cu.cc
applying patch /nix/store/bszqhrxv1yig2b4rayn6rrpp875kxxjj-bazel-0.27.patch
patching file configure.py
Hunk #1 succeeded at 234 (offset -2 lines).
configuring
patching script interpreter paths in configure
configure: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/xfghy8ixrhz3kyy6p724iv3cxji088dx-bash-4.4-p23/bin/bash"
FATAL: $USER is not set, and unable to look up name of current user: (error: 0): Success
Traceback (most recent call last):
  File "./configure.py", line 1573, in <module>
    main()
  File "./configure.py", line 1388, in main
    current_bazel_version = check_bazel_version('0.24.1', '0.25.2')
  File "./configure.py", line 471, in check_bazel_version
    ['bazel', '--batch', '--bazelrc=/dev/null', 'version'])
  File "./configure.py", line 154, in run_shell
    output = subprocess.check_output(cmd)
  File "/nix/store/w7gsq8v86hni4ynaqgwwlnlny115ylng-python3-3.7.4/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/nix/store/w7gsq8v86hni4ynaqgwwlnlny115ylng-python3-3.7.4/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 36.
builder for '/nix/store/yf7322sa4wxhy976q46n044wsnkdxgpw-tensorflow-gpu-1.14.0-deps.drv' failed with exit code 1
cannot build derivation '/nix/store/86w677irmamj65hncqj9sq49yzvs6zs4-tensorflow-gpu-1.14.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/in6n033r0myhczclkk0vhbjlxvb2akz3-python3.7-tensorflow-gpu-1.14.0.drv': 1 dependencies couldn't be built
```
```

**Comment by veprbl** [comment]
@alexvorobiev You can patch bazel to always return "nobody":
https://github.com/bazelbuild/bazel/blob/d1b344a826e02a8bc38033a6ff2e02a5d359625f/src/main/cpp/blaze_util_posix.cc#L704-L715

**Comment by alexvorobiev** [comment]
I gave up and installed tensorflow-bin which has everything pre-built. I wish I had found it earlier...

**Comment by Profpatsch** [comment]
I think building this without nix sandboxing enabled is a lost battle. Thanks for trying, though.

**Comment by veprbl** [comment]
@alexvorobiev If your analysis is correct then bazel should be broken for you even if you install it without nix (as long as you unset $USER). Perhaps this should be reported upstream so that bazel would handle this case more gracefully? If you want a solution with a nix overlay such that propagates into the other builds, then, I think, you could try adding a setupHook to bazel derivation, in that script you could set $USER.

**Comment by veprbl** [comment]
This should be fixed by #74538

**Comment by alexvorobiev** [comment]
@veprbl I don't see any effects of that PR. I still got this error trying to build tensorflow with the latest unstable channel. I tried to add the setupHook to tensorflow but it didn't help either:

```
self: super: rec {
  python37 = super.python37.override {
    packageOverrides = python-self: python-super: rec {

       tensorflow   = (python-super.tensorflow_1.override {
          sse42Support = true;
          avx2Support = true;
          fmaSupport = true;
          mklSupport = true;

      }).overrideAttrs (oldAtttrs: rec {
          setupHook = super.writeText "setuphook.sh" ''
            export USER=myuserid
          '';
      });
    };
  };
}
```

**Comment by veprbl** [comment]
@alexvorobiev The `setupHook` is executed only for reverse dependencies of a derivation. So, if you set it, you need to set it for `bazel` and not `pythonPackages.tensorflow`.

**Comment by alexvorobiev** [comment]
Adding the `setupHook` to `bazel_0_29` resulted in successful build of `tensorflow_2`. Thanks!
