### ISSUE TITLE
Spotify segfaults on launch

### ISSUE THREAD

**Issue by rileyinman** [NixOS/nixpkgs#66408]
When I try to run Spotify I get a blank window for a second then Spotify segfaults. Apparently this isn't related to #55048 based on what I was told there so I figured I should open an issue! Let me know if there's any more info I can give that will help figure this out.

**To Reproduce**
1. `nix-shell -p spotify`
2. `spotify`
3. Observe crash

**Expected behavior**
Spotify should open and run without errors.

**Additional context**
<details>
<summary>Coredump backtrace</summary>

```
[nix-shell:~]$ coredumpctl gdb 9626
           PID: 9626 (.spotify-wrappe)
           UID: 1000 (riley)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Thu 2019-08-08 19:44:39 EDT (1min 9s ago)
  Command Line: /nix/store/rz6p57mr8qg3m7j93wcb972vpdj7ccg1-spotify-1.0.96.181.gf6bc1b6b-12/share/spotify/.spotify-wrapped
    Executable: /nix/store/rz6p57mr8qg3m7j93wcb972vpdj7ccg1-spotify-1.0.96.181.gf6bc1b6b-12/share/spotify/.spotify-wrapped
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (riley)
       Boot ID: 72b70e56ccdb4e13a62e502eeed0c096
    Machine ID: 82240612c9de45ec8e28a61059221a64
      Hostname: carbide
       Storage: /var/lib/systemd/coredump/core.\x2espotify-wrappe.1000.72b70e56ccdb4e13a62e502eeed0c096.9626.1565307879000000.lz4
       Message: Process 9626 (.spotify-wrappe) of user 1000 dumped core.

GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /nix/store/rz6p57mr8qg3m7j93wcb972vpdj7ccg1-spotify-1.0.96.181.gf6bc1b6b-12/share/spotify/.spotify-wrapped...
warning: Loadable section ".dynstr" outside of ELF segments
(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 9645]
[New LWP 9628]
[New LWP 9648]
[New LWP 9641]
[New LWP 9653]
[New LWP 9637]
[New LWP 9632]
[New LWP 9639]
[New LWP 9685]
[New LWP 9643]
[New LWP 9631]
[New LWP 9638]
[New LWP 9686]
[New LWP 9640]
[New LWP 9649]
[New LWP 9646]
[New LWP 9633]
[New LWP 9650]
[New LWP 9651]
[New LWP 9652]
[New LWP 9658]
[New LWP 9680]
[New LWP 9681]
[New LWP 9683]
[New LWP 9635]
[New LWP 9644]
[New LWP 9647]
[New LWP 9684]
[New LWP 9687]
[New LWP 9634]
[New LWP 9636]
[New LWP 9626]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libthread_db.so.1".
Core was generated by `/nix/store/rz6p57mr8qg3m7j93wcb972vpd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7f0c457fa700 (LWP 9645))]
warning: File "/nix/store/hlnxw4k6931bachvg5sv0cyaissimswb-gcc-7.4.0-lib/lib/libstdc++.so.6.0.24-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /nix/store/hlnxw4k6931bachvg5sv0cyaissimswb-gcc-7.4.0-lib/lib/libstdc++.so.6.0.24-gdb.py
line to your configuration file "/home/riley/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/riley/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000001bcd198 in ?? ()
#2  0x0000000001bcd055 in ?? ()
#3  0x0000000001bcd20e in ?? ()
#4  0x0000000001bc9f07 in ?? ()
#5  0x0000000001b9a03c in ?? ()
#6  0x0000000001b9fb78 in ?? ()
#7  0x0000000001b7e43a in ?? ()
#8  0x0000000001b7e166 in ?? ()
#9  0x0000000001b5ce7d in ?? ()
#10 0x0000000001b5e963 in ?? ()
#11 0x0000000001a185ae in ?? ()
#12 0x0000000001a13479 in ?? ()
#13 0x0000000001a1a89b in ?? ()
#14 0x00000000010c5340 in ?? ()
#15 0x00000000010c5282 in ?? ()
#16 0x00000000010c516f in ?? ()
#17 0x00000000010c4e93 in ?? ()
#18 0x00000000010c4d15 in ?? ()
#19 0x0000000001c0c0eb in ?? ()
#20 0x0000000001c0c2fa in ?? ()
#21 0x0000000002074a53 in ?? ()
#22 0x00000000020718d4 in ?? ()
#23 0x000000000183887e in ?? ()
#24 0x000000000183f69b in ?? ()
#25 0x000000000183f4b4 in ?? ()
#26 0x000000000110ce30 in ?? ()
#27 0x000000000110cb65 in ?? ()
#28 0x000000000110caa6 in ?? ()
#29 0x000000000208756c in ?? ()
#30 0x00007f0c7cf14ef7 in start_thread () from /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libpthread.so.0
#31 0x00007f0c7c2b022f in clone () from /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libc.so.6
```
</details>

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.63, NixOS, 19.03.173251.56d94c8c69f (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173251.56d94c8c69f"`
 - channels(riley): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by rileyinman** [comment]
The issue seems to have resolved itself after an upgrade, closing.
