### ISSUE TITLE
sweethome3d impure? copied package don't work

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#66471]
**Describe the bug**
I copied a closure from one system (19.03) to a USB thumb drive and from that to another system (19.09), but the program don't work.

I think nix packages should be pure and work also on another system running a different NixOS channel. (Right?)

**To Reproduce**
1. have sweethome3d installed
2. plug in thumb drive
3. mount thumb drive (i use pantheons files app and open a terminal from there, then `pwd`)
4. create a folder on the thumb drive. mine is "nixpkgs"
5. copy to that folder: `nix copy --to file:///run/media/davidak/9AEE-1F0D/nixpkgs $(type -p sweethome3d)`
6. get the nix store path of the program:

```
[davidak@X230:~]$ type -p sweethome3d
/home/davidak/.nix-profile/bin/sweethome3d

[davidak@X230:~]$ ls -la /home/davidak/.nix-profile/bin/sweethome3d
lrwxrwxrwx 1 root root 87  1. Jan 1970  /home/davidak/.nix-profile/bin/sweethome3d -> /nix/store/hxp8riy9lzv5razfywxqgrqfj1db2vj7-sweethome3d-application-6.0/bin/sweethome3d
```
7. plug the usb drive into another system and mount it, get the path
8. copy the nix store path to your system: `nix copy --from file:///run/media/davidak/9AEE-1F0D/nixpkgs /nix/store/hxp8riy9lzv5razfywxqgrqfj1db2vj7-sweethome3d-application-6.0/bin/sweethome3d`
9.a you can install it for the current user if you like: `nix-env -i /nix/store/hxp8riy9lzv5razfywxqgrqfj1db2vj7-sweethome3d-application-6.0/bin/sweethome3d`
9.b or just open a nix shell: `nix run /nix/store/hxp8riy9lzv5razfywxqgrqfj1db2vj7-sweethome3d-application-6.0/bin/sweethome3d`
10. now run the program:

```
$ sweethome3d 
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.eteks.sweethome3d.SweetHome3DBootstrap.main(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/extension4577508567935158164.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:603)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:63)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:106)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:487)
	at jogamp.nativewindow.NWJNILibLoader.access$000(NWJNILibLoader.java:39)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:49)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:41)
	at java.security.AccessController.doPrivileged(Native Method)
	at jogamp.nativewindow.NWJNILibLoader.loadNativeWindow(NWJNILibLoader.java:41)
	at jogamp.nativewindow.jawt.JAWTUtil.<clinit>(JAWTUtil.java:336)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.jogamp.nativewindow.NativeWindowFactory$3.run(NativeWindowFactory.java:344)
	at com.jogamp.nativewindow.NativeWindowFactory$3.run(NativeWindowFactory.java:340)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.nativewindow.NativeWindowFactory.initSingleton(NativeWindowFactory.java:340)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1721)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2297)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1021)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1050)
	at com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:803)
	at javax.media.j3d.JoglPipeline.initialize(JoglPipeline.java:131)
	at javax.media.j3d.Pipeline.createPipeline(Pipeline.java:92)
	at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:858)
	at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:267)
	at javax.media.j3d.GraphicsConfigTemplate3D.isGraphicsConfigSupported(GraphicsConfigTemplate3D.java:348)
	at com.eteks.sweethome3d.j3d.Component3DManager.createGraphicsConfigurationTemplate3D(Unknown Source)
	at com.eteks.sweethome3d.j3d.Component3DManager.<init>(Unknown Source)
	at com.eteks.sweethome3d.j3d.Component3DManager.getInstance(Unknown Source)
	at com.eteks.sweethome3d.SweetHome3D.addComponent3DRenderingErrorObserver(Unknown Source)
	at com.eteks.sweethome3d.SweetHome3D.init(Unknown Source)
	at com.eteks.sweethome3d.SweetHome3D.main(Unknown Source)
	... 5 more
^C
```

**Expected behavior**
Program just work.

**Additional context**
I moved to a new flat with most of my computers and want to plan where to put my furniture. I installed sweethome3d on my notebook, but it is not powerfull enough. So i want to copy the program to my iMac. I have internet from my tethered mobile phone, so i can't just install it from the internet! sweethome3d is about 500 MB, that would be 1/4 of my data plan!!!

**Metadata**
X230:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.63, NixOS, 19.03.173221.9ca57dc9171 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.03.173221.9ca57dc9171, nixos-hardware, nixos-unstable-19.09pre186857.239fffc90d7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

imac:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.63, NixOS, 19.09.git.7db3602 (Loris)`
hangs after that

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: sweethome3d
# a list of nixos modules affected by the problem
module:
```

**Comment by davidak** [comment]
Looks like this problem again: https://github.com/NixOS/nixpkgs/pull/22909

cc @bjornfor @2chilled

**Comment by davidak** [comment]
When i run the package from unstable on stable, i get the same error:

```
[davidak@X230:~]$ nix run -f channel:nixos-unstable sweethome3d.application
[113 copied (464.8 MiB), 139.9 MiB DL]

[davidak@X230:~]$ sweethome3d 
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.eteks.sweethome3d.SweetHome3DBootstrap.main(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/extension8491416013782226237.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
...
```
(but it will hopefully work on the imac when i copy it there again)

**Comment by davidak** [comment]
I get the same error when i run the package from unstable on my 19.09 branch. So it might be generally broken on unstable.

**Comment by bjornfor** [comment]
Yes, looks like be some kind of impurity. It runs on my NixOS 19.03 system, both from the stable and unstable channels. And I did the "nix run" thing you said and it works there too (I'm not sure how much isolation `nix run` gives, apparently not enough).

**Comment by jtojnar** [comment]
It looks like the program copies some so files to `/tmp` on start-up:

```ShellSession
$ ldd /tmp/extension*.so
/tmp/extension444705103117971428.so:
ldd: warning: you do not have execution permission for `/tmp/extension444705103117971428.so'
    linux-vdso.so.1 (0x00007ffdddf84000)
    libX11.so.6 => not found
    libXxf86vm.so.1 => /nix/store/kc9xzzyrakzdrqvli0vz7d59spj4r3dr-libXxf86vm-1.1.4/lib/libXxf86vm.so.1 (0x00007fdbbb4b7000)
    libXrender.so.1 => not found
    libjawt.so => not found
    libc.so.6 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libc.so.6 (0x00007fdbbb301000)
    libX11.so.6 => /nix/store/fz6s5xxd1c6wgfm9c3g2dz0hnjj1nqn6-libX11-1.6.7/lib/libX11.so.6 (0x00007fdbbb1bd000)
    libXext.so.6 => /nix/store/ld1awxg8k5aaxndi5i8qcj8ml0yjdb8g-libXext-1.3.4/lib/libXext.so.6 (0x00007fdbbb1a8000)
    /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007fdbbb6c4000)
    libxcb.so.1 => /nix/store/vsh5fm04m6wk1pxdgk9p66sqgnpi7wya-libxcb-1.13.1/lib/libxcb.so.1 (0x00007fdbbb17d000)
    libdl.so.2 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libdl.so.2 (0x00007fdbbb178000)
    libXau.so.6 => /nix/store/4mj4wmhy664yjxwp57766vcr770jn798-libXau-1.0.9/lib/libXau.so.6 (0x00007fdbbb173000)
    libXdmcp.so.6 => /nix/store/khw0pddjxljm04k3ssfbx7ii3pyq4vh1-libXdmcp-1.1.3/lib/libXdmcp.so.6 (0x00007fdbbb169000)
/tmp/extension4135255653085348156.so:
ldd: warning: you do not have execution permission for `/tmp/extension4135255653085348156.so'
    linux-vdso.so.1 (0x00007fffd81ea000)
    libc.so.6 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libc.so.6 (0x00007f780d334000)
    /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007f780d6ee000)
/tmp/extension6265797356284319317.so:
ldd: warning: you do not have execution permission for `/tmp/extension6265797356284319317.so'
    linux-vdso.so.1 (0x00007ffed01ac000)
    libX11.so.6 => not found
    libc.so.6 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libc.so.6 (0x00007f816b64d000)
    /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007f816babe000)
/tmp/extension6993359893675513939.so:
ldd: warning: you do not have execution permission for `/tmp/extension6993359893675513939.so'
    linux-vdso.so.1 (0x00007ffcf6179000)
    libX11.so.6 => not found
    libXxf86vm.so.1 => /nix/store/kc9xzzyrakzdrqvli0vz7d59spj4r3dr-libXxf86vm-1.1.4/lib/libXxf86vm.so.1 (0x00007f6d2d447000)
    libXrender.so.1 => not found
    libc.so.6 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libc.so.6 (0x00007f6d2d291000)
    libX11.so.6 => /nix/store/fz6s5xxd1c6wgfm9c3g2dz0hnjj1nqn6-libX11-1.6.7/lib/libX11.so.6 (0x00007f6d2d14f000)
    libXext.so.6 => /nix/store/ld1awxg8k5aaxndi5i8qcj8ml0yjdb8g-libXext-1.3.4/lib/libXext.so.6 (0x00007f6d2d138000)
    /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007f6d2d65a000)
    libxcb.so.1 => /nix/store/vsh5fm04m6wk1pxdgk9p66sqgnpi7wya-libxcb-1.13.1/lib/libxcb.so.1 (0x00007f6d2d10d000)
    libdl.so.2 => /nix/store/iykxb0bmfjmi7s53kfg6pjbfpd8jmza6-glibc-2.27/lib/libdl.so.2 (0x00007f6d2d108000)
    libXau.so.6 => /nix/store/4mj4wmhy664yjxwp57766vcr770jn798-libXau-1.0.9/lib/libXau.so.6 (0x00007f6d2d103000)
    libXdmcp.so.6 => /nix/store/khw0pddjxljm04k3ssfbx7ii3pyq4vh1-libXdmcp-1.1.3/lib/libXdmcp.so.6 (0x00007f6d2d0fb000)
$ for f in /tmp/extension*.so
      echo "$f:"
      patchelf --print-rpath $f
  end
/tmp/extension444705103117971428.so:
/nix/store/kc9xzzyrakzdrqvli0vz7d59spj4r3dr-libXxf86vm-1.1.4/lib
/tmp/extension4135255653085348156.so:

/tmp/extension6265797356284319317.so:

/tmp/extension6993359893675513939.so:
/nix/store/kc9xzzyrakzdrqvli0vz7d59spj4r3dr-libXxf86vm-1.1.4/lib
```

Two of the programs match to libraries in the `sweethome3d.application.src` but I could not match the other two; also I do not have the same filenames as you.

```ShellSession
$ diffoscope '/tmp/extension6265797356284319317.so' '/nix/store/fla0cgm6v5jg3c86ig3sp6bna0yq88w7-SweetHome3D-r6750/lib/java3d-1.6/linux/amd64/libjogl_desktop.so'
$ diffoscope '/tmp/extension4135255653085348156.so' '/nix/store/fla0cgm6v5jg3c86ig3sp6bna0yq88w7-SweetHome3D-r6750/lib/java3d-1.6/linux/amd64/libgluegen-rt.so
```

Not sure what libraries’ RPATH should be patched but perhaps adding the following to wrapper would work as well:

```
--- a/pkgs/applications/misc/sweethome3d/default.nix
+++ b/pkgs/applications/misc/sweethome3d/default.nix
@@ -55,6 +55,7 @@ let
 
       makeWrapper ${jre}/bin/java $out/bin/$exec \
         --prefix XDG_DATA_DIRS : "$XDG_ICON_DIRS:${gtk3.out}/share:${gsettings-desktop-schemas}/share:$out/share:$GSETTINGS_SCHEMAS_PATH" \
+        --prefix LD_LIBRARY_PATH : "${libXxf86vm}/lib" \
         --add-flags "-jar $out/share/java/${module}-${version}.jar -cp $out/share/java/Furniture.jar:$out/share/java/Textures.jar:$out/share/java/Help.jar -d${toString stdenv.hostPlatform.parsed.cpu.bits}"
     '';
 
```

**Comment by jtojnar** [comment]
For the reference, the libraries loaded are listed here:

https://github.com/jtojnar/sweethome3d/blob/34c83228378af8ab881292258238a834d28ea256/SweetHome3D/src/com/eteks/sweethome3d/SweetHome3DBootstrap.java#L137-L154
