### ISSUE TITLE
Fabric broken

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#67112]
**Describe the bug**
Here to remind myself to fix the package when i have time

**To Reproduce**
nix-shell -p Fabric --run "fab --help"

EDIT: fix executable name
```
[nix-shell:~/.cache/nix-review/pr-67063]$ ./results/Fabric/bin/fab --help
Traceback (most recent call last):
  File "/nix/store/6c1nc3hn6wbkbm4sahsaf0c3gp05vr1h-python2.7-fabric-2.4.0/bin/.fab-wrapped", line 7, in <module>
    from fabric.main import program
  File "/nix/store/gaismk7zwkpvys6c8r16a6jhxxj1dlcw-python3.7-fabric-2.4.0/lib/python3.7/site-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/nix/store/gaismk7zwkpvys6c8r16a6jhxxj1dlcw-python3.7-fabric-2.4.0/lib/python3.7/site-packages/fabric/connection.py", line 16, in <module>
    from paramiko.agent import AgentRequestHandler
  File "/nix/store/v1wryayrz7bn5a5k4nd83n7n97ansdbg-python3.7-paramiko-2.6.0/lib/python3.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/nix/store/v1wryayrz7bn5a5k4nd83n7n97ansdbg-python3.7-paramiko-2.6.0/lib/python3.7/site-packages/paramiko/transport.py", line 90, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/nix/store/v1wryayrz7bn5a5k4nd83n7n97ansdbg-python3.7-paramiko-2.6.0/lib/python3.7/site-packages/paramiko/ed25519key.py", line 17, in <module>
    import bcrypt
  File "/nix/store/80496q7f2hajkj9iw46pqmhw5h401n9p-python3.7-bcrypt-3.1.7/lib/python3.7/site-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt
ImportError: cannot import name _bcrypt
```
**Expected behavior**
To work

**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:

**Comment by davidak** [comment]
On 19.03:

```
[davidak@ethmoid:~]$ nix-shell -p Fabric --run "Fabric --help"
these paths will be fetched (1.70 MiB download, 10.56 MiB unpacked):
  /nix/store/16l69ny0jndfshbph1l6i8kixcl3j092-python2.7-enum34-1.1.6
  /nix/store/29dwvdanj9j0j7qmad9kq2nw9nj8dkhn-python2.7-bcrypt-3.1.6
  /nix/store/35b9vzmjvgniyxpdcgiib4573496rx23-python2.7-cryptography-2.5
  /nix/store/3fbwi1yq4b9dyq727rys2d2c1pcdj0i0-python2.7-pycparser-2.19
  /nix/store/9cq8i54vxk169vjnximp662qlrmf6fzv-python2.7-packaging-19.0
  /nix/store/a9lf49dq9bn0505gs2h71w0yr1d9kcz6-python2.7-asn1crypto-0.24.0
  /nix/store/admzxfrv54gmppr4f8hc8drpxj4qb23l-python2.7-pyasn1-0.4.5
  /nix/store/crv0068nnwz9cahg6anz0hfr0d332jli-python2.7-invoke-1.2.0
  /nix/store/hi6h9j17mvh31cfkaww03vhrjx7l60vz-python2.7-fabric-2.4.0
  /nix/store/i1c74daj9xzxaw5kfjc6s8sqsa6ay3wc-python2.7-pynacl-1.3.0
  /nix/store/lnpgx7lk7hhppbv7bjmsivygns3cbdbi-python2.7-pyparsing-2.3.1
  /nix/store/s2zxdvr0wlm2i8jz29szss8wmmzvgwwg-python2.7-cryptography-2.5-dev
  /nix/store/v4j9z2c94cidrdk58hmz7jdj3fx6hhdh-python2.7-ipaddress-1.0.22
  /nix/store/wa2jmp3pxdc90qn619lwlpnl63aqxql7-python2.7-cffi-1.12.1-dev
  /nix/store/ycsv4m75b7pwzbwck60h04b01335glpa-python2.7-paramiko-2.4.2
  /nix/store/zm5nf4srpk7300aqvjz9ada5zf5kxqai-python2.7-cffi-1.12.1
  /nix/store/zrpgg1brslzb20prwissnqklgsyc7475-python2.7-six-1.12.0
copying path '/nix/store/a9lf49dq9bn0505gs2h71w0yr1d9kcz6-python2.7-asn1crypto-0.24.0' from 'https://cache.nixos.org'...
copying path '/nix/store/zm5nf4srpk7300aqvjz9ada5zf5kxqai-python2.7-cffi-1.12.1' from 'https://cache.nixos.org'...
copying path '/nix/store/35b9vzmjvgniyxpdcgiib4573496rx23-python2.7-cryptography-2.5' from 'https://cache.nixos.org'...
copying path '/nix/store/16l69ny0jndfshbph1l6i8kixcl3j092-python2.7-enum34-1.1.6' from 'https://cache.nixos.org'...
copying path '/nix/store/crv0068nnwz9cahg6anz0hfr0d332jli-python2.7-invoke-1.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/v4j9z2c94cidrdk58hmz7jdj3fx6hhdh-python2.7-ipaddress-1.0.22' from 'https://cache.nixos.org'...
copying path '/nix/store/admzxfrv54gmppr4f8hc8drpxj4qb23l-python2.7-pyasn1-0.4.5' from 'https://cache.nixos.org'...
copying path '/nix/store/3fbwi1yq4b9dyq727rys2d2c1pcdj0i0-python2.7-pycparser-2.19' from 'https://cache.nixos.org'...
copying path '/nix/store/lnpgx7lk7hhppbv7bjmsivygns3cbdbi-python2.7-pyparsing-2.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/zrpgg1brslzb20prwissnqklgsyc7475-python2.7-six-1.12.0' from 'https://cache.nixos.org'...
copying path '/nix/store/wa2jmp3pxdc90qn619lwlpnl63aqxql7-python2.7-cffi-1.12.1-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/29dwvdanj9j0j7qmad9kq2nw9nj8dkhn-python2.7-bcrypt-3.1.6' from 'https://cache.nixos.org'...
copying path '/nix/store/i1c74daj9xzxaw5kfjc6s8sqsa6ay3wc-python2.7-pynacl-1.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/9cq8i54vxk169vjnximp662qlrmf6fzv-python2.7-packaging-19.0' from 'https://cache.nixos.org'...
copying path '/nix/store/s2zxdvr0wlm2i8jz29szss8wmmzvgwwg-python2.7-cryptography-2.5-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/ycsv4m75b7pwzbwck60h04b01335glpa-python2.7-paramiko-2.4.2' from 'https://cache.nixos.org'...
copying path '/nix/store/hi6h9j17mvh31cfkaww03vhrjx7l60vz-python2.7-fabric-2.4.0' from 'https://cache.nixos.org'...
/tmp/nix-shell-13754-0/rc: line 1: Fabric: command not found
```

---

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.62, NixOS, 19.03.173202.31d476b8797 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173202.31d476b8797, nixos-hardware, nixos-unstable-19.09pre186857.239fffc90d7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jonringer** [comment]
sorry, this is off of master. I was reviewing a PR

**Comment by jonringer** [comment]
no longer able to reproduce this error.... weird.
