### ISSUE TITLE
pytorchWithCuda fails to run

### ISSUE THREAD

**Issue by c00w** [NixOS/nixpkgs#67468]
**Describe the bug**
Build a python environment with
```
with import <nixpkgs> {};

python3.withPackages (ps: with ps; [ pytorchWithCuda])
```

**To Reproduce**
1. Run result/bin/python test.py, where test.py is
```
import torch
```

**Expected behavior**
Pytorch should import and be usable
instead output is
```
 % ./result/bin/python3.7 test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import torch
  File "/nix/store/kj6nlr3nl329ndz3b6f0f2kq503zp9d9-python3-3.7.4-env/lib/python3.7/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: /nix/store/kj6nlr3nl329ndz3b6f0f2kq503zp9d9-python3-3.7.4-env/lib/python3.7/site-packages/torch/lib/libtorch.so.1: undefined symbol: nvrtcGetProgramLogSize
```
**Screenshots**

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 % nix run nixpkgs.nix-info -c nix-info -m          ~/brood/src/codeml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.9, NixOS, 19.09pre-git (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(colin): `""`
 - channels(root): `"nixos-19.09pre190479.765a71f1502"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- pytorchWithCuda
# a list of nixos modules affected by the problem
module:
```

**Comment by jethrokuan** [comment]
I have the same issue, I think there's ongoing work in fixing this: https://github.com/NixOS/nixpkgs/pull/65041

**Comment by stites** [comment]
#65041 will close this. Please check out https://github.com/stites/pytorch-world in the meantime to preview pytorch-1.2 and file any bugs you find (also check out the probtorch folder if you need help adding this to your project).

Cachix binaries (primarily focused on cudatoolkit_10) are also available at https://pytorch-world.cachix.org
