### ISSUE TITLE
minecraft: Launcher is stuck at "Preparing..."

### ISSUE THREAD

**Issue by shirona** [NixOS/nixpkgs#68123]
**Describe the bug**
Upon pressing the "Play" button in the Minecraft launcher, the button is then stuck in the "Preparing..." phase.

**To Reproduce**
1. Launch the launcher
2. Log in if you haven't logged in yet
3. Press Play

**Additional context**
This is what is shown in the log:
```
[03:14:30 FATAL]: Unhandled exception in thread Thread[pool-2-thread-2,5,main]
com.google.gson.JsonSyntaxException: duplicate key: null
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:191) ~[minecraft.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:146) ~[minecraft.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[minecraft.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[minecraft.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:795) ~[minecraft.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:761) ~[minecraft.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:710) ~[minecraft.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:682) ~[minecraft.jar:?]
	at net.minecraft.launcher.updater.RemoteVersionList.getCompleteVersion(RemoteVersionList.java:32) ~[launcher.jar:1.6.89-j]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getLatestCompleteVersion(MinecraftVersionManager.java:213) ~[launcher.jar:1.6.89-j]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getLatestCompleteVersion(MinecraftVersionManager.java:37) ~[launcher.jar:1.6.89-j]
	at com.mojang.launcher.game.runner.AbstractGameRunner.playGame(AbstractGameRunner.java:67) ~[launcher.jar:1.6.89-j]
	at net.minecraft.launcher.game.GameLaunchDispatcher$1.run(GameLaunchDispatcher.java:111) ~[launcher.jar:1.6.89-j]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
From what I have seen on the Internet, this happens when the launcher is outdated, so there is that. I will tag @Infinisil, since he was the last one who fixed an issue related to the launcher.

*EDIT:* might be a good time to mention that I am nearly sure this isn't an issue with my computer. Just a few hours ago, I was playing Minecraft just fine. Now it's giving me this error, without generation changes nor reboots nor whatever. I even tried deleting the entire Minecraft folder and rebooted to get a fresh install, but it's still happening.

**Comment by Infinisil** [comment]
Yeah I can't launch either, and it doesn't seem to be a NixOS-specific problem, there's many more people having the same problem: https://www.minecraftforum.net/forums/support/java-edition-support/2985294-minecraft-launcher-stuck-on-preparing, also a bug report at https://bugs.mojang.com/browse/MCL-11990 (which was closed with Invalid??)

Anyways from the thread there it seems to indicate we finally need to update our launcher. The one we use in NixOS is like at least 4 years old, even though a new one has been release for a while.

**Comment by hyperfekt** [comment]
The provided .deb file includes the icon but I can't find a URL that would point to a fixed version of it (which is available for the general package, but that does not include the icons) - we can't add copyrighted material to the repo or have the build fail because a new version is released and the hash doesn't match anymore, and I would like to not have to pull the AUR repo.
cc @peterix

**Comment by gyroninja** [comment]
I previously sent unpolished derivations for both the new Minecraft launcher and a launcher for running Minecraft-PE to @Infinisil .
Here's a link to an archive for the derivations: https://0x0.st/zLAg.gz (Note that it's is a .tar.gz despite the filename)
If you are curious about the Minecraft-PE launcher it essentially uses the x86 version of Minecraft-PE so that you can run it. This is useful if you want to use the Bedrock version of the game. If you are unaware there are two main ecosystems for Minecraft, Java Edition (the original) and Bedrock Edition (multiplatform W10, Android, iOS, switch, xbox one, etc).

**Comment by abbradar** [comment]
A bit off-topic - MultiMC launcher seems to work fine (and I consider it a better launcher :D).

**Comment by peterix** [comment]
Right. This is interesting.

If you are making binary packages and putting them on a repo, you are technically breaking copyright law. So, that flatpak thing? Illegal. Avoid it. I just don't have the heart to forward it to enforcement.

We could totally put the icon somewhere so you can grab it and use it.

**Comment by Infinisil** [comment]
@peterix Perhaps you meant to comment in https://github.com/NixOS/nixpkgs/pull/68175/? I'm just noticing that while nixpkgs doesn't use the Flatpak thing, we still had the intention of providing a prebuilt package for the launcher. Because of [a problem](https://github.com/NixOS/nixpkgs/pull/47237) however, this never actually worked. I'll make sure that in above PR we switch from `unfreeRedistributable` as a license to `unfree` such that no altered version will ever be provided by the build servers, so users will continue to have to let their machine patch it locally.

Having the icon at a fixed url would be great yeah (preferably a versioned url in case it ever changes), or even included in `https://launcher.mojang.com/download/linux/x86_64/minecraft-launcher_${version}.tar.gz` (probably won't work well because of its structure though).

Nice to have someone from the Mojang team here :D

**Comment by worldofpeace** [comment]
Having the `.deb` fetchable at a fixed url would be great also.

**Comment by worldofpeace** [comment]
@peterix 🏓️
