### ISSUE TITLE
`No module named 'pkg_resources'` when importing Z3

### ISSUE THREAD

**Issue by Pamplemousse** [NixOS/nixpkgs#68606]
**Describe the bug**
The python module for Z3, available as `pythonPackages.z3`, fails to load in a python interpreter.

**To reproduce**

```
nix-shell -p python3 python3Packages.z3

[nix-shell:~/Workspace/nixpkgs]$ python -m z3
Traceback (most recent call last):
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/nix/store/p5hmjgp2g0sq14ppn5r768dwdsm7p42b-z3-4.8.5-python/lib/python3.7/site-packages/z3/__init__.py", line 1, in <module>
    from .z3 import *
  File "/nix/store/p5hmjgp2g0sq14ppn5r768dwdsm7p42b-z3-4.8.5-python/lib/python3.7/site-packages/z3/z3.py", line 45, in <module>
    from . import z3core
  File "/nix/store/p5hmjgp2g0sq14ppn5r768dwdsm7p42b-z3-4.8.5-python/lib/python3.7/site-packages/z3/z3core.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Additional context**

Relate to #68314 , but I wonder how to make it work without it: `setuptools` seems to already be part of the `propagatedBuildInputs` of Z3: [c.f. the expression of the package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/science/logic/z3/default.nix#L15) ... :thinking:

**Comment by FRidh** [comment]
```
nix-shell -p python3 python3Packages.z3
```
This is *not* a supported way of working, and indeed fails often for bindings. Always use `python.withPackages` or `python.buildEnv`.

**Comment by Pamplemousse** [comment]
Closing issue: irrelevant as per [@FRidh comment](issuecomment-531327221).

Will update #68430, keep working on #67413, and reopen if needed.

**Comment by daef** [comment]
#68430 was never merged, but python3(10/11)Packages.z3 still doesnt work (still throws ModuleNotFoundError: No module named 'pkg_resources')
