### ISSUE TITLE
Package `gitfs` doesn't work (needs to write `/var/lib/gitfs`)

### ISSUE THREAD

**Issue by abliss** [NixOS/nixpkgs#68986]
**Describe the bug**
The `gitfs` tool from the `gitfs` package does not work.

**To Reproduce**
1. `nix-env -i gitfs`
2. `git init tmp`
3. `mkdir -p mnt`
4. `gitfs tmp mnt`

**Expected behavior**
git repo mounted 

**Additional context**
backtrace:
```
Traceback (most recent call last):
  File "/nix/store/sz4i95ad37mb27vdvndf4kyhw6gbh9vg-gitfs-0.4.5.1/bin/.gitfs-wrapped", line 11, in <module>
    sys.exit(mount())
  File "/nix/store/sz4i95ad37mb27vdvndf4kyhw6gbh9vg-gitfs-0.4.5.1/lib/python2.7/site-packages/gitfs/__init__.py", line 20, in mount
    start_fuse()
  File "/nix/store/sz4i95ad37mb27vdvndf4kyhw6gbh9vg-gitfs-0.4.5.1/lib/python2.7/site-packages/gitfs/mounter.py", line 108, in start_fuse
    args = parse_args(parser)
  File "/nix/store/sz4i95ad37mb27vdvndf4kyhw6gbh9vg-gitfs-0.4.5.1/lib/python2.7/site-packages/gitfs/mounter.py", line 40, in parse_args
    return Args(parser)
  File "/nix/store/sz4i95ad37mb27vdvndf4kyhw6gbh9vg-gitfs-0.4.5.1/lib/python2.7/site-packages/gitfs/utils/args.py", line 63, in __init__
    self.config = self.build_config(parser.parse_args())
  File "/nix/store/sz4i95ad37mb27vdvndf4kyhw6gbh9vg-gitfs-0.4.5.1/lib/python2.7/site-packages/gitfs/utils/args.py", line 72, in build_config
    return self.check_args(self.set_defaults(args))
  File "/nix/store/sz4i95ad37mb27vdvndf4kyhw6gbh9vg-gitfs-0.4.5.1/lib/python2.7/site-packages/gitfs/utils/args.py", line 142, in set_defaults
    value = value(args)
  File "/nix/store/sz4i95ad37mb27vdvndf4kyhw6gbh9vg-gitfs-0.4.5.1/lib/python2.7/site-packages/gitfs/utils/args.py", line 173, in get_repo_path
    return tempfile.mkdtemp(dir="/var/lib/gitfs")
  File "/nix/store/9kigl3bk51mfn0484y72w3zlm7d8ws76-python-2.7.16/lib/python2.7/tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/var/lib/gitfs/tmpU1yKxn'
```
Package definition: https://github.com/NixOS/nixpkgs/blob/076860e0340a5e4a909b9a710e186508b14d1c90/pkgs/tools/filesystems/gitfs/default.nix
Gitfs wiki demanding undconditional write access to `/var/lib/gitfs`:
https://wiki.archlinux.org/index.php/Gitfs#Write_access_to_/var/lib/gitfs
Problematic line upstream: https://github.com/presslabs/gitfs/blob/master/gitfs/utils/args.py#L175

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
[1 copied, 0.0 MiB DL]
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.75-ts1, Debian GNU/Linux, 7 (wheezy)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.2pre6377_954d1f4d`
 - channels(abliss): `"nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/e/abliss/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by aanderse** [comment]
@abliss from the information you've provided it seems to me that this issue belongs in the issue tracker for `gitfs`. No?

**Comment by abliss** [comment]
I wasn't sure.

I thought the gitfs owners might well reply that when gitfs is packaged,
e.g. for Debian, it's expected that the packagers would include a
preinstall script granting access to /var/lib/gitfs. From my understanding
of nix this doesn't really seem possible, so maybe whoever packages gitfs
for nixos should patch gitfs? Maybe upstream would accept a patch to make
the path configurable? Or maybe gitfs will just turn out to be
fundamentally incompatible with nix for some reason, in which case I might
suggest that the nixos packagers should remove the gitfs package.

**Comment by aanderse** [comment]
What user does Debian assign `/var/lib/gitfs` to? The `nix` package manager can't set permissions, but `NixOS` could... that being said from what the arch wiki says it looks like the directory is set to a specific user which makes me think upstream should allow the user to configure the directory. Also FYI I have no idea what this software is our does so uniformed opinion here.

**Comment by Valodim** [comment]
This issue is now fixed: There is now a `repo_path` option that allows placing the repo anywhere in the filesystem.
