### ISSUE TITLE
mopidy-2.2.3 doesn't start

### ISSUE THREAD

**Issue by MartinPotier** [NixOS/nixpkgs#69416]
**Describe the bug**
Cannot run mopidy anymore. Some python error related to `ImportError: No module named pkg_resources`

**To Reproduce**
Run:
```
$ nix repl https://github.com/NixOS/nixpkgs/archive/dd2f026780399cf11c47fcf6085145b25b14307e.tar.gz
nix-repl> :b mopidy

this derivation produced the following outputs:
  out -> /nix/store/cp95c1brgv8j9jkn28bp5j42vdcnpfr8-mopidy-2.2.3

nix-repl> ^D
$ /nix/store/cp95c1brgv8j9jkn28bp5j42vdcnpfr8-mopidy-2.2.3/bin/mopidy
Traceback (most recent call last):
  File "/nix/store/cp95c1brgv8j9jkn28bp5j42vdcnpfr8-mopidy-2.2.3/bin/..mopidy-wrapped-wrapped", line 7, in <module>
    from mopidy.__main__ import main
  File "/nix/store/cp95c1brgv8j9jkn28bp5j42vdcnpfr8-mopidy-2.2.3/lib/python2.7/site-packages/mopidy/__main__.py", line 10, in <module>
    from mopidy import commands, config as config_lib, ext
  File "/nix/store/cp95c1brgv8j9jkn28bp5j42vdcnpfr8-mopidy-2.2.3/lib/python2.7/site-packages/mopidy/commands.py", line 16, in <module>
    from mopidy.internal import deps, process, timer, versioning
  File "/nix/store/cp95c1brgv8j9jkn28bp5j42vdcnpfr8-mopidy-2.2.3/lib/python2.7/site-packages/mopidy/internal/deps.py", line 8, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

**Expected behavior**
Should start without python runtime errors

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.74, NixOS, 20.03pre193781.d484f2b7fc0 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-20.03pre193781.d484f2b7fc0"`
 - channels(eeva): `"nixos-19.09pre191505.7d5375ebf4c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - pkgs.mopidy
```

**Comment by Infinisil** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/69319
