### ISSUE TITLE
python37Packages.joblib: import error because setuptools is missing

### ISSUE THREAD

**Issue by alexpeits** [NixOS/nixpkgs#69522]
**Describe the bug**
scikit-learn has a runtime dependency of setuptools. The current nix package doesn't specify that and importing it fails. Adding `setuptools` to `buildInputs` fixes the issue.

**To Reproduce**
```
$ nix-shell -p 'python37.withPackages (self: with self; [ scikitlearn  ])'
$ python
>>> import sklearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/9mh5sm72238f721p98hgv8m7ysaxf60d-python3.7-scikit-learn-0.21.2/lib/python3.7/site-packages/sklearn/__init__.py", line 76, in <module>
    from .base import clone
  File "/nix/store/9mh5sm72238f721p98hgv8m7ysaxf60d-python3.7-scikit-learn-0.21.2/lib/python3.7/site-packages/sklearn/base.py", line 16, in <module>
    from .utils import _IS_32BIT
  File "/nix/store/9mh5sm72238f721p98hgv8m7ysaxf60d-python3.7-scikit-learn-0.21.2/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 17, in <module>
    from . import _joblib
  File "/nix/store/9mh5sm72238f721p98hgv8m7ysaxf60d-python3.7-scikit-learn-0.21.2/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 8, in <module>
    import joblib
  File "/nix/store/dwc6rb9yrb5j255p4v3bpq1p65h2vm79-python3.7-joblib-0.13.2/lib/python3.7/site-packages/joblib/__init__.py", line 112, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/nix/store/dwc6rb9yrb5j255p4v3bpq1p65h2vm79-python3.7-joblib-0.13.2/lib/python3.7/site-packages/joblib/memory.py", line 32, in <module>
    from ._store_backends import StoreBackendBase, FileSystemStoreBackend
  File "/nix/store/dwc6rb9yrb5j255p4v3bpq1p65h2vm79-python3.7-joblib-0.13.2/lib/python3.7/site-packages/joblib/_store_backends.py", line 16, in <module>
    from .backports import concurrency_safe_rename
  File "/nix/store/dwc6rb9yrb5j255p4v3bpq1p65h2vm79-python3.7-joblib-0.13.2/lib/python3.7/site-packages/joblib/backports.py", line 9, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'

```
```
$ nix-shell -p 'python37.withPackages (self: with self; [ scikitlearn setuptools ])'
$ python
>>> import sklearn
>>>
```

**Expected behavior**
Importing sklearn should work without specifying setuptools as an additional package.

**Additional context**
This is a known issue in some python packages that have not been built properly, e.g: https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources 

**Metadata**
```
[1 copied, 0.0 MiB DL]
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-64-generic, Ubuntu, 16.04.6 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.1`
 - channels(alex): `"nixpkgs-20.03pre193309.c4196cca9ac"`
 - nixpkgs: `/home/alex/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - python37Packages.scikitlearn
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
Please show the full trace so we can see exactly in which package the import fails.

**Comment by FRidh** [comment]
> This is a known issue in some python packages that have not been built properly, e.g: 

No, we no longer include setuptools/pkg_resources by default, thus requiring individual packages to declare it as runtime dependancy.

**Comment by alexpeits** [comment]
@FRidh I updated the description, on a closer look it seems like it's an issue in [joblib](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/joblib/default.nix)?

**Comment by FRidh** [comment]
correct, its joblib that needs to be fixed
