### ISSUE TITLE
NixOS: blueman does not work: Unable to load plugin module NMDUNSupport, Unit blueman-mechanism.service not found

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#69555]
I did update to today's master and blueman stopped working. Any idea what to do?
I have hardware.bluetooth.enable = true in my configuration.nix.

```
milan@nixos> blueman-manager                                                                                                          ~
blueman-manager version 2.1.1 starting
Blueman applet needs to be running
milan@nixos> blueman-tray                                                                                                             ~
blueman-tray version 2.1.1 starting
There is an instance already running
milan@nixos> blueman-applet                                                                                                           ~
blueman-applet version 2.1.1 starting
blueman-applet 18.50.34 ERROR    PluginManager:90 load_plugin: Unable to load plugin module NMDUNSupport
Traceback (most recent call last):
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/NetworkManager.py", line 6, in <module>
    gi.require_version('NM', '1.0')
  File "/nix/store/3qhlqj9c98hv30qwcdv67355gqvl7s8s-python3.7-pygobject-3.32.1/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace NM not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/PluginManager.py", line 88, in load_plugin
    importlib.import_module(self.module_path.__name__ + ".%s" % plugin)
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/applet/NMDUNSupport.py", line 3, in <module>
    from blueman.main.NetworkManager import NMDUNConnection
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/NetworkManager.py", line 8, in <module>
    raise ImportError('NM python bindings not found.')
ImportError: NM python bindings not found.
blueman-applet 18.50.34 ERROR    PluginManager:90 load_plugin: Unable to load plugin module NMPANSupport
Traceback (most recent call last):
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/NetworkManager.py", line 6, in <module>
    gi.require_version('NM', '1.0')
  File "/nix/store/3qhlqj9c98hv30qwcdv67355gqvl7s8s-python3.7-pygobject-3.32.1/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace NM not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/PluginManager.py", line 88, in load_plugin
    importlib.import_module(self.module_path.__name__ + ".%s" % plugin)
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/applet/NMPANSupport.py", line 3, in <module>
    from blueman.main.NetworkManager import NMPANConnection
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/NetworkManager.py", line 8, in <module>
    raise ImportError('NM python bindings not found.')
ImportError: NM python bindings not found.
Terminating blueman-tray
blueman-applet 18.50.34 ERROR    BasePlugin:76 _load     : Error calling StartServiceByName for org.blueman.Mechanism: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit blueman-mechanism.service not found.
Traceback (most recent call last):
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 36, in __init__
    self.init()
gi.repository.GLib.GError: g-io-error-quark: Error calling StartServiceByName for org.blueman.Mechanism: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit blueman-mechanism.service not found. (36)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/BasePlugin.py", line 70, in _load
    self.on_load()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/applet/Networking.py", line 24, in on_load
    self.load_nap_settings()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/applet/Networking.py", line 45, in load_nap_settings
    m = Mechanism()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 15, in __call__
    cls._instance = super().__call__(*args, **kwargs)
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 44, in __init__
    object_path="/org/blueman/mechanism", systembus=True, *args, **kwargs)
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 38, in __init__
    raise DBusProxyFailed(e.message)
blueman.main.DBusProxies.DBusProxyFailed: Error calling StartServiceByName for org.blueman.Mechanism: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit blueman-mechanism.service not found.
blueman-applet 18.50.34 ERROR    PluginManager:161 __load_plugin: Failed to load Networking
Traceback (most recent call last):
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 36, in __init__
    self.init()
gi.repository.GLib.GError: g-io-error-quark: Error calling StartServiceByName for org.blueman.Mechanism: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit blueman-mechanism.service not found. (36)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/PluginManager.py", line 159, in __load_plugin
    inst._load()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/AppletPlugin.py", line 57, in _load
    super()._load()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/BasePlugin.py", line 70, in _load
    self.on_load()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/applet/Networking.py", line 24, in on_load
    self.load_nap_settings()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/applet/Networking.py", line 45, in load_nap_settings
    m = Mechanism()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 15, in __call__
    cls._instance = super().__call__(*args, **kwargs)
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 44, in __init__
    object_path="/org/blueman/mechanism", systembus=True, *args, **kwargs)
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 38, in __init__
    raise DBusProxyFailed(e.message)
blueman.main.DBusProxies.DBusProxyFailed: Error calling StartServiceByName for org.blueman.Mechanism: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit blueman-mechanism.service not found.
Traceback (most recent call last):
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 36, in __init__
    self.init()
gi.repository.GLib.Error: g-io-error-quark: Error calling StartServiceByName for org.blueman.Mechanism: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit blueman-mechanism.service not found. (36)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/bin/..blueman-applet-wrapped-wrapped", line 43, in <module>
    BluemanApplet()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/Applet.py", line 34, in __init__
    self.Plugins.load_plugin()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/PluginManager.py", line 121, in load_plugin
    self.__load_plugin(cls)
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/PluginManager.py", line 159, in __load_plugin
    inst._load()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/AppletPlugin.py", line 57, in _load
    super()._load()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/BasePlugin.py", line 70, in _load
    self.on_load()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/applet/Networking.py", line 24, in on_load
    self.load_nap_settings()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/plugins/applet/Networking.py", line 45, in load_nap_settings
    m = Mechanism()
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 15, in __call__
    cls._instance = super().__call__(*args, **kwargs)
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 44, in __init__
    object_path="/org/blueman/mechanism", systembus=True, *args, **kwargs)
  File "/nix/store/x8l9w07cc6v7kk5nqjdmagfvvl94s31k-blueman-2.1.1/lib/python3.7/site-packages/blueman/main/DBusProxies.py", line 38, in __init__
    raise DBusProxyFailed(e.message)
blueman.main.DBusProxies.DBusProxyFailed: Error calling StartServiceByName for org.blueman.Mechanism: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit blueman-mechanism.service not found.
[1] milan@nixos> blueman-tray version 2.1.1 starting                                                                                  ~
Stale PID, overwriting
blueman-tray version 2.1.1 starting
There is an instance already running
[1] milan@nixos>                                                                                                                      ~
[1] milan@nixos> blueman-manager                                                                                                      ~
blueman-manager version 2.1.1 starting
Blueman applet needs to be running
milan@nixos> 
```

**Comment by worldofpeace** [comment]
I believe https://github.com/NixOS/nixpkgs/pull/69434 fixes this

**Comment by tex** [comment]
#69434 Does NOT fixes this problem.

**Comment by worldofpeace** [comment]
@tex I think I'll have a PR to fix this incoming soon.

**Comment by ck3d** [comment]
I run 19.09.git.810a568 (which includes #69434 and #70149) on my machine and I still have the same issue, blueman-mechanism.service is not found.
I added package blueman also into services.dbus.packages.

**Comment by tex** [comment]
Confirm, I have the same problem.

**Comment by ck3d** [comment]
blueman 2.1 has introduced the unit blueman-mechanism.service and is stored in ${pkgs.blueman}/lib/systemd/system . dbus is not searching in that folder.

**Comment by worldofpeace** [comment]
Are any of you using the nixos service?
* https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/desktops/blueman.nix

**Comment by ck3d** [comment]
No, but thanks for your hint. Activating the service solved the issue!

**Comment by tex** [comment]
Confirm, it works when the service is enabled!
