### ISSUE TITLE
`buildPythonPackage` does not seem to propagate inputs passed via directory

### ISSUE THREAD

**Issue by adnelson** [NixOS/nixpkgs#6955]
The summary of this is that I have a package `foo`, which builds, and a package `bar` which *depends on* `foo`, and does *not* build.

I have the following directory structure:

```
├── bar
│   ├── default.nix
│   ├── setup.py
│   └── src
│       └── bar
│           ├── bar.py
│           └── __init__.py
└── foo
    ├── default.nix
    ├── setup.py
    └── src
        └── foo
            ├── foo.py
            └── __init__.py
```

The `foo/default.nix` looks like:

```nix
with import <nixpkgs> {};

buildPythonPackage {
  name = "foo";
  version = "0.0.1";
  src = ./.;
}
```

And `foo/setup.py` looks like:

```python
import setuptools

setuptools.setup(
    name='foo',
    version='0.0.1',
    package_dir={'': 'src'},
    packages=setuptools.find_packages('src'),
    provides=setuptools.find_packages('src'),
)
```

While `bar/default.nix` looks like:

```nix
with import <nixpkgs> {};

buildPythonPackage {
  name = "bar";
  version = "0.0.1";
  buildInputs = [ ../foo ];
  src = ./.;
}
```

And `bar/setup.py` looks like:

```python
import setuptools

setuptools.setup(
    name='bar',
    version='0.0.1',
    package_dir={'': 'src'},
    packages=setuptools.find_packages('src'),
    provides=setuptools.find_packages('src'),
    install_requires=['foo']
)
```

Now, if I do a `nix-shell --pure` in the `foo` directory, it builds correctly, and I can call functions in the `foo` package:

```
foo> nix-shell --pure
running develop
running egg_info
creating src/foo.egg-info
writing src/foo.egg-info/PKG-INFO
writing top-level names to src/foo.egg-info/top_level.txt
writing dependency_links to src/foo.egg-info/dependency_links.txt
writing manifest file 'src/foo.egg-info/SOURCES.txt'
reading manifest file 'src/foo.egg-info/SOURCES.txt'
writing manifest file 'src/foo.egg-info/SOURCES.txt'
running build_ext
Creating /tmp/240a1bd3fc2538e4a5a3505f25aa4c4e-python2.7-foo/lib/python2.7/site-packages/foo.egg-link (link to src)
foo 0.0.1 is already the active version in easy-install.pth

Installed /home/anelson/workspace/nix/pythonstuff/foo/src
Processing dependencies for foo==0.0.1
Finished processing dependencies for foo==0.0.1

[nix-shell:~/workspace/nix/pythonstuff/foo]$ echo $PYTHONPATH
/tmp/240a1bd3fc2538e4a5a3505f25aa4c4e-python2.7-foo/lib/python2.7/site-packages:/nix/store/lcwiwv7jkyslj6aydv5gczw0xg7xcp7r-python2.7-setuptools-7.0/lib/python2.7/site-packages:/nix/store/bf1arcwsggzygypnxm5r2sni97cdnsvi-python2.7-distutils.cfg/lib/python2.7/site-packages:/nix/store/lxhzbj7q1969rf9164rdcjc9v76413qw-python-recursive-pth-loader-1.0/lib/python2.7/site-packages:/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/site-packages

[nix-shell:~/workspace/nix/pythonstuff/foo]$ python
Python 2.7.9 (default, Jan 01 1970, 00:00:01) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import foo.foo as f
>>> f.foo_function('bob')
hello bob
>>> 
```

So `foo` seems to build correctly and be usable. However, I *can't* do this with `bar`:

```
bar>  nix-shell --pure
running develop
running egg_info
writing requirements to src/bar.egg-info/requires.txt
writing src/bar.egg-info/PKG-INFO
writing top-level names to src/bar.egg-info/top_level.txt
writing dependency_links to src/bar.egg-info/dependency_links.txt
reading manifest file 'src/bar.egg-info/SOURCES.txt'
writing manifest file 'src/bar.egg-info/SOURCES.txt'
running build_ext
Creating /tmp/339284cab5f970074a1fd8cbd66df518-python2.7-bar/lib/python2.7/site-packages/bar.egg-link (link to src)
bar 0.0.1 is already the active version in easy-install.pth

Installed /home/anelson/workspace/nix/pythonstuff/bar/src
Processing dependencies for bar==0.0.1
Searching for foo

Note: Bypassing https://pypi.python.org/simple/foo/ (disallowed host; see http://bit.ly/1dg9ijs for details).

Couldn't find index page for 'foo' (maybe misspelled?)
Scanning index of all packages (this may take a while)

Note: Bypassing https://pypi.python.org/simple/ (disallowed host; see http://bit.ly/1dg9ijs for details).

No local packages or download links found for foo
error: Could not find suitable distribution for Requirement.parse('foo')
```

If I remove the `install_requires=['foo']` line from `bar/setup.py`, the build succeeds, but `foo` is not in the `PYTHONPATH` and I can't use it.

```
bar>  nix-shell --pure
running develop
running egg_info
deleting src/bar.egg-info/requires.txt
writing src/bar.egg-info/PKG-INFO
writing top-level names to src/bar.egg-info/top_level.txt
writing dependency_links to src/bar.egg-info/dependency_links.txt
reading manifest file 'src/bar.egg-info/SOURCES.txt'
writing manifest file 'src/bar.egg-info/SOURCES.txt'
running build_ext
Creating /tmp/339284cab5f970074a1fd8cbd66df518-python2.7-bar/lib/python2.7/site-packages/bar.egg-link (link to src)
bar 0.0.1 is already the active version in easy-install.pth

Installed /home/anelson/workspace/nix/pythonstuff/bar/src
Processing dependencies for bar==0.0.1
Finished processing dependencies for bar==0.0.1

[nix-shell:~/workspace/nix/pythonstuff/bar]$ echo $PYTHONPATH
/tmp/339284cab5f970074a1fd8cbd66df518-python2.7-bar/lib/python2.7/site-packages:/nix/store/lcwiwv7jkyslj6aydv5gczw0xg7xcp7r-python2.7-setuptools-7.0/lib/python2.7/site-packages:/nix/store/bf1arcwsggzygypnxm5r2sni97cdnsvi-python2.7-distutils.cfg/lib/python2.7/site-packages:/nix/store/lxhzbj7q1969rf9164rdcjc9v76413qw-python-recursive-pth-loader-1.0/lib/python2.7/site-packages:/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/site-packages

[nix-shell:~/workspace/nix/pythonstuff/bar]$ python
Python 2.7.9 (default, Jan 01 1970, 00:00:01) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named foo
>>> 
```

What do I need to do to be able to propagate the `foo` package as an input to `bar`?

**Comment by adnelson** [comment]
@domenkozar thanks for taking a look :smile:

**Comment by adnelson** [comment]
OK so I'm increasingly thinking this is all stemming from my ignorance of what `buildPythonPackage` actually does. I created a faux-pandas package by jury-rigging the expression for `pandas` in `python-packages.nix`. I made an empty folder and dropped this `default.nix` in there:

```nix
with import <nixpkgs> {};

let modules = python26.modules; in

buildPythonPackage rec {
  name = "pandas-0.15.0";

  src = pkgs.fetchurl {
    url = "https://pypi.python.org/packages/source/p/pandas/${name}.tar.gz";
    sha256 = "1w3wjnn3v37hf3hrd24lfgk6vpykarv9mihhpcfq6y7rg586bgjk";
  };

  buildInputs = with pkgs.python27Packages; [ nose ];
  propagatedBuildInputs = with pkgs.python27Packages; [ dateutil numpy pytz modules.sqlite3 ];

  # Tests require networking to pass
  doCheck = false;

  meta = {
    homepage = "http://pandas.pydata.org/";
    description = "Python Data Analysis Library";
    license = stdenv.lib.licenses.bsd3;
    maintainers = [ stdenv.lib.maintainers.raskin ];
    platforms = stdenv.lib.platforms.linux;
  };
}
```

And a similar, though different, thing occurs. Now, when I run `nix-build`, I get a `result` folder which contains what I'd expect:

```
pandas-test> ls result/lib/python2.7/site-packages
pandas  pandas-0.15.0-py2.7.egg-info  python2.7-pandas-0.15.0-nix-python-propagated-native-build-inputs.pth
pandas-test> cat result/lib/python2.7/site-packages/python2.7-pandas-0.15.0-nix-python-propagated-native-build-inputs.pth 
/nix/store/qqga4klc1pz4gnr2js1fw8714br601g8-python2.7-dateutil-2.2/lib/python2.7/site-packages
/nix/store/zq7p7shxc90vnd1fs105xp3kyc87n6fn-python2.7-numpy-1.8.2/lib/python2.7/site-packages
/nix/store/v7f224cq34m9ff5a705wvbw0kgjm16sl-python2.7-pytz-2013.9/lib/python2.7/site-packages
/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/site-packages
```

OK, so great right? Except:

```
pandas-test> nix-shell --pure

[nix-shell:~/workspace/nix/pandas-test]$ python
Python 2.7.9 (default, Jan 01 1970, 00:00:01) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pandas
>>> 
```

Huh? Now I can't even import `pandas` when I've activated the shell! What's going on here? What exactly does `buildPythonPackage` do, and what's the difference between `nix-build` and `nix-shell`? Why in my earlier `foo` example did the path to `foo` get added to my `$PYTHONPATH`, while that *didn't* happen with `pandas`?

**Comment by lethalman** [comment]
You are misunderstanding nix-shell.

**Comment by adnelson** [comment]
@lethalman I'm certain that I'm misunderstanding nix-shell (hopefully I'll learn that better soon), but even considering that, why then am I able to do import `foo` when I run `nix-shell` in my earlier example?

**Comment by domenkozar** [comment]
If you do `cd foo` and then `nix-shell`, this should work. This needs to be fixed or documented properly.

**Comment by adnelson** [comment]
I'm not sure what you mean: in the steps I posted about I was `cd`'d into `foo` before running `nix-shell`. But the main issue is that I can't get the paths from the `foo` package to make their way into the environment when `bar` gets built. Even though `bar/default.nix` references `../foo` in its `buildInputs`, and though doing a `nix-build` in `foo` produces a `lib` folder containing the `foo` module, the path to this folder isn't being added to `PATH` or `PYTHONPATH`.

**Comment by adnelson** [comment]
Just to expand a bit: if I do `nix-build` in the `foo` directory it produces a `result` with the following structure:

```
foo> tree result
result
├── lib
│   └── python2.7
│       └── site-packages
│           ├── foo
│           │   ├── foo.py
│           │   ├── foo.pyc
│           │   ├── __init__.py
│           │   └── __init__.pyc
│           ├── foo-0.0.1-py2.7.egg-info
│           │   ├── dependency_links.txt
│           │   ├── PKG-INFO
│           │   ├── SOURCES.txt
│           │   └── top_level.txt
│           └── python2.7-foo-nix-python-propagated-native-build-inputs.pth
└── nix-support
    └── propagated-native-build-inputs

6 directories, 10 files
```

So, it clearly seems to be *building* the package correctly. However, doing a `nix-shell --pure` in the `bar` directory produces an environment which does not contain a reference to `foo`.

**Comment by adnelson** [comment]
I should add that when adding a console script to `bar`, and installing the package with `nix-env -i`, the script which wraps the call to the `bar` package's console script does not mention the `foo` package at all. Even though it does seem to be building `foo`!

**Comment by domenkozar** [comment]
@adnelson thanks for so much debugging info. Would be easy to have a reproducible git checkout, but I think following should help:

Change the line `buildInputs = [ ../foo ];` to `buildInputs = [ (import ../foo) ];`

**Comment by adnelson** [comment]
Yay!! That worked :) Can you explain the difference? What does `import x` change versus just `x`?

**Comment by joachifm** [comment]
`./foo` is a path to a file named foo, `import ./foo` evaluates the expression contained within it.

**Comment by adnelson** [comment]
Awesome! Thanks a ton.
