### ISSUE TITLE
Packaged versions of Python modules hypothesis and typing are incompatible

### ISSUE THREAD

**Issue by exarkun** [NixOS/nixpkgs#70431]
**Describe the bug**

The Python package "Hypothesis" *optionally* uses the `typing` module.  If `typing` is unavailable it falls back to some dumber behavior but if it is found, it tries to use it.  However, it is incompatible with the version in nixpkgs.  This completely breaks Hypothesis if Hypothesis happens to be used when `typing` is installed (which may be hard to avoid if it is a dependency of another Python package).

**To Reproduce**

```
$ git -C /home/exarkun/Work/nixpkgs rev-parse HEAD
6b899cf083a23191b19520374b6418a50b1c432a

$ nix-shell -I nixpkgs=/home/exarkun/Work/nixpkgs -p 'python.withPackages (ps: [ ps.hypothesis ps.typing ps.enum34 ])' --run 'python -c "import hypothesis"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/7m2k8y7dww4km9ibwknzg1k6l5qyr8ig-python-2.7.16-env/lib/python2.7/site-packages/hypothesis/__init__.py", line 26, in <module>
    from hypothesis._settings import settings, Verbosity, Phase, HealthCheck, unlimited
  File "/nix/store/7m2k8y7dww4km9ibwknzg1k6l5qyr8ig-python-2.7.16-env/lib/python2.7/site-packages/hypothesis/_settings.py", line 40, in <module>
    from hypothesis.internal.compat import string_types
  File "/nix/store/7m2k8y7dww4km9ibwknzg1k6l5qyr8ig-python-2.7.16-env/lib/python2.7/site-packages/hypothesis/internal/compat.py", line 302, in <module>
    typing_root_type = (typing._Final, typing._GenericAlias)  # type: ignore
AttributeError: 'module' object has no attribute '_GenericAlias'
```

**Expected behavior**

The `hypothesis` module should import without error and provide its useful testing functionality.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - python27Packages.hypothesis
  - python27Packages.typing
# a list of nixos modules affected by the problem
module:
```

**Comment by exarkun** [comment]
It looks like this might be fixed by a newer Hypothesis: https://github.com/HypothesisWorks/hypothesis/issues/2014

**Comment by exarkun** [comment]
The newer Hypothesis requires a newer attrs (19.2.0) and breaks the pytest test suite somehow, fwiw.

**Comment by FRidh** [comment]
Is that only on master or also 19.09?

**Comment by exarkun** [comment]
It looks like it affects 19.09 as well:

```
$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/release-19.09.tar.gz -p 'python.withPackages (ps: [ ps.hypothesis ps.typing ps.enum34 ])' --run 'python -c "import hypothesis"'
unpacking 'https://github.com/NixOS/nixpkgs/archive/release-19.09.tar.gz'...
these derivations will be built:
  /nix/store/l1p2zwmfy77pq59hiiq7p39wa67ih2mz-python-2.7.16-env.drv
building '/nix/store/l1p2zwmfy77pq59hiiq7p39wa67ih2mz-python-2.7.16-env.drv'...
created 687 symlinks in user environment
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/8m9k8hqwm9xn756bvn56zvijw58jccij-python-2.7.16-env/lib/python2.7/site-packages/hypothesis/__init__.py", line 26, in <module>
    from hypothesis._settings import settings, Verbosity, Phase, HealthCheck, unlimited
  File "/nix/store/8m9k8hqwm9xn756bvn56zvijw58jccij-python-2.7.16-env/lib/python2.7/site-packages/hypothesis/_settings.py", line 40, in <module>
    from hypothesis.internal.compat import string_types
  File "/nix/store/8m9k8hqwm9xn756bvn56zvijw58jccij-python-2.7.16-env/lib/python2.7/site-packages/hypothesis/internal/compat.py", line 302, in <module>
    typing_root_type = (typing._Final, typing._GenericAlias)  # type: ignore
AttributeError: 'module' object has no attribute '_GenericAlias'
```

**Comment by jonringer** [comment]
this is bumped in staging, and should land in master.... soon-ish

**Comment by davidak** [comment]
I can't reproduce this issue on master.

```
[davidak@ethmoid:~/code/nixpkgs]$ nix-shell -I nixpkgs=/home/davidak/code/nixpkgs -p 'python.withPackages (ps: [ ps.hypothesis ps.typing ps.enum34 ])' --run 'python -c "import hypothesis"'
these derivations will be built:
  /nix/store/623xqggi7bcbkr5zh70gwhaq8a8gcpvf-python-2.7.17-env.drv
these paths will be fetched (0.74 MiB download, 4.42 MiB unpacked):
  /nix/store/7lmp0d0jl5iyg38pma64jy1d8azb4gr2-python2.7-attrs-19.3.0
  /nix/store/7lxlx7gpc3caxhw0qsvnhcr39fg10mdh-python2.7-coverage-4.5.4
  /nix/store/kmzigdidq84lhrkwgm435m62x72xqvxh-bash-interactive-4.4-p23-dev
  /nix/store/ni0v98pj8j0nxqk6s1yfddmm4m4pg2lv-python2.7-typing-3.7.4.1
  /nix/store/nk08da19w53ak5ymn0avcnd0szb3a332-python2.7-enum34-1.1.6
  /nix/store/z00r5g10hpw3ykqd3ng4rz9dzrf1hga9-python2.7-hypothesis-4.41.0
copying path '/nix/store/kmzigdidq84lhrkwgm435m62x72xqvxh-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/7lxlx7gpc3caxhw0qsvnhcr39fg10mdh-python2.7-coverage-4.5.4' from 'https://cache.nixos.org'...
copying path '/nix/store/nk08da19w53ak5ymn0avcnd0szb3a332-python2.7-enum34-1.1.6' from 'https://cache.nixos.org'...
copying path '/nix/store/7lmp0d0jl5iyg38pma64jy1d8azb4gr2-python2.7-attrs-19.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/ni0v98pj8j0nxqk6s1yfddmm4m4pg2lv-python2.7-typing-3.7.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/z00r5g10hpw3ykqd3ng4rz9dzrf1hga9-python2.7-hypothesis-4.41.0' from 'https://cache.nixos.org'...
building '/nix/store/623xqggi7bcbkr5zh70gwhaq8a8gcpvf-python-2.7.17-env.drv'...
created 687 symlinks in user environment
```

Keep in mind that python 2.7 will be deprecated in 28 days! https://pythonclock.org/

Also no issue with python 3.

`nix-shell -I nixpkgs=/home/davidak/code/nixpkgs -p 'python3.withPackages (ps: [ ps.hypothesis ps.typing ps.enum34 ])' --run 'python -c "import hypothesis"'`

**Comment by exarkun** [comment]
Great.
