### ISSUE TITLE
darwin: gpgme build broken

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#70996]
While reviewing #70990 I noticed, the bug on a downstream dependency

**Describe the bug**
tries to do a dlopen, and can't find the dynamic library.

**Expected behavior**
Not crash.

**Additional context**
<details> <summary> Fail log </summary>

```
Traceback (most recent call last):
  File "./final.py", line 24, in <module>
    import support
  File "/private/tmp/nix-build-gpgme-1.13.1.drv-0/gpgme-1.13.1/lang/python/tests/support.py", line 27, in <module>
    import gpg
  File "/private/tmp/nix-build-gpgme-1.13.1.drv-0/gpgme-1.13.1/lang/python/python3.7-gpg/lib.macosx-10.6-x86_64-3.7/gpg/__init__.py", line 123, in <module>
    from . import core
  File "/private/tmp/nix-build-gpgme-1.13.1.drv-0/gpgme-1.13.1/lang/python/python3.7-gpg/lib.macosx-10.6-x86_64-3.7/gpg/core.py", line 10, in <module>
    from . import gpgme
  File "/private/tmp/nix-build-gpgme-1.13.1.drv-0/gpgme-1.13.1/lang/python/python3.7-gpg/lib.macosx-10.6-x86_64-3.7/gpg/gpgme.py", line 28, in <module>
    _gpgme = swig_import_helper()
  File "/private/tmp/nix-build-gpgme-1.13.1.drv-0/gpgme-1.13.1/lang/python/python3.7-gpg/lib.macosx-10.6-x86_64-3.7/gpg/gpgme.py", line 24, in swig_import_helper
    _mod = imp.load_module('_gpgme', fp, pathname, description)
  File "/nix/store/611gq7s9s11w5ri95fbq2adi9ifrhkmn-python3-3.7.4/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/nix/store/611gq7s9s11w5ri95fbq2adi9ifrhkmn-python3-3.7.4/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/private/tmp/nix-build-gpgme-1.13.1.drv-0/gpgme-1.13.1/lang/python/python3.7-gpg/lib.macosx-10.6-x86_64-3.7/gpg/_gpgme.cpython-37m-darwin.so, 2): Library not loaded: /nix/store/95ksx1ywkpp1id8k3xqp9x219r0fjj0k-gpgme-1.13.1/lib/libgpgme.11.dylib
  Referenced from: /private/tmp/nix-build-gpgme-1.13.1.drv-0/gpgme-1.13.1/lang/python/python3.7-gpg/lib.macosx-10.6-x86_64-3.7/gpg/_gpgme.cpython-37m-darwin.so
  Reason: image not found
Running tests using /nix/store/611gq7s9s11w5ri95fbq2adi9ifrhkmn-python3-3.7.4/bin/python3.7 (3.7)...
FAIL: initial.py
FAIL: t-wrapper.py
FAIL: t-callbacks.py
FAIL: t-data.py
FAIL: t-encrypt.py
FAIL: t-encrypt-sym.py
FAIL: t-encrypt-sign.py
FAIL: t-sign.py
FAIL: t-signers.py
FAIL: t-decrypt.py
FAIL: t-verify.py
FAIL: t-decrypt-verify.py
FAIL: t-sig-notation.py
FAIL: t-export.py
FAIL: t-import.py
FAIL: t-trustlist.py
FAIL: t-edit.py
FAIL: t-keylist.py
FAIL: t-keylist-from-data.py
FAIL: t-wait.py
FAIL: t-encrypt-large.py
FAIL: t-file-name.py
FAIL: t-idiomatic.py
FAIL: t-protocol-assuan.py
FAIL: t-quick-key-creation.py
FAIL: t-quick-subkey-creation.py
FAIL: t-quick-key-manipulation.py
FAIL: t-quick-key-signing.py
FAIL: final.py
29 tests run, 0 succeeded, 29 failed, 0 skipped.
make[3]: *** [Makefile:613: xcheck] Error 29
make[3]: Leaving directory '/private/tmp/nix-build-gpgme-1.13.1.drv-0/gpgme-1.13.1/lang/python/tests'
make[2]: *** [Makefile:472: check-recursive] Error 1
make[2]: Leaving directory '/private/tmp/nix-build-gpgme-1.13.1.drv-0/gpgme-1.13.1/lang/python'
make[1]: *** [Makefile:457: check-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-gpgme-1.13.1.drv-0/gpgme-1.13.1/lang'
make: *** [Makefile:534: check-recursive] Error 1
builder for '/nix/store/3hvi5bzsjb0x1wrdhwqazs8akpqk5qa5-gpgme-1.13.1.drv' failed with exit code 2
cannot build derivation '/nix/store/napnjdcs66z1sagmndjhipv3pjm69yp3-python3.7-pgpy-0.5.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ncwjx5g23yhak4vvvq4qzmzgnkscclq2-python3.7-srht-0.54.2.drv': 1 dependencies couldn't be built
```
</details>

full log: https://logs.nix.ci/?key=nixos/nixpkgs.70990&attempt_id=d202832a-d134-4823-b199-2a1e24e7e4c4

**Comment by flokli** [comment]
I'm not sure if I get this right. You meant `python3Packages.pgpy`, right?

The log however mentions `gpgme` failing to build…

**Comment by jonringer** [comment]
correct, however, I noticed it while reviewing the pgpy package. Got a new charger for my macbook, so i might look into this... I'ts just underpowered, so doing large builds is painful at best.

**Comment by jonringer** [comment]
not really sure if this is relevant anymore, and I've lost some interest in trying to maintain MacOS support

**Comment by kirelagin** [comment]
This is still relevant. The error I am getting is:

```
ImportError: dlopen(/private/tmp/nix-build-gpgme-1.13.1.drv-2/gpgme-1.13.1/lang/python/python3.7-gpg/lib.macosx-10.6-x86_64-3.7/gpg/_gpgme.cpython-37m-darwin.so, 2): Library not loaded: /nix/store/1cdj0q33r7vp79y6993ijpiwspml6hdn-gpgme-1.13.1/lib/libgpgme.11.dylib
  Referenced from: /private/tmp/nix-build-gpgme-1.13.1.drv-2/gpgme-1.13.1/lang/python/python3.7-gpg/lib.macosx-10.6-x86_64-3.7/gpg/_gpgme.cpython-37m-darwin.so
  Reason: image not found
```

In other words, tests are trying to load the library from `$out`, but it’s just the test phase, so the library is still not there.

**Comment by kirelagin** [comment]
The problem is that the test invocation includes `LD_LIBRARY_PATH="../../../src/.libs:"`, thus it works on Linux.
