### ISSUE TITLE
Kazam package broken on unstable

### ISSUE THREAD

**Issue by madhukar93** [NixOS/nixpkgs#71031]
kazam package is broken. It does not start after installation. Looks like missing python3.7 dependency. Seems like a regression of #57660

```
$ nix-shell -p kazam
$ kazam
Traceback (most recent call last):
  File "/nix/store/bqjm7rv0bzsf6vb4r46947rai7hf130c-python3.7-pygobject-3.32.1/lib/python3.7/site-packages/gi/importer.py", line 138, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/nix/store/bqjm7rv0bzsf6vb4r46947rai7hf130c-python3.7-pygobject-3.32.1/lib/python3.7/site-packages/gi/module.py", line 265, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/nix/store/bqjm7rv0bzsf6vb4r46947rai7hf130c-python3.7-pygobject-3.32.1/lib/python3.7/site-packages/gi/module.py", line 117, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Typelib file for namespace 'Pango', version '1.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/9bxmnfv8xxxay00kgab3df7gbs2vzbh2-kazam-1.4.5/bin/..kazam-wrapped-wrapped", line 33, in <module>
    from gi.repository import Gtk
  File "/nix/store/bqjm7rv0bzsf6vb4r46947rai7hf130c-python3.7-pygobject-3.32.1/lib/python3.7/site-packages/gi/importer.py", line 140, in load_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'Pango', version '1.0' not found
```

**Additional context**

**Metadata**
nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.78, NixOS, 20.03pre196586.b943338ea58 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre196586.b943338ea58, home-manager, nixos-hardware"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
This actually a regression from `strictDeps` being enabled in `buildPythonPackage`.
See #56943, fixes are like https://github.com/NixOS/nixpkgs/commit/a203bc741e59fd54475aaa0327acc08efde6a444.

**Comment by madhukar93** [comment]
thanks, will try to send in a PR

**Comment by worldofpeace** [comment]
Hmm, I did try fixing this briefly and it appeared it had more issues than this particular one.
Perhaps an update may improve the situation.

**Comment by madhukar93** [comment]
Then it is probably beyond my abilities to fix :grimacing: 
What sort of update?

**Comment by worldofpeace** [comment]
The issue I ran into was 
* https://github.com/hzbd/kazam/issues/20#issuecomment-449975842

Fix was https://github.com/hzbd/kazam/pull/21/, but it appears this tool is abandoned
* https://aur.archlinux.org/packages/kazam#comment-675562

And I don't particularly have patience for abandonware in nixpkgs, especially maintaining them.

**Comment by thorstenweber83** [comment]
@madhukar93 
kazam is now fixed on master.
