### ISSUE TITLE
azure-cli is broken on 19.09

### ISSUE THREAD

**Issue by razvan-flavius-panda** [NixOS/nixpkgs#71096]
**To Reproduce**

* Use following configuration.nix: https://gist.github.com/razvan-flavius-panda/23f894954377548a0ac523d0e808b7b5
* Run: `sudo nixos-rebuild switch --upgrade`
* Getting following error:

```shell
In file included from /nix/store/9xhmj7mkccaa7w2pkq5927xdp0i2jx7d-node-sources/src/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/nix/store/9xhmj7mkccaa7w2pkq5927xdp0i2jx7d-node-sources/deps/v8/include/v8.h:3348:37: note: candidate: 'v8::Maybe<bool> v8::Object::SetAccessor(v8::Local<v8::Context>, v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::MaybeLocal<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType)'
   V8_WARN_UNUSED_RESULT Maybe<bool> SetAccessor(
                                     ^~~~~~~~~~~
/nix/store/9xhmj7mkccaa7w2pkq5927xdp0i2jx7d-node-sources/deps/v8/include/v8.h:3348:37: note:   no known conversion for argument 2 from 'uni::FunctionType(v8::Local<v8::String>, const GetterCallbackInfo&)' {aka 'void(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&)'} to 'v8::Local<v8::Name>'
../src/fibers.cc:795:84: error: no matching function for call to 'v8::Function::SetAccessor(v8::Handle<v8::String>, uni::FunctionType (&)(v8::Local<v8::String>, const GetterCallbackInfo&))'
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                                                                                    ^
In file included from /nix/store/9xhmj7mkccaa7w2pkq5927xdp0i2jx7d-node-sources/src/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/nix/store/9xhmj7mkccaa7w2pkq5927xdp0i2jx7d-node-sources/deps/v8/include/v8.h:3348:37: note: candidate: 'v8::Maybe<bool> v8::Object::SetAccessor(v8::Local<v8::Context>, v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::MaybeLocal<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType)'
   V8_WARN_UNUSED_RESULT Maybe<bool> SetAccessor(
                                     ^~~~~~~~~~~
/nix/store/9xhmj7mkccaa7w2pkq5927xdp0i2jx7d-node-sources/deps/v8/include/v8.h:3348:37: note:   candidate expects 8 arguments, 2 provided
In file included from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
../src/fibers.cc: At global scope:
/nix/store/9xhmj7mkccaa7w2pkq5927xdp0i2jx7d-node-sources/src/node.h:573:43: warning: cast between incompatible function types from 'void (*)(v8::Handle<v8::Object>)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/nix/store/9xhmj7mkccaa7w2pkq5927xdp0i2jx7d-node-sources/src/node.h:607:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/fibers.cc:829:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(fibers, init)
 ^~~~~~~~~~~
make: *** [fibers.target.mk:108: Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/nix/store/h1ir0zz2ql2z623y5px1z1yk3ln9h8zm-node-azure-cli-0.10.20/lib/node_modules/azure-cli/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nix/store/az7ba381fqnscaddhsahnqv0rds2ikmk-nodejs-10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.75
gyp ERR! command "/nix/store/az7ba381fqnscaddhsahnqv0rds2ikmk-nodejs-10.16.0/bin/node" "/nix/store/az7ba381fqnscaddhsahnqv0rds2ikmk-nodejs-10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /nix/store/h1ir0zz2ql2z623y5px1z1yk3ln9h8zm-node-azure-cli-0.10.20/lib/node_modules/azure-cli/node_modules/fibers
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2019-10-13T22_12_29_012Z-debug.log
[ 9 of 16] Compiling Network.WebSockets.Protocol ( src/Network/WebSockets/Protocol.hs, dist/build/Network/WebSockets/Protocol.p_o )
builder for '/nix/store/7lb1phyrf62scp1v0950f47vm51cl1l4-node-azure-cli-0.10.20.drv' failed with exit code 1
cannot build derivation '/nix/store/5v1ylyyz1jmwd2acdbqhi4gpry0bi5ib-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/bmq6fm857xrz7iphd9gmrqcizv05l9j9-nixos-system-nixos-19.09.789.7952807791d.drv': 1 dependencies couldn't be built
error: build of '/nix/store/bmq6fm857xrz7iphd9gmrqcizv05l9j9-nixos-system-nixos-19.09.789.7952807791d.drv' failed
```

**Expected behavior**

Expecting it to work.

**Metadata**

```
- system: `"x86_64-linux"`
 - host os: `Linux 4.19.75, NixOS, 19.03.173553.6420e2649fa (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09.789.7952807791d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by razvan-flavius-panda** [comment]
There was a build issue with `azure-cli` not building on 19.09. Commenting it out, and other stuff allowed the upgrade to succeed.

**Comment by flokli** [comment]
https://www.npmjs.com/package/azure-cli warns pretty loudly that one should migrate to Azure CLI 2.0 from https://github.com/Azure/azure-cli, and there's also https://github.com/NixOS/nixpkgs/issues/39638 asking for removal.

As the old node based `azure-cli` is entirely broken by now, I opened #71170 to remove it.

Work on adding version 2 is happening in https://github.com/NixOS/nixpkgs/issues/40073.

**Comment by jonringer** [comment]
I'll give 2.0 a go when I get home, it's just going to be a lot of python overrides :(

**Comment by jonringer** [comment]
#71797 has been merged, not sure if I want to make a backport though.... it's a lot of commits
