### ISSUE TITLE
pythonPackages.subliminal fails with `No module named 'pkg_resources'` in 19.09

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#71117]
**Describe the bug**

Subliminal (there may be other python packages) doesn't run:
```
Traceback (most recent call last):
  File "/nix/store/2kjlay7b4zkx077643xk3lcbhx3817yg-python3.7-subliminal-2.0.5/bin/.subliminal-wrapped", line 7, in <module>
    from subliminal.cli import subliminal
  File "/nix/store/2kjlay7b4zkx077643xk3lcbhx3817yg-python3.7-subliminal-2.0.5/lib/python3.7/site-packages/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/nix/store/2kjlay7b4zkx077643xk3lcbhx3817yg-python3.7-subliminal-2.0.5/lib/python3.7/site-packages/subliminal/core.py", line 12, in <module>
    from babelfish import Language, LanguageReverseError
  File "/nix/store/ssgfwd3d6npiq7z42ljzzz1x7fp2chaj-python3.7-babelfish-0.5.5/lib/python3.7/site-packages/babelfish/__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/nix/store/ssgfwd3d6npiq7z42ljzzz1x7fp2chaj-python3.7-babelfish-0.5.5/lib/python3.7/site-packages/babelfish/converters/__init__.py", line 6, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
ModuleNotFoundError: No module named 'pkg_resources'
```
However the same package from master does.

**To Reproduce**
1. git checkout release-19.09
2. nix build -f. python3packages.subliminal
3. ./result/bin/subliminal

Maintainer information: no maintainer
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- python2packages.subliminal
- python3packages.subliminal
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
fixed with 6c007da4e669c288ff1c8cea7f0348fe60d05a1d

**Comment by rnhmjoj** [comment]
Thank you. What happened anyway? Was setuptools removed from the enironment by default?

**Comment by FRidh** [comment]
Yes, see https://github.com/NixOS/nixpkgs/pull/68314
