### ISSUE TITLE
Installation failure on nixos-graphical-19.09.840.8bf142e001b-x86_64-linux.iso

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#71425]
**Describe the bug**
Can install NixOs with the latest iso image nixos-graphical-19.09.840.8bf142e001b-x86_64-linux.iso
Getting the error on basic config
```
[root@nixos:/home/nixos]# nixos-install              
building the configuration in /mnt/etc/nixos/configuration.nix...                          
[195 built, 312 copied (1412.3 MiB), 80.6 MiB DL]                                                        
copying channel...                                  
installing the boot loader...                                                                            
setting up /etc...                                  
Initializing machine ID from random generator.                                                           
Created "/boot/EFI".                                
Created "/boot/EFI/systemd".           
Created "/boot/EFI/BOOT".                                                                                
Created "/boot/loader".                             
Created "/boot/loader/entries".
Created "/boot/EFI/Linux".                          
Copied "/nix/store/z21pvaij484h1bha7wy2drx931v4d53g-systemd-243/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/nix/store/z21pvaij484h1bha7wy2drx931v4d53g-systemd-243/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
Created "/boot/b018a4546579407cb821837710d25847".                                                        
Random seed file /boot/loader/random-seed successfully written (512 bytes).
Failed to set LoaderSystemToken EFI variable: No space left on device
Traceback (most recent call last):                                                                       
  File "/nix/store/hdq0kfajwgvyqc6v1fnaklmkiziasq5l-systemd-boot-builder.py", line 240, in <module>
    main()                                                                                               
  File "/nix/store/hdq0kfajwgvyqc6v1fnaklmkiziasq5l-systemd-boot-builder.py", line 197, in main                                                                                                                    
    subprocess.check_call(["/nix/store/z21pvaij484h1bha7wy2drx931v4d53g-systemd-243/bin/bootctl", "--path=/boot", "install"])
  File "/nix/store/dxk1vqyhfmjk2ivxcrfw85k8kqsrzhhg-python3-3.7.4/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)                                                                                                                                                                         
subprocess.CalledProcessError: Command '['/nix/store/z21pvaij484h1bha7wy2drx931v4d53g-systemd-243/bin/bootctl', '--path=/boot', 'install']' returned non-zero exit status 1.
```
Error on second run for nixos-install
```
[root@nixos:/home/nixos]# nixos-install
building the configuration in /mnt/etc/nixos/configuration.nix...
copying channel...                                  
installing the boot loader...
setting up /etc...                                  
Copied "/nix/store/z21pvaij484h1bha7wy2drx931v4d53g-systemd-243/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/nix/store/z21pvaij484h1bha7wy2drx931v4d53g-systemd-243/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
Random seed file /boot/loader/random-seed successfully written (512 bytes).
Failed to test system token validity: No data available
Traceback (most recent call last):
  File "/nix/store/hdq0kfajwgvyqc6v1fnaklmkiziasq5l-systemd-boot-builder.py", line 240, in <module>
    main()                                          
  File "/nix/store/hdq0kfajwgvyqc6v1fnaklmkiziasq5l-systemd-boot-builder.py", line 197, in main
    subprocess.check_call(["/nix/store/z21pvaij484h1bha7wy2drx931v4d53g-systemd-243/bin/bootctl", "--path=/boot", "install"])
  File "/nix/store/dxk1vqyhfmjk2ivxcrfw85k8kqsrzhhg-python3-3.7.4/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/z21pvaij484h1bha7wy2drx931v4d53g-systemd-243/bin/bootctl', '--path=/boot', 'install']' returned non-zero exit status 1.
```

**To Reproduce**
Installation on Lenovo Laptop P53
1. Configuration used with luks encypt
```
{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub.enableCryptodisk = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;

   networking.hostName = "nixos"; # Define your hostname.
  networking.useDHCP = false;
  networking.interfaces.enp0s31f6.useDHCP = true;
  # Enable the OpenSSH daemon.
   services.openssh.enable = true;
```
Storage

```
[root@nixos:/home/nixos]# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
loop0         7:0    0 495.8M  1 loop  /nix/.ro-store
sda           8:0    1  58.6G  0 disk  
├─sda1        8:1    1   539M  0 part  /iso
└─sda2        8:2    1    21M  0 part  
nvme0n1     259:0    0   477G  0 disk  
├─nvme0n1p1 259:2    0   260M  0 part  
├─nvme0n1p2 259:3    0    16M  0 part  
├─nvme0n1p3 259:4    0 475.7G  0 part  
└─nvme0n1p4 259:5    0  1000M  0 part  
nvme1n1     259:1    0   477G  0 disk  
├─nvme1n1p1 259:6    0   511M  0 part  /mnt/boot
└─nvme1n1p2 259:8    0 476.5G  0 part  
  └─crypted 254:0    0 476.4G  0 crypt /mnt
```

**Expected behavior**
Complete installation

**Additional context**
Previously nixos was installed with previouse version of 19.09

**Comment by mudrii** [comment]
I noticed if set
  boot.loader.efi.canTouchEfiVariables = false;

Installation is successful.

**Comment by mudrii** [comment]
Not relevant anymore

**Comment by JohnAZoidberg** [comment]
> I noticed if set
> boot.loader.efi.canTouchEfiVariables = false;
> 
> Installation is successful.

Thanks! Worked for me, too.

**Comment by cdepillabout** [comment]
I also ran into this problem when installing 20.09.

The workaround of setting `boot.loader.efi.canTouchEfiVariables = false` worked for me as well.
