### ISSUE TITLE
sweethome3d fatal error on startup

### ISSUE THREAD

**Issue by emptyflask** [NixOS/nixpkgs#71752]
**Describe the bug**
The app loads but immediately shows a modal window: `Sweet Home 3D will exit now because a fatal error in the 3D rendering system of you computer` and exits.

It seems some users had a [workaround](http://www.sweethome3d.com/support/forum/viewthread_thread,8532;jsessionid=DDCAFBFE460FEBE15941D0E4404ED46E) for this in 2018, but I don't know if this is still accurate.

**Additional context**
```
com.jogamp.opengl.GLException: J3D-Renderer-1: Error making temp context(1) current: display 0x7ff28821f570, context 0x7ff2884a04f8, drawable X11OnscreenGLXDrawable[Realized true,
	Factory   jogamp.opengl.x11.glx.X11GLXDrawableFactory@6542ec49,
	Handle    0x7c000a3,
	Surface   JAWTWindow[0x6631da3c][JVM version: 1.8.0_222 (1.8.0 update 222)
JAWT version: 0x10004, CA_LAYER: false, isLayeredSurface false, bounds [ 0 / 0  792 x 112 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], pixelScale 1.0x1.0, shallUseOffscreenLayer false, isOffscreenLayerSurface false, attachedSurfaceLayer 0x0, windowHandle 0x7c000a3, surfaceHandle 0x7c000a3, bounds [ 0 / 0  792 x 112 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], window [0/0 792x112], pixels[scale 1.0, 1.0 -> 792x112], visible true, lockedExt false,
	config AWTGraphicsConfiguration[AWTGraphicsScreen[AWTGraphicsDevice[type .awt, connection :0.0, unitID 0, awtDevice X11GraphicsDevice[screen=0], handle 0x0], idx 0],
	chosen    GLCaps[glx vid 0x28, fbc 0xaf: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	requested GLCaps[rgba 5/5/5/1, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x28],
	encapsulated X11GLXGraphicsConfiguration[X11GraphicsScreen[X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x7ff28821f570, owner true, JAWTToolkitLock[obj 0x27f04d7, isOwner true, <19570680, 6b859147>[count 1, qsz 0, owner <J3D-Renderer-1>]]], idx 0], visualID 0x28, fbConfigID 0xaf,
	requested GLCaps[rgba 5/5/5/1, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	chosen    GLCaps[glx vid 0x28, fbc 0xaf: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]]]],
	awtComponent com.eteks.sweethome3d.j3d.Component3DManager$ObservedCanvas3D[canvas2,0,0,792x112],
	surfaceLock <1c351260, 37ee7406>[count 1, qsz 0, owner <J3D-Renderer-1>]]]
	at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:393)
	at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
	at javax.media.j3d.JoglPipeline.createNewContext(JoglPipeline.java:6411)
	at javax.media.j3d.Canvas3D.createNewContext(Canvas3D.java:4612)
	at javax.media.j3d.Canvas3D.createNewContext(Canvas3D.java:2386)
	at javax.media.j3d.Renderer.doWork(Renderer.java:881)
	at javax.media.j3d.J3dThread.run(J3dThread.java:271)
Error in Java 3D : 3 Renderer: Error creating Canvas3D graphics contextX11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 2/2, reusable (open, marked uncloseable): 0, pending (open in creation order): 2)
X11Util: Open X11 Display Connections: 2
X11Util: Open[0]: NamedX11Display[:0, 0x7ff28802c850, refCount 1, unCloseable false]
X11Util: Open[1]: NamedX11Display[:0, 0x7ff28821f570, refCount 1, unCloseable false]
```

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.79, NixOS, 19.09.840.8bf142e001b (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(jon): `"home-manager-19.03, nixos-unstable-small-20.03pre197483.2bd4f8023bf"`
 - channels(root): `"nixos-19.09.840.8bf142e001b, nixos-unstable-20.03pre196836.1c40ee6fc44"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by schwen** [comment]
have/had same error. the workaroud you mentioned was the solution for me. 
as a quickfix just use 
`export JAVA_TOOL_OPTIONS="-Dcom.eteks.sweethome3d.j3d.useOffScreen3DView=true"`

**Comment by rendeko** [comment]
Confirming that this issue still exists, and that schwen's fix still works.

**Comment by twhitehead** [comment]
Still an issue. An alternative solution is to downgrade your reported OpenGL version as follows
```
MESA_GL_VERSION_OVERRIDE=3.0 sweethome3d
```
I tried a variety of versions and it seems sweethome3d of java's head explodes for reasons unclear if mesa reports an OpenGL version ≥ 3.1.

**Comment by WhittlesJr** [comment]
Can we not just add one of those env vars to the wrapper to resolve this issue?

**Comment by jkozak** [comment]
Still a problem, @schwen workaround still works

**Comment by eclairevoyant** [comment]
@WhittlesJr no, it doesn't appear to work on my end

**Comment by CutestNekoAqua** [comment]
can confirm! the workaround works here.
