### ISSUE TITLE
python2Packages.webtest fails to build

### ISSUE THREAD

**Issue by marzipankaiser** [NixOS/nixpkgs#71824]
**Describe the bug**
The build of python2.7 webtest fails.

**To Reproduce**
1. `nix-build -A python27Packages.webtest` in a commit starting from 90be4c2c7875c9487508d95b5c638d97e2903ada

**Expected behavior**
The package builds successfully

**Screenshots**
<details>
<summary>Build log</summary>

```
these derivations will be built:
  /nix/store/3szldn2krfsy4wxcj3z97qmh9ci075vf-python2.7-webtest-2.0.32.drv
building '/nix/store/3szldn2krfsy4wxcj3z97qmh9ci075vf-python2.7-webtest-2.0.32.drv'...
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing setuptools-check-hook
Using setuptoolsCheckPhase
unpacking sources
unpacking source archive /nix/store/qyybi976hg7ln7vv9ab0kg4lr3115721-WebTest-2.0.32.tar.gz
source root is WebTest-2.0.32
setting SOURCE_DATE_EPOCH to timestamp 1538727593 of file WebTest-2.0.32/setup.cfg
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/webtest
copying webtest/utils.py -> build/lib/webtest
copying webtest/sel.py -> build/lib/webtest
copying webtest/response.py -> build/lib/webtest
copying webtest/lint.py -> build/lib/webtest
copying webtest/http.py -> build/lib/webtest
copying webtest/forms.py -> build/lib/webtest
copying webtest/ext.py -> build/lib/webtest
copying webtest/debugapp.py -> build/lib/webtest
copying webtest/compat.py -> build/lib/webtest
copying webtest/app.py -> build/lib/webtest
copying webtest/__init__.py -> build/lib/webtest
running egg_info
writing requirements to WebTest.egg-info/requires.txt
writing WebTest.egg-info/PKG-INFO
writing top-level names to WebTest.egg-info/top_level.txt
writing dependency_links to WebTest.egg-info/dependency_links.txt
writing entry points to WebTest.egg-info/entry_points.txt
reading manifest file 'WebTest.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
writing manifest file 'WebTest.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/webtest
copying build/lib/webtest/__init__.py -> build/bdist.linux-x86_64/wheel/webtest
copying build/lib/webtest/app.py -> build/bdist.linux-x86_64/wheel/webtest
copying build/lib/webtest/compat.py -> build/bdist.linux-x86_64/wheel/webtest
copying build/lib/webtest/debugapp.py -> build/bdist.linux-x86_64/wheel/webtest
copying build/lib/webtest/ext.py -> build/bdist.linux-x86_64/wheel/webtest
copying build/lib/webtest/forms.py -> build/bdist.linux-x86_64/wheel/webtest
copying build/lib/webtest/http.py -> build/bdist.linux-x86_64/wheel/webtest
copying build/lib/webtest/lint.py -> build/bdist.linux-x86_64/wheel/webtest
copying build/lib/webtest/response.py -> build/bdist.linux-x86_64/wheel/webtest
copying build/lib/webtest/sel.py -> build/bdist.linux-x86_64/wheel/webtest
copying build/lib/webtest/utils.py -> build/bdist.linux-x86_64/wheel/webtest
running install_egg_info
Copying WebTest.egg-info to build/bdist.linux-x86_64/wheel/WebTest-2.0.32-py2.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/WebTest-2.0.32.dist-info/WHEEL
creating 'dist/WebTest-2.0.32-py2.py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'webtest/__init__.py'
adding 'webtest/app.py'
adding 'webtest/compat.py'
adding 'webtest/debugapp.py'
adding 'webtest/ext.py'
adding 'webtest/forms.py'
adding 'webtest/http.py'
adding 'webtest/lint.py'
adding 'webtest/response.py'
adding 'webtest/sel.py'
adding 'webtest/utils.py'
adding 'WebTest-2.0.32.dist-info/METADATA'
adding 'WebTest-2.0.32.dist-info/WHEEL'
adding 'WebTest-2.0.32.dist-info/entry_points.txt'
adding 'WebTest-2.0.32.dist-info/top_level.txt'
adding 'WebTest-2.0.32.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Finished executing setuptoolsInstallPhase
installing
Executing pipInstallPhase
/build/WebTest-2.0.32/dist /build/WebTest-2.0.32
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing ./WebTest-2.0.32-py2.py3-none-any.whl
Requirement already satisfied: WebOb>=1.2 in /nix/store/n05dfyc50ix789rx9766k0qy5lz27fcw-python2.7-WebOb-1.8.5/lib/python2.7/site-packages (from WebTest==2.0.32) (1.8.5)
Requirement already satisfied: six in /nix/store/c2xxvfvnbg8z6pqnjx34mdhkrvzsdpbf-python2.7-six-1.12.0/lib/python2.7/site-packages (from WebTest==2.0.32) (1.12.0)
Requirement already satisfied: beautifulsoup4 in /nix/store/ks8675h6vsrmwk3zqbn54sm02l20jl8s-python2.7-beautifulsoup4-4.7.1/lib/python2.7/site-packages (from WebTest==2.0.32) (4.7.1)
Requirement already satisfied: waitress>=0.8.5 in /nix/store/24lsqbid223n5gi276836y9c8pi20ybc-python2.7-waitress-1.2.1/lib/python2.7/site-packages (from WebTest==2.0.32) (1.2.1)
Requirement already satisfied: soupsieve>=1.2 in /nix/store/zywln1hx9xviv9dh0zlw2azc74mv4kw5-python2.7-soupsieve-1.7.3/lib/python2.7/site-packages (from beautifulsoup4->WebTest==2.0.32) (1.7.3)
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /nix/store/sfs0qc05giqqyjyq5lp068h9akc20zp0-python2.7-backports.functools_lru_cache-1.5/lib/python2.7/site-packages (from soupsieve>=1.2->beautifulsoup4->WebTest==2.0.32) (1.5)
Installing collected packages: WebTest
Successfully installed WebTest-2.0.32
/build/WebTest-2.0.32
Finished executing pipInstallPhase
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/m1vga13wpqsvqz9wshy3ncdlq1wwi7x7-python2.7-webtest-2.0.32
strip is /nix/store/cg0k49h66nkdqx6ccwnqr0i4q0fnfznc-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/m1vga13wpqsvqz9wshy3ncdlq1wwi7x7-python2.7-webtest-2.0.32/lib
patching script interpreter paths in /nix/store/m1vga13wpqsvqz9wshy3ncdlq1wwi7x7-python2.7-webtest-2.0.32
checking for references to /build/ in /nix/store/m1vga13wpqsvqz9wshy3ncdlq1wwi7x7-python2.7-webtest-2.0.32...
running install tests
no Makefile or custom buildPhase, doing nothing
pythonCatchConflictsPhase
pythonRemoveBinBytecodePhase
pythonImportsCheckPhase
Executing pythonImportsCheckPhase
setuptoolsCheckPhase
Executing setuptoolsCheckPhase
running test
running egg_info
writing requirements to WebTest.egg-info/requires.txt
writing WebTest.egg-info/PKG-INFO
writing top-level names to WebTest.egg-info/top_level.txt
writing dependency_links to WebTest.egg-info/dependency_links.txt
writing entry points to WebTest.egg-info/entry_points.txt
reading manifest file 'WebTest.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
writing manifest file 'WebTest.egg-info/SOURCES.txt'
running build_ext
/nix/store/laypqxl087hxhrr1zp7g7krxcyg3n0q4-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/config.py:264: RuntimeWarning: Option 'with-doctest' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
/nix/store/laypqxl087hxhrr1zp7g7krxcyg3n0q4-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/config.py:264: RuntimeWarning: Option 'doctest-extension' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
/nix/store/laypqxl087hxhrr1zp7g7krxcyg3n0q4-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/config.py:264: RuntimeWarning: Option 'doctest-fixtures' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
/nix/store/laypqxl087hxhrr1zp7g7krxcyg3n0q4-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/config.py:264: RuntimeWarning: Option 'cover-package' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
/nix/store/laypqxl087hxhrr1zp7g7krxcyg3n0q4-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/config.py:264: RuntimeWarning: Option 'doctest-options' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
/build/WebTest-2.0.32/tests/test_debugapp.py:112: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(False, "An AppError should be raised")
test_custom_headers (tests.test_app.TestApp) ... ok
test_encode_multipart (tests.test_app.TestApp) ... ok
test_encode_multipart_content_type (tests.test_app.TestApp) ... ok
test_encode_multipart_relative_to (tests.test_app.TestApp) ... ok
test_get_params (tests.test_app.TestApp) ... ok
test_patch (tests.test_app.TestApp) ... ok
test_request_with_testrequest (tests.test_app.TestApp) ... ok
test_app_error (tests.test_app.TestAppError) ... ok
test_app_error_misc (tests.test_app.TestAppError) ... ok
test_app_error_with_bytes_message (tests.test_app.TestAppError) ... ok
test_app_error_with_unicode (tests.test_app.TestAppError) ... ok
test_xhr_param_change_headers (tests.test_app.TestAppXhrParam) ... ok
test_cookie_policy (tests.test_app.TestCookies) ... ok
test_cookies_readonly (tests.test_app.TestCookies) ... ok
test_expires_cookies (tests.test_app.TestCookies) ... ok
test_http_cookie (tests.test_app.TestCookies) ... ok
test_http_localhost_cookie (tests.test_app.TestCookies) ... ok
test_preserves_cookies (tests.test_app.TestCookies) ... ok
test_secure_cookies (tests.test_app.TestCookies) ... ok
test_set_cookie (tests.test_app.TestCookies) ... ok
test_supports_providing_cookiejar (tests.test_app.TestCookies) ... ok
test_get_extra_environ (tests.test_app.TestEnviron) ... ok
test_post_extra_environ (tests.test_app.TestEnviron) ... ok
test_request_extra_environ (tests.test_app.TestEnviron) ... ok
test_field_order_is_across_all_fields (tests.test_app.TestFieldOrder) ... ok
test_post_with_file_upload (tests.test_app.TestFieldOrder) ... ok
test_submit_with_file_upload (tests.test_app.TestFieldOrder) ... ok
test_url_with_fragments (tests.test_app.TestFragments) ... ok
test_url_without_fragments (tests.test_app.TestFragments) ... ok
test_parser_features (tests.test_app.TestParserFeature) ... ok
test_paste_testing_variables (tests.test_app.TestPasteVariables) ... ok
test_paste_testing_variables_raises (tests.test_app.TestPasteVariables) ... ok
test_app_script_name (tests.test_app.TestScriptName) ... ok
test_script_name (tests.test_app.TestScriptName) ... ok
test_script_name_doesnt_match (tests.test_app.TestScriptName) ... ok
test_check_status_almost_asterisk (tests.test_app.TestStatus) ... ok
test_check_status_asterisk (tests.test_app.TestStatus) ... ok
test_check_status_none (tests.test_app.TestStatus) ... ok
test_check_status_tuple (tests.test_app.TestStatus) ... ok
test_check_status_with_custom_reason (tests.test_app.TestStatus) ... ok
test_proxy_with_environ (tests.test_app.TestWSGIProxy) ... ok
test_proxy_with_url (tests.test_app.TestWSGIProxy) ... ok
test_basic_authorization (tests.test_authorisation.TestAuthorization) ... ok
test_bearer_authorization (tests.test_authorisation.TestAuthorization) ... ok
test_invalid (tests.test_authorisation.TestAuthorization) ... ok
test_204 (tests.test_debugapp.TestTesting) ... /build/WebTest-2.0.32/webtest/lint.py:481: WSGIWarning: Content-Type header found in a 204 response, which not return content.
  WSGIWarning)
ok
test_303 (tests.test_debugapp.TestTesting) ... ok
test_404 (tests.test_debugapp.TestTesting) ... ok
test_app_error (tests.test_debugapp.TestTesting) ... ok
test_app_from_config_file (tests.test_debugapp.TestTesting) ... ERROR
test_bad_content_type (tests.test_debugapp.TestTesting) ... /build/WebTest-2.0.32/webtest/debugapp.py:77: UserWarning: Behavior of MultiDict.update() has changed and overwrites duplicate keys. Consider using .extend()
  resp.headers.update(headers)
ok
test_delete_params (tests.test_debugapp.TestTesting) ... ok
test_errors (tests.test_debugapp.TestTesting) ... ok
test_exception (tests.test_debugapp.TestTesting) ... ok
test_exception_repr (tests.test_debugapp.TestTesting) ... ok
test_fake_dict (tests.test_debugapp.TestTesting) ... ok
test_options (tests.test_debugapp.TestTesting) ... ok
test_post_params (tests.test_debugapp.TestTesting) ... ok
test_post_unicode (tests.test_debugapp.TestTesting) ... ok
test_post_unicode_body (tests.test_debugapp.TestTesting) ... ok
test_print_stderr (tests.test_debugapp.TestTesting) ... Response: 200 OK
Content-Type: text/plain; charset=utf-8
°C
Response: 200 OK
Content-Type: text/plain
��C
ok
test_put_params (tests.test_debugapp.TestTesting) ... ok
test_request_obj (tests.test_debugapp.TestTesting) ... ok
test_showbrowser (tests.test_debugapp.TestTesting) ... ok
test_testing (tests.test_debugapp.TestTesting) ... ok
test_url_class (tests.test_debugapp.TestTesting) ... ok
tests.test_debugapp.test_print_unicode ... °C
ok
test_raises (tests.test_ext.TestSelenium) ... ok
test_file_upload_binary (tests.test_forms.TestFileUpload) ... ok
test_file_upload_with_content_type (tests.test_forms.TestFileUpload) ... ok
test_file_upload_with_filename_and_contents (tests.test_forms.TestFileUpload) ... ok
test_file_upload_with_filename_only (tests.test_forms.TestFileUpload) ... ok
test_goto_upload_files (tests.test_forms.TestFileUpload) ... ok
test_invalid_types (tests.test_forms.TestFileUpload) ... ok
test_invalid_uploadfiles (tests.test_forms.TestFileUpload) ... ok
test_multiple_file_uploads_with_filename_and_contents (tests.test_forms.TestFileUpload) ... ok
test_no_uploads_error (tests.test_forms.TestFileUpload) ... ok
test_post_int (tests.test_forms.TestFileUpload) ... ok
test_post_upload_empty_files (tests.test_forms.TestFileUpload) ... ok
test_post_upload_files (tests.test_forms.TestFileUpload) ... ok
test_upload_invalid_content (tests.test_forms.TestFileUpload) ... ok
test_upload_without_file (tests.test_forms.TestFileUpload) ... ok
test_form_lint (tests.test_forms.TestFormLint) ... ok
test_button (tests.test_forms.TestForms) ... ok
test_button_submit (tests.test_forms.TestForms) ... ok
test_button_submit_by_index (tests.test_forms.TestForms) ... ok
test_button_submit_by_value (tests.test_forms.TestForms) ... ok
test_button_submit_by_value_and_index (tests.test_forms.TestForms) ... ok
test_button_value_if_submitted (tests.test_forms.TestForms) ... ok
test_force_select (tests.test_forms.TestForms) ... ok
test_form_select (tests.test_forms.TestForms) ... ok
test_get_field_by_index (tests.test_forms.TestForms) ... ok
test_get_non_exist_fields (tests.test_forms.TestForms) ... ok
test_get_non_exist_fields_with_default (tests.test_forms.TestForms) ... ok
test_get_unknown_field (tests.test_forms.TestForms) ... ok
test_repr (tests.test_forms.TestForms) ... ok
test_set_multiple_checkboxes (tests.test_forms.TestForms) ... ok
test_set_submit_field (tests.test_forms.TestForms) ... ok
test_the_bs_node_must_not_change (tests.test_forms.TestForms) ... ok
test_upload_fields (tests.test_forms.TestForms) ... ok
test_force_radio_input (tests.test_forms.TestInput) ... ok
test_input (tests.test_forms.TestInput) ... ok
test_input_no_default (tests.test_forms.TestInput) ... ok
test_input_unicode (tests.test_forms.TestInput) ... ok
test_radio_input_order (tests.test_forms.TestInput) ... ok
test_textarea_emptyfirstline (tests.test_forms.TestInput) ... ok
test_textarea_entities (tests.test_forms.TestInput) ... ok
test_no_form (tests.test_forms.TestResponseFormAttribute) ... ok
test_too_many_forms (tests.test_forms.TestResponseFormAttribute) ... ok
test_multiple_select (tests.test_forms.TestSelect) ... ok
test_multiple_select_forced_values (tests.test_forms.TestSelect) ... ok
test_multiple_select_no_default (tests.test_forms.TestSelect) ... ok
test_multiple_select_no_value (tests.test_forms.TestSelect) ... ok
test_multiple_select_reset_value (tests.test_forms.TestSelect) ... ok
test_select_no_value (tests.test_forms.TestSelect) ... ok
test_single_select (tests.test_forms.TestSelect) ... ok
test_single_select_forced_value (tests.test_forms.TestSelect) ... ok
test_single_select_no_default (tests.test_forms.TestSelect) ... ok
test_unicode_select (tests.test_forms.TestSelect) ... ok
test_shutdown_non_running (tests.test_http.TestBrokenServer) ... ok
test_no_server (tests.test_http.TestClient) ... ok
test_server (tests.test_http.TestServer) ... ok
test_wsgi_wrapper (tests.test_http.TestServer) ... ok
test_no_content (tests.test_lint.TestCheckContentType) ... ok
test_no_content_type (tests.test_lint.TestCheckContentType) ... ok
test_handles_native_strings_in_variables (tests.test_lint.TestCheckEnviron) ... ok
test_no_query_string (tests.test_lint.TestCheckEnviron) ... ok
test_no_valid_request (tests.test_lint.TestCheckEnviron) ... ok
test_header_bytes_name (tests.test_lint.TestCheckHeaders) ... SKIP: bytes is str in Python2
test_header_bytes_value (tests.test_lint.TestCheckHeaders) ... SKIP: bytes is str in Python2
test_header_non_latin1_name (tests.test_lint.TestCheckHeaders) ... ok
test_header_non_latin1_value (tests.test_lint.TestCheckHeaders) ... ok
test_header_unicode_name (tests.test_lint.TestCheckHeaders) ... ok
test_header_unicode_value (tests.test_lint.TestCheckHeaders) ... ok
test_dont_close (tests.test_lint.TestErrorWrapper) ... ok
test_flush (tests.test_lint.TestErrorWrapper) ... ok
test_writelines (tests.test_lint.TestErrorWrapper) ... ok
test_close (tests.test_lint.TestInputWrapper) ... ok
test_iter (tests.test_lint.TestInputWrapper) ... ok
test_read (tests.test_lint.TestInputWrapper) ... ok
test_readline (tests.test_lint.TestInputWrapper) ... ok
test_readlines (tests.test_lint.TestInputWrapper) ... ok
test_seek (tests.test_lint.TestInputWrapper) ... ok
test_close (tests.test_lint.TestIteratorWrapper) ... ok
test_invalid_type (tests.test_lint.TestLatin1Assertion) ... ok
test_valid_type (tests.test_lint.TestLatin1Assertion) ... ok
test_lint_iterator_returned (tests.test_lint.TestMiddleware) ... ok
test_lint_no_keyword_args (tests.test_lint.TestMiddleware) ... ok
test_lint_too_few_args (tests.test_lint.TestMiddleware) ... ok
test_exc_info (tests.test_lint.TestMiddleware2) ... ok
test_to_string (tests.test_lint.TestToString) ... ok
test_normal (tests.test_lint.TestWriteWrapper) ... ok
test_wrong_type (tests.test_lint.TestWriteWrapper) ... ok
test_follow (tests.test_response.TestFollow) ... ok
test_follow_relative (tests.test_response.TestFollow) ... ok
test_follow_twice (tests.test_response.TestFollow) ... ok
test_follow_with_cookie (tests.test_response.TestFollow) ... ok
test_maybe_follow_200 (tests.test_response.TestFollow) ... ok
test_maybe_follow_infinite (tests.test_response.TestFollow) ... ok
test_maybe_follow_once (tests.test_response.TestFollow) ... ok
test_maybe_follow_twice (tests.test_response.TestFollow) ... ok
test_click (tests.test_response.TestResponse) ... ok
test_click_u (tests.test_response.TestResponse) ... ok
test_click_utf8 (tests.test_response.TestResponse) ... ok
test_clickbutton (tests.test_response.TestResponse) ... ok
test_content_dezips (tests.test_response.TestResponse) ... ok
test_html_attribute (tests.test_response.TestResponse) ... ok
test_json (tests.test_response.TestResponse) ... ok
test_lxml_attribute (tests.test_response.TestResponse) ... ok
test_mustcontains (tests.test_response.TestResponse) ... Actual response (no u'not found'):
Response: 200 OK
Content-Type: text/plain
CONTENT_LENGTH: 6
CONTENT_TYPE: application/x-www-form-urlencoded
HTTP_HOST: localhost:80
PATH_INFO: /
QUERY_STRING:
REQUEST_METHOD: POST
SCRIPT_NAME:
SERVER_NAME: localhost
SERVER_PORT: 80
SERVER_PROTOCOL: HTTP/1.0
paste.testing: True
paste.testing_variables: {}
paste.throw_errors: True
webob._parsed_query_vars: (GET([]), '')
wsgi.errors: <webtest.lint.ErrorWrapper object at 0x7ffff69e89d0>
wsgi.input: <webtest.lint.InputWrapper object at 0x7ffff69e8bd0>
wsgi.multiprocess: False
wsgi.multithread: False
wsgi.run_once: False
wsgi.url_scheme: 'http'
wsgi.version: (1, 0)
-- Body ----------
foobar
Actual response (has u'foobar')
Response: 200 OK
Content-Type: text/plain
CONTENT_LENGTH: 6
CONTENT_TYPE: application/x-www-form-urlencoded
HTTP_HOST: localhost:80
PATH_INFO: /
QUERY_STRING:
REQUEST_METHOD: POST
SCRIPT_NAME:
SERVER_NAME: localhost
SERVER_PORT: 80
SERVER_PROTOCOL: HTTP/1.0
paste.testing: True
paste.testing_variables: {}
paste.throw_errors: True
webob._parsed_query_vars: (GET([]), '')
wsgi.errors: <webtest.lint.ErrorWrapper object at 0x7ffff69e89d0>
wsgi.input: <webtest.lint.InputWrapper object at 0x7ffff69e8bd0>
wsgi.multiprocess: False
wsgi.multithread: False
wsgi.run_once: False
wsgi.url_scheme: 'http'
wsgi.version: (1, 0)
-- Body ----------
foobar
ok
test_no_form (tests.test_response.TestResponse) ... ok
test_one_forms (tests.test_response.TestResponse) ... ok
test_referer (tests.test_response.TestResponse) ... ok
test_repr (tests.test_response.TestResponse) ... ok
test_showbrowser (tests.test_response.TestResponse) ... ok
test_testbody (tests.test_response.TestResponse) ... ok
test_too_many_forms (tests.test_response.TestResponse) ... ok
test_unicode (tests.test_response.TestResponse) ... ok
test_unicode_normal_body (tests.test_response.TestResponse) ... ok
test_xml (tests.test_response.TestResponse) ... ok
test_xml_attribute (tests.test_response.TestResponse) ... ok
test_raises (tests.test_sel.TestSelenium) ... ok
test_nodefault (tests.test_utils.NoDefaultTest) ... ok
test_encode_params_NoDefault (tests.test_utils.encode_paramsTest) ... ok
test_encode_params_None (tests.test_utils.encode_paramsTest) ... ok
test_encode_params_charset_utf8 (tests.test_utils.encode_paramsTest) ... ok
test_encode_params_dict_or_list (tests.test_utils.encode_paramsTest) ... ok
test_encode_params_no_charset (tests.test_utils.encode_paramsTest) ... ok
test_json_method_doc (tests.test_utils.json_methodTest) ... ok
test_json_method_name (tests.test_utils.json_methodTest) ... ok
test_json_method_request_calls (tests.test_utils.json_methodTest) ... ok
test_json_method_request_respects_content_type_argument (tests.test_utils.json_methodTest) ... ok
test_make_pattern_None (tests.test_utils.make_patternTest) ... ok
test_make_pattern_bytes (tests.test_utils.make_patternTest) ... ok
test_make_pattern_function (tests.test_utils.make_patternTest) ... ok
test_make_pattern_invalid (tests.test_utils.make_patternTest) ... ok
test_make_pattern_regex (tests.test_utils.make_patternTest) ... ok
test_stringify_binary (tests.test_utils.stringifyTest) ... ok
test_stringify_other (tests.test_utils.stringifyTest) ... ok
test_stringify_text (tests.test_utils.stringifyTest) ... ok

======================================================================
ERROR: test_app_from_config_file (tests.test_debugapp.TestTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/WebTest-2.0.32/tests/test_debugapp.py", line 105, in test_app_from_config_file
    app = webtest.TestApp('config:%s#main' % config)
  File "/build/WebTest-2.0.32/webtest/app.py", line 165, in __init__
    from paste.deploy import loadapp
ImportError: No module named paste.deploy

----------------------------------------------------------------------
Ran 200 tests in 4.646s

FAILED (errors=1, skipped=2)
Test failed: <unittest.runner.TextTestResult run=200 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=200 errors=1 failures=0>
builder for '/nix/store/3szldn2krfsy4wxcj3z97qmh9ci075vf-python2.7-webtest-2.0.32.drv' failed with exit code 1
error: build of '/nix/store/3szldn2krfsy4wxcj3z97qmh9ci075vf-python2.7-webtest-2.0.32.drv' failed
```

</detail>

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
Thanks for reporting. See also https://github.com/NixOS/nixpkgs/pull/71792. Something really weird is going on with using namespace packages in builds since the `setuptools` change.

**Comment by Izorkin** [comment]
AFter commit 4ba99e2361a193115453ea9a539bc2c9c9479aaf error build package virtinst
`nix build -f ./default.nix virtinst`
```
error: webtest-2.0.32 not supported for interpreter python2.7
(use '--show-trace' to show detailed location information)
```

**Comment by Alkeryn** [comment]
any updates on it since i can't rebuild switch because of it

**Comment by FRidh** [comment]
@lzorkin did you read the commit message? The Python 2 version has been disabled. It won't be possible anymore to build Python 2 webtest, at least not until someone is willing to support it.

Given Python 2 is EOL many packaging are dropping Python 2 support and we're following along.

**Comment by Izorkin** [comment]
Ok. The webtest package uses the virtinst application. He, too, has not been updated for a long time, deleted it at home server.

**Comment by Alkeryn** [comment]
@FRidh The issue is that it is used as default and thus rebuild fail to build for me

**Comment by u23a** [comment]
Any updates on it?
This error prevents me from upgrading to 20.09.

**Comment by jtrees** [comment]
I also just ran into this. Can't install `virtinst` because of it.

**Comment by Artturin** [comment]
> I also just ran into this. Can't install `virtinst` because of it.

virtinst is included in virt-manager nowadays

**Comment by Artturin** [comment]
nothing depends on p2 webtest anymore afaik

**Comment by jtrees** [comment]
Ah, thanks.
