### ISSUE TITLE
cherrytree is broken

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#72218]
**Describe the bug**
Cherrytree is broken.

**To Reproduce**
1. install cherrytree
2. try to run cherrytree
```
cherrytree                                                             ~
Traceback (most recent call last):
  File "/nix/store/n8hkmihkrvffbm0wdx2vm2cp1a3kv84i-cherrytree-0.38.8/bin/.cherrytree-wrapped", line 78, in <module>
    f_main(args)
  File "/nix/store/n8hkmihkrvffbm0wdx2vm2cp1a3kv84i-cherrytree-0.38.8/bin/.cherrytree-wrapped", line 49, in f_main
    import main
  File "/nix/store/n8hkmihkrvffbm0wdx2vm2cp1a3kv84i-cherrytree-0.38.8/share/cherrytree/modules/main.py", line 22, in <module>
    import gtk
ImportError: No module named gtk
```

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.5, NixOS, 20.03pre196586.b943338ea58 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre196586.b943338ea58"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
cherrytree
```

**Comment by d4g** [comment]
@AndersonTorres

**Comment by prusnak** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/72261
