### ISSUE TITLE
mozc: can't open Preferences as mozc_tool doesn't work

### ISSUE THREAD

**Issue by Zepsylonum** [NixOS/nixpkgs#72896]
Related to #65399

`mozc_tool` doesn't work as intended, instead closing immediately with return code 255. This is caused by the usage of `clangStdenv.mkDerivation` instead of `mkDerivation` in `pkgs/tools/inputmethods/ibus-engines/ibus-mozc/default.nix`, as `mozc_tool` is an Qt application. I tried to do this:
```
{ lib, mkDerivation, fetchFromGitHub, fetchpatch, which, ninja, python, gyp, pkgconfig
, protobuf, ibus, gtk2, zinnia, qtbase, libxcb }:

let
  japanese_usage_dictionary = fetchFromGitHub {
    owner  = "hiroyuki-komatsu";
    repo   = "japanese-usage-dictionary";
    rev    = "e5b3425575734c323e1d947009dd74709437b684";
    sha256 = "0pyrpz9c8nxccwpgyr36w314mi8h132cis8ijvlqmmhqxwsi30hm";
  };
in mkDerivation rec {
  name = "ibus-mozc-${version}";
  version = "2.23.2815.102";

  meta = with lib; {
    isIbusEngine = true;
    …
  buildInputs = [ protobuf ibus gtk2 zinnia qtbase libxcb ];
    …
```
And in `pkgs/top-level/all-packages.nix`:
```
    mozc = qt5.callPackage ../tools/inputmethods/ibus-engines/ibus-mozc {
      python = python2;
      inherit (python2Packages) gyp;
      protobuf = pkgs.protobuf.overrideDerivation (oldAttrs: { stdenv = clangStdenv; });
    };
```

But apparently `mozc` must be compiled with clang only:
```gyp: Call to 'which clang' returned exit status 1.
Traceback (most recent call last):
  File "build_mozc.py", line 1236, in <module>
    main()
  File "build_mozc.py", line 1220, in main
    GypMain(cmd_opts, cmd_args)
  File "build_mozc.py", line 736, in GypMain
    RunOrDie(gyp_command + gyp_options)
  File "/build/source/src/build_tools/util.py", line 99, in RunOrDie
    '==========']))
build_tools.util.RunOrDieError:
```

I tried adding `stdenv = clangStdenv` to `mozc = {…}`, but
```
error: anonymous function at /home/zepsy/nixpkgs/pkgs/tools/inputmethods/ibus-engines/ibus-mozc/default.nix:1:1 called with unexpected argument 'stdenv', at /home/zepsy/nixpkgs/lib/customisation.nix:69:12
```

(`~/nixpkgs` is `nixos-19.09` branch of `NixOS/nixpkgs`)

Same applies for `fcitx-mozc` and probably to the rest of Qt applications with non-default `stdenv`. Maybe I'm doing something wrong, but I'm not sure how to fix this.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.81, NixOS, 19.09.1019.c5aabb0d603 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3pre6895_84de821`
 - channels(root): `"nixos-19.09.1019.c5aabb0d603"`
 - channels(zepsy): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Zepsylonum** [comment]
Don't think it matters, but switching to `master` doesn't help.
Also, installing `qt-full` fixes the problem. Obviously that's not a proper solution but it can be used as a temporary workaround.

**Comment by Zepsylonum** [comment]
Wow, it actually got fixed. Thanks!
