### ISSUE TITLE
Python ctypes.util.find_library

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#7307]
I’m trying to run a Python project that uses `libnfc` in `nix-shell`. The code does

~~~~python
ctypes.util.find_library('nfc')
~~~~

and for some strange reason this returns just `libnfc.so.5`. I’m not sure how `find_library` works, but the docs say:

> On Linux, `find_library()` tries to run external programs (`/sbin/ldconfig`, `gcc`, and `objdump`) to find the library file.

Unfortunately this doesn’t seem to work, even though `g++` successfully builds a C++ program that depends on `libnfc`. Any ideas why this is happening? Why isn’t it able to figure out the path to `libnfc`? Shouldn’t `ctypes.util.find_library` be patched in nixpkgs to avoid running weird programs and just check the environment variables?

**Comment by domenkozar** [comment]
Can you provide exact steps to reproduce?

**Comment by kirelagin** [comment]
~~~~nix
# shell.nix
let pkgs = import <nixpkgs> {};
in with pkgs;
stdenv.mkDerivation rec {
  name = "test";

  src = ./.;

  buildInputs = [
    python2
    libnfc
  ];
}
~~~~

~~~~python
# nfc.py
import ctypes
import ctypes.util

lib = ctypes.util.find_library('nfc')
print('Library: ' + lib)

ctypes.CDLL(lib)
~~~~

~~~~console
$ python2 nfc.py
Library: libnfc.so.5
Traceback (most recent call last):
  File "nfc.py", line 7, in <module>
    ctypes.CDLL(lib)
  File "/nix/store/5aq9sjd0g4frmpqni0a6zykzkcnzc3al-python-2.7.9/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnfc.so.5: cannot open shared object file: No such file or directory
~~~~

~~~~c
// nfc.c 
#include <nfc/nfc.h>

int main()
{
    nfc_context *c;

    nfc_init(&c);
    nfc_exit(c);

    return 0;
}
~~~~

~~~~console
$ gcc -lnfc nfc.c
# OK
~~~~

**Comment by kirelagin** [comment]
I assumed this was expected to work, because I saw [this patch](https://github.com/NixOS/nixpkgs/blob/ab1c1773e2f8b05701732bdddb0f6602c19e9592/pkgs/tools/misc/file/python.patch). But now I looked around nixpkgs and seems that everyone else is patching `find_library` calls with fixed paths.

I also reread the docs and notices, it says that `find_library` returns just the library _name_, not the _path_ on Linux (unlike other OS). So, hm, probably the question is then that the loader has to be patched…

**Comment by domenkozar** [comment]
@kirelagin for now setting `DYLD_LIBRARY_PATH` to point to `${libnfc}/lib` will do, but we should `find_library` to return fullpath.

**Comment by domenkozar** [comment]
It's a bit harder since `ldconfig -p` fails on NixOS since we don't keep the cache.

**Comment by kirelagin** [comment]
> but we should `find_library` to return fullpath.

As I said, Python docs state that on Linux `find_library` returns just the filename, so patching it this way might break things…

**Comment by domenkozar** [comment]
It can't break things more than they currently are - as it doesn't even work due to prefix being unknown.

**Comment by domenkozar** [comment]
Yeah I'm getting bitten by this one again.

**Comment by domenkozar** [comment]
This is the line that gets executed on linux: https://github.com/python/cpython/blob/2.7/Lib/ctypes/util.py#L242

**Comment by domenkozar** [comment]
So if you were to execute `ctypes.util.find_library('c')` it would do:

1. `LANG=C LC_ALL=C gcc -Wl,-t -o bla2>&1 -l c` and store the output
2. objdump -p -j .dynamic objdump -p -j .dynamic /nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/lib/libc.so.6|grep SONAME

I think we should replace this with our own implementation

**Comment by lethalman** [comment]
Probably just patch that code to `return "/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/lib/libc.so.6"` .

**Comment by domenkozar** [comment]
That's the thing, I don't want to maintain every package and patch it when it uses `find_library`

**Comment by lethalman** [comment]
@domenkozar well, I don't think there's any good solution to that unfortunately.

**Comment by lethalman** [comment]
@domenkozar perhaps a special env variable `PY_CTYPES_LIBPATH`, to look for libs inside that path. Similar to `LD_LIBRARY_PATH`, but not `LD_LIBRARY_PATH`.

**Comment by domenkozar** [comment]
We could use http://linux.die.net/man/8/ldconfig to generate the cache at build time.

**Comment by Profpatsch** [comment]
(triage) there have been a few patches, is this fixed now?

**Comment by domenkozar** [comment]
We haven't solved it universally yet.

**Comment by FRidh** [comment]
> perhaps a special env variable PY_CTYPES_LIBPATH, to look for libs inside that path. Similar to LD_LIBRARY_PATH, but not LD_LIBRARY_PATH.

> We could use http://linux.die.net/man/8/ldconfig to generate the cache at build time. find_library then uses ldconfig -p to get the available paths.

Both are interesting options.

`dlopen` is called during runtime. If we somehow want to hardcode the paths, we need to make sure all calls to `dlopen` are executed during the build. Otherwise, the libraries need to be found during runtime by the interpreter or whichever application is using the Python library.

So, if we consider the ldconfig cache, then the cache has to be available during runtime, and the interpreter has to be able to find it. As soon as we put packages together in say an env we end up with multiple caches, so we would have to rebuild the cache as well.

We should be able to patch the interpreter to load an environment variable that points to the cache. Then we can build the cache 1) whenever we build a Python package and 2) when we build an env.

A downside is that when building a cache all `buildInputs` would become runtime dependencies because they're listed in the cache. Furthermore, `ldconfig` in `python.buildEnv` is only passed a list of caches. Therefore, we might also need an environment variable `NIX_PY_CTYPES_LIBPATH` which files are added to a `ld.so.conf` file that is then used by `ldconfig`.

So, we patch Python to check for `NIX_PY_CTYPES_LIBPATH` and then `buildPythonPackage` and `python.buildEnv` 
1. check for `NIX_PY_CTYPES_LIBPATH`. If it exists, create a `/nix/ld.so.conf` file
2. if  `/nix/ld.so.conf` exists, build the cache `ldconfig -C `NIX_PY_LDCONFIG_CACHE -f /nix/ld.so.conf`, and set `NIX_PY_LDCONFIG_CACHE=$out/nix/nix-py-ldconfig-cache;` Note that `/nix/ld.so.conf` of dependencies should also be taken into account, so maybe its just better to add these libraries to `propagatedBuildInputs`.
3. Now the interpreter can find the cache during build time.
4. For runtime we support *only* `python.buildEnv` where we rebuild the cache and again set `NIX_PY_CTYPES_LIBPATH`

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by toyo-chi** [comment]
Trying to build another Python library and get the same error. Looks like it's still important.

**Comment by FRidh** [comment]
> A downside is that when building a cache all buildInputs would become runtime dependencies because they're listed in the cache. Furthermore, ldconfig in python.buildEnv is only passed a list of caches.

This is not actually an issue. `buildInputs` represents the runtime deps. Other build-time deps should be in `nativeBuildInputs` anyway.

**Comment by michaelcadilhac** [comment]
Still unsure what's a valid workaround here.  Setting `DYLD_LIBRARY_PATH` seems to have no effect.

**Comment by fluffynukeit** [comment]
I am also trying to fix the a find_library call in a python package, for libsnd.  Like @michaelcadilhac , setting `DYLD_LIBRARY_PATH` has no effect.

```
in pkgs.mkShell {
  buildInputs = [ 
    myenv
    pkgs.ffmpeg
    pkgs.libsndfile
  ];
  DYLD_LIBRARY_PATH="${pkgs.libsndfile}/lib";
}
```


```
DYLD_LIBRARY_PATH=/nix/store/pbx64k731w2r2501y500r8n5fxy6m91r-libsndfile-1.0.30-bin/lib
```
```
OSError: cannot load library 'libsndfile.so.1': libsndfile.so.1: cannot open shared object file: No such file or directory
```

**Comment by wilhelmy** [comment]
Just for clarification, it seems possible to fix this issue by patching `ctypes.util.find_library` to return the full path?
Should we contact upstream about possible side-effects?

**Comment by reivilibre** [comment]
> I marked this as stale due to inactivity. → [More info](https://github.com/NixOS/nixpkgs/blob/master/.github/STALE-BOT.md)

I'm still interested in this issue. It's just bitten me now and I worry I'm not experienced enough to solve this properly.

**Comment by wilhelmy** [comment]
@reivilibre Have you tried the workaround (patching the call out)?
https://discourse.nixos.org/t/screenshot-with-mss-in-python-says-no-x11-library/14534/4

**Comment by rkjnsn** [comment]
I'm running into this issue with a Calibre plugin. Even if I add the required library to Calibre's deps, the plugin, which uses find_library, can't find it. Because the actual code is part of a plugin installed in the my home directory, not by nix, patching it to use an absolute path instead isn't really practical, and would break every time the path changed due to an update+garbage-collect.

**Comment by SomeoneSerge** [comment]
> Shouldn’t ctypes.util.find_library be patched in nixpkgs to avoid running weird programs and just check the environment variables?

That's a possibility, but the issue is that there is no correct behaviour for `ctypes.util.find_library` at all. The upstream implementation might return build or host platform's dependencies at random, and in both cases the function relies on glibc and gcc internals. The most common practice seems to be to use it for locating native dependencies (i.e. what'd be detected by ld.so or ldconfig, as opposed to what'd be detected by gcc), but that's just us making assumptions. So which kind should we return?

If we were to patch ctypes... what about just introducing a separate environment variable to list search paths for `find_library` specifically? We could keep the original implementation as a fallback too, and issue `UserWarning`s whenever those branches are reached
