### ISSUE TITLE
Joker is broken in nixos-19.09

### ISSUE THREAD

**Issue by thiagokokada** [NixOS/nixpkgs#73305]
**Describe the bug**
Joker segfaults in NixOS `19.09.1172.2d896998dc9`.

```sh
$  joker                                                                                                                         16:53:43
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/candid82/joker/core.extractInt(...)
	/build/source/core/pack.go:199
github.com/candid82/joker/core.UnpackHeader(0x0, 0x0, 0x0, 0xc000126150, 0xc0000ca240, 0xc00010e9a0, 0x4e000000008a11e0, 0xc0001a9c01)
	/build/source/core/pack.go:102 +0x79e
github.com/candid82/joker/core.processData(0x0, 0x0, 0x0)
	/build/source/core/procs.go:1668 +0xd5
github.com/candid82/joker/core.ProcessCoreData(...)
	/build/source/core/procs.go:1678
main.main()
	/build/source/main.go:569 +0x3a4
```

**To Reproduce**
1. Install joker with `nix-env -iA nixos.joker`
2. Run it with `joker`

**Expected behavior**
It should run without segfaulting.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.82, NixOS, 19.09.1172.2d896998dc9 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1172.2d896998dc9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nixos.joker
```

**Comment by filalex77** [comment]
Can reproduce on NixOS unstable.

```
panic: runtime error: slice bounds out of range [:8] with capacity 0

goroutine 1 [running]:
github.com/candid82/joker/core.extractInt(...)
	/build/source/core/pack.go:199
github.com/candid82/joker/core.UnpackHeader(0x0, 0x0, 0x0, 0xc00011c540, 0xc0000da300, 0x0, 0x60, 0xc000123d38)
	/build/source/core/pack.go:102 +0x7dd
github.com/candid82/joker/core.processData(0x0, 0x0, 0x0)
	/build/source/core/procs.go:1682 +0xf1
github.com/candid82/joker/core.ProcessCoreData(...)
	/build/source/core/procs.go:1692
main.main()
	/build/source/main.go:593 +0x2cc
```

**Comment by andrestylianos** [comment]
I just became aware of this issue. I'll see if I can take a look and figure out the issue over the weekend.

**Comment by marsam** [comment]
Addressed by https://github.com/NixOS/nixpkgs/commit/174190dae1ef010e937043c6126abd56e6b9fe49 (backported to 19.09 https://github.com/NixOS/nixpkgs/commit/c961094d91422bd34b5f72f7d36d7c59b6b786d7)
