### ISSUE TITLE
undervolt doesn't work

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#73738]
**Describe the bug**
I've never used undervolt, but I activated the service and then tried to use the CLI. Seems broken on `nixos-unstable`:

```
[nix-shell:~/code/nixcfg]$ undervolt 
Traceback (most recent call last):
  File "/nix/store/ccjn2n78p82b53850j46115ihcpcqm0i-undervolt-0.2.9/bin/.undervolt-wrapped", line 4, in <module>
    import re
  File "/nix/store/gpnm7i19lpj8p43mjrdw03d0hjalmskl-python3-3.7.5/lib/python3.7/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'


```

**Comment by colemickens** [comment]
Er, I guess it works if you just use `sudo`... unexpected.
