### ISSUE TITLE
tensorboard failing to start in unstable

### ISSUE THREAD

**Issue by pashashocky** [NixOS/nixpkgs#73840]
**Describe the bug**
Tensorboard failing to start with `tensorboard --logdir=runs` on latest version from unstable.

**To Reproduce**
1) `config.nix` under `.config/nixpkgs/config.nix
```
let
  pkgs = import <nixpkgs> { config = { allowUnfree = true; }; };
in
let
  mypython = pkgs.python3;
  ppkgs = mypython.pkgs;

  my-packages = pp: with pp;
    [
      ipython
      jupyter_console
      qtconsole

      matplotlib
      numpy
      pandas
      pytorchWithCuda
      scikitimage
      tensorflowWithCuda
      torchvision
    ];
  python-stuff = (mypython.withPackages (my-packages)).override (
    args:
      { ignoreCollisions = true; }
  );
in
  {
    allowUnfree = true;
    packageOverrides = pkgs: with pkgs; {
      myPackages = pkgs.buildEnv {
        name = "user-packages";
        paths = [
          python-stuff
          jupyter
          qt5.full
        ];
      };
    };
  }
```
2) `nix-env -f '<nixpkgs>' -iA myPackages`
3) `tensorboard --logdir=runs`

the output is: 

```
$ tensorboard --logdir=runs                                       
2019-11-20 22:49:45.772242: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/nix/store/7lx3cb7jxhsvdp5z8321446gi7diyk7g-python3.7-tensorflow-tensorboard-1.15.0/bin/.tensorboard-wrapped", line 9, in <module>
    sys.exit(run_main())
  File "/nix/store/nfac7nq03pmgv3alrgn58kcgpyj89p9k-python3-3.7.5-env/lib/python3.7/site-packages/tensorboard/main.py", line 58, in run_main
    default.get_plugins() + default.get_dynamic_plugins(),
  File "/nix/store/nfac7nq03pmgv3alrgn58kcgpyj89p9k-python3-3.7.5-env/lib/python3.7/site-packages/tensorboard/default.py", line 110, in get_dynamic_plugins
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/nix/store/nfac7nq03pmgv3alrgn58kcgpyj89p9k-python3-3.7.5-env/lib/python3.7/site-packages/tensorboard/default.py", line 110, in <listcomp>
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/nix/store/nfac7nq03pmgv3alrgn58kcgpyj89p9k-python3-3.7.5-env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/nix/store/nfac7nq03pmgv3alrgn58kcgpyj89p9k-python3-3.7.5-env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/nix/store/nfac7nq03pmgv3alrgn58kcgpyj89p9k-python3-3.7.5-env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wheel>=0.26; python_version >= "3"' distribution was not found and is required by the application
```

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84, NixOS, 20.03pre202088.e89b21504f3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(pash): `""`
 - channels(root): `"nixos-20.03pre202088.e89b21504f3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information: @jonringer 
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

Thank you very much for your help, I am just starting with nixos. Please, let me know if it's me who's doing something wrong.

**Comment by jonringer** [comment]
Not a package I maintain, but I don't like that it's broken :)

**Comment by jonringer** [comment]
you can get maintainer information by doing the following:

```
$ nix eval nixpkgs.python3Packages.tensorflow-tensorboard.meta.maintainers
[ { email = "ab@fmap.me"; github = "abbradar"; name = "Nikolay Amiantov"; } ]
```

**Comment by jonringer** [comment]
@pashashocky thank you for opening up an issue though :)

**Comment by pashashocky** [comment]
> @pashashocky thank you for opening up an issue though :)

@jonringer Thank you for the info and a super quick fix! Still have a lot to learn on nix, and if you have any suggestions on any useful guides to read - would be greatly appreciated.

**Comment by jonringer** [comment]
hmm, nix is hard to pick up, other than the nix pills, and just looking through PR/code, i don't have many great resources. It was not the easiest to learn, but that's in part because it's so different from anything else.
