### ISSUE TITLE
panic mkdir build: Build fails on debian when it does not fail on NixOs:  sandbox issue?

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#75114]
**Describe the bug**
I created a simple derivation for building a hugo website. The compilation works on NixOs, but fails on my debian installation.

**To Reproduce**
1. Install `hugo` package and create a basic website or download directly a basic website:

    git clone https://github.com/gohugoio/hugoBasicExample.git && cd hugoBasicExample

2. Make sure it compiles by running `hugo`.
3. Create a file `default.nix` containing:

```
let
  pkgs = import <nixpkgs> {};
in pkgs.callPackage ./derivation.nix {}
```

and a file `derivation.nix` containing 

```
{stdenv, hugo, ... }:
stdenv.mkDerivation rec {
  name = "mysite.me";
  src = ./. ;
  
  nativeBuildInputs = [ hugo ];

  installPhase = ''
    mkdir -p $out
    ${hugo}/bin/hugo -d $out/public/
  '';
  
  meta = with stdenv.lib; {
    description = "My website that should be server at mysite.me";
    homepage = https://mysite.me;
    license = licenses.mit;
    platforms = platforms.linux;
    maintainers = [ ];
  };
}
```
- Run `nix-build`:

Output:

```
$ nix-build
these derivations will be built:
  /nix/store/hbv8vilqxsixpi0y57377896r3rfmxgd-mysite.me.drv
building '/nix/store/hbv8vilqxsixpi0y57377896r3rfmxgd-mysite.me.drv'...
/nix/store/whpnlfj79vd8p175rp1bwg0x7wz5lmj1-stdenv-linux/setup: line 795: /build/env-vars: No such file or directory
unpacking sources
/nix/store/whpnlfj79vd8p175rp1bwg0x7wz5lmj1-stdenv-linux/setup: line 795: /build/env-vars: No such file or directory
unpacking source archive /nix/store/i8a5691gsb8dgdn5alr6d5mqwmdwy0sz-hugoBasicExample
source root is hugoBasicExample
find: '/build/..': No such file or directory
patching sources
/nix/store/whpnlfj79vd8p175rp1bwg0x7wz5lmj1-stdenv-linux/setup: line 795: /build/env-vars: No such file or directory
configuring
/nix/store/whpnlfj79vd8p175rp1bwg0x7wz5lmj1-stdenv-linux/setup: line 795: /build/env-vars: No such file or directory
no configure script, doing nothing
building
/nix/store/whpnlfj79vd8p175rp1bwg0x7wz5lmj1-stdenv-linux/setup: line 795: /build/env-vars: No such file or directory
no Makefile, doing nothing
installing
/nix/store/whpnlfj79vd8p175rp1bwg0x7wz5lmj1-stdenv-linux/setup: line 795: /build/env-vars: No such file or directory
Total in 0 ms
panic: mkdir /build: permission denied

goroutine 1 [running]:
github.com/spf13/afero.GetTempDir(0x204f520, 0x2d64980, 0x1ca059c, 0xa, 0xc0006841a0, 0xc00076cc80)
        /build/go/pkg/mod/github.com/spf13/afero@v1.2.2/util.go:128 +0x319
github.com/gohugoio/hugo/helpers.GetTempDir(...)
        /build/source/helpers/path.go:636
github.com/gohugoio/hugo/helpers.GetCacheDir(0x204f520, 0x2d64980, 0x204b040, 0xc00046e900, 0x2f, 0x1c7b556, 0x1, 0x9)
        /build/source/helpers/path.go:600 +0x198
github.com/gohugoio/hugo/cache/filecache.resolveDirPlaceholder(0x204f520, 0x2d64980, 0x204b040, 0xc00046e900, 0x1cce8e4, 0x9, 0xc0005998e0, 0x2, 0x2, 0x0, ...)
        /build/source/cache/filecache/filecache_config.go:223 +0x1e5
github.com/gohugoio/hugo/cache/filecache.DecodeConfig(0x204f520, 0x2d64980, 0x204b040, 0xc00046e900, 0xc00003b340, 0x36, 0x9d24c6)
        /build/source/cache/filecache/filecache_config.go:165 +0xdc7
github.com/gohugoio/hugo/hugolib.configLoader.collectModules(0x204f520, 0x2d64980, 0xc000562f60, 0x0, 0x0, 0xc00003a0c4, 0x2f, 0xc00003a0c4, 0x2f, 0xc00003af40, ...)
        /build/source/hugolib/config.go:425 +0x136
github.com/gohugoio/hugo/hugolib.LoadConfig(0x204f520, 0x2d64980, 0xc000562f60, 0x0, 0x0, 0xc00003a0c4, 0x2f, 0xc00003a0c4, 0x2f, 0xc00003af40, ...)
        /build/source/hugolib/config.go:227 +0xab0
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc00030f790, 0xc000300001, 0x200aaa0, 0xc00059bca0)
        /build/source/commands/commandeer.go:301 +0x3ba
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0xc0006001a0, 0x2008440, 0xc00059bb80, 0xc00059bc90, 0x0, 0x0, 0x0, 0x1a61ca0, 0x2e953e01, ...)
        /build/source/commands/commandeer.go:183 +0x241
github.com/gohugoio/hugo/commands.initializeConfig(0x1a60001, 0xc0006001a0, 0x2008440, 0xc00059bb80, 0xc00059bc90, 0x67cf77, 0xc0004d1100, 0xc00076dc88)
        /build/source/commands/hugo.go:123 +0x76
github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0xc000840500, 0xc000411f80, 0x0, 0x2, 0x0, 0x0)
        /build/source/commands/commands.go:159 +0x134
github.com/spf13/cobra.(*Command).execute(0xc000840500, 0xc0000320a0, 0x2, 0x2, 0xc000840500, 0xc0000320a0)
        /build/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20190321000552-67fc4837d267/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000840500, 0xc00059bb80, 0xc00076dec0, 0x1691d52)
        /build/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20190321000552-67fc4837d267/command.go:850 +0x2fb
github.com/gohugoio/hugo/commands.Execute(0xc0000320a0, 0x2, 0x2, 0x4bdfdf, 0xc0000440b8, 0x0, 0x0)
        /build/source/commands/hugo.go:89 +0xb9
main.main()
        /build/source/main.go:23 +0x6c
builder for '/nix/store/hbv8vilqxsixpi0y57377896r3rfmxgd-mysite.me.drv' failed with exit code 2
error: build of '/nix/store/hbv8vilqxsixpi0y57377896r3rfmxgd-mysite.me.drv' failed
```

Note that if I copy this same code on a NixOs device, it does compile.

**Expected behavior**
I'd expect the program to compile also on Debian.

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

```
[1 copied, 0.0 MiB DL]
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0-4-amd64, Debian GNU/Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(me): `"nixpkgs-20.03pre203371.3fb4e09812b"`
 - nixpkgs: `/home/me/.nix-defexpr/channels/nixpkgs`
```

**Comment by tobiasBora** [comment]
So after discussing with clever, it is indeed linked with https://github.com/NixOS/nix/issues/3142
 , the PR is merged, but the changes are not yet into nixpkgs. So the fix is to compile with

```
nix-build --option sandbox false
``` 
or to set `sandbox = false` in nix.conf.
