### ISSUE TITLE
lice: exception on startup

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#75521]
**Describe the bug**

`lice` fails to run, doesn't find `pkg_resources`.

**To Reproduce**

```
> nix run nixpkgs.lice -c lice
[1 copied (0.3 MiB), 0.0 MiB DL]
Traceback (most recent call last):
  File "/nix/store/jrvln64pbjbwn9cbw13fzjrmckhnckrb-python3.7-lice-0.4/bin/.lice-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/jrvln64pbjbwn9cbw13fzjrmckhnckrb-python3.7-lice-0.4/lib/python3.7/site-packages/lice/__init__.py", line 5, in main
    from lice.core import main
  File "/nix/store/jrvln64pbjbwn9cbw13fzjrmckhnckrb-python3.7-lice-0.4/lib/python3.7/site-packages/lice/core.py", line 1, in <module>
    from pkg_resources import (resource_stream, resource_listdir)
ModuleNotFoundError: No module named 'pkg_resources'
```

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.88, NixOS, 19.09.1549.45ea6092203 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"home-manager, nixos-19.09.1549.45ea6092203, nixos-unstable-20.03pre204199.3140fa89c51, nixpkgs-19.09.1549.45ea6092203"`
 - channels(addy): `"home-manager, nixos-19.09.1549.45ea6092203, nixos-unstable-20.03pre204199.3140fa89c51, nixpkgs-19.09"`
 - nixpkgs: `/home/addy/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: lice
# a list of nixos modules affected by the problem
module:
```

**Comment by mat8913** [comment]
Give this a try

```
{ stdenv, python3Packages }:

python3Packages.buildPythonPackage rec {

  pname = "lice";
  version = "0.6";

  src = python3Packages.fetchPypi {
    inherit pname version;
    sha256 = "0skyyirbidknfdzdvsjga8zb4ar6xpd5ilvz11dfm2a9yxh3d59d";
  };

  propagatedBuildInputs = [
    python3Packages.setuptools
  ];

  doCheck = false;

  meta = with stdenv.lib; {
    description = "Print license based on selection and user options.";
    homepage = https://github.com/licenses/lice;
    license = licenses.bsd3;
    maintainers = with maintainers; [ swflint ];
    platforms = platforms.unix;
  };

}
```

**Comment by Moredread** [comment]
I haven't looked into it yet, but I pushed it up on my Todo list :p

**Comment by simonfxr** [comment]
@mat8913 Installing lice based on your snippet works for me.
