### ISSUE TITLE
python-modules/decorator doesn't build

### ISSUE THREAD

**Issue by Kaali** [NixOS/nixpkgs#75554]
**Describe the bug**
development/python-modules/decorator doesn't build because a test fails.

**To Reproduce**
1. Checkout current master (f7e5482e55a5263f4fd13b9451485775d42ff457)
2. Try to build the package
3. Watch it fail

**Expected behavior**
Should build.

**Additional context**

Commit 417f9a5b41357a5635cf76cbc788291695cf2684 touched renamed the test that fails.

Full log of the build:

```building '/nix/store/64pqww8j4l5c9hxsdvhhws44g744pilw-python3.7-decorator-4.4.1.drv'...
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing setuptools-check-hook
Using setuptoolsCheckPhase
unpacking sources
unpacking source archive /nix/store/idhfvc7jkc7gh9b3bqi3q1va87s4ckyg-decorator-4.4.1.tar.gz
source root is decorator-4.4.1
setting SOURCE_DATE_EPOCH to timestamp 1572163736 of file decorator-4.4.1/src/decorator.egg-info/top_level.txt
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
running bdist_wheel
running build
running build_py
creating build
creating build/lib
copying src/decorator.py -> build/lib
installing to build/bdist.macosx-10.6-x86_64/wheel
running install
running install_lib
creating build/bdist.macosx-10.6-x86_64
creating build/bdist.macosx-10.6-x86_64/wheel
copying build/lib/decorator.py -> build/bdist.macosx-10.6-x86_64/wheel
running install_egg_info
running egg_info
writing src/decorator.egg-info/PKG-INFO
writing dependency_links to src/decorator.egg-info/dependency_links.txt
writing top-level names to src/decorator.egg-info/top_level.txt
reading manifest file 'src/decorator.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'documentation.pdf'
writing manifest file 'src/decorator.egg-info/SOURCES.txt'
Copying src/decorator.egg-info to build/bdist.macosx-10.6-x86_64/wheel/decorator-4.4.1-py3.7.egg-info
running install_scripts
adding license file "LICENSE.txt" (matched pattern "LICEN[CS]E*")
creating build/bdist.macosx-10.6-x86_64/wheel/decorator-4.4.1.dist-info/WHEEL
creating 'dist/decorator-4.4.1-py2.py3-none-any.whl' and adding 'build/bdist.macosx-10.6-x86_64/wheel' to it
adding 'decorator.py'
adding 'decorator-4.4.1.dist-info/LICENSE.txt'
adding 'decorator-4.4.1.dist-info/METADATA'
adding 'decorator-4.4.1.dist-info/WHEEL'
adding 'decorator-4.4.1.dist-info/pbr.json'
adding 'decorator-4.4.1.dist-info/top_level.txt'
adding 'decorator-4.4.1.dist-info/RECORD'
removing build/bdist.macosx-10.6-x86_64/wheel
Finished executing setuptoolsBuildPhase
installing
Executing pipInstallPhase
/private/var/folders/4f/gpssx8mx1fl3h7db4sq60p6m0000gn/T/nix-build-python3.7-decorator-4.4.1.drv-0/decorator-4.4.1/dist /private/var/folders/4f/gpssx8mx1fl3h7db4sq60p6m0000gn/T/nix-build-python3.7-decorator-4.4.1.drv-0/decorator-4.4.1
Processing ./decorator-4.4.1-py2.py3-none-any.whl
Installing collected packages: decorator
Successfully installed decorator-4.4.1
/private/var/folders/4f/gpssx8mx1fl3h7db4sq60p6m0000gn/T/nix-build-python3.7-decorator-4.4.1.drv-0/decorator-4.4.1
Finished executing pipInstallPhase
post-installation fixup
strip is /nix/store/7aap9ycxx2af1h03h4c5kddx88p0fzcp-cctools-binutils-darwin-927.0.2/bin/strip
stripping (with command strip and flags -S) in /nix/store/cprkar016c139lz9hrpq22kfl87him5m-python3.7-decorator-4.4.1/lib 
patching script interpreter paths in /nix/store/cprkar016c139lz9hrpq22kfl87him5m-python3.7-decorator-4.4.1
running install tests
no Makefile or custom buildPhase, doing nothing
pythonCatchConflictsPhase
pythonRemoveBinBytecodePhase
pythonImportsCheckPhase
Executing pythonImportsCheckPhase
setuptoolsCheckPhase
Executing setuptoolsCheckPhase
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing src/decorator.egg-info/PKG-INFO
writing dependency_links to src/decorator.egg-info/dependency_links.txt
writing top-level names to src/decorator.egg-info/top_level.txt
reading manifest file 'src/decorator.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'documentation.pdf'
writing manifest file 'src/decorator.egg-info/SOURCES.txt'
running build_ext
test_before_after (tests.test.CoroutineTestCase) ... ok
test_coro_to_func (tests.test.CoroutineTestCase) ... ok
test_add1 (tests.test.ExtraTestCase) ... ok
test_decorator_factory (tests.test.ExtraTestCase) ... ok
test_no_first_arg (tests.test.ExtraTestCase) ... ok
test_qualname (tests.test.ExtraTestCase) ... ok
test_signature (tests.test.ExtraTestCase) ... ok
test_unique_filenames (tests.test.ExtraTestCase) ... ok
test_gen123 (tests.test.GeneratorCallerTestCase) ... ok
test (tests.test.NoDocumentation) ... /private/var/folders/4f/gpssx8mx1fl3h7db4sq60p6m0000gn/T/nix-build-python3.7-decorator-4.4.1.drv-0/decorator-4.4.1/src/tests/documentation.py:1534: PendingDeprecationWarning: isAlive() is deprecated, use is_alive() instead
  elif f.thread.isAlive():
**********************************************************************
File "/private/var/folders/4f/gpssx8mx1fl3h7db4sq60p6m0000gn/T/nix-build-python3.7-decorator-4.4.1.drv-0/decorator-4.4.1/src/tests/documentation.py", line 50, in tests.documentation.operation2
Failed example:
    operation2()
Expected:
    operation2 is slow
Got nothing
**********************************************************************
1 items had failures:
   1 of   1 in tests.documentation.operation2
***Test Failed*** 1 failures.
FAIL
test_singledispatch1 (tests.test.NoDocumentation) ... ok
test_singledispatch2 (tests.test.NoDocumentation) ... ok
test_c_classes (tests.test.TestSingleDispatch) ... ok
test_mro (tests.test.TestSingleDispatch) ... ok
test_mro_conflicts (tests.test.TestSingleDispatch) ... ok
test_register_abc (tests.test.TestSingleDispatch) ... ok
test_register_decorator (tests.test.TestSingleDispatch) ... ok
test_register_error (tests.test.TestSingleDispatch) ... ok
test_simple_overloads (tests.test.TestSingleDispatch) ... ok
test_wrapping_attributes (tests.test.TestSingleDispatch) ... ok

======================================================================
FAIL: test (tests.test.NoDocumentation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/folders/4f/gpssx8mx1fl3h7db4sq60p6m0000gn/T/nix-build-python3.7-decorator-4.4.1.drv-0/decorator-4.4.1/src/tests/test.py", line 81, in test
    self.assertEqual(err, 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 20 tests in 5.672s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=20 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=20 errors=0 failures=1>
builder for '/nix/store/64pqww8j4l5c9hxsdvhhws44g744pilw-python3.7-decorator-4.4.1.drv' failed with exit code 1
```

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.1`
 - channels(kaali): `"nixpkgs-19.09pre172680.92ec809473e"`
 - nixpkgs: `/Users/kaali/dev/nix/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Kaali** [comment]
Might be some sort of a race condition. As it passed now with a rebuild, without changing anything.

**Comment by Infinisil** [comment]
Fixed in upstream with https://github.com/micheles/decorator/pull/79

Relevant for #80379 

Once above PR is in a new release (which I hope should be soon) we can update the package in master and 20.03

**Comment by jonringer** [comment]
This is no longer the case, package builds fine
