### ISSUE TITLE
nix-shell: Bus error (core dumped)

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#75590]
**Describe the bug**
When attempting to memmap a large file, `nix-shell` triggers a Bus error (core dumped). This may be caused by [exhausting shared memory](https://github.com/pytorch/pytorch/issues/2244#issuecomment-318864552).

**To Reproduce**
0. download [this file (warning: 57GB)](https://s3.amazonaws.com/edu.stanford.cnc/Open-Science/f2_e1_omr.ome.btf)
1. add `(python3.withPackages (ps: [ps.tifffile]))` to `configuration.nix`
2. observe that this works:
```
$ python
>>> import tifffile
>>> tiff_fn  = "~/Downloads/f2_e1_omr.ome.btf"
>>> 
>>> f = tifffile.TiffFile(tiff_fn)
>>> mm = f.asarray(out='memmap')
>>>
```
2. try below:
```
> nix-shell -p "python3.withPackages (ps: [ps.tifffile])"
$ python
>>> import tifffile
>>> tiff_fn  = "/data/dlab/zfish_2p/20191101_6f/f2_e1_omr.ome.btf"
>>> 
>>> f = tifffile.TiffFile(tiff_fn)
>>> mm = f.asarray(out='memmap')
Bus error (core dumped)
```

Why does this matter? Many scientific packages are not available in nixpkgs yet, so I run these using Anaconda in a buildFHSUserEnv, which triggers this error.

**Comment by tbenst** [comment]
Figured out a bit more thanks to gdb:
test.nix:
```
let
pkgs = import <nixpkgs> {};
in
with pkgs; stdenv.mkDerivation {
  name = "test";
  buildInputs = [
    (python3.withPackages (ps: [ps.tifffile]))
    gdb
  ];
}

```

Find path (otherwise will be missing import as gdb can't use wrapper):
```
> nix-shell test.nix
$ which python
/nix/store/z83h233zyisd6sc30na5kpgd5svk0qbh-python3-3.7.5-env/bin/python
> cat $(which python)
#! /nix/store/b34zjdmq5l8k6rwdykjx55yl9r9isl8k-bash-4.4-p23/bin/bash -e
export NIX_PYTHONEXECUTABLE='/nix/store/z83h233zyisd6sc30na5kpgd5svk0qbh-python3-3.7.5-env/bin/python3.7'
export NIX_PYTHONPATH='/nix/store/z83h233zyisd6sc30na5kpgd5svk0qbh-python3-3.7.5-env/lib/python3.7/site-packages'
export PYTHONNOUSERSITE='true'
exec "/nix/store/v93lqlrwf9sgl8zjzmvvls0y31y0wfvy-python3.7-tifffile-2019.7.26/bin/tifffile"  "$@"
```

Make test.py:
```
import sys
sys.path.append("/nix/store/z83h233zyisd6sc30na5kpgd5svk0qbh-python3-3.7.5-env/lib/python3.7/site-packages")
import tifffile
tiff_fn  = "/data/dlab/zfish_2p/20191101_6f/f2_e1_omr.ome.btf"

mm = tifffile.TiffFile(tiff_fn).asarray(out='memmap')
print(type(mm))
```

Use gdb:
```
> nix-shell test.nix
$ gdb /nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/bin/python
Reading symbols from /nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/bin/python...
(No debugging symbols found in /nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/bin/python)
(gdb) run test.py
Starting program: /nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/bin/python test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/xlxiw4rnxx2dksa91fizjzf7jb5nqghc-glibc-2.27/lib/libthread_db.so.1".
[New Thread 0x7fffcb585700 (LWP 24892)]
[New Thread 0x7fffcad84700 (LWP 24893)]
[New Thread 0x7fffca583700 (LWP 24894)]
[New Thread 0x7fffc9d82700 (LWP 24895)]
[New Thread 0x7fffc9581700 (LWP 24896)]
[New Thread 0x7fffc8d80700 (LWP 24897)]
[New Thread 0x7fffc857f700 (LWP 24898)]
[New Thread 0x7fffc7d7e700 (LWP 24899)]

Thread 7 "python" received signal SIGBUS, Bus error.
[Switching to Thread 0x7fffc8d80700 (LWP 24897)]
0x00007ffff79dca2f in __memmove_avx_unaligned_erms () from /nix/store/xlxiw4rnxx2dksa91fizjzf7jb5nqghc-glibc-2.27/lib/libc.so.6
```
A thread does a bad memory access in `nix-shell`. This does not occur outside of `nix-shell`

**Comment by tbenst** [comment]
[Source code for tifffile](https://www.lfd.uci.edu/~gohlke/code/tifffile.py.html). To rule out if threading is causing the issue, I [patched tifffile](https://gist.github.com/7db5a9aa9b221e67ba85c5642b23f094) so that it does not use multithreading. I get basically the same result:

```
Starting program: /nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/bin/python /home/tyler/lib/tiff.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/xlxiw4rnxx2dksa91fizjzf7jb5nqghc-glibc-2.27/lib/libthread_db.so.1".
started
main
Program received signal SIGBUS, Bus error.
0x00007ffff79dca2f in __memmove_avx_unaligned_erms () from /nix/store/xlxiw4rnxx2dksa91fizjzf7jb5nqghc-glibc-2.27/lib/libc.so.6
```

**Comment by tbenst** [comment]
Using `poetry2nix` and same test procedure as above in a nix-shell, I got a similar error, although at least python caught it this time: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/1bsn6n4qjl2ng2q4vgg1w3mj6s13y7jz-python3-3.7.6-env/lib/python3.7/site-packages/tifffile/tifffile.py", line 2345, in asarray
    result = stack_pages(pages, out=out, maxworkers=maxworkers)
  File "/nix/store/1bsn6n4qjl2ng2q4vgg1w3mj6s13y7jz-python3-3.7.6-env/lib/python3.7/site-packages/tifffile/tifffile.py", line 11252, in stack_pages
    func(page, i)
  File "/nix/store/1bsn6n4qjl2ng2q4vgg1w3mj6s13y7jz-python3-3.7.6-env/lib/python3.7/site-packages/tifffile/tifffile.py", line 11247, in func
    **kwargs)
  File "/nix/store/1bsn6n4qjl2ng2q4vgg1w3mj6s13y7jz-python3-3.7.6-env/lib/python3.7/site-packages/tifffile/tifffile.py", line 5531, in asarray
    return TiffPage.asarray(self, *args, **kwargs)
  File "/nix/store/1bsn6n4qjl2ng2q4vgg1w3mj6s13y7jz-python3-3.7.6-env/lib/python3.7/site-packages/tifffile/tifffile.py", line 4709, in asarray
    out=out
  File "/nix/store/1bsn6n4qjl2ng2q4vgg1w3mj6s13y7jz-python3-3.7.6-env/lib/python3.7/site-packages/tifffile/tifffile.py", line 6506, in read_array
    n = fh.readinto(result)
OSError: [Errno 14] Bad address
```

**Comment by tbenst** [comment]
I wanted to test the hypothesis that this is some 32-bit restriction, but I succeeded on using `nix-shell` to memmap a 6.5GB file. I also succeeded in memmaping a 16GB file. When I tested another 73GB file in `nix-shell`, I triggered the same error. Once again, this error does not occur outside of `nix-shell`.
