### ISSUE TITLE
lollypop broken with `Namespace Gtk not available`

### ISSUE THREAD

**Issue by lovesegfault** [NixOS/nixpkgs#75844]
**Describe the bug**
`lollypop` won't launch reporting:
```
❯ lollypop
Traceback (most recent call last):
  File "/nix/store/jmg9wvq7jh4b51flfp3516cb90k9h7pj-lollypop-1.2.16/bin/.lollypop-wrapped", line 21, in <module>
    gi.require_version("Gtk", "3.0")
  File "/nix/store/ag0a9z6y785kbzyss0982j26wlx2xank-python3.7-pygobject-3.32.1/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

**To Reproduce**
1. `cd nixpkgs`
2. `nix-build . -A lollypop`
3. `./result/bin/lollypop`

**Expected behavior**
For lollypop to run, like it did before

**Metadata**
```
❯ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.3, NixOS, 20.03pre205624.8636580d6f4 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre205624.8636580d6f4"`
 - channels(bemeurer): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: lollypop
# a list of nixos modules affected by the problem
module:
```

**Comment by lovesegfault** [comment]
cc. @worldofpeace

**Comment by lovesegfault** [comment]
Here's the culprit, added by @worldofpeace:
```
abe3475df8fd133045cd01fb14e0d7013cecf66e is the first bad commit
commit abe3475df8fd133045cd01fb14e0d7013cecf66e
Author: worldofpeace <worldofpeace@protonmail.ch>
Date:   Tue Dec 10 18:23:57 2019 -0500

    treewide: remove bash snippets in flags

    Co-Authored-By: Jan Tojnar <jtojnar@gmail.com>

 pkgs/applications/audio/lollypop/default.nix       |  6 ++---
 .../graphics/rapid-photo-downloader/default.nix    | 18 ++++++++-------
 pkgs/applications/misc/multibootusb/default.nix    | 24 +++++++++++---------
 pkgs/applications/misc/plover/default.nix          |  7 +++---
 .../networking/browsers/webmacs/default.nix        | 26 ++++++++++++----------
 .../instant-messengers/blink/default.nix           | 12 +++++-----
 pkgs/development/python-modules/spyder/default.nix |  7 +++---
 pkgs/games/anki/default.nix                        | 11 +++++----
 pkgs/games/mnemosyne/default.nix                   | 11 ++++-----
 9 files changed, 68 insertions(+), 54 deletions(-)
```

**Comment by lovesegfault** [comment]
Seems to be related to https://github.com/NixOS/nixpkgs/pull/75054#discussion_r357656916

**Comment by lovesegfault** [comment]
This suggested patch does not work: 
```patch
diff --git a/pkgs/applications/audio/lollypop/default.nix b/pkgs/applications/audio/lollypop/default.nix
index 2d2062696d7..93194f6bf67 100644
--- a/pkgs/applications/audio/lollypop/default.nix
+++ b/pkgs/applications/audio/lollypop/default.nix
@@ -80,7 +80,9 @@ python3.pkgs.buildPythonApplication rec  {
   dontWrapGApps = true;
 
   preFixup = ''
-    makeWrapperArgs+=("''${gappsWrapperArgs[@]}")
+    # TODO: A bug in python wrapper
+    # see https://github.com/NixOS/nixpkgs/pull/75054#discussion_r357656916
+    local -a makeWrapperArgs="''${gappsWrapperArgs[@]}"
   '';
 
   meta = with lib; {
```

**Comment by worldofpeace** [comment]
I happen to maintain this particular package also. I'll see if we can fix it quickly.

**Comment by worldofpeace** [comment]
I believe this should just work, @jtojnar suggested the setup-hook was broken and it is. Will fix.

**Comment by jtojnar** [comment]
Fixed?

**Comment by worldofpeace** [comment]
No https://github.com/NixOS/nixpkgs/issues/78803

**Comment by cocreature** [comment]
At least for me this is fixed now, thanks a lot @worldofpeace!

**Comment by lovesegfault** [comment]
Correct, this issue has been fixed through a series of PRs, courtesy of @worldofpeace and @jtojnar!
