### ISSUE TITLE
multibootusb does not run

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#76844]
**Describe the bug**

`multibootusb` fails to run giving the following error messages:

```
$ nix-shell -p multibootusb

$ multibootusb 
Using python version  3.6.10 (default, Dec 18 2019, 19:48:10) 
[GCC 8.3.0] on platform Linux-5.4.6-x86_64-with-glibc2.3.4
Could not find resource 'data/tools/mbr.bin'.
Could not find resource 'data/tools/gdisk/gdisk.exe'.
Could not find resource 'data/version.txt'.
Traceback (most recent call last):
  File "/nix/store/0mv1y6cv91hcd8abiz01baii2r4gl1ly-multibootusb-9.2.0/bin/.multibootusb-wrapped", line 216, in <module>
    running_from()
  File "/nix/store/0mv1y6cv91hcd8abiz01baii2r4gl1ly-multibootusb-9.2.0/bin/.multibootusb-wrapped", line 58, in running_from
    gen.log('Running multibootusb version ' + gen.mbusb_version() + ' from installed system...')
  File "/nix/store/0mv1y6cv91hcd8abiz01baii2r4gl1ly-multibootusb-9.2.0/lib/python3.6/site-packages/scripts/gen.py", line 311, in mbusb_version
    version = open(resource_path(os.path.join("data", "version.txt")), 'r').read().strip()
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 20.03pre206632.b0bbacb5213 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre206632.b0bbacb5213"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: multibootusb
```

**Comment by romildo** [comment]
With recent updates it works again:

```
$ sudo multibootusb
[sudo] password for romildo: 
Using python version  3.6.10 (default, Dec 18 2019, 19:48:10) 
[GCC 9.2.0] on platform Linux-5.4.8-x86_64-with-glibc2.3.4
Running multibootusb version 9.2.0 from installed system...
Starting multibootusb GUI...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
No USB device found...
```
