### ISSUE TITLE
Can't build with nix-build

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#7712]
Hello! Trying to build https://github.com/jagajaga/ninja-thesis using `nix-build` and getting
```
these derivations will be built:
  /nix/store/9admcfbmi2sni406phh2k4w9facc0qx9-thesis.drv
building path(s) ‘/nix/store/0csik8aw0s1brbnl84y28axmvn2wp86k-thesis’
unpacking sources
unpacking source archive /nix/store/41ic6iw0v0kw4nwvv6siyzab33322xd0-ninja-thesis
source root is ninja-thesis
patching sources
configuring
invalid lock file in /tmp/nix-build-thesis.drv-6/ninja-thesis
Setting top to                           : /tmp/nix-build-thesis.drv-6/ninja-thesis 
Setting out to                           : /tmp/nix-build-thesis.drv-6/ninja-thesis/build 
Checking for program tex                 : /nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/bin/tex 
Checking for program latex               : /nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/bin/latex 
Checking for program pdflatex            : /nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/bin/pdflatex 
Checking for program xelatex             : /nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/bin/xelatex 
Checking for program bibtex              : /nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/bin/bibtex 
Checking for program dvips               : /nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/bin/dvips 
Checking for program dvipdf              : /nix/store/v558jkab12a24k2gnvk5y8nlymv5lhnw-ghostscript-9.15/bin/dvipdf 
Checking for program ps2pdf              : /nix/store/v558jkab12a24k2gnvk5y8nlymv5lhnw-ghostscript-9.15/bin/ps2pdf 
Checking for program makeindex           : /nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/bin/makeindex 
Checking for program pdf2ps              : /nix/store/v558jkab12a24k2gnvk5y8nlymv5lhnw-ghostscript-9.15/bin/pdf2ps 
Checking for program pandoc              : /nix/store/qjxx9lj1p2zn404w3jwrsdizs6axk7ca-haskell-pandoc-1.13.2.1/bin/pandoc 
'configure' finished successfully (0.013s)
building
Waf: Entering directory `/tmp/nix-build-thesis.drv-6/ninja-thesis/build'
[3/8] pandoc: ch_First/sec_Intro.pd -> build/ch_First/sec_Intro.latex
[3/8] pandoc: Introduction.pd -> build/Introduction.latex
[3/8] pandoc: ch_First/sec_Moar.pd -> build/ch_First/sec_Moar.latex
[4/8] pandoc: ch_Second/sec_Text.pd -> build/ch_Second/sec_Text.latex
[5/8] pandoc: Conclusion.pd -> build/Conclusion.latex
[6/8] pandoc: Licensing.pd -> build/Licensing.latex
[7/8] pandoc: build/Introduction.latex ch_First/chapter.latex build/ch_First/sec_Intro.latex build/ch_First/sec_Moar.latex ch_Second/chapter.latex build/ch_Second/sec_Text.latex build/Conclusion.latex build/Licensing.latex -> build/main.latex
[8/8] xelatex: build/main.latex -> build/main.pdf
first pass on xelatex
This is XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015/dev) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(/tmp/nix-build-thesis.drv-6/ninja-thesis/build/main.latex
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.
(/tmp/nix-build-thesis.drv-6/ninja-thesis/preamble.latex
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/extsizes/extreport.cls
Document Class: extreport 1996/10/08 v1.0 Non Standard LaTeX document class

(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/extsizes/size14.clo)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/base/exscale.sty))
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/extsizes/extsizes.sty

Package ExtSizes Warning: It is better to use one of the extsizes classes,
 if you can.


(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/extsizes/size14.clo))
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/geometry/geometry.sty
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/graphics/keyval.sty)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/gen
eric/oberdiek/ifpdf.sty)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/gen
eric/oberdiek/ifvtex.sty)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/gen
eric/ifxetex/ifxetex.sty))
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/textpos/textpos.sty
Package: textpos 2014/01/03 1.7j, absolute positioning of text on the page

(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/ms/everyshi.sty)
Grid set 16 x 16 = 37.34424pt x 52.81541pt
TextBlockOrigin set to 0pt x 0pt
)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/fontspec/fontspec.sty
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/l3kernel/expl3.sty
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/l3kernel/expl3-code.tex
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/etex-pkg/etex.sty))
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/l3kernel/l3unicode-data.def)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/l3kernel/l3xdvipdfmx.def))
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/l3packages/xparse/xparse.sty)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/fontspec/fontspec-patches.sty)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/fontspec/fontspec-xetex.sty
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/base/fontenc.sty
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/euenc/eu1enc.def)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/euenc/eu1lmr.fd)Fontconfig error: Cannot load default config file
)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/xel
atex/xunicode/xunicode.sty
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/tipa/t3enc.def
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/euenc/eu1lmss.fd))
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/graphics/graphicx.sty
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/graphics/graphics.sty
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/graphics/trig.sty)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/latexconfig/graphics.cfg)
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/xel
atex/xetex-def/xetex.def))))
(/nix/store/a5h94i4ysxcjzm493i07hc4cz1m1h0ma-TeXLive-linkdir/texmf-dist/tex/lat
ex/fontspec/fontspec.cfg)))kpathsea:make_tex: Invalid fontname `Liberation Serif', contains ' '


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "Liberation Serif" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.9 \setmainfont{Liberation Serif}
                                  
? 
! Emergency stop.
!...............................................  
                                                  
l.9 \setmainfont{Liberation Serif}
                                  
No pages of output.
Transcript written on main.log.
Waf: Leaving directory `/tmp/nix-build-thesis.drv-6/ninja-thesis/build'
Build failed
Traceback (most recent call last):
  File "/tmp/nix-build-thesis.drv-6/ninja-thesis/.waf-1.7.10-4f6df1d839dc35640834d81573053140/waflib/Task.py", line 123, in process
    ret=self.run()
  File "/tmp/nix-build-thesis.drv-6/ninja-thesis/.waf-1.7.10-4f6df1d839dc35640834d81573053140/waflib/Task.py", line 47, in run
    return m1(self)
  File "/tmp/nix-build-thesis.drv-6/ninja-thesis/.waf-1.7.10-4f6df1d839dc35640834d81573053140/waflib/Task.py", line 47, in run
    return m1(self)
  File "/tmp/nix-build-thesis.drv-6/ninja-thesis/.waf-1.7.10-4f6df1d839dc35640834d81573053140/waflib/Tools/tex.py", line 161, in run
    self.check_status('error when calling latex',fun())
  File "/tmp/nix-build-thesis.drv-6/ninja-thesis/.waf-1.7.10-4f6df1d839dc35640834d81573053140/waflib/Tools/tex.py", line 100, in check_status
    raise Errors.WafError("%r command exit status %r"%(msg,retcode))
WafError: 'error when calling latex' command exit status 1

builder for ‘/nix/store/9admcfbmi2sni406phh2k4w9facc0qx9-thesis.drv’ failed with exit code 1
error: build of ‘/nix/store/9admcfbmi2sni406phh2k4w9facc0qx9-thesis.drv’ failed
```

But if I use `nix-shell --pure` I can build easily with these commands
```
$ python ./waf configure
$ python ./waf
```

**Comment by danbst** [comment]
can you try `preConfigurePhase` instead of `configurePhase`?
I've recently got into same problem, that `configurePhase` override stopped working.

Another solution is to move all build steps to `installPhase` and specify

```
phases = "installPhase";
```

**Comment by jagajaga** [comment]
Thanks for your suggestion, but I can try it only in September :(

**Comment by danbst** [comment]
I've tried it myself. And know what? it failed for me because of interactive mode of builder. Setting 

```
  buildPhase = ''
    yes "" | ${python.interpreter} ./waf
  '';
```
fixed it and your error did not occure (tested against master)
