### ISSUE TITLE
python3Packages.tensorflow: undefined symbols in python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/ops/_model_ops.so

### ISSUE THREAD

**Issue by andir** [NixOS/nixpkgs#77626]
**Describe the bug**

Tensorflow 1.15.0 on current unstable commit (e.g. 59c4035e58e) fails to load the shared library `lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/ops/_model_ops.so`. It tries to find the symbol `_ZNK10tensorflow12tensorforest20DecisionTreeResource12TraverseTreeERKSt10unique_ptrINS0_13TensorDataSetESt14default_deleteIS3_EEiPiPNS0_8TreePathE`, fails and bails out.

The missing symbol demangles to: `tensorflow::tensorforest::DecisionTreeResource::TraverseTree(std::unique_ptr<tensorflow::tensorforest::TensorDataSet, std::default_delete<tensorflow::tensorforest::TensorDataSet> > const&, int, int*, tensorflow::tensorforest::TreePath*) const`

**To Reproduce**
`nix-shell -I nixpkgs=. -E 'with import <nixpkgs> {}; (python3.withPackages (p: [p.tensorflow])).env' --run "python -c 'from tensorflow.contrib import tensor_forest'"`

```bash
$ nix-shell -I nixpkgs=. -E 'with import <nixpkgs> {}; (python3.withPackages (p: [p.tensorflow])).env' --run "python -c 'from tensorflow.contrib import tensor_forest'"
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/nix/store/bzvpdbzdy3a1qba8f9ynrzyz811c10pp-python3-3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow_core/contrib/__init__.py", line 90, in <module>
    from tensorflow.contrib import tensor_forest
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/__init__.py", line 21, in <module>
    from tensorflow.contrib.tensor_forest.client import *
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/__init__.py", line 21, in <module>
    from tensorflow.contrib.tensor_forest.client import *
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/client/__init__.py", line 22, in <module>
    from tensorflow.contrib.tensor_forest.client import random_forest
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/client/random_forest.py", line 27, in <module>
    from tensorflow.contrib.tensor_forest.python import tensor_forest
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/__init__.py", line 21, in <module>
    from tensorflow.contrib.tensor_forest.python import tensor_forest
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/tensor_forest.py", line 30, in <module>
    from tensorflow.contrib.tensor_forest.python.ops import model_ops
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/ops/model_ops.py", line 42, in <module>
    resource_loader.get_path_to_datafile("_model_ops.so"))
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow_core/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /nix/store/nyx0n2hpw40n90izaxfv77qjqdpfrijk-python3-3.7.6-env/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/ops/_model_ops.so: undefined symbol: _ZNK10tensorflow12tensorforest20DecisionTreeResource12TraverseTreeERKSt10unique_ptrINS0_13TensorDataSetESt14default_deleteIS3_EEiPiPNS0_8TreePathE
```

**Expected behavior**
The import should succeed as it did with TF 1.14.0.

**Additional context**
I tried reproducing this with the official TF 1.15.0 docker image but failed so it seems like a unique nipxkgs issue.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - tensorflow
  - python3Packages.tensorflow
```

cc @timokau @prusnak

**Comment by timokau** [comment]
Did you try `git bisect`'ing it?

**Comment by andir** [comment]
> Did you try `git bisect`'ing it?

I have not tried that yet as I was hoping someone would have an idea where this comes from :)

**Comment by andir** [comment]
I started bisecting this now.

**Comment by andir** [comment]
While bisecting throught nixpkgs I can already tell that none of the 1.15.0 versions seem to have ever "worked" (regarding the described bug). I am still trying to figure out if that bug was introduced before 1.15.0 but that will likely require a lot more hours of churning through nixpkgs.

**Comment by andir** [comment]
The bisect run just finished;

```
3c3ac19c43ef1b8b7459f9da1d0d5bd8fcc42fda is the first bad commit
commit 3c3ac19c43ef1b8b7459f9da1d0d5bd8fcc42fda           
Author: Roger Qiu <roger.qiu@polyhack.io>      
Date:   Thu Jan 24 15:44:34 2019 +1100           
                                                          
    dvc: init at 0.24.3                                   
                             
 .../version-management/dvc/default.nix             | 65 ++++++++++++++++++++++
 .../version-management/dvc/dvc-daemon.patch        | 21 +++++++
 pkgs/top-level/all-packages.nix                    |  9 +++
 3 files changed, 95 insertions(+)               
 create mode 100644 pkgs/applications/version-management/dvc/default.nix
 create mode 100644 pkgs/applications/version-management/dvc/dvc-daemon.patch
bisect run success   
```
The bisect log and the test script that I used are here:
https://gist.github.com/andir/f4aec736acb7c1c25d98bd8b46de8918
Note: There were a bazillion commits on which the tensorflow package couldn't even be built. So it might be a totally different change.

**Comment by timokau** [comment]
An package init can't really be the first bad commit. What do you do when tf doesn't build? You should probably `git bisect skip` then.

**Comment by gilligan** [comment]
> An package init can't really be the first bad commit. What do you do when tf doesn't build? You should probably git bisect skip then.

What makes you say that? It builds. The error is _at runtime_ and there is no test that would reveal this. So I would say this could definitely be broken from the very beginning.

**Comment by timokau** [comment]
Yes, but the commit @andir listed just adds a completely unrelated package. It doesn't change anything in the tensorflow build.

**Comment by gilligan** [comment]
@timokau FWIW i'm not sure the bisect was even worth it. I think someone who actually understands bazel and knows the tensorflow build needs to look at the error. Neither applies to me ;(

**Comment by Rakesh4G** [comment]
Hi, 
I have taken the latest changes, but still facing this issue. Any idea, if i am missing anything here

```Traceback (most recent call last):
  File "test.py", line 35, in <module>
    test.train_head(training_set=dataset_train, validation_set=dataset_val, epochs=1)
  File "/tests/toy/model.py", line 86, in train_head
    layers="heads",
  File "/nix/store/dh2n0fv0yfkl0r9wn7yivgvwa8sz5p58-python3.7-mask-rcnn-2.1/lib/python3.7/site-packages/mrcnn/model.py", line 2341, in train
    histogram_freq=0, write_graph=True, write_images=False),
  File "/nix/store/n8098wmhhhqmd7pwxnzjd3kplbddrwnc-python3.7-Keras-2.3.1/lib/python3.7/site-packages/keras/callbacks/tensorboard_v1.py", line 96, in __init__
    from tensorflow.contrib.tensorboard.plugins import projector
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 959, in _find_and_load_unlocked
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/nix/store/n8nviwmllwqv0fjsar8v8k8gjap1vhcw-python3-3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/__init__.py", line 90, in <module>
    from tensorflow.contrib import tensor_forest
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/__init__.py", line 21, in <module>
    from tensorflow.contrib.tensor_forest.client import *
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/__init__.py", line 21, in <module>
    from tensorflow.contrib.tensor_forest.client import *
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/client/__init__.py", line 22, in <module>
    from tensorflow.contrib.tensor_forest.client import random_forest
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/client/random_forest.py", line 27, in <module>
    from tensorflow.contrib.tensor_forest.python import tensor_forest
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/__init__.py", line 21, in <module>
    from tensorflow.contrib.tensor_forest.python import tensor_forest
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/tensor_forest.py", line 30, in <module>
    from tensorflow.contrib.tensor_forest.python.ops import model_ops
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/ops/model_ops.py", line 42, in <module>
    resource_loader.get_path_to_datafile("_model_ops.so"))
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/ops/_model_ops.so: undefined symbol: _ZNK10tensorflow12tensorforest20DecisionTreeResource12TraverseTreeERKSt10unique_ptrINS0_13TensorDataSetESt14default_deleteIS3_EEiPiPNS0_8TreePathE
```

**Comment by Rakesh4G** [comment]
> Hi,
> I have taken the latest changes, but still facing this issue. Any idea, if i am missing anything here
> 
> ```
>   File "test.py", line 35, in <module>
>     test.train_head(training_set=dataset_train, validation_set=dataset_val, epochs=1)
>   File "/tests/toy/model.py", line 86, in train_head
>     layers="heads",
>   File "/nix/store/dh2n0fv0yfkl0r9wn7yivgvwa8sz5p58-python3.7-mask-rcnn-2.1/lib/python3.7/site-packages/mrcnn/model.py", line 2341, in train
>     histogram_freq=0, write_graph=True, write_images=False),
>   File "/nix/store/n8098wmhhhqmd7pwxnzjd3kplbddrwnc-python3.7-Keras-2.3.1/lib/python3.7/site-packages/keras/callbacks/tensorboard_v1.py", line 96, in __init__
>     from tensorflow.contrib.tensorboard.plugins import projector
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 959, in _find_and_load_unlocked
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
>     module = self._load()
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
>     module = _importlib.import_module(self.__name__)
>   File "/nix/store/n8nviwmllwqv0fjsar8v8k8gjap1vhcw-python3-3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/__init__.py", line 90, in <module>
>     from tensorflow.contrib import tensor_forest
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/__init__.py", line 21, in <module>
>     from tensorflow.contrib.tensor_forest.client import *
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/__init__.py", line 21, in <module>
>     from tensorflow.contrib.tensor_forest.client import *
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/client/__init__.py", line 22, in <module>
>     from tensorflow.contrib.tensor_forest.client import random_forest
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/client/random_forest.py", line 27, in <module>
>     from tensorflow.contrib.tensor_forest.python import tensor_forest
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/__init__.py", line 21, in <module>
>     from tensorflow.contrib.tensor_forest.python import tensor_forest
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/tensor_forest.py", line 30, in <module>
>     from tensorflow.contrib.tensor_forest.python.ops import model_ops
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/ops/model_ops.py", line 42, in <module>
>     resource_loader.get_path_to_datafile("_model_ops.so"))
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/util/loader.py", line 56, in load_op_library
>     ret = load_library.load_op_library(path)
>   File "/nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename)
> tensorflow.python.framework.errors_impl.NotFoundError: /nix/store/wrzrbvkvcql09fml884ar9zyxf1bwy78-python3.7-tensorflow-gpu-1.15.1/lib/python3.7/site-packages/tensorflow_core/contrib/tensor_forest/python/ops/_model_ops.so: undefined symbol: _ZNK10tensorflow12tensorforest20DecisionTreeResource12TraverseTreeERKSt10unique_ptrINS0_13TensorDataSetESt14default_deleteIS3_EEiPiPNS0_8TreePathE
> ```

It was mistake at my end. Fix works as described above.
