### ISSUE TITLE
Document pypy+cffi problems

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#7785]
if a ppy package depends on pkgs.cffi it results into 

```
Traceback (most recent call last):
  File "<builtin>/app_main.py", line 75, in run_toplevel
  File "setup.py", line 338, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/nix/store/r8kqnhfvhgskyixnirgcl0mxh0lynnv7-pypy2.5-distutils.cfg/lib/pypy2.5/site-packages/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/nix/store/r8kqnhfvhgskyixnirgcl0mxh0lynnv7-pypy2.5-distutils.cfg/lib/pypy2.5/site-packages/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/nix/store/r8kqnhfvhgskyixnirgcl0mxh0lynnv7-pypy2.5-distutils.cfg/lib/pypy2.5/site-packages/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/nix/store/r8kqnhfvhgskyixnirgcl0mxh0lynnv7-pypy2.5-distutils.cfg/lib/pypy2.5/site-packages/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 106, in finalize_options
    self.distribution.ext_modules = get_ext_modules()
  File "setup.py", line 83, in get_ext_modules
    from cryptography.hazmat.primitives import constant_time, padding
  File "/tmp/nix-build-pypy2.5-cryptography-0.6.1.drv-0/cryptography-0.6.1/cryptography/hazmat/primitives/constant_time.py", line 32, in <module>
    _ffi = cffi.FFI()
  File "/nix/store/is0m4a80scqhnag2mfkklyzxw6x9y67m-pypy2.5-cffi-0.8.6/lib/pypy2.5/site-packages/cffi/api.py", line 58, in __init__
    assert backend.__version__ == __version__
AssertionError
builder for ‘/nix/store/sihh2ldmqx7mlcylnvx7qsqpiz9y4irl-pypy2.5-cryptography-0.6.1.drv’ failed with exit code 1
```

The solution is not to depend on cffi as pypy already ships with it.

**Comment by domenkozar** [comment]
`cffi` is now `null` for PyPy in #11086
