### ISSUE TITLE
node-gyp install doesn't work on Darwin

### ISSUE THREAD

**Issue by stellarhoof** [NixOS/nixpkgs#78115]
**Describe the bug**
While trying to install `fsevents` on OS X (10.15.2 Catalina) inside a nix-shell with `node-12_x`, `node-gyp rebuild` tries to open `$PWD/$NIX_SSL_CERT_FILE` which fails since `NIX_SSL_CERT_FILE` is an absolute path.

**To Reproduce**
1. Enter nix shell with `nix-shell shell.nix`. The contents of `shell.nix` are
```
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "example-shell";
  buildInputs = [
    nodejs-12_x
  ];
  shellHook = ''
    export PATH="$PWD/node_modules/.bin/:$PATH"
  '';
}
```
2. Try to install `fsevents`: `npm install fsevents`

**Expected behavior**
Installation doesn't fail

**Screenshots**
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: ENOENT: no such file or directory, open '/Users/berserk/Code/bid-search/web/$NIX_SSL_CERT_FILE'
gyp ERR! stack     at Object.openSync (fs.js:440:3)
gyp ERR! stack     at Object.readFileSync (fs.js:342:35)
gyp ERR! stack     at readCAFile (/nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:437:15)
gyp ERR! stack     at download (/nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:409:22)
gyp ERR! stack     at /nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:162:19
gyp ERR! stack     at /nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/lib/node_modules/npm/node_modules/mkdirp/index.js:30:20
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:146:23)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/bin/node" "/nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/berserk/Code/bid-search/web/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: ENOENT: no such file or directory, open '/Users/berserk/Code/bid-search/web/$NIX_SSL_CERT_FILE'
gyp ERR! stack     at Object.openSync (fs.js:440:3)
gyp ERR! stack     at Object.readFileSync (fs.js:342:35)
gyp ERR! stack     at readCAFile (/nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:437:15)
gyp ERR! stack     at download (/nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:409:22)
gyp ERR! stack     at /nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:162:19
gyp ERR! stack     at /nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/lib/node_modules/npm/node_modules/mkdirp/index.js:30:20
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:146:23)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/bin/node" "/nix/store/zc90dvh8qa1d7jcggp1afn0hbimanqim-nodejs-12.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/berserk/Code/bid-search/web/node_modules/jest-haste-map/node_modules/fsevents
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
```

**Additional context**

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.2.0, macOS 10.15.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.2`
 - channels(berserk): `"nixpkgs-20.03pre209270.8da81465c19"`
 - nixpkgs: `/Users/berserk/.nix-defexpr/channels/nixpkgs`
```

**Comment by stellarhoof** [comment]
Pay no mind. It was a badly misconfigured node config.
