### ISSUE TITLE
Enable poetry package to be used with other interpreters than python3.7

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#78444]
The `poetry` package is currently packaged using python3.7. This creates an issue when the package is attempted to be installed using python3.8 because pip will try to import poetry, and since it exists in a different site-packages location, it's unable to be found.

Proposal:
  -- update the `format = "pyproject";` option to auto-include the new poetry package
  -- alter pyproject helper to override the version of python it's using so that it be used across many interpreter versions

example output:
```
Processing /build/source
    Preparing wheel metadata ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_internal/commands/wheel.py", line 158, in run
    resolver.resolve(requirement_set)
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 312, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 223, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
    self.metadata_directory = metadata_generator(self)
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_internal/operations/generate_metadata.py", line 136, in _generate_metadata
    return install_req.prepare_pep517_metadata()
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 606, in prepare_pep517_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 167, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "/nix/store/r9zas1x2nv9bn505hq6323171f5ik5ad-python3-3.8.1/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry'


builder for '/nix/store/0shl05cshc35328pzd5bayvynqk94qcx-python3.8-aria2p-0.7.0.drv' failed with exit code 2
error: build of '/nix/store/0shl05cshc35328pzd5bayvynqk94qcx-python3.8-aria2p-0.7.0.drv' failed
```

however, this will build as given by https://github.com/NixOS/nixpkgs/pull/77981

cc @FRidh

**Comment by jonringer** [comment]
no longer relevant due to https://github.com/NixOS/nixpkgs/pull/77437/files #80819
