### ISSUE TITLE
python 2 and scipy special at 15.06pre62649.f93a8ee

### ISSUE THREAD

**Issue by joelmo** [NixOS/nixpkgs#7870]
I get an error when trying to import scipy.special (this is needed for graph-tool).

```
[joelmo@jmdesk:~]$ python -c 'import scipy.special'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/joelmo/.nix-profile/lib/python2.7/site-packages/scipy/special/__init__.py", line 546, in <module>
    from ._ufuncs import *
ImportError: /home/joelmo/.nix-profile/lib/python2.7/site-packages/scipy/special/_ufuncs.so: undefined symbol: PyUnicode
UCS2_DecodeUTF8
```

Could this be related to change 380bd3f48?

**Comment by domenkozar** [comment]
It's probably related to UCS4 change
