### ISSUE TITLE
Pycharm won't start due to JVM x11 error (non-NixOS Linux)

### ISSUE THREAD

**Issue by rollf** [NixOS/nixpkgs#78728]
**Describe the bug**
I cannot run Jetbrains PyCharm on my non-NixOS linux. The error suggest issues with the xserver.

**To Reproduce**
```
$ nix-shell -p 'jetbrains.pycharm-community'
interactive shell

[nix-shell:~]$ pycharm-community 
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Invalid MIT-MAGIC-COOKIE-1 key2020-01-28 20:30:33,563 [    405]   WARN -        #com.intellij.idea.Main - java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable. 
java.util.concurrent.ExecutionException: java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at com.intellij.idea.StartupUtil.runInEdtAndWait(StartupUtil.java:678)
        at com.intellij.idea.StartupUtil.lambda$showUserAgreementAndConsentsIfNeeded$15(StartupUtil.java:673)
        at com.intellij.ui.AppUIUtil.showConsentsAgreementIfNeeded(AppUIUtil.java:332)
        at com.intellij.idea.StartupUtil.showUserAgreementAndConsentsIfNeeded(StartupUtil.java:673)
        at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:231)
        at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:213)
        at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:45)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:232)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1499)
        at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1318)
        at com.intellij.idea.StartupUtil.lambda$scheduleInitUi$9(StartupUtil.java:265)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more
```

**Expected behavior**
PyCharm (a GUI application) should start.

**Screenshots**
None

**Additional context**
This is a recent Nix installation. I have added [home-manager](https://github.com/rycee/home-manager). I get the same error when trying to install/run from home-manager.

I did get the same error message in home-manager right from the beginning (I first tried in home-manager). When starting pycharm within ``nix-shell -p 'jetbrains.pycharm-community'``  I first got something about "Internal error. Please report to http://jb.gg/ide/critical-startup-errors". I do not get the error anymore after reboot. 

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/ghccflvzq7rq3w02qa8dwiykdr2spsy7-nix-info
copying path '/nix/store/ghccflvzq7rq3w02qa8dwiykdr2spsy7-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.12.14-lp151.28.36-default, openSUSE Leap, 15.1`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(rollf): `"home-manager, nixpkgs-20.03pre210728.42a195919a1"`
 - nixpkgs: `/home/rollf/.nix-defexpr/channels/nixpkgs`
```
@edwtjo might be the person who could provide further insights.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: jetbrains.pycharm-community
# a list of nixos modules affected by the problem
module:
```

**Comment by rollf** [comment]
It does work on my Ubuntu Mint Machine

`` nix-shell -p "jetbrains.pycharm-community" --run "pycharm-community`` starts Pycharm as expected. I tested with an older an a recent nixpkgs version.


```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/vbl3vri2fip4r90bmlaiijgbbvi6c482-nix-info
copying path '/nix/store/vbl3vri2fip4r90bmlaiijgbbvi6c482-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-26-generic, Ubuntu, 19.10 (Eoan Ermine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(rolf): `"nixpkgs-19.09pre173147.03050e9749e"`
 - nixpkgs: `/home/rolf/.nix-defexpr/channels/nixpkgs`


 $ nix-shell -p nix-info --run "nix-info -m"                           
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-29-generic, Ubuntu, 19.10 (Eoan Ermine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(rolf): `"nixpkgs-20.03pre211021.690dd986b23"`
 - nixpkgs: `/home/rolf/.nix-defexpr/channels/nixpkgs`

```

**Comment by rollf** [comment]
I could solve the issue by running ``xhost +local:`` before as described here https://askubuntu.com/a/1113062
