### ISSUE TITLE
nix-review: xml.etree.ElementTree.ParseError: no element found: line 81451, column 0

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#78785]
**Describe the bug**
`nix-review` doesn't seem to run for some reason.

**To Reproduce**
cd nixpkgs
nix-review pr 78784

```
$ nix-review pr 78784
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/78784/head:refs/nixpkgs-review/1
Depuis https://github.com/NixOS/nixpkgs
 + 6e34d1453b0...6bd06d96b18 refs/pull/78784/head -> refs/nixpkgs-review/1  (mise à jour forcée)
$ git worktree add /home/bbigras2/.cache/nixpkgs-review/pr-78784/nixpkgs 274d02e4776d0b8b1884b57e7e6454223a9abb13
Préparation de l'arbre de travail (HEAD détachée 274d02e4776)
Mise à jour des fichiers: 100% (20861/20861), fait.
HEAD est maintenant à 274d02e4776 vimPlugins.vim-prosession: init at 2019-11-01
$ nix-env -f /home/bbigras2/.cache/nixpkgs-review/pr-78784/nixpkgs -qaP --xml --out-path --show-trace
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/c0h5vgxmzqij44gndw6s46q7gmwmchbd-nixpkgs-review-2.1.1/bin/.nix-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/c0h5vgxmzqij44gndw6s46q7gmwmchbd-nixpkgs-review-2.1.1/lib/python3.7/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/c0h5vgxmzqij44gndw6s46q7gmwmchbd-nixpkgs-review-2.1.1/lib/python3.7/site-packages/nixpkgs_review/cli/__init__.py", line 155, in main
    args.func(args)
  File "/nix/store/c0h5vgxmzqij44gndw6s46q7gmwmchbd-nixpkgs-review-2.1.1/lib/python3.7/site-packages/nixpkgs_review/cli/pr.py", line 54, in pr_command
    contexts.append((pr, review.build_pr(pr)))
  File "/nix/store/c0h5vgxmzqij44gndw6s46q7gmwmchbd-nixpkgs-review-2.1.1/lib/python3.7/site-packages/nixpkgs_review/review.py", line 131, in build_pr
    return self.build_commit(base_rev, pr_rev)
  File "/nix/store/c0h5vgxmzqij44gndw6s46q7gmwmchbd-nixpkgs-review-2.1.1/lib/python3.7/site-packages/nixpkgs_review/review.py", line 82, in build_commit
    base_packages = list_packages(str(self.worktree_dir()))
  File "/nix/store/c0h5vgxmzqij44gndw6s46q7gmwmchbd-nixpkgs-review-2.1.1/lib/python3.7/site-packages/nixpkgs_review/review.py", line 168, in list_packages
    for (event, elem) in context:
  File "/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/python3.7/xml/etree/ElementTree.py", line 1228, in iterator
    root = pullparser._close_and_return_root()
  File "/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/python3.7/xml/etree/ElementTree.py", line 1275, in _close_and_return_root
    root = self._parser.close()
xml.etree.ElementTree.ParseError: no element found: line 81451, column 0
```

**Expected behavior**

**Screenshots**

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.97, NixOS, 20.03pre210233.d1ba7dae91d (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03pre210639.e59dcf8ccec, nixos-hardware"`
 - channels(bbigras2): `"home-manager, nixos-19.09-19.09.1776.b926503738c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
It works for me:
```
% nix-review pr 78784
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/78784/head:refs/nixpkgs-review/1
remote: Enumerating objects: 524, done.
remote: Counting objects: 100% (524/524), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 734 (delta 521), reused 521 (delta 521), pack-reused 210
Receiving objects: 100% (734/734), 373.91 KiB | 12.89 MiB/s, done.
Resolving deltas: 100% (562/562), completed with 227 local objects.
From https://github.com/NixOS/nixpkgs
   8c651aa852c..af9bb2af8f0  master               -> refs/nixpkgs-review/0
 + 07fb9944a86...6bd06d96b18 refs/pull/78784/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /home/veprbl/.cache/nixpkgs-review/pr-78784/nixpkgs af9bb2af8f01a1638bbd2f57b60df494ac0720e9
Preparing worktree (detached HEAD af9bb2af8f0)
Updating files: 100% (20862/20862), done.
HEAD is now at af9bb2af8f0 Merge pull request #78328 from mkg20001/pkg/cinnamon-control-center
$ nix-env -f /home/veprbl/.cache/nixpkgs-review/pr-78784/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit 6bd06d96b18032f38531d3f424a95081c85f9979
Automatic merge went well; stopped before committing as requested
$ nix-env -f /home/veprbl/.cache/nixpkgs-review/pr-78784/nixpkgs -qaP --xml --out-path --show-trace --meta
$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/veprbl/.cache/nixpkgs-review/pr-78784/build.nix
[5 built, 35 copied (440.8 MiB), 105.1 MiB DL]
https://github.com/NixOS/nixpkgs/pull/78784
1 package built:
lego

% readlink `which nix-review`
/nix/store/c0h5vgxmzqij44gndw6s46q7gmwmchbd-nixpkgs-review-2.1.1/bin/nix-review
```

**Comment by worldofpeace** [comment]
The issue tracker for nixpkgs-review is at https://github.com/Mic92/nixpkgs-review.

**Comment by bbigras** [comment]
Oh sorry.

**Comment by veprbl** [comment]
@bbigras No worries!
