### ISSUE TITLE
Squib: Board Game Prototyping DSL in Ruby

### ISSUE THREAD

**Issue by RocketPuppy** [NixOS/nixpkgs#79157]
**Project description**
Squib is a Ruby DSL for prototyping card and board games.

**Metadata**

* homepage URL: http://squib.rocks/
* source URL: https://github.com/andymeneely/squib
* license: MIT
* platforms: Windows, OSX, Linux

**Notes**
I think mostly this requires a few changes to the default gem config in ruby modules. Unfortunately I'm stuck and could use some help. Here's what I have so far:

A default.nix to tie everything together, based on the example in the bundix readme.
```nix
with (import <nixpkgs> {});
let
  gemConfig = defaultGemConfig // {
    rsvg2 = attrs: {
      nativeBuildInputs = [pkgconfig rake];
      buildInputs = [ librsvg ];
    };
  };
  gems = bundlerEnv {
    name = "retrograde";
    inherit ruby;
    inherit gemConfig;
    gemdir = ./.;
  };
in stdenv.mkDerivation {
  name = "retrograde";
  buildInputs = [gems ruby librsvg ];
}
```

```ruby
source 'https://rubygems.org'

gem 'squib'
```

The bundix generated gemset.nix https://gist.github.com/RocketPuppy/5c1bfd6a32b5f5078f9665c1e658b5cf, using `bundix --lock`.

With the addition of the extra dependencies to the `rsvg2` gem everything builds. However when I try to run the `squib` executable I get an error that GObject Introspection can't find the Typelib for Pango.

```
Traceback (most recent call last):
	9: from /nix/store/yl1vxj43l4x2x7p7whscsgrqd7sgms1d-retrograde/bin/squib:18:in `<main>'
	8: from /nix/store/yl1vxj43l4x2x7p7whscsgrqd7sgms1d-retrograde/bin/squib:18:in `load'
	7: from /nix/store/yl1vxj43l4x2x7p7whscsgrqd7sgms1d-retrograde/lib/ruby/gems/2.6.0/gems/squib-0.15.3/bin/squib:2:in `<top (required)>'
	6: from /nix/store/yl1vxj43l4x2x7p7whscsgrqd7sgms1d-retrograde/lib/ruby/gems/2.6.0/gems/squib-0.15.3/bin/squib:2:in `require'
	5: from /nix/store/sk12v8csvwiq1man8jrj7wyk7jcv3an3-ruby2.6.5-squib-0.15.3/lib/ruby/gems/2.6.0/gems/squib-0.15.3/lib/squib.rb:3:in `<top (required)>'
	4: from /nix/store/sk12v8csvwiq1man8jrj7wyk7jcv3an3-ruby2.6.5-squib-0.15.3/lib/ruby/gems/2.6.0/gems/squib-0.15.3/lib/squib.rb:3:in `require'
	3: from /nix/store/280y9nis0wgjxfai8w2381wafiwz9a3x-ruby2.6.5-pango-3.4.1/lib/ruby/gems/2.6.0/gems/pango-3.4.1/lib/pango.rb:24:in `<top (required)>'
	2: from /nix/store/280y9nis0wgjxfai8w2381wafiwz9a3x-ruby2.6.5-pango-3.4.1/lib/ruby/gems/2.6.0/gems/pango-3.4.1/lib/pango.rb:29:in `<module:Pango>'
	1: from /nix/store/15cwaf1fp9cqk3an17gqm2qf2cd3djvq-ruby2.6.5-gobject-introspection-3.4.1/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:37:in `load'
/nix/store/15cwaf1fp9cqk3an17gqm2qf2cd3djvq-ruby2.6.5-gobject-introspection-3.4.1/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:37:in `require': Typelib file for namespace 'Pango' (any version) not found (GObjectIntrospection::RepositoryError::TypelibNotFound)
```

If I could get a little help fixing that issue I could make a PR to update the default gem config.

**Comment by RocketPuppy** [comment]
Based on https://github.com/NixOS/nixpkgs/issues/88912 I was able to figure out that all I needed was to have the required libraries in scope. So the solution is pretty simple, just make sure wherever you're going to be running the squib executable or using the ruby library has all of those libraries in scope.
