### ISSUE TITLE
aws-sam-cli 0.40.0 (NixOS unstable) fails to build Python projects

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#79379]
**Describe the bug**
`aws-sam-cli` version 0.40.0 from NixOS unstable fails to build Python projects with the following error:

Python **2.7** and Python **3.6** projects:

```shell
aws_lambda_builders.exceptions.MisMatchRuntimeError: python executable found in your path does not match runtime
Error: PythonPipBuilder:None - Binary validation failed!
```

Python **3.7** projects
```shell
PythonPipBuilder:ResolveDependencies raised unhandled exception
Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: ''
```

**To Reproduce**

```shell
# Clean up garbage
nix-collect-garbage
# Install aws-sam-cli from the latest unstable channel
nix-shell \
  -I https://releases.nixos.org/nixos/unstable/nixos-20.03pre211190.a21c2fa3ea2/nixexprs.tar.xz \
  -p aws-sam-cli 
```

```shell
# Disable telemetry
export SAM_CLI_TELEMETRY=0
# Create a new project
sam init
# choose AWS Quick Start Templates
# choose the runtime... Python 2.7, 3.6 or 3.7
# choose Hello World Example
```
enter the project directory and run

```
sam build --debug
```

### Python 3.7 error
```
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
PythonPipBuilder:ResolveDependencies raised unhandled exception
Traceback (most recent call last):
  File "/nix/store/pf7dlaih5dmy2688h4wsswkpnh7plzmn-python3.7-aws-lambda-builders-0.6.0/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/nix/store/pf7dlaih5dmy2688h4wsswkpnh7plzmn-python3.7-aws-lambda-builders-0.6.0/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 27, in execute
    pip = SubprocessPip(osutils=os_utils, python_exe=python_path)
  File "/nix/store/pf7dlaih5dmy2688h4wsswkpnh7plzmn-python3.7-aws-lambda-builders-0.6.0/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 556, in __init__
    import_string = pip_import_string(python_exe=self.python_exe)
  File "/nix/store/pf7dlaih5dmy2688h4wsswkpnh7plzmn-python3.7-aws-lambda-builders-0.6.0/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/compat.py", line 16, in pip_import_string
    pip_major_version = int(pip_version.split('.')[0])
ValueError: invalid literal for int() with base 10: ''

Build Failed
Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: ''
```

### Python 3.6 and 2.7 error

```
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Invalid executable for python at /nix/store/aw85aijllnc5spk2fqbivygrhx6x7411-python3-3.7.6/bin/python
Traceback (most recent call last):
  File "/nix/store/pf7dlaih5dmy2688h4wsswkpnh7plzmn-python3.7-aws-lambda-builders-0.6.0/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 52, in wrapper
    valid_path = validator.validate(executable_path)
  File "/nix/store/pf7dlaih5dmy2688h4wsswkpnh7plzmn-python3.7-aws-lambda-builders-0.6.0/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/validator.py", line 55, in validate
    runtime_path=runtime_path)
aws_lambda_builders.exceptions.MisMatchRuntimeError: python executable found in your path does not match runtime.
 Expected version: python3.6, Found version: /nix/store/aw85aijllnc5spk2fqbivygrhx6x7411-python3-3.7.6/bin/python.
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30

Build Failed
Error: PythonPipBuilder:None - Binary validation failed!

```

**Expected behavior**
The project builds successfully

**Screenshots**
N/A

**Additional context**

For the Python 2.7 and 3.6 runtimes, possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.101-hardened, NixOS, 19.09.2006.8b76b125205 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.2006.8b76b125205"`
 - channels(user): `"unstable-20.03pre211190.a21c2fa3ea2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
    - aws-sam-cli
# a list of nixos modules affected by the problem
module:
```

**Comment by stefano-m** [comment]
Honestly I have stopped using aws-sam-cli for the time being. Closing this issue to reduce noise.
