### ISSUE TITLE
google-cloud-sdk: gsutil does not work

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#79754]
**Describe the bug**

```
$ gsutil cp this gs://there
Traceback (most recent call last):
  File "/nix/store/w6sf268nsl8zbirfy8659wnrsbwiwjsq-google-cloud-sdk-268.0.0/google-cloud-sdk/platform/gsutil/gsutil", line 21, in <module>
    gsutil.RunMain()
  File "/nix/store/w6sf268nsl8zbirfy8659wnrsbwiwjsq-google-cloud-sdk-268.0.0/google-cloud-sdk/platform/gsutil/gsutil.py", line 123, in RunMain
    import gslib.__main__
  File "/nix/store/w6sf268nsl8zbirfy8659wnrsbwiwjsq-google-cloud-sdk-268.0.0/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 75, in <module>
    from gslib.command_runner import CommandRunner
  File "/nix/store/w6sf268nsl8zbirfy8659wnrsbwiwjsq-google-cloud-sdk-268.0.0/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 64, in <module>
    from gslib.tests.util import HAS_NON_DEFAULT_GS_HOST
ImportError: No module named tests.util
```

**To Reproduce**
1. `nix run -f '<nixpkgs>' google-cloud-sdk -c gsutil --help`

**Expected behavior**

Works.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0, NixOS, 20.03pre202933.bbeed8b9e7e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre212209.eee784a1bb6"`
 - channels(nagisa): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: google-cloud-sdk
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
cc @pradyuman @stephenmw @zimbatm

**Comment by mudrii** [comment]
I am getting same error

**Comment by edef1c** [comment]
Hmm, this only seems to come up in `MaybeCheckForAndOfferSoftwareUpdate`. I think we plausibly just want to remove that function.
