### ISSUE TITLE
tiledb-0.5.6 python packages fail a test and can't be build

### ISSUE THREAD

**Issue by DieGoldeneEnte** [NixOS/nixpkgs#80018]
**Describe the bug**
The package `python37Packages.tiledb` and `python38Packages.tiledb` can not be build on master, because
```
======================================================================
ERROR: test_ctx_thread_cleanup (test_libtiledb.HighlevelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/sj4r23dx840n2ih9d57qb7w9w0k6a6lr-python3.7-psutil-5.6.7/lib/python3.7/site-packages/psutil/_pslinux.py", line 1517, in wrapper
    return fun(self, *args, **kwargs)
  File "/nix/store/sj4r23dx840n2ih9d57qb7w9w0k6a6lr-python3.7-psutil-5.6.7/lib/python3.7/site-packages/psutil/_pslinux.py", line 1905, in threads
    st = f.read().strip()
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/s3rfykyz1y9hclasi6gaz91g8i0lind6-python3.7-tiledb-0.5.6/lib/python3.7/site-packages/tiledb/tests/test_libtiledb.py", line 2507, in test_ctx_thread_cleanup
    start_threads = len(thisproc.threads())
  File "/nix/store/sj4r23dx840n2ih9d57qb7w9w0k6a6lr-python3.7-psutil-5.6.7/lib/python3.7/site-packages/psutil/__init__.py", line 987, in threads
    return self._proc.threads()
  File "/nix/store/sj4r23dx840n2ih9d57qb7w9w0k6a6lr-python3.7-psutil-5.6.7/lib/python3.7/site-packages/psutil/_pslinux.py", line 1521, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=79)

----------------------------------------------------------------------
Ran 138 tests in 4.353s

FAILED (errors=1, skipped=7, expected failures=6)
```

I stumbled across this wile running nix-review, since it fails when testing unrelated requests.

**To Reproduce**
1. run `nix-build . -A python37Packages.tiledb` inside a cloned nixpkgs on master

**Expected behavior**
Build ends successfully.

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.2, NixOS, 20.03pre212208.8130f3c1c2b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(holger): `""`
 - channels(root): `"nixos-20.03pre212208.8130f3c1c2b, old-18.09.2574.a7e559a5504, unstable-20.03pre212208.8130f3c1c2b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - python37Packages.tiledb
  - python38Packages.tiledb
# a list of nixos modules affected by the problem
module:
```

**Comment by DieGoldeneEnte** [comment]
@FRidh I think you are the maintainer, could you have a look at this? I have no idea how tiledb works and don't know a trivial fix.

**Comment by marsam** [comment]
Looks like it's already fixed
https://hydra.nixos.org/job/nixpkgs/trunk/python37Packages.tiledb.x86_64-linux
