### ISSUE TITLE
nixosTests.redmine is broken

### ISSUE THREAD

**Issue by tfc** [NixOS/nixpkgs#80061]
```bash
$ nix-build nixos/tests/redmine.nix
...
machine# [    8.918041] systemd[1]: Starting redmine.service...
machine# [    9.009187] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]: /nix/store/nafc20sdd1813hjh5lc2s24yzr0n5rq1-redmine-env-4.1.0/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:22: warning: already initialized constant Bundler::ORIGINAL_ENV
machine# [    9.011837] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]: /nix/store/l1mn0yfbfyifk8z147qa4q1fdl523ibg-bundler-1.17.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:22: warning: previous definition of ORIGINAL_ENV was here
machine# [    9.014411] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]: /nix/store/nafc20sdd1813hjh5lc2s24yzr0n5rq1-redmine-env-4.1.0/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:24: warning: already initialized constant Bundler::SUDO_MUTEX
machine# [    9.017135] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]: /nix/store/l1mn0yfbfyifk8z147qa4q1fdl523ibg-bundler-1.17.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:24: warning: previous definition of SUDO_MUTEX was here
machine# [    9.035069] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]: /nix/store/nafc20sdd1813hjh5lc2s24yzr0n5rq1-redmine-env-4.1.0/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/feature_flag.rb:4:in `<module:Bundler>': uninitialized constant Bundler::FeatureFlag (NameError)
machine# [    9.040027] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/nafc20sdd1813hjh5lc2s24yzr0n5rq1-redmine-env-4.1.0/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/feature_flag.rb:3:in `<top (required)>'
machine# [    9.043201] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/g14byvcv13hy21mzfak30md74bbycvgx-ruby-2.5.7/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:72:in `require'
machine# [    9.045333] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/g14byvcv13hy21mzfak30md74bbycvgx-ruby-2.5.7/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:72:in `require'
machine# [    9.047499] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/nafc20sdd1813hjh5lc2s24yzr0n5rq1-redmine-env-4.1.0/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:478:in `feature_flag'
machine# [    9.050013] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/nafc20sdd1813hjh5lc2s24yzr0n5rq1-redmine-env-4.1.0/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:97:in `<class:CLI>'
machine# [    9.057029] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/nafc20sdd1813hjh5lc2s24yzr0n5rq1-redmine-env-4.1.0/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:7:in `<module:Bundler>'
machine# [    9.060133] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/nafc20sdd1813hjh5lc2s24yzr0n5rq1-redmine-env-4.1.0/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:6:in `<top (required)>'
machine# [    9.062448] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/g14byvcv13hy21mzfak30md74bbycvgx-ruby-2.5.7/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:72:in `require'
machine# [    9.065812] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/g14byvcv13hy21mzfak30md74bbycvgx-ruby-2.5.7/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:72:in `require'
machine# [    9.068125] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/nafc20sdd1813hjh5lc2s24yzr0n5rq1-redmine-env-4.1.0/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:23:in `block in <top (required)>'
machine# [    9.070428] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/nafc20sdd1813hjh5lc2s24yzr0n5rq1-redmine-env-4.1.0/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
machine# [    9.072850] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/nafc20sdd1813hjh5lc2s24yzr0n5rq1-redmine-env-4.1.0/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
machine# [    9.075099] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/mhn10fr7zw4c1ls35r07cal7jlylw7qg-redmine-4.1.0/share/redmine/bin/bundle:4:in `load'
machine# [    9.077066] ggd3zs9fiv396x10f27bp1acskxpz9ks-unit-script-redmine-pre-start[914]:    from /nix/store/mhn10fr7zw4c1ls35r07cal7jlylw7qg-redmine-4.1.0/share/redmine/bin/bundle:4:in `<main>'
machine# [    9.079360] systemd[1]: redmine.service: Control process exited, code=exited, status=1/FAILURE
machine# [    9.081404] systemd[1]: redmine.service: Failed with result 'exit-code'.
machine# [    9.082828] systemd[1]: Failed to start redmine.service.
machine# [    9.084073] systemd[1]: Reached target Multi-User System.
machine# [    9.085236] systemd[1]: Startup finished in 2.450s (kernel) + 6.602s (userspace) = 9.053s.
machine: running command: systemctl --no-pager show "redmine.service"
machine: running command: systemctl --no-pager show "redmine.service"
machine: exit status 0
(0.02 seconds)
(9.93 seconds)
error: unit ‘redmine.service’ reached state ‘failed’
(12.25 seconds)
unit ‘redmine.service’ reached state ‘failed’
cleaning up
killing machine (pid 6)
(0.00 seconds)
vde_switch: EOF on stdin, cleaning up and exiting
vde_switch: Could not remove ctl dir '/build/vde1.ctl': Directory not empty
builder for '/nix/store/7yn8mf1nmc807aym1v6143cmivw5v08b-vm-test-run-unnamed.drv' failed with exit code 255
error: build of '/nix/store/4mdciyi7nskzbr12hdy5vw5cdwfq71c6-vm-test-run-unnamed.drv', '/nix/store/7yn8mf1nmc807aym1v6143cmivw5v08b-vm-test-run-unnamed.drv' failed
```

/cc @aanderse (commit history)

**Comment by aanderse** [comment]
@tfc this has been fixed: https://github.com/NixOS/nixpkgs/pull/81442
