### ISSUE TITLE
nushell: fails to build on linux x86_64

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#80117]
**Describe the bug**
See https://hydra.nixos.org/build/112753844 & https://hydra.nixos.org/build/112753844/nixlog/1

```

--- stderr
error occured in handler:  ('event:   ', ('xcb', 'Present', 'RedirectNotify'))
Traceback (most recent call last):
  File "/build/nushell-0.9.0-vendor/xcb/rs_client.py", line 2448, in <module>
    module.generate()
  File "/build/nushell-0.9.0-vendor/xcb/xcbgen/state.py", line 108, in generate
    self.close()
  File "/build/nushell-0.9.0-vendor/xcb/rs_client.py", line 296, in rs_close
    _f.writeout(os.path.join(module.rs_srcdir, "ffi", "%s.rs" % _module_name(_ns.ext_name)))
  File "/build/nushell-0.9.0-vendor/xcb/rs_client.py", line 114, in writeout
    with open(path, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/build/nushell-0.9.0-vendor/xcb/src/ffi/present.rs'
thread 'main' panicked at 'processing of /build/nushell-0.9.0-vendor/xcb/xml/present.xml returned non-zero (1)', /build/nushell-0.9.0-vendor/xcb/build.rs:75:17
```

**To Reproduce**
1. Build package

**Expected behavior**
Should build on linux

Build on darwin works

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - nushell
# a list of nixos modules affected by the problem
module:
```

cc @filalex77 @marsam

**Comment by marsam** [comment]
It should be fixed by https://github.com/NixOS/nixpkgs/pull/80153
