### ISSUE TITLE
plasma-workspace: plasmashell crashing at display layout change or resume

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#80581]
**Describe the bug**

This is (at least one of) the reason(s) behind #80550. 
Attaching a new screen to my laptop, triggering the expansion of the workspace to a second display, makes plasmashell crash. The same or something similar happens at resuming from standby.

This is the log output of plasmashell:

```
trying to show an empty dialog
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
trying to show an empty dialog
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:302:17: QML QQuickText: Binding loop detected for property "width"
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:302:17: QML QQuickText: Binding loop detected for property "width"
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:302:17: QML QQuickText: Binding loop detected for property "width"
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:302:17: QML QQuickText: Binding loop detected for property "width"
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:302:17: QML QQuickText: Binding loop detected for property "width"
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:302:17: QML QQuickText: Binding loop detected for property "width"
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:302:17: QML QQuickText: Binding loop detected for property "width"
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:302:17: QML QQuickText: Binding loop detected for property "width"
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:302:17: QML QQuickText: Binding loop detected for property "width"
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml:302:17: QML QQuickText: Binding loop detected for property "width"
QQuickItem::stackAfter: Cannot stack StatusNotifierItem_QMLTYPE_333(0x75ab070, parent=0x3f0ce40, geometry=0,0 0x0) after StatusNotifierItem_QMLTYPE_333(0x69c46b0), which must be a sibling
KCrash: Attempting to start /nix/store/mxhd4fsbp2z52fajsvp0k21bsm98qwqq-plasma-workspace-5.16.5/bin/.plasmashell-wrapped from kdeinit
sock_file=/run/user/1000/kdeinit5__0
KCrash: Application '.plasmashell-wrapped' crashing...

[1]  + 13491 segmentation fault (core dumped)  plasmashell
```

That's the backtrace from the coredump:

```backtrace
Core was generated by `/run/current-system/sw/bin/plasmashell'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc9a5a93be0 in raise () from /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libc.so.6
[Current thread is 1 (Thread 0x7fc9a2557440 (LWP 13491))]
(gdb) bt 
#0  0x00007fc9a5a93be0 in raise () from /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libc.so.6
#1  0x00007fc9a7aa4cbc in KCrash::defaultCrashHandler(int) () from /nix/store/93kmr5s1kjbna916xiws5yv3hmqxd6pg-kcrash-5.61.0/lib/libKF5Crash.so.5
#2  <signal handler called>
#3  0x0000000000000000 in ?? ()
#4  0x00007fc9a7fc63ec in ?? () from /nix/store/hqwgzd0iyqgndglngrgf128jyl0yfmw5-qtdeclarative-5.12.3/lib/libQt5Qml.so.5
#5  0x00007fc9a80ca33a in QV4::Runtime::method_callPropertyLookup(QV4::ExecutionEngine*, QV4::Value*, unsigned int, QV4::Value*, int) ()
   from /nix/store/hqwgzd0iyqgndglngrgf128jyl0yfmw5-qtdeclarative-5.12.3/lib/libQt5Qml.so.5
#6  0x00007fc968ab4af9 in ?? ()
#7  0x0000000000000000 in ?? ()
```

Is this bug better off at upstream?

**To Reproduce**
1. Connect an external monitor to a laptop, extend the workspace to it.
2. Detach the monitor cable
3. Re-attach the monitor cable

**Screenshots**

**Additional context**

My device is a Lenovo Thinkpad T440S with an embedded Intel HD 4400 graphics chip.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.20, NixOS, 19.09.git.b3ca241 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"home-manager-19.09, nixos-19.09.2079.8731aaaf8b3, nixos-unstable-20.03pre212208.8130f3c1c2b"`
 - channels(user): `"home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by schmittlauch** [comment]
Another crash, this time more correlated to VLC switching to fullscreen.

I'm continuing to collect logs here until I manage to change to the 20.03 beta and having figured out whether these issues are fixed in newer plasma.

```
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:347: Unable to assign [undefined] to int
file:///nix/store/2jn24abf614jnrqh2744jhmsc5kh64vl-plasma-desktop-5.16.5/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:375: TypeError: Type error
QQuickItem::stackAfter: Cannot stack StatusNotifierItem_QMLTYPE_339(0x7f65e039e740, parent=0x3ca5ec0, geometry=0,0 0x0) after StatusNotifierItem_QMLTYPE_339(0x5983740), which must be a sibling
KCrash: Attempting to start /nix/store/mxhd4fsbp2z52fajsvp0k21bsm98qwqq-plasma-workspace-5.16.5/bin/.plasmashell-wrapped from kdeinit
sock_file=/run/user/1000/kdeinit5__0
KCrash: Application '.plasmashell-wrapped' crashing...
```

**Comment by schmittlauch** [comment]
I have not seen any crashes in NixOS 20.03 anymore.
