### ISSUE TITLE
Replace Bazaar with Breezy

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#80740]
**Issue description**
[Bazaar](http://wiki.bazaar.canonical.com/Download) is in maintenance mode and stuck at python 2.7, which is now officially unsupported.
A fork called [Breezy](https://www.breezy-vcs.org/), which is backward compatible and supports python 3, has been available for a while and should replace it.

**Possible course of action**

1. Package Breezy in nixpkgs
2. Alias `bazaar` to `breezy` and test dependent packages
3. Replace `bazaar` with `breezy` for working packages
4. Remove `bazaar` and broken packages (20.09)

**Affected packaged**
- fetchbzr ✓
- qarte ✓
- reposurgeon (broken on master)
- cvs2svn ✓
- ikiwiki ✓
- **nix-prefetch-scripts** ✓
- vcstool ✓
- flatpak-builder ✓
- **hydra** ✓
- ~PyLD~
- ~powerline~
- gsettings-qt ✓
- ~libftdi~
- ~pmount~
- ~mod_dnssd~

**Affected NixOS modules**
- redmine (broken on master #80061)

---

✓: works with breezy
✗: doesn't work
~--~: false positive

**Comment by rnhmjoj** [comment]
I tried replacing breezy into nix-prefetch-bzr and forcing a few fixed output derivations to rebuild. `fetch-bzr` seems to work in general and produces the same output as before, however nix-prefetch-bzr has some issue: this commands fails 

    nix-prefetch-bzr https://code.launchpad.net/~fourmond/pmount/main

```
Traceback (most recent call last):
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/commands.py", line 1016, in exception_to_return_code
    return the_callable(*args, **kwargs)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/commands.py", line 1202, in run_bzr
    ret = run(*run_argv)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/commands.py", line 759, in run_argv_aliases
    return self.run(**all_cmd_args)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/commands.py", line 784, in run
    return self._operation.run_simple(*args, **kwargs)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/cleanup.py", line 137, in run_simple
    self.cleanups, self.func, *args, **kwargs)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/cleanup.py", line 166, in _do_with_cleanups
    result = func(*args, **kwargs)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/builtins.py", line 3316, in run
    branch_or_subdir)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/controldir.py", line 814, in open_containing_tree_or_branch
    possible_transports=possible_transports)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/controldir.py", line 753, in open_containing
    return klass.open_containing_from_transport(transport)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/controldir.py", line 774, in open_containing_from_transport
    result = klass.open_from_transport(a_transport)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/controldir.py", line 737, in open_from_transport
    find_format, transport, redirected)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/transport/__init__.py", line 1613, in do_catching_redirections
    return action(transport)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/controldir.py", line 725, in find_format
    probers=probers)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/controldir.py", line 1162, in find_format
    return prober.probe_transport(transport)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/bzr/__init__.py", line 86, in probe_transport
    server_version = medium.protocol_version()
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/bzr/smart/medium.py", line 831, in protocol_version
    client_protocol.query_version()
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/bzr/smart/protocol.py", line 806, in query_version
    self.call(b'hello')
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/bzr/smart/protocol.py", line 644, in call
    self._request.finished_writing()
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/bzr/smart/medium.py", line 613, in finished_writing
    self._finished_writing()
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/transport/http/__init__.py", line 727, in _finished_writing
    data = self._medium.send_http_smart_request(self._buffer)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/transport/http/__init__.py", line 691, in send_http_smart_request
    code, body_filelike = t._post(bytes)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/transport/http/__init__.py", line 427, in _post
    accepted_errors=[200, 403]))
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/transport/http/__init__.py", line 116, in _perform
    response = self._opener.open(request)
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/transport/http/_urllib2_wrappers.py", line 942, in https_open
    connect = _ConnectRequest(request)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/transport/http/_urllib2_wrappers.py", line 584, in __init__
    connection=request.connection)
  File "/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/lib/python3.7/site-packages/breezy/transport/http/_urllib2_wrappers.py", line 530, in __init__
    origin_req_host, unverifiable)
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/urllib/request.py", line 354, in full_url
    self._parse()
  File "/nix/store/ja04f3cmapzb3f2mvjrb883bfqclsirq-python3-3.7.6/lib/python3.7/urllib/request.py", line 384, in _parse
    self.host, self.selector = splithost(rest)
AttributeError: can't set attribute

brz 3.0.2 on python 3.7.6 (Linux-5.5.6-x86_64-with-glibc2.2.5)
arguments:
    ['/nix/store/h7i8sxlxjibfbqrp8cm431gg2ay34x0s-python3.7-breezy-3.0.2/bin/b
    rz', 'export', 'brz-export',
    'https://code.launchpad.net/~fourmond/pmount/main']
plugins: bash_completion[3.0.2], changelog_merge[3.0.2],
    commitfromnews[3.0.2], cvs[3.0.2], darcs[3.0.2], email[3.0.2],
    fastimport[3.0.2], launchpad[3.0.2], mtn[3.0.2],
    netrc_credential_store[3.0.2], news_merge[3.0.2], po_merge[3.0.2],
    propose[3.0.2], repodebug[3.0.2], stats[3.0.2], upload[3.0.2],
    weave_fmt[3.0.2]
encoding: 'utf-8', fsenc: 'utf-8', lang: 'en_GB.UTF-8'

*** Bazaar has encountered an internal error.  This probably indicates a
    bug in Bazaar.  You can help us fix it by filing a bug report at
        https://bugs.launchpad.net/brz/+filebug
    including this traceback and a description of the problem.
```

**Comment by rnhmjoj** [comment]
Ugh, I have to create an ubuntu account to report a bug.

**Comment by jtojnar** [comment]
flatpak-builder just added native support for Breezy: https://github.com/flatpak/flatpak-builder/pull/333

It is great that we can reduce the amount of Python 2 usage but I am concerned about the increase of closure size:

```ShellSession
$ nix path-info -f . -Sh breezy bazaar
/nix/store/lg6kkxdnv495qhinxk46xykvqf8g1j4h-bazaar-2.7.0          	 135.9M
/nix/store/yf2d3xpzhi9zb1w3fyy8ry6iv0czyrcw-python3.7-breezy-3.0.2	 634.7M
```

**Comment by rnhmjoj** [comment]
@jtojnar: I didn't notice: that's pretty bad. Thank you for bringing it up.

**Comment by rnhmjoj** [comment]
I don't think there's anything strange going on: it's just an insane number of dependencies.
![graph](https://user-images.githubusercontent.com/2817565/77315091-37684380-6d07-11ea-8d69-8548d807a246.png)

**Comment by jelmer** [comment]
Hi, Breezy (and former Bazaar) upstream here.

The launchpad support that uses launchpadlib also existed in Bazaar, albeit using the Python 2 versions of the same libraries. I'm a bit surprised to see that it increases the size of things so much.

The launchpadlib dependency is only necessary for extra integration with Launchpad, i.e. the lp: URLs; it may make sense to disable it by default. 

I tried to reproduce the issue in https://github.com/NixOS/nixpkgs/issues/80740#issuecomment-592429598, but I'm having trouble doing so with the current 3.1 and 3.0 branches of Breezy on Debian with both Python 3.7 and Python 3.8.

**Comment by jtojnar** [comment]
Looks like this is a packaging issue `python3.pkgs.secretstorage` pulls in `dev` outputs.

**Comment by rnhmjoj** [comment]
Hi @jelmer, thank you for dropping by!

> The launchpadlib dependency is only necessary for extra integration with Launchpad, i.e. the lp: URLs; it may make sense to disable it by default.

I guessed so but I couldn't disable the dependency somehow, I don't remembed exactly because it was a while ago. I'll have to try again.

> I tried to reproduce the issue in #80740 (comment), but I'm having trouble doing so with the current 3.1 and 3.0 branches of Breezy on Debian with both Python 3.7 and Python 3.8.

The exact command that `nix-prefetch-bzr` is issueing before failing, in my case at least, is this one:
```
bzr export brz-export https://code.launchpad.net/~fourmond/pmount/main
```
The traceback is the one I pasted in before. Python is 3.7.7 and breezy is 3.0.2.

**Comment by rnhmjoj** [comment]
I figured out what it is, I don't know how exactly but it's my http proxy. I should have thought about that earlier.

**Comment by rnhmjoj** [comment]
> Looks like this is a packaging issue python3.pkgs.secretstorage pulls in dev outputs.

Strange, I dropped the `pygobject` from the `propagateBuildInputs` from secretstorage and everything still builds. This library is not even mentioned in the `setup.cfg` or `pyproject.toml`.

**Comment by jtojnar** [comment]
Yeah, it seems to me that https://github.com/NixOS/nixpkgs/pull/51904 introduced it by mistake. cc @worldofpeace

**Comment by worldofpeace** [comment]
@jtojnar lol, that seems like forever ago now, but I **think** (really not sure) https://github.com/mitya57/secretstorage/issues/8 was relevant and it fixed some bug for users having.

**Comment by jtojnar** [comment]
Looks that was actually removed in 3.0.0: https://github.com/mitya57/secretstorage/commit/709517904ea953a67c28e276b072f78c7abfb9ab#diff-caf2a6b8f4947d018f68893c695b5202

**Comment by rnhmjoj** [comment]
Good, so it's ok to drop it. I'll go on with the rest of the plan and open a PR.

**Comment by worldofpeace** [comment]
@rnhmjoj There's one detail I'd recommend changing in the possible actions `Add deprecation warning for bazaar (20.09)`. I believe we're trying to deprecate python 2 in 20.09, so we should go straight to removal.
