### ISSUE TITLE
pykms service doesn't work in release 19.09 (and 18.03/18.09)

### ISSUE THREAD

**Issue by pvgoran** [NixOS/nixpkgs#81355]
**Describe the bug**

The server from package pykms-20180208 doesn't work, thus the pykms service (which uses this package in release 19.09) doesn't work as well.

**To Reproduce**

Have the following in `configuration.nix`:
```
  environment.systemPackages = with pkgs; [
    pykms
  ];

  services.pykms.enable = true;
```

Be on release 19.09:
```
nix-channel --add https://nixos.org/channels/nixos-19.09 nixos
nix-channel --update
nixos-rebuild switch
```

And run:
```
$ client.py localhost
Connecting to localhost on port 1688...
Traceback (most recent call last):
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/client.py", line 240, in <module>
    main()
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/client.py", line 70, in main
    parsed = MSRPCRespHeader(response)
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/dcerpc.py", line 632, in __init__
    MSRPCHeader.__init__(self, aBuffer, alignment)
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/dcerpc.py", line 579, in __init__
    Structure.__init__(self,data, alignment)
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/structure.py", line 87, in __init__
    self.fromString(data)
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/structure.py", line 141, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/structure.py", line 316, in unpack
    return self.unpack(two[0],data)
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/structure.py", line 370, in unpack
    return unpack(format, data)[0]
struct.error: ('unpack requires a buffer of 1 bytes', "When unpacking field 'ver_major | B=5 | b''[:1]'")
```

**Expected behavior**

```
Connecting to localhost on port 1688...
Received V4 response
Response Hash has expected value: True
......
```

**Additional context**

As far as I remember, it is broken since release 2018-03. At that time, python3's version was changed from 3.6.5 to 3.7.x, which apparently caused the breakage (the way iterators work changed, or something). I think this problem was fixed by https://github.com/ThunderEX/py-kms/commit/57d51600c075fc8f121d62196a785ea5643eceb8 , but this version never made it into nixpkgs.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.101, NixOS, 19.09.2166.ce9f1aaa39e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(paul): `""`
 - channels(root): `"nixos-19.09.2166.ce9f1aaa39e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by pvgoran** [comment]
This was fixed by commit bf9cecf28d97b9cbcef5fc65cd8cbd297d405137, which was included in release 20.03.
