### ISSUE TITLE
multibootusb: QT error

### ISSUE THREAD

**Issue by btlvr** [NixOS/nixpkgs#81408]
**Describe the bug**
`multibootusb` does not run

**To Reproduce**
install `multibootusb`  
run `multibootusb`

**Expected behavior**
the program works

**Screenshots**
```
λ multibootusb                                                                                                                                                                                                ~
Using python version  3.6.9 (default, Jul  2 2019, 20:43:20) 
[GCC 8.3.0] on platform Linux-4.19.88-x86_64-with-glibc2.3.4
Running multibootusb version 9.2.0 from source...
Starting multibootusb GUI...


Admin privilege is required to run multibootusb.
 If you are running from source try 'sudo python3 ./multibootusb'
 or you can try 'multibootusb-pkexec' (post install)


qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

/home/user/.nix-profile/bin/multibootusb: line 6: 10105 Aborted                 (core dumped) "/nix/store/brg5wz6w4x6p9qa60q45xby6fabajapp-python3-3.6.9/bin/python" "multibootusb"
```
```
λ sudo multibootusb                                                                                                                                                                                           ~
Using python version  3.6.9 (default, Jul  2 2019, 20:43:20) 
[GCC 8.3.0] on platform Linux-4.19.88-x86_64-with-glibc2.3.4
Traceback (most recent call last):
  File "multibootusb", line 215, in <module>
    running_from()
  File "multibootusb", line 53, in running_from
    gen.log('Using python version ' + python_version + 'on platform ' + _platform, _print=False)
  File "/nix/store/hplm9l3jf7iz9djin8kd3d7mfa7qz3ss-multibootusb-9.2.0/share/multibootusb/scripts/gen.py", line 45, in log
    level=logging.DEBUG)
  File "/nix/store/brg5wz6w4x6p9qa60q45xby6fabajapp-python3-3.6.9/lib/python3.6/logging/__init__.py", line 1808, in basicConfig
    h = FileHandler(filename, mode)
  File "/nix/store/brg5wz6w4x6p9qa60q45xby6fabajapp-python3-3.6.9/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/nix/store/brg5wz6w4x6p9qa60q45xby6fabajapp-python3-3.6.9/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/tmp/multibootusb.log'

```

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.88, NixOS, 19.09.1548.3a1861fcabc (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by veprbl** [comment]
Related to #65399

**Comment by veprbl** [comment]
Should be resolved by now
