### ISSUE TITLE
builder for python2.7-decorator-4.4.1 is failing

### ISSUE THREAD

**Issue by mawis** [NixOS/nixpkgs#81703]
**Describe the bug**
After updatinging my nix-channel from yesterdays 20.03pre to the current 20.03pre `nixos-rebuild` is failing by not being able to build pythong2.7-decorator.

```
building '/nix/store/g4lj2f02pqj87vfmy2sypc7k7g8k14sv-python2.7-decorator-4.4.1.drv'...
created 487 symlinks in user environment
building '/nix/store/wq021y7lrk9p1znkqg0slpm0m9mch4av-weechat-bin-env-2.7.drv'...
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing setuptools-check-hook
Using setuptoolsCheckPhase
unpacking sources
unpacking source archive /nix/store/idhfvc7jkc7gh9b3bqi3q1va87s4ckyg-decorator-4.4.1.tar.gz
source root is decorator-4.4.1
setting SOURCE_DATE_EPOCH to timestamp 1572163736 of file decorator-4.4.1/src/decorator.egg-info/top_level.txt
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
building '/nix/store/icmlb4ihii81rav18b1l7vw5avanv6h8-etc-nixos.conf.drv'...
created 9 symlinks in user environment
running bdist_wheel
running build
running build_py
creating build
creating build/lib
copying src/decorator.py -> build/lib
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
copying build/lib/decorator.py -> build/bdist.linux-x86_64/wheel
running install_egg_info
running egg_info
writing src/decorator.egg-info/PKG-INFO
writing top-level names to src/decorator.egg-info/top_level.txt
writing dependency_links to src/decorator.egg-info/dependency_links.txt
reading manifest file 'src/decorator.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'documentation.pdf'
writing manifest file 'src/decorator.egg-info/SOURCES.txt'
Copying src/decorator.egg-info to build/bdist.linux-x86_64/wheel/decorator-4.4.1-py2.7.egg-info
running install_scripts
adding license file "LICENSE.txt" (matched pattern "LICEN[CS]E*")
creating build/bdist.linux-x86_64/wheel/decorator-4.4.1.dist-info/WHEEL
creating 'dist/decorator-4.4.1-py2.py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'decorator.py'
adding 'decorator-4.4.1.dist-info/LICENSE.txt'
adding 'decorator-4.4.1.dist-info/METADATA'
adding 'decorator-4.4.1.dist-info/WHEEL'
adding 'decorator-4.4.1.dist-info/pbr.json'
adding 'decorator-4.4.1.dist-info/top_level.txt'
adding 'decorator-4.4.1.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Finished executing setuptoolsBuildPhase
installing
Executing pipInstallPhase
/build/decorator-4.4.1/dist /build/decorator-4.4.1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing ./decorator-4.4.1-py2.py3-none-any.whl
Installing collected packages: decorator
Successfully installed decorator-4.4.1
/build/decorator-4.4.1
Finished executing pipInstallPhase
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/4d2bxibs9bl4609a298mvbp376hhs6dc-python2.7-decorator-4.4.1
strip is /nix/store/7wy2mifb0igrp9hzf9dzwddadbs7ai7d-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/4d2bxibs9bl4609a298mvbp376hhs6dc-python2.7-decorator-4.4.1/lib 
patching script interpreter paths in /nix/store/4d2bxibs9bl4609a298mvbp376hhs6dc-python2.7-decorator-4.4.1
checking for references to /build/ in /nix/store/4d2bxibs9bl4609a298mvbp376hhs6dc-python2.7-decorator-4.4.1...
running install tests
no Makefile or custom buildPhase, doing nothing
pythonCatchConflictsPhase
pythonRemoveBinBytecodePhase
pythonImportsCheckPhase
Executing pythonImportsCheckPhase
setuptoolsCheckPhase
Executing setuptoolsCheckPhase
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing src/decorator.egg-info/PKG-INFO
writing top-level names to src/decorator.egg-info/top_level.txt
writing dependency_links to src/decorator.egg-info/dependency_links.txt
reading manifest file 'src/decorator.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'documentation.pdf'
writing manifest file 'src/decorator.egg-info/SOURCES.txt'
running build_ext
test_add1 (tests.test.ExtraTestCase) ... ok
test_decorator_factory (tests.test.ExtraTestCase) ... ok
test_no_first_arg (tests.test.ExtraTestCase) ... ok
test_qualname (tests.test.ExtraTestCase) ... ok
test_signature (tests.test.ExtraTestCase) ... ok
test_unique_filenames (tests.test.ExtraTestCase) ... ok
test_gen123 (tests.test.GeneratorCallerTestCase) ... ok
copying path '/nix/store/kxxwb4p4a6gmlm1jbl8isy0gi7z136ih-libgdata-0.17.11' from 'https://cache.nixos.org'...
copying path '/nix/store/7z7vcm1allx3m3cdg0c5k5qh0ig9vhdc-evolution-data-server-3.34.3' from 'https://cache.nixos.org'...
test (tests.test.NoDocumentation) ... **********************************************************************
File "/build/decorator-4.4.1/src/tests/documentation.py", line 50, in tests.documentation.operation1
Failed example:
    operation1()
Expected:
    operation1 is slow
Got nothing
**********************************************************************
1 items had failures:
   1 of   1 in tests.documentation.operation1
***Test Failed*** 1 failures.
FAIL
test_singledispatch1 (tests.test.NoDocumentation) ... ok
test_singledispatch2 (tests.test.NoDocumentation) ... ok
test_c_classes (tests.test.TestSingleDispatch) ... ok
test_mro (tests.test.TestSingleDispatch) ... ok
test_mro_conflicts (tests.test.TestSingleDispatch) ... ok
test_register_abc (tests.test.TestSingleDispatch) ... ok
test_register_decorator (tests.test.TestSingleDispatch) ... ok
test_register_error (tests.test.TestSingleDispatch) ... ok
test_simple_overloads (tests.test.TestSingleDispatch) ... ok
test_wrapping_attributes (tests.test.TestSingleDispatch) ... ok

======================================================================
FAIL: test (tests.test.NoDocumentation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/decorator-4.4.1/src/tests/test.py", line 81, in test
    self.assertEqual(err, 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 18 tests in 5.651s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=18 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=18 errors=0 failures=1>
builder for '/nix/store/g4lj2f02pqj87vfmy2sypc7k7g8k14sv-python2.7-decorator-4.4.1.drv' failed with exit code 1
```

**Expected behavior**
`nixos-rebuild switch` should be working without an error.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.23, NixOS, 20.03beta377.ebc9620c3f6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.03beta-436.43ab8e86ca6, unstable-20.09pre215333.42f0be81ae0"`
 - channels(matthias): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute:
- python27Packages.decorator
module:
```

**Comment by mawis** [comment]
@costrouc

**Comment by mawis** [comment]
I have no idea what could have changed. I did a `nix-channel --update` but `nix-info -m` still returns the same values and now it worked without this error!?
