### ISSUE TITLE
Bulidkite agent does not work anymore

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#82042]
Buildkite agent does not start correctly anymore. Here is the error message that I get when I try to start it manually:

```
$ /nix/store/7r5mzk5qjivvrnd5wch978imm5jl306j-buildkite-agent-3.17.0-bin/bin/buildkite-agent start --config /var/lib/buildkite-agent-agent/buildkite-agent.cfg

  _           _ _     _ _    _ _                                _
 | |         (_) |   | | |  (_) |                              | |
 | |__  _   _ _| | __| | | ___| |_ ___    __ _  __ _  ___ _ __ | |_
 | '_ \| | | | | |/ _` | |/ / | __/ _ \  / _` |/ _` |/ _ \ '_ \| __|
 | |_) | |_| | | | (_| |   <| | ||  __/ | (_| | (_| |  __/ | | | |_
 |_.__/ \__,_|_|_|\__,_|_|\_\_|\__\___|  \__,_|\__, |\___|_| |_|\__|
                                                __/ |
 http://buildkite.com/agent                    |___/

2020-03-08 10:43:46 NOTICE Starting buildkite-agent v3.17.0 with PID: 35804
2020-03-08 10:43:46 NOTICE The agent source code can be found here: https://github.com/buildkite/agent/v3
2020-03-08 10:43:46 NOTICE For questions and support, email us at: hello@buildkite.com
2020-03-08 10:43:46 INFO   Configuration loaded path=/var/lib/buildkite-agent-agent/buildkite-agent.cfg
2020-03-08 10:43:46 INFO   Registering agent with Buildkite...
2020-03-08 10:43:47 INFO   Successfully registered agent "build01-agent-2" with tags [nix=true, os=nixos, queue=ghc]
2020-03-08 10:43:47 INFO   Starting 1 Agent(s)
2020-03-08 10:43:47 INFO   You can press Ctrl-C to stop the agents
2020-03-08 10:43:47 INFO   build01-agent-2 Connecting to Buildkite...
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed

runtime stack:
runtime.throw(0x11e8c9f, 0xc)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/panic.go:1112 +0x72
runtime.mlockGsignal(0xc00035b200)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/os_linux_x86.go:72 +0x107
runtime.mpreinit(0xc000241180)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/os_linux.go:341 +0x78
runtime.mcommoninit(0xc000241180)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:630 +0x108
runtime.allocm(0xc00005d800, 0x1229bb0, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:1390 +0x14e
runtime.newm(0x1229bb0, 0xc00005d800)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:1704 +0x39
runtime.startm(0x0, 0xc000580701)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:1869 +0x12a
runtime.wakep(...)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:1953
runtime.resetspinning()
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:2415 +0x93
runtime.schedule()
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:2527 +0x2de
runtime.park_m(0xc000388780)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:2690 +0x9d
runtime.mcall(0x800000)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [chan receive]:
github.com/buildkite/agent/agent.(*AgentPool).Start(0xc00059a220, 0x1208f05, 0x27)
        /build/go/src/github.com/buildkite/agent/agent/agent_pool.go:46 +0x1ce
github.com/buildkite/agent/clicommand.glob..func1(0xc0001aaf20)
        /build/go/src/github.com/buildkite/agent/clicommand/agent_start.go:745 +0x1ae0
github.com/buildkite/agent/vendor/github.com/urfave/cli.HandleAction(0xf24d20, 0x1228030, 0xc0001aaf20, 0x0, 0xc0000e94a0)
        /build/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:503 +0x7c
github.com/buildkite/agent/vendor/github.com/urfave/cli.Command.Run(0x11e2212, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11f6076, 0x18, 0x0, ...)
        /build/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/command.go:165 +0x4da
github.com/buildkite/agent/vendor/github.com/urfave/cli.(*App).Run(0xc0002b81c0, 0xc000020080, 0x4, 0x4, 0x0, 0x0)
        /build/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:259 +0x775
main.main()
        /build/go/src/github.com/buildkite/agent/main.go:115 +0x55d

goroutine 86 [IO wait]:
internal/poll.runtime_pollWait(0x7fbca079d1b8, 0x72, 0xffffffffffffffff)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0001f2518, 0x72, 0x1700, 0x176b, 0xffffffffffffffff)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001f2500, 0xc0003b0000, 0x176b, 0x176b, 0x0, 0x0, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0001f2500, 0xc0003b0000, 0x176b, 0x176b, 0x203000, 0x7fbca2965a00, 0x20300000000000)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000386000, 0xc0003b0000, 0x176b, 0x176b, 0x0, 0x0, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc00059a1c0, 0xc0003b0000, 0x176b, 0x176b, 0x7fbca2b37fff, 0x7fbca079a158, 0xc0000cf918)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc00038a258, 0x13a8900, 0xc00059a1c0, 0x40c0f5, 0x102d220, 0x11a4ce0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00038a000, 0x13a98e0, 0xc000386000, 0x5, 0xc000386000, 0xc000386008)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc00038a000, 0x0, 0x0, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc00038a000, 0xc00012a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/crypto/tls/conn.go:1233 +0x15b
net/http.(*persistConn).Read(0xc000195d40, 0xc00012a000, 0x1000, 0x1000, 0xc0000f4120, 0xc0000cfc70, 0x406b85)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:1825 +0x75
bufio.(*Reader).fill(0xc0003831a0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc0003831a0, 0x1, 0x0, 0x0, 0x1, 0xc0003a3500, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc000195d40)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:1978 +0x1a8
created by net/http.(*Transport).dialConn
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:1647 +0xc56

goroutine 87 [select]:
net/http.(*persistConn).writeLoop(0xc000195d40)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:1648 +0xc7b

goroutine 56 [syscall]:
os/signal.signal_recv(0x1229640)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/os/signal/signal.go:127 +0x44

goroutine 23 [chan receive]:
github.com/buildkite/agent/clicommand.handlePoolSignals.func1(0xc0000e8480, 0x13ca300, 0xc0003280c0, 0xc00059a220)
        /build/go/src/github.com/buildkite/agent/clicommand/agent_start.go:762 +0x48
created by github.com/buildkite/agent/clicommand.handlePoolSignals
        /build/go/src/github.com/buildkite/agent/clicommand/agent_start.go:759 +0x145

goroutine 24 [select]:
net/http.(*Transport).getConn(0xc0005a0140, 0xc00014a0f0, 0x0, 0xc000148000, 0x5, 0xc00013c080, 0x17, 0x0, 0x0, 0x0, ...)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:1291 +0x57b
net/http.(*Transport).roundTrip(0xc0005a0140, 0xc0003ac200, 0xf3a620, 0xc000140001, 0xc00014c000)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:552 +0x726
net/http.(*Transport).RoundTrip(0xc0005a0140, 0xc0003ac200, 0x11e9188, 0xd, 0xc00014c0a0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/roundtrip.go:17 +0x35
github.com/buildkite/agent/api.authenticatedTransport.RoundTrip(0xc000798040, 0x32, 0x13a9980, 0xc0005a0140, 0xc0003ac200, 0x0, 0xc0004fc018, 0xc0004fc020)
        /build/go/src/github.com/buildkite/agent/api/auth.go:30 +0x1a1
net/http.send(0xc0003ac100, 0x13a8b40, 0xc00059a200, 0xbf915107c0652428, 0xe13ae8f73, 0x1bd74e0, 0xc000132010, 0xbf915107c0652428, 0x1, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/client.go:252 +0x43e
net/http.(*Client).send(0xc0005a2300, 0xc0003ac100, 0xbf915107c0652428, 0xe13ae8f73, 0x1bd74e0, 0xc000132010, 0x0, 0x1, 0x400)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/client.go:176 +0xfa
net/http.(*Client).do(0xc0005a2300, 0xc0003ac100, 0x0, 0x0, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/client.go:699 +0x44a
net/http.(*Client).Do(...)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/client.go:567
github.com/buildkite/agent/api.(*Client).doRequest(0xc0000e8420, 0xc0003ac100, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/go/src/github.com/buildkite/agent/api/client.go:230 +0x1a0
github.com/buildkite/agent/api.(*Client).Connect(0xc0000e8420, 0x22e7099fb19b6a, 0x6417fd, 0x6417fd0012c080)
        /build/go/src/github.com/buildkite/agent/api/agents.go:55 +0xad
github.com/buildkite/agent/agent.(*AgentWorker).Connect.func1(0xc000146000, 0x13b5520, 0xc0003b8a00)
        /build/go/src/github.com/buildkite/agent/agent/agent_worker.go:285 +0x3c
github.com/buildkite/agent/retry.Do(0xc0001dbf08, 0xc00013c060, 0x1a, 0x0)
        /build/go/src/github.com/buildkite/agent/retry/retry.go:80 +0x1d9
github.com/buildkite/agent/agent.(*AgentWorker).Connect(0xc00000c1e0, 0x0, 0x0)
        /build/go/src/github.com/buildkite/agent/agent/agent_worker.go:284 +0xb9
github.com/buildkite/agent/agent.(*AgentPool).runWorker(0xc00059a220, 0xc00000c1e0, 0xc00051a000, 0x0, 0x0)
        /build/go/src/github.com/buildkite/agent/agent/agent_pool.go:51 +0x2f
github.com/buildkite/agent/agent.(*AgentPool).Start.func1(0xc00060c180, 0xc00059a220, 0xc00051a000, 0xc00010e0c0, 0xc00000c1e0)
        /build/go/src/github.com/buildkite/agent/agent/agent_pool.go:35 +0x6e
created by github.com/buildkite/agent/agent.(*AgentPool).Start
        /build/go/src/github.com/buildkite/agent/agent/agent_pool.go:32 +0x159

goroutine 25 [semacquire]:
sync.runtime_Semacquire(0xc00060c188)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc00060c180)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/sync/waitgroup.go:130 +0x64
github.com/buildkite/agent/agent.(*AgentPool).Start.func2(0xc00060c180, 0xc00010e0c0)
        /build/go/src/github.com/buildkite/agent/agent/agent_pool.go:42 +0x2b
created by github.com/buildkite/agent/agent.(*AgentPool).Start
        /build/go/src/github.com/buildkite/agent/agent/agent_pool.go:41 +0x1ae

goroutine 42 [select]:
net/http.setRequestCancel.func4(0x0, 0xc00014a0c0, 0xc000150050, 0xc0004fc018, 0xc000152060)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/client.go:379 +0xcf
created by net/http.setRequestCancel
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/client.go:378 +0x321

goroutine 43 [chan receive]:
net/http.(*persistConn).addTLS(0xc000160000, 0xc00013c080, 0x13, 0x0, 0xc00013c094, 0x3)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:1459 +0x1d3
net/http.(*Transport).dialConn(0xc0005a0140, 0x13c4480, 0xc00014e000, 0x0, 0xc000148000, 0x5, 0xc00013c080, 0x17, 0x0, 0xc000160000, ...)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:1529 +0x1c5d
net/http.(*Transport).dialConnFor(0xc0005a0140, 0xc000154000)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:1365 +0xc6
created by net/http.(*Transport).queueForDial
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:1334 +0x3fe

goroutine 26 [runnable]:
crypto/tls.(*finishedHash).Write(0xc0001ddd98, 0xc000558000, 0x14d, 0x160, 0x0, 0x0, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/crypto/tls/prf.go:174 +0x206
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc0001ddd78, 0xc000518120, 0x59)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/crypto/tls/handshake_client.go:500 +0x380
crypto/tls.(*clientHandshakeState).handshake(0xc0001ddd78, 0xc00032a000, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/crypto/tls/handshake_client.go:397 +0x3fb
crypto/tls.(*Conn).clientHandshake(0xc0001b3880, 0x0, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/crypto/tls/handshake_client.go:206 +0x5ef
crypto/tls.(*Conn).Handshake(0xc0001b3880, 0x0, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/crypto/tls/conn.go:1340 +0xcc
net/http.(*persistConn).addTLS.func2(0x0, 0xc0001b3880, 0xc000520000, 0xc00010e120)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:1453 +0x42
created by net/http.(*persistConn).addTLS
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/net/http/transport.go:1449 +0x1aa
```

The relevant Go issue: https://github.com/golang/go/issues/37436.

**To Reproduce**

At `9d0fac46fd037d7839248d8baec3296776d60263`, start `buildkite-agent` as shown above. It should fail.

**Expected behavior**
Buildkite agent should work.

**Metadata**

- system: `"x86_64-linux"`
- host os: `Linux 4.19.96, NixOS, 19.09.git.d126556 (Loris)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3pre6895_84de821`
- channels(mark): `"nixos-18.09.2337.5d972dd2c94"`
- channels(root): `"nixos-19.03.173651.ca6b6595392"`
- nixpkgs: `/nix/store/4s912x9xc14wmz66hdfkqi15qrvwsw59-8x90sd5m33zhz96z72zgydgy11nc6wb2-source`

cc @flokli

**Comment by mrkkrp** [comment]
It looks like this can be resolved by updating the kernel.

**Comment by flokli** [comment]
Reading on https://github.com/golang/go/issues/37436, this seems to be a kernel bug causing memory corruption, and only if the kernel is built with gcc9. It's not limited to go applications per se, it just shows up there more visibly.

Go 1.14 introduced a runtime kernel version detection, once it detects a vulnerable version, it tries to `mlock` signal stacks, and panics loudly if that fails (which in principle the right thing, if you're on a vulnerable stack and unable to apply workarounds).

It seems however as this version detection has false positives, as it doesn't account for backported fixes: https://github.com/golang/go/issues/37436#issuecomment-591558921.
This causes go binaries built that way to fail under Ubuntu for example.

I'm not entirely sure what we do here. 
 - `2f060f6a676395d7e1f517122a629f12b793b5b4` switched `buildGoPackage` to 1.14, but 1.13 is also suffering from memory corruptions on really affected kernels, it just doesn't have logic to try to apply workarounds.
 - We don't necessarily have control about the kernel on non-NixOS system.
 - https://github.com/golang/go/issues/37436#issuecomment-591237929 mentions 5.4.0 - 5.4.1 are affected. NixOS  `master` is currently defaulting to 5.4.24, so I think we're another false positive, and the go runtimes kernel version detection is wrong.

I propose to take a close look at https://github.com/golang/go/blob/9d4717d5f1d9b8a16c52c46d2a670c230dc72cbc/src/runtime/os_linux_x86.go#L56, and how it behaves on our systems.

**Comment by flokli** [comment]
This should be solved in the next go 1.14.1 minor release: https://github.com/golang/go/issues/37807

**Comment by mrkkrp** [comment]
golang/go#37807 is merged now.

**Comment by flokli** [comment]
Nice! Can you bump the go derivation in nixpkgs and see if this works around the issue?

**Comment by mrkkrp** [comment]
It appears that the version of `go` that is used by default by the unstable channel is already 1.14. I'm going to check if it works.

**Comment by mrkkrp** [comment]
Hmm, so they just pushed a commit to the `release-branch.go1.14` but there seems to be no new release and we are already using 1.14. I asked.

**Comment by mrkkrp** [comment]
We will have to wait till 1.14.1.

**Comment by flokli** [comment]
Well, we can still backport that patch to our go derivation.

**Comment by mrkkrp** [comment]
No longer an issue because the kernel has been updated.

**Comment by flokli** [comment]
We should still update go to 1.14.1, which includes a less invasive migitation attempt - it might be people might not be able to easily update kernels. This bump should also be backported to 20.03.

**Comment by flokli** [comment]
I opened a PR for go 1.14.1 in https://github.com/NixOS/nixpkgs/pull/83689.
