### ISSUE TITLE
terraform_0_12 crashes on macos 10.14.6 mojave

### ISSUE THREAD

**Issue by pmahoney** [NixOS/nixpkgs#82423]
**Describe the bug**
terraform_0_12 crashes on macos 10.14.6 mojave

**To Reproduce**
1. install terraform_0_12 from https://releases.nixos.org/nixpkgs/nixpkgs-20.09pre216412.04d6123309f/nixexprs.tar.xz (I also built locally on https://github.com/NixOS/nixpkgs/tree/98d134b253183e1827eea5171804e360e09d9db0)
2. run `terraform version`
3. output:
```
runtime: netpoll: break fd ready for -2
fatal error: runtime: netpoll: break fd ready for something unexpected

runtime stack:
runtime.throw(0x29a0307, 0x39)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/panic.go:1112 +0x72
runtime.netpoll(0x708d2, 0xc00005e001)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/netpoll_kqueue.go:140 +0x30a
runtime.findrunnable(0xc000065800, 0x0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:2323 +0x72b
runtime.schedule()
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:2520 +0x2fc
runtime.park_m(0xc000001080)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:2690 +0x9d
runtime.mcall(0x80000)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [runnable, locked to thread]:
github.com/hashicorp/terraform/vendor/github.com/chzyer/readline.init()
        /private/tmp/nix-build-terraform-0.12.23.drv-0/go/src/github.com/hashicorp/terraform/vendor/github.com/chzyer/readline/operation.go:10

goroutine 19 [select]:
github.com/hashicorp/terraform/vendor/go.opencensus.io/stats/view.(*worker).start(0xc000116e60)
        /private/tmp/nix-build-terraform-0.12.23.drv-0/go/src/github.com/hashicorp/terraform/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by github.com/hashicorp/terraform/vendor/go.opencensus.io/stats/view.init.0
        /private/tmp/nix-build-terraform-0.12.23.drv-0/go/src/github.com/hashicorp/terraform/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57
```

**Expected behavior**
A the version number should be printed.

**Additional context**

terraform_0_11 does not crash.

I was able to work around the problem by building building terraform_0_12 using go 1.12 (this patch against nixpkgs):

``` diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 5cf06d016c0..20293bad2a3 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -25653,7 +25653,7 @@ in
     buildGoModule = buildGo112Module;
   };
 
-  inherit (callPackage ../applications/networking/cluster/terraform {})
+  inherit (callPackage ../applications/networking/cluster/terraform { buildGoPackage = buildGo112Package; })
     terraform_0_11
     terraform_0_11-full
     terraform_0_12

```

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(patrick): `"nixpkgs-20.03pre207249.7e8454fb856"`
 - nixpkgs: `/Users/patrick/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: terraform_0_12
# a list of nixos modules affected by the problem
module:
```

**Comment by marsam** [comment]
upstream issue https://github.com/hashicorp/terraform/issues/24287
would you mind creating a PR with your patch but with `buildGo113Package`?

**Comment by pmahoney** [comment]
Looks like you beat me to it, thank you.
