### ISSUE TITLE
upower segfaults on 20.03 unless service is enabled

### ISSUE THREAD

**Issue by bhipple** [NixOS/nixpkgs#82529]
**Describe the bug**
On 19.09, a command like `upower -e` works.  

On `20.03beta529.da92e0566d1 (Markhor)`, it segfaults:

```
$ /nix/store/gdb2bg3q3pa20rq68jy8jrhcia5wiggf-upower-0.99.11/bin/upower -e
(upower:12641): libupower-glib-WARNING **: 00:23:01.643: up_client_get_devices failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1]    12641 segmentation fault (core dumped)  /nix/store/gdb2bg3q3pa20rq68jy8jrhcia5wiggf-upower-0.99.11/bin/upower -e
```
If I set `services.upower.enable = true;` in nixos-config, then it works again.

Running it under GDB does not appear to be too helpful:
```
Thread 1 "upower" received signal SIGSEGV, Segmentation fault.
0x0000000000402598 in main ()
(gdb) where
#0  0x0000000000402598 in main ()
(gdb) backtrace
#0  0x0000000000402598 in main ()
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.24, NixOS, 20.03beta529.da92e0566d1 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(bhipple): `""`
 - channels(root): `"nixos-20.03beta529.da92e0566d1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: upower
# a list of nixos modules affected by the problem
module: upower
```

**Comment by vcunat** [comment]
I don't think it will be of much use without debugging symbols.  For example:
```bash
nix-build -E 'with (import <nixpkgs> {}); upower.overrideAttrs (a_: { dontStrip = true; })' -Q
```

**Comment by bhipple** [comment]
```
$ gdb -ex run --args $(nix-build -E 'with (import <nixpkgs> {}); upower.overrideAttrs (_: { dontStrip = true; CFLAGS = "-O0 -g"; })' -Q)/bin/upower -e

Reading symbols from /nix/store/1zv1y934xq3y3q37z4ammgykn54ykcar-upower-0.99.11/bin/upower...
Starting program: /nix/store/1zv1y934xq3y3q37z4ammgykn54ykcar-upower-0.99.11/bin/upower -e
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/sc7lh1dhvd7fg28d7dxwsqzfcinnr6j5-glibc-2.30/lib/libthread_db.so.1".

(upower:26961): libupower-glib-WARNING **: 22:41:26.048: up_client_get_devices failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files

Thread 1 "upower" received signal SIGSEGV, Segmentation fault.
0x0000000000402ef0 in main (argc=1, argv=0x7fffffffd278) at up-tool.c:318
318     up-tool.c: No such file or directory.
```
https://github.com/freedesktop/upower/blob/master/tools/up-tool.c#L316-L318

It looks like `up_client_get_devices (client)` fails and returns a null pointer to set as `devices`, which then causes the segfault on `for (i=0; i < devices->len; i++) {`
