### ISSUE TITLE
direnv 2.21.2 on macOS (10.13.6) is broken

### ISSUE THREAD

**Issue by toonn** [NixOS/nixpkgs#82606]
**Describe the bug**
When trying to run direnv it immediately crashes with "SIGILL: illegal instruction"
```
SIGILL: illegal instruction
PC=0x4063a80 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/preempt_amd64.s:8 fp=0xc00009ada8 sp=0xc00009ada0 pc=0x4063a80
internal/poll.(*FD).Init(0xc000102000, 0x41fc68e, 0x4, 0xc00009ad00, 0x4051486, 0x40642a0)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/internal/poll/fd_unix.go:54 fp=0xc00009adb0 sp=0xc00009ada8 pc=0x40bd960
os.newFile(0x0, 0x41fd5e0, 0xa, 0x0, 0xc00008e190)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/os/file_unix.go:155 +0x124 fp=0xc00009ae90 sp=0xc00009adb0 pc=0x40c74c4
os.NewFile(0x0, 0x41fd5e0, 0xa, 0xc00008e190)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/os/file_unix.go:92 +0x64 fp=0xc00009aec8 sp=0xc00009ae90 pc=0x40c7374
os.init()
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/os/file.go:63 +0x17a fp=0xc00009aef8 sp=0xc00009aec8 pc=0x40ca53a
runtime.doInit(0x4378d00)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:5414 +0x8a fp=0xc00009af28 sp=0xc00009aef8 pc=0x4041d9a
runtime.doInit(0x43787c0)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:5409 +0x57 fp=0xc00009af58 sp=0xc00009af28 pc=0x4041d67
runtime.doInit(0x437a060)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:5409 +0x57 fp=0xc00009af88 sp=0xc00009af58 pc=0x4041d67
runtime.main()
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/proc.go:190 +0x1ce fp=0xc00009afe0 sp=0xc00009af88 pc=0x403527e
runtime.goexit()
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14/share/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00009afe8 sp=0xc00009afe0 pc=0x4062211

rax    0x0
rbx    0x0
rcx    0x41fc68e
rdx    0xc000100000
rdi    0x58
rsi    0x58
rbp    0xc00009ae80
rsp    0xc00009ada0
r8     0xb808102
r9     0x203000
r10    0x4
r11    0x32
r12    0xf2
r13    0x0
r14    0x423fae0
r15    0x0
rip    0x4063a80
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0
```

This seems to be caused by a [regression in Go 1.14](https://github.com/golang/go/issues/37459).

**To Reproduce**
1. Install direnv from the nixpkgs unstable channel on macOS 10.13.6, `4r922vkmjrzdkl062hichvidm8nbxh2a-nixpkgs-20.09pre216861.16a3d75f5e4/nixpkgs`
2. Running direnv immediately crashes immediately with the SIGILL error but not every time.

**Additional context**
I've had no problems with direnv before today.

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(toonn): `"darwin, home-manager, nixpkgs-20.09pre216861.16a3d75f5e4"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - nixpkgs: `/Users/toonn/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: - direnv
                - go # maybe
# a list of nixos modules affected by the problem
module:
```

**Comment by doronbehar** [comment]
I think you should report it upstream.

**Comment by toonn** [comment]
I linked the upstream issue, which has been fixed and backported to Go 1.14.

**Comment by doronbehar** [comment]
I see, I was thinking of the direnv issue. I think you'll just have to wait for https://github.com/NixOS/nixpkgs/pull/83689 to land in your channels - it's currently on staging.

**Comment by toonn** [comment]
Closing because it just landed in unstable.

**Comment by toonn** [comment]
Oops, turns out it's not fixed yet. Reopening to reflect the real current status.

**Comment by marsam** [comment]
closing because it's outdated https://hydra.nixos.org/build/125621756
