### ISSUE TITLE
esptool's espefuse.py doesn't work

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#82965]
**Describe the bug**
+ Install esptool
+ run `espefuse.py`

```
Traceback (most recent call last):
  File "/nix/store/d82aizmfkk3g2ymv5nyirsqvvf62w7lh-esptool-2.7/bin/.espefuse.py-wrapped", line 27, in <module>
    import esptool
  File "/nix/store/d82aizmfkk3g2ymv5nyirsqvvf62w7lh-esptool-2.7/bin/esptool.py", line 2
    export PATH='/nix/store/fara2bdicvvi0p8bmrgcz6s8d6yicijc-python3-3.7.6/bin:/nix/store/d82aizmfkk3g2ymv5nyirsqvvf62w7lh-esptool-2.7/bin:/nix/store/qkn0xsrkx4dwd98rbb1rgh1cp4jhfmwm-python3.7-pyserial-3.4/bin'${PATH:+':'}$PATH
              ^
SyntaxError: invalid syntax
````
Looks like `espefuse.py` tries to source the `esptool.py` wrapper script.

**Expected behavior**

The usage of the tool gets shown

**Additional context**
Looks like somebody did not the "all executables in /bin work" test

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.9, NixOS, 20.09pre216896.0729b8c55e0 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.03beta591.99a3d7a86fc"`
 - channels(wucke13): `"nixos-unstable-20.09pre215947.82b54d49066"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by wucke13** [comment]
## Still relevant!

```
> nix-shell -p esptool
these paths will be fetched (0.13 MiB download, 0.70 MiB unpacked):
  /nix/store/09z3hybpbsza7fs7ra4jd22wjynxy9zq-python3.8-pyaes-1.6.1
  /nix/store/yyb51l487y3rihg2dgzlzqa6m6nwxkyc-esptool-2.7
copying path '/nix/store/09z3hybpbsza7fs7ra4jd22wjynxy9zq-python3.8-pyaes-1.6.1' from 'https://cache.nixos.org'...
copying path '/nix/store/yyb51l487y3rihg2dgzlzqa6m6nwxkyc-esptool-2.7' from 'https://cache.nixos.org'...

[nix-shell:~]$ espefuse.py
Traceback (most recent call last):
  File "/nix/store/yyb51l487y3rihg2dgzlzqa6m6nwxkyc-esptool-2.7/bin/.espefuse.py-wrapped", line 27, in <module>
    import esptool
  File "/nix/store/yyb51l487y3rihg2dgzlzqa6m6nwxkyc-esptool-2.7/bin/esptool.py", line 2
    export PATH='/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/bin:/nix/store/yyb51l487y3rihg2dgzlzqa6m6nwxkyc-esptool-2.7/bin:/nix/store/18xk8vr4zn8xvzv03bwylrqdjz8sqjwd-python3.8-pyserial-3.4/bin'${PATH:+':'}$PATH
           ^
SyntaxError: invalid syntax
```
