### ISSUE TITLE
FreeCAD crash on stratup in nixos-19.09

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#83127]
```
FreeCAD 0.18, Libs: 0.18RUnknown
© Juergen Riegel, Werner Mayer, Yorik van Havre 2001-2019
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##


Program received signal SIGABRT, Aborted.
0x00007ffff3b69be0 in raise () from /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libc.so.6
(gdb) bt
#0  0x00007ffff3b69be0 in raise () from /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libc.so.6
#1  0x00007ffff3b6adc1 in abort () from /nix/store/wx1vk75bpdr65g6xwxbj4rw0pk04v5j3-glibc-2.27/lib/libc.so.6
#2  0x00007ffff41a8087 in QMessageLogger::fatal(char const*, ...) const ()
   from /nix/store/lgsxywa8y082rhl32b65s3763hqnzq0x-qtbase-5.12.3/lib/libQt5Core.so.5
#3  0x00007ffff477b0db in QGuiApplicationPrivate::createPlatformIntegration() ()
   from /nix/store/lgsxywa8y082rhl32b65s3763hqnzq0x-qtbase-5.12.3/lib/libQt5Gui.so.5
#4  0x00007ffff477b59d in QGuiApplicationPrivate::createEventDispatcher() ()
   from /nix/store/lgsxywa8y082rhl32b65s3763hqnzq0x-qtbase-5.12.3/lib/libQt5Gui.so.5
#5  0x00007ffff43aa725 in QCoreApplicationPrivate::init() ()
   from /nix/store/lgsxywa8y082rhl32b65s3763hqnzq0x-qtbase-5.12.3/lib/libQt5Core.so.5
#6  0x00007ffff477cdaf in QGuiApplicationPrivate::init() ()
   from /nix/store/lgsxywa8y082rhl32b65s3763hqnzq0x-qtbase-5.12.3/lib/libQt5Gui.so.5
#7  0x00007ffff4d7bed9 in QApplicationPrivate::init() ()
   from /nix/store/lgsxywa8y082rhl32b65s3763hqnzq0x-qtbase-5.12.3/lib/libQt5Widgets.so.5
#8  0x00007ffff73d53ae in Gui::GUIApplicationNativeEventAware::GUIApplicationNativeEventAware(int&, char**) ()
   from /nix/store/g53sprc5yxxwcl2p2mlp6sy66hq1jw30-freecad-0.18.3/lib/libFreeCADGui.so
#9  0x00007ffff73d4141 in Gui::GUIApplication::GUIApplication(int&, char**) ()
   from /nix/store/g53sprc5yxxwcl2p2mlp6sy66hq1jw30-freecad-0.18.3/lib/libFreeCADGui.so
#10 0x00007ffff73d48b9 in Gui::GUISingleApplication::GUISingleApplication(int&, char**) ()
   from /nix/store/g53sprc5yxxwcl2p2mlp6sy66hq1jw30-freecad-0.18.3/lib/libFreeCADGui.so
#11 0x00007ffff736cb42 in Gui::Application::runApplication() ()
   from /nix/store/g53sprc5yxxwcl2p2mlp6sy66hq1jw30-freecad-0.18.3/lib/libFreeCADGui.so
#12 0x000000000040578e in main ()
```

**Comment by tex** [comment]
Works on unstable, closing.
