### ISSUE TITLE
bumping gitlab to 12.9.x fails

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#83478]
**Describe the bug**
Bumping gitlab to 12.9.x fails in `vgo2nix`:

**To Reproduce**
1. `cd pkgs/applications/version-management/gitlab`
2. `./update.py update-all`
3. The script fails with the following error output:

```panic: Error processing import path "dmitri.shuralyov.com/gpu/mtl": unrecognized import path "dmitri.shuralyov.com/gpu/mtl"

goroutine 1 [running]:
main.main()
	/build/go/src/github.com/adisbladis/vgo2nix/main.go:239 +0x6d2
```

I checked out the `gitaly` subdir. `go.sum` contains the following line
```
dmitri.shuralyov.com/gpu/mtl v0.0.0-20190408044501-666a987793e9/go.mod h1:H6x//7gZCb22OMCxBHrMx7a5I7Hp++hsVxbQ4BYO7hU=
```

**Comment by petabyteboy** [comment]
I was able to fix this by updating the golang.org/x/tools dependency of vgo2nix to the latest version, but new problems started popping up:

```
[pbb@onyx:~/proj/nixpkgs/pkgs/applications/version-management/gitlab]$ ./update.py update-all

Initialized empty Git repository in /run/user/1000/git-checkout-tmp-T49lcm0a/gitlab/.git/
warning: redirecting to https://gitlab.com/gitlab-org/gitlab.git/
remote: Enumerating objects: 33675, done.
remote: Counting objects: 100% (33675/33675), done.
remote: Compressing objects: 100% (30103/30103), done.
remote: Total 33675 (delta 2887), reused 19705 (delta 1889), pack-reused 0
Receiving objects: 100% (33675/33675), 86.70 MiB | 16.37 MiB/s, done.
Resolving deltas: 100% (2887/2887), done.
From https://gitlab.com/gitlab-org/gitlab
 * tag                 v12.9.1-ee -> FETCH_HEAD
Updating files: 100% (29976/29976), done.
Switched to a new branch 'fetchgit'
removing `.git'...

git revision is 0ebcf602332fc27fc2bc8a2eb7b14d7a1685c343
path is /nix/store/qfwiw3405xx72g7l176hqyrgldcj192a-gitlab
git human-readable version is -- none --
Commit date is 2020-03-26 12:16:15 +0000
hash is 1xa913vrd9yx4nfw36f623wxk3l7d4vcccd8h584ww9ijqqmb0i4
panic: Error processing import path "cloud.google.com/go/bigquery": exit status 1

goroutine 1 [running]:
main.main()
	/home/pbb/proj/vgo2nix/main.go:239 +0x6d2
Traceback (most recent call last):
  File "./update.py", line 242, in <module>
    cli()
  File "/nix/store/dyjg9w55jf25w1458g7fxqcwjmkykn71-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/dyjg9w55jf25w1458g7fxqcwjmkykn71-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/dyjg9w55jf25w1458g7fxqcwjmkykn71-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/dyjg9w55jf25w1458g7fxqcwjmkykn71-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/dyjg9w55jf25w1458g7fxqcwjmkykn71-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/dyjg9w55jf25w1458g7fxqcwjmkykn71-python3.7-click-7.0/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./update.py", line 236, in update_all
    ctx.invoke(update_gitaly)
  File "/nix/store/dyjg9w55jf25w1458g7fxqcwjmkykn71-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./update.py", line 180, in update_gitaly
    subprocess.check_output(['vgo2nix', '-jobs', '1'], cwd=gitaly_dir)
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['vgo2nix', '-jobs', '1']' returned non-zero exit status 2.

[pbb@onyx:~/proj/nixpkgs/pkgs/applications/version-management/gitlab]$
