### ISSUE TITLE
backintime-qt4 DBusException

### ISSUE THREAD

**Issue by flosse** [NixOS/nixpkgs#8348]
What can I do to fix the following?

```
~ % backintime-qt4       
WARNING: import keyring failed
Traceback (most recent call last):
  File "/nix/store/kdhjmcy1iz02yf2hd042ncypqndbjv0w-PyQt-x11-gpl-4.11.3/lib/python3.4/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/nix/store/kdhjmcy1iz02yf2hd042ncypqndbjv0w-PyQt-x11-gpl-4.11.3/lib/python3.4/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/nix/store/kdhjmcy1iz02yf2hd042ncypqndbjv0w-PyQt-x11-gpl-4.11.3/lib/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/zlnkqg9kbfs1lx2hj2bn81ic1vjd57jk-backintime-qt4-1.1.4/share/backintime/qt4/app.py", line 1373, in <module>
    cfg = backintime.start_app( 'backintime-qt4' )
  File "/nix/store/m7365hhl1wb5xdxs3wi5qican8vkf9ij-backintime-common-1.1.4/share/backintime/common/backintime.py", line 155, in start_app
    cfg = config.Config(config_path)
  File "/nix/store/m7365hhl1wb5xdxs3wi5qican8vkf9ij-backintime-common-1.1.4/share/backintime/common/config.py", line 270, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/nix/store/m7365hhl1wb5xdxs3wi5qican8vkf9ij-backintime-common-1.1.4/share/backintime/common/tools.py", line 1054, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/nix/store/kdhjmcy1iz02yf2hd042ncypqndbjv0w-PyQt-x11-gpl-4.11.3/lib/python3.4/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/nix/store/kdhjmcy1iz02yf2hd042ncypqndbjv0w-PyQt-x11-gpl-4.11.3/lib/python3.4/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/nix/store/kdhjmcy1iz02yf2hd042ncypqndbjv0w-PyQt-x11-gpl-4.11.3/lib/python3.4/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/nix/store/kdhjmcy1iz02yf2hd042ncypqndbjv0w-PyQt-x11-gpl-4.11.3/lib/python3.4/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/nix/store/kdhjmcy1iz02yf2hd042ncypqndbjv0w-PyQt-x11-gpl-4.11.3/lib/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: Cannot launch daemon, file not found or permissions invalid
```

**Comment by flosse** [comment]
thix bug is gone in `15.06pre64423.4e5e441 (Dingo)` :)

**Comment by flosse** [comment]
...its strange: if `backintime-qt4` is listed in `environment.systemPackages` then the error occurs, even if I do `nix-shell --pure -p backintime-qt4`. Removing the package from `environment.systemPackages` solves the problem. Why?

**Comment by flosse** [comment]
it's still there in `16.03pre70787.6d31e9b (Emu)`

**Comment by Profpatsch** [comment]
(triage) I’m sorry we didn’t react. Works for me on a current version with `nix-shell -p backintime-qt4 --run backintime-qt4`.
