### ISSUE TITLE
home-assistant: ./parse-requirements.py fails to update on master

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#83912]
**Describe the bug**

I can't add a new `home-assistant` component because `./parse-requirements.txt` fails for reasons unrelated to my changes:

```
> ./parse-requirements.py
$ mypy --ignore-missing-imports ./parse-requirements.py
git status
Success: no issues found in 1 source file
Generating component-packages.nix for version 0.107.7
Component androidtv is missing True dependencies
missing requirements: ['adb-shell', 'androidtv', 'pure-python-adb']
Component arwn is missing True dependencies
missing requirements: []
Component default_config is missing True dependencies
missing requirements: ['home-assistant-frontend']
Component doorbird is missing True dependencies
missing requirements: ['doorbirdpy', 'home-assistant-frontend']
Component dsmr_reader is missing True dependencies
missing requirements: []
Component google is missing True dependencies
missing requirements: []
Component huawei_lte is missing True dependencies
missing requirements: ['huawei-lte-api', 'url-normalize']
Component logbook is missing True dependencies
missing requirements: ['home-assistant-frontend']
Component logi_circle is missing True dependencies
missing requirements: ['logi_circle']
Component manual_mqtt is missing True dependencies
missing requirements: []
Component mcp23017 is missing True dependencies
missing requirements: ['RPi.GPIO', 'adafruit-blinka', 'adafruit-circuitpython-mcp230xx']
Component mqtt is missing True dependencies
missing requirements: []
Component mqtt_eventstream is missing True dependencies
missing requirements: []
Component mqtt_json is missing True dependencies
missing requirements: []
Component mqtt_room is missing True dependencies
missing requirements: []
Component mqtt_statestream is missing True dependencies
missing requirements: []
Component plex is missing True dependencies
missing requirements: []
Component safe_mode is missing True dependencies
missing requirements: ['home-assistant-frontend']
Component smartthings is missing True dependencies
missing requirements: ['pysmartapp', 'pysmartthings']
Component snips is missing True dependencies
missing requirements: []
Component telegram is missing True dependencies
missing requirements: []
Component telegram_bot is missing True dependencies
missing requirements: []
Traceback (most recent call last):
  File "./parse-requirements.py", line 182, in <module>
    main()
  File "./parse-requirements.py", line 149, in main
    attr_path = name_to_attr_path(name, packages)
  File "./parse-requirements.py", line 126, in name_to_attr_path
    req, attr_paths
AssertionError: tensorflow matches more than one derivation: {'python3Packages.tensorflow-build_2', 'python3Packages.tensorflow-bin_2', 'python3Packages.tensorflow'}

```

**Comment by mweinelt** [comment]
@colemickens Fixed in 02becde898971983b0382a89409fa94b97021001, can you confirm?
