### ISSUE TITLE
Add package: catcli

### ISSUE THREAD

**Issue by petersjt014** [NixOS/nixpkgs#84071]
**Catcli**
"The command line catalog tool for your offline data."
Because git-annex is *hard*.

**Metadata**

* homepage URL: https://github.com/deadc0de6/catcli
* source URL: https://github.com/deadc0de6/catcli/releases/tag/v0.5.13
* license: gpl3
* platforms: x86_64, probably others

WIP definition

```nix
{ lib
, stdenv
, fetchFromGitHub
, buildPythonApplication
, docopt, anytree, ...
}:

buildPythonApplication rec {

  pname = "catcli";
  version = "v0.5.13";

  src = fetchFromGitHub {
    owner = "deadc0de6";
    repo = pname;
    rev = version;
    sha256 = "04mrkqmm2c8fhi1h1hddc4yh3dqhcvkmcwzhj0ggn34v7wavgb5i";
  };

  propagatedBuildInputs = [ docopt anytree ];
  buildInputs = [ docopt anytree ];

  postPatch = '' patchShebangs . '';

  meta = with stdenv.lib; {
    homepage = https://github.com/deadc0de6/catcli;
    description = "The command line catalog tool for your offline data";
    license = licenses.gpl3;
    maintainers = with maintainers; [ petersjt014 ];
  };
}
```
This builds with the relevant callPackage line in top-level.nix (I think that's where it must go), but attempting to invoke it with `./result/bin/catcli` yields:
```
Traceback (most recent call last):
  File "/nix/store/vs6ay1fks6gnyq2vbc8bmvy5ydfida56-catcli-v0.5.13/bin/.catcli-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/vs6ay1fks6gnyq2vbc8bmvy5ydfida56-catcli-v0.5.13/lib/python3.7/site-packages/catcli/__init__.py", line 12, in main
    import catcli.catcli
  File "/nix/store/vs6ay1fks6gnyq2vbc8bmvy5ydfida56-catcli-v0.5.13/lib/python3.7/site-packages/catcli/catcli.py", line 14, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'
```
This is weird, as I have docopt in the build inputs.
**edit:** typo. `./result/bin/catcli --help` now shows the expected help text.
Apparently `buildPythonApplication` takes care of the tests too, so there's nothing more to add that I can think of for now.

**Comment by petersjt014** [comment]
#84078
