### ISSUE TITLE
git-remote-hg has python import problem

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#84249]
**Describe the bug**

`git-remote-hg` depends on mercurial, which depends on python. Executing `git-remote-hg` shows that certain modules are imported incorrectly.

**To Reproduce**

```
$ nix-env -iA nixos.gitAndTools.git-remote-hg
$ git clone "hg::~/foo"
Klone nach 'foo' ...
Traceback (most recent call last):
  File "/nix/store/pcwk49av5fkrsbv6hghnxp6bjr6zfhpa-git-remote-hg-1.0.1/bin/.git-remote-hg-wrapped", line 16, in <module>
    from mercurial import hg, ui, bookmarks, context, encoding
  File "/nix/store/l6k31xsm4w68zb9ff0m0l9ybc7miml2q-mercurial-5.3/lib/python3.7/site-packages/mercurial/hg.py", line 16, in <module>
    from .i18n import _
  File "/nix/store/l6k31xsm4w68zb9ff0m0l9ybc7miml2q-mercurial-5.3/lib/python3.7/site-packages/mercurial/i18n.py", line 15, in <module>
    from .pycompat import getattr
  File "/nix/store/l6k31xsm4w68zb9ff0m0l9ybc7miml2q-mercurial-5.3/lib/python3.7/site-packages/mercurial/pycompat.py", line 38, in <module>
    from .thirdparty.concurrent import futures
ImportError: No module named concurrent
```

Cloning the same repository directly with `hg` works fine.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.25, NixOS, 20.09pre217446.ddf87fb1baf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"musnix, nixos-20.09pre217446.ddf87fb1baf"`
 - channels(turion): `"home-manager, nixos-19.03-19.03.173691.34c7eb7545d, nixos-unstable-newer-20.09pre217446.ddf87fb1baf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by turion** [comment]
This is still relevant.

**Comment by turion** [comment]
Tested recently, seems to work again for some reason.
