### ISSUE TITLE
Blink does not run

### ISSUE THREAD

**Issue by anm** [NixOS/nixpkgs#85242]
**Describe the bug**
blink does not run.

**To Reproduce**
$ nix-shell -p blink
$ blink 
Traceback (most recent call last):
  File "/nix/store/nyskcsb0kw7h221qp7wilzm9rhb5jyam-blink-3.0.3/bin/..blink-wrapped-wrapped", line 68, in <module>
    from blink import Blink
  File "/nix/store/nyskcsb0kw7h221qp7wilzm9rhb5jyam-blink-3.0.3/lib/python2.7/site-packages/blink/__init__.py", line 15, in <module>
    from sipsimple.account import Account, AccountManager, BonjourAccount
  File "/nix/store/zv3wjwb4x9w4n3m0jwmjvflp6nz86a0g-python2.7-sipsimple-3.4.2/lib/python2.7/site-packages/sipsimple/__init__.py", line 3, in <module>
    from sipsimple.logging import log  # This will initialize and make our logger available early, before anything else is loaded
  File "/nix/store/zv3wjwb4x9w4n3m0jwmjvflp6nz86a0g-python2.7-sipsimple-3.4.2/lib/python2.7/site-packages/sipsimple/logging.py", line 7, in <module>
    log = log.get_logger('sipsimple')
AttributeError: 'module' object has no attribute 'get_logger'

**Expected behavior**
Application should run.

**Notify maintainers**
@pSub 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.114, NixOS, 19.09.2370.e10c65cdb35 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(<user>): `""`
 - channels(root): `"nixos-19.09.2370.e10c65cdb35, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by armeenm** [comment]
Blink was [dropped](https://github.com/NixOS/nixpkgs/commit/33df2ffa0a5e666f9fd9a2a836b2ff4f96224e6d) from nixpkgs. Close?
