### ISSUE TITLE
ibus-setup fails to start

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#85515]
**Describe the bug**
```
❯ ibus-setup                                                                  ~
Traceback (most recent call last):
  File "/nix/store/i4mmw69f56zwi753ssp9pq2wzq2lnznm-ibus-1.5.22/share/ibus/setup/main.py", line 38, in <module>
    gi_require_version('IBus', '1.0')
  File "/nix/store/w3szjxdykh3588wqcgwmnbwapb0vz38c-python3-3.7.7-env/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace IBus not available
```

**Additional context**
Here's the content of ibus-setup wrapper on my system
```
#! /nix/store/ffli6m23501dkiznwlkf6n4xvrj02snr-bash-4.4-p23/bin/bash -e
export GIO_EXTRA_MODULES='/nix/store/0byixyx6l833y9a7ah8ygbh4d4nfgcin-dconf-0.36.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export GIO_EXTRA_MODULES='/nix/store/0byixyx6l833y9a7ah8ygbh4d4nfgcin-dconf-0.36.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export GDK_PIXBUF_MODULE_FILE='/nix/store/a7dwk7qamr2j7220rsfvn8w386b8a3lc-librsvg-2.48.0/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'
export XDG_DATA_DIRS='/nix/store/2chzii7gwmlcii9x73l0v3bl7lf2awvb-gtk+3-3.24.14/share/gsettings-schemas/gtk+3-3.24.14:/nix/store/xjg7kpw38mfaab2fsarll2d39nk06ha5-gsettings-desktop-schemas-3.36.0/share/gsettings-schemas/gsettings-desktop-schemas-3.36.0:/nix/store/2chzii7gwmlcii9x73l0v3bl7lf2awvb-gtk+3-3.24.14/share/gsettings-schemas/gtk+3-3.24.14:/nix/store/xjg7kpw38mfaab2fsarll2d39nk06ha5-gsettings-desktop-schemas-3.36.0/share/gsettings-schemas/gsettings-desktop-schemas-3.36.0:/nix/store/i4mmw69f56zwi753ssp9pq2wzq2lnznm-ibus-1.5.22/share/gsettings-schemas/ibus-1.5.22'${XDG_DATA_DIRS:+':'}$XDG_DATA_DIRS
export XDG_DATA_DIRS='/nix/store/i4mmw69f56zwi753ssp9pq2wzq2lnznm-ibus-1.5.22/share'${XDG_DATA_DIRS:+':'}$XDG_DATA_DIRS
export GI_TYPELIB_PATH='/nix/store/2chzii7gwmlcii9x73l0v3bl7lf2awvb-gtk+3-3.24.14/lib/girepository-1.0:/nix/store/a7dwk7qamr2j7220rsfvn8w386b8a3lc-librsvg-2.48.0/lib/girepository-1.0:/nix/store/kah2hha1zcbv0xvyq7fdx26gxd03002x-gdk-pixbuf-2.40.0/lib/girepository-1.0:/nix/store/r4vrzisk85nfkmmafvvi348czb8l4p86-gobject-introspection-1.64.0/lib/girepository-1.0:/nix/store/y9sn0hll1m90zdi8bwa5126lmdkdp8i9-pango-1.44.7/lib/girepository-1.0:/nix/store/ly22x5s6v91i840xkkj82dhblkfgl79v-atk-2.35.1/lib/girepository-1.0:/nix/store/br3plmq0cw4ggxzrcharf46wbhyb7rya-gtk+-2.24.32/lib/girepository-1.0:/nix/store/xjg7kpw38mfaab2fsarll2d39nk06ha5-gsettings-desktop-schemas-3.36.0/lib/girepository-1.0:/nix/store/wqf98k757rvmrzyldzj4fmq4vfl7lx1q-json-glib-1.4.4/lib/girepository-1.0:/nix/store/39mcxzz3c9jl1l6mcjjp6fxdcdsm4la3-libnotify-0.7.9/lib/girepository-1.0:/nix/store/2chzii7gwmlcii9x73l0v3bl7lf2awvb-gtk+3-3.24.14/lib/girepository-1.0:/nix/store/a7dwk7qamr2j7220rsfvn8w386b8a3lc-librsvg-2.48.0/lib/girepository-1.0:/nix/store/kah2hha1zcbv0xvyq7fdx26gxd03002x-gdk-pixbuf-2.40.0/lib/girepository-1.0:/nix/store/r4vrzisk85nfkmmafvvi348czb8l4p86-gobject-introspection-1.64.0/lib/girepository-1.0:/nix/store/y9sn0hll1m90zdi8bwa5126lmdkdp8i9-pango-1.44.7/lib/girepository-1.0:/nix/store/ly22x5s6v91i840xkkj82dhblkfgl79v-atk-2.35.1/lib/girepository-1.0:/nix/store/br3plmq0cw4ggxzrcharf46wbhyb7rya-gtk+-2.24.32/lib/girepository-1.0:/nix/store/xjg7kpw38mfaab2fsarll2d39nk06ha5-gsettings-desktop-schemas-3.36.0/lib/girepository-1.0:/nix/store/wqf98k757rvmrzyldzj4fmq4vfl7lx1q-json-glib-1.4.4/lib/girepository-1.0:/nix/store/39mcxzz3c9jl1l6mcjjp6fxdcdsm4la3-libnotify-0.7.9/lib/girepository-1.0'${GI_TYPELIB_PATH:+':'}$GI_TYPELIB_PATH
exec -a "$0" "/nix/store/i4mmw69f56zwi753ssp9pq2wzq2lnznm-ibus-1.5.22/bin/.ibus-setup-wrapped"  "$@"
```

Here's the nixos config
```
i18n.inputMethod = {
  enabled = "ibus";
  ibus.engines = with pkgs.ibus-engines; [ uniemoji typing-booster ];
};
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.31, NixOS, 20.09-4cbb870 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200403_3473b19`
 - channels(root): `""`
 - nixpkgs: `/run/current-system/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ibus
# a list of nixos modules affected by the problem
module:
```

**Comment by worldofpeace** [comment]
cc @jtojnar (think you fixed this?)

**Comment by jtojnar** [comment]
I think I mostly worked on the setups of modules. But pretty sure this was working before. If I add `gobject-introspection` to `nativeBuildInputs` the number of entries in `GI_TYPELIB_PATH` goes from 20 to 50 but still no ibus. Weird.

**Comment by SuperBo** [comment]
I also have this issue in latest version.

**Comment by jtojnar** [comment]
Yes, this is a bug. I could reproduce it in a minimal test case:

https://github.com/NixOS/nixpkgs/commit/7ca2990a876c41cd94a26ee043ab0092386825ad#diff-dc66b3a8751266cd362dbf0fcd7e2fc9R124-R131

**Comment by SuperBo** [comment]
I think the main reason is file `*ibus-1.5.22/lib/python3.7/site-packages/gi/overrides/IBus.py` can't be found by pyGObject

**Comment by jtojnar** [comment]
That is not it. The reason is the wrappers are not adding typelibs from 
the package itself to `GI_TYPELIB_PATH`.

**Comment by SuperBo** [comment]
So you already have solution for this problem, haven't you?

**Comment by jtojnar** [comment]
No. Only a minimal test case that reproduces it. Will not be able to look
into it until the day after tomorrow.

**Comment by jtojnar** [comment]
Looks like the issue is that [`giDiscoverSelf`](https://github.com/NixOS/nixpkgs/blob/9d73d285802b08b0c0082d8b9a91ad27613547aa/pkgs/development/libraries/gobject-introspection/setup-hook.sh#L21) that sets the `GI_TYPELIB_PATH` runs as `preFixup` hook so it runs after [`gappsWrapperArgsHook`](https://github.com/NixOS/nixpkgs/blob/9d73d285802b08b0c0082d8b9a91ad27613547aa/pkgs/build-support/setup-hooks/wrap-gapps-hook.sh#L41) that needs it.

**Comment by worldofpeace** [comment]
I tried this on release-20.03 and got
```
nix shell nixpkgs/release-20.03#ibus 

ibus-setup                                                                                                                                      
Traceback (most recent call last):
  File "/nix/store/01djnnw9gh2cazjr1nqakazdsag8xsc0-ibus-1.5.21/share/ibus/setup/main.py", line 38, in <module>
    gi_require_version('IBus', '1.0')
  File "/nix/store/hz347980f49wjxcgn6whmyyvfa3xavpg-python3-3.7.6-env/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace IBus not available
```

but it is fixed on master. I'll backport this to 20.03.

**Comment by jtojnar** [comment]
This has been fixed by https://github.com/NixOS/nixpkgs/pull/86416.
