### ISSUE TITLE
Nixos update failed "numpy.distutils.system_info.NotFoundError: No lapack/blas resources found."

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#85655]
**Describe the bug**
Error during a system update

 ```
unpacking channels...
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/1wyn8ghsi55q5566gr5lhqjmyss17cds-tor-browser-linux64-9.0.9_en-US.tar.xz.drv
  /nix/store/72xgm313ishj9aqqaxrpywiln2s6g6n3-sublime_text_3_build_3211_x64.tar.bz2.drv
  /nix/store/rvdq6n7g0iix49a7iqf1iwap3ki6qzy6-sublimetext3-bin-3211.drv
  /nix/store/2lr9lxhxbrmjd3abdp2lxw35nh4arm70-sublimetext3-3211.drv
  /nix/store/bhldx72i3j93ba51ymrr9y82x9p3kbw2-source.drv
  /nix/store/3f8jzyffsv4xjil6xkp1g1rc35sf1rf2-xmind-8-update8.drv
  /nix/store/67ggczlhbnpk55d72bznizk7wrqnpjjw-teams_1.3.00.5153_amd64.deb.drv
  /nix/store/9q2sch7c3bz6z0aljd9hfqkw5dznr3c9-teams-1.3.00.5153.drv
  /nix/store/fxssfq5la12v6wb3zcw4ydd8nrk68vlf-vscode-1.44.1.drv
  /nix/store/vnfbfkpi66qp9067wlap4i0q36ng2y4v-python3.7-scipy-1.4.1.drv
  /nix/store/lxhlzfrhjp860gn0jr340nc0dyz7hcvc-python3.7-pandas-1.0.3.drv
  /nix/store/giay0vmsm4v3pcx73fg899vghgsvlqj8-python3-3.7.7-env.drv
  /nix/store/lbb2habvqrvknygsyv426k63lminjdzx-tor-browser-bundle-bin-9.0.9.drv
  /nix/store/vch2vi2sq7f8g2c0v8j1lw17ac46jrdg-zoom-us-3.5.385850.0413.drv
  /nix/store/360zsh5crkw6wrkmjwj9wa99b1pdnc7q-user-environment.drv
  /nix/store/y9bswb9jhsfwin284xv12ggsk6dlb58g-etc.drv
  /nix/store/g6f6vza0fb257452176y6g60i4fhvblz-nixos-system-p53-nixos-19.09.2407.b67bc34d4e3.drv
building '/nix/store/fxssfq5la12v6wb3zcw4ydd8nrk68vlf-vscode-1.44.1.drv'...
building '/nix/store/vch2vi2sq7f8g2c0v8j1lw17ac46jrdg-zoom-us-3.5.385850.0413.drv'...
building '/nix/store/vnfbfkpi66qp9067wlap4i0q36ng2y4v-python3.7-scipy-1.4.1.drv'...
building '/nix/store/1wyn8ghsi55q5566gr5lhqjmyss17cds-tor-browser-linux64-9.0.9_en-US.tar.xz.drv'...
building '/nix/store/bhldx72i3j93ba51ymrr9y82x9p3kbw2-source.drv'...
building '/nix/store/67ggczlhbnpk55d72bznizk7wrqnpjjw-teams_1.3.00.5153_amd64.deb.drv'...
building '/nix/store/72xgm313ishj9aqqaxrpywiln2s6g6n3-sublime_text_3_build_3211_x64.tar.bz2.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing setuptools-check-hook
unpacking sources
unpacking source archive /nix/store/jzrmjnhj56rdg13rqxylp3scxjjihr3v-scipy-1.4.1.tar.gz

trying https://dist.torproject.org/torbrowser/9.0.9/tor-browser-linux64-9.0.9_en-US.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

trying https://xmind.net/xmind/downloads/xmind-8-update8-linux.zip

trying https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.3.00.5153_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
unpacking sources
unpacking source archive /nix/store/54hq9dl1g80igcy19s4vq7x90mjr9dkn-VSCode_1.44.1_linux-x64.tar.gz

trying https://download.sublimetext.com/sublime_text_3_build_3211_x64.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
source root is scipy-1.4.1
setting SOURCE_DATE_EPOCH to timestamp 1576697826 of file scipy-1.4.1/PKG-INFO
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
Running from scipy source directory.
lapack_opt_info:
lapack_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/nix/store/lm0w36273v76nnph1518gwbv1g45sl8w-python3-3.7.7/lib']
  NOT AVAILABLE

openblas_lapack_info:
  libraries openblas not found in ['/nix/store/3gia15f4i46fvxxr6n4n3jlp8di2rxyw-blas-3/lib', '/nix/store/qrfg733cck2znlfp7bagrlqsrjxja9bm-lapack-3/lib']
  NOT AVAILABLE

openblas_clapack_info:
  libraries openblas,lapack not found in ['/nix/store/3gia15f4i46fvxxr6n4n3jlp8di2rxyw-blas-3/lib', '/nix/store/qrfg733cck2znlfp7bagrlqsrjxja9bm-lapack-3/lib']
  NOT AVAILABLE

flame_info:
  libraries flame not found in ['/nix/store/lm0w36273v76nnph1518gwbv1g45sl8w-python3-3.7.7/lib']
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in /nix/store/lm0w36273v76nnph1518gwbv1g45sl8w-python3-3.7.7/lib
  libraries tatlas,tatlas not found in /nix/store/lm0w36273v76nnph1518gwbv1g45sl8w-python3-3.7.7/lib
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
  libraries lapack_atlas not found in /nix/store/lm0w36273v76nnph1518gwbv1g45sl8w-python3-3.7.7/lib
  libraries satlas,satlas not found in /nix/store/lm0w36273v76nnph1518gwbv1g45sl8w-python3-3.7.7/lib
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in /nix/store/lm0w36273v76nnph1518gwbv1g45sl8w-python3-3.7.7/lib
  libraries ptf77blas,ptcblas,atlas not found in /nix/store/lm0w36273v76nnph1518gwbv1g45sl8w-python3-3.7.7/lib
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
  libraries lapack_atlas not found in /nix/store/lm0w36273v76nnph1518gwbv1g45sl8w-python3-3.7.7/lib
  libraries f77blas,cblas,atlas not found in /nix/store/lm0w36273v76nnph1518gwbv1g45sl8w-python3-3.7.7/lib
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

accelerate_info:
  NOT AVAILABLE

lapack_info:
  libraries lapack not found in ['/nix/store/lm0w36273v76nnph1518gwbv1g45sl8w-python3-3.7.7/lib']
  NOT AVAILABLE

/nix/store/qb19waw8994w0jm43rsxn43b244i8a0v-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/distutils/system_info.py:1730: UserWarning:
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  return getattr(self, '_calc_info_{}'.format(name))()
lapack_src_info:
  NOT AVAILABLE

/nix/store/qb19waw8994w0jm43rsxn43b244i8a0v-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/distutils/system_info.py:1730: UserWarning:
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  return getattr(self, '_calc_info_{}'.format(name))()
  NOT AVAILABLE

Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 540, in <module>
    setup_package()
  File "setup.py", line 536, in setup_package
    setup(**metadata)
  File "/nix/store/qb19waw8994w0jm43rsxn43b244i8a0v-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/distutils/core.py", line 137, in setup
    config = configuration()
  File "setup.py", line 435, in configuration
    raise NotFoundError(msg)
numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
builder for '/nix/store/vnfbfkpi66qp9067wlap4i0q36ng2y4v-python3.7-scipy-1.4.1.drv' failed with exit code 1
cannot build derivation '/nix/store/giay0vmsm4v3pcx73fg899vghgsvlqj8-python3-3.7.7-env.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/360zsh5crkw6wrkmjwj9wa99b1pdnc7q-user-environment.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/y9bswb9jhsfwin284xv12ggsk6dlb58g-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/g6f6vza0fb257452176y6g60i4fhvblz-nixos-system-p53-nixos-19.09.2407.b67bc34d4e3.drv': 1 dependencies couldn't be built
error: build of '/nix/store/g6f6vza0fb257452176y6g60i4fhvblz-nixos-system-p53-nixos-19.09.2407.b67bc34d4e3.drv' failed
```

**To Reproduce**
1. nix-channel --update && nixos-rebuild switch

**Expected behavior**
A system update to be completed

**Additional context**
Usual system update

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/5h35s50503spks8gkxdv3kk4szz8vx9g-bash-interactive-4.4-p23-dev
copying path '/nix/store/5h35s50503spks8gkxdv3kk4szz8vx9g-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.32, NixOS, 19.09.2407.b67bc34d4e3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"home-manager-19.09, nixos-19.09.2426.9237a09d8ed, unstable-20.09pre222138.b3c3a0bd183"`
 - channels(mudrii): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mudrii** [comment]
Oh this is duplicated bug as the issue is already in discussion on https://github.com/NixOS/nixpkgs/issues/85637
