### ISSUE TITLE
nixos/xpra: xpra_Xdummy 3.0 crashes

### ISSUE THREAD

**Issue by lourkeur** [NixOS/nixpkgs#85694]
**Describe the bug**
When xpra is started as display-manager, the following error is raised:
```
Error: cannot start the seamless server
Traceback (most recent call last):
  File "/nix/store/mpnf5yz81h2xgh0qm05fy32b8ahmdgim-xpra-3.0.5/lib/python3.7/site-packages/xpra/scripts/server.py", line 850, in do_run_server
    app.server_init()
  File "/nix/store/mpnf5yz81h2xgh0qm05fy32b8ahmdgim-xpra-3.0.5/lib/python3.7/site-packages/xpra/x11/server.py", line 223, in server_init
    X11ServerBase.server_init(self)
  File "/nix/store/mpnf5yz81h2xgh0qm05fy32b8ahmdgim-xpra-3.0.5/lib/python3.7/site-packages/xpra/x11/x11_server_core.py", line 105, in server_init
    self.x11_init()
  File "/nix/store/mpnf5yz81h2xgh0qm05fy32b8ahmdgim-xpra-3.0.5/lib/python3.7/site-packages/xpra/x11/server.py", line 246, in x11_init
    X11ServerBase.x11_init(self)
  File "/nix/store/mpnf5yz81h2xgh0qm05fy32b8ahmdgim-xpra-3.0.5/lib/python3.7/site-packages/xpra/x11/x11_server_core.py", line 126, in x11_init
    elif os.path.isabs(self.fake_xinerama):
  File "/nix/store/nlgrx0cl1l87nx0w660lb3jksn9jdca9-python3-3.7.6/lib/python3.7/posixpath.py", line 66, in isabs
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**To Reproduce**
1. set `services.xserver.displayManager.xpra.enable = true`. Recommend using a container, in fact I reproduced it in the most minimal container.
2. boot
3. check journal

**Expected behavior**
Xpra should start normally.

**Screenshots**

**Additional context**
This comes from the fake-xinerama setting in xpra. There is logic to auto-detect it apparently, but it returns ` None` for some reason. A super dirty quickfix is to add `fake-xinerama=no` to ~/.config/xpra/xpra.conf` and it gets xpra to not crash.

**Notify maintainers**

@offlinehacker

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.33, NixOS, 20.03.1418.5272327b81e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1418.5272327b81e"`
 - channels(louis): `"nixos-unstable-20.09pre216896.0729b8c55e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: xpra
# a list of nixos modules affected by the problem
module: xpra
```

**Comment by lourkeur** [comment]
there are dangling symlinks in libfakeXinerama, I think that might be the cause.
```
$ nix-build '<nixpkgs>' -A libfakeXinerama
$ ls -l result/lib
-r-xr-xr-x 2 root root 18080  1 jan  1970 libfakeXinerama.so.1.0
lrwxrwxrwx 3 root root    16  1 jan  1970 libXinerama.so -> libXinerama.so.1
lrwxrwxrwx 3 root root    18  1 jan  1970 libXinerama.so.1 -> libXinerama.so.1.0
```

**Comment by lourkeur** [comment]
OK so, `xpra.x11.fakeXinerama.find_libfakeXinerama()` will try to locate libfakeXinerama using ld and upon success, tries to record its SONAME (it doesn't have one so that fails), then tries to find it manually in $LD_LIBRARY_PATH, (which fails), then tries ldconfig -p (which returns None), then tries to find it manually in $LD_LIBRARY_PATH but in a different function. That function can and should be side-stepped altogether by setting fake-xinerama upfront. investigating this now.
