### ISSUE TITLE
mypaint fails on start

### ISSUE THREAD

**Issue by MMesch** [NixOS/nixpkgs#85860]
**Describe the bug**

Starting `mypaint` fails with Gdk error:

```
[nix-shell:~/Projects/tweag/pfizer/ToE/ToE]$ mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/nix/store/6j9ndjmi4flqpgw48frdprni2qdf2q4v-mypaint-1.2.1'
INFO: lib.i18n: POSIX: LANG='en_US.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None
Gdk-Message: 14:41:24.280: Unable to load exchange from the cursor theme
Traceback (most recent call last):
  File "/nix/store/6j9ndjmi4flqpgw48frdprni2qdf2q4v-mypaint-1.2.1/bin/.mypaint-wrapped", line 464, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/nix/store/6j9ndjmi4flqpgw48frdprni2qdf2q4v-mypaint-1.2.1/share/mypaint/gui/main.py", line 95, in main
    from gui import application
  File "/nix/store/6j9ndjmi4flqpgw48frdprni2qdf2q4v-mypaint-1.2.1/share/mypaint/gui/application.py", line 54, in <module>
    import filehandling
  File "/nix/store/6j9ndjmi4flqpgw48frdprni2qdf2q4v-mypaint-1.2.1/share/mypaint/gui/filehandling.py", line 31, in <module>
    import drawwindow
  File "/nix/store/6j9ndjmi4flqpgw48frdprni2qdf2q4v-mypaint-1.2.1/share/mypaint/gui/drawwindow.py", line 39, in <module>
    import quickchoice
  File "/nix/store/6j9ndjmi4flqpgw48frdprni2qdf2q4v-mypaint-1.2.1/share/mypaint/gui/quickchoice.py", line 25, in <module>
    import gui.colortools
  File "/nix/store/6j9ndjmi4flqpgw48frdprni2qdf2q4v-mypaint-1.2.1/share/mypaint/gui/colortools.py", line 20, in <module>
    from colors.hcywheel import HCYAdjusterPage
  File "/nix/store/6j9ndjmi4flqpgw48frdprni2qdf2q4v-mypaint-1.2.1/share/mypaint/gui/colors/hcywheel.py", line 379, in <module>
    class HCYMaskEditorWheel (HCYHueChromaWheel):
  File "/nix/store/6j9ndjmi4flqpgw48frdprni2qdf2q4v-mypaint-1.2.1/share/mypaint/gui/colors/hcywheel.py", line 397, in HCYMaskEditorWheel
    __rotate_cursor = gdk.Cursor(gdk.EXCHANGE)
  File "/nix/store/w3vc3pfnp8ji5adp1z5ln3a0hcm7plwa-python2.7-pygobject-3.30.4/lib/python2.7/site-packages/gi/overrides/Gdk.py", line 346, in __new__
    return cls.new(*args, **kwds)
TypeError: constructor returned NULL
```

**To Reproduce**

Execute:

 `nix-shell -p mypaint -I nixpkgs=channel:nixos-20.03 --command mypaint`

or

 `nix-shell -p mypaint -I nixpkgs=channel:nixos-19.09 --command mypaint`
 `nix-shell -p mypaint -I nixpkgs=channel:nixos-19.03 --command mypaint`

**Expected behavior**

mypaint starts

**Notify maintainers**

@cillianderoiste 
@jtojnar 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.103, NixOS, 19.09.2079.8731aaaf8b3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.2079.8731aaaf8b3, home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by MMesch** [comment]
Yes running wayland! I'll try this. Thanks for the quick comment!

**Comment by MMesch** [comment]
Works fine with: ` nix-shell -p mypaint -I nixpkgs=channel:nixos-unstable`
I really should have tried this!
