### ISSUE TITLE
Conflicting readline in lldb site-packages

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#87657]
Probably needs additional triage but;

It looks like if you add the lldb python bindings to PYTHONPATH, that breaks something in readline, because trying to tab complete in pudb (python debugger frontend, unrelated to lldb) breaks.

I think this may have something to do with the readline.so in the site-packages of the lldb library, because if I copy the output and remove that library, pudb works fine again.

The repro is with 19.09 but given that this is a bit obscure it might exist on newer versions, which is why I'm filing the issue. 

repro:
```
nix-shell -I nixpkgs=channel:nixos-19.09 -p "python27.withPackages (p: [ p.pudb ])" lldb --run 'PYTHONPATH="$PYTHONPATH":$(nix-build -I nixpkgs=channel:nixos-19.09 --no-link "<nixpkgs>" -A lldb)/lib/python2.7/site-packages python -c "import pudb; pu.db"'
```

Error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/0yz15vp6xvaixrkls7y85r65d95jc0m4-python-2.7.17/lib/python2.7/bdb.py", line 53, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/nix/store/0yz15vp6xvaixrkls7y85r65d95jc0m4-python-2.7.17/lib/python2.7/bdb.py", line 88, in dispatch_return
    self.user_return(frame, arg)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/pudb/debugger.py", line 425, in user_return
    self.interaction(frame)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/pudb/debugger.py", line 378, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/pudb/debugger.py", line 2147, in call_with_ui
    return f(*args, **kwargs)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/pudb/debugger.py", line 2399, in interaction
    self.event_loop()
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/pudb/debugger.py", line 2365, in event_loop
    toplevel.keypress(self.size, k)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/pudb/ui_tools.py", line 107, in keypress
    result = self._w.keypress(size, key)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/urwid/container.py", line 1590, in keypress
    key = self.focus.keypress(tsize, key)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/pudb/ui_tools.py", line 107, in keypress
    result = self._w.keypress(size, key)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/urwid/container.py", line 1590, in keypress
    key = self.focus.keypress(tsize, key)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/pudb/ui_tools.py", line 103, in keypress
    result = handler(self, size, key)
  File "/nix/store/b4cz5ssdcss8q137qfn3zbbpv80vyab1-python-2.7.17-env/lib/python2.7/site-packages/pudb/debugger.py", line 1495, in cmdline_tab_complete
    from rlcompleter import Completer
  File "/nix/store/0yz15vp6xvaixrkls7y85r65d95jc0m4-python-2.7.17/lib/python2.7/rlcompleter.py", line 172, in <module>
    readline.set_completer(Completer().complete)
AttributeError: 'module' object has no attribute 'set_completer'
```

**Comment by deliciouslytyped** [comment]
```
nix-shell -I nixpkgs=channel:nixos-unstable -p "python37.withPackages (p: [ p.pudb ])" lldb --run 'PYTHONPATH="$PYTHONPATH":$(nix-build -I nixpkgs=channel:nixos-unstable --no-link "<nixpkgs>" -A "llvmPackages_10.lldb")/lib/python2.7/site-packages python -c "import pudb; pu.db"'
```
does not reproduce on unstable, but at least the error is documented now.
There is no readline.so in `:$(nix-build -I nixpkgs=channel:nixos-unstable --no-link "<nixpkgs>" -A "llvmPackages_10.lldb")/lib/python2.7/site-packages`.

**Comment by deliciouslytyped** [comment]
I can't check for a full repro on unstable because lldb now has a python3.7 site-packages, but it seems to work with; 
nix-shell -I nixpkgs=channel:nixos-unstable -p "python37.withPackages (p: [ p.pudb ])" lldb --run 'PYTHONPATH="$PYTHONPATH":$(nix-build -I nixpkgs=channel:nixos-unstable --no-link "<nixpkgs>" -A lldb)/lib/python3.7/site-packages python -c "import lldb; import pudb; pu.db"'
