### ISSUE TITLE
Cabal doesn't build on GHCJS (related to nodejs, libuv)

### ISSUE THREAD

**Issue by k0001** [NixOS/nixpkgs#8781]
`Cabal` doesn't build with GHCJS as of `nixpkgs-c87ee37b551fb3dba7f2980f0dbc7269a6984029` due to an issue on `nodejs` and/or `libuv` as suggested in https://github.com/joyent/node/issues/14571

It looks like this is related to https://github.com/NixOS/nixpkgs/issues/7243

```
[79 of 79] Compiling Main             ( boot/cabal/Cabal/dist/setup/setup.hs, boot/cabal/Cabal/dist/setup/Main.js_o )
Linking ./boot/cabal/Cabal/dist/setup/setup.jsexe (Distribution.Compat.Binary,Distribution.Compat.CopyFile,Distribution.Compat.CreatePipe,Distribution.Compat.Environment,Distribution.Compat.Exception,Distribution.Compat.ReadP,Distribution.Compat.TempFile,Distribution.Compiler,Distribution.GetOpt,Distribution.InstalledPackageInfo,Distribution.License,Distribution.ModuleName,Distribution.Package,Distribution.PackageDescription,Distribution.PackageDescription.Check,Distribution.PackageDescription.Configuration,Distribution.PackageDescription.Parse,Distribution.PackageDescription.Utils,Distribution.ParseUtils,Distribution.ReadE,Distribution.Simple,Distribution.Simple.Bench,Distribution.Simple.Build,Distribution.Simple.Build.Macros,Distribution.Simple.Build.PathsModule,Distribution.Simple.BuildPaths,Distribution.Simple.BuildTarget,Distribution.Simple.CCompiler,Distribution.Simple.Command,Distribution.Simple.Compiler,Distribution.Simple.Configure,Distribution.Simple.GHC,Distribution.Simple.GHC.IPI641,Distribution.Simple.GHC.IPI642,Distribution.Simple.GHC.ImplInfo,Distribution.Simple.GHC.Internal,Distribution.Simple.GHCJS,Distribution.Simple.Haddock,Distribution.Simple.HaskellSuite,Distribution.Simple.Hpc,Distribution.Simple.Install,Distribution.Simple.InstallDirs,Distribution.Simple.JHC,Distribution.Simple.LHC,Distribution.Simple.LocalBuildInfo,Distribution.Simple.PackageIndex,Distribution.Simple.PreProcess,Distribution.Simple.PreProcess.Unlit,Distribution.Simple.Program,Distribution.Simple.Program.Ar,Distribution.Simple.Program.Builtin,Distribution.Simple.Program.Db,Distribution.Simple.Program.Find,Distribution.Simple.Program.GHC,Distribution.Simple.Program.HcPkg,Distribution.Simple.Program.Hpc,Distribution.Simple.Program.Ld,Distribution.Simple.Program.Run,Distribution.Simple.Program.Script,Distribution.Simple.Program.Strip,Distribution.Simple.Program.Types,Distribution.Simple.Register,Distribution.Simple.Setup,Distribution.Simple.SrcDist,Distribution.Simple.Test,Distribution.Simple.Test.ExeV10,Distribution.Simple.Test.LibV09,Distribution.Simple.Test.Log,Distribution.Simple.UHC,Distribution.Simple.UserHooks,Distribution.Simple.Utils,Distribution.System,Distribution.TestSuite,Distribution.Text,Distribution.Utils.NubList,Distribution.Verbosity,Distribution.Version,Language.Haskell.Extension,Main)
net.js:164
        throw errnoException(err, 'setBlocking');
              ^
Error: setBlocking ENOSYS
    at exports._errnoException (util.js:746:11)
    at new Socket (net.js:164:15)
    at createWritableStdioStream (node.js:463:18)
    at process.stderr (node.js:517:16)
    at Socket._destroy (net.js:480:25)
    at Socket.destroy (net.js:510:8)
    at maybeDestroy (net.js:434:12)
    at Pipe.onread (net.js:566:5)
Failed to install Cabal-1.22.2.0
cabal: Error: some packages failed to install:
Cabal-1.22.2.0 failed during the configure step. The exception was:
ExitFailure 1
ghcjs-boot: error running: /nix/store/9qhf40q41g4pbjf61y15xs8xgn1klal1-cabal-install-1.22.6.0/bin/cabal --config-file /nix/store/43zq0kz6vmjc58h7fyj37czkkkx8i96x-ghcjs-0.1.0/lib/ghcjs-0.1.0/cabalBootConfig install ./boot/cabal/Cabal --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /nix/store/43zq0kz6vmjc58h7fyj37czkkkx8i96x-ghcjs-0.1.0/bin/ghcjs --with-gcc /nix/store/ylj1q31a7x3pvcraxk60dyv9y4wmwcrc-gcc-wrapper-4.8.4/bin/cc --with-hc-pkg /nix/store/43zq0kz6vmjc58h7fyj37czkkkx8i96x-ghcjs-0.1.0/bin/ghcjs-pkg --prefix /nix/store/43zq0kz6vmjc58h7fyj37czkkkx8i96x-ghcjs-0.1.0 --libdir $prefix/lib/$compiler --libsubdir $pkgid --enable-documentation --haddock-html --haddock-hyperlink-source --enable-library-profiling --root-cmd /nix/store/43zq0kz6vmjc58h7fyj37czkkkx8i96x-ghcjs-0.1.0/lib/ghcjs-0.1.0/run.sh
exit status: 1
```

**Comment by k0001** [comment]
I'm trying to build again with `libuv-1.6.1` at the moment, I'll report afterwards if it was successful.

**Comment by k0001** [comment]
Yep. Updating `nodejs`'s dependency on `libuv` did the trick. Everything built just fine.  See pull-request https://github.com/NixOS/nixpkgs/issues/8787
