### ISSUE TITLE
gimp: No module named gtk / plugins do not work

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#87883]
**Describe the bug**
GIMP uses Python and GTK+ for e.g. plugins. But GIMP in the NixOS-GIMP-package cannot find the Python-gtk-module:

```$ gimp
Traceback (most recent call last):
  File "/nix/store/zwx9z7swgc2da2zvfvgr6v4mf6l14qml-gimp-2.10.14/lib/gimp/2.0/plug-ins/spyro_plus/.spyro_plus.py-wrapped", line 23, in <module>
    import gimpui
  File "/nix/store/6z3xqybj1530gvp6vcq9f4r6xlq1gzbc-gimp-with-plugins-2.10.14/lib/gimp/2.0/python/gimpui.py", line 33, in <module>
    import gtk, gobject, gimp, gimpcolor
ImportError: No module named gtk
...
```

GIMP itself starts, but e.g. some plugins cannot be used, e.g. `Filter -> Enhance -> Heal selection...`. When selecting this plugin, nothing happens, and the following error is shown in the console (again):
```
Traceback (most recent call last):
  File "/nix/store/6z3xqybj1530gvp6vcq9f4r6xlq1gzbc-gimp-with-plugins-2.10.14/lib/gimp/2.0/python/gimpfu.py", line 853, in _run
    res = _interact(proc_name, params[1:])
  File "/nix/store/6z3xqybj1530gvp6vcq9f4r6xlq1gzbc-gimp-with-plugins-2.10.14/lib/gimp/2.0/python/gimpfu.py", line 372, in _interact
    import gimpui
  File "/nix/store/6z3xqybj1530gvp6vcq9f4r6xlq1gzbc-gimp-with-plugins-2.10.14/lib/gimp/2.0/python/gimpui.py", line 33, in <module>
    import gtk, gobject, gimp, gimpcolor
ImportError: No module named gtk
```

**To Reproduce**
1. Install GIMP.
2. Start GIMP.
3. Look at the error-messages.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.39, NixOS, 20.03.1795.d6c1b566b77 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1795.d6c1b566b77"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by shirona** [comment]
Can confirm this still doesn't work. Of note is that installing `(python.withPackages (pkg: with pkg; [ pygtk ])` will allow `import gtk` when used from the `python2` REPL, but GIMP will still not recognize it.

Tagging @jtojnar since they are tagged as the maintainer.
