### ISSUE TITLE
nodePackages.tsun doesn't start up

### ISSUE THREAD

**Issue by leungbk** [NixOS/nixpkgs#88046]
**Describe the bug**
`nodePackages.tsun` does not start up.

**To Reproduce**
Install and run `tsun` in the terminal.

**Expected behavior**
A TypeScript REPL should start up.

**Additional context**
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/nix/store/hpihngi6zpkna60mv4s8mgjk20mfh2kh-node_tsun-0.5.0/lib/node_modules/tsun/bin/src/register.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

It's possible that the peer dependency on TypeScript is not handled properly.

**Notify maintainers**
@terlar 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.41, NixOS, 20.09pre226012.b47873026c7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(brian): `"nixos-20.09pre225673.8ba41a1e149"`
 - channels(root): `"nixos-20.09pre226012.b47873026c7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by terlar** [comment]
I am not sure how to fix this as it is not a dependency of the tsun package, it is defined as a peer dependency and this expression is generated from a simple JSON file. Of course it should be fixable with overriding and specifying typescript as a dependency, but I don't see any other packages that have these kind of overrides, thus I am not sure how to do it for node packages. I know some other generated packages have some overrides that adds missing dependencies/applies patches and things like that.

For now you should be able to include both packages (typescript and tsun) to get it to work.

**Comment by leungbk** [comment]
I've tried `nix-shell -p nodePackages.typescript nodePackages.tsun`, but
this yields the same error message as above, which I produced with my main
`configuration.nix`, where I have

``` nix
{
  systemPackages = with pkgs;
    [nodePackages.typescript nodePackages.tsun]
}
```

Is there a more idiomatic way of installing `tsun`, either locally or
globally?

**Comment by terlar** [comment]
Ah, it is a bit confusing, but seems you need nodejs as well, this works for me:
```
nix-shell -p nodejs nodePackages.typescript nodePackages.tsun --run tsun
```

**Comment by leungbk** [comment]
> Ah, it is a bit confusing, but seems you need nodejs as well, this works for me:
> 
> ```
> nix-shell -p nodejs nodePackages.typescript nodePackages.tsun --run tsun
> ```
> 
> It seems without nodejs it won't setup the `NODE_PATH` which is used for the modules to be found.

In `nix-shell` this works for me. But when I have all this in my `configuration.nix` and install a new generation, `tsun` fails with the same error as before.

I've tried having

``` nix
    tsun = super.tsun.override {
      nativeBuildInputs = [ pkgs.makeWrapper ];
      postInstall = ''
      wrapProgram "$out/bin/tsun" \
        --prefix PATH : ${stdenv.lib.makeBinPath [ super.typescript ]}
    '';
    };
```

in `pkgs/development/node-packages/default.nix` but then I get

``` sh
[brian@leungbk-nixos:~]$ tsun
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /nix/store/v4xsc5kmxgppp0y54p8jlm4m7ri4igcx-node_tsun-0.5.0/lib/node_modules/tsun/bin/src/register.js
- /nix/store/v4xsc5kmxgppp0y54p8jlm4m7ri4igcx-node_tsun-0.5.0/lib/node_modules/tsun/bin/tsun.js
- /nix/store/v4xsc5kmxgppp0y54p8jlm4m7ri4igcx-node_tsun-0.5.0/lib/node_modules/tsun/bin/tsun
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/nix/store/v4xsc5kmxgppp0y54p8jlm4m7ri4igcx-node_tsun-0.5.0/lib/node_modules/tsun/bin    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/v4xsc5kmxgppp0y54p8jlm4m7ri4igcx-node_tsun-0.5.0/lib/node_modules/tsun/bin/src/register.js',
    '/nix/store/v4xsc5kmxgppp0y54p8jlm4m7ri4igcx-node_tsun-0.5.0/lib/node_modules/tsun/bin/tsun.js',
    '/nix/store/v4xsc5kmxgppp0y54p8jlm4m7ri4igcx-node_tsun-0.5.0/lib/node_modules/tsun/bin/tsun'
  ]
}
```

after installing from `configuration.nix`.

**Comment by terlar** [comment]
It is the `NODE_PATH` that needs to be set, so this would work:
```
    tsun = nodePackages.tsun.overrideAttrs (oldAttrs: {
      buildInputs = oldAttrs.buildInputs ++ [ pkgs.makeWrapper ];
      postInstall = ''
        wrapProgram "$out/bin/tsun" \
        --prefix NODE_PATH : ${nodePackages.typescript}/lib/node_modules}
      '';
    });
```

I see now that there are other overrides in the `default-v10.nix` so I should update this package with this code there.

**Comment by terlar** [comment]
The correct fix might also be this:
```
diff --git a/pkgs/development/node-packages/generate.sh b/pkgs/development/node-packages/generate.sh
index 5f9936c5124..b8df968e2c5 100755
--- a/pkgs/development/node-packages/generate.sh
+++ b/pkgs/development/node-packages/generate.sh
@@ -6,4 +6,4 @@ node2nix=$(nix-build ../../.. --no-out-link -A nodePackages.node2nix)
 
 cd ${DIR}
 rm -f ./node-env.nix
-${node2nix}/bin/node2nix -i node-packages.json -o node-packages.nix -c composition.nix
+${node2nix}/bin/node2nix --include-peer-dependencies -i node-packages.json -o node-packages.nix -c composition.nix
```

As the reason why it is not included by the autogenerated expression is due to it being part of  peerDependencies which is not included by default in the node2nix command.
