### ISSUE TITLE
blueman is missing dependencies and configuration for file transfer

### ISSUE THREAD

**Issue by unode** [NixOS/nixpkgs#88108]
**Describe the bug**
After configuring bluetooth following [the bluetooth wiki page](https://nixos.wiki/wiki/Bluetooth), which sums up to:
```
services.blueman.enable = true;
hardware.bluetooth.enable = true;
```
trying to send or receive a file resulted in errors in many fronts.

The first error encountered:
```
blueman-applet[23382]: Traceback (most recent call last):
blueman-applet[23382]:   File "/nix/store/h151rxwwwj7yvdbv1yqzlhj8jzxi3n2z-blueman-2.1.2/bin/..blueman-sendto-wrapped-wrapped", line 157, in <module>
blueman-applet[23382]:     SendTo(args)
blueman-applet[23382]:   File "/nix/store/h151rxwwwj7yvdbv1yqzlhj8jzxi3n2z-blueman-2.1.2/bin/..blueman-sendto-wrapped-wrapped", line 86, in __init__
blueman-applet[23382]:     self.do_send()
blueman-applet[23382]:   File "/nix/store/h151rxwwwj7yvdbv1yqzlhj8jzxi3n2z-blueman-2.1.2/bin/..blueman-sendto-wrapped-wrapped", line 93, in do_send
blueman-applet[23382]:     sender = Sender(self.device, self.adapter_path, self.files)
blueman-applet[23382]:   File "/nix/store/h151rxwwwj7yvdbv1yqzlhj8jzxi3n2z-blueman-2.1.2/lib/python3.7/site-packages/blueman/main/Sendto.py", line 63, in __init__
blueman-applet[23382]:     self.manager = Manager()
blueman-applet[23382]:   File "/nix/store/h151rxwwwj7yvdbv1yqzlhj8jzxi3n2z-blueman-2.1.2/lib/python3.7/site-packages/blueman/bluez/obex/Manager.py", line 14, in __call__
blueman-applet[23382]:     cls._instance = super().__call__(*args, **kwargs)
blueman-applet[23382]:   File "/nix/store/h151rxwwwj7yvdbv1yqzlhj8jzxi3n2z-blueman-2.1.2/lib/python3.7/site-packages/blueman/bluez/obex/Manager.py", line 39, in __init__
blueman-applet[23382]:     self.__bus_name, '/', None, None, None)
blueman-applet[23382]: gi.repository.GLib.Error: g-dbus-error-quark: Error calling StartServiceByName for org.bluez.obex: Failed to execute program org.bluez.obex: No such file or directory (23)
```
is caused by not having `obexd` registered as a (user) service.

Running:
```
systemctl --user enable obex
systemctl --user start obex
```
fixed this. Not entirely sure if the latter unnecessary.

Then `obexd` reports:
```
obexd[24672]: CONNECT(0x0), <unknown>(0xff)
obexd[24672]: CONNECT(0x0), <unknown>(0x0)
obexd[24672]: PUT(0x2), <unknown>(0xff)
obexd[24672]: PUT(0x2), Forbidden(0x43)
obexd[24672]: DISCONNECT(0x1), <unknown>(0xff)
obexd[24672]: DISCONNECT(0x1), Success(0x20)
obexd[24672]: disconnected: Transport got disconnected
bluetoothd[939]: Unable to get io data for Object Push: getpeername: Transport endpoint is not connected (107)
```
the logs also show:
```
blueman-sendt[25788]: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
```
setting `services.gnome3.at-spi2-core.enable = true;` fixed this issue and made file transfers possible.

**Expected behavior**
File transfer should work *out-of-the-box* once bluetooth/blueman is enabled as a service.
`at-spi2-core` should be automatically configured when blueman is enabled.

**Notify maintainers**
@abbradar

**Metadata**
```
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.7, NixOS, 20.03.git.6748934307c (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre217261.a2e06fc3423"`
 - nixpkgs: `/var/nixpkgs-channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: blueman
# a list of nixos modules affected by the problem
module: bluetooh blueman
```

**Comment by bjornfor** [comment]
Possibly related: https://github.com/NixOS/nixpkgs/pull/63607

**Comment by unode** [comment]
#63607 is definitely related to this.

It seems like the solution is to have `blueman` depend on the extra functionality.
If the problem is the size of the packages like discussed in #63607 then I'd vouch for having a warning or extra note to the blueman service description that the other services need to be enabled as well.

**Comment by unode** [comment]
No longer relevant
