### ISSUE TITLE
broken coffee-script

### ISSUE THREAD

**Issue by flosse** [NixOS/nixpkgs#8836]
Installing coffee-script within `15.06pre65267.6ad8fab (Dingo)` doesn't work:

```
nix-env -iA nixos.pkgs.nodePackages.coffee-script
installing ‘nodejs-coffee-script-1.9.2’
these derivations will be built:
  /nix/store/igkydwjnrjib27cja2jj4xdxmv974mfl-nodejs-coffee-script-1.9.2.drv
building path(s) ‘/nix/store/sriizw8zl666nhzqbwrqhzaldpc1vfnq-nodejs-coffee-script-1.9.2’
unpacking sources
unpacking source archive /nix/store/xkin7czmvz5xk1ypk62gfm9z3xwcbl67-coffee-script-1.9.2.tgz
tar: Ignoring unknown extended header keyword 'NODETAR.depth'
tar: Ignoring unknown extended header keyword 'NODETAR.follow'
```
and so on ..

```
tar: Ignoring unknown extended header keyword 'NODETAR.blocks'
source root is package
patching sources
configuring
net.js:164
        throw errnoException(err, 'setBlocking');
              ^
Error: setBlocking ENOSYS
    at exports._errnoException (util.js:746:11)
    at new Socket (net.js:164:15)
    at createWritableStdioStream (node.js:463:18)
    at process.stderr (node.js:517:16)
    at Socket._destroy (net.js:480:25)
    at Socket.destroy (net.js:510:8)
    at maybeDestroy (net.js:434:12)
    at Pipe.onread (net.js:566:5)
builder for ‘/nix/store/igkydwjnrjib27cja2jj4xdxmv974mfl-nodejs-coffee-script-1.9.2.drv’ failed with exit code 1
error: build of ‘/nix/store/igkydwjnrjib27cja2jj4xdxmv974mfl-nodejs-coffee-script-1.9.2.drv’ failed
```

**Comment by flosse** [comment]
using the current master 855b3c48ab8d8129cddbcf250d6dfa586dbd16b7 with `nix-env -iA pkgs.nodePackages.coffee-script -f .` works fine.

**Comment by flosse** [comment]
fixed in current unstable channel :)
