### ISSUE TITLE
python3.withPackages has broken venv module

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#88711]
**Describe the bug**

When using `python3.withPackages`, the standard library `venv` module doesn’t work.

**To Reproduce**

```console
$ rm -rf /tmp/ve
$ nix-shell -p 'python3.withPackages (ps: [])' --run 'python3 -m venv /tmp/ve'
Error: Command '['/tmp/ve/bin/python3.7', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

**Additional context**

It works `--without-pip`, it works in `python3` without `withPackages`, and it works in `python38.withPackages`.

Rerunning the failing subcommand shows it apparently trying to overwrite `easy_install.py` in the store:

```console
$ nix-shell -p 'python3.withPackages (ps: [])' --run '/tmp/ve/bin/python3.7 -Im ensurepip --upgrade --default-pip'
Looking in links: /run/user/1000/tmpcqiiudf8
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
ERROR: Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/nix/store/2h620yac804z737kb98s5aqzmxqyxc8m-python3-3.7.7-env/lib/python3.7/site-packages/easy_install.py'
```

See #66366 for a related issue in `virtualenv`.

**Notify maintainers**

@FRidh 

**Metadata**
```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.13, NixOS, 20.09.git.3b336c18c2f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.09pre226148.0f5ce2fac0c, nixos-20.03-20.03.1950.48723f48ab9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [python3]
# a list of nixos modules affected by the problem
module: []
```

**Comment by FRidh** [comment]
Yes. It's a known issue, see the tests. We essentially need to change how we deal with prefixes. Now that we have tests we can better see how that would affect things.

**Comment by calbrecht** [comment]
I wonder if it was feasible to patch the pythons `sys` module with, say `nix_base_prefix` and `nix_base_exec_prefix` to be able to detect the *real* base on runtime, and set the `base_prefix` and `base_exex_prefix` to the env var `NIX_PYTHONPREFIX` if python was invoked through the wrapper script. 
That way we could pretend against venv and virtualenv that the wrapped one is the base python and then site-packages should work, i guess, but that needs to be confirmed.
Does that make sense?

**Comment by calbrecht** [comment]
One can observe what `virtualenv` thinks and how it decides by running
```
virtualenv python3.6 -vv --clear .virtualenv >&1 2>&1 | grep 'get interpreter info'
```
and then executing one of the resulting output lines like
```
# this is a valid base, as virtualenv detects
/nix/store/ihr1vd2n26y5kgilv5cp924fi5jp77ya-python3-3.6.10/bin/python3.6 /nix/store/yg66p78h4xdi8wmgpkm5rhq56p65sn1d-python3-3.7.7-env/lib/python3.7/site-packages/virtualenv/discovery/py_info.py

# this is an invalid base, as virtualenv detects
/nix/store/km8gd09ghl4i2ryjph1dh3r01xz78q4q-python3-3.6.10-env/bin/python3 /nix/store/yg66p78h4xdi8wmgpkm5rhq56p65sn1d-python3-3.7.7-env/lib/python3.7/site-packages/virtualenv/discovery/py_info.py
```

**Comment by FRidh** [comment]
@calbrecht https://github.com/NixOS/nixpkgs/issues/84568#issuecomment-633189546

This is annoying, we have now too many issues for the same problem.

**Comment by calbrecht** [comment]
@FRidh yes. Sorry. Though, in the case of #84568 there is `virtualenv` involved instead of `venv` if i get it correct. At least the patch in `virtualenv` is fixing this.

**Comment by FRidh** [comment]
The only functional difference in `ensurepip` and `venv` between 3.7.7 and 3.8.3 is [this commit](https://github.com/python/cpython/commit/d5a70c6b0355f247931f6be80b78a0ff1869c56f) and applying it does not fix the issue.

**Comment by GuillaumeDesforges** [comment]
This is still an issue on python37, but not python38.

**Comment by KenMacD** [comment]
To make `python -m venv` work for my own local non-cross-compile I added the following to my `shell.nix`:

    shellHook = ''
      unset _PYTHON_HOST_PLATFORM 
      unset _PYTHON_SYSCONFIGDATA_NAME 
    '';

To add context as to what the first command generates when run on it's own:
```
$ ./venv/bin/python3.7 -Im ensurepip --upgrade --default-pip
Traceback (most recent call last):
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/ensurepip/__init__.py", line 214, in _main
    default_pip=args.default_pip,
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/ensurepip/__init__.py", line 127, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/ensurepip/__init__.py", line 32, in _run_pip
    runpy.run_module("pip", run_name="__main__", alter_sys=True)
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/run/user/1000/tmpss5v1dzh/pip-20.1.1-py2.py3-none-any.whl/pip/__main__.py", line 23, in <module>
  File "/run/user/1000/tmpss5v1dzh/pip-20.1.1-py2.py3-none-any.whl/pip/_internal/cli/main.py", line 10, in <module>
  File "/run/user/1000/tmpss5v1dzh/pip-20.1.1-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 9, in <module>
  File "/run/user/1000/tmpss5v1dzh/pip-20.1.1-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 7, in <module>
  File "/run/user/1000/tmpss5v1dzh/pip-20.1.1-py2.py3-none-any.whl/pip/_internal/cli/cmdoptions.py", line 24, in <module>
  File "/run/user/1000/tmpss5v1dzh/pip-20.1.1-py2.py3-none-any.whl/pip/_internal/cli/progress_bars.py", line 12, in <module>
  File "/run/user/1000/tmpss5v1dzh/pip-20.1.1-py2.py3-none-any.whl/pip/_internal/utils/logging.py", line 18, in <module>
  File "/run/user/1000/tmpss5v1dzh/pip-20.1.1-py2.py3-none-any.whl/pip/_internal/utils/misc.py", line 31, in <module>
  File "/run/user/1000/tmpss5v1dzh/pip-20.1.1-py2.py3-none-any.whl/pip/_internal/locations.py", line 64, in <module>
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/sysconfig.py", line 513, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/sysconfig.py", line 503, in get_paths
    return _expand_vars(scheme, vars)
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/sysconfig.py", line 172, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/sysconfig.py", line 551, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/nix/store/47a4zzrphdhd3ayl992szy0h6abvdqkz-python3-3.7.10/lib/python3.7/sysconfig.py", line 422, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'
```

**Comment by azazel75** [comment]
thanks @KenMacD for the suggestion, it works

**Comment by GuillaumeDesforges** [comment]
Python 3.7 will be part of release 22.11 ( [link to matrix](https://matrix.to/#/!VjfUzaKsXokUdnQcvP:nixos.org/$8xeaYA2VCWJhh53bgtxTfNkF91suZR3ajpmpBvu5AFw?via=nixos.org&via=matrix.org&via=nixos.dev) ), but probably removed later.

I suggest we close this issue by default even if not solved if we reach a point where 3.7 is not part of nixpkgs anymore.

Though it would be preferable to have a fix before then.

**Comment by azazel75** [comment]
3.7 EOL is  2023-06-27, i don't see why it cannot be in a 2023 release as well

**Comment by domenkozar** [comment]
`python.buildEnv` works, but it installs the wrong interpreter:

```
nix-shell -p 'python3.buildEnv.override { }' --run 'which python && python3 -m venv /tmp/ve && cat /tmp/ve/pyvenv.cfg'
/nix/store/z15j31jsxnpsr33fxrx46xmczphaahdr-python3-3.10.12-env/bin/python
home = /nix/store/pkj7cgmz66assy7l18zc7j992npb41nx-python3-3.10.12/bin
include-system-site-packages = false
version = 3.10.12
```

**Comment by domenkozar** [comment]
```
nix-shell -p 'python3.withPackages (ps: [ps.requests])' --run 'which python && python3 -m venv /tmp/ve && cat /tmp/ve/pyvenv.cfg && /tmp/ve/bin/python -c "import requests"'
/nix/store/nj48w2rm3w7z69qy97lbm65xv7nycmdz-python3-3.10.12-env/bin/python
home = /nix/store/pkj7cgmz66assy7l18zc7j992npb41nx-python3-3.10.12/bin
include-system-site-packages = false
version = 3.10.12
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
```
