### ISSUE TITLE
nodePackages.swagger doesn't work

### ISSUE THREAD

**Issue by leungbk** [NixOS/nixpkgs#88741]
**Describe the bug**
`nodePackages.swagger` doesn't create an application

**To Reproduce**

```
[brian@leungbk-nixos:~]$ nix-shell -p nodePackages.swagger nodejs

[nix-shell:~]$ swagger project create hello-world
? Framework? connect

/nix/store/5r6ai2w3mjfz4a43yagh1vr2rzb4ayqw-node_swagger-0.7.5/lib/node_modules/swagger/node_modules/js-yaml/lib/js-yaml/dumper.js:756
      throw new YAMLException('unacceptable kind of an object to dump ' + type);
      ^
YAMLException: unacceptable kind of an object to dump [object Error]
    at writeNode (/nix/store/5r6ai2w3mjfz4a43yagh1vr2rzb4ayqw-node_swagger-0.7.5/lib/node_modules/swagger/node_modules/js-yaml/lib/js-yaml/dumper.js:756:13)
    at writeBlockSequence (/nix/store/5r6ai2w3mjfz4a43yagh1vr2rzb4ayqw-node_swagger-0.7.5/lib/node_modules/swagger/node_modules/js-yaml/lib/js-yaml/dumper.js:521:9)
    at writeNode (/nix/store/5r6ai2w3mjfz4a43yagh1vr2rzb4ayqw-node_swagger-0.7.5/lib/node_modules/swagger/node_modules/js-yaml/lib/js-yaml/dumper.js:740:9)
    at dump (/nix/store/5r6ai2w3mjfz4a43yagh1vr2rzb4ayqw-node_swagger-0.7.5/lib/node_modules/swagger/node_modules/js-yaml/lib/js-yaml/dumper.js:817:7)
    at Object.safeDump (/nix/store/5r6ai2w3mjfz4a43yagh1vr2rzb4ayqw-node_swagger-0.7.5/lib/node_modules/swagger/node_modules/js-yaml/lib/js-yaml/dumper.js:823:10)
    at print (/nix/store/5r6ai2w3mjfz4a43yagh1vr2rzb4ayqw-node_swagger-0.7.5/lib/node_modules/swagger/lib/util/cli.js:100:22)
    at printAndExit (/nix/store/5r6ai2w3mjfz4a43yagh1vr2rzb4ayqw-node_swagger-0.7.5/lib/node_modules/swagger/lib/util/cli.js:85:5)
    at cb (/nix/store/5r6ai2w3mjfz4a43yagh1vr2rzb4ayqw-node_swagger-0.7.5/lib/node_modules/swagger/lib/util/cli.js:155:5)
    at /nix/store/5r6ai2w3mjfz4a43yagh1vr2rzb4ayqw-node_swagger-0.7.5/lib/node_modules/swagger/lib/commands/project/project.js:105:25
    at /nix/store/5r6ai2w3mjfz4a43yagh1vr2rzb4ayqw-node_swagger-0.7.5/lib/node_modules/swagger/lib/commands/project/project.js:330:23
```

**Expected behavior**
Generate an app

**Notify maintainers**
@adisbladis

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.13-gnu, NixOS, 20.09pre226148.0f5ce2fac0c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(brian): `"nixos-20.09pre225673.8ba41a1e149"`
 - channels(root): `"nixos-20.09pre226148.0f5ce2fac0c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by calbrecht** [comment]
Oh well. This is a release from 5 years ago. Nothing big has happened since then, See also https://github.com/swagger-api/swagger-node/issues/592. I guess you would be better off searching something similar like [kogosoftwarellc/open-api](https://github.com/kogosoftwarellc/open-api), [Mermade/openapi-codegen](https://github.com/Mermade/openapi-codegen) or find something on [openapi.tools](https://openapi.tools)

**Comment by SuperSandro2000** [comment]
closing because of staleness
