### ISSUE TITLE
calibre: can't convert epub to pdf, wrong version of pqtwebengine

### ISSUE THREAD

**Issue by aindlq** [NixOS/nixpkgs#88800]
**Describe the bug**
Calibre can't convert epub to pdf because of wrong `pqtwebengine` version. Calibre requires at least v5.13.0 but currently v5.12.1 is in use

**To Reproduce**
Try to convert any epub to pdf with calibre.

**Expected behavior**
calibre converts epub to pdf without errors

**Additional context**
Similar issue in debian - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944875

Stack Trace:
```
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Traceback (most recent call last):
  File "/nix/store/c07x8vlwbbz7y672py09s69rzq10v3i0-calibre-4.8.0/bin/.calibre-parallel-wrapped", line 20, in <module>
    sys.exit(main())
  File "/nix/store/c07x8vlwbbz7y672py09s69rzq10v3i0-calibre-4.8.0/lib/calibre/calibre/utils/ipc/worker.py", line 209, in main
    result = func(*args, **kwargs)
  File "/nix/store/c07x8vlwbbz7y672py09s69rzq10v3i0-calibre-4.8.0/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
    override_input_metadata=True)
  File "/nix/store/c07x8vlwbbz7y672py09s69rzq10v3i0-calibre-4.8.0/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
    plumber.run()
  File "/nix/store/c07x8vlwbbz7y672py09s69rzq10v3i0-calibre-4.8.0/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1275, in run
    self.opts, self.log)
  File "/nix/store/c07x8vlwbbz7y672py09s69rzq10v3i0-calibre-4.8.0/lib/calibre/calibre/ebooks/conversion/plugins/pdf_output.py", line 188, in convert
    self.convert_text(oeb_book)
  File "/nix/store/c07x8vlwbbz7y672py09s69rzq10v3i0-calibre-4.8.0/lib/calibre/calibre/ebooks/conversion/plugins/pdf_output.py", line 255, in convert_text
    log=self.log, cover_data=self.cover_data, report_progress=self.report_progress
  File "/nix/store/c07x8vlwbbz7y672py09s69rzq10v3i0-calibre-4.8.0/lib/calibre/calibre/ebooks/pdf/html_writer.py", line 1159, in convert
    manager = RenderManager(opts, log, container.root)
  File "/nix/store/c07x8vlwbbz7y672py09s69rzq10v3i0-calibre-4.8.0/lib/calibre/calibre/ebooks/pdf/html_writer.py", line 260, in __init__
    ans.setUrlRequestInterceptor(self.interceptor)
AttributeError: 'QWebEngineProfile' object has no attribute 'setUrlRequestInterceptor'
```

**Notify maintainers**
@domenkozar @pSub @AndersonTorres 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.42, NixOS, 20.03.1950.48723f48ab9 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1950.48723f48ab9, unstable-20.03pre212208.8130f3c1c2b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: calibre
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
@aindlq Does https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=944875;filename=944875.patch;msg=20 fix the problem for you?

**Comment by tg-x** [comment]
yes, this patch fixes the issue

**Comment by rendeko** [comment]
I was experiencing this issue in 4.8. Updating to 4.23, which is available in the repo, fixed this issue.

**Comment by Demetrio92** [comment]
Known bug:
https://bugs.launchpad.net/ubuntu/+source/calibre/+bug/1884295

Workaround:
https://calibre-ebook.com/download_linux

or directly
```
sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
```

**Comment by AndersonTorres** [comment]
workaround: use third party installer? Why the third party installer would bypass a source code failure?

**Comment by immartian** [comment]
v5.x from the official download fixed it.
