### ISSUE TITLE
Buildbot is broken

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#8909]
Or rather, when I try to run `buildbot create-master` on a recent unstable (or even 14.12, I think), it complains as follows:

```bash
$ buildbot create-master
updating existing installation
creating /home/copumpkin/master.cfg.sample
populating public_html/
populating templates/
Traceback (most recent call last):
  File "/nix/store/4hag5dbmb9gq83r2cp6b9zhfn7gz9ls1-python2.7-Twisted-11.1.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1181, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/nix/store/4hag5dbmb9gq83r2cp6b9zhfn7gz9ls1-python2.7-Twisted-11.1.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1039, in _inlineCallbacks
    result = g.send(result)
  File "/nix/store/r4ydwphvpfqgxmgmjqj4w84akr4p7qjs-buildbot-0.8.10/lib/python2.7/site-packages/buildbot/scripts/create_master.py", line 152, in createMaster
    yield createDB(config)
  File "/nix/store/4hag5dbmb9gq83r2cp6b9zhfn7gz9ls1-python2.7-Twisted-11.1.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1181, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/nix/store/4hag5dbmb9gq83r2cp6b9zhfn7gz9ls1-python2.7-Twisted-11.1.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1039, in _inlineCallbacks
    result = g.send(result)
  File "/nix/store/r4ydwphvpfqgxmgmjqj4w84akr4p7qjs-buildbot-0.8.10/lib/python2.7/site-packages/buildbot/scripts/create_master.py", line 138, in createDB
    yield db.setup(check_version=False, verbose=not config['quiet'])
  File "/nix/store/r4ydwphvpfqgxmgmjqj4w84akr4p7qjs-buildbot-0.8.10/lib/python2.7/site-packages/buildbot/db/connector.py", line 101, in setup
    basedir=self.basedir)
  File "/nix/store/r4ydwphvpfqgxmgmjqj4w84akr4p7qjs-buildbot-0.8.10/lib/python2.7/site-packages/buildbot/db/enginestrategy.py", line 249, in create_engine
    return sa.create_engine(*args, **kwargs)
  File "/nix/store/8dvlxfbbyx9vxxhn5ff1rpcahmqbgcib-python2.7-SQLAlchemy-0.7.10/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 338, in create_engine
    return strategy.create(*args, **kwargs)
  File "/nix/store/r4ydwphvpfqgxmgmjqj4w84akr4p7qjs-buildbot-0.8.10/lib/python2.7/site-packages/buildbot/db/enginestrategy.py", line 203, in create
    self.check_sqlalchemy_version()
  File "/nix/store/r4ydwphvpfqgxmgmjqj4w84akr4p7qjs-buildbot-0.8.10/lib/python2.7/site-packages/buildbot/db/enginestrategy.py", line 198, in check_sqlalchemy_version
    "SQLAlchemy-Migrate version %d.%d.%d" % (version, mvt[0], mvt[1], mvt[2]))
exceptions.RuntimeError: SQLAlchemy version 0.7.11 is not supported by SQLAlchemy-Migrate version 0.6.1
```

So the package builds fine, but fails at runtime due to a b0rked version. I think the issue actually lies in `sqlalchemy_migrate`.

Given that this thing manifests itself as a runtime error, perhaps some sort of extra test is warranted going forward?

cc:
* @bjornfor for maintaining buildbot
* @domenkozar for general knowledge about python ecosystem
* @mlieberman85 for having a vested interest in the outcome

**Comment by bjornfor** [comment]
Apart from fixing the sqlalchemy version, we should fix the test (remove ```doCheck = false``` from buildbot expression).

**Comment by bjornfor** [comment]
Uhm, our sqlalchemy-0.7.10 seems to really contain .11 version, as seen in the above error message and here:

```
$ nix-build -A pythonPackages.sqlalchemy
/nix/store/kdd76a90v4wk3qc3y98k7xpbp2ji3k15-python2.7-SQLAlchemy-0.7.10

bfo@talisa ~/nixpkgs [git:master]
$ tree -L 4 /nix/store/kdd76a90v4wk3qc3y98k7xpbp2ji3k15-python2.7-SQLAlchemy-0.7.10
/nix/store/kdd76a90v4wk3qc3y98k7xpbp2ji3k15-python2.7-SQLAlchemy-0.7.10
├── lib
│   └── python2.7
│       └── site-packages
│           ├── python2.7-SQLAlchemy-0.7.10-nix-python-propagated-native-build-inputs.pth
│           ├── sqlalchemy
│           └── SQLAlchemy-0.7.11-py2.7.egg-info
└── nix-support
    └── propagated-native-build-inputs
```

**Comment by bjornfor** [comment]
Upgrading buildbot 0.8.10 -> 0.8.12 didn't change anything (might as well fix the issue before pushing that update).

**Comment by bjornfor** [comment]
Oh, @domenkozar is listed as maintainer for sqlalchemy-migrate [1]. Waiting for his input on version dependency between sqlalchemy and sqlalchemy-migrate. It might be a general issue (not related to buildbot at all).

[1] https://sqlalchemy-migrate.readthedocs.org/en/latest/

**Comment by domenkozar** [comment]
Sigh, wish they used alembic instead of sqlalchemy-migrate. We have to bump sqlalchemy as dependency, but most importantly start to use fixed point correctly in nix+python ecosystem

**Comment by copumpkin** [comment]
What's the plan for this? @domenkozar, it sounds like this is an example of a broader problem? Is there a quick fix that will get this working until we have the better solution in place? If you tell me what it is, I don't mind taking a go at implementing it.

**Comment by domenkozar** [comment]
@copumpkin short-term: override and bump sqlalchemy dependency for buildbot
long-term: use fixed point to provide better flexibility overriding packages in python ecosystem

**Comment by domenkozar** [comment]
This is now fixed in 11086

**Comment by copumpkin** [comment]
Thanks!

**Comment by copumpkin** [comment]
Looks like it's broken (still? again?)

**Comment by FRidh** [comment]
Anyone tried the RC? 
https://pypi.io/project/buildbot/

**Comment by nand0p** [comment]
https://github.com/NixOS/nixpkgs/pull/17699 fixes buildbot (0.8.12 -> 0.8.14) and init 0.9.0rc1

**Comment by FRidh** [comment]
0.9.0rc2 is merged in d86114cbd57de9e821c35cd2a1bfcf4bad2b0a5f

**Comment by FRidh** [comment]
can we close this?

**Comment by copumpkin** [comment]
Yup but I can't get to the github UI right now
