### ISSUE TITLE
pitivi crashes with gtk errors on startup

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#89691]
**Describe the bug**
pitivi crashes with gtk errors on startup.

**To Reproduce**
1. type `pitivi` in terminal and press enter
2. Read the error message:
```
Gdk-Message: 21:35:28.686: Unable to load fleur from the cursor theme
Traceback (most recent call last):
  File "/nix/store/lg69if6n2hlcym9gf7pdvq90r23ws65z-python3.7-matplotlib-3.2.1/lib/python3.7/site-packages/matplotlib/backends/backend_gtk3.py", line 41, in <module>
    cursors.MOVE:          Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/dhgbamhqpil80yav4sl62wvsp3g54ik2-pitivi-0.999/bin/..pitivi-wrapped-wrapped", line 169, in <module>
    _run_pitivi()
  File "/nix/store/dhgbamhqpil80yav4sl62wvsp3g54ik2-pitivi-0.999/bin/..pitivi-wrapped-wrapped", line 146, in _run_pitivi
    from pitivi import application
  File "/nix/store/dhgbamhqpil80yav4sl62wvsp3g54ik2-pitivi-0.999/lib/pitivi/python/pitivi/application.py", line 34, in <module>
    from pitivi.mainwindow import MainWindow
  File "/nix/store/dhgbamhqpil80yav4sl62wvsp3g54ik2-pitivi-0.999/lib/pitivi/python/pitivi/mainwindow.py", line 47, in <module>
    from pitivi.timeline.timeline import TimelineContainer
  File "/nix/store/dhgbamhqpil80yav4sl62wvsp3g54ik2-pitivi-0.999/lib/pitivi/python/pitivi/timeline/timeline.py", line 35, in <module>
    from pitivi.timeline.elements import Clip
  File "/nix/store/dhgbamhqpil80yav4sl62wvsp3g54ik2-pitivi-0.999/lib/pitivi/python/pitivi/timeline/elements.py", line 31, in <module>
    from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas
  File "/nix/store/lg69if6n2hlcym9gf7pdvq90r23ws65z-python3.7-matplotlib-3.2.1/lib/python3.7/site-packages/matplotlib/backends/backend_gtk3cairo.py", line 6, in <module>
    from . import backend_cairo, backend_gtk3
  File "/nix/store/lg69if6n2hlcym9gf7pdvq90r23ws65z-python3.7-matplotlib-3.2.1/lib/python3.7/site-packages/matplotlib/backends/backend_gtk3.py", line 50, in <module>
    raise ImportError(exc)
ImportError: constructor returned NULL

```

**Additional context**
This happens at least on wayland/sway.

**Notify maintainers**
@OmnipotentEntity as he did the last change to the packet and no maintainer is defined.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.15, NixOS, 20.09pre228204.467ce5a9f45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.09pre228204.467ce5a9f45"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
pkgs.pitivi
# a list of nixos modules affected by the problem
module:
```

**Comment by nh2** [comment]
I get a different error with nix on Ubuntu on `master` commit 02daf3f07688e89d41bbcafca3788edf648a6b31:

```
  File "/nix/store/nz4v5db5b93p0s3a7s5lrhnqyk403zn6-pitivi-0.999/bin/..pitivi-wrapped-wrapped", line 169, in <module>
    _run_pitivi()
  File "/nix/store/nz4v5db5b93p0s3a7s5lrhnqyk403zn6-pitivi-0.999/bin/..pitivi-wrapped-wrapped", line 146, in _run_pitivi
    from pitivi import application
  File "/nix/store/nz4v5db5b93p0s3a7s5lrhnqyk403zn6-pitivi-0.999/lib/pitivi/python/pitivi/application.py", line 34, in <module>
    from pitivi.mainwindow import MainWindow
  File "/nix/store/nz4v5db5b93p0s3a7s5lrhnqyk403zn6-pitivi-0.999/lib/pitivi/python/pitivi/mainwindow.py", line 42, in <module>
    from pitivi.medialibrary import AssetThumbnail
  File "/nix/store/nz4v5db5b93p0s3a7s5lrhnqyk403zn6-pitivi-0.999/lib/pitivi/python/pitivi/medialibrary.py", line 173, in <module>
    class AssetThumbnail(Loggable):
  File "/nix/store/nz4v5db5b93p0s3a7s5lrhnqyk403zn6-pitivi-0.999/lib/pitivi/python/pitivi/medialibrary.py", line 189, in AssetThumbnail
    EMBLEMS[status].append(GdkPixbuf.Pixbuf.new_from_file_at_size(
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/nix/store/nz4v5db5b93p0s3a7s5lrhnqyk403zn6-pitivi-0.999/share/pitivi/pixmaps/asset-proxied.svg” (3)
```

On `nixos-20.03` on Ubuntu it works.

**Comment by nh2** [comment]
> ```
> Couldn’t recognize the image file format for file “/nix/store/...-pitivi-0.999/share/pitivi/pixmaps/asset-proxied.svg” (3)
> ```

I found that this issue is https://github.com/NixOS/nixpkgs/issues/56943#issuecomment-471137692; cc @jtojnar, and setting `strictDeps = false;` works around that for Pitivi.

PR in #101398.
