### ISSUE TITLE
Request: package for limetext

### ISSUE THREAD

**Issue by MasseGuillaume** [NixOS/nixpkgs#9041]
> Lime Text is a powerful and elegant text editor primarily developed in Go that aims to be a Free and open-source software successor to Sublime Text.
> Lime has a few frontends (QML, command-line interface) that can be selectively used with the pluggable backend.

http://limetext.org/
- [ ] Update [limetext wiki page](https://github.com/limetext/lime/wiki/Building-on-Nix)

**Comment by Bevaz** [comment]
I have made package for limetext-termbox in my branch (Bevaz/nixpkgs@d848f3dbf9b2ef1fb8adae9069b0331870d6d155 & Bevaz/nixpkgs@b474a24f00714b9075b1a8c7e3942191ee0eb6ea)
It is possible to compile. But it crashes on start.
Here is the dump:
```
[09:31:42 UTC 2015/08/04] [EROR] (log.(*logger).Error:5) Unable to load colorscheme definition: open ../packages/themes/TextMate-Themes/Monokai.tmTheme: no such file or directory
[09:31:42 UTC 2015/08/04] [EROR] (log.(*logger).Error:5) Unable to use 256 color mode: termbox: TERM does not contain "256"
[09:31:42 UTC 2015/08/04] [DEBG] (log.(*logger).Debug:4) {{0 0} map[log:{3 12077025} clip:{1 19477} show:{1 47035}]}
[09:31:42 UTC 2015/08/04] [CRIT] (log.(*logger).Critical:3) runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x418d72]

goroutine 1 [running, locked to thread]:
main.func·014()
	/tmp/nix-build-go1.4-limetext-termbox-30af493.drv-0/go/src/limetext-termbox/main/main.go:812 +0xd9
main.setSchemeSettings()
	/tmp/nix-build-go1.4-limetext-termbox-30af493.drv-0/go/src/limetext-termbox/main/main.go:764 +0x272
main.createFrontend(0x0)
	/tmp/nix-build-go1.4-limetext-termbox-30af493.drv-0/go/src/limetext-termbox/main/main.go:172 +0x466
main.main()
	/tmp/nix-build-go1.4-limetext-termbox-30af493.drv-0/go/src/limetext-termbox/main/main.go:816 +0xec

goroutine 5 [chan receive]:
github.com/ccpaging/log4go.(*ConsoleLogWriter).run(0xc2080422a0, 0x7f6b063debd8, 0xc208036008)
	/tmp/nix-build-go1.4-log4go-cb4cc51.drv-0/go/src/github.com/ccpaging/log4go/termlog.go:77 +0x7f
created by github.com/ccpaging/log4go.NewConsoleLogWriter
	/tmp/nix-build-go1.4-log4go-cb4cc51.drv-0/go/src/github.com/ccpaging/log4go/termlog.go:56 +0x13f

goroutine 6 [syscall]:
os/signal.loop()
	/nix/store/spzkn897hriimk3imbnlksw3s3m3fvhy-go-1.4.2/share/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/nix/store/spzkn897hriimk3imbnlksw3s3m3fvhy-go-1.4.2/share/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
github.com/ccpaging/log4go.(*ConsoleLogWriter).run(0xc208042690, 0x7f6b063debd8, 0xc208036008)
	/tmp/nix-build-go1.4-log4go-cb4cc51.drv-0/go/src/github.com/ccpaging/log4go/termlog.go:77 +0x7f
created by github.com/ccpaging/log4go.NewConsoleLogWriter
	/tmp/nix-build-go1.4-log4go-cb4cc51.drv-0/go/src/github.com/ccpaging/log4go/termlog.go:56 +0x13f

goroutine 8 [chan receive]:
github.com/limetext/text.(*SerializedBuffer).worker(0xc208094008)
	/tmp/nix-build-go1.4-text-d6b8f8c.drv-0/go/src/github.com/limetext/text/serialized_buffer.go:40 +0x61
created by github.com/limetext/text.(*SerializedBuffer).init
	/tmp/nix-build-go1.4-text-d6b8f8c.drv-0/go/src/github.com/limetext/text/serialized_buffer.go:26 +0xd9

goroutine 9 [syscall]:
syscall.Syscall6(0xe8, 0x4, 0xc2080e7cb4, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/nix/store/spzkn897hriimk3imbnlksw3s3m3fvhy-go-1.4.2/share/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.EpollWait(0x4, 0xc2080e7cb4, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/nix/store/spzkn897hriimk3imbnlksw3s3m3fvhy-go-1.4.2/share/go/src/syscall/zsyscall_linux_amd64.go:376 +0x93
gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0xc20801e260, 0x0, 0x0, 0x0)
	/tmp/nix-build-go1.4-fsnotify.v1-v1.2.0.drv-0/go/src/gopkg.in/fsnotify.v1/inotify_poller.go:85 +0xc7
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc208038230)
	/tmp/nix-build-go1.4-fsnotify.v1-v1.2.0.drv-0/go/src/gopkg.in/fsnotify.v1/inotify.go:179 +0x16f
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/tmp/nix-build-go1.4-fsnotify.v1-v1.2.0.drv-0/go/src/gopkg.in/fsnotify.v1/inotify.go:58 +0x32b

goroutine 10 [chan receive]:
github.com/limetext/lime-backend/lib/log.func·001()
	/tmp/nix-build-go1.4-lime-backend-4d984c5.drv-0/go/src/github.com/limetext/lime-backend/lib/log/logwriter.go:37 +0x69
created by github.com/limetext/lime-backend/lib/log.NewLogWriter
	/tmp/nix-build-go1.4-lime-backend-4d984c5.drv-0/go/src/github.com/limetext/lime-backend/lib/log/logwriter.go:40 +0x16b

goroutine 11 [chan receive]:
github.com/limetext/lime-backend/lib.(*Editor).inputthread(0xc208001560)
	/tmp/nix-build-go1.4-lime-backend-4d984c5.drv-0/go/src/github.com/limetext/lime-backend/lib/editor.go:366 +0x10f
created by github.com/limetext/lime-backend/lib.GetEditor
	/tmp/nix-build-go1.4-lime-backend-4d984c5.drv-0/go/src/github.com/limetext/lime-backend/lib/editor.go:142 +0x75a

goroutine 12 [select]:
github.com/limetext/lime-backend/lib/watch.(*Watcher).Observe(0xc208038280)
	/tmp/nix-build-go1.4-lime-backend-4d984c5.drv-0/go/src/github.com/limetext/lime-backend/lib/watch/watch.go:201 +0x333
created by github.com/limetext/lime-backend/lib.GetEditor
	/tmp/nix-build-go1.4-lime-backend-4d984c5.drv-0/go/src/github.com/limetext/lime-backend/lib/editor.go:143 +0x77a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/nix/store/spzkn897hriimk3imbnlksw3s3m3fvhy-go-1.4.2/share/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 13 [select]:
github.com/ccpaging/log4go.(*FileLogWriter).run(0xc208086000)
	/tmp/nix-build-go1.4-log4go-cb4cc51.drv-0/go/src/github.com/ccpaging/log4go/filelog.go:106 +0xa42
created by github.com/ccpaging/log4go.NewFileLogWriter
	/tmp/nix-build-go1.4-log4go-cb4cc51.drv-0/go/src/github.com/ccpaging/log4go/filelog.go:92 +0x3de

goroutine 15 [chan receive]:
github.com/limetext/lime-backend/lib.(*View).parsethread(0xc208104000)
	/tmp/nix-build-go1.4-lime-backend-4d984c5.drv-0/go/src/github.com/limetext/lime-backend/lib/view.go:216 +0x158
created by github.com/limetext/lime-backend/lib.newView
	/tmp/nix-build-go1.4-lime-backend-4d984c5.drv-0/go/src/github.com/limetext/lime-backend/lib/view.go:75 +0x23d

goroutine 16 [chan receive]:
github.com/limetext/text.(*SerializedBuffer).worker(0xc208112088)
	/tmp/nix-build-go1.4-text-d6b8f8c.drv-0/go/src/github.com/limetext/text/serialized_buffer.go:40 +0x61
created by github.com/limetext/text.(*SerializedBuffer).init
	/tmp/nix-build-go1.4-text-d6b8f8c.drv-0/go/src/github.com/limetext/text/serialized_buffer.go:26 +0xd9
```

**Comment by MasseGuillaume** [comment]
wip here: https://github.com/MasseGuillaume/nixpkgs/commit/3123399c651991f40184ed6760e5e4563af9fd9b

**Comment by rasendubi** [comment]
(triage) @MasseGuillaume, @Bevaz, have you succeeded in building/running limetext?

**Comment by MasseGuillaume** [comment]
@rasendubi limetext dev said the editor was not quite ready the last time I asked.

**Comment by FlorentBecker** [comment]
we should probably close this until then.

**Comment by MasseGuillaume** [comment]
Yep this projects look dead. So sad.

https://github.com/limetext/lime-qml/graphs/contributors
https://github.com/limetext/lime-termbox/graphs/contributors
https://github.com/limetext/lime-html/graphs/contributors
