### ISSUE TITLE
Unable to build simpy 

### ISSUE THREAD

**Issue by dmrauh** [NixOS/nixpkgs#90494]
**Describe the bug**

Building the Python package simpy fails with the following errors:
```
installing 'python3.7-simpy-3.0.13'
these derivations will be built:
  /nix/store/jnfx8gl20jkipbijd44cawjq48k2fyn6-python3.7-simpy-3.0.13.drv
building '/nix/store/jnfx8gl20jkipbijd44cawjq48k2fyn6-python3.7-simpy-3.0.13.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing setuptools-check-hook
Using setuptoolsCheckPhase
unpacking sources
unpacking source archive /nix/store/jzfq1zankfkrmal67j2kq7ymhflzkbkv-simpy-3.0.13.tar.gz
source root is simpy-3.0.13
setting SOURCE_DATE_EPOCH to timestamp 1586095894 of file simpy-3.0.13/src/simpy.egg-info/top_level.txt
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff6b39710>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff6b4c410>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5ee7a90>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5ebd510>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5ebd350>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
ERROR: No matching distribution found for setuptools_scm
Traceback (most recent call last):
  File "/nix/store/ih24yd9fl813ca6h72f9ly0snsvh72zn-python3.7-setuptools-46.1.3/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmpmx915qy9', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 40, in <module>
    'Topic :: Scientific/Engineering',
  File "/nix/store/ih24yd9fl813ca6h72f9ly0snsvh72zn-python3.7-setuptools-46.1.3/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
    _install_setup_requires(attrs)
  File "/nix/store/ih24yd9fl813ca6h72f9ly0snsvh72zn-python3.7-setuptools-46.1.3/lib/python3.7/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/nix/store/ih24yd9fl813ca6h72f9ly0snsvh72zn-python3.7-setuptools-46.1.3/lib/python3.7/site-packages/setuptools/dist.py", line 698, in fetch_build_eggs
    replace_conflicting=True,
  File "/nix/store/ih24yd9fl813ca6h72f9ly0snsvh72zn-python3.7-setuptools-46.1.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    replace_conflicting=replace_conflicting
  File "/nix/store/ih24yd9fl813ca6h72f9ly0snsvh72zn-python3.7-setuptools-46.1.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/nix/store/ih24yd9fl813ca6h72f9ly0snsvh72zn-python3.7-setuptools-46.1.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/nix/store/ih24yd9fl813ca6h72f9ly0snsvh72zn-python3.7-setuptools-46.1.3/lib/python3.7/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/nix/store/ih24yd9fl813ca6h72f9ly0snsvh72zn-python3.7-setuptools-46.1.3/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmpmx915qy9', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
builder for '/nix/store/jnfx8gl20jkipbijd44cawjq48k2fyn6-python3.7-simpy-3.0.13.drv' failed with exit code 1
error: build of '/nix/store/jnfx8gl20jkipbijd44cawjq48k2fyn6-python3.7-simpy-3.0.13.drv' failed
```
**To Reproduce**

1. Pin yourself to `nixos-unstable` (rev: `"029a5de08390bb03c3f44230b064fd1850c6658a"`, latest available at the moment.)
2. Issue the command: `nix-env -iA nixos.python3Packages.simpy`

**Notify maintainers**

@shlevy 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.16, NixOS, 20.09pre228622.029a5de0839 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre228622.029a5de0839"`
 - channels(dmrauh): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute: python3Packages.simpy
```

**Comment by dmrauh** [comment]
Adding `setuptools_scm` to `nativeBuildInputs` and `pytestCheckHook` to `checkInputs` fixes the issue. This is a bit weird, as i'm not sure why the derivation worked before, without these dependencies.

**Comment by dmrauh** [comment]
Simpy is now building but importing and using it in Python yields another error: `ModuleNotFoundError: No module named 'pkg_resources'`, which seems to stem from a „broken“ `setuptools` package as far as my research led me. So maybe something with the `setuptools_scm` package may not be right?

**Comment by dmrauh** [comment]
As stated under: https://nixos.wiki/wiki/Packaging/Python adding `propagatedBuildInputs = [ setuptools ];` fixes the `ModuleNotFoundError`. So now simpy is building and working as expected!
