### ISSUE TITLE
Tests for beets fail

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#91131]
**Describe the bug**
The tests are failing.

**To Reproduce**
1. nix-build -A beet

**Expected behavior**

**Screenshots**

**Additional context**

```
======================================================================
ERROR: test_config_include_paths_false (test.test_web.WebPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test/test_web.py", line 45, in test_config_include_paths_false
    response = self.client.get('/item/1')
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 396, in push
    self.match_request()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1873, in match
    rv = rule.match(path, method)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 902, in match
    new_path = "|".join(self.build(result, False))
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1040, in build
    return self._build(**values)
  File "<werkzeug routing>", line 1, in <builder:'/item/<idlist:ids>'>
  File "/build/source/beetsplug/web/__init__.py", line 172, in to_url
    return ','.join(value)
TypeError: sequence item 0: expected str instance, int found
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: item_removed
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_config_include_paths_true (test.test_web.WebPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test/test_web.py", line 37, in test_config_include_paths_true
    response = self.client.get('/item/1')
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 396, in push
    self.match_request()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1873, in match
    rv = rule.match(path, method)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 902, in match
    new_path = "|".join(self.build(result, False))
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1040, in build
    return self._build(**values)
  File "<werkzeug routing>", line 1, in <builder:'/item/<idlist:ids>'>
  File "/build/source/beetsplug/web/__init__.py", line 172, in to_url
    return ','.join(value)
TypeError: sequence item 0: expected str instance, int found
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: item_removed
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_get_multiple_albums_by_id (test.test_web.WebPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test/test_web.py", line 129, in test_get_multiple_albums_by_id
    response = self.client.get('/album/1,2')
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 396, in push
    self.match_request()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1873, in match
    rv = rule.match(path, method)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 902, in match
    new_path = "|".join(self.build(result, False))
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1040, in build
    return self._build(**values)
  File "<werkzeug routing>", line 1, in <builder:'/album/<idlist:ids>'>
  File "/build/source/beetsplug/web/__init__.py", line 172, in to_url
    return ','.join(value)
TypeError: sequence item 0: expected str instance, int found
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: item_removed
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_get_multiple_items_by_id (test.test_web.WebPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test/test_web.py", line 67, in test_get_multiple_items_by_id
    response = self.client.get('/item/1,2')
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 396, in push
    self.match_request()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1873, in match
    rv = rule.match(path, method)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 902, in match
    new_path = "|".join(self.build(result, False))
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1040, in build
    return self._build(**values)
  File "<werkzeug routing>", line 1, in <builder:'/item/<idlist:ids>'>
  File "/build/source/beetsplug/web/__init__.py", line 172, in to_url
    return ','.join(value)
TypeError: sequence item 0: expected str instance, int found
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: item_removed
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_get_single_album_by_id (test.test_web.WebPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test/test_web.py", line 121, in test_get_single_album_by_id
    response = self.client.get('/album/2')
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 396, in push
    self.match_request()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1873, in match
    rv = rule.match(path, method)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 902, in match
    new_path = "|".join(self.build(result, False))
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1040, in build
    return self._build(**values)
  File "<werkzeug routing>", line 1, in <builder:'/album/<idlist:ids>'>
  File "/build/source/beetsplug/web/__init__.py", line 172, in to_url
    return ','.join(value)
TypeError: sequence item 0: expected str instance, int found
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: item_removed
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_get_single_item_by_id (test.test_web.WebPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test/test_web.py", line 59, in test_get_single_item_by_id
    response = self.client.get('/item/1')
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 396, in push
    self.match_request()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1873, in match
    rv = rule.match(path, method)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 902, in match
    new_path = "|".join(self.build(result, False))
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1040, in build
    return self._build(**values)
  File "<werkzeug routing>", line 1, in <builder:'/item/<idlist:ids>'>
  File "/build/source/beetsplug/web/__init__.py", line 172, in to_url
    return ','.join(value)
TypeError: sequence item 0: expected str instance, int found
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: item_removed
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_get_single_item_not_found (test.test_web.WebPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test/test_web.py", line 76, in test_get_single_item_not_found
    response = self.client.get('/item/3')
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 396, in push
    self.match_request()
  File "/nix/store/rcync2hhpzaw3zjg9lzx3pymhgxsrfbk-python3.8-Flask-1.1.2/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1873, in match
    rv = rule.match(path, method)
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 902, in match
    new_path = "|".join(self.build(result, False))
  File "/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1040, in build
    return self._build(**values)
  File "<werkzeug routing>", line 1, in <builder:'/item/<idlist:ids>'>
  File "/build/source/beetsplug/web/__init__.py", line 172, in to_url
    return ','.join(value)
TypeError: sequence item 0: expected str instance, int found
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: item_removed
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1901 tests in 71.021s

FAILED (SKIP=29, errors=7)
builder for '/nix/store/pqzxdk256178prmnzzj5hfvrihbzm7fi-beets-1.4.9.drv' failed with exit code 1
```

**Notify maintainers**

@aszlig @domenkozar @pjones 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

5460cc93c4e98091c4a24b915a64e8433a3efefe

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: beet
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
potential patch https://github.com/beetbox/beets/commit/d43d54e21cde97f57f19486925ab56b419254cc8

**Comment by mweinelt** [comment]
Indeed that resolves the broken tests. Unfortunately they didn't release since May 2019, so I guess we're gonna ship that patch.
