### ISSUE TITLE
google-cloud-sdk breaks with GCE support

### ISSUE THREAD

**Issue by purcell** [NixOS/nixpkgs#91456]
**Describe the bug**

The `google-cloud-sdk` package can be built with a `use-gce` option, and such a version of it is exposed as `google-cloud-sdk-gce` in nixpkgs. However, when run on a (NixOS) machine in GCE, the `google-compute-engine` support breaks:

```
$ nix-shell -p google-cloud-sdk-gce
[nix-shell:~somedir]$ gsutil
Traceback (most recent call last):
  File "/nix/store/d6x4kl6a3darjlwybh35m43f2gjpnis3-google-cloud-sdk-297.0.1/google-cloud-sdk/platform/gsutil/gsutil", line 21, in <module>
    gsutil.RunMain()
  File "/nix/store/d6x4kl6a3darjlwybh35m43f2gjpnis3-google-cloud-sdk-297.0.1/google-cloud-sdk/platform/gsutil/gsutil.py", line 122, in RunMain
    import gslib.__main__
  File "/nix/store/d6x4kl6a3darjlwybh35m43f2gjpnis3-google-cloud-sdk-297.0.1/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 53, in <module>
    import boto
  File "/nix/store/d6x4kl6a3darjlwybh35m43f2gjpnis3-google-cloud-sdk-297.0.1/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/nix/store/d6x4kl6a3darjlwybh35m43f2gjpnis3-google-cloud-sdk-297.0.1/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/nix/store/d6x4kl6a3darjlwybh35m43f2gjpnis3-google-cloud-sdk-297.0.1/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/nix/store/h215sh6f5hs752pbn0nq357f3wkz9vn9-google-compute-engine-20190124/lib/python2.7/site-packages/google_compute_engine/boto/boto_config.py", line 29, in <module>
    from google_compute_engine import config_manager
ImportError: No module named google_compute_engine
```

Tested with current nixpkgs, but I suspect this has been broken for a little while.

**To Reproduce**
1. Access a GCE machine (this is the inconvenient part)
2. `nix-shell -p google-cloud-sdk-gce`
3. Run `gsutil` in the nix shell

**Expected behavior**

Would expect no error from `gsutil`, and ability to access google storage with it using GCE-based auth.

**Additional context**

If one overrides the `python` to `python3` in `google-cloud-sdk-gce`, then the resulting backtrace gets even more interesting, since it ends like this:
```
  File "/nix/store/jli50q24fvik6pfsnjs1jd90g3dy4p6y-python3-3.8.3/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/nix/store/jli50q24fvik6pfsnjs1jd90g3dy4p6y-python3-3.8.3/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "/nix/store/h215sh6f5hs752pbn0nq357f3wkz9vn9-google-compute-engine-20190124/lib/python2.7/site-packages/google_compute_engine/boto/boto_config.py", line 29, in <module>
    from google_compute_engine import config_manager
ModuleNotFoundError: No module named 'google_compute_engine'
```
Note the mix of Python versions involved.

I *suspect* that the `google-compute-engine` and `google-cloud-sdk` packages have somewhat diverged in compatibility, or that the `python` involved in those two and `boto` have to be lined up to be consistent, but I haven't dug deeply into either of those possibilities.

**Notify maintainers**

CC @andir, who I know has worked on some of this, and is working on the same project as me.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.118, NixOS, 20.03.2015.e7752db2fb6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.03.2015.e7752db2fb6"`
 - channels(steve): `"nixpkgs-20.09pre228165.00df2371122"`
 - nixpkgs: `/home/steve/.nix-defexpr/channels/nixpkgs

(But have tested in shell with latest nixpkgs pinned.)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
 - google-cloud-sdk
 - google-cloud-sdk-gce
 - google-compute-engine
# a list of nixos modules affected by the problem
module:
```

**Comment by purcell** [comment]
Likely defunct, and not currently an issue for me, so closing.
