### ISSUE TITLE
Error installing python2.7-pandas-0.16.2 package

### ISSUE THREAD

**Issue by sanbor** [NixOS/nixpkgs#9207]
Can't install pandas in OSX.

```
test_dict_deprecate_kwarg (pandas.tests.test_util.TestDecorators) ... ok
test_missing_deprecate_kwarg (pandas.tests.test_util.TestDecorators) ... ok
test_locale (pandas.tests.test_util.TestTesting) ... ERROR

======================================================================
ERROR: test_locale (pandas.tests.test_util.TestTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/folders/t9/l93xftz95gx9y9gq8zvq9wc00000gn/T/nix-build-python2.7-pandas-0.16.2.drv-0/pandas-0.16.2/pandas/tests/test_util.py", line 89, in test_locale
    self.assertTrue(len(locales) >= 1)
TypeError: object of type 'NoneType' has no len()

----------------------------------------------------------------------
Ran 7018 tests in 505.474s

FAILED (SKIP=341, errors=1)
builder for ‘/nix/store/gcfcm6dr4zrng9f8v778z1z7im8w78cx-python2.7-pandas-0.16.2.drv’ failed with exit code 1
error: build of ‘/nix/store/gcfcm6dr4zrng9f8v778z1z7im8w78cx-python2.7-pandas-0.16.2.drv’ failed
```

**Comment by FRidh** [comment]
What's the output of `locale -a`?

It tries to determine the available locales. If `locale -a` fails, it will return `None`, failing the test.
https://github.com/pydata/pandas/blob/v0.16.2/pandas/util/testing.py#L279


I don't think it is, but it might be related:
https://github.com/pydata/pandas/issues/10471

New location of the specific test upstream is:
https://github.com/pydata/pandas/blob/master/pandas/tests/test_testing.py
It doesn't appear to be changed. Couldn't find anything else about this issue either so I guess that either they don't know about the issue, or it's related to our package/Nix.

**Comment by sanbor** [comment]
The output of `locale -a` is
```
af_ZA
af_ZA.ISO8859-1
af_ZA.ISO8859-15
af_ZA.UTF-8
am_ET
am_ET.UTF-8
be_BY
be_BY.CP1131
be_BY.CP1251
be_BY.ISO8859-5
be_BY.UTF-8
bg_BG
bg_BG.CP1251
bg_BG.UTF-8
ca_ES
ca_ES.ISO8859-1
ca_ES.ISO8859-15
ca_ES.UTF-8
cs_CZ
cs_CZ.ISO8859-2
cs_CZ.UTF-8
da_DK
da_DK.ISO8859-1
da_DK.ISO8859-15
da_DK.UTF-8
de_AT
de_AT.ISO8859-1
de_AT.ISO8859-15
de_AT.UTF-8
de_CH
de_CH.ISO8859-1
de_CH.ISO8859-15
de_CH.UTF-8
de_DE
de_DE.ISO8859-1
de_DE.ISO8859-15
de_DE.UTF-8
el_GR
el_GR.ISO8859-7
el_GR.UTF-8
en_AU
en_AU.ISO8859-1
en_AU.ISO8859-15
en_AU.US-ASCII
en_AU.UTF-8
en_CA
en_CA.ISO8859-1
en_CA.ISO8859-15
en_CA.US-ASCII
en_CA.UTF-8
en_GB
en_GB.ISO8859-1
en_GB.ISO8859-15
en_GB.US-ASCII
en_GB.UTF-8
en_IE
en_IE.UTF-8
en_NZ
en_NZ.ISO8859-1
en_NZ.ISO8859-15
en_NZ.US-ASCII
en_NZ.UTF-8
en_US
en_US.ISO8859-1
en_US.ISO8859-15
en_US.US-ASCII
en_US.UTF-8
es_ES
es_ES.ISO8859-1
es_ES.ISO8859-15
es_ES.UTF-8
et_EE
et_EE.ISO8859-15
et_EE.UTF-8
eu_ES
eu_ES.ISO8859-1
eu_ES.ISO8859-15
eu_ES.UTF-8
fi_FI
fi_FI.ISO8859-1
fi_FI.ISO8859-15
fi_FI.UTF-8
fr_BE
fr_BE.ISO8859-1
fr_BE.ISO8859-15
fr_BE.UTF-8
fr_CA
fr_CA.ISO8859-1
fr_CA.ISO8859-15
fr_CA.UTF-8
fr_CH
fr_CH.ISO8859-1
fr_CH.ISO8859-15
fr_CH.UTF-8
fr_FR
fr_FR.ISO8859-1
fr_FR.ISO8859-15
fr_FR.UTF-8
he_IL
he_IL.UTF-8
hi_IN.ISCII-DEV
hr_HR
hr_HR.ISO8859-2
hr_HR.UTF-8
hu_HU
hu_HU.ISO8859-2
hu_HU.UTF-8
hy_AM
hy_AM.ARMSCII-8
hy_AM.UTF-8
is_IS
is_IS.ISO8859-1
is_IS.ISO8859-15
is_IS.UTF-8
it_CH
it_CH.ISO8859-1
it_CH.ISO8859-15
it_CH.UTF-8
it_IT
it_IT.ISO8859-1
it_IT.ISO8859-15
it_IT.UTF-8
ja_JP
ja_JP.eucJP
ja_JP.SJIS
ja_JP.UTF-8
kk_KZ
kk_KZ.PT154
kk_KZ.UTF-8
ko_KR
ko_KR.CP949
ko_KR.eucKR
ko_KR.UTF-8
lt_LT
lt_LT.ISO8859-13
lt_LT.ISO8859-4
lt_LT.UTF-8
nl_BE
nl_BE.ISO8859-1
nl_BE.ISO8859-15
nl_BE.UTF-8
nl_NL
nl_NL.ISO8859-1
nl_NL.ISO8859-15
nl_NL.UTF-8
no_NO
no_NO.ISO8859-1
no_NO.ISO8859-15
no_NO.UTF-8
pl_PL
pl_PL.ISO8859-2
pl_PL.UTF-8
pt_BR
pt_BR.ISO8859-1
pt_BR.UTF-8
pt_PT
pt_PT.ISO8859-1
pt_PT.ISO8859-15
pt_PT.UTF-8
ro_RO
ro_RO.ISO8859-2
ro_RO.UTF-8
ru_RU
ru_RU.CP1251
ru_RU.CP866
ru_RU.ISO8859-5
ru_RU.KOI8-R
ru_RU.UTF-8
sk_SK
sk_SK.ISO8859-2
sk_SK.UTF-8
sl_SI
sl_SI.ISO8859-2
sl_SI.UTF-8
sr_YU
sr_YU.ISO8859-2
sr_YU.ISO8859-5
sr_YU.UTF-8
sv_SE
sv_SE.ISO8859-1
sv_SE.ISO8859-15
sv_SE.UTF-8
tr_TR
tr_TR.ISO8859-9
tr_TR.UTF-8
uk_UA
uk_UA.ISO8859-5
uk_UA.KOI8-U
uk_UA.UTF-8
zh_CN
zh_CN.eucCN
zh_CN.GB18030
zh_CN.GB2312
zh_CN.GBK
zh_CN.UTF-8
zh_HK
zh_HK.Big5HKSCS
zh_HK.UTF-8
zh_TW
zh_TW.Big5
zh_TW.UTF-8
C
POSIX
```

**Comment by domenkozar** [comment]
@datakurre can you test this?

**Comment by datakurre** [comment]
@domenkozar For me it failed on a different test
```
======================================================================
ERROR: pandas.computation.tests.test_eval.TestAlignment.test_complex_series_frame_alignment('python',
 'python')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/cpp7m9jgqjcjcvrkc3fdn17zjn8mapv1-python2.7-nose-1.3.4/lib/python2.7/site-packages/
nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.16.2.dr
v-0/pandas-0.16.2/pandas/computation/tests/test_eval.py", line 932, in check_complex_series_frame_ali
gnment
    expected = expected2 + df
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.16.2.dr
v-0/pandas-0.16.2/pandas/core/ops.py", line 887, in f
    return self._combine_frame(other, na_op, fill_value, level)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.16.2.dr
v-0/pandas-0.16.2/pandas/core/frame.py", line 3124, in _combine_frame
    this, other = self.align(other, join='outer', level=level, copy=False)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.16.2.dr
v-0/pandas-0.16.2/pandas/core/generic.py", line 3374, in align
    fill_axis=fill_axis)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.16.2.dr
v-0/pandas-0.16.2/pandas/core/generic.py", line 3401, in _align_frame
    return_indexers=True)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.16.2.dr
v-0/pandas-0.16.2/pandas/core/index.py", line 2043, in join
    return_indexers=return_indexers)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.16.2.dr
v-0/pandas-0.16.2/pandas/core/index.py", line 2071, in join
    join_index = self.union(other)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.16.2.dr
v-0/pandas-0.16.2/pandas/core/index.py", line 1431, in union
    return self._wrap_union_result(other, result)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.16.2.dr
v-0/pandas-0.16.2/pandas/core/index.py", line 1435, in _wrap_union_result
    return self.__class__(data=result, name=name)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.16.2.dr
v-0/pandas-0.16.2/pandas/core/index.py", line 116, in __new__
    from pandas.tseries.period import PeriodIndex
  File "pandas/tslib.pyx", line 836, in pandas.tslib._Timestamp.__richcmp__ (pandas/tslib.c:15612)
    raise TypeError('Cannot compare type %r with type %r' %
TypeError: Cannot compare type 'Timestamp' with type 'int'

----------------------------------------------------------------------
Ran 17 tests in 14.066s
```

I cannot look into more detail right now.

**Comment by FRidh** [comment]
@datakurre 
This is indeed a new failing test since the upgrade to numpy 1.10.

**Comment by domenkozar** [comment]
@sanbor can you try on master branch again?

**Comment by datakurre** [comment]
Looks better  with the latest versions. Yet, still fails on Darwin, because a test depends on OS X cliptool utilities /usr/bin/pbcopy /usr/bin/pbpaste not available in build sandbox.

**Comment by datakurre** [comment]
@pikajude said that because pbcopy / pbpaste are not open sourced, the only option is to disable tests (or with a patch just that test) on Darwin.

**Comment by FRidh** [comment]
@datakurre could you tell exactly which test it is? We can just disable that test then.

**Comment by datakurre** [comment]
@FRidh 

```
test_read_clipboard_infer_excel (pandas.io.tests.test_clipboard.TestClipboard) ... sh: pbcopy: command not found
sh: pbpaste: command not found
ERROR
======================================================================
ERROR: test_read_clipboard_infer_excel (pandas.io.tests.test_clipboard.TestClipboard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.17.0.drv-0/pandas-0.17.0/pandas/io/tests/test_clipbo
ard.py", line 87, in test_read_clipboard_infer_excel
    df = pd.read_clipboard()
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.17.0.drv-0/pandas-0.17.0/pandas/io/clipboard.py", li
ne 51, in read_clipboard
    return read_table(StringIO(text), **kwargs)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.17.0.drv-0/pandas-0.17.0/pandas/io/parsers.py", line
 491, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.17.0.drv-0/pandas-0.17.0/pandas/io/parsers.py", line
 268, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.17.0.drv-0/pandas-0.17.0/pandas/io/parsers.py", line
 583, in __init__
    self._make_engine(self.engine)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.17.0.drv-0/pandas-0.17.0/pandas/io/parsers.py", line
 724, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/private/var/folders/y6/2zdynm9x3nv6sq5p6780dwdc0000gn/T/nix-build-python2.7-pandas-0.17.0.drv-0/pandas-0.17.0/pandas/io/parsers.py", line
 1093, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 515, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:5031)
    heuristic = 2**20 // self.table_width
ValueError: No columns to parse from file
``

**Comment by domenkozar** [comment]
On master Pandas fails to build for Python 3.4: http://hydra.nixos.org/build/27161273/nixlog/1/raw

**Comment by datakurre** [comment]
@FRidh Sorry for not responding to the now merged pull. I think, the whole TestClipboard test suite should be disabled on darwin. It's now failing on another test:

```
test_round_trip_frame (pandas.io.tests.test_clipboard.TestClipboard) ... /bin/sh: pbcopy: command not
 found
/bin/sh: pbcopy: command not found
/bin/sh: pbpaste: command not found
ERROR

======================================================================
ERROR: test_round_trip_frame (pandas.io.tests.test_clipboard.TestClipboard)
----------------------------------------------------------------------
```

**Comment by domenkozar** [comment]
Is this fixed on master?

**Comment by datakurre** [comment]
Fixed in master.

Domen Kožar kirjoitti to marraskuuta 12 21:56:48 2015 GMT+0200:
