### ISSUE TITLE
Tribler needs update from 7.4.4 to 7.5.1

### ISSUE THREAD

**Issue by operator-name** [NixOS/nixpkgs#93053]
## Issue description
[Tribler](https://github.com/NixOS/nixpkgs/blob/00a5e1e76f9d87e4c22eac1bd8e6b36c4594e1c8/pkgs/applications/networking/p2p/tribler/default.nix) needs updating to [latest version](https://github.com/Tribler/tribler/releases)

**Comment by xvapx** [comment]
I'm working on it, there are a lot of changes in the 7.5 release.

**Comment by xvapx** [comment]
It's working now on https://github.com/xvapx/nixpkgs/tree/update/tribler, but there is some clean-up and testing to do before PR.

**Comment by xvapx** [comment]
No crashes so far but it doesn't seem to be downloading at all, I need to test more.

**Comment by ilikeavocadoes** [comment]
The current version of Tribler in nixpkgs crashes upon startup with this message:
```
Traceback (most recent call last):
  File "/nix/store/i4kgcgbjx550a59fsy7zq0nww5zcniz8-tribler-7.4.4/TriblerGUI/event_request_manager.py", line 114, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'ValueError'>: Nonce must be between 8 and 128 bytes
/nix/store/i4kgcgbjx550a59fsy7zq0nww5zcniz8-tribler-7.4.4/Tribler/pyipv8/ipv8/messaging/anonymization/community.py:74:inner_wrapper
/nix/store/i4kgcgbjx550a59fsy7zq0nww5zcniz8-tribler-7.4.4/Tribler/pyipv8/ipv8/messaging/anonymization/community.py:749:on_create
/nix/store/i4kgcgbjx550a59fsy7zq0nww5zcniz8-tribler-7.4.4/Tribler/pyipv8/ipv8/util.py:76:addCallback
/nix/store/azzbbxp33hrkzbp02yn6nz1ipm7q38gv-python3.8-Twisted-20.3.0/lib/python3.8/site-packages/twisted/internet/defer.py:311:addCallbacks
--- <exception caught here> ---
/nix/store/azzbbxp33hrkzbp02yn6nz1ipm7q38gv-python3.8-Twisted-20.3.0/lib/python3.8/site-packages/twisted/internet/defer.py:654:_runCallbacks
/nix/store/i4kgcgbjx550a59fsy7zq0nww5zcniz8-tribler-7.4.4/Tribler/pyipv8/ipv8/messaging/anonymization/community.py:745:determined_to_join
/nix/store/i4kgcgbjx550a59fsy7zq0nww5zcniz8-tribler-7.4.4/Tribler/community/triblertunnel/community.py:458:join_circuit
/nix/store/i4kgcgbjx550a59fsy7zq0nww5zcniz8-tribler-7.4.4/Tribler/pyipv8/ipv8/messaging/anonymization/community.py:728:join_circuit
/nix/store/i4kgcgbjx550a59fsy7zq0nww5zcniz8-tribler-7.4.4/Tribler/pyipv8/ipv8/messaging/anonymization/tunnelcrypto.py:82:encrypt_str
/nix/store/al6x0pk1n8hkjn2bjchbfzs2akn16p9c-python3.8-cryptography-3.4.6/lib/python3.8/site-packages/cryptography/hazmat/primitives/ciphers/aead.py:189:encrypt
/nix/store/al6x0pk1n8hkjn2bjchbfzs2akn16p9c-python3.8-cryptography-3.4.6/lib/python3.8/site-packages/cryptography/hazmat/primitives/ciphers/aead.py:214:_check_params
]
```
or randomly with this message:
```
Traceback (most recent call last):
  File "/nix/store/i4kgcgbjx550a59fsy7zq0nww5zcniz8-tribler-7.4.4/TriblerGUI/event_request_manager.py", line 114, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'TypeError'>: No Python class registered for C++ class libtorrent::flags::bitfield_flag<unsigned char, libtorrent::connection_type_tag, void>
/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/lib/python3.8/threading.py:932:_bootstrap_inner
/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/lib/python3.8/threading.py:870:run
/nix/store/azzbbxp33hrkzbp02yn6nz1ipm7q38gv-python3.8-Twisted-20.3.0/lib/python3.8/site-packages/twisted/_threads/_threadworker.py:46:work
/nix/store/azzbbxp33hrkzbp02yn6nz1ipm7q38gv-python3.8-Twisted-20.3.0/lib/python3.8/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/nix/store/azzbbxp33hrkzbp02yn6nz1ipm7q38gv-python3.8-Twisted-20.3.0/lib/python3.8/site-packages/twisted/python/threadpool.py:250:inContext
/nix/store/azzbbxp33hrkzbp02yn6nz1ipm7q38gv-python3.8-Twisted-20.3.0/lib/python3.8/site-packages/twisted/python/threadpool.py:266:<lambda>
/nix/store/azzbbxp33hrkzbp02yn6nz1ipm7q38gv-python3.8-Twisted-20.3.0/lib/python3.8/site-packages/twisted/python/context.py:122:callWithContext
/nix/store/azzbbxp33hrkzbp02yn6nz1ipm7q38gv-python3.8-Twisted-20.3.0/lib/python3.8/site-packages/twisted/python/context.py:85:callWithContext
/nix/store/i4kgcgbjx550a59fsy7zq0nww5zcniz8-tribler-7.4.4/Tribler/Core/APIImplementation/LaunchManyCore.py:560:sesscb_states_callback
/nix/store/i4kgcgbjx550a59fsy7zq0nww5zcniz8-tribler-7.4.4/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py:892:get_peerlist
]
```

**Comment by ilikeavocadoes** [comment]
Pinging @xvapx

**Comment by xvapx** [comment]
cc @ilikeavocadoes I couldn't get it to work last time, I'm going to try again with the current v7.8.0 and see if I can finally update it, thanks for pinging me.

**Comment by xvapx** [comment]
Ok, so multiple Tribler python dependencies are not avaliable on nixpkgs or need different versions of what we have.

As of now, I'll mark it as broken.

To get Tribler working with the current version, I would need at least to:
* Add these python libraries:
webargs5
aiohttp-apispec
webtest-aiohttp

* Update these ones:
chardet
semver
aiohttp

* Downgrade:
apispec

And maybe more, I still haven't got it working again.

cc @FRidh 

I don't mind PRing and testing, but i know the python ecosystem is delicate and currently new packages are not desired.
Also I don't suppose downgrading a library is really a good idea, but [i'ts a dependency of a dependency and there is no new compatible version for now](https://github.com/maximdanilchenko/aiohttp-apispec/issues/105).

Is there an accepted way of including these dependencies in Tribler instead of pythonPackages or any other way I can get this working without creating conflicts with the python infrastructure?

**Comment by SuperSandro2000** [comment]
> * Downgrade:
>   apispec

Or we just relax the python dependency.

**Comment by xvapx** [comment]
@SuperSandro2000 The new version and the old one are not compatible, there are signature changes in used functions.

**Comment by SuperSandro2000** [comment]
Then we could add the old version back or overwrite it just for tribler.

**Comment by noughtmare** [comment]
Oh, I see now that there is a pull request: https://github.com/NixOS/nixpkgs/pull/128145
