### ISSUE TITLE
vagrant rsync-auto command cannot find libffi.so.6

### ISSUE THREAD

**Issue by retrry** [NixOS/nixpkgs#9324]
Hello, when I try to use vagrant command rsync-auto comman I get error:
```
$ vagrant rsync-auto
==> dev: Doing an initial rsync...
==> dev: Rsyncing folder: /home/user/Development/project/ => /vagrant
==> dev:   - Exclude: [".vagrant/", ".git/"]
==> dev: Watching: /home/user/Development/project
/nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/event/queue.rb:15: warning: toplevel constant Queue referenced by Thread::Queue
/nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/event/loop.rb:16: warning: toplevel constant Queue referenced by Thread::Queue
/nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/ffi-1.9.10/lib/ffi.rb:6:in `require': libffi.so.6: cannot open shared object file: No such file or directory - /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/ffi-1.9.10/lib/ffi_c.so (LoadError)
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/ffi-1.9.10/lib/ffi.rb:6:in `rescue in <top (required)>'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/ffi-1.9.10/lib/ffi.rb:3:in `<top (required)>'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/rb-inotify-0.9.5/lib/rb-inotify/native.rb:1:in `require'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/rb-inotify-0.9.5/lib/rb-inotify/native.rb:1:in `<top (required)>'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/rb-inotify-0.9.5/lib/rb-inotify.rb:1:in `require'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/rb-inotify-0.9.5/lib/rb-inotify.rb:1:in `<top (required)>'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/adapter/linux.rb:30:in `require'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/adapter/linux.rb:30:in `_configure'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/adapter/base.rb:45:in `block in configure'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/adapter/base.rb:40:in `each'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/adapter/base.rb:40:in `configure'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/adapter/base.rb:63:in `start'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/backend.rb:26:in `start'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/listener.rb:67:in `block in <class:Listener>'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/fsm.rb:120:in `instance_eval'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/fsm.rb:120:in `call'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/fsm.rb:57:in `transition'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/listener.rb:90:in `start'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/rsync/command/rsync_auto.rb:142:in `block in execute'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/rsync/command/rsync_auto.rb:141:in `execute'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
        from /nix/store/jrl7pg24ds3zz2ywnhkxzl5lqs7c4m56-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```
Could somebody help me fix this?

**Comment by retrry** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/11766 in https://github.com/NixOS/nixpkgs/issues/11701
