### ISSUE TITLE
GNOME gtd app

### ISSUE THREAD

**Issue by srid** [NixOS/nixpkgs#93370]
**Project description**
https://github.com/getting-things-gnome/gtg is a GTD app for GNOME. nixpkgs already has `gnome-todo`, and this one is a feature-rich version version with support for GTD workflow.

**Metadata**

* homepage URL: https://wiki.gnome.org/Apps/GTG
* source URL: https://github.com/getting-things-gnome/gtg
* license: gpl3
* platforms: linux (gnome)

**Comment by dasj19** [comment]
Hello, I have used around 2 hours on packaging.
I need however a library called liblarch to get this running.

Here is the code if you can get further.

gtd/default.nix
```
{stdenv, fetchFromGitHub, python3, python3Packages, pkgconfig, itstool, gettext }:

stdenv.mkDerivation rec {
  version = "0.4";
  pname = "gtd";

  src = fetchFromGitHub {
    owner = "getting-things-gnome";
    repo  = "gtg";
    rev = "v${version}";
    sha256 = "0r28vyr88rj3kd3cg4gj7sd29wadjchi92wzmbx67d4hlg25h8kk";
  };

  nativeBuildInputs = [ pkgconfig ];
  buildInputs = with python3Packages; [ nose mock xdg dbus-python pycairo meson pygobject3 ]
  ++ [ gettext itstool ];

  patchPhase = ''
    substituteInPlace run-tests \
      --replace "!/usr/bin/env python3" !${python3}/bin/python3
  '';

  meta = with stdenv.lib; {
    description = "A personal tasks and TODO list items organizer inspired by the Getting Things Done (GTD) methodology.";
    longDescription = ''
      GTG is designed with flexibility, adaptability, and ease of use in mind so it can be used as more than just GTD software.
      GTG is intended to help you track everything you need to do and need to know, from small tasks to large projects.
    '';
    homepage = "https://github.com/getting-things-gnome/gtg";
    downloadPage = "https://github.com/getting-things-gnome/gtg/releases";
    license = licenses.gpl3Only;
    maintainers = [ maintainers.dasj19 ];
    platforms = platforms.linux;
  };
}
```

liblarch/default.nix
```
{ stdenv, fetchFromGitHub, python3 }:

stdenv.mkDerivation rec {
  version = "3.0.1";
  pname = "liblarch";

  src = fetchFromGitHub {
    owner = "getting-things-gnome";
    repo  = "liblarch";
    rev = "v${version}";
    sha256 = "0r28vyr88rj1kd7cg4gj7sd29wadjchi92wzmbx67d4hlg25h8kk";
  };

  meta = with stdenv.lib; {
    description = "A python library built to easily handle data structure such are lists, trees and acyclic graphs";
    homepage = "https://github.com/getting-things-gnome/liblarch";
    downloadPage = "https://github.com/getting-things-gnome/liblarch/releases";
    license = licenses.lgpl3Only;
    maintainers = [ maintainers.dasj19 ];
    platforms = platforms.linux;
  };
}
```

**Comment by oyren** [comment]
I was playing around with liblarch.
With `nix-env -f . -iA python38Packages.liblarch --show-trace` the tests of liblarch runs fine but i get a Segmentation fault:
```bash
test_refresh_every_time_with_parameters (tests.test_filteredtree.TestFilteredTree) ... ok
test_refresh_only_with_new_filter (tests.test_filteredtree.TestFilteredTree) ... ok
test_add_children_first (tests.test_liblarch.TestLibLarch)
Set children of a task first and only then add it tree. ...
(nix_run_setup:94): Gtk-CRITICAL **:  _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
/nix/store/masjzvyyqdlfywk5wgsblpjnbkviafd4-setuptools-check-hook/nix-support/setup-hook: line 4:    94 Segmentation fault      (core dumped) /nix/store/7q4crsd8kvmma32ff2xw4w9ydj5k26cy-python3-3.8.3/bin/python3.8 nix_run_setup test
builder for '/nix/store/qgk7y7pk8p28ir0qk3zdwgfpi1g5wfb9-python3.8-liblarch-3.0.1.drv' failed with exit code 139
error: build of '/nix/store/qgk7y7pk8p28ir0qk3zdwgfpi1g5wfb9-python3.8-liblarch-3.0.1.drv' failed

```

pkgs/development/python-modules/liblarch/default.nix
```nix
{ stdenv, fetchFromGitHub, python3, buildPythonPackage, gobject-introspection, wrapGAppsHook, pango, gdk-pixbuf, atk }:

buildPythonPackage rec {
  version = "3.0.1";
  pname = "liblarch";

  src = fetchFromGitHub {
    owner = "getting-things-gnome";
    repo  = "liblarch";
    rev = "v${version}";
    sha256 = "0xv2mfvyzipbny3iz8vll77wsqxfwh28xj6bj1ff0l452waph45m";
  };

  nativeBuildInputs = [
    gobject-introspection
    wrapGAppsHook
    pango
    gdk-pixbuf
    atk
  ];

  propagatedBuildInputs = with python3.pkgs; [
    pygobject3
    gst-python
  ];


  meta = with stdenv.lib; {
    description = "A python library built to easily handle data structure such are lists, trees and acyclic graphs";
    homepage = "https://github.com/getting-things-gnome/liblarch";
    downloadPage = "https://github.com/getting-things-gnome/liblarch/releases";
    license = licenses.lgpl3Only;
    maintainers = [ maintainers.dasj19 ];
    platforms = platforms.linux;
  };
}
```
pkgs/top-level/python-packages.nix
```
  liblarch = callPackage ../development/python-modules/liblarch { };
```

**Comment by oyren** [comment]
Possibly the same problem as here: https://github.com/NixOS/nixpkgs/pull/36825

**Comment by jtojnar** [comment]
Maybe try adding GTK? Its settings schemas might be needed for the test.

**Comment by oyren** [comment]
> Maybe try adding GTK? Its settings schemas might be needed for the test.

Same result.

**Comment by jtojnar** [comment]
Do you have a branch I can checkout and try?

**Comment by dasj19** [comment]
It builds if we avoid all tests with `doCheck = false;`

**Comment by oyren** [comment]
> Do you have a branch I can checkout and try? Too lazy to copy and paste and create files smile_cat

https://github.com/oyren/nixpkgs/commit/c819fddc3779de78e271464e8d5b209d3e1a27c3

**Comment by jtojnar** [comment]
You can do `git rebase --interactive master` and then delete the lines you do not want and then `git push --force`.

I ran the following in my Nixpkgs to add a checkout with your changes:

```bash
git fetch git@github.com:oyren/nixpkgs.git add-liblarch
git worktree add gtg -f FETCH_HEAD
cd gtg
```

It looks like the segfault was due to GTK tests requiring X server. Fixed that by running them in Xvfb:

```nix
{ stdenv
, fetchFromGitHub
, buildPythonPackage
, python
, pygobject3
, xvfb_run
, gobject-introspection
, gtk3
}:

buildPythonPackage rec {
  version = "3.0.1";
  pname = "liblarch";

  src = fetchFromGitHub {
    owner = "getting-things-gnome";
    repo = "liblarch";
    rev = "v${version}";
    sha256 = "0xv2mfvyzipbny3iz8vll77wsqxfwh28xj6bj1ff0l452waph45m";
  };

  checkInputs = [
    gobject-introspection # for setup hook
    gtk3
  ];

  propagatedBuildInputs = [
    pygobject3
  ];

  checkPhase = ''
    runHook preCheck

    ${xvfb_run}/bin/xvfb-run -s '-screen 0 800x600x24' \
      ${python.interpreter} nix_run_setup test

    runHook postCheck
  '';

  meta = with stdenv.lib; {
    description = "A python library built to easily handle data structure such are lists, trees and acyclic graphs";
    homepage = "https://github.com/getting-things-gnome/liblarch";
    downloadPage = "https://github.com/getting-things-gnome/liblarch/releases";
    license = licenses.lgpl3Only;
    maintainers = [ maintainers.dasj19 ];
    platforms = platforms.linux;
  };
}
```

**Comment by oyren** [comment]
Thank @jtojnar , I have now put everything together in one [branch](https://github.com/oyren/nixpkgs/tree/add-gtg), but again I am not getting anywhere. 

```bash
  File "/build/source/GTG/core/dirs.py", line 23, in <module>
    from xdg.BaseDirectory import xdg_data_home, xdg_config_home, xdg_cache_home
ModuleNotFoundError: No module named 'xdg.BaseDirectory'

----------------------------------------------------------------------
Ran 82 tests in 0.056s

FAILED (errors=1)
make: *** [Makefile:30: tests] Error 1
builder for '/nix/store/s7fc87js9rzj45y5gkcwnqhasqlvq2nw-gtg-0.4.drv' failed with exit code 2
error: build of '/nix/store/s7fc87js9rzj45y5gkcwnqhasqlvq2nw-gtg-0.4.drv' failed
```
Shouldn't  `xdg` or `pyxdg` provide the required module?

By the way it would probably be better if @dasj19 maintains the package, since I'm not very familiar with python.

I saw that [pyxdg has been removed](https://github.com/getting-things-gnome/gtg/commit/233ad05e55a9b25d49e1899161087fddba254913), so I tried to set the rev value to a current commit in the master and added glib to nativeBuildInputs.

```
    rev = "6623731f301c1b9c7b727e009f4a6462ad381c68";
    sha256 = "14gxgg4nl0ki3dn913041jpyfhxsj90fkd55z6mmpyklhr8mwss1";
```

But now pycodestyle brings me a error, can I determine that pycodestyle is not called or continues despite error/warning?
```bash
make: *** [Makefile:41: pep8] Error 1
builder for '/nix/store/dnlfx7kfd8b5bkg4hdhkp1af2m5hm9fp-gtg-0.4.drv' failed with exit code 2
error: build of '/nix/store/dnlfx7kfd8b5bkg4hdhkp1af2m5hm9fp-gtg-0.4.drv' failed
```

**Comment by jtojnar** [comment]
Yeah, it should be part of pyxdg. I would recommend using `python3.pkgs.buildPythonApplication` and adding the python modules to `propagatedBuildInputs` instead of `stdenv.mkDerivation`. Also add `format = "other";` and `meson` and `ninja` to `nativeBuildInputs`.

**Comment by jtojnar** [comment]
The pep8 failure happens because `check` is default target in the `Makefile`:

https://github.com/getting-things-gnome/gtg/blob/b381aa0378a5bfe206dec8d70757e387cdc9c5f6/Makefile#L23

so our default `buildPhase` runs it.

Switching to `meson` build system will avoid using the `Makefile`.

**Comment by oyren** [comment]
Thank again @jtojnar , I updated the [branch](https://github.com/oyren/nixpkgs/tree/add-gtg). Anddddd I'm stuck again :disappointed:  . Not even sure if this is a problem of software or packing.

```bash
~> gtg
/nix/store/hl0j3abxn60dw4fd25y648gzg5293laz-python3.8-pygobject-3.36.0/lib/python3.8/site-packages/gi/module.py:171: Warning: cannot register existing type 'AtkImplementorIface'
  g_type = info.get_g_type()
/nix/store/hl0j3abxn60dw4fd25y648gzg5293laz-python3.8-pygobject-3.36.0/lib/python3.8/site-packages/gi/module.py:205: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  type_ = g_type.pytype
/nix/store/hl0j3abxn60dw4fd25y648gzg5293laz-python3.8-pygobject-3.36.0/lib/python3.8/site-packages/gi/types.py:250: Warning: cannot register existing type 'AtkImplementorIface'
  register_interface_info(cls.__info__.get_g_type())
Traceback (most recent call last):
  File "/nix/store/23nmn5vxwnfg3999lbvxxzyp1jr5idp9-gtg-0.4/bin/..gtg-wrapped-wrapped", line 63, in <module>
    from GTG.gtk.application import Application
  File "/nix/store/23nmn5vxwnfg3999lbvxxzyp1jr5idp9-gtg-0.4/lib/python3.8/site-packages/GTG/gtk/application.py", line 21, in <module>
    from gi.repository import Gtk, Gdk, Gio
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/nix/store/hl0j3abxn60dw4fd25y648gzg5293laz-python3.8-pygobject-3.36.0/lib/python3.8/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/nix/store/hl0j3abxn60dw4fd25y648gzg5293laz-python3.8-pygobject-3.36.0/lib/python3.8/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/nix/store/8hf2rpqx8fnx6a3jm9pvn0d40c065zxl-python3-3.8.3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nix/store/hl0j3abxn60dw4fd25y648gzg5293laz-python3.8-pygobject-3.36.0/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 136, in <module>
    class Widget(Gtk.Widget):
  File "/nix/store/hl0j3abxn60dw4fd25y648gzg5293laz-python3.8-pygobject-3.36.0/lib/python3.8/site-packages/gi/module.py", line 176, in __getattr__
    interfaces = tuple(interface for interface in get_interfaces_for_object(info)
  File "/nix/store/hl0j3abxn60dw4fd25y648gzg5293laz-python3.8-pygobject-3.36.0/lib/python3.8/site-packages/gi/module.py", line 102, in get_interfaces_for_object
    interfaces.append(getattr(module, name))
  File "/nix/store/hl0j3abxn60dw4fd25y648gzg5293laz-python3.8-pygobject-3.36.0/lib/python3.8/site-packages/gi/module.py", line 215, in __getattr__
    wrapper = metaclass(name, bases, dict_)
  File "/nix/store/hl0j3abxn60dw4fd25y648gzg5293laz-python3.8-pygobject-3.36.0/lib/python3.8/site-packages/gi/types.py", line 250, in __init__
    register_interface_info(cls.__info__.get_g_type())
TypeError: must be an interface
```

**Comment by jtojnar** [comment]
Your branch works for me with `strictDeps = false;`.

**Comment by oyren** [comment]
You are right :tada: , if I create a pull request should I separate the two packages (gtg and liblarch)?

@dasj19 should I add you as a maintainer?

**Comment by jtojnar** [comment]
It should be in separate commits in a single pull request.

**Comment by oyren** [comment]
I think we can close this one.

**Comment by dasj19** [comment]
@oryen sorry for slow answer... I do not necessarily want to maintain python apps I don't use... I believe it is best that the maintainer at least uses the application he maintains occasionally.
