### ISSUE TITLE
make-disk-image.sh doesn't work with partitionTableType="efi": Failed to open file system "/dev/block/254:1": No such file or directory

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#93381]
**Describe the bug**

`make-disk-image.sh` doesn't work with `partitionTableType="efi"`.

The phase1/phase2 don't setup `/dev/block` and `bootctl install` doesn't seem to like that:

(I added a bit of logging to `make-disk-image.sh`:)

```shell
++ ls -al /dev/block
ls: cannot access '/dev/block': No such file or directory
++ true
++ ls -al /dev/disk
ls: cannot access '/dev/disk': No such file or directory
++ true
++ ls -al /sys/dev/block
total 0
drwxr-xr-x 2 root 0 0 Jul 18 02:09 .
drwxr-xr-x 4 root 0 0 Jul 18 02:09 ..
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:0 -> ../../devices/virtual/block/ram0
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:1 -> ../../devices/virtual/block/ram1
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:10 -> ../../devices/virtual/block/ram10
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:11 -> ../../devices/virtual/block/ram11
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:12 -> ../../devices/virtual/block/ram12
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:13 -> ../../devices/virtual/block/ram13
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:14 -> ../../devices/virtual/block/ram14
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:15 -> ../../devices/virtual/block/ram15
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:2 -> ../../devices/virtual/block/ram2
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:3 -> ../../devices/virtual/block/ram3
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:4 -> ../../devices/virtual/block/ram4
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:5 -> ../../devices/virtual/block/ram5
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:6 -> ../../devices/virtual/block/ram6
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:7 -> ../../devices/virtual/block/ram7
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:8 -> ../../devices/virtual/block/ram8
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 1:9 -> ../../devices/virtual/block/ram9
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 254:0 -> ../../devices/pci0000:00/0000:00:07.0/virtio3/block/vda
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 254:1 -> ../../devices/pci0000:00/0000:00:07.0/virtio3/block/vda/vda1
lrwxrwxrwx 1 root 0 0 Jul 18 02:09 254:2 -> ../../devices/pci0000:00/0000:00:07.0/virtio3/block/vda/vda2


++ lsblk -f
NAME   FSTYPE FSVER LABEL UUID FSAVAIL FSUSE% MOUNTPOINT
vda                                           
|-vda1                          247.8M     0% /mnt/boot
`-vda2                               0    94% /mnt
++ udevinfo -q path -n /dev/vda
/nix/store/2a9cv8f3aisf94xgzzpmgpbnd9lhqzxw-stdenv-linux/setup: line 1297: udevinfo: command not found
++ true
++ mkdir -p /dev/block
++ mkdir -p /mnt/etc/nixos
++ NIXOS_INSTALL_BOOTLOADER=1
++ nixos-enter --root /mnt -- /nix/var/nix/profiles/system/bin/switch-to-configuration boot
setting up /etc...
Initializing machine ID from random generator.
Failed to open file system "/dev/block/254:1": No such file or directory
Traceback (most recent call last):
  File "/nix/store/99h20fjb0miaxcascrv8763byq6f43jv-systemd-boot-builder.py", line 256, in <module>
    main()
  File "/nix/store/99h20fjb0miaxcascrv8763byq6f43jv-systemd-boot-builder.py", line 199, in main
    subprocess.check_call(["/nix/store/li8ybhd1x377qb9c14mn8i6vjbig1i4z-systemd-245.6/bin/bootctl", "--path=/boot", "--no-variables", "install"])
  File "/nix/store/7q4crsd8kvmma32ff2xw4w9ydj5k26cy-python3-3.8.3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/li8ybhd1x377qb9c14mn8i6vjbig1i4z-systemd-245.6/bin/bootctl', '--path=/boot', '--no-variables', 'ins>
+ exitHandler

```

Unfortunately, I can't figure out how to mount `/dev/block` properly, or what should be responsible for doing so.

**Metadata**
This is with `nixos-unstable{-small}`. currently : 24b55081f5f34bcac32db6dd38948c795c270582

**Comment by danielfullmer** [comment]
I had a similar problem when using `systemd-boot` in `qemu-vm.nix`. I believe udev is supposed to create those device nodes, however, udev isn't available in the more minimal linux environment given by `runInLinuxVM`. I ultimately just added the symlink manually for the required device:
https://github.com/NixOS/nixpkgs/blob/0ae51edb29dc6aa5f86c1e3686047032818af089/nixos/modules/virtualisation/qemu-vm.nix#L249-L251

**Comment by ncfavier** [comment]
I am still running into this.

**Comment by vcunat** [comment]
We now sometimes get this error (message) in blocker tests, e.g. the first run of [this test on Hydra](https://hydra.nixos.org/build/138895738#tabs-buildsteps) and I can't even make that test succeed locally. _Unfortunately I know little about topics around this._
