### ISSUE TITLE
csvkit package's csvsql is broken

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#93594]
**Describe the bug**

If you install `csvkit`, and use `csvsql --help` it complains:

```
Traceback (most recent call last):
  File "/nix/store/dpaa7h0l82xd0abm0n6wg5giml8rmaya-csvkit-1.0.4/bin/.csvsql-wrapped", line 6, in <module>
    from csvkit.utilities.csvsql import launch_new_instance
  File "/nix/store/dpaa7h0l82xd0abm0n6wg5giml8rmaya-csvkit-1.0.4/lib/python3.7/site-packages/csvkit/utilities/csvsql.py", line 5, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

Recommend adding `setuptools` as a build input to the package so it can import `pkg_resources`.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.128, Matrix Central, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by CMCDragonkai** [comment]
It can be fixed with:

```
      csvkit.overridePythonAttrs (attrs: {
        propagatedBuildInputs = (attrs.propagatedBuildInputs ++ [ python3Packages.setuptools ]);
      })
```

**Comment by lestephane** [comment]
I'm still experiencing this error with csvkit 1.1.1 installed using `nix-env -i`. How come?

```
Traceback (most recent call last):
  File "/nix/store/p6iyr2a5yszfqjngdkqp6x1j4wc294aj-csvkit-1.1.1/bin/.csvsql-wrapped", line 6, in <module>
    from csvkit.utilities.csvsql import launch_new_instance
  File "/nix/store/p6iyr2a5yszfqjngdkqp6x1j4wc294aj-csvkit-1.1.1/lib/python3.10/site-packages/csvkit/utilities/csvsql.py", line 8, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

## Metadata

```
# nix-shell -p nix-info --run "nix-info -m"
bash: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF-8)
/nix/store/j80wcbm6bb1nsqsgmniq43rg980p27q9-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF-8)
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.0-41-generic, Ubuntu, 22.04.2 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixpkgs"`
 - channels(*scrubbed*): `""`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```
