### ISSUE TITLE
Git not found when trying to upgrade pubs

### ISSUE THREAD

**Issue by guillaumecherel** [NixOS/nixpkgs#94663]
(I'm not sure this is the appropriate for this report. Sorry for the inconvenience if not and please let me know.)

**Describe the bug**
Trying to update the package pubs to the latest version (0.8.3), the build fails when running the tests because the command `git` cannot be found. I'm new to nix and I'm not sure if this can be fixed on the nix side or not. 

**To Reproduce**
1. Override the pubs package like so in a file default.nix:

```
  pubs083 = pubs.overridePythonAttrs (old: rec {
    version = "0.8.3";
    src = fetchFromGitHub {
      owner = "pubs";
      repo = "pubs";
      rev = "v{version}";
      sha256 = "0npgsyxj7kby5laznk5ilkrychs3i68y57gphwk48w8k9fvnl3zc";
    };

    patches = [ ];
  });
```

(I removed the patches because I believe they were applied upstream.)

2. Install with `nix-env -f default.nix -iA pubs083`

3. The following error appears during the test phase:

```
...
======================================================================
ERROR: test_git (tests.test_git.TestGitPlugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/pubs/plugs/git/git.py", line 44, in _gitinit
    self.shell('init')
  File "/build/source/pubs/plugs/git/git.py", line 81, in shell
    raise RuntimeError('The git plugin encountered an error when running the git command:\n' +
RuntimeError: The git plugin encountered an error when running the git command:
git -C /build/tmppalwuu58/pubs -c color.ui=always init

Returned output:
/bin/sh: git: not found
...
```

**Notify maintainers**
@gebner 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.54, NixOS, 20.09pre236721.840c782d507 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(guillaume): `""`
 - channels(root): `"nixos-20.09pre236721.840c782d507, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: pubs
```

**Comment by Thra11** [comment]
You _can_ add git to `checkInputs` with a line like this in your overrideAttrs:
```
    checkInputs = old.checkInputs ++ [ git ];
```
(Depending on the context, you might need `pkgs.git` or `self.git` or something else, depending what's in scope)
However, that doesn't actually get you much further:
```
======================================================================
ERROR: test_git (tests.test_git.TestGitPlugin)
-------------------------full---------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/test_git.py", line 26, in test_git
    hash_a = git_hash(self.default_pubs_dir)
  File "/build/source/tests/test_git.py", line 12, in git_hash
    return subprocess.check_output(hash_cmd)
  File "/nix/store/1l23hylw0nxrfdd12cyp9lsasgdm5fwd-python3-3.7.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/nix/store/1l23hylw0nxrfdd12cyp9lsasgdm5fwd-python3-3.7.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('git', '-C', '/build/tmp4167cgcg/pubs', 'rev-parse', 'HEAD')' returned non-zero exit status 128.

======================================================================
ERROR: test_manual (tests.test_git.TestGitPlugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/pubs/pubs_cmd.py", line 104, in execute
    args.func(conf, args)
  File "/build/source/pubs/plugs/git/git.py", line 64, in command
    self.shell(' '.join([shell_quote(a) for a in args.arguments]), command=True)
  File "/build/source/pubs/plugs/git/git.py", line 85, in shell
    'https://github.com/pubs/pubs/issues')
RuntimeError: The git plugin encountered an error when running the git command:
git -C /build/tmp5e8h1b_u/pubs -c color.ui=always commit -m '"initial_commit"'

Returned output:

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'nixbld@localhost.(none)')

If needed, you may fix the state of the /build/tmp5e8h1b_u/pubs git repository manually.
If relevant, you may submit a bug report at https://github.com/pubs/pubs/issues
```
Looks like the second failure, `test_manual` is because the test expects git to be pre-configured with the committer's details, which in a nix build sandbox it isn't. I believe they could probably fix this test by setting some environment variables. e.g. I believe something like this won't try to read the git config because all the info it needs is already in the environment:
```
GIT_AUTHOR_NAME="AuthorName" GIT_AUTHOR_EMAIL="author@test.email" GIT_COMMITTER_NAME="CommitterName" GIT_COMMITTER_EMAIL="committer@test.email" git -C /build/tmp5e8h1b_u/pubs -c color.ui=always commit -m '"initial_commit"'
```
As for the first failure, `test_git`... I'm not sure if it's trying to use the sources as a git repo in the test (and failing because `fetchFromGitHub` just downloads an archive tarball, without the `.git` directory, not an actual git repo), or whether it's just getting its paths muddled in some way)

If you just want to get it built and aren't too worried about the git tests, you can simply remove the offending test file by adding something like this to your overrideAttrs:
```
    preCheck = ''rm tests/test_git.py'';
```
This will delete the `test_git.py` before running the check phase. `setup.py` uses a `test_*.py`glob to find test files, so it doesn't even know it ever existed. This resulted in a successful build for me.

**Comment by Thra11** [comment]
If you do remove the git tests as I described, there's probably no longer any need to add `git` to `checkInputs`.
