### ISSUE TITLE
nixos installer tests fail

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#96361]
**Describe the bug**
https://hydra.nixos.org/build/125901359

**To Reproduce**
```
$ nix-build nixos/release-small.nix -A nixos.tests.installer.simple

```

```
machine: output: 
Test "Perform the installation" failed with error: "command `nixos-install < /dev/null >&2` failed (exit code 1)"
error: 
Traceback (most recent call last):
  File "/nix/store/bdfalnsmc6f6i8rm97j0rfk1wwgl6501-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 897, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 50, in <module>
  File "/nix/store/bdfalnsmc6f6i8rm97j0rfk1wwgl6501-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 421, in succeed
    raise Exception(
Exception: command `nixos-install < /dev/null >&2` failed (exit code 1)
cleaning up
killing machine (pid 6)
(0.00 seconds)
```

**Comment by FRidh** [comment]
```
machine # building '/nix/store/7x9q5qdd27aljvvrnrvabb6h6b0sh082-01-fix-ftbfs-with-glibc-2.28.patch.drv'...
machine # warning: unable to download 'https://sources.debian.org/data/main/m/m4/1.4.18-2/debian/patches/01-fix-ftbfs-with-glibc-2.28.patch': Couldn't resolve host name (6); retrying in 323 ms
machine # warning: unable to download 'https://sources.debian.org/data/main/m/m4/1.4.18-2/debian/patches/01-fix-ftbfs-with-glibc-2.28.patch': Couldn't resolve host name (6); retrying in 575 ms
machine # warning: unable to download 'https://sources.debian.org/data/main/m/m4/1.4.18-2/debian/patches/01-fix-ftbfs-with-glibc-2.28.patch': Couldn't resolve host name (6); retrying in 1109 ms
machine # warning: unable to download 'https://sources.debian.org/data/main/m/m4/1.4.18-2/debian/patches/01-fix-ftbfs-with-glibc-2.28.patch': Couldn't resolve host name (6); retrying in 2442 ms
machine # error: unable to download 'https://sources.debian.org/data/main/m/m4/1.4.18-2/debian/patches/01-fix-ftbfs-with-glibc-2.28.patch': Couldn't resolve host name (6)
machine # builder for '/nix/store/7x9q5qdd27aljvvrnrvabb6h6b0sh082-01-fix-ftbfs-with-glibc-2.28.patch.drv' failed with exit code 1
```
the test does not have network access

**Comment by vcunat** [comment]
The VM not having network access is not the real problem.  We occasionally get these errors on changes, but I can't remember the usual solution (how we ensure that the necessary dependencies are in store beforehand).

**Comment by FRidh** [comment]
See https://github.com/Emantor/nixpkgs/commit/901de1173247b916f3575eb5ce1af5c417eda381.
Suppose the issue started already in 820a197b5fee32f946f7cfba2010ce28c8d07a4f.

Not being able to fetch patches because an installer test depends on it is not very convenient.

**Comment by vcunat** [comment]
Note that installer shouldn't need the patch.  It should have binary `gnum4` already (if it needs it).

**Comment by Emantor** [comment]
Yes, looking at the discussion in https://github.com/NixOS/nixpkgs/commit/43e30b1eadac5f86fe6f91b13ebcace88bf8a597, we'll need to find the necessary `extraDepenencies` for the installer VM.

**Comment by vcunat** [comment]
By looking at the log, I expect we're missing `lvm2.override { udev = null; }`

**Comment by Emantor** [comment]
> By looking at the log, I expect we're missing `lvm2.override { udev = null; }`

Bingo, I'll create a PR.

**Comment by vcunat** [comment]
Thanks.  I now also tried the other two failed `unstable-small` tests, successfully.
