### ISSUE TITLE
ntfy fails to build on unstable and 20.03

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#96845]
`ntfy` fails its tests.

On `nixos-20.03` and `unstable`:

```
nix-shell -p ntfy
nix-shell '<unstable>' -p ntfy
```

gets me:

```
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing requirements to ntfy.egg-info/requires.txt
writing ntfy.egg-info/PKG-INFO
writing top-level names to ntfy.egg-info/top_level.txt
writing dependency_links to ntfy.egg-info/dependency_links.txt
writing entry points to ntfy.egg-info/entry_points.txt
reading manifest file 'ntfy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ntfy.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    'ntfy = ntfy.cli:main',
  File "/nix/store/klcis2b1q5gfwrfasazgnl95xdnynnn7-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/bskshdrk1acvgby58dg6n0h3q54bm77m-python-2.7.18/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/nix/store/bskshdrk1acvgby58dg6n0h3q54bm77m-python-2.7.18/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/nix/store/bskshdrk1acvgby58dg6n0h3q54bm77m-python-2.7.18/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/nix/store/klcis2b1q5gfwrfasazgnl95xdnynnn7-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/command/test.py", line 237, in run
    self.run_tests()
  File "/nix/store/klcis2b1q5gfwrfasazgnl95xdnynnn7-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/command/test.py", line 259, in run_tests
    exit=False,
  File "/nix/store/bskshdrk1acvgby58dg6n0h3q54bm77m-python-2.7.18/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/nix/store/bskshdrk1acvgby58dg6n0h3q54bm77m-python-2.7.18/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/nix/store/bskshdrk1acvgby58dg6n0h3q54bm77m-python-2.7.18/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/nix/store/bskshdrk1acvgby58dg6n0h3q54bm77m-python-2.7.18/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/nix/store/bskshdrk1acvgby58dg6n0h3q54bm77m-python-2.7.18/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/nix/store/klcis2b1q5gfwrfasazgnl95xdnynnn7-python2.7-setuptools-44.0.0/lib/python2.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/bskshdrk1acvgby58dg6n0h3q54bm77m-python-2.7.18/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_simplepush'
builder for '/nix/store/5xqr9vqnxkcq8wvanb8cia6jyxa8smpv-ntfy-2.7.0.drv' failed with exit code 1
```

`'module' object has no attribute 'test_simplepush'`

I'm pretty sure it worked before (but `ntfy` did not change, perhaps a dependency?).

My current workaround:

```nix
(ntfy.overrideAttrs (old: { doInstallCheck = false; })) # work around: AttributeError: 'module' object has no attribute 'test_simplepush'
```

CC maintainers @jfrankenau @kamilchm

**Comment by austinbutler** [comment]
At this point ntfy is marked broken in 20.03, but it does build on unstable so going to go ahead and close this out.
