### ISSUE TITLE
Blender missing "requests" python library for add-ons

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#97250]
## Issue description

Blender is missing the Python `requests` library which is a dependency of at least one popular add-on

### Steps to reproduce

Open `Edit > Preferences > Add-ons` and select `3D View: BlenderKit Online Asset Library` and this Python backtrace is presented:

```
Traceback (most recent call last):
  File "/nix/store/v8ykwxys87dfh60s414ds70ckbgyl9yx-blender-2.83.1/share/blender/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/nix/store/v8ykwxys87dfh60s414ds70ckbgyl9yx-blender-2.83.1/share/blender/2.83/scripts/addons/blenderkit/__init__.py", line 51, in <module>
    from blenderkit import asset_inspector, search, download, upload, ratings, autothumb, ui, icons, bg_blender, paths, \
  File "/nix/store/v8ykwxys87dfh60s414ds70ckbgyl9yx-blender-2.83.1/share/blender/2.83/scripts/addons/blenderkit/search.py", line 33, in <module>
    from blenderkit import paths, utils, categories, ui, colors, bkit_oauth, version_checker, tasks_queue, rerequests
  File "/nix/store/v8ykwxys87dfh60s414ds70ckbgyl9yx-blender-2.83.1/share/blender/2.83/scripts/addons/blenderkit/categories.py", line 27, in <module>
    from blenderkit import paths, utils, tasks_queue, rerequests
  File "/nix/store/v8ykwxys87dfh60s414ds70ckbgyl9yx-blender-2.83.1/share/blender/2.83/scripts/addons/blenderkit/rerequests.py", line 28, in <module>
    from blenderkit import ui, utils, paths, tasks_queue, bkit_oauth
  File "/nix/store/v8ykwxys87dfh60s414ds70ckbgyl9yx-blender-2.83.1/share/blender/2.83/scripts/addons/blenderkit/ui.py", line 34, in <module>
    from blenderkit import paths, ratings, utils, search, upload, ui_bgl, download, bg_blender, colors, tasks_queue
  File "/nix/store/v8ykwxys87dfh60s414ds70ckbgyl9yx-blender-2.83.1/share/blender/2.83/scripts/addons/blenderkit/ratings.py", line 30, in <module>
    import requests, threading
ModuleNotFoundError: No module named 'requests'
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.7, NixOS, 20.03.git.a41b1a288c7 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/home/luke/git/nixpkgs`

**Comment by lukego** [comment]
Workaround (fix?) seems to be

```
nix-shell -p python3Packages.requests --run blender
```

**Comment by FRidh** [comment]
Proposed solution https://github.com/NixOS/nixpkgs/pull/97388.
