### ISSUE TITLE
systemd-boot-builder failing

### ISSUE THREAD

**Issue by turboMaCk** [NixOS/nixpkgs#97426]
**Describe the bug**
`systemd-boot-builder.py` seems to be failing on recent unstable (see bellow)

**To Reproduce**
1. with config

```nix
  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    kernelPackages = pkgs.linuxPackages_5_7;
  };
```
2. `sudo nixos-rebuild switch --upgrade`

```
Copied "/nix/store/kmlzasz1lbkigpirk4vwyg14g206wq18-systemd-246/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/s
Copied "/nix/store/kmlzasz1lbkigpirk4vwyg14g206wq18-systemd-246/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOT
Random seed file /boot/loader/random-seed successfully written (512 bytes).
Failed to test system token validity: No data available
Traceback (most recent call last):
  File "/nix/store/c98r56rf8iijhybmjwx8bl5gr95g27by-systemd-boot-builder.py", line 256, in <module>
    main()
  File "/nix/store/c98r56rf8iijhybmjwx8bl5gr95g27by-systemd-boot-builder.py", line 197, in main
    subprocess.check_call(["/nix/store/kmlzasz1lbkigpirk4vwyg14g206wq18-systemd-246/bin/bootctl", "--path=/boot", "install"])
  File "/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/kmlzasz1lbkigpirk4vwyg14g206wq18-systemd-246/bin/bootctl', '--path=/boot', 'on-zero exit status 1.
```

**Expected behavior**
System rebuild should not fail.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/bgdqr36i8csfda3yfq5asbcnsdkwrklc-bash-interactive-4.4-p23-dev
copying path '/nix/store/bgdqr36i8csfda3yfq5asbcnsdkwrklc-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.16, NixOS, 20.09pre239318.c59ea8b8a0e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(marek): `"nixos-20.09pre234242.c71518e75bf"`
 - channels(root): `"nixos-20.09pre242714.a31736120c5, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: system.boot.loader.systemd-boot
```

**Comment by danielfullmer** [comment]
Yours definitely seems to be a separate issue, as you are not failing at `bootctl status`, but rather at the update/install stage. Could you post the output of:
```SYSTEMD_LOG_LEVEL=debug /nix/store/kmlzasz1lbkigpirk4vwyg14g206wq18-systemd-246/bin/bootctl --path=/boot install```

**Comment by turboMaCk** [comment]
sure this is the output:

```
Found container virtualization none.
Using EFI System Partition at /boot.
File system "/dev/block/259:6" has wrong type for extended boot loader partition.
Didn't find an XBOOTLDR partition, using the ESP as $BOOT.
Copied "/nix/store/kmlzasz1lbkigpirk4vwyg14g206wq18-systemd-246/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/nix/store/kmlzasz1lbkigpirk4vwyg14g206wq18-systemd-246/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
Random seed file /boot/loader/random-seed successfully written (512 bytes).
No virtualization found in DMI
No virtualization found in CPUID
Virtualization XEN not found, /proc/xen does not exist
This platform does not support /proc/device-tree
UML virtualization not found in /proc/cpuinfo.
This platform does not support /proc/sysinfo
Found VM virtualization none
Reading EFI variable /sys/firmware/efi/efivars/LoaderSystemToken-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
EFI variable /sys/firmware/efi/efivars/LoaderSystemToken-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f is shorter than 4 bytes, refusing.
Failed to test system token validity: No data available
```

**Comment by danielfullmer** [comment]
Yeah, this looks to the the issue:
```EFI variable /sys/firmware/efi/efivars/LoaderSystemToken-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f is shorter than 4 bytes, refusing.```

You can try deleting this file and re-running `bootctl install`, but there might be something else wrong with your UEFI variable storage.  If this doesn't work, you can report the issue upstream in `systemd`. In either case, I don't think this is a NixOS-specific issue.

**Comment by turboMaCk** [comment]
Interestingly though, the problem is gone after `sudo nixos-rebuild switch --upgrade`. I was able to reboot system and see 2 bootloader entries.

**Comment by turboMaCk** [comment]
Issue seems to be fixed by upstream. Closing.
