### ISSUE TITLE
systemd-boot-builder fails to update systemd-boot

### ISSUE THREAD

**Issue by sareyko** [NixOS/nixpkgs#97427]
**Describe the bug**
Rebuilding the system configuration (using `nixos-rebuild boot` or `switch`) when using systemd-boot as bootloader and upgrading from systemd 245 to 246 fails:

```
% sudo nixos-rebuild boot
building Nix...
building the system configuration...
Traceback (most recent call last):
  File "/nix/store/c98r56rf8iijhybmjwx8bl5gr95g27by-systemd-boot-builder.py", line 256, in <module>
    main()
  File "/nix/store/c98r56rf8iijhybmjwx8bl5gr95g27by-systemd-boot-builder.py", line 203, in main
    sdboot_status = subprocess.check_output(["/nix/store/kmlzasz1lbkigpirk4vwyg14g206wq18-systemd-246/bin/bootctl", "--path=/boot", "status"], universal_newlines=True)
  File "/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/kmlzasz1lbkigpirk4vwyg14g206wq18-systemd-246/bin/bootctl', '--path=/boot', 'status']' returned non-zero exit status 1.
warning: error(s) occurred while switching to the new configuration
```

**To Reproduce**
1. Install nixos-unstable using a channel state that contains systemd 245 and enable systemd-boot (`boot.loader.systemd-boot.enable = true;`)
2. Update the nixos-unstable channel and do a `nixos-rebuild boot`

**Expected behavior**
The systemd-boot should be updated from 245 to 246 and the system configuration should be built.

**Additional context**
`systemd-boot-builder.py` contains the following code:

```python
        # Update bootloader to latest if needed
        systemd_version = subprocess.check_output(["@systemd@/bin/bootctl", "--version"], universal_newlines=True).split()[1]
        sdboot_status = subprocess.check_output(["@systemd@/bin/bootctl", "--path=@efiSysMountPoint@", "status"], universal_newlines=True)

        # See status_binaries() in systemd bootctl.c for code which generates this
        m = re.search("^\W+File:.*/EFI/(BOOT|systemd)/.*\.efi \(systemd-boot (\d+)\)$",
                      sdboot_status, re.IGNORECASE | re.MULTILINE)
        if m is None:
            print("could not find any previously installed systemd-boot")
        else:
            sdboot_version = m.group(2)
            if systemd_version > sdboot_version:
                print("updating systemd-boot from %s to %s" % (sdboot_version, systemd_version))
                subprocess.check_call(["@systemd@/bin/bootctl", "--path=@efiSysMountPoint@", "update"])
```

Unfortunately `subprocess.check_output(["@systemd@/bin/bootctl", "--path=@efiSysMountPoint@", "status"], universal_newlines=True)` fails before the result can actually be checked because calling `bootctl status` (using `bootctl` from systemd 246) returns a non-zero exit code (I guess this is because it detects systemd-boot 245 being installed?) which raises an exception.

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.59, NixOS, 20.09pre239318.c59ea8b8a0e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager, nixos-20.09pre242714.a31736120c5"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
cc @flokli

**Comment by flokli** [comment]
Can you post the output of `bootctl status` (from 246) here?

**Comment by sareyko** [comment]
```
% /nix/store/kmlzasz1lbkigpirk4vwyg14g206wq18-systemd-246/bin/bootctl --path=/boot --no-pager status
System:
     Firmware: UEFI 2.00 (Lenovo 0.5216)
  Secure Boot: disabled
   Setup Mode: user
 Boot into FW: not supported

Current Boot Loader:
      Product: systemd-boot 245
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Boot loader sets ESP partition information
          ESP: /dev/disk/by-partuuid/313e233b-5a4b-4bfb-9ff0-7a811b3eda70
         File: └─/EFI/BOOT/BOOTX64.EFI

Random Seed:
 Passed to OS: no
 System Token: not set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /boot (/dev/disk/by-partuuid/313e233b-5a4b-4bfb-9ff0-7a811b3eda70)
         File: └─/EFI/systemd/systemd-bootx64.efi (systemd-boot 245)
         File: └─/EFI/BOOT/BOOTX64.EFI (systemd-boot 245)

Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0019
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/313e233b-5a4b-4bfb-9ff0-7a811b3eda70
         File: └─/EFI/systemd/systemd-bootx64.efi

Boot Loader Entries:
        $BOOT: /boot (/dev/disk/by-partuuid/313e233b-5a4b-4bfb-9ff0-7a811b3eda70)

Default Boot Loader Entry:
        title: NixOS (Generation 127 NixOS 20.09pre239318.c59ea8b8a0e, Linux Kernel 5.4.59, Built on 2020-08-31)
           id: nixos-generation-127.conf
       source: /boot/loader/entries/nixos-generation-127.conf
      version: Generation 127 NixOS 20.09pre239318.c59ea8b8a0e, Linux Kernel 5.4.59, Built on 2020-08-31
   machine-id: d4c43007a36d43d3b3a462d9c1957723
        linux: /efi/nixos/wzrwm681jk2w6pnl72m1lqfjap306mfw-linux-5.4.59-bzImage.efi
       initrd: /efi/nixos/khd5f3h8xs6m6z10vv0rmy71vrd1wcmm-initrd-linux-5.4.59-initrd.efi
      options: systemConfig=/nix/store/xd3nq6vqawspxilx0qx89ykg32g52yg2-nixos-system-george-20.09pre239318.c59ea8b8a0e init=/nix/store/xd3nq6vqawspxilx0qx89ykg32g52yg2-nixos-system-george-20.09pre239318.c59ea8b8a0e/init loglevel=4

% echo $?
1
```

The output for `bootctl status` from 245 is mostly the same except for the missing "Boot into FW: not supported" and a different exit status:

```
% /nix/store/kg0k2hrldivj2cfr57088nzj8zmvpr06-systemd-245.6/bin/bootctl --path=/boot --no-pager status
System:
     Firmware: UEFI 2.00 (Lenovo 0.5216)
  Secure Boot: disabled
   Setup Mode: user

Current Boot Loader:
      Product: systemd-boot 245
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Boot loader sets ESP partition information
          ESP: /dev/disk/by-partuuid/313e233b-5a4b-4bfb-9ff0-7a811b3eda70
         File: └─/EFI/BOOT/BOOTX64.EFI

Random Seed:
 Passed to OS: no
 System Token: not set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /boot (/dev/disk/by-partuuid/313e233b-5a4b-4bfb-9ff0-7a811b3eda70)
         File: └─/EFI/systemd/systemd-bootx64.efi (systemd-boot 245)
         File: └─/EFI/BOOT/BOOTX64.EFI (systemd-boot 245)

Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0019
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/313e233b-5a4b-4bfb-9ff0-7a811b3eda70
         File: └─/EFI/systemd/systemd-bootx64.efi

Boot Loader Entries:
        $BOOT: /boot (/dev/disk/by-partuuid/313e233b-5a4b-4bfb-9ff0-7a811b3eda70)

Default Boot Loader Entry:
        title: NixOS (Generation 127 NixOS 20.09pre239318.c59ea8b8a0e, Linux Kernel 5.4.59, Built on 2020-08-31)
           id: nixos-generation-127.conf
       source: /boot/loader/entries/nixos-generation-127.conf
      version: Generation 127 NixOS 20.09pre239318.c59ea8b8a0e, Linux Kernel 5.4.59, Built on 2020-08-31
   machine-id: d4c43007a36d43d3b3a462d9c1957723
        linux: /efi/nixos/wzrwm681jk2w6pnl72m1lqfjap306mfw-linux-5.4.59-bzImage.efi
       initrd: /efi/nixos/khd5f3h8xs6m6z10vv0rmy71vrd1wcmm-initrd-linux-5.4.59-initrd.efi
      options: systemConfig=/nix/store/xd3nq6vqawspxilx0qx89ykg32g52yg2-nixos-system-george-20.09pre239318.c59ea8b8a0e init=/nix/store/xd3nq6vqawspxilx0qx89ykg32g52yg2-nixos-system-george-20.09pre239318.c59ea8b8a0e/init loglevel=4

% echo $?
0
```

**Comment by sareyko** [comment]
I just noticed #97433 and #97426 which seem to describe the same or similar issues.

**Comment by sareyko** [comment]
Closing since the issue is already being taken care of in #97433.
