### ISSUE TITLE
KVM/qemu/libvirt: image ownership problems "Could not reopen file: permission denied"

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#97844]
When I try to create a virtual machine using virt-manager, I run into the following error:
```
Unable to complete install: 'internal error: process exited while connecting to monitor: 2020-09-12T13:38:19.996252Z qemu-system-x86_64: -drive file=/somepath/nixos.qcow2,format=qcow2,if=none,id=drive-ide0-0-0: Could not reopen file: Permission denied'

Traceback (most recent call last):
  File "/nix/store/m67zrpwmyajrxf0c5c41zd595nynlym1-virt-manager-2.2.1/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/nix/store/m67zrpwmyajrxf0c5c41zd595nynlym1-virt-manager-2.2.1/share/virt-manager/virtManager/createvm.py", line 2089, in _do_async_install
    guest.installer_instance.start_install(guest, meter=meter)
  File "/nix/store/m67zrpwmyajrxf0c5c41zd595nynlym1-virt-manager-2.2.1/share/virt-manager/virtinst/install/installer.py", line 544, in start_install
    doboot, transient)
  File "/nix/store/m67zrpwmyajrxf0c5c41zd595nynlym1-virt-manager-2.2.1/share/virt-manager/virtinst/install/installer.py", line 491, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/nix/store/mjpn4cw8w8xqq9mc1jwk7yahwdzxxkam-python3.7-libvirt-5.4.0/lib/python3.7/site-packages/libvirt.py", line 3729, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2020-09-12T13:38:19.996252Z qemu-system-x86_64: -drive file=/somepath/nixos.qcow2,format=qcow2,if=none,id=drive-ide0-0-0: Could not reopen file: Permission denied
```

The permissions for the image get changed to: `-r--r--r--  1 root    root  nixos.qcow2`
How do I fix this?

**Comment by wyndon** [comment]
I get the same error, except I'm using `virtualisation.libvirtd.qemu.runAsRoot = false;`, so the permissions of the file are getting changed to `qemu-libvirtd:qemu-libvirtd` instead.

I am part of the `kvm`, `libvirtd` and `qemu-libvirtd` group, if that matters.

I found a temporary fix by adjusting ACL permissions :
```sh
doas setfacl -m u:qemu-libvirtd:rx /home/user
```
However, it seems ACL permissions resets when I apply a new Nix configuration.
```sh
❯ doas getfacl -e /home/wyndon
getfacl: Removing leading '/' from absolute path names
# file: home/wyndon
# owner: wyndon
# group: users
user::rwx
user:qemu-libvirtd:r-x		#effective:r-x <--------- permissions applied
user:nobody:--x			#effective:--x
group::---			#effective:---
mask::r-x
other::---

❯ doas nixos-rebuild test --flake '.#astronaut'
### skipping irrelevant output
setting up /etc...
reloading user units for wyndon...
setting up tmpfiles

❯ doas getfacl -e /home/wyndon
getfacl: Removing leading '/' from absolute path names
# file: home/wyndon
# owner: wyndon
# group: users
user::rwx
user:qemu-libvirtd:r-x		#effective:--- <--------- not effective anymore
user:nobody:--x			#effective:---
group::---			#effective:---
mask::---
other::---
```
System info:
```sh
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.7-xanmod1-tt, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - nixpkgs: `/nix/store/jl396lpnvdhlmcrpd20173dvhf6knn6v-source`
```
