### ISSUE TITLE
graalvm8 fails to build on linux-x86_64

### ISSUE THREAD

**Issue by glittershark** [NixOS/nixpkgs#98256]
**Describe the bug**

building graalvm8 results in:

```
Archiving JVM_PRODUCT_SERVER... [dependencies updated: hotspot]
WARNING: File libjvm.debuginfo for archive hotspot does not exist.
WARNING: File libsaproc.debuginfo for archive hotspot does not exist.
WARNING: File libjsig.debuginfo for archive hotspot does not exist.
Deploying jvmti.h from JVM_PRODUCT_SERVER to /build/source/openjdk1.8.0_265/linux-amd64/product/include
Deploying sa-jdi.jar from JVM_PRODUCT_SERVER to /build/source/openjdk1.8.0_265/linux-amd64/product/lib
Deploying libjvm.so from JVM_PRODUCT_SERVER to /build/source/openjdk1.8.0_265/linux-amd64/product/jre/lib/amd64/server
Deploying libsaproc.so from JVM_PRODUCT_SERVER to /build/source/openjdk1.8.0_265/linux-amd64/product/jre/lib/amd64
Deploying libjsig.so from JVM_PRODUCT_SERVER to /build/source/openjdk1.8.0_265/linux-amd64/product/jre/lib/amd64
Finished Archiving JVM_PRODUCT_SERVER
[Stopped javac-daemon on port 41015 for Java 1.8.0_265 (1.8) from /nix/store/yrd7p07f7y46gcpha3yw22icdc6hhkf9-openjdk-8u265-ga/lib/openjdk]
Shutting down
WARNING: LOOKING FOR: /nix/store/5pl355sksmrbvmb811vdq7bjdzbf684c-mx-5.247.1/bin/mx.mx
WARNING: LOOKING FOR: /build/source/mx.jvmci
[project jdk.vm.ci.hotspot.jfr was removed as dependency JFR is missing]
[project com.oracle.mxtool.junit.jdk9 was removed as JDK 9 is not available]
[jdk.vm.ci.hotspot.jfr was removed from distribution JVMCI_HOTSPOT]
[com.oracle.mxtool.junit.jdk9 was removed from distribution JUNIT_TOOL]
Traceback (most recent call last):
  File "/nix/store/5pl355sksmrbvmb811vdq7bjdzbf684c-mx-5.247.1/bin/internal_mx.py", line 19173, in <module>
    main()
  File "/nix/store/5pl355sksmrbvmb811vdq7bjdzbf684c-mx-5.247.1/bin/internal_mx.py", line 19154, in main
    retcode = c(command_args)
  File "/nix/store/5pl355sksmrbvmb811vdq7bjdzbf684c-mx-5.247.1/bin/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/build/source/mx.jvmci/mx_jvmci.py", line 1067, in run_vm
    jdk = get_jvmci_jdk(vmbuild=vmbuild)
  File "/build/source/mx.jvmci/mx_jvmci.py", line 1613, in get_jvmci_jdk
    jdk = JVMCI8JDKConfig(vmbuild)
  File "/build/source/mx.jvmci/mx_jvmci.py", line 1562, in __init__
    mx.JDKConfig.__init__(self, jdkDir, tag=_JVMCI_JDK_TAG)
  File "/nix/store/5pl355sksmrbvmb811vdq7bjdzbf684c-mx-5.247.1/bin/internal_mx.py", line 12580, in __init__
    raise JDKConfigException('{}: {}'.format(e.returncode, e.output))
__main__.JDKConfigException: 1: Error occurred during initialization of VM
Unable to load native library: /build/source/openjdk1.8.0_265/linux-amd64/product/jre/lib/amd64/libjava.so: undefined symbol: JVM_BeforeHalt, version SUNWprivate_1.1

builder for '/nix/store/vbsbmmb3nphgppj16nq0p3n8b8bpplzb-jvmci-19.3-b05.drv' failed with exit code 1
```

**To Reproduce**

```
nix-build -A graalvm8
````

**Expected behavior**

A successful build

**Screenshots**

**Additional context**

**Notify maintainers**

@volth @hlolli

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.15-ck1, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- graalvm8
# a list of nixos modules affected by the problem
module:
```

**Comment by glittershark** [comment]
Currently bisecting this - last commit *I* know that this built at was e23f530858308b9248cfaffb4b99966c0545d4f2

**Comment by glittershark** [comment]
0afe6a282a52054fbedec9d262b32ddb066271e2 appears to be the first bad commit here

**Comment by hlolli** [comment]
This is annoying. I'm not sure how's best to move forward on this. There are 2 open PR's for updates, mine which compiles graalvm from sources is still WIP, the other one patches the prebuilt ones but has some bugs and I'm not sure what the status on that one is.

**Comment by doronbehar** [comment]
Did you try using jdk 14? jdk 8 is unmaintained . See also https://github.com/NixOS/nixpkgs/pull/89731 .

**Comment by doronbehar** [comment]
Still an issue: https://gist.github.com/073fac8aab5bce89466bc0892ea360ed

**Comment by doronbehar** [comment]
graalvm8 was removed from nixpkgs.
