### ISSUE TITLE
asciidoctor missing Ascii85

### ISSUE THREAD

**Issue by TomOnTime** [NixOS/nixpkgs#98638]
**Describe the bug**
asciidoctor crashes after not being able to find Ascii85.

**To Reproduce**
1. `nix-env -i asciidoctor`
2. create a simple file (book.adoc)
3. `asciidoctor book.adoc`

**Expected behavior**
Compiles book.adoc

**Screenshots**

This is what happens instead:

```
$ asciidoctor book.adoc
Traceback (most recent call last):
	9: from /Users/tlimoncelli/.nix-profile/bin/asciidoctor:18:in `<main>'
	8: from /nix/store/9csvs84kjgnxij78m0rhp53il8sjz5a1-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
	7: from /nix/store/9csvs84kjgnxij78m0rhp53il8sjz5a1-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
	6: from /nix/store/9csvs84kjgnxij78m0rhp53il8sjz5a1-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
	5: from /nix/store/9csvs84kjgnxij78m0rhp53il8sjz5a1-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
	4: from /nix/store/9csvs84kjgnxij78m0rhp53il8sjz5a1-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
	3: from /nix/store/9csvs84kjgnxij78m0rhp53il8sjz5a1-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
	2: from /nix/store/9csvs84kjgnxij78m0rhp53il8sjz5a1-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
	1: from /nix/store/9csvs84kjgnxij78m0rhp53il8sjz5a1-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
/nix/store/9csvs84kjgnxij78m0rhp53il8sjz5a1-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find Ascii85-1.0.3 in any of the sources (Bundler::GemNotFound)
```

**Additional context**

Here is a minimal reproduction case:  (filename book.adoc)

```
= Default Yes
:doctype: article
:author: Author McAuthor
:sectnums:
:toc:


== first chapter

This is a sentence.
```

**Notify maintainers**

@gpyh @nicknovitski

**Metadata**

 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(tlimoncelli): `"nixpkgs-21.03pre243895.72b9660dc18"`
 - nixpkgs: `/Users/tlimoncelli/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by zarelit** [comment]
@TomOnTime do you happen to have a global BUNDLE_PATH set? i.e.  is this related to https://github.com/NixOS/nixpkgs/issues/85989#issuecomment-663866102 ?
