### ISSUE TITLE
gstreamer 1.18.0: Build documentation?

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#98769]
I'm trying to update derivations in the `gst_all_1` attribute path. Apparantly, for documentation, the "core" plugin needs a new package `hotdoc` - https://github.com/NixOS/nixpkgs/pull/98767 . But even with it, a configure error appears:

```
Program hotdoc found: YES
Program hotdoc found: YES (/nix/store/4p6l8l5z1h4rh1zd7hlcrhcxcz136slr-hotdoc-0.12.2/bin/hotdoc)

docs/meson.build:60:12: ERROR: Problem encountered: Documentation enabled but gi-extension missing
```

Hotdoc supposed to have builtin extensions according to: https://hotdoc.github.io/extensions.html

And:

```
nix-store --read-log $(nix-build --no-out-link -A hotdoc) | grep extensions/gi/
```

(When run with https://github.com/NixOS/nixpkgs/pull/98767 merged, or from [this branch](https://github.com/doronbehar/nixpkgs/tree/pkg/gst_all_1/dirty)).

My work is in https://github.com/doronbehar/nixpkgs/blob/pkg/gst_all_1/dirty/pkgs/development/libraries/gstreamer/core/default.nix#L52-L53 

cc @ttuegel @matthewbauer .

**Comment by jtojnar** [comment]
Yeah, the gi extension looks like it needs flex (see setup.py). We should probably set `HOTDOC_BUILD_C_EXTENSION` environment variable to `enabled`.

**Comment by doronbehar** [comment]
You were right that was it.

**Comment by doronbehar** [comment]
There's some outputs issues:

In my current pkg/gst_all_q/dirty branch, the gstreamer build fails at the end with:

```
er-1.18.0-dev
shrinking /nix/store/rgz3pgnxniq1mxc27nrhca55b805c767-gstreamer-1.18.0-dev/bin/.gst-inspect-1.0-wrapped
shrinking /nix/store/rgz3pgnxniq1mxc27nrhca55b805c767-gstreamer-1.18.0-dev/bin/.gst-launch-1.0-wrapped
shrinking /nix/store/rgz3pgnxniq1mxc27nrhca55b805c767-gstreamer-1.18.0-dev/bin/.gst-stats-1.0-wrapped
shrinking /nix/store/rgz3pgnxniq1mxc27nrhca55b805c767-gstreamer-1.18.0-dev/bin/.gst-tester-1.0-wrapped
shrinking /nix/store/rgz3pgnxniq1mxc27nrhca55b805c767-gstreamer-1.18.0-dev/bin/.gst-typefind-1.0-wrapped
gzipping man pages under /nix/store/rgz3pgnxniq1mxc27nrhca55b805c767-gstreamer-1.18.0-dev/share/man/
strip is /nix/store/p792j5f44l3f0xi7ai5jllwnxqwnka88-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/rgz3pgnxniq1mxc27nrhca55b805c767-gstreamer-1.1
8.0-dev/lib  /nix/store/rgz3pgnxniq1mxc27nrhca55b805c767-gstreamer-1.18.0-dev/bin
patching script interpreter paths in /nix/store/rgz3pgnxniq1mxc27nrhca55b805c767-gstreamer-1.18.0-dev
checking for references to /build/ in /nix/store/rgz3pgnxniq1mxc27nrhca55b805c767-gstreamer-1.18.0-dev..
.
find: '/nix/store/dgmm32a33kbkfn5ph0vhq6x3mvxrwsi2-gstreamer-1.18.0-devdoc': No such file or directory
strip is /nix/store/p792j5f44l3f0xi7ai5jllwnxqwnka88-binutils-2.31.1/bin/strip
builder for '/nix/store/1a6saqp68kskr6545q8iaqvgg80sjrc3-gstreamer-1.18.0.drv' failed to produce output
```

Without a `devdoc` output, the following tree is the result:

<details>

```
$ tree $(nix-build --no-out-link -A gst_all_1.gstreamer)
/nix/store/j7c92v6lz83864zxd0yizlqagr28ally-gstreamer-1.18.0
├── lib
│   ├── girepository-1.0
│   │   ├── Gst-1.0.typelib
│   │   ├── GstBase-1.0.typelib
│   │   ├── GstCheck-1.0.typelib
│   │   ├── GstController-1.0.typelib
│   │   └── GstNet-1.0.typelib
│   ├── gstreamer-1.0
│   │   ├── libgstcoreelements.so
│   │   └── libgstcoretracers.so
│   ├── libgstbase-1.0.so -> libgstbase-1.0.so.0
│   ├── libgstbase-1.0.so.0 -> libgstbase-1.0.so.0.1800.0
│   ├── libgstbase-1.0.so.0.1800.0
│   ├── libgstcheck-1.0.so -> libgstcheck-1.0.so.0
│   ├── libgstcheck-1.0.so.0 -> libgstcheck-1.0.so.0.1800.0
│   ├── libgstcheck-1.0.so.0.1800.0
│   ├── libgstcontroller-1.0.so -> libgstcontroller-1.0.so.0
│   ├── libgstcontroller-1.0.so.0 -> libgstcontroller-1.0.so.0.1800.0
│   ├── libgstcontroller-1.0.so.0.1800.0
│   ├── libgstnet-1.0.so -> libgstnet-1.0.so.0
│   ├── libgstnet-1.0.so.0 -> libgstnet-1.0.so.0.1800.0
│   ├── libgstnet-1.0.so.0.1800.0
│   ├── libgstreamer-1.0.so -> libgstreamer-1.0.so.0
│   ├── libgstreamer-1.0.so.0 -> libgstreamer-1.0.so.0.1800.0
│   └── libgstreamer-1.0.so.0.1800.0
├── libexec
│   └── gstreamer-1.0
│       ├── gst-completion-helper
│       ├── gst-hotdoc-plugins-scanner
│       ├── gst-plugin-scanner
│       ├── gst-plugins-doc-cache-generator
│       └── gst-ptp-helper
└── share
    ├── gdb
    │   └── auto-load
    │       └── nix
    │           └── store
    │               └── j7c92v6lz83864zxd0yizlqagr28ally-gstreamer-1.18.0
    │                   └── lib
    │                       └── libgstreamer-1.0.so.0.1800.0-gdb.py
    ├── gstreamer-1.0
    │   └── gdb
    │       ├── glib_gobject_helper.py
    │       └── gst_gdb.py
    └── locale
        ├── af
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── ast
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── az
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── be
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── bg
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── ca
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── cs
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── da
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── de
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── el
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── en_GB
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── eo
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── es
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── eu
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── fi
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── fr
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── fur
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── gl
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── hr
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── hu
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── id
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── it
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── ja
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── lt
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── nb
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── nl
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── pl
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── pt_BR
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── ro
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── ru
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── rw
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── sk
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── sl
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── sq
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── sr
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── sv
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── tr
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── uk
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── vi
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        ├── zh_CN
        │   └── LC_MESSAGES
        │       └── gstreamer-1.0.mo
        └── zh_TW
            └── LC_MESSAGES
                └── gstreamer-1.0.mo

97 directories, 71 files
```

</details>

**Comment by doronbehar** [comment]
In fact, I can't see any documentation when `devdoc` output is disabled. Maybe `devdoc` should really be removed.

**Comment by jtojnar** [comment]
Looks like maybe it is not installed intentionally:

https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/e9c99c05ae99aaeb5851524cf5ff9c2eaa4ad902/docs/meson.build#L143

The `hotdoc.generate_doc` calls below are defaulting to `install: false` too if they behave like most other Meson targets. The [module documentation](https://mesonbuild.com/Hotdoc-module.html) is unclear – “Generates documentation using hotdoc and installs it into `$prefix/share/doc/html`.” sounds like it is installed by default but the example still shows explicit `install: true`, which would suggest the opposite.

**Comment by doronbehar** [comment]
Speaking of outputs there might be a benefit to a `man` output?

**Comment by doronbehar** [comment]
And also @jtojnar what do you think about the double prefix in the gdb path in the result tree. See my previous previous comment https://github.com/NixOS/nixpkgs/issues/98769#issuecomment-699023002 .

**Comment by jtojnar** [comment]
`gtk-doc` generates documentation to `share/gtk-doc` which is [moved to `${!outputDevdoc}`](https://github.com/NixOS/nixpkgs/blob/b8883134be4dd088116267556a5152cdbf7ac61f/pkgs/build-support/setup-hooks/multiple-outputs.sh#L142), which [defaults to `REMOVE`](https://github.com/NixOS/nixpkgs/blob/b8883134be4dd088116267556a5152cdbf7ac61f/pkgs/build-support/setup-hooks/multiple-outputs.sh#L41) when `devdoc` output is not present.

We might want to move the HotDoc directories to `${!outputDevdoc}` but it will be impossible if there is no way to distinguish between development documentation and other stuff installed to `share/doc/html`.

**Comment by jtojnar** [comment]
> Speaking of outputs there might be a benefit to a `man` output?

If the manpages are big, sure. If they are just few kB, :woman_shrugging: 

> And also @jtojnar what do you think about the double prefix in the gdb path in the result tree. See my previous previous comment [#98769 (comment)](https://github.com/NixOS/nixpkgs/issues/98769#issuecomment-699023002) .

That is normal, IIRC.

**Comment by doronbehar** [comment]
Hmm. Isn't it kind of implied that a development library such as gstreamer, is giving a user (development) documentation if there's anything in `${output}/share/doc/html`? I mean, if we'd patch the package to do install the documentation, we could use the `doc` output.

**Comment by doronbehar** [comment]
That didn't work:

```
WARNING(B: [gi-extension]: (missing-gir-include): Couldn't find a gir for Gst-1.0.gir
An unknown error happened while building the documentation and hotdoc cannot recover from it. Please report a bug with this error message and the steps to reproduce it
Traceback (most recent call last):
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/run_hotdoc.py", line 294, in execute_command
    app.run()
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/run_hotdoc.py", line 107, in run
    self.project.setup()
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/core/project.py", line 183, in setup
    extension.setup()
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 190, in setup
    self.__scan_sources()
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 943, in __scan_sources
    self.__scan_node(root)
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 938, in __scan_node
    self.__scan_node(cnode)
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 938, in __scan_node
    self.__scan_node(cnode)
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 913, in __scan_node
    self.__create_structure(GIClassSymbol, node, gi_name)
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 780, in __create_structure
    res = self.__create_class_symbol(node, gi_name,
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 818, in __create_class_symbol
    hierarchy = get_klass_parents(gi_name)
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/node_cache.py", line 115, in get_klass_parents
    __get_parent_link_recurse(parents[0], res)
TypeError: 'dict_keyiterator' object is not subscriptable
FAILED: meson-install
/nix/store/1ivl94srr4rrpdsdzby4mrjwjpv1zx3g-meson-0.55.1/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
builder for '/nix/store/8l5ms4xpf7dvqirvj3w1y04glqk2jg64-gstreamer-1.18.0.drv' failed with exit code 1
error: build of '/nix/store/8l5ms4xpf7dvqirvj3w1y04glqk2jg64-gstreamer-1.18.0.drv' failed
```

The error seems unrelated to the changes:

```patch
diff --git i/pkgs/development/libraries/gstreamer/core/default.nix w/pkgs/development/libraries/gstreamer/core/default.nix
index 94227821254..4935dbdcf91 100644
--- i/pkgs/development/libraries/gstreamer/core/default.nix
+++ w/pkgs/development/libraries/gstreamer/core/default.nix
@@ -24,7 +24,7 @@ stdenv.mkDerivation rec {
   pname = "gstreamer";
   version = "1.18.0";
 
-  outputs = [ "out" "dev" "devdoc" ];
+  outputs = [ "out" "dev" "doc" ];
   outputBin = "dev";
 
   src = fetchurl {
@@ -34,6 +34,10 @@ stdenv.mkDerivation rec {
 
   patches = [
     ./fix_pkgconfig_includedir.patch
+    (fetchpatch {
+      url = "https://gitlab.freedesktop.org/doronbehar/gstreamer/-/commit/61d5c23e0d41884d032b774703c4fdb120acfa40.diff";
+      sha256 = "0m08ppdpkvkya5p65v0flbiqzgj0f76bamxnqdfw8vw6cjxsixj4";
+    })
   ];
 
   nativeBuildInputs = [
```

**Comment by jtojnar** [comment]
I was talking about adding a rule to move the directory to devdoc to multiple-outputs setup hook. That would affect packages other than GStreamer, which could use hotdoc for user documentation. And the directory name sounds pretty generic so other projects could install there to.

Compared to previous GNOME packages that used `share/gtk-doc` for development documentation and `share/yelp` for end-user documentation.

**Comment by jtojnar** [comment]
Is the gir file already installed by the time the docs are being generated? What lookup path does the hotdoc use? Perhaps we need to add `$dev/share` to `XDG_DATA_DIRS` before installation?

**Comment by doronbehar** [comment]
hotdoc c extension still appears as missing, for `gst-plugins-base`:

```
Program hotdoc found: YES
Program hotdoc found: YES (/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/bin/hotdoc)
Configuring gst_api_version.md using configuration
Generating Hotdoc configuration for:  allocators
Generating Hotdoc configuration for:  applib
Generating Hotdoc configuration for:  audio
Generating Hotdoc configuration for:  pbutils
Generating Hotdoc configuration for:  rtplib
Generating Hotdoc configuration for:  rtsplib
Generating Hotdoc configuration for:  sdp
Generating Hotdoc configuration for:  tag
Generating Hotdoc configuration for:  video
Generating Hotdoc configuration for:  gl
Generating Hotdoc configuration for:  gl-egl
Generating Hotdoc configuration for:  gl-x11
Generating Hotdoc configuration for:  gl-wayland

docs/meson.build:166:8: ERROR: Problem encountered: Documentation enabled but c-extension missing

A full log can be found at /build/gst-plugins-base-1.18.0/build/meson-logs/meson-log.txt
builder for '/nix/store/liwb2lv1n9rz743bccpq9hb9d2n4zym3-gst-plugins-base-1.18.0.drv' failed with exit code 1
error: build of '/nix/store/liwb2lv1n9rz743bccpq9hb9d2n4zym3-gst-plugins-base-1.18.0.drv' failed
```

**Comment by doronbehar** [comment]
> Perhaps we need to add $dev/share to XDG_DATA_DIRS before installation?

That didn't, though I haven't tried the `install: true` patch from before.

I've had enough Nixpkgs work for today, so I'll continue tomorrow, hopefully. Most of the updates are committed in https://github.com/doronbehar/nixpkgs/tree/pkg/gst_all_1/dirty/pkgs

**Comment by jtojnar** [comment]
https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/blob/0236fa8b9e87547075d15931c0ac81a86250f862/docs/meson.build#L164-167

we would need to look into how meson/hotdoc implements this.

**Comment by doronbehar** [comment]
Some progress. I applied the `install: true` patch for core gstreamer, and also set `-Ddoc=enabled` meson flag, and:

```
Running custom install script '/build/gstreamer-1.18.0/libs/gst/helpers/ptp_helper_post_install.sh libexec/gstreamer-1.0 capabilities /nix/store/1gqma4lfw8g4p9a6sw8n2a9dd1v4m8nn-libcap-2.27/bin/setcap'
Calling /nix/store/1gqma4lfw8g4p9a6sw8n2a9dd1v4m8nn-libcap-2.27/bin/setcap cap_net_bind_service,cap_net_admin+ep /nix/store/f8ayhlfp20ij0pchs32mli4ysm3cb4zc-gstreamer-1.18.0/libexec/gstreamer-1.0/gst-ptp-helper
unable to set CAP_SETFCAP effective capability: Operation not permitted
Running custom install script '/nix/store/1ivl94srr4rrpdsdzby4mrjwjpv1zx3g-meson-0.55.1/bin/meson --internal hotdoc --install base-doc/html --name base --builddir /build/gstreamer-1.18.0/build/docs /nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/bin/hotdoc run --conf-file base-doc.json'
WARNING(B: [gi-extension]: (missing-gir-include): Couldn't find a gir for Gst-1.0.gir
An unknown error happened while building the documentation and hotdoc cannot recover from it. Please report a bug with this error message and the steps to reproduce it
Traceback (most recent call last):
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/run_hotdoc.py", line 294, in execute_command
    app.run()
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/run_hotdoc.py", line 107, in run
    self.project.setup()
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/core/project.py", line 183, in setup
    extension.setup()
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 190, in setup
    self.__scan_sources()
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 943, in __scan_sources
    self.__scan_node(root)
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 938, in __scan_node
    self.__scan_node(cnode)
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 938, in __scan_node
    self.__scan_node(cnode)
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 913, in __scan_node
    self.__create_structure(GIClassSymbol, node, gi_name)
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 780, in __create_structure
    res = self.__create_class_symbol(node, gi_name,
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/gi_extension.py", line 818, in __create_class_symbol
    hierarchy = get_klass_parents(gi_name)
  File "/nix/store/54k5rw7vn8rz54a2kr6xylwc61fawqwx-hotdoc-0.12.2/lib/python3.8/site-packages/hotdoc/extensions/gi/node_cache.py", line 115, in get_klass_parents
    __get_parent_link_recurse(parents[0], res)
TypeError: 'dict_keyiterator' object is not subscriptable
FAILED: meson-install 
/nix/store/1ivl94srr4rrpdsdzby4mrjwjpv1zx3g-meson-0.55.1/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

I'm considering both contacting gstreamer folks that this `install: ` value should be get the value of `get_option('doc')` or alike. Perhaps we should contact them regarding the hotdoc error as well?

I had a [feeling](https://gitlab.freedesktop.org/gstreamer/gstreamer/blob/220ce9c3fdcc8d85a87936c2a6696044064ecbed/docs/meson.build#L44-45) that downgrading hotdoc to 0.11.0 would help, but it didn't.

**Comment by jtojnar** [comment]
IIRC, they were saying something about using prebuilt docs packages, instead of building docs ourselves.

And the missing git include sounds more like nixpkgs issue, would need to check the hotdoc sources liked in the traceback.

**Comment by doronbehar** [comment]
I've updated this issue's title to keep this issue open only for the sake of documentation.

**Comment by doronbehar** [comment]
I'll close this as it's not such an important issue to keep open, certainly not for me. There's enough info in the initial message to help others try to build the docs from where I stopped.
